### ISSUE TITLE
CoE Starter Kit - PowerBI Desktop Connection Issues

### ISSUE THREAD

**Issue by AravindSivanantham** [microsoft/coe-starter-kit#1015]
### Describe the issue

OrgUrl
Loading blocked by failures with other queries.
Environment
Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
![OrgUrl](https://user-images.githubusercontent.com/88816898/129145734-a5c226e2-b71a-4fab-bb1b-03ae7ba82271.JPG)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_2.2.20210707.3_managed

### What app or flow are you having the issue with?

CoE PowerBI Dashboard OrgUrl connection Issue

### Steps To Reproduce

1. Installed PowerBI Desktop.
2. logged in PowerBI Desktop.
3. entered Organization URL without https and / and signed in.

### Anything else?

![OrgUrl](https://user-images.githubusercontent.com/88816898/129146433-536d65dc-c2d3-4cd6-9501-7ced05c6556d.JPG)
![Sync_issues](https://user-images.githubusercontent.com/88816898/129146443-7209b32d-380e-425d-b24e-9e02394d5018.JPG)

**Comment by manuelap-msft** [comment]
Hello,

please check out the Troubleshooting section for setting up the Power BI Dashboard in our docs: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting

Thank you
Manuela

**Comment by AravindSivanantham** [comment]
Hi Manuelap,
we try to resolve as per suggested but still facing the same problem, we done connectivity test telnet default sql port not listening with respect to OrgUrl attachment added for reference.
 
![Port_Issues](https://user-images.githubusercontent.com/88816898/129172230-30c13293-5ca5-4371-acf1-ae8e5fecc65a.jpg)

Regards
Aravind Sivanantham

**Comment by AravindSivanantham** [comment]
Please help to know SQL  server or client version is need for CoE dashboard

**Comment by manuelap-msft** [comment]
Please see these articles on how to connect to Dataverse from Power BI:
[Connect to Dataverse using the connector in Power BI](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-powerbi-connector#connect-to-dataverse-using-the-connector)
[Limitations us using SQL to query data](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#limitations)
[Troubleshooting connection problems](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#troubleshooting-connection-problems)

You are experiencing a network issue, not an issue with the Power BI Dashboard or CoE Starter Kit. I advise working together with your Power BI or Network admins to solve this.
