### ISSUE TITLE
[CoE Starter Kit - BUG] PowerBI CDSLegacy Aug2021 - Error in embedded apps

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#1016]
### Describe the issue

The power apps "Admin - Access this App" and "Admin - Access this flow" don't works fine.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

CDSLegacy_CoEDashboard_202108.pbit

### Steps To Reproduce

By default this power apps don't be found:
![image](https://user-images.githubusercontent.com/57954993/129173501-8d79fd7b-e9e9-4d73-aabe-1195ac616dfd.png)

If I try to configure them again following the documentation: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi, section: "(Optional) Configure embedded apps in the CoE dashboard" I have this error in the Power App:

![image](https://user-images.githubusercontent.com/57954993/129173863-5a99f5db-a426-4d0e-8f2d-1a3da4cb9e1e.png)

**Comment by manuelap-msft** [comment]
Hello,

it looks like something didn't update correctly! We removed the admin_CoESettings table from the solution, as it is no longer used. The Admin - Access this App and Admin - Access this Flow app no longer refer to admin_CoESettings, see:
![image](https://user-images.githubusercontent.com/55705669/129177155-63b84bdd-c362-4cb7-bbc2-f5e556213f91.png)

1. If you had an unmanaged layer on either of those apps, the latest upgrade would not have updated those apps but left them in their unmanaged state so they may still be using the CoE Settings. You can check for unmanaged layers like this: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates
2. Make sure you only have one version of Admin - Access this App / Flow in the environment, perhaps you've taken a copy at some point or so which could be an older version. 

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Hello,

yes, the correct version contains the time stamp.

The Drillthrough appears when the App ID or Flow ID is part of the table - I think for those two tables maybe the ID is not part of the table. You can add this yourself by adding admin_flowid and admin_appid to those tables on those pages.

Thank you for confirming the new version works for you,
Manuela

**Comment by albertocaa1317** [comment]
Yes, I had done it :(

Cloud flow detail:
![image](https://user-images.githubusercontent.com/57954993/129266540-a1c08c8a-43df-470f-9d5a-43cc481462cc.png)

App detail:
![image](https://user-images.githubusercontent.com/57954993/129266639-abdf412f-5d08-4467-b1bc-664113bff012.png)

**Comment by manuelap-msft** [comment]
That's correct, but in order to drillthrough from the table on the Cloud Flows or Apps page, those tables need to contain the Flow / App ID.

Here's how to add that.
1. Navigate to the Cloud flows page
2. Select the table
3. Add the admin_flowid to the Values 
![image](https://user-images.githubusercontent.com/55705669/129345929-931be6f1-e8c1-46c8-af59-f3d8a0fa6365.png)

**Comment by albertocaa1317** [comment]
I am sorry but this values, admin_flowid and admin_app it already had selected:
![image](https://user-images.githubusercontent.com/57954993/129386581-c0ba24fe-535b-44a7-be3a-c797327d5a4d.png)

**Comment by manuelap-msft** [comment]
And does your Cloud flow Detail page look like this (this is in the Visualization tab under drillthrough):
![image](https://user-images.githubusercontent.com/55705669/129387253-eaa367e9-ce2f-4bef-a4b2-8429a21d3151.png)

**Comment by albertocaa1317** [comment]
OMG!!! This was the problem!!! I don't had the field admin_flowid and admin_appid in this option. How can I don't saw it! Sorry and thanks for your help @manuelap-msft

**Comment by manuelap-msft** [comment]
No worries, this should be included in the shipped version as well so I'll double check to make sure it hasn't fallen out!
