### ISSUE TITLE
[CoE Starter Kit - QUESTION/SUGGESTION] How to audit resources created with trial license?

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#1020]
### Describe the issue

Hi Team,

I have come across the scenario, where the resource's owner has a Power Platform trial license due to which they are unable to perform the "Approve/Reject" operation from the "Approval Email". And eventually, they will keep receiving approval emails. Because CoE Admin can not add user in CoE environment having a trial license and assign approval permission which is one of the prerequisites for the owner to have.

Is there any possibility to avoid sending an email to owners having a trial license? Or probably send a traditional email to the "owner with a trial license" asking to delete the resource from their end?

Can you please guide how to audit such resources?

Thanks,

### Expected Behavior

Need suggestions.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Archive and Clean Up (Start Approval for Apps/Flows)

**Comment by JeneferM-MSFT** [comment]
You should not need to add a user to the environment to use the approvals feature unless you have used a security group to manage access to the CoE, which is something we do not recommend. 

Please see [Security groups and approvals](https://docs.microsoft.com/power-platform/guidance/coe/limitations#security-groups-and-approvals) from our documentation.

**Comment by DiptiC-InsightRun** [comment]
Hi Jenefer,

Thank you for your response!

I confirm that we do not use security groups to secure environments.

As I checked further, the User has no rights on CoE Environment and I was under the impression that to perform "Approve/Reject" operations, the user must be assigned with "Approvals User" rights in the CoE Environment. - If this is not true, I am clear.

However, would you please help clarify why CoE Admin would receive an email with the subject line "App Owner 'UserName' does not have permissions to perform Archive Approval"? 

Thank you for your time in advance!

Best Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
They are automatically added to that security group for you, you dont need to do anything. 

There are a few reasons that a person might not be able to be added, the security group is the most common. Please see this product documentation for others: [assign approvals to any user in your tenant](https://docs.microsoft.com/power-automate/get-started-approvals#assign-approvals-to-any-user-in-your-tenant)

**Comment by JeneferM-MSFT** [comment]
closing out as no further action for the toolkit.
