### ISSUE TITLE
[CoE Starter Kit - BUG] SharePoint Apps changing app id? 

### ISSUE THREAD

**Issue by philipbullard** [microsoft/coe-starter-kit#1022]
### Describe the issue

CLEANUP - Admin |Sync Template V3 (Connection Status)
"Get-App as Admin" failures with App Type "SharepointFormApp"

Have 18 failures of apps ID's that are not found.  Verified through powershell.

When searching on the app name in the admin center, You can find the app, but it has a different AppID

### Expected Behavior

CLEANUP - Admin |Sync Template V3 (Connection Status) . Runs without these failures

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

CLEANUP - Admin |Sync Template V3 (Connection Status)

### Steps To Reproduce

In the "T-Mobile Governance" environment

Open the Center of Excellence - Core Components solution version 2.2.20210707.3

https://us.flow.microsoft.com/manage/environments/19886eb8-9729-4421-9611-5fec7fa1f89a/solutions/066903fe-a8fd-42fd-af7e-35786d5a31c4/flows/8d2037ad-66d1-435e-81fe-a5950acf8202/details?utm_source=solution_explorer

Open Failed Run history and look at failed runs

### Anything else?

https://tmobileusa-my.sharepoint.com/:u:/g/personal/philip_bullard_t-mobile_com/EXZ8rTwl3e1IuR7OO2WN1LQBbQVTZZ_ek8jslvOWhYEp2A?email=v-jemonr%40microsoft.com&e=rRtl6D

**Comment by JeneferM-MSFT** [comment]
thank you for posting with such thorough notes, we will investigate

**Comment by mikefactorial** [comment]
@philipbullard This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
