### ISSUE TITLE
Failed to import Dataverse_CoEDashboard_202107_v2

### ISSUE THREAD

**Issue by AravindSivanantham** [microsoft/coe-starter-kit#1023]
### Describe the issue

Failed to import Dataverse_CoEDashboard_202107_v2, the errors are described below.

**OrgUrl**
Loading blocked by failures with other queries.
**Environment**
Loading blocked by failures with other queries.
**App**
Loading blocked by failures with other queries.
**Flow**
The column 'admin_maker(admin_derivedowner)' of the table wasn't found.
Maker
The column 'admin_numberofpvas' of the table wasn't found.
App Connection Reference
Loading blocked by failures with other queries.
Flow Connection Reference
Loading blocked by failures with other queries.
Audit Log
Loading blocked by failures with other queries.
Connector
Loading blocked by failures with other queries.
Flow Action Details
Loading blocked by failures with other queries.
NonProdWords
Loading blocked by failures with other queries.
Virtual Agent
Loading blocked by failures with other queries.
Virtual Agent Component
Loading blocked by failures with other queries.
Virtual Agent Flows
Loading blocked by failures with other queries.
RPA
Loading blocked by failures with other queries.
RPA Sessions
Loading blocked by failures with other queries.
Power Platform User
Loading blocked by failures with other queries.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

PowerBI CoreComponents_2.2.20210707.3_managed

### What app or flow are you having the issue with?

CoE PowerBI Dashboard OrgUrl connection Issue

### Steps To Reproduce

1. Installed PowerBI Desktop.
2. logged in PowerBI Desktop.
3. entered Organization URL without https and / and signed in.

**Comment by manuelap-msft** [comment]
Hello,

please update to the latest version of the CoE Starter Kit, with the dashboard release 202108. You can download the dashboard from here: https://github.com/microsoft/coe-starter-kit/raw/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Dataverse_CoEDashboard_202108.pbit

Let me know if you continue to face issues!
Manuela

**Comment by AravindSivanantham** [comment]
Hi Manuela,

using the same version as you suggested but still facing the problem.

Regards
Aravind Sivanantham

**Comment by manuelap-msft** [comment]
What solution version of the Core Components solution are you on?

**Comment by AravindSivanantham** [comment]
![image](https://user-images.githubusercontent.com/88816898/129345505-da9a1f5c-0956-4a2e-af03-8f14de08edeb.png)

**Comment by manuelap-msft** [comment]
Hello,

I see, you're on an old version of Core Components (1.98), the current release is 2.75. 

The Core Components solution contains the tables that are used to build the Power BI Dashboard. As we release new versions, we may add new tables, fields and columns to the tables in the solution. You can therefore not upgrade the Dashboard to the July/August version if your Core Components solution is from March - they have to be upgraded together. 

Please upgrade your Core Components solution to the latest version, if you want to use the latest version of the dashboard.

Thank you
Manuela
