### ISSUE TITLE
[CoE Starter Kit - BUG] Failed install of CoE Core Components 2.75

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1024]
### Describe the issue

I started an upgrade of the August release but was not aware of the issue reported in [CoE Starter Kit - AUGUST UPGRADE HOWTO] Dependencies exist which make August upgrade need special steps #1005.
I am now stuck with a failed upgrade solution 2.75 that I am unable to delete. I followed the instructions in #1005 by upgrading in the order specified, but it fails for Core. When i try to delete the CenterofExcellenceCoreComponents_Upgrade it fails with the error: Failed deleting solution. No response received: timeout of 300000ms exceeded (ECONNABORTED)
The information shows:
Error code
80040216
Failed to find connection references with logical name(s) 'admin_CoECoreHTTPAZUREAD'. Please check if connection references exists.

### Expected Behavior

Upgrade from 2.2.20210707.3 to 2.75

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

The whole solution

### Steps To Reproduce

Import Solution
Select Update

I have also tried with Upgrade and Staged Upgrade TNA

**Comment by manuelap-msft** [comment]
Hello,

the Core components solution is rather big, often the UI gives a timeout error whilst the delete is still running. How long has the delete been running for you? I think it sometimes can take 10-20 mins. 

Thank you
Manuela

**Comment by medicineshow** [comment]
Unfortunately no. It fails and stops. I have also tried in the classic window but the same occurs.

**Comment by JeneferM-MSFT** [comment]
Can you please try an overwrite upgrade in the classic UX? 

Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)

Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)

Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png)
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by medicineshow** [comment]
This has also failed

**Comment by JeneferM-MSFT** [comment]
Do you have both the teams version of Core and the regular version of Core installed?

**Comment by medicineshow** [comment]
No. Only the regular version

**Comment by JeneferM-MSFT** [comment]
I'm afraid we are out of ideas then. We did find one local repro of his but the environment accidently had both teams and non-teams versions of core installed. Once we removed the teams version is started to work again. 
You may need to contact support or start with a clean environment.
