### ISSUE TITLE
[CoE Starter Kit - Question] CoE least privilege access

### ISSUE THREAD

**Issue by mgh1066** [microsoft/coe-starter-kit#1025]
We have tested the CoE and looking to  implement in PRD.

Whilst the power platform admin role is required during setup, we do not want to give this to our business owners when using the CoE.    What is the recommended method for giving users of CoE least privilege access whilst maintaining full functionality of the CoE.  Giving our business owners Power Platform Admin isn't really an option.

Any advice would be appreciated

Thanks

Mat

**Comment by manuelap-msft** [comment]
Hello,

what parts of the CoE do you want your business users to use?

Generally,
1. The Sync Flows need to continue running under Power Platform Admin privileges to keep updating your inventory.
2. These flows store data in the Dataverse tables of your environment.
3. All other users only need permission to those Dataverse tables - the Core components solution comes with security roles that you can use for your Admins and Makers as you share apps with them. This will give them access to the app and the underlying data, but no further Admin privileges are required.

Hope that helps,
Manuela

**Comment by mgh1066** [comment]
Turner & Townsend Confidential

Ok thanks I'll get that tested.  As you can imagine we don't want to give all CoE users power platform admin

Regards
Martyn Hewitt
M365 Technical Specialist
Turner & Townsend
Low Hall, Calverley Lane, Horsforth, Leeds, LS18 4GH
www.turnerandtownsend.com<http://www.turnerandtownsend.com/>

Turner & Townsend Limited
Registered office: Low Hall, Calverley Lane, Horsforth, Leeds LS18 4GH, United Kingdom | Registered in England and Wales | Registration No. 06468643

**Comment by manuelap-msft** [comment]
Of course, that's also not the intention of the CoE kit.
