### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Tiles are not loading in latest version (Dataverse_CoEDashboard_202107_v2)

### ISSUE THREAD

**Issue by ragbn** [microsoft/coe-starter-kit#1031]
### Describe the issue

![image](https://user-images.githubusercontent.com/55434468/129435054-75b746cb-ee2c-4592-b527-acf5d80a8610.png)

**Error Message if click on show details**

Feedback Type:
Frown (Error)

Timestamp:
2021-08-14T05:23:13.2662042Z

Local Time:
2021-08-14T15:23:13.2662042+10:00

Session ID:
21be8393-d8d7-44cd-97d7-4399bcc8bd0f

Release:
August 2021

Product Version:
2.96.623.0 (21.08) (x64)

Error Message:
This visual contains one or more filters with deleted columns, type mismatches, or other breaking modeling changes.

OS Version:
Microsoft Windows NT 10.0.19043.0 (x64 en-US)

CLR Version:
4.7 or later [Release Number = 528372]

Peak Virtual Memory:
104 GB

Private Memory:
1.06 GB

Peak Working Set:
1.19 GB

IE Version:
11.789.19041.0

User ID:
80f855ec-b001-4297-acd8-b7397894f27c

Workbook Package Info:
1* - en-GB, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: False.

Telemetry Enabled:
True

Snapshot Trace Logs:
C:\Users\rananjai\Microsoft\Power BI Desktop Store App\FrownSnapShot27f9640c-b866-454a-8bfb-198ec3d44591.zip

Model Default Mode:
Import

Model Version:
PowerBI_V3

Performance Trace Logs:
C:\Users\rananjai\Microsoft\Power BI Desktop Store App\PerformanceTraces.zip

Enabled Preview Features:
PBI_JsonTableInference
PBI_NewWebTableInference
PBI_ImportTextByExample
PBI_ExcelTableInference
PBI_rdlNativeVisual

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_qnaLiveConnect
PBI_azureMapVisual
PBI_dataPointLassoSelect
PBI_compositeModelsOverAS
PBI_dynamicParameters
PBI_enhancedTooltips

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

DPI Scale:
100%

Supported Services:
Power BI

Formulas:

section Section1;

shared OrgUrl = "org8ce595f4.crm6.dynamics.com" meta [IsParameterQuery=true, Type="Any", IsParameterQueryRequired=true];

shared Environment = let
    Source = CommonDataService.Database(OrgUrl),
    admin_environments = Source{[Schema="dbo",Item="admin_environment"]}[Data],
    #"Renamed Columns" = Table.RenameColumns(admin_environments,{{"admin_environmentcreatedon", "Created"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"createdon", "createdby", "modifiedon", "modifiedby", "createdonbehalfby", "modifiedonbehalfby", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "createdbyname", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "ownerid", "owneridname", "owneridyominame", "owningbusinessunit", "owninguser", "owningteam", "statecode", "statecodename", "statuscode", "statuscodename", "importsequencenumber", "overriddencreatedon", "timezoneruleversionnumber", "utcconversiontimezonecode", "processid", "stageid", "traversedpath", "admin_numberofapps", "admin_numberofapps_date", "admin_numberofapps_state", "admin_numberofconnectors", "admin_numberofconnectors_date", "admin_numberofconnectors_state", "admin_numberofflows", "admin_numberofflows_date", "admin_numberofflows_state", "admin_adminreason", "admin_makerrequirementbusinessjustification", "admin_makerrequirementbusinessimpact", "admin_makerrequirementbusinessimpactname", "admin_adminreviewon", "admin_adminmicrosoftteamsenvironmentstatus", "admin_adminmicrosoftteamsenvironmentstatusname", "admin_microsoftteamsid", "admin_microsoftteamsurl", "processsession", "processstage", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team", "admin_app", "admin_connector", "admin_flow", "admin_flowactiondetail", "admin_maker(admin_maker)", "admin_powerplatformuserrole", "admin_pva", "admin_pvacomponent", "admin_rpa", "asyncoperation", "businessunit"})
in
    #"Removed Columns";

shared App = let
     Source = CommonDataService.Database(OrgUrl),
    admin_apps = Source{[Schema="dbo",Item="admin_app"]}[Data],
     #"Invoked Custom Function" = Table.AddColumn(admin_apps, "admin_nonprodappnamecheck", each NonProdNameCheck([admin_displayname])),
    #"Added Custom" = Table.AddColumn(#"Invoked Custom Function", "admin_notmodifiedsincecreated", each if [admin_appmodifiedon] = null 
or 
Duration.TotalMinutes([admin_appmodifiedon]-[admin_appcreatedon])<2 
then 1 
else 0),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"createdon", "createdby", "modifiedon", "modifiedby", "createdonbehalfby", "modifiedonbehalfby", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "ownerid", "owneridname", "owneridyominame", "owningbusinessunit", "owninguser", "owningteam", "statecode", "statecodename", "statuscode", "statuscodename", "importsequencenumber", "overriddencreatedon", "timezoneruleversionnumber", "utcconversiontimezonecode", "processid", "stageid", "traversedpath", "admin_appcomplexitydescription", "admin_appcomplexityscore", "admin_approvalstatus", "admin_approvalstatusname", "admin_category", "admin_categoryname", "admin_inappcatalogname", "admin_inappcatalogfeatured", "admin_inappcatalogfeaturedname", "admin_requirement_1", "admin_requirement_2", "admin_requirement_3", "admin_requirement_4", "admin_requirement_4name", "admin_requirement_5", "admin_requirement_5name", "admin_requirement_6", "admin_requirement_6name", "admin_reviewedapp", "admin_reviewedappname", "admin_riskassessment", "admin_riskassessmentname", "admin_makersubmittedrequirements", "admin_makersubmittedrequirementsname", "admin_dlpviolationdetails", "admin_dlplastevaluationdate", "admin_appusesdataversetablesname", "admin_powerplatformuserrole", "asyncoperation", "businessunit", "processsession", "processstage", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team", "admin_auditlog", "admin_connectionreference", "admin_environment", "admin_maker"})
in
    #"Removed Columns";

shared Flow = let
Source = CommonDataService.Database(OrgUrl),
    admin_flows = Source{[Schema="dbo",Item="admin_flow"]}[Data],
    #"Invoked Custom Function" = Table.AddColumn(admin_flows, "admin_nonprodflowcheck", each NonProdNameCheck([admin_displayname])),
    #"Added Custom" = Table.AddColumn(#"Invoked Custom Function", "admin_notmodifiedsincecreated", each if [admin_flowmodifiedon] = null 
or 
Duration.TotalMinutes([admin_flowmodifiedon]-[admin_flowcreatedon])<2 
then 1 
else 0),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"createdon", "createdby", "modifiedon", "modifiedby", "createdonbehalfby", "modifiedonbehalfby", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "ownerid", "owneridname", "owneridyominame", "owningbusinessunit", "owninguser", "owningteam", "statecode", "statecodename", "statuscode", "statuscodename", "importsequencenumber", "overriddencreatedon", "timezoneruleversionnumber", "utcconversiontimezonecode", "processid", "stageid", "traversedpath", "admin_adminrequirementreviewedflow", "admin_adminrequirementreviewedflowname", "admin_adminrequirementriskassessment", "admin_adminrequirementriskassessmentname", "admin_city", "admin_country", "admin_department", "admin_makerrequirementdependencies", "admin_mitigationplanprovided", "admin_mitigationplanprovidedname", "admin_recordmodified", "admin_requirement_1", "admin_requirement_2", "admin_requirement_2name", "admin_makersubmittedrequirements", "admin_makersubmittedrequirementsname", "admin_connectionreference", "admin_environment", "admin_flowactiondetail", "admin_flowresource", "admin_maker(admin_derivedowner)", "admin_maker(admin_flowcreator)", "admin_powerplatformuserrole", "admin_pvacomponentflowlookup", "asyncoperation", "businessunit", "processsession", "processstage", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team"})
in
    #"Removed Columns";

shared Maker = let
    Source = CommonDataService.Database(OrgUrl),
   admin_makers = Source{[Schema="dbo",Item="admin_maker"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_makers,{"createdon", "createdby", "modifiedon", "modifiedby", "createdonbehalfby", "modifiedonbehalfby", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "ownerid", "owneridname", "owneridyominame", "owningbusinessunit", "owninguser", "owningteam", "statecode", "statecodename", "statuscode", "statuscodename", "importsequencenumber", "overriddencreatedon", "timezoneruleversionnumber", "utcconversiontimezonecode", "admin_photo", "admin_user", "admin_numberofapps", "admin_numberofapps_date", "admin_numberofapps_state", "admin_numberofflows", "admin_numberofflows_date", "admin_numberofflows_state", "admin_username", "admin_useryominame", "admin_numberofpvas", "admin_numberofpvas_date", "admin_numberofpvas_state", "admin_numberofuiflows", "admin_numberofuiflows_date", "admin_numberofuiflows_state", "admin_numberofenvironments", "admin_numberofenvironments_date", "admin_numberofenvironments_state", "admin_numberofcustomconnectors", "admin_numberofcustomconnectors_date", "admin_numberofcustomconnectors_state", "admin_numberofcanvasapps", "admin_numberofcanvasapps_date", "admin_numberofcanvasapps_state", "admin_numberofmodeldrivenapps", "admin_numberofmodeldrivenapps_date", "admin_numberofmodeldrivenapps_state", "admin_numberofsharepointapps", "admin_numberofsharepointapps_date", "admin_numberofsharepointapps_state", "admin_app", "admin_connector", "admin_environment", "admin_flow(admin_makerid)", "admin_flow(admin_makerid) 2", "admin_pva", "admin_rpa", "asyncoperation", "businessunit", "processsession", "systemuser(admin_user)", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team"})
in
    #"Removed Columns";

shared #"App Connection Reference" = let
    Source = CommonDataService.Database(OrgUrl),
    admin_connectionreferences = Source{[Schema="dbo",Item="admin_connectionreference"]}[Data],
    #"Filtered Rows" = Table.SelectRows(admin_connectionreferences, each ([admin_app] <> null)),
    #"Outer Join" = Table.Join(#"Filtered Rows", "admin_connector", Connector, "admin_connectorid"),
    #"Removed Columns" = Table.RemoveColumns(#"Outer Join",{"createdon", "createdby", "modifiedon", "modifiedby", "createdonbehalfby", "modifiedonbehalfby", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "ownerid", "owneridname", "owneridyominame", "owningbusinessunit", "owninguser", "owningteam", "statecode", "statecodename", "statuscode", "statuscodename", "importsequencenumber", "overriddencreatedon", "timezoneruleversionnumber", "utcconversiontimezonecode", "admin_app(admin_app)", "admin_connector(admin_connector)", "admin_flow(admin_flow)", "asyncoperation", "businessunit", "processsession", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team"})
in
    #"Removed Columns";

shared #"Flow Connection Reference" = let
     Source = CommonDataService.Database(OrgUrl),
    admin_connectionreferences = Source{[Schema="dbo",Item="admin_connectionreference"]}[Data],
    #"Filtered Rows" = Table.SelectRows(admin_connectionreferences, each ([admin_flow] <> null)),
    #"Outer Join" = Table.Join(#"Filtered Rows", "admin_connector", Connector, "admin_connectorid"),
    #"Removed Columns" = Table.RemoveColumns(#"Outer Join",{"createdon", "createdby", "modifiedon", "modifiedby", "createdonbehalfby", "modifiedonbehalfby", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "ownerid", "owneridname", "owneridyominame", "owningbusinessunit", "owninguser", "owningteam", "statecode", "statecodename", "statuscode", "statuscodename", "importsequencenumber", "overriddencreatedon", "timezoneruleversionnumber", "utcconversiontimezonecode", "admin_app(admin_app)", "admin_connector(admin_connector)", "admin_flow(admin_flow)", "asyncoperation", "businessunit", "processsession", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team"})
in
    #"Removed Columns";

shared #"Audit Log" = let
     Source = CommonDataService.Database(OrgUrl),
    admin_auditlogs = Source{[Schema="dbo",Item="admin_auditlog"]}[Data],
    #"Duplicated Column" = Table.DuplicateColumn(admin_auditlogs, "admin_creationtime", "admin_creationtime - Copy"),
    #"Calculated Start of Hour" = Table.TransformColumns(#"Duplicated Column",{{"admin_creationtime - Copy", Time.StartOfHour, type datetimezone}}),
    #"Renamed Columns" = Table.RenameColumns(#"Calculated Start of Hour",{{"admin_creationtime - Copy", "admin_creationhour"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each true),
    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"admin_creationtime", type datetime}, {"admin_creationhour", type datetime}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statuscode", "timezoneruleversionnumber", "utcconversiontimezonecode"})
in
    #"Removed Columns";

shared Connector = let
  Source = CommonDataService.Database(OrgUrl),
    admin_connectors = Source{[Schema="dbo",Item="admin_connector"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_connectors,{"createdon", "createdby", "modifiedon", "modifiedby", "createdonbehalfby", "modifiedonbehalfby", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "ownerid", "owneridname", "owneridyominame", "owningbusinessunit", "owninguser", "owningteam", "statecode", "statecodename", "statuscode", "statuscodename", "importsequencenumber", "overriddencreatedon", "timezoneruleversionnumber", "utcconversiontimezonecode", "processid", "stageid", "traversedpath", "admin_adminrequirementreviewedconnector", "admin_adminrequirementreviewedconnectorname", "admin_adminrequirementriskassessment", "admin_adminrequirementriskassessmentname"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"admin_displayname", "admin_connectordisplayname"}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"admin_id", "admin_connectionreference", "admin_environment", "admin_maker(admin_maker)", "asyncoperation", "businessunit", "processsession", "processstage", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team", "admin_usedbyappsnumber", "admin_usedbyappsnumber_date", "admin_usedbyappsnumber_state", "admin_name", "admin_makerrequirementaccessmanagement", "admin_makerrequirementbusinessjustification", "admin_makerrequirementconditionsofuse", "admin_makerrequirementdependencies"})
in
    #"Removed Columns1";

shared #"Flow Action Details" = let
     Source = CommonDataService.Database(OrgUrl),
    admin_auditlogs = Source{[Schema="dbo",Item="admin_auditlog"]}[Data],
    #"Duplicated Column" = Table.DuplicateColumn(admin_auditlogs, "admin_creationtime", "admin_creationtime - Copy"),
    #"Calculated Start of Hour" = Table.TransformColumns(#"Duplicated Column",{{"admin_creationtime - Copy", Time.StartOfHour, type datetimezone}}),
    #"Renamed Columns" = Table.RenameColumns(#"Calculated Start of Hour",{{"admin_creationtime - Copy", "admin_creationhour"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each true),
    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"admin_creationtime", type datetime}, {"admin_creationhour", type datetime}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statuscode", "timezoneruleversionnumber", "utcconversiontimezonecode"})
in
    #"Removed Columns";

shared NonProdWords = let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCnENDlGK1QExfAPADN9KMOWSmpsPZjjnF1Qq5KeB2boxpQYGxqlgdnBibkEOkBkLAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Label = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Label", type text}})
in
    #"Changed Type";

shared NonProdNameCheck = let
    BadWordMatch = (AppName) =>
    let WordList = Table.Column(NonProdWords,"Label"),
    Matchlist = List.Transform(WordList, each Text.Contains(Text.Lower(AppName), Text.Lower(_))),
    TrueMatches = List.AnyTrue(Matchlist),
    Score = if TrueMatches then 1 else 0
    in Score
in
    BadWordMatch;

shared #"Virtual Agent" = let
   Source = CommonDataService.Database(OrgUrl),
    admin_pvas = Source{[Schema="dbo",Item="admin_pva"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_pvas,{"admin_adminrequirementreviewedbot", "admin_adminrequirementriskassessment", "admin_makerrequirementaccessmanagement", "admin_makerrequirementbusinessimpact", "admin_makerrequirementbusinessjustification", "admin_makerrequirementdependencies", "admin_makersubmittedrequirements", "admin_mitigationplanprovided", "createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "processid", "stageid", "statecode", "statuscode", "timezoneruleversionnumber", "traversedpath", "utcconversiontimezonecode", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "owneridname", "owneridyominame", "statecodename", "statuscodename", "admin_environment", "admin_maker", "admin_pvacomponent", "asyncoperation", "businessunit", "processsession", "processstage", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team"})
in
    #"Removed Columns";

shared #"Virtual Agent Component" = let
  Source = CommonDataService.Database(OrgUrl),
    admin_pvacomponents = Source{[Schema="dbo",Item="admin_pvacomponent"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_pvacomponents,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statuscode", "timezoneruleversionnumber", "utcconversiontimezonecode", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "owneridname", "owneridyominame", "statecodename", "statuscodename", "admin_environment", "admin_pva", "admin_pvacomponentflowlookup", "asyncoperation", "businessunit", "processsession", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team"})
  
in
    #"Removed Columns";

shared #"Virtual Agent Flows" = let
  Source = CommonDataService.Database(OrgUrl),
    admin_pvacomponentflowlookups = Source{[Schema="dbo",Item="admin_pvacomponentflowlookup"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_pvacomponentflowlookups,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statuscode", "timezoneruleversionnumber", "utcconversiontimezonecode", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "owneridname", "owneridyominame", "statecodename", "statuscodename", "admin_flow(admin_flow)", "admin_pvacomponent(admin_pvacomponent)", "asyncoperation", "businessunit", "processsession", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team"})
   
in
    #"Removed Columns";

shared RPA = let
Source = CommonDataService.Database(OrgUrl),
    admin_rpas = Source{[Schema="dbo",Item="admin_rpa"]}[Data],
    #"Added Custom" = Table.AddColumn(admin_rpas, "admin_notmodifiedsincecreated", each if [[admin_rpamodifiedon]] = null 
or 
Duration.TotalMinutes([admin_rpamodifiedon]-[admin_rpacreatedon])<2 
then 1 
else 0),
    #"Invoked Custom Function" = Table.AddColumn(#"Added Custom", "admin_nonprodappnamecheck", each NonProdNameCheck([admin_displayname])),
    #"Removed Columns" = Table.RemoveColumns(#"Invoked Custom Function",{"admin_adminrequirementreviewedrpa", "admin_adminrequirementriskassessment", "admin_clientdatajson", "admin_makerrequirementbusinessimpact", "admin_makerrequirementbusinessjustification", "admin_makerrequirementdependencies", "admin_makersubmittedrequirements", "admin_mitigationplanprovided", "createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statuscode", "timezoneruleversionnumber", "utcconversiontimezonecode", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "owneridname", "owneridyominame", "statecodename", "statuscodename", "admin_environment", "admin_maker", "admin_rpasessions", "asyncoperation", "businessunit", "processsession", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team"})
in
    #"Removed Columns";

shared #"RPA Sessions" = let
 Source = CommonDataService.Database(OrgUrl),
    admin_rpasessionses = Source{[Schema="dbo",Item="admin_rpasessions"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_rpasessionses,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statuscode", "timezoneruleversionnumber", "utcconversiontimezonecode", "createdbyname", "createdbyyominame", "createdonbehalfbyname", "createdonbehalfbyyominame", "modifiedbyname", "modifiedbyyominame", "modifiedonbehalfbyname", "modifiedonbehalfbyyominame", "owneridname", "owneridyominame", "statecodename", "statuscodename", "admin_rpa(admin_rpa)", "asyncoperation", "businessunit", "processsession", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team"})
    
in
    #"Removed Columns";

shared #"Power Platform User" = let
Source = CommonDataService.Database(OrgUrl),
    admin_powerplatformusers = Source{[Schema="dbo",Item="admin_powerplatformuser"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_powerplatformusers,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statuscode", "timezoneruleversionnumber", "utcconversiontimezonecode"})
in
    #"Removed Columns";

### Expected Behavior

Power BI dashboard should load data

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_2.2.20210707.3

### What app or flow are you having the issue with?

Power BI

### Steps To Reproduce

1. Deploy core component 
2. Deploy Audi Component 
3. Try loading the Power BI dashboard on Power BI desktop

**Comment by sharmakhilesh** [comment]
I have the same kind  of issue, any update on this?

**Comment by manuelap-msft** [comment]
Hello,

you are using an older version of the Power BI dashboard, please update to using the *_CoEDashboard_202108 version: https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Dataverse_CoEDashboard_202108.pbit

Thank you
Manuela

**Comment by sharmakhilesh** [comment]
I used Dataverse_CoEDashboard_202107_v2.pbit file from latest CoE kit.

**Comment by manuelap-msft** [comment]
Then please upgrade to https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/CDSLegacy_CoEDashboard_202108.pbit

**Comment by sharmakhilesh** [comment]
Thanks Manuela, it works now, But still I am not able to see the option to archive my app/flow from PowerBI, and don't know where my App/Flow will be save after archive.

**Comment by JeneferM-MSFT** [comment]
There is no archival that the toolkit performs. The toolkit only tells the object owner to perform the backup (the archival)

**Comment by sharmakhilesh** [comment]
![image](https://user-images.githubusercontent.com/69086761/129558067-1d358ed1-215f-47a0-96b6-34e7a156f366.png)

I am referring https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern .

**Comment by manuelap-msft** [comment]
This is an outdated screenshot, and the Archive functionality has been removed.

You can see in the description that Archive is not called out as functionality of the app:
![image](https://user-images.githubusercontent.com/55705669/129579146-d602df38-e65b-4b0f-ae19-26010a90a3c4.png)

I have added a task for us to update the docs with newer screenshots.

Thank you
Manuela
