### ISSUE TITLE
[CoE Starter Kit - BUG] Cloud flow "Env Request | Create approved environment" doesn't work

### ISSUE THREAD

**Issue by jukkan** [microsoft/coe-starter-kit#1032]
### Describe the issue

Using the new environment management features in August 2021 release, I discovered 4 modifications that I had to perform to the flow "Env Request | Create approved environment" to make it successfully run through.

1. Step "Update Environment with security group": the input parameter for Environment is incorrect. Instead of this:

"environment": "@triggerOutputs()?['body/_coe_environment_value']"

I had to use this:

 "environment": "@triggerOutputs()?['body/coe_envdisplayname']"

2. Step "Update  a row - DLP Policy Change Request": the parameter for Environment is incorrect. It is using just the dynamic GUID of the environment, when in order to populate a Dataverse lookup field I had to use the format admin_environments(INSERT_DYNAMIC_GUID_HERE).

3. Step "Condition - Expiration date": the parameter for the condition is incorrect. It is using the display name string value "Yes" of the field "Has expiration date", when in order to compare the Dataverse Yes/No field value correctly I had to change it to the true expression.

4. Step "Send an email (V2)" at the end of the flow is using an invalid variable for the "To" field. In my tests, the variable "varEndAdmins" gets a value that has two times the same email address concatenated. For example: "user@domain.comuser@domain.com". Instead I ended up using the field "Primary Email" from the step "Get a row by ID - requestor user" as the "To" field value to get a single valid email address string for the environment's admin user.

### Expected Behavior

The cloud flow should complete successfully when given a valid values via the Power Platform Request Center app and Power Platorm Resource Request Management System app for an Environment Creation Request record.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Center of Excellence - Core Components for Teams 2.3

### What app or flow are you having the issue with?

Env Request | Create approved environment

### Steps To Reproduce

1. Request an environment with a database, expiration date, security group.
2. Approve the request and associate a DLP policy with it that results in a DLP Policy Change Request
3. The flow "Env Request | Create approved environment" will successfully create the environment but fail to complete.
4. First it will fail on "Condition - Security Group ID".
5. After applying fix 1, then it will fail on "Apply to each - DLP Policy Change Request"
6. After applying fix 2, then it will give an incorrect result in the evaluation of "Condition - Expiration date"
7. Simultaneously, it will fail on "Send an email (V2)"

**Comment by denisem-msft** [comment]
@jukkan thanks for your detailed feedback. I've attached the updated the solution, can you please test the updated solution to confirm the issues are resolved?

[CenterofExcellenceCoreComponents_2_77_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7017910/CenterofExcellenceCoreComponents_2_77_managed.zip)

**Comment by jukkan** [comment]
Thanks, @denisem-msft ! Would you happen to also have the Teams version of this updated core solution? The environment where I tested this process is deployed in Dataverse for Teams, so I probably can't use this package to get the updated flow...

**Comment by mikefactorial** [comment]
@jukkan This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
