### ISSUE TITLE
[CoE Starter Kit - QUESTION] how restore apps and flows deleted via archival flows

### ISSUE THREAD

**Issue by sharmakhilesh** [microsoft/coe-starter-kit#1033]
### Describe the issue

Hi Team,

  I run the archival flow to archive the Apps and Flows, but it archived my working apps, How and Where do I revert back my Archive Apps and Flows? 

### Expected Behavior

I want that I can move my Apps and Flows from archive to original location. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

CenterofExcellenceCoreComponents_2.2.20210707.3_managed

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2

**Comment by JeneferM-MSFT** [comment]
Hello. The archival referenced here is for the users themselves to do. The toolkit does not do an archival. I believe there are ways to restore apps and flows if you contact support, but no way via the product ux. 

The only way these would get removed is if the person approves the removal though.

**Comment by JeneferM-MSFT** [comment]
[deleted power apps](https://powerusers.microsoft.com/t5/Building-Power-Apps/Deleted-application/td-p/264820)
[deleted power automate flows](https://powerusers.microsoft.com/t5/General-Power-Automate/How-to-restore-deleted-flows/m-p/735803#M60253)

**Comment by JeneferM-MSFT** [comment]
closing out as this is not a toolkit issue.

**Comment by sharmakhilesh** [comment]
Hi Jenefer,

Thanks for respoding, but as per following URL, there is option to archive the app which I cant see it. 

![image](https://user-images.githubusercontent.com/69086761/129557058-6244a357-4587-4b27-92ea-30e28a796e05.png)


https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern

**Comment by sharmakhilesh** [comment]
Hi,

I already send some comments on issue, please review it.



***@***.***<https://www.ecleva.com/>

Level 9, Suite 12, 100 Walker St.
North Sydney 2060
www.ecleva.com<http://www.ecleva.com/>

Akhilesh Sharma
Infrastructure Manager
+91 982 446 0130<tel:+91%20982%20446%200130>|+61 2 9467 9300<tel:+61%202%209467%209300>/305
***@***.******@***.***>

[Picture1]<https://www.linkedin.com/in/directorecleva-akhilesh/>


 ***@***.*** <https://www.linkedin.com/company/ecleva/>   ***@***.*** <https://twitter.com/ECLEVA1>   ***@***.*** <https://www.youtube.com/channel/UC6vednoc-Y5z9QoYP7fWdyw/videos>   ***@***.*** <https://www.facebook.com/ecleva>
Disclaimer: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please reply to this message and follow with its deletion. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by JeneferM-MSFT** [comment]
Hello. There are no features in which the toolkit does the archive. All archival is done by the end user.
