### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI file fails to load (References to other queries)

### ISSUE THREAD

**Issue by highsmithjd** [microsoft/coe-starter-kit#1035]
### Describe the issue

We have successfully imported the core components of the CoE, run the flows, and set up the Audit connector. Next step was to setup PowerBI. When I (owner of the CoE environment, with a Power Apps per user license) try to connect to the Environment URL in PowerBI i get the following error. Any ideas?

![PowerBIerror](https://user-images.githubusercontent.com/49718142/129574974-408803b7-4b8d-47ef-9b85-1ef7c4778bcd.PNG)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

PowerBI - Flow Connector Reference

**Comment by highsmithjd** [comment]
I just installed Power BI Desktop for the first time today. I assume it's the latest version. In the About section it shows Version: 2.96.701.0 64-bit (August 2021)

**Comment by manuelap-msft** [comment]
Ok, thank you! I will need to investigate then. On my development machine I have the July 2021 version and don't see this issue.

**Comment by highsmithjd** [comment]
I am the owner of the CoE Environment but i did not make the connections during the solution import or the Audit connector setup. Not sure that matters with the Power BI portion of the setup

**Comment by manuelap-msft** [comment]
That shouldn't matter, as long as you have access to the environment and all the tables in it!

**Comment by highsmithjd** [comment]
I'm in the system administrator role too

**Comment by highsmithjd** [comment]
This was fixed. Somehow the connection for the Audit Connector disappeared and we had to reconnect. Not sure why. No one changed their password or anything. Fixed the connection, ran the audit flows again successfully, then Power BI connected and displayed information

**Comment by manuelap-msft** [comment]
Amazing, thank you for letting me know! Glad to hear it's working now!

Thanks for using the CoE
Manuela
