### ISSUE TITLE
Center of Excellence - Core Components -upgrade Issue

### ISSUE THREAD

**Issue by AravindSivanantham** [microsoft/coe-starter-kit#1037]
### Describe the issue

**Try to upgrade from 1.98 to 2.75**
![Upgrade_issues](https://user-images.githubusercontent.com/88816898/129580930-2bfcf425-e2ba-49bb-a375-a681d2d96fce.jpg)

Upgrading solution failed. Solution dependencies exist, cannot uninstall. DependencyCount : 7 RequiredComponentObject details: Type: connectionreference,
 ObjectName: admin_Office365GroupsCoEConnection, Id: 5e7e8d0b-675a-4cb9-b76b-b86b625eadbb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Welcome Email, Id: 18c1f53d-8d87-e911-a860-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEConnection, Id: ed9a81e6-04b3-4ffa-a78f-f7c0b6e9f895, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: e68f1ca0-339b-44ab-9507-f9dafa1b02d5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Welcome Email, Id: 18c1f53d-8d87-e911-a860-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: e68f1ca0-339b-44ab-9507-f9dafa1b02d5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Reminder 3 days prior event, Id: bc9a9f1a-afe6-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: e68f1ca0-339b-44ab-9507-f9dafa1b02d5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Newsletter with Product Updates, Id: e7a96786-c7e5-e911-a860-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: e68f1ca0-339b-44ab-9507-f9dafa1b02d5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Feedback Reminder, Id: 2c42d11c-afe6-e911-a860-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: e68f1ca0-339b-44ab-9507-f9dafa1b02d5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Registration Confirmation, Id: bdd94919-afe6-e911-a85c-000d3a372ab9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_2.2.20210707.3_managed

### What app or flow are you having the issue with?

CoE upgrade

### Steps To Reproduce

![upgrade](https://user-images.githubusercontent.com/88816898/129582577-2d03d2a1-916a-48ff-aa01-8ae4893aee07.jpg)

**Comment by manuelap-msft** [comment]
Please try to use Update instead of Upgrade, as called out here #1005

**Comment by AravindSivanantham** [comment]
Thanks Manuelap, its got updated but i seen two components which one to keep 
![Core_Components](https://user-images.githubusercontent.com/88816898/129593408-0583974d-9930-4d9e-9f76-861c34213357.png)

**Comment by manuelap-msft** [comment]
The one called CenterofExcelelnceCoreComponents has the version 2.75 which is the latest version, showing that the update has succeeded.

The _Upgrade is from the failed Upgrade. You should be able to safely delete this.

**Comment by Aparna-Mutalik** [comment]
Hi,

We tried to upgrade our COE toolkit(core components solution) and we got below error:

Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade

Based on the above issue, we tried to update the solution. Now we are getting below error:

Solution "Center of Excellence - Core Components" failed to import: Solution manifest import: FAILURE: Holding solution CenterofExcellenceCoreComponents_Upgrade exists. Cannot update solution.

now we have two core solutions in the environment with old and new version. Could you please let us know how to proceed further on this.

**Comment by manuelap-msft** [comment]
Hello @Aparna-Mutalik

please raise a new issue for this, filling out all mandatory information: https://github.com/microsoft/coe-starter-kit/issues/new?assignees=Jenefer-Monroe&labels=coe-starter-kit%2Cbug&template=1-coe-starter-kit-bug.yml&title=%5BCoE+Starter+Kit+-+BUG%5D+ISSUE+TITLE

We are unable to monitor issues closed in August last year, as we've had many releases since then! You'll have to provide all information in the issue template so we can triage the issue.

Manuela
