### ISSUE TITLE
[CoE Starter Kit - BUG] Last Launched date in Power BI dashboard is months old

### ISSUE THREAD

**Issue by ValleRLess** [microsoft/coe-starter-kit#1046]
### Describe the issue

I've been trying to figure out why the Last Launched date in the Power Platform Admin Dashboard for Power Apps has not updated since 4/23/2021. I’ve noticed the same with the connectors, and probably Flows are the same.
I recently noticed the Office 365 Management API connected needed to be Fixed. I fixed it last month and set the timeout expiration to 2 years.

They Apps and Flows seem to be ok, except for the one below, but I’m not sure what is the one causing the issues. The one failing is Admin | Sync Template v3 (Apps). It’s saying it can’t find the application “b1e5fa67-4348-453f-b35b-3608bb7816d4” in the default instance.

### Expected Behavior

I would expect that when I look at the Apps reports (Left Hand Nav) running on the Admin Dashboard the days would be more recent. I need to track activity, and they are not updating.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

### Steps To Reproduce

Launch Power BI. 
Go to the PowerPlatformAdminDashboard.
On the left hand navigation, click on Apps.
On the table at the bottom of the page, the last column is Last Launched. Mine all show a date of 4/23/2021 and earlier.
![LastModified](https://user-images.githubusercontent.com/89102781/129814414-c2ee5570-60a1-4475-9274-cbee313c4141.PNG)

**Comment by JeneferM-MSFT** [comment]
Can you please go validate that the audit logs flows are running and passing? Most likely they have stopped running due to the connection getting broken, perhaps when you upgraded or with an Azure outage. 
Note that current versions of the toolkit will send an email to the admin when the audit log flows fail.

**Comment by ValleRLess** [comment]
Hi Jenefer,

I wasn’t able to find the Admin | Sync Audit Logs flow in the CoE environment. I went to the Admin Center, click on the CoE environment and then click on the Flows in the resources area. The Audit log flow was disabled.

Can you guide me on how to get to the actual list of Admin flows so I can check them and make sure this one will trigger correctly? Thanks.

***@***.***

***@***.***

Ricardo Vallecillo | Principal Solution Engineer, Enterprise Technology Partners (ETP) | Southern Glazer’s Wine & Spirits | c: 954-699-1491  | ***@***.******@***.***>
Southern Glazer’s Wine & Spirits reminds you to drink responsibly. Please consider the environment before printing this email.

**Comment by JeneferM-MSFT** [comment]
The audit logs solution should be installed in the same environment as core. So if you go to  [https://make.powerapps.com/](https://make.powerapps.com/) > chose your CoE environment > Solutions 

You should see at least Core and Audit Logs there. Here are the [audit logs setup instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog) in case you need to redo some of that work. 
![image](https://user-images.githubusercontent.com/62659043/129988872-b36fcc44-bcf4-4b03-a2a3-d090112ce9dc.png)

**Comment by JeneferM-MSFT** [comment]
closing out as it seems the issue was that the flow was not enabled or running.
