### ISSUE TITLE
[CoE Starter Kit - BUG] After an upgrade Flows have an error

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1047]
### Describe the issue

When testing a flow for the first time after upgrading, the error "The XRM workflow table row could not be found" appears. I am experiencing this error on a number of flows after the upgrade. this particular error is from the [Child] Admin | Sync Logs which is part of the Audit Logs Solution but it is also evident on a number of other flows.
![image](https://user-images.githubusercontent.com/17124284/129875225-aefc4eba-a209-47d6-8fb6-da703e3a6fb6.png)

### Expected Behavior

The flow should run

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

The whole solution

### Steps To Reproduce

I have upgraded as recommended here: https://github.com/microsoft/coe-starter-kit/issues/1005

**Comment by JeneferM-MSFT** [comment]
Hello you are experiencing some product bug there. I've seen it once before for a flow unrelated to the toolkit. Turning the flow off and on again fixed it. I would suggest trying that.

**Comment by medicineshow** [comment]
I have tried that but no success. I am getting the same error for the CLEANUP - Admin | Sync Template v3 (Check Deleted) flow too

**Comment by JeneferM-MSFT** [comment]
I'm afraid you will need to contact product support. The product itself there is telling you that it cannot find the flow. Sorry we cant be of more assistance.

**Comment by yveskerwyn** [comment]
Same here, after upgrading...
