### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by DemosPapa** [microsoft/coe-starter-kit#1049]
### Describe the issue

Admin | Archive and Clean Up v2 (Start Approval for Flows) bellow error is received:

"The request was archiving was unable to process as the user has insufficient permissions to the CoE Environment. Please give them permissions to Approvals in the CoE to proceed."

What needs to be done?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.00

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Flows)

**Comment by manuelap-msft** [comment]
Hello,

the most likely cause for this is that you have set a Security Group at Environment level, and users participating in the approval process are not part of this Security Group. We advise against using Environment Security Groups for that reason, see: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#security-groups-and-approvals

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
Please see [assign approvals to any user in your tenant](https://docs.microsoft.com/power-automate/get-started-approvals#assign-approvals-to-any-user-in-your-tenant) for the full list of reasons this might happen.
