### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by davidvansickle** [microsoft/coe-starter-kit#1052]
### Describe the issue

When running the [Child] Admin | Sync Logs we are facing an error related to parsing the JSON.

Error
Action 'Parse_JSON' failed

Here's the output.  It's not all the records, it's a handful.  
{
    "errors": [
        {
            "message": "Invalid type. Expected Integer but got String.",
            "lineNumber": 0,
            "linePosition": 0,
            "path": "[1].RecordType",
            "value": "83",
            "schemaId": "#/items/properties/RecordType",
            "errorType": "type",
            "childErrors": []
        },
        {
            "message": "Invalid type. Expected Integer but got String.",
            "lineNumber": 0,
            "linePosition": 0,
            "path": "[1].UserType",
            "value": "0",
            "schemaId": "#/items/properties/UserType",
            "errorType": "type",
            "childErrors": []
        }
    ]
}

What's weird is this has worked as recently as 8/15. (see below image)
Then it stopped after a successful run.

![image](https://user-images.githubusercontent.com/9801374/130086098-65bb7269-4088-49b8-a60a-6be0a26ba709.png)

### Expected Behavior

 [Child] Admin | Sync Logs run without error.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

 [Child] Admin | Sync Logs

### Steps To Reproduce

Run Admin Sync to trigger  [Child] Admin | Sync Logs

**Comment by JeneferM-MSFT** [comment]
Sometimes back ends change the way they send data, or send new data loads, and then a parse will start to fail. 
However, we do not rely on either of these fields and do not refer to them in our schema as a result, so I suspect you are not seeing the latest schema there. 
Please open the flow in edit mode and see what you have for schema. This is what is currently shipped:
```
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "UserId": {
                "type": "string"
            },
            "UserKey": {
                "type": [
                    "string",
                    "null"
                ]
            }
        }
    }
}
```

If thats not what you see, then perhaps you have an unmanaged layer on the flow that prevented you from seeing updates from us. Please see  [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by davidvansickle** [comment]
I'm not seeing that at all in the Child Sync, here's what I'm showing for the schema.

{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "CreationTime": {
        "type": "string"
      },
      "Id": {
        "type": "string"
      },
      "Operation": {
        "type": "string"
      },
      "OrganizationId": {
        "type": "string"
      },
      "RecordType": {
        "type": "integer"
      },
      "ResultStatus": {
        "type": "string"
      },
      "UserKey": {
        "type": "string"
      },
      "UserType": {
        "type": "integer"
      },
      "Version": {
        "type": "integer"
      },
      "Workload": {
        "type": "string"
      },
      "AppName": {
        "type": "string"
      },
      "ObjectId": {
        "type": "string"
      },
      "UserId": {
        "type": "string"
      },
      "CrmOrganizationUniqueName": {
        "type": "string"
      },
      "Fields": {
        "type": "array"
      },
      "InstanceUrl": {
        "type": "string"
      },
      "ItemType": {
        "type": "string"
      },
      "ItemUrl": {
        "type": "string"
      },
      "UserAgent": {
        "type": "string"
      },
      "CorrelationId": {
        "type": "string"
      },
      "EntityId": {
        "type": "string"
      },
      "EntityName": {
        "type": "string"
      },
      "Message": {
        "type": "string"
      },
      "PrimaryFieldValue": {
        "type": "string"
      },
      "Query": {
        "type": "string"
      },
      "QueryResults": {
        "type": "string"
      },
      "ServiceContextId": {
        "type": "string"
      },
      "ServiceContextIdType": {
        "type": "string"
      },
      "ServiceName": {
        "type": "string"
      },
      "SystemUserId": {
        "type": "string"
      },
      "UserUpn": {
        "type": "string"
      },
      "AdditionalInfo": {
        "type": "string"
      },
      "Name": {
        "type": "string"
      }
    }
  }
}

**Comment by davidvansickle** [comment]
Whoops, this is what I'm showing.  Disregard if you read my deleted post.

{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "OrganizationId": {
                "type": "string"
            },
            "RecordType": {
                "type": "integer"
            },
            "ResultStatus": {
                "type": "string"
            },
            "UserKey": {
                "type": "string"
            },
            "UserType": {
                "type": "integer"
            },
            "Version": {
                "type": "integer"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": "string"
            },
            "UserId": {
                "type": "string"
            },
            "CrmOrganizationUniqueName": {
                "type": "string"
            },
            "Fields": {
                "type": "array"
            },
            "InstanceUrl": {
                "type": "string"
            },
            "ItemType": {
                "type": "string"
            },
            "ItemUrl": {
                "type": "string"
            },
            "UserAgent": {
                "type": "string"
            },
            "CorrelationId": {
                "type": "string"
            },
            "EntityId": {
                "type": "string"
            },
            "EntityName": {
                "type": "string"
            },
            "Message": {
                "type": "string"
            },
            "PrimaryFieldValue": {
                "type": "string"
            },
            "Query": {
                "type": "string"
            },
            "QueryResults": {
                "type": "string"
            },
            "ServiceContextId": {
                "type": "string"
            },
            "ServiceContextIdType": {
                "type": "string"
            },
            "ServiceName": {
                "type": "string"
            },
            "SystemUserId": {
                "type": "string"
            },
            "UserUpn": {
                "type": "string"
            },
            "AdditionalInfo": {
                "type": "string"
            },
            "Name": {
                "type": "string"
            }
        }
    }
}

**Comment by davidvansickle** [comment]
It was the solution layer, thank you!

**Comment by JeneferM-MSFT** [comment]
great news. Thanks for using CoE
