### ISSUE TITLE
[CoE Starter Kit - BUG] Connector to Audit Logs keeps disappearing

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#1055]
### Describe the issue

Every so often the connection to the Audit Logs keeps disappearing for no apparent Reason.

I notice this  when in "Connections" I get asked to fix a connection to the Audit Logs.  When I try - I get this error :-

AADSTS700016: Application with identifier 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx' was not found in the directory 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyy'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

When I check the Enterprise Apps the Enterprise App has disappeared.

Re-adding the enterprise App - everything works again.

Regards

Nigel

### Expected Behavior

I expect the Enterprise App to remain until explicitly deleted.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.3.6

### What app or flow are you having the issue with?

[Child] Admin : Sync Logs

### Steps To Reproduce

None - it just disappears

**Comment by JeneferM-MSFT** [comment]
This is a product issue and not one with the toolkit. 
I do see this sometimes and I just redo the [setup steps for the connector](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector) and re-authenticate the connection.

**Comment by JeneferM-MSFT** [comment]
Closing out as there is no action for the toolkit itself.
