### ISSUE TITLE
[ALM Accelerator - BUG]: Error found in action: RunCreateEnvironmentFlow with code: BadRequest Error:

### ISSUE THREAD

**Issue by jmcrestani** [microsoft/coe-starter-kit#1056]
### Describe the issue

When creating a new project in ALM Accelerator for Makers, I get the error bellow:
Error found in action: RunCreateEnvironmentFlow with code: BadRequest Error: {"error":{"code":"TriggerInputSchemaMismatch","message":"The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'Invalid type. Expected String but got Null.'."}} 

### Expected Behavior

No errors, or build app in an existing environment

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

### Steps To Reproduce

1. import solution ALMAcceleratorForMakers_1.0.20210521.1_managed.zip
2. execute all configuration
3. access ALM Accelerator for Makers app
4. Request approval for a new project
5. Approve new project
6. Error found in action: RunCreateEnvironmentFlow with code: BadRequest Error

**Comment by mikefactorial** [comment]
Hey @jmcrestani, would it be possible to provide some screenshots for context? The RunCreateEnvironmentFlow step that is failing is a child flow so there may be more details about the specific failure in the runs of the CreateEnvironment flow.

![image](https://user-images.githubusercontent.com/42348035/130447054-84c79a34-2831-458c-b726-2bbfba9d6b5d.png)

**Comment by mikefactorial** [comment]
@jmcrestani closing this issue for now since we haven't heard back feel free to open a new issue if you have follow up questions
