### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by wagnerdass** [microsoft/coe-starter-kit#1058]
### Describe the issue

Boa tarde, 

eu recebi essa notificação e gostaria de saber como agir para não excluir o ambiente e gostaria e entender esse novo modelo?

desde já agradeço fico no aguardo segue a baixo o email:

De: CoE Power Platform <coepowerplat@g.globo>
Enviado: quinta-feira, 19 de agosto de 2021 18:20
Para: Mariana Goulart <mariana.goulart@g.globo>
Assunto: Seu ambiente do Power Platform precisa de atenção! 
 
Olá,

Identificamos que você possui o ambiente Supervisão Logística de Mídias (org4d5fa692). Estamos aplicando em toda a nossa organização o programa de Governança de Power Platform e com isso precisamos de sua ajuda para deixarmos o ambiente cada vez mais saudável e controlável. 

Você ainda faz uso deste ambiente?

Se sim, em breve você receberá novas informações sobre a migração do conteúdo do ambiente (apps e fluxos).

Se não, você tem até o dia 31/08 para realizar a exclusão do ambiente. Caso contrário, o mesmo será excluído automaticamente.

Como excluir seu ambiente.

Abs,
CoE Power Platform

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

org4d5fa692

### What app or flow are you having the issue with?

Supervisão Logística de Mídias

**Comment by JeneferM-MSFT** [comment]
Can you please run the above through your favorite translator app? I'm afraid I dont know what language to translate from.

**Comment by JeneferM-MSFT** [comment]
ok i got informed this is portugese and was able to translate. It looks like your admin team has implemented a version of our CoE toolkit, but it also looks like they have augmented it to meet their needs. So I will not be able to assist. Please use the email address given to work with your admin team.
