### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Settings missing

### ISSUE THREAD

**Issue by davidkolenko** [microsoft/coe-starter-kit#1061]
### Describe the issue

In COE Core Components 2_75, the "CoE Settings" Group and "Configure" SubArea are missing in the "Power Platform Admin View" Model Drvien App.

![image](https://user-images.githubusercontent.com/89409300/130484397-4ef9c885-7114-4e83-97f6-620c6c8d0e35.png)

![image](https://user-images.githubusercontent.com/89409300/130484431-077fad63-2182-47fd-97aa-b72c92dab5f8.png)

### Expected Behavior

Access to the Configure section within the Power Platform Admin View Model Driven App

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

1. Open Power Platform Admin View
2. Note the missing "CoE Settings" and "Configure" option in the SiteMap (see images attached to "Describe the issue"

**Comment by davidkolenko** [comment]
> 
> 
> Hello this is by design, we removed this table from the setup steps as it was no longer needed as all settings now exist as environment variables.

Is the idea that now everything is managed via the Default Solution to update the value?

**Comment by JeneferM-MSFT** [comment]
No, with environment variables, all environments have their own values. So when you setup your CoE in your CoE environment, you filled in several of these, and now we just added the last few that were in this table previously. 
If you have dev/test/prod versions of CoE in separate environments, you will just need to add the values to the environment variable in each environment. 
Hopefully I understood your question. Please let me know.
