### ISSUE TITLE
[CoE Starter Kit - BUG] Audit logs -- trouble with interval

### ISSUE THREAD

**Issue by FacilyDev** [microsoft/coe-starter-kit#1065]
### Describe the issue

In the Center of Excellence - Audit Logs solution in flow [Admin | Sync Audit Logs] in the step [Generate timeSegments list] there is a default limit = 60 meaning that if you use [TimeInterval-Interval] actually below 30 mins. you would always receive the "CoE Audit Logs require smaller chunks" warning as in the following step [Append last segment to arrtimeSegments] the  period will be much longer than in TimeInterval-Interval as it would take all the rest time between 24 hours - 60*TimeInterval-Interval! 
![image](https://user-images.githubusercontent.com/28065097/130499740-a906441e-8a09-4ee5-9e00-5a69d7ba0995.png)

### Expected Behavior

1. Either change the default value of [Count] limit in the [Generate timeSegments list] step that is shipped with the solution (I suggest 1440 that will be enough for 1 min. TimeInterval-Interval).
2. Or at least update the documentation regarding [TimeInterval-Interval] parameter (Step 9. here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Steps To Reproduce

If  default 1hr [TimeInterval-Interval] gives you a "CoE Audit Logs require smaller chunks" warning and e.g. 30 mins don't, please use any other smaller [TimeInterval-Interval] like 15, 10, 5 mins. and surprisingly you will still receive email "CoE Audit Logs require smaller chunks".

**Comment by JeneferM-MSFT** [comment]
I have added environment variables for these, but we will not be able to test/validate them at varying degrees, so you will be able to experiment and then keep values that work for you. We will ship the defaults as they are today.

**Comment by mikefactorial** [comment]
@FacilyDev This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
