### ISSUE TITLE
COE Update or Upgrade to August version does not work

### ISSUE THREAD

**Issue by mduqueBasf** [microsoft/coe-starter-kit#1070]
Hi COE Update or Upgrade to August version does not work for CoreComponents The rest of the solutions are OK . Latest Core was June.

My Core Http Azure AD Dependencies are:

![image](https://user-images.githubusercontent.com/64835119/130593856-62af29a5-4c7a-40bd-b684-14e2abb13744.png)

**Comment by JeneferM-MSFT** [comment]
Please work with us on this version of the issue 
Duplicate of #1005
