### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unable to import - Dependancies on Solutions: CenterofExcellenceCoreComponents (2.75)

### ISSUE THREAD

**Issue by Ryn-Ash** [microsoft/coe-starter-kit#1071]
### Describe the issue

Hello,

We have our CoE kit in our Dev Environment. We created a solution with relationships to `User` and I now want to export this to an environment that doesn't have the CoE on it. I've hit a wall of dependency issues and feel I might have made a rookie mistake by using the CoE in our TO-BE Dev environment.

Would my only options be to import the CoreComponents and anything else required to the target environment? I would think the other options would involve removing core components from the existing environment and set it up somewhere else. (A lot of work.)

### Expected Behavior

Unknown

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

n/a

**Comment by JeneferM-MSFT** [comment]
I'm afraid we cannot support you through this, but yes in my experience its best to not create multiple solutions in the same environment for this exact reason. You can try this, but if it doesnt work I'm afraid I cannot help futher. 
1) Create a new unmanaged solution
1) Add all the things you need for your new (non CoE) work into it
1) Add all the CoE things that are coming as a dependency to it
1) Export it and install in a new environment
1) In that environment, remove all the CoE specific objects from the solution, then delete them from that environment.

That should do it, fingers are crossed for you

**Comment by Ryn-Ash** [comment]
Going to give it a whirl!

**Comment by JeneferM-MSFT** [comment]
I'm a little confused. It sounded like the things you were developing had nothing to do with CoE, and the dependencies were accidental (used the same shared table of Users). 
You should not have these in the same environment. You shoudl have your CoE be separate.
I'm afraid you will need to seek help from a partner, product support, or the Power Platform community to assist further as your questions are outside the scope of the toolkit. 
Sorry I cannot be of further help.
