### ISSUE TITLE
Admin - Access this Flow doesn't delete flow and set permission 

### ISSUE THREAD

**Issue by MarinaHadzi** [microsoft/coe-starter-kit#1072]
### Describe the issue

Admin access this flow or app canvas apps embeded in Power BI does not delete flow or app
![image](https://user-images.githubusercontent.com/71693895/130636481-d4b7a296-822a-4f9e-951c-75dda098e28c.png)

I don't find this flow, can I replace it with other ID?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

Admin - Access this Flow

**Comment by JeneferM-MSFT** [comment]
Does the identity which is using the Power BI have the Power Platform Admin Role? 
Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)

**Comment by Jenefer-Monroe** [comment]
Hello, per your other issue #1054 it appears that there is something wrong with your account. It is not able to create connections in your environment either, even outside of the context of our toolkit.

**Comment by manuelap-msft** [comment]
Closing as no action required on the CoE team.

**Comment by MarinaHadzi** [comment]
@manuelap-msft  hi, can you please tell me for this issue, is Power Automate per user license needed? My account has POwer Apps per user license and Power Automate per flow license is assigned to CoE environment. Is this the causing the issue?
