### ISSUE TITLE
[CoE Starter Kit - Documentation] Author a how-to for backup and restore of data in the event the CoE needs recreated

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#1075]
### Describe the issue

with all the install / upgrade issues we have seen, we need a way to recreate a CoE without loosing all the extended data

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

setup

**Comment by manuelap-msft** [comment]
We are tracking the data migration in a different bug. Closing this out.
