### ISSUE TITLE
Flows Shared With (List)

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#1083]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/863

<div type='discussions-op-text'>

<sup>Originally posted by **robertcaretta** July 15, 2021</sup>
Is there a projected release date on when "flow shares" inventory might be released? This information is of high importance for us. </div>

AB#1570

**Comment by osbornecc** [comment]
We also created our own standalone flow/table in our CoE environment to grab all flow shares.  But I'm sure it's clunky and anything the CoE team comes up with will be much better :)

**Comment by Jenefer-Monroe** [comment]
adding to orphans clean up fc

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d31aab4d-0e97-4bb2-98d1-5c793fe107ca)



![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6080e019-12de-4f83-a545-441677752ae0)

**Comment by Jenefer-Monroe** [comment]
Only took three years 🤪

**Comment by Travis-at-Kiewit** [comment]
I am so excited for this!

**Comment by IanOliveira718** [comment]
I'm so happy about this! Is it going to be available in the next CoE version?

**Comment by Jenefer-Monroe** [comment]
It will indeed. Target to ship mid week next week.

**Comment by bhavikj65** [comment]
@Jenefer-Monroe, Do we have an option to export list of flows which are ownerless ? For example, flows where the primary owner has left the company and the flow is not shared with any users (co-owner or run-only) ?

**Comment by bhavikj65** [comment]
@Jenefer-Monroe / @manuelap-msft ,

This flow requires significant optimization, particularly for enterprise tenants. After deploying the July version yesterday and monitoring it, I observed nearly 2 million requests in a single day. Based on this, I estimate it will take approximately 10 days or more to complete processing all our cloud flows.

![image](https://github.com/user-attachments/assets/0ade68c6-7f59-42da-abc2-1f966d422625)

**Comment by Vignes29** [comment]
Hi,
We are getting an error in CLEANUP HELPER - Cloud Flow User Shared With when looking for the service principle in AD.
May I know why we are seeing error - "Invalid value specified for object reference property 'id'. Please ensure that this value has an appropriate syntax and length."

![image](https://github.com/user-attachments/assets/dc2753a4-bf6d-41f5-8e41-3fe22015e42c)
