### ISSUE TITLE
[CoE Starter Kit - BUG]: Center of Excellence for Power Platform does not retrieve "Sessions" or "Last Launched on" values for model-driven apps, just only for canvas

### ISSUE THREAD

**Issue by guillermo-ac** [microsoft/coe-starter-kit#1084]
We have installed the CoE Starter Kit in our company for a better gobernance of Power Platform, but we notice that the Power Automate flow (_[Child Admin] | Sync Logs_) that retrieves information from Microsoft 365 audit log does not retrieve information for model driven apps, just only for canvas apps and that causes that Power BI reports do not show information for model driven apps such as "How many sessions have been launched on a period of time" or "How many unique users used the app in a period of time".  Our customer needs this kind of information for both types of applications (canvas and model driven).

The following screenshot shows the Power BI report for apps that comes with CoE, filtering by canvas apps:

![Canvas](https://user-images.githubusercontent.com/89647441/131146645-65c42d19-dd81-47e3-b99b-fc1d01f10c4d.png)

And the next screenshot shows the same report but filtering by model driven apps (as you can see, no information is shown for columns "Unique Users", "Sessions", "Users Shared" and "Last Launched"):

![Model-driven](https://user-images.githubusercontent.com/89647441/131146690-a58409b8-2945-45c6-a51c-07e0b1b99012.png)

Is there a way to get this kind of statistics for model driven apps?

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for coe team
