### ISSUE TITLE
CoE-Dataverse for Teams environment

### ISSUE THREAD

**Issue by raj835** [microsoft/coe-starter-kit#1085]
### Describe the issue

Following the article : https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#option-2-import-the-solution-into-a-dataverse-for-teams-environment

1.We created a Teams Group ,installed the PowerApp in Teams and created a Test app .
2.By doing so ,a Teams environment gets created by default  which we excluded from DLP policy .
3.We do not want to add any new connectors in our default policy ,thats why we excluded the Teams environment which got created after adding PowerApp .

4.We are getting DLP issues while activating flows .Microsoft says that flows belongs to some other environment and asking us to exclude it too .

Please let us know excluding the Teams environment where CoE was added to will help or not in this case .
Or should we allow the connectors first in the existing DLP policy  and than proceed further .
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.998

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by raj835** [comment]
Any update ?

**Comment by Jenefer-Monroe** [comment]
Hello there. Please note that the CoE Starter Kit is [not a supported toolkit](https://docs.microsoft.com/power-platform/guidance/coe/overview#disclaimer), it is a set of starter templates we provide to help people get going on managing their tenants, so your expectation that we would have responded within 6 hours is not one that we can guarantee to meet. 
I see that we discussed this issue in #949 as well, so adding that context here.

**Comment by Jenefer-Monroe** [comment]
As I said in 949, here are the options as I see it

1) You are incorrect and have more DLP policies that you think
1) You have not correctly excluded the environment from the one DLP policy
1) You have hit a product bug. 

Further, having to exclude an unrelated environment to exclude this environment, as you say was advised by support, would be a product bug. I would suggest you reach out to support again. They can contact myself or manuelap-msft if they have questions

**Comment by raj835** [comment]
Hello Jenefer ,

Could you please check ticket : Query on CoE Kit #1084


Regards,
_____________________________________
[spade]Rajanee Kumari

Capgemini "India" | Kolkata
Mob.: + 91 - 9535504729
www.capgemini.com<http://www.capgemini.com/>
***@***.***
People matter, results count.

**Comment by Jenefer-Monroe** [comment]
Hello. Are you referencing htis issue? [CoE Starter Kit - BUG]: Center of Excellence for Power Platform does not retrieve "Sessions" or "Last Launched on" values for model-driven apps, just only for canvas #1084

If so, can you make your comment/query there?

**Comment by raj835** [comment]
Hello ,
Please check below ,this is my query .

We are planning to implement this in our environment .
***@***.***

Regards,
_____________________________________
[spade]Rajanee Kumari
GI - Corp Apps Infra (O365)

Capgemini "India" | Kolkata
Mob.: + 91 - 9535504729
www.capgemini.com<http://www.capgemini.com/>
***@***.***
People matter, results count.

**Comment by Jenefer-Monroe** [comment]
Hello. I dont know if you are pasting pictures or something, but they are not coming through. Please note that if you want to share pictures you need to do so in GitHub itself, they do not come through if you respond in email. 
Here is what I see from you:
![image](https://user-images.githubusercontent.com/89584709/132045921-4cf24d97-5d31-477e-8654-0d03c6e66552.png)
