### ISSUE TITLE
Center of Excellence - Audit Logs - v2.2

### ISSUE THREAD

**Issue by JMM-CDS** [microsoft/coe-starter-kit#1095]
Hello,

I installed the last version of the Audit Logs.
I have an issue with the Parse JSON after the GetContent Details :
![image](https://user-images.githubusercontent.com/81332119/131686442-5aa74a4b-fba7-4b2a-8855-bb6ca1d7e808.png)

For RecordType and UserType the type of the data does not match.

I verify another child flow, i got this error on the parsing :
"message": "Invalid type. Expected String but got Null.",
"lineNumber": 0,
"linePosition": 0,
"path": "[35].ResultStatus",
"schemaId": "#/items/properties/ResultStatus",
"errorType": "type",
"childErrors": []

Can you help me ?
Thanks

**Comment by Jenefer-Monroe** [comment]
Hello. We do not have those properties in the JSON schema any longer. I believe you have an unmanaged layer leaving you with stale bits in your flows. Please see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) for how to find and remove these from your flows and apps. 

Here is what the Parse JSON Schema should look like after you remove the unmanaged layers
```
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "UserId": {
                "type": "string"
            },
            "UserKey": {
                "type": [
                    "string",
                    "null"
                ]
            }
        }
    }
}
```

**Comment by JMM-CDS** [comment]
Thank you for your feedback.
I deleted all unmanaged layers before installation.
I'll do it again and let you know if it's ok this time.

**Comment by JMM-CDS** [comment]
I deleted the solution and reimport and now it's ok. Thanks !

**Comment by pandeyup** [comment]
this succeded post changing schema .. thanks for update. wil check on update link how we can use that to remove unmanaged layer
