### ISSUE TITLE
Pipelines: Validate Pipelines and ALM Accelerator App in Gov Cloud

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#110]
Validate ALM Accelerator for Advanced Makers setup and use in GCC

**Comment by B1776** [comment]
Hello and thank you for the work on this area.  I am stepping through installation in a GCC High sandbox environment and have encountered a number of issues.  I would be happy to share or test updated solutions.  Right now, I cannot even install as the Content Conversion connector is required and not available in GCC High, so there is a blocking error asking me to re-establish the connection before import.  When I try to, I receive an error, "Could not find API 'shared_conversionservice'.

Reach out if you would like more details or have specific test cases.

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here.
