### ISSUE TITLE
[CoE Starter Kit - BUG] AuditLogs component - connection references not set after import for [Child] Admin | Sync Logs

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#1102]
### Describe the issue

After importing AuditLogs component the connection references are not set for [Child] Admin | Sync Logs, so need to edit and re-authenticate connections

![image](https://user-images.githubusercontent.com/8307644/131861945-15076b87-51b0-4f93-bd18-b65e054684b8.png)

![image](https://user-images.githubusercontent.com/8307644/131862784-f2d7090d-1357-42d6-b45a-e902f8e8a257.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
Hi there. It is expected to have to set the **_run only users_** property for child flows, as shown in [audit log setup - Setup the Power Automate Flow](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow). I just tested this on a fresh install and it worked for me. Can you please let me know if that does not work for you? 

Thanks
Jenefer

**Comment by petepuu** [comment]
Ok will check that tomorrow but should we anyhow have connections associated to flows after import?

**Comment by petepuu** [comment]
Ok that was it I complete missed that part of the setup. Has it been configured like this before as I remember that connections were correctly associated and flows enabled automatically after import?

**Comment by Jenefer-Monroe** [comment]
For me, these didn't show up until after I did the **_Run only users_**. The section was blank and then I did the **_Run only users_**, and then they showed up. 
![image](https://user-images.githubusercontent.com/89584709/131911767-fd0d8066-4608-4110-868d-16fc3361e25e.png)

I dont remember if these used to show up here before you did the **_Run only users_** setting. I think they did but I dont remember for sure. Might have been a product change.

**Comment by Jenefer-Monroe** [comment]
Looks like we are both working on this at the same time :) 
I do think this is a product change for them to show up afterwards now instead of before. Glad it worked out!

**Comment by petepuu** [comment]
OK have to read instructions better next time ;) ... thanks for the help! 👍

**Comment by Jenefer-Monroe** [comment]
You bet! Thanks for using CoE!
