### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by EmranCoE** [microsoft/coe-starter-kit#1114]
### Describe the issue

**CoE Core Components . 
Admin | Compliance detail request v3**

I am  working with Center of Excellence (CoE) Starter Kit (Developer Compliance Center), 
When it sends the Compliance request email for Apps, the app maker (licensed user) can not open the link to “Developer Compliance Center”  to fill the justification  !
I have tried with share the App.
 I also tried sharing by  assign the role (Power Platform Maker SR) but it doesn't go .

![InkedJustification_App_LI](https://user-images.githubusercontent.com/90054514/132178587-427af6bd-088e-48fa-af37-3e0f404fbd0c.jpg)
![Error_2](https://user-images.githubusercontent.com/90054514/132178622-ad06b750-7913-4fed-a5f5-75beadeecbac.png)
![Error_1](https://user-images.githubusercontent.com/90054514/132178640-6165d97c-dc5d-4fee-9fd8-62f2fb12f4af.png)
![Share](https://user-images.githubusercontent.com/90054514/132179442-fc8b545c-7a02-45d4-9a92-d7a7b5f093a4.png)

### Expected Behavior

I can open and fill it as a Admin without any error 

![Dev_Compliance_Center](https://user-images.githubusercontent.com/90054514/132178854-301de59c-a066-4c70-b743-790e10464f92.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Admin | Compliance detail request v3

**Comment by manuelap-msft** [comment]
Hello,

can you confirm that the user opening the app has a Power Apps Per User license, or that the app is covered by a Per App pass? This app uses premium features, thus a premium license is required.

Thank you
Manuela

**Comment by EmranCoE** [comment]
Hey Manuela,

Thank you for quick response .
Okay , it looks like license issues !  I have checked with the users they currently have license( Microsoft 365 E5 ) not premium license .
So , I will get back to you if the App "Developer Compliance Center" still doesn't work for them after assign the premium license for the users .

Regards,
Emran .



________________________________

**Comment by EmranCoE** [comment]
Just wondering we have a large number of users in Default Environment as well as in Microsoft Team Type Environments usually they don’t have premium license, those users mostly make the apps/flows for testing purpose.
So is there any other recommendation to share the “Developer Compliance Center” ! for them to fill the justification.
Regards,
Emran .


________________________________

**Comment by Jenefer-Monroe** [comment]
I'm afraid we dont have a solution for this that does not require a premium license. It would likely be possible to do the same thing with adaptive cards in teams if you wanted, but you would have to develop that yourself.

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for toolkit team

**Comment by EmranCoE** [comment]
Okay , Thanks for all the information .

Regards,

Emran
________________________________
