### ISSUE TITLE
 Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade

### ISSUE THREAD

**Issue by mwolfaardt** [microsoft/coe-starter-kit#1116]
### Describe the issue

I'm unable to upgrade my CoE starter kit, I've followed the instructions as on the website but still get an error. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.77

### What app or flow are you having the issue with?

Solution Upgrade

### Steps To Reproduce

1. Download latest version
2. Extract
3. Upload solution file
4. Wait for solution to upgrade
5. Error : 
Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade

**Comment by manuelap-msft** [comment]
Hello,

can you check the instructions in #1005 and see if those help? Mainly, using Update instead of Upgrade during the import.

Thank you
Manuela

**Comment by mwolfaardt** [comment]
Issues solved by following steps provided in #1005
