### ISSUE TITLE
[CoE Starter Kit - BUG] - PBI Dashboard Not Displaying Custom Connectors Correctly

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#1119]
### Describe the issue

There are multiple PBI reports on the dashboard that do not filter down on the CoE custom connector correctly. 

### Expected Behavior

Should be able to filter down to  just the custom connectors on the reports.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

PBI Dashboard - CDSLegacy_CoEDashboard_202108.pbit

### Steps To Reproduce

1. Review the provided screenshots.
2. Repeat the process of filtering to just CoE custom connector on PBI dashboard reports.

### Anything else?

![2021-09-07_8-12-28](https://user-images.githubusercontent.com/1613085/132351706-daac7044-ab78-4ae4-8601-6b15523f9739.png)

![2021-09-07_8-23-03](https://user-images.githubusercontent.com/1613085/132352498-13576d60-a1f7-47dd-89af-b774f11cef12.png)

**Comment by Jenefer-Monroe** [comment]
It looks like the second image is incorrect. If you have filtered to just custom connectors you should not see things like Approvals and Outlook showing up. That should then only be listing custom connectors after you select it. 

Can you please let me know:
- Are you aware of Custom Connectors running in your tenant? You would expect to see some custom connectors? 
- Please check that this sync flow in Core is on, running, and passing: **_Admin | Sync Template v3 (Custom Connector)_**
- What version of the PBI are you using? As in when did you download the .pbit file?

**Comment by robertcaretta** [comment]
It would appear that the filter on the second report (Cloud flow Connections) is broken. Correct, you would expect it to show nothing but that is not the case.  I tried resetting the filter but no change. 

- We do not have any custom connectors at this point, other than the one in the CoE. However, we are being asked about reporting on custom connectors as we are already have a request for one. This is why we are reviewing the reports.

- Sync flow is running, as well as the refresh schedule on the dataset for PBI dashboard. 
![image](https://user-images.githubusercontent.com/1613085/132359650-c4feb59d-065c-462e-9ee3-251aefb500d7.png)

- All of this was updated recently using the August 2021 release.
![image](https://user-images.githubusercontent.com/1613085/132360108-0deb8418-10fc-4d23-8ffb-d5a921658fb2.png)

**Comment by manuelap-msft** [comment]
Hello,

please select "Custom" from the Tier filter on the page
![image](https://user-images.githubusercontent.com/55705669/132372364-a5aa79f5-1dcf-4ac9-975f-cd952cacead9.png)

And not the Filter pane in Power BI and see if that works.

Thank you
Manuela

**Comment by robertcaretta** [comment]
@manuelap-msft - I am not understanding what the Tier filter is. This is all I see.
![2021-09-07_11-28-06](https://user-images.githubusercontent.com/1613085/132380100-7e2535c4-4dae-4e04-98fc-69f0cf9efd10.png)

**Comment by manuelap-msft** [comment]
See the highlighted part here:
![image](https://user-images.githubusercontent.com/55705669/132380589-01602cb5-fb79-4021-b191-04e5fd494acb.png)

**Comment by robertcaretta** [comment]
I just edited my comment. :)  That does indeed change the results. It does not show an option for the CoE custom connector though. Perhaps once we have some additional ones that will work?

**Comment by manuelap-msft** [comment]
Great, thanks for confirming!

There is another issue with fetching custom connectors that are in a solution (tracked #976) which is why you are not seeing the CoE custom connector at the moment. We're addressing parts of this with the next release in September!

I have also removed the confusing Standard vs Premium option from the Power BI Filter pane for the next release.

Thank you
Manuela

**Comment by robertcaretta** [comment]
Great, sounds like you are aware.  Thank you. 

I don't find the Standard vs Premium vs Custom confusing. To me that is useful information in relation to DLP policy setup. We do however have a different security group managing the DLPs. I suppose they can just look at the environments and connector names if they have questions about usage.  You must have received some other feedback on that.

**Comment by manuelap-msft** [comment]
Thanks for confirming!

Oh I meant I am removing the Standard v Premium filter that didn't work for you (it didn't work for me in my test either) from that Filter pane, as only the "Tier" filter on the page works: 
![image](https://user-images.githubusercontent.com/55705669/132383619-abc6420a-f637-4734-8ebc-ea354120752e.png)

Thank you,
Manuela

**Comment by mikefactorial** [comment]
@robertcaretta This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by robertcaretta** [comment]
@mikefactorial @manuelap-msft 
We upgraded the solution and dashboard to the latest release in our TEST environment. The PBI dashboard for Custom Connectors is not providing details about the CoE custom connector. Is there a limitation with custom connectors in a Solution?

![2021-09-10_15-27-43](https://user-images.githubusercontent.com/1613085/132914043-95cd588a-f8b8-490b-a6ee-12469430b1c6.png)

**Comment by robertcaretta** [comment]
Also no option for select "Custom" in the filters area of this report.
![2021-09-10_15-37-16](https://user-images.githubusercontent.com/1613085/132914936-66762fbb-10b7-4c8f-ad81-a1c55b440bde.png)

**Comment by manuelap-msft** [comment]
Yes there is a limitation, see  #976<https://github.com/microsoft/coe-starter-kit/issues/976>. The Custom option will only show up under Tier if you have flows using Custom Connectors.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
