### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to turn on CLEANUP - Admin | Sync Template v3 (Check Deleted)

### ISSUE THREAD

**Issue by highsmithjd** [microsoft/coe-starter-kit#1129]
### Describe the issue

I'm getting the error below when trying to start the "Turn on: CLEANUP - Admin | Sync Template v3 (Check Deleted)" workflow during the core component setup. My account is a Power Platform Administrator, CoE Environment sys admin, has O365 license, and a power apps per user license. Setting up the connections and import went successfully but when i try and run the flow i get the error;

The workflow with id '<id>' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow.

### Expected Behavior

Flow should run

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.77

### What app or flow are you having the issue with?

Turn on: CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Steps To Reproduce

Each time i run the flow i get the same error

**Comment by Jenefer-Monroe** [comment]
hello we released 2.77 without the needed documentation. We will be releasing Sept bits today and the documentation to go with it. I will let you know when that is available.

**Comment by manuelap-msft** [comment]
Hello,

please make sure the below flows are all turned ON (they are shipped OFF by default):

- HELPER - CloudFlowOperations
- HELPER - CanvasAppOperations
- HELPER - ObjectOperations
- CLEANUP HELPER - Check Deleted (Canvas Apps)
- CLEANUP HELPER - Check Deleted (Cloud Flows)
- CLEANUP HELPER - Check Deleted (Model Driven Apps)
- CLEANUP HELPER - Check Deleted (PVA)

Thank you
Manuela

**Comment by highsmithjd** [comment]
Here's what i see when searching for "Helper." I turned on the flows that i did see

![CoEflow](https://user-images.githubusercontent.com/49718142/132559124-6c30229e-3359-46bc-a9d6-b57eaaf76260.PNG)

**Comment by manuelap-msft** [comment]
Hello,

I can see two are still off in that screenshot - once you have turned them on, you should be able to turn on the main CLEANUP - Admin | Sync Template v3 (Check Deleted) flow.

Manuela

**Comment by Jenefer-Monroe** [comment]
You will also need to set their _**Run only users**_ settings.
Please see [this example from the Audit Logs solution](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow) for an example of doing this to flow in a separate solution.

**Comment by highsmithjd** [comment]
The CLEANUP - Admin | Sync Template v3 (Check Deleted) completed. Going through the remaining steps to see if it causes any other issues. Haven't changed any Run only users settings yet

**Comment by Jenefer-Monroe** [comment]
Glad you are unblocked. I'll go ahead and close this then
