### ISSUE TITLE
[CoE Starter Kit - INSTALL INSTRUCTIONS] Upgrading Core from July 2021 (less than or equal to version 2.2.20210707.3)

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1130]
### Describe the issue

If you are upgrading from Core version less than or equal to 2.2.20210707.3 (July 2021), you will need to upgrade Core first before updating the dependent solutions.

Please upgrade in the following order:
1. Upgrade Core
2. Upgrade Nurture
2. Upgrade Gov
3. Upgrade Audit Logs

**If that doesn't work:**
If any of these do not work, keep that order but try to update instead of upgrade.
![image](https://user-images.githubusercontent.com/89584709/131681136-6d9376c6-f5c0-4b3a-84ba-8b5d5bfe9540.png) 

**Try to upgrade using the classic UX** 
And if that still does not work, use classic UX to overwrite
Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/89584709/131683084-18ee4068-873a-445c-929c-b29efcb592af.png) 

Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/89584709/131683360-817b7c64-bc36-4eb5-9429-d1329001c9d3.png) 

Choose File (the solution file you were trying to install) > Next > Next >  

Leave at Action=Upgrade but chose Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/89584709/131683790-4e7d1f9a-62a1-4ba1-aa09-84d7160928ac.png) 
![image](https://user-images.githubusercontent.com/89584709/131683907-cf80ef88-1b33-49f1-aa6c-160d825f8d7d.png) 
![image](https://user-images.githubusercontent.com/89584709/131683695-fc0f19ab-a289-4854-8a6f-d6b5173b0f64.png) 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

upgrade

**Comment by paulculmsee** [comment]
I tried to upgrade Nurture first and it told me it has dependencies on Core FYI. So going with Core to see what happens ;-)
