### ISSUE TITLE
[CoE Starter Kit - BUG] CDSLegacy_CoEDashboard_202109 - Two OrgUrl to input?

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#1132]
### Describe the issue

In the lastest version of the Power BI report we have to input two OrgUrl.
One of them I supose that is the CoE enviroment url, but the second?

![image](https://user-images.githubusercontent.com/57954993/132576710-0b7dd44d-e192-47d4-b011-25bcaf015e84.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CDSLegacy_CoEDashboard_202109

### What app or flow are you having the issue with?

CDSLegacy_CoEDashboard_202109

**Comment by Jenefer-Monroe** [comment]
We thought we fixed that before we shipped. Know that if you enter it twice it works fine, and we'll patch this up before we ship again.

**Comment by manuelap-msft** [comment]
Thanks for spotting this so quickly! I just uploaded the right version to the release. 

Thank you
Manuela

**Comment by albertocaa1317** [comment]
Confirmed the fix! Thanks @manuelap-msft
