### ISSUE TITLE
[CoE Starter Kit - BUG] Command Center flow wont gather model driven apps if gathering apps fails

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#1133]
### Describe the issue

When opening the new Command Center App, it reports the "Initially Populate Bookmarks" Flow fails.  In digging, it only fails on the first App it finds I think.  At least in the "Apply to each app in this environment step, only the 1st of 26 records has an error, but that causes subsequent steps in the Flow not to execute.  It did the same thing in both the regular environment and Dataverse for Teams Environment I've tried it in.  Below is a screenshot of the Flow error:
![image](https://user-images.githubusercontent.com/41799380/132593117-6a2c34e9-5e76-4a44-96bb-d77dd8350f88.png)

### Expected Behavior

No errors in the Flow execution.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.7

### What app or flow are you having the issue with?

Initially Populate Bookmarks

### Steps To Reproduce

Open new Command Center App to trigger the Flow to run.

### Anything else?

Not sure it's actually missing anything important as the app functions fine afterward, but could be missing something.  There are only 26 COE Apps in the environment (with one "Solution Health Hub" system app in there also).  I've opened the app a couple of times now and show 44 total apps in the Command Center bookmarks (many duplicates now).

**Comment by Jenefer-Monroe** [comment]
How strange that logical name was blank for an app in you environment. I don't think this should be common, but we can get you unblocked, and add the fix below to the next release.

### **First we will fix the flow up**
1) Edit the flow 
1) Hit the ellipses on the **_Apply to each model driven app in this environment_** action
1) **_Chose Configure run after_**
![image](https://user-images.githubusercontent.com/89584709/132595322-def7ff60-9136-4fae-9ca1-289db674a937.png)
1) Add **_has failed_** as a condition and hit done
![image](https://user-images.githubusercontent.com/89584709/132595432-a271b5e9-3d68-455a-a4f6-98e7409899f3.png)
1) Save and close the flow

### **Next we'll clear the data so the flow will run again**
1) Open the **_Command Center Config_** table 
![image](https://user-images.githubusercontent.com/89584709/132595674-1acea9ca-2633-430c-a1c1-a7819b7f9d30.png)
1) Go to the **_Data_** tab
1) Select each row and hit **_Delete record_**
![image](https://user-images.githubusercontent.com/89584709/132595783-40677ac8-d3f0-478b-9e9e-c8916dd48364.png)

### **Lastly, reopen the app and it will trigger that flow to run again with your change**
![image](https://user-images.githubusercontent.com/89584709/132596105-ce70897f-b130-4f1d-8e83-fba2e10d8881.png)

**Comment by mikefactorial** [comment]
@bartsneary This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
