### ISSUE TITLE
[CoE Starter Kit - BUG] Get M365 Service Messages Flow in Teams version of Core has misconfigured values in http connector step

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#1134]
### Describe the issue

In the Core solution for Teams, the Command Center Flow called "Get M365 Service Messages" has the http step misconfigured.  For the tenant, it should have "8a235459-3d2c-415d-8c1e-e2fe133509ad", but has the environment variable for "TenantID" in there instead.  It also should have "e174092e-abdef" for the client id, but has "{client id}" in right now instead.  Finally, it should have "xyz" in there for the client secret, but has "{client secret}" in right now instead.  I found all these "correct" values that make it work in the regular environment solution for the same Flow and after editing them, this one worked also.

### Expected Behavior

Flow would run without auth issues on the http connection.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Get M365 Service Messages

### Steps To Reproduce

Run the Flow as is manually or run the Command Center App.

**Comment by manuelap-msft** [comment]
Hello,

that's definitely not correct :) That's our Tenant ID and we did not intend to Ship Core with it - the Core for Teams version is correct, and our docs are being updated with the steps on how to create an App Registration to get your client id and secret for this flow. The docs team is just reviewing the changes so we're slightly out of sync here with our release but it will get added soon.

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Docs are now live: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#optional-create-an-azure-ad-app-registration-to-connect-to-microsoft-graph
