### ISSUE TITLE
[CoE Starter Kit - BUG] Dataverse CoE Dashboard 202109 has several errors

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#1135]
### Describe the issue

Not sure yet if it's the schema in Dataverse or the PBI definition that's off, but for the regular Dataverse environment I have, there are several issues showing.

Environments Tab:
![image](https://user-images.githubusercontent.com/41799380/132612858-f54e5d27-7536-4713-8177-9d0f5b1944bb.png)

Teams Environments Tab:
![image](https://user-images.githubusercontent.com/41799380/132612917-f5f7dcdd-0be3-4ea9-952c-03b7d64dcd84.png)

App License Assignment:
![image](https://user-images.githubusercontent.com/41799380/132613025-41edd96d-3198-4f39-9a85-3d3d88e98761.png)

Cloud Flow Archive:
![image](https://user-images.githubusercontent.com/41799380/132613063-5842b212-83d4-45cd-893c-d19526dfe236.png)

Cloud Flow Risk Assessment:
![image](https://user-images.githubusercontent.com/41799380/132613088-c42be28b-63fe-4169-ba9e-c9caeca855a4.png)

Desktop Flow Archive:
![image](https://user-images.githubusercontent.com/41799380/132613135-d9ea6ea9-930e-4acb-9e2d-ff342bd98e70.png)

Power Apps Adoption:
![image](https://user-images.githubusercontent.com/41799380/132613193-26f5d859-4cb5-464a-b554-e135f118e05f.png)

Very minor thing but this pbit file was missing from the core list on GitHub.  The only way to get it was to download the whole zip file and it was in there.

### Expected Behavior

No errors on any screen

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.7

### What app or flow are you having the issue with?

Sept PBI Template

### Steps To Reproduce

Install the template connected to regular environment and run the reports.

**Comment by bartsneary** [comment]
I just installed this on my Dataverse for Teams environment and of course the launches aren't tracked there, so those screens are supposed to not work.  I believe the errors show up for all the other same report tabs for me.  :-(

**Comment by petepuu** [comment]
Seems that there are references to removed fields at least like in Environments and Teams Environment admin_numberofapps

![image](https://user-images.githubusercontent.com/8307644/132826739-2e887c8e-cd04-4178-bbf9-2ef894f243e5.png)

Apps admin_powerappstype_display is I guess now admin_powerappstypename

![image](https://user-images.githubusercontent.com/8307644/132827685-28245590-fbe6-41f5-89a9-6d0ef3b04e60.png)

So schema need to be updated?

**Comment by manuelap-msft** [comment]
Hello,

thanks for the detailed error write up! I think I fixed those issues - before we release, could you try the new version please. You can download that from here: https://github.com/microsoft/coe-starter-kit/raw/coe-october/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Dataverse_CoEDashboard_202110.pbit

Thank you
Manuela

**Comment by petepuu** [comment]
Hi Manuela, 

Still got these errors in Cloud Flows, App Risk Assessment 

![image](https://user-images.githubusercontent.com/8307644/134961657-cd6fe2b3-b708-413a-b691-b593abba016d.png)


![image](https://user-images.githubusercontent.com/8307644/134961284-4f7bf493-78e5-4b00-8d50-e07c754121dc.png)

**Comment by manuelap-msft** [comment]
Thanks for helping test this so thoroughly! I made those two changes as well now, and now making the change for #1187 in this version as well and then I'll upload a new version ready for October!

**Comment by manuelap-msft** [comment]
Thanks for spotting those additional errors - I think I got it right now: https://github.com/microsoft/coe-starter-kit/raw/coe-october/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Dataverse_CoEDashboard_202110.pbit

**Comment by mikefactorial** [comment]
@bartsneary This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
