### ISSUE TITLE
COE Core - Unable to activate the sync template flows

### ISSUE THREAD

**Issue by fim34** [microsoft/coe-starter-kit#1140]
Hi,

I have imported the Core component of COE and blocked at first step of "activate the sync template flows"
When i want to turn on "CLEANUP - Admin | Sync Template v3 (Check Deleted)", i have this message :

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"MultipleErrorsOccurred","message":"Plusieurs erreurs se sont produites : « BadRequest,BadRequest,BadRequest,BadRequest ». Consultez les détails.","details":[{"code":"ChildFlowNeverPublished","message":"Impossible d'utiliser le workflow avec l'ID « 2e6ae3e2-8afb-eb11-94ef-002248237d7d » comme workflow enfant parce qu'il n'a jamais été publié. Les workflows enfants doivent être publiés au moins une fois pour pouvoir être ajoutés dans un workflow parent publié."},{"code":"ChildFlowNeverPublished","message":"Impossible d'utiliser le workflow avec l'ID « 6bd20554-9bfb-eb11-94ef-002248237d7d » comme workflow enfant parce qu'il n'a jamais été publié. Les workflows enfants doivent être publiés au moins une fois pour pouvoir être ajoutés dans un workflow parent publié."},{"code":"ChildFlowNeverPublished","message":"Impossible d'utiliser le workflow avec l'ID « 9a470548-58fc-eb11-94ef-002248237f74 » comme workflow enfant parce qu'il n'a jamais été publié. Les workflows enfants doivent être publiés au moins une fois pour pouvoir être ajoutés dans un workflow parent publié."},{"code":"ChildFlowNeverPublished","message":"Impossible d'utiliser le workflow avec l'ID « ffd82928-64fc-eb11-94ef-002248237d7d » comme workflow enfant parce qu'il n'a jamais été publié. Les workflows enfants doivent être publiés au moins une fois pour pouvoir être ajoutés dans un workflow parent publié."}]}}".

I already installed that in a developer tenant without an issue, this time its in a client tenant.
Any tips for this issue ?

Regards

**Comment by manuelap-msft** [comment]
**Child Flows**
The flows listed below are child flows and you will need to set up their **Run only users** settings and **turn them on.**
Please see [this example from the Audit Logs](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow) solution for an example of doing this to flow in a separate solution.

CLEANUP HELPER - Check Deleted (Canvas Apps)
CLEANUP HELPER - Check Deleted (Cloud Flows)
CLEANUP HELPER - Check Deleted (Model Driven Apps)
CLEANUP HELPER - Check Deleted (PVA)
HELPER - CanvasAppOperations
HELPER - CloudFlowOperations

**Comment by fim34** [comment]
Followed your instruction, no issue, worked fine and no error after, when i turned on CLEANUP - Admin | Sync Template v3 (Check Deleted).

Thank you for your reply. Maybe there a need to update the process guide ?

**Comment by Jenefer-Monroe** [comment]
We ship the documentation through a separate process than the solutions, and typically there is a very small delta but this month due to some out-of-office folks the approval of the docs is taking longer than expected. 
They are coming though. :)
Thanks for using CoE!
