### ISSUE TITLE
Query on CoE Kit

### ISSUE THREAD

**Issue by raj835** [microsoft/coe-starter-kit#1142]
Hello ,
Referring :https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components
Flow :
Admin | Capacity Alerts   ---- Scheduled | Daily 
This flow checks actual capacity consumption and compares it with approved capacity, that an admin sets. The flow will send an alert to the admin for environments that exceed the approved capacity, or are at 80% of approved capacity.

Does this flow takes care of all types environments .
I am talking about Dataverse Database ,file and log capacity .

**Comment by manuelap-msft** [comment]
Duplicate.

**Comment by Jenefer-Monroe** [comment]
Please see from the [Table descriptions](https://docs.microsoft.com/power-platform/guidance/coe/core-components#tables)
![image](https://user-images.githubusercontent.com/89584709/134007743-e61c1708-e602-4300-88a2-788f26f7a7ae.png)
