### ISSUE TITLE
Dataverse_CoEDashboard_202109.pbit New errors

### ISSUE THREAD

**Issue by philipbullard** [microsoft/coe-starter-kit#1150]
Getting these errors now:

Load
OrgUrl
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Environment
Load was cancelled by an error in loading a previous table.
App
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow
Column 'admin_flow' in table 'Flow Action Details' cannot be found or may not be used in this expression. OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Maker
Column 'createdon' in table 'Maker' cannot be found or may not be used in this expression. Column 'createdon' in table 'Maker' cannot be found or may not be used in this expression.
App Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Audit Log
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Connector
Load was cancelled by an error in loading a previous table.
Flow Action Details
OLE DB or ODBC error: [DataSource.Error] Microsoft SQL: Return records size cannot exceed 83886080. Make sure to filter result set to tailor it to your report. RequestId: TDS;c9b8f31d-a7b8-47e8-a543-d2c42a44658b;2 Time: 2021-09-10T06:26:38.4804852Z.
NonProdWords
Load was cancelled by an error in loading a previous table.
Virtual Agent
Load was cancelled by an error in loading a previous table.
Virtual Agent Component
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Virtual Agent Flows
Load was cancelled by an error in loading a previous table.
RPA
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
RPA Sessions
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Platform User
Load was cancelled by an error in loading a previous table.

_Originally posted by @philipbullard in https://github.com/microsoft/coe-starter-kit/issues/1050#issuecomment-916664755_

**Comment by manuelap-msft** [comment]
Hello,

it looks like you are hitting a product limitation: 
`Microsoft SQL: Return records size cannot exceed 83886080. `

Check our guidance for which dashboard to use when here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#which-dashboard-to-use

If you have installed the CoE Starter Kit in a Production environment, you will have to use the CDSLegacy_ dashboard to overcome this limitation.
If you have installed the CoE Starter Kit in Dataverse for Teams, you may have to modify the dashboard to not pull in this table in order to use the Dataverse_ dashboard.

Hope that helps,
Manuela

**Comment by philipbullard** [comment]
It does thanks, legacy does work, tried it last night. Still not sure about the column mismatches. Will investigate more.  You can close the bug unless u want to investigate this more

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by manuelap-msft** [comment]
The Dataverse_ version is optimized to work when the CoE kit is installed in Dataverse for Teams (for which the CDS Legacy connector in Power BI is not available), and connecting the Dataverse_ dashboard to Dataverse for Teams I don't get a column mismatch and it works fine. I'll investigate loading the dashboard when the kit is installed in a Production environment to see if I repo there.

But the main issue that you won't overcome with the Dataverse_ version is the limitation on how much data can be loaded with the Dataverse Power BI connector (this error: Microsoft SQL: Return records size cannot exceed 83886080. Make sure to filter result set to tailor it to your report.)
