### ISSUE TITLE
[CoE Starter Kit Deployment]  new version not deleting previous version

### ISSUE THREAD

**Issue by IanRoJohn** [microsoft/coe-starter-kit#1151]
### Describe the issue

Have an issue where version 2.75 was deployed over 2.0, 2.75 has been deployed but version 2.0 deletion is failing because of a number of dependencies. 2.75 was deployed on August 13 and in the latest version for September the guidance is to install components in a specific sequence. In order to resolve this issue is an option to delete 2.75 and re-install with the latest version in the sequence suggested.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.10 -> 2.75

### What app or flow are you having the issue with?

Solution install blocked

### Anything else?

Hope this is right forum for this

**Comment by Jenefer-Monroe** [comment]
Hello a few people have hit something similar. There seemed to be a product bug around a casing mismatch for an old connector. 
Please download the [newest version of Core (3.11)](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2021/CenterofExcellenceCoreComponents_3.11_managed.zip) and install in the following manner. 

**Try to upgrade using the classic UX** 
Solutions > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/89584709/131683084-18ee4068-873a-445c-929c-b29efcb592af.png) 

Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/89584709/131683360-817b7c64-bc36-4eb5-9429-d1329001c9d3.png) 

Choose File (the solution file you were trying to install) > Next > Next >  
![image](https://user-images.githubusercontent.com/89584709/131683790-4e7d1f9a-62a1-4ba1-aa09-84d7160928ac.png) 
![image](https://user-images.githubusercontent.com/89584709/131683907-cf80ef88-1b33-49f1-aa6c-160d825f8d7d.png) 

Leave at Action=Upgrade but chose Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/89584709/131683695-fc0f19ab-a289-4854-8a6f-d6b5173b0f64.png)

**Comment by Jenefer-Monroe** [comment]
When that completes, if there are still two versions of core in place, you should now be able to delete the old one.

**Comment by IanRoJohn** [comment]
Hi

I tried following the process but are getting this error

Solution manifest import: FAILURE: Holding solution CenterofExcellenceCoreComponents_Upgrade already exists.

This is because version 2.75 is deployed and failed to delete 2.0. Should I delete 2.75 and then apply this update. Or once remove 2.75 apply updates in order.  The order recently recommended was in this order.

1 Upgrade Nurture
2 Upgrade Gov
3. Update audit logs
4. Upgrade Core

Thanks in anticipation of help.

Regards

Ian John
Principle Technologist

[Redspire-Microsoft-logo-medium]
  Suites 507-511, Baltic Chambers
  50 Wellington Street
  Glasgow, G2 6HJ
  07818581059
  ***@***.******@***.***>
  www.redspire.co.uk<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.redspire.co.uk%2F&data=04%7C01%7C%7Cc2a754df1198466a693d08d9534c7125%7C159cb7bff8044d9baf665bd443f28182%7C0%7C0%7C637632410045506892%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=acffgFdzYAxRhlohFctKt3FOkCvSOvzCnIDCeYuavDg%3D&reserved=0>
  ***@***.*** <https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fredspire-ltd&data=04%7C01%7C%7Cc2a754df1198466a693d08d9534c7125%7C159cb7bff8044d9baf665bd443f28182%7C0%7C0%7C637632410045506892%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MEMpAlvMet1QbBR8PGzl2%2FOEjUL8PQdDqspi0WeNaAk%3D&reserved=0> ***@***.*** <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fredspirecrm&data=04%7C01%7C%7Cc2a754df1198466a693d08d9534c7125%7C159cb7bff8044d9baf665bd443f28182%7C0%7C0%7C637632410045516848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DQaQ0M%2FNJB25SoZ8y2xDeWKkL0ZQqyM0s4zvLU9pqL0%3D&reserved=0> ***@***.*** <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2Fredspire&data=04%7C01%7C%7Cc2a754df1198466a693d08d9534c7125%7C159cb7bff8044d9baf665bd443f28182%7C0%7C0%7C637632410045516848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yizojdLywmZGXW0QwiJsaXUvEfnn%2BmL47C88NLP5uFo%3D&reserved=0>

**Comment by Jenefer-Monroe** [comment]
Please delete the _upgrade solution and try again with the latest version of core

**Comment by manuelap-msft** [comment]
Closing out old issues with no further action on the CoE team.
