### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs Failing

### ISSUE THREAD

**Issue by mduqueBasf** [microsoft/coe-starter-kit#1154]
### Describe the issue

The Flow: [Child] Admin | Sync Logs is failing since the last update. The error says: Action 'Parse_JSON' failed:  "message": "Invalid type. Expected Integer but got String."

The data coming from O365 comes with a different Json content than before.

![image](https://user-images.githubusercontent.com/64835119/132864350-dbe63df8-16fa-4383-89ff-bfcd13b6a000.png)

### Expected Behavior

It is expected to run with no errors

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/64835119/132864795-b96a5742-c32b-4272-939e-724d65420672.png)

![image](https://user-images.githubusercontent.com/64835119/132864817-88a27be7-9796-4501-ab97-9e31878d51c9.png)

### Anything else?

The data coming from O365 comes with a different Json content than before. Therefore the Flow is generating errors and not loading the Logs in COE Entity

**Comment by Jenefer-Monroe** [comment]
Can you please look at #1095? I believe you have stale schema. We simplified it in the past as we saw these changes from the backend come through.

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for the toolkit.
