### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to upgrade from 2.75 to 3.11 (Dependency with COE Settings)

### ISSUE THREAD

**Issue by ogiraud** [microsoft/coe-starter-kit#1155]
### Describe the issue

Tried to install the 3.11 version of Core components but failing with:
Upgrading solution failed. Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: Entity, ObjectName: COE Settings, Id: 03568229-21cd-4c10-985c-d4e8dc1a4b73, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: CanvasApp, ObjectName: admin_setflowpermissions_ce2bb, Id: f03bc934-beb9-47a4-80b2-9eb99b5b2465, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

I now have 2 versions of the solutions:
![image](https://user-images.githubusercontent.com/81678979/132876445-303b5d2f-0559-4bc4-a3e7-a3ffa649a615.png)

If I try to Apply upgrade:
![image](https://user-images.githubusercontent.com/81678979/132876606-619908ca-d73c-4ceb-8188-9f9cec7218d8.png)
I've the same error message

Also tried with the classic UI, and got following error msg:
classic: Solution Center of Excellence - Core Components cannot be deleted due to dependencies from other components in the system. Remove all dependencies to allow for solution deletion
Error code 8004f01f

Here are the dependencies details:
![image](https://user-images.githubusercontent.com/81678979/132876750-9fac33f3-1297-4e28-8e9d-8e066ffdedcc.png)
(and seems to be only included in the Core solution, nothing customized / system feature brought by the solution)

and I can see it from the COE Settings:
![image](https://user-images.githubusercontent.com/81678979/132877342-d8cd533a-05cf-4e59-ac7f-0622a84f40d0.png)

but don't know how to remove this dependency to move on ?!

Endly, I didn't find any unmanaged layer to remove:
![image](https://user-images.githubusercontent.com/81678979/132878807-da0177b8-7d30-4a60-8858-32bb5e17f581.png)

Thanks for your help

### Expected Behavior

Having the new solution 3.11 installed

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75 -> 3.11

### What app or flow are you having the issue with?

Solution install blocked

### Steps To Reproduce

Import process: Select the 3.11 solution
fill 3 of the 6 environment variables
Import button
wait during install... till failed with the related message

**Comment by Jenefer-Monroe** [comment]
**Please try to upgrade using overwrite via the classic UX**  

Solutions > Switch to Classic (note this can take some time, may have to try twice)  
![image](https://user-images.githubusercontent.com/89584709/131683084-18ee4068-873a-445c-929c-b29efcb592af.png)  

Click Import (fourth from the left)  
![image](https://user-images.githubusercontent.com/89584709/131683360-817b7c64-bc36-4eb5-9429-d1329001c9d3.png)  

Choose File (the solution file you were trying to install) > Next > Next >   
![image](https://user-images.githubusercontent.com/89584709/131683790-4e7d1f9a-62a1-4ba1-aa09-84d7160928ac.png)  
![image](https://user-images.githubusercontent.com/89584709/131683907-cf80ef88-1b33-49f1-aa6c-160d825f8d7d.png)  

Leave at Action=Upgrade but chose Overwrite customizations (note this is not the default) > Import  
![image](https://user-images.githubusercontent.com/89584709/131683695-fc0f19ab-a289-4854-8a6f-d6b5173b0f64.png)

**Comment by ogiraud** [comment]
Thanks Jenefer for the quick reply!
I already tried with the classic UI with the error message I gave...

but I just tried again, and now have this error:
![image](https://user-images.githubusercontent.com/81678979/132889638-9d1af2e8-e8be-4ee2-a64d-51df43cfa3e5.png)

should I remove the old 2.75 (or the new 3.11) one, and try again ?

**Comment by ogiraud** [comment]
I also can provide the downloaded error XML log if ever needed ?

**Comment by Jenefer-Monroe** [comment]
Yes please for both this and the previous error you were seeing if available. 

Do you have Audit Logs / Nurture / Governence installed? And if so, what version of those?

**Comment by ogiraud** [comment]
ok, here the last one, to rename in .xml format:
[importlog_CenterofExcellenceCoreComponents_3_11.txt](https://github.com/microsoft/coe-starter-kit/files/7145806/importlog_CenterofExcellenceCoreComponents_3_11.txt)

(unfortunately not available for the 1st try)

None of the other modules are installed

**Comment by Jenefer-Monroe** [comment]
That txt file didnt really help. 

I dont know what state you are in. We did remove the CoE Settings table, and Set Flow Permissions did rely on it in the past, but this install's copy of Set Flow PErmissions does not have that dependency. 

Do you have an unmanaged layer on Set Flow Permissions?

**Comment by ogiraud** [comment]
No, don't seem I've unmanaged layer for this app:
![image](https://user-images.githubusercontent.com/81678979/133045636-273d92cb-b9d8-4214-8851-ec70b196c1c0.png)

I've updated (not upgraded) as it was advised the whole Core components with the August release before
Any way perhaps to remove this dependency, or the faulty table ? or revert to the previous version ? or...

Thanks for your help

**Comment by ogiraud** [comment]
Hello Jenefer,

so, any clues here... so that we could move on and upgrade ?

Thanks

**Comment by manuelap-msft** [comment]
We released a bug fix version today, version 3.12, please try upgrading to that one https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2021/CenterofExcellenceCoreComponents_3_12_managed.zip now

This should take care of the dependency issues, and we have had a few customers successfully import it. Thank you!

**Comment by ogiraud** [comment]
Thanks Manuela for the update...
I tried this 3.12 version but still got an error :-( I think because of an already pending upgrade; as you can see I have currently 2 versions: the current 2.75, and the 3.11 which failed during the process:
![image](https://user-images.githubusercontent.com/81678979/133637258-5cc0b926-0c33-4c07-9610-9167f30ea7c0.png)

and I now try to add a 3rd one! Here are the downloaded logs for this last error (to rename in .xml)
[Center of Excellence - Core Components_import.txt](https://github.com/microsoft/coe-starter-kit/files/7178937/Center.of.Excellence.-.Core.Components_import.txt)

Thanks to let me know if I have some specific actions to perform before trying to upgrade with the 3.12 ?

**Comment by manuelap-msft** [comment]
Hello,

you should be able to remove the pending upgrade by clicking on the ... and remove upgrade. Only do this for the one where the name shows _Upgrade, and not the main one (2.75).

Thank you
Manuela

**Comment by ogiraud** [comment]
I haven't any solution with _Upgrade... northe possibility to "remove", however I can "Delete" the last ongoing to be installed:
![image](https://user-images.githubusercontent.com/81678979/133738394-74416c00-e6d5-4533-8445-fc98c3630d7e.png)

Is this what you've in mind with your advice ?

**Comment by manuelap-msft** [comment]
Yes, that's what I meant! I wasn't sure what the option was called exactly as I didn't have an example myself.

**Comment by ogiraud** [comment]
ok, that what I did... got a error message about a "timeout"... but the 3.11 solution has been removed!
I then tried to import 3.12, and still got an error message after a while:
![image](https://user-images.githubusercontent.com/81678979/133742898-69d03306-c586-4ca4-b60d-524bf31d5845.png)

Here are the logs if ever needed:
[Center of Excellence - Core Components_import.txt](https://github.com/microsoft/coe-starter-kit/files/7183618/Center.of.Excellence.-.Core.Components_import.txt)
(seems to be something related to API call)

I then tried a second time... took its time... but worked :-)
![image](https://user-images.githubusercontent.com/81678979/133745352-3975179d-753a-4123-a259-c0b1b547c0a7.png)

So, I think we are good now!
Thanks a lot for your great support & reactivity
Have a nice day

**Comment by manuelap-msft** [comment]
Awesome, thank you! Looks like the first time it failed with an intermittent time-out issue but then succeeded. That's great to here, glad it's all upgraded now! :)

I'll close this issue now, but please let us know if you need further help!
Manuela

**Comment by ogiraud** [comment]
Just have a little concern now: why the main part of the flows including in the solution are turned Off as a status ?
![image](https://user-images.githubusercontent.com/81678979/133755397-46fcc283-d5e7-4aa8-8764-c87f4fcf222b.png)

Are they just triggered automatically by the main one (Sync Template v3) or should we set them On ?

**Comment by manuelap-msft** [comment]
Hello,

we ship all flows as off on purpose to allow customers the flexibility to explore them first before running them if they want to!

Here are the steps to follow to turn them on - there's some child flows to configure first, and then you'll turn on the flows in a specific order
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

**Comment by ogiraud** [comment]
oh, ok...!
But I'm stucked when turning on some flows (Admin | Sync Template v3 (Connectors), CLEANUP - Admin | Sync Template v3 (Check Deleted) ... perhaps others ?)
![image](https://user-images.githubusercontent.com/81678979/133786059-35b0a24f-d382-482d-b965-a7d130a5271b.png)
(same error message, except for the line #)

**Comment by manuelap-msft** [comment]
Hello. All the flows have this pagination policy. It indicates that you are using an insufficient or trial license. 

Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes. 

See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles) 
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits) 

And hence our requirements for licenses as described in our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites).

**Comment by ogiraud** [comment]
ok... and should the license be assigned to the owner, or the user turning on the Flow ?
If appropriate, perhaps should be then better to set a service account owner of this solution, and assign it the proper license?
(and, in this eventuality, how to change the owner of all objects of this solution ?)

**Comment by manuelap-msft** [comment]
It should be assigned to whoever is linked to the connections - so probably the owner.
You can change ownership using the Set App Permissions and Set Flow Permissions app that are part of the CoE Kit.

**Comment by ogiraud** [comment]
and for flows where no connections are set (e.g.: CLEANUP - Admin | Sync Template v3 (Check Deleted)), how to know who should have a license ?

Thanks to mention these 2 great tools; I've already used them and noticed we cannot really change the primary owner of a Flow... but just add someone as owner. I'm then just a bit worried here because this toolkit has been first deployed with an old account (and hence used as primary owner for flows including in the solution). Now the solution is upgraded by someone else, but seems the owners aren't modified in the same exisitng flows ;-( . Do you have any clues to solve this type of situation ?

**Comment by manuelap-msft** [comment]
For flows that are in solutions, the owner can be completely changed. For flows outside of solutions, you can only add new owners. Both should work with the tools part of the kit or you can use the Power Automate Web API directly to update the flow https://docs.microsoft.com/en-us/power-automate/web-api#update-a-cloud-flow

The license should be assigned to the flow owner.

**Comment by ogiraud** [comment]
Hello Manuela,
can you please explain how to do when you say "For flows that are in solutions, the owner can be completely changed"? because seems I'm only able to add an owner with the UI, not changing it...
And, about the tools from the kit to change owner, it only shows the "old" flows/apps on our tenant (because of the missing licenses of the old owner, content is not up to date). Meaning that I cannot use it to add myself as a new owner, assign me a correct license and run it ;-(

So the solution would be to use the Web-API to change the flow owner, assign a correct license to the new owner, and turn on the flows ?
Is there a way to change the ownership of all apps/flows of a solution in 1 shot ?

Thanks for your help

**Comment by manuelap-msft** [comment]
Can you please open new issues for your new questions? I believe we have resolved your original issue in not being able to upgrade. We can track your additional questions as new issues, which helps us know what's open and what's closed and if the question comes up with  other users as well we can link to it. Thank you!

**Comment by ogiraud** [comment]
ok, np !
Thanks for your advice
