### ISSUE TITLE
@medicineshow This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1156]
@medicineshow This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

_Originally posted by @mikefactorial in https://github.com/microsoft/coe-starter-kit/issues/1101#issuecomment-915424319_

**Comment by medicineshow** [comment]
This is still happening in the Microsoft Teams version.

**Comment by Jenefer-Monroe** [comment]
re-openign original as its easier to read
