### ISSUE TITLE
CoE Starter Kit Turning Flow on Bad Request

### ISSUE THREAD

**Issue by mustajabrkhan** [microsoft/coe-starter-kit#1157]
### Describe the issue

I am receiving an error when I turn on the **CLEANUP - Admin | Sync Template v3 (Check Deleted) Flow:** 
Failed to activate component(s). Multiple errors occurred: 'BadRequest,BadRequest,BadRequest'. Please see details.

I suspected it may be a licensing issue. However we have these licenses applied which I believe should work: 

 
![licenses](https://user-images.githubusercontent.com/90003955/132923726-0563fa61-8598-42b7-8755-ee565235c650.png)

I did not see any where stating these licenses do not work. Any guidance will be appreciated. 

Thanks 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.7

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted) Flow

**Comment by Jenefer-Monroe** [comment]
Hello, this is known, the documentation explaining how to turn on Check Deleted now got delayed due to some oofs so you didnt have what you needed in documentation. Sorry.

Please see #1129

**Comment by manuelap-msft** [comment]
Docs are now live: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows
