### ISSUE TITLE
[CoE Starter Kit - BUG] Missing table in Dashboard-PowerPlatformAdminDashboard-2020-10-13

### ISSUE THREAD

**Issue by remzoa** [microsoft/coe-starter-kit#1161]
### Describe the issue

Hi. 

My PowerBI dashboard that is supposed to show me details about the PowerPlatform is not working. It`s throwing an error that it is not able to refresh the dataset. 

Error message is: 

Something went wrong
There was an error when processing the data in the dataset. 

Please try again later or contact support. If you contact support, please provide these details. 

Processing error: The key didn't match any rows in the table.
Cluster URI: WABI-NORTH-EUROPE-H-PRIMARY-redirect.analysis.windows.net
Activity ID: 6e755eb6-e1c5-47b6-9d3e-87b098c43d96
Request ID: f6bb9849-ee4c-4e6f-bdc2-7c24adb95bd8
Time: 2021-09-10 10:15:26Z

### Expected Behavior

That the PBI report shows the data needed.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.77

### What app or flow are you having the issue with?

PowerPlatformAdminDashboard

### Steps To Reproduce

After updating to version 2.77 the PBI report is not refreshing data. 

Error message can be found when trying to refresh the dataset, 

### Anything else?

I have tried to create the PBI dashboard again instead of trying to refresh the dataset. 

When trying to create the PBI dashboard again, I get an error on:

CoE Settings
"The key didn`t match any rows in the table". 

This causes all the other parts to fail as well, with error: 

"Loading blocked by failures with other queries".

**Comment by manuelap-msft** [comment]
Hello,

you will have to update to the latest version of the Power BI as well, not just the Core components solution file. The CoE Settings table was removed with a recent release, and we have removed all dependencies in our solution and from the dashboard. You are using a very old version of the dashboard, which will not work with newer version of the Core Components solution - they go hand in hand and have to be upgraded together.

Here's the latest version of the Power BI file for you to set up:
https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2021/CDSLegacy_CoEDashboard_202109.pbit

Thank you
Manuela
