### ISSUE TITLE
[CoE Starter Kit - BUG] The Flow owner is not displayed in all CoE flows and cannot be edited or added.

### ISSUE THREAD

**Issue by DrFdisk** [microsoft/coe-starter-kit#1162]
### Describe the issue

The Flow owner is no longer displayed in all CoE flows and cannot be edited or added.

### Expected Behavior

Owner should be viewed and edited in the Flows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

 3.11

### What app or flow are you having the issue with?

All CoE Flows

### Steps To Reproduce

CoE environment was newly created and the CoreComponents, AuditLogs and AuditCompunens of the August version were installed.
Unmanaged _layer were removed and updated to the Septemper update in the sequence Core, AuditLogs-, AuditComponens. 

### Anything else?

![CoE-Flows-Owners01](https://user-images.githubusercontent.com/76172630/133205729-7e705f6c-080e-430e-8442-dab17ef69489.png)

![CoE-Flows-Owners02](https://user-images.githubusercontent.com/76172630/133084309-72bec5af-8b2b-45f4-8805-763ac832a672.png)
In the Solution overview, Owner is shown.
![CoE-Flows-Owners03](https://user-images.githubusercontent.com/76172630/133205795-b573023b-0a16-4cf7-b9d2-8841d872dd4d.png)

Admin Dummy Approval Flow has an owner, and ist can be changed.
![Admin  Dummy Approval Flow](https://user-images.githubusercontent.com/76172630/133205889-31a8110d-5781-4f53-8742-7b49d4681f07.png)

**Comment by DrFdisk** [comment]
Info:
Admin  Dummy Approval Flow has an owner, and ist can be changed.
![Admin  Dummy Approval Flow](https://user-images.githubusercontent.com/76172630/133093344-c2087369-1db5-44cc-9886-31fe6727e579.png)

**Comment by manuelap-msft** [comment]
This issue is with the product and not the toolkit. We do not control what is shown to users here. You will need to reach out to the community or to product support.
