### ISSUE TITLE
[CoE Starter Kit - BUG] Not possible to activate CLEANUP - Admin | Sync Template v3 (Check Deleted)

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#1164]
### Describe the issue

Hey, 

I created a new environment and imported the core solution but I could not activate the first flow that is mentioned in the description on how to set up the component.

Here is the error description: 
![image](https://user-images.githubusercontent.com/62603605/133240131-9ea3ed33-f85c-41be-84b0-ed60d90fab4d.png)

It is all about that the flow can not be used as a child flow beceause it was never published.
I already tried to use the button in the solution to publisch all changes.

Thanks a lot for your work and your help!

### Expected Behavior

Flow activates with no problems.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Steps To Reproduce

1. import solution
2. enter values for environment variable
3. activate flow

**Comment by Cathi029** [comment]
And there are no connection references:
![image](https://user-images.githubusercontent.com/62603605/133241202-1b80e4ee-15a7-4b50-b1d2-e9c75760366c.png)

**Comment by manuelap-msft** [comment]
Hello,

please make sure you follow the following steps to activate and turn on the child flows:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

Thank you
Manuela
