### ISSUE TITLE
[CoE Starter Kit - BUG] Flow Resource table not updating

### ISSUE THREAD

**Issue by maniskt** [microsoft/coe-starter-kit#1166]
### Describe the issue

Hi, 

Wanted to check if Flow Resource table (admin_flowresources) is no longer being updated through sync flows. 

I'm not sure starting which version this behavior has changed.

If this table will no longer be updated, do we have plans to store the resource details (admin_resource, admin_resourceentity, admin_service, admin_sourcetype) in other tables or the master admin_flow table?

Regards,
Manish

### Expected Behavior

admin_flowresources table to be updated through sync flows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.0

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### Steps To Reproduce

Check the data in Flow Resource table from Core Components, and it is empty.

**Comment by manuelap-msft** [comment]
This table has never been updated before. We prepared it for some work we're planning, but due to frequent issues with API calls of our flows hitting limits we didn't complete this to reduce the amount of API calls the kit does.
