### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade from version 2.77 to 3.11 error

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#1169]
### Describe the issue

Hello COE Team,
Sorry to bother you again. I'm getting an error when importing "Center of Excellence - Core Components" version 3.11 to version 2.77.

The _Upgrade solution is still showing. 

![image](https://user-images.githubusercontent.com/68440710/133395646-6c7f5ef5-36ec-447d-b7b8-7fa14932667a.png)

Can you please confirm that I should go and import this in the classic UI again and perform an "update" like I did moving from version 2.1.6 to version 2.77? 

And to save me asking the question and using your time, do I need to do this with every import from now on?

This is the error I got.

![image](https://user-images.githubusercontent.com/68440710/133396335-2774f2b0-223f-42c0-845d-44860733af62.png)

Any help would be greatly appreciated. Thanks very much,

Garry

### Expected Behavior

No error when importing a solution. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Center of Excellence - Core Components" version 3.11

### Steps To Reproduce

Imported CenterofExcellenceCoreComponents version 3.11
Solution replaces version 2.77 and imports version 3.11
_Upgrade solution still showing.

### Anything else?

Nothing to add.

**Comment by paulculmsee** [comment]
Seeing very similar Garry. Can you take a close look at that error and confirm these dependencies?

ObjectName: admin_PowerAppsforAdminsCoEConnection, 
  DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval,  Gov
                                    
  ObjectName: admin_CDSCoEConnection, 
  DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request,  Gov

  ObjectName: admin_CDSCurrentEnvironmentCoEConnection, 
  DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, 

  ObjectName: admin_PowerAutomateManagementCoEConnection, 
  DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Gov

  ObjectName: admin_Office365UsersCoEConnection, 
  DependentComponentObject details: ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Gov

  ObjectName: admin_Office365UsersCoEConnection, 
  DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval Gov

  ObjectName: admin_Office365UsersCoEConnection, 
  DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request,  Gov

  ObjectName: admin_PowerPlatformMakeSecurityGroup, 
  DependentComponentObject details: Type: Workflow, ObjectName: Admin | Welcome Email v3,

**Comment by manuelap-msft** [comment]
Hey @GarryPope,

thanks for raising this! We have removed some components (one table and one connection reference) from the Core solution and that is causing those Upgrade issue. We are just exploring adding those back in (without using them) to see if that solves it - we have another customer test this at the moment, so if it works for them we will update our release! Will let you know!

Thank you
Manuela

**Comment by paulculmsee** [comment]
@manuelap-msft for the record I am trying to upgrade from core 2.2.20210707.3.

**Comment by manuelap-msft** [comment]
Hi @paulculmsee,

in Garrys error message, it highlights two dependencies - the admin_coesettings table and admin_httpwithazuread connection reference. We know about those - those are components we removed in the latest version. We're trying out adding them back in without using them to solve the issue.

Your dependency issues are with different components, so will be a different path to resolve - have you tried using Update, and classic import mode to Overwrite customizations to import? See some suggestions here #1130

**Comment by paulculmsee** [comment]
Yeah tried, but in my case, Latest Nurture has a dependency with one of the new components. Even in classic mode I dont even get the choice to change the update/upgrade behaviour.

**Comment by manuelap-msft** [comment]
@paulculmsee I see, I remember Jenefer mentioned that the other day. Sorry I don't have full context on this - but Jenefer prepared a solution for a customer with the same issue to try out if you want to try this as well - you can download it from here https://github.com/microsoft/coe-starter-kit/issues/1165#issuecomment-919169878

**Comment by GarryPope** [comment]
@manuelap-msft thanks for the update. Will wait to hear from you.

**Comment by manuelap-msft** [comment]
@GarryPope Please try upgrading to this version 3.12 https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2021/CenterofExcellenceCoreComponents_3_12_managed.zip - we have had a few customers who were successful with this version! Let us know how you get on, and apologies for the inconvenience.

**Comment by GarryPope** [comment]
Hello @manuelap-msft,

I've complicated matters and replied on a wrong thread! Haha. Let me add it all to my thread here so I don't mix anyone up. 

First, when I deleted the _Upgrade solution I got the below error.

![![image](https://user-images.githubusercontent.com/68440710/133771719-4caf23fe-04bd-4f67-b7ca-5c26a4c26007.png)](https://user-images.githubusercontent.com/68440710/133771641-d3f77673-a02e-4599-8a09-0161270abbee.png)

But that was a red herring, as I got this last time I deleted an _Upgrade solution and I just left it 10 minutes, refreshed the page and the _Upgrade solution had gone. So I was back to version 2.77.

I then tried to import the 3.12 solution you suggested and received the below error:

![image](https://user-images.githubusercontent.com/68440710/133771665-fd5aed4a-f98a-4897-8cf8-6613d767e9dd.png)


When I clicked Download log to see what was wrong, the message was:
"Failed to find connection references with logical name(s) 'admin_CoECoreHTTPAzureAD'. Please check if connection references exists.".

I hunted in the Default Solution and found the Connection Reference.

![image](https://user-images.githubusercontent.com/68440710/133771702-abba2a89-f953-4053-8a90-7e1537139b33.png)


Connection Reference

![image](https://user-images.githubusercontent.com/68440710/133771736-f8266997-c28d-4a02-8b32-0b0dcae2050c.png)


Any ideas why this didn't import please? Thanks very much,

Garry

**Comment by manuelap-msft** [comment]
Hi Garry,

first of all let me apologize - upgrading our solution should not be this difficult! We got into a bit of a pickle with connection references and it's proving hard to fix. 

Can you again delete the _Upgrade and try the attached 3.13 and see if that works for you?

Sorry about all that! Hopefully next month will be smoother
[CenterofExcellenceCoreComponents_3_13_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7185529/CenterofExcellenceCoreComponents_3_13_managed.zip)

**Comment by manuelap-msft** [comment]
Hello,

AMAZING! I'm very relieved this worked for you :) Thanks for confirming, and for your patience in working with us. Really appreciate it and hope you like the additions in the new version! I'll close this issue for now but please let us know if you have any issues!

Thank you
Manuela
