### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by streibk** [microsoft/coe-starter-kit#1170]
### Describe the issue

During the import of the Core Components version 3.11 from the September release it does not recognize that I have a version of Core components version 2.2.20210707.3 already imported. I also do not see the options to perform either an upgrade or update. Per the release notes it speaks to upgrade the Core which I was attempting to perform after successfully upgrading the Gov component and update of the Audit component. 

### Expected Behavior

Expecting to see the option to upgrade or update the Core Components given I have already import a version. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

NA

### Anything else?

![image](https://user-images.githubusercontent.com/58222800/133422579-d8c76293-2ba2-4984-80af-30962a513659.png)

**Comment by Jenefer-Monroe** [comment]
I've never seen this, and it appears to be a product bug. Please try with [version 3.12](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2021/CenterofExcellenceCoreComponents_3_12_managed.zip) which is the updated one for September. 

If that doesn't work try with the classic overwrite upgrade as shown here

Solution > Switch to Classic (note this can take some time, may have to try twice)  
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png) 

Click Import (fourth from the left)  
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png) 

Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import  
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png) 
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by streibk** [comment]
I attempt to import the core solution version 3.12 as you requested and still received the same results. I do not  have the option to upgrade nor for the matter update the Core components. It does not see that I have already imported version 2.2.20210707.3

![image](https://user-images.githubusercontent.com/58222800/134009895-91f73fb9-a201-4efd-813d-43dd08ad836e.png)

When I switch to classic view same results I'm not presented with the option to upgrade or 

![image](https://user-images.githubusercontent.com/58222800/134010334-9e9b28a5-e976-494e-bf23-723b4bc637d6.png)


![image](https://user-images.githubusercontent.com/58222800/134010442-6cfc5cd3-6afb-4419-8224-4ff49672efa3.png)

**Comment by Jenefer-Monroe** [comment]
I'm afraid this is a product issue then, and you will need to contact support. I've never seen this happen before.

**Comment by streibk** [comment]
That is the first out I took and they directed me to this.

**Comment by Jenefer-Monroe** [comment]
I'm sorry to hear that. There isn't anything we can do though. My suggestion is to re-open the support ticket and tell them that they can reach out to us if they wonder why they've been told to. They can reach out to manuelap-msft

**Comment by streibk** [comment]
I reached back out to technician that told me to go this route noting this issue and what you have advised. I also noted that I have opened other incidents around the CoE and this was the first time I was told to come here.
