### ISSUE TITLE
[CoE starter kit Issue] Governance Setup - Request Orphaned Objects Reassigned (Child) Flow Error

### ISSUE THREAD

**Issue by VansNogueira** [microsoft/coe-starter-kit#1171]
Hi, 
So, for the Governance components installation -> While activating a child flow named "Request Orphaned Objects Reassigned (Child)", we are getting the below error:

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'DynamicOperationRequestClientFailure' and message 'The dynamic operation request to API 'commondataservice' operation 'GetTable_V2' failed with status code 'BadRequest'. This may indicate invalid input parameters. Error response: {\r\n "status": 400,\r\n "message": "environment is null in the request.",\r\n "error": {\r\n "message": "environment is null in the request."\r\n },\r\n "source": "commondataservice-we.azconn-we.p.azurewebsites.net",\r\n "debugInfo": "clientRequestId: 83a15f1c-9bd7-40ee-8e2e-a89879df989d"\r\n}'."}}"

The flow in question does NOT use any action named 'GetTable_V2'. 

Any ideas?

**What solution are you experiencing the issue with?**
CenterofExcellenceAuditComponents_2.5_managed

Thanks in advance.

**Comment by manuelap-msft** [comment]
Hello,

we will need a bit more help to help you here! Can you open the failed flow and look at all the actions (some may be hidden in apply to each loops and conditions) and share a screenshot of the action that failed? If you can't turn it on, you may have to open it in Edit mode and see if there's any warnings anywhere. Can you confirm all connection references are and run only users for the flow are set?

GetTable is the action that's performed when you use a Dataverse action that displays the tables to pick from, so it's not something the flow logic itself does but something that in the background Dataverse actions use:
![image](https://user-images.githubusercontent.com/55705669/133473145-3c28609a-7dc0-4405-97c1-d5ed3739b7aa.png)

I believe your error happens with the Dataverse Legacy connector - if you navigate to the hold connectors for runas scope at the very bottom of the flow and look at the Get row action can you check if Current is set there as environment, or if it isn't - set the Environment to Current and the Table to Accounts
![image](https://user-images.githubusercontent.com/55705669/133473405-ddd30af7-7f08-4257-bfde-759a7f490eb5.png)

This should allow you to switch on the flow once everything is set, and we'll evaluate on our side removing this action.

**Comment by VansNogueira** [comment]
Hey Manuela,

You're right, the problem seems to be with the legacy connector. The value in the Environment field was not set to Current and the user cannot add the Current value there as well, see image below.

![image](https://user-images.githubusercontent.com/49518442/133576164-24d0ca6e-3a90-4973-9c7a-895c16d3e26c.png)


Error message: 
Could not retrieve values. The dynamic invocation request failed with error: {
  "status": 401,
  "message": "Authorization has been denied for this request.",
  "error": {
    "message": "Authorization has been denied for this request."
  },
  "source": "globaldisco.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 6d4a8dc3-7bb8-43ca-b729-b5d2-bdbc9746"
}.

**Comment by manuelap-msft** [comment]
Hello,

it's odd that you would get authorization denied here, as you're in the Current environment! However, it also looks like that action is not needed and we just had it in there for debugging / testing purposes. 

Can you click on the ... > Configure Run after of the action that doesn't work and check exactly what run after settings are set, then delete this action (the Get Row action), and then go to ... > Configure Run After on the the catch fake call 3 and configure the same run after settings as the Get Row had. 

That should work!
Manuela

**Comment by VansNogueira** [comment]
Hi Manuela,

That seems to have worked! Thanks very much for your help!!

**Comment by manuelap-msft** [comment]
Awesome, thanks for confirming!

Two notes:
1. Will look on our end at removing this action as well for the next release.
2. By editing the flow you will have added an unmanaged layer to it, so if you Upgrade the solution the next time this flow won't receive our changes as the unmanaged layer takes precedence. If you do want to receive our updates, you'll have to remove the unmanaged layer https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

I will open the ticket again so we can track this for the investigation on our side for the next release!

**Comment by manuelap-msft** [comment]
@Jenefer-Monroe could you investigate the Get Row action in this flow, it was causing issues for this user in turning on the flow and I think we may be able to remove it - or if we need it for catching errors, could we replace it with a more static action like compose or so? 

Thank you!

**Comment by Jenefer-Monroe** [comment]
believe we can remove these all together. testing.

**Comment by mikefactorial** [comment]
@VansNogueira This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
