### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade from 2.77 to 3.11 failed with ApplicationIdAlreadyInUse error

### ISSUE THREAD

**Issue by redleo85** [microsoft/coe-starter-kit#1172]
### Describe the issue

Hi,
we are having issues upgrading our CoE Core Components from version 2.77 to 3.11.

We already had issues upgrading the CoE from version 2.2.20210707.3 to 2.77, but succeeded.

When upgrading from 2.77 to 3.11 the installation fails.

We already successfully upgraded the Governance Components to version 2.5. We don't have Nurture or Audit Logs installed.

We tried the following steps to install the Core Components:
1. UPGRADING
2. UPDATING 
3. UPGRADING with Overwrite in Classic mode

All of these attempts failed with the following error message:

> CanvasApp import: FAILURE: Code: ApplicationIdAlreadyInUse Message: The application name '7a083aef-5053-46c5-9413-4ac11483478b' in tenant 'xxx' is already in use. Please specify a different name. Client Request Id: .

Error code: 80072352

### Expected Behavior

Core Components upgraded to 3.11

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.77

### What app or flow are you having the issue with?

Center of Excellence - Core Components version 3.11

### Steps To Reproduce

1. Upgrade Governance Components
2. Upgrade Core Components from 2.77 to 3.11

**Comment by manuelap-msft** [comment]
Hello,

can you please raise a Microsoft Support ticket through your usual channels to get support here: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support - it sounds like a product issue is impacting the upgrade here.

Thank you
Manuela

**Comment by GarryPope** [comment]
Hello @manuelap-msft,

Thanks so much for the reply! A couple of questions please as this failed to import. Sorry.

1. Do you want me to delete the CenterofExcellentCoreComponents_Upgrade solution first as it's still there? See below.
2. Do you want me to use the current UI and not the classic UI?
3. Lastly, do you want me to use Upgrade or Update?

![image](https://user-images.githubusercontent.com/68440710/133730276-4e291b52-4f02-4595-94f3-5f48618c5b8d.png)

Thanks very much,

Garry

**Comment by manuelap-msft** [comment]
Hello,

never apologize for questions :)

1. Yes, if you could delete the failed _Upgrade solution first
2. Current UI should work fine
3. Can you try Upgrade first, that should be fine. 

Let us know how you get on!

**Comment by GarryPope** [comment]
Hello @manuelap-msft,

 Thanks for the reply. I tried the above. 

First, when I deleted the **_Upgrade** solution I got the below error.

![image](https://user-images.githubusercontent.com/68440710/133757569-aa7b30c7-a72c-4683-8ba0-dd81c7760fa3.png)

But that was a red herring, as I got this last time I deleted an **_Upgrade** solution and I just left it 10 minutes, refreshed the page and the **_Upgrade** solution had gone. So I was back to version **2.77**.

I then tried to import the **3.12** solution you suggested and received the below error:

![image](https://user-images.githubusercontent.com/68440710/133758541-cf23fc6e-61e4-4021-ba26-fe05fd84a51d.png)

When I clicked Download log to see what was wrong, the message was: 
"Failed to find connection references with logical name(s) 'admin_CoECoreHTTPAzureAD'. Please check if connection references exists.".

I hunted in the **Default Solution** and found the **Connection Reference**. 

![image](https://user-images.githubusercontent.com/68440710/133758780-978bff7b-43ec-4cb3-9a58-f433092ff2a4.png)

**Connection Reference**

![image](https://user-images.githubusercontent.com/68440710/133758817-a05bc58e-b6c5-403c-afea-cd99b32373b3.png)

Any ideas why this didn't import please? Thanks very much,

Garry

**Comment by redleo85** [comment]
Hi @Garry and @Manuela,

I think you mean to have that conversation in this threat: [https://github.com/microsoft/coe-starter-kit/issues/1169](https://github.com/microsoft/coe-starter-kit/issues/1169)
You're question and answer are not related to this issue. 

Regards,
Leo

**Comment by GarryPope** [comment]
@redleo85 sorry! Titles were quite similar!

**Comment by manuelap-msft** [comment]
@redleo85 could you try this:

**Try to upgrade using the classic UX** 
And if that still does not work, use classic UX to overwrite
Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/89584709/131683084-18ee4068-873a-445c-929c-b29efcb592af.png) 

Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/89584709/131683360-817b7c64-bc36-4eb5-9429-d1329001c9d3.png) 

Choose File (the solution file you were trying to install) > Next > Next >  

Leave at Action=Upgrade but chose Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/89584709/131683790-4e7d1f9a-62a1-4ba1-aa09-84d7160928ac.png) 
![image](https://user-images.githubusercontent.com/89584709/131683907-cf80ef88-1b33-49f1-aa6c-160d825f8d7d.png) 
![image](https://user-images.githubusercontent.com/89584709/131683695-fc0f19ab-a289-4854-8a6f-d6b5173b0f64.png)

**Comment by redleo85** [comment]
Hi @manuela,
we had already tried that, but had the same result (error app id already in use).
We decided to delete the installed CoE Starter Kit components and do a fresh install.

**Comment by manuelap-msft** [comment]
Ok, thanks for letting me know! I'll close this ticket for now since it sounds like the clean install worked but please let us know if you have further issues!
