### ISSUE TITLE
[CoE Starter Kit - BUG] Apps visible in CoE Dashboard not visible in Set App Permission application

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1173]
### Describe the issue

We are seeing instances of applications that have owners and are visible in the Power BI dashboard yet when we try to locate the same app in the Set App Permission app, it is not visible. I have checked the filters in CoE Dashboard and they are not showing deleted apps.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

Set Permissions App

**Comment by medicineshow** [comment]
![image](https://user-images.githubusercontent.com/17124284/133439672-f114e136-428d-45ec-a7de-798c991fa131.png)

**Comment by manuelap-msft** [comment]
Hello,

can you confirm you have the Power Platform Admin SR security role assigned where the Set App Permission app is shared with you, and you have global Power Platform Admin access? 

Thank you
Manuela

**Comment by medicineshow** [comment]
Yes, I can confirm that I have both (and am the owner of the app)

**Comment by manuelap-msft** [comment]
Based on what I can make out on the screenshot you shared (please correct me if I didn't identify it correctly), the apps you highlighted as not seeing are SharePoint custom form apps - they are not standalone Power Apps, but apps tied to a SharePoint list. Those apps do not support changing ownership, as they're tied to the SharePoint list experience so they are excluded from the Set App Permissions app.

Let me know if I spotted that wrong,
Manuela

**Comment by medicineshow** [comment]
Thanks Manuela. I am very impressed with how you managed to deduce that from just a picture :) Is there a recommended way to deal with the ownership of these apps as we are in the process of cleaning up our Power Platform environment?

**Comment by manuelap-msft** [comment]
Hello,

haha, well if you look at something day in day out you start spotting patterns :)

I'm not sure, I know the Set App Owner does not work for SharePoint embedded apps
![image](https://user-images.githubusercontent.com/55705669/133603683-c7cba507-da8a-4d13-a3ca-14bd1ac361bf.png)

and even from the maker portal the share option is greyed out, meaning you can't share the app
![image](https://user-images.githubusercontent.com/55705669/133603819-447cdd72-5a5d-4cf5-b392-c25a3220d008.png)

From reading up here: https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form it sounds like anyone with anyone with SharePoint permissions to manage, design, or edit the associated list has co-owner rights to the app, but it's not possible to change ownership.

I couldn't find an existing ask for this in the Ideas forum but it may be worth raising it there https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas

**Comment by medicineshow** [comment]
OK, well thank you for that
