### ISSUE TITLE
[CoE Starter Kit - BUG] Clean up flows not respecting Admin eMail variable.

### ISSUE THREAD

**Issue by morismm99** [microsoft/coe-starter-kit#1176]
### Describe the issue

We enabled the admin clean up flows today. We have customized the following two flows, which are out of the managed solution:

a.	Admin | Archive and Clean Up v2 (Start Approval for Flows)
b.	Admin | Archive and Clean Up v2 (Start Approval for Apps)

Everything is going smooth so far with approvals being sent, but for some reason, am getting bounce backs, because these flows don't seem to be respecting the AdminEmail variable. That variable has been working fine on other admin flows we have customized. Basically, the Send an Eamil (v2) 2 action which is supposed to send an email to the AdminMail variable which is set to Admin eMail is sending it to a Microsoft 365 group. Also, the subject is showing a maker "Adelev@ppplatform.onmicrosoft.com." See the screenshot attached

![image](https://user-images.githubusercontent.com/72099434/133477494-6191b10d-6ad2-4ce9-ba92-5e1e846e8149.png)

All these bouncebacks are for flows/apps whose original maker/owner are no longer with our company.

### Expected Behavior

I would expect these emails:

![image](https://user-images.githubusercontent.com/72099434/133478022-bbc29383-6a94-4c89-8849-1e6954e3ecec.png)

To be sent to my team's distribution group as the variable is set in the CoE/Default solutions. Other flows which utilized that same variable and are outside of the solution(s) are able to use the variable(s) just fine.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.0

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Flows) - and the apps one

### Steps To Reproduce

1. Saved a copy of these two flows in our CoE Environment
2. Customized, mainly to change text in the email that goes to makers as a reminder to archive/pending flows/apps with approvals.
3. Saved these under a slightly different name, outside of the solution, and not added to any other managed/unmanaged solutions. 
4. Everything seems to be working fine, except for that second send an email action sending to a Microsoft address.

**Comment by manuelap-msft** [comment]
Hello,

we are using the Approval Admin environment variable for those scenarios, can you check that is set to the correct email address? 

Thank you
Manuela

**Comment by morismm99** [comment]
Variable is set correctly to my team's DL. Again, An example of another flow I have customized and taken out of the solution is the following:

PROD - Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created

It uses that same variable, and getting that email just fine.

![image](https://user-images.githubusercontent.com/72099434/133484952-392092c1-404c-47d7-8081-b38bf3d0770f.png)

**Comment by manuelap-msft** [comment]
There's a second environment variable called Approval Admin. Can you check that as well please:
![image](https://user-images.githubusercontent.com/55705669/133486284-bc8f5edb-186d-4eb4-af7c-bbe26b1c675f.png)

Thank you
Manuela

**Comment by morismm99** [comment]
Yup, have that one set correctly (to my preference as well) 
![image](https://user-images.githubusercontent.com/72099434/133491094-dabaefb5-5a89-4b79-863a-58bcc9139daa.png)

**Comment by manuelap-msft** [comment]
Interesting, it looks like everything is set correctly in our latest version but you're on a version that's a bit older which may have a bug there. I'll try and navigate you the point where I think the issue occurs and you can check if we left a hardcoded test email address in there. 

1. Edit the flow
2. Check if the ApprovalAdmin variable at the top pulls the information from the Environment Variable
![image](https://user-images.githubusercontent.com/55705669/133495016-c4f7f319-94d6-4394-bd1b-a05b2acae225.png)
3. Navigate further down in the flow and find the Case 404 New Orphan section and check if the variables there set the correct value for varAssignee or if they hardcode something 
![image](https://user-images.githubusercontent.com/55705669/133495077-b413c497-8d66-4292-b0b1-1ae90872a584.png)

Thank you
Manuela

**Comment by morismm99** [comment]
Everything looks good there:

![image](https://user-images.githubusercontent.com/72099434/133497964-0c3d35b1-fb5c-41c8-bad3-766656685701.png)

![image](https://user-images.githubusercontent.com/72099434/133498066-c188f351-465e-40c5-8baa-50a98f09765a.png)

![image](https://user-images.githubusercontent.com/72099434/133497928-3267c6d1-320d-4dbd-80bd-aee919591461.png)

Again, it's working fine for makers who are still active/in the company, all those approvals going out just fine...but yeah, everything looks solid on these two flows...just not sure why those actions are not respecting the variables.

We have the August release installed. We wait until end of the new month to install that month's release.

Worst case scenario, I can see about manually overriding the variable for next week's run in each of the flows.

Thanks for the help Manuela!

**Comment by morismm99** [comment]
Looks like the clean up flow for apps has completed...looking at one of those orphan apps, here are more details:

1. Approval failed: 
{
  "error": {
    "code": "InvalidApprovalCreateRequestAssignedToNoValidUsers",
    "message": "Required field 'assignedTo' contained no valid users in the organization"
  }
}

2. That then leads to the Send an Email (V2) 2 - Failure case:
![image](https://user-images.githubusercontent.com/72099434/133499194-b13f3a95-471d-4295-bb1e-b8aa74d02738.png)

Obviously, not respecting my variables.

**Comment by manuelap-msft** [comment]
I remember now that we did see an issue where Environment Variables were somehow cached for flows, could you try just turning the flow off and on again as that should refresh and pull the right environment variable value.

**Comment by morismm99** [comment]
I think I know what is going on...so until a few weeks ago, the only flows from the CoE starter kit solutions we customized was the Welcome Admin flow, and then we customized the Microsoft Teams Admin | Ask for Business Justification....flow. These customized flows are not in any solution...wonder if I add them to the Default solution, if then the variables will be respected...that has to be it.

**Comment by manuelap-msft** [comment]
That could be it too.. I have not tested this myself yet. But also try turning them off and on, we have definitely seen some odd caching issues in the past there.

**Comment by morismm99** [comment]
I had read about the recommendation of adding them to an "unmanaged" solution, but since we are not customizing that many, I had not added them to an unmanaged solution. I am going to do that and see if I can then pass those environment variables correctly.

**Comment by morismm99** [comment]
@manuelap-msft I think that is it. Any customized flows from the CoE Starter kit solutions need to be added to an unmanaged solution, in order for the Environment variables to be accessible/passed. I think we can close this one. Will monitor the next time these run, but I can already see the environment variables become an option now when I go edit those flows in a new unmanaged solution I created.

**Comment by manuelap-msft** [comment]
Awesome detective work!! Let me know if that worked for you, and if it does we'll include a note about it in our documentation about extending the kit as well :)

**Comment by mikefactorial** [comment]
@morismm99 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
