### ISSUE TITLE
Include link of flows/apps in approval email in app/flow clean up admin flows.

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1177]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/1175

<div type='discussions-op-text'>

<sup>Originally posted by **morismm99** September 15, 2021</sup>
Just an idea/suggestion. Could we look at including a link to the flows/apps flagged for deletion per the following flows:

a.	PROD – V3 Admin | Archive and Clean Up v2 (Start Approval for Flows)
b.	PROD – V3 Admin | Archive and Clean Up v2 (Start Approval for Apps)

This would allow makers to click the flow/app and view which flow/app is being referenced per the approval.

I will look into making this happen with further customization on my end, but wanted to share what our makers suggested it as an improvement. 

Thanks,

Moris</div>

**Comment by wramey-lm** [comment]
👍 - upvote

**Comment by Jenefer-Monroe** [comment]
ready for Dec release
