### ISSUE TITLE
Importing a CoE solution, the Environment Variables screen don't show Environment Variables information

### ISSUE THREAD

**Issue by ThoNogueira** [microsoft/coe-starter-kit#1179]
I'm importing CoE using CenterofExcellenceCoreComponents_3.11_managed.zip and after configure connections and clicking Next, the next screen Environment Variables show  "10 updates needed" but just 10 textboxes without Environment Variables information. Only textboxes and other things empty. Somebody help me?
![image](https://user-images.githubusercontent.com/16336883/133542038-cbd2313e-0fdb-4222-a110-39c5a706918a.png)

**Comment by manuelap-msft** [comment]
Hello,

that looks like a product bug and not something we've seen before. Please raise a support ticket through your regular support channels for this (https://docs.microsoft.com/en-us/power-platform/admin/get-help-support)

Thank you
Manuela
