### ISSUE TITLE
Update audit log custom connector to filter for PP related entries only

### ISSUE THREAD

**Issue by zsolt-illes** [microsoft/coe-starter-kit#1182]
**Is your feature request related to a problem? Please describe.**
The current implementation of the "Admin | Sync Audit Logs" flow is querying all the entries from the O365 Audit log with the General content-type. In large enterprises this causes several problems. First, the number of entries might be massive, increasing the API usage footprint of the flow. Second, the audit log entries are visible in the flow history, which raises security concerns as the flow owner (and anyone with equivalent privileges) can have access to audit log entries if they wanted to.

**Describe the solution you'd like**
Please change the custom connector that is querying the O365 Audit log to filter only for entries that are related to the Power Platform. The filter would need to be $filter=(AuditLogRecordType eq 20) or (AuditLogRecordType eq 30) or (AuditLogRecordType eq 45) or (AuditLogRecordType eq 46) or (AuditLogRecordType eq 45).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by manuelap-msft** [comment]
Hello,

thanks for this suggestion - the Office 365 Management API does not have a content type for Power Platform events, https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference?view=o365-worldwide#working-with-the-office-365-management-activity-api - they fall under the Audit.General as you can see here.

Do you have a sample implementation where you are using the filter to only get Power Platform events? That would help us see how we can change the connector.

Thank you
Manuela

**Comment by zsolt-illes** [comment]
Hi Manuela, 

I acknowledge that today it is technically not possible. (It is even called out in the [Office 365 Management Activity API FAQs and troubleshooting](https://docs.microsoft.com/en-us/office/office-365-management-api/troubleshooting-the-office-365-management-activity-api) article.) 

I was hoping maybe it would be possible to escalate it to Microsoft and ask them to surface this capability? Would that be possible?

Thank you,
Zsolt

**Comment by manuelap-msft** [comment]
Hello,

I think you are referring to this point in the FAQ:

```
**Can I query the Management Activity API for a particular event ID or RecordType or other properties in the content blob?**

No. The Management Activity API provides all the event details for a particular log. It can be used to download the entire details, and then you can implement your own query logic on the downloaded data; for example, by using a custom application or a third-party tool.
```

Our team does not own the Office 365 Management API, we are just consumers of it, and are unable to escalate feature asks for this team - you can raise an ask yourself here: https://docs.microsoft.com/en-us/answers/products/m365

If this capability becomes available, we can add it to the CoE kit!

Thank you
Manuela
