### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot upgrade core solution

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#1186]
### Describe the issue

I am trying to upgrade a core solution but I am receiving errors. I tried to upgrade, Update, and also tried to use the classic version to overwrite the customization but still does not work. 

I looked for this app ID in the Model-Driven app but I cannot find it.

CanvasApp import: FAILURE: Code: ApplicationIdAlreadyInUse Message: The application name '1f5f9d9d-aa71-46d7-9217-d5076f3e76b3' in tenant '' is already in use. Please specify a different name. Client Request Id: c1301ab9-6d77-445f-a330-d192e153543e.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

Complete solution

**Comment by manuelap-msft** [comment]
Hello,

do you have a failed upgrade that is still in your environment - it typically shows two Center of Excellence - Core Components solutions and one will have _Upgrade in the Name column (not the Display Name)?

Thank you
Manuela

**Comment by AkashPatel136** [comment]
No it does not show me the _Upgrade. I only have the CenterofExcellenceCoreComponents

**Comment by AkashPatel136** [comment]
@manuelap-msft So I found the issue. In the core solution, the canvas app is called Admin-Power Platform Resource RMS. I am not able to edit this application or delete the application. I tried to delete using Powershell but I got a 204 error. I am the owner of the application. 

![image](https://user-images.githubusercontent.com/75992078/133679099-6a946e76-f5bf-4bb3-8ea0-1849ad715c87.png)
![image](https://user-images.githubusercontent.com/75992078/133679148-f1d50f0b-6976-4109-ba63-fce8661727f8.png)

**Comment by manuelap-msft** [comment]
Thanks for your detective work here! This seems to be a caching issue - could you raise a Microsoft Support ticket to get the engineering teams help with this? https://docs.microsoft.com/en-us/power-platform/admin/get-help-support 

Thank you

**Comment by manuelap-msft** [comment]
Actually could you try this:

**Try to upgrade using the classic UX** 
And if that still does not work, use classic UX to overwrite
Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/89584709/131683084-18ee4068-873a-445c-929c-b29efcb592af.png) 

Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/89584709/131683360-817b7c64-bc36-4eb5-9429-d1329001c9d3.png) 

Choose File (the solution file you were trying to install) > Next > Next >  

Leave at Action=Upgrade but chose Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/89584709/131683790-4e7d1f9a-62a1-4ba1-aa09-84d7160928ac.png) 
![image](https://user-images.githubusercontent.com/89584709/131683907-cf80ef88-1b33-49f1-aa6c-160d825f8d7d.png) 
![image](https://user-images.githubusercontent.com/89584709/131683695-fc0f19ab-a289-4854-8a6f-d6b5173b0f64.png)

**Comment by AkashPatel136** [comment]
Hi Manuela,

I have already tried this and did not work.

Best Regards,
Akash Patel
Automation | Power Platform | Application Specialist
+1 302 773-3228 o  |  +1 302 276-4412 m

The Chemours Company
1007 Market Street, Room 455-18
Wilmington, DE 19899
***@***.***
LinkedIn<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fchemours&data=04%7C01%7Cakash.patel1%40chemours.com%7C823c6157283f4d0b9ca908d8b3e9d8c5%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637457164259861732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=F%2Bk0k0uNZlH4575vE6YGsKHyrN%2Fx9GVTQHo170ksups%3D&reserved=0>  |  Twitter<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.twitter.com%2Fchemours&data=04%7C01%7Cakash.patel1%40chemours.com%7C823c6157283f4d0b9ca908d8b3e9d8c5%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637457164259871730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0NKuZNyO0AWz0bcY5DCO2qFeAFVvfwadWFvP%2F1ItiLg%3D&reserved=0>  |  Chemours.com<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.chemours.com%2F&data=04%7C01%7Cakash.patel1%40chemours.com%7C823c6157283f4d0b9ca908d8b3e9d8c5%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637457164259871730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Qq%2F%2BpKjgsIgKbvvRFZh%2FqTTnxHAeLXvBZ%2BquyQ7ZB8k%3D&reserved=0>



From: Manuela Pichler ***@***.***>
Sent: Friday, September 17, 2021 9:05 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Patel, Akash ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Cannot upgrade core solution (#1186)

External email. Confirm links and attachments before opening.


Actually could you try this:

Try to upgrade using the classic UX
And if that still does not work, use classic UX to overwrite
Solution > Switch to Classic (note this can take some time, may have to try twice)
[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F131683084-18ee4068-873a-445c-929c-b29efcb592af.png&data=04%7C01%7Cakash.patel1%40chemours.com%7C8547e069c33342e7af6708d979dbd2ef%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637674807308116586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jp8GSc0KZQ4M3%2BJZf6s6%2Fslf7pnC%2BQPtRXwpxESi4gc%3D&reserved=0>

Click Import (fourth from the left)
[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F131683360-817b7c64-bc36-4eb5-9429-d1329001c9d3.png&data=04%7C01%7Cakash.patel1%40chemours.com%7C8547e069c33342e7af6708d979dbd2ef%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637674807308126566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1Z8nmyYZ5uP04D6z6dEtAmy7UwIpL%2B1PNbpf1L9dGQ4%3D&reserved=0>

Choose File (the solution file you were trying to install) > Next > Next >

Leave at Action=Upgrade but chose Overwrite customizations (note this is not the default) > Import
[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F131683790-4e7d1f9a-62a1-4ba1-aa09-84d7160928ac.png&data=04%7C01%7Cakash.patel1%40chemours.com%7C8547e069c33342e7af6708d979dbd2ef%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637674807308136564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8AqwiaozTQTqITNSpiJ6IJKseicr487THTO505jOceU%3D&reserved=0>
[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F131683907-cf80ef88-1b33-49f1-aa6c-160d825f8d7d.png&data=04%7C01%7Cakash.patel1%40chemours.com%7C8547e069c33342e7af6708d979dbd2ef%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637674807308136564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LjBud2bRgdWBlZrsfJtFUEL7OwuWQXy3Pwj0sblK1NI%3D&reserved=0>
[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F131683695-fc0f19ab-a289-4854-8a6f-d6b5173b0f64.png&data=04%7C01%7Cakash.patel1%40chemours.com%7C8547e069c33342e7af6708d979dbd2ef%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637674807308146563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=h%2BmAUA7J52D1MPeaCygpFMgnaYWXAtsKJOb5l%2F7VeBE%3D&reserved=0>

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F1186%23issuecomment-921780948&data=04%7C01%7Cakash.patel1%40chemours.com%7C8547e069c33342e7af6708d979dbd2ef%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637674807308146563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O%2FoLs%2B1QhCN78CiyfHk4y00OuucX6mp5SqG2421iyzY%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASDYYDQIHWVL3234BVODXP3UCM4JRANCNFSM5EFMKO6A&data=04%7C01%7Cakash.patel1%40chemours.com%7C8547e069c33342e7af6708d979dbd2ef%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637674807308156556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z7clnzwhCb%2BHuL3GmeiBOcEw9O3pF%2BGK9ewdC9365OA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cakash.patel1%40chemours.com%7C8547e069c33342e7af6708d979dbd2ef%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637674807308156556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4C%2F6JQ%2ByTZz%2FNXqeQxWW7xHRVJbKR2f%2BYvf4Ex1dpoI%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cakash.patel1%40chemours.com%7C8547e069c33342e7af6708d979dbd2ef%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637674807308166547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MyRZEUhMjKh2DsTEMIXO9jyLmQ%2B1zNTLXoUAjRc6WGg%3D&reserved=0>.

This communication is for use by the intended recipient and contains information that may be privileged, confidential or copyrighted under applicable law. If you are not the intended recipient, you are hereby formally notified that any use, copying or distribution of this e-mail, in whole or in part, is strictly prohibited. Please notify the sender by return e-mail and delete this e-mail from your system. Unless explicitly and conspicuously designated as "E-Contract Intended", this e-mail does not constitute a contract offer, a contract amendment, or an acceptance of a contract offer. This e-mail does not constitute a consent to the use of sender's contact information for direct marketing purposes or for transfers of data to third parties.


https://www.chemours.com/en/email-disclaimer

**Comment by manuelap-msft** [comment]
Thanks for confirming! Then unfortunately my only recommendation is to create a support ticket!

**Comment by Jenefer-Monroe** [comment]
closing out as no action for toolkit
