### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Center APP - App Settings and Launch does not work

### ISSUE THREAD

**Issue by remzoa** [microsoft/coe-starter-kit#1189]
### Describe the issue

When looking at apps in the Developer Compliance Center APP, and clicking on buttons for App Settings and Launch, it is supposed to open App Settings or Launch the app. 

This does not happen, it opens a new Tab, but gives error that the page cannot be reached. 

This is for apps that I am the creator on, mainly the CoE apps. 

### Expected Behavior

Open the App Settings for chosen app. 

Launch the chosen app.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2,5

### What app or flow are you having the issue with?

Developer Compliance Center

### Steps To Reproduce

Open app.
Click Details to any app.
Click App Settings/Launch

**Comment by manuelap-msft** [comment]
Hello,

this should work, and I don't repo the error in our environment. Have you updated the below two environment variables:
![image](https://user-images.githubusercontent.com/55705669/133782313-39fa7851-9709-4901-8cc4-352ee27e36bd.png)


Thank you
Manuela

**Comment by manuelap-msft** [comment]
Closing as no further action on the CoE Starter Kit required.
