### ISSUE TITLE
[CoE Starter Kit - PRODUCT BUG] Connector not populated in 'Action Flow Details' table

### ISSUE THREAD

**Issue by filcole** [microsoft/coe-starter-kit#1191]
### Describe the issue

The connector is not written to the 'Action flow details' table due to the information not being provided by the https://docs.microsoft.com/en-us/connectors/flowmanagement/#list-flows-as-admin action.  The list-flows-as-admin only returns the type and operationId and not the connector.

### Expected Behavior

I expected the connector and operationId to be output for any actions that use connectors, but it is not as shown below.

![image](https://user-images.githubusercontent.com/6078398/133931574-fdce1104-3f0f-4673-83e7-fdc086a53b64.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### Steps To Reproduce

1. Create trial environment
2. Install CoE Starter Kit core solution, following instructions up to and including https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-flows 
3. Run the 'Admin | Sync Template v3 (Flow Action Details)' manually
4. Examine the table 'Flow Action Details' with adv find, especially the columns: 'Action Type', 'Action Information' and 'Operation'

### Anything else?

This issue blocks https://github.com/microsoft/coe-starter-kit/issues/981 (Reporting on usages of deprecated actions)

The flow is expecting an ApiOperation object, yet this isn't output by the list-flows-as-admin action, see below for a screenshot from the 'Admin | Sync Template v3 (Flow Action Details)' flow.

![image](https://user-images.githubusercontent.com/6078398/133931799-1446a4d6-b47f-4cde-a095-78156f0d6ffa.png)

JSON output by the https://docs.microsoft.com/en-us/connectors/flowmanagement/#list-flows-as-admin action 

```json
{
    "body": {
        "value": [
            {
                "name": "02898523-9a20-0f52-f9a5-a4df1fcb2784",
                "id": "/providers/Microsoft.Flow/environments/a43c65f9-c051-44a6-ab44-89aaccc64bd8/flows/02898523-9a20-0f52-f9a5-a4df1fcb2784",
                "type": "Microsoft.Flow/environments/flows",
                "properties": {
                    "apiId": "/providers/Microsoft.PowerApps/apis/shared_logicflows",
                    "displayName": "DLP Request | Make approved policy change",
                    "state": "Started",
                    "sharingType": "CommonDataService",
                    "createdTime": "2021-09-19T13:23:08.8043619Z",
                    "lastModifiedTime": "2021-09-19T13:23:09.2719591Z",
                    "flowSuspensionReason": "None",
                    "environment": {
                        "name": "a43c65f9-c051-44a6-ab44-89aaccc64bd8",
                        "type": "Microsoft.Flow/environments",
                        "id": "/providers/Microsoft.Flow/environments/a43c65f9-c051-44a6-ab44-89aaccc64bd8"
                    },
                    "definitionSummary": {
                        "triggers": [
                            {
                                "type": "OpenApiConnectionWebhook",
                                "swaggerOperationId": "SubscribeWebhookTrigger"
                            }
                        ],
                        "actions": [
                            {
                                "type": "OpenApiConnection",             <-- MISSING CONNECTOR DETAILS
                                "swaggerOperationId": "GetItem"
                            },
                            {
                                "type": "Scope"
                            },
                            {
                                "type": "InitializeVariable"
                            },
                            {
                                "type": "OpenApiConnection",         <-- MISSING CONNECTOR DETAILS
                                "swaggerOperationId": "UpdateRecord"
                            },
                            {
                                "type": "Terminate"
                            },
```

**Comment by manuelap-msft** [comment]
Hello,

thanks for the detailed description! Based on your information, this does not sound like an issue with the CoE Starter kit or how it's gather information, but with the information that the connector returns. We can raise this as a feature request with the Product Group, but our team does not own those connectors. 

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Closing out as no action on the CoE Starter Kit required. If this information becomes available in the meta-data returned by this connector, we can pick this up as a work item.
