### ISSUE TITLE
[CoE Starter Kit - BUG] The dependent component Entity (Id=admin_coesettings) does not exist.

### ISSUE THREAD

**Issue by suck9999** [microsoft/coe-starter-kit#1192]
### Describe the issue

I ran into a problem while importing a Nurture Component. I checked the Log File and found message
_"The dependent component Entity (Id=admin_coesettings) does not exist."_

I think "admin_coesettings" entity  should have been setup since Core Components after finished.

I have checked entity list in solution it doesn't exist.
I have checked app "Power Platform Admin View" , CoE Setting 's section doesn't exist too.

**For more information :**
I imported file "CenterofExcellenceCoreComponents_3.11_managed.zip" for Core Components.
I imported file "CenterofExcellenceAuditComponents_2.5_managed.zip" for Governance Components.
I am importing file "CenterofExcellenceNurtureComponents_2.2_managed.zip" for Nurture Components.

### Expected Behavior

I would like to know :
- Solution
- Workaround

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

Import the solution

### Steps To Reproduce

1. Create new environment as sandbox type.
2. Setup Core Components following  : https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components
3. Setup Governance Components following  : https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components
4. Prepare content for consumption by solution objects following https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components
5. Import the solution by "CenterofExcellenceNurtureComponents_2.2_managed.zip" files.
6. The error will show on top of solution lists. "Solution "Center of Excellence - Nurture Components" failed to import:"
![image](https://user-images.githubusercontent.com/46931627/133959067-70080ed0-00ba-451d-8090-1dc2dcd422b7.png)
7. If you download log , you will see message "The dependent component Entity (Id=admin_coesettings) does not exist.  Failure trying to associate it with CanvasApp (Id=7b1e48ea-dd3c-4fb5-b250-ecfce0eeaa17) as a dependency. Missing dependency lookup type = EntityNameLookup."
8. ![image](https://user-images.githubusercontent.com/46931627/133959090-c0e62348-edc9-423b-820f-577f5a5c8cdb.png)

**For more information :**
I imported "CenterofExcellenceCoreComponents_3.11_managed.zip" for Core Components.
I imported "CenterofExcellenceAuditComponents_2.5_managed.zip" for Governance Components.
I import "CenterofExcellenceNurtureComponents_2.2_managed.zip" for Nurture Components. (Found Error)

### Anything else?
I have checked entity list in solution it doesn't exist.
![image](https://user-images.githubusercontent.com/46931627/133958815-f3dba0af-a550-4dff-bf97-8409adb183bb.png)

I have checked app "Power Platform Admin View" , CoE Setting 's section doesn't exist too.
![image](https://user-images.githubusercontent.com/46931627/133958886-bda61d0b-dd94-4344-b8f9-bf94d462b47d.png)

_No response_

**Comment by manuelap-msft** [comment]
Hello,

we have removed a table (coe settings) from the solution but realize that it caused dependency issues with the upgrade - we uploaded a new version of core where this table was added back in (unused) to resolve the dependency issues, can you try upgrading with this https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2021/CenterofExcellenceCoreComponents_3_12_managed.zip

Thank you
Manuela

**Comment by theeraponft** [comment]
Dear Manuela

Now we can set up Nurture components after we upgraded Core Components by  your file "CenterofExcellenceCoreComponents_3_12_managed.zip".

Thank you.

**Comment by theeraponft** [comment]
Dear Manuela

Now we can set up Nurture components after we upgraded Core Components by your file "CenterofExcellenceCoreComponents_3_12_managed.zip".

Thank you.

**Comment by suck9999** [comment]
Dear Manuela

Now we can set up Nurture components after we upgraded Core Components by your file "CenterofExcellenceCoreComponents_3_12_managed.zip".

Thank you.

**Comment by manuelap-msft** [comment]
That's amazing, thank you for confirming!!
