### ISSUE TITLE
[AA4M] Deployment issue from Dev to UAT

### ISSUE THREAD

**Issue by krishnasjr** [microsoft/coe-starter-kit#1196]
### Describe the issue

When deploying from Dev to UAT by running the workflow in GITHUB, connections are not establishing in Power Automate Flows and Power Apps. So impact is to adding/updating the connections manually for each action which is taking more time i.e. 16 hours to do and up the respective flows. Also to establish the connections to load the forms without errors.

### Expected Behavior

When deployed the solution from Dev to UAT, can able to change the connection in environment variables then the Powerapp forms to be loaded without connection errors. Also sync the connections with Power Automate flows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1,70

### What app or flow are you having the issue with?

PGMSSolution

**Comment by Jenefer-Monroe** [comment]
Is this in relation to using the [ALM Accelerator tools](https://docs.microsoft.com/power-platform/guidance/coe/setup-almaccelerator)?

**Comment by krishnasjr** [comment]
> Is this in relation to using the [ALM Accelerator tools](https://docs.microsoft.com/power-platform/guidance/coe/setup-almaccelerator)?

Not sure but given YML file to run the workflow and deploy the solution from DEV to UAT

**Comment by Jenefer-Monroe** [comment]
I will assume it is then, as its the only tooling we offer in the space.

**Comment by mikefactorial** [comment]
@krishnasjr the functionality you are describing is not available in the ALM Accelerator GitHub YAML templates. The functionality is available in the ALM Accelerator for Advanced Makers in Public Preview https://github.com/microsoft/coe-starter-kit/tree/main/ALMAcceleratorForAdvancedMakers. However, this tool only works with Azure DevOps at the moment. We have it in our backlog to port the functionality in the AA4AM pipelines (https://github.com/microsoft/coe-alm-accelerator-templates/tree/main/Pipelines) to GitHub workflows #47.

**Comment by krishnasjr** [comment]
please assist on our issue on deployment from one environment to another

**Comment by mikefactorial** [comment]
@krishnasjr As I mentioned, this is outside the scope of the ALM Accelerator for Makers capabilities currently. The CoE Starter Kit tools are reference implementations. If you choose to modify them to suit your business case we would be grateful for any contributions back to the project, but we aren't currently investing in updates to the ALM Accelerator for Makers as we're focusing on unifying the ALM Accelerator for Makers (AA4M) and the ALM Accelerator for Advanced Makers (AA4AM). Closing this issue for now but please feel free to create a new issue if you have specific issues that we can address with the current functionality of the ALM Accelerators.
