### ISSUE TITLE
[CoE Starter Kit - BUG] Error messages during app release.

### ISSUE THREAD

**Issue by muetzep** [microsoft/coe-starter-kit#1201]
### Describe the issue

Hello all, 

I am in the process of implementing the Innovation Log feature in Microsoft Teams. The instructions are great, I have installed everything and it has worked so far. Now I am about to publish the Canvas App. However, there are a lot of errors. They all consist of the message: "Incompatible type or the name is invalid." Licensing-wise, I use Power Apps Premium. 

![Errors_IB](https://user-images.githubusercontent.com/91114936/134124929-8ed5fa04-0b2a-43a6-bd24-53bb872c9d02.PNG)

### What solution are you experiencing the issue with?

Innovation Backlog

### What solution version are you using?

2.4

### What app or flow are you having the issue with?

Innovation Backlog App

**Comment by Jenefer-Monroe** [comment]
Hello. I am not seeing this error. The app is working in Teams for us. When did you install? Was this an upgrade or a clean install? 
One thing to try is to delete the solution entirely and try again. Its possible if it was an older solution that you hit a bug we had in the product a few months ago.

**Comment by muetzep** [comment]
Hi Jenefer, 

the version is the current version of the backlog. It is also a clean installation in Microsoft Teams. The previous steps worked very well. I have also already started the whole process a second time. Attached once again is a complete screenshot.

![BL2](https://user-images.githubusercontent.com/91114936/134184811-f31a4a3b-5868-4a9c-89cb-b71d961eea3a.PNG)

**Comment by manuelap-msft** [comment]
I wonder if this is related to this known limitation of Teams:
https://docs.microsoft.com/en-us/powerapps/teams/known-issues-limitations#canvas-components

Have you tried playing the app?

**Comment by Jenefer-Monroe** [comment]
that is most likely the case thank you for investigating Manuela!

**Comment by manuelap-msft** [comment]
Closing out old issues with no further action on the CoE team. Please let us know if you are still facing issues.
