### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to start a Flow / ownership

### ISSUE THREAD

**Issue by ogiraud** [microsoft/coe-starter-kit#1202]
### Describe the issue

From a previous discussion, you advised to turn on the flows by following a specific order as described here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows
You also mentioned that the Owner of the flow should be correctly licensed: that's the case with a PowerAutomate per user plan

I managed to start the child ones; however, when starting with the 1st one, as owner of this flow I'm not able to turn it on;  failed in error with:
![image](https://user-images.githubusercontent.com/81678979/134177049-6591ba3b-c272-401a-9e0f-182857016f88.png)

For full info, this flow has no connections, and we're 2 owners: the account which installed the solution at the first time (account deactivated since), and I (who recently updated the solution, added recently, and assigned with a correct license)

Seems the issue is similar for all the other flows on which I'm not "primary" owner (but as owner) ?! How can we change it? because the included tool (set flow permission) doesn't allow me to choose the correct flow, and also change this value... Perhaps there's a way to change the owner in all flows & apps from this solution in 1 shot ?

Thanks for your help

### Expected Behavior

Having the useful flows turned on

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Steps To Reproduce

1. Go the detail pane of the flow from the solution
2. click Turn On
3. got the error message

**Comment by ogiraud** [comment]
yes Jenefer, I know.. as said, however seems I have the correct license:
![image](https://user-images.githubusercontent.com/81678979/134185797-f35c3799-27d7-4897-9d2e-5806a610de42.png)
![image](https://user-images.githubusercontent.com/81678979/134185829-aefe95f9-92b0-4913-9cd3-a2ace25ddfdd.png)

and this account is also owner of the flow:
![image](https://user-images.githubusercontent.com/81678979/134185897-f948491f-8998-4b7d-bef3-46e8d772d16c.png)

**Comment by Jenefer-Monroe** [comment]
You can change all of the connectors to use your identity instead. You do this by going to the default solution in the CoE environment, filter to Connection References, and then for each connection reference edit and add the identity with the permissions you desire to run under.
![image](https://user-images.githubusercontent.com/89584709/134186964-77e6c921-94c1-4b19-a280-942e749e9412.png)

**Comment by ogiraud** [comment]
it's already the case for all Connection references I see: I'm both owner:
![image](https://user-images.githubusercontent.com/81678979/134189747-4e5e8bc3-6b34-41d2-86a3-d00c60068da3.png)

and referenced in the connection:
![image](https://user-images.githubusercontent.com/81678979/134189768-1f881dc4-f30a-4e75-bb40-00ab7b622657.png)

**Comment by Jenefer-Monroe** [comment]
You are in a strange spot that I've never seen and are running up against product limitations. But we can try a few more things.
Can you open the Set Flow Permissions app in Core, browse to this flow, and add new owner there? 
![image](https://user-images.githubusercontent.com/89584709/134191353-39ca11cc-fec9-479b-a7b9-9f5cc4e6a466.png)

This uses some backend tricks to get around the ownership problems the product exhibits.

**Comment by ogiraud** [comment]
Unfortunately, as previously stated, I'm not able to choose the correct flow (ok for V2, but V3 not appearing in the list):
![image](https://user-images.githubusercontent.com/81678979/134194224-7d4ec8de-2085-43ec-a32d-bd5efd4eca9b.png)

hence not able to change this value :-(

(and when I try to go on the V2 one, it told me it has been deleted:
![image](https://user-images.githubusercontent.com/81678979/134194702-7844d4f4-2a38-4525-83f0-d7ff05699dea.png)
seems the flow list isn't updated with what is really existing ?!)

**Comment by Jenefer-Monroe** [comment]
More likely it was just never put into the inventory. 
You may have to start from scratch on a new CoE unfortunately. Do you know, what have you been using it for? Just the inventory? If so you wont lose anything from starting over.

**Comment by ogiraud** [comment]
Strange , because it was correctly working at the beginning, and we were able to find our flows and the ones from the toolkit here ?! Any idea why an issue now ?
Yes we're mainly using it for inventory... What do you mean by "starting from scratch" : reinstalling the solution on the environment? or rebuild all (environnement,...) ? If appropriate, anyway to avoid it (because we've made some customizations on tables , columns, views, and add app, choices...) ?
One more thing about ownership of such a solution: should we preferably use my account or a dedicated service account (for the permissions & licenses) ?

**Comment by Jenefer-Monroe** [comment]
Yes i mean create a new environment and re-set up the toolkit there. 
I'm afraid I'm out of ideas. I dont know what is happening to your setup. And since the toolkit isnt a supported feature, we arent able to help much further here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action available
