### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by SAIKARTHIK06** [microsoft/coe-starter-kit#1206]
### Describe the issue

Previously I have opened a Support request with the Power platform support with ID - 2108160040004788
Issue:
'Admin | Welcome Email v3' cloud flow part of Center of Excellence - Core Components

Issue description
'Admin | Welcome Email v3' cloud flow part of Center of Excellence - Core Components, The status of workflow is On but does not trigger. This flow gets triggered when a new record is created in the maker table. But the maker table does not get updated with new users since 4/2021.

### Expected Behavior

Admin | Welcome Email v3 should check for a new user added to the maker table and send them a welcome email with resource information.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.6

### What app or flow are you having the issue with?

Admin | Welcome Email v3

### Anything else?

Power platform support suggestion:

As we spoke on our conversation, I would like to confirm that after verifying the information provided with our specialists team, we understand the issue is not related to your flow functionality, your solution, or the security roles within your environment. 
 
We understand from our end that you are the global administrator within your tenant, and you have the access to make modifications and manage your solution, where all the components you need to make your flow work are. You are the owner of your flow and your tables within your tenant.
 
In this case, given that you are working with a Center of Excellence item and Core Components, we will advise you to contact the Center of Excellence support team, as they will have the corresponding tools to advise you, as we understand that the issue that you are having with your table not being updated seems to be related to the “Maker” table. 
 
You can find the information required to contact the Center of Excellence support team through the following link.
Also, I will leave here all the necessary documentation to review how your security roles were applied within your environment:
 
Security roles in Dynamics 365 Customer Engagement (on-premises) | Microsoft Docs
Manage user accounts, user licenses, and security roles (Dynamics 365 Marketing) | Microsoft Docs
Overview of solution-aware flows - Power Automate | Microsoft Docs
 
Please, kindly verify the information provided to confirm if this will solve your case. I will follow up with you as we agreed on the next couple business days to have further updates regarding your case.

**Comment by Jenefer-Monroe** [comment]
Hello. I'm having a little trouble following what is happening. 
It sounds like you are saying that the makers table isn't updating with new makers. Is that what you are saying? 

If so, can you please go validate that your inventory flows in Core are turned on, running, and passing? For example:
**_Admin | Sync Template v3
Admin | Sync Template v3 (Apps)
Admin | Sync Template v3 (Flows)_**

Please also note that makers only get added to the Makers table once. So if you are in the table, and add a new app/flow, you will not be getting added again. Its one row per Maker

**Comment by SAIKARTHIK06** [comment]
Correct. The maker table does not get updated and this is the reason the flow did not trigger. 

I have verified that the below flows are turned on. I do understand that the one row is added to maker table for 1 new maker. I have tested with a user who was new to the environment. Please let me know if you need any additional information.
Admin | Sync Template v3
Admin | Sync Template v3 (Apps)
Admin | Sync Template v3 (Flows)
![image](https://user-images.githubusercontent.com/91143380/134235184-0f684098-2c96-4454-a030-fec39d89e59c.png)

**Comment by Jenefer-Monroe** [comment]
I've never seen this happen so I am unsure how to proceed. 

Can you please confirm that the user identity installing and running the flow has has the Power Platform Admin Role?  
Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf) 

If not, this is a pre-req and you will not be able to gather inventory until you get this. Please see our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites)

If you do, then please test again as follows: 

1) With a new user, creating a new canvas app in a testing environment.
1) Browse to the **_Power Platform Admin View_** model driven app in Core and play it, 
![image](https://user-images.githubusercontent.com/89584709/134362453-61531b75-a2e1-4518-8dba-1a99995d2398.png)
1) Select the target environment and edit a field in its audit page, as shown here. Be sure you set this back when you are done testing here. 
![image](https://user-images.githubusercontent.com/89584709/134363232-fad704d4-a73b-4dab-9b5a-f77f87539415.png)
1) This will trigger **_Admin | Sync Template v3 (Apps)_** for just your target environment, wait till it finishes running. 
1) Check:  Did the app get added to the inventory?
1) Check:  Did the user get added to the inventory?
1) Open the run of the run of **_Admin | Sync Template v3 (Apps)_** that was triggered and return with pictures of what happens as shown here

![image](https://user-images.githubusercontent.com/89584709/134364103-51988ce3-34e1-4dc0-b0c0-29c080e4de35.png)
![image](https://user-images.githubusercontent.com/89584709/134364220-cd2d6614-efa5-41a9-865f-7105a552ade6.png)

**Comment by SAIKARTHIK06** [comment]
This is has been resolved. Thank you for sharing valuable information.

**Comment by Jenefer-Monroe** [comment]
to help others in the future, can you please share what was the issue?
