### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Archive and Clean Up v2 (Start Approval for Flows) / Admin | Archive and Clean Up v2 (Start Approval for Apps)

### ISSUE THREAD

**Issue by gt1209** [microsoft/coe-starter-kit#1207]
### Describe the issue

The mentioned flows are not resturing any data and I know I have inactive flows and apps in my tenant.

I created a new environment and installed CoE core and governance kit .

I enbaled the flows from Governance kit but it is not resturning any data.

[
![Issue](https://user-images.githubusercontent.com/91145167/134205071-d46c07aa-e89a-4669-b1b9-d9c8ed1eb0c3.JPG)
](url)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Flows)

**Comment by Jenefer-Monroe** [comment]
Have you run the inventory flows in core? If so, please go look at that inventory and find cases you expected to show up here.

**Comment by manuelap-msft** [comment]
Closing out old issues with no further action on the CoE team. Please let us know if you are still facing issues.
