### ISSUE TITLE
[ALM Accelerator - BUG]: export-solution-to-git failing

### ISSUE THREAD

**Issue by andrewgaskins** [microsoft/coe-starter-kit#1213]
### Describe the issue

When running the Push Changes To Git the export-solution-to-git keeps failing at Update Deployment Settings. I have followed the directions and rebuilt to make sure nothing is missing. On a previous repo this was working until today. All variables are set for the environments on each pipeline. 

Thanks for your help!

`Starting: Update Deployment Settings
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.190.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\04fa7624-c087-4356-822e-29e0f3048f44.ps1'"

    Directory: D:\a\1\s\SampleSolution\ALMAcceleratorSampleSolution

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        9/21/2021  10:14 PM                config                                                                
0
0
1
0
2
1
3
1
4
2
5
2
6
7
0
8
0
9
1
10
2
11
3
12
4
13
14
0
ConvertFrom-Json : Invalid JSON primitive: .
At D:\a\_temp\04fa7624-c087-4356-822e-29e0f3048f44.ps1:195 char:24
+     $configCriterias = ConvertFrom-Json '$(Data)'
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
##[error]PowerShell exited with code '1'.
`

### Expected Behavior

Update Deployment Settings should complete without error to allow the pipeline to complete without error. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20210727.1

### Steps To Reproduce

1. Setup new repo following all steps in the guide. 
2. Run AA4AM from environment
3. Open Settings and connect to the Org/Project/Repo
4. Select AAM Sample Solution or any solution and PUSH CHANGES TO GIT
5. All steps in the pipeline run without issue until the Update Deployment Settings. 

### Anything else?

<img width="676" alt="Screen Shot 2021-09-21 at 6 12 08 PM" src="https://user-images.githubusercontent.com/11320569/134263765-eed4919e-343b-4f65-b203-0af11b69d07e.png">
<img width="1425" alt="Screen Shot 2021-09-21 at 6 12 50 PM" src="https://user-images.githubusercontent.com/11320569/134263767-5cb28b30-a245-44e5-84b8-6d9db69bcf7c.png">

**Comment by mikefactorial** [comment]
Hey @andrewgaskins, we're preparing to release a new version in the next couple of days. There are some changes in the main branch of the microsoft/coe-alm-accelerator-templates repo that are likely causing your issue. As the pipelines may be out of sync with the version of the app you are using. You can either 
1. Get the latest released version of the pipeline templates from the releases in the microsoft/coe-alm-accelerator-templates repo and overwrite your main branch with those files. https://github.com/microsoft/coe-alm-accelerator-templates/archive/refs/tags/ALMAcceleratorForAdvancedMakers-July2021.zip
2. Wait for the new version to be released and upgrade to the latest solution version.

**Comment by andrewgaskins** [comment]
Thanks @mikefactorial 

I had just set these up to start a pilot so I am thinking it makes sense to wait a few days an implement the new version.

Thanks for your prompt reply!
