### ISSUE TITLE
[CoE Starter Kit - BUG] Duplicate Center of Excellence - Core Component solution on September update

### ISSUE THREAD

**Issue by Chaitra1006** [microsoft/coe-starter-kit#1214]
### Describe the issue

On trying to upgrade Core component from 2.1.6 version to 3.12 it was unsuccessful and reported the attached excel.
![image](https://user-images.githubusercontent.com/38909384/134294374-815ed88e-6091-4897-a62b-9935e1801880.png)
On solution Update it successful but started to show duplicate solutions as shown below
![image](https://user-images.githubusercontent.com/38909384/134293908-790ad6c7-e77e-4e76-a632-98ca6e204854.png)

Please confirm if it is the expected or did I miss any step mentioned in https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2021 during the update.
[Error Center of Excellence - Core Components_import.xlsx](https://github.com/microsoft/coe-starter-kit/files/7208232/Error.Center.of.Excellence.-.Core.Components_import.xlsx)

 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.6

### What app or flow are you having the issue with?

Core

### Steps To Reproduce

1. Go to solutions
2. Import Center of Excellence - Core Component solution to **upgrade**
3. On error
4. Import Center of Excellence - Core Component solution to **update**

**Comment by Chaitra1006** [comment]
one solution show history and another does not

**Comment by Chaitra1006** [comment]
Get below error when tried to apply upgrade on the solution which has history.
![image](https://user-images.githubusercontent.com/38909384/134317832-1e36f9b0-de84-43b8-88ad-a0159e038fad.png)

**Comment by Chaitra1006** [comment]
Did try to import using Classic view and got warning with log fil
[importlog_CenterofExcellenceCoreComponents_3_12.xlsx](https://github.com/microsoft/coe-starter-kit/files/7209700/importlog_CenterofExcellenceCoreComponents_3_12.xlsx)
e

**Comment by Chaitra1006** [comment]
Also experiencing the same issue mentioned in https://github.com/microsoft/powerapps-tools/issues/615 while importing Audit Log component

**Comment by Jenefer-Monroe** [comment]
The error you see from #615 is just telling you that the subscription is already going, so you can ignore that failure.

**Comment by Jenefer-Monroe** [comment]
I dont understand the state you are in for the upgrade attempts. But you can try to manually delete the upgrade / the later version. It looks like you have two 3.12's installed now.

**Comment by xmihux** [comment]
I had the same issue, you have dependencies in your Connection References. Have a look at your screenshot with 'Dependency Details'. Go to these flows in the newer solution version, remove connections and create new ones, so it doesn't use connection references from the old solution.  Then go again to the old version and check if dependencies are still there.
Only when dependencies are gone, select '...' next to the old solution version and click 'Apply upgrade' - the old version will then be uninstalled successfully.

**Comment by Chaitra1006** [comment]
@xmihux currently the dependencies are as shown below, should the Office 365 API Management connector be deleted?
![image](https://user-images.githubusercontent.com/38909384/134385285-4d4dafea-c6cb-431e-9229-6b0456fa2070.png)

**Comment by Chaitra1006** [comment]
Got it working by following the below steps:
1. First deleted the connection of  Office 365 Management API connection, it had no impact on the above dependency.
2. Later deleted the Audit Log solution 2.4 version which was imported from the Classic page.
3. Then successfully applied the upgrade on Core component solution. This step removed the duplicate Core component solution which did not have history.
4. Again imported the Core component solution from the Solution page to be doubly sure.
5. Configured the Office 365 Management API connector
6. Imported the Audit Log solution 2.4 version

**Comment by Jenefer-Monroe** [comment]
Sounds like you are resolved now, correct?

**Comment by Chaitra1006** [comment]
yes
