### ISSUE TITLE
[CoE Starter Kit - Audit Logs] Admin | Sync Audit Logs recurrence

### ISSUE THREAD

**Issue by xmihux** [microsoft/coe-starter-kit#1215]
**Is your feature request related to a problem? Please describe.**

In the newest release, Environment Variables are used for start time / time intervals, so there is no need to edit the Flow directly and create an unmanaged layer. 
This is a great improvement, however I think Environment Variables should also be used for flow recurrence - otherwise it has to be edited anyway.

Example: I want to get audit logs for the last 1 hour instead of the default 1 day. Each hour in 10 minute chunks. I set:
- StartTime-Interval to 1 
- StartTime-Unit to to Hour
- TimeInterval-Interval to 10
- TimeInterval-Unit to Minute

Now, the flow will still run daily, so I will get only 1 hour of audit logs each day unless I change recurrence.

**Describe the solution you'd like**

Use new Environment Variables for the Flow recurrence or, even more simple: just use StartTime-Interval and StartTime-Unit variables - that should work well together, unless I am missing something.

**Comment by Jenefer-Monroe** [comment]
Hello. This got missed as it wasnt tagged correctly. In the future please post CoE issues using our template: 
[aka.ms/coe-starter-kit-issues](https://aka.ms/coe-starter-kit-issues).

**Comment by xmihux** [comment]
Hi, sorry, I did use the template but I marked this as an idea rather than a bug. Thought it might not exactly be a bug. Anyway, thanks for picking this up and responding so quickly. You're doing a great job with the CoE.

**Comment by Jenefer-Monroe** [comment]
Thank you. I will be looking into this one soon

**Comment by Jenefer-Monroe** [comment]
There doesn't appear to be a workaround for dynamic context being unavailable for a trigger's parameters.
Please let me know if you have other ideas but as far as I can tell, we cannot put env variables in those fields in the trigger.

**Comment by xmihux** [comment]
Ah, you're right. I didn't realize there's a limitation with environment variables and they don't work for all triggers. Found this in the docs: 

> Using environment variables within triggers in Power Automate is currently only supported for a limited set of connectors. Supported connecters for triggers are SharePoint, Dataverse, and SQL server.

In that case I guess it has to stay as it is. Maybe something to add in the future :)

**Comment by Jenefer-Monroe** [comment]
Thanks for helping make CoE great!
