### ISSUE TITLE
[CoE Starter Kit - BUG] Core Components - CLEANUP - Admin | Sync Template v3 (Check Deleted)

### ISSUE THREAD

**Issue by xmihux** [microsoft/coe-starter-kit#1216]
### Describe the issue

Whether items are deleted from CoE or only marked as deleted, depends on the 'Also Delete From CoE' Environment Variable. 

Actions within the Flow assume that the value of the variable is lower case:

- Condition in "Initialize DeleteFromCoE" action
- Condition in "Check if they want to delete from CoE"

Both conditions check if the value equals "yes". If the value is set to "Yes", both evaluate to false and items are not deleted from tables.

At the same time, CoE setup instructions state:

> "Also Delete from CoE | Recommend Yes here to delete objects from the CoE inventory when they are deleted from the tenant. No will keep a record that an app or flow existed in the past"

_(notice "Yes" and "No" rather than "yes" and "no")_

### Expected Behavior

Change both conditions, so they are more bulletproof, using something like: 
`equals(toLower(parameters('Also Delete From CoE')), 'yes')`

Alternatively, edit the values in the documentation and state the importance of using lower case only.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Steps To Reproduce

1. Set the 'Also Delete From CoE' environment variable to 'Yes'
2. Run the cleanup flow.

**Comment by Jenefer-Monroe** [comment]
thank you for this very clear write up. This is an easy fix for us to make for Oct. 
Thanks for helping make CoE great!

**Comment by Jenefer-Monroe** [comment]
Local fixed for Oct. Added the **_the lower_** expression so its more versatile.

**Comment by mikefactorial** [comment]
@xmihux This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
