### ISSUE TITLE
AA4AM App: Update Solution Import Experience

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#122]
Currently, all builds are included in the import flyout in the app. This should be limited to successful builds and also include details about the build to assist users in choosing which version to import.

**Comment by mikefactorial** [comment]
@devkeydet I believe you had some additional input on this. Can you comment when you have a chance?

**Comment by devkeydet** [comment]
I think we want the app user experience to be focused making discovering the builds you are looking for easier.  I think the order of importance is.

1. Builds that represent the latest that's been merged into the main dev (aka vnext) branch of the solution and hence deployed to test (get latest from source control before I start a new work item scenario)
2. Builds that have been deployed to prod (hotfix type scenario)
3. Builds that are PR builds (userX started the work in branchA and submitted a PR.  userY needs to pick up the work still necessary based on PR feedback and wants to bring the work into a clean dev environment of their own to pick up where userX left off)

**Comment by mikefactorial** [comment]
The final solution here is to not use existing builds but instead provide the user with the ability to point to a branch and a folder within the branch that contains the source controlled solution. While this introduces some overhead in the time it takes to complete the import it ensures that the source controlled solution is imported every time. In the case of using existing builds there would be no guarantee that the build is representative of what is source controlled in the branch.
