### ISSUE TITLE
Add GCC guidance to release notes

### ISSUE THREAD

**Issue by aliyoussefi** [microsoft/coe-starter-kit#1222]
**Is your feature request related to a problem? Please describe.**
GCC customers at times are unable to update the toolkit with the latest release.

**Describe the solution you'd like**
Add verbiage clearly calling out if the latest toolkit release is compatible with GCC online customers.

**Describe alternatives you've considered**
Provide a solution that works for both commerical and GCC customers.

**Additional context**

**Comment by Jenefer-Monroe** [comment]
Hello. Without more specific feedback, there isnt much we can do here. 
We already do attempt to provide a solution that works for GCC and Commercial, and do have internal folks that test this for us and hand us bugs.
