### ISSUE TITLE
[CoE Starter Kit - BUG] Different environment counts in some reports

### ISSUE THREAD

**Issue by Jodarcy1** [microsoft/coe-starter-kit#1231]
### Describe the issue

Summary data at the top of the Overview - Power Apps, Overview - Power Automate and Environments reports are showing different environment counts.  Shouldn't they be exactly the same?  Our COE refreshes daily.

### Expected Behavior

Shouldn't the reports show the same environment count? Our COE refreshes daily.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.998

### What app or flow are you having the issue with?

N/A

**Comment by Jenefer-Monroe** [comment]
Can you share pictures please?

**Comment by manuelap-msft** [comment]
I have confirmed that on the latest version, they are showing the same numbers. Can you check what version you are on, you may need to upgrade the Power BI template to the latest version.

**Comment by manuelap-msft** [comment]
Hello,

the latest version of the Dashboard is [Dataverse_CoEDashboard_202109.pbit](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2021/Dataverse_CoEDashboard_202109.pbit). I can't repo this error so it looks like you may have some filters set on the pages that lead to different numbers being displayed - can you check on all three pages and make sure that the Filter pane looks like this and no other filters are set. If other filters are set, please remove them:

![image](https://user-images.githubusercontent.com/55705669/134925096-978cbca5-2864-4133-9cdf-54792399a46b.png)

If you do not see the Filters pane in your Power BI Desktop, click on View > Filters
![image](https://user-images.githubusercontent.com/55705669/134925468-384910dd-ebf5-4d21-ae07-4692dd29cdd3.png)


Thank you
Manuela

**Comment by manuelap-msft** [comment]
Hello,

please update to use the latest Dashboard available in the October release:
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-October2021

Let us know if you continue to see issues,
Manuela
