### ISSUE TITLE
[CoE Starter Kit - BUG] Filtering on environment in Desktop Flow report returns nothing

### ISSUE THREAD

**Issue by Jodarcy1** [microsoft/coe-starter-kit#1233]
### Describe the issue

In the COE - Desktop flows report, when filtering on environment, nothing displays even though the flow's environment name is in the table. This doesn't happen in cloud flows; I notice that the flows table has the environment GUID and the desktop flows table does not.

### Expected Behavior

Filtering on environment in desktop flows report should return data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.998

### What app or flow are you having the issue with?

N/A

**Comment by Jenefer-Monroe** [comment]
Can you please share pictures?

**Comment by manuelap-msft** [comment]
Are you  using the dashboard that starts with CDSLegacy_ or with Dataverse_? I have just checked on my end and this works as expected. Are you on the latest version?

**Comment by Jodarcy1** [comment]
I'm on version 1.998 and using COE Dataverse for Teams.

**Comment by manuelap-msft** [comment]
Hello,

please update to use the latest Dashboard available in the October release:
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-October2021

Let us know if you continue to see issues,
Manuela
