### ISSUE TITLE
[CoE Starter Kit - BUG] 'When a HTTP request is received' connector missing from admin_connector table

### ISSUE THREAD

**Issue by xmihux** [microsoft/coe-starter-kit#1237]
### Describe the issue

'When a HTTP request is received' connector is not added to admin_connector table.

Details:
Admin | Sync Template v3 (Connectors) flow uses 'Get Connectors' action to add all connectors, but HTTP connectors need to be added to the table separately. This is done inside 'Add HTTP connectors' condition where the following connectors are added:
- HTTP
- HTTP Webhook

But 'When a HTTP request is received' is not there.

### Expected Behavior

'When a HTTP request is received' connector is added to the admin_connector table in Admin | Sync Template v3 (Connectors) flow as described above.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

### Steps To Reproduce

1. Run Admin | Sync Template v3 (Connectors) flow.
2. Check admin_connector table

**Comment by HamishSheild** [comment]
+1 on this issue.  I implemented DLP policies for a client the other day and they had a handful of flows that were using this connector that ended up being suspended.  Would have been nice to see this as a connector being used before applying the DLP.

**Comment by wayneiles** [comment]
+1 to this too - same as Hamish, implemented DLP and this connector was not referenced in the Impact Assessment = flows disabled.

**Comment by mikefactorial** [comment]
@xmihux This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
