### ISSUE TITLE
Core solution "failed to import: ImportAsHolding Exception during StageAndUpgrade"

### ISSUE THREAD

**Issue by ryn802** [microsoft/coe-starter-kit#1243]
### Describe the issue

Receiving error message when attempting to import core solution: "Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade". 

### Expected Behavior

Import core components solution without error message

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Entire solution

### Steps To Reproduce

In COE environment, import core components solution.

### Anything else?

[Center of Excellence - Core Components_import_20210927_1610.txt](https://github.com/microsoft/coe-starter-kit/files/7239153/Center.of.Excellence.-.Core.Components_import_20210927_1610.txt)

**Comment by ryn802** [comment]
Attempted to upgrade by choosing "overwrite customizations" as shown in the upgrade instructions (https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2021) and received message "The import of solution: Center of Excellence - Core Components failed". 

[importlog_CenterofExcellenceCoreComponents_3_12.txt](https://github.com/microsoft/coe-starter-kit/files/7239271/importlog_CenterofExcellenceCoreComponents_3_12.txt)

**Comment by manuelap-msft** [comment]
Hello,

we're about to ship a new version of the CoE Starter Kit early next week and have addressed many issues related to upgrades with this coming release. Would you be able to wait until then to upgrade to the latest version?

Thank you
Manuela

**Comment by manuelap-msft** [comment]
The October release is live now
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-October2021

Could you please try the Upgrade again?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for CoE TEam
