### ISSUE TITLE
[CoE Starter Kit - QUESTION] - Orphaned Object Reassignment Flow

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#1244]
### Describe the issue

I just have a few questions regarding the new governance flows for orphaned objects.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#request-orphaned-objects-reassigned-child

1. Will a manager be notified every day of ALL orphaned flows?  For example, if they are notified on day 1 and take no action will they be notified on day 2, day 3, etc. until all are resolved?

2. What happens in terms on unified audit log events when a manager takes ownership and/or re-assigns to someone else?  Will there be events posted to the unified audit logs?

3. Would it be possible to provide an owner the option to export a copy of the flow? 

4. Could you add the ability for admins to select which options are enabled for managers?  For our particular use case exporting a copy might be the best approach. 

### Expected Behavior

N/A

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)
Request Orphaned Objects Reassigned (Child)

### Steps To Reproduce

N/A

### Anything else?

N/A

**Comment by Jenefer-Monroe** [comment]
Hello. 

1) That is correct. The flow returns the same set of flows every time it is run. 

1) To my knowledge these things are not written to the audit logs.

1) Exporting flows programmatically doesn't work for flows that have connection references, meaning it exports but cannot be imported later. As a result, we no longer do this anywhere in the toolkit. You could make a copy of the flow and provide this functionality though if you believe your organization doesn't use connection references . 

1) I'm afraid the way the flow is written does not make this an easy work item.

**Comment by robertcaretta** [comment]
1. Great! That would ideal. It would be preferable that managers continue to be reminded until all items are resolved.
2. Ok. We will test that.
3. For our use case we are focusing more on personal productivity flows. It would be unlikely users would leverage solutions. Understood though, there is that possibility. 
4. Just an idea. It could be useful to limit the types of actions managers are allowed to take. 

Thank for you the feedback.

**Comment by Jenefer-Monroe** [comment]
You bet, thanks for the thoughtful questions.
