### ISSUE TITLE
Approvals being created for Actively Run Flows

### ISSUE THREAD

**Issue by kashanico** [microsoft/coe-starter-kit#1245]
We noticed that the "Admin | Archive and Clean Up v2 (Start Approval for Flows)" flow is creating approvals for Flows that have been run recently (as of 2 days at least). This is a concern because we have applications and business processes that use these flows and if someone approves these they will break. 

Looking at the flow, it appears it does not look at the last run date at all and only goes on modified date. It would be beneficial that last run date be taken into account when creating deletion approvals for flows. 

Any suggestions to achieve this?

Thanks

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately we cannot look at when a flow was run for a few reasons

1) Flow runs are not available to us in a supported API, so we cannot track that a flow has run in the toolkit at all. 
1) Even if flow runs were available, we cannot assume that a flow running means it is useful as they run automatically without human intervention. 

However you can exclude individual flows from the process in the Platform Admin View today
![image](https://user-images.githubusercontent.com/89584709/135124893-278d1790-31b2-4673-9cfb-0f3e0df6dcb8.png)

And starting with the Oct release, you will be able to exclude entire environments from the process as well
![image](https://user-images.githubusercontent.com/89584709/132544098-4272c8cf-1663-4155-9497-dc4cf0ea9b4c.png)

Hope that helps and thanks for using the CoE
