### ISSUE TITLE
[AA4AM]: Deployment setting seems to be broken

### ISSUE THREAD

**Issue by rajyraman** [microsoft/coe-starter-kit#1246]
I cannot get Deployment Settings working in the latest release (https://github.com/microsoft/coe-starter-kit/releases/tag/ALMAcceleratorForAdvancedMakers-September2021). The variables seems to be coming through in the custom connector, but not in the canvas app.
![image](https://user-images.githubusercontent.com/5035266/135010714-7080de6c-662f-468b-952e-6a66786de1b3.png)
![image](https://user-images.githubusercontent.com/5035266/135010725-65ec69ef-ae72-476d-a6ad-85ed36f276f8.png)
![image](https://user-images.githubusercontent.com/5035266/135010738-d1b07243-9bb5-405b-970e-f2a40f99bd2a.png)

**Comment by mikefactorial** [comment]
@rajyraman Hey Natraj, 
Thanks for reporting. I just ran through a fresh install of the latest solution and am not seeing this behavior. However, the screenshots lead me to believe that it has to do with a policy that is supposed to be applied to GetBuildDefinitions Action in the custom connector. What's strange is in the environment I just tested in it doesn't show that policy applied to any actions but it does execute the policy based on the response I'm getting. The specific Policy is a preview policy which potentially could be the issue on your end if the environment doesn't have that preview feature. Can you check the policy on the connector and see if it exists / can be applied to GetBuildDefinitions action?

![image](https://user-images.githubusercontent.com/42348035/135096746-90b59034-863b-4e9b-b916-7c28821640b8.png)
![image](https://user-images.githubusercontent.com/42348035/135097073-8621a364-3093-4560-8d5f-eeb400d45a0c.png)

**Comment by rajyraman** [comment]
@mikefactorial - I uninstalled the solution and reinstalled it again. It seems to be OK now. Maybe something was cached.
