### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot import Nurture solution in Dataverse for Teams

### ISSUE THREAD

**Issue by formsandflows** [microsoft/coe-starter-kit#1248]
### Describe the issue

I get the following error when importing the Nurture solution in Dataverse for Teams:

**There are missing dependencies. Install the following solutions before installing this one: "CenterofExcellenceCoreComponents (3.0.20210907.2)".**

I have imported the Core and Governance solutions!

Versions used (from download on 2021-09-27 in the Assets section on the GitHub webpage https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2021):
- CenterofExcellenceCoreComponentsTeams_2_9_managed
- CenterofExcellenceAuditComponents_2.5_managed
- CenterofExcellenceNurtureComponents_2.2_managed

### Expected Behavior

To be able to import the solution.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

n.a.

### Steps To Reproduce

I have created a second D4T team. Here I also imported the Core and Governance solutions. The same error occurred when importing the nurture solution.

**Comment by manuelap-msft** [comment]
Please follow the steps in this post to import Nurture into Teams:
https://github.com/microsoft/coe-starter-kit/issues/1131#issuecomment-916274706

Note there is a special Nurture solution attached to this post that imports into Teams due to an issue with Dataflows (product issue). We did not want to include it in the release so as to not confuse people, as we're hoping the product issue is resolved soon.

**Comment by formsandflows** [comment]
This issue was already addressed. I did not see it at the open issues and that's why I reported it. Thanks for the quick reply!

**Comment by manuelap-msft** [comment]
Let me know if you face issues with this solution! We're testing the October release for next week now and we'll see if we can have the dataflow back in the Nurture solution.

**Comment by formsandflows** [comment]
![image](https://user-images.githubusercontent.com/35654198/135611220-0b23ad50-dd96-4553-a970-64e9c0efcf5f.png)

So far so good :)

**Comment by manuelap-msft** [comment]
YAY!
