### ISSUE TITLE
[CoE Starter Kit - BUG] Improve DLP Editor V2 'Exclude certain environments' experience

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#1252]
### Describe the issue

The user experience for editing DLP policies where the scope is 'Exclude certain environments' could be improved

1. Enable search for the Environments **Added to policy**
2. Rename the **Added to policy** tab to **Excluded from policy** to match the Power Platform admin center wording - this can be confusing and easy to get the DLP configuration wrong.

### Expected Behavior

1. When I search environments while viewing the Added to policy tab of the Environments step in the DLP Editor I expect the list of environments shown to filter based on what I have searched (like it does for the Available tab)

![image](https://user-images.githubusercontent.com/41050216/135048740-3eb55c29-66b5-4152-aa39-9a1e7833eebe.png)

2. The **Added to policy** tab should read **Excluded from policy** if the Scope is 'Exclude certain environments'

![image](https://user-images.githubusercontent.com/41050216/135049453-50c1f550-b180-4b6b-b966-12e73db5f39d.png)

![image](https://user-images.githubusercontent.com/41050216/135049255-f9c459f0-ba4f-49f8-aadb-9510e5a0f47c.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

DLP Editor V2

**Comment by manuelap-msft** [comment]
We have completed (2) renaming to Excluded from Policy for the October release.

We will revisit searching the added/excluded from policy environments in November. I will open a new ticket for this.

**Comment by mikefactorial** [comment]
@HamishSheild This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
