### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Connectors) taking 3+ days to run

### ISSUE THREAD

**Issue by wayneiles** [microsoft/coe-starter-kit#1254]
### Describe the issue

We setup our CoE in a new Prod environment on 16th Sept, and on Sunday 26th, our Power BI CoE Dashboard stopped refreshing, due to duplicate column names in a join function on two of the queries. I've tried starting from scratch using the Dataverse_CoEDashboard_202109.pbit, and initial load of the queries throws up the following errors:

App Connection Reference - A join operation cannot result in a table with duplicate column names ("owningbusinessunitname").
Flow Connection Reference - A join operation cannot result in a table with duplicate column names ("owningbusinessunitname").

I've looked a little deeper into the Flows that populate the Dataverse tables, and can see that the Admin | Sync Template v3 (Connectors) flow ran in 8mins for the first run, but has since escalated to take over 3 DAYS to run. Now I'm guessing it's this Flow that is the root cause of the Power BI problems, although could be way off with that assumption.

![image](https://user-images.githubusercontent.com/91537094/135077563-38ef351a-c05b-427d-809d-51e4d836cde1.png)

### Expected Behavior

Flow to run in a timely manner, Power BI report not to produce duplicate column name errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

**Comment by Jenefer-Monroe** [comment]
Hello. I've never seen this happen before, and the flow does not have any calls which should fluctuate that much in its run time. 
Can you please:

1) Make sure there are no [unmanaged layers on the flow](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). This will rule out any changes on your side that may have caused issues. 
1) Go to the Analytics tab for the flow and see if the number of actions has risen dramatically. It should not have as it doesn't vary depending on inventory or anything like that. 
![image](https://user-images.githubusercontent.com/89584709/135122456-02681fbf-9d96-4b16-a148-776dc4e17830.png)
![image](https://user-images.githubusercontent.com/89584709/135122769-ff5cdebc-efbb-4f72-809b-b8544b282e8d.png)

**Comment by wayneiles** [comment]
Thanks for the quick reply Jenefer!

There are no unmanaged layers on the flow or anywhere else in the solution . Action Requests fluctuate a fair amount, and the massive jump would coincide with the linked Power BI report giving us refresh errors.

![image](https://user-images.githubusercontent.com/91537094/135228697-b0921471-e6ec-4f81-8911-c1faff6cd863.png)

If I'm reading this right the 21st stands out - lowest number of actions but took 3.25 days to run?!

We're so early in our CoE journey it's feasible to uninstall the solution and start afresh and keep a closer eye on runtimes.

**Comment by Jenefer-Monroe** [comment]
Can you please open the run that took 3 days and the run that took 13 minutes and share some screenshots? 
I'd like to see:
1) Do they both go to the same environment here? And do they go to **_Set to default_**? 
![image](https://user-images.githubusercontent.com/89584709/135276171-817e18bb-9710-4ab1-a5aa-2db68ce6c848.png)

2) How many items do they loop in **_Apply to each Standard Connector_**? The same number? What is that number? 
![image](https://user-images.githubusercontent.com/89584709/135276425-aa221df2-a974-4da3-85e5-ffc31034f950.png)

3) Have you gotten any warnings in the flow itself or the email account it is associated with, about the flow running slower than expected, or being throttled?

**Comment by Jenefer-Monroe** [comment]
This is how we persist the GUID across runs. We dont get a GUID from the product in this case (like we do for apps/flows/etc) we have to generate one the first time we see a connector. And then subsequent runs we have to see if the connector has already been  inserted. 

While this seems like a lot of calls (~3k in my test tenant) its a pretty small flow for the CoE. My test tenant with ~1400 canvas apps takes about 60k API calls to collect canvas apps every day. So if they are getting throttled by this flow, then they are not going to be able to use the toolkit as is. Please see #917

**Comment by mikefactorial** [comment]
@wayneiles This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
