### ISSUE TITLE
[CoE Starter Kit - BUG] App Assessment - the line connection between step are not connected.

### ISSUE THREAD

**Issue by nowttttt** [microsoft/coe-starter-kit#1255]
### Describe the issue

App Assessment - we have found 2 issues
- the line connection between steps are not connected.
- the active step colour was wrong.

The first time that I use this app, we get a doubt, what is the step which we are currently on (reference to screen, it show the details of complexity but the active step that the system shown is Use Case)
And it didn't have a line connection between steps "complexity" and "use case", which make the user confuse about what is the next step.

![image](https://user-images.githubusercontent.com/32125374/135046650-495c2527-c839-4607-a096-212486c9afae.png)

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

App Assessment

**Comment by Jenefer-Monroe** [comment]
Hello. It looks like this repros when you change the sort order of the categories. We will investigate but in the meantime you can avoid the bug by reseting the sort order as shown here via the admin app.
![image](https://user-images.githubusercontent.com/89584709/135131703-6a988c4d-be69-40ec-8ddb-61699c9abcd1.png)

**Comment by Jenefer-Monroe** [comment]
ok we didn't have the sort order set on the navigation, so fix was to add that. 
![image](https://user-images.githubusercontent.com/89584709/135133313-e167a48e-539b-4162-89e5-49f0a6b85da3.png)

**Comment by mikefactorial** [comment]
@nowttttt This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
