### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Model Driven Apps) Failing

### ISSUE THREAD

**Issue by VansNogueira** [microsoft/coe-starter-kit#1260]
### Describe the issue

Hello,

Referring to the issue: [https://github.com/microsoft/coe-starter-kit/issues/819](url) ... was this flow failing because the environment was a trial then or is it something else maybe? Asking this because I'm having the same issue and it happens to different types of environments (production/sandbox/default) and I compared the values of the display name and URL (from Outputs) with the environments and they all seem the same and the user running the flow is a power platform admin but even though the flow is failing. I assume it's a problem with the legacy action/connection?

Any help appreciated.

![image](https://user-images.githubusercontent.com/49518442/135092021-4aa0211a-3b6e-44be-a2f0-6e8ab19f2d87.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Model Driven Apps)

**Comment by manuelap-msft** [comment]
Hello,

can you open a failed flow run and navigate to which action is failing and share the details there? You may have to open up a few of the scopes and conditions to see exactly what action has failed.

Thank you
Manuela

**Comment by VansNogueira** [comment]
Hi Manuela, 
See below, please.
![image](https://user-images.githubusercontent.com/49518442/135262918-817670f5-b0b1-449c-87f5-9906d41b12b5.png)

**Comment by Jenefer-Monroe** [comment]
Hello I believe you do not have the correct permissions to run the CoE toolkit correctly. Please see our [Prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites) for the full list, but I believe you do not have the Power Platform Admin role. Without this you can expect these flows to only collect / work for environments to which you have sysadmin rights. 

**Power Platform Admin Check** 
Can you please confirm that the user identity installing and running the flow has has the Power Platform Admin Role?  
Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)

**Comment by VansNogueira** [comment]
Hi Jenefer, 

Thanks for you response, but that's not the case. The user running the flows etc is assigned to the PP admin role and has all permissions needed.

![image](https://user-images.githubusercontent.com/49518442/135286721-930bdec5-3693-449c-99cf-d45b41d53312.png)

**Comment by Jenefer-Monroe** [comment]
Can you please validate that this is the identity running the flow by going to the flow and opening the connection references? 
![image](https://user-images.githubusercontent.com/89584709/135292757-65421c6f-8660-4a7c-a45a-fda4fed1ad3f.png)
![image](https://user-images.githubusercontent.com/89584709/135292896-c0fcbf89-6028-433b-b94c-8ad91b0f0a28.png)

**Comment by Jenefer-Monroe** [comment]
oops sorry did not mean to close

**Comment by VansNogueira** [comment]
Hi Jenefer,

I can confirm that this user is the one being used in the connection references. See below.

![image](https://user-images.githubusercontent.com/49518442/135294548-5613acf3-197e-4262-85c1-e8757c83c6a7.png)

**Comment by Jenefer-Monroe** [comment]
The icon for those connectors are the icons I see for broken connections. Can you click edit on the flow please? See if it asks you to recreate the connections?

**Comment by VansNogueira** [comment]
No, it didn't ask the user to recreate connections :/ What do you suggest? Remove and create again anyway?

**Comment by Jenefer-Monroe** [comment]
Is this the only flow that this is occurring to? Can you go look at a passing flow in the solution and show me what its connectors look like?

**Comment by VansNogueira** [comment]
Yes, this flow seems to be the only one with this issue, the other flows are working fine, see a screenshot of another one with just successful runs:

![image](https://user-images.githubusercontent.com/49518442/135302966-5a8e34f5-a27d-4bd9-963c-425b0f9026bf.png)

**Comment by Jenefer-Monroe** [comment]
ok then I will assume that the icon you are seeing is not actually relevant.
Is the PVA sync flow passing? It uses a similar technique to get the data.

**Comment by Jenefer-Monroe** [comment]
when you say this:
![image](https://user-images.githubusercontent.com/89584709/135313041-ef044f20-bcb1-41c2-bf68-dfa04abd523d.png)

Can you clarify, is someone besides **_contractor.stephen...._** opening / editing the flow? 
What type of user is **_contractor.stephen...._**?

**Comment by Jenefer-Monroe** [comment]
And then lastly for now, please open the trigger in one of these failures and click **_Show raw outputs_**
![image](https://user-images.githubusercontent.com/89584709/135313868-da72867d-042a-4d36-bbd9-71d90f52fc2d.png)

In the pain that opens you will see a property like the below, please follow the link to see if it works for you. 
`"admin_environmentcdsinstanceurl": "https://orgabcde123.crm.dynamics.com/",`

Try both as a regular user and as this  **_contractor.stephen...._** user

**Comment by VansNogueira** [comment]
Hi,

The PVA flow is working fine, no failed runs. 
So to clarify, Stephen is the PP admin user, he's our customer, we guided him with all the CoE kit installation and all connections are running under his user. I have a user there too, but I'm not a PP admin user, I just have system admin access to the environment that the CoE kit was installed. We haven't changed the flows or connections. 
I'm not able to access other environments URLs, but Stephen is, so all good. So not sure what the problem is.

**Comment by Jenefer-Monroe** [comment]
Is he logged in as **_contractor.stephen...._** when he browses there? That seems like a test account name. 
Or is that his actual email? 

I've never seen this and am really not sure what to say. Perhaps try to remove and readd the connectors?

**Comment by VansNogueira** [comment]
Yes, he is logged in with that account, that is his actual email address. Ok, I'll ping him tomorrow so we can remove and re-add the connections again and I'll let you know. Thanks

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for toolkit team.
