### ISSUE TITLE
[CoE Starter Kit - BUG] Active Flows marked as deleted after running CLEANUP HELPER - Check Deleted (Cloud Flows)

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#1263]
### Describe the issue

Hello Manuela and Team,

I hope you are well. 

We recently installed "Center of Excellence - Core Components" version 3.13.

We tried to run the Flow "CLEANUP - Admin | Sync Template v3 (Check Deleted)" and was receiving errors that child flows were not published. So we turned on the Helper child flows. We've never done this before, so it's safe to presume these are new Flows.

We ran this on Friday 24/09/2021 and discovered that 945 Flows were marked as deleted on that day. 
We have not deleted that many in our tenancy. 
We estimate approximately 100 Flows may have really been deleted at most. 
Yet in our COE it shows 945 were deleted. So approximately 845 Flows have been marked as deleted, but are not deleted.

When we looked at the "CLEANUP HELPER - Check Deleted (Cloud Flows)" Flow it seemed like it couldn't find the flows in the tenant, meaning they must have been deleted: as per the action "If not found in tenant, delete or mark deleted".

![image](https://user-images.githubusercontent.com/68440710/135103043-b18a18e1-0bed-4313-bc33-ea92014a82d2.png)

But the Flow does exist in the tenancy. 

![image](https://user-images.githubusercontent.com/68440710/135103287-7a3c43f3-4909-4eec-a343-4822ff98309a.png)

My colleague noticed on the "CLEANUP HELPER - Check Deleted (Cloud Flows)" that the pagination for the action "List Flows as Admin" is turned off. When he created his own copy of the Flow and turned the pagination on, it worked and found the not deleted Flows.

![image](https://user-images.githubusercontent.com/68440710/135103967-33e1f424-5cd0-47b5-bba2-bb270c8d687e.png)

So we believe the pagination should be turned on. Of course, we could turn this on, but didn't want to cause an unmanaged layer to the Flow. 

Is this something that could be enabled please for the next release if possible, or are we misunderstanding something?

### Expected Behavior

Flow to not mark existing flows as deleted.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.14

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Jenefer-Monroe** [comment]
Thank you so much for the thorough investigation! I will fix this up for October and let you know how widespread the issues is and hence how to fix.

**Comment by Jenefer-Monroe** [comment]
OK this is local fixed for Oct. We evidently forgot to do this across all the helper flows, so after you upgrade to October, you will need to do a full inventory to get back to your good state. 
Please see [incomplete inventory](https://docs.microsoft.com/power-platform/guidance/coe/limitations#incomplete-inventory) for how to do a full inventory run.

**Comment by GarryPope** [comment]
@Jenefer-Monroe,

No problem at all. We're happy to help. And thanks for the "incomplete inventory" link. We'll follow the steps after we upgrade to the October release. Any idea when that will be released please?

Thanks very much,

Garry

**Comment by Jenefer-Monroe** [comment]
We are targeting ship of October release early next week.

**Comment by mikefactorial** [comment]
@GarryPope This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
