### ISSUE TITLE
[CoE Starter Kit - BUG] - Not able to extract the information into Power BI Dashboard using CoE starter Kit

### ISSUE THREAD

**Issue by pre-alt** [microsoft/coe-starter-kit#1269]
### Describe the issue

Have followed the below document for the setup ::
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup

Have followed the below documents in order to extract the information to Power BI Dashboard , still not working :
https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-monitor
https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern

Need support to extract the below information through CoE starter kit to Power BI Dashboard::
1. Tenant Level environment details.
2. App Usage.
3. Cloud flow details with respect to running, suspended and failed status.
4. App Error details.
5. Table related details.
6. Insights on Dataverse.
7. Data used by different Apps.

### Expected Behavior

Should be able to extract the below information to Power BI dashboard::
1. Tenant Level environment details.
2. App Usage.
3. Cloud flow details with respect to running, suspended and failed status.
4. App Error details.
5. Table related details.
6. Insights on Dataverse.
7. Data used by different Apps.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

NA

### What app or flow are you having the issue with?

Power BI Dashboard

### Steps To Reproduce

Have followed the below documents in order to extract the information to Power BI Dashboard , still not working :
https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-monitor
https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern

### Anything else?

Have followed the below document for the setup ::
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup

Have followed the below documents in order to extract the information to Power BI Dashboard , still not working :
https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-monitor
https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern

Need support to extract the below information through CoE starter kit to Power BI Dashboard::
1. Tenant Level environment details.
2. App Usage.
3. Cloud flow details with respect to running, suspended and failed status.
4. App Error details.
5. Table related details.
6. Insights on Dataverse.
7. Data used by different Apps.

**Comment by manuelap-msft** [comment]
Hello,

I'm not sure I follow. Can you help me understand 

1. Did you face issues setting up the Core Components solution of the CoE Starter Kit? If so, what issues?
2. Did you face issues setting up the Power BI dashboard? If so, what issues?
3. Or do you have the Power BI Dashboard set up and it is not showing any data? Or is it showing missing data?
4. Or is the Power BI dashboard showing all data, but you feel you are not able to answer the questions you have?

**Comment by Rajanisys** [comment]
Hello,

The Power BI dashboard is showing data. But I want to customize it to get data with respect to below mentioned points.

1. Tenant Level environment details.
2. App Usage.
3. Cloud flow details with respect to running, suspended and failed status.
4. App Error details.
5. Table related details.
6. Insights on Dataverse.
7. Data used by different Apps.

**Comment by manuelap-msft** [comment]
Hello,

I see, thanks for clarifying. Unfortunately we are unable to assist here with extending the CoE Starter Kit, and you will have to seek help from a partner (https://powerapps.microsoft.com/en-us/partners/) in doing this work. We can only help with existing functionality of the kit!

Thank you for using the CoE
Manuela
