### ISSUE TITLE
[CoE Starter Kit - BUG] Core Components upgrade - Import Error

### ISSUE THREAD

**Issue by ALMAcclerator** [microsoft/coe-starter-kit#1270]
### Describe the issue

We are facing problem in updating CoE starter kit - Core Components to v3.12 (latest as of now). When tried to upgrade to the latest version, it says, 'Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade'. We have tried the 'Classic' way as suggested in few of the threads online and still it was not upgrading.

### Expected Behavior

The core components should upgrade from the current version to the latest (3_12) with the success message after importing the package

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

Centre of Excellence - Core Components

### Steps To Reproduce

1. Download latest coestarterkit.zip from the website
2. Try to import the latest core components package into your solution
3. Try various options such as 'Upgrade', 'Update' with 'Overwrite' in classic mode
4. Result : Import failure

**Comment by manuelap-msft** [comment]
Hello,

we're about to ship a new version of the CoE Starter Kit early next week and have addressed many issues related to upgrades with this coming release. Would you be able to wait until then to upgrade to the latest version?

Thank you
Manuela

**Comment by manuelap-msft** [comment]
The October release is live now
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-October2021

Could you please try the Upgrade again?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for CoE TEam
