### ISSUE TITLE
Question on CoE-Starter-Kit

### ISSUE THREAD

**Issue by JMMora** [microsoft/coe-starter-kit#1273]
if I did install CenterofExcellenceCoreComponents_2_0_10_managed

do I need to install: CenterofExcellenceCoreComponentsTeams_1_9_managed

**Comment by Jenefer-Monroe** [comment]
Hello. From your recent questions, I would ask that you please acquaint yourself with our documentation. It includes videos which may help you to familiarize yourself with our offering: [CoE Start Kit](https://docs.microsoft.com/power-platform/guidance/coe/starter-kit)

For your specific question, these are separate offerings and should not be installed together. Please see [Production vs Dataverse for Teams environment](https://docs.microsoft.com/power-platform/guidance/coe/setup#production-vs-dataverse-for-teams-environment)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for toolkit team
