### ISSUE TITLE
[CoE Starter Kit - BUG] - Set Flow Permissions - Owner Assignment Error

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#1278]
### Describe the issue

When attempting add a new owner directly the application "Set Flow Permissions" throws an error.  This is a repeatable issue.
![2021-09-29_10-21-25](https://user-images.githubusercontent.com/1613085/135301217-bbeb3e22-2816-4635-87e3-7782602f1000.png)

### Expected Behavior

Should be able to assign an owner on primary Owner screen.
![2021-09-29_10-31-54](https://user-images.githubusercontent.com/1613085/135301043-9c4416d7-5274-4933-8de2-da63e8a6aade.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.7

### What app or flow are you having the issue with?

Set Flow Permissions

### Steps To Reproduce

1. Go to the Admin - Command Center.
2. Launch the app "Set Flow Permissions".  _(Side note: why is the title inside of the app called "Admin - Flow Permission Center")_
3. Select an environment,
4. Go to Owner tab. Find an owner.
5. Select one of their flows.
6. Click "Add Permission" button.
7. Find a different user. Select the user.
8. Change the "Selected User Role" drop-down option to Owner.
9. Click "Save" button.
10. Review the error.

![2021-09-29_10-40-47](https://user-images.githubusercontent.com/1613085/135302614-9c41d063-d958-42bf-a975-377a84c1646e.png)

### Anything else?

The work-around is to go to this screen. Make a person an "Editor". Then make them an "Owner".
![2021-09-29_10-23-56](https://user-images.githubusercontent.com/1613085/135302138-86aa6366-82db-407f-90c3-32077c3f3929.png)

**Comment by Jenefer-Monroe** [comment]
thanks for posting, it was an oversite to leave owner in the drop down. 
fixed by removing as an option for Oct.

**Comment by robertcaretta** [comment]
@Jenefer-Monroe - Where is this Role:Owner and Role:Creator information being stored? When I evaluate the permissions on the flow I see two items "CanEdit" and "Owner".  There is nothing about creator.

![2021-09-29_17-04-07](https://user-images.githubusercontent.com/1613085/135355030-c127288f-faf2-4adb-a1e8-d5931b5a5234.png)

**Comment by Jenefer-Monroe** [comment]
We have owner v creator as a concept just in the CoE. We created a notion called the **_derived owner_** which we use in the toolkit to allow you to change who is responsible for a flow for things like the archival flows. 

We have a note about this lower in the screenshot you share above:
![image](https://user-images.githubusercontent.com/89584709/135462467-ddb8ce76-f843-4a0b-8c21-7aec6bdc4c42.png)

**Comment by robertcaretta** [comment]
Got it, thank you. I missed that obviously, it's buried at the bottom.  There is nothing drawing my eye or attention to that information. Perhaps a different color, or placing it at the top of the page.

**Comment by mikefactorial** [comment]
@robertcaretta This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
