### ISSUE TITLE
[CoE Starter Kit - BUG] PowerBI/Cloud Flows - Table Visualization Filters Broken

### ISSUE THREAD

**Issue by baerj1** [microsoft/coe-starter-kit#1280]
### Describe the issue

In the PowerBI Dashboard, under Cloud Flows, when you select a specific connector or department or any filter it doesn't filter the table visualization. Other visualizations seem to take the filters, the Top 10 Active Departments one filters based on department selected.

For example, the department LARA has 1 Flow. But when selected in the department filter, all flows show in the table visualization still.

### Expected Behavior

When selecting a filter, I'd expect the list of flows to show the only those flows associated with the filter choice.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Dataverse_CoEDashboard_202109

### What app or flow are you having the issue with?

Dashboard

### Steps To Reproduce

1. GCC
2. Open Dashboard

**Comment by manuelap-msft** [comment]
We are tracking a few issues with the Dataverse_CoEDashboard here #1135 and #884, would you be able to try this new version (to be released next week, so it's a preview) to see if that solves your issues too or if you still see some errors:

https://github.com/microsoft/coe-starter-kit/raw/coe-october/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Dataverse_CoEDashboard_202110.pbit

**Comment by baerj1** [comment]
> 
> 
> We are tracking a few issues with the Dataverse_CoEDashboard here #1135 and #884, would you be able to try this new version (to be released next week, so it's a preview) to see if that solves your issues too or if you still see some errors:
> 
> https://github.com/microsoft/coe-starter-kit/raw/coe-october/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Dataverse_CoEDashboard_202110.pbit

Thanks, this October version appears to have fixed the issue.

**Comment by manuelap-msft** [comment]
Amazing, thanks for confirming! We will release this version next week so great to have early feedback that this works for you. I will leave this issue open and we'll close it when the version gets released officially.

**Comment by mikefactorial** [comment]
@baerj1 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
