### ISSUE TITLE
Not able to update the Environment variable value for COE DataVerse for Teams solution. 

### ISSUE THREAD

**Issue by krishnaVSU2020** [microsoft/coe-starter-kit#129]
Hi Team,

Congratulations on releasing the new version of COE on DataVerse for Teams. 

**Issue**
Yesterday while I am configuring on my personal tenant I noticed there is no way I can update the environment variable 

**Steps to reproduce the behavior**:
1. Go to Solution of the Dataverse for Teams environment
2. Select the core components solution
3. select the Environment variables as part of the dropdown (on top right corner)
4. Select **ProductionEnvironment** variable, it clearly says "**This environment variable definition cannot be edited because it is in a managed solution**" on top. 
**Note:** I need this to be No because I want to configure it for DEV setup (description on the env variable "true by default. set to false if you are creating a dev type envt. this will allow some flows to set target users to the admin instead of object owners")
5. In the past we use to go on to the environment variable table at the environment level and change the value to No since we want to configure it as DEV environment.

**Expected behavior**
I should be able to change the variable value to No.

**Screenshots**
![image](https://user-images.githubusercontent.com/70860420/114194069-1d52d080-991d-11eb-971c-6ba6b58c35ea.png)

**Comment by devkeydet** [comment]
Hi @krishnaVSU2020,
Issues in this repo are mostly unattended at the moment. We're in the process of transitioning CoE Starter Kit here, but for the time being would you mind posting this issue to https://github.com/microsoft/powerapps-tools/issues? The team is actively monitoring issues there until we fully move over.
