### ISSUE TITLE
[CoE Starter Kit - BUG] GCC Audit Logs running but not writing data

### ISSUE THREAD

**Issue by mzd4fz00** [microsoft/coe-starter-kit#1292]
### Describe the issue

our child and parent flows are running without failures, however we are not seeing the app last launched date being populated in the PowerApps App Dataverse table.  We see audit log data being pulled in from the custom connector in the flow runs, but it doesn't include data for the power apps that are actively in use.  

Our child flow does include this filter:
@or(equals(item()?['Operation'], 'LaunchPowerApp'), equals(item()?['Operation'], 'DeletePowerApp'), equals(item()?['Operation'], 'DeleteFlow'), equals(item()?['Operation'], 'PowerAppPermissionEdited'))

We don't see any data in the audit log tables either, but we do see LaunchPowerApp operation in the security logs. we are looking for hints of what we should try to inspect next to uncover why our flows are not able to retrieve any data about when users last launched or deleted a power app.

### Expected Behavior

we were expecting data to populate for app last launched into the PowerApps App dataverse table.  Data should also be populated into the Audit log dataverse table as well.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.4

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Anything else?

This is something that has never worked properly for us (not an issue where it used to work but then stopped working).

**Comment by Jenefer-Monroe** [comment]
Hello. Are you a GCC tenant, or otherwise not a normal commercial tenant?

**Comment by Jenefer-Monroe** [comment]
And have you been through any cycles with support, or us, about this in the past?

**Comment by mzd4fz00** [comment]
Hi, yes we are in a GCC tenant.  We have been working with Alex Rezac and Ernest Ovalles through ticket 2108250040005902 .  They recommended starting up this thread as a good next step as we collectively haven't been able to reach a resolution after several weeks of troubleshooting.

**Comment by Jenefer-Monroe** [comment]
Thanks for that information. When you [set up the custom connector](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector), did you set the **_Resource URL_** as shown here? 
![image](https://user-images.githubusercontent.com/89584709/135553614-7cc37e37-03bb-4ee1-a830-0e031271f00e.png)

**Comment by mzd4fz00** [comment]
Hi Jenefer, Mohamed Qureshi checked his notes when he set this up with Ernest and Alex from Microsoft and he has https://manage-gcc-office.com in his notes.  If he attempts to edit the existing connection, it doesn't show the current values for some fields such as the Resource URL (ref the screenshot):
![Screenshot](https://user-images.githubusercontent.com/91695437/135869629-8efbe9fc-5e7c-4c5e-970b-a9709dd9ac36.PNG)

Is there another way to see the current value that is in use?

**Comment by Jenefer-Monroe** [comment]
Unfortunately custom connector settings do not show up after you hit "Update connector". 
You could likely watch the network traffic to see where it is being sent. However my suggestion is that you just go ahead and reset them, then see if this works.

**Comment by ToddIngersoll** [comment]
I have the same issue.  That table has no rows being written to.

**Comment by Jenefer-Monroe** [comment]
I will hide your comments then @Label-Maker, since they do not seem to be the same issue. Thanks for using CoE

**Comment by mzd4fz00** [comment]
Hi Jenefer, were there any additional components you recommend we check?

**Comment by Jenefer-Monroe** [comment]
I've seen this happen with one GCC customer. They uninstalled the audit logs solution and reinstalled it and it worked. 
It seemed that there may have been some caching somewhere that we could not clear without delete/reimport.

**Comment by mzd4fz00** [comment]
Hi Jenefer, that has been done twice now with Microsoft support (Alex Rezac and Ernest Ovalles) but it did not correct the issue unfortunately.  Are there some additional measures you would recommend?

**Comment by Jenefer-Monroe** [comment]
From [the setup steps](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector), can you confirm that you confirm that you changed the host on the General tab? We realize that the instructions were a little confusing (say leave it as is, but then show the change needed for gov tenants) and we have changed that slightly for Nov

![image](https://user-images.githubusercontent.com/89584709/136962430-d1f692a7-8c41-4edc-b6c0-14f692cd6f3c.png)

**Comment by mzd4fz00** [comment]
Hi Jenefer, we will check this shortly and report our finding, and to be clear you are indicating since we are GCC that we should set our host value on the General tab to be: https://manage.office365.us if it isn't already set that way, correct?

**Comment by mzd4fz00** [comment]
Hi Jenefer, we did make sure on General tab to make sure the host name is set to manage-gcc.office.com.  We are now seeing some entries making it to the Audit Log table which is very encouraging,  The last launched date is not yet populating though in the PowerApps App table,  Is that normal, and should the child flow for the audit log already be populating it?

**Comment by Jenefer-Monroe** [comment]
WOOHOO!!!

We shipped with a bug last month in which that field wasnt populating. If you use the Oct version of the toolkit it will be fixed. Please see https://github.com/microsoft/coe-starter-kit/issues/1288

**Comment by mzd4fz00** [comment]
Hi Jenefer, you are correct that the admin did seee some chunk size / pagination type emails.  we reduced the size down to looking at 10 minute size chunks instead of 60 minute ones and that seems to have gotten them small enough that we don't get paging.  However, even with that smaller size, we only see 17 powerapps being detected, 16 of which are SharePointFormApp apps and 1 is a canvas (which is the DLP editor app being detected as in use).  It still doesn't pick up other model driven or other canvas apps in the tenant, so we still think something isn't correct yet.  Is there something else you think might be related?  Thanks,

**Comment by Jenefer-Monroe** [comment]
Have you validated by actually booting some apps and then looking to see if they show up as launched in the next few days?

**Comment by mzd4fz00** [comment]
Hi Jenefer, we did try booting a couple of canvas apps and indeed I can see when I do that and run the parent and child workflows that data does come in for Canvas apps at least.  Model-driven seems to be the area though were we don't see any activity at all but talking with our model driven app developers they are indicating a number of them are launched everyday.  Is there a reason our O365 logs might not contain data for model-driven app launched events?

**Comment by Jenefer-Monroe** [comment]
Correct, the audit logs only work for Canvas apps, they do not record model driven app activity.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
