### ISSUE TITLE
[CoE Starter Kit - BUG] Import Audit Components - Missing dependencies - Approval Response

### ISSUE THREAD

**Issue by Dlutchy** [microsoft/coe-starter-kit#1299]
### Describe the issue

I have imported Core components 3.12. Now I am trying to import Audit Components 2.5. 
However I receive the error Missing dependencies for Table **msdyn_flow_approvalresponse**.

When I look in the Solution **msdyn_FlowApprovalsCore** I see it there.

### Expected Behavior

Error not to appear.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Check Approval)

### Steps To Reproduce

1. Install Core Components 3.12
2. Install Audit Components 2.5

### Anything else?

Log File -> [log.txt](https://github.com/microsoft/coe-starter-kit/files/7274827/log.txt)

**Comment by manuelap-msft** [comment]
Hello,

this happens when you've not initialized using Approvals in your environment - it's the first step of the setup documentation: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for toolkit team.
