### ISSUE TITLE
[CoE Starter Kit - BUG] Core Components for Teams in Oct Release upgrade fails

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#1303]
### Describe the issue

Core Components for Teams in Oct Release upgrade fails with an error message of "Upgrading solution failed. Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: EnvironmentVariableDefinition, ObjectName: admin_EnvironmentFriendlyName, Id: 470d0859-c1a1-4b09-baf0-c2281e457598, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: EnvironmentVariableValue, ObjectName: , Id: cbc25973-a0b6-41c0-bf7c-45b2b601413e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000".   I had a value in that variable so tried deleting the value.  Same error.  

### Expected Behavior

Upgrade successfully completes.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.2

### What app or flow are you having the issue with?

Friendly Name of Environment - Environment Variable I think

### Steps To Reproduce

1. Currently on solution version 2.9 for Core in Teams (I believe this was the Sept release version).
2. Import New Solution (3.2)
3. See failure noted above.
4. I'm attaching the failure log I initially received also (put into a zip file), although it didn't help me much in looking through i
[CenterofExcellenceCoreComponentsTeams_3.2_managed.zip_import.zip](https://github.com/microsoft/coe-starter-kit/files/7278592/CenterofExcellenceCoreComponentsTeams_3.2_managed.zip_import.zip)
t.

**Comment by Jenefer-Monroe** [comment]
You are upgrading from Sept. Is that correct?

**Comment by bartsneary** [comment]
Yes, that is my understanding.  It's Solution version 2.9 right now.  It is only the Teams version I had issues with, also.

**Comment by NPrice99** [comment]
Try update rather than upgrade - I had the same issue as you and using upgrade

**Comment by bartsneary** [comment]
The new 3.3 version did import successfully the first time without switching over to using update.  Thanks @Manuela!

**Comment by Jenefer-Monroe** [comment]
Wonderful news. Thank you for validating. We will put that one in our download zip

**Comment by manuelap-msft** [comment]
Thank you! Updated the release with this new version!
