### ISSUE TITLE
October solution - getting started

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#1305]
### Describe the issue

Hi

A numberof the flows are failing because the child flow is not published.  However, I only get a GUID not the name of the flow in question.  Also there are no flows with "Child" in the title so I cannot find out which ones are need publishing.

### Expected Behavior

Flows to be switched on

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

eg. CLEANUP - admin | Sync Template v3 (Power Apps User Shared with)

### Steps To Reproduce

try to switch on the above flow. See the error

**Comment by manuelap-msft** [comment]
I think you have missed this step in our setup instructions where you update and turn on child flows:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for CoE TEam
