### ISSUE TITLE
[CoE Starter Kit - BUG] Dataflow missing from Nurture solution

### ISSUE THREAD

**Issue by Craig-Humphrey** [microsoft/coe-starter-kit#1307]
### Describe the issue

I was upgrading our existing CoE (over a year old) and while importing the Nurture Component Solution and configuring it, notice that the Maker Assessment Starter Dataflow did not appear in my environment.

I did a quick search in the solution files and couldn't find it either.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.3

### What app or flow are you having the issue with?

Maker Assessment Starter Dataflow

**Comment by manuelap-msft** [comment]
Hello,

thanks for letting us know! It looks like we missed adding the dataflow back into the solution (there was a product bug last month where the solution with the dataflow failed to import into certain regions, so we removed it temporarily). We're re-running our deployment pipelines now to make sure the import now succeeds into our test and prod environments and if it does will make a new solution available later today.

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Hello,

I updated the release with a new solution that contains the dataflow again, here's the direct download:
https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-October2021/CenterofExcellenceNurtureComponents_2_4_managed.zip

Let me know if you have any issues with importing this,
Manuela

**Comment by Craig-Humphrey** [comment]
Thanks @manuelap-msft 

It failed the first time I tried to import it - clicking the download log link did nothing.

Tried again and it succeeded and the Dataflow was present this time.

Thanks for sorting this out so quickly!
