### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Detail Request Flow - not returning apps for Default envt

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1324]
### Describe the issue

Under the control "Apply to each envt App"  the step "Get Assignee apps" fails with the error:
Unexpected error. Request to Azure Resource Manager failed with error: '{"error":{"code":"ActionRepetitionNotFound","message":"The specified repetition '000007-000000' of workflow action 'Get_Assignee_apps' is not found."}}'.

And the step "Maker has submitted business requirements apps" errors with:
Unexpected error. Request to Azure Resource Manager failed with error: '{"error":{"code":"ActionRepetitionNotFound","message":"The specified repetition '000007-000000' of workflow action 'Maker_has_submitted_business_requirements_apps' is not found."}}'.

This only occurs for 3 of the 10 environments in the tenant.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin | Compliance detail request

### Anything else?

![ComplianceDetailRequestV3-ErrorStep](https://user-images.githubusercontent.com/17124284/136241956-9c4b8fd2-3a40-4862-b4c4-45e0591daf6a.JPG
![ComplianceDetailRequestV3-GetAssigneeApps](https://user-images.githubusercontent.com/17124284/136241972-55967182-d5b3-4171-bd21-f416fa5599eb.JPG)
![ComplianceDetailRequestV3-MakerSubmittedStep](https://user-images.githubusercontent.com/17124284/136241981-3d9d1abc-7b79-4a2a-badb-027b0919e7b3.JPG)
)
![ComplianceDetailRequestV3-Tree](https://user-images.githubusercontent.com/17124284/136241991-8d844545-bc08-46b9-85e3-872e6e0b8c89.JPG)

**Comment by Jenefer-Monroe** [comment]
This scope seems to have passed. Its not showing any failures. Did the flow as a whole pass or fail?

**Comment by Jenefer-Monroe** [comment]
i see. This is an error message about the product itself trying to find loops. So I dont think that I can help you debug. 
My presumption from the text is that the error will not persist on rerun, it sounds like a transitory error. But if it does, then you may have to contact support.

**Comment by Jenefer-Monroe** [comment]
Can you open the flow in edit mode and share a picture of what these conditions look like for you?

**Comment by medicineshow** [comment]
So this is the output from the "List this envt apps" step in the failed flow :
{
    "statusCode": 200,
    "headers": {
        "Vary": "Accept-Encoding",
        "x-ms-service-request-id": "1cb70df5-646b-4874-be8c-bb98d1da788c,ae5e5c8b-8162-4941-85de-eb3e1d50262f",
        "Cache-Control": "no-cache",
        "Set-Cookie": "ARRAffinity=3288e5bb110f7d7f216504d49b6d255330e0aa12f59de91511fad78e797aaccc; domain=dwdevopsbuilddev.crm11.dynamics.com; path=/; secure; HttpOnly,ReqClientId=5f144354-d156-428e-b55f-a93d3e7c24fa; expires=Wed, 07-Oct-2071 08:12:57 GMT; path=/; secure; HttpOnly,ARRAffinity=3288e5bb110f7d7f216504d49b6d255330e0aa12f59de91511fad78e797aaccc; domain=dwdevopsbuilddev.crm11.dynamics.com; path=/; secure; HttpOnly",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
        "REQ_ID": "ae5e5c8b-8162-4941-85de-eb3e1d50262f",
        "AuthActivityId": "01a101ab-ca98-4798-9a9a-0977447986a1",
        "x-ms-dop-hint": "8",
        "x-ms-ratelimit-time-remaining-xrm-requests": "1,199.94",
        "x-ms-ratelimit-burst-remaining-xrm-requests": "7997",
        "OData-Version": "4.0",
        "Preference-Applied": "odata.include-annotations=\"*\"",
        "X-Source": "21231165109226151179134214812519777881246342041022261272411401182241079016530182218,107437311421691065220941106479246130184982351431921751522022716321822414981211",
        "Public": "OPTIONS,GET,HEAD,POST",
        "Timing-Allow-Origin": "*",
        "Date": "Thu, 07 Oct 2021 08:12:57 GMT",
        "Allow": "OPTIONS,GET,HEAD,POST",
        "Content-Type": "application/json; odata.metadata=full",
        "Expires": "-1",
        "Content-Length": "815"
    },
    "body": {
        "@odata.context": "https://dwdevopsbuilddev.crm11.dynamics.com/api/data/v9.1/$metadata#admin_apps(admin_appdescription,admin_displayname,admin_apppublished,admin_appsharedgroups,admin_appsharedusers,admin_requirement_2,admin_requirement_1,admin_requirement_3,admin_requirement_4,admin_requirement_6,admin_makersubmittedrequirements,admin_requirement_5,cr5d5_appisorphaned,_admin_appowner_value,admin_appenvironmentdisplayname,admin_AppOwner(admin_userisserviceprinciple))",
        "#Microsoft.Dynamics.CRM.DeleteMultiple": {
            "title": "DeleteMultiple",
            "target": "https://dwdevopsbuilddev.crm11.dynamics.com/api/data/v9.1/admin_apps/Microsoft.Dynamics.CRM.crmbaseentity/Microsoft.Dynamics.CRM.DeleteMultiple"
        },
        "@Microsoft.Dynamics.CRM.totalrecordcount": -1,
        "@Microsoft.Dynamics.CRM.totalrecordcountlimitexceeded": false,
        "value": []
    }
}

**Comment by medicineshow** [comment]
and this is the flow in edit mode after the "List this envt apps" step which fails:
![image](https://user-images.githubusercontent.com/17124284/136375900-96c2431c-72e1-4770-9232-29044958a106.png)

**Comment by medicineshow** [comment]
We have found that if we remove a section of the filter rows in the step"List this envt apps" the flow runs without error.
The filter row is:
_admin_appowner_value ne null and admin_appdeleted ne true and admin_appownerdisplayname ne 'SYSTEM' and admin_appenvironmentid eq '@{items('Apply_to_each_envt')?['admin_environmentid']}'

As a workaround we have set it as:
_admin_appowner_value ne null and admin_appdeleted ne true and admin_appownerdisplayname ne 'SYSTEM'

Can you explain why it needs admin_appenvironmentid eq admin_environmentid?

**Comment by medicineshow** [comment]
I should add, your last comment explains why it returned so many instances of apps when we removed the admin_environmentid filter. In other words it generated a number of emails, however, it did return apps from environments that it appeared to error before. Could this somehow be related to the admin_appenvironmentid value missing from some apps in the environment which causes it to fail for the whole environment? In which case, any idea why this value is missing?

**Comment by Jenefer-Monroe** [comment]
I think that issue is covered here: #1332 
I discovered it while debugging yours. But I did not repro your issue before fixing that so I dont think it completely explains your issue. 
We are currently revamping this flow completely for Nov, and I dont repro, so likely I fixed it already accidently. I will hold for the Nov release for you to double check.

**Comment by Jenefer-Monroe** [comment]
Unfortunately I'm not at a state that can be sent out. You'll be glad you couldn't ship this month then since this is new as next months is going to be a much better end to end solution. 
If I finish early I will let you know.
