### ISSUE TITLE
[CoE Starter Kit - BUG] Set App Permissions - D4T - cant add users to default envt

### ISSUE THREAD

**Issue by J04nn4** [microsoft/coe-starter-kit#1325]
### Describe the issue

Open Set App Permissions 
Pick an app in Default environment. 
Click Add new users
Select a user 
Get an error "The Environment could not be found in the tenant"

### Expected Behavior

Pick an app in Default environment. 
Click Add new users
Select a user 
User is added. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.2

### What app or flow are you having the issue with?

Set App Permission

### Anything else?

![image](https://user-images.githubusercontent.com/35706419/136292245-b32d3ee5-bf3a-470b-a136-b624e66298ea.png)

My guess - Default environment is not just Guid but also includes the word "Default".
Issue does not occur in non-default environments.

**Comment by Jenefer-Monroe** [comment]
Hello I do not repro. Can you please share a screenshot of your solutions so we can see what version you are on? We have not shipped a version 3.2 of Core yet. 
![image](https://user-images.githubusercontent.com/89584709/136367909-3ec49108-863c-493b-a791-f51931e4b8fe.png)

**Comment by Jenefer-Monroe** [comment]
validated for Nov release
