### ISSUE TITLE
[CoE Starter Kit - BUG] Set App Permissions -D4T - not reading env vars

### ISSUE THREAD

**Issue by J04nn4** [microsoft/coe-starter-kit#1326]
### Describe the issue

Open Set App Permissions app 
Pick an app 
Click on App Details 
It go to broken link.  Link is missing the "https://make.powerapps.com/". The Environment Variable is filed out. 
![image](https://user-images.githubusercontent.com/35706419/136293029-ff981894-a5a7-43b5-8397-52241ffdb200.png)

### Expected Behavior

App details button to open the makers portal with details of the app. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.2

### What app or flow are you having the issue with?

Set App Permissions

**Comment by Jenefer-Monroe** [comment]
OK I repro this when I install in a new tenant.

**Comment by Jenefer-Monroe** [comment]
It looks like the app is not up to date in the OnStart command, the work we did to pull in the env vars was changed and placed there. 
We somehow did not ship the app as it exists today.

**Comment by Jenefer-Monroe** [comment]
validated for Nov release

**Comment by mikefactorial** [comment]
@J04nn4 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by Jenefer-Monroe** [comment]
Sorry to hear in the office hours this may still be causing issues. I did just validate in a Dec install that this workis now. 
If you are still experiencing this, please be sure to remove unmanaged layers from the app, and upgrade to December bits. 
If you still repro with those changes, please re-activate and share pictures of the layers so we can see that it does not have any applied
