### ISSUE TITLE
[CoE Starter Kit] Duplicate app GUIDs across different environments

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1333]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/1331

<div type='discussions-op-text'>

<sup>Originally posted by **jukkan** October  7, 2021</sup>
Especially with Model-driven apps from Dynamics 365 environments, it's not uncommon that a customer will have copied an environment for dev/test purposes. This means that the existing app id values will be the same on the Power Apps service side.

Since the CoE Starter Kit sync flows will use the app id value as the record GUID when doing an insert into the PowerApps App table, this will cause failures due to duplicate values. We'll see errors like: _"Violation of PRIMARY KEY constraint 'PK_admin_AppBase'. Cannot insert duplicate key in object 'dbo.admin_AppBase'. The duplicate key value is <redacted>."_

Another issue will arise from data updates. I've previously seen from Dataverse audit history view that an app record in CoE can "jump" between different environments, based on which flow instance gets to run first. One day an app will be in Dev, then it will be listed in Test.

I'm curious to know how customers are working around this issue? The app counts in CoE will not match the actual number of apps since some will be missing due to duplicate key issue upon record create. I do realize the best practice for ALM would not be to take copies of production environments to establish non-prod environments, but the everyday reality in many customer organizations is different.

I saw a recent issue #1323 about making app id's visible in the app, where it stated that the data is actually already stored also in the AppIDString field. Is there now any actual benefit in trying to use the app's ID as the GUID value for a record in the PowerApps App table? If the GUID would not be taken from the app, this problem caused by duplicate values would presumably go away and the app inventory would be complete.</div>

**Comment by manuelap-msft** [comment]
@Jenefer-Monroe It looks like model driven apps can also have the same GUID in one tenant. Wondering if there's something we can do here like we did with Portals?

**Comment by Jenefer-Monroe** [comment]
missed this ones milestone. Fixed in Nov
