### ISSUE TITLE
[CoE Starter Kit - BUG] Set Flow approval Dataverse for teams

### ISSUE THREAD

**Issue by J04nn4** [microsoft/coe-starter-kit#1337]
### Describe the issue

When in the owner tab for Set flow approval, the user is not being pulled it. We have checked the table in Dataverse and it does have the user/owner listed along flows they have. but in the app the owner is not found, nor the flows show up. 
We re-run the collection flows and cleanup flows and all with no different for it to show in the app. The flows are active. It is happening for more then one user/owner.

### Expected Behavior

be able to filter by any owner. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.2 (Core for teams)

### What app or flow are you having the issue with?

set flow permissions

**Comment by Jenefer-Monroe** [comment]
This is our Set Flow Permissions in team, showing the owners
![image](https://user-images.githubusercontent.com/89584709/136484934-045a5a45-3d7f-4873-a409-af1e8ec2a9a8.png)

**Comment by castilld5797** [comment]
This is what happens to us as well using the MS Teams module. I have Flows in the default environment as per screen shot, but I am not found when searching in the  owner tab
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/8749850/136829715-85b66171-5cbe-40ec-8aa3-256636ae4cb7.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/8749850/136829745-ca5bfd1b-2378-468f-bd6a-04ac75083162.png)

**Comment by Jenefer-Monroe** [comment]
I dont really follow this one, and I dont repro cases in my install (even in a new tenant)
Can you please give a more specific example? Can you find the data in the table and see if it has a different person listed for Derived Owner?

**Comment by Jenefer-Monroe** [comment]
validated for Nov release

**Comment by mikefactorial** [comment]
@J04nn4 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by Jenefer-Monroe** [comment]
Sorry to hear in the office hours this may still be causing issues. I did just validate in a Dec install that this works now. 
If you are still experiencing this, please be sure to remove unmanaged layers from the app, and upgrade to December bits. 
If you still repro with those changes, please re-activate and share pictures of the layers so we can see that it does not have any applied.
Do note that there is a filter on this gallery to filter out makers without any flows, and this is determined by the calculated column in dataverse, so there may be delay in someone getting a flow assigned (or especially a new isntall of the starter kit) and them showing up here.
