### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by sbahlbhatia** [microsoft/coe-starter-kit#1340]
### Describe the issue

Trying to find out what the HELPER flows do and which apps trigger them.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

HELPER - CanvasAppOperations; HELPER - CloudFlowOperations

### Steps To Reproduce

What is the trigger of these flows?

**Comment by Jenefer-Monroe** [comment]
The helper flows are called from a variety of apps and flows. We can put documenting this on the backlog but we may not get to that quickly. In the meantime you can look at dependencies as shown here:
![image](https://user-images.githubusercontent.com/89584709/136624155-b5be3202-7409-4134-b60a-82bcde8c0033.png)

If you have specific questions, please let me know
