### ISSUE TITLE
[CoE Starter Kit - BUG] All apps and flows

### ISSUE THREAD

**Issue by sbahlbhatia** [microsoft/coe-starter-kit#1343]
### Describe the issue

Is there any documentation on the apps (like definition and/or usage) in the CORE solution of the COE Starter kit? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

ALL

### Steps To Reproduce

Just need help understanding what each of the apps do. Few are easily understandable but having trouble with the following:
1. Admin - Access this App
2. Admin - Access this Flow
3. App Catalog
4. DLP Editor V2

Have been able to come up with the following explanations yet. If you could please confirm my understanding on the others too, that'd be great!

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sbahl/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sbahl/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72" lang=EN-US style='tab-interval:.5in;
word-wrap:break-word'>

App Name | App Type | Details | App User Role
-- | -- | -- | --
Admin – Access this App | Canvas |   |  
Admin – Access this Flow | Canvas |   |  
Admin – Power Platform Resource RMS | Canvas | This   app is used by admins to approve/reject environment creation and DLP policy   creation/modification requests | Admin
App Catalog | Canvas |   | Users
DLP Editor V2 | Canvas | This   app is used by users/admins to modify existing DLP policies within existing   environments | Users/Admin
Power Platform Admin View | Model-Driven | This   app gives a complete view with lists and analytical dashboards of all the   different resources (apps, flows, environments, etc.) in the tenant | Admin
Power Platform Request Center | Canvas | This   app is used by users to request for the creation of new environments from the   admin | Users
Set App Permissions | Canvas | This   app is used to assign bulk permissions to users for a particular app | Admin
Set Flow Permissions | Canvas | This   app is used to assign bulk permissions to users for a particular flow | Admin

</body>

</html>

**Comment by Jenefer-Monroe** [comment]
Hello we have documentation for what the objects in the toolkit do. Please browse through [our documentation](https://docs.microsoft.com/power-platform/guidance/coe/starter-kit-explained) 

1. [Admin - Access this App / Flow](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard)
1. [App Catalog](https://docs.microsoft.com/power-platform/guidance/coe/core-components#app-catalog)
1. [DLP Editor V2](https://docs.microsoft.com/power-platform/guidance/coe/core-components#dlp-editor-v2)
