### ISSUE TITLE
Model apps having the same ItemInternalID across environments only shows in 1 environment

### ISSUE THREAD

**Issue by DDog80sRocked** [microsoft/coe-starter-kit#1345]
### Describe the issue

We have multiple model apps in multiple environments.  If the model app is promoted through Dev, Test, then Prod, the CoE only detects one instance of that model app.  This affects the app count and resources of the environments because the app doesn't appear in the remaining 2 environments.

### Expected Behavior

Model apps should be detected with a unique ID so they appear in each environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Model Driven Apps)

### Steps To Reproduce

1. Create 2 environments
2. In each environment, import the Solution Health Hub as an example.
3. Run the Admin | Sync Template v3 Flow
4. Check the Environment table in the Power Platform Admin View - only 1 environment will show as having an App count.
5. Click on one of the environments and check Resources.  The app will only show in one environment's Resources tab, not the other.

### Anything else?

This seems similar to Issue #1096 with Portals where the ItemInternalid is used as the AppIDString to add the entity to the dataverse table.  Then when the Model Driven apps flow finds an app with the same ItemInternalID, it ignores it and it never gets associated to the 2nd environment.  Maybe use a compound ID like EnvironmentID + itemInternalID so that each app is unique and associated to each environment where it's detected.

All 3 environments have the same Solution Health Hub app in them but it's only detected on 1:
![image](https://user-images.githubusercontent.com/42620867/136851309-75292200-e767-4868-a17e-8a5bc624fda0.png)

![image](https://user-images.githubusercontent.com/42620867/136851046-686898b2-37c0-40b8-9724-3b45949e6ef5.png)

**Comment by Jenefer-Monroe** [comment]
local fixed for November

**Comment by mikefactorial** [comment]
@DDog80sRocked This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
