### ISSUE TITLE
[CoE Starter Kit - BUG] Request Orphaned Objects Reassigned (Parent) - Extra Columns in Admin Email

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#1352]
### Describe the issue

There appears to be extra columns of information in the email sent to admins. Are these placeholders needed for something?

![2021-10-12_11-36-34](https://user-images.githubusercontent.com/1613085/136996164-d78bb2ab-1c97-4e37-aaa7-bddfcf0aec1b.png)

![2021-10-12_11-35-58](https://user-images.githubusercontent.com/1613085/136996178-1c4558d7-2f4b-4609-811a-8924659a29b3.png)

### Expected Behavior

Remove extra columns if not needed.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

### Steps To Reproduce

1. Let the flow run.
2. Review the email.

**Comment by Jenefer-Monroe** [comment]
ok I see this when I installed in a new tenant. Seems we didnt copy the flows over correctly before shipping.

**Comment by Jenefer-Monroe** [comment]
clearing milestone and solution. This isnt about teams install after all, there is just a bug in the way flow persists changes to this action type over solution export/import generally. Will have to explore.

**Comment by Jenefer-Monroe** [comment]
i found one repro of this in a test tenant and upgrading to December bits (after ensuring no managed layers) resolved it.

**Comment by Jenefer-Monroe** [comment]
closing out as a result.
