### ISSUE TITLE
[CoE Starter Kit - BUG] - Admin | Sync Template v3 (PVA) - Very long run times & Bad gateway

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#1353]
### Describe the issue

This inventory flow is taking upwards of 2 hours to complete. We have zero PVA flows in our test environment.

![2021-10-12_12-03-50](https://user-images.githubusercontent.com/1613085/136999985-9deade8e-e15c-489e-a090-eb2425a87281.png)

![2021-10-12_12-05-43](https://user-images.githubusercontent.com/1613085/136999994-95f58dae-570f-47e7-befe-1f3278269d75.png)

![2021-10-12_13-37-50](https://user-images.githubusercontent.com/1613085/137011204-7d5fc506-b624-42ab-82f3-27732ac8a656.png)

![2021-10-12_13-38-47](https://user-images.githubusercontent.com/1613085/137011213-a401b103-5697-4ad4-9e51-dbd6b7d6af2b.png)

![2021-10-12_13-39-29](https://user-images.githubusercontent.com/1613085/137011226-577e6701-fcba-4069-8959-f6407020bc3d.png)

### Expected Behavior

Would expect it to complete much faster if there is nothing to inventory.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### Steps To Reproduce

1. Let the flow run on schedule.
2. Review the run history.

**Comment by Jenefer-Monroe** [comment]
There isn't really anything we can do here. I dont know why flow took 2 hours to retry that call. We dont want to take away the retry as there are valid reasons to retry. Does this happen consistently?

**Comment by mikefactorial** [comment]
@robertcaretta This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
