### ISSUE TITLE
[ALM Accelerator - BUG]: Import Managed Solution as Update Fails to connect to Dataverse

### ISSUE THREAD

**Issue by andrewgaskins** [microsoft/coe-starter-kit#1356]
### Describe the issue

When running the test deployment pipeline I am getting hung up at Import Managed Solution as Update. The error is "Failed to connect to Dataverse". I have checked the Service connections, service connection variables and the app user on the test environment. Everything looks to be correct but I can't seem to locate where this would call from. 

Oddly the call to validation Import Managed Solution as Update works. Any help would be appreciated as I have exhausted my options I believe.

### Expected Behavior

Expect Import Managed Solution as Update to complete and continue through the pipeline.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20210922.2

### Steps To Reproduce

1. Submit PR
2. PR runs validation with no issues
3. Test pipeline is triggered and runs until Import Managed Solution as Update
4. No connection appears to be made

### Anything else?

<img width="875" alt="Screen Shot 2021-10-12 at 4 58 16 PM" src="https://user-images.githubusercontent.com/11320569/137040082-48ddf82b-3ba3-49d7-b5f3-295224990894.png">

**Comment by andrewgaskins** [comment]
Last comment: Deleting the solution from the test environment cleared the final errors. I know have successful pushes.

**Comment by mikefactorial** [comment]
Hey @andrewgaskins thanks for submitting this and for including the steps you took to push past the issues. The CreateVariableValue plugin error is something I've seen as well. It appears to be related to exporting a solution that contains current values for environment variables and / or manually setting environment variable values in the target environment. The import rejects the values in the deployment configuration in these cases. We have raised this issue with the engineering team responsible for PAC CLI and hopefully will have a fix for it in a future release. For now you can prevent environment variable values from being included in your solution by updating your export-solution-to-git pipeline to include the following variable

image-20210920105643412
