### ISSUE TITLE
[CoE Starter Kit - BUG] case sensitive - CLEANUP - Admin | Sync Template v3 (Check Deleted)

### ISSUE THREAD

**Issue by MartinWhiteDAZN** [microsoft/coe-starter-kit#1358]
### Describe the issue

This is for the Teams version...
The flow CLEANUP - Admin | Sync Template v3 (Check Deleted) is not checking the environment variable 'Also Delete From CoE' correctly because it is case sensitive.
In the flow, two variables are created. Variable 'varDeleteFromCoE' gets the environment variable in its raw state and variable  'DeleteFromCoE' gets the environment variable as a boolean and does check case sensitivity.
However, the condition named 'Check if they want to delete from CoE' is using variable  'varDeleteFromCoE' and comparing it to 'yes'.  I believe it should be using variable 'DeleteFromCoE' and comparing to true.
This worked when I tried it.

![image](https://user-images.githubusercontent.com/57627519/137108701-a1b8369a-bb68-47f1-be48-b8ede0238738.png)

### Expected Behavior

When environment variable 'Also Delete From CoE'  is set to 'Yes' with a capital Y, the flow 'CLEANUP - Admin | Sync Template v3 (Check Deleted)' removes deleted apps and flows from the CoE.
(This is for the Teams version)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Steps To Reproduce

Set environment variable 'Also Delete From CoE'  is set to 'Yes' with a capital 'Y'.
Run the flow CLEANUP - Admin | Sync Template v3 (Check Deleted).
Deleted apps remain in the CoE.

**Comment by mikefactorial** [comment]
@MartinWhiteDAZN This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
