### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot install Audit log solution: "Could not find API"

### ISSUE THREAD

**Issue by jukkan** [microsoft/coe-starter-kit#1360]
### Describe the issue

This Dataverse (full) environment has CoE Core solutions v3.13 installed and the Office 365 Management API custom connector has been configured. Upon trying to import the Audit Log solution v2.5 the prompt for updating connections shows that Office 365 Management API doesn't have any existing connections, even though I've added one under the connector already:

![image](https://user-images.githubusercontent.com/10254155/137140965-338ea909-e93f-4433-9fcc-7639fe92b945.png)

When clicking on "new connection", I get taken to an error dialog saying "Could not find API 'shared_admin-5foffice-20365-20management-20api-5f7fc9343cf45734fe'."

![image](https://user-images.githubusercontent.com/10254155/137141164-551ae92d-496c-464d-8608-38ac07f19748.png)

Looking at the name of the connection, in the Maker portal UI URL bar I can tell that it's actually "shared_admin-5foffice-20365-20management-20api-5f046de295a381644d" in this environment. Where does the Audit Log solution pick up the reference to the custom connector with that other ID string?

There has previously been an older version of the Audit Log solution installed in the environment. I deleted it and tried importing this latest version as an installation rather than an upgrade, but this didn't help.

### Expected Behavior

I should be able to either link an existing or a new connection to the Office 365 Management API connections upon solution import.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Solution import

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of the the following? My suspicion is that you do not have an active connection. 
Dataverse > Custom Connectors > Edit the Office Management API connector
Go to the test screen. Do you see a connection here? or None? 
![image](https://user-images.githubusercontent.com/89584709/137146941-c841e38e-ed8b-45a7-aa7d-3a787f29cdd3.png)

Dataverse > Connections
Do you see the connection there as connected or broken? 
![image](https://user-images.githubusercontent.com/89584709/137147106-c891778e-f070-44f1-9cd9-015d01479d22.png)

If these are broken you need to redo the security setup steps (add client id / secret / etc) and then recreate.

**Comment by Jenefer-Monroe** [comment]
I spoke with someone and they said this could be a relic of when we used to ship the custom connector in Audit Logs solution itself. 

If that is the case, then when you are ready to upgrade next (Nov release perhaps), you can delete the Audit Log solution, Delete the custom connector from the environment entirely, upgrade to Nov and try again.

**Comment by Jenefer-Monroe** [comment]
Nov is shipped.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
