### ISSUE TITLE
[ALM Accelerator - BUG]: Pack msapp files  - deploy pipeline Issue [AA4AM]

### ISSUE THREAD

**Issue by mehakvij** [microsoft/coe-starter-kit#1364]
### Describe the issue

When running the deploy pipeline, I am getting the below(attached) error.
[error.txt](https://github.com/microsoft/coe-starter-kit/files/7340243/error.txt)

![image](https://user-images.githubusercontent.com/73190679/137183996-2b27b102-ebbe-48c4-af63-350769e1d8da.png)

canvas manifest: 
![image](https://user-images.githubusercontent.com/73190679/137184212-5971b387-9a40-4f39-88e2-8d9e6bb653c4.png)

### Expected Behavior

Expect deploy pipeline to run and deploy

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

July 2021

**Comment by mehakvij** [comment]
Hi @mikefactorial, so I deleted the original files in the folder and re-exported. I'm trying to deploy again and now getting this error.

![image](https://user-images.githubusercontent.com/73190679/137939261-3aa5cabd-c46d-4609-8014-e66083c68f13.png)

However, I recently re-ran the PowerApp Management command, so not sure why this error is popping up again

**Comment by mikefactorial** [comment]
@mehakvij just ran some tests myself. I was able to reproduce your issue but only where the Application User does not exist in the target environment or doesn't have appropriate permissions. Make sure you have the Application User setup in the target environment.

**Comment by mikefactorial** [comment]
Try running this PS script as an admin to verify appropriate permissions in the target environment. Replacing CLIENTID, CLIENTSECRET, TENANTID, and YOURORG with your SP values and environment name.
```
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
    Install-Module -Name Microsoft.PowerApps.Administration.PowerShell –Force -AllowClobber
    Install-Module -Name Microsoft.Xrm.Data.Powershell –Force -AllowClobber

    Add-PowerAppsAccount -TenantID $tenantId -ApplicationId $clientId -ClientSecret $clientSecret
    $clientId = "CLIENTID"
    $clientSecret = "CLIENTSECRET"
    $tenantId = "TENANTID"
    $url = "https://YOURORG.crm.dynamics.com/"
    $connstr = "AuthType=ClientSecret;ClientId=$clientId;ClientSecret=$clientSecret;Url=$url" 

    $conn = Get-CrmConnection -ConnectionString "AuthType=ClientSecret;ClientId=$clientId;ClientSecret=$clientSecret;Url=$url"

    # Get the EnvironmentName (which is a GUID) of the environment based on the orgid in Dataverse
    $orgId = (Get-CrmRecords -conn $conn -EntityLogicalName organization).CrmRecords[0].organizationid
    echo (Get-CrmRecords -conn $conn -EntityLogicalName organization).CrmRecords[0]
    # Get the Environment using the InstanceId
    $environment = Get-AdminPowerAppEnvironment -InstanceId $orgId
    # Get the Environment name (which is a GUID)
    $environmentId = $environment.EnvironmentName    
    echo $environmentId
```

**Comment by mehakvij** [comment]
Added the app user (totally forgot I was using a new env)

Hopefully I don't get the original error again either. Thanks!
