### ISSUE TITLE
[CoE Starter Kit - BUG] DLP configuration of custom connector

### ISSUE THREAD

**Issue by davidvansickle** [microsoft/coe-starter-kit#1365]
### Describe the issue

We've setup two CoE Environments, LAB and PROD (but both are production environments)
When setting up the second CoE Environment (LAB), the Office 365 Management API is in the DLP Policy for both environments.
The ConnectionID in LAB is:

ConnectionId : /providers/Microsoft.PowerApps/scopes/admin/environments/d8769078-f1c6-4c35-8b94-bda7883324fe/apis/shared_admin-5foffice-20365-20management-20api-5fb797dc59658ede5f/connections/3a15a9b779db40daa850701952624dea

The ConnectionID in PROD is:

ConnectionId : /providers/Microsoft.PowerApps/scopes/admin/environments/21bb34e3-13ce-4415-90e5-b928a8b7ae28/apis/shared_admin-5foffice-20365-20management-20api-5f810e8001d7a977c0/connections/ef44a3b9535543d9a5efb04cb25feada

Component: OFFICE 365 Management API (custom connector)

Solution Audit Logs
Version [2.5]
App or Flow [e.g. Admin | Child Sync ]

### Expected Behavior

Office 365 Management API connector to run without error.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Admin | Child Sync  (all O365 Management API flows)

### Steps To Reproduce

To Reproduce

Go to 'Admin | Child Sync ]'
Click on 'Turn On'
See error
Turn on failed. Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ApiPolicyDataFlowViolation","message":"Admin data policy 'COE' restricts the use of /providers/Microsoft.PowerApps/apis/shared_office365 with /providers/Microsoft.PowerApps/apis/shared_admin-5foffice-20365-20management-20api-5fb797dc59658ede5f.","extendedData":{"violation":{"policyId":"/providers/Microsoft.BusinessAppPlatform/scopes/service/apiPolicies/3a30e2d8-1c44-41e2-8ccf-869bce477326","policyDisplayName":"COE","type":"BusinessAndNonBusinessConnector","parameters":["/providers/Microsoft.PowerApps/apis/shared_office365","/providers/Microsoft.PowerApps/apis/shared_admin-5foffice-20365-20management-20api-5fb797dc59658ede5f"]},"additionalInfo":{}}}}".
Expected behavior
Screenshots

<img width="421" alt="Failing" src="https://user-images.githubusercontent.com/9801374/137218129-94ceec72-3459-438b-9133-1c5220976521.png">

Additional context
The Audit Logs work fine in our Production environment

Custom connectors get real confusing when they are environment specific, I'm wondering if I need to create a whole new Azure AD App Registration for the connector in the new environment?

### Anything else?

<img width="421" alt="Running" src="https://user-images.githubusercontent.com/9801374/137217981-8fdc4011-dd65-4371-a32c-8efa8673d6ed.png">

**Comment by manuelap-msft** [comment]
Hello,

instead of adding the custom connector directly to the DLP policy, I would recommend using a tenant-level DLP policy where you allow-list the custom connector host (manage.office.com), see:
https://docs.microsoft.com/en-us/power-platform/admin/dlp-custom-connector-parity#tenant-level-dlp-policies

It is not necessary to set up separate app registrations for different environments, they can be re-used. I believe the issue is down to DLP configuration. 

Thank you
Manuela
