### ISSUE TITLE
[CoE Starter Kit - BUG] - Audit log solution issue

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/coe-starter-kit#1368]
### Describe the issue

Hello,

We've recently started to see notification alerts from the audit log solution warning that a smaller chunking interval is required to collect all the audit logs entries. 

We've updated the environment variables to a lower interval (30 minutes) as advised but unfortunately the logs still run at the default 1 hour interval. Is this a known bug or have I configured the environment variables incorrectly?

### Expected Behavior

The chunking interval should change to 30 minutes and hopefully make the auto notifications stop.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.50.20210708.1

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

I receive the auto notifications daily at 3pm.

### Anything else?

Refer to the attached screenshots which show the environment variables have been changed in the default solution:
![TimeInterval-Interval](https://user-images.githubusercontent.com/62425530/137283878-acb6b733-77d6-4277-9f3b-deed8fa404d2.JPG)
![TimeInterval-Unit](https://user-images.githubusercontent.com/62425530/137283885-1036c368-be6c-480f-84a5-f961256f4e44.JPG)

**Comment by melmgcoe** [comment]
I ended up setting the interval to 1 minute as I received a single notification yesterday saying one of the runs was truncated. I received another single notification today, however when I check both today's and yesterday's run, I see they completed without issue. Any reason why I'm still seeing the notification appear?

**Comment by melmgcoe** [comment]
Hello, could I please get a view as to why we still receive a notification that the audit log flow has been truncated? It feels like this could be a bug so I'm thinking about upgrading to the latest starter kit version.

**Comment by bigpix2000** [comment]
the guidance on a "hard restart" of a running flow when changing a variable is general and not specific to the CoE ... it would be a good article ;-) THANKS! (yes, this one came up!)
