### ISSUE TITLE
CenterofExcellenceInnovationBacklog_1_20_managed Install using Option 2 MS Teams

### ISSUE THREAD

**Issue by remenator** [microsoft/coe-starter-kit#137]
**Describe the bug**
On the last steps of the install instructions for publishing the Innovation Backlog App, step 19 I get the following error after selecting the MS Teams channel and clicking Publish 
![image](https://user-images.githubusercontent.com/60788944/114280481-48592500-99ee-11eb-892c-4620b9c6ee26.png)
The app is added to the channel despite the error message

**To Reproduce**
1. Go to Step 19 of instructions for installing using Option 2 for MS Teams
2. Click on 'Publish' and select Channel to add to, click Save and Close
3. you will get a message "Didn't Publish" 
![image](https://user-images.githubusercontent.com/60788944/114280537-9e2dcd00-99ee-11eb-9a33-d984aa7bd752.png)

4. But after checking the channel I can see the app has been added to the tab (multiple times since I repeated this process several times)

**Expected behavior**
I should have seen a success message

**Screenshots**
1
![image](https://user-images.githubusercontent.com/60788944/114280585-d2a18900-99ee-11eb-9b92-25ba60e1ad22.png)
2 
![image](https://user-images.githubusercontent.com/60788944/114280597-dd5c1e00-99ee-11eb-9f1e-ff14c53990e3.png)
3 
![image](https://user-images.githubusercontent.com/60788944/114280604-e5b45900-99ee-11eb-90c5-444414e63584.png)
4 
![image](https://user-images.githubusercontent.com/60788944/114280611-eea52a80-99ee-11eb-8909-00c25cc5c21e.png)
5 
![image](https://user-images.githubusercontent.com/60788944/114280616-f49b0b80-99ee-11eb-94e3-8421b100e660.png)

**Additional context**

**Comment by devkeydet** [comment]
Hi @remenator ,
Issues in this repo are mostly unattended at the moment. We're in the process of transitioning CoE Starter Kit here, but for the time being would you mind posting this issue to https://github.com/microsoft/powerapps-tools/issues? The team is actively monitoring issues there until we fully move over.
