### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Command Center app throwing error for Message Center in GCC environments

### ISSUE THREAD

**Issue by rrwolfe** [microsoft/coe-starter-kit#1374]
### Describe the issue

When you open the Admin Command Center app, there's an immediate error at the top of the screen related to a failure with the Command Center App > Get M365 Service Messages flow that seems specific to GCC.

![image](https://user-images.githubusercontent.com/74214126/137477120-a189a350-cbf6-46ea-aeb2-25bdc24e76bd.png)

![image](https://user-images.githubusercontent.com/74214126/137477177-1d0212cf-1639-4e23-bac0-3b6991d320cc.png)

### Expected Behavior

The Command Center App > Get M365 Service Messages flow should run successfully and display data in the app

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Command Center App > Get M365 Service Messages

### Steps To Reproduce

1. Run the Command Center App > Get M365 Service Messages flow in a GCC environment

**Comment by Jenefer-Monroe** [comment]
While we have not resolved the issue making the messages available in GCC, we have made the failure show as a label in the app rather than as a failure. So the rest of the command center will be more usable starting Jan 2022 release.
