### ISSUE TITLE
If the maker selected  Approve by mistake . "Are you still using your Apps/Flows "

### ISSUE THREAD

**Issue by EmranCoE** [microsoft/coe-starter-kit#1378]
### Describe the issue

I am working as a Power Platform Admin . 
Those two components (Admin | Archive and Clean Up v2 (Start Approval for Flows/Apps)  when sending a request to the makers "Are you still using your Apps/Flows " If the maker selected Approve by mistake is there any option to cancel the Approve request  to stop  deletion process ? 

![InkedGithub__LI](https://user-images.githubusercontent.com/90054514/137938416-7ba0af08-a147-4ffa-a4a3-27e3d8575ccc.jpg)

For the same components I have another question : Right now its sending the request to the CoE Environmnet flows as well  ,is there any alternative to exclude the CoE Environment so those components  will not send request to the CoE Environment flows ("Are you still using your Apps/Flows ")

Many Thanks .
Regards

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Flows/Apps)

**Comment by Jenefer-Monroe** [comment]
You can preview apps/flows that have been approved but not yet deleted using the [app and flow archive and clean up view](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#app-and-flow-archive-and-clean-up-view) app in gov, and you can then go manually change the value in the database. 
If its already deleted, you will need to contact support and they can restore it.

**Comment by EmranCoE** [comment]
Thank you !
One more question, If I understand right!
Following this documentation:
https://docs.microsoft.com/en-gb/power-platform/guidance/coe/governance-components#app-and-flow-archive-and-clean-up-view

So, even the maker click Approve by mistake
In the “App and Flow Archive and Clean Up View” App
If we select “Mark app/flow as excused “ == apps/flows will not be deleted
