### ISSUE TITLE
Filter out "Request Sign-off" flows from Clean Up Admin flow

### ISSUE THREAD

**Issue by morismm99** [microsoft/coe-starter-kit#1381]
### Describe the issue

Currently, the "Admin | Archive and Clean Up v2 (Start Approval for Flows)" flow includes the SharePoint document library built in "Request Sign-off" flow, which is attached to the user who enables/configures this flow. 

This flow, as far as I know cannot be edited by the owner, as it is tied to the SPO site, however, the admin flow above queries is and the owner is sent an approval if the flow was configured six months ago. Again, the user has no way to edit this flow (re-save). 

Thus, user has to reject every month if still being used.

### Expected Behavior

I have complimentary power shell scripts I had enabled, and are still running that delete truly orphan flows that have no owners, or anyone else with view/edit permissions. I am filtering out these special "Request Sign-off" SharePoint flows, as to prevent breaking those workflows in SharPoint Online document libraries.

Perhaps, the admin flow in question can be modified to also filter out these specific flows?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.50

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Flows)

**Comment by morismm99** [comment]
Sorry, let me explain a bit better.

The "Request Sign-off" is a flow makers are creating by enabling it in an SPO document library.

https://docs.microsoft.com/en-us/business-applications-release-notes/april18/microsoft-flow/request-sign-off-flow-built-into-sharepoint

The "Admin | Archive and Clean Up v2 (Start Approval for Flows)" clean up flow as part of the Governance solution catches all of the Request Sign-off flows which have not been modified in the past 6 months (using default time frame). However, owners of that flow (who are the users who initially configured it in a document library) are getting approvals to see if these can be deleted. These request sign-off flows cannot be edited by the user.

These unique flows do now show up under the maker's My Flows or Shared flows. Thus, these cannot be edited/re-saved, in order to avoid getting approvals for these.

Like you said, I avoid adding too many customizations to any of these CoE kit flows/apps.

I could edit this action in the "Admin | Archive and Clean Up v2 (Start Approval for Flows)"

![image](https://user-images.githubusercontent.com/72099434/138096306-055f7b79-dc52-4584-b8b7-e6b9f257c7e3.png)

Modifying the Filter rows section, to filter out these flows based on the display name of "Request Sign-off" flows.

Hope the above clears the waters :-)

**Comment by Jenefer-Monroe** [comment]
It looks like the product fixed this up so they now show up under "Shared with me" WOOHOO!!! 

![image](https://user-images.githubusercontent.com/89584709/145411783-2be5caf0-07cb-4f10-a1f7-d6c7ccf151b2.png)

Closing out as a result. 
Thanks for helping us understand the product even better! :)
