### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by azhar2501** [microsoft/coe-starter-kit#1386]
### Describe the issue

Hello,
We have notice that the table Power Platform User Role is not being correctly filled as the column "Flow' is empty. Please refer to the picture as attachment
![image](https://user-images.githubusercontent.com/87812978/138267075-6a60774d-b220-4977-88db-bc1f01759cc1.png)

### Expected Behavior

We expected to see all the owner(s) of Power Automate.

Thank you very much in help us with this issue

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

Admin - Sync Template V3 (Flows)

### Steps To Reproduce

Open https://make.powerapps.com/ in the environment where the COE Starter Kit is installed
Open Tables
Ensure the filter is set to 'all'
Search for "Power Platform User Role"
Open the table
then click on "data"

### Anything else?

This a suggestion for the process of dealing with orphaned objects.
In case of no answer from the manager, we can consider of reassigning the orphaned objects to their co-owner.
Hope this may help you in enhancing the CoE Starter Kit

**Comment by manuelap-msft** [comment]
This is expected behaviour. At the moment, the CoE kit only gathers user information for Power Apps and not for Flows. The Flow field was added to this table in preparation only for when we can fund this work. 

Thank you
Manuela
