### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot share Developer Compliance Center

### ISSUE THREAD

**Issue by MartinWhiteDAZN** [microsoft/coe-starter-kit#1387]
### Describe the issue

When sharing the Developer Compliance Center app with colleagues, the app does not work - it gives permission errors.
I have followed the instructions for sharing tables with colleagues i.e.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#share-the-app-from-a-dataverse-for-teams-environment
Tables: PowerApps App, Environment, Flow, PVA, Desktop flow and COE Settings

But the errors say access is required to: Maker, PowerApps Connectors and ArchiveApproval.
So I gave colleagues collaborate access to these additional tables but it still does not allow them to submit details and there is an error message that flashes up way to fast to read it.
It gets stuck on "Getting your data ..." when submit is clicked.

What should the access be for colleagues that is missing from the above documentation link?

Example error:
You don't have permission to view this data. Server Response: PowerApps Connectors failed: Principal user (Id=xxxxxxxxxxxxxxxxxxxxx, type=8, roleCount=1, privilegeCount=78, accessMode=0), is missing prvReadadmin_Connector privilege (Id=c9ab7812-385a-4f57-bf8e-08f319342aef) on OTC=10098 for entity 'admin_connector' (LocalizedName='PowerApps Connector'). context.Caller=316fe654-ba2d-ec11-b6e5-000d3ab6a040

### Expected Behavior

The Compliance Developer Center should be shareable with users outside of the Teams that it was deployed to so that they can submit their compliance details.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Developer Compliance Centre app

### Steps To Reproduce

In the Teams environment, following the sharing instructions here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#share-the-app-from-a-dataverse-for-teams-environment
Share with a security enabled Team.
Expect users of that Team to be able to submit compliance details.

**Comment by manuelap-msft** [comment]
Hello,

I believe makers may require Full Access to update Dataverse records.

Here's why:
1. The way data is written to Dataverse tables is by the sync flows that run daily and write information about apps, flows, environments... to Dataverse tables.
2. These flows are run by the admin, and all records in Dataverse are then owned by the user running the flows. They are not owned by the maker.
3. The Collaborate permission gives update permission to "your own records" which a maker will not have any of. 

Hope that makes sense,
Manuela

**Comment by mikefactorial** [comment]
@MartinWhiteDAZN This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
