### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flows) bug with Record Creation and Update Rules

### ISSUE THREAD

**Issue by ericregnier** [microsoft/coe-starter-kit#1398]
### Describe the issue

_Admin | Sync Template v3 (Flows)_ run fail when _Record Creation and Update Rules_ exists in the target environment.

**Actual Results**
- Fails at step "Get New Flow as Admin" with not found error, but flow is found at step above "List Flows as Admin"
- "Admin | Sync Flow Errors" error email is received
- Error details: "_admin_flow With Id = 38864a7b-3903-ec87-6538-9013fc59ebda Does Not Exist_"

### Expected Behavior

_Admin | Sync Template v3 (Flows)_ completes successfully either skipping **Record Creation and Update Rules** types or catering for them. Ideally, we would be able to keep an inventory of them like cloud and desktop flows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### Steps To Reproduce

1. Create a new _Record Creation and Update Rule_
2. Run the _Admin | Sync Template v3 (Flows)_ cloud flow

**Comment by Jenefer-Monroe** [comment]
I dont repro this now. Perhaps the product team fixed this up. Do you still see these in the List Flows as Admin call? And if so, can you please share how the objects being incorrectly returned were created? Perhaps you are making things differently than me, and hence they show up.

**Comment by ericregnier** [comment]
Hi Jenefer, cheers for following-up. Unfortunately I still get the flows errors complaining about Record Creation and Update Rules. My tenant is in a dedicated scale group in case not all groups got the updates.

**Comment by Jenefer-Monroe** [comment]
Can you perhaps share a document showing how you created these rules? Perhaps I didn't create them the same way. I do not have a dynamics background and so I was winging it trying to repro for you.

**Comment by ericregnier** [comment]
Here's the doc: https://docs.microsoft.com/dynamics365/customer-service/set-up-rules-to-automatically-create-or-update-records, also happy to jump on a call, PM me for the details. Cheers

**Comment by manuelap-msft** [comment]
Closing out issues with no further aciton on the CoE kit team. We are unable to repo this issue, and have not heard about it from other customers so far so this may be a product bug to raise as a Microsoft support ticket.
