### ISSUE TITLE
[CoE Starter Kit - BUG] App audit process not working correctly

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#1407]
### Describe the issue

I am testing the App audit process in Power Platform Admin View but not able to get it working correctly or maybe doing something wrong. When maker have submitted business justification and app is shared broadly the BPF starts but it is deactivated immediately. The "Next stage" does not work and it seems that I am only able to abandon the flow. 

![image](https://user-images.githubusercontent.com/8307644/139010717-dff6cf1a-f400-48e5-a22b-f13221010614.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Nov has shipped, closing this out, please return if you have issues.

**Comment by petepuu** [comment]
Ok thanks! Will test this week
