### ISSUE TITLE
[CoE Starter Kit - BUG] Approval  user has insufficient permissions to the CoE Environment

### ISSUE THREAD

**Issue by DemosPapa** [microsoft/coe-starter-kit#1409]
### Describe the issue

"The request was archiving was unable to process as the user has insufficient permissions to the CoE Environment. Please give them permissions to Approvals in the CoE to proceed."

How we correct this warning?

thank you

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Flows)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for toolkit team.
