### ISSUE TITLE
Settings for Custom Connector for Audit Logs will not save

### ISSUE THREAD

**Issue by RodneyHart** [microsoft/coe-starter-kit#1410]
### Describe the issue

I am trying to set up the Custom Connector for audit logs as detailed here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
I input all of the data and then click on 'Update Connector'.  The page acts like it is saving and then comes back to a blank page.  I have tried saving numerous times, but the page is always blank after clicking 'Update Connector'.  I have even tried to navigate on to the next page and then save but I still get the same result - no data in the connector setup.

### Expected Behavior

When I click 'Update Connector' the data that has been entered for client id, client secret, and resource URL should be saved.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Custom Connector

### Steps To Reproduce

Setting up the custom connector as per the instructions detailed here:  https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog.  After clicking 'Update Connector' nothing is saved.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for toolkit team.
