### ISSUE TITLE
DLP Editor V2

### ISSUE THREAD

**Issue by mzd4fz00** [microsoft/coe-starter-kit#1412]
### Describe the issue

Whenever we run the DLP Editor V2 using the Play button or if we preview it, we end up with an initial screen where we can select an environment but the rest of the screen is blank.  Ref screenshot.  We realize this may not be a bug but a configuration issue on our side.  Is this a known experience with the DLP Editor V2?  I checked for unmanaged layers on the DLP Editor V2 but only see 1 layer.  

We did do an upgrade today from an earlier version of the Center of Excellence - Core Components to version 3.13.  Is there a likely config activity we are missing?  I looked through other reported issues but didn't notice one like ours readily.  Thanks in advance for any thoughts.

![example](https://user-images.githubusercontent.com/91695437/139137400-3fe7c0de-5c5e-4dfb-a342-683c6163f8f1.PNG)

### Expected Behavior

We were anticipating we would see more than the blank screen

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

Open the DLP Editor V2
press the Preview button (or simply launch the DLP Editor from within the solution)

**Comment by mzd4fz00** [comment]
Thanks Jenefer.  In our environment we don't yet have any DLP policies setup, but we wanted to preview the impacts of future DLP policies that we will define to understand what apps and flows would be impacted.  The team thought they had used the DLP editor in the past to do that, but is that not the right tool to use if we wanted to preview future impacts of DLP policies not yet defined?

Also, even when using the Preview function of the DLP editor in design mode (F5 key), does the account that runs the preview of the app still need a premium license (Power Apps per user license or a Power Apps per pass license) in order to successfully preview it?

**Comment by Jenefer-Monroe** [comment]
this works for existing DLP policies, please create them with the product UX, then you can use this app for impact analysis of changes made.

**Comment by groypk** [comment]
I have the same issue in my test environment, the DLP editor opens, but there is no option of creating new polices

**Comment by manuelap-msft** [comment]
We don't support creating new policies through the DLP editor. You will have to create them through the Power Platform Admin center aka.ms/ppac. 

Closing this out as no action required on the CoE team.
