### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by smlwilliams** [microsoft/coe-starter-kit#1414]
### Describe the issue

We are setting up a Teams dataverse Starter kit. After setting up the Power Bi report we noticed that it did not pull any data from our default environment.

### Expected Behavior

We should be seeing in our report all data for all the environments in our enterprise

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2021

### What app or flow are you having the issue with?

Dataverse_CoEDashboard_202110.pbit

### Anything else?

No

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for toolkit team.
