### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Check Deleted) runs for days and then fails

### ISSUE THREAD

**Issue by pallvip** [microsoft/coe-starter-kit#1416]
### Describe the issue

Hi I have the flow 'CLEANUP - Admin | Sync Template v3 (Check Deleted)' run for days and then fails as it can find environment with error Action 'Get_Environment_as_for_bots' failed.

This has been happening for few weeks now. 
Recently I have got another bug in the environment where it doesnt identify per flow passes since I had to remove passes and had to re-add them since we change our re-seller. 

### Expected Behavior

I would expect the flow to complete without errors 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.89

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Jenefer-Monroe** [comment]
Nov has shipped.

**Comment by pallvip** [comment]
Hi Jenefer 

I have installed the core components for the Nov version and it has pagination errors, I have logged another issue for that here - https://github.com/microsoft/coe-starter-kit/issues/1450

**Comment by Jenefer-Monroe** [comment]
Hello, per Manuela's comments in that issue, the pagination is high to support many of our large customers. You may have been using a trial or seeded license? Please see our [Prereqs](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites) for details

**Comment by pallvip** [comment]
I am installing it in Dev tenant first as need to follow change control and using per user license. 
Buying licenses for 3 separate tenants (Dev test and prod) is going to be tricky. 
Is it possible to get any package version which can take lower pagination so we can try that in Dev rather than having to go and tweak each flow manually?

**Comment by Jenefer-Monroe** [comment]
Unfortunately that is not something we can provide.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
