### ISSUE TITLE
[CoE Starter Kit - BUG] Error on "export-solution-to-git"

### ISSUE THREAD

**Issue by raduneda** [microsoft/coe-starter-kit#1419]
### Describe the issue

On the following version of the pipeline templates: [https://github.com/microsoft/coe-alm-accelerator-templates/releases/tag/1.0.20210521.1a](url) I receive an error at the 'unpack msapp files' files:
`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at temp_canvas_packager.Program.Main(String[] args)
`
This happens for a managed solution that contains an "*.msapp" file:
![Annotation 2021-10-29 104550](https://user-images.githubusercontent.com/11891742/139396177-18989969-0372-4958-aa09-91622adaa7b3.png)

### Expected Behavior

The 'unpack msapp files' should pass successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.0.20210521.1a

### What app or flow are you having the issue with?

coe-templates

### Steps To Reproduce

1. Import templates from: [https://github.com/microsoft/coe-alm-accelerator-templates/releases/tag/1.0.20210521.1a](url)
2. Run the "Push Changes To Git" step from ALM Application 
3. Pipeline fails when extracting "*.msapp" file

**Comment by mikefactorial** [comment]
@raduneda following up on this to see if my previous comment was helpful.

**Comment by raduneda** [comment]
I can confirm that it works correctly with the latest version. Thank you!

**Comment by mikefactorial** [comment]
Closing this issue as resolved
