### ISSUE TITLE
[CoE Starter kit] Struggling to install Nurture Components

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1421]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/1415

<div type='discussions-op-text'>

<sup>Originally posted by **gazzz99** October 28, 2021</sup>
I am struggling to install the Solution for Centre of Excellence Nuture Components - on solution import it fails with error message 80040224 - A task was cancelled. This is error "An unexpected error occurred from ISV code"

I have managed to install the Solutions for Centre of Excellence Core Componenets and the Governance Components but not this one.

Anyone any ideas please?</div>

**Comment by fjoesne** [comment]
I see the exact same behavior as @gazzz99 
Same behavior on second attempt.

**Comment by gazzz99** [comment]
I have tried from flow.microsoft.com as well but get the same original error I'm afraid

**Comment by Jenefer-Monroe** [comment]
When I see this failure, a retry succeeds, and I have never had to hop into flow.microsoft.com to make it work. Though I have occasionally had to retry more than once. I think its some intermittent service issue. 

To both of you I would recommend attempting an overwrite for install: 

Solution > Switch to Classic (note this can take some time, may have to try twice)  
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png) 

Click Import (fourth from the left)  
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png) 

Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import  
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png) 
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by gazzz99** [comment]
Thanks Jenefer - unfortunately I get the same result in the same place when using the classic view as well - "An unexpected error occurred from ISV code". I am using a trial licence for my environment but it did let me install the previous 2 solutions.

**Comment by Jenefer-Monroe** [comment]
You will not be able to use the toolkit with a trial license. You will get pagination errors when you try to run the flows in Core. 

One last thing I can offer for you to try is installing nurture without the dataflow, I'm not sure if that feature supports trials. Here is a version of nurture without the dataflow

[CenterofExcellenceNurtureComponents_2.3_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7286983/CenterofExcellenceNurtureComponents_2.3_managed.zip)

**Comment by Jenefer-Monroe** [comment]
thanks for confirming. It appears that trial licenses cannot install dataflows then. I will keep this knowledge in my back pocket. 

I will go ahead and close this issue now.
