### ISSUE TITLE
[CoE Starter Kit - BUG] - DLP Editor V2 Impact Analysis page is not showing results

### ISSUE THREAD

**Issue by selo89** [microsoft/coe-starter-kit#1422]
### Describe the issue

When creating a DLP Policy on the DLP Editor with e.g. the SQL Server blocked within the results page no list is visible. 
![Capture1](https://user-images.githubusercontent.com/93386318/139437915-f8351c9f-df29-40ac-8f6f-f9b23cec8597.PNG)
![Capture2](https://user-images.githubusercontent.com/93386318/139437926-1e4f75ea-a029-4975-8e2d-5bd708638a3e.PNG)

### Expected Behavior

I would expect to see whole bunch of Apps using the SQL Connector. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.21091.38

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

1. Click on Create New Tenant Policy
2. Name it
3. Select Connectors to be blocked e.g. SQL
4. Select Scope
5. Select Environment in which this connector definetely is being used
6. Go to impact analysis

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for toolkit team.
