### ISSUE TITLE
[ALM Accelerator - BUG]: Connection references will not export to deploymentSettings.json

### ISSUE THREAD

**Issue by mdpc-nnit** [microsoft/coe-starter-kit#1423]
### Describe the issue

This issue was found as part of the following discussion:
https://github.com/microsoft/coe-starter-kit/discussions/1370#discussioncomment-1551286

When exporting a solution, the connection references are not added to the deploymentConfig.json file, neither are they added as variables in the deploy pipeline.

Environment variables are, for the record, added as expected.

### Expected Behavior

When a solution is exported through the AA4AM app, the deploymentConfig.json file is updated with the necessary connection reference section, e.g.:
```
    "ConnectionReferences": [
        {
            "LogicalName": "new_sharedsharepointonline_b49bb",
            "ConnectionId": "#{connectionreference.new_sharedsharepointonline_b49bb}#",
            "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_sharepointonline"
        },
        {
            "LogicalName": "cat_CDS_Current",
            "ConnectionId": "#{connectionreference.cat_CDS_Current}#",
            "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps"
        }
    ]
```
Also, the pipeline variables should be added to the deploy pipeline with the relevant connection id, eg:
`connectionreference.new_sharedsharepointonline_b49bb = 1234...`

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20211001.1

### Steps To Reproduce
NB: This might be a regional issue.
Region of affected power platform environment: Europe

Starting point:
1. Alm Accelerator app and pipelines installed and configured
2. Pipelines from commit [f7697ed](https://github.com/microsoft/coe-alm-accelerator-templates/tree/f7697ed81e58f7d1542c988b5c9801b9172c0da9)
Repro steps:
1. Create a solution with at least one connection reference.
2. Export solution via canvas app.
3.  Go to repo where solution is exported. Browse to [solutionname]/config/deploymentSettings.json
4.  Verify that there is no entry under Connection References. I.e. the connection reference section looks like:
```
    "ConnectionReferences":  [
 
                            ]
}
```

### Anything else?

The issue has been located to the following lines of code:
The query in [line 77](https://github.com/microsoft/coe-alm-accelerator-templates/blob/f7697ed81e58f7d1542c988b5c9801b9172c0da9/Pipelines/Templates/update-deployment-settings.yml#L77) gives me the output `10.184` whereas the `$solutioncomponent.componenttype_Property.Value.Value` used in the comparison in [line 81](https://github.com/microsoft/coe-alm-accelerator-templates/blob/f7697ed81e58f7d1542c988b5c9801b9172c0da9/Pipelines/Templates/update-deployment-settings.yml#L81)
is without the dot, i.e. `10184`.

Suggested fix: use the 
`-replace '\.',''`
flag to remove all dots from the queries.

**Comment by mikefactorial** [comment]
Closing this issue as resolved. Thanks @mdpc-nnit
