### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs solution fails after upgrade

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1424]
### Describe the issue

**Custom Connector lost on upgrade** 

Your audit log flows may fail after an upgrade due with an Auth error to the connection being broken. 

If you go to your connectors you will see your broken connector, clicking fix connection will not fix it: 

![image](https://user-images.githubusercontent.com/89584709/132773412-f0948b08-015c-414b-bd2c-6dd154564a22.png) 

  

  

The easiest way to fix this is to reset the custom connector and then fix the connection. This will allow you to fix the situation without editing the flow 

  

**Fix it without editing your flow** 

1) Open the custom connector for edit 

![image](https://user-images.githubusercontent.com/89584709/132773567-29ff5b59-3d3f-4aad-83d1-98c93a786170.png) 

  

1) Go to 2. Security, and chose to Edit under the Authentication type 

![image](https://user-images.githubusercontent.com/89584709/132773648-60fd808f-b64c-4d06-b59b-1f34f75b3023.png) 

  

1) Add the client id, secret and resource url that you used when you first set up the custom connector, and hit update connector 

![image](https://user-images.githubusercontent.com/89584709/132783527-342754dc-b4b1-41f8-8155-858822c58a49.png) 

  

1) Go back to the connection and hit **_Fix connection_** 

![image](https://user-images.githubusercontent.com/89584709/132773964-7c3ecb7e-4b8c-40ff-a5a9-6a6b321fe3a4.png) 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Audit Logs

**Comment by MenakaPurushothaman** [comment]
Hi Jenefer

1. Reestablished the connection both under Dataverse and Custom Connectors.
2. Under Custom Connectors -> when updating the connection and Test Operation is performed I see the below response.
{
  "error": {
    "code": "AF20024",
    "message": "The subscription is already enabled. No property change."
  }
}

**Comment by MenakaPurushothaman** [comment]
[CoE Audit Logs Solution Error.docx](https://github.com/microsoft/coe-starter-kit/files/8492494/CoE.Audit.Logs.Solution.Error.docx)

**Comment by keharrin** [comment]
That solution fixed it.  Thank you so much as always for the quick response!

**Comment by manuelap-msft** [comment]
Closing out as this solution is now deprecated.

**Comment by Star-Donovan** [comment]
> Closing out as this solution is now deprecated.

It should probably be removed from the upgrade documentation then.
See https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup#updating-the-audit-log-solution , which still links to this github

**Comment by rmedrano2** [comment]
> Closing out as this solution is now deprecated.

The CoE Update documentation is still pointing here - is this still relevant?
