### ISSUE TITLE
[ALM Accelerator - BUG]: deploymentSettings.json file dont have connection reference details after exporting solution to git

### ISSUE THREAD

**Issue by pvarma8** [microsoft/coe-starter-kit#1426]
### Describe the issue

My solution contains flows and connection references and no environment variables. I haven't used any environment variables in my solution. 

After exporting solution to git using the AA4AM App I am not able to see anything under connection references in deploymentSettings.json file in my repository.

![image](https://user-images.githubusercontent.com/46042294/139837590-835a2a6f-1afc-4215-9b09-825cdf039387.png)

### Expected Behavior

The deploymentSettings.json file should update with the necessary connection references from the solution.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

ALMAcceleratorForAdvancedMakers_1.0.20211001.1

### Anything else?

The export solution to git pipeline throwing a warning message at Update deployment settings yml file step. 

![image](https://user-images.githubusercontent.com/46042294/139837909-abb19aab-2753-43aa-9d5b-f055145e17eb.png)

**Comment by mikefactorial** [comment]
@pvarma8 a couple of things to check here. 
1. Make sure you have the latest pipelines from this tag https://github.com/microsoft/coe-alm-accelerator-templates/releases/tag/ALMAcceleratorForAdvancedMakers-September2021a. Specifically, check that the update-deployment-settings.yml file is up to date.
2. Could be related to this issue which another user reported https://github.com/microsoft/coe-starter-kit/issues/1423#issue-1039541330

**Comment by mikefactorial** [comment]
One more thing to check based on the error message about invalid configurationData. Can you see what value was passed into the Data variable of the export pipeline?

![image](https://user-images.githubusercontent.com/42348035/139921013-f145cb5a-1ab6-4a40-8f01-e3495a74a3f7.png)

**Comment by pvarma8** [comment]
@mikefactorial Thank you for your inputs, After updating the update-deployment-settings.yml file, I can see the connection references in the deploymentSettings.json file.

Regarding the Data variable under the export pipeline, I don't see anything related to data.

![image](https://user-images.githubusercontent.com/46042294/140031724-5844aa29-39b8-4f7d-ad17-00a323e60002.png)


Still I could see the Invalid JSON warning for Update Deployment Settings task.

Initially i forgot to mention you that there are 3 other warnings for the export to git pipeline.
![image](https://user-images.githubusercontent.com/46042294/140032429-9dbbcc51-3e6d-44b5-a098-8475326102d5.png)

Need your help on this.

**Comment by pvarma8** [comment]
@mikefactorial Regarding the Data variable under the export pipeline, I don't see anything related to configurationdata. Am i Missing anything?

**Comment by mikefactorial** [comment]
Hmm. @pvarma8 have you visited the Configure Deployment Settings screen for your solution prior to export? We may not be handling the scenario where that screen is not visited first, but you should be seeing a "Data" parameter coming in to that pipeline if you did.

![image](https://user-images.githubusercontent.com/42348035/140327441-a2532ae6-13f2-4869-842c-856788d40341.png)

**Comment by pvarma8** [comment]
@mikefactorial, My app is not showing that configure Deployment Settings link. I can only see the option Open Solution

**Comment by pvarma8** [comment]
I am using the latest version of the App. I cannot see the configure Deployment Settings page
![image](https://user-images.githubusercontent.com/46042294/140330883-e19eddb3-6485-41c6-8013-6142120c91d0.png)

**Comment by mikefactorial** [comment]
@pvarma8 did you upgrade to the latest version from a previous version? I wonder if there may have been some unmanaged changes in the previous version that are causing you to not see the latest interface in the app? You may want to try uninstalling and re-installing the solution.

**Comment by rfarris2000** [comment]
I'm seeing this issue as well.  I see the the data tag has [{EnvironmentUrl": "XYX.crm.dyanmics'.com/""UserSettingId": [{"EnvironmentUrl":"https://mycoeenvironment.crm.dynamics.com/""UserSettingId":[{"cat_usersettingid":"<GUID>"},{"cat_usersettingid":"<GUID2>"}]}]

Update deployment settings has:

"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\1b9b6ee4-63e8-4fc0-b47a-f95aec794e2c.ps1'"
0
0
1
0
2
3
0
0
1

The deploymentSettings.json file is empty.  I'm on the latest version.  All other pushes and pull requests work but the connection references are not coming through.

**Comment by pvarma8** [comment]
It worked for me after completely uninstalling and reinstalling the solution. 


> @pvarma8 did you upgrade to the latest version from a previous version? I wonder if there may have been some unmanaged changes in the previous version that are causing you to not see the latest interface in the app? You may want to try uninstalling and re-installing the solution.

**Comment by rfarris2000** [comment]
I've found the issue in update-deployment-settings.xml
```
Line 77
    #There is an extra '.' character being introduced in specific locales. The regex replace on the objecttypecode below is to remove it.
    $connectionReferenceTypeCode = $solutionComponentDefinitionsResults.CrmRecords[0].objecttypecode -replace '\.',''
```

This outputs the value as 10,049.  I wrapped a [int] conversion on it and that works.

@mikefactorial FYI

**Comment by mikefactorial** [comment]
@rfarris2000 thanks for looking into this. Mind creating a PR for the fix you made in [the template repo](https://github.com/microsoft/coe-alm-accelerator-templates)? It brings up something that we probably need to update in our docs and in the coe-cli as well. Looks like you are using the latest pipelines in our main branch rather than the pipelines from the latest release which is something we need to address since we are committing to main during our release development.

**Comment by rfarris2000** [comment]
@mikefactorial Done and done.

**Comment by mikefactorial** [comment]
Hey, this open-source thing really works! Thanks @rfarris2000 🥇 👍

**Comment by mikefactorial** [comment]
And thanks @pvarma8 for the assist!
