### ISSUE TITLE
[CoE Starter Kit] Redundant flows in governance components (CanvasAppOperations, CloudFlowOperations )

### ISSUE THREAD

**Issue by fjoesne** [microsoft/coe-starter-kit#1429]
**Is your feature request related to a problem? Please describe.**
Gov flows are nearly identical to existing Core flows.

Flows need to be set up with run only users by Power Platform admins both at initial setup and updating which leads to increased maintenance and complexity (the same goes for solution development).

**Describe the solution you'd like**
Use the flows that exist in core components, point to them using environment variables.

**Describe alternatives you've considered**
Adding an unmanaged layer in gov for all apps and flows that use the core flows instead, but this may just complicate the update process.

**Additional context**
Only differences I can see is that the Gov version provides some options for the actions input (also appears to use generated name of the action input, this is possibly a bug) and returns slightly different values with the same meaning ("fail" <=> "failed"). There are some other differences, such as the `ReturnValue` variable,  but input and putput seem to be the same `ReturnString` variable. 
(Perhaps there are some plans to use a http response in the future, but that does not seem to be the case with core version 3.13) 
 
Core CloudFlowOperations:
![image](https://user-images.githubusercontent.com/10668631/140049425-f34ae75a-cb52-47bc-818b-e9eee97a4bfb.png)

Governance CloudFlowOperations:
![image](https://user-images.githubusercontent.com/10668631/140049085-1423a509-f7eb-4624-9d92-5fec098b4eb8.png)

**Comment by manuelap-msft** [comment]
Hello,

these are child flows, and there is a product limitation in that child flows can't be used across solutions - we have a need to use these flows in both Core and Governance components but had to duplicate them so they can be used. 

Manuela
