### ISSUE TITLE
How to change CoE email/message sender ? (Environment variables “Admin eMail” and “Approval Admin”  )

### ISSUE THREAD

**Issue by EmranCoE** [microsoft/coe-starter-kit#1430]
### Describe the issue

Hi ,

There are many CoE components (Flows) which are sending out Welcome email/justification messages to the makers specially for (Admin | Archive and Clean Up v2 (Start Approval for Flows/Apps)) are you still using your apps/flows ? etc. 

I am wondering which options are available If I do not want to use my name/email (emran…@...com) as a sender instead of my email can use Platform Admin/CoE components  , to do that I have created a new account and changed those two environment variables “Admin eMail” and “Approval Admin”   but it doesn’t work still sending the mail from my previous account , I tried turn on/off flows also publish all customizations .
There might be other settings/access need to assign on this  ! 

 Many Thanks !

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Flows/Apps) , Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created

**Comment by Jenefer-Monroe** [comment]
Here is a write up by someone on different ways to do this: [3 ways to change email sender address in Power Automate](https://tomriha.com/3-ways-to-change-email-sender-name-in-power-automate/)

The service account methodology they reference is the one you could do without making edits to the flow. 
Hope that helps, and closing out as this out as there is no action for the toolkit team.
