### ISSUE TITLE
[CoE Starter Kit - BUG] - Forms for the PowerPlatform Admin View have not been installed

### ISSUE THREAD

**Issue by renaudarmstrongvictrix** [microsoft/coe-starter-kit#1431]
### Describe the issue

Looks like the tabs and forms for the ModelDriven App "PowerPlatform Admin View" are not showing correctly.
![image](https://user-images.githubusercontent.com/91679305/140073408-1c33a0b7-f49e-4c1b-9eef-8a9e04e9e755.png)

### Expected Behavior

Expecting tabs with name and apps life cycle time line at the top
![image](https://user-images.githubusercontent.com/91679305/140074477-a29b296d-0b41-4177-bd5b-ba8e93d9aeed.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

PowerPlatform Admin View

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid I dont repro this. I wonder if its something to do with your language settings. Can you please [add the English language pack](https://docs.microsoft.com/power-platform/guidance/coe/limitations#supported-languages) and see if it resolves?

**Comment by renaudarmstrongvictrix** [comment]
Hi,
The english pack is activated
![image](https://user-images.githubusercontent.com/91679305/140524187-9337c0b4-ea76-4f18-b23a-cabef2203d9e.png)
![image](https://user-images.githubusercontent.com/91679305/140524497-69173136-9b74-435c-a3f5-815269847260.png)

**Comment by Jenefer-Monroe** [comment]
Got it.

I dont repro and have never heard of this issue before. It could be that these were editted on your side by someone. 
Model Driven apps support merge, so we cant revert, but you can fix this up yourself

Here are the correct strings:
![image](https://user-images.githubusercontent.com/89584709/140542316-c165dcca-77ec-43bb-8eab-80124d4be3f5.png)

Let me know if you need some tips on how to edit those.

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for toolkit team
