### ISSUE TITLE
[CoE CLI]: Is CoE CLI available for GCC?

### ISSUE THREAD

**Issue by osbornecc** [microsoft/coe-starter-kit#1434]
### Describe the issue

Hi there,
I know that the Power Platform CLI is unavailable in GCC:
![image](https://user-images.githubusercontent.com/50427725/140187816-1a8232bf-99ea-4fcc-a486-527aa3eff657.png)

Is the CoE CLI available for use in GCC? https://github.com/microsoft/coe-starter-kit/tree/main/coe-cli#readme
We're seeing if the ALM Accelerator for Advanced Makers will work for us.

Thank you.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

3.11

**Comment by Grant-Archibald-MS** [comment]
@mikefactorial GCC configuration deployment has not been tested. if a setting **endpoint** is usgov is selected in the coe aa4am install then it should select the correct API endpoints to import the solution.

**Comment by Grant-Archibald-MS** [comment]
@osbornecc the **CoE CLI** currently uses the REST API to import the ALM Accelerator for Advanced makers into a power platform environment. So it should enable the managed AA4AM solution to be imported.

The main follow up question is the Azure DevOps pipelines used by the ALM Accelerator which do make use of the **Power Platform CLI**, which the above link indicates is not supported in GCC environment.

**Comment by osbornecc** [comment]
@Grant-Archibald-MS thank you for the distinction.  I'll tell my team and let them decide if they want to try it out or not.  Thanks for the quick responses!

**Comment by mikefactorial** [comment]
@osbornecc would be good to get your feedback if you decide to push forward. We've had several customers use previous versions AA4AM in GCC, but the introduction of PAC CLI into our pipelines was recent and could possibly have introduced a regression. Happy to work with you if there are issues that come up and ensure that AA4AM will run in GCC.

**Comment by osbornecc** [comment]
Hi @mikefactorial.  I spoke with our development team and we're going to wait until the Power Platform CLI is available for GCC (or a similar fix) before configuring the tool.  I'll try to keep an eye out, but if you hear of any progress please feel free to let me know.

Thank you!

**Comment by mikefactorial** [comment]
Closing this issue as there is nothing further to do here.

**Comment by osbornecc** [comment]
Does this mean it's fully functional in GCC now?  Or are we still in a holding pattern?
Thanks.

**Comment by mikefactorial** [comment]
@osbornecc thanks for following up closed out based on your last comment. Reopening for discussion.

We still haven't tested in GCC at this point. So, can't verify but it would be great if you could help us verify. We are a small team that focuses primarily on commercial customers, but want to support Gov and Sovereign customers as well.

To your original question there should be no reason CoE CLI won't work in GCC and pac-cli is now supported so I don't see any reason not to push forward at this point provide us with feedback and issues run across.

![image](https://user-images.githubusercontent.com/42348035/156657387-227d202a-6221-4feb-acf4-3cd21f0a41cc.png)

**Comment by osbornecc** [comment]
@mikefactorial  Cool, thanks!  I'll have to find time with our development team to try it out.  Feel free to close this again because if something comes up it would warrant a new issue.

**Comment by mikefactorial** [comment]
Perfect. Thanks @osbornecc!
