### ISSUE TITLE
[CoE Starter Kit - BUG] Embedding PowerApps into PBI Template 202110

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#1436]
### Describe the issue

When attempting to update the embedded Power Apps in the Cloud Flow Detail and App Detail reports in the overall Dashboard, things first seemed different when I could click on those tabs in PBI Desktop without seeing the error message that I don't have access to that app.  I ignored that and removed the visual, then added the Power Apps visual back again and selected the right two fields for it.  I've tried on 2 different machines using PBI Desktop Version: 2.99.303.0 64-bit (November 2021) on Windows 11.  Both behaved the exact same way and the Power Apps visual wouldn't return my list of environments or any apps to select.
![image](https://user-images.githubusercontent.com/41799380/140198990-c3f411e6-ea89-4fea-9a98-db5f1fb60325.png)

I tried removing and adding the visual many times on both tabs with the same result every time.  Not sure if it's an issue with PBI Desktop or the template itself, but thought I'd start here.

### Expected Behavior

I expect to see a list of environments in the visual so I can choose the right app from the right environment to make this work.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Dataverse_CoEDashboard_202110

### Steps To Reproduce

Open the Dashboard in PBI Desktop.
Replace the Power Apps Visual.
Select a field or two.
Get the error getting environments.

**Comment by Jenefer-Monroe** [comment]
Can you please see if this repros for your envt outside of our PBI? 
1.	Boot an empty PBI
2.	Enter data
![image](https://user-images.githubusercontent.com/89584709/140232554-9ef80765-b83a-4e6f-9671-49a3b1afb117.png)
3.	Insert the control and select a field for it
![image](https://user-images.githubusercontent.com/89584709/140232576-3ca5127e-8d31-434b-821a-064c97c7b151.png)
4.	Wait a moment. Do they show up? 
![image](https://user-images.githubusercontent.com/89584709/140232606-8617c373-fb7f-4e31-897a-a225dc4d72a6.png)

**Comment by bartsneary** [comment]
Looks like this is an issue for me in PBI Desktop in general.  Thanks for the troubleshooting guidance!  You can close this as a COE Starter Kit issue.  Can you take a peek at the other PBI issue I logged?  It didn't pull up the template correctly, so didn't get assigned.  It's issue #1435

**Comment by Jenefer-Monroe** [comment]
I've duped your bug to #1291. We cannot repro and hence cannot resolve it. But others have listed a way to fix in the notes.

**Comment by Jenefer-Monroe** [comment]
From a colleague: 
`I was able to get the canvas apps working in Power BI Online. Still failing for me from PBI Desktop for some reason. Progress either way!
`
I hope that helps!

**Comment by bartsneary** [comment]
I had done the same thing.  😊  Thanks for sharing.

***@***.***
Bart Sneary (he/him)
Architect & Technology Ethicist | 952-837-4560 W or 507-403-3088 M | ***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.microsoft.com%2fmtc&data=01%7c01%7cjenmoe%40microsoft.com%7cba559a6d6d8544af2e9b08d3386a40e7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=unfjA6YUnXyp8itlgzOIVX%2fbvBKncmBwW6d4D9CANmY%3d>
***@***.***

**Comment by petepuu** [comment]
This issue seems to be related to latest November version of Power BI Desktop. At least September and October versions does not have this issue.
