### ISSUE TITLE
Issue with upgrade of Core Components from 1.89 to 2.0

### ISSUE THREAD

**Issue by jefmeyer** [microsoft/coe-starter-kit#144]
We're receiving an error of: 

Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_409c1, Id: 696e81c1-a969-4e22-bfef-2887b81f54c8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Template v2 (RPA), Id: 86f47022-b7f1-ea11-a815-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

When upgrading the Core Components from 1.89 to 2.0.  Now our environment has 1.89 and 2.0 installed.  The 1.89 version of the solution has an Office 365 Groups and Office 365 Users connection reference, but we're not seeing that in the 2.0 version.

**To Reproduce**
1. Import CoE Core Components 2.0 to an environment running CoE Core Components 1.89 

**Expected behavior**
Core Components should upgrade 1.89 to 2.0

**Comment by devkeydet** [comment]
Hi @Hi @jefmeyer,
Issues in this repo are mostly unattended at the moment. We're in the process of transitioning CoE Starter Kit here, but for the time being would you mind posting this issue to https://github.com/microsoft/powerapps-tools/issues? The team is actively monitoring issues there until we fully move over.
