### ISSUE TITLE
[CoE Starter Kit - BUG] Orphan bot causes flow to fail

### ISSUE THREAD

**Issue by lcimon** [microsoft/coe-starter-kit#1440]
### Describe the issue

Admin | Sync Template v3 (PVA) flows fails to set a bot as orphan. Spotted a case where the `Get Bot Creator` step return a record without `azureactivedirectoryobjectid` field. I suppose because user has left the company.

This `azureactivedirectoryobjectid` field is used later in `Get user profile (V2) New` step to get the owner profile. As this field is null, it fails without returning a status code. 
Here the issue come: without status code, the `Switch 2` step fails also that cause the failure of the flow.

![image](https://user-images.githubusercontent.com/22662809/140340000-dce1f418-561f-4f61-aa70-542a5479deeb.png)

At the end, the current bot isn't marked as Orphaned

### Expected Behavior

Flow should mark the bot as Orphan and continue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### Anything else?

A way to fix it is to update the switch condition as following to avoid the case where no statusCode is returned.

`coalesce(outputs('Get_user_profile_(V2) New')?['statusCode'], '404')`

**Comment by Jenefer-Monroe** [comment]
Can you please open the **_Configure after run_** settings and see what you have there? 
![image](https://user-images.githubusercontent.com/89584709/140402660-5113f815-0a99-4405-bccf-f1dbb870940a.png)

**Comment by lcimon** [comment]
Hi @Jenefer-Monroe,

The _**Configure after run**_ is well set. `Switch 2` step is well executed even when `Get user profile (V2) New` fails.
![image](https://user-images.githubusercontent.com/22662809/140523328-60d0384a-e343-4908-8688-49a8240c7e97.png)

In my case, the `Switch 2` fails because the `statusCode` is null.  And the `statusCode` is empty because when the `Get user profile (V2) New` step run with a null value as upn, it fails without running a request, so no `statusCode`.

This behavior is highlighted in the error message: 
![image](https://user-images.githubusercontent.com/22662809/140531627-ed02a364-6f1d-41b1-b1e9-3331a0e19071.png)

You can reproduce this by creating a simple flow where an empty variable is passed to `Get user profile (V2)` action.

**Comment by Jenefer-Monroe** [comment]
I see. We'll have to do here what we did for MDA as they get their owner id in the same manner
![image](https://user-images.githubusercontent.com/89584709/140543459-1cb25e4c-2c01-4297-96bb-480436862945.png)

**Comment by lcimon** [comment]
Indeed, this an option. 
Let me if you need help to implement it as I will do it for my customer too.

**Comment by Jenefer-Monroe** [comment]
Hello, this is just stamping out an existing solution to another flow, so it shouldnt be difficult. We will attempt to get this in place for Dec release.

**Comment by Jenefer-Monroe** [comment]
local fixed December

**Comment by mikefactorial** [comment]
@lcimon This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
