### ISSUE TITLE
[CoE Starter Kit - Enhacement Request] Environment Governance improvements

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1441]
### Describe the issue

1) Add to PBI all objects, for a single quick view if an environment contains objects
2) Environment Users - ability to see who has access to an environment (at least sys admin, and maybe other SRs)
3) Add to Governance the ability to look for environments that are empty (we do something similar for teams now) and ask if people are still using.

Heard this from a few customers, adding to backlog to track? 
Thoughts from you other folks? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

all

**Comment by manuelap-msft** [comment]
addressed with the new Power Platform Governance dashboard.
