### ISSUE TITLE
[CoE Starter Kit - BUG] Store dataverse tables per environment

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1445]
### Describe the issue

Request from customer, looking for feedback from others. 

- Store the dataverse tables that are in an environment
- All custom tables and non-empty built ins
- Store the number of rows in each table
- Then we can attempt to use object metadata to link as well (canvas app 1 uses custom tables 1,2,3) 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

missing

**Comment by jukkan** [comment]
This would be very interesting information for analysis purposes, that's for sure. However, even a blank Dataverse environment without any custom tables or Dynamics 365 features will have over 700 tables, pure system configuration data. Some kind of filtering would be needed for not overloading the CoE database and also the sync flows with all of this. 

I'm kind of thinking that this would be more suitable for being collected the same way as the new telemetry data in the product can now be [pushed to Azure Data Lake](https://docs.microsoft.com/en-us/power-platform/admin/self-service-analytics) for analysis purposes. Sure, I'd _love_ to have this trend information available, but just not sure if it should rather be a product feature than a CoE Starter Kit feature.

**Comment by Jenefer-Monroe** [comment]
Interest is not very high, per the reasons stated above likely :) Moving from bug to backlog.
