### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor not picking up apps or flows to analyze

### ISSUE THREAD

**Issue by tommortimer21** [microsoft/coe-starter-kit#1446]
### Describe the issue

In the app 'DLP Policy Editor v2' no apps are analysed under the section 'Preview impact of DLP changes'. All environments are selected but the scan of apps does not start. It just stays on 0.

### Expected Behavior

The DLP Policy App should scan all PowerApps in the selected environments to preview the impact of changes to the DLP policy

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

1. Run DLP Editor App
2. Add all environments
3. Move onto step 'Preview impact'

Scanned apps shows '0'

**Comment by manuelap-msft** [comment]
Hello,

have you turned on all the sync flows to sync inventory into the CoE tables? Can you open the Power Platform Admin View (model driven app part of the CoE Kit) and check if apps and flows show up there?

Thank you
Manuela

**Comment by tommortimer21** [comment]
Hi Manuela

Thanks for the response.

You were correct, in that the CLEANUP – Admin Sync Template v3 app was failing to run.

I will fix this

Thanks!


Regards
Tom Mortimer
Mobile +44 7734 769 411
Telephone +44 113 307 3116
***@***.***

**Comment by manuelap-msft** [comment]
Thank you, please let us know if you need any help fixing issues with the sync flows!

The way the CoE Starter kit works is that we have sync flows that crawl your tenant to find information about apps and flows in all the environments, and we store meta-data about those apps and flows in tables in the CoE starter kit solution (e.g. PowerApps App table and Flow table) and the DLP Editor picks up apps and flows from those tables, and not directly from your environments. So if the sync flows fail, those tables may have incomplete data and then the DLP editor would not pick up the apps correctly!

**Comment by tommortimer21** [comment]
I will, you have been most helpful.

Regards
Tom Mortimer
Mobile +44 7734 769 411
Telephone +44 113 307 3116
***@***.***

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for toolkit team at this time. But if new issues arise please feel free to post!
