### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor incorrect navigation

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1447]
### Describe the issue

Via MVP channel:

…If you navigate through the left options, instead of clicking “Next” + you are switching between one policy and another (just by clicking “DLP policies” and choosing a different one from the list), some weird behaviors happen. For example, the impact analysis still shows results from previous run (from the other policy).

![image](https://user-images.githubusercontent.com/55705669/140733932-8d25bb37-0460-42b4-9b52-44394537ad5d.png)

 

This is weird of course, but something that scared me was after saving the second policy, it took the name of the other one, so I ended up with two policies with the same name. Luckily, it didn’t mess up the connectors, but I got shocked for a moment.

 

I’d suggest you can go through some further QA. Especially with these apps that we hang over to IT admins to let them govern the Power Platform.

### Expected Behavior

Navigation works both via left hand panel as well as via Next

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

latest

### What app or flow are you having the issue with?

DLP Editor

**Comment by manuelap-msft** [comment]
Removed the navigation option and the bar on the side is just to show you where you are in the progress. The Next button does quite a lot of work based on what's happened on the screen, so it didn't make sense to put that in the right navigation as people may miss steps on the main page for it. 

Fixed locally, rolling out in January.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
