### ISSUE TITLE
[CoE Starter Kit - BUG] List rows from Dataverse

### ISSUE THREAD

**Issue by LukasKo999** [microsoft/coe-starter-kit#1449]
### Describe the issue

There is extra Action after terminate List Accounts from Dataverse. No idea why.

### Expected Behavior

The List rows from Dataverse action is not necessary, maybe somebody forgot about it. please remove it.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Steps To Reproduce

Open flow detail and scroll down to last action.

### Anything else?

![image](https://user-images.githubusercontent.com/93936147/140782058-b98227c7-8559-4394-b92f-06ca0f44036d.png)

**Comment by Jenefer-Monroe** [comment]
Hello we don't see this locally, here is what this scope looks like:
![image](https://user-images.githubusercontent.com/89584709/140804048-a8f82eb2-3614-43bf-a9f5-c7ecf1c45b60.png)

Please make sure you don't have unmanaged layers on the flow. See [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) for details.

**Comment by LukasKo999** [comment]
that is weird, there is no unmanaged layer but still can see the List rows action

![image](https://user-images.githubusercontent.com/93936147/140875909-2ad83df1-1887-4ff0-8d9c-0b0844525f8a.png)


![image](https://user-images.githubusercontent.com/93936147/140875893-4de632f4-97df-4003-be7a-e7576b55f4be.png)

**Comment by Jenefer-Monroe** [comment]
Curious. Do you see multiple instances of the solution installed? I wonder if some upgrade failure hit you.

**Comment by Jenefer-Monroe** [comment]
closign out as no further action for toolkit team
