### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by dknamo** [microsoft/coe-starter-kit#1451]
### Describe the issue

Hi,
in Power Platform COE Admin View, we cannot see the new Flows and apps. Data is not updated correctly.
We updated the COE Kit in early September.

![2021-11-09 10_43_05-Flows Active Flows - Power Apps](https://user-images.githubusercontent.com/72252442/140900628-58baf2d6-4c24-460f-adc1-4188540e76a5.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

Power Platform COE Admin View-Audit logs

**Comment by Jenefer-Monroe** [comment]
Hello. Can you please confirm that you have completed the [Set up of Core](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) such that the inventory flows are running and passing?  

For example, do you have data in the inventory tables? (ex Environments, PowerApps Apps, Flows, ...)
![image](https://user-images.githubusercontent.com/89584709/140920103-39522ff2-b881-4c73-9e61-1f0b67e9de7b.png)

And are the sync flows turned on, running, and passing? (ex titles include Admin | Sync Template v3)
![image](https://user-images.githubusercontent.com/89584709/140920419-3bcc924f-a818-4fda-af6e-46371bb4687e.png)

**Comment by dknamo** [comment]
Hi Jenefer ,thanks for your reply I think we found out why it does not work.
Someone had changed the DLP policy for the COE environment and the flows were not running properly
/Nargess

**Comment by Jenefer-Monroe** [comment]
thanks for letting me know, I will go ahead and close this then. thanks for using CoE!
