### ISSUE TITLE
Enhance Power Bi Report - Flow Adoption Page

### ISSUE THREAD

**Issue by morismm99** [microsoft/coe-starter-kit#1452]
Currently, the Flow License Assessment only allows you to see a break down of flow based on connectors/owner.

Could we look into a way to identify whether a flow is standard/premium based on connector being used?

I can manually get this data as needed, but that involves sorting/filtering by the connectors I know are premium...which takes time.

Currently running the October CoE starter kit release.

**Comment by manuelap-msft** [comment]
Hello,

on the left hand decomposition tree, you should be able to drill down based on connector tier, connector name and department and drill further from your initial selection. You could select Connector Tier > Premium > then look at Connector Names in the premium bucket:

Connector tier:
![image](https://user-images.githubusercontent.com/55705669/140997719-bf1489ab-3708-42be-8424-4111db5dcf27.png)

Premium tier > Connector names:
![image](https://user-images.githubusercontent.com/55705669/140997879-20177e96-0bef-4a11-b5fa-90aa302c85f3.png)

Is this the report that you'd like or did I misunderstand?

**Comment by morismm99** [comment]
Well…I feel dumb now. It’s there! The connector tier was just hidden. Thus, I’ll tweak it, have it shown by default and that should do!

Thanks @manuelap-msft!

Best,

Moris

**Comment by morismm99** [comment]
Well...one more thing...reason I brought this up was because someone from our Software Asset Management team was looking into the report, specifically the Power Apps Adoption tab. So, I pointed them to the Flow License Assessment tab. Any plan to do a Power Automate adoption page similar to the Power Apps Adoption tab? For this month, I went ahead and added some static cards to that Flow License Assessment page, but I try to avoid customizing the report...as the more customizations I do, the more complex the monthly upgrades get when I load the new Power Bi report template.

![image](https://user-images.githubusercontent.com/72099434/141023328-8f19f7fd-b9bb-444d-be81-3fe51f8a5f2e.png)

**Comment by manuelap-msft** [comment]
Never apologize, if it's not obvious then it's probably bad design on our side! We'll review - we may be able to ship the decomposition tree expanded. 

That's a great idea, I'll see if we can add a Flow Adoption page for the December release - one reason we haven't so far is that we don't have Flow usage data as part of the CoE Kit. But we can still have some visuals like the ones you highlighted. I'll put that on our backlog!

**Comment by mikefactorial** [comment]
@morismm99 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
