### ISSUE TITLE
Does coe provide API endpoint? 

### ISSUE THREAD

**Issue by kongmengfei** [microsoft/coe-starter-kit#1453]
Just read coe documents, it seems that coe solution provides a lot of connectors but can we directly access the data/achieve the same goal via API instead of using a connector?

For example, I am trying to [Get Apps as Admin](https://docs.microsoft.com/en-us/connectors/powerappsforadmins/#get-apps-as-admin) through my own web app. is that possible?

Thanks

**Comment by manuelap-msft** [comment]
There are limited APIs available that are supported, see: https://docs.microsoft.com/en-us/power-platform/admin/powerplatform-api-getting-started - I believe there are plans to grow this further, but at the moment it's limited. 

As this is not directly related to CoE Starter Kit functionality but instead a Product question, I would recommend you post this in the Power Users community to get input from others: https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1

Thank you
Manuela
