### ISSUE TITLE
[CoE Starter Kit - BUG] Admin - Access this App is not working

### ISSUE THREAD

**Issue by ZTAdminD365** [microsoft/coe-starter-kit#1454]
### Describe the issue

Admin - Access this App is showing empty screen as shown in below snapshot.

![image](https://user-images.githubusercontent.com/93531026/141086024-676c96c0-663e-4086-aed5-0e6ba382f606.png)

We can see the runtime error message in the App designer view as shown in below snapshot.
![image](https://user-images.githubusercontent.com/93531026/141087846-2e090efb-9472-4fa3-9d0a-fdaad5719f68.png)

Any resolution on the above issue.

Thanks in Advance!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

NA

**Comment by Jenefer-Monroe** [comment]
this is not a standalone app, it is intended to be used embedded in the Power Bi. Please see https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
