### ISSUE TITLE
COE toolkit issue - Environment Request Center App

### ISSUE THREAD

**Issue by Sandhyaraniguriv** [microsoft/coe-starter-kit#1455]
### Describe the issue

 I have observed 9 issues with respect to Request center app in the COE toolkit. 
I have attached all 9 issues in the document. 
Please provdie solution for the same [
[Product Defects by status(Pending rejected approved live and cancelled) for RCA (003).docx](https://github.com/microsoft/coe-starter-kit/files/7513178/Product.Defects.by.status.Pending.rejected.approved.live.and.cancelled.for.RCA.003.docx)
](url)

### Expected Behavior

Microsoft COE - contact person needs to connect and resolve the issues I have raised. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Request centre App

### Steps To Reproduce

Mentioned in the document attached

**Comment by Jenefer-Monroe** [comment]
Assigned to area owner

**Comment by Sandhyaraniguriv** [comment]
Hello Team,

Can you please update on this ticket. It's been raised since last week and no response. Please call me on teams to check more details on the issues raised and added in the word document with this ticket.

Thanks,
Sandhya

**Comment by Jenefer-Monroe** [comment]
Hello, to set expectations, the starter kit is not a Microsoft product and is therefore not supported, and has no SLAs. We cannot work with GitHub customers either. 
Please see our [Disclaminer](https://docs.microsoft.com/power-platform/guidance/coe/overview#disclaimer)

**Comment by Sandhyaraniguriv** [comment]
Hello, 
what does this mean? I raised tickets on the same issue on 2nd Nov and the same was with Mindtree Vendor(Sumanth and Shwetha Jadav <v-sjadav@microsoftsupport.com>. Both of them closed the below tickets saying that you would be helping in resolving these issues. If you don't support who will support and where do I need to raise the tickets.

Please find the tickets raised on the issues mentioned in this tickets in word document.
Service Request 2111030060002331
support request 2111020060002325 

Let us know whom should we approach or we need to escalate it to someone.  I am from Power Objects(HCL) and we need to support a customer with the new feature MS added in the Oct release COE tool kit.

Thanks,
Sandhya

**Comment by Jenefer-Monroe** [comment]
That CoE Starter Kit is not a supported set of functionality, its just a set of free tools to get you started. 
This is the correct place to post issues, and we do our best to keep up with customers, but there is no SLA. 
I have sent your issue to the area owner and they will respond if they have questions or if they are able to resolve.

**Comment by denisem-msft** [comment]
Hi @Sandhyaraniguriv - thanks for your feedback! I have addressed each itemized issue in the attached document. Some of the issues were valid and have been fixed in the upcoming release, and others need more information from you - please respond to those issues. 

[GitHub_COE_1455-IssueTracking.docx](https://github.com/microsoft/coe-starter-kit/files/7821104/GitHub_COE_1455-IssueTracking.docx)

**Comment by manuelap-msft** [comment]
Closing as this has been fixed with the January release. If you continue to see issues, please raise each one as an individual issue so it's easier for us to track!
