### ISSUE TITLE
[ALM Accelerator - BUG]: SharePoint Datasource Environment Variables does not show correct list of sites

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#1460]
### Describe the issue

When configuring a SharePoint datasource environment variable via the Deployment Settings UI the list of sites is different than when configuring the environment variable via the maker portal.

Result is that I cannot select the correct site when configuring the environment variable for downstream environments

### Expected Behavior

List of available sites should be same as when configuring the environment variable via the maker portal

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20211001.1

### Steps To Reproduce

1. Open deployment configuration for a solution that includes a SharePoint datasource environment variable.
2. Compare the list of available sites with the list of available sites when configuring the same environment variable via the Maker Portal.

**Comment by mikefactorial** [comment]
More details on this issue in #2041

**Comment by mikefactorial** [comment]
@jenschristianschroder closing this out and referencing in #2125
