### ISSUE TITLE
[CoE Starter Kit - BUG] Flows not installing

### ISSUE THREAD

**Issue by PlanetDomino** [microsoft/coe-starter-kit#1461]
### Describe the issue

I downloaded the CoE from github.  I'm trying to install --> CenterofExcellenceCoreComponents_1_98_managed (1) in my DEV tenant.  I have verified that I am a Power Platform Admin and I have a "per user" Power Apps license.  i import the solution and everything appears to install EXCEPT the 14 flows.  i have de-installed the solution and re-imported.  still everything loads -- power apps canvas, power apps model, dataverse tables, etc -- just not the flows.

i contacted MS Support and they told me to run the 1st flow (per the MS documentation), but to run it from the existing Default solution.  it ran for about 45 minutes and then i got the following error --> Action 'Get_this_envs_PVAs_from_bots' failed

### Expected Behavior

i expect that when i import the solution that 14 flows will be present.  but they are missing.  the BPF flows are present.  the canvas apps are present.  the model drive app is present.  the dataverse tables are presnt.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.98

### What app or flow are you having the issue with?

Admin - Synch v3

### Steps To Reproduce

it is listed up above in the description.

### Anything else?

i'm confused as to why the flows are missing, however, if i go into the "Default Solution" then i see the 14 flows and i can "turn on" one of them.

**Comment by PlanetDomino** [comment]
Jenefer,

WOW !!!  thanks for the super-fast response.

At this point, I agree that I just need to start from scratch.  I’ve loaded, un-installed, loaded, un-installed, and then loaded again.

One thing, just as an FYI, that I noticed is that when I loaded the 2nd and 3rd times, I WAS NEVER asked for the connection credentials; you know the 20-22 connections that are required.  I was asked only the 1st time, so I can only infer that those connections were not de-installed when I un-installed the CoE.

And I will follow your instructions, down below.  I should be able to start later this afternoon.

Thank you for your assistance in this matter.

----------------------------------------------------
Richard Gutierrez
Senior Infrastructure Services Delivery Analyst
Information Technology - Operations
Blue Cross and Blue Shield Plans in Illinois, Montana, New Mexico, Oklahoma and Texas
Office Phone: 972.766.3295
Mobile Phone: 972.689.2061
mailto: ***@***.******@***.***>

[Ambassador E-mail signature_resized_too small]

**Comment by Jenefer-Monroe** [comment]
haha... I'm glad to help. 

And you are correct, that existing environment had the connections after the first install, so subsequent installs just picked them for you. You will need to create them again in the new environment.

**Comment by PlanetDomino** [comment]
Jenefer,

I removed the prior installation, per your recommendation; but I noticed something strange, and wanted to get your input before proceeding.

On my initial attempt to load the CoE, I used our DEV tenant (we have 2 tenants, DEV and PROD), however, since it was my 1st attempt when creating the environment, I selected the “Sandbox” option (as opposed to PRODUCTION).  So, does that really matter?

Yesterday I attempted to re-install the latest/greatest CoE, but this time I selected PRODUCTION, and got an error stating there was not enough available DASD for the dataverse table.  I am working with my counterpart SMEs to get more DASD in our DEV tenant, but do you think it’s ok to proceed using the “Sandbox” option.  And yes, I know it’s valid for only 30 days, but I contacted MS and they said all I need to do is open a premier support ticket and they will renew for as long as I need.

Please advise.

Thanks.
----------------------------------------------------
Richard Gutierrez
Senior Infrastructure Services Delivery Analyst
Information Technology - Operations
Blue Cross and Blue Shield Plans in Illinois, Montana, New Mexico, Oklahoma and Texas
Office Phone: 972.766.3295
Mobile Phone: 972.689.2061
mailto: ***@***.******@***.***>

[Ambassador E-mail signature_resized_too small]
