### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by johannigman** [microsoft/coe-starter-kit#1464]
### Describe the issue

When the "Admin | Sync Template v3 (Desktop flows)" flow is triggered to run when it gets to the step to read the workflows table form the dataverse environment it errors out with the following error:

Http request failed as there is an error: 'Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'.

There are only 141 records that would be returned, but it's somehow returning over 100MB of data, which is higher than the allowed limit.  It looks like the bulk of data being returned is possibly in the clientdata field

If I connect directly to the dataverse database through SSMS and run the following query

select clientdata
FROM [dbo].[workflow]
where category=6 and uiflowtype != 101

It returns the following error

Msg 40000, Level 16, State 1, Line 105
Return records size cannot exceed 83886080. Make sure to filter result set to tailor it to your report.
RequestId: TDS;427c24e7-62be-46de-beb1-b1b348acc353;77
Time: 2021-11-10T19:56:41.8648075Z

Would seem like there's a lot of data stored in this field that may not even be needed by the flow that could be eliminated.

### Expected Behavior

Would expect the flow to run successfully and load the desktop flows information into the rpa_admin table in the COE environment's dataverse database

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

### Steps To Reproduce

1.) Make change to environment in question to trigger "Admin | Sync Template v3 (Desktop flows)" flow to run
2.) Review flow run and see that it errored out 
![image](https://user-images.githubusercontent.com/8153751/141182920-d821285c-8462-4dc6-a27f-24206614a886.png)

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately we have to use the legacy Dataverse connector to get to these tables today because the new Dataverse connector only support current environment. However the legacy Dataverse connector does not support selecting individual columns. 

This is a product limitation that will be fixed when the new Dataverse connector allows us to select environments.

Unfortunately for now, this is just a whole in the toolkit capability.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
