### ISSUE TITLE
ALM Accelerator for Advanced Makers unable to update the configuration settings from Canvas App

### ISSUE THREAD

**Issue by ServiceAdmin365** [microsoft/coe-starter-kit#1469]
### Describe the issue

I have set the test and prod pipelines and provided the connection reference, environment variables and component owner values are not updated in the deployed environments(qa and prod).
I can see the config folder,
![image](https://user-images.githubusercontent.com/92145363/141262761-453642c7-88f9-4060-82eb-bf375a52cb2c.png)
 Test pipeline has variables,

![image](https://user-images.githubusercontent.com/92145363/141263152-e33d933f-f3f9-4734-97f8-7516d377a8c9.png)

Solution deployed in QA and connection reference is not set also the environmentvariables.

### Expected Behavior

Updated connection references and environment variables in the deploying environments

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20211001.1

### Steps To Reproduce

Retried the pipelines again to check the deployments

**Comment by mikefactorial** [comment]
@ServiceAdmin365 a couple of things to check here.
1. Are you seeing values passed in to the Data variable in the export pipeline for example:
![image](https://user-images.githubusercontent.com/42348035/141825191-d37e10b4-cc57-4868-a96f-aadbeb4917b3.png)
2. Is there a Power Platform Service Connection registered for the environment in which the ALM Accelerator is installed?
3. What does the output look like for the Update Deployment Settings task in the export pipeline (e.g. any errors or messages)?

**Comment by ServiceAdmin365** [comment]
1 . I can see the value against Data variable same as given image.
2. Service connection is required to PP (Dev,test,prod) environments? 
I have installed the aa4am in separate environment.
Please suggest do I have to create one more for coe environment ?

**Comment by ServiceAdmin365** [comment]
I am able to deploy with environment variables and connections. But the owner of the app and other components will app user(service principal). It's better to choose the owner of the components and sharing app with individual users.
