### ISSUE TITLE
Failed to deleted object that have been approved for deletion 

### ISSUE THREAD

**Issue by EmranCoE** [microsoft/coe-starter-kit#1471]
### Describe the issue

Hi ,

This "Clean up and delete" component was working fine earlier , noticed that last few days , those apps/fows have got Approval for deletion process that action failed for last 3 days. We have got several hundred (app/flows ) approve for delete , does the issue for large number of approve in same time  or others reasons !

Many Thanks 

![Cleanup_delete](https://user-images.githubusercontent.com/90054514/141275672-52d0e62e-2d99-4ddd-b846-ee78c8663390.png)

![Github_](https://user-images.githubusercontent.com/90054514/141275745-e2bdd18f-f5e3-40c5-b42f-f779b9533868.png)
![App_delete](https://user-images.githubusercontent.com/90054514/141275802-436790dd-545b-4555-bfdc-b0ea49c8b0d7.png)
![Flow_delete](https://user-images.githubusercontent.com/90054514/141275843-56908453-3dea-4114-8d74-5183e43b01d5.png)
![Apps_flows](https://user-images.githubusercontent.com/90054514/141275875-19260b6e-803c-4575-871b-3809fb0214aa.png)

Environment Variables: 

![InkedAuto-delArchive_LI](https://user-images.githubusercontent.com/90054514/141276067-d11efca1-0c9a-44c5-ac3e-49ca6584945a.jpg)
![Inkeddelete-from-CoE _LI](https://user-images.githubusercontent.com/90054514/141276101-7faf328a-90d3-4854-851f-9a7a2d54e523.jpg)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Clean Up and Delete)

**Comment by Jenefer-Monroe** [comment]
Hello, you appear to be on an old version of Governance, we now use the following to delete flows and it works for admins even if they dont have access to the flow, so the old check perms stuff is gone now. 
![image](https://user-images.githubusercontent.com/89584709/141315925-062985ef-95f9-4fe6-88fc-487f48e72a89.png)

Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by EmranCoE** [comment]
Hey Jenefer,

Thank you so much, I always appreciate your quick help very much.
After  upgrade, hope the deletion process will continue from those are waiting to be delete in  (apps/flows already  approve  and saved in Archive Approval Table ) database .
Just for sure, If I am doing the correct update process >> after removed all the unmanaged layer from apps/flows >> import the solution>> and select upgrade

![Upgrade](https://user-images.githubusercontent.com/90054514/141475274-dfcc9557-f208-427f-ac66-66d00e851681.jpg)
 
Do I need to follow any order / or in solution  >>switch to classic 
1.	Upgrade Nurture
2.	Upgrade Gov
3.	Update Audit Logs
4.	Then upgrade Core

Regards,
Emran

**Comment by Jenefer-Monroe** [comment]
What version of Core do you currently have? We did have a bug a while back which caused issues with upgrade.

**Comment by EmranCoE** [comment]
Okay , We have Core Version 2.1.70

![Solution_Version](https://user-images.githubusercontent.com/90054514/141487008-edbb80ea-4599-4383-add0-ee3a80820d8e.jpg)

**Comment by Jenefer-Monroe** [comment]
I think we had it fixed already by then, can you go and see if there are unmanaged layers to remove? That might fix it for you without any other work, and its needed for upgrade anyway.

**Comment by EmranCoE** [comment]
Yeah , there were unmanaged layers , I removed all before do the upgrade .
Upgrades looks ok , with all the new version from november .

![Upgrade-November](https://user-images.githubusercontent.com/90054514/141694995-cc4bcc2a-c8fb-44f5-a0a5-e8660f397340.jpg)

But still the issues after upgraded , deletion process not getting success .  

- Canvas App Action failed 

![Error_CanvasApp](https://user-images.githubusercontent.com/90054514/141695336-8e4cfc84-1b85-40ef-bccc-f6164f22ff92.png)

![Error_CanvasApp](https://user-images.githubusercontent.com/90054514/141695363-e7ce4072-eb5b-4d41-a35a-b80591f718a3.png)

![Error_1](https://user-images.githubusercontent.com/90054514/141695375-6e4eac85-f88f-46ad-98a0-6d7c0234538c.png)

**Comment by Jenefer-Monroe** [comment]
Can you please share the output at this failure?

**Comment by EmranCoE** [comment]
Here is the output , or you mean the OUTPUTS >> click to download >> get the code !

![Output_](https://user-images.githubusercontent.com/90054514/141702392-0da014b3-6a94-4471-a47b-41d0b86118bd.jpg)

**Comment by EmranCoE** [comment]
Hey Jenefer , 
Just want to share, tried these  >>  I have removed that app  ( from Power Platform Admin view App) in above screen  there it was stop , also removed that approval record from Archive Approval Table.
And run the flows, it runs successfully and deleted about 20 apps and 30 flows, hope it will keep continue.

**Comment by EmranCoE** [comment]
I have two questions about the new version:

- To change the owner for flows in solution using “Set Flow Permission” App.

But it’s still the same flows in solutions cannot change the owners!
[Flows in solutions can only be deleted or assigned new owners. They can not have their permission types edited programmatically ]
showing this error when trying --
![Flow-Permission](https://user-images.githubusercontent.com/90054514/141955648-2e2007b7-9236-497e-af9b-9fabcbf3bb68.png)

- Also did not see that environment variable in new version “**Exclude Teams Environment from Compliance** “  in order to exclude Teams from developer compliance center .

**Comment by Jenefer-Monroe** [comment]
It looks like your issue is now resolved for which this bug was posted. Please post separate issues for additional bugs. 
Thanks for using CoE!
