### ISSUE TITLE
[CoE Starter Kit - BUG] Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade

### ISSUE THREAD

**Issue by silvafr1** [microsoft/coe-starter-kit#1472]
### Describe the issue

I´m not able to upgrade Core component Solution with November Version, my previous version is from August - 2.2.20210707.3
On the log is this description: 

Failure | 0x80048539 | Solution manifest   import: FAILURE: Holding solution CenterofExcellenceCoreComponents_Upgrade   already exists.

### Expected Behavior

Upgrade successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

solution itself

### Steps To Reproduce

Upgrade Solution

### Anything else?

On the log is this description: 
Failure | 0x80048539 | Solution manifest   import: FAILURE: Holding solution CenterofExcellenceCoreComponents_Upgrade   already exists.

**Comment by silvafr1** [comment]
Hello,
I´ve started the Upgrade from "Core Components" solution, show I use a different upgrade order?
Thank you.
Regards

**Comment by Jenefer-Monroe** [comment]
Can you please try an overwrite upgrade in the classic UX?  

Solution > Switch to Classic (note you may have to turn off the new solution experience toggle)  
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png) 

Click Import (fourth from the left)  
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png) 

Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import  
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png) 
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by silvafr1** [comment]
Hello,
Thank you its solved.
Best regards
