### ISSUE TITLE
DLP Editor V2 - Limited Results

### ISSUE THREAD

**Issue by tommortimer21** [microsoft/coe-starter-kit#1473]
On the DLP Editor 'Impact Analysis' it says Analysed Apps 139, and Analyzed Flows 206 with all environments added. However we have significantly more apps and flows across all our environments. 

I thought 'Analysed apps' and 'analysed flows' might the the total number of Flows with issues, however I can only preview 25 of them on the 'impact analysis' screen.

So i'm not sure if the issue is that the tool is not scanning all the apps, or whether it's not displaying all the results to scroll through.

Which App/Flow in the backend of CofE do I need to run to refresh the list of apps/flows/connectors?

**Comment by manuelap-msft** [comment]
To avoid delegation issues, we store a comma-seperated list of all connectors an app uses in a field called App Connections
![image](https://user-images.githubusercontent.com/55705669/141326218-1536d093-6106-4d08-aab8-23d4b79a8ac6.png)

Can you check if all your apps have that set? It's something that we introduced a few releases ago, and it's possible you will need to run a full inventory check to update the App Connections column.

The easiest way to check that is to go to the Core solution > looking at the PowerApps App table > export the data to Excel and see if the App Connections shows blank for many apps. 

Once you have done that let me know your findings and if a full inventory run is required, we'll guide you through how to do that!

**Comment by tommortimer21** [comment]
The admin_appconnections column in that table has missing data for lots of Apps, so yes I would say a full inventory re run is required.

Will this cover Apps and Flows?

How do I do this?

Regards
Tom Mortimer
Telephone +44 113 307 3116
***@***.***

**Comment by manuelap-msft** [comment]
Yes, it's the same for Flows and Apps!

Ok, to run a full inventory please follow the below steps:

1. Set the value of the **Full inventory** environment variable to Yes (Learn more: update environment variables).
2. Turn off the Admin | Sync Template v3 (Apps) and Admin | Sync Template v3 (Flows) in the Core solution and then turn them straight back on. Flows that are on don't pick new environment variable values due to some caching issue, so that's why you have to toggle them on/off.
3. Run the Admin | Sync Template v3 flow.
4. I would wait for all the flows to finish running, and then set the Full inventory environment variable back to No.
5. Turn the flows in Core off and back on.

**Comment by tommortimer21** [comment]
I’ve done most of the steps, but just to be clear for step 5, which Flows specifically am I turning off and back on?



Regards
Tom Mortimer
Telephone +44 113 307 3116
***@***.***

**Comment by manuelap-msft** [comment]
You would turn back on and off the  Admin | Sync Template v3 (Apps) and Admin | Sync Template v3 (Flows) flows!

**Comment by tommortimer21** [comment]
Thanks, I’ll do what you’ve explained and hopefully then the DLP Editor will list all of our apps!

Last query – is there a way to export the results of the DLP policy preview to Excel, so we can see in an Excel document which apps/flows would be affected by a change?

Regards
Tom Mortimer
Telephone +44 113 307 3116
***@***.***

**Comment by manuelap-msft** [comment]
There isn't a way to export at the moment, but we've had another ask for this as well so we are investigating how we can make this possible!

**Comment by tommortimer21** [comment]
It’s looking at more apps now. Is the Analysed Apps/Flows the actual impacted Apps/Flows, or just the Apps/Flows it has scanned though?

Just need to be clear whether it’s looked at 874 apps or found 874 apps that would be impacted by a change to the policy.

Difficult to count the exact number in the list by just scrolling down

***@***.***

Regards
Tom Mortimer
Telephone +44 113 307 3116
***@***.***

**Comment by manuelap-msft** [comment]
Great! It's analysed apps - Collect and Count in Power Apps are [non-delegable function](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/delegation-overview) so we can't list impacted apps unfortunately as some tenants may have more than 2000 impacted apps. So it only shows you the ones that it scanned through!

**Comment by tommortimer21** [comment]
That makes sense. So to be clear, we can’t see a number of impact apps/flow – just the list of impacted apps/flows to scroll through on the DLP Editor App?

Regards
Tom Mortimer
Telephone +44 113 307 3116
***@***.***

**Comment by manuelap-msft** [comment]
That's correct, yes! We are looking at a way to export the impacted list to Excel or similar for you to be able to count the impacted apps there but that's still under investigation. At the moment, you can only scroll through them.

**Comment by tommortimer21** [comment]
Thanks. In that case I have the help I needed, so thank you

Regards
Tom Mortimer
Telephone +44 113 307 3116
***@***.***

**Comment by manuelap-msft** [comment]
Awesome, thank you - I'll go ahead and close this issue now but please do let us know if you experience any further issues and we'll look into it! Thank you for using the CoE!
