### ISSUE TITLE
[CoE Starter Kit - Idea] Use Environment variable for logo used in e-mails

### ISSUE THREAD

**Issue by poppynka** [microsoft/coe-starter-kit#1477]
Hi, 
my idea is about customer branding the e-mails. We are currently used October release and plan to do next upgrade probably in January.

**Is your feature request related to a problem? Please describe.**
I am currently asked to put customer's logo to all e-mail communication that goes towards our users. I can see the e.g. _Admin | Archive and Clean Up v2 (Start Approval for Apps)_ uses local variable where Microsoft logo is hard coded. Now I need to make a customization (and potentially maintain it with next upgrades), just to replace the value with link to our logo. 
![image](https://user-images.githubusercontent.com/6829792/141784401-b69b3b86-b32e-47f4-a750-2184abbef891.png)

**Describe the solution you'd like**
My proposed solution would be to add an environment variable to the logo used in e-mails, so I would just create custom value and it would be used in e-mails instead the Microsoft one. Who doesn't care for the logo, he can keep the default Microsoft (which is now hard coded)

**Additional context**
The flow mentioned above was just an example. I need to customize basically all Governance flows that send message to makers and managers.

I wish you a nice rest of the day and thanks for considering the idea :)

**Comment by Jenefer-Monroe** [comment]
This is a good idea. And I happen to be re-writing some of our email stuff for Dec. 
Will explore.

**Comment by poppynka** [comment]
Thanks :) 

I am also asked to customize and brand these, because they don't have logo and people might think it's spam or phishing
- Admin | Email Managers Ignored Approvals - mail sent to managers 
- Admin | Archive and Clean Up v2 (Clean Up and Delete), mail asking makers to delete flow manually if it's in the solution.

Maybe I could post it as separate idea :)

**Comment by poppynka** [comment]
oh, wow 😸 that sounds interesting! I look forward to that 👍

**Comment by Jenefer-Monroe** [comment]
what I've done is added this logo to the existing **_eMail Header Style_** environment variable. So this will benefit you in Nov release before we get to stamping out this helper-flow work into Gov

**Comment by mikefactorial** [comment]
@poppynka This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by poppynka** [comment]
@Jenefer-Monroe thanks! ❤️
