### ISSUE TITLE
 Cloud flow runs capture

### ISSUE THREAD

**Issue by AravindSivanantham** [microsoft/coe-starter-kit#1482]
Hi Team,

Appreciated, is there any feature upgrade in CoE to capture Cloud Flow Run History to generate reports using PowerBI dashboard.

Regards
Aravind Sivanantham

**Comment by manuelap-msft** [comment]
Monitoring cloud flow runs is currently not included in the CoE Starter Kit, as this information is not available via APIs or the Office 365 Audit Log. The CoE Starter Kit can only use what's available in the product.

**Comment by AravindSivanantham** [comment]
Please let us know the tentative time by when the cloud flow runs included in CoE Starter kit Components.

**Comment by manuelap-msft** [comment]
Cloud flow run history is not available in the product. Hence it's also not available in the CoE Kit. There is no timeframe to address this.
