### ISSUE TITLE
I'm trying to upgrade from CoE v2.2.20to the latest 3.18 - Error 

### ISSUE THREAD

**Issue by gabrielvillayzanbcp** [microsoft/coe-starter-kit#1483]
Hi, 
When I try to upgrade/update/upgrade-override the CoE 2.2.20 to 3.18, I still get this error:
Error code: 80072352
Exception message: CanvasApp import: FAILURE: Code: ApplicationIdAlreadyInUse Message: The application name '90ddb448-a721-453e-bf6a-fea0dd2c7dc7' in tenant 'my tenant' is already in use. Please specify a different name. 

NOTE: I also tried to find that App ID but I did not find it.

please help with this error.

Gabriel Villayzan

**Comment by Jenefer-Monroe** [comment]
Can you please try an overwrite upgrade in the classic UX?  

  

Solution > Switch to Classic (note this can take some time, may have to try twice)  

![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png) 

  

Click Import (fourth from the left)  

![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png) 

  

Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import  

![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png) 

![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by gabrielvillayzanbcp** [comment]
@Jenefer-Monroe I have tried that a couple of times and still getting the same error.

**Comment by Jenefer-Monroe** [comment]
I'm afraid I don't know how to help you upgrade at this point then. What aspects of the toolkit are you using? This would help me know if you could just do a clean install in a new environment.

**Comment by gabrielvillayzanbcp** [comment]
I only have this 2 solutions (Core and audit log) I tried first to upgrade to July version, then I'm trying to October/november version and I can't because of this error.
![image](https://user-images.githubusercontent.com/84060860/142219418-5379351f-3645-455a-b160-a0b5da422278.png)

on the other side, I have data in my Dataverse DB, I would like to do a clean install but keeping my data, I have also many other solutions that read the CoE Dataverse so I prefer if this clean install could be done in the same environment.

**Comment by Jenefer-Monroe** [comment]
ok. I'm afraid I cannot scale to assist then. You can look through the old closed issues around upgrade to see if you can find ideas from others. But I'm not familiar with this error in particular.

**Comment by gabrielvillayzanbcp** [comment]
So what's the suggestion here? do I need to do a fresh CoE installation? if so, is there a way to import my old data?

**Comment by Jenefer-Monroe** [comment]
We do not a way to easily migrate all the data due to some product limitations. I did summarize a technique we used to migrate just inventory and audit logs in #1507
