### ISSUE TITLE
[CoE Starter Kit - BUG] Command Center flow has incorrect filter query for Message Center services

### ISSUE THREAD

**Issue by jukkan** [microsoft/coe-starter-kit#1484]
### Describe the issue

Upon opening the Admin - Command Center app, I see that not all the Power Apps / Automate / BI related messages are retrieved. Viewing the same tenant's Microsoft 365 Message Center shows 8 messages, Command Center app shows only 5:

![image](https://user-images.githubusercontent.com/10254155/141969889-19dd25f9-ff3f-4b06-a8a2-14ff7165743b.png)

Upon closer inspection, it seems like the services name filter used in the flow "Get M365 Service Messages Details" doesn't match with the exact values used in Message Center. I modified the filter query to be as follows, now all the messages show up:

`'Power Apps' in services or 'Microsoft Power Automate' in services or 'Power Apps in Microsoft 365' in services or 'Power Automate in Microsoft 365' in services or 'Power BI' in services`

I guess there's no "contains" filter support for Graph API to pull in automatically the possible new SKU variations that may arrive later on - or at least I couldn't find a way to do it. Would be nice to retrieve everything that says "Power Apps", even if there's future services like "Power Apps in Microsoft Loop" introduced.

### Expected Behavior

Get the same list of Power Platform services related messages in Message Center and Command Center.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Get M365 Service Messages Details

**Comment by Jenefer-Monroe** [comment]
Thanks for the recommended fix! I'll test it out.

**Comment by Jenefer-Monroe** [comment]
seems to work great. Have local fixed for Dec. 
Thanks so much!!!

**Comment by mikefactorial** [comment]
@jukkan This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
