### ISSUE TITLE
November version . Set Flow Permissions does not work for flows in solution

### ISSUE THREAD

**Issue by EmranCoE** [microsoft/coe-starter-kit#1488]
### Describe the issue

Hi ,

We just upgaded the new version( **Core 3.18 , Governance 2.8** )  from november ,  but following two functions are missing .

![Upgrade-November](https://user-images.githubusercontent.com/90054514/142009453-aac9133a-ebf7-4680-ba66-26b560ed1426.jpg)

1. 

Unable to change the owner for flows in solution using “Set Flow Permissions” App .

Still  the same message
[Flows in solutions can only be deleted or assigned new owners. They can not have their permission types edited programmatically ]
showing this error when trying --
![Flow-Permission](https://user-images.githubusercontent.com/90054514/142011179-b2a63add-b941-4be1-ab2b-f4ce93f53118.png)

2. 

Also did not found  that environment variable in new version “**Exclude Teams Environment from Compliance** “ in order to exclude Teams from developer compliance center .

Many Thanks
Emran

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Set Flow Permissions

**Comment by Jenefer-Monroe** [comment]
Hello, this is not an env variable we ever shipped: **_Exclude Teams Environment from Compliance_**
You can excuse individual environments from this in the Power Platform Admin View
![image](https://user-images.githubusercontent.com/89584709/142025803-9153e50e-3efe-4330-bd8e-e76d3a354502.png)

**Comment by EmranCoE** [comment]
Thank you !  Jenefer , 
So , "Excuse from Compliance Flow " in Power Platform Admin View need to do it  for each Teams Environment separately , for example we have more than 200 Teams Environments .
But I have seen earlier few weeks ago in my other computer  while testing Demo CoE Env.
![Teams_](https://user-images.githubusercontent.com/90054514/142032165-b9f4d65e-78b0-43dd-8192-58f63abe1ab3.jpg)

It could be good may be , if have one varible works for all upcoming Teams Env also

**Comment by Jenefer-Monroe** [comment]
Yes i dont know how that env var got in there, as you can tell from the name (**_new__**... instead of **_admin_._**..) this didn't come from our official release at least. The flow does not look for this env var and so it wouldnt work unless you edited the flow as well. For now at least, you will need to exclude the teams envts individually. You could create a flow to mark them all up though if you wanted.

**Comment by Jenefer-Monroe** [comment]
Can you please show me the steps you took to get to the error message shown here
![Flow-Permission](https://user-images.githubusercontent.com/90054514/142011179-b2a63add-b941-4be1-ab2b-f4ce93f53118.png)

**Comment by EmranCoE** [comment]
**Set Flow Permissions**  open the App >> search by owner (whos flows in solution>> in the left side you can see the caution symbol and right side the **Add Permissions** button is disable , flows those are not in solution this button shows enable.

![Screenshot (565)_LI](https://user-images.githubusercontent.com/90054514/142040864-da300920-05dd-4300-9ca3-bf6f342d1a02.jpg)

When click on the flow its go to following page -that showing only Viwer and Editor Role >> when try to Add user >>comes that error I attached  earlier 

![Screenshot (566)](https://user-images.githubusercontent.com/90054514/142042866-fad330e7-b03c-43d0-94e4-a18c8f9e62d3.png)

Also at the bottom of the page  ---**Changing flow ownership is not possible in the product, so changing it here only changes it in the context of your CoE Toolkit. It is stored and used as a property of the CoE Flow table: DerivedOwner**--

**Comment by EmranCoE** [comment]
About the Env Variable . I am very sorry if I make you confused . I just remember now that  I was created this Teams Env Variable  last time for testing purpose in my other computer. 
Ok , thanks for the idea (create a flow)

**Comment by Jenefer-Monroe** [comment]
i believe you have unmanaged layers on that app (Set Flow Permissions). The page now looks like this
![image](https://user-images.githubusercontent.com/89584709/142057946-c40db18b-3ef6-4244-bd4f-b971cadce517.png)

**Comment by EmranCoE** [comment]
Checked just now , did not see any unmanaged layers

![Unmanaged_layer](https://user-images.githubusercontent.com/90054514/142059999-1907faf9-a215-486a-8e7c-dff7a9308f7a.png)

**Comment by Jenefer-Monroe** [comment]
Curious. Do you see multiple instances of the solution installed? I wonder if some upgrade failure hit you.

**Comment by EmranCoE** [comment]
Maybe its better , I explain to you the whole scenario during upgrade
After removed all the unmanaged layers >> started with following order (that might not needed)

1.  Nurture (success , No error )
2. Governance (success , No error)
3. Audit Logs ( failed , got that  error in the  below screen )

![Audit-Logs](https://user-images.githubusercontent.com/90054514/142064272-c0619a8e-421a-44b2-bc3a-976242cc1dd7.jpg)

and there were  two Audit Logs >> I deleted the latest one( version 2.6)

4 . Core ( success ,No error )

5. Then did the Audit Logs  again ( success , No error )
But  that API connection in **[Child] Admin | Sync Logs**  (Office 365 Management API)  could not connect yet . It was created  by my another colleague (in vacation now, waiting for him , hope we dont have to create the API connection again)  , currently Audit Logs components are turn off .
So , the failure hit was in Audit Logs . Does that make this issue or might get other effect in ( Core and Governance Components )

**Comment by Jenefer-Monroe** [comment]
Alright, I'm not sure what to do here. We've already fixed this bug a while ago, but you arent receiving it for some reason. 
You could try doing an overwrite of Core, as shown below. 

Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)
 
Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)
 
Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png)
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by EmranCoE** [comment]
Okay , thanks for the instructions  , if  I understand correct !  Don't have to remove unmanaged layers >> for overwrite  option 

would like to ask about  below screen from **Power Platform Admin View** App

![Maker](https://user-images.githubusercontent.com/90054514/142216774-a046cef1-af6d-4c63-a1c3-043f3eb05eb0.jpg)

 In maker page  , if we change the Display Name and User Principal Name (maker email)  , does this will change the owner (example this person has 13 Apps and 92 Flows) for all Canvas/Model Driven apps/flows ?

Also would like to know is there new CoE version coming in December !

**Comment by Jenefer-Monroe** [comment]
Yes you should always remove unmanaged layers, just in case. 

The Power Platform Admin View app does not make changes to objects, its a read of the inventory. While it will change the value in your inventory temporarily these will be overwritten with the sync flows when the object next changes. 
Use the Set App Permissions app to change ownership
Please post further questions in separate bugs.

**Comment by EmranCoE** [comment]
Okay . Thank you so much for all the help , you can close this issue
