### ISSUE TITLE
[ALM Accelerator - BUG]: Insufficient Steps in the ALM Accelerator for Makers Setup Documentation

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1494]
### Describe the issue

The Set up ALM Accelerator for Makers components documentation does not detail how to link the ALM app with the GIThub organisation. It mentions setting up the org and secrets but I do not see any mention how this is linked. Please can you direct me to more verbose setup instructions, thank you

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

**Comment by mikefactorial** [comment]
@medicineshow agreed it's vague. The secret in question is the admin password. We're making some updates to the docs and will ask that be made more specific.

**Comment by medicineshow** [comment]
Apologies. which admin password?

**Comment by mikefactorial** [comment]
Dataverse admin password. Same password(s) used in the setup app. 
![image](https://user-images.githubusercontent.com/42348035/142669307-26ce7261-4753-4b78-baf9-376fade77694.png)

**Comment by mikefactorial** [comment]
Closing this out as there's not any further action here.
