### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by mehakvij** [microsoft/coe-starter-kit#1495]
### Describe the issue

Trying to Import the November version of the Audit Log component and getting the attached "ImportAsHolding Exception during StageAndUpgrade" error.

I'm getting this for nurture and audit log components but nothing else. Currently doing an upgrade but I can do something else if necessary.

![image](https://user-images.githubusercontent.com/73190679/142081534-32902942-2e74-42a1-838e-127dcdcb4125.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Nov

### What app or flow are you having the issue with?

Audit Log Components

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid we are unable to scale to help you at this time with upgrade issues. Please browse the other closed issues around upgrade to find solutions other folks have used and be sure to consider the version from which you are upgrading when doing the search.
