### ISSUE TITLE
[CoE Starter Kit - BUG] Audit logs 

### ISSUE THREAD

**Issue by silvafr1** [microsoft/coe-starter-kit#1497]
### Describe the issue

After upgrading the Audit Logs Solution to 2.6 version and selecting the TimeInterval-Interval= 10 it still continue to create 60 TimeSegments, so only launching 60 [Child] Admin | Sync Logs.
Basically We still have the bug: https://issueexplorer.com/issue/microsoft/coe-starter-kit/1065

### Expected Behavior

Defining 
TimeInterval-Unit = Minute
TimeInterval-Interval= 10

we should have 144 TimeSegments and we only have 60

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Anything else?

We have follow the procedure mention here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

However we notice that:
We removed the unmanage Layer from the Admin | [Child] Admin | Sync Logs, then turn on the flows and by doing that, we need to configure again the Custom Connector Connection on the [Child] Admin | Sync Logs. Until here everything ok!
But if we see solutions layers again, it appears again the Unmanage Layers on [Child] Admin | Sync Logs.
And its a circle..
![Child Admin - Sync Logs](https://user-images.githubusercontent.com/49397248/142205455-fe15f2cc-7a11-4a93-9b62-f8cd019f09ec.PNG)
.

**Comment by Jenefer-Monroe** [comment]
Flows cache environment variables, and so need to be turned off and back on after you change their value. This is true for all env vars not specific to our solutions.

**Comment by silvafr1** [comment]
Hello,
Honestly I did remove all unmanage layers and stop/start all flows and was always the same result.
Meanwhile I found the tehre exist a variable "TimeSegments-CountLimit"on the Default Solution that was set to 60, so I´ve change the value to 150 and it start to work correctly.  Now I get the 144 childflow run, which was expected for the
TimeInterval-Unit = Minute
TimeInterval-Interval= 10

![TimeSegments-CountLimit](https://user-images.githubusercontent.com/49397248/142443455-96a1bc34-9a3e-490a-bfa7-2d9deed1cc3b.PNG)
 
Thank you.

**Comment by Jenefer-Monroe** [comment]
Aww yes I understand now. Thanks for following up. 
This is documented here. Please let me know if you have some language ideas that would have made this more clear. 

![image](https://user-images.githubusercontent.com/89584709/142444585-295115c1-e418-4e11-bc0f-d0db159a9d54.png)

**Comment by silvafr1** [comment]
Thank you very much!
I´m going to close this isseu.
Regards
