### ISSUE TITLE
CoE Audit Log table not showing any data - GCC

### ISSUE THREAD

**Issue by timgiard** [microsoft/coe-starter-kit#1508]
### Describe the issue

The Audit Log table within our CoE model-driven app does not contain any data. Our "Admin | Sync Audit Logs" and "[Child] Admin | Sync Logs" flows have been set up (Along with the Office 365 Management API) and are turned on. Both flows are running successfully each day since August but we are still not getting any data in the Audit Log table. Any ideas why this may be?

Please let me know if you need any more info.

Thanks,
Tim

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

**Comment by Jenefer-Monroe** [comment]
Are you GCC? #1292

**Comment by timgiard** [comment]
Yes

**Comment by Jenefer-Monroe** [comment]
ok you likely misconfigured in the same way as the customer in that bug. Please review it.

**Comment by timgiard** [comment]
You were correct, the URL needed to be updated and that fixed the issue. Thank you!!

**Comment by Jenefer-Monroe** [comment]
Wonderful!
