### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by emivy20** [microsoft/coe-starter-kit#1511]
### Describe the issue

CoE Theme editor not displaying options to change theme colors
![image](https://user-images.githubusercontent.com/94653172/142510670-2706ce17-7af1-4023-a9a1-9542ae6a61f2.png)

### Expected Behavior

Editable options to change the color of the theme template

### What solution are you experiencing the issue with?

Theming

### What solution version are you using?

2.40

### What app or flow are you having the issue with?

CoE Theme Editor

### Steps To Reproduce

1.) Open CoE Theme Editor app
2.) Create new or edit existing theme template
3.) See if there are options to change the theme colors

**Comment by slaouist** [comment]
Please enable PCF Component in your environment to resolve the issue.
