### ISSUE TITLE
[ALM Accelerator - BUG]: SetupDevEnvironment Cloud Flow always terminates for non paid GitHub orgs

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1522]
### Describe the issue

The SetupDevEnvironment Cloud Flow is part of the ALM Accelerator for Makers solution and runs as a child flow of CreateProject. A condition in the flow states that if the environment variable GitHubOrgPlanExist returns no then the flow terminates. Is this correct as it will always terminate if there is no paid GitHub org plan?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

**Comment by medicineshow** [comment]
Any update on this please?

**Comment by mikefactorial** [comment]
@medicineshow this issue obviously got lost. Can you let me know if this still requires investigation or if not feel free to close. Apologies on the oversight.

**Comment by medicineshow** [comment]
@mikefactorial To be honest, I don't know as since then you released the CoE ALM which meant we no longer were looking at the ALM Maker. I think you can close this as far as we are concerned, thanks.
