### ISSUE TITLE
Error When processing Support type Envs - Admin | Sync Template v3 (Apps) 

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#1524]
In COE Core Compoents   3.1.3

Getting the Error in the Action  Get Apps as Admin within the Load Arrays Scope.

The request failed with client error: 'The environment '<null>' could not be found in the tenant 'xxxxx-xxxxxxxxx-xxxxxxxxx.'. The correlation Id is 'xxxxxxxxxxxxxxxxxx'.

This is likely because the environment , which does exist, is of type Support, a special environment type MS support creates to help identify problems,   even we as Platform Admin  do not get full rights on these types of environments.   Perhaps the COE should not collect data on these at all ???   Or perhaps there is a different problemn here.

**Comment by binaryjam** [comment]
Hi Also having similar errors with other flows,
Sync Flows, Custom Connectors, etc  they all have this problem.

Akk failing in the same Support Environment created my MS which even Power Platform Admin Role members have no rights.

**Comment by manuelap-msft** [comment]
@Jenefer-Monroe Here's some details about these Support environments https://docs.microsoft.com/en-us/power-platform/admin/support-environment - we may have to exclude them from the sync? If we filter them out from the main Admin | Sync Template v3 maybe?

**Comment by Jenefer-Monroe** [comment]
I do not repro this. I got a support envt created, loaded in some objects, and they populate the inventory fine, 
Do you still see this repro? If so can you please share a screenshot?

**Comment by Jenefer-Monroe** [comment]
OK I just did the test a second time and indeed these envts seem to work fine from the CoE pov. 
Note that the copy itself doesnt seem to bring everything over (canvas apps not brought for example) but everything that moved over inventories well. 
Note also that PPAdmins should have access to these envt types. 
I'm going to go ahead and close this but please return if you have trouble again in the future.

**Comment by binaryjam** [comment]
Hi,Sorry cant answer last night at 9pm as not working then, 
But  I still have this problem,  the envs are not accessible to me even as PPadmin role.
I would also put forward the point that these environements are not taking capacity, are not governable, cant be put under dlp and nothing inside of them has any relevance.  Regardless of the problem I am having here, why collect any data on them at all, other than say in the environments list for reference ?

I have looked through a number of the core Flow Sync and I found on the Apps/Custom Connectors/Flow Action Details/Flows
I havent looked further than these as they are the main ones and should be enough

These are the errors that appear in the flows using these actions on support sites.

Error
     Action 'Get_Apps_as_Admin' failed

     Action 'Get_Custom_Connectors_as_Admin'

The request failed with client error: 'The environment '<null>' could not be found in the tenant 'xxxxxx-xxxxxx-xxxxxxxx'.'. The correlation Id is 'xxxxx-xxxxxxx-xxxxxxxx'.


     Action 'List_Flows_as_Admin' failed
     You are not permitted to make flows in this 'xxxxxxx-xxxxxx-xxxxxxxx'. Please switch to the default 
     environment, or to one of your own environment(s), where you have maker permissions.

**Comment by Jenefer-Monroe** [comment]
If the environment are not available to you, then this is an issue with the environment itself themselves and not the toolkit.
I suggest you reach out to support and let them know that you cannot access the support environment.

**Comment by Jenefer-Monroe** [comment]
The customers I have worked with have had access to these environments, as do I in my test tenant. I am following up with support to get clarity. 
I do think adding a flow to auto-excuse support environments from our governance solutions is a good idea though, I've posted this in the meantime: https://github.com/microsoft/coe-starter-kit/issues/1598
