### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Dashboard Issues

### ISSUE THREAD

**Issue by baerj1** [microsoft/coe-starter-kit#1530]
### Describe the issue

From the setup document: Use Legacy is Dataset is over 80MB. Use Dataverse when under 80MB. I'm not sure what the size our data set is. Either way, I tried both .pbit files.

Trying the Legacy .pbit, when opening the report in Desktop, it wants to authenticate and says "The Password won't be encrypted when sent". I'm not sending authentication information unencrypted. Am I missing something from a PowerBi perspective?

![image](https://user-images.githubusercontent.com/78232732/143125623-5041a009-8279-4991-9f86-fe073dd8cdae.png)

When trying the non-legacy .pbit, the report loads but won't return data. Below is a screenshot of the error. I'm not using HTTP in the url.

![image](https://user-images.githubusercontent.com/78232732/143126961-502aafb4-4ef4-4acf-9e27-8378ce8ef6bf.png)
![image](https://user-images.githubusercontent.com/78232732/143127444-8ceb21d2-061c-41ab-97b1-270f09965cfd.png)

When I've loaded the older July one and the October one, I'd run into the SQL error sometimes but most of the time it would work.

### Expected Behavior

The dashboard would refresh and pull in data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

PoweBI Dashboard

### Steps To Reproduce

1. Open PowerBI dashboard in PowerBI Desktop
2. Paste the URL from our environment and connect

**Comment by Jenefer-Monroe** [comment]
Are you using a Dataverse for Teams install? Or a regular production environment. If regular production then I recommend you use Legacy_CoEDashboard_yyyyMM.pbit 

As far as why you can't connect, it looks like you did not include the s in your prefix:
http**s**://yoururl.crm.dynamics.com/

**Comment by Jenefer-Monroe** [comment]
closing out as no new work for toolkit team

**Comment by baerj1** [comment]
Sorry, holidays. We're using the Dataverse in a Production Environment. Not the CDS or the Teams Dataverse. Adding the https worked. A couple suggestions:

1) For the Dataverse for Teams .pbit, please adjust the filename. DataverseTeams_CoEDashboard would help folks that may miss the MS Doc explaining them. 

2) This section under troubleshooting could use some work. It specifically says not to use the https:// when using the Org URL. However, for the CDS .pbit, it's 100% required to use https://. This is what threw me off. Ideally defaulting PowerBI to use HTTPS vs HTTP would have helped here as well, but I'm not sure how to do that.

![image](https://user-images.githubusercontent.com/78232732/143883346-e4778f5f-a7bd-4861-ba5e-7aa8954cc4f9.png)

**Comment by langloif** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/95239504/143907983-e5cd2e69-f29a-436c-b2ff-fbcab87a2432.png)
Submitting the Developer Compliance Center form gives this error. It works if you click submit a second time. VOC: This form is not very good. The questions are unclear. they can be left blank... not the standard I expect from Microsoft.

**Comment by baerj1** [comment]
Sorry, holidays. We're using the Dataverse in a Production Environment. Not the CDS or the Teams Dataverse. Adding the https worked. A couple suggestions:

  1.  For the Dataverse for Teams .pbit, please adjust the filename. DataverseTeams_CoEDashboard would help folks that may miss the MS Doc explaining them.
  2.  This section under troubleshooting could use some work. It specifically says not to use the https:// when using the Org URL. However, for the CDS .pbit, it's 100% required to use https://. This is what threw me off. Ideally defaulting PowerBI to use HTTPS vs HTTP would have helped here as well, but I'm not sure how to do that.
***@***.***
