### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by sreenuvas491** [microsoft/coe-starter-kit#1533]
### Describe the issue

Receiving  error getting environments while Configure embedded apps in the CoE dashboard. I am using latest version of Microsoft Power BI Desktop(x64) - Version 2.99.782.0.

at step 5. With the visual selected, select admin_appid from App (on the Fields pane) and Step 6 With the visual selected, select the admin_environmentid environment (on the Fields pane).
![CoE Power BI Embedded dashboard Error](https://user-images.githubusercontent.com/55984292/143237178-f4360bc8-aa6c-4e8b-87f1-d0bef4f520b4.png)
****Error Message:**** Error getting Environments, server isn't responding try refreshing your browser.
**Note:** I have checked with multiple users, everyone getting same error from past two weeks.

### Expected Behavior

It should able to show the environments.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

embedded apps in the CoE dashboard

### Steps To Reproduce

Configure embedded apps in the CoE dashboard - step 5 and 6

**Comment by manuelap-msft** [comment]
Hello,

whilst we provide the dashobard and the apps, the experience of embedding apps and the Power Apps visual are part of the product. As such, you will have to raise a Support Ticket through official support channels for this issue. Here on GitHub, we can only help you with issues related to the functionality of the CoE Starter Kit but not with product issues you are experiencing. 

Learn how to get support here: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
see also #1436 where someone else hit this, saw it repros outside the toolkit, and found a workaround.

**Comment by sreenuvas491** [comment]
> see also #1436 where someone else hit this, saw it repros outside the toolkit, and found a workaround.

Thanks Jenefer for sharing. I have tried the workaround provided in https://github.com/microsoft/coe-starter-kit/issues/1436. but still receiving same error.
![CoE Power BI Embedded dashboard Error2](https://user-images.githubusercontent.com/55984292/143391536-98226ed0-1fb7-476f-8479-68abecb83eaf.png)

**Comment by petepuu** [comment]
This issue seems to be related to latest November version of Power BI Desktop. At least September and October versions does not have this issue.

**Comment by Jenefer-Monroe** [comment]
@sreenuvas491  I'm afraid you'll need to reach out to product support then. As Manuela says, the issue is with the product and not our toolkit, I was just hoping to help with that workaround, sorry to hear it doesnt work

**Comment by sreenuvas491** [comment]
> @sreenuvas491 I'm afraid you'll need to reach out to product support then. As Manuela says, the issue is with the product and not our toolkit, I was just hoping to help with that workaround, sorry to hear it doesnt work

Thank you so much for your help Jenefer, Latest release on 30-Nov-2021 version working fine.
