### ISSUE TITLE
[CoE Starter Kit - BUG] Incorrect schema to parse Audit Logs

### ISSUE THREAD

**Issue by pandeyup** [microsoft/coe-starter-kit#1534]
### Describe the issue

While running the audit log flow "[Child] Admin | Sync Logs", on the action "Parse JSON"  this is failing for some of the object properties like Recordtype, UserType and Targetlocation.

For some records these values are returned from previous step as integer and some times this is returned as string. So any schema we are using to parse JSON is failing for some of the records.

We are using below schema:
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "OrganizationId": {
                "type": "string"
            },
            "RecordType": {
                "type": "integer"
            },
            "UserKey": {
                "type": "string"
            },
            "UserType": {
                "type": "integer"
            },
            "Version": {
                "type": "integer"
            },
            "Workload": {
                "type": "string"
            },
            "ClientIP": {
                "type": "string"
            },
            "ObjectId": {
                "type": "string"
            },
            "UserId": {
                "type": "string"
            },
            "Application": {
                "type": "string"
            },
            "DeviceName": {
                "type": "string"
            },
            "Platform": {
                "type": "string"
            },
            "UserSku": {
                "type": "string"
            },
            "TargetLocation": {
                "type": "integer"
            },
            "LabelId": {
                "type": "string"
            }
        }
    }
}

Some records I am getting Record type as :  \"RecordType\":\"83\"
For some others I am getting as  : \"RecordType\":25

which is creating schema issues in processing both types of records in one go and resulting in failing of the FLOW.

### Expected Behavior

All properties should be in string or integer (one type of data type) for getting processed from Schema.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Child] Admin | Sync Logs

**Comment by manuelap-msft** [comment]
Hello,

it looks like you have an incorrect schema here. Please look at https://github.com/microsoft/coe-starter-kit/issues/1095#issuecomment-910446704 to learn how to resolve this.

Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as dupe
