### ISSUE TITLE
[CoE Starter Kit - BUG] Documentation request - make clear how to use archive approvals in d4t

### ISSUE THREAD

**Issue by roshansalvi82** [microsoft/coe-starter-kit#1536]
### Describe the issue

I am setting up CoE starter kit on teams environment. 

CoE kit for teams says:
You cannot use the archival solution if you have secured the environment with security groups. Please see Security groups and approvals

However there is no mention of how to remove security group from teams environment. When i create a new team and create first power app, it automatically creates an environment and a security group with teams name automatically gets applied on it.

Please suggest how we could overcome this issue and there doesnt seems to be complete documentation on how to remove security group from teams environment.

### Expected Behavior

There should be some steps in the CoE documentation on how to remove security group from teams environment.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

CenterofExcellenceAuditComponents_2.8_managed

### What app or flow are you having the issue with?

Archival flows

### Steps To Reproduce

Activate the Archival flows in Governance solution
It will start sending emails to admin that the owners doesnt have access on Approvals please add them to environment

This is because of security groups which automatically gets added on teams environment once its gets created

**Comment by Jenefer-Monroe** [comment]
Can you please share a link and a picture of where precisely you see this language?

**Comment by roshansalvi82** [comment]
> Can you please share a link and a picture of where precisely you see this language?

Please go to link and see note in important
You cannot use the archival solution if you have secured the environment with security groups. Please see Security groups and approvals

Link: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components

But when Teams environment gets created, it automatically creates and applies security group for the team environment which is not mentioned in clearly in CoE document. It seems documentation for Setting CoE on teams in not accurate

**Comment by Jenefer-Monroe** [comment]
got it, thank you. We can add a note of some kind here. 
for teams its fine as everyone is in the group by default.

**Comment by roshansalvi82** [comment]
> got it, thank you. We can add a note of some kind here. for teams its fine as everyone is in the group by default.

No. When teams group got created it will only have members of that team and CoE pulls inactive flows and apps from all environments and sends approvals to the owners of these flows/apps. However here those owners will not be got added by default to the teams security group and hence archival flows gets failed.

**Comment by Jenefer-Monroe** [comment]
I see. Yes I had assumed you had already added your Makers, as that's the whole reason to install in Team instead of a regular Production environment.

**Comment by Jenefer-Monroe** [comment]
I have tested this and you are fine to assign approvals to people not in your team. So there is no action for you, you shoudl be unblocked. Please let me know if you are unable to use the functionality but you shoudl not be.

**Comment by Jenefer-Monroe** [comment]
We have updated our documentation for this one for Jan

**Comment by mikefactorial** [comment]
@roshansalvi82 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
