### ISSUE TITLE
[CoE Starter Kit - BUG] - Search in App Access View is not working Power Platform Users for the maker

### ISSUE THREAD

**Issue by Sandhyaraniguriv** [microsoft/coe-starter-kit#1537]
### Describe the issue

Search in App Access View is not working Power Platform Users for the maker
1.Login to Power Platform
2. Go to Apps->Power Platform Admin View
3. Go to Power Platform Users->Search  for your user
4. Click on the user and in General tab ->App Access-->Search this view-->Search for any app with name or role->Shows "No data available" though there are records with the search criteria.

### Expected Behavior

Search results in App access view in Power Platform user is not working.

**Search results should retrieved is the expected result**

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

Search results 

### Steps To Reproduce

Search in App Access View is not working Power Platform Users for the maker
1.Login to Power Platform
2. Go to Apps->Power Platform Admin View
3. Go to Power Platform Users->Search  for your user
4. Click on the user and in General tab ->App Access-->Search this view-->Search for any app with name or role->Shows "No data available" though there are records with the search criteria.

### Anything else?

Nothing
![image](https://user-images.githubusercontent.com/94058637/143560760-932ac8d2-ceb5-497d-9afb-52e8cbb6c26d.png)
![image](https://user-images.githubusercontent.com/94058637/143560908-e7714a05-501a-4062-b9f1-a56ebd43b4c2.png)

**Comment by Jenefer-Monroe** [comment]
We forgot to set the **_Find By_** property. Local fixed for January.
![image](https://user-images.githubusercontent.com/89584709/143931318-3f163c8c-358c-41b5-9fa3-5294e560f3d6.png)

**Comment by Sandhyaraniguriv** [comment]
Ok, Thanks for the update Jenefer.

**Comment by mikefactorial** [comment]
@Sandhyaraniguriv This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
