### ISSUE TITLE
[ALM Accelerator - BUG]: Set Flow Permissions Unable to Flow 

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#1538]
### Describe the issue

Hello COE Team,

I hope you can help please.

I'm using the app "Set Flow Permissions" and once I give myself access to the Flow and click on the "Flow Settings" button a new page opens to go to Flow, but I get a 404 screen. 

![image](https://user-images.githubusercontent.com/68440710/143863201-1e4e2165-be32-4b96-a6cc-bfe15485a86b.png)

If I go to the Flow via flow.microsoft.com I see the URL structure is different compared to opening the app.

URL if flow.microsoft.com: 
https://emea.flow.microsoft.com/**manage/environments**/Default-ENVIRONMENT_GUID/flows/shared/FLOW_GUID/details

URL when clicking the app button "Flow Settings" and getting the 404.
https://emea.flow.microsoft.com/**en-us**/Default-ENVIRONMENT_GUID/flows/FLOW_GUID/details/

Any idea why the button "Flow Settings" is not opening up the correct Flow? I must be doing something wrong.

Thanks,
Garry

### Expected Behavior

Flow to open up when I click the "Flow Settings button.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Set Flow Permissions

### Steps To Reproduce

Go to app "Set Flow Permissions" 
Give myself access as an Owner. 
click on the "Flow Settings" button.
Navigate to the Flow.

**Comment by Jenefer-Monroe** [comment]
Hello, it looks like you did update the environment variables since it points you to EMEA: [Update Environment Variables](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-environment-variables)

Can you please validate you updated this environment variable to **_https://emea.flow.microsoft.com/manage/environments/_**

![image](https://user-images.githubusercontent.com/89584709/143880972-905f15fb-7c20-4bf3-9c4a-a995f53f372b.png)

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe,

That solved in. In the Environment Variable "Power Automate Environment Variable" for it's Current Value we had "https://emea.flow.microsoft.com/en-us/", we then changed it to "https://us.flow.microsoft.com/manage/environments/" and it worked correctly. 

Thanks very much for your help. Like always, superb support from you all. 

Garry
