### ISSUE TITLE
[Enhancement Request] Power Platform Admin Canvas APP view should look like Power Automate itself or link

### ISSUE THREAD

**Issue by NajukHusky** [microsoft/coe-starter-kit#1539]
I have started to work with the CoE especially interested in monitoring and govering the growing number of cloud flows in my environments,

I am always frustrated as admin when I see something interesting shown and I want to deep dive directly in the flow execution or the flow design in the power platform. I need to evaluate flows that may have running issues like many errors, consuming lot ressources or need some other small maintenance that can not be requested by the maker.

Best case would be the "Power Platform Admin View Canvas APP" would get the same design and features as the the view in "Power Automate". See both screenshots to understand what form I mean.
In addition I want than to have the rigths of the maker granted to work on the flow, especially in cases the maker is unavailable (left company, long term absence, illness, etc).

Simple option would be a link somewhere in the list of the "flow details" in the "Power Platform Admin View Canvas APP" to jump to Power Automate directly in the Flow.

Does anybody has similar requirements and would support my aim?
![power plattform admin view canvas app sample page of the flow](https://user-images.githubusercontent.com/95225017/143895259-193741a9-3bec-40b5-8a6d-ad44dde27c16.jpg)
![power automate view flow details sample page of the flow](https://user-images.githubusercontent.com/95225017/143895280-38ce254c-3798-48ac-8961-6dcf0a23e8e8.jpg)

**Comment by manuelap-msft** [comment]
Thanks for the detailed feedback, appreciate you sharing your requirements! Please understand the CoE Starter Kit is not part of the Power Platform product and we can only build experiences for which we have supported APIs or management connectors available to us. That being said, I think there's a few things we can do in the model driven app (such as a "grant access" button and a link to the flow details page) that would help with your requirements. I have added this request to our backlog now, and we will evaluate when we can fund this work.
