### ISSUE TITLE
[CoE Starter Kit - BUG] Not All MDA apps are imported in to the Dataverse Table

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#1541]
### Describe the issue

Not all visible Model Driven Apps in an environment are imported by the Core Flow  "Admin | Sync Template v3 (Model Driven Apps)"

I can see more MDAs in my environment than exist in the table.

### Expected Behavior

I would like to see all MDA's that are visible to users in the Portal  in the COE data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Model Driven Apps)

### Steps To Reproduce

There are two states an MDA can be in, in the Portal.

Those MDAs that have their Play button disabled are not collected.  Those that do have this enabled appear.

I do not know how to cause this behaviour,  but thats how its identified.

### Anything else?

If this is deliberate, can we have all of them imported, but perhaps with a "not working flag".
I need to identify them still even if incomplete, as we do not allow them in certain environments only special ones.
This makes it impossible to create our custom flows to locate any MDA working or not.

**Comment by Jenefer-Monroe** [comment]
Hello, thats correct this is a limitation of the toolkit unfortunately. Please see our [limitations page](https://docs.microsoft.com/power-platform/guidance/coe/limitations#unpublished-model-driven-apps)

**Comment by binaryjam** [comment]
Thanks Jenefer.
