### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by vphuizar** [microsoft/coe-starter-kit#1549]
### Describe the issue

When setting up the **Office 365 Management API** connector in the Custom Connectors section after deploying November update, I am getting a 400 error see below when testing the **Start Subscription**.
{
  "cache-control": "no-cache",
  "content-length": "97",
  "content-type": "application/json; charset=utf-8",
  "date": "Tue, 30 Nov 2021 19:42:03 GMT",
  "expires": "-1",
  "pragma": "no-cache",
  "x-aspnet-version": "4.0.30319",
  "x-ms-apihub-cached-response": "true",
  "x-powered-by": "ASP.NET"
}
{
  "error": {
    "code": "AF20024",
    "message": "The subscription is already enabled. No property change."
  }
}

Have not been able to get this working since the update. 

### Expected Behavior

200 Success

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.41

### What app or flow are you having the issue with?

Custom Connector-Office 365 Management API

### Steps To Reproduce

1. Open Power Apps
2. Select Custom Connectors under Data
3. Select Edit button for Office 365 Management API
4. Click Test>Start Subscription> fill out the Tenant ID and Application ID and select test.

**Comment by Jenefer-Monroe** [comment]
Hello the point of this step is to start the subscription, it sounds, from the error, like you already did that
![image](https://user-images.githubusercontent.com/89584709/144155887-ab4e361d-b9f8-4b59-9dd4-988b1b7ce5fc.png)

So you should be fine to proceed

**Comment by vphuizar** [comment]
Hi Jenefer!

We tried to Start the Subscription and got the error I sent you and also got an error message when trying to Stop the Subscription.  The reason we are troubleshooting the Office 365 Management API is the Power Platform CoE Dashboard has not been updating since end of August/early September.

Thank you!

Victoria

**Comment by Jenefer-Monroe** [comment]
Hello, since this used to work for you (worked in August as you say) that means that the subscription was started in the past. You cannot start the subscription more again hence your error. 

1. Please go see if your audit logs are turned on, running, and passing

![image](https://user-images.githubusercontent.com/89584709/144261584-af52f6ed-9b86-4af4-8a98-2cad189a506c.png)

![image](https://user-images.githubusercontent.com/89584709/144261669-3bab84cb-2e0b-4851-a49e-7a55d5d59b9b.png)

1. If they are turned off / failing, please validate that your connection is still functioning. This is described in this bug
https://github.com/microsoft/coe-starter-kit/issues/1424

**Comment by vphuizar** [comment]
It shows that it has succeeded, but the last run was in November and the flow is turned on.   I have also checked the connections in the Data>Connections and all connections are successful.

***@***.***

Thank you!

Victoria

**Comment by Jenefer-Monroe** [comment]
Can you please share screenshots? Note you will need to be in GitHub for the pictures to come through, replying in email will not share pictures.

**Comment by Jenefer-Monroe** [comment]
And show screenshots for both flows:

- Admin | Sync Audit Logs
- [Child] Admin | Sync Audit Logs

**Comment by vphuizar** [comment]
Please see belwo for the screenshots.
![ChildAdminSyncLogs](https://user-images.githubusercontent.com/84860785/144295946-e0085157-6da8-4f1f-a6ff-c00c0bf0fa7d.PNG)

![AdminSyncAuditLogs](https://user-images.githubusercontent.com/84860785/144295909-1d9e79bb-5253-4def-97e2-4d0aec51930c.PNG)
)

**Comment by Jenefer-Monroe** [comment]
Looks like the flow is ran and passed yesterday. 
Can you tell me a few things
1. Are you a GCC install (or some other govt/special cloud install)
1. Can you validate that this used to gather data? 
1. Can you show me what data is in the Audit Log table? You can see this is the Power Platform Admin View app from Core. Sort by Creation Time so we can see when you were last populated
![image](https://user-images.githubusercontent.com/89584709/144298086-0430c971-d434-4400-b3ba-aee6807c96fe.png)

**Comment by vphuizar** [comment]
Please see below for the answers to your questions.
1.	Are you a GCC install (or some other govt/special cloud install)- **No**
2.	Can you validate that this used to gather data? **Yes, this did gather data at one time.**  
3.	Can you show me what data is in the Audit Log table? You can see this is the Power Platform Admin View app from Core. Sort by Creation Time so we can see when you were last populated
4.1.	Are you a GCC install (or some other govt/special cloud install)
2.	Can you validate that this used to gather data?
3.	Can you show me what data is in the Audit Log table? You can see this is the Power Platform Admin View app from Core. Sort by Creation Time so we can see when you were last populated
![PP_AuditLog](https://user-images.githubusercontent.com/84860785/144301703-caadb106-78b6-4eed-9032-6602e81800ba.PNG)

**Comment by Jenefer-Monroe** [comment]
ok it looks like it is gathering data, per that last column. 
What makes you think its not gathering data?

**Comment by vphuizar** [comment]
Our Power Platform CoE kit is not showing the data updating.

**Comment by Jenefer-Monroe** [comment]
Can you please share a picture of what you mean by that?

**Comment by vphuizar** [comment]
When refreshing the dataset for the Power BI report I am getting the following error:
Data source errorExpression.Error: <pii>A join operation cannot result in a table with duplicate column names ("owningbusinessunitname").</pii>. . The exception was raised by the IDbCommand interface. Table: App Connection Reference.

**Comment by Jenefer-Monroe** [comment]
OK, not sure how we ended up in audit logs. I presume this is some secondary issue now? Or was this the issue the whole time? 

This issue of duplicate columns is covered by #1291 . Its a product change that we have addressed in future versions of the dashboard, but you would need to upgrade your CoE in order to use this, or you can experiment with the workarounds discussed in that bug if you want to just tweak your PBI.

**Comment by Jenefer-Monroe** [comment]
closing out as no additional work for the starter kit team
