### ISSUE TITLE
[CoE -CLI - BUG]: References are invalid when there are separate repositories for each solution in the same project

### ISSUE THREAD

**Issue by rfarris2000** [microsoft/coe-starter-kit#1550]
### Describe the issue

Running the command for SolutionA, all pipelines are setup correctly.
Running the same command but substituting SolutionB, the wrong repository is referenced in the pipelines for SolutionB (SolutionA repository id and name show in Solution B pipelines)

When running the command similar to this one to setup the branch in Devops
```
coe aa4am branch \
-o https://dev.azure.com/devopsorg \
-p power-platform-projects \
-d ProjectName \ 
-r ProjectName  \
--pipelineRepository power-platform-pipelines \
-s validation=https://validation.crm.dynamics.com,test=https://test.crm.dynamics.com,prod=https://prod.crm.dynamics.com
```
The pipelines that get created for Solution B have a reference to the first repository 

### Expected Behavior

The correct behavior should set the repository id and repository name on the cloned build in method cloneBuildSettings in devops.ts right after line 1106.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

0.0.1

### Steps To Reproduce

1) Single devops project (ProjectName)
2) A repository per Power Platform solution 
      Repository - SolutionA 
      Repository - SolutionB

Running the command for SolutionA, all pipelines are setup correctly.
Running the same command but substituting SolutionB, the wrong repository is referenced in the pipelines for SolutionB (SolutionA repository id and name show in Solution B pipelines)

When running the command similar to this one to setup the branch in Devops
```
coe aa4am branch \
-o https://dev.azure.com/devopsorg \
-p power-platform-projects \
-d ProjectName \ 
-r ProjectName  \
--pipelineRepository power-platform-pipelines \
-s validation=https://validation.crm.dynamics.com,test=https://test.crm.dynamics.com,prod=https://prod.crm.dynamics.com
```

**Comment by andrewgaskins** [comment]
I am seeing this also, is there a workaround?

**Comment by rfarris2000** [comment]
It requires an update to the CLI. I have a custom version running that fixes it. I can send you a host tomorrow. 

I probably should create a pull request for it.

**Comment by andrewgaskins** [comment]
Thanks Russ! I was pulling my hair out and decided to go back to manually adding the pipelines which thankfully worked.

**Comment by Grant-Archibald-MS** [comment]
@rfarris2000 would be good to look the changes you have made and will look to see if we can apply the correct fix to the CLI

**Comment by rfarris2000** [comment]
You should see a line in cloneBuildSettings around line 940 in devops.ts similar to the following:

```
        var newBuild = {};
        newBuild.name = destinationBuildName;
        let process = {};
        process.yamlFilename = util_1.default.format("/%s/%s.yml", destination, destinationBuildName);
        newBuild.process = process;
        newBuild.path = "/" + destination;
        // The below line is the problem line
        newBuild.repository = sourceBuild.repository;
```

When the newBuild variable is created and the newBuild.repository object is set to the sourceBuild.repository object, the repository is the wrong one.  It should be the repository parameter passed in as a parameter to the function.

**Comment by Grant-Archibald-MS** [comment]
Thanks Russ, will add unit test and look at add and update to fix the issue

**Comment by mikefactorial** [comment]
@rfarris2000 this should be resolved with the February Release of the CoE Starter Kit. We've updated the coe-cli to ensure that the repo passed in is set on the new pipelines appropriately.
