### ISSUE TITLE
[CoE Starter Kit - BUG] PBI issue with owningbusinessunitname in Dataverse for Teams environment after update to Core v3.10

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#1557]
### Describe the issue

This worked perfectly for me today on the full Dataverse environment we have. It failed complaining about query blockers on App Connection Reference, Flow Connection Reference, and Connector tables on our Dataverse for Teams environment because the column 'owningbusinessunitname' wasn't found. I had to "Transform Data", then manually remove 'owningbusinessunitname', 'annotation', 'new_customconnecterapprovalbpf', and 'systemuser(admin_systemowner)' since they didn't exist from the "Removed Columns" step of the Connector table in PBI.  After that, all worked well.  It's the same dashboard - Dataverse_CoEDashboard_202112 - used both times. It only had issues firing up when connected to my DV4T environment after updating it to v3.10 for the Core Components for Teams.

### Expected Behavior

Successful connection to Dataverse without manipulating queries by hand.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Core 3.10 for Teams

### What app or flow are you having the issue with?

Dataverse_CoEDashboard_202112 PBI Dashboard Template

### Steps To Reproduce

In a DV4T environment, upgrade Core to 3.10.  Deploy Dataverse_CoEDashboard_202112 PBI Dashboard Template connecting to that environment.

**Comment by Jenefer-Monroe** [comment]
Spin off from #1291

**Comment by manuelap-msft** [comment]
Fixing this with #1652 for the January release. If I have the dashboards ready for testing I'll upload them earlier as well and will let you know.

**Comment by manuelap-msft** [comment]
You can try this one: https://github.com/microsoft/coe-starter-kit/raw/coe-january/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Teams_CoEDashboard_Jan2022.pbit

Let me know if you have any feedback! This is the version we're getting ready for the January release and this issue here should be addressed!

**Comment by bartsneary** [comment]
I'm guessing I just have some table cleanup to do (it's never happened in the past, though).  I got these errors when attempting to use that new pbit:

App Connection Reference
Column 'admin_flow' in Table 'App Connection Reference' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
App
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Everything Else - Load was cancelled by an error in loading a previous table.

***@***.***
Bart Sneary
MTC Architect | 952-837-4560 W or 507-403-3088 M
***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.microsoft.com%2fmtc&data=01%7c01%7cjenmoe%40microsoft.com%7cba559a6d6d8544af2e9b08d3386a40e7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=unfjA6YUnXyp8itlgzOIVX%2fbvBKncmBwW6d4D9CANmY%3d>
***@***.***

**Comment by bartsneary** [comment]
Actually, now that I look at the data, admin_flow is expected to be blank in that table if the connection being represented by the record is for an app, right?

***@***.***
Bart Sneary
MTC Architect | 952-837-4560 W or 507-403-3088 M
***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.microsoft.com%2fmtc&data=01%7c01%7cjenmoe%40microsoft.com%7cba559a6d6d8544af2e9b08d3386a40e7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=unfjA6YUnXyp8itlgzOIVX%2fbvBKncmBwW6d4D9CANmY%3d>
***@***.***


From: Bart Sneary
Sent: Monday, December 20, 2021 8:24 AM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] PBI issue with owningbusinessunitname in Dataverse for Teams environment after update to Core v3.10 (Issue #1557)

I'm guessing I just have some table cleanup to do (it's never happened in the past, though).  I got these errors when attempting to use that new pbit:

App Connection Reference
Column 'admin_flow' in Table 'App Connection Reference' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
App
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Everything Else - Load was cancelled by an error in loading a previous table.

***@***.***
Bart Sneary
MTC Architect | 952-837-4560 W or 507-403-3088 M
***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.microsoft.com%2fmtc&data=01%7c01%7cjenmoe%40microsoft.com%7cba559a6d6d8544af2e9b08d3386a40e7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=unfjA6YUnXyp8itlgzOIVX%2fbvBKncmBwW6d4D9CANmY%3d>
***@***.***

**Comment by manuelap-msft** [comment]
I don't repo this with my Teams environment with the December version of Power BI Desktop, but we did have some inactive relationships in the model that may have caused this issue. I updated the .pbit file if you could try again: https://github.com/microsoft/coe-starter-kit/blob/coe-january/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Teams_CoEDashboard_Jan2022.pbit

**Comment by bartsneary** [comment]
That version worked.  Thanks!!

***@***.***
Bart Sneary
MTC Architect | 952-837-4560 W or 507-403-3088 M
***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.microsoft.com%2fmtc&data=01%7c01%7cjenmoe%40microsoft.com%7cba559a6d6d8544af2e9b08d3386a40e7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=unfjA6YUnXyp8itlgzOIVX%2fbvBKncmBwW6d4D9CANmY%3d>
***@***.***

**Comment by manuelap-msft** [comment]
Thanks for verifying! So it was a case of doing some tidy up on our side ;)

**Comment by mikefactorial** [comment]
@bartsneary This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
