### ISSUE TITLE
[CoE Starter Kit - BUG] draft model-driven applications are not shown in the CoE toolkit

### ISSUE THREAD

**Issue by zsolt-illes** [microsoft/coe-starter-kit#1565]
### Describe the issue

The CoE toolkit does not discover draft model-driven apps. The Power Platform admin center however lists the draft apps as well. There is a discrepancy between the two source of information.

Model-driven apps are collected by the _Admin | Sync Template v3 (Model Driven Apps)_ flow, which is getting the list of model-driven apps from the appmodules table of an Environment. The appmodules table in the Environment does not list draft model-driven apps.

The draft model-driven apps are not returned with the WebAPI either.

Not listing the draft model-driven app causes problem in tracking orphaned apps, making clean up impossible for these apps. At this point it is not sure if the CoE Toolkit can be modified in a way to return draft model-driven apps at all, we have not found a way to return these draft model-driven apps.

### Expected Behavior

Draft model-driven apps are collected as well.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2021

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Model Driven Apps)

### Steps To Reproduce

1. Create an model-driven app in the Default Environment.
2. Save, but **do not publish** the app.
3. Run the Admin | Sync Template v3 (Model Driven Apps) flow. _(Alternatively run the  https://<orgname>.crm4.dynamics.com/api/data/v9.1/appmodels REST query.)

RESULT:
The draft (not published) app is not returned by the flow, or the REST query.

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately this is a limitation in the data to which we have access. Like you, we have been unable to find these to include them in the inventory. 
This is outlined in our [limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations#unpublished-model-driven-apps).

**Comment by zsolt-illes** [comment]
I've missed that, sorry. Since there's nothing CoE can do, I am closing the bug then. Thank you.
