### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by powerplatformservice** [microsoft/coe-starter-kit#1566]
### Describe the issue

When trying to upgrade the Nurture component from ver 2.2 (september release) to version 2.5 (nov release) I'm getting an error during the import.
![ImportError Nurture Components](https://user-images.githubusercontent.com/80290869/144493549-214524b5-4201-48f5-97bf-29f395c074dd.jpg)

### Expected Behavior

successfully import the solution to upgrade the current one to the newest

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

Nurture Components Solution

### Steps To Reproduce

1. click on import solution
2. select the solution package and hit import
3. wait 2 minutes
4. the error is shown

**Comment by Jenefer-Monroe** [comment]
Hello. Are you a GCC or other non-standard cloud? Are you trying to install into Dataverse for Teams?

**Comment by powerplatformservice** [comment]
Hi Jennifer,

1st Question: no?
2nd Question: is into Dataverse.

Regards,

**Comment by powerplatformservice** [comment]
Also I'm noticing that there is a new dataflow in the environment

![image](https://user-images.githubusercontent.com/80290869/144642051-bd026380-3088-4c3c-a130-a4bd8c029d61.png)

**Comment by Jenefer-Monroe** [comment]
Can you please try with the Dataflow removed? 
[CenterofExcellenceNurtureComponents_2_6_1_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7651553/CenterofExcellenceNurtureComponents_2_6_1_managed.zip)

**Comment by Jenefer-Monroe** [comment]
had an email thread on this and the removed solution works.
