### ISSUE TITLE
[CoE Starter Kit - BUG] Issue when turning on the flow "CLEANUP - Admin | Sync Template v3 (Check Deleted)"

### ISSUE THREAD

**Issue by patrickpooon02** [microsoft/coe-starter-kit#1567]
### Describe the issue

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'b3f4f0d4-cb1b-ec11-b6e6-00224828c7b0' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

### Expected Behavior

Turn On success and run first time.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Steps To Reproduce

Import the Core solution.
Set the flows to "Run only users" as 1 single account:
- CLEANUP HELPER - Check Deleted (Canvas Apps), (Cloud Flows), (Model Driven Apps), (PVA)
- HELPER - CanvasAppOperations, CloudFlowOperations
Turn on "CLEANUP - Admin | Sync Template v3 (Check Deleted)"

**Comment by Jenefer-Monroe** [comment]
Hello. Child flows need enabled before you can turn on flows that call them. 

The order to turn on the child flows is detailed here: 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

**Comment by patrickpooon02** [comment]
> Hello. Child flows need enabled before you can turn on flows that call them.
> 
> The order to turn on the child flows is detailed here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

Thanks so much! Seems the guide I am using missed some child flows.
Moreover, I cannot find these flows in Core solution. Are they obsoleted?

HELPER - Send Email
HELPER - Maker Check

**Comment by albertocaa1317** [comment]
Hi @Jenefer-Monroe 
I have this same issue after to upgrade from November Release.
It will be necessary follow this steps of configure and turn on the child flows in each new release? I already had configured them and running before the upgrade.

**Comment by Jenefer-Monroe** [comment]
@patrickpooon02 , these two flows were introduced in the Dec release, you have have downloaded before that was released on the 1st.
- HELPER - Send Email
- HELPER - Maker Check

@albertocaa1317, only when new flows are added. If you experienced this without new flows added then some product issue may have occurred. I know that they recently changed the way child flows behaved and so that could have been why you were impacted.

**Comment by albertocaa1317** [comment]
Understood @Jenefer-Monroe!

**Comment by Jenefer-Monroe** [comment]
glad we got this resolved. closing out now as this was just a confusion and not an issue to fix.
