### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by Ayatoujo** [microsoft/coe-starter-kit#1568]
### Describe the issue

I've installed CoE Core Components 3.18 to my Power Platform environment.

Then I want to uninstall the solution but I got a timeout error

![image](https://user-images.githubusercontent.com/95466021/144559267-f3b6ba2e-3eed-40e0-a5f6-09444f077523.png)

### Expected Behavior

Solution this be deleted without any issue like others

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

This issue is not related to app or flow

### Steps To Reproduce

1. Download CoE starter kit
2. Go to Power Apps and import solution
3. After import successfully, delete the solution from environment
4. Wait for deleting process and get the timeout error

**Comment by Jenefer-Monroe** [comment]
Hello. It looks like there are dependencies there and so I wouldn't expect you to be able to delete Core until you had deleted its dependencies. (ex the gov solution). Not sure why that didn't give you a dependency warning though.

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for starter kit team
