### ISSUE TITLE
[CoE Starter Kit - BUG] Envt display name limited to 100 chars but D4T display names can be larger

### ISSUE THREAD

**Issue by dmaloney02** [microsoft/coe-starter-kit#1569]
### Describe the issue

Admin Sync Template V3 error after 8 hours.

It appears there are limits on Environment name length and user generated Teams are exceeding those limits.

### Expected Behavior

Environment Name can be successfully written to CDS and Sync templates complete successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin - Sync Template V3

### Steps To Reproduce

Admin Sync Template V3 error after 8 hours.

Error: Action 'Get_Environment' failed
Error on flow step: Store environments in the CoE CDS Entry
Child Step Error: Check if Legacy Environment: 
Sub Step: Get Environment
{
  "error": {
    "code": "0x80040217",
    "message": "admin_environment With Id = a8eb0889-9773-4478-89e0-a404c1d2fe01 Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "828e383d-d004-eb11-a812-000d3a19b60d",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "9bbfa744-b70a-4cd1-bb52-908a7a419148",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_environment With Id = a8eb0889-9773-4478-89e0-a404c1d2fe01 Does Not Exist"
  }
}

Check if SYSTEM created Environment New:
Insert after check orphan status
If No -> Insert Environment
Error:
OpenApiOperationParameterValidationFailed. The 'inputs.parameters' of workflow operation 'Insert_Environment' of type 'OpenApiConnection' is not valid. Error details: The API operation 'CreateRecord' requires the property 'item/admin_displayname' to be a string of maximum length '100' but is of length '103'.

Display Name: 
Microsoft Team Name is longer than 100 Characters.  Name is omitted for privacy purposes.

### Anything else?

After upgrading the COE core components to 3.19 there are two "Center of Excellence - Core Component" solutions in the COE Environment.  One for 3.19 and one for 2.2.20210707.3.  Any advice on cleanup would be appreciated.

**Comment by Jenefer-Monroe** [comment]
thanks for the thorough investigation. I have updated the max length of the field to 750. and it appears the length limit for teams is 256 so this should work now. 
![image](https://user-images.githubusercontent.com/89584709/144646532-661a51c1-7800-4e0f-8fd7-6dc63c06f218.png)



I'm also testing to make sure objects which might have this references in their tables (ex power apps table - envt display name) will work too. 
Once that is done I will mark this local fixed for Jan.

**Comment by dmaloney02** [comment]
Thank you Jenefer, glad this seems like an easy fix.

Any ideas on removing the duplicate Core solution resulting after the upgrade to the Dec release?

**Comment by Jenefer-Monroe** [comment]
this issue local fixed January. 

Regarding your upgrade issues, here are sometimes issues with upgrade, my typical recommendation is to do a overwrite. 

**HowTo: Classic overwrite upgrade** 

Solution > Switch to Classic (note this can take some time, may have to try twice)  
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png) 

Click Import (fourth from the left)  
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png) 

Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import  
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png) 
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by mikefactorial** [comment]
@dmaloney02 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
