### ISSUE TITLE
[CoE Starter Kit - BUG] Update Core Components 2.0 to 3.13

### ISSUE THREAD

**Issue by rsch136** [microsoft/coe-starter-kit#1575]
### Describe the issue

I am trying to upgrade the core components on our production environment from 2.0 to 3.13. I am getting the following error:

`Solution dependencies exist, cannot uninstall. DependencyCount : 4 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: cb40342d-317d-4ee9-885b-f6ebccaddc03, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Reminder 3 days prior event, Id: bc9a9f1a-afe6-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: cb40342d-317d-4ee9-885b-f6ebccaddc03, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Newsletter with Product Updates, Id: e7a96786-c7e5-e911-a860-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: cb40342d-317d-4ee9-885b-f6ebccaddc03, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Feedback Reminder, Id: 2c42d11c-afe6-e911-a860-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: cb40342d-317d-4ee9-885b-f6ebccaddc03, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Registration Confirmation, Id: bdd94919-afe6-e911-a85c-000d3a372ab9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000`

![image](https://user-images.githubusercontent.com/44471683/144987357-e8ed2557-ecb9-4e71-8d7d-d39a19fee0c4.png)

We have determined that this is caused by 4 flows in the Nurture components that depend on a connection reference in the core components (which has been renamed in the later version). We did not have this issue doing the same upgrade in the validation environment, which is why this error is so particularly annoying.

![image](https://user-images.githubusercontent.com/44471683/144988501-98eccbb3-a205-4760-bd7c-65d91dab0783.png)

### Expected Behavior

I expect the solution to uninstall without any errors like it did in the validation environment

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.0 -> 3.13

### What app or flow are you having the issue with?

Office365OutlookCoEConnection Connection Reference

### Steps To Reproduce

Environment: CoE production
![image](https://user-images.githubusercontent.com/44471683/144988275-102073dd-322d-48b2-969f-934b3702ed1a.png)
Try to install Core components version 3.13

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid we do not repro this locally, and don't know how to get rid of those upgrades either. I've tried several things with other customers and were not able to remove them. Likely this is due to the way solutions were installed in the past and its not something we are able to resolve. The good news is that the solution will still work and so you are not blocked from using the toolkit.

On the side we are planning to create a data migration tool once a product limitation in dataflows blocking this ships, at which time people will be able to start fresh environments in these situations without losing their work.

**Comment by shriyamal** [comment]
@Jenefer-Monroe Thanks for your response, what do you recommend that we should do? There is now two versions of the Core Components solution installed in the production environment. The other question is why didn't we have this issue when upgrading the QA environment as we upgrade in QA to test before applying the same updates to production.

**Comment by Jenefer-Monroe** [comment]
The path you took to upgrade the different environments must have been different in the past, hence this situation. I cannot comment on how you got into this situation, and none of our test environments face it so I'm just not sure how to resolve. 
I dont think there is anything I can do to help you get rid of these "upgrade" solutions now that they are there. 

However, as I said, you should be unblocked and you can ignore them for now. And at some point, once we are unblocked by product work, we plan to offer a migration path to you to get into a clean envt without losing your data.

**Comment by Jenefer-Monroe** [comment]
wonderful, I'll go ahead and close. Sorry about the pain!

**Comment by rsch136** [comment]
Really? Do I understand correctly: you know that this issue exists but you cannot reproduce it so you recommend that we try to fix it in an unspecified manner or ignore it. And eventually you will have another tool for transferring data?

I am not satisfied with this result.

**Comment by Jenefer-Monroe** [comment]
Apologies, I thought that you were the person that had thumbed up the above comment and felt satisfied.

That said, please note that the starter kit is not a MSFT product and is not supported. It is a set of starter templates for folks to use. 
[disclaimer](https://docs.microsoft.com/power-platform/guidance/coe/overview#disclaimer)

**Comment by rsch136** [comment]
Will there eventaully be a MSFT product for monitoring and governance of the power platform? Would be greatly appreciated.
