### ISSUE TITLE
[CoE Starter Kit - Documentation] Discrepancy in numbers between PowerShell, Power Platform Admin Center and CoE Kit

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1577]
Explain and analyse expected discrepancies between getting inventory numbers from different sources.

**Comment by manuelap-msft** [comment]
We will include this in our documentation (with screenshots and samples):

**Discrepancy in numbers between PowerShell, Power Platform Admin Center and CoE Kit**

I was comparing numbers across 
•	PowerShell using Get-AdminPowerApp and Get-AdminFlow
•	Power Platform Admin Center
•	CoE Starter Kit Power Platform Admin View (model driven app)
•	CoE Starter Kit Power BI Dashboard
**Notes**
_SharePoint forms:_
SharePoint custom forms apps can be either in the Default environment or a Designated SharePoint form environment – but also both, e.g. if you have existing SharePoint custom forms in the Default environment and then designate a SharePoint form environment, existing forms will remain in the Default environment and will not be migrated.

_PowerShell and Power Platform Admin Center:_ 
These will always be up to date as you query them and return the latest information.

_CoE Starter Kit data:_
The inventory update runs daily to look for a delta and updates inventory for anything that's new or modified since the last run. However, certain clean up flows only run every 2 weeks. One of these is "Check deleted" which checks if an inventory item (e.g. an app) is still in the tenant and if not marks it as deleted - this flow involves comparing every single row in the CoE tables to your tenant and consumes a high volume of API calls, hence we have this one and similar flows scheduled to run only every two weeks. This means that your data may be out of date if resources have been deleted in the past two weeks.

_Sync flows and admin privileges:_
The CoE starter kit expects all sync flows to run with elevated Power Platform admin privileges at all times – if admin access is lost temporarily during a run, apps/flows that can’t be accessed will be marked as deleted. The CoE kit has no way of knowing what privileges the flows run under, so we can’t record this as a failure – once an app is marked as deleted, the regular daily sync flows will not look at it again (and thus not ever mark it as undeleted). Just one flow run with insufficient privileges can therefore have a big impact on the inventory. If you think this has happened, please run a Full Inventory: Limitations - Power Platform | Microsoft Docs 

_Expected differences:_
•	PowerShell returns only canvas apps and SharePoint custom forms.
•	Power Platform Admin Center shows canvas apps and published and unpublished model driven apps, but not SharePoint custom forms. I sometimes had to F5 the Resources page in the Admin Center to get it to show the correct environment, there seems to be a caching issue where it sometimes showed the previous environment.
•	The CoE starter kit shows canvas apps, published model driven apps, and SharePoint custom forms but not unpublished model driven apps (if the "play" button on a model driven apps is greyed out)
•	PowerShell, Power Platform Admin Center and CoE Starter Kit both shows flows that are in and outside of solutions and that do not have a connection error. When you try and turn on the flow and receive this error, this causes the flow to not be included anywhere.
 

_Deleted apps and flows:_
There are two options in the CoE Starter Kit to handle deleted resources – either they are deleted from the inventory or they are marked as deleted (via a “Deleted” true/false flag). This is controlled via an Environment Variable. The environment variable is called: Also Delete from CoE
 
If you have this environment variable set to No it will keep a record of deleted apps and flows and highlight them as deleted via a flag. This can then lead to a discrepancy in numbers – for example, the Power Platform Admin View (model driven app) filters out deleted items
 

But not all pages of the Power BI Dashboard do, e.g., the Apps page only checks if the environment is deleted but not apps themselves.
 

In my environment, I have this flag set to Yes which means no deleted records are kept.

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
