### ISSUE TITLE
[CoE Starter Kit - BUG] Connection references not always returned from Get flow as Admin

### ISSUE THREAD

**Issue by paulculmsee** [microsoft/coe-starter-kit#1580]
### Describe the issue

A newly created custom connector is missing some properties that is used to report... ie

![image](https://user-images.githubusercontent.com/4979626/145158384-bbf9f190-c412-4930-9efa-e66c655f6b26.png)

![image](https://user-images.githubusercontent.com/4979626/145158421-b9e5e271-a5bc-4534-8737-b19d802d42d3.png)

The connection reference data is missing now, which now means important custom connectors are not being reported to the dashboard

### Expected Behavior

Each custom connector in a flow should be correctly enumerated for the connector dashboard to properly work

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### Steps To Reproduce

1. Add new custom connector (preferably using PACONN command)
2. Make a connection ref and add a sample flow
3. Run the flow sync for that environment

**Comment by Jenefer-Monroe** [comment]
Can you please share how you got a custom connector without a display name?

**Comment by paulculmsee** [comment]
So further investigation and its SUPER weird...

Here is our current assessment distilled:

2 environments. Env A and env B

1. Add a flow that uses Gets flows as admin" to each of them
2. Add a custom connector to each env via PACONN or UI
3. Make a connection for step 2 and make a flow that uses that custom connector in each env.

Test:

Run the step 1 flow from env A and look at a flow within Env A and see missing connection ref
Run the step 1 flow from env A and look at the flow from Env B and see missing connection ref
Run the step 1 flow from env B and look at the flow from Env B and see connection ref as expected!
Run the step 1 flow from env B and look at the flow from Env A and see connection ref as expected!

So the same flow/connector steps behaves different in 2 envs! Unforunately for me, my CoE environment is env A

**Comment by paulculmsee** [comment]
Hey @Jenefer-Monroe 

I have been testing with with help from Ashlee and have isolated the issue some more. She reports this:

Two flows.

"PP Admin Get Flows - Created by Ash" (made with my woodside acct)
"PP Admin Get Flows - Created by Service Account" (made with the service acct)

They both are created in the environment dedicated to CoE and are currently looking at the "For Ashlee To Test" flow in a different environment. This flow has 2 normal connectors and 1 custom connector.

If I run "PP Admin Get Flows - Created by Ash" as me, I see everything as expected
If I run "PP Admin Get Flows - Created by Ash" as Service Account with Ash Connections, I see custom connector missing connection reference details and the regular connectors as expected
If I run "PP Admin Get Flows - Created by Ash" as Service Account with Service Account Connections, I see custom connector missing connection reference details and the regular connectors as expected

If I run "PP Admin Get Flows - Created by Service Account" as Service Account, I see custom connector missing connection reference details and the regular connectors as expected
**If I run "PP Admin Get Flows - Created by Service Account" as Ash with Service Account Connections, I see everything as normal**
If I run "PP Admin Get Flows - Created by Service Account" as Ash with Ash Connections, I see everything as normal

So far, any flow run by the Service Account brings back custom connectors truncated. This is despite it being a sysadmin of each environment by virtue of AAD roles

**Comment by paulculmsee** [comment]
Hey @Jenefer-Monroe 

I have been testing with with help from Ashlee (in fact mostly Ashlee :) and have isolated the issue some more. She reports this:

Two flows.

"PP Admin Get Flows - Created by Ash" (made with her acct)
"PP Admin Get Flows - Created by Service Account" (made with the service acct that runs CoE)

They both are created in the environment dedicated to CoE and are currently looking at the "For Ashlee To Test" flow in a different environment. This flow has 2 normal connectors and 1 custom connector.

If I run "PP Admin Get Flows - Created by Ash" as me, I see everything as expected
If I run "PP Admin Get Flows - Created by Ash" as Service Account with Ash Connections, I see custom connector missing connection reference details and the regular connectors as expected
If I run "PP Admin Get Flows - Created by Ash" as Service Account with Service Account Connections, I see custom connector missing connection reference details and the regular connectors as expected

If I run "PP Admin Get Flows - Created by Service Account" as Service Account, I see custom connector missing connection reference details and the regular connectors as expected
**If I run "PP Admin Get Flows - Created by Service Account" as Ash with Service Account Connections, I see everything as normal**
If I run "PP Admin Get Flows - Created by Service Account" as Ash with Ash Connections, I see everything as normal

So far, any flow run by the Service Account brings back some custom connectors truncated. This is despite it being a sysadmin of each environment by virtue of AAD roles

**Comment by Jenefer-Monroe** [comment]
Tagging as Product issue and updating title. Will wait to hear from Product Team

**Comment by Jenefer-Monroe** [comment]
Found that we dont need to differentiate between custom and not here so dont need the verbose info. Able to always behave the same now custom/not verbose/small.

LF and running a validation suite, will send to partner to test

**Comment by manuelap-msft** [comment]
This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
