### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by sparsley1975** [microsoft/coe-starter-kit#1582]
### Describe the issue

We have followed the Microsoft instructions and was able to successfully update the Center of Excellence to the December 2021 release, version 3.19. In the solutions the old/new are there. How do we know the update was actually successful?

### Expected Behavior

We expected the latest update should be shown, not the two versions.
![CoE-Dec2021-Update](https://user-images.githubusercontent.com/95759543/145222381-3e9b6acb-2af4-4732-b12a-aa8a1c149f6b.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### Steps To Reproduce

1. Login to CoE
2. Solutions \ we see both the old and the new upgraded releases
3. How do we know it's been upgraded as per the screen sho
![Screenshot](https://user-images.githubusercontent.com/95759543/145222816-17b9b1f1-5fd8-4ddc-94c2-03f02697b920.jpg)
t?

### Anything else?

Incident title:	We have followed the Microsoft instructions and was able to successfully update the Center of Excellence to the December 2021 release, version 3.19. In the solutions the old/new are there. How do we know the update was actually successful?

Expect response within:	1 day
Name:	Shannon Parsley
Email address:	shannon.parsley@sjrb.ca
Contact numbers:	1 (587) 391-2748 Canada
Available: anytime, 7am-4pm MST

**Comment by Jenefer-Monroe** [comment]
Hello. To set context, the CoE is not a MSFT product. It is not officially supported and hence does not have any SLA.
Please see our [disclaimer](https://docs.microsoft.com/power-platform/guidance/coe/overview#disclaimer)

**Comment by Jenefer-Monroe** [comment]
We have seen some folks hit this, its due to the mechanisms used to upgrade the solution either this time or in the past. 
We cannot repro ourselves and do not have advice on how to make this appear cleaner. 

That said, you are functionally fine, the upgrade is applied and you can proceed using the toolkit. 
At some point we hope to offer a mechanism to migrate data to a clean environment in order to no longer see these confusing objects when people get into this state.

**Comment by sparsley1975** [comment]
Hey Jenefer - thanks for your prompt response.

Based on this, if we do future updates, should we see the older versions continue to appear for the Core Components?

We updated the Audit Log and the version incremented as expected.

**Comment by Jenefer-Monroe** [comment]
I don't know if this will clean itself up. Your state is unclear to us. If you are only using us for inventory from core + audit logs, you can do work to migrate to a clean envt now using steps described in #1507

**Comment by sparsley1975** [comment]
Everything is working fine, no issues with the program itself, just confused over the update results.

We are just curious that when we apply the next update to the Core Components, will we see the older versions continue to build up?

As you stated, it's unclear if this will clean itself up. 

**Just so I understand:**
- We can continue to use the CoE as our update experience has been seen by other customers
- Unsure of the root cause
- Future updates may result in the same behavior

Are all these points correct?

**Comment by v7herman4** [comment]
@sparsley1975 did you see a place in the upgrade steps documentation on which order to install the solutions? If not, @Jenefer-Monroe is there a recommended order to install the separate solutions (i.e. core then admin, etc.?)

**Comment by sparsley1975** [comment]
No, I did not.

I simply followed the instructions from the Microsoft site that pointed me to GitHub to download the zip file. The only thing listed was to choose "upgrade", which we did.

The instructions are very light on details outside of that step.

Was there some process that needed to be followed? If so, where?

**Comment by Jenefer-Monroe** [comment]
I do not have an order to recommend. There were times in the past when we had a prescribed order but that was a one off. 
The steps to upgrade are simple, theoretically. Ensure you have no unmanaged layers and upgrade. 
It sounds like things are working so I think we can close this now.

**Comment by sparsley1975** [comment]
OK Jenefer, thanks for the reply.

Based on this, I guess we don't know or understand the behavior that has been encountered. The instructions from the Microsoft site are very simple as you stated. We will monitor for next update and have to gauge the experience at that time.

Once done, I can open up a new ticket with GitHub should we see the same thing.

In the mean time, if you have anything additional related to this ticket that you can share, we would appreciate it.

Thank you for your time.

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist in ugprades that are this old. We do plan to create a migration story for when people get stuck but we do not have the features yet to provide that.
