### ISSUE TITLE
[CoE Starter Kit - BUG] Nurture Components Solution Fails to Import

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1585]
### Describe the issue

When importing the new Nurture  Components solution, I get the error message:
Error reading JObject from JsonReader. Path '', line 0, position 0.
I have tried using Upgrade, Staging and Update paths to no avail. I am upgrading from version 2.5 to 2.6

### Expected Behavior

To upgrade to 2.6

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

The whole solution

### Steps To Reproduce

Just upgrading by importing the solution

**Comment by Jenefer-Monroe** [comment]
This appears to be occurring in the process well before anything specific to the starter kit. And I've not heard of this repro from others before. 
Can you please validate that you are selecting the zipped nurture solution
[CenterofExcellenceNurtureComponents_2_6_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7677434/CenterofExcellenceNurtureComponents_2_6_managed.zip)

**Comment by medicineshow** [comment]
I can confirm that is the version which is packaged in the latest release

**Comment by medicineshow** [comment]
when i tried using the legacy import i get this
![image](https://user-images.githubusercontent.com/17124284/145247031-693efc33-ac12-45ae-8fa4-801eef352cb0.png)

**Comment by medicineshow** [comment]
![image](https://user-images.githubusercontent.com/17124284/145247346-4a997507-1e89-4e11-98e6-c50c724c58d2.png)

**Comment by Jenefer-Monroe** [comment]
I see. I have never seen this occur, and the solution is not large. Its the smallest of our solutions actually.
Perhaps there is a relationship between envt capacity and ability to import.

**Comment by medicineshow** [comment]
I have checked capacity and it is ok. I also reset the environment and tried the upgrade again. All of the other solutions have upgraded without issue but Nurture still fails with the same error.

**Comment by Jenefer-Monroe** [comment]
Can you check to see if install works without the Dataflow in the package? [CenterofExcellenceNurtureComponents_2_6_1_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7651536/CenterofExcellenceNurtureComponents_2_6_1_managed.zip)

**Comment by medicineshow** [comment]
It worked

**Comment by medicineshow** [comment]
Thank you

**Comment by Jenefer-Monroe** [comment]
Great news! Please see #888 for a workaround to get the data imported that the dataflow was supposed to import for you.
