### ISSUE TITLE
[CoE Starter Kit] Make co-owners derived owners for flows

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1589]
In regard to flow/app clean up flows. Currently running November release. For orphan flows/apps where original owner is gone...any plans to automatically promote an existing editor to derived owner?

**Comment by manuelap-msft** [comment]
additional comment: yeah, currently, as the admin that approves the semi orphan artifacts to be archived or kept, am going through and rejected and manually assigning someone with editor perms to the derived owner...ideally, would like the approval flow to go a new derived owner...

**Comment by JeneferM-MSFT** [comment]
I think this is covered by the work to assign this to the manager. So rather than blindly reassigning we now ask the former employee's manager to decide.

**Comment by Jenefer-Monroe** [comment]
This is WF
