### ISSUE TITLE
[CoE Starter Kit] Add Adoption Maturity model assessment as an app

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1591]
Perhaps the Adoption Maturity Dashboard (assessment currently in Power Point) into the CoE as part of the "how are we doing" section? :)

**Comment by Jenefer-Monroe** [comment]
putting on backlog as full sized feature request

**Comment by manuelap-msft** [comment]
Closing out old feature asks that have not come up in a while.
