### ISSUE TITLE
[CoE Starter Kit] Videos for each app 

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1592]
- Video Idea "Day in the life of the Power Platform Admin" starring the CoE (guest starring the admin portal ;-))
- Suggestion: Mini videos (April style 1 minute?) on each of the apps especially the governance and nurture ones the "users" are expected to use :)

**Comment by albertocaa1317** [comment]
Great idea!

**Comment by Jenefer-Monroe** [comment]
Each video would flow like the below, please let us know if there is anything else you would want.

- Quick intro on what the app is an why its interesting
- How you get the app (ie which solution, which setup instructions)
- Who the app is for and how to share it (may point to another video for details)
- How to populate the data (if something augmented aside from sync flows, example app catalog)
- Then a detailed dive into the specific app usage

We may bucket a few apps when they are quite similar. Ex: Set App Permissions and Set Flow Permissions

**Comment by manuelap-msft** [comment]
Closing out.
