### ISSUE TITLE
Error Importing CoE Theme msapp. file 

### ISSUE THREAD

**Issue by Eelane** [microsoft/coe-starter-kit#1596]
Hi

I saved , published and exported the CoE Theme file successfully however when I got an error when importing the file into my environment. I tried in 2 different environments and still gotten the same error. (see CoETheme_error for error message).

I am using the Theming v2.4

![CoETheme_error](https://user-images.githubusercontent.com/50645700/145329474-e46927e8-92da-44fa-a50f-2f87322b953f.JPG)

Cheers
Ee Lane

**Comment by mikefactorial** [comment]
@EElane just ran across this while triaging issues. Sorry it took so long to respond it seemed to slip through the cracks. Is this still an issue?

**Comment by mikefactorial** [comment]
Feel free to open a new issue if you need more assistance here.
