### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Request email text incorrect

### ISSUE THREAD

**Issue by rrwolfe** [microsoft/coe-starter-kit#1603]
### Describe the issue

When a maker creates a request for a new environment and defines an expiration time period (ex. 30 days), the admin then approves that request using the Environment Request - Admin app, it sends an email to the maker stating that the environment has been created. In the same email it states that the environment doesn't have an expiration date, even though it does, see below.

![image](https://user-images.githubusercontent.com/74214126/145490368-eaf353ed-505b-41cd-87bf-dfcb864bbcb3.png)

### Expected Behavior

The email should contain the expiration date if one has been defined during the environment creation request.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Env Request | Create approved environment

### Steps To Reproduce

1. Access the Environment Request app and create an environment request with an expiration date defined
2. Admin should access the Environment Request - Admin app and approve the request
3. Email gets generated stating the there is no expiration for the environment

**Comment by Jenefer-Monroe** [comment]
assigning to area owner

**Comment by denisem-msft** [comment]
@rrwolfe Thank so much for your feedback! 

This has been fixed and will be available in the next release. You may test out the solution with the attached solution file in this message.

[CenterofExcellenceCoreComponents_3_19_2_managed.zip](https://github.com/microsoft/coe-starter-kit/files/7748469/CenterofExcellenceCoreComponents_3_19_2_managed.zip)

**Comment by rrwolfe** [comment]
@denisem-msft Bug fix has been validated on my end. Thank you!

**Comment by mikefactorial** [comment]
@rrwolfe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
