### ISSUE TITLE
Question:  Does Audit Log data get deleted when App is deleted from CoE?

### ISSUE THREAD

**Issue by osbornecc** [microsoft/coe-starter-kit#1609]
### Describe the issue

With some App cleanup we're performing in our tenant, a question came to mind.  If the CoE notices the App is deleted from the tenant, and then the flows delete it from the CoE ("also delete from CoE" = yes), will that App's entries in the Audit Log table also be deleted?

Thanks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

n/a

**Comment by Jenefer-Monroe** [comment]
No it will not, there is no such flow in place.

**Comment by osbornecc** [comment]
Good to know.  Thank you!

**Comment by Jenefer-Monroe** [comment]
you bet!
