### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3

### ISSUE THREAD

**Issue by gbecerra1982** [microsoft/coe-starter-kit#1610]
### Describe the issue

After importing Core Components we are getting errors running "Admin | Sync Template v3" with the following error:

![image](https://user-images.githubusercontent.com/6539041/145621526-5e832867-2c9c-4524-b3e0-8a83edb0bb64.png)

{

  "error": {

    "code": "0x80040217",

    "message": "admin_environment With Id = 0e86502a-6c5e-47ec-955c-dbd00f5fc9a6 Does Not Exist",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "a68f376c-d159-ec11-8f8f-002248384ed3",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "ea885575-33cc-44c9-9474-7a2f0f2d6d18",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",

    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",

    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_environment With Id = 0e86502a-6c5e-47ec-955c-dbd00f5fc9a6 Does Not Exist"

  }

}

### Expected Behavior

The flow should be collecting without errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

We removed some environments empty, but we received the same error for a Dynamics environment that we cannot remove.

### What app or flow are you having the issue with?

Admin - Sync Template v3

### Steps To Reproduce

Import the Core Components and once all the Flows for Connectors, Apps, etc. are enabled we tried to run the Admin | Sync Template v3 and is always failing.

The customer tried to remove 2 environments but seems to be happening for many environments. 

### Anything else?

No

**Comment by Jenefer-Monroe** [comment]
Can you please translate that error message for me from the Get Environment call?

**Comment by Jenefer-Monroe** [comment]
Please share the exact failure at the point of the call failing, rather than this general one shown for the whole flow. 
See how there is more specificity at the point of failure, as shown here for an unrelated failure. 

![image](https://user-images.githubusercontent.com/89584709/145629390-b58dec14-fd69-44dd-a791-eaafa59adf14.png)

**Comment by Jenefer-Monroe** [comment]
Note also that this is a caught failure. If the environment is not yet in the CoE inventory, we find that out by this call failing, setting the variable in that case, and then adding in the records below.
![image](https://user-images.githubusercontent.com/89584709/145630325-02ec2b80-294a-4f79-a380-69cb12bf089d.png)

You need to find the first uncaught failure in order to find what is wrong.

**Comment by gbecerra1982** [comment]
Hi Jennefer,

I would like to share the screenshot with the details:

![image](https://user-images.githubusercontent.com/6539041/145997106-17e897f3-8f94-4a97-960c-3d3f1d46aa1b.png)

  "error": {

    "code": "0x80040217",

    "message": "admin_environment With Id = 0e86502a-6c5e-47ec-955c-dbd00f5fc9a6 Does Not Exist",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "a68f376c-d159-ec11-8f8f-002248384ed3",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "4710f99d-a45a-4b4d-bfed-f951e33c2165",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",

    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",

    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_environment With Id = 0e86502a-6c5e-47ec-955c-dbd00f5fc9a6 Does Not Exist"

  }

![image](https://user-images.githubusercontent.com/6539041/145997339-8e4dd2aa-3e8e-4f2d-aa6d-fc4f4fc5c175.png)

![image](https://user-images.githubusercontent.com/6539041/145997402-b1f9a90d-5fd5-482b-bcbb-f838f148f6fe.png)

**Comment by gbecerra1982** [comment]
If we go to Power Platform Admin view we are not able to see any record. The issue is mainly with Dynamics 365 LAB Environment that is causing the error. We are not able to delete because is currently in use.

**Comment by Jenefer-Monroe** [comment]
It looks like you did not turn on that child flow. 
Please also be careful in the future and do not expose customer GUIDs in these bugs as they are public.

**Comment by gbecerra1982** [comment]
which child flow? all the Admin | Sync Template v3 all flows are enabled, in fact Connectors run success but not for Environments which is failing.

**Comment by Jenefer-Monroe** [comment]
The action Get Maker is a call to a child flow. It calls this helper: HELPER - Maker Check
Here is the full list of child flows that need enabled (list is for Dec release). 
https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

**Comment by gbecerra1982** [comment]
Hi Jenefer, we double check the flows and we identified that flow was disabled for some reason. Thanks a lot for your help on this request! we are able to proceed with the COE Implementation!

**Comment by Jenefer-Monroe** [comment]
great news. closing out
