### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Custom Connectors) - admin_customconnectorhost limited to 100 characters

### ISSUE THREAD

**Issue by TreyPoint** [microsoft/coe-starter-kit#1611]
### Describe the issue

Within the Admin | Sync Template v3 (Custom Connectors) the Action "Create Custom Connector" fails because the API operation 'CreateRecord" requires the property 'item/admin_customconnectorhost' to be a string of maximum length of '100' but is of length '101'.

![SyncTemplatev3_Custom_Connectors_Length_error_1](https://user-images.githubusercontent.com/7740876/145634442-5f41a2d3-94a8-40d3-a7e8-9ad69aa75a99.png)
![SyncTemplatev3_Custom_Connectors_Length_error](https://user-images.githubusercontent.com/7740876/145634455-73748a13-2780-4a25-b352-8f818d63567e.png)

### Expected Behavior

The ability to write the full Custom Connector Host URL to the PowerApps Connector Table, 'Custom Connector Host' field via the Admin | Sync Template v3 (Custom Connectors) Cloud Flow. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors)

### Steps To Reproduce

Create a Custom Connector that has a host URL that is longer than 100 characters, allow the Admin | Sync Template v3 (Custom Connectors) to run and you will recieve a "OpenApiOperationParameterValidationFailed".

### Anything else?

Is there a reason why the table and column properties are not published anywhere?  Can we get a published version on new releases that illustrates the tables, columns, properties, and relationships?

This would help understand the limits, setup, and usage of these items.

**Comment by Jenefer-Monroe** [comment]
We dont publish that just due to cost. The starter kit is not a MSFT product, just a set of tools a couple of us make for folks to get going on monitoring and governing PP in their tenant. 
This is local fixed for Jan.

**Comment by TreyPoint** [comment]
Thanks @Jenefer-Monroe - I was hoping as part of the Starter Kit teams creation of tables, apps, and flows this type of information would be shared with the community.  I apologize for making the assumption that this would have already been created and wouldn't involve any extra work for the team. 

Thanks for getting this updated for the Jan release.

**Comment by Jenefer-Monroe** [comment]
No problem, I dont mind you asking. Thanks for posting an easy one for me :)

**Comment by mikefactorial** [comment]
@TreyPoint This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
