### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs - Env variables StarTime-Interval... don't updated after apply new current value

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#1613]
### Describe the issue

Hi,
I just installed the Audit Logs solution for the 1st time, version 2.6.
The flows run OK but I need retrieve data of the 15 days previous, for example. 1 day, the default value, is not enough for me.
Then I modified this env variables in the Default solution, but the change is not applied.
Is it necessary to do other step?
![image](https://user-images.githubusercontent.com/57954993/145638777-dcee0b2f-c8ed-4017-897a-9b3b75709d98.png)

![image](https://user-images.githubusercontent.com/57954993/145638807-62fb8ba1-f352-48cf-9045-de73be0335d4.png)

### Expected Behavior

The value of the start Time should be 15 days, do not?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Anything else?

I'm following this doc, step 11:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

**Comment by Jenefer-Monroe** [comment]
Power platform caches environment variables in different ways in the different tools. 
Power Automate caches them until the flow is reset, which can be done by turning the flow off and back on for example. 
Hope that helps!

**Comment by albertocaa1317** [comment]
Yes! After turn off and back on both flows of this solution the new values has been applied.
Thanks @Jenefer-Monroe!
