### ISSUE TITLE
[CoE Starter Kit - Audit Log] Action 'Run_a_Child_Flow' failed

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#1614]
### Describe the issue

Hi,
I have this error in flow "Admin | Sync Audit Logs"

**Error:** Action 'Run_a_Child_Flow' failed
**Error details:** The server did not receive a response from an upstream server. Request tracking id 'XXX'
![image](https://user-images.githubusercontent.com/57954993/145710591-24e870a4-890e-4966-ad11-8a720282d971.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Anything else?

This is the values if the environment variables used in this flow:
**StarTime-Interval:** 7
**StarTime-Unit:** Day
**TimeInterval-Interval:** 15
**TimerInterval-Unit:** Minute
**TimeSegments-CountLimit:** 1500

I have this values because I would like retrieve the information about the last 30 days, if it's possible.

In the first execution with the default variables, I received this notifications:
_"Your audit logs were collected but some were missed do to truncated results in this run . 
You will need to use a smaller interval to gather all logs. 
Current chunking size: 1 Hour
See CoE documentation for more details."_ 

Because of that I reduced the the TimeInterval to 15 Minute. Even so, I also had notifications about the new chunking size. 
Can you give us a detail explanation of this variables and how work them?

**Comment by albertocaa1317** [comment]
With this configuration also fails:
StarTime-Interval: 7
StarTime-Unit: Day
**TimeInterval-Interval: 1
TimerInterval-Unit: Hour**
TimeSegments-CountLimit: 1500

**Comment by albertocaa1317** [comment]
With this configuration runs OK:
StarTime-Interval: 3
StarTime-Unit: Day
TimeInterval-Interval: 5
TimerInterval-Unit: Minute
TimeSegments-CountLimit: 1500

**Comment by Jenefer-Monroe** [comment]
looks like this is resolved now. We do have, on the backlog, documenting these more deeply. For now they were just put in the toolkit to help go-getters like you that we knew could bang it to a solution without having to end up with an unmanaged layer :)
