### ISSUE TITLE
[CoE Starter Kit - BUG] COE Starter Kit Install in GCC High - Core Components

### ISSUE THREAD

**Issue by cdt2021** [microsoft/coe-starter-kit#1615]
### Describe the issue

I'm removing a previous environment used to install my COE StarterKit to install a new version of the Toolkit using a service account instead of an individual account.  I've created the separate environment in GCC High to specifically install the COE Toolkit and I've done so using a newly created service account.  I started with the the Core Components.  The install of the core components was successful.  Once I arrived at the step to "update and turn on the child flows" in the documentation I encounter an error when trying to edit the "HELPER - Send Email".   I've don the following steps:

1.  Select the default solution.
2.  Sort the solution by Cloud flows.
3.  Select the ellipses of the Helper - Send Email and select edit 

When doing so It takes me to the flow however it just sits there and doesn't show any of the details.   If I select edit again once I see the flow I see the following error. "Error: Could not find flow '21499cb2-7be1-4c99-8fec-845da4bc7e4b'." See my screenshots below that show my steps:

![image](https://user-images.githubusercontent.com/80719563/145834579-613b3212-e233-4ab7-b140-fbad078564ea.png)

![image](https://user-images.githubusercontent.com/80719563/145834707-bb282029-c0ed-42f1-bf82-bf96d0019495.png)

![image](https://user-images.githubusercontent.com/80719563/145834847-59a9ed63-40a3-41da-971e-b88ef03c997b.png)

### Expected Behavior

I expect to see the details of the flow and the ability to edit them. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

HELPER - Send Email

### Steps To Reproduce

I'm removing a previous environment used to install my COE StarterKit to install a new version of the Toolkit using a service account instead of an individual account.  I've created the separate environment in GCC High to specifically install the COE Toolkit and I've done so using a newly created service account.  I started with the the Core Components.  The install of the core components was successful.  Once I arrived at the step to "update and turn on the child flows" in the documentation I encounter an error when trying to edit the "HELPER - Send Email".   I've don the following steps:

1.  Select the default solution.
2.  Sort the solution by Cloud flows.
3.  Select the ellipses of the Helper - Send Email and select edit 

When doing so It takes me to the flow however it just sits there and doesn't show any of the details.   If I select edit again once I see the flow I see the following error. "Error: Could not find flow '21499cb2-7be1-4c99-8fec-845da4bc7e4b'." See my screenshots below that show my steps:

![image](https://user-images.githubusercontent.com/80719563/145834579-613b3212-e233-4ab7-b140-fbad078564ea.png)

![image](https://user-images.githubusercontent.com/80719563/145834707-bb282029-c0ed-42f1-bf82-bf96d0019495.png)

![image](https://user-images.githubusercontent.com/80719563/145834847-59a9ed63-40a3-41da-971e-b88ef03c997b.png)

**Comment by cdt2021** [comment]
Checking to see if anyone has received my issue?

**Comment by Jenefer-Monroe** [comment]
Hello, 

Please note the CoE Starter Kit is an unsupported set of templates: https://docs.microsoft.com/power-platform/guidance/coe/feedback-support 

We do not have a support team that can help resolve issues, and support is provided on best endevaours without SLA via GitHub. We will look into your issue, but at the moment can not provide a timeline.

Thank you for your patience

**Comment by Jenefer-Monroe** [comment]
Hello, my guess is that you are logging in as someone that does not have access to those flows. 
If you installed as Service_Account_User but are logging in as CDT_User, then you wont have access to the flow unless you grant it.

**Comment by cdt2021** [comment]
I'm logging in with the Service account and trying to access the flows as the service account.    I cannot see the flows at all under the service account which is the account I used to install the core components solution.

**Comment by Jenefer-Monroe** [comment]
ok, unfortunately this sounds like an issue with the product itself and not with the starter kit. You will need to reach out to product support.

**Comment by JeneferM-MSFT** [comment]
closing out as no further action for starter kit team

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
