### ISSUE TITLE
[CoE Starter Kit - BUG] Missing Connection References / Fullinvertory ?

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#1616]
### Describe the issue

I have been reviewing the Connection References during a Custom Connector review and the November release is missing loads of connection refrences,  I have an apr 2020 version in another env at the momoment that shows the missing ones, and I rechecked them in PowerShell and they are there, just not collected.

However my November installation might have happened in conjunction with the Tenant bug regarding gathering app and flow information which for certain customer was retruning 404.  

So before saying this  definately a bug,   is it wise to first set the env param "FullInventory" to force a recollection of all information, now the platform bug is fixed.  As the default for this is no, how reliable is this, has it been implemented everywhere?  

If after the next day its not got them, I might have found a bug. 

### Expected Behavior

All the Connection references should have been collected, some have many have not.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin - Sync Template v3 (Flows and Apps)

### Steps To Reproduce

May be difficult to reproduce, asking for help on a refresh first them perhaps some help on tracking down the issue

**Comment by Jenefer-Monroe** [comment]
Can you please where you are expecting to see these that they are missing?

**Comment by binaryjam** [comment]
Hi I have been lokoing at the Apps and the reports that show Connections used by flows and apps.   But as they didnt show any data, then I looked directly in the admin_connection references also.

I am finding flows and apps that list most of the connectors but not others.

further test using XrmToolbox to query more tables, 
I have two COE toolkit envs running in parrallel till I know Oct release is working,
This is a Select count from   admin_connectionreference.

old          new
204857   12961

As these numbers were so low I check ed the admin_flow table counts also, this did not match either, by a lot.

old     new
7069   5845


This tells me that something is very wrong.   So the question regarding how to trigger a full refresh is likely more relevant now.

Does the environment flag of  FullInventory   work,   has it been implemented everywhere,   OR  do we need to delete all the data in the tables,  and how best to do this,   deleteing the environment would not be a good option,  we have weeks of work involved in setting this up so far,   so perhaps  some kind of Truncate script for all the relevant tables ??  

What is the best way to fix bad data in the COE

**Comment by Jenefer-Monroe** [comment]
Sorry for the delay. Full inventory is implemented across the board for inventory. 
Here is how you do a full inventory: 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#incomplete-inventory

**Comment by binaryjam** [comment]
Thanks, I was wondering if it was implemented everywhere, without opening all the flows.

Thx.
