### ISSUE TITLE
[CoE Starter Kit - BUG] Child Admin Sync Logs Parse JSON UserType Mismatch

### ISSUE THREAD

**Issue by dmaloney02** [microsoft/coe-starter-kit#1619]
### Describe the issue

All child audit sync flows are failing with schema errors related to UserType and RecordType data mismatch on the "Parse JSON" step under "Apply to each cluster"

[
  {
    "message": "Invalid type. Expected Integer but got String.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0].RecordType",
    "value": "83",
    "schemaId": "#/items/properties/RecordType",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected Integer but got String.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0].UserType",
    "value": "0",
    "schemaId": "#/items/properties/UserType",
    "errorType": "type",
    "childErrors": []
  }
]

The input Schema shows:
      "UserType": {
        "type": "integer"
      },
      "RecordType": {
        "type": "integer"
      },

Sample Data:
"RecordType":97
"UserType":0

### Expected Behavior

Child Audit logs syncs complete successfully.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Child Admin | Sync Logs

### Steps To Reproduce

run "Admin | Sync Audit Logs" flow

**Comment by manuelap-msft** [comment]
Hello,

We do not have those properties in the JSON schema any longer. I believe you have an unmanaged layer leaving you with stale bits in your flows. Please see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) for how to find and remove these from your flows and apps.

Here is what the Parse JSON Schema should look like after you remove the unmanaged layers:
https://github.com/microsoft/coe-starter-kit/issues/1095#issuecomment-910446704

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
