### ISSUE TITLE
[CoE Starter Kit - BUG] Core in Teams: Add note in emails with app links that they may need to see the app in Teams

### ISSUE THREAD

**Issue by MartinWhiteDAZN** [microsoft/coe-starter-kit#1621]
### Describe the issue

I am using the Teams version of the Developer Compliance Center. When I follow the instructions to share it with a security group most users are asked to start a trial. 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#share-the-app-from-a-dataverse-for-teams-environment

![image](https://user-images.githubusercontent.com/57627519/145995672-8109655f-355f-434d-b79b-3e8a0ee71794.png)

### Expected Behavior

Users can use the DCC without having to sign up to a trial for Power Apps or buy the full licence.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Developer Compliance Centre app

### Steps To Reproduce

Updated to the October release using the Teams version of Core 3.3.
Shared the tables in the Core solution as per the instructions (i.e. give colleagues full access)
Share the app with a security group.
When users in the security group access the DCC they are asked to sign up to a Power Apps trial.

### Anything else?

Is there a way to find out which table or component requires premium access?

**Comment by MartinWhiteDAZN** [comment]
Hi Jenefer,
I did follow the CoE instructions that said to share the table permissions with the security group.
I gave "Colleagues with access" Full Access to the following tables:

  *   PowerApps App
  *   Environment
  *   Flow
  *   PVA
  *   Desktop flow
I gave reference access to table

  *   COE Settings

Also granted full access to a few other tables.

Is there a way to detect where the access is missing?

Kind Regards

***@***.***
Martin White
Office 365 Development Manager
***@***.******@***.***>
Hanover House, Feltham, London, TW13 7BZ

For support with building SharePoint pages please raise a ticket here: Office 365 Help<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=787250db374e5b0020a0532e53990eaa>
For Office 365 process requests please raise a ticket using this link (choose Office 365 Application): SAS ticket<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=82a1fc24db624050a01e9ef7db961937>

**Comment by Jenefer-Monroe** [comment]
I dont think there is a way to find the list unfortunately. But I believe you are missing:

- Maker
- PowerApps Connector
- Power Platform User
- Power Platform User Role

If you assign a test user with a license to the security group, and browse to the app, it will tell you what you are missing yet. 

We will work on this documentation.

**Comment by MartinWhiteDAZN** [comment]
Hi Jenefer,
I have added permissions for these extra tables. It's the same issue, although I will try again in 2 hours in case it takes a while to apply.

One thing I keep finding is that tables I granted access to are reverting back to "None" e.g. today the Flow table is no access to the security group but I double checked it yesterday.

Kind Regards

***@***.***
Martin White
Office 365 Development Manager
***@***.******@***.***>
Hanover House, Feltham, London, TW13 7BZ

For support with building SharePoint pages please raise a ticket here: Office 365 Help<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=787250db374e5b0020a0532e53990eaa>
For Office 365 process requests please raise a ticket using this link (choose Office 365 Application): SAS ticket<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=82a1fc24db624050a01e9ef7db961937>

**Comment by plattasia** [comment]
I got the same error. I have installed the newest version of the D4T Core solution. I then tried opening the app with the same user I imported the solution with. User has E5 licenses and Power Automate per user. But any app I try to open says it requires a "premium" license.  

I have been able to repro this multiple times, in different teams and different tenants (when testing with client).

**Comment by MartinWhiteDAZN** [comment]
Hi Jenefer,
I just carried out a test without CoE.

I created a new Canvas app in a new Team. It just had a label. I shared it with a security group and the users could see the app.
But when I made the app display a dataverse table and I shared that table with the security group, they were asked for a trial.

Could there be an issue with sharing apps in Teams that is not related to CoE?

Kind Regards

***@***.***
Martin White
Office 365 Development Manager
***@***.******@***.***>
Hanover House, Feltham, London, TW13 7BZ

For support with building SharePoint pages please raise a ticket here: Office 365 Help<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=787250db374e5b0020a0532e53990eaa>
For Office 365 process requests please raise a ticket using this link (choose Office 365 Application): SAS ticket<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=82a1fc24db624050a01e9ef7db961937>

From: Martin White
Sent: Wednesday, 15 December 2021 10:53
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Teams version asks for Premium Licence (Issue #1621)

Hi Jenefer,
I have added permissions for these extra tables. It's the same issue, although I will try again in 2 hours in case it takes a while to apply.

One thing I keep finding is that tables I granted access to are reverting back to "None" e.g. today the Flow table is no access to the security group but I double checked it yesterday.

Kind Regards

***@***.***
Martin White
Office 365 Development Manager
***@***.******@***.***>
Hanover House, Feltham, London, TW13 7BZ

For support with building SharePoint pages please raise a ticket here: Office 365 Help<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=787250db374e5b0020a0532e53990eaa>
For Office 365 process requests please raise a ticket using this link (choose Office 365 Application): SAS ticket<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=82a1fc24db624050a01e9ef7db961937>

**Comment by Jenefer-Monroe** [comment]
Hello yes I am repro-ing without CoE as well. Please do create a support ticket. I will continue to try and narrow and push as well.

**Comment by MartinWhiteDAZN** [comment]
I'm not working for a few days but will raise a support ticket upon my return, unless you find a solution in the meantime.

Kind Regards

***@***.***
Martin White
Office 365 Development Manager
***@***.******@***.***>
Hanover House, Feltham, London, TW13 7BZ

For support with building SharePoint pages please raise a ticket here: Office 365 Help<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=787250db374e5b0020a0532e53990eaa>
For Office 365 process requests please raise a ticket using this link (choose Office 365 Application): SAS ticket<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=82a1fc24db624050a01e9ef7db961937>

**Comment by Jenefer-Monroe** [comment]
Hello. I just want to validate how you are sharing the app with the user. It turns out this is designed only for use within teams so they have to access it as shown here:

Apps > Built by your colleagues > Select the app
![image](https://user-images.githubusercontent.com/89584709/146583125-21cd4e5c-846c-4b89-9ed3-acd6c7ce8afd.png)

This is how it works, I had been incorrect. 
Please let me know if this works for you.

**Comment by MartinWhiteDAZN** [comment]
Hi Jenefer,
I've been using the app's direct URL.

My users can't see the app under "Built by your Colleagues".
If they had to do it this way, would it mean the link in the email that asks them to fill out DCC wouldn't work? It sends a link to the DCC app with the querystring &appName=00a95777-3cae-4a...  so it opens the app in question.
To add confusion I have a test user with an F3 licence and it can open the links directly.

Kind Regards

***@***.***
Martin White
Office 365 Development Manager
***@***.******@***.***>
Hanover House, Feltham, London, TW13 7BZ

For support with building SharePoint pages please raise a ticket here: Office 365 Help<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=787250db374e5b0020a0532e53990eaa>
For Office 365 process requests please raise a ticket using this link (choose Office 365 Application): SAS ticket<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=82a1fc24db624050a01e9ef7db961937>

**Comment by Jenefer-Monroe** [comment]
You are correct, good catch. We'll have to think on that.

**Comment by Jenefer-Monroe** [comment]
we are adding an env variable to make is clear in Flow if the install is in teams or prod
Then in the flows that send links to apps to non-admin personas, we will add a note telling them they may need to see the app in the context of teams. 
Thanks for posting and helping us get this cleaner for people.

**Comment by MartinWhiteDAZN** [comment]
Hi Jenefer,
I have done some more testing and it does seem to work via Teams and not with a direct URL.
I'm surprised this issue hasn't been raised before. The Teams version has been available for eight months.

Making the app a tenant app will make it slightly easier for users (although we wouldn't want it automatically pinned). April Dunnam's video is very helpful... https://youtu.be/D9ISGVB4I3A?t=518

**Comment by MartinWhiteDAZN** [comment]
WOW! 
I have just discovered why my test user can access the DCC directly with a URL and not using Teams.
Everyone in my organisation who can access the DCC directly has set up a Developer Plan environment! 
https://powerapps.microsoft.com/en-au/developerplan/

The Dev Plan creates an environment and grants free access to Dataverse and premium features. But it clearly expands into other environments. I had one of my users create a Dev Plan and as soon as she did, she was able to access DCC directly.

It's a relief to know why some people can access it differently (even though it's still a problem for the majority).
