### ISSUE TITLE
[CoE Starter Kit - BUG] Suggested update to Flow details view on Power Platform Admin View app

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#1622]
### Describe the issue

On the Power Platform Admin View app, can we get the the Flow Details to look just like the App Details and have the **Flow Deleted** and **Flow Deleted on** fields to automatically appear when looking up a flow? 
What Flows view currently shows
![image](https://user-images.githubusercontent.com/95765970/146014307-ce9c68d6-f2f9-44b6-aaf9-85419e7bb8b2.png)

What the App view currently shows
![image](https://user-images.githubusercontent.com/95765970/146014352-a86deec7-9978-4bbd-8246-245eb4b11715.png)

### Expected Behavior

When I go to the Flow details, I hope to see the **Flow Deleted** and **Flow Deleted on** fields.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

1. Go to **make.powerapps.com**
2. Click **Apps**
3. Click **Power Platform Admin View**
4. Click **Flows** in left hand navigation
5. Click one of the flows that appears
6. On General tab hope to see **Flow Deleted** and **Flow Deleted On** fields

**Comment by manuelap-msft** [comment]
Well spotted difference! I have now added those fields in our development environment and these will go live with the January release: 
![image](https://user-images.githubusercontent.com/55705669/146774348-c19c8de6-729e-43bf-9af8-251e24eb09e3.png)

**Comment by AUTigers16** [comment]
Thank you!

**Comment by Jenefer-Monroe** [comment]
holding open to resolve with ship of January.

**Comment by mikefactorial** [comment]
@AUTigers16 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
