### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 fails at 'Check if lecacy' action

### ISSUE THREAD

**Issue by gprowlands1** [microsoft/coe-starter-kit#1624]
### Describe the issue

above flow is failing to succeed at the "Check if Legacy" action, specifically the Get Maker action within.

{
  "error": {
    "code": "WorkflowTriggerIsNotEnabled",
    "message": "Could not execute workflow 'xxxxxx' trigger 'manual' with state 'Disabled': trigger is not enabled."
  }
}

![image](https://user-images.githubusercontent.com/96133366/146033079-d7769297-b883-49ec-990d-06b4d1096dae.png)

### Expected Behavior

a successful flow run. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

Admin | Sync Template v3
Run

**Comment by Jenefer-Monroe** [comment]
In the future, you need to show the error message in order for us to assist. 
If its the same issue, then you did not turn on the child flow. 
The action Get Maker is a call to a child flow. It calls this helper: HELPER - Maker Check
Here is the full list of child flows that need enabled (list is for Dec release). 
https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

**Comment by gprowlands1** [comment]
@Jenefer-Monroe  thank you for the comment. Worked a treat and apologies for the lack of error message. New here.

**Comment by Jenefer-Monroe** [comment]
Glad to hear it worked
