### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Legacy Report - Power Apps Adoption Page - Not Showing Monthly New Users

### ISSUE THREAD

**Issue by TreyPoint** [microsoft/coe-starter-kit#1625]
### Describe the issue

When accessing the Power BI report and on the Power Apps Adoption page shows a data card that should show "Monthly New Users".  However, this shows "(Blank).  As I investigated further I noticed that the card was using a Measure titled "MOM New User" but this measure doesn't have a formula in it.  I have repro this in Oct, Nov, and December.
![Legacy_Dec_Release_PowerApps_Adoption_MoM_Measure](https://user-images.githubusercontent.com/7740876/146042272-80b0b204-ed35-48a8-9ee0-f0ea83bff306.png)
![Legacy_Nov_Release_PowerApps_Adoption_MoM_Measure](https://user-images.githubusercontent.com/7740876/146042283-8c57791b-b377-4772-a310-d0db7f23ed6c.png)
![Legacy_Oct_Release_PowerApps_Adoption_MoM_Measure](https://user-images.githubusercontent.com/7740876/146042287-8875d456-2c60-4795-8e18-0e07da301614.png)

### Expected Behavior

Ability to see MoM New Users data and have the measure actually containing a formula

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Power BI Report

### Steps To Reproduce

Download Legacy Version of Oct, Nov, and Dec and open the Power Apps Adoption page, locate the data card "Monthly New Users".  This will highlight the column that is attached to this data card which is a measure "MOM New User", click on the column in the Fields pane and this will open the formula bar.

### Anything else?

I noticed another measure titled "NewUsers" with a formula of: 

_"NewUsers = COUNTROWS(filter('Audit Log', 'Audit Log'[IsCurrentMonth] = "Yes"))"_

This measure points to the "IsCurrentMonth" measure with the formula:

_IsCurrentMonth = 
    IF (
        YEAR ( 'Audit Log'[admin_creationtime].[Date] ) = YEAR ( TODAY () )
            && MONTH ( 'Audit Log'[admin_creationtime].[Date] ) = MONTH ( TODAY () ),
        "Yes",
        "No"
    )_
    
I dont understand why their is a column named "NewUsers" but this measure never pulls in user data.  Just current month information and nothing related to "NewUsers" - what is this used for?

**Comment by manuelap-msft** [comment]
Hello,

looks like a formula here dropped out as we shipped it! Could you try pasting the below in the MOM New User measure and see if that returns your expected data? Unfortunatley I don't have new users in my demo tenant so can't sufficiently test this.

```
MOM New User = VAR currentUsers = VALUES('Audit Log'[admin_userupn])
VAR currentDate = MAX('Audit Log'[admin_creationtime])

VAR pastUsers = CALCULATETABLE(VALUES('Audit Log'[admin_userupn]), 
    ALL('Audit Log'[admin_creationtime].[Month],'Audit Log'[admin_creationtime].[MonthNo],'Audit Log'[admin_creationtime].[Year])
    , 'Audit Log'[admin_creationtime]<currentDate)

VAR newUsers = EXCEPT(currentUsers,pastUsers)

RETURN COUNTROWS(newUsers)
```

**Comment by mikefactorial** [comment]
@TreyPoint This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
