### ISSUE TITLE
[CoE Starter Kit - BUG] Customer Connector report in Center of Excellenct BI Dashboard mostly empty

### ISSUE THREAD

**Issue by AdnanJusicMS** [microsoft/coe-starter-kit#1627]
### Describe the issue

Hi all, i have implemented the COE core component (v. 3.12) and I have run all flows, whiche are mentioned in the configuration guide. But the reports shows me only the custom connector (the count of the connectors are correct), but not the two tables in the left and right buttom are empty (blue marked in the screenshot).

![Inked234](https://user-images.githubusercontent.com/96141055/146063495-d774b970-e2a3-43fd-8e31-032b53ff9ebd.jpg)

I hope you have a good hint for me? :)

Thanks a lot in advance!

Kind regards,

Adnan

### Expected Behavior

The Customer Connector should also show data in the complete report not only on the chart on the top of the report.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Custom Connectors report in the CoE BI Dashboard

### Steps To Reproduce

1. Open CoE BI Dashboard
2. Navigate to the Custom Connectors report
3. Check the table at the left and right bottom in the report.

**Comment by Jenefer-Monroe** [comment]
So you are saying you expect to see 1 Custom Connector, as shown in the tile. But you dont see it listed. Is that what you are saying? 

It looks like you have the report filtered to a single environment, is that the environment which contains the custom connector?

**Comment by AdnanJusicMS** [comment]
Hi Jenefer,

I am able to see the one customer connector on the first charter (starting from the top of the report), but the two charts under the first one aren’t showing data?

This is my question, why in this two charts are no data populate. Is there any way to troubleshoot them? I have also try to select through all environment filters and all the other filters (because I have recognized in other reports, they are empty with the first launch, but changing the filter values are showing data in the reports.

Thanks a lot!

Kind regards,

Adnan

**Comment by manuelap-msft** [comment]
Hello,

the two visuals below show if the custom connector is used in apps or flows. Some custom connectors may exist in an environment but are not used in apps or flows. Can you confirm if your custom connector is used in apps or flows? 

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out due to lack of resonse
