### ISSUE TITLE
[CoE Starter Kit - BUG] App Share report empty (+ Refresh App Share report Feature Request)

### ISSUE THREAD

**Issue by AdnanJusicMS** [microsoft/coe-starter-kit#1628]
### Describe the issue

Hi all,

i have implemented the COE core component (v 3.12) and the "App Shares" report in the Center of Excellence BI Dasboard is empty. So the charts are showing nothing, the refiners/filters are populated with maker and environment data.

![fkf](https://user-images.githubusercontent.com/96141055/146064711-ecbc7258-4bb9-436f-a50a-a92e9278b1b1.png)

Is there any guideline for troubleshooting in this case? To check some flows or tables, etc.?

Thanks a lot in advance!

Kind regards,

Adnan

### Expected Behavior

The report shouldn't be empty.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Custom Connectors report in the CoE BI Dashboard

### Steps To Reproduce

1. Open CoE BI Dashboard
2. Navigate to the Aps Shares report
3. Check if the report is empty.

**Comment by manuelap-msft** [comment]
Hello,

is this installed in a demo/test tenant and do you have apps that are shared with more than 5 users? This report filters to look at only apps shared with more than 5 users, you can remove that filter from the Filter pane to see if it brings up data then (e.g. apps shared with 1/2 users).

Manuela

**Comment by AdnanJusicMS** [comment]
Hi Manuela,

thanks a lot for the fast reply. I will check our suggestion – Yes it is in my demo tenant, but my customers face the same issue in production, as I know.

But anyway I will check this in my demo tenant. Does this rule also count for groups, e.g. if I share the app with a office 365 group (and in the group are less or more then 5 users), how this will be treated?

Thanks!

Kind regards,

Adnan

**Comment by manuelap-msft** [comment]
This report only looks at individual users an app is shared with, groups are not taken into account! Looking at it, I think this report page could do with a bit of a refresh which I'll target for our January release to look at both users and groups! But let me know if your customers continues to see issues here.

**Comment by AdnanJusicMS** [comment]
Hi Manuela, thank a lot for your reply and all the helpful informations. I will check this with my customer, if the issues still exists with apps which are fulfil theconditions to be displayed, but arn't displayed.

Kind regards and Happy holidays,

Adnan

**Comment by mikefactorial** [comment]
@AdnanJusicMS This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by AdnanJusicMS** [comment]
> @AdnanJusicMS This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

Thanks @mikefactorial for the information! Kind regards, Adnan
