### ISSUE TITLE
[CoE Starter Kit - BUG] SyncFlowErrors  Flow Run Url incorrect

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#1634]
### Describe the issue

In the Log to SyncFlow Errors it is a concatenation of the flowEnvironment variable and some static text.

However these flow runs do not take me to the actual flow run.  This is because my flows, as per the installation docs, run from withinside the  Solution, so the actual flow run is very different.

Here is what was logged. Vs the Actual flow run.

https://emea.flow.microsoft.com/manage/environments/xxxxxxxx-087a-4475-88f4-d22dab833795/environments4a10f265-087a-4475-88f4-d22dab833795/flows/f90802d3-0ae6-83fa-0bb7-df49d3188089/runs/08585621238821762542711171739CU143/

https://emea.flow.microsoft.com/manage/environments/xxxxxxxx-087a-4475-88f4-d22dab833795/solutions/ae111cf9-e713-4e23-8f8f-b0cff8ab6887/flows/d8a5436a-71d9-4c20-8d9a-4d8029a955ad/runs/08585621238821762542711171739CU143

### Expected Behavior

The Flow run lik should go to the correct place for the environment it is running in. So if n solution then solution. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

Ensure flows are running from within the Core Solution.

Have an Error.

Click the Flow run log from the Admin  CommandCentre app.

**Comment by Jenefer-Monroe** [comment]
The sync flows error URLs as written work for us, at least from my testing. So there seems to be something specific going on for you or in a flow that rarely fails for us.

This component of the url seems to be the actual problem: **_environments4a10f265-087a-4475-88f4-d22dab833795/_**

Can you please:
- validate that if you remove this from your first URL, it works
- tell me which flow this is so I can make sure there isnt a bug at that spot, writing this extra bad content.

**Comment by binaryjam** [comment]
Removing the Mangled environment Worked.  

The flow writing this is Admin Z Sync Template v2 (Flows).

![image](https://user-images.githubusercontent.com/7352864/146219654-0cbd9d62-75f6-4f2b-a7c5-d93f4b5bed9e.png)

I checked my Env Var its Set to   (no trailing slash) (perhaps this is a problem but doesnt make sense)
https://emea.flow.microsoft.com/manage/environments

concat(variables('flowEnvironment'), workflow()?['tags']['environmentName'], '/flows/', workflow()?['name'], '/runs/', workflow()?['run']['name'])

I did a test in the and the "almost" same code, returned a diffrent url again
https://emea.flow.microsoft.com/manage/environments4a10f265-087a-4475-88f4-d22dab833795/flows/8b259cd2-74cb-4427-bd7b-2ba5af0d9980/runs/08585620218207469931380755412CU166

This is what I would expect, and this demonstrates that we really need the "/"  on the end of the environment variable.

But it doesnt explain why in the real flow I'm getting that weirdness url.

Perhaps the best thing to start with , is fix the Env Variable in my tenant.   Hope for another error and check it tomorrow, Im Uk time.

**Comment by Jenefer-Monroe** [comment]
We have been on the flow title **_Admin | Sync Template v3 (Flows)_** for at least a year now in the starter kit, rather than v2. So I'm not sure how you are still using the v2 version when on 3.13.  Can you please investigate? We are not able to support v2 at this time. 

That said, it appears it is your env var that is wrong. 

Per the documentation [env vars](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-environment-variables) it appears you need an ending slash

> The URL used by flow for your region. Here are examples:
> For a US environment: https://us.flow.microsoft.com/manage/environments/
> For a Canadian environment: https://canada.flow.microsoft.com/manage/environments/
> For an EMEA environment: **_https://emea.flow.microsoft.com/manage/environments/_**
> For a GCC environment: https://gov.flow.microsoft.us/manage/environments/
> For a GCC High environment: https://high.flow.microsoft.us/manage/environments
> For a DoD environment: https://flow.appsplatform.us/manage/environments/
> If your region is not listed here, navigate to flow.microsoft.com and copy the URL the page directs to from the browser.

**Comment by binaryjam** [comment]
Apologies its v3 that was a typo.

I have fixed the trailing slash.

Will see what happens tomorrow if I have any errors.

Do you want to close this and I could reopen another or I will defiantly be checking about 9am gmt time to confirm.

**Comment by Jenefer-Monroe** [comment]
oh good :) I was wondering how the heck you were still on v2!

We can leave this open, no problem. And we can just check in tomorrow.

**Comment by manuelap-msft** [comment]
Please make sure to turn on / off the Sync Flow errors flow after changing the enviornment variable. There's some caching that flow does and it won't fetch the latest value unless you turn on/off the flow :)

**Comment by Jenefer-Monroe** [comment]
Good catch Manuela!
