### ISSUE TITLE
1478 - Unable to upgrade CoE Starterkit components

### ISSUE THREAD

**Issue by LakshmanChand** [microsoft/coe-starter-kit#1636]
Hi,
I have created a ticket 1478 in the past. My issue is still not resolved and we also reached out to Microsoft for help.

I have installed CoE starter kit on one of our environments. The current version of Core components is 2.0.10 and compliance and report components is just 1.14. The latest available version of core components is 3.19. I am trying to upgrade the solution from 2.0.10 to 3.18 and got the error. So, then i tried to import previous versions of core components and i just found the earliest available version from previous versions is 2.1.7. 

Looks like  there was a custom connector Office365 Management API with Audit logs components which is now moved to Core Components. May be in our last update of core components, the custom connector got deleted . The version which we last upgraded was from February 2021. I do not have March and April versions at https://github.com/microsoft/coe-starter-kit/releases. 

When we are trying to upgrade/delete the solution, it is looking for the custom connector and as it is not there, the upgrade/update/delete of solution throws us below error.

Error:
Connector import: FAILURE: {"error":{"code":"ApiNotFoundForPatch","message":"The custom connector could not be found for the update operation."}}.

Please help.

**Comment by Jenefer-Monroe** [comment]
Hello, 

Please note the CoE Starter Kit is an unsupported set of templates: https://docs.microsoft.com/power-platform/guidance/coe/feedback-support 

We do not have a support team that can help resolve issues, and support is provided on best endevaours without SLA via GitHub. 

Given the age of your envt before upgrade, it will be difficult for us to assist. We will look into your issue, but at the moment can not provide a timeline.

Thank you for your patience

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid with a kit this old, we are not able to assist with upgrade. If you are unable to move forward you will need to create a clean environment and re-install. 
If all you are using us for is inventory and audit logs, meaning you arent using any of our other data fields to augment the data, then you can follow the steps outlines here: #1507
