### ISSUE TITLE
[CoE Starter Kit - BUG] Error when turning on CLEANUP - Admin Sync Template v3 (Check Deleted)

### ISSUE THREAD

**Issue by osbornecc** [microsoft/coe-starter-kit#1637]
### Describe the issue

After updating to the December release, most of the flows were turned off.  When we edited the first flow in our list to update its recurrence to our schedule, saving threw this error:

Request to XRM API failed with error: 'Message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message '**The pagination policy of workflow run action 'Get_Environments' of type 'OpenApiConnection' at line '1' and column '1525' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."**}}". Code: 0x80060467 InnerError: '.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by osbornecc** [comment]
I'm wondering if the issue is GCC (our tenant) vs Commercial.  I was able to get the flow to save by changing the Pagination settings of each step that complained.

![image](https://user-images.githubusercontent.com/50427725/146266487-ca28a457-eb15-4635-a5f4-ece58cf067b1.png)

The default from the solution is 100000 but the system says the max value is 5000.  So I updated them all to 5000.

Full disclosure:  I have not edited the other flows yet, just that one.  I expect others to have the same issue.
Thanks.

**Comment by manuelap-msft** [comment]
Hello,

this is due to you having an insufficient license to run the flows. 

Please see:
Power Automate performance profiles https://docs.microsoft.com/en-us/power-automate/limits-and-config#performance-profiles
Pagination limits per profile https://docs.microsoft.com/en-us/power-automate/limits-and-config#concurrency-looping-and-debatching-limits
And hence our limitation https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#trial-licenses

**Comment by osbornecc** [comment]
Hi there,
That's interesting.  We haven't run into this issue before (last version of Core was 3.18).  Would we have seen this issue with that version?

**Comment by manuelap-msft** [comment]
Yes, we have always had high pagination settings to support larger tenants. Note that it's the performance profile of the flow owner that is enforced here, so perhaps someone else with an appropriate license imported the solution previoulsy (and solution import sets the ownership of the flow to that account)

**Comment by osbornecc** [comment]
Oh, that makes sense!  I have multiple accounts and the one that originally imported/owned the CoE has a beefed up Power Automate license because I'm testing something.  The account we switched to own the CoE is more like a "normal" user and has our "default" Plan 1 version of the profile.  

By this profile having the pagination limit of 5000 will that potentially cause issues when the flows run?  As in, missing data, runtime errors, etc.

Thank you.

**Comment by manuelap-msft** [comment]
Yes, it will cause multiple issues unfortunately
- it might lead to not all data being gathered, but flows looking successful 
- it introduces unmanaged layers to the flow which can lead to upgrade issues; and you would have to remove the unmanaged layer on every upgrade and re-apply the changes to the pagination limits 
- every action in every flow titled Admin | Sync Flow v3 (...) and CLEANUP - Admin Sync ... has the pagination limit set like that. so you would have to go through every single flow and update every action.

**Comment by osbornecc** [comment]
Hmm, OK.  We understand the unmanaged layers because we update the flow recurrences normally anyway.  But bullet 1 is concerning.  Thanks for the info.  I think we have enough to understand what happened.
