### ISSUE TITLE
Admin Synch Template v3 not completing

### ISSUE THREAD

**Issue by plakerl** [microsoft/coe-starter-kit#1639]
### Describe the issue

I have recently installed the Center of Excellence - Core Components version 3.19.   All seemed to ok until I attempt to run the Admin Synch Template v3 flow.  Couple of issues.  First thing is that it runs on average for 4-5 hrs.  It will then fail on the step Store enironments in the CoE CDS entity.  ActionFailed: An action failed. No dependent actions succeeded.  

![12-16-2021 10-17-11 AM](https://user-images.githubusercontent.com/27173205/146398306-a0f710d0-c73d-4d15-b74e-f78d5a13ab5f.jpg)
 

### Expected Behavior

This flow retrieves the environments in your tenant by using List Environments as Admin, and creates or updates a record for each environment in the Dataverse Environment table. Running this flow will also trigger the rest of the sync flows indirectly by updating the environment records in the Dataverse instance.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin-Synch Template v3

### Steps To Reproduce

![12-16-2021 10-17-11 AM](https://user-images.githubusercontent.com/27173205/146399564-97a013b6-f76f-4034-9647-1c6d032ee9f9.jpg)

**Comment by Jenefer-Monroe** [comment]
Hello, the time spent in this flow is mostly in the very first step **_Delay Inventory_**, where we wait a random amount of time to begin the work, in order to disperse the calls to the MSFT Dataverse clouds with the calls from all the tenants using the CoE

**Comment by Jenefer-Monroe** [comment]
In order to assist with your failure, you will need to dive into the apply to each, and find the exact point of failure

Browse to Next failed as shown here
![image](https://user-images.githubusercontent.com/89584709/146407276-cfb2fcbc-dffb-4bb7-89ba-1d7e2729cdd1.png)

And dive in until you find an uncut error, as shown here, where the things following it do not run
![image](https://user-images.githubusercontent.com/89584709/146407485-c3371b3b-e795-409c-a1e2-bd5b6636e86b.png)

Then open that action and get the error message

**Comment by plakerl** [comment]
Thank you so much for quick reply.  Here is what I am seeing on the Get Environment task.   The second error is on the Get Maker Task.


{
  "error": {
    "code": "0x80040217",
    "message": "admin_environment With Id = 01e3ff6d-b258-4a29-9430-cb1af4236f07 Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "de75d156-f65c-ec11-8f8f-000d3a1a7e93",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "1f9a6df3-acba-470e-b589-ef91f6c0e0ab",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_environment With Id = 01e3ff6d-b258-4a29-9430-cb1af4236f07 Does Not Exist"
  }
}


{
  "error": {
    "code": "WorkflowTriggerIsNotEnabled",
    "message": "Could not execute workflow '7ecf431a-9535-062c-707b-8efafd1b701a' trigger 'manual' with state 'Disabled': trigger is not enabled."
  }

**Comment by Jenefer-Monroe** [comment]
That first failure is a caught error. As you can see right below the red marker that it failed you see me setting a variable, something like 'isNew" to true. This is how we detect if the object (environment in this case) is already in the inventory or not. We try to get it, if it exists we move on and skip setting that variable, else we set that isNew to true. 

The second failure states that it is trying to call a workflow (child flow) that isnt turned on. 
Please see here for the list of child flows that need turned on https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

**Comment by plakerl** [comment]
ok.  so it is the fact that I might might of missed turning on a child flow.  Looking at that now.  First glance is I have the correct ones set to on.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
