### ISSUE TITLE
[CoE Starter Kit - BUG] Manually added connectors in Admin | Sync Template v3 (Connectors) flow

### ISSUE THREAD

**Issue by xmihux** [microsoft/coe-starter-kit#1641]
### Describe the issue

Some connectors are not pulled from the API, so they are added manually: HTTP, HTTP Webhook and Spatial Services connector. Below are 2 small issues with manually added connector records.

1) 'When a HTTP request is received' connector is missing - it should be added there as well.

2) Connectors are added with incorrect IDs: admin_http, admin_httpwebhook, shared_microsoftspatialservices. Correct IDs of these connectors are:

- Http
- HttpWebhook
- /providers/Microsoft.PowerApps/apis/shared_microsoftspatialservices
- HttpRequestReceived (for the missing connector from point 1)

These are the correct IDs shown if you get a DLP policy e.g. with PowerShell. 
While it might not be that important for the current CoE version, it will be problematic when creating custom solutions based on CoE. Example: using the Connectors table to manage DLP policies - incorrect IDs from the table can't be used to set a DLP policy.

### Expected Behavior

1) 'When a HTTP request is received' is added to the connectors table
2) Manually added connectors have correct IDs assigned

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, we just noticed another issue in this space so your bug is well timed.

**Comment by Jenefer-Monroe** [comment]
Deleteting old versions of these in **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_**
![image](https://user-images.githubusercontent.com/89584709/147773052-5715fcfc-eaec-47cb-9163-074cb048047e.png)

**Comment by Jenefer-Monroe** [comment]
Resolved for January in the connectors sync flow
![image](https://user-images.githubusercontent.com/89584709/147775198-efbadbd2-3b13-4462-be62-c66b479eecb2.png)
![image](https://user-images.githubusercontent.com/89584709/147775503-72d3e247-278d-466c-baad-e4886b390403.png)

**Comment by mikefactorial** [comment]
@xmihux This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
