### ISSUE TITLE
[CoE Starter Kit - BUG] App Developer Compliance Center fails to launch selected app

### ISSUE THREAD

**Issue by txh57** [microsoft/coe-starter-kit#1647]
### Describe the issue

When you click on the _App Settings_ or _Launch_ item on Screen _'App Details Screen'_ the Launch command fails.
In my opinion typos in script **'App Detail Screen'.galAppOptions.Icon4.OnSelect** are the reason for it.

**Original script**
![image](https://user-images.githubusercontent.com/25150539/146606645-721d7cbf-bf14-425e-8785-ed8a328cb53a.png)

**Changed script**
![image](https://user-images.githubusercontent.com/25150539/146606685-91982af5-1501-44cc-89e4-d7b29a2a8d87.png)

With the script changes shown above, the Launch command executes without errors.

### Expected Behavior

- When you click the _App Settings_ item the Details Screen of the selected app should be opened.
- When you click the _Launch_ item the selected app should be played.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Developer Compliance Center

### Steps To Reproduce

1. Play app _Developer Compliance Center_
2. Select an Canvas App by clicking the _Details_ button (App Detail Screens opens)
3. Click the _App Settings_ button -> Launch fails
4. Click the _Launch_ button ->Launch fails

**Comment by txh57** [comment]
The same behavior is also found in app **App Catalog** of solution Core Components.
Here it's in script **btn_editbookmarks.OnSelect** of screen **c_appdetail**

**Current script**
![image](https://user-images.githubusercontent.com/25150539/146612561-907f1295-f4c5-41d9-ae7b-12858b5d50ef.png)

**Changed script**
![image](https://user-images.githubusercontent.com/25150539/146612765-6cd54eb5-fbab-4d8e-84fa-8262370552dd.png)

**Comment by Jenefer-Monroe** [comment]
The issue is that your environment variables are missing the end slash. 
Please see https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables

**Comment by txh57** [comment]
You are absolutely right: sometimes you can't see the forest for the trees.

**Comment by Jenefer-Monroe** [comment]
There are a lot of trees in this forest, so understandable :) 

Please note that environment variables cache, so you'll need to restart any flows that use this env var in order to see your update. 

thanks for using CoE!
