### ISSUE TITLE
[CoE Starter Kit - BUG] Teams Environments that contains only Virtual Agents get deleted after 90 days

### ISSUE THREAD

**Issue by michastauffer** [microsoft/coe-starter-kit#1648]
### Describe the issue

The Flow Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments deletes unused team environments after 90 days. it only checks if there are any apps or flows in this environment, but not checks if there are any PVA.

### Expected Behavior

If a Teams environment contains only a Chatbot, and now apps or flows, it should not get deleted.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments

### Steps To Reproduce

1. create a new teams
2. create a virtual chatbot in this team
3. wait for 90 days (or change created date in coe table environments)
4. run the mentioned workflow

**Comment by manuelap-msft** [comment]
Hello,

this is a document limitation, as chatbots in Microsoft Teams are not discoverable for the CoE (no API/connector is able to retrieve chatbot inventory for the CoE to know about these bots), see:

![image](https://user-images.githubusercontent.com/55705669/146768004-f2549dbc-840d-4cbf-adae-4add2c671db8.png)

Links:
- https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#microsoft-teams-admin--weekly-clean-up-of-microsoft-teams-environments
- https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#sync-flow-limitations-for-developer-and-microsoft-team-environments
