### ISSUE TITLE
[CoE Starter Kit] Documentation fix: Helper flows need to indicate order and clearer instructions regarding Run only users

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#1650]
### Describe the issue

When trying to enable HELPER - ObjectOperations and HELPER - CanvasAppOperations child flows we receive following errors. 

![image](https://user-images.githubusercontent.com/8307644/146754519-255fc9e5-bd4f-4a97-a46c-369d3a507211.png)

![image](https://user-images.githubusercontent.com/8307644/146754543-b15b5698-8983-467a-b5ab-05bc226761f0.png)

CanvasAppOperations flow has an action to run "Maker Check" which need to be enabled first

<img width="408" alt="image" src="https://user-images.githubusercontent.com/8307644/146756006-b6db7dca-cff2-4866-879f-0ff843d119f7.png">

ObjectOperations flow has an action to run CanvasAppOperations which need to be enabled first.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/8307644/146754127-cb5e9713-555d-4d28-9a00-a2dd6d16a897.png">

So the correct order should be mentioned in the documentation 

Another thing is that none of these flows have unmanaged layer, so maybe the statement to remove unmanaged layer can be removed from the documentation. Or is there a change that these flows could have unmanaged layers? https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows

<img width="421" alt="image" src="https://user-images.githubusercontent.com/8307644/146752722-1fc366bd-4a90-450f-8764-95d8ff0032c6.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

HELPER - ObjectOperations and HELPER - CanvasAppOperations

**Comment by mikefactorial** [comment]
@petepuu This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
