### ISSUE TITLE
[CoE Starter Kit - BUG] D4T: Need way to exempt environments from compliance and archival flows

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1654]
### Describe the issue

We have it like this in the Model Driven App for regular Core but forgot to add to the canvas version in Core for Teams
![image](https://user-images.githubusercontent.com/89584709/146812126-26e6c68a-814d-4ce2-8d27-2a2af1814f64.png)

### Expected Behavior

A way to do this exemption in the canvas version of Power Platform Admin View 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Local fixed Jan
![image](https://user-images.githubusercontent.com/89584709/146816767-ebc9384e-4581-4ba5-9206-1ee10494d974.png)

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by TodoroskiAco** [comment]
Is it possible to exempt all the environments in our tenant from all of the compliance flows at once and then include just the environments that I need to be compliant?

**Comment by Jenefer-Monroe** [comment]
We dont have such an offering, our default is to have compliance on. We arent staffed to assist with customizations but I can point you in the correct direction here. 

You could write a quick flow one off  to set everything as excused. It would look like: 
- list all environments in CoE > update row to mark as excused 

And then add another flow to run in your CoE envt that says
- listen for new envt in CoE > mark it as excused 

I hope that helps!
