### ISSUE TITLE
[CoE Starter Kit - BUG] Email formatting: header has big white space for some users

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1655]
### Describe the issue

Some people's mails now look like this, though it looks fine for others, and when viewed in a phone. 
![image](https://user-images.githubusercontent.com/89584709/146822343-bd9960ca-07f5-4e08-a80a-5658d5bf7229.png)

### Expected Behavior

Header to look nice

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Sync Flow Errors)

**Comment by Jenefer-Monroe** [comment]
Removed the image from the header as its being blocked by some folks settings. 
Admins can find an approved image to put in the headers. Else it will just be an empty row and look fine. 

<head> <style>  body {     background-color: #ffffff;     font-family: Segoe UI;     text-align: left; }  #content {     border: 1px solid #742774;     background-color: #ffffff;     width: 650px;     margin-bottom: 50px;     display: inline-block; }  #logo {     margin-left: 0px;     margin-top: 0px;     width: 60px;     height: 12px; }  #header {     font-size: 24px;     margin-left: 0px;     margin-top: 0px;     margin-bottom: 0px; }  #ribbon {     background-color: #742774; }  #ribbonContent {     font-size: 20px;     padding-left: 30px;     padding-top: 10px;     padding-bottom: 20px;     color: white;     width: 100%;     padding-right: 10px; }  #message > {     font-size: 14px;     padding-left: 60px;     padding-right: 60px;     padding-top: 20px;     padding-bottom: 40px; }  #footer > {     font-size: 12px;     background-color: #cfcfcf;     height: 40px;     padding-top: 15px;     padding-left: 40px;     padding-bottom: 20px; }  #form {     width: 100%;     border-collapse: collapse; }  #app {     width: 60%;     font-size: 12px; }  .label {     color: #5f5f5f }  table {     border-collapse: collapse;     width: 100%; }  th, td {     padding: 8px;     text-align: left;     border-bottom: 1px solid #ddd; }  </style> </head> <body> <div id='content'> <table id='form'> <tr><td><img id='logo' src=''></td></tr> <tr><td><p id='header'>Power Platform</p></td></tr> <tr id='ribbon'><td> <tr><td></td> </tr></table></td></tr> <tr id='message'><td>

**Comment by mikefactorial** [comment]
@Jenefer-Monroe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
