### ISSUE TITLE
Custom Flow Run Index log, seperate from the PowerAutomate log

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#1659]
When I have lots of environments and I am trying to isolate problems, discrepencies in data, with the COE data 
trying to track down bugs,  trying to find the flow run for the affected environments is near impossible with every new environment, I have over 70 now.

If every COE Toolkit flow, recorded its Starttime, its name etc,  and a link to the real flow run, BUT also included some key specific info that could help further identify it for analysis.   E.g.  The current environment its running for.
It would need to cleanup this flow index log, sure, Keep it for a few days Max, so a cleanup flow checks the param but maxes out at 5 perhaps.    A new page in the Admin Console app to seperate them by flow name and list the entries from the tables.

We shouldnt need this, but the platform doesnt cater for large scale data driven flow runs, just expects folk to know what flow ran when, hence the reduced info for a flow run interface.

I have asked the Twitter account, where to request this change so that a Flow could Tag its own flow run and present this info, but I doubt that will ever happen.   If it did then the COE could tag each flow run, which would be much better solution and everyone could benefit,   but thats the product team to review and upgrade us.

**Comment by binaryjam** [comment]
Thinking about this, is there a way to get the logs from the dataverse itself and just include the trigger info,   then we just need an app, in case the product team dont do this.

**Comment by Jenefer-Monroe** [comment]
Hi there. Thanks for posting. I'm having trouble following you. Can you perhaps share a picture of what you are asking for? I think this is about the sync flow failure mail, but I'm not entirely sure.

**Comment by binaryjam** [comment]
To give an example.

In trying to track down problems in a COE flow (caused by MS bug)  Each day in the  Sync Apps flow.  You can see all the Flow runs.  This is what the platform provide.  Its inadequate.  I have over 70 flow runs per day to search though each one to locate the flow run that was for that one specific environment that Im intersted it.

I would love the Product Team to make changes to PowerAutomate, which is where the improvement really belongs.  Were they to add more info to the flow run, like say the trigger values, into those flow runs we could diagnose issue faster.

I cant see them doing it, unless your team have some influence here :-)  

With that in mind and no sight of the PRoduct team making life easier.   Having the ability to view more info in the list of flow runs would help.

If it was possible to Make a COE app, that used a Custom Connector to access the flow runs directly and produce a better flow run list, this would be good, if it were possible to get the trigger info as well as just the run details in a App.

Alternatively, if its not possible to get this info, then If Each Flow in the toolkit,  made its own entry an a table that detailed its start time, trigger info  or other handly info, as well as a link to the flow run itself.  A corresponding app to list this would help, this app could filter by flow, or environment to.

Sometimes the Flow Errors are not triggered, its not an error sometimes, we still need to look through the flow run in question to see what it actually did,  its just finding them in those cases also.

**Comment by Jenefer-Monroe** [comment]
We cannot get the flow runs for people into the CoE. We did have a CC started but the data collected for it was way too large and then we found that the upcoming BYOD feature was going to offer it for us from the product itself, so that will be available next year sometime. 

We do store errors from the CoE inventory flows in the Sync Flow Errors. Is there additional information for those failures that might help? 

If what you are looking for is to see a run of (Apps) for example, for some envt, then you can dirty that envt record and it will trigger the (Apps) flow to run for it. Does that help?

**Comment by binaryjam** [comment]
Thank Jenefer, it was a long shot and wondered how useful it would be to others as well, I can dirty the env like you say, never tried that but makes sense.

The platform really should do something like this.

**Comment by Jenefer-Monroe** [comment]
thanks for posting!
