### ISSUE TITLE
[CoE Starter Kit - BUG] Missing environments

### ISSUE THREAD

**Issue by mansohrstrom** [microsoft/coe-starter-kit#1660]
### Describe the issue

We have roughly 320 environments but I can't see recently created environments in admin_environments table. When looking at the run history of "Admin | Sync Template v3" I can see that the "Get Environments" action only return between 25 and 65 environments per run. It's different between each run in the history.

### Expected Behavior

Would expect it to return all environments every time. When creating a new flow and adding a "List environments as admin" action with same API version and expand property settings all 320 environments are listed.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

Described above

### Anything else?

We installed it in July 21 and upgraded to 3.19 a couple of weeks ago. Do we need to do full inventory? Can't see the variable being used in the flow. Thanks!

**Comment by Jenefer-Monroe** [comment]
Full inventory is not necessary for Environments. We do a full inventory from the environment POV every time

**Comment by Jenefer-Monroe** [comment]
When you say "expand property settings", do you mean the pagination settings? 
Can you confirm this is the pagination setting you see in **_Admin | Sync Template v3_** are as shown here? 
![image](https://user-images.githubusercontent.com/89584709/146948023-f8154ea7-120e-425d-b513-7b5c1106095c.png)

**Comment by Jenefer-Monroe** [comment]
And can you confirm that the identity running the flow / associted with that action is a PPAdmin? 
Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)

**Comment by mansohrstrom** [comment]
Thanks for your prompt answer!

Bam! We have role assignments timing out after 4 hours and I didn't know this for this user. I thought it had a permanent role. That explains it. Case closed.

**Comment by Jenefer-Monroe** [comment]
Yeah to mysteries being solved :)
