### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI dashboard shows blank app display name and creator name

### ISSUE THREAD

**Issue by AdnanJusicMS** [microsoft/coe-starter-kit#1662]
### Describe the issue

Hi all, 

one of my customer faces a behavior on App archive report and the Cloud flow report in the Center of Excellence BI Dasboard. The customer founds few entries where column "Creator" is blank and in few entries the column "Display name" of the app is blank. Any ideas what the cause of this behavior could be?

I will forward the link to this issue also to my customer, if any additional questions rise up, maybe the customer will interact in this thread directly.

Thanks a lot in advance!

Kind regards,

Adnan

### Expected Behavior

App Archive should show Display Name for all apps in the report.
Cloud flow Archive should show "Creator" for all flows in the report.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Center of Excellence BI Dasboard

### Steps To Reproduce

1. Open Center of Excellence BI Dasboard
2. Navigate to App Archive
3. Check the column "Display Name"

1. Open Center of Excellence BI Dasboard
2. Navigate to Cloud flow archive
3. Check the column "Creator"

**Comment by manuelap-msft** [comment]
Hello,

we will need a little bit more details than that to help!

1. Creator can be blank if the app maker has left the organization. This means the app or flow is orphaned.
2. Can you run Get-AdminPowerApp with the App ID https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerapp?view=pa-ps-latest to get the meta-data and see what it shows there. Does it show a display name? If you look up the maker in AAD do they still exist?

**Comment by manuelap-msft** [comment]
Closing out issues with no further aciton on the CoE kit team or no feedback received. Please let us know if you continue to experience issues.
