### ISSUE TITLE
[CoE Starter Kit - BUG] Active app are shown in archive app report.

### ISSUE THREAD

**Issue by AdnanJusicMS** [microsoft/coe-starter-kit#1664]
### Describe the issue

Hi all,

one of my customer reports that active apps are shown in the app archive report in the Center of Excellence BI Dasboard. This active apps had a las run e.g. 10th Dec 2021, the report was checked on 21th Dec 2021. Any idea what the cause could be?

I will forward the link to this issue also to my customer, if any additional questions rise up, maybe the customer will interact in this thread directly.

Thanks a lot in advance!

Kind regards,

Adnan

### Expected Behavior

Active apps shouldn't be displayed in the app archive report.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Center of Excellence BI Dasboard

### Steps To Reproduce

1. Navigate to the Center of Excellence BI Dasboard.
2. Open App Archive report.
3. You should not see apps, which runs 10-14 days ago.

**Comment by manuelap-msft** [comment]
There is no condition on the App Archive report that filters out apps that are currently in use. We calculate an archive score: https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern#app-and-flow-archive and apps on that page are shown based on their archive score, but no apps are actually filtered out. E.g. if they have an active tenant, they may not have apps with high archive scores and then all apps would always show. 

As with all other CoE Starter Kit components, the goal is to provide a **starting** point for implementing an organizations administration and governance policies for the Power Platform. The CoE starter Kit does not aim to be a turnkey solution that fullfills the needs of all customers and there is no one size fits all approach when it comes to Power Platform adoption. Customers are encouraged to extend and customize the starter kit to make it fit their processes. A filter to exclude apps that have recently been launched can easily be added to this page.

**Comment by AdnanJusicMS** [comment]
Hi Manuela, thank you very much for taking time to sharing all the informations. I have forwarded it to the customer.
Kind regards, Adnan

**Comment by manuelap-msft** [comment]
Great, thank you! A key reason why we do not filter out unused apps by default is that many customers to not have the Audit Log solution set up and thus don't know when the app was last launched. This is often because Audit Log access requires more elevated privilges then Power Platform Admin, and many of the admins we work with don't have access to it. 

If you want to add this filter, you could add a Filter to this page > include the created on field from the Audit Log table and set it to the appropriate relative date!

**Comment by AdnanJusicMS** [comment]
Hi Manuela, thanks a lot for your reply. You wrote in your last reply something regarding unused apps, but our problem is, that "used apps", apps which had there last run time a couple of days/weeks ago, are showing up in the App Archive report. Do you mean unused oder used apps? :) Sorry for the ask!

**Comment by manuelap-msft** [comment]
Oh yes, I meant used! Sorry was doing too many things at once :)

**Comment by AdnanJusicMS** [comment]
Thanks a lot, Manuela! I can imaging it, espacally before the holidays. 
Thanks for all the help and support. 
Happys holidays and all the best in the new year!
