### ISSUE TITLE
[CoE Starter Kit - Improvement] Use select statements in clean up flows to improve run time and data consumption

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1665]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/1649

<div type='discussions-op-text'>

<sup>Originally posted by **redleo85** December 20, 2021</sup>
Hi,
we have spend some time optimizing the sync flows and we would like to share what we have done, hoping it will be implemented in the solution. For some flows we managed to decrease running time by up to 97% and data consumption by 98%.

**Issue (general):**
If the tenant is large, the sync flows take an excessive amount of time, consuming many API requests and data. Especially the high data consumption of the CLEANUP HELPER flows is an issue. This resulted in our flows running for a very long time, because they were throttled (e.g. CLEANUP HELPER (Flows) ran for up to 21 days, Admin | Sync (Flows) ran for 4 days). This made it impossible to have up-to-date data.

### CLEANUP HELPER
**Issue**
Analyzing the CLEANUP HELPER there were 2 main issues (high data consumption and high API requests). 
1. The flow iterates over all flows in the tenant. For this it filters the current flow from the list of all flows (see screenshot). The issue is that the filter function gets passed the whole list of flows which includes the flow definition and other data which is not used. Data consumption growths exponentially, because data for all flows gets pass in a loop which runs over all flows. This way the highest 50GB data consumption limit is passed if there are more than ~4500 flows in an environment.
![image](https://user-images.githubusercontent.com/9613325/146738910-8802326b-336d-41a2-8204-3ad9146581a3.png)
2. The second issue is the loop iterating over all flows. Concurrency is turned off for this flow, so even if each item only takes a few seconds it may take several days in large tenants.

**Solution**
1. Add a "Select" action before the loop, which selects only the name of the flow. Then filter the result of the Select function within the loop, instead of the result of the "List flows" action. **For us this reduced data consumption of the flow 98%.**
2. Enable concurrency for the loop and set it to 50. For us this reduced running time further 75%.
**In total these two changes decreased running time from 21 days to 15 hours for CLEANUP HELPER (Flows).**
Since the CLEANUP HELPER flow are structurally the same, we think all of them can benefit from this change.
![image](https://user-images.githubusercontent.com/9613325/146741231-b527d8eb-c75e-4cf0-a407-19ef3e829ccc.png)

We hope this makes the starter kit a better solution especially for large enterprises.

We did test these solutions before implementation, but of course we would be happy for some feedback. Maybe there was a specific reason we missed why these solutions were not implemented before.

Best Regards
</div>

**Comment by Jenefer-Monroe** [comment]
regarding cleanup helpers:
- Select - I did not know that about how filters work. THANKS!
- Concurrency - good catch, we used to have a variable in there before we split up to heleprs, but i forgot to turn on concurrency when it was removed. 

I have this part local fixed for Jan in the flow helper and our test tenant default went from ~8 minutes to 1 minute. Stamping out and testing.

AMAZING SUGGESTION! :)

**Comment by Jenefer-Monroe** [comment]
Same select fix applies in driving flow: CLEANUP - Admin | Sync Template v3 (Check Deleted)
![image](https://user-images.githubusercontent.com/89584709/147010915-7e67e545-48be-416f-b5ec-51e1b814e458.png)

**Comment by Jenefer-Monroe** [comment]
Moving other issue to a seperate bug. I know we considered doing that when we first moved away from full inventory and decided not to. But now I can't recall what that reasoning was. It could be that the reason is gone now that we've come alot further, or it could be that I'm just not remembering. I'll think on it some more. 
See #1668

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
