### ISSUE TITLE
Missing Cloud Flow Usage Report

### ISSUE THREAD

**Issue by AdnanJusicMS** [microsoft/coe-starter-kit#1666]
**Is your feature request related to a problem? Please describe.**
Yes, customer wants to track api calls, flow runs, etc. in one report.

**Describe the solution you'd like**
It would be helpful to have a report, like we have it for App usage, also to have it for cloud flows. This will enable CoE users to track the api calls or runs per flow. Maybe at the moment it isn't possible based on the transition phase, but it would be good to have it in place anyway.

**Describe alternatives you've considered**
Power Platform Admin Center Analytics (Microsoft OOF analytices).

**Additional context**
No additional context.

**Comment by manuelap-msft** [comment]
Please see: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#monitoring-cloud-flow-runs

Monitoring cloud flow runs is currently not possible with the CoE starter kit, as there is no connector or API available for us to get cloud flow run data. 

As soon as a supported way of getting this information will become available, we will evaluate how to include it in the CoE Starter Kit.

Thanks for the feedback. Closing this out as it's a documented and known limitation.

**Comment by ValentinMaz** [comment]
Hello manuelap-msf, just came across this thread - what about the Power Automate API? (api.flow.microsoft.com):

- the below Get Request returns the list of the last Flow Runs for a specific Flow: https://api.flow.microsoft.com/providers/Microsoft.ProcessSimple/environments/{environmentID}/flows/{FlowID}/runs?api-version=2016-11-01

- this API can be called from Power Automate with the HTTP with Azure AD connector (see attached)
![image](https://user-images.githubusercontent.com/39318272/171017692-666cd5a9-819c-422a-a4ac-844419fafac9.png)

- could it not be used in the existing in the "Admin | Sync Template v3 (Flows)" Flow to browse through each Flow and populate a Flow Runs table accordingly?

**Comment by manuelap-msft** [comment]
This is not a publicly/officially supported or documented API, so we can not take a dependency on it as it may change without notice.

**Comment by ValentinMaz** [comment]
Thanks for your quick response Manuela! This also answers our next question which would have been whether it was worth it for us to implement it internally...
