### ISSUE TITLE
[CoE Starter Kit - BUG] Perf Improvement Suggestion - Filter before you check for updates to reduce number you have to iterate

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1668]
### Admin | Sync Template v3
**Issue**
Every day all flows within the tenant are being synced with the Starter Kit database. The longest running flow "Admin | Sync Template v3 (Flows)" ran for 4 days. This resulted in multiple instances running simultaneously and the flow consuming around 400.000 API requests daily. The main issue seemed to be that the flow checks all flows within the tenant, even if they were not updated for a long time.

**Solution**
We added an additional filter action before the main loop to only get those flows which were updates less than 7 days ago. Since this flow runs daily, theoretically it should be possible to only get the flows that were updated in the last one or two days. **For us, this resulted in a running time decrease of 95% for "Admin | Sync Template v3 (Flows)".**
Here, too, sync flows for other artifacts could also benefit from this change.
**Note:** This is the main crawler. So for new Starter Kit installations there will need to be a check to ensure all artifacts (flows) are crawled initially.

![image](https://user-images.githubusercontent.com/9613325/146742925-e72642c2-6498-407a-ab9a-35fd598f1f99.png)

We hope this makes the starter kit a better solution especially for large enterprises.

We did test these solutions before implementation, but of course we would be happy for some feedback. Maybe there was a specific reason we missed why these solutions were not implemented before.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

sync flows

### Anything else?

Spun off from #1665

**Comment by Jenefer-Monroe** [comment]
I can't remember the reason we didnt do this initially but I know there was a reason. 
This for us to consider before implementing:
- any impact of things not marked <7 days (or whatever we chose)
- impact on full inventory runs
- impact on items new to inventory

**Comment by Jenefer-Monroe** [comment]
This appears doable by using a complex filter statement like this: 
@or(greater(item()?['properties/createdTime'], body('Get_past_time')), greater(item()?['properties/lastModifiedTime'], body('Get_past_time')))

And then the Get-Past-Time action can go back either 1 month or 120 months if full inventory. 

Few things to think through yet and it will be a big change so need to be careful here.

**Comment by Jenefer-Monroe** [comment]
Need to update canvas sharing cleanup flow to be a little more verbose due to 
![image](https://user-images.githubusercontent.com/89584709/148278817-4e765000-f7ae-4c76-80ba-2aba7f6232e8.png)

**Comment by Jenefer-Monroe** [comment]
actually since most of the calls to the object were obscured by the apply-to-each, there wasnt much work here after all. Awesome! 
Have not yet local fixed the fix to update sharing's clean up flow, but otherwise LF and running a validation suite. Will send a PR to a partner for testing.

**Comment by Jenefer-Monroe** [comment]
ok we have these values now being populated as part of the pre-existing **_CLEANUP HELPER - Power Apps User Shared With_**
![image](https://user-images.githubusercontent.com/89584709/148834677-ead14fa5-5c81-41ef-8ff6-b3dc326af50a.png)

Believe this work is now local fixed for Feb and have a PR in testing with a partner as well as in our test tenant.

GREAT SUGGESTION!

**Comment by manuelap-msft** [comment]
This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
