### ISSUE TITLE
[CoE Starter Kit] Upload file to Dataflow directly

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1671]
There's a new option for Dataflows to upload a file directly vs providing a path
![image](https://user-images.githubusercontent.com/55705669/147124996-de0c6b67-4c8e-4abe-b2b7-1fc1553eda07.png)

Evaluate if this is an option for the Dataflow part of Nurture to see if we can reduce setup steps here.

**Comment by Jenefer-Monroe** [comment]
Closing this one out as we are removing the dataflow from Nurture
