### ISSUE TITLE
[CoE Starter Kit - BUG] Flow: Request Orphaned Objects Reassigned (Parent) - Error when "User blocked the conversation with the bot"

### ISSUE THREAD

**Issue by hernan-ramirez** [microsoft/coe-starter-kit#1675]
### Describe the issue

This flow:
'Request Orphaned Objects Reassigned (Parent)'

Failed in the Action:
'Send_Intro_Card_to_Manager' 

When:
'ConversationBlockedByUser","message":"User blocked the conversation with the bot.'

Error details:
Request to the Bot framework failed with error: '{"error":{"code":"ConversationBlockedByUser","message":"User blocked the conversation with the bot."}}'.

![image](https://user-images.githubusercontent.com/18430953/147244158-b531f949-3fd9-41f9-91c7-fea2df264b56.png)
![image](https://user-images.githubusercontent.com/18430953/147244281-cfe41d73-dbdc-4539-a6c3-ab36ac12f8ae.png)

### Expected Behavior

The flow should continue with the successful end status and report on which users took that attitude.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

**Comment by manuelap-msft** [comment]
Hello,

I'm afraid this is out of our control. Every user can block bot conversations in Microsoft Teams, and we can not detect if this has happened:
![image](https://user-images.githubusercontent.com/55705669/147254168-871d9b8a-ba5c-47c1-a156-287a313a7d03.png)

If this is something your users frequently do, you may have to either ask them to unblock bot conversations or implement error handling here to send an email instead. 

Thank you
Manuela

**Comment by hernan-ramirez** [comment]
Yes, but the flow can end in a successful state if a last "terminate"
action is added, independent of any internal action in apply to each
failure caused by a user decision.

**Comment by Jenefer-Monroe** [comment]
This would be considered as a silent failure by other users. So we do not want to turn this state into a pass which indicates that the communication with that user succeeded. 
We have a few issues for this flow stacked up now. Will hold and think on it and tackle them together.

**Comment by hernan-ramirez** [comment]
Thank you Jenefer! the important thing is that the flow is not switched off
after so many failures. I understand that it is also wrong that the
activity fires with an error due to the blocking, rather it would have to
be a warning

**Comment by Jenefer-Monroe** [comment]
ok so we will have the parent flow fail, but at the end, after its gone through the child. 
This way there is still communication about the orphans to managers, and there is a flow failure indicating that communication with managers about orphans is not working. 

This will allow us to send a mail to the manager:
![image](https://user-images.githubusercontent.com/89584709/147695865-49d4e0b3-bf70-4e48-9cce-80ed5ee94afb.png)

And the admin:
![image](https://user-images.githubusercontent.com/89584709/147695906-ee2aaa4f-4de5-49ac-a32d-4954ef84373c.png)

And then fail at the end as shown here:
![image](https://user-images.githubusercontent.com/89584709/147704354-3da4de25-84f8-4446-9651-4320a653f449.png)

**Comment by Jenefer-Monroe** [comment]
local fixed Jan

**Comment by mikefactorial** [comment]
@hernan-ramirez This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
