### ISSUE TITLE
[CoE Starter Kit - BUG] Flow: Request Orphaned Objects Reassigned (Child) - Error - When names contain double quotes

### ISSUE THREAD

**Issue by hernan-ramirez** [microsoft/coe-starter-kit#1678]
### Describe the issue

The flow:
Request Orphaned Objects Reassigned (Child)

In the action:
Send_Table_For_Response

Show error:
The specified Teams flowbot adaptive card request is missing or invalid. The tracking Id is '{0}'. ---> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered

The action "Compose" show scaped doble quote like:
"MAURO \"MALATO\" DA MANTOVA"
But the AdaptiveCard isn't

![image](https://user-images.githubusercontent.com/18430953/147245178-06f47972-16f4-4380-95fd-38bc5d1a7fe8.png)
![image](https://user-images.githubusercontent.com/18430953/147245226-ec41c33e-6e80-4253-8cba-0d031d720ad8.png)
![image](https://user-images.githubusercontent.com/18430953/147245582-40a4dd28-d59b-459a-8c0a-059088fcda06.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

**Comment by Jenefer-Monroe** [comment]
Can you please test to see if this fixes it for you? 

Replace this **_Display Name_**
![image](https://user-images.githubusercontent.com/89584709/147475350-5ac23094-4cd9-49fe-9c46-ec245b9708a7.png)

With 
`replace(items('Apply_to_each_of_their_flows')?['admin_displayname'], '"', '_')`
![image](https://user-images.githubusercontent.com/89584709/147475505-d6c5eb65-7b5d-490e-90f8-05879fb32902.png)

**Comment by Jenefer-Monroe** [comment]
I made this change locally for both apps and flows for Jan. Please let me know if it resolves it for you or not.

**Comment by hernan-ramirez** [comment]
Yes, this work perfect, will we have this improvement for the next version?

**Comment by Jenefer-Monroe** [comment]
Yep, its local fixed and will ship with January bits. 
Thanks for confirming!

**Comment by hernan-ramirez** [comment]
Thank you very much Jenefer!!

**Comment by mikefactorial** [comment]
@hernan-ramirez This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
