### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by jorgemorenog** [microsoft/coe-starter-kit#1684]
### Describe the issue

The _Admin | Sync Audit Logs_ still takes the environment variables **default** values.

I changed both to new values:

- TimeInterval-Unit. From _Hour_ to _Minute_
- TimeInterval-Interval. From _1_ to _15_

After that change, the flow took default values again. I have just changed also the default values in case for the next run.

Thanks a lot.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

**Comment by Jenefer-Monroe** [comment]
Hello, this is product behavior. Power Automate caches env variables until the flow is reset, so you need to turn the flow off and back on to see the new values. 
We are redoing some documentation for January and will have this better documented.

**Comment by jorgemorenog** [comment]
Thanks a lot, Jenefer. I tried again following your instructions and it works now great.

I will take into account that behavior for other flows. It would be nice to change that aspect. Especially for complex flows that are not easily turned off and on.

From my side, this issue can be closed. Thanks!!
