### ISSUE TITLE
[CoE Starter Kit - BUG] Last iteration member in sync audit logs is not well formed

### ISSUE THREAD

**Issue by jorgemorenog** [microsoft/coe-starter-kit#1685]
### Describe the issue

It seems that in the _Admin | Sync Audit Logs_, the last iteration it is not properly formed.

The interval that it is generated to call the child flow is extremely longer than expected. That provokes that there is always a child flow sending an email about the need of reducing the chunk size.

In the following example, the chunk size is 5 minutes. And the start and end-time are very different:

![Error](https://user-images.githubusercontent.com/10724478/147688276-c97555f4-11fd-4600-b80f-6081624223db.PNG)

And it only occurs in the last member of the iteration :)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

**Comment by Jenefer-Monroe** [comment]
Unfortunately, per the documentation, we cannot scale at this point to offering assistance getting this to work, but I can tell you that other tenants have gotten the 5 minute chunks to work. 
You have to work with all the env vars offered and in particular I believe its the TimeSegment-CountLimit one you need to work with.

**Comment by jorgemorenog** [comment]
I see no problems with the chunk limits. It works fine.

Digging into the flow's logic, I believe it is more related to the condition before the final iteration. As far I understand, it seems it adds the last chunk with an interval of a day. Therefore, for that child flow, it would be a lot of records to obtain.

Here is the image:
![Error2](https://user-images.githubusercontent.com/10724478/147690333-9c7d002c-c622-4487-bbae-2bff79200265.PNG)

In the condition:
- startTime: 2021-12-**28**T22:07:46.1477050Z
- Past Time: 2021-12-**29**T17:06:46.1633249Z

In the append action, the same values. 

So, for almost the child flow, everything's fine. But for the last one, the added interval is excessive. Maybe with a change in the logic, it would be fixed.

What is the purpose of that condition? I don't get the point of that element there.

Thanks.

**Comment by Jenefer-Monroe** [comment]
The point of this loop is grab any little left overs after it has run through all the chunks. 
It looks like you covered only 5 hours with your chunks and so this is grabbing the rest of the 24 hours.

**Comment by Jenefer-Monroe** [comment]
Is this table helpful? 



| StartTime-Interval | StartTime-Unit | TimeInterval-Interval | TimeInterval-Unit | TimeSegment-CountLimit | Expectation                                                                                                                                               |
|--------------------|----------------|-----------------------|-------------------|------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|
|          1         |       day      |           1           |        hour       |           60           | Will   create 24 child flows, which is within the limit of 60.<br>Each child flow will do the work to pull back 1 hour of logs from the past   24 hours |
|          2         |       day      |           1           |        hour       |           60           | Will   create 48 child flows, which is within the limit of 60.<br>Each child flow will do the work to pull back 1 hour of logs from the past   48 hours |
|          1         |       day      |           5           |       minute      |           300          | Will   create 288 child flows, which is within the limit of 300.<br>Each child flow will do the work to pull back 5 minutes of from the past 24   hours |
|          1         |       day      |           15          |       minute      |           100          | Will create 96 child flows, which is within the limit of 100.<br>Each child flow will do the work to pull back 15 minutes of from the past   24 hours   |

**Comment by Jenefer-Monroe** [comment]
We've added this table to the upcoming Jan release of the documentation

**Comment by mikefactorial** [comment]
@jorgemorenog This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by jorgemorenog** [comment]
@Jenefer-Monroe @mikefactorial thanks for the info. I will review the update and the suggested configuration to reach a solution.

**Comment by jorgemorenog** [comment]
I can confirm that well configured it works like hell. Thanks a lot!
