### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by tbernstein2368** [microsoft/coe-starter-kit#1690]
### Describe the issue

I am getting the attached error when I am attempting to perform step 2 (Start Subscription to audit log content) [here](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content)

![2021-12-29 15_11_49-Power Apps and 12 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/54820410/147709803-78da55ba-bbfd-4e2d-acbf-3bb382f0123f.jpg)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

None

### Anything else?

I can be reached on tbernste@lasd.org or via phone 323-526-5639 or 818-612-8319

**Comment by manuelap-msft** [comment]
Hello,

it looks like you may have put the Application Client ID in incorrectly - from the error message it looks like you entered the GUID + Name, when only the GUID is required.
![image](https://user-images.githubusercontent.com/55705669/147746850-79953333-b4c6-428d-9a9b-c37aee705ae0.png)

In step 3 here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector make sure that for Client ID you only paste in the GUID from here:
![image](https://user-images.githubusercontent.com/55705669/147747000-65533683-37ac-45d4-a71e-d28da57cc826.png)

**Comment by Jenefer-Monroe** [comment]
Note also, from the name, it sounds like you might be using the wrong App. There are two optional apps made for the starter kit. 

1) Audit Logs: [Create an Azure AD app registration for the Office 365 Management API](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#create-an-azure-ad-app-registration-for-the-office-365-management-api)
2) Command Center: [(Optional) Create an Azure AD app registration to connect to Microsoft Graph](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#optional-create-an-azure-ad-app-registration-to-connect-to-microsoft-graph)

It sounds like you might be trying to use the Command Center app for the audit logs connector.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by tbernstein2368** [comment]
Problem is still there Jennifer. Worked on it for an hour or so last week following your guidance but still having issues. Figured I'd reach out after the holiday weekend 

Todd

Todd Bernstein

**Comment by tbernstein2368** [comment]
Issue still there. Please keep open. 

Todd Bernstein

**Comment by Jenefer-Monroe** [comment]
Happy to leave open for now for your tracking, but there is nothing our team can do to assist here. The data entered for the object is incorrect.

**Comment by manuelap-msft** [comment]
Hello @tbernstein2368, is there any further help we can provide you with here? Have you managed to connect now? Please provide us with an update so we can either help or close this issue. Thank you.

**Comment by tbernstein2368** [comment]
Yes. I was stuck on some other projects last week but I'm still having issues doing what you last recommended. I need to document the error I'm getting and reply back. I hope to do this by Wednesday 

Todd Bernstein

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
