### ISSUE TITLE
[CoE Starter Kit - BUG] Nurture Solution- Unable to upgrade/update or Stage for upgrade

### ISSUE THREAD

**Issue by njclosed101** [microsoft/coe-starter-kit#1702]
### Describe the issue

When attempting to run through the upgrade process in my Dev or CoE environment, I am unable to upgrade/Update or stage for upgrade the nurture component (December 2021). The following message is received when upgrading:

Solution "Center of Excellence - Nurture Components" failed to import: ImportAsHolding Exception during StageAndUpgrade

And when updating or stage for upgrade: 

Solution "Center of Excellence - Nurture Components" failed to import is returned 

### Expected Behavior

Expected the upgrade to be successful from version 2.4 to 2.6

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Nurture solution

### Steps To Reproduce

1. CoE environment (Development environment or Production)
2. Solutions
3. Import -> selected latest Nurture solution from GitHub: https://github.com/microsoft/coe-starter-kit/releases
4. Next
5. Advanced Settings: (Choose either upgrade/stage for upgrade or Update
6. Import fails after running

**Comment by Jenefer-Monroe** [comment]
Hello. Are you a GCC, or other non-commercial tenant? If so please use the solution at the bottom of #888 as you are blocked by a product issue. 
If not, then please note that we do sometimes see Nurture fail to upgrade on first try but succeed on subsequent attempts. Another product issue which we are unable to resolve but which eventually resolves itself after multiple attempts. 
(Note I am assuming that you have already upgraded Core)

**Comment by njclosed101** [comment]
Hi Jenefer - Thanks for the response!  When attempting to upgrade the Core the same error occurs.

**Comment by Jenefer-Monroe** [comment]
Can you please share a picture of your solutions so that I can understand what versions you have in play?

**Comment by njclosed101** [comment]
![image](https://user-images.githubusercontent.com/97109036/148080733-2dc319ed-9eec-4c39-97f0-af5668dd6b32.png)

**Comment by Jenefer-Monroe** [comment]
I see now, you have both June 2021 and Oct 2021 versions of Core installed. And are now trying to upgrade to Dec. 
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state, but you may need to start with a clean install and migrate any customized data.
