### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Detail Request V3 Flow - not returning canvas apps for default environment

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1704]
### Describe the issue

When I run the flow Admin | Compliance detail request v3 the following error occurs:
under the "Apply to each envt App" step in the condition "Get Assignee apps",  for the Default environment it errors with the message: 
Request to Azure Resource Manager failed with error: '{"error":{"code":"ActionRepetitionNotFound","message":"The specified repetition '000002-000000' of workflow action 'Get_Assignee_apps' is not found."}}'.
![image](https://user-images.githubusercontent.com/17124284/148092483-12ee3657-4841-4171-ba7f-fe9e88137bb3.png)
This subsequently causes the same error for different actions below this step.
![image](https://user-images.githubusercontent.com/17124284/148092724-ba5c3c3e-5144-4ca7-813a-24386323a332.png)
The problem is that no compliance audit is carried out for the Default environment. 
All of the other environments run through successfully.

### Expected Behavior

I expect the flow to run through all of the environments as I have set the environment variable Exclude Default environment from Compliance Request flows to the default value of No.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin | Compliance detail request v3

**Comment by Jenefer-Monroe** [comment]
Was anything returned? Is it actually looping any apps? I believe that is an error we see for skipped actions. And I see that we had an error in the filter that I would not expect it to return any apps for default

**Comment by Jenefer-Monroe** [comment]
local fixed Jan

**Comment by mikefactorial** [comment]
@medicineshow This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
