### ISSUE TITLE
[CoE Starter Kit - BUG] Issue with getting environment via Admin - Sync Template v3

### ISSUE THREAD

**Issue by yingying96** [microsoft/coe-starter-kit#1707]
### Describe the issue

Hello!

We are having an issue regarding the flow - Admin - Sync Template v3 where the action to get environment fails even though the environment seems to be there. Added in screenshots for your reference.

![image](https://user-images.githubusercontent.com/19566726/148149635-16bf5ae1-f33e-43e5-87a2-51e422f9d3a2.png)

![image](https://user-images.githubusercontent.com/19566726/148150016-8e6ceb8a-cc16-4ecd-8600-e78060d54a76.png)

### Expected Behavior

The flow should run successfully?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin - Sync Template v3

### Steps To Reproduce

1. Imported the solution to default environment, similar to our test tenancy by following the documentation
2. Turn on the respective flows
3. Wait for the sync template to run

**Comment by Jenefer-Monroe** [comment]
Hello, as an aside, we do not recommend you install the CoE in default environment, we recommend you install in a dedicated environment.

**Comment by Jenefer-Monroe** [comment]
What do you mean by "environment seems to be there"? Do you mean in the inventory already? Or exists in the tenant? 

This call is how we check to see if the object is already in the environment. If its new to inventory then this call will fail (expected) and be caught by the next call, if you zoom out, is this failure caught?

**Comment by yingying96** [comment]
It exists in the tenant. I'm not too sure if the object is already in the inventory. But i think the cause seems to be "Get Maker"

{
  "error": {
    "code": "WorkflowTriggerIsNotEnabled",
    "message": "Could not execute workflow '9bac990e-4a88-848a-f79d-f51bc224a3f8' trigger 'manual' with state 'Disabled': trigger is not enabled."
  }
}

![image](https://user-images.githubusercontent.com/19566726/148342498-0a46ddfd-3ee7-4c48-b9f1-5834173288f7.png)


![image](https://user-images.githubusercontent.com/19566726/148342356-4fb7fd78-80ed-4ddb-bdd4-43f6f00b2bbc.png)

**Comment by yingying96** [comment]
If we install in a production environment, will it have display data from other environments e.g. default in the dashboard? Currently it's empty. 

![image](https://user-images.githubusercontent.com/19566726/148342662-420f3caf-ada0-4edb-acb6-3f2ef9d269c9.png)

**Comment by Jenefer-Monroe** [comment]
Please look at the flows and you will see that none of them can pass without this child flows turned on, and therefore you have no inventory collected and no data to show in that app. 
As long as you have ensured you have all the [pre-reqs](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites) and followed all the setup steps, which includes turning on all these flows, then you will see the data populate.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
