### ISSUE TITLE
[CoE Starter Kit - BUG]  - Get Environment

### ISSUE THREAD

**Issue by Kaikapitaen** [microsoft/coe-starter-kit#1709]
### Describe the issue

hey at all, do you can help me?
Running Workflows with CoE 3.19, Core will display following messages:
Get Environment
![image](https://user-images.githubusercontent.com/57182309/148191043-df102baa-2cc0-455e-884e-5fda7b8951cd.png)

### Expected Behavior

see pic

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin Sync Template v3

### Anything else?

v

**Comment by Jenefer-Monroe** [comment]
Hello. That is a caught failure. As you can see from the red arrow going down to a succeeded call to set a variable. 
This is how we check to see if the object is already in the inventory, we say "get envt X from inventory", if that fails, we say "ok envt X is not yet in inventory"
So this is not a failure. Did the flow fail? If so you will need to find the point at which it fails without being caught.

**Comment by Jenefer-Monroe** [comment]
This is most certainly due to your other issue around the Maker child flow. 
closing out as no further action for starter kit team
