### ISSUE TITLE
[CoE Starter Kit - BUG] - Get Maker

### ISSUE THREAD

**Issue by Kaikapitaen** [microsoft/coe-starter-kit#1710]
### Describe the issue

hey at all, do you can help me?
Running Workflows with CoE 3.19, Core will display following messages:
Get Maker
![image](https://user-images.githubusercontent.com/57182309/148191530-0e248520-4a29-464a-bff7-b175bb976e3a.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin Sync Template v3

**Comment by Jenefer-Monroe** [comment]
Hello, according to that error message you did not turn on the child flow. 
Please note that the starter kit uses many child flows and these need turned on in order for the flows that call them to pass. 
Here are the child flows needed for Core as an example: [Update and turn on child flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
