### ISSUE TITLE
[ALM Accelerator - BUG]: Flows don't activate for connection references

### ISSUE THREAD

**Issue by mdpc-nnit** [microsoft/coe-starter-kit#1712]
### Describe the issue

When the deploy pipeline tries to activate flows, it throws the warning:
`A specified connection reference was not found in the target environment. Verify your deployment configuration and try again.`
even though the connection references are linked correctly to connections during deployment.

I narrowed the issue down to [line 109](https://github.com/microsoft/coe-alm-accelerator-templates/blob/76f5c7a2ea743d364b5daeff6f9345609ff65dbd/Pipelines/Templates/activate-flows.yml#L109):
                        `if($connections.Count -gt 0) {`
The $connections.Count is $null even if  $connections is a PSCustomObject. I have run 
`$connections | get-member`
and don't see any Count property.
All the other places, where .Count is called in the same script, it seems to return an integer correctly.

**Lazy fix:**
Change line 109 to 
 `if($connections) {`
I don't know if this has any unforseen implications.

### Expected Behavior

When the deployment settings are configured correctly, flows should activate during the activate-flows.yml

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

pipeline templates commit: d7946ffd89c8e915a5b8c5cf2211ff60125f9268

### Anything else?

Sorry if this is also a duplicate - I tried to look for it XD

I am very curious if you guys encounter the same issue. I have reproduced it in two tenants.

**Comment by mikefactorial** [comment]
@mdpc-nnit not dupe :) Haven't seen this one before. I'll take a look at what's going on.

**Comment by mdpc-nnit** [comment]
Now I encounter a similar but apparently unrelated issue:
It fails on line [119](https://github.com/microsoft/coe-alm-accelerator-templates/blob/76f5c7a2ea743d364b5daeff6f9345609ff65dbd/Pipelines/Templates/activate-flows.yml#L119)

`if($workflow.clientdata.Contains($connectionRefConfig.LogicalName) -and $workflow.statecode -ne "Activated"){` 

for some non-cloud flows because $workflow.clientdata is $null, so we cannot call the Contains method. a workaround is to avoid using a method:

`if(($workflow.clientdata -like "*$($connectionRefConfig.LogicalName)*") -and ($workflow.statecode -ne "Activated")){`

At some point the script checked for the property "Modern flow". Why was this removed?

Should I open an issue with this as well?

**Comment by rfarris2000** [comment]
> @mdpc-nnit not dupe :) Haven't seen this one before. I'll take a look at what's going on.

I submitted a pull request for this.  I encountered this issue and fixed with a check for not equal to null.

https://github.com/microsoft/coe-alm-accelerator-templates/pull/106

**Comment by mikefactorial** [comment]
This should have been resolved with the January release. Closing for now. Feel free to open a new issue if this is still an issue
