### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by tbernstein2368** [microsoft/coe-starter-kit#1713]
### Describe the issue

Can you please reopen #1690 as the issue has not been resolved.  I'm with the Los Angeles County Sheriff's Department and still need some assistant with this issue.  323-526-5639

### Expected Behavior

See #1690

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.6, 3.19

### What app or flow are you having the issue with?

Set up of admin logs

### Steps To Reproduce

See Original Ticket

### Anything else?

Please contact me

**Comment by Jenefer-Monroe** [comment]
Hello we can re-open that ticket for your tracking, but there is nothing further we can to do to assist with it unfortunately.

**Comment by tbernstein2368** [comment]
Jennifer 

I'm confused about your response. Why would you make such a statement when I said that I tried what you said and we're still having problems.  

When I spoke with Phil Topness some months ago he said this was the way to get assistance but it seems as though your focus is closing out tickets as you did with this one over a holiday weekend without even checking back. 

Todd Bernstein

**Comment by Jenefer-Monroe** [comment]
Hi Todd. We are not a supported product, rather a set of templates for folks, yet we put a lot of effort into GitHub. So I'm sorry to hear you feel that way.

The other ticket is open now so we can communicate there.
