### ISSUE TITLE
[CoE Starter Kit - BUG] App Last Launched On column is not populated.

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#1716]
### Describe the issue

App Last Launched On column from the All Apps is not populated with any data in our tenant.
![AppLastLaunchedOn](https://user-images.githubusercontent.com/7468628/148374460-22eacc36-ca5d-43ef-86c8-10393e33f905.PNG)

### Expected Behavior

The column should be populated with data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.6

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

### Steps To Reproduce

Go to Power Platform Admin View - > Apps -> View Column App Last Launched On

**Comment by manuelap-msft** [comment]
Do you have the Audit Log https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog set up? The last launched information is collected via the Audit Log.

**Comment by ClaudiuVio** [comment]
![image](https://user-images.githubusercontent.com/7468628/148388890-e8e33209-7977-45f9-9e16-5bd6bc28c7c9.png)

Thanks for your previous answer. We started the process but we encounter issues with the import of the Audit Logs Solution, what must be done in this matter? We should update the core component of the COE ?

**Comment by manuelap-msft** [comment]
That's correct, you will have to upgrade the Core components solution to the latest version. Note that your existing version is quite old, we recommend upgrading every 3 months to avoid update issues.

**Comment by ClaudiuVio** [comment]
If we upgrade we could face some data loss? or issues ? which zip file we should use for upgrading the core components?

![image](https://user-images.githubusercontent.com/7468628/148390274-9d5ca931-74f1-4fe7-b35f-239032cc8218.png)

**Comment by ClaudiuVio** [comment]
> If we upgrade we could face some data loss? or issues ? which zip file we should use for upgrading the core components?
> 
> ![image](https://user-images.githubusercontent.com/7468628/148390274-9d5ca931-74f1-4fe7-b35f-239032cc8218.png)

![image](https://user-images.githubusercontent.com/7468628/148390723-fa72232f-a01a-4fed-9716-81ddb560ea94.png)

**Comment by manuelap-msft** [comment]
The CoE Starter Kit is released monthly, you can read up about the latest release here https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-December2021 or directly download it from https://aka.ms/coestarterkitdownload 

You can read our guidance for installing updates here
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

You may not be able to upgrade as the solution may have evolved too much from the version you're on. You would not see dataloss, but simply a failure during upgrade.

**Comment by ClaudiuVio** [comment]
We tried to upgrade using CenterofExcellenceCoreComponents_3_19_managed.zip and we receive the below error :

![image](https://user-images.githubusercontent.com/7468628/148395079-2b58d062-7c4a-4328-a9f5-62ddc2a72de2.png)

**Comment by manuelap-msft** [comment]
That means you have tried to Upgrade before already, and that Upgrade failed previously - you will need to remove the _Upgrade solution first before attempting another Upgrade
![image](https://user-images.githubusercontent.com/55705669/148395364-37929dc0-6146-4467-abc8-820efb80a121.png)

**Comment by ClaudiuVio** [comment]
Hello ,

We just did a fresh install of COE kit Core Components all the flows extracted the data and everything is OK.

But now when we are trying to install Audit Logs we are receiving this error : 

![image](https://user-images.githubusercontent.com/7468628/148898166-2ba7a49d-da22-4d78-9089-31501907600c.png)

Note that the Office 365 Management API was configured and when the test at the end was made we receive the following message: 
![image](https://user-images.githubusercontent.com/7468628/148898315-4d8b373d-02bb-4e62-8104-516d7b816020.png)

Thanks for your help.

**Comment by manuelap-msft** [comment]
Hello! Can you share a screenshot of the Solutions screen in your CoE environment? What version of the Core Components is now installed, is it the latest version? What version of the Audit Log components are you trying to install?

**Comment by ClaudiuVio** [comment]
I have solved this, I did the upgrade from 3.19 to 3.20 and the connection references have been added to the new core components.

The audit log is now extracting data. Thank you  !

**Comment by manuelap-msft** [comment]
Awesome, thanks for letting us know that it now works for you!
