### ISSUE TITLE
[CoE Starter Kit - BUG] Multiple core components after upgrading to December version.

### ISSUE THREAD

**Issue by Fubblechunk** [microsoft/coe-starter-kit#1717]
### Describe the issue

After updating to the December version I am left with 2 versions of the core components.

One has a name of upgrade but I would have thought it would have replaced the original version like the others did.

![image](https://user-images.githubusercontent.com/95350630/148411583-be873ff0-6348-4a9f-8935-960161275333.png)

Also, I'm missing 7 environment variables but I can't see where I get this information from.

![image](https://user-images.githubusercontent.com/95350630/148412006-5c0c7ab6-7bfc-4368-b60b-8bb27ce82dff.png)

### Expected Behavior

Replace the original version.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

None

### Steps To Reproduce

Upgrade the CoE again?

**Comment by manuelap-msft** [comment]
You already have the latest version of the CoE Starter Kit installed it seems, it looks like you have 3.19 (green) installed and tried to import 3.19 (amber) again. 
![image](https://user-images.githubusercontent.com/55705669/148433426-ce033715-5f89-4e5b-a8b1-8b1bd3ec84eb.png)

An upgrade will fail if the new solution version is not higher - you can also see this if you click on "See History" in the navigation under the Solutions menu. It will show you the failure. You will need to remove the _Upgrade layer so that future upgrades will succeed.

**Comment by manuelap-msft** [comment]
You can information about what values to put in the environment variables in our setup instructions:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables

**Comment by AdwitiCTS** [comment]
I am getting the same although I tried upgrading from version 1.89 to 3.20. Also I am getting the following error. Any help is greatly appreciated
<img width="811" alt="CoeError" src="https://user-images.githubusercontent.com/88749369/149229295-7a47795d-688c-46d1-9baa-3ef60bb17b3f.PNG">

**Comment by AdwitiCTS** [comment]
I am facing the same issue but while upgrading the Core components from version 1.89 to 3.20
<img width="811" alt="CoeError" src="https://user-images.githubusercontent.com/88749369/149230612-87274271-0c29-4194-9555-697902ceb64c.PNG">
.

**Comment by manuelap-msft** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state, but you may need to start with a clean install and migrate any customized data. We recommend upgrading at least every 3 months, see https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup#installing-upgrades
