### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to re-assign flow to another standard user.

### ISSUE THREAD

**Issue by Fubblechunk** [microsoft/coe-starter-kit#1718]
### Describe the issue

When trying to re-assign a flow owner to another user in the business search doesn't find any names that aren't an O365 admin.

We have a flow I need to change ownership to someone else but I can't do this from the admin centre.

Not to sure this is a bug but when I raised a support ticket they told me to come here and log it.

![image](https://user-images.githubusercontent.com/95350630/148412761-ccd0d5f7-35a4-4694-ad40-1423a1f64017.png)

### Expected Behavior

Ability to re-assign apps and flows to anyone else in the business not just O365 admins.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

None

### Steps To Reproduce

Navigate to the admin centre org****crm4.dynamics.com/main.aspx

Navigate to the flow in question.

Click Assign.

Search for the user.

Only O365 admins are found.

**Comment by Jenefer-Monroe** [comment]
Hello. You are looking at just an inventory list here, even if you did re-assign with that button all you would be assinging is that record in the inventory. We cannot hide those buttons, but they should not be used. 
There is an app called Set Flow Permissions that we have added to make this easier for admins. Please see https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#apps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by raphaeltremblay1966** [comment]
Hello, 

I would like to report about the same thing. When trying to take Ownership as new Owners, us admins, we are facing with some options :

1- Powershell commands or Flows : 
- This needs some work to find the new owner ID+ the App ID, the Environment ID, etc - Tedious !

2- COE Canvas App - Admin | Set App or Set Flow Permissions : 
- Limitation of 2000 makers display, so short term, for us, this not a viable solution (we already have 2200 makers and will easily triple this number in a few months, we are a 40K user organization)
-  Any plans to redesign these 2 Canvas Apps in the future without using a collection ?

3- Environment, Apps/Flows list - Assign ourselves as Co-Owners
- Could be, but it is so badly designed for Flows, we have to scroll through the list which takes ages to get to the desired Flow, no continuous scrolling, we need to press the Load More button at the bottom after 50 flows. We already have 140+ environments and more than 10,000 flows & 2,000 Apps
- In contrast, the scrolling for the Apps work well

4- PowerBI Dashboard - Set Permission embedded app (Access this App, Access this Flow)
- Not sure if we are not doing this right, but this do not work. I grant Myself Access to a Flow, the embedded App says "You can manage this App (not sure why it says that I have No Access to "this App" - Are we talking about Flow or App ??), I refresh, go back to Drill down, and again, No Access to this App. (see screenshots). I can try to Add me as 'New Users", go back, nothing there, does not work.

![image](https://user-images.githubusercontent.com/99994964/159617159-e1fd5a0b-7e3c-4422-847e-2468b37987b5.png)
![image](https://user-images.githubusercontent.com/99994964/159617315-2280e5cc-c432-4740-9325-ffcbde5cfbe6.png)
