### ISSUE TITLE
[CoE Starter Kit - BUG] Command Center Email page only shows email for the Core solution

### ISSUE THREAD

**Issue by kashanico** [microsoft/coe-starter-kit#1719]
### Describe the issue

When trying to edit emails via the Command Center, only flows from the Core solution appear and when clicking the drop down only Core is available.

![image](https://user-images.githubusercontent.com/64927104/148445099-35ad25f7-3ad8-4966-b0db-80a82bd03ed1.png)

### Expected Behavior

It should display all solutions in the environment

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

1. Open Admin - Command Center
2. Go to Emails page
3. Click All Solutions drop down

**Comment by Jenefer-Monroe** [comment]
Hello. That is correct. We only released for flows in Core to begin with, while we get feedback and iterate before driving through to the other solutions.

**Comment by kashanico** [comment]
Ok thanks, you can close this then. 
Thanks for the quick response.

**Comment by kashanico** [comment]
See Jenefer's response. As expected behaviour.
