### ISSUE TITLE
[CoE Starter Kit - BUG] Core for Teams version issue

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#1720]
### Describe the issue

I have Dataverse for Teams core solution 3.10 installed (believe that was current in the Dec 2021 version)  When attempting to upgrade to 3.4 included in the Jan 2022 version, I get the error - "The import solution must have a higher version than the existing solution it is upgrading."

### Expected Behavior

I expect it to upgrade successfully to the new version.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4 Core for Teams

### What app or flow are you having the issue with?

core solution install

### Steps To Reproduce

Attempt to install 3.4 over the top of 3.10 in DV4T environment.

**Comment by manuelap-msft** [comment]
You're right, I incorrectly had 3.3 down as the last version for Core for Teams. Here's an update with the new version number https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-January2022/CenterofExcellenceCoreComponentsTeams_3_11_managed.zip
