### ISSUE TITLE
[CoE Starter Kit - BUG] title label missing

### ISSUE THREAD

**Issue by thondal-evry** [microsoft/coe-starter-kit#1721]
### Describe the issue

In the Power Platform Admin View several titles just says "category", so it's hard to see what it actually refeers to. (screenshot in norwegian)
![bilde](https://user-images.githubusercontent.com/55357093/148521440-79092a03-a538-4689-b37c-77d030ea4acd.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

1. Sign in to Power Platform Admin View
2. Select flows
3. Edit a flow
4. See missing category labels in overview of the flow

**Comment by manuelap-msft** [comment]
This typically happens when you don't have the English language pack installed in the environment. We only support english for the CoE Starter Kit, see our limitation here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#supported-languages

**Comment by Jenefer-Monroe** [comment]
Closing out as nothing more for starter kit team to do here. 
Thanks for using CoE

**Comment by thondal-evry** [comment]
Hi, sorry for reopening, but after installing the correct language extension, it still is not populated correctly or is the "tab,tab,tab" supposed to be the titles?
![bilde](https://user-images.githubusercontent.com/55357093/152348413-8bd5f740-5803-4e2a-9cfc-79217571b925.png)

**Comment by manuelap-msft** [comment]
It should look like this
![image](https://user-images.githubusercontent.com/55705669/152361845-205325fb-3df5-44f4-87ba-2c385dba959b.png)

and I have verified that this is what it looks like in our shipped version. This does not seem to be a bug with the CoE kit. Maybe installing the language pack after installing the kit has led to this behaviour. You may have to edit the model driven app to fix the headers.
