### ISSUE TITLE
[CoE Starter Kit - BUG] PBI Report - Cloud Flow detail not shows info in Permissions

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#1723]
### Describe the issue

In the tab Cloud Flow detail, there isn't info in Permissions about the cloud flow.

![image](https://user-images.githubusercontent.com/57954993/148530937-1aa2b700-c8a0-4ac6-bc88-de9fdd4be8a1.png)

### Expected Behavior

The same behaviour like the tab App detail:
![image](https://user-images.githubusercontent.com/57954993/148531261-699d22df-ec3a-4443-9d1e-9af00f3d959d.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Production_CoEDashboard_Jan2022.pbit

### What app or flow are you having the issue with?

Production_CoEDashboard_Jan2022.pbit

**Comment by Jenefer-Monroe** [comment]
Can you please let me know, does this repro for flows that are part of a solution AND flows that are not part of a solution? 
Flows that are part of a solution will not return this information.

**Comment by albertocaa1317** [comment]
Yes, it repro in flows that are not part of a solution also.

**Comment by Jenefer-Monroe** [comment]
And can you confirm, you see this only for flows in Default. It works for other environments.

**Comment by Jenefer-Monroe** [comment]
Actually can you also confirm that you have selected the fields as shown here? 
![image](https://user-images.githubusercontent.com/89584709/148610592-5141bd6d-5f51-4fc1-a2c2-1042c070a58f.png)

**Comment by albertocaa1317** [comment]
Sorry, I was choosing admin_flowenvironmentID, not adminflowenvironment. Solved! Thanks @Jenefer-Monroe.
