### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI for Teams failing to load due to duplicate "owningbusinessunitname" column

### ISSUE THREAD

**Issue by castilld5797** [microsoft/coe-starter-kit#1724]
### Describe the issue

Power BI Error: "A Join operation cannot result in a table with duplicate column name" when attempting to stand up Power BI Dashboard. 
![PPCOE_PowerBI_Error](https://user-images.githubusercontent.com/8749850/148567136-e8bdfc53-3052-4864-8183-a207df805c2d.png)

### Expected Behavior

Power BI Dashboard loads successfully 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Jna2022

### What app or flow are you having the issue with?

Power BI Dashboard

### Steps To Reproduce

Attempt to open Teams_CoEDashboard_Jan2022.pbit

**Comment by castilld5797** [comment]
Using latest version of Power BI (32 bit).

**Comment by manuelap-msft** [comment]
Hello,

we have done some investigation here and it looks like a change rolled out to Dataverse for Teams environments on Friday afternoon that added this column. I have tested the current .pbit with Dataverse for Teams environments created before Friday and it works, but with new environments created after Friday I repo this error.

Here is a new version removing this column that hopefully works for you: https://github.com/microsoft/coe-starter-kit/raw/coe-february/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Teams_CoEDashboard_Jan2022_v2.pbit

Please let us know if this version works for you! Thank you, Manuela

**Comment by castilld5797** [comment]
Manuela,
                I tried it, but I got the following error:

***@***.***

I saw a similar error in the setup instructions, I tried bother

"org39b609d1.crm.dynamics.com" as well as
"https://org39b609d1.crm.dynamics.com/"

Regards,


David Castillo
Associate Director | Information Technology
User Experience / Collaboration Services

Office +1 609 419-6646
Mobile +1 908 227-0093
***@***.***

**Comment by manuelap-msft** [comment]
Unfortuantely screenshots do not come through when replying via email to GitHub Issues, you'll have to navigate to https://github.com/microsoft/coe-starter-kit/issues/1724 and attach the screenshot directly there for me to see it! Thank you!

**Comment by castilld5797** [comment]
Manuela,
                Screen shot added and updated in the comments.

Regards,


David Castillo
Associate Director | Information Technology
User Experience / Collaboration Services

Office +1 609 419-6646
Mobile +1 908 227-0093
***@***.***

**Comment by manuelap-msft** [comment]
Hello,

can you go through the troubleshooting tips explained here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting to see if any of those solve the issue for you!

Thank you
Manuela

**Comment by castilld5797** [comment]
Manuela,
                None of the tips resolved the issue.

Regards,


David Castillo
Associate Director | Information Technology
User Experience / Collaboration Services

Office +1 609 419-6646
Mobile +1 908 227-0093
***@***.***

**Comment by castilld5797** [comment]
Manuela,
                Ports are not blocked:

Details:
PS C:\Users\castilld> Test-NetConnection -ComputerName org39b609d1.crm.dynamics.com -port 1433                                                                                                                                                                                                                                                                          ComputerName     : org39b609d1.crm.dynamics.com
RemoteAddress    : 13.64.174.215
RemotePort       : 1433
InterfaceAlias   : Wi-Fi
SourceAddress    : 10.0.0.94
TcpTestSucceeded : True



PS C:\Users\castilld>


Regards,


David Castillo
Associate Director | Information Technology
User Experience / Collaboration Services

Office +1 609 419-6646
Mobile +1 908 227-0093
***@***.***

From: Manuela Pichler ***@***.***>
Sent: Friday, January 14, 2022 8:23 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Castillo, David ***@***.***>; Author ***@***.***>
Subject: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Power BI for Teams failing to load due to duplicate "owningbusinessunitname" column (Issue #1724)

[Use CAUTION when opening links/attachments]

This error may be due to blocked ports on your network - here are some ways to verify you have all necessary ports enabled: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#blocked-ports

-
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F1724%23issuecomment-1013112492&data=04%7C01%7Cdavid.castillo%40bms.com%7C7aa8dda7c03447078da908d9d7610b46%7C71e34cb83a564fd5a2594acadab6e4ac%7C0%7C0%7C637777634070656897%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2B6rnquoWld%2FdqHFsmonemTibF0Bm%2FEm3uy0IRzW9Vcc%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACCYGGVS33QV4ZFELKZ5IBLUWAPUZANCNFSM5LPBMBXA&data=04%7C01%7Cdavid.castillo%40bms.com%7C7aa8dda7c03447078da908d9d7610b46%7C71e34cb83a564fd5a2594acadab6e4ac%7C0%7C0%7C637777634070656897%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d8Xq08mZWuwrxXETAiYN1hzC%2FkXZCpQWTJ0pCuQQm70%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdavid.castillo%40bms.com%7C7aa8dda7c03447078da908d9d7610b46%7C71e34cb83a564fd5a2594acadab6e4ac%7C0%7C0%7C637777634070656897%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=o2iVQ%2FfINPPXsUIOladR2UwUObERtmGn3immn%2BM5QZ0%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdavid.castillo%40bms.com%7C7aa8dda7c03447078da908d9d7610b46%7C71e34cb83a564fd5a2594acadab6e4ac%7C0%7C0%7C637777634070656897%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1OdreZRS8EAUUfk07oQ38bx9ZHsMVG8K96eTrULahaw%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________
This message (including any attachments) may contain confidential, proprietary, privileged and/or private information. The information is intended to be for the use of the individual or entity designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is prohibited.

**Comment by manuelap-msft** [comment]
Unfortuantely this seems to be an error with Power BI or your network setup, unrelated to the CoE Starter Kit - the error message means that the Power BI service can't connect to your CoE environment. I would suggest raising a support ticket so a Power BI support engineer can look into this. https://powerbi.microsoft.com/en-au/support/pro/

**Comment by Jenefer-Monroe** [comment]
Closing out as nothing more for starter kit team to do here. 
Thanks for using CoE
