### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Dashboard Dataset Refresh Fails

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1725]
### Describe the issue

When refreshing the dataset for the CoE dashboard, it fails with the following error:

Column '<pii>admin_portalenvironment</pii>' in Table '<pii>Portals</pii>' contains a duplicate value '<pii>34d9f01e-f604-4c20-9ca4-30523786cb9d</pii>' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.

On checking the table there are two entries in the Portal Unigue Name column with the following GUIDs:
**34d9f01e-f604-4c20-9ca4-30523786cb9d**_cc8b9159-1a4d-ec11-8c62-000d3ab64a7b - (Portal from blank template)
**34d9f01e-f604-4c20-9ca4-30523786cb9d**_c0887167-3954-e611-80dc-00155d209102 - (event portal)

According to Microsoft documentation, it should be allowed:
Environment with customer engagement apps | Portal from blank | 50 portals* | No limits for language. For example, more than one or all portals can use same language.

Environment with customer engagement apps | All templates except "Portal from blank" | 1 portal for each language | For example, 1 English language portal for "Community portal" template allowed.

https://docs.microsoft.com/en-us/powerapps/maker/portals/create-additional-portals

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

Power BI Dashboard Dataset

**Comment by Jenefer-Monroe** [comment]
Have you run the "data data" clean up flows? This was an issue we fixed a couple months ago but you need to run those clean up flows in order to see the bad data removed.

**Comment by medicineshow** [comment]
"data data" clean up? do you mean all the CLEAN UP flows when you say data data?

**Comment by Jenefer-Monroe** [comment]
haha typo I meant the "bad data" one
CLEANUP - Admin | Sync Template v3 (Delete Bad Data)

**Comment by medicineshow** [comment]
It does appear to have been fixed after we updated to the latest version, thanks
