### ISSUE TITLE
[ALM Accelerator - BUG]: coe aa4am install -f quickstart.json fails

### ISSUE THREAD

**Issue by davidyack** [microsoft/coe-starter-kit#1729]
### Describe the issue

info: Install AAD application
info: Application exists
info: Admin permissions granted
info: Group ALMAcceleratorForAdvancedMakers exists
info: Install DevOps Components
info: Loading DevOps Extensions Configuration
info: Checking DevOps Extensions
https://dev.azure.com/contoso010422/_apis/Location
(node:37168) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of null
    at C:\coe-cli\node_modules\azure-devops-node-api\VsoClient.js:125:52
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:37168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:37168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Expected Behavior

to work :)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

latest

### Steps To Reproduce

coe aa4am install -f quickstart.json

**Comment by mikefactorial** [comment]
The install extensions call is the first place in the coe-cli installer that it tries to connect to DevOps. Wondering if this may just be a configuration issue. @Grant-Archibald-MS have you seen this before / thoughts?

**Comment by Grant-Archibald-MS** [comment]
@davidyack The account that you are using has Tenant level administrator rights to https://dev.azure.com/contoso010422?

**Comment by davidyack** [comment]
@Grant-Archibald-MS  yes global tenant admin

Looked like it was trying to access https://dev.azure.com/contoso010422/_apis/Location which doesn't appear to exist

**Comment by davidyack** [comment]
Apparently ADO got a name with an extra S that caused the problem

Would be great if CLI gave a more clear error message.

Also on input prompts for generate it would be helpful if it gave an example if it wanted a name or a full URL

**Comment by mikefactorial** [comment]
Closing as resolved
