### ISSUE TITLE
Apps /flows that haven't been modified or launched.  Getting Approval requests every months after selecting Reject 

### ISSUE THREAD

**Issue by EmranCoE** [microsoft/coe-starter-kit#1730]
### Describe the issue

These  two components (Admin | Archive and Clean Up v2 (Start Approval for Flows/Apps) when sending a request to the makers whether the flows/apps can be deleted or using 

<img width="303" alt="Approval-req" src="https://user-images.githubusercontent.com/90054514/148697705-4fd91cba-6c5f-41ec-b999-f4667ad0df99.png">

I would like to ask about condition 3 , where it says select **Reject /Turn off** to avoid receving this mail again in another month ,  So , if some one reject today and will get this request again  next month and keep gets every month  (if no modifications)  ? is there any options to change this one month time !
About condition 1 : if turn off they gets also request every month !

Many Thanks !

Emran

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.8

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Flows/Apps)

**Comment by Jenefer-Monroe** [comment]
You can read about the processes here to understand how / when an object will be subject to this flow's approval
https://docs.microsoft.com/power-platform/guidance/coe/governance-components#admin--archive-and-clean-up-v2-start-approval-for-apps

And you can exempt individual apps/flows from the processes using this app
https://docs.microsoft.com/power-platform/guidance/coe/governance-components#app-and-flow-archive-and-clean-up-view

Hope that helps

**Comment by EmranCoE** [comment]
Hey Jenefer ! Thank you for the document links .
Based on this diagram , if the flow Turned Off (Do Nothing ) >>but user still gets request after Turned off  ?
**Rejection time out after 1 month** , I am looking for whether can change this time interval 1 month to 3 month !

<img width="531" alt="Approval-flows" src="https://user-images.githubusercontent.com/90054514/148901057-332928cb-02ef-4baf-9f82-2d694b380a84.png">

**Is there somewhere I can change this 1 month !**

<img width="940" alt="Rejected" src="https://user-images.githubusercontent.com/90054514/148901115-b6431c96-ca00-4c98-a2c6-b806f98f5c79.png">


Thanks a lot !
Regards

**Comment by Jenefer-Monroe** [comment]
Hello, no if the flow is turned off it will not get returned in the query and will not enter the process. Thats a way for people to exempt their own flow until / if they want to use it again someday.

**Comment by Jenefer-Monroe** [comment]
Regarding the rejection timeout at 1 month, we had this match the amount of time approvals stay active in the product. 
You can likely change this in the following manner, although please note that this is not something I have tested out, so you would need to test on your own after making this change. 

In the **_Admin | Archive and Clean Up v2 (Clean Up and Delete)_** flow
You would change this call to Get Past Time
![image](https://user-images.githubusercontent.com/89584709/148966523-ed5570b9-cdca-407e-9c3b-b5bf6eafaecd.png)

**Comment by EmranCoE** [comment]
Thank you so much for all the support and help with details instructions , appreciated very much .
Yes ,sure ! I will test this rejection timeout (month)
You can close this issue  

Best Regards,
Emran

**Comment by Jenefer-Monroe** [comment]
Thanks for using CoE!
