### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to set owners in the Set Flow permission app

### ISSUE THREAD

**Issue by Melvinrchrd13** [microsoft/coe-starter-kit#1732]
### Describe the issue

Unable to set owners in the | Set Flow permission under COE

### Expected Behavior

When click on "Make Owner" refreshes to the same page no changed has been made.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Set Flow Permissions

**Comment by Jenefer-Monroe** [comment]
Can you please share some screenshots to show us what you mean? We do not repro this.

**Comment by Jenefer-Monroe** [comment]
oops, didnt mean to close

**Comment by Jenefer-Monroe** [comment]
Closing out as nothing more for starter kit team to do here. 
Thanks for using CoE
