### ISSUE TITLE
 Add users to get CoE data thought PowerBI Desktop.

### ISSUE THREAD

**Issue by jfkoga** [microsoft/coe-starter-kit#1733]
Hello,

We would like to receive some indications to give permissions to different users to access to CoE data thought PowerBI Desktop.
Could you send us some steps or guide to this requeriment?
Thanks.

**Comment by manuelap-msft** [comment]
Hello,

1. We use import as part of the Power BI dashboard, so if you have published the dashboard to a workspace, it's sufficient to share just the dashboard and users won't need access to underlying data
2. If  you want users to be able to connect to the environment from Power BI Desktop, they will need environment access plus access to the CoE tables. Assinging them the Power Platform Admin SR security role that ships with the CoE Starter Kit in the environment you've installed the CoE in should be sufficient there.

Manuela

**Comment by jfkoga** [comment]
Hi Manuela,

We are going to check the options you send us.
Thanks for your support.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by jfkoga** [comment]
Hi, 
We have assing to specfici users the Power Platform Admin SR security role that ships with the CoE Starter Kit in the environment I have installed the CoE, but it doesn't work for us, receiving this error (see attached file).
Any other idea about how to solve it?

Regards.
![coe-error](https://user-images.githubusercontent.com/47460739/153956545-049a53f3-02f0-44d8-9177-0968cfef39e8.png)
