### ISSUE TITLE
[CoE Starter Kit - BUG] AdminCompliance workflows not working in Core Components for Teams 

### ISSUE THREAD

**Issue by JonTaylor5** [microsoft/coe-starter-kit#1735]
### Describe the issue

We have installed the CoreComponents on a Dataverse for Teams environment and have noticed with we create a copmliance request that no workflows or notificatrions are generated. This is different functionality to full Dataverse which does send emails and update the status etc. 

On looking into the 2 solutions I can see that  there are less AdminCompliance workflows in the Teams solution so I am looking for confirmation this is by design (or not as the case might be) and what the intended behaviour should be.

<img width="554" alt="2022-01-11 13_04_37-Different workflows in Dataverse and Dataverse for Teams - Word" src="https://user-images.githubusercontent.com/97525276/148947713-cf899fd5-6eda-44e2-87be-6cf740087e8e.png">
 

### Expected Behavior

Same fuctionality in both Dataverse and Dataverse for Teams solutions 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

CenterofExcellenceCoreComponentsTeams_3_11_managed

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponentsTeams_3_11_managed

**Comment by Jenefer-Monroe** [comment]
Hello, D4T does not support business process flows, so the compliance processes are different in D4T than in Production. 
What do you mean when you say you **_create a compliance request_**?

**Comment by JonTaylor5** [comment]
Hi Jenefer,

Thank you for your prompt response. In creating a compliance request I mean the business justification and status changes which a part of the C0E Dataverse functionality.

How does the business justification process work in D4T if there are no process flows due to functionality restrictions?

Thanks,

Jon

**Comment by Jenefer-Monroe** [comment]
The mails are only sent when objects are identified by the flow, manually requested or changing the status of a compliance will not send mail in either production or D4T. 

In both cases you can mark an object as requiring compliance details, but this alone does not trigger notification to the maker.
![image](https://user-images.githubusercontent.com/89584709/148975525-5a933f09-601a-4197-885d-cce5760cc049.png)

It will, however, show up as required when you go to the compliance center app:
![image](https://user-images.githubusercontent.com/89584709/148975764-b97d8b00-81c0-41fb-b221-897eff472ae1.png)

And then the admin can use these filters to see what has been requested / submitted / etc
![image](https://user-images.githubusercontent.com/89584709/148976205-108371ec-6fb9-489b-b010-296d101bffa4.png)

**Comment by JonTaylor5** [comment]
Hi Jenefer,

Thank you so much for your help it is very much appreciated.

Just for confirmation does the status need to be updated manually by the makers and the admin in the D4T version of CoE?

Thanks,

Jon

**Comment by Jenefer-Monroe** [comment]
Sorry I'm afraid the answer isnt simple. It depends on many factors (ex does the object hit the thresholds in the flow, did they have to update a description and wait for sync flow, etc). But the behavior should not be different D4T and Prod. 

You will need to test out your specific cases and then if you have specific questions or feedback please return with them.

**Comment by Jenefer-Monroe** [comment]
Closing out as nothing more for starter kit team to do here. 
Thanks for using CoE

**Comment by JonTaylor5** [comment]
Thank you for your help Jenefer, it is much appreciated.

Kind regards,

Jon


Jon Taylor | Solutions Manager | Email: ***@***.******@***.***>| Mob:+44 7966 064611

***@***.***
