### ISSUE TITLE
[CoE Starter Kit - BUG]  Custom Connector grid have duplicate record

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#1741]
### Describe the issue

Seems that there is issue in custom connector grid - duplicate record found for same connector

![image](https://user-images.githubusercontent.com/30046543/149152366-0737e528-2e1f-449c-a76e-b006499c1e49.png)

App Risk Assessment: Unique users and sessions have count without any display name and owner
![image](https://user-images.githubusercontent.com/30046543/149153036-26eb3b52-d591-4a1d-8ae6-4aea6c8c3c5a.png)

### Expected Behavior

In grid record should be unique 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Power BI Report

**Comment by Jenefer-Monroe** [comment]
Are these cases of the same app installed in different environments?

**Comment by manuelap-msft** [comment]
![image](https://user-images.githubusercontent.com/55705669/149157511-b49d4b41-db86-4c99-944e-8ad6f56ff9c9.png)

You can see the App Name is different for each. This grid shows you which apps use which custom connectors. If the same custom connector is used in multiple apps, it will show up multiple times here which seems to be the case for you.

**Comment by sharmajitendralal** [comment]
Yes
