### ISSUE TITLE
[CoE Starter Kit - BUG] Innovation Backlog - error when play from maker (works in player)

### ISSUE THREAD

**Issue by lauram15a** [microsoft/coe-starter-kit#1745]
### Describe the issue

Hi! 
I have a problem with the Innovation Backlog power app. When running with the Play from outside the "edit" mode it works correctly, but if I get into "edit" mode, it breaks and no longer works (I have not been able to understand why). The name of the columns are initially in English, but it gives me an error and tells me that I have to write them in Spanish.  After translating it, the errors are not solved, appearing new errors. 
Thank you very much in advance.

### Expected Behavior

.

### What solution are you experiencing the issue with?

Innovation Backlog

### What solution version are you using?

2.5

### What app or flow are you having the issue with?

Innovation Backlog

### Steps To Reproduce

.

### Anything else?

.

**Comment by Jenefer-Monroe** [comment]
Hello I am not repro-ing this. And I'm not sure about this issue with languages. Do you have the english language pack installed? Can you please share some screenshots? (note screenshots do not come through if you reply in email, you will need to add them in GitHub)

**Comment by Jenefer-Monroe** [comment]
We have seen this issue once before from another customer. #1201 

Can you please validate
1) You are in a Dataverse for Teams install
1) Your primary language is not English
1) You have the English language pack installed (see our [limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations#supported-languages))

**Comment by lauram15a** [comment]
I have uploaded 3 videos showing the errors that I have explained at the initial of the conversation. 
https://github.com/lauram15a/Innovation-Backlog-Issues
Thank you very much in advance.

**Comment by Jenefer-Monroe** [comment]
Hello. Yes it appears that you do not have the English language pack installed. Please see  our [limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations#supported-languages)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
