### ISSUE TITLE
[CoE Starter Kit - BUG] upgrade issue for Core Components version 1.89

### ISSUE THREAD

**Issue by RebekkaAalbers** [microsoft/coe-starter-kit#1746]
### Describe the issue

We have an outdated version of the core components installed (1.89). I am trying to catch up to the next available version (either 2.0 or 2.10) but get an import failure on a table not being available:
Cannot process via smartdiff for upgrade due to Cannot find entity admin_ConnectionReference 28584134-3b52-46c3-a35f-621b4ef78c38 with layer for solutionId af84a85d-dbfd-48d0-85cf-fa5e0c424c2d.. ModifiedKeys for entity: Name,OriginalName

Version 1.89 does have table admin_ConnectionReference, but with a different guid. And I cannot find any affecting solution layers or a solution with an ID starting with af84a85d-dbfd-48d0-85cf-fa5e0c424c2d.
I also cannot find our current version any longer in the previous solutions section in the old repo. Could it be the admin_ConnectionReference table has been recreated and I need a staging solution to get from 1.89 to 2.10?

### Expected Behavior

Solution imports and upgrades.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Whole solution

### Steps To Reproduce

1. Start with solution CenterofExcellenceCoreComponents 1.89 installed
2. Import for upgrade CenterofExcellenceCoreComponents 2.10

**Comment by Jenefer-Monroe** [comment]
Hello, yes at one point this connection reference got deleted, but recreating it did not actually fix the issue, and then there wasn't anything we could do to make upgrade smooth at that point from that old of a version. There were some customers that worked through the issue and have notes in GitHub that you can look for. 

But unfortunately we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. You may need to start with a clean install and migrate any customized data. We recommend upgrading at least every 3 months, see https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup#installing-upgrades

If all you are doing is migrating inventory and audit logs, we did attempt to write up good how-to migrate steps for that here [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

**Comment by RebekkaAalbers** [comment]
Understandable, but still a bit of a bummer 😉
I'll have a look through the notes to see if I can find something. We do have a some customizations, so I hope to prevent from having to do a fresh install.

**Comment by Jenefer-Monroe** [comment]
Sorry!!!
