### ISSUE TITLE
[CoE Starter Kit - BUG] Connector information not saved with newest starter kit version

### ISSUE THREAD

**Issue by redleo85** [microsoft/coe-starter-kit#1751]
### Describe the issue

After installing the CoE starter Kit and completing a first crawl there is no connection reference data saved for apps or flows.

The flow **Admin | Sync Template v3 (Connectors)**, which crawls initial connector information, stops before listing all standard connectors.

### Expected Behavior

Connection reference data should be collected for apps and flows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

### Steps To Reproduce

1. Install CoE starter Kit version 3.20
2. Turn flows on
3. Wait for crawl to be completed

### Anything else?

Within the flow **Admin | Sync Template v3 (Connectors)** there is a termination action, which looks like it was there to debug the flow, but has not been removed. See screenshot.

![image](https://user-images.githubusercontent.com/9613325/149475156-928ac16d-ad06-4d44-9946-9071601a128a.png)

**Comment by MSPowerPlatformDev** [comment]
CoE Starter Kit version 3.19 didn't have the terminate action which allowed it store details of all the connectors.
It seems this missing connector information is causing Admin | Sync Template v3 (Apps) to also fail. Raised a bug for that [https://github.com/microsoft/coe-starter-kit/issues/1752](here)

**Comment by Jenefer-Monroe** [comment]
Thank you, this is a bug and I have it local fixed now for Feb. 

Please just delete that action and then you will need to do a [full inventory run](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory) in order to get all these values into your apps/flows.

**Comment by Jenefer-Monroe** [comment]
We are about to re-ship with this issue fixed. Thanks for posting for us!

**Comment by manuelap-msft** [comment]
This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
