### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by Rene-** [microsoft/coe-starter-kit#1755]
### Describe the issue

I looked into the Admin | Compliance Detail Request v3 and saw the only tables being pulled were for Apps and chatbots, but the Developer Compliance Center showcases Flows and other resources. 

Is this on purpose or is the sample audit process just a sample? 

### Expected Behavior

All resources under the power platform be part of the sample audit process

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

 Admin | Compliance Detail Request v3

**Comment by Jenefer-Monroe** [comment]
You can manually flag other object types as requiring compliance details.
We have automatic flagging for only canvas apps and chatbots.

Hope that makes sense.

**Comment by Rene-** [comment]
> You can manually flag other object types as requiring compliance details. We have automatic flagging for only canvas apps and chatbots.
> 
> Hope that makes sense.

Is this an environment variable change? Can you show me where to manually flag other object types?

**Comment by Jenefer-Monroe** [comment]
You can flag the other objects (or apps/flows not hitting threshold to get auto-flagged) as requiring compliance in the Power **_Platform Platform Admin View_** app

Find the object and go to the Audit tab. 

![image](https://user-images.githubusercontent.com/89584709/149565400-adae5393-5856-438e-82f9-2882c4fa2505.png)

**Comment by Rene-** [comment]
in other words to get all objects to be auto flagged, or in my case, be part of the automated audit process I have to modify the flows to include the objects not currently included?

**Comment by Jenefer-Monroe** [comment]
Correct. 
Although my recommendation would be to add another flow rather than augment ours, so that you can continue to receive updates from us.

**Comment by Rene-** [comment]
Any plans for the future to include all objects in these flows?

**Comment by Jenefer-Monroe** [comment]
Not at this time as there is no "usage" details about anything else available to us.
