### ISSUE TITLE
Service connection related permission issue while running the pipelines

### ISSUE THREAD

**Issue by RPAUser24** [microsoft/coe-starter-kit#177]
I am trying out the creation of some of the YAML pipelines in the solution and getting below error with a some permissions.
The app registration in Azure is created successfully with all required API permissions granted as necessary. The application user is also created at the power platform environment level accordingly.
This in turn is translated into service connections in DevOps using the environment URLs and client secret.

Error description -
"The pipeline is not valid. Job Job1: Step input PowerPlatformSPN references service connection $(ServiceConnection) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz. Job Job1: Step input PowerPlatformSPN references service connection $(ServiceConnection) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

Pipelines that were consumed is - 
export-solution-to-git.yml
build-sample-solution.yml
deploy-test-sample-solution.yml

The service connection is created and authorized with the API permissions as required.
Could you please help make sense out of it? I am currently stuck with the issue.

**Comment by jenschristianschroder** [comment]
Please check that you have created the required pipeline variables for EnvironmentName and ServiceConnection as described here:
https://github.com/microsoft/coe-starter-kit/blob/main/PowerPlatformDevOpsALM/GETTINGSTARTED.md#create-environment-and-service-connection-required

The Getting Started doc was recently updated to clarify this step.

**Comment by jenschristianschroder** [comment]
Closing this issue as it has been verified off-line that the pipeline variables had incorrect configuration.
