### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by diego-coke** [microsoft/coe-starter-kit#1772]
### Describe the issue

When an end user is trying to submit the business justification for a teams environment is getting  and error: "Unable to reach the app. Please try again"

![image](https://user-images.githubusercontent.com/83843163/149840008-8fba786b-e534-4f8e-baf1-60a6c622ca91.png)

### Expected Behavior

the user should be able to send the info via the adaptative card in teams

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created

**Comment by Jenefer-Monroe** [comment]
Likely this ask was timed out. I cannot see the time this was sent but was it sent a while ago? It's set to time out in 6 days.

**Comment by Jenefer-Monroe** [comment]
I have added a time out notice to people with #1775 which will ship for Feb. 
Please let me know if this seems likely your case. From my testing it does appear to be so.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
