### ISSUE TITLE
[CoE Starter Kit - BUG] Sync flows fail on every run because of "HELPER - Maker Check"

### ISSUE THREAD

**Issue by redleo85** [microsoft/coe-starter-kit#1776]
### Describe the issue

All our sync flows (e.g. "Admin | Sync Template v3 (Apps)" and "Admin | Sync Template v3 (Flows)") fail on every environment with flows in them.
There is an error message "Bad Gateway - No Response" in the action "Maker Check". Here a screenshot from the Apps sync flow, but the error also occurs in other sync flows.

![image](https://user-images.githubusercontent.com/9613325/149901239-0a99a859-1dac-4e11-bb53-89c0663b735c.png)

### Expected Behavior

Sync flows run through successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

### Steps To Reproduce

1. Update to starter Kit version 3.20
2. Run Sync flows

### Anything else?

We looked at the flow "HELPER - Maker Check", because this seemed to cause the error.
We discovered that the flow failed every time on the action "Initialize variable" with the following error.

![image](https://user-images.githubusercontent.com/9613325/149901943-22c80e72-beb2-444e-8629-8aca23f6eff4.png)

We managed to mitigate the error by deleting the respective dynamic content field from the action and re-adding it. This added a question mark within the formula "triggerBody()?['boolean']".

**Comment by Jenefer-Monroe** [comment]
Thanks for your thorough investigation. 
Do you have unmanaged layers on those sync flows? They were updated in 3.20 to send a last parameter to this helper. It sounds like they were not sending it.

**Comment by redleo85** [comment]
Hi @Jenefer-Monroe ,
no, we did not have any unmanaged layers, neither on the sync flows nor on the "HELPER - Maker Check" flow.
But we have an additional managed layer. After updating that layer with the current version, it now works.
Thanks for the hint.
