### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by JadhavKalpana** [microsoft/coe-starter-kit#1787]
### Describe the issue

Trying to Install the CoE toolkit, got the step Activate the flows step 4, and it wont turn on the flow.
Unable to turn on the  inventory flows, throwing below error
 error is -  Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Connectors' of type 'OpenApiConnection' at line '1' and column '6382' is not valid. The value specified for property 'minimumItemsCount' exceeds the 
<img width="733" alt="issue" src="https://user-images.githubusercontent.com/97939667/150066841-60fd8fae-556a-4fc4-a1ed-3d11c5f3539b.PNG">
maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

Kindly Help or suggest.

### Expected Behavior

Turn on the flows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin - Sync Template V3

### Steps To Reproduce

1. Create an environment
2. Import the CoE components
3. configure the variables
4. configure the helper and clean up components
5. turn these on

**Comment by Jenefer-Monroe** [comment]
Hello. All the flows have this pagination policy. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites).

**Comment by JadhavKalpana** [comment]
Hi,

Thanks for your prompt response.

Is there any another way to do this?
Need to set up the CoE starter kit Core component.

**Comment by Jenefer-Monroe** [comment]
I'm afraid there isn't, you need at least a single full per user license in order to install and run the kit.

**Comment by JadhavKalpana** [comment]
Hello Jenefer,

Hope you are doing well!

Thanks for the prompt response and details. I need to know few things from
your end about the basic Starter Kit setup requirements and sharing license
details which we are configuring on, please find that below:

·       Microsoft Power Apps Plan 2 Trial

·       Microsoft Power Automate Free

·       Office 365 E1

·       Trial Environment created

These are the few related subscription details we are having. So, on the
basis of this we have couple of questions to ask and need your inputs,

1.       Need to know that the above mentioned subscription is fine to
configure the COE starter kit?

2.       On Microsoft docs link, we have downloaded the latest folder v3.19
and the folder structure is a bit different from the previous one, is that
creating any issue?

3.       Could you please provide us with the license details which are
required for the proper configuration?

Kindly look into this and provide your valuable inputs on the same, I will
be waiting for your response.


Regards,

Kalpana Jadhav

**Comment by Jenefer-Monroe** [comment]
Those licenses are not sufficient. See here for the licenses required
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with

In particular, Power Apps Per User license (non trial), and Microsoft 365 license.

The latest version of the starter kit has Core 3.20.6. Can you share what link you are following that brought you to an old version?

**Comment by JadhavKalpana** [comment]
Hi,

As required,
Please find below link-
 https://aka.ms/CoEStarterKitDownload

**Comment by JadhavKalpana** [comment]
Yes Jenefer, We are using the same link which you have shared.
[image: image.png]

**Comment by Jenefer-Monroe** [comment]
Note that images do not come through when you reply in email, you need to add them in GitHub proper. 

I dont think there is anything else for us to assist with here. Please let us know if you have any other specific questions.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
