### ISSUE TITLE
[CoE Starter Kit - BUG] D4T message - This app uses features that come with a Power Apps premium plan. Start a trial to use these features.

### ISSUE THREAD

**Issue by JonTaylor5** [microsoft/coe-starter-kit#1788]
### Describe the issue

When trying to open the Admin Command Center on a D4T CoE installation I get the following message:

"This app uses features that come with a Power Apps premium plan. Start a trial to use these features.

Next"

I have done previous installations yet have not seen thids message before. 
<img width="557" alt="2022-01-19 11_41_48-Power Apps — Mozilla Firefox (Private Browsing)" src="https://user-images.githubusercontent.com/97525276/150123244-5156cc40-cbff-4aad-8f57-7691e3c84a15.png">

If I start a trial it will work for the trial period then stop so this is not an option. 

Why an I now getting this message when previous installations have not required this? 

Thank you in advance for any help.

### Expected Behavior

Admin - Command Center opens

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponentsTeams_3_11_managed

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

1. Open Admin - Command Center

**Comment by manuelap-msft** [comment]
Please look at #1621 where this issue was already commented on. If the solution is imported into Teams, it is only available to open in Teams and won't be available in the browser.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by JonTaylor5** [comment]
Hi Jenefer,

Thank you for your assistance. It is very much appreciated.

Kind regards,

Jon
