### ISSUE TITLE
[CoE Starter Kit] Apps that are pending compliance justification

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1801]
report on how many apps are pending to get the compliance justification vs the number of emails sent requesting compliance details?

**Comment by manuelap-msft** [comment]
Will be great If we can know who is ignoring the compliance requests

**Comment by Jenefer-Monroe** [comment]
For prod, we do store this in the BPF table, so we could do a "setup" flow similar to what we did for archival flows, that would only be usable in prod to get back the oldest ask in place. 
And then going forward we can just add to the main sync flow to update "oldest ask" like we do with archival. This so its easy to find and also so it works Teams and Prod

**Comment by Jenefer-Monroe** [comment]
see also #1864 while doing this work

**Comment by manuelap-msft** [comment]
This work was completed as part of the June release with the new dashboard.
