### ISSUE TITLE
[CoE Starter Kit] Flow Deleted in Audit Log

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1804]
While working on Audit logs, for the deleted flows - FlowDetailsURL node comes blank. How can we know the flow id of the deleted flow in the Audit Logs. For Created and Edited flows FlowDetailsURL nodes gives the full URL.

**Comment by Jenefer-Monroe** [comment]
Unfortunately it looks like this service has changed its return value for object id in the case of flow actions, and now returns the user GUID that initiated instead. And we do not have access to the flow id. 
We will leave the audit log flows alone, in the event that this was a bug they will fix later, but as of now we cannot actually correlate flow actions with flows and so users will have to rely on the check deleted clean up flows for this.
