### ISSUE TITLE
[CoE Starter Kit - BUG] Nurture install issue

### ISSUE THREAD

**Issue by coeadministrator** [microsoft/coe-starter-kit#1814]
### Describe the issue

Solution "Center of Excellence - Nurture Components" failed to import:

### Expected Behavior

"Center of Excellence - Nurture Components" imported successfully

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

failed to import the whole nurture solution

**Comment by Jenefer-Monroe** [comment]
Assuming you have already installed / upgraded Core as Nurture depends on Core, then please follow the below. 

If you are a GCC, or other non-commercial tenant then you will be blocked by a product issue and should use solution at the bottom of [#888]( https://github.com/microsoft/coe-starter-kit/issues/888).

If not, then please note that we do sometimes see Nurture fail to upgrade on first try but succeed on subsequent attempts. Another product issue which we are unable to resolve but which eventually resolves itself after multiple attempts.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
