### ISSUE TITLE
Fail to Load PowerBI Dashboard for January 2022

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#1820]
### Describe the issue

Flows Connection Reference
 Query 'Flow Connection Reference' (step 'Outer Join') references other queries or steps, so it may not dedirectly access a datasource. Please rebuild this data combination

### Expected Behavior

I expect the PowerBi DAshboard for January 2022

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20.6

### What app or flow are you having the issue with?

PowerBI DAshBoard

### Steps To Reproduce

Downlaod latest version of PowerBi Dashboard.
Load PowerBI Desktop
Enter url of CoE Environment see error

**Comment by manuelap-msft** [comment]
Hello, what version of Power BI Desktop are you using? And are you using the Teams_ or Production_ dashboard?

**Comment by NPrice99** [comment]
HI Manuela

Happy New Year!

It is the full fat version of the production dashboard which came with the January version of the CoE.

The powerbi desktop was downloaded prior to starting.

Regards

Nigel

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by manuelap-msft** [comment]
Awesome, thank you! Happy new year to you too! Let me test this out on my side, I think I don't have the latest version of Power BI installed yet.

**Comment by robertcaretta** [comment]
I'm also having an issue with this version of the Production PBI dashboard and the latest version of PBI desktop application.  Never seen this kind of error before. In my case I am getting an ADFS error when attempting to sign into the CoE environment. 

![2022-01-24_14-26-47](https://user-images.githubusercontent.com/1613085/150992918-38a7c4ea-1f6d-4f60-866c-a2e7d95828ab.png)

**Comment by manuelap-msft** [comment]
@robertcaretta Your error occurs before even loading the dashboard (returning you an Unauthorized error) so I would recommend raising a support ticket with Power BI here as this is outside of the scope of what we can support you with here but looks more like a network configuration error or similar

**Comment by NPrice99** [comment]
Hi @manuelap-msft - have you managed to reproduce this issue ?  Thanks Nigel

**Comment by manuelap-msft** [comment]
Hello Nigel,

I upgraded to the latest version of Power BI desktop just now and opened the production .pbit and am unfortunately not able to repo this - the data loaded without issues.

**Comment by NPrice99** [comment]
Hi Maneula

Sounds like a data issue then.  Do you know what tables that query uses ?

Thanks

Nigel

**Comment by manuelap-msft** [comment]
It should just query the Connection Reference and PowerApps Connector table.

**Comment by NPrice99** [comment]
Hi Manuela

I downloaded A new version of the PowerBI Desktop today and retested this and it now works.

Thanks for your help

Nigel

**Comment by manuelap-msft** [comment]
Thank you so much for confirming! Is that the February version of Power BI Desktop?

**Comment by NPrice99** [comment]
There was !
2.100.1401.0 was released on 21/1/2022 (Even though About still says December 2021).

Regards

Nigel
