### ISSUE TITLE
[AA4PP] Export / Deploy Solution Dependency Validation

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#1821]
**Is your feature request related to a problem? Please describe.**
Currently, AA4PP and solution checker don't report issues with dependencies for solutions exported or requested for deployment.

**Describe the solution you'd like**
Either during the export process or in the PR process it would be good to be able to repo on dependency issues (e.g. missing dependencies, circular dependencies, dependencies in other solutions). This may not be something that fails the export or deployment but would provide makers / approvers feedback on potential issues with the solution earlier in the process to ensure the solution is able to be deployed. To achieve this we'd need to walk the solution dependencies which may be a performance concern. As such, may want to make this configurable on whether to enable or disable these checks.

**Describe alternatives you've considered**
Reporting on dependency issues when a solution is deployed as part of the Pull Request via the process is the current alternative but it's not a complete solution.

@devkeydet please add any color or additional thoughts you have on this.

**Comment by devkeydet** [comment]
I have a little spike/experiment on the concept here:
https://github.com/devkeydet/PrepareSelfContainedSolutionForExport

To enable better performance of this scenario, I will likely try moving the logic from the flows to Custom API implementations in Dataverse.  The downside of this is that anyone who wanted to use those APIs in their dev environment would need to deploy the solution first.  But that's something we could automate from the app.  Imagine, for example, the ALM Accelerator app checks to see if the solution is deployed in the dev environment first, then offers to deploy it if it isn't before running the preparation process.

**Comment by devkeydet** [comment]
After further discussion, we would likely release this as a separate tool from the ALM Accelerator so people wouldn't need to take a dependency on installing the accelerator to see the benefits.  Is anyone aware of an existing community tool that already does this (ex: XrmToolBox extension)?

**Comment by mikefactorial** [comment]
Closing this out as it is now a feature of in-product pipelines and no further investment will be made in the ALM Accelerator for dependency checks
