### ISSUE TITLE
[CoE Starter Kit - BUG] Documentation - incorrect name for flow

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1824]
### Describe the issue

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-environment-components#turn-on-flows

![image](https://user-images.githubusercontent.com/89584709/150646035-06c3490e-8a33-4b1b-8cef-65a68fd8e1fb.png)

Incorrectly named. In the solution it is just called Env Request | Cleanup Environments
![image](https://user-images.githubusercontent.com/89584709/150646078-10bf0b59-c861-4542-8340-4eb3b065f44a.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20.6

### What app or flow are you having the issue with?

documentation

**Comment by manuelap-msft** [comment]
Fixed locally together with the comments from the copy editor after our big setup instruction change. Should go live later today or tomorrow.

**Comment by manuelap-msft** [comment]
docs have been merged to main, should be live soon
