### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to choose a profile

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1831]
### Describe the issue

[ALM Accelerator - BUG]: Unable to choose a profile #1809 should not have been closed as it is still an issue and the profile is not saving or solutions showing even though I have confirmed the steps you asked me to.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220114.1

**Comment by mikefactorial** [comment]
Closing this issue. Reopened #1809. Apologies, @medicineshow closing #1809 was inadvertent.

**Comment by RAWDEMO** [comment]
I just installed the newest version of ALM Acelerator (CenterofExcellenceALMAccelerator_1.0.20220131.1_managed.zip) and ran into this issue.  I'm trying to manually configure the CustomAzureDevOps connector using but I keep getting the following error when I test the GetOrganizations action.

![image](https://user-images.githubusercontent.com/99212564/152881489-9a61fe87-54ea-43fb-8aa5-7729081401ae.png)
