### ISSUE TITLE
[CoE Starter Kit] DLP Impact Analysis for Custom Connector

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#1844]
explore how custom connectors (esp tenant wide ones classified via endpoint filtering) can be included in the DLP editor for impact analysis

**Comment by aliyoussefi** [comment]
Tracking per customer request.

**Comment by samadane** [comment]
Getting more customers ask for this.

**Comment by aliyoussefi** [comment]
Hi @manuelap-msft ,

Wanted to bring this item back up to see if we can get this added to an upcoming release for CoE if we plan to support within the starter kit.

Thank you!

Ali

**Comment by manuelap-msft** [comment]
Closing out. We don't get sufficient information from the product to implement this. Will re-evaluate and re-open if product behaviour changes.

**Comment by NattyG19** [comment]
How are we meant to check for custom connector impacts in an environment if they are not included as part of the review in the analysis app?  This is really important for mission critical solutions and environments with heavy custom connector usage. missing a custom connector when applying to a Prod environment can have large impacts that are high risk to business continuity. 

I checked the CoE backlog and couldn't see anything addressing this, is this in the pipeline or is there another way to do this check?
