### ISSUE TITLE
[CoE Starter Kit - BUG] Need help understanding if / how inventory collected

### ISSUE THREAD

**Issue by LanMorton** [microsoft/coe-starter-kit#1849]
### Describe the issue

We are unable to see the latest activities of PowerApps and Power Platform, Centre of Excellent (COE).
Issue description
We are unable to see the latest activities of PowerApps and Power Platform within Power Platform and Centre of Excellent (COE) just showed the latest dates in Dec 2021; no recent dates show up for apps, flows (created on, last modified date, etc)

### Expected Behavior

We are expecting PowerPlatform provide for us the details of the activities and last modified dates & times for all existing environments, apps, flows, BI reports, cloud connections, etc.; as such information stopped since Dec 2021

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

Upgraded CoE not running properly although we downloaded & installed the right software

### Steps To Reproduce

no latest, recent dates & times for any tool (PowerApps, Flows, connectors, etc.) since Dec 2021

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid we will need more information in order to assist as the CoE is a very large offering and so its unclear what you mean. 

Are you are saying that the reports (Power BI, Power Platform Admin View model driven app) are no longer showing new apps/flows that have been created? 

All these things are collected by the sync flows, you will need to go make sure all the sync flows are still running and passing. 

If you are unsure about how to check this, you may need to seek out a partner to assist here. Or perhaps, given the age of your install, start from scratch in a new environment by following our documentation. [https://aka.ms/coestarterkit](https://aka.ms/coestarterkit)

**Comment by LanMorton** [comment]
Hi Jenefer,
Thank you very much for your message.

You wrote"... Are you are saying that the reports (Power BI, Power Platform Admin View model driven app) are no longer showing new apps/flows that have been created?..." that's right. It doesn't show the latest and recent activities of apps, flows, etc. since 12/2021.

I attach the screenshot here for you. The CoE just display most activities, modified, created dates before 12/2021. I hope you can help to advise us a relevant solution to fix it. Many thanks
Kind regards,
Lan Tran Morton
Senior Dev Operations Engineer (M365)

**Comment by Jenefer-Monroe** [comment]
Hello, screenshots do not work when you reply with them in email, you need to go to GitHub and share them there.

**Comment by LanMorton** [comment]
![POWER-PLATFORM-NOT-BEING-UPDATED-ALL DATES-STOPPED-ON-05 12 2021](https://user-images.githubusercontent.com/98461604/151166758-f075f104-14b6-47dc-8410-5a82015568d6.JPG)
Hi Jenefer, where &how I can send you the screenshot? or can I share my screen with you via Teams?
![POWER-PLATFORM-NOT-BEING-UPDATED-ALL DATES-STOPPED-ON-05 12 2021](https://user-images.githubusercontent.com/98461604/151166977-f944e67e-6bec-4e48-a4e8-535b65191ea4.JPG)

**Comment by Jenefer-Monroe** [comment]
ok yes it appears you are saying that the inventory is not being kept up to date. This picture doesn't help debug though, and we cannot have meetings with our GitHub customers. 

Please note that the starter kit is not a supported product, we just do best effort to assist here. 

You will need to go and see if the sync flows are still running, if its not clear how to do that, you will need to either hire out a partner to assist, or start from scratch in a new environment by following our documentation. [https://aka.ms/coestarterkit](https://aka.ms/coestarterkit)

**Comment by Jenefer-Monroe** [comment]
Someone else asked a similar question today, see Manuela's notes as they might help #1862

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
