### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs Were Collected but Some Missed Due to Truncated Results

### ISSUE THREAD

**Issue by dragunwing** [microsoft/coe-starter-kit#1851]
### Describe the issue

I receive the following email notification when trying to collect audit logs on my large tenant.

_Your audit logs were collected but some were missed do to truncated results in this run .
You will need to use a smaller interval to gather all logs.
Current chunking size: 1 Minute_

Most environments are being logged except for the large, default environment. I've set the TimeInterval-Unit value to 1 minute. How do I set a smaller interval to collect the logging information?

### Expected Behavior

The logs should be collected successfully without the email stating that I need smaller chunks.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Steps To Reproduce

I receive the email notification that requiring smaller chunks each time the Admin } Sync Audit Logs flow runs.

### Anything else?

![AuditLogError](https://user-images.githubusercontent.com/11412139/151186446-3a908c9e-d886-4a12-a4e6-0ad44fb62897.png)

**Comment by Jenefer-Monroe** [comment]
Hello, if you are receiving too many even at 1 minute chunks, then you might just be too big for what this interim solution can provide. The BYOD solution, with which we will integrate later this year, will surface this data natively without having to use the office logs. 

Please see [Power Platform admin center telemetry data export to Microsoft Azure Data Lake](https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate)

**Comment by robertcaretta** [comment]
I am interested in the BYOD solution. Apparently our environment is too big. I have set our environment variables to the lowest setting [documented here](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#before-you-use-the-audit-log-connector) and we are still receiving alerts about smaller chunks. 

![2022-01-31_08-19-57](https://user-images.githubusercontent.com/1613085/151810205-30719f99-abdf-4ae6-a380-f4781e8ad9c0.png)

**Comment by Jenefer-Monroe** [comment]
Hello, those are just examples used to help people configure these variables, it is not intended to be an exhaustive list of options. 
You can continue iterating with these values to see if it will work for you, but you may indeed be too big. 

At this point our team is not assisting with, nor documenting setup of BYOD, it is something that you will need to explore using the Microsoft Product team links. 
Please see: 
https://docs.microsoft.com/en-us/power-platform/admin/self-service-analytics
https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
