### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Flow Errors Incorrect URL

### ISSUE THREAD

**Issue by ashculmsee** [microsoft/coe-starter-kit#1858]
### Describe the issue

The URL sent in the email notification via the Sync Flow Errors flow for a specific failed flow run is incorrect.

The URL sent in the email is as follows:
https://australia.flow.microsoft.com/manage/**environmentsGUID**/flows/GUID/runs/GUID
Selecting this URL opens the general My Flows page 
https://australia.flow.microsoft.com/manage/environments/GUID/flows

**It is missing the / between environments and the GUID**

### Expected Behavior

Clicking on the link in the email notification should bring you to the failed flow run

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Sync Flow Errors)

### Steps To Reproduce

1. Have a flow run fail
2. Click the link in the email sent by "Admin | Sync Template v3 (Sync Flow Errors)"

**Comment by manuelap-msft** [comment]
Hello,

can you check your Power Automate environment variable. We ask for it to be entered with the trailing **/** 
![image](https://user-images.githubusercontent.com/55705669/151323093-7b166e57-96ba-47c4-9b7f-22c30429d801.png)

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
