### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to turn on Flows after import of 3.20.6

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#1860]
### Describe the issue

Hello COE Team,

I hope you're well. 

I've installed the "Center of Excellence - Core Components" version "3.20.6" today, and a number of our Flows turned off, and won't turn on. 

The error I receive when I try and turn on a Flow, example: "Admin | Sync Template v3 (Apps)" is that I child Flow is not turned on.

Error is:
Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id '9301f01a-GARRY_HIDING_THE_GUID' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

![image](https://user-images.githubusercontent.com/68440710/151354139-418a83f8-cef9-45de-856d-31a0c8a85994.png)

When I open one of the Flows that won't turn on I see the below:

![image](https://user-images.githubusercontent.com/68440710/151354350-32f51f9e-0671-4c3f-b86f-9f05005cb393.png)

I've searched for the child Flow with the GUID above and cannot find it anywhere in our environment. 

![image](https://user-images.githubusercontent.com/68440710/151354461-d7c11de5-4326-4023-ad23-fdd97cae3daa.png)

Sorry to be a pain. What am I doing wrong please? 
Also, what is the actual name of the child Flow it is trying to reference please?

In advance, like always, thanks for your brilliant help.

Garry

### Expected Behavior

Flows that are turned off, are turned on without a child workflow dependency. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20.6

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps) ... although several other Flows won't turn on.

### Steps To Reproduce

1. Imported solution 3.20.6, we were on 3.18
2. Import didn't have any errors, but several Flows were turned off that were turned on before we installed this latest solution:

Admin  Sync Template v3 (Sync Flow Errors)
Admin  Sync Template v3 (PVA)
Admin  Sync Template v3 (Model Driven Apps)
Admin  Sync Template v3 (Flows)
Admin  Sync Template v3
Admin  Sync Template v3 (Apps)
Admin  Sync Template v3 (Custom Connectors)
Admin  Sync Template v3 (Desktop flows)

When trying to turn on one of the Flows above, get the error show in the "Describe the issue" section.

**Comment by manuelap-msft** [comment]
Hello,

thanks for the super awesome detailed error description - so helpful! 

Can you check if all the child flows listed here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows are turned on? We moved some of the work that the sync flows are doing to child flows and those need to be turned on first before the parent flow can be turned on. My guess is that maybe HELPER – Maker Check is not turned on.

Let me know what you find!
Manuela

**Comment by GarryPope** [comment]
Hello Manuela,

Thanks for the quick response. You are correct those Flows were not turned on. All working perfect now, please close this ticket.

Thanks very much, and have a nice day,

Garry

**Comment by manuelap-msft** [comment]
Perfect! Thanks for letting me know.

We are working on making it easier to discover if new flows have been added to the solution that need turning on - our idea is to add a new screen in the Command Center that shows the flows in the CoE kit, flags once that are mandatory for the sync that are not turned on and allows you to turn them on from there. Had a bit of a setback implementing this so not quite ready for the next release but hopefully the one after - fingers crossed!

Have a good rest of the day,
Manuela
