### ISSUE TITLE
Orphaned Object to Clean email to manager

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#1861]
### Describe the issue

The user has left the organization and it sent an email to the manager to reassign the flow to another user. The manager reached out to me and I used the set flow permission app to change the owner and it was successful. But yesterday manager received an email again for the same flow to reassign ownership. If ownership is already changed then why the manager is receiving this email again? below is the screenshot of the cloud flow owner and manager email. Please advise

Flow Ownership 
![image](https://user-images.githubusercontent.com/75992078/151380853-15868d05-2a38-4e07-a98e-4d738bdf3d0d.png)

Email
![image](https://user-images.githubusercontent.com/75992078/151381066-93128cec-964e-4746-9694-21a7312c185c.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Orphaned Objects to Clean

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of the app now that you assigned the new owner?

**Comment by Jenefer-Monroe** [comment]
can you find that flow in the Set Flow Permissions app again? To see if the assignment is still in place?

**Comment by Jenefer-Monroe** [comment]
And then also find the flow in the Power Platform Admin View app, and see if its still marked oprhan
![image](https://user-images.githubusercontent.com/89584709/151385831-abae305e-9d98-451f-a431-cef1e7819784.png)

**Comment by AkashPatel136** [comment]
I am assuming that the manager will not receive the email again?

**Comment by Jenefer-Monroe** [comment]
Hello. Can you please provide an update? I presume this has not repro-d again?

**Comment by AkashPatel136** [comment]
The user has not received an email again as of now.

**Comment by Jenefer-Monroe** [comment]
wonderful

**Comment by AkashPatel136** [comment]
Hi @Jenefer-Monroe 

Not sure if this is the same case but the User is receiving compliance email and the user has been approved for deletion 3 times and she keeps getting these emails after approval for deletion. Ultimately I had to delete the app on her behalf from the admin center.

**Comment by Jenefer-Monroe** [comment]
Completely different area of the starter kit, so not related to this. 
In order for me to investigate though I would need more details, in a new bug. 
For example you would need to show me what you mean (compliance v archvial... what email was it?)
And you would need to go look up the flow in the archival tables. 
Since the repro is gone now I suggest you post if you see that again. 
Thanks for using CoE
