### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by kabutows** [microsoft/coe-starter-kit#1868]
### Describe the issue

We had the following error on Admin | Sync Template v3 (Desktop flows):

'Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'

### Expected Behavior

We need that this flow work properly because we want to have view of the desktop flows that were created inside our tenant

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

**Comment by manuelap-msft** [comment]
You've hit one of our known limitations for large desktop flows: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#large-desktop-flows - unfortunately there's nothing we can do here.

You may want to sign up to join the private preview for the Automation CoE Starter Kit: https://docs.microsoft.com/en-us/power-platform/guidance/automation-coe/automation-coe-starter-kit which is addressing these cases differently then the CoE starter kit.
