### ISSUE TITLE
Pipelines: Validate Datasource Environment Variables in Pipelines

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#187]
**Describe the solution you'd like**
Need to ensure that Datasource Environment Variables are handled correctly and in the same manner as standard Environment Variables in the ALM Accelerator Pipelines

**Comment by devkeydet** [comment]
duplicate
https://github.com/microsoft/coe-starter-kit/issues/102

**Comment by mikefactorial** [comment]
Closing as duplicate of #102
