### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by marcuss75** [microsoft/coe-starter-kit#1872]
### Describe the issue

Affected Version: CoE Starter Kit January 2022

The import of the solution "CenterofExcellenceNurtureComponents_2.6_managed.zip" has failed for some reason without any meaningful log information.
I've retried multiple times, sometime setting the variables and sometime leaving them empty, and at the end I've been able to import the solution.
One the import completes successfully, looking into the solution imported, all the Apps contained seems to be duplicated, and together with the original App, there are other with a naming convention presenting a suffix at the end with a datetime, like "Maker Assessment" and "Maker Assessment_202001251025", "Maker Assessment_202001251045", etc.
No one of these duplicated Apps can be removed, because all of them seems to be associated with the managed solution.

Trying to remove the solution, only the latest App for each type will be removed, and all the other remain into the system.
However, those Apps can be removed manually, because they don't result as behaving to any managed solution.

In other cases, doing the same for a customer, I've not been able to import the solution at all.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

All Apps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
