### ISSUE TITLE
DLP Violation for ALM Accelerator for Advanced Maker Canvas APP

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#188]
**Describe the bug**
After I Imported Power Platform DevOps ALM Solution and when I open the Canvas App it throws DLP violation error. I have added the custom connector, Power Apps for Makers, Dataverse connector into my DLP policy but not sure why it is giving DLP violation error when I have all the connector added to the DLP policy. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/115627762-906d2700-a2cd-11eb-8c22-ba008e299aa6.png)

**Additional context**

**Comment by jenschristianschroder** [comment]
Please check the scope of your DLP policy.

If scope is environment you cannot unblock connectors that are blocked in a policy with org (tenant) scope.

If connectors are blocked in policy with org (tenant) scope you need to have changes made to either the blocking policy or have a new policy that specifically unblocks for your environment

**Comment by AkashPatel136** [comment]
We have a policy for a Dev environment and I have added a custom connector at a policy level, not at an environment level.

**Comment by AkashPatel136** [comment]
I think it uses 4 connector 

1. Power Apps for Makers
2. Logic FLows
3. Common Data Service
4. Custom Connector

I do not see any connector in DLP Policy for Logic Flows.

**Comment by AkashPatel136** [comment]
Thank you

Interesting part is that when I open the canvas app in edit mode I am able to use the app and push to git.

Thank You,
Akash Patel
________________________________
From: jenschristianschroder ***@***.***>
Sent: Friday, April 23, 2021 6:10:21 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Patel, Akash ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [microsoft/coe-starter-kit] DLP Violation for ALM Accelerator for Advanced Maker Canvas APP (#188)


External email. Confirm links and attachments before opening.


@devkeydet<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdevkeydet&data=04%7C01%7Cakash.patel1%40chemours.com%7Ca2eaa3149f0444be7b5d08d906400150%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637547694286286904%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aduEKj6L1Rphk9%2BYZxsGynmjH%2BsZ5V6p6%2FgHquImgaM%3D&reserved=0>, good point. I have created #191<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F191&data=04%7C01%7Cakash.patel1%40chemours.com%7Ca2eaa3149f0444be7b5d08d906400150%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637547694286296899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oUHOrA5kQpoQpTQOUaFv0zdrUiVD5OVOC38BGRvPVJE%3D&reserved=0> to follow up on this

@AkashPatel136<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAkashPatel136&data=04%7C01%7Cakash.patel1%40chemours.com%7Ca2eaa3149f0444be7b5d08d906400150%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637547694286296899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2eDCBSJme1V8wU3%2BA6SbH3vPeSOtaUXrG7nVnvU9l%2Fo%3D&reserved=0>
You are right, those are the 4 connectors in use.

Logic Flows connector is the connector used to call Power Automate flows from Canvas Apps. It is not available as other connectors in the DLP policy editor.

Will need to do a little more investigation into this as the UI shows different connectors depending on where you check this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F188%23issuecomment-825553560&data=04%7C01%7Cakash.patel1%40chemours.com%7Ca2eaa3149f0444be7b5d08d906400150%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637547694286306892%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jCnjnHoSUKt72WOJ28xBJrIOqjldBR2CZ1baI7vCHuw%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASDYYDQLHKF6BDSMNTHALVLTKFBQ3ANCNFSM43LHH36Q&data=04%7C01%7Cakash.patel1%40chemours.com%7Ca2eaa3149f0444be7b5d08d906400150%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637547694286306892%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7SMyOsm3GFG6tu%2BFy%2Fo2ZBGjSCPtOw%2B8itiXsbTjkXw%3D&reserved=0>.

This communication is for use by the intended recipient and contains information that may be privileged, confidential or copyrighted under applicable law. If you are not the intended recipient, you are hereby formally notified that any use, copying or distribution of this e-mail, in whole or in part, is strictly prohibited. Please notify the sender by return e-mail and delete this e-mail from your system. Unless explicitly and conspicuously designated as "E-Contract Intended”, this e-mail does not constitute a contract offer, a contract amendment, or an acceptance of a contract offer. This e-mail does not constitute a consent to the use of sender's contact information for direct marketing purposes or for transfers of data to third parties.


https://www.chemours.com/en/email-disclaimer

**Comment by jenschristianschroder** [comment]
We are still investigating internally and will provide an update soon.

**Comment by AkashPatel136** [comment]
Thank you

Thank You,
Akash Patel
________________________________
From: jenschristianschroder ***@***.***>
Sent: Thursday, April 29, 2021 3:59:53 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Patel, Akash ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [microsoft/coe-starter-kit] DLP Violation for ALM Accelerator for Advanced Maker Canvas APP (#188)


External email. Confirm links and attachments before opening.


We are still investigating internally and will provide an update soon.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F188%23issuecomment-829023056&data=04%7C01%7Cakash.patel1%40chemours.com%7C90e1fdc518ee46c7f6c608d90ae4c599%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637552799948492512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ikaq%2BWCl%2FMiYyQXkhkYsz21569LajxHPemsK90ekVKg%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASDYYDR6X6DQE3XNGS4IVFTTLEGXTANCNFSM43LHH36Q&data=04%7C01%7Cakash.patel1%40chemours.com%7C90e1fdc518ee46c7f6c608d90ae4c599%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637552799948502505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yUe9MgoUevIYFJUajB%2B0%2F3pKM64DFkDuCzB%2BPl%2BID20%3D&reserved=0>.

This communication is for use by the intended recipient and contains information that may be privileged, confidential or copyrighted under applicable law. If you are not the intended recipient, you are hereby formally notified that any use, copying or distribution of this e-mail, in whole or in part, is strictly prohibited. Please notify the sender by return e-mail and delete this e-mail from your system. Unless explicitly and conspicuously designated as "E-Contract Intended”, this e-mail does not constitute a contract offer, a contract amendment, or an acceptance of a contract offer. This e-mail does not constitute a consent to the use of sender's contact information for direct marketing purposes or for transfers of data to third parties.


https://www.chemours.com/en/email-disclaimer

**Comment by AkashPatel136** [comment]
Hello @jenschristianschroder, 

Any update on the issue. we are not able to use the app at all. Also when I try to export the app it shows an error message. An error message is below. 
![image](https://user-images.githubusercontent.com/75992078/117037629-b5ea2f80-acd4-11eb-9866-ce105c4c9653.png)


Custom Connector owner is receiving this error message.

**Comment by AkashPatel136** [comment]
Hi @jenschristianschroder  

I was able to use the app in play and did not receive the error message. 

Thank You so much for your help.
