### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Connectors) does not fetch all connectors because of terminate action

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#1884]
Admin | Sync Template v3 (Connectors) flow has terminate action after Specialty Connectors action which gets HTTP and Spatial connectors. Because of this none of the standard connectors are not fetched from the Apps

<img width="304" alt="image" src="https://user-images.githubusercontent.com/8307644/151708361-3d43cb5b-3266-4fc8-aae8-fffd88bc4f59.png">

There are only those specialty connectors in the DB and I guess that this is the reason why Apps sync flow is failing in my environment 

<img width="293" alt="image" src="https://user-images.githubusercontent.com/8307644/151708259-de67b8b5-913f-44da-b797-582031c8fd8f.png">

<img width="557" alt="image" src="https://user-images.githubusercontent.com/8307644/151708523-f724c645-5ddf-4054-90dc-32f314e2f99f.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

January 2022 (3.20)

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

**Comment by Jenefer-Monroe** [comment]
Hello, this is covered by #1751 and fixed in the current release 3.20.6
