### ISSUE TITLE
[CoE Starter Kit - BUG] canvas apps do not work after upgrading a solution to newer version

### ISSUE THREAD

**Issue by powerplatadmin** [microsoft/coe-starter-kit#1885]
### Describe the issue

Once a COE Kit is upgraded to new version, some of the canvas apps like DLP editor do not work and provide a message close to the following:

**The request was not sent or there was no response from the server. Check your internet connection. Server Response: Makers failed: null**

### Expected Behavior

Once you upgrade your COE Kit, the Canvas Apps within the components will have error message like the one below:

_The request was not sent or there was no response from the server. Check your internet connection. Server Response: Makers failed: null_

A workaround to this problem is to edit the apps and save the app (somehow allows saving without making any changes in this instance), which creates a new solution layer on top of the apps. This then removes the error message even when the solution layer will be removed and the apps work as expected.

### What solution are you experiencing the issue with?

Core, All Solution Components

### What solution version are you using?

3.2.0

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

- Update your COE Kit with a new version of the core components.
- Launch your canvas apps -The following error message will appear once you try to launch the canvas apps:
**The request was not sent or there was no response from the server. Check your internet connection. Server Response: Makers failed: null**

**Comment by Jenefer-Monroe** [comment]
Hello, it sounds like you have hit some product issue here, perhaps related to connections.

**Comment by powerplatadmin** [comment]
> 

That sounds like a possibility, thank you for taking the time to reply :)
