### ISSUE TITLE
CoE Starter Kit - Set Flow Permission Orphaned Flow

### ISSUE THREAD

**Issue by AkashPatel136-zz** [microsoft/coe-starter-kit#1894]
**Is your feature request related to a problem? Please describe.**
When I have to clean up orphaned Flow there is no way for me to see if this flow is active or stopped or in the suspended stage. It will help me because if the flow is not modified by a certain month and if it is in the stopped stage then I can just delete them without any questions. 

**Describe the solution you'd like**
This is what I was looking for where I can see each flow stage.
![image](https://user-images.githubusercontent.com/75992078/151866323-e7e04c73-a95a-49f6-ab21-afb595afcf2d.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Jenefer-Monroe** [comment]
Unfortunately, the flow state is not something that we keep up to date in the inventory, for example turning a flow off does not change its modified date, so we would need to call back to the product for every row in the table, causing the page to be very slow to load. 

I will put this on our backlog though to review what is shown on this screen to see if we can review and make it more actionable.

**Comment by AkashPatel136** [comment]
Thank You so much
