### ISSUE TITLE
User keeps receiving emails for compliances

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#1899]
### Describe the issue

I had a few users who complained that they keep receiving submit compliance details emails even after they have selected to delete them. I have attached an email that they receive. 

![image](https://user-images.githubusercontent.com/75992078/151967958-54bc5593-1d9f-46ad-9264-b4f092892333.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20.6

### What app or flow are you having the issue with?

Admin - Compliance request complete apps v3

**Comment by Jenefer-Monroe** [comment]
Hello, are you running the clean up flows in Core? When an app is deleted, the inventory does not know this, until those flows run. 

Please walk the [setup up instructions for inventory](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) to ensure the flows listed in all the sections are turned on, running, and passing.

**Comment by Jenefer-Monroe** [comment]
Please validate if the app in question still exists in the tenant, and if it still exists in the inventory.

**Comment by AkashPatel136** [comment]
Hello

The application does exist in the team environment. As you can see below from the PPAC and Admin Model-Driven app. 

PPAC
![image](https://user-images.githubusercontent.com/75992078/152001064-0a64a16a-3893-4155-b4f8-66e86685461d.png)

Model-Driven App
![image](https://user-images.githubusercontent.com/75992078/152001178-70a2d85d-22da-4c73-974f-48549966fdd2.png)


Also when the user tried to delete the app from the Developer Compliance Center user got an error message. 

Developer Compliance Center Error
![image](https://user-images.githubusercontent.com/75992078/152001294-20a9786d-7d20-426d-abe9-8495b003968e.png)

**Comment by Jenefer-Monroe** [comment]
Yes, that means that they did not delete the app. And so they will continue to get these messages until the app no longer qualifies or until they delete it. 

Per the error message they are seeing, the app is part of a managed solution install so we cannot delete it for them from within the tool. They will need to go manually delete it, or the solution as a whole.

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for starter kit team. 
Thanks for using CoE
