### ISSUE TITLE
Pipelines: Add solution checker / sarif reporting

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#19]
Solution Checker emits sarif files.  Let's incorporate into build:
https://develop1.net/public/post/2020/02/06/solution-checker-in-azure-devops-pipeline

**Comment by rpothin** [comment]
Benedikt has written great articles on this topic too:
- [ALM – Using “Solution Checker” in a pipeline](https://benediktbergmann.eu/2020/02/23/alm-using-solution-checker-in-a-pipeline/)
- [ALM – Use Results of Solution Checker](https://benediktbergmann.eu/2020/03/06/alm-use-results-of-solution-checker/)

**Comment by mikefactorial** [comment]
This has been implemented in the latest version of the pipelines. Closing this issue.
