### ISSUE TITLE
Notify Admin when App Registration secret expires

### ISSUE THREAD

**Issue by BenediktBergmann** [microsoft/coe-starter-kit#1905]
**Problem:**
As an Admin of a Power Platform installation one usually has to maintain a list of App Registrations for different purposes (Integrations, ALM, Automation and all of them for different environments). Since the Secrets of those are valid for max of 24 months (if not created otherwise through PowerShell) it can be hard to maintain/manage those before parts of the installation failed because of an expired secret.

**Possible solution**
One possible solution could be a scheduled flow that checks all App Registrations and sends a status mail to some admin. As described here:
https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/use-power-automate-to-notify-of-upcoming-azure-ad-app-client/ba-p/2406145

Another option (and in my opinion maybe better) would be some sort of App (Canvas or Model-driven) where an Admin could see the current status and gets only notified a certain amount of time before the expiration is due.

**Comment by manuelap-msft** [comment]
Great idea, this is relevant for the CoE Starter Kit where we have app registrations for connecting to the Audit Log and the M365 Message Center as well. 

Would you see this being added to the [Admin - Command Center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#admin---command-center) app as valuable?

**Comment by BenediktBergmann** [comment]
Yeah sure. I don't think it has to be its own App. Just somehow part of the CoE Starter Kit.
In the mentioned post it just notifies the admins via mail. Maybe that could be the first part/version since it might be easier than building some Canvas App (parts) around it.

**Comment by manuelap-msft** [comment]
Closing out as we're unable to deliver on this.

**Comment by BenediktBergmann** [comment]
@manuelap-msft may I ask why you are unable to deliver this?

**Comment by manuelap-msft** [comment]
It's not directly related to CoE activities. Azure governance is not part of the scope of the CoE kit. This ask has also not come up with other customers.
