### ISSUE TITLE
[ALM Accelerator] Feature Request: CLI / GitHub Actions / Az DevOps Tools

### ISSUE THREAD

**Issue by Laskewitz** [microsoft/coe-starter-kit#1909]
**Is your feature request related to a problem? Please describe.**
I really like the ALM Accelerator, but I notice that some people would love to customize the ALM Accelerator and take bits and pieces from it to reuse it within their own pipelines.

**Describe the solution you'd like**
I would love to see a CLI, GitHub Actions, or Azure DevOps tools that are reusable in pipelines. The quickest solution might be to reuse the PowerShell that is being used in certain YAML templates and convert that into a command, action, or azure devops step. 

Examples of commands, actions, or steps could be:

- Install PAC, Modules, etc
- Share Canvas App with AAD Group
- Set Dataverse AAD Group Teams
- Activate Flows
- etc, etc...

**Describe alternatives you've considered**
The alternative is to keep using the ALM Accelerator as is, but I think this could make it easier to consume when customers don't want to use the solution as is but would prefer.

**Comment by BenediktBergmann** [comment]
I do agree. All the Templates should be Tasks in the Build Tools.

My understanding is/was that the CoE Team "tests" the ALM process to detect gaps in the Build Tools. The Team which builds the Build Tools can then close those gaps.

**Comment by Laskewitz** [comment]
> My understanding is/was that the CoE Team "tests" the ALM process to detect gaps in the Build Tools. The Team which builds the Build Tools can then close those gaps.

I think this is the case, but in the meantime (until the team fixes this) this would be a good option. I mean - I'm not sure how fast the team is with fixing the gaps - it might take a while...

**Comment by Laskewitz** [comment]
Also - maybe this is the wrong place. I know Wael Hamze runs the Power DevOps Tools (https://github.com/WaelHamze/dyn365-ce-vsts-tasks) project. It might be something for that project. I believe those are also based on PowerShell so it could be an "easy" addition.

**Comment by devkeydet** [comment]
We agree with you and are actively working with the pac/build tools/github actions teams.  For now, your best bet is to use the code snippets in your own pipelines.

**Comment by BenediktBergmann** [comment]
I think adding those to Waels tools might be a really good workaround.

**Comment by mikefactorial** [comment]
Closing this out as there's no immediate action item. We as a team are contributing back to the Power Platform CLI where possible to cover the request here. Either by means of actual code contributions or collaboration with the owners of the Power Platform CLI and tasks.
