### ISSUE TITLE
[CoE Starter Kit - BUG] your issue - audit log data

### ISSUE THREAD

**Issue by felipePP8345** [microsoft/coe-starter-kit#1910]
### Describe the issue

Hi
I've gone through the documentation several times trying to set up the audit log.
Is the "Tenant ID" different from "PublisherIdentifier"?
Asking the quesiton because the wording in the documentation is a bit confusing: 

"Paste the directory (tenant) ID—copied earlier from the App Registration overview page in Azure AD—into the Tenant field, and then paste the Tenant ID into PublisherIdentifier."

In no other place in the doc seems to be a reference to  "PublisherIdentifier" 

![Evidence](https://user-images.githubusercontent.com/88781282/152132913-3f9cd73d-3d14-4ee8-8331-e8bb82678d47.png)

This seems to be the only reason I can think of for this connector to fail

![Evidence 3](https://user-images.githubusercontent.com/88781282/152133204-4f3cc463-69e2-4053-b0c5-f9b99120fc21.png)

I have gone thorugh all common issues.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

audit log - custome connector

**Comment by manuelap-msft** [comment]
Hello - it's the same info, you paste the Tenant ID into Tenant ID and PublisherIdentifier. The error message you are receiving is related to lack of permission to view this data. Pre-reqs for viewing Audit Log are in this article https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?preserve-view=true&view=o365-worldwide#before-you-search-the-audit-log

And here are some frequent issues we see:
![image](https://user-images.githubusercontent.com/55705669/152141823-863c8565-3268-4059-abd0-cc21f5f455da.png)

See our docs for further info on those:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

I would first make sure that you can view the Audit Log in the Security and Compliance Center.

**Comment by manuelap-msft** [comment]
Unfortunately we don't have other resources for troubleshooting here. Do you know if the Audit Log has been enabled recently? It sometimes can take up to 24hrs for the API to work. Other than that I would make sure the App Registration is set up with the correct permissions (maybe you have missed the "Grant access to [org]" step?

**Comment by Jenefer-Monroe** [comment]
I don't think this will resolve for you, but do note that per #1880 we did have a documentation bug there in the [start subscription](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content) section. It should be:

4. Paste the **directory (tenant) ID**&mdash;copied earlier from the **App Registration** overview page in Azure AD&mdash;into the **Tenant** field

5. Paste the **Application (client) ID** into **PublisherIdentifier**.

6. Select Test Operation.

That said, the error message is not explained by this discrepancy so I'm not sure it will help

**Comment by Jenefer-Monroe** [comment]
I think the issue for you is going to be in the Azure subscription. I don't think you have setup the correct API Permissions. Please be sure it looks like this when done

![image](https://user-images.githubusercontent.com/89584709/154342631-ce86bfd8-5226-44c0-81bb-2ac07ec73409.png)

**Comment by felipePP8345** [comment]
Hi Jenefer. 
Thank you.
I do in fact have all those permissions in place.
![image](https://user-images.githubusercontent.com/88781282/154420546-36741459-9bb7-4277-a490-8fcb8a62884d.png)

I'm also fullfilling  all Pre-reqs for viewing Audit Log: [](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?preserve-view=true&view=o365-worldwide#before-you-search-the-audit-log)

So im not sure what is it that im doing wrong.

**Comment by Jenefer-Monroe** [comment]
Are you a commercial tenant? Or something like GCC etc?

**Comment by felipePP8345** [comment]
Yes, commercial tenant.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
