### ISSUE TITLE
[ALM Accelerator - BUG]: Update Solution XML with Build Number Step Fails

### ISSUE THREAD

**Issue by GaborVig** [microsoft/coe-starter-kit#1912]
### Describe the issue

I'm having some issues around deploying a solution to the validation environment using the ALM Accelerator for Power Platform canvas app. Following the deploy-validation-solutionName pipeline trigger the build_and_deploy_job fails at the Update Solution XML with Build Number step.  It seems the PowerShell script can't find the solution package folder. 
I checked and the solution package folder exist in the source branch. 

**Error:**
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\.ps1'"
Get-ChildItem : Cannot find path 'D:\a\1\s\ALM-PowerPlatform-Sandbox\SolutionName\SolutionPackage' because it does not exist.
At D:\a\_temp\.ps1:3 char:1
+ Get-ChildItem -Path "D:\a\1\s\ALM-PowerPlatform-Sandbox\PowerPlatform …
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (D:\a\1\s\ALM-PowerP…ion\SolutionPackage:String) [Get-ChildItem], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
##[error]PowerShell exited with code '1'.
Finishing: Update Solution XML with Build Number

### Expected Behavior

The build deploy-validation-solutionName pipeline completes without any errors.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220114.1

**Comment by mikefactorial** [comment]
@GaborVig can you verify what the name of your solution is? Looks like it's looking for a solution named SolutionName? Is that correct? If not verify the following in your YAML pipeline.

variables:
- group: alm-accelerator-variable-group
- name: SolutionName # variable Name  (DO NOT CHANGE THIS VALUE) 
  value: 'SampleSolution' #Replace with the actual name of the solution you are building. (NOTE: Not the Display Name)

**Comment by GaborVig** [comment]
The solution name is fine. Please see another error example:
"Get-ChildItem : Cannot find path 'D:\a\1\s\ALM-PowerPlatform-Sandbox\PowerPlatformALMTestSolution\SolutionPackage' because it does not exist."

I think the problem is when I click on "deploy solution" using the canvas app with advanced settings off and with target "validation" selected. The pipeline triggers with reference to the "PowerPlatformALMTestSolution" branch which gets created when the first time the solution is committed from the canvas app without the solution package path. It seems the source branch settings under the validation profile gets ignored and defaults to the "PowerPlatformALMTestSolution" in my case. Also tried to deploy the solution with the advanced settings on, but in this case, the pipeline didn't get triggered at all.

**Comment by mikefactorial** [comment]
@GaborVig thanks for the details. This may be a bug. The deployment to the validation environment should result in a Pull Request in Azure DevOps from your personal branch e.g. yourusername-solutionname to the solution branch PowerPlatformALMTestSolution.

![image](https://user-images.githubusercontent.com/42348035/152201043-d0ff875e-5acd-4dc4-b706-85397a21983a.png)

Can you verify what the PR that the deployment created is targeting as both source and target?

**Comment by GaborVig** [comment]
No pull request gets created. Only the pipeline starts and fails as before:
Cannot find path 'D:\a\1\s\ALM-PowerPlatform-Sandbox\PowerPlatformALMTestSolution\SolutionPackage' because it does not exist."

I also tried to set the deployable deployment settings on the related Validation profile back to "Not Allowed" how it was originally configured. Now I can only select Test and Prod targets as expected. When I select target Test - deploy solution no pull request gets created, but the 
deploy-test-PowerPlatformALMTestSolution pipeline gets triggered which fails with the same error as before.  

Finally, I tried to commit to the yourusername-solutionname branch then deployed the solution with source  yourusername-solutionname and target PowerPlatformALMTestSolution (Advance settings on). This time the pull requested got created. 

![image](https://user-images.githubusercontent.com/78961804/152238105-be7b7f59-d725-497c-913e-df03065e8a73.png)

I'm getting now the following error message:
![image](https://user-images.githubusercontent.com/78961804/152238728-dbb20d43-ceb5-4dbd-8c41-ba94e1de64f3.png)

**Comment by mikefactorial** [comment]
@GaborVig based on the error message it looks like there is an issue with the ServiceConnection variable on the deployment pipeline i.e. it is trying to connect to undefined.crm.dynamics.com. Double check this in your pipeline. Docs are here (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-environment-and-service-connection-required)

![image](https://user-images.githubusercontent.com/42348035/152251295-d9f260be-1c4b-420b-a911-745d023e8c0a.png)

That being said. I'm still at a loss to determine why your first run failed the way it did and, assuming that the ServiceConnection is the issue, how it got into the state it's in. Can you share your export pipeline log? If not here then v-mikeochs[at]microsoft[dotcom]

**Comment by GaborVig** [comment]
Following the ServiceConnection variable update, the pipeline started working as expected. I will share the pipeline log shortly with you. Thank you for your help.

**Comment by mikefactorial** [comment]
Hey @GaborVig,
Noticed this was reopened. If you have any followup questions. Feel free to open a new issue and reference #1912. Closing as there's nothing more to do here.
