### ISSUE TITLE
Be able to view CoE Dash board from another Tenant

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#1916]
**Is your feature request related to a problem? Please describe.**
I manage two tenancies and I run the CoE in both.  I frequently get asked to view the DEV tenancy's report from the production tenancy.

**Describe the solution you'd like**
I would like to be able to view the PowerBI Dashboard for the CoE from another tenancy

**Describe alternatives you've considered**
I have tried viewing the PowerBI report from another tenancy, but I have to use my username for the tenancy the report is on.  Attempts to share the report using the "Share" button are refused . "This user is not in this domain"

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

unfortunately that's not something we can help with, the CoE kit currently does not support multi-tenancy. There's two approaches I've seen customer take who needed this - one was using Dataflows to move data from one tenant into a "main" tenant, typically this was done when all-up reporting across all tenants needed to be done, or what might work for your scenario is adding the account you wish to use as a guest user to the second tenant so the share would work. Although I have to admit I'm not familiar how sharing with guest users works in Power BI.

Sorry we couldn't be of further assistance here,
Manuela
