### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrading Coe D4T core 3.10 > 3.12

### ISSUE THREAD

**Issue by A-Demir-ilx** [microsoft/coe-starter-kit#1917]
### Describe the issue

Hello,

I am getting the below error when I try to upgrade the 3.10 version of the CoE Starter kit Core components for teams to version 3.12.

Solution "CenterofExcellenceCoreComponentsTeams_3_12_managed.zip" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: 556370d8-9179-43ae-a6cc-c00e6c2effc8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Power Platform opschonen - Clean resource, Id: 0abe16bd-9e6c-ec11-8943-000d3a2641df, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

admin_PowerAppsforAdminsCoEConnection

### Steps To Reproduce

Upgrade from 3.10 to 3.12

**Comment by manuelap-msft** [comment]
Hello,
looking at the error message, can you confirm you have created a workflow called  **Power Platform opschonen - Clean resource** as part of extending the kit?

**Comment by A-Demir-ilx** [comment]
Hi Manuela, I see that the problem is related to the cloud flow which uses the same connection. I have changed the connection of mine custom flow and now it's working.

Thanks!

**Comment by manuelap-msft** [comment]
Great, thanks for confirming!
