### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor V2 missing information

### ISSUE THREAD

**Issue by thondal-evry** [microsoft/coe-starter-kit#1919]
### Describe the issue

On entering the dlp editor there is no buttons or anything other than the main title across the screen:
![bilde](https://user-images.githubusercontent.com/55357093/152351152-cb4aed38-a138-4604-bee5-7c665abe35dc.png)

### Expected Behavior

Should show policies and connectors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

dlp editor

**Comment by manuelap-msft** [comment]
Hello,

I don't repo this, can you help with debugging

- are you assigned the Power Platform Admin role?
- if you check aka.ms/ppac can you see DLP policies there?
- If you open the app in edit mode, does it show any errors?

Please note that this app will only work for Power Platform Admins with access to the tenant, and not Environment Admins who only have access to a few environments. 

Manuela

**Comment by thondal-evry** [comment]
I was able to view some data when creating a test dlp manually in the standard DLP editor. 

But the DLP editor states that you can create a new policy, but I cannot see any button for this?

"Use the DLP Editor to view how apps and flows in your tenant are impacted by DLP Policies. Select an existing DLP Policy or create a new one, update connector groups and environments and view the impact your changes would have on existing apps and flows before updating the policy. Review and save your changes. Select an environment from the menu to view all DLP policies applied to this environment."

I've also edited the app and there is no hidden button to create a new policy from here either.

**Comment by manuelap-msft** [comment]
We had to remove the ability to create new DLP policies from the DLP Editor due to some product limitations (in the admin connector). Our recommendation is to create a policy in the Power Platform Admin Center with your desired connector combination, don't assign it to any environments at first, then go to the DLP Editor to pick that policy and apply it to environments there.

Let me know if you need further help or if this can be closed!
Manuela
