### ISSUE TITLE
export-MySolution-to-git-branch error

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#193]
**Describe the bug**
As per documentation, I have to give Allow permission to Contribute, Contribute to pull requests, and Create a branch but still get an error, Not sure if I have missed permission. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/115934391-eae9bd00-a45e-11eb-990b-60d4bdaa6a2f.png)

![image](https://user-images.githubusercontent.com/75992078/115934518-2f755880-a45f-11eb-9a8e-75553866c26c.png)

![image](https://user-images.githubusercontent.com/75992078/115934522-32704900-a45f-11eb-8a0d-017904fbbe39.png)

**Additional context**

**Comment by mikefactorial** [comment]
@AkashPatel136 the error message you are seeing "Pushes to this branch aren't permitted; you must use a pull request to update this branch" is expected if you are attempting to push to a branch that has Branch policies applied. You can't push to a branch with branch policies applied that require a Pull Request. More info here. https://developercommunity.visualstudio.com/t/tf402455-pushes-to-this-branch-are-not-permitted-y/1164589

**Comment by mikefactorial** [comment]
Closing this issue for now. @AkashPatel136 please feel free to reopen / submit another issue if need be.
