### ISSUE TITLE
[CoE Starter Kit - BUG] Error trying to setup audit log

### ISSUE THREAD

**Issue by michastauffer** [microsoft/coe-starter-kit#1939]
### Describe the issue

when trying to setup the audit log solution. i get the following error after selecting a user, when creating a connection:
![image](https://user-images.githubusercontent.com/91253916/152527658-ff955e09-f420-4720-81e2-7123b28bde33.png)

### Expected Behavior

create connection successfully

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

admin - sync audit logs

**Comment by manuelap-msft** [comment]
This looks like a product issue, unrelated to the CoE Starter Kit. The screen you are seeing the error with is the usual Microsoft login-screen driven by Azure Active Directory.

If you are still seeing an issue, please raise a support ticket with MS support https://docs.microsoft.com/en-us/power-platform/admin/get-help-support
