### ISSUE TITLE
[ALM Accelerator - BUG]: Save Solution button is not appearing

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#1945]
### Describe the issue

Hello,

After succesful deployment of ALM Accelerator, I have created maker experience as follows:
![image](https://user-images.githubusercontent.com/98403757/152552976-d4cd3297-18d4-4161-8216-468a8d8304f7.png)

After that, when I open the ALM Accelerator canvas app, it always shows "Commit Solution" and "Deploy Solution" option - why not "Save Solution" option?

![image](https://user-images.githubusercontent.com/98403757/152553427-7454a458-cafc-4744-a044-bcccef7c4b3d.png)

Can you please share - what have I missed here?

Thanks,

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

latest

**Comment by mikefactorial** [comment]
@tomsinsight you can change the names using the User Labels configuration on the User Settings

![image](https://user-images.githubusercontent.com/42348035/152576839-6a56a04c-1d60-4562-b635-739c95d61b02.png)
