### ISSUE TITLE
[CoE Starter Kit - Feature]: License consumption and app usage for model-driven apps

### ISSUE THREAD

**Issue by StevieBleeds** [microsoft/coe-starter-kit#1947]
### Is your feature request related to a problem? Please describe.

One of the challenges we're finding is managing the per app / user license consumption for model-driven apps. Ideally, we would be able to see which user has a per user / app license and if they are using it as part of that app. We also cannot view model-driven app usage either

### Describe the solution you'd like

A tab in the Centre of Excellence that supports model-driven license consumption and app usage, much like we can see with canvas apps.

### Describe alternatives you've considered

Alternatives we are currently looking at integrating with application insights for canvas information and hoping data lake integration can help with the model-driven apps by providing usage information.

We are looking to test the application insights integration with a canvas app with the hope that helps us to retrieve who has accessed that app and correlate that data with our group of users who are licensed for Power Apps to see who has logged in the last 30 days and who has not.

We are hoping to do something similar with the data lake integration, but as of writing, we are still waiting for the account to be populated with usage data.

**Comment by manuelap-msft** [comment]
The CoE Starter Kit is built on top of the Power Platform, and as such we can only surface information the platform provides us - there are currently no APIs or data stores that provide license information  or model driven app usage. As these are product gaps, I would recommend you raise them in the Power Users Ideas forum https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas to ensure they get the right level of visibilty by our Product Group.

**Comment by albertocaa1317** [comment]
Hi @StevieBleeds,
if you add this Idea in the forum paste me the url. You have my vote. I am in the same situation.

**Comment by StevieBleeds** [comment]
@albertocaa1317 Sure thing, here is the link - https://powerusers.microsoft.com/t5/Power-Apps-Ideas/View-license-consumption-and-app-usage-for-model-driven-apps/idi-p/1449045#M35364

**Comment by albertocaa1317** [comment]
Voted!
