### ISSUE TITLE
[ALM Accelerator - Feature]: Make Configuration Migration configurable

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#1960]
### Is your feature request related to a problem? Please describe.

Currently, our approach to importing configuration migration data is based on convention.  

### Describe the solution you'd like

We should consider changing this to be configurable via customDeploymentSettings.json.

**Comment by mikefactorial** [comment]
Need to prioritize this for May due to side effects with deployment configuration in the April release.

**Comment by gerald560** [comment]
This is causing issues for us as deployment setting configs are not being populated.

**Comment by ksethunath1** [comment]
Our configuration files are stored in Production folder and environment name variable is set to Production. We had to comment out workaround for renaming environment name variable to make script to owner configuration.

![Screenshot 2023-02-03 135842](https://user-images.githubusercontent.com/83974981/216709502-5742df15-ae88-41a4-8cef-0fd60b126e3d.png)

**Comment by Griffin641498** [comment]
> Our configuration files are stored in Production folder and environment name variable is set to Production. We had to comment out workaround for renaming environment name variable to make script to owner configuration.
> 
> ![Screenshot 2023-02-03 135842](https://user-images.githubusercontent.com/83974981/216709502-5742df15-ae88-41a4-8cef-0fd60b126e3d.png)
> 
>
