### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to reassign owners for orphaned flows with Admin | Archive and Clean Up v2 flow

### ISSUE THREAD

**Issue by BhargavPrasadGorakanti** [microsoft/coe-starter-kit#1966]
Hi, I want to report a bug / unexpected behavior in this power automate flow from "Center of Excellence - Governance Components" solution (version # - 2.10 - "Admin | Archive and Clean Up v2 (Start Approval for Flows)". The flow is unable to re-assign owners for flows that are orphaned.

Pic 2 shows that the flow entered the "No" branch but input parameter value was empty. However as per conditions set in Pic 1, the flow shouldn't have entered "No" branch if FlowOwnerID variable was empty. Should the null check in condition be replaced with an empty(variables('FlowOwnerID')) boolean check instead? This will cause an unmanaged layer in dev environment unless we extend this through a Managed solution. Can you please let me know if my understanding of this behavior is correct and if yes, are there any plans to change these conditions as part of a future release to the toolkit? 

Thank you.

![Picture1](https://user-images.githubusercontent.com/43746286/152790960-e6adef6b-98f0-4b5d-b625-40021523c74b.PNG)
![Picture2](https://user-images.githubusercontent.com/43746286/152790992-750709d7-39f3-4f20-aaca-20712ece8858.PNG)

**Comment by manuelap-msft** [comment]
Hello,

this is a caught and handled error. If you hover over the (i) icon you can see that the failure of the Recheck Orphan Status query is caught and the flow proceeds to the Switch statement. It looks like there's an error happening in the Switch statement, you will have to expand that statement to see what error is happening and share that back with us here for further analysis.

Thank you
Manuela

**Comment by BhargavPrasadGorakanti** [comment]
Hi Manuela,

Thank you for looking into this. This error is handled like you've explained. The flow moves on to the Switch action ('Configure run after' is set to both success and failure of previous step). The switch statement throws an error as there's no output from the previous step. Please let me know if I can provide any other details. 

Just to quickly clarify, it seems like the flow is designed to handle empty values in FlowOwnerID variable through the "Yes" branch by assigning Admin as new flow owner. But the flow is entering "No" branch as this condition - "FlowOwnerID is equal to Null" returns false despite the FlowOwnerID variable being empty. 

Thank you
Bhargav

![Picture3](https://user-images.githubusercontent.com/43746286/152962792-b9896f5a-666f-42cc-ae98-6d1a7bae865a.PNG)

**Comment by Jenefer-Monroe** [comment]
Thanks for the detailed investigation. Very useful! 
I know this used to work, so I dont know what happened, but it will require some testing to get to the bottom of it.

**Comment by Jenefer-Monroe** [comment]
Validated this is still working for apps

![image](https://user-images.githubusercontent.com/89584709/153298107-cfa1e000-60db-45b7-a1cd-e619ead454ae.png)

**Comment by Jenefer-Monroe** [comment]
now checking the length of the string variable
![image](https://user-images.githubusercontent.com/89584709/153299842-398b01ab-1dd0-4568-8edc-58fb9628aa34.png)

local fixed march

**Comment by BhargavPrasadGorakanti** [comment]
Thanks again for looking into this! We'll manage this with a fix in an unmanaged layer until the next upgrade in March. @Jenefer-Monroe
