### ISSUE TITLE
[CoE Starter Kit - BUG] Changing environment variable values in the Admin - Command Center

### ISSUE THREAD

**Issue by keharrin** [microsoft/coe-starter-kit#1969]
### Describe the issue

We are receiving the message that the COE Audit Logs require smaller chunks.

I did read the information on issue #1754 regarding changing the environment variables.

I attempted to use the Admin- Command Center app to update the default values.

However when I check the environment settings from within the Center of Excellence Audit logs solution, the defaults are not changed.

### Expected Behavior

When I click Save the Current Value listed in the app as pictured below should update wat is shown in the solution environment variables.
![image](https://user-images.githubusercontent.com/77410660/152844899-7ea21ea0-6278-46a1-9ce9-707005af575f.png)

![image](https://user-images.githubusercontent.com/77410660/152845070-f27cc15a-07f6-4474-912b-05ccde08f83c.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by manuelap-msft** [comment]
You can not change the Default Value of the Environment Variable as that is shipped with our managed solution, you can only change the Current Value.

The way environment variables work if used in an app or flow is
- look at current value
- if current value is not there, use default value

So setting a Current Value will "overrule" the Default Value we provide.

**Comment by keharrin** [comment]
Yes.  I thought that is the intent of the Power App Admin-Command Center.  However, it is not saving the current value.  Therefore we continue to get the email messages that the COE Audit Logs require smaller chunks.

What are specific steps to change the default values so that this message is addressed.

**Comment by manuelap-msft** [comment]
1. The Default value can not be changed. Only the Current Value can be changed. Check here how to update the environment variable outside the Command Center app if this isn't working for you: https://docs.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables
2. You need turn flows using this enviornment variable (in this case the Audit Log flows) off and back on to fetch the latest value as flows currently cache these.
3. It's possible you need to change the interval multiple times to find the optimal setting for you, we provide some sample configs here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow
4. If your tenant is very large, you may find that it's not possible to get all audit log events via the flow and you may find setting up [self-serve analytics](https://docs.microsoft.com/en-us/power-platform/admin/self-service-analytics) is a better way forward for you

**Comment by keharrin** [comment]
Thank you step 1 allowed me to change the defaults and resolve the issue.  Thanks!

**Comment by manuelap-msft** [comment]
Awesome, thank you for confirming!
