### ISSUE TITLE
[CoE Starter Kit - BUG] Maker - Command Center - no content in Apps

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [microsoft/coe-starter-kit#1972]
### Describe the issue

I've recently completed an install of the core components and I noticed that there isn't anything on the Apps screen of the Maker Command Center.  I have owner rights to the environment and solution, should I be seeing something there?  I was hoping to share this with the makers in our environment.  There's no documentation covering the app, so not sure what I should expect to see there.

### Expected Behavior

Should there be something in the App section of the Maker Command Center?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Maker - Command Center

### Steps To Reproduce

1. Open Maker Command Center
2. Refresh or click on the Apps tab on the left
3. Nothing is displayed.

**Comment by Jenefer-Monroe** [comment]
Bookmarks for both Admin and Maker are configured in the Admin Command Center. 
Browse to the Admin Command Center > Edit Bookmarks
![image](https://user-images.githubusercontent.com/89584709/152876130-027aae24-01e9-48d3-ab37-56ed32e3533b.png)

For each bookmark you will see the ability to display the item in the Maker and/or Admin Command Center
![image](https://user-images.githubusercontent.com/89584709/152876202-2f74ce27-8268-4049-bf39-6e85a0c9dbf5.png)

**Comment by DaveTheTeamsGuy** [comment]
Thanks, that makes sense!  Closing . . .
