### ISSUE TITLE
TEAMS COE did not install Custom Connector

### ISSUE THREAD

**Issue by AntonRobbins** [microsoft/coe-starter-kit#1973]
### Describe the issue

Looking to update the custom connector for Audit Log. I do not see the custom connector in powerapps. 

### Expected Behavior

Should see custom connector and be able to up date.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

January 2022

### What app or flow are you having the issue with?

Audit Log

### Steps To Reproduce

1. Open Powerapp > data > custom connectors

**Comment by Jenefer-Monroe** [comment]
Hello, Dataverse for Teams does not support custom connectors. As a result, our Teams CoE does not support the audit logs. 

Please see [Production or D4T Environment](https://docs.microsoft.com/power-platform/guidance/coe/setup#decide-what-environment-type-to-use-production-or-dataverse-for-teams)
![image](https://user-images.githubusercontent.com/89584709/152869175-38eb893b-7fca-4bff-bba9-563856fd9380.png)

**Comment by AntonRobbins** [comment]
DUH me.
Thank you.

**Comment by Jenefer-Monroe** [comment]
My pleasure, closing out.
