### ISSUE TITLE
[CoE Starter Kit - BUG] Tenants with Teams not enabled will not be able to use the CoE Kit. 

### ISSUE THREAD

**Issue by Rene-** [microsoft/coe-starter-kit#1975]
### Describe the issue

When defining the environment variables at the beginning of the import you are required to use a Teams connection. For Tenants that are not utilizing Teams they won't not be able to use the kit as this environment variable is a "requirement" for the kit to be fully imported. 

### Expected Behavior

Importing the kit with no issues

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

 Admin | Compliance Detail Request v3

**Comment by Jenefer-Monroe** [comment]
I'm not sure what you mean by not utilizing teams.  Are you saying the connector is blocked? 
This is a requirement as the sync flows require it in order to monitor Dataverse for Teams environments.

**Comment by Rene-** [comment]
apologies I need to add more context. 

I am using the non dataverse packaged solution. I am testing this solution in a tenant where teams licenses are not enabled. Is there a workaround for required environment variables? Specifically the Teams connection?

**Comment by manuelap-msft** [comment]
You will need to switch to classic import mode to import the solution, this will bypass setting the connection references during import. You'll then have to update all connection references to add a connection for the flows to run.

It is a required connection for certain governance flows that send adaptive cards to teams, so you will have to check those flows and add alternatives (e.g. email) if you want to use those.

**Comment by Rene-** [comment]
Hi Manuela, thank you for the useful insight. I just have one more question... Is there a way to extract only the dataverse tables from the packaged solution?

**Comment by manuelap-msft** [comment]
Not one that I'm aware of, I don't think - after you install the kit, you can create your own unmanaged solution and add components you require to that solution but that's the only thing that comes to mind here.
