### ISSUE TITLE
Power Platform COE Starter Kit Not showing all apps, but workflows not failing

### ISSUE THREAD

**Issue by amondelloSP** [microsoft/coe-starter-kit#1986]
I have a client with thousands of Apps. They all show in their previous version of the COE (from a year ago) but when I installed the new COE starter kit last month, we're only picking up a little over 100 apps. I checked the inventory workflows, and they are not failing. Does anyone have any ideas or experience with this? (and yes, we have both installed in different environments)

**Comment by manuelap-msft** [comment]
You are likely experiencing this bug #1810 which was introduced with the January release and fixed with the February release. I would recommend you upgrade.

**Comment by Jenefer-Monroe** [comment]
And you will also need to do a [fullinventory run](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory), whether you upgrade or not.

**Comment by DaveTheTeamsGuy** [comment]
Is a full inventory required after every upgrade for fixes to take effect, or do subsequent scheduled flow runs handle this?  If a full inventory is required, it may be worthwhile to add this to the upgrade instructions.  https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup#installing-upgrades

**Comment by Jenefer-Monroe** [comment]
No, its only required in special cases. For example if we added a new field to the object table that you wanted populated.
In this case its needed because we shipped an optimization that missed the "new install" case.

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for starter kit team. 
Thanks for using CoE
