### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View Missing Admin View for Apps

### ISSUE THREAD

**Issue by andrewgaskins** [microsoft/coe-starter-kit#1988]
### Describe the issue

The new Power Platform Admin View no longer has the Admin view. I see the new Compliance groups however the submitted items are not leaving the Requested area. 

### Expected Behavior

User submits justification with everything accounted for in the Developer Compliance Center app. All apps are on to look at updates and nothing moves to Submitted. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Center of Excellence - Core Components 3.31 Center of Excellence - Governance Components 2.10

### What app or flow are you having the issue with?

Admin | Compliance detail request v3

### Steps To Reproduce

1. Enable all flows in proper order
2. Users start receiving emails
3. User responds with all information
4. Information shows up in the requested view
5. No admin view available and the Submitted view is not showing updates

**Comment by Jenefer-Monroe** [comment]
Can you please share a picture of where you are used to seeing some UX you now do not see?

**Comment by Jenefer-Monroe** [comment]
I still don't really understand what you are seeing, but I did wonder if you have the flows running. 

Can you please go to the **_Admin - Command Center_** app > Cloud Flows > Compliance. 
Are they all on? 
![image](https://user-images.githubusercontent.com/89584709/153421128-f1afc2fb-d769-45a9-99a9-3c75b1a4888f.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for starter kit team. 
Thanks for using CoE
