### ISSUE TITLE
[CoE Starter Kit - BUG] Command Center initially populating bookmarks every time it is opened

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [microsoft/coe-starter-kit#1990]
### Describe the issue

Just updated to Core 3.31, the Command Center Canvas App keeps re-adding bookmarks each time it is opened.  I've opened it six times and there are now six sets of icons.

### Expected Behavior

Initial bookmark population should only occur once.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

1. Installed 3.31 upgrade
2. Opened Admin - Command Center multiple times
3. Each time command center opens, it initially populates bookmarks.

![image](https://user-images.githubusercontent.com/99212416/153065481-b30adb00-7cd0-44c7-8d14-3cc01b656107.png)

**Comment by Jenefer-Monroe** [comment]
Hello, we updated the flow to re-populate on start every time, this way you would get (for example) the apps from the Governance solution if you installed it after using this app. 
So thats intentional
Do you have an unmanaged layer on this flow? **_Initially Populate Bookmarks_**
It was updated to only insert the app if it was not already present.

**Comment by Jenefer-Monroe** [comment]
actually it looks like we intended that to only happen when you are in Edit Bookmarks. 
But regardless the flow catches the case. So you'll need to see if you have an unmanaged layer there preventing you from seeing that update.

**Comment by DaveTheTeamsGuy** [comment]
There was an unmanaged layer on that flow, but I'm not sure how it got there since I haven't done any work to extend the CoE here.  I removed the unmanaged layer, do I need to do a re-import, or should it now catch the update?

**Comment by Jenefer-Monroe** [comment]
Removing the unmanaged layer should fix it, meaning that you should no longer see new apps added each time you boot the app, though it will still look for new ones.
 
However you will need to delete the duplicates manually. You can do that by going to the table itself as shown here:
![image](https://user-images.githubusercontent.com/89584709/153076398-668c384f-9485-4ea9-ae26-e29a48ee4f58.png)

**Comment by Jenefer-Monroe** [comment]
Glad you got unblocked, and thanks for using CoE! Closing out.
