### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Center to use Helper flows for delete etc

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#1994]
### Describe the issue

Since we cant delete apps/flows that are part of a solution, and since people dont see or read the error when it comes back on its own, lets catch it and tell them like we do when they try to browse to settings for teams objects

Developer Compliance
Set App Permissions
Set Flow Permissions

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Set Flow Permissions

### Anything else?

Also teams version of the app
See #1383

**Comment by Jenefer-Monroe** [comment]
Did quick prep work to make the error bar flexible to support other error types. 
and added teams block for assigning new owners, also not supported for Teams envts

**Comment by Jenefer-Monroe** [comment]
I cant find a way to see that an app is part of a solution. I thought I had seen this but now I dont know where that was. 
If anyone has ideas, let me know.

**Comment by Jenefer-Monroe** [comment]
with the switch to using the helper flows from these apps, we will be able to delete these after all. 
work will instead be to switch Compliance Center app to use the helper flows.

**Comment by Jenefer-Monroe** [comment]
updating title and moving out of April

**Comment by sandeep-mamidala** [comment]
Hi Team,

Could you please let us know when can we expect fix for the above issue. As we see that issue is still not fixed in June release

**Comment by Jenefer-Monroe** [comment]
I'm afraid I cannot provide a fix date. We are awaiting the release of the app replatted onto the Creator Kit ([https://aka.ms/creatorkit](https://aka.ms/creatorkit)), and then we can take this work on.

**Comment by sandeep-mamidala** [comment]
Hi Team,
Do you have any update on this issue?

**Comment by Jenefer-Monroe** [comment]
We cannot provide an estimate at this time

**Comment by manuelap-msft** [comment]
Planning to update the Developer Compliance Center in the January release now.

**Comment by manuelap-msft** [comment]
Developer Compliance Center UX refresh will go live in February, and then we'll fast follow on this issue in March. Moved to March milestone.

**Comment by jjones419** [comment]
Upvoting this fix as it relates to issue #6934 as we are also experiencing the same issue.

**Comment by manuelap-msft** [comment]
Closing out as a new version of the Dev Compliance Center was released a few months ago.
