### ISSUE TITLE
[CoE Starter Kit - BUG] Cant connect to company URL

### ISSUE THREAD

**Issue by DanCrawf** [microsoft/coe-starter-kit#1999]
### Describe the issue

Cant connect when I put in Company URL

### Expected Behavior

Expected to connect

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

power BI

### What app or flow are you having the issue with?

Production_CoEDashboard_Jan2022.pbit

### Steps To Reproduce

[COE Dashboard failure.docx](https://github.com/microsoft/coe-starter-kit/files/8028855/COE.Dashboard.failure.docx)

I'm not certain what the company URL is .... I've tried the likely ones. I'm logged into the workstation and Power BI Desktop as an m365 Global Admin.
I havent done any other config or setup... just running the Power BI Template

**Comment by Jenefer-Monroe** [comment]
Have you looked through this documentation? 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard

**Comment by DanCrawf** [comment]
Jenefer,
Thanks for getting back to me. Thanks for that doco…. At least I know I’m entering https:// at the start of the org URL for the production COE.
I’m still not sure what the company URL is
I’m assuming https://sydneywater.onmicrosft.com but tried https://sydneywater.sharepoint.com as well

The attached screenshots show what I see when trying to sign in.
If I hit connect I can see “error coe second error after connect”


The details are:


OrgUrl
Loading blocked by failures with other queries.
Environment
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
App
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Flow
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Maker
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Connector
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
App Connection Reference
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Flow Connection Reference
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Audit Log
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Flow Action Details
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
NonProdWords
Loading blocked by failures with other queries.
Virtual Agent
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Virtual Agent Component
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Virtual Agent Flows
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
RPA
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
RPA Sessions
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Power Platform User
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Portals
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)
Environment Capacity
Credentials are required to connect to the Cds source. You'll need to refresh and provide credentials to continue. (Source at https://sydneywatercorporation.onmicrosoft.com/.)






From: Jenefer Monroe ***@***.***>
Sent: Wednesday, 9 February 2022 1:39 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: CRAWFORD, DANIEL ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Cant connect to company URL (Issue #1999)


CAUTION: This email originated from outside the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.

Have you looked through this documentation?
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpower-platform%2Fguidance%2Fcoe%2Fsetup-powerbi%23configure-the-power-bi-dashboard&data=04%7C01%7Cdaniel.crawford%40sydneywater.com.au%7Cd289150fd6dd4176acaf08d9eb75574b%7C8351bb5c749d4ee4b1c471a3971acbe9%7C0%7C0%7C637799711500922872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=H1oW%2FL3lG3NTGsmPF5ktsqiGqUhXkjeMZCw89adkmRg%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F1999%23issuecomment-1033284623&data=04%7C01%7Cdaniel.crawford%40sydneywater.com.au%7Cd289150fd6dd4176acaf08d9eb75574b%7C8351bb5c749d4ee4b1c471a3971acbe9%7C0%7C0%7C637799711500922872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1TmNz8RIzo2oRaMNngyvKLXs4a3ZTn1n9DKz1YrYSts%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXVUCXEST5TK2EAI7XPG2FTU2HHUNANCNFSM5N4FLGJQ&data=04%7C01%7Cdaniel.crawford%40sydneywater.com.au%7Cd289150fd6dd4176acaf08d9eb75574b%7C8351bb5c749d4ee4b1c471a3971acbe9%7C0%7C0%7C637799711500922872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=89Bh0HynJW%2F5PEsjEGrTE8juvvkt92ZawCsfaUwMPVQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdaniel.crawford%40sydneywater.com.au%7Cd289150fd6dd4176acaf08d9eb75574b%7C8351bb5c749d4ee4b1c471a3971acbe9%7C0%7C0%7C637799711500922872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z16ATYbMZw5OTKCmc2uVzQqM8jZjPNxg2A78BcKgwDY%3D&reserved=0> or Android<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdaniel.crawford%40sydneywater.com.au%7Cd289150fd6dd4176acaf08d9eb75574b%7C8351bb5c749d4ee4b1c471a3971acbe9%7C0%7C0%7C637799711501079100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sFtFRtIjBE35BdBR3sesDnSeq0iYJBsydiJ025Cxx0A%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________

[Facebook]<http://www.facebook.com/SydneyWater>  [Twitter] <http://twitter.com/sydneywaternews>   [YouTube] <http://www.youtube.com/user/sydneywatertv>   [Instagram] <http://www.instagram.com/explore/tags/sydneywater/>

________________________________

NOTICE: This email is confidential. If you are not the nominated recipient, please immediately delete this email, destroy all copies and inform the sender. Sydney Water Corporation (Sydney Water) prohibits the unauthorised copying or distribution of this email. This email does not necessarily express the views of Sydney Water. Sydney Water does not warrant nor guarantee that this email communication is free from errors, virus, interception or interference.

________________________________

**Comment by manuelap-msft** [comment]
It looks like you're using the wrong URL. It should contain something like crm.dynamics.com

Here's how to get the URL https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#get-the-environment-url

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for starter kit team. 
Thanks for using CoE

**Comment by DanCrawf** [comment]
Thanks…. I’ve been busy and didn’t have a chance to follow-up.
I’ll investigate again soon.
Thanks
For your help
Dan

From: Jenefer Monroe ***@***.***>
Sent: Friday, 18 February 2022 12:57 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: CRAWFORD, DANIEL ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Cant connect to company URL (Issue #1999)


CAUTION: This email originated from outside the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.

closing out as no further work for starter kit team.
Thanks for using CoE

—
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F1999%23issuecomment-1042976002&data=04%7C01%7Cdaniel.crawford%40sydneywater.com.au%7C6363c3a179c34543fb4c08d9f21d6c97%7C8351bb5c749d4ee4b1c471a3971acbe9%7C0%7C0%7C637807030505263920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3IqVHaP4tNT8YhBykpuBsyOZNjWIhslXs%2F6w8Wn9maw%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXVUCXHGOBQYKMWL3DDCVKTU3T5EDANCNFSM5N4FLGJQ&data=04%7C01%7Cdaniel.crawford%40sydneywater.com.au%7C6363c3a179c34543fb4c08d9f21d6c97%7C8351bb5c749d4ee4b1c471a3971acbe9%7C0%7C0%7C637807030505263920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jLunWmzcJcQddpd%2Bqhr%2BMLtKNxUY8jiZvt4LKQ58zJM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdaniel.crawford%40sydneywater.com.au%7C6363c3a179c34543fb4c08d9f21d6c97%7C8351bb5c749d4ee4b1c471a3971acbe9%7C0%7C0%7C637807030505263920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ANVF4sTit7cWeug8unWZWyFSW%2F7OgblIWC0JuWVQT8A%3D&reserved=0> or Android<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdaniel.crawford%40sydneywater.com.au%7C6363c3a179c34543fb4c08d9f21d6c97%7C8351bb5c749d4ee4b1c471a3971acbe9%7C0%7C0%7C637807030505263920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JiGNq4KKZUepdJlWYkjk8XTUPgYtNpUUtTLQL1%2FVYWI%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________

[Facebook]<http://www.facebook.com/SydneyWater>  [Twitter] <http://twitter.com/sydneywaternews>   [YouTube] <http://www.youtube.com/user/sydneywatertv>   [Instagram] <http://www.instagram.com/explore/tags/sydneywater/>

________________________________

NOTICE: This email is confidential. If you are not the nominated recipient, please immediately delete this email, destroy all copies and inform the sender. Sydney Water Corporation (Sydney Water) prohibits the unauthorised copying or distribution of this email. This email does not necessarily express the views of Sydney Water. Sydney Water does not warrant nor guarantee that this email communication is free from errors, virus, interception or interference.

________________________________
