### ISSUE TITLE
[CoE Starter Kit - BUG] Question: Is it a bad idea to delete the CoE and start again from scratch? 

### ISSUE THREAD

**Issue by Dave-Weldon** [microsoft/coe-starter-kit#2002]
### Describe the issue

Thanks for the latest office hours session, unfortunately my question was one of the ones that we ran out of time for :)

Is it a bad idea to delete the CoE and start again from scratch?  I've had issues upgrading for the last two months and now had 2 core components, one of which still has the v2 flows as well as the v3 but I'm unable to delete the old one as it has dependencies.

I'm thinking a fresh start would probably be better but also don't want to loose the audit logs if this was the way to go.

I can't find anything in your documentation and was wondering if you had information on this?

### Expected Behavior

Only have a single core components solution.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

All

**Comment by Dave-Weldon** [comment]
That's great thanks Manuela,

So it's OK to have 2 CoE's side by side while we get the the new one up and running then we just delete the old environment?

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for starter kit team. 
Thanks for using CoE
