### ISSUE TITLE
[ALM Accelerator - BUG]: Upgrade Issues - Not All Environment Names Showing

### ISSUE THREAD

**Issue by TBag** [microsoft/coe-starter-kit#2005]
### Describe the issue

Some environment names are not displayed in the Canvas app.  I've included a list of the environments in the screenshot below for reference.  Perhaps the Type of environment is the issue?

![image](https://user-images.githubusercontent.com/1407310/153256645-d16435a2-5db1-47eb-b18f-a3903fc34497.png)

### Expected Behavior

Expect to see all environment names in the Canvas app.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220131.1

### Steps To Reproduce

Open environment dropdown list.
Observe the name is missing.

**Comment by mikefactorial** [comment]
Thanks for reporting this and for the screenshots. Will look into why this is occurring

**Comment by TBag** [comment]
You're welcome.  If you would like to debug it in my environment with me just let me know.

**Comment by mikefactorial** [comment]
@TBag been looking into this. We have a few environments that are showing up with blank names as well. It may be a permissions issue in the environment for the user running the AA4PP app. It's possible we should be filtering out these environments, but need to do a little more investigation. If you have any thoughts on this based on what you're seeing would be good to get your input.

**Comment by mikefactorial** [comment]
Ultimately, what we're seeing is when we retrieve the environments using the PowerAppsforMakers connector the properties.linkedEnvironmentMetadata is null which is where we get the name of the environment from.

**Comment by TBag** [comment]
Hi @mikefactorial,

Thanks for the updates.  To follow up on your question about permissions, all the environments were created by the user who I was running the Power App with and the user has admin permissions in all of the environments.

Any ETA when the PowerAppsforMakers connector will be fixed?

**Comment by TBag** [comment]
Hey Mike,

Just confirmed the environment with the missing name does NOT have a database in it.  Like you said, if they could be filtered out from the list in the Canvas app, that would be a good solution.

**Comment by mikefactorial** [comment]
Awesome. Thanks so much for confirming Todd! Have a PR to filter these out ready for April release.

**Comment by TBag** [comment]
Nice, you're welcome.  Thanks for looking into all the feedback!
