### ISSUE TITLE
[CoE Starter Kit - BUG] Upgraded CoE Starter Kit to Feb'22 version. No Canvas Apps in Developer Compliance Center (Teams version) App and Traffic Light Indicator Not Working

### ISSUE THREAD

**Issue by ashmsport** [microsoft/coe-starter-kit#2008]
### Describe the issue

I just upgraded CoE Starter kit from Oct to Feb 2022 version and since then the Developer Compliance Center (Teams version)
app is not showing any apps in Canvas Apps section. 
In Flows section traffic light indicator is also not working. Please see the screenshot attached.

### Expected Behavior

Canvas Flows should be listed when a user launches Developer compliance app is launched > Clicks Canvas Apps
Traffic light indicators should show the right color based on Flow compliance in Developer compliance app

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Developer Compliance Center (Teams version)

### Steps To Reproduce

No canvas apps: Launch Developer Compliance Center (Teams version) app in Team > Click Canvas Apps
Traffic lights not working: Launch  Developer Compliance Center (Teams version) app in Team > Click Cloud Flows
![NoCanvasApps](https://user-images.githubusercontent.com/33230123/153298841-07ff3e7a-3d4f-4930-b042-0506632a2dfe.PNG)
![Traffic Lights Indicator Not Working](https://user-images.githubusercontent.com/33230123/153298853-b8d715a1-767a-46d7-a211-816a27d5f56b.PNG)

**Comment by Jenefer-Monroe** [comment]
For your first question: 
We have introduced the ability to filter to only the apps that have been requested for compliance by admin. And that is the default view. Drop down the filter and you will see the ablity to see all.
![image](https://user-images.githubusercontent.com/89584709/153300387-1466b97b-0837-49f4-9aba-d7dbe5f86a23.png)

**Comment by ashmsport** [comment]
That worked, thanks. Still can't see the traffic light indicators.

**Comment by Jenefer-Monroe** [comment]
I dont know if the color meaning has changed, but gray means the flow has not been requiested for compliance details. Same thing, if you use the filter you can see only requested or all. My guess is that you don't have any flows that have been requested for compliance.

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for starter kit team. 
Thanks for using CoE
