### ISSUE TITLE
[CoE Starter Kit - Question]: with Power Platform Admin role, in COE we've noticed that not all apps show

### ISSUE THREAD

**Issue by mdhauck** [microsoft/coe-starter-kit#2013]
### Is your feature request related to a problem? Please describe.

Not sure if this is an issue or ignorance. Even with Power Platform Admin role, in COE we've noticed that not all apps show (if not explicitly shared).  The analogy is that in D365 CE admins don't see personal view unless shared (but I CAN in XrmToolBox).  While I understand not necessarily default to have "access" to the app (or edit).  Not knowing that an app exists can create challenges.

### Describe the solution you'd like

Would like to be able to all apps (even if not shared) to determine who owns the app and who it may be shared with in case of employee turnover, etc).

### Describe alternatives you've considered

So far we've just tried to create other views filters but really seems like there is no visibility unless shared (or we're not looking at the right security).

**Comment by mdhauck** [comment]
> What do you mean by show? Show where? Do you mean that the inventory sync flows do not see everything and hence you dont have a tenant view in your PBI?

The only good example I have is in a client's environment so I cannot add screenshots.  In the Power Platform Admin View App if I choose Power Apps Apps in sitemap and look at the "All Apps" view, I do NOT see all the apps (if I go into Power Apps Admin Center, choose a particular environment and then go to Resources and Power Apps I see more apps here than in the COE app.

**Comment by Jenefer-Monroe** [comment]
Thanks, For the PPAdmin role, can you please validate, did the entity that installed the starter kit have this role? And is the role permanent or assigned dynamically?

**Comment by mdhauck** [comment]
IF (big if) I understand correctly, the answer is yes - the ID that installed the COE has (and had at time of install) Power Platform Admin.  I'm not sure what or how it means to dynamically vs permanently assign but I BELIEVE it is permanently (explicitly?) assigned.

**Comment by Jenefer-Monroe** [comment]
I've never seen this happen, so I think there is likely a misunderstanding or misconfiguration.
Please do the following:
- log in as the entity that is charged with the CoE runs, share that identiy with us here (obfuscated slightly)
- browse to the following flow in core **_Admin | Sync Template v3_** and share here what the connections look like
![image](https://user-images.githubusercontent.com/89584709/153599464-745e47c1-e76f-4536-a385-4b28cbf639e1.png)
![image](https://user-images.githubusercontent.com/89584709/153599656-15aa08b4-786a-483a-a4b6-a97bd5372c4c.png)
- Do this same exercise for **_Admin | Sync Template v3 (Apps)_**

- with that same user, log in to portal.azure.com
- Go to that users roles and share what you see for their Power Platform admin role
![image](https://user-images.githubusercontent.com/89584709/153600011-6a667c35-be79-4177-ae09-e6b7756983aa.png)

- then go https://admin.powerplatform.microsoft.com/ as that same user and share the UX where you are seeing apps you dont see in the CoE.

**Comment by mdhauck** [comment]
First of all I apologize for the delayed response, on of my colleagues was able to duplicate this behavior in another (non client) environment.  Wondering if it would make sense (if it is possible/feasible) for us to schedule a call and show you (or someone) what we're seeing to figure out if it is just training/education or if there is an issue or ???

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot schedule meetings with our GitHub customers. The starter kit is not officially supported and we are not staffed to take such calls. Instead we will have to do the investigation here together. 
Please look at the questions posted above and bring the answers here from your non-client repro.

**Comment by amondelloSP** [comment]
WE also have this issue with a large customer with many flows and apps.

**Comment by amondelloSP** [comment]
Thank you Jenefer. The answer to both things is YES. the entity running the COE has the PPAdmin role, and we did a full inventory run.

**Comment by Jenefer-Monroe** [comment]
Did you have failures in the sync flows?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for the starter kit team
