### ISSUE TITLE
Unable to Add Questions in Maker Assessment: Admin App in Teams

### ISSUE THREAD

**Issue by ashmsport** [microsoft/coe-starter-kit#2024]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/2010

<div type='discussions-op-text'>

<sup>Originally posted by **ashmsport** February  9, 2022</sup>
I've imported the latest version 2.6 (Feb'22) of CoE starter kit and I'm unable to add any questions using Maker Assessment: Admin App. I get several errors. For Eg. 
When I try to save answer it throws error: Value must be a data entity record. 
![MakerAssessmentAdminApp](https://user-images.githubusercontent.com/33230123/153302603-0111cb88-4800-4d70-9e6a-c86272689547.png)

When I try to add a new question there is no option to add an answer
![NoAnswers](https://user-images.githubusercontent.com/33230123/153302703-9ac5ce26-688e-4b1d-aaa6-5d80df641f2e.PNG)

Is it supposed to work in Teams or is it a bug? I had the same issue in Oct'21 version as well.
</div>

**Comment by ashmsport** [comment]
No I don't see any values in the second drop down. It's empty.

**Comment by Jenefer-Monroe** [comment]
I see. That field relies on their being values in a particular field which is filled by the starter data so something must have broken when you entered the starter data. 

We have replaced the dataflow for this with a new flow **_Add Maker Assessment Starter Data_** in March via #1889 
Please watch that bug and use the flow to repopulate the starter data with the March release.

**Comment by ashmsport** [comment]
Ok thank you.

**Comment by manuelap-msft** [comment]
Closing out as no furhter action from the CoE kit team required.
