### ISSUE TITLE
[CoE Starter Kit - BUG]  CoE Audit Log require smaller chunks

### ISSUE THREAD

**Issue by gabrielvillayzanbcp** [microsoft/coe-starter-kit#2025]
### Describe the issue

I am receiving these messages everyday (initially configured to 1 hour). So I tried to edit the variable values, wich I can't (image2), then I edited the values directly in Dataverse table "Environment Variable Value", not only the new value but also the default value (15 minutes). But I am getting the same messages and the changes are not working.

![image](https://user-images.githubusercontent.com/84060860/153430331-42a672a9-5f05-440b-986f-795f253616e4.png)

![image](https://user-images.githubusercontent.com/84060860/153434666-0de03154-676d-4bee-ad91-334277c2c224.png)

![image](https://user-images.githubusercontent.com/84060860/153434478-9e0f3574-0db4-4ec0-bc4e-4ad0bbc676e0.png)

### Expected Behavior

I need this configuration to work fine with the variables specified.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Center of Excellence - Audit Logs

**Comment by gabrielvillayzanbcp** [comment]
I have restarted the flows. I will wait tomorrow morning when these flows execute to verify.

**Comment by gabrielvillayzanbcp** [comment]
The flows are working fine right now... Thanks!!! :)

**Comment by manuelap-msft** [comment]
thanks for confirming!
