### ISSUE TITLE
[CoE Starter Kit - BUG] Data mismatch

### ISSUE THREAD

**Issue by Sishira** [microsoft/coe-starter-kit#2026]
### Describe the issue

In my current setup, Environment numbers are not matching between pages. On the Environment Dashboard its showing lesser number than other pages.

### Expected Behavior

All Pages in COE Dashboard to show consistent number.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Environment

### Steps To Reproduce

1. Open Dashboard
2. Check Environment count in OverView
3. Check Environment count in Environment
![Capture2](https://user-images.githubusercontent.com/99423817/153465962-da21fa6f-3e32-408e-a429-1bc5fff95c97.PNG)
![Capture1](https://user-images.githubusercontent.com/99423817/153465970-d8871418-bf17-46ae-8f82-2749cda2adbc.PNG)

**Comment by Sishira** [comment]
![Capture4](https://user-images.githubusercontent.com/99423817/153483257-b32be7ab-ecd3-4d11-a489-4caf68b1a449.PNG)
![Capture3](https://user-images.githubusercontent.com/99423817/153483267-c26dd123-e9bb-413a-94f7-1aeafbb4d59c.PNG)

**Comment by Jenefer-Monroe** [comment]
You have a few bugs in the PBI that we don't see. For example you are showing that all the environments were created this month. We did have a bug like that but it was a very long time ago.  

I suggest starting with a new version of the PBI, one which correlates with the month you installed Core.

**Comment by Jenefer-Monroe** [comment]
I found what I believe to be the PBI version you would need: 
[CDSLegacy_CoEDashboard_202110.zip](https://github.com/microsoft/coe-starter-kit/files/8048818/CDSLegacy_CoEDashboard_202110.zip)

**Comment by Jenefer-Monroe** [comment]
closing out as no further work for starter kit team. 
Thanks for using CoE
