### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by GES10** [microsoft/coe-starter-kit#2027]
### Describe the issue

I downloaded the last version of CoE, and I can't find the Governance component to enable the Developer Compliance Center App and its flows.

![coe](https://user-images.githubusercontent.com/91596085/153467485-3dbdeb0e-7180-44d0-9b96-d6e7c8aaf340.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

last version

### What app or flow are you having the issue with?

Core

**Comment by manuelap-msft** [comment]
Please follow the steps in our documentation to import and setup the governance solution:
1. https://docs.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov#import-the-governance-components-solution
2. 
![image](https://user-images.githubusercontent.com/55705669/153467859-73e6144d-d5ce-4128-bbff-577c9546ac3e.png)
3. https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components
