### ISSUE TITLE
[CoE Starter Kit - BUG] Desktop Flow repot is empty

### ISSUE THREAD

**Issue by AdnanJusicMS** [microsoft/coe-starter-kit#2036]
### Describe the issue

Hi lovely COE Team,

I have a question again. I am facing at my dev environment, but also at some customer in there productive environment an empty CoE Dashboard report "Desktop flow". I have also checked the tables behind and it it pretty confusing that in the report it the table RPA linked (to provide data) but if i check the tables in the CoE core component solution, there is not RAP table. I have also checked the table Desktop flow and in this table i can see my desktop flows, but this table isnt linked to the desktop flow report in the BI dashboard. Am I doing something wrong or the installed version of the CoE have a bug?

At this screenshot you will see that the Desktop flow report havn't the desktop flow table connected, as a data source/set.

![image](https://user-images.githubusercontent.com/96141055/153633106-1b28fb4b-6335-4b7c-ab92-87a02b48dfad.png)

I have one desktop flow in my environment, which i also recorded in the Desktop flow table.

![image](https://user-images.githubusercontent.com/96141055/153633334-70a56c3b-ea8a-4b37-9ae5-c70043cfc6c3.png)

![image](https://user-images.githubusercontent.com/96141055/153633434-4846d537-d158-421e-b692-f3424079fd95.png)

The RPA table is empty.

![image](https://user-images.githubusercontent.com/96141055/153633471-b51019f2-23de-43ca-b4d4-cef61da33d11.png)

Thanks a lot in advance!

### Expected Behavior

The desktop flow report shouldn't be empty, because I have one desktop flow in my environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

CoE BI Dashboard

### Steps To Reproduce

1. Open the CoE BI Dashboard
2. Browse the Desktop flow report.

**Comment by Jenefer-Monroe** [comment]
Hello.

Regarding the PBI page not showing the desktop flow, it looks like it was added to inventory on the 11th, was the PBI data updated after it was inventoried? 

For the RPA Sessions, have you run this desktop flow? And do you have this inventory flow running and passing? **_Admin | Sync Template v3 (Desktop Flow - Runs)_**

**Comment by AdnanJusicMS** [comment]
Hi Jenefer,

i apologize for reopening this case here. I have talked to the customer and he has all collecting workflows running successfully, but the desktop flow table are still empty. Do you have any suggestions regarding the troubleshooting, maybe the flow only collects active desktop flows?

Thanks a lot in advance!

Kind regards,

Adnan
