### ISSUE TITLE
[CoE Starter Kit - BUG] D4T - Import failed due to missing dependencies, CenterofExcellenceAuditLogs_2.6_managed.zip

### ISSUE THREAD

**Issue by psolano** [microsoft/coe-starter-kit#2039]
### Describe the issue

Using Feb 2022 release of the CoE Starter kit. Not able to import Governance component into Teams for Dataverse. I get the following error: Import failed due to missing dependencies for CenterofExcellenceAuditLogs_2.6_managed.zip

Looking at the documentation its supposed that Custom Connector  for Office 365 Management API gets created while installing the Core Compoments, maybe the Teams version is not doing it.
So I went there and  exported the Connector from another environment and then I imported in my D4T environment:

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/4042204/153677052-0ab4405d-07fc-412a-996e-da5cbd05edc0.png">

Then I follow the steps and I got a 200 status code.
Next steps is importing CenterofExcellenceAuditLogs_2.6_managed.zip which is giving this error:

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/4042204/153677434-db82a1b5-11fd-4d9a-bbf0-48306e90ef1e.png">

### Expected Behavior

Office 365 Management API custom connector should be created by importing CenterofExcellenceCoreComponentsTeams_3_12_managed.zip solution

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Audit Logs

**Comment by manuelap-msft** [comment]
Hello,

can you confirm you are trying to import the Audit Log solution into Dataverse for Teams? Becaues that solution is not supported in Dataverse for Teams, and custom connectors are also not supported in Dataverse for Teams.

See:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#decide-what-environment-type-to-use-production-or-dataverse-for-teams


Thank you
Manuela

**Comment by manuelap-msft** [comment]
If you are looking for the Governance components solution (and not the Audit Log solution), the solution name is different to the one you shared - it's the AuditComponents one you're looking for then:
![image](https://user-images.githubusercontent.com/55705669/153864873-e37a5727-d39d-4bc3-8648-abba5d2b8b36.png)

**Comment by psolano** [comment]
> Hello,
> 
> can you confirm you are trying to import the Audit Log solution into Dataverse for Teams? Becaues that solution is not supported in Dataverse for Teams, and custom connectors are also not supported in Dataverse for Teams.
> 
> See: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#decide-what-environment-type-to-use-production-or-dataverse-for-teams
> 
> Thank you Manuela

Hi Manuela,

Yes, I'm trying to import the Audit Log Solution into Dataverse for Teams; apologies If I wasn't clear in my description.

I guess you are referring to this:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/4042204/153875316-b390a5e1-9688-4dce-a7d6-1b1de35a3c8e.png">

I can't believe I missed this, now that I went back after trying to troubleshoot it for few hours and watching videos I  even see this is at the top of the step:

<img width="986" alt="image" src="https://user-images.githubusercontent.com/4042204/153877809-095be1e3-48f0-433b-a02d-7b8b6437ddee.png">

Thanks Manuela

**Comment by manuelap-msft** [comment]
Sorry about the confusion and extra work caused! The setup instruction video we have was recorded before we made the CoE kit available in Dataverse for Teams. We're working hard on getting updated videos recorded! Thank you!

I'll close this issue now but please let us know if you require further assistance!
