### ISSUE TITLE
[CoE Starter Kit - BUG] UI Flows do not log in COE Starter Kit when run in Edit mode

### ISSUE THREAD

**Issue by crendelacren** [microsoft/coe-starter-kit#2057]
### Describe the issue

COE Starter Kit only logs Power Automate Desktop UI Flows when they are run in the "My Flows" section of PAD (using the run button in the control room).  Those flows do not register in COE Starter Kit when a user presses the Run button while in edit mode in PAD.  This is a problem because I have found most users become accustomed to running their UI flows from Edit mode and don't even realize they can be run out of the initials Control Room/My Flows screen.  As a result, many users are running flows in the equivalent of production but we have no visibility from the COE Starter Kit.  

If not addressed, this will be a major challenge for the COE to overcome because we will lose visibility to any runs not triggered from the control room (which is the majority of runs triggered in PAD, as far as I can tell).

### Expected Behavior

I would like to see the Desktop Flows section of the COE Toolkit have a delineation of PAD runs triggered from the Edit mode as well as Control Room.  Somehow users should be pointed to running their production ready flows from the Control Room, rather than the edit screen.  

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70 I think

### What app or flow are you having the issue with?

All flows

### Steps To Reproduce

Run a flow from Edit window and see that it doesn't log in the COE Toolkit under "Monitor: Deep Dive - Desktop Flows"

### Anything else?

None

**Comment by manuelap-msft** [comment]
This is unfortunately a known limitation since PAD internal runs are meant for debugging purposes only and are not available for the CoE kit to retrieve for the inventory. There is currently no way around it other than educating users not to use this approach for their real automation runs
