### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to turn on HELPER flows after import of core components  3.31

### ISSUE THREAD

**Issue by mhomol** [microsoft/coe-starter-kit#2058]
### Describe the issue

I am currently setting up the Center of Excellence for a customer and am early in the process.  

I have successfully imported the Core Components package and am on this step to ensure that all of the Child Flows are turned on:
[Turn on Child Flows](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows)

After importing the package it looks like all but 3 child flows are currently turned on, as you can see here (all of the CLEANUP HELPER flows were On fine):
![Screen Shot 2022-02-15 at 4 19 25 PM](https://user-images.githubusercontent.com/680566/154151158-c5f060c8-6226-4659-b59f-3b2238f78d28.png)

I selected HELPER - CanvasAppOperations and attempted to Turn it On, but received the following error:
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'HIDING_THIS' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".
![Screen Shot 2022-02-15 at 4 14 29 PM](https://user-images.githubusercontent.com/680566/154151375-27ed38af-b036-49bd-8927-80e01f7eb6cf.png)

I'm not super adept with Child workflows so didn't want to dig into them and try to debug.  I did try changing the Run only users for HELPER - CanvasAppOperations to "Use this connection" then tried turning on the flow but received the same error.

Any help you can provide would be greatly appreciated

### Expected Behavior

I should be able to Turn on the Child Flows without receiving errors in this managed solution.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

HELPER - CanvasAppOperations

### Steps To Reproduce

1. Install this core component package
2. Confirm that HELPER - CanvasAppOperations is turned Off
3. Attempt to Turn ON

**Comment by Jenefer-Monroe** [comment]
The flows need to be turned on in the order shown in the documentation as they have dependencies. 
It looks like Maker Check is not turned on, which CanvasAppOperations uses

**Comment by mhomol** [comment]
thank you so very much!  that fixed it.  I see in the docs that it's number ordered but turning them on in that order was not clear.  Maybe at some point update with a note similar to what you wrote me?
