### ISSUE TITLE
[ALM Accelerator - BUG]: Run Solution checker crashes

### ISSUE THREAD

**Issue by Ballzer0** [microsoft/coe-starter-kit#2060]
### Describe the issue

Running the "Build Deploy Validation" pipeline when the "Run Solution Checker" step crashes

crash log 
```
Help         : [More Info](https://aka.ms/buildtoolsdoc)
==============================================================================
VERBOSE: InProcBindingRedirect: 2 - looking to resolve assembly: Microsoft.PowerShell.ConsoleHost.resources, 
Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
VERBOSE: InProcBindingRedirect: 1 - looking to resolve assembly: Microsoft.PowerApps.Checker.PowerShell
VERBOSE: InProcBindingRedirect: 3 - looking to resolve assembly: Microsoft.PowerApps.Checker.Client
VERBOSE: InProcBindingRedirect: 4 - looking to resolve assembly: Microsoft.IdentityModel.Clients.ActiveDirectory
VERBOSE: InProcBindingRedirect: 5 - looking to resolve assembly: System.Management.Automation.resources, 
Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
VERBOSE: InProcBindingRedirect: 6 - looking to resolve assembly: DfsrPowerShell
VERBOSE: InProcBindingRedirect: 7 - looking to resolve assembly: Microsoft.Uev.Commands
Starting PowerApps Checker Analysis...
	RuleSet: Solution Checker
	Error Level: High
	Error Threshold: 0
Processing PowerApps Checker Result...
	File: D:\a\1\a\PowerAppsChecker\20220216111515_QuantusRisikoPA10202202164.zip
	Correlation ID: b94eb085-4a7b-4ccf-868d-5e72b35bf152
	Status: FinishedWithErrors
##[error]PowerApps Checker analysis results indicate a failure or error during the analysis process.


CriticalIssueCount      : 0
HighIssueCount          : 0
MediumIssueCount        : 0
LowIssueCount           : 0
InformationalIssueCount : 0




VERBOSE: InProcBindingRedirect: 8 - looking to resolve assembly: System.IO.Compression.FileSystem
VERBOSE: InProcBindingRedirect: 9 - looking to resolve assembly: Microsoft.PowerShell.Commands.Management.resources, 
Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
Async Command Start: Upload Artifact
Uploading 2 files
File upload succeed.
Upload 'D:\a\1\a\PowerAppsChecker\results' to file container: '#/15555469/PowerAppsChecker'
Associated artifact 207 with build 981

```

Cant really figure out whats wrong with my solution. It is a pretty simple solution, just 4 cloud flows and a connection reference.
![image](https://user-images.githubusercontent.com/28560729/154257891-bbfcee38-d431-41e1-9b5e-9f8eb5e73510.png)

Some of the power automates are triggered by a canvas app, but the canvas app has been split into another solution. 

the pipeline produces an artifact called "20220216111515_QuantusRisikoPA10202202164.sarif" and a section called "invocations" thats filled with error messages like this
```
      "invocations": [
        {
          "startTimeUtc": "2022-02-16T11:15:10.569Z",
          "endTimeUtc": "2022-02-16T11:15:15.101Z",
          "toolExecutionNotifications": [
            {
              "message": {
                "text": "Error occurred running analysis on the flow Lagre risikovurdering V2. Error: StatusCode: 401; Content: {\"error\":{\"code\":\"AuthenticationFailed\",\"message\":\"Authentication failed. \"}}"
              },
              "level": "error",
              "exception": {
                "kind": "FlowFormatException",
                "message": "Error occurred running analysis on the flow Lagre risikovurdering V2. Error: StatusCode: 401; Content: {\"error\":{\"code\":\"AuthenticationFailed\",\"message\":\"Authentication failed. \"}}"
              }
            },
            {
              "message": {
                "text": "Error occurred running analysis on the flow Opprett rader risikovurdering. Error: StatusCode: 401; Content: {\"error\":{\"code\":\"AuthenticationFailed\",\"message\":\"Authentication failed. \"}}"
              },
              "level": "error",
              "exception": {
                "kind": "FlowFormatException",
                "message": "Error occurred running analysis on the flow Opprett rader risikovurdering. Error: StatusCode: 401; Content: {\"error\":{\"code\":\"AuthenticationFailed\",\"message\":\"Authentication failed. \"}}"
              }
            },
            {
              "message": {
                "text": "Error occurred running analysis on the flow Risikoberegning. Error: StatusCode: 401; Content: {\"error\":{\"code\":\"AuthenticationFailed\",\"message\":\"Authentication failed. \"}}"
              },
              "level": "error",
              "exception": {
                "kind": "FlowFormatException",
                "message": "Error occurred running analysis on the flow Risikoberegning. Error: StatusCode: 401; Content: {\"error\":{\"code\":\"AuthenticationFailed\",\"message\":\"Authentication failed. \"}}"
              }
            },
            {
              "message": {
                "text": "Error occurred running analysis on the flow SluttførRisikovurdering. Error: StatusCode: 401; Content: {\"error\":{\"code\":\"AuthenticationFailed\",\"message\":\"Authentication failed. \"}}"
              },
              "level": "error",
              "exception": {
                "kind": "FlowFormatException",
                "message": "Error occurred running analysis on the flow SluttførRisikovurdering. Error: StatusCode: 401; Content: {\"error\":{\"code\":\"AuthenticationFailed\",\"message\":\"Authentication failed. \"}}"
              }
            }
          ],
          "executionSuccessful": true
        }
      ]
```

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

 1.0.20220114.1

**Comment by mikefactorial** [comment]
Hey @Ballzer0,
Thanks for reporting and for the details. We are running into a similar issue internally and have brought it to the attention of the product team responsible for the Solution checker. The issue appears to have just cropped up in the last week. I'll forward your issue to their attention as well. If you are able to open a support ticket that may help escalate it as well. For now, it seems that disabling the Solution checker is the only workaround unfortunately. Will keep you posted as we get more information.

**Comment by Ballzer0** [comment]
> Hey @Ballzer0, Thanks for reporting and for the details. We are running into a similar issue internally and have brought it to the attention of the product team responsible for the Solution checker. The issue appears to have just cropped up in the last week. I'll forward your issue to their attention as well. If you are able to open a support ticket that may help escalate it as well. For now, it seems that disabling the Solution checker is the only workaround unfortunately. Will keep you posted as we get more information.

Is there an estimation for how long this will take? Are we talking days or weeks?

**Comment by mikefactorial** [comment]
They're aware of the issue and looking into it. I don't have an estimation from them at this point, but it's actively being worked on.

**Comment by Ballzer0** [comment]
Have you done anything to bypass this step while we are waiting for an official fix?

**Comment by Ballzer0** [comment]
> > Hey @Ballzer0, Thanks for reporting and for the details. We are running into a similar issue internally and have brought it to the attention of the product team responsible for the Solution checker. The issue appears to have just cropped up in the last week. I'll forward your issue to their attention as well. If you are able to open a support ticket that may help escalate it as well. For now, it seems that disabling the Solution checker is the only workaround unfortunately. Will keep you posted as we get more information.
> 
> Is there an estimation for how long this will take? Are we talking days or weeks?

Do you have a case ID i can reference in my support ticket? Also, im not sure where i should send my request, is it just **Help + Support** for PowerApps?

![image](https://user-images.githubusercontent.com/28560729/154264540-4faa16c6-e4ea-4dab-829e-44e875fd4ad3.png)

**Comment by mdpc-nnit** [comment]
We have the same problem - @Ballzer0 we ended up implementing the suboptimal solution to continue on error:

```

#Run Solution Checker against our solution. This is currently only triggered for pipelines that trigger for Pull Requests
- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.checker.PowerPlatformChecker@0
  displayName: 'Run Solution Checker'
  inputs:
    authenticationType: PowerPlatformSPN
    PowerPlatformSPN: '$(ServiceConnection)'
    FilesToAnalyze: '$(Build.ArtifactStagingDirectory)\$(SolutionName)_$(Build.BuildNumber).zip'
    RuleSet: '0ad12346-e108-40b8-a956-9a8f95ea18c9'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  continueOnError: true
```

This will still trigger validation deployments, if set up. However, you will not be able to see directly from the PR if the solution checker fails for valid reasons, but have to go in and check yourself.

**Comment by mikefactorial** [comment]
@Ballzer0 bypassing the solution checker can be done one of two ways
1. Comment out or update the condition on the solution checker task in the deployment pipeline https://github.com/microsoft/coe-alm-accelerator-templates/blob/6a3ded1734364f17deb35e7d01a3d21a0049dfec/Pipelines/Templates/build-Solution.yml#L141
2. If you rerun the failed pipeline manually it will bypass Solution Checker as well.
![image](https://user-images.githubusercontent.com/42348035/154290529-f1deac96-ff2d-4362-8ab0-9eeebe81168f.png)

**Comment by mikefactorial** [comment]
Didn't see @mdpc-nnit response. I like his solution better.

**Comment by mikefactorial** [comment]
@Ballzer0 and @mdpc-nnit This should be resolved now. I've verified on our end as well. Thanks again to you both for the detailed feedback and for the workarounds. Closing for now. Let us know if you have any further issues.
