### ISSUE TITLE
Apps Tab - Last Launched Date

### ISSUE THREAD

**Issue by davidvansickle** [microsoft/coe-starter-kit#2067]
### What is your question?

When reviewing the Apps tab in the Power BI dashboard, The last launch date is not populated after December 17, 2021. However the audit logs table inside of Dataverse reflected up until the current date. When we remove the last launch date and replace it with created on from the audit log it reflects current information. Can someone explain how last launch date is calculated  and why potentially this column is no longer being updated? Is there a cloud flow that updates this column that I need to look at?

### What solution are you experiencing the issue with?

Audit Log

### What app or flow are you having the issue with?

Unsure

**Comment by manuelap-msft** [comment]
The **[Child] Admin | Sync Logs** part of the Audit Log solution updates the Last Launched date of the App record. If you open a run and dive into the Switch statment you can see the action here:
![image](https://user-images.githubusercontent.com/55705669/154335824-3fb33a2a-e546-4add-8abc-45824d88a08b.png)

If the Audit Log table is up to date, it's possible the schedule refresh of the table in Power BI has failed?

**Comment by davidvansickle** [comment]
Thank you, great information.  For some reason it wasn't working so I added an Outlook notification after the Insert to see what should be getting inserted to the Last Launch Date and information is flowing.  After I save it, it seems it's now working.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
thanks for using CoE
