### ISSUE TITLE
[ALM Accelerator - BUG]: Required access right 'ReadAccess' is missing

### ISSUE THREAD

**Issue by GabeFibonacci** [microsoft/coe-starter-kit#2074]
### Describe the issue

Following the link sharing for the ALM Accelerator for Power Platform canvas app. The end user tries to create the CustomAzureDevops connection, but receives an error. It seems the ALMAcceleratorForMakers Team doesn't get synced with the ALMAcceleratorForMakers security group when the user is accessing the canvas app. The workaround at the moment is the end user clicks on the link provided in the error message. This triggers the sync between the team and the security group. Is there a better way to address this issue?

![image](https://user-images.githubusercontent.com/99877286/154477287-1f6c5b07-2ff0-45e2-8185-e025ca598031.png)
![image](https://user-images.githubusercontent.com/99877286/154476018-66e0c69b-059c-4516-bbd3-b8ff5a5c4a80.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220114.1

**Comment by devkeydet** [comment]
This, unfortunately, is a known issue in the platform that is beyond our control.  We are working with teams internally on improving this experience, but don't have any details to share right now.  For now, the workarounds are to do what you suggested or provide some other mechanism to ensure the user gets sync'd to the group team in Dataverse.  Most customers we work with today do this using a flow.  Depending on what we hear about the timing for the platform fix for this issue, we might implement a workaround in the accelerator.  But if we find a platform fix is coming soon, we won't.  Another workaround we've spiked on (which is arguably a hack) is to use a Dataverse web resource of type image that is then referenced from an image in a canvas app.  Initial tests suggest this works, but we haven't thoroughly tested it.

**Comment by GabeFibonacci** [comment]
Hi @devkeydet, thank you explaining this to me. Using a flow seems like an ideal solution for the time being to address this. Could you please provide me information around what flow action do I need to use to trigger the team sync event?

**Comment by devkeydet** [comment]
Here is a blog post that shows an approach using flow:
https://soundharyasubhash.wordpress.com/2021/05/12/force-sync-users-from-azure-ad-to-dataverse-environments-power-automate

**Comment by GabeFibonacci** [comment]
Thank you @devkeydet

**Comment by denisem-msft** [comment]
There is also a Microsoft published template for this as well for others' convenience: https://powerautomate.microsoft.com/en-US/templates/details/6e4162ca7afc48479e3ad1caadc6c1e6/force-sync-azure-active-directory-group-members-to-specified-cds-instance/
