### ISSUE TITLE
[ALM Accelerator - QUESTION] Connection Request opens Up in the Browser

### ISSUE THREAD

**Issue by GabeFibonacci** [microsoft/coe-starter-kit#2075]
### Describe the issue

When the send button pressed on connection request a new browser tab opens with the request description. Is there a way to open this in Outlook instead? Thank you

![image](https://user-images.githubusercontent.com/99877286/154484625-69bf1863-134d-48bb-bd54-f470f380e66f.png)
![image](https://user-images.githubusercontent.com/99877286/154484644-2f798327-d0fd-4f7b-9148-f400534974d9.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220114.1

**Comment by mikefactorial** [comment]
@GabeFibonacci thanks for reporting this. Since it's a mailto: link that opens it should open in your default mail client. Will need to investigate further.

**Comment by GabeFibonacci** [comment]
@mikefactorial, I found it. Thank you.
![image](https://user-images.githubusercontent.com/99877286/154516976-d6b14795-c275-4a3b-bffd-ddb108bfbfc5.png)
