### ISSUE TITLE
[ALM Accelerator - BUG]: The Project with id Does Not Exist

### ISSUE THREAD

**Issue by GabeFibonacci** [microsoft/coe-starter-kit#2083]
### Describe the issue

When trying to commit the solution from the ALM app the message below prompts. Could you please advise this? Please note that this need to be configured for citizen developers and they require minimum privileges on Azure DevOps.

![image](https://user-images.githubusercontent.com/99877286/154543115-087ac60a-13af-4e06-bc10-21946415405b.png)

### Expected Behavior

The pipeline triggers and the icon next to the Save Solution button turns blue not red.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220114.1

### Steps To Reproduce

1. Added user to DevOps with Basic license
2. Run the following command: coe alm maker add \ -f appmaker.json
![image](https://user-images.githubusercontent.com/99877286/154543978-7349c125-8e5f-4ed2-8ef6-112569cb2128.png)
3. Registered the SPN as an application user with sys admin rights on the development environment

**Comment by mikefactorial** [comment]
@GabeFibonacci This is interesting. What does the deployment profile look like in the admin app?

**Comment by GabeFibonacci** [comment]
@mikefactorial, please note that once the user added to the default sandbox team on the project then the commit succeeds. Unsure if the citizen developers should be added there if they only suppose to have minimum privilege on the project.

**Comment by GabeFibonacci** [comment]
Ok, so adding the citizen developers the sandbox team which is the member of the Project Valid Users and Contributors is the recommended way to go? 

![image](https://user-images.githubusercontent.com/99877286/154719252-c5c4464e-6295-4d3b-ba65-8757d19b317a.png)

**Comment by mikefactorial** [comment]
@GabeFibonacci you may want to use the user add command from the cli to automate the on-boarding of new users. This will ensure makers have the correct permissions to access the app / devops and associated resources / roles required to use the app. https://github.com/microsoft/coe-starter-kit/blob/main/coe-cli/docs/help/alm/user/add.md

**Comment by GabeFibonacci** [comment]
Hi @mikefactorial, I have already used the coe-cli maker coe maker add command. Please find the "Steps To Reproduce" section above for more details.  This doesn't add the user to the default Sandbox team above. Could you please let me know if I've missed something out in the json config file? Thanks

**Comment by mikefactorial** [comment]
@GabeFibonacci getting back to this. Sorry for the delay. 

To answer your question the maker add command should add the user to the AAD Group specified, but that AAD Group needs to be mapped to a group in Azure DevOps so it's possible that this is where the disconnect is. During the installation using the coe-cli an AAD Group would have been created (default name is ALMAcceleratorForMakers). This is the group that would be specified in the maker add command. This AAD Group maps to a group in Azure DevOps with the appropriate permissions also setup during install with the coe-cli. Hope this helps answer your question. Closing for now, but feel free to reopen if there's additional feedback

![image](https://user-images.githubusercontent.com/42348035/163572444-38d66130-8326-4d73-8422-63b4ad141024.png)

![image](https://user-images.githubusercontent.com/42348035/163572539-bef07151-32b4-4f29-92a2-8770180bd99a.png)
