### ISSUE TITLE
[ALM Accelerator - BUG]: import-unmanaged-to-dev-environment fails to run

### ISSUE THREAD

**Issue by Zerball1** [microsoft/coe-starter-kit#2087]
### Describe the issue

In ALM Accelerator for Power Platform canvas app. Select import solution and fill the fields as on the image below. 
![image](https://user-images.githubusercontent.com/99352598/154713621-d8f0a266-fdfb-4074-928e-e22f471518eb.png)

Click on import solution and get an error message
![image](https://user-images.githubusercontent.com/99352598/154713997-de426bf7-6490-4d1b-9161-56584b6f8a8b.png)

Text:
Error running pipeline: CustomAzureDevOps.RunPipeline failed: {"$id":"1","innerException":null,"message":"A value for the 'orgUrl' parameter must be provided.\nA value for the 'project' parameter must be provided.\nA value for the 'repo' parameter must be provided.\nA value for the 'solutionName' parameter must be provided.\nA value for the 'profileId' parameter must be provided.\nA value for the 'configurationData' parameter must be provided.","typeName":"Microsoft.Azure.Pipelines.WebApi.Pipeli...

When we tried to to test operation "RunPipeline" in a custom connector "CustomAzureDevOps", getting the same error when populate these variables:
# - Project
# - Repo
# - Branch
# - SolutionName
# - ServiceConnection
# - BuildDefinitionId
# - PipelineId
# - EnvironmentName

Do we need to do some extra configurations or pass extra parameters to be able to get values for some parameters mentioned in the text of error message?

### Expected Behavior

Be able to import solution

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.70

**Comment by mikefactorial** [comment]
@Zerball1 can't say I've seen this issue before. The next thing to check would be to see if it's possible to run the import-unmanaged-to-dev-environment pipeline in Azure DevOps. Could possibly be a permissions issue between the connector and Azure DevOps. Do other pipelines run sucessfully? e.g. export?

**Comment by Zerball1** [comment]
Same issue there. When I provide values for variables and try to run. The list of parameters that it complains about is not a part of variables in the list which were specified for this pipeline. Maybe there should be some extra config passed?
![image](https://user-images.githubusercontent.com/99352598/154761647-8cb49139-464c-4afd-b911-a128b297d490.png)

**Comment by mikefactorial** [comment]
Having a hard time getting context here based on the error. Here is an example of a successful run of the import pipeline.

![image](https://user-images.githubusercontent.com/42348035/154767378-4f6d1715-ebeb-4d33-bbe1-964f11ebaba8.png)

How does this differ from your runs?

**Comment by mikefactorial** [comment]
This seems like it may be a setup issue. Did you setup the accelerator manually or use the cli?

**Comment by mikefactorial** [comment]
orgUrl and configurationData shouldn't be variables passed to the import pipeline so something isn't right with the setup.

**Comment by ChrisL66** [comment]
Issue seems to be related to these parameters in update-canvas-app-ownership.yml - called via import-unmanaged-to-dev-environment.yml
Where are these parameter set?

if(-Not [string]::IsNullOrWhiteSpace($environments)) {
                coe alm branch --pipelineRepository $(Build.Repository.Name) -o ${{parameters.orgUrl}} -p "${{parameters.project}}" -r "${{parameters.repo}}" -d "${{parameters.solutionName}}" -a $env:SYSTEM_ACCESSTOKEN -s $environments

**Comment by mikefactorial** [comment]
@ChrisL66 the code above is from the update-deployment-settings.yml which is only ever called from the export pipeline, not the import pipeline. @Zerball1 I'd be interested in seeing how the import pipeline is configured and wonder if you are able to run the pipeline manually. You'd need to set the variables manually in order to run the pipeline but that may provide some insight since this doesn't appear to be related to the app or the connector and instead looks like a problem with the pipeline setup.

![image](https://user-images.githubusercontent.com/42348035/157900112-30b76834-9c35-40b7-bced-fbc10260b137.png)

![image](https://user-images.githubusercontent.com/42348035/157900249-e2628d3b-e0ce-4858-985a-cca4948cd435.png)

**Comment by mikefactorial** [comment]
Can you verify the import-unmanaged-to-dev-environment pipeline looks like the screenshot above?

**Comment by ChrisL66** [comment]
Yes looks the same

Above code is in update-canvas-app-ownership.yml

we did get it working through some code mods
even after setting some of the variables it was not working/getting passed through the pipeline
I will check with my team, to get the details on what code we changed and share back here

We also did not have all the variables set like you have above set so will review again, 

Many thanks for the info
We are rolling it out in our environment with multiple devs next week ;-)

**Comment by mikefactorial** [comment]
Thanks @ChrisL66. Appreciate the feedback would be great to know what needed to be changed. The error is very strange / unexpected. The variables I showed above were simply for running the pipeline manually to test / verify. They otherwise would be passed in by the app and don't need to be set manually as shown.

**Comment by ChrisL66** [comment]
Just realized I had overwritten the update-canvas-app-ownership.yml file with the wrong content

**Comment by mikefactorial** [comment]
Ah. Starting to make sense. @ChrisL66 wondering is @Zerball1's issue the same as yours (i.e. do you two work together?)

**Comment by ChrisL66** [comment]
Yes same team ;-)

**Comment by mikefactorial** [comment]
Good to know thanks @ChrisL66 let me know how it goes. Will close this out for the time being but feel free to reopen if necessary or open a new issue.
