### ISSUE TITLE
[CoE Starter Kit - BUG] Questions on Installing CenterofExcellenceCoreComponentsTeams_3_12_managed

### ISSUE THREAD

**Issue by bkrotz** [microsoft/coe-starter-kit#2089]
### Describe the issue

Install CenterofExcellenceCoreComponentsTeams_3_12_managed

Issue1: CoE Starter Kit >Dataverse for Teams Environment>Set up inventory components>Turn on setup flows
When follow the instruction to turn on the setup flows, there are two flows missing. It did not included in the core components.
- Command Center App > Get CoE Flows
- Command Center App > St CoE Flows State

Issue2: CoE Starter Kit >Dataverse for Teams Environment>Set up inventory components>Turn on inventory flows
There is no instructions to turn on inventory flows. Which flow should it be turned on (all or some of the flow)?
Is there a specific order to follow to turn on the flow?

Issue3: CoE Starter Kit >Dataverse for Teams Environment>Set up inventory components>Share apps with other admins
Did not find how to manage permission and assign roles. Only see assign dataverse security roles. Which security roles should be assigned? Please advise. 

![sharewithadmin](https://user-images.githubusercontent.com/50377264/154736894-9027f815-f5a6-430e-9181-2661811a7066.png)

### Expected Behavior

Need more instructions

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

no flow

### Steps To Reproduce

CoE Starter Kit >Dataverse for Teams Environment>Set up inventory components

**Comment by Jenefer-Monroe** [comment]
Hello, you do not have the latest version of the starter kit and so the instructions will not perfectly align to your needs. 
The documentation is currently written for the Feb release (Core 3.31)

**Comment by bkrotz** [comment]
Thanks for the information. Will you please pointing me out the direction to get the documentation (Core 3.31)?

Thanks!

**Comment by bkrotz** [comment]
Thanks for the information about issue 1 and issue 3.

For issue 2
![SetupInventoryComponents](https://user-images.githubusercontent.com/50377264/154757012-0c4412df-1782-4ced-b9c0-b8aedfd0daef.png)

I am looking at the document that updated on "2/15/2022". This is my first time to install this core component. I didn't find instructions that I need to turn on those flows. 

![Turn on Inventory flows2](https://user-images.githubusercontent.com/50377264/154757222-2efd22e9-4752-4222-82ce-106331e6a8e6.png)

Do I need to turn on the above flow one by one?

Thanks!

**Comment by Jenefer-Monroe** [comment]
I see. Yes there is a typo there. just ignore that cut off sentence. 
All flows in this article need turned on in the order shown.

**Comment by bkrotz** [comment]
Thanks for the information. It's very helpful.

**Comment by Jenefer-Monroe** [comment]
You are welcome. I will go ahead and close then.
