### ISSUE TITLE
[CoE Starter Kit - QUESTION] How does the Flow Approval BPF work (was looking for something similar to the Admin | Compliance Request v3 for the Apps) 

### ISSUE THREAD

**Issue by raphaeltremblay1966** [microsoft/coe-starter-kit#2091]
### What is your question?

How does the Flow Approval BPF work ? I was looking/hoping for something similar to the Admin | Compliance Request v3 flow that kicks in once every week for the Apps where the Maker would receive an email that would point him to the Developer Compliance Center to modify the Audit fields in their App. 

Am I missing something  ?

Thanks

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.31 (February 2022)

### What app or flow are you having the issue with?

Flow Approval BPF

**Comment by Jenefer-Monroe** [comment]
It does not do that. It just runs in the background to do some field manipulation. This allows you to manually flag flows for compliance review and still have it flow through the review process. But the compliance flow is not setup to auto-flag any flows as requiring compliance.

**Comment by raphaeltremblay1966** [comment]
Thanks a lot.

**Comment by Jenefer-Monroe** [comment]
You bet, thanks for using CoE
