### ISSUE TITLE
[CoE Starter Kit - Previous version 

### ISSUE THREAD

**Issue by PPAC-CoE** [microsoft/coe-starter-kit#2097]
### What is your question?

Hi 

From where I can download the previous version of the CoE starter kit looks like, I am having issue to upgrade it from the older version to the latest.

Also can you please suggest the any upgrade guide lines - I have followed this  - https://github.com/microsoft/coe-starter-kit/issues/1005
But still I am having some issues.

Thanks

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

 Audit Logs etc

**Comment by manuelap-msft** [comment]
Hello,

you can find our previous releases in the Release tab from GitHub
https://github.com/microsoft/coe-starter-kit/releases

This goes back to May 2021 when we moved to this GitHub repo. Older versions than that are not available.

Our upgrade instructions are documented here 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup

Manuela

**Comment by PPAC-CoE** [comment]
Hi - Thanks for your response I will go through the link and let you know asap.
