### ISSUE TITLE
[ALM Accelerator - QUESTION] What is wrong with Update Deployment Settings step

### ISSUE THREAD

**Issue by pavelsubik** [microsoft/coe-starter-kit#2103]
### What is your question?

I'm trying to configure the ALM Accelerator. I have a "config" subfolder in the repository and a deploymentSettings.json file in it.
I'm still getting the Update Deployment Settings error "Add-Member: Cannot bind argument to 'InputObject' parameter because it is null."
What am I doing wrong?

![image](https://user-images.githubusercontent.com/73695166/155105400-4c051f7b-f1b4-4d29-b175-ca8bb9c39c21.png)

![image](https://user-images.githubusercontent.com/73695166/155105754-bcc7556c-1a0b-433a-a847-b86a5fae3aaf.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

February 2022

**Comment by mikefactorial** [comment]
@pavelsubik take a look at the queue time variables passed into your export pipeline. You should see something like the following. Take note of anything that's missing or looks different here.

![image](https://user-images.githubusercontent.com/42348035/155139817-e8b5cae7-1aa0-459c-a169-dd6051d67aeb.png)

**Comment by mikefactorial** [comment]
We have an existing issue to better handle potentially invalid urls passed to the export pipeline. Make sure that the deployment profile has valid environment urls for Validation, Test and Prod.

https://github.com/microsoft/coe-starter-kit/issues/1935

**Comment by pavelsubik** [comment]
@mikefactorial  Json stored in Data is not valid. The comma separating the fields is missing, but it's the same in your screenshot. The other parameters look ok

![image](https://user-images.githubusercontent.com/73695166/155148131-e25923d0-af35-4f85-b705-9e89e29584d9.png)

**Comment by mikefactorial** [comment]
@pavelsubik yeah the missing comma is a bit of a red herring. For whatever reason it just looks like that when Azure DevOps emits it in the logs, but is actually well formatted. What's interesting here is that there is only one user settings record. That may likely be where things are going wrong. Let me run some tests. Thanks for the details.

**Comment by winterscar** [comment]
This usually happens when the deployment pipelines have no variables set on them (i.e when you forget to do [this step](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#setting-deployment-pipeline-variables) in the setup). If a pipeline has _no_ variables, trying to append more fails.

**Comment by pavelsubik** [comment]
This is an export-to-git pipeline. If the variable does not exist, it is created. It is failing on this line, am I right?

![image](https://user-images.githubusercontent.com/73695166/155275353-2ba1efed-5e2c-4c77-9d3a-d0135184bf54.png)

**Comment by pavelsubik** [comment]
@winterscar You are right Matt, Deploy channels did not have the EnvironmentName and ServiceConnection variables set.

Thank you all

![image](https://user-images.githubusercontent.com/73695166/155277214-cff2e7e0-2b12-4adc-8d0e-6bfd8bb33153.png)

**Comment by pavelsubik** [comment]
Result: EnvironmentName and ServiceConnection variables were not set for Deploy pipelines.
