### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to raise DLP change request in Maker- Environment access app which is part of COE starter kit

### ISSUE THREAD

**Issue by AnchalBerwal** [microsoft/coe-starter-kit#2105]
### Describe the issue

Unable to raise DLP change request  in Maker- Environment access app which is part of COE starter kit

### Expected Behavior

User should be able to select Policy in New DLP change request app but unable to do so. How do we fix this? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20.6

### What app or flow are you having the issue with?

Maker - Environment Request

### Steps To Reproduce

1. Click on create new DLP change request.
2. Try selecting the policy. We are stuck here as lookup is not working.

### Anything else?

We also found that DLP policy table has no data, could that be the issue?
<img width="872" alt="DLP policy data" src="https://user-images.githubusercontent.com/98586339/155131292-42411ab0-4736-4f0d-a492-53a3c48b0704.png">

**Comment by manuelap-msft** [comment]
Hello,

I'm sorry, we need a little bit more detail here to understand what's going on!

Have you synced DLP policies and shared them with makers for request: https://docs.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt#sync-shared-policies?
Have you turned on all the flows to sync DLP policies? https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-environment-components#turn-on-flows
What drop down is not working?
Are users able to submit a request and it's not showing up in the DLP policy request table?

Manuela

**Comment by AnchalBerwal** [comment]
Hey Manuela, thanks for your revert and this really helped, turns out I missed a configuration step. Apologies for a delayed confirmation.
