### ISSUE TITLE
[ALM Accelerator - Feature]: Document User license requirements

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#2109]
### Is your feature request related to a problem? Please describe.

Not obvious from documentation what the requirements are for user licenses across the stack of ALM Accelerator

### Describe the solution you'd like

Add documentation on requirements for user licenses across the stack of the ALM Accelerator
- Power Platform
- Azure DevOps

**Comment by mikefactorial** [comment]
This was included in the March release
