### ISSUE TITLE
[ALM Accelerator - QUESTION] QUESTION

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#2111]
### What is your question?

Do I find anywhere in the AA4PP app the deployment information based on the runs of my deployment pipelines:
![image](https://user-images.githubusercontent.com/15800069/155176020-9ea0aa57-2eeb-4efc-a0ac-663961cff3d4.png)

I would expect the deployment status here:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/15800069/155176236-0cc9841e-c2d9-429d-8c9c-b2d9b7bb7f84.png">

Am I wrong?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220114.1

**Comment by mikefactorial** [comment]
@megel we're tracking this. The January release removed this information from the App but we're planning to add it back. https://github.com/microsoft/coe-starter-kit/issues/1898. Feel free to add your thoughts on that issue. Closing for now
