### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow Run History and Errors

### ISSUE THREAD

**Issue by mhomol** [microsoft/coe-starter-kit#2112]
### What is your question?

Does the CoE inventory the Run History of Flows?  If so, can I see that in PBI or the PP Admin View?  We are specifically curious about flows that are failing often.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

**Comment by manuelap-msft** [comment]
Hello,

the CoE kit does not include cloud flow run history, as there is no way to get this information from the product. See our documentated limitations: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#monitoring-cloud-flow-runs

Manuela
