### ISSUE TITLE
[CoE Starter Kit - Feature]: Store App Created From as part of App sync flow

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2113]
### Is your feature request related to a problem? Please describe.

Apps can be created from templates, from data and from scratch. An tag/identifier for this is returned as part of Power Apps for Admins when we get a list of the apps and we should store this in the PowerApps App table as an additional attribute. It would allow for better reporting on maturity of makers.

### Describe the solution you'd like

Store the App Created From attribute in the PowerApps App table.

**Comment by Jenefer-Monroe** [comment]
test with these too, to see if they are identified, the dataverse for teams sample apps [Use sample apps from teams store - Power Apps | Microsoft Docs](https://docs.microsoft.com/en-us/powerapps/teams/use-sample-apps-from-teams-store)

**Comment by Jenefer-Monroe** [comment]
consider also adding an environment variable for admins to exclude template apps from compliance flows

**Comment by manuelap-msft** [comment]
not available in product, closing out
