### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs not returning a subset of logs

### ISSUE THREAD

**Issue by e-moshe** [microsoft/coe-starter-kit#2115]
### Describe the issue

see issue description in attached file.
 
 
 
 
 
 

[COE audit statistics problem.zip](https://github.com/microsoft/coe-starter-kit/files/8123289/COE.audit.statistics.problem.zip)

### Expected Behavior

filter from o365 audit logs **all**  the information relevant to PowerApps

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.3.6

### What app or flow are you having the issue with?

Power Platform Governance Admin Environment -> Cloud flows -> [Child] Admin | Sync Logs

### Steps To Reproduce

run the flow

### Anything else?

no

**Comment by Jenefer-Monroe** [comment]
Hello it appears you are on a very old version of the Audit Logs solution, so you likely dont have our chunking customization and notification. 
The backend doesn't support returning multiple pages of results so in the parent now we chunk up the requests into hourly (by default) chunks. 
If hourly is not small enough chunks you get a notice in email to the admin-email, and then you can configure the chunks smaller. 
Please see https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

**Comment by ibutbul1** [comment]
I Jenefer, same issue for me.

So from where I can get the zip files containing the updated solution ?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team.
