### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by nehaa1234567890** [microsoft/coe-starter-kit#2120]
### Describe the issue

Unable to deploy CoE

### Expected Behavior

It should be deployed in our enviornment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

Power Automate

**Comment by nehaa1234567890** [comment]
Hi.. Could you please help me in deploying CoE in our environment.  Please call me on +917906337889 and treat this on urgent basis.

**Comment by manuelap-msft** [comment]
Hello,

thanks for reaching out! I edited your comment and removed the phone number as this is a public forum. 

The CoE starter kit is not part of the Power Platform product itself, and instead represents a sample implementations of features with the aim to provide templates and a starting point for customers looking to adopt the platform. The kit itself is not supported (see: https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support) and our team does not offer a service to help install or set it up.

If you are looking for help setting the kit up, you will have to work with one of our partners - see https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1

Manuela
