### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by LucasLGH** [microsoft/coe-starter-kit#2121]
### Describe the issue

Flow: Admin | Add Maker to Group

The action name: Add member to group

please configure the Environment variable.

### Expected Behavior

please configure the Environment variable.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Admin | Add Maker to Group

### Steps To Reproduce

Flow: Admin | Add Maker to Group

The action name: Add member to group

please configure the Environment variable.

**Comment by manuelap-msft** [comment]
Hello,

I'm unsure what error you are facing. Could you share some screenshots or a more detailed description please?

Thank you
Manuela

**Comment by LucasLGH** [comment]
This one is fine.




But the 'Add member to group' action use the old code, It will cause operation error.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/coe-starter-kit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月24日(星期四) 晚上8:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #2121)





 
Hello,
 
I'm unsure what error you are facing. Could you share some screenshots or a more detailed description please?
 
Thank you
 Manuela
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jenefer-Monroe** [comment]
It's still unclear what you are facing, and if you shared a picture, note that they dont come through if you reply in email, you have to login to GitHub to share pictures. 

It sounds like maybe you didnt configure the env variable for the group? 
Here are the env variables used for the inventory: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#all-environment-variables

And in particular, this is the env var it sounds like you forgot to add:
![image](https://user-images.githubusercontent.com/89584709/155727240-18895b7f-a239-4585-8914-ab8acf78fbae.png)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for the starter kit team.
