### ISSUE TITLE
The data is not refreshing in the CoE toolkit

### ISSUE THREAD

**Issue by SESA377903** [microsoft/coe-starter-kit#2123]
### Describe the issue

The data is not refreshing and showing the old data and getting the below error.

Processing error: A join operation cannot result in a table with duplicate column names ("owningbusinessunitname").
Cluster URI: WABI-NORTH-EUROPE-G-PRIMARY-redirect.analysis.windows.net
Activity ID: cac5556e-448e-4d4f-8bad-0861722577eb
Request ID: 9fa92e43-993c-fb38-c14b-1df7835eab98
Time: 2022-02-23 11:43:20Z

Please help.
Thanks
Siva

### Expected Behavior

The latest data should be shown.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Aug 2021

### What app or flow are you having the issue with?

Admin

### Steps To Reproduce

The data is not refreshing and showing the old data and getting the below error.

Processing error: A join operation cannot result in a table with duplicate column names ("owningbusinessunitname").
Cluster URI: WABI-NORTH-EUROPE-G-PRIMARY-redirect.analysis.windows.net
Activity ID: cac5556e-448e-4d4f-8bad-0861722577eb
Request ID: 9fa92e43-993c-fb38-c14b-1df7835eab98
Time: 2022-02-23 11:43:20Z

Please help.
Thanks
Siva

### Anything else?

No

**Comment by manuelap-msft** [comment]
You're on an old version of the CoE Starter Kit and Power BI dashboard! The issue you're reporting has been raised before, and fixed with the December release - see this thread https://github.com/microsoft/coe-starter-kit/issues/1291#issuecomment-983765403 

Closing as duplicate.
