### ISSUE TITLE
[ALM Accelerator - BUG]: SharePoint Environment Variable - SharePoint Site Doesn't Show Up

### ISSUE THREAD

**Issue by GabeFibonacci** [microsoft/coe-starter-kit#2125]
### Describe the issue

The user who is configuring a solution with owner rights on the SharePoint site is unable to see the site on the dropdown list when configuring the SP env variable data source. Any idea what could be the issue?

![image](https://user-images.githubusercontent.com/99877286/155565880-b4daecbe-faf9-49df-bbbb-dba5e1d862df.png)

### Expected Behavior

The site shows up on the dropdown list for the user with site owner SP privileges. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220114.1

### Steps To Reproduce

1. Select Configure Deployment Settings on the solution 
2. Click on Environment Variables
3. Click on the Drop Down list for the SharePoint Site Url env variable
4. Find the site (the user's go owner rights and can see a number of sites on the dropdown list)

**Comment by mikefactorial** [comment]
Hey @GabeFibonacci. I'm having some trouble replicating this issue. In my environment if I go to Sharepoint and look for all sites e.g. https://foo.sharepoint.com/_layouts/15/sharepoint.aspx?p=3&q=*&v=%2Fsearch%2Fsites. I see a list of 42 sites come back that I have access to. Similarly, in the ALM Accelerator I see a list of 42 sites to pick from for my Sharepoint Datasource Environment Variable. Is there anything specific about the sites in your case that aren't showing up in the environment variable list that might help reproduce this? Adding a few more users who reported the same issue. @antonydineshhenry #2041 @jenschristianschroder #1460

**Comment by mikefactorial** [comment]
Closing this out for now as there's been no updates in over a month. Feel free to open a new issue if this is still a problem in the latest release.

**Comment by FarFromLogic** [comment]
after running into the variable resetting bug I now need to manually select my sharepoint site, it does not appear in the search, I can find the production sharepiont site (only difference is Dev and UAT have -Dev and -UAT after the site name) but not the site I need
