### ISSUE TITLE
[CoE Starter Kit - Feature]: Automatically set Component Framework at Environment Creation

### ISSUE THREAD

**Issue by rooobeert** [microsoft/coe-starter-kit#2129]
### Is your feature request related to a problem? Please describe.

Hi! 
I just realized that everytime that an environment is created and I wanted to Import the Apps that I provided in the Theming gallery, I would need to go in and turn on the Components Framework for the apps to work...

Thanks
Robert

### Describe the solution you'd like

It would be definetly be convenient if the environments get already set up like that, if not already. 

![image](https://user-images.githubusercontent.com/87785803/155858290-1200304a-3278-4b9d-9eaf-0c2c4b1f264d.png)

AB#1827

**Comment by manuelap-msft** [comment]
Hello,

thanks for the feedback! I believe there currently isn't a way to automatically set this on environment creation through the connector that we're using, but we can investigate this.

Manuela

**Comment by manuelap-msft** [comment]
We now know how to do this by modifying a field in the organization table of the environment that was created, and can consider including this in the Env Request application
