### ISSUE TITLE
[CoE Starter Kit - BUG] Embedded apps in Power BI not opening

### ISSUE THREAD

**Issue by Dharanya13** [microsoft/coe-starter-kit#2131]
### Describe the issue

PowerApp/Power automate components of COE Toolkit is not opening up in the Power BI desktop

### Expected Behavior

Example:
Power BI Desktop -> Apps tab -> select any app listed -> right click -> Drill through -> App detail

Should display the PowerApps component inside the Power BI desktop but throws an error as "Sorry, we didn't find that app"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Power BI Desktop - App Detail/Cloud flow detail

### Steps To Reproduce

Power BI Desktop -> Open the COE Dashboard -> Apps tab -> select any app listed -> right click -> Drill through -> App detail

**Comment by manuelap-msft** [comment]
Have you followed these steps to configure the embedded apps: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard ?

**Comment by Dharanya13** [comment]
Hi Manuela Pichler,

Thanks. I have followed all the steps provided in the link; however, I have an empty space in place of the App usage under the "App Details" section as in the below screenshot.

***@***.***

Thanks,
Dharanya


Dharanya Udayakumar
Senior Consultant|Rapid Circle Australia
Level 19, 15 William St, Melbourne|Tel: +61386092816|www.rapidcircle.com
|

**Comment by manuelap-msft** [comment]
Unfortunately screenshots don't come through when you reply via email. You will have to open GitHub and respond from there: https://github.com/microsoft/coe-starter-kit/issues/2131

**Comment by Dharanya13** [comment]
Hi Manuela, 
Please find the screenshot attached here
<img width="737" alt="Capture" src="https://user-images.githubusercontent.com/100100197/155977875-1e24205a-7069-466d-b08a-d12813ce35e7.PNG">

**Comment by manuelap-msft** [comment]
Hello,

it looks like the canvas app is showing correctly (under Manage App), so the embedded app is working in Power BI.

The App Usage tab is not related to the embedded canvas app. This would show information regarding app usage collected from the Audit Log in the Audit Log table.
1. To collect this information, please set up the Audit Log solution https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
2. Audit Log events will only be collected from the moment the kit is set up and don't look back, so you don't get historic data
3. If you have set up the Audit Log solution and the flows are failing, let us know so we can investigate further.

**Comment by Dharanya13** [comment]
Thanks, Manuela, for helping out. Appreciate it

Cheers,
Dharanya


Dharanya Udayakumar
Senior Consultant|Rapid Circle Australia
Level 19, 15 William St, Melbourne|Tel: +61386092816|www.rapidcircle.com
|
