### ISSUE TITLE
[CoE Starter Kit - QUESTION] Maker does not have permissions to perform Archive Approval

### ISSUE THREAD

**Issue by Dave-Weldon** [microsoft/coe-starter-kit#2133]
### What is your question?

Good morning,

After reinstalling the CoE due to some issues we had I've just received nearly 300 emails from the app & flow archive process saying the Flow Maker does not have permissions to perform Archive Approval.

It's obviously a permission that has been missed but I've looked back through the install instructions from start to finish and can't see what I've done wrong.

Is this something you might be able to assist as to which permission I have missed for our makers?

Thanks in advance.
![Flow Error](https://user-images.githubusercontent.com/70806759/155977926-36a4a5e8-6eb4-4193-b7fc-ef894180979c.jpg)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.12

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Apps), Admin | Archive and Clean Up v2 (Start Approval for Flows)

**Comment by manuelap-msft** [comment]
Hello,

is your environment protected with an Environment Security Group? See https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#security-groups-and-approvals and https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#create-your-environment

**Comment by Dave-Weldon** [comment]
Hi Manuela,

Thank you so much for your speedy reply.

Yes it was restricted this way *facepalm*

I've just removed the group, are there any other steps to clear any data or is removal of the group the only thing I need to do?

**Comment by manuelap-msft** [comment]
Of course!

The removal should be the only step, and users will be assigned the Approvals Users security role automatically as soon as you assign an approval to them - there's no action for you to assign this to users. You can read up on this a bit more here: https://docs.microsoft.com/en-us/power-automate/get-started-approvals#assign-approvals-to-any-user-in-your-tenant

I'll close this ticket now but please do let us know if you have further questions!
