### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by brucetbarrett** [microsoft/coe-starter-kit#2141]
### Describe the issue

Installed CoE v 3.20.6, but I'm having an issue with the Cloud Flow "Admin | Sync Template v3" failing to run every time at "Get Environment" and "Get Maker" for 3 specific Teams Environments. The only thing these environments seem to have in common is they were all created by the same user.

Admin | Sync Template v3 --> Store environments in the CoE CDS Entity --> Apply to each environment --> Check if legacy environment --> If no --> Get Environment (fails) and Get Maker (fails)

Get Environment returns:
"error": "code": "0x80040217",
"message": "admin_environment With Id = ********-****-****-****-************ Does Not Exist"

Get Maker returns:
Status code: 502
"error": "code": "NoResponse",
"message": "The server did not receive a response from an upstream server. Request tracking id '*********************************'."

### Expected Behavior

The flow should successfully lookup the user information a create an entry for the environment in CoE CDS.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20.6

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

Happens every time I run it.

### Anything else?

Could this be a permission thing?

**Comment by Jenefer-Monroe** [comment]
Hello, this is fixed via #2079 for the March release available this week. 
There is a temp fix suggested in that bug if you cannot wait. 

Thank you for using CoE
