### ISSUE TITLE
Audit log Custom Connector The length of the query string for this request exceeds the configured maxQueryStringLength value

### ISSUE THREAD

**Issue by devinprejean** [microsoft/coe-starter-kit#2146]
### Describe the issue

I'm getting this error when trying to fix the connection on my audit log custom connector. I go to authenticate and it shows me a server error (YSOD) with the text The length of the query string for this request exceeds the configured maxQueryStringLength value. It worked before. The password on the service account changed but there is the same problem when I use a different account to connect.

### Expected Behavior

Successfully create/fix the connection when authenticating.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.38

### What app or flow are you having the issue with?

Child Audit Log

### Steps To Reproduce

Create a new connection, or fix a broken one for the custom connector

**Comment by Jenefer-Monroe** [comment]
Hello. When you need to recreate the connection (it expires for example), you need to first update the custom connector again. You cannot directly just “fix connection”. I don’t know why this is, but it’s the case. 

See the notes in this GitHub bug for instructions: [CoE Starter Kit - BUG] Audit Logs solution fails after upgrade · Issue #1424 · microsoft/coe-starter-kit (github.com). 

Basically you redo the setup steps from when you originally installed [Setup Custom Connector](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector), except you dont need to restart the subscription.

**Comment by devinprejean** [comment]
Thanks, I'll try that out and let you know.

**Comment by devinprejean** [comment]
It looks like that will work, however I am being forced to get admin approval again for consent prompt. Why?

**Comment by Jenefer-Monroe** [comment]
I don't follow. Did you edit the app registration permissions? You don't need to do that. If you do, I imagine it would prompt for this.

**Comment by devinprejean** [comment]
I can only assume permissions have been added in the past to the app principal where it requires another admin grant... I am trying to get the granting done now but the admin is getting this message. "No reply address is registered for the application." I checked and see the redirect URI is set to the one from the custom connector page... I'm still working through it all.

**Comment by devinprejean** [comment]
I had an admin consent, but wasn't prompted to consent for the whole org for some strange reason. So now I fixed the connection but there is an error with the API. Maybe it changed since it was working last August 2021. Now I'm getting the error 
The permission set (.153ef316-1151-427a-ba11-4dbb8fb40e36) sent in the request does not include the expected permission.

**Comment by Jenefer-Monroe** [comment]
That error message usually means that the permissions were not set correctly for the app registration. Be sure you have set delegated permissions to ActivityFeed.Read.

**Comment by devinprejean** [comment]
Well that's weird because I've always had the application permissions of ActivityFeed.Read before. I'll try the delegated and let you know.

**Comment by devinprejean** [comment]
That fixed it. Looks like the API permissions changed from the last time it ran. Thanks so much @Jenefer-Monroe !

**Comment by Jenefer-Monroe** [comment]
YEAH! Are you all set then?

**Comment by Jenefer-Monroe** [comment]
looks like you are, didnt notice it was closed :) 

Thanks for using CoE
