### ISSUE TITLE
[CoE Starter Kit - BUG] Custom Connectors sync flow fails to parse - HTTP brought back application/octet-stream

### ISSUE THREAD

**Issue by Dharanya13** [microsoft/coe-starter-kit#2147]
### Describe the issue

Hi Team,

The below Admin| Sync Template V3 flows are failing

1. Admin| Sync Template V3 (Custom connectors) -  Workflow fails at "Get Custom connectors and store them in CoE CDS Entity"
2. Admin| Sync Template V3 (Portals) - Check to see if portal Model Driven App Exists. Store in portal CoE Entity

There isn't much information to drill down the issue further. 

### Expected Behavior

Workflows should run successfully 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Admin - Sync Template V3 (Custom connectors, Portals)

### Steps To Reproduce

1. Admin| Sync Template V3 (Custom connectors) -> Get Custom connectors and store them in CoE CDS Entity -> Apply to each connector - Parse JSON
2. Admin| Sync Template V3 (Portals) -> Check to see if portal Model Driven App Exists -> Loop through each website record ->site settings filtering for authentication types -> Auth open registration enable
3.Please see the below images for error description
<img width="868" alt="Admin Sync Template V3 (Custom connectors)" src="https://user-images.githubusercontent.com/100100197/156277137-4077f512-f6b7-48b0-b7af-729cf30f1a5e.PNG">
<img width="858" alt="Admin Sync Template V3 (Portals)" src="https://user-images.githubusercontent.com/100100197/156277152-f8aa7450-5cee-4f01-9a8e-d7467716aee9.PNG">
d

**Comment by Jenefer-Monroe** [comment]
Hello, the Portals issue is known and local fixed for March (targetted to go out tomorrow) with #2045

**Comment by Jenefer-Monroe** [comment]
I will change this title to track the custom connector failure only as a result.

**Comment by Jenefer-Monroe** [comment]
We dont have a repro like this. Can you please:

- Share here the contents returned from the HTTP call for that parse failure?
- Do you know how that custom connector was created?

**Comment by Dharanya13** [comment]
Hi,

I am not sure how the custom connector is created but here is the HTTP call returned,


{
  "$content-type": "application/octet-stream",
  "$content": "ew0KICAic3dhZ2dlciI6ICIyLjAiLA0KICAiaW5mbyI6IHsNCiAgICAidmVyc2lvbiI6ICIxLjAuMCIsDQogICAgInRpdGxlIjogIldlYmhvb2tDb2xsZWN0aW9uIiwNCiAgICAiZGVzY3JpcHRpb24iOiAiV2ViaG9va0NvbGxlY3Rpb24iDQogIH0sDQogICJob3N0IjogIndlYmFwcHRlc3Rha3NoYXkuYXp1cmV3ZWJzaXRlcy5uZXQiLA0KICAic2NoZW1lcyI6IFsNCiAgICAiaHR0cHMiDQogIF0sDQogICJwcm9kdWNlcyI6IFsNCiAgICAiYXBwbGljYXRpb24vanNvbiINCiAgXSwNCiAgInBhdGhzIjogew0KICAgICIve2Nvbm5lY3Rpb25JZH0vYXBpL29mZmljZW1vbiI6IHsNCiAgICAgICJwb3N0Ijogew0KICAgICAgICAic3VtbWFyeSI6ICJQT1NUIFJlcXVlc3QgT2ZmaWNlMzY1bW9uIHdlYmhvb2siLA0KICAgICAgICAiZGVzY3JpcHRpb24iOiAiVGhlIEhUVFAgYFBPU1RgIHJlcXVlc3QgbWV0aG9kIGlzIG1lYW50IHRvIHRyYW5zZmVyIGRhdGEgdG8gYSBzZXJ2ZXIgXG4oYW5kIGVsaWNpdCBhIHJlc3BvbnNlKS4gV2hhdCBkYXRhIGlzIHJldHVybmVkIGRlcGVuZHMgb24gdGhlIGltcGxlbWVudGF0aW9uXG5vZiB0aGUgc2VydmVyLlxuXG5BIGBQT1NUYCByZXF1ZXN0IGNhbiBwYXNzIHBhcmFtZXRlcnMgdG8gdGhlIHNlcnZlciB1c2luZyBcIlF1ZXJ5IFN0cmluZyBcblBhcmFtZXRlcnNcIiwgYXMgd2VsbCBhcyB0aGUgUmVxdWVzdCBCb2R5LiBGb3IgZXhhbXBsZSwgaW4gdGhlIGZvbGxvd2luZyByZXF1ZXN0LFxuXG4+IFBPU1QgL2hpL3RoZXJlP2hhbmQ9d2F2ZVxuPlxuPiA8cmVxdWVzdC1ib2R5PlxuXG5UaGUgcGFyYW1ldGVyIFwiaGFuZFwiIGhhcyB0aGUgdmFsdWUgXCJ3YXZlXCIuIFRoZSByZXF1ZXN0IGJvZHkgY2FuIGJlIGluIG11bHRpcGxlXG5mb3JtYXRzLiBUaGVzZSBmb3JtYXRzIGFyZSBkZWZpbmVkIGJ5IHRoZSBNSU1FIHR5cGUgb2YgdGhlIHJlcXVlc3QuIFRoZSBNSU1FIFxuVHlwZSBjYW4gYmUgc2V0IHVzaW5nIHRoZSBgYENvbnRlbnQtVHlwZWBgIEhUVFAgaGVhZGVyLiBUaGUgbW9zdCBjb21tb25seSB1c2VkIFxuTUlNRSB0eXBlcyBhcmU6XG5cbiogYG11bHRpcGFydC9mb3JtLWRhdGFgXG4qIGBhcHBsaWNhdGlvbi94LXd3dy1mb3JtLXVybGVuY29kZWRgXG4qIGBhcHBsaWNhdGlvbi9qc29uYFxuXG5UaGlzIGVuZHBvaW50IGVjaG9lcyB0aGUgSFRUUCBoZWFkZXJzLCByZXF1ZXN0IHBhcmFtZXRlcnMsIHRoZSBjb250ZW50cyBvZlxudGhlIHJlcXVlc3QgYm9keSBhbmQgdGhlIGNvbXBsZXRlIFVSSSByZXF1ZXN0ZWQuIiwNCiAgICAgICAgIm9wZXJhdGlvbklkIjogIlBvc3RSZXF1ZXN0T2ZmaWNlMzY1bW9uV2ViaG9vayIsDQogICAgICAgICJwYXJhbWV0ZXJzIjogWw0KICAgICAgICAgIHsNCiAgICAgICAgICAgICJuYW1lIjogImNvbm5lY3Rpb25JZCIsDQogICAgICAgICAgICAiaW4iOiAicGF0aCIsDQogICAgICAgICAgICAicmVxdWlyZWQiOiB0cnVlLA0KICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwNCiAgICAgICAgICAgICJ4LW1zLXZpc2liaWxpdHkiOiAiaW50ZXJuYWwiDQogICAgICAgICAgfSwNCiAgICAgICAgICB7DQogICAgICAgICAgICAibmFtZSI6ICJDb250ZW50LVR5cGUiLA0KICAgICAgICAgICAgImluIjogImhlYWRlciIsDQogICAgICAgICAgICAicmVxdWlyZWQiOiB0cnVlLA0KICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwNCiAgICAgICAgICAgICJkZWZhdWx0IjogIiBhcHBsaWNhdGlvbi9qc29uIiwNCiAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICJDb250ZW50LVR5cGUiLA0KICAgICAgICAgICAgIngtbXMtc3VtbWFyeSI6ICJDb250ZW50LVR5cGUiDQogICAgICAgICAgfSwNCiAgICAgICAgICB7DQogICAgICAgICAgICAibmFtZSI6ICJib2R5IiwNCiAgICAgICAgICAgICJpbiI6ICJib2R5IiwNCiAgICAgICAgICAgICJzY2hlbWEiOiB7DQogICAgICAgICAgICAgICJ0eXBlIjogIm9iamVjdCIsDQogICAgICAgICAgICAgICJwcm9wZXJ0aWVzIjogew0KICAgICAgICAgICAgICAgICJTdWJzY3JpcHRpb25JZCI6IHsNCiAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsDQogICAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAiU3Vic2NyaXB0aW9uSWQiLA0KICAgICAgICAgICAgICAgICAgIngtbXMtc3VtbWFyeSI6ICJTdWJzY3JpcHRpb25JZCINCiAgICAgICAgICAgICAgICB9LA0KICAgICAgICAgICAgICAgICJjb21wYW55bmFtZSI6IHsNCiAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsDQogICAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAiY29tcGFueW5hbWUiLA0KICAgICAgICAgICAgICAgICAgIngtbXMtc3VtbWFyeSI6ICJjb21wYW55bmFtZSINCiAgICAgICAgICAgICAgICB9LA0KICAgICAgICAgICAgICAgICJXZWJob29rTm90aWZpY2F0aW9uVHlwZSI6IHsNCiAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsDQogICAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAiV2ViaG9va05vdGlmaWNhdGlvblR5cGUiLA0KICAgICAgICAgICAgICAgICAgIngtbXMtc3VtbWFyeSI6ICJXZWJob29rTm90aWZpY2F0aW9uVHlwZSINCiAgICAgICAgICAgICAgICB9LA0KICAgICAgICAgICAgICAgICJOb3RpZmljYXRpb25PdXRhZ2VJbmZvIjogew0KICAgICAgICAgICAgICAgICAgInR5cGUiOiAib2JqZWN0IiwNCiAgICAgICAgICAgICAgICAgICJwcm9wZXJ0aWVzIjogew0KICAgICAgICAgICAgICAgICAgICAiT3V0YWdlTm90aWZpY2F0aW9uVHlwZSI6IHsNCiAgICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciLA0KICAgICAgICAgICAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICJPdXRhZ2VOb3RpZmljYXRpb25UeXBlIiwNCiAgICAgICAgICAgICAgICAgICAgICAieC1tcy1zdW1tYXJ5IjogIk91dGFnZU5vdGlmaWNhdGlvblR5cGUiDQogICAgICAgICAgICAgICAgICAgIH0sDQogICAgICAgICAgICAgICAgICAgICJSZXNvdXJjZSI6IHsNCiAgICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciLA0KICAgICAgICAgICAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICJSZXNvdXJjZSIsDQogICAgICAgICAgICAgICAgICAgICAgIngtbXMtc3VtbWFyeSI6ICJSZXNvdXJjZSINCiAgICAgICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICAgICAgfSwNCiAgICAgICAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICJOb3RpZmljYXRpb25PdXRhZ2VJbmZvIiwNCiAgICAgICAgICAgICAgICAgICJ4LW1zLXN1bW1hcnkiOiAiTm90aWZpY2F0aW9uT3V0YWdlSW5mbyINCiAgICAgICAgICAgICAgICB9LA0KICAgICAgICAgICAgICAgICJOb3RpZmljYXRpb25TZXJ2aWNlU3RhdHVzSW5mbyI6IHsNCiAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm9iamVjdCIsDQogICAgICAgICAgICAgICAgICAicHJvcGVydGllcyI6IHsNCiAgICAgICAgICAgICAgICAgICAgIlNlcnZpY2VOYW1lIjogew0KICAgICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsDQogICAgICAgICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIlNlcnZpY2VOYW1lIiwNCiAgICAgICAgICAgICAgICAgICAgICAieC1tcy1zdW1tYXJ5IjogIlNlcnZpY2VOYW1lIg0KICAgICAgICAgICAgICAgICAgICB9LA0KICAgICAgICAgICAgICAgICAgICAiRmVhdHVyZU5hbWUiOiB7DQogICAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwNCiAgICAgICAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAiRmVhdHVyZU5hbWUiLA0KICAgICAgICAgICAgICAgICAgICAgICJ4LW1zLXN1bW1hcnkiOiAiRmVhdHVyZU5hbWUiDQogICAgICAgICAgICAgICAgICAgIH0sDQogICAgICAgICAgICAgICAgICAgICJDdXJyZW50U3RhdHVzIjogew0KICAgICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsDQogICAgICAgICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIkN1cnJlbnRTdGF0dXMiLA0KICAgICAgICAgICAgICAgICAgICAgICJ4LW1zLXN1bW1hcnkiOiAiQ3VycmVudFN0YXR1cyINCiAgICAgICAgICAgICAgICAgICAgfSwNCiAgICAgICAgICAgICAgICAgICAgIlByZXZpb3VzU3RhdHVzIjogew0KICAgICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsDQogICAgICAgICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIlByZXZpb3VzU3RhdHVzIiwNCiAgICAgICAgICAgICAgICAgICAgICAieC1tcy1zdW1tYXJ5IjogIlByZXZpb3VzU3RhdHVzIg0KICAgICAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICAgICAgICB9LA0KICAgICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIk5vdGlmaWNhdGlvblNlcnZpY2VTdGF0dXNJbmZvIiwNCiAgICAgICAgICAgICAgICAgICJ4LW1zLXN1bW1hcnkiOiAiTm90aWZpY2F0aW9uU2VydmljZVN0YXR1c0luZm8iDQogICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICB9LA0KICAgICAgICAgICAgICAiZGVmYXVsdCI6IHsNCiAgICAgICAgICAgICAgICAiU3Vic2NyaXB0aW9uSWQiOiAiMjgxMGMxNWMtZDE0Ny00YWRkLWEwNjctMTc5MzNhMzgxODU2IiwNCiAgICAgICAgICAgICAgICAiY29tcGFueW5hbWUiOiAicmMiLA0KICAgICAgICAgICAgICAgICJXZWJob29rTm90aWZpY2F0aW9uVHlwZSI6ICIxIiwNCiAgICAgICAgICAgICAgICAiTm90aWZpY2F0aW9uT3V0YWdlSW5mbyI6IHsNCiAgICAgICAgICAgICAgICAgICJPdXRhZ2VOb3RpZmljYXRpb25UeXBlIjogIjEiLA0KICAgICAgICAgICAgICAgICAgIlJlc291cmNlIjogIjEiDQogICAgICAgICAgICAgICAgfSwNCiAgICAgICAgICAgICAgICAiTm90aWZpY2F0aW9uU2VydmljZVN0YXR1c0luZm8iOiB7DQogICAgICAgICAgICAgICAgICAiU2VydmljZU5hbWUiOiAiU2VydmljZSBuYW1lIiwNCiAgICAgICAgICAgICAgICAgICJGZWF0dXJlTmFtZSI6ICJGZWF0dXJlIG5hbWUiLA0KICAgICAgICAgICAgICAgICAgIkN1cnJlbnRTdGF0dXMiOiAiQ3VycmVudFN0YXR1cyIsDQogICAgICAgICAgICAgICAgICAiUHJldmlvdXNTdGF0dXMiOiAiUHJldmlvdXNTdGF0dXMiDQogICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICB9DQogICAgICAgICAgICB9LA0KICAgICAgICAgICAgInJlcXVpcmVkIjogdHJ1ZQ0KICAgICAgICAgIH0NCiAgICAgICAgXSwNCiAgICAgICAgInJlc3BvbnNlcyI6IHsNCiAgICAgICAgICAiZGVmYXVsdCI6IHsNCiAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICJkZWZhdWx0IiwNCiAgICAgICAgICAgICJzY2hlbWEiOiB7DQogICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyINCiAgICAgICAgICAgIH0NCiAgICAgICAgICB9DQogICAgICAgIH0NCiAgICAgIH0NCiAgICB9DQogIH0sDQogICJkZWZpbml0aW9ucyI6IHt9LA0KICAic2VjdXJpdHlEZWZpbml0aW9ucyI6IHt9LA0KICAiYmFzZVBhdGgiOiAiLyINCn0="
}

**Comment by manuelap-msft** [comment]
Closing out as we don't repo this.
