### ISSUE TITLE
[CoE Starter Kit - Feature]: features request - inventory without delay - triggers for things like app creation

### ISSUE THREAD

**Issue by Srise96** [microsoft/coe-starter-kit#2148]
### Is your feature request related to a problem? Please describe.

Our objective is to automatically detect any Power Platform components (Power Automate Cloud flows, Power Automate Desktop Flows, Power Apps, Power Virtual Agents, Solutions) **that is newly created/deleted across Environments** and update the record in CoE Dataverse tables.

Once a newly created Power Platform component is detected, we will trigger an email to the user who have created the component with the details of it.

We are trying to achieve this feature however, the Solutions and Cloud Flows available in CoE starter kit are not meeting the requirements.

### Describe the solution you'd like

1) Automatically detect any Power Platform components that is newly created or deleted across Environments(Power Automate Cloud Flows, Power Automate Desktop Flows, Power Apps, Power Virtual Agents), extract the details and update in the CoE Dataverse tables.

2) Automatically detect any Solutions that is newly created or deleted across Environments, extract the details and update in the CoE Dataverse tables.

**Comment by manuelap-msft** [comment]
Hello,

the CoE Starter Kit does detect newly created objects via the sync flows. Could you please describe in more details where the kit today doesn't meet your  needs?

Manuela

**Comment by Srise96** [comment]
The sync flows sits in CoE Prod environment and run based on a schedule (once every day) to update the newly created components in CoE Dataverse table.

However, in our scenario we want to automatically detect the components across Environments when it is newly created and trigger a flow immediately, to send an email to the creator for each components.

Let's say user A creates a Power Automate Desktop Flow in a default environment, we want to detect the Desktop flow once it is created and trigger a flow where it will capture the all the Desktop flow details and finally send an email to the user A.

We are not sure how the Sync flows can achieve this automatic trigger across Environments since Sync flows sits in CoE Prod environment or maybe how we can leverage on this Sync flows to meet our requirements?

**Comment by manuelap-msft** [comment]
I see, thanks for explaining. There's no trigger mechanism available in the product for this at the moment - the admin connectors only support polling (e.g. list apps as admin) and the create events in the O365 Audit Log only show up with a 24 hour delay. With the CoE Kit, you will only be able to achieve an email notification with a 24 hr delay as the sync flows run daily.

**Comment by Srise96** [comment]
Thanks for the explanation. I have few more queries regarding this as stated below

1 ) Can you please describe in detail about "the admin connectors only support polling (e.g. list apps as admin)" and "the create events in the O365 Audit Log only show up with a 24 hour delay"?

2) Is there any flows in Coe Starter kit which can get the deleted Power Platform components details across Environments?

3) What will be the impact if I change the sync flows to run every 5 minutes? Will it still update the component details in Dataverse table after 24 hours delay?

**Comment by manuelap-msft** [comment]
1. We use connectors such as Power Platform for Admins (https://docs.microsoft.com/en-us/connectors/powerplatformforadmins/) or Power Apps for Admins (https://docs.microsoft.com/en-us/connectors/powerappsforadmins/) to get inventory in the CoE Starter Kit. If you look at the connectors, you can see that they do not have triggers (e.g. when an app is created) but only have actions like "list environments as admin" or "get apps as admin". This means the connectors do not support triggers, this capability is not available in the product. The CoE Starter Kit is built on top of the Power Platform product and can only use what's available in the product. 
Certain events are logged in the Office 365 Audit Log (see https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps and https://docs.microsoft.com/en-us/power-platform/admin/logging-power-automate), however Power Platform events only show up 24 hours after the event - see https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide
![image](https://user-images.githubusercontent.com/55705669/156570935-c396f2ca-bba3-4d06-9b00-dbbfee61cfb6.png)
2. There are flows which have "Check Deleted" in the name and they check for deleted resources by comparing what's in your tenant vs whats in the CoE tables. 
3. Depending on the size of your tenant, you may run into API throttling limits of you change the frequency of this flow. https://docs.microsoft.com/en-us/power-automate/limits-and-config

**Comment by Srise96** [comment]
Hello, thanks for your reply.

However, we want to explore more if the existing solutions or any other solutions in the CoE Starter Kit can meet our requirements or maybe if we can leverage on it.

We have raised a Microsoft Support (2203010050000371) earlier regarding this and Susan Nguyen from Microsoft PowerApps & Power Automate Support team is assisting us.

Would it be possible for any of the CoE Developers/Experts to join a call with us to discuss further on this? Please let us know.

**Comment by manuelap-msft** [comment]
Hello, we're a very small team who maintains the CoE starter kit and unfortunately can not help with extending or customizing the kit, or jumping on support calls! 

I'll close this ticket now as mentioned above, what you're trying to achieve is not possible due to product limitations and you're now getting support from Microsoft support.
