### ISSUE TITLE
[CoE Starter Kit] "Flow Archive Request Ignored Since" not updated even if user replies to approval

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2154]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/2151

<div type='discussions-op-text'>

<sup>Originally posted by **poppynka** March  2, 2022</sup>
Hi,

we are getting a lot of complains that managers receive reports about ignored approvals, even if flow owners already replied that they want to keep the flow. I can see that in one of the cases the _Flow Archive Request Ignored Since_ was not updated after first "Decline" of the approval. 

example case:
the flow was created on 5/6/2021
archive approval Nr.1 was created on 1/24/2022
user declined the approval on: 1/24/2022
archive approval Nr.2 was created on 2/28/2022

the person has declined the first approval request, then received a second one, declined it and his manager was notified that he is ignoring the request, because on a flow I can see: _flow archive request ignored since_ = 1/24/2022

I can't find in which flow the _Flow Archive Request Ignored Since_ field is updated after responding to approval. There is nothing in _Admin | Archive and Clean Up v2 (Check Approval)_ and in _Custom | Admin | Archive and Clean Up v2 (Start Approval for Flows)_ I can see only reseting value in case of Approved approval. Then in branch of declined approvals, the "ignored since" field is changed only if there are some other unanswered approvals

look here:
![image](https://user-images.githubusercontent.com/6829792/156348469-79b5e3ab-0b38-4b3d-8939-eb4444f1d16f.png)
-> if rejected = yes, then fetch all other ignored archive approval (= approval response eq null, but in our case there are none)
-> then for each ignored archive approval - delete this item and reset value flow archive ignored since
=> in our case this whole for-each cycle was skipped and the "ignored since" on flow was never updated

in my case, the person has replied already twice (rejected twice) and the "ignored since" is never changed, so his manager keeps getting notifications about it. The user is not ignoring and still gets reported to his manager

Please - is this field set somewhere else in case of rejected approvals? Am I overlooking something or is it a bug?
 
thanks,
Andrea</div>

**Comment by Jenefer-Monroe** [comment]
Thank you, we do set this as you see in the **Start Approval** flows but we may as well do it straight away in the **Check Approvals** flow so that you dont get a accidental resend if the admin mail flow runs again before start approval. 

I can make this change for April. 
Thanks for the detailed investigation!

**Comment by Jenefer-Monroe** [comment]
Added to the Check Approvals flow, so the ignored since date will get cleared as soon as we record their response.

**Comment by poppynka** [comment]
thanks, @Jenefer-Monroe that will be really helpful 🙂 👍

**Comment by poppynka** [comment]
> Thank you, we do set this as you see in the **Start Approval** flows but we may as well do it straight away in the **Check Approvals** flow so that you dont get a accidental resend if the admin mail flow runs again before start approval.
> 
> I can make this change for April. Thanks for the detailed investigation!

hey, I am just thinking - would it make sense in that case to set a default times in the schedule step of the cleanup flows? 🙂  

But I think that in our case we have changed time of the "Email managers ignored approvals" flow to 22:00, expecting the "Start approvals" to run in the same day morning. For some reason, as I have turned on the Email managers, it was immediately triggered, so they both were actually running at the same time. So this was probably the issue. And the fact that the flow did not respect the schedule time is not something that neither of us can affect 😞

**Comment by Jenefer-Monroe** [comment]
Now that we moved the clearing of the date to **_Check Approval_** we should we good as it runs every day, whereas **_Email Managers_** only runs weekly. So while there may still be an overlap, it will be small.

In the past this was set in **_Start Approval_** which only runs once every 2 weeks! Not sure what I was thinking :)

**Comment by ashmsport** [comment]
I was still having this issue after installing the April update. Just installed the latest version from June. Is there anything that needs to be updated in the Flow for it to stop reminding managers about the Flows which were approved/rejected?

**Comment by Jenefer-Monroe** [comment]
Do you have unmanaged layers on the flow? That will prevent you from seeing updates from us. 
Please review [removing unmanaged layers](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) from our [updating the CoE](https://docs.microsoft.com/power-platform/guidance/coe/after-setup) documentation.

**Comment by ashmsport** [comment]
No managed layer in Admin | Email Managers Ignored Inactivity notifications Approvals or any other governance component flow.
![image](https://user-images.githubusercontent.com/33230123/175323622-eddc8f69-e721-4701-8468-dc200e430c6f.png)

**Comment by Jenefer-Monroe** [comment]
I dont entirely remember this fix at this point, but per the above the changes was in this flow
![image](https://user-images.githubusercontent.com/89584709/156585411-109d2745-2fc5-43c6-8567-33b5adbce314.png)

Please make sure none of your flows have unmanaged layers, including that one.

**Comment by ashmsport** [comment]
I don't see this Flow, it's missing: Admin | Archive and Clean Up v2 (Check Approval)

**Comment by Jenefer-Monroe** [comment]
Something must be wrong with your install then. I'm afraid I cant help with that beyond offering a suggestion. Perhaps you could try an overwrite upgrade in the classic UX
 
Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)
 
Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)
 
Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png)
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by ashmsport** [comment]
Our CoE is installed in in D4T. I reinstalled the Core for Teams, Governance and Nurture components once again but still don't see that flow.

**Comment by Jenefer-Monroe** [comment]
I'm afraid I cannot assist then. You seem to be in a strange state in your envt.
