### ISSUE TITLE
[CoE Starter Kit - BUG] Governance Flow Failed to Turn on - Request Orphaned Objects Reassigned [Child]

### ISSUE THREAD

**Issue by H-4-l** [microsoft/coe-starter-kit#2155]
### Describe the issue

Flow fails to turn on.
Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"MultipleErrorsOccurred","message":"Multiple errors occurred: 'BadRequest,BadRequest'. Please see details.","details":[{"code":"ChildFlowNeverPublished","message":"The workflow with id 'ab3784ff-ceef-eb11-bacb-00224820693c' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."},{"code":"ChildFlowNeverPublished","message":"The workflow with id 'b538d20c-d1ef-eb11-bacb-00224820693c' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}]}}".

No flows with the referenced IDs are found in the environment.

### Expected Behavior

Flow Turns on successfully.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

 Request Orphaned Objects Reassigned [Child]

### Steps To Reproduce

1. Access Flow Edit Screen.
2. Turn on Flow.
Error returned:
Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"MultipleErrorsOccurred","message":"Multiple errors occurred: 'BadRequest,BadRequest'. Please see details.","details":[{"code":"ChildFlowNeverPublished","message":"The workflow with id 'ab3784ff-ceef-eb11-bacb-00224820693c' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."},{"code":"ChildFlowNeverPublished","message":"The workflow with id 'b538d20c-d1ef-eb11-bacb-00224820693c' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}]}}".

**Comment by Jenefer-Monroe** [comment]
It sounds like you tried to turn the parent flow on before the child flow. Please note these need to be turned on in the order show in the setup instructions

**Comment by H-4-l** [comment]
Hi Jenefer,

The setup presents them in child first order then the parent.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-orphan-components#turn-on-flows

The parent (Request Orphaned Objects Reassigned (Parent))  is producing the following error.

Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'a405dd4c-78e5-eb11-bacb-000d3a8edeaa' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

**Comment by Jenefer-Monroe** [comment]
Can you clarify, Is the child flow turned on?

**Comment by H-4-l** [comment]
Here are both the child and parent errors.

**Child** 
Flow fails to turn on.
Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"MultipleErrorsOccurred","message":"Multiple errors occurred: 'BadRequest,BadRequest'. Please see details.","details":[{"code":"ChildFlowNeverPublished","message":"The workflow with id 'ab3784ff-ceef-eb11-bacb-00224820693c' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."},{"code":"ChildFlowNeverPublished","message":"The workflow with id 'b538d20c-d1ef-eb11-bacb-00224820693c' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}]}}".

**Parent**
The parent (Request Orphaned Objects Reassigned (Parent)) is producing the following error.

Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'a405dd4c-78e5-eb11-bacb-000d3a8edeaa' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

**Comment by Jenefer-Monroe** [comment]
Are you trying to turn them on at the same time or 1 by 1? Please share a screenshot. 
That error on the child is suspicious as published means turned on. So its saying you cannot turn on the flow because it was never turned on.

**Comment by H-4-l** [comment]
Found the "Helper" flow  dependencies in the Governance Components.
Please close as user error. Governance Components steps are listed in the Notes.
