### ISSUE TITLE
[CoE Starter Kit - BUG] Desktop Flow table/report is empty

### ISSUE THREAD

**Issue by AdnanJusicMS** [microsoft/coe-starter-kit#2156]
### Describe the issue

Hi lovely COE Team,

I have a question again. I am facing at a customer environment an empty CoE Dashboard report "Desktop flow" and also the table Desktop flow in the core component of the CoE is empty. Both flows "Desktop flow" and "Desktop flows" complete successfully, but there is no desktop flow inserted into the mentioned table and therefore no data shows up in the bi report "Desktop flows".

Flows

![1](https://user-images.githubusercontent.com/96141055/156450762-4eca4bec-7381-43d4-a0f1-fb256c01c941.png)

![2](https://user-images.githubusercontent.com/96141055/156450767-d29d609d-6ab5-4299-89d9-232ebae117bd.png)

Table Desktop Flow

![3](https://user-images.githubusercontent.com/96141055/156450802-800b8481-f983-47ea-bc26-10b25ff78229.png)

Example of availble desktop flow

<img width="754" alt="5" src="https://user-images.githubusercontent.com/96141055/156451066-ab4938d5-debc-45e8-b35a-06436e412cc8.png">

Any suggestion how to troubleshoot this case? Everthing is running fine, but there flows are not inserted into the table.

Thanks a lot in advance!

Kind regards,

Adnan

### Expected Behavior

Desktop flows should be inserted in the desktop flow table of the CoE core component.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Admin - Sync Template v3 (Desktop flows)

### Steps To Reproduce

1. Open make.powerapps.com
2. Open the core componente solution
3. Open Table "Desktop flow"
4. You should see in this table entries for the existing destktop flows.

**Comment by Jenefer-Monroe** [comment]
I believe you have hit a product bug around payload size and the legacy connector. 

First, please create a new flow, in your CoE environment
Insert the List Rows action of the legacy dataverse connector:
![image](https://user-images.githubusercontent.com/89584709/156187277-7691cc59-37ef-4188-b95e-34b5410ff63b.png)
![image](https://user-images.githubusercontent.com/89584709/156187413-edf66727-100f-4f49-ba2e-5a3bc9cc8c30.png)

Select the environment where you expect to see a bunch of desktop flows from the first dropdown. Then select the Processes table
![image](https://user-images.githubusercontent.com/89584709/156188428-5efe941f-8856-4a75-b6a9-99a1c1291b80.png)

Save and run the flow. Does it return the expected Desktop Flows?

**Comment by AdnanJusicMS** [comment]
Hi Jennefer,

thanks for the hint. As you assume, the customer didn’t receive desktop flows by the created flow (as you mentioned).

In my case in the DEV I receive my desktop flows.

Do you think we have a solution to solve the product bug?

Thanks a lot for your huge support!

Kind regards,

Adnan

**Comment by Jenefer-Monroe** [comment]
We dont have a solution to offer in the interim unfortunately, although we will snap to the modern connector as soon as its offered. 

This is a limitation we have written out here: https://docs.microsoft.com/power-platform/guidance/coe/limitations#large-desktop-flows

Sorry we can't be of more assistance while we await the product change!

**Comment by AdnanJusicMS** [comment]
> We dont have a solution to offer in the interim unfortunately, although we will snap to the modern connector as soon as its offered.
> 
> This is a limitation we have written out here: https://docs.microsoft.com/power-platform/guidance/coe/limitations#large-desktop-flows
> 
> Sorry we can't be of more assistance while we await the product change!

Hi Jenefer,

thank you very much for all the information and all you patiences and willingess to support.

I have forwared all the info to the customer.

Kind regards,

Adnan

**Comment by Jenefer-Monroe** [comment]
That is the solution we will use, to use the new dataverse connector. But it must first support the ability to query non-current envt. At the moment, the modern Dataverse connector only supports querying the current environment but not other environments in the tenant. Once that's possible, we'll change our flows to use the new Dataverse connector. Until then, we can't.

There is also an "Automation CoE" that you could try if you need this sooner, it has a different architecture and so does not have this limitation: 
- [Automation Center of Excellence Webinar](https://info.microsoft.com/ww-thankyou-businesscenterexcellencerpa.html?LCID=EN-US&ocid=eml_pg332504_gdc_comm_ba)
- [Microsoft Power Platform Automation CoE starter kit (preview)](https://docs.microsoft.com/power-platform/guidance/automation-coe/automation-coe-starter-kit)
- [RPA CLI](https://github.com/rpapostolis/rpa-cli)

**Comment by G1982C** [comment]
Thanks Jenefer, that is really helpful to understand the dependency. I have just taken a look at the Automation CoE and I am not quite ready to configure, implement and manage another CoE.
