### ISSUE TITLE
[CoE Starter Kit - BUG]Installing CoE March Solution fails

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#2162]
### Describe the issue

When I try and Install the MArch Update to the CoE Cor Components - it fails because it cannot delete various connection references becuase they are used by Various flows (Seescreen shot) 
![image](https://user-images.githubusercontent.com/8484048/156622167-70ae7b0e-8cf4-422e-aa8d-e6649a111c62.png)
the V2 flows only exist in the default solution and nowhere else - I am trying to upgrade from 3.31 -> 3.34

Regards

Nigel

### Expected Behavior

I expect to upgrade - no problems.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Admin Sync Template V2 etc 

### Steps To Reproduce

in my CoE environment -> Import Solution (core components 3.34) - upgrade - finsih.

THis has not happened before

**Comment by Jenefer-Monroe** [comment]
What version of Governance are you on? Over the last 6 months we have done the work to clean out these connection references.

**Comment by NPrice99** [comment]
As in what? CoE ? Currently 3.31 wanting to upgrade to 3.34

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jenefer-Monroe** [comment]
The Governance solution (aka audit components). 
![image](https://user-images.githubusercontent.com/89584709/156627512-ef2a4f6d-3837-468a-b527-7ebf39cf7c2c.png)

All these flows are in the governance solution
![image](https://user-images.githubusercontent.com/89584709/156627000-12ac8ea1-60b8-44a4-8a5a-ba7363ab3fd1.png)

If you aren't using the Governance components I suggest you delete that solution to avoid issues like this in the future, and then install it when you are ready to use it!

**Comment by NPrice99** [comment]
OK will try when I get home

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
