### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor v2 not returning any impacted apps or flows

### ISSUE THREAD

**Issue by DS2019** [microsoft/coe-starter-kit#2164]
### Describe the issue

I installed the CoE about a week ago, and when using the DLP Editor, it finds no impacted apps ad flows for any of my environments. 
For example, I have a Dev environment, and was trying to move items like Blob Storage and File System into Non-Business from Business because I know that we have Flows that use these connectors and in the same Flow other connectors like Outlook that are in Business. . It found no impacted apps and flows. Then, 2 days ago, I created a Form and a Flow in the Dev environment. In the Flow I used the Office 365 Outlook connector. I ran the Flow successfully. In the DLP Editor, I moved Forms into Non-Business. 
Yet, the DLP Editor V2 does not find any impacted apps or flows. 

### Expected Behavior

I would expect to see the Flow I made in the Dev environment with Microsoft Forms and Outlook connectors to be flagged. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

The latest

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

1) I open Teams > Power Apps > Build > CoE > Apps > Open in Power Apps > Launch DLP Editor v2
2) I run the DLP Editor and move the connector for Forms into Non-Business, while keeping the Outlook connector in Business. 
3) the App tells me no impacted apps and flows found. 

### Anything else?

![DLP Editor](https://user-images.githubusercontent.com/44073678/156702809-4f968dc2-7351-4fae-91c6-34c3b113160f.jpg)

**Comment by manuelap-msft** [comment]
Hello, can I just quickly confirm you have installed Core components in a Dataverse for Teams enviornment and not a Production environment? Just so we can investigate this in the right version for us!

**Comment by Jenefer-Monroe** [comment]
Note that if you did not let the connectors

**Comment by DS2019** [comment]
> Hello, can I just quickly confirm you have installed Core components in a Dataverse for Teams enviornment and not a Production environment? Just so we can investigate this in the right version for us!

Yes, that's right, we are using Dataverse for Teams. Thank you!

**Comment by Jenefer-Monroe** [comment]
Note also that if you did not let the connectors flow complete before doing the inventory, then your connections may have have been inventoried. 
Please see here from the [inventory setup instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-setup-flows)
![image](https://user-images.githubusercontent.com/89584709/156773829-26b9f47c-8cb2-4cdd-93fe-69bf648b3f38.png)

If this was the case, you would need to ensure that flow has completed and then do a [full inventory run](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory)

**Comment by DS2019** [comment]
Thank you! I have updated to yesterday's version of the CoE and am running an inventory, as per documentation. Will post back once that is all done.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
