### ISSUE TITLE
[CoE Starter Kit - BUG] Issue in CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

### ISSUE THREAD

**Issue by Rjrahul358** [microsoft/coe-starter-kit#2166]
### Describe the issue

we have received a lot of messages that maker's manager could not be contacted, because the manager is not in the Office365 anymore (because he left the company), but he still exists in Dataverse and he is assigned to a Maker as his M1 manager.

In the flow CLEANUP - Admin | Sync Template v3 (Orphaned Makers) they check if maker is orphaned. In our case he's orphaned in reality, but Dataverse does not know about it, because our records still contain manager and he is M1 manager to a maker.

So, when they check if the maker is orphaned, flow says no (because the field M1 Manager is not empty). The flow then goes to the branch "no".

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/100849868/156711277-5e65624d-24d0-4f63-aca8-9c1674e6de59.png)

Then the flow assumes that the manager exists, because lenght of the list of managers is more than 0. It tries to retrieve the manager using the child flow in Get Manager M1 step.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/100849868/156711386-e219cfe3-60b3-492c-b64a-8626551651df.png)

But since the user does not exist in the Office 365, the child flow returns "failure" result and this step is throwing BadGateway error for some reason. it's not possible to track deeper, because the child flow is triggered by too many other flows. We can't possibly find the correct runs of the child flow.

### Expected Behavior

I would expect it to clear the M1 manager field, if he's not in Office 365.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20.6

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

### Steps To Reproduce

This flow is run when there is orphaned makers.

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid I dont follow you here. It sounds like you have two issues. Lets take them one at a time, as I believe there is some misunderstanding. 

Your first issue: **Users that have left the organization do not show as orphaned**.
Is that correct? You have that issue? 

Note that this call does not key off the manager existing, but the user. 
![image](https://user-images.githubusercontent.com/89584709/156775877-ee21c9f1-377e-4411-9bc3-b7cdf77b27c6.png)

If this is in fact, one of your issues, please gather the users GUID and Display Name, and go to the **Helper - Maker Check** flow, and run it with that data. Be sure to set Recheck to True

![image](https://user-images.githubusercontent.com/89584709/156777139-bc63a0de-9a26-48aa-8dc1-99c402fff3d4.png)


When it is done running, look at the body of the response, and see how they are flag wrt being an orphan
![image](https://user-images.githubusercontent.com/89584709/156777626-6926c10a-8fcc-4745-ac5a-eb3710663adb.png)

**Comment by Rjrahul358** [comment]
Yes, you are correct we are mixing the two topics over here.

We received "The request to this manager failed or timed out.

If timed out, consider reaching out to them to ensure they understand the importance of this work.

If failed it may be due to the number of objects being too large for the adaptive card, you will need to work with them to resolve, or just assign all objects to them.
Or it could be due to other reasons like them blocking conversations with the flow bot.

Please look at the run to see what occurred, and the list of objects, to determine how best to proceed." this email 

Do we get it correctly that the manager is ignoring us or he blocked the teams bot and that's why the child flow timed out and we got this message?

**Comment by Jenefer-Monroe** [comment]
Yes, there are several reasons it may have timed out, as listed there. You can click the run to see more details.

**Comment by Rjrahul358** [comment]
As your comment I checked the run and my observation is, manager was received the adaptive card into the teams as per run but he not responded to it due that time out is occurs, so manager and admin both were received the mail regarding that.

**Comment by Jenefer-Monroe** [comment]
Makes sense. Do you have any other questions?

**Comment by Rjrahul358** [comment]
No, other question from my side.
