### ISSUE TITLE
[CoE Starter Kit - Feature]: Compliance request emails for Flows and Custom Connectors

### ISSUE THREAD

**Issue by BhargavPrasadGorakanti** [microsoft/coe-starter-kit#2171]
### Is your feature request related to a problem? Please describe.

Hi, Just wanted to check reg. COE Toolkit's compliance process. Currently, the Admin | Compliance Detail Request v3 flow only sends out compliance emails for Apps and Chatbots. We are looking to extend that to flows and custom connectors as well. 

### Describe the solution you'd like

Before building something on our own, wanted to check if this was already planned for a future release or if there are any reasons to not implement it for flows and custom connectors.

### Describe alternatives you've considered

Extending the existing flow to add sections for flows and custom connectors. Defining our own standards for non-compliance by referring to the conditions that are checked for Apps.

**Comment by manuelap-msft** [comment]
Hello,

for Apps, the compliance details request is based on how many users the app is shared with or how often the app is launched.
for Bots, the compliance details request is based on how often the bot is launched.

So basically the usage indicates the ask for compliance - thresholds can be set by the admin here, but it's basically to ensure we don't ask for compliance for an app that's never used that only the maker has access to anyway.

For flows and custom connectors, we do not have information on how many people it's shared with and how many people are using it, hence we've held off on implementing automated compliance request flows for it. It's not currently in our backlog to add compliance requests for those, but if you share your standards for what you would consider non-compliant and we think they'd apply to and be valuable for more customers, we'd be happy to add this feature ask to our backlog.

Thank you
Manuela

**Comment by BhargavPrasadGorakanti** [comment]
Thanks for your response Manuela! We are yet to come up with our own standards for non-compliant flows / custom connectors. I will circle back in case we have something useful to share.

**Comment by manuelap-msft** [comment]
No clear conditions available for these flows, so closing this request out.
