### ISSUE TITLE
CoE Starter Kit Upgrade 

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#2172]
### What is your question?

I currently have Core Components February 2022 installed in my tenant. When trying to upgrade to March's version. I do not get any upgrade message. Therefore, I would have to fill environment variables values again. 
<img width="839" alt="issuecoe" src="https://user-images.githubusercontent.com/100951593/156789200-b10a0a9b-9e80-4e77-a0c9-4552fce7eb59.png">
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2022

### What app or flow are you having the issue with?

Does not apply

**Comment by manuelap-msft** [comment]
I don't think we've introduced new environment variables with the upgrade from February to March, so if you have previously filled out all environment variables or environment variables have default values, you won't get prompted to provide them again.

**Comment by Jenefer-Monroe** [comment]
I believe what you are saying is that you expect to see upgrade UX like this and you dont. It looks like a new install not an upgrade
![image](https://user-images.githubusercontent.com/89584709/156802165-2c0287df-c0cf-4521-b10b-01e6dc55cd09.png)

Is that what you are saying? 

If so, how did you install last time? Did you use the ALM toolset? I see that solution there. 
Can you close the import UX and show us what is has for the other columns for Core? (ex name, version, managed externally, ...)

**Comment by LizethRegules** [comment]
Exactly, instead of seeing previous version and new version in the import pane, it looks like a new install.
I always install from the solution tab in power apps. I do not use the ALM toolset. 
 
<img width="758" alt="coeissue2" src="https://user-images.githubusercontent.com/100951593/156803476-e324a258-a143-4d5d-b77a-13644f368314.png">

**Comment by Jenefer-Monroe** [comment]
Can you expand the name field? I've never seen this before, its very odd.

**Comment by LizethRegules** [comment]
<img width="769" alt="coeissue3" src="https://user-images.githubusercontent.com/100951593/156804323-ceb92f80-ef7d-4cb4-b87c-842de7701980.png">

**Comment by Jenefer-Monroe** [comment]
ok that's why, the name isn't matching. 
Do you have a second instance of Core Components listed? Or is that the full list of solutions? 
Is there an option like "Apply Upgrade" in the elipses for your Core solution?

**Comment by LizethRegules** [comment]
That is the only core components solution I have. Apply upgrade is grayed out
![image](https://user-images.githubusercontent.com/100951593/156806522-71241138-3cc2-44ee-a9f9-4bd901dc6611.png)

**Comment by Jenefer-Monroe** [comment]
I'm afraid that I dont know how you got into this state. The only thing I can think to try is to just install again. 
The tables and flows and such are all the same so they should do an upgrade even though the solution itself isn't considered an upgrade. 
And then hopefully you can delete this one titled _Unmanaged once that completes.
