### ISSUE TITLE
[ALM Accelerator - Feature]: Call export pipeline from the "based on" branch 

### ISSUE THREAD

**Issue by mdpc-nnit** [microsoft/coe-starter-kit#2173]
### Is your feature request related to a problem? Please describe.

I am unsure how much this is intended, but the [export pipeline](https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/export-solution-to-git.yml) is always run from the default branch when called from .

### Describe the solution you'd like

I would like it to run from whatever branch we chose to base the commit on, since this would allow more flexibility.

### Additional context?

This is somewhat related to issue #1152 in the lines of making the export pipeline more flexible

**Comment by mdpc-nnit** [comment]
I have a semi-related question:
Is it feasible to convert the export pipeline variables to parameters? I suppose you chose variables since that is what the built-in actions in power automate support? 

Adding parameters would make it more convenient to run the pipeline directly from ADO, which would be nice for troubleshooting

**Comment by mikefactorial** [comment]
@mdpc-nnit can you elaborate on this a little as to the flexibility this would provide and what you mean by "is always run from the default branch"? The export pipeline generally lives in the template repo rather than with the source controlled solutions so I don't follow the solution unless your setup is different and I'm missing the context.

I'm opening a new issue for your related question to investigate based on my comment in #2176 to ensure we're tracking that separately.

**Comment by mikefactorial** [comment]
Issue for using parameters over variables #2177

**Comment by mdpc-nnit** [comment]
Oh, I see the confusion. In fact, it seems that my issue is more fundamental: I want to run the export pipeline from the solution repo (this is also my motivation for #1152), and, in fact, this is what I do in our setup.

So what I really would like is to be able to test out changes to the export pipeline without breaking all exports. This could be easily done if the export pipeline were located in the solution repo and the export solution button in the app ran the pipeline from whatever source branch was indicated at run time.

Here is some context about our setup, because in fact we are not using it entirely as intended: 
Back when we converted from multistage pipelines to separate pipelines, I discovered that you could create export-to-git-[solutionName] pipelines to make a solution specific pipeline. I needed that since the transition to the new pipelines was gradual, but then I came to like it and we never went away from it, exactly because it satisfied the above need of being able to test changes.

Have you considered making solution specific export pipelines the norm instead of a hidden feature? (Or will you remove this eventually in the app :fearful:). I don't mind having just one export pipeline; they are all pointing at the same template anyway, but it is surely handy when troubleshooting.

**Comment by mikefactorial** [comment]
@mdpc-nnit we don't have any intentions of removing solution specific export pipelines. In fact we use them internally for the CoE Starter Kit, so good find, even though it's undocumented. For testing the export pipelines from a branch you could just update the branch in the pipeline itself under triggers -> YAML -> Get sources

![image](https://user-images.githubusercontent.com/42348035/157453674-86e182d1-4198-43dc-986a-d44b94c6d917.png)

**Comment by mdpc-nnit** [comment]
Thanks for the tip! Didn't think about that. I would still suggest that export/import/delete pipelines are created in the solution repo, at least to cover the case where multiple separate teams use the same app/pipeline templates from different ADO projects to avoid that a central pipeline has access to all repos.

(One might object that such a setup should use separate apps and templates. I am not sure what my stand is on this. All I know is that we are talking about centralizing it in a rather big organization, so we will most probably have multiple projects using the setup.)

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here.
