### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to review D4T envt business justifications in Core for Teams. 

### ISSUE THREAD

**Issue by ashmsport** [microsoft/coe-starter-kit#2175]
### What is your question?

We are using CoE starter kit in Teams. All the components like Core component for Teams, Governance and Nurture were imported to a Dataverse for Teams environment and have been running fine. As an admin I'm trying to review business justification process for Dataverse Environments which starts with 'Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created' flow. As per the [documentation ](https://docs.microsoft.com/en-us/power-platform/guidance/coe/teams-governance#business-justification-process) the review must be done in Power Platform Admin View model-driven app which is only available in CenterofExcellenceCoreComponents_3_31_managed.zip. When I try to import it  into the same Dataverse for Teams environment it fails with the error: Solution 
"CenterofExcellenceCoreComponents_3_31_managed.zip" failed to import: Entity admin_app cannot be processed because it includes property HasRelatedNotes which has a dependency on an unsupported entity Annotation in your organization.
Is there any other way of reviewing their justifications or what can be done to work around this issue?
![image](https://user-images.githubusercontent.com/33230123/156800088-bf141f2d-1187-4643-8b44-4b844693f573.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Power Platform Admin View model-driven app

**Comment by Jenefer-Monroe** [comment]
It is expected that you cannot install that solution into Teams. It (Core) is a different solution that the one you have (Core for Teams) because we had to remove features that arent supported in Dataverse for TEams.

**Comment by manuelap-msft** [comment]
We have two versions of Core - Core and Core for Teams, due to product limitations of what Dataverse for Teams supports (see https://docs.microsoft.com/en-us/powerapps/teams/data-platform-compare). Things like model driven apps and business process flows are not available in teams environments, in the product, so this is therefore not something we can use in the CoE Starter Kit.

There is a lightweight Power Platform Admin View canvas app which we've built for Teams,  that supports reviewing the compliance details but does not have the business process flow.

**Comment by Jenefer-Monroe** [comment]
That will not work, you need to have your inventory and processes in one place. We do not have a story for managing a CoE across D4T and Prod environments. 
You will need to, instead, use the Canvas App that Manuela mentions. 

![image](https://user-images.githubusercontent.com/89584709/156805160-98a4a2ba-3de9-4392-b07c-a962c3c598be.png)
![image](https://user-images.githubusercontent.com/89584709/156805410-929004f9-fc99-465d-a6c9-3d137ad7db86.png)

**Comment by ashmsport** [comment]
What I was thinking of doing was to disable all three Teams Admin flows in current setup (within Teams Governance component) and enabling them in Production environment. This way the justification flow will capture justification in the Prod environment and I'll be able to review them in the model app and take action. Do you think it'll work?
![image](https://user-images.githubusercontent.com/33230123/156806863-a98d5fd9-18a6-452e-b2b1-a237c09cb711.png)

**Comment by Jenefer-Monroe** [comment]
I'm afraid we have not explored any dual-install solutions, so I cannot really offer advice. 
Dual install may create complexity and confusion that is difficult to manage, but you are of course welcome to try it. It's a **_starter kit_**, for you to take and run with! :)
'

**Comment by ashmsport** [comment]
Quick update. I've setup all CoE components separately in Prod environment and turned off everything except D4T Flows. Seems to be working fine.

**Comment by Jenefer-Monroe** [comment]
Wonderful, thanks for letting us know. 
Closing out.
