### ISSUE TITLE
[ALM Accelerator - Feature]: Making it easier to use an app registration per environment

### ISSUE THREAD

**Issue by mdpc-nnit** [microsoft/coe-starter-kit#2176]
### Is your feature request related to a problem? Please describe.

The [update-deployment-settings.yml](https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/update-deployment-settings.yml) script uses the variable $(CdsBaseConnectionString) twice on line [45](https://github.com/microsoft/coe-alm-accelerator-templates/blob/fca8675e924d8b0312ff6be8c321a060153706d7/Pipelines/Templates/update-deployment-settings.yml#L45) and line [240](https://github.com/microsoft/coe-alm-accelerator-templates/blob/fca8675e924d8b0312ff6be8c321a060153706d7/Pipelines/Templates/update-deployment-settings.yml#L240) to connect to two different environments; the dev environment and the environment where the Accelerator app is installed. These environments need not be the same, and if the app registrations used the different environments differ, the pipeline will not function as intended.

The deployment pipelines also use the $(CdsBaseConnectionString) variable, but there we circumvent the problem by using different variable groups for the different environments. Here, when it is in the same pipeline (and even same task), it is a bit more tricky with the current setup.

### Describe the solution you'd like

I would like to be able to have separate app registrations for each environment, including the ALM Accelerator app's environment. However, adding a separate variable for the Accelerator app environment will add some complexity, so maybe there are alternatives?

### Describe alternatives you've considered

I was wondering whether the generate deployment settings could be done without contacting the dev environment, maybe by simply traversing the solution files. But it does not solve the problem at its core, since the $(CdsBaseConnectionString) will still be used differently across different pipelines.

### Additional context?

Has some relation to the discussion I opened [here](https://github.com/microsoft/coe-starter-kit/discussions/2169)

**Comment by mikefactorial** [comment]
Thanks for submitting this @mdpc-nnit agreed this is inflexible as it is currently. We have a couple other issue in the backlog related to service connections in general that would be a good opportunity for us to potentially address this. So, thanks for bringing it to our attention #1086 #716

I also agree with you that contacting the ALM Accelerator environment is not ideal. As some background our original intention was to simply push the saved configuration data on export from the ALM Accelerator environment. Unfortunately, we ran into an environment variable max length issue (e.g. we hit the windows environment variable max length). Possibly another reason to investigate moving away from variables as you suggested in #2173

**Comment by mikefactorial** [comment]
This needs to be addressed as part of the issues referenced above.
