### ISSUE TITLE
[CoE Starter Kit - BUG] Production_CoEDashboard_Jan2022 now fails to refresh

### ISSUE THREAD

**Issue by JMG74** [microsoft/coe-starter-kit#2178]
### Describe the issue

From 06-MAR-2022, the Power BI report "Production_CoEDashboard_Jan2022" fails to refresh its dataset with following error:
Failure details: The feed's metadata document appears to be invalid. Error: The type Microsoft.Dynamics.CRM.systemuser has conflicting definitions for the property teams_chat_activity_record.

Technical info:
Cluster Name:        WABI-EUROPE-NORTH-B-redirect.analysis.windows.net
Refresh Start Time: March 6, 2022 3:01 UTC
Refresh End Time:   March 6, 2022 3:14 UTC

### Expected Behavior

No error should occur during dataset refresh.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Production_CoEDashboard_Jan2022.pbit

### Steps To Reproduce

The Power BI report "Production_CoEDashboard_Jan2022.pbit" was installed according to installation instructions.
This report was refreshing correctly until march, 6th. From this date, I'm getting the same error when the data set is being refreshed.

**Comment by manuelap-msft** [comment]
Hello,

if this worked until now, and you didn't make any changes to the dashboard, the dataverse tables or the refresh schedule then I believe this is a product bug with Power BI and I would ask you to raise a support ticket for this: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support

Thank you
Manuela
