### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Sync Flow Errors) fail to turn on due to associated child flow not published by default

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#2182]
### Describe the issue

Admin | Sync Template v3 (Sync Flow Errors) - running successfully with previous version(3.16 Feb Version)
but with new version (3.34 March) this flow fail to Turn On

<img width="524" alt="CoE Sync" src="https://user-images.githubusercontent.com/30046543/157057117-566afe0e-30dd-45e0-b9ba-04514bfae5f6.PNG">

Child Flow Failing to run : Issue:  -Child flow not published yet

<img width="388" alt="CoEIssue2" src="https://user-images.githubusercontent.com/30046543/157057969-e0be0975-dd1e-4c5a-9da4-3987e98d7bc1.PNG">

Please let me know the flow name so I can published, its not clear to me by looking the Flow ID

### Expected Behavior

Flow should turn on

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Sync Flow Errors)

### Steps To Reproduce

Try to turn on the flow then you will see the issue

**Comment by Jenefer-Monroe** [comment]
Hello, each time you upgrade you need to ensure that all flows for that solution area are turned on. 
For [inventory](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components), you need to make sure you

1) Turn on [child flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-child-flows)
1) Turn on [setup flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-setup-flows)
1) Turn on [inventory flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows)

It sounds like you do not have the Send Email helper turned on
![image](https://user-images.githubusercontent.com/89584709/157060742-8aa1644f-457d-4a99-bbe7-26f12933878a.png)

**Comment by sharmajitendralal** [comment]
Thanks for your support issue has been resolved
