### ISSUE TITLE
[CoE Starter Kit - BUG] Solution Upgrade from version 2.x to current version failed

### ISSUE THREAD

**Issue by declawson** [microsoft/coe-starter-kit#2184]
### Describe the issue

Early December I went to 'Upgrade' the version of the Center of Excellence - Core Components from 2.? to 3.19 and got the following error:
Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 11All of the dependencies were Object Type 'Connection Reference' but when I went to remove the connections there were Canvas Apps/Cloud Flows dependent on the connections so I was in what seemed like an infinite loop of dependencies. And since the solution was a Managed Solution I wasn't looking to have to copy each and every component of the managed solution to an unmanaged solution or remove all the dependencies just so I could clean up.Once I gave up on trying to remove the dependencies so I could delete the older version of the solution I noticed I now had 2 versions of the Center of Excellence - Core Components. One with version 2.? and with 3.19.I found an article that suggested if 'Upgrade' failed to try 'Update' instead which I did. I now have two version 3.19 Core Components in the same environment.I am pretty new to the Power Platform and have a particular focus on its administration right now. So far I have installed several of the COE - Starter Kit components, including Core Components, Governance Components, Audit Logs, and the ALM Accelerator for Makers.I can't imagine that every time I upgrade each of these components to the latest version the process is so cumbersome, reconfiguring URLs etc., and that the end result is multiple instances of each solution.What can I do to maintain the COE Solutions?

### Expected Behavior

Be able to upgrade the COE solutions to the latest versions without any error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Admin Sync v3 Desktop Flow Runs

### Steps To Reproduce

Power Platform COE
Import> Advanced Options - Upgrade

### Anything else?

I know have duplicates of the desktop sync flow and I had to manually delete the Upgrade Core solution because the previous version did not install.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
