### ISSUE TITLE
Power BI embedded app for App Detail says: "Sorry, we didn't find this app"

### ISSUE THREAD

**Issue by raphaeltremblay1966** [microsoft/coe-starter-kit#2186]
Power BI embedded app for App Detail says: "Sorry, we didn't find this app"

![image](https://user-images.githubusercontent.com/99994964/157161359-239af7db-cf6d-40f6-b06b-8599ad132c89.png)

If I try to recreate it from the Power Apps for Power BI visual, chosing back Admin_Appid and Admin_Environmentid, Then when I choose the Environment where the "Admin - Access this App" app has been imported, it cannot find no app (No app to display).

![image](https://user-images.githubusercontent.com/99994964/157161807-4bb35da3-6218-482d-8438-7ee26859a18c.png)
![image](https://user-images.githubusercontent.com/99994964/157161869-783dd6ff-8b00-48e0-b90a-478c3e52c42e.png)

I can however access the App from the solution

![image](https://user-images.githubusercontent.com/99994964/157161996-c704c5a8-1f9d-440c-baef-07c045bb10f8.png)

**Comment by manuelap-msft** [comment]
Please make sure you're signed in with the correct user in Power BI and that the app is also shared with that user. E.g. if you are a Power Platform admin, you may be able to access the app from the solution but to embed it in Power BI it has to be shared with that user.

**Comment by manuelap-msft** [comment]
Following up here to check if you were able to address this and we can close the issue?

**Comment by raphaeltremblay1966** [comment]
It worked ! Thanks !
