### ISSUE TITLE
[CoE Starter Kit - BUG] - Action "Post an Adaptive Card to a Teams user and wait for a response" not loaded

### ISSUE THREAD

**Issue by dknamo** [microsoft/coe-starter-kit#2188]
### Describe the issue

Hi
I have made and run a flow ("Admin | Compliance detail request (get using Teams)" for over a year and the flow sends an adaptive card to users where those users must complete the risk assessment and business impact for all your published apps and flows in teams and it worked fine but it failed all of a sudden.
![image](https://user-images.githubusercontent.com/72252442/157259749-6ce48ad2-7925-425f-a9df-002a3cd49b85.png)

![image](https://user-images.githubusercontent.com/72252442/157259849-75d4b007-d684-4690-9d90-c103afe5591a.png)

I can no longer find that action under Teams Actions.
![image](https://user-images.githubusercontent.com/72252442/157260006-b610d97c-61d9-4d3a-8a55-b137398be45c.png)

The flow runs with an admin account and the account has a premium license.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

Admin | Compliance detail request v3

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid we are not staffed to assist with customized starter kits. However, I do see the action you want listed
![image](https://user-images.githubusercontent.com/89584709/157262450-91fd0be9-601a-49d1-8d6a-a28f7ee2f807.png)

Sorry we cannot be of more assistance.

**Comment by manuelap-msft** [comment]
It looks like the action you were using before is now deprecated:
https://docs.microsoft.com/en-us/connectors/teams/#post-an-adaptive-card-to-a-teams-user-and-wait-for-a-response-[deprecated]

and has been replaced with this action:
https://docs.microsoft.com/en-us/connectors/teams/#post-adaptive-card-in-a-chat-or-channel

You will have to update your flow to use the new action.

**Comment by manuelap-msft** [comment]
Closing out as thre's no further action from the CoE kit team.
