### ISSUE TITLE
Issue with opening Teams_CoEDashboard_jan2022_v2

### ISSUE THREAD

**Issue by antonioscordo** [microsoft/coe-starter-kit#2191]
Hi,

I have an issue with opening Teams_CoEDashboard_jan2022_v2...

When I try and import Dashboard in-to Power-bi desktop, it tries to load for 5-10 minutes then fails, the errors I get are as follows:
OrgUrl: 
Loading blocked by failures with other queries.

Environment:
Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server.The server was not found or was not accessible. Verify that the instance name is correct and that........................

etc....

I have tried following the troubleshooting document link below but I've been unsuccessful in getting this to work.
Link:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard?WT.mc_id=BA-MVP-5000177

Is there anything you can advise or is there any logging I can turn on ?

Any help appreciated.
Antonio

**Comment by manuelap-msft** [comment]
If you are using the Teams_ dashboard
1. Make sure you enter the OrgURL in this format org31234.crm.dynamics.com **without** the https:// in the beginning and trailing / at the end
2. Make sure the TDS endpoint is enabled on this enviornment https://docs.microsoft.com/en-us/power-platform/admin/settings-features
3. Check the troubleshooting guide here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting

If you have done all that and it's still not successfull, you may have a network configuration that doesn't allow Power BI to connect to Dataverse. Here's some suggestions for network related issues: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#blocked-ports Unfortunately we're not Power BI Experts so may not be able to help further and you may need to raise a Microsoft Support ticket if you continue to be blocked here, as a Power BI support engineer should be able to trace what network configuration is causing the issue.

**Comment by manuelap-msft** [comment]
Following up to check if you resolved this and we can close the issue now?

**Comment by antonioscordo** [comment]
Hi,

Thanks for you help with this.
This call can be closed.

Many Thanks
Antonio
