### ISSUE TITLE
Dataverse Table Customized Email has no rows After Upgrade

### ISSUE THREAD

**Issue by mzd4fz00** [microsoft/coe-starter-kit#2192]
Hello, hoping you can provide some ideas of what we should do next.  

Our Customized Email Dataverse table has no rows, so workflows like the “Admin|Capacity Alerts” workflow fail when trying to retrieve a row from that empty table.  We realize if that table is missing data that some other tables might be as well for whatever caused the anomaly.

Are there some recommended "repair" actions you think we should take at this time?

The issue began in early January (likely Jan 4 2022) when we did an upgrade for the following solutions:
CenterofExcellenceAuditLogs from 2.5 to 2.6
CenterofExcellenceAuditComponents from 2.6 to 2.9
CenerofExcellenceCoreComponents from 3.13 to 3.19 

Actions that try to do a Get Items from that table fail since that table has no rows of data.  

Today 3/8/2022 we did another upgrade to the following versions but this did not resolve the issue:
CenterofExcellenceAuditComponents to 2.9 to 2.13
CenerofExcellenceCoreComponents to 3.19 to 3.34

Example of error we see in the “Get a row by ID” action:
admin_customizedemail With Id = fc8a4d58-7d41-ec11-8c62-00224829bf00 Does Not Exist

Thanks in advance for any thoughts

**Comment by manuelap-msft** [comment]
You likely forgot to run our mandatory setup flows, as explained in the documentation: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows

![image](https://user-images.githubusercontent.com/55705669/157399854-f9962db8-9d7f-460a-986e-db2ae2960e0f.png)

On every upgrade, please make sure you revisit the docs setup instructions to check if there's anything new to do.

For this specific change, the action needed to do was also called out in our release notes:
![image](https://user-images.githubusercontent.com/55705669/157400026-2e1501ee-4621-4ede-a49f-045833635bc7.png)

If you haven't already, I would recommend subscribing to our release notes (explained here https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup#installing-upgrades) so you get information like this before you upgrade.

**Comment by mzd4fz00** [comment]
Thank you for the quick insights!  I believe that feedback resolved our issue (where we had not run the Admin | Sync Template v3 Configure Emails setup workflow).  Thank you!
