### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION: Unable to assign user as new app owner from Model Driven App

### ISSUE THREAD

**Issue by JamesMcWhinney42** [microsoft/coe-starter-kit#2193]
### What is your question?

I received an email from the COE ("Orphaned Power Platform objects without managers") stating that there is an orphaned app.

When I go into the "Power Platform Admin View" app and open the app in question, then click the "Assign" button and choose the correct user, I get the below error message:

"Access to Microsoft Dynamics 365 has not yet been fully configured for this user. The user needs at least one security role before you can continue."

### What solution are you experiencing the issue with?

Governance

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by JamesMcWhinney42** [comment]
I gave the user the security role "Service Reader" and "Basic User" (against the COE environment) and this seemed to get rid of the error message.  Not sure if that is the right set of security roles for a maker.
The app still doesn't show the revised owner name.

**Comment by manuelap-msft** [comment]
Hello,

are you saying you are using the Assign button in the top navigation of the model driven app?
![image](https://user-images.githubusercontent.com/55705669/157400617-9661cef5-cd4b-49bf-bc57-4b50fb3eace8.png)

If so, that assigns record ownership but not ownership of the application. You will have to use either the Set App Permissions canvas app, or the app embedded in the Power BI dashboard to re-assign ownership.

**Comment by manuelap-msft** [comment]
The CoE Starter Kit stores meta-data of your inventory (like app name, app owner, connectors an app uses) in Dataverse tables, each app is a record/row in the table. The model driven app displays those records in views and forms. Those records are not linked to the actual artefacts in your inventory. You can read more about security constructs of Dataverse here: https://docs.microsoft.com/en-us/power-platform/admin/wp-security-cds

**Comment by JamesMcWhinney42** [comment]
Thanks, I found the "Set App Permissions" and "Set Flow Permissions" apps in the "Center of Excellence – Core Components" solution and was able to update ownership.
