### ISSUE TITLE
[CoE Starter Kit - BUG] Template Catalog error on file download

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2196]
### Describe the issue

Hello,
I've installed the latest version of Nurture Component on my environment and when i try to download file (apps, flow, image, document...) from Template Catalog it show up the attached error.. This error show up on different installation, in different tenant.
Can you help me?

Thanks a lot

<img width="879" alt="error-blob" src="https://user-images.githubusercontent.com/101250592/157410362-07584eff-de81-42d7-a8d3-05033a3c3f86.png">

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Template Catalog

### Steps To Reproduce

1. Add record on Dataverse table
2. Add file on the previews record
3. Try to save the document from Tamplate Catalog app

**Comment by Jenefer-Monroe** [comment]
thank you for posting, we missed setting this property as it selected the wrong thing by default
![image](https://user-images.githubusercontent.com/89584709/157465574-7a164d8e-4e53-4aa5-bca3-7a6d4db55de7.png)

local fixed for April

**Comment by Jenefer-Monroe** [comment]
Wonderful news! I'll re-open if you dont mind so we can use this to track the fix getting released in April.
