### ISSUE TITLE
Not able to see any data in the App Usage

### ISSUE THREAD

**Issue by SESA377903** [microsoft/coe-starter-kit#2197]
### Describe the issue

Hi Team,
We have recently installed (a week back) March 2022 version and I am not able to see any data in the App Usage area.
Could you please help us?
<img width="905" alt="image" src="https://user-images.githubusercontent.com/91530382/157411139-c8c7d2c4-ff6a-42f6-a6b6-0cfac3f572cc.png">

Thanks
Siva

### Expected Behavior

We should see the app usage across tenant.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

March 2022

### What app or flow are you having the issue with?

Admin- sync template v3

**Comment by manuelap-msft** [comment]
Have you completed the steps to set up the Audit Log custom connector, and the flows in the Audit Log solution are running successfully? https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

**Comment by NPrice99** [comment]
Hi @manuelap-msft I have also suddenly got a problem I can see the PowerApps entries in compliance.microsoft.com but not on portal.azure.com / Audit which is where the custom connector gets the entries from.
Regards
Nigel

**Comment by manuelap-msft** [comment]
Hi @NPrice99, if you can't see the entries in the portal the custom connector gets the info from that seems to Product issue and I'd recommend raising a ticket for that!

**Comment by NPrice99** [comment]
HI @manuelap-msft I think I have found the problem.  Its in the setup documentation for the connector - "Start a subscription to audit log content".  It sets the contentType to Audit.General this does not bring back any data.  However, if you set contentType to Created app and Launched app you gets of stuff back.

**Comment by manuelap-msft** [comment]
We set the content type based on this documentation: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference#working-with-the-office-365-management-activity-api

![image](https://user-images.githubusercontent.com/55705669/157891718-63ed0ef2-e255-4a6c-a246-25076b7aa3fb.png)

In our tenant, it's still working with Audit.General but we'll see if other people report similar issues.

**Comment by manuelap-msft** [comment]
Can you share a screenshot of what your configuration looks like please? We've not managed before to only return launched app events and that would be helpful to do as Audit.General returns a lot of noise we have to filter out.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action from the starter kit team
