### ISSUE TITLE
[ALM Accelerator - BUG]: Custom Connector, GetOrganizations unable to resolve

### ISSUE THREAD

**Issue by KeithHR** [microsoft/coe-starter-kit#2202]
### Describe the issue

In azure devops custom connector I cannot seem to get the body to resolve in any of the API calls. I get this error below with a status code of 203. The app also does not let me select my organization.

![image](https://user-images.githubusercontent.com/54408560/157471200-f19e6fbe-994d-47ce-be67-5195f31bea76.png)

![image](https://user-images.githubusercontent.com/54408560/157471681-730f4b94-1d18-4159-beb2-c5ed9efe1d85.png)

### Expected Behavior

response body should return appropriate data and app lets me select organization

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20211001.1

### Steps To Reproduce

Used install steps and didn't do anything other than in the steps. Behavior shows up after testing once configuring.

**Comment by mikefactorial** [comment]
@KeithHR looks like you'll need to reset the security in the custom azure devops connector. Instructions are here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#configure-the-devops-custom-connector

**Comment by KeithHR** [comment]
Thanks @mikefactorial. I redid the security and updated the connector but there was no change. Any other ideas??

**Comment by mikefactorial** [comment]
@KeithHR this specific error is always an issue with authentication to Azure DevOps from the custom connector. Any specifics you can share about your custom connector security setup or your Azure DevOps environment may help to track down the specific issue.

**Comment by mikefactorial** [comment]
Feel free to share with me v-mikeochs at microsoft dot com if you don't want to share here.

**Comment by KeithHR** [comment]
I have similar values for those required fields however I do notice that values always disappear when I update connector. Is this common?

![image](https://user-images.githubusercontent.com/54408560/157519823-73962ec7-e84d-49d0-a56a-bcf4fc8bd8b0.png)

**Comment by mikefactorial** [comment]
@KeithHR it is expected that the values will disappear after saving. Is your Azure DevOps instance in the same tenant as Power Apps? If not, we don't currently support cross tenant connections which could be a problem.

**Comment by KeithHR** [comment]
@mikefactorial Yep in the same tenant. Initially this was setup by someone who is no longer with company. It looks like it did work at some point so not sure what happened but when I took over I noticed this behavior. Since I wasn't the user to initially set this up are there additional permissions I would need in regards to ADO?

**Comment by mikefactorial** [comment]
@KeithHR you need to have at least a Basic User license in Azure Devops and you may want to run the following for your user https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/personas#alm-maker-add

![image](https://user-images.githubusercontent.com/42348035/157752659-a4614a87-c76d-4aa8-b583-d745b7b5d2cc.png)

**Comment by kallisto08** [comment]
@Keith
I have found this to be a bit hit and miss, but the best way I can describe it is look under your menu on the left.. Dataverse\Connections.. the CustomAzureDevOps connector should have your logon against it. If it doesnt then found it best to delete the connection. Uninstall the ALM Accelerator and reinstall.

Before running up the ALM Accelerator after the re-install...
1. Go to the left menu.. Dataverse\Custom Connectors and click edit on the CustomAzureDevOps 
2. Go straight to the Security Tab and Click Edit..
3. Add your ClientId, Client Secret & ResourceUrl 
4. Go straight to Test Tab and Click New Connection
5. This should get you to auth and then closes
6. Go back into the Custom Connectors.. and go to the Test tab. If the selected connector doesnt have your logon then go back and delete the connector. then do the following:
7. Back into Edit the CustomAzureDevOps .. Add your details from step 3
8. Then click Update Connector.
9. Follow steps 1 to 5.. should work.

Once the connector shows your logon you can go into Edit CustomAzureDevOps, Go straight to Test and see your connection at the top.. then hit Test and you will see your organsiation data. If not, it will show the same test you reported above and is not worth firing up the ALM app until this is sorted. 

Hope this helps

**Comment by mikefactorial** [comment]
Thanks for posting these steps @kallisto08. We've been looking at adding support to the coe-cli and / or the app itself to make upgrades easier, but your steps for fixing the custom connector is spot on. Thanks again.

**Comment by KeithHR** [comment]
@kallisto08 I will try this. thank you!

**Comment by mikefactorial** [comment]
@KeithHR can you verify if updating the security on the custom connector resolved your issue?

**Comment by KeithHR** [comment]
@mikefactorial that did it. thank you both for the help!

**Comment by mknalves** [comment]
Hi everyone! 
I've got the same problem. I've tried the steps suggested by [kallisto08](https://github.com/kallisto08) but no success. Any other suggestion to fix it?
