### ISSUE TITLE
[CoE Starter Kit - BUG] Can not archive Canvas App

### ISSUE THREAD

**Issue by Skhzada** [microsoft/coe-starter-kit#2203]
### Describe the issue

Not been able to export Canvas app through archival process, when trying to exporting the package these are the errors I come up with "does not have permission for connection '009b2166-2302-47b5-88a3-87494f5b6926' under Api 'shared_logicflows'." and "Could not find flow '8f17eaba-ea67-4a63-90bb-b1aa6d0853c8'". Or one that doesn't have an 'Export' button 

### What solution are you experiencing the issue with?

Innovation Backlog

### What solution version are you using?

Office 365 F3

### What app or flow are you having the issue with?

Canvas

### Anything else?

<img width="860" alt="Screenshot 2022-01-11 095939" src="https://user-images.githubusercontent.com/101274642/157475292-7aec7f70-1745-4f7f-becc-9b5b61099b3c.png">
<img width="362" alt="Screenshot 2022-03-04 132056" src="https://user-images.githubusercontent.com/101274642/157475475-26baf588-6dc3-4bab-b6ac-165e4e90019b.png">

**Comment by Jenefer-Monroe** [comment]
Hello, I'm having a little trouble following you, but it sounds like you are using the Archival flows from the Governance solution, and you are on a version of Governance that still uploaded copies of apps and flows to Sharepoint. 

Is that accurate?

**Comment by Skhzada** [comment]
Yes, that's right

**Comment by Skhzada** [comment]
Right ok, would you know where I could find some information to deal with this or am I asking in the wrong place (apologies if so). Thanks

**Comment by Jenefer-Monroe** [comment]
As far as the starter kit goes, this is just no longer supported, and the [latest versions](https://aka.ms/coestarterkitdownload) no longer have this functionality. 

And unfortunately given the age of your install, [upgrade](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades) will not work smoothly.  We recommend upgrading the starter kit at least quarterly.

Sorry I cant be of more help.

**Comment by Skhzada** [comment]
Thank you anyways
