### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Command Center - Coe Flows List Empty

### ISSUE THREAD

**Issue by rooobeert** [microsoft/coe-starter-kit#2206]
### Describe the issue

Hi, 

one of our customers just finished setting up all the components. For the installation service user and all admin with the Power Platform Admin SR assigned, can open the Command Center, but don´t see any Flows listed in the Flows state screen. 

Whats missing?

![image](https://user-images.githubusercontent.com/87785803/157489650-7c54c583-4d18-49f7-9db5-fdf7449ccb7c.png)

EDIT: Sometimes an error message will show. 
![image](https://user-images.githubusercontent.com/87785803/157491540-8a1fdc30-a92f-48a5-b8f2-23f4a70bfac5.png)

The flow also doesnt´t excutes with all the request that should be there, as soon as you cklick on the butto in the command center app. 
Should it go true or false in the flow?
![image](https://user-images.githubusercontent.com/87785803/157490196-ea398804-69d2-43a1-bc71-f77f8770cc81.png)

### Expected Behavior

All CoE Flows should be listed. See whats turned off or on. Configure Button.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by Jenefer-Monroe** [comment]
Loading the page calls the helper twice, first with the true flag, then false

```
ClearCollect(CurrentCoEFlows, 'CommandCenterApp>GetCoEFlows'.Run(CoE_Envt, true));
Collect(CurrentCoEFlows, 'CommandCenterApp>GetCoEFlows'.Run(CoE_Envt, false));
```

**Comment by Jenefer-Monroe** [comment]
Can you please collect some information for me to assist? 

1) Go to that Core > Cloud Flows, and show me what is listed for the flows in Core
![image](https://user-images.githubusercontent.com/89584709/157546166-eb122b0c-30c8-42c6-a441-40e1babe2ff7.png)

2) Go to the flow in question (Command Center App > Get CoE Flows) find the failure and show me where the flow is failing

**Comment by rooobeert** [comment]
I will have to reach out for the customer, it might take a day or two.

**Comment by Jenefer-Monroe** [comment]
Hello, checking in here to see about this needed debugging information

**Comment by rooobeert** [comment]
Hi! Sorry, the customer seems to be on vacation right now. I will be able to give feedback until next Friday. 
Thanks for waiting!

**Comment by rooobeert** [comment]
The Flow failes here: 
![image](https://user-images.githubusercontent.com/87785803/159457663-302d4305-824e-4648-9668-a8f38447e7b8.png)

**Comment by Jenefer-Monroe** [comment]
Do they also get failures in the sync flow run for (flows)? 
And if they create a standalone flow, as this service user, that calls this action for this environment, does it pass?

**Comment by rooobeert** [comment]
What do you mean by Sync Flow Run (Flows)? 
![image](https://user-images.githubusercontent.com/87785803/159671995-8d2fb25d-6c8f-4374-a4bf-192960b5731d.png)
This one?

**Comment by Jenefer-Monroe** [comment]
correct.

**Comment by Jenefer-Monroe** [comment]
Did you validate that the sync flow, and stand alone are using this connection? 
![image](https://user-images.githubusercontent.com/89584709/159935362-4f498376-525d-4051-a31b-68f9212244bb.png)

And can you please share a screenshot of the connection references in use
![image](https://user-images.githubusercontent.com/89584709/159936308-2baba538-fc92-4b0e-aaa5-a78743c2bf8f.png)

and the Run-only permissions
![image](https://user-images.githubusercontent.com/89584709/159936411-d8802f9e-9b7e-483f-9b5f-423a27d0881b.png)

**Comment by rooobeert** [comment]
We have the Connection References setup the way your pictures show. The run-only properties where configured both to "Use this connection..." with the Service User. We reconfigured the first connection used to "Provideed by run only user". 

Works perfectly fine now! Thanks!

**Comment by manuelap-msft** [comment]
Closing out as no further action required. Let us know if you have other issues with the kit! Thank you!
