### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to connect with Power BI Reports

### ISSUE THREAD

**Issue by lilmrsgowin** [microsoft/coe-starter-kit#2209]
### Describe the issue

When attempting to connect the Power BI reports to the orgurl, recieve this error: invalid_resource: AADSTS500011: The resource principal named http://org8f88d2d8.crm.dynamics.com was not found in the tenant named Microsoft. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: ec2e9a11-d22b-46a5-965e-364782463c00
Correlation ID: 49b05dc7-dea5-4a19-907a-273a584df0c4
Timestamp: 2022-03-09 21:24:20Z.

Unable to resolve. 

### Expected Behavior

Connect to the environment and publish reports. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Production_CoEDashboard_March2022

### What app or flow are you having the issue with?

Power BI Dashboard connection

### Steps To Reproduce

1. Open the Power BI template. enter the org url in the following format: org8f88d2d8.crm.dynamics.com
2. Click Load
3. When prompted, click Sign in and enter AAD credentials and password 
4. Error received, can proceed no further. 

Have attempted to review all of the articles referenced when googling this error and all refer to Azure Apps. I've verified both the command center and graph API application registrations are working. Also verified that TDS endpoint is enabled (by default). I can manually create a new Power BI report and connect to the environment using a normal Dataverse connection but cannot using the Common Data Service (Legacy) connection that is being used in this solution for this or any other environment. Is there a setting to disable this that should be updated?

**Comment by Jenefer-Monroe** [comment]
Hello. Couple of ideas: 

First, please see [Configure the Power BI dashboard](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard)

> 3. Enter the URL of your environment instance. If you are using the Teams_CoEDashboard_MMMYY.pbit, do not include the https:// prefix or / postfix for OrgUrl. **_If you are using the Production_CoEDashboard_MMMYY.pbit, include the https:// prefix for OrgUrl_**. If prompted, sign in to Power BI Desktop with your organization account that has access to the environment you installed the CoE Starter Kit in.

Secondly, are you logged in with the correct user identity? Either the identity that installed the starter kit, or one that you have granted sys admin to the envt? 

Lastly, please also let us know, are you installing CoE in a Production environment or a Dataverse for Teams Environment

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
