### ISSUE TITLE
[CoE Starter Kit - Feature]: Target user groups with compliance flows

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2213]
### Is your feature request related to a problem? Please describe.

Are there plans to make Compliance work in a manner that you could choose who gets the emails/requests? For instance, could we target a group of users for pilot? Right now it seems like an all or nothing and that is problematic in large orgs.

### Describe the solution you'd like

Target a group of users for a pilot

**Comment by Jenefer-Monroe** [comment]
oh I had misunderstood this question during office hours. I thought he was asking to target the communication. 
We can do this already by excluding envts, and the work to exclude individual objects i think would complete it.
