### ISSUE TITLE
[CoE Starter Kit - Feature]: Customized Emails is needed for Governance Solution

### ISSUE THREAD

**Issue by hernan-ramirez** [microsoft/coe-starter-kit#2216]
### Is your feature request related to a problem? Please describe.

Just as this feature is already available for the Core Solution, there is a need for emails to be configured for the Governance Solution as well.

### Describe the solution you'd like

I want to configure the communication in the emails that the governance flows send

**Comment by Jenefer-Monroe** [comment]
Hello, this is in our backlog. We have been waiting to ensure the systems involved work end to end. We use several child flows to accomplish and so want to make sure we are done getting feedback on them before moving to the next solution. 

Thanks for posting and for using CoE

**Comment by hernan-ramirez** [comment]
Excelent Jenefer. I'll be waiting for news!
