### ISSUE TITLE
[CoE Starter Kit - QUESTION] Security Group - Security Roles for Power Platform Admin View

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#2217]
### What is your question?

You advise to not have a security group for the CoE environment, however, if a group (Power Platform Makers) is assigned the Power Platform Makers SR role, this will automatically be given access to the Power Platform Admin View app. The role gives them Read, Write and Append privileges in the dataverse which we think is too much. As the only way to stop sharing the app is to remove the security role, but this has a knock on affect for sharing other apps to this group. Can you advise how we circumvent this?  

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Our recommendation here would be for you to create a new SR that better fits your specific needs and use it instead of the Maker SR as we cannot reduce the permissions of the SR for others. 

Hope that makes sense.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
