### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Center Stopped Working 3.22024.12

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#2218]
### Describe the issue

Since upgrading, the developer compliance center will not start. This has occurred in two separate environments.
![image](https://user-images.githubusercontent.com/17124284/157706403-d1136015-425c-49d6-b473-ab9d8430a2d3.png)

I have enabled monitor but there is no data appearing.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.13

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid I dont repro. Can you check
- are other apps opening in your tenant? that environment?
- can you open the app in edit mode? 
- can you please validate that the connections are functioning in the details page? 
![image](https://user-images.githubusercontent.com/89584709/157714539-160ceade-34ef-4d20-a8ff-9a9e4eadb090.png)

**Comment by Jenefer-Monroe** [comment]
So player works from the edit experience correct? Just if you play directly?

**Comment by medicineshow** [comment]
Yes, that is correct

**Comment by Jenefer-Monroe** [comment]
OK, I still dont repro, can you get your Power Apps version from another app? 

![image](https://user-images.githubusercontent.com/89584709/157728140-49a4868e-abc6-4f7a-9e49-d2685818473e.png)

**Comment by medicineshow** [comment]
Power Apps 3.22024.12

**Comment by Jenefer-Monroe** [comment]
Can you please check the other apps in the starter kit for us? While we investigate?

**Comment by Jenefer-Monroe** [comment]
It looks like that version of Power Apps isn't rolling out further. And I cannot even select it in my tenants as a result.

**Comment by medicineshow** [comment]
all other apps are running fine. How do we resolve the version? We did not even know you could do this.

**Comment by medicineshow** [comment]
The current authoring version is 3.22021.27
![image](https://user-images.githubusercontent.com/17124284/157863604-fa3ca348-14ac-4b1b-b50b-08880e2f5df6.png)

If is select to change version I see these versions. I pick the last one before recommended

![image](https://user-images.githubusercontent.com/17124284/157863752-d6f4f017-f243-498e-9313-530cadc96329.png)

![image](https://user-images.githubusercontent.com/17124284/157863689-9cd3867b-53a9-4c8b-ad06-c8033c29a2f9.png)

After saving and publishing, the app then works as expected, however now I have an unmanged solution layer which is not ideal

**Comment by Jenefer-Monroe** [comment]
I dont think we have a good answer for you here to get out of the situation, other than to remove the unmanaged layer when you upgrade. 

It appear that you got opted in to the early release for 2022 release wave 1. Can you check that? 
 [admin](https://admin.powerplatform.microsoft.com/) > Environments > select your environment > Updates
![image](https://user-images.githubusercontent.com/89584709/157872033-fee8eaf4-2079-4df5-a43b-a82b997cfd0c.png)

It looks like this will not auto-enroll you going forward in other early releases which is good. 
https://docs.microsoft.com/en-us/power-platform/admin/opt-in-early-access-updates#will-an-environment-that-previously-opted-in-for-the-early-access-updates-automatically-get-the-early-access-update-of-the-new-releases

**Comment by Jenefer-Monroe** [comment]
Support may be able to do something for you as well, to move you out of the early release wave, but you will need to contact them directly.

**Comment by medicineshow** [comment]
Looks like we have not.
![image](https://user-images.githubusercontent.com/17124284/157883587-a9ff2183-731f-4824-b88e-2709bc49f830.png)

**Comment by Jenefer-Monroe** [comment]
Interesting. Well you somehow got an early release that got halted. There may be other ways to enroll for that, or you may have just been an early adopter due to your region etc. 

I'm afraid we can't do much more here. Support may be able to revert you, but this is outside of the starter kit teams ability to assist.

**Comment by Jenefer-Monroe** [comment]
Player version per customers
- 3.22031.21 - does not work
- 3.22024.18 - works
- 3.22024.12 - does not work
- 3.22023.18 - works
- 3.22022.23 - does not work

**Comment by manuelap-msft** [comment]
Hello, we have confirmation from the Power Apps Player team that this got fixed now, and should be fixed for all regions with the versions that didn't work! Awaiting confirmation from some users who experienced the issue before closing this out.

**Comment by javiermga-inditex** [comment]
Hi @manuelap-msft,

It works with `Power Apps 3.22031.21`.

![AdminCommandCenter](https://user-images.githubusercontent.com/101564333/158781269-bb4e80ea-6faf-463b-9601-85d7360f0ea8.png)

Thank you!

**Comment by manuelap-msft** [comment]
Wonderful, thank you so much for confirming so quickly!

**Comment by medicineshow** [comment]
I can confirm that it appears to be working fine for me too. thanks.

**Comment by manuelap-msft** [comment]
Wonderful news, thanks for confirming so quickly! I'll close this issue for now but please let us know if you see any other issues :)
