### ISSUE TITLE
[CoE Starter Kit - BUG] Initialising flow approval tables fails 

### ISSUE THREAD

**Issue by pallvip** [microsoft/coe-starter-kit#2221]
### Describe the issue

I am deploying feb 2022 COE starter kit in my tenant. I have installed Core components Solution and Audit log solution. It is failing when I try to create approval flow before I can deploy the governance components. Following the steps specified here - 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov#initialize-flow-approval-tables-in-your-environment

Error message -
The approval flow Plugin Assemblies import: FAILURE. Error: Plugin: Microsoft.Dynamics.FlowApprovalsCore.Plugins, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 caused an exception.: Unable to load plug-in assembly.
![image](https://user-images.githubusercontent.com/40602120/157728138-ce7d1073-2650-4870-b077-9a403caf4a7e.png)

### Expected Behavior

The approval should be triggered and  approval solution should be created

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

approval 

### Steps To Reproduce

I am deploying feb 2022 COE starter kit in my tenant. I have installed Core components Solution and Audit log solution. It is failing when I try to create approval flow before I can deploy the governance components. Following the steps specified here - 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov#initialize-flow-approval-tables-in-your-environment

This is my second attempt and I have started from scratch with a brand new environment but getting the exactly same error. The approvers never receive the approval request either. 

### Anything else?

![image](https://user-images.githubusercontent.com/40602120/157726764-e507d5de-806a-4f14-978f-a0f3c959c535.png)

![image](https://user-images.githubusercontent.com/40602120/157728170-89011bd6-e4ba-4123-b342-e356fa06dbde.png)

**Comment by manuelap-msft** [comment]
Hello,

the Microsoft Flow Approvals solution itself is not part of the CoE Starter Kit, it's a Power Platform product capability that we in the kit just make use of. Learn more about Approvals here: https://docs.microsoft.com/en-us/power-automate/get-started-approvals

If this feature is not working for you, please raise a support ticket through your usual support channels:
https://docs.microsoft.com/en-us/power-platform/admin/get-help-support
