### ISSUE TITLE
Not able to see data in App Usage

### ISSUE THREAD

**Issue by SESA377903** [microsoft/coe-starter-kit#2222]
### Describe the issue

Not able to see data in App Usage in March 2022 CoE toolkit version.

### Expected Behavior

Data should be displayed for each app.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

March 2022

### What app or flow are you having the issue with?

Admin- sync template v3

<img width="765" alt="image" src="https://user-images.githubusercontent.com/91530382/157817662-8836e608-c396-407f-849c-ea7b419237fb.png">

**Comment by manuelap-msft** [comment]
Duplicate of #2197 - if you have any follow questions or comments, please post them in #2197 Thank you!

Closing as duplicate.
