### ISSUE TITLE
[CoE Starter Kit - QUESTION] There is detailed documentation on Power Platform Admin View?

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2224]
### What is your question?

Hello, I'm try to find a detailed documentation for a client. Is there a documentation that explains every single item of the Power Platform Admin View? For example the meaning of Business Justification, Admin Requirement - Risk Assessment State, ecc...

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by manuelap-msft** [comment]
Hello,

our documentation is here, for example https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#power-platform-admin-view and https://docs.microsoft.com/en-us/power-platform/guidance/coe/example-processes however please note that this is a **_starter_** kit. The way it is used, and how fields are interpreted by customers depends on the customers processes and scenarios. You may find that the customer wants to extend the fields or use different ones. We don't aim to provide a prescriptive description here as there's no one size fits all to governing the Power Platform, and many customers will have different requirements based on their processes, change and adoption management strategy.

Manuela
