### ISSUE TITLE
[CoE Starter Kit - Question] Flows failed to turn on after upgrade due to invalid connections

### ISSUE THREAD

**Issue by EmranCoE** [microsoft/coe-starter-kit#2228]
### Describe the issue

Hey ,

I have recently upgrade leatest version of CoE tools .
Several flows are unable to Turn On  those were working fine before .
Have gone through this document--
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows
All the Child flows are turned On

1.	HELPER – Send Email
2.	HELPER – Maker Check
3.	HELPER – CloudFlowOperations
4.	HELPER – CanvasAppOperations
5.	HELPER – ObjectOperations
6.	CLEANUP HELPER – Check Deleted (Canvas Apps)
7.	CLEANUP HELPER – Check Deleted (Cloud Flows)
8.	CLEANUP HELPER – Check Deleted (Custom Connectors)
9.	CLEANUP HELPER – Check Deleted (Model Driven Apps)
10.	CLEANUP HELPER – Check Deleted (PVA)
11.	CLEANUP HELPER – Power Apps User Shared With

Following flows are also Turned ON 

•	Admin | Add Maker to Group
•	Admin | Excuse Support Envts from Governance Flows
•	Admin | Sync Template v3 Configure Emails
•	Command Center App > Get M365 Service Messages
•	Command Center App > Initially Populate Bookmarks
•	Command Center App > Get CoE Flows
•	Command Center App > Set CoE Flows State
•	DLP Editor > Parse impacted resources into CSV
•	Admin | Sync Template v3 (Connectors)

But getting  error while trying to turn on or  go to Edit >> Save 

---Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowUnsupportedForInvokerConnections","message":"The workflow with id '5625768c-bd3d-ec11-8c63-00224829720b', name HELPER - Send Email cannot be used as a child workflow because child workflows only support embedded connections."}}".---

<img width="954" alt="Welcome-Email" src="https://user-images.githubusercontent.com/90054514/157926145-d719f08f-5acb-46bd-a957-6805cf594100.png">
<img width="956" alt="WelcomeV3 " src="https://user-images.githubusercontent.com/90054514/157926203-542a9ff7-8aed-4fdc-940a-86c1bb63beb8.png">
![WelcomeV3](https://user-images.githubusercontent.com/90054514/157926215-35b7eec3-8573-49fc-a4f6-3daaccffd8d7.png)
<img width="955" alt="App_Catalog" src="https://user-images.githubusercontent.com/90054514/157926238-db63f576-d161-4a34-bca3-facf0a484963.png">

Many Thanks 
Regards,
Emarn

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Admin | Welcome Email v3 .  Admin | Capacity Alerts .   Admin | Sync Template v3 (Sync Flow Errors). App Catalog > Request Access . Environment Requests Flows , Admin | Compliance detail request v3

**Comment by Jenefer-Monroe** [comment]
If you go to the flow **_HELPER - Send Email_**, does it show the connection refrence as healthy? 
And what does it show if you click edit on **_Run only users_**?

![image](https://user-images.githubusercontent.com/89584709/157931103-3a1f60ef-1fe9-40f1-97ad-e30df3639aa3.png)

**Comment by EmranCoE** [comment]
Hey Jenefer ! 

Thank you so much  for  immediate response as always !

HELPER - Send Email:
<img width="956" alt="Helper_" src="https://user-images.githubusercontent.com/90054514/157933235-c549b00d-bffd-4d93-8f24-ea62ee6cf021.png">

Edit on Run only users:

![Helper_1](https://user-images.githubusercontent.com/90054514/157933311-e94941a1-1516-4fd4-a26f-e8d1ed7e47cc.png)

Provided by run only user >> drop down my email id . was tried  changed and save

**Comment by EmranCoE** [comment]
Hey Jenefer ,

 After changed the connectors from dropdown (Provided by run only user ) >> save . I have able to Turn On all the flows except these two flows  : 

1. Env Request | Create Approved Environment

![Environment](https://user-images.githubusercontent.com/90054514/157950229-23865c5d-306d-4db0-a67c-e5580cb92977.png)

<img width="936" alt="Env-Req" src="https://user-images.githubusercontent.com/90054514/157950388-538e0653-d7b4-4450-bb62-f2af3e8990a2.png">

![Env](https://user-images.githubusercontent.com/90054514/157950409-84eb095c-6373-4dad-934f-3dc06dd8ba61.png)

2. App Catalog > Request Access

![App-Catalog](https://user-images.githubusercontent.com/90054514/157950572-63d49693-ea11-4018-9b31-90aa3504da4a.png)

![App](https://user-images.githubusercontent.com/90054514/157950581-6efba7bc-efdc-40ef-b263-ae8da9f4f3c9.png)

**Comment by EmranCoE** [comment]
All the  flows are working now . able to Turned On all .
Many Thanks again .
You can close this issue

Have A Wonderful Weekend !

Regards,
