### ISSUE TITLE
[CoE Starter Kit - question] Unable to retrieve email text for dynamic email 

### ISSUE THREAD

**Issue by DChen206** [microsoft/coe-starter-kit#2229]
### Describe the issue

When this Flow runs by hitting the Generate CSV button in DLP Editor V2's impact analysis, it is failing on:

Action: Action 'Get_a_row_by_ID' failed

Error Message: admin_customizedemail With Id = b0f83a79-fc63-ec11-8f8f-000d3a13d289 Does Not Exist

This GUID appears to be hardcoded into the "emailGUID to en-US" action.

### Expected Behavior

Email with CSVs attached are successfully sent.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

DLP Editor>Parse impacted resources into CSV

### Steps To Reproduce

1. Open DLP Editor V2 and Create a policy that blocks everything but Microsoft connectors.
2. Select only the Default Environment (Personal Productivity) or possibly an environment that you know has impacts.
3. Navigate to Impact Analysis and click on the "Export impacted apps and flows to CSV".
4. As the flow runs and hit the Get a row by ID action, the failure occurs.

**Comment by manuelap-msft** [comment]
Hello,

can you confirm you have run all the flows in our setup instructions here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-setup-flows especially **Admin | Sync Template v3 Configure Emails**? This error message seems to indicate you don't have email texts configured, which this flow does.

**Comment by DChen206** [comment]
Thanks. Yep that resolved the issue. We recently upgraded PPCoE from December's release. That Configure Email flow was turned on, but was running on a weekly schedule. The Configure Email flow last ran prior to upgrading the PPCoE. I manually reran the Configure Email flow and the CSV flow is sending out the email now.

**Comment by manuelap-msft** [comment]
Great, thanks for confirming! We are trying to make the setup experience easier with every update and are looking at updating the Admin Command Center to call out a to do list but this is still in planniing at the moment.
