### ISSUE TITLE
[ALM Accelerator - Feature]: Make easier to troubleshoot issues in update-deployment-settings.yml

### ISSUE THREAD

**Issue by michaelstephensonuk** [microsoft/coe-starter-kit#2232]
### Is your feature request related to a problem? Please describe.

When setting up the ALM accelerator if we get any configuration settings wrong the most likely place errors seem to happen is in the update-deployment-settings.yml in the templates folder.

This file contains a very big powershell script which does a lot of stuff and its really difficult to identify where the problem is

### Describe the solution you'd like

I have a few suggestions

1) Can we add logging to output to the devops console so we can identify how far its getting through the script so its easier to troubleshoot

2) Would it be possible to break up the script into multiple steps for each of the things being done within the script.  I think if there was a step which handled each of the areas within the deployment settings file and just updated the file on the build agent.  EG:
- Step 1 does connection references
- Step 2 does the environment variables
- Step 3 does the canvas app
- Step 4 does the workflow
- Step 5 does the ad groups
- Step 6 Does the updating of the pipelines to add the variables

I think breaking this down would make troubleshooting for users much easier and probably make the longer term support of the script in the toolkit easier too

3) The specific issues I had was that id misunderstood one of the permission much earlier in the toolkit setup.  I didnt see an error until in this pipeline.  It took ages to workout what the problem was and I had to add loads of logging to workout where in the script the error was coming from because devops just sees powershell exit code 1 as the error.  I think it would be useful in the pipelines to add some tests earlier in the pipelines which do some validation tests which test some of the settings and dependencies which are used later in the pipelines.  For example doing a step which tests we can connect to CRM for the main environment where the accelerator is and also the target or dev environment and then we can include logging in the pipeline step to tell the user what they have potentially mis configured.  Also doing a test that the pipelines have appropriate variables set on them.  EG one of the errors I got with this step was a "Input object null reference".  It was caused because when it tries to update the pipeline id missed adding the service connection and environment name variables.  This meant that there were no existing variables on the pipeline for the test environment so when this step attempts to update the pipeline variables it gets null for the variables which causes the script to error

**Comment by mikefactorial** [comment]
@michaelstephensonuk started to address some of this feedback in the April release, but this will be an on-going effort to refactor and add better logging in general. Closing this and referencing in #1513
