### ISSUE TITLE
[ALM Accelerator - BUG]: Powershell exit code 1 on update deployment settings

### ISSUE THREAD

**Issue by michaelstephensonuk** [microsoft/coe-starter-kit#2233]
### Describe the issue

When we run the commit to git pipeline the pipeline step for update-deployment-settings.yml always seems to get an exit code 1 which causes the devops pipeline step to get an error where it returns a powershell exit code 1.

By adding a bunch of logging it looks like the step actually executed fine and did everything it was supposed to do.  I couldnt really workout what is causing it to have a last exit code of 1

I could workaround the issue by just setting $lastexitcode = 0 at the end of the powershell script and the commit to git and the subsequent deploy to an environment work fine.

My gut feel is it was some warnings from the npm calls might be causing powershell to pick that and set the error code

### Expected Behavior

Powershell script should not exit with 1 if there are no errors

Also some logging to help troubleshoot the problem would help too

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220303.1

### Steps To Reproduce

1. Setup accelerator
2. A setup devops and pipelines
3. Run the commit to git pipeline for a solution

This seemed to just be the pretty much vanilla setup and it gets it everytime I run the commit to git pipeline if I do not ignore the error at the end

### Anything else?

This is the npm warning i see in the pipeline if it helps

![image](https://user-images.githubusercontent.com/11812194/158015449-badff32a-8601-42c3-9240-19d20a77427b.png)

**Comment by mikefactorial** [comment]
@michaelstephensonuk I haven't been able to replicate this issue and haven't heard this feedback from anyone else. Wondering if maybe you are running on a self hosted agent or in AzDO server that might explain the difference in behavior. Anything specific about your setup that might explain this? My research leads me to believe this could be a Powershell version difference or something specific to AzDO project / pipeline setup. Thanks again

**Comment by mikefactorial** [comment]
@michaelstephensonuk closing this out since we haven't gotten a response in a couple of weeks feel free to comment on this issue with more details and reopen if it's still unresolved

**Comment by danosagi** [comment]
I had encountered almost exactly the same issue on the "Update Deployment Settings" step of the pipeline after I committed a solution.
![image](https://user-images.githubusercontent.com/54644736/170535257-412a469e-70f9-49d8-b458-73d56dbcfc68.png)

Also having the similar deprecation warning lines as well:
![image](https://user-images.githubusercontent.com/54644736/170535456-12e28992-522b-4f94-801e-25a55b58336c.png)

To answer below questions:
"Wondering if maybe you are running on a self hosted agent or in AzDO server that might explain the difference in behavior. Anything specific about your setup that might explain this? My research leads me to believe this could be a Powershell version difference or something specific to AzDO project / pipeline setup. Thanks again"

I haven't done anything customized but using a trial tenant to follow all steps on the ALM Accelerator set up  documentations, so I assume I'm not running on a self hosted agent or in ADO server if these requires any customization/config to run on them.  My ADO is simply a regular ADO come with the trial.  

I was using the CLI to set up the ALM Accelerator and it's a fairly new and clean trial tenant created just for trying out ALM Accelerator.  So I followed most steps on the documentation to set the environments up.

Could you please let me know if any further details could help troubleshooting this issue, or any recommendation steps that I can try to make it work?

Thanks in advance!
