### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to update Environment Variables after import

### ISSUE THREAD

**Issue by javiermga-inditex** [microsoft/coe-starter-kit#2237]
### Describe the issue

We get the following error when running the "Admin | Sync Audit Logs" flow:

> _Unable to process template language expressions in action 'CONFIGURE_::_Tenant_Id' inputs at line '0' and column '0': 'The workflow parameter 'TenantID' is not found.'._

The error disappears when I change `parameters('TenantID')` to `parameters('TenantID (admin_TenantID)')`.

### Expected Behavior

A success flow run.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Steps To Reproduce

Just run the "Admin | Sync Audit Logs" flow to get the error.

### Anything else?

![EditFlow](https://user-images.githubusercontent.com/101564333/158168321-8690bd3b-020c-4eea-9d7e-b3b4ded5649a.png)

![FlowError](https://user-images.githubusercontent.com/101564333/158168322-48f89c9d-6b25-4b23-8e2f-74fb9a9fb184.png)

**Comment by manuelap-msft** [comment]
Hello,

it looks like you didn't configure the environment variable called Tenant ID. This is imported as part of the Core Components solution. Here's a description of the environment variable https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#all-environment-variables and here's how to update it after import https://docs.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables

**Comment by javiermga-inditex** [comment]
Hi @manuelap-msft,

Thank you for your quick response.

The `TenantID` environment variable was configured when I imported the `Center of Excellence - Core Components` solution and, as you can view in the screenshots below, the first run of the flow was successful.

If I check this environment variable in the `Admin - Command Center` app, it has the correct value.

Any idea what's going on?

Thanks!

![FirstFlowRunSucceeded](https://user-images.githubusercontent.com/101564333/158171468-2c4a0a9d-5052-4fff-be3d-f14cdf5b8c6b.png)

![FirstFlowRunTentantId](https://user-images.githubusercontent.com/101564333/158171475-694cc2f3-86e8-4d00-a632-589b550ad7a2.png)

![AdminCommandCenter](https://user-images.githubusercontent.com/101564333/158171494-396fcb2c-26ee-4a19-8392-89516196d213.png)

**Comment by manuelap-msft** [comment]
1. Do you have an unmanaged layer on this flow? Learn how to check for that in step (3) here https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup#installing-upgrades
2. Are you on the latest release of the Audit Log solution, 2.6?

I have checked this in the shipped version, and this variable is set to the value like this **parameters('TenantID (admin_TenantID)')** and succeeds for us. You may have an unmanaged layer with a change to this
![image](https://user-images.githubusercontent.com/55705669/158172485-f214722d-d16d-4cd5-b6ea-456cee5b8da2.png)

**Comment by javiermga-inditex** [comment]
Hi @manuelap-msft,

You are right, there is an unmanaged layer in that flow.

It was probably added when I changed the flow recurrence to run it every night at a certain time.

![UnmanagedLayer](https://user-images.githubusercontent.com/101564333/158174676-a2e6180b-0887-48ba-8fb0-558dd5781fa2.png)

**Comment by manuelap-msft** [comment]
I suspect what happened when you changed the flow was that it somehow messed up the way the environment variable is retrieved.

I think your only option if you want to keep a different schedule for this flow is to keep the unmanaged layer and update the variable to the correct way the environment variable is retrieved.

Note that we do not recommend having unmanaged layers or changing the schedule of this flow, but instead using environment variables to change how audit log events are retrieved. You can read up on that in Step 11 here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

**Comment by manuelap-msft** [comment]
Ah I see! I believe removing the unmanaged layer would restore the original state of the flow and it's environment variables, but would also remove all of your customizations unfortunately. And I'm not sure if you do that and then re-do your customizations, it may corrupt the environment variables again. So you're probably right in that you have to create your own flow instead!

Closing this ticket as we found the reason for the error, but please feel free to raise a new ticket if you encounter any other issues with the CoE Starter Kit! Thank you!
