### ISSUE TITLE
[CoE Starter Kit - QUESTION]  is there a way with the coe toolkit to check the capacity of a single app within an environment

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2242]
### What is your question?

Hello, is there a way with the coe toolkit to check the capacity of a single app within an environment?

Thanks

**Comment by manuelap-msft** [comment]
I'm not sure what you mean by capacity? Could you elaborate?

**Comment by JackSocini** [comment]
Capacity is the Dataverse usage in terms of Mega Byte for a single application.

Thanks

**Comment by manuelap-msft** [comment]
The CoE Starter Kit is built on top of the Power Platform, and can only show / surface data available in the platform. Is there a place where you see this information? If so, we can present it in the CoE kit.

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
