### ISSUE TITLE
[CoE Starter Kit - QUESTION] Which flow sets up environments?

### ISSUE THREAD

**Issue by billwhalenmsft** [microsoft/coe-starter-kit#2243]
### What is your question?

So, I was able to get everything setup as far as I can tell.  However, I setup the PowerBI report and there was no data.  I opened Power Platform Admin View and also noticed all the various elements (except Connectors) were blank.  

Which flow or process is setting up the Environments area?  I noticed that also had no data, which is likely why nothing is being populated.  I also noticed a few flows that fail and their errors point towards issues with the environment not being setup in Dataverse.

I attempted to setup an environment manually, however I'm sure I input some of the fields incorrectly since the error state flows were still erroring.

Errors
1) Flow - Admin | Sync Template v3 (Apps)
Message - The request failed with client error: 'The environment '<null>' could not be found in the tenant 'MYID'.'. The correlation Id is '206f4494-1069-4ca5-8611-ea3c58e6cb20'.

2) Admin | Sync Template v3 (Flows)
Message - You are not permitted to make flows in this 'ENVNAME'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions.

FYI - I replaced the text for the tenant ID and environment name.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2022

### What app or flow are you having the issue with?

Admin - Sync Template v3 (Flows); Admin - Sync Template v3 (Apps); Admin - Sync Template v3 (Custom Connectors)

**Comment by billwhalenmsft** [comment]
PS - this is the Power Platform error message and where it's failing...my UID is the global admin on the tenant and environment...so I suspect the environment setup wasn't correct.

Apps
Error - Action 'Get_Apps_as_Admin' failed
Step - Load Arrays -> Get Apps as Admin

Flows
Error - Action 'List_Flows_as_Admin' failed
Step - Get Flows and store them in CoE CDS Entity


Custom Connectors:
Error - Action 'Get_Custom_Connectors_as_Admin' failed
Step - Get Custom Connectors and store them in CoE CDS Entity

**Comment by Jenefer-Monroe** [comment]
I can't comment on anything you've done manually, but please note, at the bottom of the [Turn on inventory flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows) section, that the inventory may not begin collection for up to 12 hours due to some load balancing needs. 
![image](https://user-images.githubusercontent.com/89584709/158257509-228eda50-5f88-4442-8dfd-f770278204e8.png)


It is the **_Admin | Sync Template v2_** flow that will be filling in the details on Environments in particular.
