### ISSUE TITLE
[CoE Starter Kit - QUESTION] Question on Power Apps Business Process Flow

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2244]
### What is your question?

Hello, what it mean "Attivo per 5 ore"? Thanks

<img width="168" alt="question" src="https://user-images.githubusercontent.com/101250592/158331901-5b5ffdbd-4fa1-449a-b140-a1f3a80a670e.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by manuelap-msft** [comment]
Hello,

this is part of a product capability called Business Process Flows, learn more about those here: https://docs.microsoft.com/en-us/power-automate/business-process-flows-overview

It means that this particular process has been active for 5 days / 5 hours (unsure on the translation but it would be a time). In the case of the CoE Starter Kit, it means that the Compliance details have been requested from the maker this time ago. Learn more about the Compliance process: https://docs.microsoft.com/en-us/power-platform/guidance/coe/example-processes

**Comment by manuelap-msft** [comment]
Closing out as no further action required.

**Comment by JackSocini** [comment]
Sorry but I don't understand this phrase ' it means that the Compliance details have been requested from the maker this time ago.' Can you be more specific?

Thanks

**Comment by manuelap-msft** [comment]
This flow https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#admin--compliance-detail-request-v3 requests Compliance details and starts the Business Process Flow.

**Comment by JackSocini** [comment]
How the maker can request Compliance details? In a lot of app create by me I don't request it and the date was popolated automatically.. 

Thanks

**Comment by manuelap-msft** [comment]
The maker does not request compliance details. An automatic workflow requests compliance. Please see our documentation on this here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#admin--compliance-detail-request-v3

**Comment by JackSocini** [comment]
In this moment this flow was disable, how can it populate da date? It populated it from the creation date?
