### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Hits throttling limits

### ISSUE THREAD

**Issue by wincheng22** [microsoft/coe-starter-kit#2247]
### Describe the issue

There are several instances of flows (Admin Sync Template V3) that are stuck for days and the run history aren't available since these flows haven’t completed.  
The issue has been reported to Microsoft Support. The findings are :
1. the flows are throttling. 
2. Assigning per-flow plan to the flow does not mitigate the issue
3. one of the for each loop has been set to run concurrently and now it fails at 90 minutes (no longer timing out or getting stuck)
~ 100 records within the loop fail
4. there's nothing support engineer can do, and we are told to raise a ticket in the CoE Github

### Expected Behavior

workflows to run smoothly without throttling 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Admin-Sync Template

**Comment by manuelap-msft** [comment]
Please see #917: What to do when your CoE Hits throttling limits? Request Throttling Exemption

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
