### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment variable "admin_isTeamsInstall" deprecated?

### ISSUE THREAD

**Issue by javiermga-inditex** [microsoft/coe-starter-kit#2249]
### Describe the issue

Has the `admin_isTeamsInstall` environment variable been removed from the `Core Components` solution when the CoE Starter Kit is installed in a production environment?

It was added in a setup we did a month ago, but is no longer present in a setup we did this week.

![CoreComponents_EnvironmentVariables](https://user-images.githubusercontent.com/101564333/158588005-265c1993-4689-48b4-ab43-cef8093a09b5.png)

Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Environment variable "is Teams Install (admin_isTeamsInstall)"

**Comment by Jenefer-Monroe** [comment]
Yes we never ended up using it, and found a better way to retrieve this information, so we removed it.

**Comment by javiermga-inditex** [comment]
OK, thanks for the quick response!

**Comment by Jenefer-Monroe** [comment]
You bet, anything else I can do for you? Or are we ok to close the ticket?
