### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Desktop Flow - Runs) - Very long execution

### ISSUE THREAD

**Issue by jagibe** [microsoft/coe-starter-kit#2250]
### Describe the issue

Hi,

Reviewing the historial execution of this flow, I found several queued executions in progress.
I scrolled down the historic and I found the last ended executions have a duration ≈ 17 days! 
I've identified 3 exceptions, that I don't know if they are normal or not.

The tenant has over 1300 environments, but i see that the loop that iterates the environments, the action "List RPA Flow Sessions" is failing (catched on next action) for most environments (I detected 2 error cases for this action). 

1. The first error is when the field admin_environmentcdsmetadataname is null. I think this is normal for enviroments that doesn't have Dataverse. This error doesn't increase the execution time.
![1](https://user-images.githubusercontent.com/26441468/158585694-f3d043f1-1c60-48b9-811f-c3ea01799433.png)

2.  The second error increases the flow execution time, because 8 retries are made (22 minutes). The error returned in output is: BadGateway (502) with message "The 'RetrieveMetadataChanges' is only allowed to be accessed from OData endpoint in Dataverse for Teams offering. EnitytName: none".
![2](https://user-images.githubusercontent.com/26441468/158586121-d644c836-c7d4-4f0d-bb98-3408824c0bb4.png)

Furthermore, for the environments in which the "List RPA Flow sessions" action executes successfully and has RPA sessions to insert,  in most cases it fails when Inserting/Updating the rpa session row, because the RPA row is not found. I dont know how to investigate why those RPA rows are not inserted
![3](https://user-images.githubusercontent.com/26441468/158588038-79d48e5f-f201-4a02-93b5-82a91a1e53c9.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop Flow - Runs)

AB#1319

**Comment by Jenefer-Monroe** [comment]
We should refactor this flow as follows: 
- be type trigger and run with each envt update instead of as a long running flow
- filter out in the trigger if not CDS envt or type team
- investigate the upsert failure, I presume this is because we have hit the other issue in which some RPAs are not added to inventory when they are too large. that one is to be addressed with the fixes to the modern dataverse connector

**Comment by manuelap-msft** [comment]
This work has happened already.

**Comment by Jenefer-Monroe** [comment]
holding to go with the desktop flow refactor work

**Comment by manuelap-msft** [comment]
Closing out, addressed via the update to the modern Dataverse connector.
