### ISSUE TITLE
[ALM Accelerator - BUG]: Deploy to Prod Job

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#2251]
### Describe the issue

Hello @mikefactorial 

I do not have any issues deploying to validation and test environments. Nonetheless, while deploying my solution to Production environment I see the following error message in "Share Flows with Group Team" task:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/100951593/158624809-9fb38336-c842-40c8-931f-b3a284b64c8e.png">

Would appreciate any input on this. 
Thank you in advance :)

### Expected Behavior

I expect the Pipeline to run successfully. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

March 2022

### Steps To Reproduce

Run any deploy-prod-Solution pipeline and you will receive the error message I shared in the above screenshot.

**Comment by LizethRegules** [comment]
It seems that the template for Test build-deploy-Solution-To-Environment.yml has a step that calls set-spn-token.yml which configures the $powerShellPath/dataverse-webapi-functions.ps1, whereas the prod deploy calling the template deploy-Solution-To-Environment.yml doesn't seem to have that step and is throwing an error on dataverse-webapi-functions.ps1.

**Comment by mikefactorial** [comment]
Hi @LizethRegules Thanks for reporting this. It's been fixed in the latest version of the pipelines. You should be able to pull down the latest from the main branch in GitHub. https://github.com/microsoft/coe-alm-accelerator-templates/tree/main/Pipelines

https://github.com/microsoft/coe-starter-kit/issues/2179

**Comment by LizethRegules** [comment]
Thanks, Mike!
I was also wondering, isn't it inconvenient to have the Pipelines be ahead of the ALM Accelerator canvas app? 
I mean: 
- Canvas App has March 4th version 
- Pipelines have March 16th version

**Comment by mikefactorial** [comment]
Also, thanks for doing the investigation into this. Super helpful to have this level of detail in feedback!

**Comment by LizethRegules** [comment]
Excellent! 
I will test the pipelines and close the issue once they succeed.

**Comment by LizethRegules** [comment]
Now, it failed in a different spot. 
I am not doing it through a PR, I am running the deploy-prod pipeline only
<img width="801" alt="image" src="https://user-images.githubusercontent.com/100951593/158674356-41c3a42e-9cfc-423b-bcf0-4716ea36c885.png">

**Comment by mikefactorial** [comment]
This looks like it may be an issue with your component ownership configuration. Is it possible you've selected a user in the component ownership deployment settings screen that doesn't have a valid license / role in the production environment?

**Comment by mikefactorial** [comment]
Could also be related a connection reference owned by a different user than the owner, but maybe less likely since the error in this issue is different https://github.com/microsoft/coe-starter-kit/issues/2077

**Comment by LizethRegules** [comment]
Might be that. Since I am using a service account as the component owner

**Comment by LizethRegules** [comment]
Closing this issue, since original bug was fixed
