### ISSUE TITLE
[CoE Starter Kit - BUG] request for upgrade help from 1.45

### ISSUE THREAD

**Issue by saurabhchauhan05** [microsoft/coe-starter-kit#2252]
### Describe the issue

We are currently running on PowerApp CoE Toolkit version 1.45. 
When we are trying to upgrade CoE toolkit Core component to its latest version 3.34 then it is getting failed with error code below-

**Error code**
[80041A06](http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=80041A06&de=online)
**Exception message**
Attribute admin_rpamodifiedon is a String, but a DateTime type was specified.

We have checked all our solution in CoreComponent, but none of them is having filed/attribute with "admin_rpamodifiedon" name. 

Could you please help us with the same or provide the latest upgrade package which compatible to upgrade version 1.45? 
Thank You!

### Expected Behavior

Should be able to upgrade CoE toolkit Core component to its latest version 3.34 without any issue

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.45

### What app or flow are you having the issue with?

Admin - Sync Template 3

### Steps To Reproduce

Instruction set that we followed to upgrade-
https://github.com/microsoft/coe-starter-kit/releases

**Comment by Jenefer-Monroe** [comment]
If you cannot succeed at upgrade in end, you may need to start from scratch. 
Please see https://github.com/microsoft/coe-starter-kit/issues/1507 for help on how to get audit log data to your new envt

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
