### ISSUE TITLE
[CoE Starter Kit - BUG] Documentation issue within the core setup - reorder instructions for message center steps

### ISSUE THREAD

**Issue by Pieter-Veenstra** [microsoft/coe-starter-kit#2253]
### Describe the issue

The following page needs updating.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values

The list of variables is incomplete. e.g. Command Center - Application Client ID isn't there.

Also during the initial import in a clean environment of the core solution I'm asked for the Application Client ID, while the instructions to create the application registration comes a lot later. The sections might need a bit of reordering.

### Expected Behavior

The documentation should be a matter of follow these steps from top to bottom of the page.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Documentation

### Steps To Reproduce

NA.

There wasn't a documentation bug available.

### Anything else?

Documentation issues should be an option on this github site.

**Comment by manuelap-msft** [comment]
Unfortuantely the product doesn't allow us to specifcy optional vs mandatory environment variables, or to decide which ones to prompt for during install vs which ones to accept as empty. As per Jenefer, with the setup docs, we don't want to highlight an optional process that may cause friction for customers (e.g. not knowing how to get an Azure App Registration) at the very beginning as it may be perceived as a blocker. 

I added a note to our docs now to call out that other environment variables can be left empty during import. 
![image](https://user-images.githubusercontent.com/55705669/162971759-d50c5281-db69-4243-91e1-6115373b1339.png)

Change made locally, will go live with the May docs update.
