### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to determine the Environment variables needed for setup

### ISSUE THREAD

**Issue by pavantagirisa** [microsoft/coe-starter-kit#2254]
### What is your question?

What values to be updated for the Environment Variables for **Center of Excellence - Core Components**

admin_PowerPlatformMakeSecurityGroup --> Required for **Admin | Add Maker to Group**
admin_DeveloperComplianceCenterURL --> Required for  **Admin | Compliance detail request v3**
admin_TenantID -->Required for  **Command Center App > Get M365 Service Messages**

These are values to be updated to get the flows turned on.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

**Comment by Jenefer-Monroe** [comment]
At the beginning of each setup documentation document we describe how to get the different env variables needed for it. 
Here is that section for the [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values)

Note also that we have a [Before you begin](https://docs.microsoft.com/power-platform/guidance/coe/setup) that we suggest you walk through first.

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
