### ISSUE TITLE
Get the active and inactive users of each apps in the tenant and the unmanaged solution of CoE core component

### ISSUE THREAD

**Issue by AndriyaAugustin** [microsoft/coe-starter-kit#2256]
How can we access the app usage details of a particular app in the environment such as how many times it was launched by each user of the app, date and time of each launch, for how long a shared user has kept that app idle? And also how to get an unmanaged solution of the CoE core component solution so that we customize it adding our own apps into it?

**Comment by manuelap-msft** [comment]
Hello,

1. We don't make the unmanaged solution available currently, as customers may install it accidentally not knowing the implications - e.g. unmanaged solutions can't be deleted (you only delete the layer) and upgrades may be challenging. Many components that the CoE kit uses, such as flows and canvas apps, don't support merge behaviour so you will have to create a fork/copy of them and manage the customizations going forward. Here's our guidance for extending the kit https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup#extending-the-starter-kit
2. Who an app is shared with is stored in the Power Platform User and Power Platform User Role table which is related to the PowerApps App table. Who launches the app is stored in the Audit Log table - we don't have a report exactly what you're describing, but using those tables you should be able to match the data up and produce a report by joining the data together. 

Hope this helps and thanks for your interest in the CoE,
Manuela

**Comment by AndriyaAugustin** [comment]
Can you help me with the step by step process for extending the CoE and doing the required changes?

**Comment by manuelap-msft** [comment]
Unfortunately our team does not scale to provide help to extend the kit. If these are not changes you're comfortable making yourself, I would suggest working with a Power Platform partner: https://powerapps.microsoft.com/en-us/find-a-partner/
