### ISSUE TITLE
How to refresh the data of CoE report?

### ISSUE THREAD

**Issue by SESA377903** [microsoft/coe-starter-kit#2257]
### What is your question?

How to refresh the data of CoE report shared to other, I see the data refreshed when i publish the report, is it required to publish the report to every time to see the refreshed data?

### What solution version are you using?

March 2022

### What app or flow are you having the issue with?

Admin

**Comment by manuelap-msft** [comment]
It is not required to publish the Power BI dashboard to refresh data. Instead, you will need to configure a scheduled refresh on the Power BI dashboard: https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data#configure-scheduled-refresh

Hope that helps,
Manuela

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
