### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why the delay in the sync flows?

### ISSUE THREAD

**Issue by Pieter-Veenstra** [microsoft/coe-starter-kit#2261]
### What is your question?

The CoE Sync Flows have a delay randomly between 1 minute and 900 minutes. 

The delay action says that this is to protect the health of the Dataverse system.

This doesn't make any sense to me.

Either a delay is needed or it is not. Making this random seems to be a 'we need a bit of luck' kind of solution.

Also, the delay seems to be at the start of the Sync. So when nothing has been done yet. I could imagine that delays every now and then during the creation of a lot of data could make sense. 

Or maybe only run full/first syncs during a configurable time window ( e.g. out of hours) would be a good solution.

### What solution version are you using?

3.34

**Comment by Jenefer-Monroe** [comment]
The delay is done to prevent all the organizations that use the CoE from beginning their sync flows at the same time as they use a lot of Dataverse API calls. 

Scheduling to start at (ex) 9 PM was our first thought as well as we assumed it would mean starting at 9 PM at the point of install. But unfortunately this freezes the 9 AM at the flow origin time. So for example it would be starting at 9 PM Seattle time everywhere it was installed, therefore not spreading the API calls out.

Hope that helps you understand the reason for the delay.

**Comment by Pieter-Veenstra** [comment]
No sorry. It doesn't make any sense at all.

I just installed the CoE in a new tenant. I'm now having to wait between 1 minute and 900 minutes for things to start working. So randomly I could be hardly waiting at all ( and with the above idea in mind that could cause problems) or I'm waiting up to 900 minutes in which case I'm really protecting the system???

So randomly things go ok or not?

It would be better to monitor the health of the system while doing the initial sync. But just randomly wait for another random moment to potentially cause problems doesn't make sense to me.

**Comment by manuelap-msft** [comment]
Pieter, just to clarify - we are not talking about health of _your orgs_ system, but the health of the Dataverse system all-up. Once the product supports parameters in the schedule, we will change the delay but at the moment there's no better option available to us.

**Comment by Jenefer-Monroe** [comment]
There is an environment variable in Core called DelayInventory which you can switch to No for runs that you want to begin instantly. This can be used if you are wanting to do a one-off Full Inventory run or for first runs. 
Please do remember to set back to yes though, to protect the service.

**Comment by Pieter-Veenstra** [comment]
So why not set that to No by default and let the first successful sync set that to yes?

**Comment by Jenefer-Monroe** [comment]
We do not want to change the value of this env variable underneath people. 
But thanks for using CoE and offering your suggestions.

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
