### ISSUE TITLE
[CoE Starter Kit - Feature]: Flow error handling

### ISSUE THREAD

**Issue by Pieter-Veenstra** [microsoft/coe-starter-kit#2262]
### Is your feature request related to a problem? Please describe.

All the flows that could potentially fail should have some general error handling in it. 

### Describe the solution you'd like

The try Catch pattern should at least be implemented so that emails with links to the failed flow runs are sent to a configurable Admin email address.

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid I dont follow you. Are you referring to the Sync Flow Error pattern that we have? 

It collects the failures into a table as shown here:
![image](https://user-images.githubusercontent.com/89584709/158813149-afe6ae74-f1d9-4ec9-811d-b2b3c80f6c0b.png)

And then send them to the admin via **_Admin | Sync Template v3 (Sync Flow Errors)_**

**Comment by Pieter-Veenstra** [comment]
![image](https://user-images.githubusercontent.com/18352488/158814459-7f4177d5-ee81-422b-b0b7-c4fdf75cceff.png)

In the above image, I would adjust two things. 

1. All steps before the error handling step should be included in a single scope. Currently there are two scope boxes and some variable initialisation steps (the variables should be worked away with compose actions but that is a different discussion all together). Currently if anything goes wrong in the  Get Environments then the error handling will not kick in.  Hence my initial request.
Some additonal points:
2. The error handling currently only triggers on failed. It should include time out as well.
3. Then when something goes wrong it is logged. However, having email alerts (or any other form of alert could be sometimes required). Making this a configurable options with variables would be nice.

**Comment by Jenefer-Monroe** [comment]
I wish I could hide away those variable initializations in a scope but that is not supported by the product
![image](https://user-images.githubusercontent.com/89584709/158816229-1c6f1867-c07e-435b-a337-f6a030b68578.png)

There may be a few of these that we could have as compose instead, but for the most part these are variables and not composes because we set them in many places.

**Comment by Jenefer-Monroe** [comment]
We have never had people have report to use failures in that first scope, nor time outs. 
In general the best feedback for us, that we will act upon will be driven by actual failures faced by customers. Please let us know if you see this in the wild, or if you are just doing a code review for us here.

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
