### ISSUE TITLE
[CoE Starter Kit - BUG] Admin – Access this Flow & Admin – Access this App : permissions failures

### ISSUE THREAD

**Issue by powersd01** [microsoft/coe-starter-kit#2263]
### Describe the issue

Installing the CoE Starter Kit, somehow Contoso Environment Tenent ID is getting imported into our environment when importing the CenterofExcellenceCoreComponents_3_31_managed.zip. 
Here are our steps:

We downloaded the CoE Starter kit from aka.ms/CoeStarterKitDownload
1. We went to the Power Platform Admin Center – Select Environments – New – then Save
2. We went to make.powerapps.com – Select our new environment
3. Selected Solutions – select Import
4. we imported the CenterofExcellenceCoreComponents_3_31_managed.zip
5. We connected all the Solutions connections
6. Now, the only variables we configured were the TenantID (we added our company Tenent ID) & Power Automate environment variable – then select Import
7. We waited for the new environment to build.

We didn’t get too far in the build as you can see. This morning I went out and wanted to check both apps (Admin – Access this Flow & Admin – Access this App) and found this error. 
![image](https://user-images.githubusercontent.com/47794763/158812252-4f92df59-2f22-4aa5-a21b-a971d4c7c722.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/47794763/158812306-48b077cf-2dcd-4f65-a6db-54681692a6b4.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3_31

### What app or flow are you having the issue with?

Admin - Access this Flow & Admin - Access this App

### Steps To Reproduce

We downloaded the CoE Starter kit from aka.ms/CoeStarterKitDownload
1. We went to the Power Platform Admin Center – Select Environments – New – then Save
2. We went to make.powerapps.com – Select our new environment
3. Selected Solutions – select Import
4. we imported the CenterofExcellenceCoreComponents_3_31_managed.zip
5. We connected all the Solutions connections
6. Now, the only variables we configured were the TenantID (we added our company Tenent ID) & Power Automate environment variable – then select Import
7. We waited for the new environment to build.

We didn’t get too far in the build as you can see. This morning I went out and wanted to check both apps (Admin – Access this Flow & Admin – Access this App) and found this error.

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry you started with exactly the two apps that don't work stand alone :)

These two apps in particular do not work without being in the context of the Power BI. The Power BI hands the app the tenant, envt, and app that should be used. Stand alone they refer to our tenant, envt, and app simply because I was trying to make debugging easer for myself.

Please see [configure embedded apps in the coe dashboard](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard) for how they are used. 

Thanks for using CoE and sorry for the confusion.

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
