### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flows) and (Apps) Maker Check - Edit Bad Gateway error

### ISSUE THREAD

**Issue by hatfield41** [microsoft/coe-starter-kit#2264]
### Describe the issue

Flows are failing due to a Bad Gateway error in Maker Check - Edit steps of the Admin Sync Template v3 (Flows) and (Apps) flows.
![image](https://user-images.githubusercontent.com/71793581/158836314-a68c0647-216a-4b44-9ba1-c07edc4a988b.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows) and (Apps)

**Comment by Jenefer-Monroe** [comment]
Hello have you ensured that all the child flows are turned on?
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows

**Comment by Jenefer-Monroe** [comment]
Please go to the **_HELPER - Maker Check_** flow, and see if the connections are in place and have the green check mark as shown here

![image](https://user-images.githubusercontent.com/89584709/158889506-fbae9a1a-143c-4ff7-a82d-fec5f8d3dc3b.png)

If those look good, it may be your [run-only user](https://docs.microsoft.com/power-platform/guidance/coe/faq#set-flow-run-only-users-properties) settings as shown here
![image](https://user-images.githubusercontent.com/89584709/158889852-0ff8056e-686a-4282-b65c-5515a125ff38.png)

**Comment by hatfield41** [comment]
All the helper flows run-only properties are properly assigned with the exception of Helper-ObjectOperations, which doesn't use any connections.

**Comment by Jenefer-Monroe** [comment]
what do you mean that they are set properly?

**Comment by hatfield41** [comment]
I mean that the run-only user properties for all the flows are set to use my connections as described in the [run-only user](https://docs.microsoft.com/power-platform/guidance/coe/faq#set-flow-run-only-users-properties) article you shared above.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
