### ISSUE TITLE
[CoE Starter Kit - QUESTION] Question about request of "App and Flow Archive and Clean Up View"

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2265]
### What is your question?

Hello, what appened if user doesn't answer to a "App and Flow Archive and Clean Up View" comunication with approve or reject?
The app will be deleted or not?

Thanks

### What solution are you experiencing the issue with?

Governance

### What app or flow are you having the issue with?

App and Flow Archive and Clean Up View

**Comment by Jenefer-Monroe** [comment]
No, the archival flows only delete objects if they are approved for delete. 
We keep a date stamp for when we started asking for approval and thats how you can tell how old / how stale the ask is.  This is surfaced in various places including the **_Cleanup Old Objects App_** as shown here

![image](https://user-images.githubusercontent.com/89584709/158889034-4c812c68-2e14-4b45-9669-6d258cb604b2.png)

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
