### ISSUE TITLE
[ALM Accelerator - QUESTION] Avoid working with branches and just deploying to main

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#2267]
### What is your question?

Hey @mikefactorial 

I have several questions around ALM.

1. Without creating branches, I want to commit directly to main, but the Update Deployment Settings step fails since it wants to create a Branch Policy for the Solution branch (that I did not created). Is there a work around this, so that I don't have to create neither a branch for each solution nor the branch policy and only have my solution folders in main?   

2. Currently, my whole team sees the dropsdowns of deployment user settings . I want to limit it to only see makers and not admin user settings. How can I do that? I gave my users the Basic User Role and ALM Power App Access and I shared with them the connection to the custom connector I created with a service account. 

3. When I deploy to validation and test, my pipelines run correctly (even though I have my email address as a connection reference and a service account as a component owner). Nonetheless, when I run the prod pipeline it fails saying the component owner does not exist in my tenant (the service account has system admin role in all my environments). I changed the component owner to be the same as the connection reference and it still failed, so I am not sure why it is failing. Also, when I open the variables in my test pipeline I do not see connection references nor component ownership, yet they are set in the environment. On the other hand, the prod pipeline does have the component ownership and connection reference variables, but it is failing. 
![image](https://user-images.githubusercontent.com/100951593/158871015-4afd1efb-d565-4db3-bc84-bfdd1ad5ba91.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

March 2022

**Comment by mikefactorial** [comment]
@LizethRegules great feedback and questions.
1. This is possible. Internally we have the same branching strategy in the CoE Starter Kit, but it involves some manual manipulation of the pipelines and some configuration of the deployment profile to change the default Target Branch from [Use Solution Branches] to main. Our longer-term goal is to make this more easily configurable in the app. I'll open a feature request for this specific ask to be addressed in a future release. For now it may make sense to get on a call to walk through how to set this up if you want to schedule something for next week.
2. Assuming you're referring to the dropdown in the app that allows the user to select their experience. There is documentation on how to share user settings that might help. Essentially, if you only want a user to see a specific experience (i.e. user setting) you need to restrict their access to only that record in Dataverse. System admins will have access to all user settings but users with only Basic User and the ALM Power App Access role should only see the user settings that are shared with them. The one caveat is if the user has no user settings shared with them the first time they login a new user setting record will be created and default to the "Advanced Maker" experience which gives the user all of the knobs in the app. https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles
3. This is strange. Not totally sure what's happening here. Maybe we could troubleshoot on our call for #1019

**Comment by LizethRegules** [comment]
Closing the issue, since we are having a meeting regarding these points.

**Comment by mikefactorial** [comment]
@LizethRegules can you send me a copy of the unmanaged solution that is failing to deploy to prod so I can try to replicate this on my end?

**Comment by mikefactorial** [comment]
Hey @LizethRegules I believe I've tracked down the issue. There was a small bug in the update-component-ownership.yml. You can see the change in this PR. This should resolve the error we were looking at yesterday. The main issue here is that in order to update a flows owner it has to be deactivated first and in the case of the prod pipeline the flows were turned on after import. For whatever reason this wasn't the case in the Validation / Test pipelines. Can you test and let me know if this resolves the issue?

**Comment by mikefactorial** [comment]
I'd recommend deleting the existing connections from the prod environment to see if that updates the connection references on deploy. I'm going to close this issue out for now to make sure it doesn't get conflated. Feel free to open another issue related to the connection references if need be.
