### ISSUE TITLE
[CoE Starter Kit - Feature]: How collect all the logs for Dataverse for Teams

### ISSUE THREAD

**Issue by JulienP78hk** [microsoft/coe-starter-kit#2274]
### Is your feature request related to a problem? Please describe.

We want to open Dataverse for Teams on the tenant to let the end users from it (PowerApps in Teams, PVA in Teams)
 
As a prerequisities, we need to be able to collect all the logs for Dataverse for Teams.
We did not find a way to get the Dataverse for teams logs on the tenant and the tenant level analytics feature don't provide them neither.
 
How can we achieve this ? Your recommandations or vision would be very helpful for us.
If this is not possible, would it be possible to initiate a feature request ? We have thousands of users (>100K users) on the tenant and an important volumetry.

### Describe the solution you'd like

Find a way to get the Dataverse for Teams logs on the tenant.
This is mandatory to open Dataverse for Teams for the end users, it is blocked at the moment.

**Comment by Jenefer-Monroe** [comment]
Hello, can you please comment more specifically on the type of logging to which you are referring?
