### ISSUE TITLE
[CoE Starter Kit - BUG] DoD and GCC High with Adaptive Cards: Request Orphaned Objects Reassigned (Parent) Flow Error in DoD

### ISSUE THREAD

**Issue by rrwolfe** [microsoft/coe-starter-kit#2275]
### Describe the issue

When attempting to turn on the "Request Orphaned Objects Reassigned Flow (parent)" flow in a DoD environment, we're receiving the following error:

Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'WorkflowOperationInputsApiOperationNotFound' and message 'The 'inputs' of workflow operation 'Send_Intro_Card_to_Manager' of type 'OpenApiConnection' are not valid. The API operation 'PostUserAdaptiveCard' could not be found in API 'teams'.'."}}"

![image](https://user-images.githubusercontent.com/74214126/159247330-07de48c9-8cde-4281-bb64-be116eebe13e.png)

![image](https://user-images.githubusercontent.com/74214126/159248007-6d5ce729-6d4a-4f2f-b8f1-b4f8cf7d5a31.png)

It looks like this flow uses adaptive cards which I don't believe are available in DoD region yet. Is there another option for the "Send Intro Card to Manager" step that can be used in DoD?

### Expected Behavior

Flow should turn on and execute successfully

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.13

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (parent)

### Steps To Reproduce

1. In DoD tenant with CoE Starter Kit Governance solution installed
2. Attempt to start the Request Orphaned Objects Reassigned (Parent) flow

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, I was unaware of this limitation. 

Sounds like today we cannot support these two solution areas:
o	Governance: Orphaned Object flows
o	Nurture: Pulse Feedback Maker Survey

And this limitation impacts GCC High and DoD for the medium term. 
And GCC in the near term. 

I think what we will need to do is
1) Update documentation to say these arent supported today
2) For orphans, see what it would cost to augment one of the existing apps to add the last bit of functionality
3) For pulse.... I'm not sure will need to check with that dev

**Comment by Jenefer-Monroe** [comment]
Posted https://github.com/microsoft/coe-starter-kit/issues/2283 to track the quick doc fix. Hope to get that done for April

**Comment by manuelap-msft** [comment]
Closing out as this is a product gap until teams adaptive cards are available in Teams.
