### ISSUE TITLE
[CoE Starter Kit - Feature]: Table "Customized Email" | increase Max length of field "Body"

### ISSUE THREAD

**Issue by Sani1991** [microsoft/coe-starter-kit#2282]
### Is your feature request related to a problem? Please describe.

We want to use the customized email table to store our customized governance mails to our Power Platform users. Our mail bodies exceed the max length value of the field "admin_body" in table "Customized Email" which is currently set to 4,000 max length.

Our mail template bodies have **up to 30,000 characters.**

### Describe the solution you'd like

Please increase the field "admin_body" in table "Customized Email" from _4,000 (4k)_ to **50,000 (50k)** so that everybody can use large mails in the future.

### Describe alternatives you've considered

As an alternative we would create our own "Customized Email" table in our unmanaged solution where we store all of our customizations to the CoE starter kit. It would be a workaround, however it would be nice to use the out of the box table you provide in the CORE solution.

### Additional context?

Please see screenshot below for further understanding:
![customized_email_body_field_max_lenght](https://user-images.githubusercontent.com/90025284/159334161-70423368-eb67-4ba4-8e61-8f130b4e5d04.png)

**Comment by Jenefer-Monroe** [comment]
Easy fix, able to slip it in to April.
