### ISSUE TITLE
[CoE Starter Kit - QUESTiON] Save - As and the CoE

### ISSUE THREAD

**Issue by Srise96** [microsoft/coe-starter-kit#2284]
### What is your question?

Hello Microsoft,

Can we clone the Admin Sync Flows in the "Center of Excellence - Core Components" or clone the entire "Center of Excellence - Core Components" solution? The clone option is disabled as shown in the picture below.

![image](https://user-images.githubusercontent.com/100741617/159433543-198cffbc-56a6-47b0-bfe9-576c537aa6a5.png)

If cloning is not allowed, is there any other options to replicate?

**Comment by petepuu** [comment]
@Srise96 you can't clone managed solutions only unmanaged but you can copy any component to your own unmanaged solution. That is recommended way to customize StarterKit components. See more https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup#extending-the-starter-kit

<img width="378" alt="image" src="https://user-images.githubusercontent.com/8307644/159637090-64c3174e-d0ff-49b4-8e16-b57db57a1bab.png">

<img width="617" alt="image" src="https://user-images.githubusercontent.com/8307644/159637744-559542e9-3629-484f-ad15-74b1a615cf6b.png">

**Comment by manuelap-msft** [comment]
Closing out as there's no open questions for the CoE kit team!

**Comment by Jenefer-Monroe** [comment]
Leaving open to point folks to until we have a resolution for how to extend he kit.

**Comment by manuelap-msft** [comment]
Closing out, we now have an article on docs on how to extend the CoE kit.
