### ISSUE TITLE
[CoE Starter Kit - QUESTION] LICENSING QUESTION - Pay as you go

### ISSUE THREAD

**Issue by Jodarcy1** [microsoft/coe-starter-kit#2290]
### What is your question?

Can the COE be configured to have Pay as you Go for end users and premium licenses per user for the admin team or can all users use Pay as you Go in the COE?

**Comment by manuelap-msft** [comment]
Hello,

both is possible. You can configure the environment to have just Pay As You go, or certain users (e.g. those who frequently interact with the CoE, like your admins) can have a premium license. For pay as you go, you're only charged if a user does not have a sufficient license - e.g. if a user with no license opens a canvas app using premium features, you'll be charged pay as you go amount. if a user with a Power Apps license opens the same canvas app, you won't be charged as they're already covered with a license.

Keep in mind that pay as you go can end up being more expensive than per user if you have users frequently using the apps - so I would probably recommend licensing your admins with a Per User license, or covering certain apps with a Per App license.

Let me know if that helps
Manuela

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
