### ISSUE TITLE
[CoE Starter Kit - BUG]  Audit Log Connector set up - The subscription is already enabled.

### ISSUE THREAD

**Issue by wincheng22** [microsoft/coe-starter-kit#2292]
### Describe the issue

I am currently trying to set up a new COE environment. 
In my old env, i enabled the O365 audit log connector and set up the connection successfully. 
As i tried to configure it in my new env, I got an error saying the subscription was already enabled. 
I am not sure if that will hinder me from collect audit log data from my new env.
![image](https://user-images.githubusercontent.com/101630322/159654859-f6cf80a4-b40f-4d8b-a33f-864837a8e06f.png)

### Expected Behavior

200 Status OK

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Flow connector

**Comment by manuelap-msft** [comment]
Hello,

if your environments are in the same tenant, than that's expected behaviour - the subscription only needs to be enabled ones per tenant (not per environment). This error will not hinder you from getting audit logs, as the subscription is already correctly enabled.

Manuela

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
