### ISSUE TITLE
[ALM Accelerator - BUG]: Update Pipeline to overwrite the version of Microsoft.CrmSdk.CoreTools used

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2293]
### Describe the issue

The latest version of https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools addresses this issue: fix handling of CanvasApp where app name and paths to composite files (.msapp, image) differ; file name reference in meta xml is now source of truth

This is currently a problem for the CoE Starter Kit Core Components solution where an auto-generated component library (generated as part of using command bar) name is too long and thus unpack solution fails. 

### Expected Behavior

With the latest version of CoreTools, unpack solution should correctly unpack the solution even with long canvas app names. 

The pipeline currently does not use the latest version. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

latest

**Comment by mikefactorial** [comment]
We've implemented this internally for the CoE Starter Kit. I'm going to leave this open until we can remove the workaround in favor of using the latest of the Build Tools.

**Comment by rsantos00** [comment]
Created a PR with the workaround since multiple clients are reporting the issue, if approved will be ready in June release.

**Comment by mikefactorial** [comment]
This has been resolved in the June release
