### ISSUE TITLE
[CoE Starter Kit - BUG] App Shared Users does not show correct information

### ISSUE THREAD

**Issue by remzoa** [microsoft/coe-starter-kit#2296]
### Describe the issue

In the Power Platform Admin View app, we are supposed to be able to see how many users and groups an app is shared with, and we are supposed to be able to see specifically what users. 

When going trough apps, we see discrepancies, where "App Shared Users" shows a completely different number then the "App Shared With (List)" field. 

I.e:
![asdasd](https://user-images.githubusercontent.com/73874761/159686844-cd8068ac-8c7f-4cde-8aca-55bd4935fe01.PNG)

### Expected Behavior

Expected behavior is that the field "App Shared Users" shows the same number as the field "App Shared With (List)"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

Open Power Platform Admin View
Go to PowerApps Apps
Click on app
Check number in field "App Shared Users" to see if it matches number in field "App Shared With (List)"

**Comment by Jenefer-Monroe** [comment]
Do you have all of the flows in the [inventory setup instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) turned on?

And then, is the **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_** running and passing successfully?

**Comment by remzoa** [comment]
Thanks for your reply. 

All of the flows from inventory setup instructions are turned on. 

The flow "Cleanup - Admin | Sync Template v3 (Power Apps User Shared With)" has run, but I see that it has status as failed. 

The failure is in the "Walk Each Environment" -> "Proceed if Envt already in CoE" -> "Run a Child Flow" part, and only on 1 of 282 runs has failed. 

The error is 
Code: "NoResponse"
Message: "The Server did not receive a response from an upstream server."

If one of the runs fail, do all of them get invalid for this Flow?

**Comment by Jenefer-Monroe** [comment]
I would expect the data for the failing environment to be incorrect as a result. 
I expect the other environments to be correct, though perhaps not up to date, based on how recently the clean up flow has ran. 

I recommend running **_Cleanup - Admin | Sync Template v3 (Power Apps User Shared With)_** again, if it still fails for that environment you will need to go to the child flow (**_CLEANUP HELPER – Power Apps User Shared With_**) and see where it failed.

**Comment by remzoa** [comment]
When going trough even more apps, I can see that the information is correct for some of them, and then incorrect for others. So parts of the Flow are going trough. 

Checked the child flow, and it fails here: 

"Walk the Apps in this Envt" -> "Roles for this app" -> "Apply to each unshare" -> "Unrelate User from Role" 

Error is "BadRequest" for table name: "Power Platform Users".

It has failed on several occasions since I ran the main Flow again, and it fails on the same thing each time.

**Comment by Jenefer-Monroe** [comment]
At the point of failure, is it always failing for the same row id? (aka the same user) 
And if you copy the url in unrelate with, does it resolve to some odata when you browse to it?
![image](https://user-images.githubusercontent.com/89584709/159723513-f87f2c0a-4215-49f5-bea9-3eac51f16de0.png)

**Comment by Jenefer-Monroe** [comment]
Are you saying that you have multiple users called "Tenant" in your Power Platform User table? 
Can you please check to see if you have one that looks like this:

**Display Name**: Tenant
**Type**: Tenant
**Power Platform User**: Your tenant GUID

**Comment by Jenefer-Monroe** [comment]
I've poured over this flow and cannot repro nor find a cause, so we'll likely need to slowly debug through your case. 
Pleasae let me know the answers above as a starter. Thanks!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
