### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inventory numbers are different PP Admin v CoE

### ISSUE THREAD

**Issue by animta** [microsoft/coe-starter-kit#2307]
### What is your question?

We installed the CoE on 2/23/22 and have not made any changes to it since installing it. However we noticed the number of Power Apps and Power Automate Flows in the CoE are not matching what the reports are saying in Power Platform. We checked to make sure that inventory is turned on via CoE. The amount of apps missing from the CoE is 66 this week it was showing a difference of 95 last week. How do we get the CoE to reflect the amount of apps that Power Platform is showing?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31 - installed on Feb 23, 2022

### What app or flow are you having the issue with?

Power BI CoE

**Comment by animta** [comment]
We did the full inventory run about 2 weeks ago with no success.

**Comment by Jenefer-Monroe** [comment]
ok, few questions
- Did you leave the env variable set to yes until all the flows all completed? 
- Do you see all the environments inventoried? 
- Does the identity running the flows have its the Power Platform Admin role? 
- Is the role and license assigned permanently? (not via PIM)

**Comment by animta** [comment]
Did you leave the env variable set to yes until all the flows all completed? The variable has been set to yes since last week
Do you see all the environments inventoried? The CoE is saying we have 233 Environments but Power Platform is saying there are 225 for PowerApss and 34 Environments for PowerAutomate. For PowerApps the Coe is saying there are 2730 total Apps and PP shows 2796 total apps. In short our CoE does not match any of the reports in PP.
Does the identity running the flows have its the Power Platform Admin role? Yes 
Is the role and license assigned permanently? (not via PIM) The role is permanently assigned

**Comment by Jenefer-Monroe** [comment]
It sounds like you might not have the clean up flows running, for one element of the count differential. 
Please ensure all the flows in the [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) are running and passing including
- [child flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-child-flows)
- [setup flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-setup-flows)
- [inventory flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows)

I see, sorry I thought you were saying the CoE was only showing a hundred or so objects. 

There are inventory differences  between PowerShell, Power Platform Admin Center, and CoE Starter Kit
Please see this limitation documentation: [inventory differences](https://docs.microsoft.com/power-platform/guidance/coe/limitations#inventory-and-telemetry-differences-between-powershell-power-platform-admin-center-and-coe-starter-kit)

**Comment by animta** [comment]
Hi,
We installed the CoE with the trainer from Microsoft. I checked all the flows as you suggested and only two were turned off which was "Helper-Maker Check" and "Admin | Add Maker to Group". Below are others that are switched off, do they need to be turned on as well? Would the flows that were off affect the inventory not matching?  

<img width="685" alt="CoE Flows" src="https://user-images.githubusercontent.com/102303747/160127634-6ee4616f-010e-41c6-a892-6088a3a4150e.PNG">

**Comment by Jenefer-Monroe** [comment]
Yes Maker Check being off will impact the ability to gather inventory. I would expect the flows that attempt to call it to fail if its not turned on, which is most of the inventory flows. Have you been monitoring the flow pass rate / health? That is needed in order to have a successful CoE. 

One way to monitor the inventory flow health is in the Admin - Command Center app which is part of Core. 
Please go see how the flows are doing there.
![image](https://user-images.githubusercontent.com/89584709/160148274-42d107db-829a-4217-9bb0-e13b4a3d8ad3.png)

**Comment by Jenefer-Monroe** [comment]
Regarding which flows need to be turned on, this depends on which parts of the starter kit you are using. 
The ones you show labeled compliance are part of our [Compliance Processes](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#compliance-processes)

When you look at our documentation you will see the setup instructions split on this. So you only need those flows on if you are using those processes, they are not needed for Inventory
![image](https://user-images.githubusercontent.com/89584709/160148919-1aaae10d-2d1d-4023-9853-60d009cc4fa1.png)

**Comment by animta** [comment]
Yes I have been monitoring the flows health and prior to today we were having several failures. So only one flow has failed and that was at 4am. I have checked the CoE and the inventory is still off by 64 Power Apps, while the Power Automate CoE shows an increase of 141 flows than PP shows. Also, I am not able to turn this flow on, please see below.

<img width="843" alt="Admin - Add Maker to Group" src="https://user-images.githubusercontent.com/102303747/160148929-ab990374-692d-436f-afa7-41e63c8b2bc0.PNG">

No we are not using compliance as of yet, so I will leave those turned off. I looked at the limitations document that you posted  and I will need to dig deeper into our apps to see if any of those scenarios apply to us. But ideally the CoE should only be off by however many new apps/flows that were created recently that day, correct?

**Comment by Jenefer-Monroe** [comment]
That error indicates that you did not fill in the [required environment variable](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values) outlined in the setup instructions. 

![image](https://user-images.githubusercontent.com/89584709/160153553-665bae11-f314-4212-8497-91ec64564d75.png)

**Comment by animta** [comment]
Hi Jenefer,

What did you say the reason was for the CoE data not matching the PP inventory? This morning the CoE is reflecting even less apps than it did last week. Resulting in the CoE having 103 apps less than PP is showing we have.

**Comment by Jenefer-Monroe** [comment]
You had a helper flow turned off would have impacted ability to gather inventory. 

You need to make sure all the flows are turned on, and then wait for the inventory to occur, it sounds like you are set to do full inventory so that is good. Although note that you do need to turn the flows off and on for that setting to take, not sure if you did that. 

Then you also need to monitor your flows pass rate. This can be done in the Admin - Command Center app, Service Help page
![image](https://user-images.githubusercontent.com/89584709/160430666-20b7ee97-f395-412e-baed-b773e425ed30.png)

**Comment by animta** [comment]
Hi Jenefer,

I did turn all the flows off and back on last week, full inventory is still on. I'm confused as to why the CoE would now show we have 103 less apps compared to the Power Platform report today. I thought after turning on the "Helper-Maker Check" flow, the number would be much closer to the Power Platform report since it had the weekend to catch up.

**Comment by Jenefer-Monroe** [comment]
Can you validate that you turned the flows off and back on after changing the full inventory env var? 
If not, please do so. 

Can you validate that you have looked at the service health page? Did you have failures?

**Comment by animta** [comment]
After updating the value for full inventory the message came on to reset the flows. I went down to the bottom of this screen and select reset flows and proceeded to turn off and on the flows that were listed. Today I checked the health and there are several failures again.

<img width="567" alt="Full Inventory Update" src="https://user-images.githubusercontent.com/102303747/160471776-d24a5689-ea2b-46d5-bd14-c51687d9f54a.PNG">
.
<img width="879" alt="Full Inventory Flow Reset" src="https://user-images.githubusercontent.com/102303747/160471798-b92ce1f1-7710-45bb-bd52-0244d1014cd3.PNG">

**Comment by Jenefer-Monroe** [comment]
You need to investigate these failures.

**Comment by Jenefer-Monroe** [comment]
Also please see [expected differences between powershell, ppadmin, and coe](https://docs.microsoft.com/power-platform/guidance/coe/limitations#inventory-and-telemetry-differences-between-powershell-power-platform-admin-center-and-coe-starter-kit)

If you find differences not explained by this list, please return with specific cases, we cannot debug a generalized inventory issue.
