### ISSUE TITLE
[CoE Starter Kit - BUG] Teams CoE Dashboard - App usage report not showing data

### ISSUE THREAD

**Issue by ajinkyaskulkarni** [microsoft/coe-starter-kit#2310]
### Describe the issue

App drop down is populated correctly
App usage report doesn't show data
![app usage report without data](https://user-images.githubusercontent.com/25870713/160124772-ad386b5c-5738-4a90-b8a3-89f0c8c0e7ad.png)

### Expected Behavior

App usage report should display data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponentsTeams_3_15_managed

### What app or flow are you having the issue with?

'App Usage' Report not showing any data

### Steps To Reproduce

Goto CoE dashboard.
click on report 'App Usage'.
verify if data is rendered or not.

**Comment by manuelap-msft** [comment]
Hello,

if you have the CoE Starter Kit installed in a Dataverse for Teams environment, that is expected, as App Usage information is not available in Teams:

See limitations here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#decide-what-environment-type-to-use-production-or-dataverse-for-teams
![image](https://user-images.githubusercontent.com/55705669/160129136-02d7a0d0-2911-44ad-9429-72ef64aa851a.png)

**Comment by manuelap-msft** [comment]
Closing out as no additional questions for the CoE kit team.
