### ISSUE TITLE
[CoE Starter Kit - QUESTION] Desktop Flow inventory failures

### ISSUE THREAD

**Issue by pavantagirisa** [microsoft/coe-starter-kit#2313]
### What is your question?

The flows inside the **Center of Excellence - Core Components** solutions are failing continuously when extracting the Desktop Flow runs or desktop flows from multiple environment.

The **List Desktop Flows** Data verse Action  is failing with Bad Gateway error.

Also, the actions that use Legacy Data verse connector is failing with permissions related error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

**Comment by Jenefer-Monroe** [comment]
Note that we have a product limitation around the ability to gather Desktop Flows that makes this inventory not successful sometimes. Please see
https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#large-desktop-flows

Please share screenshots of specific failures if you think they are unrelated to this limitation.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
