### ISSUE TITLE
Queries on the setup document

### ISSUE THREAD

**Issue by KarthikRao-HM** [microsoft/coe-starter-kit#232]
Line :
**Download the latest managed solution from GitHub (https://github.com/microsoft/coe-starter-kit/releases)**
Need clarity on how to find the managed solution of ALM starter kit.

Line : 
**Select Save and Export and save the data to a folder called ConfigurationMigrationData in your local Azure DevOps repo under the solution folder for which this configuration data is to be imported.**
Need clarity on how to find the local folder of Azure DevOps repo.

Line  : 
**Update the pipeline name to build-MyNewSolution (where 'MyNewSolution' is the name of your solution) and select Save.**
Initially the pipeline is named as build-MyNewSolution (or any user specific solution)
While creating the Environment variable there is ambiguity on which pipeline it needs to be created on
**The EnvironmentName variable is used to specify the Azure DevOps environment being deployed to in order to enable tracking deployment history and set permissions and approvals for deployment to specific environments. Depending on the environment to which you're deploying set this value to Validate, Test or Production** 

Generic query  : 
1. Where should the service connection for dev environment be created?

2. While creating application user in the environment the default page does not have a business unit field defined and was not letting me save the user. Had to open the form in legacy settings and add the field and then save. Can this step be added as "if then" to the documentation?

**Comment by mikefactorial** [comment]
@KarthikRao-HM this is great feedback. It will help make our docs better. Thank you. To answer your queries.
1. The latest Managed Solution can be found under Assets in the most recent release.
![image](https://user-images.githubusercontent.com/42348035/116722434-60e4ab80-a9ac-11eb-9e0e-8444da8c311c.png)
2. You'll need to clone your repo to your local machine. This can be done either from the Git command line, Git Desktop App or from Azure DevOps by selecting Clone from your repos home page
![image](https://user-images.githubusercontent.com/42348035/116722853-ee280000-a9ac-11eb-939d-9c9e3635205d.png)
3. Azure DevOps generally names the pipeline you create after the name of the project when you create a new pipeline. If in your case you didn't see this behavior then you can ignore this step but double check that you see the correct name when you look at the pipelines tab in Azure DevOps
![image](https://user-images.githubusercontent.com/42348035/116723299-5b3b9580-a9ad-11eb-9c4b-51f4881eef01.png)

Generic query:
1. Not sure I understand the question. When you are creating the Service Connections under project settings you will create Dev, Validation, Test and Production. The same steps apply for each environment. You'll need to follow those instructions for each environment. https://github.com/microsoft/coe-starter-kit/blob/main/PowerPlatformDevOpsALM/GETTINGSTARTED.md#create-service-connections-for-devops-to-access-power-platform
2. I can add this under the troubleshooting section.
