### ISSUE TITLE
[coe starter kit - question] is there a way to avoid teams connection while importing COE core components.

### ISSUE THREAD

**Issue by suvernagithub** [microsoft/coe-starter-kit#2320]
**Describe the bug**
we are trying to import COE core component solution, but we are getting error with respect to teams connection since our organisation teams is not enabled for usage. Is there a way we can avoid teams connection while importing COE core components.

**To Reproduce**
1. download COE core component solution
2. Open flow.microsoft.com>solutions>import >select downloaded file
3. Error with teams connection. See attached.

**Screenshots**
See screenshots

**Additional context**
our organisation does not have teams enabled
![COEsolutionerror](https://user-images.githubusercontent.com/102155172/159485480-463a5b6d-218a-4e08-ad46-f6edc9b8bbdf.png)

**Comment by manuelap-msft** [comment]
Hello,

the CoE Starter Kit uses Teams to post adaptive cards to makers in some flows. You can try using Classic Solution Import, which won't prompt you to set all connection references in the beginning. You can then update the connection references after import and leave the Teams one out. You will have to change some flows to not use Teams, if they have functionality you want to use.

Hope that helps,
Manuela
