### ISSUE TITLE
[CoE Starter Kit - QUESTION] App Usage page blank

### ISSUE THREAD

**Issue by AbhishekSaxena123** [microsoft/coe-starter-kit#2331]
### What is your question?

Hi Team,

We have identified couple of pages, App Usage, where data is not being reflected from CoE Dataverse. Could you please let us know, what component is responsible for fetching the data for these pages, so that we can validate if those components are running successfully.

Also Launch Date filter is greyed out in all the pages. If you can provide the justification, how we can validate if there is any app been launched on the environment.

Thanks,
Abhishek Saxena

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

1.51

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of where you are expecting to see data. And where you see the grayed filter?

**Comment by Jenefer-Monroe** [comment]
Please also validate that you have set up the [audit log solution](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)

**Comment by Jenefer-Monroe** [comment]
As a means to show us that you have set this up correctly, please share a screenshot like this showing the connector is in place:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

And a picture like this showing the flows are running successfully:
![image](https://user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png)

**Comment by FacilyDev** [comment]
Hi Jennefer,
Attaching myself to this issue. We have Audit Logs Flows running correctly. It's visible in Power Platform Admin View (Audit Logs) but when trying to see via [Related] for the specific App it doesn't show any data -- please see screenshots below. Is there some foreign key issue, connecting Apps with Audit logs tables?
![image](https://user-images.githubusercontent.com/28065097/161588283-4efb29e1-bd0c-42a6-aac1-7abd6da165d1.png)

(believe me it's the same App with App ID from previous screenshot)
![image](https://user-images.githubusercontent.com/28065097/161588413-cf2e4c9d-f349-4612-b1fc-2ebf0af15d02.png)

Kind regards,
Adrian

**Comment by Jenefer-Monroe** [comment]
@FacilyDev yes that is a text string and not a lookup. I'm not sure why it was done that way but you will not be able to use "related" here. 
I think your issue is unrelated to the original posters though, so if you could please let me know if my response is clear enough, then I'll remove these comments so as not to confuse the issue for that person. 
Thanks!

**Comment by FacilyDev** [comment]
@Jenefer-Monroe thanks for a quick answer. Yes you are right it's sort of not for this issue, however, you provided clear guidance on how to enable Audit Logs in CoE Starter Kit. 
Frankly speaking, your answer quite surprised me as I would assume that in Admin View the ability to jump from the specific App to the details on who/when launched it (especially that data is there) should be the obvious feature... Anyway, thanks for your continuous support and improving the kit. Watching its development over just couple of months (!) is just mind-boggling. Great work!!!

**Comment by Jenefer-Monroe** [comment]
Thanks for validating. I'll hide these comments now to keep Abishek's issue clean to his issue. 
Thanks for using CoE

**Comment by Jenefer-Monroe** [comment]
closing out this issue as poster answered in #2354
