### ISSUE TITLE
[CoE Starter Kit - BUG] Set up - Admin - Command Center App documentation misleading

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#2341]
### Describe the issue

In the Set up documentation here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables

the variable for the Command Center Application Client ID states: Leave empty if you're using Azure Key Vault to store your client ID and secret, however the only variable to use Azure Key Vault stores the Application Client Secret and does not reference the Application Client ID, therefore this environment variable value must be populated in order to work.

![image](https://user-images.githubusercontent.com/17124284/161065372-8bfca5ac-d1f6-4dee-abc4-78eec5d94b70.png)

### Expected Behavior

Populate the Application Client ID value or create another environment variable to store the Client ID.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Command Center

**Comment by Jenefer-Monroe** [comment]
Can you please confirm for us the following for Azure Key Vault usage? 

1) You need need to enter both the azure key and the client id (from from app registration)
1) You need to enter these after you install core. Entering these before install breaks install. 

Thank you for your help getting this clean

**Comment by medicineshow** [comment]
Not sure we quite understand your question, however:
I can confirm that you need to configure the Command Center - Application Client ID variable with the application client ID from the [Create an Azure AD app registration to connect to Microsoft Graph](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-an-azure-ad-app-registration-to-connect-to-microsoft-graph) step.

You then need to configure the Command Center - Client Azure Secret variable with the Azure Key Vault reference for the application client secret from the [Create an Azure AD app registration to connect to Microsoft Graph](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-an-azure-ad-app-registration-to-connect-to-microsoft-graph) step.

We do not know about entering these details before Core is installed.

**Comment by VeerasekarVM** [comment]
I have created a new 'Azure Key vault secret' but what should i enter in the CoE 'Command Center - Client Azure Secret' value? is it the Azure Key Vault secret's 'Secret Identifier'?

**Comment by manuelap-msft** [comment]
Yes, it's the Identifier of the secret from Azure Key Vault. We found some customers had issues specifying it during import, and found it easier to update it afterwards by:

1. Go to make.powerapps.com > select CoE environment
2. Select Solution
3. Select Default solution
4. Filter to show Environment Variables
5. Open the Command Center - Client Azure Secret environment variable to enter the new current value > you should be presented with a screen to link to your Azure Subscription, Resource Group etc.
