### ISSUE TITLE
[CoE Starter Kit - BUG] No Name or Id in Environment Expiration Notice

### ISSUE THREAD

**Issue by rooobeert** [microsoft/coe-starter-kit#2347]
### Describe the issue

Hi all! 

I created a sample Environment Request in the app with an automatic expiration date. 
Then I received a notice that my Environment is about to expire. All good, but it didn´t show any name or id for me here. 

![image](https://user-images.githubusercontent.com/87785803/161211255-3330e32f-3539-4770-a151-fd7d18c7482f.png)

We checked the flow just to make sure and is was also not filled inside the flow.

![image](https://user-images.githubusercontent.com/87785803/161211057-81a1bad0-6e11-410f-a779-4b7fa40742d0.png)

How can it be fixed?

Thanks

### Expected Behavior

All Names and Ids are shown in the expiration mail.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Env Request | Cleanup Environments

### Steps To Reproduce

Create an Environment with automatic deletion after thirty days, approve it and wait for the expiration mail.

**Comment by BhargavPrasadGorakanti** [comment]
Hi @denisem-msft, just wanted to check if this bug fix is added to the backlog for a future release? It looks like column names referred from Environment Creation Requests row need to be changed to coe_envdisplayname and coe_environment_value. We have made the changes in an unmanaged layer as of now.

**Comment by denisem-msft** [comment]
I am not able to reproduce this. The "Environment name" in the email is referencing the EnvironmentCreationRequest's coe_envdisplayname field, which is a required field in the request form. The "Environment Id" field is populated using the LookUp value of the related Environment, which is populated upon successful completion of the "Create Approved Environment flow". If the environment was created with the request form and the flow ran without errors, these fields should be populated.

@rooobeert can you please confirm whether the Environment Creation Request record has the coe_envdisplayname and coe_environment_value fields are populated with values when the Environment is created (e.g., when the "Env Request | Create Approved Environment" flow completes)?

@BhargavPrasadGorakanti those fields are the ones referenced in the warning email sent out in "Env Request | Cleanup Environments". Which fields are you seeing in the version you're using?

    Environment name: @{items('Apply_to_each_Expiring_Environment_Request')?['coe_envdisplayname']}
    Environment Id: @{items('Apply_to_each_Expiring_Environment_Request')?['coe_environment_value']}
    Expiration date: @{items('Apply_to_each_Expiring_Environment_Request')?['coe_expirationdate']}

**Comment by denisem-msft** [comment]
@rooobeert @BhargavPrasadGorakanti I still cannot reproduce this and can validate the emails are sending out the correct fields.

![image](https://user-images.githubusercontent.com/43950360/192053951-0576d8d3-a1fd-428e-9b8f-4d8f2517bd8d.png)

Please reopen if you are still seeing this issue.
