### ISSUE TITLE
[CoE Starter Kit - BUG] -ALM

### ISSUE THREAD

**Issue by dknamo** [microsoft/coe-starter-kit#2348]
### Describe the issue

Hi
We have been installing COE and using it for over 1 year and would also like to start using ALM.
in our business, each team has its own (Dev-test-prod) environment.
and we do not have a common environment.

can ALM be set up for each team in our Center of Excellence Environment?
I mean we need to set ALM to 4 X (Dev-test-prod)

### Expected Behavior

Hi
We have been installing COE and using it for over 1 year and would also like to start using ALM.
in our business, each team has its own (Dev-test-prod) environment.
and we do not have a common environment.

can ALM be set up for each team in our Center of Excellence Environment?
I mean we need to set ALM to 4 X (Dev-test-prod)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

ALM Accelerator

**Comment by mikefactorial** [comment]
Hey @dknamo this is possible using the ALM Accelerator for Power Platform. Take a look at the docs on deployment profiles and feel free to respond with any quesions. https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles

**Comment by mikefactorial** [comment]
Closing this for now as there hasn't been any follow up. Feel free to open a new issue if you have further questions
