### ISSUE TITLE
[CoE Starter Kit - QUESTION] Definition of orphaned apps

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2353]
### What is your question?

How can an application or flow become orphaned? A thousand thanks

**Comment by Jenefer-Monroe** [comment]
This field is based off the status of the App Owner in the AD, checked via the O365 Users connector. 
Currently we update it when an application is touched in the inventory or via the following clean up flow in Core: **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_**

Hope that helps!

**Comment by JackSocini** [comment]
I probably misspelled the question. How is it possible for an app or flow to become orphaned?
Does the owner have to leave the company? Should it be deleted from the Active directory?

I need to understand these cases.

A thousand thanks

**Comment by Jenefer-Monroe** [comment]
Correct. When the person no longer resolves in the AD vie the O365 Users connector. This happens if they are deleted from Azure. 
![image](https://user-images.githubusercontent.com/89584709/161289342-a0f9ad27-f1fa-4a38-af98-a27a6c2b1811.png)
