### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION: Flows ran successfully but data is not populating properly in the reports. How data is flowing in App Shares & App Usage.

### ISSUE THREAD

**Issue by AbhishekSaxena123** [microsoft/coe-starter-kit#2354]
### What is your question?

Reports Table data is not coming properly. Fields like sessions, unique users, group shared data is not coming, though we have number of shares. We have also crawled M365 compliance Audit data. We have app shares of last 12 months. But data is showing just for few days, latest dates data mostly. Which flow is responsible for that, how can we get the data of last 1 year in the tables. Are there any additional dependencies.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

1.51

**Comment by Jenefer-Monroe** [comment]
We do not have a solution for you to get the data backwards. The audit logs collect only from the point of turning them on forward. You can probably go and manually download the data from the compliance center and upload it to the audit log table, as a solution to look backwards for whatever amount of time they store them (a month I think).

It sounds like the audit logs arent running for you either, but you already have #2331 posted for that. And we have an active question for you there that needs answered for us to assist.

**Comment by AbhishekSaxena123** [comment]
Hi Jenefer, 
We have not been looking to update any old data to be shown before turning the Audit Logs. We are trying to get the data after the audit logs has been turned on. 
Also based on the questions which has been asked in #2331 I have attached the screenshot regarding the same.

**Comment by AbhishekSaxena123** [comment]
![Sync Audit Logs Flow](https://user-images.githubusercontent.com/98746546/161763281-40dd6fc4-92ba-42de-a3b8-e87d6a8828ad.PNG)
![Office365ManagementAPI](https://user-images.githubusercontent.com/98746546/161763297-d3a4d8ea-c151-4892-9228-95ef7ccf4b25.PNG)

**Comment by Jenefer-Monroe** [comment]
Closing out as issue seems to be resolved.
