### ISSUE TITLE
[CoE Starter Kit - Core Components] Welcome Email sent to users which are not makers of an app/flow

### ISSUE THREAD

**Issue by A-Demir-ilx** [microsoft/coe-starter-kit#2358]
### What is your question?

Hello,

I see in the "Admin | Welcome Email v3" flow that an email is sent as soon as a record is created in the "Maker" table. It strikes me that some users have not created an app/flow and they still receive the welcome email.

Have the suspicion that you are in the "Maker" table as soon as an app/flow is shared with you. Is this correct?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2022

### What app or flow are you having the issue with?

Admin | Welcome Email v3

**Comment by Jenefer-Monroe** [comment]
No they will get added to the **_Power Platform User_** table if they are a viewer / editor. But if they get assigned to owner role then they will be added to **_Maker_** table

**Comment by A-Demir-ilx** [comment]
Thank you!
