### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Dashboard Cloud Flow count mismatch

### ISSUE THREAD

**Issue by alvarezskinner** [microsoft/coe-starter-kit#2361]
### Describe the issue

WIthin the Power BI Reports, in the Flows page, the admin_flowdeleted flag is set to false for the Total # of cloud flows at the top, but this filter is missing on the table view - that means the table view also counts deleted flows.

### Expected Behavior

Table and top summary to show the exact number of total Flows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

CoE Dashboard Power BI

### Steps To Reproduce

Create 2 Flows and let the inventory sync happen.
Delete 1 of the Flows and again have the inventory sync done again.
Head to the CoE Dashboard in Power BI and compare number of Cloud Flows from the table and the top summary, numbers should be different.

**Comment by manuelap-msft** [comment]
Additional info:

This visual is correct: (Total # at the top)
![image](https://user-images.githubusercontent.com/55705669/161559083-e90d14ee-2ffe-4e8c-8dc9-27f18eabbb80.png)

This table is incorrect and includes deleted flows:
![image](https://user-images.githubusercontent.com/55705669/161559156-9b58356f-4cbc-4e22-91b4-78ad740b7937.png)

**Comment by Jenefer-Monroe** [comment]
will target for May

**Comment by Jenefer-Monroe** [comment]
local fixed for May
![image](https://user-images.githubusercontent.com/89584709/165388901-7b16c4a0-8fa8-4928-8831-087d507dd21e.png)
