### ISSUE TITLE
[CoE Starter Kit - QUESTION] Share Coe toolkit with Makers process

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2369]
### What is your question?

Hi, what is the process of sharing the Coe Toolkit apps with the Makers?

**Comment by Jenefer-Monroe** [comment]
Here is some documentation we produced on how to share apps with your makers
[Share an app from a production environment](https://docs.microsoft.com/power-platform/guidance/coe/faq#share-an-app-from-a-production-environment)

Hope that helps!

**Comment by JackSocini** [comment]
Sorry but I don't find what I'm searching for.. I need the step for a client to undrstand how to share all coe toolkit app for makers easly. Is there a documentation that tell me that?

Thanks

**Comment by Jenefer-Monroe** [comment]
That documentation shows how to share an individual app. Can you explain what information is missing? What part still isn't clear?

**Comment by JackSocini** [comment]
I'll give you an example: I have to add a maker to the coe applications present in two different solutions. To do this, should I create an AD group and add that to the app or make the makers one by one?

**Comment by Jenefer-Monroe** [comment]
You should already have a group created for the makers per this [pre-work step](https://docs.microsoft.com/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users). 
You will want this group in the **_Power Platform Maker Microsoft 365 Group_** env var per [Inventory env vars](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values)
This will let the **_Admin | Add Maker to Group_** flow add new makers to that group. 

Then you can just add that group to each app. Ensuring you assign them the **_Power Platform Maker SR_** as outlined in that first document.
