### ISSUE TITLE
[CoE Starter Kit - BUG] Business process flow error first step - Power Platform Admin View

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2371]
### Describe the issue

Hello, when I try to comoplete the first step I riceve this error.

Thanks

![error](https://user-images.githubusercontent.com/101250592/161796674-42387f16-f3d9-4d0a-b080-d8b5079ab41d.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

1. Open the Power Platform Admin View app
2. Go to Power Apps App tab
3. Select an app
4. Try to complete the first step of business process flow

**Comment by Jenefer-Monroe** [comment]
This needs to be Yes before you can move forward, which means having all the things (ex business justification) set using the Developer Compliance Center app

![image](https://user-images.githubusercontent.com/89584709/161827183-36fc894c-978a-4bc6-91e4-15f5688414ef.png)

![image](https://user-images.githubusercontent.com/89584709/161829203-9f88c3c5-0864-4570-8f07-8787c954d2a7.png)
