### ISSUE TITLE
[CoE Starter Kit - BUG] Solution "Center of Excellence - Nurture Components" failed to import:

### ISSUE THREAD

**Issue by Dhruvinshah16** [microsoft/coe-starter-kit#2376]
### Describe the issue

When I tried to Import the solution for Nurture Component, it is giving me this error
Solution "Center of Excellence - Nurture Components" failed to import:

When I downloaded log, it is showing below error!
<img width="583" alt="image" src="https://user-images.githubusercontent.com/41663430/161944232-f275fadb-2b53-4837-8cf6-08b59d89c89c.png">

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Entire Solution

**Comment by manuelap-msft** [comment]
Hello,

this could indicate a temporary service issue, have you tried again later? If you check the Solution History tab, does it give you more details on the failure there? 

Thank you
Manuela

**Comment by Dhruvinshah16** [comment]
Still It is not working!
Solution history not giving me any extra information!
<img width="707" alt="image" src="https://user-images.githubusercontent.com/41663430/162004977-e431938e-2ad0-476b-ac01-0f148cbbb767.png">

**Comment by manuelap-msft** [comment]
The solution history isn't showing the Nurture solution being imported, so the failure may be occuring before import. Can you share a couple of screenshots of where you see the error message? There may be a failure before importing.

**Comment by Dhruvinshah16** [comment]
Yes, It is the error before Import!
I just tried again now! & I'm successfully able to import it! Maybe it was service Issue! Thanks @manuelap-msft  for your continuous help!!

**Comment by manuelap-msft** [comment]
Of course, thank you for confirming it's working now and sorry you experienced issues a few times before it worked!

I'll close this issue now but please feel free to raise a new one if you have other problems with the CoE kit!
