### ISSUE TITLE
Issue: Flow "DLP Editor>Parse impacted resources into CSV" Fails 

### ISSUE THREAD

**Issue by kashanico** [microsoft/coe-starter-kit#2386]
### Describe the issue

The flow DLP Editor>Parse impacted resources into CSV Fails with error:
admin_customizedemail With Id = b0f83a79-fc63-ec11-8f8f-000d3a13d289 Does Not Exist

Looking at past bugs I can confirm that the flow
Admin | Sync Template v3 Configure Emails
Has ran successfully and that I get other admin emails. 

The flow DLP Editor > Parse impacted resources into CSV is on as well.

Looking at the flow Admin | Sync Template v3 Configure Emails or the "Customized Email" table it updates I see no reference to the DLP Editor to send Impacted Objects.

![image](https://user-images.githubusercontent.com/64927104/162090539-35bbf7ab-7bb7-4bf7-b24d-7de0e2272cca.png)
![image](https://user-images.githubusercontent.com/64927104/162090614-9b776439-3032-4a3d-bc80-0047034bdbbd.png)
![image](https://user-images.githubusercontent.com/64927104/162090520-31c1cb83-d9c7-46ec-9d47-e477f7b5bf8a.png)

### Expected Behavior

When clicking the button in the DLP editor it sends me an email with the CSV attached.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

DLP Editor > Parse impacted resources into CSV

### Steps To Reproduce

Click the "Export impacted apps and flows to CSV" button in the DLP Editor app

**Comment by manuelap-msft** [comment]
Hello,

first of all let me just say a big thank you for checking past issues and doing such thorough investigation - that makes our triage so much easier, and we really appreciate you taking the time there!

The very last scope of **Admin | Sync Template v3 Configure Emails** sets up this email:
![image](https://user-images.githubusercontent.com/55705669/162155399-d8deb3a8-2e03-4e71-b687-e9f595fc4afb.png)

1. Can you re-run the flow and see if it picks it up then? This email is a newer addition and if you didn't run the flow after the last upgrade, it may not have picked it up.
2. Can you check if you have unmanaged layers on this flow by selecting ... > See solution layers. If you do have unmanaged layers that would have prevented you from receiving an update to this flow with the last upgrade.
![image](https://user-images.githubusercontent.com/55705669/162155961-64cf2e17-f53c-4d3a-90b6-6c3ffe88eb1c.png)

Thank you
Manuela

**Comment by kashanico** [comment]
It was the unmanaged layer on the **Admin | Sync Template v3 Configure Emails**. It was on the previous version that did not have the last loop for **Send Impacted Objects**. Thanks for the tip.

I had not edited this Flow previously. Do you know why Flows get unmanaged layers when they haven't been manually modified? 
More importantly, is there a way to know which Flows have an unmanaged layer after an upgrade? This has bit us in the past.

Thanks for your help.

**Comment by kashanico** [comment]
Ah great, thank you. You have been very helpful.
I'll be closing this thread then.
