### ISSUE TITLE
[CoE Starter Kit - QUESTION] Global variable Command Center

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2389]
### What is your question?

What this variable used for? Command Center - Client Azure Secret

Thanks

![variable](https://user-images.githubusercontent.com/101250592/162173876-b10fadfa-6da0-418b-b5dc-a7e9fdfd50b2.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.36

**Comment by manuelap-msft** [comment]
See our documentation here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-the-admin---command-center-app 

Please let us know if the documentation doesn't sufficiently answer your question, so we can update the docs.
