### ISSUE TITLE
[CoE Starter Kit - BUG] Clean up and Delete flow is failing

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2394]
### Describe the issue

Dear Team,

This is regarding one of the CoE Archival flows is failing since last one week with the following error:

![image](https://user-images.githubusercontent.com/98403757/162204415-4134a95a-a319-4648-afa7-d8aa9b9ead0e.png)

the flow is being run by the Power Platform Administrator (Service Account)

Would you please help resolving the same?

### Expected Behavior

Flow should succefully archive and delete an app

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Archive and Clean Up v2 (Clean Up and Delete)

### Steps To Reproduce

Check Run history

### Anything else?

No

**Comment by Jenefer-Monroe** [comment]
Is there a fuller error message that comes with that failure? And if so can you please share it? 

Can you please check the following for this repro? 

- in the [product admin pages](https://admin.powerplatform.microsoft.com/environments) for this flow's environment
Go to Settings > Users + permissions > Users > Find the identity running Clean up and Delete > Click their name
What role does the user have in the environment? 
![image](https://user-images.githubusercontent.com/89584709/162211911-c5ab0c3a-b9a3-47e1-a371-8f51d4ddee9f.png)

- back on the main admin page for this environment > Resources > Flows
Does the flow still exist there? 

- in the Set Flow Permissions app, find this flow 
Does it have a warning triangle? (this means its a solution flow)
![image](https://user-images.githubusercontent.com/89584709/162213456-c97b07ca-8b0b-407c-91f2-828574e5500d.png)
Click on the flow name and try to browse to the flow via Flow Settings in the ribbon, what happens? 
![image](https://user-images.githubusercontent.com/89584709/162213746-ee5ad0f0-9c58-4b61-bf7c-eed0016b91d3.png)

**Comment by tomsinsight** [comment]
No full error message - It only shows "Flow run failed" at top bar and "Forbidden" at action.

User running the flow is assigned with the following roles in the environment:
![image](https://user-images.githubusercontent.com/98403757/162422393-12823fa9-a963-41a7-b279-21b036dab69b.png)

Yes, flow exists in the environment and enabled.

Yes, it has a warning sign in the set flow permissions app:
![image](https://user-images.githubusercontent.com/98403757/162423184-424cfdac-2863-470f-af94-32560679a758.png)

When I click on "Flow Settings" button, it directs me to the same selected flow's details page.

What should be done to resolve this error?

**Comment by Jenefer-Monroe** [comment]
And the questions above are all for the identity running the flow?
is that identity assigned PPAdmin via PIM or directly?  
Is that the identity used to create that connection? 

I've never seem this happen before with the permissions set correctly. So you might just want to delete manually since you can get there. And then see if this ever repros again.

**Comment by tomsinsight** [comment]
And the questions above are all for the identity running the flow? **-Yes**
is that identity assigned PPAdmin via PIM or directly?**-Directly, What is PIM?**
Is that the identity used to create that connection?**-Yes**

I've never seem this happen before with the permissions set correctly. So you might just want to delete manually since you can get there. And then see if this ever repros again.**-It's happening continuously everyday since last one week, and there are plenty of apps to be removed, so removing them manually might not resolve the issue, at the same time this is happening since last one week, therefore It will continue in future too**

**Comment by Jenefer-Monroe** [comment]
The starter kit is not a supported product, so support will not assist with issues in the kit. 

Lets take a step back here though, I got confused and started asking questions about flows and your picture is an app. 
Is it a flow or an app that is failing? Some of both?

**Comment by tomsinsight** [comment]
Hello Jennifer,

Sure, Thank you for your clarification, It's a flow "Archive and Clean Up v2 (Clean Up and Delete)" that is failing to remove an app from the environment.

I hope that's helpful.

Thanks,

**Comment by Jenefer-Monroe** [comment]
And how many apps are failing?

**Comment by tomsinsight** [comment]
What was this in reference to then? - This is about your earlier ask "in the Set Flow Permissions app, find this flow
Does it have a warning triangle? (this means its a solution flow)"

And how many apps are failing? - all apps that are coming into the loop.

**Comment by Jenefer-Monroe** [comment]
But you said above this is failing for apps, sounds now like its failing for all apps and also flows? 
![image](https://user-images.githubusercontent.com/89584709/163018046-c7bdf0e7-b377-4184-bd66-cd15bb9a3b43.png)

Regardless, the fact that this is failing for all calls means there is something wrong for you that is not generalized to other users as no one else repros. There must be something wrong with your user account or your setup.

Here is what I suggest you do. 
Using the account of the CoE, create a new flow with only the call to Remove App as Admin. Put your GUIDs in there and run. 
![image](https://user-images.githubusercontent.com/89584709/163018676-1520717a-ed27-4816-928e-843300998144.png)

Bring that failure to product support.

**Comment by tomsinsight** [comment]
Tried the step as suggested, this app has been created by other user however when CoE account runs it, it throws following error:
![image](https://user-images.githubusercontent.com/98403757/163153266-df9a9585-9c23-4ff5-bd80-de4d2c53a174.png)

What should I do next?

**Comment by tomsinsight** [comment]
Apparently, these apps are coming from the CoE managed solution where it seems no one would have access to delete? until we uninstall the managed solution itself which we can not do and not intended to do.

Quick question - Is there any possibility to exclude app/flows to be archived which are in CoE environments? Can we do that?

**Comment by Jenefer-Monroe** [comment]
We are able to delete apps in solutions via Remove App as Admin. I have just validated this again in our test tenant.
It could be that you dont have the PPAdmin permissions correct or permanent, or that your apps are somehow in a bad state (which is what it sounds like). I'm afraid we cannot help with either of those situations. 

You can excuse apps and flows from archival, and entire environments. . Please see [our documentation](https://docs.microsoft.com/power-platform/guidance/coe/setup-archive-components#exempt-environments-from-the-archive-process)

**Comment by tomsinsight** [comment]
Thank you for sharing the documentation, very useful!

I think the apps are in bad state as they come from the managed solution - we will manage it how to resolve them.

Thank you again for your time and clarification!

**Comment by Jenefer-Monroe** [comment]
You are welcome. I'll go ahead and close this issue then. Thanks for using CoE
