### ISSUE TITLE
[CoE Starter Kit - QUESTION] Question about Cleanup Old Objects App

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2395]
### What is your question?

The Cleanup Old Objects App is an app for maker and admin or only for admin?

Thanks

### What solution are you experiencing the issue with?

Governance

### What app or flow are you having the issue with?

Cleanup Old Objects App

**Comment by Jenefer-Monroe** [comment]
Please read about the apps here [Cleanup Old Objects App](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#cleanup-old-objects-app). This app is intended for Makers and their managers.

**Comment by JackSocini** [comment]
I think this application is not described in the best way... The maker part is not mentioned..
Or did I misread the documentation?

Thanks

**Comment by Jenefer-Monroe** [comment]
Please let me know if you have further questions.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
