### ISSUE TITLE
[ALM Accelerator - BUG]: Update Deployment Setting

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#2396]
### Describe the issue

Update deployment setting fails:

"[{\"EnvironmentUrl\":\"[https://dte-ea-prod.crm.dynamics.com/\",\"UserSettingId\":[]},{\"EnvironmentUrl\":\"https://dte-ea-prod.crm.dynamics.com/\",\"UserSettingId\":[]},{\"EnvironmentUrl\":\"https://dte-ea-prod.crm.dynamics.com/\",\"UserSettingId\":[]}]"](https://dte-ea-prod.crm.dynamics.com//%22,/%22UserSettingId/%22:[]%7D,%7B/%22EnvironmentUrl/%22:/%22https://dte-ea-prod.crm.dynamics.com//%22,/%22UserSettingId/%22:[]%7D,%7B/%22EnvironmentUrl/%22:/%22https://dte-ea-prod.crm.dynamics.com//%22,/%22UserSettingId/%22:[]%7D]%22)
Update Deployment Settings
Remove-Item : Cannot find path 'D:\a\1\s\coe-starterkit-azdo\eDVIR\config' because it does not exist.
At D:\a\1\PipelineUtils\PowerShell\update-deployment-settings.ps1:316 char:2
+     Remove-Item -Path "$buildSourceDirectory\$repo\$solutionName\conf ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\a\1\s\coe-st...do\eDVIR\config:String) [Remove-Item], ItemNotFoundEx 
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
##[error]PowerShell exited with code '1'.

![image](https://user-images.githubusercontent.com/12697408/162227404-6d94c586-fe4c-48c9-9740-cdfd0b8cadf4.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April Release

**Comment by mikefactorial** [comment]
@gerald560 thanks for reporting this. Let me look into a fix.

**Comment by mikefactorial** [comment]
@gerald560 this is bug. I've created a PR to address this issue here https://github.com/microsoft/coe-alm-accelerator-templates/pull/125. You should be able to take the latest from this branch to fix this issue https://github.com/microsoft/coe-alm-accelerator-templates/tree/mochs-aa4pp-2396

**Comment by mikefactorial** [comment]
The PR has been merged https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/PowerShell/update-deployment-settings.ps1
