### ISSUE TITLE
[CoE Starter Kit - Feature]: "Last run" data of Cloud Flows.

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#2399]
### Describe the solution you'd like

It would possible to add to inventory the "Last Run" data of the cloud flows?
This information is available in the new analytics of the PPAC:
![image](https://user-images.githubusercontent.com/57954993/162248990-a7642afa-b486-44be-a86d-a866bb1f804f.png)

**Comment by manuelap-msft** [comment]
Hello,

we're tracking this as #433. The information in PPAC is not available via API or other data source that the CoE kit can consume, so we can not leverage this specific data unfortunately. Once data is available to us in a consumable way, we'll address this gap.

Closing this out as we are tracking an issue for this already.

Thank you

Manuela
