### ISSUE TITLE
[ALM Accelerator - BUG]: Con Ref not being set properly failing to turn on flows

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#2401]
### Describe the issue

When setting the con ref and env vars everything looks good yet when deploying 
![image](https://user-images.githubusercontent.com/12697408/162276919-91062535-df1c-4b88-9a67-11df7cce0e05.png)

we can see that by manually trying to turn it on the flow is not being recognized ... 

![image](https://user-images.githubusercontent.com/12697408/162277194-f9801c61-3e70-4afd-a20d-cbcca7df436d.png)

### Expected Behavior

Flows to be turn on with the accurate con ref

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April

**Comment by mikefactorial** [comment]
Closing this as duplicate of #2329
