### ISSUE TITLE
[CoE Starter Kit - BUG] Embedded Apps in the CoE Dashboard Environments Table Error

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#2403]
### Describe the issue

When setting up the latest Power BI dashboard embedded apps, after adding the admin_appid field the error in the visual pane is:
error getting environments
![image](https://user-images.githubusercontent.com/17124284/162281921-7adf936b-34b2-46d5-bc0c-da26475239a9.png)

This error has only occurred since updating the CoE

### Expected Behavior

After adding admin_appid to the visual pane, you can then select the environment where your app is located.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.36

### What app or flow are you having the issue with?

Power BI Dashboard Embedded Apps

**Comment by manuelap-msft** [comment]
Hello,

are you logged in to Power BI Desktop with your admin account (or with the credentials that have access to the environment and CoE apps)?

Thank you
Manuela

**Comment by medicineshow** [comment]
I am logged in with the admin account that also has access to the CoE and environment

**Comment by Jenefer-Monroe** [comment]
Hello we have seen this once before, and the issue was a product issue that repro's outside the context of the starter kit. I believe if you edit in the browser instead of the desktop it will work for you. Thats how it went when this was broken in the past.

**Comment by medicineshow** [comment]
Hi @Jenefer-Monroe . I am not sure that this is the issue as the previous dashboard template worked without issue. It is only since the update has occurred that this has  started happening. Also, I am not sure that you can open .pbit files in the browser. Happy to be corrected with that.

**Comment by medicineshow** [comment]
@Jenefer-Monroe I have just tested the following using the Power BI Desktop application:
Connected April release Power BI desktop to an environment that contains the March release Dataverse data and the table works.
![image](https://user-images.githubusercontent.com/17124284/162409727-b773d25f-f739-4692-af50-75f030550bfc.png)

The Core solution in that environment is 3.24

**Comment by Jenefer-Monroe** [comment]
Did you delete the object that was there in the PBIT and re-insert the Power App?

**Comment by medicineshow** [comment]
yes i follow the documentation instructions. Create the new pane and add the fields to the visual.

**Comment by medicineshow** [comment]
So it turns out, the conditional access policy that I recemtly enabled for the CoE Admin affects  this. Even though we have excluded Power Bi service. Once I disable MFA, I can now select the environment that contains the apps. Apologies for the incorrect bug report.

**Comment by Jenefer-Monroe** [comment]
Not a problem, we appreciate you and the great bugs you post. Thank you for following up to let us know the cause. That will help us in the future as well.

**Comment by manuelap-msft** [comment]
Hello @medicineshow,

we were also just made aware of a product bug which impacts the Power Apps visual in Power BI. This product bug impacts older versions of Power BI desktop. Customers will need to upgrade to version 2.2.19 (of the visual) which is included in latest version of Power BI desktop 2.103.881.0. 

This may also have impacted your use of the embedded app, or you may see an issue in the coming days with the visual if you're on an older version of Power BI desktop.

Just thought I'd share :)

Thank you
Manuela

**Comment by medicineshow** [comment]
Thanks @manuelap-msft . we are on the latest version
