### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Sync Template Errors for Developer Environments

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#2404]
### Describe the issue

We have just upgraded to the April release and the Admin | Sync Template flow runs for an exceptionally long time and then fails. We have disabled the delay inventory step. 
There are a total of 17 environments and the flow fails on the only four Developer environments that we have. This did not happen before the upgrade.
![image](https://user-images.githubusercontent.com/17124284/162278973-861ebe73-4492-462b-94b0-dfb950d8eb78.png)
The step is within the "Check if legacy environment" condition
The error message is: 
{
  "error": {
    "code": "0x80040217",
    "message": "admin_environment With Id = 14b548ff-3461-4169-a004-b2710f2c007e Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "7de79804-5984-ec11-8d21-0022483fc6d2",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "f01e1a87-4d95-4273-ba37-172fc840d986",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_environment With Id = 14b548ff-3461-4169-a004-b2710f2c007e Does Not Exist"
  }
}

The Child Flow "Get Maker" then fails for the four developer environments which are created by System with the error:
Could not find a property named 'SYSTEM' on type 'Microsoft.Dynamics.CRM.admin_maker'.
![image](https://user-images.githubusercontent.com/17124284/162280195-ff72eccd-2c14-4f40-a96f-e306a23b49c6.png)

### Expected Behavior

The flow used to only run for 3 - 4 minutes as this is our test tenant and only has a few environments.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.36

### What app or flow are you having the issue with?

Admin | Sync Template V3

**Comment by Jenefer-Monroe** [comment]
thank you, we are testing a hot fix for this now. Expet to deliver soon

**Comment by Jenefer-Monroe** [comment]
Fix is live. Please utilize the new Core component just released

**Comment by manuelap-msft** [comment]
Here's a direct link to the new version as well: https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-April2022/CenterofExcellenceCoreComponents_3_37_managed.zip
