### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by sandeep-mamidala** [microsoft/coe-starter-kit#2407]
### Describe the issue

Hi Team,

We observed that once if employees ignore the archival requests their managers will be notified and will be provided with the clean up old objects app link to either remind employee or reject deletion.

But how to share an clean up old objects app with manager of each employee. Do we need to manually share for each manager or any other alternate

### Expected Behavior

Expecting to automate sharing of CleanUp Old Objects app for managers

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.13

### What app or flow are you having the issue with?

CleanUp Old Objects app

**Comment by Jenefer-Monroe** [comment]
Please see #2369

**Comment by sandeep-mamidala** [comment]
Hi Issue is not sharing the app with makers but to their managers as managers will be notified and will be provided with the clean up old objects app link to either remind employee or reject deletion.
