### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power BI Dashbard, we only see CoE env

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2408]
### What is your question?

Hello, we tried to install the Power BI dashboard by inserting the link, as per documentation, of the environment where the CoE Toolkit is installed.

The result is that we only see information relating to that environment. What could be the problem?

A thousand thanks

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

Power BI Dashbard

**Comment by Jenefer-Monroe** [comment]
Please share a screenshot of what you mean and let us know which PBI you used. 
You will also need to look into the tables to validate that the sync flows populated the inventory correctly.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
