### ISSUE TITLE
ALMAcceleratorSampleSolution: Canvas app not showing environment variables after import

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#241]
If you import a Solution built off the dev branch of ALMAcceleratorSampleSolution into an environment and set values for the environment variables, then play the canvas app, you will see that it shows the default values that came from the dev environment, not the values set during import.  The only way I have been able to get those values to show from the new environment is to edit the flow, manually test the flow, then refresh the canvas app.

Researching with appropriate Power Apps / Automate teams.

**Comment by jayaroatinnovationcu** [comment]
I was going to open up a similar issue. After fixing the connection references and environment variables in my pipelines, I noticed that new Environment Variables are being transferred properly but as you mentioned the Flows keep running with the Variables from the Dev environment, even if I delete the default/current values in the Dev Environment before Importing.

**Comment by devkeydet** [comment]
This has been identified as a platform issue.  We have worked with the teams who own the fix.  Once a fix is rolled out in the platform, we will close this item.

**Comment by jenschristianschroder** [comment]
Closing this issue as the platform fix has been verified to have been rolled out in platform
