### ISSUE TITLE
[ALM Accelerator - BUG]: custom Config folder removed after commit

### ISSUE THREAD

**Issue by kallisto08** [microsoft/coe-starter-kit#2411]
### Describe the issue

We have existing config folders for each developer with the customDeploymentSettings.json & deploymentSettings.json which are setup for each developer. 

When committing using the latest (April 2022) ALM these are now removed each time.

### Expected Behavior

The directories under the config folder for each developer's own customDeploymentSettings.json & deploymentSettings.json should not be removed on a commit using the ALM Accelerator (which is the same behaviour as previous versions) 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April 2022

### Steps To Reproduce

1. Commit a solution into Azure DevOps using ALM Accelerator Canvas
2. Manually add a folder under the {solution-name}\config\{developer-name}
3. Add customDeploymentSettings.json & deploymentSettings.json files to this folder and populate with settings from developers Power Platform environment.
4. Delete solution from developers Power Platform environment
5. Use ALM Accelerator canvas app to Import solution into power platform environment
6. Open Solution and make a simple change
7. Commit Solution back into Azure DevOps into new or existing branch and you will see in DevOps that the config folder you created is now missing.

**Comment by mikefactorial** [comment]
Thanks @kallisto08! Appreciate the assistance in validating this.
