### ISSUE TITLE
[CoE Starter Kit - QUESTION] DLP policy creation

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2412]
### What is your question?

Hello, 
if I create a DLP policy with 'Exclude certain environment' scope. What appened if I create a new environment? The policy will be add to the new environment?

Thanks

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

DLP

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid we cannot scale to answering questions about the product behavior. You will need to search elsewhere online, find a partner to work with, or find a product representative / support to assist with understanding DLP behavior generally speaking. We can assist with questions / issues related to the CoE starter kit.

**Comment by last72** [comment]
Hi @JackSocini I had quick google and it seems that the policy will be added to the new environment.

Linkedin article by Amber Weise: https://www.linkedin.com/pulse/power-platform-governance-data-loss-prevention-policies-amber-weise/

> Finally, we scope out this policy to the appropriate environment(s) with the options of:
> - Add all environments (tenant-wide; all newly-created environments are added)
> - Add multiple environments
> - Exclude certain environments (all newly-created environments are added)

My understanding of the this logic is that it applies unless specified ("certain environments"). Newly created environments won't be specefied so the policy applies.
