### ISSUE TITLE
[CoE Starter Kit - BUG] compliance emails bug

### ISSUE THREAD

**Issue by AysanM365** [microsoft/coe-starter-kit#2413]
### Describe the issue

Hi,
Thank you for your help, here is the issue that our users are experiencing : 
•	a few months ago (somewhere in December 2021) I’ve started receiving emails from the Developer Compliance Center about the non-compliant Power Apps app
•	when I go to the Developer Compliance Center, I can see the app marked with yellow icon status
 
![image](https://user-images.githubusercontent.com/103069973/161832972-a7c4bc54-e26c-4b8d-aa5d-3ac8e95217cb.png)
•	after going to the Details page, I can see under App Compliance section I have not provided support details:
 
![image](https://user-images.githubusercontent.com/103069973/161833005-358b0772-2c16-45cc-8ada-19861d5c3ec4.png)
•	but that’s not true, since I have filled everything in the support details form and even uploaded attachment:
 
![image](https://user-images.githubusercontent.com/103069973/161833050-47aaf0f2-2e7c-496b-9a76-d64d6a65c167.png)

•	yet, I still receive those emails every Monday evening 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by Jenefer-Monroe** [comment]
You are on an old version of the Governance components and so it will be difficult for me to assist here. 
Note that yellow in the current version of the kit means "Submitted" so it what would be the correct state per your description. 

And I have validated that we dont resend when the fields are filled. I think you will need to upgrade before we can assist.

**Comment by AysanM365** [comment]
Hello, 
Could you please help me find the current version?
Thank you!

**Comment by AysanM365** [comment]
Thank you! I need help finding the current version on the COE, could you please help me to find which version I have? ( new to COE kit and didn't install it myself)

**Comment by Jenefer-Monroe** [comment]
Go to your CoE environment, select solutions, and you should see all the solutions and their version. 
Could you just share a screenshot so I can see what state you are in for all your solutions? 
![image](https://user-images.githubusercontent.com/89584709/162768378-12880e3d-ab13-434c-a362-3219f7983cde.png)

**Comment by AysanM365** [comment]
Thank you!
![image](https://user-images.githubusercontent.com/103069973/162805602-282c33d4-1f6f-4812-88c2-4071f540b767.png)

**Comment by Jenefer-Monroe** [comment]
Thats not as old as I thought, so hopefully upgrade will work smoothly for you.

**Comment by Jenefer-Monroe** [comment]
No I'm afraid not. We have refactored this area of the CoE. When saying its not "too old" I was just referring to the expected difficulty of upgrade. While it's too old for us to assist with upgrade, its not so old that I anticipate you hitting issues. 

Since you are new here, I should make sure you understand that the CoE Starter Kit is not a supported product, we provide assistance here based on best effort. Please see [our disclamer](https://docs.microsoft.com/power-platform/guidance/coe/overview#disclaimer). That said, we do put in a lot of effort to help customers.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for CoE starter kit team
