### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unable to build ebook

### ISSUE THREAD

**Issue by sposaro** [microsoft/coe-starter-kit#2414]
### What is your question?

Looking for more information about what tools are actually in the coe-cli.
Running into issues building the docs ebook (and can't find the full PDF anywhere).
Getting following error in powershell on clean master pull.

`PS C:\Users\franksp\Documents\GitHub\coe-starter-kit\coe-cli\docs> npm run ebook

> coe@0.0.1 ebook
> npm run diagrams & cd docs & coe ebook generate && pwsh -File ./build.ps1

> coe@0.0.1 diagrams
> node ./docs/diagrams.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module C:\Users\franksp\Documents\GitHub\coe-starter-kit\coe-cli\docs\diagrams.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
info: Checking links
pwsh is not recognized as an internal or external command,
operable program or batch file.`

### What solution are you experiencing the issue with?

Core

**Comment by mikefactorial** [comment]
Adding @Grant-Archibald-MS. The docs for the coe-cli are here https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/overview. We've moved away from the e-book functionality since we moved our docs to docs.microsoft.com and should be deprecated. The CoE CLI help documentation is here https://github.com/microsoft/coe-starter-kit/tree/main/coe-cli/docs/help

**Comment by mikefactorial** [comment]
Closing this issue for now as there's nothing more to do here. Feel free to open a new issue if you have further questions
