### ISSUE TITLE
[CoE Starter Kit - BUG] HELPER - Maker Check Flow Fail on System user

### ISSUE THREAD

**Issue by jimmo120313** [microsoft/coe-starter-kit#2420]
### Describe the issue

**HELPER - Maker Check** Power automate Flow Fail on 'System' Maker due to the new 'Scope' (early short circuit) added in front of system user check step
![image](https://user-images.githubusercontent.com/37314216/162651288-276ea48c-2199-4c2b-97be-a3719187de29.png)

### Expected Behavior

Should filter out System user or work ok with System user

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.36

### What app or flow are you having the issue with?

HELPER - Maker Check

### Steps To Reproduce

1. trigger Admin | Sync Template v3 flow
2. Flow will fail for default environment on 
![image](https://user-images.githubusercontent.com/37314216/162651725-953b492c-9624-41f2-a4de-fd79bab89e06.png)

That's when it's trying to call HELPER - Maker Check

**Comment by manuelap-msft** [comment]
I see you are on 3.36 - we unfortunately had a bug in this version, and released a hotfix the day after the release went out - version 3.37 (https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-April2022/CenterofExcellenceCoreComponents_3_37_managed.zip). You'll have to upgrade to fix this!

**Comment by Jenefer-Monroe** [comment]
closing out as duplicate, sorry for the inconvenience.
