### ISSUE TITLE
[CoE Starter Kit - Feature]: Include PowerBi Statistics

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#2424]
### Is your feature request related to a problem? Please describe.

At the moment PowerBI is not included in the Centre of Excellence Dashbord

### Describe the solution you'd like

Include PowerBI insights like the number of PowerBi licences being used and the PowerBi Adoption rate in the Centre of Excellence

### Describe alternatives you've considered

The only way to get the number of licences and the PowerBI use adoption rate is to use PowerShell.

**Comment by manuelap-msft** [comment]
Hello,

thanks for the feedback! Power BI is out of scope for the work of our team - the Power CAT team looks after Power Apps / Automate / Virtual Agents / Dataverse only, and there's a seperate Power BI CAT team (you may have seen some of their work in the Power BI guidance section: https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-adoption-roadmap-overview)

Our team is therefore not a subject matter expert when it comes to Power BI governance and administration; we did have initial conversations with the Power BI Team on them collaborating with us on the CoE Starter Kit and including Power BI elements there and although there was interest from the team, it didn't get funded for development. 

If this changes, we'll loop back here to update you but in the meantime I'll close this out.

Thank you
Manuela
