### ISSUE TITLE
[CoE Starter Kit - BUG] Having Switched on 2022 Wave 1 update - April update fails 

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#2425]
### Describe the issue

When Updating to the April release - the import appears to work, but says there have been issues.  Error File Included.

### Expected Behavior

I expected the April release to import successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

All

### Steps To Reproduce

Import Solution 3.37

### Anything else?

[Center of Excellence - Core Components_import (3).xlsx](https://github.com/microsoft/coe-starter-kit/files/8463458/Center.of.Excellence.-.Core.Components_import.3.xlsx)

**Comment by Jenefer-Monroe** [comment]
This file doesn't help with investigation. Go instead to See history, select the failure, and ge the Details and More Details from the resulting panel. 
![image](https://user-images.githubusercontent.com/89584709/162751715-4c4a2427-0a28-4ac0-80ae-54e52366a06d.png)

**Comment by NPrice99** [comment]
So 3.37 was installed successfully when the installation process tried to delete the old version (3.34) it failed due to dependencies .

![image](https://user-images.githubusercontent.com/8484048/162791402-d4338ec9-21d5-4397-9f35-5f1e3d7e8e16.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for CoE starter kit team
