### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log Components

### ISSUE THREAD

**Issue by suvernagithub** [microsoft/coe-starter-kit#2432]
### Describe the issue

We have set up audit log solution, but we are not getting audit logs for Power Automate. Also for Power Apps we see only Launch Operation. Please let us know if we are missing any steps. Followed [docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#:~:text=The%20Audit%20Log%20Sync%20flow%20connects%20to%20the,up%20the%20custom%20connector%20and%20configure%20the%20flow.)

### Expected Behavior

Audit Logs for Power Automate and Other logs for Power Apps such as Update , Published, Delete

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin- Sync Audit Logs and [Child]- Admin Sync Logs

### Steps To Reproduce

1. Import COE - core components
2. Import Audit Log components
3. Turn on Flows - Admin- Sync Audit Logs and [Child]- Admin Sync Logs
4. We see data under Power Platform Admin View APP under Audit Logs for Power Apps (only Launch operation)
5. Do not see data for Power Automate and other Power Apps operation

**Comment by Jenefer-Monroe** [comment]
Hello. App Launch is the only thing we collect data on from the Audit Logs.

**Comment by Jenefer-Monroe** [comment]
Unfortunately there is not. There is an upcoming product feature that will provide this but it will require Datalake integration

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for CoE starter kit team
