### ISSUE TITLE
[ALM Accelerator - BUG]:  Export-solution-to-Git Merge Pull Request error

### ISSUE THREAD

**Issue by Vaddeani** [microsoft/coe-starter-kit#2437]
### Describe the issue

When  I am trying to deploy solution from AA4PP App I am getting an error in export-to-git-branch Pipeline is not valid.
 The service connection does not exist or has not been authorized for use. getting an error  as there was a resource authorization issue.  

![MicrosoftTeams-image](https://user-images.githubusercontent.com/103512064/162974427-d85bdca1-797c-41d6-b707-3ba76fa34082.png)

### Expected Behavior

 Pull request should be performed successfully. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220406.1

### Steps To Reproduce

1. click on deploy solution button AA4PP App 
2. Click on processing icon, which navigates to Azure Devops where I am able to see an error.

**Comment by mikefactorial** [comment]
@Vaddeani I'm confused about the steps to reproduce and attached error message. The export pipeline should only run when you Commit the solution. It appears there is something wrong with your setup. Did you install using the coe-cli (https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/overview) or did you follow the steps in (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform)? If the latter I would double check that you followed these steps correctly https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-export-pipeline-variables-optional and https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-the-solution-build-and-deployment-pipelines

**Comment by mikefactorial** [comment]
@Vaddeani thanks for the details. It sounds like you may have accidentally associated the export pipeline with the branch policy instead of the deploy-validation-**** pipeline. https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#setting-branch-policies-for-pull-request-validation

The screenshot there is misleading as it shows the prod pipeline instead of the validation pipeline. Will need to update that screenshot

**Comment by mikefactorial** [comment]
@Vaddeani closing this out as there's been no response for several weeks. Feel free to reopen if you are still having issues or let us know if this issue is resolved
