### ISSUE TITLE
DLP Editor V2 - admin_customizedemail With Id = 8a28fcd6-2904-4956-86a9-ce11f1cf2216 Does Not Exist

### ISSUE THREAD

**Issue by Sulomania** [microsoft/coe-starter-kit#2439]
### What is your question?

Hello COE Community,

I executed the DLP Editor V2 and tried to export the CSV Document. 
I am receiving within the flow "DLP Editor>Parse impacted resources into CSV" following error:
admin_customizedemail With Id = 8a28fcd6-2904-4956-86a9-ce11f1cf2216 Does Not Exist
![image](https://user-images.githubusercontent.com/103515392/162982211-df9d6116-dfa9-49f7-a68b-8f63aaf5d2d3.png)

I read already all the other comments and executed the flows - Admin | Sync Template v3 - and - Admin | Sync Template v3 Configure Emails. Both flows does not have a unmanaged solution layer. Both flows run without any issue. 

Within the environments variables I inserted for "Admin eMail" and "Approval Admin" the powerplatform admin user mail. 
![image](https://user-images.githubusercontent.com/103515392/162983586-4ebe60f3-18b1-4fac-abdc-91d48a6e4b25.png)

Does someone have an idea

 

### What solution are you experiencing the issue with?

CSV document with the impacted apps/flows by the DLP Policy

### What solution version are you using?

April 2022

### What app or flow are you having the issue with?

DLP Editor>Parse impacted resources into CSV

**Comment by Jenefer-Monroe** [comment]
Have you localized this email in the Admin - Command Center? I ask because that is not the expected GUID for the EN-US version of the mail. 
Please go up a few steps in the failing flow, what is returned for **_List emails for preferred language_** and **_Set emailGUID to localized row_**

**Comment by Sulomania** [comment]
Thanks for your quick feedback. It is working now. I had a unmanaged layer for Admin | Sync Template v3 Configure Email. After removing that, it was working.

**Comment by manuelap-msft** [comment]
Great, thanks for confirming!
