### ISSUE TITLE
[CoE Starter Kit - App Shares only for canvas apps - not model-driven apps]

### ISSUE THREAD

**Issue by LilianThomsen** [microsoft/coe-starter-kit#2445]
### What is your question?

Does the CoE kit only show apps shares for canvas apps, not for model-driven apps?? Is that intended behaviour or is something wrong in our setup?

![image](https://user-images.githubusercontent.com/103517574/162990264-21a84529-d3e3-4269-a7bb-f26169d3a75c.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2022

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

**Comment by LilianThomsen** [comment]
Any chance this will change in the future?

**Comment by Jenefer-Monroe** [comment]
Unfortunately we can only surface the information to which we have access. There is someone on the team attempting to get us SR information, but that woudl need to be manually mapped to the MDA as the permissions for such an app are very complex.

**Comment by A-Demir-ilx** [comment]
@Jenefer-Monroe Is it also in the roadmap to see shared totals for a Cloud flow?

**Comment by Jenefer-Monroe** [comment]
Yes it is in our backlog. Please see https://github.com/microsoft/coe-starter-kit/issues/1083

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit
