### ISSUE TITLE
[CoE Starter Kit - App last launched only registered for canvas apps?]

### ISSUE THREAD

**Issue by LilianThomsen** [microsoft/coe-starter-kit#2446]
### What is your question?

It seems that "app last launched" is only registered for canvas apps. Is that expected behaviour or is something wrong with our setup?

![image](https://user-images.githubusercontent.com/103517574/162991617-b09279cb-a03f-4756-8ebc-e2a0ae917fcc.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2022

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by LilianThomsen** [comment]
Are there any plans to include launch of model-driven apps?

**Comment by LilianThomsen** [comment]
And is it possible to find an overview in the documentation on which data is only available for canvas apps and not model-driven apps? It's really important to know what we can expect to see in the coe kit when we are utilizing both sides of the power apps.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit
