### ISSUE TITLE
Env Request | Create Approved Environment fails: Resource not found for the segment

### ISSUE THREAD

**Issue by PowerPlatform-Admin** [microsoft/coe-starter-kit#2451]
### Describe the issue

Hi, We are facing a problem for setting up the environment request components. We were using the Feb release, but even after updating to the April release we still have the same problem. here please find the issue details:
- Component Name: Environment Request Components
- Issue:  An error encountered in COE environment creation. The flow “Env Request | Create Approved Environment” failed while updating the environment request.
- Steps to re-produce error:
1. Create environment request by using the app “Maker - Environment Request”. When we click save a record is added to Environment Creation Request
![01](https://user-images.githubusercontent.com/103178213/163109978-b4ee6b6e-768a-416d-8d43-046a43771278.png)
2. Admins of the COE environment will open the app “Admin - Environment Request” and approve the environment request.
![02](https://user-images.githubusercontent.com/103178213/163110104-10684d14-90b1-48d1-9f19-3474d3300b10.png)
3.	The flow “Env Request | Create Approved Environment” triggers to create environment. 
•        After environment approval, the flow create environment, add admins, apply security role if any etc…
•        After creating the environment, a record is added to the Environment table.
•        Update Environment Creation Request table row with status as “Completed” and Environment filed value with “Environment” table row details.
•        Apply DLP policies (calls DLP policy child row)
•        Send emails to admin etc.
4. This flow is failing at the time of updating the environment request record as “Live”. Please refer below screenshot.
Error message: Resource not found for the segment '88888888-8888-8888-8888-888888888888'. ( I masked the numbers)
![03](https://user-images.githubusercontent.com/103178213/163110380-4bc580f4-44ca-4088-901e-1cba21e6429c.png)

![04](https://user-images.githubusercontent.com/103178213/163110452-ed5577e5-f0cc-42d2-bff1-b9ae7b595488.png)
Reason for the issue: 
The resource/row Id “88888888-8888-8888-8888-888888888888'” of Environment table not able to link up with “Environment Creation Request” record. 
Any advice is appreciated.
Thank you

Best regards
Hamed

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.36

### What app or flow are you having the issue with?

Env Request | Create Approved Environment

### Steps To Reproduce

1. Create environment request by using the app “Maker - Environment Request”. When we click save a record is added to Environment Creation Request
2. Admins of the COE environment will open the app “Admin - Environment Request” and approve the environment request.
3.	The flow “Env Request | Create Approved Environment” triggers to create environment. 
•        After environment approval, the flow create environment, add admins, apply security role if any etc…
•        After creating the environment, a record is added to the Environment table.
•        Update Environment Creation Request table row with status as “Completed” and Environment filed value with “Environment” table row details.
•        Apply DLP policies (calls DLP policy child row)
•        Send emails to admin etc.
4. This flow is failing at the time of updating the environment request record as “Live”. Please refer below screenshot.
Error message: Resource not found for the segment '88888888-8888-8888-8888-888888888888'. ( I masked the numbers
![01](https://user-images.githubusercontent.com/103178213/163111224-b35bb6fa-38a8-4077-a77f-f6b32f7ab5cf.png)
![02](https://user-images.githubusercontent.com/103178213/163111229-c1baa37a-9948-4898-b5e0-89aa38cae829.png)
![03](https://user-images.githubusercontent.com/103178213/163111230-d237389e-2bbf-477b-8545-998743028723.png)
![04](https://user-images.githubusercontent.com/103178213/163111231-20d4aa10-f757-43c7-92c4-add5e976992e.png)
)

**Comment by denisem-msft** [comment]
@PowerPlatform-Admin This should be fixed in the latest release, can you please confirm if you're still getting this issue after updating the core solution?
