### ISSUE TITLE
[CoE Starter Kit - Feature]: Get Flow State when changed

### ISSUE THREAD

**Issue by Sani1991** [microsoft/coe-starter-kit#2456]
### Is your feature request related to a problem? Please describe.

When a non-solution aware flow is changing its status (for example from **Started** to **Stopped** or **Suspended** ) it's not considered as a flow modification. Meaning that the last modified date for the flow is not getting changed (it's only getting changed in solution-aware flows when disabling, enabling the flow state).

As the last modified date is not getting changed for non-solution aware flows, the **Admin | Sync Template v3 (Flows)** does not pick up the modification and therefore does not update the flow state in the dataverse Flow table record.

The only possibility right now is to switch the "Fullinventory" ENV variable to true => as we have several thousand flows in different Environments, there are too many API calls happening and we cannot switch full invetory to true by default.

### Describe the solution you'd like

Please see the screenshot below. The **Admin | Sync Template v3 (Flows)** Flow should be changed so that it compares the actual state of a flow to the current state in the Flows table record. It does not have to be 1:1 as proposed, it could also be done by changing the NO path in the condition **Only proceed if changed since last update in CoE or FullInventory** => add a new condition into the NO path which is comparing the actual state of the flow (by using the power automate management connector) vs the state of the flow in the Flows Dataverse Table.

### Additional context?

![Admin - Sync Template v3 (Flows) - Change Request](https://user-images.githubusercontent.com/90025284/163198274-440b25ba-3f8a-4431-a165-f7b7b0b041a7.png)

**Comment by Jenefer-Monroe** [comment]
Thank you for the detailed work to come to a recommended solution. 
Unfortunately, in an effort to reduce the API calls in the inventory sync flows we now do a filter based on modified by as shown here. 
![image](https://user-images.githubusercontent.com/89584709/163227298-6afb442b-48e4-4179-9040-34b4e0d3ec02.png)

So your solution will not work for unmodified flows. 
I can hold this though as a feature request to figure out how to update flow state with a cleanup flow or in some other manner.

**Comment by Niqlash** [comment]
Hi @Jenefer-Monroe, I can understand your concerns. As our tenant is quite large we clearly benefit from your care about ensuring that the API calls per day don't exceed the limitations. Still, we heavily rely on the Flow State to be updated correctly to properly govern our thousands of flows and it can be quite misleading having the wrong status displayed.

I therefore like your idea of a cleanup flow. Thinking of this, we (@Sani1991 and I) built a cleanup flow as part of our unmanaged solution complementing your CoE - maybe you would like to integrate this capability into your CoE either by building a separate cleanup flow or by integrating this capability into one of your existing cleanup flows:

![image](https://user-images.githubusercontent.com/34491116/163562002-e89d51c5-744e-46b6-ac7c-63cda238b4c8.png)

After having this flow run successfully, we've identified several hundred obsolete flows that we could clean out of our tenant.

**Comment by Jenefer-Monroe** [comment]
Thanks for your contributions here!

**Comment by Jenefer-Monroe** [comment]
I believe we did this  while back with this scope here


![Image](https://user-images.githubusercontent.com/89584709/214283554-2a9a61e8-45ec-4668-8933-2c608695a499.png)


So I'll go ahead and close this, but please let us know if we've missed the mark
