### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Starter Kit installed in Default environment

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2462]
### What is your question?

I'm having problems with the toolkit, currently have v1.98 and v2.75 in the same environment, trying to just have one and update it. Can't delete either version because of dependencies. Both are also in the default environment, have a separate environment prepped for this going forward.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.98

**Comment by Jenefer-Monroe** [comment]
User posted via #2457 so closing this one
