### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE installed in Dev and Prod

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2463]
### What is your question?

If I install the CoE twice, once Dev, once Prod, do the workflows get in the way because they run twice (1*DEV, 1*Prod)? Or do I have to deactivate all Flows in Dev?

**Comment by Jenefer-Monroe** [comment]
Multiple installs are fine wrt inventory flows. But as you move forward you end up with metadata and maker communications and so you need to be careful. There is a Production Environment env variable that can be used to help with this.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for CoE starter kit team
