### ISSUE TITLE
[ALM Accelerator - QUESTION] Rodmap for GitHub integration

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2465]
### What is your question?

Any roadmap for integrating the github option into ALM Accelerator for Power Platform App instead of using ALM accelerator for Makers?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

n/a

**Comment by mikefactorial** [comment]
Closing as duplicate. We already have this in our backlog but no roadmap currently. Please up vote this issue https://github.com/microsoft/coe-starter-kit/issues/47 and add your feedback there. Specifically, what you're looking for? GitHub as a repository with AzDO for automation or full automation in GitHub via workflows?
