### ISSUE TITLE
[CoE Starter Kit - Feature]: Send all compliance emails in one email

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2467]
### Is your feature request related to a problem? Please describe.

Send all compliance emails in one email for a user

(ask from office hours)

### Describe the solution you'd like

We could also consider having a summary teams adaptive card?

**Comment by Jenefer-Monroe** [comment]
We are refactoring the emails right now to be event based so this would be more difficult with that change. 
Marking as question while we discuss.

**Comment by Jenefer-Monroe** [comment]
closing out after discussion of ROI.
