### ISSUE TITLE
[CoE Starter Kit - Feature]: Change naming of Archive process

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2471]
### Is your feature request related to a problem? Please describe.

Archiving Flows/Apps when they are actually deleted is misleading - change wording to say Deletion

### Describe the solution you'd like

Archiving Flows/Apps when they are actually deleted is misleading - change wording to say Deletion

**Comment by Jenefer-Monroe** [comment]
- test upgrade here before shipping change
- Use: Inactive <object> notifications 
- also would need to change metadata and docs
