### ISSUE TITLE
[CoE Starter Kit - Feature]: Efforts to reduce API calls

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2476]
### Is your feature request related to a problem? Please describe.

Go through all sync flows and see which steps can be combined and reduced to reduce overall API calls of these flows.

### Describe the solution you'd like

Go through all sync flows and see which steps can be combined and reduced to reduce overall API calls of these flows.

**Comment by Jenefer-Monroe** [comment]
Here is the documentation for how API calls are tallied. 
https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations

Looks like there could be a win here by reducing variables to compose where possible, conditions to Coalesce

**Comment by manuelap-msft** [comment]
closing out as this is a very generic issue and we've done the work and tracked it through individual issues.
