### ISSUE TITLE
export-solution-to-git --> Update deployment setting step failes ($cdsBaseConnectionString masked)

### ISSUE THREAD

**Issue by BradleyFestraets** [microsoft/coe-starter-kit#2477]
Hi team,

RE: ALM Accelerator

I recently upgraded to the April 2022 release and then the export-solution-to-git pipeline started to fail.

I did some digging and the error is originating from the update-deployment-settings.ps1 
line 14 : $conn = Get-CrmConnection -ConnectionString "$cdsBaseConnectionString$serviceConnection"

I added Write-Host in the script to check what the $cdsBaseConnectionString variable was returning and discovered that the ClientId value is being masked by DevOps as ***.

Here is a the value from Write-Host : AuthType=ClientSecret;ClientId=***;ClientSecret=[REMOVED];Url=

I read online that this happens to connection strings when being used by powershell commands in the pipelines.

Originally I had the ClientSecret as secret, which then resulted in the whole $cdsBaseConnectionString value being returned as ***, I then removed the secret and have my variable group setup like this, without any secret variables.

![image](https://user-images.githubusercontent.com/38249392/163290262-902f2fcf-daa0-4d44-83c3-ee8493540d27.png)

Any thoughts as to how I could resolve this error?

------
Cheers and thanks in advance,

Bradley

**Comment by mikefactorial** [comment]
@BradleyFestraets you may want to try validating that the service principal in question has access to the development environment. The pipelines will reach back into the environment you're exporting from to read the deployment configuration information. Example in our environment. 
![image](https://user-images.githubusercontent.com/42348035/163393097-80d5a7f8-a2a2-492a-b40c-d5f783f95cba.png)

You can also try running the following powershell locally to test access

```
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
    Install-Module -Name Microsoft.Xrm.Data.Powershell -RequiredVersion 2.8.12
    Import-Module Microsoft.PowerApps.Administration.PowerShell -Force -RequiredVersion $(PowerAppsAdminModuleVersion) -ArgumentList @{ NonInteractive = $true }

    $clientId = "CLIENT_ID"
    $clientSecret = "CLIENT_SECRET"
    $tenantId = "TENANT_ID"
    $url = "https://DEV_ENVIRONMENT.crm.dynamics.com/"
    $connstr = "AuthType=ClientSecret;ClientId=$clientId;ClientSecret=$clientSecret;Url=$url"
    $conn = Get-CrmConnection -ConnectionString "AuthType=ClientSecret;ClientId=$clientId;ClientSecret=$clientSecret;Url=$url"

    $systemuserResult = Get-CrmRecords -conn $conn -EntityLogicalName systemuser -Fields "azureactivedirectoryobjectid"
    echo $systemuserResult.CrmRecords[0]

```

**Comment by BradleyFestraets** [comment]
Hi Mike, 
Thanks for the reply.

I had already checked to ensure the Service account has permissions on the environment before posting here.
However I did also run the script provided and it executed without errors.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/38249392/163917385-50c66eef-272c-4205-888d-0213154411b0.png">

I still believe the issue is with DevOps masking the values in the connection string.

Any thoughts?

**Comment by BradleyFestraets** [comment]
I've replaces the connection script in the update-deployment-settings.ps1 with the below and the pipeline executed without errors.

![image](https://user-images.githubusercontent.com/38249392/163919786-efcc25df-2965-4986-8a1b-89452b844314.png)

Again perhaps hinting towards the masked connection string that is causing the errors. It is strange that this error has not popped up on your side or by anyone else yet.

**Comment by mikefactorial** [comment]
@BradleyFestraets looking back on the thread I don't see the actual error message that you are getting can you share the pipeline log for where the error occurred?

**Comment by BradleyFestraets** [comment]
Hi @mikefactorial,
Apologies for the late reply.

Here is the original error.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/38249392/165191815-5091d3c5-a27c-4110-88b3-5ca26080ddd2.png">

**Comment by BradleyFestraets** [comment]
Starting: Update Deployment Settings
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\1f791b71-4959-4e94-a0aa-0f137e99049a.ps1'"
"[{\"EnvironmentUrl\":\"[https://org8821d898.crm6.dynamics.com/\",\"UserSettingId\":[{\"cat_usersettingid\":\"b5bcf054-7fb5-ec11-983f-0022489395b0\"},{\"cat_usersettingid\":\"018dc65e-7fb5-ec11-983f-0022489395b0\"},{\"cat_usersettingid\":\"33397d66-7fb5-ec11-983f-0022489395b0\"}]}]"](https://org8821d898.crm6.dynamics.com//%22,/%22UserSettingId/%22:[%7B/%22cat_usersettingid/%22:/%22b5bcf054-7fb5-ec11-983f-0022489395b0/%22%7D,%7B/%22cat_usersettingid/%22:/%22018dc65e-7fb5-ec11-983f-0022489395b0/%22%7D,%7B/%22cat_usersettingid/%22:/%2233397d66-7fb5-ec11-983f-0022489395b0/%22%7D]%7D]%22)
Update Deployment Settings


    Directory: D:\a\1\s\Dynamic Forms\EnvironmentVariablesDemo


Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
d-----         4/25/2022  11:37 PM                config                                                               
Importing PowerShell Module: D:\a\1\_coe\ALM_ACC\da\2.8.12\Microsoft.Xrm.Data.PowerShell - 2.8.12
Found System.Collections.Generic.Dictionary`2[System.String,System.Management.Automation.PSObject] solution...
Retrieving maker deployment configuration data...
Get-CrmConnection : Object reference not set to an instance of an object.
At D:\a\1\PipelineUtils\PowerShell\update-deployment-settings.ps1:39 char:25
+ ... tingsConn = Get-CrmConnection -ConnectionString "$cdsBaseConnectionSt ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SyntaxError: (:) [Get-CrmConnection], NullReferenceException
    + FullyQualifiedErrorId : -9,Microsoft.Xrm.Tooling.CrmConnector.Powershell.Commands.GetCrmConnectionCommand
 
##[error]PowerShell exited with code '1'.
Finishing: Update Deployment Settings

**Comment by ajinkyaskulkarni** [comment]
@mikefactorial I am having exact same issue. I have already checked the Devops app user permissions to all environments and also checked with powershell and all of them got crm records in the output.

To test if CdsBaseConnectionString has a issue, i modified it as below (just to test if crmconnection succeeds)
![image](https://user-images.githubusercontent.com/25870713/170686963-0ebcc3e3-7a47-466a-b8ff-9767b69dddeb.png)

and the pipeline works further the crm connection issue (fails for a different issue though)

![image](https://user-images.githubusercontent.com/25870713/170688626-2ddfa3b5-b821-4b8d-9905-cbe10c2ab6d9.png)

Please let me know if there is any other details that you need from my side.

**Comment by ajinkyaskulkarni** [comment]
I figured out the issue from other reported [relatedissue](https://github.com/microsoft/coe-starter-kit/issues/2423).

After i installed the latst CoE solution from [link ](https://aka.ms/CoEStarterKitDownload)mentioned in isssue above, my issue was sorted out, and i could commit and deploy the solution cross the environments.

Thanks & Regards,
Ajinkya S Kulkarni

**Comment by mikefactorial** [comment]
Closing this out as resolved.
