### ISSUE TITLE
[CoE Starter Kit - BUG] Admin_Sharedtotal colum does not exist - Dashboard CoE Power BI

### ISSUE THREAD

**Issue by LoRosset** [microsoft/coe-starter-kit#2478]
### Describe the issue

The refresh of data for the CoE Dashboard in PowerBI fail after the update I made of the CoE for the latest version.

I get the following error:

Data source error: The '<pii>admin_sharedtotal</pii>' column does not exist in the rowset.
Cluster URI: WABI-WEST-EUROPE-redirect.analysis.windows.net
Activity ID: ce139874-ece2-4550-af1a-7057546da4c6
Request ID: 52831065-ca5d-cb2c-6866-20767e812f3e
Time: 2022-04-14 07:48:55Z

![image](https://user-images.githubusercontent.com/25909766/163348787-40d3bb88-7765-4d91-9ca5-e021cefd8279.png)

### Expected Behavior

No error when refreshing the dataset in Power BI

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Dashboard Power BI for the CoE

### Steps To Reproduce

1. Open Power BI Online Service
2. Refresh the dataset linked to the BI Report
3. The error occur at the refresh

**Comment by A-Demir-ilx** [comment]
Hello @LoRosset , Did you also updated the Power BI report to the latest version? The latest version of the PBI report should work.

**Comment by Jenefer-Monroe** [comment]
That's correct. The field was removed as it was empty anyway, and the new field is named Total Shared
Change was made as changing type to calculated column is not supported.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for CoE starter kit team
