### ISSUE TITLE
[CoE Starter Kit - BUG] Variables on Import don´t show any description

### ISSUE THREAD

**Issue by rooobeert** [microsoft/coe-starter-kit#2481]
### Describe the issue

Hi there! 

I just wanted to import the April Release into a fresh installed environment. On import the variables don´t show any text. 
![image](https://user-images.githubusercontent.com/87785803/163384485-bde87055-8c8e-4cfa-a351-1cb89f3b68fb.png)

I have checked with older versions of the CoE Kit and it seems like its a Power Platform Issue. 
Could you provide an in order list of the variables for the import? 

Thanks!
Robert

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Import

**Comment by manuelap-msft** [comment]
Hello,

yep, that looks like a platform issue. Do you have the english language pack installed for the environment (see https://docs.microsoft.com/en-us/power-platform/admin/enable-languages), we've sometimes seen this issue when this wasn't installed.

If you can't get them to show, my recommendation would be to leave them empty on import and update them after import (and before turning on any of the flows), here's how:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables

Thank you
Manuela

**Comment by rooobeert** [comment]
Ah I see okay....that would make sense in my customers environment. We also saw a failed Language Provisioning in the history.
Interestingly tho, in my dev environment, which is english by default I don´t see the english in the language list, but still cant see the names of the fields...

I also just saw that Microsoft worked on the solution UI, it looks different.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for CoE starter kit team
