### ISSUE TITLE
[CoE Starter Kit - BUG] Custom Connector connection lost

### ISSUE THREAD

**Issue by MenakaPurushothaman** [microsoft/coe-starter-kit#2485]
### Describe the issue

Hi 

I am trying to updgrade the CenterofExcellence AuditLogs solution. The issue I am facing is re-establishing the connection with Office 365 Connection API.  It is not picking up the connection that was established. But under connections, I see the Connector status  "Office 365 Management API" to be connected. 

![image](https://user-images.githubusercontent.com/103667061/163429818-0a899210-ab23-4e84-94d4-78ca9e11d52d.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Audit Logs 

### Steps To Reproduce

1. Login to make.powerapps.com
2. Go to CoE environment --> Solutions
3. Import  CenterOFExcellenceAuditLogs_2.6_managed
4. Connections - I see CoE_Audit Logs- O365 Outlook and CoE Audit Logs - Dataverse are already connected to the account that I am logged in and is the same account that Office 365 Management API should be using. But what I see is asking me to establish a new connection instead, which I did and got the below error
"The request failed with error: '{"error":{"code":"0x80040217","message":"connector With Id = de4da0c8-bd02-41df-b0da-bbe0290e8fb4 Does Not Exist"}}'. The tracking Id is '11f7422a-1ffb-400d-8c6f-8a775442f560'."

### Anything else?

[CoE Audit Logs Solution Error.docx](https://github.com/microsoft/coe-starter-kit/files/8490731/CoE.Audit.Logs.Solution.Error.docx)

**Comment by Jenefer-Monroe** [comment]
Please see https://github.com/microsoft/coe-starter-kit/issues/1424
You have to re-establish the custom connector after upgrade of Core, and that requires re-entering the client id and secret and such.

**Comment by jinapark0957** [comment]
Hey Jenefer, 

The connection has been made to the account/environment.  We are able to add the connection however when importing the audit log, it shows the above error.

**Comment by Jenefer-Monroe** [comment]
Please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

**Comment by MenakaPurushothaman** [comment]
***@***.***

***@***.***

From: Jenefer Monroe ***@***.***>
Sent: Thursday, April 14, 2022 2:35 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Menaka Purushothaman ***@***.***>; Author ***@***.***>
Subject: EXTERNAL EMAIL: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Custom Connector connection lost (Issue #2485)


Please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
[image]<https://clicktime.symantec.com/3NnaRazSZkmHi4Ko7G5Jkf16xn?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png>

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3DnqezCAx9DZ2L4zkxGcv3X6xn?u=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F2485%23issuecomment-1099648558>, or unsubscribe<https://clicktime.symantec.com/37GUNUiCLDrLmWsPbeV686C6xn?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYW5K5OM4RTWF4MALHZDGZ3VFCFPLANCNFSM5TOH5PPA>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________
Warning: All e-mail sent to this address will be received by the corporate e-mail system, and is subject to archival and review by someone other than the recipient. This e-mail may contain proprietary information and is intended only for the use of the intended recipient(s). If the reader of this message is not the intended recipient(s), you are notified that you have received this message in error and that any review, dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify the sender immediately.
________________________________

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid pictures only come through if you are logged in to GitHub. They will not come through if you respond in email.

**Comment by Jenefer-Monroe** [comment]
you put your picture in the other bug, here is a screenshot of that 
![image](https://user-images.githubusercontent.com/89584709/163488336-3a16c74b-f305-4c53-a31b-4684a9e08c67.png)

But what I need is a screenshot of the connection above what you showed. Do you see where I have highlighted the connection in my screenshot above? Thats what I need to see.

**Comment by Jenefer-Monroe** [comment]
Two other questions. 
1) What version of Audit Logs are you upgrading from? And about how old is it? 
2) What version of Core are you on?

**Comment by MenakaPurushothaman** [comment]
Please see my comments below

From: Jenefer Monroe ***@***.***>
Sent: Thursday, April 14, 2022 3:31 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Menaka Purushothaman ***@***.***>; Author ***@***.***>
Subject: EXTERNAL EMAIL: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Custom Connector connection lost (Issue #2485)


Two other questions.

  1.  What version of Audit Logs are you upgrading from? And about how old is it? – The old version was 2.0.1.1, it was 6-8 months old.
  2.  What version of Core are you on? – We did upgrade the core components successfully a week ago and we currently have 3.34

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/34faVhWW9ghiPVtTT5Ki79u6xn?u=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F2485%23issuecomment-1099681076>, or unsubscribe<https://clicktime.symantec.com/3Wj3xsfGT1jBoVLBvh1FgaL6xn?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYW5K5LHHJAF7DLBO5DUUTLVFCMDZANCNFSM5TOH5PPA>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________
Warning: All e-mail sent to this address will be received by the corporate e-mail system, and is subject to archival and review by someone other than the recipient. This e-mail may contain proprietary information and is intended only for the use of the intended recipient(s). If the reader of this message is not the intended recipient(s), you are notified that you have received this message in error and that any review, dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify the sender immediately.
________________________________

**Comment by MenakaPurushothaman** [comment]
From: Menaka Purushothaman
Sent: Thursday, April 14, 2022 3:36 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: EXTERNAL EMAIL: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Custom Connector connection lost (Issue #2485)

Please see my comments below

From: Jenefer Monroe ***@***.******@***.***>>
Sent: Thursday, April 14, 2022 3:31 PM
To: microsoft/coe-starter-kit ***@***.******@***.***>>
Cc: Menaka Purushothaman ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: EXTERNAL EMAIL: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Custom Connector connection lost (Issue #2485)


Two other questions.

  1.  What version of Audit Logs are you upgrading from? And about how old is it? – The old version was 2.0.1.1, it was 6-8 months old.
  2.  What version of Core are you on? – We did upgrade the core components successfully a week ago and we currently have 3.34

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/34faVhWW9ghiPVtTT5Ki79u6xn?u=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F2485%23issuecomment-1099681076>, or unsubscribe<https://clicktime.symantec.com/3Wj3xsfGT1jBoVLBvh1FgaL6xn?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYW5K5LHHJAF7DLBO5DUUTLVFCMDZANCNFSM5TOH5PPA>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________
Warning: All e-mail sent to this address will be received by the corporate e-mail system, and is subject to archival and review by someone other than the recipient. This e-mail may contain proprietary information and is intended only for the use of the intended recipient(s). If the reader of this message is not the intended recipient(s), you are notified that you have received this message in error and that any review, dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify the sender immediately.
________________________________

**Comment by Jenefer-Monroe** [comment]
Can you please log in to GitHub and respond to this specific bug going forward? Its very difficult to track your responses when you respond in email. 
I have still not seen this picture from you. Please share an image showing the connection as shown here
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

**Comment by MenakaPurushothaman** [comment]
Hi Jenefer

I commented via GitHub with an attachment.

Thank you,
Menaka

On Apr 15, 2022, at 6:21 AM, Jenefer Monroe ***@***.***> wrote:

﻿

Can you please log in to GitHub and respond to this specific bug going forward? Its very difficult to track your responses when you respond in email.
I have still not seen this picture from you. Please share an image showing the connection as shown here
[image]<https://clicktime.symantec.com/3npZ66AoKYTZY46ZYHdpnB6xn?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png>

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/36W5RMj6jH4Y9nno9KXd9Bw6xn?u=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F2485%23issuecomment-1100105983>, or unsubscribe<https://clicktime.symantec.com/3Mjic9VcaomU8ARsXaUFF556xn?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYW5K5OKTVMFPKZM77QBLN3VFFULXANCNFSM5TOH5PPA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________
Warning: All e-mail sent to this address will be received by the corporate e-mail system, and is subject to archival and review by someone other than the recipient. This e-mail may contain proprietary information and is intended only for the use of the intended recipient(s). If the reader of this message is not the intended recipient(s), you are notified that you have received this message in error and that any review, dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify the sender immediately.
________________________________

**Comment by Jenefer-Monroe** [comment]
your picture did not show the connection, please see the area highlighted in yellow in my picture, that is what you need to show me.

**Comment by MenakaPurushothaman** [comment]
![image](https://user-images.githubusercontent.com/103667061/163583627-f119b706-cb98-44a0-ac4b-6f79d1eae9ff.png)

![image](https://user-images.githubusercontent.com/103667061/163583749-bdcc2e46-bf90-4314-b1b7-9dc102a3e5bf.png)

**Comment by Jenefer-Monroe** [comment]
Are you logged in as the person listed (behind the orange box in your picture) when you are trying to install?

**Comment by Jenefer-Monroe** [comment]
are you sure the connector its complaining about is this one? you may need to go list the connectors in the envt and cross reference.

**Comment by MenakaPurushothaman** [comment]
yes, I am.

**Comment by Jenefer-Monroe** [comment]
I'm afraid you are in a state I've never seen and I am out of ideas on how to assist. The CoE Starter Kit is not a supported product and so we cannot always assist people with issues that are particular to their tenant due to our staffing levels.

You will need to investigate on your own and find some more clues (ex look for the GUID of your custom connector to compare etc). If you get some clues and still need help, respond and I'll try to assist too. 

Or you may need to seek out a partner to assist. 

Sorry we couldnt be of more assistance.

**Comment by MenakaPurushothaman** [comment]
Thank you Jenefer for looking into this issue.

+Jina

Thank you
Menaka

From: Jenefer Monroe ***@***.***>
Sent: Friday, April 15, 2022 11:53 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Menaka Purushothaman ***@***.***>; Author ***@***.***>
Subject: EXTERNAL EMAIL: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Custom Connector connection lost (Issue #2485)


I'm afraid you are in a state I've never seen and I am out of ideas on how to assist. The CoE Starter Kit is not a supported product and so we cannot always assist people with issues that are particular to their tenant due to our staffing levels.

You will need to investigate on your own and find some more clues (ex look for the GUID of your custom connector to compare etc). If you get some clues and still need help, respond and I'll try to assist too.

Or you may need to seek out a partner to assist.

Sorry we couldnt be of more assistance.

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3HgwXiTiohvePttwFJnWp1m6xU?u=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F2485%23issuecomment-1100290907>, or unsubscribe<https://clicktime.symantec.com/3FM9TBeR2Ns433pfTEADSkU6xU?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYW5K5NAEYNZ44SNCQNLHOTVFG3INANCNFSM5TOH5PPA>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________
Warning: All e-mail sent to this address will be received by the corporate e-mail system, and is subject to archival and review by someone other than the recipient. This e-mail may contain proprietary information and is intended only for the use of the intended recipient(s). If the reader of this message is not the intended recipient(s), you are notified that you have received this message in error and that any review, dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify the sender immediately.
________________________________

**Comment by MenakaPurushothaman** [comment]
+Jina and + Kevin

From: Jenefer Monroe ***@***.***>
Sent: Friday, April 15, 2022 11:53 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Menaka Purushothaman ***@***.***>; Author ***@***.***>
Subject: EXTERNAL EMAIL: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Custom Connector connection lost (Issue #2485)


I'm afraid you are in a state I've never seen and I am out of ideas on how to assist. The CoE Starter Kit is not a supported product and so we cannot always assist people with issues that are particular to their tenant due to our staffing levels.

You will need to investigate on your own and find some more clues (ex look for the GUID of your custom connector to compare etc). If you get some clues and still need help, respond and I'll try to assist too.

Or you may need to seek out a partner to assist.

Sorry we couldnt be of more assistance.

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3HgwXiTiohvePttwFJnWp1m6xU?u=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F2485%23issuecomment-1100290907>, or unsubscribe<https://clicktime.symantec.com/3FM9TBeR2Ns433pfTEADSkU6xU?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYW5K5NAEYNZ44SNCQNLHOTVFG3INANCNFSM5TOH5PPA>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________
Warning: All e-mail sent to this address will be received by the corporate e-mail system, and is subject to archival and review by someone other than the recipient. This e-mail may contain proprietary information and is intended only for the use of the intended recipient(s). If the reader of this message is not the intended recipient(s), you are notified that you have received this message in error and that any review, dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify the sender immediately.
________________________________

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for CoE starter kit team
