### ISSUE TITLE
[ALM Accelerator - BUG]: We keep seeing issue with ENV variables not populating

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#2486]
### Describe the issue

when setting the env variables during commit everything is well however when deploying we can clearly see (in default) that those values do not populate. This is causing downstream effects and impact flows not turning on having to create unmanaged layers in order to make the whole thing work 

### Expected Behavior

Env var to populate

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April Release

**Comment by mikefactorial** [comment]
Hi @gerald560 can you make sure that you are not exporting the current values in the dev environment as part of the solution? Alternatively you can set the variable DoNotExportCurrentEnvironmentVariableValues on your export pipeline to ensure that the current values are excluded from source control. 
![image](https://user-images.githubusercontent.com/42348035/163436061-375f0819-eb6e-4d5c-8fe3-677cdbe52bae.png)

**Comment by mikefactorial** [comment]
Additionally, can you verify that the environment variable values you expect to be set are in the deployment pipeline's variables and that the variable name matches what is in the deploymentSettings.json file? 
![image](https://user-images.githubusercontent.com/42348035/163436589-bb6fce2c-2d1b-48cd-ace6-28fb8d5dd55e.png) 
![image](https://user-images.githubusercontent.com/42348035/163436809-2b7e3767-00b9-4ef4-b695-a8fbc82ba474.png)

**Comment by gerald560** [comment]
Hye Mike yeah I can confirm this is set to true ..we went as far as looking in the collection and ultimately the ALM Admin app as well we see the env vars there yet some how they still don't get populated 
![image](https://user-images.githubusercontent.com/12697408/163439853-491ffce7-2607-41fd-9fe4-817b93f0559a.png)

**Comment by mikefactorial** [comment]
@gerald560 are you saying that you don't see the values on the deployment pipeline or they are on the deployment pipeline and just not in the deployed environment? https://github.com/microsoft/coe-starter-kit/issues/2486#issuecomment-1099401617

**Comment by mikefactorial** [comment]
Assuming the deployment pipelines have the correct variables then the only other possibility is that there is an unmanaged layer in the deployment environment that's preventing the values from being updated. In that case this might help https://docs.microsoft.com/en-us/power-apps/maker/data-platform/solution-layers#:~:text=Remove%20an%20unmanaged%20layer&text=can%20be%20lost.-,Open%20the%20solution%20you%20want%2C%20select%20...,Solution%20column%20for%20the%20layer.

**Comment by mikefactorial** [comment]
@gerald560 closing out this issue for now since I haven't heard anything back regarding my latest questions. Let me know if you got this resolved. If not please feel free to reopen and let me know if you were able to verify the deployment pipeline variables as mentioned above.
