### ISSUE TITLE
[ALM Accelerator - BUG]: Flow failure for Teams

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#2487]
### Describe the issue

![image](https://user-images.githubusercontent.com/12697408/163432477-b154f1eb-ea81-45a6-9038-afb926c3a78b.png)

seeing this with multiple users

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April Release

**Comment by mikefactorial** [comment]
@gerald560 Can you see the failures in the Flow runs or is it not calling the flow at all? If the flow is being called is there any indication of what the invalid value is? 
![image](https://user-images.githubusercontent.com/42348035/163437435-ff0a30bf-b2b7-44c1-a2a1-ee4bae620cad.png)

**Comment by gerald560** [comment]
the error here is as follow 
![image](https://user-images.githubusercontent.com/12697408/163440668-a6465e45-cba3-4e97-9937-436d7246c21e.png)

we have set up our env very similar to MS recommended Validation (we named it to build) Test and Prod .. user are granted basic access and ALM power app access to Prod where the ALM app resides

**Comment by mikefactorial** [comment]
That's helpful thanks @gerald560. The error is related to the variables passed to the flow (you can see them if you expand the PowerApps (V2) step) in this case it's looking for an organization that doesn't exist obviously. Can you verify that the name of the target org is in fact 36378...? That looks suspicious. Could be related to how you setup your deployment profile. The deployment profile should be configured with the urls of the target environments.

**Comment by gerald560** [comment]
this is ..only certain users see this ... admin like myself don't which leads me to believe that basic and ALM is not enough as far as profiles go 
![image](https://user-images.githubusercontent.com/12697408/163449852-fc9b0a94-ae7e-44c8-b2df-79cd4cba0f60.png)

We only created on for All

**Comment by mikefactorial** [comment]
@gerald560 the ALM / Basic user permissions should be sufficient in the ALM Accelerator org. However, you may need to share the profile with users who need to see it i.e. add the profile to the deployment user setting for those users. https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-profiles

However, I don't think that would explain the error message in the flow which is explicitly saying the user doesn't have access at all to the downstream environment or the specified downstream environment doesn't exist. Have you tried asking the user in question to try to access that org directly? e.g. have them go to https://36378....crm.dynamics.com and see what happens interactively. My assumption is they will get a similar error that they can't access the environment.

**Comment by gerald560** [comment]
yeah the 363 is not even a real env ..not sure where it's getting that from... also the profile has been shared as follows: 

![image](https://user-images.githubusercontent.com/12697408/163863142-ec20b6d2-1a8b-4870-b01e-483d62c96f0a.png)

yet they don't see it

![image](https://user-images.githubusercontent.com/12697408/163862761-bb712d64-53f1-44e1-927c-324cdf826b06.png)

**Comment by LizethRegules** [comment]
Hello @mikefactorial! 
What's happening is that the deployment profile that is being shared with every new developer does have the validation org url value, developers have basic user and service reader roles in the validation environment, they do see the validation environment in make.powerapps.com, but they do not see it neither in the dropdown from the configuration deployment settings nor in the home page of the ALM app. 

What's weird is that the 36378....crm environment does not even exist, the flow is running with the right environment (https://orgname.crm.dynamic.com/) for the rest of the developers, except for these new ones that have recently been shared the deployment profile with. The 36378 environment is being taken as a value for whatever reason we don't know.

**Comment by mikefactorial** [comment]
@LizethRegules that's helpful. Are the new developers being added via AAD Groups? I ask because it's possible that this is a Just in Time provisioning of the users issue. It's a known issue in the platform, but there are some workarounds if we find that that's the issue.
![image](https://user-images.githubusercontent.com/42348035/163886360-9caa9831-ffb6-4980-a657-80f48c6458b9.png)

**Comment by gerald560** [comment]
no Mike the dev has been with me for 3 years ... this issue is still persistent.

**Comment by mikefactorial** [comment]
@gerald560 and @LizethRegules circling back on this issue. Did you ever find a resolution here?

**Comment by gerald560** [comment]
no she still doesn't see validation :(

**Comment by mikefactorial** [comment]
@gerald560 we've been working with the product team on this issue related to another issue https://github.com/microsoft/coe-starter-kit/issues/3302. What we've found is that Basic User is not sufficient for a user to be able to view or to be able to interact with a downstream environment using the ALM Accelerator. 

Users will need at least Environment Maker permissions in the downstream environment. I'm going to close this issue out for now. If you can verify that environment maker permissions resolve this issue we will continue to work with the internal teams on getting to a point where these elevated permissions aren't required.
