### ISSUE TITLE
[ALM Accelerator - QUESTION] Git Repo Does Not Exist Or No Permissions

### ISSUE THREAD

**Issue by matthewdevaney** [microsoft/coe-starter-kit#2488]
### What is your question?

The export-to-git pipeline fails on the step Update Deployment Settings with this message.  I have checked my security settings on the repo and I believe there are setup properly.  My assumption is the repo GUID here is wrong.

![image](https://user-images.githubusercontent.com/34290969/163436623-b56a6646-9924-4624-ae99-ae33fc1f586b.png)

However, when I look at the ALM Admin app I can see the proper repo GUID is set.  How can I ensure the pipeline can find the repo with the GUID I supplied? 

![image](https://user-images.githubusercontent.com/34290969/163436065-49ce8973-fcff-4837-bc41-45829bf87373.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 2022

**Comment by mikefactorial** [comment]
Hey @matthewdevaney, can you do me a favor and take a look at the deployment pipeline(s) for the solution and see if there's anything odd when you try to edit the pipeline. I'm thinking there is a problem with the pipeline definition that's causing the update to fail. Also, are you seeing variables being populated at all on any of the deployment pipelines?

![image](https://user-images.githubusercontent.com/42348035/163439346-1ef98280-c99a-45ec-993c-3c51dc4af87d.png)
![image](https://user-images.githubusercontent.com/42348035/163439562-06457faf-16cc-4849-8f6c-2fba6af19b21.png)

**Comment by mikefactorial** [comment]
The one thing that is odd about your setup is that your deployment profile points to the "pipeline" repo. That's generally reserved for just the pipeline templates / powershell etc. so it's possible that's the reason it's tripping up.

**Comment by matthewdevaney** [comment]
Mike,

I re-ran the pipeline with a different repo called wpg-policing-database with the same result.

![image](https://user-images.githubusercontent.com/34290969/163442334-61bcc783-bfdd-440e-8ad5-d79ab8ac8fcc.png)


My deploy pipeline seems to have this warning which is the same .  city-of-winnipeg policing database is an old repo name.  I deleted that repo andstarted using a different repo called wpg-policing-database.
![image](https://user-images.githubusercontent.com/34290969/163443118-fb28ad38-af42-4689-9477-6f94fcc20b4b.png)

Then I get this fun looking message when I go to classic mode.
![image](https://user-images.githubusercontent.com/34290969/163445607-30d67d82-59df-4c15-8606-cdca6ef6b58d.png)

**Comment by matthewdevaney** [comment]
I would love to remove the PolicingDatabase data (pipelines?) from Dev Ops and start over.  However, its not obvious how I can do so.

Then, when I delete deployment profiles from the admin experience they keep coming back.

**Comment by mikefactorial** [comment]
I'd recommend deleting the deployment pipelines and creating a new deployment profile for the new repo. The export pipeline (when you commit) will recreate the pipelines for you.

**Comment by matthewdevaney** [comment]
I'll go "flush the system" as you've suggested and report back.

**Comment by matthewdevaney** [comment]
It found the git repo and folder this time, hooray!  But I've hit another error.  This time it doesn't say what's gone wrong

![image](https://user-images.githubusercontent.com/34290969/163450512-27a4d6f2-bb70-409b-becb-b2ca3858514e.png)

**Comment by mikefactorial** [comment]
Closing out this issue since there's nothing else to do here.
