### ISSUE TITLE
Dependency error when importing Governance Components

### ISSUE THREAD

**Issue by dbgrl93** [microsoft/coe-starter-kit#2493]
### Describe the issue

I am installing the latest release of the CoE Starter Kit.  Successfully installed the Core Components and have walked through the steps to set that up.  When importing the Governance (labeled as Audit Components) Components, I am getting this message

Import failed due to missing dependencies for Center of Excellence - Governance Components.

![image](https://user-images.githubusercontent.com/34557134/163488633-a2a3c590-8619-4a7f-ae0d-049a108a1545.png)

I have installed version 3.18 of the Core Components.

### Expected Behavior

Import the Audit Components into the CoE Environment. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.15

### What app or flow are you having the issue with?

Importing the solution

### Steps To Reproduce

1.  Import the latest release for the CoE Core Components.  CenterofExcellenceCoreComponents_3.18.zip
2. Setup environment variables and flows according to documentation
3. Import the CoE Governance or Audit Components, CenterofExcellenceAuditComponents_2.15.zip
4. Error comes up during import.

### Anything else?

I have tried the managed and unmanaged solutions.

**Comment by Jenefer-Monroe** [comment]
Hello, we will typically need more details than this to assist. If you look at the solution history it will probably tell you which dependency is missing. 
That said, this is a typical issue people face when new to the CoE. Setup is quite complex and you need to track the setup documentation carefully. In this case you likely missed setting up the approval solutions. 
Please see [Before setting up the governance components](https://docs.microsoft.com/power-platform/guidance/coe/before-setup-gov)

**Comment by dbgrl93** [comment]
Hello, thanks for the response.  I did setup and run the approval solutions and it was successful.  

Here is some more detail
1.  I downloaded the UnManaged zip file  ( CoEStarterKit-Unmanaged.zip)  from April.  I am trying to setup a dev environment for the kit.  I noticed the core components zip file in the unmanaged set of files is version 3.13? ( CenterofExcellenceCoreComponents_3.18.zip) For the managed files, I noticed the core components file is at version 3.37 (CenterofExcellenceCoreComponents_3_37_managed.zip).  Any reason for the version difference?
2. I can see the solution history but not sure what to look for, everything listed in there is Successful.  Can you describe what I should look for?
3. When I get the error, I can click on a button labeled Show Dependencies and I see this
![image](https://user-images.githubusercontent.com/34557134/163597903-548a3719-7bf1-45fd-85d7-0e0c19b14b14.png)

**Comment by Jenefer-Monroe** [comment]
We dont test or use the unmanaged versions that are there. They are produced only sometimes and by change of this processes get run in the background. The current version of Core is 3.37 and I believe there are new fields this release that Gov relies upon.

**Comment by dbgrl93** [comment]
Hello, thanks for the response.  Is there anyway to get the latest version of the core components in an unmanaged solution?

**Comment by Jenefer-Monroe** [comment]
I'm afraid not, as I mentioned, these are not produced intentionally they are just created sometimes dependent upon which tools are used for release, and they werent produced for 3.37

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
