### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin Sync Template for Solutions

### ISSUE THREAD

**Issue by Srise96** [microsoft/coe-starter-kit#2498]
### What is your question?

Hi CoE Starter Kit team,

Do we have a **Admin Sync Template for Solutions**?

As I know, admin sync templates will extract Power Platform Components details from all the Environments and update in CoE Dataverse Tables. Similarly, we would like to extract **Solutions** details from all the Environments and update in CoE Dataverse table, however I cannot see any sync templates for Solutions. 

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for using CoE. This is on our feature backlog. But we do not have access within objects to reliably map them to which solution they belong. And hence we have held off on this funding as it appears to not be useful until we have that information as well. 

Here is the backlog item if you'd like to add some commentary and/or track. 
https://github.com/microsoft/coe-starter-kit/issues/968

Thanks again

**Comment by Srise96** [comment]
Thank you for your reply. Understand the issue. 

However, my requirement is different. I'm trying to extract Solutions details from Dataverse tables (general details for e.g Solutions ID, Name, Environment, created by etc) from all the environments and update in CoE Dataverse table (Solutions table). I guess Admin Sync Templates will extract the info and update CoE Dataverse tables. 

I can find Admin Sync Templates for Apps, Flows, Desktop Flows, PVA but Solutions is not available. Is there any Admin Sync Templates that can meet my requirement?

**Comment by Jenefer-Monroe** [comment]
That table and flow for collection would be part of the work for that feature. The reason we are not funding it yet is that this information alone is not actionable for the admin personas that we have queried about the feature. So we are waiting to do it until the product allows us to also map the objects on the solutions to the solutions. 
Please let us know how you would use just the table of solutions without the other information, and we can use for triage of the feature work in the list
Thank you

**Comment by Srise96** [comment]
Thank you.

We are thinking of monitoring the creation of Solutions in all environments by extracting the details and store in the CoE Dataverse table (Solutions table). We want to extract the Solutions information such as Solutions ID, Name, Environments, Created by etc. The details of object inside the Solutions is not required as we just need to monitor how many solutions are created and store it centrally in CoE Dataverse table.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jenefer-Monroe** [comment]
Thank you, I have made it more clear in that bug that it tracks both of these areas of work.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
