### ISSUE TITLE
[ALM Accelerator] Add Documentation around Pipeline Customization

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#25]

**Comment by mikefactorial** [comment]
For this we need to explain the default pipelines and how they can be customized in conjunction with the Deployment Profiles and interaction with the coe-cli

**Comment by jenschristianschroder** [comment]
I think this can be closed as we now have (some) documentation on 
- customizations via hooks/extensions (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorforpowerplatform-hook-extensions)
- configuring the pipelines (https://learn.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-pipelines)

**Comment by mikefactorial** [comment]
Agree closing out.
