### ISSUE TITLE
[CoE Starter Kit - BUG] UserPhotoMetadata error in Environment Request app

### ISSUE THREAD

**Issue by LilianThomsen** [microsoft/coe-starter-kit#2502]
### Describe the issue

I'm getting this error when searching for makers in the Environment Request app:

Office365Users.UserPhotoMetadata failed: The method 'UserPhotoMetadata' has an invalid value for parameter 'userId'

![image](https://user-images.githubusercontent.com/103517574/163960818-fea8f829-d28a-43e1-861f-0cf92339b28b.png)

### Expected Behavior

I would expect no error to be shown

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2022

### What app or flow are you having the issue with?

Maker - Environment Request

### Steps To Reproduce

1. Create new request
2. Add connection
3. Search for maker

**Comment by denisem-msft** [comment]
Thanks for the feedback! This has been fixed and will be available in the July release.
