### ISSUE TITLE
[CoE Starter Kit - Feature]: FEATURE Connections to reauthenticate via a flow

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#2510]
### Is your feature request related to a problem? Please describe.

We notice from time to time that connections do not reauthenticate see
![image](https://user-images.githubusercontent.com/12697408/164047227-7d4e2fe2-955e-4ec3-a917-d81b845e504a.png)

typically once clicking fix the connection and authenticating solves this issue.

Is there a flow we can use to perform this action and maybe even schedule it for all underlying connections that need it?

### Describe the solution you'd like

A flow that re authenticates all lost connections

**Comment by Jenefer-Monroe** [comment]
I don't think we have programmatic access to di this. Marking as Question for now while we investigate.

**Comment by Jenefer-Monroe** [comment]
Unfortunately we do not have programmatic access to fix this up for you. 
Thanks for posting though.

**Comment by gerald560** [comment]
long shot but @mikefactorial any ideas here.... I would say this should be MS top priority in order to have stable solutions.

**Comment by gerald560** [comment]
also not sure why it was closed this was a feature request...
