### ISSUE TITLE
[CoE Starter Kit - BUG] msft_PowerAppsUnifiedClientInfraExtensions Failure

### ISSUE THREAD

**Issue by bkrotz** [microsoft/coe-starter-kit#2513]
### Describe the issue

I have a question about the "msft_PowerAppsUnifiedClientInfraExtensions". What's this msft_PowerAppsUnifiedClientInfraExtensions" used for? Do we need to change any settings? Can we ignore it?
Thanks,
Bin

Please see the following the images for details. It shows in the history (Navigate to Solution>See history). 
![image](https://user-images.githubusercontent.com/50377264/164071908-c222c306-bccf-478d-9fb6-5209d833994d.png)
![image](https://user-images.githubusercontent.com/50377264/164074011-99e73ee8-f9af-44fd-bd60-86eb58cbe6ab.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

msft_PowerAppsUnifiedClientInfraExtensions

### Steps To Reproduce

It shows in the history 
1. Navigate to Solution
2. Click on See history

**Comment by manuelap-msft** [comment]
Hello,

the solution and component you are highlighting is not part of the CoE starter kit, but part of the product. I don't know what this extension is either, but you can raise a question through your regular support channels: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support

Manuela

**Comment by bkrotz** [comment]
Thank you!
