### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI report custom connector page

### ISSUE THREAD

**Issue by larhem** [microsoft/coe-starter-kit#2516]
### Describe the issue

The Custom connectors page  in the CoE Power BI report is showing correct number of custom connectors in upper left corner. 
But the two tables showing "Used in apps" and "Used in Cloud flows" are not showing any data at all. 
We have checked filters on the page/tables but it doesnt make any difference. 

### Expected Behavior

Expecting the tables to show app and/or flow that is using the custom connectors. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Production_CoEDashboard_April2022

### What app or flow are you having the issue with?

Production_CoEDashboard_April2022.pbit

**Comment by Jenefer-Monroe** [comment]
Can you please check in the **_Power Platform Admin View_** app to see if the expected apps / flows are there for a particular Custom Connector? 
![image](https://user-images.githubusercontent.com/89584709/164450763-f16de212-a3e5-488c-a61c-a0d918b23491.png)

If so, then likely your PowerBI data set isnt refreshed, or [set to autorefresh](https://docs.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh). 

Please let me know!

**Comment by larhem** [comment]
No. The app/flow is not present there. In what dataverse table is this relation supposed to be present?

**Comment by Jenefer-Monroe** [comment]
We do not get this from the product datatables, we create the connections in the sync flows from information we get from the product connectors. I presumed here you have already checked to make sure your sync flows are all passing. But if not that may be the cause as well, and we will find that here.

Next steps in investigation. 

- Ensure full inventory env variable still set to yes
- Pick a target app that has a custom connection. Pick one in a sparse environment if possible to make investigation faster. 
- In the **Power Platform Admin View** app, find this target environment, that contains the target app, change some property (ex Maker Requirement - Business Justification on Audit) , and save
- This will cause the **Admin | Sync Template v3 (Apps)** flow to run for the target envt
- Open the run 
- Look for your app in this filter output
![image](https://user-images.githubusercontent.com/89584709/164483504-e76c77ca-b74c-4e47-990e-45318bc39d90.png)
- Select it from the following apply-to-each and validate that it lands in the **Append to edit array** action.
![image](https://user-images.githubusercontent.com/89584709/164483957-6a366463-a04c-4016-9121-8459f934cd14.png)
- if this does not occur, then your full inventory is not correctly set. Please revisit [full inventory instructions](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory), likely you did not reset the flows.
- find the app in the Edit Updated Apps scope's Apply to each editted loop. It will likely be the same number as above but you can validate by checking the appid as shown here 
![image](https://user-images.githubusercontent.com/89584709/164485176-ffea0c81-588f-4be1-affc-606f5bf758d5.png)
- validate your custom connector shows up here 
![image](https://user-images.githubusercontent.com/89584709/164485469-32e36596-c2b1-4fc7-a3f8-73c661f5857d.png)
- validate the connection is added here 
![image](https://user-images.githubusercontent.com/89584709/164485627-69212d55-4419-449e-91ae-d3e480a4a25f.png)

**Comment by larhem** [comment]
I did the same, but for Flow instead of app. And i can see that it inserts a new flow connection reference and now its also visible in Power BI report and in Power Platform Admin View app.

![image](https://user-images.githubusercontent.com/91886096/164624816-10d23ea1-1cf1-4fae-833e-a4fff1163655.png)

**Comment by Jenefer-Monroe** [comment]
ok great. I"m not sure what was wrong, but it sounds like it is resolved now correct?

**Comment by larhem** [comment]
Yes, its correct now. But the process to get it correct was a bit overwhelming. Do we need to do the same each time we add a new custom connector?

**Comment by Jenefer-Monroe** [comment]
No not at all, I was just trying to see where the breakdown was. All you did here was trigger the flow that should occur daily anyway as a result of Admin | Sync Template v3

Please just go validate that this flow is on and passing, and that Admin | Sync Template v3 (Apps) and Admin | Sync Template v3 (Flows) are running and passing.

**Comment by larhem** [comment]
They are all running on a daily basis. But fullinventory is set to «no» as default. 

I also did a full inventory yesterday, only differrence today is that i also did a change to the environment so that the flows where triggered automatically.


I will perform the same om the other environments with custom connectors and i will keep an eye on this the next time we create a new custom connector. 

Thanks

**Comment by Jenefer-Monroe** [comment]
I think there is just  a misunderstanding. When I say do a [full inventory](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory) I mean with that envt variable set to yes. 

You do not need to do the steps above to get the full inventory, you need to just set the envt variable (and reset the flows as described in that article) and then let the Admin | Sync Template v3 run.

**Comment by Jenefer-Monroe** [comment]
Although we had a hiccup I am going to assume this was due to the original suspicion, namely that the order of setup in the setup instructions lead to an issue. 

The apps and flows begin to get populated before the custom connectors are in the inventory, and so do not get connected. 
We need to think through this setup ordering.
