### ISSUE TITLE
[CoE Starter Kit - BUG] I don't see Teams Environment in Power BI

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2517]
### Describe the issue

Good morning,
below two screenshots of two different installations on the same tenant.
In one I can see Teams environments and in the other not. Why?
Thanks 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/101250592/164195462-2de23086-3f63-45ac-a249-281a2d409be8.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/101250592/164195465-f7277fe6-13be-40ec-bf33-a2c3278ffc76.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April2022

### What app or flow are you having the issue with?

Power Bi - CoE Dashboard

**Comment by JackSocini** [comment]
The screen is named Environment.

**Comment by Jenefer-Monroe** [comment]
Have you validated that the sync flows are all running and passing in both installations? 
Have you validated that you have PPAdmin assigned directly (not via PIM)?

**Comment by JackSocini** [comment]
The PPAdmin was assigned via PIM, it is a problem? How can we selve that issue?

**Comment by Jenefer-Monroe** [comment]
Please read [our pre-reqs](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)
![image](https://user-images.githubusercontent.com/89584709/164229098-3057e80d-e12f-41ef-a698-cb8d2b5e8477.png)


We cannot support PIM as the flows are long running and if they lose access mid-run (or before a run starts) then they will not get full inventory. 
The account had PPAdmin during the run in the bottom envt and did not in the top one.
