### ISSUE TITLE
[CoE Starter Kit - BUG] Model driven apps data not being reported

### ISSUE THREAD

**Issue by pallvip** [microsoft/coe-starter-kit#2520]
### Describe the issue

Hi 
I am using COE starter kit feb 2022 version and cant see any data in the Power BI report on the model driven apps - only see Canvas and SharePointFormApp

Can you please help as this data is quite critical to provide very important information to drive an ongoing Production project.

### Expected Behavior

The Apps report dashboard should show data for Model driven apps along with Canvas apps and SharePoint form app

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

na

### Anything else?

![image](https://user-images.githubusercontent.com/40602120/164221151-226f17a6-6588-4398-99d0-70ac7e90fbe0.png)
Please note its the latest Power BI dashboard, I have just added Power Apps type in the legend.

this is the data from an older COE version and you can see there are quite a few model driven apps
![image](https://user-images.githubusercontent.com/40602120/164221538-949082d6-dc34-4806-8da9-f2f80d821439.png)

**Comment by Jenefer-Monroe** [comment]
Can you please confirm a few things for me? This can all be done in the **_Admin - Command Center_** depending on your version. 

1) Do you have this flow turned on? **Admin | Sync Template v3 (Model Driven Apps)** 
![image](https://user-images.githubusercontent.com/89584709/164224039-2ba25fff-29e1-487d-8bb3-0e0cb5e677c8.png)

2) Do you have failures for that flow in the Service Health list? 
![image](https://user-images.githubusercontent.com/89584709/164224152-d026886e-8769-4b3a-b78e-8b3a6c92c9c4.png)

3) What value do you have for the environment variable **Also Delete From CoE**
![image](https://user-images.githubusercontent.com/89584709/164224481-e8885132-3eb3-4109-a6d5-d54da74f293c.png)

**Comment by pallvip** [comment]
Hi Jenefer - Thank you for getting back so quickly.
Just to add, we used to get through the Model driven apps data until last week, and seems its very recent that we are not.

1. ![image](https://user-images.githubusercontent.com/40602120/164233411-75824f1e-c932-441a-894a-97a89a26acff.png)
2. We have quite  a few failures in Health centre and I can see the same flows run for other instances successfully.
![image](https://user-images.githubusercontent.com/40602120/164238164-742a9d96-85d2-48d3-bdf2-137d33fdf81e.png)

![image](https://user-images.githubusercontent.com/40602120/164238730-a2e4d5d8-def2-48c6-ae82-be70040db612.png)

3. ![image](https://user-images.githubusercontent.com/40602120/164237881-851268cb-e837-4b4e-9cea-66d1e950ed2d.png)

**Comment by Jenefer-Monroe** [comment]
There seems to be something quite broken happening for you here with multiple instances of **_Admin | Sync Template v3_** running at once. And with it running hourly. 

Are you sure of the version of Core that you have listed? We had a recent regression in 3.36 which caused that flow to fail. 

Please turn cancel all those instances of Admin | Sync Template v3, open that most recent failure and lets see where the breakdown is occuring.

**Comment by pallvip** [comment]
Yes the version is 3.31 - see below
![image](https://user-images.githubusercontent.com/40602120/164260442-02fa76b3-60ff-4bcc-8ace-c4e9c601caef.png)

![image](https://user-images.githubusercontent.com/40602120/164257231-95480fe4-c87d-41fc-a5a6-252dea02ff52.png)

![image](https://user-images.githubusercontent.com/40602120/164257189-b336ff1e-c3d7-47ec-b248-e542f2bb5e52.png)

I have found some failures in Sync template - due to failing to trigger child flow (suspended due to hitting limits)
Check deleted is failing as well - not fully sure on the cause. I have assigned it per flow pass as well rather than the per user license it was using to see if it resolved the issue. Will let you know 
check deleted

**Comment by Jenefer-Monroe** [comment]
We added a short circuit to the helper flow in the April release (3.37) so I think an upgrade should resolve this throttle for you
