### ISSUE TITLE
[CoE Starter Kit - BUG] Deleting a SP list does not delete its App

### ISSUE THREAD

**Issue by bethleota** [microsoft/coe-starter-kit#2527]
### Describe the issue

I have installed the March 2022 CoE update and confirmed that all flows that start with CLEANUP are turned on and running without failures. I'm seeing many SharePoint Form Apps in the default envrionment that aren't being deleted from CoE even though the site, web, or list has been deleted. I navigate to the SharePoint Form URL from the Power Platform Admin View dashboard. I click on the link and receive messages like this:
Hmmm… can't reach this page It looks like the webpage at https://<mycompany>.sharepoint.com/sites/rcm/Lists/<listname>/AllItems.aspx might be having issues, or it may have moved permanently to a new web address.

In some cases, the Maker who customized the form is no longer with the company, but in others the Maker is a current employee. Also, some lists were customized in modern and some in 
![CoE-3-Hmmmmm](https://user-images.githubusercontent.com/40639953/164276648-29cd1398-fcb2-4535-aba8-5337098140e6.jpg)
![CoE-3](https://user-images.githubusercontent.com/40639953/164276652-5a44e21f-9636-44ac-b46b-fb43735e925c.jpg)
![CoE-2-404error](https://user-images.githubusercontent.com/40639953/164276657-2bdb1bf4-9880-4715-84fb-ef7e0d75ff17.jpg)
![CoE-2](https://user-images.githubusercontent.com/40639953/164276659-1f579de4-a431-4f85-844b-28b66e951663.jpg)
![CoE-1](https://user-images.githubusercontent.com/40639953/164276667-1c71c1ae-1fb5-456b-866e-d2f1f6ac3bd0.jpg)
![CoE-Hmmmm](https://user-images.githubusercontent.com/40639953/164276671-64d5aebd-664c-4489-8b20-bd8e5a46877f.jpg)
classic SP sites.

Another similar issue is that I have found at least one site that has a list with SharePoint FormApps that doesn't show up in CoE. However, after further research, this list is on a classic SharePoint team site so maybe that's why. And the user is no longer with the company.

### Expected Behavior

Per MS documentation <https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form>
Q: What happens to my custom form if the list is deleted or restored from the Recycle Bin?
A: Deleting a list automatically deletes the associated custom form. If a list that contains an associated custom form is restored from the Recycle Bin, the custom form is also restored automatically with the list.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Steps To Reproduce

1. Personal Productivity - Default
2. Power Platform Admin 
3. View SharePointForm Apps
4. Delete custom form app from SP list settings
5. Run all CLEANUP  Flows
6. Refresh Power BI report
7. Wait one day
8. Re-check. Forms are still there.

### Anything else?

https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/customize-list-form

Deleted apps and flows - https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/limitations.md#deleted-apps-and-flows
There are two options in the CoE Starter Kit to handle deleted resources – either they are deleted from the inventory table or they are kept in the inventory table and a 'Deleted' field is set to yes (true). This setting is controlled via an Environment Variable called [Also Delete from CoE](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-core-components.md#all-environment-variables).

If this environment variable is set to No, it will keep a record of deleted apps and flows and highlight them as deleted via a field. Depending on the filter you have on the data, you may then still see deleted apps and flows.

**Comment by manuelap-msft** [comment]
If you use the PowerShell https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerapp?view=pa-ps-latest do you still see the SharePoint form apps? 

I'm not sure that if deleting the SharePoint list / site actually deletes the associated apps. If they still show up in the PowerShell as well that would be a product behaviour that we should rule out first.

**Comment by bethleota** [comment]
@manuelap-msft I'm able to retrieve the app info using the Get command. However, when I try to remove the app using Remove cmdlet, I get a 500 Internal server error. attached example.
![CoE-RemoveAdminPowerApp1](https://user-images.githubusercontent.com/40639953/164289043-75af61dc-f48d-4eb1-980a-b36ae0ff1b68.jpg)

**Comment by Jenefer-Monroe** [comment]
I'm afraid this is an issue for the product team and not something that we can assist as the starter kit team. You will need to contact product support: [Get Help + Support - Power Platform | Microsoft Docs ](https://docs.microsoft.com/en-us/power-platform/admin/support-overview)

**Comment by bethleota** [comment]
@Jenefer-Monroe OK thank you. Appreciate your prompt reply.

**Comment by Jenefer-Monroe** [comment]
You are most welcome. I hope you are able to get the help you need from Product Support! 
I'll close this out now but please let us know if you have other questions.
