### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Log connection broken

### ISSUE THREAD

**Issue by kbirstein** [microsoft/coe-starter-kit#2530]
### What is your question?

The Audit Log feature stopped working about three weeks ago and I have not been able to get the flows to start again. The Admin | Sync Audit Logs flow fails with the error "The server did not receive a response from an upstream server. Request tracking id '08585511240374405323124006052CU100". The Inventory Sync works fine. I have reinstalled the CetnerofExcellenceAuditLogs_2.6_managed.zip to no avail. I am on the current version of the Core Components, April 2022, 3.18.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

April 2022

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

**Comment by kbirstein** [comment]
The failure is on the "Run a Child Flow" within the "Apply to each timeSegment" action and status code is 502. Error is the Bdy of the Run a Child Flow action is 
{
  "error": {
    "code": "NoResponse",
    "message": "The server did not receive a response from an upstream server. Request tracking id '08585511240374405323124006052CU100'."
  }

**Comment by kbirstein** [comment]
Now I see the error in the Child flow, Office 365 Management API failed. For some weird reason it is not authenicating with my service account while all other connections are fine with the service account.

**Comment by Jenefer-Monroe** [comment]
Hello. Please see https://github.com/microsoft/coe-starter-kit/issues/1424 

Unfortunately the connections for custom connectors are often lost on upgrade and need to be reset. I have some instructions in that bug to assist. 

Failed runs should be sending you an email alert to ensure you knew this was broken. Please take a look at your Admin Email environment variable and be sure you have access to whatever distribution list you used there.

**Comment by kbirstein** [comment]
Ok, will create connector again!

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kbirstein** [comment]
I spent several hours trying to edit the Office 365 Management API connector and when I get to the Test operation and click "+ New connection" nothing happens. The instructions say to "Select + New connection and then login with your account" but I am already logged in and no login box pops up so I'm stuck. If I skip over this and go to StartSubscription and type in the tenant and PublisherIdentifier the "Test operation" button does not become active. I note the instructions on https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog are old because the 4. Code Preview screen is not shown in the screenshots so I'm hoping that the instructions are accurate. I did get this to work when I set up the COE several months ago so I don't know what's wrong at this point. I REALLY need to get this auditing working AGAIN! It's been out for almost a month now. I simply can't afford to install the complete COE again because I can't afford to lose the history so what option do I have at this point??

**Comment by kbirstein** [comment]
Went through the troubleshooting steps. I am able to search the Audit Log in compliance.microsoft.com so the ID I am using for the COE so I do have rights to search the Audit log. And all IDs entered correctly.

**Comment by kbirstein** [comment]
So on a whim I went to Connections and clicked New Connection from there and was able to setup a new connection for the Office 365 Management API custom connector, while trying to set it up from the "Test" panel within the Custom Connector edit didn't work. Is this the way it's supposed to work? Should the instructions on https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#create-an-azure-ad-app-registration-for-the-office-365-management-api be updated?

**Comment by Jenefer-Monroe** [comment]
No you should not need to create the connection in the connectors page, you should be able to create it in the test page. 
 
You can validate that connection is healthy by using the ListContent operation which you fill with your tenant id and application id where it says publisher, and updating the dates to be recent. Does that work? 

![image](https://user-images.githubusercontent.com/89584709/164457910-908f2200-3edd-4d2d-8648-54b730a9f489.png)

**Comment by rfolgadoal** [comment]
We have the same issue. The connection has disappeared, and we have trouble logging in again (in the same tenant and app as before).

**Comment by Jenefer-Monroe** [comment]
I dont know what you mean by the connection disappeared. 
Note that the audit logs are based on a custom connector, and these have issues with upgrade and need to be fixed periodically as described here: https://github.com/microsoft/coe-starter-kit/issues/1424

**Comment by kbirstein** [comment]
@Jenefer-Monroe  The List Content does work in the custom connector now that I have a connection in the "Selected connection" above, which I created via "Connections" rather than in the Custom Connector "Test" pane. So it seems that maybe I should not have put in a new client secret in the Security pane in the Custom Connector but simply just created a new connection in "Connections" rather than messing around with the Custom Connector.

@rfolgadoal I suggest that you go to "Connections" under Data and see if you have an "Office 365 Management API" connection listed (see screenshot). If not click "+ New connection", type "Office 365 Management API" in the Search box and see if it asks you to login and create a connection. I think this may be all that is wrong.

![ManagementConnection](https://user-images.githubusercontent.com/13750516/164757897-fb587ea0-8c23-4ef5-8f33-d1d236b8cce3.jpg)

**Comment by rfolgadoal** [comment]
We have edited the connection following guide #1424 , and the flows are now working. Thanks!

**Comment by Jenefer-Monroe** [comment]
Great news. Thanks all.
