### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Logs collection

### ISSUE THREAD

**Issue by rjhowes73** [microsoft/coe-starter-kit#2532]
### What is your question?

I've followed the instructions to set up the audit log connector, including ...

Creating the app registration

Setup the custom connector

Update the app registration with the redirect URL

Start a subscription to audit log content (the test operation fails with a 400 but the error is "The subscription is already enabled. No property change." so I'm assuming that is because it is already setup.

Setup the Power Automate Flow

The "Admin | Sync Audit Logs" and "[Child] Sync Audit Logs" are both successfully running, but in the Power BI dashboard I am not seeing any launches or last ran data for any apps, they just report (blank).

I've validated that I can manually see app launches in the audit log so I know auditing is working correctly.  All I can think of is does the service account that the audit log flows run under need access to the audit logs?  I didn't think so as the app registration allows that, any ideas would be appreciated.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin - Sync Audit Logs, [Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
Please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

A picture like this showing if the flows are running successfully:
![image](https://user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png) 

And a picture like this showing if the data is populating
![image](https://user-images.githubusercontent.com/89584709/164469099-1cb27bec-a1b8-4a22-8b2c-c9bdb50d7d33.png)

**Comment by rjhowes73** [comment]
Hi Jenefer.  I installed the audit log connector weeks ago and no data is logged even for apps that I can see have been launched by looking at the audit logs.  Here is the custom connector (I recreated yesterday but it has been there for weeks).
![image](https://user-images.githubusercontent.com/50109597/164628464-6182db8b-0da1-47e4-95e0-f258f15b4d6e.png)

Here are the flows successfully running ...

![image](https://user-images.githubusercontent.com/50109597/164628826-47375150-cc62-4bf4-9a72-58ee2752daf4.png)

And here is an image from the audit logs ...

![image](https://user-images.githubusercontent.com/50109597/164631014-f713602e-b4bf-4c15-b778-d6148716c65c.png)

**Comment by rjhowes73** [comment]
Also, to demonstrate what I mean, this is one of the Apps that is shown as launched in the audit log, but in the Power BI report it is showing as no launches and no last ran.
![image](https://user-images.githubusercontent.com/50109597/164671649-98b04635-3e9c-4d86-aff2-184eadbc99b2.png)

**Comment by Jenefer-Monroe** [comment]
Is your Power BI being refreshed? Here is how to set it to auto-refresh https://docs.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh

**Comment by rjhowes73** [comment]
Hi Jenefer.  That was the problem, when I went to set up the refresh it was greyed out as it said the credentials were invalid, so I entered the service account creds, manually kicked off a refresh and after 30 minutes or so the dashboard has updated.

Thanks very much for your help.

![image](https://user-images.githubusercontent.com/50109597/164719039-ba57b90f-3538-4263-8eac-221f6d60f533.png)

**Comment by Jenefer-Monroe** [comment]
So glad this is resolved!
