### ISSUE TITLE
[CoE Starter Kit - BUG] App's Total Shared info is not being updated

### ISSUE THREAD

**Issue by jorgemorenog** [microsoft/coe-starter-kit#2534]
### Describe the issue

Dear colleagues,

We have noticed that the Total Shared field within the PowerApps App table is not being updated as usual:

![image](https://user-images.githubusercontent.com/10724478/164472738-c6200e51-3b94-4ceb-bf9d-79e04a0c1264.png)

The image shows the _most shared_ apps within our tenant. Weeks ago, we had that info properly fulfilled and updated.

We have seen this error after the installation of the last CoE Starter Kit version (3.37).

Thanks a lot for helping us out.

Best regards,

Jorge

### Expected Behavior

It should be shown the total of shared users as usual.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Hello this value is not available for Model Driven or SharePoint Apps, you should see it filled only for Canvas Apps, and only after the **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_** runs.

**Comment by jorgemorenog** [comment]
Hi @Jenefer-Monroe,

Thanks. I launched the flow, and finally, I saw it obtained more info. However, I see an interesting picture within a specific app.

On the one hand, we have it shared with a group and a person individually. It gives this picture:
![image](https://user-images.githubusercontent.com/10724478/165328733-b21306ed-0dc3-4bc2-a79c-f5f6e1f2ecc7.png)

It makes sense: the group has several users, and the final sum is six users.

On the other hand, I saw that the Total Shared is still zero:
![image](https://user-images.githubusercontent.com/10724478/165329029-ed4870ff-d802-4334-b2e7-674d8dd007e2.png)

I imagine that the calculation is ok, but is it not strange to show those differences?

Regarding the issue, I think it can be closed. Thanks!

Best regards,

Jorge

**Comment by Jenefer-Monroe** [comment]
Are you saying that total Shared field is not updating?

**Comment by jorgemorenog** [comment]
Yes. How should it work? Another example in another app:

![image](https://user-images.githubusercontent.com/10724478/167100611-16cbf5cc-b5c3-4a4b-a248-d3d21db7dc03.png)
![image](https://user-images.githubusercontent.com/10724478/167100645-dd2c62f4-cc23-456a-997a-7943f968365b.png)

:/

Thanks!

**Comment by Jenefer-Monroe** [comment]
I have not found any repros in our tenant of this
![image](https://user-images.githubusercontent.com/89584709/167606517-5c6d994e-aa9f-4033-bc33-664fe4065802.png)

Is this just occuring as a one-off on a single app or is it a general issue? 

Can you see if you have solution layers on the PowerApps Apps table? 

And then also see if the equation is correct? 
![image](https://user-images.githubusercontent.com/89584709/167607418-015f092b-83bc-43d2-b47f-cb7d34451197.png)

**Comment by jorgemorenog** [comment]
It's quite strange. Here is our context:
![image](https://user-images.githubusercontent.com/10724478/167657270-4441835f-6076-4fbe-8893-1943f734867d.png)

- Total Shared: 0
- 3 groups with users...

Btw, our interface is a bit different (solution version 3.37).

And the equation is right:
![image](https://user-images.githubusercontent.com/10724478/167657610-539e3e30-f822-493c-9ee7-77562e4b5b13.png)

Do you think if I update with the last version of the CoE Starter Kit it could be resolved? Thanks.

**Comment by Jenefer-Monroe** [comment]
Yes there may have been a bug in the past that got addressed. Please do try taht.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
