### ISSUE TITLE
[CoE Starter Kit - BUG] Loading blocked:step 'Outer Join'- Production_CoEDashboard_April2022

### ISSUE THREAD

**Issue by tmcg19** [microsoft/coe-starter-kit#2535]
### Describe the issue

Just tried to open the lasted production "Production_CoEDashboard_April2022.pbit" and get the following Error, looks to be a Outer Join issue in Connections References":
OrgUrl
Loading blocked by failures with other queries.
Environment
Loading blocked by failures with other queries.
Flow Connection Reference
Query 'Flow Connection Reference' (step 'Outer Join') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination.
App Connection Reference
Query 'App Connection Reference' (step 'Outer Join') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination.

### Expected Behavior

open login and load dashboard so I can then publish to Power BI

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

latest APril 2022

### What app or flow are you having the issue with?

Production_CoEDashboard_April2022.pbit

### Steps To Reproduce

download COE, extract Production_CoEDashboard_April2022.pbit, open report in lasted powerBI desktop, login, refeash/load

**Comment by Jenefer-Monroe** [comment]
Have you updated Core to 3.37 already? You need to keep the solutions and the Power BI files in sync.

**Comment by tmcg19** [comment]
No on an older version. so I tried the older PowerBI report, I tried Jan22, Dec21, sept21 and Aug21, and all give an error.
Is this a connection issue, and any help as to how I pinpoint the issue:
DataSource.Error: Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
Details:
    DataSourceKind=CommonDataService
    DataSourcePath=orged82fdc8.crm.dynamics.com
    Message=A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
    ErrorCode=-2146232060
    Number=53
    Class=20

**Comment by Jenefer-Monroe** [comment]
Looks like you now aren't even connecting to the server. Likely for this issue you entered the envt name incorrectly. Please see https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard

**Comment by tmcg19** [comment]
environment name is correct, copied from admin center. also have tried with and without https:// and ending /, gat an error informing to remove https://. .. so environment name enter correctly

**Comment by Jenefer-Monroe** [comment]
Are you logged in to Power BI with an identity that has admin access to the envt?

**Comment by tmcg19** [comment]
yes

**Comment by Jenefer-Monroe** [comment]
I'm afraid I cannot help here. You are unable to connect to the server, there may be issues as described here
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting

But these are issues specific to your tenant and outside the scope of the starter kit to assist.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by russrimm** [comment]
I got this same error in the December 2022 Power BI version and just renamed a column and renamed it back and applied and it resolved it. @Jenefer-Monroe
