### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Desktop Flow - Runs) - Upsert the RPA Session record NotFound

### ISSUE THREAD

**Issue by rfolgadoal** [microsoft/coe-starter-kit#2537]
### Describe the issue

Hi,

When this flow lists the RPA Flow sessions and then tries to upsert the RPA Session record is always returning NotFound.

<img width="256" alt="image" src="https://user-images.githubusercontent.com/93584307/164700402-59ce639f-452c-49db-ba11-92bdd0369393.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop Flow - Runs)

**Comment by Jenefer-Monroe** [comment]
Please look to see if the flow is in the Desktop Flow table. 
And if not please look at the run of **_Admin | Sync Template v3 (Desktop flows)_** for that environment (note that you can trigger the run for that specific environment by changing a property of it in the **_Power Platform Admin View_** app)

**Comment by rfolgadoal** [comment]
I have looked with advanced find in the Desktop Flow table for the flow by data of some sessions (by the parentWorkflowId in context property), but I didn't find them. I don't know if is it the correct flow id.

![image](https://user-images.githubusercontent.com/93584307/165936375-9ddbb392-d521-48c3-9e0e-5af106230fc0.png)

For example, as you can see in the screenshot, the loop to "Apply to each" action failed for most of the 125 flow sessions because it's not founding them.

**Comment by Jenefer-Monroe** [comment]
Yes I'm afraid your Desktop Flows are not getting inventoried. This is a known limitation in the starter kit due to lack of connector access. Please see: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#large-desktop-flows

This limitation will be addressed by this feature, if you would like to track. 
https://github.com/microsoft/coe-starter-kit/issues/2607

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
