### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin access information

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2540]
### What is your question?

What appened if an admin without Power Platform admin role use Power Platform Admin View? He can see all information stored inside Dataverse?

Thnaks

**Comment by Jenefer-Monroe** [comment]
I don't know what you mean by Admin.

Power Platform Admin role is needed to do many things in the starter kit, it lets you collect and act on environments and objects to which you do not have direct access. 

The Power Platform Admin Security Role shipped with Core just gets you admin access to the CoE environment. This means they can see and act on the data in the environment.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
