### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to see other workloads on audit logs

### ISSUE THREAD

**Issue by yingying96** [microsoft/coe-starter-kit#2544]
### Describe the issue

We are only seeing powerapps workload via power platform admin view dashboard

![image](https://user-images.githubusercontent.com/19566726/165013500-352211f4-0b44-4593-a787-d85357136c03.png)

### Expected Behavior

It should have all the workloads e.g. power automate, pva.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Sync Logs

### Steps To Reproduce

1. Download the CoE toolkit
2. Setup the necessary components and enable audit logging.

**Comment by Jenefer-Monroe** [comment]
Unfortunately we only have access to Power Apps launces via the office logs so this is a known limitation.
