### ISSUE TITLE
[CoE Starter Kit - QUESTION] Querying and updating manager details from Makers table

### ISSUE THREAD

**Issue by BhargavPrasadGorakanti** [microsoft/coe-starter-kit#2550]
### What is your question?

As per this [issue resolution,](https://github.com/microsoft/coe-starter-kit/issues/1796) M1 and M2 Managers are no longer added to Makers table. Instead their details are queried using an O365 connector. 

However, the **Helper | Maker Check** flow still tries to fetch Manager display name value from Makers table by filtering Row ID using Manager's GUID value. Attaching a screenshot below for reference. This doesn't seem like a critical issue as another scheduled flow - **CLEANUP - Admin | Sync Template v3 (Orphaned Makers)** takes care of Manager field updates in Makers table but it runs on a weekly basis and doesn't update manager details immediately. 

Just wanted to check if any change / enhancement is planned for a future release? 

![HelperMakerCheck](https://user-images.githubusercontent.com/43746286/165094564-05b3265c-4b44-4a3f-964d-6b931f268a48.PNG)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Helper | Maker Check

**Comment by Jenefer-Monroe** [comment]
Yes we will just rely on the Orphaned clean up for now to make this correct. There are a few potential changes that will be used to address this depending on product team funding, but for now this is what we will have to offer

Note we do have this catch for the event that the manager is not in the maker table. 
![image](https://user-images.githubusercontent.com/89584709/165095845-730866eb-3d1e-4ae9-8bfc-a5ee932c1f01.png)

Thanks for using CoE!

**Comment by BhargavPrasadGorakanti** [comment]
Got it, thank you @Jenefer-Monroe!

I have another follow-up question reg. Makers table. We're planning to use the resource count rollup columns (Number of Apps, Number of flows, etc.) to filter out Makers with 0 resources and then delete them to do a cleanup activity. This is to remove Managers that were added due to that bug from an older version of CoE (1796). Is there a better way you'd recommend to go about the cleanup? 

Thank you,
Bhargav

**Comment by Jenefer-Monroe** [comment]
That makes sense to me!

**Comment by BhargavPrasadGorakanti** [comment]
Thank you.
