### ISSUE TITLE
[CoE Starter Kit - BUG] [CoE Starter Kit - BUG] Admin | Sync Template v3 - unable to save CoE Flows

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#2554]
### Describe the issue

![image](https://user-images.githubusercontent.com/8484048/165155791-ba864670-659b-4bd0-a96c-4b69b5c27227.png)

### Expected Behavior

I should be able to save the Flow.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin - Sync Template V3

### Steps To Reproduce

Edit flow Admin | SYnc Template V3.

Save Admin |Sync Template V3

Unable to save.

### Anything else?

![image](https://user-images.githubusercontent.com/8484048/165156279-11d188c5-9513-4268-b9b1-36ff55c517e2.png)
![image](https://user-images.githubusercontent.com/8484048/165156370-7ae3a541-fa4a-44d7-97b3-2dcfea59ab13.png)

**Comment by Jenefer-Monroe** [comment]
I dont repro this. If you hover over the output parameter there, what does it say its an output of? I'm trying to determine what field is broken, I think its the GUID itself as shown here
![image](https://user-images.githubusercontent.com/89584709/165165475-3ce8f673-5eff-416d-bfde-b41d67922ced.png)

Please also go look at your Environment table, you do still have that field there correct?
![image](https://user-images.githubusercontent.com/89584709/165165904-3bd5774b-e1d7-452b-a3b3-aeba7d6f41ff.png)

**Comment by NPrice99** [comment]
I dont have "Environment" Property -
![image](https://user-images.githubusercontent.com/8484048/165256454-4189e17a-5d5e-4079-bddd-0307a89c6275.png)
However, 
![image](https://user-images.githubusercontent.com/8484048/165256760-c602f2d4-183a-4830-b2ad-8469c9fb398e.png)
Outputs here is Outputs('Remove_any_environment_prefix').
The solution was downloaded from the github site yesterday afternoon -
![image](https://user-images.githubusercontent.com/8484048/165257310-61cf3bc3-9c0a-41c0-9922-00e94956871d.png)

**Comment by NPrice99** [comment]
yes Environment field is there -
![image](https://user-images.githubusercontent.com/8484048/165265246-100313df-63b1-4bce-b7e4-4f09df89479e.png)

**Comment by Jenefer-Monroe** [comment]
Have you already checked to see if it has unmanaged layers? This is looking like a product issue. The flow is saying it doesnt see a field that is clearly there.

**Comment by NPrice99** [comment]
I have checked and there is only the original layer.

**Comment by Jenefer-Monroe** [comment]
It appears you've hit some kind of product issue then. I have never seen this before.

**Comment by NPrice99** [comment]
I wonder - this environment is at 2022 wave 1.  Have you tried with an environment at 2022 wave 1 ?

**Comment by Jenefer-Monroe** [comment]
A second repro was just posted, looks like a change is rolling out. Can you please test by trying to create a new Environment in the inventory as shown here
Basically just give it a name that will be easy to spot and clean up, and some fake GUID
![image](https://user-images.githubusercontent.com/89584709/165551348-2bcead3c-d40c-4fe3-b578-124177e5ba2c.png)

**Comment by NPrice99** [comment]
Hi Jenefer
I followed your instructions and the Fake environment was created successfully.

![image](https://user-images.githubusercontent.com/8484048/165567076-54aa3402-5c5c-4994-87bb-e5d22b4b4731.png)



Regards

Nigel

**Comment by Jenefer-Monroe** [comment]
So it did not succeed in that you could not force the GUID. Correct?

**Comment by NPrice99** [comment]
No - I could force the GUID.  Please my screenshots

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jenefer-Monroe** [comment]
thanks just validating. This is a product issue, we are pursuing.

**Comment by NPrice99** [comment]
If there is anything I can do to help  please do not hesitate to contact me.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jenefer-Monroe** [comment]
Can you create a new environment (teams is ok) and see if this flow runs?

**Comment by Jenefer-Monroe** [comment]
From conversations offline, current state:

-	Connector no longer offers uniqueid field in flow
-	Existing flows/solutions that use this field can no longer be edited. 
-	Existing flows/solutions that use this field will still run correctly. 

This is a product regression, please create a support ticket using the information above.

**Comment by manuelap-msft** [comment]
Hi Nigel,

just to keep you in the loop (and thanks for the thorough help in investigating!), this is a product regression. It's now rolled out to our US tenant so we repo this as well. We've worked with the Power Automate team to investigate this further yesterday but no resolution yet. 

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
This product regression has been reverted. We should be back to business. Thanks for posting!
