### ISSUE TITLE
[ALM Accelerator - Feature]: Permission for Build Service user

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#2558]
### Is your feature request related to a problem? Please describe.

Setup of AA4PP by CoE CLI is not complete. The permission of a created build pipelines must be granted manually:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/15800069/165267794-9c8c69c6-97c8-42af-beb2-dc6aeb06633e.png">

### Describe the solution you'd like

Please grant permission for Pipeline Build Service user to access:
* Service Connection
* Variable Group
* Repository 
during setup from CoE CLI.

Name of Build Service user is: `<Project Name> Build Service (<Organization>)`

### Describe alternatives you've considered

Manual permitting must be done for each first pipeline run to access the resources

### Additional context?

This is related to CoE CLI commands:

```
coe alm install...
coe alm branch ...
```

**Comment by mikefactorial** [comment]
These instructions have been added to the docs. Closing this out.
