### ISSUE TITLE
[ALM Accelerator - Feature]: Service Connections authorization for Build Service during CoE CLI setup

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#2559]
### Is your feature request related to a problem? Please describe.

The Build Service user have no permission after CoE CLI setup to access the Service Connections.

The pipeline fails, because of:
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/15800069/165270252-9501216d-1e80-4021-a42a-91af1d711d73.png">

### Describe the solution you'd like

Automatic adding the project Build Service user to permission group `Endpoint Administrators` during CoE CLI.

Permission Group:
<img width="609" alt="image" src="https://user-images.githubusercontent.com/15800069/165270707-a539552f-9ce3-4779-8e05-6d9dd3644af8.png">

Each Service Security configuration inherited automatically:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/15800069/165271045-efa25fe5-b771-40be-9604-65a682fd714e.png">

COE CLI setup for DevOps by using:
```
coe alm install ...
```

### Describe alternatives you've considered

Manual adding the Build Service user to the Permission Group `Endpoint Administrators`

### Additional context?

related to coe cli setup for azure devops

**Comment by mikefactorial** [comment]
Related to #2558. Didn't see this one before I replied to #2558 will look into the best way to implement this in the cli. Thanks again @megel

**Comment by mikefactorial** [comment]
Closing this out as it is part of the ALM Accelerator Project Wizard and we're moving away from investing in additional cli functionality in favor of the admin app setup.
