### ISSUE TITLE
Not able to see Solution Name and Build Number while clicking IMPORT SOLUTION from powerapps

### ISSUE THREAD

**Issue by chinmaysahoo19** [microsoft/coe-starter-kit#256]
**Describe the bug**

**To Reproduce**
1. Open APP "ALM Accelerator for Advanced Makers"
2.  Click on IMPORT SOLUTION
3. Check Solution Name and Build Number 
4. See error    "Value is coming as Blank."

**Expected behavior**
Expecting to see Solution Name and Build Number

**Screenshots**

![image](https://user-images.githubusercontent.com/20070794/116909984-92f34900-ac0a-11eb-9e13-01373f2d9e19.png)

**Additional context**
I am using latest release.

**Comment by mikefactorial** [comment]
@chinmaysahoo19 note that we have plans to make this experience more intuitive going forward per #122 in our backlog. However, the first thing to check is that you've named your solution pipelines according to the following pattern

deploy-validation-SolutionName
deploy-test-SolutionName
deploy-prod-SolutionName

![image](https://user-images.githubusercontent.com/42348035/116917758-15850400-ac1d-11eb-864b-9dccf67d0728.png)


The latest release will show builds that were triggered from deploy-validation-SolutionName. We recently made an update to pull from builds of deploy-test-SolutionName which made more sense, but as I mentioned isn't the long term solution for this. The future UX would likely allow for users to select a branch. If you have any feedback on what the best UX would be for this feel free to comment on #122. We'd love to get others opinions.

**Comment by mikefactorial** [comment]
@chinmaysahoo19 Closing this issue for now. Feel free to respond in the discussions if you have additional questions. https://github.com/microsoft/coe-starter-kit/discussions
