### ISSUE TITLE
[CoE Starter Kit - QUESTION] is Flow / App State being treated or used?

### ISSUE THREAD

**Issue by mrramosjr21** [microsoft/coe-starter-kit#2561]
### What is your question?

Hi, I'm writing this question because we have a user that receives archival email that the flow is not modified for the past 6mons.
User claims that the flow is currently off for his future reference.

Upon checking in the Power Platform Admin View the state of the flow is currently Started.
![image](https://user-images.githubusercontent.com/20808214/165289498-a6ca4bda-6baf-48a1-b53b-33d0a5a35346.png)

User sent me this and his flow is currently off, so he shouldn't received any archival emails.
![image](https://user-images.githubusercontent.com/20808214/165289694-632f2fd6-abfd-45a2-a6b8-c454498909a0.png)

I also noticed this in my Teams flow.
So, my flow sends a chat every time a new email is received.
I turned it Off 4 days ago, but keep receiving chats.
Flow
![image](https://user-images.githubusercontent.com/20808214/165290201-4cefdc4d-e1ff-4973-9ebb-ab8163def5a6.png)
Teams Chat
![image](https://user-images.githubusercontent.com/20808214/165290095-3ba28061-8815-43f3-8d79-50619b80dad0.png)

**Expected Behavior**
1. User shouldn't receive any archival flow email if the flow is off
2. Team flow shouldn't run/process if the flow is off.

### What solution version are you using?

3.20.6

**Comment by Jenefer-Monroe** [comment]
We do not update this today unless the flow is edited. But updating it is part of a feature targeting June release. 
Please see https://github.com/microsoft/coe-starter-kit/issues/2276

Please watch that bug for traction on this work item. 
Thanks for posting!

**Comment by Jenefer-Monroe** [comment]
Happy to help! I'll go ahead and close this one then if thats ok, and you can track that other issue?

**Comment by Jenefer-Monroe** [comment]
thank you.

**Comment by Jenefer-Monroe** [comment]
Just an update that this is local fixed for July.
