### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is it possible to change the account for the CoE Starter Kit solutions?

### ISSUE THREAD

**Issue by math1san** [microsoft/coe-starter-kit#2563]
### What is your question?

When we deployed the CoE Starter Kit core solution at our organization in the summer of 2020, we did so using an account tied to a user with the Power Platform Admin role (ex. user@xyz.com).

All subsequent solutions (governance, nurture, innovation backlog, etc.) were also deployed with this account and thus all components (apps, flows, env. variables, connection references, etc.) were owned/configured with this account.

Fast forward to now, our organization is transitioning to Azure PIM to manage the Power Platform Admin role and the original account will have to be moved to a service account (ex. ppsvc@xyz.com) that will be configured with the Power Platform Admin role but not onboarded to Azure PIM.

This question/issue is being opened to get the following assistance/guidance:

1. Is it possible to transition all components of the CoE Starter Kit solutions to be owned/configured using a new account? i.e. updating the ownership of the components and connection references seamlessly?
2. If the above is not possible, is there a way to update the ownership of the components/connection references sitting in a managed solution manually?
3. Are solution upgrades only supported with the original account that was used to deploy the CoE Starter Kit solutions?
4. Do we potentially have to re-deploy the CoE Starter Kit to a fresh environment using the new account if we want a clean solution?

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2022

**Comment by math1san** [comment]
Thanks for the quick response Jenefer.

Due to organizational policies, I'm unable to post to GitHub from our corporate network so will provide a summary of what I've attempted.

- We have the CoE Starter Kit deployed in two tenants (DEV/PROD)
- I'm currently working in the DEV tenant to document the procedure of what I need to do to successfully transition the user account to the new (service) account

1. Initiated an upgrade of the core solution from Jan 2022 to Apr 2022 using the new service account but it threw an error during the uninstall of the old version (8004F01D - solution dependencies exist, cannot uninstall) so had to revert the upgrade (removed the new version manually)
2. On my second attempt with the new service account, I used the "update" option and that upgraded the core solution successfully (however, it did not migrate the old connection references to the new identity). It did prompt me for new connections to setup and those were tied to the new service account.
3. Because of #2, our COE flows are currently not associated with a valid connection reference; creating connection references manually for the new service account has been completed but unsure how to associate it with the COE flows as they are in a managed solution. Any thoughts on this part?
4. I'll use the Set App/Set Flow permissions tools to reset the ownership to the new account, but what do I do about the environment variables/connection references that remain in the managed solution under the old account?

Hopefully this paints a better picture and can provide more insight if needed.
- In the past, I was able to perform the upgrade successfully using the original deployment account; however, this time, I decided to attempt it again but this time used the "update" option and that was successful
- Even
-

**Comment by Jenefer-Monroe** [comment]
Can you clarify, are you using the ALM Accelerator for your work or doing these things manually?

**Comment by math1san** [comment]
No, we are not using the ALM Accelerator at our org. CoE starter kit has been deployed manually.

**Comment by Niqlash** [comment]
Hi @math1san 
We've faced exactly the same issue a couple of months ago. What we've come up with is to re-assign the processes using the Dynamics WebClient interface which worked perfectly. However, please be aware that this will only work inside solutions:

1. Go to Dynamics 365 organization associated with the environment. For this, the simplest way is to connect to make.powerapps.com, then select your CoE environment and then on the top right click on the settings (gear) icon to choose the "Advanced Settings"

2. In the legacy WebClient (it should open in a new tab) open the Advanced Find by clicking on the filter icon in the top right of the header bar

3. Use the following filters:

![Filter](https://user-images.githubusercontent.com/34491116/165504946-8ac9ee02-2610-444b-9b5e-1f2486b080a0.png)

4. Select the Modern Flow and click on ‘Assign Processes’

![Assign](https://user-images.githubusercontent.com/34491116/165504979-3706d453-4d3c-42a4-ac76-83202e9a4867.png)

This example is for Power Automate flows, however you may use the similar capabilities for other objects as well. E.g. for Connection References it's just a matter of changing the associated connection within the reference to the service account:

![Connection Reference](https://user-images.githubusercontent.com/34491116/165505346-13e7567b-3f87-4b4c-acf6-f7751de2beea.png)

I hope this helps you out at least a bit, I just stumbled across your post by chance.

**Comment by Jenefer-Monroe** [comment]
Marking as a documentation issue for us
Thanks for your help too @Niqlash

**Comment by math1san** [comment]
Thanks for the suggestion @Niqlash!

We tried it along with Power Apps PowerShell cmdlets but in the end, it didn't feel like a clean transition so decided to re-deploy the CoE solution to a fresh environment. This will likely save us from troubleshooting upgrades/issues in the future.

@Jenefer-Monroe hopefully there will be some documentation around how to do this if ALM is not used; this issue can be closed.

**Comment by manuelap-msft** [comment]
closing out some old issues that we missed to close
