### ISSUE TITLE
[ALM Accelerator - BUG]: Get-CrmConnection, Failed to connect to CRM: Invalid Login Information

### ISSUE THREAD

**Issue by NagulapallyLaxmanGoud** [microsoft/coe-starter-kit#2564]
### Describe the issue

When I am trying to deploy the solution from AA4PP app, deployment to validation (deploy-Validation-SolutionName) pipeline is triggering, but at the step for Set EnvironmentId its failing. The error is:

Get-CrmConnection : Failed to connect to CRM: Invalid Login Information : The HTTP request was forbidden with client.

![ALM-SetEnvIdBug](https://user-images.githubusercontent.com/99319322/165352049-22b44fc9-5612-4a00-9c45-a94ee9e2ca24.png)

### Expected Behavior

Under deployment to validation (deploy-Validation-SolutionName) pipeline, Set EnvironmentID job has to be succeded and pass to the next step.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April 2022

### Steps To Reproduce

Using the ALM for Power Apps Accelerator

Click on Deploy solution
Deploy solution to Validation
Deployment continues till Set EnvironmentId

**Comment by mikefactorial** [comment]
@NagulapallyLaxmanGoud this appears to be an issue with the service principal connecting to your deployment environment. Can you verify that the SP is registered in the target environment? You can check in the admin center or try running the following powershell script with your Service Principal's information to check.

![image](https://user-images.githubusercontent.com/42348035/165388651-1e530c00-7dca-4ecc-83e1-84620fe1e8f9.png)


```
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
    Install-Module -Name Microsoft.Xrm.Data.Powershell -RequiredVersion 2.8.12
    Import-Module Microsoft.PowerApps.Administration.PowerShell -Force -RequiredVersion $(PowerAppsAdminModuleVersion) -ArgumentList @{ NonInteractive = $true }

    $clientId = "CLIENT_ID"
    $clientSecret = "CLIENT_SECRET"
    $tenantId = "TENANT_ID"
    $url = "https://DEV_ENVIRONMENT.crm.dynamics.com/"
    $connstr = "AuthType=ClientSecret;ClientId=$clientId;ClientSecret=$clientSecret;Url=$url"
    $conn = Get-CrmConnection -ConnectionString "AuthType=ClientSecret;ClientId=$clientId;ClientSecret=$clientSecret;Url=$url"

    $systemuserResult = Get-CrmRecords -conn $conn -EntityLogicalName systemuser -Fields "azureactivedirectoryobjectid"
    echo $systemuserResult.CrmRecords[0]
```

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here. Feel free to open a new issue if this persists.

**Comment by ImranCodeBug** [comment]
@mikefactorial i am having the issue. it seems to be a relatively recent thing as this was running before,
```
function New-PP-Connection
{
    param(
        [Parameter(Mandatory)] [string] $clientId,
        [Parameter(Mandatory)] [string] $clientSecret,
        [Parameter(Mandatory)] [string] $url
    )
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
    $moduleName = "Microsoft.Xrm.Tooling.CrmConnector.PowerShell"
    $connectionString = "AuthType=ClientSecret;url=$url;ClientId=$clientId;ClientSecret=$clientSecret"

    if(-not(Get-Module -ListAvailable -Name $moduleName)){
        Write-Host "Installaing the moduel $moduleName"
        Install-Module $moduleName -Scope CurrentUser
    }
    Import-Module $moduleName

    write-host "Creating dynamics connection"
    $crmClient = Get-CrmConnection -ConnectionString $connectionString;
    write-host "Crm Client Created"  
}
``` 
![image](https://github.com/microsoft/coe-starter-kit/assets/53155339/8005399d-f876-4b2e-9ed2-00002c67516f)

**Comment by ImranCodeBug** [comment]
I found the issue. `Get-CrmConnection` only works when there is just one secret for the app registration. if you have more than one secrets it gives you the error above.
