### ISSUE TITLE
[ALM Accelerator - QUESTION] DeployToProd flow can't be turned on for ALM Accelerator for Maker

### ISSUE THREAD

**Issue by Xave686** [microsoft/coe-starter-kit#2567]
### What is your question?

Hi everyone, 

Have any of you run into this issue when you try to turn on the DeployToProd flow in the ALM Accelerator for Maker?

![Capture](https://user-images.githubusercontent.com/103982384/165439419-06b3d45a-7559-4db9-9a50-f07e4569d0f8.PNG)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

**Comment by mikefactorial** [comment]
@Xave686 haven't seen this particular issue before. Is there anything in the flow checker if you edit the flow that might shed some light on why it can't be activated?

**Comment by Xave686** [comment]
@mikefactorial I didn't edit the flow. It was turned off initially. When I wanted to turn it on, it just spits that error. And because of this flow not being turned on, DeploytoStage can't be turned on too as they are both related.

**Comment by mikefactorial** [comment]
Thanks @Xave686 was wondering if you see anything if you try editing the flow that might help understand the problem.
