### ISSUE TITLE
[CoE Starter Kit - QUESTION] Avoid environments

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#2570]
### What is your question?

Hi, is possible to avoid environments in the collect data to the inventory?

### What solution are you experiencing the issue with?

Core

**Comment by manuelap-msft** [comment]
Hello,

it is not, at the moment data for all environments is collected. Could you please explain your use case for wanting to avoid environments being collected?

Thank you
Manuela

**Comment by albertocaa1317** [comment]
Hi Manuela,
I don't want to show the data of some environments in the dashboard, like CoE Environments, but thinking better I can filter it in the PBI Dashboard! 😆
