### ISSUE TITLE
[ALM Accelerator - Azure git] Does it supports azure git?

### ISSUE THREAD

**Issue by yingying96** [microsoft/coe-starter-kit#2578]
### What is your question?

Hi Team,

Can i check if the following supports azure git? Thanks!

https://docs.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-components

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Apr 2022

**Comment by mikefactorial** [comment]
@yingying96 the ALM Accelerator for Makers, you referenced the docs for, does not support Azure Git. 

The ALM Accelerator for Power Platform does support Azure Git and Azure DevOps pipelines. https://docs.microsoft.com/en-us/power-platform/guidance/coe/almacceleratorpowerplatform-components
