### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flows) - Insert New Flow record actions referencing item/admin_flowid not part of the schema

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#2579]
### Describe the issue

"Insert New Flow record" action in "Admin | Sync Template v3 (Flows)" is referencing field item/admin_flowid not part of the schema. I ran into this issue when trying to create custom version of this sync flow and are not able to save the flow

<img width="641" alt="image" src="https://user-images.githubusercontent.com/8307644/165541966-f8a94493-3cc8-466b-a84f-863a37cda233.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

**Comment by Jenefer-Monroe** [comment]
Can you please create a new flow in the CoE environment and try to add a fake flow to the inventory like this? 
Basically add a display name that will be obvious and easy to clean up, point to a known environment in your inventory, and add a fake GUID

![image](https://user-images.githubusercontent.com/89584709/165549291-20047935-c298-4fd4-848a-e7215ca91e9d.png)

**Comment by Jenefer-Monroe** [comment]
Have confirmed with another customer that this is not the case, the ability to force the GUID is removed from the connector in your product version

**Comment by Jenefer-Monroe** [comment]
Can you please create a new environment (teams is ok) and see what gets created?

1)	Create a new environment with some easy to spot name (Teams type environment is ok)
2)	Run the main sync template: **_Admin | Sync Template v3_** 
3)	Export the data in the environment table and find your new environment in the list. 

Check:  are the Name and Environment GUIDs the same? 
![image](https://user-images.githubusercontent.com/89584709/165613501-d1978af1-954f-4c14-b2b3-78fa20259128.png)

**Comment by Jenefer-Monroe** [comment]
From conversations offline, current state:

-	Connector no longer offers uniqueid field in flow
-	Existing flows/solutions that use this field can no longer be edited. 
-	Existing flows/solutions that use this field will still run correctly. 

This is a product regression, please continue to push with the product team to address.

**Comment by Jenefer-Monroe** [comment]
This product regression has been reverted. We should be back to business. Thanks for posting!
