### ISSUE TITLE
[CoE Starter Kit - QUESTION] - cannot find Admin - Power Platform Resource RMS.

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#2581]
### What is your question?

The documentation - https://docs.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt#admin-approve-or-deny-an-environment-request talks about a PowerApp - Admin - Power Platform Resource RMS.

But it is not here -

![image](https://user-images.githubusercontent.com/8484048/165555032-fff6f384-bd83-4832-9e5c-d0c215b78312.png)

### What solution version are you using?

3.37

**Comment by NPrice99** [comment]
Hi Manuela
The Admin - Environment Request PowerApp does not actually create the Environment.  I cannot see the code anywhere to actually create the environment and there is alot of code commented out on the "approve" button "OnSelect" property.

Regards

Nigel.

**Comment by manuelap-msft** [comment]
This is a bug that's already being tracked: #2511
This link includes a patch to install or instructions on what to update if you want to fix yourself.

**Comment by NPrice99** [comment]
Thanks Manuela - That works great.

Thank you very much

Nigel
