### ISSUE TITLE
A few questions and suggestions about the AuditLog component flows

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#2587]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/2584

<div type='discussions-op-text'>

<sup>Originally posted by **Hjaf** April 28, 2022</sup>
I'm trying to get a better picture of the AuditLog components and its configuration, I have a few questions and possible suggestions.

* Is there a valid scenario for providing lower value for **TimeSegment-CountLimit** than the combination of **TimeInterval-Interval**, **TimeInterval-Unit** and **StartTime-Interval** would require in minimum to get all the records? 
  It seems that if the CountLimit is set to a value lower than the minimum amount needed, this will likely produce an email notification     about the chunk size and truncated results because the last request will span from the time at last iteration until one minute before the parent flow was triggered: 
  ![HardcodedEndTime](https://user-images.githubusercontent.com/50009020/165682260-be53432c-aa1a-4730-8dc7-6bc4390d7f26.png)

  The above results in the last request (CountLimit) asking for remaining time:
![LastRequestTimeFrame](https://user-images.githubusercontent.com/50009020/165682633-72f7d70f-0c80-4b45-a078-8b2c86577faf.png) 

* Can we instead use the parent flow to notify about the CountLimit being to low to cover the time as well as summarize all the child flows with truncate warnings?

* Could using the next link response (truncated) from the API be used directly by the parent flow instead of providing the time interval in the child flow? I.e. continue following the next-link until the EndTime is reached. Won't this reduce the amount of requests to the API, especially when density of the audit logs is varies? 

* There are some 429 (too many requests) from the GetContentDetails request in the Apply To Each Cluster loop, and I notice the concurrency for the loop is set to 50:
![image](https://user-images.githubusercontent.com/50009020/165685587-b0bc59e0-2c75-40d6-aad2-0048237c3fc3.png)
   I suspect this is part of the reason for 429 errors in these requests.

  Why is this set to 50, and what would be the drawback of reducing this?
</div>

**Comment by manuelap-msft** [comment]
Due to our investment in BYODL, we will not invest further in performance improvements in the Audit Log connector. Customers who hit limits will move to BYODL.
