### ISSUE TITLE
[ALM Accelerator - BUG]: Production pipeline not triggering automatically

### ISSUE THREAD

**Issue by NagulapallyLaxmanGoud** [microsoft/coe-starter-kit#2590]
### Describe the issue

Following the Bug Id : 2325 I have made the small change as suggested.

Changed
git clone -b "main" "https://github.com/microsoft/coe-starter-kit.git"
to
git clone -b "mochs-coe-cli-debugging" "https://github.com/microsoft/coe-starter-kit.git"
in the update-deployment-settings.ps1

I am now able to deploy the solution to test after completing the pull request automatically, but it's not triggering solution to deploy into prod. 

Is there anything that I have to change in order to trigger the (deploy-prod-SolutionName) pipeline automatically.

### Expected Behavior

deploy-prod-SolutionName pipelineshould trigger automatically without any manual configuration

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April 2022

### Steps To Reproduce

Click on the "Deploy Solution" Button in AA4pp App, selected the Source Branch and Target Branch.
Now Clicked on Deploy Solution Button.
Click on Processing icon --> Navigates to Azure Devops, After the successful completion of Pipeline go to pull requests
Approve the PR and click on the complete the merge, Now Test and Prod should trigger automatically.

**Comment by mikefactorial** [comment]
@NagulapallyLaxmanGoud dpoloyment to prod would happen when a PR is submitted from the solution branch to the main branch you can see the triggers in the deploy-prod-solutionname.yml here's an example. If you primary branch is named something other than main that could be the issue.

![image](https://user-images.githubusercontent.com/42348035/165846501-72f5528c-bda1-4ee5-952b-9d73cb916ae4.png)

**Comment by mikefactorial** [comment]
Can you verify that the PR created by deploying to Prod creates a PR from the solution branch to a branch named "main"?

**Comment by mikefactorial** [comment]
Closing this issue as there's been no response. Feel free to create a new issue if this is still an issue.
