### ISSUE TITLE
[CoE Starter Kit - GENERAL INFORMATION APP] APP SHARED WITH (LIST) EMPTY

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#2591]
### What is your question?

Hello,

Why my APP SHARED WITH (LIST) and APP SHARED WITH is empty in the Power Platform Admin View?  I can see the number of APP SHARED USERS but in the list, nothing is there.

Can you please help me?

![image](https://user-images.githubusercontent.com/7468628/165887303-e3113848-301c-4fbc-b259-ca0f5ebfacc6.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by manuelap-msft** [comment]
Hello,

can you confirm the CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) flow is running?

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
