### ISSUE TITLE
[ALM Accelerator - BUG]:Missing connection under Connections Reference

### ISSUE THREAD

**Issue by rsantos00** [microsoft/coe-starter-kit#2596]
### Describe the issue

When I'm creating a Deployment Settings and look for Connection References it doesn't show all the connections, the authenticated user has access.

When I enter the Connections from the Power Apps portal I can see all the connections, but when I'm using the Accelerator I don't see them under "Connection References".

### Expected Behavior

See all connections created by the logged-in user in the Accelerator in the selected Environments to configure under Connections References.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220406.1

### Steps To Reproduce

1. Enter https://make.powerapps.com/environments/8d6e1110....163/connections
2. See all the connections the user has access
3. Open Accelerator, pick the Deployment Settings of the solution and enter the Connection References
4. See the same list for each type of connector that is seen in number 1)

### Anything else?

I have created a simple Canvas App and called the PowerApps Maker using this code:

ClearCollect(AllConnections,

AddColumns(
    PowerAppsforMakers.GetConnections(
    {
        '$filter': "environment eq '8d6e1110....163',
        'api-version': "2016-11-01",
        '$top': 300
    }).value,
        "DisplayName",
        properties.displayName,
        "ConnectionId",
        name,
        "ApiId",
        properties.apiId,
        "IconUrl",
        properties.iconUri,
        "Status",
        First(properties.statuses).status));

I was able to return all the connections the user has access to.

Looking at the Accelerator code there is a LookUpthat might be causing the issue:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/3724826/165915550-0e5ca38b-dd74-411c-9284-91c91b1ce5a2.png">

**Comment by rsantos00** [comment]
@mikefactorial After confirming with a client, I have verified the GetConnections actually returns more than 100 connections, would be possible to increase the limit in the Query? "$top: 100"

**Comment by rsantos00** [comment]
@mikefactorial I have confirmed the bug is in the top limit we are using, changing that limit to 1000 solved the problem, I will fix it in the code.

**Comment by rsantos00** [comment]
@mikefactorial:  Confirmed in the code and the '$top' has been removed

**Comment by rsch136** [comment]
Hi @rsantos00 ,
I've just upgraded to the june version and we still have the same issue:
![image](https://user-images.githubusercontent.com/44471683/173068758-4787c179-4a4b-4486-b389-8d946a60c55e.png)
![image](https://user-images.githubusercontent.com/44471683/173068772-ba35cea3-4bac-443b-83e1-b826ca358d7b.png)
As you can see, there are at least two groups connections in the environment but none show up. I've been using the same user for both the app and to look at the connections.

**Comment by rsantos00** [comment]
Hi @rsch136,
could you contact me by email for us to setup a call my email is Rui.Santos @ microsoft.com, thanks
