### ISSUE TITLE
[CoE Starter Kit - BUG] )365 Message Center  flow fails

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#2599]
### Describe the issue

Command Center M365 Message Center List serviceAnnouncements from Graph step fails 👎 

![image](https://user-images.githubusercontent.com/8484048/165922815-38790ba7-6019-4ac0-80b1-90a021015054.png)

### Expected Behavior

I expect this flow to work.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Command Center App > Get M365 Service Messages

### Steps To Reproduce

In the command center - click on 4th Icon down on the left hand navigation - 
See error message -
![image](https://user-images.githubusercontent.com/8484048/165924079-bed031ce-ea70-4320-a1ac-fb4155dce1bf.png)

check flow -
See error -
![image](https://user-images.githubusercontent.com/8484048/165924171-3ceb7843-7de8-4bae-8185-3e43118a78a9.png)

**Comment by Jenefer-Monroe** [comment]
Where did you store the secret for the flow? In Azure or just as a text string?

**Comment by NPrice99** [comment]
Its just a text string

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
