### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Sync Template v3 (PVA) - Get Bot Creator not found

### ISSUE THREAD

**Issue by rfolgadoal** [microsoft/coe-starter-kit#2603]
### What is your question?

CoE Power Automate Flow - Admin | Sync Template v3 (PVA)

In the container "Put Bots in CoE" and "For Each Bot" the action "Get Bot Creator" returns the message:
"error": {
    "message": " No Organization is matching the given dataset: XXXXX.crm4"
  }

![image](https://user-images.githubusercontent.com/93584307/165938757-8621044c-2e8a-4419-823b-4ed205505e6a.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

**Comment by Jenefer-Monroe** [comment]
Is the identity running this flow (and this action) a Power Platform Admin? And if so, is that role assigned dynamically via PIM?

**Comment by rfolgadoal** [comment]
Yes, the user is the System admin, and it's the flow owner and configured connection references.

**Comment by Jenefer-Monroe** [comment]
My question is not about the permissions on the envt but on the tenant. 

You can confirm that the user identity has the Power Platform Admin Role as shown here: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)

Note also that the role needs to be assigned permanently, not via [PIM](https://docs.microsoft.com/azure/active-directory/privileged-identity-management/pim-configure)

Please see our [pre-reqs](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites) for this and the other requirements needed to successfully run the starter kit.

**Comment by rfolgadoal** [comment]
The user has Power Platform Admin and Global Admin roles in the tenant.

**Comment by Jenefer-Monroe** [comment]
Please scroll up to the following call. What is returned in List Bots? 
Can you browse to the URL shown as that identity? 
![image](https://user-images.githubusercontent.com/89584709/166433166-ac85aa26-ddd3-4db8-a12f-bc43286b7f89.png)

**Comment by rfolgadoal** [comment]
We got this error in two cases and the List Bots action returns the id, but we can not browse to them: 
"Error message: Access is denied. An error occurred while accessing the resources required to serve this request."

**Comment by Jenefer-Monroe** [comment]
Can you please clarify:

1) Are you saying that List Bots returned two objects? 
1) And that you cannot access the @odata.id link for either? 
1) Are you trying to log in as the user identity running the flow?
1) Can you please try to browse (as your ppadmin identity) to the link up with everything starting with api removed?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
