### ISSUE TITLE
[ALM Accelerator - BUG]: Installation error in logs: A potentially dangerous Request.Path value was detected from the client

### ISSUE THREAD

**Issue by anstein-msft** [microsoft/coe-starter-kit#2610]
### Describe the issue

{"date":"Fri Apr 29 2022 10:39:46 GMT-0700 (Pacific Daylight Time)","error":{"statusCode":400},"exception":true,"level":"error","message":"uncaughtException: ﻿{\"$id\":\"1\",\"innerException\":null,\"message\":\"A potentially dangerous Request.Path value was detected from the client (:).\",\"typeName\":\"System.Web.HttpExceptio, System.Web\",\"typeKey\":\"HttpException\",\"errorCode\":0,\"eventId\":0}\nError: ﻿{\"$id\":\"1\",\"innerException\":null,\"message\":\"A potentially dangerous Request.Path value was detected from the client (:).\",\"typeName\":\"System.Web.HttpException, System.Web\",\"typeKey\":\"HttpException\",\"errorCode\":0,\"eventId\":0}\n    at RestClient.<anonymous> (C:\\Users\\xxxxxx\\Downloads\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\node_modules\\typed-rest-client\\RestClient.js:202:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\xxxxxx\\Downloads\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\node_modules\\typed-rest-client\\RestClient.js:6:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","os":{"loadavg":[0,0,0],"uptime":777056},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\xxxxxx\\AppData\\Roaming\\npm\\node_modules\\coe\\coe","alm","install","-f","install.json"],"cwd":"C:\\Users\\xxxxxx\\Downloads\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":75182,"external":1014833,"heapTotal":51040256,"heapUsed":49091264,"rss":79437824},"pid":10984,"uid":null,"version":"v16.13.1"},"stack":"Error: ﻿{\"$id\":\"1\",\"innerException\":null,\"message\":\"A potentially dangerous Request.Path value was detected from the client (:).\",\"typeName\":\"System.Web.HttpException, System.Web\",\"typeKey\":\"HttpException\",\"errorCode\":0,\"eventId\":0}\n    at RestClient.<anonymous> (C:\\Users\\xxxxxx\\Downloads\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\node_modules\\typed-rest-client\\RestClient.js:202:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\xxxxxx\\Downloads\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\node_modules\\typed-rest-client\\RestClient.js:6:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-04-29 10:39:46 AM -0700","trace":[{"column":31,"file":"C:\\Users\\xxxxxx\\Downloads\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\node_modules\\typed-rest-client\\RestClient.js","function":null,"line":202,"method":null,"native":false},{"column":null,"file":null,"function":"Generator.next","line":null,"method":"next","native":false},{"column":58,"file":"C:\\Users\\xxxxxx\\Downloads\\coe-starter-kit-main\\coe-starter-kit-main\\coe-cli\\node_modules\\typed-rest-client\\RestClient.js","function":"fulfilled","line":6,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}

### Expected Behavior

No errors in logs

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Latest

### Steps To Reproduce

1. Using this config JSON file 

{
  "log": [
    "info"
  ],
  "components": [
	"all"
  ],
  "aad": "ALMAcceleratorServicePrincipal",
  "group": "DPXEPPALMAccelerator",
  "devOpsOrganization": "https://xxxxxxxxx.visualstudio.com",
  "project": "DCX Custom Apps",
  "repository": "alm-sandbox",
  "pipelineRepository": "pipelines",
  "environments": "https://xxxxxxxxx.crm.dynamics.com",
  "settings": {
    "installEnvironments": [
      "validation",
      "test",
      "prod"
    ],
    "validation": "dev",
    "test": "staging",
    "prod": "prod",
    "createSecret": "true",
    "installSource": "coe",
    "region": [
      "NAM"
    ],
    "cloud": [
      "Public"
    ]
  },
  "importMethod": "api",
  "endpoint": "prod",
  "$schema": "./alm.schema.json"
}

2. Run this command:

coe alm install -f install.json

3. Find the error in the bug report, in combined.log

**Comment by anstein-msft** [comment]
I determined the issue is that I provided a URL like xxxxxxxxx..visualstudio.com for the Dev Ops URL. Environment.js script does not handle this case.

**Comment by mikefactorial** [comment]
@anstein-msft thanks for investigating this. Unfortunately, the ALM Accelerator doesn't support the legacy .visualstudio.com urls. You may need to update your devops environment to use the dev.azure.com domain.  By default legacy azure devops instances allowed for backward compatibility with the .visualstudio.com urls but the ALM Accelerator assumes the domain is dev.azure.com.
