### ISSUE TITLE
[ALM Accelerator - BUG]: Cannot able to delete Managed Solutions

### ISSUE THREAD

**Issue by NagulapallyLaxmanGoud** [microsoft/coe-starter-kit#2614]
### Describe the issue

When I am trying to delete the solution from AA4PP app, the pipeline is triggering "delete-unmanaged-ALMfinalsetup-and-components-from-environment".
The pipeline contains two jobs "exportAndDeleteUnmanaged" and "importAndDeleteManaged". These both are successfully ran.
But, only Unmanaged solution from my dev environment is deleting and Managed solution from validation, test and prod environments are not deleting. 

### Expected Behavior

When I delete the solution, the pipeline should trigger "delete-unmanaged-ALMfinalsetup-and-components-from-environment". Unmanaged solution from my dev environment and Managed solution from validation, test and prod environments should be deleted.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April 2022

### Steps To Reproduce

1. Click on Delete Solution from AA4PP app.
2. Enter the Solution Name, click on Delete Solution
3. Click on Processing icon in AA4pp app beside the delete Solution button.
4. Navigates to pipeline in Azure Devops.

**Comment by mikefactorial** [comment]
@NagulapallyLaxmanGoud the functionality for deleting a solution is intended to remove the unmanaged solution from your maker environment. Deleting the managed solutions in downstream environments isn't supported by this function. The managed solutions would need to be deleted manually in your downstream environment(s)
