### ISSUE TITLE
[CoE Starter Kit - BUG] Problems with setting up the Power BI Dashboard for CoE

### ISSUE THREAD

**Issue by smurph8875** [microsoft/coe-starter-kit#2617]
### Describe the issue

When importing the Template for Power BI for the CoE Starter Kit, we get an error that the Power BI App is not compatible with this tenancy:

invalid_resource: AADSTS500011: The resource principal named http://xxxxxxxxxx.crm4.dynamics.com was not found in the tenant named xxxxxxxxxxx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 53ac060c-e4b3-43dc-935c-f12f7ab68900
Correlation ID: 43a4e554-aeaa-4875-9c95-23452b4ab719
Timestamp: 2022-05-03 07:49:21Z.

### Expected Behavior

We would expect that the system would allow access when the URL is added to the Power BI Dashboard import

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Production_CoEDashboard_April2022

### Steps To Reproduce

1. Open Power BI Desktop App
2. Click File > Import
3. Select the Production_CoEDashboard_April2022.pbix file and click Open
4. Click Sign In
5. Select M365 Admin Account and click Sign In
6. Error Message is shown

**Comment by Jenefer-Monroe** [comment]
Hello this error message is occurring before anything about CoE work comes in to play, and so there isn't much we can do to help aside from point you to common issues others customers have faced trying to connect to Dataverse from PBI. Please see our [troubleshooting section](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#troubleshooting)

**Comment by smurph8875** [comment]
Thanks Jenefer - Found the problem is related to the address.  When using the recommended address (without http:// or https://) it tried to use the http:// link instead of https:// - having added the https:// at the front of the address seems to be working - however I now get webview v2 errors when trying to show the data, so going to try and build this on a dedicated server for Power BI Dashboard Design.

**Comment by Jenefer-Monroe** [comment]
I've not heard of people getting that error before. Please let us know what you discover

**Comment by Jenefer-Monroe** [comment]
I've not heard of people getting that error before. Please let us know what you discover

**Comment by Jenefer-Monroe** [comment]
I've not heard of people getting that error before. Please let us know what you discover

**Comment by smurph8875** [comment]
Hi Jenefer.

In the documentation is states to add the URL of the environment without http:// or https:// and the following / - however, this automatically tries to sign into the environment using http://[env_link].  By adding https:// at the beginning it forces it to use the Secure Link rather than insecure and works - still need to delete the following / or it still fails.

I had to build it from a server that we have setup for building Power BI Dashboards and it stopped the WebView v2 Error as I am guessing the default PowerBI Template is resource hungry for first setting up and now have this refreshing every day in the PBI Online Platform with zero errors.

Thank you for all your help in this.
