### ISSUE TITLE
[CoE Starter Kit - BUG] [CoE Starter Kit - BUG] Desktop flows inventory does not work: Http request failed as there is an error: 'Cannot write more bytes to the buffer than the configured maximum buffer size:

### ISSUE THREAD

**Issue by tsegato** [microsoft/coe-starter-kit#2618]
### Describe the issue

The issue is well described here:
https://github.com/microsoft/coe-starter-kit/issues/1464

But the issue has been closed. Can someone clarify what to do, or why this issue is closed?

When the "Admin | Sync Template v3 (Desktop flows)" flow is triggered to run when it gets to the step to read the workflows table form the dataverse environment it errors out with the following error:

Http request failed as there is an error: 'Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'.

There are only 141 records that would be returned, but it's somehow returning over 100MB of data, which is higher than the allowed limit. It looks like the bulk of data being returned is possibly in the clientdata field

If I connect directly to the dataverse database through SSMS and run the following query

select clientdata
FROM [dbo].[workflow]
where category=6 and uiflowtype != 101

It returns the following error

Msg 40000, Level 16, State 1, Line 105
Return records size cannot exceed 83886080. Make sure to filter result set to tailor it to your report.
RequestId: TDS;427c24e7-62be-46de-beb1-b1b348acc353;77
Time: 2021-11-10T19:56:41.8648075Z

Would seem like there's a lot of data stored in this field that may not even be needed by the flow that could be eliminated.

### Expected Behavior

Would expect the flow to run successfully and load the desktop flows information into the rpa_admin table in the COE environment's dataverse database

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

### Steps To Reproduce

 Make change to environment in question to trigger "Admin | Sync Template v3 (Desktop flows)" flow to run
2.) Review flow run and see that it errored out

**Comment by Jenefer-Monroe** [comment]
Hello, you are correct that is the problem. But unfortunately the legacy Dataverse connector does not allow us to select fields and the modern Dataverse connector cannot be used as it does not yet support cross environment capabiliities. 

Once the modern Dataverse connector supports x-environment capabilities, we will fix these flows to use it. Until then there is nothing we can do and this is just a hole in the kit. 

Please follow https://github.com/microsoft/coe-starter-kit/issues/2607 to track that work if you'd like to be aware of when it is ready.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team at this time.
