### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot extend starter kit

### ISSUE THREAD

**Issue by Jodarcy1** [microsoft/coe-starter-kit#2631]
### Describe the issue

Hello.  We installed COE in our development tenant and extended it by copying and customized some flows and apps.  We packaged the extended solution and tried to install into our production tenant but this failed on table and dependency errors. 

Using the instructions given (https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup#installing-upgrades) is not helping.  Can you provide additional guidance?  Thanks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2_9

### What app or flow are you having the issue with?

Customized apps/flows

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid we are at an impasse for extending the kit while we await a fix from the product team. Please see 
https://github.com/microsoft/coe-starter-kit/issues/2284

**Comment by Jodarcy1** [comment]
Hmm... apparently when we tried to export our solution from one tenant and import it into another it didn't bring over the tables.  This is a known issue?

**Comment by Jodarcy1** [comment]
Thanks, I updated my comment because it was just clarified to me that the team was importing from one environment to another which should work. We're creating some custom tables to see if the custom tables import versus the 'managed' tables.  We have our solution in a dev tenant and will import into the production tenant once we get this working.  Thanks.

**Comment by Jenefer-Monroe** [comment]
I'm afraid we dont repro this and have not seen tables not go across. Please let us know if you discover something interesting that would help us going forward.

**Comment by Jenefer-Monroe** [comment]
I'm afraid our team is not staffed to assist with work to extend the kit. Sorry that we cannot be of more assistance.
