### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by dylanwauters** [microsoft/coe-starter-kit#2633]
### What is your question?

The "May CoE Starter Kit May 2022" release doesn't contain the latest unmanaged solution of the toolkit under assets. I see that the .zip contains the CenterofExcellenceCoreComponentsTeams_3.3.zip instead of CenterofExcellenceCoreComponentsTeams_3_19.zip
![image](https://user-images.githubusercontent.com/8872571/166878125-6e5f17ad-4212-4308-9a8c-f70efb1c2728.png)
![image](https://user-images.githubusercontent.com/8872571/166878261-33696a35-e5bb-4e02-a693-f1887df8c147.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2022

**Comment by manuelap-msft** [comment]
Thanks for letting us know! I updated the release to remove the CenterofExcellenceCoreComponentsTeams solution from the unmanaged .zip file. ALM for Teams works slightly different than for production environments, so unfortunately today we are not able to make the unmanaged version of Teams available.
