### ISSUE TITLE
[CoE Starter Kit - QUESTION] Upgrade to CenterofExcellenceCoreComponents_3.38

### ISSUE THREAD

**Issue by massimilianomenci** [microsoft/coe-starter-kit#2634]
### What is your question?

I am going to upgrade COE to may 2022 version. but when I choose to upgrade the core component CenterofExcellenceCoreComponents_3.38_managed.zip the "upgrade" choice in advanced settings is not present, so I didn't proceed.
I found out that the name of the installed core solution is CenterofExcellenceCoreComponents_Upgrade (instead of CenterofExcellenceCoreComponents), maybe for an error in the previous update.
![image](https://user-images.githubusercontent.com/83634921/166882793-6197eef7-9b2a-4335-bc89-9e070d6b8a51.png)

is there a way to rename the current solution to CenterofExcellenceCoreComponent so the upgrade option will be available?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

**Comment by Jenefer-Monroe** [comment]
Renaming will not resolve this for you. You likely have two versions of Core in play right now. Can you please share a screenshot showing all the solutions in the environment so that we can better understand your state?

**Comment by massimilianomenci** [comment]
INTERNAL



Here it is

***@***.***

This is the history:
***@***.***

Maybe in the April upgrade something went wrong

thanks


Massimiliano Menci
Mobile   +39 328 682 3227

**Comment by Jenefer-Monroe** [comment]
Hello. Pictures do not come through unless you are logged in to GitHub at the time. Please log in to GitHub and share the image again.

**Comment by massimilianomenci** [comment]
I was answering by mail...
now I am writing in github, the pictures should be here

![image](https://user-images.githubusercontent.com/83634921/166939475-2821592d-371e-4c08-a1b6-1d68ebf4e665.png)

here is the history (the first line in error is because I tried to change the solution name into the package)
![image](https://user-images.githubusercontent.com/83634921/166939209-51e9eb24-7bab-4588-98c4-5bf137edaa74.png)

Maybe during the April upgrade something went wrong

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately you were upgrading from a very old version of Core and so we cannot really assist with upgrade at this point. There are too many changes and unknowns. 

If all you are using the kit for is inventory + audit logs, we tried to do a good write up for how to migrate that here https://github.com/microsoft/coe-starter-kit/issues/1507
If you are using us for more than that, then you woudl need to migrate additional data manually.

**Comment by massimilianomenci** [comment]
thanks a lot
why do you think the Core version is very old?
I am trying to migrate from 3.37 to 3.38, the previous installed version was 3.34, not so old.
3.34 installation worked fine
3.37 installation had some problems, but is working.

Afaiu if I renamed the solution removing the _upgrade suffix, I would be able to install the new Core version

**Comment by Jenefer-Monroe** [comment]
Then you also might try an overwrite upgrade in the classic UX:
 
Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)
 
Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)
 
Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png)
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by massimilianomenci** [comment]
the import procedure does not detect a previous version of the core solution, so the choice to override is not showed
![image](https://user-images.githubusercontent.com/83634921/167381907-3ded0b6d-9d45-4114-b803-a56055b7835c.png)
I did not proceed clicking the "Import" bottom, should I?

if solution rename is not an option, I am afraid I am stuck with the version 3.37
can I have 2 or more CoE instances running in different environments, in the same tenant?
If yes I could try to install the new one from scratch in a new enviroment and after evaluate is audit log migration is need or not

thanks

**Comment by Jenefer-Monroe** [comment]
yes I'm afraid you are in a strange state and so I cannot really offer advice on how to save the envt. Yes if you are just using us for inventory then I recommend starting with a new environment as described in https://github.com/microsoft/coe-starter-kit/issues/1507
