### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log upgrade from 2.6 to 2.7 fails

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2635]
### Describe the issue

CoE Update day today - in regards to the Audit Logs solution from 2.6 to 2.7 it fails with a message of this:

Solution "Center of Excellence - Audit Logs" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f691c36f6fa56d15c_374b1, Id: 52dc7c3e-c25d-4f62-ae20-b3fe839af383, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.7

### What app or flow are you having the issue with?

Upgrade

**Comment by Jenefer-Monroe** [comment]
Neither we, nor other customers are able to repro. So it appears something specific to your case. 

Please remove any unmanaged layers from the flows in the solution. It looks like you might have one on the Child flow which somehow captured this reference. Then try upgrade again.

**Comment by Jenefer-Monroe** [comment]
Spoke with the customer that hit this and they resolved the issue with the recommendation above.
