### ISSUE TITLE
[CoE Starter Kit - BUG] No Displaynames in Set Flow/App Permissions

### ISSUE THREAD

**Issue by Samuel-Dittmann** [microsoft/coe-starter-kit#2638]
### Describe the issue

In the two Set Permissions Apps, in the Table "Flow Permissions", the displaynames and pictures of the users are blank.

### Expected Behavior

The table should show the profile picture and the display name of the user

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.15

### What app or flow are you having the issue with?

Set App Permission and Set Flow Permission

### Steps To Reproduce

1. In the dedicated CoE environment
2. Launch one of the two apps
3. Select any random app or flow

### Anything else?

![image](https://user-images.githubusercontent.com/69673546/166901864-badcb6c5-ce41-4352-aa07-e7b27eb0b2ac.png)

**Comment by Jenefer-Monroe** [comment]
That means that the user has left the organization. This object, from the look of it here, is orphaned.

**Comment by Samuel-Dittmann** [comment]
> That means that the user has left the organization. This object, from the look of it here, is orphaned.

Right, though I dont even see myself in my apps or flows. There is really no user in any app or flow

**Comment by Jenefer-Monroe** [comment]
I do not repro this, and it appears that you are on a very old version of Core, (2.15) so it could be that its just an issue that's been resolved.
![image](https://user-images.githubusercontent.com/89584709/166969436-7775d2a7-9085-48c9-abcb-2dbd3867b79e.png)

**Comment by albertocaa1317** [comment]
Hi,
I have this case:

for example, this flow is orphaned but it's shared with more users that are in the organization. The information of these users is not showed in the Set Flows permissions.

Here you can see the owner orphaned and two more users without information:

![image](https://user-images.githubusercontent.com/57954993/167094117-458fcb14-a3d8-4d2d-abd3-a677380179c8.png)

Here you can see the two users with its information:
![image](https://user-images.githubusercontent.com/57954993/167094142-332677a2-7e70-4637-aac0-74600839e197.png)

**Comment by Jenefer-Monroe** [comment]
What type of user is that AdmAzACA? 
- is is type User? or service account or something like that? 
- is it from the same tenant as the app is hosted? (inditex)

**Comment by albertocaa1317** [comment]
Hi,
yes, it's the same flow and in the same environment. Sure.
Admazaca, is my admin user with Power platform admin role.
Initially I did not have permissions in the flow and that is why I have given them and I appear there

**Comment by Jenefer-Monroe** [comment]
I'm asking because it looks like its returning just the wrong information all together. So not something that results from our app manipulating the data. And I dont repro. If you call via the same action in Power Automate, does it return the correct information?

**Comment by albertocaa1317** [comment]
Sorry, How can I call this via Flow?

**Comment by Jenefer-Monroe** [comment]
Sorry the I meant for an app repro, there isnt an easy way for me to have you get these values for a flow in flow. 

I dont repro this and I have looked all over again today. 

Can you please load this app and see if it works. Its a simplified app that pretty much just does the call to the connector. See if it returns the correct users. 
[userlookup_20220511191339.zip](https://github.com/microsoft/coe-starter-kit/files/8672818/userlookup_20220511191339.zip)
 
![image](https://user-images.githubusercontent.com/89584709/167929702-da5d064f-2f08-4970-8b7d-538f47971064.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
