### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Maker Group owner must be identity running the flow or it cant add members

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [microsoft/coe-starter-kit#2639]
### Describe the issue

I recently installed CoE Core with an account that has only the Power Platform Administrator role.  After the initial data crawl, it seems to have only found a subset of data in my environment - about a fifth of the apps and flows that acutally exist.  I have a previously installed toolkit that was installed by an account with tenant admin, and that found all data.

### Expected Behavior

Core should find all apps and flows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Not sure which

### Steps To Reproduce

1. Installed new CoE tookit in different environment
2. Ran initial sync
3. Tool only found a small subset of apps flows etc

**Comment by DaveTheTeamsGuy** [comment]
This can possibly be closed.  I noticed the admin | sync template v3 flow had finished, but as I kept monitoring I noticed app and flow counts increasing, so it seems it's just taking a while due to some other flows still running.  I also found out the hard way that the account running the toolkit needs to be an owner of the configured Power Platform Maker Group or it can't add members.  It might be worth adding that to the prerequisite documentation.

**Comment by DaveTheTeamsGuy** [comment]
More - In speaking with a colleague, they were told (by Microsoft in a CoE workshop) that the Global Admin role is required on the account running the toolkit in order for everything to run correctly.  Is this true?

**Comment by Jenefer-Monroe** [comment]
Hello, thanks for posting. 

I did not know that about the Maker Group ownership so thank you for letting me know! We can use this bug to track updating the documentation for that. 

Global Admin Role is **not** needed to run the kit. But it is needed grant permissions in a few places
- grant access to PPAdmin role
- grant access to Audit Logs
- grant admin consent to the app registrations

Can you please let me know what CoE workshop and who said that? I can ensure the communication is a little more clear in the future.

**Comment by DaveTheTeamsGuy** [comment]
I didn't get that level of detail, however I can have my colleague let them know to review this bug report for clarification.
