### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE with Power Automate Management connector while login first time to Developer compliance App

### ISSUE THREAD

**Issue by sandeep-mamidala** [microsoft/coe-starter-kit#2641]
### Describe the issue

**Power Automate Management** consent not suppressing when the user logs in first time to developer compliance center app.
[](url)
Except Power Automate Management other connectors are getting sign-in automatically with the logged in user account. 

For Power Automate Management only user needs to sign-in and then select authentication Type to First-party is there a way to directly login instead of sign-in for **Power Automate Management** connector similar to other connectors

<img width="912" alt="PowerAutomateConsentIssue" src="https://user-images.githubusercontent.com/29742556/166923841-1a89582e-ff94-493e-80ff-1324e0077698.PNG">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.13

### What app or flow are you having the issue with?

Developer Compliance App

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid this is a question / issue for the product team and not for the toolkit. We do not do anything to change this behavior.

**Comment by manuelap-msft** [comment]
Hello,

all other connectors only support one way of establishing a connection, and can therefore be connected directly. For Power Automate, you can (for now) establish connections in multipe ways - first party and third party (deprecated) https://docs.microsoft.com/en-us/connectors/flowmanagement/#creating-a-connection

We can't control the connections dialogue here, it is surfaced by the product itself. Once the deprecated third-party connection is removed from the connector itself, this connector will also establish a connection automatically. Until then, this is outside of our control.

Manuela
