### ISSUE TITLE
[CoE Starter Kit - BUG] Re-publish App in Developer Compliance Center does not always publish

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#2644]
### Describe the issue

In the Developer Compliance Center, if the Re-publish button is clicked for an app, and that app does not have a new version that is not already published then the App Published date in the CoE becomes out of sync with the actual app published date.  

![image](https://user-images.githubusercontent.com/41050216/167007621-a2683b46-db45-4c71-bc08-da674444d5f5.png)

![image](https://user-images.githubusercontent.com/41050216/167007778-203cdbfe-15a3-450d-adbf-97fa31fc9763.png)

### Expected Behavior

The Developer Compliance Center should not allow for the App Published date saved in the CoE to be incorrect.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.16

### What app or flow are you having the issue with?

Developer Compliance Center

### Steps To Reproduce

I have an app which the Developer Compliance Center says needs publishing.   

1. Click the **Re-publish** button
![image](https://user-images.githubusercontent.com/41050216/167005806-3ab36b6d-4235-49b7-827b-7bbccf23c34f.png)

2. Click **Publish** on the pop up message (which is confusing by the way)
![image](https://user-images.githubusercontent.com/41050216/167006373-e55d68b1-4337-45a4-b1ba-fef1e711d7ca.png)

3. The App Published date on the Developer Compliance Center is now set to today's date
![image](https://user-images.githubusercontent.com/41050216/167005951-2e642771-8143-4b75-99bd-481156e3bd8f.png)

4. However, that app hasn't actually been re-published.  It will only re-publish if there is a new un-published (not Live) version in the version history.  Now the CoE data about publish date is incorrect.
![image](https://user-images.githubusercontent.com/41050216/167006181-1fb06cd7-56ac-4575-99cd-2a6908fdd491.png)

**Comment by Jenefer-Monroe** [comment]
In our testing, this call did a republish, but we might have missed this case. 
//republish the app
PowerAppsforAppMakers.PublishApp(vSelectedAppN.App);

Fix will likely be to just remove the functionality from the app. Will investigate

**Comment by HamishSheild** [comment]
Thanks @Jenefer-Monroe , what I have found is that function will publish the app if the app has been updated/save and the latest update is not the published version.  

Example

Won't publish
![image](https://user-images.githubusercontent.com/41050216/167044185-88f0a2f3-3ef1-45a5-aae8-bcc766225109.png)

Will publish
![image](https://user-images.githubusercontent.com/41050216/167044596-0ca21630-949b-4d28-93bf-0d248ffc4c74.png)

**Comment by manuelap-msft** [comment]
We're targeting January for a refresh of the Developer Compliance Center now. Added to January milestone.

**Comment by manuelap-msft** [comment]
Solving this by not enabling publish if the latest version is already live:

![Image](https://user-images.githubusercontent.com/55705669/211868078-2a9947b8-5d2d-4f97-ad63-e45a2f32a072.png)

Fixed for February.
