### ISSUE TITLE
[CoE Starter Kit - BUG] Flow HELPER - Get Groups not in solution after latest upgrade.

### ISSUE THREAD

**Issue by Arandon** [microsoft/coe-starter-kit#2646]
### Describe the issue

I've just upgraded core from February to the latest version.  Following the instructions I've checked the flows to make sure they are all turned on but am unable to find HELPER - Get Groups so can't turn it on.

![Missing Flow](https://user-images.githubusercontent.com/70806759/167096954-19dd55e8-e351-4bfa-bf7b-7aaaf6bc204c.jpg)

### Expected Behavior

HELPER - Get Groups to be available in the solution to turn on.

I don't believe it was there before so expect it's a new addition since February.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

HELPER - Get Groups

**Comment by Jenefer-Monroe** [comment]
Hello, the flow was not added intentionally and the documents were updated to remove it for May
![image](https://user-images.githubusercontent.com/89584709/167139425-0211a044-8c30-4a6f-b64e-81801b07be6d.png)

Thanks for following the steps so carefully.

**Comment by Arandon** [comment]
Great, thanks for the info Jenefer :)
