### ISSUE TITLE
[CoE Starter Kit - QUESTION] Developer Compliance Center - fix references to Archival

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2647]
### What is your question?

Hello,
what it means 'Admin has falgged for archiving'?
The app with this flag will be deleted by the flow?

Thanks 

### What solution are you experiencing the issue with?

Governance

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by Jenefer-Monroe** [comment]
This means that the object got tagged in the Arhcival Flows (now called [Innactivity notifications](https://docs.microsoft.com/power-platform/guidance/coe/setup-archive-components)

We can update this language now that we have shifted.

**Comment by Jenefer-Monroe** [comment]
Work is to :
1) Rename tooltip to "Admin has flagged as inactive"
2) On both Cloud flows and Canvas Apps
3) On click, brings you to details and it seems that the UX to respond has ended up kind of hidden
![image](https://user-images.githubusercontent.com/89584709/167141534-2cf8decc-334d-439f-aa98-1eac19fdf3b6.png)

**Comment by JackSocini** [comment]
How can an admin flag an app to archive?

Thanks

**Comment by Jenefer-Monroe** [comment]
That is one of the areas of functionality in the Governance solution. Please see [Innactivity notifications](https://docs.microsoft.com/power-platform/guidance/coe/setup-archive-components)

**Comment by JackSocini** [comment]
Is this process automatic?

**Comment by JackSocini** [comment]
Sorry but is not clear... I don't understand how it is possible that an app or flow get this allert.. I don't find a answer in the documentation..

**Comment by Jenefer-Monroe** [comment]
I will hide all these questions so its easier for the dev doing this fix to see their action items.

**Comment by JackSocini** [comment]
Which is the flow that flagged the app and flow with for archiving?

**Comment by JackSocini** [comment]
The flag 'Admin has falgged for archiving' appear on user application that haven't got any answer to archival flow?

Thanks

**Comment by manuelap-msft** [comment]
We will target January for the refreshed release of the Developer Compliance Center.
