### ISSUE TITLE
[ALM Accelerator - DOCS] App Registration Strategy Docs

### ISSUE THREAD

**Issue by rsantos00** [microsoft/coe-starter-kit#2649]
### What is your question?

Do we have any documentations around strategy on App registration in ALM. Should we have only one App registration for each DevOops project? Only one App registration for all projects?

Maybe a doc describing strategy would be useful. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

May release

**Comment by mikefactorial** [comment]
Short answer is we don't, but we need guidance in this area to describe the possible alternatives to the default setup for Azure AD Admins. This is also related to these issues #716 and #1086 which both discuss limitations in our prescribed Service Principal and Service Connection setup.

**Comment by mikefactorial** [comment]
We should address this as part of the July documentation or as a part of the updates to service connections we plan to make. Adding to July release for now.

**Comment by mikefactorial** [comment]
Moving to August release since will miss the July release
