### ISSUE TITLE
[CoE Starter Kit - BUG] (Blank) Values displaying in Power BI report

### ISSUE THREAD

**Issue by dragunwing** [microsoft/coe-starter-kit#2651]
### Describe the issue

Throughout my CoE Power BI report, I'm finding **(Blank)** as the value when it should be a zero.  This occurs on multiple pages of the report, i.e.:
- Overview - Power Apps
- Overview - Power Automate
- Environments
- and other pages

![coeError1](https://user-images.githubusercontent.com/11412139/167163198-41dd3981-44ef-4f28-b94c-5dad7e5bde54.png)
![coeError2](https://user-images.githubusercontent.com/11412139/167163221-07971b8d-32e2-4f49-90e5-4096ed24e039.png)
![coeError3](https://user-images.githubusercontent.com/11412139/167163233-3b5c6b8f-6d2c-40af-b7bd-f5a66585bd4f.png)
s

### Expected Behavior

Values that are zeros should display as zeros and not null **(Blank)** values.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Power BI report - unsure of which flow provides the necessary data

### Steps To Reproduce

This occurred in earlier Power BI reports (from previous versions of the CoE installations) and currently with the April update to Core Solution - 3.37.

**Comment by manuelap-msft** [comment]
Hello,

that's default behaviour of Power BI. 

You can change the visuals to apply formulas or conditional formatting to change (blank) to 0 (here's a thread on this https://community.powerbi.com/t5/Desktop/How-to-deal-with-a-quot-BLANK-quot-value-in-a-card-visualization/m-p/30457) which would have to be applied on each and every visual and number. We currently don't have funding or capacity to do this work, as we're a very small team and have to prioritize our efforts to more impactful scenarios.

Thanks for providing feedback,
Manuela
