### ISSUE TITLE
[ALM Accelerator - BUG]: CustomAzureDevOps Unable to make connection

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#2654]
### Describe the issue

Hi Mike we just upgraded to may release however we are seeing an issue with the cust connector when establishing a connection

![image](https://user-images.githubusercontent.com/12697408/167173157-c2711c97-5a2c-476a-9f31-6611b9963cc9.png)

however when calling it we can clearly see it gives a 200

![image](https://user-images.githubusercontent.com/12697408/167173247-9ac5fdc0-0999-4118-a39b-5b7d1414449d.png)

### Expected Behavior

Establish the connection

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

May Release

**Comment by gerald560** [comment]
re try a few times and it resolved

**Comment by mikefactorial** [comment]
Thanks for reporting and for the follow up. Did you update the security on the custom connector after the upgrade? Just wondering what the process was here in case someone else reports something similar.

**Comment by gerald560** [comment]
correct had to do it a few times ...updated secrets and client and ID and resource. We have been noticing weird behaviors within the envs seems like any time the wave releases are taking place we see things like ... app that don't require any premium connectors all of the sudden need a premium license... env variables not being populated ... flows randomly fail. So I'm gonna put this on wave releases lol :)
