### ISSUE TITLE
[ALM Accelerator - Feature]: Remove NPM deprecation warnings from COE CLI

### ISSUE THREAD

**Issue by Chris-WP** [microsoft/coe-starter-kit#2658]
### Is your feature request related to a problem? Please describe.

When building the COE CLI (using npm), 3 deprecation warnings are displayed:
```
npm WARN deprecated @types/open@6.2.1: This is a stub types definition. open provides its own type definitions, so you do not need this installed.
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

### Describe the solution you'd like

1. Remove the @types/open dependency from package.json
2. Remove the querystring dependency from package.json and use URLSearchParams

**Comment by mikefactorial** [comment]
Closing this out as we focus on investing in the Project Setup Wizard over further investments in the coe-cli
