### ISSUE TITLE
[CoE Starter Kit - Feature]: Use trigger conditions to control Sync Flows

### ISSUE THREAD

**Issue by xmihux** [microsoft/coe-starter-kit#2662]
### Is your feature request related to a problem? Please describe.

With the current setup of the Core solution, the inventory Sync flows start whenever a record in the Environment table is modified. And the Environment records are modified daily, based on a scheduled trigger. 

This becomes a problem whenever we want to extend the CoE with some more metadata about each Environment. Let's say we customize the Environment table with a few additional columns, specific to requirements of an organization. Whenever we want to update information in these columns, inventory Sync flows would trigger for that environment, which is unnecessary, because they run every day anyway.

### Describe the solution you'd like

It would be useful if the Sync flows that trigger when a record in Environment table is modified, used trigger conditions. 
For instance, the main "Admin | Sync Template v3" flow could set a RunSyncFlows flag to true. The Sync flows would then trigger and change the flag back to false (or maybe even the main flow could change it back to false straight after setting to true).

**Comment by manuelap-msft** [comment]
The flows that are triggered by the main Admin Sync flow only run if items are modified, so whilst the Admin | Sync Template v3 (Apps) triggers when an environment is modified, if no apps are new or changed in the environment it will not do anything. 

The sync flow logic is highly complex so we are not able to consider this enhancement.
