### ISSUE TITLE
[CoE Starter Kit - BUG] Active Audit Logs - NoUPN for User UPN

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#2665]
### Describe the issue

Hello,

For a couple of days the User UPN has not been added anymore in the Audit Logs (nothing was changed from our side).

Could you please assist us with this issue?

![image](https://user-images.githubusercontent.com/7468628/167415137-36ceeb14-31ac-442b-a524-e41be3ca324a.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Active Audit Logs

### Steps To Reproduce

Go to POWER ADMIN VIEW and check the AUDIT LOGS

**Comment by Jenefer-Monroe** [comment]
Issue resolved with the following Audit Log solution. It is now part of the May download
https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-May2022/CenterofExcellenceAuditLogs_2.9_managed.zip

**Comment by DaveTheTeamsGuy** [comment]
Hah just installed the new version May 5 and caught this bug.  I updated to 2.9, re-ran the audit log flows and can confirm that UPNs are now showing again, however hundreds of previous records that had NoUPN are still there.  Any way to fix those, or should they just be deleted?

**Comment by ValentinMaz** [comment]
> Issue resolved with the following Audit Log solution. It is now part of the May download https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-May2022/CenterofExcellenceAuditLogs_2.9_managed.zip

Thanks for quick action! We just spotted this issue on our side, the issue started on May 2nd for us. Could you please confirm that the only change you made was to change the "UserKey" field by the "UserId" field in the "Insert Audit Log record (Current_Environment)" action? Do we know that this will not be reverted back in the future?

We are this issue now and will plan a proper update from the latest CoE Kit version in the future

**Comment by ValentinMaz** [comment]
> Hah just installed the new version May 5 and caught this bug. I updated to 2.9, re-ran the audit log flows and can confirm that UPNs are now showing again, however I have about 5k records since I upgraded on 5/5 where the UPN is still listed as NoUPN. Any way to fix those, or should they just be deleted?

Same here, although we have 76K of them :)
You can do an [Audit log search](https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps) to retrieve the Logs that have not been captured properly by filtering on the operation "LaunchPowerApp" and the appropriate period. Once you have the extract you can update each item from the Audit Logs Dataverse table to update the users UPN - this is what we are doing on our side, but there might be a better way?

**Comment by DaveTheTeamsGuy** [comment]
Thanks for the response.  I am hoping for a better way before going that route.

**Comment by Jenefer-Monroe** [comment]
@ValentinMaz Correct that is the only change made. 
@DaveTheTeamsGuy I'm afraid we dont have a better way to fix this up other than that suggested by VanetinMaz. A script to update the values.

**Comment by DaveTheTeamsGuy** [comment]
Accepting any and all suggestions on how to do that - Not really a dev or coder here.

**Comment by DaveTheTeamsGuy** [comment]
If I just delete the rows that contain NoUPN, will that have any adverse affect on anything else?

**Comment by Jenefer-Monroe** [comment]
That is not a bad approach. 
You can download from the office audit logs into Excel. Delete these, and import new records into Dataverse using the dataverse import feature
![image](https://user-images.githubusercontent.com/89584709/167934370-70472d25-d67e-427e-9052-40521b27187f.png)

**Comment by DaveTheTeamsGuy** [comment]
Since it was only a few days worth of data, I think I'll take the delete route.  Can I get confirmation that removing those logs won't break anything else?  Guessing not, but just want to be sure.  Thanks again.

**Comment by Jenefer-Monroe** [comment]
It will just show as less launches in the PBI. So you should be good.

**Comment by DaveTheTeamsGuy** [comment]
That did the trick, thanks for the input!

**Comment by Jenefer-Monroe** [comment]
wonderful. I'll close this out now that its fixed up.

**Comment by ClaudiuVio** [comment]
Hello again,

I have installed the May release and still no UPN

![image](https://user-images.githubusercontent.com/7468628/168087862-a88707c7-8b5a-4309-aa14-a3b107ba9264.png)

![image](https://user-images.githubusercontent.com/7468628/168088121-0ebdfe92-c0dc-4585-91f6-6c04cd5dd509.png)

What I should check?
