### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by talljanding** [microsoft/coe-starter-kit#2671]
### Describe the issue

I'm in the process of trying to setup the CoE kit and have been following documentation to the letter as best as I can tell. I grabbed a fresh download last week from https://aka.ms/CoEStarterKitDownload. When setting up the Power BI template I use the following URL:
https://orgXXXXXXXc.crm9.dynamics.com/

But this is what I get when it tries to load:
OrgUrl
Loading blocked by failures with other queries.
Environment
The key didn't match any rows in the table.
App
The key didn't match any rows in the table.
Flow
The key didn't match any rows in the table.
Maker
The key didn't match any rows in the table.
Connector
The key didn't match any rows in the table.
App Connection Reference
The key didn't match any rows in the table.
Flow Connection Reference
The key didn't match any rows in the table.
Audit Log
The key didn't match any rows in the table.
Flow Action Details
The key didn't match any rows in the table.
NonProdWords
Loading blocked by failures with other queries.
Virtual Agent
The key didn't match any rows in the table.
Virtual Agent Component
The key didn't match any rows in the table.
Virtual Agent Flows
The key didn't match any rows in the table.
RPA
The key didn't match any rows in the table.
RPA Sessions
The key didn't match any rows in the table.
Power Platform User
The key didn't match any rows in the table.
Portals
The key didn't match any rows in the table.
Environment Capacity
The key didn't match any rows in the table.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38 is the core version

### What app or flow are you having the issue with?

Setting up the Power BI template

**Comment by Jenefer-Monroe** [comment]
Can you please ensure you are on the latest version of Power BI and try again? 
https://aka.ms/pbiSingleInstaller

**Comment by talljanding** [comment]
I have verified that I am on the current version of Power BI (2.104.941.0 64-bit, released last month).

**Comment by talljanding** [comment]
As it turns out, in my newness to Power Platform, I hadn't changed the environment my service account set the CoE kit up in away from the Default environment. So, once I actually setup the CoE kit in the production environment that I made for it, I was able to connect the Power BI dashboard to it without issue.

**Comment by Jenefer-Monroe** [comment]
thank you for letting us know the outcome! Glad you got unblocked. And welcome to the platform! :)
