### ISSUE TITLE
[ALM Accelerator - Feature]: Additional Environment Information

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#2673]
### Is your feature request related to a problem? Please describe.

I have 3 developer environments, where I can't change the environment name (and don't ask how I got these environment, I don't know). So its hard to find the right environment for me.

Please add additional information to the environment dropdown:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/15800069/167562788-621f2a27-c7f9-4c39-a142-f07e315db78e.png">

I would prefer to see also:
* Environment Type
* Environment ID

### Additional Environment Information:
* icon / color can help to identify Dataverse or Dataverse for Teams environments
* additional type information (Developer, Sandbox, Production, Trail, ...)
* Tooltips can provide the environment id
* Environment Location (europe, north america, ...)

Well this is in VS-Code a little bit easier:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/15800069/167563425-784d4199-fcfe-42fe-9a7d-a633972199e6.png">

### Describe alternatives you've considered

Select the environment and identify the solutions insight to find the right environment

### Additional context?

AA4PP - May release - Canvas App

**Comment by mikefactorial** [comment]
Thanks for the feedback @megel. Will look into what additional information we get back from the PowerApps connector to add more context to the environment picker.
