### ISSUE TITLE
[CoE Starter Kit - QUESTION] Not showing all Apps/Flows

### ISSUE THREAD

**Issue by cr0max** [microsoft/coe-starter-kit#2674]
### What is your question?

We installed CoE v3.34 in March and upgraded to v3.38 last week. But we have been struggling to get a full inventory of our Apps and Flows, since the start. Trying to find out the reason for this difference between the CoE inventory and PPAC Tenant Level Analytics. I have been reading up on the tickets other people have been posting and checking the limitations of CoE, thinking that I might find a solution to at least close the gap between the inventories, butt unfortunatley with no luck. 

So we have a large tenant, with almost 600 environments. 
CoE shows us 3239 Model/Canvas Apps and TLA gives us 5242 Apps (Sharepoint apps not included here).
Also CoE shows us 11033 Cloud Flows, where TLA gives us 12317 Cloud FLows, not quite the big difference as on the app side.

So we are missing about 2000 Apps and almost 1300 Flows.

We have been running full inventory since last week.
All environments are collected by CoE.
The account running the flows has the Power Platform Admin role peranently assigned.
The account has the Power Automate per user and Power Apps per user license permanently assigned.

The odd thing is when I am matching the result of CoE and TLA per environment, there are differences in apps/flows per environment, that I can't understand why.

Also, its really hard to check on all CoE inventory flows as there are so many (I assume that there is one flow running per environment).

Could there be a throttling issue that we are facing?

So any help/guidance would be much appreciated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2022 v3.38

**Comment by Jenefer-Monroe** [comment]
You would know if you were being throttled, the flows wont complete. Are you seeing that? I would expect that doing full inventory runs for a week on a tenant that size. That would explain oddities in your inventory. 

Here is our documentation on the expected differences
[Inventory and telemetry differences between PowerShell, Power Platform Admin Center, and CoE Starter Kit](https://docs.microsoft.com/power-platform/guidance/coe/limitations#inventory-and-telemetry-differences-between-powershell-power-platform-admin-center-and-coe-starter-kit)
Since we are only able to assist here in GitHub, in order to help what we would need is for you to find specific examples where they are different. Then we can explore their properties to see if we can find a pattern.

**Comment by cr0max** [comment]
I have compiled a quick report with the differences, so I know what to look for. A few environments actually show the correct numbers but since not even the CoE env gives me a full inventory, there must be some issues here. Here is an example of the differences, the environments match on the list below and you can see the differences in apps and flows from TLA and CoE.
![image](https://user-images.githubusercontent.com/97740538/167603567-36f80a0b-4937-4b57-882b-2be50beddcfb.png)

Command Center is not the best for us, as the PVA bug i still present and floods the Command Center. I can find some failures for Flows and Apps flows, but only for specific environments. Our differences are bigger than that, taking the expected differences for CoE in consideration.
![image](https://user-images.githubusercontent.com/97740538/167604797-1452f400-c839-4370-a64a-d949c23f87d8.png)

We upgraded on the May 6th and The Admin | Sync Template v3 is still running on the latest two runs, but the previous did finish.
![image](https://user-images.githubusercontent.com/97740538/167605190-0df5cb65-edf0-4278-abca-02584ec886b1.png)
How long can these flows run?

So it's kinda inconsistent and I do not really know what actions to take, to fix it.

**Comment by cr0max** [comment]
Any suggestions for the Admin | Sync Template v3? 
![image](https://user-images.githubusercontent.com/97740538/167792137-d12e69be-d05d-411b-baeb-f056d13b0cfc.png)

**Comment by Jenefer-Monroe** [comment]
You are probably being throttled. 
You should turn off this flow, and cancel these runs.
Then also turn off and cancel the other sync flow runs in progress (ex Admin | Compliance Details Request eMail (Apps)) as their current run is not going to resolve for you. 

Once all the flows are turned off and their run api's draining off, you should turn off the full inventory env variable. And given your tenant size, you shoudl also change the delayinventory env variable. 

So set these env varables: 
| Name           | Description                                                                                                                                                                                                                                | Default | You set value to: |
|----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|-------------------|
| FullInventory  | Determines whether you want to update only objects that have changed, or all objects. Switching to Yes will cause the flows to inventory every single app, flow, and bot in the tenant every day, and isn't recommended for large tenants. | No      | No                |
| DelayInventory | If Yes, runs a delay step to assist with the Dataverse load balancing. Only set this to No for debugging.                                                                                                                                  | Yes     | No                |



Here is how to [update environment variables](https://docs.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables)

**Comment by Jenefer-Monroe** [comment]
If you continue to have problems with the flows never finishing after that, you may need to use some additional licensing tricks to get the needed API calls
- [pay as you go](https://docs.microsoft.com/power-platform/admin/pay-as-you-go-overview)
- [per flow licensing](https://docs.microsoft.com/power-platform/admin/power-automate-licensing/types)

Or to explore another option for collecting inventory: https://docs.microsoft.com/power-platform/admin/self-service-analytics

**Comment by cr0max** [comment]
So I have turned off all inventory flows and will wait for a 24 hours for the drain.
Below flow seems to be especially problematic, it would probably fail anyway:
![image](https://user-images.githubusercontent.com/97740538/167940140-6b83d837-5dab-4a48-af08-f78d54d3d6eb.png)

I also checked the FullInventory variable again and it is set to Yes in Command Center, but the env variable in the default solution is empty. Is this a bug, as it seems not to be set to Yes in the solution (the flows have been reset)?

![image](https://user-images.githubusercontent.com/97740538/167940380-47b7576c-055c-4614-8351-89d8940b0749.png)

![image](https://user-images.githubusercontent.com/97740538/167940408-97e50bca-7b16-42bb-9cca-b6ac07444ce9.png)

Same goes for the Delay Inventory, so it looks like the Command Center app is not able to set the variables.
Anyway, I dit set both values to No in the solution, as recommended above.


Regarding the licensing and throttling, I do have some questions that you might or might not be able to answer.
- The throttling counts per flow right? Not per licensed account? As there are so many flows run with this account. However the picture below states per license.
- Per flow licensing is not a cheap option. The license is assigned per environment, how do you determine which flow gets the license? This would require several per flow licenses as we have multiple flows that are beeing throttled?
- How can a pay as you go subscription be an alternativ, if the request limit per 24 hours only is 6000?
![image](https://user-images.githubusercontent.com/97740538/167944199-4f6c7bff-294c-49b0-b8cd-c8b3d43a5b9a.png)

**Comment by cr0max** [comment]
Just to add to this, we are definatley beeing throttled.
As we have a Power Apps per user license and a Power Automate per user license we get 40k+40k requests per day, for ALL flows on this account (I think that they are combined https://docs.microsoft.com/en-us/power-platform/admin/power-automate-licensing/types#what-happens-to-my-power-platform-requests-if-i-have-multiple-plans).
Also it is a transition period now, så all limits are currently raised.

Just some facts on threr of our inventory flows:
-	Admin | Sync Template v3 (Apps) –                      
![image](https://user-images.githubusercontent.com/97740538/168598401-8d3fd171-e43b-4d67-8089-69063f4bc3f6.png)

-	Admin | Sync Template v3 (Flows) –      
![image](https://user-images.githubusercontent.com/97740538/168598513-14559066-5f9c-43e8-b5d5-91b198fcad8c.png)

-	Admin | Sync Template v3 (Flow Action Details) –  
![image](https://user-images.githubusercontent.com/97740538/168598608-d9ff8f73-ad53-4007-b9f1-24b4470386c3.png)

The last flow is a really heavy one and this might end up to be an expensive solution to implement fully. With the per flow licenses and also a pay-as-you-go subscription that costs 0,00004$ per day for every additional requests over your license limit.
                     
The response we got from MS support was to rebuild our CoE flows for better optimization....

**Comment by Jenefer-Monroe** [comment]
Regarding the env variables first. 
Current values are weird. They are for an envt not a solution, and they wont show up in the individual solutions, only in Default. We tried to obfuscate this confusion away from you by putting it in the Command Center. My recommendation is to do the editing in the Command Center. So "delete" to get rid of the Yes for full inventory for example.

**Comment by Jenefer-Monroe** [comment]
Can you share the support ticket # with us as well? We can help support here a little bit.

**Comment by cr0max** [comment]
I activated all the inventory flows last friday, but before that changed the value of CLEANUP - Admin | Sync Template v3 (Check Deleted) to no, as default is yes.

![image](https://user-images.githubusercontent.com/97740538/168771036-50b3c020-86ab-416e-91b0-f7fc2a382acf.png)

Now I can see that CoE has marked about 300 apps as deleted, some are incorrect and are still active in PP...
However as the default was yes, could this have caused CoE to delete apps from CoE database somehow, during throttling or connector failing or other implications?

Out of curriosity, if a full inventory is run again, will any deleted apps in CoE reappear? 

There are so many questions, errors and problems with our CoE in our tenant, that I can't manage it all...

**Comment by Jenefer-Monroe** [comment]
Yes your inventory appears to be quite a mess. Have you considered reaching out to a partner to assist? There are many pre and post sales offerings through Microsoft which will help to pay for such assistance.

**Comment by cr0max** [comment]
Here is an update.
I can confirm your actionplan and it was done in the order as suggested:

- all flows got turned off - **yes, done last week**
- this let all the api calls drain off - **seems ok, waited more then 24 hours**
- now all the flow runs are complete and settled - **yes, cancelled all last week**
- you have turned FullInventory and DelayInventory env vars to No - **yes, done last week**

- Child flows - **they are on and have run**
- Setup flows - **they are on and have run**
- Cleanup flows - **they are on and have run** - 
Admin | Sync Template v3 (Check Deleted) flow failed, but there was no error in the flow. It just skipped the last step. So it looks fine.
![image](https://user-images.githubusercontent.com/97740538/169481015-1a587899-2cf5-4fb6-be9b-c3bfd0cf0e85.png)

CLEANUP HELPER - Check Deleted (XXX) flows - are on but have not run. Is this because the flows will not run when Env variable "Also Delete from CoE" is set to "No"?

- The rest of the inventory flows are on as well, as I started the above process Thursday last week.

All flows are completing now (so we are not throttled anymore)
Here are som inventory flow updates:
Admin | Sync Template v3 - No errors and all completed!

Admin | Sync Template v3 (Apps) - Only 1 legacy environment error
![image](https://user-images.githubusercontent.com/97740538/169482169-e0eff246-febc-4e50-9fd7-74a4b9975612.png)

Admin | Sync Template v3 (Flows) - No errors and all completed!

Admin | Sync Template v3 (Flow Action Details) - Some errors
![image](https://user-images.githubusercontent.com/97740538/169482513-2d369d13-0c69-4922-aa03-e699eabf3c26.png)

Admin | Sync Template v3 (Model Driven Apps) - A few env not found error (5 in total)
![image](https://user-images.githubusercontent.com/97740538/169483102-eef3c5c8-c295-4aad-b933-45ff9b040cd9.png)

Admin | Sync Template v3 (PVA) error "Action 'GetBotID' failed" on multiple environments. Same bug that was addressed in May version?
![image](https://user-images.githubusercontent.com/97740538/169483568-4055986b-815a-4362-9221-620c842587e1.png)

Right now it looks decent, no major failures, except the PVA flows.
Though still missing some inventory, but I dare not to turn on the FullInventory. 
Is there a way to turn the FullInv on per flow (lets say, only Admin | Sync Template v3 (Apps)) and let it complete? So we minimize the risk of getting throttled?

**Comment by Jenefer-Monroe** [comment]
"Also Delete from CoE" does not impact if the flows will run
- When set to No, we will identify objects as deleted in the tenant but just mark them as such (ex appdeleted field) in inventory
- When set to Yes, we delete objects from inventory when they are identified as deleted in the tenant.

**Comment by Jenefer-Monroe** [comment]
Please post individual bugs for the issues above. The PVA one is fixed in May, you may have unmanaged layers preventing you from seeing the fix, see [installing upgrades](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

**Comment by Jenefer-Monroe** [comment]
Glad we got the throttling resolved. Closing out as this first issue seems resolved and you will need to post individually new issues.
