### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Jespermollervestergaard** [microsoft/coe-starter-kit#2675]
### Describe the issue

I´ve installed Center of Excellence on a customers tenant. Everything seems to be up and running, but I´m unable to view data regarding model driven app, that are not part of the CoE environment or default environment.

When using the Coe Admin dashboard, there are no information on unique users, sessions and so on. Only the default environment are showing numbers. 

When looking at the data in Power Platform Users table, there are only users, who also figures in the Power Platform Maker table.

When i access the same information through Power platform analytics, there are no data visible.

![All env](https://user-images.githubusercontent.com/105284002/167614275-a58ed47a-5f45-41a8-9c85-d67f4ba7f093.png)
![Production env](https://user-images.githubusercontent.com/105284002/167614279-212b5e67-596c-47c4-8d27-f63cddc86f1f.png)
![Default env](https://user-images.githubusercontent.com/105284002/167614290-d83e94ed-bb49-44e0-8bea-6dc86a00f3ee.png)

### Expected Behavior

I was expecting to view telemetri data on all of our environments. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin - sync template v3

### Steps To Reproduce

1. Access power BI CoE Dashboard and look at information on all other environments than Default.

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid I'm having trouble following your concern here. 

It sounds like you are saying that the inventory didn't pick up apps outside of the Default envt. Can you confirm, did the identity used to set up and run the inventory sync flow have the PPAdmin Role permanently assigned? 
Please see this section of our documentation for more information about the requirements for the identity used to setup and run the sync flows.  [What identity should I install the CoE Starter Kit with?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by Jespermollervestergaard** [comment]
Hi Jenefer

Fair enough, it's not very well explained either, I'm sorry :)

My challenge is that I can see all apps and flows, across all our environments, but telemetry data is only visible from the Default environment and the Center of excellence environment.

This also means that there are no users in the Power platform users table, with the exception of users who are also makers.

It is, for me to see, the same data that I can access in the Power platform admin center, under Analytics - Power Apps and here there is also no data, with the exception of the two aforementioned environments.
Data for Cloud Flows exist in both Analytics and the Center of Excelence.

This suggests that it is the delivery of data to Analytics that is causing trouble.

I hope it makes sense? :)

I´ve created a new user for setting up CoE, and permanently assigned the PPAdmin role, and several others :)

**Comment by Jenefer-Monroe** [comment]
What do you mean by telemetry? App launches? That does not filter based on envt so likely you are just not getting all of the data. Can you confirm
- what version of the audit logs solution do you have? 
- are the flows in that solution turned on and running? 
- Is the env variable for **_Admin eMail_** a value to which you have access? 
- Are there mails coming to that alias indicating that you have not receieved all the audit log?

**Comment by Jespermollervestergaard** [comment]
I think we need to focus on the missing data in Power Platform admin center. It´s the same data that are missing in Center of Excellence.

But to answer your questions:

what version of the audit logs solution do you have? _We are running version 2.6_
are the flows in that solution turned on and running? _Yes all relevant flows are running, with no errors._ 
Is the env variable for Admin eMail a value to which you have access? _Yes, and emails are coming through._  
Are there mails coming to that alias indicating that you have not receieved all the audit log? _Yes i receive emails, and they indicate that I need to edit the intervals._

**Comment by Jenefer-Monroe** [comment]
You need to edit the intervals then in order to see all the launches. 

Please see step 11 of the [audit log setup - setup the flow](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow)
![image](https://user-images.githubusercontent.com/89584709/168612576-53c52b08-f236-4aeb-8b1f-8facc33aa799.png)

**Comment by Jespermollervestergaard** [comment]
Hello again :)

Should not the Power Platform Users table contain all active users in the tenant, regardless of whether the Audit Flow is running or not?

I obviously need the audit flow to run, regardless.

**Comment by Jenefer-Monroe** [comment]
Yes this is filled by these flows. Please make sure they are turned on, running, and passing:
CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
CLEANUP HELPER - Power Apps User Shared With

**Comment by Jespermollervestergaard** [comment]
Ahh ok, I did not know. .
But yes, they are on, running and successful.

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont understand your current state. I believe your concern is that you are not seeign all your telemetry data. That will be resolved by fixing up the parameters as described above. 
I hope that helps!

**Comment by Jespermollervestergaard** [comment]
Hi Jenefer

All relevant flows are running and the are successful.

I dont get why app information from apps in our production environments aren't coming through. 

Please have a look at these screen shots.


![image](https://user-images.githubusercontent.com/105284002/169483335-bb35890d-a031-40fa-8134-acf41a71d65f.png)
![image](https://user-images.githubusercontent.com/105284002/169483389-ddd468b9-751d-4791-9d77-88ce4e26bb33.png)
![image](https://user-images.githubusercontent.com/105284002/169483421-cfc6ada6-f694-4f31-a77c-7cd487eb5eb8.png)
![image](https://user-images.githubusercontent.com/105284002/169483461-64b29d0e-c5c8-424c-9b94-f86573ebefb8.png)
![image](https://user-images.githubusercontent.com/105284002/169484730-7d42405a-b0ab-4203-ae51-8439b7303f99.png)
![image](https://user-images.githubusercontent.com/105284002/169484775-0914baa3-7a2a-4007-8646-6aa96b0db9f8.png)

**Comment by Jenefer-Monroe** [comment]
Likely that is the issue described above

`Yes i receive emails, and they indicate that I need to edit the intervals.`

Please change the intervals as described above until you no longer receive these.

**Comment by Jespermollervestergaard** [comment]
Hi again

I changed the intervals a week ago and I no longer receive emails regarding the size or intervals.

**Comment by Jenefer-Monroe** [comment]
Wonderful. Then you should receive all your app launches going forward.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Jespermollervestergaard** [comment]
Hi again

I dont get why are closing the ticket. Nothing has been solved. I stil don´t se any data regarding usage and or users in relation to the model driven apps in our environments.
