### ISSUE TITLE
[ALM Accelerator - BUG]: Activate Flows for Connection References Not using Order By

### ISSUE THREAD

**Issue by kallisto08** [microsoft/coe-starter-kit#2677]
### Describe the issue

When running a deploy to Validate, Test or Production environments the Step "Activate Flows for Connection References" fails with "Child workflows need to be published at least once before they can be included in a published par    
ent workflow." 

This error is caused when you have multiple dependant workflows in the solutions and they need to be activated in a specific order. 
Although we selected the Order and it is added to the pipeline variables this step does not seem to respect the order.

### Expected Behavior

If we order number on the work flow is added in the order that they need to be activated it is expected that they are activated in that order. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

May 2022

### Steps To Reproduce

Create a solution with dependant child work flows 
Number them in the order they need to be activated
Check in solution to DevOps using the ALM app
Carry out a Pull request into V-Next (which will trigger a Validation build & deploy)
Pipeline will fail at Step "Activate Flows for Connection References"

### Anything else?

Work around to current issue is to set activate to false in pipelines and manually activate once pipeline is completed.

**Comment by mikefactorial** [comment]
@kallisto08 thanks for reporting this. We have another issue in our backlog to address this in the June release. Will close this as a duplicate for now, but feel free to reply to https://github.com/microsoft/coe-starter-kit/issues/2449 with any additional details.
