### ISSUE TITLE
[ALM Accelerator - BUG]: Sharepoint Column 'title'

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#2679]
### Describe the issue

During our deployment to validation, we kept seeing the following error
![image](https://user-images.githubusercontent.com/12697408/167695165-5d42ed40-cadb-41a9-aa49-89ce02070775.png)

Looking a little deeper my eyes caught this 

"the API operation 'PatchItem'   
  is missing required property 'item/Title'.'."}}". => Flow client error returned with status code "BadRequest""

We went into the solution and anywhere where we had a SharePoint update we added the title field even though its not required!!! 

![image](https://user-images.githubusercontent.com/12697408/167695687-4a1aeadc-855f-4aab-9b39-d2d10c92376d.png)

This ultimately solved the issue (workaround)

### Expected Behavior

Turn the flow on without having to add the title field for sharepoint

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

May

**Comment by mikefactorial** [comment]
@gerald560 nice catch. Let me see if I can track down the owner of this and see if it's a known issue or something that needs to be fixed in the platform. We could potentially add something to the accelerator to work around this in the short term but would likely be a hack

**Comment by mikefactorial** [comment]
@gerald560 could you open a ticket with MS Support for this? That would help us get more eyes on the issue and escalate it appropriately to the correct team.

**Comment by gerald560** [comment]
Support request ID
2205160040006159
Issue title
Flow - Platform error

**Comment by mikefactorial** [comment]
Thanks @gerald560 will forward this internally to see who we can have look into it.

**Comment by mikefactorial** [comment]
@gerald560 did you ever get a resolution for this issue haven't gotten a response internally on this but I'll continue trying to escalate if it's still an issue

**Comment by gerald560** [comment]
@mikefactorial unfortunately no

**Comment by mikefactorial** [comment]
@gerald560 unfortunately we've not been able to make any progress on this internally. I'm going to close out this issue as there's no more work to be done by our team
