### ISSUE TITLE
[CoE Starter Kit - QUESTION] What permissions are needed for one to use the "Admin - Access this App" control in Power BI Report?

### ISSUE THREAD

**Issue by dragunwing** [microsoft/coe-starter-kit#2680]
### What is your question?

What permissions are needed for one to use the "Admin - Access this App" or the "Admin - Access this Flow" control in the Power BI Report?  We are wanting to grant certain persons the ability to reassign owners for PowerApps and share flows with new persons (especially orphaned flows).  What rights do they require to be able to make these updates with the 2 embedded controls in the Power BI report?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin - Access this App

**Comment by manuelap-msft** [comment]
Power Platform Admin role is required to update ownership of apps and share flows. So additional to sharing the app with them, they would need those permissions.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
