### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#2682]
### Access Rights at Production Environment

Nice to meet you. Let me ask you about the permission configuration of the production environment where you want to import the CoE Starter Kit.

Regarding the environment for importing the CoE starter kit, when importing to the production environment, there was a description in the public information that "Do not configure restrictions by security group".
"https://docs.microsoft.com/ja-jp/power-platform/guidance/coe/setup#create-your-environment"

We recognize that this is due to constraints on approval actions. (If a user who does not have access to the environment is assigned to the approver, the Dataverse security role will not be granted)

I want to publish an app for users to all employees. (such as "Maker - Environment Request" app.)
How to grant access?

I think the following steps are unrealistic.
Therefore, when publishing an application for users such as "Maker --Environment Request" to the employees, add each user to the access right of the environment one by one and then add one person to the access right of the application one by one.

This is a machine translated text.
Please let me know if there is something wrong.

Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2022

### What app or flow are you having the issue with?

Maker - Environment Request

**Comment by sudadakkota** [comment]
Thanks, I had a misunderstanding.
Let me ask you an additional question.

If you created your production environment without configuring access restrictions by security groups, you should be able to access it by default for all users.
<img width="162" alt="image" src="https://user-images.githubusercontent.com/70095092/167981860-e591ea16-ccad-4a7d-a161-b3ac40986c1e.png">

However, the environment does not exist in the environment list that can be selected from the Power Apps header.
According to the Power Platform Admin Center, the accessing user was not granted any roles in the environment.

Do I need to assign a role here?
Also, is there a procedure to assign roles to many users at once?

This is a machine translated text.
Please let me know if there is something wrong.

Thank you.

**Comment by Jenefer-Monroe** [comment]
No you would not expect people to see it unless you grant them permissions. 

Security groups are just one way to secure an environment. You should instead use security roles and assign people to them directly. By default only the createor of the envt will see it, as they will be automatically added to hte Sys Admin security role. 

Here is some general information about security roles: 
https://docs.microsoft.com/power-platform/admin/wp-security-cds
https://docs.microsoft.com/power-platform/admin/security-roles-privileges

We provide 3 Security roles for you to use which align with the tables used in the kit. Please see 
https://docs.microsoft.com/power-platform/guidance/coe/core-components#security-roles

**Comment by sudadakkota** [comment]
Thanks.
I understand that I need to grant a security role to allow access to the environment.

As a reminder, is there any problem with the operation of the CoE Starter Kit even if the security role is assigned for each security group?
If all is well, I will do it by following the steps in the link below.

https://docs.microsoft.com/en-us/power-platform/admin/wp-security-cds#associate-a-business-unit-with-an-azure-ad-security-group
