### ISSUE TITLE
[CoE Starter Kit - BUG] When Sharing the Command Center person sharing with gets a Prompt for HTTP with Azure AD

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#2684]
### Describe the issue

When Sharing the command centre the person I am sharing it with gets prompted to for the Azure AD URI and the Base Resource URL: 
![image](https://user-images.githubusercontent.com/8484048/167822566-424964bb-594e-42b2-b3b0-1fb063a6a945.png)

### Expected Behavior

I expect to be able to share the command center with other people

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Command Center

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by NPrice99** [comment]
Hi Jenefer 

I have checked your questions and there are no unmanged layers and the connections are all good.

Yes, I see it when the person with whom I am sharing the App opens the App for the first time.

Inserting the graph url into both questions seems to make the app work.

Regards

Nigel
