### ISSUE TITLE
[CoE Starter Kit - BUG] Link to language support is broken

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#2686]
### Describe the issue

There might be some translations missing in **Power Platform Admin View**:

![image](https://user-images.githubusercontent.com/15800069/167875996-1f526f92-3e9a-4cbc-a922-6c93eff8012a.png)

### Expected Behavior

The default caption (english) is visible for the tabs.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2022

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

Session / Environment details:

Cluster environment: Prod
Cluster category: Prod
Cluster geo name: EU

**Comment by megel** [comment]
@Jenefer-Monroe  😥 your link leads to a chapter with a dead link:


_More information: [Regional and language options for your environment](https://docs.microsoft.com/en-us/power-platform/admin/enable-languages.md)_

The result is:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/15800069/167910470-49d2bcec-a2bd-4309-88de-c11f831d352e.png">

**Comment by manuelap-msft** [comment]
Docs updated locally, ready for June release.

**Comment by megel** [comment]
@manuelap-msft @Jenefer-Monroe maybe you see, what I oversee in my settings...

I have enabled the language code:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/15800069/171013238-d9b0bf02-4456-440f-b892-a4dd3300bceb.png">

... and I have selected **english** as user interface language:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/15800069/171013602-aa4b70d8-72dc-4123-bea3-fae11744387a.png">

As result, I see now Tab, Tab, Tab:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/15800069/171013672-114cb1e8-00f3-4111-95e1-56972d13105e.png">

any idea?

**Comment by manuelap-msft** [comment]
Did you enable the language after import? I think we have had a few people have issues with this when the language pack wasn't available on initial import.

**Comment by megel** [comment]
Where can I check / do I enable the language pack?

**Comment by manuelap-msft** [comment]
Environment > Settings > Languages is where you can check, but looks like you've already done that!

I'm not sure what else to suggest,
1. We have one user who installed the language pack, and then it solved the problem but it re-occured when they did an upgrade https://github.com/microsoft/coe-starter-kit/issues/2223
2. We have one other user who also has the Tab Tab Tab problem https://github.com/microsoft/coe-starter-kit/issues/1721

We don't repo this so unfortunately unable to help fixing it. If this is a fresh install, maybe you can re-create the environment and select English as the Dataverse language to begin with. If you're not able to re-do the enviornment, you may have to edit the forms to update the tab names.
