### ISSUE TITLE
[ALM Accelerator - QUESTION] Use AA4PP that uses SharePoint

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2691]
### What is your question?

Is it possible to use the ALM Accelerator with an app that uses a sharepoint site for DEV but another one for UAT/TEST and PROD ?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

latest

**Comment by kallisto08** [comment]
Good morning @manuelap-msft 

It is indeed, we use this where the the developers all have their own SharePoint sites and lists, then copies in Validate, Test & Production. 
If you use Environment variables one for the site url and one for list name you can swap these out in the deploymentSettings.json for development (and the pipeline variables for deployment to validate, test and production environments)

Thanks

**Comment by mikefactorial** [comment]
@kallisto08 is right again as usual :) Thanks for contributing back to the community! 🥇

**Comment by mikefactorial** [comment]
Closing for now as nothing more to do on this issue.
