### ISSUE TITLE
[CoE Starter Kit - QUESTION] Report on Flow Action details 

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2695]
### What is your question?

Possible to get a report not just of the Actions used (like send email) but the permissions that are granted and used? "Send on behalf of" for example.

**Comment by Jenefer-Monroe** [comment]
This one would need to be explored on a case by case basis as the specialty schema is different for each connector. So perhaps we should use this one for the send on behalf / outlook connector?

**Comment by manuelap-msft** [comment]
No info available in the product for this level of information. Would likely also be too API intensive for us to consume. Not enough customer demand.
