### ISSUE TITLE
[CoE Starter Kit - BUG] COE doesnt sync flows audit run history

### ISSUE THREAD

**Issue by kierianmsft** [microsoft/coe-starter-kit#2697]
### Describe the issue

we are facing issue with COE doent sync flows run history

### Expected Behavior

Sync flows Audit run history

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

admin sync flow template

### Steps To Reproduce

OPEN coe dashboard naviagate to any flows cant see flow history

![image](https://user-images.githubusercontent.com/105372968/167952598-208e7469-1df6-4077-8f46-b3eec2fb67a0.png)

### Anything else?

NO

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately this is a known limitation. We cannot collect usage logs for flows. Please see https://github.com/microsoft/coe-starter-kit/issues/433 on our backlog if you would like to track. And thanks for using CoE
