### ISSUE TITLE
Admin | Welcome Email v3

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#2701]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/2699

<div type='discussions-op-text'>

<sup>Originally posted by **ClaudiuVio** May 12, 2022</sup>
Hello,

If I will change the default flow Admin | Welcome Email v3 the trigger to 

- Change type Added
- Table Name  Power Apps Apps
- Scope Organization

![image](https://user-images.githubusercontent.com/7468628/168020943-abb88ff3-e11a-4375-a316-42943e7773e4.png)

Does it mean that the owner of a newly created app will receive a welcome email?

We want to send a notification each time an app is created in order to fill out a form.

Thank you!</div>

**Comment by ClaudiuVio** [comment]
Hello, thank you for your response.

Are you referring to this trigger?

![image](https://user-images.githubusercontent.com/7468628/168070277-545a1b56-e2af-4f99-8b7f-95004c7fbc0e.png)

**Comment by Jenefer-Monroe** [comment]
Yes that would trigger every time a new record is added to the Power Apps table, meaning we have added a new app to the inventory.

**Comment by ClaudiuVio** [comment]
Yes, but I can't find dynamic content to help me send an email.

I tried to use these dynamic contents and they are not working :

![image](https://user-images.githubusercontent.com/7468628/168072618-cd5f0f6b-9611-4ab9-beb3-a6e93e261140.png)

**Comment by Jenefer-Monroe** [comment]
App Owner is a GUID that points to the related Maker table. You would need to use it as a lookup to Maker table and get the email information from there.

I'm afraid I am unable to assist further with developing a custom solution, we just dont scale to do that type of education and training. You may benefit from hiring out a partner, or looking into our community for help.
