### ISSUE TITLE
[CoE Starter Kit - BUG] Problem with flow Admin | Sync Template v3 (Connectors)

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2705]
### Describe the issue

When I try to turn on the flow I riceve this error..

![error](https://user-images.githubusercontent.com/101250592/168094582-b8a24e98-74cd-4165-937d-f2b0583fed72.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

**Comment by manuelap-msft** [comment]
See https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows in our documentation
![image](https://user-images.githubusercontent.com/55705669/168100759-60f48df4-980d-4288-98f7-a63418a0adf9.png)
