### ISSUE TITLE
[ALM Accelerator - QUESTION] - Solution unpacking process documentation

### ISSUE THREAD

**Issue by ajinkyaskulkarni** [microsoft/coe-starter-kit#2706]
### What is your question?

Hello,

I am right now in the process of setting up ALM accelerator for our tenant. I completed the setup documented from location https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform

In order to test the pipleines for deployment, i am planning to create a solution package which includes a Power App and a flow. My question is regarding creating a unpacked solution which can source controlled and deployed using the YAML files.

Where can i find the documentation of exporting the msapp files so the structure below is met (I encountered an issue while a folder 'SolutionPackage', please see the error below).

![image](https://user-images.githubusercontent.com/25870713/168100901-4959a57a-4f8f-48fd-bf8f-4b94d8b8972c.png)

- ALMDeploy/SolutionPackage/ # Replace SolutionFolder with actual folder name in repo
- ALMDeploy/Plugins/ # Replace SolutionFolder with actual folder name in repo
- ALMDeploy/WebResources/ # Replace SolutionFolder with actual folder name in repo

The folder hierarchy of the test exported soluton is as below,
![image](https://user-images.githubusercontent.com/25870713/168101338-cb2e1219-5984-4693-b41d-5402f99b7343.png)

Contents of canvass app folder (packed msapp and dependency files)
![image](https://user-images.githubusercontent.com/25870713/168102009-f3b37f31-4944-4a3b-8fe7-dfb6a38cc30e.png)

I am looking for the way of inputting the exported or unpacked solution as expected by pipeline. can you please guide me steps or point me to documentaton.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

March 2022

AB#1302

**Comment by mikefactorial** [comment]
@ajinkyaskulkarni assuming you are using the ALM Accelerator canvas app. The app will take care of exporting and expanding the solution for you. If you're not planning on using the App for this purpose then you'll need to look into how we do the export and unpack process in the following YAML. On line https://github.com/microsoft/coe-alm-accelerator-templates/blob/b4cc4825556d8ce80e878fb742dbe016e521b621/Pipelines/Templates/export-Solution.yml#L107 you'll see that we are using the PowerPlatformUnpackSolution task to expand the solution to source code. Additionally, we are using the PowerAppsLanguageTooling in line https://github.com/microsoft/coe-alm-accelerator-templates/blob/b4cc4825556d8ce80e878fb742dbe016e521b621/Pipelines/Templates/export-Solution.yml#L132 to expand msapp files to source code. Extracting from a solution zip file won't provide the expected structure the way the unpack process does.

**Comment by mikefactorial** [comment]
This doc may assist in understanding the process involved when using the ALM Accelerator App https://docs.microsoft.com/en-us/power-platform/guidance/coe/almacceleratorpowerplatform-advancedmaker

**Comment by mikefactorial** [comment]
The following will assist in understanding the unpack process we are using 

https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks#power-platform-unpack-solution
https://github.com/microsoft/PowerApps-Language-Tooling

**Comment by ajinkyaskulkarni** [comment]
@mikefactorial Thanks for your reply.

I did proceeded with the ALM accelerator canvas app. There are two errors. one for solution containing jsut a flow and another for a solution contaaining a canvas app.


**Name of pipeline - export-solution-to-git - scenario with solution containing only flow**
![image](https://user-images.githubusercontent.com/25870713/169297631-6248211e-7d5d-41ad-a13f-724fa3fc16fa.png)

**Name of pipeline - export-solution-to-git - scenario with solution containing a canvas app**
![image](https://user-images.githubusercontent.com/25870713/169299165-8ce0272f-2d78-4347-833e-20800f34640a.png)

Pipeline variables
![image](https://user-images.githubusercontent.com/25870713/169299742-259f8542-05ac-408e-98e9-99c001f10661.png)

Can you suggest what migh be the problem.
