### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs 2.9 Upgrade still NO UPN

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#2714]
### Describe the issue

Hello,

After the upgrade of :

Center of Excellence - Core Components 3.38
Center of Excellence - Audit Logs 2.9
Center of Excellence - Governance Components 2.16 

Still NOUPN for the audit logs.

![image](https://user-images.githubusercontent.com/7468628/168214720-3ccbab5f-217c-497b-95cd-a394dfa9a4c1.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Active Audit Logs

**Comment by ClaudiuVio** [comment]
![image](https://user-images.githubusercontent.com/7468628/168269250-a1aa5650-bad0-4d6d-bfe4-02786b30fbf5.png)

**Comment by Jenefer-Monroe** [comment]
Did you check for unmanaged layers? Please see step 3 of [installing upgrades](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)
![image](https://user-images.githubusercontent.com/89584709/168292627-f2bd0bd9-d482-4542-88e9-98af61f37a76.png)

Note that sometimes unmanaged layers get added without you being aware of it.

**Comment by bhavikj65** [comment]
This is not an issue with CoE but the property CoE is trying to use has NoUPN if you check Audit Logs from M365 Compliance Center, Edit your Audit Logs flow and use the following property "
![image](https://user-images.githubusercontent.com/105588534/168470377-151f07a3-6232-43e6-816c-64e06752552e.png)
" and you will start getting UPN's.

**Comment by ClaudiuVio** [comment]
> Did you check for unmanaged layers? Please see step 3 of [installing upgrades](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades) ![image](https://user-images.githubusercontent.com/89584709/168292627-f2bd0bd9-d482-4542-88e9-98af61f37a76.png)
> 
> Note that sometimes unmanaged layers get added without you being aware of it.

Hello,

Thank you for your help, after I removed the unmanaged layer and make the connection again, it's working.

Thanks once again.
