### ISSUE TITLE
[CoE Starter Kit - Feature]: Automated Back-ups for Flows, Apps

### ISSUE THREAD

**Issue by dylanwauters** [microsoft/coe-starter-kit#2717]
### Describe the solution you'd like

It would be nice to automate backups for Flows and Apps to a SharePoint document library. Also the ability to restore the app or flow to its original location. A power app to manage backups would be nice!

**Comment by Jenefer-Monroe** [comment]
Hello, we used to offer this functionality but as the product became more sophisticated (env variables, connection references, ...) we could no longer restore reliably.

Solutions are really the way to do this for complex apps/flows. Create the content in a solution and create backups

Hope that clarification helps.

**Comment by dylanwauters** [comment]
Backups are still manually than. Maybe something you could include in the ALM accelerator app that after every solution release it takes a backup on a SharePoint library?

**Comment by Jenefer-Monroe** [comment]
Moving to ALM team to consider.

**Comment by Jenefer-Monroe** [comment]
The ask (as I understand it) is to have solution files auto-backed up.

**Comment by jenschristianschroder** [comment]
ALM Accelerator will automatically store any solution that is committed to source control and offer capability to restore (deploy) a solution to an environment. 

We have no plans to support storing solutions or individual solution components to SharePoint sites.
