### ISSUE TITLE
Nurture Components 2.11 import(upgrade) error 8004F036

### ISSUE THREAD

**Issue by cmd-k33n** [microsoft/coe-starter-kit#2718]
Trying to update the Nurture Components from v2.09 to v2.11, import is failing with error [8004F036](http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=8004F036&de=online)

_The dependent component Workflow (Id=8a28c32f-dd86-ec11-93b0-000d3a5b2abe) does not exist. Failure trying to associate it with CanvasApp (Id=3877040e-2a0d-4f45-9124-3b701029508a) as a dependency. Missing dependency lookup type = PrimaryKeyLookup._

I've checked for the existence of the mentioned Workflows through Powershell but both coming up as not existing - not sure how to deal with this since there is apparently nothing there... does anyone have tips to resolve?

**Comment by cmd-k33n** [comment]
Adding to the above, I noticed that solution.xml contained in the CenterofExcellenceNurtureComponents_2.11_managed.zip references solution="CenterofExcellenceCoreComponents (3.34)" however the May 2022 release contains CenterofExcellenceCoreComponents (3.38) - would it help to change that in the solution.xml file?

**Comment by A-Demir-ilx** [comment]
I have the same issue

**Comment by Chunlau99** [comment]
Me too I have the same issue as well

**Comment by manuelap-msft** [comment]
We released a hotfix release to address this issue
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-May2022-HF1

Please let us know if you continue to face issues, we've done some testing on our end and don't repo anymore!

**Comment by cmd-k33n** [comment]
> 0

Import of version 2.12 worked like a charm, thanks!

**Comment by cmd-k33n** [comment]
> We released a hotfix release to address this issue https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-May2022-HF1
> 
> Please let us know if you continue to face issues, we've done some testing on our end and don't repo anymore!

Import of version 2.12 worked like a charm, thanks!

**Comment by manuelap-msft** [comment]
> thanks so much, it's was tired installed releases hotfix release May2022 was successful installed 3.38 version but we have another issue cannot uninstall old version and got error code below for your reference. thanks
> 
> Error code [8004F01D](http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=8004F01D&de=online) Exception message Solution dependencies exist, cannot uninstall. DependencyCount : 7 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: f155e36d-31eb-481f-8b20-0d132f4efe4a, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: e3c0ae31-f12d-4883-b956-411cf16da285, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Welcome Policies New Maker, Id: c691aa41-2e54-eb11-a812-000d3ab9bc3d, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: e3c0ae31-f12d-4883-b956-411cf16da285, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Welcome Policies SP List Maintenance, Id: e7ce02a9-2f54-eb11-a812-000d3ab9bc3d, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: 63d051e2-43f9-4a92-a18e-4eff3f631bc9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerPlatformAdminCoEConnection, Id: a104faa4-8324-4b48-8d20-81049d0b6f7c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoEv3SyncTemplatesCDS, Id: 8bab5caf-3df7-4af2-8c3f-9d434a534c67, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoEv3SyncTemplatesCurrent, Id: df324b1f-2f62-4aa7-a6bd-bb4f64301428, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 See less

Please raise a new issue for this, as this is a seperate issue. It's tricky for us to triage and respond to multiple issues reported in one thread! Thank you!
