### ISSUE TITLE
[CoE Starter Kit - BUG] Audit log installation

### ISSUE THREAD

**Issue by 365CornerDavid** [microsoft/coe-starter-kit#2719]
### Describe the issue

I just went via the Audit Log setup and imported news version of the Audit Log solution from May release of CoE.
I see following error in [Child] Admin | Sync Logs flow
![image](https://user-images.githubusercontent.com/43808961/168310717-ffab6083-53fc-4ca9-9e05-0ac9ca56094f.png)
when I try to save the flow
![image](https://user-images.githubusercontent.com/43808961/168310823-45e3002e-ade9-461f-a773-6418766c5110.png)
and when tried to turn on the child flow
![image](https://user-images.githubusercontent.com/43808961/168310966-48e2f47d-88cf-449b-bc42-3f25bc0348ad.png)

I'm wondering if this is bug or I just did not upgraded the core of CoE for too long and the Audit Log table has been updated already?
Apprciate the answer.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

[Child] Admin |Sync Logs

**Comment by manuelap-msft** [comment]
We've introduced a new field in the Audit Log table, which is part of the Core components solution, in the May release. So you'll have to upgrade Core first before you can upgrade or install Audit Log.

**Comment by 365CornerDavid** [comment]
Thanks, that make sense :) appreciate prompt answer :)
