### ISSUE TITLE
App User security role

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#272]
**Is your feature request related to a problem? Please describe.**
concern that sys.adm. security role has more priviliges than required for the app user

**Describe the solution you'd like**
Find the absolute minimum permissions required for the app user to be able to support the functionality

**Describe alternatives you've considered**
Start out with a copy of sys.customizer and identify what needs to be added.

**Comment by devkeydet** [comment]
This all depends on what your pipelines do.  There is no one size fits all role.  We can certainly do this for our pipelines, but we need to be clear to not give the impression this will work for every pipeline.

**Comment by mikefactorial** [comment]
Closing this out as there's no further action to be taken on this based on the previous response. It all depends on what the pipelines require permissions to do.
