### ISSUE TITLE
[CoE Starter Kit - Feature]: Licensing Details

### ISSUE THREAD

**Issue by amworland** [microsoft/coe-starter-kit#2722]
### Is your feature request related to a problem? Please describe.

As licensing becomes more varied, it would be fantastic to access information about the apps that are allowed to consume per app/app passes, as well as to see what environments are pay as you go.  Additionally it would be helpful to be able to use this data to help discern license usage patterns among users.

Example 1: This app is shared with 45 users, is in a pay as you go environment with 100 app passes, and is the app is permitted to use those passes.  25 of them are per user licensed and 20 of them are utilizing per app licenses.

Example 2: Bob is a user of 4 apps that contain premium connectors and is not a Per User license.  How often is Bob using these apps? Are we sharing things to Bob appropriately and should we consider giving a Per User license?

### Describe the solution you'd like

New Table/Entity to house licensing data - relate to Maker/User records.

Add additional fields for Apps/Environments to indicate if has App Passes

### Describe alternatives you've considered

Pulling licensing data separately and utilizing some of the dataverse data to associate the information.

**Comment by Jenefer-Monroe** [comment]
Did you reset the flows after you updated the environment variable? 
Note that Power Automate caches values for environment variables and so you need to turn the flow off and back on in order to see the new value. 

Please see the note in our FAQ documentation:
https://docs.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables

**Comment by Jenefer-Monroe** [comment]
Very nice suggestion. Putting on the backlog for consideration.

**Comment by manuelap-msft** [comment]
The CoE starter Kit is built on top of the platform, and can only use what's available in the platform. At the moment, license and usage information is not available to the CoE in a way that we can consume - e.g. API, other data source, connector. We'll add this to our backlog but I want to set expectations in that we can only fulfill this ask once the platform makes this data available.

**Comment by manuelap-msft** [comment]
Closing out items where there is no product backlog to get this information.
