### ISSUE TITLE
Attribute 'value' was not found for environment variable 'admin_PowerPlatformMakeSecurityGroup'."}}". Code: 0x80060467 InnerError: '.[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by KezHalls** [microsoft/coe-starter-kit#2726]
### Describe the issue

Unable to turn on flow with
Admin | Add Maker to Group
Attribute 'value' was not found for environment variable 'admin_PowerPlatformMakeSecurityGroup'."}}". Code: 0x80060467 InnerError

### Expected Behavior

flow turns on

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin - Add Maker to Group

### Steps To Reproduce

1. Edit flow and verify connections
2. Save flow 

or 
1. Select flow
2. Turn on

**Comment by manuelap-msft** [comment]
It looks like you might have missed filling out the **Power Platform Maker Microsoft 365 Group** environment variable
![image](https://user-images.githubusercontent.com/55705669/168586145-4c9289ff-bf44-45dd-9983-9454ac25d138.png)


See

- https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values
- https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users
- https://docs.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
