### ISSUE TITLE
Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization.

### ISSUE THREAD

**Issue by brendon-colburn** [microsoft/coe-starter-kit#273]
**Describe the bug**
When attempting to deploy to TEST we are presented with this error in the EXP environment.

**To Reproduce**
1. Follow the configuration guide (and configure things not included in guide via sidebar conversations)
2. Create a project, work in the created DEV environment
3. Click deploy to TEST

**Expected behavior**
Repo gets updated with a new branch, solution gets deployed to TEST

**Screenshots**
![image](https://user-images.githubusercontent.com/16350948/117036347-52abcd80-acd3-11eb-99b6-469db0987dc4.png)
![image](https://user-images.githubusercontent.com/16350948/117036646-a4545800-acd3-11eb-81b6-3b352deb99b3.png)

**Additional context**

**Comment by brendon-colburn** [comment]
Here's a bit of extra context, it appears that we have saml enabled on our GitHub Enterprise Org:

**Comment by brendon-colburn** [comment]
I worked with @snapfisher to resolve this issue, it turns out that when we changed over from a free Github org to our Github Enterprise org we needed to reauthenticate via a prompt to the connector and reapply the connection reference to all applicable Power Automate steps.  From a documentation standpoint, there may be value in calling out that pointing the tool to a new org requires this remediation.  @devkeydet, I'm willing to assist on that front if you can point me to where that documentation would live.

**Comment by devkeydet** [comment]
@mikefactorial - please work with @brendon-colburn  on getting the docs update.
