### ISSUE TITLE
[CoE Starter Kit - BUG] admin_sharedtotal column does not exist

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [microsoft/coe-starter-kit#2731]
### Describe the issue

Getting the following after updating to 3.38 last week: 

There was an error when processing the data in the dataset.Hide details
Data source error:	The '<pii>admin_sharedtotal</pii>' column does not exist in the rowset.
Cluster URI:	WABI-US-EAST2-redirect.analysis.windows.net
Activity ID:	27403d41-8b6a-4550-9338-4be40cb17692
Request ID:	0ccc081e-6d96-1599-9a9a-1e91e42d04ce
Time:	2022-05-16 14:22:39Z

#2478 states that updating the Power BI report should fix, however I have a number of customizations that I don't want to lose.  Is there a way to fix this vs: deploying a new version of the PBI report?  

### Expected Behavior

Power BI report should refresh without error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Power BI Dashboard

### Steps To Reproduce

Open Power BI Online Service
Refresh the dataset linked to the BI Report
The error occur at the refresh

**Comment by Jenefer-Monroe** [comment]
If you can still open the PBIX (may need to deploy an old version of Core and point to it to do this) you can remove references to it. I believe it was only on the App Shared page.

**Comment by DaveTheTeamsGuy** [comment]
No problem, closing.
