### ISSUE TITLE
[CoE Starter Kit - QUESTION] Using Azure DevOps to Manage CoE Releases

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#2732]
### What is your question?

We wanted to be able to clone the CoE repository to our Azure DevOps and then Pack the managed solutions so that we could use a DevOps release pipeline to import the CoE solutions, however we found that when packing the solution it would fail because some of the filenames contain whitespaces. We would get the following error:
Cannot find required file 'D:\a\r1\a\_CoE Starter Kit\CenterofExcellenceAuditComponents\SolutionPackage\CanvasApps\admin_appandflowarchiveandcleanupview_9feed_DocumentUri_msapp_src\pkgs\TableDefinitions\Archive%20Approvals.json'.
We were able to confirm that it is the space causing the issue by renaming the file without a white space. It would then fail on the next file it found with a white space.

Best practice would suggest that filenames should not contain white spaces.
We are using the Power Platform Pack Solution tool.
Do you have a solution for this?

### What solution version are you using?

May 2022

**Comment by mikefactorial** [comment]
@medicineshow we use the ALM Accelerator to source control / build the CoE Starter Kit. There are some specific steps in the ALM Accelerator pipelines that you would need to include in your pipeline to build the CoE Starter Kit. The specific error you are seeing is likely because you aren't packing the canvas apps before packing the solution which are two different steps currently. Take a look at https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/build-Solution.yml for inspiration.

**Comment by medicineshow** [comment]
Thanks @mikefactorial. we will look at this option.

**Comment by medicineshow** [comment]
@mikefactorial thanks for the direction. we now have it working. Only issue we have is the versioning. How can we pick up the actual version that you are using as it only seems to want to display our own version which does not represent current.

**Comment by medicineshow** [comment]
@mikefactorial can you provide any answer for my question above? Thanks.

**Comment by medicineshow** [comment]
@manuelap-msft @Jenefer-Monroe @mikefactorial apologies if you are not responsible for this feed but please can someone respond to our last question re update versioning? It has been 21 days since we first asked and nobody has responded. Thank you in advance.

**Comment by manuelap-msft** [comment]
Hello,

@mikefactorial is on a well deserved holiday at the moment! I'll catch up with him next week and we'll respond then! Apologies for the delay!

Thank you for using the CoE,
Manuela

**Comment by manuelap-msft** [comment]
No need to apologize!! Thanks for keeping this on our radar! :)

**Comment by mikefactorial** [comment]
@medicineshow just getting back to this after vacation and wrapping up the July release. I'm not sure I follow your question regarding the versioning. Are you asking specifically about the version number of the solution? You can see the versioning schema in the pipeline we use to deploy the core and other components in their respective solution folders e.g. for the core components the version is based on this line in the pipeline https://github.com/microsoft/coe-starter-kit/blob/2c4a8489c561527af35aee32344774d59108c798/CenterofExcellenceCoreComponents/deploy-test-CenterofExcellenceCoreComponents.yml#L20

**Comment by medicineshow** [comment]
Hi @mikefactorial. Sorry, but do you have a response to my last post please?

**Comment by mikefactorial** [comment]
@medicineshow the version that gets set when we release is determined by the deploy-prod-* pipeline. You can see that here. Specifically for the Core components, but the same for the other components. https://github.com/microsoft/coe-starter-kit/blob/f930c97ef40c9d1f7be027bfeaec080378563d16/CenterofExcellenceCoreComponents/deploy-prod-CenterofExcellenceCoreComponents.yml#L13

**Comment by mikefactorial** [comment]
We maintain a date based version in the lower environments to make it easier to determine when the build happened but for the sake of brevity in the released version we stick with just major and revision. This isn't the case for the ALM Accelerator which may be confusing, but we decided internally to allow the kits to choose their own versioning strategy based on the audience of users.

**Comment by mikefactorial** [comment]
Closing this out for now since there's nothing more to do here. Feel free to open a new issue if need be.
