### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Dashboard Dataset Refresh Fails

### ISSUE THREAD

**Issue by Fryimb** [microsoft/coe-starter-kit#2733]
### Describe the issue

Hi,
When refreshing the dataset for the  CoE dashboard, it fails with the following error:

Erreur de source de données : Column '<pii>admin_portalenvironment</pii>' in Table '<pii>Portals</pii>' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
URI du cluster : WABI-WEST-EUROPE-B-PRIMARY-redirect.analysis.windows.net
ID d'activité:  8431edb7-15db-4ee7-8b89-9fe7e73fb79a
ID de demande:  f2391a8f-34f8-4aa1-96f7-74cd306fdabb
Heure:  2022-05-07 23:15:57Z

The last refresh without issue was 07/05/2022, 13:03:39 .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Power BI Dashboard Dataset

### Steps To Reproduce

1. go to Power bi Workspace
2. select the dataset
3. click refresh now
4. wait 2 min 
5. a Red triangle show to say that refresh failed with the same message as description

### Anything else?

![image](https://user-images.githubusercontent.com/105657326/168623513-1c3bba04-5111-4cf3-926a-bf04e19d2815.png)

**Comment by Fryimb** [comment]
Ok, it will be the first time we update it.
But for update the solution there is an order ? (there no mention in  the link)
i remember see this and writed it in a pptx (09/21) , its still correct ?

1. Upgrade Nurture
2. Upgrade Gov
3. Update Audit Logs
4. Then upgrade Core

**Comment by Fryimb** [comment]
Updated the solutions, still have the same error.
Erreur de source de données: Column '<pii>admin_portalenvironment</pii>' in Table '<pii>Portals</pii>' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
URI du cluster:  WABI-WEST-EUROPE-B-PRIMARY-redirect.analysis.windows.net
ID d'activité:  0611ee83-b72f-4ef0-bade-b6e11f83c250
ID de demande:  91c4f586-b384-d5ad-049a-34f4c1dd0433
Heure:  2022-05-23 09:13:27Z

but also now have 
Erreur de source de données: The '<pii>admin_sharedtotal</pii>' column does not exist in the rowset.

**Comment by Jenefer-Monroe** [comment]
You need to update to the latest version of the PBI as well as we have changed some column types (Total Shared v Shared Total)

Please ensure you have no unmanaged layers on any of the flows and run the clean up flows.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
