### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Core Components Upgrade Error -From June 2021 to May 2022

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2735]
### Describe the issue

Hello Team,

I am upgrading the CoE core components from June 2021 version to May 2022 version by following the upgrade process as described here - https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup

1. Removed unmanaged layer
2. Imported core solution with "Upgrade" option.

However, during the activity of import, I face the dependency error as follows:

```
RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEConnection, Id: XXXXXXXXX , ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000,
DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: XXXXXXXX, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 
```

Next, When I click on Solution layer for the same, I see as follows:
![image](https://user-images.githubusercontent.com/98403757/168630007-e1fb2259-1401-4f98-a33a-60418b931aec.png)

Which means, to upgrade the core component, I have to remove the connection reference in the Audit Solution - is that advisable to execute to resolve this dependency error? I mean, if I remove the connection reference, then the flow for the same will be stopped? Would you please help, how do I go about this?

**Note:** I will need to upgrade all the solution at later stage, therefore, It might be ok to delete the connection reference from the other CoE solution? However If you could help confirm the same, will be greatly appreciated.

Thanks and Regards,

### Expected Behavior

Core component deployment should not have the dependency error and upgrade process should go smooth.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Core Component Connection References

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are doing is migrating inventory and audit logs, we did attempt to write up good how-to migrate steps for that here [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)
And a colleague created a good supplementary video for this as well: https://youtu.be/PL_J1eI5pFA

I do think you are on the right track there of deleting all the connection manually though. 

Sorry we can't be of more assistance.

**Comment by tomsinsight** [comment]
Thank you Jennifer for your time and the assistance, It is helpful to make further decisions!

**Comment by Jenefer-Monroe** [comment]
You bet, thanks for using CoE
