### ISSUE TITLE
[CoE Starter Kit - BUG] COE ALM generate install doesn't respect switches

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#2738]
### Describe the issue

When running the COE CLI ALM command ` coe alm generate install -o quickstart.json`, and choosing options such as:

The component(s) to install:
- all - All components required from Azure Active Directory, Azure DevOps and Power Platform environment
- aad - Install and configure Azure active directory components only
- devops - Install and configure Azure DevOps components only
- environment - Install and configure Power Platform components only

No matter what option you choose you are prompted for 'all', and that is what the script generates.
https://github.com/microsoft/coe-starter-kit/blob/main/coe-cli/docs/help/alm/install.md#parameters

### Expected Behavior

Script respects options chosen and generates the correct install file.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

0.0.1

### What app or flow are you having the issue with?

coe CLI

### Steps To Reproduce

Follow instructions for Quickstart, and choose to install devops only; or anything other than 'all'.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/overview#quick-start

### Anything else?

https://github.com/microsoft/coe-starter-kit/blob/main/coe-cli/docs/help/alm/install.md#parameters
https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/overview#quick-start

**Comment by mikefactorial** [comment]
Thanks for reporting this @peteredc. Looks like a bug will take a look into what the disconnect is.

**Comment by mikefactorial** [comment]
Reopening and moving to backlog as an enhancement to make the flow less confusing in cases where certain values aren't necessary based on the component selection since this isn't a bug.

**Comment by mikefactorial** [comment]
Closing this out as we are de-investing in the coe-cli in favor of automation via the ALM Accelerator admin app.
