### ISSUE TITLE
[CoE Starter Kit - Feature]: Inventory for custom pages

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2745]
### Is your feature request related to a problem? Please describe.

Custom pages (https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/add-page-to-model-app) are currently shown in the inventory just like regular canvas apps, with no way to differentiate between them.

In this screenshot, both Planner_ and Custom Page Template are custom pages:
![image](https://user-images.githubusercontent.com/55705669/168825258-2adaf70b-8ef6-4c0a-89c1-fa813d62a5d8.png)

Looking at the output from **Get Apps as Admin** (API version 2021-02-01), a custom page has 

` "appType": "CustomCanvasPage"`

whereas a regular canvas app has

 "appType": "ClassicCanvasApp"

### Describe the solution you'd like

We should record custom pages correctly as part of the App Type. I recommend extending the App Type to be
- Canvas App
- Model Driven App
- Sharepoint Form App
- Custom Page
(vs introducing a new subtype concept)

and setting this accordingly to Custom Page where the appType is CustomCanvasPage

**Comment by Jenefer-Monroe** [comment]
https://docs.microsoft.com/en-us/power-apps/maker/model-driven-apps/add-page-to-model-app

**Comment by manuelap-msft** [comment]
Done!
