### ISSUE TITLE
[CoE Starter Kit - QUESTION] Extending the CoE Starter Kit Solutions

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#2746]
### What is your question?

Dear Team,

Hope all is well!

We are in process of installing the CoE Starter Kit Solution in the new environments and I was wondering if we can follow the below approach:

For Example Core Components:

**Dev Environment:**
1. Install 'Center of Excellence - Core Components' solution
2. Copy  all the 'Center of Excellence - Core Components' solution components into the new solution named - 'CoE Core Custom' Solution
3. Turn off all the components of the 'Center of Excellence - Core Components' solution
4. Turn On/Turn off the flows as required in the 'CoE Core Custom' Solution
5. Customize components as required in the 'CoE Core Custom' Solution

**Test/Production Environments**
1. Install the 'CoE Core Custom'  solution
2. Activate components as required

Can we follow the above approach? Will, it has any negative impact on upgrading the CoE components in the future? Can we follow the above approach in the already existing CoE components of the previous version?

Appreciate your time in advance!

Thanks,

### What solution version are you using?

May 2022

**Comment by Jenefer-Monroe** [comment]
We have a document for this being written up now. Will let you know when its ready.

**Comment by DiptiC-InsightRun** [comment]
Thanks, Jennifer, Can't wait for the up coming document! It would be great if you could share an approximate timeline about the same, so we can plan our deployment accordingly.

Thank you again!
