### ISSUE TITLE
Admin | Sync Template v3 (Apps) - Duplicate key error

### ISSUE THREAD

**Issue by ragbn** [microsoft/coe-starter-kit#2752]
### Describe the issue

**Insert New Apps**  -> **Insert New App Details** -> **Check if Orphan** -> **No** step failed with following error:

Admin | Sync Template v3 (Apps) 

{

  "error": {

    "code": "0x80040237",

    "message": "A record with matching key values already exists.",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "9ec11-a7b7-00224810928f",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "615-a797-685acbbba17b",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "DuplicateRecord",

    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "412",

    "@Microsoft.PowerApps.CDS.ErrorDetails.SqlExceptionMessage": "Violation of PRIMARY KEY constraint 'PK_admin_AppBase'. Cannot insert duplicate key in object 'dbo.admin_AppBase'. The duplicate key value is <>.",

    "@Microsoft.PowerApps.CDS.HelpLink": "[http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040237&client=platform"](http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040237&client=platform%22),

    "@Microsoft.PowerApps.CDS.InnerError.Message": "Cannot insert duplicate key."

  }

}

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponentsTeams_3_19_managed.zip

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

**Comment by Jenefer-Monroe** [comment]
Most likely you had a race condition with the flow was running twice accidently. 
To test this specific case please just rerun the flow. 

Generally, to see why you might have had two instances going at once, please go look at the flow runs for this flow, as well as the driver flow (Admin | Sync Template v3) and make sure they are completing and passing (vs being throttled and not ending)
Be sure also that you do not have the [full inventory](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory) on all the time as that uses a lot of API calls and will lead to throttling.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
