### ISSUE TITLE
[CoE Starter Kit - BUG] I cannot see desktop flow run

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2753]
### Describe the issue

Hello,
I can't see desktop flow run on Power BI dashaboard.
How can I solve it?

Thanks

![bi](https://user-images.githubusercontent.com/101250592/168975809-80ba3091-5210-41c0-a4ea-1045ec1c69cb.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.36

### What app or flow are you having the issue with?

Power BI Dashboard

**Comment by Jenefer-Monroe** [comment]
Check to see if the data is in the tables at all via the Power Platform Admin View model driven app
If it is, then likely your PBI just isnt set to auto-refresh. Please revisit the [setup instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard) for how to setup scheduled refresh. 
![image](https://user-images.githubusercontent.com/89584709/169035290-2eb85727-2ac0-4ea0-96da-f7fd9390b8eb.png)

If its not, then go through the runs you see there till you have an environment you expect to see desktop flows and begin to investigate. Let me know if you need help

**Comment by JackSocini** [comment]
Hello,
hera you can find some screenshot..
The database was updated automatically every hour.

![bi2](https://user-images.githubusercontent.com/101250592/169037006-95bbfda0-f124-4a82-8659-7da0b7202209.jpg)
![bi3](https://user-images.githubusercontent.com/101250592/169037010-ff7c655d-61af-4611-bfc4-5ce6945f7552.jpg)

**Comment by Jenefer-Monroe** [comment]
Can you please validate that **_Admin | Sync Template v3 (Desktop Flow - Runs)_** is running and passing?

**Comment by JackSocini** [comment]
Here the screenshot
![flow](https://user-images.githubusercontent.com/101250592/169260490-d8efd3af-57e7-4c33-bfb5-04198658cf61.jpg)

**Comment by Jenefer-Monroe** [comment]
I'm afraid we dont repro. Here are some clues which I hope help you. 

In  order to see runs in this list, one of the following must be true:

You have [run an attended or unattended desktop flow](https://docs.microsoft.com/en-us/power-automate/desktop-flows/run-desktop-flow) in the current environment

Another user has [shared their desktop flow](https://docs.microsoft.com/en-us/power-automate/create-team-flows#share-a-cloud-flow-with-run-only-permissions) with you, which has run in the current environment

You have [permission](https://docs.microsoft.com/en-us/power-platform/admin/database-security) to view all data in the environment

https://docs.microsoft.com/en-us/power-automate/desktop-flows/monitor-desktop-flow-runs

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
