### ISSUE TITLE
[CoE Starter Kit - BUG] Document desktop flow run limitations

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#2757]
### Describe the issue

In  order to see runs in this list, one of the following must be true:

You have [run an attended or unattended desktop flow](https://docs.microsoft.com/en-us/power-automate/desktop-flows/run-desktop-flow) in the current environment

Another user has [shared their desktop flow](https://docs.microsoft.com/en-us/power-automate/create-team-flows#share-a-cloud-flow-with-run-only-permissions) with you, which has run in the current environment

You have [permission](https://docs.microsoft.com/en-us/power-platform/admin/database-security) to view all data in the environment

https://docs.microsoft.com/en-us/power-automate/desktop-flows/monitor-desktop-flow-runs

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

documentation

**Comment by manuelap-msft** [comment]
Added this to our limitations page for June docs.
