### ISSUE TITLE
[CoE Starter Kit - BUG] Impossible to turn ON flow " HELPER - ObjectOperations Gov"

### ISSUE THREAD

**Issue by JMG74** [microsoft/coe-starter-kit#2763]
### Describe the issue

Hello Team!
I’m getting the following error when trying to turn ON the flow:
> Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowUnsupportedForInvokerConnections","message":"The workflow with id 'ab3784ff-ceef-eb11-bacb-00224820693c', name HELPER - CanvasAppOperations Gov cannot be used as a child workflow because child workflows only support embedded connections."}}"

As stated in the installation documentation (https://docs.microsoft.com/en-gb/power-platform/guidance/coe/before-setup-gov#turn-on-child-flows), I tried to set set the run-only user properties (https://docs.microsoft.com/en-gb/power-platform/guidance/coe/faq#set-flow-run-only-users-properties) but when I click on the "Edit" button of section "Run only users", I don't see any connection to change ?!? 
![image](https://user-images.githubusercontent.com/13162921/169082368-2f138859-69a1-4d61-9b02-c04adc83812c.png)

As a consequence of the 1st error, the flow "Request Orphaned Objects Reassigned (Child)" gets also into trouble when I try to turn it ON:
> Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowUnsupportedForInvokerConnections","message":"The workflow with id 'ab3784ff-ceef-eb11-bacb-00224820693c', name HELPER - CanvasAppOperations Gov cannot be used as a child workflow because child workflows only support embedded connections."}}".

### Expected Behavior

No error.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.16

### What app or flow are you having the issue with?

Flow: HELPER - ObjectOperations Gov

### Steps To Reproduce

Try to turn flow "HELPER - ObjectOperations Gov" ON.

### Anything else?

Thanks in advance

**Comment by JMG74** [comment]
Great ! Thank you, it's ok now.
All the best.

**Comment by Jenefer-Monroe** [comment]
wonderful thanks for confirming!
