### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - Error when Importing to Teams

### ISSUE THREAD

**Issue by jvolk21** [microsoft/coe-starter-kit#2764]
### What is your question?

I am trying to import the Core Components for Teams and it runs into an error. Any suggestions?

Error: 
The dependent component Workflow (Id=f28355ee-092d-ec11-b6e5-000d3a4efe76) does not exist.  Failure trying to associate it with CanvasApp (Id=2fa40f43-1455-4c51-9c39-e7506d2042ae) as a dependency. Missing dependency lookup type = PrimaryKeyLookup.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponentsTeams_3_19_managed.zip

**Comment by manuelap-msft** [comment]
This was addressed with the hotfix release 3.19.1 yesterday: https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-May2022-HF1

Direct download link: https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-May2022-HF1/CenterofExcellenceCoreComponentsTeams_3_19_1_managed.zip
