### ISSUE TITLE
[CoE Starter Kit - BUG] AUDIT LOGS IS NOT ABLE TO CAPTURE THE USER UPN ITS GIVING NO UPN

### ISSUE THREAD

**Issue by pavantagirisa** [microsoft/coe-starter-kit#2765]
### Describe the issue

We have CoE audit logs solution installed and enabled all flow with custom connector.
Since then we are able to identify to whom the app is shared, but its giving bunch of records as **No UPN** for the app launches.

As we can share the apps with only the users with in our tenant why we are seeing No UPNs

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Power Apps)

**Comment by manuelap-msft** [comment]
Hello,

this issue was addressed in the May release, see #2665 and #2714. Make sure to remove any unmanaged layers you may have on those flows to receive our latest update and changes. Instructions for how to do that are in these issues #2665 and #2714

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
closing as duplicate. Thanks for using CoE
