### ISSUE TITLE
CoE Install Issue

### ISSUE THREAD

**Issue by mattriesae** [microsoft/coe-starter-kit#2766]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/2655

This wasn't my post but I'm having the same error. When I view the runs of that child flow (Helper - Maker Check), it's failing with an error of:
Could not find a property named 'SYSTEM' on type 'Microsoft.Dynamics.CRM.admin_maker'.
 
The user running these has Sys Admin on the Default Environment so I'm not sure what I'm missing.

<div type='discussions-op-text'>

<sup>Originally posted by **amaiol01** May  6, 2022</sup>
I have the COE platform installed and have gone through the recommended steps however during the Admin | Sync Template v3 run I am getting the following error:
![image011](https://user-images.githubusercontent.com/105073188/167183243-eeb2d25c-3d7a-4f74-9991-eed6d30bac41.png)

Also getting a long run time:
![image012](https://user-images.githubusercontent.com/105073188/167183700-be32af79-23d6-4c09-a3a2-cfa67085e826.png)

Thoughts on the above?</div>

**Comment by manuelap-msft** [comment]
What version of the Core components solution are you on? I believe this is an issue that we fixed with the April release (#2404)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
