### ISSUE TITLE
[CoE Starter Kit - Feature]: App Environment not included in D4T Power Platform Admin View app

### ISSUE THREAD

**Issue by farmersnz** [microsoft/coe-starter-kit#2767]
### Describe the solution you'd like

In the Power Platform Admin View app (Team Canvas App)
Apps screen
Select the App
On the General tab please include the App Environment for the selected app.

This is available to view under Flows but not Apps.
I have multiple environments (dev, test, prod), the app name is the same so it is not easy to differentiate between them without the environment name.

**Comment by manuelap-msft** [comment]
Hello,

The App Environment is already included here, and if you click on it you get through to the Environment details page which has the ID / Instance URL etc.
![image](https://user-images.githubusercontent.com/55705669/169254317-8ade7d00-1a4e-4c4c-8115-673834ba105f.png)

Manuela

**Comment by farmersnz** [comment]
Hello Manuela,
I am sorry, I did forget to add that I am using the Teams version (Canvas app). The environment id/name is not available on the apps screen but is available on the flows screen. 
Thank you.

**Comment by manuelap-msft** [comment]
Oh, I see! We can look into that, thanks for providing extra detail.

**Comment by manuelap-msft** [comment]
Closing out. Unfortunately as we're a very small team, we can no longer invest in the Core for Teams version of the CoE Starter Kit.
