### ISSUE TITLE
Power Apps COE Audit Log Connector Timeout

### ISSUE THREAD

**Issue by jconnor2209** [microsoft/coe-starter-kit#2768]
Hi,

I have been debugging some issues that I have been having with the Audit log connector recently. I recently upgraded the solution to the latest version of the COE. I followed the instructions to re-setup the Office 365 Management API, and even verified that I received results from the connector via the ListContent operation. 

The connection to our audit logs appear to be active, but for some reason the admin sync log runs (for a long time 1-1.5 hours) and then Fails with the following error below.

_The server did not receive a response from an upstream server. Request tracking id (with long GUID)_

I then looked at the Child Admin Sync Logs, and the following error appears there below. However, what is funny is that the failures seem intermittent until it fails many times in a row which stops the process. It seems this failure keeps occurring, and it seems it cannot parse the output for some reason, but I am a bit lost on what to try next.

Start time
May 18, 03:57 PM (39 minutes ago39 min ago
)
Duration
00:00:22
Error
Action 'Parse_JSON' failed

Image of the Child Flow runs
![image](https://user-images.githubusercontent.com/25256358/169172603-bd117797-456f-409a-9751-8b014299fca1.png)

Any advice you could provide on what to try next would be greatly appreciated. Thank you!

**Comment by Jenefer-Monroe** [comment]
Unfortunately the connections for custom connectors are often lost on upgrade. You should receive emails when this flow fails to the Admin Email address on file so please watch for that in the future.
Here is a write up on how to fix these when you are doing an upgrade: https://github.com/microsoft/coe-starter-kit/issues/1424

**Comment by jconnor2209** [comment]
> Unfortunately the connections for custom connectors are often lost on upgrade. You should receive emails when this flow fails to the Admin Email address on file so please watch for that in the future. Here is a write up on how to fix these when you are doing an upgrade: #1424

Hi Jenefer,

What is weird is I followed those steps already, and everything appears to work. I even tested the ListContent feature in that connector, and it is returning data. As you can see in the screen shot, things work, and then fail about an hour in to running this procedure. Not sure if you have any other thoughts, but I did do those steps already. Thank you!

**Comment by Jenefer-Monroe** [comment]
Can you please let me know

1. What version of Core and Audit Logs are you on? 
2. Are there unmanaged layers on the flows? 
3. Open the child flow in edit mode and copy/paste what is in here for me

![image](https://user-images.githubusercontent.com/89584709/169363863-34201c76-030e-4cb7-853a-a16a1817e6f3.png)

This is what is should be: 
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "UserId": {
                "type": "string"
            },
            "UserKey": {
                "type": [
                    "string",
                    "null"
                ]
            }
        }
    }
}

**Comment by jconnor2209** [comment]
Hi Jenefer,

Thank you for your response. Here is the information you requested. 

What version of Core and Audit Logs are you on?

![image](https://user-images.githubusercontent.com/25256358/169418133-1996da8f-bde2-496e-9759-678e26d0ef40.png)

Are there unmanaged layers on the flows? No, I haven't customized anything that I am aware of.

Open the child flow in edit mode and copy/paste what is in here for me. Seems mine may be more than what you stated.

{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "OrganizationId": {
                "type": "string"
            },
            "RecordType": {
                "type": "integer"
            },
            "ResultStatus": {
                "type": "string"
            },
            "UserKey": {
                "type": "string"
            },
            "UserType": {
                "type": "integer"
            },
            "Version": {
                "type": "integer"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": "string"
            },
            "UserId": {
                "type": "string"
            },
            "CrmOrganizationUniqueName": {
                "type": "string"
            },
            "Fields": {
                "type": "array"
            },
            "InstanceUrl": {
                "type": "string"
            },
            "ItemType": {
                "type": "string"
            },
            "ItemUrl": {
                "type": "string"
            },
            "UserAgent": {
                "type": "string"
            },
            "CorrelationId": {
                "type": "string"
            },
            "EntityId": {
                "type": "string"
            },
            "EntityName": {
                "type": "string"
            },
            "Message": {
                "type": "string"
            },
            "PrimaryFieldValue": {
                "type": "string"
            },
            "Query": {
                "type": "string"
            },
            "QueryResults": {
                "type": "string"
            },
            "ServiceContextId": {
                "type": "string"
            },
            "ServiceContextIdType": {
                "type": "string"
            },
            "ServiceName": {
                "type": "string"
            },
            "SystemUserId": {
                "type": "string"
            },
            "UserUpn": {
                "type": "string"
            },
            "AdditionalInfo": {
                "type": "string"
            },
            "Name": {
                "type": "string"
            }
        }
    }
}

![image](https://user-images.githubusercontent.com/25256358/169418258-41e53ec9-178b-41ba-938d-dd8fb555dea3.png)

I can try swapping out the JSON you stated if that makes sense, but just let me know. Thank you!

**Comment by Jenefer-Monroe** [comment]
I suggest you upgrade the Audit Logs solution as the current one contains this simplified parse as well as some other needed changes due to backend shifts, and some alerting to you when you might not be receiving all the data.

**Comment by jconnor2209** [comment]
Hi Jenefer,

I have attempted to do that, and when upgrading again I got the following error. It seems this upgrade solution is still there. Any thoughts on how to upgrade this? Thank you for all your help!

![image](https://user-images.githubusercontent.com/25256358/169873795-e083a728-f996-470b-a8c9-9f2546659dfe.png)

**Comment by jconnor2209** [comment]
Hi Jenefer,

I had thought this was something to try, but unfortunately I am unable to delete either of the audit log solutions. Please see the screen shots below. Thank you.

When deleting the first Center of Excellence Audit Log Upgrade. I get the following. 

![image](https://user-images.githubusercontent.com/25256358/170343204-9633e106-06f8-4ba1-b5dd-6f0520466871.png)

Then I go into that solution, and can't find the connection it is referencing.

![image](https://user-images.githubusercontent.com/25256358/170343443-70533522-9952-4193-9dbe-efaabdf50b37.png)

Finally, I tried going in to delete the other Audit Log Solution, it says other dependencies exist. However when I try to delete the management API, it is dependent on 4 other items. It seems I am in a bit of a chicken or the egg type of dependency loop.

![image](https://user-images.githubusercontent.com/25256358/170343885-4dd9c010-4fba-4556-81cd-36b1d897987a.png)

I am not sure if you have any suggestions. I have a Premier support team I work with, and if possible I would like to arrange a call, but not sure if that is an option. Thank you for all your help!

James

**Comment by Jenefer-Monroe** [comment]
If you delete the objects in the Audit Logs solution that should fix it too. Delete the child flow, then the parent flow, then see if you can delete the solution. 

You'll have to go to the Default solution to delete objects. 
![image](https://user-images.githubusercontent.com/89584709/170386027-98bbdbb4-3e83-4145-af6e-220dfd6423eb.png)

**Comment by jconnor2209** [comment]
Hi Jenefer,

I was hoping to re-open this case. I have tried your suggestion, and I am unable to delete the Flows in the Default solution as you suggest. As you can see in the screen shot below, the Delete from this environment button is grayed out. Any advice you can provide would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/25256358/173469188-4ac70ed3-d0e1-435f-9108-a2c3b271f556.png)

**Comment by Jenefer-Monroe** [comment]
If you go outside of the context of the solution, to view the flows in the environment, Delete should be offered. Let me know!
![image](https://user-images.githubusercontent.com/89584709/173608777-90cd7803-ad39-450c-9a99-b47f9b0039a1.png)

**Comment by jconnor2209** [comment]
Hi Jenefer,

It is offered, but it seems I cannot delete these since they are a part of a managed solution. The delete option was there, but any other ideas? Thank you.

![image](https://user-images.githubusercontent.com/25256358/173942856-5dfb3f36-64c4-4b10-a36e-e15361222a42.png)

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are not funded to assist with issues like this but I can try one more thing here. 

To reiterate the issue, you somehow have multiple instances of the solution installed and cannot uninstall. 
It sounds like you cannot uninstall because of some connection reference (CDS Current Environment CoE Connection)

Let's try again with edit of the flows instead of delete

Again in default solution > Click on the name of the child flow to bring you to details
Click Edit next to "Owners" > Delete all the Connection References in Use (you will probably see the problematic one listed here)

![image](https://user-images.githubusercontent.com/89584709/173988760-c1e765b1-96fb-429e-a0de-25c82e9551ad.png)
![image](https://user-images.githubusercontent.com/89584709/173988947-00e0d5f5-3b41-4f9f-bd5c-469132549de6.png)
![image](https://user-images.githubusercontent.com/89584709/173989163-30f2a597-deed-4b34-8971-a9bc5cd62420.png)

Do the same thing for the parent flow 

Now try to delete the solution.
