### ISSUE TITLE
How to get data of Analytics from Power Apps 

### ISSUE THREAD

**Issue by nrjngrctrg** [microsoft/coe-starter-kit#2769]
Hi,
I would like to seek your help.
I was trying to preview the analytics of a specific app in PowerApps App
But instead I found the Analytics(Preview) on the Power Platform Admin center using my admin account where all the data shows in general but not in a specific app.

![image](https://user-images.githubusercontent.com/105711121/169193491-3e984001-b5cb-4ff7-852e-a6d5a7dcca16.png)

Can someone help me how or where to get all this data in the e-mail for a specific app. Thank you!

**Comment by manuelap-msft** [comment]
Hello,

this GitHub forum is specific for issues related to the CoE Starter Kit, and not monitored by the Support team for the Power Platform product itself. For issues related to Power Platform, please raise a support ticket: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support

Thank you
Manuela
