### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to retrieve audit log in the past ?

### ISSUE THREAD

**Issue by Ayako-U** [microsoft/coe-starter-kit#2770]
Hello,
After I upgraded CoreComponent, Office 365 Management API connection was failed. I could fix by updating connector, Office 365 Management API.
Due to this failure, Audit log from 5th March to 2nd May are missing. Additionally, from 4th May to 16th May, UPN are not showing because of [the bug](https://github.com/microsoft/coe-starter-kit/issues/2665). 
How can I retrieve Audit log in the past ?
<img width="293" alt="snap3594" src="https://user-images.githubusercontent.com/100763907/169212983-9220c7fb-7228-473e-9b6d-fd4cf9e3e594.png">

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

**Comment by Jenefer-Monroe** [comment]
To get the old audit logs, we do not have a programmatic solution. You will need to manually export them from https://compliance.microsoft.com/auditlogsearch 
![image](https://user-images.githubusercontent.com/89584709/169298423-f93c4c10-6bc6-4cc3-bf52-1afba8260987.png)



And manually import into the dataverse table.
![image](https://user-images.githubusercontent.com/89584709/169298951-fb36c4f1-85c1-4cb8-9597-6b44a2bc5019.png)
