### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cannot upgrade core components version 1.98 to 3.38

### ISSUE THREAD

**Issue by Chunlau99** [microsoft/coe-starter-kit#2772]
### What is your question?

would like to know anyone have a experience facing upgrading issue CoE Starter kit from 1.98 to 3.38 
we got the error code below., would anyone can provide solutions 

Error code
[8004F01D](http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=8004F01D&de=online)
Exception message
Solution dependencies exist, cannot uninstall. DependencyCount : 7 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: f155e36d-31eb-481f-8b20-0d132f4efe4a, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: e3c0ae31-f12d-4883-b956-411cf16da285, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Welcome Policies New Maker, Id: c691aa41-2e54-eb11-a812-000d3ab9bc3d, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: e3c0ae31-f12d-4883-b956-411cf16da285, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Welcome Policies SP List Maintenance, Id: e7ce02a9-2f54-eb11-a812-000d3ab9bc3d, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: 63d051e2-43f9-4a92-a18e-4eff3f631bc9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerPlatformAdminCoEConnection, Id: a104faa4-8324-4b48-8d20-81049d0b6f7c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoEv3SyncTemplatesCDS, Id: 8bab5caf-3df7-4af2-8c3f-9d434a534c67, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoEv3SyncTemplatesCurrent, Id: df324b1f-2f62-4aa7-a6bd-bb4f64301428, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.98

**Comment by Chunlau99** [comment]
Thanks your help and replied, We are successfully installed new version of 3.38 new release, but unable remove uninstall  deleted old version 1.98 Center of Excellence - core components, referring the image below, 

Not sure you can provide documents or step procedure guideline to us manually clean up, we don't have a resources hiring partner to do that. thanks

<img width="943" alt="Untitled" src="https://user-images.githubusercontent.com/75518990/169466085-87d7f3d5-012a-424e-9347-752e45a97eb0.png">

**Comment by Chunlau99** [comment]
We are resolved components dependence issue and manually remove
Finally can uninstall remove old components

**Comment by Jenefer-Monroe** [comment]
Well done! I will go ahead and close this issue then, please return with new issues if you find them. 
Thanks for using CoE!
