### ISSUE TITLE
[CoE Starter Kit - Feature]: "Set app description" action for "Power Apps for Makers" connector

### ISSUE THREAD

**Issue by Pitfrog9191** [microsoft/coe-starter-kit#2773]
### Describe the solution you'd like

I want a new Power Apps for Makers connector action to fill out the App description. 

Right now the user has to go to the app or flow settings to fill out the description. 

But I want that they can do it in their respective application.

**Comment by manuelap-msft** [comment]
Hello,

this GitHub forum is specific for issues related to the CoE Starter Kit, and not monitored by the Support team for the Power Platform product itself. Our team is also a "customer" / end user for these connectors, and we don't own them. We can forward your feedback to the engineering team but I would encourage you to raise this as an idea here: https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas

Thank you
Manuela
