### ISSUE TITLE
[CoE Starter Kit - BUG]: Issue with 'App Last Launched On' field in Admin View

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/coe-starter-kit#2774]
Hi Team,

We are using CoE starter kit flows in our tenant and using the 'Power Platform Admin View' Model Driven App we monitor the Apps and Environments.
Recently based on the data we have in Admin View, we have quarantined some apps from default environment, which were not used (based on the Last Launched Date of the App field). Apparently these apps are being used and somehow the data is not getting updated in the Admin View.

Attached the sample image of the App fields.

![image](https://user-images.githubusercontent.com/33513504/169269870-c21f525e-505a-4434-8761-81ddeecfb3fe.png)

Could you please help here.

Thanks,
Tom

**Comment by LucasCXavier** [comment]
Hello @Jenefer-Monroe, hope you are doing well!

Please see below the required screenshots:
![image](https://user-images.githubusercontent.com/105860879/169584275-ee302b97-d966-4a51-bbb0-c5ac1f7f42e0.png)
![image](https://user-images.githubusercontent.com/105860879/169584399-1baa9a23-90ab-44bb-afb4-cdcd45d817fa.png)
![image](https://user-images.githubusercontent.com/105860879/169584777-d4aaafcf-13f8-4f4b-bd7f-ff0861e639dc.png)

**Comment by Jenefer-Monroe** [comment]
It looks like that connection was just made so perhaps it had been broken and you missed some.
Please look for mails to the admin email telling you that you need to create smaller chunks in the audit logs as well.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Jenefer-Monroe** [comment]
Per your screenshot, the connection was just made when we were investigating
![image](https://user-images.githubusercontent.com/89584709/170306165-5cc1fcc7-dd2c-4bd0-9f2c-9b4b295bf2ff.png)

**Comment by Jenefer-Monroe** [comment]
For chunk size, if you arent getting all the logs you will get a mail with this subject: **_CoE Audit Logs - Missing some logs - require smaller chunks_**
It is sent to the admin email adress set in that environment variable. 
Please look for those and if you see them, do the work in step 11 of [Set up the Power Automate flow](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow)
