### ISSUE TITLE
[CoE Starter Kit - BUG] Include information about fixing custom connector in upgrade documentation

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#2777]
### Describe the issue

Lots of people ask about this. Should have in documentation
Here is what I have been pasting in docs, but should check with ALM guys as I believe they already have something written up.

Unfortunately the connections for custom connectors are often lost on upgrade. You should receive emails when this flow fails to the Admin Email address on file so please watch for that in the future.
Here is a write up on how to fix these when you are doing an upgrade: https://github.com/microsoft/coe-starter-kit/issues/1424

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

documentation

**Comment by DS2019** [comment]
This is still an issue in Feb 2023. Documentation on how to reset this up would be much appreciated!

**Comment by manuelap-msft** [comment]
Closing out as we no longer use the custom connector.
