### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3

### ISSUE THREAD

**Issue by SteveKnowlesWWHA** [microsoft/coe-starter-kit#2778]
### Describe the issue

We have just installed the CoE core components but whenever i go into the apps there is no data.

Looking it says the the flow Admin | Sync Template v3 needs to run to get the data. When i look in Cloud Flows/Flows Shared with me i am unable to locate the flow to run it and have to go into the solution > Click on the flow to display it in Microsoft Flow

Am i doing something wrong or is there something that needs to be amended for me to be able to pull in the data?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
Hello. I am having a little trouble following your situation. 
Have you gone through all the [setup instructions for inventory](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) and turned all the flows on in the order described?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
