### ISSUE TITLE
[ALM Accelerator - BUG]: CustomAzureDevOps.GetProjects failed: The method 'GetProjects' has an invalid value for parameter 'organization'

### ISSUE THREAD

**Issue by veerasekarmeiyappan** [microsoft/coe-starter-kit#2780]
### Describe the issue

1.Imported 'CenterofExcellenceALMAccelerator_1.0.20220517.1_managed'
2.Created custom 'CustomAzureDevOps', tested it worked with 200 response on 'GerOrganisations'
3. Opened the 'ALM Accelerator for Power Platform' app, selected a maker environment
4. It populated one of the available solution, but with this error message at top 'CustomAzureDevOps.GetOrganizations failed: The data returned in the response is invalid. Response data should be a valid JSON object.'

![DevOpsConnectionError](https://user-images.githubusercontent.com/50662144/169347263-aa5085f4-2901-405c-b3a6-d5c363e01414.JPG)
![DevOpsConnecterSuccess](https://user-images.githubusercontent.com/50662144/169348388-e6c58a34-5159-4a4f-b169-05b54481dbe3.jpg)
 

### Expected Behavior

It should populate the organization in 'Create profile page'

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220517.1

### Steps To Reproduce

1.Imported 'CenterofExcellenceALMAccelerator_1.0.20220517.1_managed'
2.Created custom 'CustomAzureDevOps', tested it worked with 200 response on 'GerOrganisations'
3. Opened the 'ALM Accelerator for Power Platform' app, selected a maker environment
4. It populated one of the available solution, but with this error message at top 'CustomAzureDevOps.GetOrganizations failed: The data returned in the response is invalid. Response data should be a valid JSON object.
![DevOpsConnectionError](https://user-images.githubusercontent.com/50662144/169348706-9e7ef0f1-ebaa-43c3-97ab-862afef59696.JPG)
'

**Comment by mikefactorial** [comment]
@veerasekarmeiyappan is it possible that an invalid connection was created between your step 1 and step 2? Did the app prompt you to create a new connection for the custom connector after step 2 and when you opened the canvas app? If it didn't it could be an invalid connection already exists.

**Comment by veerasekarmeiyappan** [comment]
Thanks @mikefactorial it had 2 connections. I uninstalled the solution and deleted all the existing connections and it worked now.
