### ISSUE TITLE
[CoE Starter Kit - BUG] Version discrepancy while upgrading CenterofExcellenceAuditComponents

### ISSUE THREAD

**Issue by ValleRLess** [microsoft/coe-starter-kit#2783]
### Describe the issue

I originally installed the Governance Audit Components on October 2021. I just downloaded the May 2022 components, but when installing the CenterofExcellenceAuditComponents solution, it doesn't allow me to upgrade because it says the new version has an older version number than the older one I installed last year. See the image below.

How can the version from October 2021 be 2.6 and the version in May 2022 be 2.16? How can I go about upgrading to the latest solution?

Thanks.

![image](https://user-images.githubusercontent.com/89102781/169364831-5e9fe410-9da4-4bd2-af52-a2511912557f.png)

### Expected Behavior

While doing the upgrade, the newer solution should have an newer version than the older solution.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.16

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1. Downloaded CenterofExcellenceAuditComponents_2.6_managed.zip on October 6, 2021.
2. Imported all of the CoE solutions including the governance components on October 6, 2021.
3. Configured and the solution is running well.
4. Downloaded CoE Starter Kit May 2022 - Hotfix 1
5. Imported and Upgraded the Core and Audit Logs without any problem.
6. Tried importing and upgrading the May 2022 CenterofExcellenceAuditComponents_2.16_managed.zip but got the error about the version discrepancy described above.

**Comment by Jenefer-Monroe** [comment]
2.16 should be considered larger than 2.6 so this is strange. I will install the old version in a test envt to see

**Comment by Jenefer-Monroe** [comment]
Yes I have confirmed that upgrade from 2.6 to 2.16 works

![Image](https://user-images.githubusercontent.com/89584709/169401415-99858bcb-a3cf-4793-b580-af72a1cd078d.png)



![Image](https://user-images.githubusercontent.com/89584709/169404332-a282adac-bcd7-4e1d-bbfb-5063fc5ce0b0.png)

**Comment by ValleRLess** [comment]
For some reason it was failing on me with an error when I tried to install several times on Wednesday. Yesterday it worked though. Thank you.
