### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Power BI report has failed to refresh.

### ISSUE THREAD

**Issue by bkrotz** [microsoft/coe-starter-kit#2784]
### Describe the issue

Hello,

We just updated our CoE to May release (not the May HotFix). 
Our Power BI Report has failed to refresh.

Failure details: The last refresh attempt failed because of an internal service error. This is usually a transient issue. If you try again later and still see this message, contact support. 
The '<pii>admin_sharedtotal</pii>' column does not exist in the rowset.

### Expected Behavior

Successful refresh the dataset. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Power BI report

**Comment by Jenefer-Monroe** [comment]
A field was changed, you will need to use the new PBI that comes with the May release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by bkrotz** [comment]
The refreshing is working now. Thanks!
