### ISSUE TITLE
Teams_CoEDashboard_March2022 not loading

### ISSUE THREAD

**Issue by S0URCEC0D3** [microsoft/coe-starter-kit#2785]
### Describe the issue

When I try to load the PowerBI teams template I get the below error:
"Microsoft SQL: A connection was successfully established with the server, but then an error occurred during the pre-login handshake (provider: SSL provider, error:0 - The wait operation timed out)"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Core

### Steps To Reproduce

Attempted importing the PowerBI template into PowerBI desktop then I received the error mentioned above.

**Comment by manuelap-msft** [comment]
Please look at our troubleshooting help: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
