### ISSUE TITLE
[CoE Starter Kit - QUESTION] Identity used to install the CoE Starter Kit is adding itself as owner of some flows

### ISSUE THREAD

**Issue by javier-m-g** [microsoft/coe-starter-kit#2788]
### What is your question?

We are receiving, since last Friday, May 13, these kind of emails on a daily basis:

![image](https://user-images.githubusercontent.com/101564333/169516175-e4c546a9-1609-448c-afe4-10a557ba3f25.png)

Any idea what flow is sending these emails and why?

Thank you!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Unknown

**Comment by albertocaa1317** [comment]
Hi @Jenefer-Monroe, I work with @javier-m-g .
But why we have this behavior only in the flows of one environment?
I think that we have this flow enable since older versions and never we haver this behavior.

**Comment by Jenefer-Monroe** [comment]
The work was added for specific connectors (primarily Http to get host name)
So if a flow does not have one of these specific connectors, or if the admin already has permissions, then we do not do this.

**Comment by javier-m-g** [comment]
Understood and confirmed that it is only being applied to flows that have "Http" or "HttpWebhook" actions. Thank you!
