### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by jajp777** [microsoft/coe-starter-kit#2793]
### Describe the issue

Gallery view is not clear. Template padding value is high

### Expected Behavior

Gallery view is not clear. Template padding value is high

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin template

### Steps To Reproduce

Test

### Anything else?

test

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid there is not enough information in this bug to be actionable. 
And you are also on a version of Core that is about a year old so your feedback has likely been address anyway. 
We recommend upgrade every 3 months, please get to current builds.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
