### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to edit theme.

### ISSUE THREAD

**Issue by Arandon** [microsoft/coe-starter-kit#2795]
### Describe the issue

After installing the theming solution I am unable to adjust the colours as the links don't appear.

![Themeing issue](https://user-images.githubusercontent.com/70806759/169546922-693136ae-c0e2-487f-afb4-f8d36f58b99e.png)
 

### Expected Behavior

Was expecting links to adjust colours

### What solution are you experiencing the issue with?

Theming

### What solution version are you using?

2.4

### What app or flow are you having the issue with?

Theme Editor

**Comment by manuelap-msft** [comment]
Hello,

Please make sure  publishing of canvas apps with code components is enabled for your environment:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-theming#prerequisites

We found that this has to be enabled **before** importing the solution, so if you have not enabled this, you may need to uninstall the solution, enable the setting, and then reimport the solution.

Thank you
Manuela

**Comment by Arandon** [comment]
Hi Manuela,

Yes I did install without turning that on initially but reinstalled after realising this.

I've just reinstalled again and it seems to be working, I probably didn't leave it long enough after turning on apps with code before installing.

Thanks for your help :)

**Comment by manuelap-msft** [comment]
Interesting! We've not tested the exact time it takes for the setting to "take" before installing again so it's possible that there's a bit of a delay. That's good to know for us and we can add a tip to the documentation on that!

Thank you, I'll go ahead and close this issue now but please do let us know if you have any issues going forward!

Thank you
Manuela
