### ISSUE TITLE
[CoE Starter Kit - BUG] Apps that are part of a deleted environment are not flagging as Deleted in Power Platform Admin View app

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#2798]
### Describe the issue

I was comparing the Power BI report and the Power Platform Admin view app and noticed there was a discrepancy between the number of Model Driven Apps. The Power BI report showed that there are 319 model driven apps in our tenant and when looking at the All Apps view in the Power Platform Admin View app it shows 338. 

After researching I found that the 19 model driven apps that are not appearing in the Power BI report are actually part of environments that have been deleted.

The screenshot below shows where the app is flagged as not deleted, but there is a deleted on date and time. 

![image](https://user-images.githubusercontent.com/95765970/169593369-38895e6f-f8b9-414c-8f30-b4d76caf5bf0.png)

The screenshot below is the deleted Environment that the app above belongs to. Notice the date and time the environment was deleted.

![image](https://user-images.githubusercontent.com/95765970/169593388-65a0c003-b429-4035-9b6c-b3b968b19629.png)

It appears that the PowerBI report is accurate but the Power Platform Admin View app is not reflecting correctly. I know there is a view on the Power Platform Admin view app that shows Apps with Deleted Environments, but if the apps were deleted with the environment, I am not sure why they would show under all apps view, which are active apps.

My question is shouldn't the objects included in a deleted environment be deleted and the deleted flag say Yes?

### Expected Behavior

When an environment is deleted, the App deleted flag should show as Yes for the app included in it. Unless when an environment is deleted, the actual apps within are not deleted and if this is so, then I need to be able to find where they are located to delete them. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

1. Open **Power Platform Admin View app**
2. Click **PowerApps Apps** in left hand bar
3. On **All Apps** filter by Model Driven App
4. When clicking on an app that is part of a deleted environment review the Deleted flag.

To find the discrepancies I ended up exporting the list from the Power BI report and comparing it to an exported report from Power Platform Admin view app.

**Comment by Jenefer-Monroe** [comment]
The Check Deleted flows did have bugs about a year ago, and it looks like this data is a legacy of that. 

If you mark that environment as not deleted (admin_environmentdeleted = no) and then run **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_**

Might I ask why you are keeping around objects that were deleted in the inventory? If you dont really need those anymore, I can describe to you how to clean that up, which would clean all of this out of the tables as well.

**Comment by AUTigers16** [comment]
Jenefer the issue is that the environment is deleted and shows as so, but the objects within it in the Power Platform Admin view app are flagged as not deleted but have a deleted on date.  The power bi report is reflecting our inventory correctly and does not reflect these deleted objects that were part of the deleted environment.

If you can give me instructions on how to fix this issue with flagging the deleted objects as not deleted I would appreciate it.

**Comment by Jenefer-Monroe** [comment]
Yes you are describing the behavior for a bug we had about a year ago, which is when this environment was deleted. 
The easiest way for you to fix this is to just delete that envt from the inventory (see below) then the clean up flows will delete the objects that were in it when they next run. In particular it is the **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_** flow that will clean it up so feel free to just run it right after you delete the environment from the inventory.

![image](https://user-images.githubusercontent.com/89584709/169867672-29ef78a4-5349-48ad-9b27-66f48412453a.png)

**Comment by AUTigers16** [comment]
Thanks so much Jenefer! Also, I noticed there is a view called Deleted Environments Review. Do you know what criteria is triggered for items to app on this view?

**Comment by AUTigers16** [comment]
The deleted environments are showing up under Deleted Environments Review and not under Active Environments as shown in your screenshot. Before I start deleting is that where I am supposed to be deleting them from? The Deleted Environments Review view? Also, what warrants deleted environments to show up under this view in the app?

**Comment by Jenefer-Monroe** [comment]
You can understand what a view uses for filters by going to the table > views > open the view
![image](https://user-images.githubusercontent.com/89584709/170273726-e4e3f99a-dde1-4818-bd4e-3c25fc95d2ff.png)
In the pane on the right you can see what filters are used
![image](https://user-images.githubusercontent.com/89584709/170273861-ac8855f4-831e-4e42-a743-d5105ecc854d.png)

So in this case its exactly what it sounds like. The Environment Deleted column was set to yes
