### ISSUE TITLE
[CoE Starter Kit - BUG] Quarantine App intermittent issue

### ISSUE THREAD

**Issue by dsm0811** [microsoft/coe-starter-kit#2800]
### Describe the issue

I am using a custom flow that is almost identical to the Governance flow "Admin | Set app quarantine status". I added some things to the emails and had it do additional actions, but the part of the flow that has the error is identical. The Quarantine app flow that is triggered by the Powerapps Apps field called "Quarantine App" changing between yes/no will intermittently fail with the following error:
"error": {
    "code": "NonAdminsCannotSetAppQuarantineState",
    "message": "Only admins can set app quarantine state."

If this error happens in the flow it will also occur when using the CLI version: 
Set-AppAsQuarantined -EnvironmentName $EnvironmentName -AppName $AppName

Other times this will work perfectly fine with the same account, just on different apps.

![QuarantineError](https://user-images.githubusercontent.com/18239530/169609920-071ba3d6-4811-40d7-8076-09893e85c676.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.15

### What app or flow are you having the issue with?

Admin | Set app quarantine status

**Comment by dsm0811** [comment]
Feel free to contact me with any questions. dsm0811@churchofjesuschrist.org

**Comment by Jenefer-Monroe** [comment]
Did you leave this in your new trigger? 
![image](https://user-images.githubusercontent.com/89584709/169615601-a2b0678b-ee72-4d14-9dde-6983ec80a43a.png)

**Comment by dsm0811** [comment]
I found out the hard way that using any other column doesn't work. I do currently have this using the admin_quarantineapp field.

**Comment by manuelap-msft** [comment]
Hello,

does the account you use for the quarantine have permanent Power Platform Admin permissions? Or is the account set up with PIM to only grant admin permission for certain hours?

Thank you
Manuela

**Comment by dsm0811** [comment]
@manuelap-msft Our main Service Representative (Principal Customer Engineer) for our org is wondering if you have opened an ICM that he can follow.

**Comment by miguelverweij** [comment]
How was this resolved? I experience exactly the same issue. I have the same trigger, and also permanent Power Platform administrator permissions.
