### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade failed Upgrading from 2.1.70 to 3.38

### ISSUE THREAD

**Issue by russgove** [microsoft/coe-starter-kit#2802]
### Describe the issue

Upgrading from 2.1.70 to 3.38
after importing solution and upgrading I see both 3.38 and 2.1.70 in the solutions gallery.
![image](https://user-images.githubusercontent.com/2412956/169616017-31913145-4638-497d-8b98-9c69f2a13981.png)
the history on the 2.1.70 shows this:
![image](https://user-images.githubusercontent.com/2412956/169616126-e665c6fe-68f7-4c20-b844-a0271c735fae.png)

When i click on the line in error i get this
![image](https://user-images.githubusercontent.com/2412956/169616232-490dcbcc-f2d6-408c-84f3-2a0397a82dc3.png)

### Expected Behavior

Solution upgrade should work

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Upgrade

### Steps To Reproduce

folwed instruction on web

### Anything else?

none

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help with how to migrate the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
