### ISSUE TITLE
[CoE Starter Kit - Feature]: change to ordering of release information

### ISSUE THREAD

**Issue by loryanstrant** [microsoft/coe-starter-kit#2805]
### Is your feature request related to a problem? Please describe.

The updates to each release are ordered based on descending number, which can make it challenging to consume as the content itself relates to different aspects of the Starter Kit and is a mixture of bugs / new features / improvements, etc.

### Describe the solution you'd like

It would be great if the release notes were grouped based on area of the Starter Kit they relate to, and perhaps further grouped based on type.
Like this for example: 
![image](https://user-images.githubusercontent.com/51473494/169721318-28def71b-30cf-44c1-b33c-9a4cfb2868a7.png)

**Comment by manuelap-msft** [comment]
Thanks for providing feedback! This particular ask we're already tracking under #2170 and it is on our backlog. I'll close this out as duplicate and you can follow #2170 for updates!

Thank you
Manuela
