### ISSUE TITLE
DV4T App Sharing not showing up

### ISSUE THREAD

**Issue by nikolasph** [microsoft/coe-starter-kit#2806]
### What is your question?

Dear all,

we successfully installed the core solution in a DV4T environment. 
Afterwards we wanted to share specific apps with that team. Therefore We followed: https://docs.microsoft.com/en-us/power-platform/guidance/coe/faq#share-an-app-from-a-dataverse-for-teams-environment

For some reason they do not show up in the section “build by your colleagues” in the Power Apps App. The whole section does not exist. 
Our Teams policies are quite strict and maybe there is something in the teams admin center that needs to be enabled?

Anyone an idea?

kind regards
Niko

### What solution are you experiencing the issue with?

core solution teams

### What solution version are you using?

latest hot fix in may

### What app or flow are you having the issue with?

All apps

**Comment by manuelap-msft** [comment]
Hello,

if that section doesn't exist at all, it looks like viewing "Shared Power Apps" is not allowed via your Microsoft Teams app policies. Learn more about them here: https://docs.microsoft.com/en-us/power-platform/guidance/adoption/teams-environment-strategy#use-microsoft-teams-admin-center-controls

I believe it's specifically this app policy that would be disabled for you:
![image](https://user-images.githubusercontent.com/55705669/169813595-df3a9a88-9941-41db-b825-a7e2c5623b82.png)

Thank you
Manuela

**Comment by nikolasph** [comment]
That solved it! Thank you

**Comment by manuelap-msft** [comment]
Wonderful, thank you!
