### ISSUE TITLE
[CoE Starter Kit - BUG] Audit logs flow is not working

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/coe-starter-kit#2809]
### Describe the issue

Hi Team,

We have installed latest COE starter kit in our environment and trying to run Audit log flow. We are getting below errors upon running:

![image](https://user-images.githubusercontent.com/78213183/169819554-a6cf5b00-f5a1-4f18-b540-55cf985d4aeb.png)
![image](https://user-images.githubusercontent.com/78213183/169819643-c24d77dc-9941-4d4f-9e9f-bbf793cd1d9e.png)

When we left tenant ID from above screenshot as blank and re ran the flow, we are getting below error:

![image](https://user-images.githubusercontent.com/78213183/169819749-7c9a6c40-2205-42b1-88ec-8cd74d342c66.png)
![image](https://user-images.githubusercontent.com/78213183/169819946-c0bc2389-4789-40f9-951c-e7cc645f1892.png)

Kindly check on this and do the needful on priority.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
