### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to remove the unmanaged layer

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2810]
### Describe the issue

Hi Team,

I have successfully upgraded the core components with the latest version 3.38 successfully. Also, Audit components has been upgraded successfully. However When I proceed with "AuditLogComponenets" by removing the existing unmanbged layer of "Admin | Sync Audit Logs" flow - I see following errors:

`Failed to find connection references with logical name(s) 'admin_CDSCurrentEnvironmentCoEConnection, admin_CDSCoEAuditConnection'. `

Above connection reference now no more available as they got deleted with the latest core solution upgrade - Would you please share How should I proceed with this? Or Should I delete the flow "Admin | Sync Audit Logs" itself?

Looking forward to hearing from you!

Thanks,

### Expected Behavior

Audit Log component solution's flow should be removed with the unmanaged layer without any error

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.41

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

**Comment by Jenefer-Monroe** [comment]
I've never seen this issue. We store the data for audit logs in core so you can delete the audit logs solution and re-install without losing any information. I believe that would be the best bet here.

**Comment by tomsinsight** [comment]
Perfect, Thank you very much!!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
