### ISSUE TITLE
[ALM Accelerator - BUG]: Connection references

### ISSUE THREAD

**Issue by mknalves** [microsoft/coe-starter-kit#2813]
### Describe the issue

I have a solution with for connection references (Azure DevOps, Azure Monitor, Office 365 and SQL Server). I've set up all of them with the target connections. 
![connected](https://user-images.githubusercontent.com/49026459/169839838-9154fb40-71a3-4048-9049-9d54c0ffc257.png)

I do the deployment on the target environment, and everything works fine, with all connections and workflows activated. 

But, when I open the Configure Deployment Settings with the same user, some connections aren't connected as previously. 

![Unknown_connections](https://user-images.githubusercontent.com/49026459/169851867-4a806a94-4b75-45f8-b848-3fef54ea3972.png)

During my investigation, I realized that the action Get Connections from Power Apps for Markers connection is getting the connection with status Error even with no visual error (Apps, and flows working) on the target environment. 

Here are the samples from the Get Connections action response

SQL Server Connection

![sql_error](https://user-images.githubusercontent.com/49026459/169855437-476fc59b-6ca2-4fd9-9c66-913ebcb93486.png)

DevOps

![visual_studio_teamservice](https://user-images.githubusercontent.com/49026459/169855484-e417d771-8952-436b-bbec-7bba9b46d48c.png)

Azure Monitor

![azure_monitor](https://user-images.githubusercontent.com/49026459/169855543-bb42b0a6-80b3-4e7b-955a-b3c9012a1bf1.png)

### Expected Behavior

When open the Configure Deployment Settings after the deploy finished all the connections should be with status Connected.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

latest

**Comment by mikefactorial** [comment]
@mknalves thanks for reporting this and for the detailed investigation. We'll look into this.

**Comment by mikefactorial** [comment]
@mknalves I know this has been open for quite a while. Is this something that you can confirm is still an issue? I haven't seen this behavior or any other reports of this since this issue was opened

**Comment by mikefactorial** [comment]
Closing this issue out due to inactivity
