### ISSUE TITLE
[CoE Starter Kit - QUESTION] Services that need to be activated with a Microsoft 365 E5 license of CoE Starter Kit install user.

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#2817]
### What is your question?

I know that users installing the CoE Starter Kit must have a Microsoft 365 license.

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with
<img width="455" alt="image" src="https://user-images.githubusercontent.com/70095092/169926820-0c7dda3e-9206-40a7-89ae-3823e632915a.png">

What services do I need to activate in my Microsoft 365 license?
↓Like this.
![image](https://user-images.githubusercontent.com/70095092/169926869-27ad4b45-6964-4973-8eda-3996c795b204.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2022

### What app or flow are you having the issue with?

Install User License

**Comment by Jenefer-Monroe** [comment]
We've only ever tested it with all apps of an M365 license enabled, but our guess would be that the following would be enough as we only use Teams and Outlook:

- Microsoft Teams
- Exchange Online

You can try this out and let us know?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
