### ISSUE TITLE
[CoE Starter Kit - BUG] Dataverse Missing data

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#2822]
### Describe the issue

Hello,

This morning I checked some Model-Driven Apps in the Dataverse tables and I saw that in the table PowerApps Apps the Model-driven applications are not displayed, they are missing. Only Canvas and SharePoint forms are shown.

![image](https://user-images.githubusercontent.com/7468628/169979336-5bb7efa5-47d6-4999-bd90-a44a66391e18.png)

Has something to do with the latest service change done by Microsoft?

How can we solve this?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admi - Sync Template v3

### Steps To Reproduce

Dataverse - > Tables - PowerApps Apps -> filter by Model Driven Apps

**Comment by Jenefer-Monroe** [comment]
Do you have all the flows listed in [inventory set up](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) turned on and running?

In particular, is **_CLEANUP HELPER – Check Deleted (Model Driven Apps)_** turned on, running, and passing?

**Comment by ClaudiuVio** [comment]
![image](https://user-images.githubusercontent.com/7468628/170177208-09a5af6b-5f25-4cf2-8470-3e3985310740.png)

**Comment by ClaudiuVio** [comment]
Guess what , today the Model Driven apps appeared after a ticket to Microsoft. I did nothing and they appeared back.

![image](https://user-images.githubusercontent.com/7468628/170177475-654c13bd-b43c-42da-b9ad-87ba72324cd1.png)

**Comment by Jenefer-Monroe** [comment]
That is odd. But glad to hear it is resolved! Closing out, please raise new issues if you have them though.
