### ISSUE TITLE
[CoE Starter Kit - Feature]: Provide count of users shared with when shared with groups

### ISSUE THREAD

**Issue by russrimm** [microsoft/coe-starter-kit#2835]
### Is your feature request related to a problem? Please describe.

Currently, if an app is shared with a group, it only shows 1 group.  If that group has 5000 members, there is no way to see that the app is widely shared because the toolkit only shows the 1 group vs the # of users in that group.  It would be helpful to see the total number of users the app is shared with even when it's only shared with groups.

### Describe the solution you'd like

When apps are shared with groups, include the total number of users in each group the app is shared with rather than just count the group so there is visibility of the total number of users the app is shared with.

### Describe alternatives you've considered

Creating a stand-alone flow to alert when apps are shared with > n users regardless if it's just users or groups or both that an app is shared with.

**Comment by manuelap-msft** [comment]
That's already available in the Power Platform Admin View. If you select an app > General tab > Shared with panel > if it's a group it tells you the group size:
![image](https://user-images.githubusercontent.com/55705669/170286111-fc77ccb9-7e57-460a-af8a-4d571d0232df.png)

Are you expecting this to show up in other places as well?

**Comment by russrimm** [comment]
No, I guess I'm just having trouble getting it to display anything here just like #2534.  Have run sync and cleanup and helper flows. 
![image](https://user-images.githubusercontent.com/10841574/170302733-52899862-e4bd-414a-b692-0d18d7229493.png)
![image](https://user-images.githubusercontent.com/10841574/170303038-e8a602e9-4cbe-4fc3-bc53-20872bd79f0a.png)

**Comment by Jenefer-Monroe** [comment]
Per that other user, it appears that their build did not have it implemented correctly yet. May build 3.38 should address, what version of Core are you on?

**Comment by russrimm** [comment]
OK there was, for some reason, an unmanaged layer on one.  After removing it, it appears to be updating now, thank you!

**Comment by Jenefer-Monroe** [comment]
Wonderful news, thanks for letting me know! I'll close this out now but please let us know if you need more help in the future
