### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by talljanding** [microsoft/coe-starter-kit#2837]
### What is your question?

I recently setup the COE kit and have it up and running. I understand that it's possible to have the kit provide daily notices for things like when apps are created. Could you provide some direction (or point me to a resource) for this? Notices of app creation are what I'm interested specifically at the moment.

### What solution version are you using?

May 2022

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are not staffed to assist with extensions of the kit. But I can offer a few words of advice. 

First note that the product does not offer any data triggers for objects. In other words, there is no trigger available for "App Created" or the like for other objects. 

You could get notified when apps are added to inventory though, which would just be you adding another flow to your CoE environment and having the trigger be based on that dataverse table. Something like this:

![image](https://user-images.githubusercontent.com/89584709/170305679-96769b47-8c7b-486b-b064-da077a4f5374.png)

I hope that helps and best of luck

**Comment by talljanding** [comment]
That is very helpful advice and I sincerely appreciate it. Thank you :)
