### ISSUE TITLE
[CoE Starter Kit - BUG] Failed Flow Runs: CoE(Center of Excellence) -> Cloud flows -> Admin | Sync Template v3 (Flows)

### ISSUE THREAD

**Issue by sanjuskc** [microsoft/coe-starter-kit#2842]
### Describe the issue

The flow "Admin | Sync Template v3 (Flows)" in CoE Starter Kit does not complete execution. Below is the error step and issue details:
![image](https://user-images.githubusercontent.com/91690081/170471987-da6bed85-4567-4d2a-8c70-3efe655f80eb.png)
<img width="960" alt="CoE-Flows-SyncTemplate-Error" src="https://user-images.githubusercontent.com/91690081/170472343-c628f894-6949-4c2a-a71d-205964918aa2.png">

### Expected Behavior

Inventory sync need to work with App and Flow details to be captured in Dataverse

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.12

### What app or flow are you having the issue with?

Admin - Sync Template v3 (Flows)

**Comment by Jenefer-Monroe** [comment]
I see history of product bugs in this space online. Lets see if we can get you a simple repro for support. 

In your CoE envt, create a new flow
Power Automate Management > List Flows as Admin > Chose one of the environments for which you repro
Do that again but this time with pagination of 500
![image](https://user-images.githubusercontent.com/89584709/170501703-134d41d8-44fd-433a-b632-0d49fd536b83.png)
![image](https://user-images.githubusercontent.com/89584709/170501777-dc6243a0-3be8-49f9-b069-a75c416e4d93.png)

Then again with pagination values of 5000 and 100000 (that later is what the kit uses)

In the end you will have a flow like tihs
![image](https://user-images.githubusercontent.com/89584709/170502136-a6c5d373-6de9-4df0-ae1b-4fa5a04115a6.png)

Run it and see where it fails.

**Comment by Jenefer-Monroe** [comment]
Here is a flow you can use if you prefer to import. You'll just need to select a repro environment.

[paginationtest_20220526135939 (1).zip](https://github.com/microsoft/coe-starter-kit/files/8779515/paginationtest_20220526135939.1.zip)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
