### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flow Action Details) flow keeps canceling and then turning off

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#2850]
### Describe the issue

The Admin | Sync Template v3 (Flow Action Details) flow keeps canceling and then eventually turning itself off. I know this is an optional flow, but my team wants to be able to use this flow. When going to the flow we are getting the following error message  "Your flow was turned off on 5/23/22...because it was running more actions than expected. See screenshot below.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/95765970/170509760-7f0bf157-f997-40f8-8533-dfe5570b003b.png">

I spot checked some of the cancelled runs and am getting different errors. Most are internalservererror.

We had a similar issue in the past TrackingID#2105140040005603

### Expected Behavior

Flow to successfully run.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### Steps To Reproduce

No steps to repeat, flow just keeps canceling.

### Anything else?

<img width="533" alt="image" src="https://user-images.githubusercontent.com/95765970/170510100-f74ecafb-f184-4ab8-847b-cbd25b8e7ae5.png">
<img width="536" alt="image" src="https://user-images.githubusercontent.com/95765970/170510358-058edb14-76a0-4b80-9642-fdb071100c80.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/95765970/170510720-75b096c8-c160-425a-a731-3fcbe68198f8.png">

**Comment by Jenefer-Monroe** [comment]
Now that Pay as you Go: [Set up a pay-as-you-go plan](https://docs.microsoft.com/power-platform/admin/pay-as-you-go-set-up) is live, the throttle exemptions used in the past are no longer offered by the product team. 
Unfortunately, you’ll need to either not use this component of the functionality, buy a pay as you go license for it, or push with your account manager for exemption.
