### ISSUE TITLE
[ALM Accelerator - BUG]: deployment settings not saving for all environments

### ISSUE THREAD

**Issue by J3ffr0y3d** [microsoft/coe-starter-kit#2855]
### Describe the issue

We have 3 environments we deploy to validate, test & production, when we go to ‘configuring deployment settings’ the first environment which comes up is validate, all the values previously set are still visible and correct under each setting. However, when you switch to the next environment ‘test’ the ‘environment variables’ settings are blank all the previous values are gone, every other setting seems to save. The same happens when you go to the next environment config ‘production’.

Note: the environment variables are sharepoint URL’s and Lists.

### Expected Behavior

When you open up ‘configure deployment settings’, all your previous values should already be set on all selected environment configurations.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

May 2022 Hotfix 1

### Steps To Reproduce

1.	Open up Configure Deployment Settings or when committing a solution hit the ‘Prepare’ button.
2.	First Environment 'validate'.
3. Fill in all the values under each section as required.
4.	Select the next environment 'test'.
5.	Fill in all sections as required.
6.	do the same for all other environments to configure.
7.	Save and close.
8.	Go back into Configure Deployment Settings.
9.	The first environment to show up 'validate' keeps all values.
10.	Select the next environment 'test'.
11.	Go into environment variables.
12.	The values have not saved as they show blank values.
13.	Same when selecting the next environment to configure under environment variables.

**Comment by jenschristianschroder** [comment]
Hi @J3ffr0y3d,

Thank you for reporting this. Can you share a bit more details about the environment variable values that you are setting for the Test environment?

I'm wondering if you might have any special characters in the environment values that we need to watch out for.

It would be great if you could share the actual values you are setting. Please replace any private or sensitive information with placeholder values.

**Comment by J3ffr0y3d** [comment]
Hi @jenschristianschroder,

sure, the url values are like this:
https://company.sharepoint.com/sites/abcde-fg-hijklm/PMhhjj

and the list values are just text no special characters or spaces.

**Comment by mikefactorial** [comment]
@J3ffr0y3d it's possible this a bug in the search functionality for sites. Can you verify if you are able to pick the site from the list on initial load or if you are using the filter functionality to find a site that may not come back in the initial list of sites? 
![image](https://user-images.githubusercontent.com/42348035/171473380-63c7baa3-5023-465f-a29a-fcf47e84660a.png)

**Comment by J3ffr0y3d** [comment]
Hi @mikefactorial , I can't pick from the initial lists, I always have to filter searching by the site name, when on the other environments, however I can select from the intial list the first environment "validation" URL , I noticed it seems to save the URL in the initial list.

**Comment by mikefactorial** [comment]
Okay, that makes sense. Sounds like there is a bug here. Will look into a fix for this.

**Comment by mikefactorial** [comment]
Related to #3089

**Comment by mikefactorial** [comment]
This should be resolved in the November release update. Closing out.
