### ISSUE TITLE
[ALM Accelerator - QUESTION]  doesn't match with its name

### ISSUE THREAD

**Issue by joje1234** [microsoft/coe-starter-kit#2859]
### What is your question?

I'm experiencing a problem when trying to export a solution with a model-driven app to our Test environment.

The error message is:
Component files in C:\azp\agent\_work\1\a\QuantusDocUI.zip\CanvasApps for canvas app shi_testappformalgruppadefaultcommandlibrary_6827d doesn't match with its name
SolutionPackager: Exception thrown: System.Exception: Component files in C:\azp\agent\_work\1\a\QuantusDocUI.zip\CanvasApps for canvas app shi_testappformalgruppadefaultcommandlibrary_6827d doesn't match with its name.

The app is a model-driven, however I have added some JS to a custom ribbon button on a table that is used in the App.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

May 30.05.2022

**Comment by jenschristianschroder** [comment]
Hi @joje1234, could you please try the work around mentioned here: https://github.com/microsoft/coe-starter-kit/issues/2293#issuecomment-1076540843 and let us know if that resolves your issue.

Thanks!

**Comment by joje1234** [comment]
It worked! Thank you! :)

**Comment by joje1234** [comment]
> Hi @joje1234, could you please try the work around mentioned here: [#2293 (comment)](https://github.com/microsoft/coe-starter-kit/issues/2293#issuecomment-1076540843) and let us know if that resolves your issue.
> 
> Thanks!

I got a new error when using the workaround: 

Message: CanvasApp import: FAILURE: The solution specified an expected assets file but that file was missing or invalid.Detail: 
<OrganizationServiceFault xmlns:i="[http://www.w3.org/2001/XMLSchema-instance"](http://www.w3.org/2001/XMLSchema-instance%22) xmlns="[http://schemas.microsoft.com/xrm/2011/Contracts">](http://schemas.microsoft.com/xrm/2011/Contracts%22%3E)

I'm not sure it is related, but I would think so.

**Comment by joje1234** [comment]
I tested manually importing the solution and it worked. So I guess this is related to a problem with ALM.

**Comment by joje1234** [comment]
> @joje1234 One point of interest here is that the update in #2293 did fix the issue in the export, but then it failed on import. I wonder if you applied the same change to the tools installer here in the accelerator templates https://github.com/microsoft/coe-alm-accelerator-templates/blob/331d492625c56ae9b784a4e1c5978d76df60a2fe/Pipelines/Templates/build-Solution.yml#L19 if that would make a difference.

Applied the same change to build-solution.yml but got the same error as described in my last post.

**Comment by joje1234** [comment]
> @joje1234 One point of interest here is that the update in #2293 did fix the issue in the export, but then it failed on import. I wonder if you applied the same change to the tools installer here in the accelerator templates https://github.com/microsoft/coe-alm-accelerator-templates/blob/331d492625c56ae9b784a4e1c5978d76df60a2fe/Pipelines/Templates/build-Solution.yml#L19 if that would make a difference.

I applied the same fix to build-solution but got the same error as my previous post.

**Comment by joje1234** [comment]
Do you have any other suggestions/workarounds on this issue? It's kind of critical for us atm.
We can contact microsoft support if you think this is an issue with the tooling.

**Comment by mikefactorial** [comment]
@joje1234 looks like this issue slipped through since my last reply in June. Did you ever find a resolution? Let me know. Feel free to close if it's no longer relevant.

**Comment by mikefactorial** [comment]
Closing this out as there's no more to do here.
