### ISSUE TITLE
[CoE Starter Kit - BUG] Is Teams Install variable is missing in the latest kit - is that true?

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2860]
### Describe the issue

Dear Team,

I have just upgraded the Core 3.38 version successfully and I see that the environment variable  "Is Teams Install"- is that fine? Does it only require if Microsoft Teams being used?

Thanks,

### Expected Behavior

 "Is Teams Install" environment variable should be present in the kit as mentioned in the documentation.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

 "Is Teams Install" Environment Variable

**Comment by manuelap-msft** [comment]
Hello,

we found a better way to retrieve this information, so we deprecated this environment variable. It should not have an impact on your upgrade/install.

Manuela
