### ISSUE TITLE
[CoE Starter Kit - QUESTION] Exclude SharePoint Forms from Compliance Review

### ISSUE THREAD

**Issue by GoerdesM** [microsoft/coe-starter-kit#2861]
### What is your question?

Hi, is there a smart way to automatically exclude all SharePoint Forms from the Compliance Request workflow? If someone just modified the form in SharePoint, we do not need to collect compliance details like Business Case etc.
We can of course deselect all of them manually, but this would mean that as soon as such an app is created, we need to get informed about it and change it manually within the CoE admin settings. Thanks 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Core Components for Teams 3.19.1

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by manuelap-msft** [comment]
Hello,

thanks for raising this! 

If you have a designated environment for SharePoint custom forms (https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#designate-sharepoint-custom-form-environment, recommended) you can exclude the entire environment from the compliance process. 

If not, we currently don't have a process for excluding types of apps - only single apps or entire environments can be excluded. Added this to our backlog for investigation to see if we can do that. Just to set expectations, we won't be able to commit to a date on when we can look into this, as we have quite a big backlog and have to focus on the most impactful things first. 

Thank you
Manuela
