### ISSUE TITLE
[CoE Starter Kit - Bug] admin_connectionreferences outdated

### ISSUE THREAD

**Issue by azhar2501** [microsoft/coe-starter-kit#2863]
### Is your feature request related to a problem? Please describe.

Hello, 

The table admin_connectionreferences is being successfully populated Via the sync flows, however when an app or flow is deleted the connection reference remains active in the table admin_connectionreferences. (no cascading effect either).

 Can you please let me know if it is a bug or a normal behavior?

### Describe the solution you'd like

I would like the admin_connectionreferences table  to be update to date and show real data.
 - Add new record when a connection is created [already implemented]
 - Delete the record when the app/flow/'connection is removed' [not implemented]

**Comment by azhar2501** [comment]
Thank you for this suggestion, it has removed connection for **deleted** app and flow.
Please do you know if it also removes **deleted** connection reference for **existing** app?

**Comment by Jenefer-Monroe** [comment]
No it does not. But the apps sync flow would remove these if the app is edited:
![image](https://user-images.githubusercontent.com/89584709/171866303-474e4904-1917-4386-a5e4-77fa47d1644a.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
