### ISSUE TITLE
[CoE Starter Kit - Feature]: Tracking Solutions

### ISSUE THREAD

**Issue by sciencestudent-Sharon** [microsoft/coe-starter-kit#2864]
### Is your feature request related to a problem? Please describe.

The CoE does a great job of keeping tracking everything in the platform from apps to flows in the Power Platform Admin View app - but would like to also track and keep records of Solutions (managed/unmanaged) that users creating within environments.

### Describe the solution you'd like

An entity/data model/tables for Solutions like existing ones for Power Apps & Flows etc. in the Power Platform Admin View app. 

So, would like a view + form of a table of records for managed & unmanaged Solutions created by users across platform to be visible in Power Platform Admin View app. 

Record details could be similar to existing features (ex. what connections are used, who are the users that have access) but to include what exists in a Solution (ex. what are the apps, flows, tables, custom security roles etc. in this solution)

So, when opening the view for Solutions in PPAV app, would see Display Name of the Solution, Environment that the Solution is in, the Publisher name, Owner, Created On etc. all underneath the same Staging Process/Approval BPF.

### Describe alternatives you've considered

Perhaps a separate model driven app (with the requirements as mentioned in "Describe the solution you'd like") because controls in record details may differ a lot from what is currently in the PPAV app.

### Additional context?

![image](https://user-images.githubusercontent.com/38770482/171064933-f682720b-4476-4aae-8721-e390298a6894.png)
![image](https://user-images.githubusercontent.com/38770482/171065915-cc766fa5-20b0-4274-bcad-955d5a4d4948.png)

**Comment by manuelap-msft** [comment]
Hello,

thanks for the detailed feature ask! It is something we have considered before but not picked up for development. 

Here's why: 

A solution can contain a million different things (apps, flows, tables, connection references, environment variables, plugins, webresources, security roles,...) and whilst technically feasible to pull all this information into the CoE Starter Kit, a solution based on our current architecture (where we sync inventory using cloud flows) would not scale and we'd soon hit throttling issues and timeouts - not to mention the extensive effort to keep this data up to date. 

Can you share how you would use the data and what decisions it would drive? We can explore if there's something we can do that may not involve syncing the entire solution inventory. 

Thank you
Manuela

**Comment by sciencestudent-Sharon** [comment]
That's interesting to know that it would be impacted by throttling issues/timeouts

At the moment, it'd be for visibility & keeping track of bigger projects

If not syncing the entire solution - is it more doable to track what is currently already being tracked? ie. apps, flows, chatbots, custom connectors, and then collecting solution detail info ex. name, version, date etc.

Thanks!
