### ISSUE TITLE
[CoE Starter Kit - BUG] The '<pii>admin_sharedtotal</pii>' column does not exist in the rowset.

### ISSUE THREAD

**Issue by JawnLegend** [microsoft/coe-starter-kit#2865]
### Describe the issue

Getting an error on refresh of CoE dataset. The error occurred when upgrading to may 2022 release. 

### Expected Behavior

Expected for data to be refreshed without errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.3.8

### What app or flow are you having the issue with?

Power Bi

### Steps To Reproduce

Refresh of data.

### Anything else?

![image](https://user-images.githubusercontent.com/105429761/171108543-ccca7caf-00dc-4aac-9c6c-a6ecbf1318da.png)

**Comment by manuelap-msft** [comment]
Hello,

we made some changes to our data model - you will have to use the latest version of the dashboard if you are using the latest version of Core components.

Closing as dupicate of #2784
