### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Desktop Flow - Runs) flow is suspended

### ISSUE THREAD

**Issue by bhavikj65** [microsoft/coe-starter-kit#2868]
### Describe the issue

Admin | Sync Template v3 (Desktop Flow - Runs) flow was suspended because it has been failing every time. When we checked the flow it was identified that it fails because of following error 

"message": "admin_RPA With Id = *******-****-****-****-********** Does Not Exist"

 in "Update RPA session record" action

![image](https://user-images.githubusercontent.com/105588534/171111511-34ec0b5c-c57c-4792-b00b-4ab4ffde9add.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop Flow - Runs)

**Comment by Jenefer-Monroe** [comment]
Can you please go to ensure this flow is turned on, running, and passing?  **_Admin | Sync Template v3 (Desktop flows)_**

**Comment by bhavikj65** [comment]
Yes, Admin | Sync Template v3 (Desktop flows) is turned on and running.
![image](https://user-images.githubusercontent.com/105588534/171196417-c585bcae-4e46-4729-8941-df045e18042b.png)

**Comment by bhavikj65** [comment]
Admin | Sync Template v3 (Desktop flows) is running, I checked already the RPA ID reported in error and it doesn't exist in **Desktop flow** table.

**Comment by Jenefer-Monroe** [comment]
I think that means that an instance of the Desktop Flows sync flow must be failing. 
Is this failing for all flows or just a few? 
Is it failing for a particular environment? 
Can you see if the flow exists in the inventory but under a different GUID?

**Comment by Jenefer-Monroe** [comment]
Concur, its frustrating that this fix has taken so long. We are blocked by the product feature though.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
please track the work via #2102
