### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Connection

### ISSUE THREAD

**Issue by NikoAppSphere** [microsoft/coe-starter-kit#2869]
### Describe the issue

Hello,

we deployed the core components and try to setup the Power BI report.
Unfortunately when we try to connect using the account which we installed the coe kit with but Power BI always responds with an error "you are not signed in". 
Do you have an idea why this is happening?  
Is this maybe the proxy issue that is described here: https://docs.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-powerbi-connector?tabs=Dataverse#prerequisites

TDS is activated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Power BI

**Comment by Jenefer-Monroe** [comment]
I'm afraid you have hit a product issue with Power Bi, not an issue with the kit. If the [troubleshooting](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#troubleshooting) from our documentation does not help you may need to reach out to product support.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
