### ISSUE TITLE
Clarify required permissions on Service Connections

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#287]
**Is your feature request related to a problem? Please describe.**
It is not clear which Service Connection roles are required in order for user to read via Custom ADO connector

**Describe the solution you'd like**
Add note to SETUPGUIDE.md that users of AA4AM app will need User or Administrator role on Service Connection in AzDO in order to see and select an environment in the AA4AM app

**Comment by jenschristianschroder** [comment]
Still a few places to be updated with required permission
Also need screen shot to be updated to reflect changes

@mikefactorial, can you help with the screen shot? I don't have required permission to do it my self

It is this screen shot that needs updating to show that User role is required (.attachments/GETTINGSTARTED/image-20210401093313321.png)
![image](https://user-images.githubusercontent.com/24893229/117447275-91dd5700-af3d-11eb-9103-c59384516f2b.png)

**Comment by mikefactorial** [comment]
Merged to v-next. Closing
