### ISSUE TITLE
[CoE Starter Kit - QUESTION] Trigger full inventory of seperate inventory flows

### ISSUE THREAD

**Issue by cr0max** [microsoft/coe-starter-kit#2873]
### What is your question?

Thank you for your previous help with https://github.com/microsoft/coe-starter-kit/issues/2674.

Our CoE flows are doing ok now (still some minor errors, reported as separate bug reports). However, we are still missing alot of inventory. Because the Full Inventory won't work in our tenant with our current licensing model of Power Platform, because the account will get throttled. And I do not see why we should license the CoE account with expensive licenses for a one-off inventory not even knowing if it will work either.

So my question is, if it possible to activate a full inventory of a single flow? Is it possible to do so, editing the flow manually?
![image](https://user-images.githubusercontent.com/97740538/171172129-a3d8e852-23ae-4cf4-88bb-a8c98938ef0c.png)
Then we could choose what inventory flow to select during a given time and possibly avoiding the throttling?

Would that be an option?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2022 v3.38

**Comment by cr0max** [comment]
Thank you for the tip, I'll give that a try.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
