### ISSUE TITLE
[CoE Starter Kit - BUG] Monthly active usage not being calculated

### ISSUE THREAD

**Issue by redleo85** [microsoft/coe-starter-kit#2878]
### Describe the issue

8 days ago we installed the Audit Logs (version 2.9) in our tenant to track app usage. Audit logs have successfully been collected and launch dates added to the app database. 

But the Monthly Active Usage has not been calculated. It is 0 for all apps, also those which have been launched multiple times during the last week. I already had a look at the system jobs to check when the rollup job ran last and it was today, but still no update to the MAU data.

### Expected Behavior

Monthly Active Usage data is updated after Audit Logs have been enabled.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

None

### Steps To Reproduce

1. Install audit logs components
2. Wait for a couple of days
3. Check Monthly Active Usage in PowerApps Apps table

**Comment by Jenefer-Monroe** [comment]
There was a product change around the beginning of May that made the user UPN not show up. We had to reship May's audit log solution as 2.9 to fix. While I see you have 2.9, you likely have unmanaged layers on the flows which prevents you from seeing the fix.

Please see https://github.com/microsoft/coe-starter-kit/issues/2665
![image](https://user-images.githubusercontent.com/89584709/171252757-b1f02152-1181-4ae4-9103-18d829c04071.png)

Please let us know.

**Comment by redleo85** [comment]
Hi @Jenefer-Monroe ,
thanks for the reply. The User UPN is not the issue. It is correctly populated in our database (see screenshot).
![image](https://user-images.githubusercontent.com/9613325/171362931-8a8dd506-f6f8-453e-bf74-9efa267152dc.png)

Our issue is the Monthly Active Usage metric within the PowerApps App table. In the following screenshot you can see that the Monthly Active Usage field is 0 for all apps (1), although they have been launched yesterday (3) and the roll up column was calculated today (2).
![image](https://user-images.githubusercontent.com/9613325/171363954-ad5360c2-bf3d-4f8b-812d-f1101d50a745.png)

**Comment by manuelap-msft** [comment]
It looks like we have an issue in the formula for the Monthly Active Usage (calculated field). We'll investigate that!

**Comment by manuelap-msft** [comment]
I'm not quite sure how to do this. The rollup field doesn't seem to support advanced date calculations (like "in the last month"). We are not using this rollup in our reporting either, so closing out as the field is not used by the CoE kit.
