### ISSUE TITLE
Unable to connect to CoE Kit environment with new PBI dashboard

### ISSUE THREAD

**Issue by Papa-Cho** [microsoft/coe-starter-kit#2888]
Hello,
I've followed the indications in #2784 and on Ms site to deploy the new PBI. But in PBI desktop I cannot sign in to the environment hosting the CoE data while I have system admin permission there.
I've tried with the account used for updating the CoE kit to May 22 release. Still same error message
I keep getting this error
![image](https://user-images.githubusercontent.com/92913718/171369149-7199ac6e-d018-44cf-b795-7fab32766f40.png)
Do you know how to fix this?

_Originally posted by @Papa-Cho in https://github.com/microsoft/coe-starter-kit/issues/2784#issuecomment-1143335959_

**Comment by manuelap-msft** [comment]
Your URL is missing an s - you have to preface the URL with http**s**://, not http.

**Comment by Jenefer-Monroe** [comment]
Unfortunately that is a PBI issue. Likely due to having multiple identities stuck in PBI. 
If you dont use our PBIT and just try to connect to dataverse from scratch you will see the same issue.
I'm afraid this is a PBI issue and not something our team can address.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Papa-Cho** [comment]
HEllo
Looks like indeed I have an issue with the Dataverse connector in Power BI. I've opened a ticket in the Power Bi community for support
Thank you for your kind support here
Regards,

**Comment by manuelap-msft** [comment]
Hello,

I'm not sure if that will help but I sometimes had this issue when connecting to data sources with different accounts / for different tenants and was able to solve this via:

File > Options and Settings > Data source settings
![image](https://user-images.githubusercontent.com/55705669/172601942-2e52d58f-0164-4fa5-a7d0-c960bc5e2b3c.png)

And then editing the permissions for my data source here or clearing all permissions to force a reset
![image](https://user-images.githubusercontent.com/55705669/172602098-985c6220-cde1-4059-9554-381aa2617f54.png)

Maybe you can try that as well!

**Comment by Papa-Cho** [comment]
Thank you for the tip. I've tried it without success unfortunately. I'll see what the PBI community provides
