### ISSUE TITLE
[CoE Starter Kit - Feature]: Include link to Teams adaptive card and metrics in Orphaned objects email

### ISSUE THREAD

**Issue by AnchalBerwal** [microsoft/coe-starter-kit#2889]
### Is your feature request related to a problem? Please describe.

Hi team,

Right now when our users receive the email, they don't know what to do next? What is the outcome of this email?

The only option they have is to take action in Power platform which is again not very obvious. 

### Describe the solution you'd like

Can we include the link to Teams adaptive card and metrics in Orphaned objects email to guide users more to what do next?

Following things will assist users in a better manner as to what do next?

1. **Teams adaptive card**: Email sent to manager for orphaned objects should include a link to adaptive card that's valid till the flow runs the next time
3. **App/Flow metrics** : It will help them understand the urgency and assist them in making right decision, for example, if we have an app which was launched 6 months ago, manager can go ahead and delete the app

### Describe alternatives you've considered

For now we are trying to customize the flow to add both these details. If we are not able to achieve to get the adaptive card, then we will suggest user to respond to the next adaptive card.

**Comment by AnchalBerwal** [comment]
@MrRamius Please share an approach here

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are not staffed to assist with customizations of the kit. I will leave this open for a bit to see if the community has an answer for you though.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
