### ISSUE TITLE
[CoE Starter Kit - BUG] Set App/Flow Permissions Errors

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2890]
### Describe the issue

Hi Team,

In Core 3.38, "Set Flow Permissions" app, the "Orphaned Flow" tab, does not seems to be working as expected, on the click of that tab, it keeps throwing following messages:

PowerAutomateforAdmins.GetAdminFlowOwnerRole failed: { "error": { "code": "FlowNotFound", "message": "Could not find flow 'XXXXXXX'." } }

On the other hand, it shows flows who already have owner assigned and exist. Similarly, can you please share how "Orphaned apps" are listed? As I see that there is an owner exist for the app, however the same app is being listed as an Orphaned app.

Would you please share how this tab works in both the apps and how it can be helpful for admin?

Thanks,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Set Flow Permission

**Comment by Jenefer-Monroe** [comment]
Hello. Note that the state of being deleted or an orphan are current as of the last clean up run for each. 

Can you confirm that you have all the flows in the [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) running and passing? 
In particular here ensure these flows are turned on, running and passing:
- CLEANUP HELPER – Check Deleted (Canvas Apps)
- CLEANUP HELPER – Check Deleted (Cloud Flows)
- CLEANUP - Admin | Sync Template v3 (Check Deleted)
- CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

Orphan objects are ones who's owner no longer resolves in the O365 users connector.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
