### ISSUE TITLE
[CoE Starter Kit - QUESTION] How can I configure CustomAzureDevOps custom connector?

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2894]
Hello, How can I configure CustomAzureDevOps custom connector?

### What solution are you experiencing the issue with?

Governance

**Comment by Jenefer-Monroe** [comment]
Hello I dont really follow your question. Is this for the ALM Accelerator features?

**Comment by JackSocini** [comment]
Yes of course

**Comment by mikefactorial** [comment]
closing out as no further action for starter kit team
