### ISSUE TITLE
[CoE Starter Kit - QUESTION] View All Environments

### ISSUE THREAD

**Issue by SteveKnowlesWWHA** [microsoft/coe-starter-kit#2902]
### What is your question?

Hi All

I have installed the COE starter kit into a new environment and have turned on all flows in order as required and run successfully. The Admin Sync flow has run but when i check i can only see the environment it is installed in and none of the others

Is there something i need to amend to be able to view all other environments and apps/flows?

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
The kit only gathers information about the envts to which you have admin access. The Power Platform Admin Role, permanently assigned, is required to fetch information about the tenant as a whole. Please see [What identity should I install the CoE Starter Kit with?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role? Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)
