### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (PVA) Admin | Sync Template v3 (PVA) fails

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#2903]
### Describe the issue

Flow `Admin | Sync Template v3 (PVA) Admin | Sync Template v3 (PVA)` fails in 2 of my environments:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/15800069/171577766-0edf0df7-78dc-481d-bd9f-44fd6b6dd63c.png">

The reason is still the same:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/15800069/171577632-fcf19f29-87c5-451a-b225-967c7dca84ec.png">

Environment details:
![image](https://user-images.githubusercontent.com/15800069/171578194-37c02eec-fd7b-4d79-b64d-4d4ec23418b0.png)
<img width="663" alt="image" src="https://user-images.githubusercontent.com/15800069/171578057-54a288d3-966e-4bb4-b04d-4570f5c99ed8.png">

Error Message:
```
InvalidTemplate. Unable to process template language expressions in action 'GetBotID' inputs at line '0' and column '0': 'The template language expression 'first(body('List_bot_for_a_botcomponent')?['value'])['botid']' cannot be evaluated because property 'botid' cannot be selected. Please see https://aka.ms/logicexpressions for usage details.'.
```

### Expected Behavior

😉 flow runs without an issue

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA) Admin | Sync Template v3 (PVA)

**Comment by megel** [comment]
I'm a little bit confused, because there is **no unmanaged** layer:

<img width="799" alt="image" src="https://user-images.githubusercontent.com/15800069/172053121-213925ef-dfa8-4fea-81f4-1cbebfb6d8f7.png">

However, I guess the log in the flow shows this:
![image](https://user-images.githubusercontent.com/15800069/172053369-bd9ec926-96b2-4c21-9533-7019e562b173.png)

But the editor this:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/15800069/172053576-31175438-6b11-4074-a5a9-19ff824dae4c.png">

Do you have any idea?

**Comment by Jenefer-Monroe** [comment]
In you first picture you did not have this condition and now you do
![image](https://user-images.githubusercontent.com/89584709/172061138-38d3cef9-5141-42d0-b541-5bdc7244c4eb.png)

If you rerun the failure it will go down this new path and not fail.

**Comment by Jenefer-Monroe** [comment]
I dont quite follow the situation to be honest. 
You had an unmanaged layer there before, as we can see from the condition being missing. Any run that happened then would look like this. 
Now that you have removed the unmanaged layers, future runs should work. 
Let me know if you think I've misunderstood.

**Comment by megel** [comment]
@Jenefer-Monroe I found the issue - sorry, there was a second CoE installed in a different environment 😬 which I forgot... 

There is no issue on June release. I was my fault.
