### ISSUE TITLE
[CoE Starter Kit - QUESTION] Duplicated Apps in context of established ALM

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#2907]
### What is your question?

The new Governance Dashboard have an interesting view **Apps with duplicated names**:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/15800069/171593754-bd85f459-a6ce-4008-8a02-871842b20d3b.png">

The result of the drill through in my environments is:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/15800069/171593653-39da620f-8176-4839-ba5e-5d0881ff9acd.png">

In my opinion, environments should have also a **purpose** in context of established ALM-process like:
* DEV
* VAL
* TEST
* PROD
... and except duplicity of Apps & Flows, because this is natural.

Does it make sense @manuelap-msft & @mikefactorial?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

**Comment by Jenefer-Monroe** [comment]
Assigning for investigation. Thanks for posting

**Comment by manuelap-msft** [comment]
We're already tracking this for investigation here #2630. Closing as duplicate
