### ISSUE TITLE
[CoE Starter Kit - BUG] Wrong values in table "PowerApps App", column "App Deleted On"

### ISSUE THREAD

**Issue by javier-m-g** [microsoft/coe-starter-kit#2908]
### Describe the issue

We have 7 apps that have never been deleted, but have a date in the "App Deleted On" column.

![image](https://user-images.githubusercontent.com/101564333/171606833-d99cd4aa-732a-42cc-87f6-5341b41caf24.png)

Casually, all 7 applications are model-driven type.

Surprisingly, one of them is the "Power Platform Admin View" from the CoE Starter Kit, of which I can assure that it is alive and kicking, and has never been eliminated.

The problem seems to be related to some flow, because of those suspicious coincidences in deletion dates (April 16 12:XX PM and May 6, 10:XX).

Any idea?

Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Table "PowerApps App"

### Anything else?

Seems to be related to issues [#2775](https://github.com/microsoft/coe-starter-kit/issues/2775) and [#2798](https://github.com/microsoft/coe-starter-kit/issues/2798).

**Comment by Jenefer-Monroe** [comment]
We had a bug where we were flagging these as deleted in the past. It is resolved in your version of Core which seems to match the last date marked as deleted. You will just need to go clear out that date manually.

**Comment by javier-m-g** [comment]
Understood, thank you. Closing issue.
