### ISSUE TITLE
[CoE Starter Kit - BUG] Can we copy whole CoE Starter Kit as unmanaged solution?

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2910]
### Describe the issue

Hi Team,

I just had a question on the upgrade stratagy, I have June 2021 version of CoE starter Kit Installed and I am upgrading/extending it with the latest one - I was wondering if you could provide guidance whether I can do as follows in the Development Environment:

**Dev Environment:**
1. Upgrade CoE Starter Kit May 2022 solutions
2. Copy all components of the CoE Starter Kit May 2022 (Managed) in to new extended solutions (Unmanaged)
3. Ensure all components from the CoE Starter Kit May 2022 solutions has been copied into the new extended solutions (Unmanaged)
4. Delete Upgrade CoE Starter Kit May 2022 solutions (Managed) keep only extended solutions (Unmanaged)

**Test/Production Environment:**
Deploy managed version of all CoE SK Components
 
Is above process advisable? or we should keep  both the version of CoE Starter Kit - the Managed version by Microsoft and Unmanaged version containing only the extended components?

Looking forward to hearing from you!

Thanks,

### Expected Behavior

Dev environment should have only single version of CoE SK as extended components' are being duplicated as "managed" and "unmanaged"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

All solutions

**Comment by Jenefer-Monroe** [comment]
Hello we just posted this document on how to [Extend and customize CoE Starter Kit components](https://docs.microsoft.com/power-platform/guidance/coe/modify-components). 
Can you please take a look and let us know what questions you have after reading? 
Thanks!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
