### ISSUE TITLE
[ALM Accelerator - BUG]: Con ref for Cust Connector

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#2911]
### Describe the issue

We have a flow that calls a cust connector (the cust connector is an API from APIM story for another time why we are not calling the cust connector from the app directly), but we are seeing issues when its trying to activate that particualr flow. It does seem to recognize the references.

![image](https://user-images.githubusercontent.com/12697408/171665122-1705e0ea-8e3b-4a03-b15d-72bfa2a9ce21.png)

Was hoping June would fix this as we upgraded this morning :(

##[warning]Flow could not be activated. Continuing with flow activation until no more flows can be activated. If this is a result of a child flow not being activated before it's parent consider ordering your flows to avoid this message.
************ FaultException`1 - SetState : Setting Activity State in CRM... workflow |=> Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".
Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}". => Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".[TerminalFailure] Failed to Execute Command - SetState : RequestID=85509acd-9066-4725-8762-00c094cf016c : Setting Activity State in CRM... workflow duration=00:00:01.9230399 ExceptionMessage = Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".
Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}". => Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".
Activating Flow:  CS-AgentAssist-SendLRSEmailRequest-Flow
Activating Flow:  CS-AgentAssist-GetOutage-Flow
##[warning]Flow could not be activated. Continuing with flow activation until no more flows can be activated. If this is a result of a child flow not being activated before it's parent consider ordering your flows to avoid this message.
************ FaultException`1 - SetState : Setting Activity State in CRM... workflow |=> Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".
Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}". => Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".[TerminalFailure] Failed to Execute Command - SetState : RequestID=efc2f6da-f140-4f42-bd75-6c8472826b8d : Setting Activity State in CRM... workflow duration=00:00:01.3775015 ExceptionMessage = Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".
Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}". => Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '7e244ec5-5844-465a-9ee1-7063c9a7e789'. Connection '/providers/Microsoft.PowerApps/apis/shared_new-5fweboutagebffapiaatest-5f21902973afff52cc/connections/4a7deaf45e014a1897b64447a5bd1785' to 'shared_new-5fweboutagebffapiaatest-5f21902973afff52cc' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".
##[warning]Errors occurred while activating flows. Please review the log for specific errors and verify your deployment configuration settings.
##[error]PowerShell exited with code '1'.

![image](https://user-images.githubusercontent.com/12697408/171665588-65cd00eb-fd96-4567-b2c2-e8763c1eab34.png)

### Expected Behavior

Activate the low

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

June

### Steps To Reproduce

Call a cust connector from a flow

AB#1219

**Comment by jenschristianschroder** [comment]
Hi @gerald560,

Thanks for reporting this! Can you please let us now if the owner of the connection is the same that is used to activate the flow or has the connection been shared with the user who is configured to activate the flow?

**Comment by gerald560** [comment]
Yep the owner is the same is the same as activating and the connection is share with the entire org.

**Comment by gerald560** [comment]
this appears to be solved with July upgrade.

**Comment by mikefactorial** [comment]
Great news. Thanks @gerald560 for reporting back!
