### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE BUSINESS PROCESS FLOW-model driven app

### ISSUE THREAD

**Issue by mp1295** [microsoft/coe-starter-kit#2915]
### Describe the issue

Hi guys,

I have small problem and I need a help. I can't see my business process flow that are part of Power Platform Admin View model driven app in Core solution. I published it. Please help, if you have any idea what is going on. I can't see this part, shown in the image below. Thank you.
Update: I checked, all the process flow is on, and put requested in filed and I import core solution from june month, but still I can't see the toolbar in the picture below. Please help.
![bpf](https://user-images.githubusercontent.com/106756335/171799551-6d0417f0-3d77-48b7-aa8b-f3f8e498b9d3.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
This is a business process flow. Can you please check a few things for me

1) Please select a test app that you dont mind triggering the process on
![image](https://user-images.githubusercontent.com/89584709/171862218-aaa8cfa5-cfd2-4c77-b65f-0f9ca4b478f2.png)

2) And request the assessment
![image](https://user-images.githubusercontent.com/89584709/171862563-46d4cb33-5bec-4c9f-9934-bb25a6a4487a.png)

3) Go to the Processes in the solution and make sure they are turned on
![image](https://user-images.githubusercontent.com/89584709/171862873-2f57de77-e928-40ca-8904-55cb8983f8b7.png)

**Comment by mp1295** [comment]
I did everything that you describe, but I don't see the toolbar that you have in your picture.. Do you think is everything ok with the flow process?

**Comment by mp1295** [comment]
Yea, so we find solution. :D You need to click on Process in the upper toolbar. However, thank you :)
![bpf_process](https://user-images.githubusercontent.com/106756335/172157556-dc14d4c3-44fa-41a3-baba-c5b4ce439151.png)
