### ISSUE TITLE
[CoE Starter Kit - BUG] Your audit logs were collected but some were missed due to truncated results in this run

### ISSUE THREAD

**Issue by apoorvakasbekar** [microsoft/coe-starter-kit#2920]
### Describe the issue

Your audit logs were collected but some were missed due to truncated results in this run. 
You will need to use a smaller interval to gather all logs. 
Current chunking size: 1 Minute 
See the optional Step 11 of our Audt Log flow setup documentation for more details. 

TimeInterval-Interval : **1**
TimeInterval-Unit: **Minute**
TimeSegments-CountLimit: **4900**

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Admin | Sync Logs

**Comment by manuelap-msft** [comment]
Hello,

we have some sample configurations for the TimeInterval listed here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

If even the smallest chunk size does not work for you, I'm afraid the audit log solution does not scale to your requirements (this can happen for large tenants with a lot of user activity). You will have to get your Power Apps launch events from a different source instead, see: https://docs.microsoft.com/en-us/power-platform/admin/self-service-analytics 

We currently don't have the CoE starter kit ready to works with the data from this self-serve analytics data export - although, this is on our backlog we are unable to provide an estimate on when we'll be live with it. In the meantime you may have to work with a partner to re-configure the audit log solution to work with data from the data export instead.

Hope that helps
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
