### ISSUE TITLE
[CoE Starter Kit - BUG] Command center| Maker

### ISSUE THREAD

**Issue by mp1295** [microsoft/coe-starter-kit#2921]
### Describe the issue

Hi guys,

I have a little problem, can you help me please. I turn on flows for Maker Command center, but when I click on part Apps, I don't see any app, I can see only Power Platform News and Learn part. What you thing what is problem?
![commandcentar](https://user-images.githubusercontent.com/106756335/172119193-71e39624-64bb-4cc3-85ef-1754e331b142.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Command Center App

**Comment by manuelap-msft** [comment]
Hello,

you need to configure what apps you want visible in the Maker - Command Center using the Admin - Command Center

1. Open the Admin - Command Center
2. Select Edit Bookmarks
3. Select a bookmark and select if the bookmark should be shown in the Admin or Maker Command Center (or both):
![image](https://user-images.githubusercontent.com/55705669/172143055-b03a9d3d-2775-44fa-9cc1-4597dc367157.png)

**Comment by mp1295** [comment]
> Hello,
> 
> not all apps in the CoE kit are relevant to makers, and you may also have additional resources that are relevant for makers that you want to add. We therefore don't show anything by default in the Maker Command Center. You need to configure what apps you want visible in the Maker - Command Center using the Admin - Command Center
> 
> 1. Open the Admin - Command Center
> 2. Select Edit Bookmarks
> 3. Select a bookmark and select if the bookmark should be shown in the Admin or Maker Command Center (or both):
>    ![image](https://user-images.githubusercontent.com/55705669/172143055-b03a9d3d-2775-44fa-9cc1-4597dc367157.png)
> 
> You can also add new bookmarks, for example to a Yammer community, SharePoint wiki etc h

**Comment by mp1295** [comment]
It works now, thank you very much.

**Comment by manuelap-msft** [comment]
Great, thanks for confirming!
