### ISSUE TITLE
[CoE Starter Kit - Feature]: Add Azure Secret Env Var for Audit Logs

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#2926]
### Is your feature request related to a problem? Please describe.

Add env variable to make upgrade easier for those customers with Azure Secret capability
https://powerautomate.microsoft.com/en-us/blog/environment-variables-in-custom-connectors/

### Describe the solution you'd like

Add env variable to make upgrade easier for those customers with Azure Secret capability
https://powerautomate.microsoft.com/en-us/blog/environment-variables-in-custom-connectors/

AB#1214

**Comment by manuelap-msft** [comment]
No longer needed, as we don't use the custom connector anymore.
