### ISSUE TITLE
Sync Template V3 [Desktop Flows]

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#2927]
### Describe the issue

Flow fails in step List rows for table workflows for my default environment with the following error:
Http request failed as there is an error: 'Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'.
I have about 300 rows in the table. Flow succeeds in all other environments, only failing for the default. 

Could you help me solve this? I tried re-submitting and still get the same error. 

### Expected Behavior

The flow succeeds and brings RPA flow information. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.8

### What app or flow are you having the issue with?

Admin- Sync Template V3 [Desktop Flows]

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid you have hit a product limitation which blocks the kit from correctly inventorying your desktop flows
Please see https://github.com/microsoft/coe-starter-kit/issues/2102 for details, and track it for updates. 
We are awaiting a product change and will fix this once available.

**Comment by LizethRegules** [comment]
Thank you
