### ISSUE TITLE
[CoE Starter Kit - Env Request - Bug] DLP Editor - Editing a policy only brings back connectors from the time it was saved

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2933]
### Describe the issue

A policy is saved with the definition "at the time" of saving it, so all connectors are classified in either business, non business or blocked. New connectors are automatically added to the Default group in the system. however the List DLP policies action of the Power Platform admin connector (which we use in the DLP Editor) only brings back the connectors that were available at the time the policy was saved. New connectors are not returned, thus can't be classified if the policy is edited in the DLP Editor.

### Expected Behavior

We need to do a delta analysis of new connectors and add them to the default bucket of the policy in the DLP editor. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

latest

### What app or flow are you having the issue with?

DLP Editor v2

**Comment by denisem-msft** [comment]
We will need to update the connector to accommodate this - there are several operations that need to bring back the correct connectors so we can sync those in Dataverse and send the objects back correctly in the API
