### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor Analysis - Desktop Flows

### ISSUE THREAD

**Issue by Mark-Goodwin84** [microsoft/coe-starter-kit#2939]
### Describe the issue

When running the DLP Editor Analysis (And Export to CSV Flow) after making a policy change the Analysis section does not show Desktop flows that will be impacted by the change. This can lead to flows being suspended that the admin would not be aware off by there change

### Expected Behavior

For the Analysis section (And CSV export) to show impacted Desktop flows that will be effected by the policy change

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.11 Core for Teams

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

1. Run DLP Editor
2. Make Potential change to a Policy that will effect a Desktop flow connector
3. Allow the Analysis section to complete 
4. No Desktop flows are shown

**Comment by manuelap-msft** [comment]
Hello,

currently, the DLP editor can only do impact analysis for cloud flows and canvas apps. I've marked this as a feature request to extend the DLP editor to handle desktop flows as well, and we'll investigate that as part of our backlog.

Thank you
Manuela

**Comment by manuelap-msft** [comment]
PS: One of my colleagues developed a CLI tool for DLP impact analysis for Desktop Flows, you can check it out here: https://github.com/rpapostolis/rpa-cli

**Comment by Jenefer-Monroe** [comment]
Posted also a bug for documentation
https://github.com/microsoft/coe-starter-kit/issues/2943

**Comment by manuelap-msft** [comment]
The Automation Kit offers DLP Impact Analysis for desktop flows
https://learn.microsoft.com/en-us/power-automate/guidance/automation-kit/dlp-impact-analysis

The kit specifically targets Desktop Flow / Hyper-Automation scenarios. Due to complexities regarding impact analysis, we'll have to leave this as separate tools and kits and won't invest here for the CoE kit itself.
