### ISSUE TITLE
[ALM Accelerator - Feature]: portal / pages deployment 

### ISSUE THREAD

**Issue by BradleyFestraets** [microsoft/coe-starter-kit#2940]
### Is your feature request related to a problem? Please describe.

It would be nice to have the new portal cli incorporated into the alm accelerator. 

### Describe the solution you'd like

The ability to download a portal site to the repo and to deploy it to another environment.

**Comment by devkeydet** [comment]
This is already on the backlog.  Closing as duplicate.  Please encourage others to provide feedback on the issue below and vote it up.  It is not currently prioritized for July and not one of the things we are currently looking at for August, but we welcome feedback to help us prioritize.  This is simply a matter of capacity and other issues being prioritized based on customer feedback.  We would also welcome contributions.
https://github.com/microsoft/coe-starter-kit/issues/163
