### ISSUE TITLE
[ALM Accelerator - QUESTION] manually trigger deployment 

### ISSUE THREAD

**Issue by BradleyFestraets** [microsoft/coe-starter-kit#2941]
### What is your question?

Hi team,

We are supporting many environments in our sdlc. 
I'd like to ask if there is any documentation or guidance regarding configuration for setting up pipelines that are manually triggered.

I am aware that we can edit the trigger on the yaml pipelines to none, but I was wondering what the setup would look like for the alm accelerator admin app, under the deployment steps.
I've seen the approval field, which has pr, environment and none. However none still has a trigger associated when the new pipelines are created and approval type does not seem to be the correct description. 

Thanks in advance for your response. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

May 2022

**Comment by jenschristianschroder** [comment]
Hi @BradleyFestraets,

For now we really only support Pull Request as the value for the approval field in the Admin app as the current implementation of the pipeline are defaulted to trigger on changes to a specific branch.

As you mention, the way to set pipelines to run manually requires changes to the trigger, or, changes on the Triggers tab (edit pipelione -> click Triggers in the context menu in upper right corner) to disable the YAML triggers
![image](https://user-images.githubusercontent.com/24893229/173513648-95b588da-d393-4b5c-9103-f001de0e1911.png)

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here. We have plans to provide a bring your own templates feature where users can build their own templates to achieve this requirement that the pipelines responsible for creating the deployment pipelines would use the user specified template instead of our OOB templates.
