### ISSUE TITLE
[ALM Accelerator - BUG]: build-deploy-validation-SampleSolution.yml is not triggered

### ISSUE THREAD

**Issue by VeerasekarVM** [microsoft/coe-starter-kit#2942]
### Describe the issue

1. I configured 'Commit' in ALM App which works fine
2. Now trying to deploy the solution into my Validation environment
3. In ALM Accelerator clicked 'DEPLOY SOLUTION', selected the 'Advanced Settings' and selected the required 'Source Branch'(FirstSolution) and 'Target Branch'(main) and clicked 'DEPLOY SOLUTION'
4.  The DevOps process started and clicked the blue processing icon
5. which navigated to DevOps PR page where i can see 'Set auto-complete', i clicked on it 
6. But can see then its stuck as '1 required' check not yet run'
![1](https://user-images.githubusercontent.com/61466876/172609376-f7244f60-41a1-4bbf-8a44-b665a80745c8.JPG)
![2](https://user-images.githubusercontent.com/61466876/172609390-1805496b-b21a-470b-8422-2262753cec22.JPG)
![3](https://user-images.githubusercontent.com/61466876/172609414-aa6ce637-1849-4366-a3b9-753995ea0870.JPG)
![4](https://user-images.githubusercontent.com/61466876/172609430-e58af9db-7db4-46f5-93d3-0ae13745b8a9.JPG)
![5](https://user-images.githubusercontent.com/61466876/172609620-aca2a005-302c-470d-a17c-565377d74aba.JPG)

### Expected Behavior

1. The PR merge needs to complete
2. the solution should be deployed to Validation environment

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220517.1

### Steps To Reproduce

1. I configured 'Commit' in ALM App which works fine
2. Now trying to deploy the solution into my Validation environment
3. In ALM Accelerator clicked 'DEPLOY SOLUTION', selected the 'Advanced Settings' and selected the required 'Source Branch'(FirstSolution) and 'Target Branch'(main) and clicked 'DEPLOY SOLUTION'
4.  The DevOps process started and clicked the blue processing icon
5. which navigated to DevOps PR page where i can see 'Set auto-complete', i clicked on it 
6. But can see then its stuck as '1 required' check not yet run'

### Anything else?

In Dev Ops i have set branch policy to main branch(default branch)
I have the template files in a separate project and this solution in a separate project

**Comment by jenschristianschroder** [comment]
Hi @VeerasekarVM,

Can you check that the deploy-validation pipeline has the necessary permissions on the ressources required to run?

If you queue the deploy-validation pipeline and click through to the pipeline run you should see if it requires any permissions on required resources.
