### ISSUE TITLE
[CoE Starter Kit - BUG] Another PBI Troubleshooting tip

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#2946]
### Describe the issue

Per https://github.com/microsoft/coe-starter-kit/issues/2888

### Expected Behavior

Add Manuela's tip to PBI Troubleshooting documentation
File > Options and Settings > Data source settings
![image](https://user-images.githubusercontent.com/55705669/172601942-2e52d58f-0164-4fa5-a7d0-c960bc5e2b3c.png)

And then editing the permissions for my data source here or clearing all permissions to force a reset
![image](https://user-images.githubusercontent.com/55705669/172602098-985c6220-cde1-4059-9554-381aa2617f54.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

documentation

**Comment by Jenefer-Monroe** [comment]
added to documentation for July

**Comment by JulesCam** [comment]
Very quick question - I am in the same scenario whereby I have to create install four COE Power BI dashboards across four different tenants, using four different logins. If I clear all the permissions from all my connections each time I need to establish a new connection in a different tenant, does that have any impact on the published power bi reports and sematic models or will that still remain and refresh as scheduled?
