### ISSUE TITLE
[CoE Starter Kit - Feature]: Automated daily backups of  busines critical apps/flowsincluding data sources  to a sharepoint site  for example

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2947]
### Is your feature request related to a problem? Please describe.

Auomated daily backups of  busines critical apps/flowsincluding data sources  to a sharepoint site  for example

### Describe the solution you'd like

Auomated daily backups of  busines critical apps/flowsincluding data sources  to a sharepoint site  for example

**Comment by Jenefer-Monroe** [comment]
I believe this would be a feature for the ALM accelerator team.

**Comment by manuelap-msft** [comment]
I think this would be addressed by the automatic environment back up https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments so we will not invest here. This does back up data in Dataverse, but of course not data outside the platform.
