### ISSUE TITLE
[CoE Starter Kit - Feature]: A report on users not using their license at all in any  form - so we can target this audience

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#2948]
### Is your feature request related to a problem? Please describe.

A report on users not using their license at all in any  form - so we can target this aurdience

### Describe the solution you'd like

A report on users not using their license at all in any  form - so we can target this aurdience

AB#1217

**Comment by Jenefer-Monroe** [comment]
We could do a report on users that do and do not use Premium connectors. But we do not have information about their current license type. 
This is the one that I've heard lately from customers

**Comment by Jenefer-Monroe** [comment]
There's a graph api to get license details [List licenseDetails - Microsoft Graph v1.0 | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=http). 

- it's one call per user so would add a lot of calls
- returns all license types (ex office sku)

**Comment by manuelap-msft** [comment]
waiting for license data to be available from the product. License Reporting is also rolling out into PPAC so need to then evaluate if this is still needed.

**Comment by manuelap-msft** [comment]
Closing out tasks where there is no product backlog to provide this information via API. Plus, license reporting like this is now available in the Power Platform Admin Center as well.
