### ISSUE TITLE
Build Validation does not run

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#295]
**Describe the bug**
When I do a pull request it does not do the validation and not sure what is causing the issue to not do validation. I have attached images below. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/117331074-5f136000-ae64-11eb-82d4-e145f19a2264.png)

![image](https://user-images.githubusercontent.com/75992078/117330815-1360b680-ae64-11eb-88ce-bcada3e5393e.png)

**Additional context**

**Comment by mikefactorial** [comment]
@AkashPatel136 there are a couple of things to check here. 
1. Are you able to run the build manually from Pipelines?
2. If so, verify that there are changes made to the files under the Path you've specified in your Branch Policy. The build will only run if there are changes to files under that directory.

**Comment by AkashPatel136** [comment]
Hi @mikefactorial 

When I try to run the build-AutomationRequest pipeline it throws the error message.
![image](https://user-images.githubusercontent.com/75992078/117336615-6b022080-ae6a-11eb-8e91-be918d7b0212.png)

**Comment by mikefactorial** [comment]
Okay, looks like you didn't update one of the values in the pipeline. Specifically, this 
![image](https://user-images.githubusercontent.com/42348035/117337070-eb288600-ae6a-11eb-93aa-a7704b926abc.png)

Happy to get on a call tomorrow. I'm working to get the next release out this afternoon.

**Comment by mikefactorial** [comment]
In most cases you can just replace BranchContainingTheBuildTemplates with the default branch of the repo that has the build templates assuming your pipeline templates are in the default branch

**Comment by AkashPatel136** [comment]
Hi @mikefactorial 

If you can let me know your time and timezone I can certainly set up some time with you to discuss.

**Comment by mikefactorial** [comment]
Closing this issue per our meeting last week. Feel free to open a new issue/discussion for any questions going forward.
