### ISSUE TITLE
CoE Starter Kit - Microsoft Teams environment governance

### ISSUE THREAD

**Issue by MarinaHadzi** [microsoft/coe-starter-kit#2960]
### What is your question?

Hi everyone, question about Microsoft Teams Admin  | Weekly Clean Up of Microsoft Teams environments. This will clean up environment where request for business justification is sent but not received in 7 days. What about the environments that are active and used and dont have business justification because the other flow only send request for newly created env and not for all active env? Thank you 

### What solution version are you using?

2.17

### What app or flow are you having the issue with?

Microsoft Teams Admin  | Weekly Clean Up of Microsoft Teams environments.

**Comment by Jenefer-Monroe** [comment]
You are so welcome. I will go ahead and close then but feel free to open more bugs in the future as needed.
