### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#2963]
### Describe the issue

In the section of "App Risk Assessment" I can see some apps details without name of Environment and owner which is recently created you can see attached screen shot

### Expected Behavior

App Environment name should be visible in each App 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19 May 2022

### What app or flow are you having the issue with?

App Risk Assessment

**Comment by Jenefer-Monroe** [comment]
Be sure too that all the [inventory flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) are turned on, running and passing. 
In particular I would imagine that some of the clean up ones may not be running

- CLEANUP - Admin | Sync Template v3 (Check Deleted)
- CLEANUP - Admin | Sync Template v3 (Connection Status)
- CLEANUP - Admin | Sync Template v3 (Delete Bad Data)
- CLEANUP - Admin | Sync Template v3 (Orphaned Makers)
- CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

**Comment by sharmajitendralal** [comment]
App Risk Assessment Issue:
![apprisk](https://user-images.githubusercontent.com/30046543/172990165-a11864d2-c724-4a3e-8a19-4db89cf30dfc.jpg)

All Inventory follow turned on and running:
![Sync](https://user-images.githubusercontent.com/30046543/172990574-9013a160-3fa5-4185-bc0f-cf14e9377946.JPG)

**Comment by Jenefer-Monroe** [comment]
We delete apps without environments from inventory. So this should not be happening. 

Please check for unmanaged layers on this flow **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_**
![image](https://user-images.githubusercontent.com/89584709/173100209-bf2b69ea-2d50-47b5-a890-b76ab29329f5.png)

If one exists, delete it and re-run that flow. 

Then please go to the details page of this flow: **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_**
And show us the successful runs
![image](https://user-images.githubusercontent.com/89584709/173099910-0a3f93df-d016-49a0-8402-435fbc8c8eca.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
