### ISSUE TITLE
[CoE Starter Kit - BUG] Unmanaged Layer Removal Process during Upgrade

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2969]
### Describe the issue

Hi Team,

I just had a quick question, when we plan to upgrade the CoE Starter kit, the removal of unmanaged layer is only applicable to "Cloud Flows and Canvas Apps" OR all the components? Should I remove the unmanaged layer for the model driven app for example?

Looking forward to hearing from you!

Thanks,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Power Platform Admin View App

**Comment by Jenefer-Monroe** [comment]
The primary concern for us is the Canvas Apps and Cloud Flows as those can create unmanaged layers sometimes without you even knowing. 
If you make changes to the MDA explicitly then you would want to either extend the kit as described in [Extend and customize CoE Starter Kit components](https://docs.microsoft.com/power-platform/guidance/coe/modify-components), or remove those unmanaged layers when you upgrade. 
I hope that helps

**Comment by tech-steph** [comment]
Our team is also interested in this clarification. We customized the Power Platform Admin View model driven application, adding an additional area in the sitemap and customizing the forms and business process flow. Guidance states that form customization is merge capable. What is the best practice for upgrading this solution when we undergo COE Upgrades?

**Comment by Jenefer-Monroe** [comment]
Best practice is described here:  [Extend and customize CoE Starter Kit components](https://docs.microsoft.com/power-platform/guidance/coe/modify-components)

Some elements are mergable and others arent. I believe you are correct that forms are mergable.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
