### ISSUE TITLE
[ALM Accelerator - Feature]: Support for D365 Queue records

### ISSUE THREAD

**Issue by BradleyFestraets** [microsoft/coe-starter-kit#2970]
### Is your feature request related to a problem? Please describe.

We are using queue's in our solutions and need the queue records to be the same on all environments, otherwise the workflow dont map correctly and error.

### Describe the solution you'd like

To be able to provide queue settings (Id and Email) via the solution configuration settings so that we can have a common Guid accross the environments, but also be able to dynamically set the email address.

### Describe alternatives you've considered

Cutom code using the Xrm SDK's

### Additional context?

For example:

                Guid queueId = new Guid("E8483702-E687-E911-A85F-000D3A6A0A5E");
                string Email = "";
                switch (CrmSvc.ConnectedOrgFriendlyName)
                {
                    case OrgFriendlyNames.development:
                        Email = "development@contoso.com";
                        break;
                    case OrgFriendlyNames.validation:
                        Email = "validation@contoso.com";
                        break;
                .... 

                bool QueueExists = CheckQueueExists(queueId , CrmSvc, context);
                if (!QueueExists )
                {
                    CreateQueue(queueId  , Email, CrmSvc);
                }

**Comment by jenschristianschroder** [comment]
Hi @BradleyFestraets, thank you for suggesting this feature.

We will evaluate your suggestion and prioritize accordingly.

For now, you should be able to use the Configuration Migration tool to export you configuration data from dev. Then upload the configuration data to your git repo. The file should be stored in [Repo]\[SolutionName]\config\ConfigurationMigrationData.
You can add a file for all environments by naming the file ConfigurationMigrationData.zip or environment specific by naming the file ConfigurationMigrationData-[EnvironmentName].zip
