### ISSUE TITLE
[CoE Starter Kit - QUESTION] upgrading extended kits

### ISSUE THREAD

**Issue by EstifanosTsigereda** [microsoft/coe-starter-kit#2972]
### What is your question?

Hi,  currently planning to do an upgrade to CoE to the latest version, we have Dev, Test and production environment.
And would like to know the best practices suggested by microsoft to proceed with this process.....

we thought of this two possible ways but not sure if it is the suggested way: 
1) upgrade Dev , test and production separately one by one

2) upgrade Dev , clone to test as unmanaged do the necessary configuration and clone again to production as managed....( not sure if we could face loss of data in production with this option).

waiting for your response and thanks for your support in advance !

### What solution version are you using?

Release of May

**Comment by Jenefer-Monroe** [comment]
Please see our new document on [extending the starter kit](https://docs.microsoft.com/power-platform/guidance/coe/modify-components) and [updating the starter kit](https://docs.microsoft.com/power-platform/guidance/coe/after-setup) and let us know what types of information you think would still be useful.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
