### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE : Power Platform Admin connector throws Exception

### ISSUE THREAD

**Issue by KishoreJagan83** [microsoft/coe-starter-kit#2977]
### Describe the issue

Trying to customize the Env Request | Create Approved Environment flow for automating the Role privilege's to the maker's  who initiate the request . Hence we customize this logic in child flow and calling in the parent flow 
 Used  Edit AdminEnvironmentRoleAssignment connector  for Assigning the role but it throws  error.

**_Error from token exchange: Permission denied due to missing connection ACL: Connection https://europe-002.azure-apim.net/@europe-002/logicflows/b7780637-8b45-bac5-68d1-24302c0c646b version -9223372036854775808, connection=europe-002/powerplatformforadmins/shared-powerplatform-2cdbf6b5-ecad-4ebf-afb0-0dbb62e23100_**

Not sure why this exception is throwing , tried to remove the existing connection reference, and create new Action and connector , but still issue persist.

We implement this Role Assign logic in a child flow.
![image](https://user-images.githubusercontent.com/43986892/173190016-c04154e1-8d8d-4088-ab7b-818e88afa23e.png)

### Expected Behavior

Edit AdminEnvironmentRoleAssignment connector should not throw error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Env Request | Create Approved Environment 

### Steps To Reproduce

NA

**Comment by manuelap-msft** [comment]
Hello,

I'm afraid we can not help with troubleshooting exensions and customizations to the CoE Starter Kit, as we're a very small team. If you experience issues with a product capability, please raise a Support ticket through official support channels: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support

Thank you for using the CoE Starter Kit,
Manuela
