### ISSUE TITLE
[CoE Starter Kit - BUG] Microsoft Temas environments data missing from Admin View app and Power BI report

### ISSUE THREAD

**Issue by csadev** [microsoft/coe-starter-kit#2980]
### Describe the issue

The data related to existing dataverse for teams environments is not being displayed at the Power Platform Admin View app and Power BI CoE report.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20.6

### What app or flow are you having the issue with?

Admin - Sync Template v3

**Comment by Jenefer-Monroe** [comment]
Hello. The kit only gathers information about the envts to which you have admin access. The Power Platform Admin Role, permanently assigned, is required to fetch information about the tenant as a whole. Please see [What identity should I install the CoE Starter Kit with?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role? Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by csadev** [comment]
The service account has Power Platform administrator role managed through Azure PIM:
![image](https://user-images.githubusercontent.com/27213797/174880916-d88c1095-98e4-4cbe-b5af-6567103336b0.png)
Does it work the same way?

**Comment by Jenefer-Monroe** [comment]
We cannot support accounts licensed or permissioned via PIM due to the flows being triggered at various times, via various mechanisms, or various lengths of time. 
Please see our [limitaitons documentation](https://docs.microsoft.com/power-platform/guidance/coe/limitations#pim-privileged-identity-management)
