### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Variable "Flow Approvals URL" and "Cleanup Old Objects App URL" seems to be not mentioned in the documents

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#2984]
### Describe the issue

Hi Team,

Would you please help clarify the values for Environment Variables "Flow Approvals URL" and "Cleanup Old Objects App URL" and what is the purpose of these two variables?

Thanks,

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.17

### What app or flow are you having the issue with?

Environment Variables

**Comment by manuelap-msft** [comment]
Please see our documentation here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#configure-mandatory-environment-variables

Thank you
Manuela
