### ISSUE TITLE
[CoE Starter Kit - BUG] Envirnment creation data doesn't match

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#2985]
### Describe the issue

Hello, why the two higilight data not match? Thanks

![Inkedtest_LI](https://user-images.githubusercontent.com/101250592/173374033-8011bc7d-d624-446e-92df-9efdf619abff.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.36

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
All objects have 2 "created" dates. 
One marks the date the objects was inventoried (Created On)
The other marks the date the object was created in the tenant (example: Environment Created On)

**Comment by JackSocini** [comment]
With 'objects', you mean the environment?

**Comment by Jenefer-Monroe** [comment]
Correct. In this case object = environment. 
I put it that way because this is the case for all objects. So you will also see two "create" dates for apps, flows, etc. 
Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
