### ISSUE TITLE
[CoE Starter Kit - BUG] Missing Column Data in Teams_CoEDashboard_May2022.pbit

### ISSUE THREAD

**Issue by HMJ-Somerset** [microsoft/coe-starter-kit#2987]
### Describe the issue

June CoE starter kit in D4T environment Teams_CoEDashboard_May2022.pbit

open the pbit and prompted to enter org URL
The load then fails with the following error:
![image](https://user-images.githubusercontent.com/106976858/173384736-00614e84-d5cb-4903-a962-9410defdfa8f.png)

when investigating the error further it occurs Connectors table at the step:  Removed Columns 1.  
This causes the App connection reference and Flow Connection Reference tables to fail to load as well.

### Expected Behavior

The initial data load completes and the file can be saved as .pbix file

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Teams_CoEDashboard_May2022.pbit

### Steps To Reproduce

1. Open .pbit file
2. Enter Org URL 
3. When prompted connect
4. Error on data load

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of you the solutions you have installed in your CoE environment? 
You can do this by going to https://flow.microsoft.com/ > Select your CoE Environment > Solutions
Be sure to expand all the columns so that we can see all the fields shown here

![image](https://user-images.githubusercontent.com/89584709/173955416-3db80d51-ff7d-4fa2-8f30-9c07a4f2a8a4.png)

**Comment by HMJ-Somerset** [comment]
Hi Jenefer

As requested a screenshot of the solutions installed in the CoE Admin Teams environment...
I created the CoE Governance - Customised Flows solution to put any flow that I copied and customised.

***@***.***

Thanks, Hazel

Hazel Jordan
Systems Analyst / Designer - ICT Service
Somerset County Council
+441823 355270
***@***.******@***.***> |  www.somerset.gov.uk<http://www.somerset.gov.uk/>

**Comment by HMJ-Somerset** [comment]
![image](https://user-images.githubusercontent.com/106976858/174251086-fa35beb7-64e8-47c8-8c5b-6d6e4319b059.png)

**Comment by Jenefer-Monroe** [comment]
Can you please expand that second column (Name), I ask because I dont repro so I want to make sure there isnt something wrong with the install. Name is the logical name and sometimes shows issues.

**Comment by HMJ-Somerset** [comment]
![image](https://user-images.githubusercontent.com/106976858/174326857-e0f55ca8-d2be-4600-9f53-119c468a2b91.png)

**Comment by Jenefer-Monroe** [comment]
I do not repro this unfortunately. You may need to remove that manually on your side, and then hopefully this will not repro in the upcoming release for you.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
