### ISSUE TITLE
Experiencing Error Upgrading CoECoreComponentsTeams solution from Oct 2021 to June 2022

### ISSUE THREAD

**Issue by michaelgottwals** [microsoft/coe-starter-kit#2990]
I currently have CoECoreComponentsTeams solution from Oct 2021 version 3.2 installed in a Teams site and was trying to upgrade to June 2022 version 3.19.1 (apparently versioning changed since Oct 2021) and the import fails with the error listed below. It appears as part of the upgrade it tries to uninstall the previous version which has one of the flows listed as a dependency so it fails. Not sure if I am doing something wrong or if there is a bug here, but any guidance would be appreciated. I have attached a couple of screenshots related to the import error as well as the import log file.

**Error Message:**
[CenterofExcellenceCoreComponentsTeams_3_19_1_managed.zip_import.txt](https://github.com/microsoft/coe-starter-kit/files/8893675/CenterofExcellenceCoreComponentsTeams_3_19_1_managed.zip_import.txt)

<img width="851" alt="Starter Kit Teams Core Components Solution Import Failure" src="https://user-images.githubusercontent.com/79226165/173424036-40be239e-14c8-429b-bb97-69de9ed12563.png">

Solution "CenterofExcellenceCoreComponentsTeams_3_19_1_managed.zip" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerPlatformAdminCoEConnection, Id: 966cf55d-b92d-40ed-a64c-f0ada21030b2, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObject
<img width="862" alt="Solution Import History" src="https://user-images.githubusercontent.com/79226165/173423386-81017b60-9842-4f09-9437-a2bc0a268312.png">
Name: , ParentId: 00000000-0000-0000-0000-000000000000

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help with how to migrate the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment.

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Sorry we cannot be of more assistance here.

**Comment by michaelgottwals** [comment]
Thank you for your reply. I did not realize it was critical to upgrade every 3 months. I have not done anything special here other than install the core components Teams edition back in June of last year, then upgraded in October with no issues and now tried the latest version. I originally enabled the flows according to the documentation and setup the Power Platform Admin dashboard Power BI report. Maybe you can explain how these upgrades work in general? I assume the methodology of the solution changed drastically since October. One thought that comes to mind is can I simulate an upgrade path as if I had done it sooner by trying to upgrade to say Jan 2022 version against the current version I have first? Let me know your thoughts on that approach. 

I can also try what you stated by deleting the connection reference in the applicable flow, but wanted to see what your thoughts were on my idea first. If none of these ideas work, then i guess I would lose all of the information that the solution has been gathering about my Power Platform tenant since last year, is that correct?

**Comment by Jenefer-Monroe** [comment]
I cannot comment on if you will succeed with step wise upgrade. We did a giant re-architecture with some new product features that left upgrade very painful at some point in the past, and we walked people through it at that time but can no longer do that now due to cost. 

Here is our documentation on [how to upgrade](https://docs.microsoft.com/power-platform/guidance/coe/after-setup)

If all you are using us for is inventory, then you can start from scratch and the work will all refill, nothing lost. 
If you are using us for inventory including audit logs, then we do have a solution for you there as well which you can read about in  [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

Is this the case?

**Comment by Jenefer-Monroe** [comment]
No you cannot use the audit logs in Teams, you will not be able to gather usage data when deploying there. 
And correct, only the Teams_CoEDashboard is available there.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
