### ISSUE TITLE
[CoE Starter Kit - QUESTION] Change the archive scores

### ISSUE THREAD

**Issue by S0URCEC0D3** [microsoft/coe-starter-kit#2992]
### What is your question?

I would like to change the archive scores, but I'm not sure how they are being created and where they are stored. Can someone please point me in the right direction? 

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

No issues

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
