### ISSUE TITLE
[CoE Starter Kit - BUG] After changing URL address for Environment - CoE fails

### ISSUE THREAD

**Issue by TokeJacobsen** [microsoft/coe-starter-kit#2994]
### Describe the issue

After changing the name of our designated CoE-environment (from the original name, to a more telling one) the Admin | Sync Template v3-flow now fails.

In the first scope (titled: "Get Environments and some tenant wide properties") the activity 'List Makers' fails with the following error:
"UnresolvableHostName. Http request failed with status code 'NameResolutionFailure' and status message: 'The remote name could not be resolved: '[Old-name].crm4.dynamics.com''. "

Where are we missing a change? I can't see the hostname as an input parameter anywhere. 

### Expected Behavior

We would expect the flow to run as intended - as they did before changing the url of the Enviroment. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.60

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

1. Changed the URL of the environment (https://admin.powerplatform.microsoft.com/environments)
2. Ran the 'Admin | Sync Template v3'-flow
3. The flow now fail

### Anything else?

![test](https://user-images.githubusercontent.com/26569867/173594334-d69db902-01dc-4a90-9a4b-a669c8be570a.png)

**Comment by Jenefer-Monroe** [comment]
I don't repro this. Can you clarify when you say you changed the envt name, you mean this? 
![image](https://user-images.githubusercontent.com/89584709/173646848-6080a039-2231-4f64-999f-0f231131a4a2.png)

Can you try to turn the flow off and back on? Perhaps the connector has cached the old url?

**Comment by TokeJacobsen** [comment]
> 

You were correct and turning it on and off really did the job! Thank you so much for the assistance!

**Comment by Jenefer-Monroe** [comment]
wonderful. Thank you for letting me know!

**Comment by westerdaled** [comment]
We had a similar issue.  My colleague Zoe found that just be turning the flow off and back on again, the flow  can locate the environment url it is running in. So no more blank BI reports for AI usage!

![Image](https://github.com/user-attachments/assets/2359c32a-c484-4d66-8ed2-921dcf5063ba)
