### ISSUE TITLE
[CoE Starter Kit - QUESTION] "App connections" always in english (i.e. not localized)?

### ISSUE THREAD

**Issue by MSFT-klpinhac** [microsoft/coe-starter-kit#2996]
### What is your question?

In the "Admin View", there is a column "App Connections"  for PowerApps  -
and the "App Connections" are listed in the language of the user (which may not be english) ( please see screenshot )
Therefore it might be hard for an administrator to understand what connections a PowerApp is using, if the administrator and the user don't speak the same language.
So, is it possible to display the values of the "App Connections"-column always in english?
<img width="807" alt="Screenshot 2022-06-08 140207a" src="https://user-images.githubusercontent.com/84438062/173794937-ccde7393-c3ab-4efa-b03f-febfa7b91cbe.png">

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
Unfortunately we just collect the data that the product returns. 
@manuelap-msft , have you seen this before? I believe this will break our DLP story, can you comment on that?

**Comment by Jenefer-Monroe** [comment]
Can you please see what type (tier) of connectors these international ones are? 
You can do this by going to the Connectors page in the app and looking for the name
![image](https://user-images.githubusercontent.com/89584709/175066786-56638772-ffdc-493d-ba04-154144c2ef3c.png)

Our suspicion is that these are custom connector since in your example it shows the intl name and Sharepoint  in English. 
If you can't find it in that list, you can use the Custom Connectors view to search.

**Comment by MSFT-klpinhac** [comment]
No, the custom connectors are not localized
![coe_admin_view_connectors](https://user-images.githubusercontent.com/84438062/175236851-4ec13c9a-8369-4e7a-93df-28df5faa47be.jpg)

Here is another screenshot of PowerApps in the "Admin View", which is a bit better than the 1st one:
![coe_admin_view_pas](https://user-images.githubusercontent.com/84438062/175237278-998c78ff-5110-4804-b313-9fae4bbc5cd8.jpg)

The displayName of the connection references is localized:
![coe_admin_view_pas_ps](https://user-images.githubusercontent.com/84438062/175237390-aeba62de-0d64-4913-9036-aa809531af70.jpg)

**Comment by Jenefer-Monroe** [comment]
ok it looks like this is not just custom connectors. Some connectors have a localized display name. 
marking as a bug to investigate for August so we can ensure this doesnt impact DLP. And if it doesnt, and just UX, then to figure out if an easy fix to offer.

**Comment by manuelap-msft** [comment]
We've updated the sync flow and clean up flow to store the connector id name (shared_office365) rather than the display name. We're now working on updating all the apps that use the connection string (DLP Editor etc).

**Comment by manuelap-msft** [comment]
DLP Editor has been updated.
