### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flows)

### ISSUE THREAD

**Issue by rfolgadoal** [microsoft/coe-starter-kit#3000]
### Describe the issue

I created a Flow in Teams environment but when I took a look into Power Platform Admin View app, this flow was in the Default environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

**Comment by manuelap-msft** [comment]
Hello,

can you share the steps on how you created the flow? If you go to flow.microsoft.com, does the flow show up in the Teams or Default environment for you?

Thank you
Manuela

**Comment by rfolgadoal** [comment]
First, I added Power Automate to channel, and then I created a new flow.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/93584307/174034194-f5ca7271-750a-4d7b-a32a-60e346236a88.png)

**Comment by manuelap-msft** [comment]
Hello,

thank you!

That is a known limitation of the Power Automate app in Teams, see: https://docs.microsoft.com/en-us/power-automate/teams/install-teams-app#known-issues

![image](https://user-images.githubusercontent.com/55705669/174056201-4a59da29-3726-4886-b4f1-774cf3ad23a3.png)


Closing this issue as it's expected product behaviour.
Manuela

**Comment by rfolgadoal** [comment]
Ok. Thanks!
