### ISSUE TITLE
Group Teams configuration showing teams from CoE environment

### ISSUE THREAD

**Issue by alanrroberts** [microsoft/coe-starter-kit#3001]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/2922

<div type='discussions-op-text'>

<sup>Originally posted by **alanrroberts** June  6, 2022</sup>
I am trying to set up the ALM Accelerator to replicate required AAD group based Teams to a new environment as part of a deployment and have a couple of issues

1. The list of AAD groups only seems to include include Security Based groups, not Office based groups.  Is that by design?
2. The list of roles to choose to assign to the Team/group only includes the roles available in the environment I have the ALM installed in.  It doesn't include the roles in the environment containing the solution I am trying to commit so I am unable to select the correct role.  If I type in a role name manually it is ignored and the AadGroupTeamConfiguration section in customDeploymentSettings.json remains empty.  Is this as expected?

Thanks

Alan</div>

**Comment by jenschristianschroder** [comment]
Hi @alanrroberts,

Thanks for posting these questions. Can you please let us know which version of ALM Accelerator are you using?

1. This should be fixed with the latest release to also include office based groups.
2. This sounds like a bug. Will need to investigate this.

**Comment by alanrroberts** [comment]
Hi @jenschristianschroder.  I am using 1.0.20220517.1

**Comment by mikefactorial** [comment]
Closing this out. This was resolved in a previous release.
