### ISSUE TITLE
[CoE Starter Kit - BUG] CoE sync tables missing data

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#3003]
### Describe the issue

CoE Starter kit sync only partially retrieves Power Platform artifacts from tenant. 

Power Automate Desktop Flows in the production environment are not being picked up and available to the CoE Power BI report. In fact the entire production environment is not listed as an environment to filter on in PBI - Desktop Flows view. 

Comparing the actual flows (automate/desktop) in the production environment to the CoE table contents the desktop flows are missing, as well as one other automate flow, however there is data from all the environments being captured including production so it is not an access to prod issue.

Account used for connections is fully licensed and as power platform admin role assigned via group membership, in the admin group we use for managing accounts that have that role.

![Table-DesktopFlows](https://user-images.githubusercontent.com/93291159/174097203-d4369b46-248c-4e8a-a92c-ba2413d620b8.png)

### Expected Behavior

All data from tenant is available in the CoE sync tables, and available to Admin View Model app as well as PBI Report.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin - Sync flows in general

### Steps To Reproduce

Install CoE kit, and let it run.
Compare environment contents to CoE tables/Admin View/PBI Report

### Anything else?

NOTE: support ticket 2206140040008348 was open through Admin Portal, and assigned rep had no experience with CoE or knew how to address this issue.

This is a production issue for us.

**Comment by Jenefer-Monroe** [comment]
There are limits on what data we can collect, including some limitations on Desktop Flows. See our [limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations) for details. 

1. Please confirm that the identity used to run the sync flows has its PPAdmin role permanently assigned. We cannot support dynamic permissioning. Please see [PIM (Privileged Identity Management)](https://docs.microsoft.com/power-platform/guidance/coe/limitations) from our limitations page. 

1. Please validate that all the flows in the [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) are turned on, running, and passing.

**Comment by peteredc** [comment]
The CoE was installed with my account (PApp, PAuto, PPAdmin role), so I own all the flows, however the connectors are all using an AD 'service account' that is PApp, PAuto licensed, and is also a member of the same admin group that I am and has the Az PPAdmin Role assigned (screenshot below).

Also, for the last few days the 'inventory delay' has been off, so I can debug and 'Full Inventory' has been set to yes to try and force the tables to populate regardless if the record already existed. 

Note that the limitation for Service Principals is contrary to https://docs.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-automate/ownership-supported-service-principals.  

We had planned on using SP's as owners in the future; but currently don't do this.  It would be good to know if the docs are out of date or if this is still current guidance.


Admin Template (Desktop Flows) Details
![AdminSyncTemplateDesktopFlowConnector](https://user-images.githubusercontent.com/93291159/174148436-987dec4a-b523-448e-9623-3c66a8d8f99f.png)


Admin Template (parent)
![AdminSyncTemplate](https://user-images.githubusercontent.com/93291159/174147909-ee490631-0136-4279-8890-bb18f024d8fd.png)

Admin Template (Desktop Flows)
![AdminSyncTemplateDesktopFlow](https://user-images.githubusercontent.com/93291159/174147924-795c9a7e-7d64-4e2d-82f6-9f0eea53fea9.png)


Permanent assignment of PPAdmin Role
![CoESvcAcctAZRoles](https://user-images.githubusercontent.com/93291159/174104081-efe3cc2a-3ea4-4790-b41d-49185fa83474.PNG)

**Comment by peteredc** [comment]
I ran the sync flows and the delete flows manually, and the results also don't match the tenants; specfically the WaldoDesktop flow is still showing in Personal Prod, and it's been deleted, and the Production environment doesn't show the WaldoDesktop flow even though it's installed.

Production Waldo Flow:
![ProductionWaldo](https://user-images.githubusercontent.com/93291159/174151672-bb9d18a9-883d-4f24-bcc4-659522da5c97.png)

Production Waldo Desktop Flow:
![ProductionWaldoDesktopFlow](https://user-images.githubusercontent.com/93291159/174151998-f7eb385d-eed0-45fc-889b-9280be066c87.png)


Cleanup deleted:
![CleanupFlow](https://user-images.githubusercontent.com/93291159/174150922-754d6cbd-4c60-495d-996c-c9b0b617af71.png)


![AdminViewFlows](https://user-images.githubusercontent.com/93291159/174149829-27a401f0-0c7e-4340-8f85-91b42c05dae3.png)

![AdminViewDesktopFlows](https://user-images.githubusercontent.com/93291159/174149855-fb99cde0-3b9c-48d3-a33a-0b17141982f9.png)

**Comment by peteredc** [comment]
@Jenefer-Monroe  And all flows were stopped and started as per https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components prior to all screenshots above.

**Comment by manuelap-msft** [comment]
> Note that the limitation for Service Principals is contrary to https://docs.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-automate/ownership-supported-service-principals.

Regarding this note, this capability is not yet available in the product and with the exception of Dataverse, none of the connectors the CoE Starter Kit use support authentication with service principals. This is a product limitation.

**Comment by peteredc** [comment]
As far as I can tell this functionality does exist.  It is stated as GA for June 2022, and as the screenshot shows the SP can be assigned as owner to a solution aware flow.

I'm referring to SP ownership of a flow. 

**Feature details**
Currently, flows that Service Principals own cannot be enabled because connections cannot be shared with service principals. As a workaround, **makers use shared "service accounts"** when they want more than one person to own a flow.

_In 2022 release wave 1, we're updating connection sharing capabilities to allow flow ownership by a user that represents a Service Principal._

We have been doing the bolded above...which is not ideal.

I mentioned it as the limitations https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#flows-that-are-imported-or-owned-by-a-service-principal, state that you cannot use SP owned flows with the CoE.  I'm assuming the CoE docs are out of date, as I don't see why it wouldn't work if it's supported in GA.

I ask, as using SP's as owners is where we'd like to go, and when working with the Pipelines https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools#configure-service-connections-using-a-service-principal

as well as the ALM Accelerator I believe the SP that the pipeline is using to access the PP environment will be the owner...
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-environment-and-service-connection-variables-required

You may be thinking of the connection SP functionality which is this Sept for public preview. https://docs.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-platform-pro-development/service-principal-support-connectors

![image](https://user-images.githubusercontent.com/93291159/174306678-d8511998-175c-4526-9b22-271d3a655d1b.png)

![SPOwnerFlow](https://user-images.githubusercontent.com/93291159/174306742-5166b101-7e6c-4a4a-a497-560210efd190.png)




> > Note that the limitation for Service Principals is contrary to https://docs.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-automate/ownership-supported-service-principals.
> 
> Regarding this note, this capability is not yet available in the product and with the exception of Dataverse, none of the connectors the CoE Starter Kit use support authentication with service principals. This is a product limitation.

**Comment by peteredc** [comment]
@Jenefer-Monroe I guess at this point we should confirm a few things.

1. The missing desktop flows in the CoE tables is due to https://github.com/microsoft/coe-starter-kit/issues/2755
2. Power Platfrom Tools for ADO - When using the Import Task with the SP any flows owned by an SP **will** show in the CoE, (due to recent support of SP's for owners of Flows) but all other artifacts in the imported solution that has SP owner **will not** show in the CoE tables
3. ALM Accelerator will have the same outcome as point 2, as it's also using SP's to access and import/export/etc Power Platform Environments and solutions.

Please let me know if the above is correct, or comment where needed.

Thanks!

**Comment by peteredc** [comment]
@Jenefer-Monroe thank you for your help.

**Comment by Jenefer-Monroe** [comment]
you are most welcome
