### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template V3 error

### ISSUE THREAD

**Issue by hisae-kimura-gt** [microsoft/coe-starter-kit#3005]
### Describe the issue

We are experiencing a recurring issue with the cloud flow "Admin | Sync Template V3" that causes it to fail.

The error occurs at the following step in the flow:
![image](https://user-images.githubusercontent.com/107662722/174217370-a563a166-09f4-48e8-a1bc-dc816a3fc23e.png)
![image](https://user-images.githubusercontent.com/107662722/174217464-9c895de6-ce31-497b-9032-dc1cfa660e33.png)
![image](https://user-images.githubusercontent.com/107662722/174217534-cedcb374-aaea-422c-b48e-90d95e743716.png)
![image](https://user-images.githubusercontent.com/107662722/174217628-ec8dd834-6f04-4730-8e9c-db2e014ebb23.png)

Originally, with the filter of the Maker checked today action line
You need to pass a GUID format value to admin_makerid, but in a development environment you get an error because the "SYSTEM" string is passed
![image](https://user-images.githubusercontent.com/107662722/174215973-16dc8442-20b6-40ce-b1f5-9e23cd06578a.png)

The above Maker ID is the caller's "Admin | Sync Template v3" flow
The "Creator ID" of the result of the Get Environments action is set.
![image](https://user-images.githubusercontent.com/107662722/174216073-bd5d3476-3fa5-4a25-b354-00a8de21aeb7.png)

### Expected Behavior

I want you to be able to execute normally even if "Maker ID" is "SYSTEM"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

Open Center of Excellence - Core Components solution
Select Cloud Flows and open "Admin | Sync Template V3"
View flow history

**Comment by Jenefer-Monroe** [comment]
We do not repro this, system created environments are able to inventory. I believe you have unmanaged layers preventing you from seeing latest flow structure. 

Please check for the unmanaged layers on all the inventory flows. You can do this most easily in the Admin - Command Center by filtering to inventory and looking for the layers symbol. 

![image](https://user-images.githubusercontent.com/89584709/174324265-e1ff75c9-c79f-4820-a2d9-523fffa035c0.png)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team

**Comment by hisae-kimura-gt** [comment]
solved.
Thank you for your support
