### ISSUE TITLE
Change how Connection References and Environment Variables are set to align with new Build Tools task

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#301]
As previewed in this session (at about the 18:55 mark):
https://mymbas.microsoft.com/sessions/b12efbf9-6882-47af-9f7b-d19fd8b83ffd

The Build Tools task will have native support for setting Connection References and Environment Variables on import.  If we switch to the same file-based approach, using the same json schema, we will not only improve the variable configuration experience, but we will also make the experience of [replacing our code for Connection References and Environment Variables with the updates coming in the Build Tools](https://github.com/microsoft/coe-starter-kit/issues/104) smoother.

**Comment by rpothin** [comment]
I think it is definitely the good thing to do!
+1

**Comment by mikefactorial** [comment]
Removed breaking change from this as we've made it possible for users to choose either to use the new tasks when they are available or continue to use existing pipeline custom tasks

**Comment by mikefactorial** [comment]
@devkeydet This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.
