### ISSUE TITLE
Repositories not showing in the ALM App

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#3013]
### What is your question?

I set all of the permissions in my project settings repositories as indicated in the guide: 
1. https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#update-permissions-for-the-project-build-service
2. https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#update-permissions-for-the-project-build-service-to-use-the-service-connections

Yet, I am not seeing my repositories in the dropdown when I open the ALM application, while creating a profile. 
I tried testing the custom connector and it returns a blank array. 

Where am I missing permissions to see the repositories from the app? Because from Devops I can see and edit the repos. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

May 2022

**Comment by mikefactorial** [comment]
@LizethRegules some screenshots may help. It sounds like you have done everything necessary to be able to see the repos since the custom connector impersonates your user and you are seeing them in DevOps so I'm not quite sure what the issue is here.

**Comment by mikefactorial** [comment]
@LizethRegules I just ran a test that could be related to your issue. Can you verify that the user has at least "Basic"  access level in Azure DevOps e.g. 
![image](https://user-images.githubusercontent.com/42348035/174858776-5779fc3c-17a3-4d7c-8e03-8e1f72c4e384.png)

I got the same result you did above when I changed my user from Basic to Stakeholder.

**Comment by LizethRegules** [comment]
I'll take a look, and close the issue if it's the case. Thank you, Mike!
