### ISSUE TITLE
[CoE Starter Kit - BUG] Flow 'Admin | Sync Template v3 (Portals)' fails when a portal is owned by a user that no longer exists within the organisation.

### ISSUE THREAD

**Issue by matt-lindsay** [microsoft/coe-starter-kit#3017]
### Describe the issue

Flow 'Admin | Sync Template v3 (Portals)' fails when a portal is owned by a user that no longer exists within the organisation.

### Expected Behavior

Expected all organisation portal sites to be listed recorded by the Flow, and visible in the  'Power Platform Admin View' model driven app.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Portals)

### Steps To Reproduce

1. Run the portal sync flow against a portal site where the owner no longer exists.

### Anything else?

{
    "error": {
      "code": "0x80040217",
      "message": "admin_Maker With Id = {GUID} Does Not Exist",
      "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
      "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "{GUID}",
      "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
      "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "{GUID}",
      "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
      "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
      "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
      "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",
      "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
      "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
      "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_Maker With Id = {GUID} Does Not Exist"
    }
  }

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of where in the sync flow you are seeing this error?

**Comment by matt-lindsay** [comment]
Hi @Jenefer-Monroe, please see screen shot below.

![image](https://user-images.githubusercontent.com/8628961/175009429-30e62089-d413-4f22-8a7c-2ec1e1c7e975.png)

**Comment by Jenefer-Monroe** [comment]
That shows that the failure occurs someone in the "no" oath there, but not the specific action that failed. Please continue to parse down into the failure until you come to the termination of action.

**Comment by nasilvae** [comment]
Hi Team, I also having the same issue with a gcc tenant.

**Comment by Jenefer-Monroe** [comment]
In order to investigate we will need to dive further into the flow to find the failure. If you have a repro, please dive down and find the terminating failure and share here.

**Comment by nasilvae** [comment]
![image](https://user-images.githubusercontent.com/95443860/176233494-d8160793-dbaf-4429-81d4-d6a5bfaae932.png)

**Comment by Jenefer-Monroe** [comment]
What is returned in the condition above **_Recheck Orphan status new_**? 
![image](https://user-images.githubusercontent.com/89584709/176244240-5049652e-67e1-46e3-b620-990bddcff37d.png)

And in the scope further up **_Get the owner and first orphan check_**
![image](https://user-images.githubusercontent.com/89584709/176244506-d90c431b-bcbe-4250-a063-31f02afb5bd2.png)

**Comment by nasilvae** [comment]
let me know if this helps 
![image](https://user-images.githubusercontent.com/95443860/176249265-3d33451d-6f6b-468c-9651-917474c08cb0.png)

**Comment by Jenefer-Monroe** [comment]
And then how does that faiure flow below? Does it go into the 404 in the switch statement?

**Comment by nasilvae** [comment]
yes, it does go to a 404 statement. It also finishes the execution at "Set isOrphan true 2". .

**Comment by Jenefer-Monroe** [comment]
Great, that is expected. So then in this scope in the portals flow, it should set isOrphaned to true, correct? 
![image](https://user-images.githubusercontent.com/89584709/176258554-e3615bcf-30d5-47d9-860a-b7fcdf5b1c8b.png)

**Comment by nasilvae** [comment]
![image](https://user-images.githubusercontent.com/95443860/176259893-dfbac247-2531-4e29-b98e-df695169b4e7.png)

**Comment by Jenefer-Monroe** [comment]
ready for August
