### ISSUE TITLE
[CoE Starter Kit - QUESTION] How can I find owner of Developer Environment in Power BI Report

### ISSUE THREAD

**Issue by NemadeUjwal** [microsoft/coe-starter-kit#3018]
### What is your question?

How can I find owner of respective Developer Environments in Power BI Report

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard_202206

**Comment by manuelap-msft** [comment]
Hello,

Developer environments are created by SYSTEM - if you look in the Power Platform Admin Center (aka.ms/ppac), you can see that there as well:
![image](https://user-images.githubusercontent.com/55705669/174773382-65fab22a-2f7b-44d7-8f16-2a2fd8c734e9.png)

There's no owner information available for these environments by the product, so unfortunately we don't have that information to display in the report.

Thank you
Manuela
