### ISSUE TITLE
[CoE Starter Kit - QUESTION] Archivals/Ophaned manage solutions with custom body notification

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#3019]
### What is your question?

Hi, are you planned to enable environment variables to customize the messages to the end users, by mail or teams, of the flows of inactivity componentes or orphaned resources?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Lastest

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
