### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - DLP Editor V2 - Impact Analysis Screen Doesn't Show Flows

### ISSUE THREAD

**Issue by matt-lindsay** [microsoft/coe-starter-kit#3022]
### Describe the issue

When reviewing the impact of a Data Loss Prevention policy, on the 'Impact Analysis' screen, the 'Analyzed Flows' tab does not return any data.

### Expected Behavior

Expected 63 Flows to be listed on the 'Analyzed Flows' tab of the 'Impact Analysis' screen. If you export to CSV these Flows are recorded.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

DLP Editor V2

### Steps To Reproduce

1. Open the DLP Editor V2 app
2. Select a DLP
3. Added an environment to the policy
4. Reviewed the Analyzed Flows tab in the Impact Analysis screen - no Flows were visible.

### Anything else?

![image](https://user-images.githubusercontent.com/8628961/174806614-78f2c946-1cf8-481d-af86-14fb7dd98e08.png)

**Comment by manuelap-msft** [comment]
We currently have a bug in the DLP editor that uses an incorrect filter on this page, this is code complete to be fixed with our July release. We're tracking the bug here https://github.com/microsoft/coe-starter-kit/issues/2983

Closing as duplicate.
