### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - DLP Editor>Parse impacted resources into CSV - Create CSV table for flows action

### ISSUE THREAD

**Issue by matt-lindsay** [microsoft/coe-starter-kit#3023]
### Describe the issue

The 'Create CSV table for flows' action is failing when trying to write the 'admin_flowmakerdisplayname' and 'admin_FlowCreator.admin_userprincipalname' items to the CSV table.

### Expected Behavior

The CSV output should include the admin_flowmakerdisplayname and admin_FlowCreator.admin_userprincipalname.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

DLP Editor>Parse impacted resources into CSV

### Steps To Reproduce

1. In the 'DLP Editor V2' app
2. In the 'Impact Analysis' tab
3. Click 'Export impacted apps and flows to csv' button
4. The 'DLP Editor>Parse impacted resources into CSV' triggers and fails.

### Anything else?

InvalidTemplate. The execution of template action 'Create_CSV_table_for_flows' failed. The column values could not be evaluated: 'The template language expression 'coalesce(item()['admin_flowcreator/admin_userprincipalname'], '')' cannot be evaluated because property 'admin_flowcreator/admin_userprincipalname' doesn't exist, available properties are '@odata.type, @odata.id, @odata.etag, @odata.editLink, admin_flowconnections, admin_flowid@odata.type, admin_flowid, admin_flowenvironmentdisplayname, admin_flowenvironmentid, admin_displayname, admin_FlowCreator@odata.associationLink, admin_FlowCreator@odata.navigationLink'. Please see https://aka.ms/logicexpressions for usage details.'.

![image](https://user-images.githubusercontent.com/8628961/174808260-62061de3-fbbc-4ce0-b086-da11de87c8e8.png)

**Comment by Jenefer-Monroe** [comment]
I dont repro this, and believe we had a bug in the past where this ? after item() was missing. Looks like it is for you as well. 
`coalesce(item()?['admin_flowcreator/admin_userprincipalname'], '')`

Please see if you have an unmanaged layer on the flow and if so, remove it. 
Please see [Remove unmanaged layers](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) from our upgrade documentation for more information.

**Comment by matt-lindsay** [comment]
Hi @Jenefer-Monroe, no unmanaged solution layer I'm afraid. But adding the `?` after `item()` allowed the action to run correctly. I do now have an unmanaged solution layer.

**Comment by Jenefer-Monroe** [comment]
Perhaps she fixed it locally only for July. Next release will have the fix for sure and you can remove the unamanged layer when you upgrade. 
Thanks for using CoE

**Comment by matt-lindsay** [comment]
OK, thanks for the info @Jenefer-Monroe
