### ISSUE TITLE
[ALM Accelerator - custom connector issue] 

### ISSUE THREAD

**Issue by tbrscr** [microsoft/coe-starter-kit#3024]
### What is your question?

The CustomAzureDevOps connecto doesn't work for me.
How can I solve this issue?
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/107469963/174810678-ab32a5c6-13f9-4221-b53c-0943b7448877.png">

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20220517.1

**Comment by mikefactorial** [comment]
closing out as no further action for starter kit team
