### ISSUE TITLE
[CoE Starter Kit - BUG] Reported Sync Flow Failures don't open to failed flow from Command Center

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#3026]
### Describe the issue

Reported Sync Flow Failures in the Command Center result in the wrong environment, and 404 error when clicking on link provided in Sync Failure view.

This is also the behaviour in the email sent to the admins for Sync Flow Failure. 

**Admin View**
![AdminViewUrlFail](https://user-images.githubusercontent.com/93291159/174810971-88fa5623-dc21-4017-8c45-4456c31b9407.PNG)
 
**Page Opened from URL**
![AdminViewUrlFailOpenPage](https://user-images.githubusercontent.com/93291159/174811109-59f9f7cf-7086-4e33-ab1a-608b813e7b6c.PNG)

**Email**
![SyncFailEmail](https://user-images.githubusercontent.com/93291159/174811130-c5ca1785-15a1-42a4-82b8-8ec6563963ea.PNG)

### Expected Behavior

URL in Command Center or email, opens the flow that has the sync failure, so we can determine the error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

1. Get Sync Flow Error message in Command Center
2. Click on reported error

### Anything else?

Email received time and date stamp don't match failure time and date.  Command View seems to be using the specific history, and that information matches the history of the flow.

Why is the email delayed?  Does it only go out the day after for errors, based on the history of failures in the CoE at large?

**Comment by Jenefer-Monroe** [comment]
The link relies upon an envt variable to create the correct link. Please see what you have for **_Power Automate Environment Variable_**

It appears that you did not include the manage/environments/ part of the string. I think your string should be https://canada.flow.microsoft.com/manage/environments/

Be sure to turn the flows off and on again to get this to reset in the flows. 

![image](https://user-images.githubusercontent.com/89584709/174833133-a10b685f-ec09-42b6-876a-d6059f40ed6b.png)

**Comment by Jenefer-Monroe** [comment]
You can see all the flows that rely on the env var by showing its dependencies. 
![image](https://user-images.githubusercontent.com/89584709/174871419-cd91bbe9-9d5f-478f-a58f-928b9b3c9c32.png)

You dont need to worry about the order. I cant offer a batch operation unfortunately. 
Hope this resolves it for you!

**Comment by peteredc** [comment]
@Jenefer-Monroe thank you!
