### ISSUE TITLE
[CoE Starter Kit - QUESTION] Command Center Red Flags will not clear

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#3034]
### What is your question?

We continue to get 'red flags' in the Command Center, that mention letting the flow complete before continuing however, these flows have been stopped/started a few times and the flag continues to appear.

How do we clear the flags?

![image](https://user-images.githubusercontent.com/93291159/174893165-f3610f54-6e3b-4cbd-a5d0-1c3aa9a7e257.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin Command Center

**Comment by Jenefer-Monroe** [comment]
You will not clear those flags. That is a permanent note about the flow.

**Comment by Jenefer-Monroe** [comment]
Closign out as no further action for starter kit team
