### ISSUE TITLE
Change Dev ServiceConnection Variable for Pipeline

### ISSUE THREAD

**Issue by andrewgaskins** [microsoft/coe-starter-kit#3037]
### What is your question?

I made a mistake when setting up the dev environment with a mis-spelled url. This is keeping me from being able to export to Git. I have looked everywhere and can't seem to find the location to change the dev service connection reference. The service connection is correct in settings. 

Thanks for any assistance. I wasn't sure if I need to delete and start over.

There was a resource authorization issue: "The pipeline is not valid. Job export_solution_to_git: Step PowerPlatformPublishCustomizations input PowerPlatformSPN references service connection https://**wrongaddress**-dev.crm.dynamics.com/ which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz. Job export_solution_to_git: Step PowerPlatformExportSolution1 input PowerPlatformSPN references service connection https://**wrongaddress**.crm.dynamics.com/ which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

June 2022

**Comment by mikefactorial** [comment]
Fair feedback @andrewgaskins. We're working toward a more confgurable / flexible and re-entrant experience in the pipelines and in the app. Currently the cli that we use during setup and in the pipelines are a bit rigid and assume that everything is entered correctly the first time. In your case it's likely that the url is being passed to the pipeline with a name that doesn't exactly match the service connection name in your environment. We have some updates in the July release that will alleviate that but for now the assumption is the variables / parameters passed to a pipeline in the ServiceConnection parameter / variable are named EXACTLY the same as the Service Connections in Azure Devops (including any trailing spaces / forward slashes etc.

**Comment by KodulkarNilesh** [comment]
@andrewgaskins , please environment and service connection variables[this](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-environment-and-service-connection-variables-required) and [global variable](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-pipeline-global-variables)  section.

FYI: I am also facing same problem. I am using May 22 release

**Comment by mikefactorial** [comment]
@andrewgaskins the variable in question is on the deployment pipeline e.g. 
![image](https://user-images.githubusercontent.com/42348035/176896781-fda4ca77-ec4f-4284-90c3-a3488b68a6d2.png)
