### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to import old Audit Logs

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#3040]
The below will walk you through the process of loading in old audit logs, to jump start the app launch metrics used since the custom connector cannot go back further than 7 days.

### PREPARE AND LOAD THE XL FILE
1. Go to https://compliance.microsoft.com/auditlogsearch, filter to Launched apps, go back as far as you’d like (and that your license will allow), and hit search.  
![image](https://user-images.githubusercontent.com/89584709/172685356-886dee9b-9a4a-4a49-bca5-67cc989b56d4.png)

1. Download the results
![image](https://user-images.githubusercontent.com/89584709/172685390-aa3b4a4b-bb7e-408e-a522-01275ec92663.png)
 
1. Open your downloaded file, create a Table from the data in the sheet
Put your mouse in A1 > Control-T > Ensure you have **My table has headers** checked > OK
![image](https://user-images.githubusercontent.com/89584709/172685412-dda80d6a-cc58-4030-ad85-ed6aea73225f.png)

1. Save as xlsx into a SharePoint or OneDrive location
![image](https://user-images.githubusercontent.com/89584709/172685437-73b3a1b5-09c8-46d5-9c15-644dc8b9def5.png)

1. Close the file (or flow will not be able to fetch the tables)

### IMPORT THE HELPER FLOW
1. Go to https://flow.microsoft.com/ > your CoE Environment > My flows > Import
![image](https://user-images.githubusercontent.com/89584709/172686241-cb88df25-aff2-4dbf-b14f-d724288b99c1.png)

1. Upload this helper flow: [ImportOldAuditLogs_20220622134144.zip](https://github.com/microsoft/coe-starter-kit/files/8958163/ImportOldAuditLogs_20220622134144.zip)
![image](https://user-images.githubusercontent.com/89584709/172686678-6c7ec55f-fd6f-42c7-aedd-66916a123a90.png)

1. Create or select the connections
![image](https://user-images.githubusercontent.com/89584709/172687020-aa94da7d-e675-4961-86f2-0bf494363614.png)

1. Import the flow
![image](https://user-images.githubusercontent.com/89584709/172687254-07e9838d-5546-4c0f-b59a-24a51063faca.png)

1. Once imported, click Open flow
![image](https://user-images.githubusercontent.com/89584709/172687692-8280c6bb-dc5e-48bf-8739-8449ad6faedb.png)
 
### AUGMENT AND RUN THE HELPER FLOW
1. With the flow open, edit the **List rows present in table** action to point to your file and table
![image](https://user-images.githubusercontent.com/89584709/172687941-705dedd3-2d53-4b8f-ba9a-da1a5e6fc416.png)

1. Save the flow and return to details page, turn on the flow
![image](https://user-images.githubusercontent.com/89584709/172688176-3b089f04-903f-4cf6-9e96-a165999a2560.png)

1. And lastly, run the flow
![image](https://user-images.githubusercontent.com/89584709/172688568-559d69f8-48ab-4272-a8d3-954fd76cf0ff.png)

### Once complete
Once complete, this flow will pull in all the old data into the Audit Logs table, and also update the Last Launched date accordingly.

**Comment by KristenStanley** [comment]
Hi, Thank you for providing this flow.  I installed it according to your directions.  When I run the flow, I get an error message saying admin_App With Id xxxxx Does Not exist.  I have a number of these error messages.  Do you have any support you can provide for this?  
![ErrorMessage](https://user-images.githubusercontent.com/108080466/175940853-01aadc58-f8dc-4c60-8571-b36feccdae3d.PNG)

**Comment by KristenStanley** [comment]
Thank you for responding so quickly!  I appreciate it so much!  I am not sure how to figure out how many in all 18,000+, but there are a bunch.  So the Audit log has a record of the app ID, but the App table does not.  When I look in the Audit Logs table, I can see data for the date range that was in my downloaded Audit log Excel file.  However, when I look at the Apps table, I still only see last launch date from the time I installed the CoE to today.  It's like the audit logs were imported, but the Last Launch date in the App table was not updated.  Any suggestions on where I have gone wrong?  Should I delete the imported Audit log records, and try again?

**Comment by Jenefer-Monroe** [comment]
You flow does not seem to match the one we shipped. You have some extra actions. Can you start from the beginning of the above and try again? 

If you still repro, note that the first failure (Insert Audit Log record) is caught, You will need to expand that second failure (See if app already exists...) and see what failure is listed there.

**Comment by Jenefer-Monroe** [comment]
Someone in another thread found a bug in my flow. You can try it here:
[loadoldauditlogs_20220627225411.zip](https://github.com/microsoft/coe-starter-kit/files/8996086/loadoldauditlogs_20220627225411.zip)

**Comment by GaelCasOuv** [comment]
Hi @Jenefer-Monroe, I tried to import the helper flow but I got this error:

**Comment by Jenefer-Monroe** [comment]
Did you do the steps above where it shows selecting your own data source? 
![image](https://user-images.githubusercontent.com/89584709/184145386-5cd0926b-9768-4064-a3e5-cafe63dac338.png)

**Comment by GaelCasOuv** [comment]
Hi Jenefer, thank you for your quick support.

I can't reach this step; I get the error when pressing the "import" button. As a workaround I saved the flow manually and then I was able to change the data source but when I execute it, I got a new error in the Parse JSON step:

![image](https://user-images.githubusercontent.com/110904209/184297133-67e1b983-8470-4f59-b21f-b59a65d028d8.png)

![image](https://user-images.githubusercontent.com/110904209/184297226-170d4271-c26e-4fc4-98fa-7210245de711.png)

It looks like my table has different columns than the one you show in the example.

![image](https://user-images.githubusercontent.com/110904209/184297349-c328a504-d51a-4bf2-b28a-a80a7c2dcd54.png)

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately it appears that this data is not consistent across tenants, one other person user hit this too and was able to fix it up. 
Unfortunately this was just some helper information I wrote up, its not part of the kit and so I cant really scale to assisting. You'll need to try and do the mapping yourself. If you arent familiar enough with flow to do this, perhaps you can reach out to one of the heavy users in your tenant for assistance!

**Comment by A-Demir-ilx** [comment]
Hi @Jenefer-Monroe , I have the same issues as already mentioned by @GaelCasOuv

**Comment by Jenefer-Monroe** [comment]
Yes thats correct. Its because different tenants have different structures for the output, so the parse will need made to match your tenant. Unfortunately we cannot scale to assisting with this work

**Comment by johndpalm** [comment]
> Yes thats correct. Its because different tenants have different structures for the output, so the parse will need made to match your tenant. Unfortunately we cannot scale to assisting with this work

@Jenefer-Monroe I think you misunderstand.  The error occurs when trying to import the zip file.  The flow is never imported to hit a difference in schema as you describe.

![image](https://user-images.githubusercontent.com/1281085/185656309-0ac683de-ee0c-4fc8-a51e-98fd6d151efc.png)

It appears the parameters for the list rows action is causing the error.  The source, drive, and file values are not accessible in my environment causing the 404 error upon import.

```
                "List_rows_present_in_a_table": {
                    "runAfter": {},
                    "metadata": {
                        "01M6V6XEWMH4KP42D4VFBI5MSRRIZX3UXX": "/MakerAssessmentStarterData.xlsx",
                        "operationMetadataId": "5382a96d-0c93-4e16-b76c-3ea6058b773a",
                        "tableId": "{00000000-000C-0000-FFFF-FFFF00000000}",
                        "01M6V6XEWQRZAASFESRNG25D7DP2KDYH7S": "/AuditLog_2022-03-10_2022-06-08.xlsx",
                        "01M6V6XEUY5LSFNMNPEFBYIYNQTJF63FFI": "/AuditLog_2022-03-24_2022-06-22.xlsx",
                        "01M6V6XERFDVBQMMYTOJB2MFBMUOFEL7RU": "/AuditLog_2022-05-30_2022-06-27.xlsx"
                    },
                    "type": "OpenApiConnection",
                    "inputs": {
                        "host": {
                            "apiId": "/providers/Microsoft.PowerApps/apis/shared_excelonlinebusiness",
                            "connectionName": "shared_excelonlinebusiness",
                            "operationId": "GetItems"
                        },
                        "parameters": {
                            "source": "sites/pplatform.sharepoint.com,b2ee86c4-954f-445b-8ed9-df5afb58668c,458c4093-c7c2-417f-940c-1f23aa270108",
                            "drive": "b!xIbusk-VW0SO2d9a-1hmjJNAjEXCx39BlAwfI6onAQh-ydU4QpHlS5s6iCuLSFuP",
                            "file": "01M6V6XERFDVBQMMYTOJB2MFBMUOFEL7RU",
                            "table": "{00000000-000C-0000-FFFF-FFFF00000000}"
                        },
                        "authentication": {
                            "value": "@json(decodeBase64(triggerOutputs().headers['X-MS-APIM-Tokens']))['$ConnectionKey']",
                            "type": "Raw"
                        }
                    },
                    "runtimeConfiguration": {
                        "paginationPolicy": {
                            "minimumItemCount": 100000
                        }
                    }
                }
```

**Comment by Jenefer-Monroe** [comment]
Cross tenant import of XLO should be allowed, and has been for others so I'm not sure. Perhaps something changed in the product to change this behavior. However it appears you got past that step per this comment:  As a workaround I saved the flow manually and then I was able to change the data source but when I execute it, I got a new error in the Parse JSON step:

**Comment by Jenefer-Monroe** [comment]
Either way I'm afraid this was all just written up to get folks started and its not part of the kit, or something that we have resources to work on. You may be able to manually import the content you export from the product.

**Comment by ccampora** [comment]
> Hi @Jenefer-Monroe , thank you for your quick support.
> 
> I can't reach that step; I get the error when pressing the "import" button. As a workaround I saved the flow manually and then I was able to change the data source but when I execute it, I got a new error in the Parse JSON step:
> 
> ![image](https://user-images.githubusercontent.com/110904209/184297133-67e1b983-8470-4f59-b21f-b59a65d028d8.png)
> 
> ![image](https://user-images.githubusercontent.com/110904209/184297863-6529728f-d35a-40ce-aeff-245dc8418ab3.png)
> 
> It looks like my table has different columns than the one you show in the example.
> 
> ![image](https://user-images.githubusercontent.com/110904209/184297349-c328a504-d51a-4bf2-b28a-a80a7c2dcd54.png)

This is due the new Search feature in the Microsoft compliance center. Make sure when you do the search, use the Classic Search.

**Comment by mknightca** [comment]
Hi everyone,

@Jenefer-Monroe 

I've done all the steps, everything has worked, I can see all my old 'app launches' in the audit table. However, this is not being reflected in the power bi report under deep dive apps/flows. It's only showing new app launches from after I launched CoE and none of this historical data. 

I've tried running Admin | Sync Audit Logs and Sync Template v3 twice as well as refreshing the dataset for the powerBi report.

Not quite sure what I should be targeting next to get the 'app launched' historical data in my reports.  That being said even for the 'new' app launches the 'app launched' column isn't populated either so maybe i'm missing a step. I've only installed CoE core components and audit solution. Could you guide me to my next step to troubleshoot?

**Comment by Jenefer-Monroe** [comment]
Folks this thread is closed and so we are no longer iterating on it. 

If you have new issues plesae post them as new ones: https://github.com/microsoft/coe-starter-kit/issues/new/choose
And if you struggle to get this helper to work, I'm afraid we are not staffed to assist further. You may need to start from scratch or otherwise figure out how to get old audit log data to the new envt.

**Comment by scroggoid** [comment]
Hey all, i know this was closed but I found a solution to the issue people were having importing this flow. You need the correct metadata for your excel file for it to import. To get around this: 
 
- Create a new flow with the excel action "List rows present in a table". 
- Point it to your new xlsx file you created that has the table of old audit log data in it. 
- Save it and export it. 
- Use 7zip to open the archive it exported
- Go to Microsoft.Flow->flows->flowid folder 
- Edit definition.json using notepad++ from within 7zip (you will have to set up notepad++ as the editor). 
- Select all and format the definition.json file using json tool addin. 
- Go down to where the "List rows present in a table" definition is and copy everything. 

- This is the metadata you need to insert into the same definition.json file inside [loadoldauditlogs_20220627225411.zip]
- Go to the same place in that loadoldauditlogs zip and replace the wrong "List rows present in a table" metadata with what you copied from your new flow you created. 
- Save the changes inside the archive and re-upload, you should be able to get past the "Flow save failed" error code.
