### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View environment bug

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#3044]
### Describe the issue

Hello,
when I try to filter by Environement on App section I found the duplicate in the attachment... You know why?

Thanks
![duplicate](https://user-images.githubusercontent.com/101250592/175130581-b5c5488c-f2da-4754-b072-3ae3f37621b8.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.36

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Do you have the **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_** flow turned on and running? 
What value do you have for the **_Also Delete from CoE_** environment variable?

**Comment by JackSocini** [comment]
In the enviroment section I only see two env.
![env](https://user-images.githubusercontent.com/101250592/175248199-6ad2b6f6-cd45-4424-a4d3-6ea368c4c057.jpg)
The flow is active but have some error (L'azione 'Call_Canvas_Helper_-_delete_all' non è riuscita
).
![err](https://user-images.githubusercontent.com/101250592/175248411-e32b0f86-e679-442f-988f-6f571a030e74.jpg)

**Comment by Jenefer-Monroe** [comment]
Yes it looks like your issue is that Check Deleted is failing. 
Given your role, in the future before posting issues for us, please investigate if your customer inventory is running correctly.

**Comment by Jenefer-Monroe** [comment]
Closign out as no further action for starter kit team

**Comment by JackSocini** [comment]
The problem persists...
![good](https://user-images.githubusercontent.com/101250592/178251326-cf412149-8f49-436d-8904-9dc956f55874.jpg)

**Comment by Jenefer-Monroe** [comment]
You will need to do some investigation here and post an actionable issue for us.
