### ISSUE TITLE
[ALM Accelerator - DOCS]: AADHost variable not getting created while deploying through COE CLI

### ISSUE THREAD

**Issue by Suparna-Banerjee** [microsoft/coe-starter-kit#3046]
### Describe the issue

While deploying ALM accelerator using COE CLI, the variable group alm-accelerator-variable-group gets created with all other variables except AADHost , need to manually add AADHost

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

May 2022

**Comment by mikefactorial** [comment]
@Suparna-Banerjee thanks for reporting this will look into what's happening here.

**Comment by mikefactorial** [comment]
@Suparna-Banerjee was the AADHost variable created with no value or was it not created at all? I'm reviewing the code and it is added to the variable group.  https://github.com/microsoft/coe-starter-kit/blob/375a9ad92f24e38c0148fd0471f75159298752b1/coe-cli/src/commands/devops.ts#L487

**Comment by Suparna-Banerjee** [comment]
Hi Mike,

The AADhost variable was not created at all for me. I will download the
latest version and will give it a try again, will update you if I still
face the issue.

Thanks,
Suparna

**Comment by mikefactorial** [comment]
@Suparna-Banerjee heads up AADHost was something that was added in a recent release so if it wasn't installed as part of the cli that would make sense.  Not through any fault of your own but maybe introduced in a version that we may have upgraded.

**Comment by mikefactorial** [comment]
It was called out in the https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-March2022 release, but we do need a better way of communicating this.

**Comment by Suparna-Banerjee** [comment]
@mikefactorial just had a look at March 2022 release updates, it mentions in the Upgrade Instructions -

_Add AadHost to alm-accelerator-variable-group. In general, the value for this variable will be login.microsoftonline.com except in the case of certain national clouds (https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud#azure-ad-authentication-endpoints)_

For the existing Azure Dev-Ops projects, we may add this variable manually. But while creating a new project using COE CLI, I think there should be instruction to upgrade the COE CLI version so that every time we don't need to manually add this variable.

**Comment by mikefactorial** [comment]
Closing this out as the original issue has been resolved. Will add an item to the documentation backlog to clarify that the latest CoE should be downloaded for any given release of the ALM Accelerator.
