### ISSUE TITLE
[CoE Starter Kit - BUG] Integrate new flow ownership transfer feature works with the kit

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#3052]
### Describe the issue

You can now change ownership of flows that are in a solution
https://docs.microsoft.com/en-us/power-automate/change-cloud-flow-owner

Need to test to make sure this works with the kit and our derived owners concept. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Flows)

AB#1568

**Comment by Jenefer-Monroe** [comment]
This does not work. The new owner is not surfaced to us programmatically. Marking as blocked by product team work

**Comment by Jenefer-Monroe** [comment]
sounds like this may be unblocked now. will test and see about funding

**Comment by hanuschkaih** [comment]
Great, looking forward to having this in place ;-)

**Comment by Jenefer-Monroe** [comment]
- [ ] Identifying and updating owner in sync flow
- [ ] identification of owner in the shared with flow
- [ ] - [ ] ability to update owner in helper flow
