### ISSUE TITLE
Issue in Admin | Sync Template v3 (Custom Connectors) workflow - The property 'content' must be of type JSON in the 'ParseJson' action inputs, but was of type 'application/octet-stream'.

### ISSUE THREAD

**Issue by Dharanya13** [microsoft/coe-starter-kit#3061]
The workflow fails with the error message, "The property 'content' must be of type JSON in the 'ParseJson' action inputs, but was of type 'application/octet-stream'." Can you please help fix the issue

![image](https://user-images.githubusercontent.com/100100197/175850074-c32746d4-ab91-4279-b580-c67b9a1d0bef.png)
<img width="967" alt="COE admin flow error" src="https://user-images.githubusercontent.com/100100197/175850189-16ffb32f-f6b5-4d25-89d7-5478927c0196.PNG">

**Comment by Jenefer-Monroe** [comment]
See also https://github.com/microsoft/coe-starter-kit/issues/2147
We are not able to repro this issue and will need information about the custom connector in place. Do you have information about it?

**Comment by Dharanya13** [comment]
Hi Jenefer,

Thank you for the quick reply.

I tried to check for the troubled custom connector but I couldn't see it in the custom connectors list in power automate

It is interesting because I logged in with power platform admin role and also I couldn't see it from the Power BI report

The user who created that connector has left the organisation. Is it something to do with his account disabled?

Can we please arrange a quick call and do the screen share to troubleshoot the issue?

Thanks

**Comment by manuelap-msft** [comment]
Closing out as no further action required from CoE kit team / no response received on the issue. Please let us know if you continue to face issues.
