### ISSUE TITLE
What happens when a project is created using ALM Accelerator for Makers app?

### ISSUE THREAD

**Issue by KodulkarNilesh** [microsoft/coe-starter-kit#3075]
### What is your question?

Hello,

What is expected when a Project is created using 'ALM Accelerator for Makers' app? 
1. An approval email should be triggered to admin? - No email received
2. A project(with name provided in the app)  should be created in Github?

![image](https://user-images.githubusercontent.com/63402109/176190365-c6c3a725-10ea-45b6-b7b2-35c8eeda6ed4.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20210521.1

**Comment by mikefactorial** [comment]
@KodulkarNilesh when a project is created an approval flow is started and sent to the administrator specified on setup of the app. The administrator needs to approve the project before the resources are provisioned e.g. GitHub workflows, environments etc.

**Comment by mikefactorial** [comment]
There's further details in this Docs page https://docs.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-components. Please note that there's no on going investment in the ALM Accelerator for Makers as we've shifted focus to the ALM Accelerator for Power Platform. While the latter doesn't provide full GitHub support we have it in our backlog to provide support. Feel free to use the ALM Accelerator for Makers as a reference for your own use for the time being.

**Comment by KodulkarNilesh** [comment]
> @KodulkarNilesh when a project is created an approval flow is started and sent to the administrator specified on setup of the app. The administrator needs to approve the project before the resources are provisioned e.g. GitHub workflows, environments etc.

As mentioned previously there is no email for admin. Which flow gets triggered?
