### ISSUE TITLE
Error running pipeline: Resource not found

### ISSUE THREAD

**Issue by KodulkarNilesh** [microsoft/coe-starter-kit#3076]
### Describe the issue

Hello,

I am getting below error when I am trying to deploy solution using 'ALM Accelerator for Power Platform' app
Error running pipeline: CustomAzureDevOps.RunPipeline failed: { "statusCode": 404, "message": "Resource not found" }

![image](https://user-images.githubusercontent.com/63402109/176194837-7891ec02-e2a9-41e5-b1af-890322cc00ed.png)

I am using solution from May 22 i.e. CenterofExcellenceALMAccelerator_1.0.20220503.1_managed.zip

### Expected Behavior

Based on the information provided while creating deployment profile, solution must get committed in Azure DevOps

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220503.1

### Anything else?

Followed this documentation to set-up ALM accelerator: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#document-structure

**Comment by KodulkarNilesh** [comment]
@mikefactorial , Pipeline exists with this name however no runs.
![image](https://user-images.githubusercontent.com/63402109/176631272-41fdd53d-d957-4cb8-9714-8238d5f76c89.png)

**Comment by mikefactorial** [comment]
@KodulkarNilesh thanks for providing the screenshot I can see that the export-solution-to-git pipeline has incorrect casing. Should be all lower case. That is likely the reason the App can't find the pipeline. The same is true for the delete-unmanaged-solution-and-components and the import-unmanaged-to-dev-environment pipelines.

**Comment by mikefactorial** [comment]
If changing the names of the pipelines to all lower case fixes the issue feel free to close this issue with a comment back. Thanks again.

**Comment by KodulkarNilesh** [comment]
Thanks. Changing the names to lower case fixed mentioned issue.
