### ISSUE TITLE
[ALM Accelerator - BUG]: error code 80041103 when importing ALM Accelerator

### ISSUE THREAD

**Issue by EricTaylorCoH** [microsoft/coe-starter-kit#3079]
### Describe the issue

I am getting a vague error number 80041103 when importing the CenterofExcellenceALMAccelerator solution (version 1.0.20220517.1, May Hotfix). 

I had previously installed and then uninstalled the solution. Now when I try to install, I get this error. 

Next, I went to a different environment and tried to install first the ALM Accelerator and then the COE Core components and received the same error. 

Has anyone seen this error before?
Is there a way to get more details of the error? 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

May22HF

**Comment by mikefactorial** [comment]
@EricTaylorCoH can't say I've seen that before and to be honest it's not a lot to go on. Since it is happening with multiple solutions in different environments you may need to work with MS Support on the issue. Are you able to install other solutions in those environments?

**Comment by EricTaylorCoH** [comment]
@mikefactorial So I tried again today and it installed. I can only guess that something happened when I first installed the solution that affected my account or our tenant. Maybe there was some sort of Power Platform issue that I didn't see that was affecting me. I will be mindful to look for that in the future. We are still a little new to Power Platform.

**Comment by mikefactorial** [comment]
@EricTaylorCoH thanks for the update. Will close this out for now.
