### ISSUE TITLE
[CoE Starter Kit - BUG] No description for Environment Variables

### ISSUE THREAD

**Issue by YvoValcon** [microsoft/coe-starter-kit#3082]
### Describe the issue

When I turned on the flows, the I need to fill in the Environment Variables. However when I try to do so (I tried in multiple environments), I dont know what to fill in where:

<img width="320" alt="CoE Bug Description" src="https://user-images.githubusercontent.com/97224137/176407581-99dc8297-1f6c-4f96-8554-91d5de4be85d.png">

As you can imagine, this makes it hard to fill in ;). Something else: what is exactly the difference between 
1) Command Center - Application Client ID
2) Command Center - Client Secret
3) Command Center - Client Azure Secret

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin - Set up the Admin - Command Center App

**Comment by Jenefer-Monroe** [comment]
We have seen a customer hit this once before and it was some transient product issue in their tenant that eventually went away on its own. Sorry we cannot assist with making them show up there in the Product UX as you have just hit some product bug. The solution itself does contain the descriptions.

However you can go update these elsewhere in the product. Once you install the solution you can update the env vars though
Here we describe a few different ways to do that: [How to update env vars](https://docs.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
