### ISSUE TITLE
[ALM Accelerator - Feature]: Solution Checker timeout prevention

### ISSUE THREAD

**Issue by rsantos00** [microsoft/coe-starter-kit#3087]
### Is your feature request related to a problem? Please describe.

When the solution is very big it might end up timeout during the Run Solution Checker task.
The error information is:
Starting: Run Solution Checker
==============================================================================
Task         : Power Platform Checker
Description  : Analyze solutions using Power Apps Checker endpoint
Version      : 0.0.77
Author       : Microsoft
Help         : [More Info](https://aka.ms/buildtoolsdoc)
==============================================================================
##[warning]Environment variable 'VSTS_PUBLIC_VARIABLES' exceeds the maximum supported length. Environment variable length: 40057 , Maximum supported length: 32766
VERBOSE: InProcBindingRedirect: 2 - looking to resolve assembly: Microsoft.PowerShell.ConsoleHost.resources, 
Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
VERBOSE: InProcBindingRedirect: 1 - looking to resolve assembly: Microsoft.PowerApps.Checker.PowerShell
VERBOSE: InProcBindingRedirect: 3 - looking to resolve assembly: Microsoft.PowerApps.Checker.Client
VERBOSE: InProcBindingRedirect: 4 - looking to resolve assembly: Microsoft.IdentityModel.Clients.ActiveDirectory
VERBOSE: InProcBindingRedirect: 5 - looking to resolve assembly: System.Management.Automation.resources, 
Version=3.0.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
VERBOSE: InProcBindingRedirect: 6 - looking to resolve assembly: Microsoft.Uev.Commands
Starting PowerApps Checker Analysis...
	RuleSet: Solution Checker
	Error Level: High
	Error Threshold: 0
##[error]Exceeded the max wait. Try running again with an increased SecondsBetweenChecks and MaxStatusChecks.
Finishing: Run Solution Checker

### Describe the solution you'd like

Increase the Timeout parameter or have the possibility to disable the Checker using AA4PP Canvas App

### Describe alternatives you've considered

DisableSolutionChecker = true in the variables of deploy-validation-solutionname

**Comment by mikefactorial** [comment]
This cropped up yesterday. 
![image](https://user-images.githubusercontent.com/42348035/187035423-000acf7d-e50f-4f9b-9f4d-4e5f77024e88.png)

**Comment by mikefactorial** [comment]
This appears to have been an interruption of the solution checker service. Hasn't been reported again. Closing for now as there's nothing more for the team to do here.
