### ISSUE TITLE
[CoE Starter Kit - BUG] Data issue in PowerApps Apps table 

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/coe-starter-kit#3092]
### Describe the issue

Hi Team,

We are seeing that apps which were created long back are getting added to PowerApps apps table in CDS now(most of the apps are created in teams environment).

Example: One of the app which was created on 6/10/2021 is added to table on 06/26/2022. Also, we have noticed that the record gets added repeatedly every now and then but we dont see any duplicate records in the table. 

We are facing this issue after we upgraded the COE toolkit to latest June version. Can you please help us to check why the records are getting added multiple times(no duplicates).

 Apart from Sync Template V3 (Apps) flow, which other flows add record to Powerapps Apps table?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin - Sync Template V3 (Apps)

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid I dont follow the what issue you are seeing. 

What is the issue you are trying to address? 
- Is the app created date is wrong? 
- Are there duplicate entries? 
-  What do you mean by they are getting added multiple times if there are no duplicates?

**Comment by Aparna-Mutalik** [comment]
Hi,

Please find my answers below:

1. App created date is showing correct.
2. There are no duplicate entries.
3. Example: If you see in the screenshot below, app created date is in 2020 for few but created on date(record created in dataverse Powerapps Apps table) is 2022. Last month these records were already in the table with last months date in created on column and now it is again added with created on date as this month. But there are no duplicates.
<img width="802" alt="Screenshot 2022-07-01 154733" src="https://user-images.githubusercontent.com/78213183/176887077-2d695ffd-870d-4c0b-b4af-22e2cc9f92a0.png">
 
If required we can have call and screen sharing so that we can explain you the scenario better. @ApoorvaKantale will connect with you for the call.

**Comment by ApoorvaKantale** [comment]
No . All types of apps Model Driven Apps ,Canvas Apps and SharePoint Form Apps

**Comment by Jenefer-Monroe** [comment]
ok I'm not sure what is happening for you, but unless you have some negative consequence for us to investigate, I'm not sure I can spend the cycles to figure it out. This is not something that other people see.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
