### ISSUE TITLE
[CoE Starter Kit - BUG] Template catalog app for adding templates

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#3096]
### Describe the issue

How can I add file on template catalog?

![template](https://user-images.githubusercontent.com/101250592/176692059-17c948a7-7217-496b-a4c5-6998cd15547f.jpg)

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Template Catalog

**Comment by Jenefer-Monroe** [comment]
Please see the setup documentation for the feature
https://docs.microsoft.com/power-platform/guidance/coe/setup-nurture-components#set-up-template-catalog
There is a section called **_Add your own templates to the Template Catalog_**

**Comment by JackSocini** [comment]
I just followed the documentation, but I cannot click on the template file column for add the resource...

**Comment by Jenefer-Monroe** [comment]
This is just the new product grid behavior. You click edit first and get to a live grid
![image](https://user-images.githubusercontent.com/89584709/176697734-f7599b3e-6b0e-4816-945e-076df45f71e6.png)

**Comment by Jenefer-Monroe** [comment]
Oh yep it looks like the product didnt make that part of it work end to end. 
You'll have to create yourself an app to do this. And we'll put it on our backlog. Its not a very highly used feature though so it wont be completely quickly.

**Comment by manuelap-msft** [comment]
Added this to the Nurture apps - Admin app (previously Video hub - Admin) and will go live in November.


![Image](https://user-images.githubusercontent.com/55705669/196754295-4356b6dc-8d06-481b-a5ed-2f85866d8ae6.png)
