### ISSUE TITLE
deploy-validation or build-deploy-validation

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#3097]
### Describe the issue

Hi everyone, 

I hope that you are doing well, @mikefactorial!
Working with the ALM tool I realized that when you name the yml files "build-deploy-etcetera" (as instructed in https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform) the export-to-git pipeline runs successfully and creates the 3 pipelines. Nonetheless, when opening a pipeline for example deploy-validation it looks for a yml file named "deploy-validation-SampleSolution" instead of "build-deploy-validation-SampleSolution", so I'm just wondering if the correct naming of the yml files is indeed "build-deploy-etcetera" or should be "deploy-etcetera"?

<img width="472" alt="image" src="https://user-images.githubusercontent.com/100951593/176699131-0d8d14cf-f874-43e4-b5db-49b08c8900a0.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/100951593/176700144-1dde5987-34b1-4d62-a7b9-06533c79f17c.png">

### Expected Behavior

Expect the pipeline to fetch **build-deploy-etcetera** and not **deploy-etcetera**. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

June 2022

**Comment by mikefactorial** [comment]
Hey @LizethRegules, doing well thanks :) The CoE CLI responsible for generating the pipelines pulls our build templates from our github repo. In that repo the files are named build-deploy-validation-SampleSolution.yml for example. When the CLI commits the pipeline YAML to your repo it renames it to deploy-validation-yoursolution.yml. So, what you are seeing is expected. The manual setup instructions don't necessarily match what the cli does, but the name of the really doesn't matter as long as the pipeline that consumes it points to the correct file.

That's some background and I understand the confusion. We should probably update the manual instructions to align with what the cli does, but in either case you should end up with working pipelines. 

Looking at your screenshot though it does appear that the pipeline wasn't fully setup or setup correctly. Was this a pipeline generated by the cli or one you were setting up manually? Wondering how it got into the state that I see in the screenshot.

**Comment by LizethRegules** [comment]
Glad to hear you are doing well :)
I renamed to deploy-validation / deploy-test / deploy-prod and everything works fine. I was not fully doing the manual configuration. So, I was only creating the .yml files and **NOT** creating the pipelines, that step was done on Update Deployment Settings step in the export-to-git pipeline. 
So, yes, I think it would be great if you could change in the documentation the names of the .yml files in the repo branch to be deploy-validation / deploy-test / deploy-prod instead of build-deploy. Just to avoid confusions. 

Have a great day!
