### ISSUE TITLE
[ALM Accelerator - QUESTION] Sharing ALM Accelerator app with the user

### ISSUE THREAD

**Issue by shree2905** [microsoft/coe-starter-kit#3098]
### What is your question?

How do I share the ALM Accelerator app with the citizen developers so they can only open the ALM App as maker experience and certain admins can open it as Advance makers.

I've created a AAD Security Group for citizen developers and assign them the **ALM Power App Access** and **Basic User** security roles and then I shared the ALM Accelerator app with this group. I've shared Maker Experience user settings by using the ALM Accelerator for Power Platform Administration app to this security group with **Read** and **Append** privileges. but this security group still able to see the advance maker and maker experience drop down and user can also trigger the pipeline through the ALM app without sharing the Azure DevOps service connections.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 2022

**Comment by mikefactorial** [comment]
@shree2905 the only way a user can see a deployment user settings record is if it is shared with them, if they have access to all records or when they launch the app for the first time they have no shared deployment user settings records and the app will create a record for them. Make sure your users do not have org level read access to the deployment user settings table and if they have a deployment user settings record that was created for them that you delete that record and only share the record you want them to have access to. This model follows standard Dataverse access permissions.

**Comment by mikefactorial** [comment]
Closing for now. Feel free to re-open if you have additional questions
