### ISSUE TITLE
[ALM Accelerator - BUG]: Page not found error when executing operations other than GetOrganizations

### ISSUE THREAD

**Issue by EricTaylorCoH** [microsoft/coe-starter-kit#3100]
### Describe the issue

When I try to test the ALM Accelerator API calls, the GetOrganizations call works but all of the others give a "Page not found" error. I also get this error obviously when I try to create anew Profile in the ALM Accelerator canvas app.

I have confirmed that the connection is an account that has MSDN level access to the Azure Devops Project

### Expected Behavior

Expect that any API call returns data other than Page not found 

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20220517.1

### Steps To Reproduce

1. Open CustomAzureDevOps Custom Connector test tab.
2. Select GetOrganizations
3. Select Test
4. Select the "AccountName" from the results
5. Open GetProjects
6. Enter the selected account name into the **organization** text box
7. Select Test

### Anything else?

<img width="346" alt="image" src="https://user-images.githubusercontent.com/97251886/176738427-85172c3a-0caf-4798-8407-1d6d4c3a7b97.png">

**Comment by mikefactorial** [comment]
@EricTaylorCoH this indicative of the credentials for the custom connector being incorrect or not set. You should be able to follow the instructions here to get the connector back in working order. Recommend deleting any already created connections associated with the custom connector after you update the credentials and test again. https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#configure-the-devops-custom-connector

**Comment by EricTaylorCoH** [comment]
@mikefactorial I have recreated the Secret. Recreated the connection. and reapplied the settings on the security page and updated the settings. Just to be sure, the resource URL should just be the GUID of the Azure DevOps permission and not a full URL?

**Comment by EricTaylorCoH** [comment]
So I tried using the swagger editor to test also but I cannot get the authorize to work. It is complaining about the redirect which makes sense as it is not an option in the list for the app registration. So then I added the uri to the app registration and it sends me to a power automate page that says "404 : there has been a disconnect"
<img width="322" alt="image" src="https://user-images.githubusercontent.com/97251886/176768170-1c3ecdec-9bce-49fc-a7ba-e78f7576639d.png">
<img width="349" alt="image" src="https://user-images.githubusercontent.com/97251886/176768961-d5325b0e-0d9f-4af0-93ca-2bbd3bd7f6b4.png">

**Comment by mikefactorial** [comment]
Can you verify that the azure devops org you're connecting to is not the enterprise version and also if this is an instance of azure devops that's been around a while that the backward compatible visualstudio.com domain is not enabled?

**Comment by mikefactorial** [comment]
One other potential issue is that devops must be in the same tenant as PowerApps. The custom connector won't work across tenants

**Comment by mikefactorial** [comment]
Thanks for sending this over @EricTaylorCoH. The third party application Access via OAuth could be the culprit since this is how the connector connects to your projects. Here's our settings in our test environment for reference

![image](https://user-images.githubusercontent.com/42348035/177190074-e0374023-895e-49d5-a813-e7120968ab7d.png)
![image](https://user-images.githubusercontent.com/42348035/177190074-e0374023-895e-49d5-a813-e7120968ab7d.png)

**Comment by EricTaylorCoH** [comment]
I updated my settings to be the same as what you posted. I tried yesterday and again today (in case of caching or something) and no luck still. 
The page it is referring to with the page not found I assume is this one: https://global.consent.azure-apim.net/redirect? 
I wonder if our tenant has some other page in the way (if we can ever do this)? We are mid migration from an old AD on-prem domain to an updated one that aligns with Azure AD better. And we also had some weird authentication routes enabled (STS?). I think I will talk to our security team to see if they can help. 
This is definitely something on my end causing this i just don't know what.

**Comment by mikefactorial** [comment]
Thanks for the update @EricTaylorCoH. Let me know if there's anything I can assist with. Might be worth setting up a free instance of Azure DevOps and maybe a trial of Power Platform and trying the setup in that tenant to see what the difference might be. Though that's a lot of extra effort.

**Comment by alanrroberts** [comment]
Sadly I am having this same issue since updating to the July release.  Was working fine with the previous release so I'm not sure what has changed. I am using the same Client ID and Secret.  I've also tried regenerating a new secret.

**Comment by alanrroberts** [comment]
Just to add, I created a new custom connector and copied the Swagger YAML over from the original CustomAzureDevOps one.  Using the same client credentials the new one works for everything EXCEPT GetOrganizations.  So it is the exact opposite.  This suggests to me that there must be some subtle differencing in the way calls with and without parameters need to be handled...?

**Comment by alanrroberts** [comment]
I've just realised that the cat_5Fcustomazuredevops_policytemplateinstances.json I see in my export is different from what is in the repo.  I'm not sure if that is expected or not.? My export looks like this (so missing the x-ms-apimTemplate-operationName prop). 

```[
    {
        "templateId": "dynamichosturl",
        "title": "Set host to https://vssps.dev.azure.com",
        "parameters": {
            "x-ms-apimTemplateParameter.urlTemplate": "https://vssps.dev.azure.com"
        }
    },
    {
        "templateId": "dynamichosturl",
        "title": "Set host to https://app.vssps.visualstudio.com",
        "parameters": {
            "x-ms-apimTemplateParameter.urlTemplate": "https://app.vssps.visualstudio.com"
        }
    },
    {
        "templateId": "convertobjecttoarray",
        "title": "Convert Build Definition Variables to Array",
        "parameters": {
            "x-ms-apimTemplateParameter.propertyParentPath": "@body().value",
            "x-ms-apimTemplateParameter.propertySubPath": "variables",
            "x-ms-apimTemplateParameter.newPropertyPath": "@item().variables",
            "x-ms-apimTemplateParameter.keyName": "key",
            "x-ms-apimTemplateParameter.valueName": "value",
            "x-ms-apimTemplate-policySection": "Response"
        }
    }
]```

So now I'm confused and don't know if this is expected or something going quirky with the upgrade.

**Comment by mikefactorial** [comment]
Strange. Can you try checking the custom connector policies in the environment and updating the operation to see if that fixes it? I have seen the custom connector designer wipe that field when editing in the past for unknown reasons.

![image](https://user-images.githubusercontent.com/42348035/177799331-18ede476-ef20-4c1b-a0fc-92bc1250118c.png)

**Comment by mikefactorial** [comment]
Those policies obviously control the endpoint that the api exists on so 404 would make sense since all of the other calls are made to https://dev.azure.com/_apis while the GetOrganization and GetIdentities have different endpoints.

**Comment by mikefactorial** [comment]
Seems to be something quirky with the custom connector UI that is wiping out those values on edit. You may find that the cached credentials timeout at some point and you'll start getting errors again. In that case you'll need to go back in and update security on the custom connector again. Would double check the policies again if you need to do that. Closing for now. Thanks @alanrroberts for investigating and for posting the resolution. This will certainly help someone else in the future.

**Comment by EricTaylorCoH** [comment]
@mikefactorial So this update from @alanrroberts post has inspired me I guess. I had the same issue. I had to set the app.vssps.visualstudio.com policy to apply only to GetOrganizations. I am able to run the other operations after setting GetIdentities to the vssps.dev.azure.com policy. 

<img width="351" alt="image" src="https://user-images.githubusercontent.com/97251886/177818055-47a230f0-cdd2-4187-8612-a52faa860d99.png">

**Comment by mikefactorial** [comment]
Thanks for following up @EricTaylorCoH. Guess I lost track of the original issue submitter :) but great to hear that there's a fix for both of you.
