### ISSUE TITLE
[ALM Accelerator - BUG]: Cannot insert duplicate key during Solution Import

### ISSUE THREAD

**Issue by LukasSchauffele** [microsoft/coe-starter-kit#3101]
### Describe the issue

I am pretty sure this is a product issue but I wanted to post here regardless.

Every so often, the build and deploy pipeline fails at the _Import Managed Solution as Update_ step. I've attached the complete error log here - [import_managed_solution_error.log](https://github.com/microsoft/coe-starter-kit/files/9026717/import_managed_solution_error.log). The issue seems to be with a unique key violation of an environment variable:

```log
Error: Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: Cannot insert duplicate key exception when executing non-query: System.Data.SqlClient.SqlCommand Exception: System.Data.SqlClient.SqlException (0x80131904): Violation of UNIQUE KEY constraint 'ndx_envvarval_schemaname'. Cannot insert duplicate key in object 'dbo.EnvironmentVariableValueBase'. The duplicate key value is (bis_BusinessCentralInstance, 0, Jan  1 1900 12:00AM).
The statement has been terminated.
```

Is it trying to re-create the environment variable definition of an existing environment variable or is it trying to set the value of an existing environment variable?

A simple workaround is to go into the target environment, delete the environment variable value and then re-run the pipeline. This is a non-issue in non-production environments but I am hesitant to do this in Production. _I'm still not sure if flows referencing environment variables need to be turned off and on again for the new value to take effect?_

I haven't been able to spot a pattern. This issue has popped up across different downstream environments. It seems quite random; for example: in the span of a few hours I can do a first deployment without issues, then a second one will fail despite not having made any changes to environment variables.

Has anyone come across this before?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

June 22

### Steps To Reproduce

Deploy solution update with environment variable to an environment which already has the environment variable value set.

**Comment by mikefactorial** [comment]
@LukasSchauffele following up on this. There's been some updates related to the build tools in recent days. Wonder if this is related. https://github.com/microsoft/powerplatform-build-tools/discussions

**Comment by LukasSchauffele** [comment]
Hi @mikefactorial - I don't believe it has anything to do with the new version of the build tools. I've been having this issue for a while (but not major enough to actually do anything about it...)

I'll open a ticket with MS support. If they find anything I will post an update here. I'll close the issue for now. Thanks for you help.
