### ISSUE TITLE
[ALM Accelerator - BUG]: The pipeline is not valid

### ISSUE THREAD

**Issue by KodulkarNilesh** [microsoft/coe-starter-kit#3104]
### Describe the issue

Hello,

I am getting below error when I try to commit solution using 'ALM Accelerator for Power Platform' app. I have created service connections for the respective environments mentioned in deployment profile. I have verified variables in respective pipelines and created branch policies according this [documentation](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#setting-branch-policies-for-pull-request-validation): 

![image](https://user-images.githubusercontent.com/63402109/176877058-f8381527-289f-4a1c-a9c5-b397946b5866.png)

### Expected Behavior

Solution should be committed in DevOps 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220503.1

### Steps To Reproduce

1, Select solution and create profile
![image](https://user-images.githubusercontent.com/63402109/176877407-49b5e003-4d9f-4abd-b241-c902c47f8f52.png)

![image](https://user-images.githubusercontent.com/63402109/176877607-63f8bfa3-e963-4612-8225-985a146373ed.png)
2. Create pipelines and service connections as per [documentation](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-pipelines-for-import-delete-and-export-of-solutions)
3. Click 'Commit solution' on canvas app.

**Comment by mikefactorial** [comment]
@KodulkarNilesh I have a hunch. The pipelines are very specific about the naming of the service connections down to the trailing forward slash in the url. Double check that your service connection name includes the trailing forward slash.

**Comment by mikefactorial** [comment]
Can you check this setting on your service connections?
![image](https://user-images.githubusercontent.com/42348035/176896152-e5940a3f-7730-497e-9779-1095a6407fc6.png)

**Comment by KodulkarNilesh** [comment]
Yes...this is how it looks like for all service connections

**Comment by KodulkarNilesh** [comment]
is 'CdsBaseConnectionString' value correct? I am referring to last part of the value i.e. **Url=**
![image](https://user-images.githubusercontent.com/63402109/176902279-c06a3aa1-ba1e-4d7d-8d80-80bc78a481d8.png)

**Comment by KodulkarNilesh** [comment]
In my case service connection to the environment in which unmanaged solution exists was missing.
