### ISSUE TITLE
Innovation Backlog App - Complexity Score - how calculated?

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#3105]
### What is your question?

Hello @Jenefer-Monroe @manuelap-msft,

Hope both of you are doing well! 
I was wondering if there is a way of knowing how is the **_complexity score_** being calculated? 
I tried taking a look inside the app in Edit mode, but couldn't quite figure it out, between so many variables and formulas :)
Just to be clear, I mean the value that appears inside the circle besides Complexity label. 
<img width="199" alt="image" src="https://user-images.githubusercontent.com/100951593/176913894-f946dd19-8aeb-4509-b761-8891a017907d.png">

Thank you in advance!

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

N/A

**Comment by Jenefer-Monroe** [comment]
It is complicated for sure, I hope the below helps. Please let me know.

You can see visually what elements are used by going to this page of the idea creation
![image](https://user-images.githubusercontent.com/89584709/176925108-0f85578a-0369-47a2-85f0-1e168646fe65.png)

The calculation is via this calculated column in the Backlog Item Complexity table
![image](https://user-images.githubusercontent.com/89584709/176926184-ef6a454d-1138-4ff5-8bc9-53e240b7b001.png)

Then each multiplier has its own calculated column. For example if the solution needs to use files, that yes/no is in a field which is referenced by its Multiplier calc column
![image](https://user-images.githubusercontent.com/89584709/176926845-63a92c1c-7331-4fec-8fee-6002f511f844.png)
![image](https://user-images.githubusercontent.com/89584709/176926991-c6d00221-4f50-4eb5-bfca-06f690b6245d.png)


Lastly, if you have multiple repros for an idea (as shown here) its an average of the complexity of the team repros
![image](https://user-images.githubusercontent.com/89584709/176925924-20321b20-b88c-4939-8586-ff93b76e6b10.png)
