### ISSUE TITLE
[CoE Starter Kit - QUESTION] What makers can see on admin view?

### ISSUE THREAD

**Issue by JackSocini** [microsoft/coe-starter-kit#3106]
### What is your question?

Hello,
is it possible to access the admin view by a maker, and what if you see?
Exemple: does he only see apps, flows and environments shared with him? Or?

Thanks

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
We do not support any row level security out of the box with the kit. So if you share the app with a maker (meaning they have the Maker SR), they will see the same thing as an admin as they have mostly the same read permissions
