### ISSUE TITLE
[CoE Starter Kit - Feature]: looking for CEO kit installation demo

### ISSUE THREAD

**Issue by vidhyakotian** [microsoft/coe-starter-kit#3109]
### Describe the solution you'd like

looking for CEO kit installation demo

**Comment by Jenefer-Monroe** [comment]
Here is our old playlist for setting up the starter kit
https://www.youtube.com/playlist?list=PLi9EhCY4z99W5kzaPK1np6sv6AzMQDsXG

We have a new version getting released there in a few weeks, so subscribe to the channel and you will see a new version soon.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
