### ISSUE TITLE
[ALM Accelerator - BUG]: Error 203 Custom Connector - CustomAzureDevOps

### ISSUE THREAD

**Issue by mknalves** [microsoft/coe-starter-kit#3111]
### Describe the issue

Hi everyone!
I've got the error 203 when I try to use the CustomAzureDevOps custom connector. I've tried the steps suggested by [kallisto08](https://github.com/kallisto08) on this issue https://github.com/microsoft/coe-starter-kit/issues/2202, but no success. Any other suggestions to fix it?

<img width="814" alt="image" src="https://user-images.githubusercontent.com/49026459/177142388-d543a911-88d9-47f1-96cf-ccda628b5a54.png">

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

latest

**Comment by mikefactorial** [comment]
@mknalves Looks like an issue with the oAuth security configuration. See https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#configure-the-devops-custom-connector for more information

**Comment by mknalves** [comment]
Hi [mikefactorial](https://github.com/mikefactorial)
Thanks for the quick reply! I've done this process many times, but with no success.
The redirect URL was generated properly.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/49026459/177196904-8ec6cad4-f503-4704-bd6f-f779f37a9513.png">
One more info, I have the ALM Accelerator installed on another environment using the same credentials, same tenant. There it's working fine, but on this new one, no. Any other suggestion?
Thanks!

**Comment by mikefactorial** [comment]
The fact that the response is showing the login page for AzDO means this is an auth issue. So a couple of questions. Does the user who created the connection have access to AzDO? Have you tried deleting and recreating the connection after updating the security credentials?

**Comment by mikefactorial** [comment]
Other than those specific questions. Are you sure that the credentials you are putting in security are correct? That's all I can think of that would cause an auth issue like the one you're experiencing.

**Comment by mikefactorial** [comment]
Awesome! Closing this out.
