### ISSUE TITLE
[ALM Accelerator - BUG]: Update Deployment Settings - ##[error]PowerShell exited with code '1'

### ISSUE THREAD

**Issue by KodulkarNilesh** [microsoft/coe-starter-kit#3114]
### Describe the issue

Hello,

'export-solution-to-git' pipeline is failing with error shown in below screen shot.
I have opted to do manual set-up of ALM accelerator.
![image](https://user-images.githubusercontent.com/63402109/177164204-996431d6-a6d7-43d9-915c-bf29cfac7ac3.png)

error: ﻿{"$id":"1","innerException":null,"message":"A potentially dangerous Request.Path value was detected from the client (:).","typeName":"System.Web.HttpException, System.Web","typeKey":"HttpException","errorCode":0,"eventId":0} {"statusCode":400}

### Expected Behavior

Solution should be committed in DevOps

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220503.1 
1.0.20220517.1

### Steps To Reproduce

1, Select solution and create profile
2. Create pipelines and service connections as per [documentation](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-pipelines-for-import-delete-and-export-of-solutions)
3. Click 'Commit solution' on canvas app.

### Anything else?

I have checked previously reported issues:
https://github.com/microsoft/coe-starter-kit/issues/2477
https://github.com/microsoft/coe-starter-kit/issues/2911

AB#1127

**Comment by mikefactorial** [comment]
Tagging @jenschristianschroder who has seen this issue previously.

**Comment by mikefactorial** [comment]
@KodulkarNilesh wondering if you can assist in troubleshooting this issue with us. I've created a branch of the coe-cli (where the error you are seeing is coming from) here https://github.com/microsoft/coe-starter-kit/tree/mochs-aa4pp-3114. If you modify this file in your template repo https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/PowerShell/update-deployment-settings.ps1 and change the following line it will pull the branch I created https://github.com/microsoft/coe-alm-accelerator-templates/blob/19cb59f26fe6cdadb2e2932de5865c344cd30a01/PowerShell/update-deployment-settings.ps1#L281.

I've added some logging in that branch that may be helpful in tracking down the specific issue.

Change 
            git clone -b "main" "https://github.com/microsoft/coe-starter-kit.git"
To
            git clone -b "mochs-aa4pp-3114" "https://github.com/microsoft/coe-starter-kit.git"

**Comment by KodulkarNilesh** [comment]
@jenschristianschroder , In my opinion, changing the URL to new URL has impact on other activities/projects/teams on Azure DevOps. If thats the case I would prefer to wait until "generic" solution is released. Please share your thoughts.
