### ISSUE TITLE
[CoE Starter Kit - Feature]: Update manager orphan flows to include information about solutions

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#3115]
### Is your feature request related to a problem? Please describe.

today if a flow is orphaned it goes to the former manager to clean up
unfortunately if the flow is part of a solution we cant actually do the clean up if its a delete
and if its an assign we might not be assigning all correctly as we dont tell the manager where the flow lives logically (which soln)

### Describe the solution you'd like

now that (as of August 2022) we know the solution flows belong to we should let the manager know that too.

**Comment by Jenefer-Monroe** [comment]
going to see if the error progogation work does it for us by itself. So moving this to backlog.

**Comment by Jenefer-Monroe** [comment]
Error propogation does mitigate. Going to go ahead and close this one out now and can return if we get feedback

**Comment by LakshmanChand** [comment]
@Jenefer-Monroe @manuelap-msft, we have recently enabled Orphan components. Managers have taken action to delete the Orphan apps. As they are part of managed solution, the delete action on these apps/flows failed and they are being notified during the next schedule. Please advise how can we address this. 
My thoughts:
1. There is an action to mark the item as Delete. Is it possible to add a new column to PowerApps Apps table and update it as "managed-solution-component" through a parallel action.
2. A report that can help to list down all these failed to delete managed-solution-components and reach-out to them separately.

**Comment by manuelap-msft** [comment]
I've added your comment as a new feature ask here https://github.com/microsoft/coe-starter-kit/issues/4834 for us to track.

**Comment by Jenefer-Monroe** [comment]
I'll close this one back out so we dont have duplicate work items
