### ISSUE TITLE
[CoE Starter Kit - QUESTION] Deleted apps are not deleted from the Dataverse table

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#3118]
### What is your question?

I deleted a canvas app that I created in Power Apps, but it doesn't remove it from the Power Apps App table in Dataverse.

Is it a CoE StarterKit specification that the canvas application once synchronized with the Dataverse table is not reflected in the Dataverse table even if it is deleted on the cloud?

Or will the deleted app change any specific parameters?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Admin - Sync Template v3

**Comment by Jenefer-Monroe** [comment]
There are flows who's purpose is to do this clean up. 

Please revisit the [inventory setup instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) and ensure all the flows listed are turned on and running. 

In particular, this flow and its helpers are what cleans up deleted objects from the inventory: **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_**

**Comment by sudadakkota** [comment]
Thank you!
I ran the flow manually and confirmed that the app was removed from the Dataverse table.

I feel that the execution cycle of this flow is a few set to 2 weeks, but is there any reason for setting it to 2 weeks?

**Comment by Jenefer-Monroe** [comment]
This can be a very long running flow and so we set it to two weeks for our large organizations

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
