### ISSUE TITLE
[CoE Starter Kit - BUG] CoEDashboard can not be opened since last update

### ISSUE THREAD

**Issue by BZalezak** [microsoft/coe-starter-kit#3121]
### Describe the issue

Hi,

Recently we updated our CoE starter kit to the latest version (June). We successfully imported the solution components, but the related pbit files does not seem to work properely. 
By opening Production_Dashboard_May2022.pbit (which is in the release) we are adding our ORG URL. After that we recieve the following error message:
![errormessage](https://user-images.githubusercontent.com/108741406/177343164-729171c4-e579-4a87-882a-519fe1cc4057.png)
By checking it in Azure Activity Logs we were managed to identify a possible rootcause. It seems that PowerQuery for Excel app registration could be missing:
![activitylog](https://user-images.githubusercontent.com/108741406/177344712-3ff326f5-c60a-4724-93e8-c595793b7f4b.png)
Previously we didn't experience such issues. Is this error message valid? Could you please provide some kind of explanation what is changed in the reports?

Thanks in advance.

Balint

### Expected Behavior

We should be able to open and publish the Power BI reports contained in the release.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Production_Dashboard_May2022.pbit

### Steps To Reproduce

Upgrade to the lastest CoE starter kit
Try to open pbit files
Error pop-up

**Comment by Jenefer-Monroe** [comment]
Hello, this issue is with PBI itself, and not our template file. 

My recommendation is to get a repro outside of the CoE and approach a PBI expert in your org, or support. 

To get a repro:
- Boot PBI
- Home > Data > Dataverse
![image](https://user-images.githubusercontent.com/89584709/176449586-ab2e0b9d-9262-4f6e-b601-3cd352d7659d.png)
- Click the carrot next to your CoE environment in the Navigator > select some table > Load
![image](https://user-images.githubusercontent.com/89584709/177354364-68ef18da-6c4a-474e-bf2b-0d4859cf9b26.png)

**Comment by manuelap-msft** [comment]
Hello,

you've blurred out part of this so unsure if this is the issue but when you enter the URL, make sure you enter it with https at the beginning and not http. So http**s**://orgname.crm.dynamics.com. We often see auth issues when users enter the URL with just http.

Hope that helps,
Manuela

**Comment by BZalezak** [comment]
Hi,

We tried to add the org url multiple ways. With https, or without the prefix/sufix, but it did not worked out. Does the new pbit file utilize somehow Power Query for excel which was not the case before? 
Also, I see thet the June release does not contain the pbit files, only the "normal" release which can be downloaded from here: 
https://aka.ms/CoEStarterKitDownload
Is it even necessary to re-publish these pbit files? The previous, already published reports stopped working after the update.

**Comment by Jenefer-Monroe** [comment]
There was no change or add to use Excel features. 
For June we just re-released the May PBIT because there were no changes but we often re-release the PBIT because we add new features (ex start tracking BPFs)
Please try to connect to Dataverse without our PBIT as I showed above

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
