### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Audit Logs - Keeps warning about chunking size

### ISSUE THREAD

**Issue by kashanico** [microsoft/coe-starter-kit#3123]
### Describe the issue

I keep getting warning emails about CoE Audit Logs being missed and to reduce interval. I've gone from the default 1hr to 30mins, 15mins, to 5mins and it's still complaining about the audit log sizes.

Subject: CoE Audit Logs - Missing some logs - require smaller chunks

Your audit logs were collected but some were missed due to truncated results in [this run ](XXXXXX). 
You will need to use a smaller interval to gather all logs. 
Current chunking size: 5 Minute 
See the optional Step 11 of our [Audt Log flow setup documentation ](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow)for more details.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

Reduce the TimeInterval-Interval variable
Keep getting the audit log size issue

**Comment by Jenefer-Monroe** [comment]
You can try down to 1 minute chunks, but if your tenant is too busy for the custom connector, then you will have to use the upcoming Self Service Analytics feature to gather. 

Here are some details, we do not yet support this with the Starter Kit today but do have plans to integrate this fall.  

https://docs.microsoft.com/power-platform/admin/self-service-analytics
https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by kashanico** [comment]
Reduced the size to 1mins and just got the same warning with the new setting


Subject: CoE Audit Logs - Missing some logs - require smaller chunks

Your audit logs were collected but some were missed due to truncated results in [this run ](XXXXXXXXX). 
You will need to use a smaller interval to gather all logs. 
Current chunking size: 1 Minute 
See the optional Step 11 of our [Audt Log flow setup documentation ](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow)for more details.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
