### ISSUE TITLE
ALM Accelerator - Commit solution failed to trigger export-solution-pipline

### ISSUE THREAD

**Issue by bhatiarahul1993** [microsoft/coe-starter-kit#3132]
### What is your question?

Hi,
I am trying ALM accelerator and I am unable to commit the solution to git repo. Below is the screenshot of error message.

![image](https://user-images.githubusercontent.com/35290041/177591981-bc7126f4-3210-41a9-904b-9e85cc7dd847.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220630.1

**Comment by mikefactorial** [comment]
@bhatiarahul1993 this looks like you may have pulled the latest pipelines, but not the latest solution. Can you verify if you've installed the ALM Accelerator solution from the release today https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-July2022?

**Comment by bhatiarahul1993** [comment]
@mikefactorial,  it worked after installing the latest version of ALM ACCELERATOR  SOLUTION. 
Thank you

**Comment by mikefactorial** [comment]
Thanks for reporting back. Closing this out for now.
