### ISSUE TITLE
[CoE Starter Kit - BUG] "Failed to import" when updating Core Components solution

### ISSUE THREAD

**Issue by ryanwalker726** [microsoft/coe-starter-kit#3136]
### Describe the issue

Trying to update the Core Components solution for the first time (from a much older version to the current v3.4) and getting the below errors...  Looks like it can't delete my old solution because of the existing connections that are in place.  Not sure how to 'gracefully' transition these to the new solution...  Do I need to delete these references in the old solution manually?

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 10 

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: e6e87d68-acfa-4e7e-998b-4c8444f5221b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments, Id: 708e4fc8-5e23-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: 24501793-24da-412b-9b2d-5225d648610e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Start Approval for Apps), Id: d740e841-7057-eb11-a812-000d3a9964a5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: 24501793-24da-412b-9b2d-5225d648610e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Clean Up and Delete), Id: 78466552-7e56-eb11-a812-000d3a996adc, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoEv3SyncTemplatesUsers, Id: 22387386-65b9-4877-bf3a-6fb660d77ae7, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Start Approval for Flows), Id: 7e68d839-0556-eb11-a812-000d3a996adc, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: a49cab7a-9b2c-4264-91a6-8466100aa19e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Start Approval for Flows), Id: 7e68d839-0556-eb11-a812-000d3a996adc, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: a49cab7a-9b2c-4264-91a6-8466100aa19e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Clean Up and Delete), Id: 78466552-7e56-eb11-a812-000d3a996adc, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoEAuditConnection, Id: 2e9e82bf-c4ea-47aa-aa98-9815d5ba4dfa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEAuditConnection, Id: 202a0350-bb9e-46a2-8b31-dd07304a3e2a, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEConnection, Id: 62646efe-0da1-423b-99ed-fa29ef8e39f1, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEConnection, Id: 62646efe-0da1-423b-99ed-fa29ef8e39f1, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Archive and Clean Up v2 (Check Approval), Id: 6c0522f0-6256-eb11-a812-000d3a996adc, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

### Expected Behavior

Trying to uninstall the old version of the Core Components solution after installing the latest version.  

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1. Import solution
2. Select *.zip
3. Click "Upgrade"
4. Wait for process to import solution 
5. Receive error message

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
