### ISSUE TITLE
[Power BI report-CoEDashboard_June-2022] I have two environment QA and Prod in both environment Env , bot , bot maker, Total app maker and desktop flow count is not same?

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#3137]
### What is your question?

In Power BI report both environment showing different count both environment updated with same version latest June 2022 
All Sync and helper flow is running on both environment without in failure  

Prod

![image](https://user-images.githubusercontent.com/30046543/177696635-a604550e-19d4-4d02-8ce4-a02c3d436e57.png)

QA

![image](https://user-images.githubusercontent.com/30046543/177696812-04022f69-0983-4030-a5f1-6e254e837101.png)

Please suggest

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022 - CenterofExcellenceCoreComponents_3.39_managed

**Comment by Jenefer-Monroe** [comment]
You will need to do some research here to find the differences between these. 
And with that we can try to see if it there is a bug, or if its just timing (flow x has run here but not there today, etc)
Likely this is just a timing issue.

**Comment by sharmajitendralal** [comment]
I have done my research and did not found any major gap in timing

I have also trigger all cleanup and helper flow manually but did not get any difference in report

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
