### ISSUE TITLE
ALM Accelerator -  Azure DevOps self hosted agents for ALM  accelerator pipeline

### ISSUE THREAD

**Issue by bhatiarahul1993** [microsoft/coe-starter-kit#3140]
### What is your question?

Do we have any script/or document to configure Azure DevOps self hosted agents for ALM  accelerator pipelines ? I want to know what all tools we need to install in Azure DevOps self hosted agents machines to make ALM accelerator pipelines work sucessfully. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220630.1

**Comment by mikefactorial** [comment]
@bhatiarahul1993 adding @jenschristianschroder who has setup self-hosted agents previously and could provide some details. We don't have any official docs on this currently.

I can tell you that we leverage both powershell for windows and powershell core in our pipelines so both would be required in your self-hosted agent and would require a windows environment. Apart from that there are no special requirements I can think of but @jenschristianschroder may have more details.

**Comment by bhatiarahul1993** [comment]
Thank you @jenschristianschroder
