### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by MelanieCamden** [microsoft/coe-starter-kit#3143]
### Describe the issue

Error Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '91936ab5-f4e3-46f9-9218-b19d6981b5e8'. Connection '/providers/Microsoft.PowerApps/apis/shared_powerplatformforadmins/connections/399d4dcd3a604439ae5c1bc3d1443e92' to 'shared_powerplatformforadmins' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}". Received wirh trying to TURN ON the clean up admin flow

### Expected Behavior

for the flow to be turned on

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19.1

### What app or flow are you having the issue with?

corecomponents teams workflows

### Steps To Reproduce

Trying to set up the COE on a MS team environment 
Team called Power Platform COE

Account has E5 licence and Power platform assigned  

### Anything else?

https://make.powerapps.com/environments/3f5102c7-2dee-ef46-9e04-55a5f2cdf441/solutions/ea37b061-4626-4715-b0bc-36194c99216
![Capture](https://user-images.githubusercontent.com/108744266/177751549-d0e9897b-8ab8-44b2-8e5c-8f379516ed0e.PNG)
[CenterofExcellenceCoreComponentsTeams_3_19_1_managed.zip](https://github.com/microsoft/coe-starter-kit/files/9062665/CenterofExcellenceCoreComponentsTeams_3_19_1_managed.zip)
7

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
