### ISSUE TITLE
[CoE Starter Kit - BUG] Download CoE solution missing Core component

### ISSUE THREAD

**Issue by KiraXie2** [microsoft/coe-starter-kit#3144]
### Describe the issue

[https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#download-the-solution](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#download-the-solution)
CenterofExcellenceCoreComponents_x.xx_managed.zip is missing "Admin | Sync Template v3 (Business Process Flows)".

### Expected Behavior

[https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#download-the-solution](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#download-the-solution)
CenterofExcellenceCoreComponents_x.xx_managed.zip SHOULD contain the "Admin | Sync Template v3 (Business Process Flows)"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Business Process Flows)

### Steps To Reproduce

1. Click to Download the solution (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#download-the-solution)
2. Open zip file, locate file 'CenterofExcellenceCoreComponents_x.xx_managed.zip' and open. You will see "Admin | Sync Template v3 (Business Process Flows)" is not included.

**Comment by manuelap-msft** [comment]
Hello,

when did you download the .zip file?

We released a new version yesterday which introduced this new flow, and the version you should be seeing is 3.40 and not 3.39
![image](https://user-images.githubusercontent.com/55705669/177777909-dd5e95b5-d09e-4c4f-a410-d16d689db44e.png)

**Comment by KiraXie2** [comment]
Hello,
I downloaded this zip file on Tuesday (7/5). May I know how I can resolve this issue now?

**Comment by manuelap-msft** [comment]
Hello,

you'll have to re-download the .zip file and follow our upgrade instructions to upgrade the version to 3.40: https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
