### ISSUE TITLE
[CoE Starter Kit - BUG] Column name is typo in admin_portal table

### ISSUE THREAD

**Issue by kaminagi107** [microsoft/coe-starter-kit#3147]
### Describe the issue

In the [Power Apps Portal (admin_portal)] table, the column name that should be written as [Portal is Orphaned] is [Portal is Ophaned].
I also found the typo [admin_portalisophaned] in the internal name.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

None

### Anything else?

https://github.com/microsoft/coe-starter-kit/blob/2c4a8489c561527af35aee32344774d59108c798/CenterofExcellenceCoreComponents/SolutionPackage/Entities/admin_portal/Entity.xml#L822

**Comment by Jenefer-Monroe** [comment]
Hello we cannot change the internal name, those typos are unfortunately something we will have to live with. 
In the July release you will also see the display name has changed to match the [new branding for Portals to Power Pages](https://docs.microsoft.com/power-pages/difference-portals)
![image](https://user-images.githubusercontent.com/89584709/177998815-d8e53f8c-6554-4894-a48c-f0f5fc0cbc86.png)

Thanks for using CoE

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
