### ISSUE TITLE
[CoE Starter Kit - BUG] Can't Search by AppID in Power Platform Admin View

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#3148]
### Describe the issue

When I try to search for an App or Flow with a specific ID search returns nothing?

![image](https://user-images.githubusercontent.com/48433526/177930335-ffd93030-c15d-4315-80a5-ee61ca383bc5.png)

It would be nice if you could search by the App or Flow ID as this is often used in a SharePoint webpart or other areas.

### Expected Behavior

Return all apps with the ID that you have searched for...

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
You can do this by using the filter on the AppIDString column. 
Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
