### ISSUE TITLE
[CoE Starter Kit - BUG] App Catalog - Grant Access not working

### ISSUE THREAD

**Issue by KishoreJagan83** [microsoft/coe-starter-kit#3156]
### Describe the issue

Once Maker raise Request Access for an App, Owner will receive an Adaptive card with option to Grant Access / Reject.

If the owner selects Grant Access , Maker will receive an email along with the App(Maker Requested app) link for access.
But when Maker clicks the App link it still shows 'You don't have access to this app'.
Also verified the Particular app in their Environment manually whether share option include the Maker . For few cases it includes but in few cases it doesn't include under share. Neither case App is not able to access from the mail or Launch app functionality.

Not sure why this Grant Access functionality is not working.
![image](https://user-images.githubusercontent.com/43986892/178037784-42cfd908-5d7e-4eae-9b79-d213d5faa0f1.png)

![image](https://user-images.githubusercontent.com/43986892/178038093-f733dbac-d5ae-41ec-8bd0-3d0955c4a12a.png)

### Expected Behavior

Once Maker clicks the App link from the mail , he/ she should able to access it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

App  Catalog

### Steps To Reproduce

Open App Catalog App
Maker Request access for a particular app
App Owner will receive Adaptive card with option to Grant Access / Reject
Maker receives Grant Mail access along with  Requested access App link in the email
Click the link and check for access

**Comment by KishoreJagan83** [comment]
Flow trigger is not quite consistent, even though all the connections are in tact

**Comment by Jenefer-Monroe** [comment]
There is a bug in the kit right now in which the condition statement in the flow lost its left operand
https://github.com/microsoft/coe-starter-kit/issues/3139

From your statements it sounds like you might also be having trouble with the [Run only permissions](https://docs.microsoft.com/power-platform/guidance/coe/faq#set-flow-run-only-users-properties), please see if those are set

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
