### ISSUE TITLE
[CoE Starter Kit - Question] Upgrade from version of last year failed

### ISSUE THREAD

**Issue by ANInnoSolutions** [microsoft/coe-starter-kit#3159]
### Describe the issue

As Is: By upgrading to the newest version of CoE Starter Kit (June 2022) for PowerPlatform I'm missing some Cloud-Flows inside the Core Solution ("Core Components") with the following name:
- Admin | Sync Template v3 CoE Solution Metadata

To Be: After upgrading to the newest version of CoE Starter Kit all Cloud-Flows should be installed correctly to ensure all functions are working.

_Prerequisites:_
- Installation of CoE Starter Kit was mid of 2021
- Since the first installation was succesfully done via MS Doc`s not all upgrades were done (the following upgrade was in 2022 some month after the first installation)

### Expected Behavior

After upgrading to the newest Version of CoE Starter Kit all new objects should be available. In this case it's the missing Cloud-Flow [Admin | Sync Template v3 CoE Solution Metadata]

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

### Steps To Reproduce

1. Use the instructions of Microsoft Doc's to setup the CoE correctly (https://docs.microsoft.com/de-de/power-platform/guidance/coe/starter-kit)
2. Find the Core Components setup section (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
3. Check the Flows in the solutions section for the solution "Center of Excellence - Core Components"
4. The Cloud-Flow [Admin | Sync Template v3 CoE Solution Metadata] is missing in the solution "Center of Excellence - Core Components"
<img width="772" alt="Admin Sync Template v3 CoE Solution Metadata" src="https://user-images.githubusercontent.com/91627990/178229711-65616267-6425-416b-8de5-10c4ebd1a53c.png">
<img width="1352" alt="Admin Sync Template v3 CoE Solution Metadata_missing" src="https://user-images.githubusercontent.com/91627990/178229960-2763c16c-c6e3-4198-9df7-786dca6ce215.png">

**Comment by manuelap-msft** [comment]
Hello,

thanks for the detailed walk through of your experience! Could I please ask for some additional details.

1. Navigate to make.powerapps.com > Your CoE environment
2. Select Solutions
3. Select **History**
4. Share a screenshot of what you see there

As you upgraded from a very old version (2021), I suspect the upgrade to the latest version has failed and that's why you don't see the new flows. 

Please note, we recommend upgrading every 3 months: 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup

**Comment by ANInnoSolutions** [comment]
<img width="1361" alt="Power Apps Solutions" src="https://user-images.githubusercontent.com/91627990/178249790-cd2a45cf-90dc-459d-b861-22d9f52a68c5.png">

**Comment by manuelap-msft** [comment]
From the history, it looks like the last upgrade was 3 months ago to version 3.34 and that's the version you have active at the moment
![image](https://user-images.githubusercontent.com/55705669/178250303-68e2f81d-850e-434e-9a7a-771e37e2e300.png)

It doesn't look like the upgrade to 3.40 was applied. If you go the **History** tab on this page you might see that the upgrade to 3.40 has failed.
![image](https://user-images.githubusercontent.com/55705669/178250465-5b3566f2-de76-45b7-8e00-6fb5f4ba7cf2.png)

If it has, please share the error details with us so we can help further.

**Comment by ANInnoSolutions** [comment]
<img width="1358" alt="Power Apps Solutions History" src="https://user-images.githubusercontent.com/91627990/178250929-083654ea-dc49-430e-9bae-91eeea70ee3f.png">

**Comment by manuelap-msft** [comment]
Hello,

here you can see that all the upgrades of Core components and Audit Log components have actually failed and not been applied to your tenant. If you click on the failure, you will get more details.

As your upgrades have failed for quite some time now, your environment may be in an unhealthy state that's difficult to recover from and we may be unable to help you further here, as it's unclear how you got into this state!

If you are only using the CoE kit to gather inventory and telemetry, and have not started using any of the governance and nurture flows (e.g. those that kick off approvals and teams adaptive cards) yet, then we recommend you start from a clean environment. Here is a write up to help with how to migrate the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

**Comment by ANInnoSolutions** [comment]
Okay, I can understand that there are some issues due to a longer period without updating the CoE Kit (even when I think that a timeframe smaller than 1 year should not be really a problem). Whatever, by looking deeper into the History of the core components I assumed that only the part of Deinstallation dismissed as the following image shows:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/91627990/178265825-429b264b-9075-4653-b9cc-7c35131eb9fe.png">

This gives me the hint, that all objects were added successfully and only the removal part dismissed as the Deinstallation process is the last one. By knowing the architecture of Microsoft it should also not really be a problem in this case. Anyway, is there a solution/fix for next updates planned?

As I do not really use the tool it is not that important but for the layering it is really good to work with.

**Comment by ANInnoSolutions** [comment]
**Error Description:**
Solution dependencies exist, cannot uninstall. DependencyCount : 17 RequiredComponentObject details: Type: SavedQuery, ObjectName: Compliance - Completed, Id: 348bcab5-0536-ec11-b6e6-000d3a5574a2, ParentObjectName: Flow, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Compliance - Completed, Id: f36f4696-0636-ec11-b6e6-000d3a5574a2, ParentObjectName: PowerApps Connector, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Compliance - Requested, Id: 074a58bd-0636-ec11-b6e6-000d3a5574a2, ParentObjectName: PowerApps Connector, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Compliance - Requested, Id: ce3289c9-0536-ec11-b6e6-000d3a5577a2, ParentObjectName: Flow, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Compliance - Submitted, Id: e638e4e1-0536-ec11-b6e6-000d3a5577a2, ParentObjectName: Flow, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Compliance - Submitted, Id: b12c179f-0636-ec11-b6e6-000d3a5577a2, ParentObjectName: PowerApps Connector, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Service Principle Makers, Id: adcbb158-4d75-ec11-8943-0022481e54b6, ParentObjectName: Maker, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Orphaned Makers, Id: b7913b1d-4d75-ec11-8943-0022481e5708, ParentObjectName: Maker, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Power Apps Portal Advanced Find View, Id: 389fdee7-cf75-4b4e-a0b4-38858bc701b0, ParentObjectName: Power Apps Portal, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Power Apps Portal Associated View, Id: 402a3310-1497-405d-803c-480afeca5a4c, ParentObjectName: Power Apps Portal, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Power Apps Portal Lookup View, Id: 8b834b5d-5651-4ef3-8d35-cd43cc36ff14, ParentObjectName: Power Apps Portal, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Power Apps Portals, Id: c63b99ef-865e-481a-9de9-e070fff4acb0, ParentObjectName: Power Apps Portal, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SystemForm, ObjectName: Information, Id: 50c540ca-c51a-466d-9dc2-338f8c3cea15, ParentObjectName: DLP Policy Change Request, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SystemForm, ObjectName: Portal Main Form, Id: ab3491bb-34b8-4122-bf46-931b63519b82, ParentObjectName: Power Apps Portal, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SystemForm, ObjectName: Information, Id: 7a835b75-23b1-48d5-bd26-ea6221e75069, ParentObjectName: Power Apps Portal, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: Entity, ObjectName: Power Apps Portal, Id: 8359f3f0-6f81-41fd-b419-8364a2d8538c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: Entity, ObjectName: DLP Policy Change Request, Id: 005af728-8d93-4805-ba91-d019499351cf, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: c3d71c31-c1ad-eb11-8237-000d3abb5baa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

**Comment by ANInnoSolutions** [comment]
The overall point is not really the error itself which occured in most updates. The removal of dependencies is a good starting point and regularly easy to handle to solve this issue. But, within the layers in the Power Platform Frontend it can be really difficult as there are in my research more than 27 layers possible (depending on licenses, solutions, installations like apps, versions...). 

Therefore, a CI/CD or similar would be a a good approach for the future for this tool.

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help with how to migrate the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507) if you are using that.

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment.
Some people have cleaned themselves from this state by manually cleaning out the references listed. 

Sorry we cannot be of more assistance here.

**Comment by ANInnoSolutions** [comment]
The suggestions are not really helpful at this point but anyway thanks for the thoughts.

For the future maybe there is some chance to rethink about the CI/CD approach or similar for this tool. 

Anyway, the tool is working well in most cases depending on activated features/flows with only a few restrictions due to this issue for anybody interested having the same issue.

**Comment by manuelap-msft** [comment]
We do use CI/CD for the development, we actually use the ALM Accelerator for development and release of the tool (https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/overview).

We're a very small team maintaining the kit, and the product is moving very fast - in the last year, concepts like environment variables, environment variable secrets, connection references etc all got introduced and those all change the way we use the product to develop the solution. Additionally, the more we develop the more we learn on what to do / what not to do. With our small team, we can only test upgrades for 3 months back and ensure there's no dependency issues there and that any unused things / field changes are safely cleaned up within 3 months. Anything further back is outside of our capacity to test - you're right, this is not a product limitation, but a limitation of the capacity of our team. We're trying our best, but the CoE starter kit is not an official product of Microsoft and only has a small dev team behind it. 

Thanks for your feedback and for using the CoE kit!
