### ISSUE TITLE
[CoE Starter Kit - QUESTION] "App last launched on" in the "Power Apps App" table is blank.

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#3160]
### What is your question?

I have an app that has been launched many times, but no value has been entered for "app last launched on" for that app, and it remains blank.

For example, "Set App Permission" has been started many times, but it is blank as shown below.
![image](https://user-images.githubusercontent.com/70095092/178234112-480fa7b0-1ad0-4b1b-985d-9243f6f286e4.png)

Does the flow of entering values here match with "Admin | Sync Template v3 (Apps)"?
In my environment, that flow is on.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

**Comment by manuelap-msft** [comment]
Hello,

this field is populated through the Audit Log solution, which is a separate setup process:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

**Comment by sudadakkota** [comment]
I had a misunderstanding that I have to setup that process.

Thank you for answering!

**Comment by manuelap-msft** [comment]
Great, I'll close this issue for now but if you run into an issue setting up the Audit Log solution please let us know by opening another issue for us!

**Comment by RickKush** [comment]
I have set up the custom connector for the audit log, but that last launched on date field is still not getting populated. Can I also get help to find the action that uses the custom connector to get the launched date?

**Comment by manuelap-msft** [comment]
Hello,

in order for us to best track and triage open issues, can you please raise a new issues for this instead of commenting on a closed one? Thank you!
