### ISSUE TITLE
[CoE Starter Kit - BUG] Audit flows keeps running for days

### ISSUE THREAD

**Issue by ShaishilMandot** [microsoft/coe-starter-kit#3163]
### Describe the issue

COE toolkit audit flows keeps running for days and display a warning that maximum data limit reached. The reason for this is
•	The connector bring all audit data from compliance center(even apps outside power platform) and then process it locally in flows rather than bringing filtered data for app launch events and we don’t have any configuration at our side to filter this out specifically for Power apps launch event only
•	The data limit being hit for Power automate/Power app per user license

The flow should have a filtered query to Compliance center to bring only app launch events for Power apps

### Expected Behavior

The flow should have a filtered query to Compliance center to bring only app launch events for Power apps

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

This issue can be replicated in a tenant with large volume of power apps

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid the API we use for the custom connector does not support filtering down to the target actions. 

For large tenants you will likely need to rely on the upcoming data lake features which will write these actions in a way that we can consume. 

Please see these links if you would like to explore early, we are targeting integration of the kit with this as a data source for later this calendar year.
https://docs.microsoft.com/power-platform/admin/self-service-analytics
https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
