### ISSUE TITLE
[ALM Accelerator - BUG]: Unpublished child workflow prevents flows from being turned on

### ISSUE THREAD

**Issue by wiskaso** [microsoft/coe-starter-kit#3168]
### Describe the issue

I am receiving the following error when deploying a solution which contains parent-child flows in to a new environment:

This occurs at the **Activate Flows for Connection References** step

> Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished"," 
> message":"The workflow with id '29bd0aef-5bf6-ec11-bb3d-000d3a10a684' cannot be used as a child workflow because i  
>   t has never been published. Child workflows need to be published at least once before they can be included in a pu   
>  blished parent workflow."}}". => Flow client error returned with status code "BadRequest" and details "{"error":{"    
> code":"ChildFlowNeverPublished","message":"The workflow with id '29bd0aef-5bf6-ec11-bb3d-000d3a10a684' cannot be u    
> sed as a child workflow because it has never been published. Child workflows need to be published at least once be    
> fore they can be included in a published parent workflow."}}".[TerminalFailure] Failed to Execute Command - SetSta    
> te : RequestID=f5ce013a-e0f8-4a5d-befa-016f699bcd70 : Setting Activity State in CRM... workflow duration=00:00:06.    
> 5356990 ExceptionMessage = Flow client error returned with status code "BadRequest" and details "{"error":{"code":    
> "ChildFlowNeverPublished","message":"The workflow with id '29bd0aef-5bf6-ec11-bb3d-000d3a10a684' cannot be used as     
> a child workflow because it has never been published. Child workflows need to be published at least once before t    
> hey can be included in a published parent workflow."}}"

To get around this error I logged in to the deployment environment and manually started the child flows first and then the parent flows.  The flows started perfectly fine with no further changes.   This also seems to make subsequent deploys work fine as well even if the flows were turned back off again.

The unfortunate part is that this causes the deployment pipelines to fail on the first try.

### Expected Behavior

Flows start up correctly as normal.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

CenterofExcellenceALMAccelerator-May2022

### Steps To Reproduce

1. Create a solution
2. Add a flow with an instant trigger and some parameters
3. Add a flow that has the action 'Run a Child Flow' in it and reference the flow created in step 2
4. Create a new environment(s)
5. Setup the new environment(s) to be Azure DevOps deployment ready to go
6. Load up the Centre Of Excellence ALM app
7. Fill out the deployment configurations and ensure that the above flows are in the correct activation order and turned on
8. Export solution to AzDO
9. Progress through the code promotion flow until a deployment is attempted in the new environment created in step 4.

**Comment by mikefactorial** [comment]
@wiskaso please upgrade to the latest release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-July2022. We resolved an issue with the child workflow activation in this issue in the June release https://github.com/microsoft/coe-starter-kit/issues/2449.

**Comment by wiskaso** [comment]
Thank you!
