### ISSUE TITLE
Teams env. creation compliance process

### ISSUE THREAD

**Issue by raphaeltremblay1966** [microsoft/coe-starter-kit#3170]
I would like some clarifications for the Teams environment creation compliance process. In the "Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created" flow, the default trigger is "Added". 

1. How does that applies for already created Teams ? I would like to test the process but don't want old Teams environment to receive an adaptive card.

2. Teams environments also have an "Excuse From Compliance Flow". Where is that referenced, so they are excluded ? 

Really don't want to mess with existing Teams environments ALREADY created.

![image](https://user-images.githubusercontent.com/99994964/178497450-0ed8fa9f-e006-4281-b3dd-488d7557c41c.png)

**Comment by Jenefer-Monroe** [comment]
The flow to ask for business justification, which you show above, runs whenever a teams environment is added to to the inventory (the CoE's Environments table).
So as long as a teams environment is already inventoried, this flow will not trigger for it. 

Excuse from Compliance is for all environments, and allows you to exempt environments from the separate [Compliance Processes](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#compliance-processes)
 
Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
