### ISSUE TITLE
[ALM Accelerator - BUG]: Pipeline error at Set SpnToken

### ISSUE THREAD

**Issue by Samuel-Dittmann** [microsoft/coe-starter-kit#3175]
### Describe the issue

As soon as I commit a solution in the ALM Accelerator app, the pipeline "export_solution_to_git" in DevOps starts running and fails at the "Set SpnToken for use by other tasks that need one".
It throws the following error: 

Invoke-RestMethod : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
At D:\a\1\PipelineUtils\PowerShell\dataverse-webapi-functions.ps1:4 char:17
+ … $OAuthReq = Invoke-RestMethod -Method Post -Uri "[https://$aadHost/$te](https://%24aadhost/$te) …
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: POST, Reque…-form-urlencoded
}:HttpRequestMessage) [Invoke-RestMethod], HttpRequestException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
##[error]PowerShell exited with code '1'.

### Expected Behavior

The pipeline should go through without any errors

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220503.1

### Steps To Reproduce

1. Select a random solution and commit it in the Accelerator App
2. Wait for the pipeline to fail

### Anything else?

I've used the CoE CLI to install the ALM
I've tried solutions from one specific development environment that is not part of the actual ALM environments.
All environments that I use are added as service connection in DevOps

![Screenshot 2022-07-13 090527](https://user-images.githubusercontent.com/69673546/178699569-5e2eb4f5-e76f-4726-a43a-a9acc00dc3e1.png)

**Comment by jenschristianschroder** [comment]
Hi @Samuel-Dittmann 

There is a now bug in our backlog that the CoE CLI does not create the AADHost variable in the alm-accelerator-variable-group variable group.

We are hoping to have this fixed in our next release.

Until then you can fix this issue by creating a variable in the alm-accelerator-variable-group as follows

| Variable name | Variable value |
|-----------------|----------------|
| AadHost          | login.microsoftonline.com |


Br,
Jens Schrøder

**Comment by Samuel-Dittmann** [comment]
Hey @jenschristianschroder 

thank you very much for your response!
I just looked it up and the variable is in the correct variable group.
So this does not seem to be the issue here.

Best Regards
![Screenshot 2022-07-13 161207](https://user-images.githubusercontent.com/69673546/178754793-1db664ee-c28e-4c52-b05d-d0851090a1d9.png)

**Comment by jenschristianschroder** [comment]
I see the value of aadhost is login.microsoftonline.DE.

I don't think that is a valid login URL.

Please try login.microsoftonline.com and let us know if that fixes the issue

**Comment by Samuel-Dittmann** [comment]
Damn im stupid.
Thank you very much, this seems to work now!
