### ISSUE TITLE
[ALM Accelerator - QUESTION]  CLI for Accelerator for Makers

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#3182]
### What is your question?

What should you see after you run the CLI for Accelerator for Makers? We do not receive an error message but also do not see aything happening.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

latest

**Comment by manuelap-msft** [comment]
(this come up in the office hours)

**Comment by mikefactorial** [comment]
@YvoValcon we've merged this PR https://github.com/microsoft/coe-starter-kit/pull/3198 into the main branch with updates to the coe-cli that may make it easier to troubleshoot your issues. Would you mind pulling the latest from main and reporting back on your findings?

**Comment by mikefactorial** [comment]
Closing this out as there's not been any response and no action items
