### ISSUE TITLE
[CoE Starter Kit - BUG] How to update URLs in Command Center (for renamed environment)

### ISSUE THREAD

**Issue by ryanwalker726** [microsoft/coe-starter-kit#3189]
### Describe the issue

Recently installed the July edition of the starter kit in a brand new environment.  After I installed the core components, I realized that I had forgotten to change the environment URL to something pronounceable (rather than orgXXXXXXXX.crm.dynamics.com).  I updated the environment URL and the only noticeable impact that I've seen so far is that the "Power Platform Admin View" bookmark link in the Admin - Command Center app still points to the old environment URL and I can't figure out how to update it to reflect the new URL.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

1. Install core solution
2. change the environment URL of the environment
3. "Power Platform Admin View" bookmark link points to the old environment URL
4. 404 error

**Comment by Jenefer-Monroe** [comment]
This will not update on its own, we do not overwrite existing URLs. You can update it by going to Edit bookmarks, fixing the string there and saving. 

Hope that helps

![image](https://user-images.githubusercontent.com/89584709/178890580-f860db8d-9025-481f-a53c-98444cf83025.png)
![image](https://user-images.githubusercontent.com/89584709/178890680-c24ea1fa-c9ce-40a5-87c2-0aa1002f1711.png)

**Comment by ryanwalker726** [comment]
Thank you!  That worked perfectly.  I'm still getting used to the CoE and I was overthinking it...  Thought that I needed to update an environment variable or something like that.

**Comment by Jenefer-Monroe** [comment]
You are forgiven for assuming complexity in our very complex system :)

Welcome to the CoE!
