### ISSUE TITLE
[CoE Starter Kit - QUESTION] About deletion flow of Dataverse for Teams environment

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#3190]
### What is your question?

I have a question about the "Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments" flow in the Governance component.

In the conditional branch of "Check if inactivity after 90 days 2" that deletes the environment 90 days or more ago, it was set that "Production Environment (admin_ProductionEnvironment)" was "true" as shown in the following capture.
![image](https://user-images.githubusercontent.com/70095092/178929295-7c396a9f-df28-40ec-b8a0-ffa9915bf73d.png)

By default, the "Production Environment (admin_ProductionEnvironment)" environment variable is set to "yes", so I suspect that this conditional branch may not be True.

Is this a bug? Or is it a specification?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Microsoft Teams Admin  | Weekly Clean Up of Microsoft Teams environments

**Comment by Jenefer-Monroe** [comment]
This env variable is of type yes/no, not string
![image](https://user-images.githubusercontent.com/89584709/178990117-258b4d5b-ee7a-4ac7-9f2c-491e4eff5424.png)

That means it surfaces in the flow as true/false
![image](https://user-images.githubusercontent.com/89584709/178990459-655902d3-c1ab-476e-a8fa-a95117f0847b.png)


Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
