### ISSUE TITLE
[CoE Starter Kit - Core] D4T Power Virtual agents not visible in admin view app

### ISSUE THREAD

**Issue by A-Demir-ilx** [microsoft/coe-starter-kit#3191]
### Describe the issue

Is it possible to gain insight into the Chatbots created in a Dataverse for teams environment in the CoE starter kit?

These are now not visible. Looked at it and the flow stops at a Dataverse for teams environment.

### Expected Behavior

The Power Virtual agents created in a Dataverse for teams environment visible in the CoE starter kit.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

**Comment by manuelap-msft** [comment]
That is one of our known limitations here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#sync-flow-limitations-for-developer-and-microsoft-team-environments

The product doesn't allow us to get this information unfortunately.

**Comment by GozdeKirac** [comment]
Hello! What is the recommendation regarding Microsoft Teams Governance environments in this case? Is there any workaround that Microsoft proposes to the customers that want to use D4T environments for bot creation?
