### ISSUE TITLE
HELPER - Maker Check error - Attribute 'value' was not found for environment variable 'admin_GraphURLEnvironmentVariable'."}}". Code: 0x80060467

### ISSUE THREAD

**Issue by raphaeltremblay1966** [microsoft/coe-starter-kit#3204]
Hello,

When I try to Turn On the HELPER - Maker Check, I get an error that seems to be related to the connection.

Request to XRM API failed with error: 'Message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_GraphURLEnvironmentVariable'."}}". Code: 0x80060467 InnerError: '.

![image](https://user-images.githubusercontent.com/99994964/178780203-a4681322-1ca5-49e6-862a-b4c4b5ec388b.png)

However, the connections seems to be good :

![image](https://user-images.githubusercontent.com/99994964/178812574-ef217b79-e4ab-43a7-b85f-c3c4822b0dc6.png)

If I recreate them 

![image](https://user-images.githubusercontent.com/99994964/178812786-9fe2d98e-8ad9-4ecd-9711-713d14928fc8.png)
![image](https://user-images.githubusercontent.com/99994964/178812895-7cfda9b2-1eb4-4f27-95fa-acc08df07bf3.png)

**Comment by manuelap-msft** [comment]
Hello,

it looks like you've not set the environment variable value:
![image](https://user-images.githubusercontent.com/55705669/179222986-1cd5e829-b540-47f8-a87d-2071e98e3a9a.png)

See
- https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values
- how to update environment variables https://docs.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables

**Comment by raphaeltremblay1966** [comment]
That does the trick, thanks a lot !
