### ISSUE TITLE
[ALM Accelerator - BUG]: CustomAzureDevOps.RunPipeline failed

### ISSUE THREAD

**Issue by ShridharDeshpande** [microsoft/coe-starter-kit#3205]
### Describe the issue

I've recently upgraded the ALM Accelerator version to CenterofExcellenceALMAccelerator-July2022. When I'm trying to commit the solution in getting below error.

![image](https://user-images.githubusercontent.com/47315792/179221212-5d277a2d-0b0d-45ff-908c-9a55ede159d2.png)

**Details error message:** "A value for the 'Branch' parameter must be provided.\nA value for the 'CommitMessage' parameter must be provided.\nA value for the 'Email' parameter must be provided.\nA value for the 'Project' parameter must be provided.\nA value for the 'Repo' parameter must be provided.\nA value for the 'ServiceConnectionName' parameter must be provided.\nA value for the 'ServiceConnectionUrl' parameter must be provided.\nA value for the 'SolutionName' parameter must be provided.\nA value for the 'UserName' parameter must be provided."

I've checked the Payload for API it is providing the value to parameter. I've attached the snap of the API payload below:

![image](https://user-images.githubusercontent.com/47315792/179220522-892d1f32-b592-484b-84c2-ef8ba3968390.png)

_Thanking you in Advance_

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

July 2022

### Steps To Reproduce

1. Open the ALM Canvas App.
2. Choose the deployment profile for the solution.
3. Click on "COMMIT SOLUTION" and Enter the notes and name of the new branch.
4. Click on "COMMIT"

**Comment by mikefactorial** [comment]
@ShridharDeshpande it appears that the latest app is not installed. The pipelines are expecting parameters in the latest version. If you made customizations to the app in the past you may have unmanaged layers in your environment that would prevent the app from updating when importing the latest solution.

The other possibility is that the previous version of the app is cached. In this case you may just need to clear your browser cache or Ctrl + F5 to ensure the browser loads the latest.

**Comment by ShridharDeshpande** [comment]
@mikefactorial Thank you very much it worked.
