### ISSUE TITLE
[CoE Starter Kit - QUESTION] Purpose of Admin - Access this Flow

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#3216]
### What is your question?

What is the purpose of this app ?

Looks like the grid is also not loading

Cant get my head around 'permissions' tab

![image](https://user-images.githubusercontent.com/17232756/179427326-b15d9770-292e-4860-bcc7-7b3d15ac6de5.png)
'Email Maker' and 'Maker Portal tab works perfectly fine.

Never tried 'Delete App' functionality

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Admin - Access this Flow

**Comment by manuelap-msft** [comment]
This app can't be used standalone and is used embedded in the Power BI Dashboard, see the setup here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard

Once embedded, you can navigate to it through a drillthrough of an app and you can then see the permissions of that app, change ownership, delete the app etc - the purpose of the app is to perform these tasks without leaving the context of Power BI.

I would recommend you read through our documentation to find out how to use the CoE kit more!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
