### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#3217]
### What is your question?

What is the purpose of this app?

No data is getting loaded in this app. Although i have many makers in the system.

![image](https://user-images.githubusercontent.com/17232756/179428022-cc074deb-d8ba-453e-b29b-2255a21d16af.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Maker - Command Center

**Comment by manuelap-msft** [comment]
See: https://github.com/microsoft/coe-starter-kit/issues/2921#issuecomment-1147293710

**Comment by girishuppal** [comment]
Thanks manuelap-msft. All working now.

Jus a quick suggestion: Microsoft must write some instructions around the app on usage of Bookmark functionality (without any hint admin or maker might be clueless to access the Bookmark section). Thanks.
