### ISSUE TITLE
[CoE Starter Kit - BUG] Buffer size error in Sync Template v3 (Connection Identities)

### ISSUE THREAD

**Issue by paulculmsee** [microsoft/coe-starter-kit#3218]
### Describe the issue

Flow fails on the GetCurrentActual scope. Error message: The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '209863650' bytes. This exceeded the maximum size '209715200' bytes allowed.

![image](https://user-images.githubusercontent.com/4979626/179431064-aa3a5316-ed4f-478d-bd5a-9373ad5dfcfb.png)

This looks really hard to fix 

### Expected Behavior

Connections enumerated as currently works with less active environments

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Sync Template v3 (Connection Identities)

### Steps To Reproduce

Execute flow on an environment with significant activity/usage

### Anything else?

Built-in action has no filtering ability it seems. Not sure what can be done without a custom action/API call

**Comment by stevealldridge** [comment]
I am also experiencing this same issue with 3.40

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
