### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE WITH CLEANUP HELPER - Check Deleted (Model Driven Apps)

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#3220]
### Describe the issue

Hello,

3 Days ago this flow started to work CLEANUP HELPER - Check Deleted (Model Driven Apps) and I found after the flow run that the MODEL DRIVEN APPS ( ALL OF THEM) have been deleted from the dataverse.  After a couple of hours, the MODEL DRIVEN APPS have been added back to the DATAVERSE.

Another behaviour that I have seen in the dataverse is that the CANVAS apps that are deleted are just changing the status to appdeleted = true, but Model Driven Apps when they are deleted they are deleted for good in dataverse.

The idea is beside the MODEL DRIVEN APPS that I have created for tests and then delete, the flow is also deleting apps that are not deleted. 

What could be the cause? What I should check?

![image](https://user-images.githubusercontent.com/7468628/179445220-ced74986-e765-4a31-b096-88c0bb90a6de.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

 3.39

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Model Driven Apps)

**Comment by ClaudiuVio** [comment]
Right now I have removed unmanaged layers from all the inventory flows and currently, I am updating to the latest versions for all the solutions we use : 

CenterofExcellenceCoreComponents_3.40_managed
CenterofExcellenceAuditLogs_2.10_managed
CenterofExcellenceAuditComponents_2.18_managed

**Comment by ClaudiuVio** [comment]
> Contributor
Hi @[manuelap-msft](https://github.com/manuelap-msft)

Thank you for your time. I will let you know if this solved the issue.

I have a question : 

1. The MODEL DRIVEN apps should be also marked in DATAVERSE when they are deleted just with the status appdeleted = true like CANVAS apps or is a normal behaviour to be entirely deleted from DATAVERSE ?

**Comment by Jenefer-Monroe** [comment]
Correct, all objects behave the same way in this regard and look at the value of this env variable to determine if they will delete from inventory or just mark deleted. Note that flows do cache these values so you may need to turn the Model Driven helper off and on if you have updated the variable. 

From [Core Environment Variables](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#all-environment-variables)
![image](https://user-images.githubusercontent.com/89584709/180623154-64215648-e17b-418c-901f-fc4376bca3c7.png)
