### ISSUE TITLE
[CoE Starter Kit - BUG] Turn on inventory flows

### ISSUE THREAD

**Issue by YvoValcon** [microsoft/coe-starter-kit#3221]
### Describe the issue

Hi,

I have an issue regarding the flow: Admin | Sync Template v3 CoE Solution Metadata. The error message reads: Action 'Get_CoE_Envt' failed

The step: "Get CoE Envt" seems to be the problem. The message there reads: admin_environment With Id = 7f8d351c-5ff5-e99c-9553-c4ac28c21640 Does Not Exist.

The environment exists and the ID is also correct, so I am not sure what is exactly the issue. Can you please assist me with this? As this flow does not work, the whole CoE does not work properly.

Thanks in advance!

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/97224137/179467886-be1ece83-6899-495f-929d-1e707491a6e1.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

### Steps To Reproduce

1. In the CoE Environment
2. Go to the Core Components Solution
3. Go to the flow: Admin | Sync Template v3 CoE Solution Metadata
4. Run the flow
5. Go to step 3: "Get Tenant Info"
6. In step 3, the first step is "Get CoE Envt". Here lies the problem

### Anything else?

<img width="1277" alt="Screenshot Get Tenant_Info_fail" src="https://user-images.githubusercontent.com/97224137/179468019-53550a04-a95f-492a-8ad9-a314d7af3933.png">

**Comment by manuelap-msft** [comment]
Hello,

can you make sure you don't have unmanaged layers on the flow, and upgrade to the latest version (3.40). We fixed an issue in this flow so it's no longer using the Get CoE envt step, instead we extract the environment from the flow itself.

![image](https://user-images.githubusercontent.com/55705669/179557690-2b67adb7-4e21-4cae-90b9-2a50f8c95f5f.png)

**Comment by YvoValcon** [comment]
Hi,

Thanks for the reply, I updated the version and it works! Now waiting for the Admin | Sync Template v3 flow to complete. If that works too I am all set :)

**Comment by manuelap-msft** [comment]
Hello,

usually we see the Get Maker action here failing when the child flow that this step calls is not turned on. 

Check here for all the child flows and setup flows that need to be turned on, the docs here call out the required order to turn flows on:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows

I am guessing it's the **HELPER – Maker Check** that's turned off, but it could be another one! 

Hope that helps,
Manuela

**Comment by YvoValcon** [comment]
Hi Manuela,

I updated the solution and now another issue is occuring, do you know what is wrong?
<img width="956" alt="image" src="https://user-images.githubusercontent.com/97224137/180384953-31998998-793a-443f-819d-7e4be1db45c7.png">

**Comment by manuelap-msft** [comment]
Hello,

can you pop open the "Check if Legacy Environment" condition so we can see what action is causing the failure?

**Comment by YvoValcon** [comment]
Hi there, 

<img width="957" alt="image" src="https://user-images.githubusercontent.com/97224137/180424774-903d6bba-8b83-45c0-aa9b-0fec8a019609.png">

<img width="949" alt="image" src="https://user-images.githubusercontent.com/97224137/180424848-e6a938a6-43ec-46d0-8cb1-1013de013563.png">

<img width="955" alt="image" src="https://user-images.githubusercontent.com/97224137/180424934-f28e7652-ae84-4cb3-9811-6abdbe4b87db.png">

**Comment by manuelap-msft** [comment]
Hello,

can you confirm all the child flows mentioned here are turned on?
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows

I am guessing based on the error it's the HELPER – Maker Check that's turned off, but it could be another one!

**Comment by YvoValcon** [comment]
Hi,

Hereby I can confirm that all child flows are turned on!

**Comment by Jenefer-Monroe** [comment]
Please share the following screenshots with us

1) Filter to flows in Core with the string "help" in the name, and show their state:
![image](https://user-images.githubusercontent.com/89584709/180623256-47e9a258-aa50-45fc-8b6f-ca3b08bb8d6e.png)

2) Go to Details for **HELPER - Maker Check**, do you see any successes? Are the connection references showing with a green check? 
![image](https://user-images.githubusercontent.com/89584709/180623288-21f17a83-0a60-43a9-af7a-f821abf34aaa.png)

**Comment by YvoValcon** [comment]
Hi Jenefer,

Thanks for the reply. As you can see below, all the signs are on green... 

<img width="951" alt="image" src="https://user-images.githubusercontent.com/97224137/180767840-35e1f83a-2cda-4369-a718-2f4bc258ab16.png">

<img width="941" alt="image" src="https://user-images.githubusercontent.com/97224137/180767965-1b50898c-e71a-49e7-a72f-15938509f486.png">

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont know how to assist you, I am out of ideas to assist remotely. You may need to seek out partner assistance to debug where they can log in and see what we are missing. 
Sorry I cannot be of more assistance.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
