### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why in Audit Log there is only LuachPowerApps Opration

### ISSUE THREAD

**Issue by tinghu200** [microsoft/coe-starter-kit#3222]
### What is your question?

In the Audit Log there is only LuachPowerApps Opration. is there any record about power automate. e.g. someone who lauchPower automate in AuditLog? Thank you

![image](https://user-images.githubusercontent.com/109514509/179480024-7569f255-4165-473c-9f9c-33383ddc9fbb.png)

### What solution are you experiencing the issue with?

Audit Log

**Comment by manuelap-msft** [comment]
Hello,

that's correct, we only capture Power Apps Launch events from the Audit Log at the moment. Flow runs are not available via the Audit Log.

Learn here what activities are available: 
https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps
https://docs.microsoft.com/en-us/power-platform/admin/logging-power-automate

Note: We use other mechanisms to capture created/edited/deleted/shared apps and don't rely on the Audit Log for that. We only use the Audit Log connector to get app launch events, as those aren't available anywhere else. 

Flow run information is not available via the Audit Log, but is available via Data Export (self-serve analytics, https://docs.microsoft.com/en-us/power-platform/admin/self-service-analytics) and you can track this feature to see how we progress with re-platforming the CoE kit to use the data lake as a foundation #424

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
