### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE Preview  Screen in Theme Editor stays on Loading 

### ISSUE THREAD

**Issue by matt1405** [microsoft/coe-starter-kit#3223]
### Describe the issue

The Theme Preview in Theme Editor continuously shows Loading and never completes. PCF is already enabled.
![image](https://user-images.githubusercontent.com/58092023/179478546-7a5cc356-8a18-4f3e-aaf5-773f6cb96fc0.png)

### Expected Behavior

I believe it should load a screen preview.  

### What solution are you experiencing the issue with?

Theming

### What solution version are you using?

2.4

### What app or flow are you having the issue with?

Theme Editor

### Steps To Reproduce

!. Build Theme 
2. Save Theme 
3. Preview Pane stays as loading

**Comment by manuelap-msft** [comment]
Hello,

I think there's a misunderstanding here - the "Loading ..." actually shows you what the colour and theme the Loading ... component of the Theming solution would look like when you use it. It's not Loading anything here, just showing you the component. 

You can see that in our screenshots in the documentation it also shows the Loading as expected
https://docs.microsoft.com/en-us/power-platform/guidance/coe/theming-components

Hope that helps
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
