### ISSUE TITLE
[CoE Starter Kit - BUG] After updating the kit my flow cou t is mismatched

### ISSUE THREAD

**Issue by NemadeUjwal** [microsoft/coe-starter-kit#3225]
### Describe the issue

After I updated the COE kit core component, my total count of flow is mismatched. It is showing less flows but when I run the powershell I get more count.

If I want to cleanup the flow stored in Dataverse and start as fesh what should I do ?? Just Flows

### Expected Behavior

Count should be correct

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

**Comment by NemadeUjwal** [comment]
I don't want to reinstall every things.

**Comment by NemadeUjwal** [comment]
Getting this error, adding the screenshot for more info.
![20220718_175605](https://user-images.githubusercontent.com/99943014/179510929-7642d7d7-5137-4b64-a8c5-de4a3949f456.jpg)

**Comment by NemadeUjwal** [comment]
yes, there are difference but then before update I was getting approx correct number and after upgrade I got wrong numbers.

Let me know what help you need fro my side. Hope the both the attached screenshot will help you in investigation.

**Comment by Jenefer-Monroe** [comment]
You will need to find individual cases that are wrong for us to be able to investigate. So a reference you expect that you do not see, or a reference you see that you should not.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
