### ISSUE TITLE
[CoE Starter Kit - BUG] How to exclude CoE Environment out of archiving process?

### ISSUE THREAD

**Issue by tomsinsight** [microsoft/coe-starter-kit#3227]
### Describe the issue

Hello Team,

It's been noticed that the customization done on top of the CoE is being archived through Archiving process.

Would you please share how can I exclude CoE environments from the archiving process in the latest version of the CoE kit?

Thanks,

### Expected Behavior

CoE environments should be excluded from the archiving process

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

June 2022 version

### What app or flow are you having the issue with?

Archiving process

**Comment by manuelap-msft** [comment]
To exclude an environment from the Inactivity Notifications (Archive) process, open the Power Platform admin view > Environments > select the Environment you want to exclude and select Yes for "Excuse from Inactivity flows"
![image](https://user-images.githubusercontent.com/55705669/179553453-a1b95518-09e5-410c-a083-61b1d40f5b78.png)

**Comment by tomsinsight** [comment]
Super, Thank you very much!

**Comment by Jenefer-Monroe** [comment]
Thanks for using CoE! We'll close out but please let us know if you need further assistance.
