### ISSUE TITLE
[CoE Starter Kit - BUG] Archive and Clean Up v2 (Start Approval for Flows) Impact

### ISSUE THREAD

**Issue by KishoreJagan83** [microsoft/coe-starter-kit#3228]
### Describe the issue

Is their a way to revert or delete the archival data's which was triggered due to _**Archive and Clean Up v2 (Start Approval for Flows)**_.

Flow got triggered and maker's received  the mail for the respective archival flows which are not modified for the past 6 months.
But now we want to turn off this flow and want to delete all the flow archival data's and not the app archival data's.
Any impact to  Cleanup Old Objects App ?

Any way to bulk delete these flow archival data in backend or any other way?

### Expected Behavior

Need a way to delete all the flow archival data .
Ensure their won't be any impact due to this Flow archival deletion in the downstream app or flows.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Archive and Clean Up v2 (Start Approval for Flows)

### Steps To Reproduce

Flow archival notification triggered for the Maker's whose flow's are not modified for past 6 months.

Makers will receive the mail for the respective archival flows.
Makers can Approve or reject the flow for Archival.

**Comment by manuelap-msft** [comment]
Hello,

we don't have a process to bulk delete approvals that were sent, but they are stored in a table called Inactivity Notifications approval which you'll find in the Governance components solution. If you open the table, you should see all the app and flow inactivity notifications that have been sent, and you can manually delete them from there (or run a process/flow to bulk delete them).

If it's not that many, you can also use the Inactivity notifications clean up view app (canvas app) to click into each approval that got sent, select "Delete approval" and then turn off the flows so a new approval won't be sent. 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#app-and-flow-inactivity-notifications-clean-up-view

Hope that helps,
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
