### ISSUE TITLE
[ALM Accelerator - BUG]: Issue in update deployment settings

### ISSUE THREAD

**Issue by VaibhaviK2306** [microsoft/coe-starter-kit#3232]
### Describe the issue

I've configured below 3 deployment environment in deployment profile.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/30516020/179771979-a264840d-8416-48b9-9b11-466ac5eeb809.png)

When I commit the solution using ALM it triggers the export-solution-to-git pipeline. In the update deployment setting when I click on the $buildDefinitionResourceUrl, I only can see the ServiceConnection Variable for validation environment for other environment like QA and prod the ServiceConnection Variable value set as "[https://undefined.crm.dynamics.com/"]

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/30516020/179774399-dacf78d8-790c-48c2-a6d0-3d561b07e77a.png)

But in the update deployment setting as output of yaml file, I can see the correct values for all the three environments but it is not getting reflected as pipeline variable values

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/30516020/179773950-e4f1c2a9-f2a5-4e7c-86e4-46244d841a16.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

July 2022

**Comment by mikefactorial** [comment]
@VaibhaviK2306 try renaming QA and Production steps to Test and Prod. Customizing the names of these steps isn't currently supported when generating the pipelines. This is in our backlog to address, but currently they need to be named Validation, Test, Prod.

![image](https://user-images.githubusercontent.com/42348035/179779869-b3c8ed70-29bb-4101-ab82-b02121eb1e10.png)

**Comment by mikefactorial** [comment]
@VaibhaviK2306 has this been resolved?

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to be done here.
