### ISSUE TITLE
Power Platform Admin View App - BPF data not getting populated

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#3234]
### Describe the issue

In CoE Core Components solution, there exists almost 6 Business process as listed below

![image](https://user-images.githubusercontent.com/17232756/179861368-b24ea2a3-f279-4a12-9a97-5a60369d4c9e.png)

Why doesn't this gets reflected or seen when using 'Power Platform Admin View App'. I tried looking in all the views, but am unable to find it. Am i missing any steps of activation ?

![image](https://user-images.githubusercontent.com/17232756/179861493-19f60d99-fb32-4939-a521-aca96574060c.png)

### Expected Behavior

The Business Process left menu for 'Power Platform Admin View' App must display list of Business process

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

1. Open Power Platform Admin View app
2. Navigate to 'Monitor > Business Process Flow' tab on left menu
3. View the Business process flow listings

**Comment by girishuppal** [comment]
Same issue persists for Chatbots as well.

**Comment by Jenefer-Monroe** [comment]
Please review the flows listed in [setup inventory](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components). In particular you need the inventory flows for these objects turned on. But generally speaking you want all flows on in order to have correct inventory
![image](https://user-images.githubusercontent.com/89584709/180623495-e37a7759-307d-4e87-8852-5270d61ce01b.png)

**Comment by Jenefer-Monroe** [comment]
Aww yes I see. The default view in the PP Admin View is activated BPFs. You can see deactivated ones by switching the view. 
![image](https://user-images.githubusercontent.com/89584709/181273832-3cf8dcd8-23f8-499d-860d-e003563dc865.png)

**Comment by girishuppal** [comment]
It shows only limited items. The custom BPF which i have created long back is missing from the list

![image](https://user-images.githubusercontent.com/17232756/181400693-c7cb1a42-3ff3-499b-b65c-e437cadfc51e.png)

**Comment by Jenefer-Monroe** [comment]
It appears that we have resolved the original issue in which you were not seeing the disabled BPFs. 
Now you are saying that there are some number of BPFs that are missing (enabled or not). 

To investigate, you will need to find a repro of this in your tenant to see what is going wrong. 
1. Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you are looking for missing canvas apps chose **_Admin | Sync Template v3 (Apps)_**
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

5. From here you can explore if there is a failure, or if a bad return set, etc. And let us know if you have questions

**Comment by girishuppal** [comment]
If you see the Issue screenshot, the BPF was getting populated (but not every one). So my question is why some BPF are shown and why some BPF are not shown in the list.

Note: Issue was never related to visibility of BPF (as i have already selected Active BPF View)

**Comment by Jenefer-Monroe** [comment]
I cannot debug a case like this in which you say "some things aren't inventoried". We do not repro cases where some BPFs are not inventoried. In order to debug you will need to find the specific case as outlined above and trace it through execution. Without that I cannot assist. 

Please note that there are a bunch of partners who specialize in CoE, so if you need someone who can log in and debug this for you, you may need to hire out a partner.
