### ISSUE TITLE
[CoE Starter Kit - QUESTION] About "Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments" flow in Governance Component.

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#3235]
### What is your question?

I have a question about "Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments" in the flow to remove the Dataverse for Teams environment.

In the "row filter" of the capture action, there is a description "admin_adminmicrosoftteamsenvironmentstatus ne 597910000".
![image](https://user-images.githubusercontent.com/70095092/179884526-8fc1f085-6459-4d61-9c9b-9c39710eb143.png)

I think "admin_adminmicrosoftteamsenvironmentstatus" refers to "Admin --Microsoft Teams Environment Status" in the Environment table.
<img width="256" alt="image" src="https://user-images.githubusercontent.com/70095092/179884762-e4f5a70c-5e98-4bbb-bd99-1142c8f7092c.png">

Since either "Approved" or "Rejected" is entered in this line, it is a recognition that a value such as "597910000" described in the flow is not entered.
Where did this value "597910000" come from?

---
Let me ask you one more question in addition to the above.

The same flow description as the question above said "This flow runs weekly and deletes environments that: Have been created more than 7 days ago".
<img width="359" alt="image" src="https://user-images.githubusercontent.com/70095092/180113431-1450ae10-7f8d-49c7-94aa-a0bbb273af02.png">

However, looking at the flow actions, it seems that you are getting an environment that was provided with Business Justification more than 7 days ago, not an environment that was created more than 7 days ago.
![image](https://user-images.githubusercontent.com/70095092/180113924-932ee62e-e119-4a7a-895f-a40121f364aa.png)

Is this a bug? or specification?

※"過去の時間" means "past time"

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments

**Comment by Jenefer-Monroe** [comment]
Choice fields (ex admin_adminmicrosoftteamsenvironmentstatus) are more easily referenced by their Value than their Label. 
You can see what the translation is for label to value by looking at the choice directly:
![image](https://user-images.githubusercontent.com/89584709/180817737-975d1e61-2a80-4ec7-bb7d-72fabc61b2f8.png)

**Comment by Jenefer-Monroe** [comment]
Yes we start the clock when the business justification is stamped. For flows created after you enable this system, that will mean the same day as when the envt is created. Hope that helps

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this out then, please let us know if you have more questions
