### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade March 2022 to April 2022

### ISSUE THREAD

**Issue by TigerJ** [microsoft/coe-starter-kit#3236]
### Describe the issue

I am trying to upgrade an organizations COE, They were setup with the March 2022 release and I am working my way up to the most current version. 

The April 2022 core components solution is failing with the following error:
_The dependent component Workflow (Id=f845788b-5499-ec11-b400-00224832e318) does not exist. Failure trying to associate it with CanvasApp (Id=882f0253-25ee-42c1-9c2d-e2f5dbc0f4b6) as a dependency. Missing dependency lookup type = PrimaryKeyLookup._

When I unzip the solution and search the customizations.xml for a matching guid I find the following connection reference details on line 85,262:
[note, because Microsoft is embedding json inside xml... I extracted the json also, and identified the location at line 183-214 of the json (when formatted) which is below, before the raw dump of the customizations.xml line 85,262 dump:

`  "b8bbceac-e7c9-4cb9-be31-b7467d773b7a": {
    "id": "/providers/microsoft.powerapps/apis/shared_logicflows",
    "displayName": "Logic flows",
    "iconUri": "https://connectoricons-prod.azureedge.net/releases/v1.0.1534/1.0.1534.2605/logicflows/icon.png",
    "dataSources": ["CommandCenter&gt;GetunmanagedCoElayers"],
    "dependencies": [
      "8d6aff15-65f7-49b4-b14d-c1db3442717e",
      "e384c552-b4d2-43f2-a710-1d9f5832f5b0"
    ],
    "dependents": [],
    "parameterHints": {
      "workflowName": { "value": "2c9c3077-7ba0-4908-8b23-acfe6e07146c" },
      "workflowEntityId": { "value": "f845788b-5499-ec11-b400-00224832e318" },
      "8d6aff15-65f7-49b4-b14d-c1db3442717e": {
        "value": "shared_powerplatformforadmins_1"
      },
      "e384c552-b4d2-43f2-a710-1d9f5832f5b0": { "value": "shared_webcontents" }
    },
    "parameterHintsV2": {
      "workflowName": { "value": "2c9c3077-7ba0-4908-8b23-acfe6e07146c" },
      "workflowEntityId": { "value": "f845788b-5499-ec11-b400-00224832e318" },
      "shared_powerplatformforadmins_1": {
        "value": "8d6aff15-65f7-49b4-b14d-c1db3442717e"
      },
      "shared_webcontents": { "value": "e384c552-b4d2-43f2-a710-1d9f5832f5b0" }
    },
    "isOnPremiseConnection": false,
    "bypassConsent": false,
    "dataSets": {},
    "apiTier": "Standard",
    "actions": ["Run"]
  },`

      `<ConnectionReferences>{"ae400b4b-90af-4d98-88bc-9df80776878c":{"id":"/providers/microsoft.powerapps/apis/shared_office365users","displayName":"Office 365 Users","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1563/1.0.1563.2732/office365users/icon.png","dataSources":["Office365Users"],"dependencies":[],"dependents":[],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard"},"779be2ec-9eef-4092-90d2-9dde301e2206":{"id":"/providers/microsoft.powerapps/apis/shared_powerappsforadmins","displayName":"Power Apps for Admins","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1566/1.0.1566.2741/powerappsforadmins/icon.png","dataSources":["PowerAppsforAdmins"],"dependencies":[],"dependents":[],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard"},"d77c4ce2-7361-4bd4-8f93-b4348e0ce668":{"id":"/providers/microsoft.powerapps/apis/shared_rss","displayName":"RSS","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1567/1.0.1567.2748/rss/icon.png","dataSources":["RSS"],"dependencies":[],"dependents":[],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard","actions":["ListFeedItems"]},"e0c09597-ec29-47f6-8a44-a97a854fe4ba":{"id":"/providers/microsoft.powerapps/apis/shared_flowmanagement","displayName":"Power Automate Management","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1547/1.0.1547.2676/flowmanagement/icon.png","dataSources":["PowerAutomateManagement"],"dependencies":[],"dependents":[],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard","authenticationType":"firstParty"},"aad650d5-2449-4c59-ab80-c711d3012e1c":{"id":"/providers/microsoft.powerapps/apis/shared_office365","displayName":"Office 365 Outlook","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1566/1.0.1566.2741/office365/icon.png","dataSources":["Office365Outlook"],"dependencies":[],"dependents":[],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard","actions":["SendEmailV2"]},"b2a3839c-7a5d-4c81-9652-a755bd9a0406":{"id":"/providers/microsoft.powerapps/apis/shared_logicflows","displayName":"Logic flows","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1534/1.0.1534.2605/logicflows/icon.png","dataSources":["CommandCenterApp&gt;GetM365ServiceMessages"],"dependencies":["17c6b590-5d08-4c2a-902c-54728ba4215b"],"dependents":[],"parameterHints":{"workflowName":{"value":"27120494-037d-47aa-9e1a-f0ce9cf63638"},"workflowEntityId":{"value":"b38b49ee-41fc-eb11-94ef-002248237d7d"},"17c6b590-5d08-4c2a-902c-54728ba4215b":{"value":"shared_commondataserviceforapps_1"}},"parameterHintsV2":{"workflowName":{"value":"27120494-037d-47aa-9e1a-f0ce9cf63638"},"workflowEntityId":{"value":"b38b49ee-41fc-eb11-94ef-002248237d7d"},"shared_commondataserviceforapps_1":{"value":"17c6b590-5d08-4c2a-902c-54728ba4215b"}},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard","actions":["Run"]},"17c6b590-5d08-4c2a-902c-54728ba4215b":{"id":"/providers/microsoft.powerapps/apis/shared_commondataserviceforapps","displayName":"Microsoft Dataverse","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1566/1.0.1566.2741/commondataserviceforapps/icon.png","dataSources":[],"dependencies":[],"dependents":["b2a3839c-7a5d-4c81-9652-a755bd9a0406"],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Premium"},"3b1b4789-f7af-40e8-bed4-d97e4600805e":{"id":"/providers/microsoft.powerapps/apis/shared_logicflows","displayName":"Logic flows","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1534/1.0.1534.2605/logicflows/icon.png","dataSources":["CommandCenterApp&gt;InitiallyPopulateBookmarks"],"dependencies":["81ad095a-f1b5-4b5c-b871-edc79a409211","17e23410-f916-449f-91c1-259d216f4701"],"dependents":[],"parameterHints":{"workflowName":{"value":"9902ace6-450f-4347-a0e8-4a5bd8df9a46"},"workflowEntityId":{"value":"81ea7ac4-910a-ec11-b6e6-000d3a8c225c"},"81ad095a-f1b5-4b5c-b871-edc79a409211":{"value":"shared_powerappsforadmins_1"},"17e23410-f916-449f-91c1-259d216f4701":{"value":"shared_commondataserviceforapps"}},"parameterHintsV2":{"workflowName":{"value":"9902ace6-450f-4347-a0e8-4a5bd8df9a46"},"workflowEntityId":{"value":"81ea7ac4-910a-ec11-b6e6-000d3a8c225c"},"shared_powerappsforadmins_1":{"value":"81ad095a-f1b5-4b5c-b871-edc79a409211"},"shared_commondataserviceforapps":{"value":"17e23410-f916-449f-91c1-259d216f4701"}},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard","actions":["Run"]},"81ad095a-f1b5-4b5c-b871-edc79a409211":{"id":"/providers/microsoft.powerapps/apis/shared_powerappsforadmins","displayName":"Power Apps for Admins","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1566/1.0.1566.2741/powerappsforadmins/icon.png","dataSources":[],"dependencies":[],"dependents":["3b1b4789-f7af-40e8-bed4-d97e4600805e"],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard"},"17e23410-f916-449f-91c1-259d216f4701":{"id":"/providers/microsoft.powerapps/apis/shared_commondataserviceforapps","displayName":"Microsoft Dataverse","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1566/1.0.1566.2741/commondataserviceforapps/icon.png","dataSources":[],"dependencies":[],"dependents":["3b1b4789-f7af-40e8-bed4-d97e4600805e","e3eb4218-0128-4bae-97db-26f701419535"],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Premium"},"b8bbceac-e7c9-4cb9-be31-b7467d773b7a":{"id":"/providers/microsoft.powerapps/apis/shared_logicflows","displayName":"Logic flows","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1534/1.0.1534.2605/logicflows/icon.png","dataSources":["CommandCenter&gt;GetunmanagedCoElayers"],"dependencies":["8d6aff15-65f7-49b4-b14d-c1db3442717e","e384c552-b4d2-43f2-a710-1d9f5832f5b0"],"dependents":[],"parameterHints":{"workflowName":{"value":"2c9c3077-7ba0-4908-8b23-acfe6e07146c"},"workflowEntityId":{"value":"f845788b-5499-ec11-b400-00224832e318"},"8d6aff15-65f7-49b4-b14d-c1db3442717e":{"value":"shared_powerplatformforadmins_1"},"e384c552-b4d2-43f2-a710-1d9f5832f5b0":{"value":"shared_webcontents"}},"parameterHintsV2":{"workflowName":{"value":"2c9c3077-7ba0-4908-8b23-acfe6e07146c"},"workflowEntityId":{"value":"f845788b-5499-ec11-b400-00224832e318"},"shared_powerplatformforadmins_1":{"value":"8d6aff15-65f7-49b4-b14d-c1db3442717e"},"shared_webcontents":{"value":"e384c552-b4d2-43f2-a710-1d9f5832f5b0"}},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard","actions":["Run"]},"8d6aff15-65f7-49b4-b14d-c1db3442717e":{"id":"/providers/microsoft.powerapps/apis/shared_powerplatformforadmins","displayName":"Power Platform for Admins","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1566/1.0.1566.2741/powerplatformforadmins/icon.png","dataSources":[],"dependencies":[],"dependents":["b8bbceac-e7c9-4cb9-be31-b7467d773b7a"],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard"},"e384c552-b4d2-43f2-a710-1d9f5832f5b0":{"id":"/providers/microsoft.powerapps/apis/shared_webcontents","displayName":"HTTP with Azure AD","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1567/1.0.1567.2748/webcontents/icon.png","dataSources":[],"dependencies":[],"dependents":["b8bbceac-e7c9-4cb9-be31-b7467d773b7a"],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Premium","endpoints":["https://contosocoecoredev.crm.dynamics.com/"]},"c565c758-9632-48da-a5fd-aac6274a748d":{"id":"/providers/microsoft.powerapps/apis/shared_logicflows","displayName":"Logic flows","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1534/1.0.1534.2605/logicflows/icon.png","dataSources":["CommandCenterApp&gt;GetunmanagedCoElayers"],"dependencies":["441b824e-74e6-4dad-beda-e9fe8afd19db"],"dependents":[],"parameterHints":{"workflowName":{"value":"95c64242-144f-48de-bf81-d9a355f08140"},"workflowEntityId":{"value":"224208c7-d299-ec11-b400-00224832e516"},"441b824e-74e6-4dad-beda-e9fe8afd19db":{"value":"shared_webcontents_3"}},"parameterHintsV2":{"workflowName":{"value":"95c64242-144f-48de-bf81-d9a355f08140"},"workflowEntityId":{"value":"224208c7-d299-ec11-b400-00224832e516"},"shared_webcontents_3":{"value":"441b824e-74e6-4dad-beda-e9fe8afd19db"}},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard"},"441b824e-74e6-4dad-beda-e9fe8afd19db":{"id":"/providers/microsoft.powerapps/apis/shared_webcontents","displayName":"HTTP with Azure AD","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1567/1.0.1567.2748/webcontents/icon.png","dataSources":[],"dependencies":[],"dependents":["c565c758-9632-48da-a5fd-aac6274a748d"],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Premium","endpoints":["https://graph.microsoft.com"]},"1a450884-c15c-48a7-8f59-e3d862a35577":{"id":"/providers/microsoft.powerapps/apis/shared_logicflows","displayName":"Logic flows","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1534/1.0.1534.2605/logicflows/icon.png","dataSources":["CommandCenterApp&gt;SetCoEFlowsState"],"dependencies":["098c2992-b427-4549-8cdc-ff697a7cfd28"],"dependents":[],"parameterHints":{"workflowName":{"value":"dafbaca0-8432-4c7f-bbc2-4c71f53e80cb"},"workflowEntityId":{"value":"21a5c4f1-5080-ec11-8d21-002248320bcd"},"098c2992-b427-4549-8cdc-ff697a7cfd28":{"value":"shared_flowmanagement"}},"parameterHintsV2":{"workflowName":{"value":"dafbaca0-8432-4c7f-bbc2-4c71f53e80cb"},"workflowEntityId":{"value":"21a5c4f1-5080-ec11-8d21-002248320bcd"},"shared_flowmanagement":{"value":"098c2992-b427-4549-8cdc-ff697a7cfd28"}},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard","actions":["Run"]},"098c2992-b427-4549-8cdc-ff697a7cfd28":{"id":"/providers/microsoft.powerapps/apis/shared_flowmanagement","displayName":"Power Automate Management","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1547/1.0.1547.2676/flowmanagement/icon.png","dataSources":[],"dependencies":[],"dependents":["1a450884-c15c-48a7-8f59-e3d862a35577","e3eb4218-0128-4bae-97db-26f701419535"],"parameterHints":{},"parameterHintsV2":{},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard"},"e3eb4218-0128-4bae-97db-26f701419535":{"id":"/providers/microsoft.powerapps/apis/shared_logicflows","displayName":"Logic flows","iconUri":"https://connectoricons-prod.azureedge.net/releases/v1.0.1534/1.0.1534.2605/logicflows/icon.png","dataSources":["CommandCenterApp&gt;GetCoEFlows"],"dependencies":["098c2992-b427-4549-8cdc-ff697a7cfd28","17e23410-f916-449f-91c1-259d216f4701"],"dependents":[],"parameterHints":{"workflowName":{"value":"de03c2d2-ba73-4190-91ad-a80c6d45b622"},"workflowEntityId":{"value":"86721ee7-cb7e-ec11-8d21-002248320bcd"},"098c2992-b427-4549-8cdc-ff697a7cfd28":{"value":"shared_flowmanagement"},"17e23410-f916-449f-91c1-259d216f4701":{"value":"shared_commondataserviceforapps_1"}},"parameterHintsV2":{"workflowName":{"value":"de03c2d2-ba73-4190-91ad-a80c6d45b622"},"workflowEntityId":{"value":"86721ee7-cb7e-ec11-8d21-002248320bcd"},"shared_flowmanagement":{"value":"098c2992-b427-4549-8cdc-ff697a7cfd28"},"shared_commondataserviceforapps_1":{"value":"17e23410-f916-449f-91c1-259d216f4701"}},"isOnPremiseConnection":false,"bypassConsent":false,"dataSets":{},"apiTier":"Standard","actions":["Run"]}}</ConnectionReferences>`

### Expected Behavior

I expected the solution to import successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

Install COE March 2022 into an environment.
Attempt to upgrade to COE April 2022 release.

### Anything else?

Please advise on how to proceed to upgrade this organization to the current version of the COE

**Comment by Jenefer-Monroe** [comment]
It's been a while since that release but as far as I recall the product team made a change in which they started failing to install for a new situation (in our case a canvas that called a flow that no longer exists, it used to just ignore that case but started failing on it)

I thought that we fast released a fix to that but I dont recall the build number. I would suggest just hopping up to May.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
