### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Sync Template is failing with "admin_environment With Id = 23ac1c29-93f6- Does Not Exist",

### ISSUE THREAD

**Issue by ragbn** [microsoft/coe-starter-kit#3237]
### Describe the issue

Admin | Sync Template flow is failing with following error.

Admin | Sync Template V3 ->Store Environments in the CoE CDS Entity -> Apply to each environments -> Check if legacy env -> Get Environment 

{
  "error": {
    "code": "0x80040217",
    "message": "admin_environment With Id = 23ac1c29-93f6-4957-9066-Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "7f31f3d4-ba07-",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "66ea3b5f-d9d3-4",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "[http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform"](http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform%22),
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_environment With Id = 23ac1c29-93f6-4957-9066Does Not Exist"
  }
}

### Expected Behavior

Admin | Sync Template V3  should run successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40 

### What app or flow are you having the issue with?

Admin | Sync Template V3

**Comment by manuelap-msft** [comment]
Hello,

can you share a screenshot of the flow failure? The failure you're describing is a caught failure (which means it's expected and we have error handling in place to deal with it) so it's likely the actual cause of the failure in your flow fails a bit further down on a different action.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
