### ISSUE TITLE
[ALM Accelerator - QUESTION] Adding DevOps Organisations and Projects to ALMA

### ISSUE THREAD

**Issue by Samuel-Dittmann** [microsoft/coe-starter-kit#3244]
### What is your question?

Hey,

is it possible to add other DevOps Organisations and Projects to the ALMA? I can at least select all of the orgs and projects I have access to in the app.
I tried to use the CoE CLI to reinstall the ALM with different projects and it did install the pipelines, variables and so on.
Though as soon as I try to commit a solution using the new environments it throws an error like
`"$id":"1","innerException":null,"message":"A value for the 'Branch' parameter must be provided.\nA value for the 'CommitMessage' parameter`
Is there a proper way to do this?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220503.1

**Comment by mikefactorial** [comment]
@Samuel-Dittmann looks like you'll need to import the latest version of the solution here https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-July2022. We've made changes to the pipelines since the May release and that in turn required updates to the app and the connector.

**Comment by Samuel-Dittmann** [comment]
@mikefactorial Thank you, this fixed it!
