### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to set up Audit Log subscription in GCC tenant

### ISSUE THREAD

**Issue by faapupala** [microsoft/coe-starter-kit#3246]
### Describe the issue

Trying to set up the CoE kit Audit log subscription but running into an issue with starting the subscription for the custom connector. I've followed the steps in the documentation but still run into it. Any information or help would be appreciated!

![image](https://user-images.githubusercontent.com/109743381/180230233-5eb3f8e4-243d-4d2e-9528-526a935e94c7.png)

### Expected Behavior

The setup goes as detailed here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

Set up

**Comment by manuelap-msft** [comment]
Hello,

the error message says that **gcc.office.com** could not be resolved - is that a value you put in somewhere? 

Note that the government cloud endpoints are - for GCC it's **manage-gcc.office.com** not gcc.office.com
```
If your tenant is a GCC tenant, change the host to manage-gcc.office.com.
If your tenant is a GCC high tenant, change the host to manage.office365.us.
If your tenant is a DoD tenant, change the host to manage.protection.apps.mil.
```

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
