### ISSUE TITLE
[CoE Starter Kit - BUG] App and Flow Archive and Clean Up View Tile Needs Renaming in Command Center

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3248]
### Describe the issue

The App and Flow Archive and Clean Up View tile in the command center needs to be changed to App and Flow Inactivity Notifications Clean Up View

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Admin | Command Center

**Comment by manuelap-msft** [comment]
Hello,

the tiles are populated by the **Command Center App > Initially Populate Bookmarks** cloud flow the first time the Command Center is opened and pull the latest names from there (= we didn't hard code our app names into the Command Center).

I think there's some improvements we need to make to this flow, as if apps are renamed, the new names are not picked up later on.

I'll put this improvement on our backlog for the September release (we're already code complete and testing for August so won't be able to fit this in anymore). In the meantime, you can manually delete all the rows from the Command Center Config table (provided you didn't add your own bookmarks) and re-run the flow to pick them up from scratch or you can also manually change the name of the tab using the Edit Bookmarks button.

**Comment by Jenefer-Monroe** [comment]
Update the name now, but since we determine via the name you will end up with two, so added a "remove" button as well to allow you remove the old one. 
![image](https://user-images.githubusercontent.com/89584709/182910933-68715730-050e-4489-8742-76c09c5b8289.png)
