### ISSUE TITLE
[ALM Accelerator - BUG]: Configured Deployment Setting is not reflecting in Target Environments 

### ISSUE THREAD

**Issue by ShridharDeshpande** [microsoft/coe-starter-kit#3249]
### Describe the issue

The updates to Connection References, Environment Variables, flow ownership, Sharing and Permission on the Configure Deployment Settings page of the ALM Accelerator, are not reflecting in the target environments. I can see the Deployment Settings values in AA4PP Administrator app setting.

![image](https://user-images.githubusercontent.com/47315792/180242191-ee8ef17e-367d-4c05-ba42-cd5a0b3d04f6.png)

And also can see the values in the variables of the pipelines. But after the pipeline run values are not reflecting in target environment solution.

![image](https://user-images.githubusercontent.com/47315792/180242630-b5e67dcb-e3ff-4ec0-ad42-0e877b180e8c.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

July 2022

### Steps To Reproduce

1. Click the Commit Solution,
2. select the target environments from the drop-down.
3. Update the configuration details.
4. Save and Close
5. Commit the changes to the repo.
6. Deploy to validation environments.

**Comment by mikefactorial** [comment]
@ShridharDeshpande can you share an example of where the values aren't updated in the downstream environment? Also, may help to share the logs. Haven't seen this issue before.

**Comment by ShridharDeshpande** [comment]
@mikefactorial I've a used string type environment variable in the solution and kept the current value in developing environment as 'Dev'. and trying to update the value in other environment as mentioned in below configure deployment snap.

![image](https://user-images.githubusercontent.com/47315792/180659262-d1a0ac7d-aa0b-4b7b-9c7b-b9de57a4d3c3.png)

but in the Validation, Test and Prod it is still reflecting as 'Dev'.

![image](https://user-images.githubusercontent.com/47315792/180659364-9d308281-772c-4435-8cf2-930760c6e24e.png)

Also sharing the canvas app with the group and changing owner of the flow for all the target environment.

![image](https://user-images.githubusercontent.com/47315792/180659481-cc7a926d-ff89-4c50-8d55-fa10a435965e.png)

![image](https://user-images.githubusercontent.com/47315792/180659524-a1d59e4c-21d1-474b-843c-f6bf230db2a7.png)

But the canvas not getting share with group and owner of the flow is still the name of the app user for all target environment.

![image](https://user-images.githubusercontent.com/47315792/180659620-40fd14dd-5ac1-4272-8c78-45b45a6a09e9.png)

The pipelines are running successfully without any errors. but still not getting reflected in all 3 target environment.

![image](https://user-images.githubusercontent.com/47315792/180659841-4ddac32c-78d1-49fd-b492-4e0a9309f306.png)

**Comment by mikefactorial** [comment]
Would help to see the logs here, but can you verify that you see the values in the deploymentSettings.json file being replaced in the deployment step "Replace Tokens: deploymentSettings.json?" Similar to below?


![Image](https://user-images.githubusercontent.com/42348035/180831249-18ba983f-ad9d-4d9a-b0a6-4a62f4fc4a3c.png)

**Comment by ShridharDeshpande** [comment]
@mikefactorial The values in the deploymentSettings.json file were being replaced in the Replace Tokens: deploymentSettings.json deployment step. 

![image](https://user-images.githubusercontent.com/47315792/181499237-b07e3e42-d774-4ce7-b5fc-4a5bcfe28f88.png)

Now I changed the ALM version from July-2022 to June-2022, and it's working for me.

**Comment by mikefactorial** [comment]
@ShridharDeshpande thanks for reporting back. The august release was published yesterday if you want to take the latest bits :) Closing for now
