### ISSUE TITLE
[CoE Starter Kit - BUG] There was an error when processing the data in the dataset.

### ISSUE THREAD

**Issue by MarcosCostarella** [microsoft/coe-starter-kit#3251]
### Describe the issue

Yesterday I imported july release core components 3.40 and dashboard stopped refreshing data
![coe something went wrong](https://user-images.githubusercontent.com/106347491/180279257-d6b0a693-e787-483d-b031-d5bd077848a4.jpg)

I decided to update the dashboard as well but when i open it with power bi desktop I get 
![power bi desktop apply changes](https://user-images.githubusercontent.com/106347491/180280031-dd788253-553a-4b63-98d7-6906fadb19a4.jpg)

if i hit apply changes i get
![power bi desktop load](https://user-images.githubusercontent.com/106347491/180280377-15ef430d-1a14-4250-89fe-ca37f93cf3f2.jpg)

### Expected Behavior

It should refresh the connections and let me publish

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Production_CoEDashboard_July2022.pbit

### Steps To Reproduce

I go to my workspace and I see error when refreshing data

**Comment by Jo7926735** [comment]
I had this exact issue also - I ended up re-setting up the PowerBI dashboard from the template in the latest version, and this resolved the issue for me.

**Comment by MarcosCostarella** [comment]
> I had this exact issue also - I ended up re-setting up the PowerBI dashboard from the template in the latest version, and this resolved the issue for me.

How do you re-set? I open the pbit file Production_CoEDashboard_July2022 with power bi desktop from latest release folder kit and I get the pop up error I paste at the end of my previous comment. It is not able to re load the connections to tables.

**Comment by manuelap-msft** [comment]
What version of Power BI Desktop are you using and are you able to upgrade to the latest version of Power BI Desktop, if you're not on it already?

**Comment by MarcosCostarella** [comment]
Please let me know if this is the latest one
![power bi desktop version](https://user-images.githubusercontent.com/106347491/180517744-efcf71d1-5325-4cf2-9f5c-21af06dd8a17.jpg)

**Comment by Jenefer-Monroe** [comment]
To clarify here, we are not referencing the admin_test issue anymore. That was resolved with upgrade. 
So now you are at the point of trying to use the July pbit on the July version of Core and getting **Flow Connection Reference** bug. 

Is that accurate?

**Comment by MarcosCostarella** [comment]
Hi Jenefer, we can now disregard, I finally realized the issue it was I had not removed the backslash from the end of the org url. Once I did the queries were updated

**Comment by Jenefer-Monroe** [comment]
thanks for letting us know!
