### ISSUE TITLE
Getting the following error while turning on the Helper - Make check flow

### ISSUE THREAD

**Issue by shyjujohn** [microsoft/coe-starter-kit#3252]
Hi,

We are getting the following error while turning on the Helper - Maker Check flow.
"Admin data policy 'CoE Toolkit DLP Policy' restricts connector /providers/Microsoft.PowerApps/apis/shared_webcontents to access endpoint @{parameters('Graph URL Environment Variable (admin_GraphURLEnvironmentVariable)')}v1.0/servicePrincipals/@{triggerBody()['text']}."

and the following error while turning on few other flows.

"Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Environments' of type 'OpenApiConnection' at line '1' and column '1603' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}"."

Please help!

Thank You!
Shyju John

**Comment by manuelap-msft** [comment]
If you see an Invalid Pagination Policy error when trying to turn on the flows, it indicates that you are using an insufficient or trial license. All our flows require a medium or high performance profile to run. License requirements are listed in our [prerequisites](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with).

Learn more: [Power Automate performance profiles](https://docs.microsoft.com/en-us/power-automate/limits-and-config#performance-profiles) and [Concurrency looping and pagination limits](https://docs.microsoft.com/en-us/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

See: 
Pre-requisites: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with
Error description (in the first blue paragraph): https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows

**Comment by shyjujohn** [comment]
Hi @manuelap-msft,
 
We have the below license. Please suggest if there is an additional license we have to buy for running the COE toolkit flows.

![License](https://user-images.githubusercontent.com/41447786/180848388-5462e09f-2787-47d8-bee7-bf3b590b7a33.png)

**Comment by manuelap-msft** [comment]
Hello,

yes, there are additional licenses needed, see https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with:

**Power Apps Per User license (non-trial) and Microsoft 365 license.
Power Automate Per User or Per Flow license (non-trial).**

This specifically mentions that the licenses have to be non-trial licenses. You have trial licenses assigned to your account, which we do not support as they don't have the performance profile needed to run the CoE Kit.

**Comment by shyjujohn** [comment]
Thank you so much @manuelap-msft for your quick response.
