### ISSUE TITLE
[CoE Starter Kit] Office 365 Management API is not working and is giving error 401

### ISSUE THREAD

**Issue by vijaypaliath** [microsoft/coe-starter-kit#3253]
### Describe the issue

The customer connected which connects to the Office 365 Management API is not working and is giving error 401. 

### Expected Behavior

Ideally it should be giving status code as 200

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Office 365 Management API Flow

### Steps To Reproduce

Tried with new Secret ID, granting access to API etc but it did not resolve the issue. Auditing has been turned on in the Compliance Center.

**Comment by vijaypaliath** [comment]
I have noticed that whenever "[Child] Admin | Sync Logs" flow runs it gives error "Action 'List_audit_log_content' failed" and Error details "Authorization has been denied for this request."

**Comment by manuelap-msft** [comment]
Hello,

we need a few more details to help with this issue! What error are you getting, can you share screenshots? What steps of https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog have you completed and at what step are you getting an error message?

Screenshots are typically most helpful for us to see what the error could be.

Thank you
Manuela

**Comment by vijaypaliath** [comment]
Hi Manuela,

Thanks for contacting me on this.

What a co-incident, the issue has been fixed. Seriously I don't know how.

I am able to see the data getting populated into Audit Log. Sorry about this.

Kind Regards,

Vijay Paliath
M365 Administrator

**Comment by Jenefer-Monroe** [comment]
closing out, thanks for using CoE
