### ISSUE TITLE
[CoE Starter Kit - BUG] Impacted Flows Not Displaying All Flows in Command Center that need to be Reset

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3257]
### Describe the issue

After resetting the Production Environment variable in the Command Center, the list of flows that is presented after clicking the Reset flows button is missing the flow Admin | Inactivity notifications v2 (Clean Up and Delete) which has the variable in the flow.

![image](https://user-images.githubusercontent.com/17124284/180470948-6ddd35ff-2ed4-4a33-a33d-14d171795c27.png)

There is also confusion in the documentation that states To begin deletion of flows and apps, update the [Auto Delete On Archive environment variable](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#all-environment-variables) to Yes. In the command center this variable is stating deprecated (Although it does still exist in the flow)

![image](https://user-images.githubusercontent.com/17124284/180471595-e824b191-6a04-46b7-b88b-7ccf3c6c702f.png)

and the link in the document leads to the environment variable page which does not have any reference to the Auto Delete on Archive variable.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.18

### What app or flow are you having the issue with?

Admin | Command Center

**Comment by Jenefer-Monroe** [comment]
I do see that flow in the list.

**Comment by medicineshow** [comment]
I did mean the list that is populated when you select the Reset Flows button for the environment variable. Interestingly, the flow is in the list today.
![image](https://user-images.githubusercontent.com/17124284/180739053-675db34a-f637-4754-ba16-3e0d135baa07.png)

**Comment by Jenefer-Monroe** [comment]
No that is the list for Production Environment env var, the list of flows comes from a static table in the app, does this app have an unamanged layer?

**Comment by medicineshow** [comment]
This is then list I see for the Production Environment Variable:
![image](https://user-images.githubusercontent.com/17124284/180868145-4c56ba5f-1c16-49e0-a7d4-2fcab4d511f4.png)

And there are no unmanaged layers in the ap:
![image](https://user-images.githubusercontent.com/17124284/180868357-25820408-1446-4146-8102-8aa375ee53bc.png)

**Comment by Jenefer-Monroe** [comment]
I did some testing today of installs for the August release and I do repro this in my managed installs. I have no idea what is going on but at least I repro! 
Marking as a bug to investigate.

**Comment by Jenefer-Monroe** [comment]
if a flow was never turned on it wont show in this list. which is ok in that it doesnt have a cached env var, but is still confusing. I think we should keep this bug as part of reconsidering how we use the metadata to get all this information.
