### ISSUE TITLE
[CoE Starter Kit - QUESTION] Which flow to reset when changing admin email?

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [microsoft/coe-starter-kit#3263]
### What is your question?

I recently changed the admin email in the command center, but can't figure out which flow to reset to for the change to take effect.  Sync flow error message are still going to the originally configured email address.  There isn't a reset button next to the setting in command center like there is with other settings.  Which flow needs to be reset?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

**Comment by Jenefer-Monroe** [comment]
You can check which flows depend on an env variable by checking its dependencies. 
![image](https://user-images.githubusercontent.com/89584709/180879680-9ac7050d-e5de-45a4-9cae-2e0f54b6a799.png)

Hope that helps

**Comment by DaveTheTeamsGuy** [comment]
That's helpful, thank you.

**Comment by Jenefer-Monroe** [comment]
Glad to help!
