### ISSUE TITLE
[CoE Starter Kit - BUG] Orphaned apps setting Maker as Blank

### ISSUE THREAD

**Issue by ashculmsee** [microsoft/coe-starter-kit#3269]
### Describe the issue

Previously, apps that had been orphaned had their Maker Display Name set to "Unknown".
<img width="173" alt="image" src="https://user-images.githubusercontent.com/96230040/180935899-ff0d43ba-9247-4dad-b30c-5e71510e8a1d.png">

However, we are now seeing orphaned apps having nothing set in these fields. 
<img width="172" alt="image" src="https://user-images.githubusercontent.com/96230040/180935950-9c57e800-fc60-4b2c-95a9-60eadc9950f0.png">
<img width="717" alt="image" src="https://user-images.githubusercontent.com/96230040/180936227-e7c65d61-cf3c-4a2f-b1f0-858bc761f4f4.png">

This means that in the CoE Dashboard, we now have a blank entry in the "Makers" alongside our "Unknown" maker.
<img width="113" alt="image" src="https://user-images.githubusercontent.com/96230040/180936121-4b5ac3bc-3516-4f76-8b0d-528fa17ff7f5.png">

### Expected Behavior

Apps that are orphaned should have their Maker Display Name set to "Unknown" so that there is less confusion when viewing the CoE dashboard and that data matches.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

**Comment by manuelap-msft** [comment]
Hello,

I don't recall us ever setting this to Unknown, I think it's always been Blank. Could it be that you had a customization on top of this flow that marked it as Unknown instead of Blank?

Manuela

**Comment by paulculmsee** [comment]
hehe, I don't recall either :-)  We can solve the problem on the PowerQuery side if you think that's a better approach

**Comment by manuelap-msft** [comment]
I'll chat with Jenefer; I think it may be best if we solve it in PowerQuery - as if we change it in the flows now that might lead to inconsistent behaviour for customers who don't always run a full inventory to update all fields and we try to avoid making changes that require a full inventory to be run.

**Comment by Jenefer-Monroe** [comment]
Moving to be a bug to address in the PBI

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
