### ISSUE TITLE
[CoE Starter Kit - Feature Ask] Exclude Teams Environments Virtual Agents and Cleanup flows

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#3270]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/3267

<div type='discussions-op-text'>

<sup>Originally posted by **federicoruiz** July 26, 2022</sup>
Hi everyone! 
 
We are having some Teams environments (with no apps, no flows) with the exclusively and productively use of Virtual Agents, and we know that because of these [aren't discoverable in the CoE Starter Kit these environments](https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#microsoft-teams-admin--weekly-clean-up-of-microsoft-teams-environments) the environments always goes into the Clean Up processes. 
We tried checking **Excuse from archival** process and provide justifications but it doesn't work.

¿We need to delete manually these records from the Environments table? (To force these environments run again the cleanup process)

Also, we observe similar behaviour on flows too, checking **Excuse From Inactivity Flows**, cleanup process repeats asking to the user for a justification.

¿Could we add a new Field, e.g **"Exclude from cleanup flows"** and then configure a trigger condition to filter that flows/apps in the cleanups flows? From some people this process are a little intrusive. and we need a way to avoid that.

Thanks a lot for any help.
Regards</div>

**Comment by Jenefer-Monroe** [comment]
Confirmed with issue poster the ask:
We have a flow that cleans up unused teams environments if there's no apps/flows in them.
We should add the ability to exclude Teams environments from this cleanup process (for this user this is for environments in which they only have chatbots since we cannot inventory those in D4T)
This will be another "Excuse from D4T Cleanup" type field on the envt table.

**Comment by Jenefer-Monroe** [comment]
implementing another exclude option for environments for Sept
