### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot add Dataverse Connection to [Child] Admin | Sync logs flow after July install

### ISSUE THREAD

**Issue by samadane** [microsoft/coe-starter-kit#3272]
### Describe the issue

Installed July COE toolkit version.  The audit solution has an error.  Cannot add Dataverse "connections used" to the flow [Child] Admin | Sync Logs

![image](https://user-images.githubusercontent.com/43175066/181010113-70ba9fdc-7fef-40bd-86f9-a188be89d589.png)

### Expected Behavior

Should be able to go to the child flow and choose the Dataverse connections created for the user.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

Install July Audit log solution
go to this child flow and try to select a dataverse connection. none show up
Go create another dataverse connection
Go back to child flow, connection still does not show up

**Comment by samadane** [comment]
customer can see connections, but not once they go back to the flow, and that is the user that owns the flow and the connection.

![image](https://user-images.githubusercontent.com/43175066/181073658-a1bd5380-fb68-4d9e-8063-1cfc2070af8d.png)

**Comment by Jenefer-Monroe** [comment]
It appears you have hit a product bug then as we arent doing anything special here, you are just using the product UX. 
I think you will need to reach out to the product team or to support. Please let us know what you hear back.

**Comment by samadane** [comment]
Will do!

**Comment by samadane** [comment]
It just fixed itself :) Feel free to close this out.

**Comment by Jenefer-Monroe** [comment]
Good news! Any tips on how you fixed it? In case others see this.

**Comment by samadane** [comment]
Customer just went back to it.  Potentially turning it on / off?

**Comment by Jenefer-Monroe** [comment]
woohoo! Glad its resolved! I'll close this out now.
