### ISSUE TITLE
[CoE Starter Kit - BUG] Apps Inventory not complete - iconURI returning null and connector action breaks as a result. 'The API operation 'Get-AdminApps' requires the property 'body/value/162/properties/connectionReferences/2/iconUri' to be of type 'String' but is of type 'Null'.'

### ISSUE THREAD

**Issue by TetefBubu** [microsoft/coe-starter-kit#3274]
### Describe the issue

Currently we have an issue with the Apps Inventory, the automate only inventory 9 apps instead of more than one thousand.

We tried to set in the admin command center the Full Inventory parameter to Yes, but still.. The Apps inventory is still not correct.

The Env count and Flow count number seems to be correct.

What an I do ?

Thanks in advance.

Best Regards.

### Expected Behavior

Full Apps Inventory

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin - Sync Template V3

### Steps To Reproduce

N/A

**Comment by Jenefer-Monroe** [comment]
Can you please confirm a few things for me? 
- Does the identity running the flows have the Power Platform administrator role permanent assigned? 
Please see [What identity should I install the CoE Starter Kit with?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with) for the full list of requirements for the identity that sets up and runs the kit. 
- Does the issue only repro for canvas apps? You see the full inventory for cloud flows for example
- Does the issue only repro for your Default environment? Or are other environment counts also off? 
- All flows listed in the [core inventory setup instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) are turned on
- Do you have failures in this flow? **_Admin | Sync Template v3 (Apps)_**

**Comment by TetefBubu** [comment]
Hi Jenefer,

- The identity has all the requirements (PowerPlatform admin and Licences powerApps and PowerPlateform by user, and O365 E1 + PowerBI Pro)
- The CoE Inventory contains only 189 Apps (Canvas and Model Driven), The PS Inventory contains 1191 Apps. Regarding Flows inventory it seems to be ok, The CoE Inventory contains 1980 flows and the PS Inventory contains 1974 flows (the différence should come from 1 day delay between both inventory).
- No : Apps are missing from all Environnements
- All flows listed in the setup guide are turned on, but I have an issue with this one : "Admin | Sync Template v3 (Sync Flow Errors)", and these flows don't exist in our solution : "CLEANUP HELPER - Check Deleted (Business Process Flows), Admin | Sync Template v3 CoE Solution Metadata, Admin | Sync Template v3 (Connection Identities)"
- no failures with Admin | Sync Template V3 (Apps)
- 
![image](https://user-images.githubusercontent.com/108397783/181200867-5d9bf96c-c214-46db-b6e5-4ba7fcd1f117.png)

**Comment by TetefBubu** [comment]
Hi Jenefer,

Sorry I didn't correctly check the execution for the Sync Template V3 (Apps), there is a failed (for the default Env with Get Apps as admin) : I suppose that the issue is only with that environnement.

The API 'powerappsforadmins' returned an invalid response for workflow operation 'Get_Apps_as_Admin' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-AdminApps' requires the property 'body/value/162/properties/connectionReferences/2/iconUri' to be of type 'String' but is of type 'Null'.'


![image](https://user-images.githubusercontent.com/108397783/181256711-72e430af-78d5-4dc2-972c-cd535d8042cf.png)

**Comment by Jenefer-Monroe** [comment]
That is some kind of product issue. Looks like some app in your inventory doesnt have an icon and the connector does not error check that. You will need to reach out to support so that the product team can address. 

Before doing so, I suggest you create a new flow with just this action.

![image](https://user-images.githubusercontent.com/89584709/181275957-bf9af101-8810-4d42-8403-2f38bb24ae3b.png)

Once you have the action, add your Envt Name (as shown above) and change the version to be 2020-07-01
![image](https://user-images.githubusercontent.com/89584709/181278699-4ac9dae3-17d3-46d5-95b2-c34f85b2dd24.png)

Lastly, in order to ensure you get the problematic app, update the pagination setting to 100000 (this will also match what the kit does)
![image](https://user-images.githubusercontent.com/89584709/181278889-eb616410-605c-4b54-bdee-49ddff7eb650.png)
![image](https://user-images.githubusercontent.com/89584709/181279081-432c57fb-ee46-41ac-8048-a13b5f6799cf.png)


Save and run.

**Comment by TetefBubu** [comment]
I did it, and I have the same result.


![image](https://user-images.githubusercontent.com/108397783/181291431-c7bf53fa-fc19-432d-a67a-1220a960aabe.png)

I can't find where to find the API request result (even if it's not complet).

I checked the result of the cmdlet $AllApps=Get-AdminPowerApp -EnvironmentName "Default-....." -ApiVersion "2020-07-01", using fiddler.
But the returned json didn't contain any "iconUri": with a null value 😿.

Next step : I'll open a support case regarding the "Get Apps Admin" issue.

Thanks for help.

**Comment by Jenefer-Monroe** [comment]
You bet. I'll keep this open if you dont mind so I can hear the results. 
Thanks for using CoE!

**Comment by TetefBubu** [comment]
Finally, I found the app with connector issue in the PS cmdlet JSON result.
It was not a null value, but a missing property (no iconUri property). And it was in the 162 index value as we can see in the error message : body/value/**162**/properties/connectionReferences

From our side we do not have an issue anymore, but we will open a case because, this kind of connector error can appears again in the futur.

_"ee7bde5d-95d4-4a9b-b469-7a077bc6ac60": {
						"id": "fed98814-c5dd-4f80-90e9-e2a1677b80e4",
						"dataSources": [
							"xxxxxxx"
						],
						"dependencies": [],
						"dependents": [],
						"isOnPremiseConnection": false,
						"bypassConsent": false,
						"dataSets": {
							"https://xxxxxxxxxxx.sharepoint.com/sites/app-k20003": {
								"dataSources": {
									"xxxxxxxxxxxxx": {
										"tableName": "fed98814-c5dd-4f80-90e9-e2a1677b80e4"
									}
								}
							}
						},
						"isCustomApiConnection": false
					},_

**Comment by Jenefer-Monroe** [comment]
Thanks for the update! And yes please post this so the product team can address for future cases. 
Thanks for using CoE and being such a helpful customer!!!

**Comment by lheng182022** [comment]
@TetefBubu, thanks for reporting the issue. I wonder if you have opened a support ticket on this issue for prod. if so, have you heard anything from them?

**Comment by manuelap-msft** [comment]
Closing out as no further action required from the CoE kit team.
