### ISSUE TITLE
Makers Statistics doesn't get populated in Power BI reports

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#3278]
### Describe the issue

Makers Statistics doesn't get populated in Power BI reports despite having a maker in the system

![image](https://user-images.githubusercontent.com/17232756/181143298-cd53242c-00e0-4fdd-833b-aeb0b918ce74.png)

See the Makers List

![Uploading image.png…]()

### Expected Behavior

Makers statistics should get populated

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Power BI Production CoE Dashboard

### Steps To Reproduce

1. Open the Power BI Production CoE Dashboard
2. Navigate to 'Overview - Power Apps' report

**Comment by Jenefer-Monroe** [comment]
Please go make sure that all the flows in  [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) are turned on and running. (ex do see runs for flows like **_HELPER – Maker Check_** and **_Admin | Sync Template v3 (Apps)_**)

See also if there is data in the tables, you can see this by going to the [Power Platform Admin View app](https://docs.microsoft.com/power-platform/guidance/coe/core-components#power-platform-admin-view)

**Comment by girishuppal** [comment]
The flow is running fine. 

Makers does exist in backend but not getting populated in reports
![image](https://user-images.githubusercontent.com/17232756/181661413-22799212-e074-4b6b-b4d7-b9153d149f69.png)

**Comment by jukkan** [comment]
This is likely caused by the data type of the isSystem column that is used as a default filter in the CoE  report. Please see issue #3322 for a workaround on how to fix it on your report.

**Comment by girishuppal** [comment]
Thanks @jukkan  for the response. Else i would have gone round and round with generic responses. Thanks a ton.

**Comment by Jenefer-Monroe** [comment]
Agree. I think it would have been a long way before I heard you all correctly. So thanks @jukkan for going above and beyond! 

We have to reship the dashboards anyway for #3318 so I went ahead and fixed this. 
Here they are ahead of releasing them, in case you would like an early copy: [August PBITs with alt key removed.zip](https://github.com/microsoft/coe-starter-kit/files/9242700/August.PBITs.with.alt.key.removed.zip)

**Comment by manuelap-msft** [comment]
We have re-released the PBIT files to address #3322 and #3318. They're available when you re-download https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-August2022/CoEStarterKit.zip
