### ISSUE TITLE
Power BI Virtual Agents report doesn't get populated

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#3279]
### Describe the issue

Power BI Virtual Agents report doesn't get populated

![Uploading image.png…]()

### Expected Behavior

Power Virtual Agents report should get populated

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Power BI Production CoE Dashboard

### Steps To Reproduce

1. Open Power BI Production Dashboard
2. Navigate to 'Virtual Agents' report

**Comment by girishuppal** [comment]
Reuploading Image as it was not loading while raising a ticket

![image](https://user-images.githubusercontent.com/17232756/181144050-949ac50a-af64-4af7-837b-1034c21f4589.png)

![image](https://user-images.githubusercontent.com/17232756/181144187-cb004f1b-f2c9-48b1-931b-6efa2593b7e4.png)

**Comment by Jenefer-Monroe** [comment]
Please go make sure that all the flows in  [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) are turned on and running. (ex do see runs for flows like **Admin | Sync Template v3 (PVA)**)

Please also make sure that you have the Power Platform admin role permanently assigned. You can double check all the identity requirements for the user installing the kit here: [What identity should I install the CoE Starter Kit with?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by girishuppal** [comment]
![image](https://user-images.githubusercontent.com/17232756/181169538-c3b29973-3b7f-4016-9f46-983dfa47ca53.png)

Admin role is permanently setup.

**Comment by girishuppal** [comment]
All Sync Template v3 perfectly running fine. But still the Bot information doesn't get populated in 'Power Platform Admin View' app
![image](https://user-images.githubusercontent.com/17232756/182768441-7fd3af1c-e6af-418b-bb33-cbc3b114679e.png)

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately, that does not help in debugging this issue. I will paste here once more the instructions on how to isolate the issue you describe. Without you doing the steps below we will not be able to assist.  

The COE Starter kit available as an open-sourced and unsupported set of components, we do best efforts to assist users, but are unable to debug issues without the user doing the work on their tenant to find the specifics. 

If you are unable to do the steps below you may need to hire a partner to do debugging. You can find CoE expertise partners via AppSource: 
https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1


> You will need to find a repro of this in your tenant to see what is going wrong.
> 
> 1. Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)
> 2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
>    Note you will want to change back so be aware of the change.
>    ![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)
> 3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
>    Ex: if you are looking for missing canvas apps chose **_Admin | Sync Template v3 (Apps)_**
>    ![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)
> 4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself.
>    ![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)
> 5. From here you can explore if there is a failure, or if a bad return set, etc. And let us know if you have questions

**Comment by girishuppal** [comment]
I believe thats what i displayed in my previous response. Please find it again.

![image](https://user-images.githubusercontent.com/17232756/183324163-d333b0fd-7bc2-4594-85fb-ccf42a336128.png)

![image](https://user-images.githubusercontent.com/17232756/183324213-e11a9aea-cc83-49a0-aa62-3ed2e30edbc1.png)
![image](https://user-images.githubusercontent.com/17232756/183324771-bfcd499a-5f00-47f9-b209-5ea7b21fc38c.png)
![image](https://user-images.githubusercontent.com/17232756/183324866-3374f71e-28c5-40ad-8513-ece8befcf94d.png)

**Comment by girishuppal** [comment]
Bot do exist in this environment
![image](https://user-images.githubusercontent.com/17232756/183325057-2de6b6b3-d797-4369-8176-18ee4198df63.png)

**Comment by girishuppal** [comment]
![image](https://user-images.githubusercontent.com/17232756/183325238-f37931b7-ed7b-48c1-8980-47be3b6b36ea.png)

**Comment by Jenefer-Monroe** [comment]
Your previous response only showed the flow passing 
![image](https://user-images.githubusercontent.com/89584709/183450393-138ee637-6d90-4b0b-baba-560e39872eaa.png)

**Comment by Jenefer-Monroe** [comment]
Are all your repros in environments of type Developer? You can check this in the [admin center](https://admin.powerplatform.microsoft.com/environments)

![image](https://user-images.githubusercontent.com/89584709/183450980-a67995ef-9c4e-4a2a-aa55-9f9ba0bcb879.png)

**Comment by girishuppal** [comment]
![image](https://user-images.githubusercontent.com/17232756/183524243-a1a0eae4-1f6f-459b-9ca7-a07431b06543.png)

**Comment by Jenefer-Monroe** [comment]
ok then yes unfortunately this is a known limitation. We cannot collect these types of objects in Dev environments
Please see our [limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations#sync-flow-limitations-for-developer-and-microsoft-team-environments)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
