### ISSUE TITLE
Powershell Command Execution Visibility

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#3280]
### Is your feature request related to a problem? Please describe.

CoE must provide a screen to show how many users are using Power shell to execute power apps related command?

Using powershell for provisioning, creating, updating and deleting resources

### Describe the solution you'd like

A list of makers or admin using Power shell for getting task done

### Describe alternatives you've considered

Surface in Power BI reports

### Additional context?

Adding this will allow organisation to control or promote shell based coding and identify talents within the organisation

Identify open connections left
Identify usage of PowerShell, Cloud shell etc for connection

**Comment by mikefactorial** [comment]
@girishuppal this sounds like a CoE Starter Kit request but it's tagged as ALM Accelerator. Is the ask here to expose the agent responsible for an action in the Power Platform. Would assume this wouldn't be specific to Powershell since commands executed in Powershell are the same as the commands executed in the UI and / or through the API directly. Adding @Jenefer-Monroe and @manuelap-msft

**Comment by manuelap-msft** [comment]
As far as I'm aware, we do not have insights into PowerShell usage. We don't know how runs PowerShell cmdlets, and I'm not aware of any logging of it. If you are aware of activity logging for PowerShell, let us know and we can see how we can query it.

**Comment by girishuppal** [comment]
It would be good report to view how many power shell commands were executed and by which maker. Just an idea. So that we can identify pro-devs or aspiring pro-devs within the organisation.

**Comment by manuelap-msft** [comment]
Hello,

currently, there's no way we're aware of of tracking this, this is not part of the audit log / activity logging. You can submit this as an idea for the Product Engineering Group to consider here: https://powerusers.microsoft.com/

I'll close this in the meantime as it's not actionable for us.

Thank you
Manuela
