### ISSUE TITLE
[CoE Starter Kit - QUESTION] How does the PowerApps Connector table get populated?

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3282]
### What is your question?

How does the PowerApps Connector table get populated? Is it a dynamically populated table from the Microsoft current list of connectors?

![image](https://user-images.githubusercontent.com/17124284/181235657-42e4d06f-02c9-48f6-9f4e-5b37fdbe41d1.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

PowerApps Connector Table

**Comment by medicineshow** [comment]
Sorry @manuelap-msft . Does this flow connect to an external site to get the list of all Microsoft Connectors currently available? We cannot see how this is achieved in the flow and would like to understand how it is. Thanks.

**Comment by manuelap-msft** [comment]
Oh! I see, sorry I misunderstood your question. We use the Get Connectors action of the **Power Apps for Makers** connector to get a list of all connectors: https://docs.microsoft.com/en-us/connectors/powerappsforappmakers/#get-connectors - we query that with the Default environment.

**Comment by manuelap-msft** [comment]
Here's the action we use
![image](https://user-images.githubusercontent.com/55705669/181257604-057f3e59-bec4-4b9f-81ce-d7299a3e7f76.png)

This does not return these three connectors as they're not treated as connectors but more platform capability - we add them manually, as we need them to show if an app/flow uses them - just for info:
- HTTP
- HTTP Webhook
- HTTP Request Received
- Spatial Services

**Comment by medicineshow** [comment]
Just to clarify. Do you mean this action gets a list of all connectors available in the environment? Because when you are asked to select connectors in the environment request app, the Power Apps Connector table appears to be populated with ALL available connectors (plus some) which may not necessarily be currently used in any environment.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
