### ISSUE TITLE
CoE Toolkit questions

### ISSUE THREAD

**Issue by simonarbel** [microsoft/coe-starter-kit#3285]
Hello

A customer of mine is using the CoE toolkit and has some questions:

1. Audit Logs missed due to truncated results even though the chunking size is 1 minute. How do we reduce the chunking size to seconds?

2. The environment request components consist of two apps:
                • Environment Requests (For admins)
                • Environment Request (For users): Environment Request app for makers to request environments and connectors. 
    
    Do we need to grant makers the Power Platform Maker security role in the CoE environment also?

3. The governance components solution contains the Cleanup Old Objects App app for makers and admins to manage archive approvals. Do we need to grant makers the Power Platform Maker security role in the CoE environment also?

4. CoE Audit log solution only contains Power App launch details, how can other Power Platform audit logs be made available in the CoE toolkit?

5. App Catalog: We have installed the CoE toolkit in a production environment with Dataverse. Does this mean that every user to whom we want to give access to the App catalog one of the below conditions need to be true?
  1. Users need to have a Per User license
  2. App needs to be assigned a Per App license
  3. Environment needs to be covered by pay-as-you-go

**Comment by Jenefer-Monroe** [comment]
> 1. Audit Logs missed due to truncated results even though the chunking size is 1 minute. How do we reduce the chunking size to seconds?

You have reached the limits of what the custom connector is capable of doing. The solution to tenants this large is to use the tenant written audit log into a datalake. We will be working to integrate this into the kit as they become more code complete, target this fall. Until then you can explore yourself here:

https://docs.microsoft.com/power-platform/admin/self-service-analytics
https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate


> 2. The environment request components consist of two apps:
> • Environment Requests (For admins)
> • Environment Request (For users): Environment Request app for makers to request environments and connectors.
> 
Please post this one separately, its a different engineer and I will assign to her.

> 3. Do we need to grant makers the Power Platform Maker security role in the CoE environment also?

We do not recommend adding a security group to the environment. Please see [Create your environment](https://docs.microsoft.com/power-platform/guidance/coe/setup#create-your-environment)
![image](https://user-images.githubusercontent.com/89584709/181257074-96bc1b45-5828-4aa1-a813-15436a999f1c.png)

> 4. The governance components solution contains the Cleanup Old Objects App app for makers and admins to manage archive approvals. Do we need to grant makers the Power Platform Maker security role in the CoE environment also?

Yes that is the purpose of the SR, to grant makers the permissions to the CoE tables. I think I dont understand your question.

> 5. CoE Audit log solution only contains Power App launch details, how can other Power Platform audit logs be made available in the CoE toolkit?

We do not have a solution for that today. 

> 6. App Catalog: We have installed the CoE toolkit in a production environment with Dataverse. Does this mean that every user to whom we want to give access to the App catalog one of the below conditions need to be true?
> - Users need to have a Per User license
> - App needs to be assigned a Per App license
> - Environment needs to be covered by pay-as-you-go
> 

Correct, all our apps are based off Dataverse and so the users or the app will need premium licensed.

**Comment by simonarbel** [comment]
Thanks a ton Jenefer!  I posted #2 in a new thread as requested.

**Comment by Jenefer-Monroe** [comment]
You are welcome, I will go ahead and close this then, but please let us know if you have more questions later.
