### ISSUE TITLE
[CoE Starter Kit - QUESTION]  How Update environment variables

### ISSUE THREAD

**Issue by bethleota** [microsoft/coe-starter-kit#3287]
### What is your question?

I am working on the Admin Command Center and had our security team complete the Azure AD app registration for me since I don't have permissions to do so. Security guy sent me the Application (Client) ID and Client Secret, but I think I entered the wrong GUID in the Client secret. Is there someway for me to change that? I see the Environment Variables link while in the CoE Solutions and Apps, but am unable to change them. In attached image, it previously showed 4 environment variables to be updated. Now it shows 2 so I can't change it here
![PowerPlatformCoEEnvrionmentVariables](https://user-images.githubusercontent.com/40639953/181275285-5c0c1e65-e8ce-4cc1-ba8f-8e69b5c9edf3.png)
.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Admin Command Center

**Comment by manuelap-msft** [comment]
If you've installed the solution in a production environment, do the following to update environment variables:

Go to [Power Automate](https://flow.microsoft.com/).
On the left pane, select Solutions.
Select the Default Solution, and change the filter to show Environment Variables.
Select a variable that you want to update, and then configure its Current Value.

**Comment by Jenefer-Monroe** [comment]
Here is some more information from our tips and faq page :)

[Update environment variables](https://docs.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables)

**Comment by bethleota** [comment]
Hmmm...I only see one environment variable listed. And yes, our CoE is in Production environmen
![DefaultSolution-EnvVariable](https://user-images.githubusercontent.com/40639953/181281081-e48c11a0-40e2-4a58-92ca-40986ec25acf.png)
![DefaultSolution-EnvVariable2](https://user-images.githubusercontent.com/40639953/181281086-03d3f5f0-8325-46e1-a07f-a608eb308615.png)
t

**Comment by manuelap-msft** [comment]
The solution may be called All Solution Components and not Default solution. Do you have that? I just noticed that change in my environment.

**Comment by bethleota** [comment]
thank you both. @Jenefer-Monroe  trying your solution now

**Comment by bethleota** [comment]
@Jenefer-Monroe I was able to save the correct client secret using the Admin Command Center app. Instructions say "After changing the value of an environment variable, you'll need to turn off and on all the flows that use that environment variable to make sure the flows use the latest value.". 

I'm not sure what all the flows are that use these environment variables. Do you?

**Comment by Jenefer-Monroe** [comment]
You can find the dependent flows using the product as shown here. 
You go to the env variable in the solution and chose to Show dependencies. You are looking to restart everything that is object type process
![image](https://user-images.githubusercontent.com/89584709/181287382-801a210f-2013-4258-bb11-472c37600606.png)
![image](https://user-images.githubusercontent.com/89584709/181287571-18438459-77e2-4735-90d9-e67c53829291.png)

**Comment by bethleota** [comment]
WOW - that's a lot of Flows. I'll give it a try. Thank you.

**Comment by Jenefer-Monroe** [comment]
You environment variable will not have that many dependencies. This is a different env var, I just have these pictures for the general answer :)

**Comment by bethleota** [comment]
@Jenefer-Monroe I went through and turned off/on all Flows I could find before I received your reply. <sigh> Again, I'm not sure what env var are used by Command Center. I'm guessing Command Center - Client Secret and Application Client ID since that's where I added the GUIDs. Neither of these have Object Type: Process. There are no Flows for admin_CommandCenterClientSecret or admin_CommandCenterApplicationClientID. Since I made this change, my Power BI report refresh keeps failing. Totally stuck.
![Dependencies1](https://user-images.githubusercontent.com/40639953/181597035-ee87034f-c498-4131-9b4c-64c69ce43efd.png)
![Dependencies2](https://user-images.githubusercontent.com/40639953/181597040-1b46f67f-87ef-42fe-bf7e-f3243af4a929.png)

**Comment by Jenefer-Monroe** [comment]
I'm a little lost here. You originally asked how to update these two env vars: Application (Client) ID and Client Secret. 
In the command center they woudl show here:
![image](https://user-images.githubusercontent.com/89584709/181605375-ee9c742b-6e1a-4b06-9380-c28e41fb85f1.png)

Then you just needed to find those to get their dependencies, example: 
![image](https://user-images.githubusercontent.com/89584709/181605554-205c1590-ccc1-47d5-a01b-7e0a68ae3ef5.png)

It does appear that there are no flows dependent on this so no resetting required.

**Comment by bethleota** [comment]
Ok. So any advice as to why the PBI report keeps failing on refresh? This started right after I changed the environment variables. This is the error I get. It seems that "Table: Business Process Flows" is the issue:
Data source error: {"error":{"code":"DMTS_OAuthTokenRefreshFailedError","pbi.error":{"code":"DMTS_OAuthTokenRefreshFailedError","parameters":{"ConnectionDetails":"{\"kind\":\"Cds\",\"path\":\"https://orgcd70593f.crm.dynamics.com/\"}","CredentialType":"OAuth2","DatasourceType":"Extension"},"details":[{"code":"DM_ErrorDetailNameCode_UnderlyingErrorMessage","detail":{"type":1,"value":"AADSTS700003: Device object was not found in the tenant 'my company tenant GUID' directory.\r\nTrace ID: 1f13e717-2ac0-4fbb-9c2e-06805f4c4e00\r\nCorrelation ID: a9cdcf3a-8343-4ae8-8cf6-50faaef918e7\r\nTimestamp: 2022-07-28 18:00:55Z"}},{"code":"DM_ErrorDetailNameCode_UnderlyingErrorMessage","detail":{"type":1,"value":"AADSTS700003: Device object was not found in the tenant 'my company tenant GUID' directory.\r\nTrace ID: 1f13e717-2ac0-4fbb-9c2e-06805f4c4e00\r\nCorrelation ID: a9cdcf3a-8343-4ae8-8cf6-50faaef918e7\r\nTimestamp: 2022-07-28 18:00:55Z"}},{"code":"DM_ErrorDetailNameCode_UnderlyingHResult","detail":{"type":1,"value":"-2146233088"}}],"exceptionCulprit":1}}} Table: Business Process Flows.
Cluster URI: WABI-US-EAST2-B-PRIMARY-redirect.analysis.windows.net
Activity ID: 4af4a225-cfc1-4ace-8f0a-600bda503c24
Request ID: 775658e4-dac2-d7cc-ff47-21966c738e03
Time: 2022-07-28 18:00:55Z

**Comment by Jenefer-Monroe** [comment]
Env variables dont have anything to do with the PBI. So these are not related issues. 
This error reads differently than I'm used to so I'm not positive but it sounds like you are using mismatched versions of the PBI and Core.
The reason I'm not sure is that it sounds also like an auth issue, and that might just be the first table it tried. Are you logged in to PBI with the same identity as you installed the kit? 
If not, are you logged in to PBI with an identity that has sys admin access to the coe environment?

**Comment by bethleota** [comment]
Ah ok. The timing just seemed odd. I'm logged into the CoE using our CoE service account, but the PBI is configured under my user account. However, I have also granted the CoE service account Admin (Owner) permission to the dataset. It's been refreshing daily since we updated the CoE on 7/11/22. I just tried to refresh the PBI report using our CoE service account and got the same error, except error now says: Table: Connector.

Next I refreshed it alternately using my account and then CoE svc account. Each time, a different table is listed in the error:
Table: Virtual Agent Flows.
Table: Virtual Agent Flows.
Table: Environment Capacity.
Table: Flow Connection Reference.
Table: Virtual Agent Component.
Table: Virtual Agent.

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont know what state you are in here. I suggest starting from a clean version of the PBIT which matches your Core version, which I believe would be this one
[Production_CoEDashboard_July2022.zip](https://github.com/microsoft/coe-starter-kit/files/9213650/Production_CoEDashboard_July2022.zip)

**Comment by bethleota** [comment]
@Jenefer-Monroe thank you! I'll give that a try.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by bethleota** [comment]
thank you @Jenefer-Monroe, I was able to find the Flows that needed to be run for the Admin Command Center. It's working now. The Power BI report is also synchronizing. You were all very helpful.

**Comment by bethleota** [comment]
thank you @Jenefer-Monroe, I was able to find the Flows that needed to be run for the Admin Command Center. It's working now. The Power BI report is also synchronizing. You were all very helpful.

**Comment by Jenefer-Monroe** [comment]
wonderful news. Thanks for using CoE!
