### ISSUE TITLE
Maker access to CoE environment for Environment Request apps

### ISSUE THREAD

**Issue by simonarbel** [microsoft/coe-starter-kit#3288]
A question from my customer:

The environment request components consist of two apps:
• Environment Requests (For admins)
• Environment Request (For users): Environment Request app for makers to request environments and connectors.

Do we need to grant makers the Power Platform Maker security role in the CoE environment also?

**Comment by Jenefer-Monroe** [comment]
Assigning to Denise to let you know the required SR's.

**Comment by simonarbel** [comment]
Hello
Any update on this?

**Comment by denisem-msft** [comment]
You are correct, to allow Makers to Request new Environments with the app, assign them the Power Platform Maker SR role:
![image](https://user-images.githubusercontent.com/43950360/191100748-32833988-4ff4-4295-9a4a-d32849954d2a.png)

This is also called out in our [documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-environment-components#share-apps-with-admins-and-makers):
![image](https://user-images.githubusercontent.com/43950360/191100897-48971698-cf81-4d5e-8b58-cb47fe007705.png)
