### ISSUE TITLE
Our CoE Power BI dataset will not refresh. 

### ISSUE THREAD

**Issue by diane-weisberger** [microsoft/coe-starter-kit#3291]
Does anyone know how to contact support for an issue like this?  We are relatively new to the CoE toolset. 
thanks in advance!

Data source error: The '<pii>admin_sharedtotal</pii>' column does not exist in the rowset. Table: App.
Cluster URI: WABI-US-EAST2-redirect.analysis.windows.net
Activity ID: 8e49c3d7-5b1a-43ce-bf3d-684e0b1016e0
Request ID: c23c8fa9-7ca0-d09c-2033-06a0e9836942
Time: 2022-07-27 17:33:56Z

**Comment by Jenefer-Monroe** [comment]
The CoE starter kit is an [unsupported set of features](https://docs.microsoft.com/power-platform/guidance/coe/overview#disclaimer) that you can use to extend the PP admin features. That said, we do best effort to help people with the kit, and this is the right place to post those issues for us to address.

**Comment by Jenefer-Monroe** [comment]
Note that the version of Core and the version of PBI need to match. So for example today we shipped the August release. **_Core version 3.41_** which would go with PBIT version **_Production_CoEDashboard_August2022_**

I remember an issue like this occurring a few months ago, can you get your version of Core that you have installed? Likely your resolution will be to [upgrade to the latest version](https://docs.microsoft.com/power-platform/guidance/coe/after-setup) and try the new PBI template.

**Comment by girishuppal** [comment]
Even I faced the similar issue. Its a version mismatch issue. Looks like Power BI report version is higher than the other version components. As it is clearly visible from the error that an additional field exist in the report which is missing in core components data structure. Version upgrade should ideally fix the issue (Post reloading of tables).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
