### ISSUE TITLE
[CoE Starter Kit - BUG] Solution "Center of Excellence - Core Components for Teams" failed to import: AttributeId is null

### ISSUE THREAD

**Issue by keharrin** [microsoft/coe-starter-kit#3292]
### Describe the issue

I am upgrading our COE Environment with the latest solutions.  When I attempt to import the following solution.  I get this error message but I am not sure where to update AttributeID
Solution "Center of Excellence - Core Components for Teams" failed to import: AttributeId is null

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.21

### What app or flow are you having the issue with?

NA

### Steps To Reproduce

1.  In COE Environment
2. Import Solution
3. Browse to CenterofExcellenceCoreComponentsTeams_3_21_managed.zip
4. Click Next

**Comment by Jenefer-Monroe** [comment]
As an FYI, the latest version of Core for Teams is 3.22 not 3.21. 

Can you please share a screenshot of the solutions in your environment? The easiest way to do that for Teams is to go to https://flow.microsoft.com/ > browse to your CoE environment > browse to solutions. 

Share a screenshot of what you have there, and please note that you must be logged in to GitHub to share the picture you cannot respond in email with a picture. 
![image](https://user-images.githubusercontent.com/89584709/181367195-eb7c64ca-06f1-40b7-934a-ead373684e9a.png)

**Comment by keharrin** [comment]
Thanks Jenefer here is the screensho
<img width="726" alt="solutionscoe" src="https://user-images.githubusercontent.com/77410660/181772768-41f6bb66-f46f-40a1-8d62-2f2cfc66cd3d.PNG">
t

**Comment by Jenefer-Monroe** [comment]
CAn you please share again but expand the "Name" (second) column so that I can see the full string for the logical name?

**Comment by keharrin** [comment]
<img width="675" alt="solutionscoe" src="https://user-images.githubusercontent.com/77410660/181780489-31322743-4be9-4c55-a6cc-d6b92d0ae14d.PNG">

**Comment by Jenefer-Monroe** [comment]
This environment is a production environment, you have Core 3.40 installed. You should not also install Core for Teams in this environment. You install one or the other, and Core (not Core for Teams) is the more powerful and better supported version. 

Please see https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#decide-what-environment-type-to-use-production-or-dataverse-for-teams

**Comment by keharrin** [comment]
Thanks Jenefer! That is what I was thinking but wanted to confirm.
