### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 (Connection Identities) Limit

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#3293]
### Describe the issue

For some reason we are hitting the aggregated page results size limit when our default environment gets scanned. 

### Expected Behavior

Flow should function normally.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connections Identities) 

### Steps To Reproduce

We just start the Admin | Sync Template v3 (Connection Identities) flow and it fails every morning. Other instances it runs fine. We suspect is fails when it hits our Default environment. 

![image](https://user-images.githubusercontent.com/95443860/181364536-7763f235-a63b-4b3c-82c7-48771ab288f4.png)

![image](https://user-images.githubusercontent.com/95443860/181364294-e1836e65-b21f-4737-9b3a-afe9c9c5d2de.png)

**Comment by Jenefer-Monroe** [comment]
Oh no! It appears you have hit a product limitation due to the size of your default environment. 

Since I dont repro, can you try a few things for me to see if we can resolve it? 

Create a new flow with only this call as an action
![image](https://user-images.githubusercontent.com/89584709/181371938-b064de85-1074-4c92-9485-add50b462083.png)

add your default environment in the envt name, and enter this for version instead of the one in the kit **_2021-02-01_**
Then also set the pagination to 100000
![image](https://user-images.githubusercontent.com/89584709/181371671-11a20a16-d9dc-4694-846f-a8c92aa5b6ed.png)
![image](https://user-images.githubusercontent.com/89584709/181371760-e12a6344-66bc-4a62-a52b-e16fbc3ad449.png)

Save and run this flow, let me know if it still fails with the new version. If it does I have a few other ideas we can try.

**Comment by nasilvae** [comment]
Hi is running for now will report back once it finishes.

**Comment by Jenefer-Monroe** [comment]
If that doesnt work I'm wondering if we can up the page size from 250 to a higher number and see if it works.

**Comment by nasilvae** [comment]
Hi it doesn't work :(. We tried 250 and 500 page size limits. It still yields the same results. 

250 Limit:
![image](https://user-images.githubusercontent.com/95443860/182230492-5d91c9f5-5e04-48d6-b1ec-898b5fcaa43f.png)

500 Limit: 
![image](https://user-images.githubusercontent.com/95443860/182230601-29716e68-b4d8-40fc-936c-a059affbf824.png)

**Comment by Jenefer-Monroe** [comment]
Got it. Well this is a product limitation then. Can you please create a support ticket so that this gets to the product team via that channel?

**Comment by nasilvae** [comment]
gotcha, what would it be the best way to open the support ticket? Do we open it as a regular support ticket via services hub?

**Comment by Jenefer-Monroe** [comment]
yes however you contact support normally. and use the flow we created together outside of the context of the kit's flows, so they dont just point you back to me :)
And mention that it blocks the kit but is a product issue in that the connector cannot return all the content from your default envt.

**Comment by nasilvae** [comment]
sounds like a plan. will do.

**Comment by Jenefer-Monroe** [comment]
I was playing around and think you are likely blocked due to old broken connections. There were a ton even in our small test tenant. I found a way to delete these via PowerShell

(Get-AdminPowerAppConnection -EnvironmentName "Default-**_yourguidhere_**") | Where { $_.statuses -like "*Error*"} | Remove-AdminPowerAppConnection

Hopefully that would unblock you. We are working on a flow to keep these broken connections clean but you would obviously need to be clean enough for flow to work :)

Let me know if it works!

**Comment by stevealldridge** [comment]
We have exactly the same issue. I ran the same command you provided but without the "Remove" action and instead piped the results to a CSV file. It identified 67K connection errors which seems excessive and maybe why the Flow is failing (50K of which were "shared_logicflows").
A colleague and I looked at a few which were owned by ourselves and the Flows themselves showed no errors and no connection errors, most of ours being the listed as "shared_logicflows" connection errors.
Is there a reason we're seeing these connections with errors in the output but don't see them in the Flows themselves? Could it be that some of these errors relate to the fact sometimes the connection needs to be "fixed" by the owner before it will work again ok, or that these are historical issues which are no longer a problem?
What are the implications of removing all these connections with errors, could it inadvertently break Flows which are currently working ok, or remove connections which creates other issues?
With such a huge number of erroring connections we are obviously concerned about removing anything without fully understanding the implications of doing so.

**Comment by Jenefer-Monroe** [comment]
I'm afraid I cannot comment fully here on the implications of removing all the objects. But logically here are my thoughts:
- if the connection is broken today then the object depending upon it is broken today for that user
- if you delete the connection it may result in you needing to recreate the connection in places like Run Only Permissions whereas if the user just repaired, that step would not be needed. However if its been broken a long time thats probably irrelevant.
- as far as I know you cannot remove shared_logicflows connections using this techique, the flow needs removed

I hope that helps

**Comment by orauch-a** [comment]
Hi,
We have exactly the same issue on several environments.
Did you find a solution  ?
Do you have any feedback from the product team ?

**Comment by Jenefer-Monroe** [comment]
Hello. The product team is aware of this limitation. It is a generalized limitation of the platform so I do not expect the behavior to change. 
The only solution is to reduce the number of connections in the envt. From my experience with other tenants well over half of your connections are probably bad and old and broken. So deleting them should unblock you. 
The powershell command listed above is a way for you to start doing that. It will delete all broken connections but you can explore and future filter if you'd like:
Repasted here for your convenience
`(Get-AdminPowerAppConnection -EnvironmentName "Default-yourguidhere") | Where { $_.statuses -like "*Error*"} | Remove-AdminPowerAppConnection`
I hope that helps.

**Comment by bwieland86** [comment]
Adding another instance of failure of this, with our Default environment and several others:

![Admin Sync Template v3 Connection Identities](https://user-images.githubusercontent.com/13457692/207363231-305305e3-ae1d-46bf-a2ad-de99d9567266.PNG)

Is there a workaround or a planned fix for this?

**Comment by bhavikj65** [comment]
List flows as Admin had exactly similar issue and since that is now fixed, can the team now focus on fixing the issue with Get Connections as Admin as well ?

**Comment by Jenefer-Monroe** [comment]
This is a product limitation, not something we can fix. Please give this feedback to the product team via your support channels and/or the power community https://powerusers.microsoft.com/

**Comment by manuelap-msft** [comment]
Closing out as this is a product limitation, and there's no further action required for the CoE kit team.
