### ISSUE TITLE
[CoE Starter Kit - BUG] Makers Unable to Use the Developer Compliance Centre (Teams version)

### ISSUE THREAD

**Issue by HMJ-Somerset** [microsoft/coe-starter-kit#3297]
### Describe the issue

I have installed the July version of the CoE toolkit in a D4T environment and shared the Developer Compliance Centre (Teams) and the Cleanup Old Objects app with my Power Platform Makers group.

They can add the apps to their Teams desktop but when it opens they just get a blank screen
![image](https://user-images.githubusercontent.com/106976858/181453247-bc669591-c269-4c38-8ea9-0e8511d430ff.png)

The same is true for the Cleanup Old Objects app.

I have given Group, access to all the tables so there should not be a problem.

Anyone with a Power Apps per User licence can access the app and see the data, but not those who just have the Teams licence.  There seems to be something in the installation that requires a licence in order to use it.

### Expected Behavior

Open the Compliance Centre, view apps and flows and submit compliance details.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.21

### What app or flow are you having the issue with?

Developer Compliance Centre (Teams version)

### Steps To Reproduce

1. Add Dev Comp Centre to Teams dektop
2. open Compliance centre in Teams

### Anything else?

_No response
![DevComplianceTeams](https://user-images.githubusercontent.com/106976858/181490263-f4168ad0-0c96-4b46-8fab-68a977501685.png)
I have checked the app details for the Teams version and it clearly shows that it requires a premium licence.  This is NOT what the Teams version should use.
I have checked further and ALL apps have this premium designation, so none will work in Teams
_

**Comment by Jenefer-Monroe** [comment]
All apps will require a premium license to view outside of the context of teams. 
But the D4T environment allows users to view premium apps, when they are premium due to Dataverse usage as is the case here, within the context of the teams environment without the premium license.

**Comment by Jenefer-Monroe** [comment]
Developer compliance center, by default, only shows apps that are flagged for compliance by the admin. If the user has none they will see no apps listed. 
They can change the filter from Requested to All
![image](https://user-images.githubusercontent.com/89584709/181591836-5159c4b1-0784-4875-ba1c-33e68d36dc7d.png)

**Comment by Jenefer-Monroe** [comment]
You also need to give correct permissions which means giving them permission to all the tables. 
Please see our Tips and How To document: [Share an app from a Dataverse for Teams environment](https://docs.microsoft.com/power-platform/guidance/coe/faq#share-an-app-from-a-dataverse-for-teams-environment)

**Comment by HMJ-Somerset** [comment]
The app is being used in Teams desktop
I have gone through all the tables and given the Makers group collaboration access, 
but whatever filters are set, the only makers who see any apps or flows are those with a per user licence.

**Comment by Jenefer-Monroe** [comment]
This will list flows to which the user has co-owner access. 

Please find an example of 
- a user without premium license
- that user has at least edit (co-owner) permissions to an app
- that user browses in teams
- that user changes the filter shown from requested to all

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by HMJ-Somerset** [comment]
I managed to resolve this issue by installing the Aug 2022 version of CoE Core solution for Teams.  I changed nothing else, but users were then able to view their apps in the Developer Compliance Centre (Teams) and Cleanup Old objects app within Teams
