### ISSUE TITLE
[CoE Starter Kit - BUG] HELPER MAKER CHECK cannot be activated

### ISSUE THREAD

**Issue by ddomboy** [microsoft/coe-starter-kit#3300]
### Describe the issue

Hello together,

I'm trying to activate the Flow HELPER MAKER CHECK and get the following error: 

 Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_GraphURLEnvironmentVariable'."}}"

Can someone help me out on this please?

Thanks in advance

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

helper maker check

**Comment by Jenefer-Monroe** [comment]
This error indicates that the flow relies on an environment variable that you have not set. 

Please see [Gather environment variables](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values)

![image](https://user-images.githubusercontent.com/89584709/181518411-63daf573-57f8-4d82-bb8c-4ac1ef3b1811.png)

If you need help understanding how to set an env variable please see our FAQ and Tips document. [Update environment variables](https://docs.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables)

**Comment by ddomboy** [comment]
Hey, thank you very much, I could fix it now!

But now I have a similar problem when trying to turn on Admin Symc Template v3

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Apps_as_Admin' of type 'OpenApiConnection' at line '1' and column '52892' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}"

Is there also a fast solution?

Thanks in advance!

**Comment by manuelap-msft** [comment]
If you see an Invalid Pagination Policy error when trying to turn on the flows, it indicates that you are using an insufficient or trial license. All our flows require a medium or high performance profile to run. License requirements are listed in our [prerequisites](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with).

Learn more: [Power Automate performance profiles](https://docs.microsoft.com/en-us/power-automate/limits-and-config#performance-profiles) and [Concurrency looping and pagination limits](https://docs.microsoft.com/en-us/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

See: 
Pre-requisites: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with
Error description (in the first blue paragraph): https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows
