### ISSUE TITLE
Deployment Pipeline fails at: "Starting: Archive Configuration Migration Data"

### ISSUE THREAD

**Issue by jlzd** [microsoft/coe-starter-kit#3303]
### Describe the issue

Deploy pipeline fails at Archive Configuration Migration Data

Starting: Archive Configuration Migration Data
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\5a25915e-0617-434c-97fc-dc3442b63355.ps1'"
Invoke-ArchiveConfigurationMigrationData : A positional parameter cannot be found that accepts argument 'ALM'.
At D:\a\_temp\5a25915e-0617-434c-97fc-dc3442b63355.ps1:4 char:1
+ Invoke-ArchiveConfigurationMigrationData D:\a\1\s D:\a\1\a OS CoE ALM …
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Invoke-ArchiveConfigurationMigrationData], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : PositionalParameterNotFound,Invoke-ArchiveConfigurationMigrationData
##[error]PowerShell exited with code '1'.
Finishing: Archive Configuration Migration Data

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220726.1(

### Steps To Reproduce

Run Deploy Solution form Canvas App

**Comment by mikefactorial** [comment]
@jlzd thanks for reporting this. Looks to be a bug in the latest pipelines. I've submittted a PR to fix this. In the meantime can you try updating you local build-solution.yml pipeline https://github.com/microsoft/coe-alm-accelerator-templates/pull/156/files

**Comment by mikefactorial** [comment]
I think the issue here is that we weren't expecting spaces in one of the parameters passed to the script. @RajeevPentyala for visibility

**Comment by jlzd** [comment]
Thank you for providing such a quick turn around on the fix  much appreciated!!!
