### ISSUE TITLE
CoE Starter Kit Teams Version 3.21 Installed in Dev Tenant and no flows are triggering even though they are enabled

### ISSUE THREAD

**Issue by michaelgottwals** [microsoft/coe-starter-kit#3305]
### Describe the issue

I have installed the CoE Starter Kit Teams Version 3.21 in our Dev Tenant using the same installation process as in our Prod tenant and no flows are running even though they are enabled. When I open the core components solution and check random flows run history, I do not see any run history (e.g. Admin | Sync Template v3 (Flows), Admin | Sync Template v3 (Apps). I am not sure why the flows are not being triggered because the Prod tenant installation the flows were triggering and running very soon after installing the solution. As a test, I created a new flow in the default environment of my dev tenant to see if that would trigger the Admin | Sync Template v3 (Flows) flow but it did not.  

Can you provide some guidance here where I may look to see why starter kit flows that have been enabled are not running?

Thanks in advance.

### Expected Behavior

I would expect the Teams CoE Starter Kit flows that have been enabled to be running

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponentsTeams_3_21_managed

### What app or flow are you having the issue with?

All enabled flows in the solution

### Steps To Reproduce

See Issue Description

**Comment by Jenefer-Monroe** [comment]
Did you turn on all the flows listed in [Set up Inventory](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components)?

Flows like **_Admin | Sync Template v3 (Flows)_** are triggered when this flow (**_Admin | Sync Template v3_**) runs and creates or updates environments in the inventory. Is it on and running?

**Comment by michaelgottwals** [comment]
I had followed the instructions in the link you sent but at second look based on your last post I missed enabling that one flow, so that was it. Thanks for the direction here! you can close this one out.

**Comment by Jenefer-Monroe** [comment]
good news! Thanks for letting me know.
