### ISSUE TITLE
[ALM Accelerator - Feature]: Review flow activation using impersonation logic

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#3306]
### Describe the solution you'd like

Interactive users can now share connection references with an SPN.  When they do this, our impersonation logic to turn flows on after solution import is no longer needed.  That's because a solution imported by an SPN will import and successfully turn on the flows since the SPN will have permissions to the connection.  We should review our logic and ensure we aren't attempting to turn on flows unnecessarily.  However, we should keep our logic in place as a fall back.

**Comment by mikefactorial** [comment]
The impersonation logic in the ALM Accelerator pipelines will need to be removed now that impersonation is no longer supported in the platform.
