### ISSUE TITLE
[Documentation] Add App User Troubleshooting to SETUP doc

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#331]
**Is your feature request related to a problem? Please describe.**
Add troubleshooting to setup doc based on this discussion.
https://github.com/microsoft/coe-starter-kit/discussions/330

**Comment by jenschristianschroder** [comment]
Should update the docs on adding App Users to reflect the changes in UI in PPAC.

The issue discussed in #330 is relevant only when adding App User via classic UI.
