### ISSUE TITLE
[CoE Starter Kit - BUG] UserPhotoMetadata error in Developer Compliance app 

### ISSUE THREAD

**Issue by KishoreJagan83** [microsoft/coe-starter-kit#3312]
### Describe the issue

Facing the below issue in Developer Compliance Center app for few user's.
Need to know the rootcause.
![image](https://user-images.githubusercontent.com/43986892/181742197-f38bc281-121f-4268-9116-82c2fcf6e2e2.png)

### Expected Behavior

DCC app should not throw this error when ever we click any of the APP.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.13

### What app or flow are you having the issue with?

Developer Compliance Center

### Steps To Reproduce

Open the DCC app
Check the landing page or dashboard
Click any of the app from the dashboard and check the next screen loading

**Comment by Jenefer-Monroe** [comment]
I don't repro so you will need to investigate a little more for me. 
1. Are you getting that error when you load the app or the details page? Your picture is of the loading page but your notes say to go to the details page of the app
2. Take the ID of the users that are part of the app in question and look them up in Azure protal, do they resolve?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
