### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by SusanaQueiroz** [microsoft/coe-starter-kit#3315]
### Describe the issue

Encontramos uma divergência entre aplicaçoes que estão no Dataverse, mas nao existem mais no portal do PowerApps. We've found a inconsistence in the applications in Dataverse and PowerApps portal. Some applications does not exist in PowerApps but they still exist in Dataverse

### Expected Behavior

Dataverse should be equalized as the PowerApps portal and Power Automate portal 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

published on August 2021

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Sync Flow Errors)

### Steps To Reproduce

29f36bd0-40a9-433d-86c5-5d1ea088ab55  - environment
/flows/25241ea0-a941-41dd-8514-4ce68e627a4d - flow coe
ID app Dataverse -  c0ea50fc-627d-4e22-a9af-0026e29a5104
[Evidencias divergência dataverse x portais power apps e power automate.pdf](https://github.com/microsoft/coe-starter-kit/files/9221513/Evidencias.divergencia.dataverse.x.portais.power.apps.e.power.automate.pdf)

**Comment by Jenefer-Monroe** [comment]
Hello. I'm sorry but I dont quite follow, and I will need more information in order to assist. 

1. Are you really on the version of the kit from August 2021? That would be Core 2.77. 
2. Please share screenshots of what you are seeing in both the locations where you see differences. Note that you need to be logged in to GitHub to share pictures you cannot just respond in email.

**Comment by eudeferraz** [comment]
Hello.
1. Yes, it's Core 2.77
2. Here it's the application (ID c0ea50fc-627d-4e22-a9af-0026e29a5104) in Dataverse.
![image](https://user-images.githubusercontent.com/47229449/182220238-2fb062c3-63e9-47fa-9776-78e71c4cc20d.png)
But if we tried to search it in the environment it looks like it doesn't exists.
![image](https://user-images.githubusercontent.com/47229449/182220438-dc2ed163-efd6-4a59-b5e7-f1d3eb1ab50e.png)

**Comment by Jenefer-Monroe** [comment]
You will need to find a repro of this in your tenant to see what is going wrong. 
1. Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you are looking for missing canvas apps chose **_Admin | Sync Template v3 (Apps)_**
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

5. From here you can explore if there is a failure, or if a bad return set, etc. And let us know if you have questions

**Comment by SusanaQueiroz** [comment]
Adding Camila.
Guys, could you add @Camila ***@***.***> email on this issue?

Thanks
Susana

De: Jenefer Monroe ***@***.***>
Enviada em: terça-feira, 2 de agosto de 2022 12:00
Para: microsoft/coe-starter-kit ***@***.***>
Cc: Susana Queiroz ***@***.***>; Author ***@***.***>
Assunto: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #3315)

[EXTERNAL E-MAIL]

You will need to find a repro of this in your tenant to see what is going wrong.

  1.  Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)
  2.  Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change.
[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png&data=05%7C01%7Csusana.queiroz%40vale.com%7Ca3c56d9637a04e8690b608da7497b614%7C7893571b6c2c4cefb4da7d4b266a0626%7C0%7C0%7C637950492237990742%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HZRPjrHfnPhBFWrJnTmuvIfSR%2BHvbM%2Ff97SShFdovK0%3D&reserved=0>
  3.  This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you are looking for missing canvas apps chose Admin | Sync Template v3 (Apps)
[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png&data=05%7C01%7Csusana.queiroz%40vale.com%7Ca3c56d9637a04e8690b608da7497b614%7C7893571b6c2c4cefb4da7d4b266a0626%7C0%7C0%7C637950492237990742%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fUfv8%2By0mb%2F1J6XjIkgg3SPNKpPuhAHM%2BBaFpV%2F3QR8%3D&reserved=0>
  4.  Click on the timestamp of run in progress (or the one that just finished) to see the run itself.
[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png&data=05%7C01%7Csusana.queiroz%40vale.com%7Ca3c56d9637a04e8690b608da7497b614%7C7893571b6c2c4cefb4da7d4b266a0626%7C0%7C0%7C637950492237990742%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SjbBcmPepDNA0l0Y2bibWaogGWlAndgGDRxvNa7QytQ%3D&reserved=0>
  5.  From here you can explore if there is a failure, or if a bad return set, etc. And let us know if you have questions

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F3315%23issuecomment-1202761445&data=05%7C01%7Csusana.queiroz%40vale.com%7Ca3c56d9637a04e8690b608da7497b614%7C7893571b6c2c4cefb4da7d4b266a0626%7C0%7C0%7C637950492237990742%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R%2FQLazuohdi72q8Wmj1NVqnSpsHZvpRDd3wwqkxQr8I%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANPPD2KMJLYSNVHUYKHNCETVXEZYBANCNFSM55BHKONQ&data=05%7C01%7Csusana.queiroz%40vale.com%7Ca3c56d9637a04e8690b608da7497b614%7C7893571b6c2c4cefb4da7d4b266a0626%7C0%7C0%7C637950492237990742%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ikDq8pL9%2FXQKubNWuzi8jf1cAsq0IAZ3aRGr48Y5KPU%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

AVISO LEGAL "As informações existentes nesta mensagem e nos arquivos anexados são para uso restrito. A utilização, divulgação, cópia ou distribuição dessa mensagem por qualquer pessoa diferente do destinatário é proibida. Se essa mensagem foi recebida por engano, favor excluí-la e informar ao remetente pelo endereço eletrônico acima."


DISCLAIMER "This email and its attachments may contain privileged and/or confidential information. Use, disclosure, copying or distribution of this message by anyone other than the intended recipient is strictly prohibited. If you have received this email in error, please notify the sender by reply email and destroy all copies of this message."

**Comment by eudeferraz** [comment]
> You will need to find a repro of this in your tenant to see what is going wrong.
> 
> 1. Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)
> 2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
>    Note you will want to change back so be aware of the change.
>    ![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)
> 3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
>    Ex: if you are looking for missing canvas apps chose **_Admin | Sync Template v3 (Apps)_**
>    ![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)
> 4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself.
>    ![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)
> 5. From here you can explore if there is a failure, or if a bad return set, etc. And let us know if you have questions

I have changed the record as instructed.
![image](https://user-images.githubusercontent.com/47229449/182710288-909adf25-bc17-4635-9712-19b105df9b81.png)

But the flow didn't run, the last execution was in the past week.
![image](https://user-images.githubusercontent.com/47229449/182710403-52493148-ce0d-4ca2-a608-4ac48e9c8e3c.png)

And appears that there's a issue with the Azure connection, but I not able to setup this.
![image](https://user-images.githubusercontent.com/47229449/182710578-bb2100b3-4869-4bba-b16d-1ad7585b6dd5.png)

Could you help me?

**Comment by Jenefer-Monroe** [comment]
When you setup you should have created a connection to graph as shown in step 4 here. Did you do that? 

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections

![image](https://user-images.githubusercontent.com/89584709/182712996-71ea667a-e63e-49ea-8a32-92a4a27e4571.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by SusanaQueiroz** [comment]
Hello, guys!
Thanks for the support. I'm adding Camila in the looping. She'll be able to detail the issue and provide some explanation

@Camila ***@***.***> this is the thread to interact with Github team about the issue we are facing in the Dataverse x Powerapps webpage

Thanks
Susana

De: Jenefer Monroe ***@***.***>
Enviada em: sexta-feira, 29 de julho de 2022 13:39
Para: microsoft/coe-starter-kit ***@***.***>
Cc: Susana Queiroz ***@***.***>; Author ***@***.***>
Assunto: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #3315)

[EXTERNAL E-MAIL]

Hello. I'm sorry but I dont quite follow, and I will need more information in order to assist.

  1.  Are you really on the version of the kit from August 2021? That would be Core 2.77.
  2.  Please share screenshots of what you are seeing in both the locations where you see differences. Note that you need to be logged in to GitHub to share pictures you cannot just respond in email.

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F3315%23issuecomment-1199706482&data=05%7C01%7Csusana.queiroz%40vale.com%7C33ad2d24e01b42c99eae08da7180e8ab%7C7893571b6c2c4cefb4da7d4b266a0626%7C0%7C0%7C637947095739895249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Gmbq%2B8zXdd5Z6m730C220AeOyGJ1EEBzddGWs1ll9gs%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANPPD2I6UHM5HNXIBDNMQ7LVWQCMDANCNFSM55BHKONQ&data=05%7C01%7Csusana.queiroz%40vale.com%7C33ad2d24e01b42c99eae08da7180e8ab%7C7893571b6c2c4cefb4da7d4b266a0626%7C0%7C0%7C637947095739895249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RvxmB%2FcincRAGQ15SLCHNK%2BJ7kt6BX9lKe4a5Db1zAs%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

AVISO LEGAL "As informa??es existentes nesta mensagem e nos arquivos anexados s?o para uso restrito. A utiliza??o, divulga??o, c?pia ou distribui??o dessa mensagem por qualquer pessoa diferente do destinat?rio ? proibida. Se essa mensagem foi recebida por engano, favor exclu?-la e informar ao remetente pelo endere?o eletr?nico acima."


DISCLAIMER "This email and its attachments may contain privileged and/or confidential information. Use, disclosure, copying or distribution of this message by anyone other than the intended recipient is strictly prohibited. If you have received this email in error, please notify the sender by reply email and destroy all copies of this message."
