### ISSUE TITLE
[CoE Starter Kit - BUG] Column admin_recordguidasstring in Table Maker contains blank values

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#3320]
### Describe the issue

On loading August 2022 version of Dashboard .pbix I get the error Column admin_recordguidasstring in Table Maker contains blank values and the import stops

### Expected Behavior

The iporting of data into PowerBi should work

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

All

### Steps To Reproduce

Double click on Production_CoEDashboard_August2022.pbit see error

### Anything else?

![image](https://user-images.githubusercontent.com/8484048/182114319-63906d86-734e-48fb-aaed-5543b149dd6e.png)

**Comment by manuelap-msft** [comment]
We have added new fields to several tables with the August release. Please run the **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_** flow to clean up these errors as it will populate the field.

**Comment by NPrice99** [comment]
Thanks Manuela - did I miss running CLEANUP - Admin | Sync Template v3 (Delete Bad Data) in the instructions for this month ? I ran - Admin | Sync Template v3 as usual before I ran the report.

**Comment by manuelap-msft** [comment]
No, we missed it! I just added it to the release notes now :)
