### ISSUE TITLE
Office 365 Management API connection error for Child Admin Sync Logs

### ISSUE THREAD

**Issue by keharrin** [microsoft/coe-starter-kit#3323]
### Describe the issue

since the upgrade to July release the Office 365 Management API Connection is no longer working.

When I attempt to connect using my id that worked with previously the following error is received
<html>
<body>
<span style="color: rgb(0, 0, 0); font-family: Verdana; font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="font-family: Verdana; font-weight: normal; font-size: 18pt; color: red;">Server Error in '/' Application.<hr width="100%" size="1" color="silver"></h1><h2 style="font-family: Verdana; font-weight: normal; font-size: 14pt; color: maroon;"><i>The length of the query string for this request exceeds the configured maxQueryStringLength value.</i></h2></span><span style="color: rgb(0, 0, 0); font-family: Verdana; font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif " style="color: rgb(0, 0, 0); font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Description:<span> </span></b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.<br><br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Exception Details:<span> </span></b>System.Web.HttpException: The length of the query string for this request exceeds the configured maxQueryStringLength value.<br><br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Source Error:</b><br><br>

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--

<br><hr width="100%" size="1" color="silver"><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Version Information:</b> Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3930.0</font>
</body>
</html>

### Expected Behavior

Connection should resolve as this worked with previously

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

1.  Edit [Child] Admin | Sync Logs 
2.  Office 365 Management API Flow connection is errored out
3.  Click Fix Connection
4.  Choose SID or my power platform admin account
5.  Receive error message

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
