### ISSUE TITLE
[CoE Starter Kit - BUG] Admin - Environment Request refresh fails

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#3327]
### Describe the issue

Refresh button in Admin - Environment Request seams to raise an error:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/15800069/182174639-8ac5a8b2-da2a-4ff6-9e3f-cea06b20b974.png">
The error message appears immediately after App start.

**Details from - Power App Monitor:**
![image](https://user-images.githubusercontent.com/15800069/182176077-73daa0f4-119b-4f78-bb29-e842ec9ebfe2.png)
(this might be the origin)

*later in the log, these errors appear:*
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/15800069/182175098-805ecba8-7836-441d-a7d3-29b4f2e1f710.png">
<img width="476" alt="image" src="https://user-images.githubusercontent.com/15800069/182175029-c0bd4649-d97b-414b-b3c4-a113803984e3.png">
<img width="450" alt="image" src="https://user-images.githubusercontent.com/15800069/182175223-9de13f3f-24dd-4b4c-be3a-f9d286fc9bf4.png">

### Expected Behavior

no network error ;)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2022

### What app or flow are you having the issue with?

Admin - Environment Request

### Steps To Reproduce

1. Open the App

**Comment by denisem-msft** [comment]
I believe this was fixed already. Can you please confirm if you're still seeing this @megel ?

**Comment by manuelap-msft** [comment]
Closing out as no further action required from CoE kit team / no response received on the issue. Please let us know if you continue to face issues.
