### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE IN IMPORTING 2 SOLUTIONS IN CoE TOOLKIT

### ISSUE THREAD

**Issue by amitav-anand** [microsoft/coe-starter-kit#3329]
### Describe the issue

Unable to install AuditComponents_2.19_managed & CoreComponentsTeams_3_22_managed solutions. Below are the errors I am getting while importing the solution.

CenterofExcellenceCoreComponentsTeams_3_22_managed : Attached in the error in importing this solution (Center.of.Excellence.-.Core.Components.for.Teams_import.zip).

CenterofExcellenceAuditComponents_2.19_managed: CoE-1 & CoE-2

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.22 & 2.19

### What app or flow are you having the issue with?

FlowApprovalsCore

### Steps To Reproduce

[Center of Excellence - Core Components for Teams_import.zip](https://github.com/microsoft/coe-starter-kit/files/9236438/Center.of.Excellence.-.Core.Components.for.Teams_import.zip)

![CoE-1](https://user-images.githubusercontent.com/6000045/182219702-c10d8856-3735-46ae-9449-ba962e12f5d9.JPG)
![CoE-2](https://user-images.githubusercontent.com/6000045/182219715-70160abc-d590-4fc2-82f2-16adadd50411.JPG)

**Comment by manuelap-msft** [comment]
For the error message in the screenshot, you've missed this step in our setup instructions:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov#initialize-flow-approval-tables-in-your-environment

**Comment by Jenefer-Monroe** [comment]
We do not have a video demo for this. Each solution area has a section explaining how to gather the information though.
Here, for example, is what is needed to be gathered ahead of installing Core for Inventory. [Gather environment variable values - inventory](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
