### ISSUE TITLE
[BUG]: Developer Compliance Center - Clich on Flow Settings, but can't reach Flow setting page.

### ISSUE THREAD

**Issue by hammhamm** [microsoft/coe-starter-kit#333]
**Describe the bug**
In Developer Compliance Center, Click Flows tab, and get a Flow Details. and Click 'Flow Settings' ,but can't reach Flow Setting page.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution : Governance Components
 - Version : 1.60
 - App or Flow: Developer Compliance Center

**To Reproduce**
1.Open Developer Compliance Center
2. Click to 'flows' tab
3. Click a flow
4. Click on 'Flow Settings'
5. Can't reach Flow Setting Page and Show 404 Error

**Expected behavior**
Click on 'Flow Setting' and show Flow Setting Page

**Screenshots**
Click on 'Flow Setting'
![image](https://user-images.githubusercontent.com/71855867/118087777-0feba300-b401-11eb-9583-ddeb67744e87.png)

Can't reach Flow Setting Page and Show 404 Error
![image](https://user-images.githubusercontent.com/71855867/118087624-c733ea00-b400-11eb-8197-1a991c4c1730.png)

Flow Setting Page
![image](https://user-images.githubusercontent.com/71855867/118087874-2c87db00-b401-11eb-88a5-94b2fa938397.png)

**Additional context**
In URL,'manage' is missing?

**Comment by JeneferM-MSFT** [comment]
local fixed for June release
