### ISSUE TITLE
[CoE Starter Kit - BUG] The 'admin_user' column does not exist in the rowset. Table: Power Platform User.

### ISSUE THREAD

**Issue by JawnLegend** [microsoft/coe-starter-kit#3332]
### Describe the issue

Unable to fetch data in the Center of Excellence dashboard. Met with error code:

The 'admin_user' column does not exist in the rowset. Table: Power Platform User.

### Expected Behavior

Expected a daily refresh of data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Center of Excellence dashboard

### Steps To Reproduce

1. Go to dashboard
2. Data sets
3. Center of excellence data set
4. Refresh data
5. Error

### Anything else?

![image](https://user-images.githubusercontent.com/105429761/182314208-20213279-4690-4b9d-804e-f1cc0e46bbf9.png)

**Comment by Jenefer-Monroe** [comment]
You need to match the PBI each month with the version of Core. 

We are about to reship the August PBIT files so here they are for you to use: [August PBITs with alt key removed.zip](https://github.com/microsoft/coe-starter-kit/files/9242700/August.PBITs.with.alt.key.removed.zip)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
