### ISSUE TITLE
[CoE Starter Kit - BUG] Error updating the August Power BI DAshboard

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#3339]
Hi, I am updating the COE starter kit for this month and ran into issues updating the Power BI Production_CoEDashboard_August2022.pbit file. Whenever it is updating it finally errors out and below is what I copied from the error.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/95765970/182421671-e24f6ca4-7322-47b5-804a-caf9529e2d9f.png">

I was looking at the errors and noticed the Power Platform User error and went to look the table up in my system and noticed that the reference column is blank in our Dataverse Table. Is this expected behavior? I saw that this was a new item that was added for this month. Not sure how to fix. Any guidance you can provide is greatly appreciated.

https://github.com/microsoft/coe-starter-kit/issues/3155

**Comment by AUTigers16** [comment]
I saw that this is an already reported issue with https://github.com/microsoft/coe-starter-kit/issues/3318 you can go ahead and close this. I will follow that one.

**Comment by manuelap-msft** [comment]
We have re-released the PBIT files to address #3322 and #3318. They're available when you re-download https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-August2022/CoEStarterKit.zip
