### ISSUE TITLE
[Product BUG]: Innovation Backlog App (for Teams) - Initial Publish Error

### ISSUE THREAD

**Issue by anton3sco** [microsoft/coe-starter-kit#334]
**Describe the bug**
Imported the Innovation Backlog solution into Microsoft Dataverse for Teams. Everything went well except for when publishing the app (not the admin app) it came back with the error: The dependent component Entity (Id=duplicaterecord) does not exist

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. CenterofExcellenceInnovationBacklog_1_30_managed]
 - Version [e.g. 1.3]
 - App or Flow [Innovation Backlog App]

**To Reproduce**
1. Import the solution
2. Run flows and configure as expected
3. Upload pictures to admin app
4. Open Innovation Backlog App and received the error

**Expected behavior**
I expected that the app would publish and post to the MS Teams channel selected. Instead, it gave an error screen shown in the screenshot. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26906102/118058629-39022a00-b354-11eb-80d5-a5588cb391e2.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
publish issue we have a local fix for for June
