### ISSUE TITLE
[CoE Starter Kit - BUG] CoE toolkit adding Owner(account running COE flows) to Premium flows automatically

### ISSUE THREAD

**Issue by salviroshan89** [microsoft/coe-starter-kit#3341]
### Describe the issue

HELPER - CloudFlowOperations flow is running and adding COE toolkit account as owners to users flows which are premium.

### Expected Behavior

COE toolkit should never add account it running as Owner to any end users flows automatically when the actual flow owners are active

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

HELPER - CloudFlowOperations

### Steps To Reproduce

Let an individual create a flow with premium actions in it, lets say Http action.
Save the flow.

CoE toolkit will add additional owner(account which running COE flows) to the flow created by end user .

### Anything else?

Could you please help and tell us what all flows using child flow HELPER - CloudFlowOperations. Its adding the owner to flows which are premium.  We need to stop this.

**Comment by Jenefer-Monroe** [comment]
There is one flow, **_Admin | Sync Template v3 (Flow Action Details)_**, which will, if the flow has a small subset of actions, add the identity running the flow as an owner. This is so that it can get the flow (not as admin) to get more details. It removes the user after the action is complete. 

![image](https://user-images.githubusercontent.com/89584709/182439290-705b9bc4-a35c-4b2d-8816-9b218b0d5172.png)

We cannot disable the alert unfortunately letting the running identity know they have been added. 
This is an optional flow, so if you find that too noisy for the benefit of the flow, you can disable it.

**Comment by salviroshan89** [comment]
> 

"It removes the user after the action is complete." - Its not removing the user and hence its kept added as owner in the flows which is causing concerns to the flow owners. 

for now we will disable this flow. But disabling this flow means we wont be able to see the actions used in COE dashboard, is that correct?

Could you please let us know once this bug resolves, then we could re-enable this flow.

**Comment by Jenefer-Monroe** [comment]
As far as I know, there is no bug here. If you have cases where the user is added and not removed, please bring them here and we can see about debugging. I do not repro that myself but would be glad to investigate with you.

**Comment by salviroshan89** [comment]
Please follow below simple steps to repro it.

1) Login to Power Automate with Standard E3 license
2) Create a New flow, and add atleast 1 Http action in it. Save the flow
3) You will find next day, identity running CoE flow getting added in the flow you created yesterday.

Since its impacting the lice flows, i am disabling this flow but you should be able to reproduce this issue using above steps as i successfully did this.

**Comment by Jenefer-Monroe** [comment]
Sorry I do not repro this. While the identity does get added, it gets removed afterwards. 
Perhaps you have unmanaged layers on this or the helper flow. 
![image](https://user-images.githubusercontent.com/89584709/182909187-1a334a61-9d46-4f42-885e-e762cb47659e.png)

**Comment by salviroshan89** [comment]
I can show you, could you tell me how can we connect ? i think a screen share session i could show you. It doent have unmanaged layer. I am on MS teams. So if you are also, we could connect and i can show you.

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are not staffed to meet with our GitHub customers in that manner. 
You will need to find a repro as shown above, in which the flow adds the user but then does not remove them. 
I would suggest seeing if you have unmanaged layers on the helper as a first step, then if you still repro, find the repro and return with a picture like I've shown above with which we can debug.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
