### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log Connection Fail after every CoE Update

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3348]
### Describe the issue

I have meant to raise this on a few occasions but we find that after every CoE update the audit log connector fails, we have to repopulate the security details of the Office 365 Management API Custom Connector and recreate the connection. Is this expected? If so, then the documentation should be updated to reflect this.

![image](https://user-images.githubusercontent.com/17124284/182595595-00b867ff-0534-4c88-b066-ad56d23d7013.png)
 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.1

### What app or flow are you having the issue with?

Audit Log Component

**Comment by Jenefer-Monroe** [comment]
This is a known product limitation. Please see here for our recommendation for fix
https://github.com/microsoft/coe-starter-kit/issues/1424

We do have a documentation bug about how to fix this up https://github.com/microsoft/coe-starter-kit/issues/2777

Thanks for posting

**Comment by medicineshow** [comment]
Thanks for that. Your fix is exactly what we have been doing. just never got around to highlighting it.
