### ISSUE TITLE
COE Starter Toolkit - Premium connectors not displaying for apps, only standard connectors

### ISSUE THREAD

**Issue by gcusworth** [microsoft/coe-starter-kit#335]
The COE starter kit has only detected standard connectors for apps e.g SharePoint, however I know that premium connectors such as Dataverse are being used on several apps and flows. Is this a known issue and are there any specific flows I could check please? The app detail Power BI report only shows standard connectors for apps, not premium connectors. Note that premium connectors for cloud flows are listed correctly. Thanks

**Comment by JeneferM-MSFT** [comment]
closing out as there is no further action for the toolkit here.
