### ISSUE TITLE
[CoE Starter Kit - QUESTION] App Catalog is blank

### ISSUE THREAD

**Issue by shyjujohn** [microsoft/coe-starter-kit#3351]
### What is your question?

Hi,

While setting up the COE tool kit, the App Catalog app shows no data. We have the below set up applied to the PowerApp Entity.
![image](https://user-images.githubusercontent.com/41447786/182642557-10f7acc7-6027-4bde-8c06-02890fa735e3.png)
Do we have to have the Auditing turned on or the user should have Audit Log access for setting this up?
Please help.

Thank You!
Shyju John

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

App Catalog

**Comment by Jenefer-Monroe** [comment]
There is not a relationship between Audit Logs and the App Catalog. 

[App Catalog App](https://docs.microsoft.com/power-platform/guidance/coe/core-components#app-catalog) uses the boolean field you reference which is exposed in the [Power Platform Admin View app](https://docs.microsoft.com/power-platform/guidance/coe/core-components#power-platform-admin-view)


![Image](https://user-images.githubusercontent.com/89584709/182645348-7c485b1a-5e2e-46be-8b59-943bc5e9c091.png)

Hope that helps

**Comment by shyjujohn** [comment]
Hi @Jenefer-Monroe ,

Thank you so much for the guidance. I went ahead and turned Boolean to True. But, we still do not see any apps in the App Catalog App. Can you please let me know if there is any other setting that needs to be configured.

Thank You!
Shyju John

**Comment by shyjujohn** [comment]
Hi @Jenefer-Monroe ,

Its now working as expected. Thank you so much for your help.

Thank you!
Shyju John

**Comment by Jenefer-Monroe** [comment]
Wonderful, thanks for letting me know! I'll closet this out but please feel free to raise new issues if you need further assistance.
