### ISSUE TITLE
[CoE Starter Kit - BUG] PBI App-Embed UX not showing all envts (list too long)

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#3354]
### Describe the issue

CoE Environment not showing in Power BI embedded app report. We have over 1000 environments and the list is not showing all environments which results on showing a couple of environments not including the CoE Environment. 

### Expected Behavior

We should be able to select the CoE environment in the power bi embedded app report so we can use the set permissions embedded app in Power BI. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Power BI July Report

### Steps To Reproduce

Attempted to select environment using Power BI Desktop.

**Comment by Jenefer-Monroe** [comment]
Which screen in the report are you on?

**Comment by nasilvae** [comment]
![image](https://user-images.githubusercontent.com/95443860/182852815-0f6c647f-68bc-4892-9b3f-ba4ce392cd30.png)

**Comment by Jenefer-Monroe** [comment]
I see, so you are failing at the step of embedding the app in the PBI. Unfortunately this is a product issue you have hit and not something in our power to address. 
I suggest getting a repro outside the context of the kit and contacting support. 

Here are some steps to help you create this repro outside the context of the kit
1. Boot PBI
2. Enter some fake data
![image](https://user-images.githubusercontent.com/89584709/182863088-ab18ecca-8ceb-4048-b169-5ad864e443e3.png)
![image](https://user-images.githubusercontent.com/89584709/182863180-94d683c7-9972-4b0d-b46a-64d62228ad1a.png)
3. Insert a Power App control
![image](https://user-images.githubusercontent.com/89584709/182863422-39e0087a-4d90-4ab3-b4b4-219b024ab453.png)
4. Select data to bring up the needed UX
![image](https://user-images.githubusercontent.com/89584709/182863742-06dff4dd-ce51-45bb-98d5-6cc206cdf7c4.png)


Does this list all your environments? 
Likely the PBI team has a workaround to offer you, please let us know what you find!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
