### ISSUE TITLE
[CoE Starter Kit - BUG] Admin - Command Center CoE Flows not work

### ISSUE THREAD

**Issue by maikletal** [microsoft/coe-starter-kit#3356]
### Describe the issue

When access to CoE Flow sections in Admin - Command Center application appears always this error:

"This functionality relies on data that is not yet in your CoE. 
You need to run this flow: Admin | Sync Template v3
Then return here to use this feature."

Admin | Sync Template v3 flow is running correctly

![image](https://user-images.githubusercontent.com/44426740/182788009-1d49b01c-ec34-4549-ba1f-cc098e117d01.png)
![image](https://user-images.githubusercontent.com/44426740/182788075-05804ad9-acae-4a94-a314-bc05934612e8.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

1. Run the app Admin - Command Center
2. Access to CoE Flows section

**Comment by Jenefer-Monroe** [comment]
The **_Admin | Sync Template V3_** flow has a section that looks like this that this which denotes the CoE environment. 
![image](https://user-images.githubusercontent.com/89584709/182851009-a889399a-3f3e-47ae-9240-0cbd7eb61c9d.png)

Do you have that in your runs? If not you may have an unmanaged layer on the the flow preventing you from filling in this data, and hence using this feature. 
Here is some help on how to [remove unmanged layers](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#removing-other-customizations)

**Comment by maikletal** [comment]
Thank you Jenefer. Effectively that step does not appear and I have an unmanaged layer. I'm going to delete it and see if it works later.

**Comment by maikletal** [comment]
Hi Jennifer,

I have tried your solution and deleting the unmanaged layer the flow has worked correctly.

Now we have a bigger problem that I don't know if you can give us any suggestions.

The CoE was installed by a user who is no longer part of the company, so the connections used by the original layer do not work. 

If in each flow we update the connections to use a business account that we have created to manage the CoE, that unmanaged layer is created automatically.

Therefore, now all flows have an unmanaged layer and do not receive updates correctly.

Can we update the connections of all flows without creating an unmanaged layer?

**Comment by Jenefer-Monroe** [comment]
I'm not absolutely certain, but I believe the below will resolve it.  Please let me know.

See [co-auth and connections](https://docs.microsoft.com/power-platform/guidance/coe/limitations#co-authoring-and-connections)

![image](https://user-images.githubusercontent.com/89584709/183449132-25dba0e4-f284-454a-93e4-1f0ca74554dc.png)

![image](https://user-images.githubusercontent.com/89584709/183449490-c0016792-457b-41e5-910a-59690f98ddfd.png)

**Comment by maikletal** [comment]
Hi Jennifer,

I've updated all connections and removed all unmanaged layers from all flows and everything seems to be working fine.

Thank you very much for your help.

I think we can close the issue.

Best regards
Miguel
