### ISSUE TITLE
Where are the Email Header and Style stored in CoE Environment ?

### ISSUE THREAD

**Issue by kartrabby** [microsoft/coe-starter-kit#3358]
Dear Team,

In my company, we want to customise the Header and Style that the CoE Toolkit is sending the emails.

Can you please let me know in which **Table** in **CoE Environment** the values are stored ? 

@{parameters('eMail Header Style (admin_eMailHeaderStyle)')}
@{parameters('eMail Body Start (admin_eMailBodyStart)')}
@{parameters('eMail Body Stop (admin_eMailBodyStop)')}

![image](https://user-images.githubusercontent.com/95188375/182853473-03466f3d-f5ba-4253-be7a-8164cddf37ce.png)

**Comment by kartrabby** [comment]
Hi @manuelap-msft , thank you. I got it, there were two tables **Environment Variable Definition** and **Environment Variable Value**.

I found it in the **Environment Variable Definition** table.

**Comment by manuelap-msft** [comment]
Here's how we recommend to update and review Environment Variables, either using the Admin - Command Center App or going via the Default solution: 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
