### ISSUE TITLE
Features required by Microsoft license

### ISSUE THREAD

**Issue by Chabouz7** [microsoft/coe-starter-kit#3362]
### What is your question?

It states that Microsoft 365 is required as a license required to install the CoE Starter Kit.

[What identity should I install the CoE Starter Kit with?](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with:~:text=365%20service%20admin.-,Power%20Apps%20Per%20User%20license%20(non%2Dtrial)%20and%20Microsoft%20365%20license.,-Power%20Automate%20Per)

I want to minimize the apps that can be used with Microsoft 365.
Is it enough to enable only Exchange Online?
Do you need any other apps?

The Power Apps Per user license is a prerequisite.

### What solution version are you using?

July 2022

**Comment by manuelap-msft** [comment]
Hello,

the CoE Kit uses connectors to send emails via the Outlook connector and post adaptive cards to Teams via the Microsoft Teams connector. So you may need those two apps. However this is a best guess, we have never tested removing apps from the license. 

Manuela

**Comment by Chabouz7** [comment]
Thank you for letting me know immediately.
I understand that I need to use the Outlook and Teams connectors. I would like to try.
