### ISSUE TITLE
[CoE Starter Kit - QUESTION] Status 400 Error with StartSubscription of Office 365 Management API Custom Connector

### ISSUE THREAD

**Issue by ddomboy** [microsoft/coe-starter-kit#3364]
### What is your question?

When trying "StartSubscription" for the Office 365 Management API Custom Connector I get the following Status 400 error:

"Tenant  xxxxx does not exist."

I checked in my Azure AD and the tenant is identical with the one I pasted. Is there any other issue I might have overseen?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Office 365 Management API

**Comment by manuelap-msft** [comment]
Here are some typical issues we see:
![image](https://user-images.githubusercontent.com/55705669/183056083-30ea57aa-c4fd-4cf7-92b0-73f2b174117d.png)

Also make sure you don't have blank characters anywhere you pasted in the tenant ID.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
