### ISSUE TITLE
[ALM Accelerator - BUG]: Solution-Upgrade tag not working

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#3366]
### Describe the issue

When adding the 'solution-upgrade' tag to a PR to import the solution as upgrade the solution is always imported as update

### Expected Behavior

Expect the solution to be imported as upgrade when the 'solution-upgrade' tag is added to PR

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

CenterofExcellenceALMAccelerator-August2022

### Steps To Reproduce

1. Create PR with 'solution-upgrade' tag
2. Neither build validation or subsequent deploy pipelines will import as upgrade

### Anything else?

It seems the condition to check the buildreason should be reversed to 
`if ($buildReason -eq "PullRequest") { `
on line https://github.com/microsoft/coe-alm-accelerator-templates/blob/eeda26a98142f188ca20eace1625fa3f046e917a/PowerShell/set-trigger-solution-upgrade.ps1#L27

Also, the following query seems not to return a PullRequest Id
`{
      "queries": [{
          "items": [
              "$buildSourceVersion"
          ],
          "type": "lastMergeCommit"
      }]
}`
on line https://github.com/microsoft/coe-alm-accelerator-templates/blob/eeda26a98142f188ca20eace1625fa3f046e917a/PowerShell/set-trigger-solution-upgrade.ps1#L36

**Comment by mikefactorial** [comment]
We've removed the Solution Upgrade PR tagging in favor of using deployment settings in the September release. Closing this issue out.
