### ISSUE TITLE
[CoE Starter Kit - BUG] Users still getting notifications for teams environment and apporved apps/flows to be deleted

### ISSUE THREAD

**Issue by diego-coke** [microsoft/coe-starter-kit#3369]
### Describe the issue

All the users from our tenant are getting weekly notifications about apps/flows to be deleted if they are not using them. Still, even if users approve the deletion of objects they continue to get the notifications.

There is another group of users that get similar notifications for team environments that are already rejected by the admin to be deleted. Still, they continue to get notifications on a daily basis.

### Expected Behavior

to send only the notifications when users don't respond to the approval/rejection process

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.17

### What app or flow are you having the issue with?

Not sure

**Comment by Jenefer-Monroe** [comment]
Apps/Flows: Do you have all the flows in the [inactivity notifications components](https://docs.microsoft.com/power-platform/guidance/coe/setup-archive-components) instructions turned on?
Teams Environments: Do you have all the flows in the [D4T environment management](https://docs.microsoft.com/power-platform/guidance/coe/setup-teams-components) instructions turned on?

If so, here is my recommendation
1. Make sure you dont have any [unmanaged layers](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) on any of them. 
2. Find an example app that you expect to have been deleted, and an example environment that you expect to have been deleted. 
3. Return here ready with that information and we can debug by having you look through the flow runs.

**Comment by myatix** [comment]
@Jenefer-Monroe 




We are also having this issue! 
Versions:
![image](https://user-images.githubusercontent.com/48433526/183401112-3275935f-7d40-4038-9a6b-90d734b6245e.png)

Users continue to get spammed by notifications via Teams and Email despite having responded to the Approval Workflow?

This app appears to be unused; can we delete? Floor Estimates App
OWNER DOES NOT EXIST. APPROVAL SENT TO ADMIN.
You own an app that has not been modified nor launched recently.

Last Modified:  06 Feb 2020
Last Launch:  unknown

If the user approves the App for deletion the App doesn't get deleted. They simply get a new notification and then have to Approve the deletion again. (Nothing gets deleted or cleaned up???)

![image](https://user-images.githubusercontent.com/48433526/183400054-8636825f-0e06-4e28-a267-21db667f05fa.png)

If I look at the "App and Flow Inactivity Notification Cleanup" App I cannot see the app that is approved for deletion (Floor Estimates App)

![image](https://user-images.githubusercontent.com/48433526/183400769-23d7ac67-6fe4-40d8-be43-51633f06b5a7.png)

How does the "App and Flow Inactivity Notification Cleanup" get updated? (Which flow updates the "App and Flow Inactivity Notification Cleanup" table?)

Why do users keep getting notified despite having reacted to the Approval flow?

**Comment by Jenefer-Monroe** [comment]
### Here is what the flows do:
These two start the approval process, find unused objects and create an approval:
- Admin | Inactivity notifications v2 (Start Approval for Apps)
- Admin | Inactivity notifications v2 (Start Approval for Flows)

Product itself receives the response (approve/reject) to the request and writes it to a product table (msdyn_flow_approvalresponses)

This flow migrates this response to our own CoE table (Archive Approvals)
- Admin | Inactivity notifications v2 (Check Approval)

This flow deletes the unused object if approved after reminding the user to back up for a few weeks
- Admin | Inactivity notifications v2 (Clean Up and Delete)

**Comment by Jenefer-Monroe** [comment]
We can use your Floor Estimate App with the investigation above. 
It sounds from your investigation like the user is responding "approved" but then the app isnt showing up as approved. 

1. Do you have all the flows in the [inactivity notifications components](https://docs.microsoft.com/power-platform/guidance/coe/setup-archive-components) instructions turned on? If so, please share a screenshot showing that, like this:
![image](https://user-images.githubusercontent.com/89584709/183439360-1bd52a13-2d03-4e52-8e02-ecfae50cff98.png)

2. Make sure you dont have any [unmanaged layers](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) on any of these. 

3. See if any are of the flows have failure. 

4. See if you find the app in other views (ex Apps - rejected)

5. See if you have their repsonse recorded in the Approval Responses table
![image](https://user-images.githubusercontent.com/89584709/183446550-67efc5c3-557d-4676-85e4-41a88763ea17.png)
![image](https://user-images.githubusercontent.com/89584709/183447803-74d54f9a-3370-42e7-aa9c-f8060c877d91.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
