### ISSUE TITLE
[CoE Starter Kit - QUESTION] About GroupAddress

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#3372]
### About GroupAddress

Should a group address be created in the public or private setting? Is there anything wrong with either setting?

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

No

**Comment by Jenefer-Monroe** [comment]
We envision most people using private here, which is why we have this caveat, the entity running the flow will need to be a group owner in order to add people to it:

![image](https://user-images.githubusercontent.com/89584709/183428905-c24c8dda-5f04-4d45-9381-516fbc741530.png)

**Comment by egym07** [comment]
Thank you very much. 
Thank you for your continued support.

**Comment by Jenefer-Monroe** [comment]
You are very welcome, thanks for using CoE!
