### ISSUE TITLE
Audit Log Flow throws error

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#3373]
### Describe the issue

Admin Sync Audit Logs throw error

![image](https://user-images.githubusercontent.com/17232756/183319713-44b611cc-c034-4ea5-967c-0586f28d0e18.png)

### Expected Behavior

Audit logs should sync and populate the dataverse table

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.19

### What app or flow are you having the issue with?

Admin Sync Audit Logs

### Steps To Reproduce

Run Admin Sync Audit Logs from make.powerautomate.com

**Comment by manuelap-msft** [comment]
Hello,

the error you shared indicates that the child flow has failed - the error is occurring in the child flow **[Child] Admin | Sync Logs**. Could you please look at the Details page of this child flow, open a failed run and share the failure from there?

Thank you,
Manuela

**Comment by Jenefer-Monroe** [comment]
And then most of the time, this error means that you did not fix up the Custom Connector after upgrade. Please see https://github.com/microsoft/coe-starter-kit/issues/1424 for steps on how to fix.

**Comment by girishuppal** [comment]
> Hello,
> 
> the error you shared indicates that the child flow has failed - the error is occurring in the child flow **[Child] Admin | Sync Logs**. Could you please look at the Details page of this child flow, open a failed run and share the failure from there?
> 
> Thank you, Manuela

![image](https://user-images.githubusercontent.com/17232756/183543885-082af2e2-ad1d-47bb-92cc-a46db88366f2.png)

**Comment by manuelap-msft** [comment]
> And then most of the time, this error means that you did not fix up the Custom Connector after upgrade. Please see #1424 for steps on how to fix.

This looks like the connection for the Custom connector is not available. As per Jenefer, please see #1424 for how to fix that.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
