### ISSUE TITLE
[CoE Starter Kit - QUESTION] About uploading template files to the template catalog

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#3374]
### What is your question?

We are investigating the specifications of the app in order to use the "template catalog" of the Nurture component.

Since this app refers to "CoE Templates" in the Dataverse table, it is a recognition that you need to upload the file to "CoE Templates" to download the template file from the app.

However, since you cannot upload a file to the Dataverse table from the edit screen of the table, it is a recognition that you need to create a new upload application or flow.

Do I need to create this upload app on the user side in order to use the template catalog?

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Template Catalog

**Comment by Jenefer-Monroe** [comment]
Thats correct, this app was not created for you. 
Please see https://github.com/microsoft/coe-starter-kit/issues/3096 for tracking creation of such an app

**Comment by sudadakkota** [comment]
Thank you.
I will make that app!

**Comment by Jenefer-Monroe** [comment]
Thanks for the update! I will go ahead and close but please feel free to post new issues as you work through the COE
