### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to Change run-only permissions for Cloud Flow

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3376]
### Describe the issue

The documentation for setting up audit logs solution includes editing the power automate flow [Child] Admin | Sync Logs and as part of that setup, you are meant to edit the run only users settings and select for the three connectors Use this connection (userPrincipalName@company.com). 
For the Microsoft Dataverse connection it does not give the option of my own connection and only presents me with the run-only user even though I do have a Dataverse connector setup.
![image](https://user-images.githubusercontent.com/17124284/183458811-08f1ca21-4dc3-4575-b88d-51d877ebe9bc.png)

My connector set up:
![image](https://user-images.githubusercontent.com/17124284/183458934-a027e253-6a12-4981-8c23-822de158ae38.png)

You can see the connection references
![image](https://user-images.githubusercontent.com/17124284/183459189-710252f3-6b4f-4ce2-8d84-51020a2822e9.png)

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
We have seen one other customer hit this, and it went away after some time, seemingly on its own. They may have done something in the background that fixed it, I'm not sure why or what they did. 
It does seem some product issue that intermittently hits people. I'm afraid I'm not sure how to fix. Can you please create a support ticket?

**Comment by medicineshow** [comment]
Yes that seems to have rectified itself but now I am getting an error in the child flow with a status 403

{
  "status": 403,
  "source": "https://uk-001.token.azure-apim.net:443/tokens/uk-001/admin-5foffice-20365-20management-20api-5f0a498ed2627aa6c8/shared-admin-5foffic-08e68112-b7a6-4d05-840f-32d5-79cdd96c/exchange",
  "message": "Error from token exchange: Permission denied due to missing connection ACL: Connection https://uk-001.azure-apim.net/@uk-001/logicflows/ef5b26bc-8cb3-2105-ad93-1a08b9bf78bb version -9223372036854775808, connection=uk-001/admin-5foffice-20365-20management-20api-5f0a498ed2627aa6c8/shared-admin-5foffic-08e68112-b7a6-4d05-840f-32d5-79cdd96c"
}

yet if I test the Office 365 Management API custom connector, I get 200 code returned.
![image](https://user-images.githubusercontent.com/17124284/183511453-2aae7832-9df5-4b2b-ada4-1b89c6238d0c.png)


I noticed in the List audit log content step that the PublisherIdentifier is populated with the Tenant Id variable. Is that correct?
![image](https://user-images.githubusercontent.com/17124284/183504793-835de6b9-8d11-4ac4-b5d4-36c529b06c95.png)

Because in the documentation: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content
when starting a subscription, it asks you to Paste the application (client) ID into PublisherIdentifier field.

**Comment by Jenefer-Monroe** [comment]
Can you please double check that your Run-only user permission for the custom connector is in place? 
![image](https://user-images.githubusercontent.com/89584709/183516144-061ef649-5042-4ccc-a1cc-590f2e02ba31.png)

**Comment by medicineshow** [comment]
They are confirmed. And it is the same account that I use to test the custom connector
![image](https://user-images.githubusercontent.com/17124284/183517986-333072bf-93e1-4969-bc1b-77c7f1f1b1b1.png)

**Comment by medicineshow** [comment]
I should add that this is since the update

**Comment by medicineshow** [comment]
I may have fixed it. By deleting the existing connections and then re-creating them it appears to be running successfully now.

**Comment by medicineshow** [comment]
I will check in the morning to see if it has completed but it is looking much better

**Comment by Jenefer-Monroe** [comment]
Thank you for the updates!

**Comment by medicineshow** [comment]
yes, all looks good. Thanks for the help.
