### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to Import Power BI Dashboard : admin_recordguidasstring

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3377]
### Describe the issue

When importing the August release Production_CoEDashboard_August2022.pbit the import errors with the message:

Column 'admin_recordguidasstring' in Table 'Maker' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.

This prevents all other tables loading and so I am unable to setup the dashboard.

![image](https://user-images.githubusercontent.com/17124284/183471460-7d474ed4-593e-45f1-8b82-d39d169c1a56.png)

If I look in the Dataverse at the Maker table, I can see that the column Record GUID as String has multiple entries that are blank

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Power BI Dashboard

**Comment by Jenefer-Monroe** [comment]
We reshipped the PBIT files with this fixed. Can you please re-download? [https://aka.ms/coestarterkitdownload](https://aka.ms/coestarterkitdownload)

**Comment by medicineshow** [comment]
@Jenefer-Monroe that fixed it thank you. Did I miss an announcement regarding this somewhere?

**Comment by Jenefer-Monroe** [comment]
No we snuck them in quite soon after shipping so assumed we had caught it for most people. 
My most eager hard working clients are just too fast for me :)

**Comment by medicineshow** [comment]
Thanks for the help
