### ISSUE TITLE
[BUG]: CLEANUP - Admin | Sync Template v3 (Check Deleted)

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/coe-starter-kit#338]
**Description**
CLEANUP - Admin | Sync Template v3 (Check Deleted) , every time it fails with different error.
- Action 'List_CoE_Environments_not_marked_deleted' failed
- Action 'Get_Environment_as_for_appmodules' failed
- ListDefns-PowerAutomateEnvironmentVariable failed status code 400

**Component (please tell us which flow or app you are experiencing issues with):**
-Solution Core Component
-Version 1.98
-CLEANUP - Admin | Sync Template v3 (Check Deleted)

**To Reproduce**
.Go to CLEANUP - Admin | Sync Template v3 (Check Deleted) flow inside Core Solutions
.Click on Run
.Wait for 6-8 minutes yet time after 2 to 3 hours
.Flow will fail with the mentioned error

**Screenshots**
![image](https://user-images.githubusercontent.com/78148795/117538623-a9433f80-b024-11eb-8072-71175a005822.png)

![image](https://user-images.githubusercontent.com/78148795/117538639-c415b400-b024-11eb-943f-a78845b4b137.png)

![image](https://user-images.githubusercontent.com/78148795/117538644-ce37b280-b024-11eb-8a0d-481c2a848396.png)

**Comment by JeneferM-MSFT** [comment]
closing out as no action for toolkit here.
