### ISSUE TITLE
FLOWS SUPPORTING BUSINESS JUSTIFICATION AND CLEANUP FOR TEAMS ENVIRONMENTS

### ISSUE THREAD

**Issue by michaelgottwals** [microsoft/coe-starter-kit#3382]
### What is your question?

I am running version 3.22 (Aug 2022) of the Teams CoE Starter Kit and I am looking to utilize the Teams environment business justification / cleanup functionality. However, when I check the list of flows available for the core components for Teams solution I do not see any flows that are related to that. The documentation states its part of the governance components, but it appears that functionality has been combined with the core components. Does anyone have any guidance on this topic?

Thanks in advance.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2022 3.22

**Comment by manuelap-msft** [comment]
Hello,

correct, this process is part of the Governance components so you'll have to additionally import and setup the Governance components in your Teams environment to use those processes.

Hope that helps,
Manuela

**Comment by michaelgottwals** [comment]
Hello Manuela,

Thanks for your response. I am confused because when I look at what is included in the CoE Starter Kit download zip file, I do not see a governance components managed zip file. I only see a Governance CoE Dashboard. (see screenshot) So where do I get the governance components Teams zip file to import into my Teams environment?

![image](https://user-images.githubusercontent.com/79226165/183727891-8798db6e-9b04-4521-9b85-17f8dcc11f7f.png)

**Comment by Jenefer-Monroe** [comment]
Here are the [setup instructions for governance](https://docs.microsoft.com/power-platform/guidance/coe/before-setup-gov), it will point you to the correct folder. 

Then once you do that you can decide to enable the features you desire. 
- [Setup inactivity notifications](https://docs.microsoft.com/power-platform/guidance/coe/setup-archive-components)
- [Setup compliance processes](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components)
- etc

**Comment by michaelgottwals** [comment]
Thanks @Jenefer-Monroe for this information. I have now installed the governance components in my CoE starter kit Teams site. I will look further into features.
