### ISSUE TITLE
Governance Power BI Dashboard is not upgrading

### ISSUE THREAD

**Issue by sumedhsharangdhar** [microsoft/coe-starter-kit#3383]
The PBI dashboard for CoE governance is not upgrading, as we are getting error as "RPA" Table not found. Looked in the Solution there is table for "RPA Sessions" but not RPA. Please suggest

**Comment by Jenefer-Monroe** [comment]
The Governance PBI does not pull in RPA (Desktop Flow) data. Can you please 

1. Let us know what version of Core you are on
2. Share a screenshot of the tables shown in the Fields well when you open the report in the desktop
![image](https://user-images.githubusercontent.com/89584709/183656746-c747472a-4797-4628-b611-2be9e515bcbd.png)

**Comment by manuelap-msft** [comment]
We were able to repo this and have just released a hot fix to this dashboard which you can download from here: https://github.com/microsoft/coe-starter-kit/raw/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/PowerPlatformGovernance_CoEDashboard_202208.pbit 

Please let us know if that works for you!

**Comment by manuelap-msft** [comment]
Closing as fixed.
