### ISSUE TITLE
[ALM Accelerator - BUG]: GetOrganizations in CustomAzureDevOps fails - Docs

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#3384]
### Describe the issue

For the Operation `GetOrganizations` I get and **HTTP 404**: **The resource cannot be found.**

<img width="830" alt="image" src="https://user-images.githubusercontent.com/15800069/183595758-8af17991-1e8b-4b51-94fd-e944aed42e48.png">

However, the operation `GetProjects` work.

### Expected Behavior

The operation provide information about my Azure DevOps organizations

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

August 2022

### Steps To Reproduce

1. Open custom connector `CustomAzureDevOps`
2. Goto *TEST*
3. Execute `GetOrganizations`

### Anything else?

The connector output for `GetOrganizations` was:

```json
{
  "content-length": "29",
  "content-type": "text/plain; charset=utf-8",
  "date": "Tue, 09 Aug 2022 12:20:43 GMT",
  "p3p": "CP=\"CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT\"",
  "request-context": "appId=cid-v1:c0f1266c-12b7-42e9-97fb-d15434ef9c3e",
  "strict-transport-security": "max-age=31536000; includeSubDomains",
  "x-cache": "CONFIG_NOCACHE",
  "x-content-type-options": "nosniff",
  "x-ms-apihub-cached-response": "true",
  "x-ms-apihub-obo": "true",
  "x-msedge-ref": "Ref A: D5E970FF5BDE46E7BCAA3A1D9278384B Ref B: DUS30EDGE0315 Ref C: 2022-08-09T12:20:44Z",
  "x-tfs-processid": "6e3d9f54-4eec-4164-9fd9-b0e6c41d674c",
  "x-tfs-serviceerror": "The%20resource%20cannot%20be%20found."
}
```

In ALM Accelerator for PP:
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/15800069/183645929-dd00ffb2-6dbb-463f-b0c1-2c8643be25c5.png">

No Solution Layers:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/15800069/183646344-d8a57eb7-8952-4227-b34f-f4082b661ae9.png">

**Comment by megel** [comment]
@mikefactorial  yes, this was the issue:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/15800069/183690926-77b66d46-e9bf-4d55-9478-74861028566b.png">

After adding the policy:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/15800069/183691787-c1a2fe23-af9c-46d0-a1cf-8103b1018047.png">

I guess the policy was removed during import.

**Comment by mikefactorial** [comment]
Need to document this issue and follow up with the product team on how this happens.
