### ISSUE TITLE
[CoE Starter Kit - Feature]: Delete makers and users without flows/apps

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#3387]
### Describe the solution you'd like

Hi team,
in order to have a healthy list of makers or Power Platform Users, it would possible to delete of the inventory the makers that doesn't have any flows or apps and Users that doesn't have apps shared with?

![image](https://user-images.githubusercontent.com/57954993/183610314-7951edd3-9eda-4b0c-9927-b93a1f1e67f8.png)
![image](https://user-images.githubusercontent.com/57954993/183610486-bb69721d-c152-4994-b325-4259065b2dfb.png)

**Comment by manuelap-msft** [comment]
Hello,

thanks for the suggestion! I suspect implementing this may be very API call heavy and we have to be conscious of how many API calls the kit consumes. I would recommend setting up a Bulk Deletion job with a condition to regularly clean up those tables: https://docs.microsoft.com/en-us/power-platform/admin/delete-bulk-records

**Comment by albertocaa1317** [comment]
Thanks for your suggestion also @manuelap-msft 😀
I will try this alternative. If works I will confirm it you for if it's interesting for CoE Users.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by bdestrada** [comment]
Hi,

"I would like to automatically delete my deleted users from the environment in the "Makers" table. 

Is there a way to do this?

Ps.:  In my environment, the variable "ProductionEnvironment" is set to "yes".

Thanks
