### ISSUE TITLE
[CoE Starter Kit - BUG] isSystem Data Type in Power BI Dashboard

### ISSUE THREAD

**Issue by EmMoLe** [microsoft/coe-starter-kit#3388]
### Describe the issue

When customizing the Power BI Dashboard in Power BI Desktop, all of the visualizations appear as expected. When viewing the published dashboard in Power BI Service, however, the rows for the environments and makers tables do not populate in the Power Apps and Power Automate Overview pages. 

It appears the "isSystem" column in the Makers table is set to a TEXT column type instead of TRUE/FALSE column type. After changing the column type to TRUE/FALSE, the tables populated as expected when viewing the dashboard in Power BI Service.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July Release

### What app or flow are you having the issue with?

CoE Power BI Dashboard

### Anything else?

I worked with some very smart folks in the MS Support team to resolve this issue.

**Comment by manuelap-msft** [comment]
This was fixed with our August release, see https://github.com/microsoft/coe-starter-kit/issues/3322#issuecomment-1203656138
