### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can't see app sessions in PBI (no audit logs installed)

### ISSUE THREAD

**Issue by GaelCasOuv** [microsoft/coe-starter-kit#3389]
### What is your question?

Hi, I have installed the CoE starter kit and the related PowerBI dashboard but I'm facing two issues.

The first one is I cannot see the apps sessions and when they were launched the last time.

The second one is there are some strange names in the apps, I don't know why they appear like this.

![image](https://user-images.githubusercontent.com/110904209/183634415-ac6bab67-3a66-43c5-9e0c-329a34220122.png)

Could you help me please?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2022

### What app or flow are you having the issue with?

PowerBI Dashboard

**Comment by Jenefer-Monroe** [comment]
Things like Sessions and Last Launched are collected by a second solution you need to install, the [Audit Logs](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog).  

Sometimes SharePoint Forms Apps get names auto-generated like this. If you look on the right you will see some filters, you can filter to see by app type
![image](https://user-images.githubusercontent.com/89584709/183654821-f6d717d4-45c5-475a-8e5f-1dfd26f57882.png)

Hope that helps, and welcome to CoE

**Comment by GaelCasOuv** [comment]
It works now, thank you very much Jenefer :-)

**Comment by Jenefer-Monroe** [comment]
Wonderful news. Thanks for letting me know! I'll close this out now then but please return if you have more questions.
