### ISSUE TITLE
[BUG]: Why Would the PowerBI Report only show 25 Environments when they are more ?

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#339]
**Describe the bug**
The PowerBI report is only showing me 25 Environments.  I have checked the AdminView Model App and that is only showing 25 Environments

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 2.0
 - App or FlowPowerBI

**To Reproduce**
1. Load the PowerBI Report
2. Navigate to the Environments Tab#
3. View environments

**Expected behavior**
I would of expected more than 25 environments (I have actually got 32)

**Screenshots**

**Additional context**
Which Flow updates the Environments CDS item ?

**Comment by JeneferM-MSFT** [comment]
closing out as no action for the toolkit.
