### ISSUE TITLE
[ALM Accelerator - QUESTION] How to use environments in deployment pipeline

### ISSUE THREAD

**Issue by ryanhodgson1** [microsoft/coe-starter-kit#3394]
### What is your question?

Hi, i am trying to get pipelines to deploy using the environments variable in the YAML pipeline and i can see the file deploy-Solution-To-Environment.yml has the code in there to do it, but i cant see how to do a build and deploy and include this in, as the file build-deploy-Solution-To-Environment.yml only references the deploy-Solution.yml, not the deploy-Solution-To-Environment.yml file.

Is this something that i have to manually configure in the files? or is there something im missing to get this going with how the repo is currently setup?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220517.1

**Comment by mikefactorial** [comment]
@ryanhodgson1 sorry this got buried in the feedback. I'm not sure I understand the issue. Can you supply a screen shot or error message that you're seeing specifically?

**Comment by mikefactorial** [comment]
Closing out for now. Feel free to open a new issue if this is still a question.

**Comment by mrramosjr21** [comment]
Hi @mikefactorial , I have the same question. We are trying to deploy a branch to either test or Production without merging it to the test branch and main branch to trigger the pipeline for deployment.

Do you have a documentations on how we can deploy a branch directly to the environment we want without doing the validation, merge to test and main (prod) merging. It would be great if you can help us re-use the pipeline for our deployment of Branch only. Thank you in advance.

**Comment by ryanhodgson1** [comment]
@mrramosjr21 @mikefactorial 

I ended up just putting an environment approval stage in the environment template. For example in the YAML file deploy-ccmscrmdevfulldev-SampleSolution.yml has this stage added at the start:

![image](https://user-images.githubusercontent.com/77652317/202876579-4db6b4ae-5eca-4830-a22d-cd9a1be4e307.png)
