### ISSUE TITLE
[BUG]: No items in Template Catalog

### ISSUE THREAD

**Issue by remenator** [microsoft/coe-starter-kit#340]
**Describe the bug**
When we open the Template Catalog there are no items.  We opened in designer and there is an error:
"You don't have permissions to view this data. Server Response AppTemplates failed. Something went wrong"

**Component (please tell us which flow or app you are experiencing issues with):**
Solution- nurture components
**To Reproduce**
1. Open the app in edit mode
2. View the error

**Expected behavior**
The app should open and display available apps

**Screenshots**
![image](https://user-images.githubusercontent.com/60788944/117371981-a8bc7480-ae7d-11eb-885e-44e9e39b1327.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Closing out issue as there is nothing for the toolkit here.
