### ISSUE TITLE
[CoE Starter Kit - BUG] - Admin | Capacity Alerts - Reporting on environment that no longer exists

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#3405]
### Describe the issue

The Admin | Capacity alerts email is reporting on an environment that no longer exists in our tenant. Microsoft assisted with moving the environment to another tenant.  We see no trace of this environment in https://admin.powerplatform.microsoft.com  however the CoE is still reporting on it. 

### Expected Behavior

The CoE refreshes the dataverse environment inventory fully periodically, or resolves stale entries?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin | Capacity Alerts

### Steps To Reproduce

1. Review the daily email sent out.
2. Compare to the information in the admin panel https://admin.powerplatform.microsoft.com

### Anything else?

Microsoft assisted with moving the environment from our tenant to another 3rd party tenant.

**Comment by Jenefer-Monroe** [comment]
Can you please validate that you have all flows in [the inventory setup instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) turned on and running? 

In particular there is a flow called **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** which runs and cleans up the inventory of deleted objects.

**Comment by robertcaretta** [comment]
That flow is turned on and has been running.
![image](https://user-images.githubusercontent.com/1613085/183917598-f019b08a-72cd-48b9-bda9-8d90c9d7f194.png)

We have several of the flow in an Off state, as we are not using their functionality at this time.
![image](https://user-images.githubusercontent.com/1613085/183918291-d9652262-24f6-440c-88de-989d173adb6f.png)
![image](https://user-images.githubusercontent.com/1613085/183918470-9d4b101b-5708-469d-9047-333a4c5b93b4.png)
![image](https://user-images.githubusercontent.com/1613085/183918582-dbdcb38b-5f60-4545-b473-6c5897d5e932.png)

**Comment by Jenefer-Monroe** [comment]
Ok i do repro this. I will need to do an expand filter to not return deleted environments. Can do this for Sept. 
Thanks for posting!
