### ISSUE TITLE
[ALM Accelerator - Feature]: Upgrade and Update the solution without PR

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#3407]
### Is your feature request related to a problem? Please describe.

Today you have to do a PR in order to select Upgrade/Update. Our team doesn't use PR nor does it do any branching strategy (just solution branching)

### Describe the solution you'd like

We would like a simpler way within the app to select during deployment if it should be update or upgrade, with the possibility to set this as default (maybe on the admin app)

### Describe alternatives you've considered

editing the pipelines

**Comment by mikefactorial** [comment]
@gerald560 we have an update for this in our September release https://github.com/orgs/microsoft/projects/233/views/32?filterQuery=milestone%3A%22CoE+Starter+Kit+-+September+2022%22+upgrade+

While update will continue to be the default once you set the upgrade flag in the deployment settings all subsequent deployments will be upgrades unless the flag is changed. This flag sets a variable on the deployment pipeline called TriggerSolutionUpgrade: true|false.

![image](https://user-images.githubusercontent.com/42348035/184434204-753bee8e-6ed7-44b0-93e4-ce4dbe53d304.png)


![image](https://user-images.githubusercontent.com/42348035/184434160-7d827e91-c45e-43c5-bd18-af30c42085ef.png)

Closing as a duplicate.
