### ISSUE TITLE
[CoE Starter Kit - Licensing question] Pay-as-you-go vs Premium for setting up the CoE in PROD environment

### ISSUE THREAD

**Issue by magafaterr** [microsoft/coe-starter-kit#3408]
### What is your question?

Would all features, including the Command Center App from the Core Components work without a premium license as the documentation clearly points it out, if the environment used is a PROD with Pay-As-You-Go? Is it Pay-As-You-Go an alternative? Documentation clearly lists use cases for *sharing* apps where the pay-as-you-go is best, but what about *set-up* itself, would it still work just as premium?

### What solution are you experiencing the issue with?

Core

**Comment by manuelap-msft** [comment]
For the setup itself, we recommend the user has a Power Apps Per User premium license. Although it would be possible to cover them with Pay As You Go, we estimate that that would be much more expensive than a Per User license.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
