### ISSUE TITLE
Error in loading August 2022 Power BI Dashboard [CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by ShinraTenseiii** [microsoft/coe-starter-kit#3409]
### What is your question?

While installing the Power BI CoE Dashboard after inputting the environment URL for loading the report i am getting these errors.
![image](https://user-images.githubusercontent.com/84532843/183945553-489a0e1a-84a5-4da8-8976-9a9d9619401b.png)
![image](https://user-images.githubusercontent.com/84532843/183946344-61988112-9d49-4f41-9a1d-aedf9c0470c9.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2022

### What app or flow are you having the issue with?

Power BI DashBoard Production

**Comment by Jenefer-Monroe** [comment]
Have you upgraded the Core environment already to August? 
Can you please share which PBIT file you are using?

**Comment by ShinraTenseiii** [comment]
Yes, I have upgraded the Core environment to August. I am using a PBIT file named "Production_CoEDashboard_August2022"  from the starter kit repository. According to my research, these errors are due to the Data Privacy Firewall in Power Query. The queries 'Removed Columns' and 'Outer Join' of the 'Flow' and 'App Connection Reference' tables respectively are referencing steps, not the data source.

**Comment by ShinraTenseiii** [comment]
I installed it in a Production environment. The string i entered was like (https://contoso.crm.dynamics.com).

**Comment by ShinraTenseiii** [comment]
I tried with a slash but I get the same errors again.

**Comment by Jenefer-Monroe** [comment]
I'm afraid I do not repro and so do not know how to help.

**Comment by ShinraTenseiii** [comment]
Thank you for your time @Jenefer-Monroe
