### ISSUE TITLE
[BUG]: Power BI report issue

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/coe-starter-kit#341]
**Describe the bug**
Unable to setup the Power BI report included in the latest CoE starter kit

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - N/A
 - Version - N/A
 - App or Flow - Power BI report

**To Reproduce**
1. Launch Power BI desktop and sign in using a service account with systems admin access to our dedicated CoE Environment. 
2. Browse to the PBIT file and enter the CDS URL for our CoE environment.
3. An error appears relating to SQL connectivity. 

**Expected behavior**
The report should load as expected. I need assistance to confirm if the error relates to a firewall connectivity issue on our side.

**Screenshots**
Refer to the screenshot below:

![image](https://user-images.githubusercontent.com/62425530/117029868-fc508600-acf6-11eb-8c29-797a7e25d198.png)

**Comment by JeneferM-MSFT** [comment]
Can you please try using this old version of the PBI while we work through the issues with the new direct query version? 
[Feb Version of PBI](https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-02-02%20(1).pbit)

Note that you will need to enter the org url with the prefix included as shown here: https://yourcoe.crm.dynamics.com

**Comment by hsteweri** [comment]
I'm getting "Access to ressource denied" when using the old version of the PBI

**Comment by JeneferM-MSFT** [comment]
Hello you need to be an admin on the envt in order to view he tables. Please be sure you are logged in to Power BI with the identity which setup the coe (or which has access to the envt)

**Comment by melmgcoe** [comment]
Hello, I'm able to get the PBI dashboard report working using the February release. So the issue appears to be with the April and the change to direct query as Manuela mentioned. Please let me know once the issue has been resolved and a new PBI available to download.

**Comment by manuelap-msft** [comment]
Hello,

there won't be a bug fix, as this is not an issue with the CoE Starter Kit Power BI Dashboard and we have many customers using the DirectQuery version.

There are two different ways to connect to Dataverse from Power BI:
**Import:** With this mode, data is cached in the Power BI service and imported on a scheduled interval.
**DirectQuery:** Connects directly to the data in Dataverse. This mode can also more strictly enforce the Dataverse security model. 

As you can see, these are fundamentally different ways of connecting to the data - it's not that the April version of our report has a bug and the February one does not, they just use different ways of connecting to the data. 

DirectQuery has certain pre-requisites which are listed here:
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-powerbi-connector

Going forward because many customers are struggling with the pre-requisites, we will make two version of the Power BI dashboard available - one using Import and one using DirectQuery.

**Comment by melmgcoe** [comment]
HI Manuela, thanks that's very useful info to know. I'll mention the security aspect to my team and see if it's worth looking into getting the pre-reqs in place to get the direct query version working.

**Comment by rkarthi37** [comment]
Thanks for your tips Manuela. On my side when i pasted the URL without https:// and / that connectivity error got resolved. But now I have few more errors. 
I have recently deployed COE Core 2.0 and ran all the sync flows and tried to refresh the dashboard. 
Error details are below
**RPA Sessions
Cannot convert value '' of type Text to type Date.**
**Audit Log
OLE DB or ODBC error: [DataSource.Error] Microsoft SQL: Return records size cannot exceed 83886080. Make sure to filter result set to tailor it to your report. RequestId: TDS;582c36cf-41df-47e2-9246-f764515d857d;2 Time: 2021-05-25T01:07:48.4225420Z.
**
**App
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Maker
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.**

Could you please help me to fix this errors.

**Comment by manuelap-msft** [comment]
Hello @rkarthi37,

Unfortunately you are hitting a known limitation of the TDS endpoint, which only supports 80 MB maximum size limit.
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#limitations

As your table exceeds that, you will have to use the Import connectivity mode. DirectQuery won't work for you. You can download the Power BI Template that uses Import here - please note, you will have to enter the Org Url in **https://yourorg.crm.dynamics.com** format again:
https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-02-02%20(1).pbit

**Comment by rkarthi37** [comment]
If we use Import based Power BI Template, will there be a support in future also or are there any plan to discontinue this template and planning to support only Direct based Query based template..?

Import Power BI Template works fine without any error for us.

Regards,
Karthik

**Comment by manuelap-msft** [comment]
There are no plans to discontinue support for Import - actually the opposite is true, see our roadmap item here https://github.com/microsoft/coe-starter-kit/issues/477

**Comment by rkarthi37** [comment]
Thanks a lot for clarifying it quickly.

Regards,
Karthik

**Comment by NizarFIL** [comment]
I was able to get the report to work after reaching out to our Firewall team and opening port 1433.

**Comment by manuelap-msft** [comment]
Hello,

our documentation was now updated with this troubleshooting guide, and the release from today includes the two Power BI files
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#which-dashboard-to-use

Closing out this issue.

Thank you
Manuela
