### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Dashboard Setup

### ISSUE THREAD

**Issue by keharrin** [microsoft/coe-starter-kit#3412]
### Describe the issue

I have upgraded our COE Toolkit to the July Release versions:
![image](https://user-images.githubusercontent.com/77410660/183948895-96303d48-12ba-4328-b5ca-61891bfdb583.png)

I am now trying to implement the new dashboards but I am getting this error:
The column 'admin_recordguidasstring' of the table wasn't found.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.18

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
You need to match the versions of Core and Dashboard. So I believe you will need to go find the July version of the DB if you are using the July version of Core.
