### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to Complete Microsoft 365 Management App Registration for Audit Logs

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#3418]
### Describe the issue

Unable to properly register the Microsoft 365 Management App

### Expected Behavior

Grant admin consent and link App registration to CoE kit 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Microsoft 365 Management App

### Steps To Reproduce

Created new app registration. 
Added permissions. 
Grant Admin Consent. 
Then we get an error message stating the following: 
Could not grant admin consent. Your organization does not have a subscription (or service principal) for the following API(s): Office 365 Management APIs

**Comment by Jenefer-Monroe** [comment]
Please see this section of our audit log setup instructions: [Before you use the audit log connector](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#before-you-use-the-audit-log-connector)

![image](https://user-images.githubusercontent.com/89584709/184024248-5f1c94e2-39c6-42d3-a3e8-17b2991ada78.png)

**Comment by nasilvae** [comment]
Thank you
