### ISSUE TITLE
[CoE Starter Kit - BUG] seeing multiple flow failures after upgrade to core 3.41

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [microsoft/coe-starter-kit#3421]
### Describe the issue

After updating to core 3.41 we went from one or two flow failures daily to 53 today.  Failures all seem to include "Get_(x)_from_CoE' failed", " 'Get_Connections_as_Admin' failed", maker checks or "See_if_Apps_Exist".  

Affected flows:
Admin | Sync Template v3 (Custom Connectors)
Admin | Sync Template v3 (Connection Identities)
Admin | Sync Template v3 (Solutions)
Admin | Sync Template v3 (Apps)
Admin | Sync Template v3 (RPA)
Admin | Sync Template v3 (Connection Identities)

### Expected Behavior

Flows should function normally.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Multiple - listed in details

### Steps To Reproduce

Update to core 3.41
Observe multiple flow errors

**Comment by DaveTheTeamsGuy** [comment]
Might have found it digging around other issues - HELPER - Maker Check flow was not on, thinking because I skipped filling in the new Graph environment variable when I updated to 3.41.  I just enabled, will monitor next error run and report back again tomorrow.

**Comment by Jenefer-Monroe** [comment]
Thanks, yes I'm sure thats what it is. There was a new env variable added that some people have run up against. 
I'll leave this open for now though, please let us know.

**Comment by DaveTheTeamsGuy** [comment]
Enabling the flow did the trick.  Closing.  Thanks!

**Comment by Jenefer-Monroe** [comment]
Thanks for debugging :)
