### ISSUE TITLE
Making modifications to already imported and managed solution

### ISSUE THREAD

**Issue by VanamaLaxmiChaithanya** [microsoft/coe-starter-kit#3425]
We have imported solution and now we want to modify flows and it is creating Unmanaged layer. We need clarifications on the below points
1. How to change the Unmanaged layer to Managed layer
2. Are the dependencies will also get Unmanaged after changing any flow or App
3. Creating a replica of existing solution and updating to the newly imported solution,What all components it will impact in both the solutions.
4. Exporting any Dataverse table and importing that table in new solution, will it impact any component in exisiting solutions.

**Comment by manuelap-msft** [comment]
Hello,

we have this article on extending the CoE Starter Kit
https://docs.microsoft.com/en-us/power-platform/guidance/coe/modify-components

Can you read through this and let me know if you have any questions after that?
