### ISSUE TITLE
[CoE Starter Kit - BUG] I cannot see data in the overview sections in the PowerBI dashboard

### ISSUE THREAD

**Issue by GaelCasOuv** [microsoft/coe-starter-kit#3428]
### Describe the issue

 I cannot see data in the overview sections in the PowerBI dashboard.

Screenshot below:

![image](https://user-images.githubusercontent.com/110904209/184090851-40f0d5f6-6163-4ace-8aa8-6df092974a5a.png)

![image](https://user-images.githubusercontent.com/110904209/184090894-55f3c531-8117-4b08-93c7-2854ce86ed7e.png)

However I can see the data in the other menus (apps, environements, etc)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2022

### What app or flow are you having the issue with?

PowerBI Dashboard

**Comment by GaelCasOuv** [comment]
Hi, the issue is solved.

I changed the boolean "false" in the filters to a 0 and the data is visible now.

I followed this thread:

https://community.powerbi.com/t5/Service/Power-BI-Report-not-showing-data-after-publishing-to-Service/m-p/413508

**Comment by Jenefer-Monroe** [comment]
Thanks for the update. We did fix this in the August release so you wont need to do this again next time you upgrade.
