### ISSUE TITLE
[CoE Starter Kit - QUESTION] Does audit log capture model driven app launch ?

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#3431]
### What is your question?

does COE audit log shows Model driven app launch ? or it shows only canvas app launch ?

Currently it showing only canvas app launch ? am I missing any configuration to show model driven app launch ?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Apr 2022

**Comment by manuelap-msft** [comment]
Hello,

the CoE Starter Kit gets Audit Log information from the Microsoft 365 Purview Audit Log (https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps) and only canvas app launches are logged there. We do not currently have a feature to monitor model driven app launches - I think this is available if you set up Application Insights: https://docs.microsoft.com/en-us/power-platform/admin/analyze-telemetry

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
