### ISSUE TITLE
Installation - Unrecognized arguments

### ISSUE THREAD

**Issue by and-bd** [microsoft/coe-starter-kit#3444]
Problems following the documentation for ALM Accelerator for Power Platform setup: https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/admin-install 
So far we've identified on the installation script 2 'az ad app' commands with arguments no longer valid and are unable to proceed, first one is "available-to-other-tenants". After removing that argument the script proceeds but ends up exiting without further feedback.
MS support pointed us to creating a new issue here. Can you please advise?
Thanks in advance

**Comment by mikefactorial** [comment]
@and-bd will need to investigate this issue and follow up.

**Comment by mikefactorial** [comment]
@and-bd looks like you may be using an older version of the coe-cli with the latest version of the azure cli. There are fixes in the August release to support some breaking changes in the Azure CLI that were introduced here. https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration.

Make sure you have the latest version of the coe-cli (https://github.com/microsoft/coe-starter-kit/tree/main/coe-cli) and your azure cli version is >= 3.8.0 (https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/install#prerequisites)

**Comment by mikefactorial** [comment]
Closing this out as there's no further action required.
