### ISSUE TITLE
[CoE Starter Kit - Feature]: Dashboard-PowerPlatformAdminDashboard not available

### ISSUE THREAD

**Issue by ddomboy** [microsoft/coe-starter-kit#3445]
### Is your feature request related to a problem? Please describe.

Hey,

I wanted to Configure Power BI dashboard, where I need the Dashboard-PowerPlatformAdminDashboard Folder from the download zip. But there is no such data in it. Even if I download it again it doesn't contain it. Do I have to download a seperate folder for this or where can I find it?

### Describe the solution you'd like

Can you explain where I can download the proper folder?

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont know the answer this question, and we are not staffed to assist with customizations. We can leave this question open for a bit though to see if others in the community can chime in. If not, you would probably benefit from asking in the general Power Apps community the generalized question, how to find dashboard objects in a solution download.

**Comment by manuelap-msft** [comment]
Are you looking for the Power BI Dashboard files that are part of the CoE Starter Kit? Outside of the .zip file download, you can also find them here
https://github.com/microsoft/coe-starter-kit/tree/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit

Note that our dashboards are called:
Production_CoEDashboard
Teams_CoEDashboard
PowerPlatformGovernance_CoEDashboard

I believe in some very old verisons the file was called Dashboard-PowerPlatformAdminDashboard but isn't anymore. Did you find a reference to that old name in our docs and if so could you let us know where so we can correct it? Thank you!

**Comment by ddomboy** [comment]
Thanks for the answer! In my guide to enable the CoEStarterKit they say I need "Dashboard-PowerPlatformAdminDashboard", so this might be a very old instruction then. But which file is the right one to choose now?

The Production-, Teams-, or the PowerPlatformGovernance CoEDashboard file?

Thanks in advance!

**Comment by manuelap-msft** [comment]
Please see: [Which dashboard to use?](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#which-dashboard-to-use) in our setup instructions

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
