### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Check Deleted (Canvas Apps)

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#3446]
### Describe the issue

The Cleanup-Admin | Sync Template v3 (Check Deleted) flow has been failing for the past months. I have narrowed it down to a specific environment that is causing the issue and a specific flow.

The flow that is causing it to fail is the **CLEANUP HELPER - Check Deleted (Canvas Apps)** flow. It is continuing to return a value of fail because there is no return value for a canvas app of the environment. Is this behavior expected and this flow will cause the Cleanup-Admin | Sync Template v3 (Check Deleted) to always fail because the environment doesn't have a canvas app?

Under the Check Deleted Scope of the CLEANUP HELPER - Check Deleted (Canvas Apps) flow it is failing at the "Get Apps as Admin" step.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/95765970/184377837-67e49940-27c0-42ea-a8b5-1dbff3fdf832.png">

The step above "List Canvas Apps not yet marked deleted" returns a blank value. I am not sure if this is why the next step is failing or not.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/95765970/184378362-b65997c9-78ce-4f8d-997f-25a75a651297.png">

### Expected Behavior

The **CLEANUP HELPER - Check Deleted (Canvas Apps)** flow to return a response to the **Cleanup-Admin | Sync Template v3 (Check Deleted)** flow that it passed because there are no canvas apps to mark delete in a specific environment. 

Please let me know if I am wrong in my thinking and this is working as expected and I should always expect this flow to fail or please provide guidance on how to fix this.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Canvas Apps)

**Comment by Jenefer-Monroe** [comment]
It looks like you've hit some product bug in which it expects some return to be a type string but is getting null without error handling. 
Please create a new flow as shown here to isolate the issue. Power Apps for Admins > Get Apps as Admin
![image](https://user-images.githubusercontent.com/89584709/184558244-f586490e-c08a-4a07-8c7f-c7b91d374801.png)

Enter your repro GUID for environment name and set the pagination policy to 100000 to match the CoE behavior (which just makes sure you return all the apps)
![image](https://user-images.githubusercontent.com/89584709/184558332-cdc90864-0033-4d4a-8b51-d3d42e3a8931.png)

Save and run the flow. 
Do you repro in this simplified version?

**Comment by AUTigers16** [comment]
Hi I just created the simplified version and I am still getting the error....

The API 'powerappsforadmins' returned an invalid response for workflow operation 'Get_Apps_as_Admin' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-AdminApps' requires the property 'body/value/0/properties/connectionReferences/4/id' to be of type 'String' but is of type 'Null'.'
![image](https://user-images.githubusercontent.com/95765970/185941754-9270fec4-fdca-4caf-baf1-ea8203ca1d8b.png)

**Comment by Jenefer-Monroe** [comment]
Thanks for narrowing. Yes this is a product issue then. You will need to create a support ticket and bring this simplified flow which isolates the issue to them.

**Comment by AUTigers16** [comment]
Thank you!

**Comment by Jenefer-Monroe** [comment]
let me know what you find!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
