### ISSUE TITLE
[ALM Accelerator - BUG]: ISSUE TITLE

### ISSUE THREAD

**Issue by edgarsosa61** [microsoft/coe-starter-kit#3447]
### Describe the issue

The accelerator (August release) stops requesting to manually create a HTTP with Azure AD, I can't find what information i need to type into, in order to continue, the HTTP connector asks:

Base Resource URL 
Azure AD Resource URI (Application ID URI) 

### Expected Behavior

Not to ask anything

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

August 2022

### Steps To Reproduce

just normal install 

### Anything else?

![image](https://user-images.githubusercontent.com/30062380/184428948-c6e87c73-e274-4fcc-843e-52da77e645a6.png)

**Comment by mikefactorial** [comment]
@edgarsosa61 from step 3 in this doc https://docs.microsoft.com/en-us/power-platform/guidance/coe/almacceleratorpowerplatform-advancedmaker#walk-through-alm-accelerator-advanced-maker-experience

If you're prompted to create an HTTP with Azure Active Directory (AD) connection, enter https;//graph.microsoft.com for both the Base Resource URL and Azure AD Resource URI.
