### ISSUE TITLE
[ALM Accelerator - Feature]: Reduce diffs in solution.xml MissingDependencies

### ISSUE THREAD

**Issue by filcole** [microsoft/coe-starter-kit#3449]
### Is your feature request related to a problem? Please describe.

The MissingDependencies elements in solution.xml can create very large diffs due to version numbers changing between solutions.  It would be great if the noisiness could be reduced by separating out the version numbers for dependent solutions or packages.

### Describe the solution you'd like

I have created a PowerShell script that can be run in a solution folder that aims to remove the diffs by separating out the solution and package references to SolutionRef and PackageRef elements.  See https://github.com/filcole/SolutionRefs

The idea of the script is to be run 
1) immediately after an unpack, so that the diffs are minimised, 
2) immediately before a pack, with the `-restore` flag, to recreate the original solution.xml

We know that the solution.xml format is liable to change, but in it's current format this is one approach to reducing the diffs.

I wonder if this is of interest for inclusion into the ALM Accelerator?

### Describe alternatives you've considered

Removing MissingDependencies completely.  This is a *very* bad idea!

### Additional context?

This has been discussed on the Power Platform Level Up discord channel.  It might be a very bad idea, but it's currently scratching my itch!

**Comment by sdhsynsci** [comment]
"Removing MissingDependencies completely. This is a very bad idea!" unfortunately we frequently do this entirely or for a specific dependency so that we can get a build after a merge.

**Comment by sdhsynsci** [comment]
"Removing MissingDependencies completely. This is a very bad idea!" unfortunately we frequently do this entirely or for a specific dependency so that we can get a build after a merge.

**Comment by mikefactorial** [comment]
@filcole starting to think you should create your own ALM Accelerator pipeline hook repo simiilar to what we're looking to curate here https://github.com/microsoft/coe-alm-accelerator-templates/tree/main/Pipelines/Templates/Hooks/CustomTemplates. Unfortunately, we can only include hook templates in our repo that are endorsed by our team and the product team in general. In this case, similar to the previous PR, we've been advised by the product team not to poke at the unpacked xml files in a solution so we won't be able to incorporate this despite its usefulness and effectiveness it could cause future issues as the platform changes.

**Comment by mikefactorial** [comment]
Please keep bringing these up here though for general awareness as you solve the types of issues. Appreciate the collaboration!

**Comment by filcole** [comment]
Thanks for reviewing @mikefactorial. I expected your answer, because altering the solution.xml isn't supported, so no problems.  Hopefully it's raised awareness of the issue, and one potential way to improve the XML.
