### ISSUE TITLE
[CoE Starter Kit - BUG] Column admin_recordguidasstring in Table Power Platform User contains blank values

### ISSUE THREAD

**Issue by larhem** [microsoft/coe-starter-kit#3451]
### Describe the issue

Hi,

We have run the "CLEANUP - Admin | Sync Template v3 (Delete Bad Data)" as stated in issue #3320 but are still facing issues after upgrading to the August 2022 release.

Power Bi report refresh is failing because of this error:
Column '<ccon>admin_recordguidasstring</ccon>' in Table '<ccon>Power Platform User</ccon>' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. Table: Power Platform User.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CoE Starter Kit August 2022

### What app or flow are you having the issue with?

All

**Comment by manuelap-msft** [comment]
Hello,

we had an issue with the Power BI dashboard that we addressed in a hot fix last week, can you try the new dashboards here which should no longer present this issue:
https://github.com/microsoft/coe-starter-kit/tree/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit

**Comment by larhem** [comment]
Hi,

It looks like its the "[PowerPlatformGovernance_CoEDashboard_202208.pbit"" report that is updated? But we are having problems with "Production_CoEDashboard_August2022.pbit"

**Comment by manuelap-msft** [comment]
This one has been updated too - another user with a similar issue just let us know the new dashboard worked for them (#3456). 

If it doesn't work, we can look into further, but can you please try the latest version?

**Comment by larhem** [comment]
Thanks. We have updated now and i think it solved the issue.

**Comment by manuelap-msft** [comment]
Great, thank you! If you no longer get an issue on the initial Load, the issue should be solved. I'll close the issue now, but if you experience any further issues please do let us know!

Thank you for using the CoE starter kit,
Manuela
