### ISSUE TITLE
[ALM Accelerator - BUG]: CoE CLI install - importpipelinerepo.ps1 is not recognised as the name of a script file.

### ISSUE THREAD

**Issue by piyushpaliwal** [microsoft/coe-starter-kit#3452]
### Describe the issue

Trying to install ALM Accelerator using the `CoE CLI` installer. I was able to successfully generate the `quickstart.json` file, however upon trying to run install, it throws an error while importing the templates repository with the following error

`info: Error message: The argument './src/powershell/importpipelinerepo.ps1' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

### Expected Behavior

Pipeline templates repository should be properly setup in ADO project.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

coe 0.0.1

### Steps To Reproduce

1. Install CoE CLI by following the official documentation here https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/install and choosing Local Install method
2. Generate `quickstart.json` file and install as described https://docs.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/overview#quick-start

**Comment by mikefactorial** [comment]
@piyushpaliwal there have been a couple of changes recently to the coe-cli that haven't yet been reflected in the documentation. 
1. PowerShell Core is a prerequisite for the latest updates to the coe-cli (https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.2) 
2. Git CLI is a prerequisite for the latest updates to the coe-cli (https://git-scm.com/downloads)
3. Make sure you have the latest version which includes the file referenced in the error here https://github.com/microsoft/coe-starter-kit/tree/main/coe-cli/src/powershell.
4. When running the coe-cli install command ensure that the current working directory is the coe-cli folder.

**Comment by piyushpaliwal** [comment]
Thanks @mikefactorial for the inputs; I had all of the things checked.

The only thing that was going wrong was I wasn't running the `coe` commands from inside the `coe-cli` folder.

All is good for now. I'll keep pushing through and may have some more questions.

**Comment by mikefactorial** [comment]
@piyushpaliwal thanks for the update. Want to draw your attention to an issue that has cropped up as a result of new build tools being released on Friday. You may face the same issue after install. We are working on a fix for this as we speak. https://github.com/microsoft/coe-starter-kit/issues/3450

**Comment by mikefactorial** [comment]
Oh, that was opened by you. Didn't make the connection :)
