### ISSUE TITLE
COE environment privilege

### ISSUE THREAD

**Issue by Nfaly-kaba** [microsoft/coe-starter-kit#3453]
### Describe the issue

I've configured the Centre of excellence and all is working fine. As our tenant is composed of multiple entities with corresponding environment, where Apps, Flows, datasets... are stored. We would like to provide COE access to users, but we would like them to be able to access only specific environment. 

### Expected Behavior

Providing access to Centre of excellence to user, however, we only want them to be able to manage Apps, Flows and dataset for a defined set of environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Environment

**Comment by manuelap-msft** [comment]
Hello,

the CoE starter kit gathers meta-data about your tenants Power Platform inventory in a single  Dataverse instance, as such out of the box there's no option to give user only partial access to the data. 

Here's a couple of things you can consider that we've seen other customers do:

1. If you only want share the Power BI dashboard, you could create filtered dashboards that only show the environments you want to share and then share those with your users - so publish multiple versions of the dashboard, each one filtered to the business area you want to share it with. 
2. We have seen customers who are very decentralized where each business unit operates mostly independently set up the kit multiple times - once per business area, the setup is performed by an Environment Admin who has access to all their business areas environments and thus the kit only gathers inventory information of environments they have access to. This works well for a very decentralized approach. 
3. You could look at setting up Business Units in Dataverse and potentially associating them with an Azure AD group https://docs.microsoft.com/en-us/power-platform/admin/wp-security-cds but you would have to create some logic to assign the records in Dataverse to a business unit. So today, info about a canvas app is stored as a record in the PowerApps app table - that record is owned by the admin who set up the kit. How do you determine the logic to have that record owned by the business area you want etc... 

Hope that helps give you some ideas,
Manuela
