### ISSUE TITLE
[CoE Starter Kit - QUESTION] I would like to know where the information for the audit logs is collected from

### ISSUE THREAD

**Issue by GaelCasOuv** [microsoft/coe-starter-kit#3459]
### What is your question?

I would like to know where the information for the audit logs is collected from and how it is done.

I realized that the dashboard is not showing when some apps are launched, I did a test launching the apps and then running the audit logs flows and the "last launched" info doesn't appear in the dashboard for these apps (it appears for others). 

Thank you in advance

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

July 2022

**Comment by manuelap-msft** [comment]
Audit Log is collected via the Office 365 Management API from the Microsoft Purview Audit Log, learn more:
https://docs.microsoft.com/en-us/office/office-365-management-api/
https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-basic-audit?view=o365-worldwide

Power Apps launches take up to 24 hours to reflect in the Microsoft Purview Audit Log, and then then we collect audit log events on a daily basis so you won't instantly see app launches reflected in the dashboard.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
