### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power BI dashboard fails to load

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#3467]
### What is your question?

<img width="561" alt="Screenshot 2022-08-15 114359" src="https://user-images.githubusercontent.com/100535041/184938348-328e5de8-0089-48fa-b0d9-93493517b11d.png">

Hi team, 

We're having some issues deploying the PowerBI dashboard. The CoE Service Account do have all the per user license and also E5 license and have the Power Platform Admin security role. We also have attached https:// followed by our environment org url. Could anyone help out with this issue above. Thanks

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

Production PowerBI Dashboard

**Comment by manuelap-msft** [comment]
We had a bug in our dashboard due to a new column we introduced on all tables in the data model, and released a hotfix to the dashboard last week. You can download the latest version here
https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Production_CoEDashboard_August2022.pbit

Please let us know if that works - if you see the same error still, can you please scroll down in this Refresh window to see what "other queries" are blocking it. You should find one table with a better error message.

**Comment by iamjina** [comment]
Hey! 

Thanks for answering. We currently have the July version of CoE so when we were planning on deploying the July version. For the July PowerBI pbit file, do we also have a bug that's causing this issue?

**Comment by manuelap-msft** [comment]
If you are on July, can you please scroll down in this Refresh window to see what "other queries" are blocking it. You should find one table with a better error message.

**Comment by iamjina** [comment]
![image](https://user-images.githubusercontent.com/100535041/185207798-8727b9ae-9f23-4a5a-9f3c-ba80bd61dc45.png)

Hi, 

After we scroll down, this is what we receive: Business Process Flows: The key didn't match any rows in the table.

**Comment by Jenefer-Monroe** [comment]
Please go to your CoE environment > Power Platform Admin View app > view the Business Process Flows. Is there data present? 
![image](https://user-images.githubusercontent.com/89584709/185506905-0762898f-dab2-4aaf-99a7-fe05cb401538.png)

**Comment by iamjina** [comment]
Hey Jenefer, 

I do not see Business Process Flows under my Power Platform Admin View. Has this got updated within the August version? We currently have July version of CoE

**Comment by Jenefer-Monroe** [comment]
That was shipped with the July version. Please go see
1. Do you have unmanaged layers on the app? If so please remove them. 
![image](https://user-images.githubusercontent.com/89584709/185942776-36b4c7aa-7759-458b-9cb2-368d2a164527.png)

1. Do you have data in the Business Process Flows table? 
![image](https://user-images.githubusercontent.com/89584709/185943380-b714218f-eae2-4576-8750-886c4e4c1bc0.png)

1. Do you have the Business Process Flow sync flow turned on and running?
![image](https://user-images.githubusercontent.com/89584709/185943633-8befb4d4-7e1f-4141-8dbb-9f584cd53c49.png)

**Comment by iamjina** [comment]
Hey team,

We were able to retrieve PowerBI dashboard and seems the data is also accurate. Thanks for all the help!

**Comment by Jenefer-Monroe** [comment]
good to hear. Thanks for using CoE
