### ISSUE TITLE
[CoE Starter Kit - BUG] HELPER-ObjectOperations.Run failed error

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#3468]
### Describe the issue

Hello CoE Team,
I hope all is well. 
I'm trying to use the Flow "Set Flow Permissions", but receiving an error when I'm trying to get permissions to any Flow in our tenancy. 
The errors is **HELPER-ObjectOperations.Run failed: The method 'Run' has an invalid value for parameter 'text'**

![Error with Flow](https://user-images.githubusercontent.com/68440710/185016153-5fab98c9-a959-45f6-b883-bb0e1167b94e.png)

Any idea why this is happening please?
Thanks very much,
Garry

### Expected Behavior

When using the Flow "Set Flow Permissions"
I should be able to get access to the Flow as a Viewer/Editor.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Set Flow Permissions

### Steps To Reproduce

1. Open the Set Flow Permissions Flow
2. Select Environment tab
3. Search for name of Flow
4. Check the checkbox next to the Flow display name
5. Click Add Permissions
6. Add name of user needing permission
7. In Selected User Role, select Editor
8. Click Save

**Comment by Jenefer-Monroe** [comment]
If your CoE is installed in D4T, then there is an active bug local fixed for Sept, please see https://github.com/microsoft/coe-starter-kit/issues/3103

If you are not installed in D4T, we did fix something in the helper for this recently, I cant remember if it was for July or August though. So you will need to upgrade and make sure you dont have unmanaged layers on the helpers in Core. 

Thanks for using CoE!

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe,
Thanks for the quick reply. I'm using Dataverse rather than D4T. I imported version 3.41. The app and the helper flows do not have any unmanaged layers on them. 
Yet I'm still getting the same error.
Any thoughts please?
Thanks very much,
Garry

**Comment by Jenefer-Monroe** [comment]
Interesting, I dont repro so lets look at the flows: 

Go to this flow: HELPER - ObjectOperations, open the failure (assuming its failing) and see what the failure is, and what values are sent in for the parameters: 
![image](https://user-images.githubusercontent.com/89584709/185201768-416ac764-fdd4-4a18-9b9e-aa7cad90fc74.png)

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe,
Thanks for the reply. 
I just checked that Flow and it doesn't have any runs.
Sorry.

![COE Flow](https://user-images.githubusercontent.com/68440710/185358029-88166a00-efd8-44cc-b404-eb3077fb8550.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
