### ISSUE TITLE
[ALM Accelerator - Feature]: Automatically generate change reports of resources with a release

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#3470]
### Is your feature request related to a problem? Please describe.

Customers have a hard time understanding what changes from release to release with all the components in the kit, and especially if they're managing customizations and extensions, or working on testing what has changed before rolling it out into their production instance, it can be difficult to understand what exactly has changed. The release notes we have are focused on our features and issues, but don't mention the exact tables, flows, and apps that were changed.

### Describe the solution you'd like

We'd like an automatically generated report of everything that has changed between main releases.

**Comment by mikefactorial** [comment]
@manuela-msft can we close this for now based on the work you are doing in the setup / upgrade wizard?
