### ISSUE TITLE
In COE Starter kit,(Child) Sync Audit logs flow is considering only App Usage and it is not having Flow usage. Instead of Flow usage it is having Flow Deleted condition. What opreation type to consider for getting Flow Run date as like power platform analytics for Power Automate

### ISSUE THREAD

**Issue by VanamaLaxmiChaithanya** [microsoft/coe-starter-kit#3474]
### Describe the issue

In COE Starter kit,(Child) Sync Audit logs flow is considering only App Usage and it is not having Flow usage. Instead of Flow usage it is having Flow Deleted condition. Please let us know if we want to implement it from my end, which Operation type we can use to get Flow Usage using Sync Audit Logs Flow.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Latest

### What app or flow are you having the issue with?

Sync Audit Logs

**Comment by Jenefer-Monroe** [comment]
The CoE Starter Kit gets Audit Log information from the [Microsoft 365 Purview Audit Log](https://docs.microsoft.com/power-platform/admin/logging-powerapps) and only canvas app launches are logged there. We do not currently have a feature to monitor model driven app launches, cloud flow runs, etc. 

Some of this type of information is available if you set up [Application Insights](https://docs.microsoft.com/power-platform/admin/analyze-telemetry)

And some will be exposed in the Data Lake implementation of the kit upon which we are currently iterating.  Here are some starter links if you are interested in exploring:
https://docs.microsoft.com/power-platform/admin/self-service-analytics
https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by VanamaLaxmiChaithanya** [comment]
Thanks for the response. What is the operation type to get the flow run date in (Child) Admin |Sync Audit logs flow. I can see one operation as 'Edit Flow' but it is different from the flow run date.

**Comment by VanamaLaxmiChaithanya** [comment]
Can we have a quick call. Please let me know your available time.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
