### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Solutions) null ref exception on Select Inventory Workflows action

### ISSUE THREAD

**Issue by js9331** [microsoft/coe-starter-kit#3478]
### Describe the issue

Getting an error on Admin | Sync Template v3 (Solutions) null ref exception on Select Inventory Workflows action
![image](https://user-images.githubusercontent.com/35241782/185448818-b3d49ea4-cfcc-4fef-8522-1934c6d398d4.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### Steps To Reproduce

Happens when running flow

**Comment by Jenefer-Monroe** [comment]
Sorry I dont follow this. Are you in the Power Platform Admin view? What do you mean by select?

**Comment by js9331** [comment]
Apologies, should have included another screenshot on that - I was referring to the "Select Inventory Workflows" action in the Admin | Sync Template v3 (Solutions) flow. Here's a screenshot of the error - it appears to be either a null reference exception or schema validation error?
![image](https://user-images.githubusercontent.com/35241782/185454978-82846237-28e2-45da-a124-8407b92af053.png)

**Comment by Jenefer-Monroe** [comment]
Ok thank you for clarifying! That should indeed never be null, so lets see how a null ended up in there. 
Can you please go up to these Select statements above and see what their return is? 

- Select BPF IDs from Inventory
- Select Flow IDs from Inventory

**Comment by js9331** [comment]
sorry for the delay - crazy meetings today 🤪
here's BPF ID:
![image](https://user-images.githubusercontent.com/35241782/185476123-ce781c88-c972-4a84-a61e-0a38e66431a2.png)

and here's Flow ID:
![image](https://user-images.githubusercontent.com/35241782/185476222-65dc1404-6f57-418d-9725-c6b89281164d.png)

(both images are from the same flow run instance that had the error posted above)

**Comment by Jenefer-Monroe** [comment]
The table we are pulling from here is a hidden one so this might be an adventure to investigate. Let me see what I can figure out on my side to make this easier.

**Comment by Jenefer-Monroe** [comment]
Are you familiar with how to import flows? This article shows how in the "Importing the Flow" section. But if you struggle please let me know. 
This flow can be imported into your CoE environment, and when run will send you an email with the list of solution - BPF - WorkflowID combo
[solutionbpfbug_20220818215134.zip](https://github.com/microsoft/coe-starter-kit/files/9377937/solutionbpfbug_20220818215134.zip)

Please look through to see if there is some pattern. Are all the workflowids null? Just some small subset? All with the same solution? etc

**Comment by Jenefer-Monroe** [comment]
Here is what the mail will look like 
![image](https://user-images.githubusercontent.com/89584709/185503464-06f2f402-98b1-4510-b764-f828e9776896.png)

**Comment by js9331** [comment]
Hi! I was able to run that flow this morning and get the list. Using the list and the details of the flow you gave me, I was able to query for all the BPFs in my current CoE dataset for the affected ones, and I think I see a commonality: All of these are BPFs where the process is in a solution, but the related BPF table is not in the same solution with the process - could that be the cause?
![image](https://user-images.githubusercontent.com/35241782/185656237-af33d9f6-61ff-4741-87cc-0a9ab7d7b7f6.png)

**Comment by Jenefer-Monroe** [comment]
Thank you for exploring. i cant get this to repro though. Can you please try a full inventory run to see if this column gets filled? 
[full inventory run](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by xinn-wang** [comment]
Hi@Jenefer-Monroe,

I recently installed the CoE Starter kit and run into the same issue as the topic creator, how did you figured out the previous problem? can you help me out?
<img width="658" alt="Screenshot 2023-06-15 084529" src="https://github.com/microsoft/coe-starter-kit/assets/71020538/cb4f8ae9-fe7a-4a54-b8cc-7cdf843833dd">
