### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to enter the Power BI URL when setting up the dashboard

### ISSUE THREAD

**Issue by krishnapowerBI2** [microsoft/coe-starter-kit#3479]
### Describe the issue

I am trying to install Power BI Dasboard in COE Starter Kit.

<img width="982" alt="Power_Dashboard_error" src="https://user-images.githubusercontent.com/111531010/185467249-271bb708-3054-4dbc-ba2f-6807c8cc7a62.PNG">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

n/a

### What app or flow are you having the issue with?

n/a

**Comment by manuelap-msft** [comment]
You've entered the URL incorrectly. It needs to be entered with http**s**:// (note the s!) and not http://

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by krishnapowerBI2** [comment]
still i am not able to connect with https url.
