### ISSUE TITLE
[ALM Accelerator - QUESTION] Automaton Testing -Trigger from ALM accelerator

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#3480]
### What is your question?

We are planning to implement Automaton Testing by using Selenium tool . Can you please Provide high-level overview of how can we trigger automation testing in ALM Accelerator ?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Apr 2022

**Comment by mikefactorial** [comment]
@linujohn22 thanks for the question. If your solutions contain Canvas Studio tests our pipelines will execute the tests assuming you have configured them to do so.
However, automated tests outside of Canvas Studio testing will require you to create pipeline templates / pipelines to run the specific tests. 

The recommended method for extending the ALM Accelerator pipelines is to use the hooks we distribute with the pipelines. There's documentation on how to use the hooks here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorforpowerplatform-hook-extensions

Additionally, if you plan to run your automated tests on Pull Request creation you can do so using branch policies in Azure devops without the need to customize hooks. We use branch policies in our default setup to run our validation pipeline and to run solution checker against the solution.

**Comment by mikefactorial** [comment]
Closing out as there's no further action required.
