### ISSUE TITLE
Upgrading to newer version

### ISSUE THREAD

**Issue by KishoreJagan83** [microsoft/coe-starter-kit#3481]
Hello,

In our Org we have installed the May release version of CoE Starter Kit , in that we have done a few customization.
All Customizations we created using Patch , now all the customization is deployed to Prod.

Now if we want to upgrade to Aug version  in Dev region ,  I select the upgrade option it will update the latest changes in the OOB Apps/ flows. But how we upgrade the latest updates to our customized Apps / flows.

Kindly share the procedure how to merge the latest updates to our custom app.

**Comment by manuelap-msft** [comment]
Here is our guidance for updating and extending the CoE kit:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/after-setup
https://docs.microsoft.com/en-us/power-platform/guidance/coe/modify-components

For canvas apps and cloud flows, merge behaviour is not supported by the Power Platform.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
