### ISSUE TITLE
[CoE Starter Kit - BUG] Maker manager information not populated anymore

### ISSUE THREAD

**Issue by DDog80sRocked** [microsoft/coe-starter-kit#3484]
### Describe the issue

As we're testing orphaned flows/apps, the managers are not getting the emails to disposition them.  See screenshot showing maker with blank manager info.  I reviewed the CoE flow named 'HELPER - Maker Check' and found that both the 'Update Maker' and 'Add Maker' dataverse action don't have values.  Screenshot attached.  Is this the cause of managers not showing up on the maker info page?

### Expected Behavior

Manager information is correctly populated for governance actions to function

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

HELPER - Maker Check

### Steps To Reproduce

1. Open power platform admin view
2. Select Makers on the left
3. Select a new user
4. Confirm manager fields are empty

### Anything else?

![2022-08-19 11_57_24-Power Apps _ Solutions - Default Solution — Mozilla Firefox (Private Browsing)](https://user-images.githubusercontent.com/42620867/185671397-8d20ad50-fc4b-46fa-a846-93b67946a1ea.png)
![image](https://user-images.githubusercontent.com/42620867/185671860-42f39e9d-6c36-4b0b-b616-9e1d68f05db6.png)

**Comment by Jenefer-Monroe** [comment]
We don't add the manager here, we add it in this flow: CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

**Comment by DDog80sRocked** [comment]
Thanks for the info.  Manually running that seems to work.  Sorry.

**Comment by Jenefer-Monroe** [comment]
No need to apologize! This is a very complex system and we are here to help!
