### ISSUE TITLE
[ALM Accelerator - QUESTION] export_solution_to_git failing on "Verify Default Environment Variables are Set"

### ISSUE THREAD

**Issue by concoursdude** [microsoft/coe-starter-kit#3485]
### What is your question?

Manually installing the ALM accelerator for the first time. Things are going fairly smooth, but I'm hung up on a step when committing a solution. The "Verify Default Environment Variables are Set" step seems to be receiving null values into a PowerShell script, but I have no idea how to troubleshoot this. Can someone help me figure this out? 

![image](https://user-images.githubusercontent.com/51216063/185673428-b83e90e5-a3f9-4e25-973a-963a211bf1a3.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220726.1

**Comment by mikefactorial** [comment]
@concoursdude thanks for reporting this. Looks like you may have a more recent version of the pipelines post August release. This is a known issue with our documentation on the manual setup of the pipelines which instructs you to import our pipelin repository. The side effect of this is you will get changes made since the previous release in your pipelines. To remedy this please get the latest pipelines from the release here https://github.com/microsoft/coe-alm-accelerator-templates/archive/refs/tags/CenterofExcellenceALMAccelerator-August2022-HF1.zip

We have an issue open to fix the instructions in the docs in the upcoming release.

**Comment by concoursdude** [comment]
> @concoursdude thanks for reporting this. Looks like you may have a more recent version of the pipelines post August release. This is a known issue with our documentation on the manual setup of the pipelines which instructs you to import our pipelin repository. The side effect of this is you will get changes made since the previous release in your pipelines. To remedy this please get the latest pipelines from the release here https://github.com/microsoft/coe-alm-accelerator-templates/archive/refs/tags/CenterofExcellenceALMAccelerator-August2022-HF1.zip
> 
> We have an issue open to fix the instructions in the docs in the upcoming release.

Thanks for the quick reply. Any changes to the PS scripts found in ..HF1\PowerShell that require replacement of any of those scripts from the clone, or is it just the YAMLs in the Pipelines folder that need to be replaced? I'm failing on a different step now (Disable / Enable Solution Flows) related to $(outActivateFlows).

**Comment by mikefactorial** [comment]
@concoursdude you should be able to safely overwrite all of the files in the current repo with the files from the release zip. Can you include the error you are seeing in the Disable / Enable Solution Flows task?

**Comment by concoursdude** [comment]
> @concoursdude you should be able to safely overwrite all of the files in the current repo with the files from the release zip. Can you include the error you are seeing in the Disable / Enable Solution Flows task?

You can disregard, @mikefactorial. It was indeed a discrepancy between script versions. I had only overwritten the YAMLs with the ones you sent me. On overwriting the PowerShell directory, the job proceeded as expected. Thanks again for your assist!

**Comment by mikefactorial** [comment]
@concoursdude good to hear. Thanks for the update. Closing this out for now.
