### ISSUE TITLE
[CoE Starter Kit - BUG] Solution Overview is empty - is system still broken? 

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#3487]
### Describe the issue

The **solution overview** is empty in CoE Power BI dashboard:
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/15800069/185741691-ddf4d886-48c7-481e-925f-ffe5cfa3efda.png">

However, the **solution inventory** have already some solutions:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/15800069/185741742-e46c86d0-b0fa-42e4-9e45-6b6c5868fde4.png">

### Expected Behavior

I guess, I should see some of my environments & solution makers in the **solution overview**

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2022

### What app or flow are you having the issue with?

Production_CoEDashboard_August2022.pbit

**Comment by Jenefer-Monroe** [comment]
Clear that isSystem filter, see if that fixes it.

**Comment by megel** [comment]
@Jenefer-Monroe removing this filter solved that issue:
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/15800069/185865532-09b147df-5b35-4c61-8653-22a1618f585b.png">

I guess, the filter default value is wrong.

**Comment by Jenefer-Monroe** [comment]
Oh actually I just remembered we sent that fix in an update to August. The fix was originally targetted for Sept and then we had to reship the PBIT files for another issue so I just shipped it.

I think if you download the latest PBIT, which we put in the August folder after we first released, you would not repro anymore. Can you please test that for me?

**Comment by megel** [comment]
@Jenefer-Monroe, I can confirm, the current version in main
https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Production_CoEDashboard_August2022.pbit 
is working correctly.

**Comment by Jenefer-Monroe** [comment]
Thank you for confirming!
