### ISSUE TITLE
Fails to post adaptive card for Teams Environment Business Justification

### ISSUE THREAD

**Issue by bhavikj65** [microsoft/coe-starter-kit#3491]
We are getting below error on the "Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created" flow for "Post an Adaptive Card to a Teams user and wait for a response" action.

![image](https://user-images.githubusercontent.com/105588534/185976866-7b53333b-d80e-459c-95b1-261ecb300273.png)

I've verified that the Power Automate bot is not blocked in Teams, below is a screenshot confirming the same:

![image](https://user-images.githubusercontent.com/105588534/185976540-718851cb-48bf-4791-8d99-29fa042ee1bf.png)

I've created a test flow using which I could post message to a team channel using Flow bot, however for some reason it fails to post message or adaptive card to a user.

**Comment by bhavikj65** [comment]
It seems there was some glitch with Teams, after blocking the bot and then unblocking helped fix this issue.

**Comment by Jenefer-Monroe** [comment]
Glad this was resolved, seems like some intermittent product issue was impacting you and is now addressed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
