### ISSUE TITLE
[ALM Accelerator - Feature]: Add deployment pipelines for new CoE Starter Kit solution admintaskanalysis_core (display name Power Platform Administration Planning)

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#3492]
### Is your feature request related to a problem? Please describe.

We're looking to include a new solution in the CoE Starter Kit release, starting September, and need help getting the deployment and release pipelines configured to include the following solution:
**admintaskanalysis_core** (display name Power Platform Administration Planning)

### Describe the solution you'd like

Export to Git worked and the solution has been exported (but not yet merged to main)

**Comment by mikefactorial** [comment]
Closing out this has been completed :)
