### ISSUE TITLE
[CoE Starter Kit - QUESTION] Download link in Documentation is stale

### ISSUE THREAD

**Issue by johnravas** [microsoft/coe-starter-kit#3493]
### What is your question?

I am in the process of doing a fresh install of the core components of the COE Starter kit (v 3.41)  I am running into the exact same issue that was reported in bug #3221
I am attempting to run the Admin | Sync Template v3 CoE Solution Metadata flow.  It is failing with this error:
admin_environment With Id = <environment ID removed> Does Not Exist
In looking at the code, here is where it is failing:
![image](https://user-images.githubusercontent.com/59970962/185984257-b315fc4d-f2d0-4af7-87a9-5a998992cc2a.png)

Based on what was indicated in the bug report, that action in the flow was removed.  However, my version is later and it is still there.  I downloaded the latest solution this morning.  Please advise.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

**Comment by Jenefer-Monroe** [comment]
Did you start from a new environment? It could be that you have some old version of the flow sitting around if you are re-using the envt

**Comment by johnravas** [comment]
Hi Jenefer - yes a brand new environment.  Just imported the latest solution for the core solution today.

**Comment by Jenefer-Monroe** [comment]
And what link are you using to get the latest version of core?

**Comment by johnravas** [comment]
I used the Download link under the overview column on this page - https://docs.microsoft.com/en-us/power-platform/guidance/coe/starter-kit This downloaded the CoE starter kit.  

However, I just cross checked what I installed and it is indeed 3.39!!! I have 3.41, so I will update this solution.  I expect that this will overwrite the old version with the new one allowing to move forward.  I will circle back and confirm.

Sorry for the fire drill.  I downloaded the latest, but it appears that I installed from an earlier download

**Comment by Jenefer-Monroe** [comment]
oh thank you for letting us know this link is bad! I'll use this bug to track fixing that in the documentation.

**Comment by johnravas** [comment]
Upgraded the solution and the flow in question ran fine.  Picking up and continuing with the install.  Thanks for the assistance,

**Comment by Jenefer-Monroe** [comment]
you are welcome, thanks for using CoE!
