### ISSUE TITLE
Store Flow Owner versus Creator (or both)

### ISSUE THREAD

**Issue by Yocomd** [microsoft/coe-starter-kit#3500]
Currently the "Admin | Sync Template v3 (Flows)" flow only stores creator of the flow as the Maker.  For flows within solutions, however, it is possible to change the owner of the flow.  It would be very helpful to have the new owner stored in the CoE.  We are starting an effort to notify flow owners and their managers of flows that are owned by disabled users (orphaned) or that are not owned by "service accounts".  Right now, we have no way of knowing whether flow owners have been updated since it's not updated in the CoE - unless we do it manually.

**Comment by Yocomd** [comment]
Closing this in favor of opening with the full new feature template.

**Comment by Jenefer-Monroe** [comment]
as far as I know, this new owner is not exposed to us programmatically via the connectors. https://github.com/microsoft/coe-starter-kit/issues/3052

If you know a workaround for this please do let us know.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
