### ISSUE TITLE
[ALM Accelerator - BUG]: Pipeline repository is created with `master` instead of `main` branch

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#3502]
### Describe the issue

A newly created `pipeline` repository has the **`master`** branch instead of the `main` branch:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/15800069/186107387-826d2870-952e-4964-9b52-767c1c409c63.png">

This is because, this option is active in Azure DevOps:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/15800069/186105159-fa11b9f4-1c4b-45f6-b32e-38ee4232dce5.png">

In conclusion, you get in AA4PP this error during **Commit** solution:

`Error running pipeline: CustomAzureDevOps.RunPipeline failed: {"$id":"1","innerException":null,"message":"Unable to resolve the reference 'refs/heads/main' to a specific version. Verify the reference exists in the source repository.","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException","errorCode":0,"eventId":3000}`

Created solution-branch pipelines references also `main` branch:
![image](https://user-images.githubusercontent.com/15800069/186107244-da3fc53c-a220-4c83-9eb6-a92046deb6d3.png)

This issue is related to question #3314 

### Expected Behavior

A newly created `pipeline` repository from `CoE CLI` / AA4PP have uses the `main`, which is compatible to the pipeline templates.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

August 2022

### Steps To Reproduce

1. Create an Azure DevOps organization & project
2. Change the pipeline setting to:
   <img width="398" alt="image" src="https://user-images.githubusercontent.com/15800069/186105159-fa11b9f4-1c4b-45f6-b32e-38ee4232dce5.png">
3. Use `CoE CLI` to setup Azure DevOps and the pipeline repository

### Anything else?

The workaround is to rename the `master`branch into `main` branch in pipeline respository.

**Comment by mikefactorial** [comment]
@megel thanks for sharing this. Interesting, we should be creating a main branch and attempting to delete the master branch in the import process. Can you check the combined.log that got generated in the root of the coe-cli folder for something similar to the following? It's possible something failed in the script.

Switched to a new branch 'CenterofExcellenceALMAccelerator-August2022-HF1'\nCloning into 'alm%20pipelines'...\nwarning: You appear to have cloned an empty repository.\nTo https://dev.azure.com/org/alm%20pipelines/_git/alm%20pipelines\n * [new branch]      master -> master\nSwitched to a new branch 'main'\nTo https://dev.azure.com/org/alm%20pipelines/_git/alm%20pipelines\n * [new branch]      main -> main\nTo https://dev.azure.com/pplatform/alm%20pipelines/_git/alm%20pipelines\n - [deleted]         master\n","timestamp":"2022-08-23 11:46:44 AM -0400"}

**Comment by megel** [comment]
@mikefactorial I found the old information in `combined.log`, but there wasn't any info's about creating a new branch:

```json
{"level":"info","message":"Error message: Cloning into 'coe-alm-accelerator-templates'...\nSwitched to a new branch 'CenterofExcellenceALMAccelerator-August2022-HF1'\nCloning into 'pipelines'...\nEverything up-to-date\n","timestamp":"2022-08-19 05:42:14 PM +0200"}
{"level":"info","message":"Pipeline repository pipelines imported","timestamp":"2022-08-19 05:42:14 PM +0200"}

```

**Comment by megel** [comment]
I have checked with current CoE CLI with a new created Azure DevOps Organization & Project (master is the default repository branch). 

The output during installation:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/15800069/187372113-aeb4e5d4-e5ac-44bf-92de-00a958a59903.png">

The result in my pipeline repository looks good:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/15800069/187372493-179376c1-a709-45a5-a540-7e01d26c6368.png">
