### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Business Process Flows) failed on Orphan check condition

### ISSUE THREAD

**Issue by bhavikj65** [microsoft/coe-starter-kit#3504]
### Describe the issue

In Admin | Sync Template v3 (Business Process Flows) there is a condition "Check if Orphan - New" as below:

![image](https://user-images.githubusercontent.com/105588534/186182019-6c8cc1f2-e02a-4266-bf62-b6ba5a806c7b.png)

This condition checks if ('Maker_Check_-_New')?['userisorphan'] is equal to true, in one of the runs I observed that it returned true however it still ran the actions in the no branch as shown in below screenshot:

![image](https://user-images.githubusercontent.com/105588534/186185304-c9a37146-84de-4d23-aa96-a50810247957.png)

### Expected Behavior

Instead of running the actions under the "If no" branch, it should have run the action "Create BPF (Orphaned)" under the "If yes" branch. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Business Process Flows)

**Comment by Jenefer-Monroe** [comment]
Hello, thanks for posting. We have this one local fixed for Sept. Please see https://github.com/microsoft/coe-starter-kit/issues/3375

I'll go ahead and closet his one as a dupe as a result. 
Thanks for using CoE!
