### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by gamgoumy** [microsoft/coe-starter-kit#3509]
### Describe the issue

In the same tenant, CoE has been installed in two difference environments. Everything is the same in the two environments in the Power Platform Admin View except for the number Flows. One environment has an additional 397 Flows. These Flows are all in the default environment but when I actually go to the default solution in the default environment, I can only see two Flows

### Expected Behavior

I expect to see only 2 Flows for the default environment in the Power Platform Admin View for both of the CoE enviornments we have created. Instead one shows 58 Flows and the other shows 455 Flows. I expect at least those two numbers to match.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

https://ppeuoh-coe-01.crm11.dynamics.com/
Power Platform Admin View
Flows
Filter to show default environment Flows
Check number of Flows

https://ppeuoh-coe-02.crm11.dynamics.com/
Power Platform Admin View
Flows
Filter to show default environment Flows
Check number of Flows

make.powerapps.com
default environment
go to the default solution
Check number of Flows

All Flow numbers will be different

**Comment by Jenefer-Monroe** [comment]
Is the identity that was used to set up the two environments the same identity?

**Comment by gamgoumy** [comment]
> Is the identity that was used to set up the two environments the same identity?

Yes

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
