### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Dashboard - SharePoint Integration creator filter not working?

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#3510]
### Describe the issue

Hi,

When I try to filter for Creator using the PowerBI SharePoint Integration Dashboard I get no results despite the Creator having numerous Flows associated with SPO sites?

![image](https://user-images.githubusercontent.com/48433526/186369402-0b8b5987-5553-4dd4-8e1c-a582fc7bb458.png)

### Expected Behavior

When filtering by Creator I would expect to see all the SharePoint sites that the Owner has flows associated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Power BI Dashboard

**Comment by Jenefer-Monroe** [comment]
We do not have the concept of SharePoint Flows. We only have a concept of SharePoint Apps. 
The product tracks apps as : Canvas, Sharepoint, or Model Drvien in their "Type" field. While the flow does no such demarkation. 
Hope that makes sense.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
