### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by TonyTheSharePointer** [microsoft/coe-starter-kit#3511]
### Describe the issue

Using the Power Platform Admin View model driven app to view all the flows on the tenant - two flows are missing from the list. There could be more, but to date two actual examples were found. Flows have been confirmed to exist by running a PowerShell.

### Expected Behavior

Power Platform Admin View app should display ALL M365 Power Automate flows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2022

### What app or flow are you having the issue with?

Power Platform Admin View App

### Steps To Reproduce

In the CoE Environment under OOTB configuration run the 'Power Platform Admin View' App.
Navigate to 'Flows'. Then click on the 'FlowIDString' column and hit 'Filter By'
Enter GUID of a Flow and hit 'Apply'.
Flow is Not found.

**Comment by Jenefer-Monroe** [comment]
There are limitations in our ability to collect objects so you should not expect to see the exact same set of flows across PowerShell, CoE, Product Admin pages. 

Please see [Inventory and telemetry differences between PowerShell, Power Platform Admin Center, and CoE Starter Kit](https://docs.microsoft.com/power-platform/guidance/coe/limitations#inventory-and-telemetry-differences-between-powershell-power-platform-admin-center-and-coe-starter-kit)

**Comment by TonyTheSharePointer** [comment]
Hello,

The expectation here is not to see the exact same number of flows across platforms.
The expectation is that CoE should have ALL Cloud Flows. And the link you provided clearly confirms that is should.

***@***.***

However that is not the case in our scenario – 2 flows (at least that is what is known to date) have not been found by CoE. So CoE is NOT showing all cloud flows like it is advertised.

Kind regards,
Tony Antanas Macernis.

**Comment by Jenefer-Monroe** [comment]
That section is not correct then. We do not collect all flows. Here is an example limitation. 
https://docs.microsoft.com/power-platform/guidance/coe/limitations#flows-that-are-imported-or-owned-by-a-service-principal

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
