### ISSUE TITLE
[ALM Accelerator - BUG]: Cannot read properties of null (reading id) 

### ISSUE THREAD

**Issue by HymansTesting** [microsoft/coe-starter-kit#3515]
### Describe the issue

During a Commit of a solution the step called "Update the deployment settings" errors with ##[error]PowerShell exited with code '1'. 

### Expected Behavior

To complete without errors or issues.

Solution has been manually exported successfully.

Attempted with two different solutions.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220726.1

### Steps To Reproduce

Commit a solution package

### Anything else?

1.	npm WARN deprecated [querystring@0.2.0](mailto:querystring@0.2.0): The querystring API is considered Legacy. new code should use the URLSearchParams API instead. 
added 850 packages, and audited 851 packages in 58s 
99 packages are looking for funding 
run `npm fund` for details 
3 moderate severity vulnerabilities 
To address all issues (including breaking changes), run: 
npm audit fix --force 
Run `npm audit` for details. 
> [coe@0.0.1](mailto:coe@0.0.1) build 
> tsc 
added 1 package, and audited 3 packages in 461ms 
found 0 vulnerabilities 
Environments: test=[https://hymanscitvalidation.crm11.dynamics.com/,validation=https://hymanscitvalidation.crm11.dynamics.com/,prod=https://hymanscitvalidation.crm11.dynamics.com/](https://hymanscitvalidation.crm11.dynamics.com/,validation=https:/hymanscitvalidation.crm11.dynamics.com/,prod=https:/hymanscitvalidation.crm11.dynamics.com/) 
info: Branch start 
info: Setup branch 
info: Using supplied access token 
info: Pipeline Project: alm-sandbox 
info: Found project Power Platform 
info: Found pipeline project undefined 
info: An error occurred while creating the branch: TypeError: Cannot read properties of null (reading 'id') 
error: Cannot read properties of null (reading 'id') 
Checking for secrets removed 
Checking for secrets removed 
Checking for secrets removed 
##[error]PowerShell exited with code '1'. 
Finishing: Update Deployment Settings

**Comment by mikefactorial** [comment]
@HymansTesting thanks for reporting this we're aware of the issue and are looking into pushing out a fix as soon as possible. Will report back when we have resolved the issue.

**Comment by HymansTesting** [comment]
> @HymansTesting thanks for reporting this we're aware of the issue and are looking into pushing out a fix as soon as possible. Will report back when we have resolved the issue.

Thanks mike, to the rescue again! :)

It was working recently though, was there a new release or something that introduced the bug? Thanks again!

**Comment by mikefactorial** [comment]
@HymansTesting This is a bug that was introduced in our preparations for the September release. We've discussed the issue internally related to how we are distributing the coe-cli as part of our pipelines and are working on a solution to avoid this issue in the future. A fix has been released for the immediate issue and you shouldn't be seeing the failure in your pipelines now. We're hoping to have the long term solution as soon as possible.

**Comment by mikefactorial** [comment]
@HymansTesting We've released a fix for this. There's nothing you need to do take advantage of the fix and everything should work as expected now.

**Comment by mikefactorial** [comment]
We have plans in place to ensure this doesn't happen going forward.

**Comment by gerald560** [comment]
This is showing up again

**Comment by adminatoscoe** [comment]
This error still persists
