### ISSUE TITLE
[CoE Starter Kit - QUESTION] License requirements for using the apps

### ISSUE THREAD

**Issue by melbritins** [microsoft/coe-starter-kit#3517]
### What is your question?

Hello,

We're looking to utilize the environment creation app that comes bundled with the COE starter kit.

Can you please confirm what type pf premium license is required for a user to use Admin and Maker - Environment Request apps.

Assume either a PowerApps per user or per app plan is suitable?

Thanks,

Mel

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Maker - Environment Request

**Comment by Jenefer-Monroe** [comment]
Yes a power apps per user license is required for both apps as they use Dataverse as the backend. 
You can use a [pay-as-you-go](https://docs.microsoft.com/power-platform/admin/pay-as-you-go-overview) or a [per app](https://docs.microsoft.com/power-platform/admin/about-powerapps-perapp) plan instead if you'd like.

**Comment by melbritins** [comment]
Thanks for the prompt reply.

I’ll request a quote for the per app plan as that looks to be the cheaper option.

Regards,

Mel

Melvin Uy
Microsoft 365 Engineer
IT Operations & Security

***@***.***
The Leadenhall Building
122 Leadenhall Street
London, EC3V 4AB

T: +44 (0) 203 857 1007
W: www.britinsurance.com


At Brit we work flexibly - so whilst it works for me to email now, I do not expect a response or action outside of your own working hours.

***@***.***<https://www.britinsurance.com/writingthefuture>

**Comment by bhavikj65** [comment]
This is really bad for enterprises as there are many apps part of CoE kit and it can be really expensive for companies with user base of more than 100K. 

You can't really choose per app or per user licensing plans for these apps, If I think of pay-as-you-go then its even more expensive and it bills if the user has launched the app just once in a month. 

Microsoft needs, to consider this and build solutions which are less expensive at-least for companies who have more than 100K employees.

**Comment by kabirstein** [comment]
I totally agree. When working with clients on COE I advise them to only use the Power BI template, which is invaluable for understanding usage. Then install Governance and Nurture but turn all of the flows in these apps off. Then we use the COE flows and apps as a model (although the apps in the COE are really poor, they do give you some ideas) and write custom apps and flow to meet the clients needs. For instance, we write a flow that sends an email every time a user creates an new app or flow to apprise the creator of the governance policies, adding the Power Platform Admin service account as a Co-User to each Power App and Flow (don't make service account Owner of a flow or that will accumulate too many API requests for that account.)

**Comment by Jenefer-Monroe** [comment]
Sorry to hear you folks find the kit to be insufficient. We are open to suggestions for improvement through this bug list. 
That said the kit is intended to be a starter for organizations, and it will never fit the needs of all orgs, so it sounds like you are doing what you need for your customers.

**Comment by kabirstein** [comment]
While we really appreciate the Microsoft effort in providing the COE Starter Kit, I think the words "Starter Kit" do mean that clients should use it as a starting point and not expect the apps be of a particularly finished quality. I also understand Microsoft writing the COE Starter Kit to use Dataverse, a premium connector, was necessary because of the PA metadata being in Dataverse, but MS surely can't expect a company with many thousands of users to pay $5 a month per user simply to use the COE. And it's not really necessary. For example, writing a Power App that uses SharePoint to allow Makers to request an Environment (the original ask in this issue thread) is a fairly simple task.

**Comment by Jenefer-Monroe** [comment]
You are most welcome to develop a platform like this on SP for your needs.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
