### ISSUE TITLE
[ALM Accelerator - BUG]: Error at the build-deploy "pack msapp files" step

### ISSUE THREAD

**Issue by concoursdude** [microsoft/coe-starter-kit#3518]
### Describe the issue

build_and_deploy_job is failing at the pack msapp step with error: 

Invoke-CanvasUnpackPack : Exception calling "SaveToMsApp" with "1" argument(s): "Object reference not set to an instance of an object."

The unpacking steps seem to execute successfully. Templates for these pipelines came from a clone of [this repo](
https://github.com/microsoft/coe-alm-accelerator-templates/archive/refs/tags/CenterofExcellenceALMAccelerator-August2022-HF1.zip).

@mikefactorial, any chance this is related to the changes we made in [this thread? ](https://github.com/microsoft/coe-starter-kit/issues/3485)

<img width="951" alt="image" src="https://user-images.githubusercontent.com/51216063/186675781-d7478a81-9fb1-4e8e-ab50-b57561ced548.png">

### Expected Behavior

msapp file from source control would be packed and prepared for deployment 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220726.1

### Steps To Reproduce

Unknown

**Comment by mikefactorial** [comment]
@concoursdude seems like something in the canvas apps platform has changed recently. This cropped on us starting yesterday. Looking into a fix for it.

**Comment by mikefactorial** [comment]
Were you able to run the deployment previously or is this the first time?

**Comment by concoursdude** [comment]
> Were you able to run the deployment previously or is this the first time?

This was the first time I had attempted to run it. I was trying to get the committing ironed out, that's all working perfectly now. Seems like all of the deploy pipelines are suffering from this same issue, though.

**Comment by concoursdude** [comment]
Just a quick update on this, the issue seems to be solution agnostic. The first solution I attempted to deploy where I hit this issue was a pretty complex one. Even with a simpler solution I still get the packing error. I've dug around a bit in the YML and in the PS script associated with this part of the job and I don't see anything glaring, but I'm probably out of my depth. Appreciate your help @mikefactorial.

**Comment by mikefactorial** [comment]
@concoursdude just getting back to this. We're moving to using the Power Platform Build Task's implementation of Canvas Unpack in the September release and have been focused on wrapping up work there. The release will be out next Wednesday and appears to solve the issues with Canvas Unpack that are likely due to changes in the designer. Pardon the delay, but haven't had time to investigate the issue in the current release further.
