### ISSUE TITLE
[CoE Starter Kit - Feature]: Customizable emails for Governance Solution 

### ISSUE THREAD

**Issue by hernan-ramirez** [microsoft/coe-starter-kit#3520]
### Describe the solution you'd like

The customizable emails feature for the Core solution works perfectly!
When will this feature be available for the Governance solution?

**Comment by Jenefer-Monroe** [comment]
Hello. Glad to hear its working well in Core! 

We have this on our backlog as https://github.com/microsoft/coe-starter-kit/issues/1683 but its just competing against some other big work items and we are a small team. Its useful to hear people ask for it though so appreciate you posting. I'll dupe you to that feature request, feel free to go mark it up with your notes :)
