### ISSUE TITLE
Data permissions/security roles required to share Maker Command Center with other users

### ISSUE THREAD

**Issue by bethleota** [microsoft/coe-starter-kit#3522]
I would like to share the Maker Command Center with the O365 Group that I created for Power Platform Makers. However, I'm not sure what data permissions/security roles required to do so. Kindly advise. Thank you
<img width="923" alt="ShareMakerCommandCenter" src="https://user-images.githubusercontent.com/40639953/186694342-52707fc6-7e87-4a5e-b7a5-754ceaff711b.png">
.

**Comment by Jenefer-Monroe** [comment]
We ship [3 security roles](https://docs.microsoft.com/power-platform/guidance/coe/core-components#security-roles) which you can use for the apps in Core
As this app targets your Makers, you would want to give them the **_Power Platform Maker SR_**. 

Hope that makes sense.

**Comment by bethleota** [comment]
Yes it does. Thank you!

**Comment by Jenefer-Monroe** [comment]
wonderful, ill go ahead and close this out then.
