### ISSUE TITLE
[CoE Starter Kit - Feature]: Add a isPremium property to Flow

### ISSUE THREAD

**Issue by Papa-Cho** [microsoft/coe-starter-kit#3529]
### Is your feature request related to a problem? Please describe.

I cannot distinguish flow running with Premium connectors from other flows.

### Describe the solution you'd like

I want to easily identify flows running Premium connectors in my tenant so that I can better govern those (license management mainly)

With such a property in Flow table of the CoE Kit, I could make reports and alerts to keep me informed about such flows.
I'm mainly interested in Cloud flows. But I guess similar info on Desktop flows would be useful

### Describe alternatives you've considered

I've looked for a way to browse a flow connections and from connection details detect if it's a Premium or not but failed.

**Comment by Jenefer-Monroe** [comment]
We do already store this information for you. You can see it demonstrated in the PBI here. Hope that helps
![image](https://user-images.githubusercontent.com/89584709/186946424-1af10fe6-6d03-436f-b86c-fe8a3868a5af.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
