### ISSUE TITLE
[CoE Starter Kit - Feature]: Data source (Table-level) visibility, prevention, and action. 

### ISSUE THREAD

**Issue by MichelleMSFT** [microsoft/coe-starter-kit#3530]
### Is your feature request related to a problem? Please describe.

From an security perspective, we want visibility into the datasources being used in Power Platform.

For example, we want to allow the use of certain connectors, since our business primarily uses them to store our data (SQL, SharePoint, as an example). However, let's consider someone in HR who has access to PII in these datasources. Although they may have access to this PII datasource, I do not want them to be able to use it within Power Platform. Currently, my only options: 
1. Lock down the connector for everyone
2. Stop our HR person from having licenses to Power Platform 

### Describe the solution you'd like

There are 3 things I want (as security) that would make me feel more comfortable adopting Power Platform and leaving it easy to use. 
1. **Visibility** into datasource information (Table name, URL) and which apps/flows/bots/pbis are using it. A summary of our most-used datasources, either an organized list or a dependency map. 
2. **Preventative** allow security team, or power platform team to approve/block certain datasources(tables) so that we can minimize oversight 
3. **Actions** automated emails to creators when they are using a blocked data source, to inform them they shouldn't be connecting to this, with options that allow the creator to acknowledge and automate deletion (just a push button in an email to let them delete it, so they can feel comfortable that they've deleted it correctly, and security can see that they have acknowledged and took action)

### Describe alternatives you've considered

Blocking access to all connectors except a global custom connector that security has specified table-access levels. 
- Doesn't provide the visibility aspect for security to see what's actually being used in each environment
- Doesn't allow for action aspect, automation of email to end user, and requires security to work to investigate each app/flow/bot/report

### Additional context?

Reach out if you would like more context :)

**Comment by Jenefer-Monroe** [comment]
Have you provided this feedback to the product team already as well? As far as I know most of the above is not available to us to collect in the kit. We can put on the backlog for consideration but direct feedback to the product team here would be useful for your needs.

**Comment by manuelap-msft** [comment]
Closing out tasks where there is no product backlog to provide this information. We can re-open should this information become available to us.
