### ISSUE TITLE
Innactivity Email Typo

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#3532]
### Describe the issue

Hi Team, 

The innactivity notification email for Flow and Apps has a typo. Insted of stating inquiries it says inquies. :) Also the Microsoft logo icon is too big people think the email is phising. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.18

### What app or flow are you having the issue with?

Email Manager Ignored Inactivity notifications Approvals

### Steps To Reproduce

Message Text

**Comment by Jenefer-Monroe** [comment]
Thank you for posting! 

We have fixed the spelling mistake for Sept via bug https://github.com/microsoft/coe-starter-kit/issues/3471
It's been there for like 6 months so its so fun to me that two of you posted it this month :)

For the logo, unfortunately we dont have an easy fix there. We don't have consistent rendering across clients right now. In the web app in chrome or edge it looks fine for example. https://github.com/microsoft/coe-starter-kit/issues/2004

A fix you can do for now for the logo is to remove it from the env variable as shown here. 
![image](https://user-images.githubusercontent.com/89584709/187005761-198450ee-c4b7-48a0-ba58-1b5adefefc91.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
