### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Sync Flow in Desktop Flow

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#3537]
### What is your question?

I have the following two flows turned on, but the information is not stored in the Desktop Flow table.
・Admin | Sync Template v3 (Desktop flows)
・Admin | Sync Template v3 (Desktop Flow - Runs)

I am using the CoE Starter Kit with the same version and the same settings for two tenants, but one tenant is able to collect it, and the other tenant is not.
I don't know if it's related,The tenant for which data can be collected is a test environment, and there are only 3 desktop flows. Also, the tenant for which data cannot be collected is the production environment, and there are many desktop flows.

https://github.com/microsoft/coe-starter-kit/issues/3003
It seems that a similar event has occurred in the inquiry linked above, but is it related to this problem?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

**Comment by Jenefer-Monroe** [comment]
Desktop Flows have some limitations due to the way we have to collect them. Large desktop flows, and large numbers of desktop flows in an environment, will cause the inventory collection to fail. 

Can you please see if the flows are running and passing in your production environment?

**Comment by sudadakkota** [comment]
I got a capture of the execution result of the flow.
Does this match the photo you want?

・Desktop flows
![flow](https://user-images.githubusercontent.com/70095092/187375268-c95f8a3e-1662-4631-8ded-2d3e4b59cfc4.png)

・Desktop flow - Runs
![runs](https://user-images.githubusercontent.com/70095092/187375345-fe61d753-819b-4e00-9a21-11b9b7e0e9ea.png)

**Comment by Jenefer-Monroe** [comment]
You will need to find a repro of this in your tenant to see what is going wrong. 
1. Find an environment in your tenant where you expect to see the desktop flows

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you are looking for missing canvas apps chose **_Admin | Sync Template v3 (Apps)_**, You will look for  **_Admin | Sync Template v3 (Desktop flows)_**
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

5. Return here with what happens within the flow

**Comment by sudadakkota** [comment]
Thank you for your answering.
I have tried the steps you have provided. Below is the execution result.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/70095092/187850372-b9eae869-0ed6-4837-876b-2b1c4e0ef8b5.png)

From the error message, I think that the acquired information is an error because it is over 100MB.Is that correct?

**Comment by Jenefer-Monroe** [comment]
Yes you have hit the limitation mentioned above unfortunately. 

The desktop flow work in the CoE Starter Kit currently has several limitations that make it insufficient for organizations heavily focused on that tech. This is due to the way that we gather the data and is not something we can fix without a product change (which is supposed to be coming live in a few months)

That said, there is a dedicated set of folks who work on "Automation CoE". My recommendation is that you focus in that direction instead. Here are some starter links to get you going:
- [Automation Center of Excellence Webinar](https://info.microsoft.com/ww-thankyou-businesscenterexcellencerpa.html?LCID=EN-US&ocid=eml_pg332504_gdc_comm_ba)
- [Microsoft Power Platform Automation CoE starter kit (preview)](https://docs.microsoft.com/power-platform/guidance/automation-coe/automation-coe-starter-kit)
- [RPA CLI](https://github.com/rpapostolis/rpa-cli)

**Comment by miroslav-harlas** [comment]
Hello, 
we are facing the similar, or maybe even exactly the same, issue. We are missing Desktop Flows inventory for our Default environment. We have very probably between 600-800 Desktop Flows in default environment as of now (rough estimate). We are getting the inventory of Desktop Flows properly for couple of other environments, where we have between 1-5 Desktop Flows. Do you think that this number (somewhere between 600-800) is already too much for getting Desktop Flows inventoried by CoE Starter Kit?
Thank you in advance for this clarification.
Miroslav

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
