### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Pavan12Verma** [microsoft/coe-starter-kit#3541]
### Describe the issue

Apps and flow count in overview report and deep dive reports are not matching

### Expected Behavior

All CoE starter kit Power BI reports should show correct and consistent numbers.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

NA

### Steps To Reproduce

- Perform data refresh of Power BI reports
- Go to overview Power Automate (flow) report and note down total # of flows
- Go to deep dive Power Automate (flow) report and  see total number of flows it is not matching

### Anything else?

No

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid this report is not actionable yet. Can you please share screenshots showing what numbers you are seeing different?

**Comment by Pavan12Verma** [comment]
See numbers in the attached screenshots

Thanks,

Pavan Verma
Database Administrator

Kerry
North America Region
3400 Millington Rd, Beloit, WI
www.kerry.com<http://www.kerry.com>

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately pictures do not come through if you respond in email. You will need to log in to GitHub to share them.

**Comment by Pavan12Verma** [comment]
![Deep dive Power Automate numbers](https://user-images.githubusercontent.com/101834540/187538872-81f368e4-cc6d-428e-97d3-0739fd2cdb4f.png)
![Overview report numbers](https://user-images.githubusercontent.com/101834540/187538875-a11c56da-d53e-4b5f-8377-7a6ebda19c1b.png)

**Comment by Jenefer-Monroe** [comment]
Mine match for that, can you please check your filters? See if they both filter out deleted flows.
Here are the filters on the overview page
![image](https://user-images.githubusercontent.com/89584709/187540109-56adab66-4ff9-4fc8-bc89-07168e60df2c.png)
And on the Cloud Flows page
![image](https://user-images.githubusercontent.com/89584709/187540234-7e7d11f3-8d46-4ab4-a41d-7e2d158ff878.png)

**Comment by Pavan12Verma** [comment]
Tried that too but still the counts are different
![Deep dive Power Automate filters](https://user-images.githubusercontent.com/101834540/187541621-9d35e02e-9f67-406c-bf4a-d3cb135203b0.png)
![Overview report filters](https://user-images.githubusercontent.com/101834540/187541627-50456329-e50d-4f69-943c-272e07f4e4ff.png)

**Comment by Pavan12Verma** [comment]
Just found that there is additional IsSystem filter which is causing the difference, once I clear the filter numbers on both reports are matching.

**Comment by Jenefer-Monroe** [comment]
Oh wonderful. Thanks for investigating! We did fix an issue with that filter in a later release of August. I'll go ahead and close now but please return if you have more issues.
