### ISSUE TITLE
[CoE Starter Kit - BUG] DLP and Connector for [Child] Admin | Sync Logs in Audit solution

### ISSUE THREAD

**Issue by schaud137** [microsoft/coe-starter-kit#3545]
### Describe the issue

I deployed power platform landing zone from github https://github.com/microsoft/industry/blob/main/foundations/powerPlatform/referenceImplementation/readme.md
DLPs are created for tenant (medium level) and admin environments. Then I imported "Center of Excellence - Audit Logs". When I try to turn on "[Child] Admin | Sync Logs" I get the attached error.
![Admin Sync Logs Error](https://user-images.githubusercontent.com/59722885/187334998-98695864-93de-4d1f-b867-fa0df2408b16.JPG)

### Expected Behavior

Should be able to turn on "[Child] Admin | Sync Logs"

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Aug 2022 release

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by manuelap-msft** [comment]
Hello,

this means the custom connector used by the Audit Log solution is not allowed as part of your DLP policy. We recommend setting up a dedicated DLP policy for your CoE environment with the following connectors in the same group: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

Here's how you can configure custom connector endpoints in DLP:
https://docs.microsoft.com/en-us/power-platform/admin/dlp-connector-classification#tenant-level-dlp-policies

**Comment by manuelap-msft** [comment]
PS: We also provided feedback to the Landing Zones team to consider including the custom connector host in the admin environment policies that's configured via Landing Zones.

**Comment by schaud137** [comment]
Hi,
I added the "Office 365 Management APIs" custom connector in the DLP to Business group and can turn on both "[Child] Admin | Sync Logs" and "Admin | Sync Audit Logs".
Thanks for your help.

**Comment by Jenefer-Monroe** [comment]
thanks for letting us know as well
