### ISSUE TITLE
[CoE Starter Kit - BUG] WRONG CRITERIAS FOR TEAMS ENVIRONMENT CREATION SUMMARY MAIL

### ISSUE THREAD

**Issue by WinOnMarco** [microsoft/coe-starter-kit#3547]
### Describe the issue

The "Summary mail to admins" from the cloud flow "Microsoft Teams Admin  | Weekly Clean Up of Microsoft Teams environments" sends information about environments that don't meet the criterias as described in the mail text.
The mail text says "In the past 7 days, the following Microsoft Teams environments have been created and require review - please open the Power Platform Admin View and approve/reject the business justification of these environments."

Environments are getting listed below this text that are already approved or older than 7 days.

### Expected Behavior

- If an environment was approved, it should not be listed in this e-mail "Summary mail to admins" .
- If an environment was created more than 7 day ago (no 90 days! > filter is wrong in "List new teams environments") it should not be listed in this e-mail "Summary mail to admins".

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.19

### What app or flow are you having the issue with?

Microsoft Teams Admin  | Weekly Clean Up of Microsoft Teams environments

### Steps To Reproduce

1. Create Dataverse for Teams Environment
2. Wait for compliance request
3. Approve the request
4. The environment is still listed in the mail "Summary mail to admins", even after more than 7 days.

**Comment by Jenefer-Monroe** [comment]
Hello. Thanks for posting. We have this bug in the backlog already. Please see https://github.com/microsoft/coe-starter-kit/issues/3153
I'll go ahead and close as a dupe. Thanks for using CoE
