### ISSUE TITLE
[AA4AM] Move all source code under a src folder at the root of the repo

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#355]
To stay consistent with many other repos, a src folder at the root of the repo is almost de facto standard.

**Comment by rpothin** [comment]
Hello @devkeydet,

Can you give some details about the advantages to go to a repository's organization like this one please?

Thank you in advance and have a nice day 😊

**Comment by devkeydet** [comment]
Not sure I understand the question.  Can you elaborate?

**Comment by devkeydet** [comment]
Here are examples of what the issue is proposing.
![image](https://user-images.githubusercontent.com/4499296/118286930-f7cb6080-b4a0-11eb-9198-5fb081e8ab6b.png)
![image](https://user-images.githubusercontent.com/4499296/118287061-1893b600-b4a1-11eb-8c86-99e2f43553d3.png)

The idea is that we will move anything that is source code into a "src" folder at the root of the repo.

**Comment by rpothin** [comment]
Sorry @devkeydet for the delay of my answer and for the imprecise question.

What exactly do you plan to put under the **src** folder in the case of this repository?
If I am not wrong, today we mainly have unpacked solutions with associated pipelines in YAML in each folder at the root level, no?

I am just a little bit worry because I see this **src** folder as a place to *hide a bit* things *less* interesting, like PowerShell code or code for testing 😁.

**Comment by devkeydet** [comment]
Short answer is source code.  Docs, for example, are not source code.  Today, that means all these folders will go under the src folder.
![image](https://user-images.githubusercontent.com/4499296/118297429-21d65000-b4ac-11eb-828e-0dbc5db59f7d.png)

We will have more source code root folders over time because we will have more solutions in the CoE Starter Kit over time.  We will have automation source code that doesn't belong in folders that represent Solutions.  We don't want a root with tons of folders.  We'll eventually have a GitHub worklfows here.  We want the high-level folders to have a clearer separation of concerns.

There are lots of things that are not source code that go into repos, so we want some clearer differentiation.

**Comment by mikefactorial** [comment]
We should make sure this is configurable. Ideally, we would continue with the current default structure and add variables for pointing at different structures.

**Comment by mikefactorial** [comment]
Closing this issue out. No plans to make this change in the foreseeable future.
