### ISSUE TITLE
[ALM Accelerator - BUG]: Object Not found Error in Enable/Disable Solution Flow step

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#3556]
### Describe the issue

We face below error at  Enable/Disable Solution Flow step
Error : 
![image](https://user-images.githubusercontent.com/44782172/187676942-58e9f0ed-9074-41a6-89c3-1000edef6823.png)

Solution contain some flows 
![image](https://user-images.githubusercontent.com/44782172/187677042-7b7aa70c-9fa5-4cfc-afdd-6814ef059b80.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Apr 2022

**Comment by linujohn22** [comment]
It is duplicate of  #3555

**Comment by linujohn22** [comment]
It seems , a workflow trigger on particular entity in that case that entity also part of the solution .  This is not correct , there cases we need to move only workflows .  seems it is a bug .

**Comment by mikefactorial** [comment]
@linujohn22 can you comment on the other issue that this was closed for as a duplicate. Best to keep everything in one thread. Thanks!
