### ISSUE TITLE
[BUG]: Admin | Compliance detail request v2 in Teams

### ISSUE THREAD

**Issue by Cathi121** [microsoft/coe-starter-kit#356]
Hi, 

**Describe the bug**
I set up the core component and the governance component. After this I wanted to use the "Admin | Compliance detail request v2 (Teams)" Flow but several fields within conditions where missing.

**Component:**
 - Solution [Core, Governance]
 - Version [latest with Dataverse for Teams]
 - Flow [Admin | Compliance detail request v2 (Teams)]

I don´t know if this is really a bug but it would be great to get help on the missing fields.

<img width="400" alt="Missing fields Condition Get Assignee" src="https://user-images.githubusercontent.com/84190044/118282580-b81b6d80-b4ce-11eb-8b1f-35a50307d6cc.png">
<img width="737" alt="2021-05-14 Missing fields condition business requirements and mitigation plan" src="https://user-images.githubusercontent.com/84190044/118282915-15172380-b4cf-11eb-99ab-fc97da84419b.png">

**Comment by JeneferM-MSFT** [comment]
Can you please share what version of Core and Gov you installed?

**Comment by Cathi121** [comment]
![image](https://user-images.githubusercontent.com/84190044/118286221-85737400-b4d2-11eb-95e2-4e46e2b2d0de.png)

**Comment by JeneferM-MSFT** [comment]
Hello. I do see this in our local version. It seems that the flow got corrupted. We will reship a new version shortly.

**Comment by Cathi121** [comment]
> Hello. I do see this in our local version. It seems that the flow got corrupted. We will reship a new version shortly.

Thanks a lot!

**Comment by JeneferM-MSFT** [comment]
We just shipped a new version of Core for Teams. Note that the flow is now called with a v3 in the name. 
Thanks for helping make CoE great!
