### ISSUE TITLE
[CoE Starter Kit - BUG] Connection Details report - Connectors missing for default Environment

### ISSUE THREAD

**Issue by ssmander** [microsoft/coe-starter-kit#3561]
### Describe the issue

Connectors are missing for default Environment in the Connection Details report within the COE governance POWER BI Dashboard. Connectors for all other environments are reported but no connectors for default environment appear in the report.
![image](https://user-images.githubusercontent.com/14800260/187702821-484ccaf8-594f-46ad-854c-819b04c8167b.png)

### Expected Behavior

All Connectors for default environment should appear in the Connection details report .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

### Steps To Reproduce

Open PowerPlatformGovernance_CoEDashboard_202206.pbit and select 'Connection Details' report and there are no connections displayed for the default environment (Personal Productivity)

**Comment by manuelap-msft** [comment]
You're likely running into a known limitation where you have too many connections in the Default environment so the connector can't return the size - see this thread for a workaround:
https://github.com/microsoft/coe-starter-kit/issues/3293

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
