### ISSUE TITLE
[CoE Starter Kit - Custom Connector]: Certificate credentials instead of client secret

### ISSUE THREAD

**Issue by alisoncyeh** [microsoft/coe-starter-kit#3568]
### Is your feature request related to a problem? Please describe.

In order to set up/use a custom connector, customers have to use an app registration that leverages a client secret; however, our [identity platform best practices documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/identity-platform-integration-checklist#security) states:

Protect and manage your confidential app credentials for web apps, web APIs and daemon apps. **Use certificate credentials, not password credentials (client secrets).** If you must use a password credential, don't set it manually. Don't store credentials in code or config, and never allow them to be handled by humans. If possible, use managed identities for Azure resources or Azure Key Vault to store and regularly rotate your credentials.

Is there a timeline for when certificate credentials will be supported?

### Describe the solution you'd like

ETA, if available, for when certificate credentials will be supported.

**Comment by manuelap-msft** [comment]
If I'm not mistaken, this is not supported by custom connectors itself yet - the available authentication methods are: https://docs.microsoft.com/en-us/connectors/custom-connectors/#2-secure-your-api

The CoE Starter Kit can only make use of what's available in the platform. If something is not available in the platform, I'd recommend raising this as a feature ask with our product engineering group via the Power Users community: https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity

**Comment by manuelap-msft** [comment]
Closing out as not actionable until available in the product.

**Comment by alisoncyeh** [comment]
Thanks Manuela, will do!
