### ISSUE TITLE
[ALM Accelerator - BUG]: GetSolutionConnectionReferences.Run failed

### ISSUE THREAD

**Issue by mtsyvis** [microsoft/coe-starter-kit#3570]
### Describe the issue

Can't see the connection references after clicking _Configure deployment settings_ in the solutions window.
I am getting this error message:
![image](https://user-images.githubusercontent.com/37982066/187851995-d1cde7ea-a8fb-43a9-bb83-47fb4a1c7b9a.png)

After this error if i open the **GetSolutionConnectionReferences** flow, i see the next error in _Get Solution Components_ action:
![image](https://user-images.githubusercontent.com/37982066/187854310-6382594c-f0e6-490e-b68a-2215cb31e29c.png)

Inner error in the action:

>  "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request - Request Too Long</h2>\r\n<hr><p>HTTP Error 400. The size of the request headers is too long.</p>\r\n</BODY></HTML>\r\n"

P.S. My solution has 2 connection references - SharePoint and Mail

Thank you in advance for help

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220726.1

**Comment by rsantos00** [comment]
@mtsyvis Can you confirm that you have "Environment Maker" in the 3365upgrade environment? If you open make.powerapps.com do you see that environment in the list ?

**Comment by mtsyvis** [comment]
> @mtsyvis Can you confirm that you have "Environment Maker" in the 3365upgrade environment? If you open make.powerapps.com do you see that environment in the list ?

Yes, I have 2 roles on this environment - "Environment Maker" and "System Administrator"

**Comment by mikefactorial** [comment]
@mtsyvis following up. Were you able to get this resolved? Can you verify that all of the Flows in the ALM Accelerator Solution are turned on?

**Comment by mtsyvis** [comment]
I just moved development to another environment. And there it works

**Comment by mikefactorial** [comment]
Thanks for the update @mtsyvis. Glad it's working. Closing this out for now.
