### ISSUE TITLE
[CoE Starter Kit - QUESTION] Roles required for audit log

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#3571]
### What is your question?

I would like to use the CoE Starter Kit audit log solution.
I have only given the PowerPlatform administrator role to the account for the installation. 
Can I install the audit log solution in that state?
The following URL says that the ID must have an audit log. What role is required in this case?

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with:~:text=If%20you%27d%20like%20to%20collect%20telemetry%20information%2C%20such%20as%20app%20launches%20and%20unique%20users%20per%20app%2C%20the%20identity%20must%20have%20access%20to%20the%20Microsoft%20365%20audit%20log.

Will it work with only the PowerPlatfrom administrator role?

Thank you in advance.

### What solution are you experiencing the issue with?

Audit Log

**Comment by manuelap-msft** [comment]
You will need a Global Admin to set up the App Registration in Azure, which will be set up to have permissions to read the Audit Log
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#create-an-azure-ad-app-registration-for-the-office-365-management-api

If the Global Admin then shares the client ID and client secret with you, you can configure the custom connector and that should work even if you yourself don't have access to the Audit Log. However, we've not tested that ourselves.

**Comment by egym07** [comment]
For example, a global administrator registers the application in Azure. The client ID and client secret are then shared with the PowerPlatfrom administrator. The PowerPlatfrom administrator configures the custom connector.
In this way, the PowerPlatfrom administrator will be able to see the logs?

**Comment by Jenefer-Monroe** [comment]
As long as the PP Admin has access to the audit logs yes. Please see [What identity should I install the CoE Starter Kit with?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)
![image](https://user-images.githubusercontent.com/89584709/188176221-3b02c5d5-c5ae-4310-8f96-dfd845399b44.png)

**Comment by egym07** [comment]
How do I know if the PowerPlatform administrator has access to the audit log?

**Comment by egym07** [comment]
Or am I correct in understanding that if I add the PowerPlatform administrator in Exchange Online to the group to which the [Audit Log] role is assigned, it will work?

**Comment by Jenefer-Monroe** [comment]
The best way in my experience is to just log in with that identity to see if you can view them 
https://protection.office.com/unifiedauditlog

**Comment by egym07** [comment]
Thank you very much.
This seems to be the solution for the time being.
If I have any more questions, I will ask them in another thread.
Thank you so much for your help.

**Comment by Jenefer-Monroe** [comment]
Thanks for letting us know, and for using CoE!
