### ISSUE TITLE
[CoE Starter Kit - QUESTION] GCC Audit Log Collection issues

### ISSUE THREAD

**Issue by TigerJ** [microsoft/coe-starter-kit#3577]
### What is your question?

Not sure why we are getting 

{
  "Message": "Authorization has been denied for this request."
}

When testing the custom connector for the audit logs. I have quadruple checked all the setup steps and confirmed I can access the logs with the account in use (by visiting compliance.microsoft.com) I can search the logs with the account without issue. 

Consent has been granted for the api permissions required. This connector and related flows were functioning but recently have stopped. We are trying to determine why or what change may have been made within the organization that could result in the response from testing the subscription: "Authorization has been denied for this request."

Any ideas or areas to explore would be great. We have thoroughly combed the CoE setup and not found any issues.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

N/A

**Comment by Jenefer-Monroe** [comment]
If this used to work and now doesnt, then likely your connection broke on upgrade or expired. Please see the notes in https://github.com/microsoft/coe-starter-kit/issues/1424 to see if the problem looks similar.

**Comment by TigerJ** [comment]
Upgrade did occur, connection did break, but was fixed per the steps in your link, afterwards the flow errored with "Authorization has been denied for this request."

Thanks for the response! I wish there was more details from the message that could help troubleshoot. The account is authorized to use the logs on the compliance site. I may enter a ticket in with MS support I've gone over the setup step by step multiple times.

If you have any other ideas they are greatly appreciated.

**Comment by Jenefer-Monroe** [comment]
Can you please share some screenshots for us to see your state? That will help us debug
1. In the app registration, lets make sure the permissions are set correctly
![image](https://user-images.githubusercontent.com/89584709/188026511-64e9fdac-d1eb-4b39-b097-69cbd35a13e3.png)

3. Lets see if the connector is working. In the custom connector itself > test > ListContent
![image](https://user-images.githubusercontent.com/89584709/188022011-7ad28a3f-d3e0-4bda-a1b9-c764efa632ee.png)

4. In the child flow see if the run only users permissions are set
![image](https://user-images.githubusercontent.com/89584709/188025656-78cd0d59-2a0f-41f2-9db2-b3daa5866441.png)
![image](https://user-images.githubusercontent.com/89584709/188025727-9384cd0a-0a7e-42a1-a6b5-7d4352a344d1.png)

**Comment by TigerJ** [comment]
![image](https://user-images.githubusercontent.com/1319169/188060050-099d1dec-273a-4232-9bf4-caed956248ff.png)
![image](https://user-images.githubusercontent.com/1319169/188060071-5bb156ff-0502-45bf-a2d7-667ce537a10e.png)
![image](https://user-images.githubusercontent.com/1319169/188060088-fcfa406b-1f56-477a-9361-768b23c5e8fe.png)

**Comment by manuelap-msft** [comment]
In the Azure App Registration, can you check if the secret has expired by clicking on Certificates and Secrets?

**Comment by TigerJ** [comment]
It is not, and we are using the secret value and not the guid.

![image](https://user-images.githubusercontent.com/1319169/188138792-b3d2d0e1-ea2d-4129-8323-50833aeb0c12.png)

**Comment by Jenefer-Monroe** [comment]
Are you a commercial tenant? Or are you hosted from some other cloud? (ex GCC)

Can you please share a screenshot of this identity used in the connection successfully connecting to the audit logs themselves? 
This identity:
![image](https://user-images.githubusercontent.com/89584709/188177521-2574a765-ed43-4781-9aeb-e9af8f27e990.png)

Browse here: https://compliance.microsoft.com/auditlogsearch?viewid=Search&rfr=scc_unifiedauditlog
Filter for faster results > search > click on the job status to see if you get results
![image](https://user-images.githubusercontent.com/89584709/188178549-e20f9095-0be5-4829-a9a2-228f411cb813.png)
![image](https://user-images.githubusercontent.com/89584709/188178880-5f6aa99c-8f08-4a7d-9612-f77c74c87aef.png)

**Comment by TigerJ** [comment]
We are in the GCC cloud.

![image](https://user-images.githubusercontent.com/1319169/188219295-56dcbd42-ea48-42f7-8973-815c1c031bc6.png)

**Comment by Jenefer-Monroe** [comment]
Ok, there are a few places in the documentation that call out specific things needed for GCC. 
Can you please go to the documentation and search for them to make sure you have done them all? 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
![image](https://user-images.githubusercontent.com/89584709/188227128-8a261905-3b96-4bec-a77a-3ec5b643df10.png)

**Comment by TigerJ** [comment]
Yes they have all been done.

**Comment by Jenefer-Monroe** [comment]
I'm afraid I'm out of ideas then. Other GCC customers have been able to setup with these instructions and we've walked through the issues people have hit in the past. You may need to seek out a partner to assist with setup as they will be able to log in and look at your setup.

**Comment by TigerJ** [comment]
Thanks Jenefer, 

I am a partner and have done this with several other GCC tenants. I will try to issue a support ticket with Microsoft and avoid them redirecting me here. You have helped me with several other issues in the past. When I create the support ticket I will try to avoid mentioning the COE specifically and instead reference the 401 error and compliance api.

Thanks again for your time.

**Comment by Jenefer-Monroe** [comment]
thank you! Please let us know what you find!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
