### ISSUE TITLE
[CoE Starter Kit - BUG] - Data discrepancy in sync flows

### ISSUE THREAD

**Issue by SumedhAlstom** [microsoft/coe-starter-kit#3579]
### Describe the issue

The flows are not fetching all the apps and flows, resulting in data inaccuracy. 
In Tenant level analytics: No of apps : 5500, No of Flows : 11000+. But in CoE it shows no of apps: 5100 and no of flows : 2000 only.
Earlier the number flows were correct, after this upgrade it is showing incorrect. 

### Expected Behavior

Correct number of flows and apps.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Admin - sync template V3

**Comment by Jenefer-Monroe** [comment]
We don't see issues this issue so we will need you to explore to find the source. Before diving to a deep investigation lets do a high level pass to see if there is anything obvious. 

Please share screenshots of the below questions for us to explore. Note that you need to be logged in to GitHub to share images, you cannot respond in email with pictures. 

1. App runs
Go to the details for **_Admin | Sync Template v3 (Apps)_**. Share this screen so we can see when the last successful run occurred.
![image](https://user-images.githubusercontent.com/89584709/188174202-48fef558-bc93-40b3-ba6c-712b955d8b8b.png)

Then click all runs there at the top of the run history box > filter in the top by failures. Share this screenshot so we can see when the last failed run occurred.
![image](https://user-images.githubusercontent.com/89584709/188174527-b89f4336-3bd8-4862-93cc-9275a5d5ac3a.png)

2. Flow runs
Go to the details for **_Admin | Sync Template v3 (Flows)_** and share the same screenshots as you did for apps.

**Comment by SumedhAlstom** [comment]
1) Admin | Sync Template v3 (Apps) runs : 

recent runs :
<img width="836" alt="image" src="https://user-images.githubusercontent.com/107856142/188396357-029d5d2d-2c6e-4f18-8e89-5efa16e89ead.png">

Failed runs:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/107856142/188396566-e1da3f20-9d60-4402-8e93-c90bf82228a9.png">


2) Admin | Sync Template v3 (Flows)  :

Recent runs -
<img width="895" alt="image" src="https://user-images.githubusercontent.com/107856142/188395546-e77ce022-4aa8-404c-98f7-636631e9c961.png">

Failed runs :
<img width="596" alt="image" src="https://user-images.githubusercontent.com/107856142/188395735-aefd3c8b-6dc9-48ee-98bd-c8303da3ce42.png">

**Comment by Jenefer-Monroe** [comment]
OK with numbers off at this magnitude, you should probably just run a [full inventory](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
