### ISSUE TITLE
[CoE Starter Kit - QUESTION] App Launches in PowerBI is blank

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#3580]
### What is your question?

I have completed the Audit Log procedure (and the flow is successful), but App Launches in PowerBI is blank.
I have completed the steps in the following URL
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

What could be the cause?
Is there some setting that is missing?
I would like to know.

**Comment by manuelap-msft** [comment]
Hello,

can you go to the Core Components solution, open the Power Platform Admin View (model driven app) and navigate to Audit Logs and confirm if you see any data there:
![image](https://user-images.githubusercontent.com/55705669/188102983-ebf69dfc-9c98-4ac0-ae3b-71de4fc03e9f.png)

If you do see data there but not in the dashboard, you might have to refresh the dataset in the dashboard and configure scheduled refresh so the data is up to date.

Manuela

**Comment by manuelap-msft** [comment]
And can you also open the [Child] Admin Sync Logs flow and confirm that is running without failures?

**Comment by egym07** [comment]
Thanks for the reply.
Both "[Child] Admin Sync Logs" and "Audit Logs of Power Platform Admin View" appear to be working fine.

Which document says "you might have to refresh the dataset in the dashboard and configure scheduled refresh so the data is up to date."?

![image](https://user-images.githubusercontent.com/91306350/188107697-1c1b8868-1734-4f3c-bec5-3475c9e311a8.png)
![image](https://user-images.githubusercontent.com/91306350/188107846-81a88078-7384-4952-aa0e-6f196ff260c7.png)

**Comment by manuelap-msft** [comment]
Awesome, it's good to see the Audit Log table seems to populate correctly!

[In this document https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi,](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard) step 5
![image](https://user-images.githubusercontent.com/55705669/188110621-11fa7467-5e49-4db1-9af6-d467de781bea.png)

Here's the link on how to configure scheduled refresh
https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data#configure-scheduled-refresh

**Comment by egym07** [comment]
I set it up based on the information you provided and now some values are entered where they were blank.
I had not updated the PowerBI dataset. This seems to have been the problem.
Thank you so much! I have solved the problem!

![image](https://user-images.githubusercontent.com/91306350/188115414-7e9f6753-a043-48dd-9a16-6792bf09f9f8.png)

**Comment by egym07** [comment]
Excuse me. I would like to ask one more question.
Is the blank space here due to the audit log?

![image](https://user-images.githubusercontent.com/91306350/188120367-b41abc39-6941-4f03-ba72-8aac50743751.png)

**Comment by egym07** [comment]
Sorry to ask so many questions, but there are a few things that are marked as blank in both the Production_CoEDashboard and the PowerPlatformGovernance_CoEDashboard. What settings am I missing? I would like to know.

![image](https://user-images.githubusercontent.com/91306350/188348277-5feb2847-ed81-48f6-b8e7-1e25bea19608.png)
![image](https://user-images.githubusercontent.com/91306350/188348341-2e439971-2f0a-4eec-a700-2808b92b8345.png)

**Comment by egym07** [comment]
（空白）means blank.

**Comment by Jenefer-Monroe** [comment]
For the governance dashboard, those seem like things that could have zero's (eg no non-compliant apps). 
Please see our documentation on that report: https://docs.microsoft.com/power-platform/guidance/coe/power-bi-compliance

**Comment by Jenefer-Monroe** [comment]
For the lack of data on the Makers list its likely an issue with the isSystem filter in the report. You will either need to upgrade to get the lastest version of Core etc and dashboards that does not have this bug, or remove that filter. 

Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by egym07** [comment]
Sorry for the late reply.
1) Both users and time were added to the audit log.

In some cases, it was not blank.
Is there a case where it is working correctly but is blank?
Is there something I am missing in my settings?

![image](https://user-images.githubusercontent.com/91306350/195262565-ea4622b7-2355-4416-b5b6-4880bc8307f3.png)

![image](https://user-images.githubusercontent.com/91306350/195262663-0c7cca84-62c2-4045-9a3a-f234f0eeebef.png)


2) Regarding "App Shared wirh > 100 users", I agree that it is blank because the number of people belonging to the group is certainly not over 100.

**Comment by egym07** [comment]
And, The URL you provided does not list "Open Enviroment Requests" or other information.
https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-compliance#compliance-and-governance



The latest PowerBI I imported seems to be able to retrieve the information shown in the figure below.

![image](https://user-images.githubusercontent.com/91306350/195268795-7d373f53-7269-4ddf-8080-f5bcc79f65ba.png)

Please provide details on what we can get where it is missing in the documentation.
