### ISSUE TITLE
[CoE Starter Kit - QUESTION] PowerBI and  Admin - Access this App

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#3581]
### What is your question?

I saw this on another issue and it ended up unresolved, so let me ask the question again.

When syncing with PowerBI's Admin - Access this App, I got this error on the app.

The user is the user who imported the CoE Starter Kit, and I am also signed in on PowerBIDesktop as the user who imported the CoEStarterKit. Also, the environment is set to the environment in which the CoEStarterKit was imported.
Still, I get this error.
Sorry the image is in Japanese.

What else could be the problem? I would appreciate it if you could tell me.

![image](https://user-images.githubusercontent.com/91306350/188122319-793ca8c2-5299-4045-8139-323e236a1421.png)
![image](https://user-images.githubusercontent.com/91306350/188122427-8c56e4c2-9f39-4192-8529-4b470dabdc31.png)

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
This app does not work out of the context of the PowerBI its intended for. So you would not use it just by launching. 

Please see [Configure embedded apps in the CoE dashboard](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard) for how to set this up in the context of the PBI reports. 

Hope that helps.

**Comment by egym07** [comment]
Thank you for your reply.

We are aware that this is the same issue as the following URL
https://github.com/microsoft/coe-starter-kit/issues/2377#issuecomment-1108108173

As you mentioned, the error occurred after configuring the app by embedding the app from PowerBIDesktop.

**Comment by Jenefer-Monroe** [comment]
Yes you can ignore this error, you should not boot this app outside of the context of the PBI in which it is embedded as it will have no envt/app passed in.

**Comment by egym07** [comment]
Then this one is resolved.
Thank you!

**Comment by Jenefer-Monroe** [comment]
Great thanks for confirming, and for using CoE
