### ISSUE TITLE
[CoE Starter Kit - BUG] NO LOGO SIZING IN EMAIL NOTIFICATIONS

### ISSUE THREAD

**Issue by WinOnMarco** [microsoft/coe-starter-kit#3583]
### Describe the issue

The Logo of all Notifications in CoE are not correctly sized, when opened in Outlook Client. Usually the logo is oversized. The Logo size is correct when the notification mail is opened in Outlook Online.

### Expected Behavior

The notification logo should be scaled to a fixed size (e.g. fixed width).

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

HELPER - Send Email

### Steps To Reproduce

1. Run any of the flows that are sending Email notifications.
2. The Logo (by default the microsoft logo) is oversized in the Outlook Client

### Anything else?

<img width="916" alt="image" src="https://user-images.githubusercontent.com/99335718/188222300-85dcf063-d586-4269-886a-315f31e13619.png">

**Comment by Jenefer-Monroe** [comment]
Hello, this is a known issue with the way our mails render cross clients. Please see https://github.com/microsoft/coe-starter-kit/issues/2004 for details and for a workaround of how to remove that logo. 

Thanks for using CoE

**Comment by WinOnMarco** [comment]
Thanks.

Actually, I was previously searching for an already existing similar issue. But I didn't find it. Sorry for bothering you.

**Comment by Jenefer-Monroe** [comment]
No bother, we are here to help!
