### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why Compliance solution excludes Model Driven apps?

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#3592]
### What is your question?

Hi,
we are testing the compliance solution but we see that de Model Driven are excluded of this workflow? What is the reason?
Thanks.

![image](https://user-images.githubusercontent.com/57954993/188608026-bd89c0cf-af03-4186-9b97-6f56ec01acce.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Lastest

### What app or flow are you having the issue with?

Admin | Compliance detail request

**Comment by Jenefer-Monroe** [comment]
We don't have usage data for Model Driven Apps today so we cannot predict when they are heavily used. 
Hope that makes sense.

**Comment by albertocaa1317** [comment]
Ok, and last question: Do you know if with BYO Datalake feature this data will be available?

**Comment by Jenefer-Monroe** [comment]
It does contain it! And from our preliminary testing it seems to work !

**Comment by albertocaa1317** [comment]
Great! Thanks Jenefer and have a nice day!

**Comment by Jenefer-Monroe** [comment]
happy to help :)
