### ISSUE TITLE
[CoE Starter Kit - BUG] Set App permissions app incorrupt url

### ISSUE THREAD

**Issue by A-Demir-ilx** [microsoft/coe-starter-kit#3593]
### Describe the issue

In the set app permissions app when you click on the App settings button is not working. It's missing a / after .com in the URL. See output below.

https://make.powerapps.comenvironments/d2d40d59-4d8e-4e90-ab18-2d890

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Set App permissions

**Comment by Jenefer-Monroe** [comment]
This is to be set as part of the env variable. We always assume the trailing slash to be included (as we have to assume one way or another)

Please see [Gather environment variable values](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values)

And update your environment variables in the Admin - Command Center as shown here
![Image](https://user-images.githubusercontent.com/89584709/188668361-e58c1462-eb18-45bf-8e42-1d25767fc5e9.png)

**Comment by A-Demir-ilx** [comment]
Thank you!
