### ISSUE TITLE
[ALM Accelerator - QUESTION] while scanning a simple key error - ADO Pipelines

### ISSUE THREAD

**Issue by crowdedLeopard** [microsoft/coe-starter-kit#3595]
### What is your question?

Hello - unfortunately I have another issue with the ALM accelerator 

On trying to run the first part of the deployment via the valiadation pipeline I recieve this error - I've tried researching it and cant identify what I need to do 

![image](https://user-images.githubusercontent.com/99030907/188674479-793ce591-ef6e-4685-ab39-99f3594fa2eb.png)

could anyone advise 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Aug 2022

**Comment by crowdedLeopard** [comment]
I found it -  been looking at it too long - it needed a space where there wasn't one in the line 8 position - I'm going to go sit in a dark room for a bit

**Comment by crowdedLeopard** [comment]
many thanks :-)

**Comment by mikefactorial** [comment]
Thanks for reporting back @crowdedLeopard!
