### ISSUE TITLE
Need help updating Dashboard

### ISSUE THREAD

**Issue by thecapostol** [microsoft/coe-starter-kit#3596]
### Describe the issue

We have installed the COE toolkit and need some help updating it in a test environment.

### Expected Behavior

be able to export and then import and then apply update

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin Sync logs

### Anything else?

none

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid I dont understand what you are asking for. Are you looking for generalized help on how ALM works for Power Platform?

**Comment by thecapostol** [comment]
We are not using ALM.    We just want to apply updates in a test environment.    How do we get our production solution into the test environment.   Right now the export solution is grayed out.

**Comment by Jenefer-Monroe** [comment]
Yes you have likely installed a managed solution (which is what we produce for you all) so you would not be moving it around.
If you are customizing the kit, please see [Extend and customize CoE Starter Kit components](https://docs.microsoft.com/power-platform/guidance/coe/modify-components)

**Comment by thecapostol** [comment]
The guide produced by Microsoft entitled Updating the Center of Excellence (CoE) Starter kit has a testing strategy which recommends to create a dedicated testing environment.     Are you saying not to move it around and test?

**Comment by Jenefer-Monroe** [comment]
Oh I think i understand now. Yes that is not needed for testing our chagnes. 

You can install the latest builds from us in a test environment (with ProductionEnvironment to No)
Then when you are happy with the relesae and ready for it in production, you install from us again, this timeinto your Production Environment. 

Hope that makes sense.

**Comment by thecapostol** [comment]
I don't really want to install from scratch the latest build because it took us a long time even with the help of a partner to get it configured correctly.     Is there a way to copy the production into a test, apply updates, and then test to make sure it is working properly.    Once we feel it works okay then move the UAT solution to production.

**Comment by albertocaa1317** [comment]
You can restore a backup of your prod coe environment to a test coe environment empty.
After this, like said Jennifer, remember to change the environment variable "production enviroment " to No.
After this you can update your test coe environment with the last release of coe starter kit and test it.
If everything is ok, you will can to upgrade your prod environment.

**Comment by albertocaa1317** [comment]
We make a manual backup of prod coe env and restore it in other sandbox env, the test coe environment.
This is the doc related:
https://docs.microsoft.com/en-us/power-platform/admin/backup-restore-environments#create-a-manual-backup

Like I said, it's important to change in test coe environament the environment variable "production environment" to No and it's optional turn off all flows, depend of if you want to have updated daily this test coe env.

Only turn on the flows of solutions that you want to test, after to import the updated solutions included in the new release.

We don't export anything from test to prod. When we accept the new solutions of the new release, we import them directly in Prod coe environment.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
