### ISSUE TITLE
[ALM Accelerator - Branch error] export-solution-to-git branch error

### ISSUE THREAD

**Issue by rfolgadoal** [microsoft/coe-starter-kit#3597]
### What is your question?

According to the documentation, I have given access to Contribute, Contribute to pull requests, and Create a branch, but I still get an error: TF402455: Pushes to this branch are not allowed; you must use a pull request to update this branch.
![image](https://user-images.githubusercontent.com/93584307/188818029-02d80cf1-68b8-49c1-90d9-1e4addd98253.png)

In the Pipeline policy, I got all the permissions.
![image](https://user-images.githubusercontent.com/93584307/188816301-d760da5e-8efd-4cca-ad7f-0846af53fa02.png)

In Repositories policy I don't have any policy. And in Branch security, I got these permissions (including access to ‘Bypass policies when pushing’ and 'Force push'):
![image](https://user-images.githubusercontent.com/93584307/188818150-d8a5073f-038d-4afa-89f0-a0496e0f2e02.png)

I am not sure if I have lost any permissions.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220726.1

**Comment by mikefactorial** [comment]
@rfolgadoal the default configuration creates a Branch policy on the solution branch that will prevent you from committing directly to the branch as seen below. The expectation is that you'd commit to your personal working branch based on the solution branch and then create a pull request via the Deployment screen in AA4PP. NOTE: That the first time you commit a solution you'd create your working branch off of main the export will create the solution branch for you along with branch policy and from there subsequent working branches can be created off of the solution branch.

![image](https://user-images.githubusercontent.com/42348035/188858266-7edcd867-a97c-4be5-a21a-4906d3d0276d.png)

**Comment by mikefactorial** [comment]
Closing this out as there's no action required at this time.

**Comment by rfolgadoal** [comment]
Thanks Mike! Finally I had to set as optional the Build Validation and it worked for me.
