### ISSUE TITLE
[ALM Accelerator - BUG]: ##[error]Capacity exceeds maximum capacity.  Parameter name: capacity 

### ISSUE THREAD

**Issue by HymansTesting** [microsoft/coe-starter-kit#3602]
### Describe the issue

##[error]Capacity exceeds maximum capacity. 
Parameter name: capacity 

What storage is this referring to please? As it doesn't appear to be Power Platform capacity.
![image](https://user-images.githubusercontent.com/109288908/188914297-234ae51b-b831-4787-8b65-a62a35385534.png)
![image](https://user-images.githubusercontent.com/109288908/188914252-0d16a13f-16b4-4e00-a17a-d987474c3d20.png)

### Expected Behavior

Almost 100 GB Database storage, should be no problem.
Imports manually without errors or issues.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220726.1

### Steps To Reproduce

Deploy Solution.

### Anything else?

Thanks for all the help! :)

**Comment by mikefactorial** [comment]
@HymansTesting the specific error is related to a limitation in Azure DevOps windows pipeline runner. We've made updates in the latest release to mitigate this #3250. I would recommend you upgrade to the latest https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-upgrade-config to see if this resolves the issue. Feel free to open a new issue if you find problems in the latest release.

**Comment by linujohn22** [comment]
This issue has been fixed after deploying September release .Thank you
