### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by VimmiRawat** [microsoft/coe-starter-kit#3605]
### What is your question?

We are trying to upgrade COE Starter Kit to latest version using an App ID . Earlier it was installed with another account but now we want it be imported with an App ID ; so that all notifications should go to that account . While doing the import , it fails with attached error . Though, we are using Managed solution only.
![Core_Upgrade_Issue](https://user-images.githubusercontent.com/62638075/188951872-cb98f910-a45b-4cf4-bb91-d31f4924de3b.JPG)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

All

**Comment by Jenefer-Monroe** [comment]
Please share a picture of the solutions in your CoE environment as shown below. 
Be sure to expand the name column (not display name, but name) so that I can see the full logical name. As well as the version and the managed state


![Image](https://user-images.githubusercontent.com/89584709/188974493-b22e32e0-712e-4a01-a661-00a9024884df.png)

**Comment by VimmiRawat** [comment]
![Core_Upgrade_Issue1](https://user-images.githubusercontent.com/62638075/189196563-e8755f38-7479-487d-9c6b-041514318c87.JPG)

**Comment by VimmiRawat** [comment]
![Core_Upgrade_Issue2](https://user-images.githubusercontent.com/62638075/189196919-72764c31-c7d8-4bc8-90e4-48da048d8a9b.JPG)

**Comment by VimmiRawat** [comment]
Hi Jenefer ,

I have uploaded the picture of solution as well as success import detail on GitHub.

Thanks,
Vimmi
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Thursday, September 8, 2022 2:16 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Rawat, Vimmi ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] QUESTION (Issue #3605)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________

Please share a picture of the solutions in your CoE environment as shown below.
Be sure to expand the name column (not display name, but name) so that I can see the full logical name. As well as the version and the managed state

[Image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_89584709_188974493-2Db22e32e0-2D712e-2D4a01-2Da661-2D00a9024884df.png&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=8NNRmksSBdbyV-FXj_pTSS-EX-Daf8KOdjTWJCw6zMGJU45pZs3mjhpLisGgKxg4&s=3YXuuGHSeKrs8DkyZV5ZebpxNE_NCFSJ0audz_YXYbI&e=>

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_coe-2Dstarter-2Dkit_issues_3605-23issuecomment-2D1239857428&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=8NNRmksSBdbyV-FXj_pTSS-EX-Daf8KOdjTWJCw6zMGJU45pZs3mjhpLisGgKxg4&s=Whrb25TcDxn4ZCndGCGSsPwzbb8Mq8rTFoH45G-wcKQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AO54P6YAU5EFKBUKF57QBULV5D5IBANCNFSM6AAAAAAQHAQBRI&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=8NNRmksSBdbyV-FXj_pTSS-EX-Daf8KOdjTWJCw6zMGJU45pZs3mjhpLisGgKxg4&s=p6V52foRRuujgFR6tXCFspVlOxolhw2AGKtHPl1OseQ&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by VimmiRawat** [comment]
Any update here ?

**Comment by VimmiRawat** [comment]
Hi Team,

Any update on this ?

**Comment by Jenefer-Monroe** [comment]
It looks like you tried to update on top of a kit from a year ago and the install succeeded but the uninstall of the old version failed. If you go to the history you will probably see a failure on that part
![image](https://user-images.githubusercontent.com/89584709/189697066-118d611c-0579-486c-b5b7-7180f2d488bf.png)

I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help you get starting with migrating the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Sorry we cannot be of more assistance here.

**Comment by VimmiRawat** [comment]
Hi Jenefer,

We need some advice here . Suppose , we want an App ID to be the owner of all Flows/Apps now which previously was an admin account . What is the best way/approach to configure that ?

Regards,
Vimmi

________________________________
From: Jenefer Monroe ***@***.***>
Sent: Monday, September 12, 2022 9:15 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Rawat, Vimmi ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] QUESTION (Issue #3605)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________

It looks like you tried to update on top of a kit from a year ago and the install succeeded but the uninstall of the old version failed. If you go to the history you will probably see a failure on that part
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_89584709_189697066-2D118d611c-2D0579-2D486c-2Db5b7-2D7180f2d488bf.png&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=sT23Lu1iol6EobPMSL_Ktj4CgAAiG8qjSTuVgFqoNYqx6FOJkuNmnZnLi3JKysc3&s=YTjJyKM_JTVIh5v_q7bLzC8x6w8liadZ8_5rnDkDcmc&e=>

I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see installing updates<https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.microsoft.com_power-2Dplatform_guidance_coe_after-2Dsetup-23installing-2Dupgrades&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=sT23Lu1iol6EobPMSL_Ktj4CgAAiG8qjSTuVgFqoNYqx6FOJkuNmnZnLi3JKysc3&s=3hdiOv6mfxqadRUnFa5yuRi5-aFzsvBBAEBw475avH8&e=>

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment.
Here is a write up to help you get starting with migrating the audit log data issue 1507<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_coe-2Dstarter-2Dkit_issues_1507&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=sT23Lu1iol6EobPMSL_Ktj4CgAAiG8qjSTuVgFqoNYqx6FOJkuNmnZnLi3JKysc3&s=_bf3bDwPVqhrbX-GKEaNAT5dhZI7iYxgBMZxzYgU-fs&e=>

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via AppSource<https://urldefense.proofpoint.com/v2/url?u=https-3A__appsource.microsoft.com_en_marketplace_consulting-2Dservices-3Fproduct-3Dpowerapps-26src-3Dpa-2Dm-26search-3Dcoe-26page-3D1&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=sT23Lu1iol6EobPMSL_Ktj4CgAAiG8qjSTuVgFqoNYqx6FOJkuNmnZnLi3JKysc3&s=IQTjwOPIXjHCHAVFlAsd1fyw9m-tLHbFDmhuJ1K-THM&e=>

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed.

Sorry we cannot be of more assistance here.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_coe-2Dstarter-2Dkit_issues_3605-23issuecomment-2D1243933552&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=sT23Lu1iol6EobPMSL_Ktj4CgAAiG8qjSTuVgFqoNYqx6FOJkuNmnZnLi3JKysc3&s=c8g7fr_c2_pQloQCyP-5gDDxV2oaXvrwiFNbC3wWsrA&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AO54P62GWVOSIN5XCQBDVTTV55FZZANCNFSM6AAAAAAQHAQBRI&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=sT23Lu1iol6EobPMSL_Ktj4CgAAiG8qjSTuVgFqoNYqx6FOJkuNmnZnLi3JKysc3&s=ebF7_JjXmHbhBT1nI_fA3A_1rM5cBntq_vuq2gRzWlU&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by Jenefer-Monroe** [comment]
Do you mean a service principal? The CoE Starter Kit does not yet support the ability to use a service principal to install or run it. 

If you want to migrate the flow owernship to a service account instead, you would do that as described here: [coauth and connections](https://docs.microsoft.com/power-platform/guidance/coe/limitations#co-authoring-and-connections)

**Comment by VimmiRawat** [comment]
Hey Vimmi,

Are you still facing the primary issue where the older version did not uninstall correctly? Or is your issue now with trying to use App ID (Service Principal?) for Flow/Apps ownership?


Regards,
Yash Patel

**Comment by VimmiRawat** [comment]
Hi Yash,

Primary issue is still the same . I had already upgraded the Core Component to latest but it shows two versions ( older and newer ) . That needs to be fixed.

Thanks,
Vimmi

From: Yash Patel (DYNAMICS) ***@***.***>
Sent: Wednesday, September 14, 2022 2:55 AM
To: Rawat, Vimmi ***@***.***>; microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>; Matt Gronbeck ***@***.***>; Vasavi Bhaviri Setty ***@***.***>; Ngo, Kelly ***@***.***>
Subject: RE: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] QUESTION (Issue #3605)

Hey Vimmi,

Are you still facing the primary issue where the older version did not uninstall correctly? Or is your issue now with trying to use App ID (Service Principal?) for Flow/Apps ownership?


Regards,
Yash Patel

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help you get starting with migrating the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Sorry we cannot be of more assistance here. 
Closing out as no further action for starter kit team

**Comment by VimmiRawat** [comment]
Expanding audience for visibility.

Regards,
Vimmi

From: Jenefer Monroe ***@***.***>
Sent: Monday, September 19, 2022 11:24 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Rawat, Vimmi ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] QUESTION (Issue #3605)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________

I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see installing updates<https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.microsoft.com_power-2Dplatform_guidance_coe_after-2Dsetup-23installing-2Dupgrades&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=Lw9ZUI_qszYq1L1-zoCWJzHSBIR-FYHUXeHJoAB-rMmTUkFBIFU7nRa8ozDk4UY0&s=zLJhLzebvOnDPCdX6k5_62doOXTYOfHZra7YDqpfo3k&e=>

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment.
Here is a write up to help you get starting with migrating the audit log data issue 1507<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_coe-2Dstarter-2Dkit_issues_1507&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=Lw9ZUI_qszYq1L1-zoCWJzHSBIR-FYHUXeHJoAB-rMmTUkFBIFU7nRa8ozDk4UY0&s=HabkR_5ogYGu8ZQ0a7qLxYIF61FgnzOmTj6Vz4dHwE0&e=>

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via AppSource<https://urldefense.proofpoint.com/v2/url?u=https-3A__appsource.microsoft.com_en_marketplace_consulting-2Dservices-3Fproduct-3Dpowerapps-26src-3Dpa-2Dm-26search-3Dcoe-26page-3D1&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=Lw9ZUI_qszYq1L1-zoCWJzHSBIR-FYHUXeHJoAB-rMmTUkFBIFU7nRa8ozDk4UY0&s=4obnZVq9RQonOLAGDDxW47JQR6Wd5GSiii00iiKJ-vE&e=>

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed.

Sorry we cannot be of more assistance here.
Closing out as no further action for starter kit team

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_coe-2Dstarter-2Dkit_issues_3605-23issuecomment-2D1251352205&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=Lw9ZUI_qszYq1L1-zoCWJzHSBIR-FYHUXeHJoAB-rMmTUkFBIFU7nRa8ozDk4UY0&s=NriXcnWmYpV6x5AihnK1ntvTgCBPpjRZ28WefxvJ5zM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AO54P6427XKB6ONDFORZLT3V7CSE7ANCNFSM6AAAAAAQHAQBRI&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=Lw9ZUI_qszYq1L1-zoCWJzHSBIR-FYHUXeHJoAB-rMmTUkFBIFU7nRa8ozDk4UY0&s=dDXuIlcQG-6L8Gq_Uy3KJqs4xWhISwJQfNVi_zquZtQ&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by VimmiRawat** [comment]
+ Yash, Matt, Vasavi, Kelly
________________________________
