### ISSUE TITLE
[CoE Starter Kit - BUG] Admin - Command Center error message when viewing CoE Flows

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#3606]
### Describe the issue

After upgrading to the Sept release of the kit, when I open the Admin - Command Center App and select the node for viewing the CoE Flows, I get an error message at the top of my screen like this:
![image](https://user-images.githubusercontent.com/41799380/188956126-c56c9f4a-afbc-46cf-990d-3ed72b73657e.png)

I assume it's important or I wouldn't be seeing this error, but am not really sure what's missing.

### Expected Behavior

No errors when clicking on the screen,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

1. Open the app
2. Click on CoE Flows

**Comment by Jenefer-Monroe** [comment]
You need to go and run this flow before the app will work again. We shifted some things for an upcoming setup app. 
**_Admin | Sync Template v3 CoE Solution Metadata_**

**Comment by bartsneary** [comment]
That did the trick!

**Comment by Jenefer-Monroe** [comment]
Thank you for letting me know!
