### ISSUE TITLE
[ALM Accelerator - Feature]: Move to using import-data task

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#3608]
### Describe the solution you'd like

Once the import-data task is published to marketplace, cleanup technical debt in our pipelines.
https://github.com/microsoft/powerplatform-build-tools/tree/davidjen/augRefresh/src/tasks/import-data/import-data-v2

Move from using PowerShell to calling task.

**Comment by mikefactorial** [comment]
This has been completed and will be closed.
