### ISSUE TITLE
[CoE Starter Kit - BUG] Error on import of CenterofExcellenceCoreComponents_3.44_managed.zip into DoD IL5 Environment

### ISSUE THREAD

**Issue by DevonAleshire** [microsoft/coe-starter-kit#3609]
### Describe the issue

Tried to install current version (3.44) of CoE starter kit multiple times in a DoD IL5 production environment and received the error below on import:

_The dependent component Workflow (Id=86721ee7-cb7e-ec11-8d21-002248320bcd) does not exist.  Failure trying to associate it with CanvasApp (Id=ec1e536e-6228-44a5-a02b-db7d0c7d461e) as a dependency. Missing dependency lookup type = PrimaryKeyLookup_

I was able to successfully install previous version 3.40 without issue using inventory installation instructions.

Screenshots of errors:

![Screenshot 2022-09-07 141753](https://user-images.githubusercontent.com/7697694/188982885-aa6e3d25-2efb-4073-8869-7a23ea0cc16a.png)

![Screenshot 2022-09-07 141815](https://user-images.githubusercontent.com/7697694/188982936-2b25a179-f70a-4dba-9583-8b3fd8d56c10.png)

### Expected Behavior

The CoE Core Components version 3.44 should import without error into DoD IL5 production environment 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

Unsure. Error on Import of CoE Core Solution - component Workflow (Id=86721ee7-cb7e-ec11-8d21-002248320bcd) does not exist

### Steps To Reproduce

1. Create all required connections and prepare environment variable information.
2. Import CenterofExcellenceCoreComponents_3.44_managed.zip

**Comment by manuelap-msft** [comment]
Hello, it looks like we had an issue with 3.44 where a flow triggered from a canvas app wasn't exported with the solution - in our US environment the solution imported fine and only the canvas app failed to run, but looking at your error message it seems that this may be the issue the import failed altogether. Here's a hotfix release with a new version 3.45 for you to try:
https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2022/CenterofExcellenceCoreComponents_3.45_managed.zip

Hopefully that fixes your import issue!

**Comment by DevonAleshire** [comment]
Hi @manuelap-msft version 3.45 imported successfully. I will close this issue. 

Thank you very much for the assistance!

**Comment by manuelap-msft** [comment]
Great, thanks for letting us know!
