### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION about the "Set App Permissions" app.

### ISSUE THREAD

**Issue by jbst2018** [microsoft/coe-starter-kit#3610]
### What is your question?

I have a question about the "Set App Permissions" app.

Is it possible to set the owner for model-driven apps with the "Set App Permissions" app?

From the screen, it seems that only canvas apps can be done.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Set App Permissions

**Comment by manuelap-msft** [comment]
Hello, the Set App Permission app only supports canvas app today, that's correct. Here's a blog post with more info on updating app ownership that also covers the topic of model driven apps: https://powerapps.microsoft.com/en-au/blog/updating-ownership-for-power-apps-apps/

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
