### ISSUE TITLE
[CoE Starter Kit - BUG] Issue with Admin | Sync Template v3 (Flow Action Details)

### ISSUE THREAD

**Issue by kruthihegde11** [microsoft/coe-starter-kit#3614]
### Describe the issue

Flow Name:  Issue with Admin | Sync Template v3 (Flow Action Details)

Error message : The 'inputs.parameters' of workflow operation 'Get_environment_for_name' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'

Description: Installed COE solution a couple of weeks ago. Since then, Everyday a couple of new  records get added in Flow table  (with most of the fields empty) which throws the above error message from the flow. In the flow record, flow pending suspension reason is recorded as MissingPremiumLicense. But I cannot find this flow and they are not associated with any environments (The error is mainly because the environment Id is empty).

However, these flow records are deleted by clean up flows. 
Screenshots below:

![Abandoened records view](https://user-images.githubusercontent.com/112558856/189181049-99afaf69-9b8e-4226-a3b7-fdc92b6c56be.PNG)
![Flow record with suspension reason](https://user-images.githubusercontent.com/112558856/189181082-bf203199-b789-4948-89f6-1ff60b78ae51.PNG)
![Error Message](https://user-images.githubusercontent.com/112558856/189181118-b8730ca1-a85f-475c-bee0-157639e243e4.PNG)

I see a similar issue here https://github.com/microsoft/coe-starter-kit/issues/2219
However I have installed version 3.41 but has not fixed my issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

 Admin | Sync Template v3 (Flow Action Details)

**Comment by Jenefer-Monroe** [comment]
Hello. I'm having a little trouble following you as I think there may be issues with your inventory way before this flow action details flow runs. So lets pop up a level. 

Can you please confirm that you have all the flows in the [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) turned on and running? 
In particular, do you have the **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_** running?

My suggestion is to please run that clean up flow, then open the Power Platform Admin View app. Let's see what your environments and flows look like

**Comment by kruthihegde11** [comment]
Hi Jenefer, Thanks for your reply.

Yes, all the flows in the inventory set up are running,  the **CLEANUP - Admin | Sync Template v3 (Delete Bad Data)** runs everyday. It is cleaning up the bad data. But again next day, such records get created in flow table, throws error and gets deleted by CLEANUP - Admin | Sync Template v3 (Delete Bad Data). This repeats everyday.

**Comment by Jenefer-Monroe** [comment]
I've never seen this before. So I'm curious and also stumped.
Your form for the flow does not seem to have all the fields we have in our currently shipped. Can you please check for unmanaged layers on it, and on the sync flows in Core? 
If finding / removing those do not bring back the flow id sting (see below) then also please export the data from the Flows table. We need to find the GUID of the flows that are impacted by your issue
![image](https://user-images.githubusercontent.com/89584709/189430796-f1b7e6e9-29fb-40a0-a3bc-fd2a34070898.png)

**Comment by kruthihegde11** [comment]
I am not able to find these flows anywhere, even the environment is empty.
There are no unmanaged layers on any of the Sync flows. 
I am attaching the input and output of the flow for reference.

![Inputs](https://user-images.githubusercontent.com/112558856/189654381-fcfbfee1-39ab-478a-8fe9-21a8c2a756a4.png)
![Output](https://user-images.githubusercontent.com/112558856/189654479-2bce6ced-7fb4-446e-979f-786b11c7557f.png)

**Comment by Jenefer-Monroe** [comment]
When you say Environment is empty, do you mean the value returned here is empty? 
You have the flowid there, please go to the Power Platform Admin View and look it up:

![image](https://user-images.githubusercontent.com/89584709/189670144-786a192b-462d-4b44-8088-aff13b7338b6.png)

**Comment by kruthihegde11** [comment]
The output shows the value for admin_flowid. But when the record is created in data verse, the field is empty.
You can see all values are empty in the screenshot.
![image](https://user-images.githubusercontent.com/112558856/189705598-cda5363c-becd-4516-bf57-4a4a745956e8.png)

I meant to say flow environment is null:
![image](https://user-images.githubusercontent.com/112558856/189707503-fce14236-daf7-4a45-9490-eb0af523ccb6.png)

**Comment by Jenefer-Monroe** [comment]
You are on a new flow there. Not on an existing flow. Can you please change your filter from Abandoned Flows to Active flows and try to find the flow? 
![image](https://user-images.githubusercontent.com/89584709/189711471-4c3796ca-bc4f-4ad0-b83b-6009e1964710.png)

**Comment by kruthihegde11** [comment]
I am not on a New flow, since the Name of the flow is null, its showing as New flow. but it is saved in my dataverse and the error is thrown by the flow. Also If you check, the system doesn't display us 'New' button for the flow entity, so we cant created one manually.


Even from active flows, I don't find the record with that flow id that I see in the output parameters of the cloud flow. Instead those records are empty.

![image](https://user-images.githubusercontent.com/112558856/189836344-a259c142-8b59-4f8a-a476-160f07a1a4f4.png)

**Comment by Jenefer-Monroe** [comment]
I'm afraid I have no idea how you got into this state and have never seen this before. Do any flows show up correctly?

**Comment by kruthihegde11** [comment]
Everyday there are around 5 empty records that are created, throws error and gets deleted by clean up flow. This is the story with only 5 flow records, I have more than 3000 flows which are perfectly created in flows table.

**Comment by Jenefer-Monroe** [comment]
The only think I can think to try is
1. Turn off delete bad data (so we dont get cleaned up accidently, you'll need to turn it all back on when we're done)
2. Delete these 5 records from the flow table
3. Go through the environments one by one to see when these get added by editing them as shown here
![image](https://user-images.githubusercontent.com/89584709/189979269-781ac3d8-bb56-436d-80ff-b8997c9502d3.png)
4. Which will cause the sync flow to run for just that environment
![image](https://user-images.githubusercontent.com/89584709/189980934-bd7588ae-adc0-4b53-a35b-00a4e7fb061b.png)
5. After it completes, see if they were added, repeat till you find a repro

Then we'll know at least which envt's are adding them. We can go from there.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by animta** [comment]
Hi Jenefer,

I am also experiencing the same failure mentioned above.

**Comment by javiercheke** [comment]
Hi, this error appears when the owner of the flow have the account disable in AAD.

Check the flowid and after this check the ownerid in AAD, in my case every flow even the shared flows have a disabled user.
