### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inventory flows turned off for a period

### ISSUE THREAD

**Issue by FlowHawk** [microsoft/coe-starter-kit#3615]
### What is your question?

The CoE Start Kit was installed in April 2022 with an account that had password expiration. Sometime in the next month or so the password expired and flows didn't run for a few months. Now we are trying to get everything functional with a non-expiring account.

Many of the flows are failing with "not found" on the lookups and there is missing metadata in the tables (for example there are hundreds of flows that don't have a value in the "Flow State" column).

My question is, should I be trying to chase each one of these errors down? Or am I better of just wiping the tables and performing a full re-inventory? I just don't want to lose any data that we have. Are you aware of any major issues if the inventory flows aren't run for an extended period?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2022

**Comment by Jenefer-Monroe** [comment]
Full inventory does not wipe out any personalized data, it just re-adds all the apps/flows/etc regardless if they were modified since their last time put onto inventory. So it sounds like the perfect solution for you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
