### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION Where are the Deployment Instructions for Admin Planning tool 

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#3616]
### What is your question?

Where are the deployment instruction for the CoE Admin Planning Tool ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2022 3.22

### What app or flow are you having the issue with?

Admin Planning Tool

**Comment by manuelap-msft** [comment]
In our documentation, here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-admin-tasks-component

And further info on how to use the tool https://docs.microsoft.com/en-us/power-platform/guidance/coe/admin-tasks-component

**Comment by NPrice99** [comment]
Thanks Manuela

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
