### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Sync Template V3 (Connection Identities) Error

### ISSUE THREAD

**Issue by subhasishmukhopadhyay** [microsoft/coe-starter-kit#3617]
### Describe the issue

The respective flow is failing in Default environment

**Error Text**
BadRequest: The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '209788831' bytes. This exceeded the maximum size '209715200' bytes allowed.

**Screen shot**
![image](https://user-images.githubusercontent.com/53398533/189192019-90b95849-4995-4cb2-b4ed-6caf97bec9d6.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Admin Sync Template V3 (Connection Identities)

### Steps To Reproduce

Please follow the screen shot above.

**Comment by manuelap-msft** [comment]
This is a documented limitation with a solution to address this via PowerShell posted in our documentation: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#set-up-connection-cleanup-broken-connections

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
