### ISSUE TITLE
[CoE Starter Kit - BUG] Rename CenterofExcellenceAuditComponents_x.xx_managed.zip file to CenterofExcellenceGovernanceComponents_x.xx_managed.zip

### ISSUE THREAD

**Issue by Chris-WP** [microsoft/coe-starter-kit#3620]
### Describe the issue

The filename of the CenterofExcellenceAuditComponents_2.20_managed.zip file often causes confusion for new adopters that are installing the CoE Starter Kit for the first time.

The file often gets confused with the "CenterofExcellenceAuditLogs_2.10_managed.zip" file.  Also, adopters often go looking for a file with the words "governance components" in the filename when doing the import for the first time.

It would be helpful to rename the file to "CenterofExcellenceAuditComponents_2.20_managed.zip" to "CenterofExcellenceGovernanceComponents_2.20_managed.zip". This is especially the case as the solution name is "Center of Excellence - Governance Components".

### Expected Behavior

The filename of the "Center of Excellence - Governance Components" should be called "CenterofExcellenceGovernanceComponents_2.20_managed.zip" so it is easier to find and more intuitive.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Sep 2022

### What app or flow are you having the issue with?

Setup Package

### Steps To Reproduce

1. Open the downloadable zip file containing the CoE Starter Kit solution files
2. Expect to see a file named "CenterofExcellenceGovernanceComponents_2.20_managed.zip" rather than "CenterofExcellenceAuditComponents_2.20_managed.zip"

**Comment by manuelap-msft** [comment]
For many historic reasons (and because naming is hard), the internal name of the solution is CenterofExcellenceAuditComponents and on export the name of the solution .zip file is auto generated based on the internal name
![image](https://user-images.githubusercontent.com/55705669/189349806-83e9a2d0-11b8-49f8-8edf-1cb5df12c97d.png)

We'll investigate if we can update the name in our deployment process before shipping.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
