### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3

### ISSUE THREAD

**Issue by viniciuscoelho** [microsoft/coe-starter-kit#3621]
### Describe the issue

Fresh install. The Admin | Sync Template v3 flow is receiving the error:

The 'inputs.parameters' of workflow operation 'Update_Last_Run_Successful' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'

Screenshot:
![image](https://user-images.githubusercontent.com/32205091/189267630-2590cc9c-5c1a-4de4-8861-a8d07590ec3d.png)

ps. I'm receiving the same error for CLEANUP - Admin | Sync Template v3 (Delete Bad Data) flow

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

Fresh install following official guide https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup

**Comment by manuelap-msft** [comment]
Have you turned on and run this flow **Admin | Sync Template v3 CoE Solution Metadata**?

**Comment by viniciuscoelho** [comment]
Hi Manuela,
 It's turned on, but there is no run. I'm running this flow and will post the results here. Thanks!

**Comment by viniciuscoelho** [comment]
Hi Manuela, 
 After running Admin | Sync Template v3 CoE Solution Metadata flow, all the other flows are running without any error. Thanks!!
