### ISSUE TITLE
[CoE Starter Kit - BUG] WRONG FLOW DESCRIPTION BROKEN CONNECTION CLEANUP

### ISSUE THREAD

**Issue by WinOnMarco** [microsoft/coe-starter-kit#3625]
### Describe the issue

The description of the flow "Admin | Broken Connection Cleanup" is wrong. The current description is "Runs weekly and deletes **connection references** that are errored out and which were last modified at least 30 days ago (configurable)."

This flow does not delete connection references.

### Expected Behavior

The description should be: Runs weekly and deletes **connections** that are errored out and which were last modified at least 30 days ago (configurable).

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.20

### What app or flow are you having the issue with?

Admin | Broken Connection Cleanup

### Steps To Reproduce

Open Flow details and read the description.

**Comment by Jenefer-Monroe** [comment]
The issue is with the flow not the description. Something got corrupted. Fixing via https://github.com/microsoft/coe-starter-kit/issues/3626
please track fix there. thanks for posting.
