### ISSUE TITLE
[CoE Starter Kit - BUG] Reset flows from Admin - Command Center is failing

### ISSUE THREAD

**Issue by larhem** [microsoft/coe-starter-kit#3626]
### Describe the issue

After changing "fillinventory" variable to Yes in Admin - Command Center i select "Reset Flows".
Error is given on screen saying that it cant trigger the workflow "CommandCenterApp>GetCoEFlows.

![image](https://user-images.githubusercontent.com/91886096/189292213-ca652aab-543a-4289-b280-10e1030dae9a.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by manuelap-msft** [comment]
Can you check if you have unmanaged layers on the Admin - Command Center app
![image](https://user-images.githubusercontent.com/55705669/189351010-98e1cf8c-a419-4c16-bf83-4fc734623c18.png)

**Comment by larhem** [comment]
I should have added that to the issue, but first thing i checked both on that app and on the "Command Center App > Set CoE Flows State" flow was if there was any unmanaged layers. And none of them had that.
Only thing in that solution having unmanaged layers is two of the environment variables.

**Comment by Jenefer-Monroe** [comment]
Somehow the flow got lost from the package. We are creating a new solution to release.

**Comment by manuelap-msft** [comment]
New version is now available: https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2022/CenterofExcellenceCoreComponents_3.45_managed.zip

**Comment by larhem** [comment]
Upgraded and its working now. Thank you :)
