### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Broken Connection Cleanup deletes active connections

### ISSUE THREAD

**Issue by WinOnMarco** [microsoft/coe-starter-kit#3627]
### Describe the issue

Active Connection falsely deleted from "Admin | Broken Connection Cleanup". Even Connectors with Status "Connected" get deleted!

There's a typo in the filter action "Filter to Errors"

### Expected Behavior

The new workflow "Admin | Broken Connection Cleanup" from September Release should only delete broken connections which were last modified at least 30 days ago.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.20

### What app or flow are you having the issue with?

Admin | Broken Connection Cleanup

### Steps To Reproduce

1. Create a Connection for a custom connector
2. Wait 30 days or remove the date filter in this flow
3. Run "Admin | Broken Connection Cleanup"
4. The connector from the custom connector will be deleted

### Anything else?

<img width="437" alt="image" src="https://user-images.githubusercontent.com/99335718/189296305-098b7a07-e32a-44cc-b948-b699ee9b664a.png">

**Comment by Jenefer-Monroe** [comment]
Thank you for posting. I dont know what happened to that expression but I am creating a new package now

**Comment by manuelap-msft** [comment]
Due to the impact of this change, we've released a new version as a hotfix to address this immediately before other customers get impacted - here's the new version
https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-September2022/CenterofExcellenceAuditComponents_2.21_managed.zip

Thank you for raising this!
