### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Audit Logs connection

### ISSUE THREAD

**Issue by Nass92700** [microsoft/coe-starter-kit#3628]
### Describe the issue

the flow "Admin | Sync Audit Logs" dont success and get this error on the step run child flow  : 

Failed to parse invoker connections from trigger 'manual' outputs. Exception: Could not find property 'headers.X-MS-APIM-Tokens' in the trigger outputs. Workflow has connection references '["shared_admin-5foffice-20365-20management-20api-5f7fc9343cf45734fe"]' with invoker runtime source.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Steps To Reproduce

run the Admin | Sync Audit Log

### Anything else?

![Capture d’écran 2022-09-09 100705](https://user-images.githubusercontent.com/113169835/189303106-fdc5d470-6431-4bdc-aee6-3c87422b35ab.jpg)

**Comment by manuelap-msft** [comment]
Have you followed Step 7-9 here to set the run only user configuration of the Child Flow:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

Can you navigate to make.powerapps.com > Dataverse > Connections and does the connection to the Audit Log custom connector look broken there? If it does, please follow these steps to re-authenticate https://github.com/microsoft/coe-starter-kit/issues/1424

**Comment by Nass92700** [comment]
Hello,

I made an update of the custom connector and set "run only user" to tne connextion of the child flow, and its working well.

Thank you

**Comment by Jenefer-Monroe** [comment]
Thanks for letting us know!
