### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin Task Planner starter data

### ISSUE THREAD

**Issue by fvhamel** [microsoft/coe-starter-kit#3632]
### What is your question?

Hi,

Just saw the Admin Task Planner video. Great!

Imported it in my Solutions but can you just tell me where I can find the Power BI .pbix & the data for uploading the tasks?

Kind regards,
Frank

### What solution are you experiencing the issue with?

Governance

**Comment by manuelap-msft** [comment]
Hello,

if you download the CoE kit package via https://aka.ms/coestarterkitdownload this download a .zip file of all our solutions - when you unzip that, you'll find the solution, starter data, and Power BI file in the folder
![image](https://user-images.githubusercontent.com/55705669/189346021-91243a33-6083-41ef-b986-25bf17418a12.png)

The setup instructions are here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-admin-tasks-component

**Comment by fvhamel** [comment]
Hello Manuela,

Great, works fine 😉. Have a wonderful weekend.

Kind regards,
Frank

**Comment by manuelap-msft** [comment]
Wonderful, thanks for confirming!

**Comment by fvhamel** [comment]
Hi Manuela,

When loading my Power BI desktop report and the .pbit provided I get following error.

I just linked to my PowerApps environment with the environment URL (without the ‘Https://’).

***@***.***

**Comment by manuelap-msft** [comment]
Hello,

images unfortunately do not come through when you respond to an issue via eMail - you'll have to select "View on GitHub" and upload the image from there (copy and pasting it into the text box when you respond works)
