### ISSUE TITLE
[CoE Starter Kit - Feature]: Please rename file CenterOfExcellenceAuditComponents_...,zip

### ISSUE THREAD

**Issue by txh57** [microsoft/coe-starter-kit#3633]
### Is your feature request related to a problem? Please describe.

Every time, when I update the **CoE StarterKit**, the first thing I do is compare the version numbers of the StarterKit with those of the installed solutions.
And every time it confuses me that the _CenterofExcellence**Audit**Components_...zip file belongs to the _Center of Excellence - **Governance** Components_ solution.

### Describe the solution you'd like

It would be great if the **CoE StarterKit** file could be renamed to _CenterofExcellence**Governance**Components_...zip.

**Comment by manuelap-msft** [comment]
closing as duplicate of #3620
