### ISSUE TITLE
[CoE Starter Kit - Feature]: Drilldown in Governance Dashboard

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#3635]
### Is your feature request related to a problem? Please describe.

It would be very useful to have the ability to drill into the Complience and Governance Dashboard so you can see additional details.

### Describe the solution you'd like

Clicking on the "Apps with no owners" card provides a list of all app names with no owners as well as details such as created date etc, etc, etc and maybe a link to the app

**Comment by manuelap-msft** [comment]
That is possible today - if you right-click on a card you can select Drillthrough > App Detail / Flow detail which then gives you a list of all the apps/flows that fit that criteria. Is this not working for you? In Power BI, the drill through works via right-click.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
