### ISSUE TITLE
[CoE Starter Kit - BUG] TDS Ports not open to setup Admin Tasks Dashboard

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#3636]
### Describe the issue

When creating the PowerPlatformAdminPlanner.pbit, I get the following error - 
![image](https://user-images.githubusercontent.com/8484048/189324525-f4256533-215e-46e4-b5ee-336976518616.png)

There is no mention of needing a SQL Server for this Dashboard

### Expected Behavior

I was hoping the dashboard would be displayed

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

 PowerPlatformAdminPlanner.pbit,

### Steps To Reproduce

In Power BI Desktop, open the file PowerPlatformAdminPlanner.pbit, which can be found in the CoE Starter Kit you downloaded and extracted.

Enter the URL of the environment where you imported the solution.

**Comment by shanemeisnerdhg** [comment]
Seeing the same issue here.

**Comment by manuelap-msft** [comment]
How have you entered the URL when connecting to Power BI? 

This error typically occurs if you have entered the URL including the https and trailing slash, see our Troubleshooting guidance here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting

**Comment by NPrice99** [comment]
Hi Manuela

![image](https://user-images.githubusercontent.com/8484048/189343484-886ce8f4-23a3-4794-8dca-3043b7b938f7.png)

![image](https://user-images.githubusercontent.com/8484048/189343774-259b7342-5d5a-4375-97b9-31005eadb8f6.png)

I dont have a SQL Server in this environment and there was nothing about requiring a SQL Server in the installation instructions.

Regards

Nigel

**Comment by manuelap-msft** [comment]
Please remove the trailing / from the URL.

SQL is not required. We are using the Tabular Data Stream (TDS) endpoint that emulates a SQL data to connect to Microsoft Dataverse. You can learn more about the TDS endpoint here https://docs.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query

**Comment by NPrice99** [comment]
![image](https://user-images.githubusercontent.com/8484048/189344729-f98327fd-6367-4776-b423-4b350267f6cb.png)
 Same error

**Comment by manuelap-msft** [comment]
Is the TDS endpoint enabled for this environment?

**Comment by shanemeisnerdhg** [comment]
I also entered our OrgUrl without trailing slash and without http.. same results. 

and yes, TDS End point is enabled

**Comment by NPrice99** [comment]
TDS EndPoint is switched on - 
![image](https://user-images.githubusercontent.com/8484048/189347489-594938bd-e880-4aeb-904d-8e82106788be.png)

**Comment by stjeffer** [comment]
Hey.

I can't repro this - I've tried on four different environments.  I've only seen this issue when there is a pre/suffix in the URL. Did you try manually typing in the URL to rule out any copy/paste/white space issues?  Have you tried connecting a blank Power BI dashboard to the environment? Have you tried in another environment?

We have some [troubleshooting tips/ steps](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting) documented that might be of use, but I would also recommend raising a case with Microsoft Support in case something else is happening in your environment.

**Comment by NPrice99** [comment]
WIth TDS Endpoint enabled -

Test-NetConnection -ComputerName orgXXXXXXXXX.crm11.dynamics.com -port 1433
WARNING: TCP connect to (XX.XXX.XX.XXX: 1433) failed
WARNING: Ping to XX.XXX.XX.XXX: failed with status: TimedOut

ComputerName           : orgXXXXXXXX.crm11.dynamics.com
RemoteAddress          : XX.XXX.XX.XXX
RemotePort             : 1433
InterfaceAlias         : Ethernet 2
SourceAddress          : XX.XXX.XX.XXX
PingSucceeded          : False
PingReplyDetails (RTT) : 0 ms
TcpTestSucceeded       : False

How can I check if the port is open or not ?

**Comment by manuelap-msft** [comment]
There's some additional troubleshooting steps available on the Power BI site
https://docs.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query#blocked-ports

It's a network configuration - we're unfortunately not network experts, so don't know how to open these ports.

**Comment by shanemeisnerdhg** [comment]
> 

The other PowerBi's that come with the CoE are working in our CoE environment without any issues. I'll review the links provided to see if anything points to why this one is failing.

**Comment by shanemeisnerdhg** [comment]
@stjeffer - Tried manually entering the Org URL, using two different accounts to run PowerBI with the same error. 
A
s I mentioned above, the other PowerBi dashboards that come with the CoE are working whiteout issues inside the same environment.

**Comment by manuelap-msft** [comment]
There's different ways to connect to Dataverse in Power BI, one using the TDS endpoint and one using the legacy CDS connector. You can learn more about that here
https://docs.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-powerbi-connector?tabs=Dataverse#connect-to-dataverse-using-a-connector

The other dashboards in the CoE, as they're older, still use the Legacy connector. This new dashboard uses the Dataverse connector with the TDS endpoint.

If you're having issues with this dashboard
1. Either the TDS endpoint is not enabled
2. Or ports to connect to TDS are blocked

**Comment by NPrice99** [comment]
Hi @manuelap-msft 
I think we all have made sure that 1) is not the issue.
So it must be 2) so its a case of finding out how to unblock the ports.  Unfortunately we are all probably PowerPlatform whizzes and not SQL Server Network gurus.
SO its a case of finding someone who can unblock SQL Server ports.
Perhaps a support call ?
I unfortunately do not have access to premier support anymore.
Regards

Nigel

**Comment by manuelap-msft** [comment]
It's a network setup on your side, so support won't be able to unblock those ports but they may be able to tell you how to do it.

**Comment by NPrice99** [comment]
Perhaps the documentation should be updated to include the steps to be taken to open these ports

**Comment by shanemeisnerdhg** [comment]
Just ran a test here and port 1433 is currently blocked. I'll work with our Network team to see about opening it.

I'll report back once I am able to get the port opened.
I agree that the documentation needs to be updated to reflect what is needed.

**Comment by PlanetWilson** [comment]
In corporate environments it is highly unlikely that security would allow unfettered 1433 traffic out of the firewall onto the internet? Are there plans to make this a HTTPS endpoint at some point? Also who would normally expose SQL directly like that?

**Comment by manuelap-msft** [comment]
We are just using a feature / connector in Power BI here, but don't have influence on the product feature itself - for product feedback, please use: https://powerusers.microsoft.com/

**Comment by VeerasekarVM** [comment]
I get the same type of error even using 'yourenvironmentid.crm.dynamics.com:5558'. In COE toolkit all other PBI reports works retrieving data from Dataverse tables from the same environment, i preassume the functionality is same here in this 'Admin Tasks Dashboard' as well but why it uses this TDS??

![Capture](https://user-images.githubusercontent.com/61466876/190580369-7e8f11c6-90b1-420a-b48a-4149690dff92.JPG)

**Comment by manuelap-msft** [comment]
The TDS endpoint is the recommended and newer connector, the old connector has been marked as Legacy and it is only recommended to use it when the query results will be greater than 80 MB. For other CoE dashboards, we expect larger query results and therefore still use the legacy connector.

**Comment by NPrice99** [comment]
I agree that In corporate environments it is highly unlikely that security would allow unfettered 1433 traffic out of the firewall onto the internet. This needs to be a https endpoint before security would go anywhere near it. There must be a more secure way of achieving this.  I know this is not your fault @manuelap-msft so I am not blaming / having a go at you, but I think someone needs to give the product group this feedback.  I wonder whether there was a focus group about this as it seems a pretty obvious problem for most enterprises.

**Comment by NPrice99** [comment]
I have posted about this on the community.powerbi.com (aka powerusers.microsoft.com) board.  Lets see if there are any product team members lurking and if they respond.

**Comment by shanemeisnerdhg** [comment]
Note - Port 1433 only needs to be opened temporarily to build the dashboard in Power BI Desktop. 
After you build it locally, and publish it out to Power BI, you can have them close the port.
I sent the firewall team my PC's IP address and the address I was trying to connect to. Once they opened the port for me I was able to connect to the data, save my Dashboard and publish it. 
Once published I was able to view the data without any issue.

**Comment by NPrice99** [comment]
Yes - that what my friendly PowerBi expert said - it was only for creating the Dashboard.  That is going to be a bit of a faff every month when a new version of the CoE comes out.

**Comment by manuelap-msft** [comment]
Closing out as no further action for the CoE kit team required.
