### ISSUE TITLE
[CoE Starter Kit - BUG] Helper - Maker Check disabled

### ISSUE THREAD

**Issue by eddwr1** [microsoft/coe-starter-kit#3638]
### Describe the issue

Hi,

We are experiencing an issue with the flow 'Admin | Sync Template V3'.

This may be an issue with our configuration/install, but I'm not sure where to begin investigating properly.

Below are some screenshots of the most recent flow run, which I hope can help shed some light:

![image](https://user-images.githubusercontent.com/97225231/189335814-1e2a98da-0723-482d-9589-b77f01f39c13.png)

![image](https://user-images.githubusercontent.com/97225231/189335837-1306f63f-f33d-4b7d-9d97-8e14364e4815.png)

![image](https://user-images.githubusercontent.com/97225231/189335858-07318763-927a-4088-beb6-da4adb307157.png)

![image](https://user-images.githubusercontent.com/97225231/189335873-b8ec64f6-af9e-4239-8125-080e305d2dda.png)

Please let me know if there is any other information I can include that might help, or if there is anything you would recommend I should look at that might help to resolve the issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

 Admin | Sync Template v3

### Anything else?

Text from errored Get Maker step:

x-ms-ratelimit-burst-remaining-workflow-writes
499
x-ms-ratelimit-remaining-workflow-download-contentsize
35790848
x-ms-ratelimit-remaining-workflow-upload-contentsize
35790763
x-ms-ratelimit-time-remaining-directapirequests
3333332
x-ms-request-id
uksouth:3abec104-7dd0-4e4f-8114-2b6fc78a651e
Strict-Transport-Security
max-age=31536000; includeSubDomains
Content-Type
application/json; charset=utf-8
Content-Length
190

{
  "error": {
    "code": "WorkflowTriggerIsNotEnabled",
    "message": "Could not execute workflow '4547553b-4cdd-09eb-291b-129935ffc687' trigger 'manual' with state 'Disabled': trigger is not enabled."
  }
}

**Comment by NPrice99** [comment]
Get Maker calls a Child Flow HELPER - maker check which I suspect is turned off

**Comment by manuelap-msft** [comment]
Make sure all the child flows listed here are turned on: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows

I suspect like @NPrice99 said that HELPER - maker check is turned off in your case.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by eddwr1** [comment]
Hi all,

Thank you for your help. You were correct that the flow HELPER - maker check was turned off, which resolved the issue!

**Comment by Jenefer-Monroe** [comment]
thanks for letting us know!
