### ISSUE TITLE
[BUG]: GCC High Tenant: Power BI Desktop - Import a Power Platform environment URL Error

### ISSUE THREAD

**Issue by yearwoodm15** [microsoft/coe-starter-kit#364]
**Describe the bug**

Hello, when trying to import a GCC High Power Platform environment URL to my Power BI Desktop app I am getting the following error: Details: "Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)" We were able to confirm that we have SQL Server, however we are not sure why this is happening. The effort is in junction with completing the Microsoft Center of Excellence. We are using the Dashboard-PowerPlatformAdminDashboard-2021-04-08.pbit file to attempt to import the environment so we may view Power Platform environments & analytics. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [2.0.10]

**To Reproduce**
1. Go to [download](https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Faka.ms%2Fcoestarterkitdownload&data=04%7C01%7Cmatthew.yearwood%40accenturefederaldefense.com%7Cd7170e4ffd5f4ef45b2308d916607ee9%7Ca01f407a85cb4a1698bbf28e6384bd28%7C0%7C0%7C637565425991322305%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D8z4pefS7F5M32PuJuJQmdZTDOThjka1keLNMSd%2F98c%3D&reserved=0) area of MSFT documentation.
2. Click on Dashboard-PowerPlatformAdminDashboard-2020-11-24.pbit file from CoE folder
3. Load GCC High environment
4. See error listed in description

**Expected behavior**
The environment should be able to successfully import to the Power BI Desktop application as it does on the Commercial side.

**Screenshots**
<img width="387" alt="GCCH Power BI Desktop Error" src="https://user-images.githubusercontent.com/83036044/118315686-d334b000-b4c3-11eb-992b-ec7c8218cd8a.png">

**Additional context**
Question, is this supported in GCC High yet? If not, is there a roadmap for when this may be rolled out if applicable?

**Comment by JeneferM-MSFT** [comment]
We are tracking this issue with #341 

Can you please try using this old version of the PBI while we work through the issues with the new direct query version? 
[Feb Version of PBI](https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-02-02%20(1).pbit)

Note that you will need to enter the org url with the prefix included as shown here: https://yourcoe.crm.dynamics.com

Thanks for helping make CoE great.

**Comment by yearwoodm15** [comment]
Hi Jenefer,

Thank you for this information. I wanted to let you know that I removed https:// from the equation and it successfully imported, per the other threads suggestion. I did not need to use the old PBI version. Thanks again!
