### ISSUE TITLE
[CoE Starter Kit - BUG] CommandCenterApp>InitiallyPopulateBookmarks.Run failed

### ISSUE THREAD

**Issue by fredrikhr** [microsoft/coe-starter-kit#3648]
### Describe the issue

When launching the `Admin - Command Center` canvas app, the initial screen showing the bookmarks is empty and an error banner is displayed stating

> CommandCenterApp>InitiallyPopulateBookmarks.Run failed: Connection not configured for this service.

I then went into PowerApps and selected `Monitor` on the app's context menu. With the monitor open, I then selected the `Play published app` command.

The app starts and launches two `Install` api function invocations which both fail:

### Request

```json
{
  "url": "https://<coe-environment>.crm4.dynamics.com//api/data/v9.0/workflows(86721ee7-cb7e-ec11-8d21-002248320bcd)/Microsoft.Dynamics.CRM.install",
  "method": "POST",
  "headers": {
    "x-ms-client-session-id": "...",
    "x-ms-client-request-id": "...",
    "x-ms-user-agent": "PowerApps/3.22085.9 (Web; Player; isReactNative: false)",
    "Request-Id": "...",
    "Client-Session-Id": "...",
    "x-ms-app-id": "...",
    "Accept-Language": "en-US",
    "Accept": "*/*",
    "Content-Type": "application/json"
  },
  "body": {
    "connectionReferences": {
      "shared_flowmanagement": {
        "connectionName": "...",
        "id": "/providers/microsoft.powerapps/apis/shared_flowmanagement"
      },
      "shared_commondataserviceforapps_1": {
        "connectionName": "...",
        "id": "/providers/microsoft.powerapps/apis/shared_commondataserviceforapps"
      }
    }
  }
}
```

### Response

```json
{
  "duration": 113.1,
  "size": 114,
  "status": 404,
  "headers": {
    "Cache-Control": "no-cache",
    "Content-Length": 114,
    "Content-Type": "application/json; odata.metadata=minimal",
    "expires": -1,
    "odata-version": 4,
    "req_id": "...",
    "x-ms-client-request-id": "..."
  },
  "body": {
    "error": {
      "code": "0x80040217",
      "message": "workflow With Id = 86721ee7-cb7e-ec11-8d21-002248320bcd Does Not Exist"
    }
  },
  "responseType": "text"
}
```

When I open up Dynamics CRM and force it to show the Workflow Record with 86721ee7-cb7e-ec11-8d21-002248320bcd as a Tenant-wide PowerPlatform Administrator (who also has the System Administrator security role in the CoE Environment), I indeed find that the record does not exist. (ref. `https://<coe-environment>.crm4.dynamics.com/main.aspx?app=d365default&forceUCI=1&pagetype=entityrecord&etn=workflow&id=86721ee7-cb7e-ec11-8d21-002248320bcd`)

## InstallFlow operation 2

The ID in this operation refers to the Workflow ID for the flow `Command Center App > Initially Populate Bookmarks`.

### Request

```json
{
  "url": "https://<coe-environment>.crm4.dynamics.com//api/data/v9.0/workflows(81ea7ac4-910a-ec11-b6e6-000d3a8c225c)/Microsoft.Dynamics.CRM.install",
  "method": "POST",
  "headers": {
    "x-ms-client-session-id": "...",
    "x-ms-client-request-id": "...",
    "x-ms-user-agent": "PowerApps/3.22085.9 (Web; Player; isReactNative: false)",
    "Request-Id": "...",
    "Client-Session-Id": "...",
    "x-ms-app-id": "...",
    "Accept-Language": "en-US",
    "Accept": "*/*",
    "Content-Type": "application/json"
  },
  "body": {
    "connectionReferences": {
      "shared_powerappsforadmins_1": {
        "connectionName": "...",
        "id": "/providers/microsoft.powerapps/apis/shared_powerappsforadmins"
      },
      "shared_commondataserviceforapps": {
        "connectionName": "...",
        "id": "/providers/microsoft.powerapps/apis/shared_commondataserviceforapps"
      }
    }
  }
}
```

### Response

```json
{
  "duration": 848.5,
  "size": 70,
  "status": 400,
  "headers": {
    "Cache-Control": "no-cache",
    "Content-Length": 70,
    "Content-Type": "application/json; odata.metadata=minimal",
    "expires": -1,
    "odata-version": 4,
    "req_id": "...",
    "x-ms-client-request-id": "..."
  },
  "body": {
    "error": {
      "code": "0x80040265",
      "message": "Failed to install the flow"
    }
  },
  "responseType": "text"
}
```

### Expected Behavior

The first InstallFlow operation show above should use the workflow ID of a flow that actually exists.

The flow install for the flow `Command Center App > Initially Populate Bookmarks` should succeed and the app should populate itself with the CoE App bookmarks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

Completely fresh environment setup, installed version 3.44 of the CoE Core Components solution and followed the setup instructions. Verified that all flows in the solution are activated.

### Anything else?

I looked up the `Command Center App > Initially Populate Bookmarks` flow in the solution component list and selected `Details` on the flow's context menu to bring up the flow's detail page. From here I was able to manually hit `Run` and the flow ran successfully. Subsequently opening the `Admin - Command Center` app successfully populates the initial page and no error banner is shown anymore.

**Comment by Jenefer-Monroe** [comment]
We shipped a new version of Core for the month with a flow that was missing (not this one). So its recommended that you re-download the kit and upgrade to 3.45. 

Then please make sure you have turned on all the flows in the [inventory setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components)
In particular this flow needs enabled to not see that failure message: **_Command Center App > Initially Populate Bookmarks_**

**Comment by SkippingAdi** [comment]
Hi
We just installed Version 3.45 of CoE Starter Kit and bug is still available.

**Comment by Jenefer-Monroe** [comment]
Is the flow on? And did you set the run only user properties of the flow?

**Comment by henriquesmoco** [comment]
I got the same error. Flow was on, run only user was set to my account (did not change it).

I executed the flow manually and it worked with no issues, after that the app didn't show the error anymore.

Another canvas app we created had same issue and we tried changing the read permission for "Process" as described on this [link](https://powerusers.microsoft.com/t5/Using-Connectors/connection-not-configured-for-this-service/td-p/891993). Seemed to have fixed but apparently not 100% as some users still can't run the WF from the canvas app. Looks like a bug on Power Platform...

**Comment by Jenefer-Monroe** [comment]
If you **_Edit bookmarks_** > **_Refresh_**, does it work? 
![image](https://user-images.githubusercontent.com/89584709/191107170-bbc286fc-573c-4308-9b0d-77d737e1f623.png)
![image](https://user-images.githubusercontent.com/89584709/191107260-b480849b-bb54-45df-9d3b-1281f8f184b1.png)

**Comment by henriquesmoco** [comment]
Same as yours: **Use this connection** (my account). I changed to **Provided by run-only user** to test and the refresh from the app worked.

**Comment by Jenefer-Monroe** [comment]
Good, yes **_Provided by run-only user_** is the setting we expect to see here, it just works for me the other way for some reason. 
Thank you for validating.

**Comment by SkippingAdi** [comment]
We changed run-only premissions to Provided by run-only user and the Command-Center App also seems to work now.

**Comment by Jenefer-Monroe** [comment]
Wonderful. Thanks for confirming!
