### ISSUE TITLE
[CoE Starter Kit - BUG] Installation Issue - no description for the environment variables

### ISSUE THREAD

**Issue by mscloud-pro** [microsoft/coe-starter-kit#3649]
### Describe the issue

While importing the core components 3.45 for a fresh install, the labels and the description for the environment variables are missing.
![image](https://user-images.githubusercontent.com/94551856/189646899-f781c4c3-d592-4553-9775-743a9ebdeff3.png)

### Expected Behavior

See the description and labels of the environment variables.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

core components installation

### Steps To Reproduce

1. Create an environment
2. import solution
3. make connections
4. get env variables

**Comment by manuelap-msft** [comment]
We have seen this issue before (https://github.com/microsoft/coe-starter-kit/issues/3082) but it is not related to the CoE Starter Kit solution, but a temporary product issue. Sorry we cannot assist with making them show up there in the Product UX as the solution itself does contain the descriptions. Some customers had success in trying it again later.

It also looks like you have set German as the default language - please note we only support English and you will have to install the English language pack: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#supported-languages

If even trying again doesn't make the descriptions show up, you can update the environment variables afterwards once the solution is installed. Here we describe a few different ways to do that: [How to update env vars](https://docs.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
