### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE : Cannot Able to See the All Dataverse Table

### ISSUE THREAD

**Issue by kktsz** [microsoft/coe-starter-kit#3657]
### Describe the issue

Hi , I can get all the other data (e.g. enviroment,flow and app), and I am sure that I have followed all the step in guide... After Runned the Admin | Sync Template flow, all the other data is able to see but I can see all the table the dataverse.
![image](https://user-images.githubusercontent.com/113410458/189810027-f7182d84-b8da-4dfd-8328-891f5c68a332.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

Power Platform Admin View and Datverse Table

**Comment by Jenefer-Monroe** [comment]
Hello. I presume you are asking about this table, is that correct? 
![image](https://user-images.githubusercontent.com/89584709/189811381-67690d68-406a-43ac-9acf-a6ebb5d6a4d0.png)

We do not currently fill that table today. It's still in there just for historical reasons. But we do not populate it.

**Comment by kktsz** [comment]
Ok! Thanks for your kindy help!

**Comment by Jenefer-Monroe** [comment]
You bet, thanks for using CoE!
