### ISSUE TITLE
[CoE Starter Kit - QUESTION] About the discontinuance of Dataverse (Legacy)

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#3658]
### What is your question?

I have a question about abolishing the use of the Dataverse (legacy) connector in the CoE starter kit.

We have confirmed in the admin center message that the Dataverse (legacy) connector will be deprecated in the future.
![image](https://user-images.githubusercontent.com/70095092/189831874-ef534827-4298-439c-927f-6111410d480d.png)

The current CoE Starter Kit setup instructions stated that the Dataverse (legacy) connector must be configured as a business in the DLP policy.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

Therefore, I believe that the latest version of the CoE Starter Kit also uses the Dataverse (legacy) connector, is that correct?

Also, do you have any plans to stop using the Dataverse (legacy) connector in the CoE starter kit in the future?

### What solution version are you using?

September 2022

**Comment by manuelap-msft** [comment]
Hello, that's correct - the current version of the CoE Starter Kit uses the Dataverse (legacy) connector. There are plans to remove the use of this connector, once the current Dataverse connector has parity in the functionality we need. We use the legacy Dataverse connector to query all environments in your tenant and find info on desktop flows, chatbots, and model driven apps - as the inventory for those resources is stored in dataverse tables of the environment they're created in.

At the moment, the current Dataverse connector only supports querying the current environment but not other environments in the tenant. Once that's possible, we'll change our flows to use the new Dataverse connector. Until then, we can't!

**Comment by sudadakkota** [comment]
Hello, thanks for answering.
I have understand why using dataverse (legacy) connector.

By the way, is it still unclear when the new Dataverse connector, not the legacy connector, will be able to query all environments in a tenant?

**Comment by manuelap-msft** [comment]
Yes, unfortunately there's no timeline yet for when the new Dataverse connector will be able to query all environments.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
