### ISSUE TITLE
"admin_recordguidasstring" not in Dataverse table - Power BI Center of Excellence Dashboard

### ISSUE THREAD

**Issue by JaimyPolhuis** [microsoft/coe-starter-kit#3659]
### Describe the issue

The following error appears in the query: 

Expression.Error: The column 'admin_recordguidasstring' of the table wasn't found.
Details:
    admin_recordguidasstring

When admin_recordguidasstring is removed from the query, it works, so I think that this column is not anymore in the table because I did not change anything in the standard data of the Center of Excellence.

### Expected Behavior

I excpected the data to load immediately, when connecting the data source of the Center of Excellence in Power BI, but I had to change the standard query first that comes with downloading the template for the Center of Excellence dashboard in Power BI.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.109.562.0 64-bit (September 2022)

### What app or flow are you having the issue with?

Production_CoEDashboard_September2022.pbit

### Steps To Reproduce

1. Change query by removing the string "admin_recordguidasstring"
2. Connect data source as it is supposed to be done

**Comment by Jenefer-Monroe** [comment]
Note that you need to have matching versions, aka Sept version of Core and Sept version of the report. 
Then also note that we reshipped the PBIT in August with the field removed. So I'm not sure how you were still seeing it in Sept 2022 PBIT. What table was it on?

**Comment by oburgoscr** [comment]
I'm getting the same error.

How can I remove the admin_recordguidasstring column?

**Comment by Jenefer-Monroe** [comment]
It's in the transpose data view in Power Bi, you can add it to the tables like this
![image](https://user-images.githubusercontent.com/89584709/190826316-15fa6a07-9f9b-4e18-9f52-6ab14b585bd3.png)

**Comment by JaimyPolhuis** [comment]
I am using the correct versions. And this error showed in all tables where this string was in the query.

Op 13 sep. 2022 om 15:20 heeft Jenefer Monroe ***@***.***> het volgende geschreven:

﻿

Note that you need to have matching versions, aka Sept version of Core and Sept version of the report.
Then also note that we reshipped the PBIT in August with the field removed. So I'm not sure how you were still seeing it in Sept 2022 PBIT. What table was it on?

**Comment by Jenefer-Monroe** [comment]
I dont know why you arent seeing the correct transforms. A clean install of the PBIT will have them. But if you dont then you will need to add to the remove columns as shown above.

**Comment by oburgoscr** [comment]
Thanks Jenefer you were right about the versions. First time doing this so it was confusing.
I went to [https://github.com/microsoft/coe-starter-kit/releases](url), downloaded different versions of the StarterKit from the Assets section, and tried opening them until I got the right one.

**Comment by Jenefer-Monroe** [comment]
Thanks for letting me know and welcome aboard! There is a bit of a learning curve here on CoE so feel free to reach out if you need anything!

**Comment by lrarbin** [comment]
@Jenefer-Monroe - Sorry to bother you, I'm a bit confused here. I updated to the May release on Friday, I'm now getting the "admin_recordguidasstring" not in Dataverse table error. Should "admin_recordguidasstring" exist in Dataverse?

**Comment by lrarbin** [comment]
> @Jenefer-Monroe - Sorry to bother you, I'm a bit confused here. I updated to the May release on Friday, I'm now getting the "admin_recordguidasstring" not in Dataverse table error. Should "admin_recordguidasstring" exist in Dataverse?

@Jenefer-Monroe - Sorry, me being very dumb, and pointing the report at our old COE environment!
