### ISSUE TITLE
[ALM Accelerator - BUG]: CustomAzureDevops :GetRepos Failed

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#3663]
### Describe the issue

We have shared ALM accelerartor with another user and that user get below error . 

The user has project administrator role in Devops but still getting below error .  Please advise 

![image](https://user-images.githubusercontent.com/44782172/189938226-9828b941-0732-444c-af21-76a66920252a.png)
****

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Sep 2022

**Comment by jenschristianschroder** [comment]
Have you verified that the user can indeed access the project?

Does the ALM acc. user setting include other projects than the one where the user is an admin (are there additional solutions with deployment profiles in the solution list?)

The error indicates that the returned response is not JSON and most likely HTML which would happen if the user is not permitted to see the repos.

Br,
Jens

**Comment by linujohn22** [comment]
> 

We have only one project where we we keep all solutions in separate repository . This is user is part of project administrator group . The user has access level 'Basic' . The user is part of build administrator group as well .  The user can see Repos .

**Comment by jenschristianschroder** [comment]
Looks like the necessary settings are in place. 

Could you try do a network trace using the browser developer tools to see what the Id is for the repo? It should show in the payload. 

Can you also check if you have the old url enabled on your org settings in azure devops?

**Comment by mikefactorial** [comment]
Closing this out for now as there's not been any activity in a while. Feel free to open a new issue if this is still a problem.
