### ISSUE TITLE
[QUESTION]: Is it planned to use service principals in the CoE Flows ?

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#367]
**Describe the bug**
When is it planned to use service principals rather than a service account for the CoE flows as Service Accounts are considered by many to be insecure ?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [2.0]
 - App or Flow All Flows

**To Reproduce**
N/A

If I looked into this would the Team be interested in the results ?

**Additional context**

**Comment by JeneferM-MSFT** [comment]
I'm afraid I don't follow your question. You can install the toolkit as a service principle today if you'd like.

**Comment by JeneferM-MSFT** [comment]
I can offer you this for now but cannot assist with it if there are mistakes, as we haven't vetted ourselves. 
I have added to our backlog documenting this. 
[service principle install.pdf](https://github.com/microsoft/coe-starter-kit/files/6495041/service.principle.install.pdf)

**Comment by NPrice99** [comment]
Hi Jenefer

I am happy to test / pipe clean for you.

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
That would be great! Yes please let me know if it works. :)

**Comment by NPrice99** [comment]
HI Jenefer 

I have hit a problem- some connectors do not support SPNs.

eg. Power Automate for Admins in the flow Admin | Sync Template v3 (Apps) .

Are there any plans for this connector to support SPNs in the future ?

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
I'm afraid I don't have specific answers here. This setup worked for some customers but I dont know how they did it, or if they skipped some flows, etc. 
And I'm afraid I cannot yet assist further on the support due to competing priorities. 
I have added documenting this to the backlog.

**Comment by NPrice99** [comment]
I can get all of my screenshots together and send you what I did to get this far.  If that helps.

**Comment by JeneferM-MSFT** [comment]
I wouldn't want to consume your time for this. But appreciate the offer.
