### ISSUE TITLE
[ALM Accelerator - BUG]: Get Organization Failed : intermittently

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#3672]
### Describe the issue

We have raised this issue 2 days before and closed the ticket(#3652) . However it seems our earlier finding was wrong  and closed the ticket .

We get this error intermittently after upgrade . We have upgraded 2 days before and after we started getting this error intermittently . 

we get this error for all users .

kindly advise .

![image](https://user-images.githubusercontent.com/44782172/190138471-656edff9-4099-4413-97d0-98a6f09b283f.png)

![image](https://user-images.githubusercontent.com/44782172/190138389-1daea3c3-c2bf-4fdb-bb7a-fb00f3900f77.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Sep 2022

**Comment by jenschristianschroder** [comment]
Are the two screen shots from the same user?


Usually the error "The data return in the response is invalid. Response data should be a valid JSON Object" indicates that the response status was 200 but the content was HTML and not JSON.
This will happen if the user does not have access to the Azure DevOps organization because the request is redirected to an HTML page which is then returned to the connector.

**Comment by linujohn22** [comment]
This two screen shots from same user .  Please notice that the same user works sometimes and fail again .

**Comment by mikefactorial** [comment]
@linujohn22 This is indicative of a stale connection. Sometimes on upgrade existing connections will use a cached token that needs to be refreshed. Would recommend deleting the existing connection and creating a new connection.

**Comment by elazarheefner** [comment]
@mikefactorial We have received the same error and recreated the custom connector and it did not resolve the issue.  We are able to test the connector for the GetOrgnization operation successfully. Has this been reported by others?

**Comment by mikefactorial** [comment]
Closing this issue out based on the response in #4042 and lack of other activity
