### ISSUE TITLE
[CoE Starter Kit - BUG] Implementation of new Dashboard fails in Power Platform Admin View 

### ISSUE THREAD

**Issue by ChristianLach** [microsoft/coe-starter-kit#3675]
### Describe the issue

Newly added dashboards inside the "Power Platform Admin View" MD-App show the default Power Platform Dashboard instead of the newly added one
Each implementation of a new subarea of type "dashboard" shows the Power Platform Dashboard instead of the new one.
It feels as if the Model Driven App understands there IS a new dashboard, but can't find it and loads the only available one - which is the default Power Platform Dashboard.

### Expected Behavior

The newly added dashboard should show up

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Power Platform Admin View (Model Driven App)

### Steps To Reproduce

1. Open Power Platform Admin View in Edit Mode (Managed CoE Version)
2. Open Classic Experience
3. Add dashboard "Create new"
4. Go back to modern experience
5. Add Sub-Area Type "Dashboard" -> Select newly created dashboard
6. Save and Publish

### Anything else?

![2022-09-14 17_13_45-App Designer](https://user-images.githubusercontent.com/113536340/190194760-1984e260-1b34-4cac-9347-479a6afba482.png)

![2022-09-14 17_12_48-Dashboard _ Compliance_ Apps_Flows](https://user-images.githubusercontent.com/113536340/190194793-df9501c6-9e8f-494c-a623-46c24b4bd8db.png)

![2022-09-14 17_14_28-Power Platform Admin View - Power Apps](https://user-images.githubusercontent.com/113536340/190194879-71f912b9-391b-482f-ab06-f059752f31db.png)

![2022-09-14 17_14_49-Power Platform Admin View - Power Apps](https://user-images.githubusercontent.com/113536340/190194935-8613c853-03ba-446f-90a7-96de8743a353.png)

**Comment by Jenefer-Monroe** [comment]
There seems to be a bug in the product here around the modern experience. I had to change the name here in classic before it would show up 
![image](https://user-images.githubusercontent.com/89584709/191081418-cc230dab-ccbb-4f3e-9fd9-53aea42171d5.png)
