### ISSUE TITLE
[CoE Starter Kit - QUESTION] How Much Does it cost per Month to run the CoE Core Components

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#3682]
### What is your question?

How much does it cost per month to run the Centre of Excellence Core Components flows ?

In the UK the Pay as You Go cost is 50p / flow run if you have an Azure Subscription,

I have counted 67 flows in the core components - if they run once a day the I calculate the cost to be £1005 / month (67 flows x 30 days x 50p flow run).  I know there are a number of flows which run more than once a night as they run for each environment encountered. This is many time more that the £75 Azure Subscription you get / month.

**Comment by manuelap-msft** [comment]
Most of the flows that collect inventory (all the ones that start with Admin | Sync Template v3 (...)) run once per environment, some of them run once per resource as well (e.g. Flow Action Details), a small number run once per day or per week. Other flows only run when that action is needed (DLP Editor > Parse impacted resources into CSV, Env Request | Create approved environment). 

I don't believe only using pay as you go is the most cost effective way of running the Core Components. I'm not a licensing expert, but I believe pay as you go only makes most sense when you have flows that run rarely or that may have irregular spikes in flow runs. For the Core Components, where flow runs are very predictable, we recommend that the account running the flows has a Power Automate per user license ($20 per month) and that any admins who use the apps frequently have a Power Apps per user license ($27 per month) - for apps, it will make sense to use pay as you go if you have users who interact with the CoE kit apps but aren't expected to use them very frequently. 

I'm not sure what you mean by "the £75 that you get" - I don't think there's a limit of how much you can spend on an Azure subscription.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
