### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by segovof** [microsoft/coe-starter-kit#3684]
### Describe the issue

Having an error when launching the Admin - Command Center App. "CommandCenterApp>InitiallyPopulateBookmarks.Run failed: Connection not configured for this service."

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Admin - Command Center

### Steps To Reproduce

Just Open the Admin - Command Center, an the error show.

**Comment by Jenefer-Monroe** [comment]
Can you please check your run only users property of the **_Command Center App > Initially Populate Bookmarks_** flow? 
If they are listed as another admin it may not work, and you would need to change this to be **_Provided by run-only yser_**
![image](https://user-images.githubusercontent.com/89584709/190485738-d17b6ba1-2ea5-46ca-9bf7-89390997af7c.png)

**Comment by segovof** [comment]
Thanks for your quick answer, I think the issue was the the Flow had not run it, so I just run it once and then the Bookmarks were Populated.  Thanks Much !
