### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by jathorpe** [microsoft/coe-starter-kit#3688]
### What is your question?

What is the recommended path to upgrade from March 2021 (Core Components) to the most current version? The documentations says you shouldn't fall more than three versions behind otherwise, you may have issues. In this case we are 18 versions behind but we only have the the core components installed. 

Asking for a friend :-)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2021

### What app or flow are you having the issue with?

Upgrading

**Comment by Jenefer-Monroe** [comment]
If you are just using us for inventory, and not marking up metadata (ex not using envt capacity feature etc), then you would likely be best served by just just deleting and reinstalling the new version of the kit. In this case all the data will be re-populated when you run the sync flows. 
Let me know your thoughts on that.

**Comment by jathorpe** [comment]
We have customized the Power Apps table by adding some of our own columns and data. We have also built a few custom solutions that use the data on the core tables. Based on our situation it sounds like reinstalling would create a lot of painful work. Is there a path that doesn't require reinstalling?  

I am not sure if this is doable but could we grab the oldest version available (May 2021) and upgrade to that then apply the updates for every other month until we are caught up? This plan doesn't sound great either but at least least we wouldn't lose our custom data or break any of our custom apps. 

FYI: We have a very large environment (10k apps and 40k flows).

**Comment by Jenefer-Monroe** [comment]
My suggestion would be to first export your existing modified solution into a test environment and try upgrading it there as sometimes upgrade fails and leaves you in a bad state. 
Then you can try to upgrade skipping months, June 2021, Sept 2021, Dec 2021, March 2022 .... etc

**Comment by jathorpe** [comment]
Do you know if there are any monthly updates that will require the flows to run before updating to the next release. It takes days for all the flows to complete, so we are hoping that we can hold off from running the flows until all the monthly updates have been applied.

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont know. We do occasionally have things that require that but all can be resolved with a full inventory in the end.
