### ISSUE TITLE
[CoE Starter Kit - QUESTION] SEVERAL EMAIL NOTIFICATIONS NOT HANDLED WITH HELPER SEND EMAIL

### ISSUE THREAD

**Issue by WinOnMarco** [microsoft/coe-starter-kit#3701]
### What is your question?

Why are still several Email notification not handled by the "HELPER - Send EMail" flow? 

E.g. "Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams" or "Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created" and many more. The possibility to configure Notifications without having to customize workflow (https://github.com/microsoft/coe-starter-kit/issues/1420) is a major requirement in my opinion. For instance, if I set up multiple environments (DEV, TEST, PROD) I want to be able to clearly identify where notifications are originating from by adding a identifier (e.g. prefix) to the subject.

Is there any certain reason why you did not consistently implement this? Or is this already in the backlog, but you just had no time to implement it?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

Several

**Comment by Jenefer-Monroe** [comment]
Yes we did the work for the Core solution so far and not yet for Nurture / Governance. Please see 
https://github.com/microsoft/coe-starter-kit/issues/1683

You are correct it is just a matter of being able to fund it with our small team.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
