### ISSUE TITLE
[CoE Starter Kit - BUG] Env Request | Create Approved Environment -> Does not wait after Create Environment

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#3702]
### Describe the issue

Hi,

I am experiencing continuous errors with the following Admin | Sync Template v3 flows:

- Admin | Sync Template v3 (Connection Identities)
- Admin | Sync Template v3 (Apps)
- Admin | Sync Template v3 (Custom Connectors)

![image](https://user-images.githubusercontent.com/48433526/190968881-497243e1-4ce5-414c-8931-1dafe416e128.png)

**Admin | Sync Template v3 (Connection Identities)**

Action 'Get_Connections_as_Admin' failed

The 'inputs.parameters' of workflow operation 'Get_Connections_as_Admin' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'environment'

![image](https://user-images.githubusercontent.com/48433526/190969610-bab399bf-9279-4657-bd83-4d2e06fb699d.png)

**Admin | Sync Template v3 (Apps)**

Action 'See_if_Apps_Exist' failed

The 'inputs.parameters' of workflow operation 'See_if_Apps_Exist' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'environment'

![image](https://user-images.githubusercontent.com/48433526/190969839-51b01753-d84a-4926-9960-0689e9d088b8.png)

![image](https://user-images.githubusercontent.com/48433526/190969956-ccd99b1f-9689-4ced-85c3-446a53efad65.png)

**Admin | Sync Template v3 (Custom Connectors)**

Action 'Get_Custom_Connectors_as_Admin' failed

The 'inputs.parameters' of workflow operation 'Get_Custom_Connectors_as_Admin' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'environment'

![image](https://user-images.githubusercontent.com/48433526/190970280-aabb4ba9-4f60-4a93-93cc-1ce6f3c8b6fc.png)

If would appear that the flows are looking for an environment that doesn't exists???

### Expected Behavior

Flow runs successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
Hello, in the future if you are resurecting old threads please reference them so we dont repeat the same investigation steps. 

It appears we are still at the state below from https://github.com/microsoft/coe-starter-kit/issues/3429

That is strange. OK lets get back to the flow then and see whats wrong there. 

1. Open the flow in edit mode, and make sure these two calls look like this:
![image](https://user-images.githubusercontent.com/89584709/184643616-a2bedbc2-33da-4a69-a3bf-46ef9b1d2305.png)

2. Open the failed run and expand the trigger, look for a column called admin_environmentname. It should be your envt GUID. Is it also null or is it your GUID? 
![image](https://user-images.githubusercontent.com/89584709/184644051-57ca400a-3e9b-4f1b-86d6-8abe484e95f2.png)

3. I've seen some weird caching issues lately. If you turn this flow off and back on, then Resubmit the run, does it still fail?
![image](https://user-images.githubusercontent.com/89584709/184644280-053c8b6e-d085-430d-83dc-62d60b7a6f4d.png)

**Comment by myatix** [comment]
I can confirm the below:

![image](https://user-images.githubusercontent.com/48433526/191065306-4efcb264-e224-4630-8539-712f1c6544ac.png)

The Environment ID is there:

![image](https://user-images.githubusercontent.com/48433526/191065859-b2627244-b08a-46c9-b364-6bb7883ce813.png)

When I try to filter by that Env. Name then it return's nothing...

![image](https://user-images.githubusercontent.com/48433526/191066509-c15ee932-fdc5-4a44-9455-a7123db28bcf.png)

**Comment by denisem-msft** [comment]
Regarding environment management, there might have been updated behavior on the API that we weren't aware of. Currently investigating with an internal ticket and will update when available.

**Comment by denisem-msft** [comment]
@myatix can you please confirm if you are able to reproduce this issue still? I am no longer able to myself.

**Comment by manuelap-msft** [comment]
Closing out as no further action required from CoE kit team. Please let us know if you continue to face issues.
