### ISSUE TITLE
How we can import the unmanaged layers back after solution upgrade

### ISSUE THREAD

**Issue by VanamaLaxmiChaithanya** [microsoft/coe-starter-kit#3704]
### What is your question?

**Scenario: How to get customization/unmanaged layers back to your solution**

Steps followed:
- We have a managed solution. 
- We added customizations to some of the flows/environment variables/power apps. 
- It created unmanaged layers to those components.
- We removed unmanaged layers and upgraded the solution
- Now we want to get our customizations/unmanaged layers back to this upgraded solution.

Problem Statement: 
**What would be the best practice/recommendation to achieve this.** 

### What solution version are you using?

August 2022

**Comment by Jenefer-Monroe** [comment]
I don't think this is possible. Flow does not support co-authoring which is why these layers and things exist. It just takes a copy of the flow as it existed and adds your change. There is no merge or backup type feature. 

Here is how it works visually, I hope it helps
![image](https://user-images.githubusercontent.com/89584709/191034596-24b3dedb-c987-495e-bb3a-93a17eb43cab.png)

**Comment by VanamaLaxmiChaithanya** [comment]
Hi Jenefer,

Thanks for your quick response. So we can conclude that

i. There is no feature to take backup of unmanaged layer before going for upgrade.
ii. There is no feature to backup of the flow including customizations

Please confirm once and share the doc url if any for the same.

Thanks,
Vanama Laxmi Chaithanya
________________________________

**Comment by Jenefer-Monroe** [comment]
You can remove unmanaged layers before or after upgrade. Please see [Remove unmanaged layers from inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) from [Updating the Center of Excellence (CoE) Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/after-setup)

But there is no backing up of customizations to reapply.

**Comment by VanamaLaxmiChaithanya** [comment]
Thanks for the reply Jenefer.

Please close the ticket.

Thanks,
Vanama Laxmi Chaithanya
________________________________
