### ISSUE TITLE
[CoE Starter Kit - Feature]: Create Docker image for coe-cli on release

### ISSUE THREAD

**Issue by fredrikhr** [microsoft/coe-starter-kit#3706]
### Is your feature request related to a problem? Please describe.

The ALM Accelerator pipelines need to use to use the `coe-cli` e.g. when exporting a solution to git. Previously the pipeline included the steps to clone `coe-starter-kit` and subsequently run the correct `npm` build commands to create a working version of `coe`. Currently, the pipline include their own binary copy of the `coe` tool in their source, making it hard to track which version of `coe` is being used in the pipeline as well as significantly increasing the size of the pipelines-repo and thus increasing the running time of the initial checkout step for the pipelines repo.

### Describe the solution you'd like

I propose to create a GitHub actions workflow that triggers on a release in the `https://github.com/microsoft/coe-starter-kit` repo. When triggered this workflow will checkout the tag of the release and build a Docker container using the `Dockerfile` in the `coe-cli` subdirectory. Finally, the built container should be pushed to a public Docker container repository, preferably the Docker hub. The container should be tagged with the tag-name of the release as well as updating the default `latest` tag on the container repository.

Then it would be possible to specify the container as a `resource` in e.g. the `export-solution-to-git.yml` causing Azure Pipelines to download the latest tag of the `coe-cli` container from the container repository. In the `update-deployment-settings.ps1` PowerShell script the call to invoke `coe` could then be replaced by running `coe` in the container.

### Describe alternatives you've considered

An alternative solution would be to instead specify the `https://github.com/microsoft/coe-starter-kit` repository as a `resource` in the pipeline. However, this has the disadvantage that it would require users of the ALM Accelerator to configure a GitHub service connection in Azure DevOps in order to reference the `coe-starter-kit` from GitHub. The checkout tag would also needed to be updated on each release (which could be automated by a GitHub actions workflow). Alternatively the ALM setup could add a new step to also add a copy of the coe-starter-kit to their DevOps project which would eliminate the need for a Service connection to GitHub.

### Additional context?

If I understand the documentation for [`resources.containers.container`](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-containers-container?view=azure-pipelines) correctly, a public image  does **not** require a Service Connection. I.e. hosting `coe-cli` next to the `azure-cli` container on `mcr.microsoft.com` should be unproblematic, especially since `coe-cli` already uses the `azure-cli` as a final base-layer.

Example shown below taken from the documentation shows how a ubuntu container is used, note the absence of an `endpoint` property (which would normally specify the service connection to use).

```yml
resources:
  containers:
  - container: linux
    image: ubuntu:16.04
```

The availability of a pre-built container endorsed by Microsoft could also simplify the Set-up instructions for setting up ALM Accelerator using a Docker container: Users could be directed to using the pre-built container, instead of having to build their own.

**Comment by mikefactorial** [comment]
@fredrikhr thanks for bringing this up. Adding @jenschristianschroder for visibility. This is something we've been discussing internally and our ideal path forward in the short term is to deprecate the coe-cli functionality in the pipelines in favor of porting the the coe-cli functionality to powershell. Most of the functionality in the cli (e.g. a lot of the AzDO project setup has already been ported to low code). The coe-cli is only used in the pipelines currently for generating deployment pipelines which can be done in powershell just as easily and would make it more transparent. Our hope is to do that work in the next couple of months, but always happy to take contributions and get your feedback on the progress toward that goal.

**Comment by mikefactorial** [comment]
Closing this out as we are moving away from coe-cli support
