### ISSUE TITLE
[CoE Starter Kit - BUG] CommandCenterApp Confusion with German and English field names

### ISSUE THREAD

**Issue by SkippingAdi** [microsoft/coe-starter-kit#3712]
### Describe the issue

When we open the CommandCenter app in Edit mode, we see about 12 error messages. All of them have to do with field names being unknown. In the code the field names are all English, when we search for them we don't find them but the corresponding German field names:
![CommandCenter App field names](https://user-images.githubusercontent.com/32366971/191226432-2df72fb6-ca7d-448b-a726-797d30c7e957.png)

In the above screenshot, we have commented out the English field name and displayed the German field name for illustration.
We are not sure if this is a display issue in the Canvas App Editor or where the problem lies. The app in and of itself seems to work.
The language settings in Edge are as follows:
![Edge-LanguageSettings](https://user-images.githubusercontent.com/32366971/191227874-2bc1f247-4d9f-42bb-805f-d38037d409fa.png)

the language settings of the account used are as follows:
![AccountLanguageSettings](https://user-images.githubusercontent.com/32366971/191227945-0d4e035c-cb49-4cd2-a04e-874f5ad11ec3.png)

What do you guys think?

### Expected Behavior

App Editor / Power Platform handles language/region differences 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by Jenefer-Monroe** [comment]
Hello. Please see our limitations [Supported languages](https://learn.microsoft.com/power-platform/guidance/coe/limitations#supported-languages), you need to have English supported for your environment.
