### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Apps)

### ISSUE THREAD

**Issue by athwasiya** [microsoft/coe-starter-kit#3714]
### Describe the issue

We are getting a flow failure from last few days.
![image](https://user-images.githubusercontent.com/113985215/191235942-d23c008b-d00d-464b-a5cc-9ed8cd7775c3.png)

Error  : 
[
  {
    "message": "Required properties are missing from object: bypassConsent.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0]",
    "value": [
      "bypassConsent"
    ],
    "schemaId": "#/items",
    "errorType": "required",
    "childErrors": []
  }
]

This error is coming up because of a SharePoint connection reference.

Not sure how it will get resolved. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

**Comment by Jenefer-Monroe** [comment]
Hello we do not have that as a required property in the schema there so you are either on an old version of Core or have an unmanaged layer. 
Can you please share a screenshot of these things? Note that you need to be logged in to GitHub to share screenshots. Replying in email will not share the images. 

### Your solution version
Browse to your CoE Environment > Solutions > Take a screenshot showing solution names and versions
![image](https://user-images.githubusercontent.com/89584709/191285426-61fa5c0c-0ee4-438b-a5f7-214002a96979.png)

### Your solution layers for this flow
Go into Core Solution > Flows > Admin | Sync Template v3 (Apps) > See solution layers
![image](https://user-images.githubusercontent.com/89584709/191286164-6cc232cf-d9c8-49a4-9e57-2d66e2a439bc.png)
![image](https://user-images.githubusercontent.com/89584709/191286250-c21a58a8-589e-482a-9afa-c6dad4a63a69.png)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
