### ISSUE TITLE
[CoE Starter Kit - QUESTION] Advice on Uprading from Oct 2021

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#3715]
### What is your question?

Hi,

Im running the Oct 2021 version, work got in the way so we are behind.   I am aware that you say you have tested upgrades for upto 3 months ahead, which is fine.  I have noticed that some versions have additonal work to do so wondered about the best approach.

So Ideally as we are Oct 2021  I was going to go ->Jan22->Apr22->Jul22->Sep/Oct22.

I did notice that in Dec21 release there is a new flow that needs to be ran, as part of the upgrade process, this is mentioned in the Jan22 also.

Is this flow run to import values the same in Jan as it is Dec ?  So I can happily start with Jan 22 as my first upgrade run that flow  and it will be fine, I dont need to start with Dec21 and offset along the way ?

Also the instructions dont mention this,  but should we disable all the flows first ?
What order should be upgrade the Solutions, does it matter ?  does it matter if the flows are enabled or not on the upgrade order.

Should we stick to    Core, Governance, Nurture, Audit Logs ?      I dont see any guidance on this, in one earlier release in '21.

Thanks
Simon

### What solution version are you using?

Oct 21

### What app or flow are you having the issue with?

N/A

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid I cannot comment with certainty on how to successfully upgrade from a build that old. But I can give you my best thoughts.

You should always upgrade Core first then the others. We did have a bug once that meant you had to do another order but that is something that just happened as a one off. So always Core first

As far as needing to run things on upgrade. That is typically just a way to get your inventory in working order. So its not something you should have to do between upgrades in this case. Worst case you may need to do a [full inventory](https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory) after you upgrade to the latest build.

**Comment by binaryjam** [comment]
Thanks

**Comment by Jenefer-Monroe** [comment]
You bet. Best of luck! Thanks for using CoE!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
