### ISSUE TITLE
[ALM Accelerator - BUG]: Delete solution fails, solution zipfile does not exist for import

### ISSUE THREAD

**Issue by fredrikhr** [microsoft/coe-starter-kit#3716]
### Describe the issue

When clicking `Delete solution` in the canvas app, the pipeline fails during the `importAndDeleteManaged` stage during the `Import Managed Solution` step.

> Error: Argument '--path' is invalid. The file 'D:\a\1\<solution_name>.zip' could not be found.

### Expected Behavior

The pipeline should not fail, the step importing the managed solution should take the solution exported in the previous stage and imported it, so that all solution components are deleted.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220831.2

### Steps To Reproduce

Click `Delete Solution` on a solution within the ALM Accelerator canvas app.
The Pipeline will fail.

### Anything else?

According to the logs, my Azure DevOps instance is using version `2.0.7` of the `Power Platform Export Solution` and `Power Platform Import Solution` tasks.
These use version `1.18.4+g1a00e63` of the Microsoft PowerPlatform CLI.

The export command show the following cli command line: (actual solution name redacted)

> Calling pac cli inputs: `solution export --name <solution_name> --path D:\a\1\exported\<solution_name>.zip --overwrite --managed true --async true --max-async-wait-time 60`

I did run the pipeline again with system diagnostics enabled and I could see that `pac` actually creates a zipfile named `<solution_name>_managed.zip` **regardless of the `path` argument in the CLI command**!  
And indeed the Pipeline artifacts show one file in the drop folder: `<solution_name>_managed.zip`

**Comment by mikefactorial** [comment]
This issue should be resolved in the latest release
