### ISSUE TITLE
[CoE Starter Kit - Feature]:  Broken Connection Cleanup Flow Report

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3719]
### Describe the solution you'd like

It would be helpful if this flow could produce a report of the connectors it has deleted and the flows that the connector is related to.

**Comment by Jenefer-Monroe** [comment]
We cannot correlate back to objects the connection relies on as that information is not available but we could add a mail with what was deleted. 
Please note that there was a bug in this feature when we first shipped Sept, so please go download 2.21 of Gov.

**Comment by Jenefer-Monroe** [comment]
We cut this flow due to the unreliability of the connection state returned. So closing this feature request out.
