### ISSUE TITLE
[CoE Starter Kit - BUG] [Child] Admin | Sync Logs > Run only users for Dataverse cannot be set to "Use this connection"

### ISSUE THREAD

**Issue by madeloeoutlook** [microsoft/coe-starter-kit#3723]
### Describe the issue

While configuring the [Child] Admin | Sync Logs flow and following step 8 and 9 of the setup guide we're facing an issue that we CAN ser the "use this connection <SPN>" for the "Office 365 Management API" and "Office 365 Outlook" connections but not for the Dataverse connection as it only displays "Provided by run-only user"

Also we noticed a "There's a problem with the flow's trigger". Using "Fix the trigger" throws an error as attached.

### Expected Behavior

It is expected that as documented we can also set the "use this connection <SPN>" for the dataverse connection.
Also that there is no error displayed concerning the flows trigger, see screenshot.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

 [Child] Admin | Sync Logs

### Steps To Reproduce

Following the guide till step 9. (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow)

### Anything else?

![Child  Audit flow FIX Error](https://user-images.githubusercontent.com/71876680/191305537-b1998a49-6bf5-4bfb-94bb-ab6bd356e307.jpg)
![Child  Audit flow](https://user-images.githubusercontent.com/71876680/191305542-a0129621-9d8f-4291-b057-57697a47901e.jpg)

**Comment by madeloeoutlook** [comment]
![Child  Audit flow FIX Error](https://user-images.githubusercontent.com/71876680/191305737-4fa21144-84c7-4948-9af2-27e2ce19b4de.jpg)

**Comment by Jenefer-Monroe** [comment]
Does this user (Luca) have a Dataverse connector in the environment? 
![image](https://user-images.githubusercontent.com/89584709/191320709-8bdba4cf-e6e8-4e89-a3fe-cacb8ab4e913.png)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
