### ISSUE TITLE
[CoE Starter Kit - BUG] Managers continue to receive Cleanup reports despite users having disapproved the deletion of an App

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#3726]
### Describe the issue

As part of the PowerApp cleanup process our manager are continually receiving notifications for Apps that employees have already rejected to be cleanup. Despite having rejected the deletion both via the workflow and now via the cleanup app managers are still being notified that employees have not reacted to the cleanup notification request.

![image](https://user-images.githubusercontent.com/48433526/191246420-e75db340-8dbe-4b50-bd60-422a32665235.png)

These same Apps have also not appeared in the "App and Flow Inactivity Notifications Clean Up" overview under "Apps - rejected but not yet excused."

It would appear that when the user rejects the app from being deleted then it is not registered correctly?

### Expected Behavior

When users decline an App from being deleted after it has gone to their manager then the manager should no longer receive mails notifying that the user has not responded to the cleanup email.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.20

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Jenefer-Monroe** [comment]
Hello we fixed this for you in the Sept release of Governance. 
Do note that we sent out a hotfix of the Sept release for Governance though of 2.21 so please upgrade.

**Comment by Jenefer-Monroe** [comment]
And make sure you dont have an unmanaged layer on this flow: **_Admin | Email Managers Ignored Approvals_**

**Comment by myatix** [comment]
> Hello we fixed this for you in the Sept release of Governance. Do note that we sent out a hotfix of the Sept release for Governance though of 2.21 so please upgrade.

### 

We did upgrade to the Sept release??? It would appear that we did not get the information about the additional hotfix for the September release? This obviously didn't trigger the Github watch alert for new releases (Hotfix)???

**Comment by Jenefer-Monroe** [comment]
Yes please upgrade to 3.45 of Core and 2.21 of Gov, and make sure you don't have an unmanaged layer on **_Admin | Email Managers Ignored Approvals_**

Here is how you can subscribe to be informed of releases [Subscribe to CoE Starter Kit releases](https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup#subscribe-to-coe-starter-kit-releases)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team

**Comment by myatix** [comment]
@Jenefer-Monroe As earlier stated this issue is not fixed and is the same as the new issue you requested we created issue #3776 Feel free to close this and track it on the other issue but perhaps in the future check the issue is fixed before just stating it was fixed in a previous release.
