### ISSUE TITLE
[ALM Accelerator - BUG]: Build Numbers

### ISSUE THREAD

**Issue by rfarris2000** [microsoft/coe-starter-kit#3728]
### Describe the issue

Consider the following scenario:

1) A deploy is initiated from the ALM and the build number is updated in the solution file to 1.0.20220920.1
2) The validation fails because of a gateway error.  The build is requeued and the build number is now 1.0.20220920.2
3) The PR is approved and moved through to the test environment with build number 1.0.20220920.2
4) A new change and commit is made from the developer environment because of an issue found in testing
5) A new deploy is initiated and the validation environment is now 1.0.20220920.3
6) PR is approved and moved through to test with a build number of 1.0.20220920.2
7) PR is made and approved from the solution branch to main
8) Deployment to production is successful and the build number 1.0.20220920.1

### Expected Behavior

The build numbers should be consistent across all environments.  The discrepancy causes confusion as to which one is current.  In the case above is the correct version 1.0.20220920.3 or 1.0.20220920.1

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Latest

### Steps To Reproduce

See above

**Comment by jenschristianschroder** [comment]
In the september release we introduced configurable version strategy.

You can now override our default version strategy and use the solution version number through your downstream environments.

You can also implement a completely custom version strategy using our pipeline extension points

Read here for details: https://learn.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-pipelines#customize-versioning-of-solutions-when-exporting--deploying-the-solution-using-the-alm-accelerator-pipelines

**Comment by rfarris2000** [comment]
@jenschristianschroder I missed that completely.  Thanks for the update!
