### ISSUE TITLE
[QUESTION]: What is in the Power Platform User Table? 

### ISSUE THREAD

**Issue by rahul9226** [microsoft/coe-starter-kit#373]
**Describe the bug**
In Power Platform Admin View, Power Platform user tab, some user are missing.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [e.g. 2.1]
 - App or Flow [Power Platform Admin View]

**To Reproduce**
1. Go to 'Power Platform Admin View app'
2. Click on 'Click on Power Platform User navigation in app.'
3. Cannot view all user. Some user are missing.

**Expected behavior**
Should sync all user from all environment for eg: Default, custom environemnt.

**Screenshots**
![image](https://user-images.githubusercontent.com/77864042/118532013-5a1f9d80-b6fb-11eb-8149-232ce44e4275.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid this is not sufficient information for us to assist. And likely just a misunderstand of what you will find in this table.

This is just showing the Power Platform User table, which is populated by the cloud flow **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_** within Core

From [Core Component Overview](https://docs.microsoft.com/power-platform/guidance/coe/core-components):

![image](https://user-images.githubusercontent.com/62659043/118538921-07021680-b70c-11eb-9c8a-14132914ed62.png)

![image](https://user-images.githubusercontent.com/62659043/118538969-15e8c900-b70c-11eb-8255-bc6f0fe955d1.png)

**Comment by JeneferM-MSFT** [comment]
No further action for toolkit so closing. Thanks for using CoE
