### ISSUE TITLE
Single quote causing Sync Template v3 (Connection Identities) to fail

### ISSUE THREAD

**Issue by SSSTREDDD** [microsoft/coe-starter-kit#3731]
### Describe the issue

' character (single quote) in UPN casing Sync Template v3 (Connection Identities) to fail

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

### Anything else?

')' or operator expected at position 222 in '_admin_environment_value eq 1234567-1233433-534234 and admin_name eq 'shared_office365users' and (admin_connectionreferencecreatordisplayname eq null or admin_connectionreferencecreatordisplayname eq 'fname'fname2@domain.ca')'.

**Comment by Jenefer-Monroe** [comment]
Hello, this is fixed for Oct in https://github.com/microsoft/coe-starter-kit/issues/3201
Thanks for using CoE
