### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance - App Catalog only shows apps to their owners

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#3733]
### Describe the issue

Hi,

When I mark a power app compliance and I set that it's showed in app catalog. The owner can see the app in the catalog but other users without access can't see it.

Is this behaviour correct?

App compliance:
![image](https://user-images.githubusercontent.com/57954993/191533373-b4533715-cee2-43ad-983a-310436aa63f3.png)

![image](https://user-images.githubusercontent.com/57954993/191533478-953633ca-4ed8-40b7-848b-a2576d83a002.png)

Owner view in app catalog:
![image](https://user-images.githubusercontent.com/57954993/191533702-201c3f97-234a-40df-abc0-9136119527d1.png)

Rest of users view:
![image](https://user-images.githubusercontent.com/57954993/191533736-c7618b43-7b4f-4d6a-bb23-17028782a0de.png)

### Expected Behavior

I would expect all users could see all apps catalogued to have an overview of the organization

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Lastest

### What app or flow are you having the issue with?

App Catalog

**Comment by Jenefer-Monroe** [comment]
No that is not the exected behavior, and I dont repro. We dont have any Row Level Security features in the kit like that. None of the SRs use partial access. 

Here is what is shown on visible of the screen in the app. In other words all canvas apps that are flagged as in the catalog
`ClearCollect( tenantApps, Filter( 'PowerApps Apps', 'In App Catalog' = 'In App Catalog (PowerApps Apps)'.Yes, 'App Type'='PowerApps Type'.Canvas));
`

And here is the security role for User type
![image](https://user-images.githubusercontent.com/89584709/191745510-2bb467e1-041c-4bd0-938d-1519ed59d9cd.png)

**Comment by Jenefer-Monroe** [comment]
Could it be as simple as needing to refresh the app to get the new data?

**Comment by albertocaa1317** [comment]
Sorry, the user had the Power Platform Maker SR role. After to change to User role, it can see the apps un the catalog.
Thanks,

**Comment by Jenefer-Monroe** [comment]
Thanks for letting me know!
