### ISSUE TITLE
[CoE Starter Kit - Feature]: Compliance soluction - How an Admin reject the support details of an app?

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#3734]
### Is your feature request related to a problem? Please describe.

Hi,
After to see your explanation of Compliance solution in YouTube I have a question:
![image](https://user-images.githubusercontent.com/57954993/191544166-a4b70f0c-63f4-4a2e-85ad-4ac5fd4b3516.png)

How a admin can reject the info provided by an onwer in Compliance Developer Center? 

Following the BPF of the Power Platform Adm View, the admin can to check the info and finally mark the app like "Admin Requirement - Risk Assessment State" = Complete, but if the Admin wouldn't agree with the details?

I think that it would interesant have a way by the admin contact with the owner to requiere more details o ask by a better explanation of a point of the Support details, etc.

### Describe the solution you'd like

I think that it would interesant to have a mechanism by the admin to contact with the owner and requiere more details o ask by a better explanation of a point of the Support details, etc.

**Comment by Jenefer-Monroe** [comment]
Today they just set it back to requested. We are working on a method to contact the object owners from within the Power Platform Admin View app though currently, so that is coming! :)

**Comment by albertocaa1317** [comment]
OK, good news 😄

**Comment by Jenefer-Monroe** [comment]
closing out since there is no further work here. stay tuned for the others :)
