### ISSUE TITLE
[CoE Starter Kit - Feature]: Compliance - Business impact = Critical and its dependences are not clear

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#3735]
### Is your feature request related to a problem? Please describe.

The BPF used in the model driven Power Platform Admin to review the compliance, have this condition:
![image](https://user-images.githubusercontent.com/57954993/191548655-6352001f-2faf-45d7-8ade-b3d016d8d90a.png)

If the app has a Impact = Critical, it's mandatoy to attach a Mitigation plan.

But in Developer Compliance Center, the user doesn't know this dependency. He can select Critical and plan de mitigación = No.
![image](https://user-images.githubusercontent.com/57954993/191549292-74c73314-9041-4ec7-bcb8-86e62cae341e.png)

In this case, after the 7 days the user will receive again the request and maybe he can't understand the reason.

### Describe the solution you'd like

I think that it would interesting that if the user select Critical, the button submit is disabled until de plan mitigation is Yes. And a popup inform to the user that these conditions. For example 😄

**Comment by Jenefer-Monroe** [comment]
We are revamping this feature right now away from the BPF so this complication will be gone soon. We realize we cannot easily enforce which things are mandatory for organizations.

**Comment by albertocaa1317** [comment]
Ok, thanks for your answer.
