### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cpmpliance Developer Center - Support details

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#3736]
### What is your question?

Hi Team,
can you share with us your idea about the Support Details that he user have to provide:
![image](https://user-images.githubusercontent.com/57954993/191552668-fcedf310-94e1-4717-ab0c-6728cd81cee2.png)

Maker Requirement - Business Justification
Maker Requirement - Dependencies
Maker Requirement - Data Classification
Category
Maker Requirement Access Management
Maker Requirement - Business Impact
Mitigation Plan Provided
Attachments

Thanks!

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Lastest

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by Jenefer-Monroe** [comment]
Here is our write up for this area
https://learn.microsoft.com/en-us/power-platform/guidance/coe/governance-components#compliance-processes

Each org uses these fields slightly differently so I'm not sure what to say on top of this. Please let us know what is unclear so we can try to help

**Comment by albertocaa1317** [comment]
Ok, thanks for your answer.
