### ISSUE TITLE
Export COE component after customizing some flows

### ISSUE THREAD

**Issue by VanamaLaxmiChaithanya** [microsoft/coe-starter-kit#3738]
### What is your question?

**Scenario: How to export some COE solutions from an enviornment **

Steps followed:
- We have a managed solution.
- We added customizations to some of the flows/environment variables/power apps.
- It created unmanaged layers to those components.
- Now we want to export the entire solution and wanted to use them for customization. 
- Export option is disabled for COE components.
- 
Problem Statement:
**What would be the best practice/recommendation to achieve this.**

**Comment by manuelap-msft** [comment]
Here's our guidance for extending the CoE starter kit: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

You will need to create your own unmanaged solution with your own publisher, add all your customizations to that solution and then in your production environment import both solutions (our managed solution and your solution) as managed.

Hope that helps!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
