### ISSUE TITLE
[CoE Starter Kit - BUG]: Set Flow Permissions app

### ISSUE THREAD

**Issue by ashishatthi** [microsoft/coe-starter-kit#3739]
Using APP – Set Flow Permissions
 
I am trying to use the SEt flow permissions app in the COE starter kit, trying to add a user as an editor for a flow but the user is not getting added to the PowerAutomate flow.
I checked the code of the App (set flow permissions) in edit mode and this code is written on Add User Button. **If the RoleAssignment = editor the action passed is “addeditor”**
When Add user button is clicked it calls Helper-ObjectOperations flow and passes “addeditor” action for the user to be added
Helper-ObjectOperations internally calls another flow Helper-CLoudFlowOperations which has the following condition
But there is no option for the Action : addeditor and that is the reason the user is not getting added.

Can someone please check and let me know why this app is not working to add users as editor to powerautomate flows

**Comment by Jenefer-Monroe** [comment]
Hello, here is the case for addeditor in the helper
![image](https://user-images.githubusercontent.com/89584709/191742060-e084d72e-9a9c-45a7-aa9f-9cc8a2d2f65e.png)

You likely have unmanaged layers on this flow [Remove unmanaged layers from inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
