### ISSUE TITLE
[Question]: Guidance on upgrading from older version

### ISSUE THREAD

**Issue by modery** [microsoft/coe-starter-kit#374]
**Is your feature request related to a problem? Please describe.**
As the Starter Kit has grown and evolved a lot since it was first published, I would like to see some guidance on how to upgrade from older versions, as to enable companies using it to leverage any new additions (e.g. automatic archiving).

**Describe the solution you'd like**
- What needs to be done to upgrade from a much older version to a current version
- Any other upgrade guidelines (e.g. from a relatively recent version to a current version)
- How to ensure that no existing data is list
- How to deal with any customisations

**Additional context**
We deployed the starter kit around a year ago, and have some older versions deployed (Core 1.45; Nurture 1.13; Compliance and Report 1.17). We also did some smaller customisations via own solutions: e.g. we added a few more fields to the apps table (to capture country/region of an app, for example), and updated accordingly where needed (show those fields in the Developer Compliance Center and the Power Platform Admin view). As I think the structure of the starter kit has changed a good amount (some new environment variables? slight structure change?), it is difficult to figure out how to get to the latest version

**Comment by JeneferM-MSFT** [comment]
Hello. 

Here is our documentation on how to [extend the starter kit](https://docs.microsoft.com/power-platform/guidance/coe/setup#extending-the-starter-kit) and on [installing updates to the starter kit](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

You may run in to one-off issues like this one when upgrading from a version that old as well: https://github.com/microsoft/powerapps-tools/issues/491

Unfortunately there isn't a simple way to realign divergent versions.

**Comment by JeneferM-MSFT** [comment]
No further action for toolkit so closing. Thanks for using CoE
