### ISSUE TITLE
[CoE Starter Kit - BUG] Clean Up and Delete failed (User is disabled error)

### ISSUE THREAD

**Issue by lcimon** [microsoft/coe-starter-kit#3741]
### Describe the issue

Action **_Remove Apps as Admin_** from **_Admin | Inactivity notifications v2 (Clean Up and Delete)_** flow failed with the following error: 
The request failed with error: '{"error":{"code":"0x80040225","message":"The user with SystemUserId=XX-XX-XX-XX-XX in OrganizationContext=XX-XX-XX-XX-XXis disabled"}}'. The tracking Id is 'XX-XX-XX-XX-XX'.
![image](https://user-images.githubusercontent.com/22662809/191723890-1626acdd-f3f8-40ec-be24-99e8c1f1b9e1.png)

Connection account used for this action has the Power Platform Admin role.

### Expected Behavior

Application should be deleted properly.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.17

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Clean Up and Delete)

### Anything else?

During my investigation, I noticed few things that might help:
- All failures happen on app within solutions.
- Error happpens only for apps in a Teams environment.
- During the same run, apps in standard environments and not in solution has been deleted properly.

**Comment by Jenefer-Monroe** [comment]
Will investigate for Nov release.

**Comment by Jenefer-Monroe** [comment]
Error now caught and propogated to issuer for them to delete manually. We cannot delete objects in this state and the user will have to do so, but now it will no longer cause failures, and the alert will go to the person that can act.
