### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - Looking for flow that creates New Flow and Power Apps Report email

### ISSUE THREAD

**Issue by Fubblechunk** [microsoft/coe-starter-kit#3748]
### What is your question?

Please could you let me know which flow creates the New Flow and Power Apps Report email?

I've been looking through the solutions this morning but I can't find to corresponding flow.

An idea to help up locate thing in the future might be to add the flow name to the bottom of the email maybe?

Thanks in advance.

### What solution version are you using?

September 22

**Comment by Jenefer-Monroe** [comment]
I'm sorry I dont quite follow which mail you are referencing. Can you share here a screenshot (obscuring any PII) of the mail?

**Comment by Fubblechunk** [comment]
Hi Jenefer, thanks for your speedy response.

Sorry I should have been clearer, it's the email that comes out to tell us what apps/flows/connections have been created recently within out tenant.

![New App and Flow Report](https://user-images.githubusercontent.com/95350630/191967697-b27d5080-d84a-4145-b36f-341a5a7c79b0.jpg)

**Comment by Fubblechunk** [comment]
OK thanks Jenefer, it started around the time we setup the CoE so I assumed it was part of it.

I'll keep looking but thanks for letting me know.

**Comment by Jenefer-Monroe** [comment]
You are welcome. And welcome to CoE!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
