### ISSUE TITLE
[CoE Starter Kit - QUESTION] Governance Components 

### ISSUE THREAD

**Issue by crowdedLeopard** [microsoft/coe-starter-kit#3750]
### What is your question?

Hi Team,

Where has the governance components solution gone. I need the flows the run the app/flow cleanup process  

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

September 2022 

### What app or flow are you having the issue with?

Governance Components Solution

**Comment by manuelap-msft** [comment]
It has not, here's how to set it up: https://learn.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov

**Comment by crowdedLeopard** [comment]
![image](https://user-images.githubusercontent.com/99030907/191966203-0f130865-a637-4769-830e-9f60c295a95a.png)


Hi Manuela - I can find it here here, am I pulling the right version

**Comment by manuelap-msft** [comment]
Yes, if you look at the setup instructions you can see the Governance components solution is called CenterOfExcellenceAuditComponents which you've got in this file

![image](https://user-images.githubusercontent.com/55705669/191966636-cc982529-3f47-4b90-827b-ea968f047697.png)

**Comment by crowdedLeopard** [comment]
it probably is , many thanks

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
