### ISSUE TITLE
[CoE Starter Kit - BUG] Some flows are not in the CoE starter kit or in the PPAC

### ISSUE THREAD

**Issue by WouterF** [microsoft/coe-starter-kit#3751]
### Describe the issue

In the "Power Platform Admin View" and on other locations, not all flows are visible.
We have an environment that contains 11 flows.
The CoE starter kit only shows 7 flows.
In the Power Platform Admin Center, also only 7 flows are visible for that environment.
- they are not owned by a service principle
- they are turned on
- we already did a [full inventory](https://docs.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory)

Are you aware of an issue in the product? As the behavior is the same in the PPAC...

### Expected Behavior

All flows should be showed instead of only a part of it

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

**Comment by manuelap-msft** [comment]
From looking at the missing flows, can you tell if they have anything in common? E.g. they all are triggered from Power Apps, or they all use no connectors etc?

**Comment by Jenefer-Monroe** [comment]
Have the flows ever been turned on? For example flows imported but never enabled will not show in either PPAC nor in COE

**Comment by WouterF** [comment]
They are all triggered "when a sharepoint file is created or modified". Also the ones that do show up have this trigger.
They are all turned on and have runned before.
They are in a managed solution.

**Comment by manuelap-msft** [comment]
If they don't show up in PPAC either, I'd recommend raising a support ticket through regular support channels as well: https://learn.microsoft.com/en-us/power-platform/admin/get-help-support - likely, if it is fixed for PPAC they will come through in the CoE kit as well as we use the same APIs in the background. 

We'll investigate on our end as well but a customer support ticket usually helps us in getting issues prioritized!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
