### ISSUE TITLE
Upgrading from 1.9 to current

### ISSUE THREAD

**Issue by barnsey007** [microsoft/coe-starter-kit#3755]
I started to update from 1.9 to current version, but received some errors. I thought it was maybe best to remove everything from the Environment and start fresh. If I go through and remove the solutions individually, is that going to leave things that are in flight - approvals and such? Is there an option to reset an Environment back to default and is that maybe a better option? (I tried to ask some of these questions via Support, but the Support Engineer told me to post here.)

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help you get started with migrating the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507). But other metadata would not be maintained in that case unfortunately. 

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Sorry we cannot be of more assistance here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
