### ISSUE TITLE
[CoE Starter Kit - QUESTION] Duplicate environments with (org00000000)

### ISSUE THREAD

**Issue by alisoncyeh** [microsoft/coe-starter-kit#3757]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/3756

<div type='discussions-op-text'>

<sup>Originally posted by **alisoncyeh** September 23, 2022</sup>
What could be the cause of duplicate environments? They're displayed in the CoE dashboard as:

Default Environment 1
Default Environment 1 (org00000000)
Environment 2
Environment 2 (org00000000)

For Default Environment 1 (org00000000), custom forms seem to be the cause of the duplicate, but it wasn't true for Environment 2 (org00000000). Thoughts?</div>

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Power BI Dashboard

**Comment by Jenefer-Monroe** [comment]
Are the zeros there just to obfuscate the real url? Or is that what you are seeing?

**Comment by alisoncyeh** [comment]
The zeros are just to obfuscate the real url

**Comment by Jenefer-Monroe** [comment]
And do you see them both in the product admin pages? https://admin.powerplatform.microsoft.com/environments

**Comment by alisoncyeh** [comment]
No, just the one instance for each

**Comment by Jenefer-Monroe** [comment]
When were the records last updated? Note I mean the **_Modified On_** column, not **_Environment Modified On_**.
![image](https://user-images.githubusercontent.com/89584709/192389929-9e329561-16a4-4df1-a9f4-0ad3b322ae26.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by alisoncyeh** [comment]
Hi Jenefer! The environments in question were last updated on October 10 -- we are still seeing the duplicate environments in the CoE dashboard

**Comment by alisoncyeh** [comment]
Hi @Jenefer-Monroe! The environments in question were last updated on October 10 -- we are still seeing the duplicate environments in the CoE dashboard

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot? I'm afraid I have no idea what is happening and have never seen it happen before.

**Comment by alisoncyeh** [comment]
![Duplicate environments](https://user-images.githubusercontent.com/17972132/197070036-0a04407d-9e25-48c9-984b-249eaa5d0dea.png)

**Comment by Jenefer-Monroe** [comment]
Can you delete the two small ones (9 apps and 68 apps) from the inventory? Then you can see if they get re-added and if so we can investigate.

**Comment by alisoncyeh** [comment]
Appreciate your patience on this thread! My customer is not comfortable deleting those apps -- are there any other ways to troubleshoot?

**Comment by Jenefer-Monroe** [comment]
Sorry I did not mean to delete anything from the tenant. I mean just to delete them from the inventory table. I'm glad they pushed back as my language was not clear enough!

If you go to the Environment table in the Center of Excellence - Core Components solution and click edit on the data table
![image](https://user-images.githubusercontent.com/89584709/200854614-46cb21b4-d3bb-4fae-8adf-653e743a0890.png)

Find these two environments and delete the records
![image](https://user-images.githubusercontent.com/89584709/200854993-9e694ca0-1cd2-44bf-82b5-eacec996a4af.png)

All this will do is delete these "bad" environments from inventory. If they are real they will come back.

**Comment by alisoncyeh** [comment]
Ahh, thank you for clarifying! I'll have them try deleting the records & will report back if they are readded to the table
