### ISSUE TITLE
[CoE Starter Kit - QUESTION] Missing canvas apps in Power Platform Admin View

### ISSUE THREAD

**Issue by alisoncyeh** [microsoft/coe-starter-kit#3761]
### What is your question?

Have a user with many canvas apps across multiple environments but only a handful are shown in the Power Platform Admin View. Any troubleshooting suggestions?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
If this does not work, then you will need to find a repro of this in your tenant to see what is going wrong. 

1. Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you are looking for missing canvas apps chose **_Admin | Sync Template v3 (Apps)_**
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

5. From here you can explore if there is a failure, or if a bad return set, etc. And let us know if you have questions

**Comment by alisoncyeh** [comment]
Hi @Jenefer-Monroe!

The following admin sync flows are failing with these error messages:

**Admin | Sync Template v3 (Connection Identities):** The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '210250653' bytes. This exceeded the maximum size '209715200' bytes allowed.

**Admin | Sync Template v3 (Business Process Flows):** Action 'Check_if_Orphan_-_New' failed

**Admin |Sync Template v3 (Apps):** The API 'powerappsforadmins' returned an invalid response for workflow operation 'Get_Apps_as_Admin' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-AdminApps' requires the property 'body/value/202/properties/connectionReferences/0/iconUri' to be of type 'String' but is of type 'Null'.'

**Comment by Jenefer-Monroe** [comment]
Hello, you will need to create issues for each of these, we cannot reuse issues nor use a single issue for multiple items, as it becomes too difficult to track. 

Here are some initial thoughts, and then if you still need to post issues, please do so: https://github.com/microsoft/coe-starter-kit/issues/new/choose

### Admin | Sync Template v3 (Connection Identities): 
This failure is in an out of the box connector’s action, which we're just using. Unfortunately, it has a size limitation that you have exceeded. 

We cannot fix this, but you can manually clean up some of the old connections via Power Shell and then be under the size limit. We have documented this limitation here along with a starter solution to address via PowerShell: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#set-up-connection-cleanup-broken-connections


### Admin | Sync Template v3 (Business Process Flows)
You will need to post this issue, please be sure to state what version of Core you are on and share a screenshot of the failure.

### Admin |Sync Template v3 (Apps)
You will need to post this issue, please be sure to state what version of Core you are on and share a screenshot of the failure.

**Comment by Jenefer-Monroe** [comment]
There was a product change and flow connections became deletable when they were not before. Please have a product support ticket posted, there are engineers actively working to repair the situation for customers.

**Comment by alisoncyeh** [comment]
Understood, my customer has already opened tickets on this issue so I'll continue to follow along on their progress. In the future, is it not recommended to run the PowerShell cmdlets for cleanup? The cmdlets were removed in the documentation but there isn't new guidance to replace them

**Comment by Jenefer-Monroe** [comment]
Unfortunately we do not have a new solution at this time. The upcoming BYODL solution (https://docs.microsoft.com/power-platform/admin/self-service-analytics) will read the connection identities directly and not suffer from the connector limitation.

**Comment by alisoncyeh** [comment]
Thanks for the update -- appreciate your quick responses!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
