### ISSUE TITLE
[CoE Starter Kit - QUESTION] Retrieving Managers with Admin | Inactivity notifications (Clean Up and Delete)

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#3767]
### What is your question?

Hello.
We are investigating the inactivity process of the governance component.
Please teach me about specification of  Admin | Inactivity notifications (Clean Up and Delete).

The public information about this flow states that ignored approvals will be notified to the manager, as shown in the picture below.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/70095092/192227777-ae115e0f-2574-40e2-bf49-6dbff96f0416.png">

However, looking at the flow, it seems that there is no action that is getting the manager of the approval that was ignored.
The flow had a "Get my profile (V2)" action, but this action gets the profile of the user running the flow, right?
![image](https://user-images.githubusercontent.com/70095092/192228315-e6e3308c-3830-4ab3-acea-99c9adbce2eb.png)

Where is the function to notify the manager of the manufacturer whose approval has been ignored?
Also, does this feature require a manager to be configured in Azure AD?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Admin | Inactivity notifications (Clean Up and Delete)

**Comment by Jenefer-Monroe** [comment]
The manager information for all Makers is stored in the Maker table and filled in via the **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** flow. 
The flow that sends the notifications to managers about ignored requests is **_Admin | Email Managers Ignored Inactivity notifications Approvals_**

I hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
