### ISSUE TITLE
[AA4AM] When formatting json files, sort by keys to minimize noisy diffs

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#377]
Right now, when we use jq to format json files to be more source control friendly, we are not using the --sort-keys argument. 
https://stedolan.github.io/jq/manual/
If we did, it theoretically would minimize noisy diffs.

**Comment by mikefactorial** [comment]
Possible test subject from previous PR's 

[left.txt](https://github.com/microsoft/coe-starter-kit/files/6501929/left.txt)
[right.txt](https://github.com/microsoft/coe-starter-kit/files/6501931/right.txt)

**Comment by devkeydet** [comment]
Doing this on the CanvasApps folder causes pack process to fail.  Skip CanvasApps folder since the unpack tool already handles noisy diffs for CanvasApps.
