### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Admin | Sync Template v3 (Connection Identities) error

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#3773]
### Describe the issue

CoE Admin | Sync Template v3 (Connection Identities) flow shows there is something wrong with deleting from the inventory, I think.

I'm not clear on the cause or how to fix.

![image](https://user-images.githubusercontent.com/93291159/192389449-457ad2dc-486b-4de3-90f7-ea463c4669f5.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

**Comment by Jenefer-Monroe** [comment]
Please open this run again and expand the Find it for ID action. Let me know what is in the Filter Rows
![image](https://user-images.githubusercontent.com/89584709/192392209-12fe705c-a59a-4f36-9520-c50c43a1ea78.png)

**Comment by peteredc** [comment]
How's this?

{
    "host": {
        "connectionReferenceName": "shared_commondataserviceforapps",
        "operationId": "ListRecords"
    },
    "parameters": {
        "entityName": "admin_connectionreferenceidentities",
        "$select": "admin_name, admin_accountname, admin_connectionreferenceidentityid",
        "$filter": "_admin_environment_value eq xxxxxxxxxxxxx61822 and admin_name eq 'shared_commondataserviceforapps' and (admin_connectionreferencecreatordisplayname eq null or admin_connectionreferencecreatordisplayname eq 'by@e.ca')",
        "$top": 1
    }
}

**Comment by Jenefer-Monroe** [comment]
for the think you obsuscated here 
![image](https://user-images.githubusercontent.com/89584709/192572249-a98fe8f4-564f-4235-a529-4864f4caaa4f.png)

Did the name have an apostrophe or other special character? Like JimO'Brian@company.com

**Comment by peteredc** [comment]
No. It was something similar to smithbob@timhortons.ca.

I can share full details with you privately if you'd like.  Just let me know email etc.

**Comment by Jenefer-Monroe** [comment]
1. Does this repro if you resubmit this failure? 
2. What is returned from the **_Find it for ID_** call?

**Comment by peteredc** [comment]
Resubmit fails.

Here is the return from the resubmission:
{
    "statusCode": 200,
    "headers": {
        "Vary": "Accept-Encoding",
        "x-ms-service-request-id": "-72cf-4045-8246-769950b5f457,-76c0-48b4-91b6-9220219991ee",
        "Cache-Control": "no-cache",
        "Set-Cookie": "ARRAffinity=371c47967102ce3badbad8ef1d55d13858b74e3ffbea0685c180146b2726e9f5eb29bb4b19df1459d2ea781b605f33064b9fea1f144b525b9d7676625c4ffb5408DAA14D838F7A671519421424; domain=centreofexcellence.crm3.dynamics.com; path=/; secure; HttpOnly,ReqClientId=ae172e1d-b137-4ac6-926a-319e2b58842f; expires=Wed, 28-Sep-2072 12:02:31 GMT; path=/; secure; HttpOnly,ARRAffinity=371c47967102ce3badbad8ef1d55d13858b74e3ffbea0685c180146b2726e9f5eb29bb4b19df1459d2ea781b605f33064b9fea1f144b525b9d7676625c4ffb5408DAA14D838F7A671519421424; domain=centreofexcellence.crm3.dynamics.com; path=/; secure; HttpOnly",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
        "REQ_ID": "-76c0-48b4-91b6-9220219991ee",
        "AuthActivityId": "-561d-48d6-bd27-bae415b051de",
        "x-ms-dop-hint": "8",
        "x-ms-ratelimit-time-remaining-xrm-requests": "1,198.27",
        "x-ms-ratelimit-burst-remaining-xrm-requests": "5998",
        "OData-Version": "4.0",
        "Preference-Applied": "odata.include-annotations=\"*\"",
        "X-Source": "153216253157135902221713012632169123872531342196815315120365198220251921175816820124556,24493551042073242105176135192417616637137594115113220373319239106210311273181205",
        "Public": "OPTIONS,GET,HEAD,POST",
        "Date": "Wed, 28 Sep 2022 12:02:31 GMT",
        "Allow": "OPTIONS,GET,HEAD,POST",
        "Content-Type": "application/json; odata.metadata=full",
        "Expires": "-1",
        "Content-Length": "1193"
    },
    "body": {
        "@odata.context": "https://centreofexcellence.crm3.dynamics.com/api/data/v9.1/$metadata#admin_connectionreferenceidentities(admin_name,admin_accountname,admin_connectionreferenceidentityid)",
        "#Microsoft.Dynamics.CRM.DeleteMultiple": {
            "title": "DeleteMultiple",
            "target": "https://centreofexcellence.crm3.dynamics.com/api/data/v9.1/admin_connectionreferenceidentities/Microsoft.Dynamics.CRM.crmbaseentity/Microsoft.Dynamics.CRM.DeleteMultiple"
        },
        "@Microsoft.Dynamics.CRM.totalrecordcount": -1,
        "@Microsoft.Dynamics.CRM.totalrecordcountlimitexceeded": false,
        "@Microsoft.Dynamics.CRM.globalmetadataversion": "2477032",
        "value": [
            {
                "@odata.type": "#Microsoft.Dynamics.CRM.admin_connectionreferenceidentity",
                "@odata.id": "https://centreofexcellence.crm3.dynamics.com/api/data/v9.1/admin_connectionreferenceidentities(-1d03-ed11-82e5-000d3af4e751)",
                "@odata.etag": "W/\"1149028\"",
                "@odata.editLink": "admin_connectionreferenceidentities(-1d03-ed11-82e5-000d3af4e751)",
                "admin_name": "shared_commondataserviceforapps",
                "admin_accountname": "PowerPlatformSVCCoE@e.ca",
                "admin_connectionreferenceidentityid@odata.type": "#Guid",
                "admin_connectionreferenceidentityid": "-1d03-ed11-82e5-000d3af4e751"
            }
        ]
    }
}

**Comment by peteredc** [comment]
Note this error continues to show up daily, so it's not a one time thing.

**Comment by peteredc** [comment]
Ok.  So this should be fixed with the Oct release?

**Comment by Jenefer-Monroe** [comment]
I don't know, I don't have that filter so its hard for me to debug what you see. 
In the Oct relesae your flow will look different but I dont know if that will fix your bug. Can you see if that call returns the GUID?

**Comment by peteredc** [comment]
Looks like there is no output... I think your assumption is correct.  Anything I can do to clear this error?
![image](https://user-images.githubusercontent.com/93291159/193643788-b344a588-58ef-4639-86db-4afa1674e207.png)

**Comment by Jenefer-Monroe** [comment]
ok good to understand the situation. this is fixed local fixed for Oct which we will be releasing this week.

**Comment by peteredc** [comment]
Great! Looking forward to the release!
