### ISSUE TITLE
Request Orphaned Objects Reassigned: Explore Power Cards for orphaned notes to managers due to payload size limitations of Adaptive Cards

### ISSUE THREAD

**Issue by monicasv** [microsoft/coe-starter-kit#3774]
### What is your question?

Request Orphaned Objects Reassigned (Child) flow keeps failing with message: Action "Send_Table_For_Response" failed  The request failed. Response content: "{error": The payload is too large. Please make sure the size is less than 28 KB"

![Error 1](https://user-images.githubusercontent.com/90351601/192401612-f42d6f12-dba6-4931-ae8a-119cd4fab25d.png)
![Error 2](https://user-images.githubusercontent.com/90351601/192401619-9682f968-3f72-4bc3-b175-5d2c45f49687.png)
![Error 3](https://user-images.githubusercontent.com/90351601/192401631-3cb98212-b37d-40c0-a687-c10ca6b4fd15.png)
![Error 4](https://user-images.githubusercontent.com/90351601/192401637-009b95d7-1889-4ef7-af01-55c2ae2b737b.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

AB#1565

**Comment by manuelap-msft** [comment]
Hello,

the flow here compiles a table of all the orphaned objects to send to the manager as a Teams adaptive card. The only reason I can think of this error happening is that the table is too large for the adaptive card - would you be able to share roughly how many orphaned objects are in the table? 

It looks like we'll have to add error handling here and either split up the adaptive card into multiple cards or send an email instead. We might also be able to evaluate using [Power Cards](https://learn.microsoft.com/en-us/power-apps/cards/overview) instead although that may have similar limitations. 

Thanks for raising this, it has not come up before!

**Comment by Jenefer-Monroe** [comment]
I managed to force a repro here with ~150 orphans for an individual manager. 

We can later explore if Power Cards can handle a larger set than that. Please let us know what size you repro with if its lower than that. I'll repurpose this issue for that and put it on the backlog. 

In the near term I think the only thing you will be able to do is to clean up some of the orphans yourself in the **_Set App Permissions_** and  **_Set Flow Permissions_** apps

Some suggested techniques for cleaning include seeing which orphaned objects have no other editors, have not been modified or used anytime recently etc. 

Here for example you might want to delete "AnotherTest" but not "Power Hackathon" 
![image](https://user-images.githubusercontent.com/89584709/192814526-4db56e62-c14e-4a52-83a5-5eedadb1ce01.png)

**Comment by monicasv** [comment]
Thank you both for the feedback/comments.  There are currently 673 Orphaned Apps and 678 Orphaned Flows 😮
Will try the manual approach mentioned above!

**Comment by Jenefer-Monroe** [comment]
I was able to get this workaround in for next release https://github.com/microsoft/coe-starter-kit/issues/4511
While this isn't the nice new power cards, and we should still investigate them, users are no longer blocked by this limitation.

**Comment by manuelap-msft** [comment]
Investigation in Power Cards showed that they are not available in Government clouds, and also require recipients to have the Power Apps app in teams installed which might be a blocker. Closing out for now to stick with Teams Adaptive Cards.
