### ISSUE TITLE
[CoE Starter Kit - BUG] Managers continue to recieve cleanup notices despite users having responded to the cleanup request.

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#3776]
### Describe the issue

Currently we have a large number of managers receiving notifications that users have not responded to the CoE Governance Cleanup process for Apps (Possibly flows and other solutions as well). Despite the fact that the user has responded.

**Examples of emails:**
![image](https://user-images.githubusercontent.com/48433526/192454213-1eb2413f-8157-481d-a783-f1497f3b65f0.png)

![image](https://user-images.githubusercontent.com/48433526/192454284-0c37826c-7351-45f3-878e-16ddad7404df.png)

**Solution versions:**
![image](https://user-images.githubusercontent.com/48433526/192454336-07ee992a-4a63-41e3-90e4-821a3ff28f73.png)

The user has tried to use the Cleanup Tool to decline the deletion of these apps but still no luck. Managers continue to receive emails from users who have attempted to decline the deletion but for some reasons manager continue to receive these emails.

I have checked the "App and Flow Inactivity Notifications Clean Up" and the apps do not appear in the "APPS - rejected but not yet excused" view.

This is becoming a very big annoyance for a large number of managers in our organization.

In addition to the above is it possible to edit the email that Managers receive with regards to the Cleanup. The Email message needs more clarification to why the manager is receiving the email.

EG: You are receiving this email as part of the automated governance lifecycle and Power Platform cleanup process . The following employees have not responded to 3 previous approvals to cleanup the below application. For Example: This could be due to the fact that the employee has left the organization.

It would appear that their is no email template in the Emails section of the Command and Setup Center which is a shame as we would have to create an unmanaged layer. This makes things a difficult when updating the solution.

![image](https://user-images.githubusercontent.com/48433526/192454575-2b2eb4e2-401a-4079-8b51-6f699f4bc0f2.png)

### Expected Behavior

Managers should not continue to receive emails after users have declined or approved a solution for deletion either by the Approval Flow or the Cleanup App.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.21

### What app or flow are you having the issue with?

Admin | Email Managers Ignored Inactivity notifications Approvals

**Comment by Jenefer-Monroe** [comment]
For the ability to edit the email, we are tracking this feature via https://github.com/microsoft/coe-starter-kit/issues/1683

For this issue, it sounds like you have people rejecting the approval but that approval is not showing up. Can you please confirm that is your situation? 

I have just tested and locally this work for us
- Approve and Reject of Apps and Flows via **_Clean Up Old Objects_** app.
- Approve and Reject of Apps and Flows via email approval. 

So there is either something misconfigured for you or you have a case we have not caught. 
Please look into the following:
- Do you have the **_Admin | Inactivity notifications v2 (Check Approval)_** turned on and running? 
- Do you have unmanaged layers on either of these apps? 
![image](https://user-images.githubusercontent.com/89584709/192823174-f3c08ea6-76e5-4c76-b45e-c064140a3315.png)

If that all looks good then please let me know, do you have a repro in hand that you can use? A case where person x rejected app/flow y using app or mail? We will need to walk through the case.

**Comment by myatix** [comment]
Hi @Jenefer-Monroe,

This is still an issue for us!

Yes Admin | Inactivity notifications v2 (Check Approval) is turned on and running.

![image](https://user-images.githubusercontent.com/48433526/193628709-eb1662d9-08a4-490e-9591-83a3a312f02e.png)

and no we do not have any managed layers on either of those apps.

![image](https://user-images.githubusercontent.com/48433526/193629092-2823e753-96ce-4aaa-bdfc-889657cbfba7.png)

![image](https://user-images.githubusercontent.com/48433526/193629257-d539c1c9-006d-4084-9158-4d7cd7f9c624.png)

We have had to disable the manager notification flow for now as it is a major issue that this is sending emails to all levels of management when a user has responded to the workflow and Approved or Rejected the deletion of their Apps and flows. :(

**Comment by Jenefer-Monroe** [comment]
Here is the next step for you if you would like to continue investigating

If that all looks good then please let me know, do you have a repro in hand that you can use? A case where person x rejected app/flow y using app or mail? We will need to walk through the case.

**Comment by myatix** [comment]
Yes, we do have numerous users who have both used the flow and app so please go ahead.

**Comment by Jenefer-Monroe** [comment]
sorry the ask is on you. I do not have a repro. You will need to find a repro and once you have one in hand I can walk you through some debugging steps. 
Please get
- the user
- the app / flow and environment 
- if they accepted / rejected
- the date they did so
- how they did it (via the app / email / etc)

**Comment by myatix** [comment]
Hi Again, I think you misunderstood me! I have all those things!

What are the steps?

Best regards

Alan

**Comment by Jenefer-Monroe** [comment]
Please let me know is your example
- an app or flow
- an accept or reject
- done by mail or app
- the date they did so

**Comment by myatix** [comment]
Hi @Jenefer-Monroe 

Here are the responses to your questions.

- App
- Reject
- By App (and previously by email)
- 9-9-2022


I just noticed that all Environments currently have the following set in the Power Platform Admin View.

![image](https://user-images.githubusercontent.com/48433526/194318169-867f6a7a-3af0-47da-b024-694fb0c6327f.png)

"Excuse for Empty Environment Cleanup" should this not be set to No or Yes??? Can this be related to the issue?

**Comment by Jenefer-Monroe** [comment]
So the user rejected the deletion of an app on 9/9 using the **_Cleanup Old Objects App_** 

Can you please go to the app and do the same thing to another app? 

When I do that, I see the following UX afterwards. Do you?
![image](https://user-images.githubusercontent.com/89584709/194338307-513a48c8-7c67-43d9-9b50-7a0c4ceac393.png)

**Comment by myatix** [comment]
@Jenefer-Monroe I have now carried out the requested test:

Using the CoE service account I carried out the following:
![image](https://user-images.githubusercontent.com/48433526/195051232-abbddf99-fe88-4fbf-92f2-5266c7a56e42.png)

and received the 

![image](https://user-images.githubusercontent.com/48433526/195052570-b2850695-4ca6-420e-a9ea-a27133d071a3.png)

**Comment by Jenefer-Monroe** [comment]
Mine is persisted, I just logged in to see if the sample I showed above is still marked as deleted as it is although the stale since timestamp is shown when I return (isnt there when you first reject)
![image](https://user-images.githubusercontent.com/89584709/195083112-6aecf329-101c-4def-aa83-87e688a23b49.png)

**Comment by Jenefer-Monroe** [comment]
Sorry you feel that way. The starter kit is not a supported product and we do our best effort to assist with customers. But we cannot debug all situations remotely, this one does not seem like one that we can debug remotely. 

If you are able to think of some other ways to get more clues we can try to investigate further, but I cannot think of ways to further investigate via GitHub this issue.

Please see our [discalmer](https://learn.microsoft.com/power-platform/guidance/coe/overview#disclaimer)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
