### ISSUE TITLE
Environment table settings

### ISSUE THREAD

**Issue by MichaelRoth42** [microsoft/coe-starter-kit#3778]
### What is your question?

 I didn't get any data from the Admin - Command Center in the CoE Flow and Service Health section. I got the error message that I need to run the Sync Template 3 flow. Which I obviously did. After some research I realized, that all my environments had the value "no" in the Environments dataverse table in the column "isCOE"

 So that was why the Admin Sync Template 3 flow would gather any data and my Admin Command Center was showing that error message. 
 
I manually set the values to "Yes" now and it works, but how is this value set to yes usually? I guess it's not intended to do this manually, right?
 
![Environments](https://user-images.githubusercontent.com/58400001/192494699-c1d8887c-ae1c-4ae1-810b-7aa8ab9a3ded.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2022 

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by Jenefer-Monroe** [comment]
Hello. Is your CoE installed in your Default environment?

**Comment by MichaelRoth42** [comment]
uhm....yes it is 😅

**Comment by Jenefer-Monroe** [comment]
haha ok. This isn't recommended but I see now that this is what some people end up with in test tenants so we've unblocked  for Oct with this bug: https://github.com/microsoft/coe-starter-kit/issues/3724

Thank you for posting, I'll go ahead and close as a dupe and you can get the fix when we ship next week, or loal fix as show in that bug if you'd like.
