### ISSUE TITLE
[ALM Accelerator - BUG]: Migration of Dataflows in Managed Solutions

### ISSUE THREAD

**Issue by bronsonacoutts** [microsoft/coe-starter-kit#3779]
### Describe the issue

When promoting solutions as managed with the ALM4PP tool, the owner of solution objects becomes "# ALMAcceleratorServicePrincipal"

This makes resetting credentials and parameters in dataflows after import from what I can see impossible.   When searching dataflows as an admin to change the owner and modify the dataflow, searching for "# ALMAcceleratorServicePrincipal
" returns null. 

![image](https://user-images.githubusercontent.com/55462373/192495323-6483a0ae-4967-47ef-847b-29dab4755d87.png)

![image](https://user-images.githubusercontent.com/55462373/192496065-962bedc6-7e6a-48d2-a6fe-1d0b484cb633.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

 1.0.20220726.1

### Steps To Reproduce

Add a Dataflow to a solution
Promote via the ALM4PP as managed
Attempt to modify the data flow connections

**Comment by mikefactorial** [comment]
@bronsonacoutts thanks for reporting this. This was reported previously here https://github.com/microsoft/coe-starter-kit/issues/3705. Closing this out as a duplicate. Feel free to comment on the existing issue. Thanks again
