### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin Task Power BI error

### ISSUE THREAD

**Issue by MichaelRoth42** [microsoft/coe-starter-kit#3781]
### What is your question?

Hey there,

I get the error shown below, when trying to open the BI file with Power BI desktop

![image](https://user-images.githubusercontent.com/58400001/192518686-c6f0fb4b-4a56-44b4-9056-747d28395503.png)

Anyone else?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Admin tasks

**Comment by Jenefer-Monroe** [comment]
Did you install in a dataverse for teams environment by chance?

**Comment by MichaelRoth42** [comment]
I do some crazy stuff, but I would never do that. I already figured out that I have the same behaviour with the CoE BI report, so it has something to do with the tenant and the settings there, rather than the product. 

Managed to make it work on a different tenant

**Comment by Jenefer-Monroe** [comment]
Wonderful thank you for letting us know.
