### ISSUE TITLE
[CoE Starter Kit - QUESTION] unable to uninstall CoE core components

### ISSUE THREAD

**Issue by borrelnoten** [microsoft/coe-starter-kit#3782]
### Describe the issue

When trying to remove the COE core components, it keeps telling it has a dependency on the custom connector. I can't remove the custom connector called "Office 365 Management API" and also can't remove the dependency.

### Expected Behavior

I want to be able to delete the COE core components but that is impossible.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.37

### What app or flow are you having the issue with?

entire solution

### Steps To Reproduce

delete all but the audit log component (v2.10) and the core component. Next try do unintall/remove/delete the core component solution.

**Comment by manuelap-msft** [comment]
Hello,

the custom connector is used in the Audit Log solution by the flows there - so you'll have to remove the Audit Log solution first before you can uninstall Core components.

Hope that helps
Manuela

**Comment by borrelnoten** [comment]
I did that but the custom connector is still their amd thus the dependance is also still there after audit log removal.

**Comment by manuelap-msft** [comment]
You could try deleting the custom connector manually from the Dataverse > Custom Connectors interface, but that is untested and it may break some flows if you're using this custom connector outside of the CoE kit flows. In the CoE kit, we only use the custom connector in the Audit Log solution. 
![image](https://user-images.githubusercontent.com/55705669/192593233-8ec5ba63-6831-4e55-8915-674675bdf50c.png)

**Comment by borrelnoten** [comment]
I tried that also but then the error is that also the cistom connector is used by the coe core components

**Comment by Jenefer-Monroe** [comment]
Did you try to delete from here within the solution? 
![image](https://user-images.githubusercontent.com/89584709/192662811-83359b9a-459d-48a9-9ae9-f9075a42a385.png)

**Comment by Jenefer-Monroe** [comment]
I'm not sure. I am able to delete this in a managed install of Core. You may have dependencies elsewhere local to your environment. You will have to look around. Perhaps delete the connection reference or things like that.

**Comment by borrelnoten** [comment]
I just now uninstalled the audit log solution, no problem. Result is that the custom connector is still there btw. Now when I try to uninstall the COE core component solution, the dependency points to that custom connector (which I can't delete because it also seems to link to the same core components solution installed).
![image](https://user-images.githubusercontent.com/19395576/192720829-fb0e290e-c527-4b60-a1ea-1226953c8f04.png)

Deleting the custom solution does not work because it is still linked to some of the core component solutions (but it does not say that, only when deleting it via powershell it will tell):
![image](https://user-images.githubusercontent.com/19395576/192721119-3d5a137f-78cc-4e68-97dc-bac4583163e2.png)

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with this one as we dont repro ourselves and are unsure how you got into this state. 
If you are deleting CoE perhaps reset the envt or start in a new one.

**Comment by Ridderxxl** [comment]
Hello, having the same problem here. I read that you are unable to reproduce the error. I believe it might happen when one initially uploads the core Components and or Audit solutions before having the required licenses for either.
Nevertheless, unlike Borrelnoten, I cannot delete the environment i am in..
