### ISSUE TITLE
Unable to use createdOn column of COE table in power automate flow

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/coe-starter-kit#3783]
### What is your question?

We want to create a flow and get details of records added in PowerApps App admin table in our COE environment based on CreatedOn inbult column in the table. But the filter we are using for createdOn column is not working. 

Could you please let us know if we can use this column or is there any other option to check when was the record created in the table?

**Comment by Aparna-Mutalik** [comment]
I am trying to get the date the record was created in table.

**Comment by Jenefer-Monroe** [comment]
ok this is something that is available for filtering like any other field. 

The way you get the field syntax for most filtering is as shown here: createdon
![image](https://user-images.githubusercontent.com/89584709/192793914-019a4e11-f5fa-4ba4-b29c-2d396eb3eb42.png)

**Comment by Aparna-Mutalik** [comment]
Hi,

Thanks for this. I tried using it but still not working for me. 

Basically, I want to filter out records which were created in the table for past 7 days and send an email to my team with the details file as attachment. But the condition to filter out records created only in 7 days is not working. Below is condition i am using:

@{formatDateTime(items('Apply_to_each')?['createdon'],'MM/dd/yyyy')} -le @{addDays(utcNow(),-7,'MM/dd/yyyy')}

Can you please help me on this.

**Comment by Jenefer-Monroe** [comment]
Sorry I'm afraid we aren't staffed to assist with customizations. I had hoped I could help quickly but I wasn't able to, sorry! 
You may be able to get help from the general community though: https://powerusers.microsoft.com/

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
