### ISSUE TITLE
App published date for model driven apps

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/coe-starter-kit#3784]
### Describe the issue

`We are not seeing app published date for model driven apps in our tenant. Could you please let us know if this is expected behavior. Is there any specific flow which should run to update published date for model driven apps?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin - Sync Template V3

**Comment by Jenefer-Monroe** [comment]
Correct, this is not collected for Model Driven Apps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
