### ISSUE TITLE
Problem to upgrade "Center of Excellence - Core Components" solution

### ISSUE THREAD

**Issue by kinwong7** [microsoft/coe-starter-kit#3786]
### Describe the issue

Try to upgrade "Center of Excellence - Core Components" solution from v3.39 to v3.45
after upgrade, both old and new solution exist in solutions list
![Screenshot 2022-09-27 103001](https://user-images.githubusercontent.com/29238122/192555325-b06e99cb-93b5-475a-bea1-f2b4c28d215d.png)

### Expected Behavior

No imported successful message, the older version solution should be removed.

How to get rid of the older version of solution?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

n/a

### Steps To Reproduce

download the latest version of CoE Starter kit from GitHub
unzip the file
import "Center of Excellence - Core Components" solution

**Comment by Jenefer-Monroe** [comment]
I'm afraid there are just too many specifics of how you may have gotten into this state. 
But I can say that sometimes these things help
- there may be an "apply update" type option on the larger solution number if you hit that vertical elipses, that may help
- doing a classic overwrite may help as well. I'll paste how to do that below.

**Comment by Jenefer-Monroe** [comment]
### How to do overwrite upgrade in the classic UX? 
 
Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)
 
Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)
 
Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png)
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by kinwong7** [comment]
Hi Jenefer,

Before I use the classic overwrite method, I would like to use the "apply upgrade" (your first bullet).  I found the "apply upgrade" is available to an older version (v3.39 in my case), but the option is grey out in an newer version (v3.45).  Should I use "apply upgrade" option?

**Comment by kinwong7** [comment]
I tried the "apply upgrade", it works, thanks.

**Comment by Jenefer-Monroe** [comment]
oh wonderful, thank you for letting me know!
