### ISSUE TITLE
[CoE Starter Kit - QUESTION] Upgrading from older version of COE

### ISSUE THREAD

**Issue by dchrist27** [microsoft/coe-starter-kit#3787]
### What is your question?

I haven't had a chance to upgrade COE in over a year due to an urgent migration project.   I am at the following versions (from May 2021):

core components:  2.1.6
audit logs:   1.41
governance:  1.60

I see in the update notes that if we let COE lapse more than 3 months that it may cause upgrade problems. So I would like to know how best to upgrade to the latest version?

### What solution version are you using?

May 2021

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help you get started with migrating the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Sorry we cannot be of more assistance here.

**Comment by dchrist27** [comment]
Appreciate the response.   Do I need to migrate the audit log data?  Or can I not worry about migrating that data since I have to create a new environment anyway?  

Thanks

**Comment by Jenefer-Monroe** [comment]
if you dont migrate the audit log data then you will be back to the beginning for tracking that. Meaning last launched wont be known until its been launched again after you setup again. I hope that makes sense! And sorry we cant be of more assistance.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
