### ISSUE TITLE
[CoE Starter Kit - QUESTION] Regarding the conditions for users who are Maker is Orphaned

### ISSUE THREAD

**Issue by sudadakkota** [microsoft/coe-starter-kit#3794]
### What is your question?

I'm using the Core Components Power Platform Admin View to check for orphaned apps and flows.
Please tell me the following two points.

**(1) Can the user's display name and UPN change be detected?**
When I looked at the Sync Flow included in the core component, it seemed that there was no Flow that detects when the user's UPN or display name is changed.
If a user's display name or UPN changes, will it be recognized as a different user than the user already in the 'Maker' table and 'Maker is Orphaned' will be 'Yes'?

**(2) Flows without "Maker" and "DerivedOwner" and apps without "App Owner"**
Among the information of apps and flows synchronized by Sync Flow, there are cases where "Maker" and "DerrivedOwner" are blank for flows, and "App Owner" is blank for apps.
The pictures below are samples.
<img width="397" alt="image" src="https://user-images.githubusercontent.com/70095092/192745498-9804ae61-b06d-462c-8301-a4115bbcaba7.png">

The reason why this field is blank is that when the app or flow is synchronized to the table for the first time, although the app exists, the created user or owner does not exist in Azure AD , is it right?
By the way, "DerrivedOwner" in the flow is the current owner, right?

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
Derived Owner is a concept we introduced to work around the inability to re-assign flow ownership. It will be deprecated soon as the product team is introducing that capability.

**Comment by Jenefer-Monroe** [comment]
Correct a blank owner means that the object (app/flow/etc) was inventoried after the owner was already removed from AD. We have no information about them to enter.

**Comment by Jenefer-Monroe** [comment]
The **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** flow updates things like name / photo / etc for Makers. There are other places too but this is the catch all for makers that are not active. 
![image](https://user-images.githubusercontent.com/89584709/192817344-b55a71e8-f142-48a9-ae59-7147f2185d41.png)

**Comment by Jenefer-Monroe** [comment]
Hope that all helps!

**Comment by sudadakkota** [comment]
Thank you for your answering！
Tell us more about "_**CLEANUP - Admin | Sync Template v3 (Orphaned Makers)**_".

Here is a picture of me expanding the 'update maker details' scope and checking to see the action.
![image](https://user-images.githubusercontent.com/70095092/192918629-fbb1efdc-f37f-43b7-bb1e-1b5ee58e7db4.png)
![image](https://user-images.githubusercontent.com/70095092/192918682-a7790840-3156-4ae2-95ce-12b99a3386cb.png)

From the part circled in red, I thought that changing the User Principal Name would not be detected, is that correct?

**Comment by sudadakkota** [comment]
Also, is it correct that "Maker is Orphaned" means that the user has disappeared from Azure AD?

**Comment by jbst2018** [comment]
Hi,Team.
I have the same question as sudadakkota is asking.
Is it correct that "Maker is Orphaned" means that the user has disappeared from Azure AD?

![image](https://user-images.githubusercontent.com/109139057/193183051-bde71947-e42a-43b9-bc75-e5183001f675.png)

**Comment by Jenefer-Monroe** [comment]
I'm not sure what issue you are referencing. Do you mean that you don't see the Update Maker Details? That will either be because you have [unmanaged layers hiding it](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows), or you are on too old of a version in which we had not yet added it. 

Correct on object being orphaned means its owner no longer resolved in AD.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
