### ISSUE TITLE
[CoE Starter Kit - BUG] Env Var Auto Delete on Archive Deprecated but still in flow

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3797]
### Describe the issue

The env var Auto Delete on Archive says that it is deprecated in the command center
![image](https://user-images.githubusercontent.com/17124284/192771641-e1d58cd1-ba71-4e7e-b544-13e3718c7c52.png)

however this variable is still present in the Admin | Inactivity notifications v2 (Clean Up and Delete) flow
![image](https://user-images.githubusercontent.com/17124284/192771824-450a917a-c30a-4100-96af-6a6261bc0ddf.png)

I have seen that there was an issue raised regarding the confusion in the documentation but does not resolve the variable still being active in the flow

#343

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.21

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Clean Up and Delete)

**Comment by Jenefer-Monroe** [comment]
Yes we have not taken it out yet intentionally as we want to ensure everyone has migrated to using the other env variable.

**Comment by medicineshow** [comment]
so assume it will still take effect when running the flow for now?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
