### ISSUE TITLE
[CoE Starter Kit - BUG] Solution upgrade failed

### ISSUE THREAD

**Issue by LeeMather** [microsoft/coe-starter-kit#3798]
### Describe the issue

When trying to install an update from to the Toolkit and getting the following error

The imported solution and the existing solution must both be managed for upgrade.
![image](https://user-images.githubusercontent.com/41200877/192773012-8a977292-309c-4b34-ac21-179fd2439956.png)

### Expected Behavior

The solution to import

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.40

### What app or flow are you having the issue with?

CoE Core Toolkit

### Steps To Reproduce

Download update solution
Import

### Anything else?

No

**Comment by manuelap-msft** [comment]
Can you share a screenshot of the **Solutions** screen and make sure to expand the Name column - do you see any CenterofExcellenceCoreComponents_**Upgrade** solution there? Sometimes if a previous upgrade failed that can lead to these issues. 

![image](https://user-images.githubusercontent.com/55705669/192776699-b10f02f3-84e1-440e-b41a-9d251bdbefdf.png)

**Comment by LeeMather** [comment]
Hi, as requested

It is the core solution.  I have tried to upgrade to 3.41 and 3.45

![image](https://user-images.githubusercontent.com/41200877/192778483-205e2f69-72cd-40ec-b00e-5233914cffd9.png)

**Comment by manuelap-msft** [comment]
And the Core components shows Managed?
![image](https://user-images.githubusercontent.com/55705669/192779078-0f462d83-9bee-4122-a43c-ac21da681e0f.png)

**Comment by LeeMather** [comment]
![image](https://user-images.githubusercontent.com/41200877/192783661-93efe7e4-b434-4181-8f13-50998c603c30.png)

**Comment by Jenefer-Monroe** [comment]
I've seen one person hit this. I have no idea what caused it, its some product bug detecting solution type incorrectly. They did an overwrite install and it fixed it up. 

### How to do an overwrite upgrade in the classic UX:
 
Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)
 
Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)
 
Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png)
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by LeeMather** [comment]
Thanks, we have done no custom work yet, so will back up, then try again with the steps you suggest

Thanks

**Comment by LeeMather** [comment]
Errored again

![image](https://user-images.githubusercontent.com/41200877/192976932-49414017-3591-49c4-aaa4-7f3a868e0aa1.png)

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont know how to help here. The product itself is incorrectly identifying either the new or the old solution as unmanaged. You may need to create a support ticket.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by MichaelRoth42** [comment]
Hey there, I have a very similar issue. 

I tried to upgrade the Governance components solution and ran into an error. Now there is a managed CenterofExcellenceAuditComponents_Upgrade solution.

![image](https://user-images.githubusercontent.com/58400001/207066847-968f0985-58d2-4121-ab94-cbc6b3b2eee8.png)


Can I follow the steps above or do you have another idea how to proceed here?

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont have advice here. The product itself seems to have had an error in identifying managed v unmanaged. 
The advice above fixed it for the customer mentioned but not the second customer.
