### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Audit logs flow failure

### ISSUE THREAD

**Issue by DJC339** [microsoft/coe-starter-kit#3803]
### Describe the issue

I have just installed the Audit log solution and everything went well, when I turned on the child flow and parent flow the parent flow failed on the run child flow activity with this error.

Failed to parse impersonation invoker connections from trigger 'manual' outputs. Details: 'Could not find 'x-ms-user-id' header in the trigger request. Workflow has connection references '["shared_commondataserviceforapps_1"]' with 'invoker' as impersonation runtime source.'

The output was a status code 400.

Can you help me sort this out please?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### Steps To Reproduce

1. In correct environment
2. Run Parent flow
3. See error

**Comment by sambhrama28** [comment]
I am facing the same issue, please help

Failed to parse impersonation invoker connections from trigger 'manual' outputs. Details: 'Could not find 'x-ms-user-id' header in the trigger request. Workflow has connection references '["shared_commondataserviceforapps_1"]' with 'invoker' as impersonation runtime source.'

**Comment by Jenefer-Monroe** [comment]
Did you do the **_Run only user_** settings step from [Set up the Power Automate flow](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow)? 
![image](https://user-images.githubusercontent.com/89584709/192861829-9b4c65b3-57ad-4efb-8012-bde17a6a4e90.png)

**Comment by DJC339** [comment]
@Jenefer-Monroe Thank you Jenefer, that was it, if forgot to change the dataverse one.

**Comment by Jenefer-Monroe** [comment]
Wondeful news! Thank you for letting us know!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
