### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot turn on flow Admin | Sync Template v3 (Call Updates)

### ISSUE THREAD

**Issue by tchagan** [microsoft/coe-starter-kit#3806]
### Describe the issue

The flow Admin | Sync Template v3 (Call Updates) cannot be turned on, error shows:

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"MultipleErrorsOccurred","message":"Multiple errors occurred: 'BadRequest,BadRequest,BadRequest'. Please see details.","details":[{"code":"ChildFlowUnsupportedTriggerType","message":"The workflow with id '0ca18fdb-ac43-ec11-8c62-00224829b4c1', name Admin | Sync Template v3 Configure Emails cannot be used as a child workflow. Child workflows only support manual, powerapp and http request triggers."},{"code":"ChildFlowUnsupportedTriggerType","message":"The workflow with id '7e1ddb35-613d-eb11-a813-000d3a8f4ad6', name Admin | Sync Template v3 (Connectors) cannot be used as a child workflow. Child workflows only support manual, powerapp and http request triggers."},{"code":"ChildFlowUnsupportedTriggerType","message":"The workflow with id 'f67e1e35-4cd5-ec11-a7b5-0022482783b7', name Admin | Sync Template v3 CoE Solution Metadata cannot be used as a child workflow. Child workflows only support manual, powerapp and http request triggers."}]}}".

Looking at the flow it expects that the 3 flows mentioned above can be called as Child Flows, these flows do not have a Manually trigger a flow Trigger, they are scheduled flows so cannot be called.

### Expected Behavior

The flow should be able to be turned on.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Call Updates)

### Steps To Reproduce

1. Install solution - in my case this is an update
2. Go through the steps for turning on flows etc. try to turn on the flow
3. Flow produces the error message
4. Flow is not turned on

### Anything else?

![image](https://user-images.githubusercontent.com/8684518/193008544-bf500f7a-8f35-4587-bde2-1987d82d6599.png)

**Comment by Jenefer-Monroe** [comment]
This was a change to those three child flows. They went from scheduled to trigger. 

First please make sure you don't have unmanaged layers on them, and then if that does not fix it, please turn them off and back on. I have seen occasionally the trigger type get stuck somehow in the product cache until you turn the flow off and on.

**Comment by tchagan** [comment]
Yes, that was it, sorry about that, I had been doing a few tenants and I was sure I'd removed any solution layers, but when I checked I hadn't! Apologies, and thanks for the help.

**Comment by Jenefer-Monroe** [comment]
No problem, thanks for using CoE!
