### ISSUE TITLE
Power Automate Management Connection

### ISSUE THREAD

**Issue by jenniferbrown12316** [microsoft/coe-starter-kit#3807]
### Describe the issue

Hello, 

I was told from Microsoft that they are ending life of the third party Power Automate Management Connector, However it is used in the COE. How do i change the connection and what do i replace it with? 

thanks 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Admin - Access this Flow, Admin Command Center, Developer Compliance Center

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
