### ISSUE TITLE
[CoE Starter Kit - Feature]: "App is orphaned" property to take into account the co-owner(s)

### ISSUE THREAD

**Issue by Papa-Cho** [microsoft/coe-starter-kit#3809]
### Is your feature request related to a problem? Please describe.

If my understanding is correct, the "App is orphaned" property only considers the owner and not the co-owners if any exist. So if there is a co-owner, app should be considered as orphaned as per definition.

### Describe the solution you'd like

I'd like the "App is orphaned" property to take into account the co-owner(s). It could be even combined with a new property such as "Has a co-owner". 

### Describe alternatives you've considered

I've not considered customizing the CoE kit to get the info

**Comment by Jenefer-Monroe** [comment]
Hello. we do have this on our feature backlog as #3413 so please track tehre. I will close this one as a dupe. 
Thank you for using CoE!

**Comment by Papa-Cho** [comment]
Ok, thank you
