### ISSUE TITLE
[CoE Starter Kit - BUG] PowerBI Dashboard Missing Fields

### ISSUE THREAD

**Issue by christinatang-NAES** [microsoft/coe-starter-kit#3813]
### Describe the issue

In the Power Platform Production CoE PowerBI Dashboard, I'm seeing that there is data missing that isn't carrying across. For example, under the Apps page, the fields Unique Users, Sessions, and Last Launched are blank for some reason.
![image](https://user-images.githubusercontent.com/107637236/193143002-7c437081-2ff8-41e9-b142-3bde2e9686c5.png)
Another example is the Desktop flows page. Desktop flow names are blank where the creator is listed and the rows with a Desktop flow name listed is showing blank Creator, Created On, Last run fields etc.
![image](https://user-images.githubusercontent.com/107637236/193143723-c558777f-9a2e-493a-bb53-7a560dede15c.png)

### Expected Behavior

I expected the missing fields to be populated with the correct data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Admin - Sync Template V3

**Comment by manuelap-msft** [comment]
Hello,

For **unique users/sessions:**
Do you have the Audit Log solution set up (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)? This captures information about unique users and sessions and last launched dates. If this solution has not been set up, these fields will be empty. Also note that the Audit Log solution only captures data from the moment it's set up, and is not able to get past data - so you would not get information from app launches/sessions that happened before you set the solution up.

For **Desktop flows**: we'll investigate, that looks like a bug in how we display the data. I'll get back to you on that!

**Comment by Jenefer-Monroe** [comment]
For the desktop flow issue, I do not repro so lets see where the issue lies for you. Do you see the data correct in the dataverse tables themselves? You can see this by going to the Power Platform Admin View app
![image](https://user-images.githubusercontent.com/89584709/193410537-7d00f369-c574-4358-82d1-0c2138b7dcc0.png)

**Comment by christinatang-NAES** [comment]
Hi Jenefer,

Thanks for looking into this issue! The data is correct in the Power Platform Admin View app but not the PowerBI dashboard.
***@***.***

Christina Tang
Business Hyperautomation Lead

Direct: 425-270-6041 | Cell: 425-773-9739
***@***.***
***@***.***>
[Inline images 1]
NAES Corporation
1180 NW Maple St. Suite 200, Issaquah, WA 98027

www.naes.com<http://www.naes.com/>

**Comment by christinatang-NAES** [comment]
Hi Manuela,

I noticed that my Child Admin Sync flow was turned off so I turned it off and now I'm running into 401 error. I'm not sure why it's giving me this error when it's successfully connected to the Office 365 Management API. Is this because something was set up incorrectly during the Azure AD app registration?
***@***.***

Thanks for looking into this,

Christina Tang
Business Hyperautomation Lead

Direct: 425-270-6041 | Cell: 425-773-9739
***@***.***
***@***.***>
[Inline images 1]
NAES Corporation
1180 NW Maple St. Suite 200, Issaquah, WA 98027

www.naes.com<http://www.naes.com/>

**Comment by manuelap-msft** [comment]
Hello,

yes, a 401 error typically means the custom connector has not been setup correctly or some values have expired (e.g. the client secret may have expired). Here's the setup instructions: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

Once you've followed them, if you still experience issues can you let me know the steps you have done, where you're seeing the issue and share a screenshot as well as that will help with further troubleshooting.

**Comment by Jenefer-Monroe** [comment]
I think the Desktop Flows issue in PBI is likely the old isSystemUser error we saw in the past which we've fixed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
