### ISSUE TITLE
Use ALM Accelerator with Multiple tenant and Environments

### ISSUE THREAD

**Issue by almpocahb** [microsoft/coe-starter-kit#3815]
### What is your question?

How we can use/configure the ALM Accelerator with multiple tenant ?
How to configure more than 3 environments ( Validation - Test- Prod )  ex I have 5 environments ?
Can I change the naming of ( Validation - Test- Prod ) with my own names ?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220831.2

**Comment by mikefactorial** [comment]
@almpocahb currently the ALM Accelerator doesn't support multiple tenants. See https://github.com/microsoft/coe-starter-kit/issues/3161

As far as configuring more than the standard 3 environments. This requires some additional configuration using self-hosted or what we're calling "bring your own pipelines".  See https://learn.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-pipelines#customize-the-number-of-deployment-steps-in-your-pipelines-and-the-names-of-the-target-environments

**Comment by mikefactorial** [comment]
Closing this out for now as there's no work to be done on the Accelerator side
