### ISSUE TITLE
[CoE Starter Kit - Feature]: Originating template

### ISSUE THREAD

**Issue by KlaudiaRoveri** [microsoft/coe-starter-kit#3817]
### Describe the solution you'd like

It would be great to see from which template PowerApps or PA flow is originated, especially for templates created and shared by customers, knowing which are resulting in creation of which number of apps and flows would be great information for adoption.

**Comment by Jenefer-Monroe** [comment]
Thank you for the suggestion. I dont know that this is given to us today from the product, do you happen to know? 
Will put on the backlog to investigate.

**Comment by manuelap-msft** [comment]
This was added recently, although we only have the Template ID not name.
