### ISSUE TITLE
Taking backup of model driven apps

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/coe-starter-kit#3818]
### What is your question?

Can you please let us know if there is any way to export model driven app like a canvas app which we can export as zip package?

Is there any powershell command or any power automate connector which can be used for this?

**Comment by manuelap-msft** [comment]
Hello,

this GitHub repo is focused on answering questions specific to the CoE Starter Kit and ALM Accelerator features, and is only monitored by the small team implementing those two kits. For more general Power Platform advice, and to get help from the larger Power Platform community and experts, please raise questions in the Power Users community: https://powerusers.microsoft.com/

Thank you
Manuela
