### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Connectors)

### ISSUE THREAD

**Issue by dgal0424** [microsoft/coe-starter-kit#3822]
### Describe the issue

I am unable to successfully run the Admin | Sync Template v3 (Connectors) flow. It fails after running for 20 minutes and error details are as follow "operation 'Update_Last_Run_Successful' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'"

### Expected Behavior

This flow is expected to run successfully. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.44

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

### Anything else?

Error details "The 'inputs.parameters' of workflow operation 'Update_Last_Run_Successful' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'"

**Comment by Jenefer-Monroe** [comment]
Hello, we have caught this failure in the upcoming Oct release. Its an error you can ignore and means you have not run the **_Admin | Sync Template v3 CoE Solution Metadata_** flow

Generally please be sure you have all the flows in [inventory setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) turned on and running.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
