### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Balitewicz** [microsoft/coe-starter-kit#3823]
### Describe the issue

September 2022 Power BI Dashboard will not load.  Microsoft Unified Support says this is a bug with the CoE Toolkit and not PowerBI.  Recommend we log a bug.  See attached for full details
[PowerBI COE Screenshots.docx](https://github.com/microsoft/coe-starter-kit/files/9686961/PowerBI.COE.Screenshots.docx)

### Expected Behavior

We expect the dashboard to load so we can publish it.  We are using the May dashboard instead

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2022 release

### What app or flow are you having the issue with?

Dashboard not a flow

### Steps To Reproduce

See attachment for steps

**Comment by Jenefer-Monroe** [comment]
Here are some troubleshooting tips from our documentation: [troubleshooting PBI setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#troubleshooting)

And then two very common issues are:
1. Please be sure you add the pre-fix and the trailing slash when you enter your orgurl: https://org12a11aa1.crm.dynamics.com/
2. Please be sure you have access to the org with the identity you are logged in to PBI with by browsing to that org url

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
