### ISSUE TITLE
[CoE Starter Kit - QUESTION] What is the 「Maker is Orphaned」 status in Power Apps Apps in Power Platform Admin View?

### ISSUE THREAD

**Issue by jbst2018** [microsoft/coe-starter-kit#3825]
### What is your question?

Hi,team.

What is the 「Maker is Orphaned」 status in Power Apps Apps in Power Platform Admin View?
If the status is Yes, does it mean the user doesn't exist in the Azure AD?

![image](https://user-images.githubusercontent.com/109139057/193546979-f6355c96-3436-4d51-b486-a90b407af894.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

**Comment by Jenefer-Monroe** [comment]
Thats correct. The user was not found in the AD

**Comment by jbst2018** [comment]
Thank you.

**Comment by Jenefer-Monroe** [comment]
Happy to help!
