### ISSUE TITLE
[ALM Accelerator - BUG]: Artifact drop already exists for build xxxxx

### ISSUE THREAD

**Issue by almpocahb** [microsoft/coe-starter-kit#3827]
### Describe the issue

I have tried "rerun failed jobs" option of deploy-validation-xxxx pipeline in order to approve the pull request since the pipeline failed in the execution for other issue.
(1)
![image](https://user-images.githubusercontent.com/114581811/193558722-98d2868d-b242-4d31-8347-60eed254aaa2.png)
(2)
![image](https://user-images.githubusercontent.com/114581811/193559029-304e7f0b-3803-4d37-9798-f46a53d93d4b.png)
 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220831.2

**Comment by mikefactorial** [comment]
@almpocahb this is a limitation in Azure DevOps. The deployment pipelines in the ALM Accelerator execute in two stages build/deploy. The build artifacts are created after the build pipeline runs. The benefit of this is that the artifacts are available for troubleshooting when / if the deployment fails, while the side effect is what you've noticed. 

In your specific case the recommendation would be to not rerun the pipeline from the pipeline itself, but instead to Requeue the approval check from the PR.
![image](https://user-images.githubusercontent.com/42348035/193597241-b1a0f067-a78d-4e90-9252-e4c53e4b1c2c.png)

**Comment by mikefactorial** [comment]
In the case of pipelines other than the validation pipeline you can run a new pipeline from the previous run.
![image](https://user-images.githubusercontent.com/42348035/193597855-e629e01a-9a74-47a4-ab39-3fd260ae5b0e.png)

**Comment by almpocahb** [comment]
Thank @mikefactorial  your answer is clear
