### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by rehenerginet** [microsoft/coe-starter-kit#3829]
### Describe the issue

In the flow Admin | Inactivity notifications v2 (Start Approval for Apps) in Governance Components September release, there is a misspelling in the get_env_name action. It then fails to write the App name and Environment for app already set for deletion
![CoE_error](https://user-images.githubusercontent.com/106080539/193587496-a8c88e38-eb1d-4ac2-b437-19e5bfa14aa7.jpg)

### Expected Behavior

The flows writes back the Environment Name and App

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.21

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps)

### Steps To Reproduce

Everytime it runs

**Comment by rehenerginet** [comment]
action should refer to ['admin_appenvironmentname'] with an 'n'

**Comment by Jenefer-Monroe** [comment]
Thank you for investigating and posting. We have fixed this one already for Oct via https://github.com/microsoft/coe-starter-kit/issues/3683

Appreciate you posting to help make CoE great! I'll go ahead and close this one as a dupe.
