### ISSUE TITLE
[CoE Starter Kit - QUESTION] September Version Installation

### ISSUE THREAD

**Issue by JMMora** [microsoft/coe-starter-kit#3834]
### What is your question?

Hello, hope you can help me

I have installed from scratch September version, that's include new environment, etc. facing the below issues

1.- PowerBI is not pulling information, and everything is correct during configuration
2.- Command Center giving error as: CommanCentreAppL InitiallyPopulateBookmarks.Run Failed: Connection not configured for this service, and I did perform all the steps for the configuration

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

**Comment by Jenefer-Monroe** [comment]
Do you have the [inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) running and is there data populated in the **_Power Platform Admin View_** app?

**Comment by JMMora** [comment]
All Flows are running as the instructions.

the Power Platform Admin View does not show any data and I am logging with my global Admin Role Account

![image](https://user-images.githubusercontent.com/16048560/193638759-60d8265f-02ec-493c-80fd-7a4ee90f77e8.png)

**Comment by Jenefer-Monroe** [comment]
When did you install? The first run takes a while. Please look at **_Admin | Sync Template v3_**, has it completed a run yet? 
![image](https://user-images.githubusercontent.com/89584709/193642599-d1a99190-9a51-4166-94a4-9c64e740214d.png)

**Comment by JMMora** [comment]
That one I found it running on the Step Delay Inventory for  720 minutes, right now I re-running
Admin | Sync Template v3 CoE Solution Metadata
Admin | Sync Template v3 Configure Emails
Admin | Sync Template v3 (Connectors)

and then I will check again: Admin | Sync Template v3

**Comment by JMMora** [comment]
Hi, I see data now, however getting some errors on new flow I haven't see before, posting details below

The command Admin Center still with same error:CommanCentreAppL InitiallyPopulateBookmarks.Run Failed: Connection not configured for this service, and I did perform all the steps for the configuration

Admin | Sync Template v3 (Portals): Action 'Insert_Portal_Website_' failed

Admin | Sync Template v3 (Flow Action Details)

Action 'Get_Flow_Permissions_Check' failed
The caller object id is 'eee9c0d0-1a06-4f7f-bf5b-8b2594a6a3d9'. Connection '70d034d7-591a-411c-807b-568f3adf41da' to 'shared_logicflows' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow.

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately we can't track a bunch of issues in one bug. Its just too hard to track. It looks like we have resolved your original issue so please create new issues for remaining problems. 

Before posting though, here are a few ideas:

### CommanCentreAppL InitiallyPopulateBookmarks.Run Failed: Connection not configured for this service, and I did perform all the steps for the configuration
Be sure you have set the [set flow run-only users properties](https://learn.microsoft.com/power-platform/guidance/coe/faq#set-flow-run-only-users-properties) for this flow **_Command Center App > Initially Populate Bookmarks_**. This is needed (amongst other reasons) if you have installed with a different user than you are managing with, which is sounds like is the case for you. 

### Invalid Connections
It sounds like you might have installed as a different user than you are logging in with. There are co-auth limitations in flow and so you will need to fix up the connections if you are trying to do this. See [Co-authoring and Connections](https://learn.microsoft.com/power-platform/guidance/coe/limitations#co-authoring-and-connections)

**Comment by JMMora** [comment]
understood Thanks

**Comment by Jenefer-Monroe** [comment]
closing out as no further action on this item
