### ISSUE TITLE
[ALM Accelerator - Feature]: Metadata validation

### ISSUE THREAD

**Issue by filcole** [microsoft/coe-starter-kit#3839]
### Is your feature request related to a problem? Please describe.

It would be great if the ALM accelerator could assist with adoption of development standards for PowerPlatform Solutions.  E.g naming conventions for tables, columns, option set prefixes, etc.

There exists the AttributeNamingChecker in XrmToolbox, but that is not part of a pipeline.

### Describe the solution you'd like

Block or warn upon solution export if development standards are breached with a means to except some components (individually or in bulk).

### Describe alternatives you've considered

Using AttributeNameManager manually. But that only covers attributes and there so much more.

**Comment by mikefactorial** [comment]
@filcole as always love this input. We've been working with another team on adding customtemplates to our hooks to allow this type of functionality to be opted into. May not become part of our pipelines directly but would love to add this as an opt in function via hooks https://github.com/microsoft/coe-alm-accelerator-templates/tree/main/Pipelines/Templates/Hooks/CustomTemplates

**Comment by mikefactorial** [comment]
For reference https://github.com/microsoft/coe-alm-accelerator-templates/pull/177

**Comment by mikefactorial** [comment]
Closing this out as there's nothing for the CoE Team to do today.
