### ISSUE TITLE
Licence required to respond to flow through adaptive card

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#3841]
### What is your question?

Hi,

is for the users, which respond to the flow '[Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created](https://learn.microsoft.com/en-us/power-platform/guidance/coe/governance-components#microsoft-teams-admin--ask-for-business-justification-when-microsoft-teams-environment-is-created)' a premium licence required because the flow updates dataverse with the input of the adaptive card?

Best regards
Lukas

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

September 2022

### What app or flow are you having the issue with?

Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created

**Comment by Jenefer-Monroe** [comment]
The goal of the adaptive cards is exactly that, to remove the need to have a premium license for those users.

**Comment by lukas-nC** [comment]
thanks

**Comment by Jenefer-Monroe** [comment]
You bet!
