### ISSUE TITLE
AA4PP Setup issue

### ISSUE THREAD

**Issue by nickshepherd1983** [microsoft/coe-starter-kit#3844]
### What is your question?

Hello,

I am currently developing the AA4PP to our tenant using the QuickStart method. I believe I have completed the step described in the documentation however, when I start the "ALM Accelerator for Power Platform" CanvasApp I get the following error/message "GetEnviromentSolutions.Run failed: Connection not configured for this service."

Also, should the repo pipelines repo be  empty after it's creation; should this be the case?

I had to manually add the content from https://github.com/microsoft/coe-alm-accelerator-templates to the empty repo, is this the expected behavioral?

Any assistance in resolving this issue would be greatly appreciated.

Cheers,

Nick
![MicrosoftTeams-image](https://user-images.githubusercontent.com/10635378/193847593-538591ec-83dd-4fc9-b8b3-95286df8fbcd.png)

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

October 2022

**Comment by mikefactorial** [comment]
@nickshepherd1983 can you verify that all of the flows are turned on in the solution and if the user running the app has the ALM Power App Access role? 
![image](https://user-images.githubusercontent.com/42348035/193871408-145b93fb-0872-4ee4-8790-f414d10d5e69.png)

Related to the templates repo being empty. Can you share the combined.log file that got generated during the quick start run?

**Comment by nickshepherd1983** [comment]
Hi, Mike!

It looks like the flows where disabled, I've gone in and turned them on and the issue seems to have been resolved, I must have missed that step in the instruction. Thank you!

Where would I find the combined.log file?

**Comment by mikefactorial** [comment]
Thanks for getting back to me @nickshepherd1983. You shouldn't have needed to activate the flows manually. Something may have gone wrong in the cli setup process. The combined.log would be in the root directory of the coe-cli where you ran the install from.

**Comment by nickshepherd1983** [comment]
Unfortunately I ran the CLI in a docker container and I have since stopped/delete the container so the .log file is no more :(
