### ISSUE TITLE
Error in Admin | Sync Template v3 (Flow Action Details) / HELPER – CloudFlowOperations

### ISSUE THREAD

**Issue by mduqueBasf** [microsoft/coe-starter-kit#3845]
Hi. This Flow is bad programed so it is leaving my admin account as the owner of all Flows in the Tenant

In Core Components In the Flow “Admin | Sync Template v3 (Flow Action Details)” in the action “Remove Admin”
Inside: Get Flow Action Details / Get Specialty Action Details / if Specialty Actions Exist, add them / Yes / get flow defn / reset permissions / if needed permissions, set them back / True / Remove Admin

![image](https://user-images.githubusercontent.com/64835119/193860122-eb829fea-0afe-4a3a-a3cf-8f102446315f.png)
It sets the action to “removeuser”

If we go to the child Flow “HELPER – CloudFlowOperations”: Manually Trigger a flow / action
![image](https://user-images.githubusercontent.com/64835119/193860223-bd294ad6-9ef2-4e4c-9382-877520da1e79.png)
There is no such action so as a consequence the new temporarily admin is not removed:  
![image](https://user-images.githubusercontent.com/64835119/193860283-19f3243f-7820-4406-9e09-645d814d9f34.png)

**Comment by Jenefer-Monroe** [comment]
Do you know when this happens? What app / flow is calling the helper?

**Comment by Jenefer-Monroe** [comment]
This is only called for flows that have a subset of connectors that we want to do extra work on (ex Http connector) so this should not impact most of your flows. 
And then the helper function does have this action. It's likely that you have an unmanaged layer on the helper flow which prevented you from receiving updates. Can you please check? [Remove unmanaged layers](https://learn.microsoft.com//power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows)
![image](https://user-images.githubusercontent.com/89584709/193864480-82a24394-670b-49ed-ab4e-85f68b6fb90f.png)

**Comment by mduqueBasf** [comment]
Yes

In Core Components In the Flow “Admin | Sync Template v3 (Flow Action Details)”


Manuel Duque Muriel
DevOps - Office 365 Collaboration

Mobile: +34 60 0200146, Email: ***@***.***
Postal Address: BASF Digital Solutions S.L., Paseo de la Castellana, 77, 28046 Madrid, Spain
***@***.***
BASF Digital Solutions GmbH, Registered Office: 67061 Ludwigshafen, Germany
Companies' Register: Amtsgericht Ludwigshafen, HRB 3541
Managing Directors:
Lars Rosendahl, Stefan Beck, Petra Scheithe
Chairman of the Supervisory Board: Christoph Wegner

Information on data protection can be found here: https://www.basf.com/global/en/legal/data-protection-at-basf.html





From: Jenefer Monroe ***@***.***>
Sent: Tuesday, October 4, 2022 5:39 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Manuel Duque Muriel ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [microsoft/coe-starter-kit] Error in Admin | Sync Template v3 (Flow Action Details) / HELPER – CloudFlowOperations (Issue #3845)


Do you know when this happens? What app / flow is calling the helper?

**Comment by mduqueBasf** [comment]
Hi Jenefer.

I had one unmanaged layer in the Helper (I don’t know why because I did not develop anything there). I have removed the unmanaged layer. I will then update the COE to the latest solution and I will reopen the Helper to see if there are changes. Also to see if all those Flows disappear from my behalf.

Regards,


Manuel Duque Muriel
DevOps - Office 365 Collaboration

Mobile: +34 60 0200146, Email: ***@***.***
Postal Address: BASF Digital Solutions S.L., Paseo de la Castellana, 77, 28046 Madrid, Spain
***@***.***
BASF Digital Solutions GmbH, Registered Office: 67061 Ludwigshafen, Germany
Companies' Register: Amtsgericht Ludwigshafen, HRB 3541
Managing Directors:
Lars Rosendahl, Stefan Beck, Petra Scheithe
Chairman of the Supervisory Board: Christoph Wegner

Information on data protection can be found here: https://www.basf.com/global/en/legal/data-protection-at-basf.html





From: Jenefer Monroe ***@***.***>
Sent: Tuesday, October 4, 2022 5:44 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Manuel Duque Muriel ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [microsoft/coe-starter-kit] Error in Admin | Sync Template v3 (Flow Action Details) / HELPER – CloudFlowOperations (Issue #3845)


This is only called for flows that have a subset of connectors that we want to do extra work on (ex Http connector) so this should not impact most of your flows.
And then the helper function does have this action. It's likely that you have an unmanaged layer on the helper flow which prevented you from receiving updates. Can you please check? Remove unmanaged layers<https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows>
[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F193864480-82a24394-670b-49ed-ab4e-85f68b6fb90f.png&data=05%7C01%7Cmanuel.duque-muriel%40basf.com%7Ca921b9d4dc7348a46a5408daa61f4a8c%7Cecaa386bc8df4ce0ad01740cbdb5ba55%7C0%7C0%7C638004950570403233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LNV1E6xyhDLHl%2BtKDmTxq13nVctkcr4Ll3Ks6mnoPMo%3D&reserved=0>

**Comment by Jenefer-Monroe** [comment]
Unmanaged layers can appear accidently unfortunately. When you use the Run Only Permissions settings, and even sometimes if you just open a flow to look at it in edit mode. 
Any situation in which you have accidently been assigned a flow will not auto-correct back as we dont have any flows like that. But you should not see further isssues.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
