### ISSUE TITLE
[CoE Starter Kit - Feature]: Options to provide Makers/Admins a Non Premium License Experience

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#3849]
### Is your feature request related to a problem? Please describe.

All of the CoE Canvas apps designed for Makers to engage with the CoE team require Premium licenses.

This is especially frustrating for compliance flows, or inactivity governance which is critical to the tenant.

For example the Compliance Flows will monitor (where allowed) environments for apps/chatbots that exceed the configured thresholds, and require them to go to the Developer Compliance Center, which requires a premium license.

In our case we are using the E5 Office Enablement for Power Platform for 3000+ people.  This enablement is standard only, not premium.

There are 2 areas that I believe the Office licensing is intended to accelerate automation in the Enterprise.  One is the Office 365 front end if you will, with backing flow automations, and we see a lot of this.

The other is the low code Maker that goes into Default and builds to help automate their day to day.  The result is a whole enterprise building over time, with a busy tenant.

The result is a 'logic error' in that we have a situation where 1000s of makers can make, and we cannot Govern with the CoE kit, even though we can detect them.

They are enabled to allow them to 'focus on what matters, and automate the rest' as the slogan goes I think.  However, it's a recipe for trouble without governance.

The options are to fully license everyone, which is not going to happen, not use the CoE, which would be a mistake, or hack a variant of the CoE that will use M365 products to at least give the Admins and Makers a chance to work towards a healthy tenant.

The low code maker persona for us, is not at the Team level where we would be assigning Premium licenses.  At the moment there are no barriers to being creative, as everyone is enabled via O365.  

I believe the CoE needs an 'alternate' path that makes use of standard licensing options such as M365 products (i.e. Forms, Lists, Teams, Email), and not rely strictly on Premium functionality.  This would also minimize our maintenance.

At the moment the CoE functionality, while, 'free' and you can certainly cherry pick what you want, it requires expensive Premium licensing to be used fully, in the areas you need it the most.   This means it is not 'free'.

Also, I don't believe you can PAYG enable the Default environment, which means adding environment management to the mix as well.

### Describe the solution you'd like

Alternate approach to CoE implementation that doesn't require premium licensing.

**Comment by Jenefer-Monroe** [comment]
Thanks for the feedback, whilst we certainly appreciate the challenges around licensing, the CoE starter kit is only a template implementation of administration and governance tooling to aid Power Platform adoption - outside the CoE kit, there's product capabilities or building your own solution using PowerShell, APIs and management connectors. The goal of the CoE kit is to govern Power Platform with Power Platform - as such, it is built entirely with platform features. It's not on our roadmap to offer similar capabilities that would be available with a Microsoft 365 license - we're a very small team maintaining the kit. If your requirements are not met by the kit, consider working with a Microsoft partner to implement a solution more tailored to your needs.

**Comment by peteredc** [comment]
Your work is appreciated.  Thank you!

**Comment by peteredc** [comment]
@Jenefer-Monroe @manuelap-msft 

Going a bit deeper into Compliance, Inactivity, Orphaned functionality in the CoE Kit,  can you tell me which of those areas would need a premium license by the Makers?

Compliance: Premium due to Canvas app for business justification etc
Inactivity: ?
Orphaned:? (adaptive cards needs...?)

I'm trying to figure out which of those functions can be turned on right now, as our makers only have the E5 entitlement for standard licensing.
