### ISSUE TITLE
[Admin | Sync Template v3 (Connection Identities) flow fails against large Power Apps environment

### ISSUE THREAD

**Issue by klocklo** [microsoft/coe-starter-kit#3851]
### Describe the issue

The default flow: "Admin | Sync Template v3 (Connection Identities)" generates a page results size error in large Power Apps environments. 

### Expected Behavior

The flow should run without failing 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

### Steps To Reproduce

Allow the Sync Template v3 (Connection Identities) flow to run in a large environment.
Error:
Action 'Get_Connections_as_Admin' failed
Error Details:
The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '209801907' bytes. This exceeded the maximum size '209715200' bytes allowed.

**Comment by Jenefer-Monroe** [comment]
Hello, this is an action of an out of the box connector we're using. Unfortunately, it has a size limitation that you have exceeded. 

We cannot fix this, but you can manually clean up some of the old connections via Power Shell and then be under the size limit. We have documented this limitation here along with a starter solution to address via PowerShell: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#set-up-connection-cleanup-broken-connections

Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Jenefer-Monroe** [comment]
There were product limitations in the PowerShell hence we had to take it offline. I'm afraid you'll need to post a product support ticket telling them that you cannot use this action **_'Get_Connections_as_Admin'_** 
As you get this failure:
The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '209801907' bytes. This exceeded the maximum size '209715200' bytes allowed.

**Comment by AnchalBerwal** [comment]
@Jenefer-Monroe Can you please guide me to the process for raising product support ticket?
