### ISSUE TITLE
[CoE Starter Kit - QUESTION]  "Admin-Command Center"　InitiallyPopulateBookmarks.Run failed

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#3852]
### What is your question?

I get an error when I open the "Admin-Command Center".
The error message is as follows

`CommandCenterApp>InitiallyPopulateBookmarks.Run failed: Connection not configured for this service.
`

There was a similar story in issue number #3648 .
The version is 3.45 as well.
Command Center App > Initially Populate Bookmarks is set to Use this connection (my account).
The following four flows are also turned on.
・Command Center App   > Get M365 Service Messages
・Command Center App > Initially   Populate Bookmarks
・Command Center App > Get CoE Flows
・Command Center App > Set CoE Flows   State

I wonder what else is wrong and what is causing the error. Please let me know.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

**Comment by egym07** [comment]
Same as yours: Use this connection (my account). Is this correct?
Also, is that setting just the "Command Center App > Initially Populate Bookmarks" flow?

**Comment by Jenefer-Monroe** [comment]
Can you try with Provided by run only user? If that doesnt work, can you please let me know, is the flow called and if so, where does it fail?

**Comment by egym07** [comment]
Thank you! Error gone without incident!
My question is, why did the "Provided by run only user" connection now work?

**Comment by egym07** [comment]
Let me ask one more question in conjunction with this one.

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

I would like to follow the steps in #8 of the URL, but "Use this connection (my account)" does not appear for Dataverse only. Why is this?

**Comment by Jenefer-Monroe** [comment]
I'm afraid this setting is a little finicky and so I will not be able to explain very well how this all works. The recommendation is to use "Provided by run only user" in this case, but it does sometimes work for other values.

**Comment by egym07** [comment]
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

Step 8 of this URL says "Use this connection (my account)."
However, I cannot switch only Dataverse.
As well, does this mean that sometimes it works with "Use this connection (my account)" and sometimes it works with "Provided by run only user"?

**Comment by Jenefer-Monroe** [comment]
This setting is really finicky, as I said. We can put on the backlog doing some more exploration and make the documentation clearer, but for now, you should do the one that works for you. 

For the dataverse issue, we've seen a few people hit that recently and think there may be a product bug. Please make sure you have a Dataverse connection created in the environment, and then if you do, but it does not get offered here, that woudl be something you need to post a support ticket for.

**Comment by egym07** [comment]
I see. I understood that it is not possible to decide in general that this is the way to set it up in this case. Thank you very much.

Does this mean that the bug in this case is caused by CoEStarterKit? Or is it PowerPlatfrom?

**Comment by Jenefer-Monroe** [comment]
We think there is an issue with the product. Please see this other bug where other people saw the issue for this connector as well. 
https://github.com/microsoft/coe-starter-kit/issues/3820

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
