### ISSUE TITLE
[CoE Starter Kit - QUESTION] PowerBI License

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#3853]
### What is your question?

I do not have a PowerBIPro license. Also, I am a user who has not set up CoEStarterKit. Another user has done the setup.
If I want to view PowerBI reports and dashboards, can such a user still view the reports in My Workspace by following the steps as described in the URL below? If so, do I need to give them security roles?
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

**Comment by Jenefer-Monroe** [comment]
I'm afraid I'm not a Power BI license expert but my understanding matches yours. A non-PowerBi Pro user would need to recreate the report in their own workspace which would require they have appropriate security roles. 
The SR could either be sysadmin on that environment, or we ship this SR for the Admin persona as well: [Power Platform Admin SR ](https://learn.microsoft.com/power-platform/guidance/coe/core-components#security-roles)

Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
