### ISSUE TITLE
[Power Platform Hub] Deployment Failed Error

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#3859]
### Describe your bug, question or feature ask.

I have ran the script and updated the owner email and tenant parameters.

PS C:\Users\nasilvae> C:\Users\nasilvae\Downloads\PowerPlatformHub\Deploy-PowerPlatformHub.ps1
INFO: PnP.PowerShell module is already installed.
INFO: Connecting to SharePoint Online
INFO: Creating new site...
...INFO: Connecting to newly created site
INFO: Wait 15 seconds to make sure the site is ready...
INFO: Deploying template...
ERROR: Template deployment failed with error. File not found
ERROR: File not found
ERROR: Removing site collection...
ERROR: Site collection removed. Restart deployment to roll out the Power Platform Hub.
ERROR: Deployment of Power Platform Hub failed!
PS C:\Users\nasilvae>

**Comment by Laskewitz** [comment]
Hi @nasilvae -

It looks like the template file was not found - probably because you didn't `cd` into the right directory. Can you cd into the right directory (in your case it's probably `cd C:\Users\nasilvae\Downloads\PowerPlatformHub\`) and then try running the script again?

I hope that will fix it. Let me know if this helps.

**Comment by nasilvae** [comment]
Hi I did get futher this time got a graph going on but then it stopped :(. 

                                                                                                                        PS C:\WINDOWS\system32> cd C:\Users\nasilvae\Downloads\PowerPlatformHub\                                                PS C:\Users\nasilvae\Downloads\PowerPlatformHub> .\Deploy-PowerPlatformHub                                              INFO: PnP.PowerShell module is already installed.                                                                       INFO: Connecting to SharePoint Online                                                                                   INFO: Creating new site...                                                                                              .INFO: Connecting to newly created site
INFO: Wait 15 seconds to make sure the site is ready...
INFO: Deploying template...
ERROR: Template deployment failed with error. Value cannot be null.
Parameter name: clientObject
ERROR: Value cannot be null.
Parameter name: clientObject
ERROR: Removing site collection...
ERROR: Site collection removed. Restart deployment to roll out the Power Platform Hub.
ERROR: Deployment of Power Platform Hub failed!
PS C:\Users\nasilvae\Downloads\PowerPlatformHub>

**Comment by petepuu** [comment]
@nasilvae, can you try to enable PnP tracing using Set-PnPTraceLog before starting the script. This way you should be able to see more info about error. That error does not tell much "ERROR: Value cannot be null. Parameter name: clientObject". With tracing you should see in which step the template deployment failed

https://pnp.github.io/powershell/cmdlets/Set-PnPTraceLog.html

**Comment by nasilvae** [comment]
Hi @petepuu,

I have the following message: 

PS C:\Users\nasilvae\Downloads\PowerPlatformHub> Set-PnPTraceLog -On -LogFile traceoutput.txt
PS C:\Users\nasilvae\Downloads\PowerPlatformHub> .\Deploy-PowerPlatformHub
INFO: PnP.PowerShell module is already installed.
INFO: Connecting to SharePoint Online
INFO: Creating new site...
.INFO: Connecting to newly created site
INFO: Wait 15 seconds to make sure the site is ready...
INFO: Deploying template...
ERROR: Template deployment failed with error. The object id "site:7d5a05d7-13cb-493c-a89b-80d1f7ea030d:web:d055dd84-6b1c-4182-a349-d86159b4a892:list:6cac79bd-2595-4d73-ab7f-d20c6e54389b" is invalid. System.Management.Automation.ParseException: At line:1 char:3
+  [-IndentSize <Int32>] [-AutoFlush <Boolean>] [<CommonParameters>]
+   ~
Missing type name after '['.

At line:1 char:15
+  [-IndentSize <Int32>] [-AutoFlush <Boolean>] [<CommonParameters>]                                                    +               ~                                                                                                       The '<' operator is reserved for future use.                                                                                                                                                                                                    At line:1 char:36                                                                                                       +  [-IndentSize <Int32>] [-AutoFlush <Boolean>] [<CommonParameters>]                                                    +                                    ~
The '<' operator is reserved for future use.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options) System.Management.Automation.ParseException: At line:1 char:33
+ Set-PnPTraceLog [-On] [-LogFile <String>] [-WriteToConsole] [-Level < ...
+                                 ~
The '<' operator is reserved for future use.

At line:1 char:69
+ ... raceLog [-On] [-LogFile <String>] [-WriteToConsole] [-Level <LogLevel ...
+                                                                 ~
The '<' operator is reserved for future use.

At line:1 char:93
+ ... <String>] [-WriteToConsole] [-Level <LogLevel>] [-Delimiter <String>]
+                                                                 ~
The '<' operator is reserved for future use.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options) Value cannot be null.
Parameter name: clientObject
ERROR: The object id "site:7d5a05d7-13cb-493c-a89b-80d1f7ea030d:web:d055dd84-6b1c-4182-a349-d86159b4a892:list:6cac79bd-2595-4d73-ab7f-d20c6e54389b" is invalid. System.Management.Automation.ParseException: At line:1 char:3
+  [-IndentSize <Int32>] [-AutoFlush <Boolean>] [<CommonParameters>]
+   ~
Missing type name after '['.

At line:1 char:15
+  [-IndentSize <Int32>] [-AutoFlush <Boolean>] [<CommonParameters>]                                                    +               ~                                                                                                       The '<' operator is reserved for future use.                                                                                                                                                                                                    At line:1 char:36                                                                                                       +  [-IndentSize <Int32>] [-AutoFlush <Boolean>] [<CommonParameters>]                                                    +                                    ~                                                                                  The '<' operator is reserved for future use.                                                                               at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)                                        at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options) System.Management.Automation.ParseException: At line:1 char:33
+ Set-PnPTraceLog [-On] [-LogFile <String>] [-WriteToConsole] [-Level < ...
+                                 ~
The '<' operator is reserved for future use.

At line:1 char:69
+ ... raceLog [-On] [-LogFile <String>] [-WriteToConsole] [-Level <LogLevel ...
+                                                                 ~
The '<' operator is reserved for future use.

At line:1 char:93
+ ... <String>] [-WriteToConsole] [-Level <LogLevel>] [-Delimiter <String>]
+                                                                 ~
The '<' operator is reserved for future use.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options) Value cannot be null.
Parameter name: clientObject
ERROR: Removing site collection...
ERROR: Site collection removed. Restart deployment to roll out the Power Platform Hub.
ERROR: Deployment of Power Platform Hub failed!

**Comment by petepuu** [comment]
@nasilvae, can you test by manually creating new communication site collection and then in powershell run this in that same folder where you have the template.pnp

Connect-PnPOnline -Url https://TENANTNAME.sharepoint.com/sites/powerplatformhub -Interactive
Invoke-PnPSiteTemplate -Path template.pnp

**Comment by petepuu** [comment]
@nasilvae, as we discussed in Teams chat great that site was created with all pages, assets and events even you got those errors  :)

According to couple of PnP issues I found, error you got might relate to case when site is deleted and recreated 

powershell.exe Error: 0 : 2022-10-05 13:53:59.7551	[PnP.Framework]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: **The object id "site:7d5a05d7-13cb-493c-a89b-80d1f7ea030d:web:d055dd84-6b1c-4182-a349-d86159b4a892:list:6cac79bd-2595-4d73-ab7f-d20c6e54389b" is invalid.**

https://github.com/pnp/PnP-Sites-Core/issues/2025#issuecomment-559701527
https://github.com/pnp/PnP-Sites-Core/issues/2019#issuecomment-470516254

**Comment by Laskewitz** [comment]
Closing because the site was deployed correctly.
