### ISSUE TITLE
[ALM Accelerator - Feature]: More Environment Details needed in Azure DevOps Projects - Preview

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#3864]
### Is your feature request related to a problem? Please describe.

Please add also the Environment ID / URL / Type to the list:
![image](https://user-images.githubusercontent.com/15800069/194138609-4e7692f3-566b-43fe-b84b-3ddc13026ce9.png)

Question: Why does my list contains an empty environment
Problem: Sometimes an environment can't be renamed (Developer Environments)

### Describe the solution you'd like

List contains additional information:
* Environment ID
* Environment URL (when possible)
* Environment Type

**Comment by mikefactorial** [comment]
Yep. Agree. Thanks @megel

**Comment by jenschristianschroder** [comment]
This is what the Environment Dropdown will look like. If you hover an item it will display full string of [Name] ([Type]) ([orgUrl])

![image](https://user-images.githubusercontent.com/24893229/194870169-268c8139-d78a-4e1d-ba26-87d00df41c32.png)

**Comment by megel** [comment]
Works perfect for me - sorry haven't read the comments 😅 I was a little bit busy with vacation preparation.
