### ISSUE TITLE
[Power Platform Hub] ISSUE TITLE

### ISSUE THREAD

**Issue by RakeshPower** [microsoft/coe-starter-kit#3867]
### Describe your bug, question or feature ask.

Hi Team,

Unable to find templates to download and ps1 script to create hub site at the target location: https://learn.microsoft.com/en-us/power-platform/guidance/adoption/wiki-community#create-an-internal-wiki

Could you please share the path. Thanks 
![image](https://user-images.githubusercontent.com/115120204/194178477-b871778a-7423-4e4d-808c-0b07af88d7ee.png)
![Powerhub](https://user-images.githubusercontent.com/115120204/194178652-a56ef755-19e5-404b-8c3e-93ba9786656d.JPG)

**Comment by Laskewitz** [comment]
There was an issue with the learn site, but it should be working now. Can you confirm, @RakeshPower?

**Comment by manuelap-msft** [comment]
We had a temporary issue with our documentation site, the content is now back up here: https://learn.microsoft.com/en-us/power-platform/guidance/adoption/wiki-community#get-started-with-the-power-platform-communication-site-template

Thanks for notifying us!
