### ISSUE TITLE
[Power Platform Hub] Deployment fails with Method not found (Invoke-PnPSiteTemplate)

### ISSUE THREAD

**Issue by P3N-101** [microsoft/coe-starter-kit#3868]
### Applying the template fails on ClientSidePages...
![image](https://user-images.githubusercontent.com/70491094/194187547-f1dc9778-8729-4d39-be68-75824a0ee25b.png)

**Comment by petepuu** [comment]
@P3N-101 do you have latest PnP.PowerShell module installed? https://www.powershellgallery.com/packages/PnP.PowerShell

**Comment by bhishma** [comment]
same issue.  have PnP v1.11.0 installed. 

`Invoke-PnPSiteTemplate : Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> Enumerator.MoveNextAsync()'.`

**Comment by petepuu** [comment]
Weird, I have 1.11 no issues and my customer installed hub yesterday with 1.11 no issues. What PS version you are using?

**Comment by bhishma** [comment]
I ran it in VSCode- that failed. Regular PowerShell (v5.x) worked.

**Comment by petepuu** [comment]
@bhishma good that you was able to the provisioning working. VSCode supports both 5.1 and 7 so in curiosity what is your exact installed version? I have 7.2.6 and script worked with that

<img width="316" alt="image" src="https://user-images.githubusercontent.com/8307644/195923737-044ac2b6-86aa-4002-9575-297f96b894bb.png">

**Comment by Laskewitz** [comment]
Yeah this feels a bit weird. Apart from the fact that PnP PowerShell should work on v5 en v7 - VS Code should work with both as well.

**Comment by bhishma** [comment]
VSCode also has 5.1. But failed in 2 different tenants. I was able to get the template applied in both using PowerShell (outside of VSCode).

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by Laskewitz** [comment]
Closing issue - template was successfully applied using PowerShell.
