### ISSUE TITLE
[ALM Accelerator - QUESTION] Deployment Step entity

### ISSUE THREAD

**Issue by fredrikhr** [microsoft/coe-starter-kit#3870]
### What is your question?

I have opened a Deployment Step record using the ALM Accelerator for Power Platform Administration model-driven app.

## Question 1

There are two possible values for `Step Type`: `Development` and `Deployment`. What is selecting `Development` supposed to do?

## Question 2

What effect will the different values for `Approval Type` have? I understand `Pull Request` will open a PR when clicking `Deploy solution` in the canvas app, will the canvas app do something else for `Environment`? Will it straight up deploy to target with no other checks when `None` is selected?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20220831.2

**Comment by mikefactorial** [comment]
The specific scenario is I want to be able to import a solution that has connections, environment variables etc. all wired up from source control.

**Comment by fredrikhr** [comment]
@mikefactorial Interesting, but you only answered my first question, what about the second one?

**Comment by mikefactorial** [comment]
Yep I'm working on it.

**Comment by mikefactorial** [comment]
Patience is a virtue. Pull request approval types assume a PR is created when a deployment is requested. None or environment assume you are going to run the deployment pipeline directly and the approvals will be handled outside of the PR process. You can configure an environment level approval in DevOps or have no approval. The app will just run the associated deployment pipeline directly if you specify none or environment level approval

**Comment by fredrikhr** [comment]
Cool! I'll play with it :+1: thanks!
