### ISSUE TITLE
[Power Platform Hub] Set-PowerPlatformHubAsDLPErrorSettings.ps1 fails if DLP setting exists already in tenant

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#3871]
### Describe your bug, question or feature ask.

When running the Set-PowerPlatformHubAsDLPErrorSettings.ps1 script it will fail to error 409 Conflict if there is DLP setting defined already in the tenant. Script should have logic to first check does the DLP setting exists and if yes then remove existing and create new or update existing using Set-PowerAppDlpErrorSettings command. Probably good to prompt and get confirmation from the user that existing will be updated

<img width="397" alt="image" src="https://user-images.githubusercontent.com/8307644/194249372-e4c70c09-b203-42dc-902b-e3984ae10792.png">

**Comment by Laskewitz** [comment]
Working on a fix. Should be ready soon.

**Comment by Laskewitz** [comment]
The script is now updated and will update the error settings if they already exist. Link to the script: https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/PowerPlatformHub/Set-PowerPlatformHubAsDLPErrorSettings.ps1

Thanks for reporting the issue.
