### ISSUE TITLE
[CoE Starter Kit]- Developer Compliance Centre Showing up all the CRM Apps

### ISSUE THREAD

**Issue by Raval2616** [microsoft/coe-starter-kit#3872]
Hi Team,
Developer Compliance Centre showing up all the CRM apps and flows for one of the Admins. 
<img width="1054" alt="DCC" src="https://user-images.githubusercontent.com/115143171/194258090-e70bcb5d-05d3-4e65-969e-8713e450725b.PNG">

Can you please help to let us know why is it showing like that and also how to resolve it.

Thanks in advance

**Comment by Jenefer-Monroe** [comment]
I'm not sure what you are trying to accomplish here. 
All Objects will mean all the objects (apps/flows/etc) to which the logged in user is owner
Toggling this off just gets the objects which have been requested for compliance details. 

If you want to see the apps intended for the CoE you can see those in the [Admin - Command Center](https://learn.microsoft.com/power-platform/guidance/coe/core-components#admin---command-center)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for coe starter kit team
