### ISSUE TITLE
[CoE Starter Kit - BUG] All of the Overview Tiles have "Top PowerApp / Flow Maker Cities" on the Coe PowerBI display are Blank

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#3880]
### Describe the issue

The Overview Tiles all have the Top PowerApp, Flows etc Maker Cities map are blank -
![image](https://user-images.githubusercontent.com/8484048/194322210-88a48161-b58d-4c56-ae2e-1a20c27f1b77.png)

This is because the cities column in the PowerApps / Flow etc tables in the Center of Excellence Dataverse are blank -

![image](https://user-images.githubusercontent.com/8484048/194322564-8076a85f-875b-4207-aa30-abe76266ba91.png)

### Expected Behavior

I expect the map to zoom into a town or city 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Admin - Sync Template V3

### Steps To Reproduce

In the centre of Excellence environment display the CoE Dashboard

**Comment by Jenefer-Monroe** [comment]
Can you see if this same bug repros in the **_Power Platform Admin View_** app when you look at the object or at maker? Note you'll need to add the column in order to test this
![image](https://user-images.githubusercontent.com/89584709/194339013-487d8255-3fd5-401a-8a68-4f12eaaa53f0.png)

**Comment by NPrice99** [comment]
![image](https://user-images.githubusercontent.com/8484048/194340132-ad5eb8d0-4982-4e19-8c87-6882134a33c3.png)

yes

**Comment by Jenefer-Monroe** [comment]
Can you please run the **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** flow to see if that resolves it for the Maker table for all users that have a City in the AD?

**Comment by NPrice99** [comment]
Hi @Jenefer-Monroe 
I have run the PowerAutomate flow and the city on the makers table is still blank.
![image](https://user-images.githubusercontent.com/8484048/194384618-f382727a-13f9-43ed-8365-d2741c836443.png)


  "@odata.context": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/$metadata#admin_powerplatformusers/$entity",
  "@odata.type": "#Microsoft.Dynamics.CRM.admin_powerplatformuser",
  "@odata.id": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)",
  "@odata.etag": "W/\"4198871\"",
  "@odata.editLink": "admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)",
  "admin_department": "Central Government",
  "admin_groupsize@OData.Community.Display.V1.FormattedValue": "1",
  "admin_groupsize": 1,
  "admin_userprinciplenamewithoutspecialchars": "Nigel.Price@civicadwp.onmicrosoft.com",
  "_owningbusinessunit_value@OData.Community.Display.V1.FormattedValue": "org57f46573",
  "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "owningbusinessunit",
  "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname": "businessunit",
  "_owningbusinessunit_value@odata.type": "#Guid",
  "_owningbusinessunit_value": "76b50314-77c3-ec11-a7b5-0022481b939c",
  "admin_displayname": "Nigel Price",
  "statecode@OData.Community.Display.V1.FormattedValue": "Active",
  "statecode": 0,
  "statuscode@OData.Community.Display.V1.FormattedValue": "Active",
  "statuscode": 1,
  "admin_powerplatformuserid@odata.type": "#Guid",
  "admin_powerplatformuserid": "79991901-041a-4a0b-b675-0d1648539f81",
  "admin_recordguidasstring": "79991901-041a-4a0b-b675-0d1648539f81",
  "_createdby_value@OData.Community.Display.V1.FormattedValue": "Nigel Price",
  "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_createdby_value@odata.type": "#Guid",
  "_createdby_value": "9b00fc19-77c3-ec11-a7b5-0022481b939c",
  "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Nigel Price",
  "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "ownerid",
  "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_ownerid_value@odata.type": "#Guid",
  "_ownerid_value": "9b00fc19-77c3-ec11-a7b5-0022481b939c",
  "admin_userprincipalname": "Nigel.Price@civicadwp.onmicrosoft.com",
  "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Nigel Price",
  "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_modifiedby_value@odata.type": "#Guid",
  "_modifiedby_value": "9b00fc19-77c3-ec11-a7b5-0022481b939c",
  "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_owninguser_value@odata.type": "#Guid",
  "_owninguser_value": "9b00fc19-77c3-ec11-a7b5-0022481b939c",
  "createdon@OData.Community.Display.V1.FormattedValue": "4/27/2022 8:19 AM",
  "createdon@odata.type": "#DateTimeOffset",
  "createdon": "2022-04-27T08:19:54Z",
  "admin_type": "User",
  "versionnumber@OData.Community.Display.V1.FormattedValue": "4,198,871",
  "versionnumber@odata.type": "#Int64",
  "versionnumber": 4198871,
  "modifiedon@OData.Community.Display.V1.FormattedValue": "10/6/2022 5:29 PM",
  "modifiedon@odata.type": "#DateTimeOffset",
  "modifiedon": "2022-10-06T17:29:05Z",
  "owningbusinessunit@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/owningbusinessunit/$ref",
  "owningbusinessunit@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/owningbusinessunit",
  "ownerid@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/ownerid/$ref",
  "ownerid@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/ownerid",
  "createdby@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/createdby/$ref",
  "createdby@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/createdby",
  "createdonbehalfby@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/createdonbehalfby/$ref",
  "createdonbehalfby@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/createdonbehalfby",
  "modifiedby@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/modifiedby/$ref",
  "modifiedby@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/modifiedby",
  "modifiedonbehalfby@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/modifiedonbehalfby/$ref",
  "modifiedonbehalfby@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/modifiedonbehalfby",
  "owninguser@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/owninguser/$ref",
  "owninguser@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/owninguser",
  "owningteam@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/owningteam/$ref",
  "owningteam@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/owningteam",
  "admin_powerplatformuser_SyncErrors@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_SyncErrors/$ref",
  "admin_powerplatformuser_SyncErrors@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_SyncErrors",
  "admin_powerplatformuser_DuplicateMatchingRecord@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_DuplicateMatchingRecord/$ref",
  "admin_powerplatformuser_DuplicateMatchingRecord@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_DuplicateMatchingRecord",
  "admin_powerplatformuser_DuplicateBaseRecord@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_DuplicateBaseRecord/$ref",
  "admin_powerplatformuser_DuplicateBaseRecord@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_DuplicateBaseRecord",
  "admin_powerplatformuser_AsyncOperations@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_AsyncOperations/$ref",
  "admin_powerplatformuser_AsyncOperations@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_AsyncOperations",
  "admin_powerplatformuser_MailboxTrackingFolders@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_MailboxTrackingFolders/$ref",
  "admin_powerplatformuser_MailboxTrackingFolders@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_MailboxTrackingFolders",
  "admin_powerplatformuser_UserEntityInstanceDatas@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_UserEntityInstanceDatas/$ref",
  "admin_powerplatformuser_UserEntityInstanceDatas@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_UserEntityInstanceDatas",
  "admin_powerplatformuser_ProcessSession@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_ProcessSession/$ref",
  "admin_powerplatformuser_ProcessSession@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_ProcessSession",
  "admin_powerplatformuser_BulkDeleteFailures@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_BulkDeleteFailures/$ref",
  "admin_powerplatformuser_BulkDeleteFailures@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_BulkDeleteFailures",
  "admin_powerplatformuser_PrincipalObjectAttributeAccesses@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_PrincipalObjectAttributeAccesses/$ref",
  "admin_powerplatformuser_PrincipalObjectAttributeAccesses@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_powerplatformuser_PrincipalObjectAttributeAccesses",
  "admin_photoobjectid_imagedescriptor@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_photoobjectid_imagedescriptor/$ref",
  "admin_photoobjectid_imagedescriptor@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_photoobjectid_imagedescriptor",
  "admin_admin_connectionreferenceidentity_Connect@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_admin_connectionreferenceidentity_Connect/$ref",
  "admin_admin_connectionreferenceidentity_Connect@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_admin_connectionreferenceidentity_Connect",
  "admin_PowerPlatformUser_User@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_PowerPlatformUser_User/$ref",
  "admin_PowerPlatformUser_User@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_PowerPlatformUser_User",
  "admin_RPASessions_RunTriggeredBy_admin_Po@odata.associationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_RPASessions_RunTriggeredBy_admin_Po/$ref",
  "admin_RPASessions_RunTriggeredBy_admin_Po@odata.navigationLink": "https://xxxxxxxxcrm11.dynamics.com/api/data/v9.1/admin_powerplatformusers(79991901-041a-4a0b-b675-0d1648539f81)/admin_RPASessions_RunTriggeredBy_admin_Po"
}

I dont see a city here

Regards
Nigel

**Comment by Jenefer-Monroe** [comment]
This updates for me so you'll need to do a little more exploration.

Please go to AD and find one of your Makers that has a city. Note you will need to add the column to find this easily
![image](https://user-images.githubusercontent.com/89584709/194415699-ede4d00a-2077-488a-ab92-036e8ef8010e.png)

Then find the user in the **_Apply to each maker_** loop. Is the city returned from **_Get Maker_**? Does it set it in **_Update Maker_**?
![image](https://user-images.githubusercontent.com/89584709/194416329-3e1fe78e-e13c-4e17-90d2-aebd69fca917.png)

**Comment by NPrice99** [comment]
Apologies Jenefer

I have found the issue.  In the Tenancy that the CoE exists in, Azure AD does not have address attributes set up.

Apologies

Nigel
