### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by NicolasRevello** [microsoft/coe-starter-kit#3885]
### What is your question?

Hello,

I hope you are doing well.

I have the following questions:

- How do we create and implement Business Units both for environment access and app/flow accesses?

- What is the difference between power platform admin and business unit admins? (access and permissions)

- Can viewers interact with app functionality without access to flow?

Thanks a lot.

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid we are a very small team and only staffed to assist with questions related to the CoE Starter Kit. General questions about how to use BUs can be sent to the Power Platform Community https://powerusers.microsoft.com/, hopefully you will get some help there. 
And as it relates to the CoE Starter Kit, our solution is not geared towards row level security, it is intended for the Power Platform Admin persona for the tenant. 
Sorry we cannot be of more assistance.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for coe starter kit team
