### ISSUE TITLE
[CoE Starter Kit - QUESTION] New app records are not being added to PowerApps Apps in Dataverse.

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#3886]
### What is your question?

I have a question about Dataverse's PowerApps Apps.
I created a model driven app yesterday around 4pm and the data is not reflected in this Dataverse.
The app I created around 1pm is registered.
And, I looked at the Flows in Dataverse, the flows created yesterday around 4pm were registered here.

Please let me know why the records are not being added.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

**Comment by Jenefer-Monroe** [comment]
Unfortunately [unpublished model-driven apps](https://learn.microsoft.com/power-platform/guidance/coe/limitations#unpublished-model-driven-apps) are one of our inventory [limitations](https://learn.microsoft.com/power-platform/guidance/coe/limitations). We cannot inventory them as they are not returned from the product query.

**Comment by egym07** [comment]
Thanks for sharing. I see that there was a restriction. I was not aware that there was documentation. Unfortunately, I accept that it is a limitation. Thank you very much.

Please close this case.
