### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by orauch-a** [microsoft/coe-starter-kit#3887]
### What is your question?

Hello,

If we give access to the Starter Kit to admin sys users.

Is it possible to setting the CoE Starter Kit so that the admin sys users can only see the data that is on their environments ? Using Power Platform teams for example

Regards.

**Comment by Jenefer-Monroe** [comment]
We do not have a row level security solution for the kit, no.
It is likely possible using things like Business Units and such but you would need to do the work to assign it. And its not something we have mapped out. 
Sorry we cannot be of further assistance here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for coe starter kit team
