### ISSUE TITLE
[ALM Accelerator - BUG]: Missing dependencies for the october release

### ISSUE THREAD

**Issue by mdpc-nnit** [microsoft/coe-starter-kit#3888]
### Describe the issue

I am trying to update to the October release and am getting some missing dependencies on the CreatorKitCore.

![image](https://user-images.githubusercontent.com/47601989/194544609-3c724e2c-2dbb-4b70-8ec5-08acccdc7d14.png)

Is this intentional? I couldn't seem to find it in the upgrade instructions

### Expected Behavior

Importing the ALM Accelerator package should work in a fresh environment

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

October release

### Steps To Reproduce

In a new environment, import the October release package

**Comment by mdpc-nnit** [comment]
nevermind - it is stated in the release notes that this dependency was introduced

**Comment by MMRauscher06** [comment]
I also have this error message.
What exactly is the solution to this?

**Comment by MMRauscher06** [comment]
I have found the error. The Creator Kit was not installed in the environment and therefore the tables were not available. The Creator Kit was installed, then it also worked with the ALM Accelerator.

**Comment by mdpc-nnit** [comment]
yes exactly - in the october release, there was introduced a dependency on the Creator Kit. It even states it in the release notes, but I didn't see it.
