### ISSUE TITLE
[Question]: How fill Developer Compliance Center App env var after install core? 

### ISSUE THREAD

**Issue by tato1967** [microsoft/coe-starter-kit#389]
**Describe the bug**
After installing the core components of the CoE Kit the Developer Compliance Center Canvas App is missing and therefore the Development Compliance Center URL environment variable cannot be set

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.0.20210510.5 May 2021
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**
1. Install the Core components of the starter kit
2. Look for the Developer Compliance Center App

**Expected behavior**
For the app to be available and usable

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello that env var is left blank until you install the Gov components (aka Audit Components)

Here are the instructions from Gov on how and when to fill [update variables back in Core](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components#update-the-variables-and-flows-back-in-core)

I have added a note in the Core documentation to make this more clear which will ship with the next document update.

**Comment by JeneferM-MSFT** [comment]
thanks for using CoE
