### ISSUE TITLE
Changing Owner of Flow

### ISSUE THREAD

**Issue by highsmithjd** [microsoft/coe-starter-kit#3892]
### Describe the issue

I'm trying to change the owner of a Flow from a user account to a service account. Using the CoE "Set Flow Permissions" app, I don't get the option to change owners and see the follwoing message below.  We need to be able to change these from the CoE (recommended my Microsoft support).

Changing flow ownership is not possible in the product, so changing it here only changes it in the context of your CoE Toolkit. It is stored and used as a property of the CoE Flow table: DerivedOwner

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Set Flow Permissions

**Comment by Jenefer-Monroe** [comment]
If the flow part of a solution?

**Comment by Jenefer-Monroe** [comment]
And please share a screenshot of what you are seeing as there are several paths possible in the app, that will help me know what your situation is.

**Comment by highsmithjd** [comment]
![tempsnip](https://user-images.githubusercontent.com/49718142/194624549-00b4559c-9905-4ccf-8ff7-289d908141c2.png)

**Comment by Jenefer-Monroe** [comment]
You need to add the new user first, by clicking here
![image](https://user-images.githubusercontent.com/89584709/194625003-77f8b926-42d1-426a-a366-5f9f70c1aaac.png)

You cant assign owner role to groups.

**Comment by highsmithjd** [comment]
We tried to assign a user as Editor but couldn't assign them as Owner in the Flow settings

**Comment by Jenefer-Monroe** [comment]
Can you please share screenshots of what you did and where you got stuck?

**Comment by Jenefer-Monroe** [comment]
[microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] How to configure access to Power Platform Administration Planning app? (Issue #3968
