### ISSUE TITLE
[CoE Starter Kit - BUG] Unpublished Child Flow prevents Admin FLow Turn On

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#3895]
### Describe the issue

Installed the new CoE Core, and while verifying flow status, discovered CLEANUP - Admin | Sync Template v3 (Check Deleted) was not ON.
Tried to turn it on and got  Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id '37aaead3-1e31-ed11-9db3-002248226dcd' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

I republished all in CoE environment, with no change.

![image](https://user-images.githubusercontent.com/93291159/194619566-36143e39-9964-4664-aeb9-7ac7326d9a33.png)

### Expected Behavior

Flow turns on successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by Jenefer-Monroe** [comment]
It sounds like one of its helpers isn't turned on. Make sure all the helper flows titled with **_CLEANUP HELPER - Check Deleted_** are turned on.

**Comment by peteredc** [comment]
That was it.  The new AI delete check was off for some reason... thanks!

**Comment by Jenefer-Monroe** [comment]
Thanks for letting me know! Looks like we forgot to list it in the documentation so I'll fix that up too.

**Comment by peteredc** [comment]
No worries.  Plenty to think about with this product.

**Comment by peteredc** [comment]
I do have a suggestion though.  Perhaps an additional filter on the CoE flow screen of the Command and Setup Center.  Maybe add a new column that marks the flows as 'essential' that need to be running so it can be filtered by that.

Or a massive fat restart button that just does them all anyways... :)

**Comment by Jenefer-Monroe** [comment]
We are working on a setup/upgrade app that is specifically tailored to making that easier :)

**Comment by peteredc** [comment]
Great news! Do you have an ETA?

**Comment by Jenefer-Monroe** [comment]
I dont right now, but if you come to the https://aka.ms/coeofficehours we'll talk about it there

**Comment by peteredc** [comment]
Hey that's cool! Where do you find the schedule?

**Comment by Jenefer-Monroe** [comment]
We target the second Wednesday of each month at 7 AM (PST)
