### ISSUE TITLE
[CoE Starter Kit - BUG] Custom Connector for Audit logs needs redone after every CoE update

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#3896]
### Describe the issue

After an import of the lastest CoE core, the custom connector for audit logs needs to be redone from scratch.  Not sure if this is the expected behaviour, but the flow fails to run unless the connector is rebuilt.

![image](https://user-images.githubusercontent.com/93291159/194624014-1b69762b-f3b1-476b-b76b-34ff3ecf2fe7.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
Hello, yes unfortunately this is a known product limitation. We have attempted to make a write up of what we think is the easiest path out of the problem with each upgrade here: https://github.com/microsoft/coe-starter-kit/issues/1424

**Comment by peteredc** [comment]
Got it thanks!  Out of habit upgrade everything that I have installed, however seeing as the Audit Log solution doesn't seem to change much, I could probably just not do the upgrade if the versions match... a bit OTT to do it I guess.

**Comment by peteredc** [comment]
Maybe put a link to the github doc in the MS docs for that flow as well?  I always use that list post import.  At the very least seeing it on new install might be helpful too.

**Comment by Jenefer-Monroe** [comment]
[microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] How to configure access to Power Platform Administration Planning app? (Issue #3968
