### ISSUE TITLE
[Power Platform Hub] URL too long

### ISSUE THREAD

**Issue by trekkir** [microsoft/coe-starter-kit#3898]
### Describe your bug, question or feature ask.

I tried rolling out the template by using both the provided script and manually creating the Communitation site and applying the template to it (using Invoke-PnPSiteTemplate), but I get '_object id invalid_' and '_file not found_' errors.

Further investigation showed that when I use a site collection named _/sites/1_ (instead of the provided _/sites/powerplatformhub_), it does work, so it seems like some filenames within the template maybe are too long?

My tenant name is 11 characters long, so that's not really something unusual...

**Comment by Laskewitz** [comment]
Issue fixed in new version of the script. Confirmed with @trekkir, so closing the issue!
