### ISSUE TITLE
Pipelines: build-deploy-* pipelines show a 'waiting' status when waiting to deploy to production

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#39]
![image](https://user-images.githubusercontent.com/4499296/93393567-bcf52800-f840-11ea-8d88-b3a574394562.png)
![image](https://user-images.githubusercontent.com/4499296/93393576-c2527280-f840-11ea-98be-382b6b848c0c.png)

**Comment by rpothin** [comment]
Do you have some approvals or checks configured on the Production environment in Azure Pipelines?

**Comment by devkeydet** [comment]
Yes, that's the root cause.  This work item is really to think about how to improve the experience.

**Comment by devkeydet** [comment]
Complete in our internal repo. Won't mark as complete here until we are able to transfer what's in our internal repo here. Our internal repo uses some unannounced tools and soon to be released bug fixes in the service. We will need to wait to bring these enhancements into this repo.

**Comment by devkeydet** [comment]
Resolved in private preview repo.
