### ISSUE TITLE
[Power Platform Hub] Unable to install Platform Community Hub using script

### ISSUE THREAD

**Issue by DaMichiiiiii** [microsoft/coe-starter-kit#3904]
### Describe your bug, question or feature ask.

Dear community,

i just wanted to install a Power Platform Community Hub using the script Deploy-PowerPlatformHub.ps1 from your site, which works up to the point in the script where it tries to apply the template. It is correctly initialized but after running for some time i get the following error:

Invoke-PnPSiteTemplate : Methode nicht gefunden: "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> Enumerator.MoveNextAsync()".
In Zeile:1 Zeichen:1
+ Invoke-PnPSiteTemplate -Path "C:\Dev\Powershell\EnablePowerPlatformCo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Invoke-PnPSiteTemplate], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.InvokeSiteTemplate

**Comment by Laskewitz** [comment]
Hi @DaMichiiiiii - 

Could you please check the version of the installed module by running the following cmdlet?
`Get-Module -ListAvailable -Name PnP.PowerShell`

Thanks in advance!

**Comment by DaMichiiiiii** [comment]
Hi @Laskewitz,

thank you for your reply :)
This is my module info:

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.11.0     PnP.PowerShell                      {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassification, Copy-PnPFolder...}

**Comment by DaMichiiiiii** [comment]
Hello :) Do you have some new piece of information for me regarding that error?

**Comment by Laskewitz** [comment]
Not yet - Will take a look at it more tomorrow.

**Comment by petepuu** [comment]
Could this be same PS version issues as in this case https://github.com/microsoft/coe-starter-kit/issues/3868

**Comment by Laskewitz** [comment]
Agreed @petepuu! @DaMichiiiiii - could you try running the script with PowerShell ISE or PowerShell instead of VS Code?

**Comment by DaMichiiiiii** [comment]
Thank you @petepuu, @Laskewitz: Thanks a lot you guys :) That did the trick! Wouldn't have guessed that it is related to VSCodes Powershell Version
