### ISSUE TITLE
[ALM Accelerator - QUESTION] Set SpnToken for use by other tasks that need one faild

### ISSUE THREAD

**Issue by rpa-aa** [microsoft/coe-starter-kit#3905]
### What is your question?

Hello,
I have installed the ALM with COE CLI script. The installation worked finde.
I have created a dummy solution with a dummy app and try to stage the solution to the next environment.
While the export step (export_solution_to_git pipeline) I get an error at the step in the topic (Set SpnToken for use by other tasks that need one). I just get the error code 1. I append the CMD lines at the buttom.
Do anyone else have the same issue? What can cause this issue?
Thanks and regards,
Tobias

Starting: Set SpnToken for use by other tasks that need one
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.210.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\26d0bc52-a244-490c-bd11-87cc706b39ec.ps1'"
Invoke-RestMethod : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
At D:\a\1\PipelineUtils\PowerShell\dataverse-webapi-functions.ps1:11 char:17
+ … $OAuthReq = Invoke-RestMethod -Method Post -Uri "https://$aadhost/$te …
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: POST, Reque…-form-urlencoded
}:HttpRequestMessage) [Invoke-RestMethod], HttpRequestException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
##[error]PowerShell exited with code '1'.
Finishing: Set SpnToken for use by other tasks that need one

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20220831.2

**Comment by mikefactorial** [comment]
@rpa-aa can you verify a couple of things.
1. Make sure the AADHost variable is set appropriately in the Global Variable Group. e.g. 
![Image](https://user-images.githubusercontent.com/42348035/194923743-360138a8-2bb4-42e7-b082-8338344d477c.png)
2. Verify the service connection being used in your export pipeline. 
![Image](https://user-images.githubusercontent.com/42348035/194924119-f5d8ffd1-ab99-4629-a195-54e1de0643b6.png)


For more info on the Global Variable Group and Service Connections. See these docs.

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-pipeline-global-variables

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-service-connections-for-azure-devops-to-access-microsoft-power-platform

**Comment by rpa-aa** [comment]
@mikefactorial thank you for your response.
The global values are filled out. For AADHost I also have login.microsoftonline.com and the service connections are filled out too.
Any other ideas?

**Comment by rpa-aa** [comment]
I have deleted everything from the AML and set it up again. The first try was with the COE CLI and now I tried it with the manaul setup. Now it works. I guess the COE CLI does not set up everything right.
