### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Flows can't be turned on

### ISSUE THREAD

**Issue by ddomboy** [microsoft/coe-starter-kit#3909]
### Describe the issue

Hello together,

I was trying to implement the CoE starter Kit and when it comes to activating the Admin Sync Flows the following errors occur: "ConnectionAuthorizationFailed" "Connection can't be used to activate this flow" 

What went wrong here?

Thanks in advance

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Admin Sync Template v3

**Comment by Jenefer-Monroe** [comment]
I dont recognize that particular error but it sounds similar to the co-authoring error, meaning you might be using a different identity that the one you installed the kit with? 
If you installed the kit as user A, then all the connections in the flows will be theirs. If you later want to activate with user B you would need to assign all the connections to them. Please see [Co-authoring and Connections](https://learn.microsoft.com/power-platform/guidance/coe/limitations#co-authoring-and-connections)
Please let us know.

**Comment by ddomboy** [comment]
Yes that was the problem, thanks a lot!

**Comment by Jenefer-Monroe** [comment]
glad to help. I'll go ahead and close this out then but please let us know if you need more help.
