### ISSUE TITLE
[BUG]: Sync flows error observations with the latest CoE Starter Kit

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#391]
Hello Team,

I require your help on "CoE Starter Kit 2.6" Sync flows as I have observed followings today after deployment of the core components:

**1. - Sync flows are keep throwing error message even though required connectors are established** -  For example, Sync (PVA) flow was unable to turn on as it has thrown following message:

 Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmConnectionReferenceMissingConnection","message":"Connection Id missing for connection reference logical name 'admin_CoECorePowerPlatformforAdmins'."}}".

This means, I have to save the flow on top of managed layer which will create unmanaged layer - will that be fine? Can you please clarify?

**2. - Sync Flow (Flow Action details) flow is not picking up already available "Power Automate Management" connection** - I have"Power Automate Management" connection already available in the environment using "First Party" option, however the flow is unable to pick up that connection as indicated in the following screen:

![image](https://user-images.githubusercontent.com/13658386/118816445-2c179600-b880-11eb-8bc5-df5f6a014173.png)

Further, when I try to make connection from here, it throws connection error as it might picking up deprecated connection, however I am  unsure - can you help?

Thank you for your time in advance!

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Hi there. I'm not sure what version you are using. Can you please go to solutions and see what version of Core you have? We have not yet reached 2.6 in our numbering so I am confused. 
![image](https://user-images.githubusercontent.com/62659043/118821497-890d4f00-b874-11eb-8f76-c3441bdfe351.png)

We did have, in the past, a version of the toolkit which shipped with broken connectors so I am not sure if you have hit that case. 

Please get the latest version and install after removing unmanaged layers as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by dips23** [comment]
Hi Jenefer,

My bad, that's correct, for me it's version 2.1.6 that I have downloaded on 12th May from the MS documentation. If this is not the version where the bug is fixed, could you please share the latest CoE kit link?

Thank you!

**Comment by JeneferM-MSFT** [comment]
That is the latest version, and most people have succeeded in install, so I'm not sure what is happening for you.

Did you validate that you removed unmanaged layers before upgrading as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)? 

You can go ahead and edit > save with the new connections. This will unblock you but create an unmanaged layer that will need removed before you upgrade again in the future (as described in the link above). 

Regarding the Power Automate Management connector. That is odd and seems like a product bug. Perhaps if you go to connectors and manually create a new one (or see if your old one is broken and fix), then come back and edit&save. Again, this will create an unmanaged layer that later needs removed.

**Comment by dips23** [comment]
Hey Jenefer,

Thanks to confirm the version!

Yes, I have made sure that there is no unamanaged layer as specified in the
suggested link. Moreover the environment was a copy of Production
environment ( With COE version 1.70)  where only managed solutions were
deployed while all connections were made from the scratch.

I was wondering if there is any automated ways where I can see list of
components with unmanaged layers in the solution.

Regarding PAM connector, I have already created one from the scratch,
however the flow is not picking up from the existing connection rather it
asks to create new one which throws an error as mentioned in the question,
therefore I am unable to save the flow.

I will keep you posted further observations!

Best,
Dipti

**Comment by JeneferM-MSFT** [comment]
That is odd! As far as I know there isn't a programmatic way to discover these unmanaged layers, but I am double checking. 

One thought is to check to make sure you are logged in with the correct credentials. I know some people use multiple accounts and perhaps you are logged in as the wrong one? 

What is the error you get when you try to + add the connector on that page?

**Comment by dips23** [comment]
Sure, Thank you Jenefer!

I am logged in with the same account who deployed/configured the solution.
Also the  error that I see is as enclosed. It's "FlowRPCustomConnector need
permission..." Error when I click on "+" sign, that I assume happening
probably because flow is asking for the connector which is configured with
"third party" that is deprecated? Not sure though!

Best,
Dipti

**Comment by JeneferM-MSFT** [comment]
Create a flow outside of the toolkit and use this connector. 
If that works, create a flow inside of a solution and use the connector.

**Comment by DiptiC-InsightRun** [comment]
Yes, I have tried earlier copying/saving the same flow where the PAM
connector was working, in this case, I will proceed ahead by saving-adding
a new flow in the managed solution.

Would you please share if this is an issue with
environment/connector/solution/flow?

Thank you for helping us!

Best,
Dipti

**Comment by JeneferM-MSFT** [comment]
I don't know what the issue. My guess is that you have hit a product bug but I am unsure. 

Are you saying you are unblocked now?

**Comment by DiptiC-InsightRun** [comment]
Hi Jenefer,

As of now, I am able to activate the flow by saving it manually and turn it on. Therefore, I am planning to save all the flows in the separate solution which are having the similar issues.

Please let me know if this is not an appropriate approach, otherwise we are good to close this ticket :)

Thank you for your time and help!

Best,
Dipti

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE

**Comment by DiptiC-InsightRun** [comment]
Hi Jenefer,

With further research on this issue, We have noticed that the CoE solutions were deployed via "Classic Portal" , therefore few required connection references were not established, that we have done manually now from the default solution as suggested by Manuela here - https://github.com/microsoft/coe-starter-kit/issues/420

By doing so, these errors are resolved and we were able to activate the flows successfully without saving them separately.

I hope this would be helpful for others - Thank you CoE Team for your continuous support!

Best Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Great to hear!
