### ISSUE TITLE
[ALM Accelerator - BUG]: Environment creation failed

### ISSUE THREAD

**Issue by tsharmaBGSW** [microsoft/coe-starter-kit#3911]
### Describe the issue

I'm trying to create a new project from ALM Accelerator. when admin approves the request for project creation, the system tries to create a new dev ENV. at that time, I'm getting "Environment Creation Failed" error. However, I don't want to create a new ENV but want to use my existing ENV as dev ENV.

### Expected Behavior

It supposed to use the existing environment rather than creating a new one.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

3.20123.24

**Comment by mikefactorial** [comment]
@tsharmaBGSW this appears to be related to the ALM Accelerator for Makers. The way that app works is to provision a new dev environment when a project is approved. We're not actively making changes to this solution as it is only for reference. You would need to modify the flows to use an existing development environment. 

However, the ALM Accelerator for Power Platform that we are actively developing does support the scenario in question. Would recommend moving to the ALM Accelerator for Power Platform instead. Note below are from the docs for the ALM Accelerator for Makers. https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almaccelerator


NOTE: The ALM Accelerator for Makers components are for reference only. For more robust deployment configurations, including components that need to be configured as part of—or after—solution deployment, we recommend that you use the ALM accelerator for Microsoft Power Platform. The GitHub integration in the ALM Accelerator for Makers will eventually be replaced by functionality in the ALM Accelerator for Power Platform app. More information: [Set up the ALM accelerator for Microsoft Power Platform components](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-cli) and [Use the ALM accelerator for Power Platform app](https://learn.microsoft.com/en-us/power-platform/guidance/coe/almacceleratorpowerplatform-components)
