### ISSUE TITLE
[Power Platform Hub] SPO Vanity URLs

### ISSUE THREAD

**Issue by mabaugh83** [microsoft/coe-starter-kit#3917]
### Describe your bug, question or feature ask.

FYI the changes in the doc don't work with the vanity urls for spo.

I modified the scripts as follows to hard code urls rather than variables:
deploy-powerplatformhub.ps1
$adminTenantName = 'o365spo-admin.contoso.com'
$adminURL = 'https://o365spo-admin.contoso.com'
$newSiteURL = 'https://portal.contoso.com/sites/m365powerplatformhub' 
 
and
set-powerplatformhubasdlperrorsettings.ps1
$newSiteURL = 'https://portal.kiewit.com/sites/m365powerplatformhub'

**Comment by Laskewitz** [comment]
Hi @mabaugh83 - 

Thanks, we'll add this to the docs.

Thanks,
Daniel
