### ISSUE TITLE
Canvas App cannot be deleted using Clean Up and Delete Flows

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#3919]
@Jenefer-Monroe the app is neither. Is just a regular canvas app with no dependencies. 
![image](https://user-images.githubusercontent.com/95443860/195190857-7ceb01bc-ad46-41a1-845a-e45c43206f94.png)

_Originally posted by @nasilvae in https://github.com/microsoft/coe-starter-kit/issues/3891#issuecomment-1275122374_

**Comment by Jenefer-Monroe** [comment]
Hello, per your note in that bug. The product itself is saying that it has dependencies. So if it does not really have any, then that is a product issue with incorrectly identifying dependencies.

**Comment by Jenefer-Monroe** [comment]
From your screenshot
![image](https://user-images.githubusercontent.com/89584709/195195605-f12c0aa2-42ad-41a6-a8ac-a3a01f6debd8.png)

**Comment by Jenefer-Monroe** [comment]
We will not delete objects programmatically that have dependencies, the clean up there will need to be manual.

**Comment by nasilvae** [comment]
gotcha now I caught it. Thank you

**Comment by Jenefer-Monroe** [comment]
You bet. Working on making this error propagate for Nov release.
