### ISSUE TITLE
[BUG]: CLEANUP - Admin | Sync Template v3 (Check Deleted) Flow Failing

### ISSUE THREAD

**Issue by StephenCouch** [microsoft/coe-starter-kit#392]
**Describe the bug**
CLEANUP - Admin | Sync Template v3 (Check Deleted) Flow is failing on every run. The action that is failing is 'List PVA Component Flows with Missing Flow'. This is happening 100% of the time.

The error being reported is:
A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Center of Excellence - Core Components
 - Version - 2.0.10
 - App or Flow - CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Screenshots**
![2021-05-19_8-59-45](https://user-images.githubusercontent.com/67427138/118817054-d099d800-b880-11eb-9816-841d51718002.png)
![2021-05-19_8-54-54](https://user-images.githubusercontent.com/67427138/118817081-d68fb900-b880-11eb-86a6-cdab0a07c9d9.png)

**Additional context**
Output from the last fail.

`{
   "statusCode":400,
   "headers":{
      "x-ms-service-request-id":"62dbe9cc-b657-47e9-ac0c-2eecfc9f2d1a,a0e00bef-a188-41b2-9296-89e7c578d22c",
      "Cache-Control":"no-cache",
      "Set-Cookie":"ARRAffinity=61c1c112e40dda965acca85cc55f38908146995d7afaea964e4e66a89dd3139b; domain=org97c1460d.crm.dynamics.com; path=/; secure; HttpOnly,ReqClientId=ea48bf58-dbdb-437f-9a52-94d9dfa9f0e9; expires=Mon, 18-May-2071 17:52:19 GMT; path=/; secure; HttpOnly; samesite=none,ARRAffinity=61c1c112e40dda965acca85cc55f38908146995d7afaea964e4e66a89dd3139b; domain=org97c1460d.crm.dynamics.com; path=/; secure; HttpOnly",
      "Strict-Transport-Security":"max-age=31536000; includeSubDomains",
      "REQ_ID":"a0e00bef-a188-41b2-9296-89e7c578d22c,a0e00bef-a188-41b2-9296-89e7c578d22c",
      "AuthActivityId":"479a0653-1574-4acc-875a-28f4ee3e1f39",
      "x-ms-ratelimit-burst-remaining-xrm-requests":"5724",
      "x-ms-ratelimit-time-remaining-xrm-requests":"1,189.94",
      "OData-Version":"4.0",
      "X-Source":"5713796325319212623015288231250121121566712135118929248231213107561942821892174187,2272911425115111822486159542257721937372352041098490155126198217233121160713558",
      "Public":"OPTIONS,GET,HEAD,POST",
      "Timing-Allow-Origin":"*",
      "Date":"Tue, 18 May 2021 17:52:18 GMT",
      "Content-Length":"167",
      "Allow":"OPTIONS,GET,HEAD,POST",
      "Content-Type":"application/json; odata.metadata=full",
      "Expires":"-1"
   },
   "body":{
      "error":{
         "code":"0x0",
         "message":"A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'."
      }
   }
}`

**Comment by JeneferM-MSFT** [comment]
This was fixed by https://github.com/microsoft/powerapps-tools/issues/862 and the call now looks like this with the filter by null instead of empty string
![image](https://user-images.githubusercontent.com/62659043/118820907-f1a7fc00-b873-11eb-9eff-7b7a9168bf4d.png)

Please be sure to remove unmanaged layers when you upgrade as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you won't see our changes. 

Thanks for using CoE
