### ISSUE TITLE
[CoE Starter Kit - BUG] Environment variable Admin Email not passed

### ISSUE THREAD

**Issue by dchrist27** [microsoft/coe-starter-kit#3920]
### Describe the issue

I made a customization to the Microsoft Teams Admin | Weekly Cleanup of Microsoft Teams Environments not within the managed solution but after I did a 'save as' of the flow.   The flow ran but is using the default value of Admin Email.

![image](https://user-images.githubusercontent.com/52799471/195196176-dc9641c2-d35b-4d71-bac3-c4801bc978bf.png)

I read in an older case #1176 where the user recommended to run the flow in the default solution but I do not know how to copy/move my saved flow into the default solution.  

This is a brand new install of CoE from the 9/2022 release.  If I look in the default solution under the admin email env variable I see my email address as the current value.

Thanks
Dave

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.21

### What app or flow are you having the issue with?

Microsoft Teams Admin | Weekly Cleanup of Microsoft Teams Environments

**Comment by Jenefer-Monroe** [comment]
Here is our documentation for how to [customize the toolkit](https://learn.microsoft.com/power-platform/guidance/coe/modify-components)
Please take a look at the approach outlined there. 
Thank you

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
