### ISSUE TITLE
[CoE Starter Kit - QUESTION] error in the flow "Admin | Sync Template v3 (PVA)"

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#3921]
### What is your question?

I am getting an error in the flow "Admin | Sync Template v3 (PVA)".

It appears that the ID cannot be found and the error is occurring.
What can I do to stop this error?

Error Description:
admin_pva With Id = (ID) Does Not Exist

![image](https://user-images.githubusercontent.com/91306350/195256131-d5579106-4fc0-426e-85b0-9fca895eb3df.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

**Comment by Jenefer-Monroe** [comment]
Hello. that is a caught failure. You will see the flow continue execution after that. We do this to see if the PVA is already inventoried, in this case it is not, it is new to the CoE inventory. 

You will need to go further down in the flow and find the point of failure that is not caught.

**Comment by egym07** [comment]
I see. Thank you very much.
Further down the flow, I found this error.
I am still not sure what is causing the error.

![image](https://user-images.githubusercontent.com/91306350/195469282-99893c81-24dd-44df-8302-3cf5add3da85.png)

**Comment by Jenefer-Monroe** [comment]
Strange, we don't use the substring equation anywhere in here. 
Can you plesae see, what is returned from **_Maker Check - New_** action above for userIsOrphaned?

**Comment by egym07** [comment]
The "userisorphan" has a value of "false".
Is this the correct place to check?
![image](https://user-images.githubusercontent.com/91306350/196306356-779179b6-93dd-4a59-8935-bf63a69bc1e6.png)

**Comment by Jenefer-Monroe** [comment]
Yes thats correct, and it has gone down the correct path here. 
Can you please validate if you have [unmanaged layers](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) on the flow? And if so, please remove them.

**Comment by egym07** [comment]
I tried deleting the unmanaged layer on the flow but still get the same error :(

**Comment by Jenefer-Monroe** [comment]
Can you please open the flow in edit mode and show what you see here? 
![image](https://user-images.githubusercontent.com/89584709/196750388-f68a4e49-0acc-4102-aafc-509a5c19a00f.png)

And then for the ones that are equations, please copy the question for me here as follows:

![image](https://user-images.githubusercontent.com/89584709/196750518-63c53930-6553-4ba9-bd61-5003434697cb.png)
`@if(equals(substring(body('Parse_Bot_JSON')?['_componentstate_label'], 0, 7), 'Deleted'), true, false)`

![image](https://user-images.githubusercontent.com/89584709/196750542-d3deec2d-1d7f-416d-8ae8-06658b11b6e4.png)
`@{if(lessOrEquals(variables('varNumberConvos'), 0), body('Parse_Bot_JSON')?['createdon'], variables('varLastLaunched'))}`

**Comment by egym07** [comment]
Hmmm, looks like a match...
What do you think?

![image](https://user-images.githubusercontent.com/91306350/196839144-70820a9c-37f7-47b3-905c-da1ee2186ddc.png)
![image](https://user-images.githubusercontent.com/91306350/196838454-c6daef8f-f2fb-4e1c-9229-3ee93ce87b6d.png)
![image](https://user-images.githubusercontent.com/91306350/196838484-d7c930ce-63b9-462d-a48b-82b1a78d1f7e.png)

if(equals(substring(body('Parse_Bot_JSON')?['_componentstate_label'], 0, 7), 'Deleted'), true, false)

if(lessOrEquals(variables('varNumberConvos'), 0), body('Parse_Bot_JSON')?['createdon'], variables('varLastLaunched'))

**Comment by Jenefer-Monroe** [comment]
I'm really not sure at all! Couple more questions
- Does this repro for all PVA's? Just 1 or 2? 
- Does it repro consistently? If you re-submit the flow failure? 
- Do you have the [English Language Pack](https://learn.microsoft.com/power-platform/guidance/coe/limitations#supported-languages) installed?

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
