### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Inactivity notifications v2 (Clean Up and Delete) Flow fails

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#3923]
### Describe the issue

We are seeing the following flow  Inactivity notifications v2 (Clean Up and Delete) errors in our Power Platform Environment:

It would appear this error occured and was perhaps due to the fact that the App Owner/ Teams Environment Owner had left the organisation?

![image](https://user-images.githubusercontent.com/48433526/195268866-4be56d90-09f1-4b9a-a158-bcdf86d2b0f8.png)

![image](https://user-images.githubusercontent.com/48433526/195268533-5f99a400-4238-4825-b8da-9c04e7a6d460.png)

![image](https://user-images.githubusercontent.com/48433526/195269821-6bf255d0-b06d-46ba-83a7-5ffdba4e4a64.png)

![image](https://user-images.githubusercontent.com/48433526/195269548-bccb207d-a04f-41d1-a824-6dbe9d7d110b.png)

Output Error:
The user with SystemUserId=3xxx17 in OrganizationContext=3exxxxad is disabled\"

If I manually go to admin.powerplatform.com and delete the Teams Environment then resubmit the flows the error disappears.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.23

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Clean Up and Delete)

### Anything else?

There errors are not showing up in the CoE Command center, which perhaps they should?

**Comment by Jenefer-Monroe** [comment]
Thanks for investigating. The fix here will just be in the feature to propagate these failure messages to the interested party so they know they have to delete manually. We cannot programmatically delete some objects for a variety of reasons (ex part of managed solution / has dependencies). It looks like you hit one of these cases.  https://github.com/microsoft/coe-starter-kit/issues/3915

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this issue then, please track the fix with https://github.com/microsoft/coe-starter-kit/issues/3915
