### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can not remove unmanaged layers

### ISSUE THREAD

**Issue by MantasSal** [microsoft/coe-starter-kit#3924]
### What is your question?

Hello,

can not find where to remove unmanaged layers. According to update instructions it should be done from Admin - Command center app.
But I do not find it under

![image](https://user-images.githubusercontent.com/114066875/195310992-f059c320-b598-4297-9c61-54ded7739c98.png)

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by Jenefer-Monroe** [comment]
This is the UX you eventually use to delete the unmanaged layers, the app will just show you which flows have them, and give you a link to this UX

So you go to the [Admin - Command Center](https://learn.microsoft.com/power-platform/guidance/coe/core-components#admin---command-center), which is part of the Core solution. Go to CoE Flows, and look for the icon highlighted below. Clicking that icon brings you to the UX to remove the unmanaged layer. 
![image](https://user-images.githubusercontent.com/89584709/195397751-3508111b-67e4-4b94-b87f-30264fe81a6c.png)
![image](https://user-images.githubusercontent.com/89584709/195397866-e690e7bc-0a90-4f9c-9a7f-be9d32d9f630.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
