### ISSUE TITLE
[CoE Starter Kit - BUG] App Detail Canvas App error in Power BI Report

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#3940]
### Describe the issue

When viewing the details of an app from the Power BI Report, you get the below error.
![image](https://user-images.githubusercontent.com/93291159/195441636-198b1e43-32d9-4f7f-9757-46d85ff53e81.png)

### Expected Behavior

Details of app load.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Power BI CoE Dashboard Report

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. Found and fixed for November via https://github.com/microsoft/coe-starter-kit/issues/3875
You can peek in there if you'd like to see the fix to apply locally. 
I'll go ahead and close as a dupe.

**Comment by peteredc** [comment]
Ok Thanks!

**Comment by peteredc** [comment]
I'm getting an error for the flow detail app as well.. not sure if you've got this one already.

![Screenshot 2022-10-18 100957](https://user-images.githubusercontent.com/93291159/196455570-8acb7a88-e1ed-477b-9b83-dccc915297d3.png)
