### ISSUE TITLE
[CoE Starter Kit - QUESTION]  Usage of "Power Platform Maker Group ID"

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#3943]
### What is your question?

I would like to know about the use of GroupAddress.
Using the flow "Admin | Add Maker Group", the app makers was added to GroupAddress from the environment variable "Power Platform Maker Group ID".
Am I correct in understanding that this group address is for managing app makers?
Also, is there any flow of notification using this group address?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Admin | Add Maker Group

**Comment by manuelap-msft** [comment]
Hello,

makers get added to this group as part of the **Welcome email** flow where a welcome email (that you can customize using the Admin - Command Center) is sent out to new makers. Once added to the group, you can use this group to email makers yourself or to share apps that are relevant to makers (e.g. the Developer Compliance Center) with them.

**Comment by egym07** [comment]
Thank you very much.
By the way, if I delete a user added to a GroupAddress, will he/she be re-registered?
Also, if I remove them from the group, will it affect them or CoEStarterKit in any way?

**Comment by manuelap-msft** [comment]
They will be re-added if they create a new app/flow again, yes. There's no impact on the CoE kit itself, but at the moment we don't have a way to exclude users being added to this process. Is that something you'd require?

**Comment by egym07** [comment]
Thank you.
I thought I was using this group address to manage the makers. Is this wrong?
Can notification of all makers using this address happen unless the CoEStarterKit administrator takes some action?

Yes...Several makers have requested to be removed from the group address.

**Comment by manuelap-msft** [comment]
What do you mean by manage makers? And why have makers asked to be removed?

Here's how it works:
The CoE kit discovers if there's a new maker > the maker gets one welcome email and gets added to the group. No further communication is sent to the maker and we don't have any flows that use the group to send emails to all makers. If the CoE sends emails to makers (such as for compliance requests, inactivity notifications) they get send to the individual maker and not the group. 

The purpose of the group is that if you as the Admin need to send comms to all makers or need to share something (an app, a SharePoint site etc) with all makers you can use it.

**Comment by justdevcode** [comment]
May I add to this question please. I'm upgrading from an older version (Dec 2021). 
Just want to confirm that any existing Makers are not added to the M365 group using the "Admin | Add Maker to Group" flow?
Just want to make sure we don't send a flood of emails to existing Makers :-)
Can we turn off the "Admin | Add Maker to Group" flow after an upgrade if we don't want to add users to a M365 group?

**Comment by egym07** [comment]
@manuelap-msft 
We are currently confirming why Makers is asking for it to be removed.
I wanted to know what I could do with this group address, so thank you for telling me how it works and what it is used for.
I was using a translator to tell you this, so it may have been poorly written. My apologies. Thank you very much.

**Comment by manuelap-msft** [comment]
Hello,

thank you for sharing that feedback! That's valuable for us - whilst the CoE kit does not email makers using the group address, Makers may receive an automated notification from Microsoft 365 to let them know they've been added to a group. We can add a note about the group and its purpose to our Welcome Email text so makers are aware of the group. 

I did some investigation in our logic and I was actually wrong earlier - if you remove a maker from the group, they will **not** get added again the next time they create an app/flow! So you can safely remove them from the group and they won't be added again. 

There are various processes that communicate with makers from the CoE kit, but they are all off by default and you (the admin) has to turn them on - such as the compliance process, inactivity notification process etc.
