### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to embed Admin - Access this App inside Power BI dashboard

### ISSUE THREAD

**Issue by jondoesflow** [microsoft/coe-starter-kit#3944]
### Describe the issue

Hi,

We have installed the various components of the CoE toolkit.  We are trying to configure the Power BI dashboard, with the embedded version of the Admin - Access this Flow canvas app. But when we do the embedded canvas app throws an error:

PowerAppsforAdmins.GetAdminAppRoleAssignment failed: { "error": { "code": "BusinessAppPlatformRequestFailed", "message": "The request failed with client error: 'The environment '' could not be found in the tenant '351368d1-9b5a-4c8b-ac76-f39b4c7dd76c'.'. The correlation Id is '6fabf3cd-8439-4199-8a6e-8ceae457932f'.", "details": [ { "code": "MultipleErrorsOccurred", "message": "Multiple errors occurred. Please see details.", "details": [ { "code": "EnvironmentNotFound", "message": "The environment '' could not be found in the tenant '351368d1-9b5a-4c8b-ac76-f39b4c7dd76c'." } ] }, { "code": "FullNonLocalizedError", "message": "{\"error\":{\"code\":\"EnvironmentNotFound\",\"message\":\"The environment '' could not be found in the tenant '351368d1-9b5a-4c8b-ac76-f39b4c7dd76c'.\"}}" } ] } }

We understand that it is not a standalone application, so not sure why it gives this error.

### Expected Behavior

The canvas app should embed without an error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin - Access this App

### Steps To Reproduce

Following the steps here - https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard to embed the canvas app, and then we see the error in the embedded canvas app.

**Comment by jondoesflow** [comment]
We see this error:

![image](https://user-images.githubusercontent.com/60231096/195578078-1acdf375-dda8-4bb8-85e5-2dd24d397923.png)

Then when we try and open this link :
![image](https://user-images.githubusercontent.com/60231096/195578185-d14e884d-1d16-49e6-9a81-14e9bde5f944.png)


We get this:

![image](https://user-images.githubusercontent.com/60231096/195578565-bed9b3db-66ba-4549-a799-845f05b0bd53.png)

**Comment by Jenefer-Monroe** [comment]
It appears you did not do the steps to remove the old app and re-add as your own app from the [(Optional) Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard) instructions.
![image](https://user-images.githubusercontent.com/89584709/195597622-21e4613c-22df-46de-b64e-ef0a68fc9312.png)

Please let me know.

**Comment by jondoesflow** [comment]
Hi, yes we did remove the app first, and then recreated it, the error came after that, this happened after adding the app back in

**Comment by Jenefer-Monroe** [comment]
Can you please share the screenshot of you selecting the app? Did you first select your CoE environment?

**Comment by jondoesflow** [comment]
Hi,

Sure thing.  Please see screenshot attached:

![image](https://user-images.githubusercontent.com/60231096/195609690-a9c60031-7adb-476c-a721-5ee1b3516584.png)


![image](https://user-images.githubusercontent.com/60231096/195609726-918234d5-b695-477c-b9ca-0e84bae59014.png)

**Comment by Jenefer-Monroe** [comment]
oh ok yes. I believe that is the error from our sample data. I thought we told you to ignore this in the setup steps but we did not, will fix that for Nov. 
Can you please try to use the app? It will not work by itself, by browsing to hte page. You need to drill through to it from the apps page. Note that there is a separate bug (https://github.com/microsoft/coe-starter-kit/issues/3875) that this does not work for objects in Default envt in Oct release, so select an app from a different envt

**Comment by jondoesflow** [comment]
Thanks for this. Understood.
