### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | sync Template V3 (Updates)

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#3945]
### Describe the issue

![coeerror](https://user-images.githubusercontent.com/82215551/195574197-d9879a46-dd73-4056-b7f0-8efe1dbea62a.png)

Hi I am receiving this error when turning on Admin | sync Template V3 (Updates), is there another flow that needs to be run first?

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin | sync Template V3 (Updates)

**Comment by Jenefer-Monroe** [comment]
Hello, this indicates that one of the child flows this flow calls have not been turned on. 
Please be sure to turn on all the [inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) in the order described in the setup instructions. 
In particular, these flows need to be turned on before **_Admin | sync Template V3 (Updates)_** can be turned on
- Admin | Sync Template v3 CoE Solution Metadata
- Admin | Sync Template v3 Configure Emails
- Admin | Sync Template v3 (Connectors)

**Comment by Alyson95170** [comment]
Thanks Jennier, currently we have Admin | Sync Template v3 Configure emails off in our tenant, as we are not wanting emails to be sent to users until we are fully ready with the CoE

**Comment by Jenefer-Monroe** [comment]
Configure email does not send any emails, it just puts them in the tool for customizations. You will not be able to turn the kit on without turning this flow on. And generally speaking, you need to turn on all the [inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) or you will not be able to assume you have correct inventory. There are many assumptions made in the flows that the other ones are running.

If you want to have your CoE Run in "debug" mode, meaning that all emails will be sent to admins, then you can use the ProductionEnvironment env var, and set it to no. 

Or if you are just [turning on inventory](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components), there are no mails sent to the makers from any of those flows.

**Comment by Jenefer-Monroe** [comment]
You are welcome. I'll go ahead and close this out then, please let us know if you have further issues!
