### ISSUE TITLE
[ALM Accelerator - BUG]: AzureDevOpsExtensionsDetails.json' was not included into executable at compilation stage

### ISSUE THREAD

**Issue by trepaxrm** [microsoft/coe-starter-kit#3949]
### Describe the issue

Trying to install Alm accelerator for two days now. i'm installing from CoeStarterkit 3.53 with the coe-cli.exe provided in the zip. to hack my way into the install process 1 download the source code and place it is c:\snapshot base on previous error received. now i have this one
error: File 'C:\**\coe-cli\config\AzureDevOpsExtensionsDetails.json' was not included into executable at compilation stage. Please recompile adding it as asset or script. {"code":"ENOENT","errno":-4058,"path":"C:\\snapshot\\coe-cli\\config\\AzureDevOpsExtensionsDetails.json","pkg":true}

error: Error: File 'C:\**\coe-cli\config\AzureDevOpsExtensionsDetails.json' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1049:29)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1097:18)
    at deflateSync (pkg/prelude/bootstrap.js:717:24)
    at uncompressExternally (pkg/prelude/bootstrap.js:732:25)
    at uncompressExternallyPath (pkg/prelude/bootstrap.js:745:12)
    at DevOpsCommand.readFile (pkg/prelude/bootstrap.js:1709:28)
    at DevOpsCommand.install (C:\snapshot\coe-cli\built\src\commands\devops.js)
    at ALMCommand.installDevOpsComponents (C:\snapshot\coe-cli\built\src\commands\alm.js)
    at ALMCommand.install (C:\snapshot\coe-cli\built\src\commands\alm.js)

i have the files AzureDevOpsExtensionsDetails.json in the folder: C:\snapshot\coe-cli\config

i have trouble finding a install procedure that is in par with the release package 3.53 for a first install ? any help

### Expected Behavior

No Error and install goes thrue

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

3.53

### Steps To Reproduce

install from Fresh machine for a new tennat using release package 3.53, 
Alm accelerator deploymenet unsing the coe-cli

**Comment by trepaxrm** [comment]
Work arround this issue by compiling a new coe-cli from source Code. avoiding using the one already in the release package

**Comment by mikefactorial** [comment]
@trepaxrm thanks for bringing this to our attention. Will look into a fix for the packages cli executable. BTW we've had some delay in the latest docs being published, but we've added another option for setting up projects in Azure DevOps using the Administration app https://aka.ms/aa4pp/setup/project.

**Comment by SAEED2ALAHMARI** [comment]
Error: Error: The file 'C:**\coe-cli\config\AzureDevOpsExtensionsDetails.json' was not included in the executable file in the compilation phase. Please recompile and add it as original or script.
