### ISSUE TITLE
[ALM Accelerator - DOCUMENTATION]: Documentation for demo tenant setup not compatible with current PPAC Environment options

### ISSUE THREAD

**Issue by grburner** [microsoft/coe-starter-kit#3950]
### Describe the issue

Attempting to set up a demo tenant with the Accelerator using this article:

https://learn.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/before-you-start

This article provides this table:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/37910376/195599037-6729dbef-4e30-47dd-a564-916b9f9d6c0b.png">

and this table:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/37910376/195599093-87bdffcf-0d2d-4866-877e-e0e2b346d925.png">

to describe the necessary environment configuration. The two issues that I am running into are:

1) When using demos.microsoft.com to deploy a demo tenant, you can only create 3 trial subscription environments. In the first screenshot the ALM Environment indicates that in addition to the Test, Prod, and Validation environments we would need another dataverse enabled environment, raising the total required environments to 4.

In the second screenshot I am not seeing the ALM Environment in the sample list from the first screenshot.

2) The second screenshot indicates we should be able to create a developer environment. The current PPAC only lets you create these:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/37910376/195601664-63ab3587-9ad8-4f9d-95e3-8a222909018d.png">

### Expected Behavior

Updated documentation reflecting the current PPAC limits and user experience.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Current Github Release

### Steps To Reproduce

1. Follow the steps in the article linked above
2. When configuring the environments there will be inconsistencies with the documentation

### Anything else?

I did still create the quickstart file with this configuration:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/37910376/195604631-a579251b-25ec-42a2-92b3-8c4c46f679ae.png">

And ran the COE CLI install.

The COE CLI install process seemed to run successfully until the "Importing Managed Solution" step, where I received at 500 error. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/37910376/195605257-0306231a-4f5f-4212-86a2-b20a55f6d184.png">

...

<img width="503" alt="image" src="https://user-images.githubusercontent.com/37910376/195605353-103134ee-1aeb-473d-b924-17b6753c59ef.png">

No solution was installed.

**Comment by mikefactorial** [comment]
@grburner you may want to try installing the solutions manually if you are getting an error installing the solutions with cli. Not quite sure what the 500 error here would be. 

1. Creator Kit - https://github.com/microsoft/powercat-creator-kit/releases/download/CreatorKit-September2022/CreatorKitCore_1.0.20221004.2_managed.zip
2. ALM Accelerator - https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-October2022/CenterofExcellenceALMAccelerator_1.0.20221004.2_managed.zip

If the import of the managed solutions is successful you can run the cli install again and it will skip that step and proceed with the remaining steps. However, you will need to update the security on the custom connector after install per https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#configure-the-devops-custom-connector.

**Comment by grburner** [comment]
Thanks @mikefactorial. As for the original question about not being able to create enough environments in a demo tenant - is there an updated best practice for allocating the 3 available demo environments? Or am I misunderstanding documentation about how those environments should be set up?
