### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Apps) Flow Fails

### ISSUE THREAD

**Issue by clusterb0mb** [microsoft/coe-starter-kit#3958]
### Describe the issue

We have the following flow Admin | Sync Template v3 (Apps) Flow Errors in our CoE Power Platform Environment:

Error Action 'Append_to_SelectDLPFields' failed

Unable to process template language expressions in action 'Append_to_SelectDLPFields' inputs at line '0' and column '0': 'The template language function 'split' expects its first parameter to be of type string. The provided value is of type 'Null'. Please see https://aka.ms/logicexpressions#split for usage details.'.

![image](https://user-images.githubusercontent.com/63702199/195826547-7714169d-e58b-4c83-858d-809267002772.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

**Comment by Jenefer-Monroe** [comment]
Can you please go to the output of the **_Filter to Non Compliant Apps_** action above this apply-to-each loop
![image](https://user-images.githubusercontent.com/89584709/196198602-aebaa275-ee9c-4f14-8d45-76d7ca9185c8.png)

And search (control-f) for the following string: **_lastEvaluationDate_**
You should see that in there twice, can you please let me know if you see it in there twice, and if so, share here what the value is? 
![image](https://user-images.githubusercontent.com/89584709/196199013-7161bff4-451b-4f58-a874-1cf118472869.png)

**Comment by clusterb0mb** [comment]
Sorry i cant find **_lastEvaluationDate_**

![image](https://user-images.githubusercontent.com/63702199/196698013-a5ab5db6-e12b-40d4-bf94-e384fc685056.png)

![image](https://user-images.githubusercontent.com/63702199/196698451-9520e57d-0246-44b9-a524-1fbd19631580.png)

**Comment by clusterb0mb** [comment]
I can only find it on successful runs:

![image](https://user-images.githubusercontent.com/63702199/196700442-d6803a4d-093b-46da-ba6b-987e7082c4bc.png)

![image](https://user-images.githubusercontent.com/63702199/196700345-31f788c9-cbc2-4108-99c6-a2c4acd11e4e.png)

**Comment by Jenefer-Monroe** [comment]
Do you see this string at all in the **_Filter to Non Compliant Apps_** output? **_dataLossPreventionEvaluationResult_**

**Comment by clusterb0mb** [comment]
On successful runs in input:

![image](https://user-images.githubusercontent.com/63702199/196874867-69050252-9d61-4bad-81da-a0d002262c5f.png)

Not for unsuccessful runs:

![image](https://user-images.githubusercontent.com/63702199/196875044-e4b7f42a-3767-437e-a88a-c837160b9d3f.png)

**Comment by clusterb0mb** [comment]
Maybe the problem is a missing connector from the app from this run?

![image](https://user-images.githubusercontent.com/63702199/196879841-8cb9bac8-9a58-4772-9b15-bdd6ce032355.png)

**Comment by Jenefer-Monroe** [comment]
We had assumed all flows had this scope, I dont have any that have it missing. Must be some legacy issue sitting around. 
I think I can change the flow logic to just not assume this scope is always present. 
Thanks for investigating with me, I think I can fix this for Nov.

**Comment by Jenefer-Monroe** [comment]
ok just going with a very simple fix to only collect when specifically NonCompliant
![image](https://user-images.githubusercontent.com/89584709/197000176-cb4ce75e-c8bd-4539-9f40-fe3b962aa970.png)
