### ISSUE TITLE
[ALM Accelerator - QUESTION] Virtual Entity configuration

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#3959]
### What is your question?

We work with Finance & Operations and use Dataverse
Vitrual Entities(VE) in Power platform. Do you've any
plans to automate the VE configurations.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

October2022

**Comment by jenschristianschroder** [comment]
Will add this as an enhancement issue. Please vote for it if you think this is something that we should prioritize.

This is tracked here: https://github.com/microsoft/coe-starter-kit/issues/3965

Feel free to upvote and add to the conversation via replies to the issue

**Comment by mikefactorial** [comment]
Closing out as there's nothing more to do here
