### ISSUE TITLE
D365 Service Admin needs to be a "normal" user in COE env but cannot be.

### ISSUE THREAD

**Issue by samadane** [microsoft/coe-starter-kit#396]
**Describe the bug**
Setting up COE toolkit and need some D365 uses from environments to own some env records (and only certain records).  Issue is that one of the users they want to see only X amount of environments can see all records because in the tenant they are a D365 service admin.  So as soon as a D365 service admin gets added to the COE toolkit security group they are an auto system admin, but in reality in this instance they should only be a user. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
This is a product capability, not part of the CoE Starter Kit. D365 Service Admins and Power Platform Service Admins can see all environments, see: https://docs.microsoft.com/en-us/power-platform/admin/use-service-admin-role-manage-tenant
