### ISSUE TITLE
[ALM Accelerator - QUESTION] Multi tenant

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#3961]
### What is your question?

We manage customer tenants from our own-configured ALM and are replacing that with AA4PP do
we need to install AA4PP in each tenant?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

October2022

**Comment by jenschristianschroder** [comment]
This is tracked via this issue here: https://github.com/microsoft/coe-starter-kit/issues/3946

**Comment by mikefactorial** [comment]
Closing out as there's nothing more to do here
