### ISSUE TITLE
[ALM Accelerator - QUESTION] Dev and Prod tenants

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#3963]
### What is your question?

Will there be a way to have a dev tenant and a prod tenant with the ALM Accelerator?!

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

October2022

**Comment by jenschristianschroder** [comment]
You can absolutely have both a Dev and a Prod tenant. You would need to install and maintain the solution in both tenants.

You can also have a Dev and a Prod setup within one tenant. Many customers do so in order to have a setup where the can test new releases before upgrading production instances of ALM Acc.

**Comment by mikefactorial** [comment]
Closing out as there's nothing more to do here
