### ISSUE TITLE
[ALM Accelerator - DOCUMENTATION]  Upgrade or Update Solution

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#3964]
### What is your question?

 I really loved to use Patches but I understand that to version patches makes everything too complex .. so I'm ready to stop using them. I really like the option of "Upgrade" instead of "Update" and this was a little bit hidden

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

October2022

**Comment by jenschristianschroder** [comment]
Thanks, based on the feedback from the Office Hours we will publish more video content. I think this could be good 2 minutes video to explain a little bit about upgrade vs. update and how to configure

**Comment by mikefactorial** [comment]
Closing this out. Don't think this documentation falls under the Power CAT team's purview and should be guidance provided by the product team.
