### ISSUE TITLE
[CoE] Turning on HELPER flows under Governance Components

### ISSUE THREAD

**Issue by Lauwky** [microsoft/coe-starter-kit#3966]
### Describe the issue

When i try to turn on the HELPER | xxxx flows i'm being shown this error.

Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'WorkflowOperationParametersExtraParameter' and message 'The API operation does not contain a definition for parameter 'item/admin_recordguidasstring'.'."}}".

I have followed this guide https://learn.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov and tried the solution mentioned on this page

![image](https://user-images.githubusercontent.com/20787656/196151562-71194e75-b512-483f-a8cc-e300e81ed335.png)

### Expected Behavior

Hoping to turn on the flows

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

HELPER - all 3 of them

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/20787656/196151987-dc39ec58-8109-44c8-9b0a-586d54c147b4.png)

Selecting a flow and click "Turn On"

**Comment by Jenefer-Monroe** [comment]
Hello it looks like you upgraded Governance without Core components perhaps? 
Note that you need to ahve the solutions match. So all from Oct release, or all from Sept release, etc.

**Comment by Lauwky** [comment]
Hi Jenefer,

I have updated the Core Components and was able to turn on the HELPER | xxx Flows.

This is what I have now.
![image](https://user-images.githubusercontent.com/20787656/196202455-caaba1ac-06d9-4f66-b992-93227f9ab3e4.png)

Thank you for the quick assist.
You can close this request.

Kind Regards,
Pieter

**Comment by Jenefer-Monroe** [comment]
Thank you for the quick update! I'll go ahead and close out.
