### ISSUE TITLE
[CoE Starter Kit - BUG] Embedded App Error in CoE Dashboard

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#3967]
### Describe the issue

When adding the Admin - Access this App to the Power BI dashboard I get the following error:

PowerAppsforAdmins.GetAdminAppRoleAssignment failed: { "error": { "code": "BusinessAppPlatformRequestFailed", "message": "The request failed with client error: 'The environment '' could not be found in the tenant '******************'.'. The correlation Id is '0fe028fa-22f1-4f61-a724-078ad2bdbebb'.", "details": [ { "code": "MultipleErrorsOccurred", "message": "Multiple errors occurred. Please see details.", "details": [ { "code": "EnvironmentNotFound", "message": "The environment '' could not be found in the tenant '1627d263-3195-4b8a-abc5-2e1fb0cf5a9d'." } ] }, { "code": "FullNonLocalizedError", "message": "{\"error\":{\"code\":\"EnvironmentNotFound\",\"message\":\"The environment '' could not be found in the tenant '******************'.\"}}" } ] } }
![image](https://user-images.githubusercontent.com/17124284/196172327-5858296e-a0cd-40a2-9288-a8bd630c2a89.png)

The environment does exist in the tenant and there is no issue when adding the Admin - Access this flow app.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin - Access this app

**Comment by medicineshow** [comment]
Thanks. That has worked but I think you might need to look at what you have shipped as defaults in the Power BI dashboard because when I went to the apps tab it was completely blank and this in the filters
![image](https://user-images.githubusercontent.com/17124284/196233047-1cfca8cf-c3f6-4691-b61a-b59d98760a24.png)

Once I removed the App Type Custom page
![image](https://user-images.githubusercontent.com/17124284/196233404-67f6c4b9-c90c-41a2-a0d0-f9e7c6d8095b.png)

all my apps appear ok
![image](https://user-images.githubusercontent.com/17124284/196233688-a19a0e14-6b4d-4653-8f85-e82bc3e8cdaa.png)

The same on the Cloud Flows tab
![image](https://user-images.githubusercontent.com/17124284/196233939-c4e82c0a-7cae-45fa-b22c-d1b2f65604e6.png)

Remove Custom from the display name and Ben Waters from the Flow Maker
![image](https://user-images.githubusercontent.com/17124284/196234311-0fa547c2-15bb-458d-bb1b-39e2b108a0c9.png)


hey presto, everything appears :)

**Comment by Jenefer-Monroe** [comment]
yes thank you, we have a bug tracking that for November already, but appreciate you raising.

**Comment by Jenefer-Monroe** [comment]
ill go ahead and close out, thanks for being such great CoE starter kit users!
