### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to configure access to Power Platform Administration Planning app?

### ISSUE THREAD

**Issue by miroslav-harlas** [microsoft/coe-starter-kit#3968]
### What is your question?

Hello,
how can I properly configure access to model-driven app **Admin tasks** and to its underlying data, which is delivered as a part of the **Power Platform Administration Planning** solution? There is no security role prepared as part of the solution, and I do not want to assign *System Administrator* role to users of this app. There is no guidance documented about how to setup access for this component in the official article here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-admin-tasks-component

I can see there is just single Dataverse table, it shouldn't be complicated to prepare the custom security role. I can create it myself, of course, but why this is not automatically delivered as a part of this solution?

BTW: As far as **Power Platform Administration Planning** is a new part of CoE Starter Kit suite, please, could you also consider to add this solution as an additional option to the drop-down on GitHub when we are submitting new issues ("What solution are you experiencing the issue with?"). OR put there at least option "other", so we do not need to select "none". 😉 Or, is there any other github project, where we can raise issues and questions regarding **Power Platform Administration Planning** solution?

![image](https://user-images.githubusercontent.com/16306406/196176098-79958fe8-7e80-4f3c-ba5c-abe46fab2e39.png)

![image](https://user-images.githubusercontent.com/16306406/196176143-2766daca-9f6e-49b4-b7f0-73a63dadb5ea.png)

### What solution version are you using?

October 2022

### What app or flow are you having the issue with?

Power Platform Administration Planning

**Comment by manuelap-msft** [comment]
Hello,

looks like we're having a couple of growing pains with this new solution! We can target adding a custom security role for it for the November release, you're right it's only one table! 

Thanks for also highlighting that the solution is missing from our issue template, I'll get that added straight away!

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Issue template updated:
![image](https://user-images.githubusercontent.com/55705669/196180364-c9938117-932b-4411-8185-505e2dcb3e7d.png)

**Comment by Jenefer-Monroe** [comment]
added the security group and documentation for it for Nov.
