### ISSUE TITLE
[Power Platform communication site template] ISSUE TITLE

### ISSUE THREAD

**Issue by datcot** [microsoft/coe-starter-kit#3975]
### Describe your bug, question or feature ask.

![2022-10-17 10_07_50-Window](https://user-images.githubusercontent.com/100955103/196220625-0d29866c-9a6c-4bfa-9ccd-42bc5b3c0052.png)
Hello, in the attached is the error message i got when trying to run the test at step 2 in Start a subscription to audit log content (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content). It is worth noting that we already have one environment with the same Redirect URL in our Azure Tenant. Would that be the reason why? Or where should I start troubleshoot at? Thank you in advance.

**Comment by Jenefer-Monroe** [comment]
You can use the same app across multiple environments. So thats ok. 
The message indicates you may have put in the secret's ID (its GUID) and not the secret itself. That's a common mistake as well. Can you please retry?

**Comment by datcot** [comment]
That did work! Thank you so much!

**Comment by Jenefer-Monroe** [comment]
You are so welcome!
