### ISSUE TITLE
[ALM Accelerator - QUESTION] Hooks for post deployment

### ISSUE THREAD

**Issue by rfarris2000** [microsoft/coe-starter-kit#3976]
### What is your question?

I have a question about the hooks:

Let's say I want to deploy the managed solution of a new build to several development environments but only after the deploy to test (or production).  

I could have a script that detects the environment that was just deployed and if it's the one I want I can deploy to the developer environments, correct?

Example:

CORE SOLUTION -> Deployed to validation 
PR to Test approved and deployed to test:

deploy-solution-post-hook.yml could be updated to call my custom template to deploy to each developer environment, 
correct?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Latest

**Comment by mikefactorial** [comment]
@rfarris2000 thanks for the question. That would be one way to do it. 

Another way would be to create pipelines for the other environments depending on how many environments you have. The latter would also allow you to create specific deployment settings for those target environments if there's anything that needs to be shared / configured etc. 

Several releases ago we introduced the idea of bring your own pipeline templates that requires some manual setup but would allow you to add more named deployment steps to your deployment profile.

https://learn.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-pipelines#customize-the-number-of-deployment-steps-in-your-pipelines-and-the-names-of-the-target-environments

An example would be to create a new Deployment Step called "DevEnvironment1, DevEnvironment2 etc." and points to the Deployment Environment in question. You can also specify the Pipeline Template file in your pipeline templates repo that would be a copy of https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/build-deploy-prod-SampleSolution.yml to generate the deployment pipeline on the next export of the solution.

The additional steps would then show up in the configure depeloyment settings screen.

**Comment by mikefactorial** [comment]
Your solution is likely the easiest if you don't need to configure any deployment settings for the target environments. There's an example of how to get the pipeline's run parameters in https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/Hooks/CustomTemplates/output-deploy-parameters.yml.

This would give you access to the solutionName and environmentName which would likely be sufficient for your deployment logic.

**Comment by rfarris2000** [comment]
@mikefactorial I took another look and I'm going to use release pipelines with approvals so the developer can approve to install it when they want.  I'm working through that now.

**Comment by mikefactorial** [comment]
Good idea. Let us know how it goes. Would be good learnings for others.
