### ISSUE TITLE
[ALM Accelerator - QUESTION] Pull Request - Build Validation stays in queue

### ISSUE THREAD

**Issue by rpa-aa** [microsoft/coe-starter-kit#3980]
### What is your question?

Hello,
I have installed/configured the ALM Accelerator for Power Platform and now I am testing it.
I have made a commit and now want to deploy my solution. The problem is, that the depoly is not running.
The build validation stays in the status queue and I have no idead why.
I have abandoned the deploy twice after 30 minutes of waiting, but every time (three times) it keep staying in queue.
Had anyone the same issue? I tried to google the issue but could not find any helpful entries.
Thanks and regards!

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20221004.2

**Comment by mikefactorial** [comment]
@rpa-aa it's possible that the validation build is waiting for access to resources. If you open the build validation pipeline run you may see that it is requesting access to resources. e.g. the global variable group, the service connection or the repository.

You can get around this by configuring specific permissions after install. https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#update-permissions-for-the-project-build-service

**Comment by rpa-aa** [comment]
I think the problem is the branch policy. I configured it like in the documentation to set up the ALM.
I deployed to a branch without policies and there the pipeline run directly.
I will check the link you sent me, thanks.

**Comment by rpa-aa** [comment]
@mikefactorial I found some articles which say that there is bug with hypens in the repo name and I have hypen in my repo name.
Do you know something about this bug? Here is one of the articles.
https://developercommunity.visualstudio.com/t/pipeline-template-could-not-get-latest-source-vers/579239

**Comment by mikefactorial** [comment]
All of our internal testing repos have dashes in their names so that's likely not the issue. Can you provide a screenshot of the PR and of the pipeline when it's in the waiting state you described? That may shed some light.

**Comment by rpa-aa** [comment]
Here is a screenshot of PR
![grafik](https://user-images.githubusercontent.com/115477263/196715579-a9f82dd7-2cfa-4b5a-804b-3b5c4f59a005.png)

and here of the waiting pipeline
![grafik](https://user-images.githubusercontent.com/115477263/196717210-59ed1d0c-343a-45a3-a3ab-1665e7b7b16d.png)

I have deactivated the policy branch and then the deploy was running.
I think I have a general missunderstanding of the ALM and his use. Maybe you can help me here.
I have created 4 environments (dev, val, test and prod) and in DevOps I have created a branch for my StagingSolution. I also have created pipelins for this solution (like in the documentation). Here begin my questions. When I deploy from dev to val, which branches do I have to chose? I have created a new branch for the commit (username@domain-Solutionname) and then deployed from this branch to the solution branch. If the deployment to val is successfull, it should be automatically deployed from val to test, right?
From to which branch should be used if I want to deploy from test to prod?
I have made sometest which solutions without own pipelines and branch policies. In this test, the solutions were deployed from dev over val to test. I could see the solutions in power platform but they were not displayed accelerator. This is also strange.
Can you please explain me how to use the branches and environments correctly?
Sorry for the long description

**Comment by mikefactorial** [comment]
@rpa-aa looks like you have the wrong pipeline specified in your branch policy. Should point to the deploy-validation-* pipeline. 

Your understanding of the branching is correct. With a couple of notes. 

"If the deployment to val is successfull, it should be automatically deployed from val to test, right?" - Once the validation build completes you will need to complete the PR in order for the test build to kick off unless you have selected "Bypass Approval" during the deployment in the ALM Accelerator App

Once deployed to test
You can initiate the deployment from test - production by creating a PR from your Solution Branch to main. 

This ensures that everything in main is representative source code of what is in your production environments while the solution branch is the work in progress until the next push to production.

"I could see the solutions in power platform but they were not displayed accelerator" - Only deployments / exports etc. that are initiated from the ALM Accelerator app will be reflected in the app so you won't see any builds that were run manually in Azure devops.

Finally, it's not necessary to manually create your solution branch and solution deployment pipelines. That is now handled the first time you export a solution.

You can try this yourself with a new solution by exporting to a new branch based on "main". After the export completes your SolutionBranch and the deployment pipelines will be automatically created.

**Comment by rpa-aa** [comment]
@mikefactorial  thank you very very much for your explanations and I think I have now a better understanding.
That the branch and pipelines for a solution are now build automatically is good to know. Does that mean, that when I would configure the Accelerator again I could skip the steps to create the branch and pipelines of a solution?
And one final important question, if the accelerator does not display solutions, which were run manually, how can I deploy from test to prod? It is recommended to use the bypass approval, so that I don´t have to complete the PR? Or do I have to import the solution in the accelerator?
Thanks again very much.

**Comment by mikefactorial** [comment]
@rpa-aa

1. "Does that mean, that when I would configure the Accelerator again I could skip the steps to create the branch and pipelines of a solution?" - yes you can skip those steps as they will be performed on the first export of the solution by the export pipeline.
2. "how can I deploy from test to prod" - deploying from test to prod is accomplished by creating a PR from the ALM Accelerator from your solution branch to main via the Deploy Solution. If you choose to bypass approval here the pipeline to deploy to production will happen automatically unless you have specific policies setup on your main branch.


![Image](https://user-images.githubusercontent.com/42348035/197062343-40663af4-2f1c-4c2e-9822-b0e1dae00814.png)

**Comment by rpa-aa** [comment]
@mikefactorial  Thank you very much again.
Just to be sure, the PR from the solution repo to the main repo is made in the test environment (to deploy from test to prod), right? Like I discripted earlier, I cannot see the solutions in the validation and test environment, so how can I deploy from test to main?

I noticed that I don´t have the Bypass Approval button. I have Accelerator version 1.0.20221004.2. Is my version to old?

**Comment by mikefactorial** [comment]
@rpa-aa looks like I missed your last question. Pardon the delay. Only unmanaged solutions are shown in the App since only unmanaged solutions can be updated or exported in the platform. Managed solutions are immutable and can't be exported so it wouldn't be possible to use the ALM Accelerator with managed solutions. Closing out this issue for now since it's no longer directly on topic with the original question. Feel free to open a new issue if you have further questions.
