### ISSUE TITLE
[CoE Starter Kit - BUG] F&O Sandbox under Power Platform CE URL not available in COE Portal

### ISSUE THREAD

**Issue by Raz-786** [microsoft/coe-starter-kit#3987]
### Describe the issue

Hi 
I Deploy F&O module along with install D365 CE instance  (without Database) via LCS portal . but when i check COE appplication under environment  "Environment CDS Instance URL" does not show URL.

Keep in mind this is  the only F&O instance in our environment 

### Expected Behavior

Technically I should see the URL like any other Native D365 instance under "Environment CDS Instance URL"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

not sure which flow pull this info

### Steps To Reproduce

Browse COE in browser
Click Environment
Search for F&O sandbox and found it has missing URL under "Environment CDS Instance URL"

### Anything else?

![image](https://user-images.githubusercontent.com/116106952/196505296-f3061b91-b8de-498c-a1d6-3eac42108fef.png)

**Comment by Jenefer-Monroe** [comment]
Can you please open the **_Admin | Sync Template v3_** flow and get the output of the **_Get Environments_** action
![image](https://user-images.githubusercontent.com/89584709/196567486-05667a43-9ba8-45c9-b595-628645ac4e26.png)

If you put the output in some kind of JSON parser that will make this easier. 
Look for your environment in the results and then look at its linkedEnvironmentMetadata node. Does it have data? 
![image](https://user-images.githubusercontent.com/89584709/196567713-0ab6e70f-4619-43d6-8469-6c91c08fa093.png)

If you go to the [admin pages](https://admin.powerplatform.microsoft.com/environments) and find your environment, do you see the URL there? 
![image](https://user-images.githubusercontent.com/89584709/196567884-3bb4e31a-1ee9-48c2-8b4f-36e403a4142b.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Raz-786** [comment]
Hi Monroe,

Please accept my sincere apology, since I am new to this technology (COE) having difficulty to follow your steps. Is there any way if we setup a meeting and can troubleshoot together?

Another question, are you MS employee or 3rd Party vendor?

Please advise

**Comment by Jenefer-Monroe** [comment]
Hello. I work as a vendor for the Microsoft Power Platform CAT team. Our team is small and not staffed to meet with our GitHub customers so I'm afraid I cannot offer that type of 1:1 assistance. 

However, we have many partners that offer CoE install and configuration services - you can find them via AppSource: 
https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1

Hope that helps.
