### ISSUE TITLE
[CoE Starter Kit - QUESTION] Not all solutions are visible

### ISSUE THREAD

**Issue by MantasSal** [microsoft/coe-starter-kit#3994]
### What is your question?

Hello,

CoE is updated to latest version.
I do not know if this is a bug, but not all Solutions are visible. 0 solutions are visible from some environments, although it says that there are 20 environments in total in the up left corner.
In Power Platform Admin View also environments are missing.

![image](https://user-images.githubusercontent.com/114066875/196693832-875fad29-b166-4417-ae5c-da782df73373.png)

**Comment by Jenefer-Monroe** [comment]
Hello sorry I'm confused. Are you saying the Environments themselves are missing from the reporting and the Power Platform Admin View app? Or just that there re environments where you expect solutions but no solutions are listed for those environments.

**Comment by Jenefer-Monroe** [comment]
OK I got it now, thank you. You will need to find a repro of this in your tenant to see what is going wrong. 

1. Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)
Let's use this repro of **_BDO O365 World_**

3. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

4. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page. (For you this will be **_Admin | Sync Template v3 (Solutions)_**
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

5. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

6. Once you are here, see how many solutions come through
![image](https://user-images.githubusercontent.com/89584709/197538330-99932a03-a99a-4ecb-a435-309124346d57.png)

**Comment by MantasSal** [comment]
Hello,

I got this:

![image](https://user-images.githubusercontent.com/114066875/198027846-2984bd87-72cf-4265-b918-b7ff446d4c89.png)

**Comment by MantasSal** [comment]
Expanded Put Solutions in CoE
It says 13
![image](https://user-images.githubusercontent.com/114066875/198028875-2405fc5e-9b17-4c68-a7ea-bb527783b102.png)

**Comment by Jenefer-Monroe** [comment]
OK great. And can you please go back to your PBI and make sure you have it refreshing? You need to be sure both the report and the Dataset are refreshing
Here is some help on setting up scheduled refresh [Configure scheduled refresh](https://learn.microsoft.com/en-us/connect-data/refresh-scheduled-refresh)
![image](https://user-images.githubusercontent.com/89584709/198084997-0ad6cf9d-7826-41b5-8b87-f6a3ba61aafb.png)

**Comment by MantasSal** [comment]
Hello,

Thank you for reply.
I get this. It looks like it does not refresh.
How frequently refresh should be setup? You provided link does not work, thank you again.

![image](https://user-images.githubusercontent.com/114066875/198977016-1d716b41-fce0-48d9-a774-118b36a9cfaa.png)

**Comment by Jenefer-Monroe** [comment]
Sorry about that, here you go https://learn.microsoft.com/power-bi/connect-data/refresh-scheduled-refresh

**Comment by Jenefer-Monroe** [comment]
You should refresh daily as that is how often the sync flows run. Hope that helps!

**Comment by MantasSal** [comment]
Hello,
could you advice, please, I see scheduled refresh option only under dataset:
![image](https://user-images.githubusercontent.com/114066875/199001160-acfb04f3-1ea9-4923-89ea-f9cfd05bf695.png)

Under report I do not see it, so scheduled refresh option should be only for dataset?
![image](https://user-images.githubusercontent.com/114066875/199001429-fd42ee6f-a59e-4e79-9fb9-4a90bd1a7b0a.png)

**Comment by Jenefer-Monroe** [comment]
Thats correct. Sorry, above I just meant that most people hit refresh in the report and don't know they have to refresh the dataset. 
The scheduled refresh only occurs on the dataset.

**Comment by MantasSal** [comment]
Ok, now I have scheduled the refresh.
I guess I should wait and check if I see more Solutions under Solutions tab in CoE?

**Comment by Jenefer-Monroe** [comment]
You can also do a manual refresh anytime so, you should see that option on the dataset too. Go ahead and do that and then see what you see in the report

**Comment by MantasSal** [comment]
Hello,
I can see solutions only from two environments. Nevertheless not all solutions from these environments are shown. 
[image](https://user-images.githubusercontent.com/114066875/199676214-3eb906de-441e-47f5-9d41-a766ce50c6f9.png)

For example these solutions are not shown
![image](https://user-images.githubusercontent.com/114066875/199677679-b8e22cb2-e761-4709-8a5d-f0a9f4945c74.png)

**Comment by Jenefer-Monroe** [comment]
If you have a specific solution that you think should show that isnt a Microsoft Product solution, please go to https://make.powerapps.com/ > chose the environment you are investigating here where you expect the target solution to appear > Dataverse > Tables > All > Find Solutions table and click on it
![image](https://user-images.githubusercontent.com/89584709/199716975-34793fc0-d83a-4a33-a815-c72ce55b7389.png)

Add columns until you have the following shown
![image](https://user-images.githubusercontent.com/89584709/199717269-c503da15-a242-428d-ba9a-07de96728a4b.png)
![image](https://user-images.githubusercontent.com/89584709/199717534-e3cba3a2-08d9-44da-838b-86f4073b6d00.png)

Find your target solution in the table and return with what is shown in the table.

**Comment by Jenefer-Monroe** [comment]
We did fix an issue in the Nov release in which some solutions have their GUID reused by the product so if the solution is in multiple environments it might only show in one: https://github.com/microsoft/coe-starter-kit/issues/3772

**Comment by MantasSal** [comment]
Hello,

I found these solutions in table, they are not shown in CoE dashboard under Solutions. Actually, non from current environment is shown under Solutions.
![image](https://user-images.githubusercontent.com/114066875/200288082-6fd99e27-0092-4b41-9ff6-5d72584de19f.png)

**Comment by Jenefer-Monroe** [comment]
I suspect it is this issue then https://github.com/microsoft/coe-starter-kit/issues/3772 if all are missing from one environment. They are likely just attributed to another environment

**Comment by MantasSal** [comment]
Hello,

So solution would be to update to nov release?

Thanks,
Mantas

**Comment by Jenefer-Monroe** [comment]
Correct. [Upgrade](https://learn.microsoft.com/power-platform/guidance/coe/after-setup) to Nov release, and then allow the flows (Delete Bad Data and the Sync flows) to run.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
