### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin - Sync Audit Logs

### ISSUE THREAD

**Issue by MantasSal** [microsoft/coe-starter-kit#3995]
### What is your question?

Hello,

CoE is updated to latest version.
We get this error BadGateway in Admin - Sync Audit Logs flow

![image](https://user-images.githubusercontent.com/114066875/196696282-71b4e265-91f3-4a89-8740-ba0cb3676b25.png)

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

Admin - Sync Audit Logs

**Comment by eric-duncan-pdx** [comment]
I have been seeing this error as well since updating Core to 3.5.3

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
