### ISSUE TITLE
[CoE Starter Kit - BUG] Errors in Admin - Access this Flow

### ISSUE THREAD

**Issue by ShinraTenseiii** [microsoft/coe-starter-kit#3998]
### Describe the issue

I am trying to embed 'Admin - Access this flow' into the Power BI Report. 

I am getting 2 errors.
1.
![Access this Flow](https://user-images.githubusercontent.com/84532843/196701118-2f5203ba-6cca-48ed-bc16-d49e98291bf9.png)
2.

![Access this Flow 2](https://user-images.githubusercontent.com/84532843/196701361-e040ebea-c97d-4146-8988-78895532e49c.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Power BI Production Dashboard Oct 2022

### Steps To Reproduce

1. While configuring embedded apps in the cloud flow details page select admin_flowenvironment and admin_flowid.
2. Select the environment where your CoE solution is installed and select the 'choose the app' option.
3. Select 'Admin - Access this flow' App

**Comment by ShinraTenseiii** [comment]
Thank You @Jenefer-Monroe

**Comment by Jenefer-Monroe** [comment]
you bet!
