### ISSUE TITLE
[CoE Starter Kit - BUG] BPFs active but not showing in Admin View App

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#4005]
### Describe the issue

Hi, 

I have activated the BPF for Teams environments, that worked, but the process is not showing in Power Platform Admin View App.
This process should be visible for all Teams environments, not only for those created after the installation of the kit right? (I did check it for new Teams environments, still not showing).
All the business process Flows can be activated, but are not showing up.

Love to geht help on that!

Best regards Cathi

### Expected Behavior

BPF showing up in Power Platform Admin View App

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_3.53_managed

### What app or flow are you having the issue with?

BPF´s & Power Platform Admin View App

**Comment by Jenefer-Monroe** [comment]
Are you saying that you are seeing it for Teams environments created after the setup, but not Teams environments created before setup?

**Comment by Cathi029** [comment]
neither nor, process ist not showing at all, none of the BPF´s after activation.

**Comment by Cathi029** [comment]
Thanks, that worked. 
I did not knwo this possibility. In previous versions of the Kit, this step was not nessesary. 
Will only those Teams environments with this process turned on be considered in the governance flows for the Teams environment approval?

**Comment by Jenefer-Monroe** [comment]
We will be doing a pass through of these BPFs for the Jan release and will validate their behavior at that time. 
closing out as no further action for starter kit team
