### ISSUE TITLE
[ALM Accelerator - BUG]: Environment Order is wrong 

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#4006]
### Describe the issue

We have noticed that Environment order in Canavas app under profile is not correct, and it confuse our users. Kindly check and advise

Order should be  Validation-> Test -> Production . 
Please see below screen shot , It showing different order
![image](https://user-images.githubusercontent.com/44782172/196937514-6ce65e79-8a08-4635-98c8-bec7f48d3973.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Sep 2022

**Comment by mikefactorial** [comment]
Thanks for reporting this @linujohn22. This was resolved in the October release.
