### ISSUE TITLE
Reporting on per flow usage - total runs from the date published 

### ISSUE THREAD

**Issue by cs-sgws** [microsoft/coe-starter-kit#4008]
### Describe the issue

I am building a PowerBi Report to get flow/Power Automate  usage (runs). Basically I need to know the number of successful and failed executions or runs per flow. I am unable to determine the column from the Flow tables that applies to runs per flow.

 

### Expected Behavior

Would like to get the data usage for each flow in all my environements, that list the usage of each flow per run()fails/successful) on a weekly, month to month or yearly report 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.0

### What app or flow are you having the issue with?

Reporting on per flow usage - total runs from the date published 

### Steps To Reproduce

no reporduction of the issue as there is no way to obtain the data from the tables

**Comment by manuelap-msft** [comment]
Hello,

cloud flow runs are currently not available from the product for us to consume in the CoE kit - they are available in the Power Platform Admin Center under tenant-level analytics so you can get them from there.

Going forward, we are working on integrating the kit with the Data Export feature (see #424): https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics and this will have cloud flow runs. You can set the data export up yourself to get the data as well. 

Closing out this as it will be met with our BYODL integration, and there's no other way to get this data.
