### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by RocketmanACEGov** [microsoft/coe-starter-kit#4012]
### What is your question?

Hi Team,

As we have a strategic customer who would like to utilize data for the following 3 record types listed below to be pulled. I have a couple of questions pertaining to the attached Images 1 & 2.  Thanks in advance for your time and input.

Record types: (DeletePowerApp, DeleteFlow, & PowerAppPermissionEdited)

 1. Did we intend on retrieving 4 types of records regarding app metrics when we only have a switch operation for 3/4?
 
2. Would this break any flows/reports that ref the Audit log table if we create/modify Switch operators for the other 3 types of records (DeletePowerApp, DeleteFlow, & PowerAppPermissionEdited)?

3. Would this be considerable leg work to ensure these other 3 types of records populate data into the same Audit log table in the same fashion this flow handles the first types of record (LaunchPowerApp)?

Image 1: ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/116227636/197002848-45b66721-4e8a-41ee-b463-714c388fba94.png)

Image 2: 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/116227636/197003163-fef5a5c9-33f0-4d70-af5e-876f17f8c63c.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

CenterofExcellenceAuditLogs_2.10_managed / October 2022

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
We used to use these other types but the return from the office logs changed and we were no longer able to use the return. If I recall correctly (its been a while) the delete operation stopped returning the object id and just returned the user id of who performed the delete. 
Adding new switch paths should not break anything using the flow for launches but will leave you with an unmanaged layer such that you would not be able to get updates from us, but we arent really investing here anymore so you should be fine and can just watch for updates there. 
Hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
