### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by MelissaM13** [microsoft/coe-starter-kit#4013]
### What is your question?

Our Situation: We have a custom environment that is orphaned within the CoE data due to the MS user account that created the environment is no longer in use and disabled. The environment is operational (and will remain operational) and the apps and flows within are currently being used.

Currently, we don't have the CoE Governance components, Inactivity and Orphan Cleanup processes, activated.

However, if those processes were turned on, what would the impact be in our situation? 
How does the Environment Orphaned = Yes impact the Inactivity/Orphan Cleanup processes? 
Would the apps, flows, and environment be deleted?
What is the intended purpose of the Environment Orphaned field?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.19

### What app or flow are you having the issue with?

Inactivity and Orphaned Cleanup

**Comment by Jenefer-Monroe** [comment]
Neither of these processes depend on the isOrphaned field. We don't use that field currently for any of our processes, we just mark all objects as orphaned when the user no longer resolves. Individual organizations can add funcionality for orphaned objects beyond canvas apps / cloud flows which is where our features focus. 
Hope that helps/

**Comment by MelissaM13** [comment]
Yes, your explanation helps. Thank You!

**Comment by Jenefer-Monroe** [comment]
good to hear. And for clarity, I mean that we don't use that field in the Environment table, we do use it from the Flow and Power Apps table for those processes you mention.

**Comment by MelissaM13** [comment]
Thanks.
