### ISSUE TITLE
[ALM Accelerator - BUG]: Can't edit AI Models after Tenant Migration

### ISSUE THREAD

**Issue by ddomboy** [microsoft/coe-starter-kit#4016]
### Describe the issue

Hey together,

recently I migrated some flows with its related AI models into another environment. But now I am not able to edit the AI models anymore. 

Is there any common suggestion to solve this problem?

Thanks in advance

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

-

**Comment by mikefactorial** [comment]
@ddomboy thanks for reporting this. Likely an issue with ownership or sharing in the downstream environment. We haven't spent a lot of time on AI Model scenarios so thanks for letting us know so we can track this specific issue down. We've had similar issues submitted related to Desktop Flows so could be a similar gap.

**Comment by mikefactorial** [comment]
@ddomboy after re-reading this issue it doesn't appear to be related to the ALM Accelerator and is a platform specific issue. You'll need to work with support for this as we're not able to help troubleshoot problems with the platform. Closing for now
