### ISSUE TITLE
[CoE Starter Kit - BUG] upgrade failed from 1.71.1

### ISSUE THREAD

**Issue by BenGillard1987** [microsoft/coe-starter-kit#4019]
### Describe the issue

Solution Import Failure
Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 19 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoEConnection, Id: bdd972a8-abce-41cb-a9b7-0ae3a7a3a5a8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: db83acb6-f2c3-4051-a0a8-2c99e86a54a6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Approval Clean Up, Id: 0d0f5e5e-661f-eb11-a814-000d3a1bb7bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: db83acb6-f2c3-4051-a0a8-2c99e86a54a6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoETeamsIntegration, Id: 4b82accb-dcb6-4580-9a57-4db56801c883, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created, Id: 33024c20-c222-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoETeamsIntegration, Id: 4b82accb-dcb6-4580-9a57-4db56801c883, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments, Id: 708e4fc8-5e23-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSMainCoETeamsIntegration, Id: 935d41d4-7ea7-4c92-9155-557adacc7594, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created, Id: 33024c20-c222-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSMainCoETeamsIntegration, Id: 935d41d4-7ea7-4c92-9155-557adacc7594, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments, Id: 708e4fc8-5e23-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: fda24345-a18a-4c29-b6a7-5a132fc86ec4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: fda24345-a18a-4c29-b6a7-5a132fc86ec4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Approval Clean Up, Id: 0d0f5e5e-661f-eb11-a814-000d3a1bb7bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: f8029b33-00b8-4a0e-b710-72d97c5f6ce4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: f8029b33-00b8-4a0e-b710-72d97c5f6ce4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: f8029b33-00b8-4a0e-b710-72d97c5f6ce4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: f8029b33-00b8-4a0e-b710-72d97c5f6ce4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Check Approvals, Id: c7982cc4-3024-eb11-a813-000d3a8c389b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: c8e7f3b4-2713-4460-8d3b-92af04e4d6ca, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: c8e7f3b4-2713-4460-8d3b-92af04e4d6ca, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Approval Clean Up, Id: 0d0f5e5e-661f-eb11-a814-000d3a1bb7bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: c8e7f3b4-2713-4460-8d3b-92af04e4d6ca, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: c8e7f3b4-2713-4460-8d3b-92af04e4d6ca, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_MicrosoftTeamsCoEConnection, Id: 519879d9-b85f-4598-a0aa-cc0c00ab3428, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created, Id: 33024c20-c222-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_MicrosoftTeamsCoEConnection, Id: 519879d9-b85f-4598-a0aa-cc0c00ab3428, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments, Id: 708e4fc8-5e23-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

### Expected Behavior

To import succesfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.71.1

### What app or flow are you having the issue with?

Full Solution Import

### Steps To Reproduce

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 19 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoEConnection, Id: bdd972a8-abce-41cb-a9b7-0ae3a7a3a5a8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: db83acb6-f2c3-4051-a0a8-2c99e86a54a6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Approval Clean Up, Id: 0d0f5e5e-661f-eb11-a814-000d3a1bb7bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: db83acb6-f2c3-4051-a0a8-2c99e86a54a6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoETeamsIntegration, Id: 4b82accb-dcb6-4580-9a57-4db56801c883, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created, Id: 33024c20-c222-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoETeamsIntegration, Id: 4b82accb-dcb6-4580-9a57-4db56801c883, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments, Id: 708e4fc8-5e23-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSMainCoETeamsIntegration, Id: 935d41d4-7ea7-4c92-9155-557adacc7594, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created, Id: 33024c20-c222-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSMainCoETeamsIntegration, Id: 935d41d4-7ea7-4c92-9155-557adacc7594, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments, Id: 708e4fc8-5e23-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: fda24345-a18a-4c29-b6a7-5a132fc86ec4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: fda24345-a18a-4c29-b6a7-5a132fc86ec4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Approval Clean Up, Id: 0d0f5e5e-661f-eb11-a814-000d3a1bb7bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: f8029b33-00b8-4a0e-b710-72d97c5f6ce4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: f8029b33-00b8-4a0e-b710-72d97c5f6ce4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: f8029b33-00b8-4a0e-b710-72d97c5f6ce4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: f8029b33-00b8-4a0e-b710-72d97c5f6ce4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Check Approvals, Id: c7982cc4-3024-eb11-a813-000d3a8c389b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: c8e7f3b4-2713-4460-8d3b-92af04e4d6ca, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: c8e7f3b4-2713-4460-8d3b-92af04e4d6ca, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Approval Clean Up, Id: 0d0f5e5e-661f-eb11-a814-000d3a1bb7bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: c8e7f3b4-2713-4460-8d3b-92af04e4d6ca, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: c8e7f3b4-2713-4460-8d3b-92af04e4d6ca, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_MicrosoftTeamsCoEConnection, Id: 519879d9-b85f-4598-a0aa-cc0c00ab3428, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created, Id: 33024c20-c222-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_MicrosoftTeamsCoEConnection, Id: 519879d9-b85f-4598-a0aa-cc0c00ab3428, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments, Id: 708e4fc8-5e23-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with our without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help you get started with migrating the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Sorry we cannot be of more assistance here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
