### ISSUE TITLE
[ALM Accelerator - QUESTION] Pipeline Step: Set Connection Variable is not returning the variables

### ISSUE THREAD

**Issue by grburner** [microsoft/coe-starter-kit#4020]
### What is your question?

I am unable to commit a solution because I am running into an error in the pipeline at the step: Set SpnToken for use by other tasks that need one.

It fails with this error: Invoke-RestMethod : {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '***' was not found in the directory...
					
I confirmed that the previous step: Power Platform Set Connection Variables, is getting the correct inputs, service connection name ('https://orgc139748c.crm.dynamics.com/'). When I log the variables passed into "Set SPN Token" I get this:

Tenant Id: ***
Client Id: ***
Client Secret: ***

So I think something is failing with the power platform build tool being used in the previous step: microsoft-IsvExpTools.PowerPlatform-BuildTools.set-connection-variables.PowerPlatformSetConnectionVariables@2

<img width="463" alt="image" src="https://user-images.githubusercontent.com/37910376/197276215-2c66e0a6-a97e-4111-8e57-fe8cf7b8f254.png">

I'm having trouble finding documentation on that build tool task and am not sure how else to debug this issue.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

October 2022 download

**Comment by mikefactorial** [comment]
@grburner pardon the delayed response on this appears to have been lost in the shuffle. Were you able to figure out what was going on here?

**Comment by mikefactorial** [comment]
Closing this out for now since there's been no response. Feel free to open a new issue if this persists
