### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Null could not be found in tenant id

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#4024]
### Describe the issue

Setting up the CoE Starter kit, got the following error on the step where I need to run Admin | Sync Template v3 flow

`The request failed with client error: 'The environment '<null>' could not be found in the tenant '48d1dcb6-bccc-4365-ac7f-b937a7f7fd71'.'. The correlation Id is '2adb46e6-b02b-413e-bf88-42cc91235c8f'.`

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Latest October version

### What app or flow are you having the issue with?

Admin - Sync Template v3

### Steps To Reproduce

Ran Admin | Sync Template flow as per documentation.  I did have to manually start the flow, as it did never run when I imported the core components and turned the flow on two days prior.

Documenation - 

**Wait for flows to finish
After the sync flows have finished running, you're ready to use many of the features of the CoE Starter Kit core solution.

The first run of the inventory can take a few hours depending on the number of environments and resources in your tenants. Future runs will be faster, because they'll only look at new and modified resources.

To check the status of a flow

Select Admin | Sync Template v3.

This will open a new tab to the Flow detail page.

View Runs.**

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot so that we can see where in the flow this failure is occurring?

**Comment by Jenefer-Monroe** [comment]
That error shown is a caught error, it occurs when an object is new to inventory, is caught and then the flow goes down the "new" path
![image](https://user-images.githubusercontent.com/89584709/197576882-d1021ca6-2378-48f0-bb1a-5b66280a65d5.png)

**Comment by Jenefer-Monroe** [comment]
In order to investigate the failure you will need to first find it. Click Next Failed to get to the failure and then find where it terminates 
![image](https://user-images.githubusercontent.com/89584709/197577063-6afab22f-79a0-48f8-863e-45923133c1e9.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
