### ISSUE TITLE
[CoE Starter Kit - BUG] The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '210014295' bytes. This exceeded the maximum size '209715200' bytes allowed.

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#4025]
### Describe the issue

Getting the following error when Admin | Sync Template v3 (Connection Identities) is ran against our default prod environment

The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '210014295' bytes. This exceeded the maximum size '209715200' bytes allowed.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October release

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

### Steps To Reproduce

Flow runs automatically, when it does our prod env, it gets that error, not sure how to resolve

**Comment by Jenefer-Monroe** [comment]
This failure is in an out of the box connector’s action, which we're just using. Unfortunately, it has a size limitation that you have exceeded. 

We cannot fix this, but you can manually clean up some of the old connections via Power Shell and then be under the size limit. We have documented this limitation here along with a starter solution to address via PowerShell: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#set-up-connection-cleanup-broken-connections

Hope that helps

**Comment by JayCecchine** [comment]
Thank you I will try that out!

**Comment by pagelib222** [comment]
Hi JayCecchine. Did you solve this issue on your side with the clean up? Would be great to get this information. We run in the same issue.

**Comment by RebekkaAalbers** [comment]
To bad, but understandable. Thanks anyway.
