### ISSUE TITLE
[CoE Starter Kit - Power Automate Management connector] When will be the Third-party option in the connector removed?

### ISSUE THREAD

**Issue by A-Demir-ilx** [microsoft/coe-starter-kit#4028]
### What is your question?

Our end users use the developer compliance center and find it quite difficult to set up the power automate management connector when launching the app for the first time.

Do you know when the third-party option will removed in the connector?

![power automate management](https://user-images.githubusercontent.com/96475793/197508089-7c7082c2-070e-4ab1-a2e7-0f4825bfa660.png)

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by Jenefer-Monroe** [comment]
I do not know the answer to that. We are a very small team and cannot scale to answer generalized product questions. 
Sorry I cannot be of more assistance.

**Comment by A-Demir-ilx** [comment]
Thanks @Jenefer-Monroe ! Do you know the right person for this?

**Comment by Jenefer-Monroe** [comment]
I do not. You can create a support ticket to ask or pose in the power user community (https://powerusers.microsoft.com/). I see a channel specific to connectors there that may be of assistance: https://powerusers.microsoft.com/t5/Using-Connectors/bd-p/ConnectingToData

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
