### ISSUE TITLE
[ALM Accelerator - BUG]: Issue "Cannot add a Root Component" after upgrading from older release

### ISSUE THREAD

**Issue by Ballzer0** [microsoft/coe-starter-kit#4029]
### Describe the issue

We have been stuck on the March release for a really long time, last week we attempted to upgrade following every single patch note and applying them in order.

This is the current version of the pipeline template we are using:
https://github.com/microsoft/coe-alm-accelerator-templates/releases/tag/CenterofExcellenceALMAccelerator-October2022-HF1

Ever since we upgraded we have had trouble installing unmanaged solutions.

![image](https://user-images.githubusercontent.com/28560729/197571464-97c604ae-e883-4085-b666-09e14a392714.png)

This happens whenever we try to "import solution" from source using the ALM Accelerator for Power Platform app.

I have  tested with multiple different solutions and they all have the same error but with different missing "Root Component"
```
Message: Cannot add a Root Component shi_deviation of type 1 because it is not in the target system.Detail: 

```

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

 1.0.20221004.2

### Anything else?
the artifact the pipeline produces
[shi_helper_import-shi_helper.zip](https://github.com/microsoft/coe-starter-kit/files/9853197/shi_helper_import-shi_helper.1.zip)

_No response_

**Comment by mikefactorial** [comment]
@Ballzer0 this looks like a missing dependency issue although the error message is a little cryptic. I tried to import the solution you posted manually and got the following. You may want to try importing manually to see if you get a similar error.

![image](https://user-images.githubusercontent.com/42348035/197575256-d0d23f16-8bec-471b-8227-a7dd0f60e3bd.png)

**Comment by Ballzer0** [comment]
> @Ballzer0 this looks like a missing dependency issue although the error message is a little cryptic. I tried to import the solution you posted manually and got the following. You may want to try importing manually to see if you get a similar error.
> 
> ![image](https://user-images.githubusercontent.com/42348035/197575256-d0d23f16-8bec-471b-8227-a7dd0f60e3bd.png)

yeah.. that one was a bad example. im currently exporting a solution without dependency issues.

**Comment by mikefactorial** [comment]
Hmm. @Ballzer0 that solution won't install either and looks odd when I unzip it.

![image](https://user-images.githubusercontent.com/42348035/197591452-b73a03cf-3873-4833-bcb9-8a4aaf334507.png)

Wouldn't expect to see the tables in folders like that in the root of the solution zip...Not sure how that would happen. Normal solution zip looks like like this.

![image](https://user-images.githubusercontent.com/42348035/197591729-c1d067dd-7135-4e8d-b148-439def8f3b99.png)

**Comment by Ballzer0** [comment]
I noticed that in an earlier update , you guys changed the folder
structure, could that have something to do with it?

**Comment by mikefactorial** [comment]
@Ballerz0 We did change the folder structure twice since the last time you upgraded based on the structure that the power platform build tools and pac commands predetermined for us, where we had our own structure previously. The upgrades were supposed to be seamless from one version to another since we tried to fix them up on the fly during the build but this may be a scenario we didn't account for in the pipelines. Exporting the solution again should resolve it but the import may be too out date to fix it up now.

**Comment by mikefactorial** [comment]
If you can supply a screenshot of the repo structure from the last export. We can look into making sure that the build is handling the specific scenario.

**Comment by Ballzer0** [comment]
I can't really export solutions, since we just reset our development
environments in preparation for our next sprint.

Essentially all our solutions are stuck in the repo now, with no way to get
em installed on our dev environments 😅

**Comment by Ballzer0** [comment]
> If you can supply a screenshot of the repo structure from the last export. We can look into making sure that the build is handling the specific scenario.

I'll have to do that tomorrow, I've gone home for the day, and don't have the proper credentials on me

**Comment by mikefactorial** [comment]
Okay, we can work through it together :). 

If there haven't been any changes to source control since the last build then there will be unmanaged solutions on the last build artifacts in Azure Devops that could be imported manually, but obviously, that's not the ideal solution when source control is supposed to be the source of truth. 

Talk to you tomorrow.

**Comment by Ballzer0** [comment]
here is a picture of our current folder structure.
![image](https://user-images.githubusercontent.com/28560729/197773663-a26ffad4-0d7d-4010-a43f-b89113f822fe.png)

there is about 20 different solutions inside of here. So manually importing and republishing solutions based on earlier artifacts woul be a LOT of work.
![image](https://user-images.githubusercontent.com/28560729/197773893-51b1f427-cc9b-4d12-9a0c-4e9e49b2f15a.png)

**Comment by mikefactorial** [comment]
@Ballzer0 pardon the delay on this issue. Unfortunately, we've dug into it quite a bit and it's not something we are planning to address. The change in the platform that caused this issue would require us to invest a significant amount of time to create a workaround to "fix up" the solution and isn't something we want to add to the pipelines or have time to invest in. I'm going to close this out for now. If you have any questions specifically about how you can implement a "fix up" solution of your own, feel free to reach out in a separate issue.

@RajeevPentyala for visibility.
