### ISSUE TITLE
[CoE Starter Kit - QUESTION] Timing of our potential BYODL upgrade

### ISSUE THREAD

**Issue by MelissaM13** [microsoft/coe-starter-kit#4033]
### What is your question?

It appears that the CoE Starter Kit – Feature of BYODL will be part of the December 2022 Kit release.  We are exploring the Data Lake option. We upgrade our version of the Kit every 3 months. Our next upgrade is next month - November and then in February 2023.

Question: Next month when we upgrade, we will continue with Dataverse, obviously. If the BYODL releases in December, do we have to upgrade again in December or can we wait until February and upgrade to the BYODL then (if we decide to pursue this option)?

**Comment by manuelap-msft** [comment]
Hello,

December is our target date indeed, depending on how testing goes! We will aim to offer customers a smooth transition and migration from Dataverse/current sync flows to BYODL so you'll be able to upgrade in February and set the correct flags - it will be an environment variable to say "my data is now in BYODL" that then routes all the flows correctly.

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Wonderful! If your time permits, or if you want an early sneak peak, we have the Power BI dashboard with BYODL in private preview right now. As it's a private preview and we're still testing parts of it, we recommend customers use this side by side with their regular CoE installation. If you're interested, you can sign up here https://aka.ms/coebyodlpreview - even if you're not actively participating in the private preview (e.g. setting it up and testing it), this would give you better knowledge of what's coming and how we're implementing the BYODL integration!

**Comment by JJDE** [comment]
> Wonderful! If your time permits, or if you want an early sneak peak, we have the Power BI dashboard with BYODL in private preview right now. As it's a private preview and we're still testing parts of it, we recommend customers use this side by side with their regular CoE installation. If you're interested, you can sign up here https://aka.ms/coebyodlpreview - even if you're not actively participating in the private preview (e.g. setting it up and testing it), this would give you better knowledge of what's coming and how we're implementing the BYODL integration!

Hi  @manuelap-msft  Just wondering if BYODL would eliminate the need for having PIM turned of for the flow owners? This is a blocker in current customer deployment as there PIM is mandatory
