### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log Authentication issue

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#4035]
### Describe the issue

Have deployed audit log components and trying to turn on the [Child] Admin | Sync Logs; however, keep getting an error saying, "There's a problem with the flow's trigger" Have made the configuration with the customer connector successfully. 

<img width="572" alt="Screenshot 2022-10-14 102455" src="https://user-images.githubusercontent.com/100535041/197813029-a1c01f16-aeae-4a02-beaa-9b3646abde6d.png">
<img width="790" alt="Screenshot 2022-10-14 102514" src="https://user-images.githubusercontent.com/100535041/197813072-15d4d66d-57ad-4903-9e1b-9cfa9a3d4fb3.png">

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs.

**Comment by iamjina** [comment]
For Microsoft Dataverse Connector, I am not seeing "Use this connection" but has "Provided by run-only user." 

<img width="376" alt="image" src="https://user-images.githubusercontent.com/100535041/197815184-7b1c0705-a572-4a53-9626-65fe8054e6c3.png">

**Comment by iamjina** [comment]
Hey Jenefer, 

<img width="731" alt="image" src="https://user-images.githubusercontent.com/100535041/197871724-a178f513-204f-4f23-8759-fee498b31401.png">
I've recreated the connection; however, it's still showing me an error... Would this problem be related to Dataverse connection?

**Comment by Jenefer-Monroe** [comment]
Yes I'm afraid you've hit some bug. A few people have seen this recently. Some were able to just turn on the flow anyway but that seems to not be the case for you unfortunately. 
You can try seeing if you have an unmanaged layer on the flow, remove it and try again. 
But if that doesnt work I'm afraid I'm out of ideas, and you will need to contact product support.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
