### ISSUE TITLE
[CoE Starter Kit - License] What Maker license is required for Compliance/Inactivity/Orphaned functionality

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#4037]
### What is your question?

@Jenefer-Monroe @manuelap-msft

Going a bit deeper into Compliance, Inactivity, Orphaned functionality in the CoE Kit, can you tell me which of those areas would need a premium license by the Makers?

Compliance: Premium due to Canvas app for business justification etc
Inactivity: ?
Orphaned:? (adaptive cards needs...?)

I'm trying to figure out which of those functions can be turned on right now, as our makers only have the E5 entitlement for standard licensing.

### What solution are you experiencing the issue with?

Governance

**Comment by Jenefer-Monroe** [comment]
Hello. We have a documentation bug on the backlog for this request, please see https://github.com/microsoft/coe-starter-kit/issues/3927

I can give you an initial thought though while you await that. 
The only Maker facing features that don't require Per-User or Per-App licensing are 

- [Set up inactivity notifications (unused apps and flows)](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components#set-up-inactivity-notifications-unused-apps-and-flows) - The maker can use the approval email format to approve or reject deletion
- [Set up clean-up for orphaned objects](https://learn.microsoft.com/power-platform/guidance/coe/setup-orphan-components) - The manager can use the teams adaptive card to respond to the request to clean up the orphaned objects.

**Comment by peteredc** [comment]
Excellent! That's critical to knowing what to turn on.

So it looks like we could fully enable the inactivity, and orphan functionality but no the compliance.

Would you mind if I circle back to you on the compliance with ideas of how we might be able to replace the Maker Canvas apps with a form or maybe just an email? Unfortunately we are not in a position to license the whole Enterprise, but really need compliance in default environment.  So I'm going to take a crack at what I can turn on for compliance, and maybe find a different way to get feedback from Makers other than the Canvas app.

**Comment by manuelap-msft** [comment]
It's currently not on our roadmap to change the compliance flow in a way that wouldn't require premium licenses - we recommend that if your makers do not have a Per User license, to use Per App passes or pay as you go for the app.

However, if this doesn't meet your needs please remember that the solution is called a *starter* kit for a reason - many customers to customize and extend the processes in the kit to meet their needs, be it to overcome license limitations or to make a process fit better to their organization. Here's our guide on extending the kit: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
