### ISSUE TITLE
Azure DevOps Custom Connector error

### ISSUE THREAD

**Issue by elazarheefner** [microsoft/coe-starter-kit#4042]
### Describe the issue

Hello,

We are receiving the same error at #3672 after upgrading to the latest build. I recreated the custom connector and we still have the issue.

Thanks.

![image](https://user-images.githubusercontent.com/111084845/198035417-1b4de2e1-9a29-41
[CustomConnectorError.docx](https://github.com/microsoft/coe-starter-kit/files/9869755/CustomConnectorError.docx)
db-aa1a-3f797dd02882.png)

![image](https://user-images.githubusercontent.com/111084845/198035434-03b74f09-802e-4537-acaa-38ee707cbe43.png)

### Expected Behavior

Please find the attached screenshots.

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

August Build

### Steps To Reproduce

Open ALM Accelerator for Power Platform.
[CustomConnectorError.docx](https://github.com/microsoft/coe-starter-kit/files/9869751/CustomConnectorError.docx)

### Anything else?

Please see screenshots attached.

**Comment by mikefactorial** [comment]
@elazarheefner when you say you "recreated the connector". You mean you deleted the existing connections and recreated those? Have you tried deleting the existing connections and waiting for the prompt from the app to create a new connection? Sometimes you need to refresh Ctrl+F5 the app a few times in order for it to prompt to create a new connection. Obviously, not ideal but I've seen that in the past in our testing of upgrades.

**Comment by elazarheefner** [comment]
@mikefactorial I couldnt delete the connector as it wouldn't allow it because of the solution dependency (please screenshot below). I ended up reimporting the entire solution package (CenterofExcellenceALMAccelerator_1.0.20220726.1_managed). The error has persistent for over two week, fyi.

![image](https://user-images.githubusercontent.com/111084845/198148662-0782c1f2-61de-4a8a-9b09-4570aefb86d4.png)

**Comment by elazarheefner** [comment]
I have also created a new connection to DevOps, please see below:
![image](https://user-images.githubusercontent.com/111084845/198149307-9dae7799-f66e-4f3a-b67f-a0397dff67cf.png)

**Comment by mikefactorial** [comment]
Just to be clear on the terminology. You shouldn't be deleting the CUSTOM CONNECTOR. Instead the CONNECTIONS associated with the CUSTOM CONNECTOR. Have you tried deleting all existing CONNECTIONS?

**Comment by elazarheefner** [comment]
Yes, followed by creating a new connection per my screenshot above.

Thank you.

**Comment by mikefactorial** [comment]
A connection is an instance of the connector that includes your credentials to authenticate. While the connector is simply the definition of how a connection communicates with the endpoint. It can be confusing.

**Comment by elazarheefner** [comment]
Thank you for the explanation.

Elazar Heefner
Senior Technical Consultant - Systems Integration Microsoft

Mazars USA LLP
501 Office Center Drive, Ft Washington, PA 19034 - USA
Tel: 917-903-5568
***@***.******@***.***>
www.mazarsusa.com/microsoft<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.mazarsusa.com%2Fmicrosoft&data=04%7C01%7CElazar.Heefner%40mazarsusa.com%7C56d2caf142444ec011c508d8b18a5772%7C8de9cf77347d4209b268e723cae1f46b%7C1%7C0%7C637454555017218984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=l2yokmX%2FYyFff7npd714F3gkF00PbCOqzPp5%2BEAmzwc%3D&reserved=0>
***@***.***

**Comment by elazarheefner** [comment]
Thank you, deleted all of the old connections (not just create new) and it resolved the issue!
