### ISSUE TITLE
[CoE Starter Kit - BUG] Orphaned cleanup flow is incorrectly identifying orphaned flows

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#4048]
### Describe the issue

I have assigned the owner of these flows to our service account last week, I double checked, all of these flows listed here that are part of the CoE kit are assigned to the service account.  Paige, the previous tech before me implemented the CoE kit early January as herself and not under a service account (which is why she is shown as the owner)

I am unable to remove her as owner and already had a microsoft support ticket where they explained there is nothing they can do there.

My service account, however, is a co-owner on all these flows.  The Orphan cleanup flow is detecting all of these as problems.  I tried to go through the app flow canvas app to re-assign perm's to the service account but it does not let me.

Please assist.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

October 2022

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

**Comment by JayCecchine** [comment]
to add, I did exclude my CoE environment from compliance in power admin, these flows are almost all from my CoE env

![image](https://user-images.githubusercontent.com/24686498/198117672-381db24b-1eea-4d77-9c5d-49758e423ca9.png)

**Comment by Jenefer-Monroe** [comment]
We use the Derived Owner concept for this. You can go update the Derived Owner column to your desired owner, and then unmark them as orphaned. The same thing can be done via the Set Flow Permissions app but it would have to be done one by one. 

Hope that helps.

**Comment by JayCecchine** [comment]
Would you kindly show me how to do that?  I used the set flow permissions app and got an error message.  Set app permissions app worked beautifully, just not the flow one.  I get an error when changing Paiges (disabled user now) flows.

**Comment by JayCecchine** [comment]
Here is an example flow that our service account is now a co-owner on (previous owner was paige, but we cannot remove here.  I made a microsoft support request for this and they said its impossible to remove her)

![image](https://user-images.githubusercontent.com/24686498/198392923-1826f0c3-05d9-43e6-9e19-9441fb2f9855.png)

It opens the flow settings and as you can see here, we are unable to remove her as the owner.

![image](https://user-images.githubusercontent.com/24686498/198393013-6eb6b1b5-aec7-4e0a-9865-e2b56f5ab9bd.png)

**Comment by Jenefer-Monroe** [comment]
So if you click on the flow name it should bring you to a page where you can add the new owner. Please let me know if I've misunderstood or if this helps. 

- ![image](https://user-images.githubusercontent.com/89584709/198402230-3fdec164-16dd-451a-88c7-0c658f9234cf.png)
- 
- ![image](https://user-images.githubusercontent.com/89584709/198402311-ef73d927-6f59-4158-b4c4-73f4286c5b63.png)
- 
- ![image](https://user-images.githubusercontent.com/89584709/198402390-16583022-b10a-4d90-bda2-b7d4caed96ca.png)
- 
-  ![image](https://user-images.githubusercontent.com/89584709/198402447-84e4c7f7-39c0-4233-8493-c64b980189e0.png)

**Comment by JayCecchine** [comment]
Hi Jenefer, 

I did try that yesterday, this is the error when hitting assign as owner.

![image](https://user-images.githubusercontent.com/24686498/198404873-5a85b0e4-006e-493b-8b72-666c332d46e0.png)


It times out there and then goes to this screen saying the following, but not changing the owner

![image](https://user-images.githubusercontent.com/24686498/198404922-84e7ba47-41f0-48c7-ae13-03e5bcd507aa.png)

**Comment by Jenefer-Monroe** [comment]
I dont see an error. This message is always there and just letting you know we cant do things like add editors for a solution aware flow
![image](https://user-images.githubusercontent.com/89584709/198409944-2e21f885-ac8a-4f13-b27a-980be18aa39e.png)


If you select the user and hit Assign as Owner, what error do you get? 
![image](https://user-images.githubusercontent.com/89584709/198409871-ed96465d-28ea-4b85-a913-ff5c99a46bd5.png)

**Comment by JayCecchine** [comment]
So that is the "error"  I hit assign as owner, the button goes grey for 15 seconds, it exits that screen and goes to the second screenshot I showed "flows in solutions" screen and does not add the new owner.

I've tried multiple times with no success.

**Comment by Jenefer-Monroe** [comment]
Are you running in the context of a Power Platform Admin Role user?

**Comment by JayCecchine** [comment]
Yes.  I have all the proper permissions

**Comment by JayCecchine** [comment]
This is all I see for the latest run on that -

[image: image.png]

**Comment by Jenefer-Monroe** [comment]
You have to be logged in to GitHub to share images, they do not come through if you respond in email. Can you plesae log in to GitHub and share the images?

**Comment by JayCecchine** [comment]
![image](https://user-images.githubusercontent.com/24686498/198709675-1c67c98e-d939-4423-ac9f-2d4ad87eefef.png)

**Comment by JayCecchine** [comment]
![image](https://user-images.githubusercontent.com/24686498/198709744-80e7000c-16f5-414e-b65f-55c3a47d8425.png)

**Comment by Jenefer-Monroe** [comment]
ok you have to dive down into that switch statement and follow the path to this call. 
![image](https://user-images.githubusercontent.com/89584709/198672520-f08aa24f-f12e-4c47-844f-b6bdb27925dd.png)

**Comment by JayCecchine** [comment]
I hit assign owner, button greys out, it stays on screen for 2 minutes like this

![image](https://user-images.githubusercontent.com/24686498/199031021-1cdb66ca-68ae-4a4f-a88d-23f97a46e1df.png)

It then goes to this screen, has been on it for 5 minutes now... no new owner has been added

![image](https://user-images.githubusercontent.com/24686498/199031141-fcbf829a-111c-4cb7-981b-90b07e285d36.png)

Here is the flow run saying it was successful (it was not) and only took 35 seconds to run  I've expanded all sections, this is the only one with a switch "yes" or "no" statement.  There is no update flow owner here

![image](https://user-images.githubusercontent.com/24686498/199031522-a6e03d51-8198-4904-9cb7-77d9916ae50f.png)

**Comment by Jenefer-Monroe** [comment]
Do you have an unmanaged layer on this flow?

**Comment by JayCecchine** [comment]
Nope

![image](https://user-images.githubusercontent.com/24686498/199039274-dd6ce77a-f2ef-40da-93e2-7e7e0b2c182c.png)

**Comment by Jenefer-Monroe** [comment]
Can you please open teh run and show me how it flows down into that switch statement then?

**Comment by JayCecchine** [comment]
![image](https://user-images.githubusercontent.com/24686498/199076841-40837dea-47c8-46af-ae0e-b9c0da2b7d01.png)

**Comment by Jenefer-Monroe** [comment]
I need you to dive into this switch statement
![image](https://user-images.githubusercontent.com/89584709/199081391-d365d3a1-a673-43ef-93b4-0d4283065212.png)

And follow it all the way down

**Comment by JayCecchine** [comment]
![image](https://user-images.githubusercontent.com/24686498/199082716-a73eecfa-0183-443e-b471-36283c6432d4.png)

**Comment by Jenefer-Monroe** [comment]
I mean in your run, so that we can see where it broke

**Comment by JayCecchine** [comment]
all of the runs say they're successful, but they do not actually change the owner.  That is of the latest run

**Comment by Jenefer-Monroe** [comment]
That picture yuo shared here is the flow in edit mode, that is not useful
![image](https://user-images.githubusercontent.com/89584709/199098483-546589d1-95b9-4f34-84ae-782c90d8ca9a.png)

**Comment by Jenefer-Monroe** [comment]
What you need to share is a picture of the run like you were doing here: 
![image](https://user-images.githubusercontent.com/89584709/199098586-df280e20-4c3d-4de2-8502-d2a1fbe0803c.png)


But open the switch statement
![image](https://user-images.githubusercontent.com/89584709/199081391-d365d3a1-a673-43ef-93b4-0d4283065212.png)

and follow the path down to this call
![image](https://user-images.githubusercontent.com/89584709/198672520-f08aa24f-f12e-4c47-844f-b6bdb27925dd.png)

**Comment by JayCecchine** [comment]
![image](https://user-images.githubusercontent.com/24686498/199263416-9461e882-27c0-4fea-8373-b87421f2e9be.png)

**Comment by Jenefer-Monroe** [comment]
ok it looks like it worked. Is this for the flow where you saw it failing in the app? 
Do you have an unmanaged layer on the app perhaps preventing you from seeing the change? 
Who is listed as the owner if you go to the flow?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
