### ISSUE TITLE
Admin | Sync Audit Logs - Last child run always fails

### ISSUE THREAD

**Issue by rsch136** [microsoft/coe-starter-kit#405]
The last loop (no. 61) in the Sync Audit Logs flows always fails. The child flow fails with the following error:
Child flow fails: 
```
{
  "error": {
    "code": "AF20055",
    "message": "Start time and end time must both be specified (or both omitted) and must be less than or equal to 24 hours apart, with the start time prior to  end time and start time no more than 7 days in the past. StartTime:2021-05-14T20:04:50.2372975Z, EndTime:2021-05-17T08:04:50.2529240Z"
  }
}
```

I have left the start and end times default settings but I changed the time interval to 10 minutes (Child flow fails for other reasons if interval is too big).

Found the error: The step "generate timeSegments list" is limited to 60. Using my intervals I would need at least 423 time segments. Not having enough segments causes the last segment to be too big (larger than 24 hours) for the audit log.

**Would appreciate if docu could be updated to include hint to this additional modification needed if time interval is modified.**

**Comment by rsch136** [comment]
Found the error: The step "generate timeSegments list" is limited to 60. Using my intervals I would need at least 423 time segments. Not having enough segments causes the last segment to be too big (larger than 24 hours) for the audit log.

Would appreciate if docu could be updated to include hint to this additional modification needed if time interval is modified.

**Comment by JeneferM-MSFT** [comment]
We have put this documentation update on the backlog. 
Thanks for using CoE
