### ISSUE TITLE
[CoE Starter Kit - BUG] cannot turn on Helper flows

### ISSUE THREAD

**Issue by AkunerTulachan** [microsoft/coe-starter-kit#4052]
### Describe the issue

cannot turn on helper flows.

### Expected Behavior

Having the error below while turning on helper flows. Tried with run-only properties, on Dataverse I do not see my connection as described in https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#set-flow-run-only-users-properties

![image](https://user-images.githubusercontent.com/55730006/198183834-4f45bca0-59dd-429f-bfba-91f173e09c6d.png)

Request to XRM API failed with error: 'Message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id '9301f01a-cb40-ec11-8c62-00224829b4c1' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}". Code: 0x80060467 InnerError: '.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

all HELPER flows

### Steps To Reproduce

try to turn on the Helper flows.

**Comment by petepuu** [comment]
@AkunerTulachan you should be able to turn on the child flows even you do not see the Dataverse connection. Just try to turn on the child flow and then double check is the the run-only users configuration correct = all connections having connection of CoE service account

**Comment by AkunerTulachan** [comment]
I am unable to do so. I am now getting the error below, any advice? I tried to look for an environment variable in the solution, but it does not exist. Perhaps, I should try adding one?

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_GraphURLEnvironmentVariable'."}}".

**Comment by manuelap-msft** [comment]
Hello,

you've missed to provide an environment variable for the 'admin_GraphURLEnvironmentVariable (Graph URL Environment Variable), which this flow uses. See: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values
![image](https://user-images.githubusercontent.com/55705669/198235227-12307b13-8b51-4d7c-9e20-857f991c9ea3.png)

Here's our FAQ on how to update environment variables after import:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables

Once you have updated the environment variable, you have to turn on the HELPER - ObjectOperations flow, and then you can turn on all the other HELPER flows.

**Comment by AkunerTulachan** [comment]
thank you. I was missing the value.
