### ISSUE TITLE
[CoE Starter Kit - BUG] New Environment not syncing to CoE dashboard

### ISSUE THREAD

**Issue by asriva58** [microsoft/coe-starter-kit#4055]
### Describe the issue

We are having issue with the Power Platform COE Starter Toolkit . When a new Environment is created in power platform , we are not able to see the new Environment created in Environments list in COE Dashboard under Environment .

### Expected Behavior

Whenever environment is created in Power Platform , the environment present should appear in the COE Starter Kit Dashboard

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

 1.89

### What app or flow are you having the issue with?

Admin- Sync Template V3

### Anything else?

Environment name : GIS PP COE Admin Test
https://oc-powerplatform-coe.crm.dynamics.com/main.aspx?settingsonly=true
App Name - Power Platform Admin

**Comment by manuelap-msft** [comment]
Hello,

new environments are inventoried on a daily basis (so not real time) by the **Admin - Sync Template v3** flow. The Power BI dashboard also does not refresh automatically when the inventory is refreshed, and you'll have to set up schedule refresh of the dashboard. 

Is it correct that you're on version 1.89 of Core components? If so, that's a very old version and we're unable to support this any longer. Please read our guidance for keeping your kit up to date here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup - we release a new version every month that contains bug fixes and new features, and we recommend upgrading every 3 months.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
