### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION per-flow license used for CoE Starter Kit inventory cloud flows 

### ISSUE THREAD

**Issue by miroslav-harlas** [microsoft/coe-starter-kit#4056]
### What is your question?

Hello,
We assigned per-flow license to some of the inventory cloud flows in the past, couple of months ago.
We performed CoE Upgrade to October 2022 version.
We realized couple of days after the upgrade, that per-flow license is not anymore assigned to some of the cloud flows, while some others are licensed with per-flow license still. To be more concrete, the cloud flow *HELPER - Maker Check* lost assignment to per-flow license after the upgrade, but other ones, for example *Admin | Sync Template v3 (Flows)* has it assigned properly still.

My questions are as follows:
1. Is it expected that some of the cloud flows can lose per-flow license assignment? And if yes, differs this experience per each release, and is this being documented anywhere? 
2. How can we easily review, which cloud flows have per-flow license assigned? Is there any kind of report anywhere in CoE starter Kit itself, or is there any capability built-in OOB in the platform, which we can use to list all cloud flows with per-flow license assignment?

FYI: I used this option: 
https://learn.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#view-detailed-power-platform-request-usage-information-in-the-power-platform-admin-center-preview
to identify, which cloud flows had per-flow licence assigned prior upgrade. But I do not consider this as easy enough, as it requires additional steps on the top of exported CSV file to get a distinct list of display names of the cloud flows.

I resolved the issue on our side ourselves, but I'm seeking guidance on how we can notice if this kind of issue occurs and how we can resolve it in the most effective way next time.

Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2022

### What app or flow are you having the issue with?

HELPER - Maker Check

**Comment by manuelap-msft** [comment]
Hello,

can you check if the flows that still had the Per Flow license assigned after upgrade have an unmanaged layer on them?

I will check if I can get some Per Flow passes for our development tenant so we can test this behaviour with - I have a suspicion that adding a Per Flow license to a flow introduces an unmanaged layer, and that if you remove the unmanaged layer prior to an upgrade it may also remove the Per Flow assignment. I'll try and check this in my development tenant and will get back to you on what the expected behaviour is. Once we understand the expected behaviour, we can also provide further feedback to our Engineering team on the desired behaviour.

Thank you for raising this,
Manuela

**Comment by miroslav-harlas** [comment]
Hello,
I can confirm that per-flow license assignment is NOT creating unmanaged layer.

I can also recall that I had unmanaged layer on Admin | sync Templates v3 (Flows) and that I intentionally removed that before upgrade, and per-flow license assignment is correct still, after removal of unmanaged layer and after upgrade.

![image](https://user-images.githubusercontent.com/16306406/198345306-d5814566-69d2-4e06-b552-43edea2e97d9.png)

**Comment by miroslav-harlas** [comment]
Isn't it possible that - for example - unwanted accidental "turn off" and then "turn on" of the cloud flow inside of the solution can cause the lost of per-flow license assignment?

I have no more per-flow licenses, I cannot test on other flows/solutions, and I do not want to test with current CoE setup, inventory is running now :)

Thank you in advance for any ideas.

Miroslav

**Comment by miroslav-harlas** [comment]
Additional question is if CoE Starter Kit contains details about per-flow license assignment in the inventory?
I cannot see anything like this in Power BI Dashboard nor in *Power Platform Admin View* app.

If CoE Starter Kit contains no data and cannot provide overview easily, is there any other way how to easily get list of cloud flows from specific environment with per-flow license assigned?

Thank you in advance for clarification of this detail.

Miroslav

**Comment by miroslav-harlas** [comment]
Just an update, we have updated CoE starter Kit recently from October 2022 to December 2022 in our PROD. Assignment of per-flow licenses was not impacted this time during this upgrade.

Just a reminder of my latest unanswered question from October 2022:
Does CoE Starter Kit contain details about per-flow license assignment in the inventory? If CoE Starter Kit contains no data and cannot provide overview easily, is there any other way how to easily get list of cloud flows from specific environment with per-flow license assigned? Thank you in advance for clarification of this detail.

Miroslav

**Comment by Jenefer-Monroe** [comment]
Hello. Here is the licensing update we will be putting into our documentation for the Feb release. 

**Which license should I assign to the user that's running the CoE Starter Kit flows?**

The pre-requisite for installing the CoE Starter Kit is that the user installing it has a Power Automate Per User license, or for flows to be covered with a Per Flow license - often a combination of these licenses is required to successfully run the CoE Starter Kit. The combination depends on factors like how many resources (apps, flows, environments) you have in your tenant, how many makers you have, and how often new resources are created and modified. Different Power Automate license types will have different API Limits and enforcements - if your license type is not sufficient, the flow may get throttled or run for a long time. Use the following guide to identify which license to pick.

1. Understand the [Power Automate request limits](https://review.learn.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations).
2. Start by assign Power Automate Per user license and turn on all the required flows. Monitor the flows with **_CLEANUP, Sync Template (Flows)_** and **_Sync Template (Apps)_** in the name - these often consume a high number of API requests. You can use [action analytics](https://powerautomate.microsoft.com/blog/introduction-action-usage-analytics-in-power-automate/) to monitor the API requests of these flows.
3. If the flow runs too many actions, [change the flow owner](https://review.learn.microsoft.com/en-us/power-automate/change-cloud-flow-owner) to a different account with a Power Automate Per User license. This will load balance the API requests
4. If the flow continues to run too many actions, assign a [Per Flow](https://review.learn.microsoft.com/en-us/power-platform/admin/power-automate-licensing/types#standalone-plans) plan to this flow. This will reserve capacity and API requests for the flow.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
