### ISSUE TITLE
Can't upgrade to latest version [CoE Starter Kit - BUG] Upgrade issue from 3.13

### ISSUE THREAD

**Issue by shaik-shahansha** [microsoft/coe-starter-kit#4061]
### Describe the issue

We have been trying to upgrade CoE toolkit to the latest version. I have 2 versions of CoE core components in our environment. one is 3.38 and other one is 3.13 with _upgrade package name (older version with _upgrade). We have tried most of the solutions given in forums but with no luck. 
![image](https://user-images.githubusercontent.com/73993289/198374835-c04207b1-aa2e-48ce-acb5-9ece7ced813b.png)
We tried the classic view and tried upgrade, update, stage and also overwrite options but none worked. 
![image](https://user-images.githubusercontent.com/73993289/198375133-b28ea955-7d93-42fc-938e-a6fd976aae94.png)
1. When we try to upgrade we get _upgrade package already exists.
2.  When we try to delete the _upgrade package it won't delete and gives dependency errors. We can't resolve the dependencies by any way.
![image](https://user-images.githubusercontent.com/73993289/198375704-0202d041-56fb-4ed7-ae0e-1916522ab3d7.png)
3. We tried to delete our latest 3.38 which doesn't have any dependency but still this also won't delete saying AppRevisionNotFound error

Please help to resolve and upgrade to latest version.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

Corecomponents

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with or without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help you get started with migrating the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Others have overcome it with a classic overwrite upgrade, ill paste how to do those below. 

Sorry we cannot be of more assistance here.

**Comment by Jenefer-Monroe** [comment]
Classic overwrite upgrade
### How to do an overwrite upgrade in the classic UX:
 
Solution > Switch to Classic (note this can take some time, may have to try twice) 
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)
 
Click Import (fourth from the left) 
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)
 
Choose File (the solution file you were trying to install) > Next > Next > Overwrite customizations (note this is not the default) > Import 
![image](https://user-images.githubusercontent.com/62659043/129362133-f02b9455-28bc-4cc3-80f5-e75a797bcc60.png)
![image](https://user-images.githubusercontent.com/62659043/129362227-b6cac9e8-64c3-4370-905f-442444c5f882.png)

**Comment by shaik-shahansha** [comment]
We have tried all the options (upgrade, update, stage - Overwrite) in classic view. but nothing helps same errors.

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist further here. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with or without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help you get started with migrating the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

Sorry we cannot be of more assistance here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
