### ISSUE TITLE
[CoE Starter Kit - BUG] Failed to refresh Power BI Starter Kit report 

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#4063]
### Describe the issue

I have installed CoE Starter kit in two different environment (To Maintain the QA and Prod) and also published the Power BI report in a single workspace for both QA & Prod

Now I have recently updated the QA Env with latest version after that previous published report failed to refresh with following error 

Something went wrong

There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.

Processing error: Cds: Request failed: The remote server returned an error: (502) Bad Gateway. (Bad Gateway)
Cluster URI: WABI-NORTH-EUROPE-C-PRIMARY-redirect.analysis.windows.net
Activity ID: 65860cd4-4678-494a-acd6-8be2c5f4a2b5
Request ID: d29a1441-6901-45cd-8cab-5ae6011424f3
Time: 2022-10-27 18:41:17Z

### Expected Behavior

Both published reports should work simultaneously because dataset is different for both report

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53 latest one 

### What app or flow are you having the issue with?

Production_CoEDashboard_October2022.pbit

### Steps To Reproduce

Published two different version in same workspace 

Old Version
3.39
New Version
3.53

**Comment by manuelap-msft** [comment]
Hello,

at what step are you getting that error message? Can you share a screenshot or the text that you get when you hit the Refresh button in the dashboard? Maybe it's just one table that's not loading.

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
