### ISSUE TITLE
[CoE Starter Kit - QUESTION] What is SharepointFormApp displayed in power platform admin view App Type?

### ISSUE THREAD

**Issue by jbst2018** [microsoft/coe-starter-kit#4065]
### What is your question?

Hi team.

What does the app type 「SharepointFormApp 」 mean?
I think there are two types of apps: canvas apps and model-driven apps.
However Power Platform Admin View shows SharepointFormApp.
![image](https://user-images.githubusercontent.com/109139057/198512705-824723c0-0626-4e06-855e-047b77af0dc6.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by manuelap-msft** [comment]
These are apps created using the SharePoint form integration: 
https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/customize-list-form

**Comment by jbst2018** [comment]
Thank you very much.
