### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to enable makers to use Approvals

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#4068]
### What is your question?

Turned on following flows:

Admin | Inactivity notifications v2 (Check Approval)
Admin | Inactivity notifications v2 (Clean Up and Delete)
Admin | Inactivity notifications v2 (Start Approval for Apps)
Admin | Inactivity notifications v2 (Start Approval for Flows)

We started getting dozens of emails in regard to the following -

![image](https://user-images.githubusercontent.com/24686498/198643671-953fd821-69d8-4c1b-b50a-43fcd04e6abf.png)

We are getting these in regard to flows, apps, for manager to approve a selected file etc.

I'm not sure what I'm supposed to do to resolve the error.  What permissions are the makers needing exactly?

Also, it is still sending emails out even though I stopped the flows 20 minutes ago.  Please advise how to stop them

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Oct 2022

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Flows)

**Comment by Jenefer-Monroe** [comment]
Turning a flow off does not end its runs that are in progress, you would need to cancel the run to stop it
![image](https://user-images.githubusercontent.com/89584709/198659777-b76df976-aaed-4c5f-a99a-6f0c8fafbb74.png)

**Comment by Jenefer-Monroe** [comment]
There is a security group for environments called Approvals User, and users should be auto-added to it when you assign them an approval. If that doesn't happen it could be due to a few issues listed here [Assign approvals to any user in your tenant](https://learn.microsoft.com/power-automate/get-started-approvals#assign-approvals-to-any-user-in-your-tenant). 

A work around would be to add your Maker group to the security role, please let me know if that workaround helps and if so I'll add to documentation.

**Comment by JayCecchine** [comment]
That is the other issue, I don't believe all makers were being
automatically added to the maker group properly.

Do we have a method to pull out all makers out via powershell, so I can add
them to the makers group with a for loop or something.

**Comment by JayCecchine** [comment]
We have a few hundred environments... is there a way to easily add the
maker group to that security role for all environments?

**Comment by Jenefer-Monroe** [comment]
For this: 
> A work around would be to add your Maker group to the security role, please let me know if that workaround helps and if so I'll add to documentation.

That only needs to happen in your CoE envt

**Comment by Jenefer-Monroe** [comment]
Makers are added to the Maker group via the **_Admin | Add Maker to Group_** flow. Do you have that turned on? And if so, do you have failures? It's a very simple flow so if it works at all it should always work.

**Comment by JayCecchine** [comment]
Ah ok, understood.

**Comment by JayCecchine** [comment]
I am not seeing groups come up when trying to add to the approvals security role, is this something I have to powershell?

![image](https://user-images.githubusercontent.com/24686498/198709591-8a320a62-0615-4413-86d1-3a28d11c1c83.png)

**Comment by Jenefer-Monroe** [comment]
Hmm I'm not able to do it through that UX either, must be a product bug in play. You can add them to a security role by sharing an app with them though. 

![image](https://user-images.githubusercontent.com/89584709/198745686-8e79a9ee-8c59-4514-b03a-97af5b923cb5.png)

**Comment by JayCecchine** [comment]
Sorry, which app specifically am I sharing to them here?

**Comment by Jenefer-Monroe** [comment]
I'm just trying to help you find a way to assign the SR to the group. The UX in sharing an app does it. If you create a fake app and share with them, you casn then chose in this dropdown, the approval SR
![image](https://user-images.githubusercontent.com/89584709/199038218-e90bb8f9-4a82-4f39-b8ff-327d39eb5b15.png)

**Comment by Jenefer-Monroe** [comment]
If you dont send then an invite, uncheck that box, then you can just delete the fake app after you get it shared with the SR

**Comment by JayCecchine** [comment]
ok, that seemed to have fixed it.  Thank you Jenefer!  you can close this out

**Comment by Jenefer-Monroe** [comment]
Glad you were able to resolve! I'll close this out.
