### ISSUE TITLE
Get managed solution zip path

### ISSUE THREAD

**Issue by rsantos00** [microsoft/coe-starter-kit#4074]
### Describe the issue

After committing, I tried to deploy to Test and got an error in the "Get managed solution zip path" task.

Error description:
Starting: Get managed solution zip path
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.210.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\774329f9-a992-4d79-bee3-ef97ae0edad1.ps1'"
TriggerSolutionUpgrade : The term 'TriggerSolutionUpgrade' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\a\_temp\774329f9-a992-4d79-bee3-ef97ae0edad1.ps1:5 char:67
+ … -zip-path "D:\a\1/drop/" "Rui_AppA_DeptA" "$(TriggerSolutionUpgrade)"
+                                                ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (TriggerSolutionUpgrade:String) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : CommandNotFoundException
##[error]PowerShell exited with code '1'.
Finishing: Get managed solution zip path

### Expected Behavior

Normal deploy

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

November Release

### Steps To Reproduce

1 Create solution
2 Create a simple canvas app
3 Commit
4) Deploy to test

**Comment by rsantos00** [comment]
After a deeper analysis, this situation happens when we skipped the Preparation steps/configuration deployment settings.

**Comment by mikefactorial** [comment]
@rsantos00 I wasn't able to duplicate this in the latest version of the pipelines. Closing this out for now.
