### ISSUE TITLE
[CoE Starter Kit - Feature]: Solution Metadata for Governance and Nurture

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4080]
### Is your feature request related to a problem? Please describe.

To support further setup wizards for Governance and Nurture components, the Solution Metadata flow would need to be extended to also get meta data for Governance and Nurture components. 

### Describe the solution you'd like

Solution Metadata to cover Governance/Nurture as well

**Comment by Jenefer-Monroe** [comment]
Believe I have this ready. To test with Manuela.
