### ISSUE TITLE
[Power Platform communication site template] ISSUE TITLE

### ISSUE THREAD

**Issue by castilld5797** [microsoft/coe-starter-kit#4082]
### Describe your bug, question or feature ask.

Error running the script. Please advise. 
![image](https://user-images.githubusercontent.com/8749850/199065464-d24b7f6f-c39e-4cd2-814e-1b1ae2a8ebdf.png)

**Comment by castilld5797** [comment]
additional troubleshooting shows the specific command that seems to be having an issue: 
![image](https://user-images.githubusercontent.com/8749850/199066663-d8e4126b-76a5-4357-a4f5-94535e7a7161.png)

**Comment by Laskewitz** [comment]
Hi @castilld5797 - 

Thanks for reporting this issue. Can you try and run this with PowerShell 7? If you haven't installed it, you can do it via [this link](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2). I'm seeing other people with the same issue, and they say that using PowerShell 7 fixes it.

Let me know if this works. If it does, I'll update the docs accordingly. 

Kind regards,
Daniel

**Comment by castilld5797** [comment]
Daniel,
              I installed the 64 bit MSI of Powershell 7 and it worked.

***@***.***

Regards,

David Castillo
Associate Director | Information Technology
Collaboration Services

Office +1 609 419-6646
Mobile +1 908 227-0093
***@***.***

**Comment by Laskewitz** [comment]
Thanks for the confirmation! Enjoy the template!
