### ISSUE TITLE
[ALM Accelerator - BUG]: Flow issue after deployment

### ISSUE THREAD

**Issue by thetla** [microsoft/coe-starter-kit#4090]
### Describe the issue

Hi,

I am not sure if it's possible but in some environments, we should really be able to turn off some flows, for example in the test environment. If we do not activate the flow in configure deployment settings, it's still on when we deploy to for example test/prod even if we turned the activation off. It relates to both first and subsequent deployments. 

Br Terje Hetland 
PowerPlatform Center For Enablement Team Equinor

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

 CoEStarterKit-October2022 HF1

**Comment by mikefactorial** [comment]
Thanks for reporting this @thetla will look into a fix.
