### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Set Flow Permission APP

### ISSUE THREAD

**Issue by jbst2018** [microsoft/coe-starter-kit#4095]
### What is your question?

Hi.team.

I have a question about Set Flow Permission APP.
Is it your understanding that you can also delete and set the owner of the flows included in the solution, but you cannot set anything else?
In other words, you can set a new owner,but cannot set a Viewer and Editor?

I can't speak English, so I'm sorry for the confusing question.
![image](https://user-images.githubusercontent.com/109139057/199387449-5a4deca0-b93d-4d26-b02c-1460c9f3fb60.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Set Flow Permission

**Comment by Jenefer-Monroe** [comment]
You can change the owner, thats the only thing you can do, correct.

**Comment by jbst2018** [comment]
Thank you very much.
