### ISSUE TITLE
[CoE Starter Kit - QUESTION] Follow-up question on discontinuing the Dataverse (Legacy) connector.

### ISSUE THREAD

**Issue by wnzn** [microsoft/coe-starter-kit#4099]
### What is your question?

This is a follow-up question to [Issue 3658](https://github.com/microsoft/coe-starter-kit/issues/3658).

From what I read there is no replacement for the query capability of the Dataverse (Legacy) connector. So, does this imply that new installations of the starter kit will not work after November 25th, 2022?

**Comment by manuelap-msft** [comment]
New installs of the kit, and existing installs will continue to work until the Dataverse connector has parity and can support querying multiple environments. 

Once the Dataverse connector supports querying multiple environments, we will change all our flows to no longer use the Dataverse (legacy) connector and customers will then have to upgrade to our latest version to continue using the kit as the Dataverse (legacy) connector will get deprecated once there is feature parity.

**Comment by wnzn** [comment]
Okay, all clear. Thanks!
