### ISSUE TITLE
What should be the value for "Maker Assessment SharePoint Library" value?

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#410]
Hello,

This is regarding the latest CoE Starter Kit - 2.1.6 version.

I have tried saving "CLEANUP - Admin | Sync Template v3 (Check Deleted)" flow as I am unable to activate the flow in the environment without saving it in the default solution.

However, it has thrown following error and ask for the "Maker Assessment SharePoint Library" variable value. - Can you please share what should be the value here? as it's not mentioned here it seems - https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components

Is it a Document library name? Or it's a library URL ?

Error : Flow save failed with code 'InvalidTemplate' and message 'The template validation failed: 'The value for the workflow parameter 'Maker Assessment SharePoint Library' at line '1' and column '2118' is not provided.'.'.

Thank you for your time in advance!

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Your CoE seems to be in a very weird state per this and the other issue you posted recently. 
This env var is part of Nurture solution and not Core. And this flow does not refer to it. 

From [Nurture Setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-nurture-components#import-the-solution)
![image](https://user-images.githubusercontent.com/62659043/118991389-eec70d00-b940-11eb-8f74-2411c62880b7.png)

You may benefit from starting a fresh install of the toolkit given the types of weird issues you are seeing. Or from hiring a partner to get you back into a good state. 

Depending on the features you are using you may need to manually port data into the new envt. Can you please tell me what features of the toolkit you use?

**Comment by DiptiC-InsightRun** [comment]
Hey Jenefer,

That's correct, this particular flow is not a part of Nurture component, however based on the error I see, I have assumed it might referring the Nurture component's environment variable as I see in the Nurture solution as follows:

![image](https://user-images.githubusercontent.com/13658386/119009887-918f8380-b961-11eb-9624-ae3b26ee88fb.png)

Therefore, I was looking for it's value, can you please help?

Also, I agree that this error as follows, should not occur as this flow does not refer it 

![image](https://user-images.githubusercontent.com/13658386/119010622-40cc5a80-b962-11eb-9f3a-3eaf24948da9.png)

However, We further require to check/identify/verify in our environment what could have possible gone wrong and in order to do so, we have to save the flow while we have deployed all the latest CoE components successfully in the same environment.

Best,
Dipti

**Comment by DiptiC-InsightRun** [comment]
Hmmm, sounds like "Maker Assessment SharePoint Site" == "Maker Assessment SharePoint Library" for the Nurture Component solution 1.51. I think I should proceed this variable with "SharePoint Site URL".

**Comment by JeneferM-MSFT** [comment]
I'm afraid I cannot scale to assist further here given how far off the normal track your situation seems to be with the apps in the default solution now. 
You may need to start a fresh install of the toolkit given the types of weird issues you are seeing. Or hire a partner to get you back into a good state.
Depending on the features you are using in the toolkit you may be able to manually port data into the new envt. Can you please tell me what features of the toolkit you use?

**Comment by JeneferM-MSFT** [comment]
Sounds from the other bug like you have resolved your issues. Thanks for using CoE
