### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to import/export solution from ALM Accelerator

### ISSUE THREAD

**Issue by raphaelcharreyron-bib** [microsoft/coe-starter-kit#4100]
### Describe the issue

Hello,
Since today, we are unable to import from GIT or to export to Git our solutions.
We have an error related to variables to be settable at queue time.
We have not changed anything in our setting.

![Screenshot 2022-11-02 111714](https://user-images.githubusercontent.com/69636538/199465589-c5e8b439-0de4-4e87-83d5-a12f72b2ce96.jpg)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

 1.0.20220517.1

### Steps To Reproduce

1. Run pipeline to export to Git

**Comment by raphaelcharreyron-bib** [comment]
Is this deployment has been relaunched?
https://devblogs.microsoft.com/devops/updates-to-azure-pipelines-runtime-variables-settings/

**Comment by raphaelcharreyron-bib** [comment]
Here is the guilty...
https://devblogs.microsoft.com/devops/updates-to-azure-pipelines-runtime-variables-settings/
We have removed the option and it work again...

**Comment by mikefactorial** [comment]
@raphaelcharreyron-bib looks like this got lost in the shuffle. Pardon the delayed response. Thanks for reporting back the solution. Closing this out.
