### ISSUE TITLE
[ALM Accelerator - BUG]: Setup new DevOps Project fails with `Project Wizard`

### ISSUE THREAD

**Issue by megel** [microsoft/coe-starter-kit#4105]
### Describe the issue

Creating a new project from model driven app fails with the `Project Wizard`.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/15800069/199588855-7da5ac10-e4d7-4474-a9d1-1aae88d441a3.png">

I tried to create a new project with:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/15800069/199588474-d1e11dc5-6af4-4865-a6c5-d66b30033b1f.png">

...and got as result these error messages:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/15800069/199587748-71993dde-5af5-4020-84de-244616069f42.png">

However, the access to the repos works:
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/15800069/199588325-bb7bb76d-bcfa-49e8-901e-ce11801a6e98.png">

### Expected Behavior

Project is created.

### What component are you experiencing the issue with?

ALM Accelerator for Power Platform Administration

### What solution version are you using?

November 2022

### Steps To Reproduce

1. Import AA4PP solution into a fresh environment **manually**
2. Setup AAD by using coe-cli
3. Setup Azure DevOps
4. Create new Project with model driven app by using the `Project Wizard`

### Anything else?

@mikefactorial @jenschristianschroder 
What is the expected setup procedure for AA4PP? 
Is it (1) using the `CoE CLI` to setup everything or (2) installing the solution and running afterwards a `Wizard` from Admin App to setup the Tenant AAD AppRegistration stuff?

**Comment by mikefactorial** [comment]
@megel this looks like it may be related to the Custom Connector authentication expiring after installing the latest solution. We're looking into fixing this experience with the product team but right now updating a solution appears to wipe out the existing security configuration on the custom connector.

Can you share a couple of things?

1. Is the ALM Accelerator App in a working state? Does it report any issues with connecting to Azure DevOps.
2. If not if you edit the custom connector can you share the following?
 - The list of available operations from the test screen
 - The list of policies on the definition screen

There's been some inconsistencies related to custom connectors import that we've seen recently but this would help us possibly determine the specific problem in your case.

**Comment by mikefactorial** [comment]
"What is the expected setup procedure for AA4PP?
Is it (1) using the CoE CLI to setup everything or (2) installing the solution and running afterwards a Wizard from Admin App to setup the Tenant AAD AppRegistration stuff?"

To answer this question. We're still somewhere in between. Our hope is to remove as much of the CoE CLI setup requirements as possible and move to using the Admin wizard post solution install for all of the setup and upgrade, but we don't have complete parity between the two right now and are working toward adding more functionality.

**Comment by mikefactorial** [comment]
@megel was on a call with a customer today who installed the November release as an Upgrade instead of an Update and had similar issues. We had seen similar behavior previously that the "Upgrade" gesture appears to corrupt the custom connector. You should be able to import the solution again using Update to fix the issue.

**Comment by megel** [comment]
@mikefactorial  no, I did **not Update / Upgrade** the solution. I installed the AA4PP solution into an empty environment. 

However, I have checked again today also the Project Creation Wizard and was able to move a little bit forward:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/15800069/199780451-5e1c63d0-3271-4a00-8366-7a50936bb796.png">

Unfortunately, I got this message:
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/15800069/199780257-c3a43249-4839-4d7f-811d-b54b40227e6b.png">

```
CustomAzureDevOps.CreateServiceEndpoint failed: {"$id":"1","innerException":null,"message":"Unable to find service connection type 'powerplatform-spn' using authentication scheme 'none'.","typeName":"Microsoft.VisualStudio.Services.ServiceEndpoints.WebApi.ServiceEndpointException, Microsoft.VisualStudio.Services.ServiceEndpoints.WebApi","typeKey":"ServiceEndpointException","errorCode":0,"eventId":3000}, Observed: btnWizardCreateServiceConnections.OnSelect, Source: btnWizardCreateServiceConnectio...
```

Seams working mostly....
<img width="542" alt="image" src="https://user-images.githubusercontent.com/15800069/199781220-1b54b0d2-2a33-4c08-a159-1f13a8734bd5.png">

Did not run a pipeline yet 😅

**Comment by mikefactorial** [comment]
@megel since this is a new environment can you verify the steps in this doc? 

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-preview

**Comment by megel** [comment]
@mikefactorial I guess I have skipped definitely the ADO extensions 😅...

<img width="1720" alt="image" src="https://user-images.githubusercontent.com/15800069/199786888-e35fa552-3318-465c-b76a-0ed342e11f59.png">

I was assuming the new Wizard check this.

**Comment by megel** [comment]
Uhh the AA4PP App seams to have a technical Redraw Issue - did you see this before?
<img width="895" alt="image" src="https://user-images.githubusercontent.com/15800069/199787428-f1aa6190-68b2-4e78-afa7-971ba6fec9dd.png">

**Comment by megel** [comment]
@mikefactorial I found the root cause of this problem:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/15800069/199788500-31dc2e09-55a1-4a7a-9193-91ac32a867b3.png">

Azure DevOps is caching the repositories after you have deleted a Project I guess a couple of minutes. (BTW Articact Feed approx. 30 days). And this causes the problem after re-creation of a project with the same name.

**Comment by megel** [comment]
@mikefactorial  finally it works:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/15800069/199789585-dea62959-dbbd-4026-be12-bcc099905e07.png">

----

Ok let me summarize and close the issue:

1) AAD App Registration must be created by using CoE CLI 
1) ADO Extensions must be installed manually or by using CoE CLI
1) ADO Project can be setup with AA4PP Admin App.
1) **Don't delete and recreate a project in ADO** ... wait some minutes / hours

----

The drawing issue happens also on other PowerApps - might be a Platform problem.

**Comment by mikefactorial** [comment]
@megel thanks so much for the details here. We're on our first steps toward a fully enabled click button setup process so stay tuned. We'll likely be automating a lot of these steps in the coming months. As always, your feedback is much appreciated!
