### ISSUE TITLE
[Power Platform communication site template] Deployment script failing

### ISSUE THREAD

**Issue by as-sbridegroom** [microsoft/coe-starter-kit#4106]
### Describe your bug, question or feature ask.

Running the script to deploy a Power Platform Hub and keep getting failures. All variables are set appropriately, site gets created (see it in SPO Admin Center briefly), then fails when applying the template with the attached error. I'm a global admin in the tenant and am defining the site owner as me. Not sure where the challenge is.

![image](https://user-images.githubusercontent.com/80282473/199593649-c5c16530-274e-4d6d-bc30-df22e2c8d3ea.png)

**Comment by Laskewitz** [comment]
Hi @as-sbridegroom -

Are you using VS Code to run this? Can you please try PowerShell ISE instead? It seems that VS Code PowerShell runs into multiple issues here. 

Thanks in advance, hope this fixes it. 

Kind regards,
Daniel

**Comment by Laskewitz** [comment]
Thanks for the quick response @as-sbridegroom. Can you try removing the redirect? Instructions can be found [here](https://learn.microsoft.com/en-us/sharepoint/manage-site-redirects#to-remove-a-redirect). It looks like the deletion of the site doesn't work well. And this might help solve it. 

Source: https://github.com/pnp/PnP-Sites-Core/issues/2025#issuecomment-739108889

**Comment by as-sbridegroom** [comment]
Removing the redirect didn't solve much - but the link to the other issue was useful. I took a look at Marc Anderson's post immediately above it. I fired some Clear-PnPTenantRecycleBinItem commands at it, and then queried for all redirects - everything came back clean. Remove-SPOSite returned "file not found", Get-SPOSite returned "cannot get site" messages.

Re-ran the code (in PS ISE) - it completed and deployed the site, but had some warnings in it that I suspect will impair some of the functionality:

PowerShell_ISE.exe Warning: 0 : 2022-11-04 14:05:10.4737    [List instances]  [17]  [Information]     Skip adding/updating custom actions because the site has "noscript" enabled.  1294ms      587c
773b-0a67-43ff-88e3-d7b1abd0d11a
PowerShell_ISE.exe Warning: 0 : 2022-11-04 14:05:13.9469    [List instances]  [17]  [Information]     Skip adding/updating custom actions because the site has "noscript" enabled.  4767ms      587c
773b-0a67-43ff-88e3-d7b1abd0d11a
PowerShell_ISE.exe Warning: 0 : 2022-11-04 14:05:41.4540    [List instances]  [17]  [Information]     Skip adding/updating custom actions because the site has "noscript" enabled.  1076ms      587c
773b-0a67-43ff-88e3-d7b1abd0d11a
PowerShell_ISE.exe Warning: 0 : 2022-11-04 14:05:44.4178    [List instances]  [17]  [Information]     Skip adding/updating custom actions because the site has "noscript" enabled.  4040ms      587c
773b-0a67-43ff-88e3-d7b1abd0d11a
PowerShell_ISE.exe Warning: 0 : 2022-11-04 14:07:26.1172    [List instances]  [17]  [Information]     Skip adding/updating custom actions because the site has "noscript" enabled.  1176ms      587c
773b-0a67-43ff-88e3-d7b1abd0d11a
PowerShell_ISE.exe Warning: 0 : 2022-11-04 14:07:29.1755    [List instances]  [17]  [Information]     Skip adding/updating custom actions because the site has "noscript" enabled.  4234ms      587c
773b-0a67-43ff-88e3-d7b1abd0d11a
PowerShell_ISE.exe Warning: 0 : 2022-11-04 14:11:32.8398    [Web Settings]    [17]  [Information]     Skipping NoCrawl update because the site is configured for noscript.    230ms 587c773b-0a67-4
3ff-88e3-d7b1abd0d11a
PowerShell_ISE.exe Warning: 0 : 2022-11-04 14:11:32.8478    [Web Settings]    [17]  [Information]     Skipping master page update because the site is configured for noscript.      238ms 587c773b-0a
67-43ff-88e3-d7b1abd0d11a
PowerShell_ISE.exe Warning: 0 : 2022-11-04 14:11:32.8498    [Web Settings]    [17]  [Information]     Skipping custom master page update because the site is configured for noscript.     241ms 587c
773b-0a67-43ff-88e3-d7b1abd0d11a

Anything there that's a concern or that I may need to reprocess?
________________________________

**Comment by Laskewitz** [comment]
Thanks again for the response. You can ignore the warnings because we don't do anything with that type of content. Looks like all went well now! You can go through the configuration steps in the [docs](https://aka.ms/ppcst-docs) now and configure the site! 

Have a good weekend!
