### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 (Connection Identities) Limit

### ISSUE THREAD

**Issue by PyHatTech** [microsoft/coe-starter-kit#4109]
### Describe the issue

The "Sync Template v3 (Connection Identities)" CoE toolkit flow fails for the most important environment we have, the default environment. 

### Expected Behavior

The flow shouldn't fail. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

 3.53

### What app or flow are you having the issue with?

Sync Template v3 (Connection Identities)

### Steps To Reproduce

The flow run fail is popping up everyday in the command center app. 

### Anything else?

We looked at the other threads and followed your advise. What we did was run the script to clean the broken connections. 

https://github.com/microsoft/coe-starter-kit/issues/3293

What did this do?

Looks like it broke thousands of working flows and connections....

- a lot of flows have been stopped. Working connection has been removed. 
- owner of the flow can't edit flow as it's showing "could not find flow"
- the flow does actually exist. It has a functioning url
- the only way to fix it is by using a Power Platform service admin account and adding the owner as an owner
- we're seeing a lot of logicflow connections that have been removed
- the script deleted around 6000 connections
- the failed flow run (exceeding limits) is still failing

We opened a ticket with MSFT support and are sharing logs. The recommendation to use that script can be found here in github, but it's also documented here:

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components

No warnings that working flows could be impacted. Ownership of flows breaking.  just the recommendation to run the script and issues being closed on Github.

**Comment by Jenefer-Monroe** [comment]
That script should only delete connections that are broken and so working flows would not be impacted as they would already be broken by the broken connection. 
![image](https://user-images.githubusercontent.com/89584709/199722466-80ca5a24-5c64-44ec-8a87-d1e9e4513065.png)

We can add a warning that if done incorrectly this would have a large impact on the tenant. It is a dangerous area to play in, you are correct.

The issue we are trying to resolve with this is that there are too many connections for the **_Get Connections as Admin_** feature to return. So unless you can get under this hard limit, the flow will not be able to pass. 

Sorry for the confusion.

**Comment by PyHatTech** [comment]
that is the script we used. We created an export of the broken connections, before and after running that script. We're now getting a lot of tickets from users that can't edit their own flow. The flows were working before. We confirmed this by checking the runs. The only way to fix it was by adding them as an owner using an admin account. 

When looking in the first (before running the script) export, we can find the flow name of the broken flows in the "displayname". We're also seeing UPN's and the names of connectors. None of the impacted flows show up with a UPN or name or the connections in the export. 

In the linked thread (3293), someone mentioned connections being shown in the export that actually weren't broken. That user probably didn't run the script or they would have experienced the same thing. To me it seems like something is out of sync. It was out of sync before running the script, and this is why working flows were impacted. We're trying to convince MSFT support to escalate this. Have a feeling that MSFT can perform a sync on the backend. The response we have now is "we'll update you on Monday".

**Comment by Jenefer-Monroe** [comment]
It wouldn't as far as I can tell, and didn't in my testing. 
I'll take another look at this over the next couple days and see what I can find. Thanks for the information.

**Comment by PyHatTech** [comment]
Thanks.  We did test the script first in our test tenant and there it worked fine. Think it's only impacting working flows in tenants that are out of sync. Would still be good to know if MSFT has a way to force the synchronization on the backend servers. Remember reading some posts here where the recommendation was to create a ticket with MSFT support. Not related to this issue, but related to the default environment. Might be mistaken as I can't find the posts now. Is there a sync they can perform for our default environment? maybe something they do to fix other issues?

**Comment by Jenefer-Monroe** [comment]
What do you mean by out of sync?

**Comment by PyHatTech** [comment]
that would help I think, but the obvious question after that is, how to proceed? Next to fixing the broken flows, we still need to fix the flow run for the default environment. The script deleted a lot of connections, but it wasn't enough to fix the flow run. What other options do we have?

**Comment by Jenefer-Monroe** [comment]
Unfortunately I don't think there is anything we can do in this architecture. The upcoming [self service analytics](https://docs.microsoft.com/power-platform/admin/self-service-analytics) architecture for the kit (aka Bring your own Datalake) will have this information native and you would not need to use this flow.

**Comment by PyHatTech** [comment]
not directed at you, but the PG. It's unbelievable that basic monitoring isn't just part of the product and that one of the most important aspects of the monitoring toolkit doesn't work for large tenants. We're now getting 404 errors when we try to add someone as an owner to their own flow. Was trying to find the flow in the Power Platform admin center. Have to press "load more" for hours because it has no paging feature and the search only checks resourses that have been loaded on the page. A paging feature and a functioning search is too much to ask? I really don't get it.

**Comment by Jenefer-Monroe** [comment]
Oh I'm so sorry this has been frustrating. Does your organization work with the Power CAT team? I wonder if there is something programmatic that could be done to make the clean up easier.

**Comment by PyHatTech** [comment]
No, not yet. It really is a strange issue. MSFT support reassured us that it's being escalated. Here's the the ID TrackingID#2211020030001827 just in case you know someone that you could forward it to. The error we're getting is the same as the one mentioned on the following page, but the flow we're having this problem with isn't part of a solution.
https://powerusers.microsoft.com/t5/General-Power-Automate/Sharing-Flows-getting-error-quot-There-was-an-error-while/td-p/762273 Have seen several impacted flows with successful runs in the history that happened after we ran the script. This makes it seem like the flows do still exist and are still running, but we don't have a way to edit/update them. Fingers crossed that something can be done on the backend to fix this.

**Comment by manuelap-msft** [comment]
Hello,

we've just been in contact with the Engineering Team who's working on the incident/support ticket you raised. It looks like the PowerShell cmdlet has an unintended consequence (a bug in the cmdlet) that incorrectly removes active connections for flows called from Power Apps. 

This unfortunately didn't surface in our testing, hence we recommended the script from our documentation. I know this doesn't help you as such, but we're working on removing the mention of the script from our documentation now until the PowerShell cmdlet can be fixed.

Apologies for the inconvenience this has caused!

**Comment by PyHatTech** [comment]
thanks for reaching out to them and thanks for the update. Appreciate it.

**Comment by PyHatTech** [comment]
Just want to let you know that we created the ticket on Wednesday and we haven't received any information from MSFT support. They promised an update on Monday, but nothing. I'm sending emails and asking for updates and the engineers are replying back and reassuring me that "they are working on it". The questions I ask in the emails are being ignored. So I guess they're only willing to keep us informed indirectly via Github. You have a contact there. Could you maybe ask them to at least try and help us? The flows that were impacted aren't limited to flows triggered from Power Apps btw. In this case, they didn't just drop the ball, they're kicking it around. Very, very disappointing.

**Comment by Jenefer-Monroe** [comment]
It looks like support is restoring flows now, have you gotten traction?

**Comment by PyHatTech** [comment]
thanks for checking. They have indeed been able to restore some flows. This was after 19 days, but still glad they figured it out. Will close this issue as I don't think there is anything you guys can do for us here. We'll just work with the support team on this.

**Comment by Jenefer-Monroe** [comment]
Thanks for letting me know!
