### ISSUE TITLE
[CoE Starter Kit - QUESTION] Data of Tota_shared field

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#4110]
### What is your question?

Hi!
Where is calculated the dato of the field Total_Shared? I know that is the sum of the members of groups shared with a app + the users shared directly but I don't found where is calculated.

**Comment by Jenefer-Monroe** [comment]
Its a rollup column, but in investigating I'm finding a bug in the flows that feed it. Let me investigate and get this fixed up for Dec release.

**Comment by Jenefer-Monroe** [comment]
OK actually shared total is working correctly, and its the other two fields that are not.

**Comment by Jenefer-Monroe** [comment]
Total Shared is a roll up of of the Power Platform User Roles table, Group Size column. 
For my test case that means these are rolled up

![Image](https://user-images.githubusercontent.com/89584709/199743408-ffd6dab6-f38b-470b-bc5f-ab6c78c81be5.png)

Into this
![Image](https://user-images.githubusercontent.com/89584709/199743536-7ddfa9d0-f903-418a-84ca-46d0532fd167.png)

By this rollup


![Image](https://user-images.githubusercontent.com/89584709/199743909-c779c472-b011-40af-a949-2f19aa4c2a9e.png)

**Comment by Jenefer-Monroe** [comment]
Posted https://github.com/microsoft/coe-starter-kit/issues/4113 for the other fields being zero'd

**Comment by albertocaa1317** [comment]
Thank you so much @Jenefer-Monroe
