### ISSUE TITLE
[CoE Starter Kit - BUG] Pending suspension data missing

### ISSUE THREAD

**Issue by clareboyer** [microsoft/coe-starter-kit#4111]
### Describe the issue

I have noticed that there are some columns in the Flow table that aren't being updated by the Admin | Sync Template v3 (Flows) as I'd expect. 
- Flow Pending Suspension On: All rows are blank
- Flow Pending Suspension Reason: All rows are blank
- Flow Suspension Reason: Some rows contain data (as expected)
- Flow Pending Suspension PowerAppPlanExcluded: Some records show 'no', all others blank.

### Expected Behavior

After running the Admin | Sync Template v3 (Flows) flow, I'd expect the columns to be updated in the following way:
- Flow Pending Suspension On - I would expect to see a date value here for Flows that are pending suspension
- Flow Pending Suspension Reason:  For all flows that are pending suspension, I'd expect to see a text value describing the reason for pending suspension
- Flow Pending Suspension PowerAppPlanExcluded: I'd expect to see No or Yes values in this column. At the moment I am only able to see No or blank values, which doesn't tell me which Flows are currently pending suspension. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows) 

### Steps To Reproduce

1. Test in a tenant with active Flows of varying Flow States (Started, Stopped, Suspended) and that is regularly running the Admin | Sync Template v3 (Flow).
2. Open the Power Platform Admin View app and select Flows
3. In the Active Flows view, add the following columns to the view
 - Flow Pending Suspension On
- Flow Pending Suspension Reason
- Flow Suspension Reason
- Flow Pending Suspension PowerAppPlanExcluded
4. Review the data and compare with Expected behaviour.

### Anything else?

We're hoping that this data can help us identify when a Flow was suspended so that we can investigate flows that have been suspended over a period of time. Thanks.

**Comment by Jenefer-Monroe** [comment]
Spoke with user offline and they are going to contact support to get the expected list. From there we can debug together.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
