### ISSUE TITLE
[ALM Accelerator - QUESTION] Unexpected parameter PortalSiteName

### ISSUE THREAD

**Issue by challa85** [microsoft/coe-starter-kit#4112]
### What is your question?

I am getting the error "Error running pipeline: CustomAzureDevOps.RunPipeline failed: {"$id":"1","innerException":null,"message":"Unexpected parameter 'PortalSiteName'","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException","errorCode":0,"eventId":3000}" after hitting commit solution.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

CenterofExcellenceALMAccelerator_1.0.20221004.2_managed

**Comment by mikefactorial** [comment]
@challa85 this looks to be a conflict between the version of the pipeline templates you are using and version of the app you are using. If this is an upgrade to the new version of the app make sure you also upgrade the pipeline templates using the following steps https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-upgrade-config#updating-the-pipelines-in-azure-devops.

**Comment by mikefactorial** [comment]
@chall85 were you able to resolve this issue?

**Comment by mikefactorial** [comment]
Closing this out based on our recent calls
