### ISSUE TITLE
[CoE Starter Kit - QUESTION] Meaning of NUMBER EDITORS in set flow permissions app

### ISSUE THREAD

**Issue by jbst2018** [microsoft/coe-starter-kit#4117]
### What is your question?

Hi,team.

I have a quetsion about Meaning of NUMBER EDITORS in set flow permissions app.
Does the number written in NMBER EDITORS also include the number of run-only permission users written in the docs?
![image](https://user-images.githubusercontent.com/109139057/199896825-d6662359-1031-4006-9e51-bfd0c236e32e.png)

![image](https://user-images.githubusercontent.com/109139057/199896899-5e2fc6a9-7080-4c42-aeae-c0791f1677d5.png)
https://learn.microsoft.com/en-us/power-automate/create-team-flows#share-a-cloud-flow-with-run-only-permissions

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2022

### What app or flow are you having the issue with?

Set Flow Permissions

**Comment by Jenefer-Monroe** [comment]
It uses this function:   PowerAutomateforAdmins.GetAdminFlowOwnerRole(Envt, Flow)
Which I just tested and yes it counts the run only permissions. They come through as type viewer
![image](https://user-images.githubusercontent.com/89584709/200008230-fdd88bf4-076a-4684-9d55-1c9858df77ce.png)

**Comment by jbst2018** [comment]
Thank you very much.
