### ISSUE TITLE
[CoE Starter Kit - BUG]: Innovation Backlog - Email creators - not working

### ISSUE THREAD

**Issue by JakubZizka** [microsoft/coe-starter-kit#412]
**Describe the bug**
We want to use Innovation backlog app. Unfortunately, email of our service account is in "varTo" variable when emailing creators/voters no matter who created the idea. That makes it a little bit useless.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Innovation Backlog
 - Version 1.2
 - Innovation Backlog

**To Reproduce**
1. Create new Idea as user "A"
2. Try to "Email creators"

**Expected behavior**
We expect email address of the user "A" who submitted the idea to be in "varTo". Not our CoE service account email.

Any idea what we did wrong?

Thank you,
Jakub

**Comment by JeneferM-MSFT** [comment]
Hello, I dont repro this. Below is the path I followed to try and repro, can you please show me what you are seeing, including steps, in pictures? 


![image](https://user-images.githubusercontent.com/62659043/119018454-538e6180-b959-11eb-989e-56b328159b3c.png)

![image](https://user-images.githubusercontent.com/62659043/119018553-6bfe7c00-b959-11eb-8ee1-4b863d60e439.png)

**Comment by JeneferM-MSFT** [comment]
Closing out as no action for toolkit without a repro

**Comment by JeneferM-MSFT** [comment]
While investigating a bug in another solution I realized we were only looking at default values for these env vars, to match the old product behavior. 
App needed to change to also look for current values. 
Didnt repro locally as we use the default value in our dev envt. 

Fixed for next release. Workaround until fix: go to default solution > find the env var > update its default value as well as current. 

Thanks for helping make CoE great.

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
