### ISSUE TITLE
[CoE Starter Kit - BUG] App Shared Users in PowerApps Apps table is showing incorrect value

### ISSUE THREAD

**Issue by Harini-Parthiban** [microsoft/coe-starter-kit#4120]
### Describe the issue

App Shared Users values in the PowerApps app table is not getting updated. After creating and sharing the app with users, I ran **Admin | Sync Template v3 flow**. I was able to see the app in the table but the **App shared users and total shared counts were still zero.**

Then I ran the flow **Cleanup - Admin | Sync Template v3 (Power Apps User Shared With)** following with Admin | Sync Template v3 flow again. After this I was able to see the correct value for Total shared column but the App Shared Users is still zero.
![image](https://user-images.githubusercontent.com/107025014/200009327-89af187b-e783-47e5-aec7-7fe699133360.png)

- All flows are turned on according to [inventory setup instructions](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components) 
- Both the flows Cleanup - Admin | Sync Template v3 (Power Apps User Shared With) & Admin | Sync Template v3 flow passed successfully 

### Expected Behavior

Expected behavior is to have correct value of users shared over "App Shared users" column. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
The total shared is correct (up to the last runs of the **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_** flow + time for the roll up to perform). 

The things that are incorrect here are the App Shared Groups and App Shared Users columns. This was just raised and fixed yesterday via https://github.com/microsoft/coe-starter-kit/issues/4113. Thank you for posting as well.

**Comment by Harini-Parthiban** [comment]
Thanks for resolving. But, since we already installed this version, can you suggest a temporary fix for this issue?

**Comment by Jenefer-Monroe** [comment]
The fix was in too many places in the flow to recommend people fix locally. I'm afraid you will just need to wait for Dec release. Until then you can just note to look at the total column only.
