### ISSUE TITLE
[ALM Accelerator - BUG]: ALM Accelerator Administration - Team Members email disappears

### ISSUE THREAD

**Issue by LukasSchauffele** [microsoft/coe-starter-kit#4124]
### Describe the issue

Small bug in the ALM Accelerator for Power Platform Administration model driven app. On the _Azure DevOps Projects_ custom page, the listed team members _lose_ their email address when hitting the **Refresh** button. To re-populate the email, the project needs to be re-selected.

![CleanShot 2022-11-07 at 11 30 16](https://user-images.githubusercontent.com/7881214/200204311-daff0595-8a63-449a-92d2-53db489150b1.png)

### Expected Behavior

Team members email address not be blank after clicking on Refresh

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

November 2022

### Steps To Reproduce

1. Run ALM Accelerator for Power Platform Administration and navigate to the _Deployments_ area 
2. Under _Azure DevOps_ group, select the _Projects_ custom page
3. Select a project which has at least 1 team member
4. In the _Team Members_ section, click on the **Refresh** button

### Anything else?

Meta:

The bug report template is not showing the ALM Accelerator for Power Platform Administration as a component to select. 

![CleanShot 2022-11-07 at 11 37 23](https://user-images.githubusercontent.com/7881214/200204764-b2e23918-c8b6-40fe-ab0f-8af4a55df214.png)

**Comment by mikefactorial** [comment]
Thanks for reporting this @LukasSchauffele. Will get the experience cleaned up in an upcoming release.
