### ISSUE TITLE
[ALM Accelerator - BUG]: Pipelines no longer working after November update

### ISSUE THREAD

**Issue by ryanhodgson1** [microsoft/coe-starter-kit#4132]
### Describe the issue

Hi @mikefac

I did a big update from the ALM June version to the November version (so a few versions) and now my pipelines no longer work as it cant find the variables. Below is the error i get when exporting:
![image](https://user-images.githubusercontent.com/77652317/200488089-e1dcc53d-9e54-484e-90be-5b001c7742b5.png)

I know that there was a change from variables to parameters so i was looking into that but i cant find where the issue is.

I also checked that this is disabled in ADO:
![image](https://user-images.githubusercontent.com/77652317/200488052-6843de70-39cf-4999-88f3-c10468a03411.png)

Can you please help to see where the issue is? It could be an issue with the custom connector but unsure where to look.

### Expected Behavior

That the pipelines will work after the update

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

November release

**Comment by mikefactorial** [comment]
@ryanhodgson1 this appears to be related to the ALM Accelerator App not being in sync with the pipelines. We moved away from using variables a few releases ago and are using parameters instead in our pipelines. The error is indicative of the app not being in sync with the pipelines. Can you verify that you've upgraded both the pipelines and the solution? Also possible that there are unmanaged layers that are effecting upgrading the app. https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-upgrade-config

**Comment by ryanhodgson1** [comment]
Hi @mikefactorial i did upgrade the app and the repo as per the the documentation, its on the same app and tag release version. Where can i look for the unmanaged layers? these are the solutions i have in the environment right now:
![image](https://user-images.githubusercontent.com/77652317/200939411-e98b0e20-b62c-488a-ba69-94de6fef7780.png)

**Comment by ryanhodgson1** [comment]
Hi @mikefactorial 

Would this be the issue? do i just remove this and then do the solution upgrade again?

![image](https://user-images.githubusercontent.com/77652317/201544588-ac0cfb50-01c5-4f08-8e71-34d60d49bbf9.png)

**Comment by mikefactorial** [comment]
@ryanhodgson1 that seems like it could be the culprit. If you can remove the unmanaged layer and import the solution again as an "Update" not "Upgrade". We've noticed some strange behaviors with upgrade noted here https://github.com/microsoft/coe-starter-kit/issues/4114

**Comment by ryanhodgson1** [comment]
Thanks @mikefactorial, ill give that a go tonight and let you know

**Comment by mikefactorial** [comment]
One other thing to check related to export error is that the Azure DevOps permissions are set correctly. Since you upgraded I would expect these to have been set previously, but might be worth double checking. https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#update-permissions-for-the-project-build-service

**Comment by ryanhodgson1** [comment]
Thanks @mikefactorial 

Im looking into the deployment settings and i think it might be because previously we had AAD group IDs in there but now its using the SearchAAD group flow to actually find the groups:

![image](https://user-images.githubusercontent.com/77652317/202023133-9785730d-9165-4aa5-a612-68a9b23dd7f4.png)
(I can see you have add my feature request for the BU too, thanks for that :))

The issue im getting is that the SearchAAD group flow is failing to run:
![image](https://user-images.githubusercontent.com/77652317/202023432-6c07531b-4dc2-4882-9f5b-103541b3335e.png)

![image](https://user-images.githubusercontent.com/77652317/202023602-040df82f-2f19-4693-b28a-6ce5d7a7abc3.png)

Is there some additional API permissions the ALM service principal needs for this to work? i can see i get the same issue for the sharepoint flow.

**Comment by mikefactorial** [comment]
Yeah thanks for the suggestion on the BUs 👍. Was definitely a gap.

**Comment by ryanhodgson1** [comment]
Thanks @mikefactorial 

I created a new connection with the following:
![image](https://user-images.githubusercontent.com/77652317/202030164-a5879a3a-dcf2-4afd-b65a-9b6e29fa96fc.png)

I can only sign in under my own account though so not sure if its going to be using the ALM service principal.

I ran it again and getting this now:
![image](https://user-images.githubusercontent.com/77652317/202030425-6ea7cb68-279f-4a85-aea3-3e10b5ca6028.png)

Would it be possible to delete the flow and re-import the solution to re-create it?

**Comment by ryanhodgson1** [comment]
@mikefactorial i got it working under my own user context after changing the connections to ones under my account but if any other user logs in they have an issue. Would it be possible to delete the flow and re-import the solution to re-create it so it creates the connection reference under the managed solution?

**Comment by ryanhodgson1** [comment]
@mikefactorial the export pipeline is also not working still, even though all the deployment settings are up to date.

Do the settings in the deployment settings step look correct to you? are any of these null settings needed?
![image](https://user-images.githubusercontent.com/77652317/202080142-664a0650-cd08-4a34-b4a9-f551e379fc18.png)

**Comment by mikefactorial** [comment]
@ryanhodgson1

For the flow question. Sometimes the connections are sticky even after they are deleted and may be what you're seeing for others using the app. In the case where the flow fails did it try to prompt them again for the connection information? To be honest never tried deleting a flow and reimporting in the manner youre suggesting. Honestly, deleting managed solution components shouldn't be allowed at all, but that's a topic for another day). I'd say it's worth a try if nothing else works, but I don't have any guarantees that it won't have side effects.

For the error above there is a bug in the November pipelines that is documented on this thread https://github.com/microsoft/coe-starter-kit/issues/4077 and is related to AzDO projects with spaces in their name. Can't see your project name in the trace but it looks to be the same issue. I have created a PR with a fix for this here https://github.com/microsoft/coe-alm-accelerator-templates/pull/239. It's a fairly straightforward change to one of the YAML templates that you could apply prior to our December release. 

Happy to take feedback on if the pipeline update fixes your issue or not.

**Comment by ryanhodgson1** [comment]
@mikefactorial 

Thanks for that, i added the change but got the same issue:
![image](https://user-images.githubusercontent.com/77652317/202291387-88ed74a4-3076-4959-9df9-4f37bc549d86.png)

It looks like its putting the project name twice (before and after the change):
![image](https://user-images.githubusercontent.com/77652317/202291614-3f630aef-d856-46ef-842c-4082ea5766d1.png)

**Comment by mikefactorial** [comment]
Hmm. That doesn't make any sense. The unescape should have stripped the %20 encoding out of the name of the project in line 1502. Just ran it on my side and definitely does. Are you sure you added it to the same pipeline repository that the export pipeline is running from?

**Comment by mikefactorial** [comment]
Also, verify the branch. You can see the specific here
![image](https://user-images.githubusercontent.com/42348035/202296818-874a3ba8-91ad-439a-bd30-013cbd466a9f.png)

**Comment by ryanhodgson1** [comment]
Oh my mistake, i updated the wrong branch

**Comment by mikefactorial** [comment]
Whew. I thought I was losing it :)

**Comment by ryanhodgson1** [comment]
It looks like that solved that issue, but i got a new error in the same step:
![image](https://user-images.githubusercontent.com/77652317/202298037-b8aa22d8-89c6-46d6-b01c-13618633ddf2.png)

It says sample solution in there for some reason

**Comment by mikefactorial** [comment]
@ryanhodgson1 if you've renamed the steps from the default Validation, Test, Prod you will need to supply templates for the newly named steps. Out of the box we supply deployment templates specifically for these three deployment steps and default to those if the configuration is used as is.

![image](https://user-images.githubusercontent.com/42348035/202301276-31cbf6d9-e070-492b-a39c-b61a1d049455.png)

You can customize this by supplying your own template in this case you could just copy our build-deploy-test-SampleSolution.yml in your repo and rename it build-deploy-ccmsqa1-SampleSolution.yml and do the same for other deployment steps. You can also add more deployment steps and create additional templates. You can also explicitly set the template to use in the ALM Accelerator Admin Application on the Deployment Step in the Build Template Path column.
e.g. 
![image](https://user-images.githubusercontent.com/42348035/202302968-e974da73-de2e-44b2-bd75-64323b9a5b61.png)


More specifics about customizing / configuring pipelines is here https://learn.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-pipelines#customize-the-number-of-deployment-steps-in-your-pipelines-and-the-names-of-the-target-environments

**Comment by ryanhodgson1** [comment]
@mikefactorial 

I have a repo for each solution that has thier templates in it:
![image](https://user-images.githubusercontent.com/77652317/202305440-a51033a9-10a4-4cc9-823b-d39131fe03ca.png)

 I tried updating the template path but same issue:
![image](https://user-images.githubusercontent.com/77652317/202305947-41270012-3100-4aac-82a9-428d23fd70aa.png)

Can i point it to my open repo? or will i have to add it to the templates repo?

**Comment by ryanhodgson1** [comment]
@mikefactorial 

I moved the templates to the ALM template repo and ran it again and it found them, but then the next steps says they already exist? i removed them from the source branch that was passed to the export pipeline but same error:

![image](https://user-images.githubusercontent.com/77652317/202314990-c0317ef9-b37e-405d-b282-8cd40f074af5.png)

Bit confused as it was trying to find it on that path and now that it found it it says it already exists?

**Comment by ryanhodgson1** [comment]
@mikefactorial 

I have a number of developers blocked right now from this, would it be easier to connect on Teams to go through this instead?

**Comment by mikefactorial** [comment]
Hey @ryanhodgson1, feel free to set something up between 2:00 PM EST and 4:30 PM EST today michael.ochs [at] exalents [com].

**Comment by mikefactorial** [comment]
Meeting sent. Feel free to suggest another time. I'm open between 2:00 and 4:30 PM EST

**Comment by ryanhodgson1** [comment]
Thanks so much for the help @mikefactorial. I added in the fix you gave me and it is working as expected now :)

**Comment by ryanhodgson1** [comment]
@mikefactorial Is it normal for the Flow config to be removed from the deployment settings JSON in the new update?
![image](https://user-images.githubusercontent.com/77652317/202581311-f96a6f18-6dc2-4809-b54c-7f3b22d18985.png)
