### ISSUE TITLE
[CoE Starter Kit - BUG] New DLP Policy Change Request, dropdown for Policy doesn't allow any selectioon

### ISSUE THREAD

**Issue by shriyamal** [microsoft/coe-starter-kit#4137]
### Describe the issue

In the DLP Request app when creating a new DLP Policy Change Request and I select the Policy to be applied, the dropdown doesn't work to open the list of policies I can select.

### Expected Behavior

Ability for the dropdown under Policy to show me selections 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

NA

### Steps To Reproduce

1. In the CoE environment, open the Environment Request Maker App
2. Select the tab for a new DLP request 
3. Add new DLP request
4. Select "Apply a policy to an environment" under Action requested
5. Select the environment under Environment
6. Attempting to select a Policy under Policy but nothing displays and I cannot progress with the request

**Comment by manuelap-msft** [comment]
Have you made any policies visible to be requested in the Admin - Environment Request app? See https://learn.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt#sync-shared-policies
