### ISSUE TITLE
[CoE Starter Kit - BUG] [Child] Admin | Sync Logs

### ISSUE THREAD

**Issue by shailan76** [microsoft/coe-starter-kit#4139]
### Describe the issue

Child Admin Sync Log does not run because of a 401 error. The user has the credentials required. 

### Expected Behavior

Child sync to work

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Child Admin Sync Log

### Steps To Reproduce

1. CoE Environment
2. Flows
3. Try and start Child Admin Sync Log
4. Check runs

### Anything else?

![Screen 1 Error](https://user-images.githubusercontent.com/117372397/200550100-9894b99a-d7e1-4fb4-9609-32a2f16819ba.png)
![Screen 4 Error](https://user-images.githubusercontent.com/117372397/200550103-8f779e72-7936-498f-b463-77705229f71e.png)
![Screen 3 Error](https://user-images.githubusercontent.com/117372397/200550108-f2178b91-36d1-45c5-8c34-7467be88d3c9.png)
![Screen 2 Error](https://user-images.githubusercontent.com/117372397/200550109-40446bac-bb68-4cb2-9aec-f2c483a823bf.png)

**Comment by Jenefer-Monroe** [comment]
Hello the custom connectors need reset with upgrades. Please see https://github.com/microsoft/coe-starter-kit/issues/1424

**Comment by shailan76** [comment]
Hi, this didn't work. The actual connector didn't require fixing, or have fix connection. More info below. 

![image](https://user-images.githubusercontent.com/117372397/200668706-e1a8cd1e-7cea-44f8-986a-d094a8b620b0.png)

It turns out admin privileges were removed, so need to add again.

**Comment by Jenefer-Monroe** [comment]
Thanks for letting us know, glad this got resolved!
