### ISSUE TITLE
[CoE Starter Kit - QUESTION] DLP Policy table CoE, not populated.

### ISSUE THREAD

**Issue by cr0max** [microsoft/coe-starter-kit#4140]
### What is your question?

Hi,
I'm curious on what flow actually populates the DLP Policy table CoE? The DLP Editor and Custom Environment creation apps work fine. But the table is empty.

There is an error on the DLP Request | Sync Shared Policies flow, but I do not think that this is the reason.
![image](https://user-images.githubusercontent.com/97740538/200611810-c9128458-78d5-4766-90e8-83db64adc53d.png)

Also the DLP Policy Change Request is not letting users select a policy and this might be caused bu the table beeing empty.
![image](https://user-images.githubusercontent.com/97740538/200612084-94d7745e-e413-4f7d-88f0-bbd8dd518e63.png)

Any advice?

/Sascha

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

**Comment by Jenefer-Monroe** [comment]
This table does not contain all the DLP policies in the tenant, just those you want to share with the Maker personas for use in the [Developer: Request a DLP Policy Change](https://learn.microsoft.com/power-platform/guidance/coe/env-mgmt#developer-request-a-dlp-policy-change) process.

Please see [Sync shared Policies](https://learn.microsoft.com/power-platform/guidance/coe/env-mgmt#sync-shared-policies) for how to add policies to the table.

**Comment by cr0max** [comment]
Ok, thanks. I want't to add the DLP table in the Power BI report, so env owners can see which policies applies to their env. So I'll have to make them all visible then.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
