### ISSUE TITLE
[CoE Starter Kit - BUG] Description in Flow Admin | Sync Template v3 (Ai Models)

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#4145]
### Describe the issue

Real Simple change..

In flow Admin | Sync Template v3 (Ai Models)
 the Description refers to Portals, it should refer to Ai Models.    Simple as that

### Expected Behavior

as above

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 22

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Ai Models)

### Steps To Reproduce

View the description of the flow.

**Comment by Jenefer-Monroe** [comment]
Thank you for an easy one! :)

![image](https://user-images.githubusercontent.com/89584709/200853147-d3147f03-be55-4f93-bad7-4314320d6aae.png)
