### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by keharrin** [microsoft/coe-starter-kit#4147]
### Describe the issue

We are setting up the Production COE Dashboard from the October release.

We have embedded the Admin - Flow power abb the Cloud Flow detail page.

When attempting to use the app, we get this error message 

Office365Users.UserProfileV2 failed: The method 'UserProfileV2' has an invalid value for parameter 'id'

When I attempt to add myself I get the following error.  I am a Power Platform admin and have Environment Maker access to the COE Environment.

PowerAutomateforAdmins.GetAdminFlowOwnerRole failed: { "error": { "code": "EnvironmentAccessDenied", "message": "You are not permitted to make flows in this '12ca3475-c509-e18d-9dfa-dd949c00a21d'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions." } }

### Expected Behavior

It is expected that when we drill through on the details for a flow it will return list of permissions and allow the addition of new users.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.25

### What app or flow are you having the issue with?

Production Dashboard

### Steps To Reproduce

Go to Cloud Flow page in dashboard, right click and select Drill through
![image](https://user-images.githubusercontent.com/77410660/200864415-8429bbae-15c5-4b57-99c8-bee41bc74888.png)

![image](https://user-images.githubusercontent.com/77410660/200864617-366a3291-3eb6-4257-b1ed-eee29fe0ea1c.png)

**Comment by keharrin** [comment]
user error forgot to have config  to admin_flowid

**Comment by Jenefer-Monroe** [comment]
thanks for letting us know!
