### ISSUE TITLE
[CoE Starter Kit - QUESTION] Where are the instrutions for setting up the Admin - Environment Request

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#4151]
### What is your question?

Where are the instructions for setting up the Admin - Environment Request.  I am getting errors when I run this - 
{
  "duration": 440.2,
  "size": 127,
  "status": 400,
  "headers": {
    "REQ_ID": "840c7da1-407e-47c1-bb9c-fd255b3d4071",
    "Content-Type": "application/json; odata.metadata=minimal",
    "OData-Version": 4,
    "Cache-Control": "no-cache, proxy-revalidate",
    "content-encoding": "gzip",
    "Content-Length": 326,
    "expires": -1,
    "odata-version": 4,
    "req_id": "840c7da1-407e-47c1-bb9c-fd255b3d4071",
    "x-ms-client-request-id": "db280132-c263-462d-9b05-b23046b4700a"
  },
  "body": {
    "error": {
      "code": "0x0",
      "message": "Could not find a property named 'admin_User' on type 'Microsoft.Dynamics.CRM.admin_maker'."
    }
  },
  "responseType": "text"
}

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

**Comment by Jenefer-Monroe** [comment]
You get this error when loading the **_Admin - Environment Request_** app? 
If so, can you please open in edit mode? That will help us isolate the issue.

**Comment by Jenefer-Monroe** [comment]
And please quickly check for an unmanaged layer on the app before proceeding. 
![image](https://user-images.githubusercontent.com/89584709/201136876-dd661687-cc27-4882-a133-a2237a9b1875.png)

**Comment by NPrice99** [comment]
Hi @Jenefer 
I have found the problem line - 
    /* Get entire existing makers table */
    ClearCollect( col_allmakers, Makers );

Regards

Nigel

**Comment by Jenefer-Monroe** [comment]
Strange. Can you see if you can manually refresh the Maker table? 
From within the Maker Portal you would go to the Data table and then refresh Makers
![image](https://user-images.githubusercontent.com/89584709/201166741-ebb6d413-2e4f-4353-b1d9-076c9e5fecd4.png)

**Comment by NPrice99** [comment]
Hi @Jenefer 
Been there done that refreshed the table.  i have also deleted the connection and reconnected it.

Still the same problem.

Regards

Nigel

**Comment by Jenefer-Monroe** [comment]
Refreshing the table worked though?

**Comment by Jenefer-Monroe** [comment]
Denise, I believe there used to be a column called user in the maker table, perhaps you had a dependency on it somewhere? I do not repro this though. Hoping you can investigate.

**Comment by NPrice99** [comment]
Hi @Jenefer 

No Refreshing the table did not work.  I can edit the data in the table using "Edit" but as soon as I run the POwerApps button, it fails.  If you switch off Formula-level Error Management setting, then you can see the real error "Could not find a property named 'admin_User' on type 'Microsoft.Dynamics.CRM.admin_maker'."

Regards

Nigel

**Comment by NPrice99** [comment]
Hi @Jenefer-Monroe 
This morning I rebooted my Laptop and all now seems to work.
I dont understand why.

Was there an update (PowerApps release) to 3.22105.21 yesterday.  I wonder if that fixed the issue.

Regards

Nigel

**Comment by Jenefer-Monroe** [comment]
oh wonderful. Thank you for the update!
