### ISSUE TITLE
[CoE Starter Kit - BUG] - Set Flow Permission App Shows the incorrect Note when changes the Flow Permission 

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#4155]
### Describe the issue

The Set Flow Permission app shows the incorrect note when changes the permission for the flow: Still shows the message for app instead of flow
<img width="713" alt="image" src="https://user-images.githubusercontent.com/112712553/201162966-b1819044-2ba0-4588-93a5-e764a8e60aac.png">

### Expected Behavior

Should the correct note w.r.t. flow permissions

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November

### What app or flow are you having the issue with?

Set Flow Permission App

**Comment by Jenefer-Monroe** [comment]
I've hidden it for Dec release. Thanks for posting.
