### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by ddebela22** [microsoft/coe-starter-kit#4156]
### What is your question?

In Inactivity processes, a flow named ‘[Admin | Inactivity notifications v2 (Check Approval)] & [Admin | Inactivity notifications v2 (Clean Up and Delete)]’ send notifications from Microsoft Flow to ask the app owner (via flow approvals) whether the app can be deleted.
In this process, can we modify the subject, body, and sender email address? Is there any template for that?

![image](https://user-images.githubusercontent.com/117931210/201182217-a2ec4516-78db-4df5-ba1f-0d48f4a32297.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

October 2022

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Clean Up and Delete), Admin | Inactivity notifications v2 (Check Approval)

**Comment by Jenefer-Monroe** [comment]
Hello. This is on our backlog as https://github.com/microsoft/coe-starter-kit/issues/1683 and targeted for the January release. 
Along time in the coming but we wanted to wait for the product feature to make helpers work across solution to complete. And that is done now! :)
