### ISSUE TITLE
Setting up CoE for a subset of environments variable not there

### ISSUE THREAD

**Issue by mknightca** [microsoft/coe-starter-kit#4164]
### What is your question?

from this part of the wiki: https://learn.microsoft.com/en-gb/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments

I can't complete this step: "After import of the Core components and before you turn on flows, set the value of the is All Environments Inventory environment variable to No"

I'm trying to find the variable "is All Environments Inventory" but it doesn't exist. I have CoE already installed for a while and Core Components installed. Does the variable just disappear because flows are running? the other page suggests not and i'd have to restart flows if that's the case so i don't see that being the casaue.l

Seems this variable does not exist anywhere and I can't find it. How do i omit particular environments from CoE without this variable?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
Hello, this feature to only track a subset of environments is new to the [November release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2022) via bug https://github.com/microsoft/coe-starter-kit/issues/3710

So you will not see it in 3.53 which was the Oct 2022 release. 

Glad to her you excited to use the feature! Once you upgrade please try it out and let me know if it meets your needs.

**Comment by mknightca** [comment]
oh wow i'm that quick am I :), will try the november upgrade and report back if i use this.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
