### ISSUE TITLE
[CoE Starter Kit - BUG] Admin - Access this App won't work standalone

### ISSUE THREAD

**Issue by maru55** [microsoft/coe-starter-kit#4167]
### Describe the issue

i have done setup for Center of Excellence Core components apps, i have turned on all flows and sub flows, when i run Admin - Access this App  i am getting below issue, PowerAppsforAdmins.GetAdminAppRoleAssignment failed: { "error": { "code": "BusinessAppPlatformRequestFailed", "message": "The request failed with client error: 'The environment '' could not be found in the tenant '77428205-87ff-4048-a645-91b337240228'.'. The correlation Id is '0bab5761-4cce-4214-8117-8576016ece92'.", "details": [ { "code": "MultipleErrorsOccurred", "message": "Multiple errors occurred. Please see details.", "details": [ { "code": "EnvironmentNotFound", "message": "The environment '' could not be found in the tenant '77428205-87ff-4048-a645-91b337240228'." } ] }, { "code": "FullNonLocalizedError", "message": "{\"error\":{\"code\":\"EnvironmentNotFound\",\"message\":\"The environment '' could not be found in the tenant '77428205-87ff-4048-a645-91b337240228'.\"}}" } ] } }, i checked Tenant id inside Azure directory, it is same only, is that Azure i need admin access, currently i have User acess, please guide me team,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin - Access this App

### Steps To Reproduce

open make.powerapps.com
Env:MaruthiCOEStarter
App: Admin - Access this App(run in play mode)

**Comment by manuelap-msft** [comment]
Hello,

the Admin - Access this app and Admin - Access this flow app can only be used in the context of being embedded in Power BI 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard

These apps won't work when used standaloen, as they take parameters from when you drillthrough to them from Power BI.

Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
