### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unmanaged solution for November release

### ISSUE THREAD

**Issue by raulcocerasanchez** [microsoft/coe-starter-kit#4169]
### What is your question?

Last version  CoE November  managed does not match with the unmanaged version.
Ex : core solution 356 vs 3.53 .
Unmanaged power bi solution Production_CoEDashboard_October2022.pbit

### What solution version are you using?

November

**Comment by manuelap-msft** [comment]
We had an issue with our release automation in November, and unfortunately weren't able to make the unmanaged solution available this month. We'll likely be back to having both the unmanaged and managed solution available in December.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
