### ISSUE TITLE
[AA4AM] Remove multiple agents for build/deploy

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#417]
**Is your feature request related to a problem? Please describe.**
A side effect of supporting the build completion triggers was the need to have multiple pipeline runners and as a result needed to load required packages multiple times.

**Describe the solution you'd like**
Remove the old build completion pipelines and update the latest pipelines to use a single agent.

**Comment by devkeydet** [comment]
Let's make the work to do the remove the old build completion pipelines to another issue and just focus this on the optimization of the pipeline.
