### ISSUE TITLE
[ALM Accelerator - BUG]: Pipelines not found

### ISSUE THREAD

**Issue by ShinraTenseiii** [microsoft/coe-starter-kit#4172]
### Describe the issue
I installed the ALM Accelerator with the CoE CLI method.
When I try to commit a solution or delete a solution from the Accelerator PowerApp, it gives me an error that the Pipeline is not found in the repository.
![image](https://user-images.githubusercontent.com/84532843/201674492-fee171c2-d509-460e-bbaa-9723fa70f347.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20221101.1

**Comment by mikefactorial** [comment]
@ShinraTenseiii this looks to be an issue with the pipeline setup in Azure DevOps pointing to the wrong location for the backing yml file. Try editing the delete-unmanaged-solution-and-components pipeline in Azure DevOps and see where the pipeline is pointing to in your repo.

![image](https://user-images.githubusercontent.com/42348035/201690203-d8b52210-ced0-48b5-a1c4-4d9256f19c91.png)

**Comment by ShinraTenseiii** [comment]
There is no code inside the pipeline.
I got the following warning error during installation. 

![image](https://user-images.githubusercontent.com/84532843/201699185-f589b108-8b69-424b-ae07-3057366f801f.png)

**Comment by ShinraTenseiii** [comment]
Even the pipeline is empty.

![image](https://user-images.githubusercontent.com/84532843/201718565-928160d5-9d3f-4373-b4a1-8ece91dda1d9.png)

**Comment by mikefactorial** [comment]
@ShinraTenseiii not sure what the failure was in the cli install. However, you can try manually deploying the pipeline templates instead of using the CLI. The steps to do this are documented [here](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-preview#set-up-your-first-azure-devops-project-for-use-with-alm-accelerator-for-power-platform)

**Comment by mikefactorial** [comment]
Closing this out due to inactivity / No further action required
