### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 CoE Solution Metadata - inputs.parameters

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#4174]
### Describe the issue

Hi,

I've copied an Environment with CoE, to create an Dev CoE Environment.
After that I imported the already installed CoE Solution to create connections without creating an unmanaged layer for each flow.
When I start Admin | Sync Template v3 CoE Solution Metadata I get an error at Update CoE Metadata last run pass
Details
The 'inputs.parameters' of workflow operation 'Update_Last_Run_Successful' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadat

### Anything else?

![image](https://user-images.githubusercontent.com/113470539/201675638-28d55d0c-d3bb-4c98-a595-20e44eaa5ac3.png)

**Comment by wiskaso** [comment]
I get this error from a net-new installation as well.

**Comment by wiskaso** [comment]
Just took a quick peek at the code and it looks to me like the issue seems to be a mismatch between the resolved name from the workflow()?['name'] function in the "Get ID Pass" action and the actual flow GUID in the environment itself:
![image](https://user-images.githubusercontent.com/27371887/202782484-ca0f7935-db90-4b87-9699-def880ca02b0.png)


Note the GUID in the URL vs. the what the workflow() function thinks the name (GUID) is.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/27371887/202784111-7cc53e7d-6b21-411e-b124-1fc2ce4ed599.png">


This causes a null value to passed along as the 'recordId' to the "Update Last Run Successful" action since "Get ID Pass" never returned any results.


In another throw away flow... I ran this with the GUID in the URL and works as expected.  I'm still unsure why workflow is returning the wrong GUID though.

**Comment by Jenefer-Monroe** [comment]
Sounds like something cached when you copied the environment. Sometimes resetting the flow (by turning it off and on) works to clear the cache in the flow. Can you try that? 
Generally speaking, we have not tested the path for copying a CoE for reuse as a Dev environment, we just install there. So you may hit product issues like this that we have not seen ourselves.

**Comment by dhsl** [comment]
Same issue here, fresh install without any copy/paste from a different environment

**Comment by Jenefer-Monroe** [comment]
while we await the product team to revert the change that broke this, please note that you are not blocked from proceeding. This is failing at a spot where it updates a flag we are using for an upcoming feature, so you are ok

**Comment by kashanico** [comment]
Our Sync Template v3 CoE Solution Metadata flow has been failing with the same error as well. Installed Nov upgrade, issue still persists. 

![image](https://user-images.githubusercontent.com/64927104/203178710-6eb0f7a2-ad11-452b-95f2-980c519839d0.png)

**Comment by nitingupta2012** [comment]
Same issue with a fresh new install. Seems like it is not picking the right GUID value and hence returning an invalid workflow guid. As you said that we are not blocked so moving to next steps.

**Comment by Jenefer-Monroe** [comment]
Yes this is not an issue with the kit. It is a product change. 

The flow GUIDs returned by the product are not correct but the expression used here get the GUID is still correct, hence the failure in the flow when we try to compare them.

**Comment by manuelap-msft** [comment]
Hello,

unfortunately, a planned change to how Power Automate flows are identified has started rolling out. Basically, the change assigns a new GUID (unique ID) to all solution aware flows. The CoE kit relies on IDs being unique over time so this change has caused disruption and error to the CoE kit. 

The change reached stations 1-3
![image](https://user-images.githubusercontent.com/55705669/203813112-80beec8d-6a92-412c-b6cb-d3b826a86141.png)

The change has been halted now, so will not reach further stations (Europe and North America) so customers in those regions will not be impacted. However, for customers in regions that are impacted we are still investigating what to do next. Unfortunately, this change is not something we were aware of happening and something that was out of our control, so we have some work to do now to see how we can work with the new IDs.

This has nothing to do with a bug in the CoE kit or a specific version of the CoE kit - it's a change that rolled out to the Power Automate product, the CoE kit as it is built on top of the platform is subject to platform changes and thus impacted by changes to Power Automate. 

Currently, I believe the impact is isolated to Stations 1-3 from above. Existing installations and upgrades here will fail. New installations should work if installed in a new environment.

**Comment by lukas-nC** [comment]
sorry for the late reply, I was sick
I still get errors caused by this flow 
e.g. in Admin | Sync Template v3 (Connectors)
![image](https://user-images.githubusercontent.com/113470539/205619329-83e36423-0d9f-40a8-a09b-b8e0f63e1459.png)

In the Admin | Sync Template v3 CoE Solution Metadata Flow
![image](https://user-images.githubusercontent.com/113470539/205619769-ecd42cf7-1687-465c-b385-cbd56c35acf9.png)
the 'List flows as Admin' only returns 18 flows??? and the Admin | Sync Template v3 (Connectors) isn't one of them

Any ideas?

**Comment by Jenefer-Monroe** [comment]
Which of these regions are you in?
![image](https://user-images.githubusercontent.com/89584709/205647726-85a835ac-7f3e-44f8-8b31-c68bcb7d8445.png)

**Comment by lukas-nC** [comment]
Station 4

**Comment by Jenefer-Monroe** [comment]
This was resolved by the product team by backing out the change. Closing out as no further action for starter kit team. Please let us know if you see issues in the future.
