### ISSUE TITLE
Developer Compliance Centre is empty

### ISSUE THREAD

**Issue by HMJ-Somerset** [microsoft/coe-starter-kit#4177]
I have just moved from a Teams environment to a Production PAYG environment for the CoE.  However, having installed and configured the compliance solution I have found that there is no app or flow data displayed in the Developer Compliance Centre.

If my makers can't supply the app details then I can't switch on the compliance requests...

![image](https://user-images.githubusercontent.com/106976858/201714501-1f757326-1c71-482a-8d9b-50005b744180.png)

**Comment by manuelap-msft** [comment]
Hello,

let's check a couple of details first
1. Are all your Admin - Sync flows running without failure? You can check in the Admin - Command Center to see if there are any failures
2. When you open the Power Platform Admin View, do you see your apps and flows inventory there? 
3. In the Developer Compliance Center, are all tabs empty or just the one for apps? Can you try toggling off the Can Edit to only show apps you own?

**Comment by HMJ-Somerset** [comment]
hi Manuela

1:  All sync flows run without failure except the SyncFlow (Portals).  As we don't have any portals, I have turned this flow off.
2.  Yes, I see the full list of apps and flows in the Admin Command Centre
3. In the Developer Compliance Centre, both canvas apps, model driven apps, sharepoint apps and flows are missing.  I have tried toggling Can Edit to show only Apps I own and for Requested /All Objects and for Not Compliant / All DLP status

**Comment by HMJ-Somerset** [comment]
Any progress on why this is occurring?

**Comment by Jenefer-Monroe** [comment]
I think there is a bug with the All DLP. Can you turn that one off?

**Comment by HMJ-Somerset** [comment]
I can't see a Flow called All DLP.
The only flows I have with DLP in the title are: 
![image](https://user-images.githubusercontent.com/106976858/203319508-c9e523d8-6c2f-4efd-a9ed-885ebeac6b3d.png)

**Comment by HMJ-Somerset** [comment]
I have tried that and it still doesn't show any apps..
![image](https://user-images.githubusercontent.com/106976858/203324111-bb5a0dfd-2189-4a57-97c2-57e84df7dc19.png)

**Comment by Jenefer-Monroe** [comment]
Sorry, just turn off the DLP one, leave the other two toggled on. Can you try that for me?

**Comment by HMJ-Somerset** [comment]
![image](https://user-images.githubusercontent.com/106976858/203324924-cf2152a4-2a6b-483b-a70e-ebd96f1c4373.png)

**Comment by Jenefer-Monroe** [comment]
Are you logged in to the app as a user that is an owner or editor of an app?

**Comment by HMJ-Somerset** [comment]
Yes, I own about 66 apps and 142 flows with co-owner or editor to many more

**Comment by Jenefer-Monroe** [comment]
ok I posted the DLP issue then with another bug https://github.com/microsoft/coe-starter-kit/issues/4248
We will use this one for your instance

**Comment by Jenefer-Monroe** [comment]
Can you please go to the PowerApps table in Core Components and edit the fields shown in the data tale as shown here
![image](https://user-images.githubusercontent.com/89584709/203332796-4e22d695-f777-4ed6-8292-4df908f0b83a.png)

Then filter App owner to you (the identity with which you have booted the app), Add Deleted to No, and App Type to Canvas. 
![image](https://user-images.githubusercontent.com/89584709/203333028-36eaf8b9-a38d-4932-a1e9-2402373a6372.png)

How many rows do you see?

**Comment by HMJ-Somerset** [comment]
45 rows

**Comment by Jenefer-Monroe** [comment]
Sorry I realize my picture shows filtering to Model Driven Apps, your filter should be to type Canvas. Can you please confirm by sharing a screenshot like this? 
![image](https://user-images.githubusercontent.com/89584709/203335405-f127f7dc-1710-4b45-bf51-25fd7e41d493.png)

**Comment by HMJ-Somerset** [comment]
The answer is still 45, I followed your instructions not the screenshot

**Comment by Jenefer-Monroe** [comment]
Sorry but can you please share a screenshot? Sometimes instructions arent clear and a screenshot helps us understand the issue where words do not.

**Comment by HMJ-Somerset** [comment]
![image](https://user-images.githubusercontent.com/106976858/203337650-1ac1d366-2fc3-4ff5-8aed-ea2a348d1afa.png)

**Comment by Jenefer-Monroe** [comment]
OK this is very strange. I think the next thing to do will be to test around in a test app but before doing that, can you please just quickly test that you dont have unmanaged layers on the Developer Compliance Center? 

![image](https://user-images.githubusercontent.com/89584709/203338653-5c68faac-0271-436e-914e-74b40df9ff58.png)

It should look like this if there are no problematic layers
![image](https://user-images.githubusercontent.com/89584709/203338761-1c879cb6-819f-49cb-a159-808af20cc7b4.png)

**Comment by Jenefer-Monroe** [comment]
Then if there are no layers, please create a new app in the CoE Environment 
![image](https://user-images.githubusercontent.com/89584709/203339066-da23b982-0433-4377-900c-ddc2ab962c20.png)
![image](https://user-images.githubusercontent.com/89584709/203339159-4d991919-1da3-481f-ad09-d01030066019.png)

Insert the Office365Users connector, the Makers table, and the PowerApps table
![image](https://user-images.githubusercontent.com/89584709/203339761-15779d5e-2f2d-45a8-b18d-23a81c466c4b.png)
![image](https://user-images.githubusercontent.com/89584709/203339932-e8d41752-9f15-43ff-a3ea-82faf5f0a8f6.png)



Insert a button with the following OnSelect value
```
Set(
    myOfficeProfile,
    Office365Users.MyProfileV2()
);
Set(
    myMakerProfile,
    LookUp(
        Makers,
        Maker = GUID(myOfficeProfile.id)
    )
);
Set(
    myId,
    Office365Users.MyProfileV2().mail
);
ClearCollect(
        myApps,
        Filter(
            'PowerApps Apps', 
            'App Owner'.Maker = myMakerProfile.Maker && 'App Deleted' = 'App Deleted (PowerApps Apps)'.No
        )
    );
```
And a text label with text value of `CountRows(myApps)`

**Comment by HMJ-Somerset** [comment]
Just the one layer 
![image](https://user-images.githubusercontent.com/106976858/203352783-e516971d-23ac-46b4-87ca-e36e42e9a6e8.png)
will go ahead with the app...

**Comment by HMJ-Somerset** [comment]
0 apps...
![image](https://user-images.githubusercontent.com/106976858/203354602-f4c39436-e705-47c6-9534-8e90cb604c2b.png)

**Comment by Jenefer-Monroe** [comment]
good! a repro! 
Make another text field and have it display `myOfficeProfile.displayName`

**Comment by Jenefer-Monroe** [comment]
And a third that shows `myMakerProfile.'Display Name'`

**Comment by HMJ-Somerset** [comment]
all blank

**Comment by Jenefer-Monroe** [comment]
ok there is something wrong with your user and the office365 connector then. 

In the maker, if you call the connector directly like this, does it also return nothing? 
`Office365Users.MyProfileV2().displayName`

Does your identity show correctly from the top right? 
![image](https://user-images.githubusercontent.com/89584709/203365034-370437a6-9e72-4eed-8d69-adee65bd3ecf.png)


Can you please share a screenshot?

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
