### ISSUE TITLE
[CoE Starter Kit - QUESTION] Developer Compliance Center App error messages in app and flows screen

### ISSUE THREAD

**Issue by Harini-Parthiban** [microsoft/coe-starter-kit#4181]
### What is your question?

Hi, I'm getting the following error messages while I open **Developer Compliance Center** for apps and flows screen.

**For App:**

Error in **GetConnector** method:
![image](https://user-images.githubusercontent.com/107025014/201855721-6d76f8c7-4da1-4c1f-bc90-7d7488d38683.png)
![image](https://user-images.githubusercontent.com/107025014/201856256-65bb6d31-5821-4ad1-bb98-c713aa93c7d6.png)

**For Flows:**

1. Error in **ListFlowOwners** method:

![image](https://user-images.githubusercontent.com/107025014/201856485-dcae4c26-79ed-4830-9fd0-c6f99b16772b.png)
![image](https://user-images.githubusercontent.com/107025014/201856522-631638e0-1876-4e57-9ba0-05214bcd8b8d.png)

2. Error in **GetConnector** method:

![image](https://user-images.githubusercontent.com/107025014/201856945-cd974237-3109-4882-b208-0e5d3614cf9a.png)

3. Method **UserProfileV2** failed

![image](https://user-images.githubusercontent.com/107025014/201858479-9b56ead3-5798-488a-87ce-8b7b86a0aaf1.png)
![image](https://user-images.githubusercontent.com/107025014/201858694-e2586afa-e884-45a2-96ff-ddb317122342.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.23

### What app or flow are you having the issue with?

Developer Compliance Center App

**Comment by Jenefer-Monroe** [comment]
It's hard to track all these without knowing what you have selected but I know at least some of these are fixed already

Ex here for what is live today for your first issue:
![image](https://user-images.githubusercontent.com/89584709/203074310-e716c548-3914-42ea-acf0-ec94d56ba4ee.png)

And at least one is tracked by this bug which is local fixed for Dec. 
https://github.com/microsoft/coe-starter-kit/issues/4175

I suggest you upgrade when Dec ships and then post issues if some still exist. Thank you

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
