### ISSUE TITLE
[CoE Starter Kit - QUESTION] Use ALM Accelerator for CoE Deployment

### ISSUE THREAD

**Issue by fredrikhr** [microsoft/coe-starter-kit#4182]
### What is your question?

If I fork the https://github.com/microsoft/coe-starter-kit repository to my organization's Azure DevOps instance, can I then use ALM Accelerator to deploy CoE to our Power Platform? Or are additional steps necessary to produce the release artifacts contained in a CoE release?

If using the ALM Accelerator, I'd be able to use Deployment Configuration to set up who should own and activate components in the CoE solutions making deployment easier for me. For example, if I import the CoE solutions in the context of my own user account, all components I import will be owned by me. But I'd much rather these be owned by a different 'service'-user that has been created specifically for CoE. Currently I am using XrmToolBox for importing CoE solutions in order to be able to impersonate that other user, but ideally, I'd like to dog-food the ALM Accelerator for this purpose instead.

### What solution version are you using?

November 2022

**Comment by mikefactorial** [comment]
Hey @fredrikhr, you should be able to use the ALM Accelerator to deploy the CoE Kit. We validate the ALM Accelerator releases using the CoE Kit solutions internally so this is a good use case.

**Comment by mikefactorial** [comment]
There are a few resources that are external to the solutions themselves including the PowerBI dashboards you can find under https://github.com/microsoft/coe-starter-kit/tree/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit
