### ISSUE TITLE
[CoE Starter Kit - QUESTION] Missing CenterOfExcellenceCoreComponentsTeams_x_x_x_xx_managed.zip component in latest download

### ISSUE THREAD

**Issue by davyderoeck** [microsoft/coe-starter-kit#4185]
### What is your question?

Hi CoE StartKit Team,

I'm trying to find the teams-core component as mentioned in the [MS Docs article](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components).
But when I'm downloading the latest version (https://aka.ms/CoeStarterKitDownload) and unpack this file, it seems the teams-core component is missing.
Is there another place I need to look to have this CenterOfExcellenceCoreComponentsTeams_x_x_x_xx_managed.zip solution file? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

latest?

**Comment by manuelap-msft** [comment]
Please see the note in this section: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#decide-what-environment-type-to-use-production-or-dataverse-for-teams

We are no longer investing in the Dataverse for Teams version of the CoE Starter Kit. You can download the latest available version here: https://aka.ms/CoEStarterKitD4T but it will no longer be included in current releases.

**Comment by davyderoeck** [comment]
thanks @manuelap-msft ! it's clear answer.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
