### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Report Not Showing Accurate Environment Information

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#4186]
### Describe the issue

We just renamed our default environment to personal productivity. We noticed that the Power BI report is showing a mix of applications with the old environment name and the new updated environment name.  We also noticed that one of the fields in the Power Apps Apps table is still reflecting the old environment name which still hasn't been updated. We have been experiencing this issue since we deployed our CoE version 3.39 to the latest November release.  It seems the admin_appenvironmentname is the column that has the correct value but the admin_appenvironmentdisplayname is still being referenced which happens to have the old not actual value. 

![image](https://user-images.githubusercontent.com/95443860/201941312-e5c702e4-1871-4f2e-a4bf-1836fe0eab43.png)

### Expected Behavior

Once default environment is renamed, the name should be updated in the next report refresh to reflect accurate environment information. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Power BI Nov Prod Report

### Steps To Reproduce

Open Report, Apps Overview

**Comment by manuelap-msft** [comment]
You might have to run a full inventory to update all the fields and get your data up to date:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#running-a-full-inventory

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
