### ISSUE TITLE
[Power Platform communication site template] ISSUE TITLE

### ISSUE THREAD

**Issue by samhms** [microsoft/coe-starter-kit#4189]
### Describe your bug, question or feature ask.

The deployment fails but still installed the site with the home page but nothing else.
![Screenshot 2022-11-15 114114](https://user-images.githubusercontent.com/112958956/201976732-53bdd626-ac56-4941-96c0-03699b3b351e.png)

**Comment by Laskewitz** [comment]
Hi @samhms - 

Sorry for the late reply. Can you please remove the site collection, then remove the site collection from the recycle bin and try again after you've done those things?

Thanks,
Daniel

**Comment by samhms** [comment]
Not possible anymore. We ended up deleting everything and rebuilding from scratch. Seems to work fine.

Sam Hourani
Cloud Solution Architect
Mobile: 514-994-4720
***@***.******@***.***>

[Microsoft Logo]

**Comment by Laskewitz** [comment]
Closing the issue since the rollout worked later on.
