### ISSUE TITLE
[CoE Components]: Desktop Flows sync hitting Dataverse/TDS result set limit 

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#419]
Desktop Flows sync template is hitting the Dataverse TDS buffer/result set limits in "List Desktop Flows" action. In Flow the error is "_Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600._'" and when testing the same query in SSMS we receive error "_Return records size cannot exceed 83886080. Make sure to filter result set to tailor it to your report._" indicating that query hit the TDS 80MB limit. 

![image](https://user-images.githubusercontent.com/8307644/119102259-7f294e80-ba22-11eb-8709-a5fb345f98b3.png)

The main issue seems to be clientdata column value returned which in my test returned about 13MB of data only for 1 desktop flow in the table. This would be easy to fix if the List Rows action of Dataverse (legacy) connector used in the flow offers support for selecting columns like the new Dataverse current env connector's List Rows action supports.

![image](https://user-images.githubusercontent.com/8307644/119087509-eee20e00-ba0f-11eb-9a66-d46bffbe4534.png)

**Component:**
 - Solution: Core
 - Version: at least 1.98 and newer
 - Admin | Sync Template v3 (Desktop flows)

**Comment by JeneferM-MSFT** [comment]
Hello, unfortunately you have discovered a flaw in our system that we cannot fix at this time. 
Today we use the Legacy connector to Dataverse as it allows us to select different environments to query, and the data for these is stored in each env in the tenant. And the new Dataverse connector does not yet let us pick which envt to query, always current. 
Unfortunately Legacy connector does not let us select which fields to bring back, and while we do not use this field, and could chose to not use it, we cannot chose to not bring it back with this connector. 
Connector team is making selection of envt available to the new Dataverse Connector and we will replat the suite to it for this sync flow and others that rely on it.
Until then this is a limitation in the toolkit.

**Comment by petepuu** [comment]
Thanks Jenefer! Yes that is what I was expecting and hope that possibility to select environment will be available soon in new Dataverse connector.

**Comment by Jenefer-Monroe** [comment]
We have an early release of this giant upcoming version of the kit. Please test for us! 
See this bug for build and how tos: https://github.com/microsoft/coe-starter-kit/issues/7322

**Comment by Jenefer-Monroe** [comment]
Fixed with Jan relesae.
