### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by hasanjamal21** [microsoft/coe-starter-kit#4193]
### Describe the issue

Unable to connect customer COE Starter KIT connecter 

### Expected Behavior

Unable to connect customer COE Starter KIT connecter 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.6

### What app or flow are you having the issue with?

COE Starter Kit

### Steps To Reproduce

Share Dev Envirenment

### Anything else?

COE 2.6

**Comment by manuelap-msft** [comment]
We'll need a little more information to help you here. 

What parts of our setup instructions did you follow, and where is it failing?

Here's the setup instructions for
Core components https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components
Audit Log https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
Pre-requisites https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup

Please share what steps you performed, and where you got a failure.

**Comment by hasanjamal21** [comment]
HI Team,

Using audit log, and unable to configure MS connecter.

Hasan Jamal Siddiqui (he/him)
Lead - SharePoint Online / Power Platform
Data & Information Management
Information Technology
Cell: 403.973.3012
***@***.******@***.***>
Calgary, Alberta
[Cenovus Energy]

**Comment by manuelap-msft** [comment]
Sorry it's really hard for us to provide any debugging information if you're not able to share further information about what steps you performed and what error message you are seeing. Please share some screenshots, and some more details about what steps are not working.

**Comment by manuelap-msft** [comment]
Closing out as did not hear back, not enough info to further triage.
