### ISSUE TITLE
[Power Platform communication site template] ISSUE TITLE

### ISSUE THREAD

**Issue by FurtureNinjaCoder** [microsoft/coe-starter-kit#4194]
### Describe your bug, question or feature ask.

The Deploy-PowerPlatformHub.ps1 errors out and says failed with: "PackageManagement\Install-Package : The following commands are already available on this system" and gives all the PnP commands.

**Comment by FurtureNinjaCoder** [comment]
This might have fixed: Install-Module -Name "PnP.PowerShell" -AllowClobber
but getting deployment of Power Platform Hub failed -no error searching to see what it might be.

**Comment by Laskewitz** [comment]
@FurtureNinjaCoder - Sorry for the late reply, have you rolled out the Power Platform communication site template successfully in the meantime?

**Comment by Laskewitz** [comment]
@FurtureNinjaCoder - It's been more than a week ago since the latest response. I hope it's fixed now and if not, please reopen the issue.
