### ISSUE TITLE
 The 'admin_user' column does not exist in the rowset. Table: Power Platform User.

### ISSUE THREAD

**Issue by Natashamg** [microsoft/coe-starter-kit#4196]
### Describe the issue

I get this error when I refresh the dataset in Power BI after the upgrade. 
The data in the CoE is not correct, it is missing a few flows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

CoE not giving accurate results

**Comment by manuelap-msft** [comment]
It looks like you're on an older version of the CoE kit - please upgrade to our November version
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2022

We recommend upgrading every three months:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup

**Comment by Natashamg** [comment]
So was this a bug with the previous release then? I recently upgraded to the October version.

**Comment by manuelap-msft** [comment]
It's not a bug we're aware of. But you can only use the matching dashboard with the matching release - e.g. you can use the November release dashboard with the November release Core components, the October release dashboard with the October release Core components. You can't use the November dashboard with a previous version of Core components.

If you're doing that, please share a little bit more about the bug you're seeing - could you share a screenshot and when it happens?

**Comment by Natashamg** [comment]
I did an upgrade of the core components to the latest version and I am using the Nov dashboard, but I still see some discrepancies in data shown in the CoE. There are flows that are being used frequently by a person, but it isn't showing up in the CoE. Is there anything else that can be done to fix this? There are around 5 flows made by one person and it isn't shown in the CoE, the apps made by the person show up though.

**Comment by manuelap-msft** [comment]
I see you've just raised a new issue for this, do you have two issues with the kit that we should triage or is it okay to close this issue and continue in the other one? 

If you have a second issue other than the missing flows, please describe it in a bit more detail here so we can follow up.

**Comment by Natashamg** [comment]
We can close this one, thank you!
