### ISSUE TITLE
[CoE Starter Kit - BUG] Maker Portal env var url set incorrectly (Admin - Environment Request email)

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#4198]
### Describe the issue

The link in the Email sent to the requestor saying that the environment is ready for use has a "/" missing between the .com and the word "environment"   The request comes back and says invaid url.
![image](https://user-images.githubusercontent.com/8484048/202164159-75d5be81-28a1-40b3-9186-00c3bb6461b5.png)

https://make.powerapps.comenvironments/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/apps

### Expected Behavior

I expect there to be a "/" between the words ".com" and "environment"so that when the linked is clicked, the user is taken to the c reated environment..

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

None

### Steps To Reproduce

Approve request for environment 
view resulting email that says Environment has been approved and provisioned.
Click on Link in email see issue.

**Comment by manuelap-msft** [comment]
This email uses the **PowerApp Maker environment variable** to put together the environment URL. We have to use an environment variable as government regions have different Maker Portal URLs. We ask that the environment variable value is set with the trailing slash - unfortunately environment variables don't support any kind of input validation:
![image](https://user-images.githubusercontent.com/55705669/202183807-8d26f7f8-13b2-47c0-895c-567ae69036b2.png)

You'll have to update the variable, and re-start the flows (they cache old values until they're turned off/on again)
https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables
