### ISSUE TITLE
Canvas app won't load in test environment

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#42]
Login to custom connectors fails:
![image](https://user-images.githubusercontent.com/4499296/93393388-71427e80-f840-11ea-8366-a028ae8800f9.png)
![image](https://user-images.githubusercontent.com/4499296/93393418-815a5e00-f840-11ea-9e5a-a3d9564f13c1.png)

**Comment by devkeydet** [comment]
Related to this issue documented here:
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/solutions-overview#known-limitations
![image](https://user-images.githubusercontent.com/4499296/94161257-7d879680-fe53-11ea-9673-f113842e9824.png)
A fix is in the works.

**Comment by mikefactorial** [comment]
@devkeydet I'm going to close this specific issue for now. I believe this is related to the discussion we've had about oAuth getting overwritten and will open a more specific issue for it.
