### ISSUE TITLE
[CoE Starter Kit - Question] Can we deploy the CoE solution using classic portal Or it has to be only deployed via modern portal?

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#420]
Hello,

This is regarding question on CoE starter Kit solutions deployment.

As we deploy the solution via Modern Portal, it asks for the required connections, while in classic portal this option is not available - Can you please help us if we can install/upgrade CoE solution classic portal? 

Thank you!

Regards,

**Comment by manuelap-msft** [comment]
Hello,

yes, solution import is supported using Classic Import mode. However, you will not be prompted for Environment Variables or Connection References during Import and will have to set them afterwards for the flows to turn on and work correctly. You will have to do this by going into the Default Solution of the environment and editing all Connection References related to the CoE Starter Kit to set an appropriate connection, and same for the Environment Variables. Our recommended approach is to use Modern Solution Import experience, as this reduces the manual effort of finding and updating connection references.

Thank you for using the CoE,
Manuela
