### ISSUE TITLE
[CoE Starter Kit - QUESTION] security role

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#4201]
### What is your question?

Hello!
Please tell me about the security roles for using CoEStarterKit.

I have the PowerPlatfrom administrator role for the import account.
For example, if I want other makers to use the app, which security role will I need (I would like to know about each app)?
Also, are there any apps that cannot be used without a PowerPlatfrom administrator?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

**Comment by manuelap-msft** [comment]
The CoE Starter Kit is shipped with custom security roles to give access to the custom tables that the kit comes with, e.g. the tables where your app and flow inventory is stored, or where customized emails that the kit sends are stored. 

Here's the security roles:
- Power Platform Admin SR Gives full access to create, read, write, and delete operations on the custom tables.
- Power Platform Maker SR Gives read and write access to the custom tables (environments, apps, and so on).
- Power Platform User SR Gives read-only access to the resources in the custom tables.

The kit contains apps for admins, makers, and end users - so each app has a different target persona. You can look at our documentation where each app is described for the permissions needed. Here's an example:

The Admin - Environment Request app:
![image](https://user-images.githubusercontent.com/55705669/202533360-169fa62e-35e8-4e10-b8d1-e2a0bd21f77b.png)
https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components#admin---environment-requests

The Maker - Environment Request app:
![image](https://user-images.githubusercontent.com/55705669/202533490-67e53d53-0a98-40aa-99b0-878e6daeffc8.png)
https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components#environment-requests

**Comment by egym07** [comment]
Thank you for the examples of specific security roles and apps.

I have one question.
Am I correct that "CoE Admin" in the permissions under "The Admin - Environment Request app:" is the same as Power Platform Admin SR?

**Comment by Jenefer-Monroe** [comment]
Sorry can you please share a screenshot of what you are referencing here?

**Comment by egym07** [comment]
Here it is.
https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components#admin---environment-requests
![image](https://user-images.githubusercontent.com/91306350/203298149-aca2f06a-67b4-4af0-be14-58485051e99c.png)

**Comment by egym07** [comment]
Let me ask a question along the same lines.
Which security role does the administrator alias here deserve?

https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components#flows-1
![image](https://user-images.githubusercontent.com/91306350/203299015-cc41e892-0196-4609-9362-7adaf8769ac8.png)

**Comment by Jenefer-Monroe** [comment]
ok there are a few things at play here

1. A group for the admin persona
Please see [How will you communicate with your admins, makers, and users?](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users)
This group, you enter into the **_Admin eMail_** environment variable at [setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values) 

2. A Security Role for that group to have access to CoE tables
This is the SR's that Manuela references. You would want to put the group mentioned above above into this Security Role

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
