### ISSUE TITLE
[CoE Starter Kit - BUG] Action 'Create__BPF' failed

### ISSUE THREAD

**Issue by wnzn** [microsoft/coe-starter-kit#4204]
### Describe the issue

Action 'Create__BPF' fails for SYSTEM user

Child flow 'Maker check - New' returns:
{
  "userisorphan": "False",
  "userissystem": "True",
  "userisserviceprinciple": "False",
  "usercompany": "",
  "userdepartment": "",
  "userdisplayname": "SYSTEM",
  "usercity": "",
  "usercountry": "",
  "userpreferredlanguage": "",
  "userid": "",
  "useremail": "",
  "usermanagerid": "",
  "usermanagername": ""
}

Dataverse action 'Create BPF' then fails because admin_makers(userid) has an empty string for userid value.
{
  "error": {
    "code": "0x8006088a",
    "message": "The supplied reference link -- admin_makers() -- is invalid. Expecting a reference link of the form /entityset(key)."
  }
}

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Business Process Flows)

**Comment by wnzn** [comment]
Same behavior with Admin | Sync Template v3 (Ai Models).

**Comment by Jenefer-Monroe** [comment]
Hello, thanks for posting. Does your **_HELPER - Maker Check_** flow show this scope to et the system user id? 
![image](https://user-images.githubusercontent.com/89584709/203092931-aab500d6-25a2-472d-a68e-89a7bf272004.png)

**Comment by wnzn** [comment]
It does not.

**Comment by Jenefer-Monroe** [comment]
ok that means that you have an unmanaged layer on the helper flow then. Please [remove the unmanaged layers](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) and then it should work for you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
