### ISSUE TITLE
[CoE Starter Kit - BUG] Helper - Maker Check flow disabled after update to 3.56 (graph variable doesn't appear to be the issue)

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [microsoft/coe-starter-kit#4209]
### Describe the issue

After updating to 3.56 yesterday, I noticed a number of Admin | Sync template errors involving what appeared to be the Helper - Maker Check flow, specifically "WorkflowTriggerIsNotEnabled".  I checked and saw that the flow had not been re-enabled after the update.  I can confirm the Graph variable is set and I was able to turn it on manually.  I just wanted to report this in case others may be seeing the same thing.

### Expected Behavior

Flows should re-initialize after update.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Helper - Maker Check

**Comment by manuelap-msft** [comment]
There could be multiple reasons why a flow can't be turned on on solution import - sometimes it's billing policies, data loss prevention policies, other pre-requisites not being met, and sometimes it's just temporary service issues on import as the Core components solution is very large. 

We do ask in our setup instructions to always check and make sure all child and setup flows are turned on:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-child-flows

**Comment by DaveTheTeamsGuy** [comment]
Ok sounds good - I just wanted to submit this issue in case others were seeing the same.  Maybe worth adding that to the upgrade instructions as well.
