### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by RakeshPower** [microsoft/coe-starter-kit#4213]
### Describe the issue

Power BI Dashboard unable to show any report. Data is missing. Attached is the screenshot
![image](https://user-images.githubusercontent.com/115120204/202318565-d18a1793-e93b-4506-9c90-a9ae5444ba1d.png)

Could someone please let us know what is missing here. COE version in our environment is 3.39
and Dashboard is "Production_CoEDashboard_November2022"

Regards,
-Rakesh

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Power BI Dashboard

### Steps To Reproduce

Open "Production_CoEDashboard_November2022" file and entre organization URL, after that no reports been pulled over and system is throwing error as "Loading Blocked by failure with other queries"

However, same stats available in model driven app " Power Platform Admin View". not sure why it is not being pulled over to Power BI Dashboard.

**Comment by RakeshPower** [comment]
Hi, it seems like issue is similar to https://github.com/microsoft/coe-starter-kit/issues/3659
after editing the power Query by removing admin_recordguidasstring column field.
Could you please share url to download correct version of power BI report PBIT file that will work with COre Solution release "3.39"

**Comment by manuelap-msft** [comment]
You can only use the matching dashboard with the matching release - e.g. you can use the November release dashboard with the November release Core components, the October release dashboard with the October release Core components. You can't use the November dashboard with a previous version of Core components.

3.39 was our June release which you can find here https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-June2022

Please note, we do recommend upgrading the CoE kit every 3 months to stay up to date and avoid issues: https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup

**Comment by RakeshPower** [comment]
Thanks, that was the case, will wait for Dec release as it will have CoE Wizard,
