### ISSUE TITLE
[CoE Starter Kit - BUG] Shared with info not showing

### ISSUE THREAD

**Issue by samhms** [microsoft/coe-starter-kit#4214]
### Describe the issue

Shared users not showing.
When looking at the users that an app was shared with, I'm expecting them to show up, but I can only see the Owner.
The table where that data is hosted is "Power Platform User Role".

### Expected Behavior

Share a canvas app and add the person as a co-owner
See that co-owner in the PP Admin view model driven app.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.45

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

Access the Power Platform Admin View
Navigate the PowerApps Apps tab
Select the General tab there
Scroll down to SHARED WITH
Find the co-owner in question

**Comment by manuelap-msft** [comment]
It's the **CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)** that collects this data. Is this flow on and running without failure?

**Comment by samhms** [comment]
It is on and has run successfully more than a week ago. (It is possible that the sharing has been done after that flow run.)
I tried to run it manually today by entering the tenant ID and it failed at the last step (Respond to a PowerApps or Flow).
Is that Flow meant to run only by getting trigger by another one? If yes, what is the Flow responsible of triggering it?

**Comment by Jenefer-Monroe** [comment]
Hello there are two flows of interest: 

**_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_**
Which does not have an input parameter, and runs every two weeks. 

**_CLEANUP HELPER - Power Apps User Shared With_**
Which takes in an Environment, not a Tenant, and is called from the flow above. 

So if something is shared it will not show up in the **_Power Platform Admin View_** app until these flows run again, which could be up to two weeks away.

**Comment by Jenefer-Monroe** [comment]
Note also that the work to collect shared with does not work for Model Driven Apps or Sharepoint Form Apps.
