### ISSUE TITLE
Flows missing in CoE

### ISSUE THREAD

**Issue by Natashamg** [microsoft/coe-starter-kit#4228]
### Describe the issue

I have upgraded the CoE to the latest version along with the dashboard, but I still see that some flows are missing and not showing up in the CoE. I've checked in Power Platform Admin view and don't see it there either. Any idea if I am missing something?

### Expected Behavior

Flows from all environments should be visible in the CoE.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

CoE results

### Anything else?

Any idea if I am missing something?

**Comment by manuelap-msft** [comment]
First lets see if there is a generalized problem

1. Make sure that the identity running the flows has all the correct permissions and that those permissions are assigned permanently. [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

2. Look to make sure all flows in the [inventory setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) are turned on

3. Look for failures in the inventory runs via the Sync Flow Errors mail or in the Admin - Command Center
![image](https://user-images.githubusercontent.com/89584709/192275360-483f2240-76dd-4b63-8be0-34171831439c.png)

**Comment by manuelap-msft** [comment]
If this does not work, then you will need to find a repro of this in your tenant to see what is going wrong. 

1. Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field (you can just enter some text somewhere), and save. Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you are looking for missing flows chose **_Admin | Sync Template v3 (Flows)_**
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

5. From here you can explore if there is a failure, or if a bad return set, etc. And if there are failures, share those with us.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
