### ISSUE TITLE
Admin | Sync template v3 fails in last November update

### ISSUE THREAD

**Issue by GaboVillayzanC** [microsoft/coe-starter-kit#4229]
### Describe the issue

I just upgraded my CoE solution and notice that this flow is failing. Looks like the flow is trying to reach some environments and cant continue. I verified that those environment IDs exist in the tenant. However the flows continue failing.

![image](https://user-images.githubusercontent.com/118485023/202562339-58e8a9ac-3c2e-4c08-b88d-bbd7ef4421b6.png)

![image](https://user-images.githubusercontent.com/118485023/202562366-6c44f58e-0d54-4eaa-abec-fad0c3bb4540.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync template v3

**Comment by Jenefer-Monroe** [comment]
As a result you need to continue to dive down in to the flow until you find the spot where it fails and terminates.
![image](https://user-images.githubusercontent.com/89584709/203099160-b6941b8d-407f-4567-84cc-e1adad65a6ff.png)

Please let us know what you find when you do that.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
