### ISSUE TITLE
[Child] Admin | Sync Logs fails when starting

### ISSUE THREAD

**Issue by tsegato** [microsoft/coe-starter-kit#4232]
### Describe the issue

When I start the [Child] Admin | Sync Logs it fails with:

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'WorkflowOperationParametersExtraParameter' and message 'The API operation does not contain a definition for parameter 'item/----scrubbed----'.'."}}".

I suspect it is related to following not having the option os using owner connection, but not sure. Anyone have any idea on how to trouble shoot this?

![image](https://user-images.githubusercontent.com/43033640/202647116-178ae4d9-97da-42ff-8156-6e0f145c3613.png)

![image](https://user-images.githubusercontent.com/43033640/202647164-20190a78-c2d5-4b24-8f62-df97a8dc265d.png)

### Expected Behavior

Flow will start successfully and collect audit logs

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
We've seen a few people hit this lately. There seems to be a product bug at play. A few things that have resolved it for others
- turning the flow off and back on to clear whatever is cached
- recreating the Dataverse connection used in the flow

**Comment by tsegato** [comment]
The error comes when trying to turn on the flow. So cannot turn it off. If you recreate the dataverse connection, wont that affect the entire CoE starter kit, and I would have to reconnect it on all flows?

**Comment by Jenefer-Monroe** [comment]
It could have that impact yes, especially for other places you have to select run only permissions. Perhaps just try to create a new one and see if it shows up. 
Sorry this is just a product bug so I can only offer advice of how to get around it.

**Comment by tsegato** [comment]
Thanks @Jenefer-Monroe. Is it even possible to recreate it as it is a managed solution? See the edit button is not enabled:

![image](https://user-images.githubusercontent.com/43033640/203632761-e8020f15-f2de-4f6c-8e76-dac893e0ff58.png)

**Comment by Jenefer-Monroe** [comment]
What I meant is that if you create a new connection, not a new connection reference. 
![image](https://user-images.githubusercontent.com/89584709/204105740-808f47f4-f630-4d05-93c7-140e8a2549ba.png)

As an aside, to edit a connection reference you have to go to the Default envt. 

I'm afraid you've hit a product bug here, if these ideas dont work for you, you may have to contact product support.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
