### ISSUE TITLE
[CoE Starter Kit - Admin - Access this App] Not able to view the App

### ISSUE THREAD

**Issue by BabyMukthi** [microsoft/coe-starter-kit#4233]
### What is your question?

Not able to view the App(Admin - Access this App), Getting below error after COE Update.

PowerAppsforAdmins.GetAdminAppRoleAssignment failed: { "error": { "code": "BusinessAppPlatformRequestFailed", "message": "The request failed with client error: 'The environment '' could not be found in the tenant 'fbe62081-06d8-481d-baa0-34149cfefa5f'.'. The correlation Id is 'd4537502-9cfd-473f-85d9-1558c5c0b7eb'.", "details": [ { "code": "MultipleErrorsOccurred", "message": "Multiple errors occurred. Please see details.", "details": [ { "code": "EnvironmentNotFound", "message": "The environment '' could not be found in the tenant 'fbe62081-06d8-481d-baa0-34149cfefa5f'." } ] }, { "code": "FullNonLocalizedError", "message": "{\"error\":{\"code\":\"EnvironmentNotFound\",\"message\":\"The environment '' could not be found in the tenant 'fbe62081-06d8-481d-baa0-34149cfefa5f'.\"}}" } ] } }

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Novermber 2022

### What app or flow are you having the issue with?

Admin - Access this App

**Comment by manuelap-msft** [comment]
This app is only available after embedding it in the Power BI dashboard:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard
