### ISSUE TITLE
Microsoft power automate "Send an mail notification V3" stopped sending email suddenly

### ISSUE THREAD

**Issue by Sishira** [microsoft/coe-starter-kit#4237]
Hi Team,
Microsoft power automate "Send an mail notification V3" stopped sending email suddenly. Is this a known issue the Engineering team is working on?

![image](https://user-images.githubusercontent.com/99423817/202755938-f23e2280-bdb6-43cf-8d3e-94d40113c422.png)

**Comment by manuelap-msft** [comment]
Hello,

this repo is for issues related to our [CoE Starter Kit and ALM Accelerator](https://aka.ms/coestarterkit) solutions. For any product related issues, please do raise them through your usual Microsoft Support channels: https://learn.microsoft.com/en-us/power-platform/admin/get-help-support

**Comment by pavillag** [comment]
Hi - Can we submit a request to make a "connector status" (up or down) visible to customers/people that use that connector in a Power Automate flow or in a Power App?
