### ISSUE TITLE
[CoE Starter Kit - BUG] PowerPlatformCOEDashboard Showing wrong data under environments

### ISSUE THREAD

**Issue by kashanico** [microsoft/coe-starter-kit#4243]
### Describe the issue

In the Power BI report PowerPlatformCOEDashboard if you go to Environments the total count for environments is bugged as it displays the same number for all environment types.

![image](https://user-images.githubusercontent.com/64927104/203185828-ddb813db-b674-4a3c-9184-50c43e69b59c.png)

### Expected Behavior

The numbers need to add up correctly in dashboard

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November2022

### What app or flow are you having the issue with?

power bi report

### Steps To Reproduce

1. Open Power BI report PowerPlatformCOEDashboard 
2. Go to Environments tab

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. I dont repro so can you please tell me:
1. Did you recreate the PBI with the Nov version? Production_CoEDashboard_November2022
2. Select the Teams one for example, do you see the filter correctly on the visual?
![image](https://user-images.githubusercontent.com/89584709/203309355-ea36113b-0457-41f3-b63f-89cb9a75c4a8.png)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
