### ISSUE TITLE
[ALM Accelerator - BUG]: Deployment fail in InvokePowerAppsChecker by DeprecationWarning: Buffer() 

### ISSUE THREAD

**Issue by rsantos00** [microsoft/coe-starter-kit#4245]
### Describe the issue

Upon deployment of the solution fails in the CheckSolution Steps, here is the logs:

[ 'Executing InvokePowerAppsChecker' ]
[ 'Upload started : 1 files' ]
[ 'Uploaded finished: 1 files taking 00:00:01.3453826' ]
[ 'Calling status check API. Loop count 1' ]
[ 'Finished calling status check API. Loop count 1' ]
[ '... Activity Waiting on results(1); Status: Analyzing; PercentComplete: 30' ]
[ 'Pausing for 30 seconds.' ]
[ 'Calling status check API. Loop count 2' ]
[ 'Finished calling status check API. Loop count 2' ]
[ '... Activity Waiting on results(1); Status: Analyzing; PercentComplete: 100' ]
[ 'Downloading 1 files to D:\\a\\1\\a\\PowerAppsChecker\\checker-output' ]
[ 'Finished downloading 1 files' ]
[ 'Exiting with Finished InvokePowerAppsChecker - EndProcessing : 00:00:31.9386689' ]
[ '' ]
[ 'Checker results:' ]
[ '\tFiles: 20221122104114_DLCIdee10202211223.zip' ]
[ '\tCorrelation Id: a6d555f1-d07f-4bea-9442-253fd387ad04' ]
[ '\tStatus: Finished' ]
[ '' ]
[ '' ]
[ ' Critical High Medium  Low Informational ' ]
[ '' ]
[ '        0    1     110   0             0' ]
[ '' ]
[ 'CheckSolution Action Result: ,Endpoint: https://europe.api.advisor.powerapps.com/,,Checking these solution files:,,- D:\\a\\1\\a\\DLC_Idee_1.0.20221122.3.zip,Entering InvokePowerAppsChecker - EndProcessing,Executing InvokePowerAppsChecker,Upload started : 1 files,Uploaded finished: 1 files taking 00:00:01.3453826,Calling status check API. Loop count 1,Finished calling status check API. Loop count 1,... Activity Waiting on results(1); Status: Analyzing; PercentComplete: 30,Pausing for 30 seconds.,Calling status check API. Loop count 2,Finished calling status check API. Loop count 2,... Activity Waiting on results(1); Status: Analyzing; PercentComplete: 100,Downloading 1 files to D:\\a\\1\\a\\PowerAppsChecker\\checker-output,Finished downloading 1 files,Exiting with Finished InvokePowerAppsChecker - EndProcessing : 00:00:31.9386689,,Checker results:,\tFiles: 20221122104114_DLCIdee10202211223.zip,\tCorrelation Id: a6d555f1-d07f-4bea-9442-253fd387ad04,\tStatus: Finished,,, Critical High Medium  Low Informational ,,        0    1     110   0             0,' ]
(node:2104) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
##[error]failed: Analysis results do not pass with selected error level and threshold choices.  Please review detailed results in SARIF file for more information.
[ 'Authentication profiles and token cache removed' ]
[ 'The Clear Authentication Result: Authentication profiles and token cache removed' ]
##[error]Error: Analysis results do not pass with selected error level and threshold choices.  Please review detailed results in SARIF file for more information.
Async Command Start: Upload Artifact
Uploading 1 files
File upload succeed.
Upload 'D:\a\1\a\PowerAppsChecker\results' to file container: '#/18610580/PowerAppsChecker'
Associated artifact 36201 with build 75316
Async Command End: Upload Artifact
Finishing: Run Solution Checker

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

November

**Comment by mikefactorial** [comment]
If this is a false positive you can disable solution checker by setting a pipelines variable either on the pipeline or in the variable group with DisableSolutionChecker = 'true'. However, chances are this is a valid issue that solution checker is reporting

**Comment by mikefactorial** [comment]
@rsantos00 doesn't look like there's an action item for us on this. The solution checker is just reporting what it's finding in the solution. If the error it's reporting is somehow inaccurate or incorrect then we'd have to bring this up to the product team responsible for Solution Checker, but this isn't an ALM Accelerator issue.
