### ISSUE TITLE
[CoE Starter Kit - BUG] Not all apps visible in Admin - App Permission Center

### ISSUE THREAD

**Issue by LagerquistSara** [microsoft/coe-starter-kit#4246]
### Describe the issue

In the "Admin - App Permission Center", I have three environments (dev, test and prod) where I expect to see a MDA, but all I see is "DefautlCommandLibrary (which is the app that is created to save command bar settings).

There don't show under orphaned app tab either.

### Expected Behavior

I expect to see all apps in my environment, including the MDAs.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin - App Permission Center

### Anything else?

My PROD-environment for my MDA is a pay-as-you-go.
My Dev and TEST are not PAYG.

My apps are deployed with solutions.
My apps use a custom connector.

My apps all had another owner previously who have left the company. 
When I look into Power Platform Admin View I see that my app in Dev are orphanded. But I see that in Dev and Prod I am the owner.

**Comment by LagerquistSara** [comment]
That explains A LOT! 😂 Thank you, been trying to read myself into this but so much content so I got lost :)

**Comment by Jenefer-Monroe** [comment]
yes its true there is a LOT to read. And we dont mind answering questions at all, that's why we're here :)
Thanks for the update!
