### ISSUE TITLE
[ALM Accelerator - BUG]: 'UpdateProjectSettings' has an invalid value for parameter 'project'

### ISSUE THREAD

**Issue by kinwong7** [microsoft/coe-starter-kit#4252]
### Describe the issue

After I used "Project Wizard" function to create a project in DevOps, the next step is to create pipeline templates. If I select existing project hosting pipeline templates, there is error said: 
"**CustomAzureDevOps.UpdateProjectSettings failed: The method 'UpdateProjectSettings' has an invalid value for parameter 'project', Observed: btnProjectWizardConfigureTemplates_1.OnSelect, Source: btnProjectWizardConfigureTemplates_1.OnSelect**"

![image](https://user-images.githubusercontent.com/29238122/203358412-a084a39c-5719-4353-b023-c150b16dac8d.png)

It is fine if I checked the checkbox "Install into new coe-lam-accelerator-templates repository".

### Expected Behavior

There should be no error and allow to go to next step.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20221101.1

**Comment by jenschristianschroder** [comment]
@kinwong7 thank you for reporting this. Will look into this and update this issue when relevant.

**Comment by jenschristianschroder** [comment]
@kinwong7, can you please check if the project that you created on step one of the wizard has been created correctly in Azure DevOps?
Not the SharePoint Solutions project but the project you are creating using the wizard in the screen shot you shared.

The wizard should have created the project before you reach the second step of the wizard. The error could indicate that something went wrong when creating the project.

**Comment by kinwong7** [comment]
@jenschristianschroder , the project was successfully created before I went into step 2 "Pipeline Templates".
![image](https://user-images.githubusercontent.com/29238122/203834856-94b468e1-1b20-4a8f-9bfc-481261390385.png)

I just want to simulate it again, but today, I got a different error message, "The setting for the selected Organization prevents the use of templates in external project. Ask your Azure DevOps administrator for help".  Should I change some setting?
![image](https://user-images.githubusercontent.com/29238122/203835180-0e38fa05-8eab-4758-80c9-e8fa597039af.png)

**Comment by jenschristianschroder** [comment]
@kinwong7, this message means that the organizational settings in your devops org prevent referencing files between projects.

In order to allow this you should first go to your organizational settings and disable "Limit job authorization scope to current project for non-release pipelines"
![image](https://user-images.githubusercontent.com/24893229/203837093-1e49ff9e-fa22-4a6a-983e-b202deec10b3.png)

After that, because your SharePoint Solution project was created, you should also ensure that the same settings is disabled in your project settings for SharePoint Solution project

**Comment by kinwong7** [comment]
@jenschristianschroder , thanks for the information.  I don't see the error and can create the pipelines from the template in another project.  I can't recreate the original error message, but I'm pretty sure the error message was I clicked "Next" in step 2 "Pipeline Templates".
