### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 CoE Solution Metadata failing

### ISSUE THREAD

**Issue by waiholiu** [microsoft/coe-starter-kit#4255]
### Describe the issue

This flow has suddenly started failing on my COE environment since the 20th November - it was working fine before this. Also, after doing an update to latest version of COE at a client site today, and this flow also failed to run.

Error I'm getting is `"The 'inputs.parameters' of workflow operation 'Update_Last_Run_Successful' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'"`

Please see screenshot below

<img width="289" alt="image" src="https://user-images.githubusercontent.com/8047097/203473689-6676b45d-c40b-408b-8c46-aabd7e8899a8.png">

On inspection, it looks like the card "Get ID Pass" is not actually returning any value because the id returned from `workflow()?['name']` does not exist in the CoE Solution Metadata table. 

Please see screenshot. The ID highlighted in yellow does not exist in the COE Solution Metadata table

![image](https://user-images.githubusercontent.com/8047097/203474338-a73743ad-8fbe-4429-8d53-98f3b03df8ce.png)

### Expected Behavior

the flow should run

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Sync Template v3 CoE Solution Metadata

### Steps To Reproduce

1. Turn  Sync Template v3 CoE Solution Metadata on
2. Run flow

**Comment by madhavjaya** [comment]
Will that effect the data coming into the PowerBI dashboard. Does it take 15 hrs to reflect in the dashboard?

**Comment by madhavjaya** [comment]
What is the impact of this not working to the overall COE toolkit.

**Comment by manuelap-msft** [comment]
We are still investigating the broader impact of this change with the Power Automate team.

**Comment by madhavjaya** [comment]
Any turnaround times will be much appreciated.

**Comment by waiholiu** [comment]
> A product change happened that meant Flow GUIDs are now returned differently than what the CoE Kit expects. We're working with the product group on a path forward.

thanks Manuela - great to see the COE team already on top of it.

For clarification, is my understanding correct in that the `workflow()?['name']` command is now returning something different and this is why it's broken? Not sure if it helps but I also took a peek at the previous runs where it was successful, and was surprised to find that even those runs were still filtering on the same id. This indicates to me that possibly there might have been a row with that guidobject in the COE Solution Metadata table previously but has now been deleted?

![image](https://user-images.githubusercontent.com/8047097/203657384-96de2550-8fd6-44f9-88ab-6b53538b58d9.png)


I also wanted to ask in case my customers ask me  - do we know how widespread this bug is? Is COE Solution Metadata failing for every installation of COE? Is it just certain versions where this is breaking? Will it break for new installations?

**Comment by manuelap-msft** [comment]
Hello,

unfortunately, a planned change to how Power Automate flows are identified has started rolling out. Basically, the change assigns a new GUID (unique ID) to all solution aware flows. The CoE kit relies on IDs being unique over time so this change has caused disruption and error to the CoE kit. 

The change reached stations 1-3
![image](https://user-images.githubusercontent.com/55705669/203813112-80beec8d-6a92-412c-b6cb-d3b826a86141.png)

The change has been halted now, so will not reach further stations (Europe and North America) so customers in those regions will not be impacted. However, for customers in regions that are impacted we are still investigating what to do next. Unfortunately, this change is not something we were aware of happening and something that was out of our control, so we have some work to do now to see how we can work with the new IDs.

This has nothing to do with a bug in the CoE kit or a specific version of the CoE kit - it's a change that rolled out to the Power Automate product, the CoE kit as it is built on top of the platform is subject to platform changes and thus impacted by changes to Power Automate. 

Currently, I believe the impact is isolated to Stations 1-3 from above. Existing installations and upgrades here will fail. New installations should work.

**Comment by Jenefer-Monroe** [comment]
If you are in one of the stations in red below, then between November 15th and November 23rd, the flow product team rolled a change which modified the name (the GUID) for solution flows. This had several side effects including failure of some CoE flows (ex Admin | Sync Template v3 CoE Solution Metadata), duplicate entries of other flows, and potentially loss of metadata (ex compliance information) about those flows. 

Other than the loss of the metadata, this will all correct itself now as flows continue to run including the CLEANUP - Admin | Sync Template v3 (Check Deleted) flow. 

Sorry for the inconvenience.

![image](https://user-images.githubusercontent.com/89584709/204932599-08112a90-8a81-4682-b9d5-12476299838d.png)

**Comment by Jenefer-Monroe** [comment]
ok im installing in Europe to see what you are seeing.
