### ISSUE TITLE
I'm trying to deploy Admin | Sync Template v3 CoE Solution Metadata and get error

### ISSUE THREAD

**Issue by madhavjaya** [microsoft/coe-starter-kit#4257]
The 'inputs.parameters' of workflow operation 'Update_Last_Run_Successful' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/93354778/203524962-b6ff81f0-9b1c-4c28-af0c-3b7cc33d00de.png)

**Comment by manuelap-msft** [comment]
Hello,

unfortunately, a planned change to how Power Automate flows are identified has started rolling out. Basically, the change assigns a new GUID (unique ID) to all solution aware flows. The CoE kit relies on IDs being unique over time so this change has caused disruption and error to the CoE kit. 

The change reached stations 1-3
![image](https://user-images.githubusercontent.com/55705669/203813112-80beec8d-6a92-412c-b6cb-d3b826a86141.png)

The change has been halted now, so will not reach further stations (Europe and North America) so customers in those regions will not be impacted. However, for customers in regions that are impacted we are still investigating what to do next. Unfortunately, this change is not something we were aware of happening and something that was out of our control, so we have some work to do now to see how we can work with the new IDs.

**Comment by Jenefer-Monroe** [comment]
If you are in one of the stations in red below, then between November 15th and November 23rd, the flow product team rolled a change which modified the name (the GUID) for solution flows. This had several side effects including failure of some CoE flows (ex Admin | Sync Template v3 CoE Solution Metadata), duplicate entries of other flows, and potentially loss of metadata (ex compliance information) about those flows. 

Other than the loss of the metadata, this will all correct itself as flows continue to run including the CLEANUP - Admin | Sync Template v3 (Check Deleted) flow. 

Sorry for the inconvenience.

![image](https://user-images.githubusercontent.com/89584709/204932599-08112a90-8a81-4682-b9d5-12476299838d.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
