### ISSUE TITLE
Admin | Sync Template v3 (Flows) Fails admin flow not found

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#4259]
When running Overnight run of admin Flows - I wake up in the morning to a failure in Admin | Sync Template v3(Flows) - admin flow no found - 
![image](https://user-images.githubusercontent.com/8484048/203547344-5779fc1c-1141-49fc-b518-639066815c14.png)

**Comment by Jenefer-Monroe** [comment]
This is the call we do to see if the object is already in the inventory, its an error we catch to say "new to coe"
You can see this as below the next action is a variable doing just that. 

You will need to go further down in the flow to find the source of the failure.

**Comment by NPrice99** [comment]
![image](https://user-images.githubusercontent.com/8484048/203561324-29a395c0-4d2e-49e9-8c1e-954cab76bc0d.png)

**Comment by Jenefer-Monroe** [comment]
What version of Core are you on? We switched this casll to the **_Maker Check_** helper flow
![image](https://user-images.githubusercontent.com/89584709/203569388-fbedfc2b-0b53-405d-9a14-5143949e31b9.png)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
