### ISSUE TITLE
[CoE Starter Kit - QUESTION] modify outlook connector and related upgrade issue?

### ISSUE THREAD

**Issue by CDSSYW** [microsoft/coe-starter-kit#4261]
### What is your question?

Hi !
We are on the waying deploying the CoE kit core component, and found the outlook connector is mandatory when importing, 
currently the outlook connector is disabled from company policy, the questions are:

1. Is it a way to modify the connector without having deploying it ? 

(Or we can only modify the flow and connector when the package is deployed in an environment, and edit it from there?)

2. If the outlook connector is successfully removed, and the flow is modified according to custom needs, can the modified solution able to be updated in the future? what's the proper way to update the customized CoE component?

thanks in advance for your reply!!

**Comment by Jenefer-Monroe** [comment]
I'm afraid we do not have a solution for you here for running the kit without the ability to use outlook. However you can install it using the classic ux for install as that skips the connection references. From here you could explore the kit and get an idea of how you might recreate something similar for your needs without that connector. 

### How to get to classic ux for install
![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png)
![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)

**Comment by CDSSYW** [comment]
Hi,

Thanks for the prompt reply, as for 2nd question, I've checked doc https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components, still having question:

If the outlook connector is successfully removed, and some flows are modified according to custom needs, I understand the modified flow won't receive updates but remain customized version, but can the rest of the core components receive updates?

**Comment by manuelap-msft** [comment]
Hello,

1. Yes, you will be able to continue upgrading the Core components solution. Anything you have modified that has an unmanaged layer will not receive an upgrade, however other components will still receive updates. 
2. If you are making customizations, we do recommend following an ALM (application lifecycle management) process and having a dev test and production environment in place for you to test your changes and ensure any updates don't break production scenarios.

**Comment by CDSSYW** [comment]
Hi Manuela,

Thanks for the reply, 
Concerning question 2, 

1. I assume following the best practice,  the update will only happend at coe dev env, correct? 
2.  is it recommended to create **sandbox type** of env for coe dev and coe test? 
3. I imagine for coe test , I will need to setup small test groups for user and maker persona, then follow the setup process as in coe prod env?
![image](https://user-images.githubusercontent.com/117460925/203809421-abc27da3-4744-4937-84f9-6c7de81ef4a6.png)

**Comment by CDSSYW** [comment]
> I'm afraid we do not have a solution for you here for running the kit without the ability to use outlook. However you can install it using the classic ux for install as that skips the connection references. From here you could explore the kit and get an idea of how you might recreate something similar for your needs without that connector.
> 
> ### How to get to classic ux for install
> ![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png) ![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)

I skipped the connection request by using classic UX, however I would like to run the non-outlook related flows, when I trun on the flow, it shows lacking connection reference, I've added all required connection refs at CoE env, but apparently it requires the 2nd layer to confirm the connection refs if I want to run the flow, I noticed I cannot change the connection ref property,is there a way to achieve linking the connection refs after skipping it during the import?

**Comment by CDSSYW** [comment]
> Hi Manuela,
> 
> Thanks for the reply, Concerning question 2,
> 
> 1. I assume following the best practice,  the update will only happend at coe dev env, correct?
> 2. is it recommended to create **sandbox type** of env for coe dev and coe test?
> 3. I imagine for coe test , I will need to setup small test groups for user and maker persona, then follow the setup process as in coe prod env?
>    ![image](https://user-images.githubusercontent.com/117460925/203809421-abc27da3-4744-4937-84f9-6c7de81ef4a6.png)

Thank you, I've fix the references from default solution!! and regarding these questions, do you have any insights, please?

**Comment by CDSSYW** [comment]
> I'm afraid we do not have a solution for you here for running the kit without the ability to use outlook. However you can install it using the classic ux for install as that skips the connection references. From here you could explore the kit and get an idea of how you might recreate something similar for your needs without that connector.
> 
> ### How to get to classic ux for install
> ![image](https://user-images.githubusercontent.com/62659043/129362010-9e4f4b2a-ff0d-4719-b122-ede84bf0ff15.png) ![image](https://user-images.githubusercontent.com/62659043/129362096-1db7e359-49e3-4a92-af1d-040f5ee379d0.png)

Hi ,

Still facing issue after skipping the outlook connector, I would like to edit the outlook related flow in Coe Dev env from a new unmanaged solution (goal is to remove this connection), however, it always force me to login with outlook (while it's not possible), is it a way to skip the connection part and edit the managed flow ?

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont know how to assist here. Support may be able to provide some ideas. But we are a very small team and so arent staffed to assist with customizations.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
