### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Starter Kit doesn't show Default environment update

### ISSUE THREAD

**Issue by GaelCasOuv** [microsoft/coe-starter-kit#4262]
### Describe the issue

Hello we updated the name of the Default environment but most of the apps appear as belonging to the Default environment with the old name, surprisingly the environment does appear also with the new name but very few apps appear into it.

The only page in the Dashboard that seems to be correct is the "Environments" one.

I followed these steps I found in Powerusers forum to update the inventory but it hasn't solved the issue:

1. Set the value of the Full inventory environment variable to Yes (Learn more: [update environment variables](https://docs.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables)).
2. Turn all flows in the core solution off and back on.
3. Run the Admin | Sync Template v3 flow manually - this will kick off all the other sync flows, wait for all of them to finish. Like the Sync template (Apps) and Sync template (Flows) will take the longest but this depends on the size of your inventory. Wait for all those to finish.
4. Then set the Full inventory environment variable back to No.
5. Turn all flows in the core solution off and back on.

Thank you for your help

### Expected Behavior

The CoE Starter kit should show the correct information when the Default name has been changed.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

PowerBI Dashboard

**Comment by Jenefer-Monroe** [comment]
Can you please do the following for me? 
1. Ensure you have refreshed the PBI report (if in the browser be sure to update the dataset)
2. Share a screenshot of where in the report you are seeing things incorrectly?

**Comment by GaelCasOuv** [comment]
Hi Jenefer, it has been solved. Apparently, we only had to wait a bit more for the flows to finish.
Thank you very much for your help.

**Comment by manuelap-msft** [comment]
Thanks for the confirmation! Glad to hear it's working now
