### ISSUE TITLE
[CoE Starter Kit - BUG] :Power Platform Admin View App-DLP policies not visible

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4265]
### Describe the issue

Hi 

Question 1 :

When we open ---->Power Platform Admin View App--->Environments---->Select any environment---Goto Related Tab--->DLP Policies.
In this DLP Policies, we could not see the associated DLP policies that were configured for environment, but DLP policy is configured for the environment.
Also, the DLP Policy table looks empty.

Could you please help, what are we missing here?
Do we need to run any flow to get data here?

![Dlp Policy Screen](https://user-images.githubusercontent.com/29652263/203709256-729acb05-3dad-4441-9dda-dea2e7bd4bd7.JPG)
![DLP table](https://user-images.githubusercontent.com/29652263/203709464-b6e689ce-b77b-4694-b7e2-d37b843f629b.JPG)

Question 2

In DLP Editor App , 

There are two types 
1. General 
2. Blocked
![Dlp2](https://user-images.githubusercontent.com/29652263/203710671-7c9b4fdc-e208-43a4-9b3d-f5549706d17d.JPG)
In which scenario, we can see the type "Blocked" against a dlp policy attached screenshot for reference

### Expected Behavior

Should be able to see DLP policy for environment in power platform admin view app

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Power Platform Admin View App

### Steps To Reproduce

---->Power Platform Admin View App--->Environments---->Select any environment---Goto Related Tab--->DLP Policies.
In this DLP Policies, we could not see the associated DLP policies that were configured for environment, but DLP policy is configured for the environment.
Also, the DLP Policy table looks empty.

**Comment by manuelap-msft** [comment]
Hello,

the DLP editor pulls the DLP policies you have directly from the system, they are not stored anywhere but retrieved in real time.

the DLP policies table you see here is used to support the Environment Request management solution
https://learn.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt

And in order to sync policies here you first have to choose which ones to make visible to makers for requesting
https://learn.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt#sync-shared-policies

Not all policies will be synced.

Hope that helps
Manuela

**Comment by pamatihyd** [comment]
@manuelap-msft   
thank you for responding quickly, 

if your answer "_the DLP editor pulls the DLP policies you have directly from the system, they are not stored anywhere but retrieved in real time_." in response to my question 1 

1. Why can't we see associated DLP policies that were configured for (CoE Power Platform) environment, why they are not retrieved?
I am little confused here. could you help me in understanding or missing anything 

![PP Screen 2](https://user-images.githubusercontent.com/29652263/203914743-9045db0c-7e1a-4ee9-bea7-4c8baf42eb19.JPG)

**Comment by manuelap-msft** [comment]
1. The Power Platform Admin View is a model driven app that shows data stored in Dataverse - there are certain flows in the CoE kit (Admin | Sync ....) that sync data from the platform into Dataverse, e.g. environment names, who created them, app names, connectors an app uses etc. The Dataverse tables in the CoE kit represent the meta-data of certain Power Platform inventory in your tenant. The sync from the platform into Dataverse happens on a daily or weekly basis, so it's not real time information that's represented in Dataverse. 
2. Outside of these Dataverse tables, actions in the [Power Platform for Admin](https://learn.microsoft.com/en-us/connectors/powerplatformforadmins/) or other admin connectors can pull "real-time" information - e.g. "List DLP policies" - these actions can be used in apps and flows to get the real time information.
3. For DLP Policies, we don't sync all DLP policies to Dataverse so you won't see them under Active DLP Policies. 
a. The DLP Editor uses the [Power Platform for Admin](https://learn.microsoft.com/en-us/connectors/powerplatformforadmins/] connector to retrieve DLP policies in your tenant and show them, but doesn't store them anywhere
b. The DLP Policies table in the CoE kit is only used for the [Environment Management Request](https://learn.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt#sync-shared-policies) feature and only DLP policies you mark as "visible to maker" are stored in Dataverse.

**Comment by pamatihyd** [comment]
@manuelap-msft thank you for the update
