### ISSUE TITLE
[CoE Starter Kit - model-driven apps are not visible

### ISSUE THREAD

**Issue by MantasSal** [microsoft/coe-starter-kit#4266]
### What is your question?

Hello,

when looking Apps section and selecting particular environment I can see 3 Apps:

![image](https://user-images.githubusercontent.com/114066875/203727697-44d0e031-f497-4dc1-bbdd-30a0cd441e46.png)

When looking at Power Platform admin center I can see more apps:

![image](https://user-images.githubusercontent.com/114066875/203729338-7077267c-14e7-4fdc-904d-3ca6e05e13cc.png)

So model-driven apps are not visible in apps section. Why?

Thanks

### What solution are you experiencing the issue with?

Core

**Comment by manuelap-msft** [comment]
Hello,

1. Can you check if the Admin | Sync Template v3 (Model Driven Apps) is running without failures and has been running continuously since you've set up the CoE kit?
2. Have you recently refreshed the dashboard?

**Comment by MantasSal** [comment]
Hello,

Yes, Sync Template v3 model driven apps is not running successfully.

***@***.***


It stops here:

***@***.***

***@***.***

**Comment by Jenefer-Monroe** [comment]
You will need to open the Model Driven App flow and find its failure to see why its not working. You can return here when you find that source, note that you need to log in to GitHub to share screenshots, responding in email will not share those images

**Comment by MantasSal** [comment]
Sorry, I will post image here. I tried looking in AAD for user and group according ID provided in error, but could not find anything.

![image](https://user-images.githubusercontent.com/114066875/204238728-c68fcb0d-a674-48cc-a27d-6cf1c1f18c7b.png)

**Comment by Jenefer-Monroe** [comment]
Apologies for the delay in responding. If you go into the trigger statement you will see the environment instance url. Can you browse to that? 
![image](https://user-images.githubusercontent.com/89584709/205936150-0d27aa3d-776b-4eaa-b28c-8cff91d8b7b8.png)

Here are some common things we have seen that cause this:
1. The identity running the flow does not have the Power Platform Admin Role permanently assigned. 
Note that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management), this won't be sufficient to run the CoE Starter Kit.
For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

2. The target environment for the call here was renamed but the old name is cached. In this case turning **_Admin | Sync Template v3 (Model Driven Apps)_** off and back on will clear that cache.

**Comment by Jenefer-Monroe** [comment]
Hello did you do the restart of the flow to fix?

**Comment by MantasSal** [comment]
Hello, yes, I stopped Admin | Sync Template  (Model Driven Apps) flow and started it again.
It fails every third or fourth time it runs.

![image](https://user-images.githubusercontent.com/114066875/207851632-26c23c03-61fd-46f8-9350-3e07ff8953e0.png)

**Comment by Jenefer-Monroe** [comment]
With this one and https://github.com/microsoft/coe-starter-kit/issues/4423, it appears that your user does not have PP Admin role or your license permanently assigned, or there is some other issue with your user. 

Can you please go to Azure Portal, look up the user running these flows, and let me know when you see for this role? 
![image](https://user-images.githubusercontent.com/89584709/207877334-f1746f0d-e932-4a91-8b52-acb73c26a9ed.png)

**Comment by MantasSal** [comment]
![image](https://user-images.githubusercontent.com/114066875/208390858-119619c1-7e2b-4cf3-baf9-cb626c159b03.png)

**Comment by Jenefer-Monroe** [comment]
Each one of these rows is a sep envt
![image](https://user-images.githubusercontent.com/89584709/208421778-d5999c96-26d0-4b2e-a09f-944ff9c39750.png)

You can see that by adding a column to the table. 
Go to http://flow.microsoft.com/ > Find your CoE Envt > Core Components > Cloud Flows > Admin | Sync Template v3 (Model Driven Apps)
From here you will see an Edit columns option and you can add the environmentname (its GUID type name)
![image](https://user-images.githubusercontent.com/89584709/208422804-2997db46-242c-48fc-81dc-f4c0768e9afc.png)

**Comment by Jenefer-Monroe** [comment]
Can you confirm that its the same environments failing over and over? Or it is always changing? 
If you click All runs there you can filter by failures after you add this environment name 
![image](https://user-images.githubusercontent.com/89584709/208423385-5c31d020-79e2-4d81-bc65-1e07fbca78da.png)

**Comment by MantasSal** [comment]
Hello,
Different environments are failing over and over again.
![image](https://user-images.githubusercontent.com/114066875/210735134-2a4382d5-14b5-4f60-aeda-abbaeac4ed3c.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by MantasSal** [comment]
Hello, can we reopen this case, please? I got this error:

![image](https://user-images.githubusercontent.com/114066875/213404106-ced7e08f-2fbe-4e66-b762-45dbfe8d88fe.png)

Outputs:
Boder:
{
  "status": 403,
  "message": "SecLib::CheckPrivilege failed. User: 07161f6f-e548-ed11-bba1-000d3aaaeebf, PrivilegeName: prvReadEntity, PrivilegeId: a3311f47-2134-44ee-a258-6774018d4bc3, Required Depth: Basic, BusinessUnitId: 9460d98f-da44-ed11-bba3-000d3aad7e62, MetadataCache Privileges Count: 3646, User Privileges Count: 194",
  "error": {
    "message": "SecLib::CheckPrivilege failed. User: 07161f6f-e548-ed11-bba1-000d3aaaeebf, PrivilegeName: prvReadEntity, PrivilegeId: a3311f47-2134-44ee-a258-6774018d4bc3, Required Depth: Basic, BusinessUnitId: 9460d98f-da44-ed11-bba3-000d3aad7e62, MetadataCache Privileges Count: 3646, User Privileges Count: 194"
  },
  "source": "pan-development.crm4.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: ac41799a-1243-402f-805f-9b5bfc94c324"
}

Headers:
{
  "Pragma": "no-cache",
  "Cache-Control": "no-store, no-cache",
  "Set-Cookie": "ARRAffinity=31d7e112df4ed9785378ef6db30d2113b50c989793293d38ed0e4472abdd114a;Path=/;HttpOnly;Secure;Domain=commondataservice-ne.azconn-ne-003.p.azurewebsites.net,ARRAffinitySameSite=31d7e112df4ed9785378ef6db30d2113b50c989793293d38ed0e4472abdd114a;Path=/;HttpOnly;SameSite=None;Secure;Domain=commondataservice-ne.azconn-ne-003.p.azurewebsites.net",
  "x-ms-request-id": "ac41799a-1243-402f-805f-9b5bfc94c324",
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Timing-Allow-Origin": "*",
  "x-ms-apihub-cached-response": "false",
  "x-ms-apihub-obo": "false",
  "Date": "Thu, 19 Jan 2023 09:20:37 GMT",
  "Content-Length": "812",
  "Content-Type": "application/json",
  "Expires": "-1"
}

**Comment by Jenefer-Monroe** [comment]
Hello, your issue is not related to the kit then, there is something wrong with your user identity as it is not able to access the environment. 
If you have the correct license and PPAdmin role permanently assigned (as stated above) then there is aproduct issue in place. You will need to take this new reduced issue here to the product support.
![image](https://user-images.githubusercontent.com/89584709/213452702-294a9f57-1286-4389-83f6-a2255eb5c100.png)

**Comment by MantasSal** [comment]
Hello,

Sorry, could you be more specific? I need to bring this issue to what product support? Microsoft Power platform?


________________________________
Iš: Jenefer Monroe ***@***.***>
Išsiųsta: 2023 m. sausio 19 d., ketvirtadienis 15:18
Kam: microsoft/coe-starter-kit ***@***.***>
Kopija: Mantas Salickas ***@***.***>; Author ***@***.***>
Tema: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - model-driven apps are not visible (Issue #4266)


Attention: This e-mail was sent from someone outside of BDO Global Office. Always use caution when opening attachments or clicking links from unknown senders or when receiving unexpected e-mails.


Hello, your issue is not related to the kit then, there is something wrong with your user identity as it is not able to access the environment.
If you have the correct license and PPAdmin role permanently assigned (as stated above) then there is aproduct issue in place. You will need to take this new reduced issue here to the product support.
[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89584709%2F213452702-294a9f57-1286-4389-83f6-a2255eb5c100.png&data=05%7C01%7C%7Cc946ebd0275c4fc542e408dafa1fa969%7Ce6504ea0d81945c0b8c664690f272b63%7C0%7C0%7C638097311141079646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rkZYH5tu8cXMrEH4QZ%2B63rjDozvmh81X3kSpwWlMu18%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F4266%23issuecomment-1396964805&data=05%7C01%7C%7Cc946ebd0275c4fc542e408dafa1fa969%7Ce6504ea0d81945c0b8c664690f272b63%7C0%7C0%7C638097311141079646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0H0uSnFxft2PgIDpjMc6FmikBjc4kb1j4IrZrmdca8w%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA3GILO3ZJS75T4N7J3RSKB3WTE5KPANCNFSM6AAAAAASJ62GIM&data=05%7C01%7C%7Cc946ebd0275c4fc542e408dafa1fa969%7Ce6504ea0d81945c0b8c664690f272b63%7C0%7C0%7C638097311141079646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JLytJXA%2Fz6LABLRycCdBWKP395HknEI8%2F4wh0m%2FmQhs%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>


Global IT & Services B.V. (“Global IT”) is a limited liability company registered in the Netherlands with KVK number 17239055 and VAT number NL8203.71.476.B01. It is a subsidiary of the Belgian company Brussels Worldwide Services BV (‘BWS’), that coordinates service provision within the international BDO network of independent member firms ('the BDO network'). Global IT provides services to BWS and the BDO network. Global IT, BWS and the BDO Member Firms are separate legal entities and have no liability for each other's acts or omissions. Nothing in the arrangements or rules of the BDO network shall constitute or imply an agency relationship between Global IT and the member firms of the BDO network.
BDO is the brand name for the BDO network and for each of the BDO member firms.

**Comment by MantasSal** [comment]
Could you, please, clarify what CoE dashboard data will be missing if I do not solve this issue and leave it as it is?

________________________________

**Comment by Jenefer-Monroe** [comment]
You will not be able to gather information from those environments. I suggest, if you want to have a CoE that you solve this. Otherwise you will not have predictale results in the kit generally speaking.

**Comment by MantasSal** [comment]
Hello,
I have asked Microsoft support about this permissions issue. The answer was that the flow is using legacy connector. It is the reason why it fails. Can you explain, please, or can we change connector?

![image](https://user-images.githubusercontent.com/114066875/222660198-9ae08b9c-6c1e-419f-a840-8a97b8feec1e.png)

**Comment by manuelap-msft** [comment]
- This flows retrieves model driven app inventory from all environments in your tenant
- Model Driven Apps are stored in the [appmodule](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/appmodule) Dataverse table of the environment they're created in
- This flow loops through all environments in your tenant to query this appmodule table to retrieve model driven app inventory
- The Dataverse (current) connector can only connect to the current environment and not other environments in the tenant. Only the legacy connector has the capability to connect to other environments.
- Because of this, we can't replace the legacy connector with the current one. 
- We also have many other customers who are using this flow successfully with the legacy connector, so I don't think that's the reason for the failure. 

Learn more about the legacy Dataverse connector:
https://learn.microsoft.com/en-us/power-platform/important-changes-coming#microsoft-dataverse-legacy-connector-cds-20-connector-for-power-automate-flows-will-be-deprecated-and-replaced-with-another-connector
