### ISSUE TITLE
[CoE Starter Kit - QUESTION] Multiple Maker Groups

### ISSUE THREAD

**Issue by CDSSYW** [microsoft/coe-starter-kit#4269]
### What is your question?

Hi,

Because we have distinguished the makers into 3 different levels according to the level of PP skills, 
thus wondering whether it's possible to input 3 maker groups as maker environment variables for the core component? Or is it only possible to input one maker group?

thanks in advance for your reply!

**Comment by manuelap-msft** [comment]
Hello,

it's only possible to enter one maker group in this environment variable. Makers are added to groups in the **Admin | Add Maker to Group** flow - you'd have to extend the CoE kit to add two more environment variables for your other maker groups, and then extend this flow to add makers to your groups based on the logic you want. 

Learn more about extending the kit: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

**Comment by CDSSYW** [comment]
Thank you Manuela for the prompt reply !
