### ISSUE TITLE
[Core Components] Admin - Command Center

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#427]
Many steps are involved in setting up the CoE Starter Kit – e.g. setting up SharePoint sites, Wikis, Office 365 groups for champions. A Command Center app that helps set up all the components outside the Power Platform would help. The command center could also be used to show CoE Starter Kit health (e.g. failing flows,…)

**Comment by manuelap-msft** [comment]
This should also include a form to open a GitHub issue that collects necessary information so users can directly from the CoE log issues.

**Comment by manuelap-msft** [comment]
So far, the ideas are:
- links to all CoE apps so this can be the "launch app" admins use to get to everything
- automation for things that need to be set up as part of the CoE kit, e.g. office 365 groups... (if not automation, then links to places that need automating)
- CoE Health in the form of sync flow errors (what other stats to use, e.g. are sync flows on?)
- update for environment variables
- support - link to CoE Docs and GitHub issues, download latest version
- learn - link to PP training
- message center (?) - latest PP news

**Comment by manuelap-msft** [comment]
Support:
![image](https://user-images.githubusercontent.com/55705669/129368378-1a24c5ab-1f52-4500-b4a9-88ad752a43a9.png)

Health:
![image](https://user-images.githubusercontent.com/55705669/129368410-07159732-2779-48c0-8237-4799104ff1e7.png)

Learn:
![image](https://user-images.githubusercontent.com/55705669/129368442-92c73ee4-9b4d-439f-8d57-d6086309bc2e.png)

**Comment by mikefactorial** [comment]
@jenschristianschroder and I were talking about something similar for the individual apps the other day. Having a support link that goes to GitHub issues and an upgrade to the latest version notification. In the case of non-admin users would they be able to access some of this functionality from an individual app e.g. ALM Accelerators?

**Comment by mikefactorial** [comment]
Help would also be something that we'd want to be able to link back to

**Comment by manuelap-msft** [comment]
That's a great idea! I want to build a similar app that's maker focused and we could then deep link to the learn / support page from the individual apps? 

So
- Admin "Command Center", links to admin training content, admin apps, etc
- Maker "Command Center", links to maker training content, maker apps, etc
- Both can have the Support part

We can use params to navigate to the individual pages in the app, and from each app have a link to the "command center" app? We could even build a small component for this to include in all apps.

Once the Admin one is done, the maker one should be easy to duplicate!

**Comment by mikefactorial** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
