### ISSUE TITLE
[ALM Accelerator - BUG]: Activate flow Error -Deploy Pipeline Failed

### ISSUE THREAD

**Issue by linujohn22** [microsoft/coe-starter-kit#4270]
### Describe the issue

I am getting below error in deployment step .

2022-11-24T13:38:49.4465481Z ScriptHalted
2022-11-24T13:38:49.5286564Z ##[error]PowerShell exited with code '1'.
2022-11-24T13:38:49.5987073Z ##[section]Finishing: Activate Flows

![image](https://user-images.githubusercontent.com/44782172/203785761-f9f4bf51-4cff-47b3-8721-45704a40768f.png)

when i check customdeploymentsetting.json . I am not able to see workflow details .

![image](https://user-images.githubusercontent.com/44782172/203785921-2a8d3eb2-2f27-4fec-a83a-0449850384f4.png)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Sep 2022

**Comment by mikefactorial** [comment]
@linujohn22 can you share the logs of the export done prior to the deployment? Specifically, the update deployment settings step in the export pipeline? That would help to understand why there's nothing related to flows in the customDeploymentSettings.json.
