### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to turn on Admin | Sync Template v3 (Flow Action Details)

### ISSUE THREAD

**Issue by ashlega** [microsoft/coe-starter-kit#4292]
### Describe the issue

When trying to turn on "Admin | Sync Template v3 (Flow Action Details)" flow, getting an error:

_Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id '6093b58a-4fea-eb11-bacb-000d3a578f6c' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}"._

That flow id shows up in at least a couple of places in the low definition, but there seem to be no flow with that id in the CoE solution:

![image](https://user-images.githubusercontent.com/5911927/204281496-9597e272-1d4d-45a8-a4bf-85bf1bd62b4e.png)

### Expected Behavior

Should be able to turn on "Admin | Sync Template v3 (Flow Action Details)" flow without errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### Steps To Reproduce

1. From the list of flows, click "turn on" on that flow

**Comment by Jenefer-Monroe** [comment]
Hello, can you please confirm that you have all the flows in the [inventory setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) turned on? In particular, it sounds like you are missing some of the [helper flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-child-flows)

**Comment by Jenefer-Monroe** [comment]
Then make sure you did not accidently create an [unmanaged layer](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) on this flow when investigating. 
Thank you!

**Comment by rob-amason** [comment]
I am running into a similar issue:

{
  "error": {
    "code": "NoResponse",
    "message": "The server did not receive a response from an upstream server. Request tracking id '08585319467446751957866153952CU38'."
  }
}

![image](https://user-images.githubusercontent.com/119354363/204362309-d5726965-6351-4d89-912a-b42e4941afbd.png)

**Comment by rob-amason** [comment]
> Hello, can you please confirm that you have all the flows in the [inventory setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) turned on? In particular, it sounds like you are missing some of the [helper flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-child-flows)

Any other advice?

**Comment by Jenefer-Monroe** [comment]
For rob-amason, did you validate that this flow is turned on? **_HELPER - CloudFlowOperations_**
If so, can you please validate that it and **_Admin | Sync Template v3 (Flow Action Details)_** do not have unmanged layers?

**Comment by ashlega** [comment]
> For ashlega, did you validate that this flow is turned on? **_HELPER - CloudFlowOperations_** If so, can you please validate that it and **_Admin | Sync Template v3 (Flow Action Details)_** do not have unmanged layers?

That was it (that Helper flow was off for some reason). Thank you for your help!

**Comment by Jenefer-Monroe** [comment]
Wonderful news, thanks for the update. I will go ahead and close.
