### ISSUE TITLE
[ALM Accelerator - BUG]: Can not see a "profile" in Deployment User Setting

### ISSUE THREAD

**Issue by thetla** [microsoft/coe-starter-kit#4295]
### Describe the issue

Hi,

I Cannot see a deployment user settings in the ALM Admin app. I can choose it in the app, I see all the profiles to the profile but I cannot add/remove/ users etc for the Deployment "profile". The user setting is named "CfE". 
![alm 1](https://user-images.githubusercontent.com/114479358/204465792-cf713de3-d59e-46cb-a880-3ff12e6f4871.png)
![alm 2](https://user-images.githubusercontent.com/114479358/204465844-4a4f23eb-fa1d-45ed-8e76-39c78050f570.png)
![alm 3](https://user-images.githubusercontent.com/114479358/204465860-1e5677b5-5a0d-4b52-b360-c3f830a253bd.png)

Br Terje Hetland 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

CoE Kit November Release

**Comment by mikefactorial** [comment]
@thetla it's possible the user settings record was deactivated accidentally. I don't think we're filtering for just active user settings. Can you try removing the filter from the view 

![image](https://user-images.githubusercontent.com/42348035/204576655-57887776-6860-41d1-b09a-d240ce17d64e.png)

**Comment by thetla** [comment]
That's work! Thanks 🥇
