### ISSUE TITLE
[CoE Starter Kit - BUG] Office365Users.UserProfileV2 failing for flows shared with groups in Developer compliance center app

### ISSUE THREAD

**Issue by Harini-Parthiban** [microsoft/coe-starter-kit#4299]
### Describe the issue

On the developer compliance center app, when opening the flow detail page of any flow which has been shared with a group, the following error appears. The name of the group is blank and is highlighted in red in the image below.

![office365failed2](https://user-images.githubusercontent.com/107025014/204539392-d43c5d77-a889-46df-8514-ee8f9e0a7781.png)

This error happens only when converting the group id to display name. It works good with users.
![err2](https://user-images.githubusercontent.com/107025014/204541431-916a560f-3433-4457-9a9a-ead66bf4da92.jpg)

### Expected Behavior

To display the group name on view flow permissions

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.23

### What app or flow are you having the issue with?

Developer Compliance Center

### Steps To Reproduce

1. Open the developer compliance center app
2. Navigate to cloud flows
3. Select any flow which has been shared with a group
4. Notice the error appearing on the top of flow detail page

**Comment by Jenefer-Monroe** [comment]
Thanks for posting with such well done repro steps. I do repro this with a group. We are redoing the app and so I am moving to to be a test case for those folks.

**Comment by Jenefer-Monroe** [comment]
thanks for sharing your workaround! Very helpful for the dev that does this work :)

**Comment by manuelap-msft** [comment]
The Developer Compliance Center is being re-designed using Creator Kit components and custom pages, it's a full rewrite and the way information is loaded is different but the re-write should fix this problem:

Here's what the details page looks like:

![Image](https://user-images.githubusercontent.com/55705669/211868556-3b752a86-6b20-4020-83fa-9b6292b89841.png)


This is targeted for February.
