### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#4308]
### What is your question?

Hello, I want to ask which flows I need to enable and then what actions need to be done to get values "Flows with open compliance requests", "Flow Pending Suspension", "Environments with open compliance requests" in Power Platform Governance and Compliance dashboard. 

![image](https://user-images.githubusercontent.com/54030753/204756415-c6ee879f-9f60-4e12-8e21-57b77b92db46.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

November 2022

### What app or flow are you having the issue with?

Power Platform Governance and Compliance dashboard

**Comment by Jenefer-Monroe** [comment]
Pending suspensions come from the [inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components)

The flow compliance requests come from the [compliance components](https://learn.microsoft.com/power-platform/guidance/coe/setup-governance-components). Note that there are no auto-detected flows for compliance, you would manually flag flows for compliance. 
![image](https://user-images.githubusercontent.com/89584709/204944129-4db733f9-4509-486c-92fa-292a803a4723.png)

For environments it is the [Dataverse for Teams environment management](https://learn.microsoft.com/power-platform/guidance/coe/setup-teams-components)

**Comment by BartoszKaminski1999** [comment]
@Jenefer-Monroe 

1. Could you specify which flow exactly mark flow as pending suspension?

2. I understand that for flow we need to mark Admin Requirement - Risk Assessment State to "Requested" but i don't see similar action for environment.
![image](https://user-images.githubusercontent.com/54030753/204991745-5b1a4e15-8cea-4f42-8e34-aa4915e06468.png)
![image](https://user-images.githubusercontent.com/54030753/204992019-7b9d0d4b-1561-40d4-af62-aac076093e9f.png)

**Comment by Jenefer-Monroe** [comment]
For teams, looks like we have the wrong field there. I have posted https://github.com/microsoft/coe-starter-kit/issues/4325 to fix. 
Thanks for posting

**Comment by BartoszKaminski1999** [comment]
@Jenefer-Monroe I understand that these flows that contain something in the "estimatedSuspensionData" column will be marked as Flow Pending Suspension On. My question is where does this value come from in this column, I would like to prepare such an action. 

![image](https://user-images.githubusercontent.com/54030753/205589281-c2333bfc-b5a2-491f-94aa-d1ada573bf51.png)

**Comment by Jenefer-Monroe** [comment]
That data comes from the List Flows as Admin call to Power Automate. So the product itself returns the value to us to parse. 
Does that answer your question?

**Comment by BartoszKaminski1999** [comment]
I don't care where this data comes from, but what sets it there and how to get such data. How to get estimatedSuspensionData in List Flows as Admin.

**Comment by Jenefer-Monroe** [comment]
I'm afraid that is a question for the product team, you will need to create a support ticket to get information about how this is filled into the List Flows as Admin call.

**Comment by BartoszKaminski1999** [comment]
Are you sure that you are using correct property here?
List Flows as Admin when flow is suspended returning properties like:
state: Suspended
flowSuspensionTime: 2022-11-30T15:55:41.1934922Z
flowSuspensionReason: NeverTriggeringDetected

but there is no property estimatedSuspensionData

Example of suspended flow returned by List Flows as Admin:

![image](https://user-images.githubusercontent.com/54030753/206109594-a602e00a-f545-403e-8e04-cc8ec7c9df11.png)

**Comment by Jenefer-Monroe** [comment]
The node is only present when a pending suspension is present. 
This flow you show is already suspended, so it would not have the node.

**Comment by BartoszKaminski1999** [comment]
I raised the case to the production group. Their statement is that this property is not yet official and should not be used in production, so Microsoft will consider removing them for the time being so that users cannot use them. I think that cleared all doubts. Thanks for the help.

**Comment by Jenefer-Monroe** [comment]
Do note that I see this property filled for other customers. So I'm not sure thats accurate. I think if you ask support for a list of flows that are pending suspension you can then see if you are missing any.
