### ISSUE TITLE
[CoE Starter Kit - QUESTION] Tenant Capacity Monitoring.

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4309]
### What is your question?

Hi , 

In CoE, we have Capacity Alert notifications component for environment level only ?

Do we have Capacity Alert notifications at tenant level ? we have this requirement as platform level  admins should get notified if tenant reaching its maximum capacity  ?
 
if Yes , Kindly please share the steps/approach
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Capacity Alert notification Flow

**Comment by Jenefer-Monroe** [comment]
No we do not have any tenant wide capacity information. It is a good idea though, putting on the feature backlog. 
Thank you for posting.

**Comment by pamatihyd** [comment]
Any Plan to take up this one ?

**Comment by Jenefer-Monroe** [comment]
Not at this time no. We will keep in on the backlog for now but it has not popped in priority. Thanks for letting us know you are interested!

**Comment by manuelap-msft** [comment]
Closing out. There is no way to get tenant capacity programmatically, so we are unable to report on this.
