### ISSUE TITLE
[Core Components] License guidance and reporting

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#431]
The most common ask for the CoE Starter Kit is to be able to see which users have which licenses and are using which apps – determine if a user needs a per user / per app / no license at all. We need to explore what current and coming APIs can support this ask. 

AB#1357

**Comment by redleo85** [comment]
Hi @manuelap-msft ,

the connector "HTTP with Azure AD", which is already used in the Core Components, provides the licenses assigned to any given user. 

![image](https://user-images.githubusercontent.com/9613325/189302886-f7d023d3-d8b5-4018-b408-5949fca531af.png)

Regards,
Leo

**Comment by manuelap-msft** [comment]
Hello,

yes, we have looked at that in the past - this action has to be performed per user in your organisation, so for large organisations (100k+ employees) this would dramatically increase the API calls we have to make and may lead to performance impacts and flow throttling so we're investigating other options. 

We're currently checking if Graph Data connect could be an option https://docs.microsoft.com/en-us/graph/data-connect-concept-overview

**Comment by redleo85** [comment]
Hi,
ok. It may be viable in larger tenants to do it, not by user, but by license, since most admins are only interested in premium Power Platform license.

Since there are only a handful of relevant premium licenses, you could get a list of all users with these licenses with only a couple of actions.

![image](https://user-images.githubusercontent.com/9613325/189380246-e2c6f0fc-aa90-4d03-a97f-b03fc2be24f9.png)

It would cost a lot of API requests to build an initial DB, but afterwards only a few API requests would be needed to keep the DB up-to-date.

**Comment by nickmoss99** [comment]
Tracking this... would be great to report on the per app and per flow passes/licenses in the COE PBI report.

**Comment by manuelap-msft** [comment]
Further asks from CoE Office hours:
- Would be possible to add to CoE inventory the licenses assigned to the makers or power platform users like Power Apps for O365 (Included in Office 365), power automate per user,
- Is there a way to provide insights on which apps and flows can have pay as you go plan

**Comment by lukas-nC** [comment]
I recently would that in the Audit Logs, one activity is "Change users licence"
So may initial u could get the licence for all Makers in the Maker table with the "Http with Azure" and then only perform this action for new users added to the maker table and user with has the licences change, data coming from the audit logs

**Comment by manuelap-msft** [comment]
Closing out old tasks that are still blocked. We can open a new task once data becomes available from the product.
