### ISSUE TITLE
[CoE Starter Kit - BUG] Set Flow Permissions - showing duplicate Flows

### ISSUE THREAD

**Issue by davins-msft** [microsoft/coe-starter-kit#4317]
### Describe the issue

The **Set Flow Permissions** app is showing 2 instances for the same flows. One has an owner and the other doesn't. 
 ![image](https://user-images.githubusercontent.com/91287781/204883331-860bd0f2-81a3-4a2d-baef-b5c63273a1ea.png)

For e.g. 
![image](https://user-images.githubusercontent.com/91287781/204883632-f143ef04-fddc-44b7-8927-e11bce004e86.png)

It seems to be 2 copies (different ids) of the same flow, however everything is identical (ownership, description, connections, execution times etc) across the 2 copies.

### Expected Behavior

Just one instance of the flow.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Set Flow Permissions

### Steps To Reproduce

Launch the App and see the duplicate list of Flows.

**Comment by Jenefer-Monroe** [comment]
If you are in one of the stations in red below, then between November 15th and November 23rd, the flow product team rolled a change which modified the name (the GUID) for solution flows. This had several side effects including failure of some CoE flows (ex Admin | Sync Template v3 CoE Solution Metadata), duplicate entries of other flows, and potentially loss of metadata (ex compliance information) about those flows. 

Other than the loss of the metadata, this will all correct now itself as flows continue to run including the CLEANUP - Admin | Sync Template v3 (Check Deleted) flow. 

Sorry for the inconvenience.

![image](https://user-images.githubusercontent.com/89584709/204932599-08112a90-8a81-4682-b9d5-12476299838d.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
