### ISSUE TITLE
[ALM Accelerator - Feature]: Use deployment profiles for portal uploads

### ISSUE THREAD

**Issue by ryanhodgson1** [microsoft/coe-starter-kit#4320]
### Is your feature request related to a problem? Please describe.

When uploading a portal to another environment it overwrites site settings that are specific for the environment

### Describe the solution you'd like

An option to use deployment profiles so that environment specific site settings can be maintained

**Comment by mikefactorial** [comment]
@ryanhodgson thanks for submitting this. This is something we were aware of when we released power pages support. Will look into how we can fill this gap.

**Comment by ryanhodgson1** [comment]
Thanks @mikefactorial
