### ISSUE TITLE
[ALM Accelerator - BUG]: Failure in activating flows no longer fails the pipeline in November update

### ISSUE THREAD

**Issue by ryanhodgson1** [microsoft/coe-starter-kit#4322]
### Describe the issue

Previous version of ALM failed the pipeline if a flow failed to activate on the step "Activate Flows", now if there are failures it shows the step as a success:

![image](https://user-images.githubusercontent.com/77652317/204949068-270d61d0-a776-4754-88b0-bfaf9a051ca5.png)

### Expected Behavior

Failure to activate a flow should fail the step in the pipeline

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

November Update

**Comment by mikefactorial** [comment]
@ryanhodgson you may be able to ignore those error messages. The flow activation logic should be handling errors like these and continue to attempt to activate flows without failing (specifically for this scenario where a parent flow is being activated before the child flow). If it hits an error it will continue to try to activate others and come back to the one that failed after the others are activated. Can you verify that the flows in fact were not turned on in the target environment?

**Comment by ryanhodgson1** [comment]
@mikefactorial the reason why it failed was cause some of the child flows it was looking for where not in the solution when they were meant to be, so would have been good if the step failed.

**Comment by ryanhodgson1** [comment]
@mikefactorial this also happened in a production release we did today where we didnt know that the flows failed cause it had a green tick but actually it didnt work.

It seems like there is another issue with this step as well where even though im assigning the Flow owner as a service account its activating it under the ALM service principal instead. I have seen this in multiple solutions after the November update and was why the Flows failed in our production release.

**Comment by ryanhodgson1** [comment]
@mikefactorial for now i have rolled back the activate-flows.ps1 to the older version and it has resolved both issues now, but will need to be addressed for future updates.
