### ISSUE TITLE
[ALM Accelerator - BUG]: Error on running "coe alm install -f quickstart.json"

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/coe-starter-kit#4326]
### Describe the issue

Installing ALM Accelerator using [CoE CLI admin install instructions](https://learn.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/admin-install) and running the command `coe alm install -f quickstart.json` results in the error.

"ERROR: unrecognized arguments: --sign-in-audience AzureADMyOrg"
![azclierror](https://user-images.githubusercontent.com/2699443/205074992-0e9e5455-820f-413c-9acd-ba67bae0b3a3.png)

### Expected Behavior

ALM accelerator install to succeed

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Latest

### Steps To Reproduce

1. Follow instructions in [admin install using CoE ALM Accelerator](https://learn.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/admin-install)
2. Run `coe alm generate install -o quickstart.json`
3. Run `coe alm install -f quickstart.json`

**Comment by mikefactorial** [comment]
@NarmathaBala this looks like an issue with the version of the Azure CLI you have installed try running az --version to ensure you have version 2.3.7 or higher (https://learn.microsoft.com/en-us/power-platform/guidance/coe/cli/install#local-install)

**Comment by NarmathaBala** [comment]
That was the issue, thanks @mikefactorial
