### ISSUE TITLE
[Core Components] Cloud Flow Run History

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#433]
Explore if Custom Connectors / APIs can be used to report on flow run history

**Comment by gabrieljunckes** [comment]
I don't know if the best place is in CoE or Application Insight but It would be great to have the Flow history in one place where we can create reports and set up alerts for failures.

**Comment by WouterF** [comment]
@manuelap-msft , this is an excellent idea.
I have already researched this as well and found that you can get the flow runs based on the environment id and the flow id, via the flow service API.
I found this blog post about this: https://2die4it.com/2020/07/08/custom-connector-to-get-flow-run-history/
Maybe it is possible to create a flow that loops every hour/day through all the flows that are in the table of the CoE core components? But in any case, this flow will consume a lot of API calls.
It would be better if the product team can create a trigger "When a flow in an environment fails" or something like that :)

**Comment by manuelap-msft** [comment]
Thanks for the info @WouterF! We are aware of this API, unfortunately it is not officially supported & publicly available - although we know some customers and MVPs have started taking a dependency on it, we have been discouraged by the Product Team to do so as breaking changes could happen. Due to wide customer base the CoE Starter Kit has, we are unable to take a bet on unsupported APIs. 

We are working with the Product team on alternatives, and will keep this backlog item updated as we find out more!

Thanks for the input!

**Comment by larhem** [comment]
Any chance this will be added in the near future?

**Comment by manuelap-msft** [comment]
Due to product limitations, this is not something that will be added until the product has made cloud flow run history available to us in a way we can consume it. Near term this will be through self-serf analytics https://docs.microsoft.com/en-us/power-platform/admin/self-service-analytics, which is currently in public preview and the schema is not stable yet so we can't take a dependency on it. But it may be something you want to try out in your tenant!

**Comment by larhem** [comment]
We were hoping for this to be added to CoE since you have the "Cloud Flow Runs" table there already :)
Any idea if run history will be added to power automate admin connectors (or similar) at all?

**Comment by manuelap-msft** [comment]
This will be available once we offer integration with BYODL (Data Export). Tracked via #424. We will not explore other ways of making this data available. Closing this issue as we're tracking BYODL integration via #424.

If you are interested in the private preview for CoE on BYODL please sign up here https://aka.ms/coebyodlpreview

**Comment by beck0york** [comment]
Hello @manuelap-msft , sorry to comment on a closed thread, but having read this and also the #424 and #4977 I am unsure how these fit in with the release info https://learn.microsoft.com/en-us/power-platform/release-plan/2023wave1/power-automate/store-cloud-execution-history-dataverse - are they even connected?  Will this be MS facilitating/ semi-automating the population of the dataverse Cloud Flow Runs table via the BYODL?  Thank you for any info you can offer.

**Comment by manuelap-msft** [comment]
1. Currently you can get cloud flow run information for all cloud flows using the Data Export feature > this provides a daily export of flow usage to a central Azure storage account in your Azure subscription/your tenant. This means that you have one daily file in that storage account that contains info on all cloud flow runs across your tenant.
2. As far as I know, the feature you've highlighted will provide cloud flow run history for solution-aware cloud flows (cloud flows that are in a solution only) into Dataverse, that run history is than stored in the environment the flow is in (not central). I don't have any more info on how this will be facilitated. 
3. For the CoE kit team, we've just made available the integration of the CoE kit with the Data Export (BYODL) feature. We'll evaluate closer to the time if using the Dataverse cloud flow runs table is another option for us to consider but haven't looked into this so far.

Hope this helps,
Manuela
