### ISSUE TITLE
[CoE Starter Kit - QUESTION] Product Feature question - Automatic deletion of microsoft for dataverse teams 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4333]
### What is your question?

Hi 

I have one question regarding Microsoft for dataverse for teams components.

Recently microsoft announced that automatic deletion of microsoft for dataverse teams will be parte of Admin centre.

We have seen alot of emails triggered these days for disabled and inactive dataverse for teams environments all of sudden.  It has created a chaos in our organization everyone is worried about their environments .

We would like to stop this , we really want if this setting can be stopped in Admin centre level .

We tried but no luck could you please suggest what is the best possible way to stop sending inactive dataverse for teams environments 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.73

### What app or flow are you having the issue with?

Dataverse for teams

**Comment by manuelap-msft** [comment]
Hello, is your question in relation to the [product feature of disabling inactive Teams environments](https://learn.microsoft.com/en-us/power-platform/admin/inactive-teams-environment), or the [CoE Starter Kit feature for Teams governance](https://learn.microsoft.com/en-us/power-platform/guidance/coe/teams-governance)?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
