### ISSUE TITLE
[ALM Accelerator - BUG]: pac related steps failing

### ISSUE THREAD

**Issue by sandeepadode** [microsoft/coe-starter-kit#4335]
### Describe the issue

The pac - Clone or Sync Solution step fails randomly when trying to commit to an existing branch. It works sometimes and fails intermittently.
![image](https://user-images.githubusercontent.com/37178101/205361501-dedcdb49-84bf-47ee-b5b3-ebc4b618b554.png)

### Expected Behavior

The solution should be able to export

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20221101.1

### Steps To Reproduce

N/A

### Anything else?

![image](https://user-images.githubusercontent.com/37178101/205361518-a48632c4-f99e-4257-a3ac-52ddb4b44ff7.png)

**Comment by mikefactorial** [comment]
@sandeepadode this seems to have been missed when reported. Is this still an issue you are facing?

**Comment by mikefactorial** [comment]
Closing this out as there hasn't been any response. Feel free to open a new issue if this is still a problem.
