### ISSUE TITLE
Integer values associated to choice values for admin_adminriskassessmentstate column in PowerApp Apps table

### ISSUE THREAD

**Issue by michaelgottwals** [microsoft/coe-starter-kit#4337]
I am trying to create a flow that checks the value of the admin_adminrequirementriskassessmentstate column in the PowerApp Apps table of the Teams version of the CoE starter kit. I tried using the string value to perform the check (e.g. Requested) in the flow, however, the flow fails because the column data type is integer. I would like know how to determine what “numbers” are associated with each choice value, (Requested, Submitted, Complete, None), so that I can perform the check with the associated integer value.

Thanks

**Comment by manuelap-msft** [comment]
Hello,

this field is of type Choice, so only a certain set of values are allowed. To see the value associated with the label, open the Core Components solution > Select "Choices" > Select the Risk Assessment State Choice > then you'll see the label and value of each choice:
![image](https://user-images.githubusercontent.com/55705669/205443203-012a298e-1d54-4ecb-b555-8f6089d0357c.png)

**Comment by michaelgottwals** [comment]
Hello Manuela,

Thank you for this information. For some reason when I select the any of the choices and click on "Edit" nothing happens, the choice values for the selected choice do not display. There is the yellow banner message that states "you cannot directly edit the objects within a managed solution..." so maybe for choices it does not allow the Edit dialogue box to display?

**Comment by michaelgottwals** [comment]
The default solution in my Teams environment where I have installed the CoE starter kit does not contain any "Choices" objects. I also tried viewing the choices in the CoE starter kit I have installed it a Teams environment in our Dev tenant and I got the same behavior, it does not launch the choices dialog box. No message or dialogue box displayed for that. In your example were you in a Production version of the CoE starter kit rather than Teams? if so, could that have something to do with the behavior or am I just experiencing an anomaly?

**Comment by manuelap-msft** [comment]
Yes, the screenshot I shared was from a Production environment so I think the experience in Teams is different here. I'll need to investigate how to get to this screen for Teams. If you have any solutions that sound like Default solution in your Teams environment (e.g. Common Data Services Default solution or so) that might be worth trying

**Comment by michaelgottwals** [comment]
The default solution I was looking at in my Teams environment is the "Common Data Services Default Solution" which has my first sample app and the corresponding table for the sample app. There is also another another canvas app that I created in there and that is it. I am not sure how the managed solution choices would have gotten added to the default solution, unless the installation of the CoE starter kit did that step.

Regardless, if you could confirm if it is possible to check the values of choices for managed solutions in Teams for future reference, that would be greatly appreciated.

**Comment by michaelgottwals** [comment]
Hello Jenefer, thank you for providing how to get those numeric values behind the choices in the Teams version. That worked perfectly, so you can go ahead and close out this issue.

Thanks!

**Comment by Jenefer-Monroe** [comment]
wonderful, thank you for using CoE
