### ISSUE TITLE
[CoE Starter Kit - BUG] - Critical Flows not completing successfully 

### ISSUE THREAD

**Issue by rob-amason** [microsoft/coe-starter-kit#4339]
### Describe the issue

I am troubleshooting some really odd issues within our CoE environment and tenant as a whole. I will be making two separate threads in order to keep track of the issues better. 

**First issue:**
Admin | Sync Audit Logs
This flow has not been completed successfully in over 30 days and consistently displays these errors:
_The server did not receive a response from an upstream server. Request tracking id '08585319466436564066996793532CU00'._
![image](https://user-images.githubusercontent.com/119354363/205550811-336f5f3a-cf17-42b1-acb9-92fb6d74001f.png)

![image](https://user-images.githubusercontent.com/119354363/205550997-f69a4dc3-d5df-4cfb-8bb0-a1654aa51d21.png)
_The 'start index' for function 'substring' must be equal to or greater than zero and must be less than '16' which is the length of the string._

**Second Issue:**
HELPER - CloudFlowOperations
This flow has not been completed successfully in over 30 days and consistently displays these errors:
![image](https://user-images.githubusercontent.com/119354363/205551372-69e4d7ef-55bb-48be-a8ae-c45eb7f28ad7.png)

![image](https://user-images.githubusercontent.com/119354363/205551515-c56c0dd8-c224-4425-9ebd-dd88ca7620f9.png)

![image](https://user-images.githubusercontent.com/119354363/205551637-6f61c768-18b5-44ea-b269-1ffff3dfa3c8.png)

Any guidance would be appreciated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Audit Logs and HELPER - CloudFlowOperations

### Steps To Reproduce

These issues are occuring during scheduled and manual executions.

**Comment by Jenefer-Monroe** [comment]
Hello, thanks for posting. 

**First issue:** Admin | Sync Audit Logs
This is likely due to your connection getting broken on upgrade, or other wise being broken.
Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

**Comment by Jenefer-Monroe** [comment]
**Second Issue:** HELPER - CloudFlowOperations
The second failure **_Set SolutionAwareFlow to value from CoE_** is just due to the first. As you can see, when the **_EnvtGUID_** call fails, then Get flow from CoE is not run, and then when its later referenced it fails
![image](https://user-images.githubusercontent.com/89584709/205654798-48379dfd-be31-42f3-b7a7-61d358890e8d.png)

**Comment by Jenefer-Monroe** [comment]
For the issue with **_EnvtGUID_**, it sounds like its not getting its value from the input, can you please see what is returned from the trigger? In particular for the envName field. 
![image](https://user-images.githubusercontent.com/89584709/205655169-8a0803e1-2741-4dd2-8e06-2dd110ac68eb.png)

**Comment by rob-amason** [comment]
> For the issue with **_EnvtGUID_**, it sounds like its not getting its value from the input, can you please see what is returned from the trigger? In particular for the envName field. ![image](https://user-images.githubusercontent.com/89584709/205655169-8a0803e1-2741-4dd2-8e06-2dd110ac68eb.png)

Upon running this flow I now receive a different set of errors:
![image](https://user-images.githubusercontent.com/119354363/205678089-cadf2abf-9e39-4f73-bd08-64449f06eb65.png)

![image](https://user-images.githubusercontent.com/119354363/205678263-53931f2f-4e1d-4da2-b153-72582a2007a4.png)

**Comment by Jenefer-Monroe** [comment]
this is the same cause, from the Get Flow from CoE not running, which is due to EnvtGUID failing, which (From the error) is likely due to the input. 
Please see what is returned from the trigger? In particular for the envName field. ![image](https://user-images.githubusercontent.com/89584709/205655169-8a0803e1-2741-4dd2-8e06-2dd110ac68eb.png)

**Comment by Jenefer-Monroe** [comment]
ok the envt is going in wrong, it is supposed to be the unique name (the GUID), do you know what is calling this? Or did you run it manually?

**Comment by Jenefer-Monroe** [comment]
and same with User ID, should be a GUID. Please let me know if you are running this manually as I have not seen these passed in incorrectly before

**Comment by rob-amason** [comment]
> Hello, thanks for posting.
> 
> **First issue:** Admin | Sync Audit Logs This is likely due to your connection getting broken on upgrade, or other wise being broken. Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

I've discovered that the Admin | Sync Template v3 has not been running. I am at a loss with what has happened here:
![image](https://user-images.githubusercontent.com/119354363/205740787-d724202f-0952-4eee-a07a-9d61d27c1d03.png)

![image](https://user-images.githubusercontent.com/119354363/205740973-a1b642dd-8145-4cef-9805-5d3f9b4c8470.png)

![image](https://user-images.githubusercontent.com/119354363/205741040-a97763e9-e8a8-4e25-8149-b1840c806319.png)

![image](https://user-images.githubusercontent.com/119354363/205741208-9faca033-a3c0-4cdf-9840-b9e603d8a770.png)

![image](https://user-images.githubusercontent.com/119354363/205741267-9ff79659-0c7a-470c-9ecb-0bb8c6d5fe45.png)

**Comment by Jenefer-Monroe** [comment]
For this issue
https://github.com/microsoft/coe-starter-kit/issues/4339#issuecomment-1338143147

I will need to know the trigger values for the automated run.

**Comment by Jenefer-Monroe** [comment]
For the issue with **_Admin | Sync Template v3_**, Do you have the **_HELPER - Maker Check_** flow turned on?

**Comment by rob-amason** [comment]
> 

Yes it is On, looks like it has not run since 11/04/22
![image](https://user-images.githubusercontent.com/119354363/205742520-7af446fa-669e-4240-a2cd-c89c2d87840a.png)

**Comment by rob-amason** [comment]
> For this issue [#4339 (comment)](https://github.com/microsoft/coe-starter-kit/issues/4339#issuecomment-1338143147)
> 
> I will need to know the trigger values for the automated run.

For the HELPER - CloudFlowOperations Issue:
When I click the 'Run' icon the slide-out screen requests information
![image](https://user-images.githubusercontent.com/119354363/205743859-c60169a7-4aef-4164-a99a-f5fe9c7fb120.png)

**Comment by Jenefer-Monroe** [comment]
sorry its quite difficult to track this many issues in one. we can try to finish this up but in the future plesae post one bug per issue.

**Comment by Jenefer-Monroe** [comment]
> > For this issue [#4339 (comment)](https://github.com/microsoft/coe-starter-kit/issues/4339#issuecomment-1338143147)
> > I will need to know the trigger values for the automated run.
> 
> For the HELPER - CloudFlowOperations Issue: When I click the 'Run' icon the slide-out screen requests information ![image](https://user-images.githubusercontent.com/119354363/205743859-c60169a7-4aef-4164-a99a-f5fe9c7fb120.png)

if this is how it was run when it failed then its just that you entered the values wrong. so I'm not sure if we have an issue here or not.

**Comment by rob-amason** [comment]
@Jenefer-Monroe add another one not working to the list..this is wild, I feel like I am chasing my tail.
Get M365 Service Messages
![image](https://user-images.githubusercontent.com/119354363/205749700-95036657-8681-446b-af38-979e4a0cab3d.png)

![image](https://user-images.githubusercontent.com/119354363/205749764-e07d6b59-4434-4d84-adca-dd663b3a28db.png)

**Comment by Jenefer-Monroe** [comment]
> @Jenefer-Monroe add another one not working to the list..this is wild, I feel like I am chasing my tail. Get M365 Service Messages ![image](https://user-images.githubusercontent.com/119354363/205749700-95036657-8681-446b-af38-979e4a0cab3d.png)
> 
> ![image](https://user-images.githubusercontent.com/119354363/205749764-e07d6b59-4434-4d84-adca-dd663b3a28db.png)

this issue is known and fixed for Dec, the returned json changed and we had to update the parse statement

**Comment by rob-amason** [comment]
> sorry its quite difficult to track this many issues in one. we can try to finish this up but in the future plesae post one bug per issue.

My apologies, I was trying to keep them all in one place - but I understand what you mean. However, it does seem that there is a larger issue occurring with this many flows having stopped working on or around 11/04/22 and none of them will run successfully anymore.

**Comment by Jenefer-Monroe** [comment]
Let's use this bug to track the first failure for **_Admin | Sync Audit Logs_** which is now addressed. 
Can you please post new issues for the rest if they are still a concern?

**Comment by rob-amason** [comment]
> Let's use this bug to track the first failure for **_Admin | Sync Audit Logs_** which is now addressed. Can you please post new issues for the rest if they are still a concern?

Will do. Thank you for all of your responses.

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this one out then.
