### ISSUE TITLE
[ALM Accelerator - BUG]: Multilple Group Teams associated to the same AAD Group

### ISSUE THREAD

**Issue by rsantos00** [microsoft/coe-starter-kit#4343]
### Describe the issue

Going to Deployment setttings and create a new Group Teams and pick a AAD Group that is already associated to a different Group Teams>

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/3724826/205671974-03b731c7-3dae-4d9a-b4f2-c02ab54f3599.png">

Pipelines fail silently:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/3724826/205672493-fe14c607-590c-4eef-9513-cce7f7ba94ad.png">
 

### Expected Behavior

Have a validation on the UI of Accelerator to prevent me to save with the wrong AAD Group

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

December

**Comment by mikefactorial** [comment]
Closing this out as we've addressed the group teams issue in a previous release.
