### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Compliance detail request v3 - Status Failed

### ISSUE THREAD

**Issue by rob-amason** [microsoft/coe-starter-kit#4346]
### Describe the issue

I am suddenly running into issues where various & majority of CoE flows have stopped working, here is another one for the list:
Flow
Admin | Compliance detail request v3

It last ran successfully on 10/31/22 & since then consistently fails with the error code: Action 'Get_Assignee_apps' failed
![image](https://user-images.githubusercontent.com/119354363/205751743-41474929-9e43-4967-bcca-d43d9b4eed74.png)

![image](https://user-images.githubusercontent.com/119354363/205751777-3663bb77-0d81-4c2d-835e-a1af485e984a.png)

![image](https://user-images.githubusercontent.com/119354363/205751817-f6290057-91d0-4052-a62b-6c90aecfa586.png)

![image](https://user-images.githubusercontent.com/119354363/205751853-f473ec74-388f-4f11-9412-6f6a03c5a3e3.png)

![image](https://user-images.githubusercontent.com/119354363/205751865-d3117766-1aa5-4415-aaa2-2c5ceade4306.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Compliance detail request v3

**Comment by Jenefer-Monroe** [comment]
First question would be, is the **_HELPER - Maker Check_** flow turned on and running, from your other bug it looks like its on but not running. 

Can you please check the following:

1) Does the **_HELPER - Maker Check_** flow have [unmanaged layers](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows)?

1) Does the **_Admin | Compliance detail request v3_** flow have [unmanaged layers](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows)?

1) Are the [Run only users](https://learn.microsoft.com/power-platform/guidance/coe/faq#set-flow-run-only-users-properties) set on **_HELPER - Maker Check_**?
![image](https://user-images.githubusercontent.com/89584709/205763835-caf3ce22-b661-41b3-af95-ac1c959ec05c.png)
![image](https://user-images.githubusercontent.com/89584709/205764058-69e208a4-4342-4dee-89a5-28ccb772eda7.png)

**Comment by Jenefer-Monroe** [comment]
Which account are you using for all this? Is it the one that is not returning objects per https://github.com/microsoft/coe-starter-kit/issues/4340?

**Comment by Jenefer-Monroe** [comment]
OK im afraid there is something wrong with the user identity running the flow then. 
Perhaps its something as simple as using PIM to grant the Power Platform Admin Role or license, which we don't support. 

Please review [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by rob-amason** [comment]
> OK im afraid there is something wrong with the user identity running the flow then. Perhaps its something as simple as using PIM to grant the Power Platform Admin Role or license, which we don't support.
> 
> Please review [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

What would cause it to quit working when it still uses the account that was originally used to set it up?

**Comment by Jenefer-Monroe** [comment]
If you edit that flow, what do you see here for these two actions? (please check for unmanaged layer after you do this in case one gets added) 
![image](https://user-images.githubusercontent.com/89584709/207682932-9b6c32ed-c481-4497-81fc-6daaa5969e51.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
