### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 - Status Failed

### ISSUE THREAD

**Issue by rob-amason** [microsoft/coe-starter-kit#4347]
### Describe the issue

I am suddenly running into issues where various & majority of CoE flows have stopped working, here is another one for the list:

Flow
Admin | Sync Template v3 _(the HELPER - Maker Check flow is turned on.)_

![image](https://user-images.githubusercontent.com/119354363/205752798-a1828508-f053-4816-b474-529a847c8324.png)

![image](https://user-images.githubusercontent.com/119354363/205752845-6db41ed8-2ea5-4539-9a67-64b8796849c1.png)

![image](https://user-images.githubusercontent.com/119354363/205752872-046b191c-95fe-4faf-aa14-4c2e3b312f14.png)

![image](https://user-images.githubusercontent.com/119354363/205752892-f7ce0476-d944-40ea-a137-a6b649ed6a36.png)

![image](https://user-images.githubusercontent.com/119354363/205752960-2b84b7d2-d63e-4eba-94b8-1473d7d5e69c.png)

![image](https://user-images.githubusercontent.com/119354363/205753012-0936fa37-8e19-470e-aef6-fae804a391ea.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
