### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flows in documentation don't match solution (due to a previous solution version being used)

### ISSUE THREAD

**Issue by Paconaut** [microsoft/coe-starter-kit#4348]
### Describe the issue

Installed CenterofExcellenceCoreComponents_3.53_managed.zip but run into issue when following https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows due to missing flows.

### Expected Behavior

Expected to find the following flows specified in the documentation:
- Admin | Sync Template v3 (Ai Models) 
- Admin | Sync Template v3 (Call Updates) 
- (optional) Admin | Sync Template v3 (Flow Action Details) 
- Admin | Sync Template v3 (Sync Flow Errors) 
- Admin | Sync Template v3 
- CLEANUP - Admin | Sync Template v3 (Check Deleted) 
- CLEANUP - Admin | Sync Template v3 (Connection Status) 
- CLEANUP - Admin | Sync Template v3 (Delete Bad Data) 
- CLEANUP - Admin | Sync Template v3 (Orphaned Makers) 
- CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

(Stated above)

### Steps To Reproduce

Followed documentation step by step:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
