### ISSUE TITLE
[CoE Starter Kit - BUG] Audit logs connection breaks on upgrade

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#4349]
### Describe the issue

Hello, after new release import, i had to reset Office 365 Management API connection:

![image](https://user-images.githubusercontent.com/54030753/205867870-7b3e63fb-9f59-4069-99e2-de19a768dd52.png)

There I changed :

Client id and I bring it from Application (client) ID from Azure App
Client secret and I bring it from Client Secret Value
Resource URL to https://manage.office.com/

![image](https://user-images.githubusercontent.com/54030753/205869954-12e41e62-7cee-4a11-8ac9-a568f7ded604.png)

Then I am clicking on Update Connector and i get this message:

![image](https://user-images.githubusercontent.com/54030753/205870326-1bd0a4b5-01a8-4f5d-b642-e58393401b78.png)

Im not sure if Im doing something wrong, before CoE update everything went fine and audit flows that were using this connector were running correctly. 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Newsest

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
There is a known product issue in which connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

**Comment by BartoszKaminski1999** [comment]
Resolve https://github.com/microsoft/coe-starter-kit/issues/1424 not helped me. I will try to create a ticket to MS.
