### ISSUE TITLE
[ALM Accelerator - BUG]: Deployment Variable Values Not Deployed

### ISSUE THREAD

**Issue by tylersand** [microsoft/coe-starter-kit#4357]
### Describe the issue

I have an Environment Variable configured called "ts_test" with values configured in the solution and the deployment settings.

![image](https://user-images.githubusercontent.com/16942321/205969896-916cf6d9-cc06-44d9-acfe-f41c96a1dd36.png)

![image](https://user-images.githubusercontent.com/16942321/205968470-13686b44-1994-45cb-ad0f-3d8593f5019c.png)

![image](https://user-images.githubusercontent.com/16942321/205970130-55a903ba-ec5d-4b0a-b158-6d7921f74ddc.png)

Upon Commit Solution, when the **Update Deployment Settings Pipeline Step** runs, it sees the values:
![image](https://user-images.githubusercontent.com/16942321/205967355-c20f22dc-e1d1-4ef3-afcd-c67e13f5e664.png)

However they are not reflected in the resulting deploymentSettings.json files:
![image](https://user-images.githubusercontent.com/16942321/205966476-0b0e7125-5572-49b7-8a22-9d6ff5e8ced7.png)

I thought perhaps the #{environmentvariable.ts_Test}# was a placeholder that pulled the value from elsewhere later in the deployment, however the resulting solution and deployment to an environment still reflect the original value:

![image](https://user-images.githubusercontent.com/16942321/205966897-a4496fe7-b9aa-40a8-94be-cc74898daa8c.png)

Log is attached:
[log.txt](https://github.com/microsoft/coe-starter-kit/files/10168264/log.txt)

### Expected Behavior

The ts_test Environment Variable should be deployed to TEST with a value of "test" and to VALIDATION with a value of "validation123".

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

CenterofExcellenceALMAccelerator-November2022

### Steps To Reproduce

1. Add Environment Variable to source solution
2. Configure with Deployment Settings to override the Environment Variable value
3. Commit Solution
4. Deploy Solution to TEST/VALIDATION/PROD
5. Verify the Environment Variable value in TEST/VALIDATION/PROD

**Comment by mikefactorial** [comment]
One other question. In the screenshot I only see Default Value which would have been exported with the solution from your dev environment, but I don't see the Current Value. You may want to try removing the default value from the dev environment before exporting and deploying.

**Comment by tylersand** [comment]
I noticed that the Default Value was still included in the target environment which I believed was a side effect of being set previously in the managed solution.  I did another test with a brand new Environment Variable and it worked as expected without a Default Value.

DEV:
![image](https://user-images.githubusercontent.com/16942321/206269123-dff80c50-1ee5-469b-a6e7-7789e7ab9af0.png)

VALIDATION:
![image](https://user-images.githubusercontent.com/16942321/206269034-8deb1348-c5dc-4213-bafa-4397aa3448a7.png)

**Comment by mikefactorial** [comment]
@tylersand closing this out. Glad you got it working. There is an option on the export pipeline you can add as a variable documented here https://learn.microsoft.com/en-us/power-platform/guidance/coe/almaccelerator-pipelines to ensure that the current value is not exported with the solution DoNotExportCurrentEnvironmentVariableValues = true.
