### ISSUE TITLE
[ALM Accelerator - QUESTION] Possible to deploy pipelines to an AzDo Organization in a different Azure Tenant

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/coe-starter-kit#4359]
### What is your question?

Hi - Curious to see if ALM Accelerator can deploy / run pipelines to an Azure Organization that exists in a different Tenant (than the one that the Power Platform is in). I see no options to grant Service Principal access to a different org (other than the 
![image](https://user-images.githubusercontent.com/2699443/205998007-15fc13de-5c1c-4b93-abd7-823c291581e4.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

latest

**Comment by tylersand** [comment]
That would be a nice feature, especially for partners managing many customer environments.

**Comment by mikefactorial** [comment]
@NarmathaBala there's no cross-tenant support at the moment. There's another conversation regarding this functionality here https://github.com/microsoft/coe-starter-kit/issues/3946. Closing this out as a duplicate for now. Feel free to add your feedback to #3946
