### ISSUE TITLE
PowerPlatform Admin View cannot be associated to more than one component library

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#4375]
Tried to install CoE December Update 👎 
Would not import needs Creator Kit November 2022 installed first .

Installed Creator Kit November 2022.

Try to install CoE  December update - failed - 'Power Platform Admin View' app cannot be associated to more than one component library. Already exist component library count Microsoft.Xrm.Sdk.DataCollection`1[Microsoft.Xrm.Sdk.Entity].  In Solution Import, please remove library either from Source or Target and try again.

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of your solutions? Sounds like upgrade of Creator Kit failed. Be sure to expand all columns so e can see all the text
![image](https://user-images.githubusercontent.com/89584709/206275474-4a642bf2-c539-4bcf-9241-2d7b5fb17b4d.png)

**Comment by NPrice99** [comment]
![image](https://user-images.githubusercontent.com/8484048/206301294-bceda458-f0c0-4edd-b1ab-1d8a10d15d3a.png)

History
![image](https://user-images.githubusercontent.com/8484048/206301551-24a30a5f-7099-4e24-acb6-c619252360e3.png)

**Comment by Jenefer-Monroe** [comment]
Have you added other component libraries to the Power Platform Admin View app? 
There may be easier ways to find this out, but this should do it too. 

Edit the app
![image](https://user-images.githubusercontent.com/89584709/206346300-e30fae3b-9db3-42b4-943d-e152b9178489.png)

Edit the command bar
![image](https://user-images.githubusercontent.com/89584709/206346431-d52bee54-3b6b-4dc2-915a-312533accb23.png)

Any will do
![image](https://user-images.githubusercontent.com/89584709/206346477-2daa40ad-e5d0-4df8-bddd-d1e301a60910.png)

You may have to select a command before the button shows up. 
![image](https://user-images.githubusercontent.com/89584709/206346533-256a8523-5b7e-421c-a7e1-a17cd266c0f1.png)

Do you have a command library?

**Comment by NPrice99** [comment]
Hi @Jenefer ***@***.***>

No component library

Regards

Nigel

**Comment by NPrice99** [comment]
finally fixed this via this thread - https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Managed-solution-import-Component-library-issue/td-p/1785842

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thank you for letting us know the resolution so we can help others if they face this.
