### ISSUE TITLE
[ALM Accelerator - QUESTION] Interdependecy

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#4378]
### What is your question?

So ALM December depends on the Nov Creator Kit, while the Nov creator kit is available in zip format it is not available a dynamics update yet (our installation). How do we avoid this interdependency? 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

November

**Comment by mikefactorial** [comment]
@gerald560 can you provide a little more detail here? Assume this is an upgrade what version are you upgrading from? Do you already have a version of the Creator Kit installed or no? What is the error you're seeing for context?

**Comment by mikefactorial** [comment]
@gerald560 closing this out as there's been no updates here for several months.
