### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by oburgoscr** [microsoft/coe-starter-kit#4381]
### What is your question?

Hi! I hope you are doing well!

Is there a way to programmatically exempt an app or flow from receiving inactivity notifications?

I know it can be done from the tables, such as the "PowerApps Apps" table in the Core Components. Also from the Power Platform Admin View and the Cleanup Old Objects App.

Also, I could exempt the whole environment. However, I'm looking for a way to exempt all the apps and flows individually (not the environment where they are) perhaps using PowerShell, APIs, or even SQL.

My plan is to include those apps and flows later in chunks so I don't have to deal with many exception requests at once.

Thank you in advance! and great job by the way!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Sept 2022

**Comment by oburgoscr** [comment]
Thank Jenefer! So you are saying that I could download all the data, edit what is needed, and finally import that edited file?

Another solution would be to automatically approve the exempt request if the justification contains a specific phrase. ie "business critical" 

Is that a feasible way to reduce the workload for admins?

**Comment by oburgoscr** [comment]
By the way. Edit data in Excel just downloads a file with the column names but without data. 

Thanks in advance.

**Comment by Jenefer-Monroe** [comment]
Those are good ideas too yes. It really depends on what you want the roll out to look like.

**Comment by Jenefer-Monroe** [comment]
I'm not sure that I could really advice on that as I dont understand completely what you are trying to accomplish. 
I think if what you are trying to do is slow roll out the inactivity processes the easiest thing to do is probably just use the env variables and/or roll out the envts one by one. 

For the [environment variables](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components#all-environment-variables), you could set it only flag objects that havent been edited in 24 months to start for example, and then slowly ramp back to 6 months recency. 
![image](https://user-images.githubusercontent.com/89584709/206486743-69cbee0e-eaed-4453-a05b-2447a345934c.png)

Does that make sense?

**Comment by oburgoscr** [comment]
That makes a lot of sense Jenefer! Thank you so much! I will evaluate the approach you are suggesting.

Have a very nice day!

**Comment by Jenefer-Monroe** [comment]
Wonderful! I'll go ahead and close this out but please let us know if you have other questions.
