### ISSUE TITLE
[CoE Starter Kit - BUG] COE Setup Wizard is throwing an error on launch

### ISSUE THREAD

**Issue by FQ365Microsoft** [microsoft/coe-starter-kit#4383]
### Describe the issue

COE Setup Wizard (Preview) app is throwing error on Initial Setup Page.
Error Code: AppLoadFailed
Server sent an invalid response for api call: Services.LaunchAppResponse
UciError: Server sent an invalid response for api call: Services.LaunchAppResponse at s (https://xxxx.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5013-2210.4:4859:82) at https://xxxx.crm.dynamics.com/uclient/scripts/custompage.js?v=1.4.5013-2210.4:33:6668

### Expected Behavior

The app should be launched

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CoE Setup Wizard (Preview)

### Steps To Reproduce

1) It is a common issue in multiple enviornments. Just launch the app and error appears.
<img width="916" alt="image" src="https://user-images.githubusercontent.com/116768543/206399181-3b0e0fa2-da46-4ae8-857a-28ef935186b2.png">

**Comment by manuelap-msft** [comment]
Hello,

Can you go to the solution and check these flows are on:
![image](https://user-images.githubusercontent.com/55705669/206403476-25e90ae6-0017-45d2-abf6-682d3cc9ce08.png)

Are you able to open the app using Monitor feature (Select Monitor > Then "Play model driven app") and share any error messages you get from there?
![image](https://user-images.githubusercontent.com/55705669/206403675-c2bd2197-576f-4568-b4c7-6f8a403efe6c.png)

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Can you also confirm the PCF flag is enabled for your environment? 
https://learn.microsoft.com/en-us/power-apps/developer/component-framework/component-framework-for-canvas-apps#enable-the-power-apps-component-framework-feature

**Comment by manuelap-msft** [comment]
Looks like this is more a generic error with custom pages rather than with the CoE kit as the trace you shared doesn't even show any part of the CoE kit pages rendering. 

There are some known user-related issues that you can triage here - e.g. third party cookies have to be enabled etc
https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/model-app-page-issues#user-related-issues

It's also worth double checking that PCF is enabled on your environment (this is OFF by default).

It may also help to clear your browser cache and reloading the page

**Comment by MrHueb** [comment]
Hi all, currently running into the same issue.

**Comment by FQ365Microsoft** [comment]
Issue is resolved.. I restarted the browser and used Edge. This prompt the consent on the connections for first run which was getting blocked by the browser for some reasons.

**Comment by Jenefer-Monroe** [comment]
Thank you so much for circling back to us with this information. Knowing how you resolved it, and the deduction that it was about the connection, will help us help others.
