### ISSUE TITLE
[CoE Starter Kit - FEATURE] Setup Wizard - allow manually setting communication methods

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4384]
### What is your question?

Today, when you set communication methods in the setup wizard, you can only select groups from a drop down or create a new group. There could be reasons a group is not listed in the drop down but does exist and we may want to allow overriding the drop down by pasting in an ID or eMail

One reason the group could not be listed is pagination (if many groups exist)
https://learn.microsoft.com/en-us/connectors/office365groups/

We could have a better search for group experience with a text field that searches the group, rather than listing all the groups in the drop down.

### What solution are you experiencing the issue with?

Core

**Comment by ztraartz** [comment]
I just updated the environment variables using the "Setup" section within the "Admin - Command Center" app.  For the Admin persona update the variable "Admin eMail".

When you return to the Setup Wizard the "Admin persona" will be Configured.  The same process will probably work for Maker and User persona when the correct environment variables are setup.

Enviroment Variable edit: https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables

**Comment by manuelap-msft** [comment]
closing out some old issues that we missed to close. this has been fixed with the April release.
