### ISSUE TITLE
[CoE Starter Kit - BUG] - CoE Flow Run History got deleted

### ISSUE THREAD

**Issue by Gokul-JB** [microsoft/coe-starter-kit#4386]
### Describe the issue

We could not see all Run History of "Admin | Inactivity notifications v2 (Start Approval for Apps)"  flow, it seem runs history got deleted past few days.

Reason to get run history:
We are getting automated email with subject of "App owner does not have permissions to perform Archive Approval" but could not trace the run history from above mentioned flow since it got deleted

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.23

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps)

**Comment by Jenefer-Monroe** [comment]
Are you referring to this 28 day view the product provides? 
![image](https://user-images.githubusercontent.com/89584709/206462303-44a33a61-3178-44a7-b312-c6ac0c2a6f26.png)

**Comment by Gokul-JB** [comment]
I got it now, Please feel free to close the issue
