### ISSUE TITLE
[ALM Accelerator - BUG]: Managed Security Role definition overriding Unmanaged Layer after Release

### ISSUE THREAD

**Issue by sam-barrett-synsci** [microsoft/coe-starter-kit#4388]
### Describe the issue

Security Roles were created in an Unmanaged Solution with general permissions set for existing otb Tables, managed Tables, and custom unmanaged tables at this Env's level. 

![image](https://user-images.githubusercontent.com/118316484/206525705-eccd59bd-b3ce-4b39-9020-b864926c0c00.png)

This was committed and released as part of a Managed Solution to a client configuration env, successfully. The privileges configured within the original Unmanaged solution persisted appropriately. The Security roles were then added as existing Roles into an unmanaged solution within said Client Configuration Env in order to enable permissions to Custom Entities (Town) within the Client Env Unmanaged Solution.

![image](https://user-images.githubusercontent.com/118316484/206526741-f3c9c418-941d-4fcc-b8dd-e4caea72cdcf.png)
![image](https://user-images.githubusercontent.com/118316484/206527024-6ccd16c6-0f4c-4422-8ae6-12de54658ccd.png)

These changes were committed within ALM and visible within the Commit File

![image](https://user-images.githubusercontent.com/118316484/206527541-4d195c75-c5ff-47d9-ab8a-0e88769081d4.png)

After a PR, the code is merged to a Validation Env where the unmanaged changes to the Security Roles persist. However, after a new Release occurs from the Original Env (Original unmanaged solution) to the Client Env (released as Managed Solution), the unmanaged changes within the Client Env Unmanaged solution are removed, or potentially overlayed.

![image](https://user-images.githubusercontent.com/118316484/206529581-a2281ddd-7eac-4f27-bb32-7d1fd412fc6f.png)

When checking on the solution layers of said Security Role within the Client Configuration Env, the unmanaged layer still exists, but not the actual Permission adjustments.

![image](https://user-images.githubusercontent.com/118316484/206530001-9ccc9fa0-7532-4465-8617-a72701c5c0d3.png)

Other changes released from the Original env merge and layer appropriately, within the same Release.

### Expected Behavior

For the Unmanaged Layer changes within the Client Configuration Env (Unmanaged Solution) to be present and honored after an updated release from the Original Env that holds the original Security Roles.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20221102.3

### Anything else?

I have an open ticket regarding ALM not creating and associating Teams with set Security Roles and AAD Office Groups. These security roles are the same. Unsure if these two issues are related or if this related to ALM at all.
#4195

**Comment by mikefactorial** [comment]
@sam-barrett-synsci the default behavior of the pipelines is to overwrite unmanaged customizations in the deployment envrionment. There's currently no way to override this in the pipelines without modifying the pipeline template. However, you can try updating the following line of YML in your copy of the pipeline templates to see if that results in the behavior your expecting.

https://github.com/microsoft/coe-alm-accelerator-templates/blob/fbffbca36193c31da03ac4cdcadecad0531d68c2/Pipelines/Templates/deploy-Solution.yml#L16

```
- name: overwriteUnmanagedCustomizations
  type: string
  default: 'true'
```
to 
```
- name: overwriteUnmanagedCustomizations
  type: string
  default: 'false'
```
