### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by amadan1993** [microsoft/coe-starter-kit#4389]
### Describe the issue

The child Flow  " [Child] Admin | Sync Logs " is not able to establish connection with Audit Log . The connector used in the Flow is " List  Audit Log Content" 

On Flow Run , we are getting the Error message as "Alert: Your Office 365 Management API connection isn't working"

Error Details:
Looks like your flow's Office 365 Management API connection needs to be signed-in again. The most common cause is a changed password or a policy set by your tenant administrator. Connections may also require reauthentication, if multi-factor authentication has been recently enabled for your account.

![Issuw_COE](https://user-images.githubusercontent.com/120131756/206547028-b0e85a4c-a9e4-4034-a9c6-c957daf241fb.png)

### Expected Behavior

The connection should Run successfully and audit Log Data should be updated

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
Hello. Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
