### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can not find flow in dashboard

### ISSUE THREAD

**Issue by MantasSal** [microsoft/coe-starter-kit#4392]
### What is your question?

Hello,

I have created flow, but can not find it CoE dashboard.
![image](https://user-images.githubusercontent.com/114066875/206655439-c7ec2bc8-a223-4b39-85da-2f63c2dd104e.png)

I can not find it in tab Cloud flows:
![image](https://user-images.githubusercontent.com/114066875/206655809-67ba255b-2df5-4cc1-a3e9-0f96d72517cc.png)

And there is not Tweeter connector that is used in this flow in Cloud flow connections:
![image](https://user-images.githubusercontent.com/114066875/206656125-bafa0f2a-42a7-4767-aa9e-fce32cce6345.png)

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Hello, please note that there are delays between object creation and it showing up in the PowerBi.

1) The Sync flows must run - driven by the **_Admin | Sync Template v3_** flow. 
    Note that this flow itself has delays built in as well. 
    Absolute worst case scenario, if you just created the object after the last run occurred, and the max delay occurs, this could be a 2 day delay

2) The Power BI must be refreshed. This is typically done on a daily cadence but is up to you to configure. 
    [Configure Scheduled Refresh](https://learn.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh)

**Comment by MantasSal** [comment]
Hello,

Admin | Sync Template has run successfully. I can see flow name in the list:
![image](https://user-images.githubusercontent.com/114066875/207035422-5e2053de-b395-430e-8447-7b77c2132dd9.png)

But can not see Tweeter connector in Flows Connections tab:

![image](https://user-images.githubusercontent.com/114066875/207034793-868c478d-c381-4cb8-ae54-fff805fd4a7c.png)

**Comment by Jenefer-Monroe** [comment]
I'm not sure what screen you are on, but this chart cant show all the connectors, as you can see it's still showing only 2 connectors with a single connection. 
If you're in one of our screens (ex Cloud Flow Connections screen) you will see a filter where you can look for specific connectors.
![image](https://user-images.githubusercontent.com/89584709/207055904-f29b1b2f-8ae9-4dc4-a211-4d31a5624b41.png)

**Comment by MantasSal** [comment]
Hello, Sorry if I misunderstood.

in Cloud Flow Connections I can select Premium, Standart or Custom connectors. I can not see Tweeter connector anywhere. Is there another place I should look?

![image](https://user-images.githubusercontent.com/114066875/207065257-dd00c921-8ae8-4153-8f96-a5b33c44f396.png)

**Comment by Jenefer-Monroe** [comment]
Those are little drop downs you can expand to look for individual connectors. Or you can search by name.

Also I'm not sure if you are referencing the [Twitter connector](https://learn.microsoft.com/connectors/twitter/) or some custom connector you've made named Tweeter
![image](https://user-images.githubusercontent.com/89584709/207071362-8d7c486d-db2e-4e21-bf72-c16c72421af2.png)

**Comment by MantasSal** [comment]
Hello, yes, I am referencing to Twitter connector, sorry for misleading name :)
I find my flow in the list
![image](https://user-images.githubusercontent.com/114066875/207305396-7518710f-5bcc-40ef-a919-41f35f8d31e0.png)

But when I expand Connections Trend, I see selected only OneDrive connector, but there is no Twitter connector..
![image](https://user-images.githubusercontent.com/114066875/207305788-14ddae1c-8513-46ec-a2e3-2a5189ba643e.png)

**Comment by Jenefer-Monroe** [comment]
That chart still cannot show all the connections, there are probably dozens of single uses ones. 
Please use the Connector Tier, Connector filter
![image](https://user-images.githubusercontent.com/89584709/207332796-ecb45052-e251-49de-9f84-8220dfc7081f.png)

**Comment by MantasSal** [comment]
Ok, thanks, found it.
Is there a way to list ALL connectors that are used in all environments, including single ones like twitter?

**Comment by Jenefer-Monroe** [comment]
In my opinion PBI doesnt really lend itself to that kind of thing, but yes you could just put them all in a table
![image](https://user-images.githubusercontent.com/89584709/207340436-a4d1dd2b-dd53-40d4-aadb-09f7d06d79d3.png)

Or we have them in the Power Platform Admin View App
![image](https://user-images.githubusercontent.com/89584709/207341215-31832abb-d73c-42d8-b4f9-92df1064a2db.png)

I hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
