### ISSUE TITLE
[CoE Starter Kit - BUG] Usage information missing

### ISSUE THREAD

**Issue by amadan1993** [microsoft/coe-starter-kit#4394]
### Describe the issue

In the COE Power Platform Admin View , the data is not getting synced up in associated records in Grid .  Even when we have shared the app with the users, the shared users count is coming as 0 . 

So is there any flow related to this ? 

![image](https://user-images.githubusercontent.com/120131756/206668494-4b33e5c8-9e5c-48f6-9d97-397ae8f1d9e0.png)

### Expected Behavior

The associated Grid Records should be visible

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin - Sync Template | V3

**Comment by amadan1993** [comment]
Thanks for the comment . My question when you navigate to an App , ( PowerApps App) , we are looking for usage of the App. The grid below shows blank. My question here is how does this grid populates ?

**Comment by Jenefer-Monroe** [comment]
Have you setup the Audit Logs solution?

**Comment by amadan1993** [comment]
One quick question I have is that when we setup the API management in Azure AD Application , does the person who has permission to do so , should the same person need to have access to power app environment as well?

**Comment by Jenefer-Monroe** [comment]
No the app registration can be setup by anyone with those permissions. 

The person who runs the flow will just need to get the application id and secret value from them. And then have access to the audit logs. 

Be sure to write the application id and secret somewhere that you can access the again in the future

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
