### ISSUE TITLE
[ALM Accelerator - QUESTION] Environment Variables Secret

### ISSUE THREAD

**Issue by thetla** [microsoft/coe-starter-kit#4400]
### What is your question?

Hi,

Is it possible to use Environment Variable Secrets in the ALM Canvas app? We don't get it to work. If not: Is it possible to implement it? 
![image](https://user-images.githubusercontent.com/114479358/206702113-73e7f646-1bd9-4c33-9725-b46d8f90a30e.png)

Br Terje Hetland 
PowerPlatform Center For Enablement Team Equinor

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

December 2022

**Comment by thetla** [comment]
![11](https://user-images.githubusercontent.com/114479358/206702296-3a915f99-8280-4132-96bf-976f5ca65349.png)

**Comment by mikefactorial** [comment]
@thetla you can set the secret environment variables by providing the url of the secret. There are more details in this blog post https://powerapps.microsoft.com/en-us/blog/how-to-use-environment-variables-with-akv-secrets-in-the-ci-cd-pipeline-when-deploying-applications/ the format of the url looks like what is shown in the screenshot below.
![image](https://user-images.githubusercontent.com/42348035/207080202-0c843483-5165-49a9-b716-e6819b6f3aa4.png)

**Comment by mikefactorial** [comment]
Closing this out as there hasn't been activity for over a month.
