### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by russrimm** [microsoft/coe-starter-kit#4404]
### Describe the issue

When trying to create groups on the "Configure communications methods" screen I'm having two issues.
One: if I try to create a new group, I get the error: SetupWizard&gt;CreateGroup.Run failed: Connection not configured for this service.

If I open another tab and create a group and then try to point at it, the new group is not appearing in the list.  Only if I refresh the wizard canvas app can I then see the new groups I created in the other tab.  Maybe just add a refresh button to refresh the group collection there?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CoE Setup Wizard (preview)

### Steps To Reproduce

1. Proceed to step 2 of the wizard where you select your groups for each persona.  Open another tab to go to the Azure Portal, create the groups, and the only way to see it in the pick list is to re-launch the Setup Wizard canvas app.

1. Trying to create the group from the Wizard is giving the "SetupWizard&gt;CreateGroup.Run failed: Connection not configured for this service" error

![image](https://user-images.githubusercontent.com/10841574/206748514-62f80be5-ab45-4998-a747-e2b1aa92f4d4.png)

**Comment by Jenefer-Monroe** [comment]
I believe the issue with this is that the flow is not turned on by default due to another bug we have fixed for next release. 
Can you try to turn on the flow manually and try again?

**Comment by russrimm** [comment]
Yes, this was the issue, also you have to make sure it's turned on before launching the wizard app, otherwise you have to relaunch the wizard app again after starting the flow. Thanks!
