### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE PowerBI Dashboard tailored view at environment level

### ISSUE THREAD

**Issue by RakeshPower** [microsoft/coe-starter-kit#4405]
### What is your question?

Hi Experts,

We have central IT team that manages the CoE components as well as PowerBI dashboard that provide Tenant level insights.
We have multiple environments own by individual Business Units, they have requirement to get tailored CoE PowerBI report centric to their environment. Report that could provide insights centric to specific environment instead of Tenant level.

Is there a way to customized PowerBI Dashboard to provide only single environment details to share with individual owners and how to achieve it? Similar to what Power Platform Admin portal provide Environment level insights.

Can CoE Power BI dashboard customized and those reports publish to Power BI service for respective teams to access?

Regards,-Rakesh

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
Note that we did recently provide a mechanism to setup the CoE for a subset of environments. 
[Setting up CoE for a subset of environments](https://learn.microsoft.com/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments)

This would give you to own maintenance of the CoE's while giving full CoE monitor / governance / etc to these area admins

**Comment by Jenefer-Monroe** [comment]
If all you are looking for is a way to filter the PBI, I'm afraid we are not staffed to assist with customizations as a very small team. 

But thinking through the issue I would suggest perhaps if you augmented the envt table to include a column that indicated area ownership, you could provide PBI's in which you use the "transform data" features to filter to each area experts items. 

Neither the solution we released nor this would provide any row level security though.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
