### ISSUE TITLE
Playlist Items view in "Nurture apps - Admin" app should have the name of the Playlist Item.

### ISSUE THREAD

**Issue by davins-msft** [microsoft/coe-starter-kit#4408]
### Describe the issue

The View to **Playlist Items** from the left navigation, not showing the name of the Playlist Item doesn't help in knowing anything about the Item itself, as the columns displayed are Playlist and Community Hub Content. 

![image](https://user-images.githubusercontent.com/91287781/206975507-792d477c-cf52-43df-8424-0e7158edbc7a.png)
 

### Expected Behavior

The view should also have the Name of the Playlist Item displayed as the first column.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.19

### What app or flow are you having the issue with?

Nurture apps - Admin

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting, we resolved this in the December release. 
![image](https://user-images.githubusercontent.com/89584709/207058721-0d6bef86-4cca-4433-8ebe-8f229e7daeab.png)
