### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot display flows in Admin Command Center

### ISSUE THREAD

**Issue by D3L05** [microsoft/coe-starter-kit#4411]
### Describe the issue

Having the same behaviour described [here ](https://github.com/microsoft/coe-starter-kit/issues/3724), with an aditional error "PowerAutomateManagement.ListFlowsInEnvironment failed: { "statusCode": 404, "message": "Resource not found" }"

![image](https://user-images.githubusercontent.com/62146775/207053743-63230d72-2450-4d23-82a1-2f399833454f.png)

All flows runs without errors, also already check the Environment table as described in previous bug report, running CoE version 3.56
![image](https://user-images.githubusercontent.com/62146775/207054323-857355b5-e599-40b4-a020-606c9ee779bc.png)

### Expected Behavior

See the results of this Flow on the Admin Command Center.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin - Sync Template V3

### Steps To Reproduce

Open the Admin Command Center App and click on the CoE Flows option on the left menu.

**Comment by Jenefer-Monroe** [comment]
That users issue was that the CoE was not getting flagged, I presume the Yes in your screenshot is for isCoE?
![image](https://user-images.githubusercontent.com/89584709/207065039-f84f4308-6fe5-490c-97e6-96ad3c39ec34.png)

**Comment by D3L05** [comment]
Indeed 
![image](https://user-images.githubusercontent.com/62146775/207068438-23b840e1-b2bf-49e8-ab53-7f99d1b7b265.png)

**Comment by Jenefer-Monroe** [comment]
Great, thank you for confirming. 
Can you please reload the app and see if this returns? That is picked up on app start.

**Comment by D3L05** [comment]
This is weird, now its working, I check that table ten times and always was the same.

sorry, closing this.

thanks!

**Comment by Jenefer-Monroe** [comment]
No problem at all. Thank you for confirming!
