### ISSUE TITLE
[CoE Creator Kit - QUESTION] 

### ISSUE THREAD

**Issue by MarinaHadzi** [microsoft/coe-starter-kit#4413]
### What is your question?

Is it possible to edit an item from a details list? Added the command bar on top of the details list but how can I make the item in the list editable?  Both command bar and details list are part of the creator kit. Help :)

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot with me so I can more easily understand what you are hoping to accomplish?

**Comment by slaouist** [comment]
DetailsList does not support inline editing. The recomendation is to select an item in the detailslist and use the commandbar to trigger a panel or dialog where you can edit the item.
