### ISSUE TITLE
[Nurture Components] Internal Champions Program

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#442]
Tooling approach to help with facilitating an internal champions program, e.g. sign up to be a mentor, ask questions, connect people with each other, host show&tell sessions etc.

**Comment by Jenefer-Monroe** [comment]
Include information about the enabled state of makers in our Maker apps
https://github.com/microsoft/coe-starter-kit/issues/1293

**Comment by manuelap-msft** [comment]
tracking this via the Community Hub feature.
