### ISSUE TITLE
[CoE Starter Kit - BUG] Setup wizard "view details" links are not working

### ISSUE THREAD

**Issue by ashlega** [microsoft/coe-starter-kit#4420]
### Describe the issue

Highlighted link does not open properly (there are a few pages with "view details" link, but I only tried this one):

![image](https://user-images.githubusercontent.com/5911927/207345723-e88d2c7d-67b6-419d-9b26-0a2c303b00a2.png)

Once the second "/" is removed from the url, it works:

![image](https://user-images.githubusercontent.com/5911927/207346645-a25adb5a-44a0-4434-bf4e-d2874b62c08c.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Setup Wizard

**Comment by manuelap-msft** [comment]
Fixed locally ready for February release.
