### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Power Platform Admin View Quarantine Apps Issue

### ISSUE THREAD

**Issue by keharrin** [microsoft/coe-starter-kit#4422]
### Describe the issue

Using the Power Platform Admin View, I have selected apps that we have determined need to be quarantined.

I go to the Governance tab for the app, select Quarantine App and set to Yes, and then I Save & Close

I have tested running an app where the Quarantine App is set to yes and it still plays.  I expected a request access screen or an app has been quarantined message.

The next day the Governance tab is showing the Quarantine App selection set back to No

I read the documentation, but I could not find if there is a flow or flows that the Poer Platform Admin View is dependent on for this setting to stick.

### Expected Behavior

The expected behavior would be that the setting for Quarantine App would remain at Yes and the app would be unavailable for use.
![image](https://user-images.githubusercontent.com/77410660/207353313-ce35508a-f25c-47c0-9ae9-7a4e12804ff3.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

Run the Power Platform Admin View application using the Power Platform admin account
Select an app for quarantine
Go to Governance tab, set Quarantine to Yes
Click Save & Close
Test running the app

**Comment by Jenefer-Monroe** [comment]
Did you turn on the required flows? Please see [turn on the flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-quarantine-components#turn-on-flows) from the [Set up app quarantine components](https://learn.microsoft.com/power-platform/guidance/coe/setup-quarantine-components) article

**Comment by keharrin** [comment]
We are concerned that activating these flows will automatically quarantine apps.  Is this true?

**Comment by Jenefer-Monroe** [comment]
This flow **_Admin | Quarantine non-compliant apps_** will quarantine apps automatically if they have been requested for compliance information but they did not respond in 7 days. 

This will only happen if you are using the [compliance auditing processes](https://learn.microsoft.com/power-platform/guidance/coe/example-processes). See [Setup of Compliance Processes](https://learn.microsoft.com/power-platform/guidance/coe/setup-governance-components)

The number of days is configurable by env var Quarantine Apps after x days of non-compliance, see [Update environment variables](https://learn.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables)

**Comment by Jenefer-Monroe** [comment]
This flow **_Admin | Set app quarantine status_** actually performs the quarantine or release, if set by the ux you show or programmatically.

**Comment by keharrin** [comment]
We turned on the **Admin | Set app quarantine status**  flow and used Power Platform Admin View app to set the quarantine status to yes.  The flow ran successfully but it released the quarantine status.  I think it is due to not implementing the full compliance apps and flows. 

Is there a way to quarantine an app without implementing the compliance flows and apps?

**Comment by keharrin** [comment]
Thanks It is working now.  I see that the trigger is added, modified or deleted.  Yesterday we updated before we turned on the flow.  I just quarantined an app and see that it is going down the correct path now.

Thanks as always for your assistance.

Have a wonderful holiday season!

**Comment by Jenefer-Monroe** [comment]
wonderful, thanks for the update.
