### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Sync Template v3 (Flow Action Details) Fails

### ISSUE THREAD

**Issue by MantasSal** [microsoft/coe-starter-kit#4423]
### What is your question?

Hello, flow Admin | Sync Template v3 (Flow Action Details sometimes fails. Should we ignore this error? 

![image](https://user-images.githubusercontent.com/114066875/207355700-970fb349-1400-468b-a878-f43d8c560975.png)

![image](https://user-images.githubusercontent.com/114066875/207356587-65855230-5c7f-41eb-876d-6b61e2525226.png)

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
What version of Core are you on? 

Can you please drive down into this scope to find the actual point of failure? 
![image](https://user-images.githubusercontent.com/89584709/207465296-c7b8142d-f01d-43c2-90a5-74824fecca1b.png)

**Comment by MantasSal** [comment]
Could you please, help me find what version I am using? Where should I find it in dashboard?

Actual point of failure:
![image](https://user-images.githubusercontent.com/114066875/207852613-a7c10064-5b26-4ff0-acb0-ec219ec0f714.png)
![image](https://user-images.githubusercontent.com/114066875/207853053-f3a3d78c-70ff-4249-a477-e493eb96ac13.png)

**Comment by Jenefer-Monroe** [comment]
To see the version of Core you are on, go to the solutions page 

![image](https://user-images.githubusercontent.com/89584709/207876217-f9f34997-d013-49ec-9b34-3d721e3d4874.png)

**Comment by Jenefer-Monroe** [comment]
With this one and https://github.com/microsoft/coe-starter-kit/issues/4266, it appears that your user does not have PP Admin role or your license permanently assigned, or there is some other issue with your user. 

Can you please go to Azure Portal, look up the user running these flows, and let me know when you see for this role? 
![image](https://user-images.githubusercontent.com/89584709/207877334-f1746f0d-e932-4a91-8b52-acb73c26a9ed.png)

**Comment by MantasSal** [comment]
Hello,
here is what I see in Assigned roles:
![image](https://user-images.githubusercontent.com/114066875/208390186-4de2bb6c-31b2-468b-ae76-6b59c62beb89.png)

Version:
![image](https://user-images.githubusercontent.com/114066875/208390546-bd479bb4-f9b9-4bfe-9a2d-33294995cc4d.png)

**Comment by Jenefer-Monroe** [comment]
Can you please get me the whole message from here? 
![image](https://user-images.githubusercontent.com/89584709/208424123-a5558cbc-948c-4c58-8d47-967ee15a9e66.png)

**Comment by MantasSal** [comment]
Hello,

Last time it failed was in mid of December, now it is working ok. I think we can close this case.

Thanks,
Mantas

**Comment by Jenefer-Monroe** [comment]
Sounds good. Seems like you still have an issue with your identity but we can track that with https://github.com/microsoft/coe-starter-kit/issues/4266

Will go ahead and close out.
