### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Inactivity notifications v2 (Start Approval for Apps)

### ISSUE THREAD

**Issue by bwieland86** [microsoft/coe-starter-kit#4424]
**Describe the issue**
Workflow failed within the "Get Assignee" switch branch on the switch statement after Recheck Orphan Status, stating that property "statusCode" cannot be selected, as the previous action, "Recheck Orphan Status" appears to only select the displayName and mail fields from the user profile action

**Expected Behavior**
The "Recheck Orphan Status" (Get user profile) action should include the "statusCode" field in the selected fields if it is to be referenced by another action

![Admin Inactivity notifications v2 (Start Approval for Apps)](https://user-images.githubusercontent.com/13457692/207360431-b22cc609-3599-42c2-b9c6-255227e6652f.PNG)

**What solution are you experiencing the issue with?**
Governance

What solution version are you using?
3.2

What app or flow are you having the issue with?
Admin | Inactivity notifications v2 (Start Approval for Apps)

Steps To Reproduce
No response

Anything else?
No response

**Comment by Jenefer-Monroe** [comment]
Did a quick scrub and it looks like two of our flows were impacted:

- Admin | Inactivity notifications v2 (Start Approval for Apps)
- Admin | Inactivity notifications v2 (Start Approval for Flows)

In these three spots
![image](https://user-images.githubusercontent.com/89584709/207460793-aa78c3b9-bae4-41b8-a9aa-5c412302e588.png)
![image](https://user-images.githubusercontent.com/89584709/207460812-6f0118ea-d6e0-483f-a040-505aa8de5b87.png)
![image](https://user-images.githubusercontent.com/89584709/207460850-ca7dd24f-948b-4046-b9bf-fa8c0a6ae21a.png)

**Comment by Jenefer-Monroe** [comment]
We have this local fixed and are considering reshipping the Gov solution for them.

**Comment by Jenefer-Monroe** [comment]
We are reshipping the December version of Gov for this bug. Thank you so much for posting!

**Comment by Jenefer-Monroe** [comment]
We have reshipped the governance solution. Thank you again for posting!
[CenterofExcellenceAuditComponents_3.3_managed.zip](https://github.com/microsoft/coe-starter-kit/files/10228770/CenterofExcellenceAuditComponents_3.3_managed.zip)
