### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Inactivity notifications v2 (Clean Up and Delete) - fails

### ISSUE THREAD

**Issue by johnravas** [microsoft/coe-starter-kit#4425]
### Describe the issue

When we run this flow, it reviews all of the flows approved for deletion.  It deletes many of them.  However, it does not even attempt to review the canvas apps because it fails when reviewing some of the flows.

The "Get Flows workflowentityid to see if in solution" action fails with a not found error:
![image](https://user-images.githubusercontent.com/59970962/207395740-4d8d89c0-f471-49f9-8c70-c8ae71801436.png)
When you look at the outputs from the action, you see more details on the error:
![image](https://user-images.githubusercontent.com/59970962/207396032-499f3ab0-447f-41d0-ba83-547a5256c624.png)
The ID points to the flow that is being evaluated for deletion.

When you get this error, it seems to skip the canvas apps:
![image](https://user-images.githubusercontent.com/59970962/207396210-b53e6da8-7592-4996-a135-7b384494e575.png)

### Expected Behavior

Expect it to delete all of the flows and canvas apps approved for deletion

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.23

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Clean Up and Delete) 

### Steps To Reproduce

Run the flow

**Comment by Jenefer-Monroe** [comment]
For the flow side, did this action fail? 
![image](https://user-images.githubusercontent.com/89584709/207464782-37527cf5-44dc-4843-a9e7-b6245f03224a.png)

If so it should have been caught by this variable catch. 
![image](https://user-images.githubusercontent.com/89584709/207464926-8e972448-3b4c-4de1-b91e-8ac9646c6a24.png)

**Comment by johnravas** [comment]
Hi Jenefer - here is what I am seeing.  Under Apply to each flow, there are 38 flows that are being reviewed.  Of those, 5 failed: 15, 26, 29, 30 & 34.  Additionally, a couple showed as not found under See if flow exists.  Here is one of the Notfounds:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/59970962/207620702-bac5df6a-edc7-493f-be91-0adfc2c7ba0f.png">
For the Apply to each flows that failed, here is what I see for See if flow exists:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/59970962/207621120-37fcd6c8-88af-4e94-a3f8-6ae88328e882.png">
Let me know if you need anything else.

To myatix's point - On Oct 11, I did my last upgrade of the CoE using the October 2022 release.  I am running Core 3.53 and Governance 2.23

**Comment by Jenefer-Monroe** [comment]
Before we talk about why it failed to retrieve the flow sometimes, lets make sure this (Clean Up and Delete) flow is in order. 

When the flow fails here
![image](https://user-images.githubusercontent.com/89584709/207655550-ca543508-23b2-420a-9b44-717364911684.png)

Does it catch so that alreadyDeleted is set to true? 
![image](https://user-images.githubusercontent.com/89584709/207655656-757318bb-adac-47e7-b4d5-6fad17e3e26a.png)

**Comment by johnravas** [comment]
Yes, seems to:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/59970962/207697588-b48b8bf7-ba5d-4dba-aab8-ea9ac4f7f6c3.png">

**Comment by Jenefer-Monroe** [comment]
Can you find the case where it failed here and let me know if that was caught? 
![image](https://user-images.githubusercontent.com/89584709/207699112-de6c15e3-ec7f-45b0-a099-1814e046b9d0.png)

**Comment by johnravas** [comment]
Thanks Jenefer.  Let me know if this gives you what you need:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/59970962/207711041-9ac45971-cf53-445d-9b16-fdbd70cb8e16.png">

**Comment by Jenefer-Monroe** [comment]
if you move up in the flow above this
![image](https://user-images.githubusercontent.com/89584709/207717323-227ce487-56de-4716-b13a-756d58f83d46.png)

What happens here for this failure
![image](https://user-images.githubusercontent.com/89584709/207717515-03f69faf-c7fc-4911-b233-a535b5eba853.png)

**Comment by johnravas** [comment]
Here you go:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/59970962/207969859-fb465bb1-be96-4de2-968d-1ecc4dca9a91.png">

**Comment by Jenefer-Monroe** [comment]
sorry that's still not what I need. 

You see this exact falure that you posted. In this failure, see if flow exists fails. (the screenshot you shared in the previous comment is of it passing)
Find this exact failure that you posted at first, of this flow failing to be retrieved. 
![image](https://user-images.githubusercontent.com/89584709/207972246-c5c7303c-e81a-458a-97bc-474f3a7e18ca.png)

Then what happens directly below it. Your picture cut off so I could not see. Is that failure caught?

**Comment by johnravas** [comment]
Sorry for that.  I hope this works:
![image](https://user-images.githubusercontent.com/59970962/207974819-16b2ce90-586e-4df0-9dd3-c73528caee0c.png)

**Comment by Jenefer-Monroe** [comment]
ok thank you. I assumed that is what happened. But I dont understand why it went down that path to failure, it shoudl have gone down this path, the flow already deleted path

![image](https://user-images.githubusercontent.com/89584709/207976097-8dd1f525-5df5-47cd-8a03-5c59bbcea2dd.png)

**Comment by Jenefer-Monroe** [comment]
Now that I see it, it does appear you are out of date, we've used helper flows here for a while, it should look like this. 
![image](https://user-images.githubusercontent.com/89584709/207976268-e2707f54-8aa6-4961-bbab-29e3d6542688.png)

Can you please check for unmanaged layers on this flow?

**Comment by johnravas** [comment]
We are running v2.23 of the governance module - upgraded in October.  No unmanaged layers:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/59970962/207977104-16a031d2-3343-4ae8-bab4-b2b26fa31a91.png">
Should we upgrade to December for a fix? Thanks so much for the assistance.

**Comment by Jenefer-Monroe** [comment]
I thought we made this change further back than that, but perhaps not. Yes please upgrade to Dec, its a great release! And we wont be releasing again until Feb as we are taking Jan off :)

**Comment by johnravas** [comment]
Will do.  Thanks for the assistance and Happy Holidays!!

**Comment by Jenefer-Monroe** [comment]
Happy holidays to you too!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
