### ISSUE TITLE
[CoE Starter Kit - Feature]: Bulk Delete Feature from Power Platform Admin View

### ISSUE THREAD

**Issue by MarkusBeheim** [microsoft/coe-starter-kit#4428]
### Describe the solution you'd like

We start using the COE after having Users playing around in the Default Environment for serveral years. So there is a lot of "trash".
The "Power Platform Admin View" App provides very impressive filtering options on Apps, Flows, ...  e. g. Cleanup old (2020 and older) Canvas Apps without Owner and Non-Shared
Filter:
App Environment: Evonik Industries AG (default) (Upgrade)
App Owner: -blank>
App Type: Canvas
App Last Launched: <blank>
App Last Modified: 31.12.2020 or older
Total Shares: 0

When I use this filter I find several hunderts of Apps I would like to just delete.
The "Delete" Button (removed in the latest version) did not work like expected, since it only removes the Entries from the Dataverse Tabel instead of deleting the Apps on the Environment.
My request is an option that allows Admins to bulk delete and/or archive Apps / Flows directly from the "Power Platform Admin View" App.

**Comment by MarkusBeheim** [comment]
Hello Jenefer,
thanks for your quick answer! :)
The problem is, that this flow will not work if the Owner is not set. This is a condigion of the filter above.
Rui from the power Cat Team recommended to export an excel list, write an PowerAutomate to delete the App based on this list. Do I get you right that this would not be supported yet?
We are also looking into the Inactivity Process Options provided, helping to prevent creation more of those orphand objects in the environemnt. In our case, it is already to late for some of the items.

**Comment by Jenefer-Monroe** [comment]
Rui's recommendation would work, I simply meant that multi-select delete from within the Power Platform Admin App (putting the delete button back there but making it delete from tenant) will not be possible until some product work occurs.
![image](https://user-images.githubusercontent.com/89584709/207873407-2b8df1fc-5e80-4cc9-a7fd-35a8db892f4d.png)

**Comment by Jenefer-Monroe** [comment]
For orphaned objects in particular, you can still do the inactivity processes, they would just go to the admin to approve for deletion. 
Orphan objects have another option though which is in the Set Flow Permissions (and Set App Permissions) apps. 

![image](https://user-images.githubusercontent.com/89584709/207872914-5387d4fa-c5d3-4360-95a5-a271a2e5a978.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
