### ISSUE TITLE
[CoE Starter Kit - QUESTION] Do we see Dataverse for Teams environments that have been flagged as inactive inside the COE dashboard?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4433]
### What is your question?

Do we see Dataverse for Teams environments that have been flagged as inactive inside the COE dashboard?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Yes all environments that are inactive are flagged in that report. Note that for us, inactive environments just means no apps or flows
![image](https://user-images.githubusercontent.com/89584709/207672218-2b3badb0-cc97-4777-8733-a6f5716346fe.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
