### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can we see how many users apps and flows are shared to?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4435]
### What is your question?

Can we see how many users apps and flows are shared to?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
We do not store this today for flows, see https://github.com/microsoft/coe-starter-kit/issues/1083
But we do store it for canvas apps. So for those you can add that column to the PowerApps Apps page in the **_Power Platform Admin View_**  and get an idea of the tenant sharing landscape
![image](https://user-images.githubusercontent.com/89584709/207674131-126ca561-a4bc-41a5-a654-a42046f179ef.png)

You can see who an individual app or flow is shared with in the **_Power Platform Admin View_** app as well: 
![image](https://user-images.githubusercontent.com/89584709/207674486-3887223c-58ad-409b-bbb3-8e2990164de9.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
