### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can the admin of a app request change some request values or only approve / reject? Maybe some connectors are not to be used or they chose the wrong one which should be used instead.

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4436]
### What is your question?

Can the admin of a app request change some request values or only approve / reject? Maybe some connectors are not to be used or they chose the wrong one which should be used instead.

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont understand this one, if you posted can you please provide some more details?

**Comment by manuelap-msft** [comment]
Hello,

yes, admins can change all details using the Edit Details section. They can also add security groups and view/modify DLP policies applied to the environment.
![image](https://user-images.githubusercontent.com/55705669/207674515-10194792-352e-46e6-8a66-e0e57004f8e1.png)

For the connectors requested - this only serves to show you the intent of what the maker would like to use but doesn't create or modify the DLP policy - the Data Policy section will then show you if existing policies you have cover this new environment, and you can create new policies from there as well for this environment. If the maker picked an incorrect connector that you don't allow, you can use the Email admins button to email them and let them know and just apply a policy accordingly.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
