### ISSUE TITLE
[CoE Starter Kit - QUESTION] I recall that there was a feature either in the Kit or somewhere where you can "preview" the effect of changing a DLP setting (via the Editor) ... is that there or is that a feature that does not exist?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4437]
### What is your question?

I recall that there was a feature either in the Kit or somewhere where you can "preview" the effect of changing a DLP setting (via the Editor) ... is that there or is that a feature that does not exist?

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
Yes, that's what the DLP Editor v2 part of the Core Components solution is there for: https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components#dlp-editor-v2

You can preview impact in the app and get a list of impacted apps/flows send to you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
