### ISSUE TITLE
[CoE Starter Kit - QUESTION] For the Environment Request App. Is there a way that users could request DLP changes to already existing environments on this app?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4438]
### What is your question?

For the Environment Request App. Is there a way that users could request DLP changes to already existing environments on this app?

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
Yes, makers can request for policies to be applied to their existing environments through the DLP Policy Change request option in the same app: https://learn.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt#developer-request-a-dlp-policy-change

Note that admins need to make policies visible to makers (which they can do in the Admin Environment Request app) first before makers can request them.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
