### ISSUE TITLE
[CoE Starter Kit - QUESTION] I am looking for instructions to integrate the COE Dashboard PBI with the Set App Permissions and Set Flow Permissions applications

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4440]
### What is your question?

I am looking for instructions to integrate the COE Dashboard PBI with the Set App Permissions and Set Flow Permissions applications

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
Here's how to configure the embedded apps:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
