### ISSUE TITLE
[CoE Starter Kit - QUESTION] Roadmap for the "setup wizard" ?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4441]
### What is your question?

Roadmap for the "setup wizard" ?

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
There's two features we don't yet have wizard experiences for - the audit log and innovation backlog, so that's on our list. And then there's the configuration of app registrations and related Azure activities that we'll have to figure out. 

The rest of the roadmap is in line with our feature roadmap - if we launch a new feature, it should have a setup wizard immediately. 

But for the existing wizards it's listening to feedback, seeing what works/doesn't work and evolving from there.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
