### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log custom connector authentication

### ISSUE THREAD

**Issue by CN500** [microsoft/coe-starter-kit#4442]
### Describe the issue

I am trying to run the Audit log flows - Admin | Sync Audit logs which invokes the child flow _[Child] Admin | Sync logs_. The parent flow is failing in the step to invoke the child flow. Following are the errors

**On parent Flow : Admin | Sync Audit logs**

Failed to parse invoker connections from trigger 'manual' outputs. Exception: Could not find property 'headers.X-MS-APIM-Tokens' in the trigger outputs. Workflow has connection references '["shared_admin-5foffice-20365-20management-20api-5f7fc9343cf45734fe"]' with invoker runtime source.

![image](https://user-images.githubusercontent.com/120587297/207662856-f03260df-11d1-41e5-94e0-07a72441d570.png)

Also there is a flow check error on the parent flow which says: **Update the child flow for action 'Run_a_Child_Flow' to not use 'run-only user' connections.**

**On Child flow: [Child] Admin | Sync logs**

Failed to parse invoker connections from trigger 'manual' outputs. Exception: Could not find property 'headers.X-MS-APIM-Tokens' in the trigger outputs. Workflow has connection references '["shared_admin-5foffice-20365-20management-20api-5f7fc9343cf45734fe"]' with invoker runtime source.

![image](https://user-images.githubusercontent.com/120587297/207663609-33911331-2b72-4bf4-8e62-1b996f2046a3.png)

Following are the headers

Accept-Language
en-US
User-Agent
azure-logic-apps/1.0,(workflow b8a860d5961940829ef1b38cf7617118; version 08585305726499341529),microsoft-flow/1.0
x-ms-workflow-id
b8a860d5961940829ef1b38cf7617118
x-ms-workflow-version
08585305726499341529
x-ms-workflow-name
ec4b7ef4-8241-309c-82cc-a4e76d14f902
x-ms-workflow-system-id
/locations/westeurope/scaleunits/prod-34/workflows/b8a860d5961940829ef1b38cf7617118
x-ms-workflow-run-id
08585305724360453103555114236CU196
x-ms-workflow-run-tracking-id
f54ccf40-c65a-4aff-ac4d-a184d8200e50
x-ms-workflow-operation-name
Run_a_Child_Flow
x-ms-workflow-repeatitem-scope-name
Apply_to_each_timeSegment
x-ms-workflow-repeatitem-index
3
x-ms-workflow-repeatitem-batch-index
0
x-ms-execution-location
westeurope
x-ms-workflow-subscription-id
34eedfbf-3e33-475d-b510-23537fba3dc9
x-ms-workflow-resourcegroup-name
FAD75A54A3234CD08E516A8D57035AA8-C3A03218E3644A87B0A3DC44EEF95DC2-ENV
x-ms-tracking-id
552fe0a2-003d-42f8-b571-fc944b65c973
x-ms-correlation-id
552fe0a2-003d-42f8-b571-fc944b65c973
x-ms-client-request-id
552fe0a2-003d-42f8-b571-fc944b65c973
x-ms-client-tracking-id
08585305724360453103555114236CU196
x-ms-action-tracking-id
ea1612be-c6f5-4783-ae3e-49601b384939
x-ms-activity-vector
00.00.IN.2B.IN.0R.IN.1W
Content-Type
application/json; charset=utf-8
Content-Length
127

----------

Also I see an issue with the connectors in the child flow

![image](https://user-images.githubusercontent.com/120587297/207665855-c974fcfc-03d6-4924-9f18-6be3474be330.png)

Configure Run Only users
![image](https://user-images.githubusercontent.com/120587297/207664882-eb6e2ca1-f7ca-4408-aaee-749f741974cc.png)

### Expected Behavior

I would like this flow to run without errors

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.9

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by manuelap-msft** [comment]
Hello,

thanks for the detailed description of the issue!

For all the connections, they have to be set to "Use this connection" (see Step 9 here https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow). If this isn't available, it means your user doesn't have a valid connection to the custom connector.

To fix this, try
1. Navigate to make.powerapps.com > select your CoE environment
2. Select Dataverse > Connections
3. Select + New Connection
4. Search for the Office 365 Management API and try to establish a connection to this connector. If that fails, it's possible the custom connector is not configured properly. If that's the case, please revisit these steps https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector

Note that you if you have upgraded the solution, you will have to re-authenticate the connector with every upgrade - steps are described here: https://github.com/microsoft/coe-starter-kit/issues/1424

**Comment by ClaudiuVio** [comment]
For our environment, the steps posted by Manuela are not working.

We need to edit the custom connector and re-enter the required data in the security tab, save and then go to the last tab TEST and make a new connection. Everything is OK after this.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
