### ISSUE TITLE
[CoE Starter Kit - BUG] 4.2 Core Components installation fails with Missing Dependencies error

### ISSUE THREAD

**Issue by raphaeltremblay1966** [microsoft/coe-starter-kit#4443]
### Describe the issue

Hello - We are upgrading Core Components 3.56 (Nov 2022) to 4.2 (Dec 2022) and we have the error Import failed due to missing dependencies for Center of Excellence - Core Components, related to CreatorKitCore.

![image](https://user-images.githubusercontent.com/99994964/207699228-ff837726-34ed-441a-b867-8d02eaf66eb5.png)
![image](https://user-images.githubusercontent.com/99994964/207699295-9b58169f-4580-479b-a3ab-7b8ed08bf962.png)

We are trying this on 2 different working environments with 3.56. What is the issue ? 

[log(2).txt](https://github.com/microsoft/coe-starter-kit/files/10231133/log.2.txt)

### Expected Behavior

Solution is not imported

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Core

### Steps To Reproduce

See pictures.

**Comment by petepuu** [comment]
@raphaeltremblay1966,  CoE StarterKit Core Components December release is the first version of the kit which requires CreatorKit as prerequisite as the new Setup Wizard uses controls from CreatorKit. So, just download and install the latest version of CreatorKit or install it from the AppSource before upgrading the Core

https://aka.ms/creatorkitdownload

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
