### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade Wizard: View details button link broken

### ISSUE THREAD

**Issue by rrwolfe** [microsoft/coe-starter-kit#4445]
### Describe the issue

Issue: When clicking on the "View details" button in the Upgrade Wizard, there appears to be an / causing the link to break.

![image](https://user-images.githubusercontent.com/74214126/207737229-addffb9d-3ea4-46cc-a1d7-02f200015eda.png)

![image](https://user-images.githubusercontent.com/74214126/207737774-fad6dc64-1953-4be9-95d2-8d0eb4e91bc1.png)

### Expected Behavior

The solution history page should load successfully without the additional / in the URL.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CoE Setup Wizard

### Steps To Reproduce

1. Go through the initial setup steps
2. During the Confirm pre-requisites > Upgrade History page click on the View detail button
3. A new browser tab will open with the broken link

**Comment by manuelap-msft** [comment]
Hello,

thanks for raising this - we're already tracking this under https://github.com/microsoft/coe-starter-kit/issues/4420 so I'm closing this issue as a duplicate.

Thank you
Manuela
