### ISSUE TITLE
CoE Child Flow Subscription Disabled Error

### ISSUE THREAD

**Issue by shailan76** [microsoft/coe-starter-kit#4449]
Another issue with te child flow in the CoE. Looking at the flow runs it mentions subscription disabled. This seems odd as all the Azure subscriptions are active. 
Everything is now configured, however there is a small issue when it is trying to run the flow. 
The error mentions “The subscription was disabled.”
![image](https://user-images.githubusercontent.com/117372397/207835236-ff6440ed-5856-4c6e-9a1a-88b873dfa04a.png)

Any ideas?

**Comment by manuelap-msft** [comment]
We'll need a little bit more info to help you out here, what flow specifically is failing, where in the flow are you seeing this issue etc?

My guess is that this is related to the Audit Log flows. If so, you likely missed to complete the step to start a subscription from the custom connector to the Audit Log: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content

But if my guess is wrong, please share more details here! Thank you!

**Comment by shailan76** [comment]
> We'll need a little bit more info to help you out here, what flow specifically is failing, where in the flow are you seeing this issue etc?
> 
> My guess is that this is related to the Audit Log flows. If so, you likely missed to complete the step to start a subscription from the custom connector to the Audit Log: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content
> 
> But if my guess is wrong, please share more details here! Thank you!

Thank you, that has resolved it! Many thanks.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
