### ISSUE TITLE
[CoE Starter Kit - BUG] App in Power BI showing disconnect error

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#4450]
### Describe the issue

If I try to drill through the cloud flow detail in the CoE Power BI report I get an error stating 'Sorry, there's been a disconnect'. I understand that the error is reporting the disconnect with the app. The issue occurs using Power BI desktop and Power BI Online where I am logged in with the Power Platform Service Account that is used for the CoE kit. This has never worked and not sure if this is a bug or an issue specifically with my configuration. 

The CoE has been installed in an environment called 'Prod Government Environment', I have TDS set to 'On' and the database version is 9.2.22112.00186

Is there a way to identify which app the Power BI report is trying to connect to? I can then check to see whether the app has been shared correctly. 

I have checked historic issues and can't see anyone else reporting this
<img width="355" alt="Power BI CoE Error" src="https://user-images.githubusercontent.com/117096415/207858939-f7d8955a-3888-4a2f-b5be-8a1f73e32b4a.PNG">

### Expected Behavior

The app should open in the Power BI report to provide the drill through detail of the flow

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Unable to identify app

### Steps To Reproduce

1. Open CoE Power BI report
2. Select Cloud Flows tab
3. Right click on a flow --> Drill through --> Cloud Flow Detail
4. Under the Manage Flow section the visual should connect to the Power App and is showing 'Sorry, there's been a disconnect'

**Comment by G1982C** [comment]
That has worked, thank you. I did run through all the steps when I installed with Microsoft, so perhaps it did work at some point. 

Thank you again, this is going to make my life so much easier for granting permissions.

**Comment by manuelap-msft** [comment]
Great, thanks for confirming! We also added the ability to update and manage permissions to the Power Platform Admin View with the December release (4.2) if you want to try that out: https://github.com/microsoft/coe-starter-kit/issues/941#issuecomment-1335705964

I'll go ahead and close that issue but please let us know if you have any other questions!
