### ISSUE TITLE
[CoE Starter Kit - QUESTION] Approvals User security role not auto-populated with makers assigned an approval

### ISSUE THREAD

**Issue by mknightca** [microsoft/coe-starter-kit#4451]
### What is your question?

What access should general users have to the CoE environment? 

We ran one of the governance components the other day "inacitivty notifications/check/cleanup" flows and noticed that anyone who isn't in the environment security group (any maker) doesn't get the email. 

We really don't want to remove the security group and give all users access but it seems like it might have to be the case. Each of our 1000+ users are licensed for power apps and can go to the default enviornment to build. But we wanted to hide CoE env from them so they don't do anything in there.

Is there a way to ensure all users in our org will get any flow notifications when necessary (we don't know if a new maker will start building tomorrow) but still hide the enviornment from being accessible? All this without just adding every user or maker to the group too?

### What solution are you experiencing the issue with?

governance

### What solution version are you using?

2.25

### What app or flow are you having the issue with?

Inactivity notifications

**Comment by Jenefer-Monroe** [comment]
The expected behavior here is that users are added to the **_Approvals User_** security role in the envt by the product automatically when you assign them an approval. This does not give them access to the envt other than responding to approvals. 

There are some exceptions and reasons this wont occur, the main one we have seen is that you have used a security group to secure the envt. Note that if you do this, then the approvals users will not be auto-populated when you assign an approval. 

Please see notes in our [Create your environment](https://learn.microsoft.com/power-platform/guidance/coe/setup#create-your-environment) documentation.

**Comment by Jenefer-Monroe** [comment]
Please let me know if that answers your question or if I can help in some other way.

**Comment by mknightca** [comment]
thank you for following up

to the first point: if we remove the security group this gives all users access to the environment as a 'basic user' which is how i understand it. It would be the same as the default environment. Is this not your experience?

as for the workaround: I don't recall anything about a Maker Security Group in any of the setup instructions. Can you direct me somewhere if there was instructions in the wiki? If I can automate anyone who's a maker and have them put into a security group that's great but are we talking about a team or a group here?  Each env you have to use teams to assign roles and can assign users to the team. This doesn't matter if the env is locked down to a security group as they still have to be a member of the security group as well. You can have a group then be a member of a team if you want to automate it but I have a very simple setup. Just a production env with coe installed, and access is locked down via a security group with about 6 members.

**Comment by Jenefer-Monroe** [comment]
No that is not my experience. By default the envt will just have the sys admin role filled with the envt creator and the Power Platform Admins. 

The Maker Group is described here: [Maker Group](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users)
Today in the kit we use it only in the [Admin | Welcome Email v3](https://learn.microsoft.com/power-platform/guidance/coe/core-components#flows-2) flow which adds new makers to the group. And then you can use it to share Maker oriented apps and security roles.

**Comment by mknightca** [comment]
Thank you, we we're running that flow yet as we were avoiding most things that sent any communications. I see it wants us to create mail enabled security groups for the 3 profiles (admin, maker, user).  That flow doesn't suggest it adds people to a security group though. I will look into this as I only had a brief look. 

I also see this now: "Don't restrict environment access with a security group, because some parts of the CoE Starter Kit use [approval actions](https://learn.microsoft.com/en-us/power-automate/get-started-approvals) and require makers to be able to interact with the environment."]

Please close this ticket and thanks for your on going support

**Comment by Jenefer-Monroe** [comment]
oh yes sorry, this is the flow that adds them to the group. **_Admin | Add Maker to Group_**

sorry about that. we seperated out the behavior and I forgot its a sep flow now
