### ISSUE TITLE
[ALM Accelerator - DOCS]: Confusion between pipeline names while manual Setup

### ISSUE THREAD

**Issue by ShinraTenseiii** [microsoft/coe-starter-kit#4455]
### Describe the issue

When we are creating deployment pipelines in DevOps I am confused about the names of the Pipeline. Which solution name are we talking about? MyNewSolution or SampleSolution. Are they the same solution? I am facing some issues with permissions while installing it with CoE-Cli so doing it manually. Please guide me in the right direction.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20221206.2

### Steps To Reproduce

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-the-solution-build-and-deployment-pipelines

If we go to the 18th point it says to create the pipelines with the preceding steps for each environment. But I am not sure what name to give to the pipeline.

**Comment by mikefactorial** [comment]
@ShinraTenseiii thanks for the question some of the content in that doc may be out of date. You no longer need to manually setup deployment pipelines. The deployment pipelines will be generated automatically for you the first time you export a solution. Would recommend following the steps here https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-preview which is the more straightforward approach to setup. Note we will be doing some refreshes of our docs in the coming months.

**Comment by mikefactorial** [comment]
To answer your original question though the table should be specifying the SampleSolution YAML files.

**Comment by ShinraTenseiii** [comment]
SampleSolution should be written as it is?

**Comment by ShinraTenseiii** [comment]
Thanks Mike. It all worked out fine with the documentation you mentioned.
The Commit Solution works fine but when I use Deploy Solution it shows me an error.

![image](https://user-images.githubusercontent.com/84532843/208182461-da2ad93b-4e4c-4a6b-85da-41cc61d7902b.png)

Is there something I did wrong?

**Comment by ShinraTenseiii** [comment]
Hi Mike,
Can you please share your views on this one.

**Comment by piyushpaliwal** [comment]
@ShinraTenseiii I know this is an old thread, but if you are still stuck here, the answer lies in `Service Connections`. You may have modified the connection to make it more readable or something.
See if this resolves your problem

![image](https://user-images.githubusercontent.com/635693/210085792-c04922be-c79e-4429-ac96-51adc0d4d62c.png)

**Comment by RajeevPentyala** [comment]
@ShinraTenseiii Please let me know if you are still blocked with the 'Service Connections' issue. As @piyushpaliwal rightly pointed out that you need to have "Service connection name" exactly matched to 'Server URL'. Alternatively, if you want to go with custom names for your "Service connection name", follow below steps.

- Open "ALM Accelerator for Power Platform Administration" Model Driven App, which comes with 'ALM Accelerator' build.

![image](https://user-images.githubusercontent.com/104883923/210196855-d6ae0723-d245-4b5c-8dd8-d5bd9fe4ac3f.png)

- Go to 'Deployment Profile' and open your profile record.

![image](https://user-images.githubusercontent.com/104883923/210196713-aa82ce54-59e3-4531-8d9a-6ed54931debc.png)

- Navigate to 'Deployment Environment' records as highlighted above.
- In the 'Service Connection Name' field, provide the name of your Azure DevOps 'Service Connection Name'.
![image](https://user-images.githubusercontent.com/104883923/210196980-db06fca0-0351-406d-9118-b39d4ca1e701.png)

**Comment by ShinraTenseiii** [comment]
Thank you for your inputs @piyushpaliwal @RajeevPentyala .

Creating service connections with the Admin app helped me figure this out.
