### ISSUE TITLE
Video Hub - Error (admin_contenttype: Field 'admin_contenttype' is required)

### ISSUE THREAD

**Issue by davins-msft** [microsoft/coe-starter-kit#4457]
### Describe the issue

When a video is played in the Video Hub App, the error "admin_contenttype: Field 'admin_contenttype' is required" shows up after a few seconds.

![image](https://user-images.githubusercontent.com/91287781/207969124-c85e8188-804d-4a47-bc89-6dc56acaac66.png)

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.19

### What app or flow are you having the issue with?

Video Hub App

### Steps To Reproduce

Launch Video Hub App
Play the video
After a few seconds, the error shows up.

**Comment by Jenefer-Monroe** [comment]
This was fixed for the December release. Please see https://github.com/microsoft/coe-starter-kit/issues/4062
