### ISSUE TITLE
CoE Starter Kit - No Theming solution in December's version 

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#4459]
### What is your question?

I realized there is no theming solution in December's release. 
Are you planning on discontinuing this solution?

Thanks in advance!
Btw, **LOVED** the Christmas present aka. Set-up Wizard <3
I'm very excited for February's version. So glad you are also taking time to relax during the holidays.

### What solution are you experiencing the issue with?

Theming

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Solution in general

**Comment by manuelap-msft** [comment]
Hello, you can find the Theming solution in the November release still. No changes have been made and thus it wasn't included in the December release. 

Thank you so much for your kind words about the setup wizard and about our team! Happy holidays!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
