### ISSUE TITLE
[CoE Starter Kit - BUG] COE Ste up Wizard issues - unable to turn on Admin_sync Template (Call Updates)

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#4463]
### Describe the issue

Hello Everyone,
Today I have started the set up for the COE starter kit Wizard set up process.
 
![image](https://user-images.githubusercontent.com/111575586/208128146-2358e894-6d87-4c85-adfb-4cc79da40d94.png)

It seems to be good until it reaches the Run Setup flows. Here my initial configuration of the Wizard got stuck and am unable to go further.
 
![image](https://user-images.githubusercontent.com/111575586/208128173-7430fd22-c3a0-406e-89bd-2b4649092ba4.png)

![image](https://user-images.githubusercontent.com/111575586/208128195-4ce144be-c3b1-4b7a-b6d6-4a69906dbe45.png)

 
It gives me an error saying to Turn On my Admin_Sync Template V3 flows manually, to follow that I went to my Solution and walked through all the flows.
All my Sync flows are turned On and running good. Only one flow was in Off state. When I try to turn on the Admin_sync Template (Call Updates) flow I get the below error.
![image](https://user-images.githubusercontent.com/111575586/208128222-6e6f537a-cf47-4877-9cc4-a28c936e64f4.png)

 
I need your assistance on it.
Thanks

### Expected Behavior

The initial run should complete with no errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin - Sync Template V3 

### Steps To Reproduce

Hello Everyone,
Today I have started the set up for the COE starter kit Wizard set up process.
 
It seems to be good until it reaches the Run Setup flows. Here my initial configuration of the Wizard got stuck and am unable to go further.
 
 
It gives me an error saying to Turn On my Admin_Sync Template V3 flows manually, to follow that I went to my Solution and walked through all the flows.
All my Sync flows are turned On and running good. Only one flow was in Off state. When I try to turn on the Admin_sync Template (Call Updates) flow I get the below error.
 
I need your assistance on it.

**Comment by Jenefer-Monroe** [comment]
We changed the trigger type in a few flows, and I've seen that cache for a few people. 
If you go turn off and back on the following flows, you should be ok:

- Admin | Sync Template v3 CoE Solution Metadata
- Admin | Sync Template v3 Configure Emails
- Admin | Sync Template v3 (Connectors)

**Comment by Neel1KNK** [comment]
Hello Jenefer,
Thanks for your quick response.
I have tried as the above steps by initially turning on the 3 flows and later I turned ON them back.
But even after making these steps I still see the same issue. Kindly help on that.
Thanks

**Comment by Neel1KNK** [comment]
Yeah, the same error while turning on the flow and even same for setting up the Wizard as well.
![image](https://user-images.githubusercontent.com/111575586/208437084-7ad884e4-2edd-470f-8c62-815756a1f71c.png)

**Comment by Jenefer-Monroe** [comment]
Can you please check for unmanaged layers on **_Admin | Sync Template v3 CoE Solution Metadata_**
![image](https://user-images.githubusercontent.com/89584709/208447402-15fede71-cb87-4587-a2fc-a9e2343807ee.png)

**Comment by Neel1KNK** [comment]
I see this, dose it needs to be removed??
![image](https://user-images.githubusercontent.com/111575586/208449908-fa10afbc-91b9-46a7-9452-94a093170706.png)

**Comment by Jenefer-Monroe** [comment]
Yes please. Unmanaged layers need removed if you are going to receive updates from us. The setup wizard will walk you through this once you get it going :)

**Comment by Neel1KNK** [comment]
Jenefer 
I don't see the unmanaged layer in Admin command center app to remove the unmanaged layers
![image](https://user-images.githubusercontent.com/111575586/208463505-67eea532-0b04-454e-969c-2d75f18bca0a.png)

Kindly help on that

**Comment by Jenefer-Monroe** [comment]
oh you just remove from here. select the unmanaged layer and you will see a remove option
![image](https://user-images.githubusercontent.com/89584709/208471334-20149ce5-c9f9-4be6-9cdf-963b6ddd54d3.png)

**Comment by Neel1KNK** [comment]
Thanks for that, after doing that was able to turn on the flow, but unable to complete the initial setup of wizard.
Getting the below error:
![image](https://user-images.githubusercontent.com/111575586/208476108-63a8c861-529f-4074-a632-bf8c4b3b309c.png)

**Comment by Jenefer-Monroe** [comment]
great can you please post that separately? We try not keep too many issues in one. This issue can track the inability to turn on the **_Admin | Sync Template (Call Updates)_** flow

**Comment by Jenefer-Monroe** [comment]
will go ahead and close this out then since you have posted the new issue.
