### ISSUE TITLE
[ALM Accelerator - BUG]: export-solution-to-git failed on 'Post-job: Cache Powershell Modules'

### ISSUE THREAD

**Issue by vishalgurav** [microsoft/coe-starter-kit#4474]
### Describe the issue

I am trying to configure the ALM Accelerator in my organization environment. While using the "Commit Solution" the pipeline "export-solution-to-git" is failing on "Post-job: Cache Powershell Modules" with error ##[error]Could not find a part of the path 'D:\a\1\PipelineUtils\Pipelines\Templates'.

I tried clean configuration multiple time however still it is failing at same task.
![ALM Error](https://user-images.githubusercontent.com/3853420/208641601-31ffc787-a9a7-4ba2-991a-15ed000d036d.PNG)

### Expected Behavior

Pipeline should complete without error

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Accelerator Version: 1.0.20221206.2(Managed)

### Steps To Reproduce

1. Open ALM Accelerator for Power Platform
2. Click "Commit solution" on specific solution
3. Pipeline "export-solution-to-git" will execute
4. check the log

**Comment by jenschristianschroder** [comment]
Hi @vishalgurav,

Thanks for reporting this. Unfortunately things have been slow due to holiday season. We will investigate this and report back on this thread.

Thanks

**Comment by jenschristianschroder** [comment]
@mikefactorial, @vishalgurav 

Had a call with Vishal today. It seems there is a pipeline decoration tasks configured in the organization that forces the cleanup task on all pipelines.

Waiting to hear back from ADO admin regarding the cleanup task.

We disabled the caching of PowerShell modules by adding "enabled: false" to the tasks in the relevant templates. This is an interim solution.

We should add an option to disable the caching task by setting a variable in our variable group.

Will create a new issue on this.
