### ISSUE TITLE
[ALM Accelerator - BUG]: Canvas apps sharing

### ISSUE THREAD

**Issue by daniel-klesc-lego** [microsoft/coe-starter-kit#4475]
### Describe the issue

Hello there,
  I have an issue with sharing canvas apps via AAD group. If I want to use different AAD group in **test** and **prod** then only the last set AAD group is preserved in that specific environment. E.g. Firstly I set **group1** in **test** environment and then set **group2** in **prod** environment only the **group2** remain set in production environment.

### Expected Behavior

I would like to have a possibility to set for each environment different AAD groups

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20221101.1(Managed)

### Steps To Reproduce

1. Open Configure Deployment Settings
2. Switch to configuration for the Test Environment
3. Go to Canvas Apps section
4. Set AAD group 1 in sharing drop down for an app
5. Switch to configuration for the Prod Environment
6. Go to Canvas Apps section
7. Set AAD group 2 in sharing drop down for an app
8. Save and close

**Comment by mikefactorial** [comment]
@daniel-klesc-lego thanks for reporting this issue will look into what's going on here.
