### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Sync Template v3 (Call Updates) logic

### ISSUE THREAD

**Issue by ashlega** [microsoft/coe-starter-kit#4476]
### What is your question?

Turned out "Admin | Sync Template v3 (Call Updates)" recurring flow is used to call "Admin | Sync Template v3 Configure Emails" among other things, and I've been getting my customized emails reset every morning because of that. Is this expected?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Call Updates)

**Comment by Jenefer-Monroe** [comment]
Yes that flow runs those other flows daily. If you want to have customized subject or body you need to update the Default Subject and Default Body fields to No. Note that if you use the Admin | Command Center to update these, then that will populate for you when you edit. 
![image](https://user-images.githubusercontent.com/89584709/208676551-48f53442-dbe1-4648-8eed-651483833058.png)

**Comment by ashlega** [comment]
I see - thank you for the clarification. 

PS. May I suggest moving that automated update to the "server-side" logic somehow, just so it's applied consistently when making those changes through the model-driven app, too:) Or, possibly, hardcoding "default body/subject" in the flow that's sending the email rather than in the flow that's updating configuration records. I realize you probably don't see Admin View MDA as an admin app right now. Still trying to figure out why do I need to jump back and forth between two apps (but now things are getting a bit more complicated, it seems, since there is additional logic in the canvas app, which would be one reason not to use the MDA, I guess)

**Comment by ashlega** [comment]
Appreciate the clarification, thank you! (and looking forward towards seeing those custom pages in the MDA, too:) )
