### ISSUE TITLE
[CoE Starter Kit - QUESTION] What connectors does the CoE Starter Kit Setup Wizard [Preview] use, as I'm getting a DLP policy notification

### ISSUE THREAD

**Issue by davidfeldman-coop** [microsoft/coe-starter-kit#4479]
### Describe the issue

Trying to launch the COE setup wizard app but I receive a message "It looks like this app isn't compliant with the latest data loss prevention policies."

I have reviewed the DLP policies and believe they are configured correctly

### Expected Behavior

CoE Starter Kit Setup Wizard [Preview] loads without issue

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.0.20221205.2

### What app or flow are you having the issue with?

CoE Starter Kit Setup Wizard [Preview]

**Comment by manuelap-msft** [comment]
Hello,

the Setup Wizard uses the following connectors:
- Office 365 Users
- Office 365 Groups
- Power Automate Management
- Power Apps for Admins
- HTTP with Azure AD to connect to https://graph.microsoft.com
- Power Platform for Admins
- Dataverse 

Please check to make sure
- the HTTP with Azure AD connector is in your business-data category and does *not* have endpoint filtering configured
- none of the connectors have connector action controls configured
- there's only one policy applied to your CoE environment and there's no conflicting policies which can happen when multiple policies are applied to one environment

**Comment by davidfeldman-coop** [comment]
How do I check the endpoint filtering for HTTP with Azure AD Connector?
How do I check connection action controls?

**Comment by manuelap-msft** [comment]
Here's the DLP documentation that explains how to configure and check these controls: https://learn.microsoft.com/en-us/power-platform/admin/dlp-granular-controls

**Comment by davidfeldman-coop** [comment]
Delete the rule here?
![image](https://user-images.githubusercontent.com/91218031/210392719-9c8f2b98-e8ab-4d8e-b472-dee5cd5459cb.png)

**Comment by manuelap-msft** [comment]
Yes, this rule would be causing the issue.

**Comment by davidfeldman-coop** [comment]
I removed the rule, and the app is now working.

**Comment by manuelap-msft** [comment]
Thanks for confirming! I'll close this issue now but please let us know if you have any further issues using the CoE kit!
