### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Solution) fails due to Dataverse legacy connector failing

### ISSUE THREAD

**Issue by MrHueb** [microsoft/coe-starter-kit#4481]
### Describe the issue

The Solution table is empty as the Admin | Sync Template v3 (Solution) Flow fails due to an error in the dataverse legacy connector.
When creating a new flow with the same dataverse legacy action, the following error message is shown.

Could not retrieve values. The dynamic invocation request failed with error: { "status": 401, "message": "Authorization has been denied for this request.", "error": { "message": "Authorization has been denied for this request." }, "source": "globaldisco.crm.dynamics.com", "errors": [], "debugInfo": "clientRequestId: 5ebe19df-cc89-4e0e-8ef5-aaff8cf6fe32" }.

![Screenshot 2022-12-21 091628](https://user-images.githubusercontent.com/56923538/208854333-b18104b9-6af7-4c63-be8a-6137968b4632.png)

### Expected Behavior

Legacy connector should work and get the solution data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solution)

### Steps To Reproduce

Run the flow.
Additionally, when using the same action of the dataverse legacy connector in a new flow.

### Anything else?

It is similar to issue: https://github.com/microsoft/coe-starter-kit/issues/1171
Service Account is Power Platform Admin and has System Administrator SR in all environments.
We are not sure if it's a Power Platform error or something to do with the CoE Starter Kit.
Thank you!

**Comment by MrHueb** [comment]
We were able to resolve the issue. There were some issues with the Dataverse legacy connection without being display the admin.
Resolution steps: Go to Power automate - Data - Connections and re-login by switch accounts. See screenshot attached.
![image](https://user-images.githubusercontent.com/56923538/208862340-508afb94-420a-457e-8dc7-bc7fed0c98b6.png)

**Comment by Jenefer-Monroe** [comment]
Thank you so much for letting me know the resolution! I've had several people hitting things that sound like they could be this. You filling me in on how you fixed may help us help a lot of others! THANK YOU!

**Comment by MrHueb** [comment]
Hi @Jenefer-Monroe , we faced the same issue again and used the same resolution steps as before. Have you heard about a root cause for this problem? Appreciate your help!

**Comment by Jenefer-Monroe** [comment]
I have not heard about any resolution. The product team is not investing in this connector any more but we cannot switch away from it until the new Dataverse connector supports dynamic selection of other environments. 
Thank you again for helping us to help others!

**Comment by MrHueb** [comment]
Cx ran into the same issue again. I just wanted to report that the issue is still out there and can be resolved with the steps described earlier.

**Comment by manuelap-msft** [comment]
Closing out as no further action required from the CoE kit team. This is a product limitation. We've not recently heard this issue come up either.
