### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade issue from version 3.34 to 4.2

### ISSUE THREAD

**Issue by INYAMOMCG** [microsoft/coe-starter-kit#4482]
### Describe the issue

Issue while doing CoE starter kit upgrade from version 3.34 to 4.2, we did start to upgrade core component first but encountered with below error.
Error code : 80050123
Import of app module(s) failed: 'Power Platform Admin View' app cannot be associated to more than one component library. Already exist component library count Microsoft.Xrm.Sdk.DataCollection`1[Microsoft.Xrm.Sdk.Entity].  In Solution Import, please remove library either from Source or Target and try again.

### Expected Behavior

It should allow us to do upgrade to latest version of CoE.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.34

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

Start upgrade process :
1. Import solution
2. choose CoE 4.2 core solution
3. select upgrade and start import
4. after 9 min it will throw an error

**Comment by manuelap-msft** [comment]
We've had one other user report this issue and they shared how they fixed it here https://github.com/microsoft/coe-starter-kit/issues/4375#issuecomment-1345554161

Please review the suggestions and see if that works for you as well!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
