### ISSUE TITLE
[CoE Starter Kit - QUESTION] No Flows are appearing for environment variable - Maker Assessment Admin Email

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#4486]
### Describe the issue

In the Admin Command Centre, the Maker Assessment Admin Email does not show any flows that will require resetting if the variable is updated.
![image](https://user-images.githubusercontent.com/17124284/208920945-08959d2d-e1f6-4f4a-a1a0-50913bef9643.png)

### Expected Behavior

Provide a list of flows that use the variable so as to be able to reset them when updating the value.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin - Command Centre

**Comment by manuelap-msft** [comment]
We only added the Reset feature for very high-impact flows, as the development and maintenance effort was very large and it was only a temporary solution until flows stop caching environment variable values - which has now rolled out, and flows now resets the env var values and no longer need to be turned off/on again to get the latest value:
https://learn.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-automate/push-environment-variable-updates-into-flows-asynchronously

We are going to remove the reset function from the app with the next release #4452

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
