### ISSUE TITLE
[Power Platform communication site template] What privileges are required to run the script?

### ISSUE THREAD

**Issue by JessicaBruner** [microsoft/coe-starter-kit#4487]
### Describe your bug, question or feature ask.

Have been trying to install this for a week now. Our SharePoint admin has followed all instructions provided online and is told that they need admin permissions. They are global SharePoint admin, are there additional privileges needed? If so, for what?

**Comment by manuelap-msft** [comment]
One part of the script sets the Power Platform governance message for which Power Platform admin privileges are required
https://learn.microsoft.com/en-us/power-platform/admin/powerapps-powershell#governance-error-message-content-commands

SharePoint admin privilege should not be required, but you do not permission to create a SharePoint site collection.

**Comment by JessicaBruner** [comment]
Ok so someone needs 1. The ability to create a sharepoint site collection (only our sharepoint admin in our org) AND 2. Power Platform Admin permissions for the governance message? I was temporarily assigned both SharePoint admin permissions (to install site) and Power Platform Admin permissions and the script works, I am being told through o365 auth that admin privileges are needed still.

**Comment by manuelap-msft** [comment]
Once the script has done, admin privileges will no longer be required. They're only required to get everything imported and set up, after that you only need permission to the SharePoint site itself to make changes.

**Comment by manuelap-msft** [comment]
Closing out as no further action required.

**Comment by JessicaBruner** [comment]
Yes, we replaced the vars in the script with whoever is installing as 'site owner' 
![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/121184164/210581342-26dbd3d8-430f-48e1-9fb3-66a858aaea9a.png)

**Comment by manuelap-msft** [comment]
Hm, it looks like the template uses components that are not allowed in your organization. We do ship it with embedded webparts for Yammer for example, which could cause this issue.

**Comment by JessicaBruner** [comment]
That would be the issue. Yammer is disabled in our org.

**Comment by JessicaBruner** [comment]
Is there a way to request a version of this without Yammer?
