### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to successfully create ALM Project

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#4490]
### Describe the issue

Unable to create ALM project as outlined in page 33 in ALM Accelerator for Power Platform Lab. Custom connector has been successfully setup and configured yielding message code 200 as outlined in page 31. 

![image](https://user-images.githubusercontent.com/95443860/208996119-4f9ab060-4888-4989-a6b7-10f2e3298a4f.png)
![image](https://user-images.githubusercontent.com/95443860/208996195-02899302-9dcb-4935-888e-39789b25e0f3.png)

### Expected Behavior

Project should be created with no error messages. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20 December Release

### Steps To Reproduce

1. Open Model Driven App
2. Create Project
3. Error Happens but project still gets created in list.

**Comment by mikefactorial** [comment]
@nasilvae we have seen issues with the custom connector when the solution is upgraded as opposed to updated. Not sure if that applies in your situation or if this is a new install.

**Comment by mikefactorial** [comment]
Closing this issue as there hasn't been any activity. Feel free to open a new issue if this persists.
