### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to setup Pipeline Template

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#4491]
### Describe the issue

Initiated Project Wizard to configure the pipelines. I get an error message when stepping to the next step after pipeline templates. 
![image](https://user-images.githubusercontent.com/95443860/208998743-7fbb9c50-3d86-4987-ac56-055fbf035860.png)

### Expected Behavior

I should be able to next through the wizard normally.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20 December Release

### Steps To Reproduce

1. Open Model Driven App
2. Select Project Wizard
3. Follow prompt steps regarding pipelines
4. Error Message 

![image](https://user-images.githubusercontent.com/95443860/208998897-51334aba-c6f3-4f31-a747-a8ad0a4970ba.png)

**Comment by jenschristianschroder** [comment]
The reason you get the message is that your Azure DevOps organization does not allow pipelines in one project to access a repository in another project.

The setting to deny cross project access for pipelines must be turned off in the Organizations Pipeline Settings and then in the Projects pipeline settings.

See below image
![image](https://user-images.githubusercontent.com/24893229/211285193-118fc8e7-5245-4383-8671-adde1fb09997.png)

**Comment by mikefactorial** [comment]
Closing this issue as there hasn't been any activity. Feel free to open a new issue if this persists.
