### ISSUE TITLE
[CoE Starter Kit - Question] What environment variable is required by the CoE Setup Flow 

### ISSUE THREAD

**Issue by pgtallon** [microsoft/coe-starter-kit#4492]
### Describe the issue

Hi,
I've installed the CoE Starter Kit but I'm having difficulties turning on the "Sync Template v3 CoE Solution Metadata" setup flow.

The error reported is as follows:
_Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_TenantID'."}}".

### Expected Behavior

I expect the setup flow "Sync Template v3 CoE Solution Metadata" to turn on as part of the installation.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Sync Template v3 CoE Solution Metadata

### Steps To Reproduce

1. ABP CoE Environment
2. Edit CoE Core Component
3. Select the "Sync Template v3 CoE Solution Metadata" setup flow
4. Attempt to turn on the setup flow but get an error
5. The error produced is as follows:

- Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_TenantID'."}}".

**Comment by manuelap-msft** [comment]
Hello,

this flow requires an environment variable - admin_TenantID - to be set before it can be turned on. It looks like you have not set this environment variable. Here's two ways to update it: https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables

**Comment by pgtallon** [comment]
Cheers Manuela.
