### ISSUE TITLE
[CoE Starter Kit - QUESTION] Access this App visual not refreshing

### ISSUE THREAD

**Issue by D3L05** [microsoft/coe-starter-kit#4493]
### What is your question?

I'm trying to make the Access this App work in the CoE dashboard, but it seems to work only the first time, then when you change the filter to select another app, all the visuals in the page are updated except the Access this App visual, probably doing something wrong with filters

![image](https://user-images.githubusercontent.com/62146775/209132381-ed2b5d8e-67cc-464e-b7bd-e65c731e6dc3.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin - Access this App

**Comment by manuelap-msft** [comment]
Hello,

this embedded app only works through the Drillthrough > App Detail option, as the drill through provides parameters (environment id, app id) to the app. It won't work if you just change the filter on the App Detail page as that doesn't trigger the parameters to be passed on to the app.

Hope that helps,
Manuela

**Comment by D3L05** [comment]
Thanks Manuela, indeed was a noob question :)

**Comment by manuelap-msft** [comment]
Oh not at all, understanding what happens how and when and what triggers what is half the battle :) 

I'll close this out now but please do let us know if you have further questions! Thank you for using the CoE kit!
