### ISSUE TITLE
[CoE Starter Kit - BUG] Update COE - Missing Dependencies

### ISSUE THREAD

**Issue by MSPFE2019** [microsoft/coe-starter-kit#4495]
### Describe the issue

Try to update COE from 3.56 to 4.2
Missing dependencies
Center of Excellence - Core Components
You'll need to import the following items to this environment in order to import Center of Excellence - Core Components

cat_PowerCAT.CommandBar
cat_PowerCAT.CommandBar
Custom control
Manage Permissions - Flows
Canvas app
cat_PowerCAT.CommandBar
cat_PowerCAT.CommandBar
Custom control
Manage Permissions - Apps
Canvas app
cat_PowerCAT.CommandBar
cat_PowerCAT.CommandBar
Custom control
Other Core Setup wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Clean-up for orphaned objects setup wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Compliance Setup wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Environment Request Setup wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Inactivity Process Setup wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Initial Setup page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Maker Assessment setup wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Manage Permissions - Flows
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Manage Permissions - Apps
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
More features
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Other Core Setup wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Pulse feedback setup wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Teams environment governance setup wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Template catalog wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Training in a day setup wizard page
Canvas app
cat_PowerCAT.Elevation
cat_PowerCAT.Elevation
Custom control
Video hub setup wizard page
Canvas app
cat_PowerCAT.FluentDetailsList
cat_PowerCAT.FluentDetailsList
Custom control
Initial Setup page
Canvas app
cat_PowerCAT.FluentDetailsList
cat_PowerCAT.FluentDetailsList
Custom control
Manage Permissions - Flows
Canvas app
cat_PowerCAT.FluentDetailsList
cat_PowerCAT.FluentDetailsList
Custom control
Manage Permissions - Apps
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Clean-up for orphaned objects setup wizard page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Compliance Setup wizard page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Environment Request Setup wizard page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Inactivity Process Setup wizard page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Initial Setup page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Maker Assessment setup wizard page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Manage Permissions - Flows
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Manage Permissions - Apps
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
More features
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Other Core Setup wizard page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Pulse feedback setup wizard page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Teams environment governance setup wizard page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Template catalog wizard page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Training in a day setup wizard page
Canvas app
cat_PowerCAT.Icon
cat_PowerCAT.Icon
Custom control
Video hub setup wizard page
Canvas app
cat_PowerCAT.PeoplePicker
cat_PowerCAT.PeoplePicker
Custom control
Manage Permissions - Flows
Canvas app
cat_PowerCAT.PeoplePicker
cat_PowerCAT.PeoplePicker
Custom control
Manage Permissions - Apps
Canvas app
cat_PowerCAT.ProgressIndicator
cat_PowerCAT.ProgressIndicator
Custom control
Initial Setup page
Canvas app
cat_PowerCAT.Shimmer
cat_PowerCAT.Shimmer
Custom control
Initial Setup page
Canvas app
cat_PowerCAT.Shimmer
cat_PowerCAT.Shimmer
Custom control
Manage Permissions - Flows
Canvas app
cat_PowerCAT.Shimmer
cat_PowerCAT.Shimmer
Custom control
Manage Permissions - Apps
Canvas app
cat_PowerCAT.Spinner
cat_PowerCAT.Spinner
Custom control
Initial Setup page
Canvas app
cat_PowerCAT.Spinner
cat_PowerCAT.Spinner
Custom control
Manage Permissions - Flows
Canvas app
cat_PowerCAT.Spinner
cat_PowerCAT.Spinner
Custom control
Manage Permissions - Apps
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Clean-up for orphaned objects setup wizard page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Compliance Setup wizard page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Environment Request Setup wizard page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Inactivity Process Setup wizard page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Initial Setup page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Maker Assessment setup wizard page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Other Core Setup wizard page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Pulse feedback setup wizard page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Teams environment governance setup wizard page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Template catalog wizard page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Training in a day setup wizard page
Canvas app
cat_PowerCAT.SubwayNav
cat_PowerCAT.SubwayNav
Custom control
Video hub setup wizard page
Canvas app

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Solution import

**Comment by Jenefer-Monroe** [comment]
Hello, there is now a dependency on the creator kit to install or upgrade the CoE starter kit. Please see [Creator Kit Setup](https://learn.microsoft.com/power-platform/guidance/creator-kit/setup)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
