### ISSUE TITLE
[CoE Starter Kit - BUG] How to collect device info from audit logs?

### ISSUE THREAD

**Issue by Pragtaij** [microsoft/coe-starter-kit#4497]
### Describe the issue

In the COE Power Platform Admin View, In the usage dat areport we are not able to get the name of the device being used.
So is there any way we can get device name in the report.

### Expected Behavior

The device name should be visible

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin - Sync Template | V3

**Comment by Jenefer-Monroe** [comment]
Hello, can you please share a screenshot so that I know what report you are discussing? Is it this one? 
(Note that you need to be logged in to GitHub to share images, responding in email will not share an image)
![image](https://user-images.githubusercontent.com/89584709/209343550-c5e2bad7-536d-472b-b845-4ae1d2e4062a.png)

**Comment by Pragtaij** [comment]
Hi, I am referring to Usage report from power platform admin view.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/120566772/209525165-cfd5673b-6c01-4ddc-a3a0-755e59efcaa5.png">

**Comment by Pragtaij** [comment]
Hi Jenefer,

I am referring to the app usage report in Power Platform admin view.
I have attached screenshot of the same in issue, Please check and let us know if there is any update on this.

Thanks,
Pragati

**Comment by Pragtaij** [comment]
Hi Jenefer,

Do we have any update on the below issue.
Let me know If you need more information we can have a working session for the same.

Thanks,
Pragati

From: Jadhav, Pragati
Sent: 26 December 2022 18:50
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>; Srivastava, Ankur ***@***.***>; Prasad, Rajani ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #4497)

Hi Jenefer,

I am referring to the app usage report in Power Platform admin view.
I have attached screenshot of the same in issue, Please check and let us know if there is any update on this.

Thanks,
Pragati

**Comment by Jenefer-Monroe** [comment]
Please note from [our disclamer](https://learn.microsoft.com/power-platform/guidance/coe/overview#disclaimer) that the CoE Starter Kit is not a supported product. While we do strive to assist our customers in a timely manner, we are a very small team and do not have an SLA for response.

**Comment by Jenefer-Monroe** [comment]
We collect this data from the [office audit logs](https://security.microsoft.com/auditlogsearch), I do see IP address in there but no other device information. Is this what you mean? The IP Address?

**Comment by Pragtaij** [comment]
Hi Jenefer, Thank you for your response,
I am referring to device name whether it is "Dektop" or "MobilePhone" in the app usage report.

**Comment by Jenefer-Monroe** [comment]
Whether the launch was from a desktop or mobile is not exposed to us in that information so I'm afraid here is no way for us to gather that.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
