### ISSUE TITLE
[CoE Starter Kit - QUESTION] Still use CoE Settings table? 

### ISSUE THREAD

**Issue by MarcoDelp** [microsoft/coe-starter-kit#4498]
### What is your question?

I have a question regarding the Customize COE settings object ( It's a table if i remember well) within core components solution 
This sub component ( used for COE layout / Branding customization as far i understand ) is still in use ? 

![image](https://user-images.githubusercontent.com/108942915/209415127-d3ce7fe2-e8ff-467d-b9c3-406995944056.png)

I've tried to enter some custom data here but i cannot see any outputs / changes on the interface. 

Can you clarify this ?

Thank you

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

current version

**Comment by Jenefer-Monroe** [comment]
No we no longer use this table. We left it in the solution in case others had used it for things they rely upon. 
We shifted to using Environment Variables for the things we needed when those became available to us in the product.
I hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
