### ISSUE TITLE
[ALM Accelerator - BUG]: Maker unable to access the canvas app

### ISSUE THREAD

**Issue by piyushpaliwal** [microsoft/coe-starter-kit#4499]
### Describe the issue

As per the maker setup documentation (https://learn.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/maker-setup), I have added a new maker. Everything went fine with the `coe-cli` tool, no errors reported.

1. The host environment where ALM accelerator is installed does not show up for the maker, he only sees his own developer environment thereby giving no way for him to get to the canvas app.
![Only Development environment visible](https://user-images.githubusercontent.com/635693/209791499-81578fa3-0cb5-4b44-94cc-37687ae55939.png)
  - I was able to work around this problem by pasting the `Environment Id` manually, basically appending it to the URL, like `https://make.powerapps.com/environments/<id of host env>/home` and the maker was able to **temporarily** see the environment and go to the canvas app

2. On the first execution of the canvas app, maker was asked to fix connections especially `CustomAzureDevOps`, and this where I am stuck at. Upon trying to `Sign In`, I am getting presented with the following error

`The user '4bed1603-8f7d-ed11-81ac-00224805c45f' does not have sufficient access rights to perform this operation on entity with id 37284777-a05f-4680-b0f9-1eb13e90fc71 in instance with URL '<url of the host environment>' . Required access right 'ReadAccess' is missing.
Session ID: b9835a17-9c97-4ec1-b1c4-bf37cfbed982`

![Error](https://user-images.githubusercontent.com/635693/209792317-e3ba8813-55ee-492b-b3fd-ba604ce31364.png)

Now, I don't see a mention of any additional permissions to be explicitly granted to makers. Any thoughts?

### Expected Behavior

I should be able to open up the `ALM Accelerator for Power Platform` application and start creating a solution.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20221206.2

**Comment by jenschristianschroder** [comment]
Hi @piyushpaliwal,

Using the cli to give makers access to the ALM Acc. Canvas App only shares the app and does not give the makers Environment Maker in the environment where the solution is installed. So, it is expected that the maker cannot see the environment.

For the maker to access the app you should share the app url with the maker.

In regards to the issue with the custom connector please try the following:

1. Go the environment where the ALM Acc. Solution is installed.
2. Open the COE ALM Acc solution
3. Select the CustomAzureDevOps connector
4. Click Share
5. Share the Custom Connector with the Maker

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here.
