### ISSUE TITLE
Sync-pipeline-repo does not support custom source branch

### ISSUE THREAD

**Issue by jenschristianschroder** [microsoft/coe-starter-kit#450]
The sync-pipeline-repo does not support setting a custom source branch when running the pipeline.

This is useful when wanting to synchronize against a branch other than main in the template-repo

Suggest to add a SourceBranch parameter to the pipeline so that user can configure the source branch they want to synchronize against.

**Comment by mikefactorial** [comment]
@jenschristianschroder I transferred this over from the template repo so we can keep track of everything in the release in one place. Good to close?
