### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Apps) fails for getting apps on default environment

### ISSUE THREAD

**Issue by umeshmurumkar** [microsoft/coe-starter-kit#4500]
### Describe the issue

We have recently upgraded to latest CoE Version as we had been told that old version may not work propery due to multiple changes and new features included by Microsoft. However, we are unable to get Apps as admin for our default environment where we do have most of PowerApps created

Scope name: Load Array
Connector: Get App as Admin

Error : 
ResponseSwaggerSchemaValidationFailure. The API 'powerappsforadmins' returned an invalid response for workflow operation 'Get_Apps_as_Admin' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-AdminApps' requires the property 'body/value/7/properties/connectionReferences/0/iconUri' to be of type 'String' but is of type 'Null'.'

This happens only for default environment.

### Expected Behavior

Default apps should be fetched with this action and due to this behavior of the flow, Dataverse table PowerApps App showing wrong data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

### Steps To Reproduce

1. In Default environment of our organization 
2. the flow fails when configuration takes default environment ID and flow get called from parent Sync flow.
3. As default environment contains most of the data it is vital details we are missing.
<img width="929" alt="CoE Admin Sync Apps flow error" src="https://user-images.githubusercontent.com/26483756/209822798-6b9411e7-a56d-45fc-a98d-730517044eb2.png">

### Anything else?

We are using the coe starter kit data extensively and we believe that the Admin connector itself fails for huge data.

**Comment by Jenefer-Monroe** [comment]
It sounds like there is something wrong with the connection used. Please log in as the identity you expect to run the flows and do the following

Look at the connection references for the flow. Do they appear to be pointing to the correct identity that runs the flow?Do they all show green checks? 
![image](https://user-images.githubusercontent.com/89584709/209950668-866e0096-c22e-4986-a718-5842a4eff026.png)

Go to the connection references in the Default Solution, are they all pointed to the correct person? 
![image](https://user-images.githubusercontent.com/89584709/209950945-c12e73c0-c857-491a-8a9d-6c5b4778248b.png)

**Comment by umeshmurumkar** [comment]
These connection references  are green and working as expected. In fact , the power automate connector works when any other environment id is passed to it. The issue appears for default environment  where we do have more than 10k canvas apps. 
We are not sure if the CoE Kit works for environment where apps are more than 250 or wherever get apps as admin connector is used. Can you help to understand what happens when this admin connector gets more than page size. Because if it skips the apps after 250 count, we will never get correct data for large environments like default.

**Comment by Jenefer-Monroe** [comment]
We use pagination and have max pagination on these calls so when you get >250 it calls another page. 
We do have some people who have surpassed the limit even with the max pagination but that is for something like 100,000 apps in default.

**Comment by Jenefer-Monroe** [comment]
I searched your error message and see this bug https://github.com/microsoft/coe-starter-kit/issues/3274
It's likely the same error as them, and the product was returning bad data for some case. 

Please follow the steps here to get an isolated repro https://github.com/microsoft/coe-starter-kit/issues/3274#issuecomment-1196866287. And then if it still repros please contact support.

**Comment by umeshmurumkar** [comment]
Thank you for helping out. I tried these settings previously and looks like same error in new flow too. 
![image](https://user-images.githubusercontent.com/26483756/209972977-664effa7-33ad-48d7-8c07-2d05fb1ca75a.png)

Will check with Microsoft and post here the response.

**Comment by Jenefer-Monroe** [comment]
Thank you for letting me know! And please do let me know what you find.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action from starter kit team.
