### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Delete Bad Data) - Delete Connection Reference Identity

### ISSUE THREAD

**Issue by bwieland86** [microsoft/coe-starter-kit#4501]
### Describe the issue

The CLEANUP - Admin | Sync Template v3 (Delete Bad Data) fails at the "Delete Connection Reference Identity with no Creator or Connector" action with error message "admin_ConnectionReferenceIdentity With Id = [redacted] Does Not Exist"

This triggers the scoped Error Handling, but skips any other actions in the "No Other Parent Object" scoped actions.

![CoE_CLEANUP_Delete_Bad_Data_error](https://user-images.githubusercontent.com/13457692/209829628-81c4db87-f6b6-4575-9c64-fc66329895d1.png)

### Expected Behavior

Include error handling to ignore Connection Reference Identities which do not exist

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Delete Bad Data)

### Steps To Reproduce

Allow the workflow to run daily as normal:

![CoE_CLEANUP_Delete_Bad_Data_flow_run_errors](https://user-images.githubusercontent.com/13457692/209830244-542cad7f-30da-4967-aecd-2b0661466764.png)

**Comment by Jenefer-Monroe** [comment]
We try not to add error handling places like that as it will hide real bugs later. It seems like you had an enormous number to clean, and the that flow passed later, so perhaps the state for the object just changed while it was running. 
Now that you've had a success, please let me know if it fails again in this same spot.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
