### ISSUE TITLE
[CoE Starter Kit - QUESTION] How we can schedule Full Inventory Run 

### ISSUE THREAD

**Issue by umeshmurumkar** [microsoft/coe-starter-kit#4505]
### What is your question?

We got wrong data due to delay in CoE Upgrade and now we are at 4.2 version. We want to check how can we run full inventory once and then stop this activity and run as usual once delete flags get set properly.
Also we would like to know if it resets CoE tables during full inventory run.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

**Comment by Jenefer-Monroe** [comment]
Here is our write up on how to [run a full inventory](https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory)

Hope that helps

**Comment by umeshmurumkar** [comment]
Thanks for the link. I have checked and found there is no details if data Verse tables will be reset due to full inventory run or not. We are good to go once we get this piece of vital info. But I did not get that from the article.  Can you help us with this?

**Comment by Jenefer-Monroe** [comment]
I dont know what you mean by resetting the tables. Full inventory will update all the resources in your tenant (ex flows, apps) even if they have not been updated recently. 
Perhaps you can clarify more what problem you are trying to solve?

**Comment by umeshmurumkar** [comment]
We have CoE tables like PowerApps apps, Environment, Flow with lots of data within it. Problem is we got lots of wrong data like, app deleted flag set to true despite of app being there present actually, recently created apps in default environment are not appearing in tables etc. Our concern is we need this missing data, but we do not want to lose existing data in CoE Tables as they are source to our other custom governance apps and PowerBi Dashboard. Just wanted to check if the Full inventory mode clear old data present in tables (e.g. flows, apps, environment) and create all the new records? Or it will check existing data, update if there are changes in records and create new records if not present in the tables?

**Comment by Jenefer-Monroe** [comment]
It does not delete existing records. It will update all of them and add new ones. Hope that helps!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action from starter kit team.
