### ISSUE TITLE
[CoE Starter Kit - QUESTION] Governance CoE Dashboard Documentation

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#4506]
### What is your question?

Is there any documentation specifically regarding the Power Platform Governance CoE Dashboard please?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

December 2022

**Comment by Jenefer-Monroe** [comment]
Here is that documentation, please let us know if you have specific questions from it
https://learn.microsoft.com/power-platform/guidance/coe/power-bi-compliance

**Comment by medicineshow** [comment]
@Jenefer-Monroe     that's great thank you (I should have kept reading the document longer, but there is so much) :)
I don't seem to be able to drill through the cards though.
![image](https://user-images.githubusercontent.com/17124284/209973599-751dd411-d81f-4ae0-b748-a4d33f34675b.png)

**Comment by Jenefer-Monroe** [comment]
Is that your right click? Are you in the browser or the client? 
Here is what I see for the context menu
![image](https://user-images.githubusercontent.com/89584709/210004225-a10217a4-97ae-4a41-9009-424217165eda.png)

**Comment by medicineshow** [comment]
@Jenefer-Monroe It was in the browser and it was the "meatball" menu I used. Hadn't thought to right click :)

**Comment by Jenefer-Monroe** [comment]
It's not very intuitive, imho :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
