### ISSUE TITLE
[ALM Accelerator - QUESTION] QUESTION

### ISSUE THREAD

**Issue by tf1970** [microsoft/coe-starter-kit#4507]
### What is your question?

I am getting below error on this step https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#clone-the-yaml-pipelines-from-github-to-your-azure-devops-instance

![image](https://user-images.githubusercontent.com/48414024/209963426-414a0957-23d3-4b3b-8093-cdfb448f8734.png)

Is https://github.com/microsoft/coe-alm-accelerator-templates/tree/CenterofExcellenceALMAccelerator-August2022 the right url to use?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20221206.2

**Comment by jenschristianschroder** [comment]
Azure DevOps does not support importing from a tag unfortunately.

If you want to import the git repo manually you should use this url: [https://github.com/microsoft/coe-alm-accelerator-templates](https://github.com/microsoft/coe-alm-accelerator-templates/tree/CenterofExcellenceALMAccelerator-August2022)

Recommendation is to use the Admin App to set up Azure DevOps. Here is the guide: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-preview

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do on this issue.
