### ISSUE TITLE
[CoE Starter Kit - BUG] Missing dependencies trying to install Core. (need to install creator kit)

### ISSUE THREAD

**Issue by axlrs1** [microsoft/coe-starter-kit#4508]
### Describe the issue

Current version is 3.53 trying to update it to 4.2

Getting "Import failed due to missing dependencies for CoE Core Components" error. 

### Expected Behavior

Upgrade

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CoE Update Core Components

**Comment by Jenefer-Monroe** [comment]
I presume this is about the new requirement for the Creator Kit. Please see https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/setup

**Comment by axlrs1** [comment]
Thank you @Jenefer-Monroe, Ill try that now.

**Comment by Jenefer-Monroe** [comment]
Please do let me know!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action from starter kit team.
