### ISSUE TITLE
[Power Platform communication site template] Menu options not visible

### ISSUE THREAD

**Issue by alpesh-exigotech** [microsoft/coe-starter-kit#4512]
### Describe your bug, question or feature ask.

After deploying Power Platform site - not able to see menu options on home site.

![image](https://user-images.githubusercontent.com/88418557/210289321-4ed2ba97-1c46-4cf7-8efd-796501467433.png)

**Comment by Laskewitz** [comment]
@alpesh-exigotech I've seen this one before - and although I don't know how to resolve this in the template (on most occasions it works as expected). In all the cases I've seen this, editing the navigation, and saving it usually does the trick. Can you see if that helps?

**Comment by Laskewitz** [comment]
@alpesh-exigotech Any update?

**Comment by Laskewitz** [comment]
@alpesh-exigotech - It's been more than a week ago since the latest response. I hope it's fixed now and if not, please reopen the issue.
