### ISSUE TITLE
[CoE Starter Kit - QUESTION] What flow is using the Power Platform User Group ID Env Var?

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#4514]
### What is your question?

What flow is using the Power Platform User Group ID Env Var? I am trying to understand the requirement for this user group. In our environment, all users have a O365 Power Apps licence and so could be considered Power Platform Users.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

December 2022

**Comment by Jenefer-Monroe** [comment]
We are not using it yet. The intention is to do auto-sharing for you from the Setup Wizard, but the work was not ready for release in Dec. 
In the next release you will see it in SetupWizard>ShareApps flow
![image](https://user-images.githubusercontent.com/89584709/210396436-0454456f-e409-4dfe-bc14-1623125875da.png)

Which will be called from the Setup Wizard App
![image](https://user-images.githubusercontent.com/89584709/210396746-e89e8022-e75d-490c-9a57-fda65cf078ca.png)

Hope that is clear! Happy new year!

**Comment by medicineshow** [comment]
Thanks. Happy New Year

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Ballzer0** [comment]
is this supposed to be a group of all potential users i wanna share apps with?

**Comment by Jenefer-Monroe** [comment]
Hello please post as a new question. Monitoring closed issues is difficult for us.
