### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Inactivity notifications v2 (Start Approval for Apps / Flows)

### ISSUE THREAD

**Issue by bwieland86** [microsoft/coe-starter-kit#4516]
### Describe the issue

 Both the Admin | Inactivity notifications v2 (Start Approval for Apps) and Admin | Inactivity notifications v2 (Start Approval for Flows) are missing dynamic content after the Approval action:

![Inactivity notifications v2 Start Approval for Flows - missing dynamic content](https://user-images.githubusercontent.com/13457692/210420788-6c34bcb7-f43b-40d3-96d1-5dacafc652f7.PNG)

![Inactivity notifications v2 Start Approval for Apps - missing dynamic content](https://user-images.githubusercontent.com/13457692/210420798-d4194bef-ae95-4ff5-a8c2-45d6e99aee10.PNG)

### Expected Behavior

Conditional action should contain values

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps / Flows)

### Steps To Reproduce

Open workflow for editing and observe missing values in 'If no value for 'admin flowarchiverequestignoredsince', add this one' and 'If no value for 'admin apparchiverequestignoredsince', add this one' actions

**Comment by Jenefer-Monroe** [comment]
Hello. These flows broke in this manner when we switched shipping tenants, somehow operands got dropped. That said, we thought we had fixed this for Dec release with a hot fix to 3.3 in all but one case (https://github.com/microsoft/coe-starter-kit/issues/4444) 
Please see if you have unmanaged layers on there flows as a result. If so, please make the change listed in https://github.com/microsoft/coe-starter-kit/issues/4444 and then you will be set for next release where this is fixed (though you will have an unmanaged layer to remove at that time)

**Comment by Jenefer-Monroe** [comment]
If not, the value that should go there are as shown here. Please make these changes and the ones in https://github.com/microsoft/coe-starter-kit/issues/4444 and both will be fixed for you next release. 

For **_Admin | Inactivity notifications v2 (Start Approval for Apps)_**
`items('Create_Archival_Request_for_Each')?['admin_apparchiverequestignoredsince']`
![image](https://user-images.githubusercontent.com/89584709/210429193-a6de00ac-1409-45a0-a1c5-c1cf18f69cc7.png)

For **_Admin | Inactivity notifications v2 (Start Approval for Flows)_**
`items('Create_Archival_Request_for_Each')?['admin_flowarchiverequestignoredsince']`
![image](https://user-images.githubusercontent.com/89584709/210429423-546e08c8-c505-42b1-b5aa-1704ca263feb.png)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action from starter kit team.
