### ISSUE TITLE
[CoE Starter Kit - BUG] No portal cleanup

### ISSUE THREAD

**Issue by StewartSJLDS** [microsoft/coe-starter-kit#4518]
### Describe the issue

Our CoE has duplicate entries for our Power Pages/Portals. We have noticed this primarily with Portals that have a custom domain assigned to them, so they will have an entry for their ####.powerappsportals.com address as well as their custom domain URLs. 

![image](https://user-images.githubusercontent.com/115110726/210455130-8374a9f3-ab18-4969-bf91-cb186ff9e832.png)

### Expected Behavior

Each PowePage should only have 1 entry in the CoE.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Portals)

**Comment by Jenefer-Monroe** [comment]
Unfortunately we cannot detect when portals are deleted / this type of property changed. So we do not have a clean up routine for them. The portal team is working on some admin features that we can use to make this better but until then we cant clean up. 

If you manually delete from inventory the bad ones, then they should not reappear. 
Please let me know if that is not the case.

**Comment by StewartSJLDS** [comment]
So could we delete all entries from the current table and have it repopulate so that it's somewhat accurate then deal with the one-offs as they come up?

Sam Stewart
Cloud Engineer | Power Platform / Dynamics 365
Information & Communication Services
The Church of Jesus Christ of Latter-day Saints
----------
***@***.******@***.***>
----------
Call me on ***@***.***> || Book Time With ***@***.***/bookings/>

From: Jenefer Monroe ***@***.***>
Sent: Tuesday, January 3, 2023 4:11 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Sam Stewart ***@***.***>; Author ***@***.***>
Subject: [Ext:] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #4518)

[External Email]

Unfortunately we cannot detect when portals are deleted / this type of property changed. So we do not have a clean up routine for them. The portal team is working on some admin features that we can use to make this better but until then we cant clean up.

If you manually delete from inventory the bad ones, then they should not reappear.
Please let me know if that is not the case.

-

**Comment by Jenefer-Monroe** [comment]
Yes that should do it. Sorry for the inconvenience

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action from starter kit team.
