### ISSUE TITLE
[CoE Starter Kit - BUG] power automate trigger concurrency runtime configuration cannot be removed once specified

### ISSUE THREAD

**Issue by RakeshPower** [microsoft/coe-starter-kit#4520]
### Describe the issue

Hi Team,

We have upgraded from 3.39 v to 4.2 today and two following flows failed to "Turn On"):
Admin | Sync Template v3 (Flows)
Admin | Sync Template v3

It seems like in the past, somehow someone played with concurrency settings and now it is failing to get activated.
Could you please advise what could be done to resolve this issue? Thanks in advance.

They are thworing attched error[
![IMG_8272](https://user-images.githubusercontent.com/115120204/210465220-fe26ee5c-ef0b-4cd4-bae6-6d11d97471a0.jpg)
](url)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows) & Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
Is there an unmanaged layer on the flow that contains the change to add the trigger concurrency?

**Comment by RakeshPower** [comment]
Nope, we have used classic UI for importing the solution and with option to
overwrite any customised unmanaged layer.

For a time being, we have enabled trigger concurrency and sets it’s value
to 100 for these two flows.

Do you foresee any limitations with this? As we unable to turn on flow
without it?
Please advise and also , we want flows to dump whole inventory once to
ensure nothing has missed out?

**Comment by Jenefer-Monroe** [comment]
Yes I'm afraid this is a product limitation that you cannot undo that. You may be able to contact support and find a workaround but I am not aware of one. 
How many environments do you have? If you have more than 100 environments, then I think they wont trigger.

**Comment by RakeshPower** [comment]
We have 47 standalone environments and 190 MS teams environments? Raised a
support ticket however disabling concurrency is impossible. Seems like need
to install whole CoE from scratch?

**Comment by Jenefer-Monroe** [comment]
Unfortunately I think that is what you will have to do. You should look in to the data you are using in the current setup (ex if you are using Inactivity notifications, or capacity planning, etc) and that way you can manually migrate the needed data to the new envt once it populates all the envts / apps / flows. 

Sorry for the inconvenience. I wish that setting was more dramatic or hidden so people didnt fall in to this.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action from starter kit team.
