### ISSUE TITLE
[CoE Starter Kit - FEATURE] Command Center Flow page needs UX improvement for notes/flags

### ISSUE THREAD

**Issue by Pavan12Verma** [microsoft/coe-starter-kit#4525]
### Describe the issue

Admin center showing red flag for some flow even after successful executions. For example, see Inventory (connector) flow screenshot 

![Admin center showing red flag](https://user-images.githubusercontent.com/101834540/210625810-dfbe7bdf-6ac3-46c6-adb0-dae475e20109.png)
![Inventory flow history](https://user-images.githubusercontent.com/101834540/210625811-1def27db-7a93-434c-ab48-5c0d701ff69a.png)

### Expected Behavior

No red flags in Admin center if the flow run is successful

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Multiple inventory flows

### Steps To Reproduce

1. open Power Apps
2. Go to CoE core components solution
3. Play "Admin -  command center" app

**Comment by manuelap-msft** [comment]
The red flag here just highlights a note for you to read, and doesn't take the latest run or status of the flow into consideration and it doesn't mean the flow hasn't been run successfully. 

We are working on updating the UX here and will make sure that's more clear.
