### ISSUE TITLE
[CoE Starter Kit - QUESTION] Upgrade prroblems

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#4531]
### What is your question?

Im trying to go in 3 month steps from Dec21 - now,   when updating Im getting this,

Solution "Center of Excellence - Governance Components" imported successfully with warnings: The original workflow definition has been deactivated and replaced.

There is a log , but I cant find any mentions to Warnings  so cant figure out what it failed for or whether I should be worried or if its all fine ?

CenterofExcellenceAuditComponents_2.13_managed.zip

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

March 22

**Comment by G1982C** [comment]
I have the exact same warning after importing the Centre of Excellence Core Components

**Comment by Jenefer-Monroe** [comment]
You can ignore that warning. I've seen it recently too and it does not impact the resulting solution.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action from starter kit team.
