### ISSUE TITLE
Admin | Sync Template v3 (Flows) - exceeded the maximum size '209715200' 

### ISSUE THREAD

**Issue by pagelib222** [microsoft/coe-starter-kit#4532]
### Describe the issue

Hi Center of Excellance team, we run the standard flow "Admin | Sync Template v3 (Flows)" and get this error now: The action 'List_Flows_as_Admin' has an aggregated page results size of more than '209985474' bytes. This exceeded the maximum size '209715200' bytes allowed.

Our failed environment (default) contains more than 20.000 flows. Do you know how we can proceed in case with this maximum size? Why we raised this limit? 

Maybe you can give us more hints. BR; Martin

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin - Sync Template v3 (Flows)

**Comment by manuelap-msft** [comment]
Hello,

the CoE kit is built on top of the product, and as such bound to platform limitations. In this case, we are using the out of the box [Power Automate Management connector ](https://learn.microsoft.com/en-us/connectors/flowmanagement/) to get flows. If you are hitting limitations with this connector, there's unfortunately nothing we can do to provide a workaround.

**Comment by Jenefer-Monroe** [comment]
You may benefit from exploring the self service analytics offered by the product as that does not use the connectors to get the objects. Its something we are trying to integrate with as well. 

https://docs.microsoft.com/power-platform/admin/self-service-analytics
https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by pagelib222** [comment]
Hi, many thanks for your feedback. Can you give us more insights, what limit raised or can we split this? Or how we can analyse it more. Sorry, but we have not really an idea how to fix this.

**Comment by Jenefer-Monroe** [comment]
The limit here is in how much data connectors can bring back. Unfortunately this connector does not support filtering such that we could pull back subsets of flows to work around this. 

You could use the Top Count parameter to avoid the error, but then you would not be getting the full inventory. I'm not sure what value would go their either, you would need to play with it. 
![image](https://user-images.githubusercontent.com/89584709/211362063-db942e93-0965-42ce-b510-397dba5a1721.png)

Another option would be to remove flows from the environment. You could do this by deleting them or moving them to other environments. 

Sorry you've hit this limit.

**Comment by StefanRPAva** [comment]
Instead of deleting your Flows you could also consider using logic apps or a Powershell command to export all Flows.
 Get-AdminFlow | Export-Csv -Path '.\FlowExport.csv'
 
 From there on you have several options to rebuilt the flow and run it over the .csv or push the data daily directly to Dataverse or call the logic app with http instead of a runbook.
Sadly it will cause extra cost to run logic apps.

Useful Power Platform Shell Commands -> https://learn.microsoft.com/en-us/power-platform/admin/powerapps-powershell#power-automate-commands

**Comment by Jenefer-Monroe** [comment]
closing out as unfortunately there is nothing else the starter kit can do here to assist.
