### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 (Flows) failing - The action 'List_Flows_as_Admin' has an aggregated page results size of more than '211504241' bytes. This exceeded the maximum size '209715200' bytes allowed.

### ISSUE THREAD

**Issue by bhavikj65** [microsoft/coe-starter-kit#4533]
### Describe the issue

"Admin | Sync Template v3 (Flows)" flow started to fail since 14th Nov 2022 with below error:

The action 'List_Flows_as_Admin' has an aggregated page results size of more than '211504241' bytes. This exceeded the maximum size '209715200' bytes allowed.

This is happening only in our default environment which has more than 45K cloud flows.

Same error is seen for "Admin | Sync Template v3 (Connection Identities)" flow as well.

### Expected Behavior

List flows as Admin should complete without any error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### Steps To Reproduce

N/A

**Comment by Jenefer-Monroe** [comment]
The CoE kit is built on top of the product, and as such bound to platform limitations. In this case, we are using the out of the box [Power Automate Management connector ](https://learn.microsoft.com/en-us/connectors/flowmanagement/) to get flows. If you are hitting limitations with this connector, there's unfortunately nothing we can do to provide a workaround with the current platform. 

You may benefit from exploring the self service analytics offered by the product as that does not use the connectors to get the objects. Its something we are trying to integrate with as well. 

https://docs.microsoft.com/power-platform/admin/self-service-analytics
https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by bhavikj65** [comment]
I know this is a product limitation, however we are also using Data Lake export and even Data Lake doesn't provide the inventory for such large environment. 

If the product can't support large environments, then Microsoft should document this well in advance and not reduce the limits on a fine day. 

Really bad from Microsoft.

**Comment by pagelib222** [comment]
Hi bhavikj65, any update from your side? We run in the same issue. Have actually approx. 23000 cloud flows. Investigation more actually but not a solution so far from our side. BR, pagelib

**Comment by bhavikj65** [comment]
We are still having this issue, we have configured Data Export to Azure Data Lake in our tenant, hopefully Microsoft fixes issues there.

**Comment by Jenefer-Monroe** [comment]
Hello. We have heard that the issues with your tenant's Data Export feature has now been addressed by the product team. Thank you for testing it for us and helping make it better for everyone. 

I'll go ahead and close this out since there isnt anything else we can do to make the sync flows work here for now.

**Comment by TomekPi** [comment]
Hi, we're also getting the same issue for environment with around 35k flows. I cannot see any documented limitation with "List Flows as Admin" action regarding flows count, is there any?
I can see there's another action "List Flows as Admin (V2)", maybe this one should be used in sync flow?

**Comment by pagelib222** [comment]
@Jenefer. To be honest. This limit is not acceptable in the enterprise area. When there is a hard limit than CoE should be not recommended to use for the daily business. 20k, 35k, 45k of flows are not a huge number in the next year.

Do you see an investigation part to support us here in more details. To get a deeper insight when the limit raised. What are drivers of the limit. Who we can save information to deal with the limit, etc.

**Comment by Jenefer-Monroe** [comment]
Unfortunately we are just using product features and this is a limitation of the connectors product itself, not even related to this specific Connector / Action. All connectors have this limit, most just don't hit it. 
There is nothing we can do to change this behavior in the kit for the sync flows methodology. In other words, using the Flow product to gather inventory just has this limitation.  

This, and the large API impact, is why we are investing in the self service analytics (BYODL) architecture. 
We have just gotten the last known blocking product bug for this fixed and so will be returning to investigate CoE integration with this feature. 

Here are some starter links.

https://docs.microsoft.com/power-platform/admin/self-service-analytics
https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by TomekPi** [comment]
@Jenefer-Monroe Currently, CoE is useless for big tenants with huge amount of flows/apps which hit the limit, isn't it?
Are there any open actions to create some workaround for this issue? 

From my tests it looks like action "List Flows as Admin (V2)" is dealing with bigger amount of flows, however, it doesn't provide needed properties (e.g. lastModifiedTime) so the logic would have to be changed also, but maybe it's the only way.
It looks like the action itself hits the limit, what if you could implement your own pagination (instead of built in) so the whole data is not stored in single action?

For my understating this is the core feature which is simply NOT working for large enterprises. If you're aware of this and you're ok with this, at least announce it clearly.

**Comment by Jenefer-Monroe** [comment]
You are correct about **_List Flows as Admin (V2)_**, we are working with the product team to get the requirements like last modified date that would allow us to use it, until them we would just be blowing out the API calls and also not be usable for large tenants. 

The plan for large tenants is the work we are doing to integrate with the self service analytics (BYODL) architecture. 
We have just gotten the last known blocking product bug for this fixed and so will be returning to investigate CoE integration with this feature. 

Here are some starter links.
https://docs.microsoft.com/power-platform/admin/self-service-analytics
https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by BandyC** [comment]
To make matters worse, the Get-AdminFlow in powershell also seems to have run into a limitation where it does not return flows, even when down selecting using parameters.  We're just trying to list the flows for one user.

Get-AdminFlow -EnvironmentName Default-3596192b-fdf5-4e2c-a6fa-acb706zzzzzzzzz -CreatedBy dc3763eb-5b96-4d46-a438-zzzzzzzzzz -IncludeDeleted $true 

 but doing this returns nothing.  Anyone else having this issue?

**Comment by Jenefer-Monroe** [comment]
We have just released for public preview an architecture for large orgs (ex too many flows for sync flows to handle) 
Please see [Now in preview: CoE Starter Kit backed by data from self-serve analytics data export](https://powerapps.microsoft.com/blog/now-in-preview-coe-starter-kit-backed-by-data-from-self-serve-analytics-data-export/)

**Comment by Jenefer-Monroe** [comment]
Yes we use dataflows to populate the data into Dataverse from the Datalake. One reason for this is to allow for upgrade from Sync Flow architecture to Data Export.

**Comment by TomekPi** [comment]
Ok, so in terms of keeping data which is used by CoE, nothing changes with the new approach (it's still stored in Dataverse like before), is that correct?

**Comment by Jenefer-Monroe** [comment]
Correct. The only difference is in the Audit Logs. We do not store those in Dataverse for BYODL as we did not need to and they take a lots of space. Everything else is still stored in the Dataverse.
