### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#4534]
### Describe the issue

The Setup wizard licensing check doesn't recognize Power Automate with RPA Attended license and flags that check as fail.

### Expected Behavior

All Power Automate Licensing types should be considered a pass, not just Power Automate per user.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Setup Wizard

**Comment by manuelap-msft** [comment]
Hello,

thanks for raising this! We're already tracking this as part of #4429 and have a fix ready to roll out with the February release. Closing this as duplicate.

Thank you
Manuela
