### ISSUE TITLE
[CoE Starter Kit - BUG] Audit logs not gathering

### ISSUE THREAD

**Issue by EWiseman22** [microsoft/coe-starter-kit#4538]
### Describe the issue

COE hasn't been scraping new data for approx. the last two months, it was believed to be related the O365 custom connector which was having issues. However; after the repair of the connector COE is still not being updated with current usage data.

### Expected Behavior

For COE to show current usage data

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

22_11

### What app or flow are you having the issue with?

COE

**Comment by Jenefer-Monroe** [comment]
Hello. It sounds like you are saying that the usage data is what was not coming through. 

Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve. 

Here are some things to check if you believe you already did those steps:
Make sure the connection shows up on the test screen of the custom connector:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

Make sure the flows are running successfully:
![image](https://user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png)

**Comment by EWiseman22** [comment]
Jenefer,
                Thank you for reaching out. Addressing the support provided below we did have issues with this connector but after resolving them we were still not getting fresh data into the COE. We have at this point gotten fresh data to start populating but we are now receiving some failure to complete notices in the COE health center and would like to know if you would be able to assist us with this new issue?

Regards,
Eric R Wiseman

From: Jenefer Monroe ***@***.***>
Sent: Thursday, January 5, 2023 3:58 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Eric Wiseman ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #4538)


Hello. It sounds like you are saying that the usage data is what was not coming through.

Connections to custom connectors get broken on solution upgrade. Please see issue 1424<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/issues/1424__;!!D1M8Vc7dKUMmVhMMK0snbvmI!D7BkRfmCr9ZhF3lD3NVg57pFt0OBdEOc2M0QD728ibjkh1WYpm-Xybq1L9ogVzlosLWEEI0lrUv2sb2KADeKUg0$> for how to resolve.

Here are some things to check if you believe you already did those steps:
Make sure the connection shows up on the test screen of the custom connector:
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png__;!!D1M8Vc7dKUMmVhMMK0snbvmI!D7BkRfmCr9ZhF3lD3NVg57pFt0OBdEOc2M0QD728ibjkh1WYpm-Xybq1L9ogVzlosLWEEI0lrUv2sb2KoBy1il0$>

Make sure the flows are running successfully:
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png__;!!D1M8Vc7dKUMmVhMMK0snbvmI!D7BkRfmCr9ZhF3lD3NVg57pFt0OBdEOc2M0QD728ibjkh1WYpm-Xybq1L9ogVzlosLWEEI0lrUv2sb2KNytJTzc$>

**Comment by Jenefer-Monroe** [comment]
Hello. Glad to hear this issue is resolved. I will go ahead and close it out then. 
Please do feel free to raise new issues as you hit them using the same [bug template](https://github.com/microsoft/coe-starter-kit/issues/new/choose). We are here to help.
