### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI report not showing app usage

### ISSUE THREAD

**Issue by Pavan12Verma** [microsoft/coe-starter-kit#4539]
### Describe the issue

Production Power BI app usage is not showing data
![Production PBI dashboard](https://user-images.githubusercontent.com/101834540/210889398-0ced2ef0-8110-4548-bfaf-383b063c257a.png)
![Production PBI dashboard_AppUsage](https://user-images.githubusercontent.com/101834540/210889419-4fd891a2-dcc3-4319-8e98-0fb2652fa59f.png)
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Not sure data from which flow/app is used for this report

### Steps To Reproduce

1. Open December CoE starter kit 
2. open Production_CoEDashboard_December2022.pbit
3. enter Org url to retrieve the report data
4. Go to introduction page of the dashboard
5. CTRL + click "app usage" under nurture section

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. Here are a few things to note. 

App usage is collected via the audit log flows which are in a solution separate from Core as the setup for them requires additional permissions. Please see [Set up the audit log connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog)

Audit logs begin to collect data from when they are turned on, they do not go back and get historical data.
They are based on a custom connector, and these have issues with upgrade and need to be fixed periodically as described here: https://github.com/microsoft/coe-starter-kit/issues/1424

Please validate that you have installed and setup the [audit log solution](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog)
