### ISSUE TITLE
[Power Platform communication site template] No menu items / navigation after creation powerplatform hub

### ISSUE THREAD

**Issue by gchristina** [microsoft/coe-starter-kit#4540]
### Describe your bug, question or feature ask.

After installation no menu or navigation in the header. I think i saw some exceptions when running the powershell (file not found). The events and items are present at the library. Please advise:

![image](https://user-images.githubusercontent.com/64142375/210976128-bca81cb4-d23a-47cc-8918-e6f8ab03df64.png)

**Comment by petepuu** [comment]
Check that site navigation is enabled

<img width="705" alt="image" src="https://user-images.githubusercontent.com/8307644/211276137-73412980-d1d8-4620-b1f4-007a7a078f2f.png">

**Comment by Laskewitz** [comment]
@gchristina I've seen this one before - and although I don't know how to resolve this in the template (on most occasions it works as expected). In all the cases I've seen this, editing the navigation, and saving it usually does the trick. Can you see if that helps?

**Comment by Laskewitz** [comment]
@gchristina - It's been more than a week ago since the latest response. I hope it's fixed now and if not, please reopen the issue.
