### ISSUE TITLE
[CoE Starter Kit - BUG] How to configure emails

### ISSUE THREAD

**Issue by ellierogers** [microsoft/coe-starter-kit#4547]
### Describe the issue

Please can you add the ability for the email body wording to be editable

### Expected Behavior

Please can you add the ability for the email body wording to be editable as a varaible as per the eMail Body Start & eMail Body Stop, to provide the ability to customise without having to manually edit the flows and therefore mean that monthly upgrades can no longer be implemented

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.20

### What app or flow are you having the issue with?

all that send emails

**Comment by manuelap-msft** [comment]
You can edit the email body using the Admin - Command Center and navigating to the Customize Email tab there.

**Comment by manuelap-msft** [comment]
Currently this is only available for emails send from the Core components solution. We are working on applying this to the emails sent from the Governance and Nurture solutions, and this is tracked via #1683 and should be available in February.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action from starter kit team.
