### ISSUE TITLE
[CoE Starter Kit - BUG] SetupWizard>GetTenantID fails for Organisation that do not have State listed

### ISSUE THREAD

**Issue by tf1970** [microsoft/coe-starter-kit#4549]
### Describe the issue

Error message below. I am based in UK so did not list a State for my organisation on setup, which is causing the parse JSON step to fail

`[
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "value[0].state",
    "schemaId": "#/properties/value/items/properties/state",
    "errorType": "type",
    "childErrors": []
  }
]`

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

SetupWizard>GetTenantID

### Steps To Reproduce

Run the flow for an organisation that does not have a value for state

**Comment by manuelap-msft** [comment]
Hello,

we are already tracking this under #4460 and are expecting to fix this with the February release - closing as duplicate.

To continue with the setup, please set the environment variable manually and then return to the wizard to continue with the guided steps there.

Thank you
Manuela
