### ISSUE TITLE
[CoE Starter Kit - BUG] possible type mismatch comparison

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#4551]
### Describe the issue

After latest CoE Update, the PVA Usage flow reports:

![image](https://user-images.githubusercontent.com/93291159/211340203-1e815c27-683a-4ca9-a9fc-7929918c27e6.png)

### Expected Behavior

No error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

 Sync Template - PVA Updates

**Comment by manuelap-msft** [comment]
Thanks for raising this! This issue is already tracked in our backlog under #4391 and will be fixed with the February release.

Closing this out as duplicate.
