### ISSUE TITLE
[CoE Starter Kit - BUG] Configure communication methods

### ISSUE THREAD

**Issue by torills** [microsoft/coe-starter-kit#4554]
### Describe the issue

I created three M365 groups, but they do not show up in the setup wizard. The groups do not have a team connected to them. 

### Expected Behavior

I expect to be able to write in the group name/email address if I cannot seach the group. I tried that, but it still says "Not configured"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Center of Excellence Setup Wizard

### Steps To Reproduce

1. Create three m365 groups without team in Azure Active directory. 
2. Add the service account as the owner of the three groups
3. Import core components
4. Leave environment variables empty upon import
5. Open Center of Excellence Setup wizard
6. Go to configure communcation methods
7. Try to select the groups, but not able to find them
8. Try searching for the groups but not able to find them
9. Try to paste in the email address to the group and choosing select group but still not be able to configure

**Comment by manuelap-msft** [comment]
Hello,

this is a known issue that we're tracking already. We missed to implement pagination on the control here. You can learn from this comment how to proceed https://github.com/microsoft/coe-starter-kit/issues/4535#issuecomment-1373624016 - it's by updating the environment variables in the background manually, and then returning to the setup wizard.

Closing this out as duplicate but please let us know if you struggle with the manual steps.

Thank you
Manuela
