### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard- Configure communication methods

### ISSUE THREAD

**Issue by jesslyn-omm** [microsoft/coe-starter-kit#4561]
### Describe the issue

I can neither configure an existing group, nor add a new group in the 'Configure communication methods' step

### Expected Behavior

The ability to either create a new M365 group or select an existing M365 group

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CoE Setup Wizard (Preview)

### Steps To Reproduce

Start ehe Center of Excellence Setup Wizard
Confirm pre-requisites
Hit Next
Click any Configure group'  button on the next page
Try to either add a new group or select an existing group.  
Nothing happens when you select a group not displayed in the drop-down (which is an incomplete list of groups)
Attempted creation of a group gives an error

**Comment by Jenefer-Monroe** [comment]
I believe this is known, sending to owner to triage or dupe. 
Thank you for posting.
