### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to update Audit Log custom connector security details?

### ISSUE THREAD

**Issue by jayakumarkgds** [microsoft/coe-starter-kit#4564]
### Describe the issue

One of the new tenant i am configuring COE audit logs and while creating the connector it automatically creating connector. I don't have option to provide app registration details or anything and its not any custom connector now. While running the log am getting authorization denied.

### Expected Behavior

update app details which have permission to read audit logs

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

Import Auditlogs solution
Create office365 management API
Start the flow

**Comment by manuelap-msft** [comment]
Here's the steps to update the custom connector with the app registration details, have you followed those?
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector

**Comment by jayakumarkgds** [comment]
Yes, I was trying exactly same step. But what is see is when i imported audit logs it is no more custom connector. It is part of available connectors and don't have option to edit parameters.
![image](https://user-images.githubusercontent.com/87489417/211804177-bfce2f87-848d-4ddb-aebc-20350cba86ff.png)

**Comment by manuelap-msft** [comment]
Your screenshot looks like it's from the wrong place! When you navigate to make.powerapps.com > open the Dataverse navigation option you will see Connections and Custom Connectors. Your screenshot looks like it's taken from the Connections tab, not the Custom Connectors one. If you select the Custom Connector page, you'll be able to edit:
![image](https://user-images.githubusercontent.com/55705669/211807048-d45ffbd1-7b3c-4ade-9180-4956f7f18658.png)

**Comment by jayakumarkgds** [comment]
This connection when i create it is getting created on connections tab.Custom connectors is blank

**Comment by jayakumarkgds** [comment]
Sorry, this was browser issue custom connectors was showing blank and except all others loading. I have cleared all cache and worked this time.

**Comment by Jenefer-Monroe** [comment]
Wonderful news, thank you for letting us know!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
