### ISSUE TITLE
[CoE Starter Kit - QUESTION] How does the inactivity process for flows work?

### ISSUE THREAD

**Issue by VeerasekarVM** [microsoft/coe-starter-kit#4565]
### Describe the issue

From CoE Starter Kit - Admin | Sync Template v3 (Flow Action Details) it sends email to flow owners as they have stale flows on their name considering the last modified date and gives options for user to reject or approve.

This doesn't make sense as a flow owner i have lot of flows developed and not modified but still their instances are running every minute, which means the flows are still in used.

Moreover flow owner doing the exception options for all his flow is a overhead for everyone even for their manager

### Expected Behavior

Instead of considering last modified date, can the synch flow look for if a flow has any single instance running then don't flag them as stale and dont send mail to flow owners

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.45 CoEStarterKit-December2022

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### Steps To Reproduce

1. Every monday morning COE toolkit Governance flow 'Admin | Sync Template v3 (Flow Action Details)' sends mail to a flow owner if his flow is not modified for a while 
![CEOSynchFlowIssue](https://user-images.githubusercontent.com/61466876/211774654-fb349fbb-cad0-4aa2-ac9e-1ceac2233ab1.png)

**Comment by manuelap-msft** [comment]
Hello,

it's not the Admin | Sync Template v3 (Flow Action Details) flow that sends these emails, but the flows part of the Inactivity process:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/governance-components#inactivity-processes

If the criteria for identifying inactive flows does not fit your need, we would recommend turning the flow off so those emails do not get send and developing your own process for identifying inactive flows - the CoE Starter Kit is only a reference implementation, and it may not always fit your processes. Moreover, for cloud flows we do not have run information available to us programmatically so can't take that into consideration for the inactivity process.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
