### ISSUE TITLE
[ALM Accelerator - QUESTION] Custom Dataverse Roles

### ISSUE THREAD

**Issue by ShinraTenseiii** [microsoft/coe-starter-kit#4567]
### What is your question?

Hi can you please help me understand these Custom Dataverse roles.
o	ALM Power App Access
o	ALM Power App Deployment Configuration
o	App Deployment Orchestration Role

Can you please point me to the right documentation.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20221206.2

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more for the team to follow up on here. Feel free to open a new issue with follow up questions.
