### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to use CoE without permanent access to PP Admin Role

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#4568]
### What is your question?

Hi team, 

Our main concern was around CoE Service Account needing to have an elevated admin permission. In order for us to use Power Platform Service Admin role, we have to request the PP Service admin access and ultimately would lose the elevated privileges after 8 hours. 

It seems to be the biggest bottleneck since we are not able to run the flow and use the accurate CoE data. Do we have any idea or thoughts on how we could remove this blocker? Any advice or thoughts would be appreciated. 

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
I'm afraid I do not know a workaround to this. The flows can run at any time depending on the trigger used, and some are long running, waiting for a response from someone for example or are going through a large amount of data. So permanent access really is required.

You may be able to create a tool which auto-requests and accepts the role, or get an exemption for the identity from your IT.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
