### ISSUE TITLE
[CoE Starter Kit - QUESTION] Do all the connectors needed for the COE kit support a service principal instead of a service account?

### ISSUE THREAD

**Issue by pavankumarkonda** [microsoft/coe-starter-kit#4569]
### What is your question?

Do all the connectors needed for the COE kit support a service principal instead of a service account?

### What solution are you experiencing the issue with?

Core

**Comment by manuelap-msft** [comment]
No, of the connectors, HTTP with Azure AD and Dataverse.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
