### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Log Data

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#4570]
### What is your question?

Hi team, 

Other than LaunchPowerApp, what other information are being logged when we deploy CoE Audit Log Components? I only see LaunchPowerApp information in my Audit Log Dataverse table. 

Thank you! 

### What solution are you experiencing the issue with?

Audit Log

**Comment by Jenefer-Monroe** [comment]
No we do not collect or use any of the other data, only the launches. 
Hope that helps
