### ISSUE TITLE
[CoE Starter Kit - BUG] Admin sync desktop flow is failing in core component solution - Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'.

### ISSUE THREAD

**Issue by NemadeUjwal** [microsoft/coe-starter-kit#4571]
### Describe the issue

Admin sync desktop flow is failing in core component solution

### Expected Behavior

I should get number of desktop flow in my BI report

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

Admin - sync template desktop flow

### Steps To Reproduce

I have more than 100 desktop flow in my environment.

Getting error 
Http request failed as there is an error: 'Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'.

How to fix it ?? Is it fixed in latest release ?

### Anything else?

Na

**Comment by manuelap-msft** [comment]
See: https://github.com/microsoft/coe-starter-kit/issues/4557#issuecomment-1377169762

There are a few known limitations when it comes to Desktop Flows, you can read more about it in the comment above.

**Comment by FQ365Microsoft** [comment]
@manuelap-msft and @Jenefer-Monroe is there any solution to mitigate this issue? We have very few around 200 RPAs but the the inventory flow is failing for the same reason.

**Comment by manuelap-msft** [comment]
There currently isn't a workaround for this, but I'd recommend checking out the separate [Automation kit](http://aka.ms/automationcoe) which may help you with workarounds to overcome this issue.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
