### ISSUE TITLE
[CoE Starter Kit - QUESTION Creator Kit needed to install

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4577]
### What is your question?

we have installed October release CoE in our QA Environment now planning to move to Prod Tenant 

But I have seen December release with Creator Kit. 

Could you please let me know If I can go ahead and Install CoE Starter Kit from Scratch without Creator Kit 

What is the process of Creator Kit there is not guidelines about Creator Kit 

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup

https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup

kindly please suggest 

If I can proceed to Install from scratch or upgrade CoE with Creator Kit 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Power Platform Admin View App

**Comment by manuelap-msft** [comment]
If you're installing the December release, the Creator Kit is mandatory and required to be installed before installing the CoE starter kit as the CoE starter kit now uses Creator Kit components. 

Here's the setup instructions for the Creator Kit:
https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/setup

If you are moving the October release from QA to Prod, this will not require the Creator Kit to be installed. It's a dependency only from the December release going forward.

**Comment by pamatihyd** [comment]
what if we go ahead with October release  

Scratch installation of CoE , In future will be able to upgrade to latest version ?

**Comment by manuelap-msft** [comment]
I'm not sure I fully follow your questions

1. For the October release, you won't need the Creator Kit installed.
2. If you are installing or upgrading to the December release, you will have to install the Creator Kit first.

**Comment by pamatihyd** [comment]
Thanks alot for the answer I am able to install new as well as upgrade also.

Before installing CoE core components I have installed , creator kit solution and then installed/upgraded CoE core component solution .Thank you 

How to know which are all the apps or things that are now updated or referenced with Creator Kit Solution.?

Why I am asking this means, we need to do production deployment now , and we got to know December release .
we have done the upgrade but what is the impact and dependency with Creator Kit if we go for Prod deployment

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont follow this question. You will need to deploy the same version of the Creator Kit into your Prod envt too and then it will behave as it does in your pre-prod envt. 

You can explore dependencies though if you'd like using the product UX. 
For example, to see what depends on the Search Box component for example you could go see like this
![image](https://user-images.githubusercontent.com/89584709/212983508-73efc400-311a-44bf-9910-a4cbafac556e.png)
![image](https://user-images.githubusercontent.com/89584709/212983700-41c5768d-13e6-48d5-a2d4-8856a3a97724.png)

Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
