### ISSUE TITLE
Where's the January release of the CoE Starter Kit and ALM Accelerator? 

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4578]
### What is your question?

This December 2022 release is the latest version of the CoE Starter Kit + ALM Accelerator solutions. Due to the holiday season, the team will not release a new version in January. 

We'll be back with monthly releases in February, and you can check what's tentatively planned for the February release by viewing this milestone:
https://github.com/microsoft/coe-starter-kit/milestone/37

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
February 2023 now released https://github.com/microsoft/coe-starter-kit/releases/latest
