### ISSUE TITLE
[CoE Starter Kit - BUG] Tenant ID doesn's stick in setup wizard's "mandatory setings" step (new installation of CoE)

### ISSUE THREAD

**Issue by anttipajunen** [microsoft/coe-starter-kit#4579]
### Describe the issue

When entering a tenant ID in mandatory settings, the given value doesn't stick.

![Mandatory settings](https://user-images.githubusercontent.com/64043240/212074396-a8b9fc35-2597-403f-b022-21fb33d5c85a.png)
![image](https://user-images.githubusercontent.com/64043240/212074545-853ab9bd-af25-43c2-ac22-5b69ce85d4c6.png)

This will cause "setup flows" step to not display any flows.

![image](https://user-images.githubusercontent.com/64043240/212074672-e1b1fbde-5195-4440-b890-3d16e02b6092.png)

Upon examination, the following flows are not turned on:
Admin | Sync Template v3 CoE Solution Metadata
Command Center App > Get M365 Service Messages 

When manually turning on the metadata flow, an error of a missing tenant ID is given:
![image](https://user-images.githubusercontent.com/64043240/212074996-33b180d0-0cd9-4a3f-a652-d00e9985ac17.png)

If the TenantID environment variable is manually updated with a value, the setup wizard still fails to turn on the metadata flow, and it needs to be turned on manually. When the setup wizard is then revisited, no setup flows are visible and then patch error is given:
![image](https://user-images.githubusercontent.com/64043240/212076376-887cfbd2-5771-4b1a-b333-73ac6957d654.png)

The root cause seems to be a missing value for admin_PowerPlatformUserGroupID, which has been deliberately been left null.
![image](https://user-images.githubusercontent.com/64043240/212077696-4ec68088-f029-4ff4-a748-0ec9d4489b3b.png)

When admin_PowerPlatformUserGroupID is given a value, the setup flows are displayed:
![image](https://user-images.githubusercontent.com/64043240/212078711-50c43a69-ec68-49a9-b613-f821723b7f2f.png)

### Expected Behavior

TenantID given in the setup wizard sticks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

### Steps To Reproduce

Repro steps in desc.

**Comment by manuelap-msft** [comment]
Hello,

thanks for the detailed analysis here! Could you check the run history of the SetupWizard>GetTenantID flow and check why it fails? 

Ideally we'd get that fixed so it's passing and no manual overwrite is needed but we'll look at both why it's failing and why manual overwrite isn't working.

Thank you
Manuela

**Comment by anttipajunen** [comment]
Yep. It seems to fail at the parse JSON for a null "state" property.

![image](https://user-images.githubusercontent.com/64043240/212104672-f88f3f89-9c74-464c-ac81-659c09a241f5.png)

**Comment by manuelap-msft** [comment]
Perfect, thank you - that's something we already have on our backlog #4460. Just wanted to make sure it didn't fail for a different reason!

We'll investigate why manually setting it fails!

**Comment by jeremy-Itprofessional** [comment]
Goodmorning,

I have the same issue, here if i look to the value of the key in dataverse it is empty, is there a way to manually fill the TenantID value?

**Comment by manuelap-msft** [comment]
Hello,

you can manually update the environment variable for Tenant ID following these two options:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables
