### ISSUE TITLE
[CoE Starter Kit - QUESTION] Help with CoE kit installation

### ISSUE THREAD

**Issue by RocketmanACEGov** [microsoft/coe-starter-kit#4588]
### What is your question?

Is there a way to track down which flow is posting as a flow bot using an AI Builder connector?

The customer is using COE but trying to sort through 6,000 flows, and they can’t see a specific connector under connectors in the COE called “AI Builder.”

### What solution are you experiencing the issue with?

Core

**Comment by manuelap-msft** [comment]
Hello,

the CoE starter kit is an unsupported reference implementation https://learn.microsoft.com/en-us/power-platform/guidance/coe/feedback-support, and is maintained by a very small team - we do not offer hands-on installation support.

Here's some options available to you:
- Work with your Microsoft Account Team to get a Power Platform Customer Engineer assigned to you, they have dedicated programs to help set up the CoE kit 
- Many of our partners offer different levels of CoE kit services, here is some you can find in AppSource https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&exp=ubp8&search=coe&page=1 - though if you are already working with a Power Platform partner it may be worth checking with them if they have CoE kit services as well.

Manuela
