### ISSUE TITLE
[CoE Starter Kit - BUG] Trouble with install

### ISSUE THREAD

**Issue by soniabordelon** [microsoft/coe-starter-kit#4591]
### Describe the issue

We are having difficulty installing the Power Platform COE Starter kit.  Can someone assist us with the installation?

### Expected Behavior

COE to be installed with out any issues.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

We have installed but it is not working. Getting no data in the reports.  Need to find out if it is installed correctly.

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid this forum is the only way our team is able to assist with CoE Starter Kit issues, including install.

If you need someone to walk you through setup step by step, you may need to hire a partner who specializes in the kit. Please see this list in [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

If you would like help here in the forum, please describe the issue you are having in details.

**Comment by soniabordelon** [comment]
We have installed the COE Starter Kit but it is not working.  We need assistance trouble shooting so that it is running properly.

From: Jenefer Monroe ***@***.***>
Sent: Monday, January 16, 2023 7:08 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Bordelon, Sonia M ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Trouble with install (Issue #4591)

CAUTION:This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




Hello. I'm afraid this forum is the only way our team is able to assist with CoE Starter Kit issues, including install.

If you need someone to walk you through setup step by step, you may need to hire a partner who specializes in the kit. Please see this list in AppSource<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fappsource.microsoft.com%2Fen%2Fmarketplace%2Fconsulting-services%3Fproduct%3Dpowerapps%26src%3Dpa-m%26search%3Dcoe%26page%3D1&data=05%7C01%7Csonia.m.bordelon%40conocophillips.com%7C438b67501a54478562ee08daf7c2a21e%7Cb449db5ea80a48eba4c23c88bb78353b%7C0%7C0%7C638094712607404014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZSXlQDk%2BatLs%2FwgQQhg5CGKHaCkx4910FQmXulHF444%3D&reserved=0>

If you would like help here in the forum, please describe the issue you are having in details.

-

**Comment by Jenefer-Monroe** [comment]
I'm afraid you will need to drive the conversation, we cannot start from this opaque of a state. 
Please share what you are seeing that makes you think its not working.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by soniabordelon** [comment]
Hello, we need some assistance with installing the COE Starter Kit.   We have followed the guide and a video.  These are the variables we have added and the error we are getting:

Our Variables:
***@***.***

***@***.***

Error:

***@***.***



From: Jenefer Monroe ***@***.***>
Sent: Tuesday, January 17, 2023 8:35 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Bordelon, Sonia M ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Trouble with install (Issue #4591)

CAUTION:This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




I'm afraid you will need to drive the conversation, we cannot start from this opaque of a state.
Please share what you are seeing that makes you think its not working.

-

**Comment by soniabordelon** [comment]
Hello, we need some assistance with installing the COE Starter Kit.   We have followed the guide and a video.  These are the variables we have added and the error we are getting:

Our Variables:
***@***.***

***@***.***

Error:

***@***.***

From: Jenefer Monroe ***@***.***>
Sent: Tuesday, January 17, 2023 8:35 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Bordelon, Sonia M ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Trouble with install (Issue #4591)

CAUTION:This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




I'm afraid you will need to drive the conversation, we cannot start from this opaque of a state.
Please share what you are seeing that makes you think its not working.

-

**Comment by Jenefer-Monroe** [comment]
Pictures do not come through if you reply in email. You need to log in to GitHub to share pictures.
