### ISSUE TITLE
[Power Platform communication site template] Deployment of Power Platform Hub failed

### ISSUE THREAD

**Issue by KiraXie2** [microsoft/coe-starter-kit#4595]
### Describe your bug, question or feature ask.

Deployment of Power Platform Hub failed!

INFO: PnP.PowerShell module is already installed.
INFO: PnP.PowerShell module is up to date.
INFO: Connecting to SharePoint Online
INFO: Connecting to https://zf-admin.sharepoint.com
INFO: Connected to https://zf-admin.sharepoint.com
INFO: Creating new site...
ERROR: An error occurred.
ERROR: Deployment of Power Platform Hub failed!
![image](https://user-images.githubusercontent.com/108067225/212625107-74f11f67-f6c6-4f78-af26-a08d00a4c91e.png)

**Comment by Laskewitz** [comment]
Hi @KiraXie2 -

Can you please navigate to the right directory (`C:\Users\Z0147856\Downloads\PowerPlatformHub` instead of `C:\WINDOWS\system32`) and try running the script again?

Thanks,
Daniel

**Comment by KiraXie2** [comment]
Hi, finally I didn't have SharePoint Admin role. So I replaced all the PnP related commands to the ones bypassing creating tenant site or anything like that. But I asked our SharePoint Admin to enable custom scripts on the site. So finally I was able to run the script partially successfully and got an expected result.

**Comment by Laskewitz** [comment]
Thanks for reporting back! Hope you like the site! 👍🏼
