### ISSUE TITLE
[CoE Starter Kit - BUG] Inactivity process sends emails to Admin but the apps have Owner

### ISSUE THREAD

**Issue by GaelCasOuv** [microsoft/coe-starter-kit#4597]
### Describe the issue

I have started the inactivity process flow for apps and I have received many approval emails with the message:

"OWNER DOES NOT EXIST. APPROVAL SENT TO ADMIN."

But, checking the app in the CoE Dashboard and in Set App Permissions app the apps seem to have owner indeed.

### Expected Behavior

Send the email to the owners

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

November

### What app or flow are you having the issue with?

Admin - Inactivity notifications V2

**Comment by Jenefer-Monroe** [comment]
Can you please check the value of the **_Production Environment_** environment variable? If you have the environment set to non-production (value is No) then all communications go to the admin. 
If that is not the case then you will need to find an individual case where you expect it to go to user but it doesnt, and we will need to debug in the flow together.

**Comment by GaelCasOuv** [comment]
Hi Jenefer, the Production Environment variable is set to Yes, indeed most of the emails go to the owners but some don't.

Please let me know what you need for the debugging

**Comment by Jenefer-Monroe** [comment]
Sounds like your repro is for an App, so plesae go to the latest run of **_Admin | Inactivity notifications v2 (Start Approval for Apps)_**

Look in the output of this action and find the app by searching for its appid. Note the use of some JSON parser here will give you the index
![image](https://user-images.githubusercontent.com/89584709/212734167-0a7d2aa0-0e88-416b-952c-e5b5e21b62b1.png)

![image](https://user-images.githubusercontent.com/89584709/212734519-93f99a1b-48d8-428c-a591-eab49625e5dd.png)


Then find it in the Apply to Each, you can make sure you are on the right one by checking the AppLink value
![image](https://user-images.githubusercontent.com/89584709/212734861-50ee04a1-d142-46aa-aaf9-e8f4c1168336.png)

Lets see how it behaves in the loop

**Comment by lukas-nC** [comment]
Is in these cases the owner also the original creator?
Are these Apps/Flows marked as orphaned?

**Comment by GaelCasOuv** [comment]
@Jenefer-Monroe it's a bit strange because I cannot find the "AppLink" step in "Create Archival request for Each":

![image](https://user-images.githubusercontent.com/110904209/212859084-16430288-35d3-41df-b89f-fe0d3642e16d.png)

@lukas-nC the apps are not Orphaned. I don't know how I can check if the current Owner is the original creator.

**Comment by Jenefer-Monroe** [comment]
You may have unmanaged layers preventing you from seeing the current flow. Can you please see if it has one to remove? 
[Removing other customizations](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#removing-other-customizations)

**Comment by GaelCasOuv** [comment]
It seems there are not unmanaged layers:

![image](https://user-images.githubusercontent.com/110904209/212927824-c2e2f1fd-c69f-41ce-b36b-1c36827e1d32.png)

**Comment by Jenefer-Monroe** [comment]
ok perhaps that compose statement was just added later than Nov. You can just skip that then and lets see where this item goes down the path. 

First open the Get Assignee, what path does it go down there?

**Comment by GaelCasOuv** [comment]
![image](https://user-images.githubusercontent.com/110904209/212930085-4472042e-10de-4e60-a88a-1946302c67be.png)

**Comment by Jenefer-Monroe** [comment]
ok so it looks like this user did not return from the orphan check there to Office 365
Can you open this to see what is returned? 
![image](https://user-images.githubusercontent.com/89584709/212931216-14a42e4a-1726-4ab2-b237-7f71dea9470b.png)

**Comment by GaelCasOuv** [comment]
I don't know if I'm in the correct branch...

In the JSON parse tool it appears to be in the 14th position starting from 0 so, I have selected the 15th one:

![image](https://user-images.githubusercontent.com/110904209/212938876-8c7ab73a-422b-4997-b48f-f012a2a60770.png)

I have seen other behaviour in the 16th:

![image](https://user-images.githubusercontent.com/110904209/212939437-5a803b33-ef9b-4935-a072-35521a045275.png)

**Comment by Jenefer-Monroe** [comment]
yes i belive it would be the 15th one then since these start at 1, and the json parser starts at 0

Does this user (800...) exist in the AD? 
https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers
You can search by GUID there if you paste the entire GUID
![image](https://user-images.githubusercontent.com/89584709/212957936-a0937f05-e1a3-4afb-ad84-e2b88d3a5705.png)

**Comment by GaelCasOuv** [comment]
The user doesn't exist in the AD, the question now would be why the flow checks a different user code than the other CoE starter kit apps.

**Comment by Jenefer-Monroe** [comment]
If the user doesnt exist then it is expected to go to the Admin instead. Its not using a different code, we just happen to know who it used to be so we show them. This data can often help to reassign.

**Comment by Jenefer-Monroe** [comment]
Hope that makes sense.

**Comment by GaelCasOuv** [comment]
To be honest I'm still confused, In Power Platform Admin View the app has an owner that exists in the AD, so I don't get where the Inactivity flow takes this app owner ID.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
