### ISSUE TITLE
[CoE Starter Kit - QUESTION] Governance - Request Orphaned Objects Reassigned (Child)

### ISSUE THREAD

**Issue by dksamo1986** [microsoft/coe-starter-kit#4598]
### What is your question?

We have experienced that the flow is throwing an error in relation to missing child flows. However, in the action it is just showing the guid and not the name of the flow. Thus, we are not sure which flow it is supposed to call or what the name is. 

<img width="358" alt="Reassign this one to manager error" src="https://user-images.githubusercontent.com/122786332/212653998-6f299d22-4678-4ce5-b6aa-ab35861f0625.png">
<img width="162" alt="Flow checker error" src="https://user-images.githubusercontent.com/122786332/212653991-d71c83ba-dcb4-45a8-8ed0-6760326d9b3f.png">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.16

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

**Comment by Jenefer-Monroe** [comment]
Unfortunately only GUIDs are shown on managed installs. 

Generally when you hit this, you can go to the setup instructions for the area to see what child flow its referencing. 
For this one, that's [Set up clean-up for orphaned objects](https://learn.microsoft.com/power-platform/guidance/coe/setup-orphan-components)

And this is the child flow
![image](https://user-images.githubusercontent.com/89584709/212690634-ad098357-31ce-468e-9ab5-1e08ac92c334.png)

Hope that helps!

**Comment by dksamo1986** [comment]
Hi Jenefer,

Yeah - I figured that out after I enabled both helper flows. After that, I was able to remove run-only-user connections and I was able to turn on both cloud flows to handle orphaned objects. 

Thank you for your initial help. 

Best regards,

Sabri

**Comment by Jenefer-Monroe** [comment]
Glad you are unblocked! I'll go ahead and close but please feel free to reach out if you need anything else. 
Thanks for using CoE
