### ISSUE TITLE
[CoE Starter Kit - ALM for the CoE] Which is the best way for?

### ISSUE THREAD

**Issue by javiercheke** [microsoft/coe-starter-kit#4601]
### What is your question?

Hello CoE team

Right now we are working with two environments for the CoE.

We are working with a service user in DevOps to bring new customizations to DEV to PRO with a pipeline for it.

Both environments have managed solutions installed, and normally the CoE Started solutions are installed in this environment manually, sometimes we can have some issues with dependencies just in case a new customization is using some of the components of the CoE solutions, or because some flows lose connection references, (in these cases the connection references are renewed from the solution but if someone needs to run the flow an unmanaged layer is created with the new connection reference). 

On this basis, what is the best way to update the CoE Starter Kit?

We have already looked at the information on extending and upgrading CoE.
So the final goal about this context (sorry for the long explanation) is to see if there is a recommendation to follow here regarding the ALM.

Is it possible to follow an ALM with the CoE Starter solution and customization at the same time? What is the best way to achieve this?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
