### ISSUE TITLE
[Automation Kit - Feature] Add new project button is missing in Automation Project canvas app

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/coe-starter-kit#4602]
### Describe your bug, question or feature ask.

Add new project button is missing in Automation Project canvas app

**Comment by manuelap-msft** [comment]
Hello,

is your issue related to the [Automation Kit](https://aka.ms/automationkit)? If so, that solution is maintained in a different GitHub repo and you can raise an issue for the team here: https://aka.ms/automation-kit-issues

Thank you
Manuela

**Comment by ApoorvaKantale** [comment]
Thank you
