### ISSUE TITLE
The admin_environmentsku field is "NotSpecified" for Teams environments

### ISSUE THREAD

**Issue by vilmarci** [microsoft/coe-starter-kit#4607]
Upgraded from version 1.x to 4.2. We have a lot of Teams environments, but the field shows "NotSpecified" for these. The inventory has been run overnight.

**Comment by Jenefer-Monroe** [comment]
I remember seeing this issue once when we first added the support for teams envts, but we added it so long ago that I cant recall what it was. Perhaps it was the API version on the call? It should be as shown here

![image](https://user-images.githubusercontent.com/89584709/212965365-e684877d-b650-4fb7-8176-9122c0070ce7.png)

Do you have unmanaged layers on the Admin | Sync Template v3? Please see [Removing customizations](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#removing-other-customizations)

**Comment by vilmarci** [comment]
No, I have only one layer. I ended up updating these in the database directly hand (replaced with "Teams") and hope this didn't break anything :)

**Comment by Jenefer-Monroe** [comment]
Well that wont break anything, but it also wont stay up to date unfortunately, I expect you'll see those reset next run. 
Did you check that you have the correct API version here? 
![image](https://user-images.githubusercontent.com/89584709/212965365-e684877d-b650-4fb7-8176-9122c0070ce7.png)

**Comment by vilmarci** [comment]
I cannot go to edit, but yes, it is the same:
```
{
    "host": {
        "connectionReferenceName": "shared_powerplatformforadmins_1",
        "operationId": "Get-AdminEnvironment"
    },
    "parameters": {
        "api-version": "2021-03-01",
        "$expand": "properties.capacity,properties.addons"
    }
}
```
And, indeed the "Teams" text is gone and set back to NotSpecified.

**Comment by vilmarci** [comment]
Now, I'm confused. They are back again. So, the output of the Get Environments actions says **"environmentSku":"Teams"**
There's no environment in the response saying NotSpecified in the output.
The database contains "NotSpecified" for ALL teams environments.
The Update Environment action also says "Teams" here.

I have no idea where this NotSpecified is coming from. Maybe another flow?

**Comment by Jenefer-Monroe** [comment]
I'm pretty confused too. Please go to the latest run of **_Admin | Sync Template v3_**

Find the index of one of your teams environments from this output
![image](https://user-images.githubusercontent.com/89584709/213757381-0d77a075-0ba7-4428-b89a-ae5de6397d21.png)

Find it's index in the apply to each
![image](https://user-images.githubusercontent.com/89584709/213757609-2d8587ad-aad9-47ab-8c50-eb0a7258f225.png)

I presume it will go down this path:
Check if Legacy > No branch
![image](https://user-images.githubusercontent.com/89584709/213757878-acf3725e-61b1-4bb8-8ab4-a0f37654a365.png)

See if already in CoE > Yes branch
![image](https://user-images.githubusercontent.com/89584709/213757985-af000fe0-4257-4a13-8fff-686ab914ae79.png)

See if excused from inventory > No branch
![image](https://user-images.githubusercontent.com/89584709/213758155-43c9eb7e-82dc-417f-b7ac-cdc10e1681f1.png)

Check if System created Environment > No branch
![image](https://user-images.githubusercontent.com/89584709/213758541-1e0eea2a-1a0d-4c74-a19d-458310d18fec.png)

Update after check orphan status --> either branch. 
See what gets put into sku?
![image](https://user-images.githubusercontent.com/89584709/213760071-3d268e6a-8442-42a4-b42b-f43086e3693b.png)

**Comment by vilmarci** [comment]
![image](https://user-images.githubusercontent.com/38534390/213769234-44e13f2e-178e-44ed-ad1b-89a0ac19a0fe.png)

And (and I'm writing this a weekend later than the previous screenshot), the current data looks again like this:
![image](https://user-images.githubusercontent.com/38534390/214061502-24d03740-7831-4b2f-8002-43115b837a44.png)

So, it seems like that the value of this field is switching between Teams and NotSpecified

**Comment by Jenefer-Monroe** [comment]
There must be some other process touching the table, since the above is what we would expect. 
Can you please share a screenshot of the solutions in the environment like this? Be sure to expand the columns so we can see the full value in the "Name" column (the second column)
![image](https://user-images.githubusercontent.com/89584709/214113323-52aca178-dabf-44c1-b6eb-11d7d69f36cc.png)

**Comment by vilmarci** [comment]
Now that you ask, there are some leftovers from an older version of the CoE toolkit: 
![image](https://user-images.githubusercontent.com/38534390/214243267-d5fa741a-8bd6-4b2d-b170-41f2b52758b6.png)

**Comment by Jenefer-Monroe** [comment]
Yes I'm afraid I dont know what state you are in with those other old solutions. 

Are you actually using all those other features? If not perhaps you can delete those old solutions and see where we are at.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
