### ISSUE TITLE
[CoE Starter Kit - QUESTION] App usage page is blank

### ISSUE THREAD

**Issue by Nick-Mac** [microsoft/coe-starter-kit#4610]
### What is your question?

Guys, I have followed all of the instructions and I have the COE Starter-Kit almost fully set up but I cannot get any info to display under the "App Usage" section on the PowerBi Dashboard. I was able to successfully setup the audit log solution and i am getting no errors with the Audit Log Sync flows. I am sure there is something stupid that I have missed, but I have been pouring over the documentation and doing research with no luck.

Here are the steps I followed to get the audit components set up. https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
 
![AppUsageDashboard](https://user-images.githubusercontent.com/122926082/212992845-c25d6d0c-b2f4-4f72-b328-fff56921905c.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Latest as of December 2022

### What app or flow are you having the issue with?

PowerBi Dashboard

**Comment by Nick-Mac** [comment]
Here are some updated screenshots of my environment to show you I'm pretty sure I have things set up correctly.

![Admin Sync Logs](https://user-images.githubusercontent.com/122926082/213002075-e461b0a3-c83b-4e54-b2d1-4c9d445751fb.png)

![Child Admin Sync Logs](https://user-images.githubusercontent.com/122926082/213002159-e453105a-102a-4ef2-8e32-51df7ad1e27d.png)

![Audit Log Proof](https://user-images.githubusercontent.com/122926082/213002181-be819eea-98a6-4ea7-907f-d0574093a071.png)

![Custom Connector](https://user-images.githubusercontent.com/122926082/213002196-8b01f75c-d99b-4499-a114-63d59d1394f9.png)

**Comment by Nick-Mac** [comment]
We are a commercial tenant

**Comment by Nick-Mac** [comment]
![Custom Connector](https://user-images.githubusercontent.com/122926082/213252931-3068a914-20e6-43c2-89c7-18f038a4fcd9.png)

![Admin Sync Logs](https://user-images.githubusercontent.com/122926082/213252841-1c060db4-c348-46c1-a765-242296161f7e.png)

![Child Admin Sync Logs](https://user-images.githubusercontent.com/122926082/213252858-9078d20e-3208-44c1-915c-f753e03c5773.png)

![Audit Log Proof](https://user-images.githubusercontent.com/122926082/213252870-864afa12-7766-4621-8ff2-bb7801e30492.png)

**Comment by Jenefer-Monroe** [comment]
oh you have data, its just not showing in the PBI? Did you refresh the PBI report?

**Comment by Nick-Mac** [comment]
LOL, wow... Thank you! I knew it was something stupid.

I set up the PBI report under another user account that did not have access to the dataset so the scheduled refresh was not working hence the little alert icon on the dataset... smh. I connected to the dataset using the correct account and hit the data refresh button and we are now rolling. Thank you so much!

Separate question, is there some documentation providing others access to different areas the COE Toolkit?  Right now, everything is working perfectly with the service account I used to set it up. However, the goal here would be to provide others with a level of "Admin" access and others (probably managers and higherups etc.) with a view of some of the overview data. 

Thank you again.

**Comment by Jenefer-Monroe** [comment]
Haha YEAH!!! Glad it was an easy fix and we are here to help so no problem at all. :)

Yes we are working on automating this but for now you will need to do it manually. Here described for the Admin persona.
1) You should have a group for the admins [How will you communicate with your admins, makers, and users](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users)
2) You should add that group to the Power Platform Admin SR [Security Roles](https://learn.microsoft.com/power-platform/guidance/coe/core-components#security-roles)
3) You should share the apps with that Group. (can be done with # 2)

Hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
