### ISSUE TITLE
[CoE Starter Kit - QUESTION] Orphaned Objects - what flow fills the manager for makers? 

### ISSUE THREAD

**Issue by dksamo1986** [microsoft/coe-starter-kit#4611]
### What is your question?

Hi Jenefer,

I have just enabled the two flows that handles orphaned objects for my organization. There were 7 apps and 29 flows. However, it did not find a manager for any of the objects. 

I looked into this and found that the Maker table had no manager for any of the makers. 

The question is which flow updates the maker table to ensure the relevant data is updated accordingly, for this process to actually work?

<img width="544" alt="Flow elaboration" src="https://user-images.githubusercontent.com/122786332/213113938-caad26bd-bc96-495b-83e9-1ccda4cdfe42.png">
 

Thank you for your time. 

Best regards,

Sabri

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.16

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

**Comment by Jenefer-Monroe** [comment]
Hello. This is filled by the following flow: **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_**

It will fill the manager if the user still exists in the AD when you run it. If the user has already left before this flow is run, it cannot get the information. 

I hope that helps.

**Comment by dksamo1986** [comment]
Hi Jenefer,

This helps. Thank you. 

Have a great week. 

Best regards,

Sabri

**Comment by Jenefer-Monroe** [comment]
Wonderful, I will go ahead and close then, but please feel free to open new issues if you need more help.
