### ISSUE TITLE
[Power Platform communication site template] An Error occurred

### ISSUE THREAD

**Issue by xavieralonso** [microsoft/coe-starter-kit#4614]
### Describe your bug, question or feature ask.

When I execute Deploy-PowerPlatformHub.ps1 script I get an error message. 
This is the transcript:

.\Deploy-PowerPlatformHub.ps1
INFO: PnP.PowerShell module is already installed.
INFO: PnP.PowerShell module is up to date.
INFO: Connecting to SharePoint Online
INFO: Connecting to https://axinter-admin.sharepoint.com
INFO: Connected to https://axinter-admin.sharepoint.com
INFO: Creating new site...
ERROR: An error occurred.
ERROR: Deployment of Power Platform Hub failed!

These are the defined variables:

$adminTenantName = 'axinter'
$adminURL = 'https://' + $adminTenantName + '-admin.sharepoint.com'
$companyName = 'Axel Johnson International AB'
$lcid = 1033
$newSiteURL = 'https://' + $adminTenantName + '.sharepoint.com/sites/powerplatformhub'
$ownerEmail = 'gadmin@axinter.onmicrosoft.com'
$siteTemplate = 'SITEPAGEPUBLISHING#0'
$siteTitle = 'Power Platform Hub'
$timeZone = 4

Thank you in advance

**Comment by Laskewitz** [comment]
Hi @xavieralonso - 

Can you please check the following:

- Do you have the rights to create a site collection?
- Can you check in the SharePoint Admin Center if a site collection with the url `https://axinter.sharepoint.com/sites/powerplatformhub` was created?
  - If yes, can you run the script again?
  - If not, can you try creating the site collection manually and run the script again?

Thanks,
Daniel

**Comment by xavieralonso** [comment]
Hi Daniel.

I'm Global Admin in this tenant. 
The https://axinter.sharepoint.com/sites/powerplatformhub site was not created, I just created it manually right now.

I run the script again. This is the transcript:

PS C:\Users\xavier.alonso\OneDrive - AXEL JOHNSON INTERNATIONAL AB\PowerPlatform\Communication_HUB> .\Deploy-PowerPlatformHub.ps1
INFO: PnP.PowerShell module is already installed.
INFO: PnP.PowerShell module is up to date.
INFO: Connecting to SharePoint Online
INFO: Connecting to https://axinter-admin.sharepoint.com
INFO: Connected to https://axinter-admin.sharepoint.com
INFO: Site already exists, skipping creation of site...
ERROR: An error occurred.
ERROR: Deployment of Power Platform Hub failed!

**Comment by xavieralonso** [comment]
I fix the problem. Thank you for your time.

**Comment by xavieralonso** [comment]
Hi,

I created the site but It appears without sections on the menu ( upper Ribbon )

This is the script transcript:

INFO: PnP.PowerShell module is already installed.
INFO: PnP.PowerShell module is up to date.
INFO: Connecting to SharePoint Online
INFO: Connecting to https://axinter-admin.sharepoint.com
INFO: Connected to https://axinter-admin.sharepoint.com
INFO: Creating new site...
.INFO: Wait 15 seconds to make sure the site is ready...
INFO: Connecting to newly created site
INFO: Deploying template...
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:22:43.5069	[PnP.Framework]	[0]	[Information]	File template.pnp retrieved from folder 	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:22:43.5280	[PnP.Framework]	[0]	[Information]	File template.pnp retrieved from folder 	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:22:44.0883	[PnP.Framework]	[0]	[Information]	File template.xml retrieved from folder 	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:22:44.1566	[Provisioning]	[16]	[Information]	ProgressDelegate registered	0ms	6b602b44-7850-40e4-82cf-08f75ea0094f
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:22:44.1576	[Provisioning]	[16]	[Information]	MessagesDelegate registered	1ms	6b602b44-7850-40e4-82cf-08f75ea0094f
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:22:45.6800	[PnP.Framework]	[0]	[Information]	Activating feature 94280101-dc63-4b83-842a-8707b1afb62d in web.	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:22:46.9156	[PnP.Framework]	[0]	[Information]	Activating feature 8c6f9096-388d-4eed-96ff-698b3ec46fc4 in web.	0ms	
PowerShell_ISE.exe Warning: 0 : 2023-01-18 16:22:50.4335	[List instances]	[16]	[Information]	Skip adding/updating custom actions because the site has "noscript" enabled.	865ms	6b602b44-7850-40e4-82cf-08f75ea0094f
PowerShell_ISE.exe Warning: 0 : 2023-01-18 16:22:52.1871	[List instances]	[16]	[Information]	Skip adding/updating custom actions because the site has "noscript" enabled.	2618ms	6b602b44-7850-40e4-82cf-08f75ea0094
f
PowerShell_ISE.exe Warning: 0 : 2023-01-18 16:23:05.5634	[List instances]	[16]	[Information]	Skip adding/updating custom actions because the site has "noscript" enabled.	786ms	6b602b44-7850-40e4-82cf-08f75ea0094f
PowerShell_ISE.exe Warning: 0 : 2023-01-18 16:23:07.3871	[List instances]	[16]	[Information]	Skip adding/updating custom actions because the site has "noscript" enabled.	2610ms	6b602b44-7850-40e4-82cf-08f75ea0094
f
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:20.1912	[PnP.Framework]	[0]	[Information]	File 2931574937.png retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:21.4881	[PnP.Framework]	[0]	[Information]	File CLO17.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:22.9431	[PnP.Framework]	[0]	[Information]	File Commute.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:24.5933	[PnP.Framework]	[0]	[Information]	File edd2.svg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:25.7840	[PnP.Framework]	[0]	[Information]	File Edu001.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:27.2549	[PnP.Framework]	[0]	[Information]	File Edu009.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:29.1918	[PnP.Framework]	[0]	[Information]	File Group016.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:30.6038	[PnP.Framework]	[0]	[Information]	File Hybrid030.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:32.0303	[PnP.Framework]	[0]	[Information]	File InclusiveWorkplace.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:33.3068	[PnP.Framework]	[0]	[Information]	File India017.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:34.8538	[PnP.Framework]	[0]	[Information]	File LaptopGo.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:36.1096	[PnP.Framework]	[0]	[Information]	File Lobby003.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:37.5604	[PnP.Framework]	[0]	[Information]	File Office.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:38.8715	[PnP.Framework]	[0]	[Information]	File OfficeMeeting1.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:40.1486	[PnP.Framework]	[0]	[Information]	File OfficePortrait.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:41.5714	[PnP.Framework]	[0]	[Information]	File OutsideOffice.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:43.1653	[PnP.Framework]	[0]	[Information]	File Paddington011.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:44.9177	[PnP.Framework]	[0]	[Information]	File powerapps.png retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:46.0407	[PnP.Framework]	[0]	[Information]	File Productivity1.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:47.3671	[PnP.Framework]	[0]	[Information]	File Productivity2.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:48.6313	[PnP.Framework]	[0]	[Information]	File Productivity3.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:50.0076	[PnP.Framework]	[0]	[Information]	File Redmond1.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:51.3564	[PnP.Framework]	[0]	[Information]	File Security024.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:52.7536	[PnP.Framework]	[0]	[Information]	File Slalom.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:54.0139	[PnP.Framework]	[0]	[Information]	File Team001.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:55.5984	[PnP.Framework]	[0]	[Information]	File Win15.jpg retrieved from folder SiteAssets/Images	0ms	
PowerShell_ISE.exe Information: 0 : 2023-01-18 16:23:56.7474	[PnP.Framework]	[0]	[Information]	File Logo.png retrieved from folder SiteAssets	0ms	
PowerShell_ISE.exe Warning: 0 : 2023-01-18 16:23:58.1419	[List instances]	[16]	[Information]	Skip adding/updating custom actions because the site has "noscript" enabled.	778ms	6b602b44-7850-40e4-82cf-08f75ea0094f
PowerShell_ISE.exe Warning: 0 : 2023-01-18 16:23:59.9393	[List instances]	[16]	[Information]	Skip adding/updating custom actions because the site has "noscript" enabled.	2576ms	6b602b44-7850-40e4-82cf-08f75ea0094
f
PowerShell_ISE.exe Warning: 0 : 2023-01-18 16:26:38.1282	[Web Settings]	[16]	[Information]	Skipping NoCrawl update because the site is configured for noscript.	88ms	6b602b44-7850-40e4-82cf-08f75ea0094f
PowerShell_ISE.exe Warning: 0 : 2023-01-18 16:26:38.1303	[Web Settings]	[16]	[Information]	Skipping master page update because the site is configured for noscript.	90ms	6b602b44-7850-40e4-82cf-08f75ea0094f
PowerShell_ISE.exe Warning: 0 : 2023-01-18 16:26:38.1417	[Web Settings]	[16]	[Information]	Skipping custom master page update because the site is configured for noscript.	102ms	6b602b44-7850-40e4-82cf-08f75ea0094
f
SUCCESS: Deployment of Power Platform Hub complete!
Go to the site: https://axinter.sharepoint.com/sites/Axisepowerplatformhub

![image](https://user-images.githubusercontent.com/95910807/213213731-df7810c7-2be8-4f00-a9d4-a396e85461d5.png)

**Comment by manuelap-msft** [comment]
Check that site navigation is enabled

<img width="705" alt="image" src="https://user-images.githubusercontent.com/8307644/211276137-73412980-d1d8-4620-b1f4-007a7a078f2f.png">

**Comment by xavieralonso** [comment]
Thank you

**Comment by Bea-a** [comment]
> Hi @xavieralonso -
> 
> Can you please check the following:
> 
> * Do you have the rights to create a site collection?
> * Can you check in the SharePoint Admin Center if a site collection with the url `https://axinter.sharepoint.com/sites/powerplatformhub` was created?
>   
>   * If yes, can you run the script again?
>   * If not, can you try creating the site collection manually and run the script again?
> 
> Thanks, Daniel

Could you please confirm what rights are needed to create a site collection? the site already exists but I have an error once it skips creating a site as it already exists.
