### ISSUE TITLE
Flow Inactivity determined by Last Modified Time instead of Last Run Time

### ISSUE THREAD

**Issue by thso77** [microsoft/coe-starter-kit#4616]
In the Governance Components solution, the "Admin | Inactivity notifications v2 (Start Approval for Flows)" Flow starts the inactivity approval process based off the last modified date. This should be changed to be based off the Last Run Time of a Flow. There are many Flows in my organization that run daily, weekly, monthly, or yearly that haven't been modified recently, but are still very much in use. However, these Flows are marked as inactive which causes much confusion amongst our makers.

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately we do not have access to flow usage today and so until that becomes available we can only use the last modified time stamp.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
