### ISSUE TITLE
[CoE Starter Kit - QUESTION] PowerBI report not refreshing data

### ISSUE THREAD

**Issue by SteveDiekeCTVA** [microsoft/coe-starter-kit#4622]
### What is your question?

We had the CoE StarterKit PowerBI reports running on a schedule and updated regularly.  Unfortunately the admin that set it up used their credentials and now is no longer with the company.  Now the connector is no longer updating b/c of the failed authentication and we've tried the steps below to get it working to no avail.  Any suggestions would be appreciated but here's what we've tried:

1. Get a new user with all appropriate licensing per the guidance here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup
2. Used that user to change credentials to the PowerBI data source in the web browser and try a refresh.  The refresh does not error but no new data is reflected in the reports.
3. Downloaded the Power BI .pbix to Power BI Desktop and cleared credentials using the option in PowerBI Desktop.  Then did a local refresh of the data and get the same result as the web refresh.  Refresh does not error and appears to work but data is not updated.

Any suggestions appreciated.

Steve

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

Power BI reports

**Comment by Jenefer-Monroe** [comment]
I would suggest just starting with the PBIT again as the new user. You can publish over the old report that way.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
