### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Patches Upgrade Questions

### ISSUE THREAD

**Issue by Gokul-JB** [microsoft/coe-starter-kit#4623]
### What is your question?

MS suggesting to upgrade the CoE Patches every 3 month once, but I have following question, please clarify it.

1)	How many hours required to upgrade the CoE patches (all CoE component except ALM)
2)	After upgrade, the CoE patches what would happen my early changes of CoE Flows?
    	If I lost my changes every release, then do I need update my logic every release by manually?
3)	Can I have simple steps to upgrade the CoE Patches?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

October 2022

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid I dont quite follow your question. 

The amount of time it takes to upgrade really depends on the amount of testing or customization that you have done, as well as the number of features that you are using. In my tenant, upgrade of all features takes about 2 hours but I dont have any customizations. 

You are correct that you will lose your changes if you follow our upgrade instructions and I'm afraid that is just a product limitation, we cannot coauth our solution with yours. 

So today, these are the best instructions we have for [upgrade](https://learn.microsoft.com/power-platform/guidance/coe/after-setup) and [extend](https://learn.microsoft.com/power-platform/guidance/coe/modify-components).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
