### ISSUE TITLE
[Power Platform communication site template] Top Navigation is not populated

### ISSUE THREAD

**Issue by pradeeppgp** [microsoft/coe-starter-kit#4626]
### Describe your bug, question or feature ask.

Top Navigation is not populated when template is deployed.

Errors:

INFO: Deploying template...
powershell.exe Information: 0 : 2023-01-18 21:55:46.3464        [PnP.Framework] [0]     [Information]   File template.pnp retrieved from folder         0ms
powershell.exe Information: 0 : 2023-01-18 21:55:46.3955        [PnP.Framework] [0]     [Information]   File template.pnp retrieved from folder         0ms
powershell.exe Information: 0 : 2023-01-18 21:55:47.0228        [PnP.Framework] [0]     [Information]   File template.xml retrieved from folder         0ms
powershell.exe Information: 0 : 2023-01-18 21:55:47.1698        [Provisioning]  [27]    [Information]   ProgressDelegate registered     0ms     a8939c8a-2543-4e1c-860c-b53aef9881d5
powershell.exe Information: 0 : 2023-01-18 21:55:47.1718        [Provisioning]  [27]    [Information]   MessagesDelegate registered     1ms     a8939c8a-2543-4e1c-860c-b53aef9881d5
powershell.exe Warning: 0 : 2023-01-18 21:55:54.1827    [List instances]        [27]    [Information]   Skip adding/updating custom actions because the site has "noscript" enabled.    1009ms  a8939c8a-2543-4e1c-860c-b53aef9881d5
powershell.exe Warning: 0 : 2023-01-18 21:55:56.2621    [List instances]        [27]    [Information]   Skip adding/updating custom actions because the site has "noscript" enabled.    3088ms  a8939c8a-2543-4e1c-860c-b53aef9881d5
powershell.exe Warning: 0 : 2023-01-18 21:56:15.8263    [List instances]        [27]    [Information]   Skip adding/updating custom actions because the site has "noscript" enabled.    1132ms  a8939c8a-2543-4e1c-860c-b53aef9881d5
powershell.exe Warning: 0 : 2023-01-18 21:56:18.0104    [List instances]        [27]    [Information]   Skip adding/updating custom actions because the site has "noscript" enabled.    3316ms  a8939c8a-2543-4e1c-860c-b53aef9881d5
powershell.exe Information: 0 : 2023-01-18 21:56:35.1119        [PnP.Framework] [0]     [Information]   File 2931574937.png retrieved from folder SiteAssets/Images     0ms
powershell.exe Information: 0 : 2023-01-18 21:56:37.0426        [PnP.Framework] [0]     [Information]   File CLO17.jpg retrieved from folder SiteAssets/Images  0ms
powershell.exe Information: 0 : 2023-01-18 21:56:39.5147        [PnP.Framework] [0]     [Information]   File Commute.jpg retrieved from folder SiteAssets/Images        0ms
powershell.exe Information: 0 : 2023-01-18 21:56:41.9328        [PnP.Framework] [0]     [Information]   File edd2.svg retrieved from folder SiteAssets/Images   0ms                                                                             powershell.exe Information: 0 : 2023-01-18 21:56:43.6615        [PnP.Framework] [0]     [Information]   File Edu001.jpg retrieved from folder SiteAssets/Images 0ms                                                                             powershell.exe Information: 0 : 2023-01-18 21:56:46.2635        [PnP.Framework] [0]     [Information]   File Edu009.jpg retrieved from folder SiteAssets/Images 0ms                                                                             powershell.exe Information: 0 : 2023-01-18 21:56:48.8274        [PnP.Framework] [0]     [Information]   File Group016.jpg retrieved from folder SiteAssets/Images       0ms                                                                     powershell.exe Information: 0 : 2023-01-18 21:56:51.0293        [PnP.Framework] [0]     [Information]   File Hybrid030.jpg retrieved from folder SiteAssets/Images      0ms
powershell.exe Information: 0 : 2023-01-18 21:56:53.0172        [PnP.Framework] [0]     [Information]   File InclusiveWorkplace.jpg retrieved from folder SiteAssets/Images     0ms
powershell.exe Information: 0 : 2023-01-18 21:56:55.3104        [PnP.Framework] [0]     [Information]   File India017.jpg retrieved from folder SiteAssets/Images       0ms
powershell.exe Information: 0 : 2023-01-18 21:56:57.5975        [PnP.Framework] [0]     [Information]   File LaptopGo.jpg retrieved from folder SiteAssets/Images       0ms
powershell.exe Information: 0 : 2023-01-18 21:56:59.9595        [PnP.Framework] [0]     [Information]   File Lobby003.jpg retrieved from folder SiteAssets/Images       0ms
powershell.exe Information: 0 : 2023-01-18 21:57:02.1019        [PnP.Framework] [0]     [Information]   File Office.jpg retrieved from folder SiteAssets/Images 0ms
powershell.exe Information: 0 : 2023-01-18 21:57:05.8599        [PnP.Framework] [0]     [Information]   File OfficeMeeting1.jpg retrieved from folder SiteAssets/Images 0ms
powershell.exe Information: 0 : 2023-01-18 21:57:10.4141        [PnP.Framework] [0]     [Information]   File OfficePortrait.jpg retrieved from folder SiteAssets/Images 0ms
powershell.exe Information: 0 : 2023-01-18 21:57:12.8575        [PnP.Framework] [0]     [Information]   File OutsideOffice.jpg retrieved from folder SiteAssets/Images  0ms
powershell.exe Information: 0 : 2023-01-18 21:57:15.2984        [PnP.Framework] [0]     [Information]   File Paddington011.jpg retrieved from folder SiteAssets/Images  0ms
powershell.exe Information: 0 : 2023-01-18 21:57:17.4765        [PnP.Framework] [0]     [Information]   File powerapps.png retrieved from folder SiteAssets/Images      0ms
powershell.exe Information: 0 : 2023-01-18 21:57:19.2382        [PnP.Framework] [0]     [Information]   File Productivity1.jpg retrieved from folder SiteAssets/Images  0ms
powershell.exe Information: 0 : 2023-01-18 21:57:21.3097        [PnP.Framework] [0]     [Information]   File Productivity2.jpg retrieved from folder SiteAssets/Images  0ms
powershell.exe Information: 0 : 2023-01-18 21:57:23.3845        [PnP.Framework] [0]     [Information]   File Productivity3.jpg retrieved from folder SiteAssets/Images  0ms
powershell.exe Information: 0 : 2023-01-18 21:57:25.2598        [PnP.Framework] [0]     [Information]   File Redmond1.jpg retrieved from folder SiteAssets/Images       0ms
powershell.exe Information: 0 : 2023-01-18 21:57:27.1959        [PnP.Framework] [0]     [Information]   File Security024.jpg retrieved from folder SiteAssets/Images    0ms
powershell.exe Information: 0 : 2023-01-18 21:57:29.3819        [PnP.Framework] [0]     [Information]   File Slalom.jpg retrieved from folder SiteAssets/Images 0ms
powershell.exe Information: 0 : 2023-01-18 21:57:31.9970        [PnP.Framework] [0]     [Information]   File Team001.jpg retrieved from folder SiteAssets/Images        0ms
powershell.exe Information: 0 : 2023-01-18 21:57:34.2291        [PnP.Framework] [0]     [Information]   File Win15.jpg retrieved from folder SiteAssets/Images  0ms
powershell.exe Information: 0 : 2023-01-18 21:57:36.0370        [PnP.Framework] [0]     [Information]   File Logo.png retrieved from folder SiteAssets  0ms
powershell.exe Warning: 0 : 2023-01-18 21:57:38.3901    [List instances]        [27]    [Information]   Skip adding/updating custom actions because the site has "noscript" enabled.    1159ms  a8939c8a-2543-4e1c-860c-b53aef9881d5
powershell.exe Warning: 0 : 2023-01-18 21:57:41.1811    [List instances]        [27]    [Information]   Skip adding/updating custom actions because the site has "noscript" enabled.    3950ms  a8939c8a-2543-4e1c-860c-b53aef9881d5
powershell.exe Error: 0 : 2023-01-18 21:58:07.3550      [PnP.Framework] [0]     [Error] ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: File Not Found.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()                                                       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)                       at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()                                     --- End of stack trace from previous location where exception was thrown ---                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()                                                       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)                       at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()                              --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
ServerErrorCode: -2147024894
ServerErrorTypeName: System.IO.FileNotFoundException
ServerErrorTraceCorrelationId: 32a28da0-50ab-d000-b7e2-54fe63680a40
ServerErrorValue:
ServerErrorDetails:
.       0ms
powershell.exe Error: 0 : 2023-01-18 21:58:07.6131      [PnP.Framework] [0]     [Error] ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: File Not Found.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
ServerErrorCode: -2147024894
ServerErrorTypeName: System.IO.FileNotFoundException
ServerErrorTraceCorrelationId: 32a28da0-d0bb-d000-b7e2-5ae0b97d1745
ServerErrorValue:
ServerErrorDetails:
.       0ms
powershell.exe Warning: 0 : 2023-01-18 22:00:32.8292    [Web Settings]  [27]    [Information]   Skipping NoCrawl update because the site is configured for noscript.    126ms   a8939c8a-2543-4e1c-860c-b53aef9881d5
powershell.exe Warning: 0 : 2023-01-18 22:00:32.8311    [Web Settings]  [27]    [Information]   Skipping master page update because the site is configured for noscript.        128ms   a8939c8a-2543-4e1c-860c-b53aef9881d5
powershell.exe Warning: 0 : 2023-01-18 22:00:32.8322    [Web Settings]  [27]    [Information]   Skipping custom master page update because the site is configured for noscript. 129ms   a8939c8a-2543-4e1c-860c-b53aef9881d5
SUCCESS: Deployment of Power Platform Hub complete!
Go to the site: https://abc.sharepoint.com/sites/pphub

**Comment by manuelap-msft** [comment]
Check that site navigation is enabled

<img width="705" alt="image" src="https://user-images.githubusercontent.com/8307644/211276137-73412980-d1d8-4620-b1f4-007a7a078f2f.png">

**Comment by pradeeppgp** [comment]
It is supposed to be enabled via template when we install, so its not, when I enable it it doesn't give me all top nav menus. Just edit section. Please see error warning messages I posted.

**Comment by pradeeppgp** [comment]
Not fixed.

**Comment by Laskewitz** [comment]
@pradeeppgp - the errors don't have anything to do with the navigation. If you run the script again on the same site, does it still not show the navigation?

**Comment by pradeeppgp** [comment]
Hello @laskewitz, I fixed the issue by rerunning the scripts, and then enabling the nav menu. Closing this now.
