### ISSUE TITLE
[CoE Starter Kit - BUG] Import failed due to missing dependencies for Center of Excellence - Core Components.

### ISSUE THREAD

**Issue by eranil84** [microsoft/coe-starter-kit#4631]
### Describe the issue

CreatorKitCore (1.0.20221205.1) (57)
[log.txt](https://github.com/microsoft/coe-starter-kit/files/10457826/log.txt)

### Expected Behavior

I tried upgrading the existing COE kit without any luck. Can you please engage Power CAT or relevant team to help upgrade the solutions. We have not upgraded the solutions for ~2 years and hence we are out of sync.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.32

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponents upgrade

### Anything else?

In case there is no fix available due to gap in version installed. What is your recommended for installation? i.e. Shall I create a new environment and install the latest version CoE starter kit and then delete the existing environment where old toolkit is installed. Looking forward for your guidance.

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

At this point, yes it is recommended that you start from a clean environment.

**Comment by eranil84** [comment]
Thanks Jenefer. I will install it in a clean environment and then delete
the existing environment used for CoE starter kit.

**Comment by Jenefer-Monroe** [comment]
Ok, I'll go ahead and close but please return with a new bug if you have issues going forward.
