### ISSUE TITLE
Error when upgrading Dec 2022 Governance module

### ISSUE THREAD

**Issue by kabirstein** [microsoft/coe-starter-kit#4636]
### Describe the issue

When importing the December 2022 CenterofExellenceAuditComponents_3.3_managed.zip I got a pink error message saying : "The imported solution and the existing solution must both be managed for upgrade." However, the audit components (governance) appear to have imported successfully and my Center of Excellence - Governance Components solution IS managed. Please refer to attached JPG.
![COE error and Governance Settings](https://user-images.githubusercontent.com/54034916/213536743-3162bdd1-df36-4977-8689-d3e340f7f275.jpg)

### Expected Behavior

I expected to get a green message saying "Solution "Center of Excellence - Governance Components" imported successfully."

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Governance Components

### Steps To Reproduce

Import December 2022 "CenterofExcellenceAuditComponents_3.3_managed.zip" file 

### Anything else?

No, that's it!

**Comment by manuelap-msft** [comment]
Hello,

we have seen this error message before when an app or flow in the solution was open in edit mode, either by the person importing the solution or by someone else who had access to it. You'll have to check that no one has any components open in edit mode before attempting to upgrade the solution.

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
