### ISSUE TITLE
[CoE Starter Kit - BUG] Orphaned Objects to Clean still messaging manager after flows re-assigned

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#4637]
### Describe the issue

The screenshot attached shows the "Orphaned Objects to Clean" flow still emailing a manager about flows (In this case the CoE kit that my predecessor implemented before but since has been upgraded) that were re-assigned to the service account.

I went into each flow individually a month ago and deleted the old owner from the flows in this screenshot.  There is zero trace of this person being an owner / having permissions to the flow.  The current and only owner is the service account now.

The orphaned object flow is still saying the ex employee is the owner of the flow, when in fact they are not.

Is this flow getting the current owners of flows from a database in the environment?  Is there any way to clear it and update that database with the correct information?  I don't know where this flow is getting the data from, but it is incorrect since this user is no longer the owner or has any permissions to the listed flows in the screenshot.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

December release

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### Anything else?

![image](https://user-images.githubusercontent.com/24686498/213541741-7c7e92be-0851-48c2-970b-8e14bfd47ee6.png)

**Comment by Jenefer-Monroe** [comment]
Where did you go and update the owner? 

We depend on the inventory here to see who the owner is. 
![image](https://user-images.githubusercontent.com/89584709/213801588-3968e686-b98c-45ee-89e6-fbc9037ac117.png)

**Comment by JayCecchine** [comment]
On closer inspection, while I did delete the old owner, the old owners connection references remain on some of these flows.  I am going to clean these up and see if it gets it stop counting them as orphaned flows.

**Comment by JayCecchine** [comment]
This is where I was deleting the old owner, on editting the flow.  It was the only location I was able to remove them.  I am seeing additional conn references (not shown in this screenshot) that are unused and assigned to the previous owner,  Hoping this resolves the issue

![image](https://user-images.githubusercontent.com/24686498/214070229-87024889-f1a8-4bed-a8e8-32d662a0ac6d.png)

**Comment by Jenefer-Monroe** [comment]
Flow ownership is not something we have good programmatic access to unfortunately. And changing ownership here will not mark the flow as modified and hence it will not go through our inventory system and get cleaned up. 

I suggest using the [Set Flow Permissions](https://learn.microsoft.com/power-platform/guidance/coe/core-components#set-flow-permissions) apps to make these ownership changes instead, or resaving the flow so that the inventory will clean it up. 

Hope that makes sense!

**Comment by JayCecchine** [comment]
The Set Flow Permissions tells me "Changing flow ownership is not possible in the product, so changing it here only changes it in the context of your CoE Toolkit. It is stored and used as a property of the CoE Flow table: DerivedOwner"
Is there a way to just edit this flow table directly?
Or for your other solution, is there a way to save the flows via powershell etc or does it have to be done one by one

**Comment by Jenefer-Monroe** [comment]
If you set the ownership in the Set Flow Permissions app, it will set it correctly for us. 
I'm sure you could automate the assign and save some other way, but if you use the app you wont need to.

**Comment by JayCecchine** [comment]
The problem is the set flow owner doesn't work in the app for me, I have the details stated in another ticket.  But basically it errors out whenever I attempt to use it.  Is there a way to access the flow table data directly?  In a raw editable format

**Comment by Jenefer-Monroe** [comment]
I see, yes you can edit flows directly in the table now with some recent awesome product features. Go to the Core Solution > Tables > Flow, and hit the edit button there, that will bring the table into full screen to make editing easier. 
![image](https://user-images.githubusercontent.com/89584709/215073030-5361da9b-367e-4a9d-b59b-cc9d53afe99c.png)

Then you can change what columns are shown with this control
![image](https://user-images.githubusercontent.com/89584709/215073289-e4d91da8-4334-4ea6-b7e7-03efe697003b.png)

And edit inline
![image](https://user-images.githubusercontent.com/89584709/215073623-1e2166e6-f749-4eb9-bdea-d110ed6748cd.png)

I hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by JayCecchine** [comment]
Is there a way to refresh the CoE Inventory table entirely?  Much of the info in the set flow permissions is incorrect.  Was wondering if there was a way to delete it entirely and start fresh.

**Comment by Jenefer-Monroe** [comment]
We do have a concept of a [full inventory run](https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory). I believe that is what you are asking about.

**Comment by JayCecchine** [comment]
Yes it is.  Will running that override the current table and start from scratch?
