### ISSUE TITLE
[CoE Starter Kit - Feature]: Improvement DLP Editor V2 - Inclued more features of the admin center

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#4639]
### Describe the solution you'd like

Hi,

It would be helpful, if the DLP Editor supported the creation of new DLP.
So that it is possible to create a new DLP, add the scope/environment and get the impact analysis.
This would be helpful for starters at PP governance.

Also I am missing some of the UI/UX, Information and features of the admin Center.
Information:
![image](https://user-images.githubusercontent.com/113470539/213595239-a60361c6-cf46-452a-87bc-d0a393131777.png)
UI/UX:
Sorting and filtering possibility
Features:
![image](https://user-images.githubusercontent.com/113470539/213595448-23d0f318-a2dd-4597-b5fd-87425ec576f7.png)
Also some marker that the connector has been configured would be great.

**Comment by manuelap-msft** [comment]
Hello,

thanks for the feedback! the CoE kit is built as an extension to fill certain gaps that aren't yet met by the product to make governance/administration of the platform easier - but it's developed by a very small team, and our primary focus is working on building features that address gaps and not re-building things that already exist in the product (that is developed by a much much much larger team than our two person CoE kit team). Where features exist in the product, we are not planning on replicating them into the CoE kit.

For creating DLP policies, we recommend using PPAC for that as that has all the options - during creation, don't assign it to your environments and instead once created, open the DLP Editor, select your environments there, and then perform the impact analysis from there.

The CoE kit is also built on top of the platform, so it can only make use of what the platform makes available to us - for DLP policies, we use the [Power Platform for Admin](https://learn.microsoft.com/en-us/connectors/powerplatformforadmins/) connector which does not have any action for the more granular endpoint/action configuration options so you can only do those in PPAC.

Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
