### ISSUE TITLE
[CoE Starter Kit - Feature]: Whats Leaking Data Cross Tenant

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#4641]
### Is your feature request related to a problem? Please describe.

The new Tenant Connections with the cross tenant detection is great.
Alowed me to find a bunch of connections, most folk trying gmail and discover they cant use it cos DLP.

But when there are Connections cross tenant to allowed Connectors like SharePoint etc.  
I cant tell if there are any flows or apps that are using that connection or its target.

### Describe the solution you'd like

I'd like a drill down capability for those items to locate the flow  or apps using those Connections especially cross tenant ones.

Id like to see what the Target endpoint is also,  if possible so if a 3rd party SharePoint that someone is writing to or reading from,  what SharePoint is connecting to.

This may be moot, once the cross tenant protection comes out of preview,   however it could be a good report to determine if it is needed for those who have not enabled it when its out of preview.

### Describe alternatives you've considered

Ive tried doing my own report on this editing the PowerBI, but it just whines at me saying fix this,  I know the relationships exist but I cant get it to work, to at least show the flows/apps   not sure it can or does collected the connection end points.

**Comment by Jenefer-Monroe** [comment]
To my knowledge, today we cannot connect a specific connection and an app/flow. Only a connector and an app/flow.
Putting on backlog to investigate though.

**Comment by manuelap-msft** [comment]
Closing out issues where there is no product backlog item to provide us with the information required. We can re-open this if we do get API/programmatic access to the data required.
