### ISSUE TITLE
Issue updating Audit log custom connector

### ISSUE THREAD

**Issue by CDSSYW** [microsoft/coe-starter-kit#4642]
### What is your question?

Hi CoE CAT team,

I followed this setup process 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector

however at this step: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content

**I'm blocked while trying to create new connection, the when I click + connection , there is no authentication process pop-up ..and I'm not able to establish a connection for testing**
![image](https://user-images.githubusercontent.com/117460925/213731839-110a1e02-4da7-4d38-826d-81a6100c4646.png)

Any insights to solve it?
Thanks in advance!

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Hmm might be some cache issue or something in the browser. Can you try to create the connection in this other interface? 
![image](https://user-images.githubusercontent.com/89584709/213762627-e90d19fc-ed75-4094-bd35-3fe1465e0895.png)
![image](https://user-images.githubusercontent.com/89584709/213763342-759d1158-ba42-4bf0-98d1-3a15e8259d17.png)

**Comment by CDSSYW** [comment]
Hi Jenefer,
Through connection portal , my connection isn't authorized and got message: No reply address is registered for the application.
Any clue to fix this ?

**Comment by CDSSYW** [comment]
I'm able to land on the page but does not see the content 
![image](https://user-images.githubusercontent.com/117460925/214838171-24c6e4cf-8445-4638-abf9-d41f104362a6.png)

**Comment by Jenefer-Monroe** [comment]
You will need to perform a search to see results. 

1. For example, search for app launches for a day
![image](https://user-images.githubusercontent.com/89584709/214839856-0c45b366-615c-4905-acd6-0872f46500cf.png)

2. When you hit Search, you will see the search in the run list
![image](https://user-images.githubusercontent.com/89584709/214840197-3f3651f8-c68d-4ed4-9393-4378be591d62.png)

3. Then click completed, when done, can you see some launches? 
![image](https://user-images.githubusercontent.com/89584709/214845656-257dd6f8-faa0-4767-bac1-773b2dd7d191.png)

**Comment by CDSSYW** [comment]
Hi Jennifer, thanks for reply, unfortunately I'm not able to search on the UX, it's all grayed out, does this lacking of particular permission (and what is the required permission to operate searching at audit ) related to authentication to the O365 management API custom connector?

**Comment by Jenefer-Monroe** [comment]
Sorry I should have specified that you should try this as the user whose identity runs the flows. Meaning its their connector running the flows. 
If thats you, then yes, that means you likely did not get the permissions needed. 

Here are the things to check before you can use the audit log connector:

1. Microsoft 365 audit log search must be turned on for the audit log connector to work, and the user identity running the flow must have correct permissions. More information: [Turn audit log search on or off](https://learn.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?preserve-view=true&view=o365-worldwide)
1. A Global Admin is required to configure the Azure AD app registration.
1. Your tenant must have a subscription that supports unified audit logging. More information: [Security & Compliance Center availability for business and enterprise plans](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)

In particular, I think you are missing this part from [Before you search the audit log](https://learn.microsoft.com/microsoft-365/compliance/audit-log-search?preserve-view=true&view=o365-worldwide#before-you-search-the-audit-log)
![image](https://user-images.githubusercontent.com/89584709/214861492-f0a31afe-5dbc-427f-9aa8-86cabded0a6f.png)

**Comment by Jenefer-Monroe** [comment]
The audit logs table that you have circled there is our own audit log table. In it we only store the power apps launch activity; we do not store any other activities. So anyone you grant access to view that table will see the launch information of apps across the tenant. Similarly they can view all the apps across the tenant.

The programmatic audit logs service does not allow filtering, so the way it works is that we have a flow that pulls in all logs, filters to app launches there in flow, and then save to our table (the one you have circled). We ignore all other logs in that flow.

Regarding what you can see when you pull all audit logs (or browse to https://compliance.microsoft.com/auditlogsearch) I'm afraid I cannot advice on how all things are stored or permission that means wrt mailbox auditing. I can just say that the least privaledged that will still allow querying is listed here, from [Before you search the audit log](https://learn.microsoft.com/microsoft-365/compliance/audit-log-search?preserve-view=true&view=o365-worldwide#before-you-search-the-audit-log)
- You have to be assigned the View-Only Audit Logs or Audit Logs role in Exchange Online to search the audit log. 

I hope this is helpful

**Comment by CDSSYW** [comment]
Hi Jenefer,

Thank you, it clarified some doubts, you mentioned 'so the way it works is that we have a flow that pulls in all logs',  could you please refer me which flow from CoE kit pulls all logs?

Another question is, if the org can only grant the audit log access to this service account which deploy the CoE kit,
then I use the service account to setup audit log connector , and use an admin account (normal user account) publish the BI reporting to a shared BI workspace, would it work to show all the telemetry?  Does it require to have the same identity to have access the audit log (to setup audit log connector ) and to publish the BI reporting?

Thanks a lot for your time and reply!

**Comment by Jenefer-Monroe** [comment]
### Flows that reference the log
The flows that do this are the two flows in the Audit Log solution, in particular the child flow list here.
![image](https://user-images.githubusercontent.com/89584709/216482090-584bb662-2a90-4cb3-a7f9-09f5350839b2.png)

It calls the custom connector (the green globe actions) which queries the office audit logs backend, filters to launches and deletes (we really only use the launches), and then proccesses that filtered list. 
![image](https://user-images.githubusercontent.com/89584709/216482522-fcf954e4-26dc-4a10-b96a-2cb1c3a1b852.png)

**Comment by Jenefer-Monroe** [comment]
### Permissions to view the app launches
The same identity that has the permission to the office audit logs needs to run the flow so that the custom connector runs as them. 

Once the flow writes the launch into the dataverse, then anyone that can view the dataverse can see that launch. 

We have these [Security Roles](https://learn.microsoft.com/power-platform/guidance/coe/core-components#security-roles) you can use for that. Giving someone permissions to view the data, and then sharing them the PBI will let them view the apps and all their details including launches, makers, shared with, etc

Hope that all helps
In particular if you grant someone the

**Comment by CDSSYW** [comment]
Hi Jenefer,

Thanks for these clear explanation, though org still feel concerned about what the account can see when pulling all audit logs especially it's including the mailbox activity information, especially apart from using it in CoE kit, it can be viewed from https://compliance.microsoft.com/ and request through powershell..

I'll check with MSFT for the security part and see whether there is more secured way to operate this audit log access, please close this ticket , many thanks!

**Comment by Jenefer-Monroe** [comment]
You are correct, the account will have full access to the compliance.microsoft.com audit logs. As unfortunately that service does not have any ability to permission access roles. If you do find some other answer to that please let me know but we've never found one.

There is good news here, if you cannot get these permissions. 
We are working on integrating with the new product inventory and telemetry features **_Self Service Analytics_** (aka BYODL or Bring your Own Datalake). In this case the power apps and power automate logs run and launch information will be natively gathered and stored near the objects themselves, we wont have to fish in the microsoft audit logs for them anymore. 

We believe we will be able to have a preview of the kit built on this feature in another few months. 
You can explore this ahead of time if you would like
- https://docs.microsoft.com/power-platform/admin/self-service-analytics
- https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by CDSSYW** [comment]
Thank you Jenefer ! I'll check and log the information you provided!
