### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by walkthenose75** [microsoft/coe-starter-kit#4644]
### What is your question?

Are these items available in the CoE dashboard?
- users and what apps and flows they are tied to
- users and what standard and premium connectors on a monthly basis

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

version was installed in March of last year (2022)

### What app or flow are you having the issue with?

CoE Dashboard

**Comment by Jenefer-Monroe** [comment]
Hello. you will likely have trouble upgrading from that version and may need to start from a clean install. Note that we recommend upgrading every 3 months. Please see [Updating the Center of Excellence (CoE) Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/after-setup)

Today we do not have a report that shows the apps a user has access to, but you could build that off the data, we do have the other way in the Power Platform Admin View app, a way to see the users an app has been shared with:
![image](https://user-images.githubusercontent.com/89584709/213820493-6e293e3d-a921-450c-92e6-7c5d035644f4.png)

We also do have have a direct report for the connectors, but it woudl be one more hop in a custom report. 
We do have reports that show connectors per app, and can filter by premium v not for example. 
![image](https://user-images.githubusercontent.com/89584709/213821075-57b696de-59ce-40c9-ad03-b917eca8c83e.png)
![image](https://user-images.githubusercontent.com/89584709/213821174-cffc8e8a-7ff2-4689-b522-f6533abbb4bd.png)


Hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
