### ISSUE TITLE
[CoE Starter Kit - QUESTION] How can we report accessed SharePoint sites in flows?

### ISSUE THREAD

**Issue by DeLuca-Marco** [microsoft/coe-starter-kit#4647]
### What is your question?

We are looking for a solution to report the access via flow to specific SharePoint sites. We need this report in order to monitor access to our confidential sites. Unfortunately it is not enough to iterate all flows and check the used connections, because this does not cover the cases where the Site Url in the connection uses a dynamic value (e.g. a variable or flow parameter).

Is there a way to get an overview of sites accessed via flow including "dynamic value" connection?
Is there a way to access the data table that contains the flow runs and get the information from there?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Production_CoEDashboard_December2022.pbit

**Comment by Jenefer-Monroe** [comment]
We dont currently parse or store this for flows, but it does appear to be in the results from Get Flows as Admin. 

![image](https://user-images.githubusercontent.com/89584709/214015387-94cfcb28-be91-4e97-baae-64242a227496.png)

I've put on our backlog to investigate integration but it will not happen soon due to competing priorities. 
Please let us know if you end up investigating this and find any interesting things to note.

**Comment by DeLuca-Marco** [comment]
Hello Jenefer.
Thank you for the fast answer. Does it also show the site url if the action uses a variable to connect to a SharePoint site instead of a fix site url? Because we were not able to access the dynamic value using the "Get Flow as Admin" action.

This is why we thought of accessing the flow runs instead.

**Comment by Jenefer-Monroe** [comment]
I did not test that, but likely it does not. Other areas (ex http endpoints) do not resolve from variables in the flow definition. 
And we don't have access to the flow runs programmatically I'm afraid.

**Comment by manuelap-msft** [comment]
This is now available in the Power Platform Admin View.
