### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION Power BI report not connecting to Environment 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4650]
### What is your question?

when I try to connect to Production_CoEDashboard_December2022.pbit  from Power BI Desktop Set up 

After I gave my  URL of environment instance and login with my account (Power platform Administrator ).

I am getting below screenshot 
![Power BI Screenshot](https://user-images.githubusercontent.com/29652263/214006726-9f5aea9f-3780-4e2c-a2be-bccf19632510.JPG)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Production_CoEDashboard_December2022

**Comment by Jenefer-Monroe** [comment]
Hello. It seems that you do not have access. 

Are you logged in to PBI as the user that setup the CoE? If not, please do so, or add this other identity to the environment as sysadmin or Power Platform Admin SR

**Comment by pamatihyd** [comment]
Thank you It worked

**Comment by Jenefer-Monroe** [comment]
thanks for letting us know!
