### ISSUE TITLE
[CoE Starter Kit - BUG] PBI Dashboard reports issues on every PBI refresh in Apps table

### ISSUE THREAD

**Issue by miroslav-harlas** [microsoft/coe-starter-kit#4651]
### Describe the issue

We have upgraded from October 2022 to December 2022 version recently. Upgrade of the solution was executed on Thursday January 19th and inventory cloud flows were enabled and executed then.

On Monday January 23rd, we wanted to upgrade our PBI Dashboards. After opening "**Production_CoEDashboard_December2022.pbit**", entering org. url. into and performing very first data refresh, we received 31 errors. We tried to execute the refresh multiple times, the result is the same still.

All errors are related to the table "**Apps**" and to its field  "**admin_notmodifiedsincecreated**". The error message is the same in all 31 cases: "**We cannot convert the value null to type Logical.**"

![image](https://user-images.githubusercontent.com/16306406/214037819-df6b461a-81b8-4378-b52b-dbb5a9f0c2e9.png)

![image](https://user-images.githubusercontent.com/16306406/214038153-420f8db8-b39b-4bdf-a72f-83463c43bf5f.png)

![image](https://user-images.githubusercontent.com/16306406/214037129-c84933a8-baa7-438f-b37d-d29a7cee69c6.png)

Please, share the advice, in ideal state the step-by-step process, how to fix the issue. Thank you in advance for any hint.

Best Regards

Miroslav Harlas

### Expected Behavior

PBI Refresh should be executed without errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Production_CoEDashboard_December2022.pbit

### Steps To Reproduce

We haven't noticed any issue in our non-production upgrade of CoE starter Kit to December 2022 version. We assume that root cause of the issue is a improper/missing/broken values in some of the app records in Dataverse DB, which needs to be fixed.

**Comment by Jenefer-Monroe** [comment]
Strange, I've not seen this before. 
If you go to Transform Data 
![image](https://user-images.githubusercontent.com/89584709/214041108-8e2cc4de-d58b-4143-8355-6816b91e11ac.png)

App > Added Custom, you'll see this field defined. What do you see there? 
![image](https://user-images.githubusercontent.com/89584709/214041034-52e6af43-b666-4530-ab27-4e7c08c87b4a.png)

**Comment by miroslav-harlas** [comment]
Hello,
the column is defined there, I do not think the issue is here.

![image](https://user-images.githubusercontent.com/16306406/214045825-3a0b2991-b681-4bb4-83db-98da4a8ac850.png)

Because we have more than 20k apps in our tenant, while the error is displayed for 31 apps only, therefore I assume it is about mismatch of some values in Dataverse DB for these 31 apps. However, I'm not sure where and how to fix data in Dataverse DB to resolve this issue.

**Comment by Jenefer-Monroe** [comment]
The formula depends on these two fields: admin_appcreatedon and admin_appmodifiedon. Perhaps you have blanks there for some reason. 
![image](https://user-images.githubusercontent.com/89584709/214046354-7b1d8a58-6c46-44e5-9009-107d4ab6275a.png)

Got the Core solution > Tables > PowerApps Apps and click edit to see the data
![image](https://user-images.githubusercontent.com/89584709/214047490-b3002e56-7b21-4150-93f9-3a308b7681e7.png)

Adjust the columns until you have these ones present
![image](https://user-images.githubusercontent.com/89584709/214047331-3850814b-d72d-4326-ab2a-0c73fec6d24b.png)

Filter by Does not contain data
Do you have apps without a created on or modified on date?
![image](https://user-images.githubusercontent.com/89584709/214047980-ff82a074-8720-4759-8d18-1c9246a61f27.png)

**Comment by miroslav-harlas** [comment]
You are right, there is 31 records in **Power Apps Apps** table in total (the same as number of BPI errors), which are missing data in **App Created On** filed, and in other fields as well. However after playing with filters, I have realized that some fields contain value, for example field **App** contains IDs.

![image](https://user-images.githubusercontent.com/16306406/214056755-e378ebe1-1b51-495b-afb8-2937b2af2f73.png)

**Comment by Jenefer-Monroe** [comment]
You can delete these rows from the inventory. Without the environment set they are lost / accidental entries. If they come back later blank again for Environment, please let me know.

**Comment by Jenefer-Monroe** [comment]
This set of flows are intended to keep this type of thing clean, in particular, **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_** would clean these up for you. 

From [Turn on inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows)

- CLEANUP - Admin | Sync Template v3 (Check Deleted)
- CLEANUP - Admin | Sync Template v3 (Connection Status)
- CLEANUP - Admin | Sync Template v3 (Delete Bad Data)
- CLEANUP - Admin | Sync Template v3 (Orphaned Makers)
- CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
- CLEANUP - Admin | Sync Template v3 (PVA Usage)

**Comment by miroslav-harlas** [comment]
OK, thank you for commenting and providing the guidance. I will ensure that **CLEANUP - Admin | Sync Template v3 (Delete Bad Data)** is executed and completed, and I will check if the identified bad records are deleted or not. If bad records are not be deleted after execution of the cleanup flow, I would delete them manually myself. I will let you know the results later when I'm done with these activities.

Thank you very much for your support and for the pieces of advice which you have given me. 👍

**Comment by Jenefer-Monroe** [comment]
These all also had no envt, and another customer hit something similar and helped me to deduce cause. So it will be fixed via 
https://github.com/microsoft/coe-starter-kit/issues/4608 for February

**Comment by miroslav-harlas** [comment]
I have checked that Clean Bad Data was running in our PROD CoE implementation after upgrade. I also realized that corrupted records, which were causing the issue earlier, has been deleted/fix, while new corrupted records occurs at the same. It was happening during Monday - Tuesday that bad records were continuously being crated and deleted. I assume that was because inventory flows as well as this clean-up were being executed at the same time. It was preventing me form doing any PBI refreshes any time I tried it. Therefore I have stopped all inventory as well as clean-up flows, all CoE Cloud Flows are disabled in our tenant as of now now. I performed manual clean-up of bad data and refreshed PBI then.

By the way I have also realized that Clean Bad Data started to run for significantly longer time after upgrade to Dec 2022. providing some screenshots for your interest. We were not proving this cloud flow with per-flow license, however it seems shat we need it now. Another point is that our could be messed up due to #4652, which we would like to resolve as well 😟

![image](https://user-images.githubusercontent.com/16306406/214578469-e3e19d0d-27d9-4c2a-b992-92ceff070cc0.png)

Based on your comments in #4608 I'm concerned that if I turn CoE starter Kit flows on, the issue would occur again and that it may lead to unpredictable behavior of various components of the Stater Kit, incl. scheduled refreshes of PBI dashboards.

My additional questions  are as follows:
1. Do you recommend us to keep CoE Starter Kit flows disabled until we upgrade to Feb 2023, or do think we can start the inventory only?
2. I would like also to understand if there some recommendations for scheduling the inventory & clean-up flows in the big tenants, where flows are running several days and we need to customize schedule? In other words, which flows should NOT run in parallel, and if there is any recommended order how various scheduled flows should be executed? 

Thank you very much in advance for any guidance how to proceed forward.

**Comment by Jenefer-Monroe** [comment]
Delete bad data flow had a change which causes all the flows to get touched recently. So the issues are not related. We had to do this so that the DLP monitoring would work with a recent product change. Once it gets through your flows it will go back to normal rates.

**Comment by Jenefer-Monroe** [comment]
I woudl recommend, since this is impacting you so largely, turning it (and only it) off until it completes. Cancel running instances, trigger it, once its running turn it off, once it completes turn it back on.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
