### ISSUE TITLE
[CoE Starter Kit - BUG] Capacity Alerts

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#4654]
### Describe the issue

Capcity emails are being sent for Developer environments.  Also, The capacity email sends for Near and Over from the same logic branch. 

We received an email for Developer environments Near 80% and for environments that were Over, and the Over was blank which is correct as we are not over on any environments.

However, we should not be getting an email for Over when we are not Over.
![image](https://user-images.githubusercontent.com/93291159/214078328-dc21c6b2-5aaa-4210-ba6d-68899dad8b3d.png)

### Expected Behavior

Email accurately reflect the capacity for environments that count towards capacity, and email should only be sent when there is a capacity issue to address.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

December

### What app or flow are you having the issue with?

Capacity Alert

**Comment by Jenefer-Monroe** [comment]
I believe this is the same issue as https://github.com/microsoft/coe-starter-kit/issues/4238. There was an inline fix in the flow as well as some work in the the clean up flow, **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_**, to fix up the backlog
