### ISSUE TITLE
[Power Platform communication site template] 403 Error when running Invoke-PnPSiteTemplate

### ISSUE THREAD

**Issue by pavankumarkonda** [microsoft/coe-starter-kit#4656]
### Describe your bug, question or feature ask.

Created the new site but getting the 403 error when running the invoke-pnpsitetemplate command.

![image](https://user-images.githubusercontent.com/24679499/214128724-ddc78ac9-eb4c-49ca-8095-e2a0c3c81b90.png)

**Comment by Laskewitz** [comment]
Hi @pavankumarkonda -

This happens when you don't have site collection admin rights to the SP site the template should be applied to. Can you add yourself as a site collection admin to the site and try again?

**Comment by Laskewitz** [comment]
@pavankumarkonda - Can you please check the above?

**Comment by Laskewitz** [comment]
@pavankumarkonda - Closing this due to unresponsivenss.
