### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Apps) - Run Fails - A record with matching key values already exists

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#4658]
### Describe the issue

I keep getting the same error, is this something I should be worried about (not all environments are affected only few)?

![image](https://user-images.githubusercontent.com/54030753/214253432-523d370f-10cb-4ddc-92ad-53c1e4007fa0.png)

![image](https://user-images.githubusercontent.com/54030753/214253673-3328085f-254c-47c8-8921-46f229e12ceb.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

**Comment by Jenefer-Monroe** [comment]
This can happen as a one off if two instances of the flow are running at once for example, but it should not be a repetitive issue, nor frequent. 

Let's first see if the record really does exist. If you click **_Show raw inputs_** on the failing action
![image](https://user-images.githubusercontent.com/89584709/214271176-557a2619-9463-4937-95b4-ab081d8e8272.png)

It will open a pane, copy the app id from the input. 
![image](https://user-images.githubusercontent.com/89584709/214271567-2ca84853-7d13-4a8c-a6d8-c6dc4917e3d5.png)

Go to the Power Platform Admin View app in the Core solution > PowerApps Apps 
Search in the AppIDString column for the app id you got in the previous step. 
![image](https://user-images.githubusercontent.com/89584709/214272192-b6ce191f-c498-4441-a7c9-3f7874871ed3.png)

Is the app present?
Does it appear "normal"? Meaning it has is environment / display name / etc... all its data present.

**Comment by BartoszKaminski1999** [comment]
Hello, seems to be ok

![image](https://user-images.githubusercontent.com/54030753/214533440-37ab7188-c4ba-45f0-bd96-3286a5ceffd2.png)

![image](https://user-images.githubusercontent.com/54030753/214533540-6ae3d9f8-063d-4871-952f-eb1c56fc35a1.png)

Should i fix something there are it should be fixed by your team?

**Comment by Jenefer-Monroe** [comment]
and if you rerun this failure, does it fail again for this same flow? 
![image](https://user-images.githubusercontent.com/89584709/214561910-664e4ada-ac63-49d3-b554-bd794745fbed.png)

**Comment by BartoszKaminski1999** [comment]
On resubmit flow ran successfully. So I have two questions?

![image](https://user-images.githubusercontent.com/54030753/214775905-f4df2ec7-cd49-4ee1-85fc-2eab68b1c785.png)

1. This error does not affect the quality of CoE Dashboards because this application is saved in the Dataverse and does not spoil the picture of various charts?

2. If we are aware of this error, then it should not be serve in the next releases?

**Comment by Jenefer-Monroe** [comment]
It looks like this was the intermittent issue that I referenced to begin with then. 
This can happen as a one off if two instances of the flow are running at once. 
How long did this flow take to run just now? And approx how many apps do you have in your tenant?

**Comment by BartoszKaminski1999** [comment]
Hello,

It took 31 seconds:
![image](https://user-images.githubusercontent.com/54030753/215039948-fa3dc67a-288f-4cc5-8266-9cecb27997a1.png)

We have 726 apps in tenant:
![image](https://user-images.githubusercontent.com/54030753/215040272-328f3f4f-17c5-435d-94f8-07a3c41c02f6.png)

Then I shouldn't worry about such fails because they don't affect our data in CoE?

**Comment by Jenefer-Monroe** [comment]
With a tenant your size my guess is that two instances of the sync flows just started at the same time. So I'm not worried about these now that they passed on rerun

In general, you should always check on failures in the command center, and it looks like you did. YEAH! But if a rerun passes then its ok.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
