### ISSUE TITLE
[ALM Accelerator - FEATURE]: Service connection secrets

### ISSUE THREAD

**Issue by Ballzer0** [microsoft/coe-starter-kit#4659]
### Describe the issue

![image](https://user-images.githubusercontent.com/28560729/214290628-e7f001a2-910b-44ff-b4c9-0b26b831ddad.png)

Looks like our secrets are expiring for our service connections. Its worked for nearly a year at this point. But today, all our service connections had expired secrets.

are they supposed to be updated manually?

### Expected Behavior

expected secrets to automatically rotate

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20221206.2

### Anything else?

ive found a workarond where i manually create new secrets on the app in AAD and add it to the service connection

<img width="290" alt="image" src="https://user-images.githubusercontent.com/28560729/214292554-902ddf4c-94c4-43a8-845b-aac8c3925e6c.png">

this temporarily fixes the issue

**Comment by LukasSchauffele** [comment]
Ran into this issue this week. Would be great if the secrets automatically rotated or an easy way to create and update secrets in the admin app.

**Comment by mikefactorial** [comment]
Closing this out as it's not something we plan to implement. There are solutions to this available online but are out of scope for the ALM Accelerator and would need to be implemented by individual organizations who need it. (e.g. https://koosg.medium.com/implement-automatic-key-rotation-on-azure-devops-service-connections-13804b92157c)
