### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can we run CoE Starter Kit without permanent access for account? 

### ISSUE THREAD

**Issue by autoDude** [microsoft/coe-starter-kit#4664]
### What is your question?

Hi guys,

I would like to mention an issue about the CoE starter kit or about a wrong working DLPs. 

But we are at the very beginning of Power Platform governance. So even the implementation of the CoE starter kit opens internal discussions. We want to follow best practices and need for the installation of it a service account with specific user permissions (activated MFA, MaxAgeMultiFactor = Until-Revoked, PIM disabled). 
Is this the only option to install it? Our security underlines that the mentioned permissions do not follow their best practices in terms of user management. So we have two best practices of Microsoft which do not fit together. 

**Any idea how continue with a trade-off? Or can you describe why the described way of installation does not result in security problems?**

Thanks

### What solution are you experiencing the issue with?

Governance

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately that is the requirements to use the kit. The reason being that the account used to run the kit will run at various times, and if you are using PIM or something like that, you might not have permissions or license when needed, and then your inventory will be off. 
For example, you go to fetch the environments and aren't pp admin at the time, you wont get all the environments.

**Comment by autoDude** [comment]
Thanks. We understand that. What about the security point of view? Is it correct that in general the required specifications of the service account contradict user management best practices?

**Comment by manuelap-msft** [comment]
Yes, it's correct that generally our Microsoft best practise is to use PIM. In the case of the CoE kit implementation, we are bound by technical limitations that don't allow for a different implementation - the CoE kit uses cloud flows that use connectors (e.g. Power Apps for Admin, Power Platform for Admin) to get information about your tenant to build a holistic overview of your inventory and usage - the cloud flows run on a schedule and based on the size of your tenant can take hours to run, some kick off other flows - it's therefore unpredictable how long such an inventory run will take during the day and we thus can't support time-bound access. The connectors also only support authentication with a user or service account, and not a managed identity or service principle so we don't have another auth type available to us either.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
