### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION: What is the concept of Unique Users of a powerapp application

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#4665]
### What is your question?

In COE dashboard when we export the data for the apps shared with Everyone (Tenant), we see a column Unique Users, want to understand what is the difference between Shared Users and Unique users. Because we see for an app the shared users is 0 but the unique users is 3, please help us providing the details of unique users concept in PowerApps COE.

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
Hello,

Shared Users = individual users an app is shared with (e.g. if you share an app with Megan Bowen)
Shared Groups = number of groups an app is shared with (e.g. if you share an app with My Team Group)
Unique Users = if the [Audit Log solution](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog) is set up, this shows the unique users that have launched the app. These could be users the app has been shared with through a group.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
