### ISSUE TITLE
[CoE Starter Kit - Maker-Environment Request App shows The Value 'Environment Requests" cannot be converted to a number.

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4666]
### What is your question?

Recently Installed December release of CoE Starter Kit 

When I share the app user and user opened the App . 

User is getting two error messages

"The Value 'Environment Requests" cannot be converted to a number.
The Value  "Data Policy Change Requests" cannot be converted to number 

Is this issue can be fixed by configuring something ?

![Env Req App](https://user-images.githubusercontent.com/29652263/214579911-ed902b67-3673-4fa1-8a0e-f0816a037e3e.JPG)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Maker-Environment Req App

**Comment by pamatihyd** [comment]
can I have any update on this ?

**Comment by Jenefer-Monroe** [comment]
Hello, as a reminder, the CoE Starter Kit is an unsupported set of templates. We do strive to assist our users with best efforts but do not have an SLA for response. 

Unfortunately the dev that owns this area is on vacation, she will look in to this on her return. 

Thank you for your patience

**Comment by mp1295** [comment]
I have also this error. Could you please give us advice how to resolve this? 
Br,

**Comment by clusterb0mb** [comment]
We have similar errors:

Invalid operation: division by zero.
The value 'Environment Requests' cannot be converted to a number.
The value 'Data Policy Change Requests' cannot be converted to a number.
The value 'Environment Requests' cannot be converted to a number.
The value 'Data Policy Change Requests' cannot be converted to a number.
Invalid operation: division by zero.

**Comment by ashlega** [comment]
As a workaround, this might help for now: https://www.itaintboring.com/power-platform/deploying-coe-starter-kit-in-march-2023/
