### ISSUE TITLE
[CoE Starter Kit - QUESTION] Welcome Email Customizations

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#4667]
### What is your question?

Hi, 

We made customizations for our Welcome Email through the Admin Command Center. However, when we're looking at the preview, we still see "(dynamic content here)" at the end of the email. Could we please remove this dynamic content? 
<img width="839" alt="image" src="https://user-images.githubusercontent.com/100535041/214611008-560720f8-b26b-4dea-93c8-b51c9555ce57.png">

Also, it's strange that we have the importance set to "Normal" but the email states" Importance: Low" 

Please advise. 

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

Welcome Email

**Comment by Jenefer-Monroe** [comment]
We've revamped the Email Customizations for the Feb release. Here is that that looks like now: 

![image](https://user-images.githubusercontent.com/89584709/214733516-6f05c4d1-69cc-44db-a7ad-13444101870f.png)

For the dynamic content, unfortunately we cannot have both fixed and dynamic content in the mails in a way that is customizable. In the case of the welcome mail, the thing that comes after the end of the mail is the hyperlink to our community URL 

![image](https://user-images.githubusercontent.com/89584709/214733805-7217c497-0c9c-43ba-9f88-9449ca497fff.png)
