### ISSUE TITLE
[Product BUG]:  Maker Assessment starter data install technique relies on XLO Connector which is blocked in GCC High

### ISSUE THREAD

**Issue by cdt2021** [microsoft/coe-starter-kit#467]
Describe the bug

Component (please tell us which flow or app you are experiencing issues with):

Solution - Nurture
Version - 1.51
App or Flow - Import
To Reproduce

I am working in a GCC High environment and it appears the Nurture component requires Excel Online (Business). Can you provide a previous version that doesn't require Excel Online (Business)? The documentation I've found states the connector is not available. If I'm incorrect please tell me how to implement the component. Installation of the COE in GCC High - Nurture Component

**Comment by JeneferM-MSFT** [comment]
Hello. To our knowledge this works in GCC High, we have a partner that installs there for us. Did you try or just blocked from the documentation?

**Comment by cdt2021** [comment]
I tried to install the solution and It asked that I install Excel Online (Business) and it's not listed as a connector in my list.  In addition this is the link that says it's not available in GCC High.  Can you confirm?  Maybe I'm wrong?  https://docs.microsoft.com/en-us/connectors/excelonlinebusiness/.  Did your partner install a previous version that doesn't require Excel Online (Business)?

**Comment by cdt2021** [comment]
This is the only Excel I have in my GCCHigh Environment.   However, in our commercial environment I see the Online Business version.

![image](https://user-images.githubusercontent.com/80719563/119374776-9c0e8d80-bc7f-11eb-80ee-b08bf2ef25da.png)

**Comment by cdt2021** [comment]
Can you provide me with the latest version that doesn't use the online business version of excel or where to go and get archived versions of the toolkit?

**Comment by JeneferM-MSFT** [comment]
I'm afraid we cannot do back support, but we will reach out to the product team to get this connector supported.

**Comment by cdt2021** [comment]
Yes.  This is blocking me from installing the solution.  However, I had an older solution (1.27) that I was able to install.  However, it's far behind the current version (1.51).  I'm more than happy to use the work around so that I have the latest copy.  Please advise.

**Comment by JeneferM-MSFT** [comment]
Sorry no I meant that you if you were able to install you could do the set up that flow is intended to do without the flow. 
Unfortunately you will be blocked from install until the product issue is fixed. Will let you know what we hear.

**Comment by JeneferM-MSFT** [comment]
Product team has acknowledged the issue.

**Comment by cdt2021** [comment]
Thanks!

**Comment by JeneferM-MSFT** [comment]
We have fixed this for July by moving away from the cloud flow install technique to dataflows which do not prompt for connectors on install. 

Attached here is the backup solution which still uses cloud flows in the event that data flows dont work for some folks. 
[Maker Journey Starter Data Backup Solution.zip](https://github.com/microsoft/coe-starter-kit/files/6717040/Maker.Journey.Starter.Data.Backup.Solution.zip)

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
