### ISSUE TITLE
[CoE Starter Kit - BUG] Dec release CoE missing dependency (Creator Kit)

### ISSUE THREAD

**Issue by EnsilaC** [microsoft/coe-starter-kit#4670]
### Describe the issue

hi, 
We tried to update our COE environment with the latest COE Starter Kit December 2022. 
We are in the import step, but during the import of all the files/folders of the kit. Attached the files we had in the kit: 
<img width="770" alt="MicrosoftTeams-image (29)" src="https://user-images.githubusercontent.com/123632961/214813906-cc029b96-7d37-4c67-8d65-8339e79be378.png">
 
we had errors as attached: 
- CenterofExcellenceCoreComponents_4_2_managed, our current version 3.56
<img width="447" alt="MicrosoftTeams-image (27)" src="https://user-images.githubusercontent.com/123632961/214813127-11991966-c6f5-4ccb-afc0-b4cb192b9c9b.png">
<img width="586" alt="MicrosoftTeams-image (28)" src="https://user-images.githubusercontent.com/123632961/214813130-3b491291-91ba-4be2-9dce-e8d6ac2f03f9.png">
[log.txt](https://github.com/microsoft/coe-starter-kit/files/10508287/log.txt)

- Tool ICons  with the error attached 
<img width="475" alt="MicrosoftTeams-image (30)" src="https://user-images.githubusercontent.com/123632961/214814296-9326e62f-6f45-4513-b3e9-a7d81e821d51.png">
Also all the other files in the screenshot which are not zip files couldnt be imported. With same error message as in Tool Icons above

Please let us know your advice 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

COE Starter Kit

**Comment by Jenefer-Monroe** [comment]
As of Dec release, the kit has a dependency on another solution that needs installed first, the Creator Kit. 

Please see [Import Creator Kit](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#import-creator-kit)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
