### ISSUE TITLE
[CoE Starter Kit - Environment Variable] Problems between DLPs and Graph URL Environment Variable

### ISSUE THREAD

**Issue by javiercheke** [microsoft/coe-starter-kit#4672]
### Describe the issue

After upgrading CoE to the December version we are having a problem with DLPs and flows using Http with Azure AD, the Graph URL environment variable is not recognized. We don't know why this happens, if we modify the flow by typing the url directly in the step, the DLP errors do not appear.

I opened the ticket in Microsoft but the answer was that being related to the CoE to open the incident here.

Could you help me?

The error
![image](https://user-images.githubusercontent.com/7656046/214872633-398a60f5-627d-4234-ab69-d4eddbba6cfa.png)

The environment variable
![image](https://user-images.githubusercontent.com/7656046/214873159-9d597ba7-b07c-4b84-81c9-14ab3abb1e30.png)

The DLP
![image](https://user-images.githubusercontent.com/7656046/214873426-5e57386c-b714-44a9-b444-8c690b87da44.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Helper - Maker Check

**Comment by Jenefer-Monroe** [comment]
I did also happen to notice that your env var value is missing the ending slash. 
That wont impact the issue you are describing (see Manuela's note) but it will impact your ability to use the kit. 
Please see [Gather environment variable values](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values)

![image](https://user-images.githubusercontent.com/89584709/214887806-34f2e715-ab2c-434a-b7a3-412a09d3a9e0.png)

**Comment by manuelap-msft** [comment]
Closing out as no further action from the toolkit team required.
