### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE -CANNOT UPGRADE OR UPDATE CoE - The imported solution and the existing solution must both be managed for upgrade

### ISSUE THREAD

**Issue by LanMorton** [microsoft/coe-starter-kit#4675]
### Describe the issue

We were unable to update our CoE anyway. We hit the error ''
The imported solution and the existing solution must both be managed for upgrade." everytime we tried to to import the latest CoE 4.2.
Please help us, advise what we must do..
Thank you very much in advance.

Kind regards, 
Lan Morton
Lan.tranmorton@wiltshire.gov.uk

### Expected Behavior

update/upgrade CoE4.2 from Coe V.3.39

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

CoE platform. cannot upgrade

### Steps To Reproduce

In Coe environment 
https://org74d6b291.crm11.dynamics.com/tools/solution

### Anything else?

please help

**Comment by manuelap-msft** [comment]
We have seen this error before, and it typically happened when someone had an app or flow that's in the solution open in edit mode. Can you check with everyone who has edit access to the solution and ask them to close any browser sessions that they may have open editing an app or flow and try again?

**Comment by LanMorton** [comment]
Hi Manuela,
Thank you very much for your message.
We did follow you advice to double check most flows and refreshed connections; all look good and shows no error. Anyway, we still hit the same error when importing the Core Components solution; although we could import the other components without any trouble. Hope you can advise us what we should do to get it updated please.

***@***.***


Kind regards,
Lan Tran Morton
Senior Dev Operations Engineer (M365)

**Comment by Jenefer-Monroe** [comment]
There should be an option to download specifics about the error. If you do that and open the XL file, as I recall it tells you what object is blocking upgrade. And perhaps even who has it open, but I cant recall that part.

**Comment by manuelap-msft** [comment]
Based on the error message in the log you shared, we've seen this error before and here's a thread on how someone else solved it:
https://github.com/microsoft/coe-starter-kit/issues/4375#issuecomment-1345554161

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by LanMorton** [comment]
Hi,
Please reopen this re      quest as we are unable to install the Core Components Solution (7/12/2022). It failed every time we tried to update it for our CoE. Although we have tried various ways for many hours (investigated and learned other's experiences through the Developer Community); it failed to import this solution anyway; the same error (see below) occurred every time we try to update it:
***@***.***

I believe the issue is related to two different versions of the core components are existing in our CoE (V3.39 and V3.31). We are expecting your advice and suggest us a relevant way for resolving our request/issue. Hope you can support us soon please.

Thank you very much in advance.
Kind regards,
Lan Tran Morton
Senior Dev Operations Engineer (M365)
***@***.***

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. 

The two core versions you reference are a year old and 6 months old, while we recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades)

If all you are using us for is inventory, with or without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help you get started with migrating the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Others have overcome it with a classic overwrite upgrade, ill paste how to do those below. 

Sorry we cannot be of more assistance here.

**Comment by LanMorton** [comment]
Hi Jenefer,
Thank you very much for your feedback and advice.
We've followed the requirements in the page installing updates<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fpower-platform%2Fguidance%2Fcoe%2Fafter-setup%23installing-upgrades&data=05%7C01%7CLan.tranmorton%40wiltshire.gov.uk%7Cd875824a355a42e5b75f08db090679dc%7C5546e75e3be14813b0ff26651ea2fe19%7C0%7C0%7C638113695636824589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QzS3zoMyRbBTtn9lv8ES4t8cKMQZi%2Bg1cLqmSESAQl0%3D&reserved=0> to ensure our CoE is clean, no unmanaged layers, no customised features. Most flows and apps still run well, except it's running with the old Coe template.
Specifically, the Admin | Sync Template v3 run well, succeeded most times. However, importing the Core Components 4.2 failled anyway.
We couldn't find any unmanaged flows or solution laywers within our CoE, but still hit the same error as I sent you in my last email.

Kind regards,
Lan Tran Morton
Senior Dev Operations Engineer (M365)
