### ISSUE TITLE
[CoE Starter Kit - BUG] Flow Trigger field has no data

### ISSUE THREAD

**Issue by mleblanc600** [microsoft/coe-starter-kit#4678]
### Describe the issue

When I go to the flow menu and it list all of my flows. I add the Flow trigger but that field has no data in it. How do I get data in that field.

### Expected Behavior

Have data in the Flow trigger field

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Not sure

### Steps To Reproduce

Go to Flow
Add field Flow Trigger and data is blank

### Anything else?

![image](https://user-images.githubusercontent.com/123767023/215167430-92e47661-1fff-4c8a-ac44-c0052b36816a.png)

**Comment by Jenefer-Monroe** [comment]
Hello, this is populated by the **_Admin | Sync Template v3 (Flow Action Details)_** flow which is an optional flow as it is pretty API intensive given the number of times its called. 

Please see [Turn on inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows)

**Comment by mleblanc600** [comment]
Hi Jenefer,

Thanks for your reply. It's weird because I remember seeing that workflow when I set it up but I cannot find it now in my lists of flows? Do you have some directions?

Thanks.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
