### ISSUE TITLE
[ALM Accelerator - QUESTION] Can't commit solution

### ISSUE THREAD

**Issue by diego-coke** [microsoft/coe-starter-kit#4679]
Hi guys,

I just deployed the ALM accelerator and I'm running some tests, trying to commit one solution using the export-to-git pipeline is throwing this error at the publish customizations step:

##[error]error: 1
##[error]failed: Connected to... Microsoft PowerPlatform CLI
Version: 1.21.5+ge089c16

Error: Failed to connect to Dataverse
    Failed to connect to Dataverse
        One or more errors occurred.
            Exception - Fault While initializing client - RefreshInstanceDetails
                Exception - Failed to lookup current organization data
                    The HTTP request was forbidden with client authentication scheme 'Anonymous'.
                        The remote server returned an error: (403) Forbidden.

Any idea?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Dec 2022

**Comment by diego-coke** [comment]
nvm i figured out what the issue was

**Comment by POWR-Pen** [comment]
I am getting the same issue, how did you fix this please?
