### ISSUE TITLE
[ALM Accelerator - BUG]: Stuck on Getting Solution Dependencies

### ISSUE THREAD

**Issue by diego-coke** [microsoft/coe-starter-kit#4682]
### Describe the issue

When trying to configure deployment settings, it will get stuck in "GETTING SOLUTION DEPENDENCIES...". 

![image](https://user-images.githubusercontent.com/83843163/215219301-a08c37a7-9a69-4aac-8127-d99921aa86e7.png)

It's just stuck in this screen and won't show the actual dependencies.

This was not a problem in previous versions. Just after I updated to the latest version of the solution.

### Expected Behavior

I should be able to configure the dependencies for the environments where the app will be deployed.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20221206.2

### Steps To Reproduce

1. Select a solution and a profile
2. Click on "Configure Deployment Settings"

### Anything else?

The funny part is that this was working and suddenly it got broken without any change.

**Comment by mikefactorial** [comment]
@diego-coke a couple of things to check. 
1. Are there any failures being reported in the Flows that get the solution dependencies. These are the flows that start with "GetSolution..." 
2. Possibly a service interruption since it stopped working all of a sudden as you mentioned.

**Comment by diego-coke** [comment]
Hi Mike,

It is still not working, if I tried to use the admin account that was used to deploy the solution the flows are triggering and everything is working as expected, with my user account the flow are not even getting triggered.

I'll test with another user to see what the behavior is and let you know.

**Comment by tomjosbin** [comment]
Hey @diego-coke ,

We are having the same issue and when we try to access the 'Configure Deployment Settings' directly from the home screen (rather that after clicking 'Commit Solution' button) it loads faster.

Also have you checked whether your user is allowed to have access to 'Deployment Settings' in the 'ALM Accelerator for Power Platform Administration' Model Driven app.

![image](https://user-images.githubusercontent.com/33513504/221535831-43d0f6de-4545-4bfd-85b7-c7dbbf9e599d.png)

**Comment by mikefactorial** [comment]
Thanks for the additional context @tomjosbin. @diego-coke is this still an issue on your end?

**Comment by sefa-phaag** [comment]
I am having this same version in 1.0.20230206.1. None of the GetSolutionXXX flows are even being called. Looking in the network tab of the browser developer tools, all requests returned with a 200 and none are pending, but the application is still stuck at "Getting Solution Dependencies" It doesn't work either from the Prepare step of Commit Solution or by clicking Configure Deployment Settings.

**Comment by mikefactorial** [comment]
@sefa-phaag thanks for adding more details. This is a bit of a difficult issue to troubleshoot. We haven't seen this behavior with any of the solutions we use the ALM Accelerator with internally, including the CoE Starter Kit solutions, Creator Kit and Automation Kit as well as the ALM Accelerator. Makes me wonder if there's a permissions issue here when the accelerator is trying to read information about the solution(s) in the development environment or in one of the downstream environments. 

A couple of things to check
1. Maker has permissions to read things like flows / connections / etc. in the downstream and development environments (i.e. has Maker permissions in those environments).
2. Does this happen for all solutions or just some? Anything noteable about the solutions that work vs don't work?
3. We have an open issue related to tenants that don't have Sharepoint e.g. demo Power Apps environments without M365 licenses.

**Comment by sefa-phaag** [comment]
Yeah, actually, I just reopened the app and it worked this time. I had hard refreshed the page like 9 times previously with no change, so I have no idea why it would suddenly start working again.

1. I don't think it was a permissions issue, since I'm an admin in every system at multiple levels, plus I installed the solutions, created all the connections and own all the flows - all of which I did over the past two days.
2. When it wasn't working, it was for all solutions.
3. We have SharePoint

The only thing I noticed is that in addition to the loading graphic in the middle of the page, it is now also showing the default Power Apps dots at the top of the screen before it fully loads the screen. It wasn't doing that when it got stuck. It's far too easy to accidentally swallow an error in Power Apps in my opinion, so who knows? Anyways, I appreciate your response.

**Comment by mikefactorial** [comment]
Thanks @sefa-phaag for the update. Agree with you on the issue with Power Apps swallowing errors. Definitely makes it difficult to troubleshoot and I've also noticed that things get cached for a long time in the browser and takes too long to see the latest changes in an app. I'm going to close this issue out for now. If it pops up again let us know.
