### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power App / Cloud Flow "Sorry, there has been a disconnect" message

### ISSUE THREAD

**Issue by MantasSal** [microsoft/coe-starter-kit#4684]
### What is your question?

Hello,

when selecting any Power App / Cloud Flow and navigating to Drill Through - Cloud Flow Details I can see a message "Sorry, there has been a disconnect" message.
What info should this window populate? How to fix it?

![image](https://user-images.githubusercontent.com/114066875/215472980-a9ee3cb3-76da-4ab9-a6f3-7d43674d8559.png)

### What solution are you experiencing the issue with?

Core

**Comment by MantasSal** [comment]
Thanks, I have run through setup.
I get this error, should I ignore it?
![image](https://user-images.githubusercontent.com/114066875/215769098-1973d3b0-e365-42ae-b2b3-97c666d0dbe5.png)

**Comment by Jenefer-Monroe** [comment]
A couple things:
1. You need to browse to this page from the apps page (for the apps for for example). Right click to get to this ux. Have ou done that? 
![image](https://user-images.githubusercontent.com/89584709/215796056-852e647c-c509-4e40-b0a7-28b1bcdc0dad.png)

2. What version of Core are you on? There was a bug a few months ago around envt access with using the incorrect string
![image](https://user-images.githubusercontent.com/89584709/215796296-95ade325-5704-4c3b-a8af-0b2e79efbcb6.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by mdodwani** [comment]
@Jenefer-Monroe I am also l getting this error message I have installed core 4.48.2 any idea what will be the fixed.
Account using is the owner of the App (Admin - access this app).
I will really appreciate if you can help on this.
