### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION core components and Nature components 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4687]
### What is your question?

Hi, '

We are planning to install   
1. CoE Core Components into our Prod  
2. Once core components installed, we are planning to go with Nurture Components .

Question is ,  Is it okay to install Nuture Components without installing Governance components(This will install later once our requirements ready) ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

**Comment by manuelap-msft** [comment]
Hello,

yes, Core components is the "foundation" that Governance and Nurture solutions built on but the Nurture solution does not depend on Governance so you can install Core first and then Nurture, and Governance at a later point.

**Comment by pamatihyd** [comment]
Thank you so much for response
