### ISSUE TITLE
[CoE Starter Kit - QUESTION] Courses / lessons for CoE

### ISSUE THREAD

**Issue by MantasSal** [microsoft/coe-starter-kit#4688]
### What is your question?

Hello,

are there any courses / lessons available for CoE? If not, what Microsoft (or other) courses would you recommend about how to manage Power Platform?

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
Hello,

the CoE Starter Kit is a reference implementation of how to implement a tooling approach to manage Power Platform, but it's not part of the Microsoft Power Platform product itself. Therefore, there are no courses / lessons available for the kit specificially.

Here's some resources that may help you:
- https://learn.microsoft.com/en-us/training/paths/best-practices-environments/ 
- https://learn.microsoft.com/en-us/training/browse/?products=power-platform&roles=administrator&expanded=power-platform
- https://learn.microsoft.com/en-us/power-platform/guidance/adoption/methodology
- https://adoption.microsoft.com/powerplatform
- Many of our customers also work with partners (https://powerapps.microsoft.com/en-au/find-a-partner/) who have CoE and Power Platform Admin related offers https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&exp=ubp8&search=coe&page=1
- If you have a Microsoft Account Team you're working with, it's worth reaching out to them to see if there's any services available to you through them.

Hope that helps,
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
