### ISSUE TITLE
[CoE Starter Kit - BUG]: Installation of the COE in GCC High - Innovation Backlog - PowerAutomate Flow Error

### ISSUE THREAD

**Issue by cdt2021** [microsoft/coe-starter-kit#469]
Describe the bug
Error when running the "Update Software Tools" flow. Details below.

Component

Solution - Center of Excellence - Innovation Backlog
Version - 1.30]
App or Flow - This is a flow
To Reproduce
I've installed the Center of Excellence - Innovation Backlog in our GCC High Tenant. When I run the "Update Software Tools" flow I get the following error:

Action 'Mark_Common_-_ODB' failed

The 'inputs.parameters' of workflow operation 'Mark_Common_-_ODB' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'

Is there something I can do to change the value of the recordIdto be nullable?

**Comment by JeneferM-MSFT** [comment]
Hello. Few questions:
Can you please share a screenshot of the failure to help us have context here? 
Does this repro consistantly? ie have ave you tried running multiple times?

**Comment by cdt2021** [comment]
See attached Screenshot of the error.  In addition, I've run this numerous times and it continues to fail.  This is in the GCCHigh environment.


***@***.***D75086.A895FA80]



***@***.***D75086.A895FA80]

**Comment by cdt2021** [comment]
![image](https://user-images.githubusercontent.com/80719563/119369645-08868e00-bc7a-11eb-8882-01cac4d495f6.png)

**Comment by cdt2021** [comment]
![image](https://user-images.githubusercontent.com/80719563/119369732-1dfbb800-bc7a-11eb-92ac-6c9c23b8c69a.png)

**Comment by JeneferM-MSFT** [comment]
We do assume on all of these that the connector is present, perhaps your tenant doesnt have this connector. 
Can you please show me what value came from the previous call? Click the "click to download" and let me know what is returned. 
![image](https://user-images.githubusercontent.com/62659043/119551642-178f3e00-bd57-11eb-9648-50bbcce33e9b.png)

**Comment by JeneferM-MSFT** [comment]
Got it, yep you don't have this connector for whatever reason. I have local fixed the flow to continue in the event these calls fail. 

Note that you got through most of the flow though, these steps are just marking up what we guess to be "commonly used" connectors. You can use the admin app to mark your own guesses at commonly used as well. 

So while we will fix this in the next release, you are not blocked from proceeding with using the app. 

Thanks for using CoE

**Comment by cdt2021** [comment]
Thank you.  What I did was move those two steps to the end of the flow because they were about 3 steps earlier.  All of the other steps worked.  Now that I know this doesn't block me from using the component I feel confident something wasn't missed.  I'm still learning the toolkit and I completed the rest of the items in the instructions and I didn't have any issues.  Thanks for the support.

**Comment by cdt2021** [comment]
I'll keep an eye out for the next release.

**Comment by manuelap-msft** [comment]
The release went live just now, and you can download the latest solutions via aka.ms/coestarterkitdownload

**Comment by cdt2021** [comment]
I'm still getting the same error.   This is the version of the Innovation Backlog that I'm using.

CenterofExcellenceInnovationBacklog_1_31_managed

**Comment by JeneferM-MSFT** [comment]
Can you please validate that you removed unmanaged layers before you did the upgrade? If you do not remove these you will not see changes from us. 
Please see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

When I say you can do this manually I had thought we added a screen for that in the admin pages, but we didnt. 
You can manually edit rows in the table though to mark them as favorite using your favorite Dataverse editing technique (I like the Excel addin)
![image](https://user-images.githubusercontent.com/62659043/121020027-30d3b980-c75d-11eb-9f5b-e46ba9f219da.png)

**Comment by cdt2021** [comment]
Thanks. That worked.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JeneferM-MSFT** [comment]
Wonderful news. Thanks for validating! And for using our CoE
