### ISSUE TITLE
[CoE Starter Kit - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by rsantos00** [microsoft/coe-starter-kit#4690]
### Is your feature request related to a problem? Please describe.

Feedback from a customer regarding the different menus in the Dev Compliance Center. They would like to have pass a parameter to URL to open up the creation of an environment side bar.

![image](https://user-images.githubusercontent.com/3724826/215782663-06d7fba8-931c-4db5-9fab-9db42bc55cd7.png)

### Describe the solution you'd like

When I open the App the Side Bar to create an environment will be opened

**Comment by manuelap-msft** [comment]
Hello,

could you please clarify the ask a bit more? The side bar is to provide support details (such as business justification) and not create an environment. Would they like to create an environment from this app? 

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Closing out. Deep Dive to a specific app/flow is available via a param.
