### ISSUE TITLE
[CoE Starter Kit - QUESTION] New 365 group asking to be made for Dec 2022 release, I have concerns about spam to my users

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#4693]
### What is your question?

Do I have to create a new Microsoft 365 Group for this?  This appeared after installing the Dec 2022 update

If so, what flows are going to be utilizing it, what kind of communication is going to be sent to the users?  I have a large org ~60000 Users.  The problem I had with some of the flows in the CoE kit when installing it a few months ago, was that it was spamming our user base with several emails a day due to certain flows not being modified in x amount of days etc.  I received blowback from this and many angry emails.  I would rather not run into this again.  That being said, I need to know exactly what correspondance will be made with this user group, how its going to be populated etc.  Thank you!

![image](https://user-images.githubusercontent.com/24686498/215814440-68bda609-b1ec-46d7-86d4-eaba94977841.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Dec 2022

**Comment by Jenefer-Monroe** [comment]
We are not using it yet. The intention is to do auto-sharing for you from the Setup Wizard, but the work was not ready for release in Dec. 
In the next release you will see it in SetupWizard>ShareApps flow
![image](https://user-images.githubusercontent.com/89584709/210396436-0454456f-e409-4dfe-bc14-1623125875da.png)

Which will be called from the Setup Wizard App
![image](https://user-images.githubusercontent.com/89584709/210396746-e89e8022-e75d-490c-9a57-fda65cf078ca.png)

Hope that is clear! Happy new year!

**Comment by JayCecchine** [comment]
Ah ok, is it going to populate the group from the makers group?

**Comment by Jenefer-Monroe** [comment]
We havent added that flow yet. WE plan to make this generalized area a little better in the next few months but yes you can imagine that we will have another flow similar to the one we use for makers, to add users to this new group.

**Comment by JayCecchine** [comment]
Understood, thanks Jenefer, we can close this out.

**Comment by Jenefer-Monroe** [comment]
You bet, thank you for posting and using CoE!
