### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Setup Wizard has issues with finding and creating groups

### ISSUE THREAD

**Issue by edarcy87** [microsoft/coe-starter-kit#4695]
### Describe the issue

I created three new groups all identical in setup prior to loading the setup wizard. I load the wizard and start assigning groups. I notice initially the wizard only picked up on my users group. So I added that.

I deleted the admin and maker group from M365 admin and used the wizard to make new groups.

I noticed an error saying there was no connection, so I looked in the solution and saw the Create Group flow was off. I turned it on.
I proceeded to creating my maker group fine. The screen changed to a green check and shows the Configured: IDNumber

I start on the Admin group. Initially the wizard does not load the fields for group name/email.

I refresh the screen and it loads. I enter in the group name and email.
The screen now shows Configured: admins@tenant.abc instead of the ID number.

### Expected Behavior

I expected the wizard to pick up all the groups
I expected the Create Group flow to already be on
I expected the configured screen to show the ID of the created group

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Setup Wizard

### Steps To Reproduce

I created three new groups all identical in setup prior to loading the setup wizard. I load the wizard and start assigning groups. I notice initially the wizard only picked up on my users group. So I added that.

I deleted the admin and maker group from M365 admin and used the wizard to make new groups.

I noticed an error saying there was no connection, so I looked in the solution and saw the Create Group flow was off. I turned it on.
I proceeded to creating my maker group fine. The screen changed to a green check and shows the Configured: IDNumber

I start on the Admin group. Initially the wizard does not load the fields for group name/email.

I refresh the screen and it loads. I enter in the group name and email.
The screen now shows Configured: admins@tenant.abc instead of the ID number.

**Comment by edarcy87** [comment]
Thanks, Jenefer!!

**Comment by Jenefer-Monroe** [comment]
You bet, thank you for posting and using CoE!

**Comment by manuelap-msft** [comment]
Closing as duplicate.
