### ISSUE TITLE
[CoE Starter Kit - QUESTION] Does the wizard run flows in a specific order?

### ISSUE THREAD

**Issue by edarcy87** [microsoft/coe-starter-kit#4697]
### What is your question?

Previously, when setting up core components, one would turn on and run flows in a specific order and during off peak time.
The wizard says to turn them on - will it know what flows to run and when or does it just turn them on?

![image](https://user-images.githubusercontent.com/124092704/215887954-dac53a72-963c-485e-8256-72853e549f91.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Setup Wizard

**Comment by manuelap-msft** [comment]
Hello,

the flows run on a schedule, and some have a delay figured in or run automatically when something else happens in the system. The setup wizard has all of that logic embedded and you can just turn the flows on from here, and you no longer have to worry about turning them on in a specific order.

Hope that helps,
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
