### ISSUE TITLE
[CoE Starter Kit - QUESTION] Post message to Teams disabled by admin

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#4700]
### Describe the issue

Hi, when the flow posts the massage to get the business justification from the Teams- Owner, there ist the following error: 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/62603605/216012835-f249c396-3f1d-4c0a-89ae-3be05acf1ff5.png">

I tested this behaviour in a dev tenant and the problem seems to be that custom apps are not allowed in Teams admin center, and allowing all custom apps is not an option. What setting would be nessecary to post the messagt to a teams chat?

Would be great to get help with this! 

Best regards
Cathi

### Expected Behavior

Post massage to Teams Owner

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.23

### What app or flow are you having the issue with?

Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created

### Steps To Reproduce

Create Teams environment

**Comment by manuelap-msft** [comment]
Hello,

we're unfortunately not Microsoft Teams admin experts, so not quite sure what's blocked here. According to some research it seems to be to do with the Custom app policy for Teams app permissions. Here's some pointers
- https://learn.microsoft.com/en-us/microsoftteams/teams-app-permission-policies
- https://stackoverflow.com/questions/72222231/botdisabledbyadmin-error-from-microsoft-bot-framework
- https://powerusers.microsoft.com/t5/Using-Flows/Teams-Post-Addaptive-card-error-BotDisabledByAdmin/td-p/916478

You will have to work with your Microsoft Teams admin on setting the app policy, and may have to raise a support ticket to get assistance on how to set them if your Teams admin doesn't know.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
