### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to fix the connection to the custom connector after upgrade?

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#4705]
### Describe the issue

Since updating the core components to the latest version 4.2 in December 2022, I noticed that the audit log table stopped updating as of 1/8/2023. After importing the latest version, the connection to the Office 365 Management API was broken and I followed the steps to update the connector. Both the [Child] Admin | Sync Logs and Admin | Sync Audit Logs continue to run successfully.

### Expected Behavior

The telemetry data in the Audit Log table to be updated daily.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

It looks like the Admin | Sync Template V3 failed on 1/26/2023 but not sure if this is related.

### Steps To Reproduce

As of 1/8/2023, the data in the Audit Log table in the core solution has not updated.

### Anything else?

I would very much appreciate your assistance.

**Comment by manuelap-msft** [comment]
Hello,

Connections to custom connectors often get broken on solution upgrade that may be what happened here. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve that and re-establish a connection get the Audit Log working again.

Thank you
Manuela

**Comment by dcurt1977** [comment]
Thanks for the quick response. The connection to the connector was re-established for some weeks now, but the data has not updated in the Audit Log. I don't know what else i should be checking for the Audit Log to start working again.

**Comment by Jenefer-Monroe** [comment]
Let's first make sure everything is fixed up correctly. 

First, please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

Then A picture like this showing if the flows are running successfully:
![image](https://user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png) 

Lastly a picture like this showing if the data is populating, sorted to show most recent data on top
![image](https://user-images.githubusercontent.com/89584709/164469099-1cb27bec-a1b8-4a22-8b2c-c9bdb50d7d33.png)

**Comment by dcurt1977** [comment]
<img width="958" alt="Office 365 ManagementAPI_CustomConnector" src="https://user-images.githubusercontent.com/123478097/216400038-4fe61f57-45cc-4a97-a43b-be67cc6c89da.PNG">

**Comment by dcurt1977** [comment]
<img width="583" alt="Admin_SyncAuditLogs" src="https://user-images.githubusercontent.com/123478097/216400217-bef3f282-161f-44fb-97a6-cafc634b5a6c.PNG">

**Comment by dcurt1977** [comment]
<img width="873" alt="Audit Logs" src="https://user-images.githubusercontent.com/123478097/216400262-8caaf129-7f37-42e5-b4c7-5003d95f806e.PNG">

**Comment by Jenefer-Monroe** [comment]
A few more questions:
- Are you a commercial tenant or some other tenant type (ex GCC)
- Are you getting the chunking warning mail? Suggesting that you are not receiving all data?

**Comment by dcurt1977** [comment]
GCC tenant. I did received the chunking warning mail up until 1/8/2023.

**Comment by Jenefer-Monroe** [comment]
OK I remember someone hitting a bug once where in GCC, the flows all ran but the data didnt actually write. 
For them this was due to the wrong Resource URL being used. 

![image](https://user-images.githubusercontent.com/89584709/216639275-27d0edf7-5fc5-43c5-9519-0de8d4c7b206.png)

From [Set up the custom connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector)
![image](https://user-images.githubusercontent.com/89584709/216639501-599df765-a385-4d3d-81fe-80cf6ec94280.png)

Can you try that?

**Comment by dcurt1977** [comment]
The correct Resource URL for GCC tenant was entered in the connector. Today i discovered in the Admin - Command Center App of a unmanaged layer in the Child | Admin - Sync Logs. I removed the unmanaged layer in the Audit Logs solution the re-import the current version 2.10. Could this might have created the issue? 

<img width="953" alt="ChildAdmin_SyncLogs_" src="https://user-images.githubusercontent.com/123478097/216645003-9fa5e5c4-fb36-421a-aaf8-e8c50f5dd04c.PNG">

**Comment by Jenefer-Monroe** [comment]
It could be. Lets see what happens when they run next!

**Comment by dcurt1977** [comment]
Unfortunately, the Audit Logs still not updated.

**Comment by Jenefer-Monroe** [comment]
Can you please configure this screen again and share a screenshot before you hit update connector? 
Obscure the information (app id and secret) but share the screenshot so that I can see if the input is well formatted.
![image](https://user-images.githubusercontent.com/89584709/217053851-4516b2af-775c-4c18-8440-6f301d3bdaf4.png)

**Comment by dcurt1977** [comment]
<img width="862" alt="Connector_Screenshot" src="https://user-images.githubusercontent.com/123478097/217065426-b09481de-186d-4c34-b146-f460943b6f07.PNG">

**Comment by dcurt1977** [comment]
<img width="497" alt="Connector_Screenshot" src="https://user-images.githubusercontent.com/123478097/217065716-c2d74d56-eba4-4c21-9600-2e6108ddcd7d.PNG">

**Comment by dcurt1977** [comment]
<img width="497" alt="Connector_Screenshot" src="https://user-images.githubusercontent.com/123478097/217065909-f3bfd7c2-2358-46f6-8724-669d3454f0ac.PNG">

**Comment by Jenefer-Monroe** [comment]
ok lets test it from here next. 
for PublisherIdentifier, you put the Client id from above. 
![image](https://user-images.githubusercontent.com/89584709/217066988-ec84f590-641b-4ba8-ae4f-e9c135eb88b5.png)

**Comment by dcurt1977** [comment]
<img width="553" alt="Connector_Test_operation" src="https://user-images.githubusercontent.com/123478097/217068940-492d6883-e277-494b-97fc-7359db44698d.PNG">

**Comment by Jenefer-Monroe** [comment]
Sorry I should not have cut off at just the OK (200). Can you show it returning rows? 
![image](https://user-images.githubusercontent.com/89584709/217069769-41155f04-1eeb-4c48-a869-a4d6413fe19d.png)

**Comment by Jenefer-Monroe** [comment]
Next go to the most recent run of the flow **_[Child] Admin | Sync Logs_**
Is content returned there? 
![image](https://user-images.githubusercontent.com/89584709/217070506-6dd2bf8f-acf3-4a70-b1d5-10d4f03eef55.png)

**Comment by dcurt1977** [comment]
<img width="302" alt="ChildAdmin_SyncLogs" src="https://user-images.githubusercontent.com/123478097/217076360-844632a9-e4c0-4da3-a70f-82faec3b81eb.PNG">

**Comment by Jenefer-Monroe** [comment]
If you go just below that to the next scope, what is shown here?

**Comment by dcurt1977** [comment]
![Send an email_chunk size](https://user-images.githubusercontent.com/123478097/217261704-eb64de13-5f8e-4c4f-a9bd-c26ff169461c.PNG)

**Comment by dcurt1977** [comment]
Up until 1/8/2023, we received this email notification: CoE Audit Logs - Missing some logs - require smaller chunks.

**Comment by Jenefer-Monroe** [comment]
And what do you see here in the next section? 
![image](https://user-images.githubusercontent.com/89584709/217313463-5c4feb4d-0b38-4f77-bb4b-9a669c124e66.png)

**Comment by dcurt1977** [comment]
![GetContentDetails](https://user-images.githubusercontent.com/123478097/217352697-cc55c27d-ae78-4050-a31b-74671061ce46.PNG)

**Comment by dcurt1977** [comment]
Is there a possibility, that the system ID that is used to setup the CoE Starter Kit has had its access to the Audit Logs blocked by Global Admin? Here is an excerpt from Microsoft documentation that led me to this conclusion.

If you'd like to collect telemetry information, such as app launches and unique users per app, you must be granted access to the Audit Log and work with a Global Admin who has access to [Microsoft 365 audit log](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#before-you-search-the-audit-log) to complete the setup.

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

**Comment by dcurt1977** [comment]
What do you recommend? Should we try to re-import the core components?

**Comment by Jenefer-Monroe** [comment]
Not for this, no. There isnt anything wrong with the connector or your permissions it seems. It is pulling back logs as you can see above. 

What do you see here? 
If it looks like this, nothing in the Apply to each Audit Log, then that means no launches came back. 
And if you look in the PArse JSon call you will see what operations did come back, in my case it was things like shown CRMDefaultActivity
![image](https://user-images.githubusercontent.com/89584709/218105165-9b3076c6-053a-4441-8421-d28225767368.png)

**Comment by Jenefer-Monroe** [comment]
I wonder if your environment variables got reset somehow and you just arent bringing back enough logs as a result. 
What are your environment variable values for these? 
![image](https://user-images.githubusercontent.com/89584709/218105747-b02eb3ec-3f75-4508-a6bb-2a36df6f61f2.png)

**Comment by dcurt1977** [comment]
<img width="293" alt="Apply_To_Each_AuditLog" src="https://user-images.githubusercontent.com/123478097/218113693-8b00ce23-584a-45aa-a1fe-4561aabacd6d.PNG">

**Comment by dcurt1977** [comment]
[Environment_Variables.docx](https://github.com/microsoft/coe-starter-kit/files/10708213/Environment_Variables.docx)

**Comment by dcurt1977** [comment]
<img width="776" alt="Environment_Variables" src="https://user-images.githubusercontent.com/123478097/218114548-e20d4908-bf12-4f22-a609-930ef7063230.PNG">

**Comment by Jenefer-Monroe** [comment]
So you are getting activities but not launches. I think what you will need to do is:

1) Go launch some apps and note the date time
2) When that data is available in the audit logs (takes about a day) go to the audit logs and find then in the UX
3) Then go see if they come through here, you'll need to look through all the child flows for it unfortunately.

**Comment by dcurt1977** [comment]
On 2/15/2023, I launched a couple apps as noted. After checking the audit logs in the UX, I did not see any recent logs. As shown in the image, the Apply to each Audit Log is blank.

<img width="929" alt="Apply_to_each_AuditLog_v2" src="https://user-images.githubusercontent.com/123478097/219455703-3b3135cc-e453-4326-8f47-2127af399371.PNG">

**Comment by dcurt1977** [comment]
I am in the process of setting up the CoE in a testing environment. I have already set up the core components and will set up the Office 365 Management API custom connector. This way, our organization can test the upgrades before deploying to the CoE production environment.

**Comment by Jenefer-Monroe** [comment]
Sounds good. If the logs arent writing to the UX either then there may be a product issue at play. 
Please let me know when your launches show up in the UX.

**Comment by dcurt1977** [comment]
On 02/16/2023, the Audit Logs component was set up in the testing environment and so far, launches are showing up in the UX. Here is a screenshot of the Child Admin Sync Logs flow. I will continue to monitor for the next couple days to evaluate consistent updates.  
<img width="955" alt="Apply_to_each_AuditLog_testenvironment" src="https://user-images.githubusercontent.com/123478097/219696932-79ade6ef-a468-45be-8e43-173ab4141667.PNG">

**Comment by dcurt1977** [comment]
I just checked the production environment where the CoE was initially set up and it appears that launches are showing up in the UX from 2/16/2023 to current. On 2/16/2023, the custom connector host name was changed from https://manage.office.com to https://manage-gcc.office.com. In the image below, the Apply to each Audit Log action is skipped compared to the one that was recently setup in the testing environment as shown above. We will continue to monitor launches in the production environment UX.

<img width="953" alt="ChildAdmin_SyncLogs_List_audit_log_content" src="https://user-images.githubusercontent.com/123478097/219717948-c0785885-6813-4160-8a90-518ce64c5399.PNG">


<img width="955" alt="ChildAdmin_SyncLogs_Apply_to-each_AuditLog" src="https://user-images.githubusercontent.com/123478097/219717985-f4e49af8-5ea7-4d9c-8152-c1533e50684e.PNG">

**Comment by dcurt1977** [comment]
Here is an a screenshot of the most recent Audit Logs. The "Apply to each Audit Log" action for all the flow runs are skipped. 

![Updated_AuditLogs](https://user-images.githubusercontent.com/123478097/220464382-5b3d1db2-56c2-428c-875d-c87665557293.PNG)

**Comment by Jenefer-Monroe** [comment]
It looks like its working now. IT will skip where you showed when that case does not contain launches.
