### ISSUE TITLE
[ALM Accelerator - BUG]: Need to update Release History

### ISSUE THREAD

**Issue by sciencestudent-Sharon** [microsoft/coe-starter-kit#4707]
### Describe the issue

Hi,

On Step 5 of **Set up your first Azure DevOps project for use with ALM Accelerator for Power Platform** - https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-preview#set-up-your-first-azure-devops-project-for-use-with-alm-accelerator-for-power-platform

Every time I click on Project Wizard the prompt for update Release History pops up, I select YES, but nothing else shows up for me to advance to Step 6.

Thank you

### Expected Behavior

Clicking on Project Wizard allows user to complete Step 6 of these instructions without prompting again to download Release History 
(**Set up your first Azure DevOps project for use with ALM Accelerator for Power Platform** - https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-preview#set-up-your-first-azure-devops-project-for-use-with-alm-accelerator-for-power-platform)

### What component are you experiencing the issue with?

ALM Accelerator for Power Platform Administration

### What solution version are you using?

1.0.20221206.2

### Steps To Reproduce

1. Open the ALM Accelerator for Power Platform Administration app.
2. Click Projects in the Azure DevOps group in the left side navigation.
3. If prompted to update Release Tags, click Okay. The app will download the available release tags from the ALM Accelerator Github repository.
4. Select an Azure DevOps organization in the Organization drop-down.
5. <del>In the Projects List, click New and select Project Wizard</del> Under Projects, click on New and select Project Wizard. If prompted to update Release History, click 'YES'.
6. 

### Anything else?

Not sure if this is related to user permission being able to create projects in Azure DevOps but prereqs only state: A licensed Azure DevOps user with permissions to create and manage pipelines, service connections, repos, and extensions.

**Comment by sciencestudent-Sharon** [comment]
Hi, I'm not familiar with this configuration, can anyone help provide insight on why I may be running into the above described issue? Thanks
 @mikefactorial @jenschristianschroder @RajeevPentyala

**Comment by mikefactorial** [comment]
@sciencestudent-Sharon the update release history prompt will run a flow to pull down the latest releases of the ALM Accelerator releases. That's probably not the issue or is a ref herring. My guess is that it may be related to your ability to create / manage projects in the wizard. Would be helpful if you could share a screenshot of where you are getting stuck or if there's a specific error message you see that won't let you move to Step 6

**Comment by sciencestudent-Sharon** [comment]
@mikefactorial thanks for response!
Unfortunately, I didn't see an error message.
I made a gif of the issue - essentially, the release history prompt is looping.

![alm-releasehistory-issue](https://user-images.githubusercontent.com/38770482/218860002-f8fa7afc-874b-4b32-8fa3-25d471f0a06a.gif)

**Comment by sciencestudent-Sharon** [comment]
Turns out the flow was by default(?) turned off when it was imported into the environment as part of the Solution, once I turned it on, pressing 'Yes' to download the release history worked, project wizard panels etc are showing up now
Thanks

**Comment by tocri** [comment]
I had the same error today.
The flow GetReleaseHistory was not activated because i had a connection issue on the dataverse connector.
After i fix it, i manually start AA4PP and the warning Need release history was gone

**Comment by tocri** [comment]
I had the same error today.
The flow GetReleaseHistory was not activated because i had a connection issue on the dataverse connector.
