### ISSUE TITLE
[ALM Accelerator - Feature]: Deployment settings - "Apply to all"

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4720]
### Is your feature request related to a problem? Please describe.

With a large solution, it's a little repetitive updating the deployment settings - especially for canvas app sharing, and flows. It'd be good if you could have a template and then say "apply this to all objects"

This is the page I mean:
![image](https://user-images.githubusercontent.com/55705669/216353292-b7079912-9591-4edf-903f-85a73dfdf38f.png)

### Describe the solution you'd like

Apply to all functionality

**Comment by mikefactorial** [comment]
Closing this as it was implemented in a previous release.
