### ISSUE TITLE
[ALM Accelerator - Feature]: Make using single AzDO Service Connection per Service Principal easier

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#4721]
### Describe the solution you'd like

Build Tools enabled using a single service connection per service principal across multiple environments via the BuildTools.EnvironmentUrl capability a while back.  While the plumbing of the accelerator supports this, the default setup and configuration still guides people to build a service connection per environment.  We should give people more flexibility either through the app or docs to choose the Service Principal / Service Connection mapping they prefer.

**Comment by mikefactorial** [comment]
Closing this out as it's been implemented in the admin app.
