### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by mtamura2023** [microsoft/coe-starter-kit#4729]
### What is your question?

監査ログをPowerAutomateを使用して取得する設定を行うため、AzureADアプリの作成を行いカスタムコネクタの設定の設定時に Office 365 管理 API カスタム コネクタがなかったため、新規カスタムコネクタで設定を行いたい。
新規カスタムコネクタで監査ログ取得する場合の設定パラメータについて教えてほしい。
手順は https://learn.microsoft.com/ja-jp/power-platform/guidance/coe/setup-auditlog を参考にして実施しています。

新規カスタムコネクタ作成時を行った際の設定内容は以下

※AADアプリケーションID、シークレット以外はデフォルトのまま

ホスト ：本来指定すべきホスト名がわからなかったため、既存のカスタムコネクタに設定してあった値を入力

認証タイプ：OAuth 2.0

ID プロバイダー：AsureActiveDirectory

CliemtID：AADアプリケーションID

ClientSecret：AADアプリケーションシークレット

Login URL：https://login.windows.net/

Tenant ID：Common

Resource URL：https://management.core.windows.net/

Enable on-behalf-of login：false

上記設定で作成されたリダイレクトURLは以下となったが、間違っていると思われる。

https://global.consent.azure-apim.net/redirect

### What solution are you experiencing the issue with?

Audit Log

**Comment by Jenefer-Monroe** [comment]
Hello. The CoE Starter Kit team is a very small team, I'm afraid we are not staffed to assist with such customizations. Creating the custom connector is very complex, its not something that I could talk you through here. 

The custom connector is delivered in the Core solution. You can see it by going to your CoE environment, Dataverse > Custom Connectors
![image](https://user-images.githubusercontent.com/89584709/216592151-3a629205-9460-479a-8e94-8f045031b4af.png)

**Comment by mtamura2023** [comment]
ご回答ありがとうございます。
カスタムコネクタの詳細を説明することは難しいと理解しました。
それでは新規カスタムコネクタをOAuth 2.0認証で作成する際に参考になるサイトがあればURLを教えていただけますでしょうか？
