### ISSUE TITLE
[CoE Starter Kit - BUG]: Unable to setup audit logs

### ISSUE THREAD

**Issue by joyfdacs** [microsoft/coe-starter-kit#473]
GCC Audit Logs--data is not being populated.

**Component (please tell us which flow or app you are experiencing issues with):**

 CenterofExcellenceAuditLogs_1_40_managed.zip

Center of Excellence - Audit Logs
[Child] Admin|Syna Logs
Admin|Sync Audit Logs

![NoData](https://user-images.githubusercontent.com/84588783/119351298-54cbd100-bc6e-11eb-8006-58119dbb2055.JPG)

The same issue as:  https://github.com/microsoft/powerapps-tools/issues/568

**Comment by JeneferM-MSFT** [comment]
At the end of that issue (568) it appeared that writes were not happening to the office audit log table. 
Can you please 
1. Open a browser as the identity that is running the audit log flows
2. Go to https://protection.office.com/unifiedauditlog 
3. Filter to Activity Launched app 
4. Hit Search
5. Return here with a screenshot showing results? 
6. 
![image](https://user-images.githubusercontent.com/62659043/119372820-feae5c00-bc74-11eb-80fd-76f65799fbbf.png)

**Comment by joyfdacs** [comment]
Thanks! I followed the steps, the service account was able to get the results.
![auditlogs_5_26](https://user-images.githubusercontent.com/84588783/119729238-6cf44980-be42-11eb-8ce7-17130ccf7135.JPG)

**Comment by JeneferM-MSFT** [comment]
Hello. Can you also tell me, are you GCC High? We just discovered with GCC High you need to change the login url to https://login.microsoftonline.us when setting up the custom connector.

**Comment by grkoop** [comment]
Jenefer - they are just GCC, not GCC High.

**Comment by JeneferM-MSFT** [comment]
At the bottom of the bug you referenced we found that the flow was succeeding but the writes were not happening. 
Did you contact support? 
You may be on an old version that used the old unreliable connector. 
Can you please upgrade to the latest version of Audit Logs?

**Comment by JeneferM-MSFT** [comment]
Closing out as no work for toolkit without repro
