### ISSUE TITLE
[CoE Starter Kit - BUG] Deleted flows being listed in the Automate of Power Platform Admin View app.

### ISSUE THREAD

**Issue by SuryanshTripathi** [microsoft/coe-starter-kit#4735]
### Describe the issue

The flows already deleted from the tenant are also being listed in the flows tab of the "Power Platform Admin View" app.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.19

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Hello, deleted objects are removed by **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** flow. 

Please be sure you have it, and all the other clean up flows running in the [inventory setup instructions](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
