### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor V2 not accurate

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#4738]
### Describe the issue

I have tested the DLP Editor by disabling the RSS connector in the CoE enviornment. The DLP Editor shows two apps impacted by this change.  Maker - Command Center and Admin - Command Center. However when I export the csv file I get a bigger list of apps that don't necessarily use this connector. Below are pictures as reference. 

![image](https://user-images.githubusercontent.com/95443860/216720074-98591db1-a168-45f5-9a25-95453732c295.png)
![image](https://user-images.githubusercontent.com/95443860/216720204-42df5b39-2992-4cc0-8d7c-49ec0b637b2f.png)

### Expected Behavior

DLP Editor should be able to export the list of impacted applications to a CSV file and the number of impacted application within the app and csv file should be the same.  The same is true for flows. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

DLP Editor V2 

### Steps To Reproduce

Click on export to csv once the impact list has been generated.

**Comment by Jenefer-Monroe** [comment]
Can you please let me know, has the **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_** flow run since you upgraded to Core 4.2? And does it have any unmanaged layers on it?

**Comment by nasilvae** [comment]
Hi Jenefer, 

![image](https://user-images.githubusercontent.com/95443860/216986574-d60db87f-dae8-4107-bbb9-9f996e69ab61.png)
![image](https://user-images.githubusercontent.com/95443860/216986611-49cd2aaf-7ccd-461b-9033-b11c91bf6551.png)
![image](https://user-images.githubusercontent.com/95443860/216986677-17d11660-5375-46f2-b8eb-0f18000dc18b.png)
![image](https://user-images.githubusercontent.com/95443860/216986793-870b1ae1-0563-41b5-b82c-51b63df0310c.png)

Both flows are running normally with no unmanaged layers. Let me know if you need additional information.

**Comment by Jenefer-Monroe** [comment]
ok thank you. Will put on the list to investigate for March.

**Comment by nasilvae** [comment]
> ok thank you. Will put on the list to investigate for March.

Thank you Jenefer. If possible, let me know if there are any workarounds for this. We are in the process of organizing all the dlp policies in the tenant and we have a big tenant where this type of functionality will make a big difference.

**Comment by manuelap-msft** [comment]
It looks like this is related to apps that trigger flows, which show as having a LogicFlows (shared_logicflows) connector which is treated by the impact analysis as a connector (as the app metadata returns it as a connection) but is not actually a connector. We need to filter this out. We are having some other issues with this as well, see #4293.

The solution is to filter out shared_logicflows from the connections, so it's not treated like a connector.

Fixed for March release. If this is time critical for your scenario let me know, and I'll walk you through the changes need to make updates to the flow.
