### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION > Manual eddit value for TenantID

### ISSUE THREAD

**Issue by jeremy-Itprofessional** [microsoft/coe-starter-kit#4739]
### What is your question?

In the startup wizard, i didn't check the right value of the tenant ID.
i had a list of items that i needed to fill out and later i saw that i put in a application ID and not tenantID

In dataverse i found out that the value of TenantID is empty.

Is there a way to fill this manaully, if yes How????

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Wizard app - flow > Admin | Sync Template v3 CoE Solution Metadata

**Comment by Jenefer-Monroe** [comment]
Hello. Yes the tenantid is stored as an environment variable in the system, so you can update it manually. 
Please see [Update environment variables](https://learn.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables) for how to do that.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
