### ISSUE TITLE
[CoE Starter Kit - BUG] Refresh BYODL PBI in web failure: Expression.Error: The key didn't match any rows in the table.

### ISSUE THREAD

**Issue by BroxCJ** [microsoft/coe-starter-kit#4740]
### Describe the issue

We are starting to use a PBI Report based on COE -including the Data Export features for PowerAutomate-, the report works when refreshing from the Desktop App, but when we upload it to a POwer BI Workspace, we found this error:

An error occurred while processing the data in the dataset. 
Refresh failed:

COE - PowerPlatform Report - BYOD has failed to refresh.
Failure details: The last refresh attempt failed because of an internal service error. This is usually a transient issue. If you try again later and still see this message, contact support. 
<ccon>Expression.Error: The key didn't match any rows in the table.. Key = <ccon>[workspaceId = "91a1aade-78fc-410b-b18c-c39163860b29"]</ccon>. Table = <ccon>#table({"workspaceId", "workspaceType", "Data", "workspaceName", "Tags", "ItemKind", "ItemName", "IsLeaf"}, {})</ccon>. </ccon>;<ccon>The key didn't match any rows in the table.</ccon>. The exception was raised by the IDbCommand interface. Table: byod_flowusage.
Next refresh for COE - PowerPlatform Report - BYOD is scheduled for February 5, 2023 23:00 UTC.	

### Expected Behavior

Normal Refresh an been able to get the report workig properly.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

[Child] Admin Sync Logs

### Steps To Reproduce

1st) Create the PowerAutomate Data Export connections.
2nd) Create the DataFlow.
3rd) Create the Connection as definend in document attached.
4th) Publish the report. (I cannt include the .pbit in this issue, but it's called  BYOD_COE_Dashboard_Sept2022.pbit)
[CoE on BYODL setup.docx](https://github.com/microsoft/coe-starter-kit/files/10611800/CoE.on.BYODL.setup.docx)
 

### Anything else?

N/A

**Comment by manuelap-msft** [comment]
We've not seen this error with recent releases. Closing out but please raise a new issue if you're experiencing issues with a more recent version.
