### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to capture cross flows details with respect to cross connection ids

### ISSUE THREAD

**Issue by RambabuDasari412** [microsoft/coe-starter-kit#4743]
### What is your question?

Hi Team,
We have cross tenant connection ids("admin_accountname": connections which are established with gmail accounts and etc) are present in admin_connectionreferenceidentity table. We want to capture the flow details for those cross connection references from admin_flow table. Is there any unique column to get the flow details and with respect to  admin_accountname in two tables. Please suggest how to achieve this from COE tables kindly suggest.
Thanks,
Rambabu Dasari

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately the information about which connection identity is used in a flow is not stored anywhere for us to query. 
In other words, we know that a flow uses Sharepoint, but not of its the Sharepoint connection from Jon or Jane that is used. 
Sorry we cannot provide this information as a result, I know it is commonly requested.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
