### ISSUE TITLE
[CoE Starter Kit - BUG] Error loading app, flow and custom connector page in Developer Compliance Center

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#4748]
### Describe the issue

![image](https://user-images.githubusercontent.com/89584709/216986596-38e19eb6-2eb6-4446-af05-9f08db69c048.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.6

### What app or flow are you having the issue with?

Developer Compliance Center

**Comment by manuelap-msft** [comment]
Seems to have been a custom page glitch, removed the connectors from the page, re-added them, re-published and it's working now. This will be part of the March release.
![image](https://user-images.githubusercontent.com/55705669/217283792-1c07a827-9bab-49eb-9ae3-bc0b6a24f83d.png)
