### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to find Deployment Profile in the Choose your profile dropdown

### ISSUE THREAD

**Issue by shree2905** [microsoft/coe-starter-kit#4750]
### Describe the issue

I've created one deployment user setting for the user, then I have provided below user functions.

![image](https://user-images.githubusercontent.com/79618656/217210180-65311b84-45f3-42d4-ab83-b69357aaad4d.png)

And added deployment profile to the user setting.

![image](https://user-images.githubusercontent.com/79618656/217213066-28993ad1-fe5d-4d82-bd50-bfd7c71d397e.png)

But still i'm unable see the deployment profile in the choose profile drop down as you can see in below snap.

![image](https://user-images.githubusercontent.com/79618656/217212183-8785e106-33cb-4d37-9acd-2bbb6f2c4f2b.png)

 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 2022

**Comment by mikefactorial** [comment]
@shree2905 try setting the Update Profile to Allowed on the User Settings in order to set a Deployment Profile on the Solution.

**Comment by mikefactorial** [comment]
As a follow up. If the intention is for you as an admin to create / set the deployment profiles and not allow the makers to make modifications you can create a specific deployment user setting for admins to set the profiles and still limit makers from making modifications using the current user setting record you have setup.
