### ISSUE TITLE
[CoE Starter Kit - QUESTION] audit logs missed due to truncated results

### ISSUE THREAD

**Issue by nsidrak** [microsoft/coe-starter-kit#4751]
### What is your question?

i have a small to medium environment and i keep getting "CoE Audit Logs - Missing some logs - require smaller chunks" emails.
Solution: "Center of Excellence - Audit Logs"
Version:2.10
Managed: Yes
any suggestions to fix this issue?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

**Comment by nsidrak** [comment]
Hi Jenefer,
thanks for the information, i already tried:
TimeSegments-CountLimit: 1500
TimeInterval-Unit: Minute
TimeInterval-Interval: 1
and also, all the different options listed on the Microsoft document but that did not solve the problem. 
any other recommendations?   
Thanks.

**Comment by nsidrak** [comment]
is there a way to change the "TimeInterval-Interval: and TimeInterval-Unit: " to seconds? and what would be the "TimeSegments-CountLimit:" in this case? what is the formula for calculating the time variables?
Thanks...

**Comment by Jenefer-Monroe** [comment]
I've not tested to seconds, I imagine you will get throttled, but you could try
The format (second, minute, etc) is as used in these types of power automate calls
![image](https://user-images.githubusercontent.com/89584709/217629232-568d8703-b7b7-4c1e-b0c0-3f2a840d17bc.png)

The equation is basically just a multiply.  See [here](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog#example-configurations-for-environment-variables) for examples.
So this creates 24, needs to be under the "count limit" which works of 60
![image](https://user-images.githubusercontent.com/89584709/217629641-b8314e53-1967-4c3b-b8e7-89e9a784f61e.png)
So per second going back one day would need to be 24 (hours) * 60 (minutes) * 60 (seconds) = 86,400

I dont think this will work but you can certainly try. 
You would likely need to instead run it more often (hourly?) and have it only fetch the second sized chunks from there, but even then it would be 3600. We arent staffed to assist with this level of customization unfortunately. 

I think your better bet will be starting to investigate the self service analytics where we are investing to make this scenario work for large organizations.

**Comment by nsidrak** [comment]
Hi Jenefer,

thanks for all the information,  i tried the following two configuration, it improved the number of emails i am receiving but it did not solve the problem:
StartTime-Interval: 1
	StartTime-Unit: Day
	TimeInterval-Interval: 30
	TimeInterval-Unit: Second
	TimeSegments-CountLimit: 2900

        StartTime-Interval: 1
	StartTime-Unit: Day
	TimeInterval-Interval: 15
	TimeInterval-Unit: Second
	TimeSegments-CountLimit: 5000

**Comment by Jenefer-Monroe** [comment]
It appears you will need to get on the new architecture when available then to reliably get usage data. 
Good news is that it includes usage information for model driven apps and cloud flows too, which is something we dont have with this old custom connector methodology. 
We are close to being able to release CoE Starter Kit integrated with Self Service Analytics so I suggest you check it out and get prepared so that you can benefit from it. 

Some starter links
- https://docs.microsoft.com/power-platform/admin/self-service-analytics
- https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
