### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by jpmclaughlin12** [microsoft/coe-starter-kit#4758]
### Describe the issue

When trying to access -'Admin - Access this App', I am getting the attached error.
<img width="1092" alt="Admin App error" src="https://user-images.githubusercontent.com/118436878/217519883-8727cdb9-e3cb-416a-9901-da4ab467e932.png">

I have not made any changes to the environment, unless I made them unaware to myself.

### Expected Behavior

I should be able to access this app.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

unsure

### What app or flow are you having the issue with?

Admin - Access this app

### Steps To Reproduce

1. In the CoE environment run Admin - Access this app

**Comment by Jenefer-Monroe** [comment]
What version of core are you using? And from where are you accessing this app? Note that it is only usable from [within the context of the PBI reports](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard), it is not a stand alone app.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
