### ISSUE TITLE
[ALM Accelerator - QUESTION] Why cant get all the environments

### ISSUE THREAD

**Issue by EnsilaC** [microsoft/coe-starter-kit#4761]
### What is your question?

hi Team, 

i am checking on the ALM Accelerator for Power Platform App. In the list of the environments to choose i dont have all the tenant environments listed. 
Is there a prerequisite on the environments to be shown there?
Best
Ensila

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Accelerator Version: 1.0.20221206.2

**Comment by mikefactorial** [comment]
@EnsilaC the only prerequisite is that the environment has Dataverse. Sometimes it does take a little while for recently assigned environments to show in the list. i.e.
![image](https://user-images.githubusercontent.com/42348035/217895189-62110254-71ca-4d3e-a9a3-183ef4da1ed7.png)

**Comment by mikefactorial** [comment]
Closing this out as there's no further action required here.
