### ISSUE TITLE
[CoE Starter Kit - Feature]: I tried to install the latest release CoE starter kits, but i hit the error

### ISSUE THREAD

**Issue by LanMorton** [microsoft/coe-starter-kit#4763]
### Is your feature request related to a problem? Please describe.

Hi Jenefer,
 I tried to install the latest release CoE starter kits, but i hit the following error:
The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

### Describe the solution you'd like

Hi Jenefer,
 I tried to install the latest release CoE starter kits, but i hit the following error:
The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

### Describe alternatives you've considered

Please advise how can we install this release 2023.02

**Comment by manuelap-msft** [comment]
Have you unzipped the CoEStarterKit.zip file after download?

**Comment by Jenefer-Monroe** [comment]
Hello, the same issues you had upgrading from https://github.com/microsoft/coe-starter-kit/issues/4753 will also be hit trying to uninstall. You will need to start with a fresh environment. 

Please be sure to start with [Getting started with CoE Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/setup)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by PStapperMazars** [comment]
Hello,.

I am also struggling with the same error message: 

The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

What do i need to do as i never experienced this before. It is a complete clean / new environment.

thanks for your help.

**Comment by manuelap-msft** [comment]
Hello,

this error message usually happens when you try to import the CoEStarterKit.zip file as a whole - note that this is not a solution file, you'll have to unzip it to a local folder and then upload the solution file - see these steps here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-the-core-components-solution

![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/77e5f8b5-a0b8-4d92-8334-0ea4e5bda5d1)

**Comment by PStapperMazars** [comment]
Thank you Manuela, i realized this myself about an hour ago but forgot to close my question here. Sorry for this and thanks for your help.
