### ISSUE TITLE
[CoE Starter Kit - BUG] Incorrect Email ID in "Admin - Welcome Email v3"

### ISSUE THREAD

**Issue by thso77** [microsoft/coe-starter-kit#4764]
### Describe the issue

In the "Admin - Welcome Email v3" flow, the compose action named "emailGUID to en-US" uses "253a3c62-8c80-ed11-81ac-0022480813ff" as an input for the record ID in the Customized Email table. However, there is no record in the Customized Email table with this ID. This causes the flow to fail with the following error: "admin_customizedemail With Id = 253a3c62-8c80-ed11-81ac-0022480813ff Does Not Exist".

I replaced the compose input with the actual ID of the Welcome email, which is "f530c294-4742-ec11-8c62-00224829bf00", and the flow ran successfully. However, now there is an unmanaged layer on this flow which is not ideal.

### Expected Behavior

The flow should use the correct record ID in the Customized Email table as an input to the compose function. This will allow then flow to run successfully. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin - Welcome Email v3

### Steps To Reproduce

Run the Admin - Welcome Email v3 flow and it will fail. This is because the record Id used in the flow is not the record ID in the Customized Email table

**Comment by Jenefer-Monroe** [comment]
Hmmm... that is the correct GUID. Can you please validate that you dont have unmanaged layers on these two flows

- Admin | Sync Template v3 Configure Emails
- Admin | Sync Template v3 (Call Updates)

And run **_Admin | Sync Template v3 (Call Updates)_**

When **_Admin | Sync Template v3 Configure Emails_** completes, look at the table **_Customized Emails_** table. 
![image](https://user-images.githubusercontent.com/89584709/217889021-9cf05f49-3cd8-47a1-a69e-164fd56a5873.png)

**Comment by thso77** [comment]
This seems to have fixed the issue. Thanks!

**Comment by Jenefer-Monroe** [comment]
Oh wonderful news, thank you for confirming! 
We must have accidently changed that GUID when we changed the email system this month.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by MartijnSmeitinkJDE** [comment]
Just responding here to let you know I faced the same issue, and it seems resolved for me now as well.
