### ISSUE TITLE
[CoE Starter Kit - QUESTION] Missed to install Creator Kit - Cant upgrade Core Components 3.56 to 4.3

### ISSUE THREAD

**Issue by R4RD0** [microsoft/coe-starter-kit#4765]
### Describe the issue

I'm getting an "Import failed due to missing dependencies for Center of Excellence - Core Components" when trying to upgrade 3.56 to 4.3
Clicking show dependencies show me all dependencies. 

### Expected Behavior

upgrade to be sucessful

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

-

### Anything else?

[log.txt](https://github.com/microsoft/coe-starter-kit/files/10699935/log.txt)

**Comment by manuelap-msft** [comment]
Looks like you missed to import the Creator Kit components solution - since December, the CoE kit has a dependency on the Creator Kit
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-creator-kit

**Comment by R4RD0** [comment]
Thanks, I ended up rebuilding everything in a new environment instead.
