### ISSUE TITLE
[CoE Starter Kit - How to Show and Export Cloud Flow Complexity

### ISSUE THREAD

**Issue by IonB1977** [microsoft/coe-starter-kit#4766]
### Describe the issue

Hi there,
We are using the CoE kit and we can see all environments/flows with the Power BI dashboard.
We re using:
CoE - Core components 3.37
CoE - Audit Logs 2.10

We are trying to see more custom reporting with in Power Bi dashboard.
I'm asking if there's any way to produce somehow reports for flows. With using complexity score maybe (for example something like - greater then 5) along with their owners? 
Looking at the filters available, we can't sort by complexity for out of box options.

See attached images.

Or any other types or reports to custom make?

Hope it makes sense of what I'm asking. Please let me know if any other info is required.

Thanks,
Ion

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.38

### What app or flow are you having the issue with?

N/A - All Flows working fine

### Anything else?

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/110121301/217905674-44cd2c56-dd85-4b8e-bc7a-6c4b93e51079.png)
![MicrosoftTeams-image-v1](https://user-images.githubusercontent.com/110121301/218192253-3779d72c-4249-412b-94c5-915b78fc7f27.png)

**Comment by Jenefer-Monroe** [comment]
Hello, these are custom measures that were added to the Flow table in PBI only. So you can use those to create specific tables or reports if you would like. We are not staffed to assist with customizations unfortunately as we are a very small team. But hopefully this gets you started. 

Here I've highlighted as an example the FlowStateScore which is based on its state
![image](https://user-images.githubusercontent.com/89584709/218219435-f0fbd597-017d-4b86-a790-ecf83720dae7.png)

**Comment by IonB1977** [comment]
Perfect, thank you very much. 
I understand the limitation, just wanted to know if possible. We will try to play with the  info you provided.
Thanks a lot again.
Ion

**Comment by Jenefer-Monroe** [comment]
Happy to help! Closing out as no further action for starter kit team
