### ISSUE TITLE
[CoE Starter Kit - BUG] Missing 'CoE Audit Logs require smaller chunks' email from Customized Email Table - Documentation on "configure all" option

### ISSUE THREAD

**Issue by BenUnlox** [microsoft/coe-starter-kit#4771]
### Describe the issue

Since upgrading to V3.3. of the Audit Log solution, we have seen several instances where the '[Child] Admin | Sync Logs' flow has failed. The failure always occurs on the 'Get a row by ID' action within the 'Get Row - Send notice of required chunking' scope:

![1](https://user-images.githubusercontent.com/108944628/218077109-7a1be8a0-8755-4ce8-a4fa-9346d7fa4631.jpg)

When we check the 'Customised Emails' table, the 'Reduce Chunking Size' email appears to be missing altogether as opposed to the '[Child] Admin | Sync Logs' Flow using the incorrect Row ID.

![2](https://user-images.githubusercontent.com/108944628/218077856-373e7b87-5e3a-410e-875f-83af6da0b100.jpg)

### Expected Behavior

The '[Child] Admin | Sync Logs' has been reworked in this release, but in the past we would expect the below email to be sent in the event that the chunking needs to be further reduced:

![3](https://user-images.githubusercontent.com/108944628/218078151-0163a228-6866-4ee0-80bb-56154596abae.jpg)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

1. Increase chunking size to trigger the 'Get Row - Send notice of required chunking' scope of the '[Child] Admin | Sync Logs' flow.
2. Start the 'Admin | Sync Audit Logs' parent Flow.
3. Wait for failures on the '[Child] Admin | Sync Logs' flow.

or

1. Check the 'Customised Emails' and try to locate a Row with the ID of 'f1251799-2a86-ed11-81ac-0022480813ff'.

**Comment by manuelap-msft** [comment]
If you've not used the Setup Wizard for setup, you'll have to re-run the **Admin | Sync Template v3 Configure Emails** manually to populate the new email templates.

**Comment by BenUnlox** [comment]
@manuelap-msft Thanks - that has resolved the issue. We did run the 'Admin | Sync Template v3 Configure Emails' flow after the upgrade but without enabling the 'ConfigureAll' toggle - could the documentation be updated to account for this? Apologies if it's already there and I've missed it.

**Comment by Jenefer-Monroe** [comment]
Yes that was it. that needs toggled on. Will mark this as a documentation bug.
