### ISSUE TITLE
[CoE Starter Kit - BUG] Apps, Flows, etc not mapped to Maker.

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#4772]
### Describe the issue

This is a continuation from **[CoE Starter Kit - BUG] Apps and Flows are not mapped to an environment. #4608**.

As per checking there are several objects that are not mapped to a specific Maker.
This happens in the following:
1. Overview - Power Apps
2. Overview - Power Automate
3. Overview - Chatbots
4. Overview - Solution
5. Overview - Business Process Flows
6. Overview - AI Builder Models
7. Environments
8. Makers By Country
9. Makers By City

![Power Apps](https://user-images.githubusercontent.com/119695189/218093255-e121ac89-fc64-4887-92d6-54c0b10a9980.png)
![Power Automate](https://user-images.githubusercontent.com/119695189/218093253-e432eb5d-9984-4275-b2f5-37fba75fe621.png)
![Environments](https://user-images.githubusercontent.com/119695189/218093247-5c654ad1-947a-47f3-b94a-f94206cd57d6.png)
![Makers By Country](https://user-images.githubusercontent.com/119695189/218093217-6beb2a64-acb1-44fd-adcc-694550ec25b8.png)

I already applied the following steps but I'm still seeing the issue:
1. Changed the **Modfied Date** to **1/1/1990** and run the **Admin | Sync Template V3**
2. Ran a **Full Inventory**

### Expected Behavior

Objects are mapped to Maker.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template V3

### Steps To Reproduce

1. Open Power Platform BI Dashboard.
2. Open the following tabs
- Overview - Power Apps
- Overview - Power Automate
- Overview - Chatbots
- Overview - Solution
- Overview - Business Process Flows
- Overview - AI Builder Models
- Environments
- Makers By Country
- Makers By City

**Comment by Jenefer-Monroe** [comment]
Sorry for the delay. I did manage to find a test envt with this repro, and a full inventory did fix it. So can we please try that again? I've noticed that the new feature where power automate flows pick up env variable changes automatically does not always work, so perhaps that is what happened. 

1. Using the CoE Admin Command Center, change the Env Var admin_FullInventory to yes
![image](https://user-images.githubusercontent.com/89584709/219867562-96826909-2e41-43b2-af72-df59a1bcc9b3.png)

2. Turn off these flows
- Admin | Sync Template v3 (Apps)
- Admin | Sync Template v3 (Flows)
- Admin | Sync Template v3 (Model Driven Apps)

![image](https://user-images.githubusercontent.com/89584709/219867828-2c0bc4ee-391c-4d7e-8b67-2eb7e2dae748.png)

3. Turn these flows back on

- Admin | Sync Template v3 (Apps)
- Admin | Sync Template v3 (Flows)
- Admin | Sync Template v3 (Model Driven Apps)

4. Go to the **_Admin | Sync Template v3_** flow and run it. 
![image](https://user-images.githubusercontent.com/89584709/219867999-07c78efa-db14-48ad-993b-fe2a65752be8.png)

5. Wait until all runs from the triggered Apps, Flows, Model Driven Apps are complete. 
Usually flows finish last so if you go to **_Admin | Sync Template v3 (Flows)_** > All runs
![image](https://user-images.githubusercontent.com/89584709/219868123-31cd27db-e794-416d-9b75-faf128a6deb1.png)
And then filter to Running, you can wait until that list is empty (probably a few hours)
![image](https://user-images.githubusercontent.com/89584709/219868153-62191c13-ceec-467c-b6e3-424c28d6aab2.png)

**Comment by Jenefer-Monroe** [comment]
Have you refreshed the PBI?
You should turn the Full Inventory switch back to No and turn those flows back off and on again to ensure the value takes. 
Then wait for these to complete.

**Comment by Jenefer-Monroe** [comment]
It looks like you are just too large for our sync flow architecture to do full inventory runs. Yes please cancel this long run, it will likely never complete. 
Turn full inventory back to no and reset those same flows (if you havent already)
Then turn everything back on to be running normally again. 

The good news is that we are very close to releasing our new architecture for large tenants. Come to [office hours](https://aka.ms/coeofficehours) to hear about it. And read here if you would like

- https://docs.microsoft.com/power-platform/admin/self-service-analytics
- https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

**Comment by Jenefer-Monroe** [comment]
Yes im afraid I dont have a good next step for you right now aside from the new architecture. What I believe to be the bug you hit is fixed by full inventory run and you are just too big for that. 

We will support upgrade of the kit from sync flow architecture (current) to data lake architecture (new), you will not lose the associated metadata that you have added to the kit. And apps and flows will no longer get their details from these sync flow but instead from the product data export features.

**Comment by Jenefer-Monroe** [comment]
Closing out as there is no further action other than the architecture shift.
