### ISSUE TITLE
[CoE Starter Kit - QUESTION] Does the February release provide all gov email/notification customization feature?

### ISSUE THREAD

**Issue by CDSSYW** [microsoft/coe-starter-kit#4773]
### What is your question?

Hi CAT team,

As there are some email/teams bot notification not being able to be customized in **Admin command center** in Jan release,
it it already available to **customize the email/notification from approvals/Emails from Inactivity notifications flows** in February release as the ticket https://github.com/microsoft/coe-starter-kit/issues/1683 has been closed? :)

 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

 Inactivity notifications flows

**Comment by Jenefer-Monroe** [comment]
Yes that's correct. That was one of our big ticket items for February. 
You can customize these from the new CoE Admin Command Center, another big ticket item :)
![image](https://user-images.githubusercontent.com/89584709/218103326-501fb033-a128-49f6-b4b3-c291a44a8a6b.png)

**Comment by CDSSYW** [comment]
Hi Jenefer! It's amazing, can't wait to update my CoE kit!, thanks for the update!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
