### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - App and flow Templates in CoE

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#4775]
### What is your question?

Is this possible to have a feature to store templates of Apps and flows in CoE?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Can you provide a little more information on your scenario so we can understand it?
Ex: What do the templates store for you? What are some example? Who are they for?

**Comment by manuelap-msft** [comment]
Is an app like the Template Catalog what you're looking for? https://learn.microsoft.com/en-us/power-platform/guidance/coe/nurture-components#template-catalog-page-in-nurture-apps---maker-app

It's pretty basic, but if that's what you're looking for and you have further requirements let us know and we can put that on our backlog
![image](https://user-images.githubusercontent.com/55705669/218145194-7375bef5-0251-4f8d-95bb-e5cba71c73b4.png)

**Comment by PPMini** [comment]
Thanks Manuela. Yes, the ask from customer was for a place in CoE to store the apps and flow templates which can then be shared to other users. I believe this is what the requirement is and our CoE tool kit is already taking care of it. Awesome.... :). Will post again on this thread if any further requirements I receive on this. Cheers....
