### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI related information is empty in CoE table

### ISSUE THREAD

**Issue by Gokul-JB** [microsoft/coe-starter-kit#4776]
### Describe the issue

I could not see Power BI related information in following tables of CoE, Please help me on this

1. Power BI Dataset
2. Power BI Report
3. Power BI Mashup Parameter

Do we have option to get Canvas App control information in any CoE table?, I could see only PowerApps name and connector details alone, Please help on this

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

### What app or flow are you having the issue with?

Power BI

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
