### ISSUE TITLE
Import PowerApps from Excel 

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#4778]
In the PowerApps tab of the COE there is an option to import from Excel. I want to update the Last Launch Dates for older runs which I have retrieved using Splunk.

Will the import replace all of the data? Will rows not included in the import get deleted? Will fields missing from the import get deleted? I just want to import a csv file which contains the AppID and the LastLaunchDate for those apps which don't show any prior launch in the COE and for those where the LastLaunch in the _COE_ is _older_ than what I get from Splunk (and so therefore incorrect). I believe this is caused by occasional failures of the audit log import.

Would it be possible to get direct access to the underlying table so that I can control exactly what I am doing?

**Comment by Jenefer-Monroe** [comment]
Hello that is a built in capability from the product, not a tool from the starter kit so I cannot advice on specifically what it will do. But my understanding is that it would add new row and fail for ones that are already there by primary key. 

The tables in the kit are available for data manipulation. If you go to your CoE Environment > Center of Excellence - Core Components > Tables, you will see all the tables listed. Select your table of interest (ex PowerApps Apps)

### Edit in browser
You can edit the table directly in the browser. Hit Edit to get to full screen, change the fields displayed, and edit directly inline.
![image](https://user-images.githubusercontent.com/89584709/218460347-bc8f66cb-9dfc-4f2d-b2ac-82dca89dc509.png)
![image](https://user-images.githubusercontent.com/89584709/218460559-484bf3c2-bd75-4b36-9ccb-8efe74fd40e4.png)
![image](https://user-images.githubusercontent.com/89584709/218460831-94c5a235-f99b-48c6-87e3-79bbfc90f694.png)

### Edit in Excel
Or if you have the [Microsoft PowerApps Office Add-In](https://learn.microsoft.com/en-us/power-apps/teams/edit-data-in-excel) you can open the table in Excel to manipulate.
![image](https://user-images.githubusercontent.com/89584709/218459077-3d358355-b09c-486a-8f99-7319683e07ea.png)

**Comment by RickKush** [comment]
Hi!

The PowerApps Apps table CoE Environment > Center of Excellence - Core Components doesn't contain the App Last Launched On column which is in the COE PowerApps Apps screen.

***@***.***


***@***.***


***@***.***


From: Jenefer Monroe ***@***.***>
Sent: Monday, February 13, 2023 7:46 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Import PowerApps from Excel (Issue #4778)


Hello that is a built in capability from the product, not a tool from the starter kit so I cannot advice on specifically what it will do. But my understanding is that it would add new row and fail for ones that are already there by primary key.

The tables in the kit are available for data manipulation. If you go to your CoE Environment > Center of Excellence - Core Components > Tables, you will see all the tables listed. Select your table of interest (ex PowerApps Apps)

Edit in browser

You can edit the table directly in the browser. Hit Edit to get to full screen, change the fields displayed, and edit directly inline.
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/218460347-bc8f66cb-9dfc-4f2d-b2ac-82dca89dc509.png__;!!May37g!JZp_XFacpegCzlkQRKlj6xg7embupulTk94B-rWoxPf4VBkRMiVbmKl9-gLc5Oz13_GpT7EP0LKYbljkOuB2-pN81w$>
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/218460559-484bf3c2-bd75-4b36-9ccb-8efe74fd40e4.png__;!!May37g!JZp_XFacpegCzlkQRKlj6xg7embupulTk94B-rWoxPf4VBkRMiVbmKl9-gLc5Oz13_GpT7EP0LKYbljkOuDZC9QWUg$>
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/218460831-94c5a235-f99b-48c6-87e3-79bbfc90f694.png__;!!May37g!JZp_XFacpegCzlkQRKlj6xg7embupulTk94B-rWoxPf4VBkRMiVbmKl9-gLc5Oz13_GpT7EP0LKYbljkOuAZGTo36A$>

Edit in Excel

Or if you have the Microsoft PowerApps Office Add-In<https://urldefense.com/v3/__https:/learn.microsoft.com/en-us/power-apps/teams/edit-data-in-excel__;!!May37g!JZp_XFacpegCzlkQRKlj6xg7embupulTk94B-rWoxPf4VBkRMiVbmKl9-gLc5Oz13_GpT7EP0LKYbljkOuDV5Yzo0Q$> you can open the table in Excel to manipulate.
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/218459077-3d358355-b09c-486a-8f99-7319683e07ea.png__;!!May37g!JZp_XFacpegCzlkQRKlj6xg7embupulTk94B-rWoxPf4VBkRMiVbmKl9-gLc5Oz13_GpT7EP0LKYbljkOuAEmO4tWg$>

-

**Comment by RickKush** [comment]
Sorry, I was looking under "L" for Last Launched Date, but it is under "A"


From: Kushner, Rick [USA]
Sent: Monday, February 13, 2023 4:52 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [External] Re: [microsoft/coe-starter-kit] Import PowerApps from Excel (Issue #4778)

Hi!

The PowerApps Apps table CoE Environment > Center of Excellence - Core Components doesn't contain the App Last Launched On column which is in the COE PowerApps Apps screen.

***@***.***


***@***.***


***@***.***



From: Jenefer Monroe ***@***.******@***.***>>
Sent: Monday, February 13, 2023 7:46 AM
To: microsoft/coe-starter-kit ***@***.******@***.***>>
Cc: Kushner, Rick [USA] ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [External] Re: [microsoft/coe-starter-kit] Import PowerApps from Excel (Issue #4778)


Hello that is a built in capability from the product, not a tool from the starter kit so I cannot advice on specifically what it will do. But my understanding is that it would add new row and fail for ones that are already there by primary key.

The tables in the kit are available for data manipulation. If you go to your CoE Environment > Center of Excellence - Core Components > Tables, you will see all the tables listed. Select your table of interest (ex PowerApps Apps)

Edit in browser

You can edit the table directly in the browser. Hit Edit to get to full screen, change the fields displayed, and edit directly inline.
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/218460347-bc8f66cb-9dfc-4f2d-b2ac-82dca89dc509.png__;!!May37g!JZp_XFacpegCzlkQRKlj6xg7embupulTk94B-rWoxPf4VBkRMiVbmKl9-gLc5Oz13_GpT7EP0LKYbljkOuB2-pN81w$>
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/218460559-484bf3c2-bd75-4b36-9ccb-8efe74fd40e4.png__;!!May37g!JZp_XFacpegCzlkQRKlj6xg7embupulTk94B-rWoxPf4VBkRMiVbmKl9-gLc5Oz13_GpT7EP0LKYbljkOuDZC9QWUg$>
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/218460831-94c5a235-f99b-48c6-87e3-79bbfc90f694.png__;!!May37g!JZp_XFacpegCzlkQRKlj6xg7embupulTk94B-rWoxPf4VBkRMiVbmKl9-gLc5Oz13_GpT7EP0LKYbljkOuAZGTo36A$>

Edit in Excel

Or if you have the Microsoft PowerApps Office Add-In<https://urldefense.com/v3/__https:/learn.microsoft.com/en-us/power-apps/teams/edit-data-in-excel__;!!May37g!JZp_XFacpegCzlkQRKlj6xg7embupulTk94B-rWoxPf4VBkRMiVbmKl9-gLc5Oz13_GpT7EP0LKYbljkOuDV5Yzo0Q$> you can open the table in Excel to manipulate.
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/218459077-3d358355-b09c-486a-8f99-7319683e07ea.png__;!!May37g!JZp_XFacpegCzlkQRKlj6xg7embupulTk94B-rWoxPf4VBkRMiVbmKl9-gLc5Oz13_GpT7EP0LKYbljkOuAEmO4tWg$>

-

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
