### ISSUE TITLE
[CoE Starter Kit - BUG] Ribbon actions like delete flow do not show up when I select more than one flow

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#4779]
### Describe the issue

Hallo,

I've updated the Stater Kit Core to 4.3 and expected to to have the announced options (https://github.com/microsoft/coe-starter-kit/issues/4519) like delete, but they are missing
![image](https://user-images.githubusercontent.com/113470539/218431242-b9424963-0dc5-4b82-b3d1-2f6b0565a16c.png)
Did I miss to configure something?

### Expected Behavior

to have these options
![image](https://user-images.githubusercontent.com/113470539/218429764-dc180bc8-1e87-4fef-8a74-487ee7e26cb1.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Hello. A few things to note about the ability to perform these things from the grid view

1. You cannot perform them on more than one object at a time. So in your first picture you have 2 flows selected, the options will only show if a single flow is selected. There are some commands we are awaiting before we can support this. 
![image](https://user-images.githubusercontent.com/89584709/218457086-888b7169-4f89-4eaa-94d4-018a8fcb2230.png)

2. There is also a delay sometimes after you first load the app. Where selecting the object in the grid does not update the ribbon. The product team is aware of this delay and hopefully it will resolve soon. 

Hope that is helpful

**Comment by lukas-nC** [comment]
Thanks for the quick response
1. Multiselect like in Set Flow Permissions App would be great

**Comment by Jenefer-Monroe** [comment]
totally agree! Once this is possible with the pending product feature we will update to support! :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
