### ISSUE TITLE
What is the significance of Environment variables such as FullInventory and Power Platform Make Office 365 Group?

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#478]
Hello,

As "FullInventory" and "Power Platform Make Office 365 Group" environment variables are the part of "CoE Core" ( 2.1.6 ) version - Would you please share the significance of the same? in which components they are being utilized?

![image](https://user-images.githubusercontent.com/13658386/119479090-4b01a680-bd1e-11eb-8754-a23c14116909.png)

Thanks and Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

our Environment Variables are explained in our documentation: 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables

If the docs are insufficient and you have further questions, could you let us know what specificially is unclear so we can improve our docs?

Thank you
Manuela

**Comment by DiptiC-InsightRun** [comment]
Hello Manuela,

Thanks for sharing them, yesterday I could not see these variables in the CoE docs - Now it's all clear.

We can close this now!

Best Regards,
Dipti
