### ISSUE TITLE
[CoE Starter Kit - BUG] Failed to import Admin Task Analysis

### ISSUE THREAD

**Issue by orjsol** [microsoft/coe-starter-kit#4780]
### Describe the issue

Failed to import "admintaskanalysis_core_1.0.20221206.1_managed" 

Error msg:

Solution "Power Platform Administration Planning" failed to import: Cannot add a Root Component pcat_Admintasks of type 80 because it is not in the target system.

![image](https://user-images.githubusercontent.com/52534802/218446527-ca470936-9d09-4dac-a1ba-0c96ca15dc33.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Newest - February Release

### What app or flow are you having the issue with?

Import of solution

**Comment by orjsol** [comment]
Hi. Thanks for the quick reply. It now imported successfully

![image](https://user-images.githubusercontent.com/52534802/218471815-69822bd2-c24b-4a0b-992d-a90cc73e9090.png)

**Comment by manuelap-msft** [comment]
Wonderful, thanks for confirming - I've updated the published Release as well, and we'll add some extra checks for this solution for our next release! Thanks for letting us know about the issue!

**Comment by davidfeldman-coop** [comment]
I also ran into this issue and the update file worked for me as well.
