### ISSUE TITLE
[CoE Starter Kit - BUG] Missing menue buttons in CoE Admin Command Center

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#4782]
### Describe the issue

Hello, 

I installed the latest version of the Core Component. It seems like there is somethng wrong with the new COE Adin Command Center App. The navigations seems incomplete.
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/62603605/218483140-021d7172-d139-46da-881d-789d6868c42c.png">
It would be great to get help with this :)

Best regards Cathi

### Expected Behavior

<img width="78" alt="image" src="https://user-images.githubusercontent.com/62603605/218483227-d0e2c65e-5c39-4702-88b8-ed7dddf2a8ca.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.

### What app or flow are you having the issue with?

CoE Admin Command Center

**Comment by manuelap-msft** [comment]
Hello,

we've seen this happen before when the English language pack was not installed in the Environment - then the navigation in the Model Driven app doesn't pick up the right groups. You'll have to add the English language pack to the environment to solve this: https://learn.microsoft.com/en-us/power-platform/guidance/coe/limitations#supported-languages

Note, the CoE kit is not multi-lingual and only English is supported.

**Comment by Cathi029** [comment]
Hello Manuela, 

all right, thank yout for you fast response! So I have to delete the Solution and then import it after aktivation the english language pack.
I tried to delete the solution earlier this day and got a timeout error, so is it possible that the solution can not be deleted?

**Comment by manuelap-msft** [comment]
It can be deleted, sometimes we've seen the timeout error but the delete will still be running and if you check back later the solution will be gone.

We've not tested the behaviour, you may be able to add the English language pack after install and set it as a default language and then it may work. But the recommendation would be to create an environment and select English as language there from the beginning.

Hope that helps,
Manuela

**Comment by Cathi029** [comment]
Yes thank you very much, it is working now! (but i had to install the solution again)
