### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin-Sync V3 Template  flow is failing for renamed envt

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4785]
### What is your question?

We have installed CoE Core components in one environment  and environment URL is "'orgUrl.crm4.dynamics.com''." and all flows ran successfully..

Later we have updated the environment URL to "CoEdev.dynamics.com" and Admin-Sync V3 Template  flow started failing 

Action 'List_Makers' failed
_Http request failed with status code 'NameResolutionFailure' and status message: 'The remote name could not be resolved: 'orgUrl.crm4.dynamics.com''._

as per my understanding , it was looking for old url and failing there.

I am looking for help for a quick help

Thanks in advance 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin-Sync V3 Template

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. Sometimes this flow caches the old envt names somewhere. If you turn the Admin-Sync V3 Template flow off and back on, it should clear that cache and pick up the new name.

**Comment by pamatihyd** [comment]
I have turned off and on the flow  Admin-Sync V3 Template

From then the flow is running for long time it took 24 hrs still running . another flow started running and its also running since long time 

It has paused here Store Environments in CoE Environment 

![image](https://user-images.githubusercontent.com/29652263/218972442-d7b7ab9e-f42e-446d-9e9e-4aa3e21f0d46.png)

Please suggest if any action I can take here

**Comment by Jenefer-Monroe** [comment]
You have a lot of environments and so this will take a while to run. Are you saying that it ran more quickly before this?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
