### ISSUE TITLE
[CoE Starter Kit - BUG] Error When opening canvas app Detail in the Developer Compliance Centre

### ISSUE THREAD

**Issue by JaseRuss** [microsoft/coe-starter-kit#4786]
### Describe the issue

![image](https://user-images.githubusercontent.com/46083341/218510753-14ab51c3-2a08-4a52-ae74-66bc07079d60.png)

### Expected Behavior

No Error

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.6

### What app or flow are you having the issue with?

Developer Compliance Centre

### Steps To Reproduce

Open DCC 
Navigate to Canvas Apps Section
Click on a App to see the detail page - Error appears

### Anything else?

I've actually figured out where this comes from :D

![image](https://user-images.githubusercontent.com/46083341/218512086-03b4066d-4717-44f2-ba78-ccfa5bb4aea8.png)

It's the fill for the Icon on the detail page, it needs to be capitalised RGBA for the inner substitute.

Original:

If(!IsBlank(vSelectedAppN.'Icon Background Color'),
RGBA(
Value(First(Split(Substitute(Substitute(vSelectedAppN.'Icon Background Color', "rgba(", ""), ")", ""), ", ").Result).Result),
Value(Last(FirstN(Split(Substitute(Substitute(vSelectedAppN.'Icon Background Color', "rgba(", ""), ")", ""), ", ").Result, 2)).Result),
Value(Last(FirstN(Split(Substitute(Substitute(vSelectedAppN.'Icon Background Color', "rgba(", ""), ")", ""), ", ").Result, 3)).Result),
Value(Last(Split(Substitute(Substitute(vSelectedAppN.'Icon Background Color', "rgba(", ""), ")", ""), ", ").Result).Result)),RGBA(250,250,250,1))

Fixed:

If(!IsBlank(vSelectedAppN.'Icon Background Color'),
RGBA(
Value(First(Split(Substitute(Substitute(vSelectedAppN.'Icon Background Color', "RGBA(", ""), ")", ""), ", ").Result).Result),
Value(Last(FirstN(Split(Substitute(Substitute(vSelectedAppN.'Icon Background Color', "RGBA(", ""), ")", ""), ", ").Result, 2)).Result),
Value(Last(FirstN(Split(Substitute(Substitute(vSelectedAppN.'Icon Background Color', "RGBA(", ""), ")", ""), ", ").Result, 3)).Result),
Value(Last(Split(Substitute(Substitute(vSelectedAppN.'Icon Background Color', "RGBA(", ""), ")", ""), ", ").Result).Result)),RGBA(250,250,250,1))

 hope this helps

**Comment by manuelap-msft** [comment]
Thanks for not only spotting the issue but also providing a fix for us!! Really appreciate it - we'll fix that for the next release.

**Comment by manuelap-msft** [comment]
Fixed locally ready for the next release.
