### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by JCervantes789** [microsoft/coe-starter-kit#4789]
### Describe the issue

The **Request Orphaned Objects Reassigned (Parent)** flow is return the following error when trying to turn it on for the first time:

Flow client error returned with status code "NotFound" and details "{"error":{"code":"AzureResourceManagerRequestFailed","message":"Request to Azure Resource Manager failed with error: '{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Logic/workflows/6383043a-026f-660a-d0af-6f96526a8042' under resource group 'F2ED918414BE429BA4B356405DACCE51-CB900DE14047EC3683EF76C0FCEEE318-ENV' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}'."}}".

### Expected Behavior

Flow Turned on

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

### Steps To Reproduce

1. Power Apps Online Portal
2. Solutions
3. Center of Excellence - Governance Components
4. Cloud Flows
5. Request Orphaned Objects Reassigned (Parent)
6. Turn On
![image](https://user-images.githubusercontent.com/125293778/218544123-55c8b6fb-aec7-4fd7-8bca-1502eea3fcae.png)

**Comment by Jenefer-Monroe** [comment]
Strange. This sounds like some product issue has hit you. 

A few things to try
1. Turn off and back on the child flow (Request Orphaned Objects Reassigned (Child)) and then try turning this one on again
2. Try accessing through the https://flow.microsoft.com/ interface instead of https://powerapps.microsoft.com/

**Comment by JCervantes789** [comment]
Hello,

I've tried toggling Off/On the Child Flow and reactivating both of them from the Power Apps and Power Automate interfaces but received the same error:

Flow client error returned with status code "NotFound" and details "{"error":{"code":"AzureResourceManagerRequestFailed","message":"Request to Azure Resource Manager failed with error: '{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Logic/workflows/6383043a-026f-660a-d0af-6f96526a8042' under resource group 'F2ED918414BE429BA4B356405DACCE51-CB900DE14047EC3683EF76C0FCEEE318-ENV' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}'."}}".

![image](https://user-images.githubusercontent.com/125293778/221026867-182ddbfe-f9d8-442d-a456-2dfd0411213c.png)

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
