### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by LucasGiovaniSilva25** [microsoft/coe-starter-kit#4792]
### Describe the issue

When we go to update the report we get the following error:

Erro de fonte de dados: {"error":{"code":"ModelRefresh_ShortMessage_ProcessingError","pbi.error":{"code":"ModelRefresh_ShortMessage_ProcessingError","parameters":{},"details":[{"code":"Message","detail":{"type":1,"value":"Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."}}],"exceptionCulprit":1}}}
Cluster URI: WABI-SOUTH-CENTRAL-US-redirect.analysis.windows.net
ID da atividade: 8d9f95f9-3b5f-4b8e-b89e-92a4e5900393
Solicitar ID: 5c250a53-dfab-2e40-48a6-3a3ad8bc55dc
Hora: 2023-02-01 14:52:29Z

![image](https://user-images.githubusercontent.com/125303990/218571163-3b262b03-e414-4299-a03b-b7366636eca0.png)

This is a report provided by Microsoft itself – CoE.

### Expected Behavior

We expected the report to update normally, as we are using an API provided by Microsoft itself: https://flow.microsoft.com/pt-br/blog/advanced-power-automate-rpa-run-log-analytics-with-power-bi-and-dataverse/

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

08/02/2023

### What app or flow are you having the issue with?

Advanced Power Automate RPA run log analytics with Power BI and Dataverse

### Steps To Reproduce

1. Connect to dataverse API;
2. Login with the user;
3. I publish the report;
4. I click in update.

**Comment by manuelap-msft** [comment]
Hello,

the Automation CoE kit is managed in a different GitHub repo, please raise your issue there for the team to triage:
https://aka.ms/automation-kit-issues

Thank you
Manuela

**Comment by Grant-Archibald-MS** [comment]
@LucasGiovaniSilva25 checking if this issue is related to https://learn.microsoft.com/power-automate/desktop-flows/monitor-desktop-flow-runs Power BI report

**Comment by Grant-Archibald-MS** [comment]
Closing issue waiting for confirmation that related to Automation Kit.
