### ISSUE TITLE
[CoE Starter Kit - BUG] How to modify environment variables 

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#4793]
### Describe the issue

I am getting following error message -

"This environment variable definition cannot be edited because it is in a managed solution."

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Dec 2022 

### What app or flow are you having the issue with?

All env variables in core / gov solution

**Comment by Jenefer-Monroe** [comment]
Hello, please see this article on how to [update environment variables](https://learn.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables)

Note that you can do it directly in the product without our tooling as described here:
![image](https://user-images.githubusercontent.com/89584709/218577206-c67b56b1-e5cd-4103-89b0-42c6d8090f16.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
