### ISSUE TITLE
[CoE Starter Kit - FEATURE] DLP Editor - show clearly when no apps are impacted

### ISSUE THREAD

**Issue by edarcy87** [microsoft/coe-starter-kit#4794]
### Describe the issue

When using the DLP Editor, the app does not show when there are no impacted apps. Or, should I say, the screen isn't clear that there are no impacted apps:

![image](https://user-images.githubusercontent.com/124092704/218584042-16a1bf20-d60a-40b5-ad81-860841c653f9.png)

### Expected Behavior

As a user, I find this current (if expected functionality) confusing. If no apps/flows are impacted, then the screen should reflect that.

![image](https://user-images.githubusercontent.com/124092704/218584396-3bb697d4-820c-46de-9c46-6afa1c25ad51.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

DLP Editor V2

### Anything else?

Wasn't sure if this was a bug or expected behaviour. Thank you for all your hard work on this!

**Comment by manuelap-msft** [comment]
Thanks for the idea, added as a feature ask to our backlog! The logic the DLP Editor performs to figure out impact is pretty complicated, and some actions are performed at design time in a way to avoid delegation issues and thus make it difficult to show the number of impacted apps/flows or if there are none but we'll see what we can do.

**Comment by manuelap-msft** [comment]
Unfortunately with the limitations of the platform and delegation, this is not possible today.
