### ISSUE TITLE
[CoE Starter Kit - QUESTION] CanvasAppOperations flow operation  Make Owner in Orphaned apps not work

### ISSUE THREAD

**Issue by maikletal** [microsoft/coe-starter-kit#4796]
### Describe the issue

``I'm using the Power App "Set App Permissions" to assign a new owner to the applications that are in the "Orphaned App" section but the flow "HELPER - CanvasAppOperations" throws the following error: 

`Error from token exchange: Permission denied due to missing connection ACL: Connection https://europe-002.azure-apim.net/@europe-002/logicflows/0256d4d5-8442-eaea-7fab-ff563b70ffe8 version -9223372036854775808, connection=europe-002/powerappsforadmins/cf1e1155d8fd41eb8215213f388a29c8`

![image](https://user-images.githubusercontent.com/44426740/218716122-c26c7d50-f916-450c-bd18-356b112d9a5a.png)

### Expected Behavior

The expected result is that the application has the selected owner.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Set App Permissions (PowerApp) and HELPER - CanvasAppOperations (flow)

### Steps To Reproduce

1. In CoE Environment open Set App Permissions App
2. Go to Orphaned App section
3. Enter in any orphaned app listing
4. Try to make owner to existing user or triying to add new user with viewer role.

![image](https://user-images.githubusercontent.com/44426740/218719259-7249c027-6105-45bb-877a-f016c151e93c.png)

**Comment by Jenefer-Monroe** [comment]
Hello. you may need to update the run only users properties on the child flow. Please see: 
https://learn.microsoft.com/power-platform/guidance/coe/faq#set-flow-run-only-users-properties

**Comment by maikletal** [comment]
Hello. I don't have managed layers in that flow and I already had the connections included, but it doesn't work.
![image](https://user-images.githubusercontent.com/44426740/220056741-7b9a64cb-0d7b-4002-b174-14862a2a35b1.png)
![image](https://user-images.githubusercontent.com/44426740/220057183-f765914f-bd6d-4ccf-83ce-db3e42d1d5eb.png)

**Comment by maikletal** [comment]
It's permanent 
![image](https://user-images.githubusercontent.com/44426740/220150314-49fef0c4-53dc-4bc3-acba-7749ec5a92f9.png)

**Comment by Jenefer-Monroe** [comment]
Its strange that the casing is different for the connector in question, I've not seen that before. 
![image](https://user-images.githubusercontent.com/89584709/220619266-d7a0564c-4a29-42b3-a170-5d8223c204bb.png)

Can you please check the flow connetions here, do they all show with the green check?
![image](https://user-images.githubusercontent.com/89584709/220619061-95455aab-828f-4ec6-a622-1a096cc9df32.png)
![image](https://user-images.githubusercontent.com/89584709/220619761-0ab4d054-e08d-4e53-9a14-a2aa0b7fab41.png)

Can you go to the default solution > Connection References > Find these

**Comment by maikletal** [comment]
I don't see "See all" option
![image](https://user-images.githubusercontent.com/44426740/220705445-8bdf1d65-a501-4e2f-8e82-2bd6fe287df8.png)
I review the references and I don't see errors
![image](https://user-images.githubusercontent.com/44426740/220706240-2500578b-d17b-45b8-8124-d55a72faaee4.png)
![image](https://user-images.githubusercontent.com/44426740/220706575-f70191d9-3d53-4afb-b400-9c85cd86f09b.png)

**Comment by maikletal** [comment]
Hello Jenefer,
I've been testing this morning and created a new connection, updated the reference in the solution and it worked. I don't know exactly what could be happening but now it works. Thanks for your help.

**Comment by Jenefer-Monroe** [comment]
Glad its resolved! I'll go ahead and close now but please reach out with new issues if you hit them!
