### ISSUE TITLE
[CoE Starter Kit - Feature]: Make mails look good with the Email Header and Logo

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#4797]
### Is your feature request related to a problem? Please describe.

Hello!
We were working in the Governance solution with two flows - 
1. _Admin | Inactivity notifications v2 (Start Approval for Flows)_
2. _Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created_.

After testing we saw that the _Admin | Inactivity notifications v2 (Start Approval for Flows)_ flow now has a nice email header and logo, so the users see them now in a nice way too.
However, while trying to test the _Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created_ flow, it does not show Email header and logo as the other flow.

### Describe the solution you'd like

Would that be possible to modify the _Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created_ flow, so that it also has these features as beautiful header and logo?
We created the custom copy of the flow and edited by ourselves, so that we can see the header as in the previous flows (Admin | Inactivity notifications v2 (Start Approval for Flows) flow). 
We checked the issues #1477 and #2004. In the custom flow we have the similar situation that with the Email Header Style variable we have big header: 
![image](https://user-images.githubusercontent.com/113427788/218738698-1916696c-20f6-4530-974c-4bee63f8caa5.png)
However, if we are using the CoE flow without modifying it, the user can see email like this without beautiful header/logo:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/113427788/218738545-4a50af13-169c-4560-b15a-0e86936666c2.png">

We have created our new custom Email header variable to make the header smaller. However, we do not want to have the custom environment variable, so that there will not be a mess in the future. That is why we still would like to have the same features in the original OOB flow as it has the _Admin | Inactivity notifications v2 (Start Approval for Flows)_ flow.

**Comment by Jenefer-Monroe** [comment]
Hello. We have streamlined all the mails in the kit to use the same header and such via some helper work starting in the new release Feb 2023 (Core 4.3) https://github.com/microsoft/coe-starter-kit/releases/latest

I believe that will resolve it for you.

**Comment by JanetK12** [comment]
Ok! Will look! Thank you very much!

**Comment by Jenefer-Monroe** [comment]
Glad to help! Closing out as no further action for starter kit team
