### ISSUE TITLE
[CoE Starter Kit - BUG] SR issue in v 4.2

### ISSUE THREAD

**Issue by jwstl** [microsoft/coe-starter-kit#4801]
### Describe the issue

Left navigation menu not visible to all authorized users. 
All users have been assigned the Power Platform Admin role in the CoE environment, and the Power Platform Admin canvas app has been shared with the users. All users are using the same OS (Win 11), and browser (MS Edge). Adding/removing roles confirms access.
[2023-01-30_18-28-00](https://user-images.githubusercontent.com/2245529/218810870-36e40d1b-7b05-4de0-8d49-aa20336cb0cc.png)

### Expected Behavior

the left navigation should be visible to all authorized users.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

Power Platform Admin View

### Steps To Reproduce

1. grant Power Platform Admin SR role in CoE environment
2. grant Power Platform Admin SR role in canvas app
3. open url to Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Can you please clarify what version of Core you are using? You show version 1.7 but that is probably not correct. 
You can find this by going to the Solutions screen in your CoE environment
![image](https://user-images.githubusercontent.com/89584709/218812737-fb1511ab-38cc-4bfe-a4a1-110110e8c7ea.png)

**Comment by jwstl** [comment]
Version 4.2 for Core Components and Version 3.3 for Governance Components

**Comment by Jenefer-Monroe** [comment]
ok thank you. As part of the Feb release (v 4.3) we did a pass on the SR's and as I know we did explicitly test the PP Admin View. 
Please let us know your experience after your next upgrade as a result

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
