### ISSUE TITLE
[CoE Starter Kit - BUG] App catalog is throwing error while playing this app.

### ISSUE THREAD

**Issue by madhavanbino** [microsoft/coe-starter-kit#4803]
### Describe the issue

While accessing "App Catalog" app in the Core solution, it throws the following error.

PowerAppsforAppMakers.GetConnectors failed: { "error": { "code": "ServiceToServiceEnvironmentNotFound", "message": "The environment 'Default-******************' could not be found in the tenant '***********'." } 

Tried clearing the cache multiple times also made sure that the user is having the permission in the default environment.

### Expected Behavior

App catalog app should be opened without any issues.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

App Catalog

**Comment by Jenefer-Monroe** [comment]
Hello. I dont repro this is the current release (Feb 2023, v 4.3) so I presume there was a bug in the past that is impacting you. 
Your current version is Nov 2022 (v 3.56) so I recommend you to upgrade to the latest release to get the current version with this fixed.

**Comment by madhavanbino** [comment]
I have the same version installed in a different env in a different Tenant and its perfectly working fine there, so I assume this is not related to the version. Is there any other settings i need to verify? 

Since the error says PowerAppsforAppMakers.GetConnectors is causing the issue, is this something needed to be checked with the PowerAppsforAppMakers connector? We have different DLP policies set up in the env where coe toolkit installed and in the Default environment.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
