### ISSUE TITLE
[CoE Starter Kit - BUG] It looks like this app isn't compliant with the latest data loss prevention policies.

### ISSUE THREAD

**Issue by aachanta3** [microsoft/coe-starter-kit#4804]
### Describe the issue

Hi, 
I am trying to install CoE starter kit Core components solution.
The solution imported successfully into one of my sandbox envrionment but I am unable to configure the initial setup due to the error below - 

![CoEError](https://user-images.githubusercontent.com/125409007/218870519-96c2982d-3c5a-4395-936c-2606fe697059.PNG)

### Expected Behavior

I added my sandbox instance to the CoE DLP policy and tried the install but it is failing
Expected behavior - I will be presented with a wizard to configure the initial setup with environment variables

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CoreComponents

### Steps To Reproduce

1) I imported the Core components solution to one of my sandbox instance
2) Import was successful
3) added environment to the CoE DLP which has all the connectors
4) Opened the CoE setup wizard app
5) See error "Error Code: AppForbidden
Session Id: 5f8a841c-22e1-4a5c-bafb-3eaffc114d55
Activity Id: 32de11fa-3dd3-4faa-bbf0-ac0cadc568d0
Timestamp: Tue Feb 14 2023 16:45:14 GMT-0500 (Eastern Standard Time)
It looks like this app isn't compliant with the latest data loss prevention policies.
UciError: It looks like this app isn't compliant with the latest data loss prevention policies. at s (https://cder-aois-dev.crm9.dynamics.com/uclient/scripts/app.js?v=1.4.5233-2212.3:4906:82) at https://cder-aois-dev.crm9.dynamics.com/uclient/scripts/custompage.js?v=1.4.5233-2212.3:36:6614"

### Anything else?

Error Code: AppForbidden
Session Id: 5f8a841c-22e1-4a5c-bafb-3eaffc114d55
Activity Id: 32de11fa-3dd3-4faa-bbf0-ac0cadc568d0
Timestamp: Tue Feb 14 2023 16:45:14 GMT-0500 (Eastern Standard Time)
It looks like this app isn't compliant with the latest data loss prevention policies.
UciError: It looks like this app isn't compliant with the latest data loss prevention policies. at s (https://cder-aois-dev.crm9.dynamics.com/uclient/scripts/app.js?v=1.4.5233-2212.3:4906:82) at https://cder-aois-dev.crm9.dynamics.com/uclient/scripts/custompage.js?v=1.4.5233-2212.3:36:6614

**Comment by Jenefer-Monroe** [comment]
Hello. this indicates that your tenants DLP policies are not correctly configured for the kit. You will need to review the documentation again here: [Validate data loss prevention (DLP) policies](https://learn.microsoft.com/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies)

Remember that DLP policies are additive, so if another policy that is more restrictive applies, it will be blocked.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by VicariouslyAwesome** [comment]
Hi, Umm.. I facing the same issue. I have have checked all the DLP policies that I dont see my environment in any of them. 

I am getting the error as :

Error Code: AppForbidden
Session Id: bfcc4f13-bae7-4269-9161-d8cff9afbfcb
Activity Id: a78407da-b23e-4565-b634-dde726ca1ded
Timestamp: Tue Apr 23 2024 12:45:40 GMT+0200 (Central European Summer Time)
It looks like this app isn't compliant with the latest data loss prevention policies.
UciError: It looks like this app isn't compliant with the latest data loss prevention policies. at s (https://content.powerapps.com/resource/uci-infra/scripts/app.0c23b21d5f238c6fbdee5d56068959c2.js:33:958227) at https://content.powerapps.com/resource/uci-infra/scripts/custompage.dd43ddf447c2b3d7c319d2a9013cf51e.js:4:24685

<img width="1219" alt="Screenshot 2024-04-23 at 2 26 37 PM" src="https://github.com/microsoft/coe-starter-kit/assets/167870278/3abd77b5-ee6f-4a6d-99d5-3461e6db4e11">


followed the steps as mentioned here :

https://learn.microsoft.com/en-gb/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

**Comment by PyHatTech** [comment]
Same here. DLP policy is configured correctly and I'm using the identity that installed the kit. Found a thread here where it was mentioned that we should include "HTTP with Microsoft Entra ID (preauthorised" while this isn't mentioned in the documentation. Now searching for other posts of this issue and ended up here. The error doesn't point towards any specific connector, which is very helpful with troubleshooting. Lots of customers probably just remove the DLP policy because they're tired of dealing with these type of issues.

**Comment by stevus1970** [comment]
I had the same issue, but managed to trace it to the Dataverse (Legacy) connector. Try including that in the "Business" category with the others as per the documentation.

**Comment by ManishaBhagat30** [comment]
I got this issue while playing admin and maker command center apps in a brand new installation. It was the Microsoft Entra Id connector, which when moved to business category solved the issue for me. 
Please include it in the documentation. Thank you
