### ISSUE TITLE
[CoE Starter Kit - BUG] Add Maker to Group

### ISSUE THREAD

**Issue by ccullum** [microsoft/coe-starter-kit#4805]
### Describe the issue

The Add Maker to Group workflow has an issue.  In the List group members, Inputs are now Team email addresses not the Group GUID.

### Expected Behavior

Pass the Group ID not the email address.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Add Maker to group

### Steps To Reproduce

![a](https://user-images.githubusercontent.com/49997994/218888243-cb7afa66-054e-48b6-8378-755c25def7fa.png)

### Anything else?

This was working before I updated.
![b](https://user-images.githubusercontent.com/49997994/218888515-6453304d-b560-455d-869c-de057c78480a.png)

**Comment by Jenefer-Monroe** [comment]
Hello, this is based off the environment variable. So perhaps it got the wrong value written to it when you upgraded? 

You can put it back to the GUID in the new CoE Admin Command Center
![image](https://user-images.githubusercontent.com/89584709/218890837-bb1eb4eb-f384-4131-bdd8-d159fae4b1da.png)

**Comment by ccullum** [comment]
Thank you @Jenefer-Monroe , I did not realize I had changed it when doing the update.  Sorry to bother you with a non-bug.

**Comment by Jenefer-Monroe** [comment]
No problem, glad to help! I'll go ahead and close out but please let us know if you need any other assistance.
