### ISSUE TITLE
[CoE Starter Kit - BUG] Missing Apps/flows in CoE Toolkit

### ISSUE THREAD

**Issue by Sishira** [microsoft/coe-starter-kit#4809]
### Describe the issue

Within PowerBI Report, we are not finding apps and flows developed by Makers. We can see the same available in Makers - MyFlows/Apps but the same is not present in CoE Toolkit Report. No error on refreshing the dataset.

### Expected Behavior

All Apps from Makers should appear in CoE Toolkit PowerBI Report.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

Power BI Report

### Steps To Reproduce

1- Get the list of Apps from the maker power platform login
2- Try finding same name in BI Report

**Comment by Jenefer-Monroe** [comment]
Hello. First please note that we recommend [updating the CoE Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/after-setup) at least every 3 months as we are not able to keep in mind the state of kits older than that which makes debugging issues, including upgrade itself, difficult. 

For your issue. I didnt quite follow if you said you checked the tables themselves. 
Can you please check to see, does the data exist in the Power Platform Admin View app? 
![image](https://user-images.githubusercontent.com/89584709/219028321-5d2cd3bb-28e8-467b-a3f7-167f8b6bd1d0.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
