### ISSUE TITLE
[Power Platform communication site template] Deployment failed

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#4810]
### Describe your bug, question or feature ask.

we are getting error in deployment, even though we used Global Admin ID. 
![HubPnP](https://user-images.githubusercontent.com/106515181/218998603-5d12267e-8984-41a9-8e23-c627ae2c7c0b.JPG)

**Comment by ALSPowerPlatform** [comment]
Any update on this?

**Comment by Laskewitz** [comment]
@ALSPowerPlatform - Any update?

**Comment by manuelap-msft** [comment]
Closing out as no response received.
