### ISSUE TITLE
[ALM Accelerator - QUESTION] QUESTION - Experiencing error while committing from ALM accelerator from Power Platform App

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#4812]
### What is your question?

working with ALM for the first time , established and trying to get a sample solution commit and getting the below error :
<img width="753" alt="image" src="https://user-images.githubusercontent.com/112712553/219022967-d6a1516c-0089-42a3-af54-5c707e589891.png">

Please help me to understand why I am seeing this.

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

February

**Comment by mikefactorial** [comment]
@PPMini can you verify that the Custom Connector is working correctly per the steps here https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-preview#configure-the-devops-custom-connector?

Also, any more details about what steps lead to this error is occurring?

**Comment by PPMini** [comment]
Thanks Mike for response. I have followed the process to setup the custom connector and I got the Status code 200 as well while testing. The only thing I noticed when was setting up the connector there was a change in Identity provider as "OAuth2.0" and other fields like Authorization URL, though I have changed the identity to Azure Active directory but couldn't see the field Login URL. So , I am not sure if that is the problem as I didn't have the LOgin URL field and I used the Authorization URL 
<img width="280" alt="image" src="https://user-images.githubusercontent.com/112712553/219116465-f7b0ba8c-16dc-4dcf-91ac-dca8834c71cb.png">

**Comment by PPMini** [comment]
Hi @mikefactorial , another thing I noticed in the commit wizard that I am not able to see the Based On field correctly:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/112712553/219332142-2ca51161-8a39-40b2-9ec9-1bf39d24e85f.png">

This field should actually show me a drop down box like below:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/112712553/219332580-7b62a9b3-4473-43f8-b475-42030748484b.png">


Any thoughts please.

**Comment by concoursdude** [comment]
@mikefactorial I think the docs posted re: the custom connector are no longer up to date. When first loading in the ALM solution and editing the custom connector, the identity provider is set to Generic Oauth2, which doesn't provide a Resource URL or Tenant ID field, as shown here (this screenshot is a first edit of a freshly imported ALM solution package). 

![image](https://user-images.githubusercontent.com/51216063/219494599-acb9618d-355d-42af-a3a2-20615296b723.png)

**Comment by mikefactorial** [comment]
@PPMini this looks like your repository in azure devops hasn't been initialized. Try going to the repo in question and initializing it manually this should create the main branch.

**Comment by mikefactorial** [comment]
@J3ffr0y3d looks to be a different issue. Need to make sure you've update the pipeline templates when you update the solution. There's a new parameter called CommitScope in the latest release of the pipeline templates.

**Comment by J3ffr0y3d** [comment]
ok thanks ill check, im sure i downloaded and updated the templates

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here.
