### ISSUE TITLE
[CoE Starter Kit - Code components reporting/monitoring] Does the CoE have any way to report on what code components are used and where

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#4813]
### What is your question?

MS support directed me to ask my questions here.
Looking to be able to monitor/report on what code components are imported and where in environments other than the CoE. Given the security warning for turning on code components, it would be good to be able to see what is being used and where. I am looking to understand the security concerns for enabling this (outside of the CoE environment). We have a request to turn this on for a few environments for devs to use items from the pcf gallery. Additionally, would an admin need to import these for the devs to use? It is not clear if the system customizer role allows them to do this. Or once code component framework is enabled, any maker can add things and use them?

What are the risks and ways to mitigate them for enabling the Power Apps component framework feature?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feburary 2022

### What app or flow are you having the issue with?

Component framework

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid Support may not have understood your question if they directed you to us. 

This product question would be better answered by area experts, which we are not. And is not specific to the kit. 
**_What are the risks and ways to mitigate them for enabling the Power Apps component framework feature?_**

If you cannot get answers from support, perhaps try the power community: https://powerusers.microsoft.com/

**Comment by pnoot7** [comment]
Thank you. I will reach back out to support.
