### ISSUE TITLE
Admin Command Centre App not launching correctly

### ISSUE THREAD

**Issue by vinnjosephtfgm** [microsoft/coe-starter-kit#4814]
### Describe the issue

We are getting this error after launching Admin Command Centre. The solutions we are using have been upgraded to the latest CoE release.
![image](https://user-images.githubusercontent.com/81636135/219061714-49980143-d865-41b1-bdef-ef479a5d3d43.png)

We have configured the env urls as required by the Command centre app. It was launching correctly till last week.

### Expected Behavior

The Admin Command Centre app should launch correctly.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin Command Centre App

**Comment by Jenefer-Monroe** [comment]
Hello, I've never seen that error message but it does seem to indicate some intermittent issue with your network.

**Comment by vinnjosephtfgm** [comment]
Hi 

I have fixed this issue.

Thanks
