### ISSUE TITLE
[CoE Starter Kit - Delete apps / flows directly from PP Admin View

### ISSUE THREAD

**Issue by Raz-786** [microsoft/coe-starter-kit#4819]
### Describe the issue

same issue was already registered by some other user under below URL
https://github.com/microsoft/coe-starter-kit/issues/4519

as per advised new Installation required, which i upgrade my Core Component from 4.2 to 4.3 still unable to see delete button when selected multiple flow to delete 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin View

### Steps To Reproduce

Got COE URL
Go to Flow
select Flow to delete but delete option not available

### Anything else?

![image](https://user-images.githubusercontent.com/116106952/219273811-bbb5b173-4893-4f6a-be78-89e0f49ab41f.png)
![image](https://user-images.githubusercontent.com/116106952/219273955-1b28000f-f41e-4425-9e97-b39d6d9536b2.png)

**Comment by manuelap-msft** [comment]
See https://github.com/microsoft/coe-starter-kit/issues/4779#issuecomment-1427859170

This is expected behaviour - currently only single-select is support. We are awaiting some enhancements to the command bar feature in order to implement multi-select.

**Comment by manuelap-msft** [comment]
Closing as duplicate.

**Comment by Raz-786** [comment]
But in my case not even single select is support.

Thanks

**Comment by manuelap-msft** [comment]
Not all flows can't be deleted, e.g. if a flow is in a solution we can't programmatically delete it and therefore hide the button. Try and find a flow outside of a solution that you know can be deleted and check if it's still missing.

**Comment by Jenefer-Monroe** [comment]
There is also a delay sometimes after you first load the app. Where selecting the object in the grid does not update the ribbon. The product team is aware of this delay and hopefully it will resolve soon.
