### ISSUE TITLE
[CoE Starter Kit - BUG] [Child] Admin | Sync Logs - Permission denied due to missing connection ACL

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#4822]
### Describe the issue

Some time ago I was doing a CoE update and I noticed that the flows for audit logs didn't work after it. I remembered that you also need to update the properties in the custom connector 365 Management Api after the update. I did it and flow was working properly, but for three weeks there is some error, and it seems to me that I did not make any changes. What could be the cause of this error?

![image](https://user-images.githubusercontent.com/54030753/219354231-94fceade-2fef-46b4-918a-919c340309eb.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by Jenefer-Monroe** [comment]
Hello. Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

If you believe you did that already, then we'll just need to back up and investigate

Please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

**Comment by BartoszKaminski1999** [comment]
Hello,

![image](https://user-images.githubusercontent.com/54030753/219479330-0cd5603d-887f-447e-b371-f79aa6d68ed4.png)

**Comment by BartoszKaminski1999** [comment]
I configured like that:

Client ID from this place:

![image](https://user-images.githubusercontent.com/54030753/219565916-8cfa0c28-ac41-4f85-b9c3-7656ad22ef0b.png)

Client Secret from this place (value)

![image](https://user-images.githubusercontent.com/54030753/219566167-cdd458bf-fddb-408a-bdb3-bcf527154ba0.png)

Refresh URL: https://manage.office.com/

**Comment by Jenefer-Monroe** [comment]
If you just configured this recently, then you may have been hit by this change in the default provider. Please see https://github.com/microsoft/coe-starter-kit/issues/4808

**Comment by BartoszKaminski1999** [comment]
I think that is configured in that way, look please

![image](https://user-images.githubusercontent.com/54030753/220035267-7af83b48-8741-4e65-a3ca-ca73d0e56a6c.png)

**Comment by BartoszKaminski1999** [comment]
Today I deleted all connections, in sync flow, created a new connection to custom connector again and it started working. Thanks
