### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin - Command Center - Message Center

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#4823]
### What is your question?

We have activated the message center service in Admin - Command Center and it works fine. However, I would like to ask what the "Act by" column means and why it is empty and why the last message is from December 20th. Is the data filtered to a certain date?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin - Command Center

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid I'm not sure what you are refencing. Can you please share a screenshot? 
**_Note_** that you will need to log in to GitHub to share an image. If you just reply in email the pictures will not come through.

**Comment by BartoszKaminski1999** [comment]
Hello, sure:

Im not sure why but a few days ago there was "Act by" column in place where i put "X".

![image](https://user-images.githubusercontent.com/54030753/219478002-9160ecc4-3edc-4123-9d5c-6c35dcee67e5.png)

However, I would like to ask what the "Act by" column means and why it is empty and why the last message is from December 20th. Is the data filtered to a certain date?

**Comment by manuelap-msft** [comment]
Hello,

this screen is populated from the Office 365 Message Center that's available in the admin portal, it's filtered down to only show Power Platform related messages - you can learn more about what the fields mean here: 
https://learn.microsoft.com/en-us/microsoft-365/admin/manage/message-center?view=o365-worldwide

On your current screenshot, the latest message shown is Feb 09 - where you do see the last message as December 20th?

**Comment by BartoszKaminski1999** [comment]
Thanks

Act by - We'll only have dates here if we're making a change that requires you to take an action by a certain deadline. Since we rarely use the Act by column, if you see something here, you should pay extra attention to it.
