### ISSUE TITLE
[ALM Accelerator - QUESTION] Custom Connector Setup

### ISSUE THREAD

**Issue by pavantagirisa** [microsoft/coe-starter-kit#4826]
### What is your question?

Hello,

Since the upgrade of ALM Accelerator the Authentication is not working for me for the CustomAzureDevops Connector.
I tired to update the connector to test it where I am missing the details from the document. 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#configure-the-devops-custom-connector
Can you please help if if I properly providing the details related to the security and authentication.

![image](https://user-images.githubusercontent.com/92401172/219416251-757f06d4-a82c-4f53-b4d8-68b6a49b4e76.png)

Please on the details to be provided at Authorization URL, Token URL and Refresh URL what I need to input in them.

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

Feb 2023

**Comment by pavantagirisa** [comment]
![image](https://user-images.githubusercontent.com/92401172/219427744-bac24381-45a0-42c3-889a-05de1c23a951.png)
I am able to make the test success, but when I try to use it with in the APP its failing.

![image](https://user-images.githubusercontent.com/92401172/219428318-2372589b-b525-45c5-b928-72c11363859d.png)


Please refresh the page and try signing in again. If that doesn't work, contact your admin.
Learn more
Hide details
Error Code: UserNotLoggedIn
Session Id: abd5e168-16b0-4037-a02d-1155b1850e7c
Activity Id: d3785dba-6ba2-4443-8188-bb1691aeebec
Timestamp: Thu Feb 16 2023 10:28:16 GMT-0600 (Central Standard Time)
[NotLoggedInError] User is not logged in. Error: There is no signed in user
UciError: [NotLoggedInError] User is not logged in. Error: There is no signed in user at s (https://org481f672c.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5232-2301.2:4914:82) at https://org481f672c.crm.dynamics.com/uclient/scripts/custompage.js?v=1.4.5232-2301.2:36:6614


![image](https://user-images.githubusercontent.com/92401172/219428438-049bbb9e-7048-4b29-a395-09a27828c3a0.png)

**Comment by pavantagirisa** [comment]
On Launch of APP the connection is returning as invalid, but I can connect it while testing and returning the results.

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/92401172/219437197-1685f70a-166b-4c99-83a1-75a83d5d59b7.png">

**Comment by ryanhodgson1** [comment]
@mikefactorial 

I am also having this issue. In the documentation it says resource URL like what was used in the last update:

![image](https://user-images.githubusercontent.com/77652317/219501639-b654db67-2b55-40aa-a450-ddb2b36cf1c2.png)

But now its changes to refresh URL and it only accepts an https:// address, not the client ID

**Comment by devkeydet** [comment]
On first glance, this appears to be due to using the wrong value in the Identity Provider dropdown.  Your screenshot shows "Generic OAuth" when it needs be "Azure Active Directory".
![image](https://user-images.githubusercontent.com/4499296/219512526-62d34107-c6a8-4eb2-8c0b-6ba3e3fdc430.png)

**Comment by ryanhodgson1** [comment]
Thanks @devkeydet 

I changed it to that in the drop down and it looks like it worked

**Comment by pavantagirisa** [comment]
@devkeydet

I am running into the issue while using the APP even after changing the Authentication type.

Here is how my Authentication is set in custom connector:

![image](https://user-images.githubusercontent.com/92401172/219691618-44d3dc6c-ed5b-4c38-93c4-86cc272b581a.png)

Then when I tested the Connector with AD authentication it return success on getting the organization details.

![image](https://user-images.githubusercontent.com/92401172/219691931-556bdb28-6176-454e-b3d5-7f8f958693de.png)

But, when I try to use the ALM APP here are the errors I been running into when I try to commit the solution.

Error running pipeline: CustomAzureDevOps.RunPipeline failed: {"$id":"1","innerException":null,"message":"Unexpected parameter 'PublishCustomizations'","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException","errorCode":0,"eventId":3000}

This is the first time I am running into this error mainly after upgrade.

**Comment by mikefactorial** [comment]
@pavantagirisa the error you are seeing is indicative of the latest pipelines not being installed. Depending on how you installed the ALM Accelerator originally 

1. Installed using the Project Setup Wizard: You can use the project wizard to upgrade your pipeline templates. 
![image](https://user-images.githubusercontent.com/42348035/219697349-23e484fe-dd0b-4b5f-b85b-5fd935fceda3.png)
2. Installed using CLI or manually: Follow the instructions here. 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-upgrade-config#updating-the-pipelines-in-azure-devops

**Comment by pavantagirisa** [comment]
@mikefactorial  - Thanks for sharing it.

I have used Project Wizard set up to configure the ALM, but looks like the Pipeline upgrade is failing for me.

2023-02-17T15:38:39.1984460Z ##[section]Starting: Create PR - upgradeCenterofExcellenceALMAccelerator-February2023 to main
2023-02-17T15:38:39.2097327Z ==============================================================================
2023-02-17T15:38:39.2097535Z Task         : PowerShell
2023-02-17T15:38:39.2097649Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2023-02-17T15:38:39.2097834Z Version      : 2.212.0
2023-02-17T15:38:39.2097940Z Author       : Microsoft Corporation
2023-02-17T15:38:39.2098069Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2023-02-17T15:38:39.2098254Z ==============================================================================
2023-02-17T15:38:41.1503069Z Generating script.
2023-02-17T15:38:41.1503415Z ========================== Starting Command Output ===========================
2023-02-17T15:38:41.1504038Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\9cfbf1da-27b4-4fe8-8070-305fe8718d75.ps1'"
2023-02-17T15:38:42.8018551Z ERROR: TF401179: An active pull request for the source and target branch already exists.
2023-02-17T15:38:43.1487307Z ##[error]PowerShell exited with code '1'.
2023-02-17T15:38:43.1798970Z ##[section]Finishing: Create PR - upgradeCenterofExcellenceALMAccelerator-February2023 to main

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/92401172/219701058-5de5d7d3-bbfd-4c82-8c98-5744a903256d.png">

**Comment by mikefactorial** [comment]
@pavantagirisa the error message is fairly straightforward "An active pull request for the source and target branch already exists" Go to Azure DevOps and select Repos -> Pull Requests and select the template repo. It's possible that you ran the upgrade previously but didn't select the option to "Auto complete upgrade" if you don't select that option it will create a PR in Azure Devops but not merge it. You can manually merge the PR from Azure DevOps or cancel the existing PR and try again with that option selected.

**Comment by pavantagirisa** [comment]
Thanks its worked now.

**Comment by mikefactorial** [comment]
Great! Thanks for letting me know! Closing this out for now

**Comment by MudassarAliakhtarAli** [comment]
why we use custom connector? is it Mandatory ? what if I dont want to use it so is there any other way to do it?
