### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot select embedded app in CoE Dashboard

### ISSUE THREAD

**Issue by bpr17** [microsoft/coe-starter-kit#4830]
### Describe the issue

With the February 23 release, the option to select a PowerApp to embed into the app detail and cloud flow detail pages of the CoE Dashboard is not available.
![image](https://user-images.githubusercontent.com/113717007/219506409-8c83cdc0-6f1f-4d85-b23f-25d4fb4e4332.png)

### Expected Behavior

In previous versions, the option to select the "Admin - Access this App" and "Admin - Access this Flow" apps to embed into into dashboard pages was available after opening the CoE template file.
![image](https://user-images.githubusercontent.com/113717007/219506556-95c696cb-42c8-4274-a1a6-6753ec6dc0ff.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1. Open PowerBI Desktop
2. Sign in as the CoE service account
3. Open Production_CoEDashboard_February2023.pbit in PowerBI Desktop 
4. Input your organization URL
5. Go to either the 'app detail' or the 'cloud flow detail' pages
6. Select 'Format visual' and select 'Reset to default'
The option to choose your app does not appear.

### Anything else?

This is the first upgrade where I used the CoE Upgrade wizard

**Comment by Jenefer-Monroe** [comment]
You have to select fields in order for this UX to appear. It looks like something happened to our documentation to lose these steps. I'll mark this as a documentation bug for March as a result.

**Comment by manuelap-msft** [comment]
Hello,

it looks like there's a bug with the Power App visual in Power BI desktop at the moment, we've seen several reports in the Power BI community on this as well. We're following up with the relevant team here to see if there's a status update.

Thank you for reporting this,
Manuela

**Comment by manuelap-msft** [comment]
I'm not sure if this is an option for you, but it looks like the Oct-Dec version of Power BI Desktop work still, and it's only the latest version of Power BI Desktop that has introduced this issue. If you can switch to an older version, that may resolve your issue for now.

**Comment by manuelap-msft** [comment]
We just learned a workaround from our wonderful colleague @petepuu. If you open the dashboard via the browser under app.powerbi.com, and edit the visual from there you'll be able to select the app and environment. It seems to be only Power BI Desktop that's impacted by this issue.

**Comment by robertcaretta** [comment]
Ran into this issue as well. Should we still perform step #3, select "Format visual" and select "Reset to default"?  Or skip this whole process entirely?
https://github.com/microsoft/coe-starter-kit/issues/4830

If this can all be done in the browser after publishing that would be even better. Maybe you could just distribute the .pbix files in the .zip and eliminate a step?  The pbix files can be imported into the workspace straight away.

**Comment by manuelap-msft** [comment]
Yes, you will need to perform format visual > reset to default so you can select your environment and app from there, otherwise it won't embed the correct app.

Unless we're missing something, if we share .pbix files, they are pre-loaded with data from our tenant (data shows when you open the pbix until you put in your environment details and refresh) so that's not an option for us to make available at the moment.

**Comment by bpr17** [comment]
Apologies for the late response- setting up the embedded apps through the web editor solved this! Thanks for the quick support!
