### ISSUE TITLE
[CoE Starter Kit - QUESTION] What does the Modifed On date mean in the Power Platform Admin View?

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#4833]
### Describe the issue

Hello,

In PowerApps Apps table there are two columns available to check when was app last time modified? I've checked that these dates are different, which one column is true and should be used?

![image](https://user-images.githubusercontent.com/54030753/219592701-9d6c5262-0ecb-4183-8786-0ebacaebdfc8.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by manuelap-msft** [comment]
The CoE Starter Kit collects meta-data about your inventory (such as app name, app environment, app owner) in Dataverse to build app/flow governance experiences like this Admin View app on top of. Each app, flow, environment you have in your tenant is stored as a row in a table in Dataverse. There are cloud flows that you turned on during setup (we call them sync flows) that write the data to those Dataverse tables on a daily basis.

In this screenshot:
- App Modified On - represents the date the app was last modified on
- Modified On - represents when the row in Dataverse was last modified on

Those are not the same. I would recommend not looking at the Modified On date at all in this view (it looks like you modified the view as by default we don't show that field) as it's an internal field that just relates to when the record in Dataverse was modified and has nothing to do with the App itself.

**Comment by BartoszKaminski1999** [comment]
It is as I thought, thanks for confirming
