### ISSUE TITLE
[CoE Starter Kit - BUG] Email Customization

### ISSUE THREAD

**Issue by CDSSYW** [microsoft/coe-starter-kit#4835]
### Describe the issue

Hi CAT team,

I noticed email customization feature is having mistake not applying html editor, would be nice to fix this part to reduce the customization time. Thanks!
![image](https://user-images.githubusercontent.com/117460925/219635639-9a96a68a-d0b3-4b99-a55b-73ba2a763384.png)
![image](https://user-images.githubusercontent.com/117460925/219636604-9549813d-ea64-4228-aa12-894b60d24419.png)

### Expected Behavior

markdown should be available if applying html editor

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

CoE Admin Command Center

**Comment by Jenefer-Monroe** [comment]
Hello. The approval mails in flow does not accept HTML, it accepts markdown only. Here is an article to help you learn more. [Use Markdown in Power Automate approval requests](https://learn.microsoft.com/power-automate/approvals-markdown-support)

So this is just a product limitation that we have to snap to. Hope that helps you understand the state, please let me know if I misunderstood the question. 

The rest of the mails should be HTML, please let me know if they are not.

**Comment by CDSSYW** [comment]
Thank you Jenefer!
