### ISSUE TITLE
[ALM Accelerator - Feature]: Enable Connection Sharing in the ALM Accelerator App :exclamation:

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#4838]
### Is your feature request related to a problem? Please describe.

An update to the platform now requires that connections be shared with Service Principals or anyone who is attempting to activate a flow that doesn't own a connection associated with a connection reference.

### Describe the solution you'd like

Add an option to the connection reference page in the deployment settings to share the user's connection(s) with the service principal associated with the deployment pipeline(s).

### Additional context?

[See Learn documentation for more information](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-connection-reference#enable-flows-containing-connections-from-another-user)

**Comment by mikefactorial** [comment]
Hotfix release has been created for this issue. https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-February2023-HF1

**Comment by mikefactorial** [comment]
![image](https://user-images.githubusercontent.com/42348035/220380301-efe496c6-da23-48e7-9706-5db5635b9186.png)

**Comment by rfarris2000** [comment]
For this issue do you need to update all the deployment settings or will this default to True?

**Comment by mikefactorial** [comment]
Hey @rfarris2000, the spirit of the change in the platform was that makers need to explicitly agree to share their connections so the default is false. Will require update of all deployment settings.

**Comment by rfarris2000** [comment]
Sounds good.  Just wanted to verify.  Thanks for the quick update.
