### ISSUE TITLE
Governance Components Feb 2023 release

### ISSUE THREAD

**Issue by snl-meg** [microsoft/coe-starter-kit#4840]
Is there no update for the Governance components solution in the Feb 2023 release. The last time I updated was in November.

**Comment by Jenefer-Monroe** [comment]
There is. The Gov components are called the Audit Components in the solution file. It's unfortunate but we cannot update the name. Hope that helps!

![image](https://user-images.githubusercontent.com/89584709/220093140-a726ee21-7633-4026-a9f3-bfa9f48661bb.png)

**Comment by snl-meg** [comment]
Great, thank you!

**Comment by snl-meg** [comment]
![image](https://user-images.githubusercontent.com/85708566/220168012-a61994ed-8c47-4e24-bb3c-956ff188ff15.png)
I see it.
