### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot fix connection after reestablishing Audit Log custom connector post-update

### ISSUE THREAD

**Issue by fishyconnor** [microsoft/coe-starter-kit#4841]
### Describe the issue

I've gone through the solution mentioned in [#1424](https://github.com/microsoft/coe-starter-kit/issues/1424) and I am able to re-input the client id, secret and resource URL correctly as per my application registration. I can also save this successfully. However, I am unable to create a new connection or fix the existing connection. When checking error via Azure portal, I see the following error. 
![image](https://user-images.githubusercontent.com/119827105/219991727-b4e77724-1366-42e0-b05d-c4f86343ef99.png)

No error message comes up during login, without looking at why the login failed in Azure. 

The user account does have permission to the connection and has been using it fine prior to the Feb 2023 CoE update. 

I have tried deleting the connection and recreating it, from within the flow and from the connections tab in make.powerautomate, both result in the same problem. 
![image](https://user-images.githubusercontent.com/119827105/219992187-767c1006-e44f-48a4-9475-34f822eb737c.png)

### Expected Behavior

Able to fix connection to custom connection for Audit Log flow. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

1. In the CoE Environment where the Audit Log Solution is installed
2. Updated CoE solution to 3.3 Feb 2023 update
3. Custom Connector utilised by Audit Log breaks
4. Edit Connector, identity Provider: Azure AD, Client ID, Client Secret, Resource URL[#1424](https://github.com/microsoft/coe-starter-kit/issues/1424)
5. Make sure App Reg has redirection URL added. 
6. Go to 5. Test
7. Unable to select existing connection, so attempt to Create New Connection
![image](https://user-images.githubusercontent.com/119827105/219993260-5aadad2d-2e27-4048-acbc-5579da1a97cf.png)
8. Login to service account
9. Login Dialogue Box closes, selected connection dropdown still greyed out. 
10. Also attempt to fix connection from Connections tab, Login to service account, Dialogue Box closes, does not resolve issue

**Comment by Jenefer-Monroe** [comment]
Try to create the connection from here instead, I've seen that work or at least give better error message.
![image](https://user-images.githubusercontent.com/89584709/220092062-d929a246-b18b-40c7-90db-c8eceae9f0f3.png)
![image](https://user-images.githubusercontent.com/89584709/220092359-f8d76755-aea2-4113-857e-23ed3003eece.png)

**Comment by Jenefer-Monroe** [comment]
There was also a change in the default provider in that UX so you may have been hit by this change. 

Please see https://github.com/microsoft/coe-starter-kit/issues/4808

**Comment by fishyconnor** [comment]
Solved, dumb problem, but my admin provided the wrong app registration. Thanks for looking into it @Jenefer-Monroe

**Comment by Jenefer-Monroe** [comment]
Happy to help!
