### ISSUE TITLE
[Power Platform communication site template] ISSUE TITLE

### ISSUE THREAD

**Issue by joukony** [microsoft/coe-starter-kit#4846]
### Describe your bug, question or feature ask.

Many tenants have noscript enabled by default and therefore running this script is giving the following warning:
Skip adding/updating custom actions because the site has "noscript" enabled

Should the script be modified to check that some prerequisites are in place for the deployment? These custom actions seem to be mandatory for the site to function properly? Looks like the master page is customized as well.

Script is connecting to sharepoint admin api by default, is it assumption that you need to be SP admin to deploy this or should there be alternative model and what would be the prerequisites in such scenario?
![pphub install noscript issue](https://user-images.githubusercontent.com/3913705/220130952-6f36c8d1-712b-4fe2-beec-e5ab780613b2.png)

**Comment by Laskewitz** [comment]
Hi @joukony -

We haven't modified the standard masterpage or added any custom actions in this template, so you can ignore these messages!

Cheers,
Daniel

**Comment by manuelap-msft** [comment]
Closing out as no further action required.
