### ISSUE TITLE
[CoE Starter Kit - BUG] Innovation Backlog App

### ISSUE THREAD

**Issue by davidfeldman-coop** [microsoft/coe-starter-kit#4848]
### Describe the issue

![image](https://user-images.githubusercontent.com/91218031/220390947-6c11b926-2d6d-47f3-bb8c-7c067e638cef.png)

There is a misspelling on page 3 "Tools used in terst". I am assuming terst should be test?

### Expected Behavior

Correct spelling

### What solution are you experiencing the issue with?

Innovation Backlog

### What solution version are you using?

3.1

### What app or flow are you having the issue with?

Innovation Backlog

### Steps To Reproduce

Launch Innovation Backlog app, go to page or step 3.

### Anything else?

No

**Comment by manuelap-msft** [comment]
Hello,

this should be coming through from the Name you put on the first screen

e.g. I named my idea Supplier Invoice Processing
![image](https://user-images.githubusercontent.com/55705669/220393287-e9542da9-7e14-4e5f-943e-266a35d9aeaa.png)

And it then says Tools used in Supplier Invoice Processing
![image](https://user-images.githubusercontent.com/55705669/220393205-0d138e62-7f42-4873-b7f7-7d5be6da596b.png)

**Comment by davidfeldman-coop** [comment]
Ok, it makes sense. Thank you

**Comment by davidfeldman-coop** [comment]
Closing
