### ISSUE TITLE
Permission error w/CoE Setup Wizard App

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#4850]
I just installed the update to the CoE to v. 4.3. I should be the owner of everything, but the CoE Setup Wizard App has no owner.

![image](https://user-images.githubusercontent.com/116654106/220462696-fd68db77-13ff-4e86-ae37-2c607ff92ae3.png)

**Comment by Jenefer-Monroe** [comment]
For whatever reason, that screen does not show owners for MDAs. 
![image](https://user-images.githubusercontent.com/89584709/220497614-e81d25a3-95ea-40ef-abe2-d71acbdcd05b.png)

If you go to look outside the context of the solution to view all apps, you should see the owner listed.
![image](https://user-images.githubusercontent.com/89584709/220497847-5e4375ac-14d2-4d70-95f5-b234e125a4e2.png)

This is product behavior so not something we can correct. 
Hope that helps.

**Comment by RickKush** [comment]
When I go to the App outside of the solution, I see that I am the owner, but I now get a different error when I try to run it:

This action is not supported.
Hide details

  *   Error Code: 2147746581
  *   Session Id: 20ab7f88-7fef-4440-8258-28ed3b7abacf
  *   Timestamp: Wed Feb 22 2023 13:59:59 GMT-0500 (Eastern Standard Time)
RetrieveUserContext: SecLib::CheckPrivilege failed. User: 80067d27-f650-ed11-bba1-0022481fb943, PrivilegeName: prvReadEntity, PrivilegeId: a3311f47-2134-44ee-a258-6774018d4bc3, Required Depth: Basic, BusinessUnitId: 3aa050b4-554c-ed11-bba2-000d3a1791ba, MetadataCache Privileges Count: 4029, User Privileges Count: 20
UciError: SecLib::CheckPrivilege failed. User: 80067d27-f650-ed11-bba1-0022481fb943, PrivilegeName: prvReadEntity, PrivilegeId: a3311f47-2134-44ee-a258-6774018d4bc3, Required Depth: Basic, BusinessUnitId: 3aa050b4-554c-ed11-bba2-000d3a1791ba, MetadataCache Privileges Count: 4029, User Privileges Count: 20 at s (https://ppgovcoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5227-2301.3:4914:82) at new g (https://ppgovcoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5227-2301.3:2737:2886) at g.fromLegacyErrorStatus (https://ppgovcoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5227-2301.3:2737:4764) at _ (https://ppgovcoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5227-2301.3:2737:7137) at https://ppgovcoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5227-2301.3:3722:2160

***@***.***



From: Jenefer Monroe ***@***.***>
Sent: Tuesday, February 21, 2023 8:34 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Permission error w/CoE Setup Wizard App (Issue #4850)


For whatever reason, that screen does not show owners for MDAs.
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/220497614-e81d25a3-95ea-40ef-abe2-d71acbdcd05b.png__;!!May37g!IWLZ3hmDrAyi0F_LXabt5arWSHwZI2FZwWAr1KNHvccIFwmD7Y4ZdOb4gx3CENOrbCODdFTHXBVhC_y-faB_QLlf8A$>

If you go to look outside the context of the solution to view all apps, you should see the owner listed.
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/220497847-5e4375ac-14d2-4d70-95f5-b234e125a4e2.png__;!!May37g!IWLZ3hmDrAyi0F_LXabt5arWSHwZI2FZwWAr1KNHvccIFwmD7Y4ZdOb4gx3CENOrbCODdFTHXBVhC_y-faD6dBBSYg$>

This is product behavior so not something we can correct.
Hope that helps.

-

**Comment by RickKush** [comment]
Note that this user, : 80067d27-f650-ed11-bba1-0022481fb943, does not exist in our AAD.

Thank you very much!!!

From: Kushner, Rick [USA]
Sent: Wednesday, February 22, 2023 2:07 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [External] Re: [microsoft/coe-starter-kit] Permission error w/CoE Setup Wizard App (Issue #4850)

When I go to the App outside of the solution, I see that I am the owner, but I now get a different error when I try to run it:

This action is not supported.
Hide details

  *   Error Code: 2147746581
  *   Session Id: 20ab7f88-7fef-4440-8258-28ed3b7abacf
  *   Timestamp: Wed Feb 22 2023 13:59:59 GMT-0500 (Eastern Standard Time)
RetrieveUserContext: SecLib::CheckPrivilege failed. User: 80067d27-f650-ed11-bba1-0022481fb943, PrivilegeName: prvReadEntity, PrivilegeId: a3311f47-2134-44ee-a258-6774018d4bc3, Required Depth: Basic, BusinessUnitId: 3aa050b4-554c-ed11-bba2-000d3a1791ba, MetadataCache Privileges Count: 4029, User Privileges Count: 20
UciError: SecLib::CheckPrivilege failed. User: 80067d27-f650-ed11-bba1-0022481fb943, PrivilegeName: prvReadEntity, PrivilegeId: a3311f47-2134-44ee-a258-6774018d4bc3, Required Depth: Basic, BusinessUnitId: 3aa050b4-554c-ed11-bba2-000d3a1791ba, MetadataCache Privileges Count: 4029, User Privileges Count: 20 at s (https://ppgovcoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5227-2301.3:4914:82) at new g (https://ppgovcoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5227-2301.3:2737:2886) at g.fromLegacyErrorStatus (https://ppgovcoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5227-2301.3:2737:4764) at _ (https://ppgovcoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5227-2301.3:2737:7137) at https://ppgovcoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5227-2301.3:3722:2160

***@***.***



From: Jenefer Monroe ***@***.******@***.***>>
Sent: Tuesday, February 21, 2023 8:34 PM
To: microsoft/coe-starter-kit ***@***.******@***.***>>
Cc: Kushner, Rick [USA] ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [External] Re: [microsoft/coe-starter-kit] Permission error w/CoE Setup Wizard App (Issue #4850)


For whatever reason, that screen does not show owners for MDAs.
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/220497614-e81d25a3-95ea-40ef-abe2-d71acbdcd05b.png__;!!May37g!IWLZ3hmDrAyi0F_LXabt5arWSHwZI2FZwWAr1KNHvccIFwmD7Y4ZdOb4gx3CENOrbCODdFTHXBVhC_y-faB_QLlf8A$>

If you go to look outside the context of the solution to view all apps, you should see the owner listed.
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/220497847-5e4375ac-14d2-4d70-95f5-b234e125a4e2.png__;!!May37g!IWLZ3hmDrAyi0F_LXabt5arWSHwZI2FZwWAr1KNHvccIFwmD7Y4ZdOb4gx3CENOrbCODdFTHXBVhC_y-faD6dBBSYg$>

This is product behavior so not something we can correct.
Hope that helps.

-

**Comment by Jenefer-Monroe** [comment]
User GUIDs in this context are not the AAD user GUID. They are an envt specific GUID. 

If you go to the Users table in the environment you can see the GUID there in the User column, and see its AAD corresponding GUID in the Azure AD OBject ID column. Its likely your identity its referencing
![image](https://user-images.githubusercontent.com/89584709/220782560-83666744-184a-4004-835e-8b3e0b81e71d.png)
![image](https://user-images.githubusercontent.com/89584709/220782760-c55e7330-7d3d-4d79-bc9e-9eb07adee60a.png)

**Comment by Jenefer-Monroe** [comment]
The error is saying you dont have permission. This is likely because you are logged in as a different user or your identity does not have the Power Platform Admin role permanently assigned. 

Please let me know your thoughts after looking at these things.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
