### ISSUE TITLE
Show complexity score in COE Dashboard under Cloud Flow page

### ISSUE THREAD

**Issue by ravisharma2311** [microsoft/coe-starter-kit#4852]
### What is your question?

Hi,

Can you please help me to get the formula used to get complexity score in COE Dashboard under Cloud Flow page. We are getting the complexity score in mouse hover but unable to get what formula used so that i can show the same details in flow table also how to use complexity score along with other filter on Cloud Flow page. Please see the attachment to get more information.
![COE](https://user-images.githubusercontent.com/78497015/220523743-8b339fc3-7b7a-429f-b3fa-87f20c12741a.png)

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
