### ISSUE TITLE
[CoE Starter Kit - BUG]Admin Sync Template V3 failed on Action 'Get_Environment' failed

### ISSUE THREAD

**Issue by Raz-786** [microsoft/coe-starter-kit#4854]
### Describe the issue

Hello 
 Admin Sync template v3 continuously failed See screen shot, when check the flow and found failed on specific step but not sure how interpret that error and where to look to fix the issue. it was working after COE upgrade but failed for past few days

Error
Action 'Get_Environment' failed

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

ADmin Sync template V3

### Anything else?

![image](https://user-images.githubusercontent.com/116106952/220649018-513d592e-e31a-4fad-9c3b-5e53b1d09b56.png)

**Comment by Raz-786** [comment]
Found one of the helper flow was turn off, i turn it on, let wait till tomorrow can't this flow during day time. please hold this ticket till tomorrow
thanks

**Comment by Jenefer-Monroe** [comment]
yes thats a common cause. Please do let us know.

**Comment by Raz-786** [comment]
Hi Monroe,

Flow ran successfully, please close the case

Thanks you

**Comment by Jenefer-Monroe** [comment]
Thanks for letting us know!
