### ISSUE TITLE
App last launched on by app type

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#4856]
The App Last Launched on date field in the UX is blank for both Model-Drive App and Custom Page. Does the product supposed to track the app last launched on date field by Model-Driven app and Custom Page?

**Comment by dcurt1977** [comment]
Thanks for the explanation and clarification.

**Comment by dcurt1977** [comment]
This issue can be closed and archived.

**Comment by Jenefer-Monroe** [comment]
You bet. I'll go ahead and close this but feel free to reach out with other questions in the future!
