### ISSUE TITLE
[CoE Starter Kit - BUG] unable to load Admin- Command Center

### ISSUE THREAD

**Issue by gangs036** [microsoft/coe-starter-kit#4857]
### Describe the issue

When I run Admin - Command Center , I am getting below error.

It looks like this app isn't compliant with the latest data loss prevention policies.Policy name: COEDLP_PolicyBusiness connector: shared_office365users cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_rss.Business connector: shared_powerappsforadmins cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_rss.Business connector: shared_flowmanagement cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_rss.Business connector: shared_office365 cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_rss.Business connector: shared_commondataserviceforapps cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_rss.Business connector: shared_commondataservice cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_rss. Session ID: d1e7f681-6a44-495c-ace9-b73daeda9f15

Note: I had configured DLP policy properly for following connectors and remaining connectors.
1) Office 365 user
2) Power Apps for Admin
3) Dataverse
4) Power Automate for Admin

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

No

### Steps To Reproduce

1. When play Admin- Command Center from app,
2. I am getting this error.
3. 
![image](https://user-images.githubusercontent.com/126099743/220703488-47fd3f68-0237-4694-994b-2d561139045a.png)

**Comment by Jenefer-Monroe** [comment]
The message indicates that you did not setup the DLP correctly. Note that [all these connectors](https://learn.microsoft.com/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies) need to be together in the same bucket. The message indicates some are in business and some are in non-business.

**Comment by gangs036** [comment]
Yes I have added [all these connectors](https://learn.microsoft.com/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies) need to be together in the same bucket only.. 
And getting same issue.
![image](https://user-images.githubusercontent.com/126099743/220706880-396e81d8-79ab-4d86-a4d0-268afeaf9e38.png)

**Comment by Jenefer-Monroe** [comment]
Do you have RSS connector in the Business bucket? That is the one it seems to be complaining about.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team

**Comment by bethleota** [comment]
Good day everyone. I get the same error as @gangs036. So I added the RSS Connector to our DLP policy and applied it to All Environments. I still get the error. Do I need to wait for awhile for it to sync? I'm trying to update our CoE since it was last updated in October 2022. But wanted to check for any issues in the Admin - Command Center before doing so.
