### ISSUE TITLE
[CoE Starter Kit - BUG] Power Bi not showing accurate Unique users with Shared users information 

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#4858]
### Describe the issue

Power BI Report is not showing the correct amount of users. 
We have apps in the list that are showing that they are not being shared by users or groups but they are still experimenting sessions. We don't know how the apps is shared due to an issue with the report. 

![image](https://user-images.githubusercontent.com/95443860/220761746-cf3640ca-cfdf-4acb-94dd-a010388f05c7.png)

### Expected Behavior

Unique users should be <= than shared users. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Power BI Report

### Steps To Reproduce

Open PBI Prod report, navigate to Apps report.

**Comment by Jenefer-Monroe** [comment]
There was a bug in 4.2 for getting these numbers. 
Please make sure you have no unmanaged layers on these flows

- CLEANUP HELPER - Power Apps User Shared With
- CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

Then run this flow

- CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

Once complete refresh the PBI and let me know if it looks correct.

**Comment by Jenefer-Monroe** [comment]
also please note, unique users is not about who its shared with, but its about who has launched. 
its a distinct count for the app from the audit logs table.

**Comment by nasilvae** [comment]
Hey, 

The Cleanup Helper - Power Apps User Shared With ran successfully but we are noticing discrepancies with the data. 

The group sizes are not correct, not sure why. 
![image](https://user-images.githubusercontent.com/95443860/221327151-3c220714-fdb8-496d-b372-a0561e692d03.png)

We did noticed that on one of the runs that was marked as successful it showed an error on the Get Envt from CoE invetory
![image](https://user-images.githubusercontent.com/95443860/221327204-4e02fc2f-0d5c-4693-a577-dfa87f3db19f.png)

The AD groups size in AZ vs the size specified in the CoE various up to 50 people. Not sure if this is part of this flow or a different one.

**Comment by nasilvae** [comment]
Please let me know if this is a different issue and I can open another bug thread for tracking.

**Comment by Jenefer-Monroe** [comment]
For group size, we just fetch the members and this get the count of records
![image](https://user-images.githubusercontent.com/89584709/221414668-d8ea0401-0a05-4560-8028-40a9afe6ed1c.png)

Can you please share a specific example of where this is incorrect? The group size for example. And then is it still wrong the next run (v a timing thing for example)

**Comment by nasilvae** [comment]
We re-ran the flow and the numbers remained the same. 

![image](https://user-images.githubusercontent.com/95443860/221589004-a65996c6-dd20-4735-abac-0e599c6aee50.png)
![image](https://user-images.githubusercontent.com/95443860/221589559-705ec9ed-1bc8-4ea7-92d8-f68f06c1978f.png)

![image](https://user-images.githubusercontent.com/95443860/221591738-8ad4a70e-08d4-4056-9188-e1da78ed4d8e.png)

**Comment by Jenefer-Monroe** [comment]
what error message are you getting here? 
![image](https://user-images.githubusercontent.com/89584709/221678697-50286259-9385-4c34-b227-f113559164d6.png)

**Comment by Jenefer-Monroe** [comment]
and what format is coming through in the trigger for envtName
![image](https://user-images.githubusercontent.com/89584709/221679053-75ce6033-c4bd-4a86-9d15-e36a7421c9e4.png)

**Comment by nasilvae** [comment]
> what error message are you getting here? ![image](https://user-images.githubusercontent.com/89584709/221678697-50286259-9385-4c34-b227-f113559164d6.png)

We found the issue that the parameter passed when it was kicked off manually was incorrect. We went and re-run it using the environment ids and now we are waiting to see if the data gets updated properly. The flow takes a couple of hours to run once it runs with the correct parameter will report back here.

**Comment by Jenefer-Monroe** [comment]
oh thank you for the update. I was really struggling to guess at what might be wrong! 
Please do let me know.

**Comment by Jenefer-Monroe** [comment]
my pleasure!
