### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 Failing

### ISSUE THREAD

**Issue by FredrickLucerne** [microsoft/coe-starter-kit#4859]
### Describe the issue

Admin | Sync Template v3
Failing due to "Action 'Get_Environment' failed"
Please see attached screenshot - 

![image](https://user-images.githubusercontent.com/126117946/220767221-239b64ec-c70d-44b5-a64a-98743d61eca4.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feb release

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
**_Get_Environment_** is a caught failure we use to detect if the environment is already in the inventory or not.
You will need to continue to parse down into the flow to find where it terminates in a failure. 

That said the most common cause here is that not all child flows are turned on. So please make sure that all the [child flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-child-flows) are turned on.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
