### ISSUE TITLE
[CoE Starter Kit - BUG] Not seeing all envts

### ISSUE THREAD

**Issue by chrismellis** [microsoft/coe-starter-kit#4861]
### Describe the issue

Experiencing an issue with the Power Platform Center of Excellence dashboards where it is not displaying all the environments available even though I am the Power Platform Admin and in the admin portal can see all of the environments.  We have over 50 environments and I am not seeing Teams or Sandbox or Developer Environments.  Please advise.  

### Expected Behavior

I expect to see all environments in the PBI CoE dashboards.  

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

PowerBI CoE Dashboards

### Steps To Reproduce

In PowerBI Coe Dashboard>Environments I only see 3, not the 50+ I am expecting

![CoEEnvts](https://user-images.githubusercontent.com/126122287/220786144-0c1d5041-fa6b-4507-a3db-f2a3d50eea5b.png)

### Anything else?

n/a

**Comment by Jenefer-Monroe** [comment]
First please check the Power Platform Admin View app first, to see if this is an issue with the PBI or with the sync flows.
![image](https://user-images.githubusercontent.com/89584709/220789154-aec8bf50-c66e-4e1f-9519-13793fa6532b.png)

**Comment by chrismellis** [comment]
I do not see them there either Jenefer - in Power Platform Admin View my only environments are the CoE starter kit (production) and my default environment.  At admin.powerplatform.microsoft.com as sys admin I can see all 50+ environments. Please advise.

**Comment by Jenefer-Monroe** [comment]
Did you use your identity when you setup the kit? 
Do you have the Power Platform Admin role permanently assigned? Or is it assigned by PIM? 

Please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

![image](https://user-images.githubusercontent.com/89584709/220921377-a48647a6-699b-4b56-bdc0-ccd2e54cb28c.png)

**Comment by chrismellis** [comment]
Yes Jenefer- it was not PIM, the role is permanently assigned.  Note that I did read all of the documentation before turning to you for assistance.  Can you please tell me what to do to fix it?

**Comment by Jenefer-Monroe** [comment]
We'll have to go step by step like this. 

Please go to the details page of **_Admin | Sync Template v3_**
Is it your identity? Does it show as a green check? 
![image](https://user-images.githubusercontent.com/89584709/220929227-5d1a9eb1-2883-4d96-8540-c6ff0351ebe5.png)

Next please go to the latest run of **_Admin | Sync Template v3_**
![image](https://user-images.githubusercontent.com/89584709/220928595-a4429fdf-d8b5-4696-bc6e-97da044eb652.png)

View the output from this action in a json parser
![image](https://user-images.githubusercontent.com/89584709/220928842-12f92a16-b3de-4abe-b854-ffed5fb2ccf2.png)

Do you see all the environments listed there?

**Comment by chrismellis** [comment]
No, here I only the see the limited # of envts listed above - my default, and the CoE envt, though this flow runs successfully every day.

**Comment by Jenefer-Monroe** [comment]
That means that the user running this action does not have access to those environments. Which means they do not have the Power Platform Admin Role. 

Did you check the identities here? 
Is it your identity? Does it show as a green check? 
![image](https://user-images.githubusercontent.com/89584709/220929227-5d1a9eb1-2883-4d96-8540-c6ff0351ebe5.png)

**Comment by chrismellis** [comment]
Jenefer,

To confirm, by "Power Platform Admin Role"  you mean the AAD Power Platform Administrator role assigned via Azure Privileged Identity Management, correct?  **NOT** the System Administrator security role assigned from within the Power Platform admin portal, yes?  I think my problem is that my account to which the Platform Admin role is assigned does not have an O365 license assigned and this is why I keep running into various issues with some CoE flows/administration.  

I have been assigned Power Platform Administrator role via APIM.  
This role is also assigned sys admin @ admin.powerplatform.microsoft.com. 
This role did not install the CoE, but has been assigned "owner" of CoE  core component flows
This role does not have an O365 license assigned, but does have Power  Apps Per User Plan, Power Automate Free plan, and PowerBI Pro license assigned.  This is the account we would like to use for all administration of the platform but keep running into connection issues. 

I do have green checks as you indicate above, **but** the connection reference here is to my other account, the account that installed the CoE. This 2nd account does **not** have the Power Platform Administrator role assigned via APIM.  
This role is assigned sys admin @ admin.powerplatform.microsoft.com.  This account DOES have an O365 license assigned.

Am I correct in that the account running these flows must have **both** Power Platform Admin role assigned via APIM AND an O365 license assigned?  Neither of my accounts have both.  Is this the issue here or am I way off base?

Also, throughout documentation I keep seeing "service admin" role required - is this the same as the Power Platform Amin role or is it something else entirely?

Please advise,

Chris

**Comment by Jenefer-Monroe** [comment]
Here are the requirements for the account running the flows. 
[What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)
Please note the item in yellow, you cannot have temp permissions to the role and succeed with the kit. 
![Image](https://user-images.githubusercontent.com/89584709/222534023-ca6058e6-4ea6-47f6-aece-08bcb8d2325b.png)

For this
`Also, throughout documentation I keep seeing "service admin" role required - is this the same as the Power Platform Amin role or is it something else entirely?`
I'm not sure what you are referencing, can you share as link or screenshot?

**Comment by Jenefer-Monroe** [comment]
closign out as no further action for starter kit team
