### ISSUE TITLE
[CoE Starter Kit - BUG] Power Apps SharePoint Form Apps

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#4862]
### Describe the issue

We created a flow based on the data from this table. SharePoint form apps that have not been used for more than a month are marked as 'to be removed', some users have reported that their app is used daily and it has been marked as 'to be removed'. Admin Sync Flow is working properly because we can see that there are applications that were used a few days ago. However, for some reason, it is not visible for some applications. What could be the reason? When the application gets information about usage when someone just fires form in SharePoint or does it have to make some changes there? When will we get information that the SharePoint Form App has been used?

![image](https://user-images.githubusercontent.com/54030753/220864497-8a453631-028c-4699-8349-d397d8151074.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Power Platform Admin View - Power Apps

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. Here are a few things to note. 

Audit logs are collected by a solution separate from Core as the setup for them requires additional permissions. Please see [Set up the audit log connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog)

It looks like you have this installed and that it is running as you have captured some recent launches. 

There are some issues with gathering all the data from these logs, and if thats the case for you, then your admin email should get some warnings about needing to use smaller chunks in the audit log runs. Do you monitor that email?

**Comment by BartoszKaminski1999** [comment]
Do you mean tenant-admin, should every person with these permissions get these warnings or is this person specifically indicated somewhere to get this type of warnings?

**Comment by Jenefer-Monroe** [comment]
When you setup the kit you select a few groups with which to communicate. These communications are sent to the Admin Persona. Please see [How will you communicate with your admins, makers, and users?](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users)

These mails are sent to this persona. To see what you entered for this you can go to the CoE Command Center
![image](https://user-images.githubusercontent.com/89584709/221180881-6ea5a60a-85fc-41bd-bbaf-8422ebf4450c.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
