### ISSUE TITLE
[CoE Starter Kit - QUESTION] Setup CoE Starter Kit in DEV environment

### ISSUE THREAD

**Issue by miroslav-harlas** [microsoft/coe-starter-kit#4866]
### What is your question?

Hello,
we plan to create our own custom Power Platform solutions in the same Power Platform environment where CoE Starter Kit Core Components lives because we would like to integrate our custom solutions with CoE Starter Kit inventory data. Therefore we are in a need to have DEV + UAT + PROD instances of CoE Starter Kit inside of the single O365 tenant. Our tenant is quite huge from perspective of number of environments and apps and flows, and we do not want to have three instances of Starter Kit performing  the inventory of our entire tenant in parallel.

Please, could you share with us if there is any easy way, how could we configure CoE Starter Kit core components in DEV + UAT environment to be able to do development of the customizations on top of its data?

Is there any option how to configure CoE Starter Kit inventory and limit its inventory jobs to only specified set of environments, preferably without creation of unmanaged layer in existing inventory cloud flows?

Or do you think that it would be easy and reasonable to create dataflows to replicate data from PROD database into UAT and DEV databases? (We are afraid about complexity and fragility due to db schema changes after each CoE Starter Kit update)

Thank you in advance for any hint, direction or piece of advice related to this topic.

Best Regards

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Admin - Sync Template v3

**Comment by manuelap-msft** [comment]
Hello,

you can limit the CoE to run only for a subset of environments using a flag (this means no unmanaged layers)
https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments

Using Dataflows, you would use this approach (note this uses the odata connector in dataflows, but there's no also a Dataverse connector - both work in the same way). We don't have sample dataflows, but we have done some testing and this works - you need to use the alternate key for lookup tables which we now save in a column called recordguidasstring for all tables. 
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-odata-dataflows-migration

Here's an example of how to map a lookup field - createdBy in this case is the GUID of the maker, and admin_FlowCreator is a lookup to the Maker table which has recordguidasstring as a key.
![image](https://user-images.githubusercontent.com/55705669/220987392-3521b932-3711-45c9-8b6c-3a7f2641e3ab.png)

Here's our documentation for extending the kit - we recommend creating your own unmanaged solution in DEV and creating your components there, taking a dependency on CoE kit tables where needed and then moving both Core+your solution to UAT and PROD as managed.
https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

Hope that makes sense but let us know if you have additional questions,
Manuela

**Comment by miroslav-harlas** [comment]
Thank you for providing all the details. I didn't notice that there is a documented way already how to limit Starter Kit for specific environments only. That is great, and that would be the most likely our future direction 😃

I just want to confirm that I understand it correctly, please clarify:

If we set "is All Environments Inventory" to "No" in our DEV + UAT, then:
1. "Admin | Sync Template v3" will add all new environments to the inventory in DEV + UAT. We will have a complete and accurate list of all environments in both DEV + UAT all the time. However, the environments will be "empty" from inventory perspective in DEV + UAT (no apps, flows, solutions, etc. in the inventory).
2. Inventory cloud flows like "Admin | Sync Template v3 (Apps)", "Admin | Sync Template v3 (Flows)", etc... .will be triggered ONLY for those environments. which we mark as "Excuse from inventory" = "No", only these marked environments will be inevntoried and contain apps,flows,solution etc... in DEV+ UAT database.

Is that correct understanding?

And BTW: YES, I can confirm we want to create our own solution(s), and making it dependable on CoE Starter Kit tables. We will be extending data by adding our own custom tables. We do not want to touch any apps, flows, tables, etc. inside of CoE Starter Kit solution(s).

**Comment by manuelap-msft** [comment]
The feature to inventory only a subset of environments is a pretty recent addition, so your ask came at a great time :)

1. Yes that's correct, we will always inventory all environments so we know which ones to include/exclude from further inventory flows.
2.  "Admin | Sync Template v3 (Apps)", "Admin | Sync Template v3 (Flows) are still triggered, but have a clause in them to exit early. These flows trigger when a new environment is added or modified but the first step is to check if an inventory of this environment is required - if not, it will exit
![image](https://user-images.githubusercontent.com/55705669/220999105-c31cd07e-6141-4366-8af9-410998a61500.png). So it's correct that inventory will not be collected for environments that are marked as excluded, but I just wanted to let you know that the flows will still show as triggering. 

That's great to know, if there's any questions you have regarding building your own flows/apps on top of our tables that you think we could address in our documentation let us know and we'll try and fill those gaps in our documentation!

**Comment by Jenefer-Monroe** [comment]
Yes please do let us know what direction you end up going, and your analysis. This would be incredibly edifying to us.

**Comment by Jenefer-Monroe** [comment]
closign out as no further action for starter kit team
