### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by oburgoscr** [microsoft/coe-starter-kit#4867]
### What is your question?

Can we somehow get with the CoE how much space is being consumed by each flow and app?

### What solution are you experiencing the issue with?

Core

**Comment by oburgoscr** [comment]
I'm trying to get an estimate of how much space would be reclaimed or recovered after some flows and apps get deleted.

If the CoE can't bring that information, do you know any alternative?

**Comment by Jenefer-Monroe** [comment]
I dont quite follow your question. Are you asking about Dataverse capacity for the stored inventory?

**Comment by oburgoscr** [comment]
Yes, indeed we can see that information about the capacity of each environment. I would like to know if we can get that same information for each individual flow or app.

Thanks in advance :)

**Comment by Jenefer-Monroe** [comment]
No I'm afraid I dont have that information. I think you are asking about the capacity of each row in the inventory? I still dont quite follow.

**Comment by oburgoscr** [comment]
Now I don't know if I'm asking something that does not make sense xD. 

Is there a feasible way to know the storage amount that each flow is consuming in an environment?

In the Admin portal, we can see the total space available on the tenant and how much of it has been consumed by each environment.

Now if we go down one level, I would like to know if we can see how much space has been consumed by each flow or app.

Does that make sense?

**Comment by Jenefer-Monroe** [comment]
I believe you are saying, for example, 
there is a "get tshirt sizes" app in default --> how much dataverse capacity does adding that app to inventory take?

I'm not sure how much capacity each row takes, not much is the answer though. Its the overall size of your inventory that is important for knowing how much capacity your inventory will take. 

Please let me know if I've misunderstood

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
