### ISSUE TITLE
[ALM Accelerator - BUG]: Export solution failing

### ISSUE THREAD

**Issue by ryanhodgson1** [microsoft/coe-starter-kit#4868]
### Describe the issue

When i export my solutions it works fine but for some reason i have 1 solution that always fails on the "pac - Clone or Sync Solution" step with this error:

Error: Could not find a part of the path 'D:\a\1\s\ccms-customer-call-reduction\CustomerCallReduction\SolutionPackage\CustomerCallReduction\src\PluginAssemblies\CCMS_D365_Phase2_CCRCCMSCustomerCallReduction-E43EA55C-53AC-43F7-B732-FE90CE1440E7\CCMS_D365_Phase2_CCRCCMSCustomerCallReduction.dll.data.xml'.

This happens during the unpacking stage where it cant find the directory and it looks like its because its adding an extra folder in the directory:
![image](https://user-images.githubusercontent.com/77652317/221127022-1fe2eb59-e060-4811-adc9-11eefeee9a01.png)

Because when i look at all my other solution exports that succeed there is no extra folder:
![image](https://user-images.githubusercontent.com/77652317/221127307-a834d4f4-468d-4380-a827-9f9cff62aa71.png)

@mikefactorial  Have you seen this issue happen before?

### Expected Behavior

Export solution to not fail

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

November Release

**Comment by ryanhodgson1** [comment]
I removed the plugin assembly from the solution and it stated working. Have you come across this issue before with a plugin assembly causing the export to fail? i added it back in and the solution export failed again.

**Comment by RajeevPentyala** [comment]
@ryanhodgson1 "PluginAssemblies" folder gets created under "src" folder, if the Dataverse solution you are committing has a 'Plug-in assembly' component.

We did a quick test with a solution having 'Plug-in assembly' component but could not reproduce the issue you were facing.

To troubleshoot the issue, can you share the detailed log (Click on highlighted 'View raw log') of "pac - Clone or Sync Solution" step from your failed Export pipeline?

![image](https://user-images.githubusercontent.com/104883923/221542281-8c914cd7-e454-47ea-ac70-1bbaaccad0d8.png)

Or if you can share the solution, please share the same at rajeevpe(AT)microsoft(dot)com.

FYI @mikefactorial

**Comment by ryanhodgson1** [comment]
@mikefactorial i think it was something to do with the legacy folder structure cause we hadn't export this one since October last year.

I removed the plugin, did a commit, deployed to full dev, merged the branch to develop, added the plugin back in, exported again and its working now.
