### ISSUE TITLE
[CoE Starter Kit - QUESTION] Customizing CoE Flows 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4870]
### What is your question?

Hi 

As per the official Microsoft article , we cannot  edit a flow and copy it.
![image](https://user-images.githubusercontent.com/29652263/221132403-6603b980-bcff-4a74-8cf8-3382b1d580df.png)

But I have tried this way it is copied and I am able to modify 

I have selected -->add existing flow ( Env Req Notify Admin when new env Submitted Flow) into unmanaged solution.
I have edited the flow --Save As ---copied the flow and removed the  actual flow from the unmanged solution,
It is successful .
**Note** : This flow is also having child flow in it (for triggering mail).

Now my question is , the article is bit confusing  for flows 

Am I doing correctly or not just wanted to check with you 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Env Req Notify Admin when new env Submitted Flow

**Comment by Jenefer-Monroe** [comment]
Hello, we are rewriting this article to include notes about these limitations. Please see https://github.com/microsoft/coe-starter-kit/issues/4781. 
I'll go ahead and dupe this bug to that, thanks for posting!
