### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Setup Wizard (Step - Run setup flows) is not showing the flows and 'Refresh' button is disabled.

### ISSUE THREAD

**Issue by ashwanidv100** [microsoft/coe-starter-kit#4872]
### Describe the issue

CoE Setup Wizard (Step - Run setup flows)

Is not showing the flows and 'Refresh' button is disabled. 
It's been more than 2hrs, But 'Refresh' button is still disabled. While required flows were turned on automatically.

### Expected Behavior

Can't click on Refresh button. Its Disabled.
Was only had to wait for '15 min' as it mentions in description. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CoE Setup Wizard (Preview)

### Steps To Reproduce

1. Open CoE Setup Wizard (Preview)
2. Start Initial Setup
3. Provide the required details on Step 1,2,3,4
4. Reached to 'Run Setup flows'

### Anything else?

![image](https://user-images.githubusercontent.com/10371826/221152467-c1aff8f6-b12f-4afe-91b0-d6e9b2a76f9c.png)

**Comment by Jenefer-Monroe** [comment]
Hello. This was reworked in 4.3 for this issue. You will need to continue your install manually via [Set up inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) or upgrade to 4.3

Note that 4.3 has been a very stable release so I highly recommend it. 

Thanks for posting!

**Comment by DamoBird365** [comment]
Hi there @Jenefer-Monroe, just to follow up on this particular bug, I had exactly the same experience with a customer, on version 4.3.  The interface showing the progress of the 3 flows did not appear (as per @ashwanidv100), the refresh button took 15+ seconds to go blue/active and the next button remained greyed out/inactive.  We could see that the 3 flows had been enabled and had completed their run.  We tried chrome and edge.  We tried a different machine.  We then decided to clear out the "Setup Wizard State metadata" table and started the wizard again.  As you would expect, existing parameters were saved and loaded into the UI, we worked through the stages and when we got to the above screen, the UI for the flow progress displayed OK, the flows ran a 2nd time and upon completion, we could progress to the next stage.

**Comment by Jenefer-Monroe** [comment]
Thanks for letting us know. The setup wizard has gone through another big transformation for the upcoming release as we work to add the BYODL feature. So I'm afraid the answer here until that is released is just to run these three flows manually. 
Two steps forward :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
