### ISSUE TITLE
[CoE Starter Kit - BUG] No operations listed in custom connector

### ISSUE THREAD

**Issue by ketty3bit** [microsoft/coe-starter-kit#4873]
### Describe the issue

Office 365 Management API custom connector is missing Test Operations.
I'm setting up CoE and attempted to test the Custom Connector before importing the AuditLog solution.  
![API error](https://user-images.githubusercontent.com/34868917/221285473-90aa77c4-6619-4779-90bc-6ff83052c193.png)

Could not test this way, but was able to confirm subscription via powershell.

[SCRIPTS.txt](https://github.com/microsoft/coe-starter-kit/files/10828820/SCRIPTS.txt)

After this I  continued with import of AuditLog solution and received the following: 

Solution "Center of Excellence - Audit Logs" imported successfully with warnings: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'WorkflowOperationInputsApiOperationNotFound' and message 'The 'inputs' of workflow operation 'List_audit_log_content' of type 'OpenApiConnection' are not valid. The API operation 'ListContent' could not be found in API 'admin-5foffice-20365-20management-20api-5fa3d3a862b6e24883'.'."}}". 

Is there any way to correct the APIs missing operations?

Thank You.

### Expected Behavior

![image](https://user-images.githubusercontent.com/34868917/221288192-8af4d55f-a92e-46fe-8ba6-c24dbb3e9305.png)
Expected behavior is to see list of 5 Test operations to choose from and configure so that subscription testing can be performed in the custom connector.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

9.2.23013.172

### What app or flow are you having the issue with?

Office 365 Management API

### Steps To Reproduce

For Center of Excellence (CoE) environment

1. In Azure Active Directory App Registration
> Create app and add Office 365 Management API permissions

2. In Power Apps Custom Connectors
> Edit Connector and update Security page

3. In Azure Active Directory App Registration
> Update Redirect URI

4. In Power Apps Custom Connectors
> Select Edit Connector and navigate to Test page
> Confirm connection or create new connection
	> Operations section (0)

### Anything else?

Seems to be a bug in the connector...  or have I missed something.  

I am unfamiliar with how to create the 5 operations manually

**Comment by ketty3bit** [comment]
Expected behavior pic
![image](https://user-images.githubusercontent.com/34868917/221295035-0e935484-5c58-44b3-9189-1fcd9e127513.png)

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by ketty3bit** [comment]
Below are the components that have been deployed.

![image](https://user-images.githubusercontent.com/34868917/221580988-cd44319e-1482-495d-a04b-923898bf951d.png)

**Comment by ketty3bit** [comment]
The Audit logs component deployed successfully but does not connect and shows errors.
'WorkflowOperationInputsApiOperationNotFound

**Comment by Jenefer-Monroe** [comment]
I've never seen this happen before, and this build is good for the custom connector for folks other than the setup issue do to the [change in default behavior for setup](https://github.com/microsoft/coe-starter-kit/issues/4808) so I dont really know what advice to give here. 

Some random thoughts
- did you change the default identity provider when you setup per https://github.com/microsoft/coe-starter-kit/issues/4808
- is the connector here valid? 
![image](https://user-images.githubusercontent.com/89584709/221673766-22a29fd6-0358-49cf-8854-cb93cb48b3ed.png)
- did you get to the custom connector via this route? 
![image](https://user-images.githubusercontent.com/89584709/221673892-b61a4fc0-b75c-466d-94c6-2cb280f77f5b.png)
- if you go to the defn tab do you see the actions there? 
![image](https://user-images.githubusercontent.com/89584709/221674495-516a372b-0b9c-419e-82bf-2c2e68a46db8.png)

**Comment by ketty3bit** [comment]
Hi Jenefer,
Yes, 

1.   I did encounter the change in default behavior issue when first setting up the connector.  The Identity provider did display Generic OAuth2 and I changed it to Azure Active Directory.     I also had to change the General page...
![image](https://user-images.githubusercontent.com/34868917/221876205-1dd57266-89f2-443a-89ae-f2df53ac816e.png)
the Host displayed api.contoso.com and the base URL contained only a /.

4. The connector is valid...as far as I know.  I have three now, all with different GUIDs.
5. I did use the Custom connectors link on the left panel to access the connector.
6. When I go to the definitions tab, there is nothing there as well.  Says I need to add triggers and actions 
![image](https://user-images.githubusercontent.com/34868917/221875870-1f3378e6-f56e-40dd-b6ea-a6c58cfa2c23.png)

I have tried deleting the connectors and re-adding them with no successful change, but I will try again

**Comment by ketty3bit** [comment]
No luck with deleting the connections and creating a new one.

**Comment by Jenefer-Monroe** [comment]
Yes your custom connector is totally broken, I dont know how this could have happened, I think you will need to reinstall Core to fix this.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
