### ISSUE TITLE
COE -Audit Logs [Child] Admin | Sync Logs Error

### ISSUE THREAD

**Issue by declawson** [microsoft/coe-starter-kit#4874]
Hello,

Upgraded Audit Logs to 3.3 and now getting 'Authorization has been denied for this request' on Action 'List_audit_log_content' failed.  The issue seems to be with the O365 Management API connection     "connectionReferenceName": "shared_admin-5foffice-20365-20management-20api-5f7fc9343cf45734fe",
        "operationId": "ListContent" on the Audit Logs Scope step.  Even though the Connection Reference using my account has a green check mark next to it.

Every time I upgrade the Core Solution which I did I have to re-configure the O365 Management API custom connector but I noticed I now have 2 Connections References for O365 Management.  The first one listed is referenced in the Raw Inputs but I am not able to delete the 2nd one.

![image](https://user-images.githubusercontent.com/74382505/221312979-a03333ed-d742-4bfe-8ca3-d8a560bee8f2.png)

Not sure if this is my issue or not but thought it was worth mentioning.

**Comment by Jenefer-Monroe** [comment]
Hello. As you state, connections to custom connectors get broken on solution upgrade. You can use [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve.

There was a recent product change in which the default identity provider for setting up a custom connector has changed from Azure Active Directory to Generic Oauth2. Please see https://github.com/microsoft/coe-starter-kit/issues/4808 for our bug to update the documentation about this next release. 

One last thought, it sounds like your connections might be broken outside of the context of the custom connector. If you look at them from the Default Solution instead of the Audit Log solution, you can edit and fix them there.

**Comment by declawson** [comment]
I had already tried everything noted below except for editing the connector in the Default solution.  I tried everything and still getting the error.

The flow did not fail until I did the upgrade on Friday, 2/24, see below.

***@***.***

[https://webmail.atcc.org/owa/auth/image001.jpg]
Debbie Clawson
Senior IT Architect

10801 University Boulevard
Manassas, VA 20110-2209
Tel: (703) 365-2700 ext. 2820
Fax: (703) 365-2701
Email: ***@***.******@***.***>

**Comment by Jenefer-Monroe** [comment]
Did you delete the connection? Someone else tried that and it cleaned up the issue from the bad default.

**Comment by declawson** [comment]
I deleted and re-added the connection but now the flow has a connection reference error.

[https://webmail.atcc.org/owa/auth/image001.jpg]
Debbie Clawson
Senior IT Architect

10801 University Boulevard
Manassas, VA 20110-2209
Tel: (703) 365-2700 ext. 2820
Fax: (703) 365-2701
Email: ***@***.******@***.***>

**Comment by declawson** [comment]
***@***.***

Error trying to turn the flow back on.
[https://webmail.atcc.org/owa/auth/image001.jpg]
Debbie Clawson
Senior IT Architect

10801 University Boulevard
Manassas, VA 20110-2209
Tel: (703) 365-2700 ext. 2820
Fax: (703) 365-2701
Email: ***@***.******@***.***>


From: Clawson, Debbie
Sent: Monday, February 27, 2023 3:54 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] COE -Audit Logs [Child] Admin | Sync Logs Error (Issue #4874)

I deleted and re-added the connection but now the flow has a connection reference error.

[https://webmail.atcc.org/owa/auth/image001.jpg]
Debbie Clawson
Senior IT Architect

10801 University Boulevard
Manassas, VA 20110-2209
Tel: (703) 365-2700 ext. 2820
Fax: (703) 365-2701
Email: ***@***.******@***.***>

**Comment by Jenefer-Monroe** [comment]
Note that images do not come through if you respond via email. You will need to log in to GitHub to share pictures with us.

**Comment by declawson** [comment]
![image](https://user-images.githubusercontent.com/74382505/221692766-7d94fd92-40da-488b-8924-1d1b7b47e00c.png)

**Comment by declawson** [comment]
The flow did not fail until I did the upgrade on Friday, 2/24, see below.
![image](https://user-images.githubusercontent.com/74382505/221698996-187de9fb-cb77-4758-8691-a8d266b88d58.png)

**Comment by Jenefer-Monroe** [comment]
That is expected. Unfortunately custom connectors break on upgrade and always need reset. 
The issue that people fell into this month was the change in which the default identity provider for setting up a custom connector has changed from Azure Active Directory to Generic Oauth2. Please see https://github.com/microsoft/coe-starter-kit/issues/4808 for our bug to update the documentation about this next release. 

Did you delete and recreate with Azure Active Directory? 
If so did you recreate the connection after that? https://github.com/microsoft/coe-starter-kit/issues/4808#issuecomment-1446176260
