### ISSUE TITLE
Status 401 in audit log connector[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Andriya02** [microsoft/coe-starter-kit#4876]
### Describe the issue

I was trying to set up the audit log connector in the CoE Kit. But when I gave the details of the tenant and azure app registration details and clicked on start subscription, its throwing a status 401.

The error code shown:
{
  "Message": "Authorization has been denied for this request."
}
**Header:**
[24-02 15:30] Jignesh Raval
{
  "cache-control": "no-cache",
  "content-length": "61",
  "content-type": "application/json; charset=utf-8",
  "date": "Fri, 24 Feb 2023 09:58:13 GMT",
  "expires": "-1",
  "pragma": "no-cache",
  "www-authenticate": "Bearer",
  "x-aspnet-version": "4.0.30319",
  "x-ms-apihub-cached-response": "true",
  "x-ms-apihub-obo": "false",
  "x-powered-by": "ASP.NET"
}

[24-02 15:30] Jignesh Raval
StatusUnauthorized (401)

### Expected Behavior

<img width="400" alt="coe44" src="https://user-images.githubusercontent.com/126411840/221426252-fbc0d091-171b-4c45-8562-5d7597d93021.png">

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Audit log custom connector

### Steps To Reproduce

[https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog]

**Comment by Jenefer-Monroe** [comment]
There was a recent product change in which the default identity provider for setting up a custom connector has changed from Azure Active Directory to Generic Oauth2. Please see https://github.com/microsoft/coe-starter-kit/issues/4808 for our bug to update the documentation about this next release.

**Comment by TedLaidlaw** [comment]
FWIW I came here to raise the same issue and the above has me working again.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
