### ISSUE TITLE
[CoE Starter Kit - QUESTION] disabled users as orphan

### ISSUE THREAD

**Issue by HimanshuPadhiyar** [microsoft/coe-starter-kit#4881]
### What is your question?

Azure ad users account = disabled  are not marked as orphaned

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

**Comment by manuelap-msft** [comment]
There is an environment variable - **Disabled Users are Orphaned** - that by default is set to No, if you do want to consider disabled users as orphans you will have to update that to Yes. Here's how to [update environment variables](https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
