### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cannot test Custom Connector as account does not have access to App Registration

### ISSUE THREAD

**Issue by pndi021** [microsoft/coe-starter-kit#4882]
### Describe the issue

We added the service account as an owner of the app registration related to the audit logs.
When we attempt to test the connection, we get the following error (we added all permissions as specified in the doc and have granted consent for this dedicated app registration in Azure)

AADSTS50105: Your administrator has configured the application powerplatform-coe-audit-logs-prd to block users unless they are specifically granted ('assigned') access to the application. The signed in user 'xxx' is blocked because they are not a direct member of a group with access, nor had access directly assigned by an administrator. Please contact your administrator to assign access to this application.

Could you come back to me with a solution? Thank you in advance.

Regards

### Expected Behavior

The custom connector should be turned on indicated by 200 or 400 status code (we cannot get to that step because of the issue specified above)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Office 365 Management API  (step right after security settings) 

### Steps To Reproduce

Power Apps 
Custom Connectors
Office 365 Management 
APITest 
New Connection

**Comment by manuelap-msft** [comment]
Hello,

this seems to be related to how your administrator has set up the Azure App Registration - it sounds like your user does not have permission to use this App Registration or it is otherwise blocked from being used. Unfortunately this exceeds the scope of what we're able to help with, and you'll have to work with your admin to give you access to the App Registration there.

**Comment by pndi021** [comment]
Issue fixed, thank you
