### ISSUE TITLE
[CoE Starter Kit - BUG] Help with old install

### ISSUE THREAD

**Issue by adminPP23** [microsoft/coe-starter-kit#4884]
### Describe the issue

COE starter kit was installed about 6 months back before me coming on board so I have no history of how it was done before. It looks like the Dashboard from COE toolkit are not refreshing and not showing revised data. MS support mentioned to contact here first. Would someone help me resolve and fix the issue.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

NA

### What app or flow are you having the issue with?

NA

**Comment by Jenefer-Monroe** [comment]
Unfortunately we are a very small team and cannot scale to assist with exploration of old issues like this. We suggest people upgrade at least every 3 months in order for us to try and assist as we just cannot keep track of the state of the kit from that long ago. 

Given that you werent actively using the kit anyway, and that its in a bad state. You are likely best off just starting from scratch in a new environment. The Feb release is a very high quality stable release so I suggest you grab that and put it into a new environment and start over. Begin by reading [Before setting up the CoE Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/setup)

**Comment by adminPP23** [comment]
Thanks Jenefer for your feedback, I appreciate it. The issue is when I was hired, no one took ownership of updating COE toolkit prior to me joining, they just installed and did not maintain/update. Are you suggesting that I delete the environment where its currently published/installed and start fresh with a new install in new env?

**Comment by Jenefer-Monroe** [comment]
Yep, you will be best served starting all the way from scratch. Please post issues as you go if you get stuck, we are here to help!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
