### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why do I get a forbidden error in the Set App Quarantine State step?

### ISSUE THREAD

**Issue by mperezMinsait** [microsoft/coe-starter-kit#4885]
### What is your question?

When executing this action in a step of a flow in power automate, it gives a forbidden error but the connection is configured with a user that has the role of global admin

### What solution are you experiencing the issue with?

None

### What solution version are you using?

February 2023

**Comment by Jenefer-Monroe** [comment]
Appologies but I am having trouble following you. Can you please share a screenshot of where you see this?

**Comment by mperezMinsait** [comment]
![image](https://user-images.githubusercontent.com/91242283/222077190-1f656e7c-14b2-45f2-82c4-b0a1754d39de.png)

**Comment by mperezMinsait** [comment]
The problem is that when I try to use the PowerApps for Admins Set App Quarantine State action in a Power Automate flow to quarantine an app, I get a Forbidden error. I get a message indicating that only administrators can execute this action, but the user with whom the connection is configured is a global admin.

**Comment by Jenefer-Monroe** [comment]
Can you please share the screenshot of where you are performing the action and the error? Rather than the flow

**Comment by mperezMinsait** [comment]
***@***.***

This is the screenshot of the error. The problem is that it indicates that "Only administrators can set the application quarantine status" but the user with whom that action is executed is a user who is global admin. The error occurs in the action seen in the screenshot, in a manual execution flow.

I await your comments.

Thanks,

[minsait]<http://www.minsait.com/>

Manuel Pérez Rodríguez
Tecnologías Avanzadas
[Twitter]<https://twitter.com/minsaitbyindra>
[Linkedin]<https://www.linkedin.com/company/minsait>
[Youtube]<https://www.youtube.com/channel/UCdz8akghznOoBVd2KhFW4Qw>

**Comment by Jenefer-Monroe** [comment]
How do you execute the item? That is what I am asking.

**Comment by mperezMinsait** [comment]
We keep having the same problem. I have carried out the test in 2 different tenants and the error is the same. In both cases, the role of the user with whom the power apps for admins connection is configured is power platform administrator.
To execute this type of action, does the user need to have any other specific role? Because even if the user is global admin it gives us the same error. "Only administrators can set the app's quarantine status."
I am attaching the screenshot with the parameters of how we call the action to quarantine an app and the link where the operation of that action is detailed and where it indicates that the administrator users are the ones who can execute the action, but that in In our case, that is not working.
![actionQuarentineApp](https://user-images.githubusercontent.com/91242283/223144301-eba4908e-a7a4-4353-bf25-4c74b49aceda.PNG)
Link Action:
https://learn.microsoft.com/en-us/connectors/powerappsforadmins/#set-app-quarantine-state

**Comment by Jenefer-Monroe** [comment]
sorry what I need is a picture of where you hit a button etc. I presume you did not run this flow manually correct? Or create your own new flow.

**Comment by mperezMinsait** [comment]
This is a flow that we are using to test this type of action, so we run it manually. The idea is that when the action in this flow works we will create a new flow scheduled to run recursively.

**Comment by Jenefer-Monroe** [comment]
We are a small team and so not staffed to assist with customizations. 
Please test this from the Power Platform Admin view app as shown here
![image](https://user-images.githubusercontent.com/89584709/223169602-2a3bd7da-eb7b-40a0-bf13-af1a7a8a6d44.png)

That will cause the flow to run as shown here. 
![image](https://user-images.githubusercontent.com/89584709/223169987-df2ed853-c02f-492a-b2ca-d460bf8ddd14.png)

Let me know if that passes.
