### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View' app cannot be associated to more than one component library. 

### ISSUE THREAD

**Issue by greena-blast** [microsoft/coe-starter-kit#4887]
### Describe the issue

I am trying to upgrade/update CenterofExcellenceCoreComponents managed solution, however whether I try to upgrade or update, it throws an error:
Solution "Center of Excellence - Core Components" failed to import: Import of app module(s) failed: 'Power Platform Admin View' app cannot be associated to more than one component library. Already exist component library count 1. In Solution Import, please remove library either from Source or Target and try again.
![image](https://user-images.githubusercontent.com/92062149/221920059-cbe1bab9-51f7-466f-831e-997cfe4aef26.png)

I don't know how to remove the component library from a managed solution and equally I don't know how to remove it from the .zip file that I am trying to import.  I also looked into uninstalling the current core component solution altogether from our environment, however it has dependencies which I don't know how to break.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Component library

**Comment by Jenefer-Monroe** [comment]
You've hit a product bug that a few other customers have hit, its an issue outside the context of the kit but luckily one of the users figured it out and posted a comment with how they did it. 
https://github.com/microsoft/coe-starter-kit/issues/4375#issuecomment-1345554161

Hope that helps!

**Comment by greena-blast** [comment]
Hi, I saw that post as well and tried the steps, however didn't get anywhere. From the comments it looks like this fix is for unmanaged solution, whereas I am dealing with managed solutions. Any other ideas? Can I get an older version of CoE and upgrade to it instead? If so, please point me to the location of the install link as I couldn't find it.

**Comment by Jenefer-Monroe** [comment]
You will need to contact product support to get their assistance then. 
The builds before we added a component library are now quite old so while you could use them, we would not be able to assist you. 
All old releases are here: https://github.com/microsoft/coe-starter-kit/releases
And each has this "Assets" section where you can download what was delivered that release. 
![image](https://user-images.githubusercontent.com/89584709/222473261-0d738b48-604b-4c3a-a73a-d0647a1884a2.png)

**Comment by greena-blast** [comment]
Can you please let me know how to contact the product support?

**Comment by Jenefer-Monroe** [comment]
That depends a little on what type of tenant you are, but here is the approach available to everyone. Hope that helps! 
https://learn.microsoft.com/en-us/power-platform/admin/get-help-support

**Comment by manuelap-msft** [comment]
closing out some old issues that we missed to close. no further action from coe kit team.
