### ISSUE TITLE
[AA4AM] Align Issue Templates for ALM Accelerators with CoE Starter Kit

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#489]
The generic issue templates we have now should align to the CoE Starter Kit Issue Templates to help guide users through issue creation and categorize issues better. ~~Additionally, need to clean up the Issue Template folder that got added to the ALMAcceleratorSampleSolution branch incorrectly~~.

**Comment by mikefactorial** [comment]
Assigning to @jenschristianschroder per our conversation this morning

**Comment by jenschristianschroder** [comment]
removed requirement to clean ALMAcceleratorSampleSolution as per our conversation today

Created new issue for cleaning ALMAcceleratorSampleSolution, #587

**Comment by mikefactorial** [comment]
@mikefactorial This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.
