### ISSUE TITLE
Audit Logs seem to no longer work for GCC

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#4890]
The last Launch date never updates however if add an app, add an owner, or change the owner the dashboards do update. But the Last Launched Date never does.

I am reviewing the [Child] Admin | Sync Logs and this is what was after installation: 

![image](https://user-images.githubusercontent.com/117682988/221961684-25756dce-dec4-4323-bfc7-6541829a0aca.png)

It runs successfully is there something missing from this flow?

**Comment by Jenefer-Monroe** [comment]
Please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

A picture like this showing if the flows are running successfully:
![image](https://user-images.githubusercontent.com/89584709/161313264-d2ebd13d-1123-4751-b541-ea99a2b89313.png) 

And a picture like this showing if any data is populating
![image](https://user-images.githubusercontent.com/89584709/164469099-1cb27bec-a1b8-4a22-8b2c-c9bdb50d7d33.png)

**Comment by mdphung** [comment]
One more screen shot: 
![image](https://user-images.githubusercontent.com/117682988/222484639-5d72fe99-5dbd-4308-9c2d-0f48ecaf0260.png)

**Comment by Jenefer-Monroe** [comment]
Are you a commercial tenant? Or something else (like GCC)

**Comment by mdphung** [comment]
My apologies for the delay, This is a GCC tenant.

**Comment by Jenefer-Monroe** [comment]
Do you get data if you use the list content test command?
![image](https://user-images.githubusercontent.com/89584709/224406974-24ab4855-b314-4cd0-93a4-d9621e012a6b.png)

**Comment by javiles1327** [comment]
I am having the same issue, also on the GCC Tenant.  The ListContent test on the connector succeeded and appears to be pulling data from yesterday.
the last date that i have data from on the App Last Launched was the same day prior to the time that i upgraded my CoE Core components.
Other audit log data appears to be working.

**Comment by mdphung** [comment]
Also when I try to run the other option with this listed content id. This is what happens.

![image](https://user-images.githubusercontent.com/117682988/224733112-95e585f2-a755-40f3-93e2-f4d7e9c70dc8.png)

**Comment by Jenefer-Monroe** [comment]
I'm not used to the list contents only bringing back one thing. I"ve never seem that actually. 
Did you enter the entire contentid for the input to ListContentDetails?
![image](https://user-images.githubusercontent.com/89584709/224816092-7a1e3ba6-6734-40c4-88a2-48c4ff84f162.png)

**Comment by mdphung** [comment]
Yeah, I entered all the information for the Content ID which I got from the list content it only errors out on List Content Details.

**Comment by Jenefer-Monroe** [comment]
Whats the rest of this error message?
![image](https://user-images.githubusercontent.com/89584709/224818719-09480858-c23d-48d4-8b6b-b3680c7c5895.png)

**Comment by Jenefer-Monroe** [comment]
ok im not sure. It seems like the back end may have changed for GCC. This still works for Commercial. We would need to put on our backlog investigating this.

**Comment by javiles1327** [comment]
> ok im not sure. It seems like the back end may have changed for GCC. This still works for Commercial. We would need to put on our backlog investigating this.

How long before we can find out more on this situation?

**Comment by Jenefer-Monroe** [comment]
We do not have the bandwidth to investigate this right now unfortunately. If someone from the community can investigate and figure out what is happening, then we could likely update with the found fix.

**Comment by idea01** [comment]
Hi @Jenefer-Monroe, just wondering if this issue has been added to the roadmap.

**Comment by Jenefer-Monroe** [comment]
Hello no we have not been able to investigate this issue yet. Will let you know if we do. 
If you are able to investigate further and find the source of the issue that would help us to move this faster.

**Comment by idea01** [comment]
Hi @Jenefer-Monroe , just wondering if this issue has been added to the roadmap.

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry for the delay, have been waiting for these docs to get published for you. 
We have a new way of setting up audit logs that does not rely on the custom connector. Can you please give it a try? https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http

**Comment by Jenefer-Monroe** [comment]
common issues are:

1. Environment variables cached - turn this flow off and back on and that will resolve if this is the issue
2. Forgot to change the app registration from delegated to application. See https://github.com/microsoft/coe-starter-kit/issues/6009
3. Make sure you used the secret value as well and not its GUID. Thats something people do farely often ![image](https://user-images.githubusercontent.com/89584709/225953435-8d2d5b8c-1fdd-4e24-92c0-e4618c23f1fa.png)

**Comment by mdphung** [comment]
We have a file that is 201MBs when we chose it it doesnt seem to want to pull the file in for us to import. If we chose a file that is 20MBs it takes. Is there a limitation on size?

**Comment by Jenefer-Monroe** [comment]
There is, and that is just the product feature itself on file import unfortunately, not something from our tools that we casn improve.

**Comment by mdphung** [comment]
Ok no problem, So what is the size limitation, is it 20MBs?

**Comment by Jenefer-Monroe** [comment]
I'm not certain, I believe people were able to upload 50 MB files. I know you can upload them simultaneously too for our case.

**Comment by mdphung** [comment]
oh okay so for example lets say I was only able to get a 1 week's worth just to help with the size limitation of app-launched data from compliance should i load week to week into the tool until I can at least get a quarters worth of data thoughts?

**Comment by mdphung** [comment]
also what happens if I import on app by app is that possible to work that way if for example the imports I have do not seem to have that app.

**Comment by Jenefer-Monroe** [comment]
I'm afraid I havent tested all that as ways to import old data. It seems like that would work though.
To set expectations, this is just a way to load old data, you will not need to do this on an ongoing basis.
