### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot open the "Power Platform Administration Planning.pbit" file

### ISSUE THREAD

**Issue by pndi021** [microsoft/coe-starter-kit#4893]
### Describe the issue

When launching the "Power Platform Administration Planning.pbit" file, we get the following error"

"pcat_admintasksMicrosoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)"

The service account that we connect with has full access to the dataverse tables when going through the solutions in Power Apps

### Expected Behavior

Opening the dashbord for publishing

### What solution are you experiencing the issue with?

Admin Task Planner

### What solution version are you using?

1.2

### What app or flow are you having the issue with?

Power Platform Administration Planning.pbit

### Steps To Reproduce

Launch the file "Power Platform Administration Planning.pbit"
Paste the org url with no https://
Then it spins a little bit and we get the error specified in the issue text box above

**Comment by manuelap-msft** [comment]
Hello,

this typically indicates some network-related issues / blocked ports needed for this dashboard.

Please review:
- Our troubleshooting tips here https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting
- Power BI requirements to use the TDS endpoint https://learn.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#blocked-ports
- Troubleshooting connection issues https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query#troubleshooting-connection-problems

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
