### ISSUE TITLE
[ALM Accelerator - Feature]: Deploy without commit

### ISSUE THREAD

**Issue by ryanhodgson1** [microsoft/coe-starter-kit#4895]
### Is your feature request related to a problem? Please describe.

We have people in our support team that create the pull requests from ALM into specific environments for releases, but they cant deploy (its greyed out) unless they have done a commit for that solution before.

![image](https://user-images.githubusercontent.com/77652317/222059354-72f5e4f9-ef88-4dbf-aa3c-d370fdda6731.png)

### Describe the solution you'd like

We want to be able to deploy to environments without having to commit first

**Comment by mikefactorial** [comment]
Good feedback @ryanhodgson1. I think the original intent of disabling it was to make the steps clearer to new makers, but it seems like it is blocking more advanced usage. Will look into addressing this scenario.
