### ISSUE TITLE
[CoE Starter Kit - QUESTION] Authorization denied when using custom connector

### ISSUE THREAD

**Issue by keharrin** [microsoft/coe-starter-kit#4897]
### Describe the issue

After updating COE Toolkit with 3.3 version, the Child Sync Flow continues to error with 
{
  "Message": "Authorization has been denied for this request."
}
[7:53 AM] Mukthipudi, Baby
{
  "Pragma": "no-cache",
  "x-ms-apihub-cached-response": "true",
  "x-ms-apihub-obo": "false",
  "Cache-Control": "no-cache",
  "Date": "Wed, 01 Mar 2023 13:09:04 GMT",
  "WWW-Authenticate": "Bearer",
  "X-AspNet-Version": "4.0.30319",
  "X-Powered-By": "ASP.NET",
  "Content-Length": "61",
  "Content-Type": "application/json; charset=utf-8",
  "Expires": "-1"
}

We have attempted the troubleshooting mention in https://github.com/microsoft/coe-starter-kit/issues/4874 and https://github.com/microsoft/coe-starter-kit/issues/4808 but error remains.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by manuelap-msft** [comment]
Connections to custom connectors get broken on solution upgrade. You can use [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve.

There was a recent product change in which the default identity provider for setting up a custom connector has changed from Azure Active Directory to Generic Oauth2. Please see https://github.com/microsoft/coe-starter-kit/issues/4808 for our bug to update the documentation about this next release. 

If you have made the updates to change the identity provider to Azure Active Directory, you may need to delete the old connections and then re-create a new one for this to start working - here's two suggestions on how to get this working:
https://github.com/microsoft/coe-starter-kit/issues/4808#issuecomment-1446176260
https://github.com/microsoft/coe-starter-kit/issues/4808#issuecomment-1446650853

**Comment by keharrin** [comment]
We have attempted the steps from all these articles and have been unsuccessful in resolving this issue using those steps.

**Comment by manuelap-msft** [comment]
Can you
1. Navigate to your CoE environment > Solutions
2. Select the **Default Solution**
3. Select **Connection References**
4. Open the Office 365 Management API CenterofExcellenceAuditLogs-8f08c and Office 365 Management API CenterofExcellenceAuditLogs-a3e3b
  ![image](https://user-images.githubusercontent.com/55705669/222174412-477f0c31-9976-48b0-9787-ad867d626494.png)
5. Confirm they both show a valid connection. This should show as an email address/account and not a GUID
![image](https://user-images.githubusercontent.com/55705669/222174774-076f3c48-fcd0-4ac0-971b-aafb5fd99940.png)


Then
1. Navigate to your CoE environment > Solutions
2. Open the Audit Log solution
3. View details on the [Child] Admin | Sync Logs
4. Verify that all the Connection References show with a green check
![image](https://user-images.githubusercontent.com/55705669/222175048-0a02fe95-fb0b-4703-870b-021f6d00c66c.png)
5. Open the Run only users settings of the child flow and verify the Office 365 Management API is set to use this connection
![image](https://user-images.githubusercontent.com/55705669/222175352-062a2698-0b90-43a2-b34e-b81c04f6bea3.png)

**Comment by keharrin** [comment]
We have completed these steps but the error is not resolved.

**Comment by kblasi14** [comment]
> We have completed these steps but the error is not resolved.

We had to re-import the AuditLogs solution because we had made so many changes trying to correct this. After re-importing and following the steps above, it finally worked for us.

**Comment by dcboddie** [comment]
For my installation, Office 365 Management API CenterofExcellenceAuditLogs-8f08c and Office 365 Management API CenterofExcellenceAuditLogs-a3e3b don't show up under Connection References in step #4. Is there a flow that I didn't run?

**Comment by keharrin** [comment]
We had to delete and then re-import the Audit Solution and we were then successful in applying the identity provider update similar to @kblasi14

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
