### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by jayatraining** [microsoft/coe-starter-kit#4905]
### Describe the issue

Admin - Sync Template v3 was initially disabled. This is most likely the reason why the Power Platform Admin View was not showing up to date data. So I have enabled Sync Template v3 but the flow still didn't run after checking it the following day.

I also checked the trigger of the flow and it is currently set to run once daily but no time zone, start time, hours and minutes were specifically setup. 
![image](https://user-images.githubusercontent.com/122872573/222681206-485091e1-4b18-4489-8f82-2dc99717abd6.png)

I am new to using CoE and I am hesitant to make any changes specially the solution being a managed solution which will create an unmanaged layer if I was to amend the trigger

### Expected Behavior

For Admin - Sync Template v3 to run.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.31

### What app or flow are you having the issue with?

Sync Template v3

### Steps To Reproduce

1. Enabled Sync Template v3
2. Check if it has run the following day

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
