### ISSUE TITLE
[CoE Starter Kit - BUG] Error with initial loading of PBI report - Query 'Flow' (step 'Removed Columns') references other queries

### ISSUE THREAD

**Issue by ryanwalker726** [microsoft/coe-starter-kit#4907]
### Describe the issue

For context, I was having issues with an old CoE environment, so I'm reinstalling everything from scratch in a new environment.  I'm installing the February 2023 release.  When initially opening the Production_CoEDashboard_February2023.pbit, I get this error:

**Flow
Query 'Flow' (step 'Removed Columns') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination.**

All other query loading stops, because of that error.  It's the exact same error as [Issue #4144](https://github.com/microsoft/coe-starter-kit/issues/4144).  Using all of the newest components and a completely fresh environment and the Feb. 2023 version of Power BI desktop.

### Expected Behavior

Report loads without error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Production_CoEDashboard_February2023.pbit

### Steps To Reproduce

1. Install core components following the instructions / and the new wizard that comes with the Feb. 2023 release.
2. At the point where it's appropriate to publish the Power BI dashboard, load the Production_CoEDashboard_February2023.pbit template
3. Receive error

**Comment by Jenefer-Monroe** [comment]
Hello, we have seen this error before when people were on an old version of Power BI Desktop. What version of Power BI Desktop are you on and are you able to upgrade to the latest?

**Comment by ryanwalker726** [comment]
Thanks for the suggestion, Jenefer.  I am running what I thought was the most recent version of PBI Desktop (Feb. 2023), but like the original ticket that I referenced, the problem seemed to clear up on its own.  We can close this ticket, but I don't have an explanation for why it's working now...  I didn't do anything to change my PBI Desktop installation.

**Comment by Jenefer-Monroe** [comment]
thanks for letting us know! Glad this resolved!
