### ISSUE TITLE
[CoE Starter Kit - BUG] Production_CoEDashboard loads with 0 rows (blanks). No data loading

### ISSUE THREAD

**Issue by adrianmorita** [microsoft/coe-starter-kit#4909]
### Describe the issue

Just installed core components following the instructions / and the new wizard that comes with the Feb. 2023 release (including creator kit). At the point where it's appropriate to publish the Power BI dashboard, load the Production_CoEDashboard_February2023.pbit template and insert the org url, it loads all columns for each table, but none of them have rows. No errors received.

Se below

![image](https://user-images.githubusercontent.com/126913121/222813584-1c875b21-baa6-4539-be88-5c733b40b0fa.png)

### Expected Behavior

In the past, all environment details will come right away, top flow makers, app makers, etc. This is no longer the case. All sync flows are running just fine. All solution core flows are turned on. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Production_CoEDashboard_February2023.pbit

### Steps To Reproduce

In PROD. Just installed core components following the instructions / and the new wizard that comes with the Feb. 2023 release (including creator kit). At the point where it's appropriate to publish the Power BI dashboard, load the Production_CoEDashboard_February2023.pbit template and insert the org url, it loads all columns for each table, but none of them have rows. No errors received.

### Anything else?

We had the same dashboard published since 2021. It stopped refreshing this year. So decided to reinstall the kits to see if that would make the trick, but still the same

**Comment by Jenefer-Monroe** [comment]
Are you logged in to PBI as a user that has access to the environment?

**Comment by adrianmorita** [comment]
Yes. A full cloud admin account. Again, this dashboard work as a champ
during 2021 and 2022. Last refresh was 12/23/2022. Since then, no
successful refreshed have happened.

Trying the latest CoE version didn't do the trick either. Instead, if shows
up blank for all tables (0 rows)

**Comment by Jenefer-Monroe** [comment]
Please log in as this same user to the CoE envt, and go to the Power Platform Admin View app. Do you see data there? 
![image](https://user-images.githubusercontent.com/89584709/222926863-09687c85-e31f-4d18-b3b6-02227fa687db.png)

**Comment by adrianmorita** [comment]
After 2 days, the data started to populate. It must have been a delay in
the sync flows running. Please consider this resolved.

Thanks

**Comment by Jenefer-Monroe** [comment]
Wonderful news. Thanks for letting us know!
