### ISSUE TITLE
[CoE Starter Kit - Feature]: App Catalog - Launch app from card

### ISSUE THREAD

**Issue by RyanFeagleyFIS** [microsoft/coe-starter-kit#4912]
### Describe the solution you'd like

Within the App Catalog app I would like to request a Launch App button directly on the card similar to the button we see in the command center apps.

Current:
![image](https://user-images.githubusercontent.com/124791378/223152468-85fd3b0a-7b4b-4fc2-8dae-0fd7d8324cde.png)

Request:
![image](https://user-images.githubusercontent.com/124791378/223151262-d04857b2-746f-4c29-80a3-75f43f0fd6f8.png)

**Comment by Jenefer-Monroe** [comment]
thanks for posting, will put on the backlog.
do note in the meantime that there is a launch app button from the details page
![image](https://user-images.githubusercontent.com/89584709/223209502-4160cf8c-0cfa-493e-be4d-9f78b7933339.png)

**Comment by RyanFeagleyFIS** [comment]
Thank you!  This is exactly what we're communicating to our users at this point.  This enhancement would simply remove a click for users who use this interface to launch the apps they use.

**Comment by Jenefer-Monroe** [comment]
Makes sense. I'm not sure if there was a reason she did it this way, but if not this would be an easy fix for us.

**Comment by manuelap-msft** [comment]
We've given the App Catalog a UX refresh (same as the Command Center) so it will include the same buttons now:
![image](https://user-images.githubusercontent.com/55705669/223386735-e3694081-d882-4ab8-a63f-9b1c554e98cf.png)

This will be ready with the April release.

**Comment by manuelap-msft** [comment]
Added launch button but this doesn't check if you have access to the app so you could click launch and then get to an access denied page.
