### ISSUE TITLE
Office 365 Mgmt API connection for Child Admin | Sync Logs

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#4915]
When I try to edit this flow, there are three connections that will be used. The Office 365 Mgmt API connection needs to be fixed. When I click "Fix connection" I get this error:

AADSTS50011: The redirect URI 'https://global.consent.azure-apim.net/redirect' specified in the request does not match the redirect URIs configured for the application '5f9c8a00-6e79-41f3-8128-845e6e7012e0'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. 

Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

I have verified that there is no URI mismatch. That hasn't changed for a few months now and it was working fine until I tried to update it over a week ago.

I did this, https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#update-azure-ad-app-registration-with-the-redirect-url, when I set up the custom connector and it worked fine.

**Comment by Jenefer-Monroe** [comment]
Hello. Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

Note also that there was a recent product change in which the default identity provider for setting up a custom connector has changed from Azure Active Directory to Generic Oauth2. Please see https://github.com/microsoft/coe-starter-kit/issues/4808 for our bug to update the documentation about this next release.

**Comment by RickKush** [comment]
😊

From: Jenefer Monroe ***@***.***>
Sent: Monday, March 6, 2023 5:37 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Office 365 Mgmt API connection for Child Admin | Sync Logs (Issue #4915)


Hello. Connections to custom connectors get broken on solution upgrade. Please see issue 1424<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/issues/1424__;!!May37g!MmSoTJ-Q4SAqLlmvaSS6C8LXraiOoF7BHB-n9uBgyTxqe-7GaUqv73jmZ5N8IMdJOma4nOhTTfKcKmzdw9SSblCyNw$> for how to resolve

Note also that there was a recent product change in which the default identity provider for setting up a custom connector has changed from Azure Active Directory to Generic Oauth2. Please see #4808<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/issues/4808__;!!May37g!MmSoTJ-Q4SAqLlmvaSS6C8LXraiOoF7BHB-n9uBgyTxqe-7GaUqv73jmZ5N8IMdJOma4nOhTTfKcKmzdw9QEcd5OCw$> for our bug to update the documentation about this next release.

**Comment by RickKush** [comment]
[Child] Admin | Sync Logs
Runtime error:

Action 'List_audit_log_content' failed

Error from token exchange: The connection (unitedstates-002/admin-5foffice-20365-20management-20api-5fa86a7a016182459a/1e50100c497145e5923212e0bd7199da) is not found. Please create new connection and change your application to use the new connection.



From: Jenefer Monroe ***@***.***>
Sent: Monday, March 6, 2023 5:37 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Office 365 Mgmt API connection for Child Admin | Sync Logs (Issue #4915)


Hello. Connections to custom connectors get broken on solution upgrade. Please see issue 1424<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/issues/1424__;!!May37g!MmSoTJ-Q4SAqLlmvaSS6C8LXraiOoF7BHB-n9uBgyTxqe-7GaUqv73jmZ5N8IMdJOma4nOhTTfKcKmzdw9SSblCyNw$> for how to resolve

Note also that there was a recent product change in which the default identity provider for setting up a custom connector has changed from Azure Active Directory to Generic Oauth2. Please see #4808<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/issues/4808__;!!May37g!MmSoTJ-Q4SAqLlmvaSS6C8LXraiOoF7BHB-n9uBgyTxqe-7GaUqv73jmZ5N8IMdJOma4nOhTTfKcKmzdw9QEcd5OCw$> for our bug to update the documentation about this next release.

-

**Comment by Jenefer-Monroe** [comment]
Hello screenshots woudl be really helpful to know for sure where you are at in the steps. And please note that screenshots only come through if you are logged in to GitHub. They will not come through if you respond in email. 

Please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

**Comment by RickKush** [comment]
The last correction that I made was selecting a connection for the Office 365 Mgmt API in the Child Admin: Sync Log settings:
![image](https://user-images.githubusercontent.com/116654106/223524929-39e113fd-892f-428e-b011-40479370762c.png)

**Comment by RickKush** [comment]
Here's the connection used in the Ofc 365 Mgmt API custom connection:
![image](https://user-images.githubusercontent.com/116654106/223526647-ede2cc3b-5cf4-4d7b-b1a2-6362b1826bca.png)

**Comment by RickKush** [comment]
... and here is the current error
![Auth](https://user-images.githubusercontent.com/116654106/223526980-1d7c93eb-f780-45d1-a465-5c75d2462165.PNG)

**Comment by Jenefer-Monroe** [comment]
Please try the list content test action here
![image](https://user-images.githubusercontent.com/89584709/223734447-e230db5e-b743-4a16-a47e-6e390143c61d.png)

As well as a search through the UX
https://compliance.microsoft.com/auditlogsearch

**Comment by Jenefer-Monroe** [comment]
And note also that for folks that fell into the recent 401 error, there are a few more steps some are having to go through. 

Please look through the entire thread on https://github.com/microsoft/coe-starter-kit/issues/4808

**Comment by RickKush** [comment]
I read to the bottom of #4808, but it was just a bunch of comments. Is there something particular that I should find there?

From: Jenefer Monroe ***@***.***>
Sent: Wednesday, March 8, 2023 9:15 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Office 365 Mgmt API connection for Child Admin | Sync Logs (Issue #4915)


And note also that for folks that fell into the recent 401 error, there are a few more steps some are having to go through.

Please look through the entire thread on #4808<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/issues/4808__;!!May37g!IFiiyAKCrnQ8XhXgOL80mZwpBF5Xbews2yipE2xZ5bTxXrD97Oo4W4GlHrm1B2cee57jjTSK5gBrdrWNTUbVnO1PkA$>

-

**Comment by RickKush** [comment]
I read to the bottom of #4808, but it was just a bunch of comments. Is there something particular that I should find there?


From: Jenefer Monroe ***@***.***>
Sent: Wednesday, March 8, 2023 9:15 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Office 365 Mgmt API connection for Child Admin | Sync Logs (Issue #4915)


And note also that for folks that fell into the recent 401 error, there are a few more steps some are having to go through.

Please look through the entire thread on #4808<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/issues/4808__;!!May37g!IFiiyAKCrnQ8XhXgOL80mZwpBF5Xbews2yipE2xZ5bTxXrD97Oo4W4GlHrm1B2cee57jjTSK5gBrdrWNTUbVnO1PkA$>

-

**Comment by RickKush** [comment]
In here, https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content, it says, "5. Paste the application (client) ID into PublisherIdentifier."

**Comment by Jenefer-Monroe** [comment]
We dont use the publisher here. so it being tenantid is fine. bad design from years ago. 

Since you made a new connection you need to reset the Run Only Users command
![image](https://user-images.githubusercontent.com/89584709/224408057-366bfbf6-493e-464d-8824-2b29a45f4948.png)
![image](https://user-images.githubusercontent.com/89584709/224408492-9e0fa7f3-5cea-4ee8-ac72-a3666d59b157.png)

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

My Power Platform admin account, ***@***.******@***.***> is the only run only user who created and owns the Office 365 Mgmt API COE custom connection and also installed and owns everything in the COE environment.

This is what I find in the permissions for the run only users. The right user account is already present in all four of these connections, but the first and last, the two Ofc 365 Mgmt APIs, both have the same connection four times to choose from. Do I need to be able to choose the right one? I chose the one at the bottom, hopefully the last one created. But the error still says, "Authorization has been denied for this request" for the Child Sync Logs flow...

***@***.***

From: Jenefer Monroe ***@***.***>
Sent: Friday, March 10, 2023 2:28 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Office 365 Mgmt API connection for Child Admin | Sync Logs (Issue #4915)


We dont use the publisher here. so it being tenantid is fine. bad design from years ago.

Since you made a new connection you need to reset the Run Only Users command
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/224408057-366bfbf6-493e-464d-8824-2b29a45f4948.png__;!!May37g!LEpPcWcP9ZdBr7bgUYnUVdDAQJbJOaPJGaXjU3yaCx2jMjwaLoAbFBKsA-IBqZwVsgxnEN-_mYY6iLO6S3LJbF7ZLg$>
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/224408492-9e0fa7f3-5cea-4ee8-ac72-a3666d59b157.png__;!!May37g!LEpPcWcP9ZdBr7bgUYnUVdDAQJbJOaPJGaXjU3yaCx2jMjwaLoAbFBKsA-IBqZwVsgxnEN-_mYY6iLO6S3J_ays-SA$>

-

**Comment by Jenefer-Monroe** [comment]
I woudl recommend deleting all the connections to the custom connector and starting with a new one. You may be selecting one with the incorrect (anon) access.

**Comment by RickKush** [comment]
This is what I get when I try to create a new connection:

Failure passed to redirect url. error=access_denied error_description=AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 5f9c8a00-6e79-41f3-8128-845e6e7012e0(Flow Runs). Resource value from request: https://manage.office.com. Resource app ID: c5393580-f805-4401-95e8-94b7a6ef2fc2. List of valid resources from app registration: 7df0a125-d3be-4c96-aa54-591f83ff541c, 00000003-0000-0000-c000-000000000000. Trace ID: 5f8a1048-4202-4600-a60e-8307866a6100 Correlation ID: 1b1f2515-06ab-4b7e-84ce-99884d96b781 Timestamp: 2023-03-10 20:07:32Z

From: Jenefer Monroe ***@***.***>
Sent: Friday, March 10, 2023 3:01 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Office 365 Mgmt API connection for Child Admin | Sync Logs (Issue #4915)


I woudl recommend deleting all the connections to the custom connector and starting with a new one. You may be selecting one with the incorrect (anon) access.

-

**Comment by RickKush** [comment]
TYVM!!!
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Saturday, March 11, 2023 6:02:56 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Office 365 Mgmt API connection for Child Admin | Sync Logs (Issue #4915)


I did a full write up for this situation since so many people are hitting it. Please see issue 4961<https://urldefense.com/v3/__https://github.com/microsoft/coe-starter-kit/issues/4961__;!!May37g!LQDYeCXwybv7VFV1WOBaK0D4aAIDEjpGoAC7s3ODqTdbDPwU2OtOYBpBRPp-ze5laG0QFC_zmXt8K2JI-3fDC_MNGA$>

**Comment by Jenefer-Monroe** [comment]
You are so welcome, sorry it took us so long to get the write up done!

**Comment by Jenefer-Monroe** [comment]
It looks like you entered the wrong GUID, and then also included some other text with the GUID
![image](https://user-images.githubusercontent.com/89584709/224797350-b0fe2ba9-9f67-4c97-a766-f9aee7eccccf.png)

**Comment by RickKush** [comment]
The correct client ID is 5f9c8a00-6e79-41f3-8128-845e6e7012e0.

I did it one more time to verify that I am entering the client ID correctly (and it gave me the same error):

***@***.***

From: Jenefer Monroe ***@***.***>
Sent: Monday, March 13, 2023 2:34 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Office 365 Mgmt API connection for Child Admin | Sync Logs (Issue #4915)


It looks like you entered the wrong GUID, and then also included some other text with the GUID
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/224797350-b0fe2ba9-9f67-4c97-a766-f9aee7eccccf.png__;!!May37g!OmHMq27QLv9iADkuqhEUh1Vrg3AN7bqEiQhS6MXgtZaZHZuBdpZOJCCsH6J7Wtl0ORBWjKuDNZ8_BYqjVoJjOvAg9Q$>

-

**Comment by Jenefer-Monroe** [comment]
Can you please share this as a screenshot so I can be sure I'm in the correct context?

**Comment by Jenefer-Monroe** [comment]
Its a non-obvious problem with GitHub :)

**Comment by Jenefer-Monroe** [comment]
I'm pretty stumped. 

What is shown for the redirect URL at the bottom of that security page?
![image](https://user-images.githubusercontent.com/89584709/224831541-535ddeb4-8125-404d-8708-1ec5d7883bef.png)

In the azure app registration, click on the redirect URIs. Does it show the same thing? 
![image](https://user-images.githubusercontent.com/89584709/224831310-330fec69-3e15-4035-af34-a752ab13e979.png)
![image](https://user-images.githubusercontent.com/89584709/224831435-f534d680-a786-4448-9b44-381ddda4c18b.png)

**Comment by RickKush** [comment]
![image](https://user-images.githubusercontent.com/116654106/224837178-898d9b21-a0a5-42e5-a58e-d68eec0d3138.png)

**Comment by Jenefer-Monroe** [comment]
I'm not sure about that front channel
ours is blank. I'm not sure how that would impact. Did you set that intentionally? 
![image](https://user-images.githubusercontent.com/89584709/224838697-ebe9067a-f994-4f44-ae99-6bb52666f339.png)

Then how about for API Permissions?
![image](https://user-images.githubusercontent.com/89584709/224838947-db5e6cc1-2f12-4eaf-93bb-9895622249b8.png)

**Comment by RickKush** [comment]
No, but I will be happy to blank it if you like.

**Comment by RickKush** [comment]
I removed it. It would be easy enough to put it back.

**Comment by RickKush** [comment]
Closed & reopened the browser: same error.

**Comment by Jenefer-Monroe** [comment]
What do you mean by close and open the browser? 
Did you see this error
![image](https://user-images.githubusercontent.com/89584709/224847542-f6609152-fce0-4258-8bad-52f8c86cd3ec.png)

saving the connector here? 
![image](https://user-images.githubusercontent.com/89584709/224847584-4f8b1225-b465-45cc-8d4f-113d19fbd73f.png)

**Comment by RickKush** [comment]
I hit the X in the upper right corner of the browser window and yes, I see that same error.

**Comment by RickKush** [comment]
Failure passed to redirect url. error=access_denied error_description=AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 5f9c8a00-6e79-41f3-8128-845e6e7012e0(Flow Runs). *_Resource value from request: https://manage.office.com. Resource app ID: c5393580-f805-4401-95e8-94b7a6ef2fc2. List of valid resources from app registration: 7df0a125-d3be-4c96-aa54-591f83ff541c_*, 00000003-0000-0000-c000-000000000000. Trace ID: c5f1a0f0-6bce-484e-a105-60624470f800 Correlation ID: b598c0bb-2474-4aab-80b7-fe7d7ed7aa8c Timestamp: 2023-03-13 21:59:25Z

**Comment by Jenefer-Monroe** [comment]
I appologize we seem to be talking past each other. 

Please
1) Validate that you saved the custom connector without the front channel logout
![image](https://user-images.githubusercontent.com/89584709/224838697-ebe9067a-f994-4f44-ae99-6bb52666f339.png)

2) Share a picture of your API Permissions
![image](https://user-images.githubusercontent.com/89584709/224838947-db5e6cc1-2f12-4eaf-93bb-9895622249b8.png)

3) Share a picture where this error message is occuring.

**Comment by RickKush** [comment]
I can't find c5393580-f805-4401-95e8-94b7a6ef2fc2 or 7df0a125-d3be-4c96-aa54-591f83ff541c in the custom connector in PowerApps.com. But I do find c5393580-f805-4401-95e8-94b7a6ef2fc2 in portal.azure in the app registration, in the manifest, labeled "resourceAppId", but no where else in the custom connector.

**Comment by RickKush** [comment]
[Microsoft 365 Management for COE.txt](https://github.com/microsoft/coe-starter-kit/files/10962572/Microsoft.365.Management.for.COE.txt)

**Comment by RickKush** [comment]
Here's the app registration w/o front-channel logout URL:
![image](https://user-images.githubusercontent.com/116654106/224853009-4a87bffd-25b1-4091-b799-150ae5cd26ce.png)

**Comment by RickKush** [comment]
![image](https://user-images.githubusercontent.com/116654106/224853127-bfefc282-cfdd-42f0-a93a-edf203b58a24.png)

**Comment by RickKush** [comment]
![image](https://user-images.githubusercontent.com/116654106/224869444-44e80297-f6b5-4bb1-b122-53bc780be10e.png)

**Comment by Jenefer-Monroe** [comment]
I'm afraid I'm stumped here. I think you will need to get a second pair of eyes to actually look at your configuration with you as debugging here does not seem to be working. 
Unfortunately we are a very small team (2 people) and so cannot meet with our GitHub customers. 

If you dont have anyone in your organizations, you could consider hiring a partner, there are several that have focus on the Power Platform CoE. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)
