### ISSUE TITLE
[CoE Starter Kit - BUG] - Unable to open CoE Starter Kit Setup Wizard [Preview] app. Error Code: AppMetadataFetchFailed

### ISSUE THREAD

**Issue by rr41188** [microsoft/coe-starter-kit#4916]
### Describe the issue

Hi I am   getting below error message when I tried to open  CoE Starter Kit Setup Wizard [Preview] app after the Center of Excellence - Core Components solution updated successfully . I confirmed that following flows are turned on  1.SetupWizard>GetCurrentEnvironment
2.SetupWizard>GetTenantID
3.SetupWizard>GetUserDetail

    Error Code: AppMetadataFetchFailed
    Session Id: ce0cd1aa-6617-4551-b23a-3e91d3dce3b9
    Activity Id: 781479ec-f1e7-41fe-a08a-705f5dd83fae
    Timestamp: Tue Mar 07 2023 13:21:32 GMT+1300 

Encountered internal server error from Document Server. The correlation Id is '7b1c14ea-e37a-4414-91da-97189e4cf95f'.
s@https://rdicoe.crm.dynamics.com/uclient/scripts/app.js?v=1.4.5358-2301.5:4931:82 i+Mw/lt/</<@https://rdicoe.crm.dynamics.com/uclient/scripts/custompage.js?v=1.4.5358-2301.5:36:6614 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_4.3_managed

### What app or flow are you having the issue with?

 CoE Starter Kit Setup Wizard [Preview] app

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
