### ISSUE TITLE
[CoE Starter Kit - QUESTION] Issue while upgrading the COE toolkit

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/coe-starter-kit#4917]
### What is your question?

I'm upgrading the COE toolkit, during the Core component upgrade I'm facing the following issue, can you please help me to resolve the below  issue. 

I'm not finding the CreatorKitCore -1.0.20221205 solution in GitHub, the latest CreatorKitCore is 202301, but that latest file also I'm unable to download may be the file is corrupted 

_[{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: CenterofExcellenceCoreComponents. Some dependencies are missing. The missing dependencies are : <MissingDependencies><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_cleanupfororphanedobjectssetupwizardcopy_51823\" displayName=\"Clean-up for orphaned objects setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_compliancesetupwizardpage_d7b4b\" displayName=\"Compliance Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_environmentrequestsetupwizardpage_68a5b\" displayName=\"Environment Request Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_inactivityprocesssetupwizardpage_06a62\" displayName=\"Inactivity Process Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_initialsetuppage_d45cf\" displayName=\"Initial Setup page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_makerassessmentsetupwizardpage_f018f\" displayName=\"Maker Assessment setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_othercoresetupwizardpage_1e3e9\" displayName=\"Other Core Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_pulsefeedbacksetupwizardpage_4bf3f\" displayName=\"Pulse feedback setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_teamsenvironmentgovernancesetupwizardpage_23f70\" displayName=\"Teams environment governance setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_templatecatalogwizardpage_4c407\" displayName=\"Template catalog wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_traininginadaysetupwizardpage_1cbde\" displayName=\"Training in a day setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.SubwayNav\" displayName=\"cat_PowerCAT.SubwayNav\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_videohubsetupwizardpage_3a340\" displayName=\"Video hub setup wizard page\" /></MissingDependency></MissingDependencies> , ProductUpdatesOnly : False","ErrorCode":-2147188707,"AdditionalInfo":null}]_

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

**Comment by manuelap-msft** [comment]
You should be able to install the Creator Kit from AppSource following these steps to resolve the dependencies:
https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/setup#option-2-install-from-appsource

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
