### ISSUE TITLE
Error 401 while installing the audit log solution 

### ISSUE THREAD

**Issue by athwasiya** [microsoft/coe-starter-kit#4920]
Hi, 
While installing the Audit Log Solution, There is a step to test out the  Office 365 Management API . 
It is failing with the error as 401.
{
  "cache-control": "no-cache",
  "content-length": "61",
  "content-type": "application/json; charset=utf-8",
  "date": "Tue, 07 Mar 2023 10:55:19 GMT",
  "expires": "-1",
  "pragma": "no-cache",
  "www-authenticate": "Bearer error=\"invalid_token\"",
  "x-aspnet-version": "4.0.30319",
  "x-ms-apihub-cached-response": "true",
  "x-ms-apihub-obo": "false",
  "x-powered-by": "ASP.NET"
}
{
  "Message": "Authorization has been denied for this request."
}

Could anybody please help us in this. 

Thanks, 
Aditya.

**Comment by manuelap-msft** [comment]
Hello. Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

Note also that there was a recent product change in which the default identity provider for setting up a custom connector has changed from Azure Active Directory to Generic Oauth2. Please see https://github.com/microsoft/coe-starter-kit/issues/4808 for our bug to update the documentation about this next release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
