### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance detail request flow wrong app url

### ISSUE THREAD

**Issue by A-Demir-ilx** [microsoft/coe-starter-kit#4922]
### Describe the issue

Hello,

I received mails from users that the URL of the developer compliance center is not working. I see in the "Admin | Compliance detail request v3" flow that in the send email step is used a "?" before the appname. This should be a "&". Can you please change this in the step "Send republish mail to owner apps" and "Send republish mail to admin apps".

![image](https://user-images.githubusercontent.com/96475793/223442864-8c687b6e-4691-43db-8be1-11d33cc5571a.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Compliance detail request v3

**Comment by Jenefer-Monroe** [comment]
thanks for posting with such great investigation! We will validate and fix for next release.

**Comment by Jenefer-Monroe** [comment]
Hello. This link works for me. Although it is pointing to the old app so we will need to fix that up. 

![Image](https://user-images.githubusercontent.com/89584709/227217110-e4802583-1647-4a97-96ea-8147955e5bd3.png)

Perhaps you have the wrong value in the env var? We fill this for you in the setup wizard now, but to do it manually:

### Manually fill Developer Compliance Center URL env var
1. Go to apps in your Gov solution
2. Select the app details
![Image](https://user-images.githubusercontent.com/89584709/227219805-d5afbcb2-258d-4ccb-b417-47bce45f41ef.png)

3. Copy the Web link
![Image](https://user-images.githubusercontent.com/89584709/227220101-94c270fd-3799-4e61-befa-4bf9e2bdc764.png)

4. Append this string to the end **&source=portal**
![Image](https://user-images.githubusercontent.com/89584709/227220481-0d9cf7e4-19c1-4a43-8f0d-50c9cfadfcb0.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
