### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#4923]
### What is your question?

1. Could we utilize the multi - tenant option while registering APIs
<img width="679" alt="image" src="https://user-images.githubusercontent.com/112712553/223460140-d1fbc6fa-9e80-4f14-aa72-2dbf874601f4.png">

2. Is it possible to link the introduction page tabs of Power Dashboard to the actual tabs of itself. Example if, we can make the highlighted box as clickable button to its report 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/112712553/223461257-2fe4e27f-8129-49ae-bfb3-83bd40e76a06.png">

3. Environment creation Maker App shows language codes like 1033. It would be better if it can be seen as the languages names like 'English'. Users are not aware of which code refers to which language

4. Could we provide Environment creation Maker app with more options with Type of Environment to be created : Apart from sandbox or production , we can give options for Trial and developer as well. 

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
Regarding Q3: please see https://github.com/microsoft/coe-starter-kit/issues/4674
Regarding Q4: Can you please post separately as a feature request? I will put on the backlog for that developer to consider

**Comment by Jenefer-Monroe** [comment]
Regarding Q1: We have not tested that configuration and so cannot comment. I do not think you could use an account from another tenant, but having it set that way may be ok. You'll have to test that out.

**Comment by Jenefer-Monroe** [comment]
Regarding Q2: I'm afraid I dont follow. I think what you describe is what already occurs. 
From here, clicking either of the circled items brings me to the page. Can you please let me know what I'm missing?
![image](https://user-images.githubusercontent.com/89584709/223498141-477b3cb2-1a34-4a16-bdf3-660e11acf209.png)
![image](https://user-images.githubusercontent.com/89584709/223498366-92ecda63-e060-4558-a383-d50e9191fe4a.png)

**Comment by PPMini** [comment]
Thanks a million @Jenefer-Monroe  for the answers. 

For Q3, you are right Jenner if I open my report from Power BI service  I can do that but I can not do the same from Power BI desktop. I believe its the limitation of Power BI desktop

**Comment by Jenefer-Monroe** [comment]
oh i see. Yes I misunderstood. Yes thats just not a feature in the PBI Desktop unfortunately. 
We arent PBI experts so if you end up finding a way to make that happen let us know!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
