### ISSUE TITLE
[ALM Accelerator - BUG]: Custom connector icon images not shown on prod

### ISSUE THREAD

**Issue by jnpoyser** [microsoft/coe-starter-kit#4925]
### Describe the issue

I've created a custom connector, and set an icon image for the connector.

Looking at the checked in code, the image is there and is referenced from the custom connector's .xml file.

When I deploy to prod, the connector does not have an image.

(FYI, also having another connector issue #4924 - not sure if there's a common root cause?)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20230217.1(Managed)

**Comment by mikefactorial** [comment]
@jnpoyser thanks for reporting this will look into what's happening on our end.

**Comment by mikefactorial** [comment]
@jnpoyser this appears to be a platform issue and not related to the ALM Accelerator. We've directed the feedback to the product team to investigate. Thanks again for reporting it.

**Comment by mikefactorial** [comment]
Closing this out as there's nothing for the ALM Accelerator team to do here.
