### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why import CreaterKit?

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#4928]
### What is your question?

Previously, importing CreaterKit was not included as a procedure.
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-creator-kit

Please explain why CreaterKit import was added to the procedure.
Thank you in advance.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

**Comment by manuelap-msft** [comment]
The Creator Kit is a component library with canvas and PCF components, which help easily create consistent, beautiful, and effective user experiences. We have used these components to update the user experience of the CoE kit apps. As these apps now depend on the Creator Kit you need to install the Creator Kit first.

**Comment by egym07** [comment]
I see, so the UX is new with CreatorKit.
I understand. Thank you very much.
I was using a slightly older version, so I will install and update CreaterKit.
