### ISSUE TITLE
[CoE Starter Kit - BUG] Office 365 Management API error

### ISSUE THREAD

**Issue by remzoa** [microsoft/coe-starter-kit#4929]
### Describe the issue

Hi. 

After updating to the latest version of the CoE kit, I am now not able to get the audit logs using the Custom Connector. 
When I have updated the CC with the correct information, and then run a "StartSubscription" test, I`m getting the following message: 

Operation failed (401), see response below: 
Status: 
(401)
Headers: 
{
  "cache-control": "no-cache",
  "content-length": "61",
  "content-type": "application/json; charset=utf-8",
  "date": "Wed, 08 Mar 2023 07:18:41 GMT",
  "expires": "-1",
  "pragma": "no-cache",
  "www-authenticate": "Bearer error=\"invalid_token\"",
  "x-aspnet-version": "4.0.30319",
  "x-ms-apihub-cached-response": "true",
  "x-ms-apihub-obo": "false",
  "x-powered-by": "ASP.NET"
}
Body: 
{
  "Message": "Authorization has been denied for this request."
}

I have the App reg set up with API Permissions as following: 

Microsoft Graph:
User.Read - Type: Deleaged - Status: Granted
Office 365 Management APIs
ActivityFeed.Read - Type: Delegated - Status: Granted
ActivityFeed.Read - Type: Application - Status: Granted
ServiceHealth.Read - Type: Delegated - Status: Granted
ServiceHealth.Read - Type: Application - Status: Granted
PowerApps RunTime Service
user_impersonation - Type: Delegated - Status: Granted

Client secret is not expired. 

I have the Power Platform Admin role, and it`s active. 

When the Child Admin | Sync Logs flow is running, it gets to the action: "List audit log content" where it gets an error saying "Authorization has been denied for this request". 

This was working yesterday before I updated to the newest version.

### Expected Behavior

Expected is to be able to gather Audit Log data.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Child - Admin - Sync Logs

**Comment by manuelap-msft** [comment]
Hello. Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

Note also that there was a recent product change in which the default identity provider for setting up a custom connector has changed from **Azure Active Directory** to Generic Oauth2. Please see https://github.com/microsoft/coe-starter-kit/issues/4808 for our bug to update the documentation about this next release.

**Comment by manuelap-msft** [comment]
Glad you got this working, and thanks for letting us know what you did to get it working - that will help us help other customers.

Unfortunately product changes like the one that happened with custom connectors, where both the default provider as well as some of the required fields to configure authentication changed, are out of our control. We tested the release and component before go live, and about a week after the release of this version the custom connector interface itself changed. This change was not related to the CoE kit, and would have impacted any custom connector you're configuring. The platform evolves all the time, and sometimes we have to play a little catch up.

**Comment by Jenefer-Monroe** [comment]
I did a full write up for this situation since so many people are hitting it. Please see [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
