### ISSUE TITLE
[CoE Starter Kit - BUG] Admin & Child Admin Sync Audit Log Failing since uprade of CoE

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#4931]
### Describe the issue

Since the upgrade of the CoE the Admin Sync Audit Log and Admin Child Sync Log flows are failing. The error details for the **Admin Sync Audit Log** are 'The server did not receive a response from an upstream server. Request tracking id '08585234079082424002987286403CU52'.'. 

It fails at the Audi Logs Chunk Scope when in the Apply to each timeSegment with a status code of 502 and error body showing as 
{
  "error": {
    "code": "NoResponse",
    "message": "The server did not receive a response from an upstream server. Request tracking id '08585234079082424002987286403CU52'."
  }
}

The error details for the **[Child] Admin Sync log** is that Authorization has been denied for this request. The error occurs on the Audit Logs Scope with a status code of 401, showing the List audit log content as unauthorized. 

I have checked the API connections and they are showing with a status of Connected. It also appears that they are being used in the 'Run Only Users' section of the flow, although I do see two connections for the dataverse. 

![image](https://user-images.githubusercontent.com/117096415/223669319-4dc465d9-4543-4177-a791-a0941afdd22b.png)

So it would appear the Audit log flow is unable to establish a connection as the child flow is not authorised when called upon to make that connection to the List audit log content. I am just not sure why it woudl no longer be authorised. The tenant ID is correct and can see this stored correctly in the environment variables. 

Any help would be greatly appreciated?

### Expected Behavior

The CoE audit log flows run without any issues. 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Admin Sync Audit Log

**Comment by G1982C** [comment]
I followed https://github.com/microsoft/coe-starter-kit/issues/4808 but I did not go to the bottom of the chain to see that you have to delete and recreate the connection.  

All is working now. Thanks

**Comment by Jenefer-Monroe** [comment]
Thank you for letting me know!
