### ISSUE TITLE
[CoE Starter Kit - DOCUMENTATION] Default Identity Provider for custom connector has changed

### ISSUE THREAD

**Issue by Roelof-BAM** [microsoft/coe-starter-kit#4933]
### Describe the issue

In the [Set up audit log components ](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)a screenshot is shown for setting up the security tab of the custom connector Office 365 Management API.

<img width="400" alt="coe42" src="https://user-images.githubusercontent.com/74544357/223691204-9a7c9d48-53b1-4e8a-affc-a03b189cdfbe.png">

But in Powerautomate itself the tab is different and looks like this:
![image](https://user-images.githubusercontent.com/74544357/223692007-9f42ca98-a93b-4ba0-975b-6558b155ded6.png)

### Expected Behavior

Please write the instructions that match with the security tab in Powerautomate. Because I can not get the custom connector working with the current instructions. In the test for StartSubscition I get this 401 error:
![image](https://user-images.githubusercontent.com/74544357/223692602-7de07fda-628a-4ca9-bde7-984c25563e0a.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Custom connector Office 365 Management API

### Steps To Reproduce

The description of the configuration for the Custom connectors is different from what I see in real life, (see description of this issue). Follow the instruction on https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog to reproduce this issue

**Comment by manuelap-msft** [comment]
There was a very recent product change in which the default identity provider for setting up a custom connector has changed from **Azure Active Directory** to Generic Oauth2. Please see https://github.com/microsoft/coe-starter-kit/issues/4808 for our bug to update the documentation about this next release.  You will need to change the identity provider to **Azure Active Directory**, then the screen will match again and you should be able to proceed.
