### ISSUE TITLE
[CoE Starter Kit - QUESTION]  Environmental Variable "Also Delete from CoE" set to no deleting all apps and flows

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#4935]
### What is your question?

we set  "Also Delete from CoE" to No and
--->Deleted few environments 
--->CLEANUP - Admin | Sync Template v3 (Check Deleted) -->Ran this flow (which in turn calling all child flows)

Once the flow ran success---went to Power Platform Admin View (Model Driven App)

--->The deleted Environments are displaying under Deleted Environments View that is fine.
---> Went to see the Apps from Side  Navigation ---> Respective Apps/ flows all are deleted from the deleted environments 

My question is 

"Also Delete from CoE" to "No"  is only applicable to environments but not for apps/flows within the environments ?

If Yes , In Dataverse Table "Power Apps"  we have two columns "App deleted ON" and "App Deleted" 

When or in which cases this columns updates like App Deleted to "Yes"  and App Deleted On  will be updated in the table????

![image](https://user-images.githubusercontent.com/29652263/223733837-dea90fa8-04e2-450d-bad4-d936dd754df7.png)

![image](https://user-images.githubusercontent.com/29652263/223737512-cbe25a40-889b-4bed-ad67-e285b5a9994d.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by JeneferM-MSFT** [comment]
That field does exist for apps and other objects and is filled by this flow: **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** it uses the same env variable for deleting or marking deleted.
![image](https://user-images.githubusercontent.com/62659043/224316910-e9f92f04-dc94-4338-b881-761b16353f8b.png)

Please open the run that flagged the envt as deleted. 
You should see in this scope it going down the true path here
![image](https://user-images.githubusercontent.com/62659043/224336231-3855c103-66b5-4361-b620-f33740baa4a8.png)

It then calls all the helpers like this
![image](https://user-images.githubusercontent.com/62659043/224336596-69a9847b-bb8d-427a-9f40-c2c01dbc61ee.png)

Is this what you see? If not you may have [unmanaged layers that need removed](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
