### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Admin | Inactivity notifications v2 (Start Approval for Apps) flow

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#4936]
### What is your question?

Admin | Inactivity notifications v2 (Start Approval for Apps) flow ran and we got many emails like "This app owner cannot perform approval owner name". Why we got this email to our service account?

![COE](https://user-images.githubusercontent.com/126264610/223742495-87a95fc6-0e97-42ac-ae39-cf9fa0f817b6.PNG)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.6

### What app or flow are you having the issue with?
Admin | Inactivity notifications v2 (Start Approval for Apps)

**Comment by lingutla123** [comment]
Thank you for the information. Do makers need Power apps per user license?

**Comment by Jenefer-Monroe** [comment]
They do not need one for this process. There is a license exception for responding to approvals in email. They would need it for browsing to the apps though.

**Comment by lingutla123** [comment]
Okay. Thank you.

**Comment by TifChen** [comment]
Hi, I also receive this kind of notification but there is no security group set up in CoE environment. Can you please let me know what cause might be ? 
Thank you.
