### ISSUE TITLE
[CoE Starter Kit - QUESTION] Upgrading a COE Environment - Prevent Data Loss

### ISSUE THREAD

**Issue by CodingBytes** [microsoft/coe-starter-kit#4940]
### What is your question?

When a COE upgrade occurs, is there any possibility of losing any of the historical data captured in the Dataverse?  I need to help ensure my customer that no data will be lost during the upgrade of a COE.  Additionally, my customer is interested in archiving the COE data that exists in Dataverse into a data lake for DR purposes.  Is there any guidance available to complete this objective?

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
Hello. We test the kit to the best of our ability but the kit is not a supported product so there is of course always the possibility that something could go wrong. We recommend a test environment where you test the upgrade as a result if you are using us in ways that store metadata and are business critical. 

The product itself writes inventory and usage for environments, apps and cloud flows to a DL today and we are going to be releasing a version of the kit that can use that as its base in the next few weeks. 

Please come to [office hours](https://aka.ms/coeofficehours) next week if you'd like to learn more!
