### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by M-Endou** [microsoft/coe-starter-kit#4942]
### What is your question?

If turn off the flow of “Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created”, how does the flow of “Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments” work?
Are all new Teams environments judged to have no business justification and deleted weekly?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.25

### What app or flow are you having the issue with?

Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments, Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created

**Comment by Jenefer-Monroe** [comment]
Hello 

For the cleanup, we key off a field that is added when you run **_Microsoft Teams Admin | Ask for Business Justification_**, so if you do not turn that on you will not trigger delete for any teams due to lack of justification.

**Comment by Jenefer-Monroe** [comment]
Similarly, if you turn it on, it will not impact any teams envts already present as that field will never get updated.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by M-Endou** [comment]
Thanks for the answer. I would like to ask you additionally, if it turn off the justification, we set “Rejected” for each Teams environment on CoE starter Kit, weekly cleanup will work?

**Comment by M-Endou** [comment]
I’m sorry, I closed the question by mistake.

Thanks for the answer. I would like to ask you additionally, if it turn off the justification, we set “Rejected” for each Teams environment on CoE starter Kit, weekly cleanup will work?

**Comment by Jenefer-Monroe** [comment]
I'm not sure what you mean **_turn on by justification_**. Do you mean the flow?
We dont have a technique to go back and ask for justification for old environments. If you turn that flow on all teams envts going forward will be asked for justification. If you reject them then they will be deleted in the clean up flow.

**Comment by M-Endou** [comment]
I mean, even if the asking for Business Justification flow is turned off, will the weekly cleanup flow work if I reject the teams environment individually in the CoE starter kit.

**Comment by Jenefer-Monroe** [comment]
No it wont. We do not have a system to clean up teams envts that are used that you did not ask for justification through our processes.

**Comment by M-Endou** [comment]
Thank you for the answer. I understand.
