### ISSUE TITLE
[ALM Accelerator - BUG]: Deploy Solution with Service Account using personal owner connections

### ISSUE THREAD

**Issue by FRITTENPIET** [microsoft/coe-starter-kit#4943]
### Describe the issue

Hi Team,

we're facing a probelme regarding the use of a service account when deploying with ALM Accelerator:

**SCENARIO:**
I have developed a Solution (Canvas Apps, Power Automate Flows, Connection References, Environment Variables) in a Dev environment.

Now I want to use the ALM Accelerator with my personal account to deploy the Solution to Test and Prod. For this I want to use a  seperate service account (not a service principal), so that all objects of the solution belong to the service account and the service account executes the flows after a succesful deployment. 

In the deployment settings I use the connections i created with my personal account and therefore I am the owner of these connections (Validation, Test, Prod):
<img width="771" alt="image" src="https://user-images.githubusercontent.com/98097794/224004210-2f1ea787-f13b-4b83-a2ed-68823bea9b9e.png">

Under Flows I define the Service Account as Flow Owner and Activation User:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/98097794/224003676-931a4560-8d0c-4f9a-a862-4ed31250202d.png">

When I deploy the solution with this configuration into the test environment, the pipeline always runs into an error at the step "Activate Flows":
<img width="145" alt="image" src="https://user-images.githubusercontent.com/98097794/224004713-86b38aa1-78ab-471b-adde-cf771a4f596e.png">

The error messages refers to the sharing of connections and occurs with all flows:
************ FaultException`1 - SetState : Setting Activity State in CRM... workflow |=> Flow client error returned with status code "Forbidden" and details
[...]
Connection/providers/Microsoft.PowerApps/apis/shared_sharepointonline/connections/...' to 'shared_sharepointonline' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow.

**QUESTIONS**
The question now is whether I can even share my personal connections with another account to deploy the Solution? I only see the option to share the connection with a Service Princpal in the connection share interface.
Is the answer that the solution must be deployed with the service account using the alm accelerator and referecning its owning connections, because sharing a connection between users is not possible? (see [microsoft documentation](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-connection-reference#share-connections-with-another-user-so-flows-can-be-enabled))

### Expected Behavior

Enabling the share option in the deployment settings configuration will share the connections with the service account, allowing it to activate the flows with a reference to the corresponding connection:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/98097794/224008576-949e4e91-98d6-428a-a36c-9bcf60c2ff71.png">

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

February 2023

**Comment by mikefactorial** [comment]
@FRITTENPIET thanks for reporting this and for the details. Will look into a fix for this.

**Comment by orjsol** [comment]
I also have the same problem. Is there a workaround?

**Comment by tomjosbin** [comment]
Hey, have you tried specifying your name as the 'Activation User' or without specifying anything in the 'Activation User' field? Also please open the connection in target environments and verify whether it is shared with application user which you have used while configuring the ALM Accelerator. I could see not every time the connection is shared even though the 'Share' checkbox is ticked.

**Comment by mikefactorial** [comment]
@FRITTENPIET we don't support service accounts OOB. Only service principals so this is possibly gap that didn't exist before when it was possible to use impersonation to activate flows. Impersonation has been removed in the platform and Flow activation is supported when the connections are shared with the user. It would be good to support the service account scenario, however, we've never tested or documented that scenario so it would be good to know if you've had success with it in the past and if it's just the connection sharing that is broken with the latest updates.

**Comment by mikefactorial** [comment]
Closing this out as there doesn't appear to be anything required from the ALM Accelerator Team. Feel free to open a new issue or reopen if this is still a problem.
