### ISSUE TITLE
[CoE Starter Kit - Problem with errors when update CoE after 6 months] 

### ISSUE THREAD

**Issue by mp1295** [microsoft/coe-starter-kit#4945]
### What is your question?

So, guys please help me if you know anything for this type of situation.

A colleague is imported CoE solution after 6 months, for update, and now we have a lot of errors. What do you mean, is it better fix that errors, or delete whole production CoE and then start from blank, but if we delete production CoE we will lose audit logs etc, whole database. Please give me advice.

Kind regards

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2023

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately we are a very small team and so cannot scale to assisting with upgrade issues of this age. 
We recommend upgrading at least every 3 months as that is how far back we test. 

To answer the question of if you shoudl struggle and try to save the envt or not, that will be up to you. I dont know the state of the world from back then so I cannot really answer how difficult clean up will be. 

Sorry about that!

**Comment by mp1295** [comment]
Ok, thank you :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
