### ISSUE TITLE
[CoE Starter Kit - Feature]: More options on Environment Creation Maker APP

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#4946]
### Is your feature request related to a problem? Please describe.

Not really

### Describe the solution you'd like

Present the screen shows only two types of Environment : Production and Sandbox . Looking for more options like Trial or developer

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/112712553/224062610-f5a0dd80-d1c8-43b1-ac53-f08d805f9bec.png">
 

AB#1053

**Comment by manuelap-msft** [comment]
Closing out as duplicate, we already have other tasks capturing this ask.

**Comment by PPMini** [comment]
Hi @manuelap-msft , do we have any updates on this one, could you please share the issue # to follow if not yet released.
