### ISSUE TITLE
[CoE Starter Kit - BUG] Typo in Clean Up Old Objects app

### ISSUE THREAD

**Issue by Stevef1** [microsoft/coe-starter-kit#4948]
### Describe the issue

On the landing screen of the Clean Up Old Objects canvas app, it says "Part of being a good Power Platform maker is keeping you objects tidy."

It should say 'your' and not 'you'.

![image](https://user-images.githubusercontent.com/37064740/224066723-56e1c9c5-67f1-45a2-8f13-61ba01b9b2ed.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.6

### What app or flow are you having the issue with?

Clean Up Old Objects

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
