### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Custom Connectors) not working "AzureResourceManagerRequestFailed"

### ISSUE THREAD

**Issue by JobboJJobboJ** [microsoft/coe-starter-kit#4949]
### Describe the issue

Admin | Sync Template v3 (Custom Connectors)
I've managed to get every flow that is supposed to work to get to work, but this one doesnt want to be turned on. This is the error message I've received. I have imported the CoE starter kit core components solution last week and every flow that is on the Microsoft docu list works now except for Admin | Sync Template v3 (Custom Connectors).

![image](https://user-images.githubusercontent.com/78744561/224069902-32ebfa62-5cf3-4f05-b86a-1967c24e2ba8.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors)

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by JobboJJobboJ** [comment]
![image](https://user-images.githubusercontent.com/78744561/225553216-b0517e83-1724-41cd-8f58-0459f073cdc5.png)

**Comment by Jenefer-Monroe** [comment]
And can you please share the screenshot of where this UX surfaces? In other words, where were you at when you tried to turn on the flow?

**Comment by JobboJJobboJ** [comment]
![image](https://user-images.githubusercontent.com/78744561/225595303-8fa16f53-3113-45ea-ae2c-073758d30f4f.png)

**Comment by Jenefer-Monroe** [comment]
Ok this appears to be some product issue as the flow is clearly there. Let's see if we can find a workaround. 

Please browse to the Core solution via the http://flow.microsoft.com/ instead
Open the flow details page. 
![image](https://user-images.githubusercontent.com/89584709/225597316-6f70da2d-4561-4014-b70b-961acfd9bd45.png)

Does that open? 

If so, do the connetions appear healthy? 
![image](https://user-images.githubusercontent.com/89584709/225597569-01924d36-4100-4eff-8ca4-ab356bd39266.png)
![image](https://user-images.githubusercontent.com/89584709/225597779-ca582663-1da6-4920-a8d2-94bfe1a5e33c.png)

**Comment by Jenefer-Monroe** [comment]
And the flow checker warning in yellow is just saying "the flow is off"? or is it saying something else? 
Can you turn on from this UX?

**Comment by JobboJJobboJ** [comment]
It indeed says "the flow is off" and I get the same error when I try to turn it on from this UX.

**Comment by Jenefer-Monroe** [comment]
ok I'm afraid you've hit a product issue then that I cannot assist with. You will need to [contact product support](https://learn.microsoft.com/en-us/power-platform/admin/get-help-support)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
