### ISSUE TITLE
[ALM Accelerator - BUG]: Activate Flows step failed to activate flow with status code "Forbidden"

### ISSUE THREAD

**Issue by 180DegreeLeft** [microsoft/coe-starter-kit#4952]
### Describe the issue

Release to environment failed to activate flow that was turned off. Flow client error returned with status code "Forbidden".
In ALM configuration connection references have been shared with the user that is not service principal.

![image](https://user-images.githubusercontent.com/127437316/224153796-1b60bf39-f1ef-4840-9e55-7e9e6617902b.png)

### Expected Behavior

ALM Accelerator should activate flows that are checked in for activation.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230308.1 March 2023

### Steps To Reproduce

1. In the environment turn off the flow.
2. Use ALM Accelerator to release solution to the environment and check to activate the flow.

**Comment by mikefactorial** [comment]
@180DegreeLeft not sure what you mean when you say that the deployment user is not service principal. All of the ALM Accelerator pipelines run as a service principal specified in the Service Connections configured in Azure DevOps by default. Are you using Service Connections that are not using service principal auth? 

The connection sharing in the App does expect that you are using service principal as of today, but would be interesting to hear more about your setup.

**Comment by 180DegreeLeft** [comment]
> @180DegreeLeft not sure what you mean when you say that the deployment user is not service principal. All of the ALM Accelerator pipelines run as a service principal specified in the Service Connections configured in Azure DevOps by default. Are you using Service Connections that are not using service principal auth?
> 
> The connection sharing in the App does expect that you are using service principal as of today, but would be interesting to hear more about your setup.

You are correct about Service Connection, that is what we are using to deploy. We was not aware about the limitation that connection sharing in the App does expect service principal. That does explain the error message. Thank you.
