### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inactivity Notifications

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#4953]
### What is your question?

When Maker click on Reject the deletion of the App did Manager get notify?

### What solution are you experiencing the issue with?

Governance Components

**Comment by JeneferM-MSFT** [comment]
No there is no such notification process in the kit. There are only notifications for ignored requests
Please see [Admin | Email Managers Ignored Inactivity notifications Approvals](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#admin--email-managers-ignored-inactivity-notifications-approvals)
