### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Syed0100** [microsoft/coe-starter-kit#4957]
### Describe the issue

We should be able to find office 365 outlook in the 1>PowerApps  
2>Center of Excellence – Audit Log solution.  
3>[Child] Admin | Sync Logs. > 
4>For the Office 365 Management API custom connector and Office 365 Outlook, change the value to Use this connection (userPrincipalName@company.com). If there's no connection for any of the connectors, go to Dataverse.  Connections, and create one for the connector. 
5>In above step 4: we are not able to find office 365 outlook when navigated to  : Run only users settings in the mentioned flow.

### Expected Behavior

We should be able to find office 365 outlook in the 1>PowerApps  
2>Center of Excellence – Audit Log solution.  
3>[Child] Admin | Sync Logs. > 
4>For the Office 365 Management API custom connector and Office 365 Outlook, change the value to Use this connection (userPrincipalName@company.com). If there's no connection for any of the connectors, go to Dataverse.  Connections, and create one for the connector. 
5>In above step 4:  we should be able to find office 365 outlook when navigated to  : Run only users settings in the mentioned flow.

I have pasted the Microsoft link for reference 

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs.

### Steps To Reproduce

1) solution : Center of Excellence – Audit Log solution.
2) Select the [Child] Admin | Sync Logs.
3) Edit the Run only users settings
4) For the Office 365 Management API custom connector and Office 365 Outlook, change the value to Use this connection (userPrincipalName@company.com). If there's no connection for any of the connectors, go to Dataverse > Connections, and create one for the connector.
5) For the Microsoft Dataverse connector, leave the run-only permission value blank and confirm that the connection reference for the CoE Audit Logs - Dataverse connection is configured correctly. If the connection is showing an error, [update the connection reference](https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-connection-references) for the CoE Audit Logs - Dataverse connection reference.

### Anything else?

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

Set Up Power Automate Flow Section

**Comment by manuelap-msft** [comment]
We've recently changed this flow to no longer use the Outlook connector but call a child flow instead. We're working on updating our documentation to reflect the change. You can proceed with the remaining steps in the setup instructions and ignore the mention of the Outlook connector.

**Comment by Syed0100** [comment]
Ok, Thanks for your prompt reply.




Regards
Syed

**Comment by manuelap-msft** [comment]
Closing out as we no longer use the Audit Log solution.
