### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to create Project with Pipelines Template due to Push Tag Error

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#4959]
### Describe the issue

We are attempting to create a new project with the pipelines template however we are receiving an error that seems to be related to permissions. The error can be found on the steps inside the yaml file that states the user does not have contribute permissions. However the user does have administrator permissions to the organization in devops. 

![image](https://user-images.githubusercontent.com/95443860/224436555-7d7500d7-545a-4ceb-b7dd-07e1f41616a9.png)

### Expected Behavior

Yaml file should complete and project should be created with the respective pipelines. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

February Release

### Steps To Reproduce

Attempted to Create Project under the ALM Accelerator for Power Platform Administration

**Comment by mikefactorial** [comment]
This is a new one for me @nasilvae haven't seen that happen before. Wonder if @jenschristianschroder might have some insight here? 

Can you check the permissions available based on these instructions and try to rerun the sync pipeline? https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#update-permissions-for-the-project-build-service

**Comment by nasilvae** [comment]
> This is a new one for me @nasilvae haven't seen that happen before. Wonder if @jenschristianschroder might have some insight here?
> 
> Can you check the permissions available based on these instructions and try to rerun the sync pipeline? https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#update-permissions-for-the-project-build-service
> 
> Wouldn't expect manually changing the permissions would be required based on the permissions you mentioned but it does appear that something isn't correct.

We managed to get it working by adding the account directly onto the Build Administrators security project security group. Not sure if this is acceptable or is a bug within DevOps or the ALM Accelerator.

**Comment by mikefactorial** [comment]
@nasilvae closing this out for now. Don't think this is an ALM Accelerator related issue. Most likely something related to the Azure DevOps configuration.
