### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs solution fails after upgrade - and fixing up did not work. 

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#4961]
### Describe the issue

If you experienced an issue even after attempting to fix as described in #1424, then you likely ended up with a bad connection, perhaps due to the wrong identity provider being selected as in #4808

Once a bad connection is created its very difficult to fix. Its best just to "start over". 
These steps may seem dramatic but it will lead to it being clean in the end.

### Delete and remake the connection
1. Delete all existing connections to **_Office 365 Management API_**
![image](https://user-images.githubusercontent.com/89584709/224514059-ec22d26e-5280-46d4-b215-71b1ff401393.png)

2. Edit the custom connector
![image](https://user-images.githubusercontent.com/89584709/224514106-9be298de-c1ea-4b7a-b267-0f851e8a95e4.png)

3. Be sure to select the correct Identity Provider and to enter the correct recourse url depending on if you are commercial or GCC (or other cloud). Please see [Set up the custom connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector)
![image](https://user-images.githubusercontent.com/89584709/224514253-b0c84d9d-21d7-4296-a30f-39996bd24d63.png)

4. Note that after you hit Update connector the values do appear to disappear, but they were saved, its just a product issue that they no longer appear as having been filled. You can see this as the Idenity Provider does appear correct now as Azure Active Directory instead of the default
![image](https://user-images.githubusercontent.com/89584709/224514295-7c3271b0-ce5c-4c03-934e-e5e38dbabe10.png)

5. Go to the test pane and create a connection
![image](https://user-images.githubusercontent.com/89584709/224514316-51d204e7-4ba3-49ab-ac6d-447ebe3ff3b0.png)

6. And now test by using the List Content action
Note: 
- I'm assuming you've previously started the subscription since this is an upgrade bug
- PublisherIdentifer is the Application ID
- You'll need to set the start and end time to be in the last week and only 1 day apart.20
- Make sure you get a 200 return and that data is actually returned in the body
![image](https://user-images.githubusercontent.com/89584709/224514447-f1b8ff4e-8984-47fe-995e-8207a9ad0276.png)

### Apply new connection to connection reference
7. Go to the Default solution > Connection references > Find any connection references for the custom connector
![image](https://user-images.githubusercontent.com/89584709/224514602-8adfd678-dc36-4f37-9643-3bfc58e12635.png)
![image](https://user-images.githubusercontent.com/89584709/224514661-ff2783e5-b993-4572-b817-3187db0efaed.png)

8. Click each one to open its edit pane, select the drop down, and select your connection and save
![image](https://user-images.githubusercontent.com/89584709/224514711-466ecd06-25be-4bd4-842a-3534f8f51adb.png)
![image](https://user-images.githubusercontent.com/89584709/224514745-031ec0c7-dbec-4fcc-b89a-9b881061345c.png)

### Validate flow using the new connection
9. Go to the audit logs solution > details page for  the **_[Child] Admin | Sync Logs_** flow
![image](https://user-images.githubusercontent.com/89584709/224514537-089e8429-61a2-4eb0-b15f-3930b935b867.png)

10. Validate the connections now shown all green checks (may need to refresh the page), then click **_Run only users_**
![image](https://user-images.githubusercontent.com/89584709/225330036-a763ca4a-e8a3-44e6-9abd-339095c7339e.png)

11. Validate it shows correctly as the account you selected before. 
![image](https://user-images.githubusercontent.com/89584709/224556051-edd88a2c-1014-47c6-8a73-6f1894272fee.png)

### Test the flow
12. Go to the Admin | Sync Audit Logs flow and run it
![image](https://user-images.githubusercontent.com/89584709/224514965-cf569eac-0180-4b8d-9ce0-0e9a68caf992.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

custom connector

**Comment by manuelap-msft** [comment]
Closing out as the Audit Log solution is now deprecated.
