### ISSUE TITLE
[ALM Accelerator - BUG]: Invalid client secret provided

### ISSUE THREAD

**Issue by lukkyv** [microsoft/coe-starter-kit#4964]
### Describe the issue

Not reading client secret in Pipeline 

Tenent ID is : ***Client ID is : ***Client Secret is : ***Dataverse Host is : org9b7e1323.crm4.dynamics.comAAD host is: login.microsoftonline.comBody of Req: System.Collections.HashtableURI of Req: https://login.microsoftonline.com/***/oauth2/v2.0/tokenInvoke-RestMethod : {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '***'.\r\nTrace ID: f6221305-6035-4fc0-9c8e-071eb1636c00\r\nCorrelation ID: bc3e0103-e164-4cd3-be44-3b6b9018d42a\r\nTimestamp: 2023-03-13 08:32:50Z","error_codes":[7000215],"timestamp":"2023-03-13 08:32:50Z","trace_id":"f6221305-6035-4fc0-9c8e-071eb1636c00","correlation_id":"bc3e0103-e164-4cd3-be44-3b6b9018d42a","error_uri":"[https://login.microsoftonline.com/error?code=7000215"}](https://login.microsoftonline.com/error?code=7000215%22%7D)At D:\a\1\PipelineUtils\PowerShell\dataverse-webapi-functions.ps1:13 char:17

### Expected Behavior

This feature works in older version. recently we updated latest ALm version, after that we lost complete.
 
As per document, it should work. 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-pipeline-global-variables

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20230206.1

### Steps To Reproduce

Double checked all variable values (client ID , Secret .. ) - all are correct.
  

### Anything else?

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform#create-pipeline-global-variables

**Comment by mikefactorial** [comment]
@lukkyv the latest version of the pipelines no longer use the ClientSecret specified on the Variable Group (we're in the process of updating the documentation). Instead, the secret that is used is the secret on the Service Connection associated with the pipeline. Can you check the service connection configuration for the pipeline to see if it is using a service principal for authentication?

**Comment by nkbapodra** [comment]
I am experiencing same error, confirmed ClientId/ClientSecret values are correct. Can connect to the dataverse via XRMToolbox ClientId/ClientSecret connection. This is my variable set-up:

![image](https://user-images.githubusercontent.com/39077138/228715025-7ffa016e-f4e8-4696-a8bc-b06b4966c79d.png)

**Comment by mikefactorial** [comment]
Closing this out as there's no further action required
