### ISSUE TITLE
[CoE Starter Kit - BUG] Total App Connections Count - how to validate?

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#4967]
### Describe the issue

The total App Connectors on the Power BI Dashboard:
![image](https://user-images.githubusercontent.com/117682988/224753039-041d286c-68f2-471f-9c7f-3266d9bfb779.png)

How do I know this number is correct is there a way to validate this?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

App Connectors

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont know an easy way. Leaving open for now in case someone from the community has an idea.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
