### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 - Update Environment Bad Request

### ISSUE THREAD

**Issue by bealickpulte** [microsoft/coe-starter-kit#4970]
### Describe the issue

After upgrading to the newest version of the CoE Starter Kit, the 'Admin | Sync Template v3' flow has been failing on the 'Update Environment' step within the following conditions:

Apply to each Environment > Check if Legacy Environment > See if already in CoE > See if excused from inventory > Check if SYSTEM created Environment > Update after check orphan status

![image](https://user-images.githubusercontent.com/124098695/224788985-67c099de-197e-4083-a6bb-623d6f33efd4.png)

### Expected Behavior

The flow to either not get to this step based on a currently failing condition check or for the step to handle the inputs without failing.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

1. Navigate to the 'Admin | Sync Template v3' flow
2. Open a failed flow run
3. View error

### Anything else?

This flow was previously successful prior to upgrading to the newest version of the CoE Toolkit. Upon further investigation, this is the condition check from a successful previous run:

![image](https://user-images.githubusercontent.com/124098695/224789986-fb3aad26-c2cf-4637-a624-a8ac48ae872a.png)

For the same environment being checked in the new version of the flow, the failed run shows the following check:

![image](https://user-images.githubusercontent.com/124098695/224790137-b231f45f-f332-4626-b725-3145be978b7f.png)

All the condition is doing is checking for 'userIsSystem' = true from the 'Get Maker' step.

![image](https://user-images.githubusercontent.com/124098695/224790570-6ba2ff20-9742-433f-bb04-ae217ea782dc.png)

But the userIsSystem seems to have the wrong underlying expression. What it is OOTB:

body('Get_Maker')?['Body']?['userissystem']

When I remove and re-add:

body('Get_Maker')?['userissystem']

So it looks like it has an extra 'Body' statement which then isn't yielding the right result for that condition to check against.

**Comment by Jenefer-Monroe** [comment]
Thank you for posting and investigating. I do not repro even though I do have this same operand
![image](https://user-images.githubusercontent.com/89584709/224825512-9d63db30-ac08-4f32-ae29-5e22527b8dad.png)

Here it is working for system
![image](https://user-images.githubusercontent.com/89584709/224825915-91494625-e036-4187-9463-cd240818524a.png)

and not system
![image](https://user-images.githubusercontent.com/89584709/224826217-0d857db8-3667-40f2-8bba-80ca27f9425a.png)

Can you please check for and remove [unmanaged layers](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) on both this flow and the helpers? Then see if you still repro.

**Comment by bealickpulte** [comment]
There were indeed unmanaged layers on the helper flows. After removing those layers, the Admin | Sync Template v3 flow ran successful! Sorry for the false alarm, but I appreciate the help. :)

**Comment by Jenefer-Monroe** [comment]
You are most welcome. Thank you for letting me know!
