### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by BOKF-BP** [microsoft/coe-starter-kit#4971]
### Describe the issue

"Network error when using Patch function: The requested operation is invalid." 
When using the Setup Wizard under "Run Setup Flows" I receive this error above and no flows are displayed.

 Viewing the flow "SetupWizard>RunInitialFlows" seems to succeed without issue running under the correct identity.

### Expected Behavior

The flows should run

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Setup Wizard

### Steps To Reproduce

1. Go to PowerApps in correct environment
2. Run "COE Setup Wizard (Preview)"
3. Go through first 4 steps successfully.
4. Make it to step 5.. see error at top of screen (PFA)

### Anything else?

![2023-03-13 13_27_16-Window](https://user-images.githubusercontent.com/108012422/224798206-8c547890-a2a1-4ebd-8314-ed36248295fb.png)
![2023-03-13 13_25_56-Window](https://user-images.githubusercontent.com/108012422/224798218-eb8607d8-ad2b-4af1-9988-9df6bcf18b50.png)

**Comment by BOKF-BP** [comment]
Spot on. Running the aforementioned flow was all that was needed!

**Comment by HarithaE508** [comment]
I'm also getting the same error: "Network error when using Patch function: The requested operation is invalid." For step 2 in configuring mails, what should I
![coeissue](https://github.com/user-attachments/assets/783614fe-e260-48be-801a-2a969f2f3c0c)
 do?
