### ISSUE TITLE
[CoE Starter Kit - QUESTION] COE - Admin Command center -  navigation menu issues

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#4973]
### What is your question?

Hi Team,

I have issues on COE Admin Command Center App - My navigation menu shows (in the left):

* New sub-zone
* Sync Flows errors (it's okay)
* New sub-zone

I don't think it's a bug but maybe a Misconfiguration.
<img width="115" alt="COE Issues" src="https://user-images.githubusercontent.com/10110260/224841926-c05727c7-bcf8-4c7a-8aaa-6fa0407a234c.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2023

### What app or flow are you having the issue with?

COE Admin Command Center

**Comment by Jenefer-Monroe** [comment]
We have seen a few people issues like this in the Model Driven Apps if they do not have the English language pack installed. Please see [supported languages](https://learn.microsoft.com/power-platform/guidance/coe/limitations#supported-languages)

I hope this helps!

**Comment by tocri** [comment]
hi jenefer.
I have alread installed the English language for the environment.
X
<img width="443" alt="english ok" src="https://user-images.githubusercontent.com/10110260/224849636-d4fa2b5f-6def-4d86-af12-6bf702bf3f01.png">

**Comment by tocri** [comment]
Ok found the answer. Just go to settings and select english language

<img width="421" alt="settings" src="https://user-images.githubusercontent.com/10110260/224872886-b713a4f8-2164-4518-b935-ce9afa9bf7cd.png">

**Comment by Jenefer-Monroe** [comment]
Thank you for letting me know!
