### ISSUE TITLE
[CoE Starter Kit - BUG] Maker-Environment Request

### ISSUE THREAD

**Issue by DHRUVSHAH1803** [microsoft/coe-starter-kit#4976]
### Describe the issue

Unable to get Values in Make-Environment Request App "Data Policy Change Request" Tab ->"Policy" Drop Down. No values were provided to select in Dropdown.

![Maker-Environment Request](https://user-images.githubusercontent.com/85008479/225028613-82648f44-24b1-42b0-9389-6e140e4f81fb.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Maker-Environment Request App

**Comment by manuelap-msft** [comment]
Have you made Data Policies visible for requesting from the Admin app: https://learn.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt#sync-shared-policies?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
