### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inactivity Apps/Flows Notification

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/coe-starter-kit#4980]
### What is your question?

Was wondering, if the makers gets notified about inactive apps/flows and if maker's don't take any action (approve/reject), can you tell me what happens next? 
- Do the manager gets notified about ignored employee notification weekly?
- Also do the maker's get notification about same apps/flows (the one makers ignored in the first place) the next time when the inactivity notification flow runs?

We did full inventory scan and turned-on inactivity notification the other day which then triggered multiple approval emails (in some cases about 30) for the makers who had multiple apps/flows which they hadn't modified. (_There is room for improvement regarding notification which looking at the issues list seems like some work is being done_) Was curious if there is a way for Admin to create exception for certain makers's apps/flows so that they don't get notified? Also, currently it seems like once the apps/flows inactivity notification are rejected, it won't notify about same inactive apps/flows after 4 wks, is there environment variable setting where we can configure this?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2023

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Flows)

**Comment by Jenefer-Monroe** [comment]
Hello, to set expectations, this entire system is quite complex, so we cannot make it work for all tenant situations as tenants have unique needs. There is a large write up and video available for you to explore this feature here: [Inactivity processes](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#inactivity-processes)

To answer your specific questions:
- Yes managers are notified of approvals that have been ignored by their employees. Please see [Admin | Email Managers Ignored Inactivity notifications Approvals](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#admin--email-managers-ignored-inactivity-notifications-approvals)
- Yes if the maker ignores the approval they will be asked again the next run. The process flows in the article I shared are really helpful at making the system more clear. 
![image](https://user-images.githubusercontent.com/89584709/225100239-68e780e7-2234-489e-b7e6-0802c0b755c1.png)
- The reason we do the single mail per app/flow is that this allows the makers to respond via the approval system (in email), which lets them participate without a premium license. We do have thoughts on ways to make this nicer but to be honest I doubt we will do them. Once a maker gets through their backlog the per-app system works well. 
- There is an exemption process for apps. flows and environments. Please see [the setup instructions](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components#exempt-environments-from-the-inactivity-notifications-process)
- There is no way to configure the approval reject to last a different amount of time. It's currently set to match the length of time approvals from flow are active.

**Comment by sanjeev40084** [comment]
Thanks for the info.

**Comment by Jenefer-Monroe** [comment]
You are most welcome
