### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Report Setup error on BYODL version of kit from March 14 - need documentation on privacy setting

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#4982]
### Describe the issue

After setting up the Dataflow, I opened the report template in Power BI desktop.  After putting in the 3 datasource values needed, the queries window opened up and spun for about 15 seconds before erroring out with query errors.  It showed several tables that couldn't refresh.

### Expected Behavior

Expected behavior is for all queries to connect and load the data into the model so connections could be made.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

### What app or flow are you having the issue with?

BYODL_CoEDashboard_March2023

### Steps To Reproduce

1. Open Template in PBI Desktop
2. Authenticate
3. Put in 3 required data source values
4. Watch for error in queries execution screen.

### Anything else?

The weirdest part about this is that I tried this 3 times by closing PBI ad reopening the file and got the same errors all 3 times.  The 3rd time, I just waited and went into the PowerQuery editor window.  In that UI, I was able to just click on each table one by one and all worked.  I could then Save and Close and the report worked.  I added the embedded helper Canvas Apps and published successfully to the PBI workspace.  Not sure it we want to just update the instructions to go down that path, but many users would just assume it's not worth clicking through in PowerQuery window and stop, so thought I should log this to bring attention to it anyway.

**Comment by bartsneary** [comment]
That did indeed “fix” this issue logging into the data sources upon first connection.  😊

***@***.***
Bart Sneary
MTC Architect | 952-837-4560 W or 507-403-3088 M
***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<http://www.microsoft.com/mtc>
***@***.***

**Comment by anttipajunen** [comment]
I tried this and was able to resolve errors by choosing "Always ignore Privacy Level settings".
