### ISSUE TITLE
[CoE Starter Kit - BUG] Custom Connector for Audit Log No Longer Authenticates after Core 4.3.50 Install

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#4985]
### Describe the issue

After installing 4.3.50 Core Solution, I edited the authorization settings for the Custom Connector as usual.  That allowed me to fix the Connection using that connector.  However, the [Child] Admin | Sync Logs Cloud Flow still errors each time it attempts to access the Audit Log Content with the message "Authorization has been denied for this request."

### Expected Behavior

After updating the custom connector auth details with the Client ID, Secret, and Refresh URL and reconnecting the connection, this Flow should be able to query the Audit Logs successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### Steps To Reproduce

See above details.

**Comment by Jenefer-Monroe** [comment]
The default Identity Providor for the custom connector changed to Generic Oauth 2, so likely what happened is that you authenticated to a bad connection. Unfortunately this isnt obvious and clean up isnt that easy. 
![image](https://user-images.githubusercontent.com/89584709/225247140-70c99bb5-5770-428c-b45a-60c3f45e01dd.png)

I've outlined how to clean up from this here: [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

**Comment by bartsneary** [comment]
Thanks!  That fixed the custom connector.  😊

***@***.***
Bart Sneary
MTC Architect | 952-837-4560 W or 507-403-3088 M
***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.microsoft.com%2Fmtc&data=05%7C01%7Cbasneary%40microsoft.com%7Ca0a83e45c81f40e134e708da1bec2ef1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637852998463338691%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xh4tbyy9nNWruHmqu74z0PA6pzgS4ccviMP7zcK3Ut0%3D&reserved=0>
***@***.***
