### ISSUE TITLE
[CoE Starter Kit - BUG] Connection issues with some Admin Flows

### ISSUE THREAD

**Issue by ThomAstra11** [microsoft/coe-starter-kit#4987]
### Describe the issue

since a few days some of our Admin Flows failed with the same error message. For instance the flow Admin | Sync Template v3 failed in step "Get Solutions and Exit if not Solutions in evnt or if no permissions" - Sub-Step "List solutions". In the Outputs we always see this error:

{
  "status": 404,
  "source": "https://europe-002.token.azure-apim.net:443/tokens/europe-002/commondataservice/b710a1b91d334758a7c1c475aeba077a/exchange",
  "message": "Error from token exchange: The connection (europe-002/commondataservice/b710a1b91d334758a7c1c475aeba077a) is not found. Please create new connection and change your application to use the new connection."
}

In the Headers section we see:

{
  "x-ms-failure-cause": "apihub-token-exchange",
  "x-ms-apihub-obo": "false",
  "x-ms-apihub-cached-response": "true",
  "Date": "Tue, 14 Mar 2023 17:01:30 GMT",
  "Content-Length": "363",
  "Content-Type": "application/json"
}

### Expected Behavior

This flow retrieves Solution information. This information is retrieved from underlying Dataverse tables and requires the user running the flow to have system administrator privileges in the environment. Turning on this flow is optional, only turn this flow on if a tenant-level overview of solutions is important

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### Anything else?

![image](https://user-images.githubusercontent.com/120015451/225229769-00d07156-3d3a-40ab-bdda-1ff782f75391.png)

**Comment by Jenefer-Monroe** [comment]
A few things to try
1. If you go to the details page of the flow, are the connections all showing as healthy? (Green check)
Is the identity associated with the Dataverse Legacy connector the one you expect? (the account you expect to be running the sync flows)
![image](https://user-images.githubusercontent.com/89584709/225248330-9e0c7ad3-9676-41c5-ae7a-4db4efd3ba80.png)

2. As the identity shown for Dataverse Legacy connector, try to browse to it?
open the trigger output body and look for admin_environmentcdsinstanceurl > get the URL > Can you browse to it? 
![image](https://user-images.githubusercontent.com/89584709/225250089-7e07c031-290e-473a-94e8-15f62f9049e6.png)

3. If you rerun this flow now (while you are able to browse to the page) does it pass?

**Comment by ThomAstra11** [comment]
Thank you very much. Indeed the Dataverse Legacy connector wasn't in healthy conditions. Didn't realize that because i was focussed on the run history in the failure shown there.

**Comment by Jenefer-Monroe** [comment]
No problem at all, we are glad to help.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
