### ISSUE TITLE
[CoE Starter Kit - QUESTION] The DLP Policy dataverse table is empty, what populates it? Is the CoE Starter Kit missing a Sync Flow that populates this table?

### ISSUE THREAD

**Issue by Secretss7** [microsoft/coe-starter-kit#4988]
### What is your question?

_1st Question:
We have policies created in the Power Platform Admin Center, but there isn't a sync flow that creates records in the DLP Policy dataverse table that is part of the Core Component CoE starter kit. Are we meant to write to it manually? Is there something that writes to this table? Is a record only written when someone requests a policy change?_

_2nd Question:
There is a "Is Shared" field on the DLP Policy dataverse table that gets used in the CoE flow. Do we have to "share" the DLP policy within Power Platform Admin Center for the record to be created in the dataverse table? I don't see any share button though._

### Expected Behavior
_I expect there to be an Admin | Sync Template v3 flow that creates a record in the DLP Policy dataverse table for each policy created in Power Platform Admin Center._

### Steps To Reproduce
_Create a DLP policy in Power Platform Admin Center and watch as the DLP Policy dataverse table remains empty forever._

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3 and 3.45, same issue

### What app or flow are you having the issue with?

There appears to be a missing flow in the CoE starter kit?

**Comment by Jenefer-Monroe** [comment]
This table is only used for the Environment Management App features and is filled there for its usage
If you use the [setup wizard](https://learn.microsoft.com/power-platform/guidance/coe/setup-environment-components#set-up-the-environment-request-components-using-the-setup-wizard) you can see a way to share these there

![image](https://user-images.githubusercontent.com/89584709/225252419-a0711ff1-ba0e-4224-a2d8-d071082e8e9f.png)
