### ISSUE TITLE
[ALM Accelerator - BUG]: Forbidden Error while Activating the Flows

### ISSUE THREAD

**Issue by shree2905** [microsoft/coe-starter-kit#4990]
### Describe the issue

I'm getting error when deploy solution pipeline execute "Activate Flows" task. It was working previously. I've mentioned detailed error below. 

![image](https://user-images.githubusercontent.com/79618656/225285052-87c262f6-1152-4f4e-b1b6-3d5134e23ae3.png)

Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '8403400f-d5dc-4960-bab1-66ba102a5e3a'. Connection '/providers/Microsoft.PowerApps/apis/shared_office365/connections/shared-office365-660c637d-04a3-43d6-8a3e-dd61a464f9ff' to 'shared_office365' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}". => Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '8403400f-d5dc-4960-bab1-66ba102a5e3a'. Connection '/providers/Microsoft.PowerApps/apis/shared_office365/connections/shared-office365-660c637d-04a3-43d6-8a3e-dd61a464f9ff' to 'shared_office365' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".[TerminalFailure] Failed to Execute Command - SetState : RequestID=2a5e3b0a-6a6d-4eae-a7e3-18a036e9543d : Setting Activity State in CRM... workflow duration=00:00:05.2266717 ExceptionMessage = Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '8403400f-d5dc-4960-bab1-66ba102a5e3a'. Connection '/providers/Microsoft.PowerApps/apis/shared_office365/connections/shared-office365-660c637d-04a3-43d6-8a3e-dd61a464f9ff' to 'shared_office365' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".
F 
 I have recently changed the client secret of the service principal and updated likewise in the Azure DevOps service connections and custom connector.
Would this have affected or produced this issue by any chance?
Please help to troubleshoot/resolve this issue.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

June 2022

### Steps To Reproduce

1. Click on the "Deploy Solution" Button in AA4pp App, selected the Source Branch and Target Branch.
2. Now Clicked on Deploy Solution Button.
3. Click on Processing icon --> Navigates to Azure Devops

**Comment by mikefactorial** [comment]
@shree2905 take a look at the issue referenced https://github.com/microsoft/coe-starter-kit/issues/4838. A recent platform change requires that you share your service connections with the service principal. We added an option to share to the service connection screen to make this easier, but the requirement isn't something that we control as the ALM Accelerator team it is a platform wide change that rolled out recently. The alternative to upgrading to the latest version of the ALM Accelerator to make sharing easier for makers is to manually share the connections in the target environments from the maker portal.

e.g. 
![image](https://user-images.githubusercontent.com/42348035/225321025-e6c5a3a3-105b-41c4-92be-f39a47590153.png)

**Comment by shree2905** [comment]
Thank you @mikefactorial.  we've now upgraded the ALM Accelerator to the latest and it is working fine.
