### ISSUE TITLE
[CoE Starter Kit - Feature]: Retrieve the last execution date of Power Automate flow

### ISSUE THREAD

**Issue by RemiChambard** [microsoft/coe-starter-kit#4992]
### Describe the solution you'd like

Hello,

It would be great to collect the last execution date of each Power Automate flow in order to identify flows that aren't used and may be removed.

Thanks

**Comment by manuelap-msft** [comment]
The April release shipped today includes the integration with the Data Export feature, https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-April2023
