### ISSUE TITLE
[CoE Starter Kit - QUESTION] How is this email sent (CoE Starter Kit - Orphaned Objects: Objects without Managers

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#4994]
### What is your question?

I can't tell where to look on how and when this email is sent to admins. the last time it was sent on the 2/28 but not sure where to look to get it working again. 

![image](https://user-images.githubusercontent.com/117682988/225363317-22e15b48-c57a-4cca-8edb-dbbb2f042e62.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

not sure

**Comment by Jenefer-Monroe** [comment]
This is in the **_Request Orphaned Objects Reassigned (Parent)_** flow in the Governance solution, which runs weekly. 

![image](https://user-images.githubusercontent.com/89584709/225427973-17d7573f-87ef-4be8-ac53-6643049545cf.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
