### ISSUE TITLE
[CoE Starter Kit - BUG] Deleted Environments don't get marked as deleted in the inventory

### ISSUE THREAD

**Issue by WinOnMarco** [microsoft/coe-starter-kit#4995]
### Describe the issue

I've deleted an environment and created a new one with the same name and url. In the environment inventory both environments remain listed as "active" environments.

I'm not sure if this only happened because I've re-created another environment with the same name. But for sure in older CoE Version, deleted environments got marked as deleted in the inventory.

Because of this many sync flows get triggered on deleted environments. And of course they then fail.

Additional info: I've set the environment variable "admin_deletefromCoE" to no, in order to keep deleted components and just mark them as deleted.

### Expected Behavior

An environment which got deleted should be marked as deleted. The field "admin_EnvironmentDeleted" should be set to "Yes" and "admin_environmentdeletedOn" shoud have the date the environment was recognized as deleted.
The flow which does this should identify the environment on the environment GUID and not based on the Name or URL, because the latter can be ambiguous.
(unfortunately I didn't verify, if this statement is true because I didn't find the flow which does this check, hence might have this bug).

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

e.g. Admin | Sync Template v3 (Apps) fails, but the causing flow is the one which should recognize and mark an environment as deleted

### Steps To Reproduce

1. Set the environment variable "admin_deletefromCoE" to no
2. Create an Environment with Name "ABC" and URL "abc.crm.dynamics.com"
3. Delete this environment
4. Create another environment with the same name and url
5. Run the sync flows
6. Check if both environments have the correct state in the Admin View App

**Comment by Jenefer-Monroe** [comment]
Hello, the delete operation is done by the **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** flow and its child flows. 
Do you have that turned on and has it run recently? Because of the high API call count, this is set to run every two weeks.

**Comment by WinOnMarco** [comment]
Many thanks for your response. That was it. I forgot that there are flows scheduled in a two weeks interval. Nevertheless some sync flows will fail until the next run of this clean-up.

**Comment by Jenefer-Monroe** [comment]
We try not to mask too many errors in the other sync flows as it will prevent us from catching actual bugs. 
Thanks for letting us know this is working for you!
