### ISSUE TITLE
[CoE Starter Kit - QUESTION] Clone Video Hub for other purposes

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4997]
### What is your question?

Is it possible to clone the "video hub" app from CoE and repurpose it elsewhere in the tenant as a company video hub (non-dev related)

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
Yes, you should be able to "save as" the video hub application to clone it and then you'll have to decide where to get your data from - you might want to add new categories to our existing tables that hold the playlists/videos and filter your clone to just display that our you might want to swap out the data source completely.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
