### ISSUE TITLE
[CoE Starter Kit - QUESTION] Impact of not using Graph API

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#4999]
### What is your question?

What is the impact in CoE starter kit execution if graph api is not allowed in the organisation?

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
Graph API calls are made to get tenant, user and group information - to identify for example users that are service principals, inactive, get the group size etc. Your inventory would be out of date in terms of the maker information, and as the HTTP with Azure AD connector is used in the sync cloud flows I think they would also all fail if that connection can't be established.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
