### ISSUE TITLE
[ALM Accelerator - BUG]: Link between Canvas App and Flows gets lost during deployment

### ISSUE THREAD

**Issue by FRITTENPIET** [microsoft/coe-starter-kit#5001]
### Describe the issue

I have developed a solution that includes a Canvas App and several Power Automate Flows.

The Canvas App is connected to the flows and users call the flows via the app when certain actions are performed: 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/98097794/225319395-ebdf6a80-2c7c-4b8e-bf79-f826fcd57e66.png">
I use the Power Apps (V2) trigger in the Power Automate flows. In my development environment everything works fine and as expected.

In the Deployment Settings for Test, I share the Canvas App with an AAD group and define a team for the flows as recommended, so that users of the app can call the flows:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/98097794/225326177-334bce25-db11-4b6e-9321-c266e84a9099.png">

After a successful Deployment to Test Environment the link/connection between the Canvas App and the Power Automate Flows gets lost. The App is only connected to 1 of 3 Flows in Test:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/98097794/225375276-dbfe1202-1b73-42e9-aff3-cea5cd52de1d.png">

**Why is the link between the app and the to two flows not transferred to the test environment?**

### Expected Behavior

After a Deployment to another environment the link/connection between the Canvas App and Power Automate Flows still exists and all users can trigger the Flows via the Canvas App.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

February 2023

**Comment by mikefactorial** [comment]
@FRITTENPIET do you see the same behavior in the Validation environment before it is deployed to Test or only in Test?

**Comment by FRITTENPIET** [comment]
@mikefactorial Yes it happens both in Validation and Test Environment. 

Didn't deploy to Prod yet, but i think there would be the same effect.

All three flows using the same connections and the Power Apps (V2) Trigger.

A differnce between them is that the Flow, which remains connected to the app, sends a response back to the app. The other two Flows don't send a response to the app.

But in the past i already deployed flows successfully, that also don't respond to the app.

**Comment by mikefactorial** [comment]
@FRITTENPIET wonder if just publishing the app and exporting again might fix it, but would be interested to see if those flows are being persisted into the repo. e.g.

![image](https://user-images.githubusercontent.com/42348035/225421467-03f61598-a256-40b9-8936-7df35eb2aa61.png)

**Comment by mikefactorial** [comment]
Closing this out as there's no further action required here.
