### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by erica-hoersch** [microsoft/coe-starter-kit#5005]
### Describe the issue

The inactivity notification is sending an approval for a flow or app that was already approved for deletion.  

### Expected Behavior

I expect the inactivity notification to ignore flows or apps that are marked for deletion.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps)

### Anything else?

![Capture](https://user-images.githubusercontent.com/127998119/225453896-6a1e9efa-cd10-4ab7-8e91-ea87a4658946.PNG)

**Comment by Jenefer-Monroe** [comment]
Hello. there was a bug in Gov recently where some of the operands in flow were lost and so filters werent working. You will not see this any longer if you upgrade to the Feb release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
