### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Platform CoE Starter Kit Office Hours - March Session

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#5011]
### What is your question?

Hi 

Power Platform CoE Starter Kit Office Hours - March Session

some of us could not make it to attend the meeting happened yesterday .

Could we have any link of reordered sessions or links in YouTube 

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately we are not able to share these recordings at this time

**Comment by Jenefer-Monroe** [comment]
The presentation part of the session was spent introducing the new Data Export architecture for object inventory and usage. 
Please see https://aka.ms/coebyodl to read about it!

**Comment by pamatihyd** [comment]
Thank you so much
