### ISSUE TITLE
[CoE Starter Kit - DOCUMENTATION] - Update documentation to include a check on the correct tables getting updated

### ISSUE THREAD

**Issue by ValentinMaz** [microsoft/coe-starter-kit#5013]
### Describe the issue

Error when trying to refresh the CoE BYODL Environments dataflow. When getting the refresh history export I see the error below:

"Error Code: Mashup Exception Error, Error Details: Couldn't refresh the entity because of an issue with the mashup document MashupException.Error: Expression.Error: We cannot convert a value of type Table to type Text. Details: Value = #table({"Name", "environmentId", "environmentName", "isDefault", "environmentState", "environmentUrl", "environmentType", "securityGroup", "purpose", "cdsMetadataName", "cdsInstanceUrl", "createdOn", "createdBy", "lastModifiedOn", "lastModifiedBy", "deletedOn", "environmentRegion", "tenantId", "environmentGUID", "QueriedOn", "IsOrphanText"}, {}) (Request ID: e558cc47-a099-4591-a018-509bf38ecb54)."

All other Dataflows are refreshing correctly.

(I also noticed that the Dataflow is configured to write into a new table as opposed to update the existing admin_environment table, is that expected?)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

### What app or flow are you having the issue with?

CoE BYODL Environments

### Steps To Reproduce

1. Import solution
2. Follow steps with the Wizzard
3. Open Dataflow, update connections
4. Publish Dataflow

**Comment by manuelap-msft** [comment]
Hello,

can you open the Dataflow, select the Environments table and click through the Applied steps on the right hand side. Is there a particular step during the query processing where this error appears?
![image](https://user-images.githubusercontent.com/55705669/225614314-11ffd95d-d1a8-45e3-bcb0-0e80abeea100.png)

Can you also go to Options > Global Options and change them to this
![image](https://user-images.githubusercontent.com/55705669/225614561-d4afe882-69d6-4447-9ecc-aeec18cf7187.png)

This should then show you a column profile - are there any errors shown there?
![image](https://user-images.githubusercontent.com/55705669/225614665-f3e41dda-ec73-463b-bcee-9f2bf5fa95f5.png)

In the load settings, all queries except Environments should be italic, indicating that they are not loading to any table. The Environments table should be in normal font and load to the admin_Environment table. 
![image](https://user-images.githubusercontent.com/55705669/225614867-0772c5c0-d33f-4548-bc5b-fc85de8dc056.png)

This has always worked in our tests; have you made any changes to the Query steps in the Power Query screen? This can lead to the load settings getting reset.

**Comment by manuelap-msft** [comment]
Great to hear you didn't get any errors during the Query, that should mean everything is working fine. 

The Mashup error of "We cannot convert a value of type Table to type Text." indicates that during data mapping, a table column from the query (source) is written to a text column in the table (destination) and that's why it fails. Likely that has to do with your mapping haven fallen out of place and it not writing to the admin_environment table - I can't think of another reason why that would happen.

All your other dataflows are writing to the correct admin_ table and not a new one, right? 

Hopefully this is just a small glitch and when you set it up in a new environment it will work for all dataflows - if it continues to fail, please let us know what region your environment is in so we can test this on our end to see if we can reproduce the issue!

**Comment by ValentinMaz** [comment]
Hello Manuela:
- "All your other dataflows are writing to the correct admin_ table and not a new one, right?" -> yes
- After re-importing and configuring the solution into another tenant/environment I did not face the same issue and all the dataflows were writing into the existing tables. I am still unsure how I could have made that mistake in the first place, but definitely seems to be something I did as opposed to an issue with the solution package...
Sorry for the false alarm!

**Comment by manuelap-msft** [comment]
Hi Valentin,

no need to apologize - it's honestly not ideal that you have to go in and edit the dataflow to update it with the connection/parameters, as that opens it up for other involuntary edits that can then lead to the mapping getting lost. We'll add to our documentation also to verify that the correct tables get updated to avoid unnecessary new tables getting created. We are also working with the Dataflow team to provide feedback on the importance of Dataflows supporting connection references and environment variables, just like cloud flows do, as if they supported those concepts you wouldn't have to go in and edit the Dataflow to begin with. Hopefully at some point in the future that will be possible! 

Glad you got it all set up and working now, and please let us know if you have any additional questions or face other issues!

Thank you
Manuela
