### ISSUE TITLE
[CoE Starter Kit - BUG] PowerBI Dashboard Refresh Error

### ISSUE THREAD

**Issue by Sishira** [microsoft/coe-starter-kit#5014]
### Describe the issue

Dashboard refresh giving below error:

Query 'Flow Connection Reference' (step 'Outer Join') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination.

Query 'Flow' (step 'Removed Columns') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination.

### Expected Behavior

Refresh should be successful

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

PowerBI Dashboard -Production_CoEDashboard_February2023

### Steps To Reproduce

Open PowerBI Production_CoEDashboard_February2023
Enter Org URL
SignIn
Refresh
It should give error during refresh

**Comment by manuelap-msft** [comment]
If the above doesn't work, we have sometimes seen these issues based on security/privacy settings of Power BI Desktop. Can you then try:

Open Power BI Desktop
File > Options > Options
Under Security, untick the box for Require user approval for new native database queries
Under Privacy, either check Always ignore Privacy settings or Always combine data according to the Privacy Setting for each source

**Comment by Sishira** [comment]
Updated BI dashboard and followed all recommended steps (screenshot below) but still not able to refresh:

![image](https://user-images.githubusercontent.com/99423817/225742972-a0542077-c46f-48e1-b9e5-b8cecf2c1ff3.png)
![image](https://user-images.githubusercontent.com/99423817/225743122-82b83c68-d7e3-40cf-a9cc-c3b94b924696.png)
![image](https://user-images.githubusercontent.com/99423817/225743960-5cc776a8-2819-4a69-a9b8-8c72a03abb8e.png)

**Comment by Sishira** [comment]
Below is the new issue I see post-upgrade and apply the above change:
AI Builder Models
The key didn't match any rows in the table.

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Sishira** [comment]
This is working fine now. I just had to restart the post-upgrade of BI or apply recommended changes.

**Comment by Jenefer-Monroe** [comment]
thank you for letting us know!
