### ISSUE TITLE
[CoE Starter Kit - QUESTION] Troubleshooting flow BYODL>Configure Enviornment is meant to be off

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5016]
### Describe the issue

BYODL>ConfigureEnvironment Trigger is showing to have an error. 
![image](https://user-images.githubusercontent.com/95443860/225741879-eb8695bc-64fd-4731-85d2-fb6fa1e52f12.png)

![image](https://user-images.githubusercontent.com/95443860/225741522-b7f24c94-711a-4c0d-97be-0fb0e0c9bb52.png)

Headers:
{
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
  "X-Content-Type-Options": "nosniff",
  "Content-Security-Policy": "default-src 'self'; child-src 'none'; manifest-src 'none'; media-src 'none'; object-src 'none'; connect-src https:; img-src 'self' https://p.sfx.ms data:; style-src 'self' 'unsafe-inline'; frame-src *; frame-ancestors 'self' https://adf.azure.com https://ms-adf.azure.com https://*.consent.dynamics.com https://*.ci.ai.dynamics.com https://*.api.ci.ai.dynamics.com https://msit.powerbi.com https://app.powerbi.com https://www.powerbi.com https://pbi-wfe-us-north-central.powerbi.com https://admin.powerplatform.microsoft.com https://dataintegrator.trafficmanager.net https://admin.powerapps.com https://admin.flow.microsoft.com https://*.admin.powerapps.com https://*.admin.flow.microsoft.com https://*.businessplatform.microsoft.com https://*.officeapps.live.com https://*.optin.online.office.com https://us.flow.microsoft.com https://make.powerautomate.com https://*.insightsplatform.microsoft.com https://*.crm.dynamics.com https://*.iom.d365.dynamics.com https://www.office.com https://scuprodprv.www.office.com https://outlook.office365.com https://outlook-sdf.office365.com https://outlook.office.com https://outlook-sdf.office.com https://teams.microsoft.com https://teams.powerbi.com https://web.powerapps.com https://*.web.powerapps.com https://make.preprod.powerapps.com https://make.preview.powerapps.com https://make.powerapps.com https://sci.preview.dynamics.com https://sci.dynamics.com https://windblade.preview.dynamics.com https://windblade.dynamics.com https://digitalsupplychain.preview.microsoft.com https://digitalsupplychain.microsoft.com https://*.sustainability.prod.powerapps.com https://web.azuresynapse.net https://ms.web.azuresynapse.net https://pbidpe.powerbi.com https://pbi-dfw-edog.analysis-df.windows.net https://pbidfw.powerbi.com; font-src 'self' https://static2.sharepointonline.com https://spoprod-a.akamaihd.net https://spoppe-b.azureedge.net; worker-src 'self';",
  "X-Rate-Limit-Limit": "30s",
  "X-Rate-Limit-Remaining": "999",
  "X-Rate-Limit-Reset": "2023-03-16T20:09:04.9470112Z",
  "Timing-Allow-Origin": "*",
  "Server-Timing": "total;dur=1022,route;desc=\"DataflowConnector/GetDataflowRefreshHistory\"",
  "x-ms-apihub-cached-response": "false",
  "x-ms-apihub-obo": "false",
  "Cache-Control": "no-cache",
  "Date": "Thu, 16 Mar 2023 20:08:35 GMT",
  "Content-Length": "517",
  "Content-Type": "application/json"
}

### Expected Behavior

Flow should run on when triggered. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

### What app or flow are you having the issue with?

BYODL>Configure Enviornment Flow

### Steps To Reproduce

Attempted to turn flow on.
Error Message shows up.

**Comment by manuelap-msft** [comment]
Hello,

this flow is not meant to be turned on; it's in there to make debugging and troubleshooting easier if the dataflows fail. Could you let me know what instructions led you to think this flow needed to be turned on, so we can adjust our documentation?

Thank you
Manuela

**Comment by nasilvae** [comment]
> Hello,
> 
> this flow is not meant to be turned on; it's in there to make debugging and troubleshooting easier if the dataflows fail. Could you let me know what instructions led you to think this flow needed to be turned on, so we can adjust our documentation?
> 
> Thank you Manuela

sounds good, thank you. I attempted to turn on the flow as the other BYODL flows were turned on by the wizard and I believed that this flow was left out.

**Comment by Jenefer-Monroe** [comment]
We can rename the flow so this is more obvious! Will do that for April
