### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log Components Not Working after BYODL Upgrade

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5025]
### Describe the issue

Audit Log flows not working after BYDL upgrade. I receive a not authorized error. I have reconfigured the custom connector and re-test it. Upon testing the reconfigured custom connector. I have also validated that the account has access to the compliance center audit logs and it has the audit logs security permissions assigned to it.  I receive the following error. 
![image](https://user-images.githubusercontent.com/95443860/225915179-24d1a1b8-8b8d-433c-8ddd-9ffd5b5ba759.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs & Custom Connector

### Steps To Reproduce

Attempted to re run flow and retest connector.

**Comment by Jenefer-Monroe** [comment]
The default Identity Providor for the custom connector changed to Generic Oauth 2, so likely what happened is that you authenticated to a bad connection. Unfortunately this isnt obvious and clean up isnt that easy. 
![image](https://user-images.githubusercontent.com/89584709/225247140-70c99bb5-5770-428c-b45a-60c3f45e01dd.png)

I've outlined how to clean up from this here: [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

**Comment by manuelap-msft** [comment]
PS: It's missing from our documentation at the moment, but just sharing here: The Audit Log custom connector and Audit Log solution will not be required if you've set your solution up to use Data Export. Usage data is provided via the Data Export feature then.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
