### ISSUE TITLE
[CoE Starter Kit - BUG] Data Flow  CoE BYODL Apps

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5028]
### Describe the issue

Hi Team, 

We have configured the CoE BYODL Apps data flow as part of the setup process but we noticed that we are getting an error saying that the path cannot be found. We also experiencing the same error with the apps connection data flow and the Flows Dataflow. The tenant is based in Europe, it has been about two days since we setup the export. We have also verified the storage account the application folder in question is not in the storage account yet. We are not sure if this is because of the data export still processing or something else. 

![image](https://user-images.githubusercontent.com/95443860/225971346-93eda8c0-44a7-4cc3-a6e8-dbc97dc5aeeb.png)

### Expected Behavior

Data Flow should work.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

### What app or flow are you having the issue with?

Data Flows Apps & Flows

### Steps To Reproduce

Running DataFlows.

**Comment by Jenefer-Monroe** [comment]
It can take several days for the system to get all the way setup, and they can come in one at a time, so some be there but not all. 

You should see these in the powerapps folder
![image](https://user-images.githubusercontent.com/89584709/225979979-d36afcd4-552c-4dbb-b2de-4e6197a2c73a.png)

and these in the power automate folder
![image](https://user-images.githubusercontent.com/89584709/225980053-ccf506b6-2790-46d7-a7a7-eb0332fd3e0d.png)

**Comment by Jenefer-Monroe** [comment]
Adding for consideration to add to the docs
