### ISSUE TITLE
Environment Naming Best Practices

### ISSUE THREAD

**Issue by aslmbhai** [microsoft/coe-starter-kit#503]
I work with Microsoft customers and they often ask questions about Microsoft best practices around Flow/App or Environment naming conventions.

Can we define docs around naming convention best practices? 

Initial thinking is to use the following format.
Line of Business Name-Flow or App function-Environment type

For Org wide: ORG-Flow or App function-Environment type
Retail Banking-ApprovalsFlow-UAT
Retail Banking-ApprovalsFlow-Prod

HR-ApprovalsApp-UAT
HR-ApprovalsApp-Prod

 For Org wide, it could be “CustomerName-ApprovalsApp-Prod”

**Comment by manuelap-msft** [comment]
Hello,

thanks for reaching out! This repo is for issues & feedback requests regarding the solutions shipped as part of the CoE Starter Kit. You can report bugs or feedback requests for the solutions here. Your request is not tied to tooling, as such this isn't the right place for it - maybe you can start a discussion in the Power Apps Community to get some input from how others are managing this https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/bd-p/Admin_PowerApps

From experience, typically customers have their own naming conventions for Environments sometimes following existing naming conventions from how they manage resources in Azure. Naming conventions for apps and flows with citizen developers building hundreds and thousands of apps are much harder to sustain, and I would advise spending time on a robust environment strategy https://docs.microsoft.com/en-us/power-platform/guidance/adoption/environment-strategy vs trying to force citizen makers down a path of naming their apps/flows. 

Thank you
Manuela
