### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to update Community URL environment variable to turn on Welcome Email flow

### ISSUE THREAD

**Issue by rr41188** [microsoft/coe-starter-kit#5033]
### Describe the issue

Hello ,

I am getting an error message when I tried to turn on Admin | Welcome Email v3 flow  that mentioned in  __**"Set up other core components using the Setup Wizard"__**

Error message " Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_CommunityURL'."}}".

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.2

### What app or flow are you having the issue with?

Admin | Welcome Email v3

**Comment by manuelap-msft** [comment]
The error you are receiving
**"Attribute 'value' was not found for environment variable 'admin_CommunityURL'."**

indicates that the environment variable admin_CommunityURL, which is used by this flow, does not have a value. The flow can not be turned on if this environment variable isn't provided.

You can set this environment variable either by using the **Capacity alerts and Welcome email setup wizard page**
![image](https://user-images.githubusercontent.com/55705669/226319580-acdc6047-4029-4ec1-a2a1-6ccd59a39b63.png)

or by opening the **CoE Admin Command Center** and navigating to Environment Variables from there
![image](https://user-images.githubusercontent.com/55705669/226319740-42d894f2-65e1-4adb-bd98-073fbdc3182f.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
