### ISSUE TITLE
[CoE Starter Kit - QUESTION] Feb release showing Power Platform will start relying on a new cloud service dependency for data residency compliance, evaluate adding/updating URLs to your firewall rules.

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#5036]
### What is your question?

Power Platform will start relying on a new cloud service dependency for data residency compliance, evaluate adding/updating URLs to your firewall rules.

https://learn.microsoft.com/en-us/power-platform/admin/online-requirements

Recently, I have installed CoE components in one environment, from then I m seeing above  message. Is it relevant to CoE set up ?
Because I do have other environments with CoE but I am not seeing this message .

Kindly please clarify...

![image](https://user-images.githubusercontent.com/29652263/226305908-4a23d5ee-f96e-40f4-be3f-f5461db87469.png)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.6

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid this is out side of the scope of the kit. It's likely something to do with the environment specifics of where you installed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
