### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can I use Dynamics 365 Customer Service Enterprise license instead of Power Automate Per User License?

### ISSUE THREAD

**Issue by anujay123** [microsoft/coe-starter-kit#5037]
### What is your question?

Hi there, 
Sorry if i am asking license question which may look similar to some of other questions raised in the forum. I checked the list of all relevant questions and couldn't find anyone raising this specific question. 
We are not using Power Automate per user plan in our organisation. Instead we have Dynamics 365 Customer Service Enterprise license.  
As per Microsoft licensing guide,  D365 Customer Service Enterprise license supports running Power Automate with Premium connectors "withing the context of app". Additionally Dataverse connectors are listed as Premium connectors. Can i use this license for the user who is installing / setting up CoE starter kit and running regular inventory flows? 
Will there be any issue with premium connectors like Dataverse?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

December 2022

**Comment by Jenefer-Monroe** [comment]
Hello. We are not licensing experts so I cant be certain on all these variety of license options. 
I do know some Dynamics license types will do it for you and can tell you how to test. 

### Test
1. Create a new flow as a user with the license type
2. Add a List rows action form the Dataverse connector
3. Have it list from any table, doesn't really matter
4. Settings > Turn on Pagination > Threshold = 100000 > Done
![image](https://user-images.githubusercontent.com/89584709/226338926-aa5f5d5f-9c26-4935-8160-c19d9d4db1eb.png)
5. Save > Ignore the warning > Test > Manual > Test
![image](https://user-images.githubusercontent.com/89584709/226339240-028b0c9d-930e-437e-956c-ef6aca8aba83.png)

### Result
If you get a pagination warning then your license type is insufficient. 
If it passes then you have a sufficient license type.

**Comment by anujay123** [comment]
Hi Jenefer,
Thank you very much for the prompt response. Highly appreciate your support.
I tried it and it didn't give me any pagination warning. Managed to run the flow. Flow run did give me error: 
"Http request failed as there is an error: 'Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'."
As per MS Docs it's because of Maximum Message Size limit which i guess shouldn't be a issue for CoE. Hope my understanding is right.
Thanks again,

**Comment by Jenefer-Monroe** [comment]
Yes that error is unrelated to licensing and just means you have too much data in the table you tested with (Accounts?) that will not impact usage of the kit. 
It sounds like you are will be ok with that license type.

**Comment by anujay123** [comment]
That's great. Thank you Jenefer for your support

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
