### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by EmelynTr** [microsoft/coe-starter-kit#5039]
### Describe the issue

Buen dia, estoy realizando la importación de la solución, pero al momento de activar flujos secundarios me aparece un error, lo cual impide la activación.
Esto ocurre en varios flujos.
![error](https://user-images.githubusercontent.com/128402165/226393809-065a0516-8d92-4038-bba9-95b724a1d61f.PNG)

Error al activar. Se devolvió el error del cliente de flujo con el código de estado "BadRequest" y los detalles "{"error":{"code":"XrmConnectionReferenceMissingConnection","message":"Falta el id. de conexión para el nombre lógico de la referencia \"admin_CoECoreO365Users\"."}}".

### Expected Behavior

Lo que espero es activar los flujos para poder implementar el centro de excelencia con normalidad.
![error2](https://user-images.githubusercontent.com/128402165/226394268-4988b511-7594-41f0-b3a6-c72f02cc741b.PNG)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Helper y Administracion

### Steps To Reproduce

1. En este entorno
2. ir a soluciones
3. Ir a centros de Centro de excelencia: componentes básicos.
4. Ir a flujos de nube
5. Activar HELPER - CloudFlowOperations
6. Error

### Anything else?

Se realizo cada paso con exactitud según el documento https://learn.microsoft.com/es-es/power-platform/guidance/coe/setup-core-components

**Comment by Jenefer-Monroe** [comment]
This sounds like the situation where you are turning on the flows with a different user than you installed with. 
Unfortunately this cross user flow usage is not simple in the product today. You will either need to log in with the identity you used to install the kit or transfer all the connections over to the new user (and that user needs to meet all the license/role [requirements from setup](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with))

See here for how to transfer the connection tp a new user: [Co-authoring and Connections](https://learn.microsoft.com/power-platform/guidance/coe/limitations#co-authoring-and-connections)

**Comment by EmelynTr** [comment]
La instalación del kit y la configuración del mismo se esta realizando con el mismo usuario y tiene el rol de administrador global.

**Comment by Jenefer-Monroe** [comment]
Please open the details view of the **_HELPER - Maker Check_** flow, do the connection references there show the correct name? And do they all show as green? If so, turn that flow on. (its required for the flow you are trying to turn on)
![image](https://user-images.githubusercontent.com/89584709/226412412-36e063d9-0338-4d55-b7b5-77fc8418befb.png)

Now do the same for the for **_HELPER - CanvasAppOperations_**
![image](https://user-images.githubusercontent.com/89584709/226412944-b842d90e-c0a7-48d7-8ff9-6e945b33da17.png)
![image](https://user-images.githubusercontent.com/89584709/226413117-70708911-8e92-45a5-a91f-1a907be0e1e2.png)

Then also check its run only users properties. They should be for that same user identity
![image](https://user-images.githubusercontent.com/89584709/226413376-61b29690-7425-49c6-ba28-818fd1491328.png)
![image](https://user-images.githubusercontent.com/89584709/226413544-386cc79a-61dc-43e3-a978-1cf183cfaf59.png)
