### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is the Power Automate license a new requirement?

### ISSUE THREAD

**Issue by brucetbarrett** [microsoft/coe-starter-kit#5040]
Was previously running CenterofExcellenceCoreComponents_3.41_managed (Sep 2022). I tried to update to CenterofExcellenceCoreComponents_3.41_managed (Feb 2023) without success. I deleted the old version as the data was not critical and reinstall, but the Setup Wizards appears to show I'm missing a Power Automate license (wasn't required before).

Is this new and/or required?
![image](https://user-images.githubusercontent.com/39774485/226397258-2f272c8c-7189-45c8-a5e4-4087d32caf4f.png)

**Comment by manuelap-msft** [comment]
This is not a new requirement, a Power Automate license has always been required to run the CoE kit. 

The CoE kit contains flows that run in context of Power Apps (for which a Power Apps license is sufficient), but most of the flows run standalone outside of the context of Power Apps thus a standalone license is required. Some of this may not be enforced in the product, e.g. you will be able to turn on a standalone flow if you only have a Power Apps license but it doesn't follow our license guidance, see here the Power Apps use rights only include execution of cloud flows within the app context
![image](https://user-images.githubusercontent.com/55705669/226404865-802a1abf-648e-4154-8b89-660153c61804.png)

Before the setup wizard, you likely just turned on the flows with your Power Apps license as the above guidance is not enforced today. 

Note that even in the setup wizard, you should be able to proceed to the next step despite missing this license - the check here is for information only.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
