### ISSUE TITLE
[ALM Accelerator - BUG]: Request Connection from Another User Missing Parameter

### ISSUE THREAD

**Issue by jfung85** [microsoft/coe-starter-kit#5042]
### Describe the issue

When clicking on the icon for "Request a New Connection from Another User" 
![image](https://user-images.githubusercontent.com/97466777/226476271-da2f0e6d-45b8-4d69-81a6-1b3dc9eed0b0.png)
, the email that is generated contains a link that is broken. It seems like it is trying to reference an app but does not have all the GUID references. 
![image](https://user-images.githubusercontent.com/97466777/226476638-b047279d-ff5f-4366-a62b-5ac92d4667d7.png)
![image](https://user-images.githubusercontent.com/97466777/226476694-43ad2780-e749-4ed3-9330-818e6e35c03b.png)

### Expected Behavior

I expect to be able to click on the link sent by the "Request a New Connection from Another User" feature and create a connection for use by the ALM Accelerator.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

 Accelerator Version: 1.0.20230206.1(Managed)

### Steps To Reproduce

1. In the environment where ALM Accelerator is installed
2. Open ALM Accelerator for Power Platform
3. For a solution, click on Configure Deployment Settings
4. Under Connection References, click on the icon for "Request a New Connection from Another User" 
5. Allow Pop-Ups to see the email that will be sent
6. Click on the link in the email

**Comment by mikefactorial** [comment]
Hey @jfung85 thanks for reporting this. Will look into what's going on here.

**Comment by shree2905** [comment]
Hi @mikefactorial, I'm also facing the same issue. when user clicks the autogenerated link, user is getting below screen. 

![image](https://user-images.githubusercontent.com/79618656/226899152-45b6e4d1-e796-4b6c-9598-f77a763d2536.png)

Can you please help us understand this issue or way to fix this on our end?

**Comment by mikefactorial** [comment]
I was able to track down the issue. It will be fixed in the April release in two weeks.

**Comment by jfung85** [comment]
I installed the latest version of ALM Accelerator (Accelerator Version: 1.0.20230405.2(Managed)) and tried the feature again to request a connection. The email generated still has a broken link. How can we check if this is actually fixed?
![image](https://user-images.githubusercontent.com/97466777/230660272-6197b001-cf19-4731-ae9e-e73042540a77.png)

**Comment by mikefactorial** [comment]
@jfung85 reopening this. Hard to tell without seeing the link. The issue was that there was a parameter missing in the link. Specifically, the step=. This should be resolved now. You may want to try and use an in private browser window to test. It takes some time for browser cache to catch up with new versions. Also, be sure there are no unmanaged layers in your solution which could prevent the app from updating.

**Comment by jfung85** [comment]
@mikefactorial, could I send the link to you directly? I didn't want to post it because of the GUID's that are in the URL. I confirmed that there is no unmanaged layer on the ALM Accelerator for Power Platform app and also confirmed the version number on the app has incremented to the April version.

**Comment by mikefactorial** [comment]
Sure @jfung85 v-ochsmikeatmicrosoftdotcom

**Comment by mikefactorial** [comment]
Thanks @jfung85. So, it looks like it's not an issue with the parameters which was the fix we put in for the latest release. Looks like it's a problem with getting the id of the ALM Accelerator app itself via the PowerAppsForMakers via this PowerFX.

```
Filter(
            PowerAppsforMakers.GetApps().value,
            properties.displayName = AppName && properties.environment.name = ExecutingEnvironment.tags.environmentName
        )
    ).name
```

Any chance the display name of the app was changed? Other than that it seems like a permissions or environment issue. What geo is the ALM Accelerator app running in? Is this a GCC environment or another cloud other than the public cloud?

**Comment by jfung85** [comment]
Hi Mike,

Is this supposed to return the App ID?  The name of the app didn’t change.

This potentially sounds like another case where there are many apps in this environment and perhaps the function is limited by some threshold.

I ran into something similar trying to return versions. Could this be the issue here?: https://powerusers.microsoft.com/t5/Building-Power-Apps/Version-Number-for-apps-with-more-than-100-versions/td-p/1389859

Thanks,
Jonathon Fung
Solutions Manager | Compass365, a division of General Networks Corporation
***@***.***| www.compass365.com<http://www.compass365.com/> | C: 949-307-6304
