### ISSUE TITLE
[CoE Starter Kit - BUG] Launches in the past 30 days - empty for sync flow architecture

### ISSUE THREAD

**Issue by nrd2015** [microsoft/coe-starter-kit#5043]
### Describe the issue

Dear Experts,

I am using the "Power Platform Admin View" app to get an inventory of the apps in our tenant. We are trying to identify the most active apps and I have created a view to include the "Launches in the past 30 days" column.  However the column is blank for all the apps. 

I have verified that the audit log flows are running successfully.
If I drill down to view the usage detail for the app, I can see the app launches records created for the app.

But for some reason the app launch information is not rolling up to the "Launches in the past 30 days" column.

### Expected Behavior

The app usage/launch information should roll up to the "Launches in the past 30 days" column.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

I am not sure

**Comment by nrd2015** [comment]
Thank you for the detailed information @Jenefer-Monroe

**Comment by Jenefer-Monroe** [comment]
You are most welcome.
