### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Command Center - Dataflows Page - Missing dataflows and shortcut invalid

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#5044]
### Describe the issue

In the CoE Dataflows page of the CoE Commnad Center app of de Byodl solution:

1. It's missing some coe dataflows. Only it's showed 4 of the 9 CoE BYODL Dataflows.

![image](https://user-images.githubusercontent.com/57954993/226565335-abd4ccd7-7b19-4f0f-bc51-8a368a80e501.png)

![image](https://user-images.githubusercontent.com/57954993/226566506-77b4740e-b58f-44f1-94b6-d3aa4065a664.png)

2. If you click on the shortcut "Open dataflow" the url to go it's incorrect "https://make.powerapps.com/environments//dataintegration". It's missed the Environment ID.

3. And the timestamp of the Last refresh it's incorrect in dataflow "app last launched date" and "flows last run date"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

### What app or flow are you having the issue with?

CoE Command Center

**Comment by manuelap-msft** [comment]
Fixed for April release
![image](https://user-images.githubusercontent.com/55705669/226599993-e66ca3ab-09c5-465e-a9dd-2a0650ac3b69.png)
