### ISSUE TITLE
Power Automate calls exceeds the limit by much

### ISSUE THREAD

**Issue by sanderslangen** [microsoft/coe-starter-kit#5045]
### Describe the issue

We installed the Center of Excellence Starter Kit and currently it is working fine.
But we have so much Power Automate calls that we find it very disturbing.
The limit is around 40.000 and we got daily around 300.000 calls.
![image](https://user-images.githubusercontent.com/24586028/226580170-f4430845-23ea-4cef-92ac-d6cce9998c16.png)

Are we the only one with that many calls?
What is the reason we get so many calls?
What can we do to reduce these calls?

I would like to hear from you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

All of them

**Comment by manuelap-msft** [comment]
The way the CoE kit works is it uses Power Automate cloud flows to crawl your tenant, find Power Platform resources and store the meta data of those resources in Dataverse tables to allow holistic overview of your tenants inventory and usage in Power BI dashboard and enable governance process, such as identifying inactive or orphaned apps and flows, on those resources. Many of the cloud flows run on a daily basis, and some weekly, and the number of API calls depends on the number of resources (environments, apps, flows) in your tenant. It is known that many of these flows consume a high number of API calls. 

The alternative, which over time will reduce the number of API calls, is to use the integration between the CoE kit and the Data Export feature, which is currently in experimental preview:
https://github.com/microsoft/coe-starter-kit/issues/4977

This feature will use less cloud flows, and thus will reduce the number of API calls.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
