### ISSUE TITLE
Why is the "PVA Bot Usage"  not being updated in the CoE kit

### ISSUE THREAD

**Issue by RowdyAce** [microsoft/coe-starter-kit#5046]
Hello,

I am trying to figure out why the  "PVA Bot Usage"  is not updating in the CoE kit. The ChatBot is recording the Analytics ok in Power Virtual Agent.  

Spoke to Microsoft and below was the response and directed me here …
We have been investigating the behavior described on this case, and it seems that there is some flow that is not running well on the background and is failing with the following error message: "A binary operator with incompatible types as detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'.". 

We need to understand now if this flow “Admin | Sync Template v3 (PVA Usage)” is the one updating that information on the PowerBI Dashboard or if the information not appearing is related with something else.

Thank You,

Newbie to PVA

**Comment by Jenefer-Monroe** [comment]
Hello. To start with ,can you please let us know what version of the kit you are using? You can find that information on this screen
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by RowdyAce** [comment]
![CoE Version](https://user-images.githubusercontent.com/128477450/226687715-a5798a20-8317-409e-8c87-41f74fbf26eb.JPG)
![PVA Bot Flow Failure](https://user-images.githubusercontent.com/128477450/226687858-fa8abc58-1c02-4f4d-b44b-35352a51b7dd.JPG)
![ChatBot - AIDA](https://user-images.githubusercontent.com/128477450/226687887-7a2f236d-a485-4624-9ee6-5469afd3465f.JPG)

**Comment by RowdyAce** [comment]
![Analytics in PVA](https://user-images.githubusercontent.com/128477450/226688990-d7bb0e4e-eabb-4ca1-9828-eb9b96873035.JPG)

In Power Virtual Agent the Analytics appear ok.

**Comment by Jenefer-Monroe** [comment]
Ok yes thank you for posting. There was a bug in that flow that was fixed in the Feb release (4.3) 
Please see https://github.com/microsoft/coe-starter-kit/issues/4391

**Comment by Jenefer-Monroe** [comment]
I suggest you upgrade to Feb. It was a VERY solid release and you will be out of my test matrix if you wait till the April release. 

Hopefully that helps you with your argument to upgrade :)

**Comment by RowdyAce** [comment]
Thank you. Will recommend upgrade.
