### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION --PBI Dashboard

### ISSUE THREAD

**Issue by EnsilaC** [microsoft/coe-starter-kit#5048]
### What is your question?

Hello, 

Refering to the closed ticket #4918 
In order to get the latest PBI files from the Feb Release do i need to setup the PBI dashboard from beginning? is there a way to just upload the latest files so the update will be automatically? Based on the link provided in the closed ticket it shows how to setup the PBI dashboard, but indeed we already have it, and with the latest update of the COE kit the PBI Dashboard is not being refreshed anymore

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately that is just the way shipping PBIT's works in a solution. 
You need to go through the setup steps again, and then when you publish you can just publish on top of the old one.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
