### ISSUE TITLE
[CoE Starter Kit - BUG] O365 Custom Connector Authentication Bug

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5050]
### Describe the issue

O365 Custom Connector has Generic Oauth2 as the Identify Provider. Identity Provided should be Azure Active Directory. 

This is the original connector as it comes from the core components import. ![image](https://user-images.githubusercontent.com/95443860/226649698-9c021330-0c64-4a9e-9f20-09288ac38ad6.png)

This is the identify provider that it should have to be able to authenticate. 
![image](https://user-images.githubusercontent.com/95443860/226649905-5ab2aa38-a1ed-469d-889e-20bdeec03b23.png)

### Expected Behavior

Custom Connector should be able to establish a connection with the M365 API.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

O365 Custom Connector

### Steps To Reproduce

Test Custom Connector, Start Subscription. Authorization error.

**Comment by manuelap-msft** [comment]
Hello,

the default identity provider for custom connectors has changed here, it used to be Azure Active Directory but is now Generic OAuth. This is not something that we can influence with the connector in the kit, but we're tracking an update to our documentation to include a step to change the identity provider as you update the other security details on this page like client id/secret.

This is tracked here: 
https://github.com/microsoft/coe-starter-kit/issues/4808

If you're experiencing issues after the upgrade with the connection to the Audit Log, here's a write up on how to get out of this state
https://github.com/microsoft/coe-starter-kit/issues/4961

I'll close this issue as a duplicate!

Thank you
Manuela
