### ISSUE TITLE
[CoE Starter Kit - QUESTION] Request Orphaned Objects Reassigned (Parent)

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5051]
### What is your question?

Hi,

How often "Request Orphaned Objects Reassigned (Parent) flow" runs? In flow, it is showing as  weekly .

![image](https://user-images.githubusercontent.com/126264610/226663191-193e69d8-15b7-45db-82bf-3e91d2c80407.png)

But in Documentation it is mentioned as Daily.

![image](https://user-images.githubusercontent.com/126264610/226663665-ce04af47-314a-4bc5-95bb-d7cc4c133d30.png)

 Which one is correct?

### What solution are you experiencing the issue with?

None

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent) flow

**Comment by manuelap-msft** [comment]
Made this change in our local docs branch, ready for the next docs update.

**Comment by lingutla123** [comment]
Thank you.
