### ISSUE TITLE
[CoE Starter Kit - BUG] Preview email does not send a formatted email in the Inactivity processes emails

### ISSUE THREAD

**Issue by ajeyng** [microsoft/coe-starter-kit#5054]
### Describe the issue

1. Login to Admin Command Center
2. Updated the email body under the Customized Emails -->  Edit mail: Create an approval
3. Click on Preview which send out a copy of the email to the Admin SR email address
4. The email received is not HTML formatted 

### Expected Behavior

1. Need to work in sync with some of the other email template edits

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1. Login to Admin Command Center
2. Updated the email body under the Customized Emails -->  Edit mail: Create an approval
3. Click on Preview which send out a copy of the email to the Admin SR email address
4. The email received is not HTML formatted

**Comment by Jenefer-Monroe** [comment]
Hello, that is correct. Approvals are formatted in markdown not HTML. That is just a product limitation that we had to snap to. 

### Approval Mail
![image](https://user-images.githubusercontent.com/89584709/226952592-8794070d-dad8-41b9-80c7-d91ebc7eba73.png)

**Comment by ajeyng** [comment]
Thanks, Sorry, my bad there is a note as well on the top of the text area
![image](https://user-images.githubusercontent.com/107418214/226958668-c1af183e-f916-470f-9a5f-60542c373fc1.png)

**Comment by Jenefer-Monroe** [comment]
No problem at all! Glad to help!
