### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by vsanjiv1** [microsoft/coe-starter-kit#5057]
### What is your question?

Team,

Need help not able to connect the PBIT wiht my environment. I am the admin for my environment. Getting the below error.

OrgUrl
Loading blocked by failures with other queries.
Environment
The key didn't match any rows in the table.
App
The key didn't match any rows in the table.
Maker
The key didn't match any rows in the table.
Flow
The key didn't match any rows in the table.
Connector
The key didn't match any rows in the table.
App Connection Reference
The key didn't match any rows in the table.
Flow Connection Reference
The key didn't match any rows in the table.
Audit Log
The key didn't match any rows in the table.
NonProdWords
Loading blocked by failures with other queries.
Connection Identity
The key didn't match any rows in the table.
Environment Capacity
The key didn't match any rows in the table.
Environment Request
The key didn't match any rows in the table.

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
This typically means that the data in your coe got corrupted somehow. 
Was this a new install?

**Comment by Jenefer-Monroe** [comment]
ok can you please go validate that there is data in the tables? 
You can do this by using the PPAdmin View App in Core. 
![image](https://user-images.githubusercontent.com/89584709/227311456-9afd69a7-f69e-48be-9b91-6628eebb376f.png)

**Comment by vsanjiv1** [comment]
Thanks Jenefer,

I will try that.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
