### ISSUE TITLE
[CoE Starter Kit - BUG] ProductionEnvironment variable not functional for Inactivity Flows

### ISSUE THREAD

**Issue by ajeyng** [microsoft/coe-starter-kit#5058]
### Describe the issue

1. Set ProdEnv variable to no
<img width="970" alt="image" src="https://user-images.githubusercontent.com/107418214/226793188-02263fed-75ef-4d4c-8214-eabafbf628cd.png">
2. Inactivity notifications are sent to the actual user versus the Admin user
3. However it works as expected in the compliance flows which is received by the admin user
4. Although the Evn variable is used in both the Inactivity & Compliance flows

### Expected Behavior

ProdEnv variable needs to route all emails in Inactivity to Admin when the variable is set. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

N/A

### Steps To Reproduce

1. Set ProdEnv variable to no
<img width="970" alt="image" src="https://user-images.githubusercontent.com/107418214/226793188-02263fed-75ef-4d4c-8214-eabafbf628cd.png">
2. Inactivity notifications are sent to the actual user versus the Admin user
3. However it works as expected in the compliance flows which is received by the admin user
4. Although the Evn variable is used in both the Inactivity & Compliance flows

**Comment by Jenefer-Monroe** [comment]
Sometimes there is a delay between setting the env var and it being updated in the flows that use it. If you turn the flows used for Inactivity off and back on it will force the env var to update.

**Comment by ajeyng** [comment]
Thank you very much for your quick response. I did turn off & turn on the flow, but it did not work as expected. I will try it again after couple hours

**Comment by ajeyng** [comment]
![image](https://user-images.githubusercontent.com/107418214/226947839-6c30a001-1dd0-4f4a-9835-9a2ca5da031a.png)

**Comment by Jenefer-Monroe** [comment]
I just double checked these two flows and they do also capture the env var into a variable for use, so thats an easy spot to test. 

If you open the **_Admin | Inactivity notifications v2 (Start Approval for Apps)_** flow (or the one for flows)
Go to the most recent run
Look for this variable set
![image](https://user-images.githubusercontent.com/89584709/226948111-592af767-b744-423d-aa9b-bf5603e5b4de.png)

**Comment by ajeyng** [comment]
That's correct. That is the strange behavior where Env var is picked correctly but the email recipient valie is not set is not looking at the master switch (ProdEnv var). In this case Admin should had received email but looks like end user is receiving it. 
![image](https://user-images.githubusercontent.com/107418214/226949425-882107da-a293-42dc-9c14-e677bd37b9a0.png)

**Comment by Jenefer-Monroe** [comment]
This does work for us so I'm not sure. 
If you open the flow in edit mode do you see this? 
![image](https://user-images.githubusercontent.com/89584709/226951267-17647af1-dcd0-41e4-821d-6bf5a22d2ce0.png)

**Comment by ajeyng** [comment]
This is what I think - Inactivity Emails have the Assignee set to Individual Admin email variable versus Compliance flows that are working as expected have Admin Email picked when the master switch is ON. 
![image](https://user-images.githubusercontent.com/107418214/226955398-6e41d46a-4c9e-4fd2-ac95-eae18afffffb.png)
![image](https://user-images.githubusercontent.com/107418214/226955531-c8def9e5-191b-44e4-bcae-d139446c12c3.png)
![image](https://user-images.githubusercontent.com/107418214/226955803-c5d96493-31a6-4f0f-9733-3ee51461d390.png)

**Comment by Jenefer-Monroe** [comment]
We need both "admin email" and an "individual admin" because some processes (like teams adaptive cards and approvals) will not let us send in a group. So we use this individual admin concept for those 

Individual Admin and Approval Admin are the same env var, just schema name v display name. That happened as we ended up finding out it was for more than just approvals after we started using it. 
![image](https://user-images.githubusercontent.com/89584709/226977732-92917eca-36f5-4560-95be-97bb4842f69d.png)

So in this flow, we "assign" the approvals to the individual admins, but we can send other mails to the admin group as a whole. I hope that makes sense. 

Do you have a value filled for the individual admin?

**Comment by ajeyng** [comment]
Ok, that makes sense. I do have a value int eh individual admin & that is where I received the inactivity notifications. But I could not differentiate between user & individual admin as it was the same user who created & also an admin.

Admin email = M365 Admin Group email
Individual Admin = Service account or any individual account (Mostly the account that may have installed CoE)
**If ProdEnv variable = No** then **Inactivity Notifications are routed to the Individual Admin (due to Approvals)** 
& **Compliance notifications** or for that matter any regular notification **that does not involve approvals will be routed to the  Admin email**.

Thank you very much for the detailed guidance. Appreciate your help!
