### ISSUE TITLE
[CoE Starter Kit - BUG]: GCC High - Center of Excellence Audit Logs/Office 365 Management API

### ISSUE THREAD

**Issue by cdt2021** [microsoft/coe-starter-kit#506]
**Describe the bug**
I'm trying to install the Center of Excellence Audit Logs in our GCCHigh environment using the Office 365 Management API.   When I import the solution and create the connection I get the following error.

AADSTS700016: Application with identifier 'e2c3b58b-7b9f-48ca-aa63-3382827fcaab' was not found in the directory '2d5b202c-8c07-4168-a551-66f570d429b3'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Center of Excellence Audit Logs]
 - Version [1.41]
 - App or Flow [Flow]

**Comment by cdt2021** [comment]
![image](https://user-images.githubusercontent.com/80719563/119591724-c1dd8480-bd9c-11eb-96a5-eeb070096269.png)

**Comment by cdt2021** [comment]
![image](https://user-images.githubusercontent.com/80719563/119591746-cd30b000-bd9c-11eb-823f-5cf062b18e8f.png)

**Comment by cdt2021** [comment]
When I try to fix the connection for the Office 365 Management API I get the error listed in the previous attached screenshots.

![image](https://user-images.githubusercontent.com/80719563/119591918-197bf000-bd9d-11eb-99b3-70738ae9bd62.png)

**Comment by JeneferM-MSFT** [comment]
Hello. We often see this when the application, secret, or tenant id have been pasted incorrectly, or when users don't have access to the audit logs from office. 

Please re-walk the steps in the [setup docuementation](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog) carefully.

Note that there is a chunk of common errors in install shown in the document as well
![image](https://user-images.githubusercontent.com/62659043/119594807-b50b6180-bd99-11eb-8272-9d759fce1def.png)

**Comment by cdt2021** [comment]
Thank you I will work with my Tenant Admin and walk through the steps again.

**Comment by cdt2021** [comment]
I tried again with our enterprise architect and he got the following error.


![image](https://user-images.githubusercontent.com/80719563/119597978-b0e64080-bda7-11eb-9e29-c3d49fd41dd3.png)

**Comment by JeneferM-MSFT** [comment]
Hello. Here is the error message of interest: **_Confidential Client is not supported in Cross Cloud request_**

It seems that you have some settings in your tenant that are blocking you from using Azure secrets. 
I'm afraid we cannot scale to assisting in figuring out those settings or how to get around them, but if you create a support ticket then a product support engineer can walk you through whatever setting you have. 
Please let us know what you find and we can update our documentation for other users.

Thank you

**Comment by cdt2021** [comment]
Thank you.  We'll open a support ticket for this.

**Comment by JeneferM-MSFT** [comment]
Someone just pointed out to me that you likely just didnt update your Resource URL to the required value for GCC High
![image](https://user-images.githubusercontent.com/62659043/119714474-2857b680-be20-11eb-80e3-f69b35a362a9.png)

So it should look like this for you
![image](https://user-images.githubusercontent.com/62659043/119714741-7076d900-be20-11eb-8282-0355f782aa22.png)

**Comment by cdt2021** [comment]
The resource URL is correct.  We found the issue.  The login URL on the security page should be login.microsoft.us and not login.windows.net
![image](https://user-images.githubusercontent.com/80719563/119715408-95bc1500-be29-11eb-8b37-73cc0b3c7f4f.png)

**Comment by JeneferM-MSFT** [comment]
Wonderful thank you for investigating. We will update our documentation to reflect.

**Comment by cdt2021** [comment]
Now the authentication is working as expected.  I'm stuck trying to add the custom connector to the DLP

**Comment by cdt2021** [comment]
any command I try to use results in this error.
![image](https://user-images.githubusercontent.com/80719563/119715860-167b1100-be2a-11eb-81c0-57d70a8697b5.png)

**Comment by cdt2021** [comment]
any idea as to why this is occurring.   I just simply ran the following command:

Add-PowerAppsAccount

**Comment by cdt2021** [comment]
I will not let me display the policies either so I'm really confused.  This is the last step and I'll have the solution in place and running....at least I think I will.

**Comment by JeneferM-MSFT** [comment]
Yes this is a difficult thing today. The product team is investing in making Custom Connectors easier in DLP but in the meantime it is a cumbersome endeavor that requires you use an Environment level DLP and PowerShell. Please see this documentation for assistance.
[Custom Connector into DLP.pdf](https://github.com/microsoft/coe-starter-kit/files/6549080/Custom.Connector.into.DLP.pdf)

**Comment by cdt2021** [comment]
Great!  Thank you.  I'll go through the PDF.

**Comment by cdt2021** [comment]
The first step in the document is giving me trouble..... :-(    .  I'll go back through and see what I could have missed.

![image](https://user-images.githubusercontent.com/80719563/119719570-8db2a400-be2e-11eb-964d-474d05ba4c5e.png)

**Comment by JeneferM-MSFT** [comment]
Couple thoughts. 
1) Did you put the samples in the same folder as PowerShell? My sample assumes that you did 
1) It looks like you have a space between the .\ and Microsoft, and you shouldn't. 

Hope that helps.

**Comment by cdt2021** [comment]
Looks like the extra space was the issue.  However, I decided to close PowerShell and open it back up as an Admin and I'm still having an issue with none of the commands working.  See attached screenshot.  I wanted t add my account or run any other command.  It prompts me for my user name and password and then throws the error you see below.

![image](https://user-images.githubusercontent.com/80719563/119724665-a02fdc00-be34-11eb-86a6-c6dc58ba6258.png)

**Comment by JeneferM-MSFT** [comment]
I'm not familiar with that command. I know when I run any calls that go to the PP I get prompted to add credentials through some login UX. Perhaps just proceed without trying to do the Add-PowerAppsAccount command

**Comment by cdt2021** [comment]
I've numerous commands and they all come back with the same error so I'm completely confused.... :-(

**Comment by JeneferM-MSFT** [comment]
I'm afraid I can't assist with that. The product team will have the new feature to get Custom Connectors in DLP soon, so you may have to wait.

**Comment by cdt2021** [comment]
Great!  Thank you.  I'll give it a try now.

**Comment by cdt2021** [comment]
Thanks for the help.  I was able to get the custom connector added to the DLP.
