### ISSUE TITLE
[CoE Starter Kit - BUG] Core Components - Admin | Sync Template v3 is not capturing all environments.

### ISSUE THREAD

**Issue by Srise96** [microsoft/coe-starter-kit#5060]
### Describe the issue

Center of Excellence - Core Components - Admin | Sync Template v3 is not capturing all the existing environments in our organization and due to this we are not able to extract the full list of Cloud, Flows, Desktop Flows, PowerApps, Solutions etc. This a high priority issue for us as we need the full list of environments and other components for reporting purposes.

### Expected Behavior

All the existing environments should be updated in CoE environment, but it is not completed when we cross check in admin power platform.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.81

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
Hello. The most typical reason for this is that the identity running the flows does not have the correct licenses and roles assigned permanently. [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

In particular, please validate the user has the Power Platform Admin Role permanently assigned. 
![image](https://user-images.githubusercontent.com/89584709/226924688-ea65a5cc-c5ce-4bf7-9172-38a34347a6bf.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
