### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View - Flows

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#5061]
### Describe the issue

Hello,

We have a problem that in the flows table in the power platform admin view application, for some flows that have a suspended or stopped status, the flow suspension reason is missing.

![image](https://user-images.githubusercontent.com/54030753/226862440-e3580dfc-f854-4983-a833-7ae9fdafd515.png)

Regards

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Power Platform Admin View - Flows

**Comment by Jenefer-Monroe** [comment]
This is filled by the **_Admin | Sync Template v3 (Flows)_** flow

### Lets find the correct run
Browse to http://flow.microsoft.com/ > Coe Envt > Solutions > Your CoE Envt > Core Solution > Flows > Find this flow > Click its name to get to details
![image](https://user-images.githubusercontent.com/89584709/227058314-152f7f06-c05e-4156-81f1-dacfb11d22ec.png)

Edit columns > Add admin_environmentname > Save
![image](https://user-images.githubusercontent.com/89584709/227058387-245c5140-7ae2-4491-a74e-075edd0242d7.png)
![image](https://user-images.githubusercontent.com/89584709/227058463-8008b77a-ce70-49c0-b80f-af3cffc4112e.png)

Click all runs > and find your default envt by searching for default, you may need to click show more at the bottom of the list a few times. Click the timestamp to open the run
![image](https://user-images.githubusercontent.com/89584709/227058578-c2215ea4-b163-48ca-92d4-3565919897b5.png)
![image](https://user-images.githubusercontent.com/89584709/227058895-7b88ba61-ef61-414f-a320-5a06caa138ef.png)

### Find the part of the run that fills this
You'll find this section called Flow State. Look out the output of List flows turned on. Find one of your repros for type suspended in your picture to get the index in the return (rememer that it may start count at 0 or 1 depending on the tool you are using)
Find it in the apply to each 
![image](https://user-images.githubusercontent.com/89584709/227059500-338b90f5-02a8-4bc8-bc57-b408461c3da6.png)

Let me know what you see

**Comment by BartoszKaminski1999** [comment]
I found that all flows that has empty column flow suspension reason has flowsuspensionreason in flow: "None".

![image](https://user-images.githubusercontent.com/54030753/227135824-18d3fa70-7c30-4a40-bae9-99a02a9ab1cb.png)

![image](https://user-images.githubusercontent.com/54030753/227135713-e5be7ae9-ace5-4b97-bf32-0d8ae68a3d70.png)

So I have two questions:

What does reason none mean if flow is stopped?

Why not all flows in power platform admin view have the status none, if in flow I see that this information exists?

**Comment by Jenefer-Monroe** [comment]
It turns out we don't update that field if the flow is stopped
![image](https://user-images.githubusercontent.com/89584709/227309174-93217a53-cbef-415b-a3f1-002d886c6dc7.png)

I don't know why we did that but I presume it would have to do with limiting the API calls.
Let me think on it a little.

**Comment by Jenefer-Monroe** [comment]
hello. yes it turns out we did this for API calls, and there are some product changes coming that will mean investing here would not be useful, so we wont be changing this behavior.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
