### ISSUE TITLE
Update the CoE Starter Kit into the latest version

### ISSUE THREAD

**Issue by PongeerthanaM** [microsoft/coe-starter-kit#5064]
### Describe the issue

We already installed the coe starter kit into our environment 1 year ago. Now, we need to update the kit into the latest version. When we have tired to follow the microsoft documents to update the coe, we facing issue. We can't able to install the updated coe kit into our testing environment.

### Expected Behavior

The current coe version need to updated into the latest version (Feb 2023) in both test and live environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

-

**Comment by Jenefer-Monroe** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades). That is how far back we test as well. 

If all you are using us for is inventory, then we recommend you start from a clean environment. 

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out errored references listed for example, if they are familiar enough with Power Platform. 

Others have overcome it with a classic overwrite upgrade, ill paste how to do those below. 

Sorry we cannot be of more assistance here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
