### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYOD PBI Dataflow - data missing

### ISSUE THREAD

**Issue by ValentinMaz** [microsoft/coe-starter-kit#5066]
### What is your question?

- When we used the PBI dataflow from the Phase 1 of the private preview, the data seemed correct
- When using the PBI dataflow from the Phase 2, we miss a lot of data
- To compare we just created a Power BI report connecting to both dataflows, here is what we found:
Apps: more than 2 x less Apps with Phase 2
Flows: around 3 x less Flows with Phase 2
AppsUsage: same count with both Phases
Environments: same count with both Phases
 
Looking at the two Dataflow Flows queries, here is what I found:
- it seems like at least part of the error could come from a missing step in the Phase 2 Apps and Flows queries. During the "Merged with environments" steps, the default environment is not matched because it has a lowercase "d" from the Environments queries. By adding a text transform step before the merge to lowercase the Environment Name columns it then properly matches the default environment
- in the Apps query I also found other discrepancies: the "Extract environment ID from file Name" step in Phase 2 different from the "addEnvName" step in phase 1. I replaced the step in Phase 2 by the one from Phase 1, and added the two "Replace value" step to replace "model" and "canvas" in the environmentName columns. Once done I have almost the same App counts for both queries

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

### What app or flow are you having the issue with?

PBI Dataflow

**Comment by Jenefer-Monroe** [comment]
Thank you for posting! I believe this is covered by https://github.com/microsoft/coe-starter-kit/issues/5052. Can you take a quick peek and see if you agree?

**Comment by ValentinMaz** [comment]
Hello Janefer, I had not seen #5052 apologies. Yes it seems similar, though what I experienced was not the "default" prefix missing... It was that the "default" had a higher case "D" in the Apps and Flows queries but a lowered case "d" in the Environment query. I assumed it was missing a lowercase step in the Apps and Flows queries prior to the Merge step.
Not sure whether it is the exact same thing?

**Comment by Jenefer-Monroe** [comment]
No problem at all! Thanks for comparing. I'll send this off to the dev to make sure the fix will work for your case too :)

**Comment by manuelap-msft** [comment]
Hello,

yes, we had an issue both with lowercase (for Flows) as well as with accidentally filtering out the Default- (for Apps) so the merge with the Environments table didn't work for the Default- environment. 

Can you try downloading this updated Dataflow and see if this update works? In my tenant I now see Apps/Flows for Default so hopefully that fixed the issue (After configuring the dataflow, you have to refresh the dataflow and then refresh the Power BI dashboard to see the new data):
https://github.com/microsoft/coe-starter-kit/blob/coe-powerbidataflow/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/PowerPlatformAdminAnalytics-DF.json

Thank you
Manuela
