### ISSUE TITLE
[CoE Starter Kit - Feature]: Show flows to reset after to change an env variable

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#5072]
### Is your feature request related to a problem? Please describe.

In November version at least when we need to change the value of env var FullInventory we could to reset directly the flows affected, something very helpful:
![image](https://user-images.githubusercontent.com/57954993/227185463-2ef2e254-88e8-4357-93fe-b09634f54588.png)

Now in February version we lost this possibility:
![image](https://user-images.githubusercontent.com/57954993/227185069-e9d818f7-66ec-47a5-8b7d-ed8c81326689.png)

### Describe the solution you'd like

It will interesting have again a way directly to identify the flows affected to a env var to reset them more easy.

Thanks!

**Comment by manuelap-msft** [comment]
Hello,

flows no longer cache environment variables, and no longer have to be turned off/back on to get the new value - see: https://learn.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-automate/push-environment-variable-updates-into-flows-asynchronously

We therefore removed this feature, as it's no longer required: https://github.com/microsoft/coe-starter-kit/issues/4452

Hope this helps,
Manuela

**Comment by albertocastro365** [comment]
OMG Manuela! I missed this information! Thank you so much!

**Comment by manuelap-msft** [comment]
No worries, we missed it too at first! I think it snuck in really quietly ;)
