### ISSUE TITLE
[CoE Starter Kit - BUG] Data Export Greyed Out on Setup Wizard

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#5087]
### Describe the issue

I have managed to get through to the 'configure inventory data source' step in the CoE Setup Wizard, although the 'Data Export' option is greyed out. 

<img width="966" alt="CoEDataExportMissing" src="https://user-images.githubusercontent.com/117096415/227526106-b5cd7b82-4fd5-48e4-a884-1b5133729383.PNG">

I have read through the documentation and looked through your issue log and I can't see any reference to this. The Data Export has been configured, it has data in it as I was able to see it through Microsoft Azure Storage Explorer and connect to it through Power BI. The account I am using to run the CoE Wizard has access to the data, as that is the account used to check the content was there and to connect through Power BI.
<img width="402" alt="DataFlow" src="https://user-images.githubusercontent.com/117096415/227526870-5ae62ade-19ab-41c0-8e50-be3e538a5fea.PNG">

Any ideas?

### Expected Behavior

Should be able to select 'Data Export' when configuring the inventory data source. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

CoE Setup Wizard (Preview)

### Steps To Reproduce

1. Run CoE Setup Preview
2. Confirm pre-requisites - the only status that is not a success is hte MS Power Platform Service admin, global tenant admin requirement, this is showing as verify manually (this appears to be expected behaviour as the Microsoft Learn Content shows the same warning
3. Configure communication methods
4. Configure inventory data source - this is where I have the problem 
<img width="966" alt="CoEDataExportMissing" src="https://user-images.githubusercontent.com/117096415/227528065-dc752eb9-74fc-4ec9-89da-9df2aa807a41.PNG">

**Comment by Jenefer-Monroe** [comment]
Hello, yes we released the Data Export in public preview only. So the v4.3 that you have installed is the Feb release, from before the preview. 

You can get the preview bits at https://aka.ms/coebyodldownload
We will (almost certainly) be going live with the work in the upcoming April release and it will be a single download from then on.

**Comment by G1982C** [comment]
Thanks Jenefer. Can I just delete the solution and reimport the preview corecomponent solution and start again?

**Comment by Jenefer-Monroe** [comment]
Was this in a test envt just created for this work? If so then yes that should be fine. 
We have also tested upgrade form 4.3 to 4.3.50 and it works and would get you back to that screen with it enabled.

**Comment by G1982C** [comment]
Correct. I was discussing with Manuela who was very helpful and suggested a test environment. I built that out this morning and installing the CoE with data export to test it out. 

Thanks. I will do an upgrade of the existing solution rather than removing and reimporting.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
