### ISSUE TITLE
[ALM Accelerator - BUG]: Error in Flatten JSON files if flow name contains brackets

### ISSUE THREAD

**Issue by sefa-phaag** [microsoft/coe-starter-kit#5088]
### Describe the issue

When the Flatten JSON files build pipeline step runs, if a flow name contains brackets (e.g., [ ]), the build process fails with an error like:

```
An object at the specified path D:\a\1\s\Print Labels\PrintLabels\SolutionPackage\src\CanvasApps\src\sefa_printlabels_8eb29\DataSources\PrintInventoryLabels[Child].json does not exist, or has been filtered by the -Include or -Exclude parameter.
```

The issue is the same as described [here](https://github.com/PowerShell/PowerShell/issues/16063) (the brackets are being interpreted as wildcard characters in PowerShell) and the fix should be the same, I think: specify -LiteralPath within the command.

The following change in build-deploy-solution-functions.ps1 seems to have fixed it in my environment:

<pre>
function flatten-JSON-files
{
    param (
        [Parameter(Mandatory)] [String]$solutionFolderPath
    )

    Get-ChildItem -Path "$solutionFolderPath" -Recurse -Filter *.json |
    ForEach-Object {
        $fileContent = (Get-Content <b><i>-LiteralPath</i></b> $_.FullName) -join ' '
        if(-not [string]::IsNullOrWhiteSpace($fileContent)) {
            Set-Content <b><i>-LiteralPath</i></b> $_.FullName $fileContent -Encoding utf8NoBOM
        }
    }
}
</pre>

### Expected Behavior

The build should complete without error.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

March 2023

### Steps To Reproduce

1. Create a flow with brackets in the name (e.g., my[flow]).
2. Commit the solution to source control.
3. Attempt to deploy the solution.

**Comment by sefa-phaag** [comment]
I'll create a pull request to fix this.

**Comment by mikefactorial** [comment]
Thanks @sefa-phaag for the PR. We've merged the change. Closing this out.
