### ISSUE TITLE
[CoE Starter Kit - QUESTION] After fix #4558 Maker Table not updating

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#5089]
### What is your question?

Since the changes to fix the upn/email went in,   I set a full inventory and now afterwards, the emails column population is sporadic,  there are users in that table who are still active and have flows but the user email column is blank and they do have an email address.

Looking through the flow runs there are so many maker checks I cant locate any that do not hit the shortcut at the top, the maker always seems to have been updated, even flows with long runs like 10 seconds +  all shortcuts,   I go back through time to when no one is in the office and the flow runs should be updating and cant find any either.

But when I do a full inventory after this fix, I would expect that user Email in maker to be populated for everyone by now as its been a good while to run thru the inventory.   Of 877 users 600+ are not updated.

The param for check maker is also set to not force check,   not sure under what circumstances that would be set to force check.

Was there a new flow to run to force fix this data at all I missed ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feb 2022

### What app or flow are you having the issue with?

Helper - Maker Check

**Comment by binaryjam** [comment]
Hi,

I needed my users updating so I was about to write a flow that called Maker Check forced for my blanks.

I found that the Get User Profile (v2)  Action   is using the flow param MakerID, 

![image](https://user-images.githubusercontent.com/7352864/227547278-6cd89ddc-0e90-4cf0-b1e4-897d586971b8.png)

If should use the UPN from the first( 'See if maker exists and updated already today' ) above it.

**Comment by binaryjam** [comment]
That hasnt ran since the install as its on a weekly  and didint know to run it.   I kicked it off and can already see it fixing things up.
Ive added this to the install guide for my team to specifically run this cos the Makers table  was corrupt.

Thanks.

**Comment by Jenefer-Monroe** [comment]
Thanks for letting me know!
We have also started running this from the setup wizard when you get to the last screen, as it was needed for the BYODL case.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
