### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3( Connection Identities) Failed

### ISSUE THREAD

**Issue by akhilmit08** [microsoft/coe-starter-kit#5092]
### Describe the issue

Core Component "Admin | Sync Template v3( Connection Identities) Failed)" failing with error:
The action 'Get_Connections_as_Admin' has an aggregated page count of more than '1000'. This exceed the maximum page count '1000' allowed.

### Expected Behavior

Flow should to be successfully run and data to be generated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3( Connection Identities)

### Steps To Reproduce

Error :
The action 'Get_Connections_as_Admin' has an aggregated page count of more than '1000'. This exceed the maximum page count '1000' allowed.
Flow failed with custom environment and get notification from flow Admin| Sync Flows Errors.

### Anything else?

Nothing

**Comment by Jenefer-Monroe** [comment]
Hello, can you please share a screenshot? (You need to log in to GitHub to share images, you cannot reply in email).

**Comment by akhilmit08** [comment]
![COEIssue1](https://user-images.githubusercontent.com/37968876/227573078-4b72c62f-3554-4151-b990-8449e1701ca7.png)

**Comment by Jenefer-Monroe** [comment]
Ok yes this is unfortunately a product limitation. 
The CoE kit is built on top of the product, and as such bound to platform limitations. 
It appears that your tenant is too large for this flow for that environment. If you reach out to product support they may be able to help you clean up old and bad connections and get to a size that will work.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
