### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION- YoY percentage blank on Power BI Dashboard and some more

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5094]
### What is your question?

Hi 

1. Not sure if we are calculating this or not , could see that YoY Maker percentage is blank, however all cards have there percentages in it. And there are loads of makers. Could you please suggest in this scenario why I am not able to see the Maker Percentage.
<img width="928" alt="image" src="https://user-images.githubusercontent.com/112712553/227596168-084e15e0-e0b8-416d-9b33-ec5d20d3887a.png">

2. Whenever the different Apps from CoE are open like Maker - Environment Request and CoE Maker command center, by default see some errors. Can these errors be suppressed, not pleasing to the eyes the moment app is opened

<img width="455" alt="image" src="https://user-images.githubusercontent.com/112712553/227598441-831abbec-d31e-4831-94a0-7b44ccbfd453.png">

<img width="899" alt="image" src="https://user-images.githubusercontent.com/112712553/227598556-25124f9e-111e-4065-b8cb-eb5828edc531.png">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2023

**Comment by Jenefer-Monroe** [comment]
Helllo. Its difficult to manage multiple issues in one GitHub issue so please post a separate one for your app issue.

**Comment by Jenefer-Monroe** [comment]
For the YoY. Perhaps this is due to the CoE being installed this year. We dont have a concept of "Maker first created something" so the visual is just based on when the record was created. 
Does the chart for Maker show anything from last year?

**Comment by PPMini** [comment]
Hi Jenefer, 

Sure, I will make sure to log the issues separately now onwards. You mean, it will start recording from when CoE get installed, that's why we can not see the previous year records. No, chart doesn't show anything 
<img width="304" alt="image" src="https://user-images.githubusercontent.com/112712553/229357811-880cd84d-0c23-4a2e-97e7-64bfd8d93784.png">

**Comment by Jenefer-Monroe** [comment]
OK yes. Our concept of when the Maker was "created" is just when they were inventoried. So these charts are only useful after the CoE has existed for a while.

**Comment by PPMini** [comment]
Thanks Jenefer for clarification. Closing this out

**Comment by Jenefer-Monroe** [comment]
You are welcome, sorry we didnt have a better answer for you!
