### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Automate license

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#5098]
### What is your question?

I was using ver 3.53. Since it has been over 3 months since the previous version, we attempted to update. While checking the license, I was aware that the PowerAutomate license was not previously required, but was it added this time?
If so, what was it needed for and why was it added?
Thank you in advance.

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with
![image](https://user-images.githubusercontent.com/91306350/227828511-07909243-52de-4205-8cb5-058de58fc10c.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

**Comment by manuelap-msft** [comment]
This is not a new requirement, a Power Automate license has always been required to run the CoE kit. 

The CoE kit contains flows that run in context of Power Apps (for which a Power Apps license is sufficient), but most of the flows run standalone outside of the context of Power Apps thus a standalone license is required. Some of this may not be enforced in the product, e.g. you will be able to turn on a standalone flow if you only have a Power Apps license but it doesn't follow our license guidance, see here the Power Apps use rights only include execution of cloud flows within the app context
![image](https://user-images.githubusercontent.com/55705669/226404865-802a1abf-648e-4154-8b89-660153c61804.png)

Before the setup wizard, you likely just turned on the flows with your Power Apps license as the above guidance is not enforced today.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
