### ISSUE TITLE
[CoE Starter Kit - BUG] Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. 

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/coe-starter-kit#5099]
### Describe the issue

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 16 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365GroupsCoEConnection, Id: dff2e433-8290-45dd-8600-369f74b92b52, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Welcome Email, Id: 18c1f53d-8d87-e911-a860-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Welcome Email, Id: 18c1f53d-8d87-e911-a860-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Reminder 3 days prior event, Id: bc9a9f1a-afe6-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Newsletter with Product Updates, Id: e7a96786-c7e5-e911-a860-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Feedback Reminder, Id: 2c42d11c-afe6-e911-a860-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Registration Confirmation, Id: bdd94919-afe6-e911-a85c-000d3a372ab9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Check Approvals, Id: c7982cc4-3024-eb11-a813-000d3a8c389b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: 0bc8c8f1-1b9c-4949-9a5b-6419d657f363, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: e637dd14-f8ba-4788-88ae-7de354023898, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoEConnection, Id: acf087ad-3e8c-4dbc-9603-c8fa6164e5a4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: cd430ab8-e1fe-4286-bc1c-ec1ec0df097e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: cd430ab8-e1fe-4286-bc1c-ec1ec0df097e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: cd430ab8-e1fe-4286-bc1c-ec1ec0df097e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

### Expected Behavior

Unable to install Core Component solution, getting the above error.  Can you please help me resolve this issue on priority 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.39

### What app or flow are you having the issue with?

Admin | Compliance detail request

### Steps To Reproduce

1. Import solution
2. Select core component solution 
3. Click on Upgrade

**Comment by manuelap-msft** [comment]
It sounds like you've developed extensions or customizations to the CoE kit components that now depend on connection references in the Core components solution. For example, one dependency that's mentioned in the error message is **Admin | Flow Archive and Clean Up - Start Approval** which is not a flow that ships with the CoE kit so must be one that you've developed yourself. All the dependency errors point towards connection references that may have been created by editing the flows and creating unmanaged layers.

You'll have to go through all of the 16 dependencies (looks like they're all flows) and clean up the connection references so they point to new ones. Alternatively, if you don't want to keep these flows or the unmanaged layers, you can try removing the unmanaged layers.

I'm afraid we cannot assist with upgrade problems of this complexity as there are just too many specifics and unknowns of how you got into this state. 

Some people have cleaned themselves from this state by manually cleaning out errored references listed for example, if they are familiar enough with Power Platform.

Others have overcome it with a classic overwrite upgrade, ill paste how to do those below - see https://github.com/microsoft/coe-starter-kit/issues/5064#issuecomment-1479582662

**Comment by ApoorvaKantale** [comment]
Hi,

We don't have any customization. and Before i start the upgrade I have removed all unmanaged layers

**Comment by ApoorvaKantale** [comment]
Hi,

Similar error i have received when I have upgraded Governance

Solution "Center of Excellence - Governance Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 6 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSGovernConnection, Id: 33610b46-6bfa-4b1f-b877-0405c8aefdd9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSGovernConnection, Id: 33610b46-6bfa-4b1f-b877-0405c8aefdd9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSGovernConnection, Id: 33610b46-6bfa-4b1f-b877-0405c8aefdd9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSGovernConnection, Id: 33610b46-6bfa-4b1f-b877-0405c8aefdd9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Check Approvals, Id: c7982cc4-3024-eb11-a813-000d3a8c389b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_ApprovalsCoEGovernConnection, Id: e6c409a9-279e-4942-b9c7-1bcc76dcb665, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_ApprovalsCoEGovernConnection, Id: e6c409a9-279e-4942-b9c7-1bcc76dcb665, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | App Archive and Clean Up - Start Approval, Id: 10610458-cbee-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

**Comment by ApoorvaKantale** [comment]
Can you please suggest me the best possible way to resolve them

**Comment by manuelap-msft** [comment]
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. From your dependency issues, some reference objects that are not part of the CoE kit (e.g. admin_ApprovalsCoEGovernConnection and Admin | Flow Archive and Clean Up - Start Approval are not objects we ship as part of the CoE kit, so they are your own objects) and we cannot assist with a state you got into due to your own extensions and customizations. 

You may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out errored references listed for example, if they are familiar enough with Power Platform. 

Others have overcome it with a [classic overwrite upgrade](https://github.com/microsoft/coe-starter-kit/issues/5064#issuecomment-1479582662), ill paste how to do those below. 

Sorry we cannot be of more assistance here.

**Comment by ApoorvaKantale** [comment]
Hi,

But in history it say successful , all components are successfully deployed

![image](https://user-images.githubusercontent.com/78148795/228017470-efabbce5-8f3a-4e41-bbb5-3d1708ee3c1d.png)

**Comment by ApoorvaKantale** [comment]
![image](https://user-images.githubusercontent.com/78148795/228023255-5cb84dbf-aaf0-4727-b1a1-d24ca2c999d0.png)


![image](https://user-images.githubusercontent.com/78148795/228023312-036ed5aa-ecc9-4dc7-95de-9d5a52a730c1.png)

**Comment by Jenefer-Monroe** [comment]
There are more solutions than that, please share the entire list like I have shown.

**Comment by ApoorvaKantale** [comment]
![image](https://user-images.githubusercontent.com/78148795/228132319-92cbe24c-46b8-4afc-bfe9-31bab8b73b83.png)

![image](https://user-images.githubusercontent.com/78148795/228132403-f13e3958-0a72-47f9-bf46-0dcd2a425184.png)

![image](https://user-images.githubusercontent.com/78148795/228132502-e493eed0-4e49-4495-b506-d3ea3fb0ab86.png)

![image](https://user-images.githubusercontent.com/78148795/228132540-1cb4a482-87c2-4633-9189-9583c266ff29.png)

**Comment by ApoorvaKantale** [comment]
I can see the Admin | Flow Archive and Clean Up - Start Approval in the Default Solution, But to remove it from environment , the button is disabled, Can you let m know How can I remove/delete it. The Button is Greyed out

![image](https://user-images.githubusercontent.com/78148795/228134421-6dcd9ef8-869e-4cbe-bc66-7ce817c6331e.png)

Same with the Connection Reference as well, even to delete the connection reference the button is greyed out

**Comment by ApoorvaKantale** [comment]
If I have to delete also in which order Should I need to delete

**Comment by Jenefer-Monroe** [comment]
You can try that. you can also see if there is an "apply" option in its menu. 
For order I'm really not sure as I dont know what state your dependencies are in.

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are unable to assist here. You have hit up against some product issues with managed solutions and ALM. You may be able to find some resources online for how to remove these in an unsupported manner but I cannot advice in that direction. 

You may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Or start from a clean envt. Sorry we cannot be of more assistance here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
