### ISSUE TITLE
Error on the "Admin | Sync Template v2 (Model Driven Apps)" flow

### ISSUE THREAD

**Issue by HenryJammes** [microsoft/coe-starter-kit#51]
The "**Admin | Sync Template v2 (Model Driven Apps)**" flow step "**Upsert Model Driven App (created by SYSTEM)**" fails with the error: "A record with matching key values already exists."

My assumption is that the "Update a record" action actually doesn't support upsert - to do this you would probably need to use the Web API directly: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/update-delete-entities-using-web-api#upsert-an-entity

**Comment by devkeydet** [comment]
Sorry, this is a bit of a repo in transition, which has confused people.  We hit some snags in being able to move to using this repo, but didn't want to make it private.  If you haven't already, please file the issue here: https://github.com/microsoft/powerapps-tools/issues.
