### ISSUE TITLE
[CoE Starter Kit - BUG] admin_customizedemail With Id = f1251799-2a86-ed11-81ac-0022480813ff Does Not Exist

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/coe-starter-kit#5100]
### Describe the issue

Hi,

The [Child] Admin | Sync Logs flow is  failing with the following error 

"admin_customizedemail With Id = f1251799-2a86-ed11-81ac-0022480813ff Does Not Exist"

I have also checked in Customized Email table, unable to find the entry with Id = f1251799-2a86-ed11-81ac-0022480813ff

### Expected Behavior

Id = f1251799-2a86-ed11-81ac-0022480813ff this template should be added in customized Email Table so the [Child] Admin | Sync Logs flow runs successful

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by manuelap-msft** [comment]
Hello,

if you've recently upgraded the solution, you may have to run the **Admin | Sync Template v3 Configure Emails** again to configure all the new emails.

Could you try that and let us know if that works?

Manuela

**Comment by Jenefer-Monroe** [comment]
And note that if you run it manually you will need to set this ConfigureAll parameter to yes
![image](https://user-images.githubusercontent.com/89584709/227951748-6412bb1f-5eb4-491a-931c-fea08387f7e6.png)

**Comment by ApoorvaKantale** [comment]
Hi,

Thank you that helped to resolve the issue.

But I'm getting other error now 

"Could not execute workflow 'ca6a4e48-584e-52be-5854-97244d042514' trigger 'manual' with state 'Disabled': trigger is not enabled."

**Comment by ApoorvaKantale** [comment]
I have tried , it didn't work

**Comment by Jenefer-Monroe** [comment]
Sorry are you saying that you cannot turn on this flow? Or you cannot run it? Admin | Sync Template v3 Configure Emails
Or some other flow entirely

**Comment by ApoorvaKantale** [comment]
Admin | Sync Template v3 Configure Emails has run successful

**Comment by Jenefer-Monroe** [comment]
so what issue are you facing now? when do you see that error?

**Comment by Jenefer-Monroe** [comment]
From your other bug, it sounds like your envt is in a bad state. I suggest you start over in a clean envt

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
