### ISSUE TITLE
[CoE Starter Kit - Power Automate desktop] -- How to find Last run date for Power Automate desktop flow

### ISSUE THREAD

**Issue by RambabuDasari412** [microsoft/coe-starter-kit#5101]
### What is your question?

Hi Team,
Could you please guide me, how to find Last run date for Power Automate desktop flow. Please give me the Dataverse table if we are already capturing last run date for Power automate desktop flows in COE.
Thanks,
Rambabu

### What solution are you experiencing the issue with?

Governance

**Comment by manuelap-msft** [comment]
Hello, the **Admin | Sync Template v3 (Desktop Flow - Runs)** flow captures this data in the **RPA Session** table. Note, data is only available from the moment you've installed the kit and turned on this flow - historic data is not captured here.

**Comment by RambabuDasari412** [comment]
Hi Manuela
Thanks for your response.
Kindly provide If there is any column name/ metadata for storing last run date for power automate desktop flow.

If flow runs successfully then instance will be created in RPA sessions table, please clarify what if power automate cloud flow runs failed. failed instance will be also created in RPA sessions table.
Thanks,
Rambabu

**Comment by RambabuDasari412** [comment]
Hi Manuela
Thanks for your response.
Kindly provide If there is any column name/ metadata for storing last run date for power automate desktop flow.

If flow runs successfully then instance will be created in RPA sessions table, please clarify what if power automate cloud flow runs failed. failed instance will be also created in RPA sessions table.
Thanks,
Rambabu

**Comment by manuelap-msft** [comment]
If you look at the RPA Sessions table columns you'll find the information stored - Completed On is the date column you're looking for for when the desktop flow last ran. 
![image](https://user-images.githubusercontent.com/55705669/227942088-b714fca9-794c-4131-9f7b-cb7ec4fb077d.png)

Cloud flow runs are not available in a Dataverse table, they're only available via the [Data Export] feature which writes data to an Azure storage account. We currently have an [experimental preview](https://github.com/microsoft/coe-starter-kit/issues/4977) of the CoE kit integrating with Data Export available to try out, but in this integration we're only using cloud flow runs for reporting and aren't writing them back to Dataverse as that would be a large volume of data. However, you can look at this solution and explore if you want to build a customization on top of that to consume the data. If you're primarily interested in Desktop flow data, I'd also recommend checking out the [Automation kit](http://aka.ms/automationcoe) which specifically looks to solve hyper automation administration scenarios and may be a better fit for your requirements.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
