### ISSUE TITLE
Threshold Points for archiving actions

### ISSUE THREAD

**Issue by Annanas-12** [microsoft/coe-starter-kit#5103]
### Describe the issue

Dear team, 
we are using the CoE Starter Kit and are using the clean up flows (2. generation). We are wondering at what archiving score the flows will become active. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

Clean Up helper

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
