### ISSUE TITLE
[CoE Starter Kit - QUESTION] SharePointForm Orphaned Resources Cleanup 

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#5105]
### What is your question?

Hi team,

We are trying to cleanup SharePointForm Orphaned App. However, Set App Permission only assigns ownership to Canvas and Model-Driven App. Any advice on cleaning up SharePointForm orphaned apps or flows using CoE? Please advise. 

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
Unfortunately permissions for SP Forms Apps do not use the Power Platform permissioning model, they use the SP permissioning model, so we cannot automate them the same way. I'm afraid you'll need to go and manually assign them to another owner.

**Comment by MrHueb** [comment]
Hi @Jenefer-Monroe , I guess the Owner of a SP Form App is not really relevant from a permission model. However, Admins maybe want to change the Owner in the Admin View MD App for SP Form Apps once a previous owner leaves the company. 
Logik: For app where the maker is not available (deleted), unblock the field or send a notification etc. Does that make sense?
