### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Sync Template V3 | Connection Identities - throttling error

### ISSUE THREAD

**Issue by DHRUVSHAH1803** [microsoft/coe-starter-kit#5107]
### Describe the issue

Getting a mail to Admin with Following Subject Line "Alert! Your flow is running too many actions and will be turned off[External Sender]" and the flow is Turning off in 7 days automatically

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin Sync Template V3 | Connection Identities- flow

**Comment by DHRUVSHAH1803** [comment]
Hi Jenefer,
We are having "Power Automate Per User" Plan (non-trial) , then what is the need for per-flow licenses???. It is clearly mentioned in pre-requisites that we need either Power Automate Per User license, or Per Flow licenses (non-trial).(https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
