### ISSUE TITLE
[CoE Starter Kit - BUG] Updating CoE Starter Kit

### ISSUE THREAD

**Issue by PrasannaKumarPenumarthi** [microsoft/coe-starter-kit#5114]
### Describe the issue

While updating CoE Starter Kit to latest version from previous version, If I had done any changes like:
1.Change the setting for Exempting Environments from Inactivity ,Compliance, Quarantine, Teams CleanUp(https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#exempt-environments-from-the-inactivity-notifications-process) in Power Platform Admin View app and
2.Adding some customized Email content part and adding logo etc in CoE Admin Command Center app
Should i revert back those changes that i had made manually to receive updates to the above mentioned apps?, or can i proceed for update to latest CoE starter kit without reverting back the changes that i had made in those apps?
and the third question is should i "turn off" all the flows in Core component, Governance component, Nurture Component, etc before updating CoE Starter kit.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

CoE Kit Update

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
