### ISSUE TITLE
[CoE Starter Kit - QUESTION] When Latest COE March release available?

### ISSUE THREAD

**Issue by Gokul-JB** [microsoft/coe-starter-kit#5115]
### What is your question?

May I know when Latest COE March release available? I want to upgrade complete CoE packages (CoE Core, Governance, and etc. )except ALM in my client environment.
If March release is not available then can we user Feb release ?

Please provide the source code path and steps to upgrade CoE and also How long days it will take if I didn't do any changes/ customize from existing CoE component

**Note**: We have installed complete CoE packages on Oct 2022

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Sep 2022

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
