### ISSUE TITLE
[ALM Accelerator - BUG]: "Add project references to cdsproject" pipeline step fails if path contains spaces

### ISSUE THREAD

**Issue by sefa-phaag** [microsoft/coe-starter-kit#5118]
### Describe the issue

If the top-level repo has a space in its name, then when the pipeline is trying to add PCF controls, you get an error like:

t a valid command. Try running 'pac [command] help'.

Full surrounding log:
```
cdsProjPath - D:\a\1\s\Expense Approval\ExpenseApproval\SolutionPackage\ExpenseApproval.cdsproj
Cds Proj File Found!!!
Adding .pcf project references to cdsproj
Adding Reference of Pcf Project -  D:\a\1\s\Expense Approval\ExpenseApproval\PCF\ExpenseApprovalButtons\ExpenseApprovalButtons.pcfproj
Add Reference Command - solution add-reference --path D:\a\1\s\Expense Approval\ExpenseApproval\PCF\ExpenseApprovalButtons\ExpenseApprovalButtons.pcfproj
Microsoft PowerPlatform CLI
Version: 1.21.5+ge089c16

t a valid command. Try running 'pac [command] help'.
```

When passing the path to solution add-reference, it isn't escaped and is failing.

Changing code-first-functions.ps1 fixes it:
```PowerShell
Write-Host "Adding .pcf project references to cdsproj"
# Get all pcfproject files under Repo/Commited Solution folder
$pcfProjectFiles = Get-ChildItem -Path "$buildSourceDirectory\$repo\$solutionName" -Filter *.pcfproj -Recurse
foreach($pcfProj in $pcfProjectFiles)
{     
    Write-Host "Adding Reference of Pcf Project - " $pcfProj.FullName
    # broken code
    # $pcfProjectPath = pcfProj.FullName
    
    # fixed
    $pcfProjectPath = "`"$($pcfProj.FullName)`""

    $addReferenceCommand = "solution add-reference --path $pcfProjectPath"
    Write-Host "Add Reference Command - $addReferenceCommand"
    Invoke-Expression -Command "$pacexepath $addReferenceCommand"
} 
```

I'll create a pull request to address this.

### Expected Behavior

The solution should build without error.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

March 2023

### Steps To Reproduce

1. Create a repo with a name in it.
2. Create a solution with an included PCF control
3. Try to deploy the solution.

**Comment by mikefactorial** [comment]
@sefa-phaag asked @RajeevPentyala to look into this issue. Thanks so much for the PR.
