### ISSUE TITLE
[CoE Starter Kit - BUG] Editing a flow without an Outlook Connection

### ISSUE THREAD

**Issue by Tadhg-io** [microsoft/coe-starter-kit#5122]
### Describe the issue

I've started implementing CoE in a tenant that still uses exchange on premises. 
I'm looking at the Flow "HELPER - Send Email". I can see from the description that this functionality is contained in one flow in case someone wants to change the method of communication. This is great as I think we will either try to switch to the SMTP connector or some kind of alert with HTTP or Service Bus.
The issue I'm having is I can't open this flow to view or edit it. Because I can't create an Outlook connection, and the "Continue" button on the splash screen stays greyed out. 
<img width="470" alt="image" src="https://user-images.githubusercontent.com/40873652/228478035-fc3f169a-c039-44e5-b12b-aa87e7b6baf2.png">

I'm looking for a way to get past this splash screen so that I can edit the flow. I also can't save a copy of the flow for the same reason. I understand that I am likely working outside of the prerequisites as per the CoE kit documentation, but I would appreciate any tips someone might have for circumventing this blocker.

As a last resort, I may import this flow elsewhere to analyse it, and then build my own version and repoint the parent flows to my new flow, but this changes the number of flows with an unmanaged layer from 1 to **14+**, so I would be keen to avoid this.

Let me know if this would be better posted in general Platform forums.
Thanks!

### Expected Behavior

I would expect to be able to edit this flow, and remove the steps using the connector that doesn't have a working connection.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

HELPER - Send Email

### Steps To Reproduce

- Needs to be recreated wither in a tenant without Outlook, or a user that does not have Exchange Online
- Import Core Components
- Attempt to edit the "HELPER - Send Email" flow

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont have an idea for this right now. You may be able to ask product support for a workaround, they may have ideas. 
I'll leave this open here to and see if others have ideas.
