### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Record Settings Defaults

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#5124]
### What is your question?

Is it possible to set the defaults for Environments on creation to Yes.

Specifically, If I have an environment created and its production, dynamics, pro code, in my case,  then last thing I want is it to be included in the inactivity, complliance, quarentines, cleanup flows.

Now I have these things turned off cos they can delete flows and envs etc which tbh is too scary.   But if some fool was to turn them on and it goes firing off emails and deleting things,  that would be bad.

So I am thinking it would be good to have default values for new envs that forces exclusions.  It would be better to have these by type also,   so developer vs sandbox vs production.

Is that possible today,    I could probably make my own flow detects creation of envirnments in datavserse and set it myself, but Id need to keep up with new settings each release of course.  So be nice if this was built in.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feb 2022

### What app or flow are you having the issue with?

N/A

**Comment by Jenefer-Monroe** [comment]
I dont think we can change the default behavior like that as it would impact all the tenants that have us installed. 
And with the new BYODL work, an env var is likely not going to work to do the same until the data flows support them. 
So I think for now you will need to just a flow that sits next to your CoE, when an envt is created > set the defaults as you want them. 
I hope thats helpful!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
