### ISSUE TITLE
[CoE Starter Kit - QUESTION] Refresh token URL for Office 365 Management API

### ISSUE THREAD

**Issue by HMJ-Somerset** [microsoft/coe-starter-kit#5127]
### What is your question?

![image](https://user-images.githubusercontent.com/106976858/228561459-2ee347a6-1656-43bd-a8a0-9afc02bb4226.png)
 I updated to the latest release of the CoE and I lost connection to the Office 365 Management API.
Fix connection doesn't work and so I think that I need to edit the custom connector.
I tried to edit the connection but have been asked for the Refresh token URL.  I can't find this in the setup documentation. 
 What is the URL?

### What solution are you experiencing the issue with?

Audit Log

**Comment by manuelap-msft** [comment]
The default identity provider for setting up a custom connector has changed from Azure Active Directory to Generic Oauth2 and needs to be changed when updating the security tab, see details here: https://github.com/microsoft/coe-starter-kit/issues/4808

Are you still seeing this new field when changing the identity provider to Azure Active Directory?
