### ISSUE TITLE
[ALM Accelerator - BUG]: ShareConnectionWithServicePrincipal.Run failed

### ISSUE THREAD

**Issue by dhaneshpmenon** [microsoft/coe-starter-kit#5128]
### Describe the issue

We are currently experiencing an issue while selecting the Production environment from the drop down. The error states that "**ShareConnectionWithServicePrincipal.Run failed: Connection not configured for this service.**".  We have suddenly started to observe this error and are unsure of its possible cause.

![image](https://user-images.githubusercontent.com/118192568/228573904-7c98e753-07ad-4885-84fc-048eca2191ed.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

3.23022.27

**Comment by mikefactorial** [comment]
@dhaneshpmenon can you verify if the flow is enabled?

**Comment by gerald560** [comment]
hi Mike it is and works well with other deployments

**Comment by dhaneshpmenon** [comment]
@mikefactorial Yes, it is.

**Comment by mikefactorial** [comment]
"The connection not configured for this service" error is pretty generic and usually means there's something wrong in the deployment. Sometimes deleting the existing connection and recreating it can help or it can also be an issue with permissions to the backing process table in Dataverse that has the Flow record in it. If the user doesn't have access to that record then this error can occur as well.
