### ISSUE TITLE
[ALM Accelerator - BUG]: Environment Variables SharePoint Data Source Unable to Select Site

### ISSUE THREAD

**Issue by jfung85** [microsoft/coe-starter-kit#5131]
### Describe the issue

When configuration deployment settings under Environment Variables, we are trying to select a SharePoint site as a data source but are unable to select the site that we want. We are using an account that has Site Collection Admin permissions to the site. Some sites are displayed in the drop-down but not all sites that this account has access too. This account has access to many sites and we think that the drop-down is not returning all sites over some threshold amount.

![image](https://user-images.githubusercontent.com/97466777/228687502-2d3a7af3-6e1b-41b5-81fd-9565f3222f07.png)

### Expected Behavior

We expected to be able to find the site that we want to configure for the SharePoint data source environment variable from the list of available sites that the logged in account has Site Collection Admin access to.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230308.1

### Steps To Reproduce

1. Open ALM Accelerator for Power Platform using an account that has access to many sites (not certain how many sites the account we are using has access to, it is a tenant admin account so may have access to all SharePoint site, this could be in the 1000's)
2. For a solutions that has a SharePoint Data Source environment variable -> select Configure Deployment Settings
3. Click on the Environment Variables tab
4. Click the drop-down and look for a site that the account has access to but does not show up in the listing

**Comment by mikefactorial** [comment]
@jfung85 thanks for submitting this. Will need to look into filtering capabilities for Sharepoint data source environment variables.

**Comment by jfung85** [comment]
I thought this issue had been resolved in the April release as we were able to configure the SharePoint Data Source value for a site that we needed to filter from a large list of sites that the account we are using has access to. When we clicked on the Filter icon and then added the URL, the next time we looked in the drop down the site was in the list. We were then able to proceed with a deployment. However, in trying a second deployment with the same configuration, all the SharePoint variables were cleared out and now the Filter icon doesn't seem to work as before using the same process and we are unable to find the site that we need. Is this still an open issue where the filter results are inconsistent so we may be able to filter for the site we need sometimes but not be able to at other times? Also, is it a different issue that all the SharePoint data source values were cleared out when trying to deploy a second time?

**Comment by mikefactorial** [comment]
Hey @jfung85 unfortunately this issue didn't make it into the April release and requires some more investigation to find a fix. We are aware of the issue and will try to get it fixed as resources permit.

**Comment by jfung85** [comment]
After further testing, it looks like the filter feature is able to find the site by the site name rather than the complete URL. I believe this issue could be closed based on this. For the main site, the site name worked to return the URL we were looking for. For subsites, it was a little bit harder if the name was the same between different main sites. In this case, search on a single key word in the subsite name seemed to work better to return the different main site + subsite URL we were looking for. Closing for now.

**Comment by jfung85** [comment]
One suggestion, it might be helpful to add a tooltip to the filter icon to give some guidance on using the site display name or partial display name to search.

**Comment by mikefactorial** [comment]
Thanks for the update @jfung85 and for the advice on the tooltip. Good call. Thanks. Will make that update now.
