### ISSUE TITLE
Custom Connector instructions don't match current March 2023 custom connector

### ISSUE THREAD

**Issue by kabirstein** [microsoft/coe-starter-kit#5132]
### Describe the issue

The instructions for setting up the custom connector in order to collect audit data do not match the custom connector which is dropped into Custom Connectors by the March 2023 core component import. Screenshot in instructions at https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog and current values in the Security tab of the Office 365 Management API custom connector fields do not match. Does anyone have the correct instructions? I am getting a 401 when trying to start the subscription.

### Expected Behavior

Need to have instructions that match the custom connector.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

downloaded ZIP 3/29/2023

### What app or flow are you having the issue with?

Custom Connector setup

### Steps To Reproduce

Need correct instructions. Note that instructions say go to the Security tab in the Office 365 Management API. Here are excerpts from the instructions on https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog:

Step 8. Don't change the Tenant ID. Note that there is no "Tenant ID" in the custom connector Security tab.
Step 9. Leave the Login URL as is for commercial tenants. Note that there is no Login URL field. There are "Authorization URL" and "Token URL" fields that are greyed out. They appear to be login URLs, so maybe Step 9 is incorrect and should be updated to refer to these 2 fields?
Step 10. Set the Resource URL to https://manage.office.com. There is no Resource URL. There is a "Refresh URL" that I keyed https://manage.office.com into but since I'm getting a 401 I assume this is not correct.

The connector updates and I am able to create the connection. However, when I go to test and Start Subscription and in put the Tenant ID and Application ID and select Test Operation I'm getting a 401 error:

{
  "cache-control": "no-cache",
  "content-length": "61",
  "content-type": "application/json; charset=utf-8",
  "date": "Thu, 30 Mar 2023 03:40:17 GMT",
  "expires": "-1",
  "pragma": "no-cache",
  "www-authenticate": "Bearer error=\"invalid_token\"",
  "x-aspnet-version": "4.0.30319",
  "x-ms-apihub-cached-response": "false",
  "x-ms-apihub-obo": "false",
  "x-powered-by": "ASP.NET"
}

Body:
{
  "Message": "Authorization has been denied for this request."
}

**Comment by kabirstein** [comment]
The instructions are out of date on https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog as you can see from this screenshot. Can someone update them? Also, what will happen to the Audit Log solution of my client's COE installations when they upgrade to the March 2023 download which contains this updated Custom Connector? Will they have to manually update their custom connectors or will their COE Audit Log solution continue to use the old custom connector with the OAuth 2.0 Authentication type?


![CurrentCustomConnectorInstructions](https://user-images.githubusercontent.com/54034916/228966455-52221fb0-1097-4b6a-9828-88755e4f781f.png)

**Comment by Jenefer-Monroe** [comment]
Yes we understand that the instructions are out of date. We have this fixed up for the next docs drop in April but I'll keep this as another doc bug to fix up real quick, perhaps a picture showing that would be good. 

Every time you update the CoE you need to update the connector, which is just a product issue with custom connectors and ALM. If you accidently setup as Generic Oauth (the new default, which is wrong), then there are more steps to clean up. I've outlined how to clean up from this here: [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

**Comment by kabirstein** [comment]
Actually the issues is NOT that the Identity Provider is Azure Active Directory. My Identity Provider is correctly, as you state it should be, "Generic OAuth 2". What is not working is the instructions. Aside from the confusion of Secret ID/Secret Value, Directory/Tenant ID, Application/Client ID, one needs to guess whether "Refresh URL" in the Security tab should be "https://manage.office.com" which is referred to as "Resource URL" in the instructions. Also, one must wonder why the Test gives a 401 even though the Custom Connector connection is able to be created and shows "Connected". Here are screenshots of my custom connector and app registration. If anyone can see anything wrong, please let me know. 

**And are there any current, complete instructions on how to create the needed custom connector from scratch?**

![SecurityTab](https://user-images.githubusercontent.com/54034916/228975459-2baf540b-bf7c-4951-97e5-449a37bb400f.png)

![TestTab](https://user-images.githubusercontent.com/54034916/228975528-12c28bfe-ff87-4113-a76b-aba441dbab36.png)

![AppRegistration](https://user-images.githubusercontent.com/54034916/228975736-7b98ea37-b5f3-4e99-b06a-e00f64c1341c.png)

![ClientSecret](https://user-images.githubusercontent.com/54034916/228975777-998486c2-f864-4f34-aeb0-a62452fd7714.png)

![ErrorCode](https://user-images.githubusercontent.com/54034916/228976746-95e66c76-a375-419e-9c11-1b0dcf598811.png)

**Comment by Jenefer-Monroe** [comment]
No it should not be generic oauth. It should be Azure Active Directly.

**Comment by Jenefer-Monroe** [comment]
As a result, the instructions in our documentation is correct except they are missing a step change away from the default identity provider
You must chose Azure Active Directory (which used to be default) and then you will see what you are used to seeing.
![image](https://user-images.githubusercontent.com/89584709/228861013-878b3fb7-d716-410d-8d31-4d73837113c7.png)

**Comment by Jenefer-Monroe** [comment]
And now that you are in a broken state due to bad connection creation, here are steps to get out of that state: [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

**Comment by manuelap-msft** [comment]
closing out as no further action from the CoE team required.
