### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Logs

### ISSUE THREAD

**Issue by PrasannaKumarPenumarthi** [microsoft/coe-starter-kit#5133]
### What is your question?

Sometimes i am getting the following mail (not daily FYI) regarding Audit Logs. Which "Environment Variables" do I need to update on "CoE Admin Command Center App", so that I won't receive this mail in future?
![auditlog](https://user-images.githubusercontent.com/129184387/228727536-342fcc03-767f-4191-b927-74d1d38b0c50.PNG)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Audit Log Mails to Admin

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
