### ISSUE TITLE
[CoE Starter Kit - BYODL] Consuming more API Calls then the normal COE Starter kit

### ISSUE THREAD

**Issue by A-Demir-ilx** [microsoft/coe-starter-kit#5135]
### What is your question?

Hello,

I have tested the new BYODL CoE starter and I saw that the BYODL is consuming more API calls then the normal COE starter kit.

Is there a way that the team can reduce the api calls? See attached screenshots. This is in a large tenant.

![image](https://user-images.githubusercontent.com/96475793/228807730-ed9974e3-3668-4aef-9508-0a9c89d7a760.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2023

**Comment by Jenefer-Monroe** [comment]
Hello, I'm not sure what the columns of numbers there represent, perhaps you can share that detail.
Can you please look at the following flows and let us know its state (on v off) and its API weight across the two envts

### Off in BYODL
These should be off for the BYODL evnt, and so not be taking any API calls (note i think we didnt force them off in the first preview, we just exited early, current bits turn these off)
Are they off? If on, what is their API usage compared to the Sync Flow envt?

- Admin | Sync Template v3 (Apps)
- Admin | Sync Template v3 (Flows)
- Admin | Sync Template v3 (Model Driven Apps)
- Admin | Sync Template v3
- CLEANUP - Admin | Sync Template v3 (Connection Status)
- CLEANUP HELPER - Check Deleted (Canvas Apps)
- CLEANUP HELPER - Check Deleted (Cloud Flows)
- CLEANUP HELPER - Check Deleted (Model Driven Apps)

### On in BYODL
These flows are specific to the BYODL case and woudl not be turned on for Sync Flows. Can you let me know if one of these appears to be the problematic flow? 

- SetupWizard>UpdateDataflowEnvironment
- CoE BYODL - When Maker dataflow refresh is complete
- CoE BYODL - When Environment dataflow refresh is complete
- CoE BYODL - When App dataflow refresh is complete
- CoE BYODL - When Flow dataflow refresh is complete
- CoE BYODL - When Model App dataflow refresh is complete

### Other API Intensive Flows
These are API intensive flows, can you see if they are on in both envts? And if they are consuming similar amounts of API calls? 

- Admin | Sync Template v3 (Flow Action Details)
- CLEANUP - Admin | Sync Template v3 (Check Deleted)
- CLEANUP - Admin | Sync Template v3 (Connection Status)
- CLEANUP - Admin | Sync Template v3 (Delete Bad Data)
- CLEANUP - Admin | Sync Template v3 (Orphaned Makers)
- CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
- CLEANUP - Admin | Sync Template v3 (PVA Usage)

**Comment by A-Demir-ilx** [comment]
Hi @Jenefer-Monroe , 

The setup of the BYODL environment is done via the Setup and Upgrade wizard. The flows that you have mentioned was already off.

Can we maybe plan a call to discuss it?

**Comment by Jenefer-Monroe** [comment]
I'm sorry but we are not staffed to have calls with our GitHub customers. 

Can you please check on the API usage for these flows? See if you can find the outlier that is causing all the noise? 

### Check API Usage 
- CoE BYODL - When Maker dataflow refresh is complete
- CoE BYODL - When Environment dataflow refresh is complete
- CoE BYODL - When App dataflow refresh is complete
- CoE BYODL - When Flow dataflow refresh is complete
- CoE BYODL - When Model App dataflow refresh is complete
- Admin | Sync Template v3 (Flow Action Details)
- CLEANUP - Admin | Sync Template v3 (Check Deleted)
- CLEANUP - Admin | Sync Template v3 (Connection Status)
- CLEANUP - Admin | Sync Template v3 (Delete Bad Data)
- CLEANUP - Admin | Sync Template v3 (Orphaned Makers)
- CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
- CLEANUP - Admin | Sync Template v3 (PVA Usage)

If you find the culprit, please compare with the usage in the sync flow envt
