### ISSUE TITLE
[CoE Starter Kit - BUG]  Invalid Pagination Policy error 

### ISSUE THREAD

**Issue by ChrisSchmucker** [microsoft/coe-starter-kit#5136]
### Describe the issue

I get the Invalid Pagination Policy error  when I activate Admin Sync flows.

![image](https://user-images.githubusercontent.com/111736821/228829475-d42f76a9-ec5d-4bfd-b6e7-3a9192f47374.png)

### Expected Behavior

Not to get the error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Ai Models) - and others 

### Anything else?

I should have the correct licenses associated with users so I'm not limited to 5000

![image](https://user-images.githubusercontent.com/111736821/228830183-7de79135-bb34-4420-bb6c-4cca5a3d0a3c.png)

**Comment by Jenefer-Monroe** [comment]
If you believe you have the correct licenses and the pagination still isn't working, then I'm afraid that would be a product issue, we do not have the ability to dictate anything about licenses, they just consume. You would need to contact product support.

**Comment by ChrisSchmucker** [comment]
Thanks for the quick feedback. It took +12 hours for the license to become active and it all works now.

**Comment by Jenefer-Monroe** [comment]
Thank you for letting me know! This will help me in the future, its a great question for me to ask people when they got the license assigned. Appreciate you following up! 
I'll go ahead and close but please return with new issues as you need help.
