### ISSUE TITLE
[Power Platform communication site template] Missing Pictures 

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5138]
### Describe your bug, question or feature ask.

Hi, 

When running the deployment script the script states that its not able to find pictures for the SharePoint site. The SharePoint side deployed successfully but the script was not able to source and upload certain pictures. I suspect the script images addresses hasn't been updated.

**Comment by Laskewitz** [comment]
Hi @nasilvae -

The script output is very descriptive. The template uses a mechanism where it checks if a picture is available, if not it uploads the picture, if it is it skips the uploading. In most cases, you're deploying the site to a new site collection, so it is a bit confusing, but it should work in the end. 

Do you see any missing pictures on the site?

**Comment by nasilvae** [comment]
> 

sounds good. I'm not noticing any missed pictures at this time.

**Comment by Laskewitz** [comment]
Thanks for the update. Closing the issue for now.
