### ISSUE TITLE
[Power Platform communication site template] Powershell keep stating deployment failed.

### ISSUE THREAD

**Issue by otecomputer** [microsoft/coe-starter-kit#5144]
### Describe your bug, question or feature ask.

INFO: Creating new site...
.INFO: Wait 15 seconds to make sure the site is ready...
ERROR: An error occurred during connecting to the newly created site.
ERROR: Deployment of Power Platform Hub failed!

Deleted the site and tried again. Now I get
INFO: Site already exists, skipping creation of site...
ERROR: An error occurred.
ERROR: Deployment of Power Platform Hub failed!

**Comment by Laskewitz** [comment]
Hi @otecomputer,

Can you remove the site from the recycle bin and try again?

Thanks!

**Comment by Laskewitz** [comment]
@otecomputer - can you please try what I asked last week? If we don't get a response we'll close this issue soon.
