### ISSUE TITLE
[ALM Accelerator - QUESTION] QUESTION

### ISSUE THREAD

**Issue by alena-grischenko** [microsoft/coe-starter-kit#5148]
### What is your question?

Happy Friday!
My client’s ops team got a request from developers to support the ALM accelerator setup and configuration.
Following the steps in the article below:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-preview#give-power-app-management-permission-to-your-app

Here is the Important text:

Currently, this cmdlet gives elevated permissions (for example, Power Platform Admin) to the app registration. Your organization's security policies may not allow for these types of permissions. Ensure that these permissions are allowed before continuing. In the case that these elevated permissions are not allowed certain capabilities won't work in the AA4PP pipelines.

Questions:

1)	Is it “for example, Power Platform Admin” or Power Platform Admin?
2)	As we can’t allow Power Platform Admin which capabilities will not work?
3)	What are the minimum permissions required for the app?
4)	How do we assign these required permissions if the cmdlet only gives the elevated one?

Thank you very much in advance!
I really appreciate your help with this one.

Thank you very much!

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.1.2023

**Comment by mikefactorial** [comment]
@alena-grischenko this is currently a gap in functionality in the platform. Without these permissions Canvas App Sharing will not succeed but the pipeline won't fail on deploy. We're using the admin enpoints for sharing canvas apps in the platform as they are the only APIs available that support Service Principal currently. If you decide not to provide the permissions then you'll need to manually share apps in the downstream environment. Not something we can work around at the moment based on the platform restrictions. Here's the list of functionality in the pipelines that require this permission today. 

 - Sharing canvas apps in downstream environments.
 - Updating canvas app owner on import of an unmanaged solution.
 - Running canvas test automation, where applicable, to override connection consent.

**Comment by alena-grischenko** [comment]
> @alena-grischenko this is currently a gap in functionality in the platform. Without these permissions Canvas App Sharing will not succeed but the pipeline won't fail on deploy. We're using the admin enpoints for sharing canvas apps in the platform as they are the only APIs available that support Service Principal currently. If you decide not to provide the permissions then you'll need to manually share apps in the downstream environment. Not something we can work around at the moment based on the platform restrictions. Here's the list of functionality in the pipelines that require this permission today.
> 
> * Sharing canvas apps in downstream environments.
> * Updating canvas app owner on import of an unmanaged solution.
> * Running canvas test automation, where applicable, to override connection consent.

@mikefactorial Thank you so much for the detailed response! I will share it with my ops and dev teams

**Comment by mikefactorial** [comment]
Closing this out as there's no further action required here.
