### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to repopulate maker group?

### ISSUE THREAD

**Issue by EmpbPowerAdmin** [microsoft/coe-starter-kit#5152]
### What is your question?

The maker group did not populate because the email address was in the field instead of the objectid for the group itself.  Now my add to maker flow is working but only for the past six users that created their first flow.

We have ~100 users that make flows and applications but are not in the Team/group for Power platform makers.

How do I populate this group?  The inventory flows said they ran successfully but only the six users that the add to maker group flow caught are in there currently.

Thank you

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Latest

### What app or flow are you having the issue with?

Adding all makers to group

**Comment by Jenefer-Monroe** [comment]
We dont have a flow to repopulate these groups today but it is in our backlog
To do it yourself:

### In flow
You could make a flow yourself that does the same operations as **_Admin | Add Maker to Group_** but a little changed. 
You could list all the people in the Maker table, then put the **_Add user Scope_** section in an apply to each for them. And call these spots with the current maker 
![image](https://user-images.githubusercontent.com/89584709/229121783-767e7286-596f-491d-aec2-3aedb4ca1771.png)

### Manually
If you are not comfortable enough with flow to do this, you could just do it manually. With 100 users, if you don't know flow well that might be faster. 
You would just get the names from the Maker table and add then in Azure to your group.

**Comment by EmpbPowerAdmin** [comment]
thanks Jenefer, I think I will just do manually, how do I list the makers from the table?

**Comment by EmpbPowerAdmin** [comment]
It did! just used powershell to get them in there real quick.  Thank you Jenefer!

**Comment by Jenefer-Monroe** [comment]
wonderful news!
