### ISSUE TITLE
[CoE Starter Kit - QUESTION] Data export feature comment for setup wizard

### ISSUE THREAD

**Issue by anttipajunen** [microsoft/coe-starter-kit#5153]
### What is your question?

I'm trying the new data export preview and while this feels quite straightforward, there's one thing I'd change with the wizard. Please see the image below. The text in bold. I'd be more specific what _"inventory and usage files in the folders configured to receive the Data Export"_ means. I reckon this refers to a storage account's storage browser.

Another point. The link in the bolded text just re-opens the setup wizard in a new tab.

![image](https://user-images.githubusercontent.com/64043240/229127097-1072180a-3b7f-4f12-94e8-1c0f2c59a59a.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2023 preview

**Comment by Jenefer-Monroe** [comment]
fixing up the link, at least, would qualify for our papercut push.

**Comment by manuelap-msft** [comment]
Fixed locally, there was just a typo in the URL and then the launch failed.
