### ISSUE TITLE
[CoE Starter Kit - QUESTION] Storage account endpoint problem

### ISSUE THREAD

**Issue by anttipajunen** [microsoft/coe-starter-kit#5155]
### What is your question?

[Learn](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#troubleshooting-1) states that _Verify that the DatalakeURL parameter points to your Azure Storage Account URL - the URL should contain dfs.core and end with /powerplatform._. I've set up a gen 2 and completed data export for apps and flows from PPAC but my endpoint is https://xyz.dfs.core.windows.net/

I'm getting the DataFormat.Error and can't figure out how to correct this. The storage browser does show that the metrics have increases so the sync should be fine. PPAC also states connected.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

**Comment by manuelap-msft** [comment]
You would just need to append powerplatform - https://xyz.dfs.core.windows.net/powerplatform when updating the parameter.

**Comment by anttipajunen** [comment]
Ooh, hahaha. Thanks Manuela! I completely missed that haha. It works.

**Comment by manuelap-msft** [comment]
No worries, it's a bit hidden under the screenshot. I think in the next version we'll append powerplatform in our Dataflow logic so you won't have to do that manually anymore.

There's a couple of open issues with the March version of this, just letting you know here so you're aware too:
https://github.com/microsoft/coe-starter-kit/issues/4977#issuecomment-1469601369
