### ISSUE TITLE
[ALM Accelerator - BUG]: Flows are not activated after import

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5156]
### Describe the issue

Hello, we've configured flows to be on in the deployment settings
![image](https://user-images.githubusercontent.com/55705669/229154674-dbc31185-1669-47e8-97b0-887ded021bc3.png)

but they're off after solution import. Have opened the solution.zip file and also the solution meta-data shows the flow status as off there.

### Expected Behavior

Flows turn on after import.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

latest

**Comment by mikefactorial** [comment]
Thanks for reporting this @manuelap-msft. Always good to have internal eyes on what we're doing :) @RajeevPentyala any chance you can take a look at this on Monday? If not I'm happy to take it as an action item after our bug bash

**Comment by manuelap-msft** [comment]
Hello, 

I did some more testing and hoping that helps with the triage
- Other flows activate fine, so it seems to be specific to the ones highlighted
- The solution has about 90 flows and the once we want to activate are alphabetically at the bottom, so could it be a pagination issue / or not retrieving all flows?
- The flow names contain a special character >, not sure if that could lead to an issue (e.g. comparing > with &gt; if there's encoding in place or so)

**Comment by mikefactorial** [comment]
This ended up being an encoding issue with ConvertTo-Json in powershell that was creating unicode escaped values in the name of the deploymentSettings.json. Solution was to Unencode the json before storing it. https://github.com/microsoft/coe-alm-accelerator-templates/pull/292

**Comment by manuelap-msft** [comment]
Great news, and sorry for introducing special characters 😄
