### ISSUE TITLE
[CoE Starter Kit - BUG] New-PowerAppManagementApp doesn't respeect "usgov" endpoint

### ISSUE THREAD

**Issue by rbmathis** [microsoft/coe-starter-kit#5157]
### Describe the issue

When running through the setup for USGOV customers, I'm unable to set the endpoint to "usgov", and receive 401 errors when running the New-PowerAppManagementApp command.  I believe this is likely caused by the PS not using the -Endpoint param

### Expected Behavior

After running Add-PowerAppsAccount -Endpoint "usgov", when I run New-PowerAppManagementApp, it should use the usgov endpoint

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.0.156

### What app or flow are you having the issue with?

New-PowerAppManagementApp

### Steps To Reproduce

Follow instructions from https://github.com/Power-Platform-DevOps/Power-Platform-ALM-Starter-Kit.

1. Per setup instructions, run Add-PowerAppsAccount -Endpoint "usgov" to successfully auth to usgov tenant
2. Run New-PowerAppManagementApp to provide ApplicationId for the management app

**Comment by mikefactorial** [comment]
@rbmathis have you tried az cloud set --name AzureUSGovernment before az login?

**Comment by rbmathis** [comment]
I did try that (via AzConnect PS). Here's the deeper exception that is throwing.

CategoryInfo          : InvalidOperation: (Method: PUT, Reques…ontent-Length: 0
                        }:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ErrorDetails          : {"error":{"code":"MultipleErrorsOccurred","message":"Multiple errors occurred:
'Unauthorized,Unauthorized,Unauthorized,Unauthorized'. Please see
details.","details":[{"code":"ClientNotSupportedForCrossCloudRequest","message":"The client is not supported in Cross
Cloud Request for tenant
'6ac4a3f0-12c0-444e-ba72-c80809d1550a'."},{"code":"ClientNotSupportedForCrossCloudRequest","message":"The client is
not supported in Cross Cloud Request for tenant
'6ac4a3f0-12c0-444e-ba72-c80809d1550a'."},{"code":"ClientNotSupportedForCrossCloudRequest","message":"The client is
not supported in Cross Cloud Request for tenant
'6ac4a3f0-12c0-444e-ba72-c80809d1550a'."},{"code":"ClientNotSupportedForCrossCloudRequest","message":"The client is
not supported in Cross Cloud Request for tenant '6ac4a3f0-12c0-444e-ba72-c80809d1550a'."}]}}
InvocationInfo        :
    MyCommand        : Invoke-WebRequest
    ScriptLineNumber : 75
    OffsetInLine     : 25
    HistoryId        : 9
    ScriptName       : C:\Program Files\WindowsPowerShell\Modules\Microsoft.PowerApps.Administration.PowerShell\2.0.156
\Microsoft.PowerApps.RestClientModule.psm1
    Line             : $response = Invoke-WebRequest -Uri $Uri -Headers $Headers -Method $Method -UseBasicParsing

**Comment by mikefactorial** [comment]
Based on the error this would seem to be a policy in the GCC Cloud that is set to not allow up leveling the Service Principals permissions. You can still use the ALM Accelerator, however, some functionality will not work without the permission. Closing this out as there's nothing more to do here with respect to the permissions restriction on our end.

**Comment by mikefactorial** [comment]
The specific features that won't work as a result of not having this permission are listed here
https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceALMAccelerator/PREVIEW.md
