### ISSUE TITLE
[CoE Starter Kit - BUG] Mismatch between city and country in Maker table

### ISSUE THREAD

**Issue by KiraXie2** [microsoft/coe-starter-kit#5164]
### Describe the issue

I found mismatch problem between city and country in Maker table as below for an example.
How is the data populated for the Maker table (admin_maker) in CoE core components? I want to know if there is any flow and which flow in core components is used to create and update records in this Maker table? 
![image](https://user-images.githubusercontent.com/108067225/229398235-feeb5943-a62d-4a5a-8c69-893365788779.png)

### Expected Behavior

Only Shanghai-China (city-country) pair is valid.
Solve the problem of invalid city-country pair. e.g. Shanghai-Germany, Shanghai-Czech Republic...

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

I don't know which flow; but the problem comes from Maker table (admin_maker) in Dataverse

### Steps To Reproduce

1. Go to the core components in CoE environment
2. Open the Maker table (Dataverse table)
3. the mismatch problem can be found as the image attached above in issue description

**Comment by manuelap-msft** [comment]
Hello,

we get this information from the Office 365 Users connector and the Azure Active Directory profile of the maker. Can you create a test flow that calls the [Get user profile](https://learn.microsoft.com/en-us/connectors/office365users/#get-user-profile-(v2)) action of the Office 365 Users connector with one of the User IDs that's showing Shanghai/Germany in the Maker table and see what it returns for city and country?

Thank you
Manuela

**Comment by KiraXie2** [comment]
Hi Manuela, yes now I see the user data maintained in Azure is not correct from our side. But could you tell me which flow in CoE toolkit is populating and updating records in this Maker table?

**Comment by manuelap-msft** [comment]
It's the **HELPER - Maker Check** flow that does this

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
