### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by alena-grischenko** [microsoft/coe-starter-kit#5165]
### What is your question?

Hi Team,
There is a concept of the Datverse for Teams environment inactivity and there is a built-in cleanup.
"Power Platform includes a built-in mechanism for automatically cleaning up Dataverse for Teams environments that have been inactive for 90 days."
For the Power Platform environment (not Teams), how would we define inactivity? Also, is there currently a way to identify inactive environments via the available admin connectors?

Thank you very much!

Olena Grischenko

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Hello. We do not currently have a technique to identify non-teams environments as active or not, although we do have a backlog item to add such a feature.

**Comment by Jenefer-Monroe** [comment]
If you have some ideas of what you would like to be considered inactive, or concerns about such a feature., please do let us know and we can add to the feature item.

**Comment by alena-grischenko** [comment]
> If you have some ideas of what you would like to be considered inactive, or concerns about such a feature., please do let us know and we can add to the feature item.

@Jenefer-Monroe Thank you very much for the quick response. Our team is currently discussing this issue. Will let you know what we came up with. Thanks a lot again!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
