### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by PowerPlatformers** [microsoft/coe-starter-kit#5174]
### What is your question?

1. Why is there a difference between the identifier I can get from Power Automate in the solution and the identifier I can see in the CoE Starter Kit when I import a solution exported in an unmanaged configuration by another tenant into the Teams environment?
2.  The apps/flows in the solution exported in the UNMANAGED configuration can be viewed in the Power Platform Admin View. On the other hand, what is the reason that apps/flows in the solution exported in the MANAGED configuration cannot be viewed in the Power Platform Admin View?
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 2022

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Sorry I'm having some trouble following this. 

For your first issue. I'm lost on what identifier you are referecing, and what you are comparing it to. Can you please share some screenshots? (note you need to be logged in to GitHub to share pictures)

For your second issue, similarly, I'm not sure what you are referencing. Do you mean an unmanaged version of our solution? Screenshots would be helpful.

**Comment by PowerPlatformers** [comment]
Thanks for the reply.

1. As for the identifier, I am referring to the ID in the attached screenshot.

[from Power Automate in the solution]
![image](https://user-images.githubusercontent.com/129748781/229665552-45f3feab-d287-49fc-8141-aba80f1124e4.png)

[in the CoE Starter Kit]
![image](https://user-images.githubusercontent.com/129748781/229665645-93857341-bd5a-4f95-994d-f8125b87806b.png)

2. I am not referring to your solution that encompasses the CoE Starter Kit, but rather to a solution made with Power Platform in general.
I am having trouble importing said solution in a managed manner into the Teams environment and the specifics are not coming up in the Admin View.

[the apps/flows in the solution exported in the MANAGED configuration cannot be viewed in the Power Platform Admin View]
![image](https://user-images.githubusercontent.com/129748781/229665738-cec42ed2-a380-4201-ac51-2e21956884ff.png)

**Comment by Jenefer-Monroe** [comment]
Can you please share what you clicked to get to this? 
![image](https://user-images.githubusercontent.com/89584709/229800688-5758bffa-610a-4c45-9324-1d0ac11c7890.png)

**Comment by Jenefer-Monroe** [comment]
For issue 1. 
The product uses several GUIDs for each object, so I can't really comment on why they picked that GUID for that spot in the UX.  It's not one we track, so I'm afraid you'll need to contact product support. It appears to be a bug to me. 
The GUID we use, that you see in our app, is the one you would use to get information about the flow as shown here
![image](https://user-images.githubusercontent.com/89584709/229812538-77c653f4-0336-4d76-842a-eed7f45979de.png)

**Comment by Jenefer-Monroe** [comment]
For issue 2. 
If you are not able to import the solution into the product then it will not appear in our inventory.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
