### ISSUE TITLE
[CoE Starter Kit - QUESTION] App and Flow Inactivity Notifications Clean Up View

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5181]
### What is your question?

Hi,

After rejecting the APP or Flow by user, do Admin need to excuse the app or flow in  "App and Flow Inactivity Notifications Clean Up View" ?  What happen if Admin won't excuse the App or Flow?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Yes the idea is that if you read their rejection note and believe it can permanently excuse the app/flow, then you can do that in that admin app. 
If you do not do that, then the rejection will time out after a month and they will be pinged again. 
You can see some diagrams for this that are helpful in our documentation for [Admin | Inactivity notifications v2 (Start Approval for Apps)](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#admin--inactivity-notifications-v2-start-approval-for-apps) and [Admin | Inactivity notifications v2 (Start Approval for Flows)](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#admin--inactivity-notifications-v2-start-approval-for-flows)

**Comment by Jenefer-Monroe** [comment]
You are most welcome.
