### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to Commit Solution

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5182]
### Describe the issue

Unable to start commit step for solution. We are getting the following error. 
![image](https://user-images.githubusercontent.com/95443860/229602618-0e3c8133-d2d4-48de-b585-e8dcb9ddc491.png)

### Expected Behavior

Able to commit. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

December Release

**Comment by mikefactorial** [comment]
@nasilvae looks like you're fairly far behind on releases. The latest is here (https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-March2023). Have you tried upgrading to the latest? https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-upgrade-config

Also, make sure that both the solution you have installed in Dataverse matches the version of the pipelines you have installed from https://github.com/microsoft/coe-alm-accelerator-templates
