### ISSUE TITLE
[CoE Starter Kit - Feature]: Compliance emails localization

### ISSUE THREAD

**Issue by ashlega** [microsoft/coe-starter-kit#5183]
### Is your feature request related to a problem? Please describe.

Currently, there is a part of compliance emails which is not translatable / customizable - would be great if we could add translations without having to do unmanaged customization of those flows:

![image](https://user-images.githubusercontent.com/5911927/229608989-b8995e12-b910-4139-b7a4-d2a73b6dd70c.png)

### Describe the solution you'd like

Maybe one option would be to use url replacement of some sort (handlebar sytnax... or even simple replacement... so that we'd specify something like app.name in the email template, and that would be replaced with the display name of the application). In that case we could just put all that content in the template instead of having some of it hardcoded in the flow

**Comment by ashlega** [comment]
I wonder if this could be done using Dataverse custom API - for example, if the solution had custom API to do the replacements, you could just pass email "body" and a json object with name-value pairs to the custom API so that the replacement would be done there in one action, and the output of that action could be used to populate email body. Whether it's handlebars or just pure string replacement... could be the latter at first. I'll try to prototype it to see how it works.

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this out but if you come up with a strategy please post for us.
