### ISSUE TITLE
[CoE Starter Kit - BUG] PBI BYOD_Flows table not accurate

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5189]
### Describe the issue

Hi Team, 

We have successfully installed CoE BYODL. However, we have noticed that the flow and app reports from the Admin View and PBI are not matching up. For example, flow report in Admin View is 57198 flows and flow report in PBI is 8669 flows. We are using the same dataflows configuration that was provided along with the same account and same storage account. Both reports are refreshing successfully. 

Thoughts?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March BOYDL Preview

### What app or flow are you having the issue with?

Admin View & Power BI Reports

### Steps To Reproduce

Run data flows, open report.

**Comment by manuelap-msft** [comment]
This is likely related to this known issue, where the Power BI dashboard is missing data from the Default- environment:
https://github.com/microsoft/coe-starter-kit/issues/5052

We do have an updated Power BI dataflow that should address this issue:
https://github.com/microsoft/coe-starter-kit/issues/5052#issuecomment-1480843722
