### ISSUE TITLE
Customized Emails

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#5194]
I have edited the customize Compliance Details Request email notifications in the customized emails table, but after publishing the customizations, the contextual update reverted back to the original text. How can i get around this so that the email notification is customized for our organization needs?

**Comment by Jenefer-Monroe** [comment]
Where did you customize it? Did you customize it in the CoE Admin Command Center? 
![image](https://user-images.githubusercontent.com/89584709/229936091-515d82a7-9cd0-497c-9b02-06e900516361.png)

**Comment by dcurt1977** [comment]
I edited the record **Send Audit Mail to Owners Apps** in the Customized Emails table in the Core Components solution. In the screenshot below, yesterday I changed the Default Value from Yes to No and it appears that the changes I made to the body of the email did not change back to the default text. 

![CustomizedEmail](https://user-images.githubusercontent.com/123478097/230099301-4a36351f-98e7-482c-ba04-2e2b3368f471.PNG)

**Comment by Jenefer-Monroe** [comment]
Yes thats correct, if you use the app that will happen for you but you can edit there too.

**Comment by dcurt1977** [comment]
Thank you very much as always. The CoE is a fantastic tool for our organization.

**Comment by Jenefer-Monroe** [comment]
awww thank you so much, we love to hear that!

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this but please feel free to return with other issues as needed.
