### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to customize env request so user cannot invite other admins?

### ISSUE THREAD

**Issue by Zubair-DS** [microsoft/coe-starter-kit#5198]
### What is your question?

Is it possible to create a custom environment request maker application where only the admin user is designated as the owner and no other users are displayed? The application should restrict the owner selection to only the admin user. Is this achievable?

### What solution are you experiencing the issue with?

Core

**Comment by Jenefer-Monroe** [comment]
We aren't staffed to assist with customizations but I did take a quick look for you and this does seem pretty easy yes. 

Basically you could just filter that gallery even further down to only be the logged in user
![image](https://user-images.githubusercontent.com/89584709/230082756-94131839-5d7a-4230-aa9b-f39098eee602.png)

Hope thats helpful!

**Comment by Zubair-DS** [comment]
Yes, I got it. Let me try this.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
