### ISSUE TITLE
[BUG]: CLEANUP - Admin | Sync Template v3 (Check Deleted) Failing

### ISSUE THREAD

**Issue by hankanman** [microsoft/coe-starter-kit#520]
**Describe the bug**
CLEANUP - Admin | Sync Template v3 (Check Deleted) flow failing with:

Error: 
Action 'List_Apps_with_No_Environment' failed

Error Details:
Principal user (Id=334c01f3-9cb8-eb11-8236-002248016b22, type=8, roleCount=4, privilegeCount=564, accessMode=1(Setup/Stub user with filtered privileges from associated roles. Consider changing user AccessMode to Full (without privilege filtering))), is missing prvCreateadmin_SyncFlowErrors privilege (Id=1b88fda1-4358-42f2-a680-992a0249af2f) on OTC=10188 for entity 'admin_syncflowerrors'. context.Caller=334c01f3-9cb8-eb11-8236-002248016b22. Or identityUser.SystemUserId=14180b8c-75be-400e-b125-332f6cd47f07, identityUser.Privileges.Count=2097, identityUser.Roles.Count=0 is missing prvCreateadmin_SyncFlowErrors privilege (Id=1b88fda1-4358-42f2-a680-992a0249af2f) on OTC=10188 for entity 'admin_syncflowerrors'.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - 2.1.6
 - CLEANUP - Admin | Sync Template v3 (Check Deleted)

1. Run flow with appropriate privileges
2. flow fails with above error
3. check principal user id in Azure Ad, user doesn't exist

**Expected behavior**
Flow runs successfully

**Screenshots**
![Screenshot 2021-05-27 092947](https://user-images.githubusercontent.com/3953290/119793042-251b0400-bece-11eb-8b25-35011e3aeb79.png)

**Comment by JeneferM-MSFT** [comment]
Can you confirm you have installed with a service principle yes? 
And what do you mean by this step? 
3. check principal user id in Azure Ad, user doesn't exist

**Comment by JeneferM-MSFT** [comment]
Thank you, correct it is not required. I was just checking from your notes it sounded like you did.

**Comment by hankanman** [comment]
Okay no worries! Let me know if there is any other info needed

**Comment by JeneferM-MSFT** [comment]
closing out as no action for toolkit without repro
