### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Detail Request Flow - Requested Apps

### ISSUE THREAD

**Issue by santhods** [microsoft/coe-starter-kit#5200]
### Describe the issue

In the compliance request flow (on the compliance for apps section), the condition named: Condition: Audit apps that are broadly shared or admin has requested audit (under Compliance due to heavy usage -> Apply to each envt -> Send Compliance Request email for Apps -> Apply to each envt App) has a final condition that says:

-	Admin Requirement risk assessment state _is not equal to 597910000 (this is None in the choice column in PowerApps app table)_ 

![image](https://user-images.githubusercontent.com/25540261/230072926-cfcce8ea-4e2a-4f4a-b773-a00daaae8e3d.png)

The condition allows some apps that do not meet our compliance conditions to be included in the compliance requests (where users get an email notification asking them to submit compliance details, but their shared users, shared groups, and launches last 30 days are not met).

During our recent testing, removing this specific condition clause resolves this issue – and only apps that meet with our compliance conditions are set to ‘Requested’.  Before removing this clause, we tested by adding an excel action to print out the list of apps and their associated users and groups shared and app launches, and we can see that some apps would not meet a condition to become 'Requested'.

We did not know about this behaviour until we have the results returned from the flow run.

### Expected Behavior

The flow should only get mark apps for compliance that meet with the compliance conditions that we set (we set these conditions in the Admin - Command Centre app). We checked the compliance condition values in the flow and they are correct.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Compliance detail request v3

### Steps To Reproduce

1. Switch on Admin | Compliance detail request v3
2. Run Admin | Compliance detail request v3
3. Retrieve the results in PowerApps app table with 'Risk Assessment State' equal to 'Requested'.

**Comment by Jenefer-Monroe** [comment]
I'm remembering we did have a bug once in past in which we incorrectly flagged some apps as Requested so maybe your data just needs cleaned up, mark those objects back to none?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
