### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Command Center - Papercut push

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5201]
### Describe the issue

command center papercut:
1. command center > m365 shows as sync flow issue when in fact it's just not configured, need to catch that 
1. helper - maker check catch and ignore failure if a record with matching key values already exists, just ignore this failure 
1. customized emails page - dialog on save needs to be creator kit dialog 
1. env var - for secrets, open default solution to update the secret 
1. coe support - extend width of command bar to show report issues by default without having to click on ... 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

latest

### What app or flow are you having the issue with?

Command Center

**Comment by Jenefer-Monroe** [comment]
- [ ] command center > m365 shows as sync flow issue when in fact it's just not configured, need to catch that 
- [ ] helper - maker check catch and ignore failure if a record with matching key values already exists, just ignore this failure 
- [ ] customized emails page - dialog on save needs to be creator kit dialog 
- [ ] env var - for secrets, open default solution to update the secret 
- [ ] coe support - extend width of command bar to show report issues by default without having to click on ...
