### ISSUE TITLE
[CoE Starter Kit - QUESTION] Issue with Audit Log Sync Flows

### ISSUE THREAD

**Issue by joebeyer75** [microsoft/coe-starter-kit#5202]
### What is your question?

Hello, 

We had to refresh the Client Secrets on the App Registrations and update the Office 365 Management API connection with this information. After updating the "Security" tab for that Custom Connection, we then go to the "Test" tab, select StartSubscription, enter the tenant ID and the Client ID, and we're getting the following error message:

Status (401)
{
  "cache-control": "no-cache",
  "content-length": "61",
  "content-type": "application/json; charset=utf-8",
  "date": "Wed, 05 Apr 2023 15:09:10 GMT",
  "expires": "-1",
  "pragma": "no-cache",
  "www-authenticate": "Bearer error=\"invalid_token\"",
  "x-aspnet-version": "4.0.30319",
  "x-ms-apihub-cached-response": "true",
  "x-ms-apihub-obo": "false",
  "x-powered-by": "ASP.NET"
}

{
  "Message": "Authorization has been denied for this request."
}

On the "Security" tab of the Custom Connector, we typically update what is called the "Resource URL". That is now called the "Refresh URL". Is this the same thing? We're using https://manage.office.com

Is it typical for the Admin | Sync Audit Logs flow to run for 3+ days when successful, and run for 12 hours even when it fails? 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Was deployed in June of 2022

### What app or flow are you having the issue with?

Admin | Sync Audit Logs & [Child] Admin | Sync Logs

**Comment by manuelap-msft** [comment]
The default identity provider for custom connectors has recently changed, and you'll need to update it to successfully authenticate the custom connector, see: 
https://github.com/microsoft/coe-starter-kit/issues/4808

We have a write up here of how to get out of this state:
https://github.com/microsoft/coe-starter-kit/issues/4961

**Comment by joebeyer75** [comment]
> 

Thanks, this helped. After choosing the new Auth type and updating the connection, we were back in business for a few hours. 

I just logged in to check, after not making any changes, and all of the recent flow attempts have failed for the [Child] Admin | Sync Logs flow. 

The error is "list audit log content" step, and is showing "Authorization has been denied for this request."

Any ideas on that part?

**Comment by Jenefer-Monroe** [comment]
Once you have a bad connection, cleaning it up is difficult, likely you have the old connector still referenced in the Run Only Users property of the flow. I recommend deleting all the connections to the custom connector and starting over. The steps outlined here 
https://github.com/microsoft/coe-starter-kit/issues/4961 will help you walk through step by step to ensure the correct connection is used.

**Comment by Jenefer-Monroe** [comment]
For 1, as long as you follow that write up, and see the things outlined, then you should be good to go. This is the only place we call the custom connector.

For 2, no that is not normal, can you please post separately with screehshots so I can follow the issue?
