### ISSUE TITLE
[CoE Starter Kit - BUG] April 2023 Cannot turn on Admin | Sync Template v3 (Call Update) and Setup Wizard > Call OrphanFlow

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#5204]
### Describe the issue

Cannot switch on Admin | Sync Template v3 (Call Update) and Setup Wizard > Call OrphanFlow

### Expected Behavior

I expect to turn these flows on either from the SetUp Wizard  or manually

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Call Update) and SetupWizard > CallOrphanFlow

### Steps To Reproduce

Run Setup Wizard -> Get to Inventory Flows
Attempt to turn these flows on.
Nothing Happens.
Navigate tpo flow and attempt to turn flow on.

**Comment by Jenefer-Monroe** [comment]
These things have dependencies so do need to be turned on in the correct order. So I presume you've done them in the correct order (as would happen if using the Setup Wizard)

What error message is given when you try to turn on manually?

**Comment by NPrice99** [comment]
![image](https://user-images.githubusercontent.com/8484048/230143211-59f9b36b-5c0c-4470-accc-c0d55d4566c3.png)

**Comment by NPrice99** [comment]
That was the problem ! (the clue was you had Admin | Sync Template V3 and I only had Admin | Sync Template V2)

**Comment by Jenefer-Monroe** [comment]
awesome! Thanks for installing so quickly for us!
