### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Sync Template V3 error with Orphaned User

### ISSUE THREAD

**Issue by Sishira** [microsoft/coe-starter-kit#5205]
### Describe the issue

Admin sync template is running with error when encounter any Orphaned users. Based on the run log, we could trace the issue is due to condition check logic where user profile output is like "true" but on condition its "True". I have highlited in below screenshots:
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/99423817/230168526-95568adf-bb81-4dc9-9607-5214d01289a3.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/99423817/230168537-1c2bb691-f869-43b9-beb4-a16b4fb7ff2d.png)

### Expected Behavior

Flow should run without any error for Orphaned users also

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin - Sync Template v3

### Steps To Reproduce

1- Run flow with users are really not exist in Org but App exists

**Comment by Jenefer-Monroe** [comment]
Hello I believe you have unmanaged layers on your flow. This was a change we did a few months ago when the ability to return boolean was introduced. Here is what is present today:
![image](https://user-images.githubusercontent.com/89584709/230176670-6a13d39b-f468-4ad0-bb33-364fc1d0c71a.png)

Please make sure you have [removed all unmanaged layers](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows) from the flows in the kit. 
Hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
