### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Sub2000** [microsoft/coe-starter-kit#5206]
### What is your question?

After upgrading to 4.2, the connector display name is no longer an option to add to an export when exporting apps or flows to excel using the admin view.  We were several releases behind, so I don't know when the advanced find tool was replaced.  I like the upgrade better, but we have end user facing reports that use the connector display name.  This is much easier for people to deal with and ID the connector.  Below is a sample that is returned using PowerShell.  The CoE admin view only provide the last part of the connector ID such as "shared_office365" where it previously provided the display name such as "Office 365 Outlook".  I have not been able to find the display name to add using the edit columns.  Please let me know if I am missing something or if this should be a feature request to add display name back.  I also added a screen snip for clarity.  Thanks

Connector ID:	
/providers/Microsoft.PowerApps/apis/shared_office365

Connector Name:
Office 365 Outlook

<img width="435" alt="ConnectionNames" src="https://user-images.githubusercontent.com/92055324/230216090-410159eb-ea2b-4c79-b79f-14b2b8caf251.PNG">

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

admin view

**Comment by Jenefer-Monroe** [comment]
We use this column for the DLP Editor app, and so we had to switch away from using the Display Name because its localized and so was not reliable for detecting connectors. 

Can you explain what you are trying to accomplish when you export? Ex: want to know what connectors are used in an app? and envt? etc. 
I would think our PBI reports meet your need already and if not, would love to hear the need so we can see how to add it.

**Comment by Sub2000** [comment]
Thanks for the quick reply.

We export all the flows and then split the connector column so each connector creates a new row in excel.  We then add a new column that compares each connector to the connectors allowed in a DLP policy we plan to apply to the default environment.  This is how we have reported to end-users for them to know if they need to request a new environment to migrate to before we lock down the default.   We do this for apps as well.  The connector display name worked great as it is provided when we export our DLP policy using PowerShell.  It is also clearer and matches up with online resources such as List of all connectors published by Microsoft | Microsoft Learn<https://learn.microsoft.com/en-us/connectors/connector-reference/connector-reference-microsoft-connectors>.  It is a much easier ID to use for endures and admins.

Thanks

**Comment by Jenefer-Monroe** [comment]
I see, you used it for the same reason we did but did not have the localization problem. 
Could you use the PowerApps Connectors table in your process to convert from logical name to display name? 
![image](https://user-images.githubusercontent.com/89584709/230386092-8ab93fc8-a227-407d-a64c-752349636530.png)
