### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Inactivity notifications v2 (Clean Up and Delete)-- Core Components

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5207]
### What is your question?

Hi,

Our employees received the below email for the app (Bulletins and Milestones) which was created in MS Teams.

![image](https://user-images.githubusercontent.com/126264610/230239442-f931cb93-7c8d-447b-b51e-27b2f0226508.png)

Why this flow couldn't able to delete this app?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Hello this is just a product limitation. We cannot delete flows that are part of a managed solution programmatically. The solution as a whole is managed as a single entity. We do have work planned to managed solutions in this feature area but its lower priority than some other work and so wont be released soon. 
Hope that helps.

**Comment by lingutla123** [comment]
Thank You. 

What is the process of deletion?

**Comment by Jenefer-Monroe** [comment]
For a teams envt, I usually go to the http://flow.microsoft.com/ ux to delete solutions. 
So http://flow.microsoft.com/ > Browse to the team > Solutions > Delete it
![image](https://user-images.githubusercontent.com/89584709/230398562-6a165bb2-56c8-4376-be24-e17daf456095.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
