### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE BYODL - Power Query Connector supported in GCC?

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5210]
### What is your question?

Hi,

I am updating COE starter kit with April release. While Importing Core Components it is asking CoE BYODL - Power Query to create a new connection. We are GCC Region. Is this available in GCC? With out this i can't proceed.

![image](https://user-images.githubusercontent.com/126264610/230377648-731839ff-2b62-4a9a-a33d-9ddef0b6e21b.png)

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
According to the documentation, it is supported yes
https://learn.microsoft.com/connectors/dataflows/
![image](https://user-images.githubusercontent.com/89584709/230381780-5e73d9a1-89a1-4d5b-9109-3e042e9feb93.png)

**Comment by lingutla123** [comment]
What is the use of this connection?

**Comment by Jenefer-Monroe** [comment]
We have just released an architectural option for the kit that uses the Data Export feature of the Power Platform Admin Center. It uses Dataflows to bring in the data to the CoE Dataverse tables and we need this connector to have flows that are triggered by the Dataflows. 

To my understanding that option isnt available quite yet in GCC so you wont be using the connector yet, but its part of the install now. 

Please see [Now in preview: CoE Starter Kit backed by data from self-serve analytics data export](https://powerapps.microsoft.com/blog/now-in-preview-coe-starter-kit-backed-by-data-from-self-serve-analytics-data-export/) and [What data source should I use for my Power Platform inventory?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory)

**Comment by lingutla123** [comment]
Thank you

**Comment by v7herman4** [comment]
> We have just released an architectural option for the kit that uses the Data Export feature of the Power Platform Admin Center. It uses Dataflows to bring in the data to the CoE Dataverse tables and we need this connector to have flows that are triggered by the Dataflows.
> 
> To my understanding that option isnt available quite yet in GCC so you wont be using the connector yet, but its part of the install now.
> 
> Please see [Now in preview: CoE Starter Kit backed by data from self-serve analytics data export](https://powerapps.microsoft.com/blog/now-in-preview-coe-starter-kit-backed-by-data-from-self-serve-analytics-data-export/) and [What data source should I use for my Power Platform inventory?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory)

**@Jenefer-Monroe is it still the case that BYODL is not yet available in GCC, GCC-H? Today is April 16, 2024.**

**Comment by v7herman4** [comment]
I found out that in order to get this to work we have to open up a support ticket. Trying to proof out this architecture now. If anyone has succeeded in installing the BYODL version of COE Toolkit successfully in GCC please let me know!

**Comment by mrmonto1** [comment]
Hello, was this ever resolved for configuring the DataFlows for CoE BYODL in the GCC? We are looking to move to the BYODL configuration as opposed to our current deployment with Cloud Flows.
