### ISSUE TITLE
[ALM Accelerator - BUG]: ALM Accelerator for Power Platform in GCC/Government environments

### ISSUE THREAD

**Issue by dpbnk** [microsoft/coe-starter-kit#5211]
### Describe the issue

The canvas app points to "make.powerapps.com" instead of "make.gcc.powerapps.us" in several places. This affects "Configure Deployment Settings" - at least when trying to setup connections for the downstream environments. I tried customizing the app by replacing with the correct URL. That opened the correct page to create the connection. However, after creating the connection, pressing the refresh icon or doing a browser refresh still did not populate the dropdown with the newly created connections. 

Not sure if there are other similar hardcoded values affecting the app. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Latest

**Comment by mikefactorial** [comment]
@dpbnk thanks for reporting this will look into if we can detect the portal url ahead of the redirect in the app. There shouldn't be anything blocking reading the connections. We're using the Power Apps for Makers connector GetConnections to read the connections in the environment. Does the user have Environment Maker permssions in the target environment?

**Comment by mikefactorial** [comment]
@dpbnk just a heads up @nasilvae has been submitting some questions related to GCC as well recently. We have not validated the ALM Accelerator in GCC or other sovereign clouds, but absolutely want to make sure that GCC is covered. Appreciate the feedback on where we might improve documentation or where there are gaps in functionality supporting GCC. For reference https://github.com/microsoft/coe-starter-kit/issues/5193

**Comment by rbmathis** [comment]
I also ran into a related issue with Gov.,  https://github.com/microsoft/coe-starter-kit/issues/5157#issuecomment-1492584810

**Comment by dpbnk** [comment]
@mikefactorial , 
1. The user has System Administrator permission.
2. The Power Apps for Makers connector GetConnections method works. What seems to be failing is the filtering based on the connectorid / customconnector id for the dropdown control.

**Comment by mikefactorial** [comment]
@dpbnk unfortunately we're not able to duplicate the issue you are experiencing as we don't test in GCC environments. If there's any more specifics, you can provide related to your assumption that the filtering of the connections is the issue or if you can track down the issue in the app please let us know. If not we'll likely close this issue as not reproducible.

**Comment by mikefactorial** [comment]
Closing this out as the threads gone stale.
