### ISSUE TITLE
[CoE Starter Kit - BUG] Get M365 Messages flow fails

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#5213]
### Describe the issue

Not sure what this means and what I should do to fix this:

![image](https://user-images.githubusercontent.com/117682988/230453462-552b52b4-13fc-4bbf-b240-ca86139a6301.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Command Center App > Get M365 Service Messages

**Comment by Jenefer-Monroe** [comment]
This flow fails if you don't have the configuration setup to get the M365 messages into the Admin Command Center
[Set up the CoE Admin Command Center App](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#set-up-the-coe-admin-command-center-app)

It looks like you got it to pass in the end, I presume by configuring it? 

Note that we happen to have made this easier to debug for the May release with some cleanup efforts we are doing.

**Comment by mdphung** [comment]
so the instructions say if you are using Azure key vault to leave it blank however I did that and I still did not get m365 messages. then I decided to go back and create the app registration for the Command Center Client Azure Secret value can not be null which value should I put here? If I put the value as the client secret id from the app registration.

**Comment by Jenefer-Monroe** [comment]
If you are using Azure Key Vault then you would store these two env vars.
![image](https://user-images.githubusercontent.com/89584709/230503130-eae01117-57c6-4405-91e7-463f679e44b5.png)

You get the **_Command Center - Application Client ID_** from the app registration
![image](https://user-images.githubusercontent.com/89584709/230503424-f09e04d4-ab9c-4c0f-8342-661bcea55034.png)

Then for **_Command Center - Client Azure Secret_**, after you put the secret in the key vault, and setup the key vault from that UX as shown here:
![image](https://user-images.githubusercontent.com/89584709/230504520-2085abd4-59cd-4b00-a88f-f122fcb81fcd.png)

![image](https://user-images.githubusercontent.com/89584709/230504794-2797f963-ad1a-4f39-a860-63b6ff7684e2.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
