### ISSUE TITLE
[CoE Starter Kit - QUESTION] COE Dashboard Blank After Updating

### ISSUE THREAD

**Issue by joebeyer75** [microsoft/coe-starter-kit#5215]
### What is your question?

Hello, 

We recently upgraded our COE environment with the April 2023 update. We had some issues with the Management API Custom Connector (had to delete and re-create), but have since resolved that and all flows appear to be running fine. When we browse to the Power Platform Admin View and when we open up the .pbix file with the download file, everything shows "Blank" or "No Data Available" 

I believe our network is preventing me from attaching screenshots here. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

Admin Dashboards

**Comment by Jenefer-Monroe** [comment]
Are you logging in with a different user perhaps? One that doesnt have the correct SR permissions?

**Comment by joebeyer75** [comment]
> Are you logging in with a different user perhaps? One that doesnt have the correct SR permissions?

No, same user account that installed/upgraded the COE. It's a service account with Power Platform Admin rights. It's only been an issue since upgrading COE to April.

**Comment by Jenefer-Monroe** [comment]
I'm not sure I will be able to do this without images but we can try. We have no processes that would delete all the data in your inventory, and I've never seen this happen, so I'm pretty stumped. 

Please do the following:
1. Browse to the Admin Command Center > Environment Variables > What is the value for this item? 
![image](https://user-images.githubusercontent.com/89584709/230621685-2f293271-b215-4f91-8234-0f39c8f638e9.png)

2. Browse to the Admin Command Center > CoE Flows Page > Inventory. When did this flow last run and did it pass? Click Flow details to browse to it. 
![image](https://user-images.githubusercontent.com/89584709/230622288-a392e38b-cabc-4cf9-849d-29491a22946b.png)

3. Open the most recent run. Does it make it down to this call? If so how many environments are returned? You can see this by popping it into a json parser.
![image](https://user-images.githubusercontent.com/89584709/230622587-e17a3ad2-e1d2-4d58-8a0c-255aa469359d.png)

**Comment by joebeyer75** [comment]
Hello,

Now that I can reply in email, I believe images will work. Here are the settings to the first question:

***@***.***

I am  not seeing the “Admin | Sync Template v3” specific flow. Only the same name with a solution after it.

***@***.***

Here are the screenshots of what I am seeing that I was not able to attach in the browser:

***@***.***

***@***.***

Thanks again!
Joe

From: Jenefer Monroe ***@***.***>
Sent: Friday, April 7, 2023 9:08 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Beyer, Joe ***@***.***>; Author ***@***.***>
Subject: {EXTERNAL} Re: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] COE Dashboard Blank After Updating (Issue #5215)


CAUTION: The message originated from an EXTERNAL SOURCE. Please use caution when opening attachments, clicking links or responding to this email.



I'm not sure I will be able to do this without images but we can try. We have no processes that would delete all the data in your inventory, and I've never seen this happen, so I'm pretty stumped.

Please do the following:

  1.  Browse to the Admin Command Center > Environment Variables > What is the value for this item?
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_89584709_230621685-2D2f293271-2Db215-2D4f91-2D8234-2D0f39c8f638e9.png&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=tsJYs7i4kyh9UTUtbFqzdJBe3dPdsLbQH18L5MsaN_c&m=knlas2-IyRzyHiYAWFQBUileTL6L9bDDwSwkmwBbiLOPmeF3nbQ3jXeptxiCgE2F&s=UjOHY3A7A9tZbWyCwWkU7bZoIqm1FXMOQhhExkhHA58&e=>
  2.  Browse to the Admin Command Center > CoE Flows Page > Inventory. When did this flow last run and did it pass? Click Flow details to browse to it.
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_89584709_230622288-2Da392e38b-2Dcabc-2D4cf9-2D849d-2D29491a22946b.png&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=tsJYs7i4kyh9UTUtbFqzdJBe3dPdsLbQH18L5MsaN_c&m=knlas2-IyRzyHiYAWFQBUileTL6L9bDDwSwkmwBbiLOPmeF3nbQ3jXeptxiCgE2F&s=TRi4LMnYTOLd5K9vWZpc_ErfZl8eeansRuAX6Hz7Zuk&e=>
  3.  Open the most recent run. Does it make it down to this call? If so how many environments are returned? You can see this by popping it into a json parser.
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_89584709_230622587-2De17a3ad2-2De1d2-2D4d58-2D8a0c-2D255aa469359d.png&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=tsJYs7i4kyh9UTUtbFqzdJBe3dPdsLbQH18L5MsaN_c&m=knlas2-IyRzyHiYAWFQBUileTL6L9bDDwSwkmwBbiLOPmeF3nbQ3jXeptxiCgE2F&s=dB-cMRdQd0GLkzcOw3XDDSwg-8gFIqQU7ZoSsv98VGA&e=>

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_coe-2Dstarter-2Dkit_issues_5215-23issuecomment-2D1500323816&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=tsJYs7i4kyh9UTUtbFqzdJBe3dPdsLbQH18L5MsaN_c&m=knlas2-IyRzyHiYAWFQBUileTL6L9bDDwSwkmwBbiLOPmeF3nbQ3jXeptxiCgE2F&s=JdLJp_6rQtq5DPzStDUX8oCCHADd6I9VCCLZJMLZq-8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AW5QLI2UHFKIH5FPNJEAYS3XAANVZANCNFSM6AAAAAAWV33TDQ&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=tsJYs7i4kyh9UTUtbFqzdJBe3dPdsLbQH18L5MsaN_c&m=knlas2-IyRzyHiYAWFQBUileTL6L9bDDwSwkmwBbiLOPmeF3nbQ3jXeptxiCgE2F&s=JniUkleKXLX7iIxOQTrWgimAednBIsCpw_Y0Q7YgPao&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

CONFIDENTIALITY NOTICE This e-mail message and any attachments are only for the use of the intended recipient and may contain information that is privileged, confidential or exempt from disclosure under applicable law. If you are not the intended recipient, any disclosure, distribution or other use of this e-mail message or attachments is prohibited. If you have received this e-mail message in error, please delete and notify the sender immediately. Thank you.

**Comment by joebeyer75** [comment]
> Hello, Now that I can reply in email, I believe images will work. Here are the settings to the first question: ***@***.*** I am not seeing the “Admin | Sync Template v3” specific flow. Only the same name with a solution after it. ***@***.*** Here are the screenshots of what I am seeing that I was not able to attach in the browser: ***@***.*** ***@***.*** Thanks again! Joe From: Jenefer Monroe ***@***.***> Sent: Friday, April 7, 2023 9:08 AM To: microsoft/coe-starter-kit ***@***.***> Cc: Beyer, Joe ***@***.***>; Author ***@***.***> Subject: {EXTERNAL} Re: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] COE Dashboard Blank After Updating (Issue #5215) CAUTION: The message originated from an EXTERNAL SOURCE. Please use caution when opening attachments, clicking links or responding to this email. I'm not sure I will be able to do this without images but we can try. We have no processes that would delete all the data in your inventory, and I've never seen this happen, so I'm pretty stumped. Please do the following: 1. Browse to the Admin Command Center > Environment Variables > What is the value for this item? [image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_89584709_230621685-2D2f293271-2Db215-2D4f91-2D8234-2D0f39c8f638e9.png&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=tsJYs7i4kyh9UTUtbFqzdJBe3dPdsLbQH18L5MsaN_c&m=knlas2-IyRzyHiYAWFQBUileTL6L9bDDwSwkmwBbiLOPmeF3nbQ3jXeptxiCgE2F&s=UjOHY3A7A9tZbWyCwWkU7bZoIqm1FXMOQhhExkhHA58&e=> 2. Browse to the Admin Command Center > CoE Flows Page > Inventory. When did this flow last run and did it pass? Click Flow details to browse to it. [image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_89584709_230622288-2Da392e38b-2Dcabc-2D4cf9-2D849d-2D29491a22946b.png&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=tsJYs7i4kyh9UTUtbFqzdJBe3dPdsLbQH18L5MsaN_c&m=knlas2-IyRzyHiYAWFQBUileTL6L9bDDwSwkmwBbiLOPmeF3nbQ3jXeptxiCgE2F&s=TRi4LMnYTOLd5K9vWZpc_ErfZl8eeansRuAX6Hz7Zuk&e=> 3. Open the most recent run. Does it make it down to this call? If so how many environments are returned? You can see this by popping it into a json parser. [image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_89584709_230622587-2De17a3ad2-2De1d2-2D4d58-2D8a0c-2D255aa469359d.png&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=tsJYs7i4kyh9UTUtbFqzdJBe3dPdsLbQH18L5MsaN_c&m=knlas2-IyRzyHiYAWFQBUileTL6L9bDDwSwkmwBbiLOPmeF3nbQ3jXeptxiCgE2F&s=dB-cMRdQd0GLkzcOw3XDDSwg-8gFIqQU7ZoSsv98VGA&e=> — Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_coe-2Dstarter-2Dkit_issues_5215-23issuecomment-2D1500323816&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=tsJYs7i4kyh9UTUtbFqzdJBe3dPdsLbQH18L5MsaN_c&m=knlas2-IyRzyHiYAWFQBUileTL6L9bDDwSwkmwBbiLOPmeF3nbQ3jXeptxiCgE2F&s=JdLJp_6rQtq5DPzStDUX8oCCHADd6I9VCCLZJMLZq-8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AW5QLI2UHFKIH5FPNJEAYS3XAANVZANCNFSM6AAAAAAWV33TDQ&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=tsJYs7i4kyh9UTUtbFqzdJBe3dPdsLbQH18L5MsaN_c&m=knlas2-IyRzyHiYAWFQBUileTL6L9bDDwSwkmwBbiLOPmeF3nbQ3jXeptxiCgE2F&s=JniUkleKXLX7iIxOQTrWgimAednBIsCpw_Y0Q7YgPao&e=>. You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>> CONFIDENTIALITY NOTICE This e-mail message and any attachments are only for the use of the intended recipient and may contain information that is privileged, confidential or exempt from disclosure under applicable law. If you are not the intended recipient, any disclosure, distribution or other use of this e-mail message or attachments is prohibited. If you have received this e-mail message in error, please delete and notify the sender immediately. Thank you.

![4](https://user-images.githubusercontent.com/96142755/230921335-a90a218f-abc5-4416-865a-b48924dcc185.png)
![3](https://user-images.githubusercontent.com/96142755/230921344-02a6e46a-14c3-475b-90b1-f7524411e00a.png)
![2](https://user-images.githubusercontent.com/96142755/230921346-2f465f74-1948-41ff-a124-8373865030ae.png)
![1](https://user-images.githubusercontent.com/96142755/230921350-9897e782-b4f4-48b9-ba28-51fc38072ada.png)

**Comment by Jenefer-Monroe** [comment]
ok I see. You set the system to be based on Data Export. Was that intentional?
Do you have the product's data export going? https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics
And if so, when did you turn it on? Did you follow the rest of the setup instructions to enable the data flows and such?

**Comment by joebeyer75** [comment]
> ok I see. You set the system to be based on Data Export. Was that intentional? Do you have the product's data export going? https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics And if so, when did you turn it on? Did you follow the rest of the setup instructions to enable the data flows and such?

I don't think we set that up purposefully if we did. Is that something outside of the COE? We were mainly just trying to set up the COE by default. Nothing special on top of that.

**Comment by Jenefer-Monroe** [comment]
OK so this is empty because the data is now looking to come from the Data Export. 
Here you can learn about the two data source architectures. https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory

Book the setup wizard app in Core. If you used it to setup before then you will not be started on the first page so select it by clicking back until you get there
![image](https://user-images.githubusercontent.com/89584709/230945995-707a9e83-3006-4d41-94cd-4c76284e3b3a.png)

Then walk the setup wizard by first acknowelding the dialogs you see, then clicking next till you get to this screen. 
Choose "Cloud Flows" as your data source and continue walking the rest of the setup wizard till the end
![image](https://user-images.githubusercontent.com/89584709/230946361-4d3a0dac-8e8d-46f8-b02a-38eff2f3be0c.png)

**Comment by joebeyer75** [comment]
> OK so this is empty because the data is now looking to come from the Data Export. Here you can learn about the two data source architectures. https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory
> 
> Book the setup wizard app in Core. If you used it to setup before then you will not be started on the first page so select it by clicking back until you get there ![image](https://user-images.githubusercontent.com/89584709/230945995-707a9e83-3006-4d41-94cd-4c76284e3b3a.png)
> 
> Then walk the setup wizard by first acknowelding the dialogs you see, then clicking next till you get to this screen. Choose "Cloud Flows" as your data source and continue walking the rest of the setup wizard till the end ![image](https://user-images.githubusercontent.com/89584709/230946361-4d3a0dac-8e8d-46f8-b02a-38eff2f3be0c.png)

Ok, thanks. That may have been selected by mistake. I've gone back through and updated that to Cloud Flows and progressed through the rest of the wizard again. Will it take some time for these updates to reflect on the dashboards? 

Thanks,
Joe

**Comment by joebeyer75** [comment]
> Yes they should be updated today. But please check that the correct flows are on now by going to the CoE Admin Command Center > CoE Flows > Inventory. Make sure all flows in this list are turned on. Then while you are there you can see when Admin | Sync Template v3 last ran, as that is what will populate your inventory. ![image](https://user-images.githubusercontent.com/89584709/231169765-12080d1c-8596-4c23-832a-346de8bd9422.png)

Hello, 

I think we are in a good spot now. The information has starting getting pulled in to the dashboards. Thanks again for the help!

Joe

**Comment by Jenefer-Monroe** [comment]
You are welcome! I will go ahead and close this out then, please let us know if you have more questions.
