### ISSUE TITLE
[CoE Starter Kit - Feature]: A search box on setup wizards to look for environments exempt from Compliance and Inactivity process

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5216]
### Is your feature request related to a problem? Please describe.

On Compliance setup wizard , have to scroll in case a lot of environments exists. So if we could have a search box would be great.
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/112712553/230585109-0fbd563c-a937-4315-975a-cd87a20f3db6.png">

### Describe the solution you'd like

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/112712553/230584647-aa5c789d-9ef1-4d96-a398-ee8927886d74.png">

**Comment by Jenefer-Monroe** [comment]
Great suggestion and well timed as we are doing a papercut fix up push on these apps for next month.

**Comment by manuelap-msft** [comment]
Fixed for May release


![Image](https://user-images.githubusercontent.com/55705669/233640702-0b594353-7003-4949-add8-8353b2482bbb.png)
