### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by echeng82** [microsoft/coe-starter-kit#522]
**Describe the bug**
Trying to import download CoEStarterKit.zip solution fails 

**To Reproduce**
1. Go to Power Platform Maker
2. Click on Solutions > Import 
3. Browse to file
4. Click Next
5. See Error

**Expected behavior**
Import successful

**Screenshots**

![image](https://user-images.githubusercontent.com/48643362/119831580-c3e04880-bf40-11eb-8407-b586667e9f1d.png)

**Additional context**
Tried in different environments across 2 tenants and experienced the same error.  Environment is a Production tenant with a database.

**Comment by manuelap-msft** [comment]
Hello,

the CoE Starter Kit consists of many solutions, as well as non-solution aware components like the Power BI dashboard. We ship it as one .zip file. You will have to extract the .zip file and that then contains the solution files that you can import, e.g. Core, Governance, Nurture files. 

Please follow our setup instructions closely to ensure a smooth install process!
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#option-1-import-the-solution-into-a-production-environment
![image](https://user-images.githubusercontent.com/55705669/119838459-56f68f80-befb-11eb-832a-2df5a5febccc.png)

Thanks for exploring the CoE Starter Kit
Manuela
