### ISSUE TITLE
[ALM Accelerator - Feature]: May Release Documentation

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#5227]
### Is your feature request related to a problem? Please describe.

Placeholder for May Release Documentation

### Describe the solution you'd like

1. Import to dev using deploy as unmanaged
 - Use new dev template
 - Recommend setting deployable to false
 - Updated pipelines to move data migration prior to flow activation
 - Bringing issues back to the top of the queue. Always feel free to ping an issue that's gotten lost
 - Add app user setup to maintenance tasks
 - Secure / Unsecure config updates for Plugins
 - Add deprecation or redirects to coe-cli

**Comment by sefa-phaag** [comment]
@mikefactorial Got it - that makes sense. Thanks!
