### ISSUE TITLE
[CoE Starter Kit - BUG] Office 365 Management API Connector Fails

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#5230]
### Describe the issue

Hello
When upgrading the CoE solution, it is always required to update this connector and it has always worked, however this time I am getting an Operation failed (401) when I test the List subscription
![image](https://user-images.githubusercontent.com/17124284/230767252-5200dc96-25de-4ce3-86ff-d0986551c1bb.png)

and the Schema validation error:
Property "" type mismatch, Expected: "array", Actual: "object".
![image](https://user-images.githubusercontent.com/17124284/230767283-662d96f2-49d7-41f3-8648-c7e136e2b6a7.png)

I have updated the Client ID and Client Secret and the Refresh URL (Documentation needs updating btw. It still says Resource URl :))

### Expected Behavior

a code 200 response

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Office 365 Management API Custom Connector

**Comment by medicineshow** [comment]
I notice that I am also getting this error if I try authorization using the Swagger editor:

The redirect URI 'blob:///oauth2-redirect.html' specified in the request does not match the redirect URIs configured for the application

**Comment by Jenefer-Monroe** [comment]
The default Identity Providor for the custom connector changed to Generic Oauth 2, so likely what happened is that you authenticated to a bad connection. Unfortunately this isnt obvious and clean up isnt that easy. 
![image](https://user-images.githubusercontent.com/89584709/225247140-70c99bb5-5770-428c-b45a-60c3f45e01dd.png)

I've outlined how to clean up from this here: [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

**Comment by medicineshow** [comment]
Ok that has fixed it thank you as always.

**Comment by Jenefer-Monroe** [comment]
You are so welcome! :)
