### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power BI

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5232]
### What is your question?

Hi,

After updating (April release)  COE starter Kit we are getting below error in Power BI.

![image](https://user-images.githubusercontent.com/126264610/230904185-30b7779a-9c74-444c-bdf6-5244deedac03.png)

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
Hello I I just double checked and it is there: 
![image](https://user-images.githubusercontent.com/89584709/230945269-d13c961d-84e4-4d8e-a323-88c729d3ba42.png)
