### ISSUE TITLE
[CoE Starter Kit - BUG] Weekly Digest not including Apps and Flows not being used

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#5234]
### Describe the issue

We have moved alot of our environments to 'Managed'. For the last 2 weeks, the email says 'there arent any apps' and 'there arent any flows'. 
I have "Excused" environments from Inventory, Inactivity etc. (see image below) just whilst i gradually implement some CoE processes.
can you confirm that this is the reason ? also what is the criteria it uses for the 'consider cleaning up'

### Expected Behavior

see the apps and flows not being used

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

core components 4.3.5

### What app or flow are you having the issue with?

None - weekly digest

### Anything else?

![mgd env](https://user-images.githubusercontent.com/78494876/230906187-a9d5d967-33ed-4ea8-af17-c2a0e21c8022.JPG)
![Capture](https://user-images.githubusercontent.com/78494876/230906816-596417fd-559f-47a1-932e-c9c8ab2f8380.JPG)

**Comment by manuelap-msft** [comment]
Hello,

Managed Environments and the CoE Starter Kit are two different feature sets/products, and they don't work together - settings in one won't impact the other.

Managed Environments is a product feature, it's fully supported and configurable from the admin center. It offers out of the box capabilities to govern your Power Platform adoption.
CoE Starter Kit is a reference implementation with templates for administering/governing Power Platform, it's something you install in your tenant and maintain/customize to your needs.

If you see issues with Managed Environments, we can't help with that - you'll need to raise a support ticket through your usual Microsoft support channels.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
