### ISSUE TITLE
[ALM Accelerator - QUESTION] App Registrations on Setup

### ISSUE THREAD

**Issue by Ryanb58** [microsoft/coe-starter-kit#5237]
### What is your question?

```
[9:51 AM] Taylor Brazelton
Internally the team I am working with has their own Power Platform tenant with the domain @roomsofthehouse.com where they are currently performing their development.

I'm not sure which account I should be using for the Azure AD App Registration. Is there any reason I should use my @microsoft vs my @roomsofthehouse credentials? And will that impact how my maker team logs into the ALM Accelerator power app?

[9:53 AM] Taylor Brazelton
I tried setting it up in my @microsoft account (in azure portal) but Grant Admin consent for (your tenant) was disabled when adding the permissions.

[9:54 AM] Taylor Brazelton
Wondering how big of a deal that would be to the overall setup of ALM Accelerator.
```

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

Latest

**Comment by mikefactorial** [comment]
@Ryanb58 unfortunately cross tenant isn't supported so the App registration would need to be in the @roomsofthehouse.com  tenant.

**Comment by mikefactorial** [comment]
@Ryanb58 btw we have some docs updates coming that might help with setup. There are a few gaps in the current documentation. Will update you when those go live

**Comment by mikefactorial** [comment]
@Ryanb58 Closing this out. Here is the documentation I mentioned above. https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#set-up-makers-to-use-the-alm-accelerator-for-power-platform-app
