### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inventory Active Environments

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#5239]
### What is your question?

Since the last update, I can see in COE that I have only 275 flows in the default environment, but in the admin centre, I have 1476 flows.
![image](https://user-images.githubusercontent.com/7468628/231073360-e1398775-c4a4-437c-a195-34d15bfc713f.png)
![image](https://user-images.githubusercontent.com/7468628/231073404-d11500ea-2580-4400-893e-8b13258b2f68.png)

I have extracted the list of all flows using PowerShell and the correct number is 1476

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

Admin - Sync Template v3

**Comment by ClaudiuVio** [comment]
The number of Apps is not impacted.

**Comment by manuelap-msft** [comment]
Can you check if the Admin - Sync Template v3 (Flows) is failing? You can do that by opening the CoE Admin Command Center app and checking the Sync Flows page for any failures.

**Comment by ClaudiuVio** [comment]
Nope, everything is OK.

The last failed sync flow was [Child] Admin | Sync Logs when the update was done.

![image](https://user-images.githubusercontent.com/7468628/231137417-24daaa6b-fb15-426d-94f3-350373bfdb4e.png)

**Comment by Jenefer-Monroe** [comment]
Can you please check on the value for this env var? 
![image](https://user-images.githubusercontent.com/89584709/231170903-cb14ed81-c4eb-48e8-be66-162eddcc8fb8.png)

**Comment by ClaudiuVio** [comment]
![image](https://user-images.githubusercontent.com/7468628/231347982-51df585d-3d3a-4bd3-8f54-69e68306ebfd.png)

**Comment by Jenefer-Monroe** [comment]
You will need to find a repro of this in your tenant to see what is going wrong. 
1. Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)
- Looks like you already have one here, the default envt

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you are looking for missing canvas apps chose **_Admin | Sync Template v3 (Apps)_**
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

5. From here you can explore if there is a failure, or if a bad return set, etc. And let us know if you have questions

**Comment by ClaudiuVio** [comment]
I did this, and now the syncs are running.

![image](https://user-images.githubusercontent.com/7468628/231464023-75646079-2837-4286-a2b4-c68d87235223.png)

**Comment by ClaudiuVio** [comment]
The exact 3 runs that started after the actions requested failed.

![image](https://user-images.githubusercontent.com/7468628/231647498-5f321923-af88-4ba0-88fd-d1a8bf8e21ad.png)

Message error: 
![image](https://user-images.githubusercontent.com/7468628/231647687-3325ef05-817c-4e9b-9087-9acda1139ab7.png)

NOTE:  All the other runs that started after this are successful.

![image](https://user-images.githubusercontent.com/7468628/231647955-56cfd8da-8777-4d42-b887-7a2395dae3a1.png)

![image](https://user-images.githubusercontent.com/7468628/231648037-71e519df-d409-42dc-bb86-703f48feabaa.png)

**Comment by ClaudiuVio** [comment]
This issue occurs only on the Default env, for the others environments number of the flows is correct.

**Comment by Jenefer-Monroe** [comment]
Please note that failures like this "flow does not exist" are caught/expected failures. You will need to open the flow run and find the terminating failure

The first failure that is giving the message: 
We use these calls to see if the object is new to the inventory, and if it is, this call to “get it” will fail. This failure is caught and the “isnew” variable is set to true. 
![image](https://user-images.githubusercontent.com/89584709/225679681-01467de5-1a1c-4c93-bf57-71296f5ea83b.png)

Please find terminating failure:
In order to debug you need to find the terminating failure in the flow. Here for example the call to “forced failure” failed, and was not caught, so the flow terminated here. That is the spot you need to find in your failure in order to debug. 
![image](https://user-images.githubusercontent.com/89584709/225681214-a5549790-32e9-482e-b427-0c346aa50684.png)

**Comment by ClaudiuVio** [comment]
![image](https://user-images.githubusercontent.com/7468628/232685535-f408c2d5-3c96-4dab-893a-3e69b6cf8a2c.png)
![image](https://user-images.githubusercontent.com/7468628/232685736-f76b79ea-e797-4800-bcc1-bd2372cc391f.png)

All the failed ones are with this text :

"A record with matching key values already exists."

**Comment by ClaudiuVio** [comment]
![image](https://user-images.githubusercontent.com/7468628/232689435-b9ba8f2f-67f7-42d7-9f3e-25cffaf62f99.png)

**Comment by ClaudiuVio** [comment]
This morning I have this.

![image](https://user-images.githubusercontent.com/7468628/233263444-b8fceab5-8b08-4971-871d-5018d1cc97ba.png)

**Comment by Jenefer-Monroe** [comment]
Can you please open the flow in edit mode and show me what you see here? 
![image](https://user-images.githubusercontent.com/89584709/233849859-147faeee-7275-48a1-804d-b66b449d2372.png)

If it does not look like this, then you probably have an unmanaged layer on the flow that needs removed.

**Comment by ClaudiuVio** [comment]
![image](https://user-images.githubusercontent.com/7468628/233931381-e5a8e00e-9377-4d47-9645-01b60b447013.png)

I have checked all the inventory flows for the unmanaged solution layer.

![image](https://user-images.githubusercontent.com/7468628/233931596-5a77392e-8c7e-42d0-9ed7-6904fecff315.png)

![image](https://user-images.githubusercontent.com/7468628/233932570-ce328f42-3d0c-4353-9d58-5fa1fd4be245.png)


After the last update, the flows disappeared.

**Comment by Jenefer-Monroe** [comment]
The flows disappearing might be a separate issue from this individual failure. Please see https://github.com/microsoft/coe-starter-kit/issues/5331. We are preparing a hotfix for that. 

Lets see your state after importing the hotfix solution.

**Comment by ClaudiuVio** [comment]
Sure, the Sync is working.

**Comment by ClaudiuVio** [comment]
The Flow admin finished their work , all the new flows are added but the one that disappeared are not back in the FLOWS list.

**Comment by Jenefer-Monroe** [comment]
We are working to make this better in May, but for now you will need to do a full inventory to get them back. 
Please see https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory

**Comment by ClaudiuVio** [comment]
@Jenefer-Monroe  Thank you , all the flows are back.

**Comment by Jenefer-Monroe** [comment]
Wonderful, thank you. Sorry for the bother!
