### ISSUE TITLE
[CoE Starter Kit - QUESTION] Maker persona

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#5240]
### What is your question?

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users

I have a question about persona.
Currently, we do not intend to make the CoE Starter Kit available to other users; we plan to view and manage it with only one account.
In that case, would it be unnecessary to set up these personas?
For example, will I no longer need to configure them in the setup wizard shown below?

![image](https://user-images.githubusercontent.com/91306350/231079228-cd4df6b9-a6cc-477b-87f8-4e0f35375314.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53

**Comment by manuelap-msft** [comment]
Hello,

certain flows will not work if these groups are not configured - for example, as part of app/flow inventory we add makers to the Maker persona security group so some of the inventory flows would fail if the group wasn't configured. For the user persona group, this is used by the flow that would share apps with users (in the Share apps stage of the setup wizard if you click on the Share All button) so you could set this to an empty group if you do not intend to use that. 

So you can choose to not use the groups for anything, but you'll have to configure them.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
