### ISSUE TITLE
[CoE Starter Kit - QUESTION] Advise Audit Log connector set up 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#5241]
### What is your question?

**To set Audit log connectors** 

In order to set up 
1.  App registration key generated
2. Enable audit log search in Microsoft purview 
3.  Set up Custom connector and deploying solutions 

do we need to use same user identity for everything ?as per the article we need higher privilege's .
because ,In our org we were given power platform admin but not global admin privilege's.

(If we request set up app keys and enable audit search  global admins create and give them to )

my question is 
if we use global admin another account to enable Audit log in Microsoft Purview and App registration keys 
If we use another account for audit log set up (Importing solutions and setting up custom connector) 

In this way we can go and install and make it work without any issues.

Please suggest

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

4.3

**Comment by manuelap-msft** [comment]
You don't need to use the same identity for all the setup steps. A Global Admin could enable Audit Log search and create the App registration, then share the client id/client secret with the Power Platform admin to complete the setup of the custom connector.

**Comment by pamatihyd** [comment]
we have followed the same  Global Admin team created APP Registration Shared with us 

we followed every step as is from the article , we are getting the below error 

The request failed with error: '{"error":{"code":"0x80060888","message":"Edm Object passed should have the options selected. "}}'. The correlation Id is 'de68a6d7-180f-4e43-9cb9-ce53c926a7e2'.

any persmissions I am missing

**Comment by manuelap-msft** [comment]
Hello,

this issue seems to be unrelated to permissions, but related to a possible product change with custom connectors. We've seen a few customers report this since yesterday, but are still investigating what's causing this.

**Comment by pamatihyd** [comment]
Oh okay, thank you for quick response  but already configured custom connectors are working.
 but now when we are trying to set up new one we are getting this issue. 
 
 Thank you will await for resolution from your end . 
Is there anything we have to do to resolve this from our end please let me know

**Comment by Jenefer-Monroe** [comment]
Another customer hit this recently and it went away on its own, some intermittent or reverted product issue.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
