### ISSUE TITLE
[ALM Accelerator - BUG]:Receiving prompt to "select an existing project that is empty" in project wizard

### ISSUE THREAD

**Issue by challa85** [microsoft/coe-starter-kit#5243]
### Describe the issue

Hi Team,

We have been receiving a prompt to "select an existing project that is empty" in the project wizard (under ALM Accelerator for Power Platform Administration app), although we selected the project which is empty and doesn't have any pipelines.

Thanks
Srikrishna Ch

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

CenterofExcellenceALMAccelerator_1.0.20230404.2_managed

**Comment by mikefactorial** [comment]
@challa85 thanks for reporting this. Will look into making this experience better. Would be ideal if existing projects could be initialized in addition to the issue you're reporting.

**Comment by RajeevPentyala** [comment]
@challa85 Please be advised that we are unable to accommodate the requested changes at this time, unless we receive similar feedback from other users.

However, As a proactive measure, we will be adding more descriptive information on the application screen which helps users while picking up a blank project.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/b5492a1b-0154-4be4-938a-324c20ba0c5d)

FYI @mikefactorial @jenschristianschroder
