### ISSUE TITLE
Unable to load April BYOD Power BI

### ISSUE THREAD

**Issue by andrewgaskins** [microsoft/coe-starter-kit#5244]
### Describe the issue

When brining up the BYODL Power BI report for April I am getting blocking calls. The most recent I see is byod_environments
The column 'createdPrincipalId' of the table wasn't found. I have updated the data flows and they are executing correctly and have the correct GUIDs and workspace address. I have looked at the individual calls and can't seem to find the blocking point. 

I looked at previous issues around this but the resolution didn't work for me since I am using the latest release.

Thanks!

### Expected Behavior

Expect April BYODL Power BI report to load with queries in order to publish new version to workspace. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4

### What app or flow are you having the issue with?

BYODL_CoEDashboard_April2023.pbit

### Steps To Reproduce

1. Open PBI Desktop
2. Open BYODL_CoEDashboard_April2023.pbit
3. Input workspace url with and without trailing '/'
4. Input workspace and dataflow GUID
5. Enter and wait for queries to refresh
 
CoE Starter Kit Environment
Loading blocked by failures with other queries.
Connector
Loading blocked by failures with other queries.
Flow Action Details
Loading blocked by failures with other queries.
NonProdWords
Loading blocked by failures with other queries.
Virtual Agent
Loading blocked by failures with other queries.
Virtual Agent Component
Loading blocked by failures with other queries.
Virtual Agent Flows
Loading blocked by failures with other queries.
RPA
Loading blocked by failures with other queries.
RPA Sessions
Loading blocked by failures with other queries.
Power Platform User
Loading blocked by failures with other queries.
Portals
Loading blocked by failures with other queries.
Environment Capacity
Loading blocked by failures with other queries.
byod_apps
Loading blocked by failures with other queries.
byod_connectionreference
The key didn't match any rows in the table.
byod_environments
The column 'createdPrincipalId' of the table wasn't found.
byod_usage
Loading blocked by failures with other queries.
byod_flowconnectionreference
The key didn't match any rows in the table.
byod_flows
Loading blocked by failures with other queries.
byod_flowusage
Loading blocked by failures with other queries.
Business Process Flows
Loading blocked by failures with other queries.
Solutions
Loading blocked by failures with other queries.
Soltion_Apps
Loading blocked by failures with other queries.
Soltion_BPFs
Loading blocked by failures with other queries.
Soltion_Flows
Loading blocked by failures with other queries.
Makers
Loading blocked by failures with other queries.
8.

**Comment by Jenefer-Monroe** [comment]
Thanks for posting
1. Can you please see what version of PBI you are using? 
![image](https://user-images.githubusercontent.com/89584709/231205295-5d16482c-7e10-4272-9b29-9be0fa0f3d01.png)
2. Did you enter the environment URL including the prefix like this? https://orga111a1a1.crm.dynamics.com/

**Comment by andrewgaskins** [comment]
I tried that as well and still getting the errors. If I go into the editor I am seeing errors in the following:

byod_ConnectionReference
Expression.Error: The column 'connectorSharedName' of the table wasn't found.
Details:
    connectorSharedName

byod_Environments
Expression.Error: The column 'createdPrincipalId' of the table wasn't found.
Details:
    createdPrincipalId

byod_connectionreference
Expression.Error: The key didn't match any rows in the table.
Details:
    Key=
        entity=Flow Connections
    Table=[Table]

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by andrewgaskins** [comment]
Thanks Jenefer, does this help?

<img width="1314" alt="Screenshot 2023-04-17 at 6 00 37 PM" src="https://user-images.githubusercontent.com/11320569/232635861-d2d0a841-ac32-4924-be06-ce593a4476bc.png">

**Comment by andrewgaskins** [comment]
I do see a failure for 4.2 uninstall but can't find it at all. Looking at classic mode as well and I don't see anything either. 
![image](https://user-images.githubusercontent.com/11320569/234726890-c1ca0e4f-9825-483a-b164-cbb3de3af7f4.png)

<img width="803" alt="image" src="https://user-images.githubusercontent.com/11320569/234726442-0c993c9b-d5f8-4817-a6da-801a77191b0a.png">

**Comment by Jenefer-Monroe** [comment]
A failure back in 4.2 should not be related since its not showing up anymore in the solution list. Probably a timeout or something.

I'm really not sure what could be happening here. This loads for other folks. Maybe there is something wrong with your Data Export. Can you please browse to your storage account > containers > powerplatform > powerapps > environments 

Look at environments.json file and look for createdPrincipalId. Do you have it in your file? 
![image](https://user-images.githubusercontent.com/89584709/234886277-33e2939f-cabf-4a52-873c-804f3661cee1.png)

**Comment by andrewgaskins** [comment]
Thanks for your help on this @Jenefer-Monroe I looked and createdPrincipal is in there and the dataflow is getting it but what I see is that when the dataflow is called in the PBI it is getting createdBy instead of createdPrincipal when it creates the table in the navigation step. 
<img width="915" alt="image" src="https://user-images.githubusercontent.com/11320569/234940478-de74060b-05b9-4aee-a528-8aeb2e295425.png">

**Comment by Jenefer-Monroe** [comment]
Do you see createdPrinciple, or createdPrincipleId in your Datalake? 
I see the following in the PBI data tranformations. Is this where you are looking? 
![image](https://user-images.githubusercontent.com/89584709/234953710-71e91f4d-8759-4163-9e97-fb233aebe9ca.png)

**Comment by andrewgaskins** [comment]
It looks like quite a few columns are off from yours. 
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/11320569/234956600-39425716-2359-41e9-b423-5980789349c5.png">

**Comment by andrewgaskins** [comment]
Sorry I also meant to add that yes I do see createdPrincipalID in both the data lake JSON and the Data Flow.

**Comment by andrewgaskins** [comment]
I am also seeing this in the transformation 
Table.RenameColumns(#"Changed column type", {{"cdsInstanceId", "cdsMetadataName"}, {"createdTime", "createdOn"}, {"createdPrincipalId", "createdBy"}, {"lastModifiedTime", "lastModifiedOn"}, {"lastModifiedPrincipalId", "lastModifiedBy"}, {"deletedTime", "deletedOn"}, {"tenantGuid", "tenantId"}})

**Comment by Jenefer-Monroe** [comment]
ok ill need to have our area expert take a look. Thank you

**Comment by Jenefer-Monroe** [comment]
Wondeful news. Thank you so much for letting us know! I'll go ahead and close out then.
