### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 - fail to get organization id

### ISSUE THREAD

**Issue by peteredc** [microsoft/coe-starter-kit#5246]
### Describe the issue

Admin | Sync Template v3 fails on some environments with Action 'Get_organization' failed.

![image](https://user-images.githubusercontent.com/93291159/231251687-f9ec7a5f-1c78-4ddc-ae23-8c897ee87ba9.png)

### Expected Behavior

Environments are processed without org errors, as there is no obvious reason for the issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. We have this one local fixed for May by this issue: https://github.com/microsoft/coe-starter-kit/issues/5197

If this is blocking you, you an delete this part of the flow, and then remove the unmanaged layer that is created when you install the May release
![image](https://user-images.githubusercontent.com/89584709/231277266-625d3955-c5b2-42e7-83f5-b5cd62d6367a.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by ethan-hurst** [comment]
Hi All, 

Just did this install for a customer. This issue is still present in 4.4.2

**Comment by Jenefer-Monroe** [comment]
4.4.2 was a hotfix for April that only contained one fix. This bug was fixed with the May release which was just shipped yesterday. It is Core 4.7

**Comment by srijapam1985** [comment]
After installing the latest package I cannot see the flow with the name **Admin | Sync Template v3**, does it get renamed, if yes can you let me know the name of the flow? I want to run this flow as I installed the CoE kit for the first time.

**Comment by Jenefer-Monroe** [comment]
Hello. If you use the setup wizard to install / upgrade then all of these details will be covered for you. 
**_Admin | Sync Template v3_** was renamed to **_Admin | Sync Template v3 (Driver)_**

For order, manually you would need to refer to the documentation and see the order there. But its not up to date yet so I'll paste it here for you. 
SetupWizard>CreateGroup
SetupWizard>GetCurrentEnvironment
SetupWizard>GetTenantID
SetupWizard>GetUserDetails
Admin | Sync Template v3 (Connectors)
Admin | Sync Template v3 CoE Solution Metadata
Admin | Sync Template v3 Configure Emails
SetupWizard>RunInitialFlows
SetupWizard>UpdateInventoryTypeAppSetting
HELPER - Send Email
HELPER - Maker Check
HELPER - CloudFlowOperations
HELPER - CanvasAppOperations
HELPER - ObjectOperations
HELPER - Add User to Security Role
SetupWizard>CallOrphanFlow
SetupWizard>ShareApps
SYNC HELPER - Apps
SYNC HELPER - Cloud Flows
SYNC HELPER - Get Security Role Users
CLEANUP HELPER - Check Deleted (Ai Models)
CLEANUP HELPER - Check Deleted (Business Process Flows)
CLEANUP HELPER - Check Deleted (Canvas Apps)
CLEANUP HELPER - Check Deleted (Cloud Flows)
CLEANUP HELPER - Check Deleted (Custom Connectors)
CLEANUP HELPER - Check Deleted (Model Driven Apps)
CLEANUP HELPER - Check Deleted (PVA)
CLEANUP HELPER - Check Deleted (Solutions)
CLEANUP HELPER - Power Apps User Shared With
Admin | Add Maker to Group
Admin | Excuse Non Inventoried Envts from Governance Flows
Admin | Excuse Support Envts from Governance Flows
Command Center App >  Get M365 Service Messages
Command Center App > Initially Populate Bookmarks
Command Center App > Set CoE Flows State
DLP Editor>Parse impacted resources into CSV
Admin | Sync Template v3 (Ai Models)
Admin | Sync Template v3 (Business Process Flows)
Admin | Sync Template v3 (Connection Identities)
Admin | Sync Template v3 (Custom Connectors)
Admin | Sync Template v3 (Desktop Flow - Runs)
Admin | Sync Template v3 (Desktop flows)
Admin | Sync Template v3 (Environment Properties)
Admin | Sync Template v3 (Model Driven Apps)
Admin | Sync Template v3 (Portals)
Admin | Sync Template v3 (PVA Usage)
Admin | Sync Template v3 (PVA)
Admin | Sync Template v3 (Solutions)
Admin | Sync Template v3 (Sync Flow Errors)
Admin | Sync Template v4 (Apps)
Admin | Sync Template v4 (Flows)
Admin | Sync Template v3 (Call Updates)
Admin | Sync Template v3 (Flow Action Details)
Admin | Sync Template v3 (Driver)
CLEANUP - Admin | Sync Template v3 (Check Deleted)
CLEANUP - Admin | Sync Template v3 (Delete Bad Data)
CLEANUP - Admin | Sync Template v3 (Orphaned Makers)
CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
CLEANUP - Admin | Sync Template v3 (PVA Usage)

**Comment by srijapam1985** [comment]
Thank you very much, Jenefer.

Regards,
Srini
