### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by CarlosGMata** [microsoft/coe-starter-kit#5247]
### What is your question?

Hi.

We are having problems with Center of Excellence - Core Components, We are getting these type of errors:

- Admin | Sync Template v3 (PVA)

Request to Azure Resource Manager failed with error: '{"error":{"code":"WorkflowTriggerHistoryNotFound","message":"The workflow '569a0903-b617-f67b-828b-ff0c6c78fefb' trigger 'When_a_record_is_created_or_updated' history '08585264688633340286872861979CU29' could not be found."}}'.

- Admin | Sync Template v3 (Flows)

Request to Azure Resource Manager failed with error: '{"error":{"code":"WorkflowTriggerHistoryNotFound","message":"The workflow 'd9692173-5d97-95bf-65a0-7476e6935635' trigger 'When_a_record_is_created_or_updated' history '08585264673368667253543521581CU181' could not be found."}}'.

- Admin | Sync Template v3 (Apps)

Request to Azure Resource Manager failed with error: '{"error":{"code":"WorkflowTriggerHistoryNotFound","message":"The workflow '591cba51-bfb8-3e88-eba9-492fd797db57' trigger 'When_a_record_is_created_or_updated' history '08585264678802047993591805395CU109' could not be found."}}'.

We deployed CoE Starter Kit Friday April 09 version 2.0.

![image](https://user-images.githubusercontent.com/90932255/231275283-4e15cefa-1d29-4adb-afcb-6ba3742b9abc.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Fri Apr 09 2021 2.0

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA), Admin | Sync Template v3 (Flows), Admin | Sync Template v3 (Apps)

**Comment by Jenefer-Monroe** [comment]
Hello. I'm a little lost on your version. 

Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names. 

![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by CarlosGMata** [comment]
Hi Jenefer, thanks for your help.

Here the screnshot:

![image](https://user-images.githubusercontent.com/90932255/231303956-d4379890-b9ae-434c-b3d0-06a7e117b436.png)

**Comment by Jenefer-Monroe** [comment]
Oh i see. I assumed version 2.0 was a typo haha. :) 
I wont be able to help you here if there is anything wrong with the flows as your version is so old, but the error messages do sound like the connections may have just broken. Can you see if they are broken and if so fix them up? 
![image](https://user-images.githubusercontent.com/89584709/231310098-3b6da1c0-7d6f-4427-a9a7-68b78f7e21ab.png)

**Comment by CarlosGMata** [comment]
It is correct, the version is so old jeje, do you recommend that we should update the CoE Starter Kit to solve the errors in the flows? I have checked the connections and they are not broken, the problem with flows is that sometimes they fail and sometimes they don't, recently We created a support ticket with Microsoft and they told us the error is probably because of the version of the CoE uses the legacy dataverse connector and that connector is deprecated.

**Comment by Jenefer-Monroe** [comment]
The old connector is not yet deprecated, and is still used. There are a few features left to migrate to the new connector so the old one is still supported by the product team. You may want to give them that feedback. 

But yes, you should upgrade and we have a forced upgrade coming in a few months. 

It is very unlikely that you will be able to upgrade from that old of an install though. If all you are using us for in inventory, you will be better served starting from scratch either in a new envt or by first deleting Core and installing again.

**Comment by CarlosGMata** [comment]
Hello Jennifer.
I understand, I appreciate all your comments, we are going to review what is the best scenario to update the solution.
Thanks!
