### ISSUE TITLE
[CoE Starter Kit - QUESTION] Do I need to import all the solutions when doing an upgrade?

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5248]
### What is your question?

Hello,

I just updated the "Center of Excellence - Core Components" solution 
(CenterofExcellenceCoreComponents_4.4_managed.zip) 
and the "Center of Excellence - Governance Components" solution 
(CenterofExcellenceAuditComponents_3.8_managed.zip).

Do I need to import (upgrade) these other solutions as well:

- admintaskanalysis_core_1_2_managed.zip
- CenterofExcellenceALMAccelerator_1.0.20230404.2_managed.zip
- CenterofExcellenceAuditLogs_3.3_managed.zip
- CenterofExcellenceInnovationBacklog_3.1_managed.zip
- CenterofExcellenceNurtureComponents_3.4_managed.zip

Attached is a screenshot of my "Solutions" list.
Note: I did Not set up the audit log connector yet, but will want to do that next week.

![coe-solutions-list](https://user-images.githubusercontent.com/128085471/231281796-a0c73567-7b58-4930-8e2b-5ec918fcf4ec.png)

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
We do not always reship every solution, so you should compare the version you have installed with what is in the release. If the number is the same then you do not need to upgrade it. 

Then its best practice to always update the versions together, so you have all the "April bits" installed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
