### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE BYODL - When App dataflow refresh is complete

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#5251]
### What is your question?

We are getting Trigger condition error (The trigger is invalid) for the flows which are used to push the data to Dataverse tables from Azure Data lake.

Could you please let us know if we missed something?

All the data flows are up and running. 

Also, the environment variables showing the correct values. 

This error happening with all COE BYODL flows. 

![image](https://user-images.githubusercontent.com/130560248/231440088-a294d024-1146-421b-a9d9-1946946bd121.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.41

### What app or flow are you having the issue with?

CoE BYODL - When App dataflow refresh is complete

**Comment by Jenefer-Monroe** [comment]
Hello. 
1. Did you setup using the Setup Wizard?

2. When you say all env variables are set can you confirm, both these are set:
![image](https://user-images.githubusercontent.com/89584709/231454122-4246be17-f692-422b-980a-a65720798923.png)

3. As well as this one is set? Does it have the -region thing at the end? 
![image](https://user-images.githubusercontent.com/89584709/231453805-9013f349-0e0c-437f-b3dc-8a044753af66.png)

**Comment by devvelegandla** [comment]
All good @Jenefer-Monroe 

Thanks
