### ISSUE TITLE
[ALM Accelerator - BUG]: Stuck on Getting Solution Dependencies

### ISSUE THREAD

**Issue by orjsol** [microsoft/coe-starter-kit#5252]
### Describe the issue

When trying to configure deployment settings, it will get stuck in "GETTING SOLUTION DEPENDENCIES...".
![image](https://user-images.githubusercontent.com/52534802/231448900-ab8ab96f-0e1d-42d5-867e-9031ab812313.png)

It's just stuck in this screen and won't show the actual dependencies.

### Expected Behavior

I should be able to configure the dependencies for the environments where the app will be deployed.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230308.1

### Steps To Reproduce

1. Select a solution and a profile
2. Click on "Configure Deployment Settings"

### Anything else?

Could this be related to security roles in the environments
How should the security roles be set up for makers?

Environments:
dev - "Environment Maker"
test - "Basic User"
Prod - "Basic User"

On https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-users
it says:
Configure the deployment settings
Basic User
If the logged-in user needs to create/list connections, list "Teams" for sharing in "Flows", and list of "Teams" to share in "Custom connector" the user will need a "Basic user" role in the corresponding environment, otherwise no permission is needed

Have also set "Deployment Configuration" to allowed.

![image](https://user-images.githubusercontent.com/52534802/231449667-af376ef9-09d7-4043-b01f-f84cbd802dae.png)

**Comment by miguelverweij** [comment]
I have the same issue all of a sudden. It used to work for me before

**Comment by orjsol** [comment]
Looks like it is working when you give the user "Environment Maker" in deployment environment. Like Test & Prod. But I don't think that this is a good idea since maker shouldn't have the opportunity to make changes in those environments..

**Comment by mikefactorial** [comment]
@orjsol Environment Maker permissions are required currently in downstream environments. Unfortunately, there's no OOB role that can be used with the ALM Accelerator with least or lesser permissions. This is something we're aware and are working with the product team on but don't have any control over currently. This is called out in the documentation here https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-app-user-permissions#permissions-for-downstream-environments

**Comment by mikefactorial** [comment]
@miguelverweij if you've recently upgraded we have seen this behavior immediately after upgrade and tends to resolve itself after a little while or when switching over to an in private session in the browser.

**Comment by mikefactorial** [comment]
@orjsol will need to look into this again as previously configuring deployment settings only required Basic User. It's possible something in the platform or in the accelerator changed that is requiring Environment Maker.

**Comment by miguelverweij** [comment]
@mikefactorial I've upgraded a few weeks ago. That's when I made the comment.  I am in a call atm to onboard a new ALM user, but the same error occurs to this new user. The supporting flows are not triggered somehow. I hope this is useful input.

**Comment by miguelverweij** [comment]
As @orjsol mentioned, adding the Environment Maker role isn't ideal, but this did resolve it for now.

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more we can do for this issue until the platform makes it possible to use least privelege.
