### ISSUE TITLE
[CoE Starter Kit - QUESTION] Invalid token when testing Office 365 Management API

### ISSUE THREAD

**Issue by EmpbPowerAdmin** [microsoft/coe-starter-kit#5253]
### What is your question?

Using 365 management API app reg I created,

![image](https://user-images.githubusercontent.com/129513320/231453937-07e2663d-5675-4e1b-9b0a-c013594b5b93.png)

I put the correct inputs in as per documentation.  
The custom connector is added to the DLP policy for the CoE environment

![image](https://user-images.githubusercontent.com/129513320/231454617-d82f89f7-3906-41fb-acb8-aa20f6d95e1c.png)

Here is the error message... I've checked and reinput the tenant ID, appid, secret value, I'm 100% I'm entering the correct values, not sure why it is saying invalid token.  Please let me know what I'm doing incorrectly

![image](https://user-images.githubusercontent.com/129513320/231453499-e1aee529-0cea-415c-8587-676f8c1b474f.png)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Most recent release

### What app or flow are you having the issue with?

Testing Office 365 Management API

**Comment by EmpbPowerAdmin** [comment]
Worked, thank you!

**Comment by Jenefer-Monroe** [comment]
wonderful, ill go ahead and close then but do let us know if you need anything else!
