### ISSUE TITLE
[CoE Starter Kit - BUG] App forbidden - COE Setup and Upgrade Wizard 

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#5255]
### Describe the issue

Hi,
I've upgraded the COE solution yesterday. All works fine until now but i' ve an issue with the COE Setup and upgrade wizard that says AppsForbiden 

"It looks like this app isn't compliant with the latest data loss prevention policies.
UciError: It looks like this app isn't compliant with the latest data loss prevention policies. at s (https://org8e2b571b.crm3.dynamics.com/uclient/scripts/app.js?v=1.4.5498-2303.4:33:895291) at https://org8e2b571b.crm3.dynamics.com/uclient/scripts/custompage.js?v=1.4.5498-2303.4:4:27117"
<img width="879" alt="Capture d'écran 2023-04-12 083807" src="https://user-images.githubusercontent.com/10110260/231459819-0e6a8b80-9fdc-44bc-bbc1-b40ca13451d9.png">

From the authorize app, do you add new connectors that i need to autorize in my DLP policies for my COE environment ?

### Expected Behavior

Hi,
I've upgraded the COE solution yesterday. All works fine until now but i' ve an issue with the COE Setup and upgrade wizard that says AppsForbiden 

"It looks like this app isn't compliant with the latest data loss prevention policies.
UciError: It looks like this app isn't compliant with the latest data loss prevention policies. at s (https://org8e2b571b.crm3.dynamics.com/uclient/scripts/app.js?v=1.4.5498-2303.4:33:895291) at https://org8e2b571b.crm3.dynamics.com/uclient/scripts/custompage.js?v=1.4.5498-2303.4:4:27117"

From the previous app, do you add new connectors that i need to add in my DLP policies for my COE environment ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

COE Setup and upgrade wizard

### Steps To Reproduce

1. Open the app

**Comment by manuelap-msft** [comment]
We've added the PowerQuery connector with the latest release, so you'll have to update your DLP policy to include that. Note, you can always find our latest required DLP requirements in our documentation: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

**Comment by tocri** [comment]
Thank you for the quick reply @manuelap-msft. 

I've added the connector to buisness compartiment. After 20 minutes, the error was still present. So i desactivated/activated the app and then after that the process setup begined.

Thank you.

**Comment by DamoBird365** [comment]
For anyone else experiencing the same issue of "It looks like this app isn't compliant with the latest data loss prevention policies.", we added the new dataflow connector in DLP, waited 20+ minutes after much retrying, restarting the browser and then we tried going into solutions via Power Automate instead of Power Apps and the App ran without issue.  No idea why the Automate Portal worked and the App Portal didn't but something for others to try and report back on.

**Comment by slmmobile2020** [comment]
I had same error, and I have attached current list of DLP Policy based on Microsoft Documentation, however, I found [MSDN Documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies) is wrong, 

DLP Listing missing **"HTTP with Microsoft Entra ID (preauthorised)"** connector to DLP - Business, please add this to DLP and error should be resolve. 

Hope this helps saving lots of people's valuable time.

![Wrong MSDN - COE DLP Policy which is missing HTTP with Microsoft Entra ID (preauthorised)](https://github.com/microsoft/coe-starter-kit/assets/15915147/d9a2bbf7-2c55-403e-bffe-09e75c33f081)

**Comment by amalarajaf** [comment]
I made the Power Query connector addition to the DLP and checked after 10 mins and not working. Any suggestions?

![Image](https://github.com/user-attachments/assets/0366a6ef-a8a8-4946-80a9-96cca0f092a6)
