### ISSUE TITLE
[CoE Starter Kit - Feature]: Compliance Process - Customizable categories

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#5256]
### Is your feature request related to a problem? Please describe.

In the complinance process when the maker is providing the support details, he has to choose a category.
![image](https://user-images.githubusercontent.com/113470539/231477319-0c62c656-4f23-4add-96a5-6105074810a7.png)
These category doesn't always fit the expectation of the customer/user and modifing them creates a unmanaged layer, which isn't so great when it comes to updates

### Describe the solution you'd like

Can u make these cataories customiziable, so modifing them wont create an unmanaged layer?
![image](https://user-images.githubusercontent.com/113470539/231476805-8b4fcf38-e59e-4ef9-b27a-e8a88386769b.png)

**Comment by Jenefer-Monroe** [comment]
I believe this is a mergable change if you edit it outside of the context of the solution like this. Can you please try it and let me know? 
![image](https://user-images.githubusercontent.com/89584709/231534863-0c7b1a4c-7908-42de-aff2-970ce818c09e.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
