### ISSUE TITLE
[CoE Starter Kit - BUG] Data Lake Export not working

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5258]
### Describe the issue

Hi We have tried setting the data lake in our tenant. The data export keeps failing even after we used the following. We used a GA account that is also an owner on both the storage account and subscription. We have also made sure that the location of the storage account matches the location of the Power BI tenant. Thoughts?

### Expected Behavior

Data Lake Export should work so it can be ingested in the dataflows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

Dataflows

**Comment by nasilvae** [comment]
> I think you're saying that the Data Export itself is failing and not writing files to your storage account, is that right? If so, that is unrelated to the CoE Kit. Data Export is a product feature and if it isn't working you'll have to go through your usual Microsoft support channels: https://learn.microsoft.com/en-us/power-platform/admin/get-help-support

gotcha no worries, we opened a ticket just wondering if your team had experienced this issue before.

**Comment by manuelap-msft** [comment]
No, we've not seen it fail before unless it was due to incorrect permissions. It could be some network restrictions, but not sure.
