### ISSUE TITLE
[CoE Starter Kit - QUESTION] When will the audit log source change from this custom connector to the BYODL data export usage data?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5260]
### What is your question?

When will the audit log source change from this custom connector to the BYODL data export usage data?

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
We have no plans of changing it completely, at the moment you have two options

1. Use cloud flows to retrieve inventory via Power Platform admin connectors and telemetry via the Audit Log
2. Use BYODL to retrieve inventory via Data Export 

We are not planning on adding an option where you can use cloud flows for inventory and Data Export for usage only. 
We are not planning to remove the option to use the Audit Log as customers may not be able to configure Data Export, and we want to continue to support those.

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
