### ISSUE TITLE
[CoE Starter Kit - QUESTION] Limit for desktop flows in Power BI dashboard

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5266]
### What is your question?

There was earlier limitation of only 99 desktop flows which were visible in Power BI dashboard report. Does the limitation still exist with April release? 

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
There is no limit in PBIT or Dataverse. Likely what you hit was the limitations on desktop flows generally in which the number that we can return is limited due to the connector we have to use to get them. 
This is not yet resolved unfortunately.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
