### ISSUE TITLE
[CoE Starter Kit - QUESTION] is there a conflict using both managed environments and COE Starter Kit

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5267]
### What is your question?

is there a conflict using both managed environments and COE Starter Kit

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
No, they can be used alongside each other. For some features where there's overlap you will have to decide if you want to use one feature over the other to avoid maker confusion - a good example is the Maker welcome content https://learn.microsoft.com/en-us/power-platform/admin/welcome-content

In Managed Environments, admins can provide customized welcome content to help their makers get started with Power Apps. When the welcome content is enabled, upon signing in to Power Apps, makers will be greeted with customized getting started information. A similar concept in the CoE Starter Kit is the [welcome email](https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components#flows-2), which sends an email to new makers only after they've created an app, flow, or bot for the first time. This means that makers may get necessary information only after they've created their first resource, whereas the Managed Environments feature shows them information when they sign in to Power Apps.

You likely only want to set up one welcome content and not both.

**Comment by mdphung** [comment]
has anyone seen an issue where you as a service admin role can not access the managed environment from power platform admin view

**Comment by Jenefer-Monroe** [comment]
Can you share a screenshot so we better understand what you mean?
