### ISSUE TITLE
[CoE Starter Kit - QUESTION] I do not see in the COE Starter Kit parameters a time for environments to be considered inactive. is it the same as apps?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5268]
### What is your question?

I do not see in the COE Starter Kit parameters a time for environments to be considered inactive. is it the same as apps?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
We do not support a concept of inactive environments today. We do have this on our backlog https://github.com/microsoft/coe-starter-kit/issues/3154
