### ISSUE TITLE
[CoE Starter Kit - QUESTION] We have PIM roles assigned to our admins.  Will all of the Flows, we have installed associated with the CoE run as scheduled if these roles are deactivated?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5271]
### What is your question?

We have PIM roles assigned to our admins.  Will all of the Flows, we have installed associated with the CoE run as scheduled if these roles are deactivated?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
No you cannot rely on timing the CoE actions for PIM. You will need to get an exemption for this identity to run the kit.
