### ISSUE TITLE
[CoE Starter Kit - QUESTION] give environment makes more insights about apps on a specific environments

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5272]
### What is your question?

When I would like to give environment makes more insights about apps on a specific environments I read there's the possibility for several CoE installations, any recommendations for that?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont follow this question. Will leave open to see if we get more details.
