### ISSUE TITLE
[CoE Starter Kit - QUESTION] customise the Audit log flows to account for other event log types

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5273]
### What is your question?

Can we customise the Audit log flows to account for the event log types that are not currently included in the flow so that we can surface event logs back to Environment owners?

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
We will not be further investing in these but you are welcome to create extensions to the kit which do this!

**Comment by jamieg-nbs** [comment]
Thanks Jenefer, this question was from me a few weeks back. I've been working on surfacing additional data, will share it here when I've finalised testing :)
