### ISSUE TITLE
[CoE Starter Kit - QUESTION] Does it matter if the service account used has power automate per user plan with RPA or with no RPA? 

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5274]
### What is your question?

Does it matter if the service account used has power automate per user plan with RPA or with no RPA? 

### What solution are you experiencing the issue with?

None

**Comment by manuelap-msft** [comment]
We're not licensing experts but let me try and answer that. 

We don't use desktop flows (RPA) in the CoE kit so RPA is not required, but based on the license guides the execution rights for cloud flows are the same on the per user/per user with RPA license so any of those licenses should be fine for running the flows in the kit
![image](https://user-images.githubusercontent.com/55705669/231692749-ae8131ad-9240-4e0a-9a8b-a02c4561f17a.png)

Note, a Power Apps per User/per App license will be required for all the admins that will launch apps in the CoE kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
