### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Environment Properties) "problem with flows trigger" after upgrading

### ISSUE THREAD

**Issue by dchrist27** [microsoft/coe-starter-kit#5275]
### Describe the issue

I just upgraded the core solution to 4.4.1 and I noticed that the Environment Properties flow was set to off.  It was not off on the prior version.  When I open the flow I see:

![image](https://user-images.githubusercontent.com/52799471/231555000-c41bed25-25d0-411d-83b4-09e2c3b08428.png)

When I try to turn the flow on I see the following:

![image](https://user-images.githubusercontent.com/52799471/231555282-e62b2249-d942-473e-8ea7-452093c94508.png)

Clicking on 'fix the trigger'

![image](https://user-images.githubusercontent.com/52799471/231555410-b064602e-caf9-445b-88c9-dad17d630eea.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Environment Properties)

**Comment by Jenefer-Monroe** [comment]
If you use the setup wizard to upgrade, it will ensure the correct flows are turned on so you dont hit this in the future. 
In this case the flow now calls a helper : **_SYNC HELPER - Get Security Role Users_** so you'll need to turn that on.

**Comment by dchrist27** [comment]
Thanks…turning on the SYNC HELPER flow resolved the trigger issue.

**Comment by Jenefer-Monroe** [comment]
wonderful news. I'll go ahead and close but please return if you have new issues.
