### ISSUE TITLE
[CoE Starter Kit - BUG] April 2023: Flow Client error "BadRequest" ChildFlowNeverPublished

### ISSUE THREAD

**Issue by lizgarciaMSFT** [microsoft/coe-starter-kit#5277]
### Describe the issue

I'm receiving an issues with turning on the following flows;
HELPER - ObjectOperations
Admin | Sync Template v3 (Apps)
Admin | Sync Template v3 (Call Updates)
Admin | Sync Template v3 (Environment Properties)
 
[April23CoE_flow errors.docx](https://github.com/microsoft/coe-starter-kit/files/11215467/April23CoE_flow.errors.docx)
[April23_COE errors.zip](https://github.com/microsoft/coe-starter-kit/files/11215531/April23_COE.errors.zip)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_4.4_managed

### What app or flow are you having the issue with?

HELPER - ObjectOperations

### Steps To Reproduce

Followed instructions listed here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup

Warning when importing the solution: Child Flows must be published

Error when turning on flow: Cannot turn on flow, Child Flow must be published at least once for these flows:
HELPER - ObjectOperations
Admin | Sync Template v3 (Apps)
Admin | Sync Template v3 (Call Updates)
Admin | Sync Template v3 (Environment Properties)

**Comment by Jenefer-Monroe** [comment]
Hello the order that you turn these flows on is important as it appears you are turning on flows before their children are turned on. The order is specified in this documentation. [Setup core components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components)
We recommend using the setup wizard to install / ugprade as that will take care of all this for you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
