### ISSUE TITLE
[CoE Starter Kit - BUG] April 2023 CoE - PowerBI not gathering data (Blank)

### ISSUE THREAD

**Issue by lizgarciaMSFT** [microsoft/coe-starter-kit#5279]
### Describe the issue

The Power BI report is having issues importing data into the report. See attached image:

![PowerBI-CoE-April-2023-Blank](https://user-images.githubusercontent.com/112203147/231619615-c96dbe74-95d9-4898-aa8a-2acdcf0e10f4.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_4.4_managed

### What app or flow are you having the issue with?

Production_CoEDashboard_April2023

### Steps To Reproduce

1. Install the CoE toolkit
2. Install the Power BI dashboard and link to the environment where the CoE toolkit is installed

**Comment by Jenefer-Monroe** [comment]
Please do the following:
1. Browse to the Admin Command Center > Environment Variables > What is the value for this item? 
![image](https://user-images.githubusercontent.com/89584709/230621685-2f293271-b215-4f91-8234-0f39c8f638e9.png)

2. Browse to the Admin Command Center > CoE Flows Page > Inventory. When did this flow last run and did it pass? Click Flow details to browse to it. 
![image](https://user-images.githubusercontent.com/89584709/230622288-a392e38b-cabc-4cf9-849d-29491a22946b.png)

3. Open the most recent run. Does it make it down to this call? If so how many environments are returned? You can see this by popping it into a json parser.
![image](https://user-images.githubusercontent.com/89584709/230622587-e17a3ad2-e1d2-4d58-8a0c-255aa469359d.png)
