### ISSUE TITLE
Monitor Cloud Flows

### ISSUE THREAD

**Issue by anandasanyal** [microsoft/coe-starter-kit#5280]
Is there any feature available in COE to monitor Cloud Flows at tenant level ?
As admin I would like to monitor the same.
Thanks

**Comment by manuelap-msft** [comment]
Hello,

monitoring cloud flow runs is possible if you use the public preview of the CoE kits integration with the Data Export feature. You can learn more about this feature here: http://aka.ms/coebyodl

In the setup wizard, under choose inventory data source, you'll have to pick Data Export as your source for inventory and telemetry.

There is no other way to retrieve cloud flow run history for us, so we'll only support this through the integration with the Data Export feature.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
