### ISSUE TITLE
[CoE Starter Kit - BUG] Sharepoint apps not showing in COE

### ISSUE THREAD

**Issue by FolkestadNett** [microsoft/coe-starter-kit#5281]
### Describe the issue

In our Default environment we have some apps but they are not showcasing in the COE 

![Skjermbilde 2023-04-13 082525](https://user-images.githubusercontent.com/123945365/231672114-0b55630f-f704-4fba-a6f4-1a932f676ac5.png)

### Expected Behavior

It is weird that all the dates are the same.
need help to figure out how to showcase all the apps that are in the default environment 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

NAN

**Comment by FolkestadNett** [comment]
But it says we have 154 apps in this environment which is far from correct, After opening and saving a few apps they now appear in the list, but this will ruin the insight into seeing when the app was last edited.

**Comment by Jenefer-Monroe** [comment]
I dont know what state you are in so I suggest you do a "full inventory" run. Please see https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory

Then follow that by running the clean up flows 

- CLEANUP - Admin | Sync Template v3 (Check Deleted)
- CLEANUP - Admin | Sync Template v3 (Connection Status)
- CLEANUP - Admin | Sync Template v3 (Delete Bad Data)
- CLEANUP - Admin | Sync Template v3 (Orphaned Makers)
- CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
- CLEANUP - Admin | Sync Template v3 (PVA Usage)

**Comment by FolkestadNett** [comment]
They all ran successfully and did an "refresh of full inventory", the "FullInventory" was already set to "No" in the default solution in the COE environment
![image](https://user-images.githubusercontent.com/123945365/232775171-dc88f550-594f-4d35-999e-5a0a8341973c.png)

Still the same issue when viewing apps in the admin view in coe

**Comment by Jenefer-Monroe** [comment]
Correct, No is the default. You will need to do a full inventory run which means setting this to yes, resetting all the flows (if they do not update on their own) and then running an inventory. 
Please see https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by FolkestadNett** [comment]
changed to yes, and ran the Admin | Sync Template v3 flow, still the exact same problem in the default environment.
