### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View - Flows - Not Updated Data

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#5282]
### Describe the issue

Hello, I noticed that the list contains flows that no longer exist (they have been removed). Could you please tell me where the flow and the exact actions that are responsible for checking whether the flow has been deleted set the deleted flag to yes.

![image](https://user-images.githubusercontent.com/54030753/231702454-2899e94b-4074-4982-af4b-9c87a494218b.png)

I am the power platform administrator so I should see every flow.

![image](https://user-images.githubusercontent.com/54030753/231702673-d14ec9ec-b65f-48e3-8b0e-481203bc732e.png)

Regards

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Power Platform Admin View

**Comment by ClaudiuVio** [comment]
Hello ,

Check when the flow CLEANUP - Admin | Sync Template v3 (Check Deleted) ran the last time.

![image](https://user-images.githubusercontent.com/7468628/231703435-fd211ddf-a691-4872-9a75-f10cb86059db.png)

**Comment by BartoszKaminski1999** [comment]
Hello, thanks for help, it could be resolved.

**Comment by BartoszKaminski1999** [comment]
Hello, thanks for help, it could be resolved.
