### ISSUE TITLE
[CoE Starter Kit - QUESTION] Solution for high number of API action calls when running CoE with orphaned maker flow enabled

### ISSUE THREAD

**Issue by thomgerm** [microsoft/coe-starter-kit#5284]
### What is your question?

We would like to run the flows to identify and manage / clean-up  orphaned apps and flows in our large tenant. Enabling the relevant functions results in very high number of action calls (250k once a week for HELPER maker check). In combination with the other flows the number of action calls cannot be managed with any license type and is jeopardizing our clean-up activities.
Is there any solution in sight for this (considering the natural growth we do not believe that cleaning up the maker table is a long time solution)

### What solution are you experiencing the issue with?

None

**Comment by Jenefer-Monroe** [comment]
We dont have anything specifically targetting governance other than you switching to the product's [Managed Environments](https://learn.microsoft.com/en-us/power-platform/admin/managed-environment-overview) concept. 

We did just make a change for April to reduce the API calls for Maker Check but its still a highly called object. 

Have you already looked at the new Data Export feature and its integration into CoE? https://powerapps.microsoft.com/en-au/blog/now-in-preview-coe-starter-kit-backed-by-data-from-self-serve-analytics-data-export/
That wouldnt help these particular API calls but would help with the overall load for a large tenant. 

We are also open to ideas of how to save API calls in Gov if the community has some!

**Comment by thomgerm** [comment]
Jenefer, thank you - would you agree that it might be impossible to run the orphan makers clean-up in a large environment / tenant, please?

**Comment by Jenefer-Monroe** [comment]
We do have large organizations running these flows. I'm not sure if they did something to do an early clean up or something to make it run faster perhaps. 

Some ideas:
- Do a manual pass on the orphan objects to clean up things that seem to be able to be deleted (ex apps not run in years, with a name that includes "test", which are not shared with any other users)
- Start by exempting some environments and clean up envt by envt.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
