### ISSUE TITLE
[CoE Starter Kit - QUESTION] Microsoft Teams Business Justification

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5289]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

When i opened Teams Environment in Power Platform Admin View to approve getting the below message "The Business Process Flow has been Deactivated for this record".

![image](https://user-images.githubusercontent.com/126264610/231803549-3a24f6d7-3f44-4dd1-b42e-cf0efa8ee896.png)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by lingutla123** [comment]
Worked. Thank you.

**Comment by Jenefer-Monroe** [comment]
Wonderful, thank you for letting me know. I'll keep an eye out to see if something happened to turn these off that needs fixed up.
