### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by JamesJustinD** [microsoft/coe-starter-kit#5291]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have a Flow running in the CoE that needs to connect to Azure SQL Server.  We are in the GCC, and when the IP Range changes the connection breaks.  Is there a way to allow for a more permanent way to connect our CoE Flow connection in the GCC to our Azure SQL Server?  note that our Azure is in the public area of the cloud.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

November 2022

### What app or flow are you having the issue with?

Custom Flow

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We aren't staffed to assist with customizations, and unfortunately I don't know the answer here to assist. 
Will leave open for a while to see if the community has some ideas.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
