### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to load CoE Setup and Upgrade Wizard

### ISSUE THREAD

**Issue by bwieland86** [microsoft/coe-starter-kit#5293]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to initialize the Setup and Upgrade Wizard. Receiving the following error:

Error Code: AppForbidden
Session Id: c085bd4b-fe5e-4d1c-89ab-d42f6cf9fa96
Activity Id: 80878299-bdb0-47ab-a543-ba2443607cf5
Timestamp: Thu Apr 13 2023 15:46:56 GMT-0400 (Eastern Daylight Time)

It looks like this app isn't compliant with the latest data loss prevention policies.s@https://x.y.dynamics.com/uclient/scripts/app.js?v=1.4.5434-2302.4:4923:82 i+Mw/ut/</<@https://x.y.dynamics.com/uclient/scripts/custompage.js?v=1.4.5434-2302.4:36:7139

Need to know what connectors need to be added (since the December 2022 release) for the Setup to load and a list of required connectors to be placed in environment for DLP Policy.

### Expected Behavior

Setup and Upgrade Wizard should load

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. In the CoE environment, open the Center of Excellence - Core Components

**Comment by manuelap-msft** [comment]
This question has been asked and answered before, see: https://github.com/microsoft/coe-starter-kit/issues/5255#issuecomment-1505209659

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
