### ISSUE TITLE
[CoE Starter Kit - BUG] The last refresh attempt failed because of an internal service error. This is usually a transient issue. If you try again later and still see this message, contact support

### ISSUE THREAD

**Issue by psandypatil** [microsoft/coe-starter-kit#5294]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I published "Pulse_CoEDashboard" and "Power Platform Administration Planning"(which are comes with CoE Starter Toolkit) power bi reports on one of my workspace, but i am getting this error on my outlook email :

"
Refresh failed: TMHE Pulse CoE Dashboard has failed to refresh
An error occurred while processing the data in the dataset.
Refresh failed:

TMHE Pulse CoE Dashboard has failed to refresh.
Failure details: The last refresh attempt failed because of an internal service error. This is usually a transient issue. If you try again later and still see this message, contact support.

<ccon>Expression.Error: The key didn't match any rows in the table.. Key = <ccon>[Schema = "dbo", Item = "admin_pulsefeedback"]</ccon>. Table = <ccon>#table({"DisplayName", "Name", "Location", "IsDefault", "Data"}, {})</ccon>. </ccon>;<ccon>The key didn't match any rows in the table.</ccon>. The exception was raised by the IDbCommand interface. Table: admin_pulsefeedback.

Next refresh for TMHE Pulse CoE Dashboard is scheduled for April 14, 2023 7:00 UTC.

"

So how can i fix this issue?

### Expected Behavior

It should show the proper data on graphs, charts as per data verse table having with no errors and warnings

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2023

### What app or flow are you having the issue with?

no, its having with power bi reports

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Have you collected Pulse feedback through the Pulse feedback feature already? https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#set-up-pulse-feedback-survey

The dashboard will only work if Pulse feedback has been collected, so if there's data in the tables the dashboard uses.

**Comment by psandypatil** [comment]
Okay, but is that error related to SQL server?

**Comment by psandypatil** [comment]
Yes, i already did.
If the table in blank, so it should show blank data on power bi report, but why the error is there?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
