### ISSUE TITLE
[CoE Starter Kit - QUESTION] Data Export & Audit Log together or not necessary?

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#5295]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team!
One simple question because I don't be clear after read the documentation (again 😄 )

If we have using Data Export to retrieve the data for CoESK, is it necessary to install also the solution Audit Log?

Thanks!

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 2023

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
It will no longer be necessary to install and configure the Audit Log solution, if you are using Data Export. The Data Export contains the usage information for Power Apps that we used to get from the Audit Log, so the Audit Log flows are therefore not needed.

Great question - I've added this to our documentation backlog so we can address this in our FAQ section!

**Comment by albertocastro365** [comment]
It has sense 😃 Thank you!

**Comment by manuelap-msft** [comment]
Added locally, ready for our next docs update.
