### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard incorrectly sets Admin eMail to Group ID instead of email address

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#5296]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have noticed that the Sync Templates V3 (Sync Flow Errors) for the Self Service Analytics version of the CoE has been disabled as it was failing. The error is: The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'String '8fd4d4ea-9d34-4547-9947-93b537696695' does not validate against format 'email'.'.

It fails on the condition 'If table is not empty, send email' at the 'Send Sync Flows to Admin' step. The body message is 

{
  "error": {
    "code": "TriggerInputSchemaMismatch",
    "message": "The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'String '8fd4d4ea-9d34-4547-9947-93b537696695' does not validate against format 'email'.'."
  }
}

I believe the issue is because the variable set is not an email address. I have checked the variable in the command centre and it is showing as 

<img width="701" alt="CoE Admin Variable" src="https://user-images.githubusercontent.com/117096415/232006963-bc864848-0a71-4af9-ae55-a021da362c90.PNG">

I thought I would check first, but is this just a simple case of updating the admin_AdminMail to an email address? Not sure if this was an issue I caused during the setup or an issue with the setup process, so I thought I would share. 

I will wait to hear back from you before updating the variable.

Thanks

### Expected Behavior

Sync Template V3 (Sync Flow Errors) emails the admin email of any sync flow errors. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.50

### What app or flow are you having the issue with?

Admin - Sync Template V3 (Sync Flow)

### What method are you using to get inventory and telemetry?

None

**Comment by G1982C** [comment]
Thanks Manuela. I have changed the variable from the GUID to the email address, ran the flow again and it ran without any issues. 

I did indeed use the setup wizard which is one of the reasons I thought I would share this insight, in case there is an issue. 

thanks for the speedy response

**Comment by manuelap-msft** [comment]
Thank you so much for the detailed analysis and investigation, that's really helpful for us! We'll check the logic in the setup wizard to resolve this issue from there - looks like the wizard is incorrectly writing the group ID rather than the email address back to the environment variable.
