### ISSUE TITLE
[ALM Accelerator - QUESTION] Service Prinipal

### ISSUE THREAD

**Issue by orjsol** [microsoft/coe-starter-kit#5297]
### What is your question?

Hi.
During setup of ALM I've created the app registration as described. 
But I also needed to give the service principal rights in the environments. Got some error messages when I used the admin app to set up a new project. Think it was related to creation of the service connectors/env queries..

What kind of rights does this service principal need in the environments? Or is this necessary at all?
or is this done by these commands:

Install-Module -Name Microsoft.PowerApps.Administration.PowerShell
Install-Module -Name Microsoft.PowerApps.PowerShell -AllowClobber
New-PowerAppManagementApp -ApplicationId [the Application (client) ID you copied when creating your app registration]

I've run these commands without error messages so I assumed it was ok. Is there a way to check this? And can a power platform run the commands?

This is what I needed to do to fix my issues:

Added the "ALM Service Principal"  (Application (client) ID )) as System Administrator for "all" environments. (dev, test & prod)

- Power Platform admin center 
- Selected Environments 
- Selected the environment I've created, for example ent-dc-project-DEV
- Selected settings 
- Selected Application users under Users + permissions 
- Selected New app user 
- Clicked on Add an app and pasted in the app-id 
- Selected business unit 
- Added security roles – System Administrator  

Hope someone can highlight this..

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 2023 - 1.0.20230405.2

**Comment by mikefactorial** [comment]
@orjsol thanks for the questions. The steps you followed are correct. The service principal does require System Administrator rights in the environments. This was a gap in the previous setup documentation that we published an update for yesterday.

https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#set-up-makers-to-use-the-alm-accelerator-for-power-platform-app

**Comment by orjsol** [comment]
Thanks for the reply!
