### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by vibhavrikhi1990** [microsoft/coe-starter-kit#5298]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am unable to import the coe component zip into powerapp solutions. 
It states import failed due to missing
![MicrosoftTeams-image](https://user-images.githubusercontent.com/130783135/232107666-af86ace5-fc34-4898-88b4-f0074d8ae079.png)
[log.txt](https://github.com/microsoft/coe-starter-kit/files/11235288/log.txt)
 dependencies 

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by vibhavrikhi1990** [comment]
It just worked, But I may need some help in order to complete the COE kit installation. How can we connect?

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid we are a very small team and so cannot assist with installs. 

There are many partners that specialize in the CoE and can be hired out to do this though. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

If you would like to try on your own please use our documentation starting with [Before setting up the CoE Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/setup). Were I to guess I suspect you did not install the required pre-requisite solution which you fill find listed in the [Set up inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) article.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
