### ISSUE TITLE
[CoE Starter Kit - QUESTION] Troubleshooting error messages when turning on COE flows

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5299]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have upgraded to the April 2023 release of the COE kit.

I opened the "CoE Setup and Upgrade Wizard" and got to the "Run inventory flows" section.
Unfortunately, I cannot turn on any of the inventory flows using the toggle buttons.

![COE-Upgrade-Wizard](https://user-images.githubusercontent.com/128085471/232156157-e820eec3-faa2-420c-a988-c3ed688f904b.PNG)

Example 1
when I attempt to turn on the "Admin | Sync Template v3", I get the error message in the attached screenshot. 

![Error1](https://user-images.githubusercontent.com/128085471/232156198-3cd709fc-d05c-4071-838b-b97057847de0.png)

Example 2
when I attempt to turn on the "Admin | Sync Template v3 (Environment Properties)", I get the error message in the attached screenshot. 

I'm not sure where I should start troubleshooting.
Would anyone have any idea of where I should begin my troubleshooting?

![Error2](https://user-images.githubusercontent.com/128085471/232156278-8975e9cb-d854-468f-93c2-17df1ab9fc67.png)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 2023

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

have you extended the CoE tables with new fields? Especially the environments table?
Based on this error:
![image](https://user-images.githubusercontent.com/55705669/232460057-a1ccc061-0d1e-42aa-92ff-8a6c11d065aa.png)

It looks like you've added a new field ending with _frc (we don't have a field like that in our table) and marked that as required, and as this is a custom field and not one shipped with the CoE kit it's not updated as part of our sync flows and therefore fails. I'd recommend not making the field required if you want to continue using our regular out of the box sync flows.
