### ISSUE TITLE
Can't deploy Developer Compliance Centre outside Dedicated environment?

### ISSUE THREAD

**Issue by Alcamala** [microsoft/coe-starter-kit#53]
Hi all,

Not sure if im doing this wrong or if I had the wrong impression of how this should work.

I have an environment dedicated to COE - I want to deploy the developer compliance center to users without giving them access to all the data in COE. Do the CDS entities that COE relies on need to each be manually moved, and then manually updated (regularly) from the coe environment where all the flows that grab this data lives, or is this an unintended issue?

**Comment by Alcamala** [comment]
or perhaps if there is some documentation on what roles the user needs specifically to access DCC in the coe environment that would be very helpful.

**Comment by devkeydet** [comment]
Sorry about the confusion, but this repo is the future home of the CoE Starter Kit.  That transition hasn't happened yet.  We tried to make that clear in the readme.md.  Until the transition is complete, would you please ask here:
https://github.com/microsoft/powerapps-tools/issues
