### ISSUE TITLE
[CoE Starter Kit - QUESTION] QCOE Test Environment

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5304]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

Currently we are using COE Stater Kit in production environment, how can we leverage this in Test ( non production) environment? Is there any documentation or steps to enable this in Test environment?

Thank you!

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

you can use our environment variable called **ProductionEnvironment** (yes/no flag) to indicate that you're in a test environment. Set it to yes in your production environment, and no in your test environment. If it's set to no, it means no emails will be sent to makers/users and they will all be re-directed to the group you've set up for the Admin eMail which means you can check if they meet your expectations. 

We have some limited documentation on a testing strategy here
https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup#testing-strategy

**Comment by lingutla123** [comment]
Thank You.
