### ISSUE TITLE
[CoE Starter Kit - QUESTION] Not all environments show in the CoE

### ISSUE THREAD

**Issue by JaimyPolhuis** [microsoft/coe-starter-kit#5306]
I have installed the CoE for our tenant and it appeared to work. However, not all environments show in the CoE dataverse tables and Power BI dashboard. Also, when new environments are created these do not show up here. Is this a familiar problem and what could be the solution to this?

**Comment by manuelap-msft** [comment]
Hello,

that's not expected, so we'll have to triage through this to figure out what's happening

1. Can you confirm you have the Power Platform Admin role assigned to the user running the flows?
2. Can you confirm this role is permanently assigned to your user (or the service account running the flows) and not constrained via PIM?
3. Can you let us know what version of the CoE Core Components solution you are on?
4. Can you open the CoE Admin Command Center app > navigate to Sync Flows page > check if there are any errors and if the Admin | Sync Template v3 flow is on?

**Comment by JaimyPolhuis** [comment]
Hi, thanks for your quick reply.

**Comment by JaimyPolhuis** [comment]
Hi, thanks for your quick reply. The Power Platform admin role is indeed assigned and the account has full and permanent access to all information on our tenant. Besides, the account also has a power apps per user license. The version that I am using is 3.56 of the CoE. There were some errors on the admin | sync template v3 (apps) but those were just solved and I do not think that could have an effect on the environments showing. The admin | sync template V3 is turned on and working fine as far as I can see (no errors and the flow succeeds). However, when I check this flow, the environments that I am missing are also not retrieved here. Could the problem be in this flow then?

**Comment by manuelap-msft** [comment]
Yes, that would be the issue then - lets dive a bit deeper there then!

Can you find this scope and the Get Environments action
![image](https://user-images.githubusercontent.com/55705669/232461615-3aa1af2a-b4de-4234-ba23-91ac7bfd16cd.png)

If the Outputs section doesn't show you content straight away, select Click to download and copy the content into your preferred JSON viewer.

Does this output show all environments you're expecting or are some missing from there as well? 

Then go to this scope and check if the apply to each loop loops through the number of environments you're expecting? e.g. in my case I have 84 environments in my tenant.
![image](https://user-images.githubusercontent.com/55705669/232462199-730dd3f3-d5df-42e1-8c39-f18c4e788d13.png)

If all of this still looks correct, check if any of the steps in the apply to each environment loop fail by selecting "next failed". It's greyed out in my case as they're all succeeding, but if there's failures would be available to click on.

Let's see if any of that gets us closer to the issue!

**Comment by JaimyPolhuis** [comment]
I see that action, and there are no errors in the second step that you show. However, in the first step the environments that I am missing are also missing in the output there (so that makes sense). Only, could there be another reason for this besides the account that makes the connection (as this does not appear to be the problem, because as described earlier it satisfies the requirements)?

**Comment by manuelap-msft** [comment]
Hello,

the flow here is using the [Power Platform for Admins](https://learn.microsoft.com/en-us/connectors/powerplatformforadmins/) connector and the [List Environments as Admin](https://learn.microsoft.com/en-us/connectors/powerplatformforadmins/#list-environments-as-admin) action to get a list of all the environments. From the connector documentation and our experience, the only pre-requisite is to be a Power Platform service admin. The connector documentation also states: 

> Power Platform service admins will have access to all resources and operations available in their tenant from this endpoint.

The CoE kit is only a user of this connector, but we don't own the connector or troubleshooting for the connector so here's what I would recommend.
1. Create a new flow that just uses the [List Environments as Admin](https://learn.microsoft.com/en-us/connectors/powerplatformforadmins/#list-environments-as-admin) action. Here's the version that we use so you can set it to the same
  ![image](https://user-images.githubusercontent.com/55705669/232464588-085169aa-27c8-4f0f-8225-dfa093a9b3b0.png)
2. Check if the output there still only returns a limited number of environments
3. If it does, raise a support ticket with Microsoft support https://learn.microsoft.com/en-us/power-platform/admin/get-help-support to triage with them why the connector is only returning a limited number of environments.

**Comment by JaimyPolhuis** [comment]
Thank you for the information. I'll try to figure it out with the help of your advice. Thanks again!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by ImranCodeBug** [comment]
I have very similar issue to this. i am using 4.33 version of the core components app. i am not sure which flow should I be looking at.

one point to highlight is the during the installation, the developer did not have power platform admin right. the global admin granted admin permission to the developer since then.
