### ISSUE TITLE
[CoE Starter Kit - BUG] Corrupt link to Developer Compliance Center

### ISSUE THREAD

**Issue by josefhagen** [microsoft/coe-starter-kit#5308]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The link to developer compliance center is broken in the email where the user needs to submit compliance details for their flow. 
When I click, I get: 

Error
An error has occurred.

Try this action again. If the problem continues, check the [Microsoft Dynamics 365 Community](https://go.microsoft.com/fwlink/?LinkId=98746) for solutions or contact your organization's Microsoft Dynamics 365 Administrator. Finally, you can contact [Microsoft Support] (https://go.microsoft.com/fwlink/?LinkId=394391).

I have tried with several users, browsers and flows, same error.

<img width="297" alt="error d365" src="https://user-images.githubusercontent.com/50071213/232472066-33fa8be5-61e1-4756-8304-3179da3ba3a7.PNG">
<img width="123" alt="error mail" src="https://user-images.githubusercontent.com/50071213/232472070-bf0fce82-4295-4043-b206-bfbc94a24321.PNG">

### Expected Behavior

The flow should open in Developer Compliance Center.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

Admin | Compliance Details Request eMail (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. An email from Admin | Compliance Details Request eMail (Flows) should be sent to a user with an app that is shared too broadly
2. Click the Developer Compliance link
3. The error message will appear

**Comment by manuelap-msft** [comment]
Hello,

thank you! We switched from using a Canvas App to using a Model Driven app with custom pages recently for the Developer Compliance Center, and as part of that didn't realize that deeplinking (passing a parameter to the app/page) worked differently for custom pages. We're tracking a fix for this for the May release.
