### ISSUE TITLE
[CoE Starter Kit - BUG] Command Center CoE Flows Bug

### ISSUE THREAD

**Issue by dchrist27** [microsoft/coe-starter-kit#5309]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am not seeing  'Last Run' or 'Last Run Passed' for the PVA and Desktop flows.

![image](https://user-images.githubusercontent.com/52799471/232493079-19e1aacd-4124-4422-bf1d-6ae2966feaaf.png)

![image](https://user-images.githubusercontent.com/52799471/232493126-85781bf2-c64f-4111-98ae-5d928e4fd485.png)

But they are in fact running when I open each flow.

![image](https://user-images.githubusercontent.com/52799471/232493269-f57d8f08-b4e5-4bcd-b0e8-1e7a4f89170f.png)

![image](https://user-images.githubusercontent.com/52799471/232493409-99b1ed8f-d952-414a-9d4e-d7386bea09f0.png)

Dave

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

None

**Comment by dchrist27** [comment]
I checked and both flows do not have an unmanaged layer.

The desktop flows flow stops in the second step.   Should the expression result be true?

![image](https://user-images.githubusercontent.com/52799471/232504031-a1b5b17f-fc0e-42a6-b074-32783b77472e.png)

**Comment by manuelap-msft** [comment]
Hello,

no, that's correct like that - we terminate early if we can't retrieve desktop flows from an environment (this is true for environments without Dataverse, and Dataverse for Teams environments). This flow runs once per environment, you'll have to find a run that goes past this step to the Get RPAs step. 

Do you know if overall in your tenant you have desktop flows and chatbots? We might not record last run/last run passed if you don't have desktop flows and chatbots in any environments.

**Comment by dchrist27** [comment]
When I look at the PowerBI report under Desktop flows I see data.

![image](https://user-images.githubusercontent.com/52799471/232521323-590f791e-f7e5-4a31-a97a-8bb1ddb24af0.png)

All 20 of the desktop flows are in the default environment.

I found the specific flow that queries the default environment and it keeps failing.

![image](https://user-images.githubusercontent.com/52799471/232521657-0d1a77ee-d9d3-410e-b1fa-7f1b067f2226.png)

**Comment by manuelap-msft** [comment]
Thanks for sharing the error - looks like we need to improve the error handling on this flow to capture the failure and update the last run status! I'll assign it to the dev for further triage.

**Comment by dchrist27** [comment]
Wanted to circle back on one more thing.   My default environment has Dataverse shouldn't step two be true based on what you previously mentioned (and also because I verified that all the desktop flows are in my default environment)?

![image](https://user-images.githubusercontent.com/52799471/232528251-07798eba-12b8-4703-863e-c11c7f400f81.png)

**Comment by Jenefer-Monroe** [comment]
Failures there occur if you do not have access or if there are no bots in the envt.
Not having access usually means that your admin persona running the flow is subject to PIM which we cannot support.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
