### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by KristenStanley** [microsoft/coe-starter-kit#5310]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are using the February 2023 CoE Core Components and Audit Logs.  The number of sessions and the number of shares are inaccurate and very large.  Also, the data does not make sense in that there are some entries with no reported unique users, sessions, and last launch date, but they have over 10,000 users shared and 40+ groups shared.  When I dig further to compare the actual # of people the app was shared with compared to the # being reported in the CoE Apps page and within the Power App itself, it's incredibly different!  The data that I have right now is inaccurate and cannot be used.  I do not know if this is an issue with the CoE Core components or the Audit Logs.  We have both installed.  Can you please offer some guidance on how this data can be corrected and usable once again?

### Expected Behavior

I expect the data being reported in the Power BI CoE report to accurately reflect the number of shares, sessions, and unique users.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Core = 4.3, Audit Logs = 3.3

### What app or flow are you having the issue with?

I'm not sure which flow is causing the trouble

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

The data I am looking at is being surfaced in the Power BI report.  Please see screen shots in the attached document
[CoE Power BI Issue - Incorrect App Details being Reported.docx](https://github.com/microsoft/coe-starter-kit/files/11253429/CoE.Power.BI.Issue.-.Incorrect.App.Details.being.Reported.docx)

**Comment by manuelap-msft** [comment]
We did have an issue with the user count being incorrect due to a bug on our side, that was fixed with the February release (https://github.com/microsoft/coe-starter-kit/issues/4468#issuecomment-1361422088). Could you check if you have any unmanaged layers on any of the inventory flows?

The easiest way to do this is to look at the CoE Admin Command Center > CoE Flows page and check if the solution layer icon shows up for any of the flows:
![image](https://user-images.githubusercontent.com/55705669/232724563-8f72bcd9-fb80-4c01-9d34-55277ff594f0.png)

**Comment by manuelap-msft** [comment]
Unique Sessions and Users are recorded over time and we don't apply a time filter in the dashboard - so they're aggregated from the moment you've set up the Audit Log solution and will therefore increase month over month if it's an active app.

**Comment by KristenStanley** [comment]
Thank you for your response.  I reviewed the Cleanup Helper flow and confirmed the variables are being reset to 0 now.  As far as my data goes, do you have any recommendations on how to fix it?  Should I clear out the values and let the flows start fresh collecting the data again?  I can't think of another way to fix the data, but if there is another way, please let me know.

**Comment by KristenStanley** [comment]
I'm afraid this did not clean up the data.  It still has crazy numbers that do not make sense.  Do you have another suggestion?

**Comment by KristenStanley** [comment]
Sure, I'll try that.  Do I need to set the Environment Variable Full Inventory back to yes before I run it?

**Comment by KristenStanley** [comment]
Great news! I went in to the CoE today to trigger that flow to run, but I decided to check the Power BI report first just to see what the data was today.  The # of users shared, and groups are both back to accurate numbers.  I did not have to run the second flow.  Thank you!  I'm going to assume the Unique Users and sessions are accurate.  I have no way to validate that data.  Thank you for your help with this!  I really appreciate it.  Case closed! :)

**Comment by manuelap-msft** [comment]
Wonderful, sounds like the FullInventory just took a bit longer to complete then. Glad to hear it's all up to date now! Thanks for your patience as we worked through this. I'll close this issue for now, but please let us know if you have any further questions, issues or feature asks for the CoE kit!
