### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to turn on flow because child flows have not been published

### ISSUE THREAD

**Issue by EmelynTr** [microsoft/coe-starter-kit#5311]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://user-images.githubusercontent.com/128402165/232566797-128e1a9e-f7e3-407f-ba71-b5f58475fa54.png)

Al activar el flujo secundario me aparece el siguiente error, como podría solucionarlo?

### Expected Behavior

Cambie de estado desactivado a activado.
![image](https://user-images.githubusercontent.com/128402165/232567286-81f84c90-17a1-4d5d-84d1-4bec2e34bf43.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Helper y Administracion

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. soluciones
2. centro de excelencia: componentes basicos
3. flujos de nube
4. Activar trabajo secundario
5. error

### Anything else?

Se aplicaron los pasos segun documentacion

**Comment by manuelap-msft** [comment]
Hello,

unfortunately, we're only able to triage issues in English as our team doesn't speak other languages. 

This flow depends on two other child flows that have to be turned on first - can you check those two flows are on and if not can you turn them on?
![image](https://user-images.githubusercontent.com/55705669/232721891-7ad648b7-5797-4b56-897d-e8ceb1a5bbd3.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
