### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Admin Command Center Links Not Working

### ISSUE THREAD

**Issue by joebeyer75** [microsoft/coe-starter-kit#5312]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I recently upgraded our COE to the April 2023 version. Now when I browse to the CoE Admin Command Center, where it lists all the CoE apps, everyone I click on (the pop-out button), it opens a new tab but doesn't load anything. I've tried multiple browsers. 

There are more than just these two that just open blank pages, but the two I am concerned about are; App and Flow Inactivity Notifications Clean Up View, and Cleanup Old Objects App .

### Expected Behavior

Apps load as expected. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

Governance Flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Can you check if the **Admin | Sync Template v3 CoE Solution Metadata** has run after you've upgraded, and if not can you re-run this flow? This cleans up the bookmarks and links and hopefully the command center works after that.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by joebeyer75** [comment]
> closing out as no further action for starter kit team

Hello, this hasn't quite been resolved. The Admin | Sync Template v3 CoE Solution Metadata flow is running successfully, what appears to be every 7 days. I am still unable to access the following apps from the Bookmarks page in Command Center:

- App and Flow Inactivity Notifications Clean Up View
- Cleanup Old Objects App
- Template Catalog
- Maker Assessment Admin App
- Power Platform Training Management
- Power Platform Training Registration
- Innovation Backlog
- Innovation Backlog Admin
- Maker Assessment
- Developer Compliance Center

For each one of those, when I click the link, it opens a new tab in the browser and doesn't load anything just a blank page. All others work. 

Not sure if related, but ever since we upgraded the CoE, the data on the Admin View and PBI views have been very inconsistent and do not appear to load the correct information. 

How can we get this fixed? It worked better before the upgrade.
