### ISSUE TITLE
[CoE Starter Kit - QUESTION] Configure embedded apps in the CoE dashboard Documentation requires Update

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#5315]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I was not sure where to post this but the documentation for Configuring embedded apps in the CoE dashboard requires an update.
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard

it shows resetting the embedded app
![image](https://user-images.githubusercontent.com/17124284/232743038-8e4a1355-0f22-4687-a2fa-59cd915be989.png)

However the "Reset to Default" option is no longer available imediately:
![image](https://user-images.githubusercontent.com/17124284/232743618-9c204e72-23b3-4e94-bfe7-3a46c1567709.png)

you need to first edit the visual
![image](https://user-images.githubusercontent.com/17124284/232743836-d7c14569-66ba-4f35-aa0a-bd85a5b14991.png)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April Release

### What app or flow are you having the issue with?

Production_CoEDashboard_April2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Thanks for letting us know! Hard to keep up to date with the constantly changing platform :) I'll mark this as a documentation bug and we'll fix that with the next update!

**Comment by medicineshow** [comment]
I'm sure it is but keep up the good work guys :)

**Comment by manuelap-msft** [comment]
Hello,

what version of Power BI desktop are you using? I've just checked this today with the May 2023 version and reset to default is still available without first editing the visual under the "format your visual" panel 


![Image](https://github.com/microsoft/coe-starter-kit/assets/55705669/f8e02296-5edd-4510-900c-afeacbffccbe)

**Comment by medicineshow** [comment]
@manuelap-msft apologies for the huge delay in responding. We have been extremely busy elsewhere and CoE has not been on the top of our list (this is a good thing as it is working away fine, no issues 😊) I have just checked and can see that reset to default is present. Not sure now which version I originally raised the issue with but I can confirm that I am now on May 2023. Thanks again.

**Comment by Jenefer-Monroe** [comment]
thank you for letting us know!
