### ISSUE TITLE
While upgrading the coe core component using classic upgrade One more solution is getting created with logical name as centerofeccellenceCorecomponents_upgrade[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by PrakritiVyas** [microsoft/coe-starter-kit#5317]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

While I am trying to upgrade the coe start kit instead of upgrading already existing core component it is creating a second solution with _upgrade in the logical name.How to resolve this so only one core component solution is there with updated version.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

this typically happens when the Upgrade has failed at some stage

Go to your CoE environment > Solutions > Solution History > Check the Upgrade (which will consist of an Install/Uninstall step) and see if there are any failures there, and what the failures are.

**Comment by PrakritiVyas** [comment]
There is a failure and it's showing error as Solution manifest import failure  Holding solution CenterofExcellenceCoreComponents_Upgradd already exists.

Error code :- 80048539

Please let us know how to resolve this.

**Comment by PrakritiVyas** [comment]
Sorry for the wrong information. I have checked and the import for successful when we did the import but it created another solution with _upgrade in the name

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
