### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard - Compliance process and Maker assessment show blank space under Share Apps

### ISSUE THREAD

**Issue by krhoadesnh** [microsoft/coe-starter-kit#5319]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Changes made on screen 2, _Exempt environments_, are saving.  Changes made to screen 3, _Configure settings_, are not saving.

**Feature Request:**  It is very confusing that the final 'share' screen does not have a close button or a save or something to notify you it is ready to close.
![image](https://user-images.githubusercontent.com/122402854/232814680-765ffb2d-d9df-4398-bcdf-d4e34951f8f1.png)

### Expected Behavior

I would assume there to be a way to complete or save the setup process.  Also assume that env. variables would be saving.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

Center of Excellence Setup Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the wizard
2.  Go to more features > _Compliance process_
3. Next to 'Exempt'.  Make change to at least one setting.
4. Next to _Configure Settings_.  Make change to at least one setting.
6. Next through to _Share Apps_
7. No options at that point so use navigation to go back to 'More Features'

**Comment by manuelap-msft** [comment]
Hello!

You're right - we do have a bug here! We moved this app from a standalone canvas app to a page as part of the Nurture apps - Maker model driven app and missed some updates in the setup wizard. You can follow the manual setup instructions until we fix this issue:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#set-up-the-maker-assessment-components-manually

**Comment by manuelap-msft** [comment]
The screenshot you shared is from the Maker Assessment tool, but the title refers to the Compliance process so I wasn't sure which one you were experiencing issues with. Above I shared the manual setup instructions for Maker Assessment but let me know if there's another part you have issues with.

**Comment by krhoadesnh** [comment]
I included the Maker Assessment screenshot but that was the _second_ app I tried from the wizard, both had the same experience.
