### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Command Center missing toolbar buttons

### ISSUE THREAD

**Issue by krhoadesnh** [microsoft/coe-starter-kit#5321]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This actually started after the previous CoE upgrade, I assumed it would be fixed in this one.  The toolbar buttons are missing, but if you hover over where they _should be_ the cursor changes & the buttons do still work.

![image](https://user-images.githubusercontent.com/122402854/232823983-9a526a9f-44dd-4cbe-8e02-205595c6826c.png)

### Expected Behavior

I should be able to see the buttons.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the Admin Command Center.

### Anything else?

I did not see this in the Issues list but I might have missed something.

**Comment by manuelap-msft** [comment]
I don't repo this myself
![image](https://user-images.githubusercontent.com/55705669/232846231-db6e695e-3aee-483a-a0b7-d6dad285666c.png)

What browser and browser version are you using?

**Comment by krhoadesnh** [comment]
Edge, whatever the latest version is.  My coworkers see the same experience.

**Comment by Jenefer-Monroe** [comment]
Can you please check to see what version of Creator Kit you have installed? 
![image](https://user-images.githubusercontent.com/89584709/233841569-277b4af3-9994-48fe-8645-6700e02ee4c5.png)

**Comment by krhoadesnh** [comment]
1.0.20230118.1

**Comment by Jenefer-Monroe** [comment]
Thanks, I'm setting up to see if I repro.

**Comment by Jenefer-Monroe** [comment]
I installed that version of creator kit with April Core and do not repro. 
Can you please go to the Default Solution > Pages > Open the page in edit mode, be sure to hit **skip** the "update code components" dialog. 
![image](https://user-images.githubusercontent.com/89584709/234074891-51b07a62-b6cc-4d78-b59a-6138e032c656.png)
![image](https://user-images.githubusercontent.com/89584709/234075008-dd19e874-8761-47c4-add6-58f67ae442f7.png)
![image](https://user-images.githubusercontent.com/89584709/234075049-1a5c6e25-6891-4546-a754-b19fe1f0c64f.png)

Do you see them in edit mode? Do you see any errors?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
