### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to import Nurture Components

### ISSUE THREAD

**Issue by AJ-Zafar** [microsoft/coe-starter-kit#5325]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to import Centre of Excellence nurture components managed.

Error message:
Cannot insert duplicate key exception when executing non-query: System.Data.SqlClient.SqlCommand Exception: System.Data.SqlClient.SqlException (0x80131904): Violation of UNIQUE KEY constraint 'ndx_envvarval_schemaname'. Cannot insert duplicate key in object 'dbo.EnvironmentVariableValueBase'. The duplicate key value is (admin_TrainingInaDayFeedbackForm, 0, Jan  1 1900 12:00AM). The statement has been terminated.    at Microsoft.Crm.CrmDbConnection.HandleExecutionExceptionAbstract(Exception exception, String commandText, IDbConnection connection, IDbCommand command, IDbTransaction transaction, Boolean isOpen, Int32 commandTimeout, IConnectionRetryPolicy localRetryPolicy, Int32& retryCount)    at Microsoft.Crm.CrmDbConnection.InternalExecuteWithRetryAbstract[TResult](Func`1 executeMethod, IDbCommand command, IConnectionRetryPolicy retryPolicy)    at Microsoft.Crm.CrmDbConnection.<>c__DisplayClass235_0.<InternalExecuteNonQuery>b__0()    at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)    at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)    at Microsoft.Crm.Platform.Server.DataEngine.SqlDataAccessManager.ExecuteNonQuery(IDbCommand command, ISqlExecutionContext context, Int32 sourceLineNumber, String memberName, String sourceFilePath)    at Microsoft.Crm.BusinessEntities.BusinessProcessObject.ExecuteNonQueryAbstract(IDbCommand command, ISqlExecutionContext context)    at Microsoft.Crm.BusinessEntities.BusinessProcessObject.ExecuteNonQueryAbstract(IDbCommand command, ExecutionContext context)    at Microsoft.Crm.Platform.SolutionAwareComponents.CreateInstanceActionBase.ExecuteCreate(IDbCommand command, ExecutionContext context) ClientConnectionId:**Removed** Error Number:2627,State:1,Class:14 ClientConnectionId before routing**Removed** Routing Destination:**Removed**.northeurope1-a.worker.database.windows.net,11042

### Expected Behavior

I expected it to import with no errors

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

2.19

### What app or flow are you having the issue with?

The whole solution

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

I have all other parts of the latest release installed. Just this one has been failing.

### Anything else?

[Center of Excellence - Nurture Components_import (2).xlsx](https://github.com/microsoft/coe-starter-kit/files/11267365/Center.of.Excellence.-.Nurture.Components_import.2.xlsx)

**Comment by manuelap-msft** [comment]
Hello,

we've seen this before and it was a temporary issue usually caused by solutions being imported at the same time. Have you tried the import again after this failure, and if not could you try again and make sure there's no other solution imports happening in this environment?

**Comment by AJ-Zafar** [comment]
By uninstalling and reinstalling I was able to get it to work.
