### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Welcome Email v3 not triggered

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#5327]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, 

Admin | Welcome Email v3 is not triggering but Admin | Add Maker to Group that has the same trigger is triggering correctly.

![image](https://user-images.githubusercontent.com/54030753/233012867-11e85a42-7d47-45ad-9313-c86e9244b3af.png)

![image](https://user-images.githubusercontent.com/54030753/233012899-24524f3c-86f7-4581-a830-22fd60321f38.png)

What can be the problem?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Welcome Email v3

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
I don't think we've seen that behaviour before, the flows have exactly the same trigger so should both trigger - can you check if the flow is on and showing any issues like this - either a red dot in the Flow Checker or a yellow notification bar?
![image](https://user-images.githubusercontent.com/55705669/233115304-2f209ff7-c9d0-46d2-bc70-957f4b5dad0f.png)

**Comment by BartoszKaminski1999** [comment]
Hello,

Flow is turned on, I've also reset it a couple days ago and still nothing.

![image](https://user-images.githubusercontent.com/54030753/233287499-1f6c8036-2778-4b08-9b46-20b1a8956010.png)

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid if the flow is not triggering correctly then this is some product issue outside of the context of the kit. 
I've seen triggers be broken in the past if envts are restored but that impacts all triggers, not just some.
