### ISSUE TITLE
[CoE Starter Kit - QUESTION] Current configuration of Governance flows with ProductionEnvironment variable

### ISSUE THREAD

**Issue by iharabagiu** [microsoft/coe-starter-kit#5328]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Currently I have updated the ProductionEnvironment environment variable to no in the CoE solution as I don't want to bother the users with notifications. 

I am preparing to deploy the CenterOfExcellenceAuditComponents solution to my environment, and considering that some flows may be already enabled after doing the deployment, is it safe to say that all flows from this solution that need to send emails are taking into consideration the value of the env variable ProductionEnvironment?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.8

### What app or flow are you having the issue with?

All Governance Flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

no flows from the Audit (Governance) or Nurture component solutions will automatically be enabled, they're all off on import and you'll manually decide which bits to use. All flows also take the ProductionEnvironment variable into consideration, that's correct.

Hope that helps,
Manuela
