### ISSUE TITLE
[CoE Starter Kit - QUESTION] office 365 Management API

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5329]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

when i click on New connection it is not prompting sign in page. It is directly saving the connection.

![image](https://user-images.githubusercontent.com/126264610/233092233-b384010f-20f3-49f4-bc9a-1cba4d4f51dc.png)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

for the custom connector, you specify the security / authentication information in the Security tab of the custom connector - that's the client id, client secret etc that you provided. 
![image](https://user-images.githubusercontent.com/55705669/233113110-90812cf6-b6b7-4c37-82e5-d692c017c84a.png)

When you create a connection, that's what's used. Could you explain a bit more what your question, issue or concern is? I'm not sure I understand from the info you provided.

**Comment by lingutla123** [comment]
Figured out the issue. I used Identity provider is " Generic Ouath 2" because of this  the  login window is not prompted
 when i click on "New connection" on Test page. I changed Identity provider to "Azure Active Directory" and it worked.

**Comment by manuelap-msft** [comment]
Oh I see! Yes, recently the default identity provider has changed from Azure Active Directory to Generic OAuth 2 and a lot of folks have stumbled over this! Hopefully it's all working fine now.

I'll close this issue for now, but please let us know if you have any further questions!
