### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Check Deleted  (Cloud Flows) marking existing Flows as deleted

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#5331]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Cleanup Helper Flow marks existing Flows as deleted.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted  (Cloud Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

It´s probably due to our big inventory size and might not occur in smaller inventories.

I quickly checked the Flow and compared it with an older version, where the issue didn´t occur.

I saw that the "List Flows as Admin" action is there twice now, but only the output from "List Flows as Admin (V2)" is used in the "Select" Action below.

I then checked the settings of that action and saw, that pagination is turned off, which I assume is the problem here, since it was turned on and set to a 100.000 threshhold in the older version I compared it with (Which would also explain why it didn´t mark all Flows as deleted but just most).

![image](https://user-images.githubusercontent.com/109345362/233099801-dec9efb8-dbd6-473b-853b-c463a285cfdf.png)

![image](https://user-images.githubusercontent.com/109345362/233099966-04c6daee-758c-4ffe-93ab-a6d6d6d89fb8.png)

Thanks for your support!

**Comment by DominicMeznik** [comment]
Glad I could help! Keep up the great work :)

**Comment by cr0max** [comment]
Hi, we face the same issue, we just installed the April verision of CoE. It marked 10000+ active flows as deleted in our database. Is there a quick fix and a way to bulk change the marked as deleted flows?

**Comment by Jenefer-Monroe** [comment]
### Fix locally. 
To local fix so you can continue to run these flows while you await the May release. 
1. Open **_CLEANUP HELPER - Check Deleted (Cloud Flows)_** in edit mode

2. Browse to the **_List Flows as Admin (V2)_** action > Settings
![image](https://user-images.githubusercontent.com/89584709/233843991-13c39c3d-e5fd-4135-a7a2-e016f0b50c48.png)

3. Turn on Pagination and set Threshold to 10000
![image](https://user-images.githubusercontent.com/89584709/233844051-33a030e6-4b9a-4f71-8401-45e95b3bff27.png)

Note this will create an unmanaged layer that will need removed when you upgrade

**Comment by Jenefer-Monroe** [comment]
### Data Cleanup with Excel
To reset these flows as not deleted. 

If you have the [Microsoft PowerApps Office Add-In](https://learn.microsoft.com/en-us/power-apps/teams/edit-data-in-excel) you can open the table in Excel to manipulate.
![image](https://user-images.githubusercontent.com/89584709/233844397-b31b171f-533d-4012-b804-1e26bff9510d.png)

When the file opens > Enable Editing > Ignore the error shown and make sure you are logged in as the correct user
![image](https://user-images.githubusercontent.com/89584709/233844480-71c8c318-69da-46f7-836f-7ee19ccc61ec.png)

Set all the flow deleted values to false and publish
![image](https://user-images.githubusercontent.com/89584709/233844566-ea9d4f77-c42a-4c65-a590-238139097903.png)

**Comment by Jenefer-Monroe** [comment]
### Data Cleanup with a quick flow
If you do not have access to edit in Excel in your organization you could create a quick flow in the CoE envt instead. 
Be sure to set the pagination on the List Rows action to also be the 10000
I have included a copy of this fix up flow at the bottom as well for import as well (using flow import not solution) in case thats easier
![image](https://user-images.githubusercontent.com/89584709/233844977-8ae2d150-cd65-454f-aab3-df3b09495bfd.png)
[cleanupincorrectlydeleted_20230423141847.zip](https://github.com/microsoft/coe-starter-kit/files/11303940/cleanupincorrectlydeleted_20230423141847.zip)

**Comment by Jenefer-Monroe** [comment]
Local fixed for May

**Comment by cr0max** [comment]
> ### Data Cleanup with Excel
> To reset these flows as not deleted.
> 
> If you have the [Microsoft PowerApps Office Add-In](https://learn.microsoft.com/en-us/power-apps/teams/edit-data-in-excel) you can open the table in Excel to manipulate. ![image](https://user-images.githubusercontent.com/89584709/233844397-b31b171f-533d-4012-b804-1e26bff9510d.png)
> 
> When the file opens > Enable Editing > Ignore the error shown and make sure you are logged in as the correct user ![image](https://user-images.githubusercontent.com/89584709/233844480-71c8c318-69da-46f7-836f-7ee19ccc61ec.png)
> 
> Set all the flow deleted values to false and publish ![image](https://user-images.githubusercontent.com/89584709/233844566-ea9d4f77-c42a-4c65-a590-238139097903.png)

Worked great, thank you for the quick response!

**Comment by Jenefer-Monroe** [comment]
We have released a hotfix for this bug
https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-April2023-HF1/CenterofExcellenceCoreComponents_4_4_2_managed.zip

Thank you so much for posting and helping us get to a fix so quickly!!!
