### ISSUE TITLE
[CoE Starter Kit - QUESTION] What does the Logic Flows connector mean?

### ISSUE THREAD

**Issue by kabirstein** [microsoft/coe-starter-kit#5332]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am trying to clean up a Default environment for a client and in the Apps Connectors report the "Logic Flows" connector is listed for several apps. I understand from reading Issue #3295 and Issue #1087 that this is not a real connector but perhaps some kind of internal designation in Dataverse that the CoE picks up as it's syncing. I'd like to know more about why this "Logic Flows" "connector" is displayed for these apps so I can know whether to ignore it for DLP purposes when I see it in the future. I analyzed one of the apps, a very simple app, and the actual connectors in the app are:

- Office 365 Outlook
- Office 365 Users
- Excel for Business
- SharePoint

The only thing that I see that could possibly be triggering this "Logic Flows" connector designation is the sole Flow that is called from the app that uses the "datauri" expression in a Compose action. Do you know if this is causing the "Logic Flows" connector to be displayed for this app in the CoE App Connectors report and if so, why? I'm uncomfortable not knowing why this designation appears and would like to understand it more. Here's a screenshot of the Compose action:

![image](https://user-images.githubusercontent.com/54034916/233123916-d0d80b63-f1cc-48b9-a450-425f549e5ece.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2023

### What app or flow are you having the issue with?

App Connectors Report

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Yes, Logic Apps typically indicates that the flow is triggered with the Power Apps trigger. I don't think we've ever seen LogicApps being listed for anything other than Power Apps triggered flow, but as there's no documentation on this connection I can't rule out that other triggers also show up as Logic flows.
