### ISSUE TITLE
[ALM Accelerator - QUESTION] ALM Accelerator for Power Platform

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5333]
### What is your question?

Hi,

Getting below error when i opened "ALM Accelerator for Power Platform" app to configure.

![image](https://user-images.githubusercontent.com/126264610/233138088-be5c99a6-f1c7-4938-a114-390ce1816b79.png)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 19th 2023

**Comment by mikefactorial** [comment]
@lingutla123 can you verify that all of the solution flows are turned on (specifically GetEnvironmentSolutions in this case), but best to check that all flows are turned on in the solution. 
![image](https://user-images.githubusercontent.com/42348035/233143802-beac39f0-055e-4295-9a19-a382e41291eb.png)

**Comment by lingutla123** [comment]
It worked. Thank You.
