### ISSUE TITLE
[ALM Accelerator - BUG]: Update Deployment Settings fails after finding wrong build definition

### ISSUE THREAD

**Issue by BJHF-power** [microsoft/coe-starter-kit#5335]
### Describe the issue

We have an issue where the Update Deployment Settings step of Build & Deploy is failing because the pipeline attempts creation in the wrong repository. 

In line 150 of the execution, the build query is only using the definitions name and not including a repository filter. In this case, we have two versions of a Solution, deployed into 2 different repos (one ending in -1999999 and the other ending in -4999999 in the screenshot). The query is returning the -4999999 repo instead of the -1999999 repo that it should.
 
Adding the repository filter to the query should address this issue where the same solution name exists but in different repos:
https://learn.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-7.0#build 

### Expected Behavior

The correct repo should be found when creating the user deployment settings

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

unsure

### Steps To Reproduce

Deploy a Solution using  Repo A
Deploy the same Solution via Repo B

### Anything else?

![image](https://user-images.githubusercontent.com/106766774/233148721-ebc01232-d7df-4530-994e-081eb437ec19.png)

**Comment by mikefactorial** [comment]
@BJHF-power thanks for submitting this. Will look into handling this scenario better in the upcoming release.
