### ISSUE TITLE
[ALM Accelerator - BUG]: Build Number

### ISSUE THREAD

**Issue by rfarris2000** [microsoft/coe-starter-kit#5336]
### Describe the issue

The build number that is output is different than the one that is written to the solution.xml file

### Expected Behavior

The build number should match all the way through the pipeline

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

February 2023 versions

### Steps To Reproduce

I only have an example.  See screen shots below

### Anything else?

![image](https://user-images.githubusercontent.com/1624416/233216899-e5b0fb3b-35df-4e4d-a3b4-cce2cf407103.png)

![image](https://user-images.githubusercontent.com/1624416/233216905-5de69999-349c-46fa-ac97-0f383d37a14d.png)

![image](https://user-images.githubusercontent.com/1624416/233216704-6ac39aa5-4778-4986-8fea-5039c901b663.png)

**Comment by mikefactorial** [comment]
@rfarris2000 looks like this issue got lost in the shuffle. Can't say I've ever seen this behavior before. I assume that the screenshots are all from a single build pipeline? Have you seen this recently since this issue was opened?
