### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Components Import Fails due to missing Power Automate Approvals solution

### ISSUE THREAD

**Issue by talljanding** [microsoft/coe-starter-kit#5337]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to import CenterofExcellenceAuditComponents_3.8. I have not previously imported the Audit Components solution. I have already imported/setup COE - Core Components, COE - Audit Logs, Creator Kit, and CreatorKitReferences (Canvas/MDA).

When I try to import the Audit Components solution, I get an error due to missing dependencies:
![image](https://user-images.githubusercontent.com/55523205/233217606-68d8b858-311d-4210-8fdb-747a2a086ba7.png)

I have tried following the setup directions to address this via the COE Setup Wizard and the Compliance Process piece. However, the Compliance Process piece says that it is missing a prerequisite. So I seem to be in a catch-22.
![image](https://user-images.githubusercontent.com/55523205/233217882-32f98463-ef45-477e-ab9b-6c944c6e847f.png)

### Expected Behavior

Expectation is that either Compliance Process would allow me to address the missing dependency for the Audit Components solution or that the Audit Component solution would import without issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.8

### What app or flow are you having the issue with?

COE - Audit Components

### What method are you using to get inventory and telemetry?

None

**Comment by DominicMeznik** [comment]
Did you make sure to initialize the "Microsoft Flow Approvals Solution"? Looks like it´s missing that dependency. The solution is installed, once the Approvals connector has been used in a Flow for the first time.

https://learn.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov#initialize-flow-approval-tables-in-your-environment

**Comment by manuelap-msft** [comment]
Thank you @DominicMeznik!!

**Comment by talljanding** [comment]
That is precisely what I was missing, @DominicMeznik. Thank you so much for the assistance!
