### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to configure the Audit Log to smaller chunks sizes?

### ISSUE THREAD

**Issue by nschf** [microsoft/coe-starter-kit#5339]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, 

i have installed the CenterofExcellenceAuditLogs_3.3_managed.zip file. 
Now I get the following email every day:

"CoE Starter Kit - Audit Logs: Missing some logs - require smaller chunks
Your audit logs were collected but some were missed due to truncated results.
You will need to use a smaller interval to gather all logs.
See the optional Step 11 of our[ Audit Log flow setup documentation](http://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow) for more details.

Current chunking size:
1 Hour"

Unfortunately I can't change anything because it is a managed solution. 
The environment variables are also all managed where I can't change anything. I also don't know for sure which audit log flow it is affecting or if it is both. 
Can someone help me there or have the same problem?  

Thank you !

### What solution are you experiencing the issue with?

Audit Log

### What app or flow are you having the issue with?

Admin Sync Logs

### What method are you using to get inventory and telemetry?

None

**Comment by DominicMeznik** [comment]
You can change the value of Environment Variables in the Admin Command Center App. (https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables)

**Comment by manuelap-msft** [comment]
Thank you @DominicMeznik!!
