### ISSUE TITLE
[CoE Starter Kit - QUESTION] What value to provide for Data Export option environment variables, when choosing sync flow architecture?

### ISSUE THREAD

**Issue by EnsilaC** [microsoft/coe-starter-kit#5343]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

hi Team, 

i just updated the core components into the latest release, and setting up with the CloudFlows option not the Data Export. 
But there are 14 environment variables to be filled, most of them in regard to the Data Export option
![2023-04-20_15-31-23](https://user-images.githubusercontent.com/123632961/233382297-0106144c-912b-4263-ac5a-2188f119ca09.png)
What we have to do with those?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April Release 4.4

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

you can leave them empty on import! We actually recommend using the Setup Wizard for configuration and setup of the kit, and as part of that leaving all environment variables empty on import and setting them during the Setup Wizard.

Thank you
Manuela
