### ISSUE TITLE
[CoE Starter Kit - QUESTION] New environments are not inventoried

### ISSUE THREAD

**Issue by RocketmanACEGov** [microsoft/coe-starter-kit#5344]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Newly created environments are not showing up in the GCC Center of Excellence Toolkit.  
The latest environment that are showing up in our CoE Toolkit were created in December 2022. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 2022

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

is the Admin | Sync Template v3 flow running without failure? This flow would inventory new environments. 

Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
