### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Desktop flows) - Error Parse_RPA_JSON - missing operand

### ISSUE THREAD

**Issue by Service-WebDevPowerP** [microsoft/coe-starter-kit#5346]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Since I installed the April release, the Sync Template v3 (Desktop flows) flow fails every day, with an error Parse_RPA_JSON
![Capture](https://user-images.githubusercontent.com/105202791/233469364-c6e6a930-b222-4c71-bb09-e717a4ca1187.PNG)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.41

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

It happens every time the flow runs

![image](https://user-images.githubusercontent.com/105202791/233470151-d3b16e93-3bad-4eec-8d0f-7559e141aab5.png)

**Comment by Jenefer-Monroe** [comment]
Can you please show the output for the parse failure? It would tell us what about the parse failed.

**Comment by Service-WebDevPowerP** [comment]
Hi Jennifer, I am afraid that I cant show it as there is no output only an error 

![image](https://user-images.githubusercontent.com/105202791/234309697-e6f70c19-dd8d-4170-a1e1-f7c9b0bb5624.png)

Is there any other info that I can sent that might help identify the issue?
