### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to populate the customized email table?

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5347]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I created a new env for testing and installed COE starter kit. Ran Admin | Sync Template v3 flow successfully. The Customized emails are not showing in CoE Admin Command Center. Do i need to run any other flows?

![image](https://user-images.githubusercontent.com/126264610/233472422-ec72e5f7-24a7-4ef6-8ead-95d402f0c5ae.png)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

you'll have to follow the setup instructions, either by using the [setup wizard](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-using-the-setup-wizard) or by following them [manually](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-manually) and running them in the right order.

Manuela

**Comment by lingutla123** [comment]
I followed the CoE starter Kit setup document

**Comment by lingutla123** [comment]
Hi Manuela,

I am trying to setup the CoE Setup and Upgrade Wizard in test environment getting below error. 
![image](https://user-images.githubusercontent.com/126264610/234055975-a80ee148-5400-42dc-8b31-cbf0316da31a.png)

Today i am getting same error in Prod Environment. Reviewed this document  [Validate data loss prevention (DLP) policies](https://learn.microsoft.com/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies). All connectors are added.

**Comment by manuelap-msft** [comment]
We have recently added the PowerQuery Dataflow connector, so you may need to update your DLP policy to add that. If the error persists, another user recently shared a tip on how to get around that - see: https://github.com/microsoft/coe-starter-kit/issues/5255#issuecomment-1516551652

**Comment by lingutla123** [comment]
After Deactivate and Activate the app is working.

Thank You.

**Comment by Jenefer-Monroe** [comment]
glad to hear it! closing out as no further action for starter kit team
