### ISSUE TITLE
[CoE Starter Kit - QUESTION] Verify BYODL Data in Default environment

### ISSUE THREAD

**Issue by RPadhy** [microsoft/coe-starter-kit#5353]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I configured the data flows to pull data from storage account as part of Azure Data export. The data flows refreshed successfully. But, I don't see all the apps and flows populated to the Dataverse tables. 

Do we need to run the Sync template V3 flows as well?? The sync template V3 flow is terminating if inventory in BYODL is true. 

Can you please suggest ?? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Core component 4.4

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
When did you configure the Data Export feature? Sometimes its takes a week or so to get all the data into the Data Lake. 
Then note also that new apps / flows (and deleted apps/flows) can take a day or two to arrive in the Data Lake. 

If you dont think your case is one of these, then you will need to see what types / envts / etc are missing so that we can investigate with you here.

**Comment by RPadhy** [comment]
Thank you for the response. 

I believe the issue is with the Data source itself. I pulled an export from the storage account container. I could see 2 Default- .json files. one for Canvas and one for modeldriven apps. 

But, If I compare the length of the file, the canvas .json file length is very low and it looks like the data is not populated properly (screenshot below). 

 
![image](https://user-images.githubusercontent.com/43860631/234742120-f61b7f6d-ed72-44a2-9cd9-7deb7a3055c3.png)

I got count from the the default canvas file as suggested by you and the count is showing as 30.  There are around 9000+ canvas apps in our tenant.

**Comment by manuelap-msft** [comment]
Hello,

thanks for following the steps and checking this - it does indeed look like the canvas.json file for Default is very small and doesn't contain data about all apps! We just had another customer report the same, where the canvas.json only contained custom pages but not canvas apps for the default environment. 

The Data Export feature is a product feature and is fully supported by the product team, and the feature has nothing to do with the CoE kit itself so unfortunately we can't help further here. We (the CoE kit) are just consumers of the data provided through this feature, similar to how we're consumers of connectors etc. As this is an issue with Data Export itself, can you please raise a support ticket through your regular support channels: https://learn.microsoft.com/en-us/power-platform/admin/get-help-support

We'll follow up internally with the team that owns the Data Export feature as well, but a support ticket will help them track this better. 

Thank you,
Manuela

**Comment by pezlin** [comment]
We have the same problem with a lot of apps missing, particularly canvas apps. And I don't see any default files at all.

**Comment by manuelap-msft** [comment]
@pezlin If you don't see the files in the storage account configured to receive the Data Export files, please raise this as a support ticket for the Microsoft product team to triage. The CoE kit is only a consumer of the data provided by Data Export, but we can't troubleshoot issues related to Data Export itself (e.g. missing/incorrect files). Data Export is a product feature and fully supported through official Microsoft support channels.

**Comment by RPadhy** [comment]
> Hello,
> 
> thanks for following the steps and checking this - it does indeed look like the canvas.json file for Default is very small and doesn't contain data about all apps! We just had another customer report the same, where the canvas.json only contained custom pages but not canvas apps for the default environment.
> 
> The Data Export feature is a product feature and is fully supported by the product team, and the feature has nothing to do with the CoE kit itself so unfortunately we can't help further here. We (the CoE kit) are just consumers of the data provided through this feature, similar to how we're consumers of connectors etc. As this is an issue with Data Export itself, can you please raise a support ticket through your regular support channels: https://learn.microsoft.com/en-us/power-platform/admin/get-help-support
> 
> We'll follow up internally with the team that owns the Data Export feature as well, but a support ticket will help them track this better.
> 
> Thank you, Manuela

Thank you Manuela. 

As a second thought meanwhile we will work with Microsoft on this issue. 

Can we use the cloud flows to run a complete inventory of the apps/flows and other components and then create the data flows with the storage account(from Data export) which will read the usage data at least and update to the respective Dataverse tables?
Path from storage container :  PowerApps/Usage

Will this approach help to get the unique users, last launch date, last run date of flow etc ??

**Comment by manuelap-msft** [comment]
Hello,

I checked internally with the Engineering team that owns the Data Export feature and they confirmed this issue has been fixed and the fix is just rolling out to all customers, according to them you should see the full Default environment file coming through either later today or tomorrow. Fingers crossed!

Thank you
Manuela

**Comment by RPadhy** [comment]
Thanks you for the update. I will verify tomorrow and update this thread with the details. 

Meanwhile, I tried the approach to collect the inventory using cloud flows. Then create Power Platform dataflow that populates data from the App Usage folder to the CoE Audit Log table in Dataverse and then use the Production CoE dashboard which brings in data from the Dataverse tables. This looks good so far.

**Comment by pezlin** [comment]
> Hello,
> 
> I checked internally with the Engineering team that owns the Data Export feature and they confirmed this issue has been fixed and the fix is just rolling out to all customers, according to them you should see the full Default environment file coming through either later today or tomorrow. Fingers crossed!
> 
> Thank you Manuela

I can confirm that it is working now.

**Comment by Jenefer-Monroe** [comment]
Wonderful news. Closing out.
