### ISSUE TITLE
[ALM Accelerator - Feature] Is it possible to set an Async Wait Time for build tool tasks?

### ISSUE THREAD

**Issue by alanrroberts** [microsoft/coe-starter-kit#5355]
### What is your question?

My deploy jobs are timing out after hitting the default 60 minute async timeout (e.g on PowerPlatformImportSolution).  I can edit the deploy-Solution.yml file to add a MaxAsyncWaitTime to the step but this will likely get lost next time I update the pipeline files.  Is there a supported way to specify this value?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

March 2023

**Comment by mikefactorial** [comment]
@alanrroberts mind creating a PR for this over in https://github.com/microsoft/coe-alm-accelerator-templates?

**Comment by DSTAlan** [comment]
@mikefactorial happy to do so but may need some guidance...do you mean an issue or a PR?  I'm not sure how to raise a PR with no code to submit?  All I have done to date is manually go into the deploy-Solution.yml  and hard code in longer timeouts where needed (which isn't much of a solution) e.g.

- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.import-solution.PowerPlatformImportSolution@2
  displayName: 'Import Managed Solution as Upgrade'
  inputs:
    authenticationType: PowerPlatformSPN
    PowerPlatformSPN: '${{parameters.serviceConnectionName}}'
    SolutionInputFile: $(ManagedSolutionPath)
    HoldingSolution: true
    MaxAsyncWaitTime: 120
    OverwriteUnmanagedCustomizations: ${{parameters.overwriteUnmanagedCustomizations}}
    UseDeploymentSettingsFile: $(UseDeploymentSettings)
    DeploymentSettingsFile: $(DeploymentSettingsPath)
  condition: and(succeeded(), ne(variables['IsUnmanaged'], 'true'), eq(variables['TriggerSolutionUpgrade'], 'true'), eq(variables['SolutionExists'], 'true'))

**Comment by alanrroberts** [comment]
@mikefactorial happy to do so but may need some guidance...do you mean an issue or a PR? I'm not sure how to raise a PR with no code to submit? All I have done to date is manually go into the deploy-Solution.yml and hard code in longer timeouts where needed (which isn't much of a solution) e.g.

task: microsoft-IsvExpTools.PowerPlatform-BuildTools.import-solution.PowerPlatformImportSolution@2
displayName: 'Import Managed Solution as Upgrade'
inputs:
authenticationType: PowerPlatformSPN
PowerPlatformSPN: '${{parameters.serviceConnectionName}}'
SolutionInputFile: $(ManagedSolutionPath)
HoldingSolution: true
MaxAsyncWaitTime: 120
OverwriteUnmanagedCustomizations: ${{parameters.overwriteUnmanagedCustomizations}}
UseDeploymentSettingsFile: $(UseDeploymentSettings)
DeploymentSettingsFile: $(DeploymentSettingsPath)
condition: and(succeeded(), ne(variables['IsUnmanaged'], 'true'), eq(variables['TriggerSolutionUpgrade'], 'true'), eq(variables['SolutionExists'], 'true'))

**Comment by mikefactorial** [comment]
Lost track of this one as we had some routing issues in GitHub that we resolved recently. Will look to make this user definable.
