### ISSUE TITLE
[CoE Starter Kit - QUESTION] Child Admin| Sync Logs failing

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#5356]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I keep getting a Failure Notice: Sync Audit Logs email. When I got to the Starter kit to check the flows, the parent does not have any failed runs. So I checked the child flow and it has some successful runs, but there are a few failed runs. I am not sure how to correct the issue. Below are screenshots on errors in the flow run.

<img width="763" alt="image" src="https://user-images.githubusercontent.com/95765970/233697826-e51ebcee-c1bc-4429-8501-0bdff5bd7892.png">

![image](https://user-images.githubusercontent.com/95765970/233697988-5fd1a665-76ba-4529-bee2-5c3cfd8248b7.png)

![image](https://user-images.githubusercontent.com/95765970/233698188-2ba1851c-7505-436c-8a5c-d419abfcd9c8.png)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by AUTigers16** [comment]
Following up on this as I haven't seen an update or suggestions on how to resolve.

**Comment by Jenefer-Monroe** [comment]
It looks like you are sending too many requests for the backend to handle. 
![image](https://user-images.githubusercontent.com/89584709/234652836-2dddf087-eb95-451e-bbb2-24a98e8b9ffa.png)

Did you change the env variables which are used for chunking? You may have made them too small for the backend to handle.

**Comment by AUTigers16** [comment]
We have the TimeInterval-Internal set to 5 and the TimeInterval-Unit is set to Minute? What do you suggest we change it to?

<img width="603" alt="image" src="https://user-images.githubusercontent.com/95765970/234675927-9094308e-5024-4109-9aef-686cb73f4592.png">

**Comment by Jenefer-Monroe** [comment]
That cadence works for most people. Please double check that you have the related env vars set correctly too. 
Please see from our documentation: [Example configurations for environment variables](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog#example-configurations-for-environment-variables)
![image](https://user-images.githubusercontent.com/89584709/234887035-da1a1c1e-4a17-4206-9177-608f3f544e23.png)

**Comment by AUTigers16** [comment]
Our TimeSegment-Countlimit was set at 60. I upped it to 300. Crossing fingers that this works.

**Comment by Jenefer-Monroe** [comment]
This call is in an apply to each, how many clusters is it iterating? (aka 1 of X)
![image](https://user-images.githubusercontent.com/89584709/235438330-f55fbe55-8f66-4b1b-9ea0-0911fe7144e0.png)

**Comment by AUTigers16** [comment]
Looks like I am not getting the error emails anymore. I think this can be closed.
