### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform User Role Table Empty

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5357]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team, 

We currently have BYODL CoE setup and we noticed that the Power Platform User Role table is empty. We have also verified that the Clean - Admin | Sync Template v3 (Deleted), Cleanup Helper - Power Apps User Shared and Helper - CanvasAppOperations are on. 

### Expected Behavior

Power Platform User Role table should have data. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

Power Platform User Role Table

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Likely the flows just ran before the dataflows populated the data. Please rerun CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
