### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is it possible to identify which flows were created from Sharepoint Sites and which are there from scratch

### ISSUE THREAD

**Issue by AJ-Zafar** [microsoft/coe-starter-kit#5358]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Similar to how you can see the custom canvas form apps created on sharepoint lists I have a need to Identify which flows / automation were created from sharepoint and if possible teams. these get created in the default environment.

![image](https://user-images.githubusercontent.com/114920334/233729884-fd8cd22c-3ba5-44c9-856d-048645e4a922.png)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by AJ-Zafar** [comment]
Thanks for the update I did think so, I had some clients question this and thought there was nothing Out of the box or in the CoE kit. This is also quite a niche request, I will look into building something custom for them.
