### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to transfer CoE "ownership" to a new admin

### ISSUE THREAD

**Issue by akshaya-ak** [microsoft/coe-starter-kit#5360]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have installed, CoE toolkit through an users account, now that user is leaving the company, how we can transfer all the resources to other user? Please guide us with this issue.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

1.7

### What method are you using to get inventory and telemetry?

None

**Comment by DominicMeznik** [comment]
Hi, you should consider using a service account to prevent this from happening in the future.

Not sure if this is the best solution but you can just change the connection used in the connection references (in the CoE solutions)

**Comment by akshaya-ak** [comment]
okay, so if i use a service account, and change all the owners of apps, flows, and connections to the service account ID it will work right? or do I have to install it again in a service account?

**Comment by Jenefer-Monroe** [comment]
Thanks for helping Dominic! 

Here is our write up on how to deal with this
https://learn.microsoft.com/power-platform/guidance/coe/limitations#co-authoring-and-connections

Basically you have to transfer all the connections and you do this in the Default Solution.

**Comment by akshaya-ak** [comment]
Hi Jenefer, Thanks for your quick response, Right now I have installed CoE in production environment, so can you please me with the further steps ?

**Comment by Jenefer-Monroe** [comment]
Default Solution, not default environment. So these are the correct steps for you! :) https://learn.microsoft.com/power-platform/guidance/coe/limitations#co-authoring-and-connections

**Comment by petepuu** [comment]
@akshaya-ak, you mentioned version 1.7 but not which solution but I guess Core solution, right? If it is really Core solution and version 1.7 then you have very old version installed. Do you have only Core deployed or maybe other solutions as well like auditlog, governance etc? If only core is used then I would recommend to do a fresh installation to new environment with dedicated service account

But like mentioned in previous comments we can change the connection of all CoE connection references but also the owner of the components like apps, flows, connection references, business process flows etc. At the moment easiest and fastest way is to use legacy Dynamics UI to change the owner of multiple components at once. Canvas app owner can be changed using Set-AdminPowerAppOwner command see more info from https://powerapps.microsoft.com/en-us/blog/updating-ownership-for-power-apps-apps/

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
