### ISSUE TITLE
[CoE Starter Kit - BUG] Self Service Analytics Setup Failure

### ISSUE THREAD

**Issue by meredithhendren** [microsoft/coe-starter-kit#5362]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to setup self-service analytics to export Power Platform inventory and usage data. I have been following the guidance listed here: https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics. However, when I setup the data exports, I have repeatedly gotten failures, even after retrying multiple times. 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/131678130/234006327-0da3da3a-c8c3-4633-89aa-92c5a1699056.png">

### Expected Behavior

I expect the data exports to successfully be created within 24 hours of setup. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

PPAC version: 1.2023.411.10

### What app or flow are you having the issue with?

Data Export in Admin Center

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid this failure is in the product itself, and not in our kit. And so we will not be able to assist in getting you unblocked. However product support should be able to assist you. 

Here is how to contact support, if you do not already have another pre-existing relationship: [Get Help + Support - Power Platform | Microsoft Docs ](https://docs.microsoft.com/en-us/power-platform/admin/support-overview)
