### ISSUE TITLE
[CoE Starter Kit - BUG] Errors when opening Maker - Environment Request

### ISSUE THREAD

**Issue by thso77** [microsoft/coe-starter-kit#5363]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Two errors appear when opening the "Maker - Environment Request" app in the browser. The two errors are:
- The value 'Environment Requests' cannot be converted to a number.
- The value 'Data Policy Change Requests' cannot be converted to a number.

### Expected Behavior

There should be no errors when opening the app.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

Maker - Environment Request

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the Core Components Solution.
2. Open the "Maker  - Environment Request" app.
3. The two errors will appear at the top of the app.

AB#647

**Comment by Jenefer-Monroe** [comment]
sending to dev owner

**Comment by KanwarSingh** [comment]
I am getting the same issue when accessing the makers app, can you please confirm if there is any update.

![image](https://user-images.githubusercontent.com/26156698/236359406-5fe1ce0c-8744-4869-b77b-41dd3ef24139.png)

**Comment by manuelap-msft** [comment]
Closing out, these were fixed with the conversion of this app to custom pages.
