### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to edit dataflows in setup

### ISSUE THREAD

**Issue by pezlin** [microsoft/coe-starter-kit#5364]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am setting up a new CoE with Data Export. None of the nine Dataflows in the setup are possible to edit. Edit button is greyed out. Following these instructions: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#configure-connections-to-data-sources

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CoE Starter Kit April 2023

### What app or flow are you having the issue with?

Setup wizard

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
Can you share a screenshot of your full screen? Where are you navigating to to edit the dataflows from?

**Comment by pezlin** [comment]
> Can you share a screenshot of your full screen? Where are you navigating to to edit the dataflows from?

I navigated from the "root" of the solution since the link to open Dataflows in the Wizard wasn't possible to click. I then "played" the app and at that point it was possible to click the link and it opened up a similar page with the dataflows and on that page it was possible to edit the dataflows.
