### ISSUE TITLE
[CoE Starter Kit - BUG] Details not populated in PowerApps App and Flow Tables

### ISSUE THREAD

**Issue by Pothan-HP** [microsoft/coe-starter-kit#5366]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Every day, the **Admin | Sync Templates V3** flow generates new records in the corresponding tables for new Apps and Flows. However, it seems that there is an issue where certain columns are not being populated with data for some Apps and Flows, except for the **App/Flow ID** and **Environment Lookup** columns.
Attaching the screenshot for reference: 
![image](https://user-images.githubusercontent.com/129990223/234048086-25e2a09f-6568-4b0e-9665-8065a3db6081.png)

### Expected Behavior

All the columns to be updated with respective app/flow metadata.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin - Sync Templates V3

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. This is a way we currently catch some missed objects, the next run of **_Admin - Sync Templates V3_** should fill in the details if you leave them in place. Can you check that for me?

**Comment by Pothan-HP** [comment]
Hi @Jenefer-Monroe. Although **Admin - Sync Templates V3** is running daily, yet the data is not yet populated in the columns. I have attached a screenshot displaying the record created and modified timestamps for your reference.
Could you please look into this issue and provide any guidance or recommendations for resolving it?

**PowerApps App** table data
![image](https://user-images.githubusercontent.com/129990223/234190108-f41318e6-4ade-40d5-9e8f-0ab33f6226b9.png)

**Admin - Sync Templates V3** run history
![image](https://user-images.githubusercontent.com/129990223/234191495-f7911c89-ab63-4e37-bf8f-58145060f100.png)

**Comment by Pothan-HP** [comment]
I have attempted to follow the aforementioned steps, but unfortunately they did not resolve the issue. Additionally, the **_ModifiedOn_** details for the App/Flow are not being populated during either the first or second run.

Upon further observation, there appears to be **no difference in the data** between the outputs of the first and second runs.

**Data screenshot** 
![image](https://user-images.githubusercontent.com/129990223/234508507-6c356f5b-6ede-4576-8e3d-e6e54e6b1bd2.png)
![image](https://user-images.githubusercontent.com/129990223/234509313-279b5df7-3b95-4647-ac7f-2b3926bd127a.png)

**Flow run history**
![image](https://user-images.githubusercontent.com/129990223/234509899-47a129eb-6bbc-4bcb-a73e-a0f5e152ef47.png)

**Comment by Jenefer-Monroe** [comment]
OK. I'm afraid you will just need to do a [full inventory run](https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory) then. We are re-doing this logic to make the caught apps/flows go through the same logic as other apps so this issue should resolve with that new archtiecture.

**Comment by Pothan-HP** [comment]
So is this expected to be released in the next release? Also is there any temporary fix that we can do for now?

**Comment by Jenefer-Monroe** [comment]
Unfortunately the full inventory is the temporary fix.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
