### ISSUE TITLE
[CoE Starter Kit - QUESTION] Developer Compliance Center

### ISSUE THREAD

**Issue by mdlister** [microsoft/coe-starter-kit#5368]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

With the new Developer Compliance Center, I have updated the links for the new app and went to share the app with the makers groups but I can't find any reference for what dataverse permissions i need to set for them? 

![image](https://user-images.githubusercontent.com/38280500/234060398-d5a44faf-3065-4100-8027-0cd79710bec4.png)

I've raised the same for the official Microsoft Documents as they also all reference the canvas app. https://github.com/MicrosoftDocs/power-platform/issues/1900 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Developer Compliance Center App

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by mdlister** [comment]
@manuelap-msft I've seen your comment on the other ticket i've raised but I don't have that option to select Power Platform Maker SR even tho when i click manage roles i can see it?

**Comment by Jenefer-Monroe** [comment]
Hello, you must first share the app with the security role: ![image](https://user-images.githubusercontent.com/89584709/234064528-4be3e3b9-921b-4387-9335-189b1d7ff2a9.png)

And then you can add individuals to that custom SR if you'd like
![image](https://user-images.githubusercontent.com/89584709/234064660-13735332-5cb6-4e77-9133-f0cf6c6f90c9.png)

**Comment by mdlister** [comment]
Thanks Jenefer, When i share the app with the group, i only get the options in my screenshot for Administrator and System Customiser from the permissions drop down?

**Comment by mdlister** [comment]
Thanks I've figured it out. I didn't see the App selected in the screenshot and thought it was the new group. 

Thanks

![image](https://user-images.githubusercontent.com/38280500/234070853-30998f95-b978-4994-ade2-49241fdf3f81.png)

**Comment by Jenefer-Monroe** [comment]
oh wonderful news. Thank you for letting me know!
