### ISSUE TITLE
[ALM Accelerator - BUG]: Solution Checker is failing with 'Unauthorized' error

### ISSUE THREAD

**Issue by GU-VITA** [microsoft/coe-starter-kit#5369]
### Describe the issue

I am getting the following error when executing the Pull request pipeline. The job is failing when executing the Power Platform Checker

'Executing InvokePowerAppsChecker' 
Error: Operation returned an invalid status code \'Unauthorized\'

Task         : Power Platform Checker
Description  : Analyze solutions using Power Apps Checker endpoint
Version      : 2.0.19
'authN to admin API: authType=SPN; cloudInstance: UsGov' 
Endpoint: https://gov.api.advisor.powerapps.us/'

PS: My tenant is GCC and I am getting the same failure with the Power Platform Built Tool for Azure DevOps

### Expected Behavior

Expect the Pull Request to work with the solution checker.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230206.1

### Steps To Reproduce

1. Launch ALM Accelerator for Power Platfomr
2. Select Advanced Maker Experience
3. Clecik on Deploy Solutions

### Anything else?

![ALM Accelerator Issue](https://user-images.githubusercontent.com/119626174/234129658-23b7d99a-c111-4d8e-b120-0ace1c831085.png)
[logs_50.zip](https://github.com/microsoft/coe-starter-kit/files/11315080/logs_50.zip)

**Comment by mikefactorial** [comment]
@GU-VITA this appears to have been lost in the shuffle. This is a known issue in GCC. https://github.com/microsoft/coe-starter-kit/issues/5193 You can disable solution checker to work around the issue, but likely the solution is to give the Service Principal the correct permissions to run solution checker. Unfortunately, while we want to support GCC with the ALM Accelerator as a small team we don't have the resources to validate functionality in all clouds and do all of our testing in the public cloud. If you do find a resolution please let us know and we can work to update our documentation.

**Comment by GU-VITA** [comment]
This would be an acceptable resolution if the documentation would say not tested in GCC or GCC High.
