### ISSUE TITLE
[ALM Accelerator - BUG]: Redirect Power App Url for GCC tenant

### ISSUE THREAD

**Issue by GU-VITA** [microsoft/coe-starter-kit#5370]
### Describe the issue

'Open Solution' button redirects to the commercial Power Apps studio.

My tenant is GCC is the redirect should go to https://make.gov.powerapps.us/

### Expected Behavior

Application should pick up the Power Apps Studio Url from an environment variable

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230206.1

### Steps To Reproduce

Browse to ALM Accelerator for Power Platform
Clicik on 'Open Solution'
![ALM Accelerator Issue](https://user-images.githubusercontent.com/119626174/234130566-962c4e2d-b12a-4b32-ab53-ca556edd0c8f.png)

**Comment by mikefactorial** [comment]
@GU-VITA thanks for reporting this. Will look into how to make the redirect more dynamics based on specific clouds
