### ISSUE TITLE
Upgrade to Core Components  4.4.2 fails both imported solution and existing solution must be managed for upgrade

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#5371]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I apply hotfix April 2023 Patch 1 it fails - 
The imported solution and the existing solution must both be managed for upgrade.

### Expected Behavior

I expected the upgrade to be applied

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

None- Import

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Download patch from Github
2. Import Solution
3.  Browse for solution File
4. select solution file
5. click Next
6. Click Import
See error

**Comment by NPrice99** [comment]
![image](https://user-images.githubusercontent.com/8484048/234251397-a38f62df-e0c6-4f93-9716-9bac78e69692.png)

**Comment by manuelap-msft** [comment]
Hello,

we have seen this error before when any of the apps or flows of the existing managed solution were open in Edit mode or had an unmanaged layer. Can you check if you or anyone else has any of the apps/flows open in edit mode, or if any of them have unmanaged layers?

Thank you
Manuela

**Comment by NPrice99** [comment]
I have checked for unmanaged layers so could not find any - tried again - still same issue -- deleted  version 4.4.1 - tried to delete 3.56 previous version to 4.4.1. "Could not delete due to dependencies" - looks like the whole of the core components.  Cannot find way to remove these dependencies - stuck !

**Comment by Jenefer-Monroe** [comment]
I'm just not sure unfortunately. That original issue was not with the kit but is just some product code around import depending on the state of your current solution. For me it was when I had objects open. And now I just dont know what state you are in. 
It sounds like this is not a production envt given you were deleting core so perhaps just reset it or start from scratch?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
