### ISSUE TITLE
[Power Platform communication site template] Missing header menu

### ISSUE THREAD

**Issue by MichaelRoth42** [microsoft/coe-starter-kit#5372]
### Describe your bug, question or feature ask.

I was just deploying the Power Platform Community Hub and everything went well so far. No error messages, smooth deployment. 

But I'm missing the header menu. Did you change the default settings, so I have to switch it on or did something went wrong?

![image](https://user-images.githubusercontent.com/58400001/234254222-b1528ea9-2759-42c8-9a40-08abac1d8303.png)

**Comment by manuelap-msft** [comment]
Hello,

we've seen this before when the site nav was not enabled, can you check that?
![image](https://user-images.githubusercontent.com/55705669/234256514-4f2a74e6-3eab-4bae-bc3c-ffe8326b4ede.png)

In all cases we've seen, editing the navigation, and saving it usually does the trick. Can you see if that helps?

**Comment by MichaelRoth42** [comment]
Yip that was the issue, thanks a bunch 🙏
