### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Sebaasf92** [microsoft/coe-starter-kit#5373]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In our team we have two different reports about what our tenant contains. One is an old version of the dashboard and the other one we got it after actualizing the starter kit. Both of them shows different ammount of apps, flows, environments, etc. How can we reach the correct information? 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

March 2023

### What app or flow are you having the issue with?

Dashboard

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello. You can expect reports to be different depending on many factors. For one thing the delay is different, newly created/deleted objects can take a few days to show up in the datalake for example and that is different than sync flows. And I dont know what state your old version is in. 

Unfortunately, the only way to proceed here is to find cases where you expect to see something in the inventory but do not, and investigate on a case by case basis.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
