### ISSUE TITLE
[CoE Starter Kit - BUG] Can we change who the shared with mail from the product comes from

### ISSUE THREAD

**Issue by akshaya-ak** [microsoft/coe-starter-kit#5375]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow Name: App Catalog > Request Access

1) App Catalog app in core solution: 
![image](https://user-images.githubusercontent.com/71701878/234852848-2b91c884-add4-41a1-928c-c1b96b4f13a5.png)

2) user request App for access:
![image](https://user-images.githubusercontent.com/71701878/234317630-4565b59c-ea55-42a3-9cda-d9fe4dc4ea5c.png)

3) After requesting, app owner will receive teams bot to accept/Reject the request:
![image](https://user-images.githubusercontent.com/71701878/234853026-814a33ec-2306-4154-a812-c65150130df9.png)

![image](https://user-images.githubusercontent.com/71701878/234853149-3663ea0e-a23e-44f7-9f00-55c2929e432b.png)

4) After the owner accepts the request: User receives a mail for the same:
![image](https://user-images.githubusercontent.com/71701878/234853396-e9ee4468-0afe-43d5-8b97-39c60c4be081.png)

5) In step number 3, Prema Pasala (User)  has requested access for an app through app catalog to the app owner (Edith), when the  request is granted through teams bot, Instead of receiving the mail from App Owner Id (Edith) the user (Prema) is receiving this mail from her user Id (Prema).
![image](https://user-images.githubusercontent.com/71701878/234853653-23ba9354-854d-4712-b051-85554b9a18e5.png)

### Expected Behavior

When the app owner shared the app with the user who requested the access through the teams bot, the user should receive a email that ( app owner (Edith) ) has shared the app with you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

App Catalog

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1) App catalog app - core component - CoE
2) Request access for an app through Request access button
3) App owner will receive an teams bot to grant the request.
4) Once owner grants it, the user (requestor) receives an email. 

### Anything else?

[App Catalog Issue.docx](https://github.com/microsoft/coe-starter-kit/files/11323965/App.Catalog.Issue.docx)

**Comment by manuelap-msft** [comment]
Hello,

we're already tracking this under #5340 which you also opened for this issue. Please note that the CoE Starter Kit is an unsupported collection of templates/tools, although we try our best to triage issues on GitHub we are a very small team and can't offer an SLA on when we are able to resolve or respond. 

Thank you for understanding,
Manuela

**Comment by manuelap-msft** [comment]
Closing as duplicate.

**Comment by akshaya-ak** [comment]
Hey, I totally understand, However, this is another issue, 5340 is the issue where user is not able to launch the app, however this issue: 5375 - is regarding the email that the user is receiving once the owner grants the access.

I request you to please have a look at this issue once.
Thanks

**Comment by akshaya-ak** [comment]
Hey, any update on this ?

**Comment by akshaya-ak** [comment]
I apologize for the inconvenience caused,

I request your assistance for this issue, and help me with further steps

**Comment by Jenefer-Monroe** [comment]
I do think this is the same issue, as we do not send this mail, this a mail from the product. And that if we fix the other one this one will be fixed for free. Will hold to validate with that fix.

**Comment by Jenefer-Monroe** [comment]
OK so this one we cannot make behave differently. It will send as the person who's identity is being used in the Run Only of this helper. This is just product behavior. But I do have a local fix for the other issue. 
![image](https://user-images.githubusercontent.com/89584709/236627649-09162133-1754-46aa-acbc-148d2816a2be.png)
![image](https://user-images.githubusercontent.com/89584709/236627696-7c4e481f-8600-4b0a-9c4c-58c739379341.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
