### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard | Compliance Process missing apps to share

### ISSUE THREAD

**Issue by BrentEllingwood** [microsoft/coe-starter-kit#5376]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When going through the setup wizard, the Share Apps step says there is only 1 app but no apps display to share from here. (I was able to manually share the app, but wanted to log the bug for a future fix)
![Screenshot 2023-04-25 124136](https://user-images.githubusercontent.com/131800293/234345501-dffafc7a-76d9-41ba-88d1-8283ddc3fb1c.png)

### Expected Behavior

The app to share shows up.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Thank you for raising this! We're already tracking this under #5319 and have a fix targeted for our next release. I'll close this as a duplicate as we're already tracking that.
