### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE BYODL Makers dataflow

### ISSUE THREAD

**Issue by Natashamg** [microsoft/coe-starter-kit#5377]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am unable to edit the CoE BYODL Makers dataflow, not sure if I am missing something or skipped a step or something.
Not able to turn on the dataflow as it is a managed solution and the dataflows are not showing up in the dataflows tab outside the solution.

![dataflow ceo](https://user-images.githubusercontent.com/23278100/234346929-309bf08b-acd6-48ae-a754-fac25a1ab695.PNG)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

CoE BYODL Makers dataflow

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
Hello,

you won't be able to edit the dataflow from the managed solution. You'll have to do it from the main navigation under make.powerapps.com > select Dataflows there.
![image](https://user-images.githubusercontent.com/55705669/234347849-0b2d4af3-4ae1-48b1-ae8b-f9a775ded52b.png)

If you don't see Dataflows in the navigation here, you may have to add it via "More"
![image](https://user-images.githubusercontent.com/55705669/234347978-179fd463-2b4c-4ef3-aeda-c5015a644f45.png)

If you're using the setup wizard and are on the "Configure dataflows" step, the link to edit dataflows there should take you to the correct page as well.

**Comment by Natashamg** [comment]
I've tried from the main navigation and the link from the wizard but the dataflows don't show up, they only show up in the solution. I've tried to search them by owner (me) from 'All Dataflows' as well.

![image](https://user-images.githubusercontent.com/23278100/234349075-0eb0eef2-448b-4301-afbc-1bed1d8e18b2.png)

**Comment by Natashamg** [comment]
Yes I installed the CoE kit from my account, I do have admin access and I've also checked with the service account but it still isn't showing up. Can you think of anything else I should be doing or could do to debug this?

**Comment by Jenefer-Monroe** [comment]
Can you enter that owner name (Natasha) here to see if they show up? 
![image](https://user-images.githubusercontent.com/89584709/234362029-37dda442-d41e-4fdb-9ec8-4bef4e87450d.png)

**Comment by Natashamg** [comment]
I've already tried that, nothing shows up. Do you think deleting the solution and reinstalling would help?
![image](https://user-images.githubusercontent.com/23278100/234364134-165ec73c-f86f-4015-b5a0-4013e7918f49.png)

**Comment by manuelap-msft** [comment]
Do you have a guest account in that tenant? It looks like on the solution page your name shows up as Natasha George and here it shows up as George, Natasha. In our screens, the names look exactly the same in the solution page and in the Dataflow page. Is there a way to search for and select Natasha George?

**Comment by Natashamg** [comment]
The is just how it is set up in our organization, names show as last name,
first name

**Comment by Jenefer-Monroe** [comment]
If you go to the product Dataflow table
![image](https://user-images.githubusercontent.com/89584709/234404716-1ff737e1-34c0-4833-b2b5-d4a86142e10a.png)

Update to see these columns. 
![image](https://user-images.githubusercontent.com/89584709/234405106-05bfc280-90d7-43ab-acc9-8136bee36cea.png)

Do you see them there? You should see each listed twice, Owner as you for all, and Created By with you for half. Is that what you see?

**Comment by Natashamg** [comment]
I am Creator and Owner but I see it only once
![image](https://user-images.githubusercontent.com/23278100/234405863-40dc6d44-eb98-47b3-9de0-b0c561188d72.png)

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names. And then what region is your envt? 
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Natashamg** [comment]
Region: US
![image](https://user-images.githubusercontent.com/23278100/234660513-9cd8a14d-31f9-4bd5-a5ed-37277c27b0e8.png)

**Comment by Jenefer-Monroe** [comment]
I'm really not sure what happened here. It seems like something went wrong on your install. From here I would just be guessing. 
You may need to create a support ticket and just say that your Dataflows are not showing up outside of the solution.

**Comment by Natashamg** [comment]
I got in touch with support, the issue is resolved. My environment had admin mode enabled, so the dataflows wouldn't show up. I had to disable it and import the solution again and it shows up now.
Thanks for your help!

**Comment by Jenefer-Monroe** [comment]
Thank you so much for letting us know the resolution. This will help us if others fall into this same state. Appreciate you!
