### ISSUE TITLE
[Power Platform communication site template] ISSUE TITLE

### ISSUE THREAD

**Issue by federicoruiz** [microsoft/coe-starter-kit#5378]
### Describe your bug, question or feature ask.

Hi,

There is a way to install the template without using PnP? In my company the use of this powershell module is unavailable, and I need to justify the use because of this -->

![permission-pnpmodule](https://user-images.githubusercontent.com/6534864/234374144-d6159b59-e052-4181-a371-c35500580092.png)

Apparently, the use of this module requires unjustifiable set of permissions. I tried to login using weblogin and tried to use a sharepoint app user, but it generated the 50% of the site.

**Comment by petepuu** [comment]
You can try UseWebLogin but I think that need legacy auth be enabled https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#example-9 

 It does not create the AAD application. In the Deploy script there are 3 connect-pnponline commands you need to change

**Comment by petepuu** [comment]
When you tried UseWebLogin did you replace it in all 3 connect-pnponline commands in the script?

**Comment by petepuu** [comment]
Menu is often not enabled for some reason

**Comment by petepuu** [comment]
@federicoruiz You can try these commands to save the pnp binary template to XML and that way see what the template is provisioning

$t = Read-PnPSiteTemplate -Path C:\temp\PowerPlatformHub\template.pnp

Save-PnPSiteTemplate -Template $t -Out C:\temp\PowerPlatformHub\template.xml
