### ISSUE TITLE
[CoE Starter Kit - BUG] Cloud Flow Inventory Still Broken After Upgrade to 4.4.2

### ISSUE THREAD

**Issue by thso77** [microsoft/coe-starter-kit#5380]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

My organization's tenant used to have 1200 flows in the default environment, and after the April upgrade to 4.4.1, there were only 262. I upgraded the solution with Hot Fix 1, and reran the sync flows, however this did not fix the issue.

### Expected Behavior

The Overview Dashboard in the Power Platform Admin View app should display the correct number of flows in the tenant.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
You will need to run a full inventory to get them back. The hotfix was for the issue that removed them. 
https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory

**Comment by thso77** [comment]
Thank you! Somehow I missed this.

**Comment by Jenefer-Monroe** [comment]
Oh no problem, we happened to have another shift in our inventory coming for May that would not require the full inventory now but it was too big a change for this hotfix. 
Thank you for using CoE!
