### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can we use same datalake storage for DEV and PROD

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#5383]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi @Jenefer-Monroe  - 

Can we use the same storage for both DEV and Prod instances of CoE starter kit?

Thanks,
Devendra

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

I think you're referring to the data you get into your storage account from the Data Export feature, right? If so, yes you can use the same data for dev and prod environments. We only read the data, so the storage account is used for read-only purposes only. 

Hope that helps,
Manuela

**Comment by devvelegandla** [comment]
Thanks @manuelap-msft 

That is correct, we are using the same storage account for BYODL feature.
