### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by NeelimaRongali** [microsoft/coe-starter-kit#5384]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi May i know where can i find Latest Release notes. I do checked the release link and feature questions and all. But i wanted to know what are all the latest upgrades or enhancements made on Kit and what deprecations as well. Where can i find each and every detail of Upgrade in CoE Starter Kit. Please help me out

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by DominicMeznik** [comment]
I´m pretty sure all changes also have an according ticket number. So I guess going through all the linked tickets in the change log is the best way to do this. That´s how I do it at least.

**Comment by NeelimaRongali** [comment]
Are you speaking about log mentioned in this Article "https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-April2023". can you please confirm. Or is there any place i can find??

**Comment by manuelap-msft** [comment]
Thank you [DominicMeznik](https://github.com/DominicMeznik)!! 

Yes that's correct, we (the CoE team) raise tickets on GitHub for ourselves as well for three reasons
- to track work that we're doing and when we're doing it (in milestones)
- to be completely transparent about the work we're doing - everyone can comment on our open items etc
- to have one place of truth for all that we're working on - like Dominic said, it'd be chaos if we tracked some of our work items on GitHub and some of them elsewhere. We prefer to do all our work "in the open" to give everyone a chance to prepare for what's coming too.

Here's an example of an issue we raised for ourselves to work on
https://github.com/microsoft/coe-starter-kit/issues/5203

You can also find our upcoming milestones here and see what items are targeted to be part of an upcoming release - though please note that we do move issues in/out of releases during our development cycle quite often but it can give you an idea of some of the things we're working on.
https://github.com/microsoft/coe-starter-kit/milestones

**Comment by NeelimaRongali** [comment]
Thanks you both. It helped me a lot.
