### ISSUE TITLE
[CoE Starter Kit - BUG] Run Setup Flows in upgrade wizard don't start

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#5385]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When running the setup wizard on an existing setup to ensure the configuration and make changes the "Run Setup Flows" step in the wizard never runs the flows even if you click the button "ReTry Run setup flows".

![image](https://user-images.githubusercontent.com/48433526/234558718-07e207e7-8a99-4bf6-8029-a43d11e266ac.png)

### Expected Behavior

Expect the flows to run automatically or by clicking "Retry run setup flows"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

- Login as Power Platform Service Account with Power Platform Admin Role.
- Run through the upgrade wizard and when you get to the "Run Setup Flow" step non of the 3 flows start. Even if triggered by manually clicking the retry button.
- Tested in 2 separate Environments (Dev/ Test) with 2 separate service accounts. (Same experience in both environments)

**Comment by DominicMeznik** [comment]
You could check in the Flow details directly, if they´re really not triggering. I had a similar case, where the UI just wouldn´t update correctly, but the Flows were running anyways.

**Comment by Jenefer-Monroe** [comment]
I've also seen this repro a few times but never consistently. The logic here is more complex than you might imagine. We will continue to try and make it nicer but in the meantime please follow the link to make sure the flows have completed since the upgrade, and then click next. 
Sorry for the complexity.

**Comment by myatix** [comment]
@Jenefer-Monroe I already checked the flow history and they never ran. I ended up manually triggering the flows in our Dev Environment. 
As for our Test Environment they never ran either but I haven’t manually triggered these just in case you wanted to check/ troubleshoot something!

**Comment by Jenefer-Monroe** [comment]
Thank you for that offer, please do go ahead and run them so you are unblocked. We have what we need to investigate on this one. Appreciate it!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
