### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Command Center screen gives an error due to Hotfix release name(?)

### ISSUE THREAD

**Issue by jukkan** [microsoft/coe-starter-kit#5388]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Now that the latest release available is called "CoE Starter Kit Core Components April 2023 - Hotfix 1", this seems to break the logic that is used on the CoE Support page of the CoE Admin Command Center app to parse the date information. This worked before the hotfix, now it gives the error message: "The value ' Core Components April 2023 - Hotfix 1' cannot be converted to a date or time value."

![image](https://user-images.githubusercontent.com/10254155/234587470-a70a6cb5-a093-4c54-9c83-1bee4c564f7e.png)

### Expected Behavior

Seeing the installed and latest available versions.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Oops, we didn't consider our highly advanced string matching logic in the Command Center when we released the hotfix ;) 

I changed the hotfix name (in GitHub) to allow for our matching and it seems to work again now:
![image](https://user-images.githubusercontent.com/55705669/234597944-151d9443-2aec-449a-b050-f9fe3171c3be.png)
