### ISSUE TITLE
[CoE Starter Kit - BUG] Blank apps and flows inside Power Platform Admin View app

### ISSUE THREAD

**Issue by annsarP** [microsoft/coe-starter-kit#5392]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello!  While upgrading with an April version of CoE we saw errors trying to load tables Apps and Flows into Power Bi reports. That's when we found out that we have 3 completely blank apps rows and 4 flows with blank names inside our Power Platform Admin View app data. 
![image](https://user-images.githubusercontent.com/127112137/234778365-d0b01d01-751b-419e-8b4c-9625c0d17642.png)
![image](https://user-images.githubusercontent.com/127112137/234777946-e37b1ff7-093a-402e-a548-46127c1d61d7.png)
(Please notice that apps don't even have an ID string and how weird is date of modification for both of these tables.)

As I can see, rows has been created Oct-22 - March-23 and latest update on them was a couple of days after importing April solutions. (We're not sure if it has been blank from the beginning, audit history is blank too, but we haven't notice this before). 
Checked Sync Flow runs, it had some problems for a few days because after import some of the flows was turned off, but we turned everything required on and for now they are running without any errors or failures. 

On top of that we found out that some of the apps are missing from Power Platform Admin view data. Currently we have 80 apps for one of the environment while in Admin Center I counted 83 of them. I already saw similar topic [here](https://github.com/microsoft/coe-starter-kit/issues/3234), but I've turned off any filters on the table, checked sync flows and updated environment data to run them for specific environment as you suggested and number of apps has updated but it's still not correct. It's hard for us to tell which exact apps are missing because in our tenant we have over 100 environments and over 800 apps. 

I wasn't sure if I should post it as a bug or question, because the problem might be on our side. Please guide us on next steps. Should we delete blank rows and re-run sync flows or do something else? 

Thank you in advance.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately you fell into a bug as described in https://github.com/microsoft/coe-starter-kit/issues/5239

You've already upgraded to the hotfix so thats good, you wont fall in again, but now you'll need to do a full inventory to get them back. 
Please see https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory

We;re working to make recovery easier in May.

**Comment by annsarP** [comment]
Hi. Thank You, sorry for duplicate, couldn't find this topic before. We did full inventory yesterday and it worked like a charm in case of this blank rows. Blanks are gone but number of apps haven't change and it is still incorrect :( We have apps modified in 2019 in Dataverse but no app that was modified 3 months ago... Again no errors on sync flows... Here are our environment variables regarding this case:

**Comment by Jenefer-Monroe** [comment]
No problem on the dupe, appreciate you trying to find it!
Correct unfortunately [Unpublished model-driven apps](https://learn.microsoft.com/power-platform/guidance/coe/limitations#unpublished-model-driven-apps) arent exposed to us in a way that we can gather them.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
