### ISSUE TITLE
[ALM Accelerator - BUG]: Error while running the install on CLI

### ISSUE THREAD

**Issue by firozozman** [microsoft/coe-starter-kit#5398]
### Describe the issue

I get the following error when running the following command

 coe alm install -o install.json 

ERROR: unrecognized arguments: --available-to-other-tenants false

### Expected Behavior

Installation completes

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.7

### Steps To Reproduce

Open the Terminal window on Mac
Run  coe alm install -o install.json

**Comment by mikefactorial** [comment]
@firozozman we're moving away from support of the coe-cli as the preferred installation method and is currently marked as deprecated. Recommend using the following doc for setup and install https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks.

**Comment by mikefactorial** [comment]
Closing this out as there's no further action required here.
