### ISSUE TITLE
[ALM Accelerator - BUG]: Deployment Pipeline - Set EnvironmentId Error

### ISSUE THREAD

**Issue by jfung85** [microsoft/coe-starter-kit#5399]
### Describe the issue

We have a solution committed successfully and now trying to deploy to our TEST environment. In the deployment pipeline, the "Set EnvironmentId" step fails with this error:
            The user is not a member of the organization.
                Operation returned an invalid status code 'Forbidden'

### Expected Behavior

We expect to run the Set EnvironmentId step successfully as the user is an admin account with elevated permissions.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Accelerator Version: 1.0.20230405.2(Managed)

### Steps To Reproduce

1. Configure Deployment Settings for a solution
2. Commit Solution
3. Deploy Solution to TEST environment
4. Check Pipeline results to see error occurs at Set EnvironmentId step

### Anything else?

    [ 'Connected to... Unable to validate connection to default environment' ]
    [ 'Authentication profile created' ]
    [ '    * DATAVERSE                                https://<REMOVED>.crm.dynamics.com/       : ***     Public' ]
    [ '' ]
    [ 'The Authentication Result: \'***\' authenticated successfully.,Validating connection...,Connected to... Unable to validate connection to default environment,Authentication profile created,    * DATAVERSE                                https://<REMOVED>.crm.dynamics.com/       : ***     Public,' ]
    [ 'Connected to... Microsoft PowerPlatform CLI' ]
    [ 'Version: 1.22.3+g8af83fd' ]
    [ '' ]
    [ 'Error: One or more errors occurred.' ]
    [ '    One or more errors occurred.' ]
    [ '        One or more errors occurred.' ]
    [ '            The user is not a member of the organization.' ]
    [ '                Operation returned an invalid status code \'Forbidden\'' ]
    [ '' ]
    [ '' ]
    [ 'Usage: pac org who' ]
    [ '' ]
    [ '  This command does not take any arguments.' ]
    [ '' ]
    ##[error]error: 1
    ##[error]failed: Connected to... Microsoft PowerPlatform CLI
    Version: 1.22.3+g8af83fd

    Error: One or more errors occurred.
        One or more errors occurred.
            One or more errors occurred.
                The user is not a member of the organization.
                    Operation returned an invalid status code 'Forbidden'

    Usage: pac org who

      This command does not take any arguments.

    [ 'Authentication profiles and token cache removed' ]
    [ 'The Clear Authentication Result: Authentication profiles and token cache removed' ]
    ##[error]Error: Connected to... Microsoft PowerPlatform CLI
    Version: 1.22.3+g8af83fd

    Error: One or more errors occurred.
        One or more errors occurred.
            One or more errors occurred.

**Comment by mikefactorial** [comment]
@jfung85 based on this it looks like the service principal doesn't have access in the deployment environment "Operation returned an invalid status code \'Forbidden\'' ]" have you added the service principal as an app user in the target environment as a system admin?

**Comment by mikefactorial** [comment]
There are two parts to the pipelines being able to access a deployment environment or a maker environment 
1. There has to be a service connection to that environment using the service principal's information (e.g. tenant, client and secret)
2. There has to be an app user in the deployment or development environment for the same service principal in the environment with (sys admin role). Once these are setup you should have any other access issues.

**Comment by jfung85** [comment]
Hi,

For item 1, I believe I was able to configure the service connection correctly by using the ALM Accelerator Admin app.
For item 2, I have a service principal but I don’t know how to add it as an app user to the environment. Is there any article or more specific steps you could provide to do this?

Thanks,
Jonathon

**Comment by mikefactorial** [comment]
Hi @jfung85 instructions are here for setting up the App User. https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#set-up-makers-to-use-the-alm-accelerator-for-power-platform-app

Might make sense to add this to the maintenance tasks as well. Will add this to our list of todos for the may release.

**Comment by jfung85** [comment]
Hi Mike,

I just checked and the service principal has already been setup as an App User with System Admin permissions. I think both items you mentioned are covered. Is there another way to confirm proper permissions are set?

Jonathon

**Comment by jfung85** [comment]
I just deleted my previous message because I realized that I only checked on the source environment which did have the app user setup but didn't check the destination environment which was missing. After setting up the service principal on the destination environment, it was able to successful complete this step. Thanks @mikefactorial !

**Comment by mikefactorial** [comment]
Thanks for reporting back @jfung85. Will close this issue out for now.
