### ISSUE TITLE
Action 'Get_Model_Driven_App_from_CoE' failed

### ISSUE THREAD

**Issue by tsegato** [microsoft/coe-starter-kit#54]
I get following error. Any suggestions what can cause this?

![image](https://user-images.githubusercontent.com/43033640/106861299-ddc1fb00-66c5-11eb-8eb1-39bc983a70cb.png)

{
  "error": {
    "code": "0x80040217",
    "message": "admin_app With Id = 83aa0ab5-04c4-e911-xx-xxDoes Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "xx-7b59-eb11-xx-xx",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "x-x-464c-x-x",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_app With Id = x-x-x-x-xDoes Not Exist"
  }
}

**Comment by tsegato** [comment]
Let me know if you need more info on this.

**Comment by devkeydet** [comment]
@tsegato  - This is not the active repo for the COE Starter Kit yet.  See:
https://github.com/microsoft/coe-starter-kit/blob/main/README.md

Please file your issue there.  Thanks!
