### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYODL Dashboard Sync taking long time

### ISSUE THREAD

**Issue by jayakumarkgds** [microsoft/coe-starter-kit#5401]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

After i have deployed BYODL Solution ,PowerBi dashboard sync is running more than 48 Hrs and still not completed. 

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Can you please show me a screenshot of what you mean?

**Comment by jayakumarkgds** [comment]
Find below screenshot
![image](https://user-images.githubusercontent.com/87489417/235175021-2a9daf95-c998-4289-a3e2-dee6791d6550.png)
Also we faced different errors while trying to sync the powerbidasboard first time


[ Description = "Environment URL of the environment where the CoE Starter Kit is installed, e.g. https://mycoe.crm.dynamics.com" ]
shared #"CoE Starter Kit Environment" = "https://<>.crm4.dynamics.com/" meta [IsParameterQuery=true, Type="Any", IsParameterQueryRequired=true];

shared Environment = let
    Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_environments = entities{[EntitySetName="admin_environments"]}[Data],
    #"Renamed Columns" = Table.RenameColumns(admin_environments,{{"admin_environmentcreatedon", "Created"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"admin_adminmicrosoftteamsenvironmentstatus", "admin_adminmicrosoftteamsenvironmentstatus_display", "admin_adminreason", "admin_adminreviewon", "admin_businessarea", "admin_businessjustificationdate", "admin_makerrequirementbusinessimpact", "admin_makerrequirementbusinessimpact_display", "admin_makerrequirementbusinessjustification", "admin_microsoftteamsid", "admin_microsoftteamsurl", "createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "processid", "stageid", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "traversedpath", "utcconversiontimezonecode", "versionnumber", "admin_adminrequirementriskassessment", "admin_adminrequirementriskassessment_display", "admin_adminrequirementriskassessmentstate", "admin_adminrequirementriskassessmentstate_display", "admin_allocatedenvironmentcapacity", "admin_connectedgroupid", "admin_recordguidasstring", "admin_numberofflows_state", "admin_numberofapps", "admin_numberofapps_date", "admin_numberofapps_state", "admin_numberofconnectors", "admin_numberofconnectors_date", "admin_numberofconnectors_state", "admin_numberofflows", "admin_numberofflows_date", "admin_hasdlppolicy", "admin_excusefromappquarantineflow", "admin_excusefromarchivalflows", "admin_excusefromcomplianceflow", "admin_excusefromemptyenvironmentcleanup", "admin_excusefrominventory"})
in
    #"Removed Columns";

shared Connector = let
Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_connectors = entities{[EntitySetName="admin_connectors"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_connectors,{"admin_adminrequirementreviewedconnector", "admin_adminrequirementriskassessment", "admin_adminrequirementriskassessment_display", "admin_makerrequirementaccessmanagement", "admin_makerrequirementbusinessjustification", "admin_makerrequirementconditionsofuse", "admin_makerrequirementdependencies", "admin_recordmodified", "createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "processid", "stageid", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "traversedpath", "utcconversiontimezonecode", "versionnumber", "admin_adminrequirementriskassessmentstate", "admin_adminrequirementriskassessmentstate_display", "admin_compliancerequestedon", "admin_recordguidasstring"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"admin_displayname", "admin_connectordisplayname"}}),
    #"Lowercased Text" = Table.TransformColumns(#"Renamed Columns",{{"admin_id", Text.Lower, type text}})
in
    #"Lowercased Text";

shared #"Flow Action Details" = let
 Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_flowactiondetails = entities{[EntitySetName="admin_flowactiondetails"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_flowactiondetails,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber"})
in
    #"Removed Columns";

shared NonProdWords = let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCnENDlGK1QExfAPADN9KMOWSmpsPZjjnF1Qq5KeB2boxpQYGxqlgdnBibkEOkBkLAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Label = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Label", type text}})
in
    #"Changed Type";

shared NonProdNameCheck = let
    BadWordMatch = (AppName) =>
    let WordList = Table.Column(NonProdWords,"Label"),
    Matchlist = List.Transform(WordList, each Text.Contains(Text.Lower(AppName), Text.Lower(_))),
    TrueMatches = List.AnyTrue(Matchlist),
    Score = if TrueMatches then 1 else 0
    in Score
in
    BadWordMatch;

shared #"Virtual Agent" = let
 Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_pvas = entities{[EntitySetName="admin_pvas"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_pvas,{"admin_adminrequirementreviewedbot", "admin_adminrequirementriskassessment", "admin_adminrequirementriskassessment_display", "admin_makerrequirementaccessmanagement", "admin_makerrequirementbusinessimpact", "admin_makerrequirementbusinessimpact_display", "admin_makerrequirementbusinessjustification", "admin_makerrequirementdependencies", "admin_makersubmittedrequirements", "admin_mitigationplanprovided", "createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "processid", "stageid", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "traversedpath", "utcconversiontimezonecode", "versionnumber"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"admin_pvaowner"}, Makers, {"admin_makerid"}, "Makers", JoinKind.LeftOuter),
    #"Expanded Makers" = Table.ExpandTableColumn(#"Merged Queries", "Makers", {"admin_city", "admin_department", "admin_displayname"}, {"Makers.admin_city", "Makers.admin_department", "Makers.admin_displayname"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Expanded Makers",{"admin_recordguidasstring", "admin_adminrequirementriskassessmentstate", "admin_adminrequirementriskassessmentstate_display"})
in
    #"Removed Columns1";

shared #"Virtual Agent Component" = let
 Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_pvacomponents = entities{[EntitySetName="admin_pvacomponents"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_pvacomponents,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber"})
  
in
    #"Removed Columns";

shared #"Virtual Agent Flows" = let
 Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_pvacomponentflowlookups = entities{[EntitySetName="admin_pvacomponentflowlookups"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_pvacomponentflowlookups,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber"})
   
in
    #"Removed Columns";

shared RPA = let
 Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_rpas = entities{[EntitySetName="admin_rpas"]}[Data],
    #"Added Custom" = Table.AddColumn(admin_rpas, "admin_notmodifiedsincecreated", each if [[admin_rpamodifiedon]] = null 
or 
Duration.TotalMinutes([admin_rpamodifiedon]-[admin_rpacreatedon])<2 
then 1 
else 0),
    #"Invoked Custom Function" = Table.AddColumn(#"Added Custom", "admin_nonprodappnamecheck", each NonProdNameCheck([admin_displayname])),
    #"Removed Columns" = Table.RemoveColumns(#"Invoked Custom Function",{"admin_adminrequirementreviewedrpa", "admin_adminrequirementriskassessment", "admin_adminrequirementriskassessment_display", "admin_clientdatajson", "admin_makerrequirementbusinessimpact", "admin_makerrequirementbusinessimpact_display", "admin_makerrequirementbusinessjustification", "admin_makerrequirementdependencies", "admin_makersubmittedrequirements", "admin_mitigationplanprovided", "createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"admin_rpaowner"}, Makers, {"admin_makerid"}, "Makers", JoinKind.LeftOuter),
    #"Expanded Makers" = Table.ExpandTableColumn(#"Merged Queries", "Makers", {"admin_city", "admin_department", "admin_displayname"}, {"Makers.admin_city", "Makers.admin_department", "Makers.admin_displayname"})
in
    #"Expanded Makers";

shared #"RPA Sessions" = let
 Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_rpasessionses = entities{[EntitySetName="admin_rpasessionses"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_rpasessionses,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber"})
    
in
    #"Removed Columns";

shared #"Power Platform User" = let
    Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_powerplatformusers = entities{[EntitySetName="admin_powerplatformusers"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_powerplatformusers,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber"})
in
    #"Removed Columns";

shared Portals = let
    Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_portals = entities{[EntitySetName="admin_portals"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_portals,{"timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber", "createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"admin_portalowner"}, Makers, {"admin_makerid"}, "Makers", JoinKind.LeftOuter),
    #"Expanded Makers" = Table.ExpandTableColumn(#"Merged Queries", "Makers", {"admin_city", "admin_department", "admin_displayname"}, {"Makers.admin_city", "Makers.admin_department", "Makers.admin_displayname"}),
    #"Replaced Value" = Table.ReplaceValue(#"Expanded Makers",null,"Unknown",Replacer.ReplaceValue,{"Makers.admin_displayname"})
in
    #"Replaced Value";

shared #"Environment Capacity" = let
    Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_environmentcapacity = entities{[EntitySetName="admin_environmentcapacities"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_environmentcapacity,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber"}),
    #"Sorted Rows" = Table.Sort(#"Removed Columns",{{"admin_actualconsumption", Order.Descending}})
 in
    #"Sorted Rows";

shared byod_apps = let
    Source = PowerBI.Dataflows(null),
      #"workspace" = Source{[workspaceId=#"Power BI Workspace ID"]}[Data],
    #"dataflow" = #"workspace"{[dataflowId=#"Power BI Dataflow ID"]}[Data],
    Apps1 = #"dataflow"{[entity="Apps"]}[Data],
    #"Invoked Custom Function" = Table.AddColumn(Apps1, "admin_nonprodappnamecheck", each NonProdNameCheck([name])),
    #"Added Custom" = Table.AddColumn(#"Invoked Custom Function", "admin_notmodifiedsincecreated", each if [lastModifiedTime] = null 
or 
Duration.TotalMinutes([lastModifiedTime]-[createdTime])<2 
then 1 
else 0),
    #"Removed Duplicates" = Table.Distinct(#"Added Custom", {"appId"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates", {"createdPrincipalId"}, Makers, {"admin_makerid"}, "Makers", JoinKind.LeftOuter),
    #"Expanded Makers" = Table.ExpandTableColumn(#"Merged Queries", "Makers", {"admin_city", "admin_department", "admin_displayname", "admin_country"},{"Makers.admin_city", "Makers.admin_department", "Makers.admin_displayname", "Makers.admin_country"}),
    #"Inserted Merged Column" = Table.AddColumn(#"Expanded Makers", "City, Country", each Text.Combine({[Makers.admin_country], ", ", [Makers.admin_city]}), type text)
in
    #"Inserted Merged Column";

shared byod_connectionreference = let
    Source = PowerBI.Dataflows(null),
       #"workspace" = Source{[workspaceId=#"Power BI Workspace ID"]}[Data],
    #"dataflow" = #"workspace"{[dataflowId=#"Power BI Dataflow ID"]}[Data],
    connectionreference1 = #"dataflow"{[entity="App Connections"]}[Data],
    #"Merged Queries" = Table.NestedJoin(connectionreference1, {"connectorSharedName"}, Connector, {"admin_name"}, "Connector", JoinKind.LeftOuter),
    #"Expanded Connector" = Table.ExpandTableColumn(#"Merged Queries", "Connector", {"admin_customconnectorhost", "admin_customconnectorhostishttp", "admin_connectordisplayname", "admin_publisher", "admin_tier"}, {"Connector.admin_customconnectorhost", "Connector.admin_customconnectorhostishttp", "Connector.admin_connectordisplayname", "Connector.admin_publisher", "Connector.admin_tier"}),
    #"Replaced Value" = Table.ReplaceValue(#"Expanded Connector",null,"Custom",Replacer.ReplaceValue,{"Connector.admin_tier"})
in
    #"Replaced Value";

shared byod_environments = let
    Source = PowerBI.Dataflows(null),
       #"workspace" = Source{[workspaceId=#"Power BI Workspace ID"]}[Data],
    #"dataflow" = #"workspace"{[dataflowId=#"Power BI Dataflow ID"]}[Data],
    environments1 = #"dataflow"{[entity="Environments"]}[Data],
    #"Removed Duplicates" = Table.Distinct(environments1, {"environmentId"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates", {"createdPrincipalId"}, Makers, {"admin_makerid"}, "Makers", JoinKind.LeftOuter),
    #"Expanded Makers" = Table.ExpandTableColumn(#"Merged Queries", "Makers", {"admin_city", "admin_department", "admin_displayname"}, {"Makers.admin_city", "Makers.admin_department", "Makers.admin_displayname"}),
    #"Replaced Value" = Table.ReplaceValue(#"Expanded Makers",null,"SYSTEM",Replacer.ReplaceValue,{"Makers.admin_displayname"}),
    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"createdPrincipalId", "createdBy"}, {"createdTime", "createdOn"}})
in
    #"Renamed Columns";

shared byod_usage = let
    Source = PowerBI.Dataflows(null),
       #"workspace" = Source{[workspaceId=#"Power BI Workspace ID"]}[Data],
    #"dataflow" = #"workspace"{[dataflowId=#"Power BI Dataflow ID"]}[Data],
    usage1 = #"dataflow"{[entity="AppsUsage"]}[Data],
    #"Sorted Rows" = Table.Sort(usage1,{{"appLaunchTime", Order.Descending}})
in
    #"Sorted Rows";

shared byod_flowconnectionreference = let
    Source = PowerBI.Dataflows(null),
       #"workspace" = Source{[workspaceId=#"Power BI Workspace ID"]}[Data],
    #"dataflow" = #"workspace"{[dataflowId=#"Power BI Dataflow ID"]}[Data],
    flowconnectionreference1 = #"dataflow"{[entity="Flow Connections"]}[Data],
    #"Lowercased Text" = Table.TransformColumns(flowconnectionreference1,{{"connectorName", Text.Lower, type text}}),
    #"Merged Queries" = Table.NestedJoin(#"Lowercased Text", {"connectorSharedName"}, Connector, {"admin_name"}, "Connector", JoinKind.LeftOuter),
    #"Expanded Connector" = Table.ExpandTableColumn(#"Merged Queries", "Connector", {"admin_customconnectorhost", "admin_customconnectorhostishttp", "admin_connectordisplayname", "admin_publisher", "admin_tier"}, {"Connector.admin_customconnectorhost", "Connector.admin_customconnectorhostishttp", "Connector.admin_connectordisplayname", "Connector.admin_publisher", "Connector.admin_tier"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded Connector",{"connectionReferenceId", "connectorName", "tenantId"})
in
    #"Removed Columns";

shared byod_flows = let
    Source = PowerBI.Dataflows(null),
       #"workspace" = Source{[workspaceId=#"Power BI Workspace ID"]}[Data],
    #"dataflow" = #"workspace"{[dataflowId=#"Power BI Dataflow ID"]}[Data],
    Flows1 = #"dataflow"{[entity="Flows"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(Flows1,{{"createdOn", type datetime}}),  
    #"Invoked Custom Function" = Table.AddColumn(#"Changed Type", "admin_nonprodflowcheck", each NonProdNameCheck([name])),
    #"Added Custom" = Table.AddColumn(#"Invoked Custom Function", "admin_notmodifiedsincecreated", each if [lastModifiedOn] = null 
or 
Duration.TotalMinutes([lastModifiedOn]-[createdOn])<2 
then 1 
else 0),
    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"lifecycleState", "State"}, {"name", "Display Name"}}),
    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns", {"flowId"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates", {"createdBy"}, Makers, {"admin_makerid"}, "Makers", JoinKind.LeftOuter),
    #"Expanded Makers" = Table.ExpandTableColumn(#"Merged Queries", "Makers", {"admin_city", "admin_department", "admin_displayname", "admin_country"}, {"Makers.admin_city", "Makers.admin_department", "Makers.admin_displayname", "Makes.admin_country"}),
    #"Inserted Merged Column" = Table.AddColumn(#"Expanded Makers", "City, Country", each Text.Combine({[Makes.admin_country], ", ", [Makers.admin_city]}), type text)
in
    #"Inserted Merged Column";

shared byod_flowusage = let
    Source = PowerBI.Dataflows(null),
      #"workspace" = Source{[workspaceId=#"Power BI Workspace ID"]}[Data],
    #"dataflow" = #"workspace"{[dataflowId=#"Power BI Dataflow ID"]}[Data],
    flowusage1 = #"dataflow"{[entity="FlowUsage"]}[Data]
in
    flowusage1;

[ Description = "You can get the Workspace ID by navigating to the Workspace and from the URL copying the GUID after /groups/" ]
shared #"Power BI Workspace ID" = "dcaca303-800c-4e43-b008-86149942178f" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true];

[ Description = "You can get the Dataflow ID by selecting a dataflow and from the URL copying the GUID after /dataflows/" ]
shared #"Power BI Dataflow ID" = "2ffac01e-7638-47a6-be4a-1e456f7cc430" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true];

shared #"Business Process Flows" = let
    Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_businessprocessflowses = entities{[EntitySetName="admin_businessprocessflowses"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_businessprocessflowses,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber", "admin_recordguidasstring"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"admin_businessprocessflowowner"}, Makers, {"admin_makerid"}, "Makers", JoinKind.LeftOuter),
    #"Expanded Makers" = Table.ExpandTableColumn(#"Merged Queries", "Makers", {"admin_city", "admin_department", "admin_displayname"}, {"Makers.admin_city", "Makers.admin_department", "Makers.admin_displayname"}),
    #"Replaced Value" = Table.ReplaceValue(#"Expanded Makers",null,"Unknown",Replacer.ReplaceValue,{"Makers.admin_displayname"})
in
    #"Replaced Value";

shared Solutions = let
    Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_solutions = entities{[EntitySetName="admin_solutions"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_solutions,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber", "admin_recordguidasstring"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"admin_solutioncreator"}, Makers, {"admin_makerid"}, "Makers", JoinKind.LeftOuter),
    #"Expanded Makers" = Table.ExpandTableColumn(#"Merged Queries", "Makers", {"admin_city", "admin_department", "admin_displayname"}, {"Makers.admin_city", "Makers.admin_department", "Makers.admin_displayname"}),
    #"Replaced Value" = Table.ReplaceValue(#"Expanded Makers",null,"Unknown",Replacer.ReplaceValue,{"Makers.admin_displayname"})
in
    #"Replaced Value";

shared Soltion_Apps = let
    Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_ppsolution_apps_tableset = entities{[EntitySetName="admin_ppsolution_apps_tableset"]}[Data]
in
    admin_ppsolution_apps_tableset;

shared Soltion_BPFs = let
    Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_ppsolution_bpf_tableset = entities{[EntitySetName="admin_ppsolution_bpf_tableset"]}[Data]
in
    admin_ppsolution_bpf_tableset;

shared Soltion_Flows = let
    Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_ppsolution_flow_tableset = entities{[EntitySetName="admin_ppsolution_flow_tableset"]}[Data]
in
    admin_ppsolution_flow_tableset;

shared Makers = let
Source = Cds.Entities(#"CoE Starter Kit Environment", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_makers = entities{[EntitySetName="admin_makers"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(admin_makers,{"createdby", "createdon", "createdonbehalfby", "importsequencenumber", "modifiedby", "modifiedon", "modifiedonbehalfby", "overriddencreatedon", "ownerid", "owningbusinessunit", "owningteam", "owninguser", "statecode", "statecode_display", "statuscode", "statuscode_display", "timezoneruleversionnumber", "utcconversiontimezonecode", "versionnumber"})
in
   #"Removed Columns";

**Comment by Jenefer-Monroe** [comment]
Sorry thats a lot of text. Can you help me understand a little more succinctly what error you are seeing ?

**Comment by jayakumarkgds** [comment]
Summary this may be issue with Huge data in AzureDL which is causing delay in Sync as the sync to powerbi template you have provided as part of the solution is not getting finished even after 24 hrs of sync.

Some time we get WebView can't be loaded.So we are unable to publish the BYODL dashboard.

**Comment by Jenefer-Monroe** [comment]
Sorry I meant the summary of this comment
![image](https://user-images.githubusercontent.com/89584709/235181424-ea7bb670-5558-4013-9f4b-8d28db728a3a.png)

**Comment by Jenefer-Monroe** [comment]
This is what you should see while waiting for the data from the data flows to come in
![image](https://user-images.githubusercontent.com/89584709/235450501-08a20c31-957d-4bce-9229-d968d6d6badc.png)

At this state they are loading
![image](https://user-images.githubusercontent.com/89584709/235450570-4f73f75b-8b1f-4c98-ad8b-18c09cadca18.png)

If you get stuck at this stage then I'm afraid you've hit some product issue with PBI and delay. You'll need to contact product support for that.

**Comment by jayakumarkgds** [comment]
HI Team,
Am getting all of those above and concern is not even finishing the sync job after 48hrs of continuous run. Query is how to minimize the data for first sync? So that i can publish the dashboard and later sync it online.
Its not an issue of powerBI app ,because of huge data it is not getting completed

**Comment by jayakumarkgds** [comment]
![image](https://user-images.githubusercontent.com/87489417/237004994-80e60ac7-ae25-4e63-b5f1-cdd712c136e8.png)

**Comment by jayakumarkgds** [comment]
Somehow i managed to sync the BYODL dashboard But now refresh is failing with below error.

![image](https://github.com/microsoft/coe-starter-kit/assets/87489417/b314eb12-b81c-4e57-8a2d-9c4924b4127d)

![image](https://github.com/microsoft/coe-starter-kit/assets/87489417/6af8bbf6-ff0a-49c5-9d1e-ac6ecc8a0105)

**Comment by manuelap-msft** [comment]
Hello,

I think we need to figure out what table is causing the load issue before we can suggest anything further.

Can you cancel the initial load, and then select Transform Data > Transform Data from the ribbon

![Image](https://github.com/microsoft/coe-starter-kit/assets/55705669/bc198263-a5ac-4b1b-aafc-60219ad8e215)

Then select each table and select Refresh > Refresh All

![Image](https://github.com/microsoft/coe-starter-kit/assets/55705669/2c4c8ee4-42e9-4502-ab40-78fdd29d7209)


Check if any of the tables are causing a load issue?

**Comment by jayakumarkgds** [comment]
I have done some work around to fix this. Below video helped me to limit the data refresh.  

https://www.youtube.com/watch?v=_zYvybVMk7k

**Comment by Jenefer-Monroe** [comment]
Thank you so much for sharing the link to what helped you. This makes our community so much better when you can help others. Appreciate it!

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this out then, please let us know if you have other questions.
