### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 Error vApril2023

### ISSUE THREAD

**Issue by KanwarSingh** [microsoft/coe-starter-kit#5403]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Installed COE april 2023 release to new environment, I noticed in the "CoE Admin Command Center app" that the flow Admin | Sync Template v3 is erroring out. 

Error is on the step "Store enviornments in the COE CDS entity" >> GET has PCF enabled value > YES > Get Organisation.

Error Details : Action 'Get_organization' failed
![FlowError](https://user-images.githubusercontent.com/26156698/235398978-b7fdca95-d5f7-4662-a8f1-78527c3dd47e.jpg)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.41

### What app or flow are you having the issue with?

Admin | Sync Template v3 

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

In the COE solution > Cloud Flows > Admin | Sync Template v3

### Anything else?

Nothing

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. We have this one local fixed for May by this issue: https://github.com/microsoft/coe-starter-kit/issues/5197

If this is blocking you, you an delete this part of the flow, and then remove the unmanaged layer that is created when you install the May release
![image](https://user-images.githubusercontent.com/89584709/231277266-625d3955-c5b2-42e7-83f5-b5cd62d6367a.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by KanwarSingh** [comment]
Thanks @Jenefer-Monroe

**Comment by Jenefer-Monroe** [comment]
you bet! :)
