### ISSUE TITLE
[ALM Accelerator - QUESTION] Power App Links Environment Variable Configuration on Destination Environment

### ISSUE THREAD

**Issue by jfung85** [microsoft/coe-starter-kit#5404]
### What is your question?

What is the expected deployment steps for a new solution to a new environment when there are environment variables in the solution that reference the Power Apps within the solution since those Power App links will be generated as unique in the destination environment.

In this case, is it always expected to deploy the solution twice? Once to deploy with something like "TBD" in the App Link environment variable configuration and then a second time with the App Link after it has been generated in the destination environment?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Accelerator Version: 1.0.20230405.2(Managed)

**Comment by mikefactorial** [comment]
@jfung85 there should be no reason to deploy the solution more than once. You can configure the environment variables for the downstream environment in the deployment settings and it will wire them up during the deployment. Not sure if I'm missing anything here.

**Comment by jfung85** [comment]
Hi @mikefactorial, this would be a specific scenario where a Power App link is referenced elsewhere in the solution. A couple of examples of this would be sending an email from a workflow with a link back to a Power App or a Power App that is a launchpad to other Power Apps. In these cases, we created text environment variables to hold the Power App links for reference. When first deploying to a new environment, the Power Apps don't exist yet, so we don't have the link values to configure for the environment variable. Also, when the Power App is first created, the link that is created is different between environments for the same Power App. For these scenarios, it seems that the only way to get it configured properly would be to deploy once with a temporary value and so that the Power Apps could be created with their links. Then update the environment variables with the links from the destination environment and then deploy again. I think the key points are that (1) the Power App links for the same Power App are different between environments and (2) the Power Apps have not been created yet before the first deployment so the environment variables cannot be set with the actual value at that time. Let me know if any of these points are not accurate.

**Comment by jfung85** [comment]
Thanks for the reference @mikefactorial . I'll take a look at the hook extensions to see if that will help. But overall this answered my question and we can close this thread.
