### ISSUE TITLE
[ALM Accelerator - BUG]: CustomConnector throws error 500 when trying to access Organization

### ISSUE THREAD

**Issue by Awnhumbla** [microsoft/coe-starter-kit#5406]
### Describe the issue

We have been running the ALM accelerator since the last year without this issue. 

Now we cannot get the customconnector to fetch the correct organization name. When testing the GetOrganizations call it throws this in Headers: 
{
  "content-length": "265",
  "content-type": "application/json"
}

and this in Body:
{
  "error": {
    "code": 500,
    "message": "Variable organization has no value.",
    "source": "unitedstates-002.azure-apim.net",
    "path": "choose[3]\\when[1]",
    "policyId": "",
    "clientRequestId": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"
  }
}

### Expected Behavior

status should be 200

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20221101.1

### Steps To Reproduce

1. Open the CustomConnector 
2. Check the credentials are correct in the Security tab
3. Update connector
4. Test the getOrganization

**Comment by mikefactorial** [comment]
@Awnhumbla there have been some recent changes to the Custom Connector Security screen make sure you are choosing the correct Auth Type and Identity provider per https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#configure-the-devops-custom-connector

**Comment by Awnhumbla** [comment]
Thanks, Mike. We solved the issue by upgrading to the newest ALM Accelerator release.

**Comment by mikefactorial** [comment]
Good to hear! Thanks for reporting back @Awnhumbla.

**Comment by Masciuniria** [comment]
Still got same error with last ALM Accelerator version 1.0.20231012.1

**Comment by Masciuniria** [comment]
> @Awnhumbla there have been some recent changes to the Custom Connector Security screen make sure you are choosing the correct Auth Type and Identity provider per https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#configure-the-devops-custom-connector
