### ISSUE TITLE
[CoE Starter Kit - QUESTION] Microsoft Teams Business Justification

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5407]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

HI,

Who will receive the business justification email for Teams? Is Teams Channel creator or Channel member?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 19th 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The environment maker. Meaning the person that created the Dataverse for Teams instance.

**Comment by Jenefer-Monroe** [comment]
Have you done the setup work for the solution area? [Set up Dataverse for Teams environment management](https://learn.microsoft.com/power-platform/guidance/coe/setup-teams-components)

If so, please go look at this flow: Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created

Did it run or is it running? If so, please open the run and see who is listed for SendTo
![image](https://user-images.githubusercontent.com/89584709/235508165-c872b1bf-e505-41d3-982b-b71650436b31.png)
![image](https://user-images.githubusercontent.com/89584709/235508308-dde0443f-604a-414a-bbb2-394769e06881.png)

**Comment by lingutla123** [comment]
In the flow  teams channel member email is showing. The Teams Channel maker added the members as owners to the teams channel.

![image](https://user-images.githubusercontent.com/126264610/235682209-d1ae4efe-a7fe-4b20-9762-7a273c4bbd35.png)

**Comment by Jenefer-Monroe** [comment]
Hello. We do use any of that information, we just use the maker concept from the D4T. 

Please validate, 

1. Have you done the setup work for the solution area? [Set up Dataverse for Teams environment management](https://learn.microsoft.com/power-platform/guidance/coe/setup-teams-components)

2. If so, please go look at this flow: **_Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created_**.  Did it run or is it running? If so, please open the run and see who is listed for SendTo
![image](https://user-images.githubusercontent.com/89584709/235508165-c872b1bf-e505-41d3-982b-b71650436b31.png)
![image](https://user-images.githubusercontent.com/89584709/235508308-dde0443f-604a-414a-bbb2-394769e06881.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
