### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - Audit Log - App Sessions

### ISSUE THREAD

**Issue by mar05lun** [microsoft/coe-starter-kit#5408]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi! In the Apps report in Power BI there is a column that shows sessions for an app. 
<img width="157" alt="appsessions" src="https://user-images.githubusercontent.com/132279063/235471757-93e8a06c-c8e0-4599-885a-f94e4f9ba06a.png">

If a user launches the app and encounters a fix connection pop up and then exits without fixing the connection, will this still count as a session in the report? and will they show up as a unique user as well?
<img width="293" alt="appfixconnection" src="https://user-images.githubusercontent.com/132279063/235472255-9b0b3757-0381-4544-9144-3db17d1cf30a.png">

### What solution are you experiencing the issue with?

Audit Log

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid I dont know the answer to this question. We just consume the office audit logs we do not produce them, the product does that directly. My assumption is that it would count as a launch, as its not related to connections (which is where you stop in your example) but to the launch itself. 
I will leave open in case others in the community might know for sure.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by S0URCEC0D3** [comment]
Thank you, Jenefer! Very helpful as always
