### ISSUE TITLE
[CoE Starter Kit - QUESTION] Administration Planning Component - Sample admin task data

### ISSUE THREAD

**Issue by The-Don1** [microsoft/coe-starter-kit#5409]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Setting up the CoE for the first time recently, we're using the March 2023 version.
Have installed the Administration Planning component (admintaskanalysis_core_1_2_managed) and now trying to install the sample admin tasks xlsx file. Power Platform only gives the option to Import CSV or XML from the Admin Tasks app. We tried importing using CSV but this imported a large number of blank tasks, only 51 were successful.
Downloaded the April set of files but this has no sample data - Is it missing or is there a new approach in the April package?  

### What solution are you experiencing the issue with?

Admin Task Planner

### What solution version are you using?

Feb 2023

### What app or flow are you having the issue with?

Admin ta

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I dont repro this. I've taken some screenshots of me importing the sample data, hopefully it helps you. Please do let me know.

### Here is the sample data file in the download
![image](https://user-images.githubusercontent.com/89584709/235507491-4edc302f-6d08-4b3f-afe8-fd2b4b8ea042.png)

### Here is how you get to the import ux
![image](https://user-images.githubusercontent.com/89584709/235506557-52c9a839-a508-491a-a0ff-ef8ad8835a2f.png)
![image](https://user-images.githubusercontent.com/89584709/235506731-c4f2f271-f68d-4409-a7c2-e8831d1f97c1.png)

### You can select an xlsx file, not sure why the message doesnt say thats ok
![image](https://user-images.githubusercontent.com/89584709/235506785-a9763615-9007-4656-a91c-5cd3fbd922f4.png)
![image](https://user-images.githubusercontent.com/89584709/235506943-ca702e4d-4e04-49ea-9320-a7f40542ca9b.png)
![image](https://user-images.githubusercontent.com/89584709/235507058-ceeabba9-3186-4109-9a3d-fd42ea14fa29.png)
![image](https://user-images.githubusercontent.com/89584709/235507164-03654256-7861-45fe-bee0-adda04e5f9f3.png)

### Afterwards I see all records were imported, and I can see them if I hit refresh in the app
![image](https://user-images.githubusercontent.com/89584709/235507228-1aa9acf2-94b3-4eae-81d3-657afaecfc8a.png)
![image](https://user-images.githubusercontent.com/89584709/235507278-39d6ee20-c0a9-40b0-9107-0a272d05f08e.png)
![image](https://user-images.githubusercontent.com/89584709/235507325-d1ab2fc1-18d3-4816-b6e7-b69f646174f2.png)

**Comment by The-Don1** [comment]
Hi Jenefer, thanks for the quick response.
1. I'm now able to Import the admin tasks, I had to convert the XLS format to CSV and then map the fields as per your screenshot above.
2. There were ~150 tasks imported, 72 were successful and 5 failed but I created those manually. There were about 80 blank tasks created by the import process. I ran the Admin Task Power app in Edit mode to delete the blanks.
3. Pretty sure that I'm pulling down the wrong package for April as my extract is missing the Power BI templates as well......Yes, I was pulling from the main page, instead of from Releases. Sorry about that, I'm a Github newbie!

**Comment by The-Don1** [comment]
As things stand in our particular environment, we have everything up and running so no further action required. Thanks again for your assistance!

**Comment by The-Don1** [comment]
As things stand in our particular environment, we have everything up and running so no further action required. Thanks again for your assistance

**Comment by The-Don1** [comment]
As things stand in our particular environment, we have everything up and running so no further action required. Thanks again for your assistance

**Comment by Jenefer-Monroe** [comment]
Thanks for letting me know!
