### ISSUE TITLE
[ALM Accelerator - QUESTION] Deployment Settings

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/coe-starter-kit#5413]
### What is your question?

Hi @mikefactorial - Could you please let me know where the deployment settings are saved. I was trying to delete existing settings configured for a solution, and for this I have deleted the deployment pipelines and the repository as well. Still the old deployment settings are coming up. What would be the procedure to start everything fresh for a solution.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 2023 Hotfix

**Comment by mikefactorial** [comment]
@tomjosbin thanks for the question you can find the deployment settings in the ALM Accelerator Admin app if you select Settings from the left Nav and then User Settings.
![image](https://user-images.githubusercontent.com/42348035/235707349-d0705464-b4f4-4b49-9697-5f0dc6a2d546.png)

**Comment by tomjosbin** [comment]
Thanks Mike, appreciate your quick response :)

**Comment by mikefactorial** [comment]
No problem @tomjosbin :) BTW. You should be able to delete those records to reset things and they will be recreated the next time you save the deployment settings. Closing this out for now.
