### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 fails to get organizations

### ISSUE THREAD

**Issue by PaulSchaefer01** [microsoft/coe-starter-kit#5414]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
the flow "Admin | Sync Template v3" runs into an error when trying to get organizations. This error occurs only in 3 environments.
The error message I get is the following: _No Organization is matching the given dataset_
The flow is executed with an account that has the Power Platform Administrator role, so it should have access to the environments.

![image](https://user-images.githubusercontent.com/132338999/235616105-eff31f8d-9c72-4bd8-9547-c5a33482295b.png)
![image](https://user-images.githubusercontent.com/132338999/235616798-2a9a0e4d-9306-4940-8f06-3e9cc6250758.png)

Thanks in advance

### Expected Behavior

Flow runs successfully 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Start the "Admin | Sync Template v3" Flow

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. We have this one local fixed for May by this issue: https://github.com/microsoft/coe-starter-kit/issues/5197

If this is blocking you, you an delete this part of the flow, and then remove the unmanaged layer that is created when you install the May release
![image](https://user-images.githubusercontent.com/89584709/231277266-625d3955-c5b2-42e7-83f5-b5cd62d6367a.png)

**Comment by PaulSchaefer01** [comment]
Thanks for your help. The flow went through successfully.
I assume that the flow _"SYNC HELPER - Get Security Role Users"_ has a similar cause of error that will be fixed in the may update?
Here I also get the error message that the group ID is not found for 3 environments.

**Comment by Jenefer-Monroe** [comment]
Yes that flow is also local fixed for May. Thank you!

**Comment by PaulSchaefer01** [comment]
Thank you very much for your help!

**Comment by joebeyer75** [comment]
Was this actually fixed in the May release? We are using the May release in our Prod and Dev Environments and we're still having this issue. The Admin | Sync Template v3 is failing "Get has PCF Enabled value" action. I have removed it to try again but need to understand why this keeps happening.
