### ISSUE TITLE
[CoE Starter Kit - GCCH] Can you assist me with updating CoE 4.2 to 4.4.2 in GCCH?

### ISSUE THREAD

**Issue by yearwoodm15** [microsoft/coe-starter-kit#5417]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I was searching through the repository, but was unable to find an answer to what is occurring. I was able to successfully update my Commercial tenant w/ 4.4.2 - but am having issues with GCCH. They both were previously 4.2 successfully implemented. Can you please assist in what may be the case here? I have attached logs and screen shots.

Note: I was able to get the Creator Kit updated in GCCH, but Core Components and Nurture are not updating. 
[nurture_log.txt](https://github.com/microsoft/coe-starter-kit/files/11373913/nurture_log.txt)
<img width="752" alt="CoE Dependency_Core" src="https://user-images.githubusercontent.com/83036044/235688129-26596b79-2249-4844-a7db-320adb184c64.PNG">
<img width="675" alt="CoE Dependency_Nurture" src="https://user-images.githubusercontent.com/83036044/235688132-499c744a-9708-439c-9c94-91d0cb02fa37.PNG">
[Core_log.txt](https://github.com/microsoft/coe-starter-kit/files/11373914/Core_log.txt)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April2023

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
From the error message it looks like you have another custom solution called DataflowSolution which is causing the error. Can you please take a look? 
![image](https://user-images.githubusercontent.com/89584709/235728698-f8b13e75-766c-4b3d-b5e7-f9baf06ce907.png)

**Comment by yearwoodm15** [comment]
Hi Jenefer! Hope all is well. I do not see that solution in the parent:

![image](https://user-images.githubusercontent.com/83036044/235749359-1a74e15c-f2a5-4393-a3dd-c0377f9487a5.png)

**Comment by Jenefer-Monroe** [comment]
Can you see if you have this table? 

CoE Environment > Tables > All > Search for Dataflow > **_DataflowRefreshHistory_**
![image](https://user-images.githubusercontent.com/89584709/235790976-fafa66cd-f0cd-447f-88f1-ed1499b3ba33.png)

**Comment by yearwoodm15** [comment]
I only have Dataflow, no DataflowRefreshHistory'
![image](https://user-images.githubusercontent.com/83036044/235930913-61186c4f-29a8-47c5-944e-eb9e402b7597.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by yearwoodm15** [comment]
Hi Jenefer,

I was able to confirm the DataflowRefreshHistory shows up in the environment I tested out. I would like to keep the older environment, if possible. What would be the recommended solution if I wanted to keep my other environment since I have other users on it as well?

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont know. Thats a product table thats missing, not one of ours. Product support may be able to assist if you just tell them that you are missing that product table.

**Comment by ballard297** [comment]
Hey @yearwoodm15 - I was able to get past this issue by going to the admin center and following this path: Environments -> select target env -> Resources (button found in upper action bar) -> Dynamics 365 Apps.

Going here will greet you with a list of solutions that I believe Microsoft installs in all environments. You should see one named "Power Platform Dataflows", which I am betting will have an "Update Available" indicator. I faced the same error as you, but then was able to get past it once the I installed the update from the admin center. 

Not sure why Microsoft doesn't install these updates automatically, maybe its a GCCH thing. My envs have quite a few updates available, but I only install them as needed since its too much to keep up with.
