### ISSUE TITLE
[CoE Starter Kit - BUG] Inventory Data Not Updating Correctly After April 2023 Upgrade

### ISSUE THREAD

**Issue by joebeyer75** [microsoft/coe-starter-kit#5419]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After we upgraded to the April 2023 CoE Starter Kit, our inventory numbers are very low (much lower than they should be and were before). After checking some of the flows, we noticed a lot of them were terminating on step 2. For example, the below three flows are showing terminated on the second step. Step 1: When a record is created or updated. Step 2: Check if Environment Deleted, terminate if true"

1. Admin | Sync Template v3 (Apps)
2. Admin | Sync Template v3 (Flows)
3. Admin | Sync Template v3 (Environment Properties)

We also noticed that the Admin | Sync Template v3 hasn't succeeded since 4/5/23, which was the day we installed the update. It has failed every attempt since even after running for over 14 hours. It shows as "canceled" on 4/26 and the flow was turned off. I have turned that back on today and it has been running for just about 30 minutes, and still going. 

### Expected Behavior

Inventory numbers after upgrade are significantly lower than before upgrade. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by joebeyer75** [comment]
The Admin | Sync Template v3 flow failed after 2 hours with error "Action 'Get_organization' failed". 

It failed on the action "Store environments in the CoE CDS Entity" and then the "Apply to each Environment" within that action. Under that section, it failed on the "Get has PCF enabled value" on the If yes - Get Organization" action. It failed on 1 of the 40 total actions. 

"ActionFailed. An action failed. No dependent actions succeeded".

**Comment by manuelap-msft** [comment]
This is a known issue that will be fixed with the May release, see https://github.com/microsoft/coe-starter-kit/issues/5414 for details on how to fix this yourself in the meantime.
