### ISSUE TITLE
Admin | Sync Template v3 (Model Driven Apps) : Doesn't update the Model drive app into POWER APPS Dataverse table 

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/coe-starter-kit#542]
The Admin | Sync Template v3 (Model Driven Apps)  runs successful. But the data is not getting update in POWER APPS table
**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution :: Core
 - Version :: 1.98
 - App :: Admin | Sync Template v3 (Model Driven Apps)

**Expected behavior**
All the model apps created in environment should be available in POWER APPS Table

**Comment by manuelap-msft** [comment]
Hello,

Can you confirm the missing model driven apps are all published? Due to product limitations this sync flow only can pick up published apps.

Thank you
Manuela

**Comment by ApoorvaKantale** [comment]
Yes the apps are published

**Comment by JeneferM-MSFT** [comment]
Can you please upgrade to the latest version of Core? You seem to be on an old version and some old versions use a deprecated connector.

**Comment by ApoorvaKantale** [comment]
okay, Thank you
