### ISSUE TITLE
[CoE Starter Kit - BUG] Manual setup of BYODL integration

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#5421]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are setting up CoE with BYODL. 

However - 

1) Setup wizard app does not load. We have made sure DLP does have the connectors in Business bucket as mentioned in the documents.

![image](https://user-images.githubusercontent.com/106515181/235889230-b32bb32e-c523-47fe-a1e2-3334cf73e17d.png)

2) So we went ahead and started setting up manually. For setting up the data flow we got success for Makers but while setting up the dataflow for Environments we are getting below error - 

<img width="696" alt="MicrosoftTeams-image (10)" src="https://user-images.githubusercontent.com/106515181/235889776-94bcf308-9bd8-4d1c-bfcd-9c6e131b6f4c.png">

### Expected Behavior

The setup wizard should load and dataflow should run successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

COE BYODL Environments

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
Setting up the Data Export integration with the CoE Kit is currently only supported through the setup wizard, see [our documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
![image](https://user-images.githubusercontent.com/55705669/235891870-49fa0732-f983-4457-8c26-16aa60ab4489.png)

The wizard performs some tasks, such as running flows and setting environment variables in the background that we haven't documented yet for manual setup yet and thus manual setup doesn't quite work. 

Here's three tips for how to resolve the DLP issue:
- https://github.com/microsoft/coe-starter-kit/issues/5255#issuecomment-1505209659
- https://github.com/microsoft/coe-starter-kit/issues/5255#issuecomment-1516551652
- https://github.com/microsoft/coe-starter-kit/issues/5347#issuecomment-1520494654

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
