### ISSUE TITLE
[CoE Starter Kit - Feature]: App Complexity for reporting

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5423]
### Is your feature request related to a problem? Please describe.

Looks like the Get Apps as Admin response now includes a Complexity score across different metrics (data sources, components on screen etc)
![image](https://user-images.githubusercontent.com/55705669/235909427-c6571a9e-c200-441a-8fce-bc2276fdd2b0.png)

### Describe the solution you'd like

We currently have a complexity score for flows, and should evaluate if we can use these new fields for an app complexity score. This is a frequent ask for compliance considerations.

**Comment by Jenefer-Monroe** [comment]
Dupe to https://github.com/microsoft/coe-starter-kit/issues/6014
