### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by DreyesGCPUD** [microsoft/coe-starter-kit#5424]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am unable to locate the 4.3 version of the starter kit that is referenced in a bug issues I encountered with the 4.2 version.

I have removed the 4.2 and need to install the latest but the website is still downloading the 4.2 

Please tell me where I can find the zip download?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. You can get the latest version of the kit by browsing to : https://github.com/microsoft/coe-starter-kit/releases/latest

And you can browse previous releases here: https://github.com/microsoft/coe-starter-kit/releases

I'm not sure if perhaps you mean v 4.4.2. That is the latest Core and you can find it here. 
[CenterofExcellenceCoreComponents_4_4_2_managed.zip](https://github.com/microsoft/coe-starter-kit/files/11401018/CenterofExcellenceCoreComponents_4_4_2_managed.zip)

**Comment by Jenefer-Monroe** [comment]
aww I see. Likely just a typo by one of us then. Glad you are unblocked Will go ahead and close but please reach out if you need more assistance.
