### ISSUE TITLE
[CoE Starter Kit - QUESTION] Manager Taking Ownership of Orphaned Resource

### ISSUE THREAD

**Issue by krhoadesnh** [microsoft/coe-starter-kit#5425]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am trying to understand when a manager would or would not be able to successfully click on "_Take Ownership_" for an abandoned flow.  

- Would the manager need to already have the flow shared with them as an owner?  
- What happens if it is unsuccessful, do they receive an error?  
- If the flow is in a solution is there any different behavior? 

Because we do not have a test environment for the CoE I unfortunately can't test & I can't find info in documentation anywhere.  As always, I truly appreciate the work your team puts into supporting this product.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.8.1

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Do you mean in the context of the orphaned objects solution that sends out teams chats? 
If so, then they do not need to have ownership prior, they will be assigned permissions to the flow. If a flow fails to be assigned to them they will be told this in the chat bot, that the assignment failed. No difference for solution aware flows here. Although we do not (yet) make it clear that the object is in a solution (meaning that they would also want to take ownership of this app etc)

Hope that helps!

**Comment by manuelap-msft** [comment]
No further action required. Thank you for using the CoE kit!
