### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to get the CoE Database size down?

### ISSUE THREAD

**Issue by JayCecchine** [microsoft/coe-starter-kit#5426]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Our COE kit is taking up a substantial amount of space, ~4.5 GB.  We're nearing the cap of our database size limit for power platform. 

Is there anything I can do to slim down the size?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

can you 
1. Open https://aka.ms/ppac
2. Select Resources > Capacity
3. Select Dataverse
4. Select the Details icon next to your CoE environment
   ![image](https://user-images.githubusercontent.com/55705669/236155282-9ab7a1db-c50e-46d5-b0fb-2ee109c014ae.png)
5. Does it look like one of the CoE tables (admin_) is consuming a lot of database capacity?
6. If you have the Audit Log solution installed, Audit Log entries are collected in Dataverse over time so if you've set up this solution a while ago it could be that the table has grown significantly. If it has, I would evaluate how far back you need audit logs for reporting (e.g. 3 months, 6 months, 1 year?) and perform a bulk delete job to reduce the size of this table. Let me know if you need step by step instructions on where to find and how to use bulk delete
7. If it's not a database table but instead log tables that are taking up capacity, there's some tips in this article: https://learn.microsoft.com/en-us/power-platform/admin/free-storage-space 

Hope that helps, but please let us know if you have further questions here!
Manuela

**Comment by JayCecchine** [comment]
Hello,

It looks to be the database and file.  We don't have logging just yet enabled

![image](https://user-images.githubusercontent.com/24686498/236334931-659233f5-985f-4441-b184-ce302b0fe28e.png)

**Comment by JayCecchine** [comment]
Oh nevermind, I see now.  The audit log base is part of the db, and is taking a large margin of space ~2.5GB

**Comment by JayCecchine** [comment]
Could I get the steps to bulk delete the log data? It is causing issues in our environment, we're getting reports about laginess and other issues from users.

Thank you @manuelap-msft !

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are a very small team and so not staffed to assist with general product assistance. 
I do know that there are bulk edit operations in Dataverse. Here is a starter link for that I found https://learn.microsoft.com/power-apps/developer/data-platform/delete-data-bulk

Will also leave open in case others in the community have a more direct response.

**Comment by JayCecchine** [comment]
Hi Jenefer,

I just need the step by step instructions -

Manuela did mention step by step instructions to bulk delete, "

If you have the Audit Log solution installed, Audit Log entries are collected in Dataverse over time so if you've set up this solution a while ago it could be that the table has grown significantly. If it has, I would evaluate how far back you need audit logs for reporting (e.g. 3 months, 6 months, 1 year?) and perform a bulk delete job to reduce the size of this table. **Let me know if you need step by step instructions on where to find and how to use bulk delete**"

**Comment by Jenefer-Monroe** [comment]
Oh I didnt see that. Sorry! She'll be back from vacation tomorrow and so will hopefully be able to assist there.

**Comment by manuelap-msft** [comment]
Hello,

here you go:

1. Navigate to the Power Platform Admin Center > Environments
2. Select your **CoE Environment**
3. Select **Settings**
4. Select **Bulk deletion** under Data management
   ![image](https://user-images.githubusercontent.com/55705669/237045388-9bcdbe08-dfce-4303-bf2b-b8a301ab40de.png)
5. In the new window that opens up (Bulk deletion system jobs), select **New**
6. Select **Next**
7. Select **Audit Logs** in the "Look for" dropdown
8. Specify the criteria of which audit logs you want to delete - Creation Time is the field the CoE writes the data to (of when the app was launched), so you could base the criteria on that and select something like e.g. Creation Time is last year - you're quite flexible with the rules here and could also set it to "older than x years"
   ![image](https://user-images.githubusercontent.com/55705669/237046263-3e0c9831-bedc-4331-bef2-7100099b3c91.png)
   ![image](https://user-images.githubusercontent.com/55705669/237046470-11fb7654-3537-4f5e-999b-dc8d28935da4.png)
9. Select Next once you're happy with the criteria.
10. Select when to run this job (e.g. overnight is usually a good time and optionally choose to send an email to yourself if the job is finished. The default name of the job is Bulk Deletion timestamp - I'd also recommend renaming that to CoE audit log bulk deletion so you can easily find it.
   ![image](https://user-images.githubusercontent.com/55705669/237046825-3009c66e-b948-45f6-9eec-c0975644df87.png)
11. Select Next > Submit
12. You can then search for the job and check the status of how many records it deleted. 
   ![image](https://user-images.githubusercontent.com/55705669/237047277-f4a0a134-3daf-44db-8cf8-7fc09dc739a1.png)
13. Tune it from there - e.g. you could start with deleting everything from 2 years ago, if that doesn't free up enough capacity delete everything older than a year.
14. Remember to refresh the Power BI dashboard after you've deleted the records too. 

If you do want to keep the audit log information for reporting, and just free them up from Dataverse you'd have to evaluate other technologies - e.g. exporting it to Azure Synapse Link or another data warehouse and keep the data there and then wire up the Power BI dashboard to get data from a different source. 

Hope this helps
Manuela

**Comment by JayCecchine** [comment]
Perfect!  Thank you so much.

We can close this
