### ISSUE TITLE
[CoE Starter Kit - BUG] Model Driven App Sync Template Flow can not collect all MDAs existing in an Environment

### ISSUE THREAD

**Issue by pp-panda** [microsoft/coe-starter-kit#5427]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the Release CoE Core Components 3.56 is a MDA Sync Flow - **Admin | Sync Template v3 (Model Driven Apps)**
This Flow is working with the legacy Connector and for a few weeks, can no longer capture all MDAs. Since the legacy connector has been discontinued, you should now use http action wtih rest api call: 
api/data/v9.2/appmodules/Microsoft.Dynamics.CRM.RetrieveUnpublishedMultiple()?
When will it be implemented in the core components?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.56

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Model Driven Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
