### ISSUE TITLE
[CoE Starter Kit - Question] Get Admin App Role Assignment error

### ISSUE THREAD

**Issue by davidkellyirl** [microsoft/coe-starter-kit#5429]
I have installed the CoE core components and got my Power BI working - except for 1 piece of the puzzle, when i drill down on a specific app or flow and get brought to the advanced app insights embedded power app I get the following error message

please help

![image (1)](https://user-images.githubusercontent.com/57921138/236156740-2e5d99f5-04c8-4e14-987c-9b35e3410e09.png)
![image](https://user-images.githubusercontent.com/57921138/236156746-049c0e99-2a3e-4f99-9e3a-3c198c4c4e5a.png)
.

**Comment by Jenefer-Monroe** [comment]
What versions are you using? Meaning. The installed version of Core as well as the file name of the PBIT you used. 

And did you follow the setup instructions for the embedded apps? 
https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard

**Comment by davidkellyirl** [comment]
Hi Jenefer,

Core Component Version: 4.2
PBIT: PowerPlatformGovernance_CoEDashboard_DEcemeber2022

I followed both docs instructions and Manuela Pichler's PowerCAT YouTube Video

thanks

Dave

[cid:7758220c-86f5-4ef3-85c9-e3cdbc33d3d5]
David Kelly - UPCOMING LEAVE May 15th - 26th
Technical  Specialist
Dynamics 365 + Power Platform
***@***.******@***.***>

[cid:ac5c0636-1cd9-463e-96b3-f12e14479675]<https://www.youracclaim.com/badges/4344fde5-cbec-4f4d-80be-0cd1e806e295/public_url>[cid:8cb7a82e-5b33-42cb-ac24-6ec6878efb9a]<https://www.youracclaim.com/badges/cedb9746-1a98-41a0-b8ce-1be0196fcb6b/public_url>[cid:d6b2d0fe-5f45-4daf-815b-ae906990ec23]<https://www.youracclaim.com/badges/d3931af6-696d-4c10-9329-d4ab080431a5/public_url>[cid:15005079-174d-4996-8a51-dd0396711ca8]<https://www.youracclaim.com/badges/b81302dc-1bd7-44ae-b5dc-69f324276a72/public_url>

________________________________

**Comment by Jenefer-Monroe** [comment]
Got it, its best to keep the PBIT and Core versions matched. We changed the input parameters from PBI to PowerApps a few months ago, not sure exactly when. That is likely what is hitting you. 
Please use the Production_CoEDashboard_April2023

**Comment by manuelap-msft** [comment]
No further action required. Thank you for using the CoE kit!
