### ISSUE TITLE
Office 365 Management API Connector Issue - Environment property cannot be changed

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#543]
Hello Team,

I have successfully deployed/Activated latest version of CoE Starter Kit ( 2.1.6 ) except the Audit Log Components.

I have client App registered with required permissions to receive audit activities, however when I update the same detail in the custom connector, it throws following error:

**Steps:**

1. Specify all required details in the custom connector security definition.
2. Click "Update Connector"
3. Throws an error (Environment property cannot be changed.)  as follow:

![image](https://user-images.githubusercontent.com/13658386/120276739-18f1c680-c281-11eb-9015-cc6baea7f343.png)

I have then connected with MS Support who were unable to help and suggested to be addressed with Github.

Can you please help what could be the root cause for this issue?

Thanks and Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

unfortunately, as this error is coming from the Custom Connector interface and not the CoE Starter Kit itself we will be unable to help here as we are not product support. This error could be something to do with your permissions or the environment itself, but it would not be related to the custom connector we make available. You will have to get back in touch with MS Support who should help you here.

Thank you,
Manuela
