### ISSUE TITLE
[CoE Starter Kit - BUG] Unnecessary Unmanaged Layer creating in Copy of CoE Prod environment. 

### ISSUE THREAD

**Issue by Gokul-JB** [microsoft/coe-starter-kit#5431]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We generated a replica of the production CoE environment into the test environment since we wanted to upgrade the most recent CoE April release in my test environment.

I discovered that all flows had been stopped because the flow connector's connection had not yet been made in Test (Copy of Prod) environment, So I manually made the connection using my service account, however this resulted in the creation of an unmanaged layer. Please advise how to prevent unmanaged layer.

**Note**: We have created copy of Prod CoE environment using Service account and trying to turn on all flows using same service account

### Expected Behavior

Should not stop all my flows or create unmanaged layer while establishing connection.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Sep

### What app or flow are you having the issue with?

Admin | Add Maker to Group

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid this is feedback to the product team and not us. We do not create the layering. And your issue is not specific to our solution but any solution would face this. 
You can provide product feedback in the Power Users community: https://powerusers.microsoft.com/

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
