### ISSUE TITLE
[CoE Starter Kit - Feature]: Group components by SolutionID

### ISSUE THREAD

**Issue by BCBuizer** [microsoft/coe-starter-kit#5434]
### Is your feature request related to a problem? Please describe.

The issue is that I can't group components by their solution: The COE starter kit tables (in first instance 'PowerApps App' and 'Flow') do have a relation with the 'Power Platform Solution' table, but don't contain a column that gives the SolutionID. Because of this we can't automate certain governance processes that are applied either at component or solution level.

### Describe the solution you'd like

I would like to see a SolutionID column in the tables for all components that may be included in a solution so that can be used to group components by SolutionID.

### Describe alternatives you've considered

Currently the alternative is to add a custom column to the beforementioned tables and populate that manually.

**Comment by BCBuizer** [comment]
Hi,

In our process we want to make sure developers have made certain development considerations. Currently this process is triggered by the creation of a new item in, for instance, the 'PowerApps App' or 'Flow' tables. Since we don't want to run the same process in parallel for multiple apps/flows within the same solution, there is a need for grouping in a similar fashion as in the above.

We'll have a look into how we can use the above to check if, for instance, a newly created flow is part of a solution for which a process has already been started/completed.

**Comment by odindeltoro** [comment]
@manuelap-msft, thank you for the valuable insights. Indeed, we can retrieve apps and flows associated to solutions through tools within governance and core components. Nevertheless, that would be case by case with a manual review to look for those associated views based on the N:N relationship between core components tables (PowerApps Apps, Flows and Power Platform Solutions tables). For our scenario, we're trying to allocate every time an app or flow is created within the company on which solution is created in the case is marked within the issolutionapp and issolutionflow columns as Yes. Is there a way you can recommend to us to create a lookup column between PowerApps Apps and Power Platform Solutions table form the CoE?
Thank you!

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are a very small team and not staffed to assist with customizations. But we can leave this open for a little while to see if anyone from the community can hop in to assist.

**Comment by manuelap-msft** [comment]
No further action required. Thank you for using the CoE kit!
