### ISSUE TITLE
[CoE Starter Kit - BUG]  "HELPER-ObjectOperations.Run failed: The method 'Run' has an invalid value for parameter 'text"  when trying to share an App from PP Admin View

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#5437]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The sharing feature is very useful. IT has worked in the past but I now get the error message in the Title

### Expected Behavior

successful share

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

core components 4.4.1

### What app or flow are you having the issue with?

HELPER - ObjectOperations

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1) select App in Admin View
2) select' shared with' , 'manage permissions'
3) search and select the user
![Capture](https://user-images.githubusercontent.com/78494876/236271024-0a210989-ae71-48d0-b6fc-a056564b9727.JPG)

**Comment by Jenefer-Monroe** [comment]
Thank you for posting. We have this one local fixed for May release via https://github.com/microsoft/coe-starter-kit/issues/5149

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
