### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Admin | Sync Template v3 failing with error "Action 'Get_organization' failed"

### ISSUE THREAD

**Issue by williamlai11** [microsoft/coe-starter-kit#5439]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v3 failing with error "Action 'Get_organization' failed"

![COEerror](https://user-images.githubusercontent.com/132615496/236324654-19e90f69-747c-4b88-b499-e5a04285afdf.PNG)

### Expected Behavior

Admin | Sync Template v3 run successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Turn On Admin | Sync Template v3
Run Admin | Sync Template v3

**Comment by Jenefer-Monroe** [comment]
Hello. We have this one local fixed for May by this issue: https://github.com/microsoft/coe-starter-kit/issues/5197

If this is blocking you, you an delete this part of the flow, and then remove the unmanaged layer that is created when you install the May release
![image](https://user-images.githubusercontent.com/89584709/231277266-625d3955-c5b2-42e7-83f5-b5cd62d6367a.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
