### ISSUE TITLE
Core components import Unknown Geo: ZAF for Organization

### ISSUE THREAD

**Issue by thomaswz** [microsoft/coe-starter-kit#5441]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I setup a new environment, downloaded and imported "CentreofExcellenceCoreComponents_4_4_2_managed
Received the following error: Solution "Center of Excellence - Core Components" failed to import: Unknown Geo: ZAF for Organization.
Please see the downloaded log: 
[Center of Excellence - Core Components_import (1).zip](https://github.com/microsoft/coe-starter-kit/files/11403984/Center.of.Excellence.-.Core.Components_import.1.zip)

### Expected Behavior

The solution loads without errors, as it was downloaded today so is current and should be production ready. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Import solutions

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. In this environment. 
2. Go to Solutions / Import Solutions. Browse to CentreofExcellenceCoreComponents_4_4_2_managed
3. Fill out environment variables as suggested.
4. Initiate load process and then error appears.

**Comment by Jenefer-Monroe** [comment]
This error does not sound related to the kit but a generalized issue. 
Can you please tell me, what type and region your envt is? 
From https://admin.powerplatform.microsoft.com/environments
![image](https://user-images.githubusercontent.com/89584709/236448954-94b70ef1-1698-4082-a895-13d95f96a652.png)

And then when did you create it? Perhaps it was still provisioning when you tried to install. 
Were you able to install the pre-req creator kit solution? https://aka.ms/creatorkit

**Comment by thomaswz** [comment]
Good day Jenefer,
Thanks for your email and assistance with this.
Please see below: Type is Sandbox, Region is South Africa.
It should not have been provisioning and I tried it twice.
I had to install the creator kit through the app link.
[image: image.png]

**Comment by Jenefer-Monroe** [comment]
I believe you've hit a product issue and will need to contact product support for assistance. 
Please try to manually install some other solution. I've attached one for you if you dont have another. 
[testsolution_1_0_0_1_managed.zip](https://github.com/microsoft/coe-starter-kit/files/11410649/testsolution_1_0_0_1_managed.zip)

**Comment by thomaswz** [comment]
Hi Jenefer, thanks - your test solution imported successfully!
Please can you let me know what I should do now?

**Comment by thomaswz** [comment]
Please note that I have been able to install it in a Europe environment, but not in a South African environment. Please can you kindly let me know who I must log this with?

**Comment by thomaswz** [comment]
Kindly note that I have logged a support request.

**Comment by thomaswz** [comment]
Hi Jenefer, 
I have been working Microsoft support, and they can't seem to find the issue. 
Please can I ask that you check the organization codes to see if they validate to a location... and if ZAF is missing from that?

**Comment by thomaswz** [comment]
Hi Jenefer, 
Please note that the error code above states that Geo for the organisation is ZAF.  The environment setting is
"Cluster geo name: ZA".
This look like a bug in this program as the Geo is ZA and Not ZAF. 

I have been working with the Microsoft support and we are as yet unable to resolve it yet. From this comment, it seems that the issue is a bug in this program and not the platform.

**Comment by manuelap-msft** [comment]
Hello,

looks like you've raised a new ticket for this issue now, so I'll close this as duplicate. 

Manuela
