### ISSUE TITLE
[ALM Accelerator - QUESTION] Maker Environment

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5443]
### What is your question?

HI,

I created Deployment profile in Admin ALM APP. In Maker environment   "Import Solution"--->Select a Profile it is showing  two profiles and selected  ALM Project profile but it is not showing Solution Source, Solution Folder and Configuration options.

![image](https://user-images.githubusercontent.com/126264610/236540613-df4437f1-4d10-464c-9671-36b7114cbe1b.png)

Did i miss any steps?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 19th 2023

**Comment by lingutla123** [comment]
Let me explain the background and post my question again:
Currently when we need to implement the changes on prod deployed application, we are making changes in DEV environment, export as managed solution which gives the zip file. We move this zip file into DevOps and then through pipeline we deploy to higher environments. 

Where and how can we leverage the ALM Accelerator in this process? Can I get any documentation around this to ensure that we are doing it correct way.

Currently, through Admin app, we are creating profile ( to import zip file).  In Accelerator app, able to select the profile; however, the other options do not have any values to select.

**Comment by lingutla123** [comment]
Is this works for Model Driven Apps?

**Comment by mikefactorial** [comment]
@lingutla123 Yes, the ALM Accelerator works for anything that can be added to a solution in Dataverse including Model Driven apps.

**Comment by lingutla123** [comment]
I created a new power app solution and created a pipeline in DevOps. As you mentioned to create profile in Accelerator app. I ma trying to create a profile in Accelerator app but i can't see any value in "solution dropdown" .

![image](https://user-images.githubusercontent.com/126264610/236936610-681bf5f5-a39b-4c4d-8599-ef84f1bea9b7.png)

**Comment by mikefactorial** [comment]
@lingutla123 are there any initialized repositories in that project?

**Comment by lingutla123** [comment]
Hi,

I figured out why i can't able to see. I was using service account that's why. Now i logged into Maker env with my regular credentials.
