### ISSUE TITLE
[CoE Starter Kit - BUG] "List Flows as Admin" with: "The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '210250653' bytes.

### ISSUE THREAD

**Issue by shanelaney** [microsoft/coe-starter-kit#5444]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

"Admin | Sync Template v3 (Flows)" fails on action "List Flows as Admin" with: "The action 'Get_Connections_as_Admin' has an aggregated page results size of more than '210250653' bytes. This exceeded the maximum size '209715200' bytes allowed."

We see this succeeding for some environments, but failing when it runs against the "Default Environment".   The flow then fails to update the "Flows" table with records for the "Default Environment" and the CoE Dashboard is missing the same records.

Here is the "List Flows as Admin" step in the flow:
![image](https://user-images.githubusercontent.com/3108209/236576577-e6297aac-3de1-4b28-b006-2cdbb97014c0.png)

We then made a few adjustments to attempt to solve the issue:

We changed the flow to "List Flows As Admins V2", but had to adjust "Filter Flows" to do nothing because this new stage returns less fields and not the date fields used in the filter.

After making these changes, we noticed the "Flow" table doesn't have "Flow Created On" for the records.  Now that the Table is missing data for this field, the CoE Dashboard fails to update records because it is obviously missing data in key fields.

Has anyone run into this and solved it?

### Expected Behavior

We expect the flow to work for a customer's default environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1, but this happens with earlier versions too.

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

We have a environment where many flows have been created in the default environment.

**Comment by Jenefer-Monroe** [comment]
Hello. Yes the created on and modified on dates were missing from the v2 call until just the last week or so. We have upgraded the flow to use this and will be releasing it mid-May for the May release as the last few issues with the new connector resolve. 
Please see https://github.com/microsoft/coe-starter-kit/issues/5137

**Comment by shanelaney** [comment]
Great, thank you so much!
