### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Setup Wizard - More Features -- Audit Log setup

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5446]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

was trying to use the Audit log Setup Wizard to configure this feature 

<img width="239" alt="image" src="https://user-images.githubusercontent.com/112712553/236631117-5f49ad66-eb97-41e2-86be-a8dc0772a330.png">

The moment I click on Configure this feature link 
<img width="228" alt="image" src="https://user-images.githubusercontent.com/112712553/236631169-26e4b2c9-9e75-411c-a696-7c2b6d317c8a.png">

It takes me to the documentation of how to setup the Audit log component. https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

It seems to be a bug to me but still need to clarify if this is the expected behaviour

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. This one is on our backlog as https://github.com/microsoft/coe-starter-kit/issues/4283. 
Will go ahead and close out as a duplicate. 
Thanks for using CoE
