### ISSUE TITLE
[CoE Starter Kit - QUESTION - Shouldn't we have the apps here in CoE setup wizard to share

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5447]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/112712553/236631620-423e66c2-dc3e-4257-8915-a459331a774d.png">
 In the above CoE setup wizard screen, shouldn't we have the app 'App Catalog' on the screen to be shared as we have on other wizards 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. This one is on our backlog as https://github.com/microsoft/coe-starter-kit/issues/5173.
Will go ahead and close out as a duplicate.
Thanks for using CoE
