### ISSUE TITLE
"Command Center App > Get CoE FLows" flow not running,  envtGUID not supplied

### ISSUE THREAD

**Issue by kabirstein** [microsoft/coe-starter-kit#5448]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This flow was on but was not running because it was looking for "envtGUID". Apparently this is supposed to be supplied by the Command Center App in the Core component since the trigger is Power Apps. I guessed that the GUID it was looking for was the GUID of the COE Starter Kit environment so I tested the flow and it ran. 

I looked in the Environment Variables listed in the Command Center and there is no "envtGUID" environment variable. Also, in the trigger there is a Yes/No variable called "Get Turned  On", which appears to be set to "No". What is this parameter for? 

Why is the purposes of this Flow and why is it not running automatically? It seems like it should run when the Command Center is played? Correct? Is there any documentation about it? 

### Expected Behavior

Flow should run, apparently, when turned on.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Command Center App > Get CoE FLows

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Just noticed that this flow had never run 6 weeks after the March COE installed. . .

**Comment by Jenefer-Monroe** [comment]
Hello. This flow was deprecated, it was just left in for a legacy reason and has actually been removed for the May release. Its no longer needed for the way we fetch the CoE flows into the command center.

**Comment by manuelap-msft** [comment]
No further action required. Thank you for using the CoE kit!
