### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flows) -> Get Flow as Admin failing for Teams environment

### ISSUE THREAD

**Issue by FQ365Microsoft** [microsoft/coe-starter-kit#5449]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Since 26th Apr 2023, Admin | Sync Template v3 (Flows) flow is failing for Teams environment on action Get Flow as Admin. The account that connect is global power platform admin. It works fine for the other environments but failing on Teams for few few days. 
"error":{"code":"UserNotMemberOfCdsSecurityGroup","message":"The user 'XXXXXX-6XXX-4XX5-XXXXXXXX' cannot be created in Microsoft Dataverse because the account is not a member of group '2XXXXX-7b41-XXf4-XXXX-e4XXXXXX4'. Please ask an administrator to add user to the group."}
We have opened a ticket with CSS to see if there are updates on this connector.

### Expected Behavior

List of Flows should be returned.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
