### ISSUE TITLE
[CoE Starter Kit - BUG]: Sync flow - Admin | Sync Template v3 (Apps) has not triggered after creating new app/flow

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#545]
**Describe the bug**
Admin | Sync Template v3 (Apps) has not triggered after creating new app/flow 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [2.1.6]
 - App or Flow [Admin | Sync Template v3 (Apps)]

**To Reproduce**
Activate all sync flows
Create a Test App ( Canvas App)
Ensure that Sync flow is triggered next day
Verify if flow "Admin | Sync Template v3 (Apps)" is triggered or not.

**Expected behavior**
Admin | Sync Template v3 (Apps) flow should be triggered and new entry should be added in the "PowerApps App" table - is that correct?

**Additional context**
Can you please share why flow "Admin | Sync Template v3 (Apps)" has not triggered? Similarly Sync flows for Flows, Modern Driven Apps, PVA, Custom connectors and desktop flows are not triggered too - Could you please share the root cause?

**Comment by DiptiC-InsightRun** [comment]
Thanks for clarifying, in this case - can you further help, why rest of the automated flows are not triggered while the main Sync flow is triggered and ran successfully?

I have created test app/flows to verify if I can see them in the respective tables, however I could not see as Sync flow for Apps was not triggered by the main flow - am I missing anything specific here?

Thanks and Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

I'm unsure why the flows would not trigger - this process is working well for all of our customers and we have not seen any issues with it.

1. Ensure you have the Power Platform Service Admin Role
2. Ensure all flows are turned on

are really the only two steps to follow. The Sync flow for Apps gets triggered when a record in the Environment table is created or modified, so should always trigger after the main Sync flow runs.

Based on some of the other issues you have raised, I'm afraid we may not be able to scale to help you and you may need some hands-on assistance by a partner to help you with the setup of the CoE Starter Kit.

Apologies we couldn't help further,
Manuela
