### ISSUE TITLE
[CoE Starter Kit - QUESTION] Causes of not being able to obtain information on other environments

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#5450]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Imported CoE Starter Kit.
I am successfully getting information on the imported environment, but I am not getting information on the other environments (e.g. default environment).
Where should I check?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The most common cause here is incorrect permissions for the identity running the flow. Namely, that does not have the Power Platform Admin Role permanently assigned. 

Note that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management), this won't be sufficient to run the CoE Starter Kit.

For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by egym07** [comment]
I have been granted the role of PowerPlatform administrator, but I still cannot see other environments.

I have the settings on correctly as per the URL below.
https://learn.microsoft.com/ja-jp/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with

Are there any other possible causes?

**Comment by Jenefer-Monroe** [comment]
Are you not able to see them at all, even in the admin center? https://admin.powerplatform.microsoft.com/environments

**Comment by egym07** [comment]
It is shown in the admin center.

**Comment by egym07** [comment]
Thank you.

The action shown below resulted in an error.
![image](https://github.com/microsoft/coe-starter-kit/assets/91306350/a7da4ac4-18b4-42c0-bf16-d14d5722098f)

The error is as follows
![image](https://github.com/microsoft/coe-starter-kit/assets/91306350/51cb5f90-bc9a-4632-8d5b-559206608a71)

Which one should be corrected?

**Comment by Jenefer-Monroe** [comment]
If you go to the Connections page you should see broken connections on top so that you can fix them
Please see this product article which may help https://learn.microsoft.com/power-automate/add-manage-connections

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
