### ISSUE TITLE
[CoE Starter Kit - BUG] Business Justification SendTo error

### ISSUE THREAD

**Issue by miguelverweij** [microsoft/coe-starter-kit#5452]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Business Justification flow is triggered when a D4T environment is created, In the flow there is some logic in the compose action called SendTo that checks if its a production environment. If yes, it is sent to the environment owner. If not, it is sent to the individual admin provided in an environment variable.

My version gives the following issue. 
![image](https://user-images.githubusercontent.com/50626860/236787269-1da44dfe-0855-4afa-b48f-064e38e3ceee.png)

I am a bit behind, and updating is planned next sprint. I did have a quick look in the most recent version, and the logic is exactly the same.

It seems there is a problem with the outputs('Get_Owner')?['body/admin_useremail'] part. In my case, there is no such output, which results in an error for the trim function.

I can adjust it un an unmanaged layer, but as it is a dataverse call, I would think I am not the only one who is affected by this.
If I am missing something, please tell me.

### Expected Behavior

Get the owner email as the output for this action, if the Environment variable ProductionEnvironment is set to true. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.6

### What app or flow are you having the issue with?

Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Create a D4T environment
2. Set the environment variable Production Environment to True (default)
3. The flow runs successfully, but there is an issue in the action itself

**Comment by Jenefer-Monroe** [comment]
Hello, if you use the Setup Wizard it will make sure you have all the needed fields set. But you need to have values for both of these: 
![image](https://user-images.githubusercontent.com/89584709/236874561-e3a72d8c-b42c-460b-be16-d27f79ee2799.png)
![image](https://user-images.githubusercontent.com/89584709/236875046-faab62bb-bef3-4a53-a9f3-115c1eeb6c34.png)

**Comment by miguelverweij** [comment]
Hi Jenefer,

Thanks for the response. I have values for both env vars. To add some context, I've added the logic of this particular action.

`trim(if(equals(parameters('ProductionEnvironment (admin_ProductionEnvironment)'), false), parameters('Individual Admin (admin_ApprovalAdmin)'), outputs('Get_Owner')?['body/admin_useremail']))`

I haven't updated the environment variable admin_ProductionEnvironment, so it is set to true. This means the compose action is set to outputs('Get_Owner')?['body/admin_useremail']

The problem I encounter is that there is no output admin_useremail in the Get_Owner action. I checked the raw ouput from the action and copied it to VSC to search for it, but it's not there.

I can change the outputs('Get_Owner')?['body/admin_userprincipalname'], which does contain the email, but this creates an unmanaged layer, and I think I am probably not the only one where this is not a valid output?

I hope this is clear enough to understand an reproduce. I am happy to explain it even further if needed.

**Comment by miguelverweij** [comment]
It are actual users. Multiple accounts give the same result.
The output is copied in below. For privacy reasons many values are removed, but all properties are listed.

`{
  "@odata.context": "",
  "@odata.type": "",
  "@odata.id": "",
  "@odata.etag": "",
  "@odata.editLink": "",
  "admin_numberofcustomconnectors_state@OData.Community.Display.V1.FormattedValue": "",
  "admin_numberofcustomconnectors_state": 1,
  "statecode@OData.Community.Display.V1.FormattedValue": "Active",
  "statecode": 0,
  "admin_department": "",
  "admin_numberofflows_state@OData.Community.Display.V1.FormattedValue": "1",
  "admin_numberofflows_state": 1,
  "admin_numberofuiflows_state@OData.Community.Display.V1.FormattedValue": "1",
  "admin_numberofuiflows_state": 1,
  "admin_numberofuiflows@OData.Community.Display.V1.FormattedValue": "0",
  "admin_numberofuiflows": 0,
  "admin_numberofsharepointapps_date@OData.Community.Display.V1.FormattedValue": "5/9/2023 7:28 PM",
  "admin_numberofsharepointapps_date@odata.type": "#DateTimeOffset",
  "admin_numberofsharepointapps_date": "2023-05-09T17:28:58Z",
  "admin_numberofapps@OData.Community.Display.V1.FormattedValue": "1",
  "admin_numberofapps": 1,
  "admin_numberofcustomconnectors@OData.Community.Display.V1.FormattedValue": "0",
  "admin_numberofcustomconnectors": 0,
  "admin_photoobject@odata.type": "#Binary",
  "admin_photoobject": "",
  "admin_numberofcanvasapps@OData.Community.Display.V1.FormattedValue": "1",
  "admin_numberofcanvasapps": 1,
  "admin_userprinciplenamewithoutspecialchars": "",
  "admin_photoobject_timestamp@OData.Community.Display.V1.FormattedValue": "638,191,053,285,252,000",
  "admin_photoobject_timestamp@odata.type": "#Int64",
  "admin_photoobject_timestamp": 638191053285252500,
  "admin_photoobjectid@odata.type": "#Guid",
  "admin_photoobjectid": "",
  "admin_numberofapps_state@OData.Community.Display.V1.FormattedValue": "1",
  "admin_numberofapps_state": 1,
  "admin_userisserviceprinciple@OData.Community.Display.V1.FormattedValue": "No",
  "admin_userisserviceprinciple": false,
  "_ownerid_value@OData.Community.Display.V1.FormattedValue": "",
  "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "ownerid",
  "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_ownerid_value@odata.type": "#Guid",
  "_ownerid_value": "",
  "admin_numberofpvas_date@OData.Community.Display.V1.FormattedValue": "5/9/2023 7:28 PM",
  "admin_numberofpvas_date@odata.type": "#DateTimeOffset",
  "admin_numberofpvas_date": "2023-05-09T17:28:58Z",
  "modifiedon@OData.Community.Display.V1.FormattedValue": "5/9/2023 8:27 PM",
  "modifiedon@odata.type": "#DateTimeOffset",
  "modifiedon": "2023-05-09T18:27:32Z",
  "admin_numberofapps_date@OData.Community.Display.V1.FormattedValue": "5/9/2023 7:28 PM",
  "admin_numberofapps_date@odata.type": "#DateTimeOffset",
  "admin_numberofapps_date": "2023-05-09T17:28:58Z",
  "admin_managerid": "",
  "admin_numberofflows@OData.Community.Display.V1.FormattedValue": "5",
  "admin_numberofflows": 5,
  "admin_numberofflows_date@OData.Community.Display.V1.FormattedValue": "5/9/2023 7:28 PM",
  "admin_numberofflows_date@odata.type": "#DateTimeOffset",
  "admin_numberofflows_date": "2023-05-09T17:28:58Z",
  "versionnumber@OData.Community.Display.V1.FormattedValue": "4,020,706",
  "versionnumber@odata.type": "#Int64",
  "versionnumber": 4020706,
  "admin_numberofsharepointapps_state@OData.Community.Display.V1.FormattedValue": "1",
  "admin_numberofsharepointapps_state": 1,
  "admin_company": "",
  "admin_numberofmodeldrivenapps_date@OData.Community.Display.V1.FormattedValue": "5/9/2023 7:28 PM",
  "admin_numberofmodeldrivenapps_date@odata.type": "#DateTimeOffset",
  "admin_numberofmodeldrivenapps_date": "2023-05-09T17:28:58Z",
  "admin_recordguidasstring": "",
  "admin_photoobject_url": "",
  "admin_m2managerprinciplename": "",
  "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "",
  "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_modifiedby_value@odata.type": "#Guid",
  "_modifiedby_value": "",
  "admin_numberofpvas_state@OData.Community.Display.V1.FormattedValue": "1",
  "admin_numberofpvas_state": 1,
  "statuscode@OData.Community.Display.V1.FormattedValue": "Active",
  "statuscode": 1,
  "admin_numberofenvironments_state@OData.Community.Display.V1.FormattedValue": "1",
  "admin_numberofenvironments_state": 1,
  "_owningbusinessunit_value@OData.Community.Display.V1.FormattedValue": "",
  "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "owningbusinessunit",
  "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname": "businessunit",
  "_owningbusinessunit_value@odata.type": "#Guid",
  "_owningbusinessunit_value": "",
  "admin_numberofcanvasapps_date@OData.Community.Display.V1.FormattedValue": "5/9/2023 7:28 PM",
  "admin_numberofcanvasapps_date@odata.type": "#DateTimeOffset",
  "admin_numberofcanvasapps_date": "2023-05-09T17:28:58Z",
  "admin_numberofcanvasapps_state@OData.Community.Display.V1.FormattedValue": "1",
  "admin_numberofcanvasapps_state": 1,
  "admin_makerid@odata.type": "#Guid",
  "admin_makerid": "",
  "createdon@OData.Community.Display.V1.FormattedValue": "1/17/2023 10:00 PM",
  "createdon@odata.type": "#DateTimeOffset",
  "createdon": "2023-01-17T21:00:43Z",
  "admin_makerisorphaned@OData.Community.Display.V1.FormattedValue": "No",
  "admin_makerisorphaned": false,
  "admin_managerprinciplename": "",
  "admin_userprincipalname": "",
  "admin_numberofpvas@OData.Community.Display.V1.FormattedValue": "0",
  "admin_numberofpvas": 0,
  "admin_numberofsharepointapps@OData.Community.Display.V1.FormattedValue": "0",
  "admin_numberofsharepointapps": 0,
  "_createdby_value@OData.Community.Display.V1.FormattedValue": "",
  "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_createdby_value@odata.type": "#Guid",
  "_createdby_value": "",
  "admin_numberofuiflows_date@OData.Community.Display.V1.FormattedValue": "5/9/2023 7:28 PM",
  "admin_numberofuiflows_date@odata.type": "#DateTimeOffset",
  "admin_numberofuiflows_date": "2023-05-09T17:28:58Z",
  "admin_numberofcustomconnectors_date@OData.Community.Display.V1.FormattedValue": "5/9/2023 7:28 PM",
  "admin_numberofcustomconnectors_date@odata.type": "#DateTimeOffset",
  "admin_numberofcustomconnectors_date": "2023-05-09T17:28:58Z",
  "admin_numberofenvironments_date@OData.Community.Display.V1.FormattedValue": "5/9/2023 7:28 PM",
  "admin_numberofenvironments_date@odata.type": "#DateTimeOffset",
  "admin_numberofenvironments_date": "2023-05-09T17:28:58Z",
  "admin_displayname": "",
  "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_owninguser_value@odata.type": "#Guid",
  "_owninguser_value": "",
  "admin_numberofmodeldrivenapps_state@OData.Community.Display.V1.FormattedValue": "1",
  "admin_numberofmodeldrivenapps_state": 1,
  "admin_numberofmodeldrivenapps@OData.Community.Display.V1.FormattedValue": "0",
  "admin_numberofmodeldrivenapps": 0,
  "admin_accountenabled@OData.Community.Display.V1.FormattedValue": "Yes",
  "admin_accountenabled": true,
  "admin_numberofenvironments@OData.Community.Display.V1.FormattedValue": "0",
  "admin_numberofenvironments": 0,
  "ownerid@odata.associationLink": "",
  "ownerid@odata.navigationLink": "",
  "owningbusinessunit@odata.associationLink": "",
  "owningbusinessunit@odata.navigationLink": "",
  "createdby@odata.associationLink": "",
  "createdby@odata.navigationLink": "",
  "createdonbehalfby@odata.associationLink": "",
  "createdonbehalfby@odata.navigationLink": "",
  "modifiedby@odata.associationLink": "/$",
  "modifiedby@odata.navigationLink": "",
  "modifiedonbehalfby@odata.associationLink": "",
  "modifiedonbehalfby@odata.navigationLink": "",
  "owninguser@odata.associationLink": "",
  "owninguser@odata.navigationLink": "",
  "owningteam@odata.associationLink": "",
  "owningteam@odata.navigationLink": "",
  "admin_maker_SyncErrors@odata.associationLink": "",
  "admin_maker_SyncErrors@odata.navigationLink": "",
  "admin_maker_DuplicateMatchingRecord@odata.associationLink": "",
  "admin_maker_DuplicateMatchingRecord@odata.navigationLink": "",
  "admin_maker_DuplicateBaseRecord@odata.associationLink": "",
  "admin_maker_DuplicateBaseRecord@odata.navigationLink": "",
  "admin_maker_AsyncOperations@odata.associationLink": "",
  "admin_maker_AsyncOperations@odata.navigationLink": "",
  "admin_maker_MailboxTrackingFolders@odata.associationLink": "",
  "admin_maker_MailboxTrackingFolders@odata.navigationLink": "",
  "admin_maker_UserEntityInstanceDatas@odata.associationLink": "",
  "admin_maker_UserEntityInstanceDatas@odata.navigationLink": "",
  "admin_maker_ProcessSession@odata.associationLink": "",
  "admin_maker_ProcessSession@odata.navigationLink": "",
  "admin_maker_BulkDeleteFailures@odata.associationLink": "",
  "admin_maker_BulkDeleteFailures@odata.navigationLink": "",
  "admin_maker_PrincipalObjectAttributeAccesses@odata.associationLink": "",
  "admin_maker_PrincipalObjectAttributeAccesses@odata.navigationLink": "",
  "admin_photoobjectid_imagedescriptor@odata.associationLink": "",
  "admin_photoobjectid_imagedescriptor@odata.navigationLink": "",
  "admin_admin_aibuildermodel_AiCreator_admin_make@odata.associationLink": "",
  "admin_admin_aibuildermodel_AiCreator_admin_make@odata.navigationLink": "",
  "admin_admin_bpf_maker@odata.associationLink": "",
  "admin_admin_bpf_maker@odata.navigationLink": "",
  "admin_admin_solution_SolutionCreator_admin_make@odata.associationLink": "",
  "admin_admin_solution_SolutionCreator_admin_make@odata.navigationLink": "",
  "admin_App_AppOwner_admin_Maker@odata.associationLink": "",
  "admin_App_AppOwner_admin_Maker@odata.navigationLink": "",
  "admin_EnvironmentMaker@odata.associationLink": "",
  "admin_EnvironmentMaker@odata.navigationLink": "",
  "admin_Flow_DerivedOwner_admin_Maker@odata.associationLink": "",
  "admin_Flow_DerivedOwner_admin_Maker@odata.navigationLink": "",
  "admin_Flow_FlowCreator_admin_Maker@odata.associationLink": "",
  "admin_Flow_FlowCreator_admin_Maker@odata.navigationLink": "",
  "admin_portal_PortalOwner_admin_Maker@odata.associationLink": "",
  "admin_portal_PortalOwner_admin_Maker@odata.navigationLink": "",
  "admin_PVA_PVAOwner_admin_Maker@odata.associationLink": "",
  "admin_PVA_PVAOwner_admin_Maker@odata.navigationLink": "",
  "admin_rel_ConnectorMaker@odata.associationLink": "",
  "admin_rel_ConnectorMaker@odata.navigationLink": "",
  "admin_RPA_RPAOwner_admin_Maker@odata.associationLink": "",
  "admin_RPA_RPAOwner_admin_Maker@odata.navigationLink": "",
  "coe_EnvCreationRequest_SystemAdmins@odata.associationLink": "",
  "coe_EnvCreationRequest_SystemAdmins@odata.navigationLink": "",
  "admin_PulseFeedback_Feedbackfrom_admin_Ma@odata.associationLink": "",
  "admin_PulseFeedback_Feedbackfrom_admin_Ma@odata.navigationLink": ""
}`

**Comment by Jenefer-Monroe** [comment]
Do these users not have emails in portal.azure.com?

**Comment by miguelverweij** [comment]
<img width="377" alt="Untitled" src="https://github.com/microsoft/coe-starter-kit/assets/50626860/c47e31a1-091e-47bc-9f2c-6e4f3145153f">

Is this the property you are referring to? This does contain their email.

**Comment by Jenefer-Monroe** [comment]
And is the mail value present in the Maker table in Core?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0f6a7290-760c-47ef-a2a9-96b81aecff4a)

Can you please validate that you have all the inventory flows turned on and running? 
In particular the **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** flow.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0ad0cdab-ad6a-4c95-85b7-2f4d89fdb2d1)

**Comment by miguelverweij** [comment]
After updating, it is working as it should. Not sure what the issue was, but it's resolved. That's the goal. Thanks  @Jenefer-Monroe for your support.
