### ISSUE TITLE
[CoE Starter Kit - BUG] OrphanApps data in COE Governance dashboard is not accurate

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#5454]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have installed COE Starter Kit latest April version with BYODL, we see the OrphanApps data in COE Governance dashboard is not accurate. The orphaned apps data contains owner as unknow for many apps, but in reality the app has an Owner.
Also we were not able to see the SharePointFormApps in COE Dashboard.

### Expected Behavior

OrphanApps should fetch only the apps where Owner is out of organization.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.8.1

### What app or flow are you having the issue with?

COE Governance Dashboard data

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Can you please
1. Share an image of where you are seeing the information incorrectly?

2. Go to the Power Platform Admin View app > PowerApps Apps > Add App is Orphaned column > Filter to Yes. Is the list correct here? 
![image](https://user-images.githubusercontent.com/89584709/236816137-dc3a10f3-d0d7-43ad-be8f-c9e476f0fae9.png)

3. Has the **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** flow been running and passing?

**Comment by ALSPowerPlatform** [comment]
Hello,

Please find screenshots below from Power platform Admin view and status of cloud flow.

Cleanup- sync template (orphaned Makers) is in Turned On state, running successfully.

[cid:ee52c522-b9cf-409c-9ea8-ca61ffba5c4a]

Below is the Data from Power platform Admin with is orphaned to yes, data is not accurate , below are the apps which are not orphaned and have actual Owners.

[cid:fd7e0932-b530-46a6-9103-de0ed598d6fb]

Thanks and regards,
Powerplatform Team.

________________________________

**Comment by Jenefer-Monroe** [comment]
Please note that screenshots do not come through when you respond in email, you will need to log in to GitHub to share them.

**Comment by ALSPowerPlatform** [comment]
<img width="440" alt="AdminviewScreenshot" src="https://user-images.githubusercontent.com/106515181/236989686-dce46aa0-0ab1-47f1-9a41-5b313c069fdd.png">
<img width="569" alt="Flowscreenshot" src="https://user-images.githubusercontent.com/106515181/236989692-f1e497b7-90c6-4fd2-91bb-330505849d27.png">

**Comment by Jenefer-Monroe** [comment]
Is the owner of the apps a person? A service principle? A group?

**Comment by manuelap-msft** [comment]
Can you please make sure all inventory flows are turned on (check the CoE Admin Command Center > CoE flows page)



![Image](https://github.com/microsoft/coe-starter-kit/assets/55705669/6078d278-1edb-4cf8-a496-9669a75be14a)



Specifically, the **CoE BYODL - When Maker dataflow refresh is complete** does clean up of orphans/unknown makers for the Data Export feature.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
