### ISSUE TITLE
[CoE Starter Kit - QUESTION] Customizing the App and Flow table in the "Admin | Email Managers Ignored Inactivity Notification Approval" flow

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5459]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am trying to customize the "Admin | Email Managers Ignored Inactivity Notification Approval" flow

For both the "App" table, and the "Flow" table (that appears in the email that is sent to the Manager),
I want to customize the header names to make them bilingual (in English and French)

How would you specify the columns and values?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
If you go to the **_Admin | Email Managers Ignored Inactivity notifications Approvals_** flow you can see the tables we create there, both headers and values, as shown below. Hope that helps!

![image](https://user-images.githubusercontent.com/89584709/236881866-184d6515-a985-4d5c-88b4-4e283577b78c.png)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
