### ISSUE TITLE
[CoE Starter Kit - BUG]: Flow "Admin | Archive and Clean Up v2 (Start Approval for Apps)" does not send approval request to App Maker

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#546]
**Describe the bug**
Flow "Admin | Archive and Clean Up v2 (Start Approval for Apps)" does not send approval request to App Maker

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Governance]
 - Version [2.1.6]
 - App or Flow [Admin | Archive and Clean Up v2 (Start Approval for Apps)" does not send approval request to App Maker]

**To Reproduce**

1. Upgrade CoE Governance Component by installing latest updates as available in CoE Kit version 2.1.6
2. Activate all Archive Flows

**Expected behavior**
This flow should send the Archival task to App owner as explained here - https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#admin--archive-and-clean-up-v2-start-approval-for-apps

**Additional context**
In the environment, "Archive Approval" has no data at all, while this flow sending approval task, based on "Archive Approval" task data - Is that true? Could you please clarify the root cause?

**Comment by JeneferM-MSFT** [comment]
Hello you have given us the version of Core not Gov, Can you please let us know what version of Governance you are using? 

Can you please also confirm:

1. The values of the Env Variables for the solution? Go to the Default envt to see them and check each value
[Governance Env Vars](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components#update-environment-variables)

1. That you upgraded Gov following the steps outlined in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Unmanaged layers will leave you without the updates actually installed

1. Did the flows run and pass, and if so, can you please follow the path of one you expected to send an approval?

**Comment by DiptiC-InsightRun** [comment]
Hello Jenefer,

Thank you for your attention!

With further research on it, I was able to identify that Environment was enabled only for "Admins" therefore it did not send the Approval task to owner, after disabling that option for the environment, Approval task was being sent to App Owner as expected in the flow.

However, our current concern is that "Archive Approval" table data is removed completely when we import latest CoE Core Solution ( 2.1.6)

MS Support has stated that, It has happened due to latest CoE solution import, while we have used "Upgrade" option, that should not delete the data in "Archive Approval" table. I was wondering if can you help if data will be deleted in "Archive Approval" table if latest CoE core solution 9( 2.1.6) is installed with upgrade option?

Thank you for your time!

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Below is the recommended path for installing updates. Is that the path you are following? 
The table you reference is in Gov not Core, and so the version you are referencing updating to is presumable 1.61
We have never seen data deleted from a table due to upgrade 
There is an action in one of the flows that deletes old entries though, older than a month, and this is intentional. See picture below.

![image](https://user-images.githubusercontent.com/62659043/121031174-5c5ba180-c767-11eb-9265-00e53760ee88.png)
![image](https://user-images.githubusercontent.com/62659043/121032039-21a63900-c768-11eb-8bd7-fa05430201f1.png)

**Comment by JeneferM-MSFT** [comment]
Yes we removed automatic backup as the introduction of the connection references feature made backup and restore of flows unreliable for cloud flows. 

We also received feedback that it was just another hurdle for admins to have to manage and store these things. 
Companies eventually end up removing many thousands of these objects and so always storing a backup of these is expensive and mostly useless. 

Hope that helps. And thanks for using CoE.
