### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Helper - Get Security Role Users failing with: The resolved string values for the following parameters are invalid, they may not be null or empty: 'groupId'

### ISSUE THREAD

**Issue by DS2019** [microsoft/coe-starter-kit#5460]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have seen a few issues in the Issues list with this Flow, not exactly what I'm seeing. I upgraded to April's CoE and all was fine for a few days, and then I had this Flow fail on one environment. Then, as days went on, it started failing on more environments. This is the details of the error I'm getting on all failures:
The 'inputs.parameters' of workflow operation 'List_group_members' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'groupId' I have added a picture of the area of the Flow that is failing. 
![Sync Helper](https://user-images.githubusercontent.com/44073678/236905023-86fa1d9f-31ce-4728-9cec-af46c7ef3b17.jpg)

### Expected Behavior

I've been using the CoE for months, and have not seen this error before. It started happening a few days after upgrading to April's CoE (which has the hotfix on it). 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4-4-2 Core

### What app or flow are you having the issue with?

Sync Helper - Get Security Role Users

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

I am getting messages in my email that some of the sync flows in the Coe Starter Kit have failed. It is the Sync Helper - Get security roles that is failing, now on several environment.

**Comment by Jenefer-Monroe** [comment]
This one is known and fixed for May. Please see https://github.com/microsoft/coe-starter-kit/issues/5242

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by tocri** [comment]
Oh that's  a good new to kown this is a bug. I've plenty messages like this but i couldn't manage these because i had a lot of work to do first. So this morning i was thinking how to resolve this error but i'm happy to read you. You saved me a lot of time.

I'm looking for the next release. Hope it will come soon

**Comment by manuelap-msft** [comment]
The May release with this fix is now available here:
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-May2023
