### ISSUE TITLE
[ALM Accelerator - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by sefa-phaag** [microsoft/coe-starter-kit#5461]
### Is your feature request related to a problem? Please describe.

I have access to multiple Deployment User Settings because I am a system administrator in our ALM COE environment and I constantly have to select my desired setting.

### Describe the solution you'd like

Save the last selected deployment user setting in the same manner that the Select Your Maker Environment dropdown works.

### Additional context?

In my environment, the opened dropdown always defaults to Maker Experience (not really sure why since it was created second and is after Advanced Maker Experience alphabetically). I would prefer it to default to Advanced Maker Experience.

![image](https://user-images.githubusercontent.com/94123640/236906023-f9e1e4af-9bc3-42ef-a9d2-6985db131496.png)

**Comment by mikefactorial** [comment]
@sefa-phaag I think this issue slipped through the cracks when it was submitted so pardon the delayed response. Will look into defaulting the user setting selection.

**Comment by mikefactorial** [comment]
This has been implemented in the September release.
