### ISSUE TITLE
[CoE Starter Kit - QUESTION] Maker's Manager Display Name

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#5462]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team, 

I'm trying to see which flows extract the data for maker's manager name and manager principal name. I believe it's using Office 365 Users Connector to retrieve this information, but which flow gives us the data and how does it get extracted? 

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

it's using the Get Manager action of the Office 365 Users connector: https://learn.microsoft.com/en-us/connectors/office365users/#get-manager-(v2)

And it's the **HELPER - Maker Check** flow that gets and stores this information - you'll have to expand the maker check scope, navigate into the "No" branch of the condition and look for the 200 Success in the switch after the user profile is retrieved, this is where the Get manager call is made:
![image](https://user-images.githubusercontent.com/55705669/237063029-9aef1196-6be0-4a75-987f-227ebba56b87.png)

Does that answer your question?

Thank you
Manuela
