### ISSUE TITLE
[CoE Starter Kit - BUG]  Admin | Sync Template v3 CoE Solution Metadata gives empty body for one of the governance flows

### ISSUE THREAD

**Issue by annsarP** [microsoft/coe-starter-kit#5463]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, our **Microsoft Teams Admin  | Weekly Clean Up of Microsoft Teams environments** flow has failed due to inactive user accounts in our organization. 

![image](https://user-images.githubusercontent.com/127112137/237003810-76ddf111-1ffd-414a-8b1e-08da2877ee29.png)

Flow caught error but couldn't write it to _Last Run Passed_ column because **Microsoft Teams Admin  | Weekly Clean Up of Microsoft Teams environments** flow isn't appearing in the _CoE Solution Metadata_ table. 

![image](https://user-images.githubusercontent.com/127112137/237003932-b7f965e1-2e13-4e5e-b2bf-039d60f56444.png)

![image](https://user-images.githubusercontent.com/127112137/237004218-924668ed-4987-467d-b3c5-90a8240f00f0.png)

I searched **Admin | Sync Template v3 CoE Solution Metadata** flow runs and it seems that for **Microsoft Teams Admin  | Weekly Clean Up of Microsoft Teams environments** flow gives blank body and row is not being added. 

![image](https://user-images.githubusercontent.com/127112137/237004918-374f6e1e-52c3-41f4-a9d7-73b40a901aaf.png)

While for other flows it gives body:

![image](https://user-images.githubusercontent.com/127112137/237005216-425bd987-702f-4959-8ac8-2eaab511860b.png)

### Expected Behavior

Simple errors should be caught and written to table with metadata. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.8.1

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
oh my gosh. Somehow we had two spaces in the name of the flow between Admin and the pipe symbol ( | )
Thank you so much for the great debugging. Still took me forever to figure out what was going on! ha
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a0db585b-44e4-4be9-b413-51abdc52f786)
