### ISSUE TITLE
[CoE Starter Kit - BUG] Nurture Components (power BI dashboard Error)

### ISSUE THREAD

**Issue by VamshiKommineni25** [microsoft/coe-starter-kit#5464]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

 In the Set up the Power BI dashboard to view feedback step in Nurture Components. I'm getting Below Error:

admin_pulsefeedback
Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
admin_maker
Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
Query parameters

![Power BI Error](https://user-images.githubusercontent.com/121937890/237038184-4ace8f65-4600-43cb-97ea-7e45800c7623.png)

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Power BI Dashboard

### What method are you using to get inventory and telemetry?

None

**Comment by Vamshi7981342555** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/121937890/635cab7b-aebf-48ff-af4c-f77e36ca7254)
I'm getting different error

**Comment by manuelap-msft** [comment]
<environment> is a placeholder, you'll have to replace that with your CoE environment name. 

You can get this by 
1. Navigate to make.powerapps.com
2. Select your CoE environment
3. Select the settings cog in the top right corner
4. Look a the instance URL and copy that, remove the https:// when you do your PowerShell query

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
