### ISSUE TITLE
[CoE Starter Kit - QUESTION] CleanUp - Check deleted flow intervene built-in environments clean up process

### ISSUE THREAD

**Issue by marekbuban** [microsoft/coe-starter-kit#5465]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have noticed in PP Admin center that all our environments are being updated every other week (when we have scheduled Check deleted flow).
This is causing a problem that built-in [dataverse environments cleanup](https://learn.microsoft.com/en-us/power-platform/admin/inactive-teams-environment) process doesn't work as environment is never inactive for more than 2 weeks.
Environment cleanup process was deprecated from CoE due to out of the box process. Is this a bug in CoE causing the environments to update Last activity date or are we missing anything?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2023

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Cloud Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by marekbuban** [comment]
Hi @manuelap-msft,

thanks for your suggestions. I've did that - created a flow with List Flows as Admin and I can see that Last activity of an environment has changed - to the time when the flow ran.

 
![image](https://github.com/microsoft/coe-starter-kit/assets/12535089/f8c3a411-c2c0-4ac1-8a31-e5f267a0afb3)
![image](https://github.com/microsoft/coe-starter-kit/assets/12535089/3f9e7453-b113-4435-bd02-008b4ca13406)

Sure, I can reach out to MS, but I'm afraid I'll get a standard MS Support response that this behavior is by design and CoE is not official Microsoft supported tool. I'll give it a try though and will keep you posted.

Thank you for your help so far!

**Comment by manuelap-msft** [comment]
Hello,

unfortunately the Last Activity date is not something that's in our control - it's a PPAC setting, that we don't specificially set. If in the support request you simply don't mention the CoE kit and just articulate that your own flow with which you are performing a read only action is updating the date, you should get through to the right team!

Hope that helps and thanks for investigating here - we weren't able to repo this ourselves, but our tenant is in United States region so there might be a difference based on region.

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
