### ISSUE TITLE
[CoE Starter Kit - QUESTION] PBI out of sync with Core. missing columns

### ISSUE THREAD

**Issue by sydneywilliams2844** [microsoft/coe-starter-kit#5468]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

PowerBI Dashboard refresh issue after upgrade of CoE toolkit.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

PowerBI Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by sydneywilliams2844** [comment]
![MicrosoftTeams-image](https://github.com/microsoft/coe-starter-kit/assets/114082282/40869bf1-080e-4a6d-97df-0c938be061b5)

**Comment by Jenefer-Monroe** [comment]
Hello, you need to keep the PBI and Core versions consistent. So as you upgraded to April you would also need to use the corresponding Production_CoEDashboard_April2023.pbit

In this case we removed a confusing and deprecated field. 
Hope that helps.

**Comment by manuelap-msft** [comment]
No further action required by the CoE kit team. Thanks for using the CoE kit and please let us know if you have further questions!
