### ISSUE TITLE
[CoE Starter Kit - QUESTION] Office 365 Management API connector has been deleted in my environment, How to fix?

### ISSUE THREAD

**Issue by rjpiazza** [microsoft/coe-starter-kit#5469]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello and thanks in advance...I noticed that the Office 365 Management API connector has been deleted in my environment. Is there way to restore that connection or re-import? 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April solution

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. You would need to re-import the solution to get that back. 
Hope that helps.

**Comment by manuelap-msft** [comment]
If the connector still shows up, and you're only missing the connection here's how you can re-establish that:
https://github.com/microsoft/coe-starter-kit/issues/4961

Check here for the custom connector:


![Image](https://github.com/microsoft/coe-starter-kit/assets/55705669/7ae14e03-5586-4997-a857-8fb37c2a1739)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
