### ISSUE TITLE
[CoE Starter Kit - BUG] Column 'admin_useremail' in Table 'Power Platform User' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. (admin useremail (950307))

### ISSUE THREAD

**Issue by kartrabby** [microsoft/coe-starter-kit#5472]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When Loading the CoE Dashboard April-2023, I am receiving the following error.

Column 'admin_useremail' in Table 'Power Platform User' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. (admin useremail (950307))

### Expected Behavior

![image](https://github.com/microsoft/coe-starter-kit/assets/95188375/cce1009f-4404-4a85-9e3d-2b4d7b7178f7)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

Power BI CoE Dashboard

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I do have blanks in that column and the dashboard works. 

Can you please let me know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

And also share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by kartrabby** [comment]
@Jenefer-Monroe : I faced this issue while upgrading the CoE Toolkit. Below are the details as requested !

We have entries in the table Power Platform USer in the CoE Dashboard. BUt also has some null values.

![image](https://github.com/microsoft/coe-starter-kit/assets/95188375/2097f8d2-4a10-41cb-8dfe-45e5fa8ac09c)



![image](https://github.com/microsoft/coe-starter-kit/assets/95188375/2f9e25b3-7465-4c43-a45f-0b31157226b9)

**Comment by Jenefer-Monroe** [comment]
Which of those envts is your CoE? The Europe or US? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fdc37b44-2d4a-43f0-9a69-9e7479b9200a)

**Comment by kartrabby** [comment]
@Jenefer-Monroe : The CoE Environment in the Europe Region !

**Comment by Jenefer-Monroe** [comment]
Do you have entire blank rows in the table? 
Please go to the Power Platform User table. Have these two columns in place > filter where Record GUID as String does not contain data. Are there records? Do they have a Power Platform User guid? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66a6cb36-c87e-43f9-a7f9-4a2f5aaa898a)

**Comment by Jenefer-Monroe** [comment]
And plesae also let me know, are you loading from a PBIT? If so which one. 
Or are you refreshing when you see this?

**Comment by kartrabby** [comment]
@Jenefer-Monroe : We have almost 3000+ rows ,

- but some of the **User Email** are empty and
- all the **UPNs** have data except for external users !

![image](https://github.com/microsoft/coe-starter-kit/assets/95188375/14506f42-caa5-4a24-92d1-77ec210719a2)

**Comment by kartrabby** [comment]
@Jenefer-Monroe : I think I have fixed the issue

I modified the relationships

Required !
![image](https://github.com/microsoft/coe-starter-kit/assets/95188375/81e31ec6-e9c2-4cd9-99cc-5f93a97db001)

Actual !
![image](https://github.com/microsoft/coe-starter-kit/assets/95188375/fb7622a1-0b94-4b3f-ad66-bdcd94c0d455)

**Comment by Jenefer-Monroe** [comment]
Thank you for pressing and investigating! Love our customers!!!

I checked and didnt see that in my PBI. Let me make sure, perhaps you were on an old copy?

**Comment by Jenefer-Monroe** [comment]
OK I have validated we only had one relationship in the shipping copies. Thank you again for debugging! I'll go ahead and close but please let us know if you have questions in the future.
