### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by guptapranjal1995** [microsoft/coe-starter-kit#5473]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

List Flows as Admin Action failing in CoE Starter Kit for Admin | Sync Template Flows Power Automate

### Expected Behavior

Expectation is that the issue should be resolved by replacing the action with List Flows As Admin V2 as it does not have file size limitation

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin - Sync Template v3 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
This is already on our roadmap, part of the upcoming May release:
https://github.com/microsoft/coe-starter-kit/issues/5137

Closing as duplicate.
