### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow Admin | Sync Template v3 failed when Entity 'admin_environment' Does Not Exist, MakerDisplayName is empty. Should we remove the Environment?

### ISSUE THREAD

**Issue by PatrickGroen1** [microsoft/coe-starter-kit#5474]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Just one environment causes the Admin | Sync Template v3 flow to fail. The failure is similar to #2144 Action 'Get_Environment' failed, but with Error message: Entity 'admin_environment' With Id = 42fd295c-cb5e-45f8-9e76-4ec8a2332cab Does Not Exist". In Power Platform Admin Center we see the environment started 23/11/2017, 18:49:00 and Initiated by is blank. The environment has no Resources and no user has access. After the flow failure we added two Environment admins and one Environment maker, but the Initiated by value is not  still the flow failed. 

The 'Get Maker'step fails with status 'BadGateway' 8 retries occurred. The input field MakerID = SYSTEM, MakerDisplayName is empty. Is the blank 'Initiated By' the reason why the environment is not in the dataverse table? Should we remove the entire environment to make the flow succeed and prevent the flow from being turned off? Or is there a way to solve the error and somehow keep the envrionment? Thank you for your help

![Environment-Details](https://github.com/microsoft/coe-starter-kit/assets/34736899/d4494bfb-b490-48b8-b863-d33640fa55b2)
![Get-Maker-step-MakerDisplayName-is-empty](https://github.com/microsoft/coe-starter-kit/assets/34736899/42655449-59be-4fe7-bf76-0169b285d754)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.1

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
It sounds like its a bad environment, perhaps something went wrong when it was created. Since no one has access / uses, perhaps just delete it?

**Comment by PatrickGroen1** [comment]
Thank you, Jefener, for your swift reply. 

It was not possible to trace more history about this environment. I deleted the bad environment and Admin | Sync Template v3 ran successfully
