### ISSUE TITLE
[CoE Starter Kit - QUESTION] What happens if we add new field to table

### ISSUE THREAD

**Issue by krhoadesnh** [microsoft/coe-starter-kit#5475]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have interpreted different things from the documentation & your responses to other questions so going to the source.  Is it possible for us to add a field to one of the dataverse tables (specifically Flows) that won't be overwritten with an update?  I am new to model driven apps but did I understand correctly that if we are modifying tables through a custom MDA those table changes would merge?

Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
What is and is not mergable in Dataverse is a little complex. But in my experience yes you can add columns to a table and you can add columns to a MDA form / view, and those will all persist.

**Comment by manuelap-msft** [comment]
There's some guidance on this here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

**Comment by krhoadesnh** [comment]
> There's some guidance on this here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

Thank you, I had read that but also read in questions that everything can be overwritten.   Thank you both (as always) for the prompt responses.
