### ISSUE TITLE
[CoE Starter Kit - BUG]: Admin | Sync Template v3 (Check Deleted) does not finish

### ISSUE THREAD

**Issue by mschaefer85** [microsoft/coe-starter-kit#548]
**Describe the bug**
The flow Admin Sync Template v3 (Check Deleted) either fails or does not finish. Accordingly, some deleted elements do not disappear from the CoE, like environments that have been deleted weeks ago.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]: **Core**
 - Version [e.g. 1.29]: **2.1.6**
 - App or Flow [e.g. Sync Template (v2)]: **Admin | Sync Template v3 (Check Deleted)**

**To Reproduce**
1. Install the Core Components.
2. Wait for the flow Admin | Sync Template v3 (Check Deleted) to trigger automatically or trigger it manually.
3. Flow either fails (happened the first time) or runs for a very long time (> 15 days)

**Expected behavior**
I'd expect the flow to finish and delete obselete items from the CoE.

**Screenshots**
As you can see, the flow keeps running for more than two weeks; the next one is starting already:
![image](https://user-images.githubusercontent.com/10259284/120324456-f0041c80-c2e6-11eb-9967-303bcfd15bef.png)

The first time this flow was executed, it failed after 5 days:
![image](https://user-images.githubusercontent.com/10259284/120324556-0f02ae80-c2e7-11eb-813a-60230952197c.png)

**Additional context**
The Power Platform we're dealing with here is huge, with tens of thousands of users and several hundreds of environments.

**Comment by manuelap-msft** [comment]
Hello,

this flow crawls the entire tenant to compare what's in the tenant with what's in the Dataverse tables. It's a long running flow that consumes many API calls and in your case is hitting throttling limits. 

Unfortunately, from a CoE Starter Kit point of view, there's nothing we can do - we know that this flow is very resource heavy and have optimized it as much as possible. 

Please check the Flow Analytics to see how many actions daily this flow consumes and see if they could be met with the Power Automate per flow plan https://docs.microsoft.com/en-us/power-automate/limits-and-config
![image](https://user-images.githubusercontent.com/55705669/120326631-d6f86d00-c2e0-11eb-9eac-2f3033ad71e5.png)

Thank you,
Manuela

**Comment by mschaefer85** [comment]
> Hello,
> 
> this flow crawls the entire tenant to compare what's in the tenant with what's in the Dataverse tables. It's a long running flow that consumes many API calls and in your case is hitting throttling limits.
> 
> Unfortunately, from a CoE Starter Kit point of view, there's nothing we can do - we know that this flow is very resource heavy and have optimized it as much as possible.
> 
> Please check the Flow Analytics to see how many actions daily this flow consumes and see if they could be met with the Power Automate per flow plan https://docs.microsoft.com/en-us/power-automate/limits-and-config
> ![image](https://user-images.githubusercontent.com/55705669/120326631-d6f86d00-c2e0-11eb-9eac-2f3033ad71e5.png)
> 
> Thank you,
> Manuela

test

**Comment by mschaefer85** [comment]
Thanks for your quick reply! We'll check that.

Just to get a better understanding:

- If the number of action is too large, even for a Power Automate Per Flow plan, this would mean that this workflow will not work as itended.
- In that case, deleted flows, environments, apps etc. might not disappear from the CoE. Which means that the CoE might **not** display the current status and thus be unusable.

Is that understanding correct?

**Comment by manuelap-msft** [comment]
Hello,

yes, that's correct. 

Two notes:
1. If you have the Audit Log solution configured and check Audit Logs, these also record when a flow or app is deleted and update the PowerApps App and Flow table accordingly. However, "Delete" events in the Audit Log don't exist for environments, bots, desktop flows, model driven apps etc so some other resources will be out of date there. Additionally, for very large tenants you will also see throttling on the Audit Log flows.
2. Look for this feature to go into public preview https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate as it will push inventory and telemetry information into your datalake, from where you can build reporting on it. For large tenants, this will be a better and more sustainable way of building custom reporting then the "CoE way" of using cloud flows.

Thank you
Manuela

**Comment by mschaefer85** [comment]
Hello,

thanks for the updates!

Concerning number 2: Would this be the best alternative to monitor (very) large tenants, that cannot be covered by the CoE Starter Kit anymore?

**Comment by mschaefer85** [comment]
Also, here are the screenshots for the flow's analytics:

![image](https://user-images.githubusercontent.com/10259284/120827194-79bc2000-c55b-11eb-8eee-1d569737528c.png)

![image](https://user-images.githubusercontent.com/10259284/120827266-8f314a00-c55b-11eb-8b56-df1ee87c4505.png)

**Comment by manuelap-msft** [comment]
Thanks for providing that screenshot - long term, even with a Power Automate per Flow license this consumes to many actions to complete successfully however in the interim you may be able to use a D365 license (if available) or Power Automate per Flow license for these flows - check the description here: 
https://docs.microsoft.com/en-us/power-automate/limits-and-config#action-request-limits

There are planned limits, and interim limits - as the product transitions further into enforcing limits, more flexibility has been given and the enforced limits are higher than the plan at the moment. So based on this a MediumLow2 or High performance profile should cover the 80,000 actions in 24hours. 

Long term, yes the best option to monitor large tenants is to go with the BYO Datalake Option. I believe this is now targeted to go live end of June. Customers will be able to build their own reports on top of the Datalake, and we are also exploring if we can offer the CoE dashboard on top of the datalake as a template / starting point. Currently estimating that this will take 1-2 months after the BYO Datalake option is available in the product, as we will need to do some re-platforming and testing. 

Hope that helps provide guidance on what to do as next steps,
Manuela

**Comment by JeneferM-MSFT** [comment]
Hello I believe you are running an old version of this flow as that action used to fail in that manner for an incorrect null check. 

Please upgrade using the steps described in [installing udpates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) as any unmanaged layers present will prevent you from getting that fix.

**Comment by JeneferM-MSFT** [comment]
While you await the Bring your Own Datalake feature, you can request an exemption to the throttling, but please note that it will be temporary and expire once that feature is available.

Here are the steps to follow to request the exemption:
1)	Gather the flow ids for the flows that are being throttled.
2)	Create a support ticket with the following information:
```
- Purpose of ticket: Power Automate throttle request - raise throttle limit
- Refer support to this ICM: [MSFT ICM # 241151666](https://portal.microsofticm.com/imp/v3/incidents/details/241151666/home)

```

Here are ones that are known to be long running and which may be impacted for you:
| Solution | Flow Name |
| ----------- | ----------- |
| Header      | Title       |
| Header      | Title       |
| Header      | Title       |
| Header      | Title       |
| Header      | Title       |
| Header      | Title       |

**Comment by manuelap-msft** [comment]
That's correct - based on your license, you have a specific number of Actions per 24 hours. The reason the flow doesn't complete is because it uses up the actions per 24hours day over day until it finishes. A Power Automate per Flow license has a higher volume of allowed actions per 24 hours, so the flow would complete faster.

**Comment by mschaefer85** [comment]
@JeneferM-MSFT, @manuelap-msft - thank you both for being so supportive!

We'll try to get an exemption for the short-term and see whether this will let the flows run faster.

Because at the moment, apparently there is already a D365 license assigned to the user running the flows: the "Dynamics 365 Customer Engagement Plan". As far as I understand, this would count as a "MediumLow2" performance profile and grant (at least for the time being) 100,000 actions a day. This should be enough for "CLEANUP - Admin | Sync Template v3 (Check Deleted)" (with 77,000 at its maximum), but I suppose there are other flows that also use up the rest of the available actions.

**Comment by mschaefer85** [comment]
@JeneferM-MSFT: I tired to access the resource you've linked to ([MSFT ICM # 241151666](https://portal.microsofticm.com/imp/v3/incidents/details/241151666/home)), but got no access - I guess you mean we just need to link to this when creating the ticket?

Also, I understand that we should exemption for all the flows you've listed.

**Comment by JeneferM-MSFT** [comment]
Correct, that link is just for you to share with support. It's internal documentation to make the back and forth between you and support faster. 

Regarding which flows, that is a list of potential flows that might be throttled, please see which flows you believe are being throttled and include only those in your list.

Hope that helps.

**Comment by JeneferM-MSFT** [comment]
closing out as no additional work for the toolkit
