### ISSUE TITLE
[CoE Starter Kit - QUESTION] Exclude CoE env from Power BI reporting

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5484]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there an easy button to customize the Power BI report to make the default view exclude the COE env and COE service account principal used (as it skews the numbers)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We do not have something like that although you could add a report wide filter which filters out that envt.

And then we also offer the ability to only inventory a subset of environments:
https://learn.microsoft.com/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments

Hope that helps!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
