### ISSUE TITLE
[CoE Starter Kit - QUESTION] Will the new default environment routing feature affect the CoE in any way?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5485]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Will the new default environment routing feature affect the CoE in any way?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
No impact on CoE
