### ISSUE TITLE
[CoE Starter Kit - QUESTION] send an environment dependent Welcome Mail 

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5487]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What do you recommend to send an environment dependent Welcome Mail when someone creates a first Flow/Power Apps/Solution?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
This would not be straight forward to detect in a performant way. Will leave open a few days to see if people in the community have an idea.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
