### ISSUE TITLE
[CoE Starter Kit - QUESTION] only use BYODL inventory for telemetry

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5489]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is a combination of cloud flows and BYODL inventory planed? BYODL only for telemetry. Because in my byodl installation are less environments, apps etc. shown

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
No there is no such plan. If you see missing objects from the Data Export it is likely either a day (it can take a few days for new objects to show up in the export) or a product bug. Please do let us know.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
