### ISSUE TITLE
[CoE Starter Kit - QUESTION] identify those flows that send approvals to mail, teams etc

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5490]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

A way to identify those flows that send approvals to mail, teams etc so that when someone clicks somewhere, we can see if it orphans the flow?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont follow this ask. Will leave open in case the questioner can clarify.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
