### ISSUE TITLE
[CoE Starter Kit - QUESTION] include your Power BI reports into your Core solution directly

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5491]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Any plans to include your Power BI reports into your Core solution directly in the future (as solution managed artefact)?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We do have a feature for this but it is blocked by some feature gaps. 
https://github.com/microsoft/coe-starter-kit/issues/4085
