### ISSUE TITLE
[CoE Starter Kit - QUESTION] When will the Starter kit generally available in Azure datasources instead of Dataverse?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5493]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When will the Starter kit generally available in Azure datasources instead of Dataverse?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately we are blocked by the product's Data Export feature itself going to Generally Available.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
