### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can App insights be integrated into the CoE or how can both be leveraged?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5494]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can App insights be integrated into the CoE or how can both be leveraged?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
This feature area is too bespoke for us to pull in in any generalized way. But this would be an area for folks to extend their own kits as their organization uses that feature.
