### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there a way of excluding certain environments or types of environments from the inventory flows?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5495]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way of excluding certain environments or types of environments from the inventory flows?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Here's a writeup of how to do that:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
