### ISSUE TITLE
[CoE Starter Kit - QUESTION] What is the best way to track child flows (who are using them, where, if any are "orphaned". etc? links for guidance or CoE reports?)

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5496]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What is the best way to track child flows (who are using them, where, if any are "orphaned". etc? links for guidance or CoE reports?)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
There is no top level flag to identify child flows today.

After investigation, here's what we could do:
As of today, CoE starter kit would need to traverse all flow definitions, extract the flow IDs from the "Run a child flow actions" and map to the related flows. 
Or take a fuzzy approach of listing possible child flows - flows with manual triggers AND one of the below two response actions. 
Respond to a Power App or flow (under the Power Apps connector).
Response (on the premium HTTP request/response connector).

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
