### ISSUE TITLE
[CoE Starter Kit - BUG] Suspended flow  and  Triggers  missing information's in Azure Data Lake

### ISSUE THREAD

**Issue by JihenKembi** [microsoft/coe-starter-kit#5499]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello , 
After we configured Data Export to Azure Data Lake , we have some missing Data : Suspended Flow and triggers  informations . 
The columns exists in Power BI table byod_flows  but the data is empty 
![image](https://github.com/microsoft/coe-starter-kit/assets/19647002/521e40ce-3c0f-463a-8a08-e4a42e558efb)
![image](https://github.com/microsoft/coe-starter-kit/assets/19647002/72297d6e-d77e-47cc-8d50-80b2d92c2ef1)

### Expected Behavior

ggggfff

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately there are some fields not yet supported by the Data Export and so we have to add those via a sync flow that runs after the dataflow completes. Hopefully over time we can remove those API calls and just rely on the JSON. 

Hope that helps.

**Comment by manuelap-msft** [comment]
Hello,

the Data Export feature is a Power Platform product feature, and our team does not support it. We are just consumers of this feature as well, like we are consumers of the connectors etc. 

You can find the schema definition of what's returned by Data Export here:
https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics-schema-definition

As far as I know, fields that aren't mentioned in this documentation, and are empty on export are currently just placeholders for once this information is available via Data Export.

For further questions that are only related to Data Export and not the CoE kit, you'll have to go through other Microsoft support channels https://learn.microsoft.com/en-us/power-platform/admin/get-help-support

Thank you
Manuela
