### ISSUE TITLE
Error in Add pain points flow in Innovation Backlog

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#55]
I installed the Innovation Backlog solution and when I ran the **Add pain points** flow I got the error in the screenshot below.

Looks like the flow is corrupt around the name of the **Innovation Backlog Pain Points** entity in the **See if already exists** and **Create a new record** actions.  I refreshed the Table name parameter in both of those actions and this seemed to fix the issue.

Issue screenshot
![image](https://user-images.githubusercontent.com/41050216/109623078-a863dc80-7ba1-11eb-8bbf-3c0de43c54d9.png)

Solution screenshot
![image](https://user-images.githubusercontent.com/41050216/109623637-36d85e00-7ba2-11eb-82b2-49d987c0ba64.png)

**Comment by mikefactorial** [comment]
Hi @HamishSheild,
Pardon the delay. This repo isn't currently active. We're in the process of transitioning CoE Starter Kit here, but for the time being would you mind posting this issue to https://github.com/microsoft/powerapps-tools/issues instead?
