### ISSUE TITLE
[CoE Starter Kit - QUESTION] PVA/Bot Archival?

### ISSUE THREAD

**Issue by StewartSJLDS** [microsoft/coe-starter-kit#5501]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Other than scripting to have a bot be placed into a solution then exported, does anyone else do archival of their PVAs or have other suggestions of best accomplishing it? I have seen the documentation on exporting via solution, but we'd like to avoid that if possible. Road map maybe?

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
No further action required. Thanks for using the CoE kit, and please let us know if you have any more questions!
