### ISSUE TITLE
[CoE Starter Kit - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by Reinhard-S** [microsoft/coe-starter-kit#5506]
### Is your feature request related to a problem? Please describe.

We currently do not know how PowerBI reports are being used within an organization.

### Describe the solution you'd like

Please also include statistics on PowerBI reports/dashboards within the Center of Excellence Dashboard.

All features implemented for Apps are basically applicable for PowerBI, especially usage statistics on reports based on Audit Log data, relevant actions e.g.:
- Viewed PowerBI Dashboard
- Created PowerBI Dashboard
- etc...

### Describe alternatives you've considered

- Custom extension of flows *Admin | Sync Logs* and *[Child] Admin | Sync Logs*.
  -> Not perfect as we do not want unmanaged layer on these flows
- Custom implementation cloning these flows collecting PowerBI-related Audit Logs.

**Comment by manuelap-msft** [comment]
Hello,

Power BI is out of scope of what the CoE kit team currently looks after, and there's currently no investments being made to add Power BI to the CoE kit. It's a different team that looks after admin&governance for Power BI. I'm aware of one other open source tool (not related to the CoE kit) that helps with Power BI monitoring: https://github.com/RuiRomano/pbimonitor - I'm myself not familiar with this but that may help you.

Manuela
