### ISSUE TITLE
[ALM Accelerator - QUESTION] Deployment Profile Setup

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5508]
### What is your question?

Hi,

Created a Project Wizard through the ALM Accelerator Admin App. I followed the steps from the below video.
https://www.youtube.com/watch?v=oe7zPIoSWpo
Successfully created a profile from ALM Accelerator App. Watched below video.
https://www.youtube.com/watch?v=0F4cT_YxakQ&t=347s
After Commit the solution getting error (info: Pipeline template does not exist /Master7/deploy--Master7.yml). 

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/67ae5240-126c-4c69-9fed-70045c6ce0fe)

This is my DevOps Project.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/525ed3ff-8675-4dfb-8d7e-1a2e1e3523b9)

This is Solution Profile
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/d7e859b5-44a8-48d8-89ac-5057cc4bedb7)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 19th 2023

**Comment by lingutla123** [comment]
Actually i created Test and Prod environments in PowerApps but the ALM Accelerator App is not showing the environments.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/b2e8b009-fef4-4489-9f4b-092519dc6572)
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/3fc42e6d-45fb-4710-9dde-0de7f1d8eb83)

**Comment by lingutla123** [comment]
Do i need to create a Hook for update deployment settings?

**Comment by mikefactorial** [comment]
@lingutla123 that is just an info message and not an error. Are the pipelines being created? Can you supply the full log?

**Comment by lingutla123** [comment]
here is the complete log
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/6be3c338-4414-430e-9939-51aad0076b9b)
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/1c91deca-d3d8-495b-a528-f46f97e21341)
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/a9ad590f-1198-4efe-88a0-90346bf8e359)
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/9ec42e1b-d537-4b29-a81e-c07ca3e2ee31)

**Comment by mikefactorial** [comment]
@lingutla123 thanks for sharing the log the specific error is here 

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/75bab927-95ec-49c2-9d7c-1c7d86434a23)

You'll need to update the permissions for your AzDO project Build Service. Double check the permissions specified in the setup here https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#update-permissions-for-the-project-build-service

**Comment by lingutla123** [comment]
Now i am getting "Unauthorized error in PR  when i Deploy the solution.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/34fe190c-99d0-4113-9bfa-9222e0474b83)

**Comment by mikefactorial** [comment]
@lingutla123 looks like you're in a GCC tenant based on the error message. While our intent is to support GCC as well as public cloud we currently don't validate our releases in GCC. We have heard similar feedback from other GCC users on this particular issue. For now you can disable the solution checker using the DisableSolutionChecker variable as a work around. https://github.com/microsoft/coe-starter-kit/issues/5193#issuecomment-1497827796

**Comment by mikefactorial** [comment]
@lingutla123 since this thread is no longer on topic with the original question / issue. I'm closing it out for now. Feel free to open a new issue if you run into additional problems.

**Comment by lingutla123** [comment]
Thank you very mush. You guys are amazing.
