### ISSUE TITLE
[CoE Starter Kit - QUESTION] New App Plan Classification Type - Extended

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#5511]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We were auditing the Power Apps in our tenant using Power Platform Admin View and we saw a new App Plan Classificiation Type.
Usually it's either Standard or Premium but now we are seeing out of thousands of apps we have 3 Power Apps with a classification type of **Extended**.

Can you please let us know the definition of an App with a Plan Classification Type of **Extended**?

![1](https://github.com/microsoft/coe-starter-kit/assets/119695189/6e086986-2ae5-4ecd-b5f5-6e9a2944ae6d)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
This is just what we get from the product - here's the documentation on app plan classification:
https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/license-designation
