### ISSUE TITLE
[CoE Starter Kit - QUESTION] Regarding non-makers showing in Makers table

### ISSUE THREAD

**Issue by krhoadesnh** [microsoft/coe-starter-kit#5513]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are trying to clean up our Makers table before starting conversations without community about the CoE.  In looking at the Makers table, we see that close to half of the entries are users who have a "0" across the board in all "Number of ....." columns.   They are enabled users & not orphaned.  Why are they in the Makers table?   What would happen if we remove them from the table?

Thank you!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I'm not sure how they got added, but you can remove them. We dont remove people from the Maker Group today when they are removed so nothing will happen. If you were wrong and they did own something, then they would get added back in to the Maker table when their thing gets touched again (ex if they update it)

**Comment by manuelap-msft** [comment]
No further action required. Thanks for using the CoE kit, and please let us know if you have any more questions!
