### ISSUE TITLE
[CoE Starter Kit - Feature]: Find SharePoint list integrated forms

### ISSUE THREAD

**Issue by lindquiswi** [microsoft/coe-starter-kit#5514]
### Is your feature request related to a problem? Please describe.

Need the ability to discover PowerApps forms that are integrated in SharePoint Lists. 

https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/customize-list-form

### Describe the solution you'd like

With deployment of the COE, there are several PowerApp dashboards and PowerBI dashboards to help find PowerApps in the environment. I need a dashboard/report that shows the SharePoint Lists that have custom forms attached to the list/library.

### Describe alternatives you've considered

Currently using PowerShell: https://github.com/petepuu/PowerShell/blob/main/PowerPlatform/Get-CanvasAppsWithSPConnection.ps1

Problem with PowerShell is that it takes hours to run in large environments. 

### Additional context?

Must accommodate COE deployment using Data Lake for the following environment size:

102 developer environment + 56 production environment + 6 sandbox environment +1 trial environment + 788 MS Teams environment.

**Comment by manuelap-msft** [comment]
Does this existing report meet your requirements? https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-monitor#sharepoint-integration 

It's called SharePoint integration in the existing Power BI report.

You can also use the Power Platform Admin View (model driven app) > PowerApps Apps and change the view to "SharePoint"
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/59889e88-a9bc-4afc-99e4-769d2b855b2c)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
