### ISSUE TITLE
[CoE Starter Kit - QUESTION] No Compliance parameter/environment variables for Flows

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5517]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

while working with kit , could see we don't have any compliance parameters for flows and I understood that we are not saying that flows are compliant or not. but if we will go to the compliance center, we have 'flow' in the left panel and also allows to provide support details for the flows. 
<img width="1153" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/1acabc2d-6783-4670-9a0a-e5dcc54dd17e">

would like to understand here when we are not even making the flows non-compliant on any basis, then when the Maker will be prompted to provide business justification for them?  

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

February

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
There is no automatic flagging of flows for compliance, but with all these objects you can manually request they provide the details. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5074b78a-c110-4f4f-842a-2b59b1616a04)

Hope that helps

**Comment by manuelap-msft** [comment]
No further action required. Thanks for using the CoE kit, and please let us know if you have any more questions!
