### ISSUE TITLE
[CoE Starter Kit -is there a way to remove the unwanted files or other stuff from COE

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#5521]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I wanted to check like is there any way to clean up the unused or unwanted data from the COE as I see that my COE environment where I have installed is consuming allot of my tenant capacity space. So wanted to know if there is any way to clean up the unused data or files or flows or any other stuff if possible.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

NA

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Here are some steps for bulk deleting data from the Audit Log table, which may take up a lot of space if you've had the audit log solution running for a while:
https://github.com/microsoft/coe-starter-kit/issues/5426#issuecomment-1539735147

If you're not sure what takes up the most space, check here:
https://github.com/microsoft/coe-starter-kit/issues/5426#issuecomment-1534332523

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
