### ISSUE TITLE
CoE Core Tracking Flow Runs Question

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#5523]
I am implementing CoE and been trying to figure out if CoE can get and store flow runs in Dataverse. Right now Im tracking this manually by creating separate flows but if there is something integrated to CoE I would prefer that.

Thank you.

**Comment by Jenefer-Monroe** [comment]
Hello. The CoE does have the ability to track Desktop Flow runs. But we have a bunch of limitations currently. 
Please see these examples:
- https://learn.microsoft.com/power-platform/guidance/coe/limitations#large-desktop-flows
- https://learn.microsoft.com/power-platform/guidance/coe/limitations#desktop-flow-runs

For people with a dedicated desire to track Desktop Flows it is, at this time, recommended to use the Automation CoE
https://learn.microsoft.com/power-automate/guidance/automation-kit/overview/introduction

Hope that helps.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
