### ISSUE TITLE
[CoE Starter Kit - QUESTION] all COE solutions mysteriously disappeared in my testing environment

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5524]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

On May 10, I created a brand new testing environment, and setup the core/inventory components.
On May 11, I set up the governance components, and set up the inactivity processes.

I used the Setup Wizard whenever it was possible.

On May 12, at 8:30am EST, when I began working, I went to make.powerapps.com and noticed all the COE solutions are missing.
and all that is left is shown in the attached screenshot.

I did the usual stuff, clear browser cache, InPrivate browsing mode.
I tried looking in the "Power Platform Admin View" of my production COE environment, and there aren't any flows for the COE test environment.
I tried restoring my May 11 5pm backup, and the solutions are still missing after restoring.
I tried restoring my May 11 8am backup, and the solution are also missing after restoring.

Thankfully, my Production COE environment was not affected at all, and I can just create another COE test environment, but I'm curious if that has ever happened to anyone before, and what could have caused it to happen? 

Maybe it was because I did the entire installation using InPrivate mode in MS Edge?

![missing-solutions-test-envrionment](https://github.com/microsoft/coe-starter-kit/assets/128085471/0f977701-b666-429e-93b0-e2f012f75c72)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. It looks like the creator kit was removed as well. I'm really not sure as I've not seen this before. Perhaps someone reset the environments?

**Comment by firefox-edge123** [comment]
I'm still not sure what exactly happened. I decided to just delete the Test environment and create a brand new Test environment and install the May 2023 release. But thank you for all your help.
