### ISSUE TITLE
[CoE Starter Kit - QUESTION - Editing available on environment requests created by Maker Environment Request App

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5529]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is it sensible to create a Edit button for the Environment requests still in Pending state?
In case if the maker wants to go back and make some changes to requests created by him.

Thanks! 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April

### What method are you using to get inventory and telemetry?

Cloud flows

AB#650

**Comment by Jenefer-Monroe** [comment]
Thank you for the suggestion, added to backlog.

**Comment by PPMini** [comment]
[like]  Mini Kaushik reacted to your message:
________________________________
