### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Platform Admin View sharing

### ISSUE THREAD

**Issue by accvik** [microsoft/coe-starter-kit#5530]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

According to the documentation, the "Power Platform Admin View" App cannot be shared if a user is not Global or Power Platform Admin. 
Is it not possible to share with a user without that role in Azure AD? 

If not, can the app be customized (where is it technically enforced?) to be sharable with other users? Or what in the app is requiring the AD role?

https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components#set-app-permissions

Thanks in advance.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by accvik** [comment]
Hi @manuelap-msft,

Thank you for your swift response, that sounds great and will solve our gap. 

However, we cannot get it working. I added a user to the Power Platform Admin SR and then tried sharing the play URL. But I get the following error: 
![image](https://github.com/microsoft/coe-starter-kit/assets/106146275/d8cb6d93-295a-4236-b82a-ca4d59e7f757)
![image](https://github.com/microsoft/coe-starter-kit/assets/106146275/e918746a-08cf-4fb6-8e0d-9ab450f0da3a)

Any suggestions? Or what are we missing?

**Comment by Jenefer-Monroe** [comment]
If first you add the Custom role to the App itself
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d32ce117-8006-4686-9fcd-29df19de8d2a)

And then add the user to the role
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2873222a-3262-42ee-aad4-170edf5d930b)

Then that user should have access.

**Comment by accvik** [comment]
Hi,

That seemed to do the trick, thank you so much!

**Comment by Jenefer-Monroe** [comment]
Wonderful, thanks for letting us know!
