### ISSUE TITLE
[ALM Accelerator - QUESTION] Deployment

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5537]
### What is your question?

Hi,

After deployment to validation environment, the Test deployment pipeline asks for deploy 'permission'. If approved, it is immediately deploying to Test environment. Is this expected behavior? How long this option will be available to deploy to Test environment. Generally, we deploy to Test only after QA testers validation in Validation environment ( which can take days at minimum).

In the attached screen shot, there is no easy way to identify which environments have the deployment completed? Prior there use to be visual identifier for completed environment. Is there a way to easily identify ( which I am not aware)?

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/7436aff1-68b2-4ac7-8ecd-cf07fc8466e0)
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/4759efe0-d623-4958-ae26-cf79de45e5e4)

Thank you!

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 19th 2023

**Comment by mikefactorial** [comment]
Depending on what the pipeline is asking permission to you can ensure that the pipelines don't ask for permission by updating the permissions in the project. Specifically, ensure that the pipelines have access to the repositories it's using 
#10 under this topic https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#update-permissions-for-the-project-build-service

and that your service connections are shared with all pipelines.

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/94c2fe71-2413-4d21-90fd-83267f9ed48b)
