### ISSUE TITLE
[CoE Starter Kit - QUESTION] Recommendations about Data Lake Export integration in non-prod Starter Kit environment

### ISSUE THREAD

**Issue by miroslav-harlas** [microsoft/coe-starter-kit#5543]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I would like to extend my question about how to prepare DEV/TEST environment from the past, which is logged under #4866. Currently, we are using the approach of setting "is All Environments Inventory" to "No" in all non-prod Starter Kit environments nowadays.

However, we are starting to think about integration of CoE Starter Kit with Azure Data Lake Export (BYODL). As far as we have DEV + UAT + PROD Starter Kit environments and we are developing some custom solutions on top of that or next to that, we are thinking if we can apply the same Starter Kit setup to all three environments with Data Lake data integrated.

Our key question/concern is if we enable BYODL in PROD starter kit only and not in DEV and UAT, would be all our customizations developed on top of Core solution in DEV and UAT compatible with PROD Starter Kit setup? 

If not than another questions could be:
Is BYODL approach compatible with "is All Environments Inventory" to "No" ?
Is there any recommendation about how to setup Data Lake Export integration for non-prod CoE starter Kit implementations where we do not want to see and use inventory and usage data from all environments in tenant?

Thank you very much in advance for any comments about this topic.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Here you go, hope the below helps

### Our key question/concern is if we enable BYODL in PROD starter kit only and not in DEV and UAT, would be all our customizations developed on top of Core solution in DEV and UAT compatible with PROD Starter Kit setup?

This really depends on the customization so I can't answer generally. I think most people customize in areas that do not involve the inventory gathering, ex customizing Inactivity Processes or Compliance. If that was the case then how the data got into the inventory would not matter. 

### Is BYODL approach compatible with "is All Environments Inventory" to "No" ? Is there any recommendation about how to setup Data Lake Export integration for non-prod CoE starter Kit implementations where we do not want to see and use inventory and usage data from all environments in tenant?

No we have not done the work to enable this today although it is on the backlog.

**Comment by miroslav-harlas** [comment]
Thank you for your answers. It is clear.
