### ISSUE TITLE
Power BI report refresh keeps failing due to "the last refresh attempt failed because of an internal service error"

### ISSUE THREAD

**Issue by Dineshb2w1985** [microsoft/coe-starter-kit#5544]
Power BI report refresh keeps failing due to "the last refresh attempt failed because of an internal service error"

**Comment by Jenefer-Monroe** [comment]
It sounds from my searching like this is an intermittent product issue with Power BI. If its persistent you may need to create a support ticket for Power BI team

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
