### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Process Wizard can not be closed

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5547]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

On below screen of compliance center setup wizard the close icon not working:
<img width="1144" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/b20a71a8-50d8-4786-8779-f03af3c8d150">

### Expected Behavior

The window should get closed after clicking the 'X' button 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April

### What app or flow are you having the issue with?

Governance solution

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

<img width="1144" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/98745141-a003-4e43-8548-c3872f9de228">

**Comment by manuelap-msft** [comment]
Hello,

that's expected - if you do not meet the pre-requisites you can't close the pre-requisite window. You'll have to select "More features" on the side to back out of this and select another wizard, or close the app altogether. 

Or are you saying that you do meet the prerequisites and are still seeing the pop up?

Manuela

**Comment by PPMini** [comment]
Hi Manuela, thanks for responding, yeah I got it. No, it's not the other case. Closing this out
