### ISSUE TITLE
[CoE Starter Kit - QUESTION]  import the creator kit

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#5551]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

It was stated in the documentation that a global admin is required to import the creator kit.

However, we would like to give only the PowerPlatform admin to the account that imports the CoE Starter Kit.
Is it possible to import the Creator Kit using an account with global administrator privileges, and then import the CoE Starter Kit using another account with PowerPlatform administrator privileges?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I do not believe global admin is required to install cretor kit. I believe you just need to be sys admin on the environment, not global admin in the tenant.

**Comment by egym07** [comment]
Oh, I'm sorry. I misunderstood.
I needed system administrator privileges in the security role. .
Thank you very much.

**Comment by Jenefer-Monroe** [comment]
You are quite welcome, and no worries the security model in Power Platform is complex (and awesome).
