### ISSUE TITLE
[ALM Accelerator - BUG]: An unexpected error during import Managed Solution (Update or Upgrade)

### ISSUE THREAD

**Issue by R4isin** [microsoft/coe-starter-kit#5552]
### Describe the issue

During the import of the solution via the pipeline "deploy-test-NameofSolution" an error is triggered in the step "Import Managed Solution as Update" (Remark : the same error is triggered if we tried to use "Import Managed Solution as Upgrade")

This error occurs for solutions/applications that have already been successfully imported via the ALM Accelerator in the past.
At first sight, nothing has changed in our settings.

Below 2 example of this error:

**Solution A**
See attachment
[Error - Solution A.txt](https://github.com/microsoft/coe-starter-kit/files/11496409/Error.-.Solution.A.txt)

**Solution B**
See attachment
[Error - Solution B.txt](https://github.com/microsoft/coe-starter-kit/files/11496408/Error.-.Solution.B.txt)

Is this related to a timeout? A performance problem with the target environment? Is it possible to get more details about these errors ? If yes, could you help me please ?

Kr,

### Expected Behavior

Finish the step successfully like before:
[ExpectedBehavior.txt](https://github.com/microsoft/coe-starter-kit/files/11496393/ExpectedBehavior.txt)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230217.1

### Steps To Reproduce

1. Go to the env. where "ALM Accelerator for Power Platform" is installed
2. Go to the Canvas App "ALM Accelerator for Power Platform"
3. Setup the Deployment Configuration
4. Commit the solution (success)
5. Merge the branch in DevOps (NewCustomization --> SolutionA")
6. Deploy the solution in TST (use the branch named "SolutionA")

### Anything else?

It's still possible to import the solution manually (without error)

**Comment by mikefactorial** [comment]
@R4isin you may be able to get more information about the failed solution import from the Solution History in the maker portal. 
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/b98ca8fc-4fcc-49ff-81ca-378cda611eb9)

**Comment by R4isin** [comment]
Oh, I guess I was tired of not checking that first. Typically, it's my first instinct... I apologize for the inconvenience, it was an error related to a secret environment variable. My user connected to the ALM didn't have access to retrieve the secret. Sorry again, and thanks for reminding me of this tip!
