### ISSUE TITLE
[CoE Starter Kit - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by rjpiazza** [microsoft/coe-starter-kit#5557]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

A way to see what Power platform licenses that have been assigned for apps..., flows for users...
Thank you

**Comment by Jenefer-Monroe** [comment]
Hello thank you for posting. We do have this on our feature backlog here: https://github.com/microsoft/coe-starter-kit/issues/431

Thank you for using CoE!
