### ISSUE TITLE
[CoE Starter Kit - Feature]: Remove user from Sys Admin role

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5558]
### Is your feature request related to a problem? Please describe.

Now that we report on who is a sys admin across environments, the next step is ability to remove one user / users in bulk from the role. 

Scenarios to include:
- Filter by user > remove user from sys admin access across all environments
- Filter by environment > select certain users and remove them from sys admin access
- Select individual user in individual environment > remove sys admin access

### Describe the solution you'd like

See above

### Additional context?

Will work for Directly granted sys admin access only, not groups. For v2 we can explore linking to Azure portal to remove user from group 

AB#930

**Comment by Jenefer-Monroe** [comment]
Created the flow to do this. Must be a flow as it requires we go off to random envts and do the unrelate.


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cafff9b7-78ad-40f0-be2f-7f8f213f4763)

**Comment by Jenefer-Monroe** [comment]
Need to surface in UX yet, but will be able to do that for March.

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5cd65b83-550e-489a-8121-da9212985f26)

**Comment by tocri** [comment]
Wow...it's such a great addition. i'm looking forward to testing this functionnality tomorrow
