### ISSUE TITLE
[CoE Starter Kit - QUESTION] Microsoft Teams Governance exemption from setup wizard

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5571]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is Microsoft Teams Governance exemption from setup wizard is any different from exemption from inactivity/compliance/quarantine settings we have in Power Platform Admin View App.

If we will excuse any teams environment from Teams governance, what does that mean? 

Should we have a setting in Power Platform Admin view for this as well as we have for other processes like compliance/inactivity etc.

<img width="827" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/1ea28dbf-7fbe-48b9-bc70-d37da89033ae">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April

### What app or flow are you having the issue with?

Governance solution

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. The way we do the Teams work is that it occurs right when the Team envt gets inventoried so there isn't opportunity to exempt before we send off the justification request. Hope that helps

**Comment by Jenefer-Monroe** [comment]
Sorry I did not follow that question. Can you try again?

**Comment by PPMini** [comment]
Apologies! I believe I did not understand your previous point correctly, are we saying there that exemption of a Teams environment can not happen unless business justification is done for that environment?

**Comment by Jenefer-Monroe** [comment]
I'm saying that there is no concept of exempting a teams envt from this process. Nor can there be, because the process starts as soon as the envt is inventoried. 
You can choose to approve envts pre-emptively, before they user provides justification here though:

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/52fbe78c-6a70-4f6a-8ab3-1aab84e98936)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
