### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Platform Admin View

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5572]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I Setup COE test Environment. Not able to see the data except Environments and Connectors in "Power Apps Admin View" app. I turned on all flows.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/c85b34e0-38bf-4ca7-994e-dcdfcc87be6c)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 19th 2023

### What app or flow are you having the issue with?

Power App Admin View

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
1. Browse to the Admin Command Center > Environment Variables > What is the value for this item? 
![image](https://user-images.githubusercontent.com/89584709/230621685-2f293271-b215-4f91-8234-0f39c8f638e9.png)

2. Browse to the Admin Command Center > CoE Flows Page > Inventory. When did this flow last run and did it pass? Click Flow details to browse to it. 
![image](https://user-images.githubusercontent.com/89584709/230622288-a392e38b-cabc-4cf9-849d-29491a22946b.png)

3. Open the most recent run. Does it make it down to this call? If so how many environments are returned? You can see this by popping it into a json parser.
![image](https://user-images.githubusercontent.com/89584709/230622587-e17a3ad2-e1d2-4d58-8a0c-255aa469359d.png)

**Comment by lingutla123** [comment]
1. ![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/53e38cd1-99d9-4be1-97dd-6652631accf1)

2. I don't see the Admin| Sync Template V3(Driver) (After May release  Admin| Sync Template V3). But this flow turned on and ran successfully.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/e0fd0a19-1945-4510-8924-433fa0b648ba)

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/7c1cf201-336f-47c2-afb5-062d351927b6)

**Comment by Jenefer-Monroe** [comment]
Did you use the setup wizard to install / upgrade?

**Comment by lingutla123** [comment]
Yes.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/0ea2ff59-802d-43f8-be4e-0c508b610a7e)

**Comment by Jenefer-Monroe** [comment]
Oh you're right, I'll need to update that FAQ. The flow is now called **_Admin| Sync Template V3(Driver)_**

**Comment by Jenefer-Monroe** [comment]
Was this test environment a restored environment?

**Comment by Jenefer-Monroe** [comment]
I ask because restored environments go into somethign called **Administration mode**, and flow triggers on Dataverse do not work when in **Administration mode** so you need to toggle that off if you use a restored environment for CoE
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/27dc6281-0e50-4afb-a47e-6ad19cead098)

**Comment by lingutla123** [comment]
I didn't restored the environment.  I am doing form scratch. I installed Core components. Now i am  not seeing Set Up Flows in 
Center Of Excellence Setup Wizard.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/e0329810-5e0c-4699-8155-82fafef15945)

**Comment by Jenefer-Monroe** [comment]
Hello. That screen does sometimes take a while to update. If you click refresh in that UX it will show you the status of the flows. 
Are you trying setup again from scratch?

**Comment by lingutla123** [comment]
Yes. Anyway i turned on manually all flows and Admin| Sync Template V3(Driver). And now i can see the data in Power Apps Admin View App except Audit Logs.

**Comment by Jenefer-Monroe** [comment]
Wonderful. Audit logs are a seperate setup. We just shipped a simpler system for that and the documentation for it is not yet released. Here is a write up you can use in the meantime if you would like: https://github.com/microsoft/coe-starter-kit/issues/5561#issuecomment-1551916651

**Comment by lingutla123** [comment]
Hi Jenefer,
I followed this document https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog to setup Audit Logs.
But i am still getting flow error. 

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/83ca92c1-e0ef-42b2-9be9-6ba9ce5543a7)
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/e77af1c7-e86a-4fc0-ae34-57a6ebf4deab)

**Comment by Jenefer-Monroe** [comment]
Hello. The documentation you point to here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
is old and refers to the way we collected audit logs in the past and includes flows from another solution. The docs team has not yet published the documentation for this new release. 

To use the flow you show above, in the Core solution, you need to use the instructions in the link I provided above:  https://github.com/microsoft/coe-starter-kit/issues/5561#issuecomment-1551916651

In particular the app registration has changed
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ec7ae8a6-edd8-4d2a-a5ca-87f52d763fbd)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
