### ISSUE TITLE
[ALM Accelerator - DOCS] Custom Connector Setup

### ISSUE THREAD

**Issue by JMM-CDS** [microsoft/coe-starter-kit#5578]
### What is your question?

I just updated my version and I can't succed to set up the security of the Custom Connector.
I get a 203 error but I can't find the good parameter for the Resource URL.

Thanks for helping.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230516.1

**Comment by mikefactorial** [comment]
@JMM-CDS thanks for for the question the Resource URL is the Azure DevOps Client ID. In the public cloud that ID is usually 499b84ac-1321-427f-aa17-267ca6975798 but can be found in the Azure Portal under the App Registration API Permissions. Will  update the docs to call this out more clearly.

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/42ccae8f-48ad-4763-bb81-cf51276f7d65)

**Comment by mikefactorial** [comment]
Can also be found under Enterprise Applications in Azure Active Directory
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/e3fe9498-97bf-42a5-bc6e-e1eb9ad666e9)
