### ISSUE TITLE
[CoE Starter Kit - QUESTION] - [Child] Admin | Sync Logs Error

### ISSUE THREAD

**Issue by dksamo1986** [microsoft/coe-starter-kit#5579]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I have seen several times, that we get an issue that says: "A record with matching key values already exists" (see attached Child Admin - Sync Logs Error
![Child Admin - Sync Logs Error](https://github.com/microsoft/coe-starter-kit/assets/122786332/08a0b420-e0d5-4b1e-b902-d9cba71bda10)
)

When I look into the Admin_flow or Admin_app tables, I am finding that there are rows that have empty values in many of the columns. (see attached two images showing both tables with many columns empty). 
![2023-05-19 08_00_36-Window](https://github.com/microsoft/coe-starter-kit/assets/122786332/c73f4cd9-8483-45db-ad20-05aab7d06e35)
![2023-05-19 07_58_59-Window](https://github.com/microsoft/coe-starter-kit/assets/122786332/0103eba4-0184-40d7-a6b2-da04763bbf2b)

Not sure what to do to resolve this issue? 

Any recommendations, would be appreciated. 

Best regards,

Sabri

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Child Admin | Sync Logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by dksamo1986** [comment]
Sorry, I didn't see that one of the columns was not showing fully. 

![CoE Components Installed](https://github.com/microsoft/coe-starter-kit/assets/122786332/98c2227b-7ed2-4e62-94f8-d660732d7207)

**Comment by Jenefer-Monroe** [comment]
Thank you, lets focus on your blank data first. 
Can you plesase confirm, do you have the **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_** flow turned on and running?

**Comment by dksamo1986** [comment]
Hi Jenefer,

No, it looks like that flow is turned off and has never run. 

Should I turn it on? 

Best regards,

Sabri

**Comment by dksamo1986** [comment]
Hi Jenefer,

After having run the flow (CLEANUP - Admin | Sync Template v3 (Delete Bad Data)), all the rows without a flow or app environment have been removed. 

Now, we just have the rows that have an environment, but the remaining fields are almost all empty (see attached).

Any suggestions on what process should be in place to remove them or what should be done with them? 

![apps](https://github.com/microsoft/coe-starter-kit/assets/122786332/2a2657b9-ef0d-4e77-93b6-292fdca176de)
![flow](https://github.com/microsoft/coe-starter-kit/assets/122786332/5d8a499c-d692-4c5a-812b-54d346d58240)

**Comment by Jenefer-Monroe** [comment]
Sorry for the delay. In the May release we added a flag that allows you explicitly ask that an app or flow be inventoried next run  regardless of its current data set (although it must have its environment filled which now all yours do) 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/09780219-270d-434c-acaa-3559a7e30a7d)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by dksamo1986** [comment]
Okay - thank you for that Jenefer. 

Best regards,

Sabri
