### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 (custom connectors) and Sync Template v3 (Connectors) failing invalid response from API 'powerappsforappmakers'

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#5580]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Today I have started to receive an error from the flow runs across nearly all environments for the Sync Template v3 (custom connectors) flow. The issue happens at the 'Get Custom Connectors and store them in CoE CDS Entity' scope at the 'Get Connectors' action. The error below is received:

The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/94/properties/connectionParameters/username/uiDefinition/constraints/clearText' to be of type 'Boolean' but is of type 'String'.'

![image](https://github.com/microsoft/coe-starter-kit/assets/117096415/3497cba3-d9f5-42f3-95e4-375dac79a5e3)

The flow has only succeeded for 7 environments out of 55. 

Please let me know if there is any other information that might be useful

### Expected Behavior

Get connectors for the environment within the filter query

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Run Admin | Sync Template v3 (Custom Connectors)
2. Error occurs at Get Connectors stage of the 'Get Custom Connectors and store them in CoE CDS Entity' scope

### Anything else?

Not sure if this helps or is related, the only change I made yesterday was to change the environment variables below, due to emails regarding missing logs and require smaller chunks

TimeSegments-CountLimit: 1500
TimeInterval-Unit - Minute
TimeInterval-Interval - 1

**Comment by Jenefer-Monroe** [comment]
Can you please let me know what region and type of the failing envts? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

**Comment by G1982C** [comment]
Region - All of the ones failing are 'asia', the 7 that did run successfully were in unitedstates, europe and united kingdom. 

Type - those failing are of type developer, sandbox, production, Teams and default. Those successful are Teams, Production and Sanbox. 

so it would appear region specific as all flows in the asia region are failing

**Comment by Jenefer-Monroe** [comment]
OK I repro for Aisa region as well. Thank you for debugging. Let's get you a repro outside of the kit, and then you can contact product support. We will also post an internal ticket. 

Please collect an envt id for an Asia region envt, and a US one
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7d098714-9dce-47f4-8a47-a28020c32f43)

Create a flow and have it call the **_Get Connectors_** action of the **_Power Apps for Makers_** twice. First for your US region and then for your Asia. This way you can show support the format is correct with the passing US one. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b4ae5539-fc67-4a0c-811e-73e31c776790)

Run it and you will see US passing but not Asia.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/59997063-08ea-4d6b-81d1-a2b6a13a687c)

Bring this flow to product support and I'll bring it internal

**Comment by G1982C** [comment]
Thanks Jenefer. I have created the test flow for the Get Connections in both Asia and US to demonstrate the Asia one failing and attached that as an image. I have raised a support ticket with the product team.

**Comment by G1982C** [comment]
Just a quick update to say that I did a screen share with the team assigned the ticket, they were also able to replicate and they are now raising internally with the product team. Thanks

**Comment by VasilinaMaroz** [comment]
Hello @Jenefer-Monroe !
I faced the same issue. Should I raise it as a ticket as well?

**Comment by Jenefer-Monroe** [comment]
Yes please. Bring the same flow, the repro outside of the kit, with you, to make the work with the support team faster.

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid this is a product bug and there isn't anything I can do to fix it. Please contact support with the information shown above to help the product team get this fixed up for you.

**Comment by OctavianSfetcu** [comment]
Hi
I got the same error on an environment that I updated to the may version, but also on another environment that was not updated in the last 6 months (different tenants). There is any news about this?
Thanks

**Comment by FQ365Microsoft** [comment]
Same issue and we have opened a support case. (fingers crossed)

**Comment by JMG74** [comment]
Same issue for my environments in regions Europe and Switzerland. I have opened a support-ticket at Microsoft.

**Comment by Mengting233** [comment]
Same issue here in region Europe Sweden.  It starts yesterday 2023-05-25 10:52PM.

**Comment by petepuu** [comment]
Yes same here with Admin | Sync Template V3 (Connectors) flow in 4.8 in EMEA and US envs failing in **Get Connectors** action with that error

The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/98/properties/connectionParameters/username/uiDefinition/constraints/clearText' to be of type 'Boolean' but is of type 'String'.'

<img width="452" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/3dba0e6d-b2ab-4b24-80bb-b72b50efa3d8">


Setup Wizard lets continue even the flow failed after few seconds it was running even the status is not successfully completed

<img width="341" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/cc01b6cf-b45d-4867-8eb5-5eed6348c215">

**Comment by petepuu** [comment]
I think we have a bigger issue related to this especially in new installations. At least the SYNC HELPER - Apps is failing as there is no connectors populated in the connectors table meaning that app info is not saved

<img width="445" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/5f44c2c9-659a-414b-9599-7c2e1de31a14">

**Comment by dksamo1986** [comment]
Same issue over here. Just started today.

**Comment by PPMini** [comment]
Just to confirm we are in UK region and here as well failing : 
<img width="534" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/8fd79f85-63d1-40f0-87d1-66969f883d90">

**Comment by G1982C** [comment]
I can also now confirm that this issue is impacting other regions now, it is not just Asia. 

I reported this 7 days ago with a ticket to Microsoft, so far I have only had two updates, both of those were to say it was with their product team. 

This is probably equally as frustrating for the CoE team as it is us.

**Comment by Jenefer-Monroe** [comment]
@petepuu Manuela is adding you to the internal thread we have going for this. Appreciate your help in pressing.

**Comment by manuelap-msft** [comment]
I've raised this internally with our Engineering team again, we did raise it initially when we only saw it in our preview environment. Will update here once I learn more.

**Comment by luff99** [comment]
Another one for the list.  UK region and just started today.  Running the March release.  Let me know if you want more info.

**Comment by peteredc** [comment]
You can add Canada to the list as well.  Any idea of the ETA for this to be fixed?  The CoE kit has to be the biggest consumer of this connector by a long shot.  No word on a sprint date at least?

With respect to raising a ticket, we've got a few options.  What's the most effective way to do it?  Through Admin, account rep...?

![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/73665a6d-4b47-46f4-adc1-2edb4888d537)

**Comment by jax-coe-admin** [comment]
I am having this same issue with version 4.8.  All my environments are "United States"

![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/6e729b71-a443-4d8b-8092-72b1ddd4a2b8)

**Comment by Natashamg** [comment]
> A fix has been released by the product team. We should all be unblocked now.

Hi
Does the May hotfix fix this issue or is there something else I need to do?

**Comment by Jenefer-Monroe** [comment]
This is a product bug and was a product fix, it does not depend on what version of the kit you are using. The fix is pushed by the product release tooling.

**Comment by Jenefer-Monroe** [comment]
closing out now that this no longer repros with the product fix. Thanks community for pressing it to resolution.
