### ISSUE TITLE
[CoE Starter Kit - BUG] Error in app catalog launch

### ISSUE THREAD

**Issue by Siddhesh-S21** [microsoft/coe-starter-kit#5582]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Facing an Error message in Core Component App - App Catalog

### Expected Behavior

Error:
PowerAppsforAppMakers.GetConnector failed: 
The method 'GetConnector' has an invalid value for parameter 'connectorName'

Getting the above error on the Homescreen or on the Details screen for the app featuring in the App Catalog.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

App Catalog

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

![Capture](https://github.com/microsoft/coe-starter-kit/assets/134070821/f2b47f5a-75b5-4577-aa58-c03cc4d8e22b)

### Anything else?

Kindly loop in me as well as my colleague @pranjal.gupta@external.totalenergies.com for any email communications

**Comment by Jenefer-Monroe** [comment]
Hello. We do not us email to respond to these issues, we interact directly in GitHub so I cannot pull your colleague in to the conversation. 

I do not repro this, and it also looks like you are using the old deprecated App Catalog. 
This app will be removed soon, can you please try the new one? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d6666518-30e5-4d06-8901-4aa3044f2c8b)

**Comment by Siddhesh-S21** [comment]
Which upgrade of CoE Starter Kit will have this update of App mentioned in screenshot as the last upgrade we did for CoE Starter Kit was of December 2023

**Comment by Jenefer-Monroe** [comment]
I'm not sure which version we shipped the new Model Driven Apps with. I think it may have been Feb? We did just release the May version though so that would be the recommended version to use now.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
