### ISSUE TITLE
[CoE Starter Kit - I have  a doubt regarding the environment variables

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#5583]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I started installing the COE of the new features, but unable to find the environment variables it's asking. Can you please help me providing the documents or details so that it helps me to find them. 

I tried for MS documents but couldn't find them.

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/0255e9e0-2371-4b1f-bb1a-2ed4392bdc00)

Thanks

### What solution are you experiencing the issue with?

None

### What solution version are you using?

NA

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Documentation is a few days behind, we wrote up a how to here while you wait for those to ship
https://github.com/microsoft/coe-starter-kit/issues/5561#issuecomment-1551916651

Thanks for using CoE
