### ISSUE TITLE
[CoE Starter Kit - BUG] Nurture - sort order on maker assessment app not working for new categories 

### ISSUE THREAD

**Issue by lrarbin** [microsoft/coe-starter-kit#5584]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I've configured an additional category under 'Assessment Categories', configured the 'Sort Order' in 'Nurture apps - Admin', but the sort order is ignored in the 'Nurture apps - Maker' app.

### Expected Behavior

That the 'Nurture apps - Maker' app categories reflect the sort order defined in 'Nurture apps - Admin.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.6

### What app or flow are you having the issue with?

Nurture apps - Maker / Nurture apps - Admin

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Add a 'Assessment Categories', and configure the 'Sort Order' in 'Nurture apps - Admin'.
2. Save the new item.
3. Open the 'Nurture apps - Maker' app.

### Anything else?

See example 'Company Info'

![2023-05-19 15_31_00-Window](https://github.com/microsoft/coe-starter-kit/assets/8376969/9a7b3d38-0669-4e95-a457-1cad4e288a53)
![2023-05-19 15_31_10-Window](https://github.com/microsoft/coe-starter-kit/assets/8376969/16f5933b-95e3-4f58-9b89-992fd9a2bf97)

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. Putting on the papercut backlog

**Comment by manuelap-msft** [comment]
Fixed by adding Sort Order to the collection where we pull this information from

![Image](https://github.com/microsoft/coe-starter-kit/assets/55705669/36038ebd-16eb-4734-9e77-a418d70473a2)

Local fixed ready for September release.
