### ISSUE TITLE
[CoE Starter Kit - BUG] Missing Admin | Sync Template v3

### ISSUE THREAD

**Issue by ReneTest998** [microsoft/coe-starter-kit#5585]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Missing Admin | Sync Template v3

![image](https://github.com/microsoft/coe-starter-kit/assets/131083902/ac6c016b-2eff-4ee4-9af7-a9009445ff4a)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
oh yes sorry, not sure how that got in the string. Fixed above too

**Comment by jenniferbrown12316** [comment]
I had this issue also, and it wont let me do the rest of the set up for the in the wizard until this flow is done.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
