### ISSUE TITLE
[CoE Starter Kit - BUG] Center of Excellence - Core Components You need to import the following into this environment to import the Center of Excellence - Core Components

### ISSUE THREAD

**Issue by Miled122** [microsoft/coe-starter-kit#5586]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: CenterofExcellenceCoreComponents. Some dependencies are missing. The missing dependencies are : <MissingDependencies><MissingDependency><Required type=\"300\" schemaName=\"cat_powercatcomponentlibrary_0be3a\" displayName=\"Power CAT Component Library\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_appcatalogpage_3315f\" displayName=\"App Catalog page\" /></MissingDependency><MissingDependency><Required type=\"300\" schemaName=\"cat_powercatcomponentlibrary_0be3a\" displayName=\"Power CAT Component Library\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterappspage_fdc96\" displayName=\"Command Center Apps page\" /></MissingDependency><MissingDependency><Required type=\"300\" schemaName=\"cat_powercatcomponentlibrary_0be3a\" displayName=\"Power CAT Component Library\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentercoedataflowspage_5ab77\" displayName=\"Command Center Coe Dataflows page\" /></MissingDependency><MissingDependency><Required type=\"300\" schemaName=\"cat_powercatcomponentlibrary_0be3a\" displayName=\"Power CAT Component Library\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentercoeflowspage_bd424\" displayName=\"Command Center CoE Flows page\" /></MissingDependency><MissingDependency><Required type=\"300\" schemaName=\"cat_powercatcomponentlibrary_0be3a\" displayName=\"Power CAT Component Library\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentercoesupportpage_06f77\" displayName=\"Command Center CoE Support page\" /></MissingDependency><MissingDependency><Required type=\"300\" schemaName=\"cat_powercatcomponentlibrary_0be3a\" displayName=\"Power CAT Component Library\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterenvironmentvariablespage_9d99b\" displayName=\"Command Center Environment Variables page\" /></MissingDependency><MissingDependency><Required type=\"300\" schemaName=\"cat_powercatcomponentlibrary_0be3a\" displayName=\"Power CAT Component Library\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentermessagecenterpage_6675d\" displayName=\"Command Center Message Center page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_appcatalogpage_3315f\" displayName=\"App Catalog page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterappspage_fdc96\" displayName=\"Command Center Apps page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentercoeflowspage_bd424\" displayName=\"Command Center CoE Flows page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentercoesupportpage_06f77\" displayName=\"Command Center CoE Support page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterenvironmentvariablespage_9d99b\" displayName=\"Command Center Environment Variables page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_deleteflowobject_eddf3\" displayName=\"PPAdmin View Delete Object - Flow\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_emailconfiguration_d275f\" displayName=\"Command Center Email Configuration page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_managepermissions_bfe40\" displayName=\"PPAdmin View Manage Permissions - Flows\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_managepermissionsapp_93136\" displayName=\"PPAdmin View Manage Permissions - Apps\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_othercoresetupwizardpage_1e3e9\" displayName=\"Other Core Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewdeleteobjectapp_01080\" displayName=\"PPAdmin View Delete Object - App\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewquarantineapp_be8d8\" displayName=\"PPAdmin View Quarantine App\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewstartflow_e0f91\" displayName=\"PPAdmin View Start Flow\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewstopflow_17a00\" displayName=\"PPAdmin View Stop Flow\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewunquarantineapp_93313\" displayName=\"PPAdmin View UnQuarantine App\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.CommandBar\" displayName=\"cat_PowerCAT.CommandBar\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"coe_environmentcreationrequest_bbe9d\" displayName=\"Maker - Environment Request\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_appcatalogpage_3315f\" displayName=\"App Catalog page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_cleanupfororphanedobjectssetupwizardcopy_51823\" displayName=\"Clean-up for orphaned objects setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterappspage_fdc96\" displayName=\"Command Center Apps page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentercoesupportpage_06f77\" displayName=\"Command Center CoE Support page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterlearnpage_b5b93\" displayName=\"Command Center Learn page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentermakerapps_92d6f\" displayName=\"Command Center Maker Apps\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterreleasenotespage_d825c\" displayName=\"Command Center Release Notes page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_compliancesetupwizardpage_d7b4b\" displayName=\"Compliance Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_environmentrequestsetupwizardpage_68a5b\" displayName=\"Environment Request Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_inactivityprocesssetupwizardpage_06a62\" displayName=\"Inactivity Process Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_initialsetuppage_d45cf\" displayName=\"Initial Setup page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_makerassessmentsetupwizardpage_f018f\" displayName=\"Maker Assessment setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_managepermissions_bfe40\" displayName=\"PPAdmin View Manage Permissions - Flows\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_managepermissionsapp_93136\" displayName=\"PPAdmin View Manage Permissions - Apps\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_morefeatures_6a3ed\" displayName=\"More features\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_othercoresetupwizardpage_1e3e9\" displayName=\"Other Core Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_pulsefeedbacksetupwizardpage_4bf3f\" displayName=\"Pulse feedback setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_teamsenvironmentgovernancesetupwizardpage_23f70\" displayName=\"Teams environment governance setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_templatecatalogwizardpage_4c407\" displayName=\"Template catalog wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_traininginadaysetupwizardpage_1cbde\" displayName=\"Training in a day setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Elevation\" displayName=\"cat_PowerCAT.Elevation\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_videohubsetupwizardpage_3a340\" displayName=\"Video hub setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_appcatalogpage_3315f\" displayName=\"App Catalog page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterblogpage_98b4c\" displayName=\"Command Center Blog page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentercoedataflowspage_5ab77\" displayName=\"Command Center Coe Dataflows page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentercoeflowspage_bd424\" displayName=\"Command Center CoE Flows page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterenvironmentvariablespage_9d99b\" displayName=\"Command Center Environment Variables page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentermessagecenterpage_6675d\" displayName=\"Command Center Message Center page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterreleasenotespage_d825c\" displayName=\"Command Center Release Notes page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_emailconfiguration_d275f\" displayName=\"Command Center Email Configuration page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_initialsetuppage_d45cf\" displayName=\"Initial Setup page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_managepermissions_bfe40\" displayName=\"PPAdmin View Manage Permissions - Flows\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_managepermissionsapp_93136\" displayName=\"PPAdmin View Manage Permissions - Apps\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.FluentDetailsList\" displayName=\"cat_PowerCAT.FluentDetailsList\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"coe_environmentcreationrequest_bbe9d\" displayName=\"Maker - Environment Request\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_appcatalogpage_3315f\" displayName=\"App Catalog page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_cleanupfororphanedobjectssetupwizardcopy_51823\" displayName=\"Clean-up for orphaned objects setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcenterappspage_fdc96\" displayName=\"Command Center Apps page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_commandcentermakerapps_92d6f\" displayName=\"Command Center Maker Apps\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_compliancesetupwizardpage_d7b4b\" displayName=\"Compliance Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_deleteflowobject_eddf3\" displayName=\"PPAdmin View Delete Object - Flow\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_emailappusers_a6c56\" displayName=\"PPAdmin View Email App Users\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_emailconfiguration_d275f\" displayName=\"Command Center Email Configuration page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_emailflowusers_9b94b\" displayName=\"PPAdmin View Email Flow Users\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_environmentrequestsetupwizardpage_68a5b\" displayName=\"Environment Request Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_inactivityprocesssetupwizardpage_06a62\" displayName=\"Inactivity Process Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_initialsetuppage_d45cf\" displayName=\"Initial Setup page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_makerassessmentsetupwizardpage_f018f\" displayName=\"Maker Assessment setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_managepermissions_bfe40\" displayName=\"PPAdmin View Manage Permissions - Flows\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_managepermissionsapp_93136\" displayName=\"PPAdmin View Manage Permissions - Apps\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_morefeatures_6a3ed\" displayName=\"More features\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_othercoresetupwizardpage_1e3e9\" displayName=\"Other Core Setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewaibuilderusers_45b58\" displayName=\"PPAdmin View Email AI Builder Users\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewbpfusers_84235\" displayName=\"PPAdmin View Email BPF Users\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewdeleteobjectapp_01080\" displayName=\"PPAdmin View Delete Object - App\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewemailbotusers_66e1a\" displayName=\"PPAdmin View Email Bot Users\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewemailchatbotusers_fc54a\" displayName=\"PPAdmin View Email Desktop Flow Users\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewemailcustomconnectorusers_4c340\" displayName=\"PPAdmin View Email Custom Connector Users\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewemailenvironmentusers_43ee2\" displayName=\"PPAdmin View Email Environment Users\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewemailmakers_bc561\" displayName=\"PPAdmin View Email Makers\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewemailpowerpagesusers_7133c\" displayName=\"PPAdmin View Email Power Pages Users\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewquarantineapp_be8d8\" displayName=\"PPAdmin View Quarantine App\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewsolutionsusers_e1c9b\" displayName=\"PPAdmin View Email Solutions Users\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewstartflow_e0f91\" displayName=\"PPAdmin View Start Flow\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewstopflow_17a00\" displayName=\"PPAdmin View Stop Flow\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_ppadminviewunquarantineapp_93313\" displayName=\"PPAdmin View UnQuarantine App\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" solution=\"CreatorKitCore (1.0.20221205.1)\" /><Dependent type=\"300\" schemaName=\"admin_pulsefeedbacksetupwizardpage_4bf3f\" displayName=\"Pulse feedback setup wizard page\" /></MissingDependency><MissingDependency><Required type=\"66\" schemaName=\"cat_PowerCAT.Icon\" displayName=\"cat_PowerCAT.Icon\" s

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.1

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponents

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. There are a few things to do before you can install the core components. 
First, please look through and prepare with the items in [Before setting up the CoE Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/setup) artivcle.
And then do the [Before you start](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#before-you-start) steps of the [Set up inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) page, which include installing the creator kit, which is what this error message is referencing. 
Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
