### ISSUE TITLE
[CoE Starter Kit - QUESTION] Change environment variables

### ISSUE THREAD

**Issue by egym07** [microsoft/coe-starter-kit#5589]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I think I used to be able to change environment variable settings in "Admin - Command Center", but if this is removed, where will I be able to change environment variables?
Is it only in the Set up wizard?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, you can still edit env vars in the Command Center. Please see this article for how to update them, including through that tool and through the product itself. 
https://learn.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables

Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
