### ISSUE TITLE
CoE Starter - Upgrade of Core Components fails

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#559]
I am currently running version 1.71.7 and applying version 2.1 using the upgrade option. The import of Core Components has failed with error message that there are dependencies. These dependencies are part of the managed solution  Center of Excellence - Governance Components and so are unable to be deleted. I have attached the error log.

**Comment by manuelap-msft** [comment]
Hello,

unfortunately, you are quite a few versions behind our current one. You may have to upgrade Governance and Nurture first, before updating Core.

Thank you
Manuela

**Comment by medicineshow** [comment]
Nurture installed OK but Governance has the error: There are missing dependencies. Install the following solutions before installing this one: "Active". Active is not a solution I can see in the unpacked file. Any thoughts?

**Comment by medicineshow** [comment]
I have successfully installed Core, Governance and Nurture. I now have a problem with upgrading Audit Logs solution. The current version is 1.3.2 and the upgrade version is 1.4. 
The upgrade fails with the error: Upgrading solution failed. Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365AuditCustomCoEConnection,. 
I try to delete the connector but the following error occurs:
The request failed with error: '{"error":{"code":"0x8004f01f","message":"The connector(de4da0c8-bd02-41df-b0da-bbe0290e8fb4) component cannot be deleted because it is referenced by 5 other components. For a list of referenced components, use the RetrieveDependenciesForDeleteRequest."}}

How can I Delete the Office 365 Management API custom connector?

**Comment by JeneferM-MSFT** [comment]
You do not want to delete that connector. 
Given the age of your old version, I think you are hitting an issue due to us moving the connector in the past. 
Please delete your version of the audit log solution, dont worry, the data wont be deleted as it is stored in Core. 
Then install a fresh version of Audit Logs. Be sure to follow the [install steps](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog) carefully
