### ISSUE TITLE
[CoE Starter Kit - BUG] DESKTOP FLOW ISSUE

### ISSUE THREAD

**Issue by VasilinaMaroz** [microsoft/coe-starter-kit#5590]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v3 (Desktop flows) fails on "List Desktop Flows" action for the Default environment with "BadGateway" error.
![MicrosoftTeams-image (58_1)](https://github.com/microsoft/coe-starter-kit/assets/116820870/11a70ed4-ef81-433a-8faa-9221cc26a54d)

### Expected Behavior

It should return the list of Power Automate Desktop flows from the environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1.Turn on Admin | Sync Template v3 (Desktop flows)
2.Admin | Sync Template v3 (Desktop flows) is automated flow and runs every day
3.When it's trying to get list of flows from the Default environment, it receives "BadGateway" error.

**Comment by Jenefer-Monroe** [comment]
Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role? Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)

**Comment by VasilinaMaroz** [comment]
Yes, I checked this and confirming that the account has the Power Platform Admin Role

**Comment by Jenefer-Monroe** [comment]
Sorry my FAQ was out of date, what I had needed you to check was if it has the role permanently assigned (v assigned by PIM for example)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/38cafc35-4d42-452a-b2ae-f305082f3f1c)

**Comment by VasilinaMaroz** [comment]
Do you have any updates on this?

**Comment by Jenefer-Monroe** [comment]
Hello, please note the CoE Starter Kit is an unsupported set of templates: https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support 

We do not have a support team that can help resolve issues, and support is provided on best endevaours without SLA via GitHub. We will look into your issue, but at the moment can not provide a timeline.

Thank you for your patience

**Comment by Jenefer-Monroe** [comment]
If you go into the trigger statement you will see the environment instance url. Can you browse to that as the identity running the flow? 
![image](https://user-images.githubusercontent.com/89584709/205936150-0d27aa3d-776b-4eaa-b28c-8cff91d8b7b8.png)

Here are some common things we have seen that cause this issue:
1. The identity running the flow does not have the Power Platform Admin Role permanently assigned. 
2. The target environment for the call here was renamed but the old name is cached. In this case turning **_Admin | Sync Template v3 (Model Driven Apps)_** off and back on will clear that cache.
3. The connection needs fixed as in https://github.com/microsoft/coe-starter-kit/issues/4481

**Comment by AtsushiIshida** [comment]
I have same issue.
And, it was discovered that when the filter query for retrieving a list was written, it failed with a 502 error.

Therefore, the filter query was removed and a filter process was added in the later stage, but now the list retrieval action is caught by the 100MB limit in my enviroment.

I am posting this information in hopes that it will be useful for the investigation.

**Comment by Jenefer-Monroe** [comment]
Yes that is another understood limitation. There is a size limit on what is returned and you cant select individual fields with the legacy connector. 
This area will be made better with that modern connector once its unblocked for usage. 
I;ll go ahead and close this now then as understood limitations.
