### ISSUE TITLE
[CoE Starter Kit - QUESTION] Setup Wizard - Other Core Components

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5591]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The setup wizard for Other Core Components , doesn't show any apps to be shared in the 'Share Apps ' Blade . Is this the expected behaviour.

<img width="1167" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/6b1e33de-073a-47af-8071-83fd77abe85b">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Yes there are no apps specific for this solution area at this time.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
