### ISSUE TITLE
[CoE Starter Kit - BUG] Rows getting deleted

### ISSUE THREAD

**Issue by guptapranjal1995** [microsoft/coe-starter-kit#5592]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have a business justification process in place which is triggered whenever a new row is added in PowerApps App table. Recently we have observed a few cases where on deletion of the app its row is also getting deleted. Is this ideal process to happen?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin - Sync App

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I believe you are saying the following. Can you please confirm? 

- Today when an app is created in the tenant you see it added to the inventory tables
- Today when this app is deleted from the tenant, that row is also deleted from the inventory tables. 
- You would like to keep the record in the inventory table even if the app is deleted from the tenant. 

Is that what you are saying? 
If so, we do have an env variable called **_Also Delete From CoE_** which will just mark the app in inventory as Deleted, but keep the row in the inventory
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/60c4c3a9-73da-4e0c-aa22-3bfd35e18f2c)

**Comment by Jenefer-Monroe** [comment]
If this is the issue you are asking about
- Today when an app is created in the tenant you see it added to the inventory tables
- Today when this app is deleted from the tenant, that row is also deleted from the inventory tables. 
- You would like to keep the record in the inventory table even if the app is deleted from the tenant. 

Then correct, this value being yes means the app will be deleted from inventory when it is deleted from the tenant.

**Comment by guptapranjal1995** [comment]
Thanks for the confirmation!!

**Comment by Jenefer-Monroe** [comment]
You're welcome!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
