### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by RupaKondapalli28** [microsoft/coe-starter-kit#5594]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have installed COE starter kit & set up audit logs & the flows are running successfully but however the last flow run date is still not populating. Could you please let us know how can we achieve to get the last flow run date field to be populated without blanks? 

Also could you please confirm which flow is responsible for populating the last flow run date?

Thank you!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. We'll need a little more information to assist. Can you please go to the Admin Command Center and look at the Inventory Flows. Click on **_Last Run_** column header to sort by that column. Scroll down as needed. Do you see any flows with a Last Run date? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/49d8b1e6-9b3f-4a82-80e0-f9b131343b7f)

**Comment by RupaKondapalli28** [comment]
Hi,

The issue is we need that *last flow run date* to be populated for *all the
flows*, not only for the COE ones. Please check with the below for
reference.

[image: image.png]


If it is for COE Command Center, the last flow run date is populated.

[image: image.png]


Thank you!

**Comment by Jenefer-Monroe** [comment]
Oh I see. Yes that column will only be filled if you are using the Data Export option for your architecture. 

Please see [What data source should I use for my Power Platform inventory?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory) and [Frequently asked questions about the Data Export integration](https://learn.microsoft.com/power-platform/guidance/coe/faq-dataexport) for more information.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
