### ISSUE TITLE
[CoE Starter Kit - BUG] Wrong Environment ID for Default Environment Sync

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#5595]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The issue Im describing only applies to the default environment, in my case the Default environment ID is something like Default-xxxxxxx-xxxxxx while the others do not contain that first Default part. This flow is correctly using the 'name' of the environment which contains the full id to list the flows action but for the remaining actions it uses the value 'environmentid' which I cannot find in the dataverse table and also does not contain the initial Default value.
Now that this has run everything in that default environment has been marked as deleted because it cannot correctly find the flows in remaining steps. 
So in the connectors I get the message saying that I do not have permissions to that environment due to being the wrong ID.

### Expected Behavior

The flows should be found in dataverse as well as get flow action and correctly accessing their information..

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open Admin | Sync Template v4 (Flows)
2. Open SYNC HELPER - Cloud Flows
3. Find that any action that requires environment ID is failing so it thinks the flows do not exist and marks them as deleted in the dataverse table

**Comment by Jenefer-Monroe** [comment]
I see, the issue is that we sent the ID to the child flow not the name. 
Fix is to send in name instead. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e133c0ca-5a54-47a4-8c51-53be1f4072f8)

Thank you for debugging!

**Comment by Jenefer-Monroe** [comment]
Yes the change will be to send in both name and id, and then us the correct one throughout the child flow

**Comment by plattasia** [comment]
Can we please get a hotfix for this asap. All flows from Default environment are gone. Customers cannot wait a month to get that data back. and all the data collected for compliance is gone along with the flows.

**Comment by Jenefer-Monroe** [comment]
We are shipping June soon as this release was so late. I will work internally to see about a hot fix or just an early release of June.

**Comment by Jenefer-Monroe** [comment]
Hot fix released 

View:
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-May2023-HF1

Download:
https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-May2023-HF1/CenterofExcellenceCoreComponents_4.8_managed.zip

**Comment by plattasia** [comment]
Thank you so much!

**Comment by maikletal** [comment]
I have the same issue in the latest CoE version (june-23)

**Comment by Jenefer-Monroe** [comment]
Hello. Please post a new issue and reference this one.
