### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by bethleota** [microsoft/coe-starter-kit#5596]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In this section of the starter kit instructions, I'm confused about what type of group to create. I realize this is probably a dumb question, but I'm not sure what type of group to create and what is meant by associating it with a MS team. See:
We recommend using three [Microsoft 365 groups](https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups#microsoft-365-groups), one for each persona. This group type is an email-enabled security group and can be associated with a Microsoft team for collaboration between the people in the [group.](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users)

 
![CoE-TypeOfGroup](https://github.com/microsoft/coe-starter-kit/assets/40639953/c41b1304-1ded-40d4-831f-0661d2eec195)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

Core CoE Install

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Yes the language around the group types is a little confusing. Its this one that you want
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e7e741e9-5418-4349-893f-cdb5bcb060f2)

It contains the needed features of those other ones. 
Hope that helps
