### ISSUE TITLE
admin_app With Id = xx Does Not Exist

### ISSUE THREAD

**Issue by tsegato** [microsoft/coe-starter-kit#56]
I get following error from the CoE framework. Any pointers on how to solve?

![image](https://user-images.githubusercontent.com/43033640/110121642-eee25280-7dbe-11eb-9ecb-028fb70839b0.png)

**Comment by devkeydet** [comment]
Sorry about the confusion, but this repo is the future home of the CoE Starter Kit. That transition hasn't happened yet. We tried to make that clear in the readme.md. Until the transition is complete, would you please ask here:
https://github.com/microsoft/powerapps-tools/issues
