### ISSUE TITLE
[CoE Starter Kit - BUG] Loading blocked by failures with other queries.

### ISSUE THREAD

**Issue by Bala-Ammu1221** [microsoft/coe-starter-kit#5602]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

COE start Kit is not working, it's showing the error like "Loading blocked by failures with other queries."

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

latest

### What app or flow are you having the issue with?

Desktop flows

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid we'll need more details to assist. 
I presume you mean that the PBI dashboard would not load? If so please provide the following. Note that you need to log in to GitHub to share the screenshots, they will not come through if you just respond in email.

1. Let us know, were you first loading a PBIT or were you refreshing an existing PBIX?
2. Name of the PBIT or PBIX you were trying to load
3. Screenshot of the failure (the pbit refresh faliure)
4. Screenshot of the solutions you have installed. Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Jenefer-Monroe** [comment]
Thank you, can you please also provide the screenshot of the solutions you have installed as shown above?

**Comment by Bala-Ammu1221** [comment]
I haven't installed any solution, Can you please provide the detailed steps to access CoE dashboard?. Lot of confusion in MS documentation

**Comment by Bala-Ammu1221** [comment]
And at the same time what type of access is required to view/monitor all the flows across environments

**Comment by Jenefer-Monroe** [comment]
Hello. The CoE dashboards rely on the CoE solutions being installed. I'm afraid setup is a bit of work and our documentation is the best we can do generally speaking. Please go through it and if you have specific questions please let us know. 

Note also that there is a setup wizard app that will help you through the process quite a bit. 
And that there is a large partner community around the kit that can help you get it set up and comfortable with its usage. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

If you want to try and configure on your own, please start here: [Before setting up the CoE Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/setup)
It contains a section called [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with) which details the permissions/access needed to setup and run the kit. 

Once you are done with that, you can [Set up inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components). It contains a section near the bottom that tells you when you would be ready and able to [Set up the Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#set-up-the-power-bi-dashboard), as well as a link to the instructions on how to do that.

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team
