### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Sync Template v3 worklfow is missing

### ISSUE THREAD

**Issue by power-mike** [microsoft/coe-starter-kit#5605]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

the main workflow Admin | Sync Template v3 is missing in the may release.

### Expected Behavior

the workflow should be inside the core component solution so that it can trigger the inventory flows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

adnin - sync template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

download may release, import in new environment

**Comment by Jenefer-Monroe** [comment]
Hello. The flow was renamed to **_Admin | Sync Template v3 (Driver)_** this month to get around an issue with the name not being unique.
Thank you for using CoE
