### ISSUE TITLE
[CoE Starter Kit - QUESTION] Setup Wizard DLP Error 

### ISSUE THREAD

**Issue by declawson** [microsoft/coe-starter-kit#5609]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Initial Setup is failing with Error Code: AppForbidden

{"error":{"code":"ApiPolicyViolated","message":"It looks like this app isn't compliant with the latest data loss prevention policies.\r\nYour organization’s governance reference material:  <URL of GitHub Power Platform site template DLP.aspx>  Your organization’s governance contact: _scrubbedSensitiveData_","details":[{"code":"MultipleViolations","message":"Policy name: Policy <policy name>\r\nBusiness connector: shared_office365users cannot be use<truncated>

I already added Power Query Dataflows to the DLP for Business and tried running from make.powerautomate instead of make.powerapps.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
