### ISSUE TITLE
[ALM Accelerator - BUG]: Canvas Sharing Doesn't Work for Managed Solution Deployment

### ISSUE THREAD

**Issue by jfung85** [microsoft/coe-starter-kit#5611]
### Describe the issue

We have not been able to deploy a managed solution to a TEST environment with the Canvas App shared properly to the AAD group configured in AA4PP. In the Pipeline step: Retrieve AAD Group Team Config for Deploy -> it does look like it is able to retrieve the group. However, the step: Share Canvas App with AAD Group -> looks like it is return blank values even though it is successful.

Sharing app (guid) with (guid)
Code        : 
Description : 
Headers     : 
Error       : 
Errors      : 
Internal    : @{put=System.Object[]}

Here are some other configurations that are working for reference:
1. Import the same solution as unmanaged to a different dev environment -> Canvas App has AAD group setup co-owner and lows have the account configured in AA4PP set as Owner
2. Import the solution as managed to TEST environment -> Flows have the account configured in AA4PP set as Owner 

### Expected Behavior

We expect the AAD group configured in AA4PP settings to be added as Co-Owner on Canvas Apps after deployment is complete.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Accelerator Version: 1.0.20230517.1(Managed)

### Steps To Reproduce

1. In AA4PP, go to solution -> Configure Deployment Settings
2. Under Canvas Apps -> Add AAD Group to all Canvas Apps and set as Edit
3. Commit Solution with settings -> Create New Branch 
4. Deploy Solution with settings -> Advanced disabled -> Select Test profile

**Comment by mikefactorial** [comment]
@jfung85 is the App registration that you are using to deploy to test the same as the app registration deploying to dev i.e. same app id for the service connection? If not double check that the App registration has the permissions mentioned here https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#give-power-app-management-permission-to-your-app. Unfortunately, this is still a requirement for sharing apps using a service principal.

**Comment by jfung85** [comment]
Hi @mikefactorial, yes the app registration is the same. I've added the service principle as an App User with System Admin role on the TEST environment. I can see that service principal is the owner on the Canvas Apps when they were created in the TEST environment. The Custom Connector and the Service Connections on the DevOps project all look to be configured correctly as described to the article. It seems like the current permissions allowed it to do other things like set ownership on Flows. Is there something specific that would affect just the Canvas App sharing configuration?

**Comment by mikefactorial** [comment]
@jfung85 the only thing that should affect the canvas app sharing is the app management permission I mentioned above but if the app sharing is working in the dev environment. There's nothing I can think of that would make sharing not work. Can you try running the script here just to verify that the permission has been added? https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#give-power-app-management-permission-to-your-app.

**Comment by mikefactorial** [comment]
@jfung85 you can also try running Get-PowerAppManagementApps to see all of the existing service principals with this permission.

**Comment by jfung85** [comment]
I tried the deployment again and it is working now. I see that the groups have been added as co-owner on the canvas app in the target environment. I didn't make any changes so I am not sure why the prior run didn't set the canvas app permissions but I think we are good for now. Will try more tests to see if it will configure it consistently.
