### ISSUE TITLE
DLP Editor stuck in giving impacted flows and apps details

### ISSUE THREAD

**Issue by subcha3** [microsoft/coe-starter-kit#5612]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

DLP Editor stuck in giving impacted flows and apps details. It is showing a blank screen/showing very few flows or apps and getting stuck and moving.  And I am unable to get the data imported to an excel where it is not giving all details. Please help

### Expected Behavior

It should show all the flows and apps which are going to impact once we assign the policy

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

DLP Editor V2

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Open the DLP Editor app
2. select the existing dlp policy to do the impact analysis

**Comment by Jenefer-Monroe** [comment]
Hello. I"m afraid you'll need to provide a little more detail. Note that we do have this bug currently on the list for investigation. Is that what you are seeing? https://github.com/microsoft/coe-starter-kit/issues/4788

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
