### ISSUE TITLE
[CoE Starter Kit - ISSUE] Admin | Add Maker to Group flow is continuesly failing 

### ISSUE THREAD

**Issue by ShaktiKovvuru** [microsoft/coe-starter-kit#5614]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Admin | Add Maker to Group flow is failing with the below error :
 The 'inputs.parameters' of workflow operation 'List_group_members' of type 'OpenApiConnection' is not valid. Error details: Input parameter 'groupId' is required to be of type 'String/uuid'. The runtime value '"***********"' to be converted doesn't have the expected format 'String/uuid'.
![image](https://github.com/microsoft/coe-starter-kit/assets/134496019/79b5ba0c-2542-4c03-ae44-22757c763917)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Add Maker to Group

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
What value have you entered for the Power Platform Maker Group ID?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d1f0d119-336a-4f09-837a-675a72947b64)

[Gather environment variable values](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#gather-environment-variable-values) 
It shoudl be the ID (the GUID) of the group
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6b7804d0-b68b-43d3-96c4-5d7704196822)

By the way, if you use the setup wizard, some of these complexities will be handled for you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
