### ISSUE TITLE
[CoE Starter Kit - BUG] Apps shared with Groups that are not identifiable

### ISSUE THREAD

**Issue by Jakrina** [microsoft/coe-starter-kit#5618]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are experiencing weird number of Users and Groups an App is being shared with (it has happened for many Apps).
 
![Shared](https://github.com/microsoft/coe-starter-kit/assets/98682417/7405fb02-b6b3-40f8-a9b8-48ac5ac8786e)

This Picture is an example. You can see in the Green part that the “Total Shared with” is 16. Also – when I open the Shared app itself, I see only those 16 users. The same when running PowerShell Script to “See Role Assignments”. Only 16 and all are people, not groups.

But then there is the Red part – “App Shared Groups” and “App Shared Users” which has some large groups. I cannot see what the groups are, as I mentioned that both from the App and the Script there are no Groups being shared with at all.

Also, in the Dataverse it looks weird as the Total that is being calculated is less than the number of groups.
 
![image](https://github.com/microsoft/coe-starter-kit/assets/98682417/ad425f8a-274d-44c5-a6a7-282e44945607)

And it is like that for at least Most of Canvas Apps in Personal Productivity, but not ALL.
 

We could assume that the calculations are wrong, but:
1.	The flows for that seem to be running successfully.
a.	Cleanup - Admin | Sync Template v3 (Power Apps User Shared With) 
b.	CLEANUP HELPER – Power Apps User Shared With
2.	Then we should also see the Groups from the App itself or the Script, but as I mentioned there are no groups visible.

So, I assume that more likely there are some “mystical” groups appearing in the Data. Also, the users say they have no idea who they are.

Are there any suggestions?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Cleanup - Admin | Sync Template v3 (Power Apps User Shared With) 

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Open Admin App
Open an App
Compare the Total shared with Groups Shared and Users Shared

**Comment by manuelap-msft** [comment]
Hello,

this was a bug in a previous version - see the thread here: https://github.com/microsoft/coe-starter-kit/issues/4468 and was resolved in February. I recommend you upgrade to our May release to solve this.

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
