### ISSUE TITLE
Default Environment not shown on the Coe Admin App

### ISSUE THREAD

**Issue by leondarl** [microsoft/coe-starter-kit#562]
Dear all,

I have installed the Coe Kit on a Trial Environment and I made sure I have Power Platform Admin role but still cannot see any activity from the Default environment where currently all of our apps and flows are running,.

Any hep will be appreciated.
Stay safe
Thank you
Leonidas
Dear all,

 My apologies for not sharing more details 
Coe Kit Version 2.0.10 
One of the flows  "Admin | Compliance detail request v3" is failing trying to read the Default environment. 
Here is the snap shot of the flow and the failure:

![COE_Admin_ComplianceDetailReport v3](https://user-images.githubusercontent.com/84543367/120701797-4efd9900-c481-11eb-9eef-c78ddc797d06.JPG)

Error:
InvalidTemplate. Unable to process template language expressions in action 'Default_Environment_Name' inputs at line '1' and column '32661': 'The template language expression 'first(body('Get_Default_Environment')?['value'])['admin_environmentname']' cannot be evaluated because property 'admin_environmentname' cannot be selected. Please see https://aka.ms/logicexpressions for usage details.'.

We have renamed our Default Environment.

Please let me know if you need any additional information.
Stay Safe
Thank you
Leonidas

**Comment by manuelap-msft** [comment]
Hello,

We will need a little bit more detail to help here. What version of the Core Components solution do you have installed? Has the Admin | Sync Template v3 flow run successfully or were there errors? Have the other sync template flows run without error? If you can provide screenshots of what you are seeing where, that would help. 

Thank you
Manuela

**Comment by leondarl** [comment]
Dear Manuela,

Thank you for your prompt response.
My apologies I added the new comments and described the  one error I found once I went through the Flows Run History.

Please let me know if this is sufficient or you need any additional information.

Looking forward to your comments .
Stay safe
Thank you !!
Leonidas

**Comment by JeneferM-MSFT** [comment]
Hello I believe this is failing because you do not have admin access to the Default envt

Can you please confirm what was returned in the call to Get Default Environment in the action above the failing action? 
![image](https://user-images.githubusercontent.com/62659043/121022953-0e8f6b00-c760-11eb-832a-5eb837deec7d.png)

Can you please confirm that the user identity installing and running the flow has has the Power Platform Admin Role? 
Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)

**Comment by leondarl** [comment]
Dear Jenefer,

 Here is a snap shot of the response with any id's removed for your review:

![image](https://user-images.githubusercontent.com/84543367/121080711-c5fc9f80-c7a9-11eb-943f-57791c053a39.png)

I have verified that I do have the proper power platform admin role and re ran the flow to make sure.
Same error 
Please let me know  if I should upload the most recent version and create a new Solution to test.

I really think this tool is the Stairway to power platform MS Heaven !!

With much appreciation for all your help and support 
Thank you !!!!!!
Leonidas

**Comment by JeneferM-MSFT** [comment]
Yes, as you can see it did not return any value. So it did not find a default envt in your inventory.

1) Is your identity that you validated has PP Admin the identity that installed the Core solution? 
1) Please validate that the following flow has been running successfully: **_Admin | Sync Template v3_**
1) Please open your Power Bi or the Model Driven app and validate that you see the default envt there 
![image](https://user-images.githubusercontent.com/62659043/121083293-7cf21e80-c79c-11eb-9092-779c7b0afb06.png)
1) Please go to https://admin.powerplatform.microsoft.com/environments and validate that the Default envt is shown there. And let me know what is listed for its Type
![image](https://user-images.githubusercontent.com/62659043/121083630-ea05b400-c79c-11eb-8afd-7da9a9a24b2b.png)

**Comment by JeneferM-MSFT** [comment]
And thank you for the kind words, we love the starter kit

**Comment by leondarl** [comment]
![image](https://user-images.githubusercontent.com/84543367/121085186-8d5fc480-c7af-11eb-8215-a2b0679ba837.png)

Dear Jenefer,
Here is what I see. I see all the environments.  Just  to make sure that I did not have this role when I imported teh solution. I requested it post installation . 
I can re install the latest version that you have available and see if this error clears out.
Sorry to trouble you and thank you !!
Have a great evening !!
Leonidas

**Comment by JeneferM-MSFT** [comment]
Quite all right. Please just make sure that **_Admin | Sync Template v3_** has run and passed since you got those permissions.

**Comment by JeneferM-MSFT** [comment]
checking in to make sure this is resolved for you.

**Comment by leondarl** [comment]
Dear Jenefer,
 Thank you so much for checking in I have re installed the Core Components and the Audit and log solutions.
I am still waiting for the data to compile but at a first glance it looks that my Power Admin role rocks and I can see on the Admin Dashboard all the Environments and the proof is that the flow ran without any errors for now .
![image](https://user-images.githubusercontent.com/84543367/121925845-53407680-cd0b-11eb-99bb-0e5e20286c6e.png)

I still need to wait until all data is compiled and I will update you.

I will like to ask a question about "Coe Updates" I tried to perform a manual update but I was not able.
The instructions are not so clear but it seems that there is an Upgrade option that I was not able to identify. 
Can you please help me with that question as well when you get a chance.
There are already a few updates that I need to apply .
As always with much appreciation for all your help and thank you for all you do for the Power Platform community.
Stay safe
Thank you !!
Leonidas

**Comment by leondarl** [comment]
Dear Jenefer,

I have great news.
The data is compiled and I can see the Default Environment along with all activities on the dashboard.
I will take some time to digest now all the ifnormation .
Wish me luck !!

So this ticket can be closed and Thank you for all your help.
If you can just help me with how to  Update my current solution with the latest Coe Releases.
With much appreciation !!!
Stay safe
Thank you !!
Leonidas

**Comment by JeneferM-MSFT** [comment]
You update following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.  
Thanks for using CoE
