### ISSUE TITLE
[CoE Starter Kit - QUESTION] Disabled Dataverse for Teams environments do not get deleted

### ISSUE THREAD

**Issue by Jakrina** [microsoft/coe-starter-kit#5621]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!

I have just noticed that we have lots of Dataverse for Teams environments with Disabled status and, when opened, it says they will be deleted today. But I assume that it is not happening as I checked some of them in the emails and they are disabled already since January.

We thought that this will happen automatically since this new feature was implemented.

Should we change/turn on something for the Disabled environments to get deleted finally? Cannot find anything related to this.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid this is a product feature and not a feature of the toolkit, so I cannot provide assistance. You will need to contatc product support.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
