### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by farzanapenske** [microsoft/coe-starter-kit#5625]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We installed COE in out power platform environment on APril 23rd with help of Micosoft. It was working fine for few days after that  dashboard is showing updated data. It might be configuration issue or some power automate flows might be broken. We need help to COE works again

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Not sure

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid we are a very small team and so cannot scale to meeting with our GitHib customers. If you provide me some details on what is / is not working I can try to help you here, or you can reach out to the person that helped you set it up and see if they can help.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
