### ISSUE TITLE
[ALM Accelerator - QUESTION] Repositories vs Folders

### ISSUE THREAD

**Issue by GU-VITA** [microsoft/coe-starter-kit#5627]
### What is your question?

what is the recommend Azure DevOps structure?

1. One single repository with a sub-folder for each solution? in this scenario, will the solution folder be automatically created or does the DevOps engineer need to create the solution subfolder in DevOps first?
2. Use the ALM Acc. Admin to create a repository for each solution?
3. Should the template pipeline be added to each repository or can we use the template pipelines folder from the default project repository?
 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April 2023

**Comment by mikefactorial** [comment]
@GU-VITA thanks for the question. I can't recommend a specific setup as it is up to you how you'd like to implement source control at your organization. I can tell you that we as the Power CAT team store all of our solutions in a mono-repo per project e.g. the CoE Starter Kit solutions and the ALM Accelerator are stored in the same repo, while we store the Creator Kit and Automation Kit in seperaate repos. For each AzDO project, however, you will need to have the ALM Accelerator templates installed in a repo and have the pipelines configured.

**Comment by GU-VITA** [comment]
Thanks

**Comment by mikefactorial** [comment]
Closing this out for now. One additional option to better help with maintenance and updates if you decide to use multiple projects for your solutions is to store your pipeline templates in a central repo and generate the pipelines off of that repo this will make it easier for you to update to the monthly releases without having to have multiple copies of the templates.
