### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Log for Flow sessions?

### ISSUE THREAD

**Issue by GU-VITA** [microsoft/coe-starter-kit#5628]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

It seems like the COE Audit Log only captures auditing based on the AppLaunched event. 

Does the CoE provides auditing on flows? 

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by GU-VITA** [comment]
Thank you

**Comment by Jenefer-Monroe** [comment]
You are welcome! I'll go ahead and close this out then, but please return if you have questions in the future.
