### ISSUE TITLE
[CoE Starter Kit - QUESTION] Capacity Alerting and Reporting

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5629]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

For Capacity alerting and reporting, email is received when consumption is over the approved limits
<img width="530" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/495ba8fb-e6da-49ad-99a4-9b581a6026be">

Could you please guide, how this actual consumption is calculated or from where it is coming?
Also, 1. Could we add the Environment type in this report as well
2. From the current report , we have found these environments are Developer environments. Could you please suggest what action should be taken by the owner of developer environment? 

The below doc snip says, developer environments are not counted against capacity. Shall they be then scrutinized by CoE?
<img width="455" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/e58a9c95-5bd2-430d-9aaa-3065204322ba">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April

### What app or flow are you having the issue with?

Admin sync Template- V3

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
