### ISSUE TITLE
[Core components for Teams environment]: failed to import

### ISSUE THREAD

**Issue by AhmadiRamin** [microsoft/coe-starter-kit#563]
I'm trying to install CoE toolkit in a Teams environment, but I get the following error:

Customizations from file "CenterofExcellenceCoreComponentsTeams_1_992_managed.zip" failed to import: Definition with ID ab10dde3-c788-4dc5-8025-894190891ab3 and SchemaName admin_DeleteFromCoE already has a value.

I can see it in the installed apps but I'm wondering if something it is imported successfully.

**Comment by JeneferM-MSFT** [comment]
If that still does not work, please see if the env variable referenced has an unmanaged layer.  See #566

**Comment by JeneferM-MSFT** [comment]
closing out as no additional work for the toolkit
