### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Starter Kit Set-Up Identity (Service Account)

### ISSUE THREAD

**Issue by sciencestudent-Sharon** [microsoft/coe-starter-kit#5631]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi there,

I've reviewed the prereqs for the identity needed to install the CoE ([https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with))

What type of account to deploy the CoE Starter kit with such that it can be managed by multiple people?

I have reviewed service principals and service accounts and would like to set up a service account for this kit.
But I'm not sure about group managed service accounts or standalone etc. - any additional details would be greatly appreciated on this.

Thank you

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. We do not yet support service principles as service principle support is not yet done for the connector set upon which the kit relies. 

Many people use a shared account like "PowerPlatformAdmin@yourtenant.onmicrosoft.com" to manage their kit. The only thing to be sure is that you allow the account permanent access to the role and license, just like you would need to do role a regular account driving the kit. 

Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
