### ISSUE TITLE
[CoE Starter Kit - BUG] Seeing Blank Rows in Power Bi Dashboard and on Power Platform Admin View Model Driven App

### ISSUE THREAD

**Issue by ashwanidv100** [microsoft/coe-starter-kit#5632]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Seeing few blank rows in CoEDashboard in Overview - PowerApps Page. Please find the images

(Environment Name is not visible but in Power Platform Admin View Model-driven App, The data for these rows are almost blank, for 1-2 few dates stamps are available)

![image](https://github.com/microsoft/coe-starter-kit/assets/10371826/a7a9e069-0c6a-485a-98e7-8f5111196c70)

Hypothetically I think it because of Orphaned Apps. (But please clarify on Why App Makers are not showing these huge number of Apps)

![image](https://github.com/microsoft/coe-starter-kit/assets/10371826/5ff4e013-36af-4f1b-9d63-28686baa84de)

All the useful inventory flows are turned ON and running smoothly.

### Expected Behavior

All Data should be visible and available. In case of Orphaned Apps and Flows the CoE Dashboard should show indicate App Maker as a "Orphaned App"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Dashboard is missing few Display Names and Power Platform Admin View App have rows with missing data

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Install the CoE Starter Kit
2. Turn on Inventory Flows
3. Setup Power Bi Dashboard
4. Identify Missing value for rows and same is not appearing in Dashboard

### Anything else?

Screenshot for Power Platform Admin View, Model-Driven App
Filter on App Display Name with "Dose not contain Data"

![image](https://github.com/microsoft/coe-starter-kit/assets/10371826/f85b6359-844d-4f94-94e2-e49f290a46ab)

**Comment by Jenefer-Monroe** [comment]
Please be sure that the **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_** flow is turned on and running. This will clean up the records with no environment. Those records will never recover as all inventory flows are based on environment. 

Then see if they return, and if so we will debug. 

Please note that all Inventory flows need to be turned on to have a reliable inventory. Note that if you use the **_CoE Setup and Upgrade Wizard_** app to install / upgrade, this will happen for you automatically. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0ad0cdab-ad6a-4c95-85b7-2f4d89fdb2d1)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by ashwanidv100** [comment]
Thank you this helped. Although I can still see the Top App Makers is blank (screenshot already shared above). Shall I consider those to be Orphaned App and also Model-driven or Dynamics App where we don't see Owner Names.
