### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Dashboard Not showing any Data for Desktop Flow and PVA pages

### ISSUE THREAD

**Issue by ashwanidv100** [microsoft/coe-starter-kit#5633]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

CoE Dashboard Not showing any Data for Desktop Flow and PVA pages in the report

### Expected Behavior

We should seeing the Power Automate Desktop and PVA data in the Power Bi Dashboard

![image](https://github.com/microsoft/coe-starter-kit/assets/10371826/4319d708-0613-46ec-9f54-782c4f2dcd39)

![image](https://github.com/microsoft/coe-starter-kit/assets/10371826/b382a428-694a-4989-a86b-ae1a9a0cfc31)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

CoE Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Install CoR Starter Kit Core components
2. Turn on Admin | Sync Template v3 (Desktop Flow - Runs)
3. Turn on Admin | Sync Template v3 (Desktop Flow)
4. Turn on Admin | Sync Template v3 (PVA)
5. Turn on Admin | Sync Template v3 (PVA Usage)
6. Setup Power Bi (CoE Dashboard)
7. View Desktop flows and Virtual Agents Power Bi Pages

**Comment by Jenefer-Monroe** [comment]
Hello. All Inventory flows need to be turned on to have a reliable inventory. Note that if you use the **_CoE Setup and Upgrade Wizard_** app to install / upgrade, this will happen for you automatically. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0ad0cdab-ad6a-4c95-85b7-2f4d89fdb2d1)

Can you please view the Power Platform Admin View app. Do you have environments present? Do you have the Desktop Flows and PVAs there? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2bd31c48-2beb-4f02-871d-62de63d183f3)

**Comment by ashwanidv100** [comment]
HI @Jenefer-Monroe, Yes I have Environments present and I know few Environments that does have Desktop Flows created and PVA's.

Screenshot from Power Platform Admin View (Please ignore "OFF" status of Admin | Sync Template v3 (Flows) as we 'v4' turned "ON")

![image](https://github.com/microsoft/coe-starter-kit/assets/10371826/a9336f91-5d0d-4339-87dd-ca730c329022)


And the screenshots for Flows Runs 
![image](https://github.com/microsoft/coe-starter-kit/assets/10371826/5d86adc2-1ae9-4030-90a5-05c94affdc21)

![image](https://github.com/microsoft/coe-starter-kit/assets/10371826/020b60ce-6307-40e2-8728-94b649c835b4)

**Comment by Jenefer-Monroe** [comment]
Thats strange, you should not see the old flows, they should have been removed when you upgraded. I dont think that woudl be why you arent seeing your inventory but it may lead to other issues. Let's settle that after we look for your objects.

**Comment by Jenefer-Monroe** [comment]
So pick one of the environments where you expect PVAs and Desktop Flows to be present and note its GUID. Make sure also that its in your inventory.

Go to the runs for these flows, add the environmentid column to the view and go to all runs
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7476860e-0d24-4695-b293-20b06b58214e)

Control-F to look for your GUID in the runs
You may need to browse to the bottom and click "Show more" a few times if you have lots of environments. 
When you find it click its timestamp to open the run
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/05bdc8d4-66be-4152-a85a-5d40a6593578)

Let me know what you see in the run.

**Comment by ashwanidv100** [comment]
I'm still looking into PVA. But I can share the info on Desktop Flows, (This is our Default Env. and it looks like the flow is failing due daily due to same reason and i.e.  `Http request failed as there is an error: 'Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600.'`

![image](https://github.com/microsoft/coe-starter-kit/assets/10371826/39d9d435-77d8-4482-b73e-51c5f6422760)

**Comment by Jenefer-Monroe** [comment]
The desktop flow work in the CoE Starter Kit currently has several limitations that make it insufficient for organizations heavily focused on that tech. This is due to the way that we gather the data and is not something we can fix without a product change (which is supposed to be coming live in a few months). Please see our [limitaitons](https://learn.microsoft.com/power-platform/guidance/coe/limitations#large-desktop-flows)

That said, there is a dedicated set of folks who work on "Automation CoE". My recommendation is that you focus in that direction instead if you need this data. Here are some starter links to get you going:
https://learn.microsoft.com/power-automate/guidance/automation-kit/overview/introduction

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
