### ISSUE TITLE
[CoE Starter Kit - QUESTION] Request to add descriptions for coe flows that are missing descriptions

### ISSUE THREAD

**Issue by SoumyaBehera123** [microsoft/coe-starter-kit#5634]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have installed CoE starter kit and created an additional custom view in CoE Admin command center which captures all the flow details including it's description. But for a number of CoE flows, the flow description is not present in the Microsoft learn site as well as in the description field of the CoE flow details. As a result, when we are running a custom flow to capture the description details in our view in a column, it is coming as empty in the description column of our custom view. 

Please let us know if the requested flow description details will be available in the upcoming updates of CoE starter kit or can you update the flow description details for the mentioned below flows where it is not present. There are 13 CoE flows in total for your reference. Also have attached the screenshot of customized view containing the CoE flows having the description details.  Attached screenshots for your reference. Also attached the Microsoft learn site for your reference as well.

https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components

<img width="960" alt="Screenshot_CoEflows_descriptionnotpresent" src="https://github.com/microsoft/coe-starter-kit/assets/134600630/4b1bee50-41f6-498c-b838-7f407ed0cd58">

<img width="962" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/134600630/a9d51da2-530a-4aba-8607-e03900d0899a">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I believe you are just asking us to add descriptions for our flows where we forgot to. Is that correct? 
If so, I can do this for the June release.

**Comment by SoumyaBehera123** [comment]
Hi Jenefer, Yes please. You can add the descriptions for the flows which are missing in the June release.

**Comment by Jenefer-Monroe** [comment]
Re-opening. We will use this bug to track it being complete and then it will get auto-closed so you know when its complete. 
Thanks for posting!
