### ISSUE TITLE
[CoE Starter Kit - QUESTION] Account used to install CoE is not mail enabled. OK to use other non-admin account for Outlook connection reference?

### ISSUE THREAD

**Issue by HenningStrand** [microsoft/coe-starter-kit#5636]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

During import of core solution I need to provide connections for all the connection references. I am not able to create an Office 365 Outlook connection as the Power Platform admin account I am using is currently not mail-enabled. Can you confirm that there will be no issues using a different account for this connection reference that is not given the Power Platform admin role? 

I checked that this connection reference is being used in three apps and 4 flows.
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/f503eacc-03de-45cc-affb-87cd7f065eb3)
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/f28cdf77-9191-4280-9bf9-9a5ce7d627eb)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Install

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
This should work, but it's not something we've tested on our side. However, we know other customers have a similar setup where

1. One connection is used for the Power Platform Admin / Dataverse / ... connectors. This connection has to be to an account that has the Power Platform Admin role.
2. One connection is used for the Outlook / Teams connector. This connection has to be to an account that's email enabled. 

I'm not aware of any issues with this setup, but like mentioned earlier it's not something we test ourselves. Do let us know what you find and if you have any issues, and we can add it to our documentation as well.

**Comment by HenningStrand** [comment]
OK. Thx. If I use my regular account for the Teams/Outlook connectors it is set up with MFA. The adm account is not. I don't see that this should give any extra worries, right?

**Comment by manuelap-msft** [comment]
It should not, no, Power Automate works with conditional access and MFA. There's some guidance on this here: [
conditional access and multi-factor authentication in Flow - Power Automate | Microsoft Learn](https://learn.microsoft.com/en-us/troubleshoot/power-platform/power-automate/conditional-access-and-multi-factor-authentication-in-flow)

**Comment by HenningStrand** [comment]
Thx again. One last thing. I am logged on as the admin account when creating the connections. Hence the Outlook connection (using the other mail-enabled regular account) will be owned by the admin account. I guess this will not give any issues blocking turning on the flows due to connection permissions. Any thoughts?

**Comment by HenningStrand** [comment]
Hmm. Not positive. Adding the new connection fails and leaves it with status 'Can't sign in Fix connection'. Now I cannot even delete it as I get a permission issue. Seems like connection sharing issue. Means that I have to install the core components using an email enabled account... or?
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/a40038c0-68f6-40d6-ab63-406a7a4919c9)

**Comment by Jenefer-Monroe** [comment]
I'm afraid we haven't explored this area much, our general guidance is that the account needs to be email enabled and it appears that this guidance is correct.
I think some people have figured out a way around this but I wouldn't be able to explain that path to you as I havent figured it out myself.

**Comment by HenningStrand** [comment]
Understand. I managed to create Teams and Outlook connections using another account and install the solution. But still the setup wizard app's checks gives a fail for the account doing the setup, so I opted out. Will set up a new account that has all the requirements.

**Comment by manuelap-msft** [comment]
Hm, I think for the Setup Wizard if you're talking about the first screen (check pre-requisites), that only checks the license and permissions of the "logged in" user and not of the connection references you have set. If you know you're meeting the pre-requisites across different accounts, you should be able to ignore the first screen on the setup wizard and select Next still.

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team
