### ISSUE TITLE
COE environment being used as a Dev environment

### ISSUE THREAD

**Issue by snl-meg** [microsoft/coe-starter-kit#5639]
We installed our COE in an environment. Now the same environment is being used a development environment for users to start developing apps and testing. Is it a good idea or should I plan to install the COE into its own environment? If so how can I save data that has already been collected?

**Comment by Jenefer-Monroe** [comment]
Hello. Unless the development is about your CoE then I would not suggest this, no. Mostly because this would give all the devs in that environment access to all the data about the PP inventory and usage in your tenant. 

Data migration is not simple unfortunately. Can you comment what type of features in the CoE you are using?
If you cannot just recreate (aka if you are using for more than just to view the inventory but also to collect things like compliance information) then likely you will need to migrate the data over using dataflows. I'm afraid I dont have a good write up for this. 

Please do let us know how you are using the kit today,.

**Comment by manuelap-msft** [comment]
You could also explore the configuration migration tool to migrate data, although we don't have experience with this ourselves: https://learn.microsoft.com/en-us/power-platform/alm/configure-and-deploy-tools

**Comment by snl-meg** [comment]
Hi Jenefer,

We use it mostly for compliance.

Maria

**Comment by snl-meg** [comment]
Thank you for responding. Would it be any different if say I haven’t updated the COE in more than 3 months? What is the best solution in that scenario?

Maria

**Comment by Jenefer-Monroe** [comment]
I'm afraid we do not have a good write up for data migration specific to the kit. But you could explore the configuration migration tool that Manuela referenced as an option: https://learn.microsoft.com/en-us/power-platform/alm/configure-and-deploy-tools

**Comment by snl-meg** [comment]
Okay thank you for responding. Would there be much historical data loss?

Maria
Sargent & Lundy

**Comment by Jenefer-Monroe** [comment]
Sorry I dont follow the question. 
Perhaps you can repurpose the envt just for CoE usage and kick everyone else out :)

**Comment by snl-meg** [comment]
If I create a brand new environment what would happened to the old environment in regards to data.
I do like your second option but that would make some developers upset.

Maria

**Comment by Jenefer-Monroe** [comment]
You would not want to have two envts for the kit running. So you would want to turn off the old one. And then if you do not migrate any data you would just just get a clean set of inventory. So if you marked an app as requiring compliance details for example that data would be lost unless you migrate it.

**Comment by snl-meg** [comment]
Okay understood. What would be the best way to turn off the environment?

Maria

**Comment by Jenefer-Monroe** [comment]
If you arent going to migrate the data, then delete the Coe starter kit components. Starting with Gov/Nurture/etc and finally delete Core. 
If you are going to migrate it, then just turn off all the flows and unshare all the apps.

**Comment by snl-meg** [comment]
Are there steps on how to migrate it to another environment?

Maria

**Comment by Jenefer-Monroe** [comment]
I'm afraid we do not have a good write up for data migration specific to the kit. But you could explore the configuration migration tool that Manuela referenced as an option: https://learn.microsoft.com/en-us/power-platform/alm/configure-and-deploy-tools

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team
