### ISSUE TITLE
[Admin | Sync Template v3 (Apps)] Action 'Add_CDS_Native_Connection_Reference' failed

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#564]
Every day I have the error Action 'Add_CDS_Native_Connection_Reference' failed in the flow Admin | Sync Template v3 (Apps) for random enviroments.

![image](https://user-images.githubusercontent.com/57954993/120605566-7c7d1f00-c44e-11eb-805a-99f53d338ef4.png)

**OUTPUT ERROR:**
{
  "error": {
    "code": "0x80040217",
    "message": "admin_Connector With Id = 412368f1-c62f-4012-87f2-23e6a061204a Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "366424ab-3428-eb11-a813-000d3a201891",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "68e11535-ee1b-4afc-acff-efad6668175a",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_Connector With Id = 412368f1-c62f-4012-87f2-23e6a061204a Does Not Exist"
  }
}
**RAW OUTPUT ERROR:**
{
    "statusCode": 404,
    "headers": {
        "x-ms-service-request-id": "d4850e54-8070-40dc-b5e8-d07d65785c00,0b8c1380-7f63-4a98-94d6-90d0c2e6e15c",
        "Cache-Control": "no-cache",
        "Set-Cookie": "ARRAffinity=6232acf71d887424a356d3a1f8f34d9460709234636d3ff871a5417a3dedd1f3; domain=org58a90771.crm4.dynamics.com; path=/; secure; HttpOnly,ReqClientId=dde8184e-f7f9-420b-880b-9b2672973693; expires=Mon, 01-Jun-2071 23:23:13 GMT; path=/; secure; HttpOnly; samesite=none,ARRAffinity=6232acf71d887424a356d3a1f8f34d9460709234636d3ff871a5417a3dedd1f3; domain=org58a90771.crm4.dynamics.com; path=/; secure; HttpOnly",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
        "REQ_ID": "0b8c1380-7f63-4a98-94d6-90d0c2e6e15c,0b8c1380-7f63-4a98-94d6-90d0c2e6e15c",
        "AuthActivityId": "16b84c61-2a5f-422b-8b4d-137ffcfa6181",
        "x-ms-ratelimit-time-remaining-xrm-requests": "1,164.12",
        "x-ms-ratelimit-burst-remaining-xrm-requests": "5301",
        "OData-Version": "4.0",
        "X-Source": "17919418413069254914711422205271826966157420210424012729721131422351002481667619224,143213154695525417913729150186187235211471604986243142139996282551844111624010316482",
        "Public": "OPTIONS,GET,HEAD,POST",
        "Timing-Allow-Origin": "*",
        "Date": "Tue, 01 Jun 2021 23:23:13 GMT",
        "Content-Length": "1137",
        "Allow": "OPTIONS,GET,HEAD,POST",
        "Content-Type": "application/json; odata.metadata=full",
        "Expires": "-1"
    },
    "body": {
        "error": {
            "code": "0x80040217",
            "message": "admin_Connector With Id = 412368f1-c62f-4012-87f2-23e6a061204a Does Not Exist",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "366424ab-3428-eb11-a813-000d3a201891",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "68e11535-ee1b-4afc-acff-efad6668175a",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
            "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
            "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_Connector With Id = 412368f1-c62f-4012-87f2-23e6a061204a Does Not Exist"
        }
    }
}

**Comment by manuelap-msft** [comment]
Hello,

can you confirm you're on the latest version of the CoE Starter Kit - Core Components that was released earlier this week, and have removed unmanaged layers before the upgrade (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates)?

Thank you
Manuela

**Comment by albertocaa1317** [comment]
Hi Manuela,
it's a pleasure contact with you. I am a very fan of your posts in the community and you videos of Power CAT :)

Yesterday I updated the CoE to the lastest version and I don't had any unmanaged layers. I think that if I had them, the updated had failed, do it?

This error already had it  from the previous version and I did hope that this new version fix it, but not :(

How will be the best way to fix it?

Thanks.

**Comment by manuelap-msft** [comment]
Hello,

thank you for the lovely comment!

The update will succeed if you have unmanaged layers, but the components (flows or apps) with unmanaged layers won't receive the upgrade but will stay in the unmanaged version. 

The best way to check is selecting the Admin | Sync Template v3 (Apps) flow, clicking on the ... and looking at "See Solution Layers"
![image](https://user-images.githubusercontent.com/55705669/120699158-f2fa3b00-c4a7-11eb-9976-1e8d44e19d74.png)

If that shows an unmanaged layer, then we would know!
![image](https://user-images.githubusercontent.com/55705669/120699234-0c9b8280-c4a8-11eb-8dea-b324eea860d3.png)

Could you check that and let me know if you see any unmanaged layers? If not, then the issue would be in the current release and I'll have to investigate on my side.

Thank you 
Manuela

**Comment by albertocaa1317** [comment]
I forgot indicate this in my last post. I don't have unmanaged layers:
![image](https://user-images.githubusercontent.com/57954993/120706924-fac2db00-c4b9-11eb-8bfd-1414f94fcf87.png)

**Comment by JeneferM-MSFT** [comment]
Do you see this scope in your flow? I believe you do not and you are using a version of the flow where we accidently shipped with our GUID hard coded (thats our GUID that is failing in your picture) 

If not, please upgrade to 2.1.6 which was released last week to see this resolved. 

![image](https://user-images.githubusercontent.com/62659043/121027914-94151a00-c764-11eb-86e0-48ea4c149cde.png)

**Comment by albertocaa1317** [comment]
Hi Manuela, Jenefer,

I re-imported the lastest solution and now I don't have this error.

**Comment by manuelap-msft** [comment]
Amazing, thank you so much for letting us know & thanks for using the CoE!
