### ISSUE TITLE
[CoE Starter Kit - BUG] Admin View Premium API Column not accurate

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5640]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team, 

When you expand the premium api column under the apps table in the admin which provides a true/false statement is not complement and is missing information. 

### Expected Behavior

Premium API column under the Apps table should be fully populated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

Admin View

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Open Admin View
Add Premium API Column.

**Comment by Jenefer-Monroe** [comment]
This field will not be filled for all app types. Canvas and custom pages will contain it though. Are you seeing data for those?

**Comment by nasilvae** [comment]
> This field will not be filled for all app types. Canvas and custom pages will contain it though. Are you seeing data for those?

I have for some but I have a lot of incomplete data. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/83104e76-2af8-4fd4-9aac-9553ff980ffa)

**Comment by Jenefer-Monroe** [comment]
Can you please try a full inventory run? 
Also, is this just something you found while testing or is this a field you are actively using?
