### ISSUE TITLE
[ALM Accelerator - QUESTION]ALM Accelerator Power Pages

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5642]
### What is your question?

Hi,

To deploy Power Pages, can we follow Model Driven apps pipeline? If not, what is the process?

Thank you!

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 19th 2023

**Comment by mikefactorial** [comment]
@lingutla123 have you looked at the documentation here? https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/configure-power-pages

**Comment by mikefactorial** [comment]
Closing this out for now unless there's a more specific question. Please read the docs before asking a question here.

**Comment by lingutla123** [comment]
Hi,

Thank you for quick reply! I did read the documentation, do we need to create yaml file per environment or it will be created by pipeline?
