### ISSUE TITLE
[CoE Starter Kit - BUG] Error Loading Control

### ISSUE THREAD

**Issue by ricov98** [microsoft/coe-starter-kit#5643]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

CoE Setup and Upgrade Wizard -> Pre-requisites -> Showing 'Error Loading Control' -> Minified React Error
![image](https://github.com/microsoft/coe-starter-kit/assets/134672486/2aff7af7-e4a6-457c-8fd8-b86dcace1b73)

### Expected Behavior

Should show the lsit of pre-requisites.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7.0

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Import the V4.7 of CoE Core.
![image](https://github.com/microsoft/coe-starter-kit/assets/134672486/24ff7311-dbe9-4c3f-9ef8-02009a203cf8)

3. Open the CoE Setup and Upgrade Wizard
4. Get errors 'Error loading control'
5. Turned on the Relevant workflow as per: [https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#troubleshooting](url)
6. Still get error 'Error loading control'

**Comment by manuelap-msft** [comment]
Can you check that these flows are on:

SetupWizard>GetCurrentEnvironment
SetupWizard>GetTenantID
SetupWizard>GetUserDetails

And if they are not, try turning them on manually and then return to the Setup Wizard.

**Comment by manuelap-msft** [comment]
Sorry I just saw you already tried that. Can you look at the runs of each of these flows to see if any of them failed?

**Comment by ricov98** [comment]
Hi @manuelap-msft, 

When looking at the run of all the flows, it looks like the GetUserDetails function didn't get run at all, whereas all the other flow successfully ran.

**Comment by manuelap-msft** [comment]
Are you in a commercial cloud tenant, or is your tenant GCC / GCC High / DoD (government cloud)? 

When you look at the flow details of the GetUserDetails flow, can you check the connection references are showing with a green tick and the HTTP with Azure AD reference points to https://graph.microsoft.com?
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/fb8f729c-dba5-4f0c-90ce-ed0210f09928)

This flow gets called directly from the app and doesn't have any other pre-requisites so I'm not sure why it would not be triggering. Can you expand the error of the custom page where it says show more details, does that give more info?

**Comment by ricov98** [comment]
Hi @manuelap-msft @Jenefer-Monroe 

1. It's turned on, and ss attached to show the green connection.
![image](https://github.com/microsoft/coe-starter-kit/assets/134672486/106bef85-5c5b-4c10-bd33-54421a8b69ed)

2. Commercial

Thank you.

**Comment by Jenefer-Monroe** [comment]
I'm just not sure then. I've not seen this issue before. You may have unmanaged layers on the app or page. 
You may just need to ignore that screen and use the rest of the setup wizard if possible.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
