### ISSUE TITLE
[CoE Starter Kit - BUG] App and Flow Inactivity Notifications Clean Up View

### ISSUE THREAD

**Issue by FQ365Microsoft** [microsoft/coe-starter-kit#5644]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

App and Flow Inactivity Notifications Clean Up View is not showing Enviornments name in the view. The data is present in the Dataverse but app is showing empty column. It was working fine before upgrade to 4.7

### Expected Behavior

It should show the environment name in the view.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

App and Flow Inactivity Notifications Clean Up View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Launch the app App and Flow Inactivity Notifications Clean Up View  and Environment name column is empty for all records.

### Anything else?

<img width="953" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/116768543/8fcc939c-0ab4-4e7f-b310-853b16f1dbd5">

**Comment by Jenefer-Monroe** [comment]
In the gov solution there is a table called Archive Approval. Please go there and see if the **_App Environment Name_** and **_App Name_** columns contains data, you may need to add the columns to the view. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/47838fca-200e-4108-8899-eca793481e3f)

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team
