### ISSUE TITLE
[ALM Accelerator - QUESTION] ALM Power Pages- Deployment profile

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5647]
### What is your question?

Hi,

Thank you for quick reply! I did read the documentation, do we need to create yaml file per environment or it will be created by pipeline?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 19th 2023

**Comment by mikefactorial** [comment]
@lingutla123 I may have lost the context for this question, but from what I can glean from the question you would supply a yaml file per environment. The idea is that there are specific settings to be applied in each environment that the power pages site is deployed. There's no way for the pipelines to generate that information without some specific customization to the pipelines.

**Comment by lingutla123** [comment]
Thank You.
