### ISSUE TITLE
[AA4AM]: No Environments showing when loading app 

### ISSUE THREAD

**Issue by NIhil1409** [microsoft/coe-starter-kit#565]
![Flow ALM Error](https://user-images.githubusercontent.com/82605803/120615053-c6b2d000-c44f-11eb-8c48-5ef4c96a5f8d.png)
![Installer Error](https://user-images.githubusercontent.com/82605803/120615056-c74b6680-c44f-11eb-8c5a-4f7500bc30eb.png)
![No Azure Devops Service Connection](https://user-images.githubusercontent.com/82605803/120615058-c74b6680-c44f-11eb-9346-a79be2ff14cb.jpg)
![No Environment shows](https://user-images.githubusercontent.com/82605803/120615059-c7e3fd00-c44f-11eb-809b-77b3d8097e55.jpg)

**Describe the bug**
When i load ALM Accelerator for Advanced Makers from solution. I am not able to see any environments also i am not able to see Azure Devops Service Connections. please see attached images 
**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution ALM Accelerator for Advanced Makers

 - App or Flow :- app(ALM Accelerator for Advanced Makers)

**To Reproduce**
1. Go to :- Pipeline in Azure Devops and run pipeline (deploy-validation-MyNewSolution)
2. Click on : Run Pipeline
4. See error:- please see attached 
@ALM4AM
**Expected behavior**
When i run the app it should should show all the environments and also i should see Azure Devops Service Connections.
**Screenshots**

**Additional context**

**Comment by mikefactorial** [comment]
@NIhil1409 You'll need to make sure that the user your are logged in to that app as has at least User permissions to the Service Connection.

![image](https://user-images.githubusercontent.com/42348035/120652012-5905a480-c44d-11eb-89bf-1948a9e4b75e.png)

**Comment by NIhil1409** [comment]
Hi Mike,

Thanks for quick reply.  i have already assigned Admin rights 

![image](https://user-images.githubusercontent.com/82605803/120652812-09889e00-c478-11eb-8d76-6ceb887d6c53.png)

**Comment by mikefactorial** [comment]
@NIhil1409 It looks like the name of the Service Connection is incorrect. The name of the service connection should be identical to the url of the environment. Per the note under step 5 here https://github.com/microsoft/coe-starter-kit/blob/main/ALMAcceleratorForAdvancedMakers/SETUPGUIDE.md#create-service-connections-for-devops-to-access-power-platform 

![image](https://user-images.githubusercontent.com/42348035/120655092-4e004380-c450-11eb-9991-2edc67d5142c.png)

**Comment by mikefactorial** [comment]
Example: 
![image](https://user-images.githubusercontent.com/42348035/120655280-8142d280-c450-11eb-8f07-4cabae956073.png)
