### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Management - question on cleaning up expired enviornments

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5650]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In https://learn.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt  , we have mentioned a flow diagram 
<img width="546" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/36a85157-c78b-40a5-a560-20101d730b28">

Flow diagram says, that when the environment is not expired ; email will be sent to developer to ask for extension ; however; the flow is getting all the expired environments and deleting them. 

Please suggest if missing something.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May

### What app or flow are you having the issue with?

Admin sync Template- V3

### What method are you using to get inventory and telemetry?

Cloud flows

AB#649

**Comment by Jenefer-Monroe** [comment]
Assigning to area owner
