### ISSUE TITLE
[CoE Starter Kit - Feature]: Release Wave Email Notification

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#5651]
### Is your feature request related to a problem? Please describe.

I wish to receive an alert in my email when a release wave post was added to the Command Center App. 

### Describe the solution you'd like

This is an idea of an extended feature of the Command Center.

**Comment by manuelap-msft** [comment]
Closing out as we don't have the necessary feed (e.g. API/rss) to provide notifications.
