### ISSUE TITLE
[CoE Starter Kit - BUG] Discrepancies between Power BI and Admin View MDA

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#5652]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I was going through the power bi report and Admin View MDA and I realized that they are showing different results regarding the "shared with" information of the apps.
MDA:
<img width="596" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/100951593/868625f5-a738-4ab8-a39f-2549b27eef7c">

Power BI:
<img width="596" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/100951593/cd18417e-d33e-462c-8068-31d936051d4e">

Even within the MDA it doesn't add up.
For example, it says the app in default environment was shared with 1 user and 1 group of 2 users, but the total shared is 4 instead of 3. The owner was already in the list, so it shouldn't be adding another one.
<img width="780" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/100951593/7c1d3c6b-7dbb-4c39-a6d1-4298df33b6a7">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

Power BI and MDA admin View

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Compare power bi with MDA in the shared apps columns.

### Anything else?

I'm just wondering which source is true, and this is causing doubts of the accuracy and veracity of the data presented in the MDA and Power BI report.

**Comment by Jenefer-Monroe** [comment]
Hello. The PBI and the MDA are reading from the same table so they should be the same. Have you refreshed the data in the PBI recently? Note that you can [configure scheduled refresh](https://learn.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh) to make sure PBI stays up to date.

**Comment by LizethRegules** [comment]
@Jenefer-Monroe 
I see the same numbers in the power bi and the MDA now. I published May's version of the report. Only 2 questions:
1. Was there an error on the data the power bi was bringing? For one of the apps in the tenant it went from shared with 180 users to 0. 
2. And within the MDA, could you possible add the column of shared with co-ownership and ownership. I have an app that says it is shared with 0 users and 0 groups, but then the total is 3, so it is confusing.
<img width="779" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/100951593/6d0f1057-981b-4f66-a719-8caea09181bc">

**Comment by Jenefer-Monroe** [comment]
I dont follow your request. Can you restate?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
