### ISSUE TITLE
Command Center Sync Flow Errors URL Format for GCC Customers

### ISSUE THREAD

**Issue by VA-smcvey** [microsoft/coe-starter-kit#5654]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Command Center Sync Flow Errors utility has a URL to lead to the Power Automate failed run.  The formated URL points to Power Automate Commercial, i.e. https://make.powerautomate.com.  For GCC Customers, the URL root should be https://make.gov.powerautomate.us.

### Expected Behavior

The Command Center Sync Flow Errors utility error URL should have a root URL that corresponds to the customer's tenant. e.g. Commercial, GCC-Moderate, GCC-High, DoD

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Command Center Sync Flow Errors utility

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open Command Center Sync Flow Errors utility from a GCC tenant.
2. Click on the error URL

**Comment by Jenefer-Monroe** [comment]
Hello. Did you use the setup wizard to install?

**Comment by VA-smcvey** [comment]
My apologies.  That was the issue.  I ran thru the wizard with the upgrade but apparently miss setting that this round.

**Comment by Jenefer-Monroe** [comment]
oh good. I've got a local fix for June that will mean you dont need to reset this on every upgrade. YEAH!
