### ISSUE TITLE
[CoE Starter Kit - BUG] Inactivity Setup Wizard does not save the exemption value in Power Platform Admin view as well don't retain on setup wizard as well

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5659]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Inactivity setup wizard 
Before setting Exemption

<img width="1039" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/18561fd9-a3fb-4e67-b4a9-7e406c730889">

After setting Exemption

<img width="1049" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/c5e15e4b-1ff1-4e83-8631-3a5802ab51d2">

Turned on the flows 

<img width="956" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/b8d423fd-e007-4745-8135-8d9e42e7671f">

Power Platform Admin View 
<img width="830" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/3bb28ceb-4628-489e-b784-6aa5593579b2">

Went back to setup wizard , selected more features, selected  configure inactivity process and the settings are not saved

<img width="1040" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/745f55f2-665a-487a-93e7-9381473e0c45">

### Expected Behavior

The exemption settings should get saved , because of this issue we are not able to exempt the environments for testing

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

May

### What app or flow are you having the issue with?

Governance solution

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Provided above

**Comment by Jenefer-Monroe** [comment]
Hello. This one is tracked via https://github.com/microsoft/coe-starter-kit/issues/5509 and local fixed for June. 
thank you
