### ISSUE TITLE
[PRODUCT BUG]: Cannot update environment variables in Dataverse for Teams CoE

### ISSUE THREAD

**Issue by SteveO-32732** [microsoft/coe-starter-kit#566]
**Describe the bug**
Cannot update environment variables in Dataverse for Teams CoE

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution all of them
 - Version [various]
 - Environment variables

**To Reproduce**
1. Go to 'Flow.microsoft.com'
2. Select Dataverse for Teams environment
3. Go to solutions (no default solution exists)
4. Open solution  - There is no option to set current value.
![image](https://user-images.githubusercontent.com/85085775/120482936-a0256400-c37f-11eb-8820-8999a004740d.png)

**Expected behavior**
I need to know how to update environment variables in Dataverse for Teams.  I can't find anything in the documentation.

**Screenshots**

**Additional context**

**Comment by Jodarcy1** [comment]
We are also not able to update the environment variables.  Also we cannot see the default environment while installing Dataverse for Teams COE with version no. 1.998.

<img width="651" alt="nodefault" src="https://user-images.githubusercontent.com/45642255/121715186-93ee8480-caac-11eb-996e-1196b0892b82.PNG">

**Comment by krishnaVSU2020** [comment]
Hi Team,

I also don't see the default solution in my old instance to update Environment variables:
![image](https://user-images.githubusercontent.com/70860420/121715310-b4b6da00-caac-11eb-9002-94db8e18cc38.png)
Not sure it is COE issue or change at Power Platform level.Because, I have installed COE 2 months back. Kindly help me to update the Environment variables

**Comment by manuelap-msft** [comment]
there is a limitation / issue with how this currently works in Dataverse for Teams, that the Engineering team is looking at. In the meantime, the below steps should unblock you:

1. Go to flow.microsoft.com
2. Select your Dataverse for Teams environment
3. Select Solution
4. Select Common Data Service Default Solution
5. Select + Add > Environment Variables
6. Select the existing Environment Variables from the managed solution that you want to update
7. After adding those, selected Environment Variables in the new menu navigation and you should then be able to add a default and current value

Closing as this is a Product issue, which we can't influence.
