### ISSUE TITLE
[CoE Starter Kit - QUESTION] Azure Devops Pushed resources are recognized as orphaned

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5660]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 
We have a situation with one of our customers, where there Azure Devops pushed resources have no owners and all the resources are identified as orphaned by CoE and the same resources are also identified as orphaned by MC552235. May be from CoE side we can turn off the flows from below setup wizard. But that will stop us identify the actual orphaned resources and help them to clean up. So, we thought, would it be good idea , if we can get the exemption feature on this setup wizard as well. Please suggest.

<img width="1003" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/37ef042a-53d3-44c3-aea1-cd96691b5ca5">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

May

### What app or flow are you having the issue with?

CleanUp Old Objects App

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
What type of users are these? Are they service principles?

**Comment by PPMini** [comment]
Yes, service principles

**Comment by Jenefer-Monroe** [comment]
We do handle service principles with our orphan processes already so I'm a little confused. 
And I dont know what this is: **_orphaned by MC552235._** 

Please see here this are service principle owned apps and they do not get flagged as orphaned.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dc63b1d4-a0b5-448f-872b-8baca157e25e)

Can you please show me more specifically what problem you are seeing?

**Comment by PPMini** [comment]
Sure Jenefer, will try to get more details on this, MC552235 is a message center ID. I raised issue #5565 to understand how CoE is supporting this. Thanks for your support.

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team
