### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - cannot locate Flows "Request Orphaned Objects Reassigned"

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#5661]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to set this up
https://learn.microsoft.com/en-us/power-platform/guidance/coe/governance-components#request-orphaned-objects-reassigned-child

I cannot see the Flows "Request Orphaned Objects Reassigned" Child and Parent - do they have a different name ?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.8.1

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team
