### ISSUE TITLE
[CoE Starter Kit - QUESTION] Nurture- Maker App - Solution Assessment

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#5662]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Nurture Maker App - solution assessment page is not showing any steps like Data, test category , Audience , support  like below as mentioned in the documentation: https://learn.microsoft.com/en-us/power-platform/guidance/coe/nurture-components

<img width="566" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/be6404f2-c4f9-41f4-98fe-6a3f71874226">

May version of Nurture Maker App is showing below:
<img width="984" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/17652787-e7a6-47fc-b9a6-650e5d587724">

And on Next : 

<img width="740" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/933e3589-c6d9-4b07-8dcb-60694af4a77e">

Please provide clarity around this. 

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

May

### What app or flow are you having the issue with?

Nurture 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Did you add the starter data?
https://learn.microsoft.com/power-platform/guidance/coe/setup-nurture-components#import-starter-data-set-for-the-maker-assessment-app

**Comment by PPMini** [comment]
Hey Jenefer, yes, I figured out this morning. Apologies missed to let you know. we are good and closing this.
