### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Audit Logs | Office 365 Management API Subscription failing

### ISSUE THREAD

**Issue by RakeshShhh** [microsoft/coe-starter-kit#5670]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team, we have just upgraded CoE core components from Feb release to May Release (4.8) and trying to start subscription for Audit Log Flow "  Admin | Audit Logs | Office 365 Management API Subscription ". However, it is failing with error 401, error message is: 

  "error": {
    "code": "AF10001",
    "message": "The permission set () sent in the request does not include the expected permission."
  }
}

We can confirm, same Client ID and Client Secret working fine in Audit Log using a custom connector module. Please advise.

### Expected Behavior

Subscription should have started.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

 Admin | Audit Logs | Office 365 Management API Subscription failing

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
The API Permission needs to be type application not Delegated. So that has changed from when it was used in the custom connector. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/32b53887-edf6-43b0-8c2b-1d456f3e6f29)

**Comment by Jenefer-Monroe** [comment]
And the first failure you show from the flow is a caught failure indicating that your secret is stored directly in the env var rather than in Azure Key Vault. 

Hope that helps.

**Comment by RakeshShhh** [comment]
Many Thanks for your promptness, seems like missed that step. Should have highlighted in Yellow :)

**Comment by Jenefer-Monroe** [comment]
Glad you are unblocked. I'll go ahead and close but please let us know if you have other questions.

**Comment by goldiagrawal10** [comment]
I have the same problem and I tried disabling and enabling flow but it is still same issue. It says Action 'Get_Azure_Secret' failed. As per the article, I have put value for Audit Logs - ClientID and Audit Logs - Client Secret but not Audit Logs - Client Azure Secret because I am staying Client secret in plain text. 

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

{
  "error": {
    "code": "0x80040216",
    "message": "Error occured while reading secret: Value cannot be null.\r\nParameter name: input"
  }
}

**Comment by AkshayKathuria06** [comment]
My org isn't allowing us to set up this app using application permissions and instead want to set this up as delegated permissions.
What tweaks would I need to do in order to consume this using delegated permission?
