### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inactivity Notification Process

### ISSUE THREAD

**Issue by dksamo1986** [microsoft/coe-starter-kit#5672]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

Does the Inactivity notification process include quarantined apps in the process? 

We have made the decision to send the unanswered apps and flows due to inactivity to the admin and then we would quarantined those apps and take it from there. 

I just cannot see in the flow if it will keep sending an inactivity notification if the app has been quarantined. 

Best regards,

Sabri

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.6

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
No, quarantine is not considered in the processes. You can see a nice process flow of what is considered in our documentation here. Hope that helps

[Admin | Inactivity notifications v2 (Start Approval for Apps)](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#admin--inactivity-notifications-v2-start-approval-for-apps)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2cd1fbd1-d460-43eb-a13a-bdd2d77ac768)

**Comment by dksamo1986** [comment]
Hi Jenefer,

Thank you for the process flow. 

Just so it's 100% clear, if a app is quarantined, but has not been launched or modified in the last 6 month or is not excused from the process, they will still get an inactivity notification?

Best regards,

Sabri Moussi

**Comment by dksamo1986** [comment]
Okay - thank you.

**Comment by Jenefer-Monroe** [comment]
You are most welcome!
