### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inactivity flow is not sending deletion approval request emails

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5676]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I installed the May 2023 release (and the "CoE Starter Kit Core Components (Hotfix 1) - May 2023") into a Test environment.

I ran the "CoE Setup and Upgrade Wizard" and configured the "Inactivity Processes".

I set the "ProductionEnvironment" variable to "No", since I do not want users to be notified during my testing.

I configured the environment variables "InactivityNotifications-PastTime-Interval" and "InactivityNotifications-PastTime-Unit" so that apps and flows that haven't been modified in 45 days are considered inactive.

However, I did not get an "app deletion approval request" email for an app that I use for testing (that hasn't been modified in 2 months.

The owner of this test app is my regular user account, and it was created in the default environment.

I looked in the "App and Flow Inactivity Notifications Clean Up View" app, and I see an entry that was created for the app.

![1-Untitled picture](https://github.com/microsoft/coe-starter-kit/assets/128085471/65ebb39d-b7c4-4373-8885-699beafd4112)

For my other testing, emails have been delivered to my Admin account's Inbox.

I have also configured these "app deletion approval request" emails to be CC'ed to my shared mailbox.
It didn't appear there either.

I went into my Test environment, Solutions, "Center of Excellence - Governance Components", Cloud Flows, "Admin | Inactivity notifications v2 (Start Approval for Apps)"

I can see that the flow succeeded.

![2-Untitled picture](https://github.com/microsoft/coe-starter-kit/assets/128085471/c43776d3-e3fa-4d89-9dc1-820da38bcd71)

I'm not sure why the "app deletion approval request" emails are not being sent out/delivered.
And I don't know where to troubleshoot next.
Any suggestions?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I think you are saying the approval mail itself correct? The mail that includes the buttons to accept or reject deletion. 
If so, please let me know, what do you have configured for this env var? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/057c00cf-b217-4165-b411-ffc099b53106)

**Comment by firefox-edge123** [comment]
Yes, I am referring to the inactivity approval mail (The mail that includes the buttons to accept or reject deletion.)

I checked the  "Individual Admin" variable and realized it was set to the non-routable email address of my Admin account. I have switched it to the routable email address of my Admin account, but my regular user account mailbox still doesn't get the "approval mail" after I manually ran the "Admin | Inactivity notifications v2 (Start Approval for Apps)" flow. 

If I look in the "App and Flow Inactivity Notificaitons Clean Up" app, I can see a new entry there.

![Untitled picture](https://github.com/microsoft/coe-starter-kit/assets/128085471/6ac06481-d605-472e-840a-27579b971b12)

**Comment by Jenefer-Monroe** [comment]
Great news. That was certainly the issue then.

**Comment by firefox-edge123** [comment]
I probably wasn't clear in my previous response (my apologies), but the issue actually is Not resolved yet.

After I manually ran the "Admin | Inactivity notifications v2 (Start Approval for Apps)" flow again,
I can see the entry in the "App and Flow Inactivity Notifications Clean Up" app but I do Not get the inactivity approval mail (The mail that includes the buttons to accept or reject deletion.)

Do you have additional suggestions on where I can troubleshoot next?

**Comment by Jenefer-Monroe** [comment]
Find a test case, one where you expect it to send you an approval and note its id (its appid or flowid). 
Go to the latest run of **_Admin | Inactivity notifications v2_** (Start Approval for Apps) (assuming its an app, else go to the flow one)
Look in the download for this action and find your app / flow. Note its index in the array (and note if your array starts at 0 or 1 to know for sure where to find it in the flow run)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7b3b847f-c046-4f91-b681-a4446f8d25c6)

In the loop, first look at the output of AppLink to make sure you have the correct app. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/61e02833-740e-417c-b2af-eb76f90755f0)

If you found it, follow the path downword, does it land at the create approval? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/10ec3933-4e33-4165-acb4-2159ffe4e0fb)

**Comment by firefox-edge123** [comment]
I found the test case you suggested. But it shows that the flow ran successfully here. (See screenshot), but I never got the inactivity approval mail (The mail that includes the buttons to accept or reject deletion.)

Is there a specific part of the "Create an approval" output that I should look under to see an error code or something?

![inactive-app-email-not-sent](https://github.com/microsoft/coe-starter-kit/assets/128085471/0770dc28-de59-4d00-b46c-ad36eee483a0)

**Comment by Jenefer-Monroe** [comment]
Please expand this action
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6d0547a4-4311-4839-bd19-c42fa52da06c)
 
What do you see?

**Comment by firefox-edge123** [comment]
For INPUTS, here is what I see.


![inputs](https://github.com/microsoft/coe-starter-kit/assets/128085471/f9964296-b2a8-4c0e-b1e3-6241c02040f5)


![inputs-details](https://github.com/microsoft/coe-starter-kit/assets/128085471/6bb5528a-e9b3-4342-a4b7-64516cddacc4)


--

For OUTPUTS, here is what I see.
(Let me know if you wish to see the "Body" section of OUTPUTS.)


![outputs](https://github.com/microsoft/coe-starter-kit/assets/128085471/87cf2d3e-f68e-441f-b9c1-334fe532229a)


![outputs-details](https://github.com/microsoft/coe-starter-kit/assets/128085471/b0baff81-ebb3-4290-8763-923868b1aa70)

**Comment by Jenefer-Monroe** [comment]
and who is here? is it the identity you expected? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc2aabf6-1d73-4dc3-aaed-632e8f30edb8)

**Comment by firefox-edge123** [comment]
That's the email address of my admin account. 


And yes, this is the identity I expected.
Since this is my testing environment, I had set the "ProductionEnvironment" variable to "No" so that my Admin account gets the Inactivity notification emails instead of the users/makers.
Unfortunately, those inactivity emails are not getting delivered.

This identity is a user/person.

**Comment by Jenefer-Monroe** [comment]
ok. Unfortunately it appears you have hit some product issue then. The flow is noting that is successfully sent the approval to that identity.  Have you checked your spam folders?

**Comment by firefox-edge123** [comment]
The missing emails are not in the Junk folder. I upgraded my COE kit in my Test environment to the June 2023 release, but those emails are still not getting delivered. I will do some more troubleshooting next week.
