### ISSUE TITLE
Free up the capacity of the environment space

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#5677]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Everyone,
AM sorry to raise this question again but it didn't worked for me. I tried the methods of removing the emails and attachments and notes and other methods to free up the space but nothing seems to work. 

I tried the below steps using the statements given in that but still nothing worked.

If you're not sure what takes up the most space, check here:
https://github.com/microsoft/coe-starter-kit/issues/5426#issuecomment-1534332523

These are the details what I see in my environment:
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/4890e630-25c2-4c5a-89fb-66065ea56ecf)

Please let me know if I can use some other methods to remove unwanted data.

Thanks in advance.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

none of the tables you are showing here are tables of the CoE kit - all CoE kit tables have a prefix of admin_. So I'm not sure what's taking up capacity in your environment, but it doesn't look like it's related to the CoE kit. Most of your capacity seems to be taken up by file usage, and the only files the CoE kit ships are icons / javascript web resources which shouldn't take up a lot of space, in our tenant this takes up about 500 MB, it looks like in yours it's taken up 2.5GB. I'm not sure where that is coming from, but I don't think it's the CoE kit. 

Sorry I don't think we can be of further assistance here,
Manuela

**Comment by Neel1KNK** [comment]
Thanks for the update,

The thing is like we have only COE installed in this environment and no even a single flow we have created here.

It's only dedicated for COE. The file usage shows up for the webresource base which is the highest consuming capacity.

**Comment by Jenefer-Monroe** [comment]
Unfortunately there must be something else getting written as none of those are ours. 
Can you share a screenshot with what solutions are installed in this environment? 
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Jenefer-Monroe** [comment]
I believe its something from your expansion solution then. The ones by BSX.

**Comment by Neel1KNK** [comment]
Am sorry if you are talking about this solutions it has only one flow and one app.
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/2b1a1972-92a8-4195-8a6b-61de242e087d)

We have not even using them anywhere and they are testing app & flow.

**Comment by Jenefer-Monroe** [comment]
OK, Regardless of that guess being correct, the objects consuming file space are not ours. We have no such utility. You may need to contact product support to get assistance

**Comment by Neel1KNK** [comment]
Thanks for your update.

Could you please share the documents so that we can come across and see which or what is occupying the database capacity.

and, we can close the ticket.

Thanks again for your support.

**Comment by Jenefer-Monroe** [comment]
What documents are you looking for?

**Comment by Neel1KNK** [comment]
how to remove the unwanted data from dataverse for COE. I have COE in 2 different tenants and the other one is also occupying more data capacity. Like which table is occupying more data capacity.

I tried those bulk removal methods but couldn't help that.

**Comment by Jenefer-Monroe** [comment]
I'm afraid we dont have any documentation aside from the generalized product documentation that Manuela shared. 
Here is a link to her response again https://github.com/microsoft/coe-starter-kit/issues/5521#issuecomment-1545803978

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team
