### ISSUE TITLE
[CoE Starter Kit - BUG] Update Flow Record missing MakerID

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#5678]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Admin Sync Termplates V3 (Flows) is showing the error message "message": "The supplied reference link -- admin_makers() -- is invalid. Expecting a reference link of the form /entityset(key)." as part of the 'Update Flow Record' under the Upsert Flow Details Scope. 

Looking at the failed run and focussing on teh 'Get Flows and store them in CoE CDS Entity' scope, within the apply to each there is a 'Get Flow from CoE', for this particular flow there is no admin_derivedowner. 
<img width="294" alt="ErrorOneCOE" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/f2030fb1-446e-42c4-ba76-ed84f59d02a4">

It then proceeds to the Get Update Flow Owner step. As the FlowOwner ID is null it proceed to the Maker Check - Derived Owner step (see below) where it gets the Creator Object ID. 

<img width="589" alt="ErrorTwoCOE" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/4f06e23d-6a4c-4538-b31e-555d7cb6e3a6">

The userisorphan is set to 'true' so it then goes to the Upsert Flow Details step (see below)

<img width="658" alt="errorthreecoe" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/62014583-8dea-4230-a710-7378ffac7ae6">

I am assuming the MakerID should not be blank at this point? The FlowOwnerID at this point is blank, hence the MakerID being blank. 

Should the FlowOwnerID by set by the Maker Check -Derived Owner User ID? Otherwise there is nothing writing to the FlowOwnerID and it will remain blank. 

<img width="490" alt="errorfourcoe" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/e3f90916-dedb-4a17-934c-8e6bc39a86fe">

I have checked the flow in question through the Power Platform Admin View and there is no derived Owner. 

<img width="420" alt="errorfivecoe" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/76425e16-2ac7-431c-a9f7-36459ed82eb7">

Perhaps related and not sure if useful, but the flows in question started to fail recently and required reauthenticating the actions in the flow itself. Error below
Error from token exchange: Bad Key authorization token. Token must be a valid JWT signed with HS256
Failed to validate token: IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.

Thanks

### Expected Behavior

See issue with screen shots. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Admin - Sync Template V3 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We have new flows for this now and they do this check a little differently (aka better). From looking at your case and what we do now, I think it woudl now just send in the creator id to maker check instead of the blank as above. 
Can you validate, does your flow return something for creator? 
If you call Get Flow as Admin with the envt name and flow id
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/abc69ce0-90af-4bac-8d46-b777f1f20b1b)

It would come back as 'Get_Flow_as_Admin')?['body/properties/creator/objectId']
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/53042c34-ffce-4668-bf7a-62678b66493e)

**Comment by G1982C** [comment]
Thanks Jenefer. Correct it does return values for the creator. See below

<img width="169" alt="coe5" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/2b3bfa93-89b2-4115-bcfc-36c0b689e669">

**Comment by Jenefer-Monroe** [comment]
Good news. Then I do believe the new v4 version of the apps released in May will no longer repro this issue for you.

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team
