### ISSUE TITLE
[CoE Starter Kit - QUESTION] Microsoft Power Platform self-service analytics to export Power Platform inventory

### ISSUE THREAD

**Issue by RakeshShhh** [microsoft/coe-starter-kit#5686]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,

We are planning to use this feature, however as mentioned in "Azure Data Lake Storage Gen2 configurations" it requires storage account to be accessible through Public IP.

In our organization , Azure storage access from Public IP is blocked, is there any consideration in future to make some other alternatives as well? Please advise

The following Azure Data Lake Storage Gen2 configurations are supported for this preview feature:

Storage Account Types: Standard general-purpose v2 or Premium block blobs.
Hierarchical Namespace: Enable hierarchical namespace must be selected.
Network Connectivity, Network Access: Enable public access from all networks must be selected.
Network Routing, Routing Preference: Microsoft network routing is recommended.
Security: Require secure transfer for REST API operations must be selected.

Regards,
-Rakesh

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid this is a product feature that we just consume. And as a very small team cannot scale to providing product support. You will need to reach out to product support with these questions, or the general product community.

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team

**Comment by CharuChawla** [comment]
I have created a storage account which have data in Blob Containers. But when I am trying to configure the Datasources in the  dataflows it's throwing error that path doesn't exist. Can someone please help what is missing from my side?
