### ISSUE TITLE
[ALM Accelerator - BUG]: exportAndDeleteUnmanaged pipeline fails if delete takes more than 4 minutes

### ISSUE THREAD

**Issue by sefa-phaag** [microsoft/coe-starter-kit#5693]
### Describe the issue

If deleting the managed solution takes longer than 4 minutes, the pipeline fails even if the delete ultimately succeeds. This is because the default timeout for pac solution delete is 4 minutes and it doesn't appear to have a timeout or async option like other pac solution methods, although perhaps there is a workaround similar to the one outlined [here](https://www.develop1.net/public/post/2021/05/19/increase-timeout-for-pac-pcf-push).

### Expected Behavior

The pipeline should only fail if the solution truly fails to delete.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

May 2023

### Steps To Reproduce

1. In the canvas app, attempt to delete a moderately complex solution

### Anything else?

Full log:
```PowerShell

[ '' ]
##[error]error: 1
##[error]failed: Connected to... SEFA Dev 3
Connected as ***

Deleting Dataverse Solution...
Microsoft PowerPlatform CLI
Version: 1.23.3+ga05f0df

Error: The request channel timed out while waiting for a reply after 00:04:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
    The HTTP request to 'https://sefa-dev-3.crm.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.49.3165' has exceeded the allotted timeout of 00:04:00. The time allotted to this operation may have been a portion of a longer timeout.
        The operation has timed out


Usage: pac solution delete --solution-name

  --solution-name             Name of the solution (alias: -sn)

[ 'Authentication profiles and token cache removed' ]
[ 'The Clear Authentication Result: Authentication profiles and token cache removed' ]
##[error]Error: Connected to... SEFA Dev 3
Connected as ***

Deleting Dataverse Solution...
Microsoft PowerPlatform CLI
Version: 1.23.3+ga05f0df

Error: The request channel timed out while waiting for a reply after 00:04:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
    The HTTP request to 'https://sefa-dev-3.crm.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.49.3165' has exceeded the allotted timeout of 00:04:00. The time allotted to this operation may have been a portion of a longer timeout.
        The operation has timed out


Usage: pac solution delete --solution-name

  --solution-name             Name of the solution (alias: -sn)

Finishing: Power Platform Delete Managed Solution
```

**Comment by mikefactorial** [comment]
@sefa-phaag pardon the delayed response. Will look into a possible solution here.

**Comment by RajeevPentyala** [comment]
@sefa-phaag The error was thrown by the pac CLI. I have logged an [issue](https://github.com/microsoft/powerplatform-vscode/issues/608) to address this error.

**Comment by RajeevPentyala** [comment]
@sefa-phaag n the latest pac version, the default timeout has been increased from 4 minutes to 30. For more details, refer [https://github.com/microsoft/powerplatform-vscode/issues/608](url) .Please feel free to reopen the issue if any further questions.
