### ISSUE TITLE
[CoE Starter Kit - QUESTION] Removing Command Center - Client Azure Secret Env Variable value

### ISSUE THREAD

**Issue by robertfinkley** [microsoft/coe-starter-kit#5694]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, I'm attempting to go through the update process and found some issues with our CoE setup. We are not using the Command Center - Client Azure Secret Env Variable. 

When I try to remove the value for that env variable using the Admin Command Center, I get the following error and the value returns.

![image](https://github.com/microsoft/coe-starter-kit/assets/116120866/380314e7-490d-41e6-940e-52e4687fa8f8)

Am I doing something wrong?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Azure secret type env vars cannot be managed in the command center as they are stored differently. You will need to removd directly from the product. 

Here is an article on how to [use Azure Key Vault secrets](https://learn.microsoft.com/power-apps/maker/data-platform/environmentvariables#use-azure-key-vault-secrets-preview)

And to delete them from the environment you go to the default solution
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d4723302-35cf-4ed3-be86-caaacb7a83b7)

Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as  no further action for starter kit team
