### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Miled122** [microsoft/coe-starter-kit#5695]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The CoE Starter Kit requires access to your tenant's Power Platform environments. Therefore, the identity you set up the CoE Starter Kit requires admin privileges and licenses. Please confirm your account meets the prerequisites before continuing:

Power Apps User (non-trial) licence               Fail
Power Automate Per User (non-trial) licence   Fail

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

Center of excellence setuo wizard

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry we will need a little more context in order to assist. Are you saying you have the correct license and the setup wizard is not displaying them?

**Comment by Miled122** [comment]
I want to launch COE setup and Upgrade Wizard, I have the powerapps for office 365(plan3) and power automate for office 365 licenses and I have the messages:
Power Apps User (non-trial) licence Fail
Power Automate Per User (non-trial) licence Fail

**Comment by Miled122** [comment]
Hi,

I want to launch COE setup and Upgrade Wizard, I have the powerapps for office 365(plan3) and power automate for office 365 licenses and I have the messages:
Power Apps User (non-trial) licence Fail
Power Automate Per User (non-trial) licence Fail

***@***.***

***@***.***

De : Jenefer Monroe ***@***.******@***.***>
Envoyé : jeudi 1 juin 2023 08:57
À : microsoft/coe-starter-kit ***@***.***>
Cc : Jami Miled (Externe) ***@***.***>; Author ***@***.***>
Objet : [EXTERNE] - Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #5695)

ATTENTION : CE COURRIEL PROVIENT DE L'EXTÉRIEUR DE REVENU QUÉBEC
Soyez vigilant avec les liens et pièces jointes et ne transmettez jamais des informations confidentielles si vous ne connaissez pas l'expéditeur du courriel.

Hello. Sorry we will need a little more context in order to assist. Are you saying you have the correct license and the setup wizard is not displaying them?

**Comment by Jenefer-Monroe** [comment]
That page reads the license types from Azure, and then proceeds. It sounds like you might not have the correct licenses permanently assigned to the user you are using to setup the CoE. 
If you think thats incorrect and that you do have the correct type, then you can ignore and proceed. You will not be able to turn on most of the flows with an incorrect license type so you will know at that point if it was an issue with our reporting or with your license.
Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
