### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by autoDude** [microsoft/coe-starter-kit#5696]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi guys,

we installed the CoE starter kit with the required setup. Somehow we are not able to publish the BI report and we got the error message that it depends on BI licences. That's strange because our service account has an E5 licence and the workspace is a premium one. Any idea?

<img width="958" alt="MicrosoftTeams-image (1)" src="https://github.com/microsoft/coe-starter-kit/assets/123499790/6016438d-27d4-4a2d-b808-17aedab48d0e">
`
Thanks

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

**Comment by DominicMeznik** [comment]
The Power BI license is included in the E5 but it also has to be enabled for the user. Also you could check if you´re logged in with the correct account.

**Comment by Jenefer-Monroe** [comment]
Thanks for the help Dominic!

**Comment by autoDude** [comment]
It was not a licence issue. We checked it already but thanks for the tip @DominicMeznik. We never logged in at office.com with the service account and we opened directly Power BI. We guess that it is required to login initially at office.com. After it we were able to publish it. Weird issue xd

**Comment by Jenefer-Monroe** [comment]
oh gosh, thank you for sharing that tip! It takes a community to raise a CoE Starter Kit! 
I will go ahead and close then. Please let us know if you have other questions in the future!
