### ISSUE TITLE
"The term 'Get-CrmConnection' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify  that the path is correct and try again"

### ISSUE THREAD

**Issue by Faranakt** [microsoft/coe-starter-kit#5697]
Getting this issue when we try to run Powershell tasks in DevOps. It was working until an hour ago .. now is broken!

**Comment by mikefactorial** [comment]
@Faranakt I'm going to close this out for now since I haven't heard back. Feel free to reopen if it's still an issue.

**Comment by Faranakt** [comment]
This issue was resolved by changing the agent against the pipeline, it stopped failing when I changed the agent to "Windows-latest"

**Comment by mikefactorial** [comment]
Interesting 🤔... thanks for the update @Faranakt

**Comment by Faranakt** [comment]
> Interesting 🤔... thanks for the update @Faranakt

Which makes sense and it wasn't the first time, basically, the VM running in the background might be going through an update etc, and doesn't have a ref to that Powershell library .. we have experienced this before but thought I reply to my post as I am sure it will happen again and hopefully this will help someone out there on a deployment day :)
