### ISSUE TITLE
[CoE Starter Kit - QUESTION] Customized email

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#5698]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

1. If I modify customized email message body it will stay customized after CoE upgrade? F.E this one:

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/9e1425a1-488a-4915-9b9f-1f98bbd32c39)

2. From Dataverse table I created my custom one customized email row and I am considering if it won't be deleted after CoE upgrade?

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/404cca29-4d2a-4811-b096-491dbf06de32)

3. Why for custom row i don't have same body editor as in default one. Could id be some how turned on?

My custom row body editor (tools on the top missing)

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/0401277c-1d70-429d-9d76-2457faf11c0b)

Default body editor

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/990b2cf3-f389-47a1-aed1-1eef06d99274)

Regards

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

Customized emails

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Customized emails from us wlll persist the changes you make in them in our app, yes. However, the tooling is not set up to support custom rows, meaning new mails created by you, and these would be removed on upgrade. This is so that we can remove mails we remove from the system.

**Comment by BartoszKaminski1999** [comment]
So in summary, if we make changes to the body message for messages that are already in CoE, for example "Welcome Message", even after CoE Upgrade they will remain with our modification. But by creating our custom rows into customized emails, they will be removed during the upgrade. That's true?

**Comment by Jenefer-Monroe** [comment]
Thats correct.

**Comment by Jenefer-Monroe** [comment]
You are most welcome!

**Comment by Yocomd** [comment]
@Jenefer-Monroe, could you tell me how the system knows not to overwrite modifications to an email that we customized?  I had a custom email record set up for the Welcome email because in the past it WAS overwritten by the configure emails flow.  But I just got bit today because I upgraded and it deleted my custom email record.

**Comment by Jenefer-Monroe** [comment]
The table will not store custom records from others. We only support customizations of the emails we ship. 

There are columns we use to denote if the subject / body are modified. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0012ed77-7f8e-48c6-8ac3-e6079c862e02)

If you use the Command Center to edit the mails you will be able to see that as shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4607228d-1e5b-4968-adb3-55642909ef9a)
