### ISSUE TITLE
Action 'Parse_JSON' failed

### ISSUE THREAD

**Issue by tsegato** [microsoft/coe-starter-kit#57]
I get following error. Any pointer on how to fix this?

![image](https://user-images.githubusercontent.com/43033640/110121905-4254a080-7dbf-11eb-9ad1-9894cb796f76.png)

**Comment by devkeydet** [comment]
Sorry about the confusion, but this repo is the future home of the CoE Starter Kit. That transition hasn't happened yet. We tried to make that clear in the readme.md. Until the transition is complete, would you please ask here:
https://github.com/microsoft/powerapps-tools/issues
