### ISSUE TITLE
[ALM Accelerator - QUESTION] ALM Accelerator for Power Platform

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5704]
### What is your question?

Hi Mike,

When i open "COFIGURE DEPLOYMENT SETTINGS" in ALM Accelerator for Power Platform   getting below error.

Error reading environment configuration: SearchAADGroups.Run failed: { "error": { "code": 502, "source": "power-apis-usgov001-public.azure-apihub.us", "clientRequestId": "7f608c2c-886d-4dd4-bc87-8a63d0cf1071", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not receive a response from an upstream server. Request tracking id '08585159627960619595815670681CU01'." } } } }

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/84aace80-d3e2-41b2-b6fa-fcc57fefa000)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 19th 2023

**Comment by mikefactorial** [comment]
@lingutla123 that flow uses the HTTP with Azure AD connector to search Groups in Azure active directory. Based on the error there's some issue with communication between the flow and AAD. Since it's hitting a usgov endpoint it's more than likely a permissions or tenant level issue that's restricting your user from accessing AAD Groups. Are you able to log into the Azure Portal and see a list of AAD Groups in the same tenant as your PowerApps environment?

**Comment by lingutla123** [comment]
Thank you! Able to see AAD groups in same tenant of Power Apps environment. And also, the HTTP with Azure AD connector is showing successful in connections.

The Seach AAD flow is showing below error.
BaseResourceUri (https://manage-gcc.office.com) must be a base of the full url (https://graph.microsoft.com/v1.0/groups?$select=id,displayName&$top=999).
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/e90771aa-3635-4670-89f7-040895894c5a)

**Comment by mikefactorial** [comment]
@lingutla123 in GCC you may need to change the Base Resource URL and Azure AD Resource URI of the connection for the HTTP with Azure AD connection. Try deleting the existing connection and when prompted try entering (https://manage-gcc.office.com/) as the error states. Unfortunately, we don't have GCC environments to validate this in so this could cause other side-effects, but the error is specifically stating that there's a mismatch between the actual endpoint and the url entered for the Base Resource URL and Azure AD Resource URI.

**Comment by lingutla123** [comment]
Hi Mike,

I tried but still showing same error.

**Comment by lingutla123** [comment]
Hi Mike,

Created a test flow using the Base Resource URL in COE test env and shared the flow with my Manager. 
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/ca3fd5ea-0f55-4d67-9aee-3c396f9ab02a)

My Manager can run flow successfully. But when i try to run the same flow it is failing. We both have same permissions. Why it is happening?

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/f5eca79a-f34d-4b54-beff-02e6dcfa4f90)

**Comment by lingutla123** [comment]
I fixed the issue. I am not getting the error

**Comment by lingutla123** [comment]
Hi Mike,

 I changed Base Resource URL and Azure Resource URI to https//graph.microsoft.com. Before also i tried it didn't work. Yesterday i tried again it worked. 
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/40c97147-80e9-4d14-83a3-53657a94f705)
 
Now my team member getting error not same error different one.
