### ISSUE TITLE
[CoE Starter Kit - BUG]: License issue

### ISSUE THREAD

**Issue by tsegato** [microsoft/coe-starter-kit#571]
User is PowerPlatform Admin

I get following error:
![image](https://user-images.githubusercontent.com/43033640/120768395-62aa0d80-c51c-11eb-9a55-d1acea217d37.png)

The user used for connections has following license:
![image](https://user-images.githubusercontent.com/43033640/120768427-6f2e6600-c51c-11eb-8428-765717ad05f3.png)

I have added Per app license too to the environment:

![image](https://user-images.githubusercontent.com/43033640/120768496-80777280-c51c-11eb-8b8c-b48b6422c25c.png)

What am I missing as license?

**Comment by manuelap-msft** [comment]
You will need a license that falls under a MediumLow1, MediumLow2 or High performance profile:
![image](https://user-images.githubusercontent.com/55705669/120774560-4dcc7a80-c51a-11eb-8a7b-925571d91bd7.png)

See: https://docs.microsoft.com/en-us/power-automate/limits-and-config

**Comment by tsegato** [comment]
Thanks appreciated. I only see what you see on the image. Is it because we need to buy some licenses, or why are these not shown in our licenses?

**Comment by manuelap-msft** [comment]
Yes, the plans mentioned above are paid licenses that need to be purchased first before they show up.
