### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Administration Planning issues errors when viewing from Power BI dashboard

### ISSUE THREAD

**Issue by ckunes** [microsoft/coe-starter-kit#5711]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When viewing the Power BI dashboard after successfully loading the Power Platform Administration Planning pbit, the content in the Team breakdown -experience & personas section is broken.  

<img width="636" alt="PowerBI_PowerPlatformAdminPlanning_Errors" src="https://github.com/microsoft/coe-starter-kit/assets/32179396/6e451c15-3b32-4bbe-9161-581f357fcf3b">

When clicking on the see details link after the  'Something's wrong with one or more fields' the following message appears:

<img width="337" alt="FieldsNeedToBeFixed" src="https://github.com/microsoft/coe-starter-kit/assets/32179396/80b3f578-dc2c-4f94-b332-cf7fcf0532d1">

**The identified missing fields include:**
pcat_name
pcat_peripheraladminpersonaname
pcat_primarytaskcategoryname
pcat_secondarytaskcategoryname
pcat_frequencyname
pcat_productorservicename
pcat_automationname
pcat_outsourcedtaskname 

### What solution are you experiencing the issue with?

Admin Task Planner

### What solution version are you using?

admintaskanalysis_core_1_2_managed solution

### What app or flow are you having the issue with?

Power Platform Administration Planning.pbit - May 2023

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Open Power Bi Desktop
2. Click File, then select Browse reports
3. Open Power Platform Administration Planning.pbit
4. Confirm successful load 
5. Scroll down to view the multiple 'Something's wrong' errors

**Comment by Jenefer-Monroe** [comment]
I dont repro this. Perhaps your import here failed or you didnt map all the columns? [Import sample admin task data](https://learn.microsoft.com/power-platform/guidance/coe/setup-admin-tasks-component#import-sample-admin-task-data)

If you select the failing Visualization it will show you what columns are expected. For example this one uses the two fields highlighted: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1567eb15-5e41-4d53-b945-1d26a64b9238)

You can go to the Model Driven App from there and see if they are present:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4dcebbf1-9430-4c82-8b2d-906379691c06)

**Comment by stjeffer** [comment]
Yes, you should update the task metadata as per this article:

https://learn.microsoft.com/en-us/power-platform/guidance/coe/admin-tasks-component#update-the-admin-task-data

Give this a try.

**Comment by v7herman4** [comment]
We had the exact same error as as @ckunes . Turns out the names of some of the columns that came over came as the friendly name but the model requires the schema name. To fix:

On the report view, for each visual with an error, click on the visual. Note the "missing" field.
![orig2](https://github.com/microsoft/coe-starter-kit/assets/89024016/8db21adf-807b-46db-8ed8-afa9d98a338f)

Back on the "Table View", find the respective column and rename it to the schema name.

![orig2](https://github.com/microsoft/coe-starter-kit/assets/89024016/b22bd7ed-aa63-42cd-8e8e-03356e96c4e0)

**Comment by v7herman4** [comment]
![orig2](https://github.com/microsoft/coe-starter-kit/assets/89024016/31d65b99-e008-4fd0-b44e-668ff8c58096)

**Comment by v7herman4** [comment]
![orig1](https://github.com/microsoft/coe-starter-kit/assets/89024016/be70c674-a490-4aa4-a41f-05bcd2816ae8)

**Comment by manuelap-msft** [comment]
This has been fixed by updating the dashboard to match to the new column names.
https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Power%20Platform%20Administration%20Planning.pbit
