### ISSUE TITLE
[CoE Starter Kit - BUG] HTTP call in Admin | Audit Logs | Sync Audit Logs (V2) flow fails sometimes 

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#5714]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

HTTP call in Admin | Audit Logs | Sync Audit Logs (V2) flow has failed few times with error "Error occured while reading secret: secretReference". This has happened only 2 times now and is most likely service issue. 

For example in this case there were 7 pages of events with totally about 1500 GetContentDetails HTTP action calls and only 1 failed, so not a major issue but still we can miss events. 

<img width="380" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/b85552a6-c82f-484e-a1b3-b5e025aa5c21">

We should implement retry logic and/or additional error handling to HTTP actions to rerun them if call fails

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

None

**Comment by russrimm** [comment]
@Jenefer-Monroe fyi this issue can also happen in the BuildContentSlotArray loop as well, was that also fixed in the July fix for this issue?
![image](https://github.com/microsoft/coe-starter-kit/assets/10841574/99bb0bdf-bb84-4a0d-ad50-30f2c74ff432)

**Comment by Jenefer-Monroe** [comment]
This is not yet resolved. Pete is investigating.

**Comment by petepuu** [comment]
@russrimm, could you check has this happened only intermittently or in every run? Also are there multiple pages processed in that step and HTTP call always fails to this error "Error occured while reading secret: secretReference"?
