### ISSUE TITLE
[CoE Starter Kit - QUESTION] Looking to see if there is way for Environment Admins to manage the CoE

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#5716]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

So for example,

Power Platform Admins we have Power Platform Service Admins that will see the entire tenant but not really manage individual environments. They have Environment Admins that manage specific environments and there could be one environment admin per environment that is created.

is it possible for the Environment Admins to have specific access using the apps within inventory core and governance only be able to work through environments they have access to?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Power Platform Admin View/ Admin Apps

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. We dont have a out of the box solution here but here are a few ideas. 
If you would like to manage several instances of the kit, we do offer [Setting up CoE for a subset of environments](https://learn.microsoft.com/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments)
You could also consider implementing RLS using the modern business units .

I hope this helps get you started!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by mdphung** [comment]
Hey @jenefer-monroe, is it possible that maybe done the road this could be a new feature for the tool kit to be able to add specific admins to specific environments to manage?

**Comment by Jenefer-Monroe** [comment]
We do have an item like this on the backlog somewhere but honestly I dont think it will be on top of the list anytime soon due to other requirements. Thank you for expressing your interest though!
