### ISSUE TITLE
[CoE Starter Kit - BUG] Error Turning on Child Flows in COE Core Components

### ISSUE THREAD

**Issue by mwagner88** [microsoft/coe-starter-kit#5718]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are currently setting up our COE for our organization and are running into an issue when trying to turn on child flows to begin the setup. We have verified and recreated what we believe are the relevant connections. We have attached screenshots of the errors we are receiving when trying to turn on the needed child flows.

[Coe ERROR.docx](https://github.com/microsoft/coe-starter-kit/files/11637923/Coe.ERROR.docx)

### Expected Behavior

We should be able to turn on the child flows with no errors and proceed with setting up the COE.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

HELPER - Add User to Security Role

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Access CoE Core Components
2. Access Cloud Flows
3. Attempt to turn on any of the following Child Flows
                HELPER - Add User to Security Role
                HELPER - Send Email
                HELPER - Maker Check
                HELPER - CloudFlowOperations
                HELPER - CanvasAppOperations
                HELPER - ObjectOperations
                CLEANUP HELPER - Check Deleted (Ai Models)
                CLEANUP HELPER - Check Deleted (Business Process Flows)
                CLEANUP HELPER - Check Deleted (Canvas Apps)
                CLEANUP HELPER - Check Deleted (Cloud Flows)
                CLEANUP HELPER - Check Deleted (Custom Connectors)
                CLEANUP HELPER - Check Deleted (Model Driven Apps)
                CLEANUP HELPER - Check Deleted (PVA)
                CLEANUP HELPER - Check Deleted (Solutions)
                CLEANUP HELPER - Power Apps User Shared With
                SYNC HELPER - Apps
                SYNC HELPER - Cloud Flows
                SYNC HELPER - Get Security Role Users
4. Receive errors as attached below
[Coe ERROR.docx](https://github.com/microsoft/coe-starter-kit/files/11637959/Coe.ERROR.docx)

**Comment by Jenefer-Monroe** [comment]
In the future, please attach images and details diretly in the bug. It makes our processes much easier.

**Comment by Jenefer-Monroe** [comment]
I cant read the error message on the Maker check flow, its blurred. CAn you plase share here whast it says?

**Comment by Jenefer-Monroe** [comment]
It sounds from the other message like you might be logging in and turning the flows on with a different user than created the connections and installed the kit. While this is possible, its not easy. Is that the case?

**Comment by mwagner88** [comment]
> I cant read the error message on the Maker check flow, its blurred. CAn you plase share here whast it says?

Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is 'ad05253f-0be2-4e8c-803d-02ab45f33e0b'. Connection '/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps/connections/8a76d588726e494aa334bff008195c3e' to 'shared_commondataserviceforapps' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".

**Comment by mwagner88** [comment]
> It sounds from the other message like you might be logging in and turning the flows on with a different user than created the connections and installed the kit. While this is possible, its not easy. Is that the case?

Would a different user creating the environment have the same effect? The environments were created by an initial user. Then everything was modified and imported using a global admin service account. So, in theory the same user was used for everything but the creation of the environment itself. If this is not ideal, then we can recreate the environments as we have not gotten very far into this process.

**Comment by Jenefer-Monroe** [comment]
No environment creation would not matter. But the connection creation would. 
Please go to the connections in your CoE environment as the user you are using to setup the kit. Do you see [all the connections](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#create-connections) there? Are they healthy or do they show as needing fixed? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4a7bed80-2a3b-4672-ab50-b384c1757f61)

**Comment by mwagner88** [comment]
> No environment creation would not matter. But the connection creation would. Please go to the connections in your CoE environment as the user you are using to setup the kit. Do you see [all the connections](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#create-connections) there? Are they healthy or do they show as needing fixed? ![image](https://user-images.githubusercontent.com/89584709/242980281-4a7bed80-2a3b-4672-ab50-b384c1757f61.png)

They all state connected

**Comment by manuelap-msft** [comment]
Can you open the Flow Detail view for any of the flows, and check if all the connection references show with a green check?
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/d2ab817d-5d19-455b-bc02-a465b081d4c0)

If any of them aren't, note the name and:

1. Go to [Power Automate](https://make.powerautomate.com/).
2. On the left pane, select Solutions.
3. Select the Default Solution, and change the filter to show Connection References.
4. Select the connection reference that didn't have a green tick.
5. Set the value by selecting an existing connection from the drop down or creating a new one.
6. Select Save and confirm you want to save the changes.

**Comment by mwagner88** [comment]
> Something must have happened here with the connections according to the error. If you can recreate and start over in a new enironment then I would.

I recreated as it did seem the connections were made with another account somehow. I am now running into the below issue with the new environment. The environments and connections were made using the intended service account.

![image](https://github.com/microsoft/coe-starter-kit/assets/135364699/62e070c0-58a8-4db5-bb9b-24439bd314cc)

**Comment by Jenefer-Monroe** [comment]
And are you logged in as that service account now?

**Comment by Jenefer-Monroe** [comment]
Something is wrong with who you installed as v who you are logged in as. 
Please share the following images. 

- a screenshot with what solutions you have installed in this environment. Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

- a screenshot showing who owns all the apps. please obfuscate the name slightly but not so much that we cant validate
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d7cd30c6-d076-4c33-9dcc-e34569ac6f65)

- same thing but for the pages
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/973a64c4-a1f3-4c56-bc88-05e549f05868)

- the connection and owner for this flow: SetupWizard>GetUserDetails
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/94605808-0f2a-4587-997b-4ef0b3efd8d8)


- your environment in https://admin.powerplatform.microsoft.com/environments to see if a security group is assigned
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/47cd8e4f-f0ab-4e77-a5da-12152da57523)

**Comment by Jenefer-Monroe** [comment]
It is a service principle or a service account?

**Comment by mwagner88** [comment]
Service Account

**Comment by Jenefer-Monroe** [comment]
OK I'm afraid I really dont know. 

- You installed as ABC_Admin, 
- All connections show as belonging to ABC_Admin
- All apps / pages are set as owned by ABC_Admin
- You are logged in as ABC_Admin and try to launch the apps

You are told you (ABC_Admin) do not have access to the app. 



Can you validate, is this the correct GUID for ABC_Admin? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/298ac3c5-3973-4f28-8ed6-c642441149c2)

**Comment by mwagner88** [comment]
I was not seeing the same Object ID when checking against the account properties in AAD. I then tried opening a new Edge browser with the Service Account signed in and encountered the below error message when trying to access the CoE Setup app.

![image](https://github.com/microsoft/coe-starter-kit/assets/135364699/ca83ca9a-3a98-4cad-927a-f09365fc7d7d)

**Comment by mwagner88** [comment]
I noticed it was not referencing the same object ID when comparing the account to the properties seen in AAD. I then signed into a new Edge session with the appropriate Service Account and encountered the below message.

![image](https://github.com/microsoft/coe-starter-kit/assets/135364699/fff7a4ee-9d0a-46b2-991e-112851665567)

**Comment by mwagner88** [comment]
> OK I'm afraid I really dont know.
> 
> * You installed as ABC_Admin,
> * All connections show as belonging to ABC_Admin
> * All apps / pages are set as owned by ABC_Admin
> * You are logged in as ABC_Admin and try to launch the apps
> 
> You are told you (ABC_Admin) do not have access to the app.
> 
> Can you validate, is this the correct GUID for ABC_Admin? ![image](https://user-images.githubusercontent.com/89584709/243442990-298ac3c5-3973-4f28-8ed6-c642441149c2.png)

When compared to the account in AAD it is not showing the same object ID

**Comment by mwagner88** [comment]
I attempted to sign into a new Edge session using the Service Account and now receive the below instead with accessing the CoE Setup Wizard

![image](https://github.com/microsoft/coe-starter-kit/assets/135364699/7d851a49-0be7-46ea-a2e0-89725d4e6a2e)

**Comment by Jenefer-Monroe** [comment]
Ok it looks like your browser is not correctly logging you in to that user. I'm afraid this is beyond what I can help with.
Perhaps try in incognito mode, and create a browser profile just for that identity.

**Comment by mwagner88** [comment]
After setting up the child flows I ran into the below error on several of them and have been unable to move past them.

![image](https://github.com/microsoft/coe-starter-kit/assets/135364699/9f6c83fd-0caa-4f6a-a662-10dbf6bdae79)

**Comment by Jenefer-Monroe** [comment]
This typcially means you did not turn [the child flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-child-flows) on in the required order. 

If you can use the setup wizard you should, as it removes much of the complexity in the [Set up inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) documentation for you.

**Comment by mwagner88** [comment]
I have moved past the wizard and have now been able to open to the CoE Dash in PowerBi
