### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE - Admin Command Center Bookmarks

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#5719]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

Will my custom bookmarks in the app stay or be removed if I upgrade CoE?

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/5a05a905-65db-40b1-9b5b-0c8697d3db36)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

Admin Command Center App

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Yes custom bookmarks are supported. Enjoy!

**Comment by BartoszKaminski1999** [comment]
Thanks
