### ISSUE TITLE
[ALM Accelerator - BUG]: DevOps Pipeline Fails at Install PowerShell Modules - For Some but not all

### ISSUE THREAD

**Issue by ChristopheHare** [microsoft/coe-starter-kit#5720]
### Describe the issue

The Task within DevOps fails for some pipelines but not others, please help.

As seen below, my pipeline for build-deploy-xxxx-CenterofExcellenceAuditLogs fails with the error:
" No match was found for the specified search criteria and module name 'Microsoft.Xrm.Data.PowerShell'. Try Get-PSRepository to see all available registered module repositories."
![Screenshot 2023-06-05 102515](https://github.com/microsoft/coe-starter-kit/assets/118164862/02f2c0f3-12c4-4131-bcc4-5960c8ac2f8b)

Where as the pipeline for build-deploy-xxxx-CenterofExcellenceCoreComponents seems to pass perfectly fine, 

![Screenshot 2023-06-05 102734](https://github.com/microsoft/coe-starter-kit/assets/118164862/dd3dc6b1-c483-4e29-b84e-78b64e006b1a)

 I cannot figure out why this is happening, any support / guidance is most welcomed. 
 Thanks in advance

***This is not being run within the ALMAccelerator Application, this is within DevOps*** 
Please Redirect and accept my apologies if this is the incorrect place to raise.

Thanks again.

### Expected Behavior

The behaviour I expect is that of task completion within the pipelines, as the same install-powershell-modules.yml is being referenced for each pipeline the same passing result and moving to next subsequent tasks within the Pipeline

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

4.8

### Anything else?

Logs Can be provided :}

**Comment by mikefactorial** [comment]
@ChristopheHare having trouble understanding what could be happening here. Does it consistently fail on one pipeline or is it failing randomly for different pipelines?

**Comment by ChristopheHare** [comment]
Hi @mikefactorial, hope your well. Thanks for getting back to me on this.

I have not tried running since its initial failure and raising of this ticket, if it's believed to be a library issue, should i attempt a re-run?

It would seem the Audit Components are the pipeline having this issue. I wasn't sure if it was due to the deprecation of components that was causing it? I'm a novice at this, so learning as I go. Appreciate the support. (Without all the YAML Templates you guys have made available to us, this would have taken a lot longer, so thanks for all you guys do :) )

For now I have successfully deployed the Core & Nurture components to our Test & Prod environments. The Innovation Backlog has an issue with the "Update Solution XML with Build Number" step.

I can provide the logs if you would like them, I have the successful Core run and the failed Audit Components.

Thanks again Mike.
Chris

**Comment by ChristopheHare** [comment]
Attempted to re-run, to validate if it was an issue with the feed, received the same result.
Thanks
Chris

**Comment by mikefactorial** [comment]
@ChristopheHare this has me at a bit of a loss. There's no reason why some solutions would fail for this particular step and succeed for other solutions. We use the ALM Accelerator internally for all of our ALM and I can't say I've seen this happen before so would be hard to duplicate. Let's get on a call sometime later next week and maybe we can get to the bottom of this. Feel free to set up a call v-ochsmike at microsoft dot com.

**Comment by ChristopheHare** [comment]
Hi @mikefactorial,

Thanks for your response. I am getting an Undeliverable response when attempting to mail you, 
![image](https://github.com/microsoft/coe-starter-kit/assets/118164862/559b08c9-6b42-4ba2-9bc9-ca8c113820ed)

Am I being dumb? Apologies for this.

**Comment by mikefactorial** [comment]
@ChristopheHare closing this out for now per our call. Looks like it was a transient issue. Feel free to open a new issue if you have any further questions / concerns

**Comment by ChristopheHare** [comment]
Awesome, thank you so much again for your time @mikefactorial & @RajeevPentyala . Really appreciate it and all you guys do!
