### ISSUE TITLE
[CoE Starter Kit - BUG] Apps last launched date is not populating for almost all the power apps in personal productivity environment.

### ISSUE THREAD

**Issue by nvarsha23** [microsoft/coe-starter-kit#5724]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Apps last launched date is not populating for almost all the power apps in personal productivity environment (default environment). Our version of CoE is March 2023.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2023

### What app or flow are you having the issue with?

Admin - sync template

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, here are a few things to note. 

Audit logs in the past:
In the past audit logs were collected by a solution separate from Core as the setup for them requires additional permissions. Please see [Set up the audit log connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog)
They were subject to a chunking issue that people would hit if there was too much traffic in their tenant that led to missed launches.
And as they were based on a custom connector they had issues with upgrade and needed to be fixed periodically as described here: https://github.com/microsoft/coe-starter-kit/issues/1424

New technique:
We do offer a new technique that is not subject to these custom connector limitation. And the custom connector technique will be deprecated in August 2023. See https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http

The new technique does have a different API requirement in the app registration though, so please review that carefully and be sure to change from delegated to application permissions if you re-use the old app registration. 

In either technique: 
Audit logs begin to collect data from when they are turned on, they do not go back and get historical data. There is a helper script for getting old logs though described here: [How to get older data](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#how-to-get-older-data)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
