### ISSUE TITLE
[CoE Starter Kit - BUG] Inactivity email for Flows last ran versus last modified

### ISSUE THREAD

**Issue by sam-nagle-SJP** [microsoft/coe-starter-kit#5727]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This issue has been raised before but I'm raising again to keep visibility and to let the team know this is an issue that multiple people would appreciate some thought put into.

Here is the issue logged before which gives a good description. https://github.com/microsoft/coe-starter-kit/issues/3855

The issue really comes down the fact the inactivity emails are triggered by the last modified date of the flow.

We as admins as well as a high number of our users would expect this flow to be triggered from a last ran date, not the last modified date. 

### Expected Behavior

Allow trigger for inactivity emails to be changed from last modified to last ran.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.8.1

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Flows)

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

this is already on our backlog, see: https://github.com/microsoft/coe-starter-kit/issues/5214

You can find all the backlog items related to Inactivity under this tag:
https://github.com/microsoft/coe-starter-kit/labels/InactivityRewrite

Raising duplicate issues or raising issues again doesn't help keep visibility, they actually just make it more difficult for us to plan our backlog and increase our overhead in having to respond and sort through issues! We're a really small team managing the CoE kit, so I thank you for considering this when you raise issues in the future. 

Closing as duplicate.
