### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 - No Organization is matching the given dataset

### ISSUE THREAD

**Issue by SSSTREDDD** [microsoft/coe-starter-kit#5728]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

 Admin | Sync Template v3 - No Organization is matching the given dataset

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

None

### Anything else?

![Screenshot 2023-06-05 115708](https://github.com/microsoft/coe-starter-kit/assets/28159451/1230c97d-dee3-4eec-ae33-1651fedef726)

**Comment by Jenefer-Monroe** [comment]
Hello, this is a known bug which was fixed in later versions of the kit.
Basically there is a product bug which causes this value to not be able to be returned for some environments, and so now we just catch and do not update that property for those environments
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/69654546-99b8-4f56-a688-beb338dcbd4f)

**Comment by Jenefer-Monroe** [comment]
Will close out as a duplicate.

**Comment by VasilinaMaroz** [comment]
Hi! We've just faced the same issue in the latest release of Core Components solution - 4.9 (June). The flow name is Admin | Sync Template v3 (Business Process Flows).

**Comment by Jenefer-Monroe** [comment]
Can you please post as a new issue? Then I'll take a look with you.

**Comment by mdphung** [comment]
@jenefer-Monroe,

I have same problem and I am on the August Release build:
Here is the screenshots of the issues will the above change work for all of these:

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/4a2490e2-197b-4965-bf0d-049e3a5cfe59)
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/3ffa8228-b7b8-41a2-9a05-85eab6684504)
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/f23f5109-75d2-4282-817c-fa08096bd451)
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/fac0247d-da5b-450d-9b12-5803ab997dbb)
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/5218f663-b9f7-4d1c-a5f5-7d5f327f4e18)
