### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYODL and some GCC customers

### ISSUE THREAD

**Issue by osbornecc** [microsoft/coe-starter-kit#5735]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi there,
To sort of add onto #5210 : 

We attempted to use BYODL with the CoE.  Our Power Platform tenant is GCC but our Azure portal is Commercial.  Creating the connections needed for the Data Flows will not talk to Commercial Azure (only Gov).  

I created a support case, and was told the scenario was being worked but won't be available for quite some time.  Unfortunately, that means we will not be able to take advantage of the data BYODL offers as delivered in the CoE.   We're "stuck" with the old-school CoE Flows.

Still holding out hope, though!
Thanks.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Thanks for trying it out and for the update! Will be hoping for you. We are fans of BYODL!

**Comment by manuelap-msft** [comment]
Closing out as no action required for CoE kit team.
