### ISSUE TITLE
[CoE Starter Kit - QUESTION] From where is HELPER - CanvasAppOperations and HELPER - CloudFlowOperations being called?

### ISSUE THREAD

**Issue by HenningStrand** [microsoft/coe-starter-kit#5738]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I see that both of these flows have the 'power' to delete apps and flows from the platform, e.g. using the 'Remove Flow as Admin' connector. I'd like to know from which apps or flows this flow is triggered to perform these deletions. Thx
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/556a7c81-3b36-4cba-8fd3-550acf5111bd)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

HELPER - CloudFlowOperations

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by HenningStrand** [comment]
That's interesting. I did exactly that before writing to you and got no info on dependent objects.
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/91e7026f-fe96-4257-b3bd-e7ecdf25ee08)

**Comment by Jenefer-Monroe** [comment]
Are you in an unmanaged solution? I believe it behaves differently there. Mine is from a managed install.

**Comment by manuelap-msft** [comment]
Are your flows off? Its possible the dependencies don't show off if your flows are off.

**Comment by HenningStrand** [comment]
The flows are turned on and the apps are live and kicking, so strange thing the dependencies are not showing!

**Comment by Jenefer-Monroe** [comment]
Did we answer your question about how this is used though? Aside from the unfortunate issue with your dependencies not showing.

**Comment by HenningStrand** [comment]
Seems like the dependency issue is not related specifically to the CoE solution. I managed to reproduce on my own solutions as well. Have reported this to Microsoft support.

**Comment by Jenefer-Monroe** [comment]
Thanks for letting me know. I'll go ahead and close them but please do return with other questions in the future
