### ISSUE TITLE
[CoE Starter Kit - BUG] Installing May release Fresh, receiving error  "25 Queries are blocked by the following error"

### ISSUE THREAD

**Issue by sperry1625** [microsoft/coe-starter-kit#5739]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I saw mention of this in another post but no resolution.
When I try and open Production_CoEDashboard_May2023.pbit in PowerBI Desktop I receive the following error:
![image](https://github.com/microsoft/coe-starter-kit/assets/22748990/be088b9c-4310-42c2-9a89-e8bed9cba83f)
I do not know what it means or how to resolve the issue. Is this due to flows still running? 

### Expected Behavior

The dashboard to load with data in it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

The Core Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Install Core Solution
2. Go through Setup App
3. Open pbit file included in download.

**Comment by Jenefer-Monroe** [comment]
I've seen this happen to people occassionally, and have even seen it a few times myself. But I cannot get it to repro consistently even for the same PBIT file. 

What has worked to resolve is to go ahead and let whatever will finish, finish. And then refresh again once in the PBIX file

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by v7herman4** [comment]
I had the same error. Since I was still in the template file, I saved my changes as a pbix, closed, started it back up again and then clicked "apply changes" and that worked.
