### ISSUE TITLE
[CoE Starter Kit - BUG]: Solution "Center of Excellence - Audit Logs" failed to import

### ISSUE THREAD

**Issue by uohlukas** [microsoft/coe-starter-kit#574]
**Describe the bug**
Solution fails to upgrade

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Audit Logs
 - Version: 1.41
 - Solution (zip file)

**To Reproduce**
1. Go to 'Import'
2. Click on 'CenterofExcellenceAuditLogs_1_41_managed.zip'
3. Scroll down to 'Import' (using default Upgrade action)
4. See error;

Solution "Center of Excellence - Audit Logs" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 2 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_64c11, Id: 7ec92171-d21c-4802-a50f-2888e831d7a5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f691c36f6fa56d15c_a4b81, Id: a6b13be9-2602-4b14-8bd8-d2b1fe44b438, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

**Expected behavior**
For the solution to upgrade

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello it looks like you may be upgrading from an old version as we moved this connector. 

Please download the latest solutions from here https://aka.ms/CoEStarterKitDownload
Then upgrade your Core solution first (currently at 2.1.6)
Then if you still cannot upgrade successfully delete the Audit Logs solution (dont worry, data is stored in Core and you wont lose it) and reinstall fresh.
