### ISSUE TITLE
[CoE Starter Kit - QUESTION] Have Request Orphaned Objects Reassigned (Parent) send mails instead of MS Teams bot

### ISSUE THREAD

**Issue by JawnLegend** [microsoft/coe-starter-kit#5741]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is it possible to have the Request Orphaned Objects Reassigned (Parent) flow send out emails to the managers, instead of the MS Teams bot? My organization has disabled the bot, so I'm unable to run the flow.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent) and Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

as part of our implementation, we only support Teams messages as we use adaptive cards to provide managers with immediate action options (e.g. take ownership, delete,...). If you wanted to use Teams, you'd have to implement that yourself by extending the CoE kit. 

Here's our documentation for extending the kit that should give you a starting point on how to get going:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

**Comment by JawnLegend** [comment]
Hasn't it been sent out by email in previous versions? I would like to avoid making any extensions.

**Comment by Jenefer-Monroe** [comment]
We have not sent these adaptive cards in email in the past. 
To my knowledge, for orphans, we have not sent mananagers any mails here in the past.
