### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYODL CoE Inventory Flows

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#5744]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Since updating the BYODL CoE Core Components to version 4.8 and noticed that a number of the inventory flows were turned off (some that I am sure were on before). I was having issues (and still having issues) with the default environment flow and app data not going into the Power BI report. When researching existing issues it mentioned in one that all inventory flows should be on. 

I have turned all inventory flows on and hopefully will see the default environment data, but wanted to check that all inventory flows should be on?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello. I'm having a little trouble tracking your issue. 

1. You can see which flows should be turned on for BYODL in the CoE Solution Metadata table in Core
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2eab5417-f73e-4051-945b-b47286ea9e8b)

2. It sounds like you are getting data from all environments except default. Is that correct? If so please go look in the data lake itself. Do you have an environment in the apps folder for Default?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5a1744dd-6f29-4771-8b87-476f8a54cf20)

**Comment by G1982C** [comment]
Correct, there is data in the data lake for both flows and apps, although neither are showing in the Power BI Report. 

For some reason it is not allowing me to udd an image, GitHub is giving an error. 

PowerApps has 404.36 KB for Canvas and 12.50 for Model driven for the default environment. Flows has 577.03 kb of data for the default environment. So in relation to the other environments, it is showing the largest amount of data which is correct.

**Comment by Jenefer-Monroe** [comment]
Is the data in the Power Platform Admin View app? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f031332c-2aa1-4b58-8b02-73b66ccc2a5e)

**Comment by G1982C** [comment]
I can see the apps but they are showing up as the wrong environment. 
![PowerAppsApps](https://github.com/microsoft/coe-starter-kit/assets/117096415/58167d3d-64ad-4840-99b8-da5b4e67a4ed)

They are showing as (from preview) rather than the default environment. I have selected one of the apps showing as being in the (from preview) environment and it is definitely in the Default environment. 

I think as a result of me turning on the inventory flows yesterday, I have now created an issue with the flows and environment as they are all showing as deleted now in the Power Platform Admin View

![DeletedFlows](https://github.com/microsoft/coe-starter-kit/assets/117096415/a83c7cb2-d965-4a47-9f62-f1e124b8526c)

Is there a way to undo those that are now showing as deleted?

I was reading one of the issues (5250) that I thought was linked to my issue and I thought it was suggested that all inventory flows should be on (see below)

![SnipImage](https://github.com/microsoft/coe-starter-kit/assets/117096415/55db5399-8a7d-4df6-a6a5-3ea124ea9a41)

**Comment by Jenefer-Monroe** [comment]
i dont repro this so you'll need to investigate for me. 
In your CoE environment > Dataflows > Edit the **_CoE BYODL Environments_** dataflow > find your default environment in the last step. Is the environment id column show with this format? default-tenantGUID
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f7e513fa-5bd4-431a-8a74-5f47fa2deae0)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a582cb50-1a93-4979-b6e5-801c3016541b)

**Comment by G1982C** [comment]
Hi Jenefer, is there anything else I should be looking at to determine why the default environment flows and apps are not coming through to the Power BI report? At some point I would like to transition to a production environment of the BYODL CoE toolkit, although at present that is not possible given the issue in data not showing correctly. Thanks

**Comment by G1982C** [comment]
Just to add some good news, the flows are now showing up in the flows and apps tables with the correct environment. (see below) - just still not coming through into Power BI

![Coeimg120623](https://github.com/microsoft/coe-starter-kit/assets/117096415/934449f0-6687-41b7-91bc-9bdf418f4a92)

It is showing data in the datalake storage for that environment (see below)

![Coe2_120623](https://github.com/microsoft/coe-starter-kit/assets/117096415/963cf6ed-7dcd-4f6c-8424-489504e0ffa4)

I can see flows in the CoE BYODL Flow data flow as showing with the default environment (see below)

![Coe3_120623](https://github.com/microsoft/coe-starter-kit/assets/117096415/e00e514f-4817-40d1-a5b1-b6bc6abd36c3)

although if I go to the Power BI dataflow, edit that and select the Flows query - there is nothing showing for that default environment (see below)


![Coe4_120623](https://github.com/microsoft/coe-starter-kit/assets/117096415/da162c9a-fe58-492a-a6e5-070e91d8f544)

If I select applied step before the merged queries I can see the default environment showing (see below)

<img width="255" alt="Coe5_120623" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/6ed14e98-8563-4da7-a408-e1c6271ef3c4">

Although if I select the merged queries step, the default environment is no longer there. So it is the join that seems to be the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/117096415/72290101-48d6-4aee-a466-9f00e3cb3f67)

If I look at the environments query and specifically at the EnvironmentId column, the default environment ID does exist in that table that is linked to that join (see below)

<img width="428" alt="Coe6_120623" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/dcdd9c68-4723-44d5-b452-f581d37785df">

**Oh I can see the issue**. In the environments table it is showing as default (lower case d) and in the flows table it is showing as Default with uppercase D. So that is why it is not making the match at the join.

Was there an updated Power BI report as when I looked at the May hotfix release I could only see an updated version of the solution (see below)

<img width="575" alt="Coe7_120623" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/3ccac034-475f-4bb4-9b45-b9fd8b35e73e">

**Comment by Jenefer-Monroe** [comment]
That issue was fixed in Aprill https://github.com/microsoft/coe-starter-kit/issues/5780#issuecomment-1587339462

> 

Yes this is a product limitation. There is no upgrade path for dataflows, you just need to redo the work.

**Comment by G1982C** [comment]
Thanks. When you say redo the work, are you able to point me in the right direction of the work I will need to do for dataflows? Thanks

**Comment by Jenefer-Monroe** [comment]
Thank you for investigating. The issue with the **_D-_** v **_d-_** was fixed in April, so you will need to upgrade the PBI and dataflows. We did not ship a new June version this time due to some issues we faced so you will use the May version.

**Comment by Jenefer-Monroe** [comment]
If you need to update the dataflow (which you do) you will redo steps 7 - 15 of this https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#import-power-bi-dataflows

And then normally you will just do this step
https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard

Hope that helps

**Comment by G1982C** [comment]
Thanks Jenefer. I will give that a go. Thanks again

**Comment by G1982C** [comment]
Just to confirm, this is now working. I had to do all of the steps (rather than steps 7 - 15) relating to this https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#import-power-bi-dataflows

**Comment by Jenefer-Monroe** [comment]
Oh wonderful news, thank you for following back up and letting us know!
