### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Tracharr** [microsoft/coe-starter-kit#5746]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi I am trying to set-up the governance component - I have imported the governance solution, however when I get to the developer compliance section - I do not have the setup wizard option in my left hand bar to run? Can you advise please

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Here's the setup instructions for the compliance process - both for using the wizard, as well as manual instructions (some folks had an issue with the compliance setup wizard with the latest release):
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components
