### ISSUE TITLE
[CoE Starter Kit - QUESTION] How Can I Exclude Environments from a CoE

### ISSUE THREAD

**Issue by sperry1625** [microsoft/coe-starter-kit#5747]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way to exclude environments from the CoE? As an example, I have installed the CoE in a Development environment and I would like to have it scan and process information only from my Development environments. Do the same for production.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

May 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Does this section in our documentation cover and answer your question? 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments

**Comment by sperry1625** [comment]
What if all the flows already ran? Can the environments be removed?

Regards,

Steven Perry
***@***.***

**Comment by sperry1625** [comment]
I will give that a try.

Regards,

Steven Perry
***@***.***
