### ISSUE TITLE
[CoE Starter Kit - QUESTION] Core Components,

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5748]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I am getting below error in below flows.

Admin | Excuse Support Envts from Governance Flows
Admin | Sync Template v3 (Business Process Flows)
Admin | Sync Template v3 (Custom Connectors)
Admin | Sync Template v3 (Desktop flows)
Admin | Sync Template v3 (Environment Properties)
Admin | Sync Template v3 (Flow Action Details)
Admin | Sync Template v3 (Model Driven Apps)
Admin | Sync Template v3 (Solutions)
Admin | Sync Template v4 (Apps)
Admin | Sync Template v4 (Flows)
Admin | Welcome Email v3
Command Center App > Initially Populate Bookmarks
SetupWizard>CallOrphanFlow
SetupWizard>UpdateDataflowEnvironment
SetupWizard>UpdateInventoryTypeAppSetting

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/d23c1e6f-c33a-4316-83ea-99b6a428b2c4)
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/0ce16ede-1ed9-415f-a204-3390e58b065a)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 19th 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Please share a screenshot with what solutions you have installed in this environment. Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by lingutla123** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/b59cb8fa-ca22-4755-aa36-2c7abdb64fa0)

**Comment by Jenefer-Monroe** [comment]
I've never seen this error before. It seems like the trigger isn't working because you've hit some kind of limit. I'm not sure where to begin investigating this. 

A few thoughts I have, not sure if they are a good direction or not:

- if you wait it might just go away if whatever is causing the limit to be hit stops
- you might be hitting some API limit or something with your license that I've just never seen and so perhaps look at your license type
- your environment is restored or something and so is in Administrative Mode.

**Comment by lingutla123** [comment]
Hi Jenefer,

Now the error is not showing but i deleted few solutions, Apps and environments three days back . Still showing deleted solutions, apps and environments n Power Platform Admin View.

**Comment by Jenefer-Monroe** [comment]
Sounds like the issue is resolved then? You may have just been hitting some product throttle.

**Comment by lingutla123** [comment]
Yes. Do i need to Change the Value of Full Inventory in Environment Variable?

**Comment by Jenefer-Monroe** [comment]
No that is just for when you hit an incompete inventory. That should not relate here. 
Wonderful news, I'll go ahead and close then, let us know if you need more help in the future.
