### ISSUE TITLE
[CoE Starter Kit - QUESTION] CenterofExcellenceAuditComponents

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5749]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

In May release Audit Components version is 3.9.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/fc0d6df2-45c5-48aa-9d01-ce267120dfee)

In June release  Audit Components version is 3.8.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/78edee62-0162-4bdb-81cb-a02cd7bbe23d)

Why is this difference? Isn't it need to be version 3.10?

Thank You.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 19th 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. That is strange. We did not make any changes to Gov so it shoudl have just remained 3.9. Will follow up

**Comment by manuelap-msft** [comment]
Updated - sorry that was an oversight in our release pipeline; we didn't make changes to the AuditComponents solution so just re-released 3.9 again but had that incorrectly configured during the release! Fixed that now! Thanks for letting us know!
