### ISSUE TITLE
[CoE Starter Kit - QUESTION] PBI Report Production_CoEDashboard_May2023

### ISSUE THREAD

**Issue by BroxCJ** [microsoft/coe-starter-kit#5750]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, I've been working  COE report and I am to implement a new relationship betweeen Apps & AppsUsage, that in theory should be 1-N, finding the surprise that I cannot create it beause 5K out of 25K entries are duplicated and cannot understand why. That relationship exists correctly when talking about FLows & FlowsUsage.

In some cases difference between duplicated entries is only the "modified date" and in others the latest version. I guess we should only obtain the last modified with the latest version.

(We have enabled the BYOLD & DataFlow).

Thanks in advance.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2023

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

if you're using BYODL + Dataflow, then you should be using the BYODL_CoEDashboard - you can download that directly from this folder:
https://github.com/microsoft/coe-starter-kit/tree/CoEStarterKit-June2023/CenterofExcellenceResources/Release/Collateral/CoEStarterKit

The Production_ dashboard gets the data from the Dataverse tables (if you're using cloud flows for inventory), the BYODL_ dashboard gets the data from the Power BI dataflow (if you're using BYODL/Data Export) 

Here's the setup instructions to use this dashboard:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-the-byodl-power-bi-dashboard

This dashboard already includes a relationship between Apps and AppUsage
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/bf52b701-b544-4b08-a9a1-3363505667e2)

Does that help and answer your question, or did I misunderstand your question?

Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
