### ISSUE TITLE
[ALM Accelerator - QUESTION] How to Skip Validation Step

### ISSUE THREAD

**Issue by KYT9212** [microsoft/coe-starter-kit#5755]
### What is your question?

Is there a way for us to setup ALM pipeline to skip the validation environment? Pipeline would go DEV - TEST - PROD instead of the  typical DEV - VALIDATION - TEST - PROD

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

May 2023

**Comment by mikefactorial** [comment]
@KY9212 you should be able to skip the Validation stage by removing it from the Deployment Steps in the profile prior to the first commit of your solution. The deployment steps are responsible for determining what pipelines get generated during the export. 
There's more documentation on customizing the pipelines below.
https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/configure-azuredevops-pipelines#customize-the-number-of-deployment-steps-in-your-pipelines-and-the-names-of-the-target-environments 
https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/customize-deployment-pipelines

**Comment by mikefactorial** [comment]
@KY9212 going to close this out as there's no more to do here. Feel free to open a new issue or reopen if you are still having problems given the instructions.
