### ISSUE TITLE
[CoE Starter Kit - QUESTION] DataExport Feature  Can we get Power Automate failure or success results 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#5757]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

with the installation of the data export feature, we are now able to get the Flow last run date 

Similarly, will we able to get the flow sessions and like no of times it is fails and success.

If yes, how do we see or configure please let us know 

### What solution are you experiencing the issue with?

Core

### What app or flow are you having the issue with?

Admin-Sync V3 Template 

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
Cloud Flow run information, including if a run has failed or succeeded, is available via Data Export. You can learn more about the Data Export feature, including the schema definition of what data is available by going to the documentation here: https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics-schema-definition#power-automate-subfolder

Note that run information is only available from the moment you turn on the Data Export feature - it's not provided historically.

The Power BI and Power Platform dataflows provided as part of the CoE kit already consume Flow Usage data, and for example we have a Cloud Flow usage tab in the Power BI dashboard that shows you this information. 
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/368c24d6-914e-4be0-b54d-ce38b721aa71)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
