### ISSUE TITLE
[CoE Starter Kit - BUG] PP admin view - Manage permission - Add user - error loading control

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#5759]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi the team,

Since i ve updated my COE to the last update (June update), i can't change the owner of a canevas app.
I always have **Error loading control** under select yser.

Until now, i never had a problem with this. 

<img width="215" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/67596c2f-9a12-42bd-862a-f86c4e10d482">

<img width="244" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/c649060a-e33b-4ad8-b038-9bbcf8ab42d3">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Power Platform Admin view

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Click on powerapps app
2. Select an app (canevas app)
3. click on manage permission
4. select add user
5.

**Comment by Jenefer-Monroe** [comment]
What version of Creator Kit are you on?

**Comment by tocri** [comment]
1.0.20221205.2


Anthony Leduc
Architecte de solutions M365
________________________________
De : Jenefer Monroe ***@***.***>
Envoyé : jeudi 8 juin 2023 19:51
À : microsoft/coe-starter-kit ***@***.***>
Cc : Anthony LEDUC-PASQUIER ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] PP admin view - Manage permission - Add user - error loading control (Issue #5759)


What version of Creator Kit are you on?

**Comment by tocri** [comment]
I've updated the creator kit to the last version 

<img width="502" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/7803fc1a-772d-44a3-a247-4404b37c09c8">

No change...but i ve forgotten to paste this error

<img width="215" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/c0b15752-80f7-4956-8277-29171209dfed">

**Comment by Jenefer-Monroe** [comment]
I dont repro, can you please let me know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

**Comment by tocri** [comment]
The COE envt is where I setup the COE

***@***.***

The Mes applications personnelle it's the default envt and it's where that I often need to change the owner of an app.

***@***.***






De : Jenefer Monroe ***@***.***>
Envoyé : vendredi 9 juin 2023 08:57
À : microsoft/coe-starter-kit ***@***.***>
Cc : Anthony LEDUC-PASQUIER ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] PP admin view - Manage permission - Add user - error loading control (Issue #5759)


I dont repro, can you please let me know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
[image]<https://user-images.githubusercontent.com/89584709/237367659-4c23e8c8-2f8b-4d8b-af43-79a9f289be69.png>

-

**Comment by tocri** [comment]
Oh i didn't know. Sorry.

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/96811d0e-ab57-4039-994b-ca82268cb1c8)
![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/c7b5c495-665b-46c1-9371-d6d97e1447d5)

**Comment by Jenefer-Monroe** [comment]
Looks like you are in Canada. Thats an early release region, I'll go test there now.
