### ISSUE TITLE
[CoE Starter Kit - Audit log flows & HTTP Connector

### ISSUE THREAD

**Issue by monicasv** [microsoft/coe-starter-kit#5760]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In this new release, the audit log information is being gathered using new flows in the core solution that utilizes the HTTP connector as described in the [documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http).

- One of the concerns we have with this is that the client secret for the app registration has to be provided in plain text
- The only way around is it to use Azure Key Vault but this is not available at our organization
- Outside of the Azure Key Vault option to securely store this information, is there any other way we can get the flow to work without having the client secret stored in plain text?
- Alternatively, is there any way we can mask the secret in the environment variable? If not, can we ask for a feature request?

The previous custom connector method didn't store the secret in plain text so this is a bit of a setback for us as we're likely going to lose access to reporting of unique users/app launches. We also have only two months to find a remediation as the custom connector is slated to be removed in the August 2023 release.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

New Audit Log flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I'm afraid Azure Key Vault is the product's solution to making secret env vars. There isn't another way that I know of. 
If you are unable to get access to the Key Vault, and cannot store the secret directly, then your last option woudl be to save the custom connector outside of the context of Core. You could re-create it in the old Audit Log solution, and keep it there. We will stop shipping the old audit log solution and the custom connector, but it would keep working of course if you held a copy locally.

**Comment by Jenefer-Monroe** [comment]
Adding as a documentation item for July release. Will let you know here as well when I have the steps complete.

**Comment by Jenefer-Monroe** [comment]
I tested around and it looks like the documentation tells you that you need these permissions to use the secrets as an env var. 
Where both the user and the Dataverse object are **Key Vault Secret Users**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5a5ae675-cea6-41ae-94c0-3b00a9c7f8fb)

But from my testing what you actually need is this:
Where the user running the flow is both **Key Vault Secret User** and **Key Vault Contributor**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8fe1fcd4-94eb-479b-a0f4-4694f96395ec)

**Comment by Jenefer-Monroe** [comment]
Yes apologies, we forgot to put the link here. We documented this in the form of a bug: 
https://github.com/microsoft/coe-starter-kit/issues/6017

**Comment by monicasv** [comment]
Thank you!
