### ISSUE TITLE
[CoE Starter Kit - QUESTION] Core Components

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5761]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

I deleted Power Apps environments on  Tuesday 6th. But the  deleted environments, Apps and solutions are still showing in "Power Platform Admin view" app. Is it take sometime to show the change?

Thank you!

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 19th 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. If you are using the sync flow architecture, then environments are deleted by the **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** flow which runs every two weeks by default.
If you are using the Data Export architecture then its based on how long the product takes to mark it as deleted in the datalake. Typcially 3-5 days.

**Comment by lingutla123** [comment]
Thank You Jenefer.

**Comment by Jenefer-Monroe** [comment]
You are welcome!
