### ISSUE TITLE
[CoE Starter Kit - BUG] SharePoint Forms Apps listed as Canvas after update 4.9

### ISSUE THREAD

**Issue by ClaudiuVio** [microsoft/coe-starter-kit#5762]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After the latest update in June 2023 and a sync of all environments, the SharePoint Forms are still listed as forms. (or at least the old ones are ). How can I modify back the type of the app?

### Expected Behavior

SharePoint Forms app should be added correctly in table.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin - Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Search in dataverse SharePoint forms app , and they are listed as Canvas.

**Comment by ClaudiuVio** [comment]
Hello @Jenefer-Monroe,

Thanks for this. Can you please tell me if there is a way to change InventoryMe bulk for items? I have like 100k.

Unmanaged layer I don't have , we always check this before update.

**Comment by Jenefer-Monroe** [comment]
This feature flag is focused on when you have a handful of objects you want to run in inventory. 
It sounds like you just want to rerun your entire inventory. Is that correct? If so you are looking to do a [full inventory](https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory)

With that many apps this will be a very long running operation though.

**Comment by ClaudiuVio** [comment]
Thanks , i managed to solve it , i had to mark 70 forms.

**Comment by Jenefer-Monroe** [comment]
thank you for letting me know!

**Comment by tocri** [comment]
I ve just give it a try. I run manually sync helper flow. And it 's work my sharepoint form app recognize as an canvas change as a Sharepointformapp. Thanks for the tip
