### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 fails on Support environments

### ISSUE THREAD

**Issue by gprof** [microsoft/coe-starter-kit#5763]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Admin | Sync Template v3 fails when it finds a Support environment in the scope "Store environments in the CoE CDS Entity". And specifcally on the Condition: "Get has PCF enabled value". 

Here it loops through all environments but when it finds a Support environment created by MSFT Support the flow fails.
 
[COE Starterkit - Admin  Sync Template v3 Error.docx](https://github.com/microsoft/coe-starter-kit/files/11703097/COE.Starterkit.-.Admin.Sync.Template.v3.Error.docx)

### Expected Behavior

It should not process MSFT support environments, only actual environments created by the customers. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

 Center of Excellence - Core Components 4.4.1 

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

See attachment

**Comment by manuelap-msft** [comment]
Hello,

this bug was fixed in the recent releases, see
https://github.com/microsoft/coe-starter-kit/issues/5414

You'll have to upgrade to the latest version to resolve this!

Closing out as duplicate.
