### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Audit Logs | Sync Audit Logs (V2) lost values

### ISSUE THREAD

**Issue by aserbenko** [microsoft/coe-starter-kit#5765]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We installed the newest CoE Core Components solution but can't turn on the flow **Admin | Audit Logs | Sync Audit Logs (V2)** as it has lost values in one of the actions.

![image](https://github.com/microsoft/coe-starter-kit/assets/65975957/09ab192a-dbbb-4a46-864b-38bf1e77b33a)

What should be pasted in this condition?

The path to the action:
**Get Logs** scope - **LoopContentIDs** apply to each - **GetAndProcessEvents** apply to each - **Apply to each Audit Log** - Switch - **LaunchPowerApp** Case - **UpsertAuditLog-and-AppLastLaunched** scope - **Update Last Launched if newer** condition

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

None

**Comment by petepuu** [comment]
@aserbenko We should have there "App Last Launched On" from GetApp action in both conditions

<img width="329" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/4ca64c31-6473-4518-95eb-3e2947c2d24b">

**Comment by aserbenko** [comment]
@petepuu Thank you!

**Comment by petepuu** [comment]
@aserbenko, just remember to remove the unmanaged layer which will be created when changing the flow before installing next version of the Core
