### ISSUE TITLE
[CoE Starter Kit - Feature]: Export All Assets When user leaves  

### ISSUE THREAD

**Issue by crowdedLeopard** [microsoft/coe-starter-kit#5767]
### Is your feature request related to a problem? Please describe.

Hello, 

When users leave an organisation their PowerAutomate connections are disabled. 

### Describe the solution you'd like

I'd like a method to export all of the users power Platform objects and store them centrally. Probably using PowerAutomate

**Comment by Jenefer-Monroe** [comment]
Hello. This would have to be done via solution. There is no other mechanism to reliably backup and restore objects anymore aside from solutions. I've moved you over the the ALM team to see if they ahve feature ideas in the space.

**Comment by mikefactorial** [comment]
@crowdedLeopard ALM Accelerator can store this information in Azure DevOps if you are using it and requiring users to use the ALM Accelerator when deploying their solutions. Would like to get some more information about your requirements though.
