### ISSUE TITLE
[CoE Starter Kit - BUG] Flows unable to find Row ID in Customized Email Table

### ISSUE THREAD

**Issue by salviroshan89** [microsoft/coe-starter-kit#5768]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Yesterday, we had updated on CoE Starter Kit from Sept 2022 to Feb 2023

We only use Core and Governance components.

After upgrading to Feb 2023 we noticed flow "Admin | Inactivity notifications v2 (Start Approval for Apps)" failed at "Get a row by ID 3" action. 

Does Cusomized Email table missing some entries ? Our customized Email table has 19 entries at the movement
![ErrorInactivityNotifications](https://github.com/microsoft/coe-starter-kit/assets/108810665/fb30e425-7935-49b6-8a80-60daa8c66b7f)

### Expected Behavior

Admin | Inactivity notifications v2 (Start Approval for Apps) flow should run without any error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.6

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Go to Flow Admin | Inactivity notifications v2 (Start Approval for Apps) from Governance solution
Flow is failed
Upon opening the flow, we find it failed at action Get a row by ID 3. Seems its missing an entry in Customized Emails table.
![ErrorInactivityNotifications](https://github.com/microsoft/coe-starter-kit/assets/108810665/173ab102-de51-4038-89e6-c79841f36aca)

**Comment by manuelap-msft** [comment]
If you haven't used the setup wizard after the upgrade, you'll have to manually re-run these flows to make sure all emails and solution meta data is configured correctly:
- Admin | Sync Template v3 CoE Solution Metadata
- Admin | Sync Template v3 Configure Emails

The setup wizard would run these as part of an upgrade for you, so we do recommend just running through the setup wizard steps after an upgrade to make sure everything is configured!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
