### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Get Security Role Users fails with '

### ISSUE THREAD

**Issue by SOM-Scott** [microsoft/coe-starter-kit#5769]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

SYNC HELPER - Get Security Role Users fails if the user has a ' in admin_businessunitname under Action 'List_Inventoried_SR_Members'.

```
{
  "error": {
    "code": "0x0",
    "message": "Syntax error at position 183 in '_admin_environment_value eq 8a84df77-b312-4da4-ac92-93e80810d0ab and admin_securityroletemplateid eq 627090ff-40a3-4053-8790-584edc5be201 and admin_businessunitname eq 'Commissioner's Office''."
  }
}
```

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. BU's with apostrophes were broken with the original ship of this feature. Fixed by https://github.com/microsoft/coe-starter-kit/issues/5655 for June release.
I will go ahead and close as a dupe but please let us know if you need something else in the future
