### ISSUE TITLE
Is a Power Automate per user license currently obliged for the CoE installation identity?

### ISSUE THREAD

**Issue by SummerIsHereAndNow** [microsoft/coe-starter-kit#5771]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Dear CAT team,

I've checked the CoE wiki->https://github.com/microsoft/coe-starter-kit/wiki/Issue-triage-(CoE-Starter-Kit)#why-is-a-power-automate-license-required 

However, not fully understand it thus would like some clarification..
from my previous installation experiences, the kit was running without issue as long as having the power app per user plan license.
In the wiki, what you explained is : actually, there are many CoE flows running standalone while it's not part of the app, the fact that I can still run these standalone flow is because the guideline of power automate capability under per user plan is not fully enforced, so if one day, this guideline is enforced, I will need to assign power automate per user plan to this identity?

could you provide some name of the standalone flows from the CoreComponent? so I can test whether it's needed to assign the 'power automate per user plan' to this identity?

Thanks in advance for your clarification.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

as per the licensing guide, which you can find here https://go.microsoft.com/fwlink/?linkid=2085130, the Power Apps per User license is only allowed to be used for flows that run in the context of the flow.
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/41fe2c8e-1b28-4817-bc02-abbffb0075e2)

Today, to the best of my knowledge, this is not enforced in the product - so you can turn on an a standalone flow (one that's outside of the context of an app) with a Power Apps Per User license and technically it would work but you would be in violation of the license guide/license agreement. 

Hope that clarifies your question,
Manuela
