### ISSUE TITLE
[CoE Starter Kit - QUESTION] No Data Showing in COE Dash for Cloud Flows

### ISSUE THREAD

**Issue by mwagner88** [microsoft/coe-starter-kit#5773]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have recently completed the COE Setup and Upgrade Wizard and have accessed the COE Dash in Power Bi. However, It is currently showing no data. I need assistance in getting data to show for our company resources

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

COE Governance Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

![image](https://github.com/microsoft/coe-starter-kit/assets/135364699/0f2d7be3-0c30-4794-a561-5a88e189bcab)

**Comment by Jenefer-Monroe** [comment]
1. Browse to the Admin Command Center > Environment Variables > What is the value for this item? 
![image](https://user-images.githubusercontent.com/89584709/230621685-2f293271-b215-4f91-8234-0f39c8f638e9.png)
2. Browse to the Admin Command Center > CoE Flows Page > Inventory. When did this flow last run and did it pass? Click Flow details to browse to it. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8603efba-6eb3-4813-a66f-475c7f8a1a22)
3. Open the most recent run. Does it make it down to this call? If so how many environments are returned? You can see this by popping it into a json parser.
![image](https://user-images.githubusercontent.com/89584709/230622587-e17a3ad2-e1d2-4d58-8a0c-255aa469359d.png)

**Comment by mwagner88** [comment]
1)  ![image](https://github.com/microsoft/coe-starter-kit/assets/135364699/592337e8-f4ef-4428-89cc-96ac383995c9)
2)   ![image](https://github.com/microsoft/coe-starter-kit/assets/135364699/3536852b-41ce-4f52-8a58-565c54a77ea7)

3)  Do you have a suggested parser for this?

**Comment by Jenefer-Monroe** [comment]
My guess is that the driver flow just hadnt finished running. Plese refresh the PBI now and see if you see data.

**Comment by mwagner88** [comment]
Everything is now showing. Thank you again for the assistance, Marking this thread as resolved.

**Comment by Jenefer-Monroe** [comment]
Wondeful news. Thanks for letting me know!
