### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Apps flow is not populating App Connection references

### ISSUE THREAD

**Issue by bhavikj65** [microsoft/coe-starter-kit#5776]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We recently observed that admin_connectionreference doesn't contain connection references for all our apps. The difference is basically that it has 6091 connection references for Apps and 1,46,986 rows for Flows. 

Just to give an overview on number of resources, we have around 20K Power Apps and 60 Cloud Flows.

After seeing this huge difference is number of connection references, I checked the SYNC HELPER - APPS flow and found below:

Get App as Admin returns Connection References:
![image](https://github.com/microsoft/coe-starter-kit/assets/105588534/6227a2f1-84e0-49e5-904b-b36a31f5186a)

Prepare Connection String scope could confirm that connection references exists:
![image](https://github.com/microsoft/coe-starter-kit/assets/105588534/4546590f-2839-40ba-bc1a-af6a078e5d26)

However "Get Actual - App Connections" scope inside "Prepare for Connection References Table scope"  returns false:
![image](https://github.com/microsoft/coe-starter-kit/assets/105588534/ecd3d786-b2a3-48b2-9baa-68657457c12e)

Now, I checked the expression used in the condition which checks if connection references exists or not and here is the difference:

In Prepare connection string scope its: outputs('Get_App_as_Admin')?['body/properties/connectionReferences'], however in Prepare for Connection References Table its "outputs('Get_App_as_Admin')?['properties/connectionReferences']"

Because of this, it returns false and hence couldn't insert anything in the admin_connectionreferences table. 

### Expected Behavior

It should be able to insert connection references details in the admin_connectionreferences table

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Run the SYNC HELPER - APPS flow for any Power App which contains at least 1 connection reference
2. You will notice that it doesn't insert connection reference details in admin_connectionreferences table.

**Comment by Jenefer-Monroe** [comment]
Hello. Thank you for posting. This was fixed with https://github.com/microsoft/coe-starter-kit/issues/5610 in June. 
I'll go ahead and close as a dupe but please let us know if you need more help.
