### ISSUE TITLE
[CoE Starter Kit - BUG]: issue title

### ISSUE THREAD

**Issue by arpitjain1470** [microsoft/coe-starter-kit#578]
HI Team,

I want to use Azure DevOps and its  Repository and Organization for Power Platform GitHub ALM .
Do please let me know if is possible to set up ALM accelerators  for Makers components using Azure DevOps instead of Github.
if it is possible please share step with me

**Comment by manuelap-msft** [comment]
Hello,

there is no version for the AM Accelerator for Maker that works with Azure DevOps. However, we do have the ALM Accelerator for Advanced Makers that works with Azure DevOps - you can read more about it here: https://github.com/microsoft/coe-starter-kit/tree/main/ALMAcceleratorForAdvancedMakers

I'm converting this Issue to a Discussion, so we can a conversation there if you have follow up questions!

Thank you
Manuela
