### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 Configure Emails Flow Execution not syncing with the Setup Wizard

### ISSUE THREAD

**Issue by sirdiogoamorim** [microsoft/coe-starter-kit#5782]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The "Admin | Sync Template v3 Configure Emails" Flow execution is not syncing with the setup wizard. In consequence, I can't proceed with the setup:

<img width="701" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/97000259/a8426e3e-566e-4862-aa92-01e7b28be9b4">

<img width="530" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/97000259/1819fd11-67b1-4a34-b17a-f624c7d4b29b">

### Expected Behavior

To sync with the setup wizard and enable the "Next" button.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v3 Configure Emails

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
