### ISSUE TITLE
[CoE Starter Kit - QUESTION] coe license requirements

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#5784]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Team 

For implementation of Power Platfor CoE Kit . What are the licences Required . We have Office 365 E3 Lic in our Bucket.

Using Power Apps for Office 365 and power Automate for Office 365 all flows and apps will run..?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Ai Models) Admin | Sync Template v4 (Apps) Admin | Sync Template v3 (Business Process Flows) Admin | Sync Template v3 (Call Updates) Admin | Sync Template v3 (Connection Identities) Admin | Sync Template v3 (Custom Connectors) Admin | Sync Template v3 (Desktop Flow - Runs) Admin | Sync Template v3 (Desktop flows) Admin | Sync Template v3 (Environment Properties) (optional) Admin | Sync Template v3 (Flow Action Details) Admin | Sync Template v4 (Flows) Admin | Sync Template v3 (Model Driven Apps) Admin | Sync Template v3 (Portals) Admin | Sync Template v3 (PVA) Admin | Sync Template v3 (PVA Usage) Admin | Sync Template v3 (Solutions) Admin | Sync Template v3 (Sync Flow Errors) Admin | Sync Template v3 (Driver) CLEANUP - Admin | Sync Template v3 (Check Deleted) CLEANUP - Admin | Sync Template v3 (Connection Status) CLEANUP - Admin | Sync Template v3 (Delete Bad Data) CLEANUP - Admin | Sync Template v3 (Orphaned Makers) CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) CL

### What method are you using to get inventory and telemetry?

None

**Comment by sunilmhatugade** [comment]
can u please call me on +91 9975471900 .  so we can discuss in detail.

**Comment by Jenefer-Monroe** [comment]
We are a very small team and cannot met with our GitHub customers. 

### License Requirements
Please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with) which details the license requirements for the user that will install the kit. 

Note also that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management), this won't be sufficient to run the CoE Starter Kit.

### Where to find help
While we cannot help you install, we do have many partners that offer CoE install and configuration services - you can find them via AppSource: 
https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
