### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Log Paging

### ISSUE THREAD

**Issue by Krishi27** [microsoft/coe-starter-kit#5785]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are new to COE and recently we have implemented COE, after setting up COE we are receiving below emails 

"Your audit logs were collected but some were missed due to truncated results.
You will need to use a smaller interval to gather all logs.
See the optional Step 11 of our[ Audit Log flow setup documentation](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdocs.microsoft.com%2Fpower-platform%2Fguidance%2Fcoe%2Fsetup-auditlog%23set-up-the-power-automate-flow&data=05%7C01%7Cppcoesvc%40nha.nielseniq.com%7Caab4d281183949b4d8c508db6a623ebd%7C6ac7a1f45fb14153bb4f12d2020a1f7d%7C0%7C0%7C638220742404243218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zkCvXmSDbkVErTqdigAL9swZpGf2wXxsrYa0PcGcY5I%3D&reserved=0) for more details.

Current chunking size:

1 Hour

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

CenterofExcellenceCoreComponents_4_4_2

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
This mail is intended to let you know that you need to continue making these chunks smaller to hopefully be able to cover your tenant usage. You can try down to 1 minute (see below for help with that), then if you still get the error you may just be too large to work with the existing custom connector solution. 

Because of the way the backend we are using works, we see other office operations (ex boot excel) so the number of records here balloons quickly. You could try 1 minute chunks

- TimeSegments-CountLimit: 1500
- TimeInterval-Unit: Minute
- TimeInterval-Interval: 1

But if that does not work then I'm afraid there is nothing we can do about this until we re-plat to the BYODL (Self Service analytics) where the logs will be more natively gathered rather than via this custom connector

Good news is that we are now in preview in which you can use the Data Export feature of the product instead of the office audit logs. You can explore this product feature here: [Set up Microsoft Power Platform self-service analytics to export Power Platform inventory and usage data (preview)](https://docs.microsoft.com/power-platform/admin/self-service-analytics)

And read about the CoE Starter Kits integration with it here: [What data source should I use for my Power Platform inventory?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory)

**Comment by Krishi27** [comment]
Hello Jenefer,

Thanks for the email, is there any possibility that we can connect over call and you can guide on how to make the chunks smaller as we are new to this COE ???

Krishnakumar G
Support specialist | Messaging & Collaboration

[Icon  Description automatically generated]

M: +91 6380890157

Follow NIQ:
LinkedIn<https://www.linkedin.com/company/nielseniq/> | Twitter<https://www.twitter.com/nielseniq> | Facebook<https://www.facebook.com/NielsenIQ.global/> | Instagram<https://www.instagram.com/nielseniq/> | YouTube<https://www.youtube.com/channel/UCYgAtbXKtOHSPlF81g56c3w>

**Comment by Jenefer-Monroe** [comment]
Note also that we just released a new version of this for the sync flow architecture that no longer suffers from the paging requirement. Plese see these notes:

### Audit Logs - NEW

Hello, here are a few things to note. 

Audit logs in the past:
In the past audit logs were collected by a solution separate from Core as the setup for them requires additional permissions. Please see [Set up the audit log connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog)
They were subject to a chunking issue that people would hit if there was too much traffic in their tenant that led to missed launches.
And as they were based on a custom connector they had issues with upgrade and needed to be fixed periodically as described here: https://github.com/microsoft/coe-starter-kit/issues/1424

New technique:
We do offer a new technique that is not subject to these custom connector limitation. And the custom connector technique will be deprecated in August 2023. See https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http

The new technique does have a different API requirement in the app registration though, so please review that carefully and be sure to change from delegated to application permissions if you re-use the old app registration.

In either technique: 
Audit logs begin to collect data from when they are turned on, they do not go back and get historical data. There is a helper script for getting old logs though described here: [How to get older data](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#how-to-get-older-data)

**Comment by Jenefer-Monroe** [comment]
We are a very small team and cannot meet with our GitHub customers. However, we have many partners that offer CoE install and configuration services - you can find them via AppSource: 
https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1

**Comment by Krishi27** [comment]
Could you share the steps on how to set 1 min chunk ?

Krishnakumar G
Support specialist | Messaging & Collaboration

[Icon  Description automatically generated]

M: +91 6380890157

Follow NIQ:
LinkedIn<https://www.linkedin.com/company/nielseniq/> | Twitter<https://www.twitter.com/nielseniq> | Facebook<https://www.facebook.com/NielsenIQ.global/> | Instagram<https://www.instagram.com/nielseniq/> | YouTube<https://www.youtube.com/channel/UCYgAtbXKtOHSPlF81g56c3w>

**Comment by Krishi27** [comment]
While Importing the solution, we did not specify any current value and now the default value is set. Is there any possibilities that this can be edited as these variables are in Managed Solution ??



***@***.***

Krishnakumar G
Support specialist | Messaging & Collaboration

[Icon  Description automatically generated]

M: +91 6380890157

Follow NIQ:
LinkedIn<https://www.linkedin.com/company/nielseniq/> | Twitter<https://www.twitter.com/nielseniq> | Facebook<https://www.facebook.com/NielsenIQ.global/> | Instagram<https://www.instagram.com/nielseniq/> | YouTube<https://www.youtube.com/channel/UCYgAtbXKtOHSPlF81g56c3w>

**Comment by Jenefer-Monroe** [comment]
Thats correct. They have a default value. You can see how to update current values for env vars with this link:

> Sure.
> 
> They are environment variables. Which you can set as described here: [update environment variables](https://learn.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables)
> 
> And the values are what I gave you here:
> 
> * TimeSegments-CountLimit: 1500
> * TimeInterval-Unit: Minute
> * TimeInterval-Interval: 1

**Comment by Krishi27** [comment]
Thanks a lot, this worked :)

**Comment by Jenefer-Monroe** [comment]
Wonderful news, thanks for letting us know. I'll go ahead and close then but please let us know if you have other questions in the future
