### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Logs

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5787]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

Why we need "ActivityFeed.Read"  Application Permissions in Office 365 Management API custom connector for Audit Logs?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 19th 2023

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
We just use what's provided by the Office 365 Management API here:
https://learn.microsoft.com/en-us/office/office-365-management-api/get-started-with-office-365-management-apis#specify-the-permissions-your-app-requires-to-access-the-office-365-management-apis

You can learn more about this API here
https://learn.microsoft.com/en-us/office/office-365-management-api/

**Comment by lingutla123** [comment]
Thank You.
