### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unable to create Teams connector during CoE Setup

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#5788]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When creating connections for the CoE, the Teams one fails, and I cannot create it. Getting error:

Troubleshooting details
If you contact your administrator, send this info to them.
Copy info to clipboard
Request Id: 674adfc5-9717-4883-a45d-63ffefe64a00
Correlation Id: 60876a98-0ba6-4cb2-bae1-dca5375558e7
Timestamp: 2023-06-12T17:15:38Z
Message: AADSTS50011: The redirect URI 'https://global.consent.azure-apihub.us/redirect/teams' specified in the request does not match the redirect URIs configured for the application 'App GUID (not sure if sensitive, so removed)'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.
Flag sign-in errors for review: Enable flagging
If you plan on getting help for this problem, enable flagging and try to reproduce the error within 20 minutes. Flagged events make diagnostics available and are raised to admin attention.

When going to  'https://global.consent.azure-apihub.us/redirect/teams' in the browser, it gives:
{"Message":"Redirect URI (https://global.consent.azure-apihub.us/redirect/teams) did not receive an expected state query parameter from the authorization service (Referer: not found)."}

In GCC tenant, but unsure how to proceed at this point.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

if I read this right, you're seeing the issue when you follow these steps to create connections for all the connectors the solution uses
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections

If that's right, that's just product capabilities outside of the scope of what we can help you with. 

The Teams connector is supported in GCC regions, here's some tips on creating a connection from the Microsoft Teams connector website
https://learn.microsoft.com/en-us/connectors/teams/#creating-a-connection

If that doesn't help, you'll have to go through regular Microsoft Support channels to get assistance. We can only help with issues specific to the CoE kit - those that occur once you import the solution!

**Comment by pnoot7** [comment]
I have a lab from a class with a commercial tenant and it works there. I will open a ticket with MS Support.

**Comment by pnoot7** [comment]
Microsoft support confirmed a known issue in the GCC space, but refused to post a service advisory. It is fixed at this time.

**Comment by Jenefer-Monroe** [comment]
Wonderful news, thanks for letting us know!

**Comment by jayakumarkgds** [comment]
> Hello,
> 
> if I read this right, you're seeing the issue when you follow these steps to create connections for all the connectors the solution uses https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections
> 
> If that's right, that's just product capabilities outside of the scope of what we can help you with.
> 
> The Teams connector is supported in GCC regions, here's some tips on creating a connection from the Microsoft Teams connector website https://learn.microsoft.com/en-us/connectors/teams/#creating-a-connection
> 
> If that doesn't help, you'll have to go through regular Microsoft Support channels to get assistance. We can only help with issues specific to the CoE kit - those that occur once you import the solution!

I am facing same issue with China 21v Tenant.Not able to create teams connector. Is there anyway without teams connector we can proceed the setup?Which version support without teams connector?
