### ISSUE TITLE
[CoE Starter Kit - BUG] Gettting Error For Setting PowerBI Report after upgrading to June 2023

### ISSUE THREAD

**Issue by salviroshan89** [microsoft/coe-starter-kit#5789]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have just upgraded the CoE solution to June 2023 and after upgrading tried to load "Production_CoEDashboard_June2023" power bi report to publish it. However getting attached error while loading the data and also getting error on refresh. 

Could you provide a fixed powerBi ""Production_CoEDashboard_June2023"" file please
![PowerBIError2](https://github.com/microsoft/coe-starter-kit/assets/108810665/20447d56-2f85-47af-b1cd-cb622bc9c4fa)
![PowerBIError1](https://github.com/microsoft/coe-starter-kit/assets/108810665/b792a3ca-a2fa-4dc7-b05e-ae1795d9d143)

### Expected Behavior

Production_CoEDashboard_June2023 should work with no issues

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Production_CoEDashboard_June2023

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Download June 2023 CoE Kit 
Double click on Power BI file "Production_CoEDashboard_June2023" and enter Org URL.
Notice attached error after few minutes on loading
![PowerBIError1](https://github.com/microsoft/coe-starter-kit/assets/108810665/57c82c63-150a-4747-9f4d-efe83b8e49f6)

**Comment by djtrustgod** [comment]
FYI - I just did the update to June release from April 2023 release and did not experience this issue.

**Comment by Jenefer-Monroe** [comment]
Please see if a refresh resolves for you. Occassionally I see people need to do a refresh for some reason.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
