### ISSUE TITLE
 Center of Excellence - Governance Components. - missing msdyn_FlowApprovals for install

### ISSUE THREAD

**Issue by Miled122** [microsoft/coe-starter-kit#5790]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

[{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: CenterofExcellenceAuditComponents. Some dependencies are missing. The missing dependencies are : <MissingDependencies><MissingDependency><Required type=\"1\" schemaName=\"msdyn_flow_approvalresponse\" displayName=\"Approval Response\" solution=\"msdyn_FlowApprovalsCore (2.0.4.3)\"><package>msdyn_FlowApprovals (2.0.4.3)</package></Required><Dependent type=\"29\" displayName=\"Admin | Inactivity notifications v2 (Check Approval)\" id=\"{6c0522f0-6256-eb11-a812-000d3a996adc}\" /></MissingDependency></MissingDependencies> , ProductUpdatesOnly : False","ErrorCode":-2147188707,"AdditionalInfo":null}]

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.9

### What app or flow are you having the issue with?

CenterofExcellenceAuditComponents_3.9_managed

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
