### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION: New record in Environment table after upgraded from Sandbox to Production

### ISSUE THREAD

**Issue by miroslav-harlas** [microsoft/coe-starter-kit#5799]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,
I have a questions about upgrading environments from Sandbox to Production. I have noticed that when Environment SKU is upgraded from "Sandbox" to "Production" the new ID is generated, the Production env. has a new name and it is recognized as a new environment by CoE Starter Kit and new record is created in Environment table. This is causing a lost of some details, which we manually entered for environment while it was a Sandbox environment.

Questions:
- Could we use some CoE Strater Kit field in some table to recognize that specific record of Production Environment is related to another older record of the Sandbox environment?
- Is there any built-in feature in CoE Starter Kit to perform this upgrade from "Sandbox" to "Production" to avoid mismatch/lose of Environment data?

Thank you very much in advance for reply.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

December 2022

### What app or flow are you having the issue with?

Admin - Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I do not repro this. Converting from sandbox to production does not change the evnt id, org id, nor the url for me. 
Can you test again with a sample envt and see if this occurs for you? If so what region are you in?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a03fb1f3-7dc7-4144-ab0d-05cebe2b9c00)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
