### ISSUE TITLE
500 error on repo creation

### ISSUE THREAD

**Issue by Nohj101** [microsoft/coe-starter-kit#58]
Testing project creation from the ALM Accelerator for Makers after setting up the COE Starter Kit, and we have an issue on the create repo step.  It gives a 500 error, and gives a general error of "Cannot create repo with name ****"

We are using a non-paid git hub org account setup.

{
    "statusCode": 500,
    "headers": {
        "x-ms-workflow-run-id": "08585855019469477994336743357CU53",
        "x-ms-correlation-id": "d7190980-78c4-4871-9963-2844111e9f86",
        "x-ms-client-tracking-id": "08585855020515451346868756993CU78",
        "x-ms-trigger-history-name": "08585855019469477994336743357CU53",
        "x-ms-execution-location": "westus",
        "x-ms-workflow-system-id": "/locations/westus/scaleunits/prod-109/workflows/2e83030f9f664db6bba1fe7800c25f65",
        "x-ms-workflow-id": "2e83030f9f664db6bba1fe7800c25f65",
        "x-ms-workflow-version": "08585855072469115110",
        "x-ms-workflow-name": "f3e8da8e-f407-a2fa-1662-c5187c99fbe1",
        "x-ms-tracking-id": "1f2a83f7-4a2c-4412-b417-4eaef40d0d9f",
        "Content-Type": "text/plain; charset=utf-8"
    },
    "body": "Error Creating Repo with name thistime"
}

![image](https://user-images.githubusercontent.com/60517236/111705730-2c0f0180-880f-11eb-8e60-2c18d3015b59.png)

**Comment by mikefactorial** [comment]
Hi @Nohj101,
Pardon the delay. This repo isn't currently active. We're in the process of transitioning CoE Starter Kit here, but for the time being would you mind posting this issue to https://github.com/microsoft/powerapps-tools/issues?
