### ISSUE TITLE
[CoE Starter Kit - BUG] Dashboard not showing orphaned flows and apps

### ISSUE THREAD

**Issue by JawnLegend** [microsoft/coe-starter-kit#5800]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The CoE dashboard does not show any orphaned data. The orphaned flows shown in the screenshot are from old environments, that were deleted months ago. The email clearly depicts that they're orphaned flows that are not displayed in the dashboard.

### Expected Behavior

All orphaned flows and apps are shown in the dashboard.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May release

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Go to the dashboard
2. Go to Flows page
3. Filter on Blank users

### Anything else?
![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/e3112b2f-6705-4ab0-a763-0fd6a5c82362)
![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/1c1faa0f-9f09-47f1-a397-f24808f285b0)

**Comment by Jenefer-Monroe** [comment]
1. Can you please go to the PPAdmin App and lookup this flow id? 
- Who is listed as the owner?
- Is it marked as orphaned?

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a0af8e69-718c-4583-97bf-0b0217ad4afc)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/15080fe1-decf-426d-8ee4-717fe463a4dc)

2. And also please let me know what value you have for this environment variable? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3b39e4a-4e1a-4c5c-9b04-b287e37c6436)

3. And when were these two flows last run? And did they pass? 
- CLEANUP - Admin | Sync Template v3 (Check Deleted)
- CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

**Comment by JawnLegend** [comment]
Hi, 

I've checked and found the following:


**1. Can you please go to the PPAdmin App and lookup this flow id?**

- Who is listed as the owner?
A user in the default environment (he's no longer a part of the AAD)
- Is it marked as orphaned?
It's not been marked as orphaned by the CoE (see below screenshot)

![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/60dcabd9-7bd5-4d37-bcbc-eb6dd2127bec)


**And also please let me know what value you have for this environment variable?**
See below screenshot:

![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/977637f1-9c44-4655-969e-ee32b69e5d53)


**And when were these two flows last run? And did they pass?**

The CLEANUP - Admin | Sync Template v3 (Check Deleted) flow has never run.
![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/999b7292-01ea-42ca-b97a-d7ca38910c93)



The CLEANUP - Admin | Sync Template v3 (Orphaned Makers) has run  4 times. 
![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/e0c653c6-30cb-4034-8aa8-d612e2b61453)

**Comment by Jenefer-Monroe** [comment]
Is the user removed from the AAD or just marked disabled? 
Do you know when he was removed/disabled?

**Comment by JawnLegend** [comment]
It's removed from the AAD entirely - it was removed last month.

**Comment by Jenefer-Monroe** [comment]
ok you will need to dive into that last run then and debug. 

1. Open the output of this call to **_List Makers_** and find your user in the list, note its location in the array
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2bf82412-acf9-4930-a125-1d48f56fc1fe)

2. Expand **_Apply to each maker_** and go to that iteration. What is returned? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/077281bc-2581-4064-91df-ee69c22cdb84)

**Comment by JawnLegend** [comment]
This is what I found out with the user:

![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/71433c6d-1e38-4149-ac78-44621df07124)

**Comment by JawnLegend** [comment]
Ok. I went down that path and downloaded the output of the "List flows of maker," and the output is empty. See screenshot:

![image](https://github.com/microsoft/coe-starter-kit/assets/105429761/e24c71e8-74dc-47c9-9733-56cf8972ced0)

**Comment by JawnLegend** [comment]
Any updates on this?

**Comment by JawnLegend** [comment]
Of course! Sorry, it wasn't intended to come off as anything less than guidance and assistance.

**Comment by Jenefer-Monroe** [comment]
Can you please go find that flow again the PP Admin View app? 
Edit Columns and add in the **Flow is Orphaned** column. What does it show in that field for this flow?

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/17255072-2eef-4729-8899-2db88391ef2b)

**Comment by JawnLegend** [comment]
Hi. It shows that the flow is orphaned with multiple other orphaned flows from the previous owner.

**Comment by JawnLegend** [comment]
Great. In that case, how would I then be able to see orphaned flows in the dashboard? I usually filter on Owners as (Blank).

**Comment by Jenefer-Monroe** [comment]
You would have to add the filter yourself for now. 
We can add updating it to our backlog as well. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/42e10485-d616-4e49-a49d-282bacc816b4)

**Comment by manuelap-msft** [comment]
Working on the PBI refresh this month and have added this in. As part of the PBI refresh we consolidated a few pages and updated the look of the report, but you'll be able to filter to orphaned makers on all pages with the August release. 

![Image](https://github.com/microsoft/coe-starter-kit/assets/55705669/a7b58038-ba9b-4e41-9238-80a4e0654f0f)
