### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Logs

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5801]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The Audit Log flow ran successfully but i don't see data in Power Platform Admin View.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/f495e707-4cfb-423f-8db4-0f96e88ee20f)

I added "ActivityFeed.Reed" App Permission in office365 API Management.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 19th 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Audit logs begin to collect data from when they are turned on, they do not go back and get historical data. There is a helper script for getting old logs though described here: [How to get older data](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#how-to-get-older-data)

**Comment by lingutla123** [comment]
I turned on yesterday afternoon. Till now no data is not showing.

**Comment by Jenefer-Monroe** [comment]
Which of these mechanisms to collect auditlogs are you using? 
- [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)
- [Collect audit logs using a custom connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog)

**Comment by Jenefer-Monroe** [comment]
Ok thank you for that detail. We shipped a bug in the first version where the string you send in here has to be all lower case. 
So plesae rerun this step with the work **_start_** all lower case.


![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4e9f6389-21f0-412c-9126-facb781eef7f)

**Comment by lingutla123** [comment]
I reran this step with the work start all lower case letters. No data showing.
Do we need to turn on Audit logs in COE env?
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/fdf3abfe-dcf8-4749-9f9b-f1e3f890e57e)

**Comment by lingutla123** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/03641c2e-5b59-4f38-becd-c2a8602d5990)
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/fe02a01b-8ae3-4dd7-b5b0-31399f7e8543)
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/bfacea5d-02cd-4338-a996-bd7daf3f2181)

**Comment by Jenefer-Monroe** [comment]
ok great. then your subscription is going. 
Please continue with the setup: https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#turn-on-flows

**Comment by lingutla123** [comment]
In Audit Log Search everything disabled.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/29dd7fb9-8b68-47a5-82fc-46d8b82f2f5c)

**Comment by Jenefer-Monroe** [comment]
Please review our list of common issues. This is outside the context of the kit unfortunately, just a product feature and so if you are unable to access or use, and the below does not help, you will need to reach out to product support. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/99102040-3704-44d4-ae29-d34a8019369d)
