### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI: Power Platform Administration Planning errors

### ISSUE THREAD

**Issue by nyoung30** [microsoft/coe-starter-kit#5802]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The _Power Platform Administration Planning_ Power BI report has numerous errors related to the **pcat** columns.

![image](https://github.com/microsoft/coe-starter-kit/assets/25697904/af353691-356a-4dc1-b775-923c9455a482)
![image](https://github.com/microsoft/coe-starter-kit/assets/25697904/230b531b-4f22-444e-85ea-f306af82d47d)

### Expected Behavior

No broken report visual and no invalid expressions

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

Power Platform Administration Planning.PBIT

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

New set up the Microsoft Power Platform administration planning component. See https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-admin-tasks-component#set-up-the-power-bi-dashboard

**Comment by nyoung30** [comment]
Taking a second look at this and I may installed the [Power Platform admin task planner components](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-admin-tasks-component) out of order. Please cancel/delete/close this issue.

**Comment by Jenefer-Monroe** [comment]
Thanks for debugging!
