### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by fosttj** [microsoft/coe-starter-kit#5804]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The issue I am having is the Admin | Audit Logs | Sync Audit Logs (V2) keeps failing to run because the environment variable admin_AuditLogsClientAzureSecret is blank. We operate in the Azure GCC domain and do not have approval just yet to use Azure Key Vault and according to the description for the variable, use it only if you have stored the secret in Azure Key Vault, the reason it is blank

### Expected Behavior

The expected behavior is that the Sync Audit Logs (V2) should not fail because this environment variable is blank.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Ensure that the CoE Environment variable admin_AuditLogsClientAzureSecret is blank
Run Admin | Audit Logs | Sync Audit Logs (V2)

**Comment by fosttj** [comment]
My mistake, the error is further down in the flow and has to do with permissions and not the Azure Key Vault variable.

**Comment by Jenefer-Monroe** [comment]
No problem, thank you for letting me know!
