### ISSUE TITLE
[CoE Starter Kit - BUG] Flow Action Details - Array Variable Limit of 100000 Exceeded

### ISSUE THREAD

**Issue by michael-wright-pwc** [microsoft/coe-starter-kit#5806]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

"Append http action" is failing with error message: `BadRequest. The number of array items in variable 'ActualFlowActionDetails' reached the limit: maximum '100000' and actual '100000'.`

It's not letting me attach a screenshot - let me know if you want me to email it to you

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by michael-wright-pwc** [comment]
That's fantastic! Appreciate the quick response. Sorry for not finding the related issue - I tried searching by the error message and couldn't find it. Feel free to close this issue.

**Comment by manuelap-msft** [comment]
No worries, it took me a few minutes too to find the old issue - I just knew we had one ;)
