### ISSUE TITLE
[CoE Starter Kit - BUG]  CustomAzureDevOps.GetPullReqeust failed: _scrubbedSensitiveData_

### ISSUE THREAD

**Issue by itAppsDevNog** [microsoft/coe-starter-kit#5807]
### Describe the issue

This error started to appear last week when using ALM Accelerator App.
Error occurs when app calls Custom Connector Operations like GetPullReqeust or the operation to start deployment, receiving error messages like _scrubbedSensitiveData_

### Expected Behavior

ALM Accelerator App can successfully obtain Pull Requests and complete its deployment process of solutions.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230606.1

### Steps To Reproduce

1. Open ALM Accelerator App
2. Wait for CustomAzureDevOps.GetPullReqeust to be called
3. Error occurs

This is another scenario where error occurrs
1. Start Deployment of solution
2. Specify Details and description
3. Click on Deployment button
4. Error occurs

### Anything else?

![ALM Accelerator App Bug](https://github.com/microsoft/coe-starter-kit/assets/118563497/df02dd43-4822-46d4-9ad3-eef182b2adc8)

**Comment by mikefactorial** [comment]
Closing this out since there's been no response in several weeks. Feel free to open a new issue if this is still a problem.
