### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to Share Connection In Deployment Settings

### ISSUE THREAD

**Issue by jfung85** [microsoft/coe-starter-kit#5810]
### Describe the issue

We are having an issue trying to use the connection sharing feature where the migration account requests a separate account to create the connection in the destination environment and shares it with the pipeline user account for use during the deployment.

After the separate account creates the connection, checks shared checkbox and saves/closes the AA4PP app, the Connections show as Connected.

When opening the AA4PP app with a different account, tried both migration account and pipeline user account, it shows as Unknown Connection and shows a GUID in the drop-down. The migration account has System Customizer permissions on the selected environment and the pipeline user has System admin permissions on the selected environment

### Expected Behavior

We expect to be able to create a connection with a different account than the one running the solution deployment. Then account running the solution deployment should be able to see the connection and use it for the deployment.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Accelerator Version: 1.0.20230517.1(Managed)

### Steps To Reproduce

1. Configure migration account to open AA4PP app with access to solution Deployment Profile
2. Configure Deployment Settings with migration account -> Go to Destination environment profile -> Under Connection References -> click the Request Connection from Another User button -> enter different account (destination service account) for connection creation-> Send the email generated to this account
3. Open email with the Destination Service Account and open AA4PP app -> Configure Deployment Settings with migration account -> Go to Destination environment profile -> Under Connection References -> Create New Connection for all Connection References needed -> Check the Share All checkbox -> Click on Save and Close
4. Go back to the AA4PP app with either migration account or also the pipeline user account ->  Go to Destination environment profile -> Under Connection References -> view connections to see Unknown status with GUIDS in the textbox -> Remove the GUID and click on Select to Choose Existing Connection -> See Dropdown displays Existing Unknown Connection

**Comment by mikefactorial** [comment]
@jfung85 this is expected behavior. There's no mechanism in the platform for interactive users to see each other's connections which is why you see the Unknown Connection. At the point at which the user created the connection and shared it we stored the id of the connection (which is what you see in that field when opening as another user) The sharing functionality only shares the connection with the Service Principal related to the service connection in Azure DevOps for the environment. So, the connections aren't shared with the other users. The UX may be a little confusing but this is the expected behavior.
