### ISSUE TITLE
[CoE Starter Kit - QUESTION] Are there known issues with App Launches for the June release?

### ISSUE THREAD

**Issue by anttipajunen** [microsoft/coe-starter-kit#5813]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I'm looking at the Audit Log table, and I see data for app launches being pulled in from the O365 Management API. The new HTTP connector for collecting them is being used. I'm looking at the "Apps" report in the June PBI and that's completely empty for "Last launched". The "App Usage" report is completely blank.

Wondering if there are any known issues around these?

History:
CoE installed in May, updated to the June release, June PBI published, audit log collection initiated as the last step.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Yes, there is a known issue. You can find the details here:
https://github.com/microsoft/coe-starter-kit/issues/5765

**Comment by anttipajunen** [comment]
Thanks Manuela.
