### ISSUE TITLE
[CoE Starter Kit - BUG] I have setup audit log connector in azure portal

### ISSUE THREAD

**Issue by NemadeUjwal** [microsoft/coe-starter-kit#5818]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have setup audit log, azure ad app and generated client od and secert also admin has granted the required permission. But still when i try to run Admin | Audit Logs | Office 365 Management API Subscription flow in core component solution from COE kit I am getting below error

{ "error": { "code": "AF10001", "message": "The permission set () sent in the request does not include the expected permission." } }

### Expected Behavior

Flow shoud show status 200 code 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

None

**Comment by NemadeUjwal** [comment]
Am I missing something ? Do i need any azure related license to run this ?

**Comment by Jenefer-Monroe** [comment]
Two areas people often miss in the [setup instructions](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http) are:

1. The API permissions must be Application (not Delegated)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/38fa4e02-7bd8-405c-9b94-6469a43fde92)

2. Not starting / validating the subscription [Start a subscription to audit log content](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

**Comment by NemadeUjwal** [comment]
![16868102796681719923445380815542](https://github.com/microsoft/coe-starter-kit/assets/99943014/22d9d812-56f6-4f6d-b362-94d124cbd5e5)
1. I have this 2 app permissions. You saying Type should not be delegated. Is my understanding correct ? How to fix it can you please help with some article URL. What should come in TYPE column if not delegated.
2. While starting the subscription itself i got the error msg.

**Comment by Jenefer-Monroe** [comment]
We show how to create this in step 6 of the [Create an Azure AD app registration for the Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#create-an-azure-ad-app-registration-for-the-office-365-management-api) section of our instructions.

I dont think you can change it, you delete that one (the delegated) and add a new one that is correctly set to application.

**Comment by NemadeUjwal** [comment]
Sure.. let me try it. 
Thanks

**Comment by alinefmr** [comment]
@NemadeUjwal if you're reusing the same AppId previously used to collect logs using the custom connector method, that version used to required delegated permissions. Granting Application permissions instead should solve the problem.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by AkshayKathuria06** [comment]
My org isn't allowing us to set up this app using application permissions and instead want to set this up as delegated permissions.
What tweaks would I need to do in order to consume this using delegated permission?
