### ISSUE TITLE
[CoE Starter Kit - QUESTION] Delete the SharePoint App Forms using Cleanup Old Objects App

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#5819]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi @manuelap-msft ,

It seems there is no support for deleting the SharePoint App forms using Cleanup Old Objects App. Is it possible to exclude these from cleanup activity?

Also, once the app/flow added to archive approval table, it doesn't listen for changes such as App launched/deleted. Did i miss anything that is already available in starter kit that updates the Archive table on daily/weekly basis? 

Thanks,
Devendra

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.9

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
These are excluded already, there was another issue in which they were not being correctly identified which has been fixed. 
Please see https://github.com/microsoft/coe-starter-kit/issues/5600

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
