### ISSUE TITLE
inconsistent use of parameters/variables in export-Solution.yml

### ISSUE THREAD

**Issue by FH-Inway** [microsoft/coe-starter-kit#582]
The export-Solution.yml template makes inconsistent use of the BranchToCreate, Branch and CommitMessage parameters/variables. In some part of some steps, the template parameters are used while in others, the variables are used.

When calling the template from a pipeline with parameters, the expectation is that the template uses the provided parameters. However, that is not the case.

This probably is not an issue for the current setup of the CoE kit, as I believe the setup ensures that the parameters will always have the same values as the variables.

My use case is different because I'm using the template in my own pipeline, ignoring the rest of the CoE it setup. Since I want to make use of dynamic user defined parameters at queue time of the pipeline, I cannot rely on statically defined variables like in the CoE kit setup.

To enable a consistent use of the template parameters, I propose the following changes:
1. **steps that contain the BranchToCreate variable in their condition**: remove the condition on that variable; instead, add a conditional insert for the step using an if expression that can make use of the BranchToCreate template parameter
1. **step that commits changes**: change PowerShell script to use CommitMessage parameter instead of variable
1. **step that pushes changes to local existing branch**: change displayName to use parameter Branch instead of variable Branch, like the other displayName of other steps do
1. **third step that pushes the changes**: change displayName and comment to refer to Branch instead of BranchToCreate to correctly reflect what the step is doing

These changes would not change the functionality of the template. The first 2 changes are the important ones, the other 2 just change displayName and a comment.

Let me know if you want me to provide a pull request with the proposed changes.

**Comment by FH-Inway** [comment]
Hey @mikefactorial , just noticed another minor issue: the template has a step to export a managed solution, but as far as I can tell, nothing is ever done with it, the .zip file just gets deleted a few steps later in the "Format JSON files" step. Is this intentional (maybe the export of a managed solution does some additional checks which the export of an unmanaged solution does not cover) or can it be removed? And if it can be removed, do you want me to include that in microsoft/coe-alm-accelerator-templates/pull/49 or should I open a separate issue/PR?

**Comment by mikefactorial** [comment]
Agree doesn't seem to be any reason for exporting the managed solution. @devkeydet can you confirm?

**Comment by mikefactorial** [comment]
Closing this issue out since we weren't able to approve the original PR.
