### ISSUE TITLE
[CoE Starter Kit - QUESTION] The CoE kit is not showing all the apps or makers. 

### ISSUE THREAD

**Issue by henryed07** [microsoft/coe-starter-kit#5821]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The CoE kit is missing some Apps that are in the default environment. All the flows have run with no errors. I'm able to see the apps in the admin centre. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please do the following:
1. Browse to the Admin Command Center > Environment Variables > What is the value for this item? 
![image](https://user-images.githubusercontent.com/89584709/230621685-2f293271-b215-4f91-8234-0f39c8f638e9.png)
2. Browse to the Admin Command Center > CoE Flows Page > Inventory. When did this flow last run and did it pass? Click Flow details to browse to it. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8603efba-6eb3-4813-a66f-475c7f8a1a22)
3. Open the most recent run. Does it make it down to this call? If so how many environments are returned? You can see this by popping it into a json parser.
![image](https://user-images.githubusercontent.com/89584709/230622587-e17a3ad2-e1d2-4d58-8a0c-255aa469359d.png)

**Comment by henryed07** [comment]
Hi, 

1. Value is no
2. 15/6/2023
3. Yes it makes it to this part and it comes back as 73 environments - and that's the number we have.

**Comment by henryed07** [comment]
Hi 

I'm unable to find the app in this output - the app is showing in the https://admin.powerplatform.microsoft.com/ view.

**Comment by Jenefer-Monroe** [comment]
That call passes and returns other apps though?

**Comment by Jenefer-Monroe** [comment]
Can you please change the pagination setting for this call to 100000 and see if it returns correctly? 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bcc9115e-6fd3-4c89-a326-9a34305105c3)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/53fe9f53-7dbe-4c4d-9246-ad0d1d4497b1)

**Comment by manuelap-msft** [comment]
Missed to close this out with July milestone. Closing manually.
