### ISSUE TITLE
[CoE Starter Kit - QUESTION] Updating Secret Value for Command Centre and Audit Logs

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#5822]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 

The secret value for the app registration for the Command Centre and Audit Logs has expired. I now have a new Secret ID and Value for the existing Application (client) ID, although I wanted to check what I need to update in the CoE. Sorry to trouble you but I couldn't find anything online on how to specifically do this and don't want to get it wrong. 

I need to update this for both the cloud flows and the BYODL Data Export CoE. i believe from memorry the BYODL doesn't need the audit log app anymore as it manages it differently. 

Could you please share a link or some guidance on what I exactly need to update for both?

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8 and 4.42

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Sorry I'm having a little trouble following. Let's handle these one at a time as a result.

First it sounds like the secret for this app registration has expired. Is that accurate? 
If so, you just need to update the secret. If you are storing as plain text you can do that right there in he Command Center app, if not, and you are storing in Azure Key Vault, then you need to update the secret using the product UX itself.
[Use Azure Key Vault secrets](https://learn.microsoft.com/power-apps/maker/data-platform/environmentvariables#use-azure-key-vault-secrets-preview)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4b58f0fb-eb1e-472f-82a3-6da6099047e9)

**Comment by Jenefer-Monroe** [comment]
Oh thats the CoE Maker Command Center, you need the CoE Admin Command Center. :

**Comment by G1982C** [comment]
Doh, thank you. Interestingly the Client ID and Secret were blank in the BYODL Admin Command Center, so I have added those in. 

Is the only other change I need to make to add the new secret to the Office 365 Management API connection? As below
<img width="658" alt="Coe1506" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/8ae0aa09-0a3d-4eca-bbe5-7b8b47300375">

Thanks

**Comment by Jenefer-Monroe** [comment]
If you are using the BYODL architecture then you dont need the audit log solution, those are native in the datalake from the product itself. Let's check that. Please browse Admin Command Center > Environment Variables > What is the value for this item? 
![image](https://user-images.githubusercontent.com/89584709/230621685-2f293271-b215-4f91-8234-0f39c8f638e9.png)

**Comment by Jenefer-Monroe** [comment]
I tested around and it looks like the documentation tells you that you need these permissions to use the secrets as an env var. 
Where both the user and the Dataverse object are **Key Vault Secret Users**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5a5ae675-cea6-41ae-94c0-3b00a9c7f8fb)

But from my testing what you actually need is this:
Where the user running the flow is both **Key Vault Secret User** and **Key Vault Contributor**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8fe1fcd4-94eb-479b-a0f4-4694f96395ec)

**Comment by G1982C** [comment]
Sorry for the late reply. For the BYODL solution this is the environment variable value that you requested above. Thanks

<img width="962" alt="Coe2206_1" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/134affeb-7133-41b5-beda-f47921db2276">

**Comment by Jenefer-Monroe** [comment]
ok you should not turn on the audit logs then if you are using the BYODL, it brings in app usage natively.

**Comment by Jenefer-Monroe** [comment]
The product's Data Export feature itself, upon which that is built, is still marked preview so we cannot mark our solution on top of it as out of preview as a result. 
Many people are using it though already for production. I'm afraid the answer will depend on your company policies.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
