### ISSUE TITLE
[CoE Starter Kit - BUG] - Admin | Audit Logs | Sync Audit Logs (V2) - flow always Fails - delegated permissions

### ISSUE THREAD

**Issue by brunoboucher** [microsoft/coe-starter-kit#5825]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Since the May update, our CoE cannot get audit logs through http using Admin | Audit Logs | Sync Audit Logs (V2) 

I follow all the instructions,( the audit logs was working with the custom connector.), but continue to got an error.
![image](https://github.com/microsoft/coe-starter-kit/assets/32851166/a548c790-809f-4802-8c83-4cec37d2cebb)
![image](https://github.com/microsoft/coe-starter-kit/assets/32851166/de817b8e-bb20-4fb7-97bc-f7daaadf1025)![image](https://github.com/microsoft/coe-starter-kit/assets/32851166/4662dbb2-c0c6-416b-a399-bfcb7167de95)

### Expected Behavior

I expected the flow collect the audits logs data

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2) 

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run the flow....

**Comment by brunoboucher** [comment]
And the var has correctly been filled

**Comment by Jenefer-Monroe** [comment]
Your API permissions are Delegated but need to be Application. Please see step 6 of the [Create an Azure AD app registration for the Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#create-an-azure-ad-app-registration-for-the-office-365-management-api) section.

**Comment by brunoboucher** [comment]
same error

**Comment by Jenefer-Monroe** [comment]
Sounds like you may have skipped this set of instructions
https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables

**Comment by brunoboucher** [comment]
;( nope done too...

![image](https://github.com/microsoft/coe-starter-kit/assets/32851166/013ef8fd-26c2-476f-8eb7-d15aa88e36f2)

**Comment by brunoboucher** [comment]
Any idea ?  I reviewed the configuration and all settings seems to be the same specified in the documentation.

**Comment by anttipajunen** [comment]
I hopped to 4.9 from 4.3 and had to review my KeyVault pretty thoroughly according to docs, and changed the AAD app from delegated to application. I noticed there was a delay of  ~10 minutes before Power Platform picked up any changes made to KeyVault. KV docs:
https://learn.microsoft.com/en-us/power-apps/maker/data-platform/environmentvariables#configure-azure-key-vault

Note:
_We have recently changed the security role that we use to assert access permissions within Azure Key Vault. Previous instructions included assigning the Key Vault Reader role. If you have set up your key vault previously with the Key Vault Reader role, make sure that you add the Key Vault Secrets User role to ensure that your users and Dataverse will have sufficient permissions to retrieve the secrets._

Happy hunting! I've always struggled with env vars that use secrets from KV.

**Comment by Jenefer-Monroe** [comment]
I tested around and it looks like the documentation tells you that you need these permissions to use the secrets as an env var. 
Where both the user and the Dataverse object are **Key Vault Secret Users**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5a5ae675-cea6-41ae-94c0-3b00a9c7f8fb)

But from my testing what you actually need is this:
Where the user running the flow is both **Key Vault Secret User** and **Key Vault Contributor**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8fe1fcd4-94eb-479b-a0f4-4694f96395ec)

**Comment by brunoboucher** [comment]
ok I test that ;)

**Comment by brunoboucher** [comment]
@Jenefer-Monroe  do you have any idea what I can check ...  I still got the same error but everything is like the doc...

**Comment by Jenefer-Monroe** [comment]
Did you update the permissions in the key vault per the above note?

**Comment by brunoboucher** [comment]
oh sorry ;P I was thinking you answered to anttipajunen ....   I'll update and give you some news

**Comment by brunoboucher** [comment]
> Did you update the permissions in the key vault per the above note?

After validation, why I need this when i don't use keyvault ?

**Comment by Jenefer-Monroe** [comment]
oh you dont. I was updating lots of bugs and didnt notice yours was plain text.

**Comment by Jenefer-Monroe** [comment]
Please go to the latest run of the flow
Do you see your secret getting set to this variale here? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0bef61fb-4086-478f-aaff-52a5d9a9fa97)

And then do you see the Secret_AzureType variable getting set to false as shown here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3dc68e4f-4086-4f54-a1ea-677c20fafadc)

**Comment by brunoboucher** [comment]
Yes and Yes
![image](https://github.com/microsoft/coe-starter-kit/assets/32851166/d3e20306-ee66-4041-83f0-e5427bc68acb)
![image](https://github.com/microsoft/coe-starter-kit/assets/32851166/418ab16d-337c-4597-b167-fb4dea337581)

**Comment by Jenefer-Monroe** [comment]
I really dont know then. Its failing but also returning with an unauthorized note but also returning data. 
Pulling in Pete to see if he can assist in investigation here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0b5ce91e-31b6-4e8a-a3c4-6ef3793c9133)

**Comment by pete-msft** [comment]
@brunoboucher, just double checking... so you have configured and granted application permissions for the service principal and you are using plain text client secret like below? And you have started the Office 365 Management API subscription?

<img width="319" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/120018333/3625cd60-f5b2-402b-b04c-537782d3dd9f">
<br><br>
<img width="348" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/120018333/15b50c25-4e68-48ad-904f-416fc020fbb1">

As you are not using KeyVault here then this action fails which is fine as it is handled exception
<img width="348" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/120018333/c37b38f3-4bd7-4b28-aac6-004123491d69">


ListAuditLogContent HTTP action is failing right? Can you check what is the error there? I set wrong client secret just for testing purposes and got this. If the flow fails here then that is what we need to investigate

<img width="503" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/120018333/2abfe326-cd81-468c-ba8a-c893e1710bd9">

**Comment by brunoboucher** [comment]
Hi @pete-msft , 
Yes application permission has been grant like the doc :
![image](https://github.com/microsoft/coe-starter-kit/assets/32851166/c1ed0937-2a4e-4616-96a8-fd6915a56e0d)

And yes is the HTTP action is failling.. in the audit logs and for start a subscription..same error

**Comment by brunoboucher** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/32851166/d67c453c-26c3-4f7d-9516-44ccea193bb2)

**Comment by brunoboucher** [comment]
@pete-msft  and @Jenefer-Monroe 
finally, the first problem I'v corrected with Jenefer to change my app registration from delagated to application was the good fix.

Finally the recent error was du to our Conditional Access ...

Now is working fine !
Thanks for your support

**Comment by pete-msft** [comment]
OK good that it is working now! Can I ask what kind of CA policy was causing that issue? 😊

**Comment by brunoboucher** [comment]
The CA refuse the connexion du to IP restriction
This range wasn't authorize

**Comment by mrmonto1** [comment]
Hello, I am experiencing a similar issue with the COE gathering audit logs with the HTTP Connector. My Admin | Audit Logs | Sync Audit Logs (V2) flow is running successfully hourly, but no new data is being populated in the Dataverse Audit table.  The only data I have in the Audit table is from the manual import I ran via the Admin | Audit Logs | Load events from exported Audit Log CSV file Flow when initially deploying the COE. I am able to run Audit Searches via the Purview Compliance Portal. How can I ensure that my App Reg configs are correct?

**Comment by Jenefer-Monroe** [comment]
We did ship originally with a bug that blocked non-commercial clouds (eg GCC) from working, its fixed in the August release, please see https://github.com/microsoft/coe-starter-kit/issues/6075
