### ISSUE TITLE
[CoE Starter Kit - QUESTION] Secure Data Export feature

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5828]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there any way to secure the Azure Data Lake (BYODL) further? At this point, for our customers to use the feature, they will need to "Enable public access from all networks" which is a big drawback.

Can we at least provide password protection via KeyVault? Or IP-range block the access somehow?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I'm afraid this is a question / feedback for the product team and not us, we are just consumers of that feature.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
