### ISSUE TITLE
[CoE Starter Kit - QUESTION] Last Launched flows

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5829]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

how do we activate the audit for last-launched flows?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
