### ISSUE TITLE
[CoE Starter Kit - QUESTION] Exclude Dynamics system flows from inactivity approval requests

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5831]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am getting approval requests for an unused flow "Project Service Core - Abandon Open Operation Set" and "Project Service Core - Abandon Pending Operation Sets". Those appear to be Dynamics related but we dont actively use Dynamics. Should this be excluded as a "system flow" 

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Our recommendation here woudl be for you to manually exclude them like you would any other environment.
Please see [Exempt environments from the inactivity notifications process](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components#exempt-environments-from-the-inactivity-notifications-process)
