### ISSUE TITLE
[CoE Starter Kit - QUESTION] What API permissions are needed for the Audit Log App Registration?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5832]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What API permissions are needed for the Audit Log App Registration?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Office 365 Management API > Application permissions > ActivityFeed.Read.
Please see [Create an Azure AD app registration for the Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#create-an-azure-ad-app-registration-for-the-office-365-management-api)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
