### ISSUE TITLE
[CoE Starter Kit - QUESTION] Estimate cost of BYODL / Data Export

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5833]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

For the BYODL option - are there any guides or recommendations to help us estimate the potential costs (I.e. how can we gather the data to populate the pricing calculator)?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We do not have such a thing, this would be a great ask for the product team as well given its the Data Export feature you are asking about cost for.

**Comment by manuelap-msft** [comment]
There's some information on what amount of data to expect in the product documentation here
https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics#data

Closing out as not related to CoE kit.
