### ISSUE TITLE
[CoE Starter Kit - QUESTION] Are apps and flows that have a co-owner or where we have reassigned ownership still considered orphaned (blank) in the DLP Editor V2 Impact Analysis?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5836]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Are apps and flows that have a co-owner or where we have reassigned ownership still considered orphaned (blank) in the DLP Editor V2 Impact Analysis?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The DLP tool does not relate to orphans so I'm not entirely following here.
We do not consider co-owners for orphans today generally though it is on our backlog.

**Comment by Jenefer-Monroe** [comment]
No the report should show the new owner after you re-assign.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
