### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Log Chunk size

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5837]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Even after changing time frame to TimeInterval-Unit to 1 minute or 2 minute. I am getting chunk size issues in Audit log flows. Also the account by which Audit log flows are running, for child audit log flow, it logs more than 250k - 300k calls each day. This eventually slow down the process and cancel after 5-6 days.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
If 1 minutes chunks do not work then I'm afraid you are just too large for the audit log solution.
You will need to move to the BYODL architecture in order to collect usage as that format stores the usage natively from the product itself rather than scraping from the office audit logs.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
