### ISSUE TITLE
[CoE Starter Kit - QUESTION] Are there embedded Power Apps for the Power BI reports designed for BYODL data tables, or are there additional configuration steps to set these up?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5838]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Are there embedded Power Apps for the Power BI reports designed for BYODL data tables, or are there additional configuration steps to set these up?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We have not yet done the work to add those to the PBIT file but it is on our backlog.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
