### ISSUE TITLE
[CoE Starter Kit - QUESTION] If a flow is deprecated does that mean that we should turn it off?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5839]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

If a flow is deprecated does that mean that we should turn it off?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The only deprecated flows we have are for the audit logs. We have suggested moveing to [collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http) at which point you would be able to delete that audit log solution

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
