### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Log Switch case

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5840]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I saw Audit Log Flow is using Switch case for (1) Launch PowerApps Case (2) Delete PowerApps Case (3) DeleteFlow Case. Can we break the flow logic to handle the scenarios independently, so that flow will close quickly within a day, rather taking 3 days - 6 days.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Can you provide more detail on what you are thinking here? I'm not seeing the path that this woudl bring the run time down substantially but happy to learn.
