### ISSUE TITLE
[CoE Starter Kit - QUESTION] Where can we find which tables are being used to store the metric values in dataverse that the Power BI CoE surfaces?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5841]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Where can we find which tables are being used to store the metric values in dataverse that the Power BI CoE surfaces?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I dont understand this question, if you posted it, please hop on and provide some more details.
