### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is "Managed Environment" configuration captured somehow as a part of the environment inventory?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5842]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is "Managed Environment" configuration captured somehow as a part of the environment inventory?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
@miroslav-harlas I think this question came from you. Yes this is available via the Power Platform Admin View > Environments > You can select Managed Environments
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/ed8a669c-b896-46b0-b6d7-3331af316e64)

If you want to use this for your own processes, you're looking for the Governance Protection Level field with "Standard" as value (unmanaged environments have "Basic" as value)
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/c614f5b3-fd51-4c6d-a383-f32e1d400f0d)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
