### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE installed in two environments - do I need two different app registrations?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5843]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have 2 environments installed with COE. My doubt is like dose both environments
require two different app registration, client Id & secret or one would work??

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
One will work. Thats how we do it with our test environments as well.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
