### ISSUE TITLE
[CoE Starter Kit - QUESTION] Will the CoE still be able to gather solution data after the Dataverse (Legacy) connector goes away?

### ISSUE THREAD

**Issue by thso77** [microsoft/coe-starter-kit#5846]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Many of the Sync Flows currently use the Dataverse (Legacy) connector to gather data. However, Microsoft plans to get rid of this connector in the near future: [](https://learn.microsoft.com/en-us/connectors/commondataservice/). 

I am particularly concerned for solutions, because the Power Platform Solutions table is populated by using this connector. My company currently has some custom apps built on top of this table. How will the Power Platform Solutions table get populated after this connector goes away? From my knowledge, using the Data Export to the Data Lake only gets Power Apps and Cloud Flow data.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Power Platform Solutions

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
This is actually addressed in our wiki
https://github.com/microsoft/coe-starter-kit/wiki/Issue-triage-(CoE-Starter-Kit)#why-are-some-flows-still-using-the-dataverse-legacy-connector-when-its-been-marked-for-deprecation

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
