### ISSUE TITLE
[CoE Starter Kit - BUG] Inventory Flow for Flows Failing

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5851]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Sync Inventory Flow (Flows) failing due to bad data request. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/34ff7db1-03a1-4bd5-9614-7e7dbcdad260)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/249e9a16-3b2e-4c8d-9080-dfc49fbaafd6)

### Expected Behavior

Fow should work normally

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023 - Hotfix

### What app or flow are you having the issue with?

Admin Sync Template (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run flow

**Comment by Jenefer-Monroe** [comment]
I believe this is the same issue as https://github.com/microsoft/coe-starter-kit/issues/5678 which no longer repros with the v4 actions. Please take a look at those notes and let me know what you think.

**Comment by nasilvae** [comment]
> I believe this is the same issue as #5678 which no longer repros with the v4 actions. Please take a look at those notes and let me know what you think.

sounds like a plan let me check if we are having the same issue regarding the derivedowner.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
