### ISSUE TITLE
[CoE Starter Kit - BUG]  PowerBI Dashboard App Archive and Cloud Flow Archive has messages sorry, there's been a disconnect.

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#5852]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/04df8d26-c235-4650-9afd-b49443d93c9e)
Not sure how to fix this disconnect any ideas?

### Expected Behavior

I am assuming I should have a page like this 
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/1359b182-2dbf-40c0-af14-f4250a9596ae)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

not sure

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

go to Power BI Dashboard App Archive shows sorry there is been a disconnect. not really sure how to fix this.

**Comment by Jenefer-Monroe** [comment]
Here are the instructions [(Optional) Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
