### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Driver) cannot be turned on ERROR

### ISSUE THREAD

**Issue by kashanico** [microsoft/coe-starter-kit#5853]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have just installed the June COE update, I have checked and there are no unmanaged layers for [CoE Starter Kit - BUG] Admin | Sync Template v3 (Driver)

![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/19b4c2a8-7ed6-4a2e-ae4d-1a46072e06fb)

![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/100f783f-45e4-4a70-b5b5-63b2d443874c)

When I go to turn the flow on I get an error:
Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '3e0762f2-4e30-4b26-aa3b-a7973f4efea9'. Connection '/providers/Microsoft.PowerApps/apis/shared_commondataservice/connections/571098f7b3524df0919a9d0f4a24bada' to 'shared_commondataservice' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".

When I go to Edit the flow and resave it I get this error
![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/06ae1724-c40e-4726-aa11-f14ec1ecaa1f)
![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/ec5f7afa-02f2-41b5-8c61-ce47559bd2ce)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Strange, I wonder if the upgrade failed? 

What solutions do you have installed in this environment? Be sure to expand the indicated columns so that we can see full names. This will let us see if something broke on upgrade.
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by kashanico** [comment]
@Jenefer-Monroe here is a screenshot
![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/dffd582d-16e5-4665-a84e-7d6eff88384a)

**Comment by Jenefer-Monroe** [comment]
Can you see if there is an unmanaged layer on the flow?

**Comment by kashanico** [comment]
Not not look like it
![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/8c851b72-7d5f-449d-92ae-34eb0b0921ae)

**Comment by Jenefer-Monroe** [comment]
no we removed that column all together. I'm not sure how it got "stuck" in yours. I've not seen that happen to other people luckily.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
