### ISSUE TITLE
[CoE Starter Kit - BUG] The New Admin Command Centre is launching deprecated apps

### ISSUE THREAD

**Issue by shriyamal** [microsoft/coe-starter-kit#5855]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The New Admin Command Center, when clicking on the Maker Command Centre from the bookmark page, it is launching the deprecated version of the Maker Command Centre. 

### Expected Behavior

Clicking on the Maker Command Centre from the new Admin Command Centre should launch the new version of the Maker Command Centre and not the deprecated version 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Please run this flow and then reload the app: **_Admin | Sync Template v3 CoE Solution Metadata_**
Let me know if that fixes it.

**Comment by shriyamal** [comment]
Hi Jenefer, I ran the flow as you suggested and refreshed the browser, and reloaded the app but it still opens the deprecated app. It's not causing any impact but wanted to let you and your team know in any case. 
<img width="581" alt="Flow" src="https://github.com/microsoft/coe-starter-kit/assets/91137553/11e47f37-e2ed-49bc-86a7-f891eafd51d6">

**Comment by Alyson95170** [comment]
I had the same, if you open the maker command centre app from the App in the solution, from here you can get the url, then you can go to the admin command centre app and update the bookmark.

![Screenshot 2023-06-20 110519](https://github.com/microsoft/coe-starter-kit/assets/82215551/5cd18077-79a5-4e98-93bb-fc307c0eb2a8)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
