### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by christosAmpa** [microsoft/coe-starter-kit#5858]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I've installed Center of Excellence - Core Components 4.8 and when accessing Production_CoEDashboard_June2023 > App Archive > Drill through > App Detail, I receive the error messages.

![image](https://github.com/microsoft/coe-starter-kit/assets/136715559/55a60249-1185-469e-a1fa-05a6087e240c)

- PowerAppsforAdmins.GetAdminApp failed: The method 'GetAdminApp' has an invalid value for parameter 'environment'

- PowerAppsforAdmins.GetAdminAppRoleAssignment failed: The method 'GetAdminAppRoleAssignment' has an invalid value for parameter 'environment'

### Expected Behavior

Identify root cause and provide a solution.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Production_CoEDashboard_June2023 PBI

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Production_CoEDashboard_June2023 > App Archive > Drill through > App Detail

**Comment by christosAmpa** [comment]
Yes

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
