### ISSUE TITLE
[CoE Starter Kit - License for COE Kit] can we install COE starter kit without power automate license?

### ISSUE THREAD

**Issue by DineshShikare** [microsoft/coe-starter-kit#5860]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Client has PowerApps per user license but not having the Power Automate license for the tenant. Client wants to install the COE starter kit for the tenant .
Is there a way to workaround to install the COE kit and execute the Power Automate/flows manually without the requirement of Power Automate license?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2023 

### What app or flow are you having the issue with?

Power automates flow

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
There is not.

Here's our license requirements
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with

And the reason for the Power Automate license
https://github.com/microsoft/coe-starter-kit/wiki/Issue-triage-(CoE-Starter-Kit)#why-is-a-power-automate-license-required

**Comment by DineshShikare** [comment]
Thank you so much for your quick response !!
