### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by ShaktiKovvuru** [microsoft/coe-starter-kit#5862]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

the flows and apps which are deleted from admin portal are not getting updated as deleted in COE power apps and flows table.

Both the flows, Admin | Sync Template v3 (Flows) and Admin | Sync Template v3 (Apps) are running successfully. please find the below screenshots.

![image](https://github.com/microsoft/coe-starter-kit/assets/134496019/9bc9ad85-1654-47cf-9c13-cfd68755b835)

![image](https://github.com/microsoft/coe-starter-kit/assets/134496019/d57be423-037e-4c1b-a594-4110d8b08506)

please advise.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows) and Admin | Sync Template v3 (Apps)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Objects are deleted from inventory by the following flow which runs every two weeks: CLEANUP - Admin | Sync Template v3 (Check Deleted)

Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
