### ISSUE TITLE
[CoE Starter Kit - BUG] Sections within the PowerBI dashboard do not display any data.

### ISSUE THREAD

**Issue by S0URCEC0D3** [microsoft/coe-starter-kit#5863]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I installed the CoE starter kit and it's been about 2 weeks already and the following areas in the Power BI dashboard isn't displaying any data.

PowerBI (Production_CoEDashboard)
- App Shares
- App Usage
- Tenant Connections
- Desktop Flows
- Desktop Flow Runs
- Desktop Flow Errors
- SharePoint Integration
- Desktop Flow Risk Assessment
- Desktop Flow Archive

Did I miss anything in the configuration or installation of the solution?

### Expected Behavior

Display all data as expected.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Installed CoE and all flows have ran for the past few weeks.

**Comment by Jenefer-Monroe** [comment]
Browse to the Admin Command Center > Environment Variables > What is the value for this item? 
![image](https://user-images.githubusercontent.com/89584709/230621685-2f293271-b215-4f91-8234-0f39c8f638e9.png)

Browse to the Admin Command Center > CoE Flows > Inventory
(Note you may see a loading error which is a product bug they are addressing, if you wait it will go away and the data will appear)
Are all flows in the on state?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/232990c4-fe6b-4acc-a180-b0c9ca14f2f9)

In this same view, filter to the CLEANUP flows, when did they last run? If the same day you installed, they may have run before the inventory was in place, rerun this set.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/502825dc-f5b1-41d8-baf7-9f5dc932e63d)

**Comment by S0URCEC0D3** [comment]
Hi Jenefer, 

From your first screenshot, the Env Variable is set to 'no'. As for the other two screenshots they are all turned on, but some of them do not have the green 'passed' icon under last run passed column. it's just blank.

Could that be the issue?

**Comment by Jenefer-Monroe** [comment]
Yes for some of these, they run infrequently (every two weeks). 
Please run this circled set
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0089658a-c797-49d9-b259-418e16b0a5e0)

**Comment by S0URCEC0D3** [comment]
Ok let me try them and I'll respond with my results. 

Thanks

**Comment by S0URCEC0D3** [comment]
Well I ran the flows and they finished successfully, but still no data displaying on the dashboards. Would this be an issue with the version? Should I upgrade to the latest version and see if that fixes it?

**Comment by Jenefer-Monroe** [comment]
No. This would not be an issue with the version. There is something wrong with your setup I believe. LEts please take the issues one at a time. Show a screenshot where you expect to see data but do not.

**Comment by S0URCEC0D3** [comment]
So started from scratch and created a new env, installed the June 23 CoE solution and now I am able to see all data besides desktop flows data in the PowerBI dash. 

I've added the screenshots of the dashboard on the desktop flows tabs and it doesn't display anything. 

I did check the flows ran with no errors and the dataverse tables have no data.


![Desktop Flow 3](https://github.com/microsoft/coe-starter-kit/assets/30586809/905c362f-2873-4f0e-9ae6-29f630013b6c)
![Desktop Flow 2](https://github.com/microsoft/coe-starter-kit/assets/30586809/c36f6050-b826-4ca9-86ad-daaceec90aec)
![Desktop Flow 1](https://github.com/microsoft/coe-starter-kit/assets/30586809/adc4f256-88a4-4042-9b53-53ca17888cc8)

**Comment by Jenefer-Monroe** [comment]
You will need to find a repro of this in your tenant to see what is going wrong. 
1. Find an environment in your tenant where you expect to see the object (desktop flow in your case)

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you were looking for missing canvas apps chose **_Admin | Sync Template v3 (Apps)_**
For you: Admin | Sync Template v3 (Desktop flows)
![image](https://user-images.githubusercontent.com/89584709/181270115-1b21a34a-5bc5-4395-ad7c-61c5873f390e.png)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://user-images.githubusercontent.com/89584709/181271431-9c71c82b-c044-41d4-ad3b-26fee240bc8e.png)

5. From here you can explore if there is a failure, or if a bad return set, etc. And let us know if you have questions

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
