### ISSUE TITLE
[CoE Starter Kit - QUESTION] Question about upgrading COE kit

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5868]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

A few months ago, I created a new Production environment and installed the COE kit (Dec 2022 release).

In April, I upgraded to the April 2023 release of the COE kit.

There is now a June 2023 release and I’m thinking of upgrading soon.

However, I realized that you recommend to upgrade every 3 months at most. 
(I unfortunately skipped the Feb 2023 release and went from Dec 2022 release to April 2023 release)

I realised that there wasn’t a January 2023 release or March 2023 release, so would I be okay to just upgrade from April 2023 release to June 2023 release?
(Or do you recommend I install the June 2023 release from scratch)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
You would be okay upgrading from April to June, as part of our release testing we do test upgrades for versions of three months back - so for the June release, we test upgrades against May/April/February (we skipped March) releases and only ship if they work seamlessly. So yes, I'd recommend you upgrade straight to June.

**Comment by firefox-edge123** [comment]
Thank you for the information. I'm so glad I can just upgrade (instead of doing a fresh re-install) :)
