### ISSUE TITLE
[CoE Starter Kit - QUESTION] English language pack not installed

### ISSUE THREAD

**Issue by qtipcore** [microsoft/coe-starter-kit#5869]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Why is it that we only have one group available in the COE Admin Command Center App?

If we edit the app, the other two groups are available, but if we play it - They disappear.
Screenshot of missing groups:
![image](https://github.com/microsoft/coe-starter-kit/assets/53943457/624aab65-7108-42a3-8b37-cfa83f2d186f)

Editing the app:
![image](https://github.com/microsoft/coe-starter-kit/assets/53943457/d217b7e9-1284-4c2d-b15c-6c648dfdd071)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

the CoE kit is only supported with the English language pack, and this error occurs if the English pack is not available in the environment. Here's the documented limitation on that:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/limitations#supported-languages

**Comment by qtipcore** [comment]
Thanks for the quick follow-up.
