### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Gokul-JB** [microsoft/coe-starter-kit#5870]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

After upgrading to the CoE April release in our environment, we noticed that the trigger event for the flow "Admin | Sync Template v3 (Flow Action Details)" was changed from "Automated flow" to "Scheduler job" (at weekly once), but this change is affecting our functionality because we consume data from the "Flow Action Details" table on a daily basis.

Can we change the scheduler job to run daily instead of weekly? If so, please let us know if there will be any impact on this change.

Flow Name: Admin | Sync Template v3 (Flow Action Details)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

None

**Comment by Gokul-JB** [comment]
Hi Team,

Any updates on this?

Thanks
Gokul J B

**Comment by Gokul-JB** [comment]
Thanks for response.

May I know when we will get 4.9 version
If we are changing schedule frequency to daily instead of weekly, will it impact anything?

**Comment by Jenefer-Monroe** [comment]
version 4.9 is out now, it is the June release. It should not impact anything except how quickly you see the values entered into the inventory.

**Comment by Gokul-JB** [comment]
Appreciate immediate response, as of now, we will change frequency by manually from this flow "Admin | Sync Template v3 (Flow Action Details)", later we will update June release.

**Comment by Jenefer-Monroe** [comment]
Makes sense. I'll go ahead and close this out then. Thank you!
