### ISSUE TITLE
[CoE Starter Kit - QUESTION] What do the Flow/App License Assignment reports mean?

### ISSUE THREAD

**Issue by MantasSal** [microsoft/coe-starter-kit#5871]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I would like to know if licenses per user and licenses per flow are covered by Premium section In Flow license assesment chart?

![image](https://github.com/microsoft/coe-starter-kit/assets/114066875/db29a4f9-c54d-41c3-b08c-cdd0a3f917cf)

Also the same question for App license assessment? What is covered by Premium? Standart licenses means Free licenses?

![image](https://github.com/microsoft/coe-starter-kit/assets/114066875/ab009a63-a433-4978-996c-ddf26ad3166e)

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

these charts don't cover the license assigned to the user, they cover if Premium connectors are used in an app or flow - so standard means only standard connectors (like Outlook, OneDrive, Teams) are used and Premium means premium connectors (like SQL, Dataverse, ...) are used. 

Hope that helps
Manuela

**Comment by nvarsha23** [comment]
Hi,
Cloud flow connections and Flow license assessment reports have same insights about the connectors used across flows. May I know the difference between these two reports?

**Comment by Jenefer-Monroe** [comment]
They really are just different visuals for the same data, thats true.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Jash718** [comment]
Is this report still available? I just installed the August 2024 version of the Coe kit and the power BI dashboard but couldn't find this template? to review the licenses
