### ISSUE TITLE
[ALM Accelerator - QUESTION] ALM Pipeline- Connection References are not showing up.

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5878]
### What is your question?

Hi Mike,

Created a new solution in dev env. Ready to commit. Before committing the solution trying to setup connection references but the Connection References are not showing up in Configuration Deployment Settings. I can see Environment Variables and Flows.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/d045bf03-22c7-4e94-acda-0956dfb72f3c)

The flow ran successfully.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/867c1217-1fb2-43ba-b3e7-a99fd6d10473)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 19th 2023

**Comment by mikefactorial** [comment]
@lingutla123 can you verify that the connection reference is, in fact, included in the solution in question? Also what comes after the branch to "Check if any results came back in Connection References" are any results returned? Finally, can you see what value is returned in the following query for your maker environment where the solution exists?

https://YOURORGNAME.api.crm.dynamics.com/api/data/v9.2/solutioncomponentdefinitions?$select=objecttypecode&$filter=primaryentityname%20eq%20%27connectionreference%27

**Comment by lingutla123** [comment]
Sorry Mike. I realized what mistake i did. Now i can see the connection references.
