### ISSUE TITLE
[CoE Starter Kit - BUG] Mashup Exception Error

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5880]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Error with CoE BYODL Flow Data Flow
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/d38598e8-be4a-43f2-a6de-5cc361c797c0)

This is the only data flow generating issues. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/23987559-1abd-4a79-9e36-51f0e96e6fa9)

### Expected Behavior

There should be no error when dataflow runs

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June Release

### What app or flow are you having the issue with?

CoE BYODL Flows

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Run Data Flows. I have also verified the authentication parameters and they are valid.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by nasilvae** [comment]
> closing out as no further action for starter kit team

The problem has not been solved. I have 3360 flows in the tenant.

**Comment by Jenefer-Monroe** [comment]
Re-opening per request. HEre is the current ask:
Can you please give us an idea of the size of this tenant's flow list? 

You will likely need to open a product support ticket

**Comment by nasilvae** [comment]
> Re-opening per request. HEre is the current ask: Can you please give us an idea of the size of this tenant's flow list?
> 
> You will likely need to open a product support ticket

I have 3360 flows in the tenant overall. Or do you mean amount of users?

**Comment by Jenefer-Monroe** [comment]
oh i see you responded with size now. I've never seen this error before and we've serviced much larger tenants. 
Please attempt a clean install with the upcoming drop and see if it repros again. May have been jsut a configuration issue.

**Comment by nasilvae** [comment]
> oh i see you responded with size now. I've never seen this error before and we've serviced much larger tenants. Please attempt a clean install with the upcoming drop and see if it repros again. May have been jsut a configuration issue.

gotcha no worries will try again see what happens once we get the new drop.
