### ISSUE TITLE
Audit Log Records are not being created

### ISSUE THREAD

**Issue by VA-smcvey** [microsoft/coe-starter-kit#5881]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

- CoE Starter Kit June Release installed (V 4.9)
- Admin | Audit Logs | Sync Audit Logs (V2) is running and successfully completing
-  #I've manually updated the Admin | Audit Logs | Sync Audit Logs (V2) to add the dynamic values per issue #5765 

I am not seeing any new audit log records being created.  Any diagnostic direction would be appreciated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2) 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please go to Admin | Audit Logs | Sync Audit Logs (V2) and open a run

1. Is there data returned from **ListAuditLogContent**?
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b5da7dc0-966a-401e-bd03-9f46928a825c)

2. How many loops does it go through for LoopContentIDs?
3. How many loops does it go through for GetAndProcessEvents?
4. Is there content returned for GetContentDetails?
5. For any of the GetAndProcessEvents loops, is there something returned from FilterEvents?

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/79191aee-fbfb-4d73-9a88-68380a1a624b)

**Comment by VA-smcvey** [comment]
Thank you for the diagnostic steps to walk thru the Sync Audit Logs (V2) flow!  Your faithful attention to these all the issues is greatly appreciated.

My answers are below:

Please go to Admin | Audit Logs | Sync Audit Logs (V2) and open a run
	_1. Is there data returned from ListAuditLogContent?_
		○ Yes
	2. How many loops does it go through for LoopContentIDs?_
		○ 1
	_3. How many loops does it go through for GetAndProcessEvents?_
		○ For the last 3 runs: 198, 148, 76
	_4. Is there content returned for GetContentDetails?_
		Yes
	_5. For any of the GetAndProcessEvents loops, is there something returned from FilterEvents?_
		○ I am not finding any output in the sampling I have done.

If the filter criteria on operateion type is not met, then that explains why no new or updated audit log records are being created
	_@or(
		equals(item()?['Operation'], 'LaunchPowerApp'), 
		equals(item()?['Operation'], 'DeletePowerApp'), 
		equals(item()?['Operation'], 'DeleteFlow'), 
		equals(item()?['Operation'], 'PowerAppPermissionEdited')
		)_

Given that the M365 audit is pulling in a lot of data that does not match those operation types, I guess the next question is how a large tenant is processed and expected to produce Audit Log records in the Starter Kit app?  Meaning, for a large tenant, how long should it take for Power app launches to start showing up in the Sync Audit Logs (V2) flow.  (I upgraded to v.49 a week ago).  With 48K Apps, I would think that some launch activity would be captured, but I admit I don't fully understand how tenant scale affects this design pattern.

**Comment by Jenefer-Monroe** [comment]
yes I would expect you to see launch activities getting logged. We did test this on very large tenants and its working so I dont think its a scale problem. I suggest you go launch a few apps yourself and then see if those launches end up showing in the list.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by VA-smcvey** [comment]
Revisiting this issue as we still do not see any new audit records being created.  Any additional diagnostic advice would be appreciated.  (i.e. to figure out if there was a configuration or parameter upstream that would affect our M365 audit query such that our audit data would not include any of the operation types necessary to create an audit record. )

Currently on the October Release (V4.16)

The preceding Parse action does have values, just no operations matching the filter.

![image](https://github.com/microsoft/coe-starter-kit/assets/53627055/ef82746c-532e-4ddf-8dae-7b1e98d2d44e)

**Comment by VA-smcvey** [comment]
@Jenefer-Monroe - FYI 

Thanks to @v7herman4 , I think we finally found the root of the issue that was causing our 'Admin | Audit Logs | Sync Audit Logs (V2)' flow to not produce any Power Apps audit records.  (this has been a 9 month mystery)

While we did have the correct environment values for GCC set per this article

[Collect audit logs using an HTTP action - Power Platform | Microsoft Learn](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables)

Commercial (Default): https://manage.office.com/

GCC: https://manage-gcc.office.com/

The http actions in the 'Admin | Audit Logs | Sync Audit Logs (V2)' were hard-coded to the commercial value (i.e., https://manage.office.com/)

![image](https://github.com/microsoft/coe-starter-kit/assets/53627055/01720922-fae0-491f-8235-10516252fe80)

![image](https://github.com/microsoft/coe-starter-kit/assets/53627055/e7d55579-f581-4f36-98ca-c9d5db96646f)

I updated the URI manually to the GCC value (https://manage-gcc.office.com/), and the flow again started creating / updating Audit records.  

Updating the actions in a future version to utilize the environment variable should fix this issue.

Regards,

Steve
