### ISSUE TITLE
[CoE Starter Kit - BUG] Invalid Pagination Policy

### ISSUE THREAD

**Issue by ricov98** [microsoft/coe-starter-kit#5883]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When turning on the following flow
Admin | Sync Template v3 (Custom Connectors),

I get the following error.
"{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Connectors' of type 'OpenApiConnection' at line '1' and column '14387' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}"

![image](https://github.com/microsoft/coe-starter-kit/assets/134672486/bb5e87c9-a67c-46d3-b39d-0b06dbc20aad)

My user account has a Power Automate per user plan so I believe that I have the appropriate license for the allowed paginations?

### Expected Behavior

The workflow should be turned on correctly.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors) and most others Sync Template v3 that has same pagination utility.

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open Admin | Sync Template v3 (Custom Connectors)
2. Turn on the flow
3. Error message is displayed

**Comment by Jenefer-Monroe** [comment]
Hello. All the flows have this pagination policy. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites]( https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with).

**Comment by ricov98** [comment]
Hi @Jenefer-Monroe, I have a Power Automate per user plan license, is that still not sufficient for the pagination?

**Comment by Jenefer-Monroe** [comment]
If you are seeing that error then your license type is not sufficient. 
You can see here our full [prerequisites]( https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with) list. 

Licensing is pretty complex so you'll need to loko through that list, but my guess is that you are missing **_Power Apps Per User license (non-trial)_**

**Comment by ricov98** [comment]
I have got green ticks on both licenses on the CoE Setup Wizard
![image](https://github.com/microsoft/coe-starter-kit/assets/134672486/c418d492-51d7-4d09-b6c1-e02b9a8bda87)

**Comment by ricov98** [comment]
Hi @Jenefer-Monroe , it works for me. 

And you are right, it turns out that the flow owner is still the person who installed the CoE before.

**Comment by Jenefer-Monroe** [comment]
Wonderful news, thank you for letting me know!

**Comment by cccFinn** [comment]
I am having this issue as well and have confirmed that my licensing is fine by creating the workflow you described in this solution which tested successfully.  I have also confirmed that I am a Global admin and have Power Platform service Admin rights.  I am also the one who installed the kit so the flows aren't running under a different account.

**Comment by AHMEDBOUCHAALA** [comment]
hello @cccFinn, i'm facing the same issue. Did you find a solution to this problem ? I'm using a newly licensed user. I will try to wait until tomorrow and test again;
