### ISSUE TITLE
[CoE Starter Kit - BUG] Wrong default environment ID in Dateverse Cloud and Apps tables

### ISSUE THREAD

**Issue by maikletal** [microsoft/coe-starter-kit#5884]
### Does this bug already exist in our backlog?

- [ ] I have checked and confirm this is a new bug.
Same error that https://github.com/microsoft/coe-starter-kit/issues/5595 in new version

### Describe the issue

Between Friday the 9th and Monday the 12th of June we have updated the CoE to the latest version and we have detected that since then the new power automate flows and new power apps that are detected in the Default environment are being saved with the identifier without the word "Default-" before it.

This issue is causing that new and deleted flows or apps not be detected correctly and the Power Bi dashboard is also not working well.
We don't know what causes this error because the default environment is still accessed with the word “Default-“ in front of it.

We need to resolve this error.

### Expected Behavior

We expect the correct ID with "Default-" word in Environment ID when save the data in dataverse tables.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

unknown

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. In CoE environment
2. Got to Flows dataverse table
3. Filter by dafault environment ID
4. Verify that the field "Flow Environment ID" have different values for the same deafult environemnt.

### Anything else?

![flow errors](https://github.com/microsoft/coe-starter-kit/assets/44426740/f4c11574-4101-4ecf-910c-8fc7ada5ecee)
![error apps](https://github.com/microsoft/coe-starter-kit/assets/44426740/679fa459-1e69-4981-ba7d-9a49848faa6f)

**Comment by maikletal** [comment]
Is it possible to delete the content of the "Power App Apps" and "Flows" tables in the CoE so that the information of the flows and applications of the default environment is regenerated?

**Comment by Jenefer-Monroe** [comment]
If you arent storing any metadata about these objects then you could do that yes. 

Or if you are storing metadata, then in 4.9, there is a flag on these objects requesting they be re-inventoried. This can be flagged manually in the Power Platform Admin View app 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e343ebfc-35bf-4828-8fce-392333400f2d)

Or you could write a quick flow to mark this field for all flows / apps in default as true (Yes). Then the next time your inventory runs they will be re-inventoried.

**Comment by Jenefer-Monroe** [comment]
That issue there of the text field showing id instead of name, I will look into

**Comment by maikletal** [comment]
I attach the data of the version that I have installed
![installed versions](https://github.com/microsoft/coe-starter-kit/assets/44426740/e7240362-2f9d-4df9-8e9b-266631e78e4d)

What is the correct data? The one that has "Default-" or the one that doesn't.

**Comment by Jenefer-Monroe** [comment]
Yes it appears this column has actually stored the envt name not the envt id as string in the past. 
So I have updated the flows to do that again. 

Change is in these two spots


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1301a2a3-766b-4a35-8212-2736c15c5552)



![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/09c144d0-eb9d-473a-b49c-cec19683b4e4)

**Comment by maikletal** [comment]
Hi Jenefer.
Ok. So, to fix the problem I have to edit those two flows so that the data is saved correctly. That will create an unmanaged layer that I will have to remove in the next COE update, where I assume the bug will be fixed.
To correct the data in dataverse, I can create a flow that gets the wrong data and update the envId field or correct the two flows first and use the re-inventory option, right?

**Comment by Jenefer-Monroe** [comment]
envtname is correct. 
envtid and envtname are the same value except for things like default evnt which prepend a string. Thats how we got this bug when we replatted to v4. 
Thank you for posting!
