### ISSUE TITLE
[ALM Accelerator - QUESTION] Issue accessing external project

### ISSUE THREAD

**Issue by sgshameem** [microsoft/coe-starter-kit#5886]
### What is your question?

I have recently done the ALM Accelerator setup using the ALM Accelerator for 
Power Platform (AA4PP) Hands-on Lab Step-by-Step.pdf and creating Trail versions. 

Now I am doing the same setup using our company environments. As per the steps in the document I created a AA4PP Project Pipelines project which has the coe provided template repository. I did using the Azure Devops-->New--> Projects.

However when I am creating project for our solutions using Azure Devops-->New--> ProjectsWizard and i get below error accessing the AA4PP Pipelines project. 

I have checked the options in Azure Devops which all seem Okay for accessing project within same organization. 

Can you help what exactly do I need to check for resolving this issue ? 

![MicrosoftTeams-image (2)](https://github.com/microsoft/coe-starter-kit/assets/47221026/02472ae4-3b20-4761-b9dc-bdb93bd22a9b)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

 1.0.20230606.1

AB#722

**Comment by mikefactorial** [comment]
@sgshameem The error is related to the settings in the organization for allowing projects to access templates that live in another project. Since you are selecting a different project to install the templates into there are settings that you need to update to allow this. Specifically, there's a setting under the organization settings -> pipelines -> settings called Limit job Authorization scope to current project for non-release pipelines. This has to be turned off at the organization level in order to make this work.

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/a45bd2c0-c01b-40ca-b78a-c16c5439b2de)

**Comment by sgshameem** [comment]
Thanks Mike. I will check with our DEVOPS admin.  regards.

**Comment by sgshameem** [comment]
Hi Mike, 
Good morning. I hope you are keeping well. 

Devops administrator has disabled the above suggested option as you suggested but I still have the same issue. I am logged in as  Power platform admin in all. 

This is the setting in devops in our organisation

![image](https://github.com/microsoft/coe-starter-kit/assets/47221026/7649b4cb-17ad-42c4-a61c-ff5b811c6bd2)

Just wondering is there a way we can do 2 min call on Teams or Zoom?

**Comment by sgshameem** [comment]
The steps followed in ALM Setup (Nov 22 v0.94) guide using Trail instances worked all good. The only difference this time is I have taken new CenterofExcellenceALMAccelerator-July2023 release.  
![image](https://github.com/microsoft/coe-starter-kit/assets/47221026/af1d7702-070c-4a61-a646-80595f703d2d)

**Comment by sgshameem** [comment]
Just compared the Azure deveops pipeline settings in Trail setup vs settings in our Devops
![image](https://github.com/microsoft/coe-starter-kit/assets/47221026/bed91316-acba-4967-beba-903aa421d3d7)

**Comment by sgshameem** [comment]
Hi Mike, 

Good morning. Do you have any inputs for me please?

Thanks.

**Comment by anttipajunen** [comment]
I had the same issue and the setting fixed it for me. @mikefactorial this was a bit hard to find actually. Think this could be added to docs / made more visible somehow?

**Comment by RajeevPentyala** [comment]
@sgshameem @anttipajunen We are updating documentation in a separate issue #5974. Closing this item for now.
