### ISSUE TITLE
[CoE Starter Kit - BUG] Copy of CoE Production Env to Sandbox creates duplicate Apps 

### ISSUE THREAD

**Issue by anujay111** [microsoft/coe-starter-kit#5890]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi All
I couldn't find anyone reporting this issue hence treating it as a new issue.
In order to ensure the upgrade goes well, we created close of the CoE Production environment on a sandbox (called it Dev). 
When i started to import the core solution, i got below error:
CanvasApp import: FAILURE: There should not be more than one record matching the name, found 2 records for CanvasApp with nameadmin_dlpeditorv2_fcf06
When i checked, i noticed there are two apps with same name with additional datestamp added to the name. I then noticed this happened to all Apps. 
 DLP Editor V2_202306090337
 Admin - Environment Request_202306090336

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

DLP Editor Canvas App

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Create new sandbox
2. Copy the CoE production environment to new sandbox
3. Import CoE core components

**Comment by Jenefer-Monroe** [comment]
Yes someone else just hit this recently. It turns out you can't duplicate the environment. This is a product limitation but we can add it to documentation. You will need to delete this duplicated environment you made for testing, and create it from scratch.

**Comment by manuelap-msft** [comment]
Closing out as this is a product limitation.
