### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by mukeshranjan-gsk** [microsoft/coe-starter-kit#5892]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Manual, @manuelap-msft 

Hope you are doing well. 

I am Mukesh Ranjan from GSK and i am Power Platform Tech owner and recently we have faced below error. 

"No Organization is matching the given dataset". 

Then i reached to Microsoft support but i didn't get any help to resolve this issue. Then I reached to one of Designated CSA (Deepa Shinde) from Microsoft. She told to connect with you hence dropping the message here.

**Problem details :**

In one of CoE power automate program i.e. called **CLEANUP HELPER - Check Deleted (Solutions)** which stopped working and throwing error in one of the List action of Microsoft Dataverse connector. The details are attached.

Please help us to resolve this problem ASAP

Thanks & Regards
Mukesh Ranjan
GSK, Principal Engineer, Productivity and Collaboration
[CLEANUP HELPER - Check Deleted (Solutions).docx](https://github.com/microsoft/coe-starter-kit/files/11795485/CLEANUP.HELPER.-.Check.Deleted.Solutions.docx)

### Expected Behavior

It should fetch the list of system admin in that action where flow is failing and flow should successfully do the clean task

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.41

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Rerun the Cleanup flow of CoE core.

### Anything else?

The details are attached

**Comment by Jenefer-Monroe** [comment]
The issue you show in your screenshot would not be the terminating failure as it is a caught failure. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/058d62c6-009f-4618-ad32-8694f9b9c136)

So if this flow is failing, you will need to go further down in the flow to find the terminating failure in order for us to assist in debugging.

**Comment by mukeshranjan-gsk** [comment]
Hi Jenefer,

We have done the changes and re-run in test environment attached is the details.

Please suggest you need any further information that helps you in debugging.


Thanks & Regards


***@***.***


Mukesh Ranjan
Principal Productivity
End User Services, Core Tech

GSK Asia Private Ltd, Bangalore, India
Email   ***@***.******@***.***>
Mobile +91 8861183183
Working Hours : 1:30 PM –9:30 PM (IST)

***@***.***<https://www.gsk.com/>

***@***.***<https://www.facebook.com/GSK>
***@***.***<https://twitter.com/GSK>
***@***.***<https://www.linkedin.com/company/glaxosmithkline>

**Comment by Jenefer-Monroe** [comment]
Hello please note that when you respond in email things like attachments and images do not come through, you need to log in to GitHub to share.

**Comment by mukeshranjan-gsk** [comment]
please find the attached document with the details which you want for debugging
[Cleanup Helper check deleted solution flow_test.jpg.docx](https://github.com/microsoft/coe-starter-kit/files/11801301/Cleanup.Helper.check.deleted.solution.flow_test.jpg.docx)

**Comment by Jenefer-Monroe** [comment]
That document is a little confusing. I'm still not sure from looking at it where your flow is actually failing. 
I see **_List Users for SYSTEM user fails_**, but it is caught and the HasAccess is set to false 
That should make it go down the no path of both **_Count SYSTEM users_** and **_If have access then continue_** which would mean both no-op. 
You do seem to be in a copy of the flow though with some changes to it, so I'm just not sure of your state.


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/67c7a118-eaae-4ff1-b146-269fb03c7301)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
