### ISSUE TITLE
[CoE Starter Kit - BUG] COE Setup and Upgrade Wizard

### ISSUE THREAD

**Issue by ashes2076** [microsoft/coe-starter-kit#5894]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I recently wanted to exclude some environments from inactivity notification process, and everytime i turn on for an environment, the setting doesn't get saved/implemented. I am not sure as why this is happening.

On the other hand, I turned off a flow manually from the solution, and that gets updated in the wizard. And not the other way round

### Expected Behavior

I expect the toggle in the wizard to work as expected.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

COE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, this one was fixed, along with a general setup wizard pass, for June 
https://github.com/microsoft/coe-starter-kit/issues/5509

I'll go ahead and close as a dupe but please feel free to reach out again in the future as needed.
