### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYODL-Unable to set schedule for Dataflow

### ISSUE THREAD

**Issue by jayakumarkgds** [microsoft/coe-starter-kit#5895]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am unable to set the schedule for dataflow. Find the attached screenshot. Manual refresh is success.

![image](https://github.com/microsoft/coe-starter-kit/assets/87489417/4cd4c254-64a6-4417-aa4a-464d5b55a039)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

PowerPlatformAdminAnalytics-DF

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
You need to select the time yet, hope that helps. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3fdcb016-d31f-47c6-83a2-4cf2ba01cc80)

**Comment by jayakumarkgds** [comment]
Great. Thank you for that. This is fixed. Generally, default(12:00AM) it will take so i didn't notice than. Good one.

**Comment by Jenefer-Monroe** [comment]
This caught me too in the past! Glad its fixed up. Ill go ahead and close then.  Feel free to reach out again as needed.
