### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flows) - failed to update flow table

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#5897]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v3 (Flows) -Flow ruining successfully however 'flow' table not updating so to investigate that I have opened this flow and found that actually flow are failing internally on specific action (see if flows exist) 

Error message :"message": "The access token has been obtained from wrong audience or resource 'https://graph.microsoft.com/'. It should exactly match (including forward slash) with one of the allowed audiences 'https://service.flow.microsoft.com/','https://management.core.windows.net/','https://management.azure.com/','https://service.powerapps.com/','https://service.kratosapps.com/','637fcc9f-4a9b-4aaa-8713-a2a3cfda1505'."

Screen shot attached : 
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/e2e84562-67e7-4859-bda5-3b36cbe3a22d)

to go further, I have validate connector and found that there is no issue 

Screen shot attached : 
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/1d9c6b90-07e2-43c6-bc9a-e584b04b6350)

Now , I can update the connection and check but I don't want to create "Un Managed layer"

Query: if on the top flow status showing running successfully then how we know which flow is failing internally and we need to take action .

Query 2: Why this flow is failing if everything seems good , I mean connection reference available 

### Expected Behavior

Flow should update the flow table periodically and if its failing, alert message should be trigger to notify the flow owner

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Sync Template v3 (Flows)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry I'm not following here. It sounds like your connection is broken. What is the change you are suggesting to make?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
