### ISSUE TITLE
[CoE Starter Kit - QUESTION] How do we install the HotFix

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#5898]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,  I have looked and googled for this answer,

But how do we install a Hot Fix,,   In the Assets the hotfix is a standalone file, doesnt look like one of the existing solutions,  so wont update an existing solution,   there isnt anything in the upgrade docs about hotfixes that IU can see.

So how do we apply a hotfix, Im looking to do May 23 upgrade from Feb 23, and  stopped as I dont know how or what the knockon effect will be, 

Can we have some instructions for this in the how to upgrade docs,  if this is patching a specific solution how will that look ? and behave afterwards ?

Thanks
Simon.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

May 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Is this a question for the ALM folks? Or is this just about our starter Kit releases. 
From your POV a hotfix and a release should not be different, the difference is only internal (where we ship from etc)
Can you point me to where you are seeing the single file? Here is what you should see
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e495faf3-a909-4375-abf8-875ddba41d77)

**Comment by binaryjam** [comment]
Hi , please close this, Im an idiot. thanks

**Comment by Jenefer-Monroe** [comment]
I'm not sure how that ended up happening. But here is the correct version of core. You can just install it directly. 
[CenterofExcellenceCoreComponents_4.8_managed.zip](https://github.com/microsoft/coe-starter-kit/files/11803131/CenterofExcellenceCoreComponents_4.8_managed.zip)

PS... not an idiot :)
