### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#5899]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

we are getting below error message when we are using the CoE Upgrade Wizard app 

![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/ad7add2e-452c-4c1a-b0d9-05d4c119fd59)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

CoE Upgrade Wizard app 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. This is a product regression tracked by https://github.com/microsoft/coe-starter-kit/issues/5815 impacting load of the controls we employ. The product team is in the process of hotfixing. I'll go ahead and dupe to that bug.
