### ISSUE TITLE
ALM Power Platform Checker execution getting failed because of this issue ErrorId: PACHECKER_PS_FILE_NOT_FOUND; ErrorCategory: InvalidArgument; TargetObject: System.String[]; Exception: System.InvalidOperationException: ERROR: code=PACHECKER_PS_FILE_NOT_FOUND, param=FileUnderAnalysis, message:The file(s) under analysis must exist

### ISSUE THREAD

**Issue by prakashnandshukla** [microsoft/coe-starter-kit#5900]
### Describe the issue

Hi All,

I am working on ALM Power Platform Solution Checker, I have setup all the requested to execute it perfectly. While commit of solution it is throwing error as given below.

"Entering InvokePowerAppsChecker - EndProcessing
Executing InvokePowerAppsChecker
Exiting with Failed InvokePowerAppsChecker - EndProcessing : 00:00:00.0062833
Microsoft PowerPlatform CLI
Version: 1.23.4+g9141d02" 

Error: ERROR: ErrorId: PACHECKER_PS_FILE_NOT_FOUND; ErrorCategory: InvalidArgument; TargetObject: System.String[]; Exception: System.InvalidOperationException: ERROR: code=PACHECKER_PS_FILE_NOT_FOUND, param=FileUnderAnalysis, message:The file(s) under analysis must exist.

Thanks
Anand

### Expected Behavior

After setting up all the steps it should execute and provide the sarif file as an output.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20230516.1

### Steps To Reproduce

I have followed steps mentioned in blog given below.
https://benediktbergmann.eu/2020/02/23/alm-using-solution-checker-in-a-pipeline/

### Anything else?

Nop

**Comment by mikefactorial** [comment]
@prakashnandshukla I'm not sure I follow what you are trying to do here. If you have already installed the ALM Accelerator there is a step in the pipelines that runs Solution Checker already for the PR Validation Build as seen below. Can you provide more context for what the scenario you are trying to accomplish is? https://github.com/microsoft/coe-alm-accelerator-templates/blob/74ee39bc9ab75e1b0d2d6187383c69db51dcf6f4/Pipelines/Templates/build-Solution.yml#L253

**Comment by mikefactorial** [comment]
Closing this out as there doesn't seem to be anything for the ALM Accelerator team to do.
