### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI reports error admin_haspcfenabled does not exist

### ISSUE THREAD

**Issue by tomka75** [microsoft/coe-starter-kit#5901]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Upgrading from CoE April 2023 to June 2023 and using the newest Power BI reports, we did the steps explained in the setup guide https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-the-production-and-governance-power-bi-dashboard
So, open pbit, enter URL, saved locally and published. This gives the error in the dataset refresh, that the column admin_haspcfenabled in table environments is missing.
We opened the Power BI report again and did a refresh. This removed this column from the models table, we published again and now the refresh worked.
Maybe you can add an extra step in the description, that before publishing is done, a refresh should be done.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Production_CoEDashboard_June2023.pbit and PowerPlatformGovernance_CoEDashboard_June2023.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I'm glad you got it resolved, I dont repro this myself. That column is not present in the PBIT file (like in the transform or anything). 
I'll hold this to see if others are affected. 
Thanks for posting!

**Comment by erikthomte** [comment]
A customer of mine has reported the same bug after upgrading from CoE April 2023 to June 2023. 
I have instructed them to do the same procedure as tomka75.

FYI: The April release was their first/initial setup of the CoE Starter Kit.

**Comment by G1982C** [comment]
I started to get that error on the 19th June (see below)
<img width="524" alt="CoE260623" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/d72bba05-241d-4be4-86d0-1d2b8cdd24a9">

I think I was on the June version, but downloaded the lastest Power BI PBIT and I no longer get the error

**Comment by Jenefer-Monroe** [comment]
Yes that makes sese. We used to refer to this field in old versions of the PBIT because it used to exist. But it was removed.
