### ISSUE TITLE
[CoE Starter Kit - QUESTION] Which flow adds the information that a flow or app is deleted (BYODL)

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#5906]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I've currently the problem that some apps and flows which are deleted, are not marked as deleted in the CoESK.
The app Dataflow does not retrive this information, and the check deleted cloud flow switch to an early exit, if BYODL is active.

Which flow does (should) retrive the information about deleted resources?

Best regards

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
We determine if its deleted by it not being present in the dataflow. And it can take several days for a deleted object to be removed from the data export. 
Can you please go see if the object you are asking about is present in the datalake file?

**Comment by lukas-nC** [comment]
Thanks for the tip
It's still there.
How long does it, from your experience take, that deleted objects are no longer in the JSON?
I'm asking because one app has been mark as deleted in under a week, another is still there after 10 days.

The check if its still there or will get marked as deleted, takes place in the CoE BYODL - When App dataflow refresh is complete - flows

**Comment by Jenefer-Monroe** [comment]
I would have expected it to be removed. Please create a support ticket for this, and we will also press internally.

**Comment by manuelap-msft** [comment]
Hello @lukas-nC, once you create a Microsoft Support ticket, can you please follow up here and let us know the Support Ticket number. That will help us get this assigned to our Engineering team internally! Thank you!

**Comment by manuelap-msft** [comment]
Hi @lukas-nC, if you are okay with sharing this here could you let me know your tenant ID / environment ID / app ID where you're seeing this issue so we can fast track resolution. If you would prefer, you can also email me those details at mapichle@microsoft.com

**Comment by manuelap-msft** [comment]
Closing out as fixed by product group. No further action required by CoE team.
