### ISSUE TITLE
[ALM Accelerator - BUG]: export_solution_to_git failing at Update Deployment Settings step

### ISSUE THREAD

**Issue by hymans-ryanmaclean** [microsoft/coe-starter-kit#5909]
### Describe the issue

export_solution_to_git failing at Update Deployment Settings step with the following error message:

`Deleting D:\a\1\s\Business Support\BusinessSupport\config\Validation\*eploymentSettings.json
Creating deployment settings
Creating custom deployment settings
https://dev.azure.com/hymans/Power Platform/_apis/build/definitions/1953?api-version=6.0
Invoke-RestMethod : {"$id":"1","innerException":null,"message":"TF20507: The string argument contains a character that 
is not valid:'u200B'. Correct the argument, and then try the operation again.\r\nParameter name: 
definition.Variables.Variable.Key","typeName":"System.ArgumentException, 
mscorlib","typeKey":"ArgumentException","errorCode":0,"eventId":0}
At D:\a\1\PipelineUtils\PowerShell\update-deployment-settings.ps1:505 char:9
+         Invoke-RestMethod $buildDefinitionResourceUrl -Method 'PUT' - ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
##[error]PowerShell exited with code '1'.
Finishing: Update Deployment Settings
`

### Expected Behavior

Typically I'd expect to see a new branch created

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230606.1

### Steps To Reproduce

1. Open ALM Accelerator App
2. Click Commit Solution
3. Add notes about solution
4. set Scope to Solution and Settings
5. Create New Branch togged to Yes
6. Based on Solution Branch
7. Commit Solution

### Anything else?

[Update Deployment Settings Output.txt](https://github.com/microsoft/coe-starter-kit/files/11818722/Update.Deployment.Settings.Output.txt)

**Comment by mikefactorial** [comment]
@hymans-ryanmaclean the error is pretty straightforward in that there's a unicode character somewhere in the request to set the build definition variables on one of the deployment pipelines (specifically u200B which is a zero width space character...these are always fun to try to find :)) 

It's possible that you copy and pasted a value into the deployment settings from somewhere that contains that character which would be invalid as the error mentions. One thing to try may be to copy out any text values from the deployment settings (e.g. Environment variables or email addresses to notepad and then repaste them or if there's not many of them re-enter them by hand. Finally, I would need to see the logs to troubleshoot the issue any further if you want to send them outside of this thread you can send them to v-ochsmike at microsoft dot com.

**Comment by hymans-ryanmaclean** [comment]
Hey @mikefactorial, I had identified the ZWSP character, and I can see it in the repo in the name of a specific flow. I've updated the Flow name but I'm still getting the error.  It's specifically in this section:



![Image](https://github.com/microsoft/coe-starter-kit/assets/104084324/5c0e95f4-ce3e-4076-851e-68b11a4153f1)

I've also tried removing the Flow from the solution and committing but it doesn't work.

Can you advise how I can get this Flow definition updated?

**Comment by mikefactorial** [comment]
@hymans-ryanmaclean did you update the deployment settings after renaming the flow? The old values may still be there if you don't revisit the deployment settings and save the values for each environment.

**Comment by RajeevPentyala** [comment]
> The string argument contains a character that
> is not valid:'u200B'

@hymans-ryanmaclean Can you check the 'customDeploymentSettings.json' files under _Repo -> Solution -> config -> Prod/Test/Validation_ path and make sure no ZWSP characters present?
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/9023e749-d89a-4e32-b376-0d3627afd8a7)

**Comment by RajeevPentyala** [comment]
@hymans-ryanmaclean Closing this issue as there have been no updates in the last 2 weeks. Feel free to reopen or log a new issue for any further queries.
