### ISSUE TITLE
[CoE Starter Kit - BUG] Installation account and service account need to be different for IT Security approval

### ISSUE THREAD

**Issue by RBpspc123** [microsoft/coe-starter-kit#5910]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Working for a large enterprise, IT Security needs to approve the use of generic service account with powerful admin privileges.  Using only one account (for install, updates and running as the service) with an Admin role, non-PIM and email enabled makes using the COE Starter Kit a very high risk for our enterprise IT Security team.  We cannot use this kit without some changes to how the tool is installed, updated and ran as a daily service.

### Expected Behavior

We are requesting the following changes to the COE Starter Kit to make it more inline with modern IT Security guard rail requirements:

- Separate accounts for each function: install  / update account, running  the service account
- Service account with admin role should not be email enabled (use Azure, Sentinel or Defender to send email instead?)
- Make the install / update account admin role PIM-able as the role is only required during an install / update operation 
- The separate Service account (or Service Principal?) can't be PIM and we realize that

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

latest release

### What app or flow are you having the issue with?

Installation and configuration

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Not applicable

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately these are limitations of the product itself, and not of our toolkit. 
For example: 
Flows that run at an unpredictable time cannot be PIM enabled as you will just never know if you have the correct permissions/roles/licenses at the time
Install generates the connection references that are used to run, so you will run as those (unless you manually change them all, which you can do today. 

We are built on the product and hence confined by its limitations. This would be good feedback to the product team that you can provide your MSFT representative.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
