### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is it possible to remove the Approve and Reject buttons (and the stuff below it) in the Inactive Notification email?

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5911]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have been trying to edit the "Admin | Inactivity notifications v2 (Start Approval for Apps)" flow to remove the sections shown in the screenshot below. 

![image](https://github.com/microsoft/coe-starter-kit/assets/128085471/21572a1b-550a-4e70-966e-fd6566e9e5bb)

This is where I am trying to make the edits, but I have been unsuccessful.

![github-where-I-am-editing-the-flow](https://github.com/microsoft/coe-starter-kit/assets/128085471/acb62aac-5a5d-41d0-a5fb-00dc2bf1340a)

Can any of these sections be removed?
And if yes, how do I remove them?

Note: I am using the June 2023 release.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Those are components of the mail generated by the product itself, they arent things we add. We are using the approval feature and just adding custom text into it. 
So I dont think there is a way to remove them, no.

**Comment by firefox-edge123** [comment]
Thank you for the information.
