### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYODL - Dataflow createdPrincipalId null

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#5913]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi @Jenefer-Monroe ,
I set-up the Power BI report connecting to the Dataflow. 
I realized that my apps and makers number was way below the accurate one. I first thought the issue was with the connection, but it wasn't. It isn't neither the dataflow configuration in PBI, nor the dataflows in Power Apps. 
I then went to my data storage > containers > powerplatform > powerapps > Applications and I see "null" in the createdPrincipalId in several of the json files. 
Since the power bi query merges the Maker table to the createdPrincipalId column (and it is mainly blank), I don't see all of my apps, makers, flows, etcetera. 

What can I do? 
Is the data export not working? Can I edit that somehow? I started data export 2 weeks ago.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

Power BI report

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
ok. Majority but not all. Can you spot check a few to see if the product itself has these? I'm just wanting to make sure that its not an old environment thats kind of "abandoned" by people that long ago left the company or something.

**Comment by LizethRegules** [comment]
They are not. It is a new tenant. Like 1 year old. 
The createdPrincipleId of the environments are all populated, the ones of the flows as well. The ones that are mainly null are the ones of the applications

**Comment by Jenefer-Monroe** [comment]
ok. I'm afraid I can't help fix this as its the product itself doing the export. Please contact Product Support and see what they say.

**Comment by LizethRegules** [comment]
got it, thanks

**Comment by manuelap-msft** [comment]
Hello @LizethRegules , once you create a Microsoft Support ticket, can you please follow up here and let us know the Support Ticket number. That will help us get this assigned to our Engineering team internally and will hopefully speed up resolution! Thank you!

**Comment by LizethRegules** [comment]
Of course!

I first opened a support ticket in the admin center Case 2306270040011381. They weren't able to help,and asked me to open a support ticket from Azure portal, and I did: case #2306270040011381. (Same case number, different contact). First contact was Raj Kumar Dubey, current one is Lucas Talento. 

Up until now, I haven't seen any new changes. My last interaction was Tuesday.

**Comment by LizethRegules** [comment]
I closed the previous ticket, since 2 months have gone, and no solution was provided. 
I keep seeing null values for my createdprincipalid.
Can I raise a new ticket and you could re direct it internally with your data export team? I saw other issues where you did that #5353 and #5796
