### ISSUE TITLE
CoE Audit Logs Custom Connector - Unauthorized 

### ISSUE THREAD

**Issue by antares-solutions** [microsoft/coe-starter-kit#5917]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The custom connector that comes with the CoE Audit Logs (v3.4) solution always fails with "_Authorization has been denied for this request_".

This needs to work before any flow or app can make use of it...

I downloaded the CoE Starter kit from here - https://aka.ms/CoEStarterKitDownload

I followed all documentation I could find on this
- https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
- https://www.youtube.com/watch?v=Z9Vp2IxFzpU

<html>
<body>
<div data-ogsc="" style="border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 14.6667px; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div data-ogsc="" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"><br class="Apple-interchange-newline">

Tenant ID | 5bde05c7-ee0d-4bc6-926d-89d2ba3354fb
-- | --
Audit Logs - Client Secret | Khv*************************************
Audit Logs - ClientID | 44342a23-ca99-430f-b226-339dcbbfd80f

</div></div><div data-ogsc="" style="border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 14.6667px; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p data-ogsc="" style="margin: 0px; font-size: 11pt; font-family: Calibri, sans-serif;"><span data-ogsc="black" class="x_ContentPasted0" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: black !important;"> </span></p></div>
</body>
</html>

I have created an App Registration, granted it access and created a Secret.

![image](https://github.com/microsoft/coe-starter-kit/assets/10804466/f25e39fc-e0f4-4115-8d21-6c3e374dea01)
![image](https://github.com/microsoft/coe-starter-kit/assets/10804466/aadb38ce-e661-4d6f-9bf2-1fe106dfb35a)

I then go to configure and test the connection but it fails in the test

![image](https://github.com/microsoft/coe-starter-kit/assets/10804466/c4d2fbe2-d139-41c7-88a0-d22946ba1bcf)
![image](https://github.com/microsoft/coe-starter-kit/assets/10804466/f3c29ee4-8e76-482c-a522-4a622d9a3da5)
![image](https://github.com/microsoft/coe-starter-kit/assets/10804466/be728529-52b1-41bf-bf1b-6283c8fc1202)
![image](https://github.com/microsoft/coe-starter-kit/assets/10804466/6bb727b6-4a44-4d59-a1cf-e0a61ae4523f)
![image](https://github.com/microsoft/coe-starter-kit/assets/10804466/85200be3-f06e-4178-8ba5-4a4d2793736c)

### Expected Behavior

HTTP 200 response code - as documented.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Custom Connector

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Create a new environment
2. Install Creator Kit
3. Install the CoE Core Components
4. Run the set up wizard
5. Add a single row to the COE Settings table
6. Fill out remaining empty Environment variables
7. Install the CoE Audit Logs
8. Edit the Custom Connector to configure and test it

**Comment by Jenefer-Monroe** [comment]
Does the identity running the flow have [access to the audit logs](https://compliance.microsoft.com/auditlogsearch)? 
From our [setup instructions](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content), here are the most common reasons people are not able to connect:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb651ea7-ac24-419d-bc77-f58a50aeae18)

**Comment by Jenefer-Monroe** [comment]
Note that we do also offer a new technique that is not subject to some of the custom connector limitations. And the custom connector technique will be deprecated in August 2023. 

See https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http for how to setup the new technique.

The new technique does have a different API requirement in the app registration though, so please review that carefully and be sure to change from delegated to application permissions if you re-use the old app registration.

**Comment by antares-solutions** [comment]
Hi Jenefer, thank you for responding to this.

To be clear we have not been able to get the custom connector to work by itself, let alone the flow.

I have also tried the Azure Key Vault but that failed. Microsoft Support said that it is still in beta and not to rely on it (basically not supported yet)

For the workflow, I have followed the instructions in the link you sent but the flow fails either with the Vault error or the custom connector error.
(https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http) 

"_BadRequest. Http request failed as there is an error getting AD OAuth token: 'AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '44342a23-ca99-430f-b226-339dcbbfd80f'. Trace ID: e792e6a9-d2f5-4db2-b554-4d31c4071e00 Correlation ID: eb01ff96-b64b-456a-b143-ee94ccec8c90 Timestamp: 2023-06-15 05:35:33Z'._"

![image](https://github.com/microsoft/coe-starter-kit/assets/57471453/a72d00e1-3f34-439a-ab9e-5352ecae924e)

![image](https://github.com/microsoft/coe-starter-kit/assets/57471453/d9574446-1de7-4b7c-ae7e-370945fdfbc2)

![image](https://github.com/microsoft/coe-starter-kit/assets/57471453/f6e93395-48bc-44c0-97a7-467094490bac)



The account I am using to install/setup the CoE is only a Power Platform Admin. My customer has been using a global admin account to configure the App Reg for me.


For the HTTP process you mentioned, will extra permissions on the App Reg prevent things from working? In other words, should I remove all other permissions from this App Reg - except for "Application ActivityFeed.Read"?

![image](https://github.com/microsoft/coe-starter-kit/assets/57471453/eb9ede86-d3b0-4ef9-a971-49fdde429590)



These are the environment variables for the customer's CoE environment:

![image](https://github.com/microsoft/coe-starter-kit/assets/57471453/56431e47-2e9c-4d67-acd0-03b80b466910)



I have also made sure that all DLP Policies allow the Microsoft specified connectors:

https://admin.powerplatform.microsoft.com/dlp/policy/b1c1e3da-9918-441c-9a8f-7f4d1b256742

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

![image](https://github.com/microsoft/coe-starter-kit/assets/57471453/3a7139f1-4e82-4162-af65-fc5ba493e9d5)

**Comment by Jenefer-Monroe** [comment]
Validate that the azure key vault permissions are correct. User needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)
