### ISSUE TITLE
Flow not working

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#5918]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/coe-starter-kit/issues/5825
```

**Comment by sunilmhatugade** [comment]
Flow Name:- Admin | Audit Logs | Sync Audit Logs (V2)

above mentioned flow continue failed . I hvae mentioned correct Environment Veriable

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/d3616b37-4555-4bc7-9c51-e87d79629d39)

**Comment by pete-msft** [comment]
@sunilmhatugade can you verify that Office 365 Management API subscription is started https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
