### ISSUE TITLE
[CoE Starter Kit - QUESTION] Add/edit Power Platform Admin View to add new columns

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#5919]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I wanted to ask some extra questions to App makers, so I used the Developer Compliance Center deprecated Canvas App. I would like to show their answers in the Admin View , Apps, 'Governance' tab - but its a Managed model driven app.
Any ideas ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

core components 4.4.1

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of where you are hoping to expose these answers?

**Comment by jimpreston29** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/78494876/6abbf2a3-45d1-4f5c-96a9-175c9a9f979e)
![Capture](https://github.com/microsoft/coe-starter-kit/assets/78494876/940b4f6a-a9d3-45b9-a9b5-312c1fd17993)
Hi, In this box here. Thanks

**Comment by Jenefer-Monroe** [comment]
ok great, then this is easy. Forms are mergable across coauthors so if you add the fields here, they will not be lost when you upgrade. 

To edit forms you go here: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e97e42b6-4866-48d8-9dd0-6ec07eb5297f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f477442a-7ae6-43f2-ac85-cab459b1860e)

Then select the tab you want to add columns and pull the fields in.

Hope that helps

**Comment by jimpreston29** [comment]
Thanks !

**Comment by Jenefer-Monroe** [comment]
You bet I'll go ahead and close out then.
