### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE- Flow not working

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#5920]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have imorted core componant solution and turned on all flow  but "Admin | Audit Logs | Sync Audit Logs (V2)" flow getting failed continuously. All environment veriable mentioned correctly.

It showing the Subscription is disabled..... Is it required any specific subscription for CoE..?

how to enable Subscription for CoE...

 "
![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/60790700-bead-4aa5-bfa9-03c1fafba545)
"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The new technique does have a different API requirement in the app registration though, so please review that carefully and be sure to change from delegated to application permissions if you re-use the old app registration.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
