### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can I check Custom Connectors from Power Platform Admin View ?

### ISSUE THREAD

**Issue by Ayako-U** [microsoft/coe-starter-kit#5921]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

As I want to check all Custom Connectors in the default environment, I checked the connectors in Power Platform Admin View.
I filterd by Tier as "Custom" and added column "Connector Environment Display Name".
I can find 28 Custom Connectors but if I search Custom Connector from Power Apps I can only see 1 Custom Connetor. (I have Power Platform Administrator role.)
My question is if I filter by Tier as "Custom" in Power Platform Admin View, these connectors are all Custom Connectors ?
If so, is there any way to find them in the Power Apps or Power Automate ? 
![snap1789](https://github.com/microsoft/coe-starter-kit/assets/100763907/1117e712-8a63-4244-9be1-28023ccccfd0)
![snap1790](https://github.com/microsoft/coe-starter-kit/assets/100763907/21020e78-9ffd-451e-a61e-99b97c711bf7)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately there isnt a way that I know of to grant access to custom connectors programmatically. 
This should be the list of the CCs in that envt aside from our known [limitaitons on what CCs we can gather](https://learn.microsoft.com/power-platform/guidance/coe/limitations#missing-custom-connectors)). 
I will leave open to see if others in the community know of a way to get access to these.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
