### ISSUE TITLE
[CoE Starter Kit - BUG] PCF code component load issue

### ISSUE THREAD

**Issue by Mmace123** [microsoft/coe-starter-kit#5922]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We've seen an "error loading control" appear across multiple Model Driven Apps (e.g. Developer Compliance Center, Nurture Apps, CoE Setup and Upgrade Wizard).

It looks like it is coming from a loading spinner that should show, but does not.

### Expected Behavior

Spinner should show

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

For Developer Compliance Center:

1. Open app
2. go to Flows
3. Error shows

For CoE Setup and upgrade wizard

1. Load app
2. As soon as it tries to load error appears, and then goes away
3. Go to Run inventory flows, error appears for a while.

### Anything else?

![error](https://github.com/microsoft/coe-starter-kit/assets/114146687/9e0294ac-31f1-4b77-aa6b-053d77e3e3c3)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
