### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 (Ai Models) fails

### ISSUE THREAD

**Issue by VasilinaMaroz** [microsoft/coe-starter-kit#5923]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The new version of Sync Template v3 (AI Models) fails on the Microsoft Dataverse (legacy) action "List AI Models" with error "Looks like your flow's operation is hitting an action limit designed to protect the connector service being called."
![image](https://github.com/microsoft/coe-starter-kit/assets/116820870/035d8b70-c1ac-4492-9073-4b8f0fa3da1d)

![image](https://github.com/microsoft/coe-starter-kit/assets/116820870/e076b5cb-089e-4eae-8c8a-417fa6b0febe)

### Expected Behavior

This action shouldn't have an error and should list number of records from a dataverse table.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Ai Models)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Run the flow Admin | Sync Template v3 (Ai Models).
2. Flow fails on action "List AI Models"

**Comment by VasilinaMaroz** [comment]
Yes, but it occurs for different environments every day.
We have the same issue for one more flow - Admin | Sync Template v3 (Solutions)

**Comment by Jenefer-Monroe** [comment]
ok I'm afraid there isnt anything we can do here. We will be deprecating this connector but cannot do so until the modern dataverse connector suports cross envt query.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
