### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot see latest desktop flows created in CoE

### ISSUE THREAD

**Issue by neelkantc** [microsoft/coe-starter-kit#5925]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Desktop flows created in this power platform environment are not loading in CoE dashboard

### Expected Behavior

Desktop flows should be shown.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin - Sync template V3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Access the power platform CoE
Check the desktop flows created in the environment.

### Anything else?

Its related this ticket as well https://github.com/microsoft/coe-starter-kit/issues/2753

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
