### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cloud streams do not update in the environment where it is created

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#5927]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, please we have a problem because the cloud flows do not appear in the environment where they are created. We already had a problem that the environments did not update in the inventory, so we followed the procedure of updating the entire inventory, but even doing that now, the cloud flows do not appear in the environments.
The maker created some cloud flows in a new environment and these flows don't appear in both Power BI and the Set Flow Permissions app.
We have already updated Core Components to version 4.9 and put Full Inventory to run, but it does not update the cloud flows in the environments.

Can you tell me if it's a flow that does this or if it's a flow error not updating it? 

![Versão Core](https://github.com/microsoft/coe-starter-kit/assets/129080740/fa272479-3f92-4cd4-9200-999a7a18c1f5) 
![PB1](https://github.com/microsoft/coe-starter-kit/assets/129080740/795e45e8-69ce-45b7-96ef-4adadb86f4a7)
![Aplicativo de acesso](https://github.com/microsoft/coe-starter-kit/assets/129080740/e6802013-5c83-4c60-b633-a473883b6a76)
![Admin Power platform](https://github.com/microsoft/coe-starter-kit/assets/129080740/1054e191-2a70-4f5e-945a-b965337d7684)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

junho 2023 4.9

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Browse to the Admin Command Center > Environment Variables > What is the value for this item? 
![image](https://user-images.githubusercontent.com/89584709/230621685-2f293271-b215-4f91-8234-0f39c8f638e9.png)

**Comment by minobrega** [comment]
Hello,

Follow the print as requested. Thankyou..
![Ambiente admin](https://github.com/microsoft/coe-starter-kit/assets/129080740/7ef29cf2-67d4-460c-a7cb-504017c76c36)

**Comment by Jenefer-Monroe** [comment]
That is the reset value. If you scroll the right you will see your current value.

**Comment by minobrega** [comment]
Follow the print..
![Ambiente admin2](https://github.com/microsoft/coe-starter-kit/assets/129080740/34130c10-c2e0-4967-9f51-72415982e9ef)

**Comment by Jenefer-Monroe** [comment]
Thank you, can you please clarify a few questions

1. The environment in question does show up inventory? Or not?
2. The flows do show up in inventory but assigned to the wrong envt? Or they dont show up at all?

**Comment by minobrega** [comment]
Apparently the inventory is not running, as I did the complete inventory and it does not update the flows as shown in the images below

The flows below are in the environment as shown in the print below
![Nesse ambiente](https://github.com/microsoft/coe-starter-kit/assets/129080740/8b40fc01-47a0-4ae9-95af-711a2a5ad165)

As you can see in the Table of Environments below, the environment appears but does not update the flows
![Screenshot_4](https://github.com/microsoft/coe-starter-kit/assets/129080740/2ac6d964-26d7-4cbe-8850-bd28378c0bf6)

**Comment by minobrega** [comment]
Would it be a flow that updates apps and flows from the environment?

Out of this cloud flow?
![Inventori](https://github.com/microsoft/coe-starter-kit/assets/129080740/d3ca148c-93b2-434c-969c-8e2f3d753b0f)

**Comment by Jenefer-Monroe** [comment]
That is a Dataverse rollup column and so only updates once I day I believe. So it should show the number of flows it knew were attributed to that envt yesterday.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9480c1e4-0071-441f-bdee-8f3c7e832870)

Please go to the Flows table itself, and filter by your target envt. You can do this in the Power Platform Admin View app. Do you see them there?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2fef7f66-4f4d-4014-8861-7612493e5746)

If not please get the id of that environment, you will need it for the next step of the investigation
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e9c625c2-af82-41d5-9692-d96db6337538)

**Comment by minobrega** [comment]
Flows do not appear in Admin View
![Admin View](https://github.com/microsoft/coe-starter-kit/assets/129080740/d24d60bf-b1a7-4472-86ba-0abd66693776)

I found
![Ambiente admin view](https://github.com/microsoft/coe-starter-kit/assets/129080740/b5edaaf3-40ee-4f47-823e-7a00037c9e96)

**Comment by Jenefer-Monroe** [comment]
Great, next step then is to go to the flow run for that envt and see what happens

Browse to the details page for **_Admin | Sync Template v4 (Flows)_**. 
Edit columns, add environment name and save, then hit All runs
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/841b37ba-0fe1-4132-b0a5-fe6d9d887442)

Control-F to look for your envt id, when you find it, click that timestamp
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c712b0b4-e396-4073-83eb-4ccbb8ab3903)

Once you open it, go to List Flows as Admin (V2) and see if your flows are in the output
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/91b8bd2e-d758-43db-a190-e5642b4962db)

**Comment by minobrega** [comment]
So that's why the problem, but when I try to activate this flow it says that another child flow was never published.

I'm trying to find this child fluxo

![Ambiente 3](https://github.com/microsoft/coe-starter-kit/assets/129080740/a958fc89-0aa4-4a6e-b0a8-ce496ac22578)

**Comment by minobrega** [comment]
I found the child stream, turned it on, and turned on this Admin | Sync Template V4 (Flows)

![Ambiente 5](https://github.com/microsoft/coe-starter-kit/assets/129080740/001421d4-8be2-465e-b054-f0a634f277fe)

**Comment by minobrega** [comment]
Now do I run the full inventory to force the app and cloud flows to refresh?

**Comment by Jenefer-Monroe** [comment]
You are quite welcome. I'm glad we got it resolved!
