### ISSUE TITLE
[CoE Starter Kit - QUESTION] Difference Fields

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#5929]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What is the difference between the fields admin_appplanclassification (Blank / Premium / Standard), admin_usespremiumapi (True/False) and admin_tier (Standard, Premium, custom)of conneciton reference?

I´m currently building an extension for the licensing reports and would like to use the correct field to identify Apps, that require a premium license, but I get different numbers for all 3 fields.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

Power BI

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We read these directly from the product. 

So for apps we have
**App Plan Classification:**: outputs('Get_App_as_Admin')?['body/properties/appPlanClassification']
**Uses Premium API**: outputs('Get_App_as_Admin')?['body/properties/usesPremiumApi']

And for connections:
**Tier**: items('Get_Connectors')?['properties/tier']

I know that the tier property of Connectors is correct. We use it all over the kit. I never use those ones from App. If they aren't reliable I'm afraid I would need to point you to product support. Or you can just rely on the connectors one.

**Comment by manuelap-msft** [comment]
Here's the documentation on the App Plan Classification field, that may help
https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/license-designation

An app could use premium features (for example, the mixed reality features) without using a premium connector. So you could have an app that is marked as premium app plan classification where all connectors are still standard. From what we observed, this field is correct. This field is also surfaced through make.powerapps.com if you select ... next to an app > Settings, you can see the License designation there:
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/a02267b6-7d26-4d7d-80db-4c84849fb8d7)

The UsesPremiumAPI we get from the Power Apps for Admin connectors and store directly, but we don't use it ourselves as far as I know so we've never evaluated if it's correct. 

Hope that helps!

**Comment by Jenefer-Monroe** [comment]
You are quite welcome!
