### ISSUE TITLE
[CoE Starter Kit - BUG] From Name is Not Changing when a user submits the new Environment creation Request

### ISSUE THREAD

**Issue by VamshiKommineni25** [microsoft/coe-starter-kit#5930]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have shared the **Maker - Environment Request**App to the user to create the new environment request. After user made the request I got the following error.
**FROM** name also showing Admin name and **TO** name also showing Admin Name

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Maker - Environment Request, HELPER - Send Email, Env Request | Notify admin when new request submitted

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I believe this is expected behavior. We do not send the mail in the context of the envt requestor. Their invormation should be in the mail though. Plesae let me know if I've misunderstood.

**Comment by VamshiKommineni25** [comment]
When a requestor made new envt request then admin will get mail from requestor right.
In that Admin mail, Requestor name is not coming as from instead Admin name only showing.
For your reference I'm sending you photo of that.
![image](https://github.com/microsoft/coe-starter-kit/assets/121937890/4d8bf725-8f03-468a-9e05-306ffd5142c4)

**Comment by VamshiKommineni25** [comment]
To is coming correctly only , but above Kommineni vamshi is there right, that is not getting correctly, I mean that request was made by another person but it is showing my name.

**Comment by Jenefer-Monroe** [comment]
Thank you for confirming, mails sent in flows are sent in the context of the identity that is running the flow, it uses that connection. 
We would not be able to send this mail int he context of the requestor as they are not running the flow. 
There is a concept of run on behalf that we support but it woudl not allow you to send the mail on behalf the requestor but on behalf of some other service user you make for people to communicate with admins. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/45e3009b-43e8-485b-879c-edf625f49231)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
