### ISSUE TITLE
[CoE Starter Kit - QUESTION] Uninstall CoE failed with Timeout

### ISSUE THREAD

**Issue by NathanZhengASW** [microsoft/coe-starter-kit#5931]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I was trying to remove CoE kit from environment, and it failed with timeout error. below is the screenshot for your reference. 

![image](https://github.com/microsoft/coe-starter-kit/assets/135016903/6e84c1a0-4a43-499a-ba96-0fd0ee3f4b91)

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

**Comment by DominicMeznik** [comment]
The operation should still finish in the background. You can check the history tab to verify.

**Comment by NathanZhengASW** [comment]
Nice, It is removed now.  

thank you for the prompt reply!
