### ISSUE TITLE
[CoE Starter Kit - BUG] after upgrading Audit Log component, fail to load data into Audit Log table

### ISSUE THREAD

**Issue by amolyadav90** [microsoft/coe-starter-kit#5933]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Audit log data not loaded into audit log table after upgrading audit log component to newer v3.4.
[Admin | Audit Logs | Sync Audit Logs (V2)] flow successfully running hourly interval.All actions and child flow running successfully,but not loading into Audit log table.Before it was working fine on older version.

![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/30cbecb6-bb8b-4308-b0f9-e65a7661afae)

### Expected Behavior

Audit log data should be load by flow.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

-Upgrade COE starter kit to new version
-Upgrade audit log component to v3.4
-Audit log component upgraded to new v3.4. As per MS document coe starter kit upgraded.(https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup#updating-the-audit-log-solution).
-Then followed HHTP audit log insttalltion process as per MS doc (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http)
-Subscription enabled using flow -Admin | Audit Logs | Office 365 Management API

### Anything else?

![CaptureAuditlogIssue](https://github.com/microsoft/coe-starter-kit/assets/137497313/0e805d6b-b1d9-4e6b-9b45-b6f4a69fc231)
![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/5a7ccb23-3004-4b37-92a5-594f197b0a25)

**Comment by Jenefer-Monroe** [comment]
1. Please check to see if the data is present in the Power Platform Admin View
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/14ea2af1-e0fc-4d1e-9be9-5443286013ad)

1. Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

1. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

1. Turn the flows off and back on. Sometimes env vars get stuck in them with old values

**Comment by amolyadav90** [comment]
@Jenefer-Monroe Thank you for the prompt response, point 2,3,4 I have checked ,its same as you have mentioned.
For Point 1, Can you please share URL to see Audit log into power platform, I am unable to see these options into https://admin.powerplatform.microsoft.com/ portal. I seen audit data visualize into compliance portal (https://compliance.microsoft.com/auditlogsearch?viewid=Async%20Search)
![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/8a304114-7a11-49ce-ace3-68bfa3f4334a)

**Comment by Jenefer-Monroe** [comment]
Please share screenshots of 2 and 3. And make sure you restart the flow (per number 4).

**Comment by amolyadav90** [comment]
Hi, 
Please find below screenshots.
2. AAd app permissions
![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/1725c13f-1a0c-4db3-9501-5d6065278cb3)
3.Command admin center -env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/c5b47b1c-9b40-4168-8a92-74c818e27d0e)

Flow success screenshot-
![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/c14f4113-fbaa-4da8-ba68-5b9a07066c2f)

**Comment by Jenefer-Monroe** [comment]
Click on the timestamp
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/acac2c59-22f8-4040-901c-fbe9164116ee)
Does the flow fail on this action? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c277e57b-803f-44d5-ac34-f6aa6c4b6f1b)

If so, what is the error?

**Comment by amolyadav90** [comment]
there has no any error into flows action, all steps succeeded.Please see screenshot.

![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/8bb4def0-4e5d-408f-8b06-f405a0594158)
![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/d2e024b6-0eb7-42ed-8a8a-0799955d7649)
![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/c7c899fe-03dc-4b6a-8962-31fffe3ebb41)

**Comment by Jenefer-Monroe** [comment]
oh ok. Looks like its working then, you just arent picking up any launches. 
Please launch a few apps yourself, and see what gets picked up in the next run

**Comment by amolyadav90** [comment]
Hi, Seems only 3 records added into Audit Log table even after launching 7-8 app. 
Seems there has error occured in one action. And how we will get older data ?
![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/8c7f9435-0ec6-4b24-ae0c-0607ffa629f3)

**Comment by Jenefer-Monroe** [comment]
A failure here means that the app is not in inventory. Typically because it was added since you last ran the inventory. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2a366075-584c-4303-999e-56eedc32602b)

**Comment by Jenefer-Monroe** [comment]
Please see [How to get older data](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#how-to-get-older-data)

**Comment by amolyadav90** [comment]
@Jenefer-Monroe   Thanks for the support. Finally we are getting audit log data.
I have one more query, When we upgrade audit log component , why older data clears? 
If its clear will it impact on flow which are running on that data?  goverannce flows (cleaning) basically depends on app usage right?  Can we download older Audit log table data from and use/export it into Audit log table without going to complaince portal?? Because we don't have access for complaince portal to download data.

**Comment by Jenefer-Monroe** [comment]
Old data should not get cleared out. I have not seen this happen.

Unfortunately the only way to get old data is to start from the UX so without permission there you will just have to start gathering data from today onward.

**Comment by amolyadav90** [comment]
@Jenefer-Monroe  Thanks for the support. Finally Coe upgraded successfully on prod after did these below changes.

- Removed Activityfeed.Read delegated permission from AAD app
- Disable depreciated flows
- Turn off/on audit log flows

**Comment by Jenefer-Monroe** [comment]
Wonderful, thank you for letting me know! I'll go ahead and close this now then, but feel free to reutrn with more questions in the future.
