### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Deployment in China Cloud Environment - App Catalog app cannot trigger "Request Access" button  

### ISSUE THREAD

**Issue by MeredithOneWorld** [microsoft/coe-starter-kit#5937]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

MS Teams connecter is blocked in China Cloud for Power Automate. When customizing "App Catalog > Request Access" flow which calls a child flow, the only way to customize flows with child flows is by editing the flow in the managed solution and creating an unmanaged layer. Thus, **I have only replaced the MS Teams component with Office 365 outlook for approval without changing anything else**. The flow has been manually tested by entering the text and was run successfully. 
     However, when adding a z[deprecated] App Catalog app (for testing purpose) into the App Catalog model driven app, I clicked on the button to request access. But error was thrown saying " The GetConnector has invalid value" (maybe due to the fact I changed "Outlook connector" to be RUN-only by user property)" and " the input body for trigger 'manual" of type request did not match its schema . "Contact maker" option can work as expected. Other than modifying flow itself, does the app also have to be modified? What will be the right approach? Many thanks. 

<img width="1135" alt="flow" src="https://github.com/microsoft/coe-starter-kit/assets/95392006/d3fac21d-1053-4d27-8c94-696a7b1d4e30">
<img width="1248" alt="App catalog" src="https://github.com/microsoft/coe-starter-kit/assets/95392006/d66ecac8-d0cb-4342-9154-c38477d2e5e9">
<img width="1169" alt="PVAflow" src="https://github.com/microsoft/coe-starter-kit/assets/95392006/eb2ddccd-5c72-4055-96bc-f9b03c12ae1b">

### Expected Behavior

Users can send out request to app creator for access permission. App creator can receive email for approval request. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

App Catalog and App Catalog > Request Access

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

<img width="1135" alt="flow" src="https://github.com/microsoft/coe-starter-kit/assets/95392006/610ab481-3b33-49a0-aca9-ab3d454619b1">
<img width="1248" alt="App catalog" src="https://github.com/microsoft/coe-starter-kit/assets/95392006/c6e28454-b2b5-42c1-9ff2-022d0e6387eb">
<img width="1169" alt="PVAflow" src="https://github.com/microsoft/coe-starter-kit/assets/95392006/dc2bcc75-19bf-46e5-9c22-f1e160d5bd7d">

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are a very small team and are not staffed to assist with customizations. 
It also looks like you are using the old and deprecated app catalog. We will be removing those soon so you should use the new app catalog.
That will explain the second error you see.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d46488ef-52a6-4ea8-9e1d-b11f841d70b9)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b7bf802c-cac2-4434-b94a-260cd1ae7b2d)


I also repro that other issue loading a model driven app in the old app. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e7b81cbf-1f39-4e11-8b53-5a166b85fa26)

Please try with the new App Catalog.

**Comment by MeredithOneWorld** [comment]
Understood that. But previous screenshot is taken when I open up the deprecated app Catalog and request access inside of new App Catalog app. Somehow the App Catalog and App Catalog > Request Access can be copied into a new solution. Does it mean I have to remove original one from CoE starter it? However, this parent flow calls a child flow which shouldn't allow copying according to documentation https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components


May you please help me understand how the App Catalog > Request Access flow supposed to work? Thank you

**Comment by Jenefer-Monroe** [comment]
The old apps are being removed from the July release. 

The new app sends in the following parameters to the flow. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/983ce33e-6260-4710-94f8-0b468ada3507)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
