### ISSUE TITLE
[Power Platform communication site template] ISSUE TITLE

### ISSUE THREAD

**Issue by Schwaigy** [microsoft/coe-starter-kit#5938]
### Describe your bug, question or feature ask.

Hi, I can't deploy the PowerPlateform Hub :(

This is my error code : 

![image](https://github.com/microsoft/coe-starter-kit/assets/137719365/838bbb16-a89d-451c-b7e8-31b79ee45395)

**Comment by Laskewitz** [comment]
Hi @Schwaigy - 

It looks like you're not in the right directory. `C:\Windows\System32` is not the place where you extracted the zip-file you downloaded? Make sure you run the script from the directory where you extracted the zip-file! This leads to the `File not found` error.

Hope that helps!

**Comment by Schwaigy** [comment]
Thx @Laskewitz :) yes that works but I have another problem now :(

Have you ever seen this ?

![image](https://github.com/microsoft/coe-starter-kit/assets/137719365/d3379826-db77-43fa-b4a1-098f914801f9)

**Comment by Schwaigy** [comment]
Hi @Laskewitz it works now ! 

![image](https://github.com/microsoft/coe-starter-kit/assets/137719365/7298276f-0091-42c1-935e-549c19ce1ee0)

But the Navigation of the SharePoint don't work... 

![image](https://github.com/microsoft/coe-starter-kit/assets/137719365/7cb780e2-38e5-40b3-8bba-57a64a110a09)

Is there a solution for this ? 

Thx in advance to you ;)

**Comment by Schwaigy** [comment]
Hi @Laskewitz I tried the solution from another issue and it works now ! ;)

![image](https://github.com/microsoft/coe-starter-kit/assets/137719365/6cca2aa3-cf13-4641-83a1-edb4c771e36c)

Thx a lot for this amazing template ! 😉👌

You can close my issue.

Kind regards,


Simon
