### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Starter Toolkit configuration 

### ISSUE THREAD

**Issue by shriyamal** [microsoft/coe-starter-kit#5939]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the CoE Admin Command center, a cloud flow connects to the MS Graph API via App registration to get the MS 365 messages center update.
The client secret of this App registration is recommended to store in an Azure Key Vault and then to be referred in an environment variable.

The question is about a very specific Firewalls setting of the key vault, which we don’t find a direct answer from MS document.

What should be selected for "Allow Access from" in the configuration under Firewall and virtual networks for it to work.
For example, do we have to switch to “Allow public access from all networks ”? Certainly we’d like to avoid this to be accessible from all networks. If we go for “Disable public access”, is there additional settings to take into consideration?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by shriyamal** [comment]
I am referring to this configuration for reference:

<img width="361" alt="firewall" src="https://github.com/microsoft/coe-starter-kit/assets/91137553/96f69058-8bf0-46c0-b43f-31280514bded">

**Comment by manuelap-msft** [comment]
Hello,

using Azure Key Vault in Environment Variables is just a product feature that the CoE kit uses, it's not something that's specific to the CoE kit so unfortunately we can't help with questions specific to this feature. The documentation of this feature is here https://learn.microsoft.com/en-us/power-apps/maker/data-platform/environmentvariables#use-azure-key-vault-secrets-preview and if this does not answer your question you will have to raise a ticket with Microsoft Support asking about this specific feature! 

Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
