### ISSUE TITLE
[CoE Starter Kit - BUG]: Dataverse Connectors can be moved to blocked with DLP Editor V2 Canvas App

### ISSUE THREAD

**Issue by marcster** [microsoft/coe-starter-kit#594]
**Describe the bug**
Using the Admin portal, the Microsoft Dataverse connectors cannot be blocked but within the DLP Editor V2 Canvas App they can be. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core 
 - 2.1.70
 - DLP Editor V2 Canvas

**To Reproduce**
1. Open the DLP Editor V2 Canvas app
2. Create a new tenant policy
3. On the non business tab, search for Dataverse
4. Right click and the option to Block is available

**Expected behavior**
The Microsoft Dataverse connectors are not blockable within the Power Platform Admin Center and so should this not be the same in the DLP Editor V2 Canvas App?

**Screenshots**
![image](https://user-images.githubusercontent.com/1025102/121333104-653ba700-c910-11eb-9e56-d2ca42b0dd52.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

thanks for letting us know - yes, this is bug. Unfortunately there's currently no API to pull a list of unblockable connectors so we had to hardcode them into the app. Looks like we may have missed Dataverse (or are still using the old Common Data Service name) there! I will update and add that for the next release.

Thank you,
Manuela

**Comment by manuelap-msft** [comment]
Fixed locally and will be part of the July release.

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
