### ISSUE TITLE
[CoE Starter Kit - QUESTION] Set up wizard, no flow progress

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#5940]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Trying to get CoE installed. My CSAM asked to post here again, so here we go. 

History: Had and issue with May update, broke our CoE. Due to how someone else configured it before me, and after Power Platform Admin training, and discussing with the instructor, I decided to start fresh to build to the standards provided. Built new environment, got it all ready, installed June version 4.9, can't make teams connector, issue in gcc space, got that fix, but then PCF errors. Couldn't continue. After waiting, told that should be fixed, but may need to republish. Decided my CoE has nothing in it, let's start fresh again. Installed everything, still "error loading form". Told I need to republish, okay, try to edit a MDA, and even more errors, but can still hit publish button that gives check mark. Still no luck in set up wizard. Able to click next step, and that loads, enter group into, select GCC, production yes, has tenant ID, and admin email, continue, select cloud flows, continue to flows running and nothing. Refresh changes nothing. Go to troubleshooting part of setup doc, confirm those 3 flows are running. Still not able to progress to get into a "running state".

![MicrosoftTeams-image](https://github.com/microsoft/coe-starter-kit/assets/125403575/38b75cc6-7dd7-45cc-a36e-b9d8fdbcf49d)

I'm running out of options before my management cans this whole thing. They have been largely disappointed, and I keep saying lets see if we can get it running. Support/assistance has been a nightmare. I don't know what else to do to try and get this running again. Yes, I will be sure to have a test/prod just for the CoE in the future. I just don't know how I can make processes for our enterprise around this "product" at this point. Please help?

Issues I've opened/commented on trying to get this all to work:
https://github.com/microsoft/coe-starter-kit/issues/5649
https://github.com/microsoft/coe-starter-kit/issues/5788
https://github.com/microsoft/coe-starter-kit/issues/5865
https://github.com/microsoft/powercat-creator-kit/issues/338

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Sorry for your bad experience. The CoE kit is an unsupported set of templates, made available in an open-source fashion on GitHub. See [Feedback and support for Center of Excellence (CoE) Starter Kit - Power Platform | Microsoft Learn](https://learn.microsoft.com/en-us/power-platform/guidance/coe/feedback-support), its not a product. 

Our team triages questions on GitHub as best as we can, but without an SLA. 
We are a very small team (there's only 2 of us), and so some people do need to reach out for more dedicated support from others. 
I do suggest you reach out to your Microsoft contact and ask about programs related to this. I believe we gave him some pointers in a separate chat.

**Comment by Jenefer-Monroe** [comment]
All that said, let's see if I can help you here.
1. For one thing, we can just skip the setup wizard entirely if you'd like and install manually. It''s not the preferred route but some people do still do it this way. [Set up inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components)

2. You are a non-Commercial tenant, GCC I believe, is that correct? Please go to the Admin | Command Center > Environment Variables, and validate that these environment variables are correct for you. 

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bbf4bf3f-b48e-4f8e-86d8-28d3705990df)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6b17f72b-b32d-4f79-8273-211074e8dd9e)

3. View the **_Admin | Sync Template v3 CoE Solution Metadata_** flow. Did it run and pass? 
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/214deedc-850c-456e-b11d-e4c149c588cc)

4. Please open and run **_Admin | Sync Template v3 (Call Updates)_**. It will in turn call several other flows (including the metadata one above). Wait about 15 minutes after doing this, and boot the Setup Wizard again to see if it lets you continue.

**Comment by pnoot7** [comment]
2. variables appear correct. However, the power app player is different is the documentation up to date on that one?
3. On and ran successfully.
4. Could not turn on, had this error:

"Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'e05cfb27-740d-eb11-a814-000d3a1bb7bb' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}"."

I edited it and found:
![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/aa300f9f-6408-476a-86d8-aea99994796d)

Going to that flow, it was off. I couldn't turn it on. I edited it, hit save, then was able to turn it on.

With that, I can now turn on and run the Call updates flow. That is in progress currently.

Any idea why the child flow wouldn't have been published properly?

**Comment by pnoot7** [comment]
Manually enabling flows, and "Command Center App > Get CoE Flows" is missing, but listed in the documentation. Thoughts?

![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/64ea4344-4e98-4769-842c-30953059176f)

**Comment by Jenefer-Monroe** [comment]
That flow was removed. You can just skip that.

**Comment by pnoot7** [comment]
Any thoughts on error above?

Also, has "CLEANUP - Admin | Sync Template v3 (Connection Status)" been removed too? It is listed in the documentation.

**Comment by pnoot7** [comment]
Still trying to get everything set up. Getting status 200 on audit logs. Have you confirmed that the search permissions are still needed? It wasnt confirmed last time I asked.

https://github.com/microsoft/coe-starter-kit/issues/5786

**Comment by pnoot7** [comment]
manually enabled all flows and ran per directions. I'm still not getting any info in the dashboard, and the set up wizard is stuck in the same place. So I'm afraid I haven't made any real progress. Suggestions?

**Comment by Jenefer-Monroe** [comment]
There is a delay in the initial processing of the kit that we added to avoid all the 10k kit installs asking for inventory at once from the product datacenters. So lets go see how its progressing.

Please go to the Admin Command Center > Coe Flows.
Note you may see this error on load, its that same product bug you were hitting before. But if you wait then it will load.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9f60e160-7127-4414-b0ba-5605cfe10349)

Browse to inventory flows, and check if everything is on. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f687ce0d-9647-4301-a4d8-81015c98a105)

Find this flow, and go to Flow details
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/97f197be-84de-4329-8cbc-adb1d6dc3f9b)

Once there you will likely see a run in progress, click the time stamp and you can see where in the flow it is sitting.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/caf86bcd-388c-40ab-8417-9b9dc78aee82)

You are likely sitting in the delay inventory spot, 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/71a2fe7a-95b8-440d-ba40-753924fc24a3)

**Comment by pnoot7** [comment]
Getting into the Driver flow, it is running, currently at 2:31:45 for duration. 

However, from the command center app, viewing that flow, and trying to go to details, it tried to direct me to the commercial site and gave me an error. I did confirm that the "admin_PowerAutomateEnvironmentVariable" is set to "https://gov.flow.microsoft.us/manage/environments/", and if I take a url for the flow, and replace the front with that, it does redirect to the gcc version. 

We don't have a large environment, but I guess I'll need to wait for this flow to finish. 

Any thoughts on the audit log set up?  My service account can't run a search, but the app has the right api, and I get a status 200. I can go through the process to get it access, but want to confirm that is needed, as it will take a fair amount of work on my side to get that approved.

**Comment by Jenefer-Monroe** [comment]
you might have a cached env var. Can you turn off the **_Admin | Sync Template v3 CoE Solution Metadata_** flow, turn back on, and rerun?

**Comment by Jenefer-Monroe** [comment]
for the audit log, it could also be a caching issue. 
1. Turn off then back on this flow:  Admin | Audit Logs | Office 365 Management API Subscription 
2. Run this flow with the input "start" (all lower case)
3. Open the run and see if it passed (or told you it was already turned on)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/af9e8491-d85e-4e61-b08e-77c5ca3ddb16)

4. Turn off then back on this flow: Admin | Audit Logs | Sync Audit Logs (V2)

**Comment by Jenefer-Monroe** [comment]
by the way, your debugging helped me figure out what was blocking some GCC folks from using setup wizard. I'm going to try and fit this fix in for July as a result of your help so THANK YOU
https://github.com/microsoft/coe-starter-kit/issues/5959

**Comment by pnoot7** [comment]
I guess mostly an FYI, I was setting up the Power BI dashboard and got several errors during it. In some combination of the yellow banners to refresh and apply items, they eventually went away and I was able to publish it. Not sure if local to me, or the report.

![PowerBI errors](https://github.com/microsoft/coe-starter-kit/assets/125403575/d80938fb-d369-4891-a077-e554e5e38bcc)

**Comment by Jenefer-Monroe** [comment]
Yes thank you. Sometimes people hit this and a refresh resolves. Some issue with the calc chain in PBI that gets fixed as you try again.

**Comment by pnoot7** [comment]
Getting a test environment running for future upgrades, and I had core 4.4.2 going to 4.9, and the set-up wizard gave this error. I believe I got this in my production too, but don't remember. Figured I would pass along. Seeing if I can continue or if I need to do it all manual in test env. 

![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/44aa2e0a-3113-4040-8663-0f397e6919e3)

**Comment by Jenefer-Monroe** [comment]
thank you. I think I'll just need to have someone internal do a test pass for me on non-commercial installs. Aprpeciate you pointing to the issues here.

**Comment by Jenefer-Monroe** [comment]
Have the following work item to track that test pass: https://github.com/microsoft/coe-starter-kit/issues/5959
