### ISSUE TITLE
[CoE Starter Kit - COE Sync flows are failing.

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#5943]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have issues with our COE flows. There are multiple flows failing and all are from Admin Sync flows everyday.

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/d3bedc8d-539f-41ac-8192-0c5d2eb8f31e)

One thing I observred is that like most of the flow failing is Admin Sync Template V3 (PVA). Admin Sync Template V3 (Flows). Admin Sync Template V3 (apps). We have Sync flows V4 in the solution but the error describing the V3. We turned on the flows with V4 versions as well.

I see all are running successful.
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/796e2aee-764f-4848-ad7c-040c9a0eaf50)

All the flows were working fine until the new update, After update the flows started failing.
Initially we had a issue in Start subscription flow and later we have fixed that. These flows are failing even after the issue is fixed.

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/306b59c8-cb82-4490-afc1-2c632963c30f)

I tried to open and check the error message, but it says as:

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/6eb9b9c5-b1df-4a3b-ad58-a0a80bc281b8)

### Expected Behavior

The flows should not fail.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin - Sync Template V3 (Flows)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
You should not see both v3 and v4 for flows. So likely your upgrade did not succeed

Can you please let me know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

And also share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Jenefer-Monroe** [comment]
Your list of failures shows the old flows though. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/12310a8b-ab77-4abe-a06f-2d90344ba88b)

**Comment by Jenefer-Monroe** [comment]
Perhaps we just need to simplify the ask here. Please pick a single issue from above for us to debug and we will dive into that.

**Comment by Jenefer-Monroe** [comment]
so this one should not be present per your comment above that this flow is no longer present. Is it an old failure? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/31a376bb-715a-461f-bd4c-974f2ff8c261)

**Comment by Neel1KNK** [comment]
This was from todays email I have received and failed. When I tried to open am unable to open
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/b7cb8349-d047-46bd-ae22-20ab7b39318e)

**Comment by Jenefer-Monroe** [comment]
Please go to your flow list and search as shown here and share a screenshot
https://flow.microsoft.com/ > your CoE envt > Core > Cloud flows > search for **_(Flows)_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d8953ab2-bfd7-48f4-afa6-996b10fe016f)

**Comment by Neel1KNK** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/7646e3b4-3605-4a41-8bd9-2aa9371e11a7)

**Comment by Jenefer-Monroe** [comment]
ok great. Then that failure may have been something that finally failed after a week when you installed. 
since that flow no longer exists there is nothign to investigate there.

**Comment by Jenefer-Monroe** [comment]
for this one, you'll need to open the failure to see where the flow fails
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6fd94604-e4ab-4b8d-ac8e-cb257be32d4b)

**Comment by Neel1KNK** [comment]
Initially I tried to troubleshoot on same and found the same as flow is not existing but still my flows are failing.

I get the same error when I try to open it for Admin Sync flows (PVA) as well
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/554a1c10-2d86-4dd7-b70f-635a7d1adb3d)

**Comment by Jenefer-Monroe** [comment]
ok you will need to manually find the error then. 
Go to that flow, and find the failure in the run list.

**Comment by Neel1KNK** [comment]
What do you mean manually 
When I tried to open this link it dosnet open and give this error:
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/765865e0-f0cd-4b47-991d-5435530dfc24)

When I go manually to Core solutions and open the PVA flow I don't see any of the failed flows
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/f4b39167-c1f8-46c3-a801-7006d941ad53)

Not sure where to troubleshoot exactly.

**Comment by Jenefer-Monroe** [comment]
ok I'm not sure what state you are in with this. It looks like you are mixing envirnoments here so I dont know if your failure was from your dev or prod. It looks like it was from your dev envt

**Comment by Neel1KNK** [comment]
This is the only environment where our COE flows are failing and this is the sandbox environment we have installed our COE.

This is from our Prod COE environment.

**Comment by Jenefer-Monroe** [comment]
I'm not sure then, I'm sorry I can't help. Your runs are gone, this isnt something that the kit controls. 
Either you are looking at the wrong envt for the runs or somehow the runs were wiped out by the product.
