### ISSUE TITLE
[CoE Starter Kit - QUESTION] Collecting audit logs using an HTTP action seem to get a permission issue 

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#5944]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

the account I am using has access to be allowed to view audit logs. But this happens when it errors out.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/90d572e0-1c9f-4431-b197-0d07eba7e481)

Is there something else could be happening for this error to appear.

### Expected Behavior

I am assuming I should either get 200 or 400 but I am getting 401.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription 

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
The permissions you need on the app registration are:

Office 365 Management API > Application permissions > ActivityFeed.Read.
Please see [Create an Azure AD app registration for the Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#create-an-azure-ad-app-registration-for-the-office-365-management-api)

This looks like you have incorrect permissions on the app registration.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
