### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by fshink** [microsoft/coe-starter-kit#5947]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

So this is more of a question than an issue.  I am looking at the Connection Reference Identity Table and see some references to the Twitter Connector. 

I checked with the connection owner, and she claims to not have ever used the twitter connection.  

How can i reconcile this?  Is there a way to see which flow that uses this connection?

I do have, and always had the twitter connector blocked so the data is a little weird to me. 

### Expected Behavior

NA just asking a question on how to find a flow from the Connection Reference Identity Table.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

admin - sync template

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

So this is more of a question than an issue.  I am looking at the Connection Reference Identity Table and see some references to the Twitter Connector. 

I checked with the connection owner, and she claims to not have ever used the twitter connection.  

How can i reconcile this?  Is there a way to see which flow that uses this connection?

I do have, and always had the twitter connector blocked so the data is a little weird to me.

**Comment by Jenefer-Monroe** [comment]
We cannot identify which connection is used in a flow/app, there is no mapping exposed to us. You can ask her to delete the connection though, and you can see if the connection is used anywhere in the PBI report or the PPAdmin App as shown here:

### Power Platform Admin View
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/310676df-bd4c-4bfc-8338-911528c0a0f9)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f9c43efe-8894-44a6-bf0b-3b88d563f8e7)

### PBI
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/048799a7-e6e8-464a-8694-b7acfb4f2d27)

**Comment by fshink** [comment]
Thank you very much, appreciate the info!

**Comment by Jenefer-Monroe** [comment]
Glad to help. I'll go ahead and close this out then, thanks for using CoE
