### ISSUE TITLE
[CoE Starter Kit - BUG] The server did not receive a response from an upstream server

### ISSUE THREAD

**Issue by joebeyer75** [microsoft/coe-starter-kit#5949]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Audit Logs fails with following message:

The server did not receive a response from an upstream server. Request tracking id '08585140649668171240798261180CU110'.

It fails on the action; Audi Logs Chunk Scope > Apply to each timeSegment > Run a Child Flow

Status Code: 502

{
  "error": {
    "code": "NoResponse",
    "message": "The server did not receive a response from an upstream server. Request tracking id '08585140649668171240798261180CU110'."
  }
}

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

March 2023

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, this is the same issue as your other bug. We can get you unblocked tehre
https://github.com/microsoft/coe-starter-kit/issues/5950
