### ISSUE TITLE
[CoE Starter Kit - BUG]: No impact analysis results being shown anymore in the DLP Editor V2 app

### ISSUE THREAD

**Issue by marcster** [microsoft/coe-starter-kit#595]
**Describe the bug**
No results are being shown in the impact analysis

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - 2.1.70
 - DLP Editor V2 app

**To Reproduce**
1. Open the DLP Editor V2 app
2. Create a new tenant policy
3. Add Power Apps for Admins to Business Data and leave all others in Non Business
4. Proceed through the wizard to the Impact Analysis screen
5. No results shown

**Expected behavior**
As the CoE Toolkit is installed in the environment I am running the DLP Editor in, there should be results showing flows and apps as the DLP policy being tested is not met as there is only one connector in the Business Data and some of the connectors used in the apps and flows are within the Non Business Data group.

**Screenshots**
![image](https://user-images.githubusercontent.com/1025102/121334617-b8622980-c911-11eb-9645-03014d5cd41e.png)
**Additional context**

**Comment by JeneferM-MSFT** [comment]
Can you please validate, is the DLP policy you are changing of scope envt or org? You can see by going to the admin center and viewing the column shown below
https://admin.powerplatform.microsoft.com/dlp
![image](https://user-images.githubusercontent.com/62659043/121354228-e9c7fe80-c8eb-11eb-8e4a-c4d935d2e629.png)

**Comment by JeneferM-MSFT** [comment]
I've heard a few people raise this so we will either add something to the documentation or the app itself to make this more obvious.

**Comment by marcster** [comment]
I was able to do this before in the older versions of this app. So, has this now been changed? What is the purpose of New Tenant policy button in the app then? 

I can also verify that the app is not working for any policies Environment or Tenant. The behaviour is the same as in the screenshot already attached/

**Comment by JeneferM-MSFT** [comment]
If that used to work, it wasn't recently. Either that or we are talking past each other. 
Let's solidify, and please let me know if this seems wrong, 

**Can do today**
1) Create a policy of scope tenant
2) Do impact analysis on pre-existing policies of scope tenant
3) Do impact analysis on pre-existing policies of scope environment
4) Get impact analysis on large datasets (before June release we had a delegation issue)

**Cannot do today**
a) Create a policy of scope environment
b) Use the impact analysis feature on a policy that has not yet been saved

**Comment by marcster** [comment]
Cannot do today
    Do impact analysis on pre-existing policies of scope tenant
    Do impact analysis on pre-existing policies of scope environment
    Get impact analysis on large datasets (before June release we had a delegation issue) - can't say as it is not working
    Use the impact analysis feature on a policy that has not yet been saved

Using DLP Editor V2 from Core Components version 1.89, this all works.

Haven't Tried
Create a policy of scope tenant  as this is done using the Admin portal by a team within my company with Global Admin rights.

**Comment by JeneferM-MSFT** [comment]
I'm afraid I dont repro any of these issues. 
```
Cannot do today
Do impact analysis on pre-existing policies of scope tenant
Do impact analysis on pre-existing policies of scope environment
Get impact analysis on large datasets (before June release we had a delegation issue) - can't say as it is not working
Use the impact analysis feature on a policy that has not yet been saved

```
The app is working for us, and for a few customers in the June release with whom I work. 

Can you please confirm that the user identity installing and running the flow has has the Power Platform Admin Role?  

Here is a document in case you need help finding that answer: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf)

**Comment by manuelap-msft** [comment]
Hello,

one more thing - we had to make some changes to how we get the information into the DLP Editor to overcome delegation issues in large tenants. You will have to run a FullInventory on your tenant to get all the fields we now need populated, you may be missing them at the moment and that's why the impact analysis isn't showing anything.

To run a FullInventory, go to the Default Solution and change the value of the FullInventory value to yes, and wait for the overnight sync flows to finish before changing it back.

Thank you
Manuela

**Comment by marcster** [comment]
@manuelap-msft  Thanks for this insight and it would be good to add this to the documentation for users who like myself who had the setting as No.  I am in the process of testing but will only be able to confirm if it works hopefully on Monday.

**Comment by marcster** [comment]
@manuelap-msft and @JeneferM-MSFT  I changed the setting FullInventory  to "Yes" but it was still not working. However, when I looked at the set up core components documentation, I saw that there was a new connector being used in the Admin | Sync Template v3 (Apps) and Admin | Sync Template v3 (Flows) cloud flows i.e. HTTP Azure AD Connector. In the company where I work, connecting to Azure AD in the cloud is not approved and is also blocked by DLP policies. I altered these two flows to remove where the HTTP Azure AD connector was being used. Of course, this means we will not be using the new check for the service principal makers but it is something we will have to live with. Once this was done, I could see the new fields being populated which are needed in the DLP Editor V2 canvas app.  The impact analysis is now being seen and I will now run further tests for the scenarios important to us. 

Thanks for pointing me in the correct direction. 
A few queries:

1. Is there a chance that a custom connector could be created instead of using the full blown HTTP Azure AD connector?
2. We also don't have approval for the Office 365 Outlook connector and so we create copies of those canvas apps which use that connector? Is there a possibility of shipping additional apps which don't have those connectors for some customers like us where we are not fully cloud but hybrid models?

If this is not the right place to raise these issues, please let me know where I should e.g. Enhancements

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
