### ISSUE TITLE
[CoE Starter Kit - BUG] Suspended Flow Due to DLP Policy

### ISSUE THREAD

**Issue by joebeyer75** [microsoft/coe-starter-kit#5951]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v3 (Call Updates) is failing with following message:

This flow is suspended due to data loss prevention policies applied to this flow and its child flow: 'HELPER - Maker Check'. Admin data policy '********* Data Policy' restricts use of these apis: /providers/Microsoft.PowerApps/apis/shared_webcontents.

This entire environment is excluded from the DLP policies, so not sure why we are getting these. 

When I look at the HELPER - Maker Check flow, it is running successfully and did so as recent as 12 hours ago. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2023

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Call Updates)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I'm afraid this is just the product detecting the flow as violating DLP and not something the kit makes happen. I would look back through the DLPs in your tenant and see if one got the CoE added, or was missed for exclusion.

**Comment by Jenefer-Monroe** [comment]
I'm afraid there isnt anything we can do here. The product is detecting your flow as violoating DLP, not the kit,so you will need to contact product support.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
