### ISSUE TITLE
[CoE Starter Kit - QUESTION] -Power BI report -What would happen when the number of objects in tenants exceed 10,000?

### ISSUE THREAD

**Issue by enotakadesu** [microsoft/coe-starter-kit#5952]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, I would like to ask a question about the Power BI report of CoE.
We are trying to set up the Power BI report using data from cloudflows.
I found a document below which said a performance issue could happen if the oblects in the tenant exceed 10,000.
![2023-06-28 130600](https://github.com/microsoft/coe-starter-kit/assets/137970094/b35a0d99-233a-43d3-b541-33c9f7821e07)
URL：https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory

What the performance issue have an effect on? Only on the Power BI report, or whole performance level of PowerPlatform?
I guess that it affect only on the Power BI report, but I would like to confirm that just in case.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
You may see throttling on the flows that fill the inventory. 
Once the data is in the inventory there is no issue in the performance of PBI getting that data. 
Hope that helps.

**Comment by enotakadesu** [comment]
Thank you for your reply!
I understood it only affect the perfomance of the flow which is used for the data extracting.

I would like to ask two more questions.
1)Is is possible to swicth the data source to Azure Data Storage from data flows when the number of objects exceed 10,000?
2)If possible, dose the previous data remain after we swich the data source?

Thank you for your cooperation.

**Comment by Jenefer-Monroe** [comment]
### Is is possible to swicth the data source to Azure Data Storage from data flows when the number of objects exceed 10,000?
Yes

### If possible, dose the previous data remain after we swich the data source?
Yes

Here are some additional [Data Export FAQ's](https://learn.microsoft.com/power-platform/guidance/coe/faq-dataexport) with more detailed explanations.

Hope that helps!

**Comment by enotakadesu** [comment]
Thanks for your reply!
I see.
I don't have further questions.
Thank you foy your help!
