### ISSUE TITLE
[CoE Starter Kit - Feature]: Power BI Reports enalbed Search option for every Dropdown Slicer Field

### ISSUE THREAD

**Issue by poi-radvine** [microsoft/coe-starter-kit#5954]
### Is your feature request related to a problem? Please describe.

The default Power BI reports you provide do not have the search option enabled for all dropdowns.
These reports are affected:
Production_CoEDashboard_June2023.pbit
PowerPlatformGovernance_CoEDashboard_June2023.pbit
BYODL_CoEDashboard_June2023.pbit

### Describe the solution you'd like

Could you please change your source report, so that in every dropdown the search function is enabled by default. The data model changes frequently and this results in me always returning to the same base report you provide and having to check the search tag on every page.
I added a screenshot so you know what I mean. This would help me a lot as we do this every month and it helps speeding up processes of our team a lot.

![image](https://github.com/microsoft/coe-starter-kit/assets/88713407/4a1b23c3-ce26-4824-9aea-3f3c61650d48)
Additionally it would also be nice to select multiple App Owners etc. without having to Ctrl-Click

### Describe alternatives you've considered

Doing it every month on my own for every report when the datamodel has changed.

**Comment by Jenefer-Monroe** [comment]
We are not PBI experts so we learn from you all here, thank you! 
Can you please show me how to set this property?

**Comment by poi-radvine** [comment]
Sure, it´s depicted in the attached image. (external source)
Just select the slicer, click the ... and enable search.
For large lists >6 items like Environments, AppId´s, UserNames, Connectors, this is an essential feature.
https://i0.wp.com/radacad.com/wp-content/uploads/2021/10/2021-10-13_09h59_43.png?ssl=1

**Comment by lrarbin** [comment]
We'd like this feature too! I'm surprised it's only been suggested in the last couple of days. When you have thousands of users, the slicers are difficult to use.

**Comment by Jenefer-Monroe** [comment]
local fixed for July
