### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Apps not visible for makers

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#5955]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have shared apps form CoE Setup and upgrdate Wizard page but still apps not showing .who has available in Makers group. Is that need to do anything else .

Is it required every single app with each user

### Expected Behavior

Need to Visible Makers apps to all Makers who has available Makers group. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Please select an individual person and app with which to test here and then: 

1. Validate that the person is in the maker group that you selected
2. Validate that the individual app is shared with the maker group. 

Please let me know what you find.

**Comment by sunilmhatugade** [comment]
If I want to share the app with the Maker group ... which is created for comminution .. Is it possible ..? 

from this view we can share or need to share from individual app.. 
![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/9e48a088-b50c-4ce9-8198-9e6c9cb466fd)

**Comment by Jenefer-Monroe** [comment]
This works for the apps listed (the canvas apps) to my knowledge. 
So if its not working for you we would need to debug as described above, by selecting an individual person and app which is not behaving as you expect and then:

1. Validate that the person is in the maker group that you selected
2. Validate that the individual app is shared with the maker group.

**Comment by sunilmhatugade** [comment]
for other apps. Develop compliance Center app how I can share ... 


Also in the "App catalog" apps are not showing. 

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/8c4aa87c-da5e-4657-9639-88f5a0a1932b)

**Comment by sunilmhatugade** [comment]
Still makers app does not visible who is part of the maker group.. is it required to provide environment access also ?

**Comment by sunilmhatugade** [comment]
can u please share step how we can share apps with all users who not port of our CoE environment.

**Comment by Jenefer-Monroe** [comment]
Do you have the envt secured by a security group? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3cf12ea-9a90-4f7e-a569-6415277f86e9)

It remains our recommendation that when you [create your environment](https://learn.microsoft.com/power-platform/guidance/coe/setup#create-your-environments), you set the security group to None

**Comment by sunilmhatugade** [comment]
is there any impact ... ? if we set it to none then .. it will be accessible to all users.

We don't want to provide permission to create any apps or flow under this environment for all users.

**Comment by Jenefer-Monroe** [comment]
When you add a security group to the enviroment as a whole, it means that users / groups cannot be added to the envt security roles (ex basic user or our custom SRs) without also adding them to this group. 
So if you want to go this route you would need this SR to include reference to your Admin, Maker, and User SRs, or they will not be able to use the features (approvals / shared apps / etc)

Leaving the security group to not assigned means that people can be added to different SRs without having to also have them in any envt wide group. It does not automatically grant people access to anything. They will need to be explicitly added to SRs to be able to create apps, see data, see apps, etc.

**Comment by Jenefer-Monroe** [comment]
link to the product documentation for more information: https://learn.microsoft.com/power-platform/admin/control-user-access

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
