### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Driver) Action - 'Get_organization' failed - MakerDisplayName SYSTEM and 'Helper - Maker Check' filter

### ISSUE THREAD

**Issue by tomka75** [microsoft/coe-starter-kit#5957]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The "Admin | Sync Template v3 (Driver)" flow fails with the error "Action - 'Get_organization' failed". Taking a deeper look it is a status code 502 in the "Get Maker" action, that is calling the flow. The action "Get Organization" runs without an error. And all runs of the helper are successful.
What we found: Tenant has multiple environments, some of them are created by the maker(displayname) "SYSTEM" with the MakerID "Microsoft Dynamics Deployment Server" which is not a GUID! When we run the helper manually and enter displayname and id, it is successfull. When the helper is called from the Admin Driver flow, both parameters were given, but in the run history of the helper, the MakerID is empty and only the name is filled in the trigger. The run is successful for the helper, but the Admin fails for multiple environments with the 502 Bad Gateway. So here something is not working correctly.
Additionally inside of the helper there is an aktion "Maker checked today" with a filter that is missing the '' around the admin_makerid, because in this tenant it is a string with spaces --> "admin_makerid eq Microsoft Dynamics Deployment Service and modifiedon gt 2023-06-27T08:53:54.0895948Z" should be "admin_makerid eq 'Microsoft Dynamics Deployment Service' and modifiedon gt 2023-06-27T08:53:54.0895948Z".

### Expected Behavior

Admin | Sync Template v3 (Driver) runs successfull

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Have a tenant with environments that are created by SYSTEM with ID "Microsoft Dynamics Deployment Server"
2. Install CoE Core 4.9
3. Run Admin | Sync Template v3 (Driver)
4. Admin flow fails for every environment created by this user

**Comment by Jenefer-Monroe** [comment]
Hello. This is due to the following issue which is resolved in the July release
https://github.com/microsoft/coe-starter-kit/issues/5613

Thank you for the detailed investigation!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
