### ISSUE TITLE
[CoE Starter Kit - QUESTION] how view rollup field expressions in dataverse

### ISSUE THREAD

**Issue by michael-wright-pwc** [microsoft/coe-starter-kit#5960]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I'm trying to view the rollup expressions for the following columns in the Environment table. Do you know of a way to do so in a managed solution? It doesn't seem possible from what I can tell (it's greyed out).

If not, could you please share screenshots of the rollup expressions?

Environment External Connection Count
Number of Apps
Number of Custom Connectors
Number of Flows

Thanks so much!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Go to the CoE environment > Tables > Environments > Columns > Filter by the string num > Edit
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a4f682f2-a816-41b9-a0fc-437234585f32)

Click Edit on the rollup, that will bring up a dialog where you can see the expressions used
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7181da9e-884c-4af3-8f0e-72bbc734eaf7)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dabbf6f4-20b5-4023-aa84-34d4e18f1b77)

Hope that helps!

**Comment by michael-wright-pwc** [comment]
Thanks Jenefer - yeah in managed solutions the "Edit" is greyed out. Sounds like we're just filtering out flows that are not deleted (makes sense).

What about these 3 columns (same logic)?:

Environment External Connection Count
Number of Apps
Number of Custom Connectors

**Comment by Jenefer-Monroe** [comment]
That picture is from a managed install. If instaed of going into the solution and then to Tables you go straight to Tables you will be able to access
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/60a625fc-dea8-4139-83e9-25c5c4819e85)

Please do let me know

**Comment by michael-wright-pwc** [comment]
Ah that does the trick - THANK YOU!

**Comment by Jenefer-Monroe** [comment]
Glad to help. This is a little trick I use all over, you can do things there that you cant do from within a managed solution. :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
