### ISSUE TITLE
[CoE Starter Kit - QUESTION] Would there be any issues if I were to change the Display Name of my Production COE environment

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#5961]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When I setup my COE kit in Feb 2023, I set the production environment display name to COE-DEV.
In May 2023, I created a separate environment that I use only for testing COE releases before upgrading COE-DEV.

Now, I want to rename COE-DEV to COE-PROD
Will that cause any issues?

(To do the rename, I would be going to the Power Platform Admin Centre "admin.powerplatform.microsoft.com" with my Admin account, click "Environments" on the left side panel, select the COE-DEV environment, under "Details" click "Edit", change the Display Name to COE-PROD, then "Save".)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
There should be no issue with that no. 

We have seen flow cache environment properties in the past such that the old name "sticks". However this doesnt always happen, and turning the inventory flows off and back on resolves that if it does happen to you.

**Comment by firefox-edge123** [comment]
Thank you for the information.
