### ISSUE TITLE
[CoE Starter Kit - BUG] Mashup Exception Error #5880

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#5963]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

https://github.com/microsoft/coe-starter-kit/issues/5880

### Expected Behavior

https://github.com/microsoft/coe-starter-kit/issues/5880

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June Release

### What app or flow are you having the issue with?

Refer to Original Issue

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

https://github.com/microsoft/coe-starter-kit/issues/5880

### Anything else?

https://github.com/microsoft/coe-starter-kit/issues/5880

**Comment by Jenefer-Monroe** [comment]
Hi there. We can re-open the other issue but its not actionable to us without further information and is likely a proudct issue, so you may want to also engage with product support.

**Comment by Jenefer-Monroe** [comment]
closing as dupe
