### ISSUE TITLE
[ALM Accelerator - QUESTION] Error running pipeline: CustomAzureDevOps.RunPipeline failed: The method 'RunPipeline' has an invalid value for parameter 'project'

### ISSUE THREAD

**Issue by tkudya** [microsoft/coe-starter-kit#5966]
### What is your question?

I have just finished setting up the ALM Accelator and just running a test i am getting the following error message

Error running pipeline: CustomAzureDevOps.RunPipeline failed: The method 'RunPipeline' has an invalid value for parameter 'project'

help
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/2f7e68cb-7005-4a48-81ee-9d9d87c63f6f)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

June 2023

**Comment by tkudya** [comment]
I have got it abit further that error is not coming up but getting this
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/bd9a8c94-ccff-45c1-8e99-4e855a332360)
 this is the deployment profile
 
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/66a3c096-f637-486f-89e6-d6540d91c9d0)

**Comment by mikefactorial** [comment]
@tkudya thanks for the update. Looks like you are having the same issue as #5856. We are still trying to investigate why this is happening for some but not others. Closing this issue out and will follow up on #5856 so as not to duplicate efforts
