### ISSUE TITLE
[ALM Accelerator - QUESTION] sync-repo exited with code 1

### ISSUE THREAD

**Issue by tkudya** [microsoft/coe-starter-kit#5967]
### What is your question?

I am just configuring ALM and I am at the stage of configuring this https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-pipeline-sync 

when i run the pipeline i keep getting

![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/15268eb4-eb48-42a0-b00b-b4de278b7291)

would you be able to advise what i might be doing wrong

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

June 2023

**Comment by mikefactorial** [comment]
@tkudya looks like you may be supplying incorrect parameters to that pipeline can you share what parameters you're supplying?

**Comment by tkudya** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/fc15a297-3e0e-45df-aed2-25901e44d108)
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/e72f0e3a-108d-4f7d-8b4f-0cc68bb0ccc0)
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/d1b38bdc-be48-4455-8bcc-fc053ee9b92f)

Are these what you are after?

**Comment by mikefactorial** [comment]
Thanks, that helps @tkudya. Rather than choosing to Sync from a "Branch" choose Sync from a "Tag". BTW the July release went out today if you want to upgrade to the latest.



![Image](https://github.com/microsoft/coe-starter-kit/assets/42348035/80767e10-4d01-4f56-837e-6aa6bdb7e579)

**Comment by tkudya** [comment]
this is has been succesful for me now

**Comment by mikefactorial** [comment]
Great thanks for reporting back @tkudya
