### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by sharrison01** [microsoft/coe-starter-kit#5972]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am experiencing an issue when attempting to complete the CoE will not complete the metadata setup flow. The process has been running for ~16 hours, and all other setup flows have completed.

### Expected Behavior

The wizard should complete setup flows in ~5 minutes.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin - Sync Template v3

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Duplicate tab
2. Refresh page
3. Refresh setup flow
4. Setup flows continue to stall

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/138142033/2488dab3-577d-4a68-8007-e35f79eb9f47)

**Comment by Jenefer-Monroe** [comment]
Looks like it accidently got triggered twice and it won't be listening for the second to finish, so this UX will never update.

If you re-open the setup wizard you may have to sit through the wait again but its unlikely that it will have the double call again. Please do let me know.

**Comment by sharrison01** [comment]
Hi Jenefer, thank you for the quick response. 

I attempted to initiate the process again, but the wizard continues to default back to the setup flow step and won't allow me to restart the wizard from the beginning. I've attached a screenshot to illustrate the current state and the option available when I view the  CoE upgrade and Setup Wizard App/Component.

![image](https://github.com/microsoft/coe-starter-kit/assets/138142033/da59217c-e632-4768-bb46-7d96c4b02750)
![image](https://github.com/microsoft/coe-starter-kit/assets/138142033/8143aa3a-0e51-4281-af0a-4ca149bb5c6d)

**Comment by Jenefer-Monroe** [comment]
thats ok, you can just click next from here.

**Comment by sharrison01** [comment]
When I click next, it jumps back into the setup flow process (still appearing to hang on the same processes):

<img width="923" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/138142033/5b85e631-c7c6-41f8-863f-790aafe028ad">

**Comment by Jenefer-Monroe** [comment]
Are you a commercial tenant or something else (like GCC?)

**Comment by sharrison01** [comment]
We are a commercial tenant.

**Comment by Jenefer-Monroe** [comment]
What version of Core do you have installed?

**Comment by sharrison01** [comment]
Version 4.8

**Comment by Jenefer-Monroe** [comment]
ok I did a big pass on papercuts like this in the Setup Wizard for 4.9. 
I would suggest you either
1. Do the [install manually](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-manually). At this point you just need to turn all the flows on
2. Upgrade to 4.9 and try again
3. Wait for the July release (Wednesday next week) and try that.

**Comment by sharrison01** [comment]
Sounds good. I will give those options a try and keep you posted. Thank you!

**Comment by sharrison01** [comment]
I attempted to import and run the 4.9 setup wizard yesterday. I left the session running so as to not interfere with the operation. Are you able to see if anything has completed on the backend, or if it would be safe to proceed in refreshing the page? I don't want to refresh and inadvertently trigger the setup a second time (like I did yesterday).

![image](https://github.com/microsoft/coe-starter-kit/assets/138142033/d529f860-0e6a-4cf2-b0e6-d48b4b9cdc03)

**Comment by Jenefer-Monroe** [comment]
No we cannot monitor your flow runs. Its ok to hit refresh here.

**Comment by sharrison01** [comment]
Thank you for confirming. Updating to version 4.9 resolved the setup flow issue and allowed me to complete the setup wizard, so this can be closed. Thanks again for all of your assistance!

**Comment by Jenefer-Monroe** [comment]
So glad you got through it! Thanks for letting me know!

**Comment by Jenefer-Monroe** [comment]
Wonderful news. Thanks for confirming you were unblocked.
