### ISSUE TITLE
[ALM Accelerator - templates repo usage in multiple projects instead of adding to each project ] 

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#5973]
### What is your question?

Hi Mike,

Do we need ALM Accelerator template repo in each project? We have many  CRM application code projects in DevOps, thinking that if we can have ALM accelerator template repo at root level/separate project and reuse it in all projects instead of adding ALM Accelerator template repo in each project. Is this something possible?

Thank you!

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April 19th 2023

**Comment by mikefactorial** [comment]
@lingutla123 yes this is possible and a lot of other organizations setup their projects this way. If you're using the Project Setup Wizard to setup the projects for storing your solutions you can point to an existing project for where the pipeline templates live. This will generate the export, import and delete pipelines in the project where the solutions are stored but point to the templates that live in another project. Similarly, when the deployment pipelines are generated for the solution they will point to the central repository for the templates. You will need to ensure that the pipelines are able to access the templates in another project by turning off the following setting in the Organization Settings of your Azure DevOps org.

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/cb0898d2-d8e7-4621-8c2a-8ecc2cc42319)

**Comment by lingutla123** [comment]
Thank You.

**Comment by mikefactorial** [comment]
Closing this out for now. Feel free to reopen if you have issues.

**Comment by lingutla123** [comment]
> Closing this out for now. Feel free to reopen if you have issues.

Hi Mike,

I have existing PowerApps project in DevOPs and trying to set up Pipelines using the "COE templates project" without creating separate repo for Templates in Power Apps project. For this, when I use Project Setup Wizard and select existing Power App Project, getting below error. Does reuse /refer to COE templates without creating template repo in PowerApps supported for empty/new projects only?

Thanks much! 
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/77df63d1-bbf9-46ee-b8d1-c51b75a64302)
