### ISSUE TITLE
[CoE Starter Kit - BUG] adminuser_upn storing guids instead of emails

### ISSUE THREAD

**Issue by caguilar169** [microsoft/coe-starter-kit#5976]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The audit log component is storing guids instead emails in the adminuser_upn and other user fields field in the admin_auditlogs table in dataverse 
![image](https://github.com/microsoft/coe-starter-kit/assets/5819140/81a6f9a7-acc9-498d-a989-79accd0e2201)

### Expected Behavior

THese user fields should store emails and not guids

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Production_CoEDashboard_April2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I dont repro this. Which of these techniques are you using to gether the audit logs? 

- [HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)
- [Custom Connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/763c38cd-8866-4a69-a3da-5fa84737577c)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
