### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Emails Not sending to Owners

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#5978]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The compliance details flows are generating the error below on requesting compliance details. The flows run successfully; however, the emails are not being sent.  Only the Admin | Compliance Details Request email (Apps) flow is working. Here is the image of the error message.

<img width="456" alt="Send_Audit_Email_to_Owner_Apps" src="https://github.com/microsoft/coe-starter-kit/assets/123478097/d3638466-f90e-45a1-92d6-20a6ad91fae9">

### Expected Behavior

When the Admin Requirement - Risk Assessment State selected value is Requested, an email sent to resource owners.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Admin | Compliance Details Request

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. In the Power Platform Admin View Model-Driven App, select Requested from the Admin Requirement - Risk Assessment State drop-down field.
2. Check the Power Automate Run history

**Comment by Jenefer-Monroe** [comment]
Hello, I do not repro, and you are on an older build (dec 2022) so it may be difficult to debug with you but we can try. 

What is shown for the inputs to this call?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a6bb06d3-acd0-456f-b9b3-9efd1aa42106)

What path does it go down here for picking assignee?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7d1105c5-dc65-4645-bb86-a7b1c64a7725)

**Comment by dcurt1977** [comment]
This is the path it go down. We customized the email notifications. What are the best approach to ensure that upgrading to the latest version doesn't override the email customizations? 
![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/061cd3ab-8b0e-46ed-b9f6-88ec8c31f2b9)

**Comment by Jenefer-Monroe** [comment]
What do you mean by customized? Did you customize the flow or the mail through our Command Center app? Or something else?

**Comment by dcurt1977** [comment]
In the Admin - Command Center app, we customized the CSS and HTML to fit our organization's brand and theme. Also customized the text in the body of the compliance emails in the Email table in the Core Components solution.

**Comment by Jenefer-Monroe** [comment]
If you customize via the command center then the chagnes should persist. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e9b84dac-9c16-4838-8aa6-f3858f969d77)

**Comment by dcurt1977** [comment]
The email is sending to the right person, the Send Audit Mail to Owner Apps is generating an error as shown in the image. This is from the Admin | Compliance Details Request eMail (Flows)

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/62e9215c-4203-48c0-839d-9a362e9f52c0)

**Comment by Jenefer-Monroe** [comment]
Sorry I'm a little confused. Is the original issue resolved then? Or do I just misunderstand?

**Comment by Jenefer-Monroe** [comment]
Either find the above run in the **_HELPER - Send Email_** flow, or retrigger it with the input. 
My guess is that you dont have SendOnBehalf setup for the desired account, but the flow will tell you why it failed.

**Comment by Jenefer-Monroe** [comment]
Find the run of HELPER - Send Email flow which resulted in the failure, or retrigger it with the input. Unless I can see this I cannot help debug.

**Comment by dcurt1977** [comment]
In the Customized Email table of the Send Audit Mail to Owner Flows, an email address is added in the cc line which is different from the email the flow is being sent from. When the flow ran, the email is being sent from the email added in the cc line which is incorrect. 
![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/8eaea432-44df-4084-889b-f49354240f14)

Here is an image from the Desktop flow where the email in the cc line did not get populated in the from field when the flow ran.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/97c27d70-5258-4eca-9055-14cf155b4408)

**Comment by Jenefer-Monroe** [comment]
I do believe its the From (Send As), espcially with the Forbidden note. Can you please share what the output is for this?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5c132646-2f67-4bb9-b176-022320a2242e)

**Comment by dcurt1977** [comment]
Here is the output. Once the email is removed from the cc line it worked.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/45dea337-4c4b-494d-a7cd-bc2c1fdd6a64)

**Comment by Jenefer-Monroe** [comment]
Aww yes I remember that bug now. It was fixed in the Feb version of the kit. You are due for an upgrade anyway and the July release has just shipped.
Please see https://github.com/microsoft/coe-starter-kit/issues/4402

**Comment by dcurt1977** [comment]
Yes, i'm planning for an upgrade next week and will provide feedback.
