### ISSUE TITLE
[ALM Accelerator - BUG]: Feature to Specify Connection ID doesnt work when using other user's (service account for eg) connection ID

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/coe-starter-kit#5981]
### Describe the issue

Feature to Specify Connection ID doesn't work when using other user's (service account for e.g.) connection ID. When we commit the solution, the deployment settings are not getting saved and uses the deployment user's connection instead of the specified connection ID. Could you please check this.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

 1.0.20230606.1

### Steps To Reproduce

1. Click on Configure Deployment Settings
2. For any connection reference, specify the connection ID from another user in target environment
3. Click on save and commit
4. Open the Configure Deployment Settings again to verify the saved values.

**Comment by mikefactorial** [comment]
@tomjosbin we have a similar issue report from @jfung85 #6011. Closing this out and will follow up on that issue. We have a meeting scheduled to discuss on Monday.

**Comment by mikefactorial** [comment]
Will update #6011 with our findings next week.
