### ISSUE TITLE
[ALM Accelerator - QUESTION] Guidelines on going back to a previous solution version

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/coe-starter-kit#5984]
### What is your question?

Hello Team,

Could you please help us with the best way of going back to a previous version of a solution deployed through ALM Accelerator.

In Pipelines for Power Platform we are able to download the managed and unmanaged version directly from the artifact.

How we can do something similar here in ALM Accelerator as we already saves both versions in DevOps.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

 1.0.20230606.1

**Comment by mikefactorial** [comment]
Hey @tomjosbin. We don't have any published guidance on this today. Would like to get your feedback on what the ideal scenario would be here. You can always import a solution based on a branch but that may not cover all scenarios. There's a similar request here https://github.com/microsoft/coe-starter-kit/issues/4304. I'm going to close out this issue and ask that you comment back on the ideal scenario in that issue.
