### ISSUE TITLE
[CoE Starter Kit - QUESTION] Help with Dataverse security requirements for a 3rd party dev

### ISSUE THREAD

**Issue by Tracharr** [microsoft/coe-starter-kit#5987]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have a 3rd party developer that needs to create dataverse tables, however I do not want them to have system customiser as that gives them the ability to modify the environment, what exact permissions do they need just to be able to create & modify dataverse tables?

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid this is a general product question and not a question about the starter kit. We are a very small team and so cannot scale to assisting with generalized questions like this. You may have luck asking the general PP community though, its a great community: https://powerusers.microsoft.com

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
