### ISSUE TITLE
[CoE Starter Kit - BUG] -- Not able to load the data -- all the tables are empty "Power Platform Governance COE Dashbaord"

### ISSUE THREAD

**Issue by VaraDonaparthi** [microsoft/coe-starter-kit#5988]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This is not a new bug. 
Recently we had got a KT and  downloaded COE starter Kit to integrate with our Existing ENV and load the data  from the power apps.
We don't see any errors and data is not loading  as the tables are empty. Please find below attached images
![image](https://github.com/microsoft/coe-starter-kit/assets/138544015/a5cc0f49-3304-40ad-8d79-aeae2d58f9a0)
![image](https://github.com/microsoft/coe-starter-kit/assets/138544015/8e8ae831-340d-4ca5-abbb-b8486c3e75fb)

### Expected Behavior

Ideally  tables have to be loaded with data and PowerBi should display the Report

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Core

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Navigate to "COE Starter KIT" folder from the downloads
2. Click on " Production_CoEDashboard_May2023" 
3. Dashboard will be Opened in Power BI
4. Provide the Url to connect : "https://coesandbox.crm5.dynamics.com/"
5.  Once the connection is established, power Bi dashboard is displayed
6. Check for the data : All are blank
7. Expected Behavior: Dashboard to load all  data of other ENV available in the power apps
8. Actual Behavior: Dashboard is showing blank instead of values as the tables under "transform Data" are empty. No errors or exceptions observed

### Anything else?

power Bi to load data

**Comment by manuelap-msft** [comment]
Have you followed the setup steps here to set up the inventory components?
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components

**Comment by Jenefer-Monroe** [comment]
Please also do the following:
1. Browse to the Admin Command Center > Environment Variables > What is the value for this item? 
![image](https://user-images.githubusercontent.com/89584709/230621685-2f293271-b215-4f91-8234-0f39c8f638e9.png)
2. Browse to the Admin Command Center > CoE Flows Page > Inventory. When did this flow last run and did it pass? Click Flow details to browse to it. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8603efba-6eb3-4813-a66f-475c7f8a1a22)
3. Open the most recent run. Does it make it down to this call? If so how many environments are returned? You can see this by popping it into a json parser.
![image](https://user-images.githubusercontent.com/89584709/230622587-e17a3ad2-e1d2-4d58-8a0c-255aa469359d.png)

**Comment by VaraDonaparthi** [comment]
Hi Jenefer,

               Please find below the details:

             We Could not find the required info using the path provided by you
               Verified through "PowerApps--> EPMSCOESandbox (Click on ENV)--> Select Solution --> Default Solution --> Check for Environment Variables and Cloud flows

  1.  Browse to the Admin Command Center > Environment Variables

Could  not  check for the values as the menu does not show the Environment variables.

NOTE: Using Power APPS Could verify the value kindly check the next ***@***.***



[image]

  1.  Browse to the Admin Command Center > CoE Flows Page > Inventory. When did this flow last run and did it pass? Click Flow details to browse to it.
NOTE: The request flow  was not turned on . I have turned it on today Can verify the requested values tomorrow and get back to you
***@***.***
Thanks,
Varalakshmi

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by VaraDonaparthi** [comment]
Hi Jenefer,
Sorry that i could not answer at the earliest
I have an issue in this section 
**Configure connections to data sources**

1. Navigate to [make.powerapps.com](https://make.powerapps.com/).
2. Select the environment you've installed the CoE Starter Kit in.
3. Select Dataflows.
4. Edit the CoE BYODL Makers dataflow. Edit the CoE BYODL Makers dataflow.
I dont have edit access for the above flow
how can we get that?
![image](https://github.com/microsoft/coe-starter-kit/assets/138544015/3fe42579-9de6-4041-8dd1-f6a213987f5f)

**Comment by VaraDonaparthi** [comment]
Hi Jenefer,
Sorry that i could not answer at the earliest
I have an issue in this section , We donT have edit access. Can you please assist as what can be done
Configure connections to data sources

  1.  Navigate to make.powerapps.com<https://make.powerapps.com/>.
  2.  Select the environment you've installed the CoE Starter Kit in.
  3.  Select Dataflows.
  4.  Edit the CoE BYODL Makers dataflow. Edit the CoE BYODL Makers dataflow.
I dont have edit access for the above flow
how can we get that?
[image]<https://user-images.githubusercontent.com/138544015/253234964-3fe42579-9de6-4041-8dd1-f6a213987f5f.png>
Thanks,
Varalakshmi
