### ISSUE TITLE
[CoE Starter Kit - BUG] "App Details" button in "Power Platform admin view" App doesn't work in specific environments

### ISSUE THREAD

**Issue by Laisten** [microsoft/coe-starter-kit#5989]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

"App Details" button in Power Apps admin view App doesn't work in specific environments
![image](https://github.com/microsoft/coe-starter-kit/assets/130041524/661c5d7c-297c-4a0c-a65b-404eb2ea5675)

Reproduce Steps
============
1. Open "Power Platform admin view" App
2. Click "PowerApps Apps" in left manu
3. Click one of Canvas App
4. Click "App Details" in ribbon button
5. It throws the following error

Error
=============
- Component library is still being published. Try again.

Additional Info
=============
- There is one more CoE environment which took the same step to implement it. The environment side CoE kit with "App Details" button works as expected. Please advise how to solve or steps the we may perform.

### Expected Behavior

It should route App Details page in PowerApps Maker Portal

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

Power Platform admin view

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Open "Power Platform admin view" App
2. Click "PowerApps Apps" in left manu
3. Click one of Canvas App
4. Click "App Details" in ribbon button
5. It throws the following error

### Anything else?

Please advise how to solve this issue. Thank you.

**Comment by manuelap-msft** [comment]
Hello,

we've not seen this issue before! It's possible this can happen when the solution hasn't finished importing yet. Have you just recently imported the solution into the environment? If you go to the Solutions > History tab in the environment, does the CoreComponents solution show with a start and end time?
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/7681c9c7-6e5c-4a57-8fdc-2b216ccdb68c)

**Comment by Laisten** [comment]
Hello @manuelap-msft ,

Thanks for your quick response. Please see below: **Solution installed successfully**

![image](https://github.com/microsoft/coe-starter-kit/assets/130041524/2e237b07-60ee-486a-930b-3650a82db25b)

**Comment by Laisten** [comment]
Hello @manuelap-msft ,

I have confirmed that the feature doesn't work for Korea data center(*.crm21.dynamics.com) environments only. The same tenant has APAC data center(*.crm5.dynamics.com) environment and confirmed that it works as expected.

There is another KR tenant that implemented CoE Kit solution and confirmed that this "App Details" button also doesn't work and shows the same error message.

Would you please check whether there is any required action/implementation for newly deployed region's data center? Korea data center for Dataverse deployed in April 2022.

**Comment by manuelap-msft** [comment]
Hello,

thanks for the detailed debugging here, narrowing this down to the Korean data center. Would you be able to raise a Microsoft Support Ticket for this and let me know the support ticket number so I can follow up internally. It seems to be a product-related issue, independent of CoE kit capability, so a support ticket will help us get traction internally when I reach out to the Engineering team.

Thank you
Manuela

**Comment by Laisten** [comment]
Thanks @manuelap-msft ,

I provided the information. Thanks for following up on this matter.

**Comment by manuelap-msft** [comment]
Closing out as no further action required by CoE team.
