### ISSUE TITLE
[CoE Starter Kit - QUESTION] What does the blank values in App Last Launched , Flow latest run indicates?

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#5992]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We started using CoE BYODL since this April. 
After 2-3 months of usage, we see that many entries for apps - in column app last launched, sessions it is blank.
So as for the flows.
What does it indicate? does the blank value means the apps / flows were not launched since April (when we imported COE) ?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
Yes, it could indicate that. If you're seeing app and flow usage come through for other apps, and the Dataflow refresh is working fine then the most likely cause for these being empty is that they haven't been launched/run since you've set up the CoE kit.
