### ISSUE TITLE
[CoE Starter Kit - QUESTION] How is the data sync happens in BYODL?

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#5993]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How is the data sync happens in COE? i.e Does it take data from Datalake and store it inside the dataverse tables using Dataflows? as well as data from cloud flows. ?

If this is the case? why don't we see usage table? and why the PBI dashboard has separate dataflow to sync?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
Can you review our FAQ section on the Data export topic first, and let me know if you have further questions 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq-dataexport#how-does-the-coe-starter-kit-consume-data-from-the-data-export-feature

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
