### ISSUE TITLE
[CoE Starter Kit - QUESTION] Developer Compliance Center Link in the Notification goes to an error screen

### ISSUE THREAD

**Issue by 1jena5** [microsoft/coe-starter-kit#5998]
### Describe your bug, question or feature ask.

Hi,

We recently updated to June 2023 and the Developer Compliance Center Link to the app in the Notification for keeping the app updated to stay compliant goes to an error screen. The app is working fine if opened from Power platforms, only the link from the notification has error. Please see attached screenshots.

This is the link in the email notification - https://org7d621975.crm.dynamics.com/main.aspx?appid=0c093032-63b1-ed11-9885-000d3a17af33?appName=410a1a9d-e1f8-4fec-a259-df7ce64c4480

![ComplianceError](https://github.com/microsoft/coe-starter-kit/assets/94581451/62db446e-e9fa-44a7-8869-514d1b1c07d8)
![ComplianceEmail](https://github.com/microsoft/coe-starter-kit/assets/94581451/4ed5d189-e0c0-49c1-afc3-fa21cb4c663c)

**Comment by 1jena5** [comment]
Hi, I checked and we do not have any unmanaged layer. I checked the workflow run and it sends to this link that is directed to the error I attached.

<a href='https://org7d621975.crm.dynamics.com/main.aspx?appid=0c093032-63b1-ed11-9885-000d3a17af33?appName=66525f13-f791-4082-a3e5-b57d33f4f727'>Developer Compliance Center</a>

This is the code
<a href='@{parameters('Developer Compliance Center URL (admin_DeveloperComplianceCenterURL)')}?appName=@{items('Apply_to_each_envt_App')?['admin_appid']}'>Developer Compliance Center</a><br><br>

This is the app id of our dev compliance center - 0c093032-63b1-ed11-9885-000d3a17af33. This also produces an error when added in the parameters given. Can you advise if our current workflow is incorrect?

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of the flow you are referencing that is failing?

**Comment by 1jena5** [comment]
Hi, It is the Admin | Compliance detail request v3 flow. It is not really failing, it's just the link to Compliance Center has an error when clicked. After reinstalling again it works now but we are now directed to a page not found error but we can navigate to the other tabs.
![devcomperror](https://github.com/microsoft/coe-starter-kit/assets/94581451/5ed998fd-9342-4606-a60b-73b2560c3e81)

**Comment by Jenefer-Monroe** [comment]
What version of Core are you on? 

Please go to **_Admin | Compliance Details Request eMail (Apps)_** and open the flow in edit mode. Share what you see here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ba057d56-9f46-4c0b-b2ce-aa53a58faa87)

**Comment by 1jena5** [comment]
Version 4.11 for the Core Components
Admin | Compliance detail request v3 flow
![CaptureDevCompl](https://github.com/microsoft/coe-starter-kit/assets/94581451/0ad7ac18-6129-4d16-96be-7df20d16a59c)
Admin | Compliance Details Request eMail (Apps)
![CaptureDevCompApps](https://github.com/microsoft/coe-starter-kit/assets/94581451/7e41decd-be69-4d7f-80d7-b0eaf6bd8aae)

**Comment by Jenefer-Monroe** [comment]
The correct flow for sending to flow should be **_Admin | Compliance Details Request eMail (Flows)_** and has this. Is that the name of the flow you see? If so, you must have an unmanaged layer on it

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3ad9f8d-9f04-4dfb-a187-0d7a6d030950)

**Comment by rrwolfe** [comment]
Hi Jenefer - I'm seeing the same issue in my environment. The steps that send the Republish Email (email GUID: 4169820e-ca41-ec11-8c62-00224829b4c1) are hosted in the Admin | Compliance detail request v3 flow. The URL looks to be misconfigured when you compare it to the Send Audit Mail to Owner Apps action from the Admin | Compliance Details Request eMail (Apps) flow. The link in the Send Audit Mail to Owner Apps action works successfully.

Screenshot of the misconfigured link:
![image](https://github.com/microsoft/coe-starter-kit/assets/74214126/a3a96e7d-ee5a-482e-9346-c4247d541665)

**Comment by 1jena5** [comment]
Apologies for the confusion, what I sent screenshot above is for **Admin | Compliance detail request v3** and **Admin | Compliance Details Request eMail (Apps)**. Having the same issue in another Tenant, this seems to me an error in the worfklow from the toolkit.

**Comment by Jenefer-Monroe** [comment]
Oh gosh wonderful, thanks so much for helping us reach clarity! 
Good ok so its in this flow that we missed updating one of the mails: 
**_Admin | Compliance detail request v3_**. 
I do repro this! yeah! Local fixed for August.
