### ISSUE TITLE
Pipelines: Replace solution upgrade task with official (when available)

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#6]

**Comment by rpothin** [comment]
I think it is only this file that will need to be updated: **coe-starter-kit/src/Pipelines/Templates/deploy-Solution.yml**

**Comment by devkeydet** [comment]
Correct.  That's the yml file that will be updated.  Work on this is already in progress internally.  There will be a set of these issues that will all be closed when we get our latest source into this repo.  The goal of sharing them now was mostly for transparency of our backlog.  Once we are able to formally switch to this repo, we will close a number of issues well before we are ready to take contributions.

**Comment by devkeydet** [comment]
Resolved in private preview repo.
