### ISSUE TITLE
[AA4AM]: Solution not appearing after import

### ISSUE THREAD

**Issue by coatsy** [microsoft/coe-starter-kit#600]
After running the import pipeline, the solution is imported into the environment, but does not appear in the list of solutions in the app

**To Reproduce**
1. Run AA4AM
1. Click Import Solution
1. Choose the Branch and Solution from the dropdowns in the import dialog
1. Click Import
1. Watch the import pipeline run
1. When complete, refresh the view
1. Note that the imported solution does not appear
1. Click the Import Solution icon again
1. Observe that the import is listed as successful
![image](https://user-images.githubusercontent.com/1772428/121455771-63451700-c9e8-11eb-9c8f-d86310a32133.png)

Note also that the solution appears in the appropriate environment in the Power Apps portal

![image](https://user-images.githubusercontent.com/1772428/121455894-8cfe3e00-c9e8-11eb-9a75-6cd977690257.png)

**Expected behavior**
Solution appears

**Comment by coatsy** [comment]
Re-opening this app and selecting the environmment gives the following eror:

![image](https://user-images.githubusercontent.com/1772428/121456266-2594be00-c9e9-11eb-9dba-8300a3acb058.png)

Looking for where to configure the connection...

**Comment by mikefactorial** [comment]
@coatsy I've seen that issue but only when importing the solution through the API and not rewiring the connection reference for the GetEnvironmentSolutions flow. Assuming you imported the solution via the user experience which would prompt you to create the necessary connections I'm not sure how it could have gotten into that state. Could it be that the connection needs to be shared with the demo user?

**Comment by mikefactorial** [comment]
@coatsy any update on what the root cause might be here?

**Comment by coatsy** [comment]
@mikefactorial, nope - been on holiday. Back now and looking.

**Comment by coatsy** [comment]
>Assuming you imported the solution via the user experience which would prompt you to create the necessary connections I'm not sure how it could have gotten into that state.

I did import the solution through the UI

> Could it be that the connection needs to be shared with the demo user?

Not sure what I need to do here - can you please elaborate?

**Comment by coatsy** [comment]
Ok - think I solved this one - the demo user needed ReadSolution rights (I updated the ALM Power App Access role to include this).

![image](https://user-images.githubusercontent.com/1772428/122005781-6762a180-cdf9-11eb-92e0-eb6ceee7803a.png)

@mikefactorial, I think we should file this as a bug either in docco or in the solution itself.

**Comment by coatsy** [comment]
Adding an AAD security group with all of the demo devs in it and making that group a co-owner of the `GetEnvironmentSolutions` cloud flow seems to have fixed this. I guess that what you meant by

> Could it be that the connection needs to be shared with the demo user?

**Comment by winterscar** [comment]
Bump on this with the same issue and same fix. App was deployed both manually and via pipeline (no difference) and the fix was to make the user a co-owner of the flow. Being environment admin did not make a difference. This seems like a recent change.

**Comment by mikefactorial** [comment]
Thanks @coatsy and @winterscar for the repro and the solutions. Certainly shouldn't need to make all users co-owner so we'll have to figure out what's going on there as well as update the included security role which we already have an issue #123 in the backlog for that I'll add the info too as well.

**Comment by mikefactorial** [comment]
@coatsy and @winterscar I believe I've found a resolution to needing to make users co-owners of the Flow. If you have a chance, in addition to the added solution permission, can you try giving the users **global permissions to the process entity** and removing them as a co-owner? There's another bug I think I found as well that's related and both fixes are in this PR #676

**Comment by mikefactorial** [comment]
An alternative to giving organization level permission to the process entity is to give user level permission to process and then share the GetEnvironmentSolutions process with the specific user(s).

**Comment by winterscar** [comment]
Thanks for looking into this mike, that fix does indeed work. What I don't understand however is why it's needed in the first place?
Surely sharing an app with a flow should implicitly share that flow as well?

**Comment by devkeydet** [comment]
We'll share your feedback with the team who owns the design of this.
