### ISSUE TITLE
[CoE Starter Kit - BUG] Inventory flows won't turn on

### ISSUE THREAD

**Issue by brigidaanne94** [microsoft/coe-starter-kit#6004]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Add make to group, Admin | Sync template v3 (connection identities), Admin | Sync template v3 (Call updates) flows won't turn on during CoE setup wizard. I click on the toggle to turn it on and it doesn't work. Can't move forward in the setup process.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

CoE Setup Wizard

### What method are you using to get inventory and telemetry?

None

### Anything else?

![Snag_2dd3fe90](https://github.com/microsoft/coe-starter-kit/assets/106391215/2f00698d-8b59-42a3-b171-9ccce7635df4)

**Comment by Jenefer-Monroe** [comment]
You can move forward, there is a bunch of timing here to make the flow easier, that typically means the flow is already on now but still in the collection. 
When done you can go to the Command Center and make sure everything you need to be on is on
