### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 (Environment Properties)

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6005]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Sync Template flow does not run properly. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/2dee07e2-68ad-49b2-838e-b2f78fb828c0)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/ce0ac618-5aba-4418-a9d4-6889d4e467bb)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/b15a1fe4-3bb8-4fd6-8e81-d4b6b8e4b5be)

### Expected Behavior

Flow should run

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June Release

### What app or flow are you having the issue with?

Sync Template v3 (Environment Properties)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run Scheduled flows normaly.

**Comment by Jenefer-Monroe** [comment]
You dont seem to have the correct actions in there. You shoudl see this which catches some of the errors: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5766d74b-803a-493a-a112-6790d3969cc3)

Can you please check to see if you have unmanaged layers on this flow?

**Comment by nasilvae** [comment]
> You dont seem to have the correct actions in there. You shoudl see this which catches some of the errors: 
> 
> ![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5766d74b-803a-493a-a112-6790d3969cc3)
> 
> 
> 
> Can you please check to see if you have unmanaged layers on this flow?

Correct, this flow does not have any unmanaged layers.

**Comment by Jenefer-Monroe** [comment]
Your failure
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e74b3b2e-be40-4fcc-9f79-2d50374cc73f)

doesnt have any of these actions though
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/552a28fb-11cb-4890-b910-2a8ae86d45eb)

**Comment by nasilvae** [comment]
> Your failure ![image](https://user-images.githubusercontent.com/89584709/251303551-e74b3b2e-be40-4fcc-9f79-2d50374cc73f.png)
> 
> doesnt have any of these actions though ![image](https://user-images.githubusercontent.com/89584709/251303629-552a28fb-11cb-4890-b910-2a8ae86d45eb.png)

Hi When opening the folow in edit mode we can see the same actions. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/595b13ce-2bc0-423b-928e-3a39dd14b442)

**Comment by Jenefer-Monroe** [comment]
the failure must have been an old one then. Please rerun it.

**Comment by nasilvae** [comment]
> the failure must have been an old one then. Please rerun it.

gotcha, we are getting this error now. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/e103ccdd-81c3-44dc-aa92-299ce1774bfa)

**Comment by Jenefer-Monroe** [comment]
Please share a view that is zoomed out a bit so I can see the calls that occurs before and after. This should be caught.
