### ISSUE TITLE
[CoE Starter Kit - HOWTO] Convert audit logs to http format from custom connector 

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#6009]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

If you are converting from collecting audit logs using [a custom connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog) to [an Http call](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http), here are the steps to follow

### Update app registration
1.	Browse to your app registration. 
2.	API Permissions > Remove the delegated permissions to Office 365 Management APIs ActivityFeed.Read
 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5e788fcb-e251-454b-9510-4ccb17387074)

3.	Add instead Application permissions to Office 365 Management APIs ActivityFeed.Read and get it granted for the organization
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d49db08b-2963-4a44-9384-099e2a3ca23c)

 ### Update Env Variables
Update as described here: [Update environment variables](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables)

### Remove old solution
Delete the old audit logs solution, you no longer need those flows and the data is stored in Core.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8ca7e575-860c-4bc0-a0cc-3f4945b5d89b)

### Ensure subscription started. 
As described here: [Turn on subscription](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

### Turn on new flows
As described here: [Turn on flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#turn-on-flows)
Note: if these flows are already on, turn them off and back on to ensure they gather the environment variables as set above.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

audit logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by jax-coe-admin** [comment]
Can the "Office 365 Management API" custom connector also be removed?  I assume, yes.

![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/193d1dda-22fc-4f67-99eb-48325e5f50c7)

**Comment by Jenefer-Monroe** [comment]
It will be removed when you upgrade to the August+ release. Please be sure to delete the old Audit Logs solution if you have it installed or your upgrade will fail.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by gprof** [comment]
I am unable to delete the old Center of Excellence - Audit Logs solution because I get below dependency error:

![image](https://github.com/microsoft/coe-starter-kit/assets/25688152/42bb1ffc-a106-4cbe-b9e6-a42a5565a483)

These dependent flows are in the CenterofExcellenceCoreComponents_Upgrade which I am also unable to Upgrade or Uninstall. Seems I cannot move forward or backward.

Please advise.

**Comment by Jenefer-Monroe** [comment]
Hello you need to delete the audit logs solution before you can delete the connection refernces

**Comment by RandomDept** [comment]
It mentions updating the Environment variables with a link to the generic how to.
Would be good to call the specific ones to update out.
