### ISSUE TITLE
Upgrading governance solutions error - There are missing dependencies. Install the following solutions before installing this one: "Active".

### ISSUE THREAD

**Issue by jw97305** [microsoft/coe-starter-kit#601]
**Describe the bug**
When attempting to upgrade the solutions, I get the error when upgrading the governance solution: There are missing dependencies. Install the following solutions before installing this one: "Active".

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution- Governance
 - Version 1.28 to 1.61 or 1.43 to 1.61

**To Reproduce**
I am trying to update all solutions from the February packages to the latest release.
1. remove all unmanaged layers from core components
2. upgrade core from 1.78 to 2.1
3. remove all unmanaged layers from audit log components
4. upgrade audit log components from 1.34 to 1.41
5. Upgrade governance components from 1.28 to 1.61 (i forgot to remove unmanaged layers)
6. Get error Upgrading solutions: Error - There are missing dependencies. Install the following solutions before installing this one: "Active".
7. Remove unmanaged layers form Governance components
8. Error upgrading again
9. delete Governance components 1.28
10. Install Governance components 1.61 (won't install due to dependencies, same error below)
10. Install Governance components 1.43
11. Upgrade governance components from 1.43 to 1.61
11. Error upgrading again, same error below
12. Upgrade nurture components 1.23 to 1.51
13. Error upgrading nurture components
14. Delete nurture components
15. install nurture components 1.51 successfully
16. Upgrade governance components from 1.43 to 1.61
16. Error upgrading again

**Expected behavior**
The solution will be imported successfully

**Additional context**
[{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: CenterofExcellenceAuditComponents. Some dependencies are missing. The missing dependencies are : <MissingDependencies><MissingDependency><Required key=\"14\" type=\"connectionreference\" displayName=\"admin_CoECoreDataverse2\" solution=\"Active\" id.connectionreferencelogicalname=\"admin_CoECoreDataverse2\" /><Dependent key=\"10\" type=\"29\" displayName=\"Admin | Archive and Clean Up v2 (Start Approval for Apps)\" id=\"{d740e841-7057-eb11-a812-000d3a9964a5}\" /></MissingDependency><MissingDependency><Required key=\"30\" type=\"2\" schemaName=\"admin_apparchiverequestignoredsince\" displayName=\"App Archive Request Ignored Since\" parentSchemaName=\"admin_app\" parentDisplayName=\"PowerApps App\" solution=\"Active\" /><Dependent key=\"29\" type=\"26\" schemaName=\"APPS  - approvals ignore for 1 month+\" displayName=\"APPS  - approvals ignore for 1 month+\" parentSchemaName=\"admin_archiveapproval\" parentDisplayName=\"Archive Approval \" id=\"{2b738278-f3b7-eb11-8236-0022481cc098}\" /></MissingDependency><MissingDependency><Required key=\"32\" type=\"2\" schemaName=\"admin_flowarchiverequestignoredsince\" displayName=\"Flow Archive Request Ignored Since\" parentSchemaName=\"admin_flow\" parentDisplayName=\"Flow\" solution=\"Active\" /><Dependent key=\"31\" type=\"26\" schemaName=\"FLOWS  - approvals ignore for 1 month+\" displayName=\"FLOWS  - approvals ignore for 1 month+\" parentSchemaName=\"admin_archiveapproval\" parentDisplayName=\"Archive Approval \" id=\"{92fa95f3-f4b7-eb11-8236-0022481cc098}\" /></MissingDependency></MissingDependencies> , ProductUpdatesOnly : False","ErrorCode":-2147188707,"AdditionalInfo":null}]

**Comment by JeneferM-MSFT** [comment]
There are new fields in Core upon which Gov relies. You need to upgrade your Core version to the latest before upgrading Gov. 

Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not removed the unmanaged layers as described there you will not receive updates from us.

**Comment by JeneferM-MSFT** [comment]
closing out as no further work for the toolkit
