### ISSUE TITLE
[CoE Starter Kit - Feature]: Store App Compexity information (ex PCF Control Count) for PowerApps App table

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6014]
### Is your feature request related to a problem? Please describe.

The goal is to enable impact analysis for apps that use PCF components. The scenario is that an environment has PCF components enabled, and an admin may want to disable that - we then want to run an impact analysis to show which apps are using PCF components.

This information is available in new properties that have recently been added to the Get Apps as Admin output, in the appDocumentComplexity scope:

 "appDocumentComplexity": {
                        "controlCount": 77,
                        **"pcfControlCount": 9,**
                        "uiComponentsCount": 7,
                        "totalRuleLengthOnStart": 2124,
                        "dataSourceCount": 11,
                        "totalRuleLengthHistogram": [
                            826,
                            560,
                            473,
                            36,
                            5,
                            2,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ],
                        "blocksOnStart": false,
                        "namedFormulasCount": 0,
                        "startScreenUsed": false
                    }

### Describe the solution you'd like

Either if pcfControlCount > 0: store a true/false in a new field of usesPCFControls 

OR (probably better option)

If we think we will use the appDocumentComplexity attributes for other purposes, such as showcasing complexity of an app (which could be relevant reporting), we could store pcfControlCount  as a number (and then the reporting would trigger on where pcfControlCount > 0).

**Comment by bch920** [comment]
@Jenefer-Monroe  would it be possible to store

dataSourceCount
controlCount
uiComponentsCount

ideally we would like to get an idea of how many "complex" apps we have.

**Comment by Jenefer-Monroe** [comment]
Thanks for the suggestion, I am looking at this next and do hope to have a good overall set of data for you so your suggestions are quite helpful!

**Comment by Jenefer-Monroe** [comment]
I just went ahead and added all of them. Still need to finish testing and make a view

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cd695eb8-e94b-497d-bea8-176258da001f)
