### ISSUE TITLE
[ALM Accelerator - BUG]: HTTP with Azure AD - need to input when citizen devs open the app for the 1st time

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#6021]
### Describe the issue

When a citizen dev opens AA4PP for the 1st time, they must input https://graph.microsoft.com to use the app

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/da0da5d7-1b72-4327-8c88-d8aa3311f34a)

I tired to bypass the consent with this documentation https://learn.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/set-adminpowerappapistobypassconsent?view=pa-ps-latest. but it doesn't work with this connector.

### Expected Behavior

In an ideal world, they just need to click on ok 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230606.1

### Steps To Reproduce

1. Open AA4PP for the 1st time
2. A prompt appears
3. input https://graph.microsoft.com in the 2 fields

**Comment by mikefactorial** [comment]
@tocri unfortunately I don't think this is a problem we can solve. Would need to be something the product team addresses. The ALM Accelerator is built on top of the Power Platform architecture so we're only able to work within the confines of what the platform provides.

**Comment by mikefactorial** [comment]
Closing this out as there's nothing we can do to resolve this since it's a platform limitation.
