### ISSUE TITLE
[CoE Starter Kit - QUESTION] July 2023 managed solutions actually unmanaged?

### ISSUE THREAD

**Issue by nlshelton** [microsoft/coe-starter-kit#6022]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I attempted to import some of the July 2023 managed solutions for upgrade in my CoE environment, and receive the message that the imported solution and existing solution must both be managed for upgrade. As my existing solution is managed, I think perhaps unmanaged solutions were accidentally tagged as managed in the GitHub release. Could someone please check?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

the solutions that were uploaded are the managed ones! Sometimes customers have seen this error message in the past when an app/flow in the CoE solution was open for editing or had unmanaged layers. You may have to check if you or anyone else has a flow/app that's part of the CoE kit open for editing, or check if anything has unmanaged layers. 

There's some older threads where you can learn how the community has overcome this
https://github.com/microsoft/coe-starter-kit/issues/5685
https://github.com/microsoft/coe-starter-kit/issues/5371


Hope that helps,
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
