### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Audit Logs | Sync Audit Logs (V2) not working correctly with 401 error

### ISSUE THREAD

**Issue by jax-coe-admin** [microsoft/coe-starter-kit#6023]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are attempting to convert to the "Sync Audit Logs" flow within the Core solution from the deprecated "Audit Logs" solution.  When we run the "Admin | Audit Logs | Office 365 Management API Subscription" flow with START we get a 401 error instead of a 400.  When we attempt to run the new "Admin | Audit Logs | Sync Audit Logs (V2)" flow, we also get a 401 error.

Following the documentation [here](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http)

Since we are coming from previous solution, App registrations is already complete:
![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/cc439ed3-64af-4fc7-8831-70499674dd1b)

API permissions:
![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/0d220431-9aa5-4d2f-b1f2-bcf084f35b32)

Certificates & secrets
![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/d96a0ea0-489b-4035-b889-e253bcc679d3)

Environment Variables:
![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/c6de39de-026f-456e-9390-4afc7b91aeb9)

"Admin | Audit Logs | Office 365 Management API Subscription" results after being run with START:
![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/7a6ab7a9-faf0-48f1-9f78-4c853936e72f)

OUTPUTS Body:
{
  "error": {
    "code": "AF10001",
    "message": "The permission set () sent in the request does not include the expected permission."
  }
}

![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/f0239726-8bbe-4d0f-bd25-5e6d0f2447aa)

OUTPUTS Body:
{
  "operation": "START",
  "response": "{\"error\":{\"code\":\"AF10001\",\"message\":\"The permission set () sent in the request does not include the expected permission.\"}}",
  "statuscode": "401"
}

The flow completed with Success despite the error.

Assuming this was normal, tested the new "Admin | Audit Logs | Sync Audit Logs (V2)" and received a Failed status:
![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/3197de6d-ff53-4b8a-8fda-107de0341636)

![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/c21ae88b-56f0-443a-aba0-6cceba159faa)

![image](https://github.com/microsoft/coe-starter-kit/assets/126201040/548a7f0f-8cb2-4845-b0ae-f27176bae722)

### Expected Behavior

"Admin | Audit Logs | Office 365 Management API Subscription" should give 400 error and "Admin | Audit Logs | Sync Audit Logs (V2)" should complete sucessfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Enable and run new Sync Audit Log flows

### Anything else?

This the same registration information being used by the Custom Connector for the deprecated solution

**Comment by manuelap-msft** [comment]
I think you've missed updating the App registration, see:

### Update app registration
1.	Browse to your app registration. 
2.	API Permissions > Remove the delegated permissions to Office 365 Management APIs ActivityFeed.Read
 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5e788fcb-e251-454b-9510-4ccb17387074)

3.	Add instead Application permissions to Office 365 Management APIs ActivityFeed.Read and get it granted for the organization
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d49db08b-2963-4a44-9384-099e2a3ca23c)

Here are the detailed steps on how to move from using the custom connector to the new HTTP method for collecting audit logs:
https://github.com/microsoft/coe-starter-kit/issues/6009

**Comment by jax-coe-admin** [comment]
I overlooked the permission type on the registration and I'm working on getting the correct permission added.

I will update once I get this complete.

Thanks!

**Comment by jax-coe-admin** [comment]
This is all set.

I can confirm that I missed the change in API permission from Delegation to Application.

Once the correct API permission was added and consented, the "Admin | Audit Logs | Office 365 Management API Subscription" flow completed with the expected 400 response.

Thank you, Manuela!

**Comment by Jenefer-Monroe** [comment]
Wonderful news, thank you for letting us know!
