### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Quarantine Power Automate flows

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#6027]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In CoE, we have  option to quarantine canvas apps from  power platform admin view app 
we dont see similar option for power automate flows to quarantine flows
could you please let me know if there is any option to quarantine power automate flows.
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

quarantining is only supported for canvas apps today by the product itself, there's no option to quarantine flows. I believe this is on the backlog for the Power Automate team to address but you could ask or add your idea to the user community here https://powerusers.microsoft.com/

Thanks for using the CoE,
Manuela
