### ISSUE TITLE
[CoE Starter Kit - QUESTION] Get co owner details for an orphaned power Automate 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#6028]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

we are having around 1000 orphaned flows which are all in running state. 
we are thinking to retrive if there are any co owners for these flows and assign ownership to them. 
when we  open these flow details in Power Platform admin view app, we could not find any details of co owners. 

When I click on flow details and redirects to flow , I am seeing no access message.
**
![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/e54ab54e-259b-4913-b3a8-28403ec64c1c)
**

I could not see the flow details, it is saying you dont have access to the flow 
When I verify from Set Flow Permission If I open any  orphaned flow to see the details nothing is displaying but an error

![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/45e52959-1bdc-4671-aed1-fc5583177e41)

Could you please let me know how we can find the co owner details of orphaned flows in Power Platform .
How do we manage these kind of scenarios.
If we dont even have the orphaned resource manager details. 
If we dont get co owners details 
but flows are running in state and we can see flow last run details ?

How to assig ownership for these flows ?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. We do have tracking co-owners in the inventory on the backlog via https://github.com/microsoft/coe-starter-kit/issues/1083 and plan to address it with a broader look at orphans, but have not been able to fund yet. We are waiting for one more product update and then will be able to tackle that space. 

In the meantime you can look at this on a flow by flow basis using one of these two tools

### Set Flow Permissions app
This is a standalone canvas app that has a screen devoted to Oprhaned Flows as shown here. It shows the number of editors and last modified and allows for multi-select and delete 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3a33bb4b-a52f-4d66-bfaa-c86b570ba495)

### Power Platform Admin View
This app isnt yet as helpful for your scenario as we await the above referenced work item, but once that is done, this will be the better space for you to perform this work so including for reference as today you can one by one select a flow and see who is authorized to it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b254f742-6436-4b51-a140-235bf922a00f)

**Comment by pamatihyd** [comment]
Yes we tried to check from above two possible ways 

![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/ffc46d2e-76fb-4daf-bc2b-dee87da175ff)


![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/03c341c9-47f4-4692-8b4b-81a06f3c16e4)

This flow is having 3 users , actually verified from PowerShell, 

Why cant I see in COE

**Comment by pamatihyd** [comment]
Please find the attached screenshot , We have set up CoE using Data Export feature in this environment
![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/3e55e005-8633-4312-941f-5d0f1a8aea80)

**Comment by pamatihyd** [comment]
Could you please let me know if you have any idea how we can proceed

**Comment by Jenefer-Monroe** [comment]
Are you certain that this flow still exists? Do you have the **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** flow turned on and running?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
