### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs

### ISSUE THREAD

**Issue by erickovach** [microsoft/coe-starter-kit#6030]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We continue to receive emails regarding not all audit logs are collected.  I've adjusted the related variables multiple times.  Our current chunking size is 1 minute.

Your audit logs were collected but some were missed due to truncated results.
You will need to use a smaller interval to gather all logs.

### Expected Behavior

all audit logs are collected.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
