### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot make Default Solution managed due to Application Ribbon layer

### ISSUE THREAD

**Issue by liseraz** [microsoft/coe-starter-kit#6031]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

My customer wants to upgrade their existing CoE from 4.2 to 4.11. We have succeeded to remove all unmanaged layers except 1. In the Default Solution there is an Application Ribbon layer that we cannot remove. Since we cannot export and import the Default Solution either, we are a bit stuck. I have searched this forum and googled and did not find anyone with this same problem.
How can we remove this Application Ribbon so that the Default Solution can be Managed again?
Please see the attached screen shot.

Thank you in advance,
RAZ

### Expected Behavior

I thought we could just remove this layer and make the solution into a managed solution.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

Application Ribbons

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Go to Default Solution that is now an Unmanaged solution.
Click on it to see what dependencies are present
Was able to remove everything except Application Ribbons. When we click on the "Remove active customization" option is not available and we cannot remove it.

### Anything else?

<img width="910" alt="appribbon" src="https://github.com/microsoft/coe-starter-kit/assets/139161629/9dcd6ef5-e89f-4da7-aff8-46c5d4c0677a">

**Comment by Jenefer-Monroe** [comment]
That isnt part of the kit, its something thats in an environment without the kit being installed, so no need to worry about it.
Hope that helps

**Comment by liseraz** [comment]
Hi Jenefer,Thanks for your mail. But since the solution is in status Unmanaged we cannot run the upgrade. We get the message that "imported and existing solutions must be managed".All other solutions are managed.Thank you!Kind regards Lise 11 juli 2023 kl. 00:27 skrev Jenefer Monroe ***@***.***>:﻿
That isnt part of the kit, its something thats in an environment without the kit being installed, so no need to worry about it.
Hope that helps

**Comment by Jenefer-Monroe** [comment]
If you installed the kit as unmanaged, I dont think you can convert to managed. I doubt that is what happened though. 
Please go look at the solutions list int he environment. What is listed for the "Managed: Column? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3206a8f0-d53b-4698-bbf6-4c51ea42d3bd)

More likely you have hit this odd product issue. Sometimes customers have seen this error message when an app/flow in the CoE solution was open for editing or had unmanaged layers. You may have to check if you or anyone else has a flow/app that's part of the CoE kit open for editing, or check if anything has unmanaged layers. 

There's some older threads where you can learn how the community has overcome this
https://github.com/microsoft/coe-starter-kit/issues/5685
https://github.com/microsoft/coe-starter-kit/issues/5371


Hope that helps

**Comment by liseraz** [comment]
Hi!
Thank you for your tips. We ended up leaving all environment variables empty during the import, and also changed from our service account to a Global Admin account. Then we could import the Core solution.
You can close this case now.

Best,
/Lise


MVH/Best regards
Lise Rasmussen
0760-580659
***@***.***>
<https://gigz.se>



Den 11 juli 2023 04:54:22 +02:00, skrev Jenefer Monroe ***@***.***>:

**Comment by Jenefer-Monroe** [comment]
Glad you are unblocked and thanks for letting us know!
