### ISSUE TITLE
[CoE Starter Kit - BUG] Set Flow Permissions

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6032]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Is this notification still true below that the Make Owner only changes it here on this page and does not actually make them the owner? Then why have the button if that is true?

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/bb1d4324-92b3-4260-b157-46bcbbe56af2)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Center of Excellexne - Core Components

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We use a concept called derived owner, its not that it changes just for this page, its that it chagnes it just for the kit. So anywhere in the kit we ask about owners we will use the person you select here.

**Comment by mdphung** [comment]
So to be clear on the actual flow it self it will not update the owner only just displayed on the tools and apps within the CoE?

 [cid:0f7a1ae3-fc9e-4fe7-bf91-f5794592f8b6] [cid:df4d4865-b743-4eb8-82d8-119142bde5e0] <http://www.truetandem.com/>
Corporate Headquarters
[cid:2ba12e8e-59aa-4c7d-9926-f30f70b154aa]



Mai Phung
Sr. Project Manager

Email: ***@***.******@***.***>
Mobile: (571) 228-9123


“We are a trusted information technology solutions provider, committed to the success of our customers, communities and employees.”  www.truetandem.com<http://www.truetandem.com/>



________________________________

**Comment by Jenefer-Monroe** [comment]
Correct the flow itself is not updated. We do not have access to update the owner concept on the actual flows today, (other than on solution aware flows, a new feature we have not yet integrated with). 

So we added a new piece of metadata (a column in our flow inventory table) to store who you folks tell us is the actual owner, the "Derived Owner". And then we use it in the kit for owner. So its used when you check for orphan for example, we wont check the flow "creator" which is the owner concept in the product. Instead we check this "Derived Owner". 

By default we copy the "Creator" into "Derived Owner"

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
