### ISSUE TITLE
[CoE Starter Kit - BUG] Sync flow for Audit Logs failure

### ISSUE THREAD

**Issue by NicoleSSmith** [microsoft/coe-starter-kit#6033]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Have been receiving Sync flow for Audit Logs failure emails since updating the CoE Core Components with the 4.9 release in June.
If I view the failure this is the error I receive:
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/ed8608ce-e738-4d5c-ba0d-5586821190d8)
I have tried resubmitting the run, with no luck. 

### Expected Behavior

I updated the CoE core components with the newest release and the flow is still failing. I expected the timing of the flow to fail at the time the newest upgrade was imported, but the time the flow ran has continued to update at the time the June release was updated.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2.10

### What app or flow are you having the issue with?

Sync Flow for Audit Logs

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
It sounds like the child flow is off. 
Are you using the custom connector methodology for collecting audit logs? Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

If that does not resolve, then you likely ended up with a bad connection, perhaps due to the wrong identity provider being selected as in [issue 4808](https://github.com/microsoft/coe-starter-kit/issues/4808)

If that occurs please try the steps outlined in [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

**Comment by NicoleSSmith** [comment]
Issue 4808 ended up fixing the connection. The flow was still failing after the connection was fixed. I imported the most recent Audit Log asset to see if that would fix the issue. I can now see that the [Child] Admin| Sync Logs flow is now deprecated.

I used Collect audit logs using an HTTP action - Power Platform | Microsoft Learn<https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content> to start the subscription to audit log content. When I get to step 4, where the Admin| Audit Logs| Office 365 Management API Subscription  gets turned on, I get this error message:


[cid:8a1042ef-c333-4fc0-b95a-e9a2b3aff85d]

Please advise!

________________________________
From: Jenefer Monroe ***@***.***>
Sent: Monday, July 10, 2023 2:04 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Nicole Smith ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Sync flow for Audit Logs failure (Issue #6033)


It sounds like the child flow is off.
Are you using the custom connector methodology for collecting audit logs? Connections to custom connectors get broken on solution upgrade. Please see issue 1424<https://github.com/microsoft/coe-starter-kit/issues/1424> for how to resolve

If that does not resolve, then you likely ended up with a bad connection, perhaps due to the wrong identity provider being selected as in issue 4808<https://github.com/microsoft/coe-starter-kit/issues/4808>

If that occurs please try the steps outlined in issue 4961<https://github.com/microsoft/coe-starter-kit/issues/4961>

**Comment by Jenefer-Monroe** [comment]
Pictures do not come through if you respond in email so you will need to log in to GitHub to share. However there is a change needed to the app registration to switch from cc to http. Please follow the steps outlined here: https://github.com/microsoft/coe-starter-kit/issues/6009

**Comment by NicoleSSmith** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/02a5f45c-ca47-4365-9129-2812d97b279e)
Apologies! This is the error message I am getting.

**Comment by Jenefer-Monroe** [comment]
No problem. ok yes there is a step in that link I sent called "update env vars" and thats what htis is complaining about. 
So walk through that document and then you should be golden.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
