### ISSUE TITLE
[CoE Starter Kit - BUG] Test Pass: Conditions in Admin | Sync Template v3 (PVA) are based on labels instead of name

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6035]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Raised via CAT SA Olivier: 

Some of the conditions in flows (ex: Admin | Sync Template v3 (PVA)) are based on labels instead of name which results in errors when the base language of the environment is not English.

### Expected Behavior

Conditions are based on names that are unique and not localized.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

latest

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I presume this is about this bug: https://github.com/microsoft/coe-starter-kit/issues/6000
Did a pass and cant recall why we used labels. Confirmed using this work for Japanese, French and English.
if(equals(body('Parse_Bot_JSON')?['componentstate'], 2), true, false)

Will hold this bug as a quick general pass to see if there are other spots.

**Comment by manuelap-msft** [comment]
AI Builder Models column aistate seems to be another place where we use a localized label. Can we explore if we can find a non-localized value?

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/732da44d-8d0e-4ada-be9d-4224770a4ef7)

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/09e2f312-efb7-4e4d-a68f-facde58742f3)

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/46638daf-2214-4615-8745-ec98c6d3e6b3)

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/92c58293-c818-4373-8279-4a4c471721fd)

**Comment by GithMen** [comment]
Hi,
the case seem not to be completely resolved because i have the release of 5 Mars 2024  installed and i still have this issue occur in the update Bit action in Admin | Sync Template v3 (PVA).
The flow failed  with error "The length of substring can't be longer than '6' which is the length of the source string." on the Dataverse action "Update Bot".
Any help will be appreciated.
