### ISSUE TITLE
DLP V2 Editor - Order the connectors by name alphabetically on the Assign connector page

### ISSUE THREAD

**Issue by marcster** [microsoft/coe-starter-kit#604]
**Is your feature request related to a problem? Please describe.**
When comparing the DLP policy in the DLP Editor canvas app and the Power Platform Admin portal, it is difficult to match the connectors as they are not ordered by name in the canvas app

**Describe the solution you'd like**
When looking for connectors to add to the various groups within the DLP Editor V2 app. it would be good if the connectors are ordered by name alphabetically as it provides parity with the DLP creator option in the Power Admin Portal. It also makes it easier to ensure you are comparing like for like.

**Describe alternatives you've considered**
I have done this by adding an order by on the Name column on the gallery items.

**Additional context**
N/A

**Comment by manuelap-msft** [comment]
Thanks for the great feedback! I have just added this as well and it will be released with our next version.
