### ISSUE TITLE
[CoE Starter Kit - BUG] Set App Permissions - When you go from one owner to another on a app it to quickly it seems to get an issue

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6041]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

So by selecting an app and setting permissions to an app by selecting another user to an owner and then going back and setting the owner to another person and then selecting a user from viewer permissions to editor permissions, we get this error. I am wondering if you are to fast in your change does this cause this problem?

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/6ad9a517-514a-4ee6-83cd-ddbd92af28cd)

### Expected Behavior

I would think you can change permissions around if you make a mistake but after keep changing permissions on an app it tends to error out.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

set app permissions app

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Select an app that has an owner then select someone else as the owner and click save.
then on the same app add someone as a viewer then save then select viewer and change their permission to editor.
Then this error appears.

**Comment by Jenefer-Monroe** [comment]
I dont repro this so there may be some other issue at play with the user you select, or a timing issue as you suggest. 

If you are able to find a simpler repro we are happy to take a look but this app is pretty highly used and solid for folks so I would be hesitant to play around with the timing in it. 

Also please do note that although the underlying features and components used to build the Center of Excellence (CoE) Starter Kit (such as Microsoft Dataverse, admin APIs, and connectors) are fully supported, the kit itself represents sample implementations of these features.

**Comment by Alyson95170** [comment]
I am having a similar issue, when setting an owner I get error "office365users.usersprofilev2 failed: the method had an invalid value for parameter id" when I cancel and refresh the new owner is showing in the app permissions

**Comment by mdphung** [comment]
No problem. Working on a new repro to make sure.

 [cid:4f525d0a-7d3c-42ba-a12f-ea96f5223769] [cid:2eb0b4e0-1f57-4b01-8064-a730edeb024b] <http://www.truetandem.com/>
Corporate Headquarters
[cid:441a6a3b-dd6a-4e68-b755-3f5c3f1dc4e7]



Mai Phung
Sr. Project Manager

Email: ***@***.******@***.***>
Mobile: (571) 228-9123


“We are a trusted information technology solutions provider, committed to the success of our customers, communities and employees.”  www.truetandem.com<http://www.truetandem.com/>



________________________________

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
