### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Upgrade Wizard - Error in button "Refresh dataflow for initial inventory"

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#6042]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
i am upgrading to July 2023 version (Data Export) and in the step 7 of the wizard "Configure dataflows (Data Export)" when I press the button "Refresh dataflow for initial inventory" I have this error:

PowerQueryDataflows.RefreshDataflow failed: %7B%0D%0A%20%20%22Message%22:%20%22The%20refresh%20request%20is%20invalid%20%27https:/europe-002.azure-apim.net/apim/dataflows/7b8a682992e744c28d9d930df02653b7/api/groups/38dfed98-1fd5-e667-ba1b-3238ef4a755a/dataflows/95bbc0db-d3ee-45a5-b0cf-7be08889e9e8/refreshdataflow?workspaceType=2chars

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/c3b57584-d114-4c4b-bbbe-901adca5d5f5)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

Upgrade wizard

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Can you please 

1. Go see if all these env vars have a value 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1ab0a206-5379-435c-a3b3-aa1e0af5cf6d)

2. Go manually refresh the Maker flow
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/af92abca-c2e1-4278-abaa-63e55c90cea9)

3. And then wait to see if the On Complete Flows pass and the rest of the rest of the dataflows pass. This will help me know where the error is

**Comment by albertocastro365** [comment]
More 20 minutes after to refresh the makers dataflow the rest don't start automatically:

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/6c615d23-0b0d-4b74-b6d7-a97f4f5e3403)

**Comment by albertocastro365** [comment]
More info:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/40bf2ef1-0284-4249-9b32-5f3018f1075c)

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/4067b503-c504-4a19-83aa-d9aa6b9c95a0)

**Comment by albertocastro365** [comment]
Hi @Jenefer-Monroe 
I am investigating and and the flows to sync the dataflows fail with this error:

Message	:	The trigger is invalid 'https://flow-apim-europe-002-westeurope-01.azure-apim.net/apim/dataflows/7b8a682992e744c28d9d930df02653b7/api/groups/38dfed98-1fd5-e667-ba1b-3238ef4a755a/dataflows/75fcf83d-e2fa-4059-8c84-0dc8a9cc3996/onrefreshcomplete?workspaceType=Environment'
Reason	:	'InvalidTrigger' - GroupType 'Environment'
WorkspaceType	:	Environment
OperationId	:	OnRefreshComplete
ClientRequestId	:	750fc53d-740b-4f1c-a5b0-4b9cf9a333be
ClientRequestUrl	:	https://flow-apim-europe-002-westeurope-01.azure-apim.net/apim/dataflows/7b8a682992e744c28d9d930df02653b7/api/groups/38dfed98-1fd5-e667-ba1b-3238ef4a755a/dataflows/75fcf83d-e2fa-4059-8c84-0dc8a9cc3996/onrefreshcomplete?workspaceType=Environment

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/52d0aae6-fbab-4ca1-a67a-e687bda62162)

**Comment by Jenefer-Monroe** [comment]
Thank you. I was suspicious this was the issue, not good news. 
Can you please do the following? 

Open the trigger, note what you see here, and let me know what the postfix is (ex -westus)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2910f6c9-8683-4159-b47d-ea871b36aef5)

Create a new flow with this same trigger type but this time select the envt manually and enter the dataflow guid
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/780c682d-2631-4cf8-ba4e-884049bc81e5)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/072dc970-d632-44cb-afae-109ddf9e5925)

Refresh the maker flow and see if this new flow works, and if so, what is its envt postfix?

**Comment by albertocastro365** [comment]
Hi,
I have two scenarios:
A. an environment with CoE Starter Kit (Sync flows)
B. an environment with CoE Starter Kit (BYODL)

I am trying to upgrade the scenario A from sync flows to Data export. In this environment I have this issue.

I updated the scenario B  with the new CoE version and I don't have this issue: the dataflows runs ok helped by the "CoE BYODL - ..." flows.

In scenario A the cloud flow "CoE BYODL - When Maker dataflow refresh is complete" never has been executed automatically:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/d82628cd-68c1-4352-8ccf-7ae2e0a082e9)


In scenario B, this is a trigger execution of the flow "CoE BYODL - When Maker dataflow refresh is complete":
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/33acbc2d-9be9-4c85-924e-d51d2d111e13)

**Comment by albertocastro365** [comment]
In scenario A I made a cloud flow that you proposed:

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/34eee268-4326-4283-837b-b08d5e348f23)

**Comment by albertocastro365** [comment]
New test:
I changed this flow removing the environment variables and put on directly the environment and the dataflow makers ID:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/84e2cd8d-38e8-497d-ba66-c7355dd95d81)

In this case, after to refresh makers dataflow id this cloud flow triggered OK but fails in the second step:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/bae3ac7c-d934-4c51-ad45-31fba8bef8c6)

    "statusCode": 400,
    "headers": {
        "Date": "Mon, 17 Jul 2023 11:05:51 GMT",
        "Content-Length": "765",
        "Content-Type": "application/json"
    },
    "body": {
        "Message": "The refresh request is invalid 'https://flow-apim-europe-002-westeurope-01.azure-apim.net/apim/dataflows/7b8a6829XXXd930df02653b7/api/groups/38dfXXXe667-ba1b-3238ef4a755a/dataflows/ca68c84XXX472a486a548/refreshdataflow?workspaceType=Environment'",
        "Reason": "'InvalidRefreshRequest' - GroupType 'Environment'",
        "WorkspaceType": "Environment",
        "OperationId": "RefreshDataflow",
        "ClientRequestId": "f3171630-de30-4dae-a268-14a3483fa4af",
        "ClientRequestUrl": "https://flow-apim-europe-002-westeurope-01.azure-apim.net/apim/dataflows/7b8a68299XXX0df02653b7/api/groups/38dfed9XXX7-ba1b-3238ef4a755a/dataflows/ca68c84e-3367-49ecXXX2a486a548/refreshdataflow?workspaceType=Environment"
    }
}

**Comment by manuelap-msft** [comment]
Hello,

unfortunately the way the Dataflow trigger works is that it doesn't just need the Environment ID (under Group) but the Environment ID plus a Dataflow specific suffix. 

Using the Setup Wizard, we update environment variables for these values and we're taking a guess at the suffix based on the location of your tenant (e.g. -unitedstates, -europe) but it looks like in your case that didn't work. We do have a workaround for this but haven't done a write up on it yet as no one has hit this problem yet. Please find the steps below, and we'll include them in our documentation as well:

We do have a workaround for this in place:
- Navigate to the **Default solution**
- Find the CurrentEnvironment environment variable and delete the current value of it
  ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/8d55a047-e2d0-430d-82d0-ecd9309d3b2a)
- Then navigate to the **Core components solution**
- Find the **DebugBYODL>ConfigureEnvironment** flow and turn it on
- Edit the flow
- Edit the "When a dataflow refresh completes" trigger at the top and select your CoE environment from the Group parameter dropdown. Make sure to select it from the dropdown and do not paste in an ID. Then select the CoE BYODL Maker dataflow from the drop down for the Dataflow parameter
   ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/06b8a5de-2a36-4817-8f02-65717d3c8df3)
- Save and Test the flow by running it manually
- Check that it goes to this step in the condition where it updates the Environment variable with a value
   ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/a2de665d-1251-45ca-894a-cac1b42067e1)
- The value you see here should be your environment GUID plus a suffix

If you have made changes to the CoE BYODL>When .... flows in the kit, remove the unmanaged layers to return them to their managed state where they use the environment variables and try them again. You can trigger the CoE BYODL Maker dataflow refresh manually and that should kick off the cloud flow.

Let me know how you get on,
Manuela

**Comment by albertocastro365** [comment]
Hi @manuelap-msft,
after apply this workaround the CoE BYODL>When .... flows runs OK and all dataflows are refreshing correctly. Thanks.

Some questions:
- I must remove the unmanaged layer and turn off the cloud flow DebugBYODL>ConfigureEnvironment , do I?
- Is there an explanation of this behavior?
In my scenario B: upgrading a Data Export Coe to July version I don't have this issue.
In fact the current environment variable is this:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/b91136ce-013a-4a65-9e0b-c009e4864045)

In my scenario A: upgrading a Sync Flows CoE to July version with Data Export I had this issue and after your workaround the current environment variable is this:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/f7f0b0af-5872-4714-a985-0361ba3ec4ba)

**Comment by manuelap-msft** [comment]
Wonderful thanks for confirming!

1. You won't need the DebugBYODL>ConfigureEnvironment again, so you can turn it off. There's no need to remove the unmanaged layer, but you can do it. 
2. Are both of your environments in the same region? Are both of the environments of type Production, or is one of them a Sandbox/Developer/other environment type? I'm not quite sure what caused this behaviour. The Dataflow trigger expects the environment with this suffix. There's no Dataflow-specific lookup table for the suffix and no one could really tell us the exact value. During our development and testing we found that if we looked at the location property of the workflow() action in a flow, that seemed to always match the suffix expected by the Dataflow trigger so we implemented this as part of the Setup Wizard. The SetupWizard>UpdateDataflowEnvironment uses this logic and updates this as part of the wizard. We tested this with US, Canada, France, UK, Europe environments and it always seemed to work. It looks like in your case this "guess" was incorrect. We did expect that it wouldn't always work which is why we added that DebugBYODL flow in to manually force the environment variable to have the correct value with the suffix.

**Comment by albertocastro365** [comment]
Both environments are configured equal.

Environment scenario A with issue: CoE Sync Flows converts into Data Export
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/e5f4f0f1-b14c-4d99-8aad-324fc1bdc89a)

Environment scenario B: CoE Data Export
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/45b2348b-bd50-4d2e-ac26-c57952562f60)


OK, not worries.
I go to check our test environment and when the check list has been passed I will upgrade the production environment.

We can close this issue with this workaround. When I will upgrade prod env, if I have the same issue (or not) I post it here to document it.

Thank you so mucho!
