### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (PVA) issue - flow fails due to length of input field

### ISSUE THREAD

**Issue by FredericTaes** [microsoft/coe-starter-kit#6044]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We're getting errors with the PVA Sync Flow. The error message we're getting is the following:

![image](https://github.com/microsoft/coe-starter-kit/assets/139330603/faa27a48-6801-4c83-a308-c94acfa01d52)

However, if looking into the flow, the actual error is something different. It seems one of the parameters (that is automatically generated) for the step "Create Bot" is longer than expected.

![image](https://github.com/microsoft/coe-starter-kit/assets/139330603/b18f0009-02b1-490d-8244-c761949a33be)

It seems the column doesn't expect values like the one we're having in some of our environments (I suppose it's a newer value):

![image](https://github.com/microsoft/coe-starter-kit/assets/139330603/c277e95b-7740-484a-aa3e-b64744b1af2b)

I suppose modifying the length of the column 'admin_bottemplate' of the 'admin_pva' table will fix this:

![image](https://github.com/microsoft/coe-starter-kit/assets/139330603/04b31c25-de39-4fad-8ed6-7938b1e9835d)

### Expected Behavior

A flow that works fine with all PVA environments

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin - Sync Template v3 (PVA)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Run the standard sync flows.
2. Have an environment in which a PVA bot is running (I suppose of a newer or specific type).

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting, we fixed this in July with https://github.com/microsoft/coe-starter-kit/issues/5808
I'll go ahead and close as a dupe, but please do let us know if you need further assistance.
