### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor>Parse impacted resources into CSV fails when one of the arrays is empty

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#6047]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

If the list of flows or apps is empty then the flow fails with 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e6f0f1fe-b50d-4c5b-8668-d14c44390588)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

DLP Editor>Parse impacted resources into CSV

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
local fixed for August

**Comment by morismm99** [comment]
I am getting the following error when clicking on the Export impacted apps and flows to CSV on the DLP Editor V2 app - not sure if the August fix will also address this issue:

![image](https://github.com/microsoft/coe-starter-kit/assets/72099434/0b81d46c-c759-4f49-9379-9b01ae8d17bc)
