### ISSUE TITLE
[CoE Starter Kit - BUG] Request Orphaned Objects Reassigned (Child) fails

### ISSUE THREAD

**Issue by nrd2015** [microsoft/coe-starter-kit#6048]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The "Request Orphaned Objects Reassigned (Child)" flow fails when the maker and manager accounts are no longer active. 

Error  - 
The request failed. Error code: 'GraphUserDetailNotFound'. Error Message: 'No user details with email or UPN 'xxxxx' were found in Graph.'.

Can this check be included in the flow.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.6

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, this version of the audit log collection system is deprecated and will be removed from the kit in August 2023. 
As a result, we will not be investing in changes here. 

Here are your options to move forward
1. Convert to the new system. See [How to convert audit logs from custom connector to http format](https://github.com/microsoft/coe-starter-kit/issues/6009)
2. Keep a local copy of this solution and keep using CC, you can also make your desired changes at that time. See [How to maintain custom connector methodology to gather audit logs](https://github.com/microsoft/coe-starter-kit/issues/6017)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
