### ISSUE TITLE
[ALM Accelerator - BUG]: New Solution Branch not being recreated during Export pipeline

### ISSUE THREAD

**Issue by BJHF-power** [microsoft/coe-starter-kit#6049]
### Describe the issue

After promotion to master branch, we delete the Solution branch. The Export pipeline then recreates the Solution branch during the next deployment run. 

However, after July release, the Solution branch is not getting re-created by the Export pipeline like it used to. 

We've found the issue in brach-pipeline-policy.ps1 on lines 261/262:

changing line 262 to `$getExistingYmlContentFileURL = "$orgUrl$solutionProjectName/_apis/git/repositories/$solutionRepositoryName/items?path=$ymlContentFilePath&api-version=6.0&versionDescriptor.versionType=branch&**versionDescriptor.version=$sourceBranch**"` results in the Solution branch successfully getting re-created during Export pipeline.

### Expected Behavior

A solution branch is successfully created when missing during Export pipeline run

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

July

### Steps To Reproduce

Deploy all the way to master
Delete the solution branch
Run Export pipeline again with a new Solution version into the same repository

**Comment by mikefactorial** [comment]
@RajeevPentyala this is the issue we discussed a few days ago regarding deleted solution branches.
