### ISSUE TITLE
[ALM Accelerator - BUG]: Security Role assignment fails when GroupTeam name doesn't match AAD Group display name

### ISSUE THREAD

**Issue by BJHF-power** [microsoft/coe-starter-kit#6050]
### Describe the issue

Not really a bug, as it's working as intended, but something to consider:

Scenario: There are 2 Azure AD groups with the same display name (e.g., "Contoso App Users") but different Azure Object IDs (e.g., 0000-0000-0000 and 9999-9999-9999). However, in Power Platform, there cannot be 2 GroupTeams with the same display name under the same BU. So the corresponding GroupTeam for these AAD groups in the Power Platform environment is "Contoso App Users" and "Contoso App Users - 2". Now, someone is deploying their solution and wants to assign a Security role to Contoso App Users (9999-9999-9999). 

in dataverse-aad-group-teams-functions.ps1, there is logic that evaluates whether the AAD group that should be assigned a Security Role already exists as a GroupTeam in the target environment. This is done by querying the Teams table for a record with a matching Azure Object ID (line 74), and then determining if the returned GroupTeam name matches the AAD Group display name (lines 88-93):
`if ($existingTeamName -ne $aadGroupTeamName) {
                    Write-Host "Existing team - $existingTeamName not matching with  aadGroupTeamName - $aadGroupTeamName. Cancelling Security Role refresh"
                    $applySecurityRoleRefresh = $false
                }else{
                    Write-Host "Existing team - $existingTeamName matching with  aadGroupTeamName - $aadGroupTeamName. Proceeding with Security Role refresh"
                }`
                
If the GroupTeam name and AAD Group name don't match, and in this case, the AAD name is "Contoso App Users" and the GroupTeam is "Contoso App Users - 2" , the Security Role assignment is skipped. However, this validation seems unnecessary as the display names are not important - what matters is that the Security Role is assigned to the expected AAD group (9999-9999-9999) as configured in User Deployment Settings. The display name is irrelevant to the security role being assigned to the members of the group as expected.

### Expected Behavior

Remove the validation of the display name, and instead use only the Azure Object ID GUID to determine if a GroupTeam already exists in the target environment.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

July

### Steps To Reproduce

Have 2 AAD groups with the same name
Create GroupTeams for both under the same BU in the target environment (one will need a different display name)
Try to assign a security role to the ID with the different GroupTeam using the dataverse-aad-group-teams-functions.ps1 logic

**Comment by mikefactorial** [comment]
Thanks @BJHF-power for making us aware of this. @RajeevPentyala let's take a look at this. Have some thoughts on how we might better handle this scenario.

**Comment by BJHF-power** [comment]
@mikefactorial we did find that there _is_ a valid scenario in which two GroupTeams with the same Azure Object ID can exist with the same environment, as long as the membership types are different. If anything, AAD ID + Membership type might be a better validation than AAD ID + Display Name, but for our purposes we've modified the code to always select the GroupTeam with matching AAD Object ID and membership type = Members and Guests (since that's what all pipeline-created GroupTeams should be, and we don't want people creating GroupTeams manually directly in Production)

**Comment by mikefactorial** [comment]
Thanks @BJHF-power @RajeevPentyala and I discussed this, this morning, and agreed to make the same change. We don't currently specify member type when creating group teams in the pipelines so Members and Guests is the default. @RajeevPentyala I would agree that we should include member type = Members and Guests to be sure that we are only updating teams that were created or could have been created via the accelerator pipelines and not potentially update some other group that was created manually.
