### ISSUE TITLE
[CoE Starter Kit - QUESTION] What does Cross Tenant connection reference mean and how to enable it?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6053]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are looking to enable "Tenant isolation" and want to check if there are any apps or flows that use it . We can see an option on COE kit for "Cross Tenant connection reference" and on there there is no data :)

We want to ensure we are getting data under "Cross Tenant connection reference" on COE , how can we check this pelase?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Here is where you can find information about cross tenant restrictions. How to set / how to use / etc
https://learn.microsoft.com/en-us/power-platform/admin/cross-tenant-restrictions

The only thing we do in the kit with these is report on the connections for them. So you can go see what cross tenant connections exist.

It's collected by the **_Admin | Sync Template v3 (Connection Identities)_** flow

And can be viewed in the Governance dashboard
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e72e9599-342c-462e-b9e7-e57a828b0f97)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c852e5c3-04a7-4931-8227-2e89c0600ada)

**Comment by ryanwalker726** [comment]
We recently considered enabling Tenant Isolation, thinking that there wasn't any legitimate use for exfiltrating data to external domains, but didn't realize that it was something that was reported in the CoE Toolkit.  Thanks for pointing this out.

I was **_shocked_** by the number of connections that it showed on the Governance Dashboard.  Looking through the Production Dashboard, I noticed the corresponding 'Tenant Connections' page that I hadn't seen or paid attention to in the past, but I don't see a way to correlate these connections back to specific apps/flows.  

Couple of tangential questions:
1. Is there a way to work backwards from the connection to the assets where they are used?
2. Is there a way to do a clean-sweep (removal) of all connections to a specific domain?

**Comment by Jenefer-Monroe** [comment]
Unfortunately we do not have a way to connect apps/flows with individual connections. That isnt exposed to us programmatically.
However they likely fall into a number of connections (twitter / onedrive / etc) and so you can look at the flows that use those connections in the report.

We cannot offer a safe way to programmatically remove connections unfortunately, but there is a powershell command for collecting and deleting connections that you could use. We cant make it for people as its just too dangerous and all the connections kind of behave a litte differently. 

I hope this is a start at helpful at least!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by jchwila** [comment]
Could you please clarify on the interpretation of 'Cross Tenant Identity' value = True in Connection Identity table? Does it mean that connection is targeting external tenant or that it potentially MAY be used for hitting external tenant.
In the PBI report I can see thousands of values 'Cross Tenant Identity' = True for connection identities. However most of them flagged with True are legit and are connected to home tenant.

**Comment by chaitanyadev777** [comment]
I've noticed that we have over 500 connections under the category of cross-tenant isolation. Upon examining the list, I've come across the Excel business connector. Could you please advise me on how to determine which other tenants this Excel business connector is communicating with? Additionally, I'd like to know how to identify the other tenants that our platform is engaged with.
