### ISSUE TITLE
[CoE Starter Kit - QUESTION] For the Audit logs update, can we use the Azure HTTP action instead of the HTTP connector?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6055]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

For the Audit logs update, can we use the Azure HTTP action instead of the HTTP connector?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I played with this a bit and it appears that you cannot do this. If someone else knows how to do that please do let us know.
Even if we could figure out how, we would also need to content with having multiple endpoints in multiple HTTP with Azure AD connections. 
We've played with this in the past and we could not figure out how to ensure the connection references hooked up to the correct connection (with the correct endpoint). 
Welcome any feedback from the community here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
