### ISSUE TITLE
[CoE Starter Kit - QUESTION] Best practices for updating the CoE kit monthly

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6057]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When updating CoE starter kit each month are there any requirements or best practice regarding running flows (and not interfering with them) - particularly as the sync audit logs now runs every hour

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We dont have anything like this. From my quick testing, upgrade does not seem to impact the flows ability to run other than for a very brief moment in time. 

So I guess you could manually run the audit logs after upgrade to be sure you dont miss anything. 

Will hold open to see if the community has ideas here too.
