### ISSUE TITLE
[CoE Starter Kit - QUESTION] See Power BI report usage

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6059]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way to see usage of Power BI reports in the COE dashboard. We are trying to see if we need all of the licenses we have purchased

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Power BI is not currently part of the reporting and inventory in the CoE kit.

**Comment by lukas-nC** [comment]
Maybe this helps

[https://github.com/RuiRomano/pbimonitor](PBIMonitor)

**Comment by manuelap-msft** [comment]
Closing out as no further action required from the CoE kit team. There are currently no plans to cover Power BI admin and governance as part of the CoE kit.
