### ISSUE TITLE
[CoE Starter Kit - QUESTION] Connections randomly stop working

### ISSUE THREAD

**Issue by jaehwanahn** [microsoft/coe-starter-kit#6060]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

This is the second time I observed that some connections were broken.
![image](https://github.com/microsoft/coe-starter-kit/assets/22118813/2af33fe3-732c-4a12-8a5c-1885782bac59)

We just noticed the admin account became the owner of bunch of cloud flows. I am aware there was a bug which got fixed in June version, which we are currently on. (https://github.com/microsoft/coe-starter-kit/issues/6038)

Since the bug should not be in our CoE installation, I suspect having some connections broken may be the cause of the behavior.

Can you guide me what can be done to keep connections operational?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I'm afraid I don't have good advice here, I've not seen connections break like this regularly. Sometimes connections time out and break, and sometimes the connection itself changes and so they break (for example if you upgraded a custom connector, its connections will break). I just dont know how you got into that state so I'm not sure.

**Comment by jaehwanahn** [comment]
That's unfortunate....I guess the best bet is to connect with Microsoft Support on this.
