### ISSUE TITLE
Log Analytics Template - Workspace and Report Names not displayed

### ISSUE THREAD

**Issue by Jaik2022** [microsoft/coe-starter-kit#6064]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Log Analytics Template - Workspace and Report Names not displayed

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.0

### What app or flow are you having the issue with?

Log Analytics Template - Power BI

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Power BI 

### Anything else?

NA

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot? Note that you need to be logged in to GitHub to share pictures, responding in email will not share them.

**Comment by Jaik2022** [comment]
<img width="502" alt="Log" src="https://github.com/microsoft/coe-starter-kit/assets/114470163/955fc960-df3a-48ae-b66a-f3116e1ce8ce">
Please check

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
