### ISSUE TITLE
[CoE Starter Kit - BUG] Power Apps inventory difference in BYODL and Cloud Flows architechture

### ISSUE THREAD

**Issue by bhavikj65** [microsoft/coe-starter-kit#6065]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We identified an issue with number of apps being inventoried by cloud flows is way less than what is reported by BYODL.

Example below you could see BYODL report shows 424 apps created in June 2023, however Cloud Flows could only inventory 141 apps:

BYODL:
![image](https://github.com/microsoft/coe-starter-kit/assets/105588534/48082a38-a899-447e-b442-3f52702fc96a)

Cloud Flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/105588534/74f5c783-05be-4849-aaca-ef41e8616d68)

To further narrow down, I did a comparison using PPAdmin app and we found an app that was created on June 9th was not inventoried by cloud flows, initially I assumed that it could be that the app was deleted and hence it was skipped by cloud flows, however the app exists and still it was not inventoried. 

There is no way apart from running a full inventory to fix these kind of scenarios. Not sure if this is limited to Power Apps or its also happening with Power Automate resources. When full inventory is done the cloud flows are running for probably 2 weeks and we start seeing messages that the flow is making lot of requests and it may get suspended even if it has per flow license. 

Kindly suggest a solution to these issues as it impacts our governance processes. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Apps)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The need to run full inventory to get missing apps/flows has been removed in recent versions of the kit. May was the first relesae with that, which I see you are on, but it took a little bit to get the kinks out. I suggest you upgrade to July release and see if they appear on the next run of the kit.

**Comment by manuelap-msft** [comment]
Hello,

can you check if in the Power Platform Admin View you see the correct number of apps when inventoried via sync flows? I'm just checking the dashboard and am wondering if it's an error in the dashboard (incorrect filter) vs an error in the inventory itself. 

Thank you
Manuela

**Comment by bhavikj65** [comment]
I cross checked in PPAdmin view app and the numbers shown in PBI report
matches there as well.

**Comment by Jenefer-Monroe** [comment]
Can you please clarify, is the **_total number of apps_** wrong in PBI? How about in PPAdmin View? 

Or is it just the creation trend that is wrong?

**Comment by bhavikj65** [comment]
It's isn't the creation trend that's wrong, I have compared with PPAdmin
app and it shows same numbers.

**Comment by Jenefer-Monroe** [comment]
sorry not trying to be obtuse just making sure we are on the same page.

The **_total number of apps_** is wrong in PBI.  Is that correct? Can you share a screenshot showing that?
The  **_total number of apps_** is also wrong in our PPAdmin View model driven app.  Is that correct? Can you share a screenshot showing that?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
