### ISSUE TITLE
[CoE Starter Kit - QUESTION] Do we have a COE kit for Cina 21v tenant?

### ISSUE THREAD

**Issue by jayakumarkgds** [microsoft/coe-starter-kit#6069]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

DO we have any COE Kit solution available for china 21v Tenant power platform?same kit support 21v as well?or any version dependencies?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately we are a very small team and so cannot test different clouds, but the same kit is used across clouds (ex commercial, GCC, DOD, etc). So you would just need to give it a try and see if it works in that cloud.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
