### ISSUE TITLE
[AA4AM] Export Solution to Git error

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/coe-starter-kit#607]
**Describe the bug**
I am trying to push the changes to git and it throws the below error message. 

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/59940632/121556490-eca51b00-c9e1-11eb-950c-55b0c491918b.png)

Also when my team mate launch the app he get below error message where i do not get the error message. 

CustomAzureDevOps.GetPullReqeust failed: {"$id":"1","innerException":null,"message":"TF401180: The requested pull request was not found.","typeName":"Microsoft.TeamFoundation.Git.Server.GitPullRequestNotFoundException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitPullRequestNotFoundException","errorCode":0,"eventId":3000}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mikefactorial** [comment]
@aakashpatel660 can you verify that the ServiceConnection variable on the pipeline matches the name of the service connection configured in the project settings e.g. 
![image](https://user-images.githubusercontent.com/42348035/121557181-88cf2200-c9e2-11eb-8bed-a259ec61f6a1.png)
![image](https://user-images.githubusercontent.com/42348035/121557323-a8fee100-c9e2-11eb-8e19-f278090ce45e.png)

**Comment by mikefactorial** [comment]
For the Git error I may need to open a separate issue as this is likely a bug related to something being stored in the user settings or defaulting incorrectly.

**Comment by aakashpatel660** [comment]
@mikefactorial  but the pipeline which is throwing the error message is export-solution-to-git and there is no service connection variable we have to set up. Because it is taking the solution and storing it into source control.

**Comment by mikefactorial** [comment]
Can you try running the App User Setting Management App and delete the record associated with the user that's having the error to see if that clears out the problem? If the problem persists then I'd lean toward it being an issue with some default value.
![image](https://user-images.githubusercontent.com/42348035/121558184-6f7aa580-c9e3-11eb-88cf-337907e0d0db.png)
![image](https://user-images.githubusercontent.com/42348035/121558369-a18c0780-c9e3-11eb-94d9-16cbe0f89a27.png)

**Comment by mikefactorial** [comment]
Ah got it. The issue may be that your pipelines are out of sync with the App version that's running. We updated the name of the variables that are being passed to the pipelines in a recent release and as such the app needs to be on the same version. It's possible that if you have unmanaged changes (e.g. from when we were in preview and had to update the flow for the canvas app) that importing the solution won't overwrite with the latest changes. You may need to use the classic import experience and set the flag to "Overwrite Customizations" or delete the existing solution and reimport.

**Comment by aakashpatel660** [comment]
@mikefactorial my sync pipeline repo did get failed not sure that can cause the issue?

![image](https://user-images.githubusercontent.com/59940632/121559188-5e7e6400-c9e4-11eb-9e7c-94aa318b87ec.png)

**Comment by mikefactorial** [comment]
@jenschristianschroder any thoughts on the above error in the sync pipeline? @aakashpatel660 in the meantime are you able to update your pipeline repo with the latest YAML from https://github.com/microsoft/coe-alm-accelerator-templates and import the latest version of the solution from releases? 

That should resolve the ServiceConnection error on export https://github.com/microsoft/coe-starter-kit/releases/download/AA4AM-1.0.20210521.1/ALMAcceleratorForAdvancedMakers_1.0.20210521.1_managed.zip

**Comment by mikefactorial** [comment]
@aakashpatel660 going to move this over to discussions. I've added a new issue #608 for better error handling associated with the error you mentioned in the app that was fixed by deleting the user's settings. Feel free to respond to the discussion with any other questions you have
