### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Quick Report button missing on several tables

### ISSUE THREAD

**Issue by Sani1991** [microsoft/coe-starter-kit#6072]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Dear coe-starter-kit Team

We noticed that for some tables (at least the ones that are listed below) the Power Bi "Visualize this View" button in the Model Driven App view is missing. For other tables the button appears. It seems like the ribbons have been customized for each table individually using Ribbon Workbench.

Missing "Visualize this view" button on tables:
- Power Apps Apps
- Flows
- Environments

"Visualize this view" button appear on:
- Makers
- PowerApps Users

![image](https://github.com/microsoft/coe-starter-kit/assets/90025284/4262aaac-68db-4a5d-aebe-e5c5c66694b5)

We made sure to turn on the "Enable Power BI quick report visualization on a table" setting within the MDA:

![image](https://github.com/microsoft/coe-starter-kit/assets/90025284/06c988b6-610d-4d0f-b859-77ab15890387)

We would like to make use of this feature. Could you unhide the button on all tables? If at some point we want to hide it on all tables we would customize the DefaultCommandLibrary using RibbonWorkbench.

Thanks & best regards
Sandro

### Expected Behavior

- Make "Visualize this view" Button available / unhidden on all Tables

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Power Platform Admin View MDA

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

- Open MDA
- Go to Power Apps App, Flow, Environemnt View
- Check if "Visualize this view" button is missing

**Comment by manuelap-msft** [comment]
Yes, we've customized the ribbon to remove some actions that caused confusion or weren't needed. We can add those Power BI actions back in. 

Targeting for August release.

**Comment by Sani1991** [comment]
Tanks Manuela, much appreciated.

Best regards from Switzerland :)

**Comment by manuelap-msft** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/19def669-290a-4893-890d-13cdd48191c1)

Added back in for all the inventory type tables that are shown in the PP admin view. Ready for August release.
