### ISSUE TITLE
[ALM Accelerator - FEATURE] templates repo usage in multiple projects instead of adding to each project

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#6073]
### What is your question?

Hi Mike,

I have existing PowerApps project in DevOPs and trying to set up Pipelines using the "COE templates project" without creating separate repo for Templates in Power Apps project. For this, when I use Project Setup Wizard and select existing Power App Project, getting below error. Does reuse /refer to COE templates without creating template repo in PowerApps supported for empty/new projects only?

Thanks much!
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/39b58a9d-50bb-474b-979f-b4f331cb5e40)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

April 19th 2023

**Comment by mikefactorial** [comment]
@lingutla123 adding @RajeevPentyala here. We've discussed this internally and while it should be possible to initialize an existing project with the ALM Accelerator pipelines if you set them up manually. However, It's currently not possible using the Admin app. There's a lot of things to consider when implementing this and could have adverse effects. Think we should maybe revisit it though.

**Comment by lingutla123** [comment]
Okay, thank you Mike!
