### ISSUE TITLE
[CoE Starter Kit - BUG] Help with new audit logs solution

### ISSUE THREAD

**Issue by mattriesae** [microsoft/coe-starter-kit#6076]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Office 365 Management API Subscription Failing with the error: 
{
  "error": {
    "code": "AF10001",
    "message": "The permission set () sent in the request does not include the expected permission."
  }
}

The user who is running the flows can search the audit logs at: https://compliance.microsoft.com/auditlogsearch?viewid=Async%20Search

The application is set up like this:
<img width="638" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/105824691/bf825ea2-4def-43cb-bf23-bf7df0870a26">

My environment variables are set up:
admin_AuditLogsClientID: Set to the Application (client) ID from Azure (with the dashes)
admin_AuditLogsClientSecret: Set to the Secret Value from Certificates & secrets from the Azure Application

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Are you converting from the old custom connector methodology to Http? It looks like you missed the step of changing the app registration. 
We did a write up to help you, please see https://github.com/microsoft/coe-starter-kit/issues/6009

**Comment by mattriesae** [comment]
That fixed it, thanks for the quick response!!

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thank you for letting us know.
