### ISSUE TITLE
[CoE Starter Kit - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by mattriesae** [microsoft/coe-starter-kit#6078]
### Is your feature request related to a problem? Please describe.

Not related to any problems

### Describe the solution you'd like

Allow security groups to be added as owners to Flows the Admin - Flow Permission Center.

**Comment by Jenefer-Monroe** [comment]
Hello. I believe this is covered by this backlog item https://github.com/microsoft/coe-starter-kit/issues/5438
Please do let me know if I"ve misunderstood.

**Comment by Jenefer-Monroe** [comment]
you bet!
