### ISSUE TITLE
[CoE Starter Kit] How to setup connection to custom connector

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#6079]
### Describe your bug, question or feature ask.

I'm in the process of upgrading the Center of Excellence - Audit Logs and experiencing some difficulties creating a connection to Office 365 Management API. When I create a connection and the page refresh, the page refresh then defaults back to "Select a connection." Can you please provide some guidance?

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/3cf03b92-6c0f-4f42-8425-6edb01bec738)

**Comment by Jenefer-Monroe** [comment]
Hello, please note that we are deprecating the Custom Connector technique to gather audit logs. 
It is recommended that you instead [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

### Recommended path
Please follow the steps at [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

### Deprecated path

If you do wish to use the custom connector note that we are removing it in August so you will need to maintain a local copy before that upgrade. See [How to maintain custom connector methodology to gather audit logs](https://github.com/microsoft/coe-starter-kit/issues/6017)

In order to create a connection to the custom connector you need to follow the steps in [Collect audit logs using a custom connector (deprecated)](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog). 
In particular you cannot create a connection to the CC until you set it up as described in this section of that article: [Set up the custom connector](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector)

**Comment by dcurt1977** [comment]
I am trying to set up the HTTP action, but the flow keeps failing even though I have entered all the information for the variables. Any thoughts?

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/f974ac03-ec4c-4fb7-8558-57fa1bfd0706)

**Comment by Jenefer-Monroe** [comment]
Please share a screenshot of your API Permissions for the app registration.

**Comment by dcurt1977** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/0345ebe7-312b-40e8-b444-64359fe7809c)

**Comment by Jenefer-Monroe** [comment]
ok yes you have delegated permissions there but you need application permissions. 
Please see [Create an Azure AD app registration for the Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#create-an-azure-ad-app-registration-for-the-office-365-management-api)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ac45a11a-940f-446e-ba0c-44b79c7dfab2)


I believe you will need to delete the delegated permissions now and re-add as application

**Comment by dcurt1977** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/81884ba5-9497-4e61-ab82-baed9a899971)

**Comment by dcurt1977** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/0ede06fa-030c-4230-8ac3-24d36982bbb2)

**Comment by Jenefer-Monroe** [comment]
Please delete the delegated permission row. I believe if you have both it uses the delegated.

**Comment by dcurt1977** [comment]
I'm still getting the error message. 

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/dbca8ba8-5d13-467c-b600-f5af6d1ae93d)

Can i update the Azure Key Vault from this screen? Looks like when i update in the environment variable, it doesn't appear in the environment. 

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/40fb2d5b-c836-4272-92a7-9ba99ace7519)

**Comment by dcurt1977** [comment]
Although the Azure Key Value reference was entered as a variable, the value in use is blank in the CoE Command Center App.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/1a06233b-56b0-4e4b-bd57-345a876878f9)

**Comment by dcurt1977** [comment]
Also, i tried to update the variable but i'm getting this error. What is the user permission that should be applied on the subscription? 

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/a83112eb-b837-4983-9595-9bf57b623ab1)

**Comment by dcurt1977** [comment]
It appears that nothing has worked to set up audit log using the HTTP action, so will try the other method. The current version of the audit log is 2.10 as I'm not able to successfully upgrade yet to the latest version. Also, to maintain a local copy of the Office 365 Management API in my environment, create an unmanage solution then add the existing Office 365 Management API?

**Comment by dcurt1977** [comment]
It appears that nothing has worked to set up audit log using the HTTP action, so will try the other method. The current version of the audit log is 2.10 as I'm not able to successfully upgrade yet to the latest version. Also, to maintain a local copy of the Office 365 Management API in my environment, create an unmanage solution then add the existing Office 365 Management API?

**Comment by Jenefer-Monroe** [comment]
Here are the steps to maintain custom connector methodology to gather audit logs 
https://github.com/microsoft/coe-starter-kit/issues/6017

**Comment by dcurt1977** [comment]
I get this screen when testing the connection.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/10654b31-8676-4aa7-8783-49d856d39c3b)

When i click Back to app, i get this error message. Can you help? This has been very frustrating setting up the custom connector. 

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/4ea46cda-6352-4f3f-8176-9f97dbf808dc)

**Comment by dcurt1977** [comment]
I tried turning on the New| [Child] Admin | Sync Logs (Flow) and getting the below error message.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/ad4eb26b-a034-45ca-9376-a3e0bb914755)

When i click to open the flow, i get this blank screen. Please help.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/55b724c9-cc8c-4b5e-aa73-e1104a15812b)

**Comment by Jenefer-Monroe** [comment]
Duping to your other issue, we can resolve there together
https://github.com/microsoft/coe-starter-kit/issues/6150
