### ISSUE TITLE
[CoE Starter Kit] Parameter 'To' on Send an Email V2 action is being set to null

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#6080]
### Describe your bug, question or feature ask.

The latest version of the Center of Excellence Core Components was upgraded in a test environment. When the Admin | Compliance Details Request (Flows) runs, I'm getting the below error message on the HELPER - Send Email. The parameter of the 'To' field is empty.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/5c0c443a-81a2-42a6-a9e4-189eec6727a5)

**Comment by Jenefer-Monroe** [comment]
Please go to **_Admin | Compliance Details Request eMail (Flows)_** and find the run that resulted in this blank being sent to the helper. 

You can find it by adding the flowid as shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f0430795-e6cc-4a57-a9f5-37738c2dc59f)


Open the run and look at this scope and please answer the questions shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/600ee4f8-3f82-45f8-a967-23ec46770e62)

**Comment by dcurt1977** [comment]
Admin | Compliance Details Request eMail(Flow) is now working.

**Comment by Jenefer-Monroe** [comment]
thank you for letting me know!

**Comment by dcurt1977** [comment]
I deployed the Core Component solution in my production environment and i'm getting a similar error as described above. What from the FlowOwerID

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/873d12b1-9ba9-4806-bc14-0ae2d7f90c30)

Which path?

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/311f5753-8027-4533-892b-a879819cbfc1)

**Comment by Jenefer-Monroe** [comment]
can you please post a new issue for yours? Feel free to point to this one if you'd like but its how we track the cost to support the kit.
thank you!
