### ISSUE TITLE
[CoE Starter Kit - QUESTION] Does the CoE Solution versioning follow best practices?

### ISSUE THREAD

**Issue by craig-lund** [microsoft/coe-starter-kit#6084]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Does the versing of the CoE components follow the Power Platform Best practices and guidelines? For instance, when **adding** or **changing** components it's a "revision" version increment, for update imports. When patching a solution, it's a "Build" version increment for update only. When **removing**, adding, or changing components it's a "major" or "minor" version increment for "upgrades". 

I have ready that when upgrading the CoE components monthly to perform Upgrades. As I automate solutioning for customer I use versions to determine what type of imports to do. 

To restate my question, can I use the version increment to determine what type of import to do? 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

N/A

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

here's the principles we follow for versioning:
- usually: minor version increase (from 4.8 to 4.9). Typically during a monthly release we will always add, modify and remove components and indicate this with a minor version 
- rarely: major version increase (from 4.8 to 5). We would increase the major version if there's a major architecture change, or a big shift in functionality. We don't have anything on the roadmap today that would make us shift major version. 
- never: patches, we don't release patches.

We do recommend to use Upgrade for upgrades.

Hope this helps
Manuela

**Comment by craig-lund** [comment]
Amazing! 

By using Major and Minor only, removing, adding and updating components for each Minor version you are indeed following the platform "suggested" version practices. This makes it easy to incorporate into my deployment scripts.

You can see an example of that here: 

https://github.com/craig-lund-planet/PowerCoE/blob/main/scripts/Create-Settings-CoE.ps1
https://github.com/craig-lund-planet/PowerCoE/blob/main/scripts/Import-Solutions-CoE.ps1

Thanks for your response! Happy coding.
