### ISSUE TITLE
Move a non compliant flow to quarantaine after 7 days or more

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#6086]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi the team,

Like quarantaine apps process, is it possible to move a flow that is non compliant after 7 days ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately that feature is not offered for flows for us to use. Only canvas apps offer the quarantine feature.

**Comment by tocri** [comment]
thank you for your quick reply.

**Comment by Jenefer-Monroe** [comment]
you bet!
