### ISSUE TITLE
Do we need to setup the audit logs for BYODL?

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#6089]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi @manuelap-msft,

We are using BYODL option for starter kit. Do we still need to configure the Audit Logs via HTTP?
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

Thanks,
Devendra

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.4

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
You don't. Please review our FAQ on this topic: 
- https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq-dataexport
- https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq-dataexport#will-i-still-need-to-install-the-audit-log-solution-to-get-app-usage

**Comment by bch920** [comment]
@manuelap-msft just to confirm this one I thought it was mentioned in one of the office hours if you use the audit logs on top of data lake the benefits were you would get to know when apps were deleted quicker and you would have the context on who deleted it or was this something else ?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
