### ISSUE TITLE
Power Platform center of excellence missing flows from core solution

### ISSUE THREAD

**Issue by PPTechy** [microsoft/coe-starter-kit#6091]
I have installed the "CenterofExcellenceCoreComponents_4.9_managed" core solution in my environment. I have turned on all flows referring to this [MSDN article](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components). However, as per the MSDN documentation the below two flows also should be turned on but these two flows are not found in the "CenterofExcellenceCoreComponents_4.9_managed" core solution.

Is it an issue or these flows are deprecated from the 4.9 version of the core solution? So, these are not in the 4.9 version of the core solution.

- CLEANUP - Admin | Sync Template v3 (Connection Status) – This flow is not found
- Command Center App > Get CoE Flows – This flow is not found.

My second question is - apart from the flows listed out in the [MSDN article](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components) documentation to be turned on - still there are many flows in the core solution but not mentioned in this MSDN documentation about their turn on. So, I didn't turn them on. Is it Ok or we should turn on all flows irrespective of the MSDN documentation mentioned above or we should stick to the MSDN documentation guidance?
```[tasklist]
### Tasks
```

**Comment by manuelap-msft** [comment]
These flows have been deprecated with the 4.9 version. We are tracking removing them from the docs. It's highly recommended that you use the Setup Wizard to setup and upgrade as it ensures flows are all turned on in the needed order, and then you don't have to worry about which flows to turn on when or which ones are deprecated. The Setup Wizard will always be up to date.

The CoE kit consists of many different features, the foundation is the Inventory components feature which is the article you pointed to and lists the flows you turn on. Once you have your inventory foundation in place, the CoE kit then implements admin, governance and nurture processes on top of that - that's what the other flows are for. They are turned on when you follow the setup instructions for those processes. You can discover the processes also in the Setup Wizard if you select the "... More Features" navigation option.

**Comment by PPTechy** [comment]
Thanks for the detailed explanation @manuelap-msft, I got what I needed, hence closing the thread.
