### ISSUE TITLE
[CoE Starter Kit - QUESTION] Licensing requirement for viewing CoE kit Power BI Dashboard

### ISSUE THREAD

**Issue by NathanZhengASW** [microsoft/coe-starter-kit#6092]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Greetings! 

We are going to invite one vendor consultant to check the data from the CoE starter Kit.  For the sake of the security reason, we are not going to share with them the Power Admin credential and plan to share the CoE Power BI dashboard (running the latest version) to their guest account in AAD. 

Just want to confirm if this would work in this scenario? and does the guest account still require Power BI Pro license or even Power Platform Admin role to view the PowerBI Dashboard? 

By reading the article, it appears we can share the Power BI dashboard to any other accounts who don't have Power Platform Admin role. please kindly share any suggestions if my understanding is not correct. thank you! 

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Regarding this role
User does **_not_** need this to view the PBI
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e082df1c-6f2f-4cbf-9a7b-a451379647c6)

Security Roles:
They will need a SR to view the data though. We have not tested the PBI with different SR's so you may need to experiment though, or just assign the Admin SR as that is just for reading data.

Guest users:
We have not tested around guest users, but I believe they do not behave differently than member users wrt PBI features here. 

Licenses:
I'm not certain but I believe you need a power bi pro license to view a shared report.

**Comment by NathanZhengASW** [comment]
Thank you, Jenefer! 

This does clarify the role requirement. Just want to confirm the Admin SR refers to **this role** in the COE environment? 

![image](https://github.com/microsoft/coe-starter-kit/assets/135016903/5ef549b7-338a-4467-9347-44da0f0ca08a)

**Comment by Jenefer-Monroe** [comment]
Thanks for asking; no we ship a set of SR's in Core just for the kit. It grants access to the data. So I woudl suggest you pick the **_Power Platform Admin SR_** which is shown here. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/aa06f9a4-0032-4061-97b0-c1afc489a860)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d05869ef-96aa-4708-a337-7ccb5838aa62)

**Comment by NathanZhengASW** [comment]
Thank you! let me test it out and revert with the findings. Maybe this is not an uncommon scenario to share CoE kit data to guest account like for Auditing purpose.

**Comment by NathanZhengASW** [comment]
Okay. As we don't have Power BI Pro license yet, here is the way we grant the access of CoE starter kit environment to our auditors.  

1. In AAD, Add guest accounts for external auditors with proper license. 
2. Add them into the Security Group and grant them the Power Platform SR role in CoE environment. 
3. Then auditors can access the Environment link and play the Apps. 
4. Auditors can also use Power BI Desktop to import the Dashboard template and view the report using the normal licensing.

close this issue off. thank you for your advice!

**Comment by Jenefer-Monroe** [comment]
thanks for confirming this all works for your guest user!
