### ISSUE TITLE
Office 365 Management API connection issue: Cannot sign in Fix connection

### ISSUE THREAD

**Issue by PPTechy** [microsoft/coe-starter-kit#6093]
I had created this **Office 365 Management API** connection a year ago, and recently I upgraded the core solution (4.9 version). Now this connection is not working, saying cannot sign. When I am clicking on the **Fix Connection** link, it is taking me to the connection login page, and once I enter the credential, nothing happens. What I need to do to fix this connection? By the way, it seems that this connection has been used in the "Centre of Excellence Audit Logs" solution and not in the core solution.

<img width="635" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/9c53e8c4-8ebd-4170-9194-d0080697957b">

**Comment by manuelap-msft** [comment]
Please review some walk throughs on how to fix the connection here:
- https://github.com/microsoft/coe-starter-kit/wiki/Issue-triage-(CoE-Starter-Kit)#audit-log-connector-not-working-after-upgrade
- https://github.com/microsoft/coe-starter-kit/wiki/Issue-triage-(CoE-Starter-Kit)#audit-log-connector-authentication-failed

**Comment by Jenefer-Monroe** [comment]
Hello. Connections to custom connectors get broken on solution upgrade. Please see [issue 1424](https://github.com/microsoft/coe-starter-kit/issues/1424) for how to resolve

If that does not resolve, then you likely ended up with a bad connection, perhaps due to the wrong identity provider being selected as in [issue 4808](https://github.com/microsoft/coe-starter-kit/issues/4808)

If that occurs please try the steps outlined in [issue 4961](https://github.com/microsoft/coe-starter-kit/issues/4961)

**Comment by Jenefer-Monroe** [comment]
Note also that due to complexities like these we have moved away from the custom connector methodology to an http methodology and are deprecating the old audit log solution as a result. 
Please see https://github.com/microsoft/coe-starter-kit/issues/6009

**Comment by PPTechy** [comment]
Thanks for your reply @Jenefer-Monroe . I have followed you instruction mentioned in the link but no luck. I am getting this error while clicking on the fix connection after updating the connector with client id and secret. Below is the error I am getting: "Failed to refresh access token for service: aad. Correlation Id=06589az0-1c5a-39m3-b5bb-d9192a54ca5e, UTC TimeStamp=5/30/2022 3:54:38 PM, Error: OAuth 2 access token refresh failed. Client ID and secret sent in form body."

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
