### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - PowerBI Pulse_CoEDashboard

### ISSUE THREAD

**Issue by DevJasLane** [microsoft/coe-starter-kit#6097]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Afternoon,

I have installed the Pulse_CoEDashboard with the relevent env URL (-Https//) and have now got 'Fix this errors' on all the visuals and cards. It appears the naming is not found in the report or has been chnaged so it cannot relate.

### Expected Behavior

The report should display the outcomes from the surveys section of the CoE.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

July Release

### What app or flow are you having the issue with?

Pulse_CoEDashboard.pbxi

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Opened the Pulse_CoEDashboard.pbix file.
Added the Org url
Connection refreshed
Error on all visuals 'Fix This' All names in the 'Visulaization fields' are missing and have 'Yellow' caution symbol

**Comment by Jenefer-Monroe** [comment]
Here are the setup steps for this report [Set up the Power BI dashboard to view feedback](https://learn.microsoft.com/power-platform/guidance/coe/setup-nurture-components#set-up-the-power-bi-dashboard-to-view-feedback)
Highlighted in yellow the two most common issue:


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4d377079-55c3-4208-8a10-3cdd84f270ca)

**Comment by DevJasLane** [comment]
Classification: OFFICIAL

Hi,

I have followed all these steps a few times now.

TDS is turned on in the environment. The URL I take excludes all https and /. But yet I still get this error on the visuals.

Thanks

Jason Lane
Senior Developer (PowerPlatform)
07745739528
Magnox Hub Bristol, Keypoint, Almondsbury Business Park, Great Park Road, Bradley Stoke, BS32 4QQ
Email: ***@***.******@***.***>

Annual Leave - 9th August to 18th August
[Intranet]   ***@***.*** [microsoft-certified-power-platform-fundamentals.png]
***@***.***

**Comment by DevJasLane** [comment]
UPDATE

I have managed to get this work. I had to use a remote desktop to bypass some firwall settings.

Thanks

**Comment by Jenefer-Monroe** [comment]
oh wonderful thank you so much for letting us know!
