### ISSUE TITLE
[CoE Starter Kit - Feature]: AI builder capacity consumption report

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#6100]
### Is your feature request related to a problem? Please describe.

Hi, 

Could we include historical reporting on AI Builder Credit consumption at tenant level with drillable options to filter for specific environments in CoE ?

We are aware the we could see the AI builder consumption report from PPAC, however, it only reports on last 30 days.

### Describe the solution you'd like

Explained

AB#634

**Comment by manuelap-msft** [comment]
We recently learned that this data is available via the Dataverse **AI Event** table. We have not investigated storing and using this information yet.

Putting on our backlog for investigation, but we do have a few high priority items on our backlog so I don't think we'll be able to work on this anytime soon. If this is urgent for you, I'd recommend trying to implement a solution yourself by looking at the AI Event table.

**Comment by PPMini** [comment]
Thanks Manuela for guiding. 
When I am connecting Power Bi with my environment's Dataverse , could not see msdyn_AIEvent table in the list 
<img width="203" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/95ea1094-8711-4119-819d-c71503922e15">

Could you please advice on this?
Also , would like to understand, is it possible to see all tenant data instead of environment wise

**Comment by PPMini** [comment]
[like]  Mini Kaushik reacted to your message:
________________________________

**Comment by rmatesick-nw** [comment]
This is a great idea.  

What we would really need is to also be able to drill down to the user level within each environment.  The use case is when we see our AI Builder credits are nearing capacity, and we need to find out exactly who may be over-using and then we can open a line of communication with that person.

**Comment by v7herman4** [comment]
Until the COE Toolkit is updated consider leveraging the solution identified here: https://github.com/v7herman4/COE-TK-AI-Builder-Consumption

**Comment by Jenefer-Monroe** [comment]
Looking good for April release! 

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bf8f8c6b-e412-4dff-8b94-3a92128f94ea)

**Comment by PPMini** [comment]
[heart]         Mini Kaushik reacted to your message:
________________________________
