### ISSUE TITLE
Admin | Sync Template v3 (Driver) fails for environments linked to Dynamics 365 F&O 

### ISSUE THREAD

**Issue by yveskerwyn** [microsoft/coe-starter-kit#6101]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the `Admin | Sync Template v3 (Driver)` flow:

- Expand the `Store environments in the CoE CDS Entity`scope
- Expand the `Apply to each Environment`
- In the `No` branch of the `Check if Legacy Environment` condition open the `Get Maker` action
- Following input values are passed the `HELPER - Maker Check` child flow:
  - **MakerID**:  `@{items('Apply_to_each_Environment')?['properties/createdBy/id']}`
  - **MakerDisplayName**:  `@{if(equals(items('Apply_to_each_Environment')?['properties/createdBy/displayName'], null), '', items('Apply_to_each_Environment')?['properties/createdBy/displayName'])}`

For a regular environment that would successfully pass something like:

```json
{
  "host": {
    "workflowReferenceName": "9301f01a-cb40-ec11-8c62-00224829b4c1"
   },
   "body": {
      "text": "f987bb6c-dcfa-47d4-b5e6-87126f057098",
      "text_1": "Tom Baeten",
      "boolean": false
    }
}
```
For an environments linked to Dynamics 365 F&O it will fail because of the wrong values for **MakerID** and **MakerDisplayName**:
```json
{
  "host": {
    "workflowReferenceName": "9301f01a-cb40-ec11-8c62-00224829b4c1"
  },
  "body": {
    "text": "Microsoft Dynamics Deployment Service",
    "text_1": "SYSTEM",
    "boolean": false
  }
}
```

You'll get a error with status code 502:
```json
{
  "error": {
    "code": "NoResponse",
    "message": "The server did not receive a response from an upstream server. Request tracking id '08585119800273959433427282377CU43'."
  }
}
```

### Expected Behavior

You should not get a error 502.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Test the  `Admin | Sync Template v3 (Driver)` flow against an environment linked to Dynamics 365 F&O .

**Comment by manuelap-msft** [comment]
This was fixed with the July release, see
https://github.com/microsoft/coe-starter-kit/issues/5613
