### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Environment Properties Flow Fails)

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6104]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/f72b2dc3-92a8-469d-b884-fd8eac1284c0)

Not really sure does this mean there is an issue with a system admin sr matching does mean maybe some one left and there is no one listed anymore. Maybe you know how I should fix this.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Environment Properties Flow Fails)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. This was a product issue we worked around in the July release via https://github.com/microsoft/coe-starter-kit/issues/5754
I'll go ahead and close as a dupe to that. Thanks for posting.
