### ISSUE TITLE
[CoE Starter Kit - BUG] if the flow owner is changed, the update in the Starter Kit table is not performed

### ISSUE THREAD

**Issue by orauch-a** [microsoft/coe-starter-kit#6105]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

A flow is in a solution.
Flow owner has left the company and flow owner has changed to another account.
The starter kit does not modify the owner information in the admin_flow table.
We still have the previous owner.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows) and SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of where you change the flow owner?

**Comment by orauch-a** [comment]
In the flow detail : 
![image](https://github.com/microsoft/coe-starter-kit/assets/34766578/43e0627b-214f-471e-854f-ebaa8e289577)
Here the Microsoft documentation : https://learn.microsoft.com/en-us/power-automate/change-cloud-flow-owner

**Comment by Jenefer-Monroe** [comment]
Great thank you, just making sure we were on the same page. 
Yes this is not exposed to us programatically yet. We have a backlog item for this awaiting a product fix. https://github.com/microsoft/coe-starter-kit/issues/3052

I will dupe to that.

**Comment by orauch-a** [comment]
Sorry but the information is good in the "Get flow as admin" action, it's in "properties/creator"
But in the "SYNC HELPER - Cloud Flows" the owner is always retrieved from the inventory : 
<img width="410" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/34766578/bd92b46d-997e-4fe2-bf97-17e0d79d0ae3">

coalesce(outputs('Get_Flow_from_Inventory')?['body/_admin_derivedowner_value'], '')

And not in the "Get flow as admin" action.

I could be wrong, but wouldn't that be the problem?

**Comment by Jenefer-Monroe** [comment]
oh thats great news. We have not tested recently to see if the feature was lit up and unblocked. Sounds like it is. 
Will add that note to the feature
