### ISSUE TITLE
[CoE Starter Kit - QUESTION] Accessibility / Section 508 Compliance

### ISSUE THREAD

**Issue by bwieland86** [microsoft/coe-starter-kit#6109]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

With the move from Canvas Apps to Custom Pages and the usage of the Creator Kit / Fluent UI controls within the various CoE apps, has anyone tested if the Creator Kit controls or the various apps meet Accessibility guidelines in accordance with Section 508 (in the US), or its equivalents internationally? If not, is there a timeline to make the CoE apps compliant?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

All

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
The Creator Kit components follow Fluent UI guidelines, those components meet or surpass WCAG 2.1 AA standards, which are considered a higher level of accessibility compared to 508 standards (although similar). That just goes for the component itself, but not for the app using it. 

The CoE kit apps using those components do not implement accessibility - e.g. we don't use Alt Text, Tab Index or other accessibility properties as described here https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/properties-accessibility. We're unfortunately not staffed to do that level of development work on our apps.
