### ISSUE TITLE
[CoE Starter Kit - BUG]: Power BI Dashboard - Cloud Flow filtering by Connectors and Flow Actions does not work 

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#611]
**Describe the bug**
In the Power BI Dashboard of the CoE Starter Kit, on the Cloud Flows tab filtering by Connectors does not work. 

**Issue**
This is due to the relations between Flow, Flow Connection References, Flow Action Details and Connectors being single instead of both so they do not allow for cross filtering.

**Comment by manuelap-msft** [comment]
Fixed by updating the relation to cross-filter both. Need to end to end test if any other pages are impacted.

**Comment by morismm99** [comment]
Any updates on this one @manuelap-msft? I have spent a good chunck of this morning trying to figure this out. While I can fix the filter for flow actions/connectors, that requires the relationship between App Connection Reference and App to be set from Both to single, breaking a few other pages.

I also tried a few other things by duplicating the connector query, but that led to other issues with other pages...

**Comment by albertocaa1317** [comment]
Hi @manuelap-msft,
let me add a comment to this issue with a resumen of the behaviours of my Cloud flows tab:

This is the dashboard without filters:
![image](https://user-images.githubusercontent.com/57954993/122548667-f0fcb400-d031-11eb-9138-4e838d2d8dee.png)

1. The filters Creator and Department only filter the data of "Top 10 Active Departments":
![image](https://user-images.githubusercontent.com/57954993/122549289-9c0d6d80-d032-11eb-844e-83a13b6d626e.png)

2. The filters Connector and Action directly don't filter anything.

3. The filters Enviroment and Display Name filter OK.

4. If I select a Department in dashboard "Top 10 Active Department" it filter only the "Total # of Desktop flows":
![image](https://user-images.githubusercontent.com/57954993/122550234-b8f67080-d033-11eb-883d-729d8187b811.png)

5. If I select a Enviroment in the Dashboard "Top 5 Env'ts by % of cloud flows" all dashboards tab is filtered OK.

I hope that this information is helpful

**Comment by manuelap-msft** [comment]
Hello!

We are working on addressing this with the next release - we're moving the Data Model in the BI to a [star schema](https://docs.microsoft.com/en-us/power-bi/guidance/star-schema) which is helping us solve some of the cross filter issues, as well as simplify the model. 

It's a relatively large effort, as we have to redo the model and then test all the pages and filters but we're confident we will have this ready for the July release (targeted for first week of July).

I will loop back here when the new version is released, and if we make a version available sooner for testing will let you know as well.

Thank you
manuela

**Comment by manuelap-msft** [comment]
Good news! If you want to test the new dashboards before the July release, they are uploaded now and you can find them here: https://github.com/microsoft/coe-starter-kit/tree/CenterofExcellenceResources/CenterofExcellenceResources/Release/Collateral/CoEStarterKit

The same instructions as here apply:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi

If you get a chance to try it out before the July release, let me know if you find any issues with any of the filters still!

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
