### ISSUE TITLE
Is it possible to add Power App version notes to ALM commit message?

### ISSUE THREAD

**Issue by fosttj** [microsoft/coe-starter-kit#6112]
### What is your question?

After working on your Power App in the Power App UI, there is an option in a drop down to save with version notes.
Is it possible to capture these version notes and auto include them into the commit message.

After working on your Power App in the Power App UI, there is an option in a drop down to save with version notes.
 
![image](https://github.com/microsoft/coe-starter-kit/assets/136116520/f57a426c-ec88-4599-9b9b-5e6e677d09b1)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

July 2023

AB#924

**Comment by mikefactorial** [comment]
@fosttj can you provide a little more context here? Not sure where that screenshot is from.

**Comment by fosttj** [comment]
![saveoptions](https://github.com/microsoft/coe-starter-kit/assets/136116520/4093644d-ab7b-408f-8723-0afcb07b81e3)

Hi Mike, I have attached a screen capture from the Power Apps Editor showing the save with version notes selection. This is where the image I attached earlier from. 
![commitscreen](https://github.com/microsoft/coe-starter-kit/assets/136116520/723b99dc-476c-4171-af33-daf0f40669e5)
In the second attachment is the Commit solution window from ALM Accelerator with an arrow pointing to the location where I would like the version notes from the Power App Editor save option to auto populate.
Does this help?

**Comment by fosttj** [comment]
I have not gotten any updates from the information I posted 3 weeks ago. Is this something that is possible?

**Comment by RajeevPentyala** [comment]
@fosttj Apologies for the delayed response. In 'ALM Accelerator,' each commit represents a solution—a collection of components. Consequently, 'Notes' in the 'Commit' pane should be manually entered, focusing on the purpose of the solution commit rather than individual app version notes. Unfortunately, your request can't be fulfilled. Feel free to reach out if you need further assistance.
