### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 (Environment Properties) not finding child flow

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6114]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow keeps failing when trying to run child flow. Error I get is that it cannot find the child flow but the flow doesnt have any unmanaged layers. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/6da19015-3e2f-4af9-820a-b188a803ec54)

 

### Expected Behavior

Flow should run. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July Release

### What app or flow are you having the issue with?

Sync Template v3 (Environment Properties)

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Running the flow shows the issue.

**Comment by Jenefer-Monroe** [comment]
This typcially means that you have not turned on new child flows when you upgraded.

Its highly recommended that you use the Setup Wizard for installs and upgrades as it does the work for you to turn flows on in order. But if you cannot do that then you need to walk the [setup documentation](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) when you do them. 

If that still doesnt work then another option is to look at the flow dependencies. In the Required objects you will see which flows (labeled Process here) require to be turned on for the flow to work properly. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c210a21-8a71-413d-815f-bd7f3747608f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/39a7a3aa-9f39-4c07-8287-9004f4cb56e5)

**Comment by nasilvae** [comment]
> This typcially means that you have not turned on new child flows when you upgraded.
> 
> Its highly recommended that you use the Setup Wizard for installs and upgrades as it does the work for you to turn flows on in order. But if you cannot do that then you need to walk the [setup documentation](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) when you do them.
> 
> If that still doesnt work then another option is to look at the flow dependencies. In the Required objects you will see which flows (labeled Process here) require to be turned on for the flow to work properly.
> 
> ![image](https://user-images.githubusercontent.com/89584709/254875561-4c210a21-8a71-413d-815f-bd7f3747608f.png) ![image](https://user-images.githubusercontent.com/89584709/254875859-39a7a3aa-9f39-4c07-8287-9004f4cb56e5.png)

you are right thank you. We ran the setup wizard but didnt validate the helper flow to be on. We turned it on and it fixed the issue. Thank you.
