### ISSUE TITLE
[ALM Accelerator - BUG]: Deploy Solution Icon Remains in progress after all work has been completed

### ISSUE THREAD

**Issue by ChrisMcKee1** [microsoft/coe-starter-kit#6115]
### Describe the issue

After deploying a solution the status icon remains in progress. When you click on the icon, it takes you to an open PR. If you manual close the PR then the icon shows completed. 

![image](https://github.com/microsoft/coe-starter-kit/assets/25754153/f5deb51d-9345-4038-880f-6c859a69c49b)

![image](https://github.com/microsoft/coe-starter-kit/assets/25754153/71072128-e886-437b-b060-cbcb64651526)

![image](https://github.com/microsoft/coe-starter-kit/assets/25754153/5f4eb7a5-b031-49b3-994b-ef201a491815)

![image](https://github.com/microsoft/coe-starter-kit/assets/25754153/5725bfee-ef68-4fa1-aca1-5e25e08ad8ca)

### Expected Behavior

After the deployment is complete, the icon updates. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230629.1

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here.
