### ISSUE TITLE
[CoE Starter Kit - Feature]: Data Classification Variables for Compliancy Form

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#6118]
### Is your feature request related to a problem? Please describe.

The current data classification of General, Confidential, Highly Confidential does not match the current UK government classifications.

### Describe the solution you'd like

It would be very helpful if the values that are currently available were editable as variables so that it is possible to customise rather than having to change them and create layering.

**Comment by manuelap-msft** [comment]
Hello,

I think you should be able to modify those values based on your requirements

1. Navigate to your CoE environment and select the **Default solution**
2. Select Choices
3. Search for Data classification (admin_dataclassification)
4. You can delete and add values there and they should come through in the app etc.

That will create an unmanaged layer on the Choice but will not create issues during upgrade etc.

Hope that helps
Manuela

**Comment by medicineshow** [comment]
That is brilliant than you. Works a treat
