### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs: Missing some logs - require smaller chunks

### ISSUE THREAD

**Issue by kalpesh-jadhav77** [microsoft/coe-starter-kit#6120]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am getting this issue for Our environment

Your audit logs were collected but some were missed due to truncated results.
You will need to use a smaller interval to gather all logs.
See the optional Step 11 of our[ Audit Log flow setup documentation](http://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow) for more details.

Current chunking size:
1 Minute

I tried setting up time interval to 1Minute and Segment is 1500 still I am getting same error. Please what should I do.

### Expected Behavior

It should not send any email with this error.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Not sure

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1, run the flow Admin | Sync Audit Logs
2. child flows sends email as it's not getting expected result

### Anything else?

it was working till 19 July 2023 correctly. its not working since today 20th July.

Please let us know what can be done over here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
