### ISSUE TITLE
[CoE Starter Kit - COE Governance

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#6123]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have installed complete COE in our environment, 
My question is like I wanted to know about few things like: Once the flow / app gets deleted using the Sync Flows are those removed permanently or its only removed from the COE tables??

I also wanted to know if what cost more in COE which occupies more space in database capacity? We are currently seeing the environment impacted allot where it has only Core installed and really worried whether to continue with Governance and nurture or not?

How frequently the COE data is updated in Power BI reports.??

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
### 1. Once the flow / app gets deleted using the Sync Flows are those removed permanently or its only removed from the COE tables??
The sync flows detect if an object is deleted. So if a maker deleted their canvas app, we detect that and either delete the item from the CoE Tables as well (default behavior) or mark it deleted if you've flagged that setting.

### 2. I also wanted to know if what cost more in COE which occupies more space in database capacity? We are currently seeing the environment impacted allot where it has only Core installed and really worried whether to continue with Governance and nurture or not?
Most capacity needs are in the Core solution as they have a record for all your PP objects.

### 3. How frequently the COE data is updated in Power BI reports.??
You configure this yourself as shown here: [Configure the Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a2096f18-313d-46c1-aaca-64e6c8c976a6)


Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
