### ISSUE TITLE
[CoE Starter Kit - BUG] Auditing not reporting modified dates for flows within 6 months

### ISSUE THREAD

**Issue by mknightca** [microsoft/coe-starter-kit#6124]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flows stopped reporting modified dates from Jan 23rd or before, in the power admin view app. Nothing in the audit logs shows any modifications past the 23rd and that's obviously not true

### Expected Behavior

PowerApps are showing all modified dates up to todays date in the power admin view app

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

The audit logs flow runs fine, no issues, to duplicate i'm just in power admin view app and sorting flows by modified date from newest to oldest, there's nothing newer than Jan 23rd and obviously I never noticed until now

### Anything else?

I only upgraded to the new audit flow 2 days ago then i noticed this, so it wasn't working before the upgrade i'm sure, but the new flow has ran and completed successful with no errors

**Comment by Jenefer-Monroe** [comment]
Hello. We do not rely on the Audit logs for detecting that a flow was modified. The sync flows themselves do that. What version of Core are you on?

**Comment by mknightca** [comment]
I'm using the july version 4.11 but was previously using 3.56

**Comment by Jenefer-Monroe** [comment]
Great news, we should be able to get this fixed up and current for you then. 

Please go to the CoE Admin Command Center > CoE Flows > Inventory > Make sure you don't have any unmanaged layers by looking down this column, and if you do remove them
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ef3e2671-c90b-48e5-a520-d3c11fa033be)

Then make sure all the flows are on by looking down this column.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eae8f4ef-c136-4f23-853b-cacc627d6e2d)

Then look for these flows, have they run and passed recently?

- Admin | Sync Template v3 (Driver)
- SYNC HELPER - Cloud Flows
- Admin | Sync Template v4 (Flows)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5de860be-9aef-4dc8-85ac-2e699937f5fd)

**Comment by mknightca** [comment]
Thank you, so a couple things now that I've investigated.

1) the driver did have an unmanaged layer, i've never edited it though so its quite strange.

2) I don't have every flow enabled, especially ones contacting users

3)a) sync template v4 flow was off and I cannot turn it on error is "Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'a44274df-02da-ed11-a7c7-0022480813ff' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}"."

3)b) SYNC HELPER - Cloud Flows was off too and i've turned it on. This fixed the 3)a) issue.

I'll take a step back and run through CoE Setup and Upgrade Wizard as it seems i should to get everything setup properly.

**Comment by Jenefer-Monroe** [comment]
great thank you please do let me know if that resolves.

**Comment by mknightca** [comment]
yes, flows have  newer modified on dates now, issue resolved, thank you

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thank you for letting us know.
