### ISSUE TITLE
[CoE Starter Kit - BUG] When I try to launch a new app from app catalog I got an error because app is not found

### ISSUE THREAD

**Issue by wilmandx** [microsoft/coe-starter-kit#6125]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I launch an app from app catalog I have an error because it doesn't find the app, I checked in the inventory and the app id is different 

When I check the correct app id is different from that one generated in url: 

![image](https://github.com/microsoft/coe-starter-kit/assets/2592429/83fc03f2-67a5-4d3a-a4fc-417f2e4e8629)

so the app launcher is not using the correct app id

### Expected Behavior

the application is openned in the new window correctly

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

app catalog

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Add new app to catalog in power platform admin view
![image](https://github.com/microsoft/coe-starter-kit/assets/2592429/6c22ac4f-9889-42e4-bbc4-20a107a13536)

2. Open app catalog 

3. Click in the app that you want to open
![image](https://github.com/microsoft/coe-starter-kit/assets/2592429/85b0277b-f94a-4c8e-82e8-44a3d102e09e)

4. Error is shown in new window
![image](https://github.com/microsoft/coe-starter-kit/assets/2592429/89a14a9c-9d18-4baa-af8b-3de3250f5b40)

**Comment by wilmandx** [comment]
Yes absolutely, and I realized othre apps other are generated with the same wrong app id (7b5baf0d-0a25-ee11-9965-000d3a0a2c12 )

Desire link (working when I go directly)

https://orgf8ffe177.crm3.dynamics.com/main.aspx?appid=3d333a9e-fbff-ed11-8f6d-000d3aff3da3

Generate link by app catalog (wrong app id)

https://orgf8ffe177.crm3.dynamics.com/main.aspx?appid=7b5baf0d-0a25-ee11-9965-000d3a0a2c12

**Comment by Jenefer-Monroe** [comment]
Does this only repro for Model Driven Apps? We might have done it wrong for those when we lit up putting MDAs in here.

**Comment by Jenefer-Monroe** [comment]
Thank you for posting. 
Fix is just to change which field we use in the URL for the MDA case as shown below.
Local fixed for August.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d04206ab-a98e-4e53-a262-acbac1f05df2)
