### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Center Link in the Notification goes to a blank screen

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#6127]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the email notification, on click of the Developer Compliance Center url it goes to a blank screen.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/a8a68e15-2715-462c-bfd2-c72586715af1)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin | Compliance Detail Request (Flows)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Trigger the compliance email notification manually from the Power Platform Admin View Model - Driven App.
2. Click the url in the email notification that get sent to a user.
3. Check the screen for the object

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/b182485a-4f36-411f-a337-ea263474332d)

**Comment by Jenefer-Monroe** [comment]
Hello. I believe that is the old, deprecated canvas version of the compliance center. The link is now oriented towards the new model driven app. 

To fix this up you will need to update the env variable to point to the correct app. 

### Get the correct URL
In the Coe envt > Apps > Look for the DEveleoper Compliance Center Model-driven app > Details > Copy the Web link
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c7ef8766-9734-4ca0-9009-d3bac7dbbe5b)


### Update the env var
Done most easily in the Admin Command Center
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b42fa205-6b1d-4bcf-bcce-3e0134bef56b)

### Restart the flows
To ensure they pick up the new env var, I suggest you restart all the compliance flows
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d4cf69c5-2171-4d32-b545-96b45162f7c6)

**Comment by Jenefer-Monroe** [comment]
You are most welcome!
