### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Governance and Compliance Report - Environments with open Compliance

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6128]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Is this correct?

This doesn't seem to be calculating the correct number but then I am not sure how this is getting pulled as I have no data for it

This is the report:
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/0971906f-781f-457c-aa5d-b2f2d10ec8a0)

then below is what are power platform admin view looks like.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/ce9dcc50-241c-4f18-8ccc-65a85e8ad946)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.9

### What app or flow are you having the issue with?

Not really sure

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Please consider with your PBI FC

**Comment by manuelap-msft** [comment]
Environments get marked as Compliance requested via the Teams governance process: https://learn.microsoft.com/en-us/power-platform/guidance/coe/teams-governance - so you'd have open compliance request environments if this process is in use and compliance has been automatically requested. 

Hope that helps,
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
