### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Approval BPF

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6129]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

What populates the Date Asked for Business Justification, during the environment requests it was asked for business justification but not sure why the data isn't populating.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/13c029ca-3fd0-484f-85c8-9f01d21e1524)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.9

### What app or flow are you having the issue with?

not sure

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
That is only populated for Teams environments as part of the D4T governance feature. Please see [Set up Dataverse for Teams environment management](https://learn.microsoft.com/power-platform/guidance/coe/setup-teams-components)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
