### ISSUE TITLE
Quarantined App - Governance CoE - able to track users that tried to use the app while in quarantine

### ISSUE THREAD

**Issue by alzia-msft** [microsoft/coe-starter-kit#6130]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In Power Platform CoE Governance module, if an app is quarantined, I want to send the users subscribed to the app when they access it that the app is quarantined and cannot be accessed. Can this be created in a Flow or possibly in the existing Admin | Set app quarantine status & Admin | Quarantine non-compliant apps Flows?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Latest

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We do not have this authored but it could be done by cross referencing the audit logs. 
It's an interesting idea and we can place on our backlog. I don't expect us to be able to fund soon though so if its something you need soon you will likely need to consider the extension yourself.

**Comment by alzia-msft** [comment]
Thanks, Jenefer! I assume there still won't be a trigger that would alert the user if they are accessing the quarantined app in real time, correct? I assume you might query the Audit logs and keep track of the users that accessed a quarantined app and present a report at a particular schedule? Would like to listen more to your thoughts.

**Comment by Jenefer-Monroe** [comment]
The user will know the app is in quarantine when they try to access, they will see a note like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4a3e0184-901e-49e8-b883-f65ce144d86c)

**Comment by manuelap-msft** [comment]
We've been able to fit the reporting on this into the PBI refresh work that we had planned for August anyway. 

Here's how it works - can you let me know if that is sufficient?

On the Power Platform Governance Dashboard you have a new tile for **quarantined apps**
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/dd8cdbad-f59c-4699-9d2a-ad5477f5477d)

From the tile you can drill through to see the App details, that's a list of the apps that are quarantined (3 in my case)
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/7a1c2845-f0d9-4ce3-abcd-d7de0bfdc58a)

And from this list you can again select a single app and drill through to User details to see the details of the users that have launched the app and when:
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/8a01a473-4811-4c57-990d-6364840343ae)

Does this work for your requirements?

**Comment by manuelap-msft** [comment]
Re-opening so it gets closed as part of our August release and shows up in the Release notes :)
