### ISSUE TITLE
[CoE Starter Kit - BUG] Error with Data Export (with Data Lake). It does not populate the Power Automate files. 

### ISSUE THREAD

**Issue by JoelCanteroGCO** [microsoft/coe-starter-kit#6133]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello everyone,

I'm currently using the latest version of Core Components, specifically CenterofExcellenceCoreComponents_4.11_managed.zip.

I've been working on configuring the dataflows with Data Export (Data Lake v2) and have come across a few challenges that I would like to share and seek some assistance with.

Issue 1: Data Export not Populating Files

![image](https://github.com/microsoft/coe-starter-kit/assets/88024807/c1a7ae71-fa4d-4c39-a1ac-0b54217fdb63)

After setting up the data export with Data Lake for Power Apps and Power Automate, I noticed that the data export isn't populating any files in the folder /powerplatform/powerautomate/ within my Storage Account. It seems that the following dataflows are affected:

CoE BYODL Flows (Flows, admin_flows tables)
Coe BYODL Flows Last Run Date (FlowUsage table)
CoE BYODL Flows Connection (FlowConnRef table)

These dataflows appear to be empty, and I'm unable to find the data I expected.

Issue 2: Error in "CoE BYODL Flows Last Run Date" Sample File
Furthermore, when trying to access the "CoE BYODL Flows Last Run Date" Sample file, I encountered the following error message:

Expression.Error: There weren't enough elements in the enumeration to complete the operation.

Troubleshooting Steps Taken:

I've waited for more than 5 days, hoping that the dataSource error of "The specified path doesn't exist" would resolve on its own. Unfortunately, the issue persisted.

As an alternative, I manually created the entire folder architecture /powerplatform/powerautomate, but even after doing so, the Data Export still hasn't populated all the required files into my storage account.

I would appreciate any guidance or suggestions to resolve these issues and get the Data Export working as expected. Thank you in advance for your help!

### Expected Behavior

I am expecting to have powerautomate files in my storage account.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Configure data export with Power Automate and Power Apps.
2. Configure dataflows.
3. Go to my storage account and then see that the powerautomate files are not available.

**Comment by manuelap-msft** [comment]
Hello,

Data Export is a product feature part of the Power Platform Admin Center, and not related to the CoE kit itself. The CoE kit is just a consumer of the data exported from the Data Export feature. If the data export doesn't work properly, then the CoE kit can't consume the data.

I'd recommend raising a Microsoft Support ticket to let them know you're not receiving Power Automate files through Data Export. If you let me know your Tenant ID here, I can also follow up with the Engineering team internally.

Thank you
Manuela

**Comment by JoelCanteroGCO** [comment]
This is what they've said:
![image](https://github.com/microsoft/coe-starter-kit/assets/88024807/68b46ace-e6cc-4d2a-904b-6e1157f1a306)

**Comment by JoelCanteroGCO** [comment]
So @Jenefer-Monroe?

**Comment by manuelap-msft** [comment]
You'll have to continue working with Microsoft Support to let them know the issue is not related to the CoE kit, but to the Data Export feature. 

There's unfortunately no support we can provide for this, this feature is set up from PPAC and the CoE kit just consumes data from it.
