### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Setup and Upgrade Wizard - Capacity alerts and Welcome email - Missing pre-req

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#6135]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After going through the set up wizard, I select more features, Capacity alerts and Welcome email, configure this feature, and once I get the page to load (had to do a refresh, otherwise it never loads), I get this message:

![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/076d9479-80d2-4c3b-88e6-576dc4a445d2)

If I try to go back to the initial setup wizard, and back my progress up, under run set up flows, it just sits as blank.

![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/611c8d7a-18de-4177-bc6b-b67f97a70108)

### Expected Behavior

Be able to use wizard to configure component and/or complete requirements. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
These are the same flows as your other issue which is being investigated. So I'll go ahead and dupe to that. I am meeting with someone who has a GCC install so hopefully we can get this resolved at that time. 
Dupe to https://github.com/microsoft/coe-starter-kit/issues/6074
