### ISSUE TITLE
[CoE Starter Kit - BUG] Issue with data of Model Driven app User activity not available in dashboard.

### ISSUE THREAD

**Issue by bb-vinod** [microsoft/coe-starter-kit#6136]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The user activity of Model Driven apps are not available in the COE dashboard.

### Expected Behavior

We would want to see the user activity and identify the usage of our model driven apps.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Apps) 

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

The flow runs fine. But filters only for the below 3 activities from Audit logs:
•	LaunchPowerApp
•	DeletePowerApp
•	DeleteFlow

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately we cannot collect user activity for Model Driven apps today, only for canvas.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
