### ISSUE TITLE
[CoE Starter Kit - QUESTION] Question about environment backups and Audit Logs

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#6137]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I just want to get a second opinion before I proceed.

My production environment is currently on the April 2023 release, and currently has Audit Logs setup using the custom connector.
Since the COE kit needs to be upgraded every 3 months, I am planning to upgrade to the July 2023 release, then re-configure Audit Logs using HTTP (after I upgrade to the July 2023 release)
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

I also have a COE testing environment with the July 2023 release installed.

I have 2 questions:

Question 1:
There are 2 types of environment backups: "System Backups" and "Manual Backups"
Do you recommend doing a "Manual Backup" of my COE Production Environment each time I upgrade to a new COE kit release? Or would the automatic "System Backups" be good enough in case something goes wrong with the upgrade?

Question 2:
Is it okay to have Audit Logs installed in both my COE Production and COE Testing environment?
I still don't quite know Audit Logs very well, but I don't want there to be duplicate log entries in the backend, and I'm worried this will happen if I have Audit Logs setup in both my COE Production and COE Testing environment.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I think the system backups are fine. If you are using a test envt especially which it sounds like you are.
The sync flow architecture does write the audit logs to a table, you can write a little script to delete them between upgrade tests though if you'd like. 

I hope thats helpful.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
