### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Emails Not Sending to Owner

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#6139]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Reference #

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Compliance Emails

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Trigger request from the Power Platform Admin View Model-Drive App
2. Check the Compliance Flow
3. Check the HELPER Flow

**Comment by Jenefer-Monroe** [comment]
This is in reference to bug https://github.com/microsoft/coe-starter-kit/issues/6080

**Comment by Jenefer-Monroe** [comment]
From your picture
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6de4ac8a-facd-42ac-b9ac-0cb4ded19b0c)

It looks like its going to the correct person. What do you mean when you say its going to the wrong person? Who is it going to?

**Comment by dcurt1977** [comment]
The "To" field in the HELPER - Send Email is blank.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/e2bec550-246e-4553-9a56-3c4f2c21144a)

**Comment by Jenefer-Monroe** [comment]
Please share what is sent in to this call
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/472477c6-2626-4c93-a778-3207b7a76364)

**Comment by dcurt1977** [comment]
It appears that the compliance emails now working.
