### ISSUE TITLE
[Set Flow Permissions] Url incomplete to access to Flow settings

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#614]
Core 2.1.70

In the app Set Flow Permissios, when I try to go to the settings of the flow, the url is incomplete in the navigator:
![image](https://user-images.githubusercontent.com/57954993/121594553-8352f580-ca3d-11eb-912d-9e2656326fd0.png)

![image](https://user-images.githubusercontent.com/57954993/121594977-0f651d00-ca3e-11eb-85a5-3356ac52ffea.png)

https://emea.flow.microsoft.com/ is missing

I have checked the app and I see this:
![image](https://user-images.githubusercontent.com/57954993/121594710-bac1a200-ca3d-11eb-83a6-22b70f01d067.png)

It seems that the problem is in settings.'Flow Maker URL'

**Comment by JeneferM-MSFT** [comment]
1. Did you do these steps outlined in the [Core Setup Instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#configure-the-coe-settings-table)?

1. Can you please open the details page on any flow and show me the URL? 
![image](https://user-images.githubusercontent.com/62659043/121697023-e2d6f280-ca89-11eb-9c02-6588af52a830.png)

**Comment by albertocaa1317** [comment]
1. Yes, I think :)
![image](https://user-images.githubusercontent.com/57954993/121859062-8da01880-ccf7-11eb-8d52-8b3e7e3d2382.png)
In Default Solution -> Power Automate Enviroment Variable =  https://emea.flow.microsoft.com/manage/environments/

2. 
![image](https://user-images.githubusercontent.com/57954993/121859840-8299b800-ccf8-11eb-878f-1373d4f27fb6.png)

https://emea.flow.microsoft.com/ is missing

**Comment by JeneferM-MSFT** [comment]
fixed for July

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
