### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 (Solutions) Fails to get solution owner

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6141]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow fails to get solution owner. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/92f84793-5921-45ed-90be-62044ff7efd8)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Flow run fails

**Comment by Jenefer-Monroe** [comment]
Please post the text from that output failure.

**Comment by nasilvae** [comment]
I got the error details from today's latest failed run. It seems an issue with the dataverse connector. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/585c2fa9-1528-48f1-a178-756c84042925)

**Comment by Jenefer-Monroe** [comment]
Will try that same retry but again, your tenant might just be up against limits for which you will need to press to have the rate limit changed.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/efa4b091-1ff0-4430-9bcb-8c254e154cce)

**Comment by nasilvae** [comment]
> Will try that same retry but again, your tenant might just be up against limits for which you will need to press to have the rate limit changed. ![image](https://user-images.githubusercontent.com/89584709/255645519-efa4b091-1ff0-4430-9bcb-8c254e154cce.png)

Are rate limits per tenant or is it a PG ask? I'm trying to understand who to escalate.

**Comment by Jenefer-Monroe** [comment]
Product Group. Yes this is a basic limitation on the connector across the board.

**Comment by manuelap-msft** [comment]
Closing out as we increased the retry policy here with the last release
