### ISSUE TITLE
[ALM Accelerator - BUG]: Save Solution not creating Prod Pipeline

### ISSUE THREAD

**Issue by Aditi3981** [microsoft/coe-starter-kit#6143]
### Describe the issue

The ALM is unable to create the prod pipeline in the folder after saving the Solution in ALM Accelerator app. It creates validation and Test pipeline correctly but does not create Prod. Also, it is adding 'coe-starterkit-azdo' label in front of the solution name.

### Expected Behavior

It should create the Validation, Test and Prod pipelines in the Folder with Solution Name correctly.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230629.1

### Steps To Reproduce

1. Create yaml files in main branch in the Solution Name Folder
2. Create a Branch with the Solution Name
3. Click on Save Solution in ALM
4. Should create 3 pipelines (Dev, Test and Prod) in the Solution name folder

**Comment by mikefactorial** [comment]
@Aditi3981 can you share if there are any specific errors during the Update Deployment Settings stage in the export pipeline? Logs would help figure out the specific issue here.

**Comment by mikefactorial** [comment]
Closing this out as there hasn't been a reply. The creation of the folders with the repo name prefix is expected and was added recently to allow for pipelines to be created in the same project for difference repos.

**Comment by Aditi3981** [comment]
Ok. Yes, we were able to create the pipelines correctly and we renamed the folders afterwards. Thank you.

From: Mike! ***@***.***>
Sent: Wednesday, September 06, 2023 1:48 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Aditi S Patil ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [ALM Accelerator - BUG]: Save Solution not creating Prod Pipeline (Issue #6143)


Closing this out as there hasn't been a reply. The creation of the folders with the repo name prefix is expected and was added recently to allow for pipelines to be created in the same project for difference repos.

-
