### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUUpgrade COE from 4.3 to 4.11 - need to boot Setup Wizard?

### ISSUE THREAD

**Issue by Raz-786** [microsoft/coe-starter-kit#6144]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

****** it's not a bug reporting request******

Hello,

Q1.  I was able to successfully upgrade my Core component from 4.3 to 4.11 and follow the below link https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup

One of the section discuss

After the solution import is successful, **open the Center of Excellence - Core Components solution.**
Do I have to run CoE Setup and Upgrade Wizard app.
it looks to me things are working as expected after run import solution successfully without following next step i.e. CoE Setup and Upgrade Wizard app, but you never know I may be in wrong assumption

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

no Issue with any Flow

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Yes the setup wizard will get the needed flows and environment variables set for you. We recommend you always boot it and walk through its screens when you upgrade.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
