### ISSUE TITLE
[CoE Starter Kit - QUESTION] Changing from non-production to production environment

### ISSUE THREAD

**Issue by rjhowes73** [microsoft/coe-starter-kit#6146]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Before starting to send inactivity and compliance emails out to users I switched the productionenvironment variable to No and then turned on the inactivity notifications process, and will soon be turning on the compliance flows.  The principal reason for this was to try and see how many apps and flows would be flagged for inactivity, and how many apps and flows will be flagged for compliance, so that we have an idea of how many additional per user licenses we will need.

My question is do I need to do anything to clean up the existing deletion approvals that were sent to my admin account, or will the flows then just reassign the approvals from my admin account to the actual owners?  And the same for compliance notifications that will initially be sent to my admin account?

Thanks in advance.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.9

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Good question. Thanks for posting. 

For inactivity, you can delete the records in the **_Archive Approval_** table of the Core solution. 
They would clean themselves out eventually but you may as well start from clean.

For Compliance, there is no such backup to clean out.

**Comment by rjhowes73** [comment]
Thanks.  Just so I am clear, if I turn the compliance flows on in non-production I will receive the compliance emails and they won't get sent to the owners when I change it to production?  Or will the approvals get sent to the owners but I will also still have them as well?

**Comment by Jenefer-Monroe** [comment]
Sorry I dont follow
isProduction = no is used to send all mails to the admin email isntead of the maker. True for inactivity, compliance, and so on.
Is that what you are asking?

**Comment by rjhowes73** [comment]
Not quite.  I know that with isproduction set to no it will send the compliance notifications to me as the admin.  My question is when I switch isproduction to yes, the next time the flows run will they send the notifications to the actual owners, even though they have already been sent to me?

**Comment by Jenefer-Monroe** [comment]
yes we just resend those each time unless the work has been completed (ex the person filled out the required fields) 
Do note that sometimes env vars get cached so if they are sent to you again after changing the env var you can turn the flows off and on again to reset the cache.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
