### ISSUE TITLE
SharePoint library not visible

### ISSUE THREAD

**Issue by rahul9226** [microsoft/coe-starter-kit#615]
Describe the bug
SharePoint library not visible to select.

Component (please tell us which flow or app you are experiencing issues with):

Nurture component
Version [e.g. 1.40]
App or Flow [e.g. Maker Assessment | Import starter data cloud flow]
Environment Variable - Maker Assessment SharePoint Library"
To Reproduce

Import Nurture component
While importing solution update Environment Variable
Scroll down to 'Maker Assessment SharePoint Library'
Can't see library.
Expected behavior
When trying to select "Maker Assessment SharePoint Library", the new site we created does not show up in the list of sites. Checked with permission, user is owner as well as Admin for SharePoint site. Also created library, which is not displayed within the Maker Assessment | Import starter data cloud flow.

![image](https://user-images.githubusercontent.com/77864042/121605723-c000fb80-ca01-11eb-855d-f022fa7c7d4a.png)

**Comment by manuelap-msft** [comment]
Hello,

this screen is part of the Solution Import experience, and thus part of the product - it's outside of the CoE Starter Kit and not something we have control over. Please raise a support ticket through regular support channels to get help for this!

Thank you
Manuela
