### ISSUE TITLE
[CoE Starter Kit - BUG] New | [Child] Admin Sync Logs (Flow) in the new solution getting error

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#6150]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After importing the New Audit Log CC solution, I tried to turn on the New | [Child] | Sync Logs flow but getting the blow error message.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/cf253c58-f5c5-4c3a-9f2f-bd0e51d792b8)

Also, when I open the flow i'm getting this blank screen.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/a34f217a-b45b-4612-a1c7-193bfc6712b2)

### Expected Behavior

Tried to turn on the New | [Child] | Sync Logs flow.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.0.0.3

### What app or flow are you having the issue with?

New | [Child] Admin | Sync Logs

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Turned on the New | [Child] Admin | Sync Logs
2. Observe the behavior

**Comment by Jenefer-Monroe** [comment]
Please share a picture of the test screen for the custom connector so that we can validate that it was set up correctly:
![image](https://user-images.githubusercontent.com/89584709/161313079-237ddfa5-8fcd-48ed-98ae-26a99983a7b7.png)

A picture like this showing the API permissions are set correctly
![image](https://user-images.githubusercontent.com/89584709/225952426-74897c8e-4190-40e2-a91a-681f66a46d3d.png) 

Make sure you used the secret value as well and not its GUID. Thats something people do farely often
![image](https://user-images.githubusercontent.com/89584709/225953435-8d2d5b8c-1fdd-4e24-92c0-e4618c23f1fa.png)

**Comment by dcurt1977** [comment]
Here's a copy of the test screen for the custom connector.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/0c936046-8b35-4467-87da-1af2ac3aa605)

**Comment by dcurt1977** [comment]
Is the Security tab set up correctly? Do i have the correct Redirect URL?

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/c294c2a5-e809-47d9-8d2a-aad16ba763b3)

**Comment by Jenefer-Monroe** [comment]
Yes that looks correct if you are GCC
Note you also need to set on this first page as shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/94e793f6-d3a0-4e58-b29a-44cfc2248670)

**Comment by Jenefer-Monroe** [comment]
Please run a test command to see if the connection is correctly setup
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6383cc2e-e5d2-4953-b9f4-41fb5fe981fc)

**Comment by dcurt1977** [comment]
I'm still getting the same error message when i try to turn on the flow. Do i need to start a subscription? Re-import the solution? When i click on the edit button of the flow, i get this screen.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/d212f0be-72ae-4a4e-af09-f725f7e8688e)

**Comment by Jenefer-Monroe** [comment]
Something strange is happening for you with the inability to see the new flow
Can you please shrae a screenshot of what your solution list looks like? 

Basically I'm looking especially to see the things in yellow, as well as to see if the old audit logs is gone.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/65c59fd0-e174-419e-9629-c71e9037fbfb)

**Comment by dcurt1977** [comment]
Here's a screenshot of my solutions.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/f8dc1cab-101d-4d9b-ae41-044cff17b678)

**Comment by dcurt1977** [comment]
Here's a screenshot of my solutions.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/f2b02227-17e2-4b9c-8abb-6b19096ee7ed)

**Comment by Jenefer-Monroe** [comment]
Are the screenshots above from your debug envt then? Just making sure I understand the state. 
I ran through the steps again and they work for me so I'm just not sure what is happening. 

Can you check to see if the connection appears to be healthy from this UX?

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b167f6a0-e2e8-4982-ac31-8edf0e8a3a24)

**Comment by dcurt1977** [comment]
Yes, the screen shots above are from my debug environment, but I have not yet set up to maintain the old custom connector methodology in my Prod environment. Should i give it a try in production?

The connection appears to be health.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/d5093311-1eb2-4497-a7f0-e5de3b696f8c)

**Comment by Jenefer-Monroe** [comment]
Can you remind me, what was the reson for not using the new Http methodology? 
Might it be due to this bug? https://github.com/microsoft/coe-starter-kit/issues/6075

If so that fix will be shipping next week.

**Comment by dcurt1977** [comment]
I have good news! I went ahead and set up the old custom connector methodology in Prod environment. The New | [Child] Admin | Sync Logs turned on and ran successfully. Thank you so much for your time responding to my questions. 

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/40a125de-8656-4a75-ab6f-c103696d0b22)

**Comment by dcurt1977** [comment]
I tried setting up the HTTP Methodology but kept getting the below error when creating a connection.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/ff493e0a-06f5-46c9-b2d6-0425b2d2d770)
