### ISSUE TITLE
[CoE Starter Kit - BUG] Flow 'CLEANUP HELPER - Power Apps User Shared With' fails when group doesn't exist anymore

### ISSUE THREAD

**Issue by lcimon** [microsoft/coe-starter-kit#6151]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The action "Get application role assignments as admin" returns the group assignment that no longer exists. The group has been deleted from Active Directory.
This will cause the 'CLEANUP HELPER - Power Apps User Shared With' flow to fail because it was trying to list group members.

![image](https://github.com/microsoft/coe-starter-kit/assets/22662809/dda7d9d1-ced5-45b2-95c9-b3b2f9f8f73d)

### Expected Behavior

The error must be caught to prevent the flow from failing.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, this is local fixed for August by https://github.com/microsoft/coe-starter-kit/issues/6090
So I'll go ahead and close as a dupe for that.
