### ISSUE TITLE
[CoE Starter Kit - BUG] Mashup Exception Error

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6153]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This is a follow up from: https://github.com/microsoft/coe-starter-kit/issues/5880

The BYDOL CoE is experiencing inaccurate inventory counts of resources. Upon checking, I noticed the BYODL Flows Data is having a Mashup Exception Error. I had the issue escalated with support engineering and they advised that we are hitting the limits of the dataflow. 

Currently per PPAC Analytics these are the number of resources that we have:
Environments: 803
Apps: 9,189
Connections 7,229
Flows: 114,004

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/54ae5af8-c5a6-478d-b38c-51d9bc84c1af)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/0f251ea6-309a-46a8-9a2b-cd4c1c503067)

I was advised to validate Power Query data limits as the error is a limit error. It seems My tenant is hitting the Power Query limit. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/3ef9f4c1-c7f2-4b7a-9b2e-f05f67a26b8a)

### Expected Behavior

Data Flow should run normally. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023 Release

### What app or flow are you having the issue with?

BYODL Flows

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Run Data Flow and it fails. 

AB#436

**Comment by Jenefer-Monroe** [comment]
I dont think there is anything we can do about this limitation but thank you for raising awareness. We will take a look to see if we can do anything but this may just be a place where you need to escalate to the product team your client needs for the feature.

**Comment by nasilvae** [comment]
> I dont think there is anything we can do about this limitation but thank you for raising awareness. We will take a look to see if we can do anything but this may just be a place where you need to escalate to the product team your client needs for the feature.

Hi, I changed the refresh from full to incremental and it seems to be working. I'm using 7 day old using the last modify column.

**Comment by nasilvae** [comment]
> I dont think there is anything we can do about this limitation but thank you for raising awareness. We will take a look to see if we can do anything but this may just be a place where you need to escalate to the product team your client needs for the feature.

Hey, We are noticing the flow counts are now not accurate since we changed the dataflow setting to incremental. What other steps can we take?

**Comment by nasilvae** [comment]
@Jenefer-Monroe after additional research we noticed that when doing incremental dataflows the CoE is only capturing the new values and not the whole dataset. Thoughts?

**Comment by Jenefer-Monroe** [comment]
It looks like incremental refresh won't work due to how the data is coming through via Data Export. Incremental refresh only works for data that's in a normalized table format, but we're just getting a file dump.

The Mashup error is just a product limitation, so there isnt anything we can really do about it. You may need to work with the product group directly and then if you are able to find something that would help us we would be happy to hear about it.

**Comment by nasilvae** [comment]
> It looks like incremental refresh won't work due to how the data is coming through via Data Export. Incremental refresh only works for data that's in a normalized table format, but we're just getting a file dump.
> 
> The Mashup error is just a product limitation, so there isnt anything we can really do about it. You may need to work with the product group directly and then if you are able to find something that would help us we would be happy to hear about it.

gotcha we just opened a support ticket and having escalated will keep you posted.

**Comment by Jenefer-Monroe** [comment]
Have another repro which I will dupe here as you do your investigation: https://github.com/microsoft/coe-starter-kit/issues/6462

**Comment by nasilvae** [comment]
> Have another repro which I will dupe here as you do your investigation: #6462

Im still waiting from the escalation team. Once I get an update will follow up.

**Comment by jayakumarkgds** [comment]
> > Have another repro which I will dupe here as you do your investigation: #6462
> 
> I'm still waiting from the escalation team. Once I get an update will follow up. One of the recommendations they advised me was to divide the query onto multiple queries or minimize the amount of data the query ingests.

Any solution?we are also facing same issue

**Comment by Jenefer-Monroe** [comment]
Another repro: https://github.com/microsoft/coe-starter-kit/issues/6962

**Comment by jayakumarkgds** [comment]
I beleive we have discussed this earlier and it is due to the table column limit to accomodate the name of the flow or app.identifying such flows and apps will be a problem
