### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Request - Ability to Change the Model Driven App, What are the risks?

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6156]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

For the Environment Request Process how much can be edited and what are the impacts of editing that app I have a customer that would like to have addtional fields to this that this app does not cover.

Thoughts?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

not sure

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Model Driven Apps and Tables do support co-auth to some extent. I'm afraid I cannot assist with specifics here as we are not staffed to help with customizations. 
Here is some product documentation on this https://learn.microsoft.com/power-apps/maker/model-driven-apps/coauthoring

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
