### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to turn on New |[Child] Admin| Sync Logs

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#6158]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I followed the instructions on How to maintain custom connector methodology to gather audit logs #6017. The new custom connector is set up successfully, but when i tried to turn on the flow "New | [Child] Admin | Sync Log" i'm getting this error message.

![image](https://github.com/microsoft/coe-starter-kit/assets/123478097/0bff609a-dd9e-4c19-869d-b8f2759ee069)

### Expected Behavior

Back in the New Audit Log Solution, successfully turn on the New | [Child] Admin | Sync Logs.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.0.0.3

### What app or flow are you having the issue with?

New | [Child] Admin | Sync Logs

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Deleted Audit Log 2.10
2. Imported New Audit Log CC
3. Successfully set up the new custom connector
4. Imported NewAuditLogSolution 1.0.0.3
5. Updated the environment variables
6. Back in the New Audit Log Solution, turn on New | [Child] Admin | Sync Logs
7. System generated error above

**Comment by Jenefer-Monroe** [comment]
Duping to your other issue, we can resolve there together
https://github.com/microsoft/coe-starter-kit/issues/6150
