### ISSUE TITLE
[CoE Starter Kit - QUESTION] No data showing after setting up the kit

### ISSUE THREAD

**Issue by Kargadong-Putik** [microsoft/coe-starter-kit#6160]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have recently installed the COE Core Components, I used "Setup Wizard" to complete the configuration. However, when opening the Power Platform Admin View there are no data 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
How recently did you set the Core components up? It can sometimes take a few hours for the flows that gather inventory to finish running.

**Comment by Kargadong-Putik** [comment]
> How recently did you set the Core components up? It can sometimes take a few hours for the flows that gather inventory to finish running.

Thanks Manuela, around 3 hours ago.

**Comment by Jenefer-Monroe** [comment]
Please browse to the flows in Core and find this one: **_Admin | Sync Template v3 (Driver)_**

Open to look at the details and click the in progress run
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/20834b6e-1ae2-4ee3-9036-dd6640e50a8a)

You will probably find it sitting in this action. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3991ade7-b493-4f3b-985c-76ea94f64711)

Most people have to return the next day to see their inventory populated.

**Comment by Kargadong-Putik** [comment]
Thanks Jenefer, upon checking the workflow "Admin | Sync Template v3" still running. Thanks so much!

**Comment by Jenefer-Monroe** [comment]
You're welcome! I'll go ahead and close out but feel free to return with new issues as needed.
