### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Inactivity notifications v2 (Check Approval) fails in the 'Check_Approval_Status' action

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#6161]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After the CoE Starter Kit April upgrade, we noticed that the flow "Admin | Inactivity notifications v2 (Check Approval)" very often fails in the 'Check_Approval_Status' action.
<img width="185" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/1ebfad52-e5b9-4aa1-a24d-0f9380c0d4db">
<img width="580" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/caba13bb-0328-49e0-996e-1334d2ec7a1b">

I noticed that the flow fails when the action "Check if item found" is at least once "true". 

![image](https://github.com/microsoft/coe-starter-kit/assets/113427788/eb521159-639d-44bb-a7a8-42fb277f15cc)

However, if all the "rows" are "false" in the action "Check if item found", then the flow's run is successful. 

<img width="578" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/9b57bb6d-0d7c-4839-a749-969bb149dd42">

### Expected Behavior

The Admin | Inactivity notifications v2 (Check Approval) flow needs to run successfully. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.8.1

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Check Approval)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Can you please open this and see which action inside is failing for you?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1d82d05e-d4a7-4cc3-843c-edd24887808b)

**Comment by JanetK12** [comment]
Hi @Jenefer-Monroe! 
Thank for your answer!
Here are the screenshots:
<img width="595" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/2fb9f533-f968-4092-9c16-5053c2479010">
![image](https://github.com/microsoft/coe-starter-kit/assets/113427788/274fce6e-4bdd-48e0-8b8a-16e7873a124d)
<img width="470" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/4229e5d7-1ba9-4978-9228-f5155b504577">
<img width="298" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/5b483aaf-31ed-4bf5-b83c-6b19aabc475e">

**Comment by Jenefer-Monroe** [comment]
It appears that you have not run the update flows after upgrade. 
Please do note that we now have a setup wizard, the **_CoE Setup and Upgrade Wizard_**, if you boot this after each upgrade it will ensure that the correct flows are on and that the upgrade flows run. 
In this case you are missing emails in the customize emails table. 
Please go make sure these flows are turned on:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6924f9de-d412-41d4-996a-8a3a608498b8)

Then turn on and run this flow: **_Admin | Sync Template v3 (Call Updates)_**

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by JanetK12** [comment]
Hello @Jenefer-Monroe!
Could I ask the question a little bit out of the topic? Am I understanding that right, that all these flows need to be turned on in order to use the CoE Setup and Upgrade Wizard app?

<img width="790" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/f63ea67a-8fc8-46b6-93b5-e687f3931928">
 because I receive this error while opening the app, and I checked that all these flows are turned off, so I assume that is because of that.
 
<img width="852" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/b6d93e94-8b10-41f0-9b2a-93fb60199a18">

**Comment by Jenefer-Monroe** [comment]
Only these four flows need to be turned on, everything else is turned on by the app itself. 

- SetupWizard>CreateGroup
- SetupWizard>GetCurrentEnvironment
- SetupWizard>GetTenantID
- SetupWizard>GetUserDetails

These should be turned on when you install the kit already as well.
