### ISSUE TITLE
[CoE Starter Kit - QUESTION] CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) - FLOWS

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#6162]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello! We had a question regarding the CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) flow. As this flow is a long running flow which walks the tenant and finds the sharing state of apps, we wanted to ask whether it is possible in the future to create the flow which walks the tenant and finds the sharing state of the FLOWS as well?
Because an OOB CoE starter kit flow does not collect information about the users, whom the flow is shared, although the same information is collected and displayed for apps.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023 - 4.4.2

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
This is on our backlog
https://github.com/microsoft/coe-starter-kit/issues/1083

But due to some other high priority work we've not been able to implement this yet.
