### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by wlee04** [microsoft/coe-starter-kit#6169]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am setting up CoE first time and following this instruction https://learn.microsoft.com/en-us/training/modules/get-started-center-excellence/2-core-components
but when I try to turn on this flow "CLEANUP - Admin | Sync Template v3 (Check Deleted)", I got attached error.
![platform](https://github.com/microsoft/coe-starter-kit/assets/18008091/e679b56d-2431-452c-99d0-daebfd17efc1)
does anyone know how to fix it?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I'm not familiar with that documentation. We recommend that you use the setup wizard to do the installs as it takes care of all these details for you. Or if you want to do it manually, here is our documentation: [Setup inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/92a42a11-be73-4619-81a6-3b5245e1d48c)
