### ISSUE TITLE
[CoE Starter Kit - BUG]: Set Apps Permissions - Objects of users without O365 licenses show as orphans

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#617]
Solution Core 2.1.72
In the app "Set Apps Permissions", in the section "Orphaned App", there is orphaned apps with a real owner.

For example:
This app "Procesado Datos Afiliados" is showed as Orphaned App:
![image](https://user-images.githubusercontent.com/57954993/121680470-e2eee680-cab9-11eb-95f4-20d1ffe3ab5c.png)

In app details the owner is not showed as expected:
![image](https://user-images.githubusercontent.com/57954993/121680585-044fd280-caba-11eb-91d4-2bff835a2aeb.png)

But in the App Settings, the app have assigned a user as owner, and this user is active on our organization:
![image](https://user-images.githubusercontent.com/57954993/121681220-d454ff00-caba-11eb-8fe4-01b8edb60a4f.png)

**Comment by JeneferM-MSFT** [comment]
This is drawn directly from the product, so you may be experiencing a product bug. We've seen a few around caching so its possible its returning the wrong / stale results. I have seen one other person face this, so could you please test something out for me? 

Please load the attached app: [Bug in Get Roles.zip](https://github.com/microsoft/coe-starter-kit/files/6639729/Bug.in.Get.Roles.zip)

And paste in the envt GUID-Name and the app GUID to get the roles, as shown here. Please let me know if you repro the same issue for the same app with this simpler app.
![image](https://user-images.githubusercontent.com/62659043/121715748-7a454100-ca9c-11eb-9570-ad7e39e1ff97.png)

**Comment by albertocaa1317** [comment]
I have an error in the upload:
![image](https://user-images.githubusercontent.com/57954993/121864146-ddcda980-ccfc-11eb-9cc3-f6000a3979f1.png)

Network trace:
Request URL: https://api.bap.microsoft.com/providers/Microsoft.BusinessAppPlatform/environments/e23c629b-9cec-4d86-a02e-5d1d8282360a/listImportOperations/70011c7d-b86a-4f47-95e9-589c47ad98c5?api-version=2016-11-01
Request Method: GET
Status Code: 400 
Remote Address: 10.1.7.183:8080
Referrer Policy: origin

**Comment by JeneferM-MSFT** [comment]
Sorry yes what I provided you was just a zipped MSAPP file (because GitHub wont let me share msapp files directly)

From the PowerApps maker, you will hit File > Open > Browse > select the unzipped msapp file > open

Note that its just a test app so you'll see errors until you fill in the GUIDs/Names. I'm really just wanting to see if you repro with the least logic in the app possible. 

![image](https://user-images.githubusercontent.com/62659043/121896519-9e906000-ccde-11eb-9a69-f2d59d06693b.png)

**Comment by albertocaa1317** [comment]
Set app permissions:
![image](https://user-images.githubusercontent.com/57954993/121901506-bee40d00-cd26-11eb-87a2-b2a421899ed9.png)

App Bug.in.get.roles
![image](https://user-images.githubusercontent.com/57954993/121901342-99ef9a00-cd26-11eb-800e-d860294074c0.png)

**Comment by JeneferM-MSFT** [comment]
thank you. This is helpful! It appears to be a problem with the apps displaying things rather than with the product call. Thats a relief!

**Comment by JeneferM-MSFT** [comment]
Can you please create a test flow which just calls Office 365 Users  to get Alex's identity? I presume he is the a39f.... GUID in the list. We can confirm that with this call
 
![image](https://user-images.githubusercontent.com/62659043/121924522-39963380-ccf9-11eb-894d-c4900dc690a2.png)

**Comment by albertocaa1317** [comment]
The user doesn't exists! :(
![image](https://user-images.githubusercontent.com/57954993/121953612-10f45500-cd5e-11eb-8463-64e888dd75b1.png)

In our AD the user exists, but I confirmed that this user haven't any o365 license. This is the check that I had to do before to open this issue :(

**Comment by JeneferM-MSFT** [comment]
I just went to try and repro and I do not repro. I have users with no licenses, and their presence in the AD makes this call succeed. 
Can you look them up in [Azure](https://portal.azure.com/) and validate that they still exist there?

**Comment by albertocaa1317** [comment]
Hi @JeneferM-MSFT,
you have reason, the user does't exists in our AzureAD. It may a sync error between AAD and onpremAD, because I see the user in the Active Directory Administration Center.
Apologize for don't check this point :(

**Comment by JeneferM-MSFT** [comment]
Oh wonderful news. Thanks for double checking. I will go ahead and close this then as the issue with the blank entries is local fixed by #621
