### ISSUE TITLE
[CoE Starter Kit - BUG] no inventory flows are listed in CoE Admin Center > CoE Flows page after upgrade to 4.11

### ISSUE THREAD

**Issue by js9331** [microsoft/coe-starter-kit#6170]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After upgrading to 4.11 the list of flows on CoE Admin Command Center app > CoE Flows page does not include many of the CoE flows, and specifically does not list the inventory flows.

![admin_sync_flows_not-in-list](https://github.com/microsoft/coe-starter-kit/assets/35241782/ce47ce06-a42f-4549-95d0-7736ef179c79)

### Expected Behavior

The inventory flows show in the list so that we can easily monitor for unmanaged layers on all inventory flows in one place.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Log into environment
2. Open CoE Command Center app
3. Navigate to CoE Flows page
4. Review list of flows

### Anything else?

We use dev/test/prod environments for CoE and process updates in that order. This issue did not show up in our dev and test environments, just in prod, but I don't know what to check since all 3 environments are maintained in the same way (i.e. only deployment of managed solutions from github)

**Comment by Jenefer-Monroe** [comment]
Do you use the Setup Wizard when you are donig upgrades? It's highly recommended as it ensures the required flows get turned on and run. 

I dont know what you upgraded from but my guess is the metadata flows werent run, and so you arent seeing the new flows (we replaced some and renamed others)

Please go make sure these flows are turned on:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6924f9de-d412-41d4-996a-8a3a608498b8)

Then turn on and run this flow: **_Admin | Sync Template v3 (Call Updates)_**

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by js9331** [comment]
So, I did have those flows enabled? And, yes, using the Setup Wizard, but none of the setup flows show up their either: 
![image](https://github.com/microsoft/coe-starter-kit/assets/35241782/6f08a27c-a948-4f1a-a77a-21e8070fe566)
