### ISSUE TITLE
[CoE Starter Kit - Feature]: Add Date Filters to Pages in Power BI Report

### ISSUE THREAD

**Issue by AllyThorne** [microsoft/coe-starter-kit#6171]
### Is your feature request related to a problem? Please describe.

Is it possible to add date filters to the pages of the Power BI Report so that we can review activity within specific time periods aligned with our adoption activities. 

### Describe the solution you'd like

Ideally, we would like to review the data on the dashboards for specific time periods and we have had to add these in manually on to the dashboards for end users.

**Comment by Jenefer-Monroe** [comment]
Do you mean for the date the item was created?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
