### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Logs Version 3.4

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#6173]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

My environment is set up to maintain the old custom connector methodology. Am I supposed to import the Audit Log ver 3.4 solution?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
No, you have installed the New audit log solutions, those are now "local copies" for you, we will no longer be shipping the CC or the Audit Logs solutions and you will not need to install anything for those going forward.
