### ISSUE TITLE
[CoE Starter Kit - QUESTION] Limitation of managing Power Automate Desktop flows on the tenant

### ISSUE THREAD

**Issue by VasilinaMaroz** [microsoft/coe-starter-kit#6175]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We faced a limitation when planning a housekeeping process for PAD flows on the tenant. We have the same process for Cloud flows. But the next limitations make it impossible to create the same process for PAD: 
1) The PAD runs are created in Dataverse only for flows which are created using the license. Without the license, runs are not recorded at all. 
2) We can't get the list of actions which are used in the flow. 
3) We don't have a status for them to see whether they are premium or not. 
4) For getting details about cloud flows we can use flow actions (i.e. a lot of actions in groups ‘Power Automate Management’ and ‘Power Automate for Admins’). But there are no such actions for Power Automate Desktop. That means that we can't make a clean up process on the tenant and create a bulk deletion of the flows which are not needed any more. 

Is there any way or workaround Microsoft can suggest to create a housekeeping process for PAD? 
Is it in the roadmap? 
Or what should we do if my organization wants to use the PAD flows, but there is no way to manage them?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. There are several limitation in the CoE Starter Kit with gathering Desktop Flows due to some tooling limitations in our architecture, but the good news is that we do have an entire kit and small team devoted to Desktop Flows
The recommendation is to use that tooling and team for deep questions around this feature area. 
https://learn.microsoft.com/power-automate/guidance/automation-kit/overview/introduction

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
