### ISSUE TITLE
[CoE Starter Kit - BUG] Blank Error when attempting to Edit "App Catalog" (Core components solution)

### ISSUE THREAD

**Issue by GeeLau8** [microsoft/coe-starter-kit#6180]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Blank Error message when attempting to Edit "App Catalog" model driven app. 

<img width="677" alt="App Catalog Error" src="https://github.com/microsoft/coe-starter-kit/assets/140720191/567c1a6f-cd1e-47e2-8304-3532f6378192">

### Expected Behavior

Expected to access app designer to edit the "App Catalog" model driven app. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

App Catalog

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Log into make.powerapps, select environment with CoE Starter Kit.
2. My Apps > App Catalog
3. Click Edit
4. Blank Error message and cannot proceed any further. 

<img width="677" alt="App Catalog Error" src="https://github.com/microsoft/coe-starter-kit/assets/140720191/8dbc75a3-18bd-4f57-aa0b-dced9d58c5e9">

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
