### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Environment Properties) Limit Issue

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6184]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

 Admin | Sync Template v3 (Environment Properties) is failing due to hitting action limits. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/c08779e6-ec75-4b00-8bd4-66d70c0d6553)

### Expected Behavior

it should run

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Environment Properties)

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

It should work.

**Comment by Jenefer-Monroe** [comment]
Dupe to https://github.com/microsoft/coe-starter-kit/issues/6088
