### ISSUE TITLE
[CoE Starter Kit - Feature]: Table to log ideas from maker assessment

### ISSUE THREAD

**Issue by thso77** [microsoft/coe-starter-kit#6185]
### Is your feature request related to a problem? Please describe.

Currently when a maker goes through the Maker Assessment in the Nurture Components, they are prompted to send an email to an admin. This is great, but it doesn't log any of the submissions or provide the admins with a queue of ideas.

### Describe the solution you'd like

I'd like a submit button added that will add their submission to a table, therefore providing a backlog of project ideas.

### Describe alternatives you've considered

We have developed our own "Ideas App", where makers can submit an idea. This then gets added to our queue. I'd like to see this incorporated into the Nurture Components.

**Comment by Jenefer-Monroe** [comment]
Please see the [Innovation Backlog](https://learn.microsoft.com/power-platform/guidance/coe/use-innovationbacklog) solution, that is our attempt at an ideas table. 
Its also slated for an upgrade (it was made before custom pages, creator kit, etc features were available)

**Comment by thso77** [comment]
Awesome thanks Jenefer... can I ask what is the purpose of the Maker Assessment if the Innovation Backlog is meant to gather Ideas?

**Comment by Jenefer-Monroe** [comment]
Happy to help. 
Its to determine if the user's idea will require additonal needs like premium licenses, database capacity, etc. And then email asking for these resources.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
