### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Ai Models) Fails not finding id

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6186]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

[CoE Starter Kit - BUG] Admin | Sync Template v3 (Ai Models) Fails not finding id. I have verified all child, sync and cleanup flows to be on. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/b41ae350-1d70-4ca7-9ca6-7500e6b0b136)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/f20e7b00-fb9c-48a0-b3f9-873114113b26)

### Expected Behavior

it should work

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Ai Models)

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
That is not the terminating failure, that is a caught failure as you can see here. We use it to determine if the object is already in inventory, in this case its not and so it sets the variable IsNewToCoE to true 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/917162e6-5927-4c52-8cf4-382a46d97102)

You will need to go deeper into the flow to find the terminating failure.

**Comment by nasilvae** [comment]
> That is not the terminating failure, that is a caught failure as you can see here. We use it to determine if the object is already in inventory, in this case its not and so it sets the variable IsNewToCoE to true ![image](https://user-images.githubusercontent.com/89584709/256589745-917162e6-5927-4c52-8cf4-382a46d97102.png)
> 
> You will need to go deeper into the flow to find the terminating failure.

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/5d63a268-f5e4-4b09-8976-6df27efbe0f4)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/390039e5-f402-4bb8-a46f-b1aaeb8d2b8e)

**Comment by Jenefer-Monroe** [comment]
The error says that the child flow is not turned on. 
Can you please check? If it is now, rerun and see if it passes. Perhaps this ran before you turned it on.

**Comment by Jenefer-Monroe** [comment]
yep seems like it ran before you turned all the flows on then.

**Comment by nasilvae** [comment]
> yep seems like it ran before you turned all the flows on then.

gotcha that makes sense. Thank you.
