### ISSUE TITLE
[Power Platform communication site template] Unable to install template, returns generic error after connecting

### ISSUE THREAD

**Issue by tomas-andrews99** [microsoft/coe-starter-kit#6188]
### Describe your bug, question or feature ask.

i have downloaded and installed all pre-requisites, successfully connected to the tenant but receive an error message when trying to run the script:

PS C:\WINDOWS\system32> .\Deploy-PowerPlatformHub.ps1
INFO: PnP.PowerShell module is already installed.
INFO: PnP.PowerShell module is up to date.
INFO: Connecting to SharePoint Online
INFO: Connecting to https://XXX-admin.sharepoint.com
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
INFO: Connected to https://XXX-admin.sharepoint.com
ERROR: An error occurred.
ERROR: Deployment of Power Platform Hub failed!

Does anyone have any suggestions on how to get this installed?

thanks!

**Comment by Laskewitz** [comment]
Hi @tomas-andrews99 -

It looks like you haven't updated the variables in the script. Please follow the following instructions and try again:
https://learn.microsoft.com/en-us/power-platform/guidance/adoption/wiki-community#update-the-powershell-script-variables

Thanks!

**Comment by tomas-andrews99** [comment]
thanks for looking into this for me. i have updated the variables in the script, the XXX below have been defined and i still receive the error message
## Set variables for deploying template
$adminTenantName = 'XXX'
$adminURL = 'https://' + $adminTenantName + '-admin.sharepoint.com'
$companyName = 'XXX'
$lcid = 1033
$newSiteURL = 'https://' + $adminTenantName + '.sharepoint.com/sites/powerplatformhub'
$ownerEmail = 'XXX'
$siteTemplate = 'SITEPAGEPUBLISHING#0'
$siteTitle = 'Power Platform Hub'
$timeZone = 2

**Comment by dav1dbailey** [comment]
> when running the script from the directory, with all of the variables updated i receive this error: PS D:\Scripts\PowerPlatformHub> .\Deploy-PowerPlatformHub.ps1 INFO: PnP.PowerShell module is already installed. INFO: PnP.PowerShell module is up to date. INFO: Connecting to SharePoint Online INFO: Connecting to https://XXX-admin.sharepoint.com INFO: Connected to https://XXX-admin.sharepoint.com ERROR: An error occurred. ERROR: Deployment of Power Platform Hub failed!

I am also experiencing this. Gave you managed to resolve?
