### ISSUE TITLE
[CoE Starter Kit - BUG] How to force Inventory flows to run?

### ISSUE THREAD

**Issue by kbirstein** [microsoft/coe-starter-kit#6193]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I often have a critical need to run the cloud Inventory Flows immediately. I used to be able to remove the Delay action on the 
Delay action in the “Admin | Sync Template v3” flow, i.e. the Parent flow that used to run all the other sync flows, but this flow no long exists! There must be some way to force the inventory flows to run. A quick answer would be much appreciated since I'm presenting at a Microsoft conference tomorrow and I need to know if this is possible!

Thanks!

### Expected Behavior

Need to know how to run cloud inventory flows immediately.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin - Sync Template 3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

I need to know how to force cloud inventory flows to run.

### Anything else?

This should be possible if its not!

**Comment by Jenefer-Monroe** [comment]
Hello, the flow was just renamed due to some processing we needed to start doing by name. It is now called **_Admin | Sync Template v3 (Driver)_**

**Comment by kbirstein** [comment]
AH! Thanks so much for the quick response. . .

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
