### ISSUE TITLE
[CoE Starter Kit - QUESTION] Dev/test v Prod envts - is everything the same expect the production environment env-var?

### ISSUE THREAD

**Issue by snl-meg** [microsoft/coe-starter-kit#6194]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am installing a test COE environment. Do the same exact instructions apply as far as turning on flows? I do have the production environment variable set to No but just wondering if the turning on the flows are necessary as well.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Thats correct, setup is exactly the same. Only that env var differentiates the dev/test from prod envts.

**Comment by snl-meg** [comment]
Great, thank you!

Maria

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
