### ISSUE TITLE
[CoE Starter Kit - BUG] Missing records after upgrade (Feb 2023 version)

### ISSUE THREAD

**Issue by rkapofu** [microsoft/coe-starter-kit#6195]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We installed the coe starter kit in November 2022, I've tried to update twice and both times the records stop as of 12/31/2022. The version that I am using from November has 2023 data, but the upgraded versions are not pulling into my test environment for 2023 data. The second upgrade I did I had to fix the custom connector, but even after fixing it, the records are still not updating. 

### Expected Behavior

I expected that with each version installed, the record counts would match to the production environment version.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.53 & 4.3

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid we are not able to assist here with this level of detail. 
I do not recall the state of the kit for those builds (Oct 2022 and Feb 2023) or what might be the difference between them, but we do fix bugs over time so the exact count may vary across builds like that. 
We are releasing a new version of the kit next week, the August 2023 version. You should upgrade to that and then if you find issues with the inventory please do let us know.
