### ISSUE TITLE
[CoE Starter Kit - BUG] Missing Audit Environment Variables

### ISSUE THREAD

**Issue by EgoManiac** [microsoft/coe-starter-kit#6196]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When trying to set up the Audit Logs for the new HTTP connector using the information found here : https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http 
I am missing the environment variables for the the audit settings.

### Expected Behavior

I am expecting to see Variables for the following :
Audit Logs - Audience
Audit Logs - Authority
Audit Logs - ClientID
Audit Logs - Client Secret
Audit Logs - Client Azure Secret

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin - Audit

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open CoE Admin Command Centre as the account who installed the environment.
Go to Environment Variables.
Sort by Schema name or Name
Open Power Automate Admin > Check Solutions, > Default Solutions > Environment Variables.

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/3205464/458f226b-bfa1-4696-a0ae-7269c18458cf)

**Comment by manuelap-msft** [comment]
Hm I don't repo this
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/c8f5accf-9b93-4074-9155-1045e7ffec81)

Is this a clean install or an upgrade?

Can you go to make.powerapps.com > Solutions and take a screenshot of the solutions you see, make sure you expand the Name column so we can fully see the name there as well.
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/7fd68dfa-74c7-4746-a3fd-10523a18c671)

Thank you!

**Comment by EgoManiac** [comment]
Thanks for checking.. it is a brand new clean install.

![image](https://github.com/microsoft/coe-starter-kit/assets/3205464/14d5172f-b149-406c-bce8-1caf01885b52)

**Comment by manuelap-msft** [comment]
Hello,

the Core Components solution shown here is version 4.4.2 which is an older version that does not have these new environment variables yet. The new environment variables for this Audit setup were only introduced with the July version 4.11. You'll have to upgrade to the latest version to see them.

Thank you
Manuela

**Comment by EgoManiac** [comment]
I thought I had downloaded the latest, but evidently not.

Thank you for your spot. I'll upgrade now.

**Comment by EgoManiac** [comment]
sorted
