### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Centre - Republish App is cutting off the message

### ISSUE THREAD

**Issue by FQ365Microsoft** [microsoft/coe-starter-kit#6197]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the Developer compliance centre app, the message is not complete and the link as it says Publish below to mark the tasks is not visible.
<img width="298" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/116768543/4814457a-6d9b-4255-87c0-a582d4d39a24">

### Expected Behavior

The message should be completely visible with the link as needed.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

Developer Compliance Centre

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Open an app in the Developer compliance centre where re-publish is needed.

**Comment by Jenefer-Monroe** [comment]
I dont repro this. We did have a bug where some of the container defaults were off that I fixed a month or so ago, so it may have been that.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
