### ISSUE TITLE
[CoE Starter Kit - BUG] Most of cloud flows cannot be turned on

### ISSUE THREAD

**Issue by ShotaHarita** [microsoft/coe-starter-kit#6198]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have been setting up CoE Starter Kit, based on the info from the link below.
https://learn.microsoft.com/ja-jp/power-platform/guidance/coe/setup-core-components

An error prevents us from turning on most of cloud flows named in the step 'Turn on inventory flows'.

Below is the list of the flows:
----------------------------------
Admin | Sync Template v3 (Ai Models)
Admin | Sync Template v4 (Apps)
Admin | Sync Template v3 (Business Process Flows)
Admin | Sync Template v3 (Connection Identities)
Admin | Sync Template v3 (Custom Connectors)
Admin | Sync Template v3 (Desktop Flow - Runs)
Admin | Sync Template v3 (Desktop flows)
Admin | Sync Template v3 (Environment Properties)
Admin | Sync Template v3 (Flow Action Details)
Admin | Sync Template v4 (Flows)
Admin | Sync Template v3 (Model Driven Apps)
Admin | Sync Template v3 (PVA)
Admin | Sync Template v3 (Solutions)
Admin | Sync Template v3 (Driver)
CLEANUP - Admin | Sync Template v3 (Check Deleted)
CLEANUP - Admin | Sync Template v3 (Delete Bad Data)
CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
CLEANUP - Admin | Sync Template v3 (PVA Usage)
----------------------------------

And the error that comes when we try to turn the flows on says like the following:
----------------------------------
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'List_Ai_Models' of type 'OpenApiConnection' at line '1' and column '3422' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

*¹Item name following "workflow run action" is unique to each flow.
*²Number following "column" is unique to each flow.
*³Except two points mentioned above, all the flows show us the same error message.
----------------------------------

Note: Currently we are using cloud flows to get inventory and telemetry, but are supposed to use data export in prod environment.

Could you please tell us the cause and how to fix this issue?
Thank you for your cooperation in advance.

Best regards,
Shota.H

### Expected Behavior

Any flows listed in 'Turn on inventory flows'  from the Micrsoft public info can be turned on without errors. 
https://learn.microsoft.com/ja-jp/power-platform/guidance/coe/setup-core-components

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin | Sync Template v3; Admin | Sync Template v4; CLEANUP - Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. As test environment, create environment named "TestEnv" with Microsoft account which has the licenses below.

Microsoft Power Automate Free
Microsoft Power Apps Plan 2 Trial
Microsoft 365 E5 Compliance
Microsoft 365 E3

2. Import two solutions "CreatorKitCore" and "Center of Excellence - Core Components".
3. From "Flows" on the left pane, find and select  a flow listed in "Turn on inventory flows" step.
4. Click "Turn on" displayed on the upper position.
5. See error...

**Comment by manuelap-msft** [comment]
Hello. All the flows have this pagination policy. The error indicates that you are using an insufficient or trial license.
Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
 
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites]( https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with).

**Comment by ShotaHarita** [comment]
Well noted. Thank you for your quick reply.
The cause of the error became clear because we are actualy using a trial license.

In case upgrading the license to make this error disappear, which plan must be assigned to a user from the list below? 
We would like to know which licenses are classified as "insufficient".

- Microsoft 365 plans
- Power Apps Plan 1, Per App plans
- Power Automate Plan 1
- Dynamics 365 Team Member
- Microsoft Power Apps for Developer
- Power Apps triggered flows, manual flows, child flows, Power Apps Plan 2, Power Apps per user plan
- Power Automate Plan 2, Power Automate per user, Power Automate per user with Attended RPA plans
Dynamics 365 Enterprise plans, Dynamics 365 Professional plans
- Dynamics 365 non-licensed users, application users, users with special free licenses
- Power Automate per flow plan
- Pay-as-you-go flows, Dynamics in context flows running under service principal

We would be glad if you could get back to us with an additional answer.

Thank you and best regards,
Shota.H

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are not licensing experts and so cannot comment on all of these license types. 
However I can point you to our recommended required licenses here: [CoE licenses](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3e068417-bbaf-48ae-9f2d-dcb40fb23343)

**Comment by ShotaHarita** [comment]
Thank you for the recommendation.
We will proceed with asking for license details through power platform admin center while considering using non-trial license in prod envt.

This case can be closed at this moment. We appreciate all your help.

Kind regards,
Shota.H
