### ISSUE TITLE
[CoE Starter Kit - BUG] Snyc Helper - Get Security Roles Flow getting error and thought this was resolved in May

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6199]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This is the error I get. More than one concurrent Delete requests detected for an Entity c24a2cf5-55dd-ed11-a7c6-001dd80702fd and ObjectTypeCode 10727.

Screenshot of the flow:

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/4a742c76-afcb-41e2-9950-d6f2743b89d5)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Sync Helper - Get Security Roles

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
