### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrading from 4.3 to June 2023 Release

### ISSUE THREAD

**Issue by uzma-fis** [microsoft/coe-starter-kit#6200]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to upgrade my environment which is running 4.3 but I am presented with an error stating "The imported solution and the existing solution must both be managed for upgrade".

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Core Component Upgrade

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Import solution from June 2023 toolkit CenterofExcellenceCoreComponents_4.9_managed

### Anything else?

In another issue I've read someone had this when the solution was years old, but this is a few months out of date. Is there a fix for this without complete reinstall

If re-install is required, can we delete the solution and associated flows to maintain connections OR do we just create a new environment?

**Comment by Jenefer-Monroe** [comment]
I've recently seen this pop up just for normal upgrade errors. You should be offered a spreadsheet to download that will contain a pointer to where your problem lies.

**Comment by uzma-fis** [comment]
Thanks for that, it's a pain in Excel but I have got it! Edited to protect info - I've inherited this set up so I have NO idea what stage of the set up this is! I guess audit?!

User is not authorized to read secrets from '/subscriptions/660a7476-1xxx/resourceGroups/PowerPlatformCOE/providers/Microsoft.KeyVault/vaults/PowerPlatformCoEVault/secrets/CSPPCOE

**Comment by Jenefer-Monroe** [comment]
Got it. Yes it sounds like they use key vault to store secrets for some of the app registrations involved. So you will need to make sure you have permissions to that key vault.  

Browse to key vaults: 
https://portal.azure.com/#view/HubsExtension/BrowseResource/resourceType/Microsoft.KeyVault%2Fvaults

And look for your vault (PowerPlatformCoEVault), click to go in and click access control > View my access
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/23fbfd77-e1e4-46b1-ba38-7c4c6501bf39)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a6edf304-49aa-4ff7-8c3d-d5c1076282bb)

From the name of the vault, it sounds like you should try to get owner access now that you've taken over, but for sure you need these
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/06704e6e-3c13-4fb9-9fc4-d999568089f1)

**Comment by uzma-fis** [comment]
Thanks for that! 
Wonderful help, I will get the admin to provide me permissions and will try again.

**Comment by Jenefer-Monroe** [comment]
Happy to help!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
