### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL Dataflow issue with makers

### ISSUE THREAD

**Issue by KYT9212** [microsoft/coe-starter-kit#6203]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

From 'Makers' dataflow environment API doesn't return 'SYSTEM' as part of maker causing dataflow not to be able to process default environment and MDA.     

### Expected Behavior

'Makers' dataflow include query to add 'SYSTEM' as part of maker. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

CoE BYODL Environments & Model Driven Apps

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Setup Azure DL
2. Setup Data export
3. Run Dataflow starting from Makers -> environment -> MDA

**Comment by manuelap-msft** [comment]
Hello,

you'll have to use the Setup Wizard for the setup of the CoE BYODL integration. That inserts the SYSTEM record in the Maker table. See the note in our docs on this:
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/f395207c-5fa4-4ad5-a34b-dd67def04466)

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
