### ISSUE TITLE
[ALM Accelerator - QUESTION] Parallelism Request

### ISSUE THREAD

**Issue by cajetzer** [microsoft/coe-starter-kit#6204]
### What is your question?

I have configured a project in the ALM Accelerator Admin app, and set up a Profile for the solution in the ALM Accelerator app. Upon an attempt to Commit the solution to the project/repo, I get an error that the export-solution-to-git.yml file is not found. Upon looking at the yml files deployed into the coe-alm-accelerator-templates branch, I do not see the any yml files for the 3 pipelines (delete, export, import) that are expected to be deployed. Am I missing a step or is this a bug?

![image](https://github.com/microsoft/coe-starter-kit/assets/64230564/e5a906b8-6c8f-4026-b959-eea5e041fe8d)
![image](https://github.com/microsoft/coe-starter-kit/assets/64230564/75aff054-189a-4306-b420-d1ec4e7d2b8e)
![image](https://github.com/microsoft/coe-starter-kit/assets/64230564/0f246872-83fc-496e-becf-21234403bba5)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

July 2023 1.0.20230629.1

**Comment by mikefactorial** [comment]
Closing this out for now. Feel free to reopen or open a new issue if you have any other questions or issues.

**Comment by anttipajunen** [comment]
@mikefactorial saw this after a considerable amount of time debugging why the wizard deployment caused my initial commit to fail, just like with @cajetzer. I'd recommend to add a mention of hosted parallelism to docs, just like the deprecated version has:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/cli/alm/maker-setup
