### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by kapoorn21** [microsoft/coe-starter-kit#6205]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

we are encountring an issue with turning on "Flow Admin | Sync Tamplate v3 (call updates)" due to an error massage:

Error:

Turn on failed. Flow client error returned with status code "Badrequest" and details {"error": {"Code" : childflowNeverPublished" 

Upon importing the "CreaterKitCore_1.0.20230421.1_managed", we found that the following child flows are not visible in Core Kite Solution.

1. SYNC HELPER - Apps
2. SYNC HELPER - Cloud Flows

we have also rasied ticket with MS and MS confirmed that there is not workflow in our environment.

Environment ID: e05cfb27-740d-eb11-a814-000d3a1bb7b

### Expected Behavior

we should be able to Turn on the workflow " Flow Admin | Sync Tamplate v3 (call updates)"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.0.20230421.1

### What app or flow are you having the issue with?

Flow Admin | Sync Tamplate v3 (call updates)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Environment ID: e05cfb27-740d-eb11-a814-000d3a1bb7b
2. Turn on failed. Flow client error returned with status code "Badrequest" and details {"error": {"Code" : childflowNeverPublished" 

Upon importing the "CreaterKitCore_1.0.20230421.1_managed", we found that the following child flows are not visible in Core Kite Solution.

1. SYNC HELPER - Apps
2. SYNC HELPER - Cloud Flows

### Anything else?

Turn on failed. Flow client error returned with status code "Badrequest" and details {"error": {"Code" : childflowNeverPublished" 

Upon importing the "CreaterKitCore_1.0.20230421.1_managed", we found that the following child flows are not visible in Core Kite Solution.

1. SYNC HELPER - Apps
2. SYNC HELPER - Cloud Flows

**Comment by Jenefer-Monroe** [comment]
Hello, all the flows you mention are part of CenterofExcellenceCoreComponents not CreatorKitCore.

Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by kapoorn21** [comment]
> Hello, all the flows you mention are part of CenterofExcellenceCoreComponents not CreatorKitCore.
> 
> Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names ![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

Hi Jenefer, Thanks for your quick response.

I am not able to copy paste in Github or might be I am missing the option for copy paste.

It is very hard to write the details in writing. 

Please find the details for your reference.

1. Center of Excellance  - Core Components , version 4.4.2, managed - Yes
2. Creater Kit reference (Canvas) , version 1.0.20221205.1, managed - Yes
3. Creater Kit reference (MDA) , version 1.0.20221205.3, managed - Yes
4. CreaterKit , version 1.0.20230421.1, managed - Yes

sorry, not able to share the screenshot because of copy paste issue with Github. Please let me know how can I do it.

PLease let me know if you need more information.

**Comment by Jenefer-Monroe** [comment]
The flows will be in Center of Excellence - Core Components solution, not Creator Kit. 

That version of Core does contain the Setup Wizard. If you use that it will make sure all these flows get turned on in the correct order without having to do anything manually.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3bb5868-7736-4b5a-b67b-5f7c1048826d)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
