### ISSUE TITLE
[CoE Starter Kit - BUG] Production_CoEDashboard_July2023.pbit - Visualizations Top 10 Active Departaments

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#6206]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
in Production_CoEDashboard_July2023.pbit the visualization "Top 10 Active Departments" from Apps, Cloud Flows, Makers, Desktop Flows, Virtual Agents and Power Apps Portals, are wrong. They are not filtering by Top 10.
For example:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/db96b2c1-e6a3-4cf3-a1ea-711f1c315894)

### Expected Behavior

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/e108138a-2f62-43f0-b4a7-402ffaa1e03c)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

Production_CoEDashboard_July2023.pbit 

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
These were removed from the PBI in their refresh. Plesae take a look when they come out this week and let us know if you still need this visual.

**Comment by Jenefer-Monroe** [comment]
August release is now available.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
