### ISSUE TITLE
[ALM Accelerator - BUG]: GetSolutionSDKSteps.Run failed: Connection not configured for this service.

### ISSUE THREAD

**Issue by perssonkasia** [microsoft/coe-starter-kit#6207]
### Describe the issue

Hi, 
I'm having trouble with "Configurate Deployment Settings" in app, I receive error: "Error getting solution dependencies: GetSolutionSDKSteps.Run failed: Connection not configured for this service".
Has anyone else encountered this error?

/Kasia

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230629.1

![Error](https://github.com/microsoft/coe-starter-kit/assets/55349153/f0173649-f0c1-42c9-afde-1048d35174a3)

**Comment by mikefactorial** [comment]
@perssonkasia this is always a tough issue to troubleshoot and not related to the ALM Accelerator specifically. Either the connections is having an issue or their is a permissions issue. Have you assigned the appropriate roles to the user? https://github.com/microsoft/coe-starter-kit/issues/4567

**Comment by perssonkasia** [comment]
Hi @mikefactorial, thank you for the comment. The user has got the right permissions. I have made a clean install of ALM in another Environment, everything seems to work there. I suppose it was a configuration error in my custom connector.

**Comment by mikefactorial** [comment]
@perssonkasia thanks for the feedback closing this out for now.
