### ISSUE TITLE
[CoE Starter Kit - QUESTION] Impact of blocking email forwarding and enable cross-tenant isolation

### ISSUE THREAD

**Issue by bdcqr** [microsoft/coe-starter-kit#6209]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, 

I need assistance on how we can determine the impact to our current apps and flows if we enable the two security settings:

1. Disable auto-forwarding of email using Exchange Online rules
2. Enable cross-tenant isolation

In the CoE Admin View model-driven app, there is a tab on the left labelled "Connection Identities". It claims to show cross tenant connection references but most of the items that are listed are within our tenant, not external.

Are there any reports in the CoE toolkit that could help determine the impact of these security changes?

Thanks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Cross tenant report is shown here, perhaps you have the wrong view selected?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eae9c1f5-4ef5-47d1-a690-a94fae606abf)

**Comment by Jenefer-Monroe** [comment]
for this one: Disable auto-forwarding of email using Exchange Online rules

I dont think our kit can help with that one as we only work with the Power Platform automation, not with Exchange rules.

**Comment by bdcqr** [comment]
Hi Jenefer,

I saw this section in the COE. However, what's odd is the connections that are listed are not cross-tenant. The connections and accounts that are used are within our single tenant so I am confused as to what it's showing exactly.

Regards,

Bobby Chow (he/him)
Manager, Enterprise Solutions
QuadReal Property Group
T 604-975-9520
***@***.******@***.***>

**Comment by Jenefer-Monroe** [comment]
We guess locasl tenant based off the admin email you use.

Go to a recent run of this flow for your Default environment, what is selected for localTenantString?

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cca3bf31-eb2e-41e5-a6b6-fb4c83859cf3)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0f14a610-4e0a-4a50-aa81-0ae8340df8da)

**Comment by bdcqr** [comment]
Hi Jenefer,

So, the flow only checks to see if the domain isn't equal to your primary domain (localtenantstring), it doesn't know if this domain is still internal to your O365 tenant, is that correct? This would explain why I am seeing other internal domains in the admin view.

Regards,

Bobby Chow (he/him)
Manager, Enterprise Solutions
QuadReal Property Group
T 604-975-9520
***@***.******@***.***>

**Comment by Jenefer-Monroe** [comment]
it just checks against the admin email you use. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dedad35-1e34-4030-96de-731424b650b9)

**Comment by bdcqr** [comment]
Understood, thanks for clarifying. You can close this help request.

Cheers,

Bobby Chow (he/him)
Manager, Enterprise Solutions
QuadReal Property Group
T 604-975-9520
***@***.******@***.***>

**Comment by Jenefer-Monroe** [comment]
Thank you!
