### ISSUE TITLE
[CoE Starter Kit - BUG] 'PowerApps App' and 'Flow' table both have inconsistent numbers

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#6210]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

For the majority of the day, Both these tables have a fraction of the correct number of Apps and Flows. For some parts of the day the total is correct. This has been ongoing for months. We have a large tenant, and using datalake. What is causing this and is there a fix ? its preventing me from effectively doing inactivity notifications and general inventories
Same result both from PP Admin View and viewing tables from make.powerapps.com

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

core components 4.4.1

### What app or flow are you having the issue with?

Not aware of errors. Just the counts are very low

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. go to our CoE environment in make.powerapps - then click Tables and locate either table. remove all filters
2. Or view this from PP Admin View

**Comment by Jenefer-Monroe** [comment]
I believe you were hit by this bug for which we released a hotfix https://github.com/microsoft/coe-starter-kit/issues/5331 back in May. 
We are releasing the August release tomorrow, I recommend you upgrade to that build.

**Comment by jimpreston29** [comment]
Hi, the 'CLEANUP HELPER - Check Deleted' flows have the hotifx described - but there were no runs.
I believe they are triggered by CLEANUP - Admin | Sync Template v3 (Check Deleted) - that had not run, so i ran this flow - it was successful but it did not trigger CLEANUP HELPER - Check Deleted (Cloud Flows) , or, CLEANUP HELPER - Check Deleted (Canvas Apps)

I ran the flow that you zipped but it does not see any flows in the deleted table that eq deleted

do you still think Aug release will fix this ?

**Comment by Jenefer-Monroe** [comment]
I have not heard about these problems in more recent releases, so yes I do believe an upgrade will fix. We are shipping August later today!

**Comment by Jenefer-Monroe** [comment]
August release is available, please try that out and post an issue if you have issues with your inventory. 
thank you
