### ISSUE TITLE
[CoE Starter Kit - QUESTION] Compliance Request Question

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6211]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is this an accumulative compliance evaluation or are they separated meaning they find apps that are shared with more than 1 group and shared with more than 20 users then they would get notified to complete the compliance request?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

May Release

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
No its an OR, so: shared with lots of people OR launched a lot times OR ...

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
