### ISSUE TITLE
Unable to see the apps created in recent times

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#6212]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to see few apps which are there created last month. The version that is being shown is also the older version. 
All the Dataflows are running fine.
![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/d8107af6-4c9f-4ae8-b452-60da2dbb94fa)

![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/8562cd90-02c2-4315-b05d-89130fa6cd58)

### Expected Behavior

App should be visible.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Sync of apps

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Have you [configured the scheduled refresh](https://learn.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh) for the PBI? 

See [Configure the Production and Governance Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-production-and-governance-power-bi-dashboard)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3c014f66-a2b8-4404-8a93-61f79b8f345b)

**Comment by ALSPowerPlatform** [comment]
Yes it is already configured. Please refer below images
![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/e5e739bd-e48f-45d1-b8a0-0a08aab8eb8c)
![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/1d711f7f-2d32-483e-89f6-2532748734c3)

**Comment by Jenefer-Monroe** [comment]
Can you please go see if they are available in the Datalake container?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
