### ISSUE TITLE
[CoE Starter Kit - ADLS

### ISSUE THREAD

**Issue by monicasv** [microsoft/coe-starter-kit#6215]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Would like more info around the data export to ADLS. The feature has been in preview for a while - is there a GA date set that can be shared? 

On the info page for the setup it mentions Network Connectivity, Network Access: Enable public access from all networks must be selected". We are not able to do this at our organization - not even in our DEV tenant. Is there a more segregated approach we can take to the network? [https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics](url)
![image](https://github.com/microsoft/coe-starter-kit/assets/90351601/f1cfa8a9-34a0-466c-8251-f004c1e0a178)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid our kit is just a consumer of this product feature and so questions like these need to be directed to the product team.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
