### ISSUE TITLE
[CoE Starter Kit - QUESTION] COE Maker Command Center

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#6217]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

HI,

Installed latest version (August 2023) of COE Starter kit. When i click on Release Wave Notes it is giving an error.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/9ff1e1a2-78ee-47b2-9ff8-04cce70a2833)

Thank You

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 19th 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Thats strange, I dont repro this. Was the upgrade complete when you tried? Or were you given the "new version of app" notice at the top?

**Comment by lingutla123** [comment]
yes. The upgrade completed.

**Comment by Jenefer-Monroe** [comment]
Can you refresh the page? The custom page is definately in there.

**Comment by lingutla123** [comment]
Before the core components version 11 was not deleted. After some time it is gone. Now i can see.

**Comment by Jenefer-Monroe** [comment]
wonderful, thank you for letting us know!
