### ISSUE TITLE
[CoE Starter Kit - QUESTION] Customized email

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#6218]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

Which one is the Customized email added in August release?

This is related to Issue# 5864

Thank you.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
It's these two here, you wont see them until you upgrade Governance solution and run the upgrade flows.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5ed06ee1-3efe-4aeb-85bf-bbf62ddded09)

**Comment by lingutla123** [comment]
What are the upgrade flows? Admin | Sync Template V3 (driver) is this upgrade flow?

**Comment by lingutla123** [comment]
I can see them now.

Thank You.
