### ISSUE TITLE
[Power Platform communication site template] Quick Launch + Title Issue

### ISSUE THREAD

**Issue by jt-azdhs** [microsoft/coe-starter-kit#6219]
### Upon creation, title and top-side navigation is missing. Replicated twice.

<img width="590" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/141270301/a6c8f074-9e14-4ff0-bccb-68a20355c118">

Files are all present however, in site pages and events.

**Comment by Laskewitz** [comment]
@jt-azdhs can you turn the navigation off and on again? That should fix it.

**Comment by Laskewitz** [comment]
@jt-azdhs - It should work like this:

Select the gear icon at the top right and select `change the look`:

<img width="1912" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/3766843/5f754e60-2122-4ff2-b287-19eeb700fec9">

Select navigation:

<img width="1912" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/3766843/19fda8c4-3799-4d6c-826b-ce353a74d630">

Make sure the `site navigation visibility` is on and select `Save`:

<img width="1912" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/3766843/92244300-6c43-4f49-8ff5-267e19423f57">

You might need to turn it off, save it, and turn it on and save it again. 

Let me know if that works!
