### ISSUE TITLE
[CoE Starter Kit - BUG] No data is appearing in my Power BI report

### ISSUE THREAD

**Issue by jackmicrosoft** [microsoft/coe-starter-kit#6221]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I load the CoE Production Power BI report for the first time after successfully installing the CoE Starter Kit in my environment, no data is appearing in my report. I am logged in with the same account and am using the same environment URL. When I check the Table view, no data is appearing there. The refresh window doesn't show any errors - it successfully finishes. Please help!

### Expected Behavior

There should be data

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

Production_CoEDashboard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
There are some built in delays in the sync flows. Most people need to wait a day to start seeing data roll in after first install. 
Please check back after ~24 hours to see if you have your data.

**Comment by jackmicrosoft** [comment]
> There are some built in delays in the sync flows. Most people need to wait a day to start seeing data roll in after first install. Please check back after ~24 hours to see if you have your data.

Hi Jenefer, unfortunately it's not as simple as that - this has been happening for a week now and I've refreshed multiple times.

**Comment by Jenefer-Monroe** [comment]
Have you run through the setup wizard to get all the flows running? 
If so, plesae take a look at this flow and let me know if its passing: Admin | Sync Template v3 (Driver)

**Comment by jackmicrosoft** [comment]
That was it! Thanks Jenefer, the flow was disabled as soon as I enabled it - it started working.

You're a lifesaver!


Thanks,

Jack McCardel  (He/Him)

SharePoint and Power Platform Developer

MᶜConnell Dowell

M: +61 491 332 744

This email, including any attachments, is confidential and may be privileged. If you are not the intended recipient please notify the sender immediately, and please delete it; you should not copy it or use it for any purpose or disclose its contents to any other person. We may collect personal information in the course of our interactions with you. For further information please see our privacy collection notice available on our website.

________________________________

**Comment by Jenefer-Monroe** [comment]
Great to hear. I'll go ahead and close this out then, please let us know if you have other issues int he future
