### ISSUE TITLE
[ALM Accelerator - BUG]: Deploy pipelines are not getting created automatically after Commit

### ISSUE THREAD

**Issue by pvarma8** [microsoft/coe-starter-kit#6222]
### Describe the issue

I have configured ALM accelerator as per the documentation. 

I am able to create profiles on ALM app and configure deployment settings. The moment we commit the solution to profile branch or developer branch, the export solution to git pipelines is running fine and the solution is getting exported to git and Solution branch is getting created with deploy pipelines .Yml files.

![image](https://github.com/microsoft/coe-starter-kit/assets/46042294/7808b4ed-1f35-48a3-a378-bf2ddf6a558a)

![image](https://github.com/microsoft/coe-starter-kit/assets/46042294/6225be8e-7007-4769-8573-6948341521dd)

But no Deploy pipelines are getting created under pipelines. Please find as per the below screenshot.

![image](https://github.com/microsoft/coe-starter-kit/assets/46042294/9ae13038-d8c6-48e3-af3c-ec37bbb41d8a)

I don't see any failure or error message neither in the export solution to git pipeline nor in ALM App.

Please help me in identifying the issue.

Also in our organization we are maintaining only 3 environments in ALM, we don't have validation environment. 

During the deployment profile selection/ environment selection, I have provided Test environment in both validation and test.

![image](https://github.com/microsoft/coe-starter-kit/assets/46042294/9df95bd4-7411-472e-b8a1-7452f11f6925)

Am I doing correct?, please help me on how to avoid validation if I am doing wrong.

I could see that Build template path is blank in Deployment step in Admin app.

![image](https://github.com/microsoft/coe-starter-kit/assets/46042294/5ee45e9a-cb8b-4729-9fe6-f79651fc389c)

### Expected Behavior

Deploy pipelines should get created automatically, to deploy solutions to target environments after approving pull request.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20230629.1

**Comment by neelbasak08** [comment]
Hello @pvarma8 ! I would be keenly interested to know how you resolved this issue in COE ALM accelerator. Even I don't see the Deploy pipelines should get created automatically. And I don't see the deployment happening after approving the pull request.. Any direction would be helpful
