### ISSUE TITLE
[CoE Starter Kit - BUG] Connection break when I update

### ISSUE THREAD

**Issue by pablocarceller** [microsoft/coe-starter-kit#6223]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

All the flow disconnect when customer update the CoE

When I update the CoE, they need to remove the managed layer for almost all the flows, then the flow turn off.  When they update it, they need to turn on all the flows and recreate the connections

If they tried without this, they received the error messaged of failed connection 

Turn on failed. Flow client error returned with status code "NotFound" and details "{"error":{"code":"AzureResourceManagerRequestFailed","message":"Request to Azure Resource Manager failed with error: '{\"Code\":\"NotFound\",\"Message\":\"Cannot find connection with name shared-commondataser-3c89407d-fed0-4b8a-8e1b-b150-fda62fa5 .\",\"Target\":null,\"Details\":[{\"Message\":\"Cannot find connection with name shared-commondataser-3c89407d-fed0-4b8a-8e1b-b150-fda62fa5 .\"},{\"Code\":\"NotFound\"},{\"ErrorEntity\":{\"ExtendedCode\":\"14003\",\"MessageTemplate\":\"Cannot find connection with name {0} .\",\"Parameters\":[\"shared-commondataser-3c89407d-fed0-4b8a-8e1b-b150-fda62fa5\"],\"Code\":\"NotFound\",\"Message\":\"Cannot find connection with name shared-commondataser-3c89407d-fed0-4b8a-8e1b-b150-fda62fa5 .\"}}],\"Innererror\":null}'."}}".

 I use an application user for the connection with dataverse and my user for the connection ( can this impact the update, are the any workaround?

 
![7160cb05-1c4e-423e-8d72-d8a142de26aa](https://github.com/microsoft/coe-starter-kit/assets/69342183/0ab58aac-6619-48a8-9918-0723125ed114)
![Untitled picture CoE](https://github.com/microsoft/coe-starter-kit/assets/69342183/41fb4f92-8cac-4ea7-8427-47423f788666)

### Expected Behavior

We able to update the CoE without replicate all the steps and without create layers in all the flows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Update CoE

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Just import the new version of the Center of Excellence

**Comment by Jenefer-Monroe** [comment]
I think the issue here is in who owns the connection references. 
Log in as the identity you are wanting to install the kit, remove all your unmanaged layers etc, get to a clean state in that regard, then go to the default solution > Connection references
If you look through the connection references used for the kit you will likely find them using a connection that looks like a code/guid/something. Change this to be the identity of the user doing the install for all the connection references. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f999fd43-7ae4-43ab-84db-31942889bd23)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
