### ISSUE TITLE
[ALM Accelerator - QUESTION] How to remove validation stage / Environment from ALM

### ISSUE THREAD

**Issue by pvarma8** [microsoft/coe-starter-kit#6226]
### What is your question?

Hi,

In our organization we are using three environments in our Power platform SDLC. We use Development, Test and Production environment and no Validation.

While configuring profiles in ALM Accelerator App, what do I need to select for Validation Environment? And how to avoid validation pipeline running after creating a Pull request or clicking on Deploy solution?

![image](https://github.com/microsoft/coe-starter-kit/assets/46042294/a6017ac2-045b-4fd6-9d6d-0985892cb942)

Please help.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230629.1

**Comment by ahmedsassi2024** [comment]
same problem, i have only dev , test and prod environment , no need validation one, how to change config pipelines to do this ? thank you
