### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Configuration - Excuse 

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#6228]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

If there is a certain environment that we want to completely exclude from the CoE, meaning remove all the environment's apps and flows from the CoE, what steps do we need to take? 

We already excluded from inventory and inactive flows, etc in the Configuration section, but I didn't see the apps and flows getting removed from the PowerApps Apps and Flows table. Also, we are able to exclude out of the inactivity and compliance flow; however, would it also be excused from the orphaned flows (Request Orphaned Objects Reassigned)? If so, how do we do it? 

Please advise. Thank you! 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

Power Platform Admin View 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We do have this feature available: [Setting up CoE for a subset of environments](https://learn.microsoft.com/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments)
Hope that is helpful.
