### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Helper - Cloud Flows incorrect character expected error

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6231]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/bf27dda8-db95-4b92-88f3-eb3eb45d6269)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/337f9b8a-f59f-4ef3-b4b2-2fd671d5309a)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Sync Helper - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Is there more information than that if you hit show raw output? I dont know what its referencing and have never seen this failure before.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
