### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Platform Admin View app: environment actual size

### ISSUE THREAD

**Issue by dchrist27** [microsoft/coe-starter-kit#6232]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When I view capacity of a production environment (without dataverse) I see that the actual size is zero.   Is this by design because I know that MSFT requires 1GB of database capacity to create a production environment (with or without a dataverse bound to it).

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

Power Platform Admin view

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Can you please show me where you are viewing the capacity? A screenshot would be great.

**Comment by dchrist27** [comment]
I am within Power Platform Admin View app

![image](https://github.com/microsoft/coe-starter-kit/assets/52799471/2ba60069-a1e1-45a8-9523-5312d17d40a9)

**Comment by Jenefer-Monroe** [comment]
Got it thank you, will wait till the area expert is back next week.

**Comment by manuelap-msft** [comment]
Hello,

thank you for your patience! 

Are all your environments showing as 0 capacity, or just some of them?

This information is set in the **Admin | Sync Template v3 (Environment Properties)** - can you open the details page of this flow, select Edit columns under Run history and add the admin_environmentid and admin_displayname to the columns
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/58f7793b-12b0-4b16-8fd4-3a07514f2157) 

Once you have that, find your environment in the run list and select the run to debug it
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/709c5a05-9852-4a77-b94d-b4061b3bac0e)

Look for this scope and select Click to download under Outputs
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/b435e74b-1965-4ac8-a44a-e50db8643a56)

This is a List of all environments, again search for your environment in the JSON file and check if it contains this capacity information - what does it say there? Is capacity listed there accurately?

If that looks okay so far check the scope where the capacity is updated in the Dataverse table - can you look through that information and see any issues there? 
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/f097c84c-9198-448a-adb9-1c0b85fff989)

![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/fe034f0b-5e0a-4af5-841e-28e7499976cd)

**Comment by dchrist27** [comment]
No...not all the environments are experiencing the issue.  It's only happening to a few production environments.

This is what I see in the JSON for the 'FSM Users' environment.

"id": "/providers/Microsoft.BusinessAppPlatform/scopes/admin/environments/fdc3cfeb-567d-41c6-b5c7-4882ac71b82b",
    "type": "Microsoft.BusinessAppPlatform/scopes/environments",
    "location": "unitedstates",
    "name": "fdc3cfeb-567d-41c6-b5c7-4882ac71b82b",
    "properties": {
      "tenantId": (removed)
      "azureRegion": "westus",
      "displayName": "FSM Users",
      "createdTime": "2020-06-23T20:49:45.3419914Z",
      "createdBy": {
        "id": "0c4ba227-8483-4a3a-892f-52ab7283d8ea",
        "displayName": "CS O365 Admin",
        "email": "O365admin@northwestern.edu",
        "type": "User",
        "tenantId": (removed)
        "userPrincipalName": "svc.o365admin@ads.northwestern.edu"
      },
      "lastModifiedTime": "2020-06-23T20:49:45.3419914Z",
      "lastModifiedBy": {
        "id": "0c4ba227-8483-4a3a-892f-52ab7283d8ea",
        "displayName": "CS O365 Admin",
        "email": "O365admin@northwestern.edu",
        "type": "User",
        "tenantId": (removed)
        "userPrincipalName": "svc.o365admin@ads.northwestern.edu"
      },
      "provisioningState": "Succeeded",
      "creationType": "User",
      "environmentSku": "Production",
      "isDefault": false,
      "capacity": [
        {
          "capacityType": "Database",
          "actualConsumption": 0,
          "ratedConsumption": 1024,
          "capacityUnit": "MB",
          "updatedOn": "0001-01-01T00:00:00Z"
        },
        {
          "capacityType": "File",
          "actualConsumption": 0,
          "ratedConsumption": 0,
          "capacityUnit": "MB",
          "updatedOn": "0001-01-01T00:00:00Z"
        },
        {
          "capacityType": "Log",
          "actualConsumption": 0,
          "ratedConsumption": 0,
          "capacityUnit": "MB",
          "updatedOn": "0001-01-01T00:00:00Z"


If this helps this is what I see in the PowerBI Dashboard.

![image](https://github.com/microsoft/coe-starter-kit/assets/52799471/27f5b3ea-2c03-43df-be67-57dcbe204bda)

Now if I look in Power Platform Admin under Resources | Capacity...I see 1GB for the database.

![image](https://github.com/microsoft/coe-starter-kit/assets/52799471/93bc6490-d028-4810-a61c-451b079ad35b)

**Comment by manuelap-msft** [comment]
Hello,

thanks for sharing the details!

Each environment has actual and rated consumption - which you can see here. Your rated consumption for this environment is 1 GB (1024 MB) but your actual consumption is 0 GB (that means no Dataverse capacity is consumed). 

{
"capacityType": "Database",
"actualConsumption": 0,
"ratedConsumption": 1024,
"capacityUnit": "MB",
"updatedOn": "0001-01-01T00:00:00Z"
}

We use actual consumption in our reporting, so you can easily identify empty environments where no Dataverse capacity is consumed by anything "you've created". The rated consumption represents just the capacity the environment takes up upon creation (the 1 GB, as you mentioned earlier). 

So both the CoE kit and PPAC are correct, they're just reporting on different consumptions. 

Hope that makes sense,
Manuela

**Comment by dchrist27** [comment]
It does.   But I have a related question.   Is it possible to track rated consumption or will it always be 1GB regardless of the total number of apps and flows saved to that environment?

**Comment by manuelap-msft** [comment]
We do write the Rated Consumption back to the Dataverse table, we just don't surface it in the report.

If you do want to report on it, you can add it - if you look at the Environment Capacity table, the Rated Consumption is available as a field there
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/0c8d4de9-a385-4b0b-b4de-b0311cf7eb7f)

From my analysis of this in our own tenant it looks like

- For Production and Sandbox environments that have apps/flows/data, actual and rated consumption are the same. 
   ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/21dcec3e-b495-4aa1-98ed-42c349aaf22d)
- For Production and Sandbox environments that have no apps/flows/data (empty environments), actual consumption is 0 and rated consumption is 1 GB (what it took to create the environment) 
    ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/3a2921f0-8803-4f5b-9d8a-dd8c62bdd99e)
- For Default (and potentially Teams, Developer) environments, actual consumption is what the apps/flows/data in that environment consume, and rated consumption is 0 GB
    ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/9a0e944c-990a-4404-8faf-32d73d4654b3)


I think the reason for this is that for Production/Sandbox environments, creating them consumes 1 GB capacity that is taken from your overall tenant capacity. For Developer/Default environments, the capacity of creating them does not come from your tenant capacity so that's why it's likely 0. 

Hope that helps,
Manuela

**Comment by dchrist27** [comment]
Here's what I see in the capacity table.

![image](https://github.com/microsoft/coe-starter-kit/assets/52799471/045a9913-28ee-48f0-9c68-5c2590818777)
And in Power Platform Admin view.  So I won't see actual consumption even those these 2 environments have apps/flows?

![image](https://github.com/microsoft/coe-starter-kit/assets/52799471/d51b5e00-56a6-4b97-944a-832742a2ffe8)

**Comment by manuelap-msft** [comment]
I'm not sure I understand the question - the CoE kit just writes to the table what is returned by the connector and from the output you shared, the CoE kit is writing the correct data back to the table. 

If those apps/flows aren't using Dataverse Database capacity then 0 GB is correct. 
If they are using Dataverse Database capacity then the connector incorrectly returns 0 GB and you'll have to raise a support ticket through your regular Microsoft support channels to get this looked at by the engineering team. The CoE kit is just a consumer of the data that is returned by the out of the box connector.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
