### ISSUE TITLE
Unable to Update CoE Core Components Solution

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#6233]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I tried update the CoE Core components to Aug 2023 build. The previous build installed was Jul 2023. When i tried importing the new solution, the system threw this error

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 3 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Deprecated | [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: 6093fa1e-b34c-4dd1-9a75-5a60525a5e95, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5ff18d20b7ec3dbffe_a3e3b, Id: 2a211419-ac83-4f90-bca0-ed262996ee0f, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/20c415d7-bd3d-4bdc-b5a5-1121402b345a)

### Expected Behavior

The solution update should happen smoothly from Jul 2023 to Aug 2023 (Core Components)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Solution Import process is throwing error

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Download CoE starter kit Aug 2023 version
Import Solution - Center of Excellence - Core Components

**Comment by annsarP** [comment]
Hello,
You can find solution to this problem being described here: https://github.com/microsoft/coe-starter-kit/issues/6018.

**Comment by Jenefer-Monroe** [comment]
Hello this is due to the deprecation and removal of the Audit Logs custom connector. Please see https://github.com/microsoft/coe-starter-kit/issues/6018

**Comment by girishuppal** [comment]
Issue Fixed.

Below steps were followed:
------------------------------

1. Manually removed the Core 4.13 component version
2. Updated the App Registration for Audit Logs and changed the permission type from 'Delegated' to 'Application' (for Activity Feed.Read API)
3. Manually removed the Audit Logs solution
4. Re-Imported the Core 4.13 Component

**Comment by Jenefer-Monroe** [comment]
Wonderful news! I'll go ahead and close then.
