### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI loading data error - OLE DB or ODBC error on flows table

### ISSUE THREAD

**Issue by jackpoz** [microsoft/coe-starter-kit#6234]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The August Power BI report "Production_CoEDashboard_August2023" keeps showing errors when trying to refresh the data when opened in Power BI Desktop, making it impossible to publish:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/f4557cce-c216-4376-9294-e095ee201f02)

### Expected Behavior

The data should be loaded

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Production_CoEDashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open Production_CoEDashboard_August2023.pbit
3. Fill the environment address with https:// prefix
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/bea61f73-0fd2-41ff-a49c-d7f9c2e330af)
5. Click "Load" and login if it's the first time
6. Wait for the data to be loaded and see the error

After the initial error, this message bar appears and clicking on "Apply changes" still shows the same error:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/868a700a-22f8-470b-8154-e81d64d3a041)

### Anything else?

The Power Platform solution was updated from 4.11 to 4.13 2 days ago and the wizard setup was ran successfully. Is there any time or flow one has to wait for the dashboard to load correctly ?

**Comment by jackpoz** [comment]
I opened the July 2023 report to check if it still worked and the data refresh reported 3 errors in the Flow table.
The first time I clicked "View errors" it said it couldn't show them, the second time it worked and showed 3 rows with "admin_notmodifiedsincecreated" column as error:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/a9be52b1-c586-4af9-8a7c-be1affd62266)

These rows had somehow a lot of null columns:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/2edb466f-19a3-49e5-9eb8-8aca85ceb3b9)

One of the columns about if the flow was deleted was set to "True". I ran "CLEANUP - Admin | Sync Template v3 (Check Deleted)" and this removed from CoE the 3 flow rows:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/3c4a6f3b-9ed2-4c8c-9301-7372fd8d746b)

After this, the July 2023 report didn't show any error anymore. I retried with August 2023 report and that worked too.

Not sure why the August 2023 report couldn't show which rows errored out in the same way the July 2023 did.

This issue can be closed, letting the maintainer decided if any investigation should be done to improve the error reporting in this case.

**Comment by jackpoz** [comment]
After I was able to publish the August 2023 report, I received another error on Power BI (not desktop) when the dataset is being refreshed:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/c020eed6-cf87-4115-a969-a7436fc34a17)

This looks still a data-specific error but I will have to solve, but some error handling in the report would be nice

**Comment by jackpoz** [comment]
The same Power BI error on column " 'Created on (Month)'" happens on tables "Flows", "Environment" and "Power Virtual Agent bots", reported 1 at a time

**Comment by santiareh** [comment]
I am experiencing the same problem. Were you able to find a workaround this?

**Comment by Jenefer-Monroe** [comment]
If you open the transform and go to the Flows table, casn you see where it breaks? 
We add that calculated column in the spot shown

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/60a4cf47-6b25-4d45-9d0e-7c7cfb753ea0)



![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ec3ebadd-e831-4589-ab58-d68e59540952)

**Comment by santiareh** [comment]
Hey Jenefer, I tried recreating the report and did not experience these issues, I'm not sure what changed but we are good now. Hopefully it is for everyone too.

**Comment by Jenefer-Monroe** [comment]
Well your avatar is certainly spot on for moments like this :) 
Thanks for the update!

**Comment by jackpoz** [comment]
> The same Power BI error on column " 'Created on (Month)'" happens on tables "Flows", "Environment" and "Power Virtual Agent bots", "Desktop Flows", reported 1 at a time

I was not able to fix this. July 2023 report can update the dataset just fine in Power BI "Cloud" , but August 2023 keeps erroring out, even with tables have have 14 rows and "Created on" is never an empty string.

**Comment by Jenefer-Monroe** [comment]
If you open the transform and go to the Flows table, can you see where it breaks? 
We add that calculated column in the spot shown

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/60a4cf47-6b25-4d45-9d0e-7c7cfb753ea0)



![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ec3ebadd-e831-4589-ab58-d68e59540952)

**Comment by bhavikj65** [comment]
I am facing similar issue, tried loading report from May 2023 release and there are no errors. However still unable to get the Aug 2023 report working.

**Comment by bhavikj65** [comment]
Looks like after upgrade it created records in the admin_app table where it only contains admin_appid and remaining all fields are null. Not sure why ""CLEANUP - Admin | Sync Template v3 (Delete Bad Data) flow didn't delete those records.

**Comment by jackpoz** [comment]
@Jenefer-Monroe when opening the report in Power BI Desktop I don't get any error in the "Created on (Month)" column. It works fine as long as I open it locally.
The error I get is after I publish the report online and Power BI tries to refresh the dataset:

![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/778a6efe-6ad6-4115-91fb-58049ea0a703)

**Comment by jackpoz** [comment]
As I get this error on different tables ("Flows", "Environment" and "Power Virtual Agent bots", "Desktop Flows" so far but it changes at every dataset refresh), I checked the smallest table, in my case "Power Virtual Agent bots":
>Processing error:	The following system error occurred: Type mismatch. Unable to convert a value to the data type requested for table 'Power Virtual Agent bots' column 'Created On (Month)'. The data provider was unable to convert the value '' from the source data type 'VT_BSTR' to the expected data type 'VT_DATE'. Please check the column data types in the data model and data source and ensure that the data types are compatible. The command has been canceled.. The exception was raised by the IDbCommand interface. The current operation was cancelled because another operation in the transaction failed. The command has been canceled.. The exception was raised by the IDataReader interface. Please review the error message and provider documentation for further information and corrective action. The command has been canceled.. The exception was raised by the IDataReader interface. Please review the error message and provider documentation for further information and corrective action. Table: Power Virtual Agent bots.
Cluster URI:	WABI-NORTH-EUROPE-redirect.analysis.windows.net

This table has 14 rows in Dataverse, none of which is empty:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/1cc9d446-2a6b-401b-bd1c-ad067abff740)

When opening the dashboard with Power BI Desktop, the table is loaded correctly without any error:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/b055e7f7-3ae5-4d50-81d7-570d59ab07f8)

**Comment by jackpoz** [comment]
All the new "Created On (Month)" column have this formula:
`
= Table.AddColumn(#"Renamed Columns", "Created on (Month)", each Text.Combine({DateTimeZone.ToText([Created On], "MMM"), " ", DateTimeZone.ToText([Created On], "yyyy")}), type text).
`

Notice how the type is `text`.

The column type is visible as "ABC" in the Query Editor:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/2e5af991-a828-4c01-8a9f-667ba00e345f)

In the Data view, the column is defined as `Date`:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/1d6fdc52-da19-4eed-976c-0ae8aaaa99e4)

When publishing the report to Power BI and opening the Data model, it's defined as `Date`:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/541c839b-0c65-479e-beee-d30b879317aa)

I tried changing the formula to `date`, skipping `Text.Combine` and instead just creating a date at the 1st of the month:
`
= Table.AddColumn(#"Renamed Columns", "Created on (Month)", each #date(Date.Year([Created On]), Date.Month([Created On]), 1), type date)
`
After publishing this, the dataset was refreshed successfully:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/eb272802-d0e9-446f-a246-2cd78ab5a368)

The report also still looks good:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/0c549923-eab8-4c15-a90c-5df03550540c)

**Comment by jackpoz** [comment]
While at it, it's better to add a null check to the [Created On] column as that seems to be set to null by some flows, so something like this:
`
each if ([Created On] <> null) then #date(Date.Year([Created On]), Date.Month([Created On]), 1) else null, type date)
`
or anything better (as I'm not really a Power BI developer)

**Comment by manuelap-msft** [comment]
@jackpoz Do you know what Power BI Desktop version you're on? I don't repo this error with the July 2023 version. Thank you! I'm looking into the issue with regards to null values, though I'm not sure how the created date could ever be null.

**Comment by jackpoz** [comment]
Power BI Desktop Version: 2.119.986.0 64-bit (juli 2023), but the dataset refresh issue happens only when publishing it to https://app.powerbi.com .

For the null values, what I have seen is that the rows with null have null in a lot of fields (see the image below) and are rows marked to be deleted by the next "CLEANUP - Admin | Sync Template v3 (Check Deleted)" run. 
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/6534a82b-1a10-4105-9441-e56cf3b8d1ba)

Maybe some flow is trying to set the "Deleted" flag but ends up setting to null everything else ?
This GitHub issue got quite confusing as it's about 2 different issues now, do you want me to create a new one for the "null" issue and keep this for the "convert from string to date" ?

**Comment by manuelap-msft** [comment]
Hello,

no, that's okay - we can track both of them here! I'm hoping to have a new PBIT file with both fixed ready later today. 

Just writing down tasks for me:

- [ ] Update Created on (Month) column on all tables to be of type date (in Transform Data step)
- [ ] Update formulas that rely on Created/Modified Date to handle null values
- [ ] Test publishing and refresh on app.powerbi.com

**Comment by manuelap-msft** [comment]
We've made some changes to the PBIT file and uploaded the new version
https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Production_CoEDashboard_August2023.pbit

Would you be able to test this and let us know if you still experience issues with it? 

Thank you for your help debugging this, and providing the Power BI queries that would resolve it as well!

**Comment by jackpoz** [comment]
Hi, I uploaded the new version and I didn't experience the issue, so it's working good.
I could test the "Flow" case as I have again 3 rows marked as "Deleted" and with "Created On" date null, with "Created On (Month)" also null and not erroring out, so working good:
![image](https://github.com/microsoft/coe-starter-kit/assets/1153754/72ab9277-cb62-487e-9ce6-96b7d0e486c7)

So to me the issue looks solved and can be closed, thanks for the fast update.

**Comment by manuelap-msft** [comment]
Wonderful, that's great news - thanks for confirming this so quickly and helping us debug this!

Here's a little token of our appreciation - sorry, we're many things but graphic designers we're not! It's the thought that counts 😄 
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/3086dc6e-f850-4701-bb33-d3f08688e656)

**Comment by manuelap-msft** [comment]
Fixed with a new PBIT file, that's been updated in the release. Closing out!
