### ISSUE TITLE
[CoE Starter Kit - BUG] Office 365 Management API is not working after upgrade to CoE 4.11

### ISSUE THREAD

**Issue by FlorinVoinea** [microsoft/coe-starter-kit#6236]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After upgrading the CoE
- Core Components from 3.38 to 4.11
- Audit Logs from 2.9 to 3.4
the custom connector "Office 365 Management API" is not working anymore, stopped working.

   

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Office 365 Management API

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Edit the Office 365 Management API custom connector
2. Add Client ID, Client Secret, Refresh URL
3. Click on: "Update connector"
4. Go to 5. Test
5. Select Operation: ListSubscription
6. Add Tenant ID
7. Click on Test operation button
8.  Response: Status 401, "Message": "Authorization has been denied for this request."

**Comment by FlorinVoinea** [comment]
Hi Jenefer. Your recommended links helped me to solve the problem.
Thank you!

**Comment by Jenefer-Monroe** [comment]
Wonderful! thank you for letting me know!
