### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cannot delete CenterofExcellenceCoreComponents_Upgrade because of dependencies.

### ISSUE THREAD

**Issue by annsarP** [microsoft/coe-starter-kit#6237]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello while performing an August upgrade Center of Excellence - Core Components has been uploaded as new solution instead of being an upgrade. Now I have 2 Core Components solutions: CenterofExcellenceCoreComponents and CenterofExcellenceCoreComponents_Upgrade. I performed all steps described in https://github.com/microsoft/coe-starter-kit/issues/6009. I cannot delete CenterofExcellenceCoreComponents_Upgrade because of dependencies. 
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/a3e72fd3-b8ad-42c9-af67-bee5bb1870e8)

All of the dependencies are for custom connector which as I understood won't be used anymore. 
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/16041fb7-51fd-44bd-b370-b3964f68df64)

For sure I missed some steps or done something wrong. Can you guide me on how to solve this and to have only one (the latest) version of Core Components solution? Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023 and August 2023

### What method are you using to get inventory and telemetry?

None

**Comment by annsarP** [comment]
I reviewed https://github.com/microsoft/coe-starter-kit/issues/6018 once again and saw that somebody suggested Applying upgrade. Thanks to that _Upgrade version has disappeared and I was able to import 4.13 as an upgrade:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/34a33223-0984-49d3-8712-b775ac2a6cf4)

But received an error caused by dependencies:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/6d4520ec-07a7-4e64-b4ff-7722c19bc2c6)

And now I have new version of _Upgrade (and by that again two versions of Core Components solution :/)
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/b9ad3256-f0e8-488a-a400-c412511327c8)

**Comment by Jenefer-Monroe** [comment]
Hello. Did you delete the audit logs solution now? 
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by annsarP** [comment]
Hello, yes, I deleted Audit Log solution before trying to upgrade version. Here are all solutions from Power Platform Admin publisher we have currently installed: 
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/2883fcc6-2b2d-4558-b823-aeb554e3acb4)

**Comment by annsarP** [comment]
Ok I found another comment to **delete Office 365 management API connection references from Default Solution** and then custom connector. That worked! :) 
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/e616aeac-18e9-4fd6-bab7-97af5f033677)

**Comment by Jenefer-Monroe** [comment]
Thank you for letting me know what fixed it up for you! That will help me help others!
