### ISSUE TITLE
[CoE Starter Kit - BUG] Issues with Admin | Compliance Details Request eMail Flows

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6238]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Not sure why none of these have ran 

Admin | Compliance Details Request eMail (Chatbots)
Admin | Compliance Details Request eMail (Custom Connectors)
Admin | Compliance Details Request eMail (Desktop Flows)
Admin | Compliance Details Request eMail (Flows)

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/3989cec3-7524-463e-adbc-d58cf3d5e4a5), I get the same thing across the list above

but not this one: 

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/5abdfd08-2d7a-46d2-baea-990c017010f1)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.9

### What app or flow are you having the issue with?

 Admin | Compliance Details Request eMails

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Most objects have no automated detection for initiating a compliance request. 
You manually flag them as needing information from the maker, at which point these flows will be triggered to send the request.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a1a7a796-c101-4f33-b198-3d3ea45909dd)

**Comment by mdphung** [comment]
All the objects here for flows connectors bots none have picked up so in what you are saying we should review and decide what meets a certain criteria then change this flag on those.

**Comment by Jenefer-Monroe** [comment]
Thats correct, we do not have an automated process to detect these objects.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
