### ISSUE TITLE
PBI COE report errors while loading

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#6241]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

 
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/15c54ff1-e6cd-426d-a874-a888d7ca1dea)

We are facing the issue with the PBI report when we try to launch the latest version, we get the above error. 
 
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/4f5439a0-5408-48a3-8d4c-40ba54bbbb6f)

These are the above columns I see in the Makers table. I don’t see any of the flows failing.

Not sure why this is getting. We have only core COE installed and it was working previously. I see only connection identities flow is failing.

Please advice

Thanks

### Expected Behavior

error should not pop out

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

PBI reports

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello this is a new field we added with 4.13 so you will need to upgrade Core in order to use this new PBIT file.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
