### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View Uses Premium API Column not accurate

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6242]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Uses Premium API Column not accurate

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/dfce3e4a-555b-49ad-83e2-46029ffd2c13)

When you open the app inside the view the App Plan Classification field populates. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/254ac419-afe4-496f-98a4-3e6f436fdefe)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Open Report. Filter report by empty fields inside of Uses Premium API column.

**Comment by Jenefer-Monroe** [comment]
These are different fields if you are referencing this
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/800bf5ba-fa4a-4c62-934b-0777c85c7556)

We just collect this directly from the product as shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ba271924-5af0-4b8b-b789-a029171cb297)

And i did just validate that this is coming through as expected
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/78ee80af-079f-48de-b474-b2809c55b178)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/596983da-e6d0-4b9e-811e-4496792c1135)

Perhaps your cases just experienced a bug when they went through inventory, there is a newish flag for canvas apps and flows now and if you set it you will get them re-inventoried next day.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b8065fc3-7f4a-44d7-ad7c-b24e24444776)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
