### ISSUE TITLE
[CoE Starter Kit - BUG] Error turning on 3 of the Admin | Sync Template child flows

### ISSUE THREAD

**Issue by KristenStanley** [microsoft/coe-starter-kit#6243]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I just installed the CoE Core Components updating our CoE from Feb 2023 to June 2023.  When I try to turn on the following flows, I receive an error messge that say, "Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'xxxxx' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

Admin Sync Template v4 (Apps)
Admin Sync Template v3 (Environment Properties)
Admin Sync Template v4 (Flows)
![CoEFlowError](https://github.com/microsoft/coe-starter-kit/assets/108080466/0ab602ad-f481-4989-a888-d28f1552c231)

### Expected Behavior

When I click the button to turn on the flow, I expect the flow to turn on.

I am following the instructions on this site that says Turn on inventory flows > https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

 Admin Sync Template v4 (Apps), Admin Sync Template v3 (Environment Properties), Admin Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1.  Select the flow 
2.  Click Turn on

**Comment by Jenefer-Monroe** [comment]
Hello, we highly recommend you use the Setup Wizard which you will find in Core to do your upgrades as it will take care of things like turning flows on in the correct order and running needed flows to sync up metadata. Please do go give that a try!

If you cannot do that, and generally speaking when you see errors like this, you can check to see what flows are a dependency for another flow like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/59783b63-4299-4b9b-a484-4504a4bec11a)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/74ec6ce7-5600-4e88-93ac-f04b71bb6fb2)

Then you can turn that child flow on and return to this parent.

**Comment by KristenStanley** [comment]
Wow!  Thank you for your speedy response!  You made my day!

Yes, I did use the set up wizard and I love it!  As you can see in the screen shot, I made it past the Run set up flows and Run inventory flows with no problem.  I am also using the CoE documentation as a guide as I go through the update.  When I got to the section that says make sure these flows are turned on, I noticed the flows I listed were not turned on, even though I did use the setup wizard.

Your solution fixed my issue.  I am now able to turn the flows on.  Thank you for your excellent support!  Have a great weekend.
![CoESetupWizard](https://github.com/microsoft/coe-starter-kit/assets/108080466/9be4bb71-8428-4198-9f17-4c2e59d02a4f)

**Comment by Jenefer-Monroe** [comment]
I'm glad to help! 

Please make sure you have the correct setting for this env var, I'm afraid you may have accidently set to BYODL (Data Export) architecture which would explain why these werent turned on for you. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed4779ba-0fb3-4266-856e-a54aa8f31913)

**Comment by KristenStanley** [comment]
Thanks for the tip.  I did check that environment variable and it's set to no.
![InventoryTelEnvVariable](https://github.com/microsoft/coe-starter-kit/assets/108080466/504e7aff-fb82-4459-a421-edb80b8574aa)

**Comment by Jenefer-Monroe** [comment]
oh good. I'm not sure what happened then but sounds like you're good to go now.

**Comment by KristenStanley** [comment]
Yep, all good now!  Again, thank you for your excellent prompt replies!  I was able to continue with the installation without delay.  THANK YOU!

**Comment by Jenefer-Monroe** [comment]
You're most welcome. I'll go ahead and close then but please do return with a new issue if you have other questions in the future.

**Comment by KristenStanley** [comment]
Will do!  Thanks!
