### ISSUE TITLE
[CoE Starter Kit - BUG] Desktop Flow Numbers are significantly lower after update.

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#6244]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Since we updated our CoE Starter Kit version to 4.8 last June 2023, I have noticed that the Desktop Flow Numbers are significantly lower when compared to our previous version.

OLD:
![Old](https://github.com/microsoft/coe-starter-kit/assets/119695189/52bf0e66-cc3d-4903-93a6-ec181d43473e)

NEW:
![New](https://github.com/microsoft/coe-starter-kit/assets/119695189/da2f7bb4-594f-44f9-9e5e-06b825a0cf3b)

### Expected Behavior

Around the same number or even larger than the previous count.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Power Platform CoE Power BI Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open Power Platform CoE
2. Go to "OVERVIEW - Power Automate" Tab
3. Check total Desktop Flows Count.

**Comment by Jenefer-Monroe** [comment]
Can you please go look at the data in the Power Platform Admin View app to see if it looks correct there?

**Comment by Jenefer-Monroe** [comment]
Thank you, can you find a desktop flow where you expect it to be inventoried but its missing? Then we can debug.

**Comment by Jenefer-Monroe** [comment]
ok yes thats unfortunately just a limitation of our platform today. We will be able to resolve this when the new dataverse connector supports dynamic environment selection as we will then be able to select columns and not bring back the giant ones in that table which, for example, hold the whole flow definition. 

That said, there is a dedicated set of folks who work on "Automation CoE" which has a different architecture and therefore does not have this limitaiton. Please see [Overview of the Automation Kit](https://learn.microsoft.com/power-automate/guidance/automation-kit/overview/introduction)
