### ISSUE TITLE
[CoE Starter Kit - BUG] Embedded Power BI manage access app error for Flows

### ISSUE THREAD

**Issue by dspencelink** [microsoft/coe-starter-kit#6246]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I upgraded our CoE toolkit to the August 2023 release and updated the power bi reports.  I also configured the app detail and flow detail to have the embedded app in Power BI.  When I open app details and manage access, the app loads fine and I'm able to apply permissions.  But if I try to manage access on flow details for a flow in the Default environment, it throws 2 errors and won't let me manage access.  This used to work before the upgrade.  It looks like the ID for the default environment shown in the error is missing "Default-" on the beginning of it.  My account is a Power Platform Admin role and I've also tried with a different account with the same role and same error.  I'm certain that everyone in the default environment is an Environment maker.
Error: "PowerAutomateManagement.AdminGetFlow failed: { "error": { "code": "EnvironmentAccessDenied", "message": "You are not permitted to make flows in this 'd6130c51-e1f1-43fa-b6cb-9634098b05a6'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions." } }"
Default Environment ID: Default-d6130c51-e1f1-43fa-b6cb-9634098b05a6
ID shown in the error: d6130c51-e1f1-43fa-b6cb-9634098b05a6
![2023-08-04 14_14_27-Production_CoEDashboard - Power BI](https://github.com/microsoft/coe-starter-kit/assets/133893716/981e8e83-726f-4cee-937c-9f30acdf991a)

### Expected Behavior

I should be able to manage access for Flows in the default environment, just like I could manage access previously and just like I can with the embedded app for power apps.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Power BI report

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Update solution to latest Aug release
2. Update Power BI report (not the Data lake one)
3. embed the app for manage access
4. Go to flow detail and drill through to manage access on a flow in the default environment

**Comment by Jenefer-Monroe** [comment]
Yes it looks like we selected the wrong field when we did the PBI udpates. 
Thanks for posting will fix for Sept.

**Comment by manuelap-msft** [comment]
Thank you! Looks like we brought in the stripped GUID (without Default-) instead of the actual GUID (with Default-) in the PBI which led to this issue. Fixed locally, and we may upload a new version of the PBIT sooner then September due to some other issues with the new version. Will update back here once it's updated!

**Comment by manuelap-msft** [comment]
We've updated the PBIT file to fix this issue, the new file is available here: 
https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Production_CoEDashboard_August2023.pbit

The release has also been updated. 

Thank you,
Manuela
