### ISSUE TITLE
[CoE Starter Kit - QUESTION] Maker Table Update Delay

### ISSUE THREAD

**Issue by javiles1327** [microsoft/coe-starter-kit#6247]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are having an issue with the Maker table taking a longer time than we would like/is expected to update, delaying the sending of the welcome email by 12-24 hours or more.  We see the HELPER - Maker Check flow running multiple times at the same hour/minute, but it seems to be all at once.   We have checked several others that seem to be doing the same and cannot figure out if there is a way to get them to run on a more frequent interval.  
Please advise if there are any other flows that are responsible for/impacting this action and if anything can be done to better serve the needs of our customers requesting these in a more timely manner.

Thank you in advance for your assistance.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Can you please clarify the issue you are raising here? Is the concern that welcome mails dont come as quick as you expect?

**Comment by Jenefer-Monroe** [comment]
The user is added to the maker table when their first item is inventoried. So this process will occur when the inventory flows run. 
Flow triggers are not configurable by env vars to so we cannot make when this happens configurable for you.

**Comment by Jenefer-Monroe** [comment]
That said, the welcome mail should come to the user within 24 hours of them creating their first object.

**Comment by javiles1327** [comment]
thank you so much!  my apologies in the delayed reply, but that gives us enough to be able to communicate back to our customers effectively, and we/they will be able to work with that information

**Comment by Jenefer-Monroe** [comment]
wonderful. thanks for reaching out
