### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs - ContentID returned not being recognized

### ISSUE THREAD

**Issue by NicoleSSmith** [microsoft/coe-starter-kit#6248]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Audit Logs | Sync Audit Logs (V2) is failing. When I navigate to the Flow Instance URL, getting the follow error:
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/95a5125d-18b6-4b0a-a645-c97223b68e47)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of your App Registrations API Permissions? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d204b547-ed03-441e-a794-d4dd56280c2f)

**Comment by NicoleSSmith** [comment]
See API Permissions here:
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/ecf82fee-c150-4191-8998-3a84bc4edf61)

**Comment by Jenefer-Monroe** [comment]
Can you delete that Delegated permission? I think that may conflict.

**Comment by NicoleSSmith** [comment]
I will remove the delegated permission and will re-establish.

Has there been a change to the licensing and role requirements for the HTTP call? Reding through Collect audit logs using an HTTP action - Power Platform | Microsoft Learn<https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables> it has the following steps:
Before you set up the audit log flows

  1.  Microsoft 365 audit log search must be turned on for the audit log connector to work. More information: Turn audit log search on or off<https://learn.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?preserve-view=true&view=o365-worldwide>
  2.  The user identity running the flow must have permission to the audit logs. Minimum permissions for this is described in Before you search the audit logs<https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-search?preserve-view=true&view=o365-worldwide#before-you-search-the-audit-log>.
  3.  Your tenant must have a subscription that supports unified audit logging. More information: Security & Compliance Center availability for business and enterprise plans<https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center>
  4.  A global admin is required to configure the Azure AD app registration.

The Office 365 Management APIs use Azure Active Directory (Azure AD) to provide authentication services that you can use to grant rights for your application to access them.


When you get into the sep 3 link,  instructions state that you need one of the following licenses:

Enterprise Mobility + Security E5/A5, Microsoft 365 E5/A5, Microsoft 365 E5/A5/F5 Security and F5 Security & Compliance, and Microsoft Entra ID Premium Plan 2 provide the rights for a user to benefit from Microsoft Entra ID Governance.

I just want to make sure that nothing is needed before I proceed to re-establish the API permissions.
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Tuesday, August 8, 2023 7:37 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Nicole Smith ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Action 'Get_Azure_Secret' failed (Issue #6248)


Can you delete that Delegated permission? I think that may conflict.

**Comment by Jenefer-Monroe** [comment]
No there is no license change associated with the change for http

**Comment by NicoleSSmith** [comment]
I completely deleted the API permissions and set up a new permission with the type being application:
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/b55458b6-d0fa-42df-90a5-22101e609d20)

I wasn't sure if I needed to, but I created a new client secret under the Microsft 365 Management Application registration.
I placed the client secret value into the enviromental variables in CoE Admin Command center App. 

I canceled all running instances of Admin | Audit Logs | Sync Audit Logs (V2) and turned it off, then back on. I reran the flow, which took several hours. 

The flow has again, failed. See the error message below.
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/74858835-5b48-4a73-93c4-4c7e95f7b56e)

Please advise.

**Comment by Jenefer-Monroe** [comment]
Open the last attempted run for Admin | Audit Logs | Office 365 Management API Subscription
Is the app id correctly ingested here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/97eee119-aae8-4b4e-95f4-2f5e6bd49feb)
Is the secret correctly ingested here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9783b8d9-4ddb-40d7-928f-eeeeb9c1145a)
Does this call fail hence correctly marking the variable as false?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0da62240-6cef-42b5-96fd-6b8bea57cb48)

**Comment by NicoleSSmith** [comment]
These are screenshots from my most recently attempted, but failed run.
Shot one matches:
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/a239a67a-4291-47b5-9eba-d4bfb152666d)

Second part successfully ran:
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/f786a23f-b252-4627-adaf-93122da7ed27)

And the third also looks the same:
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/b57dcc76-2126-4878-9d2f-c7910f638842)

**Comment by NicoleSSmith** [comment]
No. We are an enterprise tenant.

**Comment by Jenefer-Monroe** [comment]
Sorry that meant commercial vs a government tenant (like GCC / DOD / etc)
Sounds like you are.

I'm a little confused on which Audit Log system you are using from looking at the screenshots above. 

There are two solutions at play, the old deprecated one with a custom connector and a new one that uses HTTP. Please take a step back and look at these two, and decide which path you will follow. It's highly recommended that you use HTTP in qhich case you can delete the audit logs solution and no longer have the flow you originally posted about

[Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)
[Collect audit logs using a custom connector (deprecated)](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog)

**Comment by NicoleSSmith** [comment]
We were using a custom connector, but I previously followed the https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http instruction set to set up the HTTP path.
In this step: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http
You turn on the Admin | Audit Logs | Office 365 Management API Subscription flow on and run.
I have opened the flow and verified that the action to start the subscription has passed.
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/d0ea2c77-e458-44fb-88bc-9e91256c60ae)
I see a value of 400, which means the subscription has been successfully enabled in the past.
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/8383ba90-4845-49dc-b3c3-17855f6286b5)
The step after that is to turn on flows. This is the flow that is failing every hour and this is the last step in the instructions.
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/35c966a3-858a-4606-8fd8-f969777d0eb1)

I no longer have the audit log solution installed:
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/b8269c6c-68e0-49cc-8985-84da476fac4a)
I am accessing the flow in the Center of Excellence - Core Components.

**Comment by Jenefer-Monroe** [comment]
oh i see. ok first thing, please run the following flow. If you use the setup wizard for your upgrades this will be done for you: **_Admin | Sync Template v3 (Call Updates)_**

Once that is done, return and we can see what happened further above as well.

**Comment by NicoleSSmith** [comment]
That flow has successfully ran:

![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/7c8a7df6-d8a2-447d-bde8-dff5d185d3ee)

**Comment by NicoleSSmith** [comment]
I reran the failed flow. It gave me the same error in the same spot. 
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/248958fa-cda1-4e9e-b5c0-177101d707d8)
We are using the Client secret and not the Client Azure Secret
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/79748644-c19f-47f9-aa9c-33b8857476c1)

**Comment by Jenefer-Monroe** [comment]
OK we had a bug there. If you paste the following in the place shown
`@{first(outputs('Get_ID_Fail_2')?['body/value'])?['admin_coesolutionmetadataid']}`
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/300f8901-4e55-4d7a-8f7a-8daf244a8592)

Then it will fail here instead which is the expected behavior and then we will need to explore above what caused the failure.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4f85c802-bf31-4703-8113-f33ea445f036)

**Comment by Jenefer-Monroe** [comment]
Once you local fix the above See how many loops you go through there
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f941062a-035e-4746-99bf-f78a720ec2bd)

Walk through the loops, you'll be looking for one that goes down the true path here to increment this variable.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/752bc1d6-74c4-4c8a-b023-6f948112b815)

**Comment by NicoleSSmith** [comment]
I edited the flow in the Update Last Run Fail 2
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/13de8e4f-ad0b-4c27-b5af-1820144ea2ab)
Then I ran the flow and got the matching error as seen here:
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/a4dde837-a957-4486-8345-1fac49a04117)
The BuildVontentSlotArray step only went through one loop and I get the matching increment variable condition is not satisfied message.
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/1ed12935-299e-4c99-b926-5cf175c5bcef)
How should I proceed?

**Comment by NicoleSSmith** [comment]
And editing the flow, created an unmanaged layer. Will this be a problem on the next release?

**Comment by NicoleSSmith** [comment]
Any updates on next steps?

**Comment by Jenefer-Monroe** [comment]
How about this loop? Do you increment it in these? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/26fda12f-a7f4-4d16-a518-c297121d1493)

**Comment by NicoleSSmith** [comment]
Yes. This is what that step looks like
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/95a5125d-18b6-4b0a-a645-c97223b68e47)

**Comment by Jenefer-Monroe** [comment]
Thank you, adding the author of the flow here, hopefully they can help us understand if there is a change we can make.

**Comment by pete-msft** [comment]
@NicoleSSmith Could you please share the output of the GetContentDetails step. It seems that all HTTP calls of the first content slot (1/44) fails, so would like to see what is the error in that step. Can you also check the status of few other GetAndProcessEvents loop steps to see are there more these same errors in that loop

<img width="373" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/120018333/93fe150d-fcf3-497b-b6cd-8d26bbaab55a">

**Comment by NicoleSSmith** [comment]
@pete-msft - This is the output of the GetContentDetails step
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/f578edc7-19e5-4638-96ee-27795b53f29c)
{
  "error": {
    "code": "AF20052",
    "message": "Blob key 20230821140744842016388$20230821140833780017133$audit_general$Audit_General$na0020 in the url is invalid"
  }
It appears as if all of the the GetContentDetails events failed. I scrolled through the first 20 loops and they all have the same error with code AF20052, but with different combinations of Blob keys ending with "$audit_general$Audit_General$na0020 in the url is invalid"

**Comment by pete-msft** [comment]
@NicoleSSmith Blob key (contentId) seems to be correct in format at least. So, is this GCC/DoD tenant? If yes then please double check that "Audit Logs - Audience" and "Audit Logs - Authority" URLs are correct

Just tested in my tenant and here is one contentId which worked compared to one you sent
20230828171604712068871$20230828173205648032977$audit_general$Audit_General$emea9037
20230821140744842016388$20230821140833780017133$audit_general$Audit_General$na0020


Here is similar problem in GCC thought root cause of that error is not solved https://github.com/microsoft/coe-starter-kit/issues/4890#issuecomment-1468092899

**Comment by NicoleSSmith** [comment]
We are not a GCC/DoD tenant. We are an enterprise tenant. The URLs match the "commercial" tenant URLs.

**Comment by NicoleSSmith** [comment]
The first few seem to match
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/e5cc89c2-0b77-43c8-b874-1f9a70d13f66)
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/94b0ef70-6271-4a82-9818-96fa87ddcc96)

![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/5dcecf74-a5cd-4115-bf61-c6cd3f084b4c)
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/549cf60c-0ddd-4a24-a317-076dc0568060)

**Comment by NicoleSSmith** [comment]
I mixed my screenshots up, but confirming the second one shows the matching IDs

**Comment by pete-msft** [comment]
@NicoleSSmith Thanks! Did you compare the whole string that it is exactly the same like the below one? There are not spaces in the end or any other differences? 

20230821140744842016388$20230821140833780017133$audit_general$Audit_General$na0020

**Comment by NicoleSSmith** [comment]
They look exactly the same. Here are the first three complete data fields from the ListAuditLogContent body:

[
  {
    "contentUri": "https://manage.office.com/api/v1.0/bbfb3f2b-353c-4e04-863a-76285f90f906/activity/feed/audit/20230821140744842016388$20230821140833780017133$audit_general$Audit_General$na0020",
    "contentId": "20230821140744842016388$20230821140833780017133$audit_general$Audit_General$na0020",
    "contentType": "Audit.General",
    "contentCreated": "2023-08-21T14:08:33.780Z",
    "contentExpiration": "2023-08-28T14:07:44.842Z"
  },
  {
    "contentUri": "https://manage.office.com/api/v1.0/bbfb3f2b-353c-4e04-863a-76285f90f906/activity/feed/audit/20230821140833864077953$20230821140950387057192$audit_general$Audit_General$na0020",
    "contentId": "20230821140833864077953$20230821140950387057192$audit_general$Audit_General$na0020",
    "contentType": "Audit.General",
    "contentCreated": "2023-08-21T14:09:50.387Z",
    "contentExpiration": "2023-08-28T14:07:44.842Z"
  },
  {
    "contentUri": "https://manage.office.com/api/v1.0/bbfb3f2b-353c-4e04-863a-76285f90f906/activity/feed/audit/20230821140950559057198$20230821141123536076966$audit_general$Audit_General$na0020",
    "contentId": "20230821140950559057198$20230821141123536076966$audit_general$Audit_General$na0020",
    "contentType": "Audit.General",
    "contentCreated": "2023-08-21T14:11:23.536Z",
    "contentExpiration": "2023-08-28T14:07:44.842Z"
  },

This is the first three strings from the ParseContentIDs. All strings match:
[
  {
    "ContentID": "20230821140744842016388$20230821140833780017133$audit_general$Audit_General$na0020"
  },
  {
    "ContentID": "20230821140833864077953$20230821140950387057192$audit_general$Audit_General$na0020"
  },
  {
    "ContentID": "20230821140950559057198$20230821141123536076966$audit_general$Audit_General$na0020"
  },

**Comment by pete-msft** [comment]
@NicoleSSmith Thanks again for providing more info! Just realized thought that re-running over 7 days old instance should not even work anymore as Office 365 Management API has a limitation to return only last 7 days back of events. I would still run the flow manually to get latest events. If flow is not enabled currently then just turn on the flow and run ones manually.

<img width="190" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/120018333/b320bd03-1053-40ea-988f-fc7a1718fd2a">

**Comment by NicoleSSmith** [comment]
My flow has been continually failing for over a month. I have a failed run from about 90 minutes ago as well that I can pull information from.
In the most recent failure, the content IDs match as well. I get the same error for the failure
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/8d9b976b-a9fd-425c-a9ab-0c90cd5659b0)
The GetContentDetails has the same blob key error
![image](https://github.com/microsoft/coe-starter-kit/assets/122120379/7e1906f7-0578-46a5-9fdd-77d5f65df914)
{
  "error": {
    "code": "AF20052",
    "message": "Blob key 20230829140953101088348$20230829141138392012843$audit_general$Audit_General$na0020 in the url is invalid"
  }
}
I have tried turning the flow off and back on. I have also tried canceling the running flow and turning off and back on. I have resubmitted failed runs. None of those steps have worked. It stills try to pick up the azure secret, which we do not use.

**Comment by pete-msft** [comment]
@NicoleSSmith That "error" in the run details can be ignored as it is showing first exception which happens in the flow run and that is handled exception. If Azure secret is not defined the flow will then continue because of "configure run after" configuration. But this AF20052 "Blob key..." error is strange if the contentId is correct which I haven't seen before. 

@Jenefer-Monroe what do you think we should do next with this? Could we involve PG owning the Office 365 Management API?

![image](https://github.com/microsoft/coe-starter-kit/assets/120018333/ae3fe00e-4891-4a7c-b83a-459c0853504e)

**Comment by Jenefer-Monroe** [comment]
I think we would be better off creating a repro outside the context of the kit and having OP create a support ticket.
I'm not sure the easiest way to create such a repro but basically I think it would just be like get all the ContentIDs for some time period and then loop them to get each. I suppose the bug woudl repro there if I understand it.

**Comment by Jenefer-Monroe** [comment]
Thanks Pete! I'll go ahead and clean up the above so we can keep this as a reference in case others see this issue.

**Comment by NicoleSSmith** [comment]
Do you need any additional information from me at this time?
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Wednesday, August 30, 2023 5:45 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Nicole Smith ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Action 'Get_Azure_Secret' failed (Issue #6248)


Thanks Pete! I'll go ahead and clean up the above so we can keep this as a reference in case others see this issue.

**Comment by pete-msft** [comment]
@NicoleSSmith If you want to test and verify does the same happen outside of CoE then here is PowerShell script attached which does exactly similar calls to O365 Management API [Test-AuditLogAPI.ps1.txt](https://github.com/microsoft/coe-starter-kit/files/12478665/Test-AuditLogAPI.ps1.txt) Just remove '.txt' and probably you need to unblock the file

Then define $TenantID, $ClientID and $ClientSecret values of your service principal in the beginning of the script. It will take 1h hour back of Audit.General event and outputs the count of events found if the HTTP calls works :)

![image](https://github.com/microsoft/coe-starter-kit/assets/120018333/e1517fe5-3125-4369-b9b9-206b5db8341f)


![image](https://github.com/microsoft/coe-starter-kit/assets/120018333/b66e7816-70dd-42c8-ad6a-9f9482b5edd4)

**Comment by NicoleSSmith** [comment]
When this PowerShell script was ran, we had 7483 events. It showed Planner, Teams, Yammer, CRM, etc events.

Audit.General events found - 7483

**Comment by petepuu** [comment]
@NicoleSSmith Sorry about the delay in my response. Audit.General content type contains events of other services as well and sync flow just filters the events which are used in CoE Kit. As the similar HTTP calls works in PowerShell there must be now something wrong in the audit log sync flow which breaks the contentId value in your case. I have checked the values you have sent many times but do not see any issues with those. I will do some testing in my environment but probably next we need to take one contentID (blob key) not working and copy-paste it to the PowerShell script to see does that work

**Comment by NicoleSSmith** [comment]
No worries! Let me know next steps once you get your testing done. I am eager to get the flow up and running.

**Comment by petepuu** [comment]
@NicoleSSmith Here is the script to test the failed HTTP calls having that "Blob key..." error. 

Copy ContentID value of ParseContentIDs action to the $contentId parameter of the script. In script the param value need to be inside single quotes. Also provide $TenantID, $clientID and $clientSecret. Would be good to test with few ContentIDs which failed. Remember that those need to be max 7 days old content slots of events

<img width="326" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/428e56cc-5c96-4e88-a2cb-48cba9ba6acd">


```
$TenantID = ''
$clientID = ''
$clientSecret = ''
$contentId = ''

$ReqTokenBody = @{
    grant_type = "client_credentials"
    client_id = $clientID
    client_secret = $clientSecret
    scope = "https://manage.office.com/.default"
    }

$authUri = "https://login.microsoftonline.com/$TenantID/oauth2/v2.0/token"

$TokenResponse = Invoke-RestMethod -Uri $authUri -ContentType "application/x-www-form-urlencoded" -Method POST -Body $ReqTokenBody

$authheader = @{
"Authorization" = "Bearer $($Tokenresponse.access_token)"
"Content-type" = "application/json"
}

$uri = "https://manage.office.com/api/v1.0/$TenantID/activity/feed/audit/$($contentId)"

Invoke-RestMethod -Uri $uri -Method Get -Headers $authheader 
```

Params should be like this

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/3cf4a001-74ca-4752-81ee-e07c6eb9540f)

**Comment by petepuu** [comment]
If previous test works and returns the events, then next step would be to edit the flow and add Compose action to see the actual whole URL used in the call. Add Compose action after the ResetHttpCallFailed2 action and copy-paste the URI value of the GetContentDetails action to Compose value. Then save and test the flow and see what is the URI value of the Compose action

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/bb83c7f2-66c9-4057-a46c-61ad425cc6a3)

 
![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/61b790be-b5f3-4f80-9d4e-172965b7fbe7)


You can then even test that URI in the PowerShell script like below (need to be in single quotes)

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/bb9b812a-8665-4356-a963-53f3924c0bd9)

**Comment by Jenefer-Monroe** [comment]
We have another repro https://github.com/microsoft/coe-starter-kit/issues/6527. Pointing them here to hopefully assist with a repro

**Comment by mrmonto1** [comment]
Hi. I updated to the Sept. release and it looks like it's still requiring the Azure Client Secret.  Is there a way to bypass this?

![image](https://github.com/microsoft/coe-starter-kit/assets/142948654/2f58dd60-7f2e-4053-9069-6442041d30fd)

**Comment by Jenefer-Monroe** [comment]
Please note that, per your previous bug, that failures like is a caught/expected failure. 
We use this call to see if you are storing the secret as plan text or azure. In your case the call would fail and set the next variable to false as a result and then continue. And I believe fail at the same spot as the user above.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0da62240-6cef-42b5-96fd-6b8bea57cb48)

**Comment by mrmonto1** [comment]
Thanks @Jenefer-Monroe! Per your advice, I dug a little deeper into the flow and found following error below. Restarting the subscription to Audit Log Content with the Admin | Audit Logs | Office 365 Management API Subscription flow and then re-running Admin | Audit Logs | Sync Audit Logs (V2) seems to have fixed it and audit data is now being populated into the Audit Log table. I know I did this when I installed the COE in July. I guess I must have missed this step after upgrading the COE. I'll remember to do this next time I upgrade.  I suggest updating the COE update instructions to include this because the current instructions mention to update the deprecated custom connector for Audit Logs.  https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup#updating-the-audit-log-solution 

![image](https://github.com/microsoft/coe-starter-kit/assets/142948654/6d4a4810-e1f1-4576-9e5c-4219361a0452)

**Comment by pete-msft** [comment]
@mrmonto1 you should not need to restart the subscription when upgrading CoE Kit. Subscription is not stopped automatically when you upgrade the solution

**Comment by mrmonto1** [comment]
Hi @pete-msft . That's good to know.  However, speaking from my experience after successfully installing the COE (July release) and setting up the Audit Log subscription (or at least I thought it was successful because I received a 200 response when instantiating it), I didn't turn that flow off or stop the subscription prior to upgrading to the August and September releases.  I had to re-instantiate the subscription to get the Admin | Audit Logs | Sync Audit Logs (V2) to work in the Sept. release.

**Comment by NicoleSSmith** [comment]
https://github.com/microsoft/coe-starter-kit/issues/6248#issuecomment-1707157759
@pete-msft in regards to the above comment, I ran the script with the values of the ParseContentIDs
Here are the values that were output:
[file1.txt](https://github.com/microsoft/coe-starter-kit/files/12588214/file1.txt)
[file2.txt](https://github.com/microsoft/coe-starter-kit/files/12588215/file2.txt)
[file3.txt](https://github.com/microsoft/coe-starter-kit/files/12588218/file3.txt)
[file4.txt](https://github.com/microsoft/coe-starter-kit/files/12588221/file4.txt)
[file5.txt](https://github.com/microsoft/coe-starter-kit/files/12588222/file5.txt)

I edited Admin | Audit Logs | Sync Audit Logs (V2), added the compose action after ResetHttpCallFailed2. Then grabbed the URL from the output and ran the URl through the script you attached and this is my result:
[INC0311406_20230912.csv](https://github.com/microsoft/coe-starter-kit/files/12591393/INC0311406_20230912.csv)

The flow is still continuously failing. How do you suggest I proceed? Would upgrading the COE to the newest release help resolve the issue? We are currently on version 4.11, updated in July.

**Comment by NicoleSSmith** [comment]
@pete-msft I am well, Thank you. The flow was still failing at the blob key error. I have a working session scheduled for next week to get the newest upgrade installed. I will keep you updated on the progress.

**Comment by NicoleSSmith** [comment]
I was able to update to the October release after working through bug https://github.com/microsoft/coe-starter-kit/issues/6018. I am no longer seeing this issue.
