### ISSUE TITLE
[CoE Starter Kit - BUG] Production_CoEDashboard_August2023 fails with error

### ISSUE THREAD

**Issue by bhavikj65** [microsoft/coe-starter-kit#6249]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When trying to publish Production_CoEDashboard_August2023.pbit report it fails on initial refresh with below errors:

![image](https://github.com/microsoft/coe-starter-kit/assets/105588534/9b579e7e-6782-4d4a-b0c1-b0e1f6918d8b)

![image](https://github.com/microsoft/coe-starter-kit/assets/105588534/d4d322d6-4373-480a-a3f8-ab01476ccf16)

### Expected Behavior

Initial refresh of the PBI report should work. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Production_CoEDashboard_August2023.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, I am duping this to https://github.com/microsoft/coe-starter-kit/issues/6234 please look there for notes to try and to help with investigation.
