### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI report roading error

### ISSUE THREAD

**Issue by enotakadesu** [microsoft/coe-starter-kit#6252]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I tried to set up Power BI dashboard by using Production_CoEDashboard_July2023.pbit, but the error below occured. Then, the report did not display anything.
![image](https://github.com/microsoft/coe-starter-kit/assets/137970094/8455723d-5aa6-4202-96c8-d730530a2b52)

I also tried August ver, but it also had another error similar to the case #6234.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Production_CoEDashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1.Open Power BI and import the data from Production_CoEDashboard_July2023.pbit
2.Fill the environment address with https:// prefix
3.Click "Load" and login if it's the first time
4.Wait for the data to be loaded and see the error

**Comment by Jenefer-Monroe** [comment]
Hello, this issue was resolved with the August release. You will need to upgrade to the [August CoE](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2023) and then you can try out the new dashboards.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
