### ISSUE TITLE
[CoE Starter Kit - BUG] Lots of Errors On Connection References when Importing

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#6255]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I Import  version 4.13 I get the following errors even though thehistory says the Import was successful -

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 14 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: 89ea83b1-d040-47cb-9c3c-05fb27c39210, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: 89ea83b1-d040-47cb-9c3c-05fb27c39210, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Approval Clean Up, Id: 0d0f5e5e-661f-eb11-a814-000d3a1bb7bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: 91c211e5-936e-43cc-83cb-578d69a48717, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: 91c211e5-936e-43cc-83cb-578d69a48717, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Approval Clean Up, Id: 0d0f5e5e-661f-eb11-a814-000d3a1bb7bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_409c1, Id: 93eee03a-234f-4e21-a31a-5ed4a1d8a5ea, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Social Media Manager: Retweet Posts, Id: b986ad7f-f30d-ee11-8f6d-0022489937a4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: d466feb6-bd1e-44c7-b5d8-ce37080d3705, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: d466feb6-bd1e-44c7-b5d8-ce37080d3705, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Check Approvals, Id: c7982cc4-3024-eb11-a813-000d3a8c389b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: d466feb6-bd1e-44c7-b5d8-ce37080d3705, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Social Media Manager: Retweet Posts, Id: b986ad7f-f30d-ee11-8f6d-0022489937a4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAppsforAdminsCoEConnection, Id: 0eee5f38-af45-4f9f-a836-fd38ea544b63, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Approval Clean Up, Id: 0d0f5e5e-661f-eb11-a814-000d3a1bb7bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Deprecated | [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fc6cb07ce08806beb_c6935, Id: 0b6ea6c3-49e8-ed11-a7c6-002248993f4a, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fc6cb07ce08806beb_e4a54, Id: 43a4ffe4-15d6-ed11-a7c7-002248993f4a, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: eed8494a-28c0-45d5-ab2a-9b4cc5b420e8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5ff18d20b7ec3dbffe_a3e3b, Id: 4ea5adc8-0299-4f43-a47b-e40399409ac4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

I have deleted the upgrades back to 4.8 but I still get this issue.

### Expected Behavior

I would hope the supplied Solution would upgrade without any errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

All

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. In my environment select solutions and then Import solution
2. click upgrade
3. see the results after about 30 mins.

**Comment by NPrice99** [comment]
I can make this work but I have to go through all of the affected flows and manually add he Connections into the flows.  This then means I have a large number of customised Solution Layers which need to be deleted before I Import next months solution.

**Comment by manuelap-msft** [comment]
Hello,

it looks like there's multiple issues at play here with your connection references

- Some seem to be connection references cross-referenced between the Core components and Governance components solution. This is something we fixed quite some time ago, so each solution only uses it's own connection references. Can you try and upgrade the Governance components solution first before you attempt to upgrade Core?
- Some seems to be that you're using CoE connection references in your own flows, e.g. one flow that's called out here is Social Media Manager: Retweet Posts - this can happen as flow automatically picks up an available connection reference, and you'll have to update your own flows to use different connection references separate from our solution
- Some seem to be related to the Audit Log solution, which we've recently deprecated. There's a thread here that can help with how to clean that state up https://github.com/microsoft/coe-starter-kit/issues/6018

Hope that helps
Manuela

**Comment by NPrice99** [comment]
Hi @manuelap-msft 
I tried to delete the Governance Solution as it was version 1.51.5 (created 2 years ago) but it would not delete because of dependences - 
![image](https://github.com/microsoft/coe-starter-kit/assets/8484048/ee1951f2-56e6-4e80-bd03-1d2a321cad0b)

Which look as if they are all within the Solution.

So why can I not delete the Governance Solution ?

Regards

Nigel

**Comment by manuelap-msft** [comment]
Hi Nigel,

two years is a long time ago in terms of CoE kit versions, and we don't have this version installed anywhere to check so I'm not able to look into this. I would check if you have unmanaged layers on either the connection reference or the flows, or if the connection references are used in other flows to resolve this.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
