### ISSUE TITLE
Changing owners for SharePoint Form Apps

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#6259]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Team,

I have a question like how do we set app owner for the customized share point form???

As a part of governance, we have successfully set the Orphaned apps to Quarantine, when a user requested back we have released from quarantine as well. As the previous owner has left the org and the app was orphaned for few months and we set it to quarantine, but now we have a problem is that like we are unable to set a new owner to the share point customized form.

1. Is there a way to find the share point customized form is orphaned or not?
2. Is there a way to set the app owners for share point customized form using COE. I tried to check with the Set App permission but unable to find the app in that list.

Need your inputs on this.

Thanks

### What solution are you experiencing the issue with?

None

### What solution version are you using?

NA

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
If this is a feature you require, please raise it via the Power Apps Ideas forum (https://ideas.powerapps.com/d365community/forum/f1458c72-ae29-ed11-9db2-000d3a8c451e) or work with your Microsoft Account Team to feed this back to the Product Group.

**Comment by Neel1KNK** [comment]
Is that the reason like we are unable to see all these apps in the Set App Permission App??

**Comment by manuelap-msft** [comment]
You can find them in:

Power Platform Admin View > PowerApps Apps > Sharepoint (select under View)
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/d710f087-76ce-4fd9-8a44-3d0491583873)

Power BI dashboard > SharePoint Form Apps tab
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/7a04618f-10a9-443f-8636-c70274fe8288)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
