### ISSUE TITLE
[ALM Accelerator - BUG]: Pipeline "deploy-prod" The async operation completed with a statuscode of Failed.

### ISSUE THREAD

**Issue by perssonkasia** [microsoft/coe-starter-kit#6263]
### Describe the issue

Hi, 
I have the issue with "Deploy-prod-..." pipeline. 
Validation and test deployment are successful. 
I can't import solution via pipeline to production. I receive "an unexpected error".
Manual import to the environment working fine.  Hope you can help me to solve this problem. 

![image](https://github.com/microsoft/coe-starter-kit/assets/55349153/061c3349-e4b6-4249-b991-8f0ad6cc87c1)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20230802.1

**Comment by perssonkasia** [comment]
Hi @mikefactorial, thank you for the comment.  I have made a clean install of ALM in another Environment, everything seems to work there. I suppose it was a configuration error in my custom connector.
I have instilled ALM for over one year ago and upgrade it regular since. Probably i missed some configuration in custom connector.

**Comment by mikefactorial** [comment]
@perssonkasia thanks for reporting back. Glad you got it working! Going to close this out for now.

**Comment by tocri** [comment]
for what it worth, i had the same issue due to unmanager layer on the **shareconnectionwithserviceprincpal** flow. 🤯🙃
