### ISSUE TITLE
[CoE Starter Kit - QUESTION] What should make "Admin | Sync Template v3 (Flow Action Details)" run?

### ISSUE THREAD

**Issue by anttipajunen** [microsoft/coe-starter-kit#6265]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I'm trying to get "Admin | Sync Template v3 (Flow Action Details)" to run by creating a new environment (it should run on the conditions seen below) and then running the driver, but I'm not seeing any runs for the flow at all. Are there any known issues that I've just been unable to find or am I doing something wrong?

![image](https://github.com/microsoft/coe-starter-kit/assets/64043240/1cdd4a44-854d-4f16-9d8f-5d36e5a162e9)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
No thats how it shoudl be triggered and is triggered for me. 
Are other dataverse triggers in your environment working? I've seen this happen when the envt was in Admin Mode.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d65230d5-92ad-401a-8a23-d6e23bc866c0)

**Comment by anttipajunen** [comment]
This is peculiar. I updated to 4.13 but even that didn't fix the issue for me. I've now reset my CoE env. I'll update on the findings as I've reinstalled CoE.

**Comment by anttipajunen** [comment]
A reset of my CoE end and a reinstall of CoE did the trick. The flow now works as intended.
