### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Audit Logs | Sync Audit Logs (V2) not able to pull in new data

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6269]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Looking at compliance we found that there were several new launched dates for a specific app however it still does not show their app's last launched date on the power platform admin view. Found a few others that have only the last launch date of what I had loaded but there were all new records from yesterday that never seem to be found from this flow.

It pretty much stops here and then says it is successful.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/fc9b27a1-71f2-40a6-a535-64b3030370cb)
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/55a2239a-a1eb-4350-94ed-e7a6a019ebcf)

Not sure how to fix this.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by mdphung** [comment]
There is also this screen too.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/660a646c-a383-4cec-81a2-994be795f5e0)

**Comment by Jenefer-Monroe** [comment]
Hello, this was fixed for the July release via https://github.com/microsoft/coe-starter-kit/issues/5765
I'll go ahead and close as a dupe to that bug. You can see in there how to local fix while you await your upgrade cycle.
