### ISSUE TITLE
[CoE Starter Kit - BUG]: Developer Compliance Center - Delete App Error

### ISSUE THREAD

**Issue by anton3sco** [microsoft/coe-starter-kit#627]
**Describe the bug**
After installing the governance components, I realized that the "delete app" trash icon was throwing an error. It is currently connected to a variable vApp which does not hold the app ID but if updated to VSelectedApp it corrects the issue.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Governance
 - Version 1.60
 - App or Flow Developer Compliance Center Canvas App

**To Reproduce**
1. Open the Developer Compliance App in edit mode
2. Press play to begin navigating through the app. Click on the details of an app to view details.
3. Click the trash icon at the top right. An error message appears. 
4. Exit play mode and update the error from vApp to vSelectedApp
5. Click play and repeat steps - the app is deleted

**Expected behavior**
When opening the app details and clicking the trash icon, a dialog to confirm opens then clicking the delete button should immediately remove the app without issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/26906102/122109555-1e075780-cde3-11eb-9d1e-8346d9982133.png)

**Additional context**
A nice to have feature would be that when an app is deleted that the canvas app reflects the deleted app. Right now, the app doesn't go away until the flow runs.

**Comment by JeneferM-MSFT** [comment]
Thank you for catching I have fixed the bug around the reference to the old variable vApp

**Comment by anton3sco** [comment]
Great, thank you. Did you see that the compliance submit form button also uses the variable? I didn't touch that one in my tenant because I figured if it's still saving the details, it must serve its purpose. 

Thanks again for being so quick on this. Will it be implemented in the next version?

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
