### ISSUE TITLE
upgrading to 4.13 core components - User is not authorized to read secrets from

### ISSUE THREAD

**Issue by KezHalls** [microsoft/coe-starter-kit#6272]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Importing CenterofExcellenceCoreComponents_4.13_managed.zip produces error
User is not authorized to read secrets from

This import worked successfully on previous occasions
I found this issue which is the same as what I am seeing #5348
I have tried
- ensuring Dataverse and user have correct access to keyvault as per above article
- providing any principal with the word dataverse permissions to the keyvault
- I tried to empty the secrets variable but it would not let me leave it blank 

### Expected Behavior

solution would import successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

import

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Go to CoE environment
Import Solution

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/29215309/4daa6e15-782d-4bc5-8ea2-e2781806e2a2)
![image](https://github.com/microsoft/coe-starter-kit/assets/29215309/27c4be90-42b9-4f95-b075-3beb473e4d34)

**Comment by manuelap-msft** [comment]
What access do you / the user importing the solution have to the Key Vault?

Please validate that the azure key vault access control is correct the (IAM). User needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)

**Comment by KezHalls** [comment]
I showed it in my screenshot. s-powerplatform.  and that has the correct access.

**Comment by Jenefer-Monroe** [comment]
Are you able to get contributor access?

**Comment by KezHalls** [comment]
i gave contributor access and I still got the same error.  
![image](https://github.com/microsoft/coe-starter-kit/assets/29215309/0437776a-c5e2-467a-b08a-45fd1070dc6b)

**Comment by KezHalls** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/29215309/3bd85142-d5ad-4746-95ff-d4f169af69d0)

**Comment by Jenefer-Monroe** [comment]
Changes here can take quite some time to propogate I've noticed. 
I'm afraid we are just consumers of this Azure feature and so you will need to contact product support to get assistance with why you are unable to read these secrets.

**Comment by KezHalls** [comment]
Its not clear to me what you mean.  Do you mean changes from microsoft?
I will log a ticket with them.
Thanks

**Comment by Jenefer-Monroe** [comment]
Changes in your permissions for key vault is what I meant. Sorry we cannot be of better assistance here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team

**Comment by KezHalls** [comment]
Hi Jenefer and others.  
Microsoft just got me to change my keyvalt to rbac access from access policy and this resolved my issue.

![image](https://github.com/microsoft/coe-starter-kit/assets/29215309/66051dd6-da15-43c5-96c2-031078a0171d)
