### ISSUE TITLE
[CoE Starter Kit - BUG] I was facing issue during update of CoE Starter kit core component 

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#6273]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

During Update I get this error message and duplicate solution created in my environment

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/a3784cb4-5d9b-4b99-978e-ee36944a0ef0)

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/c1edaeec-e2f0-4e0f-b6d9-5535e5c123fa)

 

### Expected Behavior

Solution should be updated without any issue, your suggestion is appreciated to fix this issue 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Office 365 Management API connector 

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

I am getting this issue during version update of Core component "4.3" to 4.13

**Comment by manuelap-msft** [comment]
Hello, this is an expected upgrade failure due to the deprecation of the Audit Logs custom connector. 
Please see the following to resolve. https://github.com/microsoft/coe-starter-kit/issues/6018

**Comment by sharmajitendralal** [comment]
Ok, Noted let me try it

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
