### ISSUE TITLE
[CoE Starter Kit - QUESTION] SYNC HELPER - Get Security Role Users More than one concurrent delete requests

### ISSUE THREAD

**Issue by uzma-fis** [microsoft/coe-starter-kit#6275]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Previously discussed on https://github.com/microsoft/coe-starter-kit/issues/6199 but was closed out. 

SYNC HELPER - Get Security Role Users
This is appearing for a particular environment with error with "Action 'Delete_it' failed" description 

More than one concurrent Delete requests detected for an Entity e1c5f53f-af34-ee11-bdf4-0022487fe19b and ObjectTypeCode 10384.

Looking at the issue that was posted earlier, I can provide you with info that this flow has successfully run approx 115 times a day, but has error on this particuar environment. 

Is there a way to clear this error for the environment as it seems there's a clash somewhere for the delete request? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023 4.9

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. What I need is a run count (succeeds or failures) for these two flows run in a day

- Admin | Sync Template v3 (Environment Properties)
- SYNC HELPER - Get Security Role Users

You can see it by going to the Analytics and then usage. This example flow tends to run ~75 times per day for example

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7dbfaef6-8fac-4310-a920-6d6c2abd3f70)


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9ef87125-e78b-4600-8307-6cb768de997b)

**Comment by uzma-fis** [comment]
Admin | Sync Template v3 (Environment Properties)

![image](https://github.com/microsoft/coe-starter-kit/assets/141040714/fa4693ea-7dae-4715-9451-dc8f63602775)

It's 1312 or 614!

SYNC HELPER - Get Security Role Users
![image](https://github.com/microsoft/coe-starter-kit/assets/141040714/7234f6a9-acd3-4172-aab5-aab1ebf21aad)

**Comment by Jenefer-Monroe** [comment]
And how many environments do you have in your tenant?

**Comment by uzma-fis** [comment]
We have many environments!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by uzma-fis** [comment]
________________________________

**Comment by uzma-fis** [comment]
332 environments to be exact.
________________________________

**Comment by Jenefer-Monroe** [comment]
I belivee this was a dupe to https://github.com/microsoft/coe-starter-kit/issues/6095 fixed in the August release. 
I'll go ahead and close as a dupe to that but plesae let us know if you expereince other issues here after your next upgrade.
