### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Driver) Missing Environments

### ISSUE THREAD

**Issue by SOM-Scott** [microsoft/coe-starter-kit#6278]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The **Get Environments** action in **Admin | Sync Template v3 (Driver)** is only returning 5 environments. This causing the rest of the environments to be listed as deleted and not inventoried. This is a new issue as of 4.13, 4.9 was fine.

### Expected Behavior

Return all environments to then inventory them.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1, Run the flow
2, Check flow history
3, Got to Get Environments and some tenant wide properties
4, Open results from Get Environments
5, JSON response only has 5

CoE Admin only list 5 environments as active

### Anything else?

This is GCC if that matters.

**Comment by Jenefer-Monroe** [comment]
Hello. This is just an out of the box action that we call and so it should return whatever environments you have access to. We have seen this happen for people when they have their PPAdmin role assigned to them via PIM, which we do not support. 
Please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6901b231-4c70-4508-9683-41baa11c6a9f)

Can you please check if you have PPAdmin role permanently assigned?

**Comment by SOM-Scott** [comment]
Thanks, somehow the service account lost the PPAdmin role. Once it was restored, inventory is running correctly again.

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thank you for letting me know!
