### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to delete Center of Excellence - Audit Logs when installing August release

### ISSUE THREAD

**Issue by gprof** [microsoft/coe-starter-kit#6280]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In am following the instruction in #6009 and I get below error when trying to delete the Center of Excellence - Audit Logs

![image](https://github.com/microsoft/coe-starter-kit/assets/25688152/80c7597c-306d-48fe-88f7-aeae626045d6)

Please advice how to proceed. 

Note - Below is an overview of all installed solution in my environment:

![image](https://github.com/microsoft/coe-starter-kit/assets/25688152/3ef69266-5fb0-41a8-aa05-17cec3475c1e)

 

### Expected Behavior

Procedure described in  #6009 should allow me to delete the Center of Excellence - Audit Logs solution so that I can install the Center of Excellence - Core Components v4.13 (August release)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

 Center of Excellence - Audit Logs 3.4

### What app or flow are you having the issue with?

See screenshot

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We do not have a dependency between those flows in our kit. So you may need to go remove unmanaged layers from them. 

Please remove unmanaged layers from both of these flows
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/87837620-2a47-41d4-b580-35120db38e9f)

Then see if you can uninstall Audit Logs

**Comment by gprof** [comment]
Thanks Jenefer - that did it! I am now able to delete audit logs and install the core components 4.13.

**Comment by Jenefer-Monroe** [comment]
oh what wonderful news! Thanks for letting me know
