### ISSUE TITLE
[CoE Starter Kit - Feature]: Maker DLP Viewer

### ISSUE THREAD

**Issue by bch920** [microsoft/coe-starter-kit#6281]
### Is your feature request related to a problem? Please describe.

Users can't easily see what DLP policies we have and see which connectors are enabled /blocked

### Describe the solution you'd like

Ideally would like a Canvas App that let users see certain DLP's and see which connectors are enabled within them.
Reason for a Canvas App is we would like to embed it in our SharePoint site so users can easily see or environment strategy and the DLP's for each environment type.

### Describe alternatives you've considered

We have considering writing our own flow which pulls the info and stores it in a SharePoint list so users can easily see the info in there.

**Comment by thomgerm** [comment]
every user can easily see the DLP at https://admin.powerplatform.microsoft.com/dlp - at least in our tenant - I am quite surprised how much info is displayed here, but that is the way it is.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
