### ISSUE TITLE
[CoE Starter Kit - BUG] Thottling Issue on specific Flow Admin | Sync Template v4 (Flows)

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6282]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/b20ec4c1-5ec3-4f06-b8ce-9ccf4719b99d)
Is there something else I can do to fix this, maybe is it better to add a per-flow user license to the sync template.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by mdphung** [comment]
If we move to BYOD is there an issue with duplicative data considering we have data already?

**Comment by Jenefer-Monroe** [comment]
Hello we added some retry logic for this and a few other actions in the August release. Please see ttps://github.com/microsoft/coe-starter-kit/issues/6037

**Comment by Jenefer-Monroe** [comment]
Please see our [Data Export FAQ](https://learn.microsoft.com/power-platform/guidance/coe/faq-dataexport) for some generalized learnings about transitioning to BYODL

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this as a dupe to #6037
