### ISSUE TITLE
[CoE Starter Kit - QUESTION] how would you implement a "WelcomeMail" to users who start creating Power Apps with a different text per environment?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6283]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How would you implement a "WelcomeMail" to users who start creating Power Apps with a different text per environment (different guidelines/governance)? CoE allows only 1 mail valid for environments.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
We would recommend using Managed Environments > Maker onboarding content instead
https://learn.microsoft.com/en-us/power-platform/admin/welcome-content

This allows you to configure an onboarding message per environment.

**Comment by fs366e2spm** [comment]
Sure - for "Managed Environments", for non managed environments?
CoE has a Welcome E-Mail functionality even in multi language, just same e-mail for all environments and therefore not usable

**Comment by manuelap-msft** [comment]
The CoE kit is not part of the Power Platform product, it's a reference implementation / collection of templates of how you can administer, govern and nurture your Power Platform tenant. There's no one size fits all, and often the templates in the CoE kit only provide a starting point or inspiration for how to achieve a certain use case. 

In this case:
- As the ability to tailor a welcome message exists in the product via Managed Environments, we are not going to replicate this functionality into the CoE kit. The goal of the kit is to extend the product, not to replicate product capabilities into it.
- If your requirement isn't met by either Managed Environments or the CoE kit, you'll have to look at extending the kit to meet your needs. Most of the data you need is already there, but you'd have to build your own Welcome Email flow around it that pulls emails based on specific environments. Here's our guidance on extending the kit https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
