### ISSUE TITLE
[CoE Starter Kit - QUESTION] Will changing from the Data Export service from the Power Automate Flows for Audit information have me lose previous information in the PowerBI Report (like yoy adoption)

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6284]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Will changing from the Data Export service from the Power Automate Flows for Audit information have me lose previous information in the PowerBI Report (like yoy adoption)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
No, we combine data from the Audit Log table where you may have existing data with the data from Data Export in the dashboard, so you should not lose any information there.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
