### ISSUE TITLE
[CoE Starter Kit - QUESTION] My CoE platform is showing only few environments. not all the environments. any possible reason for that?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6286]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

My CoE platform is showing only few environments. not all the environments. any possible reason for that?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
There could be many reasons for this, typically it's:

- the account running the sync flows doesn't have the right permissions and is not a Power Platform Admin permission
- the account running the sync flows has admin access assigned via PIM and loses access whilst the sync flows are running

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
