### ISSUE TITLE
[CoE Starter Kit - QUESTION] How do users see a list of all their own flows? We utilize multiple environments and many resources are shared with other users as well

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6287]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How do users see a list of all their own flows? We utilize multiple environments and many resources are shared with other users as well

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Currently, users can see all resources they own in the Developer Compliance Center so its mainly there so they can provide or review additional details and not for reporting.

As part of https://github.com/microsoft/coe-starter-kit/issues/3573 we are working on maker-facing reporting and may add a list of all flows/apps as part of that report for further reporting and drill-throughs.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
