### ISSUE TITLE
[CoE Starter Kit - QUESTION] We installed the CoE Toolkit 2 years ago in a Sandbox environment. We need to star again with a fresh new installation. If I delete the old Sandbox environment, will all the objects be deleted? or do we need to clean manually?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6288]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We installed the CoE Toolkit 2 years ago in a Sandbox environment. We need to star again with a fresh new installation. If I delete the old Sandbox environment, will all the objects be deleted? or do we need to clean manually?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by WorkingWithData** [comment]
Thanks!    The Solution was installed as unmanaged,  does this make a difference?   :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
