### ISSUE TITLE
[CoE Starter Kit - QUESTION] Are there specific resources (separate from the general documentation) for establishing the CoE kit on GCC or GCCH tenants?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6289]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Are there specific resources (separate from the general documentation) for establishing the CoE kit on GCC or GCCH tenants?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
To our knowledge we have been able to obfuscate away GCC/etc specific issues from users of the kit, aside from some configuration steps which are noted inline as shown below. 

There are sometimes issues specific to these clouds though so do reach out if you see issues.

### Example of the inline instructions:
[Set up the Inventory components using the Setup Wizard](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-using-the-setup-wizard)


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66ae1947-df50-48fa-a6cb-1fec10f1113a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
