### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can you give more insights on update #5991-[CoE Starter Kit - Feature]: One App for Makers and One for Admins - is it implemented or what are the apps for Admins and Makers?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6290]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can you give more insights on update #5991-[CoE Starter Kit - Feature]: One App for Makers and One for Admins - is it implemented or what are the apps for Admins and Makers?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
It's not on our roadmap to implement this. Customers use the CoE kit in many different ways, and rarely have an "all or nothing" approach to the kit. If we had just one monolithic application, it would be really hard for customers to only adopt parts of the kit.

Now that most of our apps just consist of custom pages, if you require a "one app" approach you can create your own model driven app and add our views, forms and custom pages to it. 

A walkthrough of this is here
https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

And specifically for custom pages
https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components#configure-a-new-model-driven-application

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
