### ISSUE TITLE
[CoE Starter Kit - QUESTION] will the new powerbi dashboard provide insights on out of context (standalone) flows

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6291]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

will the new powerbi dashboard provide insights on out of context (standalone) flows

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Yes this is in the Governance dashboard as shown here.

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/74ff9fd9-edb1-4fee-ab7f-1ac7490ce324)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
