### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there a way to monitor ai models used in tenant using coe toolkit

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6292]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way to monitor ai models used in tenant using coe toolkit

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Yes, see https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-monitor#ai-builder-models

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
