### ISSUE TITLE
[CoE Starter Kit - QUESTION] Are the apps/flows deleted using COE are permanently deleted or only deleted in the COE tables?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6293]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Are the apps/flows deleted using COE are permanently deleted or only deleted in the COE tables?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
If you delete them through the orphan/inactive process or through the "delete app/flow" button in the Power Platform Admin View, they are permanently deleted. I believe they can be restored using PowerShell for a short amount of time.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
