### ISSUE TITLE
[CoE Starter Kit - QUESTION] We are over 1 year behind on the CoE upgrades after the team managing this abandoned it 😕 Best to start over or incrementally update?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6294]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are over 1 year behind on the CoE upgrades after the team managing this abandoned it 😕 Best to start over or incrementally update?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
If you start over, you'd lose all data that's already been collected. So if you're only using the CoE kit for inventory that may be fine, but if you've started using governance processes you may lose a lot of data.

I'd try upgrading to the latest version and see if that works. We've recently had a few folks with successful updates from this far back, although it's not something we personally test.

If that doesn't work, start incrementally - e.g. look at a version 6 months back and see if that works, if that doesn't work go back further in 3 month increments (which is what we recommend).

The 3 month recommendation is a target, it doesn't mean that upgrades will break if they're more than 3 months old (we don't do anything on purpose to break an upgrade). It's just how far back we test, so that's why it's our recommendation.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
