### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there a release plan somewhere that we can follow?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6295]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a release plan somewhere that we can follow?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
You can look at our milestones in GitHub
https://github.com/orgs/microsoft/projects/195/views/53

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
