### ISSUE TITLE
[CoE Starter Kit - QUESTION] In COE Toolkit Power Platform admin view, the details present in the governance tab of any Power App/ Power Automate Flow gets populated from where? If we manually update those details, during the next COE upgrade, will the manually updated details get overwritten after the upgrade?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6296]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In COE Toolkit Power Platform admin view, the details present in the governance tab of any Power App/ Power Automate Flow gets populated from where? If we manually update those details, during the next COE upgrade, will the manually updated details get overwritten after the upgrade?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
1. Meta data about the app (e.g. the app name, created by, what environment it is in) gets populated by the sync flows or by Data Export and gets overwritten on a daily basis. Those fields are locked (read-only) in the view so you can't modify them anyway.
2. All custom fields (e.g. Governance, Business Justification) are for you to populate data in. They don't get updated by the system and if you perform an upgrade that doesn't impact the data in those fields. 
3. The data gets populated manually - either you as the admin can enter data there, or makers can use the Developer Compliance Center to provide further information.
4. The data is meant for you to build a bigger picture on the apps and flows you have in your tenant, beyond the data that's provided by the product. So you can store business justification, importance, etc etc

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
