### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Automate Process Mining has recently been made available in GA. Will there be a separate CoE Starter Kit for that product?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6297]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Power Automate Process Mining has recently been made available in GA. Will there be a separate CoE Starter Kit for that product?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
What are your governance, admin and nurture requirements for Process Mining? If you can help us understand those, we can add them to a list.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
