### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admins asked about the report for flows co-owners or who are the flows shared with, the flow last run time.

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6298]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Admins asked about the report for flows co-owners or who are the flows shared with, the flow last run time.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
This is on our backlog, see https://github.com/microsoft/coe-starter-kit/issues/1083

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
