### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Sync Template v3 flow failing

### ISSUE THREAD

**Issue by arpitasaha11** [microsoft/coe-starter-kit#6300]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Admin Sync Template v3 (Driver) flow is failing on the environments which are created by SYSTEM. The Helper Maker Check flow is failing with Could not find a property named 'SYSTEM' on type 'Microsoft.Dynamics.CRM.admin_maker'. I understand this was an old bug but I have imported the new solution and there are no unmanaged layers. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin Sync Template v3 (Driver) 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Have you used the Setup Wizard to set up the kit? This inserts the SYSTEM Maker into the Maker table. We recommend that even for an upgrade, you use the Setup Wizard to go through the steps to set up the kit.
