### ISSUE TITLE
[CoE Starter Kit - QUESTION] can I visualize a flow that is looped in a dashboard, to identify an anomaly?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#6301]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

can I visualize a flow that is looped in a dashboard, to identify an anomaly?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
