### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by mattriesae** [microsoft/coe-starter-kit#6305]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

DLP Editor v2 failing to send emails for impacted Apps and Flows.

When I try to export my impacted apps and flows with DPL Editor v2, it never sends an email. Checking the DLP Editor>Parse impacted resources into CSV flow, it's failing with a ValidationFailed. The schema validation failed. Action 'Parse_Non-Business_connectors' failed error.

Output of the error is below.
[
  {
    "message": "Required properties are missing from object: id.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0]",
    "value": [
      "id"
    ],
    "schemaId": "#/items",
    "errorType": "required",
    "childErrors": []
  },
  {
    "message": "Required properties are missing from object: id.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[1]",
    "value": [
      "id"
    ],
    "schemaId": "#/items",
    "errorType": "required",
    "childErrors": []
  },
  {
    "message": "Required properties are missing from object: id.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[2]",
    "value": [
      "id"
    ],
    "schemaId": "#/items",
    "errorType": "required",
    "childErrors": []
  },
  {
    "message": "Required properties are missing from object: id.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[3]",
    "value": [
      "id"
    ],
    "schemaId": "#/items",
    "errorType": "required",
    "childErrors": []
  }
]

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

DLP Editor>Parse impacted resources into CSV

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

In our CoE Environment, open the DLP Editor v2 and start editing a policy. When I get to the Impacted Flows and Apps section, hitting the button for Export impacted apps and flows to csv does nothing.

**Comment by manuelap-msft** [comment]
Can you please try the new app, DLP Impact Analysis [Preview], and see if that works for you? We amended the flow to work for the new app and may have missed updating it in a spot in the old one. New app has the same (+ more) functionality so it would be great if you could try it out and let us know if that works for you!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
