### ISSUE TITLE
[CoE Starter Kit - BUG]: Power BI Does not show correct data

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/coe-starter-kit#631]
**Describe the bug**
When I look into Power BI for 1 of my environment it has 13 model-driven apps but in the Power BI report, it only shows 7. Also, it happens the same with the canvas app. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 2.1
 - Power BI - 2021-04-08 

**To Reproduce**

**Expected behavior**

**Screenshots**
CoE Power BI
![image](https://user-images.githubusercontent.com/59940632/122127653-7fd6ba00-ce01-11eb-98f3-052428f24bc9.png)

PPAD
![image](https://user-images.githubusercontent.com/59940632/122127705-91b85d00-ce01-11eb-831a-5587a6d35713.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Please do the following to help us debug:

1. go view in the [Power Platform Admin View (Model Driven App)](https://docs.microsoft.com/power-platform/guidance/coe/core-components#power-platform-admin-view) to see if the apps show there? This will help us understand if the issue you are seeing lies in the sync flows or in the report. 

1. go to the runs of the apps and model driven apps to see if there have been failures in any of the recent runs, and to see when they last ran

1. Tell us, does your organization use PIM to manage credentials? 

1. Does the user running the sync flows have the PPAdmin role?

**Comment by aakashpatel660** [comment]
Hi @JeneferM-MSFT 

Nice to see you again. 

I am a global admin. 

1. Not all the applications shown in the Power Platform Admin View. Below is the screenshot. 
![image](https://user-images.githubusercontent.com/59940632/122149732-90e7f100-ce2a-11eb-853c-3a06a67dfc3c.png)

2.  Both flows are getting succeeded
3. Yes we do use PIM
4. I am running the flows from my account.

**Comment by JeneferM-MSFT** [comment]
Note that PIM may be the issue you are seeing. We cannot support PIM with the toolkit as sometimes the permissions will go away mid-run. Please see our [limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations#pim-privileged-identity-management)

Can you please share a screenshot like below of the successes for the Model Driven apps? I want to make sure the correct flow is running:
![image](https://user-images.githubusercontent.com/62659043/122222648-afbca680-ce6f-11eb-843e-89c783d8a76e.png)

**Comment by aakashpatel660** [comment]
![image](https://user-images.githubusercontent.com/59940632/122555320-255b7a80-d008-11eb-85a7-e2d9ffaf8e59.png)

**Comment by JeneferM-MSFT** [comment]
I'm afraid the issue is likely your PIM then. 

PIM does not work well with automated flows as you can't guarantee that the identity will have the permissions when the flow is triggered / running. Please see [limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations#pim-privileged-identity-management)
