### ISSUE TITLE
How to customize this mail in French : App could not be deleted for you

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#6311]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

Yesterday, a user received this mail in english. He wants to delete his sharepoint form app that is not used.
I told him how to do this but i was very surprised that the mail was in english
I lookup on the customized email form COE admin Command center but i didn't find it.

do you know where i can translate it ?

<img width="632" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/3db7139d-c319-48da-99b0-7a6b5035a174">

thanks a lot

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.10

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, we had missed these and just added them to the configuration table for August release via https://github.com/microsoft/coe-starter-kit/issues/5864

I'll go ahead and close as a dupe, but thank so much for posting!
