### ISSUE TITLE
[ALM Accelerator - QUESTION] Custom Connector Connection

### ISSUE THREAD

**Issue by MKUltraCSA** [microsoft/coe-starter-kit#6312]
### What is your question?

While configuring the ALM accelerator, there is a step to test the custom connector. Step 2 says to select new connection and create one. What permissions does the account used to create this connection need in devops? In the screenshot form the docs, it's listed at the top as "selected connection."

![ALM Connection Doc photo](https://github.com/microsoft/coe-starter-kit/assets/141785636/bfc05aa4-7322-4d19-ae68-81a1d0fcffd1)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230802.1

**Comment by mikefactorial** [comment]
@MKUltraCSA the user needs to have at least a Basic Access Level
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/1ed5a86e-3578-4f7d-be5f-5e17c9c663b0)

There's additional details about user permissions here https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-app-user-permissions
