### ISSUE TITLE
[ALM Accelerator - BUG]: Commit Solution Pipeline Error

### ISSUE THREAD

**Issue by jfung85** [microsoft/coe-starter-kit#6318]
### Describe the issue

After upgrading to the latest ALM Accelerator solution (1.0.20230802.1), we tried to update Deployment Settings for the Prod environment and then Commit Solution. This had been working in prior versions for the Test environment configuration.

This error was displayed: Error running pipeline: {"$id":"1","innerException":null,"message":"Unexpected parameter 'ArtifactUrl'\nUnexpected parameter 'PipelinesServiceConnectionName'\nUnexpected parameter 'PipelinesServiceConnectionUrl'\nUnexpected parameter 'PipelinesStageRunId'\nUnexpected parameter 'AgentPool'\nUnexpected parameter 'VMImage'","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException","errorCode":0,"eventId":3000}

### Expected Behavior

We expect to be able to run the Commit Solution Pipeline

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230802.1

### Steps To Reproduce

1. Click on Configure Deployment Settings
2. Update settings for the selected solution for the Prod Environment configured
3. Click on Save and Close
4. Click on Commit Solution
5. Enter Notes, Select Scope: Solution and Settings, Use existing Branch from prior deployments
6. Click on Commit Solution
7. Error message appears: Error running pipeline: {"$id":"1","innerException":null,"message":"Unexpected parameter 'ArtifactUrl'\nUnexpected parameter 'PipelinesServiceConnectionName'\nUnexpected parameter 'PipelinesServiceConnectionUrl'\nUnexpected parameter 'PipelinesStageRunId'\nUnexpected parameter 'AgentPool'\nUnexpected parameter 'VMImage'","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException","errorCode":0,"eventId":3000}

**Comment by mikefactorial** [comment]
You can upgrade the pipelines through the admin app or manually via a PR using these steps https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-pipeline-sync

**Comment by jfung85** [comment]
Thanks for the pointer @mikefactorial. I had run the job to update the pipeline but missed the last step to approve and complete the pull request. I think that should resolve this issue. I will test and confirm but otherwise, we can close this one for now.
