### ISSUE TITLE
[CoE Starter Kit - BUG] Sync template V3 gets suspended due to failures

### ISSUE THREAD

**Issue by thomgerm** [microsoft/coe-starter-kit#6320]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

the main flow of CoE has stopped working and is suspended. 
the version of CoE core component is 4.11 - it worked for some time and collected data, but then stopped working probably due to too many errors being thrown?
we opened a MS case as well but I hope to get some information here if this is a known issue or a solution is around

this is what was retrieved:
"body": {

        "error": {

            "code": "0x80040217",

            "message": "Entity 'admin_Maker' With Id = 94fe5771-b1d2-4f30-b890-ae2b852d9629 Does Not Exist",

            "@Microsoft.PowerApps.CDS.HelpLink": "[http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform"](http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform%22),

            "@Microsoft.PowerApps.CDS.InnerError.Message": "Entity 'admin_Maker' With Id = 94fe5771-b1d2-4f30-b890-ae2b852d9629 Does Not Exist"

### Expected Behavior

CoE collecting data as usual

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin - Sync Template V3

### What method are you using to get inventory and telemetry?

None

### Anything else?

TrackingID#2308100050003057 case number

**Comment by thomgerm** [comment]
reason for suspending it:
![image](https://github.com/microsoft/coe-starter-kit/assets/130649311/45bef8f9-4620-47c7-9d83-acf600430cde)

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by thomgerm** [comment]
Jenefer, all this is the screenshot, let me know if it is sufficient. We could start the flow again manually but it is still throwing the ... does not exist errror which is mentioned above
![image](https://github.com/microsoft/coe-starter-kit/assets/130649311/bb76c59d-a0e7-4607-bc61-7dcdf6c2e22f)

**Comment by Jenefer-Monroe** [comment]
That flow got renamed and so it should no longer be in your list. Thats why I was asking to see if you had an install error in the past.
Do you have a flow called **_Admin | Sync Template v3 (Driver)_**?
Can you see if there is an unmanaged layer on it?

**Comment by thomgerm** [comment]
we upgraded to 4.11 (not a fresh installation) - should the new flow be part of this update, we did not face any installation issue during the upgrade to 4.11.
I understand that the new flow should have been a part of 4.11 update - what is your recommendation how to fix it?
A new update  of CoE might also not replace the flow, is there something we need to consider to make it successful?
thank you

**Comment by Jenefer-Monroe** [comment]
No its the same flow but renamed. You must have an unmanaged layer on the flow, can you please check again? 
Please share a screenshot of what you see when you click this
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/42573be9-4748-4ca1-a781-77764a0f1097)

**Comment by thomgerm** [comment]
![741d956d-7051-43a9-b1a3-16adfac64c1e](https://github.com/microsoft/coe-starter-kit/assets/130649311/8dde45ec-6803-4b87-a566-e9fb48a8e487)

Hi this is what we see. 
Jennefer if you say that there was no change, just renaming, then I fear that the issue will still exist anyway. Our issue is mainly the high number of errors causing the flow to be suspended: admin_Maker' With Id = 94fe5771-b1d2-4f30-b890-ae2b852d9629 Does Not Exist",
Is there a known issue with messages like that which could cause trouble in a large environment and how can we get this solved, please?

**Comment by Jenefer-Monroe** [comment]
No there were changes to the flow, but also a rename. We redid the data sent in to the child helper for checking users to repair what you are seeing. 
I dont know how to assist as your environment seems to be in a bad state not getting updates from us.
Perhaps if you do a repair install, or install to the August release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by thomgerm** [comment]
Jenefer, if you still read this - when checking the connections and other things the flow updated (driver in brackets) and everything is working fine now. We did run any update process so we do not have a good explanation but it works now and that is most important. Thank you for your help
Thomas

**Comment by Jenefer-Monroe** [comment]
Oh wonderful news, thank you for letting me know!
