### ISSUE TITLE
[CoE Starter Kit - QUESTION] Confirm what tables in Dataverse are written when ActivityFeed.Read permission is enabled.

### ISSUE THREAD

**Issue by GeeLau8** [microsoft/coe-starter-kit#6322]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

As part of our due diligence, we need to understand what tables within Dataverse are updated when the ActivityFeed.Read is enabled.
<img width="317" alt="ActivityFeed Read API" src="https://github.com/microsoft/coe-starter-kit/assets/140720191/a94e36b5-cc61-4ea3-a25a-2dbac9df659f">

This will allow us to build appropriate security roles within Dataverse to prevent non Admin users from accessing this information. 

Thanks in advance, 
Gee

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
The **Audit Log** table is populated with App Launch information retrieved from the Microsoft Purview Audit Log. This process only happens once the related flows are turned on as well - see here for which flows those are: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
