### ISSUE TITLE
[CoE Starter Kit - Switch to Dashboard to Dataexport - Audit logs table still used?

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#6323]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

when I switch an CoESK installation form cloud flow inventory to Dataexport. 

Will the data collected from the audit logs in the audit logs table and the data in the datalake will be combined, or do I only see/use the data form the datalake? 
In the CoE Apps and the Dashboard?
If only the Datalake is used, do I still need the Audit Logs table content? 

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
The dashboard is set up to combine data from your Audit Log with usage from the Data Export so you don't lose any usage/adoption insights (such as when an app was last launched) when you switch to Data Export. 

The Audit Log solution itself is no longer needed when you switch to Data Export, as that information is gathered from elsewhere. But if you want to seamless reporting, the Audit Log table is still used in the dashboard in combination with usage data from Data Export.

**Comment by lukas-nC** [comment]
thanks Manulea
Is there some sort of dublicate identification?
So that it is possible to start gathering the data from Dataexprt now and switch the database of the CoESK and the PowerBI dashboard later?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
