### ISSUE TITLE
Error while upgrading Microsoft Center of Excellence (CoE) from 4.8 to 4.13

### ISSUE THREAD

**Issue by STLCC-SPOSA** [microsoft/coe-starter-kit#6332]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Error while upgrading Microsoft Center of Excellence (CoE),  from 4.8 to 4.13 after about 45 minutes got an error.  I did remove id guids changed with {guid}

`Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 3 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: {guid}, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Deprecated | [Child] Admin | Sync Logs, Id: {guid}, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: {guid}, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5ff18d20b7ec3dbffe_a3e3b, Id: {guid}, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: {guid}, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: {guid}, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .`

### Expected Behavior

Import to be successful 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Core

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1.   Walk through the import wizard.
2.  select the CenterofExcellenceCoreComponents_4.13_managed.zip
3. Error occurs approx 45 minutes later.

### Anything else?

I did assume the issue may be related to the variable: Audit Logs - Client Azure Secret not being set.  So when I tried to set got error message similar to: User is not authorized to read secrets from {variable I tried to Enter} resource

Currently both 4.8 and 4.13 show as installed.

![image](https://github.com/microsoft/coe-starter-kit/assets/111318875/c946974a-4c66-467c-9ba7-5f7c275dd77c)

When looking through the history see error  as in screenshot below.
![image](https://github.com/microsoft/coe-starter-kit/assets/111318875/f410f44e-feea-4ac2-8f3f-2d1437619fcc)

retried upgrade and got error 80048539.  {already upgraded.}

**Comment by Jenefer-Monroe** [comment]
Hello. This is a known issue due to the deprecation of the Audit Logs Custom Connector methodology. 
Please see https://github.com/microsoft/coe-starter-kit/issues/6018 for steps to address.
