### ISSUE TITLE
[CoE Starter Kit - Feature]: Power BI Report Manage App Access and Manage Flow Access Data 

### ISSUE THREAD

**Issue by winniemangeni** [microsoft/coe-starter-kit#6333]
### Is your feature request related to a problem? Please describe.

I have been configuring the PBI Manage App Access and Manage Flow Access tabs. However, the admin_appid and admin_environmentid fields do not show on the Manage App Access and similar to the Manage Flow Accees.  I decided to use the fields on the screenshot below the app showed and I selected my Production environment.  However to grant access I can see all admins from other environments. Is it possible to just drill down to my admin environment rather than all? What are the correct fields I should be selecting for both of these tabs?
![Snag_2933a94b](https://github.com/microsoft/coe-starter-kit/assets/112147926/9463b026-c76f-4fef-9ef4-b880a049eaf8)

When I select the filter button and set it to just my environment, it still shows all other environments on the Power App that grants access. What are the new fields to use? 
![image](https://github.com/microsoft/coe-starter-kit/assets/112147926/561af024-c5e5-4828-b0e7-7110f86b04a4)

### Describe the solution you'd like

The Power App is working on my end but the data poits are not correct. When I select the filter button and set it to just my environment, it still shows all other environments on the Power App that grants access. What are the new fields to use? 

### Describe alternatives you've considered

I have refreshed data and also deleted app and redid the steps again in the correct service account and environment.

**Comment by Jenefer-Monroe** [comment]
Hello. These steps are no longer needed. Please see [Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard)

You now just need to "reset the default" and then select the app again.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
