### ISSUE TITLE
[CoE Starter Kit - BUG] On refresh, the column "admin_stateorprovince" of the table wasn't found

### ISSUE THREAD

**Issue by jackmicrosoft** [microsoft/coe-starter-kit#6336]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I've downloaded and extracted the latest CoE (August). After inputting my CoE environment URL, the datasource refresh begins. It soon errors out with this message: the column "admin_stateorprovince" of the table wasn't found.
Please help

![Screenshot 2023-08-14 122552](https://github.com/microsoft/coe-starter-kit/assets/141290680/67ac80c0-18ad-4be6-982c-d30e1d32c307)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2023

### What app or flow are you having the issue with?

Production_CoEDashboard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
The Power BI dashboard pulls it's data from the CoE kit environment, specificially from the tables that get installed via the Core Components solution. The Power BI dashboard version always goes hand in hand with the Core Components release version - we've introduced a new column in a table with the August release, that the dashboard now uses. So you will have to upgrade your Core Components version in your environment before you can use the August release of the Power BI dashboard.

**Comment by jackmicrosoft** [comment]
Thanks Manuela - I'll give that a go!


Thanks,

Jack McCardel  (He/Him)

SharePoint and Power Platform Developer

MᶜConnell Dowell

M: +61 491 332 744

This email, including any attachments, is confidential and may be privileged. If you are not the intended recipient please notify the sender immediately, and please delete it; you should not copy it or use it for any purpose or disclose its contents to any other person. We may collect personal information in the course of our interactions with you. For further information please see our privacy collection notice available on our website.

________________________________

**Comment by Jenefer-Monroe** [comment]
closing out as a dupe then. thank you!
