### ISSUE TITLE
[CoE Starter Kit - QUESTION] UAT Environment Set Up

### ISSUE THREAD

**Issue by uzma-fis** [microsoft/coe-starter-kit#6339]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Looking for some best practice/advice here. 

The toolkit is best installed in a pre-production/UAT environment so we can test the release in a small set of testers/admins and then released to production for wider usage by admins and makers. 

We currently have the toolkit installed in a different test tenant, which is causing us issues due to licenses/email/no data for us to test with. 

I plan to create a new environment in our tenant and install the toolkit as a test arena only, with focus to getting the governance area/clean up orphans reviewed

HOWEVER, I am looking at what is the impact of running an install in our "live" tenant. 

- Notifications to makers - I will ensure that this flow does not run as we already have this running
- Clean up objects - I am right in thinking that this will inevitably run in the uat COE rather than us using the live COE. 

Therefore our test/flow run will ALWAYS be in our live? 

What is the best practice and flows we should be mindful of not running when we want to test the UAT environment? 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

June 2023 4.9

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

there's an environment variable called ProductionEnvironment which by default is set to yes, that you can set to No in your UAT/Test environment. With this environment variable set to NO, all of the emails that would usually go to makers/end users are redirected to the admin email address instead. This means you can test your governance flows as well, and review the emails that your makers would get before enabling them in Prod.

Hope that answers your question,
Manuela

**Comment by uzma-fis** [comment]
Ha that's brilliant. Thanks for the reply. Just seen your YouTube tutorials on governance too so nice to meet you!

**Comment by uzma-fis** [comment]
In terms of governance flows, we can run them and the notifications will not be issued BUT we can review the flows involved and look at what COULD have been sent out right?

**Comment by Jenefer-Monroe** [comment]
The notifications are issued so that you can test them. But they are sent to Admin you have configured instead of the Maker.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
