### ISSUE TITLE
[CoE Starter Kit - BUG] Sharing Set App Permissions - 'user with object id does not have any access to permissions 'manageanypowerapp'

### ISSUE THREAD

**Issue by uzma-fis** [microsoft/coe-starter-kit#6341]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have seen this should have been fixed in May 2023 but for the App Catalog but I am experiencing it in the canvas app Set App Permissions in the June 2023 Release. 

I can note that the editors number is missing compared to admin log in. As the user scrolls down the app, the error messages are persistent. 

What permissions SHOULD the users be granted to use Set App Permissions

### Expected Behavior

App should run with no errors. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023 4.9

### What app or flow are you having the issue with?

Set App Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1) Go to Admin Command Center
2) Click on Set App Permissions
3) Click on Orphaned Apps
4) Scroll. 

![image](https://github.com/microsoft/coe-starter-kit/assets/141040714/0b4d463e-7371-405b-b64a-78f6f6a36a2c)

**Comment by uzma-fis** [comment]
https://github.com/microsoft/coe-starter-kit/issues/5340 as reference

**Comment by Jenefer-Monroe** [comment]
oh ok yes. The sharing of the app in the App Catalog just grants them permission to the app in question. It does not do things to grant other needed thign for the app. 

So for example if you had an app showcased in there that had a SQL dependency, getting access to the app woudl not auto-update the SQL to allow that user. The maker will need to do that. But this will let them see and use the app. 

In the case of the Set XX PErmissions apps, users need the Power Platform Admin Role to update permissions for apps/flows across the tenant.

**Comment by Jenefer-Monroe** [comment]
You can find specifics like this for apps in the documentation
https://learn.microsoft.com/power-platform/guidance/coe/core-components#set-flow-permissions
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/99b67f07-f78e-408b-b449-b7c53ba151a1)

**Comment by uzma-fis** [comment]
Thank you for explaining! I should have taken a look at the CoE page before sharing

**Comment by Jenefer-Monroe** [comment]
You are most welcome

**Comment by cihys** [comment]
Is there a way to set this permission for a custom security role?
