### ISSUE TITLE
[CoE Starter Kit - BUG] Environment name doesn't change in Flow or App tables after name change

### ISSUE THREAD

**Issue by lukebrandt** [microsoft/coe-starter-kit#6343]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are experiencing an issue where an environment name was changed and the name change does show in the Environment table (Environment column), but the Flow or App table retains the old Enivornment name in the Environment column.

### Expected Behavior

The expected behavior would be to have the new Environment display name display in the Flow and App tables

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.42

### What app or flow are you having the issue with?

Flow and App tables

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Change the name of an environment.
2. Look at the data in the Environment table.
3. The name displayed in the Environment column is the new name
4. Look at the data in the Flow or App table.
5. The name displayed in the Environment column is the old name.

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot for clarity? I do expect the lookup field to update after the next run of inventory. If that doesnt happen then turn the driver flow off and on and see if that fixes it. Sometimes the flow caches the calls to the Power Platform.
However the fields that are a copy (like Environment Display Name) will likely not update until they are edited again unless you force an inventory run for them using the flag shown below (which will run next day)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b951e2d7-8036-4568-bda0-83c5e79e5703)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e7939d40-ba55-4a22-9f3a-f10c75be15f7)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
