### ISSUE TITLE
[CoE Starter Kit - BUG] Archive Request Cleanup view on Cleanup Old Objects App not returning list of Apps/Flows

### ISSUE THREAD

**Issue by GTInc1** [microsoft/coe-starter-kit#6344]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

'No apps to Display' message appears on Archive Request Cleanup view within Cleanup Old Objects App when clicking on 'Apps' or 'Flows' for each user, despite previous page detailing several apps/flows have been ignored. 

![image](https://github.com/microsoft/coe-starter-kit/assets/140699612/4d9866c2-0804-40f1-9cd5-55d905bbfafd)
![image](https://github.com/microsoft/coe-starter-kit/assets/140699612/89e82103-6656-40f2-9fc4-204b65d92411)

### Expected Behavior

Expected to see list of apps/flows for each employee to either send a reminder or reject the request for deletion.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.8.1

### What app or flow are you having the issue with?

Cleanup Old Objects App

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Select CoE Starter Kit environment
2. My Apps > run Cleanup Old Objects App
3. Select User View > Select User > Apps/Flow button
4. App/Flow view displays message 'No Apps to Display' or 'No Flows to Display'

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/140699612/4d9866c2-0804-40f1-9cd5-55d905bbfafd)
![image](https://github.com/microsoft/coe-starter-kit/assets/140699612/89e82103-6656-40f2-9fc4-204b65d92411)

**Comment by Jenefer-Monroe** [comment]
Hello. I dont repro this. Could be a bug in the past that was fixed as Gov is now on 3.11. 

When you first browse to that page it shows your data as shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6e90615a-3739-46ca-9f38-997a858c4d27)

Then when you click on an employee it will show theirs:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/685a454d-65bd-4abb-b8f7-8480ffa353b0)

Then clicking on Apps brings you to the list:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/778a5cee-5147-4c8d-b66f-8a3ec40b751b)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/baed83ab-d79c-4bc3-b5c9-c8b3b688f3d0)

**Comment by GTInc1** [comment]
Can replicate until list of apps/flows screen then shows 'no apps to display'.

Thanks, will look to upgrade.
