### ISSUE TITLE
[CoE Starter Kit - QUESTION] Configure Dataflows (Data Export)

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#6345]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Please could I check whether we have to configure the dataflows for data export each time we update the CoE toolkit? As this takes me a couple of hours given the number of dataflows that need to be updated and queries that need to be authentictated.

<img width="760" alt="CoE140823" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/049ade50-2759-4738-a70f-5521c9105c0f">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2023

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately you do need to do that. This is just a product limitation around dataflows and solutions not specific to our use case. Over time this does get faster, I am able to do this in about 20 minutes now. I know thats still a lot of time but there isnt anything we can do about it unfortunately.

**Comment by G1982C** [comment]
Thanks Jenefer. You are super fast as I could never do it in 20 mins, maybe your tenant is faster than mine when it comes to the authentication part as that is the bit that takes time.
