### ISSUE TITLE
[CoE Starter Kit - BUG] Dataflow Unable to create OAuth Connection

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#6347]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have updated the CoE toolkit to the latest version and running through the upgrade Wizard, I am at the point of configuring the dataflows. When I open up the CoE BYODL Maker dataflow, I have updated the parameters, then selected a table, select Configure Connection and when I tried to sign in as Orgnizational account I get the error below

<img width="844" alt="CoE1408231" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/7e62c001-30f2-4cf1-b80b-45074caaa30d">

I have updated the dataflows a number of times before without issues, so not sure why I am getting it this time round on doing the upgrade.  

### Expected Behavior

Selecting Sign in will allow for you to sign in. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Dataflows

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Open CoE BYODL Makers dataflow
2. Update the DatalakeURL and Environment API parameter
3. Select a table
4. Select configure connection
5. Select Sign in

**Comment by G1982C** [comment]
Correct. I have it set to https://mydataexport.dfs.core.windows.net/powerplatform

I have /powerplatform at the end as per the learn material. Is that correct?

**Comment by G1982C** [comment]
In case this might be helpful, in the connection name it is https://mydataexport.dfs.core.windows.net/powerplatform/powerapps/environments

**Comment by manuelap-msft** [comment]
Can you confirm the permissions you have on the storage account?

##Confirm Storage Account permission
1. Navigate to [portal.azure.com](https://portal.azure.com/).
2. Search for or select the storage account configured to receive [Data Export data](https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics#set-up-the-data-export-process-for-your-tenant).
3. Select Access Control (IAM).
4. Select View my access
5. Confirm you have the Storage Blob Data Reader role assigned. Confirm your account has the Storage Blob Data Reader role.

![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/7527c5aa-398c-47e6-b583-94013ff890de)

Note that even if you are the owner of the storage account, or have contributor access already, you still need Storage Blob Data Reader role assigned as well.

**Comment by G1982C** [comment]
Thanks Manuela. I did check this earlier and could see that it has full access. I assumed as this account has worked previously and nothing should have changed, that full access was correct. See below. Is my assumption of having full access correct?

<img width="616" alt="CoE1408232" src="https://github.com/microsoft/coe-starter-kit/assets/117096415/1b4564d1-3b85-4425-a7b7-c896f4c582f9">

**Comment by manuelap-msft** [comment]
I'm unfortunately not an expert when it comes to permissions here, but it looks like you're inheriting the permissions from the Resource Group. Can you try assigning the Storage Blob Data Owner or Reader role directly on the resource so that under Scope it says "This resource"?

If that doesn't work, I'm unfortunately out of ideas. You may have to raise a Microsoft Support ticket to get further assistance on how to connect there, the CoE kit is just using out of the box platform capabilities here.

**Comment by manuelap-msft** [comment]
Hello,

we've just learned today that a bug has rolled out to Dataflows that stops users from creating new connections. This seems to impact the Dataflow feature (nothing to do with the CoE kit). The Engineering team is aware and is working on a fix. I can keep you updated here as I learn more, or you could also raise a Microsoft Support ticket to be kept up to date by Engineering directly. 

Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
