### ISSUE TITLE
[CoE Starter Kit - QUESTION] PowerBI "manage flow access"  & "Manage App Access"

### ISSUE THREAD

**Issue by STLCC-SPOSA** [microsoft/coe-starter-kit#6348]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The PowerBI template Production_CoEDashboard_August2023 "manage flow access" & "Manage App Access"  When trying to goto the tabs I gett message "Sorry, We didn't find that app."

When clicking more get "The environment '{guid}' could not be found in the tenant '{guid}'.

Session ID: f7ec87c9-929f-4055-83b5-fe94493972ed

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

PowerBI

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, did you perform the steps described here? Basically you need to do a **_Reset to default_** and then select your local version of the app. [Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard)

Note that we did ship the PBIT file with a bug this month so depending on when you downloaded, you may need to [download again](https://aka.ms/coestarterkitdownload).

**Comment by STLCC-SPOSA** [comment]
The reset did appear to make a change, I did pick the "Admin - Access this Flow" & "Admin - Access this App" 
It appears to be working now when I goto the App Deep Dive & Flow Deep Dive and right click "Drill Through"
The Flow is giving permission error on our service account for the Default environment.  But that is a different issue to work through.  Thanks
