### ISSUE TITLE
[CoE Starter Kit - QUESTION] My wizard didn't install some environment variables. What is variable 'admin_AuditLogsAudience'

### ISSUE THREAD

**Issue by mcozza** [microsoft/coe-starter-kit#6349]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

HI! I am setting up the CoE and for some reason the wizard did not set up the variables that said "Leave empty".  
I am just having difficulty with turning on a flow that gives me this error: ****Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_AuditLogsAudience'."}}".****

Which I can update that variable except I don't know what a "admin_AuditLogsAudience" variable is...
Is there a list of variable definitions any where I can reference?  

Thanks :)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello you can find the manual setup instructions here: [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

And specifically here is the information to [update the environment variables](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables)

**Comment by mcozza** [comment]
Ugh Thank you! You're amazing! I totally looked right over it. <3

**Comment by Jenefer-Monroe** [comment]
Glad to help! YEAH! I'll go ahead and close then. Plesae do let us know if you have other issues in the future.
