### ISSUE TITLE
[ALM Accelerator - BUG]: Default Branch May Not Be `main` When Cloning Pipelines

### ISSUE THREAD

**Issue by coatsy** [microsoft/coe-starter-kit#635]
When [Cloning the YAML Pipelines from GitHub to your Azure DevOps instance](https://github.com/microsoft/coe-starter-kit/blob/main/ALMAcceleratorForAdvancedMakers/SETUPGUIDE.md#clone-the-yaml-pipelines-from-github-to-your-azure-devops-instance), the default branch may not be `main` (in my case, it was `devkeydet-coe-523`)

Not picking this up and then going onto subsequent steps can lead to the pipelines being based on a branch other than `main`.

**Suggested Fix**

As this may not be possible to automate (see @mikefactorial's answer to #550), suggest we add:

5. Check that the default branch for this repo is `main`. Choose **Repos** and **Branches** and ensure that the `main` branch is tagged as the default:  

![image](https://user-images.githubusercontent.com/1772428/122215203-4a5bca80-ceee-11eb-81e7-982e34750e38.png)

If it is not, select the 3 vertical dots corresponding to the `main` branch and from the **More options** menu, choose **Set as default branch**

![image](https://user-images.githubusercontent.com/1772428/122215580-b9d1ba00-ceee-11eb-81ac-3e3a529a67e6.png)

**Comment by mikefactorial** [comment]
Thanks @coatsy. Will add this to the July release notes.

**Comment by mikefactorial** [comment]
@coatsy This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.
