### ISSUE TITLE
[ALM Accelerator - BUG]: test Azure API connecotr fails

### ISSUE THREAD

**Issue by ptdominey** [microsoft/coe-starter-kit#6352]
### Describe the issue

Tried testing the Custom Azure Devops connector using the GetOrganizations method and get this result
{
  "error": {
    "code": 500,
    "message": "Variable organization has no value.",
    "source": "europe-002.azure-apim.net",
    "path": "choose[3]\\when[1]",
    "policyId": "",
    "clientRequestId": "e1794e24-6e5e-47c3-98df-2c6a86e978ab"
  }
}
If I test using Postman with Basic Authentication and a Personal Acccess token I can do GetProjects for one of my organisations and it works.  Don't seem to be able to do Get Organisations in Postman either.  If I try GetProjects in the Test panel for the Custom connector I get a similar error even though passing in a valid org

{
  "error": {
    "code": 500,
    "message": "Variable project has no value.",
    "source": "europe-002.azure-apim.net",
    "path": "choose[3]\\when[1]",
    "policyId": "",
    "clientRequestId": "76724d4e-a083-49e5-8967-84dd9436af2c"
  }
}

### Expected Behavior

Response code 200 and a list of organisations in my tenant

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20230405.2

### Steps To Reproduce

See above

**Comment by mikefactorial** [comment]
@ptdominey can you validate that all of the following policies are on the connector? All 6 and in particular the one related to the GetOrganizations action? 
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/aa79d032-2614-440f-a343-7360b6227ef8)
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/10c3f864-bfd0-4665-bc07-145a7e7ea6ac)

**Comment by mikefactorial** [comment]
Also the PAT test isn't a good test since this is an oAuth based connection and you should have a client id, secret and the tenant id set in the security.

**Comment by mikefactorial** [comment]
Might want to refer here https://github.com/microsoft/coe-starter-kit/issues/4826

**Comment by ptdominey** [comment]
I don't see "GetCurrentUserProfile" in the list of paths even when I download the Swagger definition and search in Notepad. Could I have got an invalid API definition from somewhere?

**Comment by mikefactorial** [comment]
@ptdominey the GetCurrentUserProfile action was added in the August release. Looks like you are on an earlier version so that would be why you don't see it. You may want to consider upgrading to the latest release if possible as we've made a lot of improvements since April https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-upgrade-configuration.

**Comment by ptdominey** [comment]
Seems to be working now!

**Comment by mikefactorial** [comment]
@ptdominey thanks for reporting back! Glad to hear it's working
