### ISSUE TITLE
[CoE Starter Kit - QUESTION] QHELP! August Upgrade failing

### ISSUE THREAD

**Issue by KRhoadesHyp** [microsoft/coe-starter-kit#6354]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Help!  I am in the middle of an upgrade of the core components for August & got this error.... where should I look?

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 4 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5f7599b4ac73ffd2b8_4ba0f, Id: dad62cb8-c3a0-ed11-aad1-000d3a170d2c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5f7599b4ac73ffd2b8_2fc5f, Id: 8bb93e39-c1a0-ed11-aad1-000d3a170e81, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5f7599b4ac73ffd2b8_77d1b, Id: bb20d25a-7624-ed11-b83e-002248253268, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5f7599b4ac73ffd2b8_b2a0d, Id: c24af596-f6ef-ed11-8848-002248289af9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
This is an expected failure, due to deprecating the Audit Log solution with this release. Please see a write up on this here https://github.com/microsoft/coe-starter-kit/issues/6018

**Comment by KRhoadesHyp** [comment]
I swear I have followed that & every other thing I can find to the T but it just keeps telling me I have 4 dependencies.   Uber frustrating since it takes an hour & a half to get there.

Kristy Rhoades
Sr. Developer, IT Modern Work Team

**Comment by KRhoadesHyp** [comment]
The dependency error is referring to the custom connector, what will happen if I delete the custom connector before trying to update the Core Components again?

Kristy Rhoades
Sr. Developer, IT Modern Work Team

From: Kristy Rhoades
Sent: Tuesday, August 15, 2023 2:43 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] QHELP! August Upgrade failing (Issue #6354)

I swear I have followed that & every other thing I can find to the T but it just keeps telling me I have 4 dependencies.   Uber frustrating since it takes an hour & a half to get there.

Kristy Rhoades
Sr. Developer, IT Modern Work Team

**Comment by KRhoadesHyp** [comment]
Last email –

I can see the problem but don’t know how to resolve it 🤦 .

***@***.***

***@***.***

Kristy Rhoades
Sr. Developer, IT Modern Work Team

From: Kristy Rhoades
Sent: Tuesday, August 15, 2023 2:53 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] QHELP! August Upgrade failing (Issue #6354)

The dependency error is referring to the custom connector, what will happen if I delete the custom connector before trying to update the Core Components again?

Kristy Rhoades
Sr. Developer, IT Modern Work Team

From: Kristy Rhoades
Sent: Tuesday, August 15, 2023 2:43 PM
To: microsoft/coe-starter-kit ***@***.******@***.***>>; microsoft/coe-starter-kit ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] QHELP! August Upgrade failing (Issue #6354)

I swear I have followed that & every other thing I can find to the T but it just keeps telling me I have 4 dependencies.   Uber frustrating since it takes an hour & a half to get there.

Kristy Rhoades
Sr. Developer, IT Modern Work Team

**Comment by Jenefer-Monroe** [comment]
Correct for whatever reason some people, when they delete the audit logs solution, do not have their connection references deleted. I do not repro but a handful of people have seen this so I went ahead and added it as a step in #6018 to make sure they were deleted.
Manually deleting them from the default solution is how you resolve.

**Comment by KRhoadesHyp** [comment]
@Jenefer-Monroe Thank you Thank you Thank you! The fifth time will be the charm, I can feel it! :-)

**Comment by Jenefer-Monroe** [comment]
wonderful news! ill go ahead and close this out then.
