### ISSUE TITLE
[PP Admin View] - Manage permission (Canvas) : Can't add a new user error (PowerAppsforAdmins.GetAdminAppRoleAssignment)

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#6355]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

hi,
Since the update i have this error when i try to manage permission to a canvas app.
<img width="219" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/714db5fc-0052-4a02-a289-001c73d585dc">

It seems text_2 that correspond to environnement name is lost.
I said that because if i click on add user  i have this

<img width="200" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/0ea6ed59-08f7-49d7-8992-5e4e7b42d4c7">

So i tried with the App SetApp permission. No error. the user is added. 
Also, i check the flow Helper | objectoperation, no error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Select canvas app
2. click on Manage Permissions
3.

**Comment by manuelap-msft** [comment]
Hello,

we accidentally shipped the custom page with some debug code which is causing this issue. Please see this thread on how to resolve this yourself in the meantime. It is also fixed for the next release.
https://github.com/microsoft/coe-starter-kit/issues/6308#issuecomment-1673008884

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
