### ISSUE TITLE
[CoE Starter Kit - QUESTION] How get DLP into CSV

### ISSUE THREAD

**Issue by tomasziss** [microsoft/coe-starter-kit#6357]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

At ISS we’re in the process of implementing the DLP Impact Analysis [Preview] app.
We struggle to export results into a CSV file, which would be very useful to make decisions on next steps.
We would appreciate any help provided. Thank you!

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

could you please describe in a bit more detail what you struggle with? Are you seeing an error message? Can you check the DLP Editor>Parse impacted resources into CSV flow to see if there's any error messages?

Thank you
Manuela
