### ISSUE TITLE
[CoE Starter Kit - BUG] Deleted apps still showing in the CoE (been one month since deletion)

### ISSUE THREAD

**Issue by victoria-vassi** [microsoft/coe-starter-kit#6358]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Apps are still appearing on the Center of Excellence Toolkit after deletion. We have also done similar processes in the past (as near as last month, with the same version of the Center of Excellence toolkit in place), and the related apps deleted on those processes are no longer appearing on the toolkit. However, now, this is not the case: many of the deleted apps are still referenced on the CoE toolkit.

The related flow (‘CLEANUP - Admin | Sync Template v3 (Check Deleted)’) was executed manually by me yesterday, but to no avail (I was hoping that the fact that the default scheduling of 1 week was the cause of the delay, but it seems to not be the case). There’s no error on its execution, nor on the child ‘CLEANUP HELPER - Check Deleted (Canvas Apps)’. The environment variable related to this topic is set to delete the applications also from the Dataverse on the CoE (‘admin_DeleteFromCOE’ = true).

I’ve checked that the applications were effectively deleted (using Get-AdminPowerApp cmdlet), that the PowerBI report has no synchronization issue, and that the related Dataverse table (‘PowerApps App’), indeed, does still contains those deleted apps… So, the problem is somehow related with the ability of the CoE flows to identify those apps as deleted, and to potentially remove them from the Dataverse table. 

### Expected Behavior

Deleted apps not to appear in CoE

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)’

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Are you using Data Export or Sync flows to gather your inventory? This can be found here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f7b450c8-871e-48a1-bc9e-d19311c4e0e8)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
