### ISSUE TITLE
[ALM Accelerator - BUG]: Setup Documentation Sequencing - Create Pipeline Global Variables before Service Connections Created 

### ISSUE THREAD

**Issue by coatsy** [microsoft/coe-starter-kit#636]
In the [Setup Pipeline Global variables](https://github.com/microsoft/coe-starter-kit/blob/main/ALMAcceleratorForAdvancedMakers/SETUPGUIDE.md#create-pipeline-global-variables) section of the setup guide, there's an instruction to add the `ValidationServiceConnection` variable, which is described as

> [The url of the validation instance of Dataverse e.g. https://deploy.crm.dynamics.com/] NOTE: This must be **identical** to the Azure DevOps **Validation Environment Service Connection** name you specified previously including any trailing forward slash. This environment will be used to run solution checker during the build process.

However, this service connection has not yet been created - it's done in the **Development Project** section further down the document

**Suggested Fix**

Either

move the [Create Service Connections for DevOps to access Power Platform](https://github.com/microsoft/coe-starter-kit/blob/main/ALMAcceleratorForAdvancedMakers/SETUPGUIDE.md#create-service-connections-for-devops-to-access-power-platform) above the pipeline section

Or

leave `ValidationServiceConnection` out of the variable group for the pipeline variables section and then come back to it after the service connection section

**Comment by mikefactorial** [comment]
Thanks again @coatsy. There were some updates to the last release that didn't get merged in during the release. This is one of them since ValidationServiceConnection variable is no longer used. Adding to doc updates in July release

**Comment by mikefactorial** [comment]
In addition to removing the ValidationServiceConnection from the global variables in the doc. Also, need to remove PipelineIdToLoadJsonValuesFrom as neither of these variables are used by the pipelines since the last release

**Comment by mikefactorial** [comment]
@coatsy This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.
