### ISSUE TITLE
Admin - Sync Template V3 Apps Flow doesn't show data for Default Environment

### ISSUE THREAD

**Issue by VimmiRawat** [microsoft/coe-starter-kit#6361]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Admin - Sync Template V3 Apps Flow doesn't show data for Default Environment

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin - Sync Template V3 Apps

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello we have moved to a new systemm for inventory of apps and flows with a v4. Plesae ugprade to see those improvements.

**Comment by Jenefer-Monroe** [comment]
Sorry by v4 I meant the name on the flow, not of the solution. 
v 4.13 of core no longer uses a flow called Admin - Sync Template V3 (Apps) or Admin - Sync Template V3 (Flows)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
