### ISSUE TITLE
[ALM Accelerator - QUESTION] Non-compliant Power Automate Cloud Flows due to Service Principal

### ISSUE THREAD

**Issue by kimjensen90** [microsoft/coe-starter-kit#6362]
### What is your question?

Hi guys, 

Thanks for the awesome work! 

Now that MS is enforcing the limitations of using Power Automate with a Power Apps Premium Licenses (See this: https://learn.microsoft.com/en-us/power-platform/admin/power-automate-licensing/faqs#enforcement), I don't believe that using a service principal for delpoyment of solutions with the ALM Accelerator is feasible, since you cannot assign a license to such an entity - to my knowledge. I'm obviously hoping that I am wrong and that there is a workaround. What are you inputs on this?

I'm currently investigating non-compliant cloud flows within my tenant and some show with the error message: 
![image](https://github.com/microsoft/coe-starter-kit/assets/104207653/8b5d8f1d-0f80-4ea9-a1fa-e96c88fdcf68)

What can I do to get around that? 

Thanks so much for your support! 

/Kim 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

July 2023

**Comment by mikefactorial** [comment]
@kimjensen90 from an ALM Accelerator standpoint you can update the ownership of the flows after they are imported to a licensed user. As far as licensing goes I can't claim to be an expert in this area, but it does read as if you would need a Power Automate Process license for each of the flows if they remain owned by the Service Principal. 

@RajeevPentyala @jenschristianschroder for visibility

**Comment by kimjensen90** [comment]
@mikefactorial yeah, that is true and would solve the problem momentarily, but on the other hand I would prefer if these flows weren't owned by actual people as they could be rather critical. But as you say, I could also choose to license the flows individually, but that would require 4 licenses, right (DEV, VAL, TEST, PROD)? 

I know we're a bit off topic here, but thanks for your input!

**Comment by mikefactorial** [comment]
@kimjensen90 I lost track of this issue and didn't see your last message. I'm not sure I know the answer to the question of licensing per environment. My licensing knowledge is fairly limited, but if you found an answer that might help others (including myself) would be great to know. Closing this out for now.
