### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to add makers to the Power Platform Maker Microsoft 365 Group

### ISSUE THREAD

**Issue by yveskerwyn** [microsoft/coe-starter-kit#6363]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

As documented: Makers are automatically added to the **Power Platform Maker Microsoft 365 Group** with the **Admin | Add Maker to Group** flow and as part of the **Admin | Welcome Email v3**.

In our case we see all makers in the **Maker** inventory table, but not in the **Power Platform Maker Microsoft 365 Group**. So the **Admin | Add Maker to Group** flow was never run.

Is it normal that the **Admin | Add Maker to Group** flow was never not run?

How are we supposed to bring the **Power Platform Maker Microsoft 365 Group** in sync with the **Maker** inventory table?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
If the flow was not on when someone was added to the table then they would not have been added to the group. 
We do have on our backlog adding some UX to do a backlog fill / delete / etc. But we have not been able to fund that yet due to competing higher requirements. 
So you would need to manually do this or write a quick flow to add all users in that table to the group.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team

**Comment by yveskerwyn** [comment]
@Jenefer-Monroe, your suggestion to "create a quick flow to add all users from the Makers table to the Makers group" will not work because we are in a hybrid setup: Groups synced from on-premises Active Directory can only be managed in the on-premises Active Directory. So, adding users via a Cloud Flow to the AAD group will not work, as documented here: https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/concept-learn-about-groups

And this is also the reason why no users got added the Makers group in the first place, the "Admin | Add Maker to Group" flow always fails with a "Authorization RequestDenied" (403) error.

Other suggestions are welcome :-)
