### ISSUE TITLE
[CoE Starter Kit - BUG] Error on unquarantining Apps

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#6364]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

When we are trying to unquarantine app from 'Unquarantine App' button from menu , it throws below error for some apps 

<img width="1193" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/c972916c-90c9-4013-a850-b242615c14eb">

<img width="820" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/1ff6b357-53d8-4f6c-b992-4ddfe6ded192">

When we are changing the quarantine status from the Business Process flow, the app doesn't get quarantined instead it gets sit into Deleted Apps 

### Expected Behavior

The apps should get Unquarantined without throwing error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July

### What app or flow are you having the issue with?

Admin sync Template- V3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Go to Power Platform Admin view
2. select any quarantine app 
3. Try to unquarantine with Unquarantine App button on the menu 
4. PS: throwing this Error only for some apps and not all apps

**Comment by Jenefer-Monroe** [comment]
We do not repro so you will need to find the case with which you repro, perhaps the app is deleted but not yet noted as deleted, etc. 
And then there was a bug in the past in which one of the buttons brought up the wrong dialog (the delete dialog) but that has been resolved.

**Comment by PPMini** [comment]
ok sure, we ill investigate a bit more to see in which scenarios. It is happening. Thanks a million.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
