### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cleanup Orphaned Makers Managers

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#6365]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have several resources that are orphaned due to Makers leaving the organization. Is the Maker data with their managers coming from AAD? How often is this updated for all Makers and is this also updated when the process runs?

From the data I pulled the Makers do not have a manager or it shows them listed themselves but I can see an M2 Manager, is this used to send the teams notifications or only the first manager field?

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/4e174cd3-7f8a-4bef-aab0-cf1194ed6f15)

Thanks in advance!

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
This is filled by the **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** flow and does use the information from AAD. 
We added the feature to track this probably a year to a year and a half ago, so if they left the organization before then, the table will not contain their managers. 
We do not use M2 for any of our processes, we just added it so others could extend to using it if they wanted. Like an escalation up the chain.

**Comment by santiareh** [comment]
Fantastic! Thanks for such a quick response, it is very appreciated!

**Comment by Jenefer-Monroe** [comment]
So happy to help!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
