### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Only Showing one Environment in Power BI Report

### ISSUE THREAD

**Issue by JeromieSkypoint** [microsoft/coe-starter-kit#6366]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When viewing the Power BI Report, there is only one environment showing when there should be multiple. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2023

### What app or flow are you having the issue with?

Power BI Report

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Typically this means that the user that setup the kit does not have the Power Platform Admin Role permanently assigned and so the inventory only collected the envts to which it has access. 
Please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7b048069-921f-4438-8c6e-7311eee58c76)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
