### ISSUE TITLE
[ALM Accelerator - BUG]: Commit is failing

### ISSUE THREAD

**Issue by challa85** [microsoft/coe-starter-kit#6374]
### Describe the issue

Committing the solution to ADO is failing in the 'pac - Clone or Sync Solution' step with below error.

Error: Could not find a part of the path 'D:\a\1\s\GOPSQuality_MEHP_MFGExceptionHandling_ALMDeploy\GOPSQualityMEHPManufacturingExceptionHandling\SolutionPackage\GOPSQualityMEHPManufacturingExceptionHandling\src\environmentvariabledefinitions\mehp_EnVarMEHPEnvironmentName\environmentvariabledefinition.xml'.

### Expected Behavior

Commit should be successfull.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

CenterofExcellenceALMAccelerator_1.0.20230802.1_managed

### Steps To Reproduce

1. Created new profile
2. Commit solution to  repository
3. It's failing in 'pac - Clone or Sync Solution' step

**Comment by mikefactorial** [comment]
@challa85 this looks to be a windows max path issue. The max path in windows is 256 characters and the path in question is 263 characters long. Unfortunately, we have no way of bypassing this restriction at the moment in Azure DevOps hosted agents. Might recommend using a shorter name for the repo however if possible.

**Comment by mikefactorial** [comment]
Closing this out for now as there's nothing more to do here currently.
