### ISSUE TITLE
Find Licenses by user

### ISSUE THREAD

**Issue by pwbcan** [microsoft/coe-starter-kit#6378]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a feature or report in the CoE, that will allow an export or view of the licenses assigned per user?

This would be very helpful as license management is a major task in the Power Platform.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
