### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Missing Dependencies Importing into Dataverse for Teams

### ISSUE THREAD

**Issue by pstork** [microsoft/coe-starter-kit#6379]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Importing the COE Starter Kit Core Components into a Dataverse for Teams environment fails because of a missing dependency.  I think it is dependent on the Power Apps Checker Base solution which is automatically in a regular Dataverse environment but not in a Teams environment.  Its looking for a Web Resource called accessChecker_openDialog.

### Expected Behavior

I expected to be able to import the solution into a Dataverse for Teams environment after importing the Creator Kit solution which is also a dependency.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

All of them

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Create a Dataverse for Teams environment in the Power Apps client in Teams by creating a blank app.
2. Import the Creator Kit Solution into the Teams environment
3. Import the CreatorKitCore_1.0.20230421.1_managed.zip solution into the environment.  You will receive an error about a missing dependency.

### Anything else?

<img width="462" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/12916548/af158dae-7029-45c7-9f87-483d6ca5a7f8">

**Comment by manuelap-msft** [comment]
It changed in September 2022
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2022

**Comment by pstork** [comment]
OK, but the announcement says that we can still download it for use in Dataverse for Teams.  Just that bugs won't be fixed.  Any idea what solution contains the Web resource that is causing the problem?  If I can import it I'll fix any necessary bugs myself.  But I can't fine where the dependency is coming from.

**Comment by manuelap-msft** [comment]
You're trying to import the latest version. That's not supported. You'll have to import the Dataverse for Teams specific version from  the Sep 2022 which you can download from this folder:
https://github.com/microsoft/coe-starter-kit/tree/main/CenterofExcellenceResources/Release/Collateral/CoED4T

Blog posts always just represent a moment in time. The best way to keep up to date with the CoE kit is by subscribing to our release notes on GitHub, and looking at the documentation under https://aka.ms/coestarterkit

**Comment by pstork** [comment]
Thanks for the link to the previous version.

**Comment by Jenefer-Monroe** [comment]
Automatic environment cleanup
