### ISSUE TITLE
Last Active of Environments

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#6384]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

It would be helpful to be able see which environments are eligible to deletion to help manage capacity in the tenant.

Is there some way to do this in the Toolkit?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We do not have any concept of "active" for an evironment today although it is on our backlog and we hope to tackle something liket his later this year.

**Comment by pwbcan** [comment]
Is there a way to determine what the last time anyone accessed the environment was?  Regardless of the CoE..?

We are looking to clean up unused Prod and Sandboxes.  These types are not subject to inactivity cleanups in the tenant like developer is.

**Comment by Jenefer-Monroe** [comment]
Here is a product feature that does somethign like this. I have not used it myself and so cannot comment much on it.
[Automatic environment cleanup](https://learn.microsoft.com/power-platform/admin/automatic-environment-cleanup)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
