### ISSUE TITLE
[CoE Starter Kit - BUG] PowerPlatformGovernance_CoEDashboard_August2023 - Cross tenant report issue - add cleanup of records without accountname

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#6387]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Team,

Cross tenant report are outdated from one month, I am not sure in which frequency cross tenant report refreshed and which power automate are responsible for this activity.

When attempting to retrieve the same connection details using PowerShell CMD, the connection is not available.

Please advice to fix the issue.

### Expected Behavior

Report should be updated 
Flow Status : 
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/f99d04b7-8981-4fb4-bf65-233b7936767e)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Visit the "Power Platform Compliance and Governance" Power BI Report
2. Select Cross Tenant Report

**Comment by manuelap-msft** [comment]
Hello,

it's this flow **Admin | Sync Template v3 (Connection Identities)** that gets the info needed for the cross tenant connection references. Can you check if this flow is running successfully? 

Have you set up scheduled refresh on the Power BI dashboard and has it refreshed successfully recently?

Manuela

**Comment by sharmajitendralal** [comment]
Hi, Yes, Flow seems ok

 Admin | Sync Template v3 (Connection Identities): Running Status
 
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/cd1a427e-357f-4560-af65-71e1ab7b49c1)

 Admin | Sync Template v3 (Connection Identities): Running History

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/b79bd5c2-6f91-42b3-aec8-fdfec46c65be)

Power BI Refresh Status:

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/fb115904-1bc4-429d-ae68-8e5b1b4b1be9)

All are seems ok, but there is gap in report, CoE Report showing item exist and active connection however item(Connection) not found using PowerShell, Some cross connection removed using PowerShell CMD last month but CoE report are not refreshed(UpToDate)

**Comment by Jenefer-Monroe** [comment]
Then if there are not unmanaged layers, please check to see which inventory architecture type you are by looking at the value in use for this env var: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/51b330b8-857f-41c9-8f8f-8c2530bba832)

**Comment by sharmajitendralal** [comment]
Hello,

Please find the below details to understand the root cause of this issue , Its seems that there is some issue in Power Automate for specific env. 

No unmanaged solution layer found
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/9d554d4d-40c4-4136-b56a-1b044a1792f5)

Environment Variable :
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/004c49ad-0afc-4e8c-887a-48520d8a0cb8)

Run History: Target Failed
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/3ecc1059-4e2e-4c3c-b123-6788c2b7a569)

Failed Summary : 
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/a664fbc9-8802-4047-b30f-7ad5e24fc322)

Power BI Report : Highlighted content already removed using PowerShell
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/1721585a-cca3-42a0-98cc-dcfa8374b558)

We are using Following script to remove the existing cross connection 
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/1dd43886-1608-45cf-a5a7-b558aed87576)

**Comment by Jenefer-Monroe** [comment]
Yep once the flow fails it wont finish the clean up here.

There should never be records in there with a blank Account name and we do filter those out before adding. 
Can you please see if in the table you have records where Account is blank? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2bc1a2c4-12dd-4673-ba72-41a473738023)

If they are there please delete them, then your flows should pass.

**Comment by Jenefer-Monroe** [comment]
I've added deleting these to the "Delete Bad Data" flow as well. Not sure how they got in there, may have been from an old bug in the flow.

**Comment by sharmajitendralal** [comment]
Let me check and confirm the status

**Comment by sharmajitendralal** [comment]
Yes, I found one record and has been successfully deleted 
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/ae894de7-9e96-4cf7-a5cd-5d115fb273f1)

**Comment by sharmajitendralal** [comment]
ok, Then lets open ticket with MS
