### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by HarishDhauta** [microsoft/coe-starter-kit#6388]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Parent flow is getting failed with following error.

Action 'Update_Environment' failed

### Expected Behavior

In Prod environment COE is working fine, Issue started after upgrading to latest COE version.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync template V3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Global Sony COE Sandbox is the impacted environment, after upgrading to new COE kit. Parent Cloud Flow "Admin | Sync template V3" stopped working.
It is failing with the following error, need your help to correct the flow.

Run Details
Start time
Aug 21, 03:38 AM (7 hours ago7 h ago)
Duration
05:07:28
Error
Action 'Update_Environment' failed

### Anything else?

![COE error](https://github.com/microsoft/coe-starter-kit/assets/131711282/eea9c03e-4164-48ba-9dd3-22dd31be4c82)

**Comment by HarishDhauta** [comment]
Please send me a teams meeting invite or call me on my cell> +91-9654387212

**Comment by HarishDhauta** [comment]
Hi,

 I am trying to turn on this flow but encountered this error, please help.
 
Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'b677aa25-8de4-ed11-a7c7-0022480813ff' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

**Comment by HarishDhauta** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/131711282/f5614159-c93b-4b81-b4f8-4997ebecba6d)

**Comment by Jenefer-Monroe** [comment]
Hello. If you use the Setup Wizard it will walk you through turning all these flows on in the required order. 
If you cannot use the Setup Wizard, and generally speaking for flows, you can see what processes are required for it by showing its dependencies as shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6eb05999-3aed-4b12-b20d-74dd2f1e85c6)

Going to Required objects you can see which Processes are required. That will let you know. These flows (SYNC HELPER - Apps in this case) needs to be on before the selected flow can be turned on.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d7c6756c-f81a-4f0b-8de8-cebf705e38aa)

**Comment by Jenefer-Monroe** [comment]
Closing at as no further action for starter kit team
