### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow turn-off alert from Microsoft Power Automate 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#6389]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team, 

Could you please help me in understanding this or suggest.

suddenly few people in our organization, started receiving Flow turn-off alert from Microsoft Power Automate and due for suspension. kindly take an action. 

 Microsoft Power Automate  sending mails to users with All flows with no owners and have premium licenses  .
 
 These users are not part of any flows , they are like tenant level ,they dont create flows but still they are receiving flows .
 
 Is there any recent update from Microsoft 
 
 On what criteria, users are receiving mails

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin-Sync V3 Template 

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

this repo is specific to issues and questions related to the CoE Starter Kit (https://aka.ms/coestarterkit). We can't help with questions related to Power Platform behaviour all up. The alerts you are referring to are sent directly from Power Automate / Power Platform. You'll have to raise a Microsoft Support Ticket through your usual channels, or (if you have) work with your Microsoft Account Team on reaching out to the Product Group.

Thank you
Manuela

**Comment by pamatihyd** [comment]
Thank you
