### ISSUE TITLE
[CoE Starter Kit - BUG] app is never launched or not used from last one user but still app showing complient.

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#6390]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have deployed CoE starter Kit 2 months back. We observed that multiple apps are there which is not launched from more than 6 months or never lunched. but still showing as a compliant. 

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/d37f8ace-a078-4af2-b006-ef75174ed02a)

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/e33e7e5a-ff66-4b68-aa67-8e23d5b2663c)

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/f0c83f6d-68f2-4c18-9080-160322e76430)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

 Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The compliance processes actually look for frequently used apps, not inactive ones. The point is to make sure you find heavily used apps to meet your requirements. 

Please look through these resources:

- [Inactivity processes](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#inactivity-processes)
- [Compliance processes](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#compliance-processes)

**Comment by sunilmhatugade** [comment]
Request Orphaned Objects Reassigned (Parent)
Request Orphaned Objects Reassigned (child)

both flows are still running since last 24 hr. 

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/35cb6f3b-e86c-4288-b395-bc64d5d216a1)

**Comment by Jenefer-Monroe** [comment]
correct they run waiting for the user to respond.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
