### ISSUE TITLE
[CoE Starter Kit - BUG] Azure AD Connection Failure

### ISSUE THREAD

**Issue by ALongCOT** [microsoft/coe-starter-kit#6395]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are attempting to install the CoE, for the first time, in a GCC tenant.  The [setup page](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components) indicates that, in GCC tenants, the HTTP with Azure AD connection should use https://portal.azure.com for the Azure AD Resource URI.

The account we are using for the installation has both Power Platform Administrator and Global Administrator roles assigned to it, yet the connection produces this error when the Azure URI is used:

![ConnectionWarning](https://github.com/microsoft/coe-starter-kit/assets/25212055/7fe7f629-1d6d-4fe0-a62c-63fcc117c987)

We also get this warning when we run the Setup Wizard.  At the Run Setup Flows stage, the Wizard never allows the advancement to the next stage (Refresh was clicked several times over the span of a couple hours).

![WizardWarning](https://github.com/microsoft/coe-starter-kit/assets/25212055/d21262b9-70a4-4325-b618-c788f0e0b8c7)

For reference, these are the licenses assigned to the account in that tenant:

![Licenses](https://github.com/microsoft/coe-starter-kit/assets/25212055/5c9ea097-6052-4351-a4e6-1687d450393a)

### Expected Behavior

We expect that the user should be able to make the connection, as instructed in the setup.

We expect that the Setup Wizard should run all necessary flows and advance to the next stage.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

All steps to reproduce the errors have been described above.

**Comment by Jenefer-Monroe** [comment]
GCC is currently blocked from install until (hopefully) late this week. Please see https://github.com/microsoft/coe-starter-kit/issues/6074#issuecomment-1686690453

Once unblocked, note that you have configured the HTTP with Azure AD connector wrong. Please see [Create connections](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#create-connections)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5bda03cc-f881-46f1-8482-33fe494202ae)

And that refrence to validate manually is about your needed role not license. Please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/76ee63cd-4fbe-4ab9-aaa2-415dea859713)

**Comment by ALongCOT** [comment]
Thank you, Jenefer, that thread didn't show up in my searches.

Regarding configuration of the Azure AD connection, per your snapshot, the link to the [page regarding Graph service root endpoints](https://learn.microsoft.com/en-us/graph/deployments#microsoft-graph-and-graph-explorer-service-root-endpoints) states that I should use the Azure URI for the second field when configuring for GCC.  If this is incorrect, shouldn't that page be updated?

My coworker who created the installation user account is on vacation until the 30th and he has the MFA for the account, so I'll have to wait for him to return anyway.  Hopefully, MS will have corrected the problem by then.

**Comment by Jenefer-Monroe** [comment]
i pointed there because these two should be the same. I did not double check the entry for GCC but do trust that documentaiton.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cadf85a8-b51a-44ef-beea-514cc3f2bed5)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
