### ISSUE TITLE
Is it possible to force commit where there is nothing new

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#6397]
### What is your question?

Hi,
Sometimes it happens my commit fails by my fault.
If i click on commit again it fails because there is nothing to change. 
So i must open the solution, add a comment when i click on the publish button and after that i can commit.

It's not very convenient.

Maybe the option is in front of me and i don't see it. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

July 2023

**Comment by tomjosbin** [comment]
Hey @tocri,

Rather than making any changes and doing commit again, you could just delete the temporary branch created when you commit the solution.

I will be like yourusername-solution name in your repo specified.

We are following this, which saves time and making unnecessary changes to our solution.

Thanks,
Tom

**Comment by tocri** [comment]
Thanks @tomjosbin. It 's what am i doing for now but the purpose of my question is about makers that have zero knowledge about devops. They can see the error but don't understand it and they often call me or ping me on teams. 
They don't have permission to delete a branch.

I'm curious how do you manage makers

**Comment by tomjosbin** [comment]
Yea, its a problem with Makers who have zero knowledge in DevOps. We have created some documentations for these scenarios and they are making use of it.

**Comment by tomjosbin** [comment]
The users are allowed to delete the temporary branches they own only. Other branches such as Main / solution main branches are locked by policies.

Yes, force commit would be really good if we could get that option while performing the Commit Solution from UI itself

**Comment by tocri** [comment]
Thank you @tomjosbin. 
In the meantime, I will follow your recommendations
