### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Automate flow owner ship change 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#6398]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

few users left the organization, their flows become orphaned now we have changed the ownership of the flows using  CoE Set flow Permission app. 

But Owner it is always showing as loading  even after changing the ownership 

Cant we see the new owner details here ?

![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/6c0cebe0-428c-4353-a987-4f7775a5f6b5)
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin-Sync V3 Template 

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Yes you should be able to see the owner there. Unfortunately this is the Product UX and not the kit so this is a product bug that you will need to bring to product support. 
[Product support](https://learn.microsoft.com/en-us/power-platform/admin/get-help-support)

**Comment by pamatihyd** [comment]
Does it means , we are  changed the actual owner with new owner through Set App permission ?

let say for a flow I have changed the  ownership from X to Y through this set app permission .since it is a product issue that is why it is not coming there. 

But when I verifed using power shell command like below to know the owner details 

Get-AdminFlowOwnerRole -EnvironmentName '' -FlowName ''
we see Y as coowner but still the actuall  owner showing as X only 

How can we make sure if the real owner is changed from X to Y

**Comment by tocri** [comment]
Is it the same behavior with Power Platform admin view? I use rarely Set own permission flow.

**Comment by Jenefer-Monroe** [comment]
Hello. Setting flow owner is only possible for solution aware flows. For non-solution flows we have added a concept of "derived owner" so that you can have a person changed with the flow but this is not recorded anywhere that the product itself recognizes.

**Comment by pamatihyd** [comment]
As per of COE governance Process, we proposed Orphaned process changing Ownership using CoE Tool kit.

we are having around 1200 orphaned flows outside solution only one environment. 

could you please suggest what is best possible way to implement this using CoE tool kit

**Comment by Jenefer-Monroe** [comment]
That is the recommended process. I was just explaining the strangeness of the product behavior that we are working around.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
