### ISSUE TITLE
[CoE Starter Kit - QUESTION] Dev vs Prod

### ISSUE THREAD

**Issue by nickmac88** [microsoft/coe-starter-kit#6400]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Guys,

We are setting up a DEV environment for the COE Starter kit and want to know if after we set the Environment variable to DEV will all the tools act in the exact same way as PROD. Our main concern is that we don't want to get a bunch of duplicate emails and alerts that go out to our end users after we set up the "Govern" tools.

Thanks in advance for any insight you are able to provide.

Nick

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Latest as of August 2023

### What method are you using to get inventory and telemetry?

None

**Comment by tocri** [comment]
hi, 

You need to pass this env variable **ProductionEnvironnment** to **No**

**Comment by Jenefer-Monroe** [comment]
Thank you @tocri for your help! Thats corret the point of this env var is to make it so that communications will go to the configured Admin and not the Maker.

**Comment by nickmac88** [comment]
> Thank you @tocri for your help! Thats corret the point of this env var is to make it so that communications will go to the configured Admin and not the Maker.

Thanks, this has answered my question. I have already set the variable to "No" but just wanted to confirm that notifications would not go out to Makers once I did this.

**Comment by nickmac88** [comment]
Question answered. Thanks, guys!

**Comment by Jenefer-Monroe** [comment]
Sometimes env vars do cache in Flows so to be absolutely certain you may want to turn your flows off and back on. You can see which flows use it by going to its dependencies

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/90b1b821-71ef-4536-b945-aa8b09dbdafe)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b746f30c-166d-43b6-a7a0-69923468d2c9)

**Comment by nickmac88** [comment]
Good to know. Thank you!
