### ISSUE TITLE
[CoE Starter Kit - Feature]: Quarantine / suspend non compliant flows

### ISSUE THREAD

**Issue by josefhagen** [microsoft/coe-starter-kit#6402]
### Describe the solution you'd like

Like the app compliance process, have the possibility to quarantine / suspend non compliant flows. 

### Describe alternatives you've considered

Manually disable non compliant flows.

**Comment by manuelap-msft** [comment]
Quarantining is a product feature that the CoE kit just makes use of. At the moment, quarantining is only supported for canvas apps by the product, so we can't implement it yet for cloud flows. Once it's supported for cloud flows, we can add that in!

Thanks for the suggestion,
Manuela
