### ISSUE TITLE
[CoE Starter Kit - BUG] Security role permission duplicate

### ISSUE THREAD

**Issue by tchinnin** [microsoft/coe-starter-kit#6403]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have thousands of duplicate record for Environment System Admin user in admin_environmentsecurityrolepermission.
The flow Admin | Sync Template v3 (Environment Properties) got hundread of results for List System Admin SRs actions.
I suspect it gets as much SR as much BU in my environment, as SR are duplicate for each children BU.
As a result I got a lot of duplicated record for the same env/user

### Expected Behavior

I should only have 1 record per user per env as system admin.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Environment Properties)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
This was addressed in the August release, see details here:
https://github.com/microsoft/coe-starter-kit/issues/5228#issuecomment-1650504495

You will have to upgrade to the latest version to solve this.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
