### ISSUE TITLE
Shared Groups (how many users in that group)

### ISSUE THREAD

**Issue by sasrsc** [microsoft/coe-starter-kit#6404]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I would like to know the count of how many users (members) if an app is shared with a AD Group
As a baby step - maybe you can just do a count of the members
I realize this could have groups within groups. 
Then as phase 2 - you start counting up all the members of all the groups.
This would appear in the apps/bi that show "shared with counts"
You have a clear count on the App Shared Users
and you do count how many App Shared Groups there are but not how many members in that group.

**Comment by manuelap-msft** [comment]
Hello,

this is already available - can you check if this meets your requirements:

In the Power Platform Admin View app > select PowerApps Apps > select a Canvas App > select the "Shared with" tab
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/1777792c-80d8-4b60-bbc9-779ecec678df)

Here you can see a list of all the users and groups an app is shared with, and in the table the Group Size indicates how many users are in the group (1 if its just a single user).

The Total Shared indicates the added up number of users + users in groups.

**Comment by sasrsc** [comment]
Thank you Manuela…

I hadn’t noticed that… I’m still new to this and not confident it what’s what and more importantly where it is yet.

***@***.***

And it’s even on the BI report…

***@***.***

Richard Clowes
Senior Director ● Travel Operations
Tel: + 1 919 531 7955 ● Cell: + 1 919 413 3084 ● ***@***.******@***.***>
Worldwide Headquarters ● Cary, NC

www.sas.com<http://www.sas.com/>
SAS(r) … THE POWER TO KNOW(r)
