### ISSUE TITLE
[CoE Starter Kit - QUESTION] Orphan App and coe env. access with end users

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#6405]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

During the process of implementing Orphan Objects clean up, the approval contains a link to the Clean Up App that they do not have access to. Does this need to be manually shared with them? Also our CoE is hosted in a specific CoE Environment and the approvals show that environment, even though they do not have access will the approvals still work?
This would extend to the app that is also hosted in that environment, meaning users need access to the CoE environment?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.7

### What app or flow are you having the issue with?

Clean Up Old Objects App

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. 

Approvals have a special case both for envt access and license requirements. Makers can respond to the approval mails and the product grants them a special security role which will let them do that response. 

If you want them to be able to view the app they will need a Power Apps Per User license and access to the Maker SR.

For more information please see [Set up inactivity processes](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components)

**Comment by Jenefer-Monroe** [comment]
Happy to help! I'll go ahead and close then but please do return with other questions as you have them!
