### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Admin Command Center does not list Options for CoE configuration

### ISSUE THREAD

**Issue by WS6303** [microsoft/coe-starter-kit#6408]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,

When I go into CoE Admin Command Center, I can't find Options for CoE configuration.

<img width="941" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/139745339/992231d9-4068-45b3-98ab-df49fb42dc39">

If I use the URL it can display the corresponding service
<img width="611" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/139745339/3ce567ad-2ce6-4b68-a1b5-896e1aeed4a9">

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, per our [limitatons doc]( https://learn.microsoft.com/power-platform/guidance/coe/limitations#supported-languages), the CoE Starter Kit solutions are not localized, and only support English. Add the English language pack to your environment to make sure all apps and flows work. More information: [Regional and language options for your environment](https://learn.microsoft.com/en-us/power-platform/admin/enable-languages)
![image](https://user-images.githubusercontent.com/89584709/224966722-dd5d48e7-780d-46cb-b6ae-507318f03ad2.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
