### ISSUE TITLE
Deleted apps still showing in the CoE (been one month since deletion)

### ISSUE THREAD

**Issue by jorgereales** [microsoft/coe-starter-kit#6420]
Are you using Data Export or Sync flows to gather your inventory? This can be found here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f7b450c8-871e-48a1-bc9e-d19311c4e0e8)

_Originally posted by @Jenefer-Monroe in https://github.com/microsoft/coe-starter-kit/issues/6358#issuecomment-1680766909_

**Comment by jorgereales** [comment]
Hello, 

This is in reference to https://github.com/microsoft/coe-starter-kit/issues/6358. The issue referred there was happening in our tenant, but I was not able to follow-up on that previous issue on time (therefore I'm opening this one now). I can confirm that our configuration for that environment variable is also as shown on the image (so, my understanding is that we are using Sync flows). I've tried now to increase the value for the 'InventoryFilter_DaystoLookBack' to 30, as the flows that were deleted are still appearing on the report. My plan is running again the Cleanup Helper flows. Is there any other action recommended to try to solve this issue?

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

Also also please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by jorgereales** [comment]
Hello,

Please find attached the list of solutions in our environment, as requested:

![image](https://github.com/microsoft/coe-starter-kit/assets/2552595/9db64239-b798-4fbb-bef3-e9f34c9e08fb)

Regarding the Inventory Flows, I've checked that all are active. Solution layer exist only on the 'HELPER - CanvasAppOperations'. What appears on the details as updated properties are 'clientdata' and 'workflowidunique'.

Many thanks for your support!!
Jorge

**Comment by Jenefer-Monroe** [comment]
The look back variable will not help you unfortunatly. 
OK can you please find an object that you think should be deleted from inventory but which wasn't? 

Find it in the table, shown here if it was an app for example. See if the App Deleted field is checked
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/74aafea6-0b68-47a0-aca2-748c8359978a)

If so, let me know, there is an env var that is at play to store deleted records. 

If not, grab the envt name of the envt, go to the helper for that object type and run it as shown here with "CheckIfDeleted" flagged on

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/21930e45-733e-4728-ad5d-a06a47add70f)

Open the resulting run and find your object in here, note its iternation # (ex #5 of 64)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7a5a9a25-ae86-405c-a198-3c799b1ed749)

Show me how it traces through the run from there
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/97477006-07ba-4b9b-a3ac-b4f765a7df22)

**Comment by jorgereales** [comment]
Hello, Jenefer

Many thanks for your support on this!!

After additional investigation with another team, it seems that we might have had another kind of problem not so much with the CoE itself, but with the script that was deleting the apps previously. 

Therefore, it finally seems that the problem was really elsewhere.... Thank you in any case for all your help and insights here, Jenefer.

BR,
Jorge

**Comment by Jenefer-Monroe** [comment]
So glad to hear you got it sorted!
