### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by mrmonto1** [microsoft/coe-starter-kit#6422]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am unable to see Flow data in the Admin Command Center App.  I am trying to follow the steps to update the COE to the latest release to resolve my issue with gathering Audit Logs on the GCC. When checking for unmanaged layers on the inventory flows, I am getting the following error below. 

PowerAutomateManagement.ListFlowsInEnvironment failed: The method 'ListFlowsInEnvironment' has an invalid value for parameter 'environmentName'

The Command center was working fine a few weeks back and I could see Flow statuses. I am not sure what could have changed. I have checked the Power Platform Env Variable and it is set according to the documentation for the GCC - https://make.gov.powerautomate.us/environments/.  Any guidance would be greatly appreciated. Thank you!

![image](https://github.com/microsoft/coe-starter-kit/assets/142948654/b1d6a3de-e96e-4a76-991f-23cf1b8167e8)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July

### What app or flow are you having the issue with?

 Admin Command Center App

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Note that for GCC (and all non-commercial tenants) you will hit issues with the kit currently due to a product bug. 
Please track via https://github.com/microsoft/coe-starter-kit/issues/6074 while they resolve it. 

Once that is resolved its highly recommended you use the setup wizard as it will help with things like unmanaged layers.

For this one, outside of the setup wizard, do you have this flow turned on? Did it run?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1f1a33b7-16ff-4f35-aff4-69e8190e6677)

**Comment by mrmonto1** [comment]
> Note that for GCC (and all non-commercial tenants) you will hit issues with the kit currently due to a product bug. Please track via #6074 while they resolve it.
> 
> Once that is resolved its highly recommended you use the setup wizard as it will help with things like unmanaged layers.
> 
> For this one, outside of the setup wizard, do you have this flow turned on? Did it run? ![image](https://user-images.githubusercontent.com/89584709/263001157-1f1a33b7-16ff-4f35-aff4-69e8190e6677.png)

Yes, it looks like it has been running successfully.

![image](https://github.com/microsoft/coe-starter-kit/assets/142948654/810841f3-7f56-4fa9-bb11-3947526b49bd)

**Comment by mrmonto1** [comment]
Hi @Jenefer-Monroe, what is your recommended path forward? Is there another way to checking for unmanaged layers on the inventory flows? Or am I going to have to do a fresh install of the August release to resolve my Audit Log issues?

**Comment by Jenefer-Monroe** [comment]
I just saw this bug today repro, but a refresh of the app resolved it. Can you refresh the app and see if it fixes it for you too? Could be that we have the envt id fetch adn the call in sep places and have a race condition.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
