### ISSUE TITLE
[CoE Starter Kit - BUG] Dont see all flows using a connector

### ISSUE THREAD

**Issue by c05009a** [microsoft/coe-starter-kit#6423]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Some flows are not appearing on the admin portal, however in the Powerbi dashboard they do.

### Expected Behavior

We're trying to move flows from one environment to another, but must be sure the connectors the flows are using has been migrated to Business as per the policy. But after checking the connectors, we noticed some flows are not being listed, as if they were not created, but when checking the powerbi dashboard we noticed they were there. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

N/A

### What app or flow are you having the issue with?

NewEmailRetentionPolicyAcquisitionsExceptions NewEmailRetentionPolicyWaiversExceptions NewEmailRetentionPolicyLOAExceptions Grant-CSDialOutPolicy_ECS Grant-CSDialOutPolicy_BR

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1.open admin.powerplattform.com
2. Go to Power plattform Admin View
3. locate the connector Azure Automation
4. look for the flows described above
5. go to Flows and look for the flows listed above

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot from Power Platfom Admin View where you are expecting to see your flows listed by connector?

**Comment by Jenefer-Monroe** [comment]
Closing at as no further action for starter kit team
