### ISSUE TITLE
What is the extent of localization in the Toolkit?

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#6424]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are considering rolling out the user facing components (emails, canvas forms for quarantine etc) and I'm having difficulty finding information on whether or not the whole toolkit can be localized.

Can you point me to where it is possible to localize the toolkit?

Thanks!

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

the only localization aspect of the kit today is the ability to make emails available in other languages. You can do this via the CoE Admin Command Center > Customize Emails page > the default language we provide is English, and you can add localized versions of all emails by adding the email body and language code. The CoE kit then picks up the preferred language from a users AD profile to send them the language in their preferred language (if available, if not default to English).

None of the apps are available in localized versions. You'd have to extend the kit to localize the apps, though we do not have experience with that ourselves.

**Comment by pwbcan** [comment]
Got it!

**Comment by Jenefer-Monroe** [comment]
Closing at as no further action for starter kit team
