### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there a flow that automatically adds members to the Maker persona Teams group?

### ISSUE THREAD

**Issue by jackmicrosoft** [microsoft/coe-starter-kit#6425]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi. Over the weekend, a Teams group I had created and associated with the Maker persona in the CoE Upgrade Wizard (August 2023 version) automatically invited about 80 members to the group. I'm the only one who had access to this group so it must have been some automatic flow and I think it was part of the CoE. Is there a flow that automatically adds members to the Maker persona group? If so, can you please let me know which one so I can disable it?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
As part of the inventory process, the CoE kit discovers makers in your organization and adds them to the Maker group with the **Admin | Add Maker to Group** flow.
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/747e24a3-2a59-40aa-beb3-bee4674c1138)

(see our [environment variable documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#all-environment-variables))

You can turn this flow off to stop makers from being added.

**Comment by jackmicrosoft** [comment]
Thanks so much Manuela! Appreciate it

Thanks,

Jack
________________________________

**Comment by Jenefer-Monroe** [comment]
Closing at as no further action for starter kit team
