### ISSUE TITLE
[CoE Starter Kit - BUG] No information about Apps sharing

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#6428]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I'm not sure if this is a bug or if I have set up my new CoE incorrectly.
The Power BI report Production_CoEDashboard_August2023 is not showing any data for "Total Shared With". 
The "Power Platform Admin View" app does show data in the "Shared with" tab.
![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/5a71c225-a1a7-4f6c-a12f-6bfecca1c1bd)

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/0a29b0fb-a15f-47b1-81cf-7c82f37da753)

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/bd956787-eb9b-43f7-a0db-dc2f3a026265)

### Expected Behavior

I'm expecting to see the number of people an app is shared with, when viewing the "App Deep Dive" page of the Production_CoEDashboard report.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August2023

### What app or flow are you having the issue with?

Production_CoEDashboard_August2023.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the Production_CoEDashboard report, click on the "App Deep Dive" page .

**Comment by manuelap-msft** [comment]
Most of the information you're looking for is gathered by this flow 
**CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)**

which runs on a schedule every 2 weeks. Can you check this flow has run successfully? If you've only recently set up the kit, it may hasn't run yet. If it has run and you're not seeing data in the dashboard, you may also have to refresh the dashboard. 

The Total Shared column is a Dataverse rollup column and those can take 24hrs to refresh, so you can expect that number to be updated about 1 day after the CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) runs.

**Comment by MartinWGT** [comment]
The flow you mention has only run once at set up and took just 10 seconds to complete. I've started it again and it's taking much longer, which is a good sign. I'll update the issue in 24 hours with  the outcome.
Thanks Manuela.

**Comment by MartinWGT** [comment]
I can confirm this is working now. Thanks for the quick reply!

**Comment by Jenefer-Monroe** [comment]
Wonderful, yes I believe that flow runs when we turn it on, but there are no objects yet to "cleanup" so it just runs a second and passes.
