### ISSUE TITLE
CoE core solution does not give details all environments

### ISSUE THREAD

**Issue by PPTechy** [microsoft/coe-starter-kit#6429]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have 50 plus environments in our tenant, but the CoE report showing the data (Flows) from only 20 environments. What could be wrong here? Which flow should we run to get all environments from the tenant? We are using the 4.9 version of core solution. Thank You!

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
There could be many reasons for this, typically it's:

the account running the sync flows doesn't have the right permissions and is not a Power Platform Admin permission
the account running the sync flows has admin access assigned via PIM and loses access whilst the sync flows are running

**Comment by PPTechy** [comment]
Thanks for your quick reply. Could you please list out what permissions should be granted to that service account?

**Comment by PPTechy** [comment]
Thanks for your quick reply. Could you please list out what permissions should be granted to that service account?

**Comment by manuelap-msft** [comment]
They are all listed in our documentation here
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with

I recommend you review the Get Started / Prerequisite section before setting up the CoE kit.
