### ISSUE TITLE
CoE Starter Kit - How to add company branding to customizable emails

### ISSUE THREAD

**Issue by fosttj** [microsoft/coe-starter-kit#6430]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am currently working on making changes to the Inactivity Process emails to customize them to fit our business wording and branding. I have been able to successfully make the changes to the Subject line and the Body.  I want to add our company branding to the emails and not have it default to having Microsoft icons, logos, social media sites, etc all over in the email.
What is the correct process steps to remove this information and add my own to these?  I have looked through the flows associated to the emails and have been unable to identify where these are set.
In the attached document I have made reference to one of the Inactivity emails that I working with. The last image is an email I received from the system and as seen I have marked up the things that I would like to have changed or removed.
[CoE-Customized-Emails.docx](https://github.com/microsoft/coe-starter-kit/files/12430277/CoE-Customized-Emails.docx)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2023

### What app or flow are you having the issue with?

Flows associated to CoE Inactivity customized emails

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, yes there are 3 additional environment variables used to format the email and you can customize those without generating any unmanaged layers on any flows. 

This will impact all emails sent by flows in the kit
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/378a63a5-96ea-434e-919a-d96e16a3d187)

**Comment by fosttj** [comment]
I have also updated those environment variables with no change to the email example I sent.

**Comment by fosttj** [comment]
I have also opened a support ticket 2308230010010600 for this same question.

**Comment by fosttj** [comment]
Any other suggestions in how to make this work?

**Comment by Jenefer-Monroe** [comment]
The starter kit is not a supported product so they will not be able to assist you. 
Sometimes flows cache env vars so if you turn the **_HELPER - Send Email_** flow off and back on after saving your changes, you should see your changes to those env vars.

**Comment by fosttj** [comment]
I stopped the HELPER - Send Email flow before making any changes. I updated the eMail Body Start environment variable and changed the code to point to our logo png file and have updated the Flow name Admin | Inactivity notifications v2 (Start Approval for Apps).  I have updated the Subject line with our information, and the body with our information.  Once I saved the changed and turned the HELPER - Send Email flow and then turned on and ran the Admin | Inactivity notifications v2 (Start Approval for Apps). The attachments still show the Microsoft logos and other Microsoft information. Also the link that is circled in the image "Clean Up App" points to the Commercial Power Platform site and Not GCC.

![inactivity_email1](https://github.com/microsoft/coe-starter-kit/assets/136116520/32de626d-6a62-4458-abfa-ff748a3529cd)
![inactivity_email2](https://github.com/microsoft/coe-starter-kit/assets/136116520/e3a806b1-a032-4130-80a1-acbf197c1337)

**Comment by Jenefer-Monroe** [comment]
Oh i see, yes unfortunately this is the one mail we cannot completely customize as we are using the products **_Approval_** feature to send the mail. This is as customized as we are able to make this mail since we are using their feature.

**Comment by fosttj** [comment]
Do you have any suggestions on how we may include our company branding to these types of emails? What about the other customized emails, which ones would use company branding?

**Comment by Jenefer-Monroe** [comment]
I'm afraid there is nothing we can do to make this mail more configured than it is. 
The rest of the mails in the kit are regular mails, not based off product mails. So the above is how you customize those.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
