### ISSUE TITLE
[CoE Starter Kit - BUG] Cib

### ISSUE THREAD

**Issue by jdmccarroll72** [microsoft/coe-starter-kit#6431]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Error Loading Control showing in compliance model driven app

### Expected Behavior

Should be showing connections

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Latest July 23

### What app or flow are you having the issue with?

Developer Compliance Centre

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Click on app
Shows error loading control under connections

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/15926760/a50ee095-d878-44e6-9fa5-8a1b8a523b5f)

**Comment by Jenefer-Monroe** [comment]
Hello, thanks for posting, this one is local fixed for Sept by https://github.com/microsoft/coe-starter-kit/issues/5505
I'll go ahead and close as a dupe, you can watch that bug for when the release is available.

**Comment by jdmccarroll72** [comment]
Hi @Jenefer-Monroe this hasn't resolved the issue

I am still getting this issue as the name isn't passing through

![image](https://github.com/microsoft/coe-starter-kit/assets/15926760/ea2fe64a-e3aa-40d4-a563-8008c5b65f81)
