### ISSUE TITLE
[CoE Starter Kit - QUESTION] Need to update full inventory to update deleted APPs and Flows?

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#6432]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

Please, I'm migrating the apps and flows from the company's standard environment to the environments according to area and company, so after migrating to the correct environment, we need to exclude these apps and flows from the standard environment, the problem is that even after a week these apps and flows do not update that were excluded from the default environment, it is necessary to change the Fullinventory variable and run the flow: ![Captura de tela 2023-08-24 153516](https://github.com/microsoft/coe-starter-kit/assets/129080740/af488919-872e-43aa-bae4-dac379d5c98d) For updating deleted apps and flows.
Can you tell me if this is normal?
![Captura de tela 2023-08-24 153610](https://github.com/microsoft/coe-starter-kit/assets/129080740/305d47bd-04bb-4601-9a76-93a69d159f38)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Agosto 4.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Is this summary correct?

- You had AppX in EnvtA
- You moved AppX to EnvtB
- You deleted AppX from EnvtA
ISSUE: The CoE kit now still shows AppX in both EnvtA and EnvtB

If so, please note that the clean up flow for deletes is a long running flow and so it runs only every few weeks. 
Please go run **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** and you should see AppX removed from EnvtA

**Comment by minobrega** [comment]
Hello Jenifer, yes, the summary is correct.

Ok, I'm going to force the execution of this flow when I delete some flow or application, if it works I'm going to reduce its recurrence because currently it's at once a week.

Thank you for the info..

**Comment by Jenefer-Monroe** [comment]
Once a week is fine, changing its recurrence will cause an unmanaged layer and prevent you from getting updates in the future.

**Comment by minobrega** [comment]
Hello,

yes, but always before applying the update i remove the unmanaged layers.

If that's the case, I always change the recurrence after applying the updates because it will lose removing the unmanaged layers, right?

**Comment by minobrega** [comment]
Okay, thanks a lot for the information..

**Comment by Jenefer-Monroe** [comment]
You are most welcome, thank you for using CoE

**Comment by minobrega** [comment]
Hi Jenifer

Please, I created a resource with sharepoint and some cloud flows to help us in the migration of applications and cloud flows that are in the standard environment to move to the environment according to the area or company of the group, this tool has the objective monitor the migration of apps and makers' flows, charging them via email and reporting to us on what is pending without the need to keep track of whether or not the migration has already been completed. Perhaps this idea could contribute to one more feature in CoE. Do you think it would be interesting? Who could I talk to about this?

**Comment by Jenefer-Monroe** [comment]
Can you take a look at this tool? The ALM Accelerator: https://learn.microsoft.com/power-platform/guidance/alm-accelerator/overview

I think it might lean in the same direction as you are going. That team is very responsive as well and love cusotmer feedback!

**Comment by minobrega** [comment]
Thanks a lot for the tip Jenefer ..  :)
