### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Get Security Role Users - "Add_new_SR_User" & "Find_it_for_ID"

### ISSUE THREAD

**Issue by Rajeshgn053** [microsoft/coe-starter-kit#6437]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The following 3 actions are resulting in similar kind of error across multiple runs.
"Add_new_SR_User", "Find_it_for_ID" & "Delete_it"

Error - Action Failed
Error Description - "Could not acquire Write lock in time 30000 milliseconds. Lock mode: Write. Lock name: UserGroupsCache:XXXXXXX-XXXXXX|XXXXXXX-XXXXXX|XXXXXXX-XXXXXX",

### Expected Behavior

Need to perform the respective actions

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users 

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

![Add_New_SR_User](https://github.com/microsoft/coe-starter-kit/assets/143060581/3a7268c6-5ef2-4f4a-ac04-3558dc6d060b)

**Comment by Rajeshgn053** [comment]
Note - All COE flows are running on Service account enabled  with Power platform admin access

**Comment by Jenefer-Monroe** [comment]
Hello we've made quite a few major changes to this flow since the May release. Please retest after your next upgrade to August 2023 or later.

**Comment by Rajeshgn053** [comment]
Ok, We will check this & keep you posted

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and clsoe this out as a dupe, but please return with bugs after your next upgrade as you find them.
