### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Get Security Role Users - Action "Get_SR" & Get_BU" failed

### ISSUE THREAD

**Issue by Rajeshgn053** [microsoft/coe-starter-kit#6440]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The following 2 actions are used to get the Security role & Business units.

Error - Action "Get_SR" & Get_BU" failed
Error Description - No Organization is matching the given dataset: _

Notes - The respective action outputs are used to extract the values. Which is going on error, due to null output.

Proposed solution - Need to do Null check, before extracting the values out of the res
![Get_BU](https://github.com/microsoft/coe-starter-kit/assets/143060581/8565de9f-81fe-4d86-9ac7-5c8a3633f0be)
pective outputs. 
![Get_SR](https://github.com/microsoft/coe-starter-kit/assets/143060581/da0baf6a-5321-44f9-a02e-1882f5606ab3)
![SR And BU Output formulas](https://github.com/microsoft/coe-starter-kit/assets/143060581/294d6842-cb78-4943-8675-e696b9454284)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Rajeshgn053** [comment]
Note - All COE flows are running on Service account enabled  with Power platform admin access

**Comment by Jenefer-Monroe** [comment]
Hello we've made quite a few major changes to this flow since the May release. Please retest after your next upgrade to August 2023 or later.

**Comment by Rajeshgn053** [comment]
Ok, will check & keep you updated

**Comment by Jenefer-Monroe** [comment]
lets just use a single issue to track all this as its a single issue. We can use https://github.com/microsoft/coe-starter-kit/issues/6443
