### ISSUE TITLE
[CoE Starter Kit - BUG] - PowerApp CoE Admin Sync flows are getting failed

### ISSUE THREAD

**Issue by srilekha704** [microsoft/coe-starter-kit#6442]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have installed PowerApps CoE tool kit appx 3 months around from last 1.5 months one of the primary flow is getting Failed and went to Disabled state on it's own(Due to multiple Failed runs).

Now we no longer able to Turn the flow ON or make any changes to the existing Flow and Save.

**Flow Name:** Admin | Sync Template v3

### Expected Behavior

CoE Flows should run successfully and CoE PowerBI reports are unable to fetch the latest data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.2023.817.10

### What app or flow are you having the issue with?

 Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

![img1](https://github.com/microsoft/coe-starter-kit/assets/89075457/6beb226a-08d1-4adc-a2f4-3d22b17e70fb)
![img2](https://github.com/microsoft/coe-starter-kit/assets/89075457/a49dd394-71f6-47bb-a8c6-7102d1c7d152)
![img3](https://github.com/microsoft/coe-starter-kit/assets/89075457/3dcb8ab1-3676-4c4b-9d19-e7aebdf8422e)

**Comment by Jenefer-Monroe** [comment]
Can you please check for unmanaged layers on this flow? We renamed it so you should no longer be seeing it like that in your solution

**Comment by srilekha704** [comment]
Hi Jenefer,

We have recently started using Powerapps CoE tool kit we tried all possible ways to edit the flow..the problem is it's not getting saved as it's in disable state and we neither able to enable the same.

I request you for getting into a call with us to take this further.

Thank You
Sri Lekha

**Comment by Jenefer-Monroe** [comment]
Hello, please note that the CoE Starter Kit is not a product and not officially supported. Further we are a very small (2 person) team managing all 12k installs and so cannot meet with our user on calls as a result. We do best efforts here though to assist.

**Comment by Jenefer-Monroe** [comment]
Here is how to check to see if you have unmanaged layers
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3bddbfd5-d880-4240-9665-4454ab51a3c7)

It should look like this but may have unmanaged ones on top that need removed
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d3ac52e0-3ceb-495e-b0b1-27167795a296)

**Comment by srilekha704** [comment]
Hi Jenefer,

I could see Unmanaged layer in solutions layer and removed that as suggested. No I dont see any error in flows.

But I still stale data in CoE powerbi reports even after restart of the dataset.

As you can see in the attached image3 powerbi data is stale and last updated data is of JUNE.

Thank You
Sri Lekha

![image](https://github.com/microsoft/coe-starter-kit/assets/89075457/f5af32ec-9eac-4eda-8ec9-f525133361e8)

![image](https://github.com/microsoft/coe-starter-kit/assets/89075457/4879458b-63a6-49c6-98bd-de3b28ebda49)

![image](https://github.com/microsoft/coe-starter-kit/assets/89075457/1e4351ab-cbdd-4031-abac-7d52498c9eda)

**Comment by Jenefer-Monroe** [comment]
Have you refreshed the PBI data set? 
You can see when it was last refreshed and when it will next be refreshed in the workspace.
If there is no "next refresh" then you have not yet configured that or the connection for it broke. Please see [Configure scheduled refresh](https://learn.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a7323e5a-e2bc-49fc-89cb-a42b87a2bb27)

**Comment by srilekha704** [comment]
Dataset has been refreshed already. It's same post that too.

![image](https://github.com/microsoft/coe-starter-kit/assets/89075457/d041ab3d-afb4-44b3-91d2-fae3a4f1ef6c)

**Comment by Jenefer-Monroe** [comment]
And you have had new envts created since June? I'm not sure but I presume that is what your chart is showing is created envts over time. 
If so, please find an envt you know has been created since then, go to the most recent run of this flow **_Admin | Sync Template v3 (Driver)_**, and see if it shows up in the output here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/54c6979d-bdd4-46ad-b482-5e76bf31afcb)

**Comment by srilekha704** [comment]
I don't have option to download but I still see the raw data of the output.

Also, I could see the newly created environment which is not visible in PowerBI reports.

![image](https://github.com/microsoft/coe-starter-kit/assets/89075457/bac64e62-2934-422b-b7bf-290ca549f328)

![image](https://github.com/microsoft/coe-starter-kit/assets/89075457/d2f3d5ef-4e86-4a0e-81ed-41c161f2cfa5)

**Comment by Jenefer-Monroe** [comment]
Are the new envts present in the dataverse tables? You can check this via the **_Power Platform Admin View_** app of the CoE
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e024359a-a82f-431d-ad21-93099060ada5)

**Comment by srilekha704** [comment]
I see it is available in DataVerse. PFB.

![image](https://github.com/microsoft/coe-starter-kit/assets/89075457/7c3d9c60-9255-4740-9e6b-dbff5f1d04fd)

**Comment by Jenefer-Monroe** [comment]
ok im really not sure. We have reshipped the PBI's since the one you are looking at and I dont repro so it could have been a bug in the old PBIs


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/05a9e0ea-2cff-4d92-a392-aeeb453de569)

**Comment by Jenefer-Monroe** [comment]
I woudl suggest upgrading to the latest and using the Power Platform Admin View app in the meantime until you are able to do so

**Comment by srilekha704** [comment]
Sure Jenefer. we will take this task in our next sprint. Please keep the thread open.

**Comment by Jenefer-Monroe** [comment]
what is your ETA for that? We need to keep our list tidy but if you give me an expected date in the next few weeks then I'm happy to leave open.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
