### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Solutions) - List Solution Apps

### ISSUE THREAD

**Issue by Rajeshgn053** [microsoft/coe-starter-kit#6443]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are facing error in the flow, while fetching the "Actual Soln Objects".

Error - Action 'List_Solutions_Apps' failed
Error Description - Attached the image & action output.
![List_Solutions_Apps](https://github.com/microsoft/coe-starter-kit/assets/143060581/a6c5a714-6c3d-448e-96b2-f92a325d1c00)
[List_SolutionApps.txt](https://github.com/microsoft/coe-starter-kit/files/12437981/List_SolutionApps.txt)

### Expected Behavior

Should have fetched the current actual solution objects & followed with solution workflows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Rajeshgn053** [comment]
Note - All COE flows are running on Service account enabled with Power platform admin access

**Comment by Jenefer-Monroe** [comment]
Hello, this is an out of the box connector we are using here so if the call is failing its likely some configuraiton or product issue. 

Here are the common debugging steps. Please let us know your responses. 
1. As the identity running the flow, go into the trigger statement you will see the environment instance url. Can you browse to that? 
![image](https://user-images.githubusercontent.com/89584709/205936150-0d27aa3d-776b-4eaa-b28c-8cff91d8b7b8.png)

2. Does the identity running the flow does not have the Power Platform Admin Role permanently assigned? 
Note that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management), this won't be sufficient to run the CoE Starter Kit.
For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

3. Sometimes the target environment for the call here was renamed but the old name is cached. In this case turning this CoE flow off and back on will clear that cache.
 
4. Perhaps the connection needs fixed 
https://github.com/microsoft/coe-starter-kit/issues/4481
Could not retrieve values. The dynamic invocation request failed with error: { "status": 401, "message": "Authorization has been denied for this request.", "error": { "message": "Authorization has been denied for this request." }, "source": "globaldisco.crm.dynamics.com", "errors": [], "debugInfo": "clientRequestId: 5ebe19df-cc89-4e0e-8ef5-aaff8cf6fe32" }

5. Perhaps the envt was deleted after the flow started, the error would not recur the next day if that is the case.

**Comment by Rajeshgn053** [comment]
All COE flows are running on Service account & it does have full time "Power Platform Admin" access

**Comment by Jenefer-Monroe** [comment]
Please share a screenshot like this
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7d915b12-249a-407e-960d-dc96ecdd68e1)

**Comment by Rajeshgn053** [comment]
I have requested the related details of our service account & get back to you in few days.

**Comment by Rajeshgn053** [comment]
Hi Jenifer,
The account we are using has the direct permissions as PPA, Attached the screenshot FYR
![PROD_ServiceAccount_Previlieged](https://github.com/microsoft/coe-starter-kit/assets/143060581/4368a229-922b-4064-8e14-5edc5558277f)

**Comment by michael-wright-pwc** [comment]
Hi @Jenefer-Monroe. I'm working with @Rajeshgn053 on these issues.

As mentioned above, all our CoE flows use connection references with an account that is permanently assigned Power Platform admin with proper licensing.

We are having 2 mysterious error messages related to the Dataverse Legacy connector throughout the CoE solution:

1) Most often, we get a 400 with a blank error message. (amazing right?) - have you ever seen this and any thoughts on how to troubleshoot it?

2) We also sometimes get a 404 with error message " No Organization is matching the given dataset: _" - have you ever seen this and any thoughts on how to troubleshoot it?

Thanks so much.

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately we ended up with a bunch of copies of this bug so its difficult to keep them all up to date. Latest question is in this bug. Lets use it to drive to resolution? https://github.com/microsoft/coe-starter-kit/issues/6436

**Comment by Jenefer-Monroe** [comment]
Per other thread, this turned to be that envt was deleted after the flow started, the error will not recur the next day in this case.
