### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Solutions) - Get Solution Publisher

### ISSUE THREAD

**Issue by Rajeshgn053** [microsoft/coe-starter-kit#6444]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow is not able to fetch the "Solution publisher", while running the scope "Put Solutions in COE". This is leading to the faolure of all remaining steps
![Get_Solution_Publisher](https://github.com/microsoft/coe-starter-kit/assets/143060581/d9e7ad37-387c-4a53-abc2-fb5d3fbacab7)

### Expected Behavior

Solution publisher has to be fetched & proceed with next steps.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Rajeshgn053** [comment]
Note - All COE flows are running on Service account enabled with Power platform admin access

**Comment by Jenefer-Monroe** [comment]
Hello, this is an out of the box connector we are using here so if the call is failing its likely some configuraiton or product issue. 

Here are the common debugging steps. Please let us know your responses. 
1. As the identity running the flow, go into the trigger statement you will see the environment instance url. Can you browse to that? 
![image](https://user-images.githubusercontent.com/89584709/205936150-0d27aa3d-776b-4eaa-b28c-8cff91d8b7b8.png)

2. Does the identity running the flow does not have the Power Platform Admin Role permanently assigned? 
Note that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management), this won't be sufficient to run the CoE Starter Kit.
For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

3. Sometimes the target environment for the call here was renamed but the old name is cached. In this case turning this CoE flow off and back on will clear that cache.
 
4. Perhaps the connection needs fixed 
https://github.com/microsoft/coe-starter-kit/issues/4481
Could not retrieve values. The dynamic invocation request failed with error: { "status": 401, "message": "Authorization has been denied for this request.", "error": { "message": "Authorization has been denied for this request." }, "source": "globaldisco.crm.dynamics.com", "errors": [], "debugInfo": "clientRequestId: 5ebe19df-cc89-4e0e-8ef5-aaff8cf6fe32" }

5. Perhaps the envt was deleted after the flow started, the error would not recur the next day if that is the case.

**Comment by Rajeshgn053** [comment]
[All COE flows are running on service account & it does have "Power Platform Admin" access](https://pwc.sharepoint.com/:x:/t/GBL-IFS-CitizenLedDevelopment-CoEStarterKitMicrosoft/ERBSxGnU8OxFgV9LeW7-jIEBCm3MF7a7lWwOCrDS-4t-Yg?email=rajesh.gudibanda.nagaraja%40pwc.com&e=3IbKax)

**Comment by Rajeshgn053** [comment]
All COE flows are running on Service account & it does have full time "Power Platform Admin" access
