### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor>Parse impacted resources into CSV Error (Action Non-Business Connectors Parse Failed

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6446]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/547b0a04-50dc-4c0c-a1c5-bd47427b4a99)

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/07117acc-7199-40d7-ad92-5699eb9bc9a6)

Can you provide a fix to this?

Looks like this area is duplicated.
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/f22ccf98-66a4-49b2-a716-2a562d8dbdf7)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

DLP Editor>Parse impacted resources into CSV

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Is your screenshot of the app code from the DLP Editor (canvas app) or the new DLP Impact Analysis (model driven app)? 

In the new DLP Impact Analysis, I see the correct code
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/5ed4ca07-aef1-4f01-85c6-31e35b155ef9)

We are removing the DLP Editor v2 app with the next release, in favour of the new DLP Impact Analysis app which has the same and more functionality. 

Here's some of the differences between the two:
- they both support the same set of functionality, editing DLP policies and reviewing the impact. no change in features there.
- the new app is using Creator Kit components for a fresh look and feel, and with using Details List component allows us to support multi select for moving connectors / environments around
- the new app allows you to export the impacted apps/flows both to CSV as well as to a task list (Dataverse table) for further analysis

With September, the new app will also support
- saving policies as draft. as part of editing a policy, you can save the changes as draft and apply them later once the risk/impact has been mitigated
- workflows to reach out to mitigated makers in bulk and collect info from them on what to do with the app (delete, update, migrate)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
