### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why are 'makers' being added to Maker table

### ISSUE THREAD

**Issue by KRhoadesHyp** [microsoft/coe-starter-kit#6449]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

About 20% of the entries in our Makers table have zeros in all of the 'Number of...' columns.   Below is an example of 4 that were added in the last week (only one of the number columns displayed).  I had cleaned out all of these 'zero' makers a few months ago but something is obviously triggering them.  Can you tell me what I might be missing so I can find out if they are indeed "Makers"?  Two of the account listed are just display devices so.... ?  Thanks!

![image](https://github.com/microsoft/coe-starter-kit/assets/135135789/4b1b7570-3f34-4583-99b0-f60d1293fe61)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

August 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
every time we run inventory we add new "makers" to the maker table. This means we have found them as owning an object we have found which is to be added to the inventory. 
You can see all the roll ups if you go to the Maker table in the Power Platform Admin View app and add the as shown below. Note that these are roll up fields and so do take some hours to update.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f8038179-8ee4-49d6-97d9-e4a384e9d20b)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0f9fb1e6-dac0-4c3b-95e2-5a72f785bbcb)

**Comment by Jenefer-Monroe** [comment]
Then if you do not see your answer there you may have to search in each of the individual tables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/16d4c78a-89a4-4629-95c9-c96d7174d79a)

**Comment by Jenefer-Monroe** [comment]
I've just looked in our test tenant as well and dont see anything suspicious in our table but I've kicked off a full inventory there to see if something pops up.

**Comment by KRhoadesHyp** [comment]
Thank you, we are very curious about this one.  I will start tracking through the tables.

Kristy Rhoades
Sr. Developer, IT Modern Work Team

**Comment by manuelap-msft** [comment]
Makers are added
- to the security group via this flow: **Admin | Add Maker to Group**
- to the Makers table via this flow: **HELPER - Maker Check** which is called from all the inventory sync flows. You can see the details of all those flows by selecting the Helper flow > ... > Advanced > show dependencies. basically everything that we capture in inventory also captures the maker in the maker table
  ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/499dc863-171a-4a95-8539-a0773b547a8d)

Makers are never removed from the group or table. So there could be a scenario where a maker deletes all they've created (apps, flows, environment) so they show as having 0 resources, but they'd still be listed in the maker table as they were once a maker.

**Comment by KRhoadesHyp** [comment]
@manuelap-msft thank you, that clear up a few of the questions.  However, I still don't see how we are getting accounts in there that don't even have a 365 license associated with them, they can't possibly be creating anything.   I can say with certainty that most of the 'zeroed' accounts in the maker table would never have actually created anything, so I am curious why else they are being added.  Accessing PBI reports is the only thing I can think of that they might be doing?

**Comment by Jenefer-Monroe** [comment]
We do not have any processes that would add PBI users to this table. But you may have extensions in your environment that add users for other reasons. 
If you delete them, perhaps see if they come back and then debug from there.

**Comment by KRhoadesHyp** [comment]
@Jenefer-Monroe thanks, we did already delete them all once and they have gradually come back.

**Comment by Jenefer-Monroe** [comment]
Meaning things authored in your tenant for your own specific needs. Many people extend the kit with their own functionality.

**Comment by KRhoadesHyp** [comment]
Neither of the first 5 I looked for have entries in that table.

**Comment by KRhoadesHyp** [comment]
@Jenefer-Monroe  the maker check ran 600+ times yesterday, is there a way to search through those to find one specific user?

**Comment by Jenefer-Monroe** [comment]
Not an easy one that I know of. 

You can export the csv and use it to stitch together the runid, but that only gets you a hundred records
Or you can add the MakerID in the ux and keep loading more
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/270906ac-ebcb-42b1-8c7e-c5599a6b589c)

I believe PowerShell has better search for old runs than this but I'm not super familiar with those calls.

**Comment by Jenefer-Monroe** [comment]
Another option would be
1. Delete them from the maker table
2. Run one of these flows and see if they return

- CLEANUP - Admin | Sync Template v3 (Orphaned Makers)
- CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
- Admin | Sync Template v3 (Driver)

3. if not run another ... etc

**Comment by KRhoadesHyp** [comment]
So will a user get added to the maker table if an app has been shared with them?  I am trying to understand the relationship between the Maker & Power Platform User table[s].

**Comment by Jenefer-Monroe** [comment]
Its its been shared with them as a co-owner yes, as that implies ability to edit. 
If they are shared with as a user (viewer) only, then no it should not.

**Comment by KRhoadesHyp** [comment]
Yet I am seeing active users with the co-owner role [for apps] in the _Power Platform User Roles_ table that are not in the Maker table.  This is proving too much to track down.  We are going to have to write a flow to remove any users from the AD group that have zero in all of the "Number of" columns and hope for the best.

**Comment by Jenefer-Monroe** [comment]
That would be a fine thing to do! If I hear this from others or see it in my testing, I'll track it down as well.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
