### ISSUE TITLE
[CoE Starter Kit - QUESTION] SYNC HELPER - Apps, Handling Apostrophe

### ISSUE THREAD

**Issue by Rajeshgn053** [microsoft/coe-starter-kit#6450]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,

We are facing error in following flow, while fetching the details that has 'Apostrophe' in the value. 
SYNC HELPER - Apps

Based on our research, you have mentioned in the following issue that this will be handled.
https://github.com/microsoft/coe-starter-kit/issues/5430

Could you please confirm, whether you are going to fix this on all COE flows that has similar queries? If not, please let us know, when you can fix this.
![Apostrophe](https://github.com/microsoft/coe-starter-kit/assets/143060581/3786d26c-c50c-4061-83d6-c56205f40761)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We have not done a systematic review of all flows to look for these, no. And likely we will not. 
Please do realize we are a very small (2 person) team charged with all the 12k tenants using the kit, and that the kit is not a product but rather a template of resources for you to use and expand upon for your governance needs. Please see 
https://learn.microsoft.com/power-platform/guidance/coe/feedback-support

We do look at questions as they come in though and do a best effort to have the kit work for folks as is.

**Comment by Jenefer-Monroe** [comment]
This issue in particular was resolved in recent builds, so your next upgrade will see it resolved.

Please see:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b833dbe9-ce56-42a6-b834-a8f5d2c9ba03)

**Comment by Rajeshgn053** [comment]
Thank you, will check after next build upgrade..
