### ISSUE TITLE
[CoE Starter Kit - BUG] Can not turn on the flows Admin | Sync Template v4 (Flows) & Apps & Env Properties 

### ISSUE THREAD

**Issue by pp-panda** [microsoft/coe-starter-kit#6452]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After the install of the August 2023 Release of the CoE Core Componets, I would like to start the Flow/App/ Env Sync Flows V4 (they are habe new trigger actions) but I get the following message:
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'a44274df-02da-ed11-a7c7-0022480813ff' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

With the dataverse tigger they dont have to have a parent flow right?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please note that the starter kit uses many child flows and these need turned on in order for the flows that call them to pass. 
Here are the child flows needed for Core as an example: [Update and turn on child flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-and-turn-on-child-flows)

Please also note that if you use the Setup Wizard for installs and upgrades, this ordering is handled for you, so its highly recommended!

**Comment by pp-panda** [comment]
Thank you very much! The turn on ordering helped!

**Comment by pp-panda** [comment]
Flows are turned on :)
