### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Power Apps User Shared With - Action 'List_group_members' failed

### ISSUE THREAD

**Issue by Rajeshgn053** [microsoft/coe-starter-kit#6456]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The following cleanup flow is fetching the Apps & the permissions shared. While handling the groups that are permitted to use the apps, its throwing error for few groups, which doesn't exist.
![image](https://github.com/microsoft/coe-starter-kit/assets/143060581/7659abbc-eaff-4b8c-b517-6782601466d8)
[List Group Members- Error output.txt](https://github.com/microsoft/coe-starter-kit/files/12453548/List.Group.Members-.Error.output.txt)

### Expected Behavior

We understand the scenario of few groups that might not exist & would have got deleted. But on such instances, the flow should capture them in separate log output & mark the rest of the successful instances as completed. This is leading to confusion & increase in the sync flow errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello this bug has been fixed in current builds, I don't remember when we fixed it but your next upgrade will no longer repro this. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dcb2a4ea-1e72-48e5-ad19-6838a9745942)

**Comment by Jenefer-Monroe** [comment]
As an aside please do not add tags like this to your issues
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/673e980f-21e7-493d-827d-3d5ac6422c3b)

We use these tags for our internal processes and are likely to miss your issues if you use them.

**Comment by Rajeshgn053** [comment]
Ok, going forward can i raise them as Question?

**Comment by Jenefer-Monroe** [comment]
Sorry that was a mistake on my part, you opened them fine, another process marked the other tag as bug.

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this one out as a dupe then.
