### ISSUE TITLE
PowerApps Actions not working for Model Driven App

### ISSUE THREAD

**Issue by rajan1980** [microsoft/coe-starter-kit#6458]
Hi Team

I see many PowerAutomate action which work properly for canvas app does not work for Model driven app and throw error
GetApproleassignment
EditAppRoleassignment
QuarantineApp
GetAppAsAdmin
SetAppQuarantineStatus

**Comment by manuelap-msft** [comment]
Hello,

in this GitHub repo we only triage questions specifically related to the CoE Starter Kit and ALM Accelerator solutions. For more generic questions related to Power Platform, please post them in the Power Users community: https://powerusers.microsoft.com/
