### ISSUE TITLE
[CoE Starter Kit - BUG]: Connection failed using Office 365 Management API

### ISSUE THREAD

**Issue by dhsiaot** [microsoft/coe-starter-kit#646]
**Describe the bug**
In setting up the audit log connector (Office 365 Management API), the connection failed with below error:

OAuth2 authorization flow failed for service 'Azure Active Directory'. OAuth 2 sign in failed to exchange code for access token. Client ID and secret sent in form body.. Response status code=Unauthorized. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 15d70cd4-fe44-48a0-8339-20ec12e56c00\r\nCorrelation ID: 3a187e95-0a80-4d26-a127-c438b5325b2a\r\nTimestamp: 2021-06-17 13:55:42Z","error_codes":[7000215],"timestamp":"2021-06-17 13:55:42Z","trace_id":"15d70cd4-fe44-48a0-8339-20ec12e56c00","correlation_id":"3a187e95-0a80-4d26-a127-c438b5325b2a","error_uri":"https://login.windows.net/error?code=7000215"} Client ID and secret sent in Basic authorization header.. Response status code=Unauthorized. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: e25336c5-2215-4df8-bb20-16b58bd26100\r\nCorrelation ID: ed0f567d-83e9-4be0-b0e3-d52023cb58e0\r\nTimestamp: 2021-06-17 13:55:43Z","error_codes":[7000215],"timestamp":"2021-06-17 13:55:43Z","trace_id":"e25336c5-2215-4df8-bb20-16b58bd26100","correlation_id":"ed0f567d-83e9-4be0-b0e3-d52023cb58e0","error_uri":"https://login.windows.net/error?code=7000215"}

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Governance]

**To Reproduce**
1. Go to 'make.gov.powerapps.us'
2. Click on 'custom connectors'
3. Select 'Office 365 management API', click 'Edit'
4. Filled out all required fields, go to 'Test', create a new connection, see the error above.

**Expected behavior**
Expect to see connection succeed.

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Unfortunately the problem you are having is not part of the toolkit, you are just struggling to setup the custom connector. 

In particular it sounds like you have entered the incorrect client id and secret, but it may be something else like permissions. 

Please view [Paul's setup video](https://www.youtube.com/watch?v=Z9Vp2IxFzpU&list=PLi9EhCY4z99W5kzaPK1np6sv6AzMQDsXG&index=3&t=2s) to see if he can help you with the steps. He starts the work of audit log setup at ~minute 20.
