### ISSUE TITLE
[CoE Starter Kit - BUG] Audit log cannot be started - secret value cannot be null

### ISSUE THREAD

**Issue by monicasv** [microsoft/coe-starter-kit#6463]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are trying to run the Admin | Audit Logs | Office 365 Management API Subscription flow - it fails each time with error: Error occurred while reading secret: Value cannot be null.
Parameter name: input
![image](https://github.com/microsoft/coe-starter-kit/assets/90351601/b06aa2ec-b274-454d-b087-afb29e1866bb)
![image](https://github.com/microsoft/coe-starter-kit/assets/90351601/8e028e60-63bb-429c-908a-554c15de496f)

We have double checked all of the values that are entered into the env variables - everything seems to be correct.
![image](https://github.com/microsoft/coe-starter-kit/assets/90351601/2db39fe7-f0ef-411e-8a04-50d7e4eaaf10)
![image](https://github.com/microsoft/coe-starter-kit/assets/90351601/4f792238-fd20-4f89-bcff-e1555800365a)

There is one step where "Set AppID - Current Value is not showing a value in outputs
![image](https://github.com/microsoft/coe-starter-kit/assets/90351601/29c1a9d1-42d9-4034-adde-9cb6154221af)

What else can we try to get the subscription started?

### Expected Behavior

Should be able to run/start the flow with no error and start the subscription.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Run Admin | Audit Logs | Office 365 Management API Subscription flow - enter "start" in the parameter.
2. Flow fails - error 'Error occured while reading secret: Value cannot be null.
Parameter name: input'

**Comment by Jenefer-Monroe** [comment]
turn the flow off and back on, looks like it cached a blank value.

**Comment by monicasv** [comment]
We tried that a few times with no luck.  Also made sure to go back to the env variables and publish changes. Can't seem to get it to register

**Comment by Jenefer-Monroe** [comment]
Please share a screenshot of your app registrations API Permissions. Note that you will need to be logged in to GitHub to share images, you cannot respond in email to share images.

**Comment by monicasv** [comment]
I wanted to provide an update - after triple checking the user guide step-by-step info and verify variables, API permissions, etc, we:
1. Removed the Client Secret variable and also the Client ID variable
2. Published all customizations after the changes
3. Re-populated the values in Client Secret and Client ID
4. Published customizations after re-populating the variable values
5. Turned off the Admin | Audit Logs | Office 365 Management API Subscription flow
6. Turned the flow back on and ran it
7. Success!! The subscription was finally started

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thank you for the update!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by lokeshkscb** [comment]
Hi @monicasv , Thanks for the solution. But wanted to check on these steps?

Removed the Client Secret variable and also the Client ID variable
Published all customizations after the changes

What you meant by this please. You mean you have removed the client secret and client ID from the environment variables in COE command center app right? Please confirm and what is meant by Published all customizations after the changes? can you please elaborate the same, we are facing same issue
