### ISSUE TITLE
[ALM Accelerator - BUG]: Environment variable value can't be an empty string.

### ISSUE THREAD

**Issue by gerald560** [microsoft/coe-starter-kit#6465]
### Describe the issue

Somehow when deploying to prod env vars are not being recognized:

<img width="1018" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/12697408/a5ee0a52-d594-49ab-a1da-ee2db6816e86">

but when looking at ALM and even the variables in the pipeline we can see that env vars are there

<img width="1762" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/12697408/a805e57b-0528-4000-a7a1-457226797f5c">

### Expected Behavior

Pipeline not to fail

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Accelerator Version: 1.0.20230802.1(Managed)

**Comment by mikefactorial** [comment]
Closing this out for now. We made an update in the October release related to addressing the described behavior above
