### ISSUE TITLE
[CoeE Starter Kit - Feature]: Wrong product, deprecate me // Connector deep dive should provide information about which flows and which envs a connector is in

### ISSUE THREAD

**Issue by anttipajunen** [microsoft/coe-starter-kit#6468]
### Is your feature request related to a problem? Please describe.

I'm having a really hard time getting to info that would tell me:
- How many connectors of X (for example SQL) do I have
- Which flows are they in
- Which envs are the flows in

### Describe the solution you'd like

I absolutely want to get this information from the connector deep dive page:

![image](https://github.com/microsoft/coe-starter-kit/assets/64043240/132d4b85-e6c6-45e5-9220-51e68d0f7394)

### Describe alternatives you've considered

The experience of drilling down from flow deep dive is absolutely horrible because the tree visualization absolutely sucks from a UX perspective. It's just bad and shouldn't be used. It's also really illogical to drill to a connector from flow deep dive when I'm interested in a connector. I want to get there from the connector deep dive.

![image](https://github.com/microsoft/coe-starter-kit/assets/64043240/b7e84b58-e239-4d24-a4e5-5f21b23f60d1)

### Additional context?

The tree visualization is horrible. I really wish you'd consider alternatives to that.

**Comment by anttipajunen** [comment]
Gosh. Went to ALM accelerator. Close and re-open. My bad.

**Comment by manuelap-msft** [comment]
Tracking this under https://github.com/microsoft/coe-starter-kit/issues/6469. Closing as duplicate
