### ISSUE TITLE
[CoE Starter Kit - BUG]Active Connectors does not show the correct usage by Apps and Flows 

### ISSUE THREAD

**Issue by faszul** [microsoft/coe-starter-kit#6470]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

reopen the case from #6325 

For some connectors (connectors - active connectors - used in - Apps and Flows) it does not shows the correct list of active Flows and Apps that currently using the connectors.
For example we blocked our Azure Dev Ops connector in the DLP and while in Active Connectors shows that no one using it we received lot of Apps and Flows owners complaining that it is blocked by our DLP policy.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.4.6070-2307.1

### What app or flow are you having the issue with?

All apps or flows that utilising the connectors

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Steps To Reproduce
1.Go to connectors - active connectors - used in - Apps and Flows
2. Put the connectors to block
3. Apps and Flows owner reported to be blocked while the 'Active Connectors' did not show any activity

### Anything else?

![image001](https://github.com/microsoft/coe-starter-kit/assets/142005629/dbbc227a-bf06-4f73-ae01-0f7eb9da8756)

**Comment by manuelap-msft** [comment]
Are you using sync flows or Data Export for inventory?
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory

**Comment by faszul** [comment]
No we did not.



From: Manuela Pichler ***@***.***>
Date: Tuesday, 29 August 2023 at 6:51 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Aziz, Fahdzul ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG]Active Connectors does not show the correct usage by Apps and Flows (Issue #6470)
Are you using sync flows or Data Export for inventory? https: //learn. microsoft. com/en-us/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory — Reply to this email directly, view it on GitHub,


Are you using sync flows or Data Export for inventory?
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory<https://urldefense.com/v3/__https:/learn.microsoft.com/en-us/power-platform/guidance/coe/setup*what-data-source-should-i-use-for-my-power-platform-inventory__;Iw!!MfzFaTml5A!lwqycT3RTgbpIdVU-mpLkUSuCZUuk0F0cgt1p2OR2E5fjV3MomLZ6kQYIsSMazXIsSRQuNBh246Hsonc4aLK4dr8sT7Mlj61eHPLFc-M$>

**Comment by Jenefer-Monroe** [comment]
Please find the envt and app name for an app that the maker is telling you is blocked
Find that app in the Power Platform Admin View and click it to open
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/214d58fb-3787-4030-8365-e805fe1e9bb2)

Look at the connections page, do you see the connector listed there?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f8de7ce4-6281-4459-b00a-bb87474fac50)

Click app details, does the app load?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fa1e7f90-291e-4641-8406-91b8ea6c8a26)

**Comment by faszul** [comment]
Thanks for the update.

We are compiling and confirming the name of the affected apps from the owners/developers - will update you soon.

Fahdzul
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Tuesday, September 5, 2023 3:04:02 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Aziz, Fahdzul ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG]Active Connectors does not show the correct usage by Apps and Flows (Issue #6470)

Please find the envt and app name for an app that the maker is telling you is blocked Find that app in the Power Platform Admin View and click it to open Look at the connections page, do you see the connector listed there? Click app details,


Please find the envt and app name for an app that the maker is telling you is blocked
Find that app in the Power Platform Admin View and click it to open
[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/89584709/265528420-214d58fb-3787-4030-8365-e805fe1e9bb2.png__;!!MfzFaTml5A!g8sbCPimWtS3eRJzuGLCnA8kHsqvUDdkFEOBq7Qd7VnzQwA0PWqaSnF2a0t2W6Ey94yBr_8-2wweMcS2YM16DXg0klhS1yQok9VrRsXa$>

Look at the connections page, do you see the connector listed there?
[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/89584709/265528522-f8de7ce4-6281-4459-b00a-bb87474fac50.png__;!!MfzFaTml5A!g8sbCPimWtS3eRJzuGLCnA8kHsqvUDdkFEOBq7Qd7VnzQwA0PWqaSnF2a0t2W6Ey94yBr_8-2wweMcS2YM16DXg0klhS1yQok4jemuyD$>

Click app details, does the app load?
[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/89584709/265528564-fa1e7f90-291e-4641-8406-91b8ea6c8a26.png__;!!MfzFaTml5A!g8sbCPimWtS3eRJzuGLCnA8kHsqvUDdkFEOBq7Qd7VnzQwA0PWqaSnF2a0t2W6Ey94yBr_8-2wweMcS2YM16DXg0klhS1yQok4ZLG7d1$>

**Comment by faszul** [comment]
We are still waiting for the apps owners/dev to confirm the name of their PowerApps.

But let me give another example below which is Flows that using Azure Automation connectors

NewEmailRetentionPolicyAcquisitionsExceptions
NewEmailRetentionPolicyWaiversExceptions
 NewEmailRetentionPolicyLOAExceptions

We unable to find it in the Active Flows view too… although they are using the Azure Automation connectors.
It also not available in Connectors view under Used In - Flows



Regards,
Fahdzul
[Image]


From: Aziz, Fahdzul ***@***.***>
Date: Wednesday, 6 September 2023 at 12:54 AM
To: microsoft/coe-starter-kit ***@***.***>, microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG]Active Connectors does not show the correct usage by Apps and Flows (Issue #6470)
Thanks for the update.

We are compiling and confirming the name of the affected apps from the owners/developers - will update you soon.

Fahdzul
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Tuesday, September 5, 2023 3:04:02 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Aziz, Fahdzul ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG]Active Connectors does not show the correct usage by Apps and Flows (Issue #6470)

Please find the envt and app name for an app that the maker is telling you is blocked Find that app in the Power Platform Admin View and click it to open Look at the connections page, do you see the connector listed there? Click app details,


Please find the envt and app name for an app that the maker is telling you is blocked
Find that app in the Power Platform Admin View and click it to open
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/265528420-214d58fb-3787-4030-8365-e805fe1e9bb2.png__;!!MfzFaTml5A!g8sbCPimWtS3eRJzuGLCnA8kHsqvUDdkFEOBq7Qd7VnzQwA0PWqaSnF2a0t2W6Ey94yBr_8-2wweMcS2YM16DXg0klhS1yQok9VrRsXa$>

Look at the connections page, do you see the connector listed there?
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/265528522-f8de7ce4-6281-4459-b00a-bb87474fac50.png__;!!MfzFaTml5A!g8sbCPimWtS3eRJzuGLCnA8kHsqvUDdkFEOBq7Qd7VnzQwA0PWqaSnF2a0t2W6Ey94yBr_8-2wweMcS2YM16DXg0klhS1yQok4jemuyD$>

Click app details, does the app load?
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/265528564-fa1e7f90-291e-4641-8406-91b8ea6c8a26.png__;!!MfzFaTml5A!g8sbCPimWtS3eRJzuGLCnA8kHsqvUDdkFEOBq7Qd7VnzQwA0PWqaSnF2a0t2W6Ey94yBr_8-2wweMcS2YM16DXg0klhS1yQok4ZLG7d1$>

**Comment by faszul** [comment]
![932A2E78-A0FC-4472-8FA8-889DD93D5013](https://github.com/microsoft/coe-starter-kit/assets/142005629/c682d758-aab0-4bc0-86a6-5e0f101c76b7)
![278468D3-8D83-4748-BC42-4ACF8C2D16AB](https://github.com/microsoft/coe-starter-kit/assets/142005629/f0ba7799-21d4-4a4c-b165-5497f0773a09)

Screenshot attached

**Comment by Jenefer-Monroe** [comment]
Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by faszul** [comment]
These are the flows that is in “off state” … any Flows below that related that I should turn it on?

Admin | Add-Ons Alerts
Admin | Sync Audit Logs
Admin | Sync Template V3 (Environment Properties)
Admin | Sync Audit Logs (Flow Action Details)
DLP Request | Process Approved Policy Changes
DLP Request | Sync New Policy
DLP Request | Sync Shared Policies


And there is one solution layer existed for flow below.. if I click ‘Remove Solution layers’ what impact it will bring? Need confirmation before I proceed to click it.

Admin | Compliance detail request v3   (on state)


Regards,
Fahdzul
[Image]


From: Jenefer Monroe ***@***.***>
Date: Wednesday, 6 September 2023 at 3:18 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Aziz, Fahdzul ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG]Active Connectors does not show the correct usage by Apps and Flows (Issue #6470)
Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. — Reply to this email directly, view it on GitHub, or unsubscribe. You are


Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here.
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/261634052-598b5024-2e1a-4390-a6b2-49644368c246.png__;!!MfzFaTml5A!nmQbLLerN0S26Gwn2Ua3_3peTJv6Vrs1F7bcOpfg9qvq2q3y1p5MF2pIeDLQpOKgt7ZIyY2RKp2xyKUsOXEcuwwFPsrcbs3qcGb2J1Zf$>

**Comment by Jenefer-Monroe** [comment]
Unmanaged layers prevent you from getting updates from us. They represent a change you've made on the flow, intentionally or accidently. You should always remove them when you upgrade.

**Comment by Jenefer-Monroe** [comment]
Look at the most recent run of this flow: **_Admin | Sync Template v3 (Driver)_**
It should have occurred within the last day.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5ec0b509-6657-4bd3-ab48-e655b14cfc80)

Find and open the results of this action. Does it show the environment of the flow you are expecting to see?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dfac24e9-c7e6-4f84-8435-db1f1f3d360b)

**Comment by faszul** [comment]
Thanks Jenefer. Will it affect any flows if I remove this unmanaged layers?

Regards,
Fahdzul
[Image]


From: Jenefer Monroe ***@***.***>
Date: Wednesday, 6 September 2023 at 7:54 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Aziz, Fahdzul ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG]Active Connectors does not show the correct usage by Apps and Flows (Issue #6470)
Unmanaged layers prevent you from getting updates from us. They represent a change you've made on the flow, intentionally or accidently. You should always remove them when you upgrade. — Reply to this email directly, view it on GitHub,


Unmanaged layers prevent you from getting updates from us. They represent a change you've made on the flow, intentionally or accidently. You should always remove them when you upgrade.

**Comment by faszul** [comment]
Thanks Jenefer.

We dont have Sync Template v3 (Driver) but the one attached. I can see the status is Succeeded but when i view the flows it also have error as per the screenshot I attached. And it also have unmanaged layers icon beside it.

![F223A273-C82E-4554-AD21-33CEBC79E4D5](https://github.com/microsoft/coe-starter-kit/assets/142005629/25e9c55b-24b8-4636-8757-1a719d43ea85)
![5429F453-037C-4354-AE43-1C79A64A6005](https://github.com/microsoft/coe-starter-kit/assets/142005629/294620d2-6082-4875-8a9f-0490ea8e4b36)
![B2F5258D-4742-4D71-9F68-996A509DC992](https://github.com/microsoft/coe-starter-kit/assets/142005629/e6aa2c04-75cb-4dbe-8372-cc673ff24db8)

**Comment by Jenefer-Monroe** [comment]
Yes please remove that unmanaged layer and then see if your target envt is shown in the spot indicated above.

**Comment by faszul** [comment]
Thanks. Let me try and update you.


From: Jenefer Monroe ***@***.***>
Date: Thursday, 7 September 2023 at 6:46 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Aziz, Fahdzul ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG]Active Connectors does not show the correct usage by Apps and Flows (Issue #6470)
Yes please remove that unmanaged layer and then see if your target envt is shown in the spot indicated above. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message


Yes please remove that unmanaged layer and then see if your target envt is shown in the spot indicated above.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
