### ISSUE TITLE
[CoE Starter Kit - QUESTION] View all Default Environment Makers 

### ISSUE THREAD

**Issue by FC-SMS** [microsoft/coe-starter-kit#6477]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are looking to manage the default environment better by reviewing who has been creating what in the default environment and then applying our internal governance to these workloads.

Is there a way to see at a glance all the makers in a certain environment? 

I think i am effectively looking for a view similar to the All Makers view but filtered to show only a specific Environment. Looking at what is there, i am thinking that to do this i will need to extend the CoE Core.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

we don't have a view that exactly meets your criteria but your best bet is to look at the Power BI dashboard

If you look at the Makers tab there, you can add an additional filter for the Environment Name and select your Default environment there. 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-nurture#makers

You may have to change some of the visuals as they're looking at the "Top 10" at the moment and you'd want to see all makers
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/9510eb7e-6d83-4c8a-a508-e100d012e06d)

Another option is to explore the Default report in the Compliance and Governance dashboard and see if you want to modify that to give you a list of all makers
https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-compliance#default-environment

Makers are only indirectly related to environments (via the apps, flows,...) they built so I think using Power BI (vs the model driven Power Platform Admin View app) will be easier for you as we've already done the required relationships there.

**Comment by FC-SMS** [comment]
Thanks Manuela.

We are looking to create a mini system for all the workloads in the default environment that allows us to manage our governance processes. Thought the best place to start was customising the CoE Core Components was the best place to start and evolve as we mature on our journey. The Power Platform Admin View app is awesome but want to incorporate something less busy that is tailored for us and compliments the Admin View app.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
