### ISSUE TITLE
[ALM Accelerator - Question]: Retain Dev solution version

### ISSUE THREAD

**Issue by challa85** [microsoft/coe-starter-kit#6478]
### Is your feature request related to a problem? Please describe.

Currently, when we are importing the solution to QA/UAT or Prod environments using the ALM Accelerator app update the solution version with the DateTime stamp but we would like to update the solution with the same version as of Dev solution.
This way we can make sure whether all the environments are in sync or not.

Eg: In Dev, we have solution version history as 1.0.0.27 but when we are importing to other environments it is updating as 1.0.20230823.2(with date time stamp).

### Describe the solution you'd like

Please update the solution version same as the Dev solution.

**Comment by mikefactorial** [comment]
@challa85 thanks for the question. Take a look at this learn article.  https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/configure-azuredevops-pipelines#turn-on-or-off-specific-actions-in-the-pipelines

There's a variable you can set on the export pipeline ```UseSolutionVersionFromDataverse``` that will accomplish what you are attempting to do. Settting that variable to true will retain the solution version from Dataverse on export and then in subsequent deployments.

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here.
