### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to extend "CoE Flows" in the Admin Command Center with custom flows

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#6479]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hey guys,

I have created a custom flow in a separate solution (also managed), You can display this flow in the gallery of CoE Admin Command Center flows.

I would like to monitor all flows that are customized from Kit CoE

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by ClaudioRWS** [comment]
Good morning!

exactly, I updated the solution core components to 4.13, but I have separated an old custom alert flow into a custom solution.


![image](https://github.com/microsoft/coe-starter-kit/assets/94450591/82d210f1-f1a1-4a77-9e3b-f7adbefa4a03)

![image](https://github.com/microsoft/coe-starter-kit/assets/94450591/7431b3da-a7aa-406e-bd41-adb8f499fcd7)

**Comment by Jenefer-Monroe** [comment]
Got it. We dont have a path to customize these, but if you add the flows to the metadata table manually, and then just write a helper to touch your records (rewrite some column) every day, then they should show up and remain. I hope that helps!
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/31260f6d-dd67-49f5-81ba-9bb68d99ff07)

**Comment by ClaudioRWS** [comment]
Jenefer, thank you very much, it helped me a lot.

obrigado!
