### ISSUE TITLE
[CoE Starter Kit - BUG]: Audit log solution issue

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/coe-starter-kit#648]
Describe the bug
The flows relating to the audit log solution are coming up with errors. We've upgraded to the latest version of the solution.

Component (please tell us which flow or app you are experiencing issues with):

Solution - Core
Version - 1.41
App or Flow - [Child] Admin | Sync Logs and Admin | Sync Audit Logs

To Reproduce
The errors occur when the flows runs on it's set schedule.

Expected behavior
The flows should run without any errors.

Screenshots
I've attached screenshots and text files containing the error for each flow.

[Admin Sync Audit Logs.txt](https://github.com/microsoft/coe-starter-kit/files/6671112/Admin.Sync.Audit.Logs.txt)
![Admin Sync Audit Logs screenshot](https://user-images.githubusercontent.com/62425530/122420462-9c9afb00-cf83-11eb-9580-12cb3a4939e0.PNG)
[[Child] Admin - Sync Logs.txt](https://github.com/microsoft/coe-starter-kit/files/6671113/Child.Admin.-.Sync.Logs.txt)
![Child  Admin Sync Logs screenshot](https://user-images.githubusercontent.com/62425530/122420468-9dcc2800-cf83-11eb-89b2-accc8e9c6df1.PNG)

**Comment by JeneferM-MSFT** [comment]
It sounds like you have edited the parent flow or in some way changed the communication between them such that the time parameter is not being sent to the child. 
My recommendation is that you remove any unmanaged layers on both of the flows (see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)), and ensure your **Run only users** setting is set correctly as described in [Set up Power Automate flow](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow).
If this does not work, then delete the Audit Logs solution and reinstall following those same instructions.
