### ISSUE TITLE
[CoE Starter Kit - BUG] PBI BYODL Aug2023 - Type mismatch. Unable to convert a value to the data type requested for table 'AI Builder Models' column 'Created on (Month)'

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#6482]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have this error to refresh BYODL_CoEDashboard_August2023 in the cloud:

The following system error occurred: Type mismatch. Unable to convert a value to the data type requested for table 'AI Builder Models' column 'Created on (Month)'. The data provider was unable to convert the value '' from the source data type 'VT_BSTR' to the expected data type 'VT_DATE'. Please check the column data types in the data model and data source and ensure that the data types are compatible. The command has been canceled.. The exception was raised by the IDbCommand interface. The current operation was cancelled because another operation in the transaction failed. The command has been canceled.. The exception was raised by the IDbCommand interface. The command has been canceled.. The exception was raised by the IDataReader interface. Please review the error message and provider documentation for further information and corrective action. The command has been canceled.. The exception was raised by the IDataReader interface. Please review the error message and provider documentation for further information and corrective action. Table: AI Builder Models.

In local, I haven't the error 😢 

Any suggestion?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2023

### What app or flow are you having the issue with?

BYODL_CoEDashboard_August2023.pbit

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Do you mean to say that the bug only repros when the PBIT is published but not when on your desktop?

**Comment by albertocastro365** [comment]
Exactly!

**Comment by Jenefer-Monroe** [comment]
We did fix something for August and re-release the PBITs. https://github.com/microsoft/coe-starter-kit/issues/6234

Can you check to see if the currently uploaded PBIT has the issue? If so, then then ill send this over to Manuela to hopefully fix for Sept.

**Comment by albertocastro365** [comment]
Hi,
in the PBIT of #6234 I don't have the issue but I am using the BYODL pbit.

More information:
I have 2 coe environments: DEV and PROD, and 2 coe pbi workspaces.
The issue here posted is from prod dashboard but in DEV dashboard I have a similar error but with Desktop Flows table.

[PWPL CoE Dashboard] has failed to refresh.
Failure details: The following system error occurred: Type mismatch. Unable to convert a value to the data type requested for table 'Desktop Flows' column 'Created On (Month)'. The data provider was unable to convert the value '' from the source data type 'VT_BSTR' to the expected data type 'VT_DATE'. Please check the column data types in the data model and data source and ensure that the data types are compatible. The command has been canceled.. The exception was raised by the IDataReader interface. Please review the error message and provider documentation for further information and corrective action. The current operation was cancelled because another operation in the transaction failed. The command has been canceled.. The exception was raised by the IDataReader interface. Please review the error message and provider documentation for further information and corrective action. The command has been canceled.. The exception was raised by the IDataReader interface. Please review the error message and provider documentation for further information and corrective action. Table: Desktop Flows.

**Comment by Jenefer-Monroe** [comment]
I believe she reshipped both of those inventory PBITs. If you just download August again you'll see it

**Comment by albertocastro365** [comment]
Yes! This new versión works fine! Thanks @Jenefer-Monroe! Let me give you  🏆

**Comment by Jenefer-Monroe** [comment]
Wonderful, thanks for confirming!
