### ISSUE TITLE
[CoE Starter Kit - QUESTION] COE Environment permissions strategy 

### ISSUE THREAD

**Issue by nickmac88** [microsoft/coe-starter-kit#6484]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there some published advice for setting up permissions on the COE environments? I would like to do the following.

1. Restrict the ability to create apps/flows/bots in both my COE DEV and PROD environments.
2. Give all users default access to the flows/apps and any required resources in the solutions.
3. Restrict access to the environments via the Admins, Makers, and Users Groups. The only people who should have the ability to create in the environment are the Admins.
Is there any easy way to share all apps in the solutions without having to share each one individually?

I understand that each company may have different strategies for the roles so there may not be a 1 size fits all approach to this... But any advice on this matter would be very helpful.

I am sorry if i have asked this question in the wrong place. Please feel free to point me in the right direction if i have done so.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Latest as of August 2023

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello. The Security Roles we ship are only intended to give access to the data and apps needed for the Admin / Maker / User personas. They are not intended to give access to if you can / cannot create apps and things like that. There are built in SRs you would need to explore and use for that like **_Basic User_**

For more information please see [Configure user security in an environment](https://learn.microsoft.com/power-platform/admin/database-security)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
