### ISSUE TITLE
[CoE Starter Kit - QUESTION] How best handle PBIs when upgrading?

### ISSUE THREAD

**Issue by HenningStrand** [microsoft/coe-starter-kit#6485]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the documentation there is content on how to upgrade the kit, but I cannot find anyhing is mentioned of how to best handle the PBIs. I just go through the regular setup as described in https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi, but then end up with new datasets and reports every upgrade. Any way to just update the exising ones, keeping the same url, sharing, embedding, etc.?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

July 23

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Unfortunately not. You just need to recreate with the fresh PBITs each month. 
If you save as the same name each time before publish to the workspace (ex: Contoso Power Platform CoE) you do overwrite the file in the workspace in PowerBI.Com so you wont need to reshare / restart the recurring refresh etc.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
