### ISSUE TITLE
[CoE Starter Kit - QUESTION] HTTP with Azure AD connection configured incorrectly

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6489]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

HTTP Request fails on both GetTenantID and GetUserDetails setup flows. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/dd06c0fe-437e-4f74-b659-3cdad448b149)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/a29ffaa0-8261-4de2-8cbf-42f301a5e97d)

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/9997a8eb-1f69-4144-9176-eaf6e44216e7)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/a01187b1-b3d2-4dbf-bdb8-1cfaf001b23c)

### Expected Behavior

setup flows should work

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

SetupWizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
That sounds like you've incorrectly configured the HTTP with Azure AD connection. Your base URL shouldn't have anything related to crm.dynamics in it (from your error message)
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/6eac415a-3c9c-48fb-888c-e91de5491db9)

Instead your Base URL and Azure AD resource URL need to be set to the following
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/dfb9dab0-e841-4399-9295-e42df7cb66f9)

This is explained in our documentation here
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections

I'd recommend you delete your HTTP with Azure AD connection and re-configure it. You may also have to update the connection reference for this connector.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
