### ISSUE TITLE
Cannot see a Dataverse for teams environment in the COE environment Admin view.

### ISSUE THREAD

**Issue by shallyboi** [microsoft/coe-starter-kit#6490]
Hello all, is it Possible to excuse a Microsoft Teams Environment from the Compliance Flow ?, The environment does not show up in the COE CORE Environment when looking for it via the "Admin view" Model driven app. However, when it is viewed from the Default environment, the teams environment shows up. Even after excusing the Default environment from the compliance flow, Compliance warning messages are still sent to user.  https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components

**Comment by Jenefer-Monroe** [comment]
What do you mean by this? `However, when it is viewed from the Default environment, the teams environment shows up.`

**Comment by shallyboi** [comment]
When you open the Default environment and you go to Admin view, you will see the said Dataverse for Teams environment listed there.  I have excused the default environment as a whole from the complaint flow but I still get the messages.

**Comment by Jenefer-Monroe** [comment]
Apologies but I'm still not following. Can you please share a screenshot of where you **are** and **are not** seeing the Teams environments listed?

**Comment by shallyboi** [comment]
Under Infogain (default) Environment we are able to see that Teams App but under Power Platform Coe Environment, it is not Visible.

**Comment by shallyboi** [comment]
I cannot attach pictures, it keeps throws an error

**Comment by Jenefer-Monroe** [comment]
Sorry without pictures I am just not following you. Perhaps you can update a word file with the pictures in it?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
