### ISSUE TITLE
[ALM Accelerator - BUG]: Step timeout: "Update Solution Component Ownwership"

### ISSUE THREAD

**Issue by rhulshof** [microsoft/coe-starter-kit#6492]
### Describe the issue

When deploying my Solution, the step called "Update Solution Component Ownwership" reports a timeout after 2 minutes. My Solution contains 72 Flows, which ALM Accelerator apparently is not able to process within the set 2 minutes.

### Expected Behavior

The job to work with a reasonable timeout, higher than the currently set 2 minutes. Perhaps 15 or 30 minutes?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

CenterofExcellenceALMAccelerator_1.0.20230802.1_managed.zip

### Steps To Reproduce

Deploy a Solution using ALM Accelerator, containing a large number of Power Automate Flows.

### Anything else?

Starting: Update Solution Component Ownwership

Task : PowerShell
Description : Run a PowerShell script on Linux, macOS, or Windows
Version : 2.226.2
Author : Microsoft Corporation
Help : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell

##[warning]Environment variable 'VSTS_PUBLIC_VARIABLES' exceeds the maximum supported length. Environment variable length: 33814 , Maximum supported length: 32766
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a_temp\cea385e6-1130-4468-915e-4bd125cef416.ps1'"
Importing PowerShell Module: D:\a\1_coe\ALM_ACC\da\2.8.14\Microsoft.Xrm.Data.PowerShell - 2.8.14
Inside Get-OwnerFlowActivations
Ownership Configuration Content - [{
"solutionComponentType" : 29,
"solutionComponentName" : "NotifyITTeam",
"solutionComponentUniqueName":"50f82263-ba7c-eb11-a812-000d3abf9898",
"ownerEmail": "EU_D365_FS@OUR_DOMAINNAME.com"
},
{
... 71 more configuration objects ...
}]
Inside Get-OwnerFlowActivations; Printing Active Flows
activationConfigs -
systemuserid - 0cfbe699-989e-ea11-a812-000d3a3a7f02
3 - Adding flow NotifyITTeam to activation collection
0

... 70 more similar lines ...
systemuserid - 0cfbe699-989e-ea11-a812-000d3a3a7f02
3 - Adding flow zzzWOSPlabelrequested to activation collection
72
Deactivating the Flow
##[warning]Errors occurred while updating solution component ownership. Please review the log for specific errors and verify your deployment configuration settings.
************ TimeoutException - SetState : Setting Activity State in CRM... workflow |=> The request channel timed out while waiting for a reply after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
The request channel timed out while waiting for a reply after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. => The HTTP request to 'https://OUR_ENVIRONMENT_NAME.crm4.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.45.2156' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout. => The operation has timed out[TerminalFailure] Failed to Execute Command - SetState : RequestID=c9268600-98bb-4222-9223-340e7a94c527 : Setting Activity State in CRM... workflow duration=00:02:00.3937462 ExceptionMessage = The request channel timed out while waiting for a reply after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
The request channel timed out while waiting for a reply after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. => The HTTP request to 'https://OUR_ENVIRONMENT_NAME.crm4.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.45.2156' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout. => The operation has timed out
##[error]PowerShell exited with code '1'.
Finishing: Update Solution Component Ownwership

**Comment by mikefactorial** [comment]
@rhulshof the two minute timeout is a platform timeout not an ALM Acclerator or DevOps timeout. There should be no reason under normal circumstances for this timeout to be hit since we set the owners on the Flows one at a time so the number of Flows wouldn't make a difference. My guess is that there was something happening server side in your Dataverse environment at the time you hit this timeout that was blocking the set owner call. Have you tried this again since getting the original error?

**Comment by rhulshof** [comment]
Thanks Mike! Your comment made me think of trying to activate some flows manually in the target environment. It turned out that 2 were corrupt, as they were leveraging a Dataverse Column that no longer existing. In the Power Apps Maker (make.powerapps.com) Portal, the error message was pretty clear. In this Pipeline Step however this resulted in the given timeout. So you are right, it's not a bug in the ALM Accelerator fortunately. However, a potential improvement on the error handling could save other developers in the future some time solving any issues. Just a thought. Thanks for your efforts and good work on the ALM Accelerator. I love it!

PS: I created a Hook that exports Configuration Migration Data as part of the export-to-git Pipeline, matching the already existing "Import Configuration Migration Data" Pipeline Step. Please let me know if that would be a feature of interest to you. I am happy to share it.
