### ISSUE TITLE
changing flow owner when previous owner is blank fails.

### ISSUE THREAD

**Issue by krishnasubhashb** [microsoft/coe-starter-kit#6495]
Unable to make myself as a owner.  I'm the global admin, configuring this CoE for the 1st time. I'm not sure how the other person got added as a Owner. Can someone help me with changing the Owner and with the resolution of error?

![image](https://github.com/microsoft/coe-starter-kit/assets/136664183/39877b36-6dec-4c5b-a869-69aebf68828a)

error : Please see the below error and advise
![image](https://github.com/microsoft/coe-starter-kit/assets/136664183/1a84ae04-73ad-4ab5-85cd-16423684fb38)

when i run the app, it throws below errors. I'm not sure what exactly happened. Appreciate if you can help me with this issue.


Office365Users.UserProfile failed: { "status": 404, "message": "No user found with the specified id.\r\nclientRequestId: 8611809b-5af6-48de-a8d5-72d322efe5b7\r\nserviceRequestId: 415492d5-71c7-490d-85e2-426703252d63", "error": { "message": "No user found with the specified id." }, "source": "office365users-eus2.azconn-eus2-002.p.azurewebsites.net" }

Office365Users.UserPhotoMetadata failed: { "error": { "code": "ErrorUserResolutionFailedUserDoesNotExist", "message": "Exception of type 'Microsoft.Fast.Profile.Core.Exception.ImageNotFoundException' was thrown.", "innerError": { "date": "2023-09-01T14:47:13", "request-id": "fa37a56b-7928-41bd-a619-076e96351fef", "client-request-id": "fa37a56b-7928-41bd-a619-076e96351fef" } } }

Office365Users.UserProfileV2 failed: { "error": { "code": "-1, Microsoft.SharePoint.Client.ResourceNotFoundException", "message": "Exception of type 'Microsoft.SharePoint.Client.ResourceNotFoundException' was thrown.", "innerError": { "date": "2023-09-01T14:47:14", "request-id": "f9363ad3-8127-4484-a8cd-8817abaa0cd4", "client-request-id": "f9363ad3-8127-4484-a8cd-8817abaa0cd4" } } }

**Comment by Jenefer-Monroe** [comment]
Can you please clarify here, you are in the context of the PBI correct? And you've selected a flow who's permissions you want to update.
From there which button do you hit?

**Comment by krishnasubhashb** [comment]
Yes, I'm using Production_CoEDashboard_August2023.pbit file to get all the reports by providing environment URL . I can access  App Deep Drive report, where as my flow deep drive is having issue with "Power Apps | Admin - Access this Flow ". I would like to update my account with Owner Access with "Power Apps | Admin - Access this Flow ", but i can get only edit access.

I'm also getting below errors 
Office365Users.UserProfile failed: { "status": 404, "message": "No user found with the specified id.\r\nclientRequestId: 8611809b-5af6-48de-a8d5-72d322efe5b7\r\nserviceRequestId: 415492d5-71c7-490d-85e2-426703252d63", "error": { "message": "No user found with the specified id." }, "source": "office365users-eus2.azconn-eus2-002.p.azurewebsites.net" }

Office365Users.UserPhotoMetadata failed: { "error": { "code": "ErrorUserResolutionFailedUserDoesNotExist", "message": "Exception of type 'Microsoft.Fast.Profile.Core.Exception.ImageNotFoundException' was thrown.", "innerError": { "date": "2023-09-01T14:47:13", "request-id": "fa37a56b-7928-41bd-a619-076e96351fef", "client-request-id": "fa37a56b-7928-41bd-a619-076e96351fef" } } }

Office365Users.UserProfileV2 failed: { "error": { "code": "-1, Microsoft.SharePoint.Client.ResourceNotFoundException", "message": "Exception of type 'Microsoft.SharePoint.Client.ResourceNotFoundException' was thrown.", "innerError": { "date": "2023-09-01T14:47:14", "request-id": "f9363ad3-8127-4484-a8cd-8817abaa0cd4", "client-request-id": "f9363ad3-8127-4484-a8cd-8817abaa0cd4" } } }

**Comment by Jenefer-Monroe** [comment]
And is the owner really blank? Or did you erase it for privacy?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1dd9bb4c-c877-4e34-8806-229ff13a0e5c)

**Comment by Jenefer-Monroe** [comment]
OK i think i may have missed the case where this is blank, I've never seen it blank before. Can look into the helper flow this calls.

**Comment by Jenefer-Monroe** [comment]
Im afraid I cant commit to that but I do have it in my targets for the month yes.

**Comment by Jenefer-Monroe** [comment]
ok I actually think there isnt a change here from us to do. We dont allow ownership change generally from this app you have to do it from the one described below. And it does not seem to have a limitation due to a blank id for old owner.

To change owner go to the Power Platform Admin View app, find the target flow, and hit Manage Permissions.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e1742400-3c97-4fad-ac8a-d819f520ebf3)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
