### ISSUE TITLE
[CoE Starter Kit - BUG] Quarantined apps not showing in the view

### ISSUE THREAD

**Issue by ortizh** [microsoft/coe-starter-kit#6496]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

**Unable to see Quarantined Apps under the Quarantine Apps view.** 
Ex: This App is quarantined but it is not labeled as quarantined under the "App is Quarantined" field and therefor it does not show under the _Quarantined Apps for the Power Platform Admin View App._
![fdcd3763-9913-4010-a4a6-1ef60a1008b5](https://github.com/microsoft/coe-starter-kit/assets/16614595/29910208-99d9-4839-b49b-1efb83198bff)
![b59bc167-d170-4f4b-a468-b98a94d21852](https://github.com/microsoft/coe-starter-kit/assets/16614595/a4a51f96-61a1-4bbb-b2a0-c461009c1343)

### Expected Behavior

Be able to see all Quarantined App under the Quarantined Apps View

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.9

### What app or flow are you having the issue with?

n/a 

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the Power Platform Admin View App 
2. Navigate to Quarantined Apps View
3. Nothing is displayed as somehow all quarantined apps are not being tagged as quarantined

**Comment by Jenefer-Monroe** [comment]
Do you know when and how the apps are quarantined? We go off the inventory and so the view will only work once the app is updated in inventory after the quarantine occurs. 
If you go kick off the **_Admin | Sync Template v3 (Driver)_** flow, upon completion of the suites run you should see the apps in that view.

**Comment by ortizh** [comment]
Hi Jenefer!

Apps should be quarantined if ever they are not compliant compliant for more than 14 days.  There is the _**Admin | Quarantine non-compliant app**_s flow and the _**Admin | Set app quarantine status**_ that are running successfully. 
The flow Admin |Sync Template v3 (Driver) is off.  Could that be the reason why the Quarantine View under apps it is not showing ?

**Comment by Jenefer-Monroe** [comment]
Yes all flows related to inventory need to be turned on in order to know that you have a complete inventory.
Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

If you have a bunch of flows turned off you may want to boot the setup wizard as it will ensure they get turned on in the correct order.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
