### ISSUE TITLE
Setup Wizard fails on Pre req page

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#6498]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We just installed the COE and the preq page gives us this error: SetupWizard>GetCurrentEnvironment.Run failed as well as the below error message.

![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/7e0a39df-9ce2-4c49-958e-68031af08ef7)

### Expected Behavior

Wizard loads correctly.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

GetEnivronment Setup Flow

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

is your tenant in a commercial cloud or government cloud (like GCC, GCC High or DoD)? 

can you look at the SetupWizard>GetCurrentEnvironment cloud flow run and share the failure you get from there?

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
