### ISSUE TITLE
[ALM Accelerator - BUG]: Unable to Set Solution Customizatoins

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6499]
### Describe the issue

I get the following error message
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/aadd7855-7c02-4540-85b7-938b187e47ba)

When I try to add a team to share I am unable to share options 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/e41c202c-24d1-4de9-846b-f900be5eaf95)

### Expected Behavior

It should work

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

August 2023

### Steps To Reproduce

Open canvas app and go to solution configuration.

**Comment by mikefactorial** [comment]
@nasilvae would recommend trying to run the SearchAADGroup flow directly to narrow down the issue. It's possible there's a problem with the HTTP with Azure AD Connection or possibly a permissions issue in Azure AD that is blocking the call. Tough to tell from the error message show in the app.

**Comment by nasilvae** [comment]
> @nasilvae would recommend trying to run the SearchAADGroup flow directly to narrow down the issue. It's possible there's a problem with the HTTP with Azure AD Connection or possibly a permissions issue in Azure AD that is blocking the call. Tough to tell from the error message show in the app.

I just reseted the http connection with azure and it fixed it thank you.

**Comment by mikefactorial** [comment]
Thanks @nasilvae thanks for reporting back. You should be able to share the flow assuming you are an owner. Will close this out for now.
