### ISSUE TITLE
[AA4PP] Include App save notes in Commit message 

### ISSUE THREAD

**Issue by coatsy** [microsoft/coe-starter-kit#650]
When I save a canvas app, I'm prompted (by Power Platform) for some change notes. When I commit solutions changes, I'm prompted for commit notes. The save notes aren't reflected in the commit message

If possible, I'd like all save notes included in the default commit message

The message from here

![image](https://user-images.githubusercontent.com/1772428/122484894-044f5580-d019-11eb-8670-1b9f6a4fa74f.png)

Should end up here

![image](https://user-images.githubusercontent.com/1772428/122484954-2b0d8c00-d019-11eb-9241-d9625aa57a5e.png)

**Comment by devkeydet** [comment]
This is not something we can do easily.  We must work within the constraints of existing platform APIs.  Will check with the studio team to see if there is even an API to tap into for this, but I don't think there is.  If there is, it is likely undocumented, and we only call undocumented APIs when it is absolutely necessary.  However, this is not high priority.  Agree it would be very convenient and synergistic, but not likely easily accomplished for us.  But we'll investigate.  The recommendation, for now, when using source control is to not provide save commentary, but instead put that in the commit message using the canvas app.

**Comment by mikefactorial** [comment]
Closing out this issue as well. @Coatsy thanks for all of the feedback, but not likely to invest here either. Feel free to open a new issue and we'll triage but nothing to do here on the CoE team side.
