### ISSUE TITLE
[CoE Starter Kit - BUG] Manage Permissions in Power Platform Admin View App is giving error

### ISSUE THREAD

**Issue by FQ365Microsoft** [microsoft/coe-starter-kit#6505]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After the upgrade, in the new version of the CoE toolkit, the model-driven app Power Platform Admin View is throwing an error as below when trying to manage permissions. This error is reproducible in multiple deployments.
PowerAppsforAdmins.GetAdminAppRoleAssignment failed: _scrubbedSensitiveData_

<img width="952" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/116768543/a953bba7-d33c-4acb-b96b-2e6533719ca5">

The Add User button does not work after selecting the role.

### Expected Behavior

The manage permissions should work and allow to assign roles to selected users.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1- Launch the Power Platform Admin View app.
2- Select any Canvas App
3- Click Manage Permissions

### Anything else?

The screen shot is attached.

**Comment by manuelap-msft** [comment]
We're already tracking this under https://github.com/microsoft/coe-starter-kit/issues/6308

Closing as duplicate.
