### ISSUE TITLE
[CoE Starter Kit - QUESTION] v3 flow versions remain in solution after Update

### ISSUE THREAD

**Issue by ecelermi** [microsoft/coe-starter-kit#6508]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello CoE Team,
We have currently upgraded the CoE Kit Core Components to the new version (4.13). 
After the upgrade, we have encountered the error in the Setup and Upgrade Wizard indicating that the flows Admin | Sync Template v3 (Apps) and Admin | Sync Template v3 (App Properties) is running and we need to wait until the flow runs.
When we have looked into the flows, we have seen the error BadRequest 400.
After checking the new version of CoE Kit, we have seen that there is a new version of the flows and we have deactivated the v3s.
Now, it seems like CoE Kit is running without any problems but we are not sure if this is the workflow of the new version and if we will encounter any problems in the new upgrade regarding the dependencies.
We have also assumed that there was a problem with the upgrade/update of the solution and therefore have tried to upgrade the solution again, but this has not solved the issue, as Power Platform has shown the message indicating that this version of the solution is already installed to the system.
Could you give information if this is an expected error in the new version and if we need to take further actions to prevent any upcoming problems in the system?
Thank you

### Expected Behavior

After investigation in another environment of CoE Kit, we have seen that the flows listed below are not included in the new version of CoE Kit:
Admin | Sync Template v3 (Apps)
Admin | Sync Template v3 (App Properties)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Apps) and Admin | Sync Template v3 (App Properties)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

We could not reproduce this error in another environment.

### Anything else?

-

**Comment by manuelap-msft** [comment]
Hello,

it's not expected that those v3 flows remain in the solution after an upgrade, however there's a few reasons why they could

- if you have unmanaged layers on those flows, they will remain in the solution
- if you have performed an Update and not an Upgrade https://learn.microsoft.com/en-us/power-apps/maker/data-platform/update-solutions, solution components won't be deleted either

If you can turn the v4 versions on and the v3 versions off, then we wouldn't expect any issues going forward.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
