### ISSUE TITLE
[AA4AM] Commit messages should end up in Pull Request

### ISSUE THREAD

**Issue by coatsy** [microsoft/coe-starter-kit#651]
As I commit my changes to my own dev branch, I leave commit messages. When I create a PR, my PR has a title and description. None of the commit content is carried over to the PR by default.

If there's only one commit in my PR, I'd like the title to default to the commit message.

If there's more than one commit, I'd like the title to default to the most recent commit message, and the description to default to include a list of all the commit messages.

Related to #650

**Comment by devkeydet** [comment]
We'll investigate whether the Azure DevOps REST API supports this.  If so, we can add it as an option.  If not, then it will be lower priority.  But I like the idea.

**Comment by mikefactorial** [comment]
Hey @coatsy, I'm closing this out as we haven't gotten much feedback in this area and the issue has been open for a long time. Not likely to invest in this as a feature.
