### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - Azure Monitoring Data Export

### ISSUE THREAD

**Issue by anujay111** [microsoft/coe-starter-kit#6511]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi 
I tried to search for this topic but couldn't find it.
We are trying to automate the process of setting up Azure Monitoring for each of the new Citizen Developer environment created (for monitoring both Dataverse events as well as Power Automate activities) . As a part of that we need to create new Application Insight and new Data Export records (separate for Dataverse / Power Automate) for each new environment. 

Has anyone achieved this? I would appreciate if anyone has thoughts.
Thanks
Vijay

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

in this GitHub repo we only triage questions specifically related to the CoE Starter Kit and ALM Accelerator solutions. For more generic questions related to Power Platform and to get help and input from the broader Power Platform Community, please post them in the Power Users community: https://powerusers.microsoft.com/

Thank you
Manuela

**Comment by anujay111** [comment]
Thank you for your response Manuela,
Sure i will flag this in the wider community.
Regards
