### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Cloud Flow Runs not populated

### ISSUE THREAD

**Issue by tsegato** [microsoft/coe-starter-kit#6514]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have installed the CoE Package (including audit logs components) and seems like flows are running as expected. However this table is not populated. Any ideas on how to troubleshoot this?

Problem also posted here:
https://powerusers.microsoft.com/t5/General-Power-Automate/CoE-Cloud-Flow-Runs-not-populated/m-p/2331851#M138208

### Expected Behavior

Table with runs should be populated

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Core components

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Go into dataverse and se table is empty

**Comment by petepuu** [comment]
@tsegato CoE cloud flows inventory method does not gather cloud flow runs. This is included only in Data Export (BYODL) inventory method

https://learn.microsoft.com/en-us/power-platform/guidance/coe/limitations#monitoring-cloud-flow-runs

**Comment by Jenefer-Monroe** [comment]
Thanks Pete for helping! 
Closing out as no further action for starter kit team
