### ISSUE TITLE
[CoE Starter Kit - QUESTION] Question related to Admin | Broken Connection Cleanup

### ISSUE THREAD

**Issue by faszul** [microsoft/coe-starter-kit#6518]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In CoE cloud flows we found a flow called "Admin | Broken Connection Cleanup and the default status is Off.
We unable to find any KB related to this.

So our question:

- should we turned it ON
- will it affect other environment that excluded from the CoE 

![9FC49A18-4AC6-4F85-BAD3-8C70D762D0E6_4_5005_c](https://github.com/microsoft/coe-starter-kit/assets/142005629/6ad29ebd-29e5-4c69-82d1-33c0bccbc5e9)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.4.6070-2307.1

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
This flow was removed from our solution at the beginning of the year, as customers faced unintended issues with cleaning up connections. We do not recommend you switch this flow on. 

We also recommend you upgrade your solution to the latest version.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
