### ISSUE TITLE
[CoE Starter Kit - QUESTION] "Request Orphaned Objects Reassigned (Child)" flow - automatically reassign a co-owner 

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#6519]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi!
This question is a continuation of the #6517 question about the "Co-owners" information in the column.
We currently are experiencing lots of orphaned items because of employees leaving organization. After manual investigation we see that most of these items have co-owners, so we think it would really save time if there was a feature how to automatically reassign a co-owner (one of them?) as the owner of the item. Is there a chance that something like this might be implemented in the future?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.10

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, yes this is something we have on our backlog but have not yet implemented.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
