### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis [Preview] and DLP Editor v2 copy environments fault

### ISSUE THREAD

**Issue by fseinstein** [microsoft/coe-starter-kit#6521]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

in DLP Impact Analysis [Preview] or DLP Editor v2 when we create a copy of an existing DLP which contains connectors with  Endpoints configured, it doesn´t copy the Endpoints listed there!
Could you please check it? Is it a bug or an already known limitation?
Thank you!

### Expected Behavior

in DLP Impact Analysis [Preview] or DLP Editor v2 when we create a copy of an existing DLP which contains connectors with  Endpoints configured, it doesn´t copy the Endpoints listed.

For example: DLP with connector "HTTP with Azure AD" with Allow and Deny endpoints the copy won´t bring those connectors endpoints 

The same issue if the DLP have Custom connector patterns, it doesn´t copy them

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

DLP Editor V2

### What method are you using to get inventory and telemetry?

None

**Comment by fseinstein** [comment]
Thank you very much for your help!
And continue with the good work!
Regards

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
