### ISSUE TITLE
[CoE Starter Kit - BUG] Inactivity Process Flows

### ISSUE THREAD

**Issue by fosttj** [microsoft/coe-starter-kit#6524]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I came into work from holiday weekend to find that I and other (Admins) and (Makers) received emails from these two flows; Inactivity notifications "Admin | Inactivity notifications v2 (Start Approval for Apps) and Admin | Inactivity notifications v2 (Check Approval).  The flow states for these and all inactivity processes flows have been turned off since 8/28/2023, so there should have not been any emails sent out.  I checked the environment variable ProductionEnvironment and it was set to "yes", but have never had it send out emails unless the inactivity flows were turned on.

The only flows that I have found that ran during the time the inactivity emails were sent out were the Inventory flows (20 of them).
Would any of these flows call or launch inactivity flows? I have found no logs that show these flows ran.

### Expected Behavior

No inactivity flows to run or any inactivity emails be sent out to Admins or Makers.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2023

### What app or flow are you having the issue with?

Admin 

### What method are you using to get inventory and telemetry?

None

**Comment by fosttj** [comment]
Duplicate not sure why

**Comment by fosttj** [comment]
I closed the duplicate.

**Comment by Jenefer-Monroe** [comment]
They may have just been long running. 
Open the flows to their details page, you will see when the flow last ran and how long it took to run
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ccd957b5-0a38-49f4-b958-2a189bd348ad)

**Comment by fosttj** [comment]
The last run for this flow either succeeded or I canceled. I would have thought if it was still running it would have shown that in the history.

![image](https://github.com/microsoft/coe-starter-kit/assets/136116520/a150255c-2fa9-49f5-a7b8-18299213dc95)

**Comment by Jenefer-Monroe** [comment]
Yes it would have. Can you share a screenshot of the mail you received? That way we can know for sure which flow it came from

**Comment by fosttj** [comment]
Here is one that I as an Admin received.
![image](https://github.com/microsoft/coe-starter-kit/assets/136116520/a1419fb3-757a-4caa-8e87-7bbea9bb5990)

**Comment by fosttj** [comment]
Here is one that was sent by a Service Account to me (Admin)
![image](https://github.com/microsoft/coe-starter-kit/assets/136116520/346d7192-3030-4da0-85f7-f54fc055a00a)

**Comment by Jenefer-Monroe** [comment]
Ok those are both from those flows. I'm not sure what happened. Perhaps you have another instance of the CoE running somewhere. You could see this in your inventory. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/be3850b3-43ed-4af7-89f4-823a98229f04)

Or perhaps these got delayed in your email system.

**Comment by fosttj** [comment]
At this time I have two CoE environments, Prod and Sandbox and neither are setup to be part of the inventory process. They do not show in the dashboard that you uploaded. Also there is nothing installed in our CoE_Sandbox so it should not do anything related to flows or emails.

**Comment by fosttj** [comment]
This flow associates to one of the emails that I received and it correlates to day and time. How to backward engineer this flow to determine which flow called it?

![image](https://github.com/microsoft/coe-starter-kit/assets/136116520/ba412ee5-9535-40d7-b1d7-6de1845b32b5)

**Comment by Jenefer-Monroe** [comment]
You cant directly do that but you can look at the **_Send an email (V2)_** to make sure its the correct mail. 
And then you can look at the processes which call it to see if there are any outside of the kit
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/674fc0cd-ede7-4f69-88e7-99a580c61939)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2a45c9a7-f56d-43a7-852b-6712a2263cfb)

**Comment by Jenefer-Monroe** [comment]
Another idea would be to look at the suspect flow (if app or flow in your send email example)
Go to **_All runs_** and see if there are any long running ones these that may have finished over the weekend.

**Comment by fosttj** [comment]
Thank you Jenefer-Monroe. I found the problem. I had forgotten that I made a copy of the Admin | Inactivity notifications v2 (Start Approval for Apps) for testing and did not realize that I did not change the status to Off.  This was a bug alright, an ADMIN bug. ;)

**Comment by Jenefer-Monroe** [comment]
haha thank you so much for letting me know! I've done similar things in the past for sure.
