### ISSUE TITLE
Not all flows appear when checking the use of a connector

### ISSUE THREAD

**Issue by c05009a** [microsoft/coe-starter-kit#6528]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After auditing the connectors, we found out that a connector doesn't show all the flows where it is being used

### Expected Behavior

for governance best decisions we must be sure connectors should show the full list of flows/apps where they're being used.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

N/A

### What app or flow are you having the issue with?

NewEmailRetentionPolicyAcquisitionsExceptions NewEmailRetentionPolicyWaiversExceptions NewEmailRetentionPolicyLOAExceptions Grant-CSDialOutPolicy_ECS Grant-CSDialOutPolicy_BR

### What method are you using to get inventory and telemetry?

None

### Anything else?

we checked the power bi dashboard for CoE, and in there it shows the flows that don't appear on the web portal.

**Comment by manuelap-msft** [comment]
I think we already have an issue open for this here, this thread mentions the same flow names
https://github.com/microsoft/coe-starter-kit/issues/6470

Can you confirm this is a duplicate?

**Comment by c05009a** [comment]
Hi Manuela! I think the previous one was closed, both are about the same thing

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Manuela Pichler ***@***.***>
Sent: Wednesday, September 6, 2023 4:28:35 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Rodriguez, Jonathan ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] Not all flows appear when checking the use of a connector (Issue #6528)

External email: Do not click the links. Verify legitimacy before taking action.

I think we already have an issue open for this here, this thread mentions the same flow names
#6470<https://urldefense.com/v3/__https://github.com/microsoft/coe-starter-kit/issues/6470__;!!MfzFaTml5A!g3Gg11jsogVOtuhoQMIXsJHLcowksxcKthRXscuKyyoc4_gK-8w_spTuBjse-HD_BX4MBArh1b6JS-09RldjilR9WVowlDruVQ$>

Can you confirm this is a duplicate?

**Comment by manuelap-msft** [comment]
https://github.com/microsoft/coe-starter-kit/issues/6470 This one is still open, my colleague Jenefer just responded to it an hour ago.

**Comment by c05009a** [comment]
Awesome!, thank you Manuela

From: Manuela Pichler ***@***.***>
Sent: Wednesday, September 6, 2023 7:22 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Rodriguez, Jonathan ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] Not all flows appear when checking the use of a connector (Issue #6528)

#6470 This one is still open, my colleague Jenefer just responded to it an hour ago. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <microsoft/coe-starter-kit/issues/6528/1708353086@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
Do not click links or open attachments. Verify legitimacy before taking action.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/MfzFaTml5A!h6gBua38lD3ohHgEleeok0cm5zYtIMqEBsWIUG4UZmqkW1PVeQkZ7EbMhlqRCvuXIE2XkKoZJwWJNkWN59cPhSzwm2nyTjKQVARLNzyGh5YoVCaFHRLiiZ6ifs8$>   ‌
ZjQcmQRYFpfptBannerEnd

#6470<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/issues/6470__;!!MfzFaTml5A!nEnWAjds8V5UzPmrLgEaVVoYIHk0QUtqSqgJcSCXsufeR47mQjzov2ocyLh4CnTPHyqk3yriVXoFXpkjJrnusGtfuqN-c6MUxQ$> This one is still open, my colleague Jenefer just responded to it an hour ago.

**Comment by Jenefer-Monroe** [comment]
Will go ahead and close this dupe then. Thank you
