### ISSUE TITLE
[CoE Starter Kit-BYODL - QUESTION] Is the BYODL CoE kit version in preview or GA?

### ISSUE THREAD

**Issue by jayakumarkgds** [microsoft/coe-starter-kit#6529]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello team,
Just to confirm the BYODL COE kit is no more in preview right?Its GA and production ready right?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Data Export

**Comment by manuelap-msft** [comment]
The BYODL CoE kit uses a product feature called Data Export: https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics - this feature is still in public preview, and as the BYODL CoE kit fully relies on the data from this feature, the BYODL CoE kit version is also in public preview and will remain so until such as point as when the Data Export feature will go GA.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
