### ISSUE TITLE
[CoE Starter Kit - BUG]: Error while importing the CoE Starter Kit

### ISSUE THREAD

**Issue by PatricLiebelt** [microsoft/coe-starter-kit#653]
**Describe the bug**
I am installing the CoE starter kit in an sandbox environment
[importlog_CenterofExcellenceCoreComponents_2_1_70.zip](https://github.com/microsoft/coe-starter-kit/files/6676974/importlog_CenterofExcellenceCoreComponents_2_1_70.zip)
.
I am owner of the environment and Power Platform Admin.
During installation of the CoE starter kid I get an error that the file is to large and the installation does not complete. 

**Additional context**
Attached you find a logfile for the unsuccessful import.

**Comment by JeneferM-MSFT** [comment]
Where do you see this error about the file being too large? I do not see that. And I have not seen that with any other customers either, including in a sandbox install.

**Comment by PatricLiebelt** [comment]
Hi –

I am using this link to import the CoE Starter Kit.
https://orgc36e3be3.crm4.dynamics.com/tools/solution/import/SolutionImportWizard.aspx

This is what I try to import:
***@***.***D766A5.638449D0]
Importing the solution:

***@***.***D766A5.638449D0]

Progress…

***@***.***D766A5.638449D0]

This time I did get a different error message:

***@***.***D766A5.638449D0]

I attached the logfile…

Mit freundlichen Gruessen / With kind regards

Patric Liebelt

Manager Digital Efficiency
Daimler AG
HPC 096- O612

70567 Stuttgart, Germany

Mobile: +49-(0)160 86 28 290
Fax:        +49-(0)711 1779070150

**Comment by JeneferM-MSFT** [comment]
I'm afraid I dont know the names of the aspx files like that. Please share a screen capture of the issue you are seeing end to end. 

Note that you will need to share pictures in GitHub itself. Responding in email with pictures will not share the picture.

**Comment by PatricLiebelt** [comment]
I updated the last comment/mail of mine. Now I directly uploaded the pictures and the logfile in GitHub.

**Comment by JeneferM-MSFT** [comment]
It looks like you are using the legacy ux for solution import. Can you try installing using the modern import experience? See [this setup video](https://www.youtube.com/watch?v=Z9Vp2IxFzpU&list=PLi9EhCY4z99W5kzaPK1np6sv6AzMQDsXG&index=2) at minute ~5:45

**Comment by PatricLiebelt** [comment]
The modern ux did not work for us  due to the connector setup. We do not have a O365 right now, so I was not able to setup all the connectors. Using the legacy ux was the tip I got from our Microsoft consultants...

**Comment by PatricLiebelt** [comment]
I did try it again - 
So here are the connectors that I cannot setup...
- Office 365 Outlook (we do not have Outlook 365)
- SPO CoE Connection (we do not have SharePoint online)
- CoE Core - Teams (we do not Teams)
- Office 365 Outlook CoE Connection
- CoE Core - O365 Outlook
- Teams CoE Teams Integration
- CoE Http Azure AD
- Microsoft Teams CoE Connection

**Comment by JeneferM-MSFT** [comment]
I just tested and am able to install using the legacy ux as well. I do not get a sizing error.

**Comment by JeneferM-MSFT** [comment]
From your log it just sounds like you hit an issue with the product. 
"code":"InternalServerError","message":"Encountered internal server error. The tracking Id is '3320c073-9e0e-4068-8c67-f62ae10adfe2'."}}'

I'm afraid we cannot be of assistance as the issue you are hitting is in the product and not the toolkit. 

You will have to work with your MSFT consultant or support.
