### ISSUE TITLE
[ALM Accelerator - QUESTION] Profile Setup

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6531]
### What is your question?

Hi how can we setup the Accelerator to only use the following environment configuration?
Developer, Testing, Production. 

Remove the Validation Environment requirement. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

August 2023

**Comment by mikefactorial** [comment]
@nasilvae You should be able to remove the Validation Deployment Step from the Deployment Profile in the Admin app prior to the first export of the solution to bypass the validation pipeline deployment.

**Comment by nasilvae** [comment]
> @nasilvae You should be able to remove the Validation Deployment Step from the Deployment Profile in the Admin app prior to the first export of the solution to bypass the validation pipeline deployment.

 I'm having a hard time finding that option. Is this through the admin setup app?

**Comment by mikefactorial** [comment]
@nasilvae in the ALM Accelerator Admin app navigate to Deployment Profiles and open the profile you want to edit. At the bottom you'll see the Deployment Steps.
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/c432aa1c-9260-4b7b-9087-c78a4646c347)

**Comment by nasilvae** [comment]
> @nasilvae in the ALM Accelerator Admin app navigate to Deployment Profiles and open the profile you want to edit. At the bottom you'll see the Deployment Steps. ![image](https://user-images.githubusercontent.com/42348035/266754700-c432aa1c-9260-4b7b-9087-c78a4646c347.png)

it worked thank you very much

**Comment by mikefactorial** [comment]
@nasilvae thanks for confirming. Closing this out.
