### ISSUE TITLE
[ALM Accelerator - QUESTION]  ALM Accelerator connect to jekking or jira

### ISSUE THREAD

**Issue by will-franca** [microsoft/coe-starter-kit#6533]
### What is your question?

ALM Accerator connects in jekking or jira? Or is it necessary to have Azure DevOps.

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20221206.2

**Comment by mikefactorial** [comment]
@will-franca tthanks for the question. The ALM Accelerator only works with Azure DevOps currently.
