### ISSUE TITLE
[CoE Starter Kit - QUESTION] Getting error AF10001 The permission set () sent in the request does not include the expected permission. when trying to start Audit log subscription.

### ISSUE THREAD

**Issue by travusgonzalez-excellus** [microsoft/coe-starter-kit#6536]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have attempted to setup the CoE audit log features multiple times with Microsoft support guiding us live on a call but we continue to get errors when trying to start the audit log subscription. When starting the subscription we get an error "AF10001 The permission set () sent in the request does not include the expected permission." We have re-added the app registration, re-added the client id / secret multiple times. Tripple checked that the account we are using to setup everything has access to run the audit logs.

Any ideas what might cause this issue?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

core 4.15 Audit 3.12

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, first please go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated. Please share a screenshot
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

**Comment by travusgonzalez-excellus** [comment]
Unfortunately I am unable to upload screenshots, but I think this is the issue as ours is set to Delegated. I will adjust this and try again, thank you!

**Comment by Jenefer-Monroe** [comment]
You're most welcome.
