### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by FredrickLucerne** [microsoft/coe-starter-kit#6537]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When sending the teams card to the manager it proceeds to the "child flow" part but this flow id no longer exists.  What flow is it supposed to be executing here?

![image](https://github.com/microsoft/coe-starter-kit/assets/126117946/b426ccd4-c083-4687-a320-dc5bb541adc7)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

march release

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
In managed solutions the name of the flow does not show up there unfortunately.
Generally speaking you can see what flow its calling by looking at its dependencies (required objects). In this case you can see that this flow has a dependency on two flows: **_Request Orphaned Objects Reassigned (Child)_** and **_HELPER - Send Email_**

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cbafc151-90cd-45c8-a6ff-2a10ca84a741)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/18a5ee90-6b72-458c-9ec2-37dbbfedf5ee)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
