### ISSUE TITLE
[CoE Starter Kit - QUESTION] Only some desktop flows displayed in Power Platform admin view

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#6538]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Although I already found a reference here: https://github.com/microsoft/coe-starter-kit/issues/3025

My problem is a little different, I noticed that only a few desktop flows appeared in the visualization, but I have an environment with more than 2 thousand desktops flows that did not appear.

So I did the test by editing some field of the description of the environment in "Environment"

![Edit field](https://github.com/microsoft/coe-starter-kit/assets/94450591/d84c39ea-c364-49d3-beff-7ff921c18323)

And following the execution of the flow, I verified that it failed
![error flow](https://github.com/microsoft/coe-starter-kit/assets/94450591/66e7b1a0-e5c3-4515-8d28-a1587ca8030c)

So I changed the count to a much lower limit and successfully resubmitted the run.

![change run](https://github.com/microsoft/coe-starter-kit/assets/94450591/87e70401-6563-47de-b0db-0ec192ddb118)

![runs sucess](https://github.com/microsoft/coe-starter-kit/assets/94450591/2965a92b-3bc8-4043-8418-193375138653)

My question is: is the Dataverse Legacy action in this case not supporting listing the environment due to quantity?

![default](https://github.com/microsoft/coe-starter-kit/assets/94450591/1a8b0cd7-7ff2-4600-ab30-d33863a4cf98)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Thats correct, the real issue is that the legacy connector does not let you select which fields to return and to it basically returns the entire table of information. The Desktop Flows in the Process table in particular have a field that is basically the content of the desktop flow so it balloons quickly. 

The fix here is to use the modern dataverse connector, which allows us to select particular fields. We are just waiting for it to contain the feature to dynamically chose which environment to query. That shoudl be rolling in another few months and we will rewrite this product area first as it is the most blocked.

Hope that all makes sense!

**Comment by ClaudioRWS** [comment]
I don't know if it's possible, but through an environment listing to access the Workflows (Process) table, through the fetch xml process?

**Comment by Jenefer-Monroe** [comment]
Appreciate the suggestion. We are waiting for the connector update as we do have dozens of these to replace and then the legacy connector will be deprecated. So we do not want to do this work more than once and we also want to use the out of the box connector once ready. 
Hopefully we will be able to deliver this soon.

**Comment by Jenefer-Monroe** [comment]
I'm not sure I havent testing around that. It sounds like a good theory but it would require some testing around to validate. I'm afraid we dont have bandwidth to test around it to figure out on our side. But do let us know if you play around here, may help others to read.
