### ISSUE TITLE
[CoE Starter Kit - BUG] Cloud Flow Runs Table Not Populating

### ISSUE THREAD

**Issue by javiles1327** [microsoft/coe-starter-kit#6540]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are looking for information on Flow Last Run data, and we are unable to find anywhere that information is populated.  Specifically, we have found the Cloud Flow Runs table within the CoE Core Components, but it is blank.  Can you please tell us what should be populating that table, or how we can get the information we are looking for?

### Expected Behavior

Cloud flow run table populated.  Flow Last Run data accessible.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Cloud Flow Run table - uncertain which flow

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello we do not fill that table. It was added once for a feature we did not end up implementing and left it in there as some folks implemented it themselves and so have a dependency.
Sorry for the inconvenience.

**Comment by javiles1327** [comment]
thank you for your prompt response!
i know this isn't in the immediate scope of the CoE Starter Kit, but do we know if something similar is available if we installed the Automation kit?

**Comment by Jenefer-Monroe** [comment]
To my knowledge no, the automation kit focuses on Desktop Flows. 
The product team is working to expose this information natively and then we will be consuming it for cloud flows though.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
