### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Apps) - Action 'Get_Apps_as_Admin' failed

### ISSUE THREAD

**Issue by Rajeshgn053** [microsoft/coe-starter-kit#6545]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v4 (Apps) - Is throwing error for the environment that might have been deleted recently.
Though the initial actions are trying to verify the existence of the environment, the following action is failing with message that environment doesn't exist. 
Or, Possible issue is environment is deleted even though it's marked as not deleted in CoE Environments table
![Get Apps as Admin](https://github.com/microsoft/coe-starter-kit/assets/143060581/9442a585-4150-4cf9-926d-8aa331b0b0ce)

### Expected Behavior

The logic should handle the environments that got deleted with some additional check/delay introduced. And stop the execution at initial level

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Rajeshgn053** [comment]
Here are few more details regarding the issue. The environment for which the error occurred is actually deleted. However, when we checked the deletion details under "Environment" table. It shows none. 
One more observation - That particular row got modified at 09/07/2023 12:51 AM IST & at the same time, the above flo got triggered & throwed this error.

**Comment by Jenefer-Monroe** [comment]
Hello, you are seeing a few issues here.

### 1. Envt deleted but inventory flows still picked it up and try to inventory hence failure image above
Yes there is a timing issue that occurs occasionally in which the envt starts to be inventoried and then is deleted before it completes. You can ignore that and the next run of your inventory (initiated by Admin | Sync Template v3 (Driver)) will not repro again.

### 2. Envt deleted but not yet marked deleted in inventory
There is a set of flows used to update deleted objects in inventory that is long running and so only runs periodically. Please validate that all flows are turned on and that there are no unmanaged layers as shown below, and then the next run of **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** will mark the envt and its objects as deleted or remove them from the inventory depending on your settings.
Admin Command Center > CoE Flows > Inventory
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by Rajeshgn053** [comment]
Hi, 
We got the issue & applied fix with our research. Please check & revert back in case of any issues.
[Environment Not Found.docx](https://github.com/microsoft/coe-starter-kit/files/12596454/Environment.Not.Found.docx)

**Comment by Jenefer-Monroe** [comment]
Great thank you for following up and letting us know the cause. 
Will go ahead and close the case then since this was a transient issue due to this case:
- Envt was deleted after the flow started, the error would not recur the next day if that is the case.
