### ISSUE TITLE
[CoE Starter Kit - CoE Admin Command Center] I can´t load solutions

### ISSUE THREAD

**Issue by Asabadel** [microsoft/coe-starter-kit#6546]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I have an isssue with the CoE Admin Command Center app. I am using a power platform admin account with a premium license following the permissions and prerequisites below menitoned.

![image](https://github.com/microsoft/coe-starter-kit/assets/144326422/4e7dcd63-53b4-4a13-a46f-05323b73ee24)

Unfortunatelly, the app is not able to load any solution, please, see below image.

![image](https://github.com/microsoft/coe-starter-kit/assets/144326422/db45c07e-82f5-48d9-a977-857d2b3d91e3)

Please, could you provide any help on this topic?

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, per our [limitatons doc]( https://learn.microsoft.com/power-platform/guidance/coe/limitations#supported-languages), the CoE Starter Kit solutions are not localized, and only support English. Add the English language pack to your environment to make sure all apps and flows work. More information: [Regional and language options for your environment](https://learn.microsoft.com/en-us/power-platform/admin/enable-languages)
![image](https://user-images.githubusercontent.com/89584709/224966722-dd5d48e7-780d-46cb-b6ae-507318f03ad2.png)

**Comment by manuelap-msft** [comment]
Have you run through the [Setup Wizard](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-using-the-setup-wizard) (recommended) or through the manual install steps? The solution areas and what's shown here is populated as part of the setup and it looks like that data is missing for you.

**Comment by Asabadel** [comment]
> Have you run through the [Setup Wizard](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-using-the-setup-wizard) (recommended) or through the manual install steps? The solution areas and what's shown here is populated as part of the setup and it looks like that data is missing for you.

Hello,

Thanks a lot for your fast response.

We have checked and it seems that we used the manual install steps, as it was the February version.
How should we proceed with this issue? Can we just go throught the Setup wizard (The February preview version)? 
Also, as we want to update out version, maybe it is easier to just update to the May version (I saw that more than 3 months wasn´t recommended) and then fix the issues with the Setup Wizard.

Thanks a lot,

**Comment by Jenefer-Monroe** [comment]
Yes we cannot assist here with a kit version of that age so you will need to upgrade. 
You should be able to upgrade directly to the Sept release which just came out this week, I've been testing back further than normal lately for an upcoming mandatory upgrade. 

If you have the Audit Logs solution installed, please note that starting with the August 2023 release, you will no longer be able to upgrade the CoE Starter Kit Core Components until you either [switch to the new http methodology]( https://github.com/microsoft/coe-starter-kit/issues/6009) or [take a local copy of the old custom connector solution]( https://github.com/microsoft/coe-starter-kit/issues/6017) for your personal use.
See [This pinned issue]( https://github.com/microsoft/coe-starter-kit/issues/6018) for more details on how to fix this upgrade issue up.

**Comment by Jenefer-Monroe** [comment]
And do note also that you need to fix the language issue mentioned above as well.

**Comment by Asabadel** [comment]
> And do note also that you need to fix the language issue mentioned above as well.

Already done, thanks a lot.

So, after the update is there anything else we should do to fix the popullating data issue ?

**Comment by Jenefer-Monroe** [comment]
After the upgrade completes, boot the Setup Wizard. It will walk you through the upgrade, ensure all the new flows are turned on in the correct order, and trigger things like population of the bookmarks screen and doing other cleanup steps needed.

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b84cc1ff-383a-497c-9236-569e8313c73c)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
