### ISSUE TITLE
[CoE Starter Kit - QUESTION] Clean Up Orphan App/Flow Testing

### ISSUE THREAD

**Issue by uzma-fis** [microsoft/coe-starter-kit#6547]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am looking into what sort of notifications and chat messages managers would get. I have read through the walk through https://www.youtube.com/watch?v=0zptiBppTNo

I would like to sample test this out in the UAT environment we have where the environment variable is set to test (production = no)

What admin email are notifications going to be sent to as there are two configs 

admin_AdminMail and admin_ApprovalAdmin. 

Clean up orphan apps and flows is the next step to help clean up our environments but would like to test this before hand (is it even testable?)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 2023 4.9

### What app or flow are you having the issue with?

Governance Component

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello I believe you are asking if there is a way to test the orphans feature out with the prod envt env var. Yes you can. Basically it will send to the value in admin_ApprovalAdmin the cards.

**Comment by uzma-fis** [comment]
That is perfect. We don't know the real impact of this feature when we run it in production. Good to know!

**Comment by Jenefer-Monroe** [comment]
Glad to help!
