### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION Plan 2 License Not Recognized Post Upgrade

### ISSUE THREAD

**Issue by sjdwyer2** [microsoft/coe-starter-kit#6553]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am reporting on behalf of someone who upgraded their CoE and the setup wizard is telling them they are missing pre-requisites for Power Auto and Power Apps. This user has Plan 2, which is a legacy SKU. Is this expected behavior? 

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The CoE kit contains flows that run in context of Power Apps (for which a Power Apps license is sufficient), but most of the flows run standalone outside of the context of Power Apps thus a standalone license is required. Some of this may not be enforced in the product, e.g. you will be able to turn on a standalone flow if you only have a Power Apps license but it doesn't follow our license guidance, see here the Power Apps use rights only include execution of cloud flows within the app context
![image](https://user-images.githubusercontent.com/55705669/226404865-802a1abf-648e-4154-8b89-660153c61804.png)

Before the setup wizard, you likely just turned on the flows with your Power Apps license as the above guidance is not enforced today. 

Note that even in the setup wizard, you should be able to proceed to the next step despite missing this license - the check here is for information only.

**Comment by sjdwyer2** [comment]
Thank you Jennifer, I found this detail in the FAQ before I submitted.

What I need to understand is - does a Plan 2 license still offer premium app AND automate capabilities? Or is my user truly lacking a license necessary to run the kit?

If plan 2 is supposed to cover both (which was my understanding), why is it flagging the user on the pre-req screen?
[A screenshot of a computer  Description automatically generated]

Thanks,

Scott Dwyer (He/Him) - Sr. Technical Specialist - Business Applications | Health & Public Sector Industries  | +1 (608) 609-6056

**Comment by Jenefer-Monroe** [comment]
I'm afraid licensing questions are not something we can guarantee current knowledge about. You'll need to contact product support or your sales contact if you ahve one. But my understanding is that no, those licenses do not cover Power Automate

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
