### ISSUE TITLE
[CoE Starter Kit - FEATURE] Add Filter to DLP Impact Analysis list for customers with more than 2000 environments so they can perform impact analysis on the Default environment

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6555]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team, 

We are still experiencing the environment issue with the DLP Impact Analysis tool after the September upgrade. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/2dd9c5b1-c49b-4bb4-a057-64f340daa6e5)

Recommendations?
https://github.com/microsoft/coe-starter-kit/issues/6396

### Expected Behavior

It should show the environment list that has over 2800 environments. We have verified user to be a Power Platform admin and user can view the environments table with no issues directly. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

DLP Impact Analysis

### What method are you using to get inventory and telemetry?

Cloud flows

AB#926

**Comment by manuelap-msft** [comment]
It looks like you're not seeing any environments now, that's odd. Is the Environments table populated in your environment, e.g. if you go to the Power Platform Admin View > Environments, do you see environments there? 

I'm not sure if we can show 2800 environments due to delegation issues / some functions we need that aren't delegable. So the max we could show would be 2000. You may have to just use this solution as a template and see how you can bring in more than 2000 environments for your tenant.

**Comment by manuelap-msft** [comment]
Can you also share what the policy scope is please?

**Comment by nasilvae** [comment]
> It looks like you're not seeing any environments now, that's odd. Is the Environments table populated in your environment, e.g. if you go to the Power Platform Admin View > Environments, do you see environments there?
> 
> I'm not sure if we can show 2800 environments due to delegation issues / some functions we need that aren't delegable. So the max we could show would be 2000. You may have to just use this solution as a template and see how you can bring in more than 2000 environments for your tenant.

We tried with multiple accounts, and we experience the same issue. Both accounts are Power Platform admins accounts and will show all environments when opening the environment list under PPAC. They also can view the environment table directly with no issues. The scope of the policy is to be applied to multiple environments and we choose one test environment with the intent of changing it to the default environment using the DLP app so we could measure impact.

**Comment by manuelap-msft** [comment]
Can you check if you have unmanaged layers on either the DLP Impact Analysis model driven app or the DLP Impact Analysis page (custom page)? 

I don't repo this, I just tried it again with the latest version installed as managed in my test environment and it does show all environments I have in the tenant
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/509d5c3e-2907-4f03-9ec0-cdfe14980f43)

Have you waited on this page for some time? I suspect with 2000+ environments that the details list may take some time to load and we don't have a loading spinner/indicator on that screen so maybe it's just loading for a while?

If that doesn't work, I can only suggest that you edit the page and debug it from there to see why environments aren't being loaded in the collection.

**Comment by nasilvae** [comment]
> Can you check if you have unmanaged layers on either the DLP Impact Analysis model driven app or the DLP Impact Analysis page (custom page)?
> 
> I don't repo this, I just tried it again with the latest version installed as managed in my test environment and it does show all environments I have in the tenant ![image](https://user-images.githubusercontent.com/55705669/266610015-509d5c3e-2907-4f03-9ec0-cdfe14980f43.png)
> 
> Have you waited on this page for some time? I suspect with 2000+ environments that the details list may take some time to load and we don't have a loading spinner/indicator on that screen so maybe it's just loading for a while?
> 
> If that doesn't work, I can only suggest that you edit the page and debug it from there to see why environments aren't being loaded in the collection.

you were right the mda didnt had an unmanaged layer but one of the components did. We just removed it and we are getting a list limited to 2k. We also noticed that the added to policy environment showing in the app is not the same added environment in ppac. 

Also is there a way we can focus on getting all production and sandbox environments? This is currently a blocker for rolling out the environment strategy.

**Comment by nasilvae** [comment]
> > Can you check if you have unmanaged layers on either the DLP Impact Analysis model driven app or the DLP Impact Analysis page (custom page)?
> > I don't repo this, I just tried it again with the latest version installed as managed in my test environment and it does show all environments I have in the tenant ![image](https://user-images.githubusercontent.com/55705669/266610015-509d5c3e-2907-4f03-9ec0-cdfe14980f43.png)
> > Have you waited on this page for some time? I suspect with 2000+ environments that the details list may take some time to load and we don't have a loading spinner/indicator on that screen so maybe it's just loading for a while?
> > If that doesn't work, I can only suggest that you edit the page and debug it from there to see why environments aren't being loaded in the collection.
> 
> you were right the mda didnt had an unmanaged layer but one of the components did. We just removed it and we are getting a list limited to 2k. We also noticed that the added to policy environment showing in the app is not the same added environment in ppac.
> 
> Also is there a way we can focus on getting all production and sandbox environments? This is currently a blocker for rolling out the environment strategy.

Hi we tried the workaround of replacing the collect statement for environments with the following: 
col_environments, Filter(Environments, 'Environment Sku' = "Default")

This worked to kickoff the environment strategy conversation with the Default and Power Users environment. Can I suggest a filter in the DLP Impact Analysis tool which could filter by environment type? This could give us more highway using the collects and bypass the 2k limitation.

**Comment by nasilvae** [comment]
This is an example screenshot of the bug that shows the different environment names but same id for the added to policy screen. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/99b026d6-f0bf-4094-925b-5d8ec47c8160)

**Comment by Jenefer-Monroe** [comment]
Pushing the request for a filter to the bug list.

**Comment by manuelap-msft** [comment]
It's a little tricky for us monitoring multiple issues and asks in one ticket. We're fixing the issue related to the wrong environment name showing in the October release
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/ea6283c9-80ff-4a06-a71e-e2ce678e0d25) 

And we've got this bug open for it https://github.com/microsoft/coe-starter-kit/issues/6753

The ask to add a Default filter we'll see if we can address in November.

**Comment by Jenefer-Monroe** [comment]
to new dev owner

**Comment by nasilvae** [comment]
> to new dev owner

We have the drop down but we are missing the default sku which is the main environment we are working with. Can we add the default sku since this was part of the original ask?
