### ISSUE TITLE
[ALM Accelerator - BUG]: Azure DevOps > Project Group missing in the Administration App

### ISSUE THREAD

**Issue by LucasCXavier** [microsoft/coe-starter-kit#6557]
### Describe the issue

I'm trying to follow the final part of this documentation: https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#set-up-your-first-azure-devops-project-for-use-with-the-alm-accelerator

For some reason the "Azure DevOps > Projects" is not showing in my Model Driven Administration App.

Could you please help?

Thanks in advance!
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/cdad1a73-49d8-4a64-9f26-0eb1283b4e92)

### Expected Behavior

![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/71961d79-e79c-432d-a84f-a8b625fd2281)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230906.1

### Anything else?

https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#set-up-your-first-azure-devops-project-for-use-with-the-alm-accelerator

**Comment by LucasCXavier** [comment]
The GetAzureTenantInformation Flow is failing:
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/37bc94dc-f26b-43fb-ab12-68f5caff7a4b)

**Comment by LucasCXavier** [comment]
> The GetAzureTenantInformation Flow is failing: ![image](https://user-images.githubusercontent.com/105860879/266465028-37bc94dc-f26b-43fb-ab12-68f5caff7a4b.png)

I managed to resolve the issue by updating the JSON schema, but the Model Driven still doesn't display the Azure DevOps section

**Comment by mikefactorial** [comment]
@LucasCXavier is this an upgrade or first time install? If it's the former were you on a version that had the Project menu item previously? Is it possible that there are unmanaged layers on the solution that are blocking the upgrade? I just ran through a fresh install in another environment and the Projects menu item is there so could use a little more info about your environment to assist with what's going on.

**Comment by LucasCXavier** [comment]
> @LucasCXavier is this an upgrade or first time install? If it's the former were you on a version that had the Project menu item previously? Is it possible that there are unmanaged layers on the solution that are blocking the upgrade? I just ran through a fresh install in another environment and the Projects menu item is there so could use a little more info about your environment to assist with what's going on.

Hey Mike. Hope you are well!
This is a first time install. It's a personal Tenant that I'm using for test/study purposes.
Do I need to install any other solutions from the CoE Starter Kit?

Strangely, if I try to edit the Model Driven I'm able to see the Projects menu Item.

Please, let me know what additional information do you need. I'm going to try in a different Environment tomorrow.

**Comment by mikefactorial** [comment]
@LucasCXavier shouldn't need to install anything but the ALM Accelerator Solution. I believe this is a language setting issue since we don't have translations for that particular menu item. Unfortunately, we only support English currently. See [supported languages](https://learn.microsoft.com/power-platform/guidance/coe/limitations#supported-languages).

**Comment by LucasCXavier** [comment]
> @LucasCXavier shouldn't need to install anything but the ALM Accelerator Solution. I believe this is a language setting issue since we don't have translations for that particular menu item. Unfortunately, we only support English currently. See [supported languages](https://learn.microsoft.com/power-platform/guidance/coe/limitations#supported-languages). Try switching your preferences over to English and see if that fixes it. ![image](https://user-images.githubusercontent.com/42348035/266484578-05c41b00-e618-4526-bf05-a23c66eceff8.png)

Thanks a lot, Mike. Just changing the language fixed the issue.
