### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Policy in appears to require Azure Resource Manager for CoE Setup and Upgrade Wizard

### ISSUE THREAD

**Issue by tchagan** [microsoft/coe-starter-kit#6561]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have installed the latest September release for the CoE kit, specifically the Core solution. On launching the CoE Setup and Upgrade Wizard there was an error that indicated the app wasn't compliant with DLP policy.

It looks like this app isn't compliant with the latest data loss prevention policies.\r\n\r\nYour organization’s governance contact: _scrubbedSensitiveData_","details":[{"code":"MultipleViolations","message":"Policy name: <scrubbed>r\nBusiness connector: shared_office365users cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_arm.\r\nBusiness connector: shared_powerplatformforadmins cannot be used with no<truncated>

shared_arm is the Azure Resource Manager connector, the documentation does not include this as being required for the DLP policy for the CoE Starter kit.

Adding Azure Resource Manager to the DLP appears to fix the issue.

### Expected Behavior

CoE Setup and Upgrade Wizard runs without errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

In the environment play the CoE Setup and Upgrade Wizard, results in DLP policy violation error.

**Comment by manuelap-msft** [comment]
Hello,

that's correct, the setup wizard now requires Azure Resource Manager as we've added a capability to configure KeyVault secrets from the wizard.

Our documentation is still being reviewed by the content editor and we expect it to be updated in the next few days. 

Manuela

**Comment by tchagan** [comment]
okay, thanks for confirming, happy to close this.

**Comment by manuelap-msft** [comment]
We can leave it open until our documentation is updated, just in case others stumble over it too!

**Comment by fosttj** [comment]
At this time in Azure GCC our company is not approved to use Commercial Azure resources, is there a way to bypass this required connector? To take advantage of other updates in the September release?

**Comment by pnoot7** [comment]
It appears to be broken for GCC. During import it did not ask to create a connector for Azure Resource Manager. When launching the set up wizard, it wants me to sign into this connector, which I do not seem to be able to complete, it says it can't find an account with that name, even though its the same account I am signed into everything else with.

Any chance we can get some info on how this works? Appears to be broken for GCC, making CoE set up also broken as you can't continue.

**Comment by pnoot7** [comment]
Found this issue, before another one that describes my issue. https://github.com/microsoft/coe-starter-kit/issues/6569

**Comment by Jenefer-Monroe** [comment]
correct that is where we are trackign this mystery for GCC please do move there for the continued discussion

**Comment by manuelap-msft** [comment]
The documentation has now been updated:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

**Comment by pnoot7** [comment]
I have to disagree on closing this, the documentation is not complete. The connector will not work for GCC. I feel that should be noted in the documentation. It is not listed as a limitation on the connector documentation itself.

**Comment by Jenefer-Monroe** [comment]
The GCC issue is slightly different. The issue described here is about people being unable to load the app due to a DLP policy, and the fix is as described. This is just  normal PP use case and fix was just to document it.
Yours is due to the connector support itself being broken as you state. We are working around your GCC issue with these issues instead

1. Workaround for now described in: https://github.com/microsoft/coe-starter-kit/issues/6569
1. We've removed the connector from the app starting in Oct with this one: https://github.com/microsoft/coe-starter-kit/issues/6579
