### ISSUE TITLE
[CoE Starter Kit - BUG] Clean Up Old Objects App not keeping responses

### ISSUE THREAD

**Issue by Service-WebDevPowerP** [microsoft/coe-starter-kit#6563]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

managers are receiving emails stating that employees have ignored inactivity notifications, but the employees have responded by going into the Clean Up Old Objects app, but the responses in the app do not seem to be recorded in the dataverse tables and if you leave the app and go back in it is not recognising the reposes that were previously entered

![Capture](https://github.com/microsoft/coe-starter-kit/assets/105202791/8b9722ab-8a21-410f-83d7-ac5f25d4dc2d)

![tempsnip](https://github.com/microsoft/coe-starter-kit/assets/105202791/cff97c36-7123-4ae5-b2f6-f77110af4992)

![tempsnip2](https://github.com/microsoft/coe-starter-kit/assets/105202791/f6829da8-393d-4f4a-b6ce-4315d663ff1d)

![tempsnip3](https://github.com/microsoft/coe-starter-kit/assets/105202791/cf574191-12b7-48d7-bf40-d8be7da9d632)

### Expected Behavior

User rejects or approves the deletion in the Clean Up Objects App and that responses is recorded and the item is no longer included in the email to the manager about ignoring inactivity notifications

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.10

### What app or flow are you having the issue with?

Clean Up Old Objects All

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

See above

**Comment by Jenefer-Monroe** [comment]
This is a dupe to https://github.com/microsoft/coe-starter-kit/issues/5456
Thank you for posting as it lets me know to focus on that bug for next release. 
I'll go ahead and dupe to it, you can track that bug for the fix.
