### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | add Maker to a group - success even if the owner doesn't have the sufficient privilege to add the member

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#6564]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

hi,

I forgot to add my admin coe user as owner of the AAD security group that i use for makers.
The flow status is successful even if the Add member to a group action fails. 

I don't really know if it's a bug or if it's intentional.

For my part, I was surprised after a few days to see that there were no members in this group.

<img width="671" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/7638747c-7877-4309-a649-af895ad8c897">

<img width="304" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/34677a5a-0b19-4a2e-a528-9eb97d0efa8e">

### Expected Behavior

maybe make the flow fail so that we can see it in the COE admin command center?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September

### What app or flow are you having the issue with?

Admin [ Add Maker to a group

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
It was intentional in that we were catching the case where the user is already a member. 
But I can make this better to fail for other things like this.
Thank you for posting!

**Comment by Jenefer-Monroe** [comment]
Fix is to only try to add if not already a member. This way if it fails it wont be for a reason we want to catch.


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc1f6545-1384-4ed9-b7fa-3c240091363c)
