### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade failure due to dependency on Office 365 Management API

### ISSUE THREAD

**Issue by streibk** [microsoft/coe-starter-kit#6565]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Upgrading Center of Excellence Core Components from 4.11 to 4.15, received failed to import:

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 7 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Deprecated | [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7e6c8905c219f14a_a9da8, Id: 1c7eafbd-3072-ec11-8943-00224809e4bd, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7e6c8905c219f14a_39394, Id: a1676677-3272-ec11-8943-00224809e5b7, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7e6c8905c219f14a_238fd, Id: a64d8c9a-3472-ec11-8943-00224809e5b7, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7e6c8905c219f14a_a2337, Id: 2ea2402d-3572-ec11-8943-00224809e5b7, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: 95b23406-e652-4e72-bfdc-2967d50acb85, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5ff18d20b7ec3dbffe_a3e3b, Id: b5a862cf-f755-4b29-a861-87d93c8a6247, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

The import of release 4.15 was succesful however uninstall of 4.11 failed. 

![image](https://github.com/microsoft/coe-starter-kit/assets/58222800/003df316-470a-4374-8f9b-fd16830b4d12)

### Expected Behavior

Successful import of Core Components to release 4.15. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

See error noted in the issue.

**Comment by manuelap-msft** [comment]
Please see https://github.com/microsoft/coe-starter-kit/issues/6018 where we have a write up on how to handle this.

**Comment by streibk** [comment]
Thanks for the links based on the information provided I was able to upgrade to release 4.15 and convert over to HTTP format for gathering logs.
