### ISSUE TITLE
[ALM Accelerator - QUESTION] QUESTION Get-ChildItem : Cannot find path because it does not exist.

### ISSUE THREAD

**Issue by ChristopheHare** [microsoft/coe-starter-kit#6566]
### What is your question?

Hi guys,

After some help if possible, I am a bit of a novice, and by no means a Pro Coder. I have previously used DevOps to Upgrade the CoE Toolkit, but when was fortunate to have a chat with Mike, he raised some concerns on the set up I was using. 

I went back to square 1, following the Microsoft Guidance word for word.

As per Mike's advice i now have separate repositories for Source Code (Solutions) and Pipelines (coe-alm-accelerator-templates)

When deploying a "custom Solution" that's been created by a Maker within my organization, I am able to commit, Import & Deploy this solution, which is great, but facing issues with the coe-starter-kit.git in an attempt to handle the upgrades via ALM Accelerator.

The error I keep getting is 
Get-ChildItem : Cannot find path 'D:\a\1\s\coe-starter-kit.git\CenterofExcellenceCoreComponents\S' because it does not exist.

Within DevOps
![image](https://github.com/microsoft/coe-starter-kit/assets/118164862/2cdcb7aa-fb0b-444d-997d-7bf61769f620)

This is happening for all Source Repo's i have created/imported - CreatorKit, coe-start-kit, and the components within these. (not specific to CoreComponents)

any ideas on where i've gone wrong with the set-up or configuration? I'm sure it's something small and daft that I have missed. 

any help appreciated :)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

3.23062.17

**Comment by mikefactorial** [comment]
@ChristopheHare looks like the pipelines don't like '.' in the repo name. Try renaming the repo to just coe-starter-kit under Project ->Settings -> Repositories.

**Comment by ChristopheHare** [comment]
Will give that a go, Thanks Mike

**Comment by ChristopheHare** [comment]
@mikefactorial You are such a legend! Thank you so much again for your advice, and all that you guys do to bring such a wonderful thing to us.
![image](https://github.com/microsoft/coe-starter-kit/assets/118164862/1c73aad5-b72c-45bc-a07e-523be82068aa)
I knew it would be something minor, thanks for your time to take a look and point it out Mike.
