### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Prod Dashboard

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6568]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When we open the Connector Deep Dive report and we filter by environment name everything works. However when we filter by environment type everything works except the Default option. Please refer to the screenshot for additional details. We can choose the default environment from the name filter but not from the environment type filter. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/ade42c93-aab5-488c-910d-d7cd815f00da)

### Expected Behavior

Report should filter information consistently. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2023

### What app or flow are you having the issue with?

Power Bi Sept Prod Report

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
thanks for posting, to investigate for Oct

**Comment by manuelap-msft** [comment]
Thank you for raising this! 

The issue is the Default- prefix for the Default environment, so there's an issue with the relationship between Apps and Environments. Looking to fix this for October.

**Comment by manuelap-msft** [comment]
Fixed for Connector page:


![Image](https://github.com/microsoft/coe-starter-kit/assets/55705669/60aac1a6-afd5-4d2c-aa99-4866daf1c9a1)

**Comment by manuelap-msft** [comment]
Code complete for Production / BYODL dashboards for October.

**Comment by nasilvae** [comment]
> Code complete for Production / BYODL dashboards for October.

thank you, you guys are awesome!
