### ISSUE TITLE
Developer compliance center app

### ISSUE THREAD

**Issue by S0URCEC0D3** [microsoft/coe-starter-kit#6570]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the August 2023 version the developer compliance center center app is a model driven app. When setting up the compliance center, what kind of access will the regular users that aren't licensed to use dataverse need? 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

August 2023

### What app or flow are you having the issue with?

Developer compliance center app

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
This app has always used Dataverse - just the user interface has changed from a canvas app to a model driven app using custom pages. 

License: End users need to have a Per User license, or the app needs to be assigned a Per App license, or the environment needs to be covered by pay-as-you-go.

Access: End users need to be assigned the Power Platform Maker SR security role that is part of the CoE solution.

**Comment by S0URCEC0D3** [comment]
Thank you Manuela, due to this, I had to recreate the app on canvas and a flow to process the back end for user submission. When I do an upgrade, will this app and flow I created in the solution be removed?

**Comment by Jenefer-Monroe** [comment]
You should put your customized objects into your own solution. Ex: CoE-Extensions. That way upgrading components from us will not break your customized work.

**Comment by manuelap-msft** [comment]
I would also recommend you review the Power Platform licensing guide https://go.microsoft.com/fwlink/?linkid=2085130 specifically in terms of multiplexing. Architecting a solution to overcome licenses (e.g. moving data from a "free" back end to a "paid" backend) is typically considered multiplexing and may be in breach of your enterprise agreement.

**Comment by S0URCEC0D3** [comment]
> You should put your customized objects into your own solution. Ex: CoE-Extensions. That way upgrading components from us will not break your customized work. 

Do the upgrades remove any additional columns added to the dataverse tables?

**Comment by S0URCEC0D3** [comment]
> I would also recommend you review the Power Platform licensing guide https://go.microsoft.com/fwlink/?linkid=2085130 specifically in terms of multiplexing. Architecting a solution to overcome licenses (e.g. moving data from a "free" back end to a "paid" backend) is typically considered multiplexing and may be in breach of your enterprise agreement.

Oh that's not good. I might have to revert that then. Thanks Manuela for the info.

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this then, please do let us know if you have other questions in the future.

**Comment by S0URCEC0D3** [comment]
Thank you.
