### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Add-on AI builder Actual Consumption column is empty

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#6574]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In CoE, Environment Add ons table , there a column called Actual consumption, which is always empty
![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/841d3c43-abb4-400b-bcff-e69a0ae4223b)

we want to know if we can fetch this information in CoE  Tables so that we can use it for report

If yes could you please let me know what are we missing here or anything we need to configure ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin-Sync V3 Template 

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately this data is not gathered today so we do not have it to add here. Marking as a documentation bug for our limitations page.
