### ISSUE TITLE
CoE Starter Kit Power Platform environment type 

### ISSUE THREAD

**Issue by GithMen** [microsoft/coe-starter-kit#6575]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,
Is it possible to install CoE starter kit on a  sandbox environment ? is it necessary that the environment must be production ?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

Setup power platform environment type 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
