### ISSUE TITLE
[CoE Starter Kit - BUG] Add "Inventory Me" concept for Flow Action Details

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#6576]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Need to be able to ask for individual flows to get their flow action details.
This due to the high API calls required to gather these, its prohibitively expensive to run for a whole tenant for most people.

### Expected Behavior

Similar to how we have for apps/flows. Allow admins to flag a flow to get its flow action details inventoried

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.15

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9cbe0a35-397c-40ee-84a4-fda4d9fdc64a)

**Comment by JohnMHearn** [comment]
It is stated above that this will work similar to how apps/flows 'inventory me' feature works... so, if I understand correctly, this will result in all recently modified flows' action details to be inventoried + those that are flagged Yes by this new feature?  The 'flow action details' flow is already too API hungry, this will increase that, not limit it, right?  I think it would be more useful if instead, we could simply identify the flows we want inventoried for action details and not have it run for all the recently modified flows too.
