### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL dataflow error "We found extra characters at the end of the JSON input"

### ISSUE THREAD

**Issue by bilodeauju** [microsoft/coe-starter-kit#6577]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The dataflow refresh had been working since setting it up earlier this month, then it started failing on September 9th-10th.

The CoE BYODL Makers dataflow is failing with error : 
Error Code: Mashup Exception Data Format Error, Error Details: Couldn't refresh the entity because of an issue with the mashup document MashupException.Error: DataFormat.Error: We found extra characters at the end of the JSON input. Details: Value = ,;Position = 174813 (Request ID: 2a82c017-d2f6-4ef6-82be-db9d0fc297b5).

The Power BI dataflow refresh is also failing with the same error on the Apps table : "
Error: DataFormat.Error: We found extra characters at the end of the JSON input. Value = <ccon> </ccon> Position = <ccon>174813</ccon>. RootActivityId = f97310c8-495f-4693-ab12-901d43dbba17.Param1 = DataFormat.Error: We found extra characters at the end of the JSON input. Value = <ccon> </ccon> Position = <ccon>174813</ccon> Request ID: 90a316b3-d57c-4058-8862-e2c6fcd08ccc.

Please see screenshots below, I'm hoping to get some guidance on how to resolve this error. 

BYODL CoE environment dataflow error screenshots:

![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/80760811-d660-4bb3-9360-c78e41d890ec)
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/767064d9-137a-45a7-a4bd-aa9d2b9d12e8)
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/212ddc51-83cd-4e6f-be1f-046c5c25409a)

Power BI Dataflow error screenshots: 

![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/ed22f48b-f8e6-4bd1-85e3-c97eef8fd993)
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/800201d9-7073-4ab7-bf0a-509272f1ad5d)

### Expected Behavior

Dataflow refresh should complete succesfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

CoE BYODL Makers dataflow

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Manually trigger an on demand refresh.

**Comment by manuelap-msft** [comment]
Hello,

we don't repo this on our side, but it's something to do with the JSON transformation we're doing in the dataflow. 

As we don't repo this, I have a few questions that will hopefully help me narrow this done. 

Are you please able to:

1. Edit the Power BI Dataflow
2. Select the Apps table
3. Select the "Get content" step under Applied Steps
4. In this view, do you see a specific environment that shows as Error instead of showing List in the invoked custom function view
    ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/ca7000a1-9b1a-4aa9-afe0-21c43f4d983b)

Or if there's any other steps you can think of that could help us narrow down the specific JSON file that's causing the issue, that would be great.

**Comment by bilodeauju** [comment]
Hello Manuela, thank you for looking into this. I did find 3 rows with error under the "Invoked custom function" column in the Power BI Dataflow Apps table. 

![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/75295219-fdc8-4152-b3f0-5b41dc55190f)

4400eb13-2480-48d8-907a-f0fdae39dfb1 is our default environment, 5b0d7fd7-60cb-4373-a165-d4d124027f9c is our second most used environment and 5e0ccb4d-d286-4e38-970d-eb746b310c57 is a test sandbox.

I noticed these environments were listed twice in this table, so I went ahead and tried adding a step to remove the rows with errors, saved the changes and then tried to refresh the dataflow again and the refresh completed succesfully.

![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/1143e235-7903-4f1d-a66f-060a264fff15)

I found the same 3 environment rows with errors in the App Makers table in the CoE BYODL Makers dataflow, added a step to remove the rows with error, republished the dataflow and refreshed and the refresh succeeded as well. 

I may have jumped the gun removing these rows with errors and can undo these changes for further testing if needed. What would you advise for next steps? Thank you again for your help.

**Comment by manuelap-msft** [comment]
Hello,

through Data Export, for applications you get two files per environment - one for canvas apps, and one for model driven apps. So that's why you see each environment listed twice. I think by removing the error rows, that means that the inventory in that file won't be processed so that will lead to incorrect reporting (e.g. if the canvas file for the Default environment is causing an error, and you filter it out, that will mean you won't see canvas apps for the Default environment in your reporting).

But it does feel like we're getting closer to the issue - another customer also had the same issue with the Default and their most used environment. Something there is causing our data transformation to fail! 

Could you

1. Go to portal.azure.com > your Storage Account where the Data Export files are landing
2. Navigate to powerplatform/powerapps/Applications
3. Search for Default- 
4. You should have two files there, one that ends with canvas.json and one with model.json. I suspect it's the canvas.json that is the issue as usually people have more canvas apps in the Default environment
5. Can you open that file and scroll to the bottom - does it end with a closing curly bracket } or are there any special characters at the end of it? 

If you feel comfortable sharing the file that's causing the issue with me, you can send it to mapichle@microsoft.com and I can do the debugging from there as well. If not, we can continue to triage it together here on GitHub - there's like something in the file that causes our data transformation in the dataflow to fail.

**Comment by manuelap-msft** [comment]
Actually, I _think_ I got it. 

Can you try
1. Edit the Power BI dataflow
2. Navigate to App helper > Helper queries folder (at the very top)
3. Open the Transform file function  
   ![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/661d640f-8907-471f-a139-c088dc49da31)
4. Select Advanced Editor 
5. Replace everything you see there with the code below:


let
    Source = (Parameter as binary) => let
    Source = Table.FromColumns({Lines.FromBinary(Parameter)}),
    #"Transformed Column" = Table.TransformColumns(Source, {"Column1", Json.Document}),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Transformed Column", "Column1", {"resourceId", "environmentId", "type", "subType", "DocumentVersion", "name", "description", "uri", "tenantId", "lifecycleState", "owner", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "lastEnabledTime", "lastEnabledPrincipalId", "sharedUsers", "sharedGroups", "appPlanClassification", "bypassConsent", "canConsumeAppPass", "sharepointFormURL", "status", "almMode", "usesDataverseTables", "dlpEvaluationStatus"}, {"resourceId", "environmentId", "type", "subType", "DocumentVersion", "name", "description", "uri", "tenantId", "lifecycleState", "owner", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "lastEnabledTime", "lastEnabledPrincipalId", "sharedUsers", "sharedGroups", "appPlanClassification", "bypassConsent", "canConsumeAppPass", "sharepointFormURL", "status", "almMode", "usesDataverseTables", "dlpEvaluationStatus"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1", {{"resourceId", type text}, {"environmentId", type text}, {"type", type text}, {"subType", type text}, {"DocumentVersion", type any}, {"name", type text}, {"description", type text}, {"uri", type text}, {"tenantId", type text}, {"lifecycleState", type text}, {"owner", type text}, {"createdTime", type datetime}, {"createdPrincipalId", type text}, {"lastModifiedTime", type datetime}, {"lastModifiedPrincipalId", type text}, {"lastEnabledTime", type datetime}, {"lastEnabledPrincipalId", type text}, {"sharedUsers", Int64.Type}, {"sharedGroups", Int64.Type}, {"appPlanClassification", type text}, {"bypassConsent", type text}, {"canConsumeAppPass", type any}, {"sharepointFormURL", type any}, {"status", type any}, {"almMode", type any}, {"usesDataverseTables", type any}, {"dlpEvaluationStatus", type any}})
   in
   #"Changed Type"
    in
     Source




It looks like everything is loading okay now on my side but hoping you can help verify that on your end before we upload a new version of the Power BI dataflow!

Thank you for your incredible help testing this with us!

**Comment by bilodeauju** [comment]
Hi Manuela, thank you for your fast replies as well as for your explanation that for applications there are two JSON files per environment for canvas apps and for model driven apps. 

Also, it looks like you indeed got it!! I deleted the step I added yesterday in the Apps table to remove rows with errors and edited the Transform file function in Avanced Editor with your new code. I then went back to look at the Apps table and there were no more errors at the "Get content" step. I saved and refreshed the Power BI dataflow successfully!

Then I went to the CoE BYODL Makers dataflow to try the same, deleted my step to remove rows with errors in the App Makers table, edited the Transform file function that had the same old code with your new code, then checked the "Get content" step again under App Makers table and the errors were also gone. Published and the CoE BYODL Makers dataflow refresh was also successful! 

Let me know if you would still like a copy of the JSON file or if there's anything else I can help testing :)

**Comment by Mmace123** [comment]
Hi.

This issue appears to affect the Power Platform CoE BYODL Dataflows as well. As they show the same failure when refreshing.

Will this solution work with that too?

Thanks.

**Comment by manuelap-msft** [comment]
@Mmace123 This issue affects the Power BI dataflow as well as the Power Platform CoE BYODL Apps and Maker dataflows. The same solution should work for all of them, yes. We are just testing this on our side and aiming to include the fix in the October release, but you can test it yourself with the above Power Query too.

**Comment by manuelap-msft** [comment]
The reason for this bug is that new properties have been made available in Data Export, and our data transformation wasn't robust enough to handle that (there's a new nested JSON attribute that tripped our transformation up). Additional to the bug fix above, we also need to consider how we can consume the new properties for reporting purposes. I'm tracking that via this task:

#6701

This contains a list of all the new attributes if you want to have a look at that yourself too.

**Comment by Mmace123** [comment]
Thanks. Will definitely take a look at that list.

**Comment by pamatihyd** [comment]
@manuelap-msft 
I have also tried to replicate the same steps 
https://github.com/microsoft/coe-starter-kit/issues/6703

![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/af316962-f583-4b4b-ba9f-9fac8adf9e10)
![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/b907f3c5-e3f4-4b40-88ae-c17702e98b20)

we dont have any problem with Apps Flow so only tried to change Makers dataFlow ?

CoE BYODL Makers

Navigate to make.powerapps.com > Dataflows
Edit the CoE BYODL Makers dataflow

Select the Transform files from Query folder > Transform file function (there's multiple functions in that folder, and it's the one without any number behind it)

Select Advanced Editor and paste in the following code
let
Source = (Parameter as binary) => let
Source = Table.FromColumns({Lines.FromBinary(Parameter)}),
#"Transformed Column" = Table.TransformColumns(Source, {"Column1", Json.Document}),
#"Expanded Column1" = Table.ExpandRecordColumn(#"Transformed Column", "Column1", {"resourceId", "environmentId", "type", "subType", "DocumentVersion", "name", "description", "uri", "tenantId", "lifecycleState", "owner", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "lastEnabledTime", "lastEnabledPrincipalId", "sharedUsers", "sharedGroups", "appPlanClassification", "bypassConsent", "canConsumeAppPass", "sharepointFormURL", "status", "almMode", "usesDataverseTables", "dlpEvaluationStatus"}, {"resourceId", "environmentId", "type", "subType", "DocumentVersion", "name", "description", "uri", "tenantId", "lifecycleState", "owner", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "lastEnabledTime", "lastEnabledPrincipalId", "sharedUsers", "sharedGroups", "appPlanClassification", "bypassConsent", "canConsumeAppPass", "sharepointFormURL", "status", "almMode", "usesDataverseTables", "dlpEvaluationStatus"}),
#"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1", {{"resourceId", type text}, {"environmentId", type text}, {"type", type text}, {"subType", type text}, {"DocumentVersion", type any}, {"name", type text}, {"description", type text}, {"uri", type text}, {"tenantId", type text}, {"lifecycleState", type text}, {"owner", type text}, {"createdTime", type datetime}, {"createdPrincipalId", type text}, {"lastModifiedTime", type datetime}, {"lastModifiedPrincipalId", type text}, {"lastEnabledTime", type datetime}, {"lastEnabledPrincipalId", type text}, {"sharedUsers", Int64.Type}, {"sharedGroups", Int64.Type}, {"appPlanClassification", type text}, {"bypassConsent", type text}, {"canConsumeAppPass", type any}, {"sharepointFormURL", type any}, {"status", type any}, {"almMode", type any}, {"usesDataverseTables", type any}, {"dlpEvaluationStatus", type any}})
in
#"Changed Type"
in
Source

Select OK to confirm the changes

Select the App Makers table

Open Advanced Editor and paste in the following code
let
Source = AzureStorage.DataLake(DatalakeURL & "/powerapps/Applications"),
excludehiddenfiles = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
excludezerolengthfiles = Table.SelectRows(excludehiddenfiles, each [Attributes]?[Size]? > 0),
#"Replaced canvas.json" = Table.ReplaceValue(excludezerolengthfiles, "canvas.json", "", Replacer.ReplaceText, {"Name"}),
#"Replaced model.json" = Table.ReplaceValue(#"Replaced canvas.json", "model.json", "", Replacer.ReplaceText, {"Name"}),
#"Lowercased environment name" = Table.TransformColumns(#"Replaced model.json", {{"Name", each Text.Lower(_), type nullable text}}),
#"Merged queries" = Table.NestedJoin(#"Lowercased environment name", {"Name"}, Environments, {"environmentId"}, "Environments", JoinKind.Inner),
Getcontent = Table.AddColumn(#"Merged queries", "Transform file", each #"Transform file"([Content])),
#"Expanded file" = Table.ExpandListColumn(Getcontent, "Transform file"),
#"Expanded createdBy" = Table.ExpandRecordColumn(#"Expanded file", "Transform file", {"createdPrincipalId"}, {"createdBy"}),
#"Removed errors" = Table.RemoveRowsWithErrors(#"Expanded createdBy", {"createdBy"}),
#"Removed columns" = Table.RemoveColumns(#"Removed errors", {"Extension", "Date accessed", "Date modified", "Date created", "Attributes", "Folder Path", "Name", "Content", "Environments"}),
#"Removed duplicates" = Table.Distinct(#"Removed columns", {"createdBy"}),
#"Filtered rows" = Table.SelectRows(#"Removed duplicates", each [createdBy] <> null)
in
#"Filtered rows"

Still I am facing the same issue

Please help
