### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis environment blank

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#6581]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The environment tab is blank:

![image](https://github.com/microsoft/coe-starter-kit/assets/131751950/de40c5f2-5454-4914-9f31-4d305fc148b6)

### Expected Behavior

show correct environment list

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

 DLP Impact Analysis Model Driven App

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by SOMSGH** [comment]
Hi Manuela,

Thanks for reply, indeed I do not see Environments under Power Platform Admin View, will wait until all flows finish running ,thanks!

**Comment by Jenefer-Monroe** [comment]
Hello. Has this been resolved now that you have the inventory?

**Comment by SOMSGH** [comment]
yes, it wroks!!! thanks!
