### ISSUE TITLE
[CoE Starter Kit - BUG] not logged usage of model driven apps 

### ISSUE THREAD

**Issue by amariano72** [microsoft/coe-starter-kit#6582]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Power platform MS Toolkit doesn't log app usage/launch of "model driven" apps. Instead are correctly logged usage/launch of "canvas" apps. Thank you

### Expected Behavior

log app usage/launch of "model driven" apps

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, thats correct, the Model Driven Apps do not write out launches to the source we use for audit logs. Only Canvas apps do so we are not able to provide MDA usage at this point.

**Comment by amariano72** [comment]
Hello.
is available any workaround to have this logging? 
next releases of CoE wil include it?

thank you

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
