### ISSUE TITLE
[CoE Starter Kit - BUG] #6192 ISSUE Audit Log Subscription Flow fails on start - can't read secret

### ISSUE THREAD

**Issue by sukhiwrring** [microsoft/coe-starter-kit#6583]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am facing same issue, the solution didnt work for me as stated in [CoE Starter Kit - BUG] #6192

While trying to run the Admin | Audit Logs | Office 365 Management API Subscription flow it fails with error: Error occured while reading secret: Value cannot be null.
Parameter name: input

The secret is clearly NOT NULL. I can see it in the Command Center and in the Default Solution environment variable "current" value.

I am not using Azure Key Vault.

### Expected Behavior

I should be able to run the flow with the "start" parameter successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription flow

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Client: NAVCANADA
Run the Admin | Audit Logs | Office 365 Management API Subscription flow with the "start" parameter.
Flow fails with error 'Error occured while reading secret: Value cannot be null.
Parameter name: input'

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/36275080/d3ca2e47-b9b8-40cb-8ee8-0d033facb2e4)

**Comment by Jenefer-Monroe** [comment]
You are not using Azure Key Vault so this failure is expected and caught. 
Note that flow always shows the first failure even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

**Comment by sukhiwrring** [comment]
Hi Jenefer,
The flow fails at this step:
![image](https://github.com/microsoft/coe-starter-kit/assets/36275080/d1ab436a-6288-4c71-bdca-743104136c26)

**Comment by Jenefer-Monroe** [comment]
Can you please share a larger screenshot so I can see the entire input and output for that failure?
And then also please share the screenshots described above for the common debugging steps.

**Comment by sukhiwrring** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/36275080/cc87d986-c265-437b-b834-7447a1bc4080)

**Comment by Jenefer-Monroe** [comment]
got it thank you. Please now also provide these screenshots

**Comment by sukhiwrring** [comment]
1. App registration
![image](https://github.com/microsoft/coe-starter-kit/assets/36275080/07d7e89c-19fc-4de5-bbef-f7adbdb38417)

2. Env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/36275080/b700b71e-ba88-444f-b7d3-1235b3baffb9)

3. App ID
![image](https://github.com/microsoft/coe-starter-kit/assets/36275080/ead5398b-82b3-4a29-b960-6f16e673cbad)

4. Client Secret

![image](https://github.com/microsoft/coe-starter-kit/assets/36275080/4f8fb2ea-3f48-4554-ad4d-70496af0fec7)

**Comment by Jenefer-Monroe** [comment]
Can you please make sure there are no unmanaged layers on this flow? We did ship before with a bug for GCC in this flow. 

And then it does look like you entered an Azure Secret here, you did not intend to though correct? You are wanting to use the plain text?
I suggest you delete this if so by going to the default envt and deleting this value 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/08a4341d-ee23-4509-92c0-ace83ce7f8ed)

**Comment by Jenefer-Monroe** [comment]
It looks like you added the wrong Authority env var. 
Per [the documentation](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables) it should be as shown here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2f1ab3a4-a085-462d-9cf4-8ec26d5b45a4)

Please update and then turn all the flows for audit logs off and back on to be sure they do not cache the old value

**Comment by sukhiwrring** [comment]
The flow went further and is failing at this step:
![image](https://github.com/microsoft/coe-starter-kit/assets/36275080/4adf31d1-680c-4eb4-83a8-b29a7f2005fe)
![image](https://github.com/microsoft/coe-starter-kit/assets/36275080/5d0e1836-6a7f-4e7d-a798-b17d7b38ec54)

**Comment by sukhiwrring** [comment]
This says tenant Id doesnt exist. I have verified the ID. Here are the error details:{
  "error": {
    "code": "StartSubscription [CorrId=27e3b4f7-dd6a-4fa3-b107-52a97829fdc3][TenantId=6ddf65e7-9232-4a19-bb68-a2dbf5ea5a74,ContentType=Audit.General,ApplicationId=d242d952-a041-4291-88fa-964a4dab88d5,PublisherId=6ddf65e7-9232-4a19-bb68-a2dbf5ea5a74][AppId",
    "message": "242d952-a041-4291-88fa-964a4dab88d5] failed. Exception: Microsoft.Office.Compliance.Audit.DataServiceException: Tenant 6ddf65e7-9232-4a19-bb68-a2dbf5ea5a74 does not exist.\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetSubscriptionTableClientForTenantAsync>d__52.MoveNext() in d:\\dbs\\sh\\nibr\\0906_164315_0\\cmd\\t\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 2113\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetAPISubscriptionAsync>d__22.MoveNext() in d:\\dbs\\sh\\nibr\\0906_164315_0\\cmd\\t\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 549\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.StartController.<StartSubscription>d__0.MoveNext() in d:\\dbs\\sh\\nibr\\0906_164315_0\\cmd\\1m\\sources\\dev\\auditing\\src\\auditapiservice\\apifrontendservicerole\\Controllers\\StartController.cs:line 76"
  }
}

**Comment by Jenefer-Monroe** [comment]
Did you fix the Authority env var as described above and then turn the flow off and back on?

**Comment by Jenefer-Monroe** [comment]
There is also a tenant ID env var, do you have that filled? Please check it as well to be sure its correct and if not, fix it and turn the flow off and back on. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eaddc904-009a-4292-946a-2c099e3b844c)

**Comment by Jenefer-Monroe** [comment]
Great so this issue is resolved then yes? If so I'll go ahead and close.

**Comment by sukhiwrring** [comment]
Yes, this can be closed now. 
Thanks

**Comment by Jenefer-Monroe** [comment]
Great news!
