### ISSUE TITLE
[CoE Starter Kit - QUESTION] Active environments appear as deleted in CoE app

### ISSUE THREAD

**Issue by marialaura-diazpena** [microsoft/coe-starter-kit#6585]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have many environments that are currently in use and active but they are listed under the "Deleted Environments Review" view in the Power Platform Admin View app in our CoE environment. These environments have the 'Environment Deleted" flag set to "Yes" and an Active BPF named "Environment Approval BPF" 
![image](https://github.com/microsoft/coe-starter-kit/assets/63078943/f46c5046-0a4b-434b-8033-ced05ee212a7)

![image](https://github.com/microsoft/coe-starter-kit/assets/63078943/057c3580-5ded-4cb5-972d-16e19f1f6281)

What triggered these environments to be placed under this view? Does it mean that these environments will be deleted? Is there a way to revert it? How can we prevent this from happening again?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud Flow

**Comment by Jenefer-Monroe** [comment]
These two issues are not related I think. 
Environment Deleted just means that the environment has been marked deleted. For cloud flow architecture this is done primarily by the **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** flow. 

I also have an example that shows deleted on 9/9 so I'll walk through how I see it getting marked deleted. Please do the same with one of your ents that you think should not be marked deleted.

**Comment by Jenefer-Monroe** [comment]
Here is the envt which got marked deleted in 9/9
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0b6f9d00-ddc2-4218-9536-2c4a1d1c0795)

So I open the run of that flow from that date
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/06f8a627-e275-4b2d-a3c7-ed75f03a2180)

First I validate that, in my case, the envt is indeed deleted so it should not longer get returned when I query for all envts here, my GUID will not appear in that download.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3f8181db-eddd-4463-8933-2c24124365d9)

Next I look for my envt in the output here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/55cba7e9-e031-46ed-8a61-bc4c2e8a6cf0)

It's the 42nd envt on my list so I go to that iteration and see that since its not found it gets marked deleted
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d81e7021-22ad-4f93-84ca-a1f28e684d7f)

**Comment by marialaura-diazpena** [comment]
Thank you for your throughout explanation, @Jenefer-Monroe!
Do you know what triggered these environments to be placed under this view? Does it mean that these environments will be deleted? Is there a way to revert it? How can we prevent this from happening again?

**Comment by Jenefer-Monroe** [comment]
The flow above is what puts them into the view when behaviong correctly. Its becasuse the envts **_are_** deleted, not that they will be deleted.

It sounds like you have an envt marked deleted on the 9th that isnt actually deleted. It may have been restored or it may be a bug in your configuration. So please take that sample envt through the steps outlined above to see where its at.

**Comment by Jenefer-Monroe** [comment]
Given and envt X which still exists but which is marked deleted, does it show up in the output of this call?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9d4fecc4-4b17-4bc1-9413-5780fa10a70b)

**Comment by marialaura-diazpena** [comment]
No, it does not show up in this output

**Comment by Jenefer-Monroe** [comment]
ok you have some permissions issue at play then. Disabling this flow will not fix things for you. 

Can you please confirm that the identity running the flow has the PPAdmin Role permanently assigned (not PIM) and directly assigned (not through RBAS)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f01a14f7-afd4-435c-bde2-14501445ddd9)

**Comment by marialaura-diazpena** [comment]
The service account did lose the permanent Power Platform Admin role at some point, and we got the role re-instated 1 or 2 days ago. We suspect that's why the number of environments under the Deleted Environments Review view had many environments but now we only see a few, 
However, the service account has the D365 admin role and it should have been able to see most of the environments. Do you know why this wasn't the case? 

Thank you!

**Comment by Jenefer-Monroe** [comment]
No I'm not sure. I've been told those shoudl be equivalent but there were some chagnes around dynamic access that may have disrupted that. I'll change the documentation to specify the PP Admin Role explicitly.

**Comment by marialaura-diazpena** [comment]
Thank you very much!
