### ISSUE TITLE
[CoE Starter Kit - BUG] upgrade failure

### ISSUE THREAD

**Issue by wramey82** [microsoft/coe-starter-kit#6589]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am having issues with installing the [Center of Excellence - Core Components] 4.15 - Last month after the upgrade to 4.13 even though it shows that it was successful it never removed the previous version 4.11.  Now it will not allow me to install the latest's version 4.15   
![image](https://github.com/microsoft/coe-starter-kit/assets/1717478/9e640ae0-d628-4c1a-b43b-9cd8282679b9)
 
![image](https://github.com/microsoft/coe-starter-kit/assets/1717478/ed9a1b29-a37f-4344-9f51-1dbb2dacf1ff)

![image](https://github.com/microsoft/coe-starter-kit/assets/1717478/0f3e1b41-3036-4fb3-adb1-d6eb6472c816)

Error code
[80048539](http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=80048539&de=online)
Exception message
Solution manifest import: FAILURE: Holding solution CenterofExcellenceCoreComponents_Upgrade already exists.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

None

**Comment by wramey82** [comment]
Fails to Delete the Upgrade:

Solution dependencies exist, cannot uninstall. DependencyCount : 2 RequiredComponentObject details: Type: SavedQuery, ObjectName: Administration Mode, Id: 58c18072-041c-ee11-8f6e-0022480819d7, ParentObjectName: Environment, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: 22bd1684-ab98-ec11-b400-0022482f32f1, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: SavedQuery, ObjectName: Disabled Background Operations, Id: b71f64a8-041c-ee11-8f6e-0022480819d7, ParentObjectName: Environment, ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: admin_PowerPlatformAdminView, Id: 22bd1684-ab98-ec11-b400-0022482f32f1, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

![image](https://github.com/microsoft/coe-starter-kit/assets/1717478/aa75239a-56ac-4cbf-a683-5f2d16a63b30)

Is there another way to Remove the upgrade, or to remove the dependencies? 

![image](https://github.com/microsoft/coe-starter-kit/assets/1717478/52674d92-38c3-41a0-add4-afaee28cbbbb)

**Comment by Jenefer-Monroe** [comment]
It looks like you have some custom dependencies from work local to your tenant in that Model Driven App listed.
