### ISSUE TITLE
[CoE Starter Kit - QUESTION] How do people setup and manange CoE upgrade deployments across Dev-Test-Prod with the solution being managed?

### ISSUE THREAD

**Issue by rpulcino** [microsoft/coe-starter-kit#6590]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

ALM with CoE as a Managed solution - How do people setup and manange CoE upgrade deployments across Dev-Test-Prod with the solution being managed?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

August 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Do you mean specifically with the ALM Accellertor tooling?

**Comment by rpulcino** [comment]
No - sorry! I mean for the CoE Starter Kit it seems necessary to have a way to manage customizations (unmanaged layers) eventually for the tool to work well for us. This would seem to require an ALM deployment approach like we do with our custom solutions across Dev-Test-Prod environments.
Is there a way folks are managing CoE in this way? Does that clarify?
Thank you!!

Roarke
(720) 757-3626

**Comment by Jenefer-Monroe** [comment]
Got it, thank you. 
Here is our write up for that, will leave open to see if others in the community have other thoughts to share
[Extend and customize CoE Starter Kit components](https://learn.microsoft.com/power-platform/guidance/coe/modify-components)

**Comment by rpulcino** [comment]
This is perfect - thank you!

Roarke
(720) 757-3626

**Comment by Jenefer-Monroe** [comment]
Wonderful! I'll go ahead and close then but please do let us know if you have other questions in the future.
