### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by js9331** [microsoft/coe-starter-kit#6591]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What flow syncs the Connections and Actions data for flows? (I'm on Sept 2023 version and not seeing SharePoint sites or Dataverse tables populated - want to go see if I've got permissions problems or something...)
![image](https://github.com/microsoft/coe-starter-kit/assets/35241782/0b11e396-175a-4e57-9435-dbb21ecc196f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2023

### What app or flow are you having the issue with?

that's what my question is 😀

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
In preparing to answer here I did notice that Referenced Recourses property of flows only shows for legacy CDS and not modern. Posted https://github.com/microsoft/coe-starter-kit/issues/6641 to see if we can follow up and get that added. If not will have to change the text here to make that explicit.

This is filled by the **_SYNC HELPER - Cloud Flows_** flow and as such will only fill over time as objects get inventoried. 
You can go and look for all flows with SP / Legacy Dataverse connector and mark them as "Inventory Me"

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
