### ISSUE TITLE
[CoE Starter Kit - QUESTION] Will the CoPilot for Admin be in the CoE or in the main app?

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#6596]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Will the CoPilot for Admin be in the CoE or in the main app (mainly because it may need license\token capacity credits etc.) ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

unknown

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
So far, the Copilot features are only planned for the product - the Power Platform Admin Center - and will have no impact on the CoE kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
