### ISSUE TITLE
[ALM Accelerator - QUESTION] Share Canvas App to Everyone

### ISSUE THREAD

**Issue by dspencelink** [microsoft/coe-starter-kit#6598]
### What is your question?

As it stands today, if we want to share a canvas app with Everyone, we can share to Everyone directly from the app.  Unfortunately, in ALM Accelerator, in the Deployment Settings, the option to share to everyone isn't available, even searching for the Everyone group.  Is there a way to share to Everyone in the ALM Accelerator deployment settings?  Thanks.  Pic below for referenced area:

![image](https://github.com/microsoft/coe-starter-kit/assets/133893716/45f449f6-0ad6-4e37-ba8b-26d5959b0da4)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230802.1

**Comment by mikefactorial** [comment]
@dspencelink recommend creating a dynamics user group in AAD to meet this requirement. https://learn.microsoft.com/en-us/azure/active-directory/external-identities/use-dynamic-groups

**Comment by dspencelink** [comment]
That works but adds to the group sprawl in the environment as opposed to a readily-available group.  If that's the only option, I guess it's what I'll use but was hoping to avoid more groups.
