### ISSUE TITLE
[CoE Starter Kit - QUESTION] "Power Platform User Roles" table do not show the data in the columns 

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#6602]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!
We had the question about the "Power Platform User Roles" table that we have in our environment. We checked this table, and we see that it contains such columns as "Resource Type", "Flow", "App", "Role Name", etc.
The problem is that we see that the "Flow" column is completely empty, but the "App" column 99% filled with the data, but still some fields are missing. Am I understanding that right, that there are some flows that updates data in this table? If yes, could we ask what are the names of the flows? As I tried to find them by myself but seems that all the flows that are needed are turned on, that is why I am confused why the column do not contain the data. 

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. This table is intended to store data about the users and their roles for both apps and flows. However the work to store flows has not yet been done. Its on our near term backlog awaiting one more product change before we can proceed.

As a result right now you shoudl see apps in here and that is filled primarily by this flow and its dependencies: CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

**Comment by JanetK12** [comment]
Thank you for your answer @Jenefer-Monroe !
Could we ask if that is ok - do you perhaps know what is the approximate time when it will be implemented? Just approximately when will it be available in the new update for the installation.

**Comment by Jenefer-Monroe** [comment]
I'm not sure, we hope to do it in the next several months, hopefully by end of calendar year, but we are dependent on a product change before we can proceed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
