### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE CoE Setup and Upgrade Wizard fails to run - need to allow ARM in data policy for CoE Envt

### ISSUE THREAD

**Issue by sukhiwrring** [microsoft/coe-starter-kit#6605]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to initialize the Setup and Upgrade Wizard. Receiving the following error:

Error Code: AppForbidden
Session Id: a057c741-836d-4bdd-93a3-3b24b5490439
Activity Id: 7859367b-3400-494a-acf1-a26b64806d12
Timestamp: Thu Sep 14 2023 10:34:52 GMT-0400 (Eastern Daylight Time)
{"error":{"code":"ApiPolicyViolated","message":"It looks like this app isn't compliant with the latest data loss prevention policies.","details":[{"code":"BlockedConnector","message":"Policy name: MPP-Admin (CoE)\r\nConnector: shared_arm cannot be used since it is blocked by your company's admin.\r\n"}]}}
UciError: {"error":{"code":"ApiPolicyViolated","message":"It looks like this app isn't compliant with the latest data loss prevention policies.","details":[{"code":"BlockedConnector","message":"Policy name: MPP-Admin (CoE)\r\nConnector: shared_arm cannot be used since it is blocked by your company's admin.\r\n"}]}} at s (https://content.powerapps.com/resource/uci-infra/scripts/app.50ea41bba95087f887e5e62343371f81.js:33:903705) at https://content.powerapps.com/resource/uci-infra/scripts/custompage.214fa508cc7e8eb73cc19500c4f815e5.js:4:25770

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

In the CoE environment, open the Center of Excellence - Core Components, run app CoE Setup and Upgrade Wizard

### Anything else?

NA

**Comment by Jenefer-Monroe** [comment]
Hello, thats is correct, this connector was added to the app and so you will need to update the data policy for the CoE envt to allow it.

**Comment by Jenefer-Monroe** [comment]
No its this one. Sorry about this not being documented yet, the update is still in review.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4fa627a1-cc97-4c14-8f2a-c0c459e325ce)

**Comment by sukhiwrring** [comment]
Added this to DLP policy business, still see the error. Do I need to refresh something? I did publish all customizations

**Comment by sukhiwrring** [comment]
We are commercial client. Does this apply to us?

**Comment by Jenefer-Monroe** [comment]
Nope sorry must have confused your user name with another person.

**Comment by sukhiwrring** [comment]
How do I resolve it?

**Comment by Jenefer-Monroe** [comment]
You need to add that connector to all DLP policies taht impact your envt.
You must be missing some if you still arent seeing it working. PErhaps there is an "all environments" policy thats touching the envt

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
