### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE Data source error: The 'admin_userprinciplenamewithoutspecialchars' column does not exist in the rowset.

### ISSUE THREAD

**Issue by sukhiwrring** [microsoft/coe-starter-kit#6606]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Upgrade version: 4.15

Data source error: The 'admin_userprinciplenamewithoutspecialchars' column does not exist in the rowset.
Cluster URI: WABI-CANADA-CENTRAL-redirect.analysis.windows.net
Activity ID: 31b0387f-2260-45ba-85f0-94b8958d12e5
Request ID: 24ff6edf-bdfc-49b8-99e8-00884fbfcb49
Time: 2023-09-14 14:19:15Z

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Production_CoEDashboard_September2023.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Production_CoEDashboard_September2023.pbit

**Comment by Jenefer-Monroe** [comment]
Hello I remember having a field like that in the past but it was removed a while ago and the PBIT files were updated to no longer reference it. 

Can you please be sure that you started with the PBIT from the download folder? 
And can you tell me what table its complaining about htat for?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
