### ISSUE TITLE
[CoE Starter Kit - BUG] Error loading control when boot Setup Wizard

### ISSUE THREAD

**Issue by FCB-AG** [microsoft/coe-starter-kit#6609]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

COE Setup Wizard shows connection errors and error loading control warnings.
![Capture](https://github.com/microsoft/coe-starter-kit/assets/138033727/536e803e-e342-47b2-843d-da7edc331fc6)

### Expected Behavior

completed install of COE starter kit

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CreatorKitCore_1.0.20230118.1

### What app or flow are you having the issue with?

COE Starter Kit

### What method are you using to get inventory and telemetry?

None

### Anything else?

![Capture](https://github.com/microsoft/coe-starter-kit/assets/138033727/b2c2c4a2-c70b-4d53-a125-f1589a11c0f2)

**Comment by Jenefer-Monroe** [comment]
Can you please go see if this flow is on and what it returned when last run? SetupWizard>GetUserDetails

**Comment by FCB-AG** [comment]
Hello Jenifer.   Wwe will check and respond shortly.  Adding Kyla to the email as the PP Administratioor






From: Jenefer Monroe ***@***.***>
Sent: Thursday, September 14, 2023 8:10 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Greenspan, Adam ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6609)
 

NOTICE: External Sender. 
Please exercise caution when opening attachments or clicking links.



Can you please go see if this flow is on and what it returned when last run? SetupWizard>GetUserDetails
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>




This electronic mail and any files transmitted with it are confidential and are intended solely for the use of the individual or entity to whom they are addressed. If you are not the intended recipient or the person responsible for delivering the electronic mail to the intended recipient, be advised that you have received this electronic mail in error and that any use, dissemination, forwarding, printing, or copying of this electronic mail is strictly prohibited. If you have received this electronic mail in error, please immediately notify the sender by return mail. Visit us online at www.firstcitizens.com or call 1-888-FC DIRECT (1-888-323-4732). First Citizens Bank. Forever First®. Member FDIC.
---------------------------------------------------------------------------------------------------

**Comment by FCB-AG** [comment]
Good morning,
   This flow is currently turned on.  It ran as successful when last run.  I've included a screenshot of the flow from when it ran.
Thanks,
Kyla

***@***.***

Kyla Moehring | Vice President
Cloud Services Operations | First Citizens Bank
FCB Mail Code: DAC71 | 100 East Tryon Road | Raleigh, NC 27603

[Logo]

**Comment by Jenefer-Monroe** [comment]
Hello screenshots do not come through when you respond in email you will need to log in to GitHub to share them. 
Please also try out the Setup Wizard again now that you know the flow is on.

**Comment by FCB-AG** [comment]
[ss_getuserresultsflow.docx](https://github.com/microsoft/coe-starter-kit/files/12677125/ss_getuserresultsflow.docx)

screen shot attached

**Comment by Jenefer-Monroe** [comment]
Can you please try out the setup wizard again now that you have the flow turned on?

**Comment by Jenefer-Monroe** [comment]
And if it still does not work please return with what happens inside the scope. You should be seeing something like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d1af579a-57e6-4a4d-9200-28657aaa2599)

**Comment by FCB-AG** [comment]
the loading control errors seems to have resolved itself....  thanks!

**Comment by Jenefer-Monroe** [comment]
thank you for letting us know!
