### ISSUE TITLE
[CoE Starter Kit - BUG]: Error Creating a new DPL Policie using DLP Editor v2 App

### ISSUE THREAD

**Issue by JimmyMoralesH** [microsoft/coe-starter-kit#661]
**Describe the bug**
**_Error Creating a new DPL Policie in DLP Editor v2 App.._**

Error de PowerPlatformforAdmins.CreatePolicyV2: { "error": { "code": "DLPPolicyConnectorReferenceInvalid", "message": "La referencia del conector de la directiva de pérdida de datos no es válida para la solicitud." } }

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: CoreComponents
 - Version 2.1.6
 - App or Flow admin_dlpeditorv2_fcf06_DocumentUri.msapp

**To Reproduce**

**Expected behavior**

**Screenshots**
![CoE - Error Create Policy 1](https://user-images.githubusercontent.com/84737793/122608087-a25b1400-d049-11eb-9d87-f78cfe6ff0dc.png)
![CoE - Error Create Policy 2](https://user-images.githubusercontent.com/84737793/122608089-a4bd6e00-d049-11eb-902e-52c7e652305d.png)

**Comment by manuelap-msft** [comment]
Hello,

could you please share what's the one connector you have in Business, and the one you have in Blocked so I can validate this on my end?

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Hello,

thank you for letting us know! It looks like there may be some unexpected complexities with creating new policies. We are removing this function from the DLP Editor now, and you can create the policies from the Power Platform Admin Center UI and then come to the DLP Editor to edit them. If you create a policy and leave all connectors in the Non-Business group, this will not have an impact on any apps/flows in the environment. Or, you could create the DLP Policy in the PPAC UI with your desired connector grouping and don't add an environment to it - then come to the DLP Editor, add the environments and perform an impact analysis there.

Thank you
Manuela

**Comment by manuelap-msft** [comment]
vnext: removed New Tenant Policy from DLP Editor

**Comment by chrispiasecki** [comment]
> Hello,
> 
> thank you for letting us know! It looks like there may be some unexpected complexities with creating new policies. We are removing this function from the DLP Editor now, and you can create the policies from the Power Platform Admin Center UI and then come to the DLP Editor to edit them. If you create a policy and leave all connectors in the Non-Business group, this will not have an impact on any apps/flows in the environment. Or, you could create the DLP Policy in the PPAC UI with your desired connector grouping and don't add an environment to it - then come to the DLP Editor, add the environments and perform an impact analysis there.
> 
> Thank you
> Manuela

I observed this issue this week as well working with a new client. We performed a workaround where we created a new empty DLP policy in the Admin Center, then used the DLP editor to setup the connectors/scope etc so we could view the impact analysis before applying it.

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
