### ISSUE TITLE
[ALM Accelerator - QUESTION] Error retrieving organization  when opening AA4PP for makers

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#6610]
### What is your question?

Hi,

When i open AA4PP with a user that is into a security group that has the SR ALM Power app access and Basic user , i have this error

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/32b79f54-45a4-4550-a0f1-9597fc1d86f1)

I try to understand what i have missed.

The custom devops connector is shared with the org

<img width="571" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/412ea88f-2c68-41ee-8974-e0083932f9b4">

AA4PP is shared to the AAD security group

<img width="450" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/420ffd73-2962-4a6e-b4ff-90120fabc052">

<img width="838" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/652a8bac-46d5-490d-8879-14aef24b0e5f">

 
![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/e08791c4-cbb8-46d6-be23-6d52b642b37d)

What am i missing ?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

september

**Comment by tocri** [comment]
Ok i think i have found what where the misconfiguration.

In powershell i use this commnd to bypass connectors consent.

**Set-AdminPowerAppApisToBypassConsent -EnvironmentName [Guid] -AppName [Guid]**

So i tried to clear the consent with this command

**Comment by mikefactorial** [comment]
@tocri pardon the delayed response on this. Thank you for reporting it and for following up with the solution. Will certainly help others who may have the same issue in the future. Closing out for now
