### ISSUE TITLE
[CoE Starter Kit - QUESTION]  is there any documentation or use cases we could leveraged as PPAdmins to supply to our other security and platform ops depts for education purposes? 

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#6632]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have noticed after the new license updates that you may assign licenses within the PPAC. IF my org currently does not allow the PPAC to issue licensing (e.g., M365 Admin must go into Azure or M365 to issue), is there any documentation or use cases we could leveraged as PPAdmins to supply to our other security and platform ops depts for education purposes? (looking to RFC the current license process within my org.)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
This question doesn't seem related to the CoE kit. I would recommend you reach out to Microsoft Support through official channels, or post your question in the Power Users community to get some help/input from the wider community.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
