### ISSUE TITLE
[CoE Starter Kit - BUG]: Approval to archive not working

### ISSUE THREAD

**Issue by rajramachandranaa** [microsoft/coe-starter-kit#664]
**Describe the bug**
The approval status to delete or retain the flows and apps are not being updated in the Archive Approval table. This meant that the subsequent clean up flows are unable to delete the flows.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Governance
 - 1.61
 - Admin | Archive and Clean Up v2 (Start Approval for Flows), Admin | Archive and Clean Up v2 (Start Approval for Apps), Admin | Archive and Clean Up v2 (Clean Up and Delete), Admin | Archive and Clean Up v2 (Check Approval)

**To Reproduce**
I followed the steps in the Governance Component setup page.

**Expected behavior**
I was expecting that once the item is approved for deletion, this would reflect in the Approval Response table and then the Check Approval workflow will update the Archive Approval table and finally the Clean Up and Delete flow would delete the flow/app in 3 weeks time

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Please validate that all four of these flows (and the one in yellow in particular for your issue) are turned on and that they have been running successfully.

**Comment by JeneferM-MSFT** [comment]
I have just validated in my test tenant that this is working. So if this is turned on and running, please also validate that you dont have any unmanaged layers on the flow as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by rajramachandranaa** [comment]
Thanks Jenefer for your prompt response. 

They are all On and running. I am also notified when a request to delete a flow or app is approved or rejected. 

I can also see the approval requests in the "Approval" Table in the Dataverse, I can also see data in the Approval Request table and Archive Approval table too. 

It's just that Approval Response table is empty which Check Approval clean up uses. 

Do the users need to have specific permission or a premium license for this workflow to work as expected?

**Comment by JeneferM-MSFT** [comment]
The Archive Approval table is the table that we use, so if you see the responses in there, then its working to copy from product to our extended custom table. 

Can you explain again what issue you are seeing then behaviorally? (as apposed to thinking you should see data here or there in tables)

**Comment by rajramachandranaa** [comment]
Hi Jenefer

The issue/concern is that the Approval Response column in the Archive Approval table is not populated even after these flows have either been approved / rejected.

Is that expected, if so I am happy for this issue to be closed?

![Archive Approval](https://user-images.githubusercontent.com/86220156/122805067-87dea000-d2c0-11eb-857c-e9f9a1aef64d.png)

**Comment by rajramachandranaa** [comment]
Found the issue. The connector needed to be fixed and it is working now
