### ISSUE TITLE
[ALM Accelerator - QUESTION] The deploy pipeline fails at the task "Restructure legacy folders"

### ISSUE THREAD

**Issue by Shishir-Jakhmola** [microsoft/coe-starter-kit#6648]
### What is your question?

In Deployment Profile when changing the Approval Type of Deployment Step to anything other than "Pull Request" the deploy pipeline fails at the task "Restructure legacy folders" with error "Get-ChildItem : Cannot find path 'D:\a\1\s\<ProjectName>\<SolutionName>\S' because it does not exist."

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20230906.1

**Comment by mikefactorial** [comment]
Closing this out as there hasn't been any activity in a while
