### ISSUE TITLE
[CoE Starter Kit - BUG]: "Start Approval for Apps" Flow is not picking up environment variable value as defined in CoE 2.1.7

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#665]
Hello,

We have just deployed the latest CoE Starter Kit with version 2.1.7, that includes governance release (1.61)  as described [here](https://docs.microsoft.com/en-us/power-platform/guidance/coe/release-notes/governance-1.61) that does not mention about the change of Audit flows,  However, when we tested them, flows are not picking up the environment variable values that we have defined, instead it's picking values as follows:

![image](https://user-images.githubusercontent.com/13658386/122720444-7b653380-d23d-11eb-80ca-a2b838e6d019.png)

This is happening for the "ProductionEnvironment" variable as well, while we have set value as "No", it's picking up as true as follows:

![image](https://user-images.githubusercontent.com/13658386/122721335-8a98b100-d23e-11eb-8e8e-120c28928090.png)

I have further checked and noticed that in the Governance version 1.60, Governance flows were working as per the defined variable as Data source variables were not defined there in the Initialization actions as follows:

**Governance components 1.60** ( CoE Starter Kit 2.1.6 )
![image](https://user-images.githubusercontent.com/13658386/122720847-f62e4e80-d23d-11eb-8751-68bea6e6b2c0.png)

**Governance components 1.61**( CoE Starter Kit 2.1.7)
![image](https://user-images.githubusercontent.com/13658386/122720657-c2532900-d23d-11eb-8fbe-00ae4cd71a36.png)

I assume that "Datasource Variable" feature is currently in preview and might be not fully functional during the migration process of solution, however I am not sure exactly - these were the findings we have faced 2 months back.

Could you please share what should we do in order to resolve Audit flows of **Governance components 1.61**( CoE Starter Kit 2.1.7) which are changed than version **Governance components 1.60** ( CoE Starter Kit 2.1.6 )?

![image](https://user-images.githubusercontent.com/13658386/122729994-c126f980-d247-11eb-84fb-770e1991fd30.png)

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
I believe you are saying that your environment variable values for **_Admin eMail_** and **_ProductionEnvironment_** are not correctly populating. 

Please browse to the default solution and filter to environment variables.  
![image](https://user-images.githubusercontent.com/62659043/122765867-2c7bc600-d25e-11eb-8a49-e112bcdd25a4.png)

Open these two environment variables and see what values you have. My test install shows them correctly. Admin Email (for example) has no default value and the current value which I provided on import
![image](https://user-images.githubusercontent.com/62659043/122766123-66e56300-d25e-11eb-849c-93e0864c3d31.png)

If this looks correct you may have hit a known product bug in which solution layers were getting added to environment variables (they should not be). Please browse to solution layers for the env vars, and if unmanaged layers exist, remove them. 
![image](https://user-images.githubusercontent.com/62659043/122766238-88464f00-d25e-11eb-9735-994e5b135294.png)

**Comment by DiptiC-InsightRun** [comment]
Hi Jenefer,

Thank  you for your response!

Yes, that's correct as it's not taking the right value of environment variable after we have performed as follows:

1. Ensure that there is no unmanaged layer in Environment Variables, apps,flows,tables
2. Installed latest CoE Starter Kit 2.1.7 without any error
3. Updated Environment variable "Default" and "Current" values as per our alignment

Next, we have checked, Governance Flows, which is picking up "Admin Email" value as "adelev@pplatform.onmicrosoft.com" while we have updated with different value.

Then I have raised this ticket, and removed unmanaged layer again as you have suggested as it's adding "unmanaged layer" after deployment, however after removing unmanaged layer and updating the environment variable value as ours, it's still picking up value as "adelev@pplatform.onmicrosoft.com" for "Admin Email" variable.

Any other thing that I should be checking?

Looking forward!

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
I'm afraid I dont follow you. Can you please share a picture of
1) The environment variable settings for admin email
2) The solution layers for the environment variable admin email

**Comment by DiptiC-InsightRun** [comment]
Sure,

**Admin Email Solution Layer :**
![image](https://user-images.githubusercontent.com/13658386/122778411-f993fb00-d27a-11eb-9163-7bfe52e1febb.png)

above unmanaged layer was created, after we have updated our own values from the default solution as follows:
![image](https://user-images.githubusercontent.com/13658386/122778707-36f88880-d27b-11eb-997c-49a2e273f656.png)

Hope this is  helpful.

Please let me know if require any further information!

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Yes you just need to remove the unmanaged solution layer shown there on the environment variable.

**Comment by DiptiC-InsightRun** [comment]
If we remove the unmanaged layer, then it will remove our values that we have set for the "Admin Email"

How do we update Environment variable value once we remove unmanaged layer without creating unmanaged layer?

**Comment by JeneferM-MSFT** [comment]
It should not, it does not for me. Note that you dont need to set the Default value. You only want/need to set current values for env variables as upgrade will wipe out your default anyway.

**Comment by DiptiC-InsightRun** [comment]
Hi Jenefer,

As suggested, I have removed unmanaged layer, then updated current values ( This was already done earlier which was failed and that created unmanaged layer by design) and checked if it's picking up updated value, however it does not. It's still picking up value as adelev@pplatform.onmicrosoft.com 

Any suggestions/thoughts? Do you suggest to utilize Governance flows from 1.60 instead of 1.61?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
No you should update the env variables in the default solution. And you can update them later.

**Comment by JeneferM-MSFT** [comment]
I'm afraid what you have hit is a product bug in that the env variables are not reading correctly. You will need to contact support. I have let the product team know internally as well of the repro. 
Thanks for using CoE.

**Comment by DiptiC-InsightRun** [comment]
Thank you Jenefer, 

Just for my clarification, could you please help if this is the bug with CoE Starter Kit, OR this is a bug with Power Platform for environment variables?

Thank you again!

Dipti

**Comment by JeneferM-MSFT** [comment]
From my understanding of the above: You are setting the env variable to your admin email and the product is not picking it up. 

Hence this is a product bug.

**Comment by DiptiC-InsightRun** [comment]
Thank you,

Could you share the timeline when the next release will be available with this fix? OR if we connect Microsoft Support, will they be able to resolve for our environment? Need a help to take a decision further on the upgrade process.

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
I'm afraid we cannot assist with product bugs. You will need to contact support and they will need to be your conduit from here.

**Comment by DiptiC-InsightRun** [comment]
I have tested this concern further and it appear that - because my flow was not a solution aware flow, it was not picking up the latest environment variable value, so if we plan to customize any CoE flows, testing inside the solution is the key.

I hope this could be helpful for anyone facing similar concern.

Thank you Jenefer for your attention and help!
