### ISSUE TITLE
[CoE Starter Kit - QUESTION] Import Solution time to upgrade

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#6653]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I noted on the Microsoft Learn material for upgrading the CoE that it states it can take up to 15 minutes for the upgrade to finish. Typically it takes up to 2 hours for me to upgrade the core solution. I just wanted to check whether that is normal and the Learn content may be a bit out of date or whether there is an issue perhaps with my instance? 

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
We have also noticed recently that the upgrade is taking a lot longer than it used to, in our testing it took about 45-75 minutes to perform an upgrade. We can certainly update our documentation to set the right expectations here!

**Comment by G1982C** [comment]
Thank you. I think that would be helpful to set expectations as I did start to worry there was an issue with my instance. 

One other typo I noticed was under the section 'Remove unmanaged layers from inventory flows', on step 2 it states 'sync flows' when on my app it shows as 'CoE flows'. 

I hope you see this as me trying to be helpful and don't see it as me picking faults with the learn content, as the content is great. For anyone new, it can be slightly confusing trying to find sync flows :-)

Thank you

**Comment by manuelap-msft** [comment]
Great, we can get that fixed as well with the next update! 

Not at all - this feedback is really important for us. We make updates to our docs with the monthly releases, but often it's just in the spots where we made changes and we rarely review the entire documentation to check if it's still up to date so feedback like this really helps us stay on top of things! Thanks for taking the time to provide it - we really appreciate it :)
