### ISSUE TITLE
[CoE Starter Kit - QUESTION] September 2023 Version Number

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#6654]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

We are trying to update the CoE Starter Kit to the latest version (September 2023) but we noticed that the version that we installed last **May 2023 (4.8)** is higher compared to the latest version **September 2023 (4.15)**.

![CoE Starter Kit Issue](https://github.com/microsoft/coe-starter-kit/assets/119695189/a6f6b415-971b-48c2-a278-f5b5d99474ad)

We also noticed this with the Audit Component **May 2023 (3.4)** Vs **September 2023 (3.12)**.

Can you confirm if it's safe to to install the latest version (September 2023)?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
4.15 is higher than 4.8 (15 is higher than 8). The warning message you are seeing only informs you that you already have this solution installed and an update (vs new install) will be performed. Are you seeing an error message when you proceed from here?
