### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Governance Dashboard error Admin_stateorprovince not found

### ISSUE THREAD

**Issue by crowdedLeopard** [microsoft/coe-starter-kit#6655]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

when enabling the PowerBI governance dashboard data load fails with the error admin_stateorprovince not found

### Expected Behavior

power bi dashboard should load data to model without error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Power BI

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Load the powerBI template 
Add the environment URL
error occurs

**Comment by manuelap-msft** [comment]
This is a field we introduced with the latest version of the CoE Starter Kit Core Components solution. You'll have to upgrade the solution in your environment before you can use the latest Power Bi dashboard.
