### ISSUE TITLE
[CoE Starter Kit - BUG] incorrect argument type - dlp impact analysis tool.

### ISSUE THREAD

**Issue by crowdedLeopard** [microsoft/coe-starter-kit#6656]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

when  running an impact analysis tool produces the error - incorrect argument type.

![Screenshot 2023-09-18 150819-edited](https://github.com/microsoft/coe-starter-kit/assets/99030907/cd08c5a1-c51b-4c40-892b-2f92bb279f34)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

DLP - Impact Analysis

### What method are you using to get inventory and telemetry?

None

AB#916

**Comment by manuelap-msft** [comment]
We've noticed this as well, and it seems to be related to the Creator Kit DetailsList component. From what we've seen it does not impact the functionality of the app but we'll look at how to remove the error.
