### ISSUE TITLE
[CoE Starter Kit - QUESTION] Editing the Microsoft Logo on CoE emails

### ISSUE THREAD

**Issue by gidionr** [microsoft/coe-starter-kit#6659]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the COE Admin Command Center you can customize the email body of the CoE email to be sent out. We want to take customization further and want to find out if we can change the Microsoft logo on the email, with the Company's logo.

![image](https://github.com/microsoft/coe-starter-kit/assets/72568527/f2d7e9c7-e8d3-49a6-ab1f-90a52ad2c3cb)

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

**Comment by gidionr** [comment]
Figured this out by customizing admin_eMailBodyStart. You can close this work item and thank you guys for the awesome job you are doing with the CoE Starter Kit. 

![image](https://github.com/microsoft/coe-starter-kit/assets/72568527/5c2de66c-b019-4a54-ba8a-b8b4564b0946)

**Comment by Jenefer-Monroe** [comment]
Thank you for your kind words! Sorry we did not get here in time to help you but looks like you got the perfect answer.
