### ISSUE TITLE
[CoE Starter Kit - BUG] Dashboard not fetching all date

### ISSUE THREAD

**Issue by JawnLegend** [microsoft/coe-starter-kit#6663]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Since upgrading to the august CoE starter kit and publishing the latest dashboard, the dashboard does not seem to fetch any dates beyond the date I updated (aug 23, 2023). I've looked into multiple flows in the CoE Admin Command Center and am not seeing any errors, with all of them running successfully. The dashboard is running a daily scheduled sync. 

### Expected Behavior

Expecting the CoE dashboard to fetch all dates. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

CoE dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Go the the dashboard in PBI
2. Go to App Usage
3. Check date range

### Anything else?

Attached are images of both dashboards (the old and new one) where the dates are only showing data up until august 23.

![billede](https://github.com/microsoft/coe-starter-kit/assets/105429761/a150217b-6037-4b57-8ce2-4929b21cf3cf)

![billede](https://github.com/microsoft/coe-starter-kit/assets/105429761/d7c55662-8148-4977-a9d8-95f67631472a)

**Comment by JawnLegend** [comment]
Hi! Somehow both my flows in the HTTP action were turned off. I redid the process and it functions as intended now. Thanks as always!

**Comment by Jenefer-Monroe** [comment]
oh wonderful news, thanks so much for following up and letting us know.
