### ISSUE TITLE
[CoE Starter Kit - BUG] Incorrect total number of Model Driven Apps

### ISSUE THREAD

**Issue by mspatlin** [microsoft/coe-starter-kit#6664]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When using CoE Dashboard report or Platform Admin View App to check the total# of Model Driven Apps,
many of the model driven apps are there under the environment but just uncounted. We cross checked by using Power Platform Admin Center and also jumping into that environment to see the apps list

Can anyone guide us anything I missed?

Please view the report screenshot here
https://1drv.ms/i/s!Aj5QMOfJ03f9jK9LiZtp_nhkuZ3rQw?e=auBANj 

### Expected Behavior

The total # of MDA is exact the same as it is in Power Platform Admin Center List

### What solution are you experiencing the issue with?

Core

### What solution version are you using?
September 2023

### What app or flow are you having the issue with?
 Power BI Dashboard or Power Platform Admin View 

### What method are you using to get inventory and telemetry?
Cloud flows

### Steps To Reproduce
1. Go to Power BI  Dashboard Report > Monitor > Overview Power App > select the environment > Check the total # of Model Driven Apps
2. Compare that number with the total number of the model driven apps list under the environment in Power Platform Admin Center

### Anything else?
No

**Comment by Jenefer-Monroe** [comment]
Can you confirm, are you saying the number in PBI is incorrect? But the number in the Power Platform Admin view is correct?

**Comment by manuelap-msft** [comment]
For Model Driven apps, there's a known limitation in that unpublished model driven apps show up in the Power Platform Admin Center but not in the CoE kit dashboard. You can find more about expected differences between the different ways to view your Power Platform resources here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/limitations#inventory-and-telemetry-differences-between-powershell-power-platform-admin-center-and-coe-starter-kit

**Comment by mspatlin** [comment]
Hi, Manuela Pichler :

Thank you for the clear reply.

Manuela Pichler ***@***.***> 於 2023年9月20日 週三 下午5:10寫道：

**Comment by Jenefer-Monroe** [comment]
ill go ahead and close then but please do let us know if you have other questions in the future.

**Comment by mspatlin** [comment]
Thanks a lot for Jenefer's prompt reply!

Jenefer Monroe ***@***.***> 於 2023年9月21日 週四 上午3:58寫道：
