### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power BI Report

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#6667]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

How to see what are the Flows and Apps in Microsoft Dataverse (legacy) Connector in Power BI report and who created?

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/e37c1689-5eec-4789-bf8f-d47598961bef)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

August 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I beleieve this is a dupe of https://github.com/microsoft/coe-starter-kit/issues/6469 in that we lost some of the fidelity here when we redid the PBI reports recently. Please do take a look

**Comment by lingutla123** [comment]
Thank You.
