### ISSUE TITLE
[CoE Starter Kit - QUESTION] Co-Owners

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#6669]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team, 

Is there a way to display a list of Co-Owners for Environments, Power Apps, and flows? We would like this data to help us identify true "orphans," In the Power Platform Admin View, it only shows the "owner" or creator of the resources and would like to understand how we could view the information easily. Ex) In the Power Platform Admin View, it shows the creator of the app as the "App Owner" even though there may be Co-Owner. Please advise :) 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We only store this for PowerApps canvas apps today but do have work items to do it for Flow which we hope to fund soon after one more product dependency is complete.

For apps, we display this in the Power Platform Admin View app today as shown here:
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b16cf91c-a82a-493c-bbb3-738b7fcc5374)

And then if you are managing permissions from there you can also choose from the Editors listed. 
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b27cfb88-46c7-4eb6-b7fb-97e922936495)

**Comment by iamjina** [comment]
Thank you Jenefer 👍

**Comment by MrHueb** [comment]
Hi @Jenefer-Monroe  is there already a feature item we are able to track. Thank you! :)
