### ISSUE TITLE
[CoE Starter Kit - BUG]: Office 365 Management API Authentication issue

### ISSUE THREAD

**Issue by chrisan1992** [microsoft/coe-starter-kit#667]
**Describe the bug**
Hi Team,
I'm a Support Engineer from Microsoft and Manuela Pichler requested to have this issue posted here.
When configuring the Office 365 Management API custom connector, were are getting the following error message:

> OAuth2 authorization flow failed for service 'Azure Active Directory'. OAuth 2 sign in failed to exchange code for access token. Client ID and secret sent in form body.. Response status code=Unauthorized. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 7ac11296-04ad-4284-acb5-e596ae1c7301\r\nCorrelation ID: 7de45b6f-d389-43ca-aaf5-f0581097e39f\r\nTimestamp: 2021-06-21 18:04:28Z","error_codes":[7000215],"timestamp":"2021-06-21 18:04:28Z","trace_id":"7ac11296-04ad-4284-acb5-e596ae1c7301","correlation_id":"7de45b6f-d389-43ca-aaf5-f0581097e39f","error_uri":"https://login.windows.net/error?code=7000215"} Client ID and secret sent in Basic authorization header.. Response status code=Unauthorized. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 0945bbcf-25dd-4e53-80df-611992621c01\r\nCorrelation ID: d513c4ea-9eb0-4ad8-9673-6669f82d30ae\r\nTimestamp: 2021-06-21 18:04:28Z","error_codes":[7000215],"timestamp":"2021-06-21 18:04:28Z","trace_id":"0945bbcf-25dd-4e53-80df-611992621c01","correlation_id":"d513c4ea-9eb0-4ad8-9673-6669f82d30ae","error_uri":"https://login.windows.net/error?code=7000215"}

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version 2.1.70
 - Custom connector Office 365 Management API

**To Reproduce**
1. Follow the instructions on the following URL: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components
2. Once you have the client and secret in Azure, setup the security configuration, and when testing and creating a new connection the connector fails indicating this is an issue with the client and secret

**Expected behavior**
Be able to establish a connection with the custom connector

**Screenshots**
![image](https://user-images.githubusercontent.com/4581561/122808405-184dbe00-d28a-11eb-95a6-f5b0218e775c.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

the error message states: AADSTS7000215: Invalid client secret is provided - please verify the admin has given the correct client secret, that there's no copy&paste issue (trailing blank spaces), and that the Azure App Registration has been set up with the correct permissions.

Thank you
Manuela

**Comment by chrisan1992** [comment]
> Hello,
> 
> the error message states: AADSTS7000215: Invalid client secret is provided - please verify the admin has given the correct client secret, that there's no copy&paste issue (trailing blank spaces), and that the Azure App Registration has been set up with the correct permissions.
> 
> Thank you
> Manuela

Hi Manuela,

I have verified this already, this is the exact same error that the customer is getting and I was able to reproduce it. I confirmed there are no white spaces on my end either

**Comment by manuelap-msft** [comment]
Hello,

we see this error when one of the below has happened:
![image](https://user-images.githubusercontent.com/55705669/122895913-74731980-d340-11eb-99bb-178f120f7888.png)

Please go over our setup instructions again:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

As many of our customers are successful in this step, we are confident there is no issue in the CoE kit here.

Manuela
