### ISSUE TITLE
[CoE Starter Kit - BUG] Flow Last Run ON 

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#6670]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, 

I am not able to view the "Flow Last Run ON" column on my Power Platform Admin View. All my Admin | Sync Template flows are turned on, as well as configure Audit Log flow as well. Which flow is retrieving this information? 

Please advise. Thank you. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin - Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
That information is not available for the cloud flow architecture unfortunately. The product team is working on something to make it available but I cannot comment on when it might be avaialble. Currently we can only grab that for the BYODL (Data Export) Architecture.
Please see our [Data Export FAQ](https://learn.microsoft.com/power-platform/guidance/coe/faq-dataexport) for more information

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
