### ISSUE TITLE
[CoE Starter Kit - BUG] Inactivity Setup Wizard does not save the exemption value in Power Platform Admin view

### ISSUE THREAD

**Issue by nickmac88** [microsoft/coe-starter-kit#6671]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Guys, I am still experiencing this issue listed below but the only difference is that this time the value saves in the setup wizard but not on in Power Platform Admin view. My Power Platform COE account is also receiving alerts for inactivity even though i set the COE environment to exempt.

https://github.com/microsoft/coe-starter-kit/issues/5509

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Latest as of August 2023

### What app or flow are you having the issue with?

Setup Wizard

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
I dont repro this, can you please check the environment table to see if the flag got set there? If so we can move to the next place to spot
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7d9a092d-9737-4178-99a4-15f1269d9e2f)

**Comment by nickmac88** [comment]
The dataverse table? I am not seeing this view you have pictured above. Where can i find that? I will say that i had to set it manually in the place pictured below.

![image](https://github.com/microsoft/coe-starter-kit/assets/54548626/d09f49cb-102e-46a6-8d69-82e5273297be)

**Comment by Jenefer-Monroe** [comment]
Correct thats the table itself. You can make any temp view you want there by clicking on More and chosing the fields you want to see
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5636bce3-f1e5-4811-8b34-40595fd89e80)

**Comment by Jenefer-Monroe** [comment]
This issue was fixed so can you please see if you have unmanaged layers on the page ? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e293232f-6c0d-4164-993a-c00507cba093)

**Comment by nickmac88** [comment]
Perfect, thanks. Yes, it is saved there now but i am thinking that is because i manually updated it in the Power Platform Admin View. I say this because the COE svc account was receiving inactivity notifications for apps and flows not being used in the COE environment.

**Comment by Jenefer-Monroe** [comment]
If you open the setup wizard and go back to that wizard, you can test again and check against that. 
Please check for the unmanaged layers as well.

**Comment by nickmac88** [comment]
Yeah, I played around with the setup process and it seems to be working. I can not repo this issue any further. I can set and change values and they change in the table accordingly. Not sure why this happened initially on my 1st run though.

However, now i know that i can check this table to make sure the value is set correctly. Thank you for your help!

**Comment by Jenefer-Monroe** [comment]
Oh wonderful. Thank you for letting us know! I'll go ahead and close this then, please do reach out again if you have other concerns.
