### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by KYT9212** [microsoft/coe-starter-kit#6672]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Upgrading from CoE Core Solution v4.13 to 4.15 and getting below error message. Unable to remove the components mentioned in error. 

![Screenshot 2023-09-19 134628](https://github.com/microsoft/coe-starter-kit/assets/136002212/892907ea-a9e7-4596-b915-d986ddda87b5)

### Expected Behavior

Be able to upgrade without getting the errors 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

CoE Core Solution 

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Import 4.15 using upgrade
2. receive error message 

### Anything else?

Audit solution and related connection has been removed as part of 4.13 upgrade.

**Comment by manuelap-msft** [comment]
Hello,

the highlighted issue calls out a dependency between an environment variable called admin_excludedefault and the Admin | compliance detail request v3 flow.

We don't have an environment variable called admin_excludedefault, so there's two reasons for this issue

1. I'm not sure if we ever had an environment variable like that, it's possible that we deprecated it - you may have unmanaged layers on the Admin | compliance detail request v3 flow that stopped you from receiving updates. If that's the case, you will have to remove the unmanaged layer to ensure this flow can receive the latest version. Here's how to exempt the default and other environments from the compliance process: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#exempt-environments-from-the-compliance-process
2. It's possible this is an environment variable you introduced yourself. If that's the case, you have to make sure to maintain the environment variable and flow yourself in a separate solution so it doesn't interfere with upgrades.

**Comment by KYT9212** [comment]
Hello,

Thank you for the quick response. Environment variable "Exclude Default environment from Compliance Request flows" seems to have been deprecated (please see below). I was able to confirm there isn't any unmanaged layer on Admin | Compliance detail request v3 and we have it turned off. Any other suggestions? 

![image](https://github.com/microsoft/coe-starter-kit/assets/136002212/e221249a-d81b-4c1c-ac3f-3527e58189c6)
![image](https://github.com/microsoft/coe-starter-kit/assets/136002212/f1fe4728-0b8a-4232-9619-914ea7eb04ba)

**Comment by Jenefer-Monroe** [comment]
Sometimes if a flow is unpublished / renamed / etc, our trick for finding layers that we use here doesnt work. We've just recently discovered this. 
Can you go to the flow directly and check for solution layers? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0833cc26-31de-42a4-b93e-e51ae62d628b)

**Comment by KYT9212** [comment]
Thank you for the response Jenefer. There was an unmanaged layer I wasn't aware of. After removing upgrade ran as expected.

**Comment by Jenefer-Monroe** [comment]
oh wonderful news! Thanks for letting us know!
