### ISSUE TITLE
[CoE Starter Kit - BUG] Command Center Bookmarks page still missing descriptions for MDAs after upgrade

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#6673]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This was meant to be fixed after bug #6326  however, after upgrading to September release, I am still not seeing descriptions for some apps.
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/134c6980-5f0c-449f-bf3b-945c8c984bf4)

I have run the metadata flow Admin | Sync Template v3 CoE Solution Metadata and also the inventory for the environments has run.
I also checked and the Initially Populate Bookmarks flow has run.
The following have no description:
CoE Theme Editor
CoE Theme Gallery
Developer Compliance Center
DLP Impact Analysis
Innovation Backlog
Innovation Backlog Admin
Maker Assessment
Video hub - Admin

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September Release v4.15

### What app or flow are you having the issue with?

Admin - Command Centre

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I dont repro this so not sure what is going on. 
Do you have an unmanged layer on this page by chance? Cant remember if I asked you that in the other issue.

**Comment by medicineshow** [comment]
No
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/2b468356-f7c7-44da-8432-09ef063e60b6)

**Comment by Jenefer-Monroe** [comment]
Can you please check again today? We've noticed there seems to be some delay in upgrades applying to components.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
