### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to Manage Flows with Admin - Access This Flow Embedded App

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#6674]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Anytime I drill down in to a flow from the Power BI dashboard i get the error message "Cannot update or delete flows in a solution here.
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/94d5d97d-da50-4957-90ab-e5d0aa4917d1)

My account is a Power Platform Administrator.

It does allow access to a flow in the Default Environment. Admin - Access this App does not have the same issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2023 (Version 4.15)

### What app or flow are you having the issue with?

Admin - Access this Flow [works embedded in Power BI only]

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Is it a flow that is in a solution? If so, then this is unfortunately expected. We are still blocked from doing this until we do an uncoming feature which is blocked by one more product change.

**Comment by medicineshow** [comment]
Yes they are in solutions. This did used to work though didn't it? When is the change expected?

**Comment by Jenefer-Monroe** [comment]
I dont think it ever worked in the PBI, no. We can change owner if you use the PPAdmin View technique. 


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f0dbd86d-4f8c-4354-9288-7380d686c623)



I cant comment on timeline unfortunately as we are blocked by one more product change.

**Comment by medicineshow** [comment]
Thanks for reminding me of that one.  I have noticed that some flows show the owner in the Manage Permissions window, yet the Maker and Derived Owner field are both empty. Should I raise this as an issue or is there a known reason for this?

**Comment by Jenefer-Monroe** [comment]
I think we may already have a few posted that we are iterating
Can you look at these two? And see if you get blank creator returned when you run the flow mentioned?
https://github.com/microsoft/coe-starter-kit/issues/6677
https://github.com/microsoft/coe-starter-kit/issues/6665

**Comment by Jenefer-Monroe** [comment]
That issue with the fields was likely a product regression that is getting rolled back now.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team

**Comment by kartrabby** [comment]
@Jenefer-Monroe : Just wondering any ideas when we can manage the Solution Aware Cloud flows via CoE Toolkit to assign owners, Coe-owners, viewers or remove the Users/Groups
