### ISSUE TITLE
[CoE Starter Kit - Feature]: Maker Power Platform Request count

### ISSUE THREAD

**Issue by morismm99** [microsoft/coe-starter-kit#6675]
### Is your feature request related to a problem? Please describe.

No, just a feature request for pulling in Power Platform requests into the CoE Admin Dashboard report.

### Describe the solution you'd like

In PPAC we can now manually download a Power Platform Requests report in csv format - https://learn.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#view-detailed-power-platform-request-usage-information-in-the-power-platform-admin-center-preview. 

It would be great if we could grab this information via the CoE Kit once a week, in order to show the total number of requests for makers.

### Describe alternatives you've considered

Creating a new table to manually ingest this Power Platform Request report and creating a relationship between this new table and the makers table, then tweak the Power Bi report to show total number of requests for a user and monthly filter.

**Comment by Jenefer-Monroe** [comment]
I dont think this information is available to us programatically. Are you aware of a programmatic access point? Will leave open to see if others have ideas.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
