### ISSUE TITLE
[CoE Starter Kit - BUG] Plan 2 License and Setup Wizard

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#6678]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We were in a process of upgrading the CoE to the latest version. During the deployment, we got an error in our Setup Wizard regarding unmeet licensing requirement. Currently, we have a Plan 2, which is a legacy sku but a Premium licensing; however, the CoE is not recognizing Plan 2 as Premium, rather the system is saying it's not compliant (need the Power Apps and Power Automate Premium). 

The question is does the CoE accept Plan 2 as Premium and is able to run all the CoE apps and flows? Or would the legacy sku not work for CoE? Please advise :) 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin - Sync Template v3 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

The CoE kit on the pre-req screen only checks for currently available license SKUs and not legacy ones. If you have a legacy SKU, you'll have to check yourself if that meets the requirements to use the CoE kit (which is: run standalone apps, run standalone cloud flows). The pre-req screen is not blocking and if the license check fails, you are still able to continue here. 

Manuela
