### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log + Core Component Upgrade

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#6679]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team, 

Due to the deprecation of the Audit Log solution, we were upgrading the CoE to the August version. We've followed the instructions, where we have deleted the Audit Log solution, and removed the Office 365 audit log connection references as well. 
![image](https://github.com/microsoft/coe-starter-kit/assets/100535041/70c9578f-d026-4dc3-b97c-ada25357abf1)

However, under the Default Solution, we could not remove the Office 365 Management API Custom Connectors, and cannot uninstall the Core Components due to the Custom Connector. 
![image](https://github.com/microsoft/coe-starter-kit/assets/100535041/87f44ddb-f5a5-4f85-90d4-662582b0135c)
![image](https://github.com/microsoft/coe-starter-kit/assets/100535041/381cd7e8-3f71-4a21-9e6a-21bca752ca93)

Even though the upgrade went through, it gave us an error _(Solution Upgrade action failed after import as holding. Solution dependencies exist, cannot uninstall. DepedencyCount: 1 RequireComponentObject details: Type: connector, ObjectName: Office 365 Management API)_  and the CenterofExcellenceCoreComponents_Upgrade (version 4.13) would not go away and still have the CenterofExcellenceCoreComponents(version 4.9) in the system. 
![image](https://github.com/microsoft/coe-starter-kit/assets/100535041/19330162-21f5-4657-8b27-63228224d846)

Does this mean that the upgrade was successful? If so, why do we have 2 Core Components (version 4.13 and 4.9) listed under the Solution and is this a known bug or would the Core Components be merged together? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Audit Log Components 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

no, that means the upgrade was not successful. The reason you're seeing two solutions is because the initial import of the new solution succeeded but then the upgrade over the old solution could not be applied.

It's likely this happened because you have unmanaged layers on the custom connector - can you go to the Default solution and check the dependencies and unmanaged layers of the Office 365 Management API custom connector?

Manuela

**Comment by iamjina** [comment]
This worked! Thank you 👍
