### ISSUE TITLE
[CoE Starter Kit - QUESTION]  Older Center of Excellence Starter Kit versions. Calls to the deprecated List flows as Admin action.

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#6681]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

we have noticed a potential update or roll out from Microsoft for few connectors in Power Automate .

This roll out has significant impact on below points

- Older Center of Excellence Starter Kit versions.
- Calls to the deprecated List flows as Admin action.

we have June Version of CoE Starter Kit installed in our Production, 

Could you please let us know if this have any impact on our CoE tool kit ?

If yes, , what are the measures we have to take to handle this from CoE Perspective

Attached is the screenshot,
[image](https://github.com/microsoft/coe-starter-kit/assets/29652263/806d4a19-fc19-4a22-9129-2fe166f8b3c8)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

the May 2023 version of the CoE kit has been updated to use the new List Flows as Admin v2 action, and all versions after May (June, July, August, September) are only using the new List Flows as Admin v2 action and no longer use the deprecated version. Older versions of the CoE kit will stop working once the old List Flows as Admin action is fully deprecated. The measures you have to take is to upgrade your CoE kit version to a later version, if you're on a version from before May 2023.

Thank you
Manuela

**Comment by pamatihyd** [comment]
Thank you
