### ISSUE TITLE
[CoE Starter Kit - Feature]: Teams, their Entra ID object and security roles assigned.

### ISSUE THREAD

**Issue by MrHueb** [microsoft/coe-starter-kit#6686]
### Is your feature request related to a problem? Please describe.

Cx requirement:
It is necessary to monitor what groups have been assigned e.g. the environment maker security role in each environment.

### Describe the solution you'd like

Include the information in the CoE Starter Kit Core Components.
For every Environment object in the Admin View MDApp, the Teams in that environment should be listed.
For every team listed, one should have the Entra ID Object Id (group id) and the assigned security roles to that team.

Opt.: Include an additional table with teams available and allow filtering by e.g. ,environment maker sr.

### Describe alternatives you've considered

Security Role Permissions are already available in the Admin View MD App. Potentially include information about the Environment Maker Security role here as well and show that it is assigned via a team?

### Additional context?

I know that this feature might require some investment as the names of the Security Roles differ and the complexity increases with BU-level security role. Enabling this feature only for out of the box SR like Environment maker, System customizer, and System admin would be great.
```[tasklist]
### Tasks
```

**Comment by Jenefer-Monroe** [comment]
Hello. We've experimented with this a little bit and the data is just too heavy for most organizations to do with our architecture. 

We do have something similar for the System Admin role today, and you can optionally flip an env var to do it for all BUs for that SR. The focus in this is on the individual not the group but it does comtain the group through them. So it will show for example that Adele is a direct member and also a member via a group with the group information. 

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a1fde453-7c7d-4471-8184-d4c0637c394e)

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1a03a84c-8219-4120-b653-8a970e76fda4)


I did try to write the flow in a way that people could extend it to all SRs if they wanted, but we just cannot ship that way as the COGs would be too high for most people.

**Comment by MrHueb** [comment]
Thank you Jenefer! This helps a lot. We will then tune the flow to include other SR as well. 👍Having the out of the box security roles in the same view sometime in the future as a standard would be great though. ;)

**Comment by Jenefer-Monroe** [comment]
Great! If you add a second flow instead of tuning this one. You can get all, and filter out sys admin, then do the rest. This way you can continue to get updates from us in the original flow in case we make improvements.

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this out but please returning if you have other questions in the future
