### ISSUE TITLE
[CoE Starter Kit - BUG] Import solution failing - missing dependencies - CreatorKitCore (1.0.20230421.1) (202)

### ISSUE THREAD

**Issue by kurtvanbalen** [microsoft/coe-starter-kit#6687]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When downloading / extracting the CoE Core Components from [setup-core-components](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components ), I tried importing the solution in my new freshly setup environment. 

Unfortunately, the following dependencies are missing: 
![PPError](https://github.com/microsoft/coe-starter-kit/assets/28528957/be806635-10a6-47a8-99ef-1d282d24939b)
[log (1).txt](https://github.com/microsoft/coe-starter-kit/files/12683333/log.1.txt)

Could you please assist in how to solve this?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Solution itself

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
It looks like you missed to import the Creator Kit solution first, please see:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-creator-kit

**Comment by kurtvanbalen** [comment]
Thanks manuel, seems like I didn't see that step, my mistake! Thanks for the quick response!
