### ISSUE TITLE
[AA4AM] Rename "global-variable-group" to make it easier to identify that it belongs to AA4AM

### ISSUE THREAD

**Issue by Chris-WP** [microsoft/coe-starter-kit#669]
**Is your feature request related to a problem? Please describe.**
The setup of AA4AM currently requires the creation of of an Azure Pipelines Library variable group with the name "global-variable-group". This name is very generic and makes it difficult for other administators to understand that it is used by "AA4AM"

**Describe the solution you'd like**
Renaming the group to say "aa4am-global-variable-group" (or something similar) would make it easier for other administrators when working in Azure DevOps of large organisations.

**Describe alternatives you've considered**
Whilst this could be customised for just my organisation, I think it may be useful for the broader community

**Comment by mikefactorial** [comment]
@Chris-WP this is good feedback. Adding it to the backlog. Thanks

**Comment by mikefactorial** [comment]
@Chris-WP This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.
