### ISSUE TITLE
[CoE Starter Kit - BUG] PowerPlatformGovernance_CoEDashboard_August2023 - Cross tenant report issue

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#6692]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am refereeing here my previous ticket which is in close state - "issues/6387"

Now the situation is worse in cross tenant report

1. Deleted record still appearing in report 
2. User which belongs to my tenant (st.com) also reported as cross connection 
3. Item count in report drastically grown up to 1256

Screen shot: 
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/44775bf1-b14a-4831-9f4d-20b99b0cb342)

Dashboard refresh: Report refreshed today
Admin | Sync Template v3 (Connection Identities) - Running fine without any error 
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.15

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities) 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Can you confirm what version of Core you are on? It says 3.15, is that correct?

**Comment by Jenefer-Monroe** [comment]
Do you have this filter set?


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ee7dc95e-eb99-45c8-ba85-dcce2e2c2626)

**Comment by sharmajitendralal** [comment]
Yes, your assumption is correct, we have installed 4.15

No there is no filter applied 
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/3b3d4215-307f-48ec-b310-6c68a2975016)

**Comment by Jenefer-Monroe** [comment]
Please browse to the last recent run of **_Admin | Sync Template v3 (Connection Identities)_**
What comes through as the localTenantString here? Is it th **_st.com_**?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/faed040f-8139-4946-8bbd-3d2b89a8d685)

**Comment by sharmajitendralal** [comment]
Hi, 
No, I can see this guid

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/313ee24e-4b5c-40e4-adaf-a2c1e2edbc61)

**Comment by Jenefer-Monroe** [comment]
ok this is based off the value you have for admin email. so it appears that env var was set incorrectly. This will actually mess up quite a few things in the kit, not just this. 

You can fix this in the CoE Admin Command Center
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8b612d56-b465-4f73-9e1e-47fdde0c9973)

And you should enter the email of an Admin persona as described here: [How will you communicate with your admins, makers, and users?](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users)

**Comment by Jenefer-Monroe** [comment]
Since flows sometimes cache env vars, after you fix you may want to restart all the flows that reference this env var. You can get that list as shown here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/10fa5094-7767-41ac-b07e-ad6fef5c9212)

**Comment by sharmajitendralal** [comment]
> ok this is based off the value you have for admin email. so it appears that env var was set incorrectly. This will actually mess up quite a few things in the kit, not just this.
> 
> You can fix this in the CoE Admin Command Center ![image](https://user-images.githubusercontent.com/89584709/270669305-8b612d56-b465-4f73-9e1e-47fdde0c9973.png)
> 
> And you should enter the email of an Admin persona as described here: [How will you communicate with your admins, makers, and users?](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users)

Does It mean , I need to put M365 group email ID in this Admin Email Variable?

**Comment by Jenefer-Monroe** [comment]
you need to put the email address in there, as shown in the example

**Comment by sharmajitendralal** [comment]
> you need to put the email address in there, as shown in the example

Hi Thanks, 

Please confirm is this correct? this is M365 group email ID Admin Persona
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/2ec77191-0fb4-488d-bfaa-0392dfc84c99)

**Comment by Jenefer-Monroe** [comment]
Yes that is the format you will want.

**Comment by sharmajitendralal** [comment]
Hi,  

Admin Email not update in default environment variable after update of "Admin Email" using Power Apps Admin app

Here is screen shot:

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/1e2bbb8f-3bcc-41c1-8fa9-78505b92ab32)

**Comment by Jenefer-Monroe** [comment]
We did ship with that in there as default accidently once but that was literally years ago at this point. So I dont know how you would still have it. 
Can you please check if you have unmanaged layers on the env var? 


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/debbc60c-2314-4ad1-8bb8-66e2b09acb30)

**Comment by Jenefer-Monroe** [comment]
If it does, and that default is removed, then please follow these instructions on how to [update environment variables](https://learn.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables).
With regards to order to reset, you can turn off in any order you like, then follow [setup instructions](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) for the order to turn back on.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
