### ISSUE TITLE
[CoE Starter Kit - BUG] Not populating the data in the CoE Dashboard 

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#6696]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, 

I currently do see 28 bots in the Production_CoEDashboard; however, is not able to see the data for each bot in the below table. Was something misconfigured or is this a known issue? 
![image](https://github.com/microsoft/coe-starter-kit/assets/100535041/c55b00d3-52e6-452c-bf99-b3b5516bb384)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August

### What app or flow are you having the issue with?

Production_CoEDashboard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I do not repro this. If you select the table, can you confirm that you dont have something on the visual filtered?



![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fe4d2b15-90fd-4d4f-9ee7-c99087d3a2aa)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
