### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Dataflow Apps Not working

### ISSUE THREAD

**Issue by MartinGecko** [microsoft/coe-starter-kit#6702]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When refreshing the PowerBI Dataflow, I get the error Error: DataFormat.Error: We found extra characters at the end of the JSON input. Value = <ccon> </ccon> Position = <ccon>8387</ccon>. 

The Power Apps Dataflow is not having this issue. 

### Expected Behavior

I expected the PowerBI Dataflow to complete refreshing without errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September

### What app or flow are you having the issue with?

PowerPlatformAdminAnalytics-DF

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello. There was a change in the incoming JSON from Datalake. We are working to fix for Oct release. Please see https://github.com/microsoft/coe-starter-kit/issues/6577

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close as a duplicate. Please monitor that bug for updates.
