### ISSUE TITLE
[ALM Accelerator - QUESTION] Grant application user power app management permission

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#6705]
### What is your question?

Hi , 

I'm using a trail tenant and not able to configure grant Power app management permission by powershell:
https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#give-power-app-management-permission-to-your-app-registration

Is there workaround to achieve this step?

Thanks a lot in advance for your advice!!

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

September 2023

**Comment by mikefactorial** [comment]
@SOMSGH not sure if there's a workaround but you can still use the ALM Accelerator without the specific permission. There will just be a few features that won't work documented here. https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceALMAccelerator/PREVIEW.md
