### ISSUE TITLE
[ALM Accelerator - QUESTION] QUESTION

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#6706]
### What is your question?

What makes the Solution Checker run in the deployment pipeline?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

September 2023

**Comment by mikefactorial** [comment]
@LucX4 Solution Checker runs in the Validation pipeline when a PR is created from your feature branch to the solution branch. There's a branch policy on the solution branch that defines the pipeline to run when the PR is created.

**Comment by LucX4** [comment]
Thanks @mikefactorial!
