### ISSUE TITLE
[CoE Starter Kit - BUG] changing email environment variables

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#6708]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello everyone, everything good?

I'm customizing the messages in the inactivity flows, and I found it strange that the text was behaving differently, when I realized that the text boxes are not in the same pattern, some are as formatted texts and others as pure text, forcing them to be placed in HTML code as per the evidence below

![Backup reminder command bar format](https://github.com/microsoft/coe-starter-kit/assets/94450591/2d966367-8643-4c45-8e34-0f0905aca4a8)

![Create an approval](https://github.com/microsoft/coe-starter-kit/assets/94450591/bb09ea02-8e10-45d3-9e06-6cd7338b0c9d)

I believe this is an easy issue to be equalized in the CoE Kit

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by ClaudioRWS** [comment]
Olá Jenefer,
thank you for the explanation!
i will close the bug which is don´t bug

**Comment by Jenefer-Monroe** [comment]
You are most welcome, thanks for using the kit!
