### ISSUE TITLE
cannot Setup new ALM Accelerator Project

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#6711]
### What is your question?

Hi , 

The user got project administrator permission at DevOps but not able to Setup new ALM Accelerator Project, having error '_scrubbled sensitive data_' 'when tried to create new repo-
![image](https://github.com/microsoft/coe-starter-kit/assets/131751950/67124b46-60ec-42ae-b6c8-314b72b54ae7)
![image](https://github.com/microsoft/coe-starter-kit/assets/131751950/969ca7ec-11db-4d39-88af-a2fee56d3fbf)

If I choose to 'Select existing Project hosting Pipeline Templates' and select existing project, then nothing happened after clicking NEXT...

![image](https://github.com/microsoft/coe-starter-kit/assets/131751950/cae3be68-4095-4600-bb17-1c737ac39f04)

Please advice how to configure this step , thanks!

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

September 2023

**Comment by mikefactorial** [comment]
@SOMSGH are you able to create a repo in the project manually from Azure Devops? Seems like a permissions issue or a problem with the Azure DevOps Custom Connector Connection.

**Comment by orjsol** [comment]
<img width="338" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/52534802/40be15ae-bb77-487c-8df3-c6ae98119344">

Get an error on Schema validation.

This is when I test the custom connector

**Comment by SOMSGH** [comment]
Hi Mike,

It was resolved once I grant proper permission to the identity, thanks!

**Comment by SOMSGH** [comment]
> I have the more of the same problem after updating to September release. I first created the project in devops then I use the app to set it up. Everything seems fine. Repo are created I'm able to commit, but when I try to deploy nothing happens. The pipelines does not start.
> 
> But during the setup from ALM I also get the error: _Scrubbed_Sensitive_Data

Hi @Orjsol,

Did you ALM app shows deployment successful while no pipeline running at Devops?
