### ISSUE TITLE
[CoE Starter Kit - QUESTION] Where can we find all data/table schema for CoE kit, especially for the environment capacity and usage

### ISSUE THREAD

**Issue by mspatlin** [microsoft/coe-starter-kit#6712]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, Team:

Would like to know if there's any link/info that we can download the table schema/columns used for CoE Govern components? 
The purpose is to get the capacity consumption data of environments and then we can download related data and design our own reports/filters.

That brings another question, how long does CoE keep this capacity consumption data, 
Will it be overwritten and always be the snapshot of the status-quo? 
If so, any API we can use to pull out the data periodically?

Thank you in advance!

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Sep. 2023

### What app or flow are you having the issue with?

Environment capacity

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately we do not have very thorough notes on this. We are a very small (2 person) team and so authoring and even harder updating these things becomes prohibative. 
You can start with this information though: https://learn.microsoft.com/power-platform/guidance/coe/core-components

**Comment by Jenefer-Monroe** [comment]
We do not manage the data storage in your tenant at all, so for audit logs for example you may want to go purge old records periodically if the storage is too high.

**Comment by mspatlin** [comment]
Hi, Jenefer:


Thank you for the reply and info, got it

Patrick

Jenefer Monroe ***@***.***> 於 2023年9月27日 週三 21:06 寫道：

**Comment by Jenefer-Monroe** [comment]
Great. I'll go ahead and close then but please do return if you have other questions in the future!

**Comment by mspatlin** [comment]
Sure and thanks for great support again.

Patrick

Jenefer Monroe ***@***.***> 於 2023年10月2日 週一 21:18 寫道：
