### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Zubair-DS** [microsoft/coe-starter-kit#6714]
### Does this question already exist in our backlog?

- [ ] I have checked and confirm this is a new question.

### What is your question?

Is there any way to change the Microsoft logo to the customer's company logo in the email template? I have checked the Customized email Table and admin center app but didn't find any resolution. 

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Please see https://github.com/microsoft/coe-starter-kit/issues/6659

**Comment by Zubair-DS** [comment]
Thanks, I have got it now.

**Comment by manuelap-msft** [comment]
Great, I'll close this out now but please let us know if you have other questions! 

Thanks for using the CoE kit!
