### ISSUE TITLE
[CoE Starter Kit - QUESTION] Note from your Power Platform Admin: Reminder to back up your flow: 

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#6715]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

How often we get this type of email that we mark for deletion.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/12bf2d98-bb48-4b5a-bc63-7e7a56d24df6)

Thank You.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

August 2023

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, we have a workflow diagram that shows this for [apps](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#admin--inactivity-notifications-v2-start-approval-for-apps) and [flows](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#admin--inactivity-notifications-v2-start-approval-for-flows) that you can view for more details. Ive shared below as well but the short answer is **_3 weeks_**. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/04c90f9e-8490-4dc6-b053-f90c92f433e0)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/27f16d0a-ade5-428b-953a-d1d54aa34936)

**Comment by lingutla123** [comment]
Are we get multiple notifications before delete? Is it only 1 notification?

**Comment by Jenefer-Monroe** [comment]
You will get them weekly. Please view the diagram from above which explains the process.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/43a1bb0b-07c3-48a2-b092-bd28a12513f2)

**Comment by lingutla123** [comment]
Thank You.
