### ISSUE TITLE
Error while upgrading COE toolkit from version 4.9 to 4.15

### ISSUE THREAD

**Issue by HimanshuVirmani05** [microsoft/coe-starter-kit#6716]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am upgrading my existing COE toolkit from version 4.9 to version 4.15. I am getting error which I am attaching for your reference.
![Capture](https://github.com/microsoft/coe-starter-kit/assets/146099902/443ac433-517a-4b91-8eb1-8880df54f1b2)
[Center of Excellence - Core Components_import.txt](https://github.com/microsoft/coe-starter-kit/files/12728173/Center.of.Excellence.-.Core.Components_import.txt)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Details mentioned in attached log file

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

When we are importing solution 4.15 over 4.9 then we are getting the error.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
