### ISSUE TITLE
[AA4AM] Update Connection References - Timeout

### ISSUE THREAD

**Issue by rajyraman** [microsoft/coe-starter-kit#672]
When I deployed a solution with "Upgrade", the connection references step timed out.

![image](https://user-images.githubusercontent.com/5035266/122840468-82736b00-d33d-11eb-9a1b-5c7259f33d4b.png)

**Comment by mikefactorial** [comment]
Hey Natraj,
Were you able to get past this issue? Was it a transient slow down in the platform or is it still an issue?
Mike

**Comment by mikefactorial** [comment]
Hey Natraj,
Closing this out for now.
Mike

**Comment by rajyraman** [comment]
@mikefactorial - The import and solution upgrade take more than 2 hours. So, I think that it will happen again, but I haven't imported a new version yet.
