### ISSUE TITLE
[CoE Starter Kit - BUG] Some Flows Missing from CoE Tools

### ISSUE THREAD

**Issue by kashanico** [microsoft/coe-starter-kit#6720]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When searching for a Flow in Admin Set Flow Permissions OR Power Platform Admin View app, no flow comes back.
But I can confirm the flow is in fact there, on and active.
This has been the case for a handful of flows through our experience.

![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/503e8845-fe94-4c9f-83af-e2b4ad36a3ab)
![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/1c72ceda-40e1-4b83-b59f-434a863b353a)
![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/7ee150ae-f875-44c2-957b-a93d7f4f3c78)

Admin | Sync Template v4 (Flows) is on and active
![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/0819b6b5-c209-436e-af41-398545bbe213)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry I'm not quite following. I think you are saying that "Project Account Invoice Approval - V2" is a flow you have in an environment but that its not showing up in the inventory. 

Please find the most recent run of the **_Admin | Sync Template v4 (Flows)_** for that environment. You can find this by adding the display name column to the run
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/64ab4905-8526-46bd-8de1-f56b9bb06ab0)

Is it the failed run you show? If so you will need to open that failure and find where it failed.

**Comment by kashanico** [comment]
Hi. We are finding that there we cannot find certain flows using any of the CoE tools like the PwrP Admin View or Set Flow Permissions. When in fact we know they are active in our tenant. This is happened to several people on our team when looking for a flow within the CoE toolkit. The behaviour started after we deployed the Sept CoE Update.

The Admin | Sync Template v4 (Flows) flow is on and running. 

Looking at the Sync Template v4 flows and at the most recent run for the default env which is where this one flow is in for this example, here is the error:
![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/ab62d982-8d51-4acf-bdb3-147d6656c993)

I'm seeing the same errors across all runs that have failed no matter the environment they are looking through

**Comment by kashanico** [comment]
In fact all these flow errors from this Admin | Sync Flow Errors email
have the same error
Failed to parse impersonation invoker connections from trigger 'manual' outputs. Details: 'Could not find 'x-ms-user-id' header in the trigger request. Workflow has connection references '["shared_commondataserviceforapps","shared_commondataserviceforapps_1"]' with 'invoker' as impersonation runtime source.'
![image](https://github.com/microsoft/coe-starter-kit/assets/64927104/ed8aa29b-b338-4af3-8de2-5edc60be2a9b)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
