### ISSUE TITLE
[ALM Accelerator - BUG]: ALM Accelerator for Power Platform App configure Connection not showing

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#6722]
### Describe the issue

Hi, 

when trying to use this app as maker and > configure solution > create a new connection at target env > refresh > the dropdown of connection still empty, any insights on this bug? thanks in advance !
![image](https://github.com/microsoft/coe-starter-kit/assets/131751950/ee5d04c1-8708-4700-ab2c-e0a13f1c87a2)

### Expected Behavior

show connection reference available at dropdown

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

September 2023

AB#553

**Comment by mikefactorial** [comment]
@SOMSGH I'm not able to reproduce this. It's possible that this is an upper limit issue on the number of connections in the target environment. Have you been able to narrow down the issue at all?

**Comment by RajeevPentyala** [comment]
@SOMSGH Please provide an update on Mike's feedback.

**Comment by SOMSGH** [comment]
thanks the connection has shown
