### ISSUE TITLE
[ALM Accelerator - QUESTION] File /Pipelines/export-solution-to-git.yml not found in repository

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#6724]
### What is your question?

Currently I'm testing at trail tenant , I'm now not able to finish deploying solution from source to target env due to lacking of template at project repository ,  when I commit the solution, it shows error see below:

Error running pipeline: {"$id":"1","innerException":null,"message":"An error occurred while loading the YAML build pipeline. File /Pipelines/export-solution-to-git.yml not found in repository [https://dev.azure.com/ModAlmDemo/AlmDemo2/_git/coe-alm-accelerator-templates branch refs/heads/main](https://dev.azure.com/ModAlmDemo/AlmDemo2/_git/coe-alm-accelerator-templates%20branch%20refs/heads/main) version baebe7370116c4c4db737f696c2117e4db858a73.","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException","errorCod...

 I suppose the root is when I try to install templates via ALM accelarator admin app it shows ##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request
From <https://dev.azure.com/ModAlmDemo/AlmDemo3/_build/results?buildId=3&view=logs&j=edfb52f7-1394-5d79-43ff-35b6afee0ed2>

I then filled in the form but it mentioned will take 2-3 days to approve the request..which gives uncertainty, I guess this result in not able to commit the solution to devops?

Any work around to install the basic templates (to commit and deploy)at devops?
Could you please provide a step by step guide from install basic template to commit the solution, thanks a lot!

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

September 2023

**Comment by mikefactorial** [comment]
@SOMSGH pardon the delay. This may not be an issue anymore since some time has passed, but thought I'd follow up for the sake of anyone else who has the same question. 

The only workarounds to the "No hosted parallelism..." message is to do as you have and fill out the form and wait for approval or use self-hosted agents until your request for parallelism is approved. Azure DevOps trials don't provide compute capacity by default.

Closing this out.

**Comment by SOMSGH** [comment]
Yes , indeed, once parallelism is approved it works, thanks!

**Comment by AHMEDBOUCHAALA** [comment]
Hello @SOMSGH , do you please remember how much time it took for the approval ?

**Comment by SOMSGH** [comment]
> Hello @SOMSGH , do you please remember how much time it took for the approval ?

Sorry for late reply, it took only within 24 hours!
