### ISSUE TITLE
[CoE Starter Kit - Feature]: Inactivity processes - Change condition to Start Approval for Flows - Data Export - Number executions

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#6727]
### Is your feature request related to a problem? Please describe.

Hi,
actually in the Inactivity processes, the flow "Admin | Inactivity notifications v2 (Start Approval for Flows)" check if a flow haven't been modified in the last six months.
This condition may not be fair because a flow may be running daily correctly and usefully but without being modified for more than 6 months.

### Describe the solution you'd like

With Data Export we can to know the number of executions of a flow.

I think that it would better that the condition was "number of executions = 0" for example.

**Comment by manuelap-msft** [comment]
Hello,

this is already on our backlog: https://github.com/microsoft/coe-starter-kit/issues/4996 - we have a larger update planned for Inactivity Notifications (UX update, some update to the logic). There's a label through which we're tracking all this work: https://github.com/microsoft/coe-starter-kit/issues?q=label%3AInactivityRewrite+ 

We're hoping to get to this potentially in November - we're just waiting for some product features to roll out before we can start there.

**Comment by albertocastro365** [comment]
Oh sorry, I didn't see it.

**Comment by manuelap-msft** [comment]
No worries at all! There's way too many features on our backlog to know about them all :)
