### ISSUE TITLE
[ALM Accelerator - QUESTION] Microsoft.TeamFoundation.Git.Server.GitPullRequestNotEditableException

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#6729]
### What is your question?

Hello, 

After successfully commit the solution to devops source control , I would like to deploy the solution but got the error msg below:

![image](https://github.com/microsoft/coe-starter-kit/assets/131751950/b67ec0e2-5e6b-4f44-beb1-8141b750c155)

Please suggest how to deal with this error in order to deploy the solution via ALM accelerator, thanks!! 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

September 2023

AB#324

**Comment by mikefactorial** [comment]
@SOMSGH I haven't been able to replicate this issue. However, it is likely something to do with the app attempting to set the auto-complete flag on the PR after it's created. I wonder what the state of the PR is in Azure DevOps after it's created. If you're still having this issue can you take a look in Azure DevOps and see if the PR that's created is completed or some other state than active?

**Comment by RajeevPentyala** [comment]
@SOMSGH Can you please try Mike's suggestion and revert the findings?

**Comment by SOMSGH** [comment]
@RajeevPentyala , 

Thanks, it works now!
