### ISSUE TITLE
Incorrect App unique users when comparing this with Analytics in power platform admin dash board for Apps

### ISSUE THREAD

**Issue by albertsonsdev** [microsoft/coe-starter-kit#6731]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

App unique user count is showing wrong in the PBI report when comparing the same user count for the same app Analytics in power platform admin dash board for Apps.
Tried to followed the resolution given in https://github.com/microsoft/coe-starter-kit/issues/4858. 
 Cleanup Helper - Power Apps User Shared With flow ran for 15 hours with errors. "Resource does not exit or one of its queried-reference property objects are not present".  This error appears on list group members for the App.

### Expected Behavior

App unique user count in PBI report should be same as app Analytics in power platform admin dash board for Apps.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

 Cleanup Helper - Power Apps User Shared With, Admin | Audit Logs | Sync Audit Logs |

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Compare PBI report with app Analytics in power platform admin dash board for Apps.

**Comment by Jenefer-Monroe** [comment]
Can you please share screenshots? That helps us know where in the PBI you are referencing much easier. Note that you need to be logged in to GitHub to share images, responding in email will not work.

**Comment by albertsonsdev** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/130549862/3173f322-6a40-40b1-97bd-64ae8574eafd)
Flow name : Cleanup Helper - Power Apps User Shared With
Step :  list group members for the App
Error :  "Resource does not exit or one of its queried-reference property objects are not present"

**Comment by albertsonsdev** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/130549862/9ce20cec-2e98-41fe-a525-9bb5b1bf314c)

**Comment by Jenefer-Monroe** [comment]
And for your failures in the shared users . Please share a screenshot inside the flow at the point of failure.
I presume by this action: **_Step : list group members for the App_**
You mean this call. If so failures there should be caught

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66e22813-6dfa-425e-bbc4-bcb7b9f11e46)

**Comment by albertsonsdev** [comment]
**Error Details**

"error": {
            "code": "Request_ResourceNotFound",
            "message": "Resource '4e072a75-3a6b-438e-ad33-b8216ce793cc' does not exist or one of its queried reference-property objects are not present.",
            "innerError": {
                "date": "2023-09-26T20:59:56",
                "request-id": "929449dc-fdc9-480e-9129-bd2ff7ede64b",
                "client-request-id": "929449dc-fdc9-480e-9129-bd2ff7ede64b"
            }
        }
There is no catch in this step.
![image](https://github.com/microsoft/coe-starter-kit/assets/130549862/f321be47-8ad5-4f90-9b71-1e33a2de84eb)

**Comment by Jenefer-Monroe** [comment]
ok you must have an unmanaged layer on the flow as you can see from my screenshot, this is now a caught error. (ex if the group got deleted) 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9b8a9925-5a62-484f-9a71-b607d2bf919e)

Please see [Removing other customizations](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#removing-other-customizations)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
