### ISSUE TITLE
Audit log content retrieved

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#6733]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What content from M365 Management API does the Audit flow retreive in detail?  I realize that we only keep some of the information, but what total amount of information is being retrieved?

We are being asked by security to explain and provide the list of fields, and I can't find details on what the ActivityFeed.Read permissions will return, or what fields we keep.  Other than shared, launches.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately there is no filter on that backend for what service to retrieve, so we retrieve everything and then filter in the client (the flow). 
In other words, permission to the backend does give you permission to see everything (ex boots of Excel), and then we filter in the flow to only the things of interest.

**Comment by PPCan** [comment]
Ok. Can you point me to the list of data that is retrieved?  We will be asked for it so security can review the risk.

**Comment by manuelap-msft** [comment]
Data is retrieved via the Office 365 Management API, so you can find more information on that in the documentation of that API. Here's the schema: https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#common-schema

**Comment by manuelap-msft** [comment]
The sync flow retrieves all data of the Audit.General category - see https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference#working-with-the-office-365-management-activity-api - there's no Power Platform category, instead all Power Platform and other events fall under the Audit.General activity.

Once all data is retrieved, it's filtered to the events we care about - that's LaunchPowerApp, DeletePowerApp and DeleteFlow. Those are the only events processed as part of the flow. 

For LaunchPowerApp we store the CreationTime and look at the Unique ID of the app. For DeletePowerApp and DeleteFlow we also look at the CreationTime of the event (= when the flow/app was deleted) and the App/Flow Name (unique ID).

**Comment by PPCan** [comment]
Thanks!  I went into the flow and I see how it works.  

Is there a location that lists all the operations/content that the Audit.General activity logs? We going to have to show that the content returned for Audit.General has no personal information, or information that would be considered sensitive, if it was compromised.

**Comment by Jenefer-Monroe** [comment]
Not that I am aware of, but here is the documentation for it. Its a product api that we just use so if this documentation doesn't contain what you need you may need to reach out to product support for more information. 
https://learn.microsoft.com/office/office-365-management-api/

**Comment by PPCan** [comment]
Ok. Thank you.  I found this in the CoE docs.  I guess this is the list of activities that are logged in M365 Office management, and the flow just filters for the 3 fields above?

**Comment by Jenefer-Monroe** [comment]
You are welcome! I'll go ahead and close this out then, but please do return if you have other questions in the future.
