### ISSUE TITLE
[CoE Starter Kit - BUG] Admin |Sync Template v4 (flows) in error when disabled envt

### ISSUE THREAD

**Issue by sikadouc** [microsoft/coe-starter-kit#6734]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

when Dataverse for teams environment is disabled by inactivity process the admin async template (flows) is failing on the action List Flows as Admin  with the error : 

Request to XRM API failed with error: 'Message: The Dynamics 365 organization you are attempting to access is currently disabled.  Please contact your system administrator', see the CS below 

![image](https://github.com/microsoft/coe-starter-kit/assets/129759606/84c3cb3d-0d47-4905-87bb-719b01675fc2)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin - sync Template v3 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
If you go to the Power Platform Admin View app, find one of these environments. What is shown in the "Environment State" section? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/df32f0ca-7fe7-47a3-bdf4-900ae5317375)

Can you also confirm, does a similar failure happen for other object types? 
For example if you go find the most recent run for this envt in **_Admin | Sync Template v4 (Flows)_**, does it also fail?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/57309be6-3710-4dbf-ac4b-ca66ee928ced)

**Comment by orauch-a** [comment]
The solution version of the core component is 4.9 not 4.13
We have not this "Environment change" section on our version.
And the  Admin | Sync Template v4 (Apps) does not fail.

**Comment by Jenefer-Monroe** [comment]
You can check for this state property in the product itself intead then please by going to https://admin.powerplatform.microsoft.com/environments > selecting the environment for which this is failing

Share what you see both here

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2996fdba-0a74-4fde-9e66-78e207793d2b)


and then when you click that edit button, here


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/81a66858-1e88-4a29-ab80-e15452a83768)
