### ISSUE TITLE
[CoE Starter Kit - BUG] Phantom Outlook Connectors Still Being Reported After Power Apps Removed Them (App Solutions Included)

### ISSUE THREAD

**Issue by abhijkumar-msft** [microsoft/coe-starter-kit#6737]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

TAKEN DIRECTLY FROM THE CLIENT EMAIL:

Please find two of the zip files attached. These apps have removed the outlook connector from make.powerapps.com but the apps are still showing the connection in the CoE and PowerShell and if a new user tries to access the app they’re still asked to allow access to the Outlook connection, so there’s clearly some phantom references left somewhere in the source code even after removal from the UI. In some instances, we can still see the Outlook connector show in under the Connections tab in the app settings screen, while some other instances don’t show up in the connections tab at all.

The Planning Credential Request file has some clear references left in the json files and inside the msapp file. For the second package (labeled test), I still haven’t been able to find where the connection is still being referenced. 

This issue is causing significant issues for us as we’re planning to include Outlook in our DLP to block access, but multiple users have reached out saying that they’re still being flagged as non compliant even after removing the connector from their app. We currently have ~400 apps facing this same issue which is blocking us from being able to properly implement controls requested by our InfoSec team, so your urgent help would be greatly appreciated.

### Expected Behavior

Once the developers have removed the Outlook connectors from their power apps, the CoE Starter Kit should no longer report them as having said connectors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.7 (June Version)

### What app or flow are you having the issue with?

CoE BYODL Flows Connection dataflow

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

I have linked to two app solution files that contains the power apps that are mis-reporting the 'phantom Outlook connectors'. Simply publish them to any local environment and see if the connectors are still being reported.

Please ping me directly in Teams (abhijkumar@microsoft.com) if you'd like additional information.

[PlanningCredentialRequestV4.zip](https://github.com/microsoft/coe-starter-kit/files/12741816/PlanningCredentialRequestV4.zip)
[test_20230913144359.zip](https://github.com/microsoft/coe-starter-kit/files/12741817/test_20230913144359.zip)

**Comment by Jenefer-Monroe** [comment]
Hello. It sounds like this is an issue with the app itself and not hte kit's inventory of it. 
The app itself is keeping the connection in its msapp file. I'm afraid this is something you would need to work with product support about.

**Comment by abhijkumar-msft** [comment]
Would you suggest we file an IcM ticket? Or is there someone specific in the product group I could work with that you might recommend?

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont know the answer to that question for your organization. I suggest you work with your lead / peers to see how they typically raise issues blocking their customers.

**Comment by abhijkumar-msft** [comment]
Okay, working with Power CAT / IcM to continue troubleshooting. Thanks Jennifer!

**Comment by Jenefer-Monroe** [comment]
You bet, happy to help. 
I'll go ahead and close this out then.
