### ISSUE TITLE
[CoE Starter Kit - QUESTION] Fill HAS DLP Policy for environments

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#6738]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

Sorry for the question, but I'm still new to the CoE world, in Environment the column "Has DLP Policy" is all marked as "No", but in several environments it exists.

What is this behavior like, would it be a bug that I can't see?

![screenAdminView](https://github.com/microsoft/coe-starter-kit/assets/94450591/7380f358-06ed-43cb-abdd-840448600c1d)

I thank you for your attention

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Environment Properties)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#920

**Comment by Jenefer-Monroe** [comment]
I'm not sure what this field is to be honest. It looks like it got added but never filled. 
I'll hold and ask around but I think this might just be a field we need to remove as we dont actually populate it.
Thank you for posting!

**Comment by Jenefer-Monroe** [comment]
moving to be an enhancement to fill

**Comment by manuelap-msft** [comment]
The goal of this field is to identify if environments are not covered by any DLP policy go highlight those in the governance dashboard as a "take action here" item for admins. Once implemented, it should reflect “yes” for any environment covered by DLP, either explicitly or implicitly (e.g. covered by the default policy).

**Comment by Jenefer-Monroe** [comment]
Found a pretty low API impact way to do this with selects and filters. 
Will just be another 7 API calls per envt:

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d8b5808c-d884-4eff-904c-95c6ab049c5d)

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8d28288c-2b4e-4ada-ad35-ccf8fec03789)

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6c442bbb-740c-4588-977e-9d5f8ec4ff08)

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/59948582-ead9-460b-8aa5-8dc7dad228de)
