### ISSUE TITLE
[ALM Accelerator - QUESTION]: License Required for GetReleaseHistory flow

### ISSUE THREAD

**Issue by violat0r1690** [microsoft/coe-starter-kit#6744]
### Describe the issue

One I would like to to turn on the "GetReleaseHistory" Cloud flow I am getting following error:

Flow client error returned with status code "Forbidden" and details "{"error":{"code":"MissingAdequateQuotaPolicy","message":"The user 'xxx-xxx-xxx-xxx-xxxx' does not have a service plan adequate for the non-Standard connection 'Microsoft Dataverse'. https://go.microsoft.com/fwlink/?linkid=2123710","extendedData":{}}}".

For me it is a bit weird because this flows should be associated with the app. With that being said I should not need additional Power Automate Premium license. 

I do already have Power Apps Premium license.

### Expected Behavior

Clould Flow should be associated with app

![image](https://github.com/microsoft/coe-starter-kit/assets/81821434/cc79c5a1-5633-4500-973a-faae03034cdd)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

 1.0.20230906.1

**Comment by mikefactorial** [comment]
@violat0r1690 there are 2 flows for getting the release history. 1 is on demand and associated with the canvas app (UpdateReleaseHistoryInstant) while the other is a scheduled sync of the release history (UpdateReleaseHistoryScheduled). Both of these call the child flow GetReleaseHistory. This is probably why you are seeing the message you are. Unfortunately, I don't have a solution to propose to get around this issue except to modify the flows which would add an unmanaged layer to the managed solution.
