### ISSUE TITLE
[CoE Starter Kit - BUG] Wizard app has a DLP error

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#6750]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have upgraded from CenterofExcellenceCoreComponents_4.13_managed to CenterofExcellenceCoreComponents_4.15_managed.
When I launch the 'CoE Setup and Upgrade Wizard' it shows an error relating to the DLP policy.
The wizard was working before the upgrade.
Not sure if this is related, but I enabled the Audit Logs functionality after initially running the wizard. But after the Audit Logs were set up the Wizard could still be launched ok.

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/7cfc3d62-ae36-4a3c-92b4-c1468055b298)

### Expected Behavior

The Wizard app should open without errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Upgrade to v4.15 of the Core solution
2. Open the Wizard app

**Comment by Jenefer-Monroe** [comment]
Hello. Yes a connector was added and so you need to upgrade the DLP Policies which impact the CoE to allow it. 
Please see [Validate data loss prevention (DLP) policies](https://learn.microsoft.com/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies)


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bf3721c4-5d94-4f67-9a0b-1d6093918543)

**Comment by MartinWGT** [comment]
Thanks Jenefer, 
This has fixed the issue.

**Comment by Jenefer-Monroe** [comment]
Thank you for following up and letting us know!
