### ISSUE TITLE
[CoE Starter Kit - QUESTION] DLP Impact Analysis App limitation?

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#6752]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I've tested block one connector used in a flow at A env, I noticed when the flow is outside of a solution, it can be detected, while flow in a solution cannot be detected, is there limitations that the impact analysis is only working on flow/app outside of solution?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2023

### What app or flow are you having the issue with?

 DLP Impact Analysis Model Driven App

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Are both flows in inventory already? Note that we look over flows in inventory for our DLP work. 

If the solution flow is not inventoried, it could be that its never been turned on. 
Note that we do not yet inventory flows that are "unpublished" meaning they have never been turned on (though the product team is working to address this gap).

**Comment by SOMSGH** [comment]
thanks for this helpful info
