### ISSUE TITLE
Environment Flows fail history

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#6754]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

If a fail flows, in an environment, does the Toolkit log the failure?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We do not track flow usage at all in the kit, no.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
