### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Check Deleted (Cloud Flows) - Failing for Teams environments that are disabled

### ISSUE THREAD

**Issue by Rajeshgn053** [microsoft/coe-starter-kit#6756]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The following flow, has an action to list down all the flows from environment. But the action fails for the "Teams" oriented environments (which are disabled). 

Since, this category of environments are associated with "Teams", they do get influenced by the Microsoft policies, when the "Teams" goes inactive for certain period, leading to disabling them (in turn the respective D365 instances). 

![D365 Disabled](https://github.com/microsoft/coe-starter-kit/assets/143060581/6938a212-ecf9-4ca7-90bc-a2ca01949bf4)
![Dynamics CRM Disabled](https://github.com/microsoft/coe-starter-kit/assets/143060581/40fc7f63-17a2-42ac-96be-29395dd37dce)

### Expected Behavior

I believe, before performing this action or this child flow getting called. A check has to be performed on environment instance, in case they are "Teams" oriented.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Cloud Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#221

**Comment by Jenefer-Monroe** [comment]
Thanks for the thorough debugging. Can you please confirm the following?

If you go to the Power Platform Admin View app, find one of these environments. What is shown in the "Environment State" section? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/df32f0ca-7fe7-47a3-bdf4-900ae5317375)

Can you also confirm, does a similar failure happen for other object types? 
For example does it fail to inventory Model Driven Apps in **_Admin | Sync Template v3 (Model Driven Apps)_**?

**Comment by Rajeshgn053** [comment]
Hi Jenefer,

So far this error encountered only with Flows associated logics - CLEANUP HELPER - Check Deleted (Cloud Flows) & Admin | Sync Template v4 (Flows). 

Attached the details you requested, the "Environment State" block doesn't populate for all type of  environments under the App. 

May be my account doesn't have required permissions. Will send you the additional screenshot, once i check with onsite team.
![D3653](https://github.com/microsoft/coe-starter-kit/assets/143060581/e66775c4-28f5-4f0a-9e38-0bcd1224089a)

**Comment by Jenefer-Monroe** [comment]
Thank you, you can also check in the product's admin pages:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/01a488a8-9e81-4905-9b08-8f63434611d8)

**Comment by Rajeshgn053** [comment]
I will check with my team  & get back to you..

**Comment by Rajeshgn053** [comment]
Attached the screenshot requested - 
![image](https://github.com/microsoft/coe-starter-kit/assets/143060581/fe7c7fdb-6e05-490f-af3d-7ecc568c91b0)

**Comment by Jenefer-Monroe** [comment]
great thank you. we will not want to block all teams here since we do normally want to be able to do this for teams type envts. And I presume this would also repro for non-teams evts that are disabled. 
I'll explore here what / where a good fix might be for us and let you know when I have something for you to test.
Thank you for your help!

**Comment by Rajeshgn053** [comment]
Hi Jenefer,

Any updates on this issue? Any progress on this?

**Comment by Rajeshgn053** [comment]
Hi Jenefer,

Waiting for your response on this...

**Comment by Rajeshgn053** [comment]
Hi Jenefer,
To overcome this kind of error, we have applied the following fix & hope implementing this change in your next release might help the consumers, facing this particular issue.

![image](https://github.com/microsoft/coe-starter-kit/assets/143060581/13747cec-a493-4055-b499-17eb20cc9b14)

**Note - We are facing same issue with "Admin | Sync Template v4 (Flows)". Due to 8 level Nested loop limitation, we have applied the same fix in slightly different manner.**

**Comment by Jenefer-Monroe** [comment]
Hello sorry I lost access to the mailbox where responses go and so only see updates from people when I manually look at bugs. Hopefully I get it back soon.

**Comment by Jenefer-Monroe** [comment]
This is the setting we will go with, if disabled. And this is in the inventory so we may be able to just not trigger the flows at all with filters in the query.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ad4b1b6f-bae1-4b13-aa4d-563546052c16)

**Comment by Jenefer-Monroe** [comment]
Can you please comment, is this the only flow you see failing for this? I still dont have a repro locally.

**Comment by Rajeshgn053** [comment]
Yes, we have one more flow facing the same issue. Raised ticket for the same & you have responded - https://github.com/microsoft/coe-starter-kit/issues/6942

**Comment by Jenefer-Monroe** [comment]
oh thank you, I didnt notice that was for a different flow. So also Admin | Sync Template v4 (Flows)

Thank you!

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1b41243e-f7e1-497e-9c5b-38cae753b69b)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7d41f300-1adc-4110-8fdf-763d5f1b0c05)

**Comment by Jenefer-Monroe** [comment]
thank you for posting, ready for Nov release

**Comment by michael-wright-pwc** [comment]
Hi @Jenefer-Monroe, just to reiterate what @Rajeshgn053 is saying above, the CoE is storing "states/**management**/id" as "Environment State", and what we really need is "states/**runtime**/id" instead. The management id will still say "Ready" even when the environment is disabled.

**Comment by michael-wright-pwc** [comment]
Hey @Jenefer-Monroe - just checking in on this!

**Comment by Jenefer-Monroe** [comment]
Hey folks. Sorry I do not get notified of messages to bugs anymore due to some internal paperwork issues over here. This wont be resolved until the new year sadly so you may make comments I dont see until then. I have to actively look at issues to see if there are updates on them.
