### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is the CoE SK admin a system administrator in all the environments in the tenant?

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#6760]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I see that the administrator of the CoE SK has access to all the environments in the admin center with System Administrator role. Even the developer environments. 
Is this a setting in the CoE SK?
Is this expected? Is it being done through a flow?

Thanks a lot in advance!

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Today all people with the PPAdmin Role are added to all environments as sys admin. That is a product feature and we just rely on it to gather inventory.

**Comment by LizethRegules** [comment]
Got it. 
I was wondering, because only the 2 PP admins (who are CoE SK admins in the environment variable of the core components) have that behavior. 
The global tenant admin does not appear to be a user in the developer environments and has both PP admin and global admin.

**Comment by Jenefer-Monroe** [comment]
I think there are some oddities with the features around being assigned diretctly through a group or something like that. 
If the feature isnt behaving as you expect though, you may want to create a support ticket to get clarity.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
