### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION can we add a sender email instead of getting email by "flow-noreply@microsoft.com"

### ISSUE THREAD

**Issue by Zubair-DS** [microsoft/coe-starter-kit#6765]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

 Can we add a sender email instead of getting an email by "flow-noreply@microsoft.com" and also remove power automate from the start body?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

for emails send by the CoE kit, you can customize the "send on behalf of" email using the CoE Admin Command Center > Customize Emails page and editing all the individual emails there. You can customize the header and footer by modifying the email body start / end environment variables as well (which are in CSS format).

For approval emails and other emails sent by the product, here the CoE kit just relies on out of the box product features and there's no options to customize those. You can raise those as an ask for the product team here https://powerusers.microsoft.com/

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
