### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by gghaleb** [microsoft/coe-starter-kit#6767]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, I am not finding the DLP Editor v2 canvas app in Sept/October release.
was it replaced ?

### Expected Behavior

DLP Editor v2 was always here.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Sept 2023

### What app or flow are you having the issue with?

none

### What method are you using to get inventory and telemetry?

None

### Anything else?

thanks

**Comment by gghaleb** [comment]
Thanks Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
