### ISSUE TITLE
[CoE Starter Kit - QUESTION] App Launches Data Population after Audit Logs update

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#6770]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

We have updated on 9/20 to use the new audit logs development and begun to see the app usage data come through since then. With this new data, will we have to wait a month or longer period of time to have the launches in the last 30 days? I'm in the process of implementing the inactivity process and with our current data almost all our apps would be marked as inactive.

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/505d2eaa-753a-4b80-a6ca-0f7ddf8b7656)

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/405b573e-c674-4ab3-82f3-c21152e7c658)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
The Launches in the past 30 days field is only filled for customers who use Data Export as a method for retrieving inventory and usage, see field description:
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/948bd82e-c1f4-4d1f-8c6d-4298c199aef0)

This won't have an impact on your usage - the launches of the past 30 days are retrieved differently for customers who use cloud flows for inventory.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
