### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to exclude environments from the CoE kit?

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#6772]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team

We have implemented CoE Kit in our environment. As per our business requirement need to exclude some environments from CoE kit features. How we can achieve this. 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
See this article in our FAQ section: https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments

Once you've read through the instructions there, please let us know if you have additional questions.

**Comment by sunilmhatugade** [comment]
When we implemented CoE we selected YES. so all inventory gathered. 

But for now whenever new environments created  need to exclude these new environments from Inventory.

If I change value "is All Environments Inventory " to No. Is it solve my Issue?

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/d744f791-154c-4017-a8ed-0a540ec27e6c)

Or if anything else is required.

**Comment by manuelap-msft** [comment]
If you select NO, new environments will be excluded from inventory - that's correct. You can then review the excluded environments in the Power Platform Admin View and add environments you want to monitor and manage to the inventory by selecting No for the Excuse from inventory configuration.

**Comment by sunilmhatugade** [comment]
If we need a notification if the app is shared with 5 or more number of users .. then how we can achieve this...

**Comment by manuelap-msft** [comment]
There's no notification process available in the CoE kit for this, you can

- use the Power Platform Admin View to create a few of all apps shared with more than 5 users
- use the Power BI dashboard to filter and find apps shared with more than 5 users
- use the Compliance Process to ask makers to submit compliance information for your review based on how many users the app is shared with
- use the[ Sharing Limits feature in Managed Environments](https://learn.microsoft.com/en-us/power-platform/admin/managed-environment-sharing-limits) to restrict sharing 

If that's not sufficient, you can extend the CoE kit yourself to build your own notification process - here's our guidance on extending the kit:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

**Comment by sunilmhatugade** [comment]
> If you select NO, new environments will be excluded from inventory - that's correct. You can then review the excluded environments in the Power Platform Admin View and add environments you want to monitor and manage to the inventory by selecting No for the Excuse from inventory configuration.

We changed this and Set to NO,,, But still new environments not excluded from inventory.

**Comment by sunilmhatugade** [comment]
> There's no notification process available in the CoE kit for this, you can
> 
> * use the Power Platform Admin View to create a few of all apps shared with more than 5 users
> * use the Power BI dashboard to filter and find apps shared with more than 5 users
> * use the Compliance Process to ask makers to submit compliance information for your review based on how many users the app is shared with
> * use the[ Sharing Limits feature in Managed Environments](https://learn.microsoft.com/en-us/power-platform/admin/managed-environment-sharing-limits) to restrict sharing
> 
> If that's not sufficient, you can extend the CoE kit yourself to build your own notification process - here's our guidance on extending the kit: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

We set the Compliance Process if the user shared the app with more than 1 group. and We shared one app with 2 groups but still we have not get any mail notification.

**Comment by sunilmhatugade** [comment]
any update on this..?

**Comment by manuelap-msft** [comment]
> > If you select NO, new environments will be excluded from inventory - that's correct. You can then review the excluded environments in the Power Platform Admin View and add environments you want to monitor and manage to the inventory by selecting No for the Excuse from inventory configuration.
> 
> We changed this and Set to NO,,, But still new environments not excluded from inventory.

Sometimes environment variable values are cached in flows, and you may have to turn the flows on/off for the new value to be picked up.

**Comment by manuelap-msft** [comment]
> > There's no notification process available in the CoE kit for this, you can
> > 
> > * use the Power Platform Admin View to create a few of all apps shared with more than 5 users
> > * use the Power BI dashboard to filter and find apps shared with more than 5 users
> > * use the Compliance Process to ask makers to submit compliance information for your review based on how many users the app is shared with
> > * use the[ Sharing Limits feature in Managed Environments](https://learn.microsoft.com/en-us/power-platform/admin/managed-environment-sharing-limits) to restrict sharing
> > 
> > If that's not sufficient, you can extend the CoE kit yourself to build your own notification process - here's our guidance on extending the kit: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components
> 
> We set the Compliance Process if the user shared the app with more than 1 group. and We shared one app with 2 groups but still we have not get any mail notification.

The compliance process does not include a notification to the admin. If that is what you need, you'd have to extend the kit and implement the notification process yourself.

**Comment by sunilmhatugade** [comment]
> > > There's no notification process available in the CoE kit for this, you can
> > > 
> > > * use the Power Platform Admin View to create a few of all apps shared with more than 5 users
> > > * use the Power BI dashboard to filter and find apps shared with more than 5 users
> > > * use the Compliance Process to ask makers to submit compliance information for your review based on how many users the app is shared with
> > > * use the[ Sharing Limits feature in Managed Environments](https://learn.microsoft.com/en-us/power-platform/admin/managed-environment-sharing-limits) to restrict sharing
> > > 
> > > If that's not sufficient, you can extend the CoE kit yourself to build your own notification process - here's our guidance on extending the kit: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components
> > 
> > 
> > We set the Compliance Process if the user shared the app with more than 1 group. and We shared one app with 2 groups but still we have not get any mail notification.
> 
> The compliance process does not include a notification to the admin. If that is what you need, you'd have to extend the kit and implement the notification process yourself.


Can we create a separate flow for notifications and use the same table?

Please please share the table name where shared with no. of use details available.

**Comment by manuelap-msft** [comment]
Yes you can. The information on shared users is available in the PowerApps App table. Please find more information about the tables here in our documentation: https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components#tables

**Comment by sunilmhatugade** [comment]
We have set criteria in the compliance process.  but still not no any notification and alert.

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/79fbf28f-ccd4-4b71-baa4-e8df1ce873f8)

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/40ed3926-8a94-496b-ac30-0e403b10b295)

**Comment by sunilmhatugade** [comment]
Sorry.. but we are not getting this... can u please guide how we can resolve this ...

**Comment by sunilmhatugade** [comment]
this is already set to NO. Please find below snap for your reference 

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/97355134-64bb-41ee-8208-4ce5c429c6f9)

**Comment by Jenefer-Monroe** [comment]
Is this the same issue as https://github.com/microsoft/coe-starter-kit/issues/6825?

**Comment by sunilmhatugade** [comment]
Yes.. Please archive this ticket.. we will work on new ticket.
