### ISSUE TITLE
[ALM Accelerator - QUESTION] The extension **Replace token** is required but it is not Microsoft certified

### ISSUE THREAD

**Issue by Tamy05** [microsoft/coe-starter-kit#6779]
### What is your question?

As mentioned in the article below, as a prerequisite to install the ALM accelerator, the extension **Replace token** is required but it is not Microsoft certified, I'm trying to install it in my Governance environment for our organization but as it is not Microsoft certified extensions are there any workaround for it, or is it necessary to add these extensions in order to have the Accelerator run smoothly on the AzureDevops side, as this would require a Cybersecurity external check that seems a bit extensive, Could you please help with clarifying the situation? Also can you help with understanding why this is required and what it does? Waiting for your response on this

 "Install Azure DevOps extensions
The ALM Accelerator uses several Azure DevOps extensions, including some third-party extensions that are available in the Azure DevOps marketplace. The website of each third-party extension and a link to their source code are provided in the following instructions. [Learn how to evaluate a Marketplace extension publisher](https://learn.microsoft.com/en-us/azure/devops/marketplace/trust).

Sign in to [Azure DevOps](https://dev.azure.com/).

Select Organization settings.

Select General > Extensions.

Search for and install the following extensions:

Power Platform Build Tools (required): This extension contains the Microsoft build tasks for Power Platform. (https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerPlatform-BuildTools)

Replace Tokens (required): The pipelines use this extension to replace tokens in configuration files and store secure values in private variables configured for a pipeline. (https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens | https://github.com/qetza/vsts-replacetokens-task)

SARIF SAST Scans Tab (optional): Use this extension to visualize the SARIF files the solution checker generates during a build. ([SARIF SAST Scans Tab - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=sariftools.scans))"

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Latest

**Comment by mikefactorial** [comment]
@Tamy05 the Azure DevOps extension is responsible for substituting placeholders in the deployment settings with values stored on the pipelines as variables as mentioned. The purpose of doing this is to obfuscate potentially sensitive information away from source control so the values aren't stored as plain text in the repo. The only workaround, currently available, is to disable the tokenization of the deployment settings values by setting ```UseDeploymentSettingsPlaceholders = true``` variable in the ALM Accelerator variable group (https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/configure-azuredevops-pipelines#turn-on-or-off-specific-actions-in-the-pipelines). You would then have to remove the reference to the extension from the build and deploy pipeline [here](https://github.com/microsoft/coe-alm-accelerator-templates/blob/c7ca2e7bf00313b82969f7cd6b9e8272c5fe0555/Pipelines/Templates/build-Solution.yml#L137) and [here](https://github.com/microsoft/coe-alm-accelerator-templates/blob/c7ca2e7bf00313b82969f7cd6b9e8272c5fe0555/Pipelines/Templates/deploy-Solution.yml#L106)

**Comment by mikefactorial** [comment]
Closing this out for now. Feel free to open another issue if you have any additional questions.
