### ISSUE TITLE
[BUG]: Assign Role Flow Failing on Security check

### ISSUE THREAD

**Issue by derrikkbFBS** [microsoft/coe-starter-kit#678]
**Describe the bug**
I have given myself every possible security role available and still fails saying that I do not have the correct permissions.  Error code is as follows.

RetrievePrivilegeForUser: The user with id 254b25f8-12d3-eb11-bacc-0022481eac35 has not been assigned any roles. They need a role with the prvReadUser privilege.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Power Platform GitHub ALM
 - Version 1.0.0.72
 - App or Flow Assign Role Flow

**To Reproduce**
1. Create Project
2. Approve project via approval email
3. Fails one you get to assign role flow.  

**Expected behavior**
Project environment should be created and sandbox enabled for development

**Screenshots**
![image](https://user-images.githubusercontent.com/54599638/122871614-86c36800-d2ec-11eb-976d-97f472548769.png)

**Additional context**
I have given the user account all security roles trying to find correct level of privilege with no avail.

**Comment by mikefactorial** [comment]
@derrikkbFBS can you verify that the user id shown in the error message is the user that you added security roles too? The specific error is saying that the user doesn't have read rights to the systemuser table. You can double check the id by locating the user in the admin.powerplatform.com and opening the user's record. In the url you will see the id of the user e.g.

![image](https://user-images.githubusercontent.com/42348035/124942572-c28f4a80-dfd9-11eb-8480-c1b2ad20fa09.png)
