### ISSUE TITLE
[ALM Accelerator - BUG]: CustomAzureDevOps.GetGitRepos failed:

### ISSUE THREAD

**Issue by JakeStratton** [microsoft/coe-starter-kit#6782]
### Describe the issue

Despite updating the custom connector settings, mot users are not able to access branches when attempting to deploy, nor will the status icons appear. Something is wrong with the AzureCustomDevOps COnnector.  Doesnt matter which env or solution. 
 Seeing this error:

CustomAzureDevOps.GetGitRepos failed: Cannot read properties of undefined (reading 'replace')

All the policies are setup correctly in the custom connector, and somehow it is working for some users but no one else.  

### Expected Behavior

I expect to be able to access the branches to run a deploy using AA4PP.

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20230906.1

### Steps To Reproduce

1. Open ALM Accelerator
2. Click Deploy Solution

AB#329

**Comment by mikefactorial** [comment]
@JakeStratton sounds like this is an Azure DevOps permissions issue. Are the users having the problem able to view repos / branches in the project from the Auzre DevOps portal? If not do those users have a Basic or higher user license in Azure DevOps? Stakeholder will not allow for Git access.

**Comment by JakeStratton** [comment]
Yes, the users have no trouble accessing the repos dnd have the proper access level/licensing to the project.

**Comment by mikefactorial** [comment]
@JakeStratton need a little more to go on here. Wonder if the users in question can try running the custom connector from the test tab to get any more information that may come back in the response. 


![Image](https://github.com/microsoft/coe-starter-kit/assets/42348035/350da209-c9d5-4d01-a11b-c07e1a1b368e)

**Comment by RajeevPentyala** [comment]
@JakeStratton Closing this issue as there has been no update from you. Please feel free to reach out if you require further assistance.
