### ISSUE TITLE
 Inactivity processes - Baby Step Question

### ISSUE THREAD

**Issue by sasrsc** [microsoft/coe-starter-kit#6783]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Our team is launching the CoE and we want to be very careful and make sure we understand it all properly first. We intend to update the [ProductionEnvironment environment variable](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#all-environment-variables) to No and let it run sending the emails to our PP admin account. This in turn puts things in the Cleanup Old App. Once we review all the email output we will want to change the ProductionEnvironment environment variable back to Yes so that it will send the email/adaptive cards to the employees and not our PP admin account. Our question is - what happens to those App that get moved to the Cleanup Old App (assigned to the PP admin account). It's our believe that if we switch the ProductionEnvironment environment variable back to Yes, after 3 weeks of sitting in the Cleanup Old App they will be unassigned and hence the need weekly inactivity process email will then out to the proper employee. Yes?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Sept 2023

### What app or flow are you having the issue with?

n/a

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
When you are ready to turn the production environment env var to yes. I suggest you just delete all the records in the archive approval table, this way first run will be fresh. 

Be sure to also turn all the dependent flows off and back on as sometimes env vars cache in a flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1d7feaac-bca6-4143-a2ce-dbe1b5330d87)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
