### ISSUE TITLE
[CoE Starter Kit - QUESTION] Error loading apps: Failed to execute 'text' on 'Response': body stream already read

### ISSUE THREAD

**Issue by JanParnahaj** [microsoft/coe-starter-kit#6788]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are getting the following error when trying to run 
CoE Admin Command Center app or any other app:

Error Code: 2147746581
Session Id: 94334ce2-57b1-4caa-be8d-fe8d534c4a59
Timestamp: Wed Oct 04 2023 12:46:27 GMT-0400 (Eastern Daylight Time)
AppContextLoader: Failed to execute 'text' on 'Response': body stream already read
TypeError: Failed to execute 'text' on 'Response': body stream already read at La (https://content.powerapps.com/resource/uci-infra/scripts/mds.29cb19423afca598d522056c63809ea8.js:4:52705) at https://content.powerapps.com/resource/uci-infra/scripts/mds.29cb19423afca598d522056c63809ea8.js:4:51928 at async Ca (https://content.powerapps.com/resource/uci-infra/scripts/mds.29cb19423afca598d522056c63809ea8.js:4:42282)
Loading...

Can you please advise if this is a known issue and if there is any solution to address it?

Thank you,
Jan

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

All model driven apps

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

we've not seen this issue before and I don't repo this myself either. What region is your environment in? Do you still see the error if you try again and refresh the app?

Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
