### ISSUE TITLE
[CoE Starter Kit - QUESTION] App usage for model driven apps

### ISSUE THREAD

**Issue by bdcqr** [microsoft/coe-starter-kit#6791]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

In the CoE PowerBI Dashboard, there's no data for "App Usage" and "App License Assignment" for any of our model driven apps. E.g., if I go to either of these sections, and filter by the environments where the model driven apps live, there are no results. However, under "Apps", if I filter for the same environments, I do see the model driven apps listed, however they don't give me the information I need in terms of how many people are accessing them. 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

September 2023

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

usage information is currently only available for canvas apps. There's no data source we can query that gives us model driven app launches, so this is a known limitation. 

Manuela

**Comment by bdcqr** [comment]
Hi Manuela,

Ok thanks for letting me know.

Cheers,

Bobby Chow (he/him)
Manager, Enterprise Solutions
QuadReal Property Group
T 604-975-9520
***@***.******@***.***>
***@***.***
