### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL Data Export - Missing Dataflow? 

### ISSUE THREAD

**Issue by SPMush** [microsoft/coe-starter-kit#6792]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Upgrading to CenterofExcellenceCoreComponents_4.16 and configuring Dataflows and there is one missing: **CoE BYODL Flows Last Run Date .**
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/f1404795-f8ba-41b8-a951-b68470570170)

As a result the  BYODL_CoEDashboard_October2023 has erroring flow usage visuals

### Expected Behavior

Dataflow CoE BYODL Flows Last Run Date expected to exist as detailed in Guide [https://learn.microsoft.com/en-gb/power-platform/guidance/coe/setup-core-components#configure-connections-to-data-sources](https://learn.microsoft.com/en-gb/power-platform/guidance/coe/setup-core-components#configure-connections-to-data-sources)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Dataflow: CoE BYODL Flows Last Run Date

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Follow upgrade steps 
Configure connections to data sources
Dataflow: **CoE BYODL Flows Last Run Date** not present.

### Anything else?

I have been able to publish BYODL _CoE_Dashboard_October2023

But still see 
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/c71540f2-2da8-4d55-93ca-e1817ba6463d)

In PBI Desktop, applying changes does not remove the warning

**Comment by SPMush** [comment]
Discarding the changes does remove the PBI Desktop warning message . 
Message on discarding was "you have changed": Privacy setting 
I can find no visualisation issues in the published Dashboard. 
So unsure if this is an issue!

**Comment by manuelap-msft** [comment]
Hello,

I have just imported the solution in a new environment and I can see all the dataflows are there:
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/b725cea4-e2a2-467b-b54d-472a8fa319e7)

Can you check the solution and see if they are there, and just not listed in the Dataflow page? 

We had an issue like that before where the environment had admin mode enabled and that's why the import of the Dataflows failed, here's a few triage steps that you could look at:
https://github.com/microsoft/coe-starter-kit/issues/5377

**Comment by SPMush** [comment]
Hi Manuela,
I see all 9 in the solution 
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/81e0e724-33ac-47cd-b7f6-d05302ecdfd4)

But missing from My Dataflows? 
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/8dc3e6e7-9a78-4799-87a8-0055573577f0)

**Comment by manuelap-msft** [comment]
Could it be that someone else imported the kit, ever owned the kit or transferred ownership? Does it show you as the owner in the Owner column of the solution? You can look for other dataflows under All Dataflows > search by owner.

**Comment by SPMush** [comment]
It's my private tenant, I am the only user. 
All owned me.
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/3e63b2b1-e552-497b-bbe7-27c6fd5dbbfa)

**Comment by manuelap-msft** [comment]
If you go to the product Dataflow table
![image](https://user-images.githubusercontent.com/89584709/234404716-1ff737e1-34c0-4833-b2b5-d4a86142e10a.png)

Update to see these columns. 
![image](https://user-images.githubusercontent.com/89584709/234405106-05bfc280-90d7-43ab-acc9-8136bee36cea.png)

Do you see them there? You should see each listed twice, Owner as you for all, and Created By with you for half. Is that what you see?

**Comment by manuelap-msft** [comment]
If you go to aka.ms/ppac > Environments > Your CoE Environment and select Edit on the Details tab, does it show Admin mode as Disabled. 
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/21af9841-d50a-4843-a605-282cbab5912c)

If you select See all under Details, What does it show under State and Service Health?

We've only ever seen this before when the environment had admin mode enabled during import. That customer had to disable admin mode, import the solution again and then it worked - see here for reference https://github.com/microsoft/coe-starter-kit/issues/5377#issuecomment-1527951259

If that's not the case, you may have to get in touch with Microsoft Product Support through your regular support channels to figure out why the dataflow isn't showing.

**Comment by SPMush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/db812abc-dab9-4aa0-97b9-b7ac130e554c)
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/e2097941-7fb4-48ab-9847-e9a4b274090c)
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/7aec182a-8f20-44c2-a03c-4bf7a964ce62)

**Comment by SPMush** [comment]
The missing dataflow was there and refreshing ok in the September release, Issue only appeared since deploying 4.16.
Very odd it vanished. Thank you for your advice, Manuela, I will get a ticket logged. I do wonder if it relates to the environment being **managed** and the warning I received when importing? [https://github.com/microsoft/coe-starter-kit/issues/6789](https://github.com/microsoft/coe-starter-kit/issues/6789)

**Comment by manuelap-msft** [comment]
Can you please share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names. Are you only seeing the Core components solution there once, or do you see it listed twice once with the _Upgrade post-fix? 

![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

Sorry I'm a little out of ideas here :( It's definitely in the solution

**Comment by manuelap-msft** [comment]
> The missing dataflow was there and refreshing ok in the September release, Issue only appeared since deploying 4.16. Very odd it vanished. Thank you for your advice, Manuela, I will get a ticket logged. I do wonder if it relates to the environment being **managed** and the warning I received when importing? #6789

I don't think it's related to this error. This error is due to a formula issue in a custom page, and shouldn't have an impact on the dataflows.

**Comment by SPMush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/8a45b3fe-4909-4af3-8625-03e6458be6c8)



Only other thing that I have changed for the Environment that is dataflow related is I have configuring Application Insights on my CoE environment for testing, could that be creating a conflict?
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/2624bc69-e0b4-4abe-9965-483958c72ec5)

https://learn.microsoft.com/en-us/power-platform/admin/set-up-export-application-insights#create-an-export-package

**Comment by manuelap-msft** [comment]
I've not tried this myself yet but I'm not sure why it would lead to a conflict. Is your environment region United Kingdom? I'll try and set up an environment on my end with the same configuration to see if I can repo this. 

If you raise a support ticket and they have any findings, please also let us know - right now I'm unfortunately a little bit confused by this issue :(

**Comment by SPMush** [comment]
"Is your environment region United Kingdom? And you upgraded from September to October?"
Yes, and correct.

Thank you Manuela, appreciate your support with this. I will keep you informed,

**Comment by manuelap-msft** [comment]
Ok great, thanks for confirming - I'll set this up on my end and see if I can repo this issue! Sorry I wasn't able to help so far. Hopefully between us and the Support team, we'll get to the bottom of this.

**Comment by SPMush** [comment]
Ticket logged 🤞

**Comment by manuelap-msft** [comment]
I've just stood up a new environment, imported the September version, then enabled Managed Environments + Application Insights export, then upgraded to the October version. I still see and am able to configure all dataflows, including the CoE BYODL Flows Last Run Date one so I don't think it's anything to do with your environment setup. 

Hopefully support can shed a light on what's going on here! Sorry I wasn't able to help further here so far :(

**Comment by SPMush** [comment]
Just to update , I did spin up a new environment and deployed a shiny new install of October release.
All dataflows were there and was able to connect to my Datalake no problem.

Not had a chance to speak with Support engineer yet, but I still have the problem instance troubleshooting the issue.
As this is a test instance, i am not too worried as my new CoE Environment is now working fine.

**Comment by Jenefer-Monroe** [comment]
Wonderful, sounds like we are ok to close then?
