### ISSUE TITLE
[CoE Starter Kit - Feature]: Orphaned Resources - Customized Emails 

### ISSUE THREAD

**Issue by miguelverweij** [microsoft/coe-starter-kit#6796]
### Describe the solution you'd like

The orphaned resources flows send an adaptive card to the manager of the former resource owner. THe text is static. WIth emails, we have the ability to adjust the message. It would be nice if the text in the Adaptive Card is also based on an Environment Variable.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
