### ISSUE TITLE
[CoE Starter Kit - BUG] Missing recent data while flows were off

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#6798]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow and App sync isn't bringing any Flows or Apps created or modified after 9/15/23. First, starting 9/15, the driver flow was failing with ExpiredAuthenticationToken. I wasn't aware because there were no error emails and the flows finished Successfully. Then I upgraded to 4.15 (n 9/28) and fixed all of the connections, and the driver flow stopped having errors and started updating the Flows and Apps again. But all of the updates are Flows that indicate that they had been deleted. This is not always the case. But a more serious problem is that the updates don't include any flows or apps that were created or modified after 9/15.

### Expected Behavior

Update the Flows and Apps with the latest new creations and modifications after 9/15/23.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run the Admin | Sync Template v3 (Driver) and examine the Flows and Apps tables.

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/4b505177-81ea-4d33-ae2f-ce246e60ba7b)

![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/3f771fc6-af91-4dcc-a84f-c92366701f25)

**Comment by Jenefer-Monroe** [comment]
To reduce API counts we dont look at all objects to see if they've been modified, we filter to "recent ones". But we control this with an environment variable so you can set it back to when your problems started and this should pick up the missing ones

From [environment variables](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#all-environment-variables)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bf025d51-8f4c-433d-b5db-6cba9ea50af2)

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

Hi Jenefer,

There are plenty of records in the COE that are getting updated, and the changes to the underlying Flows are all much more than the 20 that I put in for the InventoryFilter_DaysToLookBack. But there isn't one new or modified Flow in the last 20 days!

From: Jenefer Monroe ***@***.***>
Sent: Thursday, October 5, 2023 2:07 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6798)


To reduce API counts we dont look at all objects to see if they've been modified, we filter to "recent ones". But we control this with an environment variable so you can set it back to when your problems started and this should pick up the missing ones

From environment variables<https://urldefense.com/v3/__https:/learn.microsoft.com/power-platform/guidance/coe/setup-core-components*all-environment-variables__;Iw!!May37g!K727c2Prids-uHmTb9cIvdaoV1IJbgNblO81O_Qe9ihf8-zIqhlMgOXoWkb8IR8R2sUimXw0dLiLE13wFM8nXEy0GQ$>
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/272999781-bf025d51-8f4c-433d-b5db-6cba9ea50af2.png__;!!May37g!K727c2Prids-uHmTb9cIvdaoV1IJbgNblO81O_Qe9ihf8-zIqhlMgOXoWkb8IR8R2sUimXw0dLiLE13wFM9aveDzzw$>

-

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

Sorry, I forgot my attachment:

***@***.***
From: Kushner, Rick [USA]
Sent: Thursday, October 5, 2023 3:07 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Subject: RE: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6798)

Hi Jenefer,

There are plenty of records in the COE that are getting updated, and the changes to the underlying Flows are all much more than the 20 that I put in for the InventoryFilter_DaysToLookBack. But there isn't one new or modified Flow in the last 20 days!

From: Jenefer Monroe ***@***.******@***.***>>
Sent: Thursday, October 5, 2023 2:07 PM
To: microsoft/coe-starter-kit ***@***.******@***.***>>
Cc: Kushner, Rick [USA] ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6798)


To reduce API counts we dont look at all objects to see if they've been modified, we filter to "recent ones". But we control this with an environment variable so you can set it back to when your problems started and this should pick up the missing ones

From environment variables<https://urldefense.com/v3/__https:/learn.microsoft.com/power-platform/guidance/coe/setup-core-components*all-environment-variables__;Iw!!May37g!K727c2Prids-uHmTb9cIvdaoV1IJbgNblO81O_Qe9ihf8-zIqhlMgOXoWkb8IR8R2sUimXw0dLiLE13wFM8nXEy0GQ$>
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/272999781-bf025d51-8f4c-433d-b5db-6cba9ea50af2.png__;!!May37g!K727c2Prids-uHmTb9cIvdaoV1IJbgNblO81O_Qe9ihf8-zIqhlMgOXoWkb8IR8R2sUimXw0dLiLE13wFM9aveDzzw$>

-

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

It is also very funny that all of these Flows were deleted at exactly the same time that the COE record was updated, when the audit was running:

***@***.***

From: Jenefer Monroe ***@***.***>
Sent: Thursday, October 5, 2023 2:07 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6798)


To reduce API counts we dont look at all objects to see if they've been modified, we filter to "recent ones". But we control this with an environment variable so you can set it back to when your problems started and this should pick up the missing ones

From environment variables<https://urldefense.com/v3/__https:/learn.microsoft.com/power-platform/guidance/coe/setup-core-components*all-environment-variables__;Iw!!May37g!K727c2Prids-uHmTb9cIvdaoV1IJbgNblO81O_Qe9ihf8-zIqhlMgOXoWkb8IR8R2sUimXw0dLiLE13wFM8nXEy0GQ$>
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/272999781-bf025d51-8f4c-433d-b5db-6cba9ea50af2.png__;!!May37g!K727c2Prids-uHmTb9cIvdaoV1IJbgNblO81O_Qe9ihf8-zIqhlMgOXoWkb8IR8R2sUimXw0dLiLE13wFM9aveDzzw$>

-

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

Almost all of these Flows were supposedly deleted, but they were not:
***@***.***

***@***.***

From: Jenefer Monroe ***@***.***>
Sent: Thursday, October 5, 2023 2:07 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6798)


To reduce API counts we dont look at all objects to see if they've been modified, we filter to "recent ones". But we control this with an environment variable so you can set it back to when your problems started and this should pick up the missing ones

From environment variables<https://urldefense.com/v3/__https:/learn.microsoft.com/power-platform/guidance/coe/setup-core-components*all-environment-variables__;Iw!!May37g!K727c2Prids-uHmTb9cIvdaoV1IJbgNblO81O_Qe9ihf8-zIqhlMgOXoWkb8IR8R2sUimXw0dLiLE13wFM8nXEy0GQ$>
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/272999781-bf025d51-8f4c-433d-b5db-6cba9ea50af2.png__;!!May37g!K727c2Prids-uHmTb9cIvdaoV1IJbgNblO81O_Qe9ihf8-zIqhlMgOXoWkb8IR8R2sUimXw0dLiLE13wFM9aveDzzw$>

-

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

Just one more:
***@***.***

***@***.***

***@***.***



From: Jenefer Monroe ***@***.***>
Sent: Thursday, October 5, 2023 2:07 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6798)


To reduce API counts we dont look at all objects to see if they've been modified, we filter to "recent ones". But we control this with an environment variable so you can set it back to when your problems started and this should pick up the missing ones

From environment variables<https://urldefense.com/v3/__https:/learn.microsoft.com/power-platform/guidance/coe/setup-core-components*all-environment-variables__;Iw!!May37g!K727c2Prids-uHmTb9cIvdaoV1IJbgNblO81O_Qe9ihf8-zIqhlMgOXoWkb8IR8R2sUimXw0dLiLE13wFM8nXEy0GQ$>
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/272999781-bf025d51-8f4c-433d-b5db-6cba9ea50af2.png__;!!May37g!K727c2Prids-uHmTb9cIvdaoV1IJbgNblO81O_Qe9ihf8-zIqhlMgOXoWkb8IR8R2sUimXw0dLiLE13wFM9aveDzzw$>

-

**Comment by manuelap-msft** [comment]
Hello,

screenshots don't come through if you reply to issues via email. You'll have to log in to GitHub and append them directly by replying to issue in the comment. 

Thank you
Manuela

**Comment by RickKush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/471342da-421f-4ce2-abbb-958dbfbcea2b)

![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/aae8257c-6fdd-4b7d-847c-eedb8169c951)

![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/98581693-e63b-4e5b-8e22-2497b1572186)

**Comment by Jenefer-Monroe** [comment]
Does the identity running the flow have permanent and direct access to the PP Admin Role?


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2a18a568-39ee-4e95-8bd0-f9e9d89e0ce1)

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

Yes

From: Jenefer Monroe ***@***.***>
Sent: Friday, October 6, 2023 2:58 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Missing recent data while flows were off (Issue #6798)


Does the identity running the flow have permanent and direct access to the PP Admin Role?

[Image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/273308545-2a18a568-39ee-4e95-8bd0-f9e9d89e0ce1.png__;!!May37g!KxG6_Pg9WS7bKZvA0FrfM6kz2JO-91nsVmfFAG26ehtNHb84fNc7yLVDmaEMWWNjYLIPMNwDVXvyFUmnswVJT4wK5w$>

-

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

***@***.***

From: Jenefer Monroe ***@***.***>
Sent: Friday, October 6, 2023 2:58 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Missing recent data while flows were off (Issue #6798)


Does the identity running the flow have permanent and direct access to the PP Admin Role?

[Image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/89584709/273308545-2a18a568-39ee-4e95-8bd0-f9e9d89e0ce1.png__;!!May37g!KxG6_Pg9WS7bKZvA0FrfM6kz2JO-91nsVmfFAG26ehtNHb84fNc7yLVDmaEMWWNjYLIPMNwDVXvyFUmnswVJT4wK5w$>

-

**Comment by Jenefer-Monroe** [comment]
Please try to repro with a new flow
1. Create a new flow in one of your target envts where you are not seeing flows you expect to see. 

2. Turn the flow on and test it to make sure its in the system. 

3. Go to the **_Admin | Sync Template v4 (Flows)_** flow details add find the target envt by adding the envt display name as a column

4. Find the most recent run of the flow for that envt, and open it by clicking on the timestamp
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/baed749b-388f-4844-b68c-fe01a3efe64c)

5. Resubmit the flow and wait for it to complete, then see what happens here:
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/90e81d5e-e3a3-4c18-bc23-c0b48424c352)

6. Does your new flow show up here? If so, find its location in the array 
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fc899914-8164-4256-80e7-33c2c3c7da89)

Please log in to GitHub to respond as its quite difficult to find your responses in your email replies

**Comment by RickKush** [comment]
I followed the steps as listed. I did find my new flow in _List Flows as Admin_  (3fd4a1fa-d674-4de3-8631-8c5d5fb4be40)
I also found my flow in Filter out unpublished flows, but my new flow was missing in CurrentFlowInventory.  (See attached txt files.)
It was also missing from _List inventory flow with estimated suspension_. And it was not added to the Flows table in the COE environment.
[CurFlowInven.txt](https://github.com/microsoft/coe-starter-kit/files/12857729/CurFlowInven.txt)
[FilterUnpub.txt](https://github.com/microsoft/coe-starter-kit/files/12857730/FilterUnpub.txt)
[ListFlows.txt](https://github.com/microsoft/coe-starter-kit/files/12857731/ListFlows.txt)

**Comment by Jenefer-Monroe** [comment]
Thats expected to not be listed in Current inventory or estimated suspensions. 
Assuming you are not doing a full inventory new flows should show here and they do for me I just tested:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cfbbc30f-9fed-404d-8663-f9a84f0819dc)

What do you see for the Get past time call here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ede57240-6f41-4564-bb08-42c476337804)

**Comment by Jenefer-Monroe** [comment]
ok it looks like the connection for this flow broke. You can see that here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cf294b97-7116-4c37-85e0-99560379f6d6)

You will need to fix the connection which you can do from here if you are logged in as the user running the flows
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2d613696-a4fd-4cfb-909c-06a1c5a724d7)

**Comment by Jenefer-Monroe** [comment]
Are you able to fix up the connection?

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

Done, and tested.

Thanx!!!

From: Jenefer Monroe ***@***.***>
Sent: Wednesday, October 11, 2023 3:59 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Missing recent data while flows were off (Issue #6798)


Are you able to fix up the connection?

-

**Comment by Jenefer-Monroe** [comment]
Wonderful news! I'll go ahead and close then but please do return if you have other issues in the future.
