### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION How to use a service account for the CoE Starter Kit

### ISSUE THREAD

**Issue by StephenUstinov** [microsoft/coe-starter-kit#6799]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Manuela mentioned in the video below that the CoE Starter Kit can be configured with either a named account or a service account. Could you please let me know the technical details for this service account. Is it an application user or something else? Thank you 
https://www.youtube.com/watch?v=Lsooi7xp6eA

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

you can't use an app registration or service principle today to use the CoE kit, as not all of the connectors we use support authentication with a service principle.

Typically, customers use a named account with a "service name" to install the CoE kit - e.g. "CoE Admin". It's the same as a named account, but it's not tied to an "real" employee. The benefit is that if the employee leaves the organisation or changes jobs/moves to a different department, the "named service account" can be handed over easily and you don't have to go through the trouble of changing ownership on all resources etc. 

Hope that makes sense,
Manuela

**Comment by StephenUstinov** [comment]
Thank you for getting back to me on this.
Our InfoSec team only permits the creation of named accounts with admin roles such as the "Power Platform Role" with PIM in place. According to the [following article](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with) "it's not sufficient for the admin access to be granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management)."

Can you think of a workaround?

**Comment by StephenUstinov** [comment]
Do you think the following could work? Thank you

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/gabor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/gabor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Account   Name | CoE Admin | CoE Connection
-- | -- | --
Purpose | Deployment / Upgrade of the CoE   Kit | Creation of the connections
Privilidge | Environment Admin | Power Platform Admin
Access to Account | Permanent Access | Temporary     Access to the account's password.     Weekly password reset



</body>

</html>

**Comment by Jenefer-Monroe** [comment]
I'm afraid I don't follow this suggestion so I'm not sure I can advise. A single account is all that is needed from our experience so I'm not sure how a second account would help get around the requirement. Happy to hear more but off the top of my head I think this will not help

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
