### ISSUE TITLE
[CoE Starter Kit - BUG] New Environment Request applications

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#6803]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team

As you confirm on ticket no.  #6774 you are going to fix an issue related to Maker/Admin- Environment request app loading issues. 
We Deployed the latest version 4.16 but in this release, we are not finding any new app related to maker /admin - Environment Request. can u please check this on priority?

Also, old apps showing as deprecated. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Maker - Environment Request.

### What method are you using to get inventory and telemetry?

None

**Comment by manuelap-msft** [comment]
Hello,

- the Maker - Environment Request app has been replaced with custom pages that were added to the **CoE Maker Command Center**
- the Admin - Environment Request app has been replaced with the **CoE Admin Environment Request** model driven app

We're still in the process of updating our documentation to document the new apps there.
