### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL PBI Dashboard Oct'23 - Column 'ID' in Table 'Power Virtual Agent bots' contains blank values 

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#6804]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
the BYODL_Dashboard.pbi of October 2023 versions fails in the initial configuration with this error:

Power Virtual Agent bots
Column 'ID' in Table 'Power Virtual Agent bots' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. (ID (513)).

I replaced the dataflow with the October version and it's working fine.

I tried to configure the BYODL Dashboard September version and works fine .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2023

### What app or flow are you having the issue with?

BYODL_dashboard

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Sometimes there is data corruption in a data set that makes the PBIs be blocked. 
In this case it sounds like something the **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_** flow should keep tidy for you. Can you please go make sure its turned on, running, and passing? 


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/308d0bfd-10f1-4e9d-b072-547388d9000d)

**Comment by albertocastro365** [comment]
Hi Jennefer,
I have this flow running OK.
I have this issue in my Test environment, curiously in PROD not.
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/7a1d0fb4-4006-4d90-be96-27375c02cb40)

**Comment by Jenefer-Monroe** [comment]
It indicates some data corruption in one of the tables. So you will need to find that in the table. I'm not sure what the issue is but its likely that there is a row with a blank Bot id in one of the PVA table
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c8fc740d-f87f-47d1-98f5-df514e106ae6)

**Comment by albertocastro365** [comment]
Yes, Jennefer, I don't found the reason, but I had old data in PVA Bot table. After to delte the rows wrongs , the .pbit loads ok.
Thank you so much for your guidance.
