### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit log table data operation

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#6805]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi CAT team,

Could you please provide info on following questions in related to audit log data at COE kit?
1. **What are the info taken from the audit and logged to COE audit log table?**
I see there are some columns starting with admin_ might be the columns to store the data after running : Admin | Audit Logs | Sync Audit Logs (V2), but after testing, I found only APP ID and User UPN are loaded to audit log table, can you confirm the only data pulled from audit to audit log table are **APP ID and User UPN?**

2. How long the data is kept in the dataverse? Is it permanent ? 
3. Is there a cleanup process is in place? Or we need to develop the customed cleanup process ?
Thanks in advance!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2023

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

1. The data that we log is Session ID, Creation Time (Launch Time), App ID, Operation (Audit Log Event), User ID and Workload.
2. Yes, data is kept permanently. You can decide how long you want to keep data for based on your audit and reporting requirements - for example, the Power BI dashboard provides year-over-year and month-over-month reporting based on this data. It's up to you to decide how far back your reporting needs go.
3. There's no clean up process in place. I'd recommend setting up a Bulk Delete process.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by SOMSGH** [comment]
> Hello,
> 
> 1. The data that we log is Session ID, Creation Time (Launch Time), App ID, Operation (Audit Log Event), User ID and Workload.
> 2. Yes, data is kept permanently. You can decide how long you want to keep data for based on your audit and reporting requirements - for example, the Power BI dashboard provides year-over-year and month-over-month reporting based on this data. It's up to you to decide how far back your reporting needs go.
> 3. There's no clean up process in place. I'd recommend setting up a Bulk Delete process.

Thanks for the valuable info!
