### ISSUE TITLE
CustomAzureDevOps.getpipeline returns 0 count but we have 41 pipeline available

### ISSUE THREAD

**Issue by JDIppsawant** [microsoft/coe-starter-kit#6808]
### What is your question?

We have newly setup a ALM accelerator app and it is setup successfully.
so when i try to commit the solution i am getting below error msg.
![Capture](https://github.com/microsoft/coe-starter-kit/assets/117742698/0ba9402e-5bfa-435e-99dd-c3614daa0e08)

but when i try with my managers account it is getting committed

Can any one suggest when to look for 
i also tried testing 
CustomAzureDevOps.getPipeline which retuen 0 count 
but for my manager it returns 41 count 
![image](https://github.com/microsoft/coe-starter-kit/assets/117742698/c58ae5c4-6e57-40a3-a7cb-ed42b7d5e951)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

October 2023

AB#320

**Comment by JDIppsawant** [comment]
Can any one please provide any comments

**Comment by mikefactorial** [comment]
@JDlppsawant pardon the delay. Seems to be a permissions issue in Azure DevOps. Are you able to see the export-solution-to-git pipeline in the project in Azure DevOps?

![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/1d97a979-6c25-4181-a619-0c80e06fbd37)

**Comment by JDIppsawant** [comment]
@mikefactorial   Can you please suggest me ahead
What to check after the export-solution-to-git

**Comment by JDIppsawant** [comment]
Can anyone please suggest on this issue

**Comment by RajeevPentyala** [comment]
@JDIppsawant Apologies for the delayed response. Can you please provide us following details?

- What Dataverse security role you are having?
- Can you connect to the Azure DevOps project from browser, and in a new browser tab hit this URL."https://dev.azure.com/{organization}/{project}/_apis/pipelines". Replace '{organization}' and '{project}' accordingly. 
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/9aec4bb0-e96b-43b7-afc5-021946155ed9)
- Above URL should give the list of pipelines you have access to.

**Comment by JDIppsawant** [comment]
@RajeevPentyala RajeevPentyala
What Dataverse security role you are having? 
- Environment Maker 

Can you connect to the Azure DevOps project from browser, and in a new browser tab hit this URL."[https://dev.azure.com/{organization}/{project}/_apis/pipelines]

I am able to get the count 44 and list of pipelines

however, if i try to do the same thing with custom connect method "GetPipeline"
then i get 0 Count

![image](https://github.com/microsoft/coe-starter-kit/assets/117742698/8a847bc8-a38c-4a3a-b1fb-69ac6e4b320f)

**Comment by MaheshSripada** [comment]
Hi @JDIppsawant 

For accessing the features of the ALM, users should also be assigned with below security roles 
ALM Power App Access and 
ALM Power App Deployment Configuration.

Only Environment Maker role is not sufficient.

**Comment by RajeevPentyala** [comment]
@JDIppsawant Trust, you have got the necessary details. I am now closing this issue. Please feel free to reach out if you require any further assistance.
