### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Flows deleted/missing in October Update

### ISSUE THREAD

**Issue by ribackdulux** [microsoft/coe-starter-kit#6812]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

when trying to enable/access the request orphaned objects reassigned (parent and child) flows, the flow manager says the flows have been deleted. see screenshots attached
![Screenshot 2023-10-09 141553](https://github.com/microsoft/coe-starter-kit/assets/139734115/8cb4033b-8044-41fa-ba0e-2606ba088ca2)
![Screenshot 2023-10-09 141615](https://github.com/microsoft/coe-starter-kit/assets/139734115/11515d04-c513-473b-bc28-040eedb50a6a)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent & Child)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

these flows are part of the Governance components solution. Can you share a screenshot of your solution page to show that you have installed that solution? Can you open the solution to show the flows that are there? 

Possibly it's just the link from the Command Center that's going to the wrong page here. 

Thank you
Manuela

**Comment by Jenefer-Monroe** [comment]
Note also that this screen is to check on the status of flows you are already using. If you are turning a solution area on for the first time its highly recommended that you use the **CoE Setup and Upgrade Wizard**. 
This will walk you through any the order the flows need enabled as well as any other environment variables or features available.. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d7901e1e-4c2a-442a-ba27-dfbeb62332bb)

**Comment by ribackdulux** [comment]
Thanks team.

I can confirm the solution is installed:

[cid:ed6a2168-8f2f-4ddf-a7f9-3ad488a83063]

Also, I think you are correct where it is just the link to the flow from the command center, as when i went looking inside the solution, I found the flow and it was working. I will try the upgrade wizard to see if it fixes the linking issue.

[cid:b4c123b7-5c11-4e93-b99c-f9a55a3170f0]

Thank you!


Ryan Riback​​​​
M365 Power Platform & SharePoint Specialist
Information Technology & Digital Enablement

***@***.******@***.***>
1956 Dandenong Road     ,       Clayton ,       Victoria        ,       3168    ,       Australia
www.duluxgroup.com.au<https://www.duluxgroup.com.au/>

[cid:caebc70a-6610-4141-a2fb-b61ec99d1426]
________________________________

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
