### ISSUE TITLE
[CoE Starter Kit - BUG] App Environment Display name is blank in PowerApps table

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#6814]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

We have noticed that in our COE Dataverse PowerApps table, **App Environment Display name is blank** for many of the apps. All our COE BYODL dataflows are running successfully. Could you please help us on this issue.

### Expected Behavior

App Environment display name should contain app environment value.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

PowerApps table

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Dataverse powerapps table- App Environment display name contains blank value for many of the apps list.

**Comment by Jenefer-Monroe** [comment]
I dont repro this so I'm not sure what you could be experiencing. Please go to the Dataflows outside of the solution and open the apps one in Edit

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d5c7e68c-e865-4224-bb34-d43895cbbb33)

Select the Apps Query and go to the Expanded Environments step. Do you see the display name there? Do you see the other envt properties?

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2ea97a7c-c072-46b2-8fcb-d1ffab6bc4a2)

**Comment by ALSPowerPlatform** [comment]
We can see null values in Environment display name
<img width="792" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/5c6fdbd0-2e5a-4a15-9577-44c08519e508">

**Comment by ALSPowerPlatform** [comment]
We also see the the Flag App Shared is Tenant is having incorrect data. Please assist us as we are not able to rely on the data present in the PowerApps table

**Comment by ALSPowerPlatform** [comment]
We have checked in all the data flows and the Environment API variable is updated with our COE environment.

<img width="611" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/1ebf4b6b-f944-4f7d-a61f-1047760193a4">

**Comment by Jenefer-Monroe** [comment]
ok so in that same dataflow then I presume you also see null for the display name here correct?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2f9ee141-d4ad-4745-b79a-ffd788f60b6a)

Next please go to the environment dataflow and see if the display name comes through in the spot shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7255abb1-053a-4cd2-847f-b09a06701d9f)

**Comment by ALSPowerPlatform** [comment]
cannot see the Environment display name column here in BYODL Apps Dataflow.
<img width="806" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/abfb7bd6-0fd7-42c0-b22c-0375dbbd13a7">


In Environments dataflow:
<img width="790" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/107b8e19-0aad-455d-92e3-693804d4b897">

**Comment by Jenefer-Monroe** [comment]
ok you are missing the display name in the step shown
I know we fixed some issues for missing fields like this recently, may have been for the Oct release. So you can local fix by adding it until you upgrade again.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/396a1c9d-9611-4a0a-8958-5a68c7d97b1a)

**Comment by ALSPowerPlatform** [comment]
Have updated the admin display name as suggested, but still after the dataflow is run successfully, we see env display name is blank for 800+ apps.

<img width="797" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/239120a4-8d5d-406e-844a-e24edcde40cc">

**Comment by Jenefer-Monroe** [comment]
Are they blank in Environment table? You can see this in the Power Platform Admin View app
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/15a90522-74c1-43df-ad51-15fe76fdcd5b)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
