### ISSUE TITLE
[CoE Starter Kit - QUESTION] Upgrade failed after following instructions in Issue #6018

### ISSUE THREAD

**Issue by holocene319** [microsoft/coe-starter-kit#6816]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have followed the instructions documented in [Issue 6018](https://github.com/microsoft/coe-starter-kit/issues/6018).

This includes removing the delegate permissions on the Azure app registration, deleting the newer version of the solution (which represents an upgrade attempt), deleting the O355Mgmt connection reference that appeared in the Default Solution and trying again.

However, I still get a similar error message to the first one I received which corresponded to the screenshot in Issue 6018.

![CoE-UpgradeErr2](https://github.com/microsoft/coe-starter-kit/assets/6861736/e3ff6b69-4437-4803-85dc-d910f7d0bf70)

It seems to be referring to API connections still configured. Where should I check for these connections, please?

Do I need to delete "Center of Excellence - Governance Components"? I think this is needed for the Inactivity Notifications process.

Please could someone advise how to clear the error so I can upgrade CoE?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Solution

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

you don't have to delete the Governance components solution - that one does not connect or use the custom connector. Likely you just have leftover connections that still connect to the custom connector.

Can you download the log from the error message - it should show you the exact connection name you're looking for to delete?

Here's what helped some customers.
1. Open the Default solution > Connection References > look for connection references to the Office 365 Management API there
2. Switch to classic experience and delete remaining connection references from there

**Comment by holocene319** [comment]
Please find a screenshot of the log attached, I had a look in the Components sheet but couldn't find anything for connections in there:

![CoE-UpgradeErrLog](https://github.com/microsoft/coe-starter-kit/assets/6861736/a7e56cdb-f863-4a1a-803a-8f9b614bcc31)

I switched to classic when looking at Default Solution and still can't see anything for Office 365 Management API under connection references:

![CoE-ClassicDefaultSolution](https://github.com/microsoft/coe-starter-kit/assets/6861736/0f58e41f-21b8-49dd-8a03-c5983c077b4f)

I deleted the connection reference on the second attempt to upgrade and it hasn't reappeared since.

**Comment by manuelap-msft** [comment]
If you look at the components tab on the Excel spreadsheet of the log, does it give you more details like a connection name of what is still a dependency?

**Comment by holocene319** [comment]
When searching for "Office 365 Management", there are three components of type 'Workflow' and 'Workflow Activation' that have the name "Admin | Audit Logs | Office 365 Management API Subscription". Should I delete these from the current version of the core solution before trying to upgrade again?

**Comment by holocene319** [comment]
I tried again but got the same error. I've navigated to custom connectors in Power Apps to manually delete but I get an error saying there are still connections. How do I find out where these connections are so I can delete them, please?

**Comment by Jenefer-Monroe** [comment]
If you open the error download again and look at the second sheet you will likely see either a failure or a first "unprocessed" which will point you to the issue.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6f5a1234-03fd-4148-9249-2c6f7a3711cf)

**Comment by holocene319** [comment]
There are no failures, only Unprocessed:

![CoE-UpgradeErrLog2](https://github.com/microsoft/coe-starter-kit/assets/6861736/1d75f10c-5be9-43ee-baad-607a53c971bd)

I checked "Audit Log Wizard>Start Audit Log subscription" but it only has a Dataverse connection. Nothing else on the list seems to be relevant for Office 365 Management API connection.

Do I need to reinstall from the beginning?

**Comment by Jenefer-Monroe** [comment]
I'm not sure, the instructions have worked for other people. 
Are you still in the state where you have both Core and Core_upgrade installed? I would suggest walking the steps of https://github.com/microsoft/coe-starter-kit/issues/6018 again starting with deleting that _upgrade. 

You are trying to convert to the http methodology yes?

**Comment by holocene319** [comment]
The http methodology was up and working for me from version 4.16. I delete the Core_upgrade solution every time the upgrade process fails. It failed for me for the August and September releases but I thought I'd wait until the next release. Now it seems I'll have to delete everything and start from scratch :/

**Comment by holocene319** [comment]
Do you have any advice on where I might look for these flagged connections, please?
![CoE-UpgradeErrCC](https://github.com/microsoft/coe-starter-kit/assets/6861736/a69ff784-b802-4031-a796-436e8f0c5d31)

**Comment by DominicMeznik** [comment]
Hi, you should be able to find the connection here

![image](https://github.com/microsoft/coe-starter-kit/assets/109345362/150a67df-6ea6-42ac-a696-255331ce1ebf)

**Comment by Jenefer-Monroe** [comment]
You may have to explore with PowerShell, perhaps it will show some that are being hidden by the UX.

**Comment by Jenefer-Monroe** [comment]
Since many people have hit this, added the following to the pinned bug  https://github.com/microsoft/coe-starter-kit/issues/6018

Some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use  powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest)  these remaining connections to the old connector.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
