### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL Governance inventory issues in clean CoE installation

### ISSUE THREAD

**Issue by ekdegerman** [microsoft/coe-starter-kit#6818]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I recently completed a fresh installation (September 2023) followed by an upgrade (to October 2023) of the CoE in a new, clean environment and ran into some issues related to the inventory where the numbers in the the **PowerPlatformGovernance_CoEDashboard** report (which I understand from the documentation is supposed to be used for both CoE versions) are not matching the numbers in the **BYODL CoE Dashboard** report, and in some cases appear as blank. 

For flows, the **Compliance and Governance Insights** page of the governance report started with a reasonable amount of Flows directly after setup but was gradually going down to just a few remaining ones when refreshed a while later. When looking at the data, I could see that most flows were getting connected to our "from preview" legacy environment instead of the default one. Issue #5744 pointed me towards the **CoE BYODL - When Flow dataflow refresh is complete** flow, which I found was marking them all as deleted as they could not be found in the legacy environment. I also looked at the **CoE BYODL Environments** dataflow itself as suggested in that thread and found what looks to me like a logical error. To my understanding, the **Filtered rows** step is supposed to remove the legacy environment from the result, however, it uses two **not** statements with an **or** in-between them and as a result nothing gets filtered out: 
![image](https://github.com/microsoft/coe-starter-kit/assets/56835119/04a52c39-1b92-48cc-a2c4-91f3747a7312)
I tried changing it to **and** instead and this seems to have resolved that particular issue for me. The default environment flows are now connected to the default environment as expected and remain in the count even after the flows run. Of course the ones that actually do belong to the preview environment are now considered deleted, since they too are considered as default environment flows, but as I understand the documentation this is the expected behavior due to those environments having the same environment ID? 

In addition to the failing calls for legacy environment flows, flows and apps belonging to the CoE environment itself are getting **forbidden** errors in these post dataflow refresh flows (see example below). Below is an example for one of the Flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/56835119/225d17b4-2d56-4374-aa8e-a8c9916f1de7)
Is this to be expected? The account used for the connections is the same one used to set up the entire solution in that environment, and it has a permanent direct assignment of the power platform admin role...

A lot of the visuals in the **Adoption insights** and **Default environment** pages still remain empty. The app counts for the default environment still seem to fail to identify the default environment so I may have a remaining environment issue somewhere. I can see numbers for **Apps with no owners** and **Apps shared with everyone** if I uncheck the environment type and I do see matching lines if looking Table View and filtering on all those values. App usage data on these pages seem to be looking for audit information, that to my understanding shouldn't be needed for the BYODL version since that is managed by the data export? Are all visuals in this report expected to work with BYODL alone or do some of them depend on the older flow based version that has long been too heavy to run in our tenant?  

We also seem to be hitting the same issue with an empty inventory of desktop flow that is mentioned in #2102, but I understand this is already pending development from the product team...

### Expected Behavior

Matching numbers across the dashboard and governance reports, containing a complete inventory from our tenant

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard and dependencies

### What method are you using to get inventory and telemetry?

Data Export

AB#918

**Comment by Jenefer-Monroe** [comment]
i believe this was completed with today's release and we just lost this bug.
