### ISSUE TITLE
[CoE Starter Kit - BUG]: Gov Flows are sending to end user

### ISSUE THREAD

**Issue by samadane** [microsoft/coe-starter-kit#682]
**Describe the bug**
Approval flows are sending to end users because prod variable is getting equated incorrectly. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Governance
 - Version 1.61

**To Reproduce**
Look at gov solution 1.61
Run the archive and cleanup v2 (start approval for flows)
Env variables should point to Prod being No and have an admin email
When reading in prod variable it is being set to a string (False):

![image](https://user-images.githubusercontent.com/43175066/123108170-2de8f200-d408-11eb-9e9f-82a4479ec476.png)

The get assignee step should list isProd "is equal to" False (or don't use a string variable) but it is being equated to 'no'
![image](https://user-images.githubusercontent.com/43175066/123108565-84eec700-d408-11eb-9112-f1b5cb21c43e.png)

This causes the flow to send to end users. 

**Expected behavior**
users should not get email or approvals if Prod env is set to NO

**Comment by JeneferM-MSFT** [comment]
Thank you for posting with such clear notes, I will investigate

**Comment by JeneferM-MSFT** [comment]
Yep when we switched the way we read these parameters in to match some product changes, it changed these from strings (Yes, No) to bool (True, False) but flow doesnt treat them exactly like bools, and we forgot to update the condition anyway. 

Thanks so much for the great investigation. Made fixing this for July possible.

**Comment by samadane** [comment]
I would make sure to check this for all the flows as well.

**Comment by JeneferM-MSFT** [comment]
Do you mean in the Start Approvals for Flows one? If so, yep it reprod in both and is now fixed in both.

**Comment by samadane** [comment]
> Do you mean in the Start Approvals for Flows one? If so, yep it reprod in both and is now fixed in both.

Yes

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
