### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#6821]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Just completed an upgrade from 4.2.2 to 4.15 successfully but there is an error on the CoE Dashboard when it refresh
Dataset error: 
Data source error: The 'admin_haspcfenabled' column does not exist in the rowset. Table: Environment.

Email received: 
![image](https://github.com/microsoft/coe-starter-kit/assets/133137665/1f676919-6fe5-412c-a670-04fd7dba67d6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

CoE dashboard/Power Bi Refresh

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Error after upgrade from 4.2.2 to 4.15

**Comment by Jenefer-Monroe** [comment]
You will need to update to the current version of the PBIT file as well. This field was changed from a boolean (admin_haspcfenabled) to a tri-option column (admin_pcfenabled)

Generally speaking you will always want to update the PBIT file when you upgrade, although sometimes it may not be absolutely needed.

**Comment by RyanCloud8888** [comment]
> You will need to update to the current version of the PBIT file as well. This field was changed from a boolean (admin_haspcfenabled) to a tri-option column (admin_pcfenabled)
> 
> Generally speaking you will always want to update the PBIT file when you upgrade, although sometimes it may not be absolutely needed.

Thanks a lot, Jenefer.
Are there steps or documents on how to update the PBIT file?

**Comment by RyanCloud8888** [comment]
Thank you, Jenefer.
I never done that before.  Is this the right document for it? https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi

**Comment by RyanCloud8888** [comment]
That seems to do it.  Jenefer but I'm lost where "**Configure embedded apps in the CoE dashboard**"

![image](https://github.com/microsoft/coe-starter-kit/assets/133137665/9a851537-96bb-4afd-8aa5-e2bb63bdb65c)
