### ISSUE TITLE
[CoE Starter Kit - BUG] Sync flows for apps / flows not running daily as in v3 version.

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#6822]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

I observed that sync flows for flows and apps are not running daily. In connection to that I can observe that some apps are not synced in CoE. Also apps and flows sync flows are not syncing data from all environments.

Example:

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/f68cf130-4945-4a3d-ae20-29f1dda7a4b2)
![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/3b4f17d8-3b63-45a0-8cd8-a01c00a6f5f4)

Sync flows:

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/7355330b-8fc7-4b41-86e6-22a5940a25fe)
![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/4d14f96f-6a1e-46a8-bdb0-9241da0c57f8)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows/Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello it looks like either there is something wrong with your permissions or your envt for triggers.

Can you please validate, has the **_Admin | Sync Template v3 (Driver)_** flow been turned on, running and passing? It should run every day
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6813cfdc-bcd9-47e3-ac60-2872c156da40)

If on, running, and passing. Go to the most recent completed run and look at the output of the **_Get Environments_** call. Is it all the envts you expect from your tenant? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fd5bb68b-169b-423e-b9f9-a242c2ee0def)

**Comment by BartoszKaminski1999** [comment]
Hello,

Thanks for help, this flows was turned off.

Regards
