### ISSUE TITLE
[CoE Starter Kit - BUG] Action Limit Hit for Admin | Sync Template v3 (Flow Action Details)

### ISSUE THREAD

**Issue by swoodhousecoop** [microsoft/coe-starter-kit#6824]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi, we updated to the September release on the 26th (a bit late) and a few days later on the 4th we were sent a notification that stated that the flow was going to be turned off for performance related reasons:

> Performance alert
> Your flow may be performing slow because it's running more actions than expected. Your flow will be turned off in 7 days if it does not use fewer actions.

According to the banner on the flow page, this will be turned off if the flow does not use fewer actions. I'm aware that the October release has just come out and we will be looking to update probably next week; though I don't see anything in the release notes that will potentially sort this.

Interestingly the flows are failing in certain areas due to trying to add permissions using a child flow, but I can't see that the flow it is trying to trigger actually exists, I don't _think_ that's relevant as the warning is about the number of actions, not due to repeat failures.

I'm not sure what else is helpful here, most of the runs are less than a minute, other than some of our larger environments such as default which is taking 8 or more hours to run.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Nothing to re produce, is just a daily flow, it is failing due to what I think is a different issue. But runs successfully on most environments. Just a warning about performance

**Comment by Jenefer-Monroe** [comment]
Hello., This is a heavy API flow, if its failing to call the child flow its possible that the retries are making you hit the throttle limit but not likely. 
Regardless of this flow though you will certainly want all helpers to be turned on. In this case the helper is **_HELPER - CloudFlowOperations_** 
Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
