### ISSUE TITLE
[CoE Starter Kit - BUG] Complince process not working 

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#6825]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have set criteria in the compliance process. but still not no any notification and alert.

image

image

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

 CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

None

AB#197

**Comment by Jenefer-Monroe** [comment]
Hello your images did not come through, can you please try again? Note that you will need to be logged in to GitHub to share images, you cannot respond in email with them.

**Comment by sunilmhatugade** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/74c5ad8d-a397-439c-b88e-ca90af452e14)
![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/6fb83e05-1b41-4be7-b894-d12e0f778f32)
 

Please check attached screenshot ..

**Comment by Jenefer-Monroe** [comment]
Have you turned the feature on with the setup wizard? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7e174fba-956f-49c0-9bcd-9861145b2f78)

**Comment by sunilmhatugade** [comment]
Yes We already configured this feature.

**Comment by Jenefer-Monroe** [comment]
The feature looks at the current values in the inventory for shared count, 

Please browse to the app in the PPAdmin View app and see if its current for shared with list
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5a8e558e-2684-47d2-ae49-a4815e9943b0)

If not, trigger a run of **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_**. Its long running so only runs every 2 weeks by default.

**Comment by sunilmhatugade** [comment]
Hi Team 

We have run CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) flow . but still mails not trigger for business justification... 
![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/fa408d42-5a7a-4156-b353-46414e64ddd1)

In admin View app values also reflected app shared with how many users.. but still complinece process not yet started. 

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/84f3fb93-458b-4908-9e46-975d07c79bba)

Please find below snap .. what complience process we set.

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/985cf30e-c44c-46dc-aa0d-20dd382035a2)

if the notification not triggered to user .. then user know .?
also, can we set restrictions to share app. App can be share with 20 users only.. otherthan 20 not allowed.

**Comment by Jenefer-Monroe** [comment]
Please browse to the app in the PPAdmin View app and see if its current for shared with list
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5a8e558e-2684-47d2-ae49-a4815e9943b0)

**Comment by sunilmhatugade** [comment]
Please check my previous comments.. I already shared snap with you. . I asked some questions in that comment..please check ...

This value is showing in Admin view app. But maker doesn't get any notification related to this ..

**Comment by Jenefer-Monroe** [comment]
And when did the **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_** flow last run?

**Comment by sunilmhatugade** [comment]
Yesterday

**Comment by Jenefer-Monroe** [comment]
Please open that run and check the following

1. Is the envt for your target app returned here? If so, find its iteration in the array
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/db32f32a-4c6f-4902-9453-696319520b86)

2.  Find that envt in this first loop, then find the app in this array and find its item in the second loop
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b9f0daa1-8a9c-48ed-9c77-eb6487497fb3)

3. Does it go down this path as expected?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4427c1a9-e7aa-4415-b54d-4b69ab57e3ad)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
