### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Apps - Entity 'admin_app' does not exist

### ISSUE THREAD

**Issue by uzma-fis** [microsoft/coe-starter-kit#6826]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Patched upgrade Aug 2023 toolkit with no issues in a dev environment 

Seeing many errors with the following flow. 

SYNC HELPER - Apps
![image](https://github.com/microsoft/coe-starter-kit/assets/141040714/a89a336e-da2b-4ebf-a37c-55d9733e04ea)

Last 7 days stats
![image](https://github.com/microsoft/coe-starter-kit/assets/141040714/4305c809-617b-480b-a676-6a7ac77baea0)

Why is this happening and what do we do to resolve errors?

### Expected Behavior

Should not fail

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Check command center admin
Flows errors

### Anything else?

Nothing

**Comment by Jenefer-Monroe** [comment]
In your failing flow, please go to the Get Owner Information section. 
What do you see an input to the call to Maker Check
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/58007010-7712-4e8b-819e-788e2cac3460)

**Comment by JimmyHang** [comment]
Hi, 

I've done a bit investigation about this issue. And as it turn out the '"admin_Maker' With Id = "" Does Not Exist"" is "SYSTEM" account, and "SYSTEM" is not a "real" account  and the flow action fails. I've documented my findings in a my blog here:

https://hangconsult.com/2023/10/11/power-platform-coe-sync-helper-apps/

**Comment by Jenefer-Monroe** [comment]
I believe you guys are experiencing this issue: https://github.com/microsoft/coe-starter-kit/issues/6778
In which Microsoft started deploying a solution with a new SYSTEM user ID to tenants. Matches 

By happenstance we recently changed the way we identify SYSTEM users in the kit so this should not repro for you when you upgrade. 
If you are on 4.13 other users said it doesnt repro there either. Please check to make sure you dont have unmanaged layers on any of your flows especially these:
- HELPER - Maker Check
- SYNC HELPER - Apps
- SYNC HELPER - Cloud Flows
- Admin | Sync Template v4 (Apps)
- Admin | Sync Template v4 (Flows)

**Comment by Jenefer-Monroe** [comment]
Great I'll go ahead and close as a dupe.

**Comment by uzma-fis** [comment]
Thanks for the update - Our Prod that needs patching has the issue, UAT that is 4.13 does not so will upgrade!
