### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why Cloud Flow usage report is missing?

### ISSUE THREAD

**Issue by annsarP** [microsoft/coe-starter-kit#6833]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello! We noticed that Cloud Flow usage report is missing form Production_CoEDashboard_October2023 dashboard. I was trying to find some information in the release notes but couldn't find anything. 
Expected view:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/0e1f3d13-95e9-432a-b587-630b5e41390f)

Current view:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/b02bfba9-19cf-4e08-9c6f-314ed3f5a5c1)

We are using data gathered from cloud flows report, not BYODL one (is it the reason?).

### What solution are you experiencing the issue with?

None

### What solution version are you using?

October 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

that's correct - cloud flow usage information is only available if you use Data Export / BYODL as a source for inventory and usage information.

Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
