### ISSUE TITLE
[CoE Starter Kit - BUG] Solution Upgrade action failed after import as holding. Dependencie: admin_sharedcommondataservice_a3c3f

### ISSUE THREAD

**Issue by BroxCJ** [microsoft/coe-starter-kit#6834]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to update Core from version 4.15 (September) to 4.16 (October), and founf this issue:

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataservice_a3c3f, Id: 6fea1b3b-b6f1-4b3e-8ca8-8a194a15d01c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: GetSolutionSecurityRoles, Id: 5ef40ef8-5a51-ed11-bba1-000d3a9c423b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

I also tried to remove the dependecie (rollback the version 4.16, and later in default solution, remove the connectionreference), but the button to "delete" is disabled, it has a dependency with Flow "GetSolutionSecurityRoles". So, I can't remove that flow too......another reference.....

So, now, I'm not sure if I have to keep on going upwards on each dependency (ALM Accelerator in this case), or might be needed to update first ALM instead of Core.

Thanks.

### Expected Behavior

Upgrade succesfull.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Installation

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1st - Go to COE Environment
2nd - Get the October 2023 COE Toolikt
3rd - Install the Core Solution.
4th - After a long while (40 mins?). Error appears.

**Comment by manuelap-msft** [comment]
Hello,

GetSolutionSecurityRoles is not a flow that's in the CoE kit - it's likely a flow in a different solution in the same environment, that has taken a dependency on a connection reference in the kit. Your best path forward is to find that flow, and change all the connection references in that flow to new ones that are not related to the CoE kit at all. Our overall recommendation is to not use connection references across solutions as that can lead to dependency issues. Once you've updated your GetSolutionSecurityRoles flow, the upgrade should work. 

Manuela

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
