### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot Upgrade Core Components from May Hotfix Version

### ISSUE THREAD

**Issue by michael-wright-pwc** [microsoft/coe-starter-kit#6836]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When we try to upgrade our CoE Core Components solution from its current version (May Hotfix) to any other version (June, July, September, etc.) we are getting this very strange error message right at the end of import:

Error Code: 8004801E - `Solution "Center of Excellence - Core Components" failed to import: Model-Driven App is missing required components uniquename : admin_PowerPlatformAdminView. Please include the App with required components.`

I've tried it several times now upgrading to several different versions (including the very next version - June) and always either get the above error message or the more generic:

Error Code: 80072031 - `The status for this operation is unavailable, please try again.`

We are running version 1.0.20230727.2 of the Creator Kit, have ensured all unmanaged layers are removed, and can verify our "Power Platform Admin View" app currently opens/works fine.

### Expected Behavior

Solution should upgrade successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Core Components solution upgrade

### What method are you using to get inventory and telemetry?

Cloud flows

AB#199

**Comment by Jenefer-Monroe** [comment]
I've never seen this error before unfortunately and people have been successfully upgrading so it seems something happened in your tenant. 
I'm not sure what this is referencing. Perhaps the site map? Do you see it there in the context of Core solution?


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bcec523f-ad18-4d9e-bb94-d1a6bffc5d6e)

**Comment by michael-wright-pwc** [comment]
"admin_PowerPlatformAdminView" exists as the logical name for both the model-driven app & site map with displayname "Power Platform Admin View". My team has spent several hours troubleshooting this without success. Any other ideas to try / things to check?

**Comment by Jenefer-Monroe** [comment]
Did you validate that these were included in the solution? Perhaps they someone got taken out and are just in Default Solution? 
I'm really not sure here as I've never seen this before.

**Comment by michael-wright-pwc** [comment]
Yeah they're both in the current core component solutions v. 4.8.

**Comment by Jenefer-Monroe** [comment]
I’m afraid I have no idea then, I’ve never seen this before
You could try an override through classic upgrade.

**Comment by Jenefer-Monroe** [comment]
I wonder if its something you all have added to yours that its expecting to have in the new upgrade?

**Comment by michael-wright-pwc** [comment]
I would be surprised if something was added as I'm the one that mostly works in it and I didn't add anything. I will look into the override through classic upgrade option (not familiar with it) - do you know offhand if that will preserve our existing CoE data in dataverse? I have also created a ticket with MSFT and will let you know what the solution is if we find it.

**Comment by Jenefer-Monroe** [comment]
override does not impact the data in the dataverse tables. So that will be safe

**Comment by michael-wright-pwc** [comment]
@jenefer-monroe your override import suggestion worked!!! And on Friday the 13th too! haha - I'm so happy and thankful for that idea! Sending you lots of virtual hugs & high fives and appreciation.

**Comment by Jenefer-Monroe** [comment]
huzzah!!!! I'll go ahead and close then. Thanks for letting us know it got resolved!
