### ISSUE TITLE
[CoE Starter Kit - BUG] APP CATALOG PAGE CLEAR COLLECT DOESN'T WORK

### ISSUE THREAD

**Issue by djxrm08** [microsoft/coe-starter-kit#6837]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

ClearCollect Fx function is not pulling data from dataverse tables in the APP Catalog canvas page. 

The following function in the OnStart property- ClearCollect(tenantApps, Filter( 'PowerApps Apps', 'In App Catalog' = 'In App Catalog (PowerApps Apps)'.Yes)); is supposed to be collecting data from Power Apps but I keep getting an error. I have tried to use this function in a different app/page and it works fine there but just not in the APP Catalog canvas page. 

![Error](https://github.com/microsoft/coe-starter-kit/assets/147629252/24e87bf4-5c62-4b93-aeea-6a77753556d7)

### Expected Behavior

I had three apps with the InApp Catalog set to 'Yes' and still we see no apps in the APP CATALOG

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

admin_AppCatalog

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

In our tenant OOTB App catalog is not fetching records via Clear Collect. 

1. Open App Catalog Canvas page in editor mode. 
2. Run OnStart from App under Tree View. 
3. Check if Collection Variable Tenant Apps has any rows. 
4. Put the ClearCollect function in a button and press the button. 
5. Check if Collection Variable Tenant Apps has any rows.

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/147629252/50ca2e17-c2e0-4e44-b7a6-1a28494025e5)

AB#203

**Comment by Jenefer-Monroe** [comment]
This is working for me, can you please share a screenshot so we can better understand your issue?


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dbf2875c-0f2c-4d56-881c-b1cb89c5c897)

**Comment by djxrm08** [comment]
Hi Jenefer, 

Thanks for the prompt reply. 

Please find the screenshots below with explanation on each step. 

1. App Catalog shows nothing when I launch the app. I have 3 apps in the backend that are flagged as Yes and to be included in the app catalog. 

![image](https://github.com/microsoft/coe-starter-kit/assets/147629252/5fdbaaf5-f9fb-465d-8382-788657cf7ab9)

 2. Upon further investigation I noticed that the function is not fetching rows as expected. In my backend Dataverse table I have 3 apps or 3 rows that this ClearCollect should be fetching. 

![image](https://github.com/microsoft/coe-starter-kit/assets/147629252/ab8915fa-0501-4560-842c-57408859c39a)

![image](https://github.com/microsoft/coe-starter-kit/assets/147629252/35acc074-6139-4a09-8f07-b060dfaac828)

3. When I use the same Fx in a button, I get the following error- ‘Error when trying to retrieve data from the network’.  
![image](https://github.com/microsoft/coe-starter-kit/assets/147629252/598b3e1f-428e-4429-a886-8be70928dea0)


4. To further test, I used a filter option and added a gallery to see if records are populated and this seems to be working. I can see the 3 apps listed here. 

![image](https://github.com/microsoft/coe-starter-kit/assets/147629252/b9508eb5-5b48-4ea5-a5d1-b661a1e85bb4)

ClearCollect isn't working with this specific table but I wonder if this is a tenant specific issue since, it's working on your end.

**Comment by Jenefer-Monroe** [comment]
Can you please let us know what region your CoE envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

**Comment by Jenefer-Monroe** [comment]
also please check on the health of your connections, perhaps the Dataverse connection used in the app is broken?

**Comment by djxrm08** [comment]
Our region on the CoE envt. is Canada and I just checked again the Dataverse connections are healthy and working in the app. 

I turned off the Formula-level error management in the app and this what I see in the error when I try to run the same ClearCollect Fx function in a button: 

![image](https://github.com/microsoft/coe-starter-kit/assets/147629252/1cea61b6-714b-42c9-ae28-5646de31f2f9)

**Comment by Jenefer-Monroe** [comment]
ok I did test in a Canada envt and still did not see this. 

I know it sounds dumb but if you delete all the tables from the custom page and then add them back in, does it resolve? 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/666409c7-4906-4e12-815a-c2b6206b3b64)

**Comment by djxrm08** [comment]
Hi Jenefer, already tried this and still the same outcome :(

We are planning to upgrade our CoE with the new October release sometime this month. Maybe that'll fix the issue. Let me get back to you after our upgrade.

**Comment by Jenefer-Monroe** [comment]
Hi just checking in to see if upgrade resolved the issue for you.

**Comment by djxrm08** [comment]
Hi Jenefer, still no luck. We did an upgrade last week and the case is still the same. We are planning to build our own app catalog until we find a fix for this.

**Comment by Jenefer-Monroe** [comment]
ok I've asked around and unfortunately no one else has ideas of what may have happened in your tenant to result in this problem. I'm so sorry we cant get you unblocked!

**Comment by djxrm08** [comment]
Hi Jenefer, no worries! yes it is sort of a weird issue and maybe something happened at the time of installation that may have caused this. We are also trying install CoE on a different environment so maybe that resolves the issue. I will go ahead and close this ticket. Thanks for all your help.
