### ISSUE TITLE
[Governance Components]: Find apps with duplicate functionality

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#684]
Abilty to look for apps that do similar things. This perhaps added to Innovation Backlog, App Catalog, or something new. 

Can look at tools used already, then consider what's available in these as well: 
- [Announcing updates to the Power Platform VS Code Extension and the Power Platform Command line](https://powerapps.microsoft.com/en-us/blog/announcing-updates-to-the-power-platform-vs-code-extension-and-the-power-platform-command-line/)
- [Canvas source code tool integrated with Power Platform CLI](https://powerapps.microsoft.com/en-us/blog/canvas-source-code-tool-integrated-with-power-platform-cli/)

**Comment by manuelap-msft** [comment]
no concrete plans. has not come up with customers again. closing
