### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by SomarajuA** [microsoft/coe-starter-kit#6851]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

[Environment not visible.pdf](https://github.com/microsoft/coe-starter-kit/files/12881805/Environment.not.visible.pdf)

We are unable to find environments in Power BI COE reports even though I can find the environments in Power Platform admin center. We can see that the dataset is also refreshed recently, but we are still not able to see the environments in Power BI COE reports.

When we raised a request with MS Support, they have asked to create a ticket with you. Please see the attached PDF for the conversation which we had with MS Support. Also please see the screenshots which shows the enviroment in admin center, but not in COE reports.

![MicrosoftTeams-image (4)](https://github.com/microsoft/coe-starter-kit/assets/147693435/57e51587-c1c9-4647-9941-1ed841d007a6)
![MicrosoftTeams-image (3)](https://github.com/microsoft/coe-starter-kit/assets/147693435/3d024a4c-66e8-456c-a18a-1a792378039c)
![MicrosoftTeams-image (2)](https://github.com/microsoft/coe-starter-kit/assets/147693435/32baa1c4-0db3-4339-8ac0-87f04b27292f)

### Expected Behavior

Power BI COE reports should show all the available environments

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Not sure

### What app or flow are you having the issue with?

Power BI 

### What method are you using to get inventory and telemetry?

None

AB#196

**Comment by Jenefer-Monroe** [comment]
Hello lets first see what version of the kit you are on
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by SomarajuA** [comment]
Hi Jenefer,

We have a lot of rows which will not suffice in one screenshot. I am attaching screenshot with the top rows. Please let me know if it is fine or if I need to apply any filters.

***@***.***

Best Regards,
Somaraju Ankolu


***@***.***

Somaraju Ankolu
Global Technology Automation Team
Mobile: +91 9701777172

ManpowerGroup
***@***.***
www.manpowergroup.com<http://www.manpowergroup.com/>
For any issue with Automation please raise a ticket in ServiceNow here<https://mpgemea.service-now.com/gtesc>

**Comment by Jenefer-Monroe** [comment]
Hello multiple screenshots would be fine. However please not that you must log in to GitHub to share images, they do not come through if you respond in email. Can you please log in to GitHub and share?

**Comment by SomarajuA** [comment]
Hi Jenefer/team,

Please let us know if there is any update here.

Best Regards,
Somaraju Ankolu


***@***.***

Somaraju Ankolu
Global Technology Automation Team
Mobile: +91 9701777172

ManpowerGroup
***@***.***
www.manpowergroup.com<http://www.manpowergroup.com/>
For any issue with Automation please raise a ticket in ServiceNow here<https://mpgemea.service-now.com/gtesc>









From: Ankolu, Somaraju
Sent: 12 October 2023 18:22
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>; Aluri, Haribabu ***@***.***>; Chaudhuri, Supta ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6851)

Hi Jenefer,

We have a lot of rows which will not suffice in one screenshot. I am attaching screenshot with the top rows. Please let me know if it is fine or if I need to apply any filters.

***@***.***

Best Regards,
Somaraju Ankolu


***@***.***

Somaraju Ankolu
Global Technology Automation Team
Mobile: +91 9701777172

ManpowerGroup
***@***.******@***.***>
www.manpowergroup.com<http://www.manpowergroup.com/>
For any issue with Automation please raise a ticket in ServiceNow here<https://mpgemea.service-now.com/gtesc>

**Comment by SomarajuA** [comment]
Hi Jenefer and Team,

Please refer following screenshots that have the CoE tool kit solutions details, let us know if you need any further details.

Unmanaged solutions
***@***.***

Managed solutions:
***@***.***


Regards,
Hari

From: Ankolu, Somaraju ***@***.***>
Sent: Friday, October 13, 2023 12:35 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>; Aluri, Haribabu ***@***.***>; Chaudhuri, Supta ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6851)

Hi Jenefer/team,

Please let us know if there is any update here.

Best Regards,
Somaraju Ankolu


***@***.***

Somaraju Ankolu
Global Technology Automation Team
Mobile: +91 9701777172

ManpowerGroup
***@***.******@***.***>
www.manpowergroup.com<http://www.manpowergroup.com/>
For any issue with Automation please raise a ticket in ServiceNow here<https://mpgemea.service-now.com/gtesc>









From: Ankolu, Somaraju
Sent: 12 October 2023 18:22
To: microsoft/coe-starter-kit ***@***.******@***.***>>; microsoft/coe-starter-kit ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>; Aluri, Haribabu ***@***.******@***.***>>; Chaudhuri, Supta ***@***.******@***.***>>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE TITLE (Issue #6851)

Hi Jenefer,

We have a lot of rows which will not suffice in one screenshot. I am attaching screenshot with the top rows. Please let me know if it is fine or if I need to apply any filters.

***@***.***

Best Regards,
Somaraju Ankolu


***@***.***

Somaraju Ankolu
Global Technology Automation Team
Mobile: +91 9701777172

ManpowerGroup
***@***.******@***.***>
www.manpowergroup.com<http://www.manpowergroup.com/>
For any issue with Automation please raise a ticket in ServiceNow here<https://mpgemea.service-now.com/gtesc>

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid I still cannot see your screenshots. You need to login to GitHub to share them. Sharing via attaching to email responses does not work.

**Comment by SomarajuA** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/147693435/261198e3-5a4f-4f0c-8e4e-19922b36bdf9)
![image](https://github.com/microsoft/coe-starter-kit/assets/147693435/4cfb7cbd-149d-49f3-afc7-4c98e6538e00)

**Comment by Jenefer-Monroe** [comment]
Wonderful! 
You are on an old version of the kit. (Feb 2023) so lets gather a few more details to know what direction to go:

1. Did you install the kit yourself or did someone else? 
2. If someone else, do you know if they still with the company?
3. Do you know what features you are using? Just inventory? 
4. Please look for these flows in particular and see when they last ran successfully
     - Admin | Sync Audit Logs
     - Admin | Sync Template v3

**Comment by SomarajuA** [comment]
Hi Jenifer,

Please see the below details.

Did you install the kit yourself or did someone else?
It is installed with service account: [SVC-global-PPlatform@manpowergroupapps.onmicrosoft.com](mailto:SVC-global-PPlatform@manpowergroupapps.onmicrosoft.com). With the help of MS support team, the CoE starter Kit installed
 
If someone else, do you know if they still with the company?
It is installed in  end of March 2023.
 
Do you know what features you are using? Just inventory?
We are trying to use Power BI reports from CoE starter kit for audit purpose
 
Please look for these flows in particular and see when they last ran successfully
Admin | Sync Audit Logs ==> currently it is in turned off state. 21st May was last run and it was failed; 2nd May was last successful run
Admin | Sync Template v3  ==> No run history, currently it is in turned off state. Last modified 8th May

**Comment by SomarajuA** [comment]
We need this to be resolved as soon as possible, please prioritize this

**Comment by Jenefer-Monroe** [comment]
After this you will have inventory in your tables and running again, you can check in the Power Platform Admin View app to see it. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3ae2daf4-3f83-4569-b089-edbfe5375c7c)


Then you can setup the Power BI as well: [Set up the Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi)
And get the new Audit Log system going: [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by SomarajuA** [comment]
Hi Jenefer, We need your help while we are doing these steps as these looks like major changes. Please let us know if you can connect with us in a call and we will do this in screen share.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team. 
Please do return here with a new bug though if you try the steps and get stuck.

**Comment by SomarajuA** [comment]
Hi Jenefer, we are trying follow the steps provided.

When we are executing the center of excellence setup wizard, we are not able to turn on the below Run inventory flows and getting the below error. Please suggest.

**Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_PowerPlatformMakeSecurityGroup'."}}".**

![MicrosoftTeams-image (5)](https://github.com/microsoft/coe-starter-kit/assets/147693435/f6939949-9c95-4d59-86fb-4d233af97739)


![MicrosoftTeams-image (6)](https://github.com/microsoft/coe-starter-kit/assets/147693435/4eebaa48-99f6-4133-a4e1-bb905ff3a421)
