### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL Data Export - Environments

### ISSUE THREAD

**Issue by peter-griff** [microsoft/coe-starter-kit#6854]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When setting up the BYODL Environments I get the below message 

![image](https://github.com/microsoft/coe-starter-kit/assets/147742087/4f1a0256-1b7b-4205-863f-ea2db05a93c4)

The Maker dataflow is fine but when I have come on to the second dataflow I have this issue

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

BYODL Environments

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Edit BYODL Environments

AB#195

**Comment by Jenefer-Monroe** [comment]
Can you please share the expression you have here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c27cc42e-7387-4dab-b514-49a94bafc0fc)

**Comment by manuelap-msft** [comment]
Can you open up the Transform environments folder at the top and check you have authenticated the admin_makers table already:
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/6db1b973-eff7-478b-92e6-6c03fe9874ab)

**Comment by peter-griff** [comment]
Table.ReplaceValue( #"Replaced SYSTEM user", null, Table.SelectRows(admin_makers, each [admin_displayname] = "SYSTEM"){0}[admin_makerid], Replacer.ReplaceValue, {"createdBy"})

**Comment by manuelap-msft** [comment]
Had an offline chat with Peter: Likely caused by the customer not using the Setup Wizard for the setup, and thus the SYSTEM maker is missing from their maker table and that's causing the merge to fail. Will keep this open until we have confirmation that that was the issue.

**Comment by peter-griff** [comment]
All sorted now had to re-run the wizard thanks :)

**Comment by Jenefer-Monroe** [comment]
wonderful news, thanks for the update!
