### ISSUE TITLE
[AA4AM] Suggestion: Move AA4AM into a separate GitHub repository

### ISSUE THREAD

**Issue by Chris-WP** [microsoft/coe-starter-kit#686]
**Is your feature request related to a problem? Please describe.**
As AA4AM continues to evolve and mature, it may be worth considering moving it into its own GitHub repository.

**Describe the solution you'd like**
A separate repository would provide the following advantages:

- make it easier to track new releases
- remove the need to prefix issues with [AA4AM]
- make forking the solution a little bit easier
- reduce the "noise" of GitHub notifications that relate to other parts of the "starter kit" code base
- help AA4AM create its own identity as a tool that is separate but complementary to the COE Starter Kit

**Describe alternatives you've considered**
There may be other build, platform and governance considerations that may provide reasons for not doing this.
It is a "nice to have" suggestion rather than a blocking issue.

**Comment by mikefactorial** [comment]
Hey @Chris-WP,
Good feedback. Agree that the experience is a bit awkward ATM because we are in private preview. The goal is to have AA4AM released as part of the CoE Starter Kit when we are out of preview. AA4AM is a component of the CoE Starter Kit along with AA4M. I'll bring up this issue with the team when we meet today as your points are well taken.

**Comment by devkeydet** [comment]
The tool is not separate from the CoE Starter Kit.  It's part of it.  This will become more apparent as we come out of private preview and start to surface it as part of https://aka.ms/coestarterkit.  There will be other modules of the CoE Starter Kit that we introduce as well.  The CoE Starter Kit is not just for Governance and Administratio.  It's the set of tools our team (Power Customer Advisory Team) builds to help embody patterns & practices we've learned through our own usage of the platform as well as what we've learned from other customer implementations.  Tools that a CoE would want to promote for consistent implementation of patterns & practices.  But your points about the advantages are great.  But if we did something like this, we would probably do it for all CoE Starter Kit components.  There are pros/cons to either approach, but something we'll take into consideration.  However, for now, evaluating this would slow down other high priority work.  We're focused on getting out of public preview.  After we do, can re-evaluate.

**Comment by devkeydet** [comment]
Also, there are other things we can consider making the experience better, including using some of the newer features coming to GitHub issues:
https://twitter.com/github/status/1407731478096756739
...and more clarity on contribution guidance.  All things that we plan to do.  Still agree that there may come a day where it makes sense to separate, but for now it's lower priority to move to another repo.  But we'll continue to learn and evolve.

**Comment by Chris-WP** [comment]
Many thanks for your insights @mikefactorial and @devkeydet. It's great to hear that AA4AM will be part of the bigger CoE Starter Kit picture.
