### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Bi CoE report

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#6867]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

Please, in the CoE power bi makers report, there are environments that have makers just because that maker has a chatbot, but looking at this environment, there is no chatbot created. Looking at the prints below, can you tell me why the CoE adds these makers to the environment saying that there is a chatbot when it doesn't?
![Coe Makers 1](https://github.com/microsoft/coe-starter-kit/assets/129080740/cb7709b3-bc4d-4f67-9c54-7e00c49c42b4)
![CoE Makers 2](https://github.com/microsoft/coe-starter-kit/assets/129080740/17449f21-f627-4efd-9ba8-fae3331d3b7b)
![CoE Makers 3](https://github.com/microsoft/coe-starter-kit/assets/129080740/078abed5-d8a5-445f-ac7b-8254279471a0)
![CoE](https://github.com/microsoft/coe-starter-kit/assets/129080740/0d6f349c-1c43-448a-852f-8d7b83b83f2b)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Setembro 2023 -  4.15

### What app or flow are you having the issue with?

Power BI CoE

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
You are on an older version of the PBIT file so I'm not sure if there may have been a bug there. 
If you open in the desktop you can see what is behind that tile, it should be as shown here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2fd1abb7-acb9-4add-b6b6-3c7de6638c8a)

**Comment by Jenefer-Monroe** [comment]
You're so welcome. I'll go ahead and close out then, but please do return with other questions in the future
