### ISSUE TITLE
[CoE Starter Kit - QUESTION] GCC license change on service account - G3 to F3

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#6868]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

We currently have our CoE service account set up with a Microsoft 365 G3 (directly assigned), but I am being asked if they can downgrade it to an F3 license. I suspect they want to do this to save money.

As far as I can tell, it will still have all the features it needs to run the CoE. Am I missing anything? Any gotcha's with this license? Will still have a mailbox, and still have the premium licenses added, including Power BI Pro.

Just looking for confirmation that a Microsoft 365 F3 GCC license will be enough for the CoE service account.

Thank you.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 2023

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by pnoot7** [comment]
May be unrelated, but I just got this email after I submitted this.

![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/cce7cde2-b839-435f-8824-1c29bc913936)

**Comment by Jenefer-Monroe** [comment]
Hello. I'm not a licensing expert so I'm not sure exactly what that license type covers. We don't do anything with DevOps but the ALM Accelerator does if you have that configured. And I don't know their licensing requirements. 

Things I know to look out for are 
1. Pagination limits (we require 100,000 pagination size)
2. Per-user flow licensing capability
3. Per-user app licensing capability. 

Sorry I cant be of better help here. But I'm sure your account rep could tell you with that information.

**Comment by pnoot7** [comment]
I was hoping to get a specific answer for the requirements of the CoE. As you know, if I mention the CoE in a support ticket, I get routed here. It is also difficult to get answers from licensing specialist, as they are in Sales, and I've been misled already, as they always say we need the expensive version of licenses. Do you have any suggestions on who I could talk to? Since this is specific to the CoE, I am always referred here, and other MS staff won't touch it.

I don't see pagination listed on the comparison sheet. https://go.microsoft.com/fwlink/?linkid=2248949&clcid=0x409&culture=en-us&country=us

As for the email alert I posted, I got that email after submitting this ticket. I don't have ALM accelerator set up, and this GitHub account is not tied to my tenant at all. Is there something on the back end that was set up for the CoE repository that was triggered and failed? It appears to be on your end, the link in the email goes here: https://github.com/microsoft/coe-starter-kit/actions/runs/6536433877

and going one level up looks like a bunch of related items to the CoE repository:
https://github.com/microsoft/coe-starter-kit/actions/workflows/sync-to-azdo.yml

**Comment by manuelap-msft** [comment]
> May be unrelated, but I just got this email after I submitted this.
> 
> ![image](https://user-images.githubusercontent.com/125403575/275583253-cce7cde2-b839-435f-8824-1c29bc913936.png)

@RajeevPentyala can you comment on this please? We recently set up a sync between GitHub and our own Azure DevOps board, the email may be related to this sync.

**Comment by RajeevPentyala** [comment]
> > May be unrelated, but I just got this email after I submitted this.
> > ![image](https://user-images.githubusercontent.com/125403575/275583253-cce7cde2-b839-435f-8824-1c29bc913936.png)
> 
> @RajeevPentyala can you comment on this please? We recently set up a sync between GitHub and our own Azure DevOps board, the email may be related to this sync.

@manuelap-msft Yes, this email is related to the sync workflow. Users can opt to not receive the emails by changing the notification settings.

**Comment by pnoot7** [comment]
> > > May be unrelated, but I just got this email after I submitted this.
> > > ![image](https://user-images.githubusercontent.com/125403575/275583253-cce7cde2-b839-435f-8824-1c29bc913936.png)
> > 
> > 
> > @RajeevPentyala can you comment on this please? We recently set up a sync between GitHub and our own Azure DevOps board, the email may be related to this sync.
> 
> @manuelap-msft Yes, this email is related to the sync workflow. Users can opt to not receive the emails by changing the notification settings.

Where would a user do this? Would they have to customize the notifications on each and every support issue? Just my two cents, but this is a poor user experience. Are these instructions posted anywhere? If this is profile specific, what if I had my own actions that I want notifications for?

**Comment by Jenefer-Monroe** [comment]
Regarding the license question, I wish the licensing were simple enough for us to help here but it just isn't, there are people who are experts at licensing as a result and your account rep is that person. And they really are supposed to be supporting you to best value. I'm sorry if that has not been your experience. 

I mention the pagination as that is one that has hit people when they change license types. A gotcha as you had requested. 
Details about it can been found here [Concurrency, looping, and debatching limits](https://learn.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d79236fe-226f-4478-854d-f2bdac8e35d2)

**Comment by Jenefer-Monroe** [comment]
I'll let @RajeevPentyala comment there, I was guessing. 

@RajeevPentyala can you please show how to silence that notification? I'm not seeing it so not sure how to advise here.

**Comment by RajeevPentyala** [comment]
@pnoot7 To turn off notifications, please go to [Notification Settings](https://github.com/settings/notifications) and uncheck the 'Email' and 'On GitHub' options and save. FYI @Jenefer-Monroe 
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/38c4e493-e9c0-4ae1-96bd-0ff7f0594198)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
