### ISSUE TITLE
Count between PBI Report and Admin app don't seem to match

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#6869]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The count of say App in the PBI and the admin app don't seem to match.  This is true for Apps, Flows, Makers.

Where is the difference coming from..?

If this is by design what is the filtering that is applied for each.  We get asked by management for numbers and I would like to understand which one is good for what so we don't get questions about why they don't match.

![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/6906b34f-4ae1-43a6-b216-735a4d51aefc)

![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/76940ff3-7d72-4142-a389-b008b853eeb6)

For flows it's PBI 1329 and 1335 for Admin app.

### Expected Behavior

Counts match as filtering logic should be the same.  I think...

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September

### What app or flow are you having the issue with?

PBI and Admin App

### What method are you using to get inventory and telemetry?

Cloud flows

AB#222

**Comment by Jenefer-Monroe** [comment]
The best way to explore this would be to open the PBI in the desktop and look at what is filtered and to look at the view in the PP service. Out of the box these do have the same filters but they can be changed by people.

Look at the table view: 
Its filter is status = Active and App Deleted = No
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/00893954-2a38-413c-97cd-d53b78a637c1)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d3d38f04-45ec-4185-97ff-002244e2cc17)


Look at the PBI in the desktop:
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3b4395be-a4d9-4ad0-9e07-47b8a144b27a)

**Comment by PPCan** [comment]
Ok. Thanks.  I'm assuming that the Admin app should be trusted when there are discrepancies considering it's always fresh when it loads..?

**Comment by Jenefer-Monroe** [comment]
Thats correct, it doesnt have a refresh to do.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
