### ISSUE TITLE
Find Connections used by environment

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#6871]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way to find the connections that are used by environment, and which apps are using them?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately no, the information about which connection is used in which app/flow is not something that is accessible to us. 
The only thing in this area that are able  to do for you is store identities that use a connection in an envt. 

Here you can see that report: 
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4cde44ae-0053-4239-86a3-cfa0e5f73e3b)
