### ISSUE TITLE
[CoE Starter Kit - QUESTION] Some SharePointFormApp are listed as Canvas

### ISSUE THREAD

**Issue by muler-git** [microsoft/coe-starter-kit#6877]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

**Some of the SharePointFormApp are listed as Canvas.**

Hi, 
We have upgraded COE to Aug version, but we still see Some of the SharePointFormApp are listed as Canvas.

As per the below article the App categorization was fixed in June release.
https://github.com/microsoft/coe-starter-kit/issues/5600

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Aug 2023 (4.13)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#235

**Comment by Jenefer-Monroe** [comment]
Did you run these apps through inventory? Unfortunately the way our inventory works, it does not detect things that need inventoried, you must force the inventory. 

You can do this with the Inventory Me flag on the app record


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/69460aff-74ed-460c-b06c-0d69a0d195de)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by muler-git** [comment]
It worked, Thank you for your help.
