### ISSUE TITLE
[CoE Starter Kit - BUG] - Apps with no owners are not showing as Orphaned in App-Permissions App

### ISSUE THREAD

**Issue by AmandaMet** [microsoft/coe-starter-kit#6879]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I couldn't find this in the backlog, but am new here so don't understand some of the terminology in the existing issues.
Installed CoE yesterday, so should be up to date version.
I want to add permissions to orphaned apps so I can delete/update them. They show in the list of Apps with a 'blank' owner.  I then run the App Permissions App to add permissions (so I can change the owner), but the Apps with a 'blank' owner aren't listed.  Have tested a few.

Tried logging this with Microsoft Unified Support but they directed me here.
Thanks

### Expected Behavior

Hoping to find the Apps with a 'blank' owner and reassign permissions so I can delete/edit them.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Set App Permissions

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. From Power Platform Admin View App
2. Power Apps Apps
3. Search for App
4. Its listed with App Owner blank
5. From Set App Permissions App
6. Switch to the correct environment
7. Search (and tried scrolling) to find the App
8. Not listed.

### Anything else?

![App listed in PowerApps App with no owner](https://github.com/microsoft/coe-starter-kit/assets/148332846/99ad2562-0eda-4108-9bda-8659d90d881e)
![App not listed in Set App Permissions](https://github.com/microsoft/coe-starter-kit/assets/148332846/e32ec6c1-131a-4433-8e2e-3a1a058ca159)

AB#231

**Comment by Jenefer-Monroe** [comment]
I believe the image from the first screen is a Model Driven App, is that correct? 
The Set App Permissions app does not support Model Driven Apps unfortunately, only Canvas.

**Comment by AmandaMet** [comment]
It's a SharePointFormApp - don't know what this is, but am guessing same applies, that the Set App Permissions is purely for Model Driven?
***@***.***
Thanks
Amanda

**Comment by Jenefer-Monroe** [comment]
Its purely canvas, no SP Forms and no MDAs. 

Permissions for SP Forms is handled in SP itself. Not in Power Platform. For those records you can go to the Power Platform Admin View app and find where the SP site is

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/07c2775f-f5bd-4371-8379-c86ad5d5cfb6)

And then manage from there
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b646990d-7249-402a-b174-5e42ede988ed)

**Comment by AmandaMet** [comment]
Ok!
Thanks for the info, there are several owners on the SP site, however the app is blank - how do I change ownership of the app itself?

***@***.***

**Comment by Jenefer-Monroe** [comment]
Can you please find this app in the Power Platform Admin View app and mark it to be inventoried? 
Then wait for the next day's inventory to run and see if this fixes it. If not we can look at what the product returns for owner.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/aaeba4f6-e4f8-4871-b1c3-0fb567b7f307)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by AmandaMet** [comment]
Hi there
I did this last week, but just realised I didn't follow up with you.
Where do I find the next days inventory run to see if it's fixed?
Thanks
Amanda
