### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can I get the user licenses details using the COE starter kit in power platform? Would like to know which user has which licenses in power platform?

### ISSUE THREAD

**Issue by DineshShikare** [microsoft/coe-starter-kit#6880]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can I get the user licenses details using the COE starter kit in power platform? Would like to know which user has which licenses in power platform?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.2

### What method are you using to get inventory and telemetry?

None

AB#234

**Comment by Jenefer-Monroe** [comment]
Unfortunately we do not have access to this information in a way we have been able to make performant. 
It in on our backlog but we have not found a way to do this correctly.

**Comment by DineshShikare** [comment]
Thank you for the quick response and update.
