### ISSUE TITLE
[ALM Accelerator - QUESTION] - Uninstalling the solution

### ISSUE THREAD

**Issue by ajinkyaskulkarni** [microsoft/coe-starter-kit#6882]
### What is your question?

Hello,

I Installed the CoE - ALM accelerator last year and after some initial struggle it was finally successfully installed.

I have read in the documentation that any updates above 3 months can cause problem, while updating the solutions. So in order to have a clean setup i am currently deleting the solutions (last solution first).

I am encountering the attached error while attempting to delete ALM Accelerator solution.

At first i am getting the error 'cannot delete API due to existing connections' and in the second attempt getting workflow uninstall failure (I checked further in the solution and the flow does not exist and appears like a zombie flow reference).

- Please let me know if there has been such case and a possible soltion to forceflly delete these solutions (without deleting the CoE environment) as these solutions are managed deleting a particular componenent is not possible. 

![ALM Accelerator](https://github.com/microsoft/coe-starter-kit/assets/25870713/5d7aa8ff-acb7-4ba0-80dd-1cea891ee67c)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

March 2022

AB#236

**Comment by mikefactorial** [comment]
@ajinkyaskulkarni the GetSolutionConnectionReferences flow should be a part of the solution and was part of the solution even a year ago so the fact that it isn't there is strange. I would try re-importing whatever release you installed previously or a newer one to see if that flow is restored and then delete the solution. The first error is a recent platform change that requires the connection to be deleted before the solution can be uninstalled. I've seen that error pop up just recently and it never did that before, but deleting the connection does get rid of the error.

**Comment by mikefactorial** [comment]
Closing this out as there's nothing more to do here.
