### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unintalling solution - Solution CoE Core components - timeout

### ISSUE THREAD

**Issue by ajinkyaskulkarni** [microsoft/coe-starter-kit#6883]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I Installed the CoE - ALM accelerator last year and after some initial struggle it was finally successfully installed.

I have read in the documentation that any updates above 3 months can cause problem, while updating the solutions. So in order to have a clean setup i am currently deleting the solutions (last solution first).

While uninstalling the solution i am getting operation time out error. Also i checked for the solution dependency with 'Dependency checker' and it doesn't report any.

Please let me know if the solution can be deleted without having to delete the environment itself.
![CoE - Core Components](https://github.com/microsoft/coe-starter-kit/assets/25870713/da812377-f2bc-4a35-ac40-4dbedeaa72bb)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

March 2022

### What method are you using to get inventory and telemetry?

None

AB#237

**Comment by Jenefer-Monroe** [comment]
This is a product limitation in the solution management. The UX will often time out but the process itself does not. 
If you click **_See history_** you can watch for the process to complete there.

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2df332a7-de15-487a-a3aa-535f0d4db507)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
