### ISSUE TITLE
[CoE Starter Kit - BUG] Dataflow Export Permissions & Documentation update

### ISSUE THREAD

**Issue by poi-radvine** [microsoft/coe-starter-kit#6884]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,
we were updating to the newest CoE Starter Kit with BYODL Dataflows and noticed some important details that are currently absent in the documentation.

1. The Resource group of the subscription needs to be in the same region as the Power Platform/PowerBI Premium Capacity. We continuously got an error message in PowerBI we did not understand.

2. The current documentation does show an image of the IAM Access Control Permissions to be set for the Datalake storage account but does not mention this for the resources group.
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#confirm-storage-account-permission 

Please change the image to show the resource group. The permissions Storage Blob Data Owner/Storage Blob Data Reader need to be set for the owner of the CoE Dataflows.
![image](https://github.com/microsoft/coe-starter-kit/assets/88713407/d5528f36-4939-49ab-96bd-eff0c2eae6ef)

3. Omitted URL in Documentation makes it hard to know what goes in what setting box.
When configuring the Datalake url the appendix "powerplatform" is required.
Example: https://youinventory.dfs.core.windows.net/powerplatform
When configuring the Credentials the Datalake URL withouth the appendix is required. 
Example: https://yourinventorydata.dfs.core.windows.net/

Can you please update your documentation as this was quite hard to figure out on our own, especially after already configuring all to make it work with PowerBI.
We are all not experts in all needed platforms (BI, Azure, PowerPlatform, Fabric etc) and are relying on your great documentations to make setup seamless and stress free.

Wish you a stress free rest of the week. Greets from Styria! 🍻

### Expected Behavior

Hi Team,
we were updating to the newest CoE Starter Kit with BYODL Dataflows and noticed some important details that are currently absent in the documentation.

1. The Resource group of the subscription needs to be in the same region as the Power Platform/PowerBI Premium Capacity. We continuosly got 
The current documentation does show an image of the IAM Access Control Permissions to be set for the Datalake storage account but does not mention this for the resources group.
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#confirm-storage-account-permission 

Please change the image to show the resource group. The permissions Storage Blob Data Owner/Storage Blob Data Reader need to be set for the owner of the CoE Dataflows.
![image](https://github.com/microsoft/coe-starter-kit/assets/88713407/d5528f36-4939-49ab-96bd-eff0c2eae6ef)

When configuring the Datalake url the appendix "powerplatform" is required.
Example: https://youinventory.dfs.core.windows.net/powerplatform
When configuring the Credentials the Datalake URL withouth the appendix is required. 
Example: https://yourinventorydata.dfs.core.windows.net/

Can you please update your documentation as this was quite hard to figure out on our own, especially after already configuring all to make it work with PowerBI.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

BOYDL Dataflows

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

x

### Anything else?

x

AB#239

**Comment by Jenefer-Monroe** [comment]
Thanks for these notes! It takes a village to make good documentation :)

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
