### ISSUE TITLE
[ALM Accelerator - QUESTION] Both a source and target reference is required

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#6885]
### What is your question?

Hi, 

I have a strange issue and i don't know why. I have an error Both a source and target reference is required and TF401180: The requested pull request was not found when i want to deploy a solution when show advanced is not active.

Here are my tests :

1. New solution : Name : Solution 1
> Show advanced : No
      * commit ok

> Deploy Test
      * Show advanced : no
       * Deploy error : **Both a source and target reference is required + TF401180: The requested pull request was not found.**
       
       * Show advanced yes : 

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/d352fc30-339c-414a-a078-1cd644562c31)
![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/2782316e-9176-474e-b261-7d3e5c4c38c0)

Works but skip Test environnement.

Do you have an idea?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

october 23

AB#240

**Comment by tocri** [comment]
?? I ve received that ? is it normal ?

<img width="613" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/86f62657-22b3-451c-903c-41b90f9afe1a">


<img width="569" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/0642358b-c310-4250-bc57-6444cbbf898e">

**Comment by tocri** [comment]
After several hours of test & learn, I finally found the issue. I don't know if the problem comes from devops or from AA4PP, but it seems that having 2 deployment profiles pointing to the same repo causes issues. Yet, it worked perfectly fine this way for several months.
So, I changed my approach which I find more agile now. For each deployment profile, I've associated a repo. 
Ex: Deployment profile 1 = Repo DEP 1, deployment profile 2 = Repo DEP 2. This approach is healthier for me as I can adjust the reviewer according to the branch, it's simpler in terms of maintenance and management

**Comment by RajeevPentyala** [comment]
> ?? I ve received that ? is it normal ?
> 
> <img alt="image" width="613" src="https://user-images.githubusercontent.com/10110260/276334414-86f62657-22b3-451c-903c-41b90f9afe1a.png"> <img alt="image" width="569" src="https://user-images.githubusercontent.com/10110260/276334464-0642358b-c310-4250-bc57-6444cbbf898e.png">

@tocri That notification was from one of our workflow. please go to [Notification Settings](https://github.com/settings/notifications) and under 'Actions', uncheck the 'Email' and 'On GitHub' options and save. FYI @Jenefer-Monroe 
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/38c4e493-e9c0-4ae1-96bd-0ff7f0594198)
