### ISSUE TITLE
[ALM Accelerator] Export Solution to Git Pipeline not saving SP connection reference in flow

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#6886]
### Describe the issue

This issue is on my client's tenant.
If we use a different connector, like teams connector, I see the **connection reference** in the repo branch. When going to src > Workflows > flow.json
But when we commit a solution that uses SP connection reference, it is empty.
![image](https://github.com/microsoft/coe-starter-kit/assets/100951593/783fad7e-e792-4c05-9c56-035d399095a3)

When it should show something like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/100951593/56ee4c76-6ce5-4323-85a5-8511e3185978)

Thus, when we deploy the solution to test environment, the flow appears to have no connection reference linked, even though the connection reference exists in the solution and it is pointing to the correct account:
![image](https://github.com/microsoft/coe-starter-kit/assets/100951593/8344b5e4-eee9-4c12-b517-29f84f0a53d8)

### Expected Behavior

Connection reference is being saved in the flow.json file in the src folder in the repository commited branch. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

October 2023

AB#241

**Comment by LizethRegules** [comment]
@mikefactorial any insights would be helpful! Thank you so much in advance!

**Comment by mikefactorial** [comment]
@LizethRegules I'm traveling this week so won't be available for a call. However, have you tried exporting the solution manually and unzipping to see if the connection reference is there? If not then maybe try removing / re-adding the connection reference to the solution.

**Comment by LizethRegules** [comment]
@mikefactorial, thanks for the idea. We will try the manual export and see if it's there.
It is funny, because the connection reference **IS** in the solution and is populated with the right connection, only not appearing on the flow. 
So:
![image](https://github.com/microsoft/coe-starter-kit/assets/100951593/64a26753-5161-443e-8b25-a429d988a321)

but:
![image](https://github.com/microsoft/coe-starter-kit/assets/100951593/0d3178c3-c44f-41d1-84bb-316f1548fc11)

**Comment by mikefactorial** [comment]
Are those screenshots from dev environment or the target environment?

**Comment by LizethRegules** [comment]
@mikefactorial target environment

**Comment by mikefactorial** [comment]
So, in the dev environment the connection reference is shown? Is the person exporting the solution the same person that owns the connection reference? Does the same thing happen if you create a new solution with just a new flow and that connection reference in it? Just trying to eliminate variables.

**Comment by LizethRegules** [comment]
The manual export is not showing the connection either:
![image](https://github.com/microsoft/coe-starter-kit/assets/100951593/0b47cc40-7bec-4ba1-900c-5b9f102768a6)

The person exporting the solution is different to the person the owns the connection reference. 
I will ask them to recreate the connection in the flow and see if that fixes it?

**Comment by LizethRegules** [comment]
@mikefactorial client was using connections instead of connection references in the flow. 
Now it is working.

**Comment by mikefactorial** [comment]
@LizethRegules thanks for reporting back the solution 👍
