### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Report - Power Automate count mismatch 

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#6889]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Overview - Power Automate: We are verifying Power Automate count and found some mismatch

Let me provide you overview : 

In Report Total Count : 8246 

However, when we are trying to calculate all Started, Stooped and suspended flow
Count Flow - Started : 4282
Cloud Flow - Stopped : 1907
Cloud Flow - Suspended : 897

Total : 4282+1907+897 = 7086

Now you can there is gap aground :  8246-7086 = 1160 Gap
Screen Shot: 
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/a1eb3418-ba7c-4286-a581-b041621f35a0)

One more Point, I have installed CoE in two env as recommend and there is huge gap in report in the context of count Power Automate & Power Apps dashboard section :- 
In Prod Core component version :  4.13
In QA Core component version : 4.15 

QA: Snapshot

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/0497307e-388d-4d25-8976-b5332252ef96)

Prod: Snapshot
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/501dc540-7042-4af2-a98b-16cb4eaa6e59)

Apart from that my previous case "Issue #6692" is closed however, still ST.com count as cross connection after preforming the all suggested action.

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/9eb6d457-5c94-446a-925d-60c901818f06)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

None

AB#244

**Comment by Jenefer-Monroe** [comment]
Regarding the difference between Prod and QA, please compoare the values of the env vars across these. Ideally the only difference would be "production environment"
I ask that you please compare all but in particular are these different? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb3da781-c142-40a4-973f-acc67d7e2f7b)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/852d013c-659a-4752-bbf8-fd97513b554a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
