### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE sends automatic emails saying that I have been added as a co-owner to a flow.

### ISSUE THREAD

**Issue by maikletal** [microsoft/coe-starter-kit#6890]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I installed the new version on Monday (October, 16) and since yesterday I started receiving emails saying that the management account has been added as a co-owner of a flow. 

Since yesterday I have already received more than 100 emails in different flows.

The most curious thing is that when I click on the link to access any of the flows, in all of them it tells me that I do not have access.
![image](https://github.com/microsoft/coe-starter-kit/assets/44426740/f1d01265-1cb7-4605-a202-c81909f2029a)
![image](https://github.com/microsoft/coe-starter-kit/assets/44426740/fd511fb7-2cc8-4184-9e6f-64fbc1aa596a)

I have seen similar issues but they were from previous versions and had been fixed. Which may be due?

Thank you for your support

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2023, 4.16

### What app or flow are you having the issue with?

HELPER - CloudFlowOperations

### What method are you using to get inventory and telemetry?

Cloud flows

AB#245

**Comment by maikletal** [comment]
Creo que el flujo que está enviando esos emails es HELPER - CloudFlowOperations

**Comment by Jenefer-Monroe** [comment]
Hello. This is from the Flow Action Details flow. 
In the past the product only shared some details about a flow with people who own in. In this case its details like what source an HTTP call is using. So this flow adds the person running the flow as an owner, fetches those details and then removes them (if thy werent already owners)
There is not a way to silence the notificiation from this connector unfortunately. 
However in the next few months the product team is adding the mising information to Get Flow as Admin and we will be able ot remove this noise once that ships.

**Comment by maikletal** [comment]
Hello Jenefer.
But this was not happening in previous versions. Why am I receiving this information now?
The truth is that it is a bit annoying because it fills up the administration account inbox.
If nothing can be done, I'll put a rule in the mail.
Thanks for your help.

**Comment by Jenefer-Monroe** [comment]
If you want details about things like you see in the governance dashboard (has plain text password, http calling site, etc) then this is unfortunately just something that you have to deal with for now.

Perhaps people are using these connectors for the first time in your tenant, or perhaps you recently turned on the flow which gathers this information:  Admin | Sync Template v3 (Flow Action Details)

Here is the note in the setup instructions which discusses this: [Turn on inventory flows](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#turn-on-inventory-flows)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6a0d573f-318f-437b-8394-24565b2c393e)

We are as eager as you to remove this issue but are blocked for now.

**Comment by maikletal** [comment]
Ok, Jenefer.
Thank you very mucho for your support.

**Comment by maikletal** [comment]
Ok. Thanks for the support!
