### ISSUE TITLE
[CoE Starter Kit - QUESTION] SYNC HELPER - Apps throwing error

### ISSUE THREAD

**Issue by PPTechy** [microsoft/coe-starter-kit#6891]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have been getting error in "SYNC HELPER - Apps" flow, the error details say below:

Error
**Action 'Get_App_from_Inventory' failed**

**Entity 'admin_app' With Id = d2563447-cd4c-4bb8-90b6-38dce901d643 Does Not Exist**

This error is coming from most my environemts with the different ID but says the same message **Entity 'admin_app' does not exist**.

What does this "SYNC HELPER - Apps" flow do? And what should I check to prevent this error coming?

I am using core solution 4.9 version.

Thank you!!!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9 June 2023

### What method are you using to get inventory and telemetry?

Cloud flows

AB#246

**Comment by Jenefer-Monroe** [comment]
Please note that failures like this are caught/expected failures. 
We use these calls to see if the object is new to the inventory, and if it is, this call to “get it” will fail. This failure is caught and the “isnew” variable is set to true. 
![image](https://user-images.githubusercontent.com/89584709/225679681-01467de5-1a1c-4c93-bf57-71296f5ea83b.png)
In order to debug you need to find the terminating failure in the flow. Here for example the call to “forced failure” failed, and was not caught, so the flow terminated here. That is the spot you need to find in your failure in order to debug. 
![image](https://user-images.githubusercontent.com/89584709/225681214-a5549790-32e9-482e-b427-0c346aa50684.png)

**Comment by PPTechy** [comment]
It seems you have misunderstood me, I am not getting error in "Admin | Sync Template V4 flows, in your screenshot you have shown "Admin | Sync Template V3" flow  - the issue what I had explained was "**SYNC HELPER - Apps**" flow, here I have attached the screenshot of the flow where it is failing. 

<img width="671" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/ddfc3ed3-d3b4-442a-94a7-14aa74def63f">

Kindly suggest me what's wrong in this flow?

**Comment by Jenefer-Monroe** [comment]
My screenshot was just a canned sample I have for all these cases, its a common misunderstanding people have since the flow clearly says its failing due to that reason. 
But unfortunately flow always shows the first faiure there even if its caught. 
Please dive into that scope (App exists in tenant) and find where the terminating failure is, I have shown a sample of how to do that with another flow.

**Comment by PPTechy** [comment]
I have checked these failed flows; it seems these apps are not available in the environment, hence the error. From each environment, we are getting two apps with the failure error message "The app does not exist" error. From each environment, the below two apps are not found:

- **Dataverse Actions Page**
- **Overview**

I have checked these apps manually for each environment, but they are not available. My question is: can we ignore this error? If these apps are not available in the given environment, where is the "**SYNC HELPER-Apps Flow** (CoE flow)" getting these app details?

**Comment by PPTechy** [comment]
Please see the below screenshots, where it is throwing error:

FLowname: SYNC HELPER - Apps


<img width="574" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/ceeed237-14e7-47bf-ae96-5dcad10723a0">

FLowname: SYNC HELPER - Apps

<img width="774" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/d5ba898a-8085-455c-9e84-2acbc5e9dff2">

From each environment, getting the above two errors saying that "**Overview**" and "**Dataverse Actions Page**" PowerApps app are not found.

**Comment by Jenefer-Monroe** [comment]
The error under "Run Details" pane is the first error seen in the flow. As described above it is a caught error so you can ignore that. 
The terminating failure is the Upsert App record one.

**Comment by Jenefer-Monroe** [comment]
Can you please resubmit the run? This is an upsert which means it should update or insert, so it should not ever see this message. But perhaps two instances ran at the same time and both tried to insert

**Comment by PPTechy** [comment]
Yes, when I am resubmitting both the instances one by one, the flow ran status is successful but the "**Inventory this app**" scope action is in error state for the instances. Is it normal, can we ignore it? As this is working while resubmitting but not while running automatically everyday - how can we run it automatically without errors?

<img width="663" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/28768acf-f78d-481c-a4fb-6926190e4a9d">

As these errors are captured using the "**Active sync flows error**" , we are getting emails every day regarding these errors; how can we get rid of this error from emails?

**Comment by Jenefer-Monroe** [comment]
No I had just hoped that the rerun would fix it. Your Update call is not behaving correctly. Dataverse updates are supposed to do an upsert as shown by this test flow where I create a fake GUID and use **_update a row_** to insert a new fake app
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c6fbe693-7722-4f7e-a993-a32dadfb146d)

**Comment by Jenefer-Monroe** [comment]
If this is only happening to a few apps you can fix it up by manually adding a record for these but I think you should probably contact product support. Let me help you with both of those by creating a flow outside of the kit

**Comment by Jenefer-Monroe** [comment]
Create a new flow "Test bug behavior" with a Manual trigger
add a new step > Microsoft Dataverse connector > Update a row action: Table > PowerApps Apps

Put these for the inputs so that they will get fixed up next run
Row ID: the GUID from your failure
App Environment (Environments) : admin_environments(GUID OF YOUR APPS ENVT)
Inventory Me: Yes

Then run the flow

**_If it fails_** 
- open a support ticket with this and let them know your updates arent behaving as upserts
- create a new flow with insert a row instead with the same inputs so you will be unblocked

**_If it passes:_** 
let me know so we can see why its not working for you in the COE

**Comment by PPTechy** [comment]
I have created a sample flow as per your steps, and it ran successfully:

<img width="776" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/d21f2c0c-2a82-4100-830b-1ef5d597e433">

**Comment by Jenefer-Monroe** [comment]
I'm not sure, this is definately a unique issue. 
If you run the SYNC HELPER - Apps failure above does it pass now?

**Comment by PPTechy** [comment]
When I am re-submitting the failed flow, it passes through, it was same until yesterday also. But when the flow "**SYNC HELPER - Apps**" runs automatically through the CoE process, it doesn't pass through.

**Comment by Jenefer-Monroe** [comment]
That step still fails? Sorry that was my question. And what is the error now?

**Comment by PPTechy** [comment]
Everyday automatically runs at the specific time but today it didn't run yet - it is almost one hour pass from the daily specified run time. What could be wrong here? Or we need to wait till it runs automatically?

**Comment by Jenefer-Monroe** [comment]
I see I thought you were resubmitting it. If its in the inventory now it wont auto-rerun. 
Can you find the run above and hit resubmit? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/976148fd-6e86-405b-9dcb-85d8d09ef76f)

**Comment by Jenefer-Monroe** [comment]
Please also go to the flow and look for unmanaged layers
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c3eb6e20-dc61-4821-964d-d81e6aa589f7)

**Comment by PPTechy** [comment]
When I resubmit the failed flow - it works. What I need to check in "See solution layers"?

**Comment by Jenefer-Monroe** [comment]
just show me what you see there
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/674b7da4-21d2-4519-8c49-ae2103b529b5)

**Comment by PPTechy** [comment]
Ok, no, solution layers - it is empty, please see below:

**SYNC HELPER - Cloud Flows**

<img width="704" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/df314b13-41fe-4c0d-8c13-70a4dde3f008">

**SYNC HELPER - Apps**

<img width="702" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/8f8cd971-6c81-4569-a043-bddbac758b07">

**Comment by PPTechy** [comment]
Today, the "SYNC HELPER - Apps" flow didn't run automatically, so we didn't see any errors. Is this expected behavior? When will it run automatically again?

**Comment by Jenefer-Monroe** [comment]
back in that failure rather than showing me the failure on the right, since that is not for this action, please show me the outout for that call which would be below
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/389b608b-53c8-45c3-971e-1e1aa0140c50)

**Comment by PPTechy** [comment]
This is the error in that output:

{
  "error": {
    "code": "0x80040217",
    "message": "Entity 'admin_Maker' With Id = 00000000-0000-0000-0000-8187dbb02gde Does Not Exist",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "Entity 'admin_Maker' With Id = 00000000-0000-0000-0000-8187dbb02gde Does Not Exist"
  }
}

**Comment by Jenefer-Monroe** [comment]
oh got it, we were chasing the wrong issue as I got confused with the error shown v what the actual error was. 
We resolved some issues around user detection and mapping in recent builds so you should not see this error any longer when you upgrade. 
With a June build you are due for an upgrade anyway we do recommend upgrading at least every 3 months. 

Do note if you are using the audit logs solution you will hit this known issue on upgrade this time but its normally smooth. 
https://github.com/microsoft/coe-starter-kit/issues/6018

**Comment by PPTechy** [comment]
Is it ok to live with for some days with the current version of the solution? Today, the "SYNC HELPER - Apps" flow didn't run automatically, so we didn't see any errors. Is this expected behavior? When will it run automatically again? 

Note: Now, we are not using audit logs only using the core solution.

**Comment by Jenefer-Monroe** [comment]
Great then upgrade will be smooth for you. 
Yes you can ignore these failures, even if new ones pop up. You will just be missing these records until you upgrade and then it will catch up. 
As long as this flow is running, your inventory is going: **_Admin | Sync Template v3 (Driver)_**

**Comment by Jenefer-Monroe** [comment]
Yes you'll continue to see these until you upgrade again.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by PPTechy** [comment]
As part of upgrade we need to download the [latest version of CoEStarterKit](https://aka.ms/CoeStarterKitDownload), and upgrade the core solution. I was referring this [article ](https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup)about the upgrade process, but there it not mentioned about "**Creator Kit**" solution upgrade, already we have installed the "**Creator Kit**" solution few months back, and we have this creator Kit version "**1.0.20230421.1**". So, before upgrading the starter kit core solution, should we upgrade the "**Creator Kit**" solution as well? Or, it is not needed to upgrade? Please suggest on this.
