### ISSUE TITLE
[CoE Starter Kit - BUG] Issue while upgrading COE kit from 4.6 to 4.16

### ISSUE THREAD

**Issue by sambhrama28** [microsoft/coe-starter-kit#6892]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Team,

I am trying to upgrade COE kit from 4.6 to 4.16  and facing dependency issue.

We have created some of the flow and app which are dependent on the COE kit Dataverse tables. Now we are getting issues because of these apps and flow. Is there a way we can upgrade the solution without disturbing the customization?

Also noticed that i am getting 2 solutions one for 4.6 and another one for 4.16 if i try to import.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.6

### What app or flow are you having the issue with?

No issues with flow

### What method are you using to get inventory and telemetry?

Cloud flows

AB#247

**Comment by Jenefer-Monroe** [comment]
Hello, when an upgrade fails it typically leaves you in a state where you have two solutions installed
They both have the same "Display Name" but in the "Name" column you will see the later one as **CenterofExcellenceCoreComponents_Upgrade**. That is just the product behavior. 

There is a known upgrade blocker described here: https://github.com/microsoft/coe-starter-kit/issues/6018
Not sure if that is what you are seeing. 

Without more details I'm afraid I cant help more than that.

**Comment by sambhrama28** [comment]
Hello Jenefer,
In my scenario both the solution is present even after couple of days of trying to upgrade but that's not an issue as of now.

My original query here is I have created couple of flows and apps which are connected to Maker and App tables from COE kit, now because of these apps and flow connections/reference i am unable to delete the old COE kit solution.  Is there a way to delete old COE kit solution without removing the app and flow i have created for COE kit Dataverse's tables. 

Even i have tries to import some of the flows i have created but not getting the import option.

**Comment by Jenefer-Monroe** [comment]
The second one will never go away on its own. You need to fix things and then apply the upgrade or delete it, fix things, and re-import.

The short answer is yes, its possible to customize the kit and still receive updates. However you have to be care with the dependencies. And how to do that is completely dependent on the changes you made. You would need to examine each failure from the upgrade and fix them one by one. 

Perhaps you are using a field that no longer exists and you would need to re-add it or a connection reference that was removed and you can just point it to a new one.

Unfortunately thats not something we can help with here very easily. But if you download the log from the upgrade failure that would be where to start, and point you to which objects need addressed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by sambhrama28** [comment]
Hello Jennifer,

Thank you for the info. Having two solution is product behavior? I am bit confused here.
