### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can CoE kit use a service account with on-prem Exchange?

### ISSUE THREAD

**Issue by DigPacksPhilMVP** [microsoft/coe-starter-kit#6894]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can CoE kit use a service account with on-prem Exchange?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#257

**Comment by Jenefer-Monroe** [comment]
I don't think the connection is the same for sending mail and we do send mail as the service account running the kit so I don't think it would work. However we have not tested this so I'm just not sure.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
