### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL: Add a way to go back further for usage information

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#6899]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Team,  

We are using BYOLD inventory from April and datalake flows were setup, In new COE October release we see the App Launches for the apps is only captured from past 3 months and not from the begininning of the datalake setup. Could you please help us to get the app launches data from April month.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

app

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Hello Team,  

We are using BYOLD inventory from April and datalake flows were setup, In new COE October release we see the App Launches for the apps is only captured from past 3 months and not from the begininning of the datalake setup. Could you please help us to get the app launches data from April month.

AB#265

**Comment by ALSPowerPlatform** [comment]
April Month we have set up datalake BYODL, please see the below image with older date.

<img width="712" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/03f1c3b6-f5a7-4501-87d6-049e265a2cf1">

**Comment by Jenefer-Monroe** [comment]
Open your PBI in the desktop and click Transform data
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a086d75a-c5d5-44e5-8738-93c6f6765e61)

Go to the query and step shown here. What is the first date you see?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a99366b7-da6b-409c-9c07-84e088c8982c)

**Comment by ALSPowerPlatform** [comment]
We can see the last launch date from 1st August only as shown in the below screenshot.

<img width="643" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/d28d97a8-0d1c-4d4b-b15e-0df1a77e88af">

**Comment by Jenefer-Monroe** [comment]
ok thank you. the owner of this area is back early next week so we'll look into this when she is here.

**Comment by ALSPowerPlatform** [comment]
Could you please update us on the issue.

**Comment by Jenefer-Monroe** [comment]
Hello, please note the CoE Starter Kit is an unsupported set of templates: https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support 

We do best effort to assist our GitHub customers but we do not have SLA. 

Thank you for your patience

**Comment by ALSPowerPlatform** [comment]
Could you please help us if owner of this area is back to check on this.

**Comment by Jenefer-Monroe** [comment]
moving to consider with Dataflow rewrite for Dec

**Comment by ALSPowerPlatform** [comment]
It means we need to wait for December release for this fix?

**Comment by Jenefer-Monroe** [comment]
We have not been able to fund a way to go back further. Adding as a feature for the backlog.
