### ISSUE TITLE
[CoE Starter Kit - BUG]  Import solution fails with error:  DataflowId already exists under a different environment

### ISSUE THREAD

**Issue by GithMen** [microsoft/coe-starter-kit#6901]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

I´m currently upgrading the starter kit to the newest version (october release) and ran into an issue, while trying to import the core solution. I get the following error: Code: BadRequest Content: DataflowId already exists under a different environment.
I am using 2 different Environments (DEV and PRD), dev environnement is duplicated from PRD Environment.
The error most likely came from environnement duplicating instead of creating a new one from scratch.

Do you have any suggestions or idea how I could fix this error ?

Do you think that i can bypass error with these following solutions :

- Re importing the solution and choosing update instead of upgrade. ( solution 1)
 - Deleting all coe kit components ( i have installed only core and audit components) and re installing it from scratch.( solution 2)
Thanks;

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Core solution 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#267

**Comment by Jenefer-Monroe** [comment]
That is a strange issue we’ve seen people hit a few times but have never hit ourselves even though we import the kit into many environments in the same tenant quite a bit. 
We found this discussion about it, with a person that found a way around. It has helped others, can you see if that helps you as well? 
https://powerusers.microsoft.com/t5/Microsoft-Dataverse/Cannot-import-solution-containing-Dataflow-Error-Code-80040265/td-p/1606090

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by javiles1327** [comment]
We are getting this too, but only with the Update option.  With the default Upgrade option, it tells us that both the imported and existing solution need to be managed, but we are unable to find any unmanaged layers within our solution
