### ISSUE TITLE
[ALM Accelerator - BUG]: Error when I click in Button Import Solution unmaneged

### ISSUE THREAD

**Issue by will-franca** [microsoft/coe-starter-kit#6902]
### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/135626493/b9a71877-1ac6-48f8-a354-527a2615b823)

I am getting an error i am going to import a solution when not managing in unmanaged environment through Import Solution button.

Message Error:
Error running pipeline (): { "statusCode": 404, "message": "Resource not found" }

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231011.5

### Steps To Reproduce

1.Import Solution.
2.
![image](https://github.com/microsoft/coe-starter-kit/assets/135626493/58ee2404-f29d-4c7b-8fde-73e25e0a6819)

3. Click Import solution.

AB#268

**Comment by RajeevPentyala** [comment]
@will-franca Thanks for reporting the issue. Will check at our end and get back to you soon.

**Comment by RajeevPentyala** [comment]
@will-franca It seems that the 'import-unmanaged-to-dev-environment' pipeline is missing from your Azure DevOps repository. Could you please check and confirm? If you don't find 'import-unmanaged-to-dev-environment,' you might need to redeploy the latest 'ALM Accelerator' build.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/0000a755-3356-4926-affb-92980a5c52fd)

**Comment by RajeevPentyala** [comment]
@will-franca Did you get a chance to check my comment?

**Comment by RajeevPentyala** [comment]
@will-franca Closing this issue as there has been no update from your side. Please feel free to reopen or create a new issue if you are still facing the problem.
