### ISSUE TITLE
[CoE Starter Kit - Feature]: Licensing

### ISSUE THREAD

**Issue by dksamo1986** [microsoft/coe-starter-kit#6905]
### Is your feature request related to a problem? Please describe.

Currently, it's almost impossible to tell which solutions/Apps/Environments are using an per user license or App passes (formerly per app license). So, we cannot see how license are actually being consumed on the Power Platform. A good example could be we have an environment that has app passes and there is a user that is using 3 or more apps that require a license. At some point, it makes more sense to give the user a per user licenses. This would also help us see if we need to purchase more licenses on the Power Platform.  

### Describe the solution you'd like

I am thinking if we could add some new reports on the Power BI Dashboard governance or Power Platform View that can show licenses consumed by:

1. Individual users (showing whether they are consuming passes or per user license). 
2. If using passes in an environment, how many are consumed vs available. 
3. If using passes, show how many passes an individual user is using, so we can decide whether we should unassign the app pass and give the user a per user license. 

### Describe alternatives you've considered

Currently, we can see in the admin center under licenses per environment. But, it's not possible to get an overview per user - which would be way more beneficial. We have also asked our Microsoft partner and they were not aware of any current solution. 

It's hard for us to decide whether we need more licenses and whether we should shift a user licensing because he is more active on the Power Platform. 

AB#272

**Comment by Jenefer-Monroe** [comment]
Hello. This is a super common ask but unfortunately this information isnt given to us in a programmatic way that we can consume for the kit.

**Comment by dksamo1986** [comment]
Hi Jenefer,

Thank you for your response. 

Unfortunately, I am not sure where this data is available. And I am not sure who I can communicate this. Any ideas? 

Best regards,

Sabri Moussi

**Comment by Jenefer-Monroe** [comment]
Unfortunately I dont think this information is easily available. 
If you post this in the user forums you may be able to garner attention for a feature to enable this though: https://powerusers.microsoft.com

**Comment by dksamo1986** [comment]
Okay - great. Thanks for the assistance, Jenefer. 

Best regards,

Sabri Moussi

**Comment by Jenefer-Monroe** [comment]
You're welcome, sorry I couldnt bring better news. I'll go ahead and close out but please do return with new issues if you have other questions in the future.
