### ISSUE TITLE
[CoE Starter Kit - QUESTION] Would the app GUID change after upgrading?

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#6908]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi CAT,

I would like to ask this general question: Would the app GUID change after upgrading? Or it will always stay the same? 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

September 2023

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#275

**Comment by Jenefer-Monroe** [comment]
We arent able to really answer all the generalized product questions I'm afraid. You may be better served asking in the community channels as a result. https://powerusers.microsoft.com 

But I can try! I've noticed some links break on upgrade but none of the ones we rely on for our feature set. 
Can you comment on what GUID you are specifically referencing?

**Comment by Jenefer-Monroe** [comment]
https://github.com/microsoft/coe-starter-kit/issues/6899
