### ISSUE TITLE
[ALM Accelerator - QUESTION] When creating a new Project Wizard is a new Devops project required, can we not use any existing project?

### ISSUE THREAD

**Issue by Tamy05** [microsoft/coe-starter-kit#6910]
### What is your question?

Getting-->Please use new or existing empty project, while adding a project Wizard? 
We have an existing ADO Project that we want to use for the new creation and to run pipelines for can we not include that, and can you please elaborate on empty project or uninitialized one, if so can I make the existing one that?
Could you please help me with that

![image](https://github.com/microsoft/coe-starter-kit/assets/146843228/3dc6d0f0-547f-41cc-8452-21fd49dd8c48)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Latest

AB#280

**Comment by RajeevPentyala** [comment]
@Tamy05 Connect to the AzDo project, and open the default repo (i.e., Repo with project's name). It should be un-initialized as shown below.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/2f121d05-e0ab-4bf5-a1f6-31cbb75c1463)

The reason it requires an uninitialized project is to avoid deleting or overwriting existing files from the App.

**Comment by RajeevPentyala** [comment]
@tamy05 Please let me know if you got the required details or need any additional info.

**Comment by mnhnielsen** [comment]
> @Tamy05 Connect to the AzDo project, and open the default repo (i.e., Repo with project's name). It should be un-initialized as shown below. ![image](https://user-images.githubusercontent.com/104883923/278293180-2f121d05-e0ab-4bf5-a1f6-31cbb75c1463.png)
> 
> The reason it requires an uninitialized project is to avoid deleting or overwriting existing files from the App.

So it would not be possible to create the setup with existing projects that are being used and previously not have had any alm pipelines?

**Comment by mikefactorial** [comment]
@mnhnielsen currently the Project setup application doesn't support initializing an existing project. You would need to manually initialize the existing project using the instructions here https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#clone-the-yaml-pipelines-from-github-to-your-azure-devops-instance.

**Comment by Tamy05** [comment]
What is the Clone URL needed to be added here?
![image](https://github.com/microsoft/coe-starter-kit/assets/146843228/90ec8bde-1481-4436-b1eb-d3b3626e4af2)
I'm getting an error while adding the url can you please help with what to add here?

**Comment by mnhnielsen** [comment]
> What is the Clone URL needed to be added here? ![image](https://user-images.githubusercontent.com/146843228/279301448-90ec8bde-1481-4436-b1eb-d3b3626e4af2.png) I'm getting an error while adding the url can you please help with what to add here?

This one
https://github.com/microsoft/coe-alm-accelerator-templates.git

**Comment by mnhnielsen** [comment]
> @mnhnielsen currently the Project setup application doesn't support initializing an existing project. You would need to manually initialize the existing project using the instructions here https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#clone-the-yaml-pipelines-from-github-to-your-azure-devops-instance.

Alright. So, am I understanding this right: Each time I want a new Power App solution to work with the ALM Accelerator I need to manually configure the solution setup if the solution should reside in an Azure DevOps project that isn't empty?: https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#solution-setup

**Comment by Tamy05** [comment]
Thankyou for your reply @mnhneilsen, have you done the setup? I
'm stuck on adding the Project repo here needed some guidance on this, any help would be greatly appreciated!
Like why a new one is required and what he next steps should be after the above thing is completed

**Comment by mikefactorial** [comment]
@mnhnielsen the solution setup instructions are no longer necessary to manually perform. Will likely need to remove those sections since the initial export is responsible for creating the pipelines now. You can safely skip those steps for any new or existing solutions.

**Comment by mnhnielsen** [comment]
> Thankyou for your reply @mnhneilsen, have you done the setup? I 'm stuck on adding the Project repo here needed some guidance on this, any help would be greatly appreciated! Like why a new one is required and what he next steps should be after the above thing is completed

Yeah I am almost done. Well I guess you have to clone the repo in as it contains a lot of pipeline templates for configuration in the ALM Admin app. I ended up creating a new project for the Power Apps solutions to be in as I had some difficulties setting it up manually. So I just followed the guide using the Admin App:
https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks

**Comment by Tamy05** [comment]
Need help or any kind of assistance with these steps after this above mentioned steps are done @mikefactorial @RajeevPentyala Please guys any help would be greatly appreciated!

**Comment by RajeevPentyala** [comment]
> Need help or any kind of assistance with these steps after this above mentioned steps are done @mikefactorial @RajeevPentyala Please guys any help would be greatly appreciated!

@Tamy05 Please reach out to me at rajeevpe(at)microsoft(dot)com.

**Comment by Tamy05** [comment]
Thanks for the quick reply emailed you with the details, @RajeevPentyala ! Tamanna here!

**Comment by Tamy05** [comment]
HI team, @RajeevPentyala @mikefactorial How important these following extensions are going forward in the setup 
![image](https://github.com/microsoft/coe-starter-kit/assets/146843228/43577489-fb46-40a5-a297-46b50a3c0044)
Could you please help me with the clarity on that?

**Comment by Tamy05** [comment]
@mnhnielsen Could you please help with that further? After we set it up?

**Comment by Tamy05** [comment]
Hello Team @mikefactorial @RajeevPentyala What exactly are in this steps to be done after a new project is created, as i went through the steps not mentioned which service connections and Pipelines this creates and what to give once we do that, Can you please help with that!
![image](https://github.com/microsoft/coe-starter-kit/assets/146843228/f0971062-2a3f-4234-bf1d-17bc1c223e02)

**Comment by RajeevPentyala** [comment]
> Hello Team @mikefactorial @RajeevPentyala What exactly are in this steps to be done after a new project is created, as i went through the steps not mentioned which service connections and Pipelines this creates and what to give once we do that, Can you please help with that! ![image](https://user-images.githubusercontent.com/146843228/281628419-f0971062-2a3f-4234-bf1d-17bc1c223e02.png)

@Tamy05 As discussed on the call, 'Service Connections' are required to link your pipelines to Dataverse environments. Closing the ticket now. Feel free to reach out for any further assistance.
