### ISSUE TITLE
[CoE Starter Kit - BUG] DLP impact analysis app showing different connector counts than Power Platform admin center

### ISSUE THREAD

**Issue by bilodeauju** [microsoft/coe-starter-kit#6911]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I noticed when testing editing a policy in the the DLP impact analysis app that is showing different counts of connectors for Business, Non-business and Blocked groups compared to the Power Platform Admin Center (PPAC). Also when adding up the count of connectors shown in each group, the totals don't match (1129 connectors in PPAC vs 1100 connectors in DLP impact analysis app)

Here are some examples of side by side comparison between PPAC on the left and DLP Impact analysis app on the right. 

In this example it is showing 0 Business connectors in PPAC and 1 Business connector count in DLP Impact analysis app, however in the list below it states "No matching connectors found" despite the count above being "1". Non business and Blocked counts also do not match. This policy was last modified on 9/27/2023 in PPAC so there are no recent changes. 
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/cce12ac6-4d07-4cd7-88c4-09578de992d6)

Here is another example where is is showing 3 non-business connectors in PPAC and showing a count of 4 in DLP Impact analysis app but only 3 in the list below. 
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/4020b364-612a-4d84-83d6-4b619f695e1c)

Here is another example of connector count mismatch for our default policy. 
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/af46c77b-14e1-4745-a1b3-4c123a78c2d6)

### Expected Behavior

The connector counts for each group in the DLP Impact analysis app should match with the connector count in PPAC. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

 4.16

### What app or flow are you having the issue with?

DLP Impact analysis

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the DLP impact analysis app
2. Select a policy and click edit
3. Click next to the Connectors section
4. Compare the connector counts with the same policy in PPAC

### Anything else?

I have another test environment where the COE starter kit is configured with Data Export and I notice the exact same issue with the DLP Impact analysis app in both environments. 

AB#281

**Comment by Jenefer-Monroe** [comment]
Sending to area owner to investigate when they return from leave
