### ISSUE TITLE
[ALM Accelerator - BUG]: Infinite loop of calls to /GetClientMetadata in Admin app

### ISSUE THREAD

**Issue by cjbadger** [microsoft/coe-starter-kit#6912]
### Describe the issue

Hi there, 

_Please note that this concerns the Admin app, not the canvas app, but the former does not appear as an option in the predefined issue fields._

Some users are unable load the 'Azure DevOps Projects' page in the ALM Accelerator for Power Platform Administration MDA (the [cat_azuredevopsprojects_80ae5](https://github.com/microsoft/coe-starter-kit/tree/main/CenterofExcellenceALMAccelerator/SolutionPackage/src/CanvasApps/src/cat_azuredevopsprojects_80ae5) custom page). When selecting 'Projects' from the site map, the page does not load in the main pane. On checking the browser's Network tab, there is a stream of identical requests to the following endpoint (some parameters have been redacted as noted):

https://**`{DOMAIN REDACTED}`**.crm6.dynamics.com.mcas.ms/api/data/v9.0/GetClientMetadata(ClientMetadataQuery=@ClientMetadataQuery)?@ClientMetadataQuery={%22MetadataType%22%3A%22resourcestring%22,%22GetDefault%22%3Afalse,%22ChangedAfter%22%3A%2214101500%22,%22AppId%22%3A%**`{GUID REDACTED}`%22}**&umv=14101500&mv=14962545&rde=1&api-version=9.1&McasCtx=2&McasUserAuth=**`{TOKEN REDACTED}`**

Decoded, the query string parameters are as follows (with redactions as noted):

- @ClientMetadataQuery: {"MetadataType":"resourcestring","GetDefault":false,"ChangedAfter":"14101500","AppId":"**`{GUID REDACTED}`**"}
- umv: 14101500
- mv: 14962545
- rde: 1
- api-version: 9.1
- McasCtx: 2
- McasUserAuth: **`{TOKEN REDACTED}`**

These continue indefinititely at a rate of approximately 50 per second, until the user navigates away from the Projects page. 

All responses to these requests are identical and are as follows:
```json
{"@odata.context":"https://{DOMAIN REDACTED}.crm6.dynamics.com/api/data/v9.0/$metadata#Microsoft.Dynamics.CRM.GetClientMetadataResponse",
"Metadata": 
{}
}
```

There are currently three users of the application; two users are affected:
- The **unaffected** user has a System Administrator role in the environment.
- The **affected** users do not have a System Admininistrator role in the environment; they have the following roles:
    - ALM Power App Deployment Configuration
    - ALM Power App Access
    - Power Platform Maker SR
    - Power Platform User SR
    - Environment Maker
    - Basic User

Here is an example of what's appearing in the Network tab of an affected user's browser's dev tools:

<img width="962" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/94421801/a819c875-9c74-4d73-b2cb-e795494f2910">

### Expected Behavior

The 'Azure DevOps Projects' custom page should be rendered in the Model Driven App. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

October 2023

### Steps To Reproduce

1. Go to the make.powerapps.com and select the environment in which the ALM Accelerator has been installed and configured.
2. Sign in using credentials for a User account that does not have System Administrator security role assigned, but which has the following Security Roles assigned: ALM Power App Deployment ConfigurationALM Power App Access, Power Platform Maker SR, Power Platform User SR, Environment Maker, Basic User.
3. Select 'Apps'
4. Select 'All' from the Apps grid filter
5. Click the vertical ellipsis in the row for the 'ALM Accelerator for Power Platform Administration' app, and select 'Play'
6. From the site map, under the heading 'Azure DevOps', click 'Projects'

### Anything else?

We have successfully deployed and used the ALM Accelerator without issue in our own environment, but this is an instance that has been deployed to a client's environment in which other factors may be in play, such as more restrictive security policies.

AB#282

**Comment by RajeevPentyala** [comment]
@cjbadger Thanks for reporting this issue. We will check and revert.

**Comment by cjbadger** [comment]
Hi @RajeevPentyala - just on my point re: this being an issue in a client's environment in which more restrictive security policies might be in place, it's probably worth pointing out that this is occurring in mcas.ms suffixed domain.

**Comment by RajeevPentyala** [comment]
> Hi @RajeevPentyala - just on my point re: this being an issue in a client's environment in which more restrictive security policies might be in place, it's probably worth pointing out that this is occurring in an environment with a ".mcas.ms"-suffixed domain:
> 
> https://**`{DOMAIN REDACTED}`**.crm6.dynamics.com.mcas.ms/main.aspx?appid=**`{GUID REDACTED}`**&pagetype=entitylist&etn=cat_deploymentusersetting

@cjbadger Thanks for the details. We'll try to include this in our documentation. Closing the issue as no action items are identified currently. Feel free to contact us for any additional queries.

**Comment by cjbadger** [comment]
Hi @RajeevPentyala - does that mean this _is_ related to the app being accessed via a .mcas-ms domain? Is there any workaround?
