### ISSUE TITLE
[CoE Starter Kit - BUG] Error when updating connectors in policy using DLP Impact analysis app: PowerPlatformforAdmins.UpdatePolicyV2 failed DLPPolicyConnectorReferenceInvalid

### ISSUE THREAD

**Issue by bilodeauju** [microsoft/coe-starter-kit#6913]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When testing editing a policy in the DLP impact analysis app by moving a connector to a different group, I get an error at the last step when clicking on "Update Policy": 
PowerPlatformforAdmins.UpdatePolicyV2 failed: { "error": { "code": "DLPPolicyConnectorReferenceInvalid", "message": "The data loss policy connector reference is invalid for the request." } }

![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/af9fbbec-c60e-4a2a-bb31-8887e761e52f)

### Expected Behavior

The policy update should be successful when using an account with the proper admin permissions. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

DLP Impact analysis

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the DLP impact analysis app using an account with Power Platform Administrator role and Environment admin role. 
2. Select a policy and click edit
3. Click next to the Connectors section and move a connector to a different group. 
4. Click next until the last step and click on Update Policy.

### Anything else?

I have another test environment where the COE starter kit is configured with Data Export and I notice the exact same issue with the DLP Impact analysis app in both environments.

AB#283

**Comment by Jenefer-Monroe** [comment]
I dont repro so will set for area owner to investigate when they return from leave

**Comment by bilodeauju** [comment]
Hi @v-bjaiswal, thank you for looking into the issue. I can no longer repro the error today, I am still on the same version 4.16 so I'm not sure what would have changed. 

Now when I move a connector to a different group, click next to the last step and click the "Update policy" button on the "Review" page, nothing seems to happen and the app doesn't provide any confirmation message that the update was made, it just appears to be stuck on that last step. But if I go to see the policy directly in PPAC I can see the change was done successfully, so it is working now.

Now, after clicking "Update policy", since it just stays on this page without any confirmation the update is completed and doesn't take me back to the main screen, this is still somewhat confusing: 
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/5e7b6523-90ba-49ff-820a-ec6c42195d65)

I also confirmed all my connection references were connected and there were no issues there.

**Comment by RahulBojji** [comment]
@bilodeauju Thanks for the confirmation. If you feel, the experience of nothing is happening on click of update policy is an issue, can you please create a new bug or enhancement, and we can discuss it in that.

Thanks

**Comment by RahulBojji** [comment]
@bilodeauju Created this [issue](https://github.com/microsoft/coe-starter-kit/issues/7312) to track the issue where nothing happens on click of update policy

**Comment by RahulBojji** [comment]
closing out as no further action for starter kit team
