### ISSUE TITLE
App sessions, flow runs, total shared users data

### ISSUE THREAD

**Issue by S0URCEC0D3** [microsoft/coe-starter-kit#6914]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 

Which table in the COE contains the app usage, app sessions, shared with users, groups, flow runs. 

Asking for a friend :)

Thanks

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

August 2023

### What method are you using to get inventory and telemetry?

Cloud flows

AB#284

**Comment by Jenefer-Monroe** [comment]
For sync flow architecture, "Audit Logs" table stores the app launches from which usage is derived
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a38f1300-9f7a-40b9-826c-7c47b26947d2)

Power Platform User Role stores information about shared with users, groups
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/67b7b687-713d-4734-99b1-b2a407a1d91a)

And we dont store flow run information anywhere. It's only available for BYODL and we dont write it back from the Dataflows at all, we only derive in there and write back properties to the flows.

Hope that helps your friend :)

**Comment by S0URCEC0D3** [comment]
Hi Jenefer, can I pull this data directly into an app? or is something I will need to manipulate to show that data?

**Comment by Jenefer-Monroe** [comment]
You certainly can pull any of this data into apps to make your own, thats quite encourages since we do believe we are a starter kit for your admin needs. If you need to manipulate the data will depend on what you are trying to do with it. 
I'm not sure what you mean by sessions, but the only data we have about sessions / launches, its what is in the Audit Logs table.

**Comment by S0URCEC0D3** [comment]
Does the Audit Log provide any info for flows or is it just for Power Apps?

**Comment by Jenefer-Monroe** [comment]
Just Canvas Power Apps unfortunately. The flow team is working on writing some information about runs to a Dataverse table for us to consume but no idea when that might be.

**Comment by S0URCEC0D3** [comment]
Gotcha - thank you Jenefer for the info!
