### ISSUE TITLE
[CoE Starter Kit - QUESTION] Delete SharePoint Forms Apps

### ISSUE THREAD

**Issue by DorotheevanTriel1** [microsoft/coe-starter-kit#6918]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

While dealing with a clean-up for a client's tenant, I was wondering where I can delete SharePoint Forms Apps. SharePoint Forms Apps are the Power Platform resource most frequently created by accident. However, I do not find the source where to get rid of them. The Set App Permissions App only displays SharePoint Forms Apps when editing the Power Fx formula for the respective gallery but the corresponding flow to delete a resource runs on an error when I try to delete a SharePoint Form App. Also, I do not find any other way to set permissions for SharePoint Forms Apps or to delete them. Can you help me out on this question? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Set App Permissions

### What method are you using to get inventory and telemetry?

Data Export

AB#288

**Comment by DorotheevanTriel1** [comment]
Thanks @Jenefer-Monroe  for the reply. What if the site or list does not exist any more? And what, if the owner of the SharePoint Forms App is orphaned?

**Comment by Jenefer-Monroe** [comment]
Unfortunately this seems to be a product gap. I dont know any way to delete these once the list is deleted aside from restoring the SP list.
We are tracking that product gap here locally: https://github.com/microsoft/coe-starter-kit/issues/6493

If you post this in the user forum: https://powerusers.microsoft.com, you may be able to gather feedback from other admins to help address this gap. 

Sorry I dont have a better answer!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
