### ISSUE TITLE
[CoE Starter Kit] Cloud flows cache the value for environment variables and do not clear that cache until the flow is re-activated. 

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#692]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/659

<div type='discussions-op-text'>

<sup>Originally posted by **fz8975** June 18, 2021</sup>
Dataverse connector reference is appearing for around 20 apps in our tenant, (both in power BI and in Power Platform admin view) even though the apps don't have any connection to Dataverse. I tried to list down connectors using the **Get App as Admin**  for an app and Dataverse doesn't show up there(as expected). I have tried to update the app so the _Admin | Sync Template v3 (Apps)_ would pick it up and update the references but still Dataverse is appearing in connector reference for these apps.

I haven't see such issue with any other connector reference being reported incorrectly yet. 

Any ideas what might be wrong here?

I wasn't sure to put this in issues or discussion, </div>

**Comment by manuelap-msft** [comment]
@JeneferM-MSFT could you take a look at this issue (from the Discussion) where Full Inventory doesn't seem to be running? Thank you!

**Comment by JeneferM-MSFT** [comment]
looking now

**Comment by JeneferM-MSFT** [comment]
It is likely that same product bug around env vars getting solution layers. If so, we can re-ping product team.

**Comment by JeneferM-MSFT** [comment]
OK this is a product bug but not the one referenced above. 
Cloud flows cache the value for environment variables and do not clear that cache until the flow is re-activated. 
So until they fix that bug, in order to change the value of an env var, you will need to turn off and then turn back on all flows related to that env variable, or it will stick with the old value.

**Comment by JeneferM-MSFT** [comment]
closing out as there is no action for the toolkit and this is now documented in limitations.
