### ISSUE TITLE
[CoE Starter Kit - QUESTION] Republishing state resets to Requested

### ISSUE THREAD

**Issue by ortizh** [microsoft/coe-starter-kit#6923]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Republishing state under Governance resets to Requested. 

![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/e3058a68-3dcc-40aa-9d07-f80670b09fab)

On a weekly basis, makers receive an email asking them to republish any unpublished applications. Even after setting the Republishing status to Completed and/or None, the users are still receiving a notification and the status is resetting to Requested.

**How can we exempt applications from receiving the republishing notification email ?**

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

September 3.11

### What method are you using to get inventory and telemetry?

Cloud flows

AB#294

**Comment by Jenefer-Monroe** [comment]
What value do you have for this environment variable?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/153d10de-8cfc-4887-aa6d-de0b01de0358)

**Comment by ortizh** [comment]
Hi Jenefer, 

Thank you for your prompt responses, as always :)! 


Value : 180 
![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/fed40d6a-e6c1-430d-82be-636a94cd9485)

**Comment by Jenefer-Monroe** [comment]
I think this might be due to https://github.com/microsoft/coe-starter-kit/issues/5680

Can you please check on an app you expect to no longer be getting pinged for publishing, what does the inventory say its published date is? If it appears to be stale flag it for "Inventory Me" and that should resolve with the next inventory run.

**Comment by ortizh** [comment]
Hi Jenefer, 

Here ? Should I label it as "Yes" ? 

![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/deae8948-3779-4db2-8622-4394c01f1f75)

**Comment by Jenefer-Monroe** [comment]
Yes thats correct! Thats a flag we added to allow you to manually request an app be inventoried even if it hasnt changed recently. 
Once you set that, you'll wait for the next run of the inventory to complete, you'll see it reset to no and you can see if the published date is updated.

**Comment by ortizh** [comment]
Hi Jenefer, 

I'll give that a try! Thank you :)

**Comment by ortizh** [comment]
Hi @Jenefer-Monroe !

I have a very recent example of the above. 

User recently published the app as indicated below :
![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/d155ec21-4451-49eb-9098-8bace131415d)

On the Developer Compliance Center app, the user keeps on seeing "Republish needed" and he also received a notification via email to republish the app :

![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/5ab66ee5-61e2-46a4-902c-cce00eddae31)


On the Power Platform Admin View, I see that the publishing date was  3/3/2023  and the modified date was 10/11/2023. It looks like the CoE is capturing the modified date as the publishing date ? 
![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/e515e28e-1352-4607-955c-3a590956742c)

For this application the InventoryMe is set to No :
![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/cf8db24d-209f-460f-966d-97ca4f497ac8)

and the Admin Requirements-Republish State is set to Requested
![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/c4ab6335-e7d7-4555-99f2-8eba6997a7da)

Please note that I am on version 4.13 for the Core Components and 3.11 for Governance Components.

**Comment by Jenefer-Monroe** [comment]
Oh sorry I thought you were on Sept release which is Core 4.15. 
That is the build the published bug (https://github.com/microsoft/coe-starter-kit/issues/5680) was fixed in. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ea62c9c4-c96b-4081-9d2a-c75d87f0eee4)

You'll be able to see this fix on your next upgrade.
Sorry for the miscommunication!

**Comment by ortizh** [comment]
Hi Jenefer!

So far so good ! I see the updated publishing values. I will keep on monitoring for the upcoming weeks. 

Thank you for your guidance!
