### ISSUE TITLE
[CoE Starter Kit - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by jcgds** [microsoft/coe-starter-kit#6924]
### Is your feature request related to a problem? Please describe.

Admin | Capacity Alerts 

### Describe the solution you'd like

Olá,  ativei o fluxo de Admin Capacity Alerts do meu CoE, contudo, está ocorrendo o erro citado na imagem. Tentei encontrar algum workaround, mas não encontrei, por favor, existe algum procedimento que devo realizar? Obrigado! 

Estou utilizando o pacote CenterofExcellenceCoreComponents_4.16_managed. 
![AdminCapacity](https://github.com/microsoft/coe-starter-kit/assets/147111987/a3595fcd-7648-4598-89b2-272705bb43f6)

AB#295

**Comment by Jenefer-Monroe** [comment]
Hello I'm afraid I dont see an issue in the above. The flow is passing and writing to the metadata table successfully. That catch isnt running because its not needed. 
Please let me know if I am missing something.

**Comment by jcgds** [comment]
Jenefer, thank you, you're right. I was mistaken with the emails from the admin group. Thanks!

**Comment by jcgds** [comment]
Jenefer, thank you, you're right. I was mistaken with the emails from the admin group. Thanks!
