### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there any guide on how to expand the audit log capturing?

### ISSUE THREAD

**Issue by frcelaya** [microsoft/coe-starter-kit#6926]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there any guide on how to expand the audit log capturing? It seems our CoE is only capturing Power Apps launch events and we would like to capture Power Automate events as well.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#298

**Comment by Jenefer-Monroe** [comment]
We dont have a write up but it is a public API, here's a link for you to get started: 
https://learn.microsoft.com/office/office-365-management-api/office-365-management-activity-api-schema

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
