### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by iharabagiu** [microsoft/coe-starter-kit#6927]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Cannot see the Flows listed in the Flow Deep Dive Page on the Power Bi CoE Dashboard; the count shows up on the Explain flow by... visual; but nothing is displayed on the Flow Details

### Expected Behavior

The list of flows should show up, as it shows the apps in the App Deep Dive panel

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Power Bi

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open PBI Dashboard
2. Click on the Flow Deep Dive Panel
3. Look at the Flow Details page

AB#300

**Comment by Jenefer-Monroe** [comment]
I'm not sure I understand the issue, or I dont repro. Can you please check your filters? And share a screenshot of what you are seeing?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f5752e10-664c-4e04-866a-62f1bb0a2d58)

**Comment by iharabagiu** [comment]
i had filters added on the visual that i missed - thank you for the suggestion; this can be closed; thanks
