### ISSUE TITLE
[CoE Starter Kit - QUESTION] PowerBi Production_CoEDashboard_October2023

### ISSUE THREAD

**Issue by fim34** [microsoft/coe-starter-kit#6929]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,
I couldn't find the post that talked about this

we use the Production_CoEDashboard report for a view of all the environments and this same report limited by entity in the company which corresponded perfectly.
But having upgraded from the August version to the October one.
I've noticed that this report isn't the same at all and that there are fewer pages, the tables aren't the same and the columns aren't the same.
![old_new dahsboard](https://github.com/microsoft/coe-starter-kit/assets/89391607/ddb206ad-2211-467c-a800-258e6cfc26bc)

So I can't use the old one, which worked well for entities.
I'm trying to get closer to what the old one offered, but it's complicated.

For example, I had the top 20 makers for solutions that no longer worked, and I couldn't create the same relationship between the solutions tab and the makers tab that existed before.
![solution exemple](https://github.com/microsoft/coe-starter-kit/assets/89391607/704e48d1-a1c1-46be-bfa5-9496c7130524)
![table relation](https://github.com/microsoft/coe-starter-kit/assets/89391607/b6699837-ba17-4dee-97d9-5d8efc90e8e5)
![table](https://github.com/microsoft/coe-starter-kit/assets/89391607/75208aca-f240-438f-be5d-ef5adf75807b)

Other example The filters on right side no longer there

Is there any way of getting the old one working  with the new tables, or have the old version still ok in new release ?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.16 for core

### What app or flow are you having the issue with?

Power Bi Production_CoEDashboard_October2023

### What method are you using to get inventory and telemetry?

Cloud flows

AB#302

**Comment by Jenefer-Monroe** [comment]
The old version had a lot of relationship issues that made it very difficult to maintain and caused lots of issues for people when installing so we had perform a remake.

For the filters, they are still there we just used the pane version instead as its more versatile (ex supports "last two weeks", "top N", types of things)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e67cbf70-651f-4bd1-a113-21db4b84d201)

You do have everything you need to make that visual (top 20 solution makers). I used this report as a reference
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f6af256e-c23e-4977-a44a-bcf91d7fc791)

Like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7d6ed4cd-dbda-46c3-97f0-1a284f27be51)

Hope that helps

**Comment by fim34** [comment]
hi, 
ok, thx , will update it.
