### ISSUE TITLE
[CoE Starter Kit - BUG]: Could not able to create 'Microsoft Teams' connection while importing the latest solution

### ISSUE THREAD

**Issue by challa85** [microsoft/coe-starter-kit#693]
While I am trying to import/upgrade the latest CoE  Starter Kit solution in PowerApps environment it's prompting to add connection for 'Teams CoE Teams Integration' , 'Microsoft Teams CoE Connection' and when I tried to add the connection it's throwing me an alert like 'Something went wrong. Please try again later.'

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution  - Core Component
 - Version - CenterofExcellenceCoreComponents_2_1_70_managed
 

![image](https://user-images.githubusercontent.com/33087528/123318698-20895000-d54d-11eb-8704-83e8c6f45d1b.png)

![image](https://user-images.githubusercontent.com/33087528/123318721-2717c780-d54d-11eb-981f-fe66da6ac01f.png)

**Comment by JeneferM-MSFT** [comment]
I'm afraid this isnt a toolkit issue, there is just an issue for you creating a connector. 
I suggest you try to create the connector outside of the context of an install
- In your CoE environment go to Data > Connections > New Connection 
![image](https://user-images.githubusercontent.com/62659043/123320710-5c8dc800-d4ef-11eb-9eac-ef1dd91c3b3d.png)
- Search for Teams and hit +
![image](https://user-images.githubusercontent.com/62659043/123320799-78916980-d4ef-11eb-8844-fc86f190641d.png)
- Then create and chose the account you are trying to install with

**Comment by manuelap-msft** [comment]
Hello,

I see you are adding the connections with a Service Account - can you make sure that Service Account has a Teams license / Teams usage rights, otherwise you won't be able to add a connection here.

Thank you
Manuela

**Comment by challa85** [comment]
Hi Manuela,

I tried creating connections with Service Account and normal account, none of them worked. Not sure why I am not able to create the connection, can you please help me out. Is there a way where I can pull the logs and see what's happening behind that stopping me to create the Teams connections? also can you please let me know the purpose of the connections 1. CoE Core - Teams 2.Teams CoE Teams Integration 3. Microsoft Teams CoE Connection.

Thanks

**Comment by manuelap-msft** [comment]
Hello,

what you are experiencing is not an issue with the CoE Kit, but an issue with your account not being able to create a connection to Teams. If you are sure that you have a Microsoft Teams license assigned, you will need to raise a support ticket through regular support channels. Your issue is beyond the scope of what we are able to support here. 

The connections are used to get information from Teams environments, and send adaptive cards to Teams:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/teams-governance

Thank you for using the CoE
Manuela

**Comment by challa85** [comment]
Thanks for the update Manuela. Till today I am using Service account for importing/update the CoE solution and also the service account has Power Platform admin privileges. Now Teams connector came into picture(where service account does not have teams license) and  if I use my account for creating the Teams Connection, does my account should have privileges to read all the teams data(assuming my account is normal one and doesn't have any special privileges on Teams). In simple words can you please let me know what privileges does user should have who is going to create Teams connection for CoE Toolkit.
