### ISSUE TITLE
[CoE Starter Kit - BUG] Takes 24 hours for deleted Apps to be removed from Developer Compliance Center

### ISSUE THREAD

**Issue by DeVolk-D** [microsoft/coe-starter-kit#6934]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When deleting apps whether it be from within Developer Compliance Center or in make.powerapps.com it takes up to 24 hours for the Developer Compliance Center and Power Platform Admin View app to update since the inventory flows only run once daily.  Our users brought up there might be certain actions such as app deletions that they would like to see updated more quickly or ideally immediately. 

### Expected Behavior

When an app is deleted using the UI in Developer Compliance Center, it should be removed from the app view immediately and not need to wait for the inventory flow to be run. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.1.1

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#307

**Comment by Jenefer-Monroe** [comment]
Hello, this ask is captured by this feature request: https://github.com/microsoft/coe-starter-kit/issues/1994
Hope to be able to fund soon but we unfortunately have a bunch of competing work. 
Thanks for posting.

**Comment by mdphung** [comment]
This would definitely be a nice fix as people get confused when they think they did something but it doesn't show until later.

**Comment by Jenefer-Monroe** [comment]
Agreed! We do want to do this one too!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
