### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Center Republish Apps doesn't display the new version

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6935]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

1.	When an app is flagged as needing to be republished, we encountered an issue that if the user makes a change to the app and published a new version from within the app editor and doesn’t go to developer compliance center to republish the app from there the next run of the compliance flow does not pick up that the app was republished and still shows the app needing to be republished.

As you can see in the below screenshots the Dyn365T2P1-U1 Canvas Restricted Entity app is showing as needing republished even though an app publish happened on 10/18/23 it is still showing the app published date as being 2/3/20.  We waited for the compliance flow to run on 10/23/23 to see if it would catch that the app was published but it did not.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/da2cdb96-fbff-491f-80ac-4556ec38634f)

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/32412cf9-f21b-4d9f-92d0-bfef0d6330be)

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/e3aaaf88-07df-4ca1-9799-ea7e001f089e)

### Expected Behavior

We would have assumed that editing and republishing an app from within the app editor would clear out the request for an app to be republished the next time the compliance flow ran?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#308

**Comment by Jenefer-Monroe** [comment]
There was a bug in the way we fetch last published date which was resolved in the Sept release. 
https://github.com/microsoft/coe-starter-kit/issues/5680

After you upgrade to Sept release or later, you will need to flag these apps to be inventoried (with the InventoryMe flag) and then you will get teh correct lsat published date

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
