### ISSUE TITLE
[CoE Starter Kit - BUG]  Republish Used Power Apps Editor  No Change on Developer Compliance Center

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6936]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

If the user made a change to the app and did a republish within the app editor and then they went over to the Developer Compliance Center and clicked the republish button. We observed that the app would be removed from the Developer Compliance Center as needing republished. However, it would return to the Developer Compliance Center as needing republished when the compliance flow ran again the following week.
In this example, when the user would click the republish button in the Developer Compliance Center the app publish date would get set to the current date.  It would also remove it from the Developer Compliance Center as needing to be republished. However, once the compliance flow ran again the next week it would revert the App Published date back and it would show again in the compliance center as needing republished.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/1ef36344-1a56-46ba-8287-dcc850d1dfeb)

### Expected Behavior

Assumed that after I made an update on the app using power apps editor and republished that we would need to click the republish button on Developer Compliance Center was needed to “close” the republish task but in this case but it did not work it reverted next day.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#309

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
