### ISSUE TITLE
[CoE Starter Kit - BUG] App Editor and only saved but used the Developer Compliance Center Republish button still doesnt update

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#6937]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

A user makes a change to an app in the app editor and only does a save and doesn’t do a republish from within the app editor.  Then the user returns to the Developer Compliance Center and clicks the republish button.  In this scenario, the latest version of the app that was created earlier was then marked as being live and the app publish date was set and the app no longer showed in Developer Compliance Center as needing republished.  However, once the compliance flow ran the next week the app publish date was reverted and the app was showing as needing republished again.

As you can see in the below screenshots this app is showing with an old app publish date and is showing as needing republished after the compliance flow ran on 10/23/23 even though a version of it was made live after clicking the republish button on 10/19/23.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/f2b9bc2b-c0da-4600-8a98-dd07a6601284)

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/58182a62-09cd-4e0f-a215-27c12253f7b5)

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/314b2af4-61fd-4d47-af55-da706454882f)

### Expected Behavior

After Flows run it should pick up the newest version date and there should be no republish button in the app as it is confusing users as they can just click that and think that it is being republished versus they should go and fix there app and test and republish and let the app pick up the new date if there is one.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.11

### What app or flow are you having the issue with?

Developer Compliance

### What method are you using to get inventory and telemetry?

Cloud flows

AB#310

**Comment by Jenefer-Monroe** [comment]
There was a bug in the way we fetch last published date which was resolved in the Sept release. 
https://github.com/microsoft/coe-starter-kit/issues/5680

After you upgrade to Sept release or later, you will need to flag these apps to be inventoried (with the InventoryMe flag) and then you will get teh correct lsat published date

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
