### ISSUE TITLE
CoE Dashboard - Apps Details - Latest Launched not up to date

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#6938]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

CoE Dashboard, App Deep Dive - Apps Details - The Latest launch is not up to date, only shows up to the end of July this year.
Is there a CoE flow that needs to be turned on?
![image](https://github.com/microsoft/coe-starter-kit/assets/133137665/f4f365f5-e6f0-4aa9-87c0-d8b581c9fff8)

Thanks Team.

### Expected Behavior

Should be up to date

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#311

**Comment by Jenefer-Monroe** [comment]
Hello yes the Audit Log flows need to run. 
Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http) for the preferred methodology to collect audit logs.

**Comment by RyanCloud8888** [comment]
> Hello yes the Audit Log flows need to run. Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http) for the preferred methodology to collect audit logs.

Thanks Jenefer.  We used to use Customs connector.
I followed the document you recommended, now I registered an app.  Do I have to worry about the Variables that I have in the red rectangle?
![image](https://github.com/microsoft/coe-starter-kit/assets/133137665/50961421-168c-4616-86ac-5bb70dc3dbe2)

**Comment by RyanCloud8888** [comment]
> Hello yes the Audit Log flows need to run. Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http) for the preferred methodology to collect audit logs.

That did it.  Thank you, Jenefer.
