### ISSUE TITLE
Find flows that are not licensed correctly and will be shut down

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#6939]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are getting emails of flows that have been licensed incorrectly and will be shut down in 120 days.

Is there a way to find these flows in the Toolkit?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#312

**Comment by Jenefer-Monroe** [comment]
We do have a PBI report [Configure the Production and Governance Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-production-and-governance-power-bi-dashboard) that surfaces these as one of the reasons to be pending suspension. 
Hope that helps!
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cff1b6d9-7f45-47d3-bd85-447aa082ed7b)

**Comment by PPCan** [comment]
Nice! Can you tell me what flow is creating the data for this report?  Where did the compliance data come from?  The Powershell in the MS docs for this, is lacking display name for user and environment... not much fun.

**Comment by Jenefer-Monroe** [comment]
This is filled by these two flows:
- Admin | Sync Template v4 (Flows)
- SYNC HELPER - Cloud Flows

And was done in a way that it should be filling for you automatically as long as you have these flows turned on and running. 
Do you know what version of Core you have? You can see this on the solutions screen
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0b987b2d-cdfe-4275-9a72-429ef019295a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
