### ISSUE TITLE
[CoE Starter Kit - BUG] Total Shared With vs Unique Users

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#6940]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team, 

Below is my understanding of this concept: 
1) Count of session: # of app launch
2) Unique users: Unique users that have launched the app. These could be shared through a group. 
3) Total Shared With = # of users + users in groups

My question is how can a "total shared with" be smaller than "unique users." For example, how is it possible that there is 0 number of total shared with; however, have 35 unique users. Please advise. 

![image](https://github.com/microsoft/coe-starter-kit/assets/100535041/59ceb9d2-775c-41b0-ab29-147ca8faf983)

-Thanks 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

PowerBI CoE Production Dashboard 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#313

**Comment by Jenefer-Monroe** [comment]
It could be that the shared with has changed. The unique users is over time while the shared with is a snapshot. So if Jon used to have permission but no longer does for example. 
Can you browse to validate that the shared with there is correct?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by iamjina** [comment]
Hi team, 

Reopening this issue due to clarifications needed: 

The count of session is the number of app launch. Unique users are the individual users who have launched the app. Lastly, the total shared with is the total number of users + users in groups. 

The question is, how can #of Total Shared With be smaller than # of Unique Users (please refer to the screenshot above)? 

Thanks
