### ISSUE TITLE
[CoE Starter Kit - Feature]: Admin | Welcome Email v3 - Translation/Modification

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#6941]
### Is your feature request related to a problem? Please describe.

Hallo,

The welcome email is customizable or translatable from the Command Center app. However, it always adds "our Power Platform Community" at the bottom.
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/7b203066-f309-4404-9519-6167419598b5)

### Describe the solution you'd like

If the variable "Community" is not filled, the flow should still be usable.
The name of the link should be neutral or also customizable.

### Describe alternatives you've considered

For me it would be good, that the flow just sends out the modifiable text from the Command Center App and Links to Community, Wiki etc. could and should be added there

AB#314

**Comment by Jenefer-Monroe** [comment]
Unfortunately we dont have a way to make this section of the email customizable and we wouldnt want to change the mail at this point due to other people dependencies. 
For this one, I think your best bet would be to make a copy of the flow which does more specifically what you would like.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
