### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Sync Template v4 (Flows) - Failing for Teams environments that are disabled

### ISSUE THREAD

**Issue by Rajeshgn053** [microsoft/coe-starter-kit#6942]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

PROBLEM - The following flow, has an action to list down all the flows from environment. But the action fails for the "Teams" oriented environments (which are disabled).

Since, this category of environments are associated with "Teams", they do get influenced by the Microsoft policies, when the "Teams" goes inactive for certain period, leading to disabling them (in turn the respective D365 instances).

SOLUTION - We are checking D365 instance state, before moving forward with next steps. 

"Inventory flows for this envt", add a action "Get Environment as Admin - Check if still exists", add a condition called "Condition - if environment is not ready (disabled)" where @outputs('Get_Environment_as_Admin_-_Check_if_still_exists')?['body/properties/linkedEnvironmentMetadata/instanceState'] != "Ready", then put termianate action underneath condition in its' "If yes" branch "Terminate if Environment CDS entity is disabled". No actions on "If no" branch. Leave the remaining steps as it is.

This issue is similar to the one we have - https://github.com/microsoft/coe-starter-kit/issues/6756. But the solution implemented is little different, (Due to the 8th leven Nested loop limitation)

![image](https://github.com/microsoft/coe-starter-kit/assets/143060581/1df7e508-2b66-4e4a-b362-1e2d4919c0de)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#315

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, we'll track the fix with this bug: https://github.com/microsoft/coe-starter-kit/issues/6756
Appreciate you help as always.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team, tracked by the other bug
