### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can we enable Managed environment to CoE already installed environment ?

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#6943]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi 

we are trying to explore power pipelines in power platform. 

Part of this, we are decided to to test this feature in CoE installed environments 
we have one CoE Dev and CoE production. 

we are planning to convert production environment into Managed environment 

could you please help us in understanding if this is okay to enable CoE installed environment to Managed environment  ?. 
if we enable, this will not have any impact on CoE solutions ?
our CoE environments are admin driven  (most of the activities are performed by admin and have premium licenses )

if there are any negative impacts, please help us in understanding them because for us our CoE installed environment is important .

 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What method are you using to get inventory and telemetry?

Cloud flows

AB#331

**Comment by Jenefer-Monroe** [comment]
We have not tested this but I don't there there would be any impact here other than the obvious one in which anyone interacting with the environment needs a premium license, which is just an impact on any managed environments. 
If you try it on the dev first you might be able to see anything that isnt anticipated but I dont anticipate any issues.

**Comment by pamatihyd** [comment]
we are using Pay as  you go for Makers environment request *
![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/418f43e0-8dd5-446e-aa51-a806dc5921aa)

**Comment by Jenefer-Monroe** [comment]
OK looks like a limitation of Managed Environments. I'm afraid this is a product feature and not a feature of the kit so I cant really comment on it much. You may be able to get help from [product support](https://docs.microsoft.com/en-us/power-platform/admin/support-overview) or the [Power Platform Community](https://powerusers.microsoft.com)

**Comment by pamatihyd** [comment]
Yeah, but thank you thought of letting you know about this ..

**Comment by Jenefer-Monroe** [comment]
I appreciate it! Ill hold open for a few days in case you want to follow back with any more learnings for the community.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
