### ISSUE TITLE
[CoE Starter Kit - BUG] "Update a row" action is having duplicate key error

### ISSUE THREAD

**Issue by AnkitTotal** [microsoft/coe-starter-kit#6944]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow name : Admin | Audit Logs | Sync Audit Logs (V2)

The UPSERT action is not working as it should be for one flow particularly.
Error message on UPSERT :  "message": "A record with matching key values already exists.",
    

![image](https://github.com/microsoft/coe-starter-kit/assets/149079245/a73e30b7-d465-4b02-b5cd-330a9bbc8bd3)

### Expected Behavior

As expected the UPSERT should update the record as it already exists.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#332

**Comment by Jenefer-Monroe** [comment]
That is strange, I just validated that this is correctly an "Update a row" action, not an insert. So this error should never occur. 
Can you open the flow in edit mode and validate that its an "Update a row" action for you too?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9b43ca44-c214-453d-bc55-752e12aedc6b)

**Comment by AnkitTotal** [comment]
Hi Jenefer/team ,

Let me know if we can connect and show you the issue with screenshare.

Regards,
Ankit

**Comment by Jenefer-Monroe** [comment]
I'm afraid we are a very small, 2 person team, managing all 11k installs of the kit and so are not staffed to meet with our GitHub users to debug. We will have to manage here with back and forth. 
When you share your screenshot response please do log in to GitHub. If you respond by email the pictures will not come through.

**Comment by AnkitTotal** [comment]
Will share th escreenshot today

**Comment by AnkitTotal** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/149079245/2d186bf0-c2e7-48fa-a15d-14eb2c798597)
{
  "error": {
    "code": "0x80040237",
    "message": "A record with matching key values already exists.",
    "@Microsoft.PowerApps.CDS.ErrorDetails.SqlExceptionMessage": "Violation of PRIMARY KEY constraint 'PK_admin_AuditLogBase'. Cannot insert duplicate key in object 'dbo.admin_AuditLogBase'. The duplicate key value is <redacted>.",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040237&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "Cannot insert duplicate key."
  }
}

**Comment by Jenefer-Monroe** [comment]
Sorry the ask was to please open the flow in edit mode and validate that its an "Update a row" action for you too as shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9b43ca44-c214-453d-bc55-752e12aedc6b)

**Comment by Jenefer-Monroe** [comment]
Also please share the following
What solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)
And also please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by AnkitTotal** [comment]
Hi ,

Let us know if a Meeting can be set up for the display of details on the flow and also sharing other details.

Regards,
Ankit

**Comment by Jenefer-Monroe** [comment]
Unfortunately we are not staffed to meet with our GitHub users. We do best efforts to assist users here, but some people need more help, and hands on. If this is the case for you, you may want to consider reaching out to one of the partners who specializes in the CoE kit to assist.
[AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by AnkitTotal** [comment]
How can we reach out to that specialized partner of COE Kit. We need resolution to this issue.

**Comment by AnkitTotal** [comment]
Please reopen this ticket.

**Comment by Siddhesh-S21** [comment]
> Also please share the following What solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names ![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png) And also please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/ ![image](https://user-images.githubusercontent.com/89584709/237367659-4c23e8c8-2f8b-4d8b-af43-79a9f289be69.png)
> 
> Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. ![image](https://user-images.githubusercontent.com/89584709/261634052-598b5024-2e1a-4390-a6b2-49644368c246.png)

Hello, as per the requirement, I'm sharing the screenshots below:

1) It is the update action for us as well.
![image](https://github.com/microsoft/coe-starter-kit/assets/134070821/32c5fa6e-cd73-4bdd-8087-9f093492a1b7)


2) We have the May version of CoE Starter Kit installed with below 3 solutions.
![image](https://github.com/microsoft/coe-starter-kit/assets/134070821/4814958a-d335-48e2-b5b0-c6dbb5cc7b07)

3) The Region for our environment is Europe and it's a Production type environment.
![image](https://github.com/microsoft/coe-starter-kit/assets/134070821/b318605b-c628-4762-b64e-aaffcd829a55)
