### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by AnkitTotal** [microsoft/coe-starter-kit#6945]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v4 (Flows)
SYNC HELPER - Cloud Flows

Only fails for a particular flow: f9d27e7b-a0b9-41ee-8d06-05bc05ebd4b2
Looks no issue with Flow value in Dataverse as the value existes in Flow table. A childflow connected to this flow is throwing error for Parse Json action. Analysing for the same by comparing schema  with output of 'get flow by admin'.
Schema looks like an issue , couldnt find the difference from collected data fro, 'get flow as admin'. 

![image](https://github.com/microsoft/coe-starter-kit/assets/149079245/421e4635-e863-4e6a-9d55-3ebab0904057)
![image](https://github.com/microsoft/coe-starter-kit/assets/149079245/39fe0e93-9450-4f35-b735-1b97505b4ed8)

sync helper - cloud flow error

![image](https://github.com/microsoft/coe-starter-kit/assets/149079245/0e615c62-684a-45bb-a425-3552351836bc)

### Expected Behavior

Parent flow should not get failed as flow id exists in dataverse table. It throws parse json error .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows)  ,  SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

AB#333

**Comment by Jenefer-Monroe** [comment]
We have removed the parse statement from the child flow in Nov for an issue found with a change in the what the product returns sometimes. 
So I believe if your error in the child is a parse, it will be resolved with that fix.
https://github.com/microsoft/coe-starter-kit/issues/6807

Please do let me know your thoughts.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by AnkitTotal** [comment]
Ok
