### ISSUE TITLE
Issue with the core components solution

### ISSUE THREAD

**Issue by adminPP23** [microsoft/coe-starter-kit#6947]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

While importing the core components solution for october update, it duplicates the core components solution, I already saw the thread opened on this and tried the steps mentioned there and I am still getting an error so hoping for some support here. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

NQ

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/126533167/e9aef37e-6670-4a9d-bc9a-c841f4a0f3a3)
![image](https://github.com/microsoft/coe-starter-kit/assets/126533167/6a68f7c7-931e-4c23-a42d-922f65f88d4c)

AB#335

**Comment by Jenefer-Monroe** [comment]
The behavior of it being there twice is just the product behavior when an install fails.

You failed due to the Audit Log solution being present, which ahs been deprecated. You need to clean up references to the Custom Connector from that which sits in Core. The steps for that are described here https://github.com/microsoft/coe-starter-kit/issues/6018

Please follow these steps and let us know how it goes.

**Comment by adminPP23** [comment]
I do not have audit logs solution, that was deleted already. The references in the default solution for 0365 management api were also deleted and I am seeing this error after following the article/steps you linked.

**Comment by adminPP23** [comment]
By the way steps mentioned here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http is not working for me either, 
![image](https://github.com/microsoft/coe-starter-kit/assets/126533167/f5123418-7549-461a-a624-52c11f60af25)

Would it be better to wait for November update and do the upgrade then?

**Comment by Jenefer-Monroe** [comment]
Lets please use this bug to track your upgrade issue and once its resolved you can post a new issue for help getting audit logs setup.

**Comment by Jenefer-Monroe** [comment]
You must still have references to the custom connector, thats what that error message says. Please see the following from that help issue:

### Make sure everything is deleted
A few people have found that some objects did not get deleted when the old Audit logs solution was deleted so just go double check that they did and delete these objects if you see them still there.
Go to the Default Solution > Connnection References. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/30db106e-99c3-4f3f-bb20-cb1d1cd7e9b3)

And some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use  powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest)  these remaining connections to the old connector.

**Comment by adminPP23** [comment]
I do not have any issue with the Audit logs at the moment, its with the core components just to clarify. Would it be easier to get rid of the old core components solution and just install the new updated one as import?

**Comment by Jenefer-Monroe** [comment]
You have an old reference to the audit logs custom connector which used to be in core thats why you cant upgrade. Because we deleted this custom connector as it is now deprecated. 

If you are able to delete core and start from scratch that would resolve it for sure.

**Comment by adminPP23** [comment]
It does not let me delete the solution due to dependencies, how do I get rid of the dependencies?

**Comment by Jenefer-Monroe** [comment]
oh yes you have gov and nurture installed as well it seems. 
Are you using these? If not, then you'll need to delete them first.

**Comment by adminPP23** [comment]
So basically deleting nurture and gov components would remove the dependencies and allow me to delete core components?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jenefer-Monroe** [comment]
It should yes. 
You'll need to delete Nurture, Gov, then the Core with the _Upgrade, then Core

**Comment by adminPP23** [comment]
So I ran the powershell to fetch the connections and still saw o365 api connection active so deleted it by running powershell, I then tried to import core solutions as upgrade and it still duplicates. It does not upgrade.
![image](https://github.com/microsoft/coe-starter-kit/assets/126533167/3f475112-7d42-45be-a9b6-0f62a556dcde)

**Comment by adminPP23** [comment]
Finally, after some hard troubleshooting and digging, I finally am not seeing duplication, deleting the o365 management api via powershell commands, thanks a ton for your constant inputs, this was a bit of frustrating experience upgrading but surely  your inputs made it helpful and easier in the end, thanks so much @Jenefer-Monroe , appreciate your help. Last question, is the audit logs deprecated now? I am wondering if I need to import it or now.

**Comment by Jenefer-Monroe** [comment]
So glad to hear you were able to upgrade! Normally upgrade is not this painful so you shouldnt have to go through this again.

The thing that was deprecated was the custom connector methodology for gathering audit logs. We were able to get this to work with an http connector instead. Here are the instructions: [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

The big hiccup most people hit when converting from the old solution to new (aside from the upgrade issue which you've now gotten through) is that the app registration needs to be of type Application now, whereas it used to be delegated.
From the link above:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ce25ae3d-9527-416e-93fd-1b4a860199a8)

**Comment by Jenefer-Monroe** [comment]
You're welcome! I'll go ahead and close this out then but please do return with new issues if you have other issues with the kit!
