### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Template v3 (Desktop Flows) Failing

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#6948]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When we run the Desktop Flows template we get a bad request error citing logic app limits. 

Thougts?
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/956a5637-eb3b-403e-9a74-7182f434c8bd)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run the flow as scheduled. 

AB#336

**Comment by Jenefer-Monroe** [comment]
That is just a product limitation that we cannot really get around. We are shipping with the new dataverse connector for Desktop Flows as an optional flow for Nov and hopefully it will have better experience in this regard. Please see https://github.com/microsoft/coe-starter-kit/issues/6946

**Comment by Jenefer-Monroe** [comment]
You're welcome. I'm hopeful that will resolve it! If not please post a new issue for us! 
I'll go ahead and close this one out.
