### ISSUE TITLE
[CoE Starter Kit - BUG] Presence of _Upgrade solution

### ISSUE THREAD

**Issue by bhupendra14** [microsoft/coe-starter-kit#6950]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

There are two Core Component Solutions in my Production environment of different versions showing. Looking at flow runs it would appear both sets are running but this should not be possible. If the flows are keyed from ID and there is only one actual flow, we have no idea which one is actually running the old or the new.

### Expected Behavior

After CoE upgrade only one Core Component should be available, the old one should be remove automatically after upgrade.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

None

### Anything else?

![SSCoreC](https://github.com/microsoft/coe-starter-kit/assets/35683189/f67e0a80-26ab-4afa-b689-1aab8bed198c)

**Comment by bhupendra14** [comment]
Thanks for pointing me back to #6018

I had already performed these but I was not sure about to deleting the O365 Management API connector. I follow your path and deleted the connection from the environment and redid Apply Upgrade which worked.

Thanks Again!

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thanks so much for following up to let us know, that always is a relief to know. 
I'll go ahead and close then but please do return with new issues if you need more help in the future!
