### ISSUE TITLE
[CoE Starter Kit - QUESTION] No Maker Env. Request App, am I missing something?

### ISSUE THREAD

**Issue by KRhoadesHyp** [microsoft/coe-starter-kit#6952]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

After running the October update I no longer have a Maker Environment Request app, just the deprecated version.  Should I try reinstalling?

![image](https://github.com/microsoft/coe-starter-kit/assets/135135789/2c4e55ba-16a7-4c58-8a41-018fc854ed98)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Thanks for reaching out! 
With the switch to custom pages we added this to the existing Model Driven App for Makers, the CoE Maker Command Center


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/606c1881-26f0-48da-a5d6-a485ffeb25cd)

**Comment by KRhoadesHyp** [comment]
If I don't say this enough you ladies are amazing, thanks for all you do!! 🥇

**Comment by manuelap-msft** [comment]
Please note that unfortunately we have a bug in the custom page version at the moment that will be fixed with the next release:
https://github.com/microsoft/coe-starter-kit/issues/6815

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
