### ISSUE TITLE
[CoE Starter Kit - BUG] Update how to activate BPFs documentation

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#6956]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

Please, the POWER PLATFORM ADMIN VIEW application is giving an error, as shown in the images below, when I open the application the message above appears, and when I click on NEXT STAGE nothing happens, it would be moving to the next validation step, right?
Can you help me? Is this an error or pending configuration?
![tela 1](https://github.com/microsoft/coe-starter-kit/assets/129080740/1fcea28e-5a08-4dbb-a215-82e9a620b4e8)

![tela 2](https://github.com/microsoft/coe-starter-kit/assets/129080740/b16e12bb-22c2-48dc-9753-1603cb0ece6e)

![Versão CoE](https://github.com/microsoft/coe-starter-kit/assets/129080740/83865ea8-727f-4027-939d-7209bc4dfd6f)

### Expected Behavior

According to the video on how to use COMPLIANCE PROCESS, after clicking on NEXT STAGE, another Risk Assessment stage was supposed to come and finally FINISH, but it did not go beyond the first stage.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

14.15

### What app or flow are you having the issue with?

compliance process works

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Here is how we tell people to turn these on: [Activate the business process flows](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#activate-the-business-process-flows)

But it looks like the product has changed and you cant do this anymore in a managed solution.
I'm not sure where to do this now, will investigate and let you know, then update the documentation.

**Comment by Jenefer-Monroe** [comment]
ok what you do is go to the processes in the solution
click on the name of the Process that is turned off
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9bcf2138-8945-45b2-81a9-252d84a89bbe)

That will open the BPF in the editor. Hit Activate
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/591db644-ac15-490a-93ba-b4e89d436204)

We'll keep this issue open to update the documentation as well. 
Thanks for posting.

**Comment by minobrega** [comment]
Hi Jenefer..

Thank you very much for your help, it worked!!

I activated all the modules that we are going to use and now I have moved on to the next step.

![Deu certo 1](https://github.com/microsoft/coe-starter-kit/assets/129080740/a9b22830-9281-445a-bcf9-39d1074c744f)

![Deu certo 2](https://github.com/microsoft/coe-starter-kit/assets/129080740/2ad429bf-dff9-480c-afc8-ef379ff7152a)

**Comment by dtheilen** [comment]
The business process flows aren't activated on import or after running the wizard. These manual steps to activate do work but it would be great if this were reflected in the documentation for setting up the compliance feature.
