### ISSUE TITLE
[ALM Accelerator - BUG]: Existing Users Getting Error While Opening ALM Accelerator after Upgrading to October Version

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/coe-starter-kit#6958]
### Describe the issue

Hello Team,

Could you please help with this error.

After upgrading to the latest version, we are receiving the below error while opening ALM App.

![MicrosoftTeams-image (5)](https://github.com/microsoft/coe-starter-kit/assets/33513504/ea4043d5-2603-4d65-a7ca-5a5f77ed6cff)

The profiles are showing 'Select a Profile' option and while selecting it is showing the below error.

![MicrosoftTeams-image (6)](https://github.com/microsoft/coe-starter-kit/assets/33513504/17802ee7-c8a1-410e-a845-8771ac7d8710)

The users have required access to Deployment Profile and Required Security Roles in the Environment where ALM is installed.

Also the issue is not appearing to users who have System Admin access to the Environment where ALM is installed.

Could you please help here.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231004.1

**Comment by mikefactorial** [comment]
Hey @tomjosbin, there was an issue with the ALM Accelerator app role's permissions on a new table (cat_solutionprofile) we added in the October release. We pushed out a hotfix for this on the 12th. Can you import the latest solution to resolve this? https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-October2023/CenterofExcellenceALMAccelerator_1.0.20231012.1_managed.zip

**Comment by tomjosbin** [comment]
Thanks a lot Mike. I missed the hot fix notification, was using the first version.
