### ISSUE TITLE
[CoE Starter Kit - QUESTION] In our Governance Dashboard, the two Apps Not Launched metrics are blank but everything else seems to be filled in.

### ISSUE THREAD

**Issue by fshink** [microsoft/coe-starter-kit#6959]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In our Governance Dashboard, the two Apps Not Launched metrics are blank but everything else seems to be filled in.  How Do I go about troubleshooting this?

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Click transform data
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4fcd2252-eff7-4c42-941e-daca3eb202d7)
Go to the spot shown, do you see nulls in the **admin_applastlaunchedon** column?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8c56fec9-3d23-41cd-9ecd-ed8d5ee84b45)

**Comment by fshink** [comment]
Those columns ARE populated.  The Power BI Governance Report does not seem to pick up the values.

**Comment by Jenefer-Monroe** [comment]
When you say populated, do you mean with dates? Or are there nulls in there too?

**Comment by fshink** [comment]
There are dates in there but some are blank since the CoE kit has not always run.  However for the most part, lastrun date is populated with a date.

**Comment by Jenefer-Monroe** [comment]
ok then for this last step of the query, do you see trues / falses in the columns shown?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cb765420-863e-4c19-b648-e75e09f48b6f)

**Comment by Jenefer-Monroe** [comment]
And then lastly do you see the filters as shown here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6ed3f692-9112-447a-b39e-e2282d62a0d2)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/90826bfc-3334-4674-886d-b4b7212d8128)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
