### ISSUE TITLE
[AA4AM] Eliminate custom connector for Azure DevOps

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#696]
Today, we are using a custom connector, instead of using the Azure DevOps connector:
https://docs.microsoft.com/en-us/connectors/visualstudioteamservices/
The reason we decided to do this was because the connector does not have actions we needed.  While we could have used the **Send an HTTP request to Azure DevOps** action:
https://docs.microsoft.com/en-us/connectors/visualstudioteamservices/#send-an-http-request-to-azure-devops
..., we chose not to because it would have made the canvas code overly complex and harder to maintain.  While we could have also wrapped that action in a flow, we didn't want to incur the extra overhead of doing so for each call the Azure DevOps REST API.  In addition to performance overhead, this would also result in more maintenance overhead.

However, requiring a custom connector for a service that already has a OOB connector is a heavy burden and likely a blocker for some organizations to deploy the accelerator since it requires an Azure AD app registration to function.  Instead of using a custom connector, we plan to contribute new actions to the OOB Azure DevOps connector.  We will then switch to using the OOB Azure DevOps connector, which will now have the actions we need.  

This will:
- Eliminate the need for the custom connector
- Remove the dependency on an Azure AD app registration as a prerequisite to deployment
- Benefit others who want to build apps/flows over Azure DevOps APIs with less need to use the **Send an HTTP request to Azure DevOps** action

Similarly, as we enhance the app to use GitHub as a backend, we will make similar contributions to the GitHub connector.

**Comment by devkeydet** [comment]
Given our plans to have a single Accelerator that works with both GitHub and Azure DevOps and the patterns we plan to implement to provide it depending on using custom connectors:
https://github.com/microsoft/coe-starter-kit/issues/2046
...we haven't prioritized completing the work to eliminate the custom connector as it's now a key part of our strategy to support both GitHub and Azure DevOps using a single Accelerator.  We've made some progress in contributing back to the Azure DevOps connector that some may have noticed.  While we still think the idea of contributing back to the Azure DevOps connector is something that will benefit customers, we're a small team that needs to prioritize what we spend time on.  This is not something we currently have the resources to work on right now since it's now in conflict with how our roadmap has evolved.  We may revisit this decision if / when circumstances change.

**Comment by mikefactorial** [comment]
Closing out this issue for now based on our proposed solution.
