### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Blues1981** [microsoft/coe-starter-kit#6961]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When trying to re fresh the data set in Power BI Dashboard I am receiving the following error.

### Expected Behavior

To refresh Data set

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

COE

### What method are you using to get inventory and telemetry?

None

### Anything else?

![MS Issue PBI](https://github.com/microsoft/coe-starter-kit/assets/133023969/df7c43a5-41ec-4c99-bd81-62b3654609e7)

**Comment by Jenefer-Monroe** [comment]
Hello. This is a field that was removed from the CoE tables. You are likely using an older copy of the PBIT file with a newer install of Core. Sometimes you can do this and its not a problem but other times you will be forced to use the new PBIT file. 
Best practice is to update your PBIT every time you update Core. 
Hope that makes sense.

**Comment by Blues1981** [comment]
Hi Jenefer, can you remind me how I update the PBIT please?

**Comment by Jenefer-Monroe** [comment]
Yes of course! Happy to help.
Each time you download a new version of the kit https://aka.ms/coestarterkitdownload
You will find PBIT files. Assuming you are on the cloud flow architecture, you will typically only need to update these two
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2f818cc9-17f5-46e5-a7a3-a740b805e070)

You will [Get the environment URL](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#get-the-environment-url)

And then [configure these Production and Governance Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-production-and-governance-power-bi-dashboard) by simply entering it as shown in this link.

You can then optionally [configure the embedded apps in the CoE production dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard) if you'd like. 

Save to your desktop with the same name as you have published to PBI.com in the past, and then publish to the same workspace, and it will ask you if you want to overwrite. 

If you have not already, be sure to also [configure a scheduled daily refresh](https://learn.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
