### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE BYODL Flows Failing

### ISSUE THREAD

**Issue by niwrejim21** [microsoft/coe-starter-kit#6962]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am not sure if this is a bug but the initial run was successful - all succeeding runs are failing with the error:

Error Code: Mashup Unknown Error, Error Details: Couldn't refresh the entity because of an internal error (Request ID: de9ea470-868f-4458-b266-83aed1c6bb5b).

![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/8a742c4b-2dc6-46d8-a9b8-8a753f02cde6)

Tenant Size:

Environments: 500
Power Automate: 30000
Power Apps: 10000

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

CoE BYODL Flows

### What method are you using to get inventory and telemetry?

Data Export

AB#437

**Comment by Jenefer-Monroe** [comment]
This is tracked by https://github.com/microsoft/coe-starter-kit/issues/6153. 
We are shooting to have a solution for testing for the Dec release.

**Comment by Jenefer-Monroe** [comment]
closing as a duplicate

**Comment by niwrejim21** [comment]
Hello again Jenefer, May I kindly know if the fix for this was included in the January release?
