### ISSUE TITLE
[CoE Starter Kit - BUG] CoE BYODL Environments dataflow 

### ISSUE THREAD

**Issue by accsimonwalsh** [microsoft/coe-starter-kit#6964]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When connecting to the CoE BYODL Environment dataflow I get the following issue: 

<img width="612" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/2f3d2090-77b2-44fe-a42d-1918cbde2ddd">

This occurs at the marked step in the picture. The following pictures below are from the step before. There is data from all environments, so the query shouldn't end up empty in the subsequent step. 

<img width="436" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/fcc30725-a077-41ff-807d-5583c7bfceb1">

<img width="367" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/fd0a1c9b-132e-4687-b804-faf2bce9c0c9">

<img width="369" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/68a226c7-7b7c-438c-a101-b03f52d3bfdf">

Additional information is that I've recently upgraded to CoE starter kit version 4.16 for core components. Before the upgrade unmanaged layers were deleted. 

### Expected Behavior

The "Environments" table is connected without issues. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

CoE BYODL Environments

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Edit dataflow
2. Set up datalake and environment parameters
3. Connect to the "Environments" table.
4. The error occurs.

AB#438

**Comment by manuelap-msft** [comment]
Hello,

this usually happens when you don't use the Setup Wizard to set up the CoE kit, which leads to the SYSTEM user not existing in the Maker table. Please run the Setup Wizard and complete the steps from there, which will insert a SYSTEM user into the maker table and then you can configure the dataflow. 

Let me know if you've run the Setup Wizard and are still seeing this issue.

Manuela

**Comment by accsimonwalsh** [comment]
Thank you, this solved the problem!

/Simon
