### ISSUE TITLE
[CoE Starter Kit - BUG] Inactivity email for Flows not picking up save date

### ISSUE THREAD

**Issue by Nomester** [microsoft/coe-starter-kit#6965]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have resaved power automate flows and they show a modified date of 24th October but I'm still receiving unused flow requests from CoE which show the old Last Modified date of 18 April.

### Expected Behavior

I would expect that if you resave a flow then the modified date would mean that the CoE wouldn't flag them as unused.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Flows)

### What method are you using to get inventory and telemetry?

None

AB#439

**Comment by Jenefer-Monroe** [comment]
Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown below.
In particular these two flows are what fills inventory for cloud flows:

- SYNC HELPER - Cloud Flows
- Admin | Sync Template v4 (Flows) 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
