### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE: Admin | Audit Logs | Office 365 Management API Subscription Cloud flow failing

### ISSUE THREAD

**Issue by goldiagrawal10** [microsoft/coe-starter-kit#6968]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

**This is not a new bug but other bug article is closed. https://github.com/microsoft/coe-starter-kit/issues/5670****

I have the same problem and I tried disabling and enabling flow but it is still same issue. It says Action 'Get_Azure_Secret' failed. As per the article, I have put value for Audit Logs - ClientID and Audit Logs - Client Secret but not Audit Logs - Client Azure Secret because I am staying Client secret in plain text.

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

{
"error": {
"code": "0x80040216",
"message": "Error occured while reading secret: Value cannot be null.\r\nParameter name: input"
}
}

### Expected Behavior

As per the article https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#create-an-azure-ad-app-registration-for-the-office-365-management-api, if we are storing client secret in plain text, then we can keep Audit Logs - Client Azure Secret empty. Hence, flow should run successfully in either case. 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

![COEAuditLog](https://github.com/microsoft/coe-starter-kit/assets/123458513/4ee90567-6165-4a6c-ade1-b86c7956767e)

AB#445

**Comment by Jenefer-Monroe** [comment]
If you are not using Azure Key Vault then this failure is expected and caught. 
Note that flow always shows the first failure even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

**Comment by Jenefer-Monroe** [comment]
So please dive down into here: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4042521a-5e1d-474b-8622-76a3f9137b7d)

To find the terminating failure

**Comment by goldiagrawal10** [comment]
![Audit-Logs](https://github.com/microsoft/coe-starter-kit/assets/123458513/3dc68b67-18b4-43c6-b5b5-1d0bc924acdd)

If I drill down, it is throwing this error message. Again, I have given correct Application ID and Client Secret.

**Comment by Jenefer-Monroe** [comment]
Is the secret correctly ingested here? And is it of type Secret (not a GUID)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9783b8d9-4ddb-40d7-928f-eeeeb9c1145a)

**Comment by Jenefer-Monroe** [comment]
Are you a regular tenant (Commercial) or something like GCC / DoD? 
And do you have all these env vars filled correctly for your tenant type?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

**Comment by goldiagrawal10** [comment]
I filled the Client ID instead of Client Secret... Its working now... Thanks for your help.

**Comment by Jenefer-Monroe** [comment]
YEAH! Thank you so much for letting me know!

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close out but please do return with new issues if you have other questions in the future.
