### ISSUE TITLE
[CoE Starter Kit - QUESTION] There was an issue retrieving your most up-to-date data. Some features may not behave correctly until a successful connection is established.

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#6970]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

we are trying to upgrade CoE tool kit to latest version 

Solution : CoE Core Components of Version 4.16 is installed successfully but older version of CoE Core components 4.9 version is not  getting uninstalled. and we are repeatedly receiving  below error message 

![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/074789b5-c9cf-4a4f-8bdb-f4631cfb407f)

we are running all Inventory flows too 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin-Sync V3 Template 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#449

**Comment by Jenefer-Monroe** [comment]
This particular issue is a product error and one I've never seen before. It sounds like the product is having trouble with its internal connetions. I dont see any refrence to this error online either, I'm afraid I would not know how to assist there. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eaddee99-32c2-4c09-94a8-665823488fa4)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
