### ISSUE TITLE
[CoE Starter Kit - BUG] PowerBI Dashboard deployment issue

### ISSUE THREAD

**Issue by Jurny123** [microsoft/coe-starter-kit#6974]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

I am trying to deploy PowerBI dashboard according to the instructions here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi but when I am opening pbit file, I am not getting any window to provide OrgURL. It is just opening and showing me something as below:

![image](https://github.com/microsoft/coe-starter-kit/assets/65650068/e6d896e4-f44f-4909-8d0b-635307b35dbd)

How to manually enter this URL and publish Dashboard?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

-

### What method are you using to get inventory and telemetry?

Cloud flows

AB#559

**Comment by Jenefer-Monroe** [comment]
Can you please return to the file you are clicking and check its type? It's a PBIT file that is included in the download. Perhaps you are opening an old saved version which would be PBIX
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/55446f92-6966-4c3c-a8b2-7a08c1b1a54c)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/af65f0e3-d5af-4c73-b06b-f0a082bce128)

**Comment by Jurny123** [comment]
It's pbit file directly from CoE package:

![image](https://github.com/microsoft/coe-starter-kit/assets/65650068/1ea31b3d-2d4b-4a9f-9498-c5a6d3ce2549)

**Comment by Jurny123** [comment]
Ok, Instead of opening PowerBI and then opening template file, I've opened template directly by double clicking on it and it worked. So that's kind of bug what should be fixed, but I guess it's app related, not template related.

**Comment by Jenefer-Monroe** [comment]
Great. Yes unfortunately thats PBI product behavior and not something we have any control over. 
Glad you are unblocked!
