### ISSUE TITLE
Audit Logs via HTTP - Subscription START Fails with 401 Error - GCC High

### ISSUE THREAD

**Issue by EmMoLe** [microsoft/coe-starter-kit#6975]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am using the instructions at https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http to move to the new HTTP method for collecting audit logs. When running the flow to start the subscription, I receive a 401 error.

Steps already taken:
* Audit logs ARE enabled
* Confirmed environment variables are entered accurately
* Confirmed Azure app registration for O365 Management API is config'd correctly (with APPLICATION permissions, not DELEGATED)

I noticed in the START SUBSCRIPTION step in the flow, the URI references https://manage.office.com/api/v1.0. Not sure if this would be the correct target for GCC High?

### Expected Behavior

Should receive message subscription was started OR already exists (200 response).

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Core Components, October 2023 Release (v4.16)

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

AB#560

**Comment by Jenefer-Monroe** [comment]
Hello I know we had an issue in the past where we had hard coded in the URI but that was fixed. Can you open the flow in edit and validate that the action looks like this now? 
If it does not, please check for an unmanaged layer on the flow and remove. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9b212efb-8957-436a-9bbb-5f1672db06ee)

**Comment by EmMoLe** [comment]
@Jenefer-Monroe , I uninstalled/reinstalled the solution and it is now giving the expected result in the subscription flow. Thanks for your response!

**Comment by Jenefer-Monroe** [comment]
YEAH! Wonderful news, thank you for letting me know!

**Comment by Star-Donovan** [comment]
seeing similar issue in my GCC tenant (not GCC High)
