### ISSUE TITLE
[CoE Starter Kit - QUESTION] Trying to determine who is using which connector, what apps/flows, what env and when the app/flow were last created or modified

### ISSUE THREAD

**Issue by sasrsc** [microsoft/coe-starter-kit#6976]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Our security team wants to know who is using what connectors…(he’s going to red flag one or more connectors) – in this case JIRA but we’ll want to look at more… and he wants to know IDEALLY the date it was created, last used and last modified and how much it’s being used. Ideally not to have to look all over the place for this.
1.	Date Created: When the flow/app was created that uses the specific connector
2.	Date Last Modified:  When the flow/app was last modified that uses the specific connector
3.	Date Last Used: When the flow/app was last run that uses the specific connector.
4.	How Many Times Used: How many times between 2 dates that the flow/app has been run.

In the PPAC we can see the app/flows but we can see the dates and how much it's been used in a time span. We don't mind building our own BI report but we need to know what tables to find the data in. Can you help?

I will probably build a BI report and also a flow to connect and report on this data for the app sec team. I haven't done anything special with the method for getting the data, so that means flows right?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Current

### What method are you using to get inventory and telemetry?

Cloud flows

AB#563

**Comment by sasrsc** [comment]
Do you want me to add as a RFE?


Richard Clowes
Senior Director ● Travel Operations
Tel: + 1 919 531 7955 ● Cell: + 1 919 413 3084 ● ***@***.******@***.***>
Worldwide Headquarters ● Cary, NC

www.sas.com<http://www.sas.com/>
SAS(r) … THE POWER TO KNOW(r)

**Comment by sasrsc** [comment]
If I were to explore my own Power BI report for this … which table(s) should I focus on?


Richard Clowes
Senior Director ● Travel Operations
Tel: + 1 919 531 7955 ● Cell: + 1 919 413 3084 ● ***@***.******@***.***>
Worldwide Headquarters ● Cary, NC

www.sas.com<http://www.sas.com/>
SAS(r) … THE POWER TO KNOW(r)

**Comment by Jenefer-Monroe** [comment]
We don't store that data today so it would need to be gathered before its reported upon.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
