### ISSUE TITLE
[CoE Starter Kit - QUESTION] Datalake - Is it possible for the Datalake version to grab information from owner name insted owner id?

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/coe-starter-kit#6977]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I raised several support items with Microsoft and they said the data export is behaving correctly. Nonetheless, 50% or more of my power apps are being saved with a null value in the createdprincipalid. The owner is populated, but not the id. 

So, I'm wondering if there is any workaround?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2023

### What app or flow are you having the issue with?

Data export feature

### What method are you using to get inventory and telemetry?

Data Export

AB#569

**Comment by Jenefer-Monroe** [comment]
Including link to old version of the bug: https://github.com/microsoft/coe-starter-kit/issues/5913

**Comment by Jenefer-Monroe** [comment]
We cannot use Owner as its just a Display Name and not unique.

**Comment by Jenefer-Monroe** [comment]
moving to consider with Dataflow rewrite for Dec

**Comment by Jenefer-Monroe** [comment]
This is blocked by the following product bug https://github.com/microsoft/coe-starter-kit/issues/6658
Unfortunately the product is just returning the wrong thing. We cannot rely on name as its not unique. There may be several Jane Doe's in an organization for example. 
Closing this out as a dupe to https://github.com/microsoft/coe-starter-kit/issues/6658
