### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View - no number of flows or apps near makers names

### ISSUE THREAD

**Issue by Jurny123** [microsoft/coe-starter-kit#6979]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am facing strange issue with PP Admin View app:
![image](https://github.com/microsoft/coe-starter-kit/assets/65650068/f6c78e65-2817-4a6c-b1cd-8957d4e57ba3)

As you can see, it's not showing any numbers there, but if I switch to "Flows" or "Apps" card, I've got a list of flows and apps, with owners:

![image](https://github.com/microsoft/coe-starter-kit/assets/65650068/1d008ad2-57fd-4e81-9fa5-dbae586fb6a7)

What's wrong?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

-

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

AB#581

**Comment by Jurny123** [comment]
Same situation with "Active Environments" tab: 
![image](https://github.com/microsoft/coe-starter-kit/assets/65650068/187b1042-e5c7-4dfe-8e67-ba5503cb6476)

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry for the confusion. Those are roll up fields and so for a new install they take a while to update. The product itself determines how frequently and when to update these roll up fields but I believe its up to a 12 hour delay before they will occur.

**Comment by Jurny123** [comment]
Okay, currently there's more than 36 hours after deployment, but still zeroes in place. Is there any way to manually update it for the first time?

**Comment by Jenefer-Monroe** [comment]
Likely your inventory delay had you missing the first instance of the rollup being refreshed.
You can force these to calculate. Please see the tip in this product team article on [Rollup columns](https://learn.microsoft.com/power-apps/developer/data-platform/calculated-rollup-attributes#rollup-columns)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d374b7dc-82e2-499d-8855-be81a70bdb98)

**Comment by Jurny123** [comment]
Which one exactly? I see multiple System Jobs what contains "Calculate rollup fields" in the name. Also, all of them are succeeded recently (last run from today, less than hour ago.

**Comment by Jenefer-Monroe** [comment]
You can also just wait until tomorrow to see if they've updated. I've only gone and forced this a few times myself so would have to go refamiliarize myself as well.

**Comment by Jenefer-Monroe** [comment]
While you wait, you can also go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by Jurny123** [comment]
Yes, flows are ON, no solution layers, no failed runs.

**Comment by Jurny123** [comment]
And unfortunately, today still zeroes everywhere...

**Comment by Jenefer-Monroe** [comment]
ok. It sounds like you (the user running the flows / who installed) might not have permission to write to the Data

Quickly on the roll up fields please answer these two question

### The Roll Up Field
Go to the Environment table
Core > Tables > Environments > Edit the columns shown in the table to the ones shown.
What is shown there? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/23b94912-f380-4523-a0b3-a27eeab50381)

### Envt field in Apps
Go to the PowerApps App table
Core > Tables > PowerApps App > Edit the columns shown in the table to the ones shown.
What is shown there? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/04ed0692-7af9-4b7f-8136-76606d8ce03d)

**Comment by Jurny123** [comment]
1. All zeroes
2. I see complete list of all apps in tenant.

**Comment by Jenefer-Monroe** [comment]
And how about the other question for the envt fields in apps?

**Comment by Jurny123** [comment]
As I've posted, I can see list of all apps:

![image](https://github.com/microsoft/coe-starter-kit/assets/65650068/6ebec23d-8a97-47da-a02f-ef925cb3a5ff)

**Comment by Jenefer-Monroe** [comment]
Please go to the column to see if its setup correctly. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/83cf5f83-d15f-4bd5-b7be-ee6587626b2c)

**Comment by Jenefer-Monroe** [comment]
And also add the App Deleted and App Deleted On columns to the app view from above, are your apps marked deleted?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d8563649-7bbd-4e28-bc4f-4e022a361668)

**Comment by Jurny123** [comment]
1. Configuration seems to be fine:
![image](https://github.com/microsoft/coe-starter-kit/assets/65650068/f2cec135-f81b-4f34-a624-d7040a04fe78)


2. All apps have "App Deleted" parameter set to "No":
![image](https://github.com/microsoft/coe-starter-kit/assets/65650068/548fe37c-7736-4055-8a00-4370262433e5)

**Comment by Jenefer-Monroe** [comment]
ok im really not sure here. These are just a product feature we use. I've never seen this happen before
You will likely just have to contact product support. I suggest just raising this as a roll up field that isnt calculating without referencing the kit so they dont bump you back here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
