### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis App bug(s)

### ISSUE THREAD

**Issue by accvik** [microsoft/coe-starter-kit#6981]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Seems like a bug when trying to export the impact analysis to csv:

![image](https://github.com/microsoft/coe-starter-kit/assets/106146275/c48502a4-580f-4b6e-a5c4-6c5deffb00b2)

This is me trying to edit a "Exclude certain environments" Scope DLP where the default environment currently is excluded. I want it to be "Available" instead by doing:
Open the new DLP Impact Analysis App ->  "Edit Policy" -> Select Default environment ->Press "Remove from policy"->Next 

No impacted apps/flows visibly, there should be, and when pressing "Export to CSV" the flow run fails.
I believe the logic does not account for the case when a policy that has the scope "Exclude certain environments", and we remove such an exception, it does not get added to the data of envs that should be checked. Can that be correct? Or how can I get around this? 
(Since if I try the app with a Scope "Add multiple environments" and try to add an environment, the data shows up and the flow runs fine).

Really appreciate an answer, need to assess this DLP change :) Thanks.

(By the way, either the data is wrong or the showing within the app that every Environment in my list is called the same..? This is only also appearing for when I'm editing the "Exclude certain environments" DLP. In the Admin View App, all environment names are correct.
![image](https://github.com/microsoft/coe-starter-kit/assets/106146275/2c45b4b0-ab77-4f88-a44a-848bc3dfb00d)

(By the way 2, also when editing the same DLP, the Default Environment incorrectly shows up in the "Available" list in the DLP Impact Analysis app, which is should not:
![image](https://github.com/microsoft/coe-starter-kit/assets/106146275/d3696c6b-b75b-42a5-8226-4c82e8df7a96)

From admin center: 
![image](https://github.com/microsoft/coe-starter-kit/assets/106146275/a03a8126-acfb-4178-aa24-df2cb418cb7d)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

DLP Editor>Parse impacted resources into CSV

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

See above

AB#584

**Comment by Jenefer-Monroe** [comment]
I do repro this. It's pretty complicated logic though so over to area owner for investigation.

**Comment by accvik** [comment]
Thanks for the update Jenefer. Will I continue getting updates through here?

**Comment by LucX4** [comment]
Hi team,
I'm experiencing the same error when attempting to run the impact analysis on a DLP with the 'Add all environments' scope.

**Comment by accvik** [comment]
Is this a planned fix for the February release?
