### ISSUE TITLE
[ALM Accelerator - BUG]: Solution Checker 30MB size limit

### ISSUE THREAD

**Issue by lasjoe** [microsoft/coe-starter-kit#6982]
### Describe the issue

Hi, 

I'm getting the error below when trying to deploy solution with an app weighing ~50MB due to images inside.

`Error: ERROR: ErrorId: PACHECKER_PS_FILE_TOO_LARGE; ErrorCategory: InvalidArgument; TargetObject: System.String[]; Exception: System.InvalidOperationException: ERROR: code=PACHECKER_PS_FILE_TOO_LARGE, param=FileUnderAnalysis, message:The file(s) under analysis must be under 30 MB.  D:\a\1\a\POM_1.0.20231102.1.zip`

### Expected Behavior

Is there any way to ignore this error and deploy anyway?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

October 2023

### Steps To Reproduce

1. Create app with more than 30MB of media files inside.
2. Deploy

AB#588

**Comment by mikefactorial** [comment]
@lasjoe pardon the delay. You can skip the solution checker by setting DisableSolutionChecker = true in the deployment pipeline variables e.g. 

![Image](https://github.com/microsoft/coe-starter-kit/assets/42348035/947bcd81-c9d9-459a-b649-d654d4504d77)

**Comment by RajeevPentyala** [comment]
@lasjoe Hope you've tried the option suggested by Mike. Closing this issue for now. Feel free to reach out if you need further assistance.
