### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to trigger compliance for flows

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#6984]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I'm still in our testing phase of CoE and wanted to try the compliance process for flows. I looks like flows compliance isn't triggered. I can see how it works for apps i.e. the flow "Admin | Compliance detail request v3" starts the process and looks at apps and bots. For apps the flow "Admin | Compliance Details Request eMail (Apps)" sends compliance emails for apps.
My question is - does anything trigger the flow "Admin | Compliance Details Request eMail (Flows)" ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Admin | Compliance Details Request eMail (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#590

**Comment by Jenefer-Monroe** [comment]
Hello. There are no automated processes which trigger this, but you can manually flag a flow as requiring it go through the process in the Power Platform Admin Center as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/31d6f1b1-95b1-43cf-8ae5-a05d9b4546b8)

**Comment by MartinWGT** [comment]
Thank you, that's good to know.

**Comment by Jenefer-Monroe** [comment]
You're so welcome!
