### ISSUE TITLE
[Power Platform communication site template] Environments from CoE Dashboard doesn't exist

### ISSUE THREAD

**Issue by TomasASvoboda** [microsoft/coe-starter-kit#6985]
### Describe your bug, question or feature ask.

Hello, 
I am looking at the Production_CoEDashboard, where on the Overview - Power Apps and Overview - Power Automate pages I see the top 20 Environments, where the environment: 'environment name' (default) (Upgrade).

However, it cannot be found on the Environments page, and I can't find it in the Power Platform admin center, where I am a global administrator.

What kind of environment is this? Is it not visible anywhere.

AB#598

**Comment by Jenefer-Monroe** [comment]
Hello. It sounds like you have an issue outside the context of the PBI so lets focus on that. 
Can you please share a screenshot for what you mean by this: `I can't find it in the Power Platform admin center, `
Just to be sure we ware on the same page. 
NOTE: You will need to log in to GitHub to share images, if you respond in email they will not come through.

**Comment by TomasASvoboda** [comment]
Hello, 
I am attaching the screenshot from Production_CoEDashboard, page: Overview - Power Apps.
I apologize for obscuring the name of the environments. 
You can see the one environemnts (yellow marked) with the name: "name" (default) (Upgrade) 
This environment has many power apps, power flows.
But this environment can't be found anywhere, even with my global permissions in power platfrom admin center I can't find this environment.  Also I cannot find the exact power apps and flows from this env. .

I also noticed that in Production_CoEDashboard this environment is not on the Environments page (orange marked on the screen).

![CoEscreenshot](https://github.com/microsoft/coe-starter-kit/assets/149689572/ff532e32-f123-45c1-baed-067666849faf)

**Comment by Jenefer-Monroe** [comment]
And when you say this:
`But this environment can't be found anywhere, even with my global permissions in power platfrom admin center I can't find this environment. `

Do you mean here? https://admin.powerplatform.microsoft.com/environments

**Comment by TomasASvoboda** [comment]
Yes I mean this. 
I really can't find this environment, I can find other environments but not this one.

**Comment by Jenefer-Monroe** [comment]
Go to https://admin.powerplatform.microsoft.com/environments and filter to default. What do you see?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b5d7952d-96ab-419a-87fc-56c27e68d10c)

**Comment by Jenefer-Monroe** [comment]
This means you do not have sufficient permissions. 

Please confirm that you are logged in as the user installing and running the kit, and that the user has the Power Platform Admin Role assigned both directly and permanently? 
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

**Comment by TomasASvoboda** [comment]
I am attaching the screen. 
Everything is the same as in your screen.
![CoEScreenAdminsRights](https://github.com/microsoft/coe-starter-kit/assets/149689572/826851f9-00d6-427b-8c7e-a6afc8479418)

**Comment by Jenefer-Monroe** [comment]
OK, unfortunately this is a product issue and you'll need to contact product support.
As a Power Platform Admin, you should be able to see all the environments in the product's admin pages. The fact that you cannot is something I can't debug as I am not a member of the product dev team.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
