### ISSUE TITLE
[CoE Starter Kit Bug]: Flow Action Details Sync flow incorrectly evaluating FullInventory value

### ISSUE THREAD

**Issue by chrispiasecki** [microsoft/coe-starter-kit#699]
The **Admin | Sync Template v3 (Flow Action Details)** flow is not doing a full crawl on subsequent runs even when the FullInventory environment variable is set to **True**. 

The root cause looks to be the condition action called **Only proceed if changed since last updated in CoE or FullInventory**. It is checking if the string variable FullInventory is "yes", when it should be checking for "True". Or alternatively, like other sync flows, evaluate the environment variable parameter directly instead of using a string variable.

Admin | Sync Template v3 (Flow Action Details) condition is checking against yes
![image](https://user-images.githubusercontent.com/39163673/123520077-2cb7ff00-d66c-11eb-8e1a-4be3e762c877.png)

Here is an example flow run where the FullInventory environment variable is set to Yes.
![image](https://user-images.githubusercontent.com/39163673/123520126-5f61f780-d66c-11eb-83a5-0db0614f9a8e.png)
In the example, my flows haven't changed, and the full inventory check will always evaluate to false, therefore the condition results in false and never updates the flow action details on an unchanged flow.
![image](https://user-images.githubusercontent.com/39163673/123520162-9a642b00-d66c-11eb-9304-a9efa933ddd6.png)

You can see the Admin | Sync Template v3 (Flows) is evaluating against the environment variable boolean parameter value directly instead of using a variable.

![image](https://user-images.githubusercontent.com/39163673/123520346-7d7c2780-d66d-11eb-90fb-2ab9f21d30dd.png)

**Comment by JeneferM-MSFT** [comment]
thank you, we changed type and didn't complete the change across the board.
local fixed for July, and ran through all the flows in core to double check

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
