### ISSUE TITLE
App records are missing for our default environment in powerappapps table

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#6991]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Upon conducting random checks, we have identified that certain default environment app records are absent from the PowerApp app table, despite the continued existence and active usage of the respective apps, which are not considered orphaned. We attempted to rectify this by executing a full inventory, but unfortunately, it did not result in the creation of the missing app records. We are inquiring whether there may be an open issue related to this matter or if there could be an API limit affecting the default environment apps.

Admin | Sync Template v4 (Apps) is running on per flow license.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#599

**Comment by Rajatchopra3** [comment]
We have gathered the application IDs that we anticipate to find in our inventory and have diligently followed the steps you provided. Regrettably, we were unable to locate the records we sought. All the application records we are attempting to find currently reside in the default environment of our tenant and are actively in use. We kindly request your guidance in identifying the probable reasons for the flow's inability to generate records for the application IDs we are searching for. These application IDs are merely exemplars provided by users, and there may be numerous others.

**Comment by Jenefer-Monroe** [comment]
Are you saying that the app you are using to test with is not getting returned here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0a8e7ce7-7c9d-4222-86f1-aca257083013)

**Comment by Rajatchopra3** [comment]
yes, exactly

**Comment by Jenefer-Monroe** [comment]
Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently? 
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

**Comment by Rajatchopra3** [comment]
yes, the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently?

**Comment by Jenefer-Monroe** [comment]
OK I'm not sure then. This is an out of the box connector we are using so if its not returning all apps there isnt much we can do about that. You may need to contact product support.
I suggest you create a flow outside of the context of the kit to do this which only calls this action.

**Comment by Rajatchopra3** [comment]
Hi, we created a flow outside of the context of the kit to do this which only calls this action, as suggested and we were able to find the app id in the Json output. But we are still not getting the app records from Admin | Sync Template v4 (Apps)

**Comment by Jenefer-Monroe** [comment]
Perhaps you are using a different user to run the flow? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5c6c2617-416a-474a-b57d-02c590ba099a)

I just checked and the action is not changed since June. Correct version and pagination. 
Or perhaps you missed it in the output when you tested?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
