### ISSUE TITLE
[CoE Starter Kit - BUG] Access token has expiry while creating Environment 

### ISSUE THREAD

**Issue by Gokul-JB** [microsoft/coe-starter-kit#6994]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin approved the environment requests but behind the scenes it is not creating Power Platform environments. Please refer the below error

**Error:** The received access token has expiry UTC time '10/19/2023 11:48:52 AM' which is earlier than current UTC time '10/30/2023 2:27:55 PM'.

### Expected Behavior

Should create the environment

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

Env Request | Create Approved Environment

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1) Raise create environment request by Maker
2) Approve Admin

AB#602

**Comment by Jenefer-Monroe** [comment]
This likely means that your connection expired or otherwise broke. Please browse to connections in the environment as the user that setup the kit and repair any broken connections
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ac52c3f6-f538-47ed-a68f-2e31676aaa53)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
