### ISSUE TITLE
[ALM Accelerator - QUESTION] Progress status is missing for 

### ISSUE THREAD

**Issue by AdrianPPopa** [microsoft/coe-starter-kit#6999]
### What is your question?

In ALM Accelerator Canvas app, the status for COMMIT SOLUTION action is missing. The below screenshot from request history shows that the status for DEPLOY SOLUTION does not have this problem.

![image](https://github.com/microsoft/coe-starter-kit/assets/51173177/93c2c66a-5872-40c7-8df5-e693dc862bcb)

After hitting the COMMIT SOLUTION button I'm presented with this not very suggestive error message: 
![image](https://github.com/microsoft/coe-starter-kit/assets/51173177/3a226099-137d-4117-9f81-1ae79449ab92)

I tested the GetPipelines operation in the Custom Azure DevOps connection and it works just fine returning status 200 and all pipelines.

Also, the export-solution-to-git pipeline is triggered successfully in Azure DevOps.

Any idea how to fix this error? Let me know if further details are required.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231012.1

AB#610

**Comment by AdrianPPopa** [comment]
Just to add to initial request - same issue is with the IMPORT SOLUTION action:
![image](https://github.com/microsoft/coe-starter-kit/assets/51173177/c3aa6716-4f04-4636-9f33-514551a0e8d5)

Only DEPLOY SOLUTION action shows the status.

**Comment by mikefactorial** [comment]
@AdrianPPopa not seeing this behavior on my end. 


![Image](https://github.com/microsoft/coe-starter-kit/assets/42348035/81a330d7-41b9-4b67-83a5-7b5e47910863)


One question is do the pipelines for export, import and delete live in the same project as the repo configured on the deployment profile? I've seen issues with the status icons in the past when the pipelines are defined in another project.

**Comment by AdrianPPopa** [comment]
@mikefactorial thanks for your question, it helped me to pinpoint the misconfiguration. I'm using one single project but different repositories for ALM and Code versioning. The AzDO Pipeline Project was configured in deployment profile as the name of ALM repository instead of using the Project name. The api call for GetPipelines was requesting the history from the "ALM" project which does not exist hence the failure. After updating the AzDO Pipeline Project value with the project name it worked like a charm.

**Comment by mikefactorial** [comment]
@AdrianPPopa makes sense. Thanks for providing the update with the specifics of the issue. Hopefully it will help others who run into the same.
