### ISSUE TITLE
Pipelines: eliminate hard coding of pipeline definition '13' in build-Solution.yml

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#7]

**Comment by rpothin** [comment]
I do not know if you could apply the solution below in that case, but it is an idea and I think it could work.

- An example of a multistage pipeline: https://github.com/rpothin/Presentations/blob/main/20200823_NYC_PowerPlatform_2020/Pipelines_YAML/CI_CD/build-deploy-solution-to-qa-on-commit-on-main-branch.yml
- An example of pipeline template I use for the build part (publish an artifact): https://github.com/rpothin/Presentations/blob/main/20200823_NYC_PowerPlatform_2020/Pipelines_YAML/PipelineTemplates/pack-unmanaged-solution-template.yml
- An example of pipeline template I use for a solution deployment (download the artifact generated in a previous stage): https://github.com/rpothin/Presentations/blob/main/20200823_NYC_PowerPlatform_2020/Pipelines_YAML/PipelineTemplates/generate-managed-solution-template.yml

**Comment by devkeydet** [comment]
The fix is relatively easy.  It's just not been high priority in our current internal environment.  I consider this fit and finish as we track towards an initial release.  This is just an item to track and ensure we do it.

**Comment by devkeydet** [comment]
Resolved in private preview repo.
