### ISSUE TITLE
Privileges required for creating Team connection for CoE Tookit

### ISSUE THREAD

**Issue by challa85** [microsoft/coe-starter-kit#700]
Till today we are using Service account for importing/update the CoE solution and also the service account has Power Platform admin privileges. Now Teams connector came into the picture(where service account does not have teams license) and if we use the individual account for creating the Teams Connection, does the individual account should have privileges to read all the teams data(assuming my account is normal one and doesn't have any special privileges on Teams). In simple words can you please let us know what privileges does user should have who is going to create Teams connection for CoE Toolkit?

**Comment by manuelap-msft** [comment]
The Teams connection is used to Post adaptive cards to a Teams user as part of the Governance components workflows. https://docs.microsoft.com/en-us/power-automate/create-adaptive-cards 

This user does not need privileges to read all Teams information. Our pre-reqs are listed here https://docs.microsoft.com/en-us/power-automate/create-adaptive-cards
