### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to act on orphaned resources via Teams notification

### ISSUE THREAD

**Issue by KRhoadesHyp** [microsoft/coe-starter-kit#7008]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I doubt this is a bug since no one else has reported it.  We have a manager (a global admin) who has been receiving notifications from the Orphaned resources process since we enabled it,  I believe it is for 3 different makers, a few dozen resources.  He has not been able to Reassign or take ownership of any of them using the links in the Teams adaptive card, they just timeout or eventually come back with an error.  In digging through the '_Request Orphaned Objects Reassigned (Child)_' runs I found this error, undoubtable there are others - 
![image](https://github.com/microsoft/coe-starter-kit/assets/135135789/a5ae957e-6534-4b8e-acb7-03f725208400)

I am attaching the full text in the hopes you can tell me where to start looking?  I am looking for other managers to see if they have had better luck reassigning.

[error.txt](https://github.com/microsoft/coe-starter-kit/files/13270013/error.txt)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

October, 2023

### What app or flow are you having the issue with?

Orphaned Resources

### What method are you using to get inventory and telemetry?

Cloud flows

AB#620

**Comment by KRhoadesHyp** [comment]
Okay, I did see the Teams connector had an issue.  I will need to wait for the flows to re-run.

**Comment by KRhoadesHyp** [comment]
Will the change ownership buttons in the adaptive cards work on flows that are in solutions?  If not do they return a specific error or just a general failure?

**Comment by Jenefer-Monroe** [comment]
I believe that this works yes. And we do return specific error messages when something fails to the user.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team

**Comment by KRhoadesHyp** [comment]
In case anyone else runs into this, the errors were due to a Forms connection inside of the referenced flows.  The form belonged to a user who's account had been deleted.
