### ISSUE TITLE
Power Platform User Roles table missing flow shares

### ISSUE THREAD

**Issue by S0URCEC0D3** [microsoft/coe-starter-kit#7012]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the Power Platform User Roles table there are the app shares with other users/co-owners, the table contains a column for 'Apps' and another one for 'Flow', but the flow column doesn't contain any data. 

Do you know which flow is the one that feeds this table? Is this feature available for flows within this app?, if not where is this data stored? 

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2023

### What method are you using to get inventory and telemetry?

Cloud flows

AB#671

**Comment by manuelap-msft** [comment]
This feature is not yet available, it's on our backlog https://github.com/microsoft/coe-starter-kit/issues/1083

**Comment by Jenefer-Monroe** [comment]
closing out as a dupe.
