### ISSUE TITLE
[CoE Starter Kit - BUG]: Unable to Restore Flows After Archiving

### ISSUE THREAD

**Issue by MDRooks** [microsoft/coe-starter-kit#702]
**Describe the bug**
When archiving and then deleting Flows from the environment it saves the archived Flow as two JSON files, one for the body and one for the connectors. However, there is no way to automatically restore the Flow from these files.

**Component (please tell us which flow or app you are experiencing issues with):**
Governance

**To Reproduce**
1. Run the governance Flow: Admin | Flow Archive and Clean Up - Check Approvals and Archive
2. Select some Flows you would like to archive
3. View files stored in the archive location - they are JSON files which do not allow for any apparent way to restore them.

**Expected behavior**
I would expect either: 
a.) A Flow to restore the archived Flow from these JSON files or 
b.) Flows archived in .zip files formatted the same as an export.

**Comment by MDRooks** [comment]
A bit more information:
The CoE archives flows by using the Power Automate Management action “Get Flow”. It saves the contents of property “definition” and property “connectionReferences” as JSON files and stores those JSON files to a location. However, there does not appear to be a way to restore the Flow from the definition and connectionReferences information.

**Comment by JeneferM-MSFT** [comment]
Hello. There was a product change around connection references sometime last year which caused us to walk away from archiving the flows in the toolkit. We used to provide an app which allowed the admin to pull in these two json files and restore the flow but it quit working with that product change.

We now tell users to store their own archive (by exporting the flow) if they want to restore later. 

Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) and you will see this new system in which the flow/app owner are charged with their own backup. 

Sorry for the change.

**Comment by MDRooks** [comment]
Thank you for the quick response!
