### ISSUE TITLE
[CoE Starter Kit - BUG] Impact Analysis Results Incorrect

### ISSUE THREAD

**Issue by NattyG19** [microsoft/coe-starter-kit#7033]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When running the DLP Analysis app, applying a tenant level DLP policy using Exclude Certain Environments scope, the impact analysis results come back with 0 apps and 0 flows impacts. 0 apps and 0 flows analysed.

I have purposefully blocked a common connector to test this functionality and it still is not showing the correct results. 

When I choose Add to Multiple Environments as the scope, the impact analysis results in 67 impacted flows. However, the number of apps and flows analysed does not match what is recorded in the PPAC as the totals in those environments added.

Seems there is an issue with the scope options and all assets being picked up and analysed.

### Expected Behavior

Impact analysis should show and accurate list impacted apps and flows and an accurate count of apps and flows analysed for the environment parameters selected.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

DLP Impact Analysis

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Select an Applied Policy to test
2. Scope = Exclude Certain environments
3. Add excluded enviros to policy
4. Review impact results showing no impacts and no apps or flows analysed. 

### Anything else?

![DLP Impact Analysis Incorrect Results](https://github.com/microsoft/coe-starter-kit/assets/98507113/7bb2439c-a440-4efe-a846-b94e17a4b6f5)

AB#710

**Comment by manuelap-msft** [comment]
The DLP Impact Analysis tool works of the inventory stored in the CoE kit Dataverse tables which is populated by the sync cloud flows. Let's first verify that you have a complete inventory:

Can you check the Power Platform Admin View and do you see the full intenvory of environments, apps and flows there if you do a spot check?
Can you open the CoE Admin Command Center and the CoE flows page there to see if there's any issues with the flows responsible for inventory?

**Comment by NattyG19** [comment]
hi, I've checked the PP Admin View and the full list of environments are there, along with expected numbers of apps and flows which I've compared to the CoE Power BI report.  

I've just run the DLP Analysis app again and also used the previous DLP Editor V2 app (which we imported to the CoE Enviro) and both are not picking up on any non-compliance even though our end users were impacted when policies were Assigned to environments which was not meant to happen!

Also double checked all the sync flows are working as expected. 

The Command Center app is showing all sync flows are turned off when in fact they are turned on which I checked in the solution itself. That also seems to be an issue now. 

![Command Center App - Flows off when On](https://github.com/microsoft/coe-starter-kit/assets/98507113/fc39a71c-c735-4c03-8754-2f5c88066b4b)

**Comment by NattyG19** [comment]
I have since had one of my team look at the DLP Analysis app and we have found the problem

Issue: the DLP editor collects the **display name** of the connectors that are blocked/non-business, e.g "Gmail", "SharePoint", and then compares it to the asset record's "App Connections" or "Flow Connections" field (text field). 

This worked until the latest CoE version update, where the App/Flow Connections fields were changed to record the **idname** of the connectors, so they are "shared_gmail" and "shared_sharepointonline" now. Therefore nothing matches!!

![image](https://github.com/microsoft/coe-starter-kit/assets/98507113/eb98ee98-0917-4927-a0f6-3dab17a3d6a2)

**Comment by Jenefer-Monroe** [comment]
I just noticed that the on/off on that screen isnt working today too. Will post thank you

**Comment by Jenefer-Monroe** [comment]
I am not reproing this. We did change what is stored in apps/flows to be the id instead of the string quite a while ago, and it looks like you go that change. Will have to have the app owner take a look.

**Comment by Jenefer-Monroe** [comment]
@v-bjaiswal please see if you can repro

**Comment by Jenefer-Monroe** [comment]
Found a repro in which if you select "all environments" it does not get the impacted apps / flows.

**Comment by ramontebar** [comment]
Hi, we are having the same issue as described by @NattyG19 in our deployment when using "Exclude certain environments". Running latest Nov version.
