### ISSUE TITLE
DLP Impact Analysis - DLPs of type "All" and "Exclude" do not show correct envt count on list screen

### ISSUE THREAD

**Issue by jcgds** [microsoft/coe-starter-kit#7036]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, I created a DLP policy for all environments in my tenant, I checked that the policy is working as can be seen in the second image, however, in DLP Impact Analysis zero is displayed in the total number of environments, is this correct? Shouldn't it display the number of environments to which the policy is being applied? Thanks!

![1 1 DLP](https://github.com/microsoft/coe-starter-kit/assets/147111987/0e5ea1fa-fefe-4d22-b231-e9201b04eb08)
![1 2 DLP](https://github.com/microsoft/coe-starter-kit/assets/147111987/4f4e3373-948e-484b-ae6e-88257a1e5a60)
![1 3 DLP](https://github.com/microsoft/coe-starter-kit/assets/147111987/08b81f7a-7f30-4e1c-a5ae-e9852839e4de)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#725

**Comment by manuelap-msft** [comment]
The DLP Impact Analysis tool works of the inventory stored in the CoE kit Dataverse tables which is populated by the sync cloud flows. Let's first verify that you have a complete inventory:

Have you run the Setup Wizard after importing the solution to configure everything needed for inventory?
Can you check the Power Platform Admin View (model driven app) and do you see the full inventory of environments, apps and flows there if you do a spot check?
Can you open the CoE Admin Command Center and the CoE flows page there to see if there's any issues with the flows responsible for inventory?

**Comment by jcgds** [comment]
Hello Manuela! Apparently my inventory is ok, I checked and all flows are enabled. Please, what is the specific flow I need to check and what is the procedure to carry out this check? Thanks!

![4 4DLP](https://github.com/microsoft/coe-starter-kit/assets/147111987/9c513a55-a1b9-4a50-b577-e9013bf9f8be)



Admin | Sync Template v3 (Ai Models)
Admin | Sync Template v4 (Apps)
Admin | Sync Template v3 (Business Process Flows)
Admin | Sync Template v3 (Connection Identities)
Admin | Sync Template v3 (Custom Connectors)
Admin | Sync Template v3 (Desktop Flow - Runs)
Admin | Sync Template v3 (Desktop flows)
Admin | Sync Template v3 (Environment Properties)
Admin | Sync Template v4 (Flows)
Admin | Sync Template v3 (Model Driven Apps)
Admin | Sync Template v3 (Portals)
Admin | Sync Template v3 (PVA)
Admin | Sync Template v3 (PVA Usage)
Admin | Sync Template v3 (Solutions)
Admin | Sync Template v3 (Sync Flow Errors)
Admin | Sync Template v3 (Driver)
CLEANUP - Admin | Sync Template v3 (Check Deleted)
CLEANUP - Admin | Sync Template v3 (Delete Bad Data)
CLEANUP - Admin | Sync Template v3 (Orphaned Makers)
CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
CLEANUP - Admin | Sync Template v3 (PVA Usage)
Admin | Sync Template v3 (Call Updates)

**Comment by Jenefer-Monroe** [comment]
I'm not sure if this is a new install, it sounds like it is so to finish up on Manuela's questions, can you please browse to the [CoE Admin Command Center](https://learn.microsoft.com/power-platform/guidance/coe/core-components#coe-admin-command-center) > CoE Flows > Make sure the **_Admin | Sync Template v3 (Driver)_** flow has completed. 
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c82e030d-8059-4bd1-a2c4-12dd0bd6bea4)


And go to the [Power Platform Admin View](https://learn.microsoft.com/power-platform/guidance/coe/core-components#power-platform-admin-view) app and make sure you have apps/flows inventoried.
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c106ea1c-f9d6-4c83-a692-d26d046b8692)

**Comment by Jenefer-Monroe** [comment]
Oh I see. This is just a usability issue with the app for when DLPs are of type All Environments. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c9c4c807-c864-4398-91be-085a9e012036)

In the product view this shows "All" basically
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5623c992-2758-488d-8657-6b9b1b46441a)

While in our app we show zero for these
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/98c55c39-f67d-4f27-ab6c-f2d62feb4dad)

Hopefully thats an easy fix up.

**Comment by Jenefer-Monroe** [comment]
Looks like similarly we should 6 instead of all but 6 for type exclude
Product:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/33345b8e-9277-4149-8641-28d04f2b419d)

Our App:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b6bf8860-5e6e-4d8e-bd7c-8ca59373c114)

**Comment by Jenefer-Monroe** [comment]
Hopefully this is an easy fix up. Will try for Dec if it is.

**Comment by jcgds** [comment]
Thanks Jenefer!
