### ISSUE TITLE
[CoE Starter Kit - QUESTION] Reliability and Automation Failure Event Storage Question

### ISSUE THREAD

**Issue by mrmonto1** [microsoft/coe-starter-kit#7038]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, our IT group responsible for the CoE has been asked the following questions from our Information Systems Security Manager.  Any information provided would be extremely helpful.  Thanks!

**How reliable is the CoE solution for continuous monitoring?** 

**Additionally, how long are events stored in the CoE in event of an automation failure?**

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

AB#727

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
