### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by gghaleb** [microsoft/coe-starter-kit#7039]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How in the CoE we can best monitor the existing licenses? 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Sept 2023

### What app or flow are you having the issue with?

none

### What method are you using to get inventory and telemetry?

Cloud flows

AB#728

**Comment by Jenefer-Monroe** [comment]
Unfortunately we do not have a licensing story in the CoE Starter Kit. We do not have access to the information programatically and in a way that can scale to the org sizes we see.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
