### ISSUE TITLE
[CoE Starter Kit - BUG] Error in orphan objects module

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#7040]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

Please the flow: REQUEST RESIGNED ORPHAN OBJECTS (PARENT) is showing an error in the step: SEND EMAIL ADMIN OF THE ORPHANS THEY WILL NEED TO RESOLVE, we think that because of this error the flow does not continue and cannot proceed with the next actions, you Can you confirm if this is an error in the flow or some wrong parameter?

### Expected Behavior

It would be necessary to run this flow: REQUEST RESIGNED ORFHAN OBJECTS (PARENT) without errors and in parallel run the flow: REQUEST ORPHANED OBJECTS REASSINGNED (CHILD), however the first flow gives an error and no longer completes the process.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

![Versao CoE-hoje](https://github.com/microsoft/coe-starter-kit/assets/129080740/d8371cb8-a7a2-4f93-966a-77b394bd455a)
![Erro 1](https://github.com/microsoft/coe-starter-kit/assets/129080740/065884e2-987c-4358-81bf-eb93048ba64e)
![Erro 2](https://github.com/microsoft/coe-starter-kit/assets/129080740/469e1203-f01a-43a5-ae7b-7681bf0759d8)
![Erro 3](https://github.com/microsoft/coe-starter-kit/assets/129080740/1a076dd3-cc91-4d67-8a6f-40904b5f9b59)

AB#732

**Comment by Jenefer-Monroe** [comment]
It sounds like the helper flow is not turned on: **_HELPER - Send Email_**

Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by minobrega** [comment]
Hello Jenefer..

Thank you for your help..

Only one flow had another layer that I removed, the HELPER - SEND EMAIL flow is active and running without errors.

![Help send email](https://github.com/microsoft/coe-starter-kit/assets/129080740/5f3409eb-7347-4cff-b309-0c6539e080e3)

![help send email2](https://github.com/microsoft/coe-starter-kit/assets/129080740/dfc338b1-403e-4bb1-8642-bff680def516)

**Comment by Jenefer-Monroe** [comment]
Strange. It is failing to call that child flow and complaining about the trigger. 
I know it sounds odd but can you turn that child flow (HELPER - Send Email) off and back on, and see if it works? Sometimes triggers for child flows cache in parent flows.

**Comment by minobrega** [comment]
I deactivated and activated the flow: HELPER - SEND EMAIL but the flow: Request Orphaned Objects Reassigned (Parent) continues to give an error

![erro 4](https://github.com/microsoft/coe-starter-kit/assets/129080740/9c09b4f7-0c84-4f49-b505-89a1e0d56b57)

![erro 5](https://github.com/microsoft/coe-starter-kit/assets/129080740/488fb3a3-8b0d-4e7d-bb53-b94b97172230)

**Comment by Jenefer-Monroe** [comment]
Can you put the flow in edit mode and see what you have for input to the child flow?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0509044b-1ade-4661-8b68-f9e05c4cefa6)

**Comment by Jenefer-Monroe** [comment]
and also look at the latest run and see what is entered for this variable
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d8bb325a-390a-4af4-8901-8686d50d835b)

**Comment by minobrega** [comment]
![print 2](https://github.com/microsoft/coe-starter-kit/assets/129080740/ca364503-34ab-4cab-97d6-59c4d1182e56)
![Print 1](https://github.com/microsoft/coe-starter-kit/assets/129080740/bf9c1673-e0e7-4bbb-9147-cd10e8fb5d3e)

**Comment by Jenefer-Monroe** [comment]
Bingo we found the problem! That env var needs to be an email. 
Please go to the CoE Admin Command Center > Environment Variables > update the Admin eMail env var to be an email address instead of a GUID
You may need to turn this Parent flow off and back on in order for the variable to not be cached in the flow after you update it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/47081fb7-a25d-4d46-b994-2fa775295e02)

**Comment by minobrega** [comment]
Wow, this change was made at the beginning when we were implementing the CoE, we immediately put this ID in place of the Email.. I made the changes and ran the main flow again.. I'm waiting..

I'll let you know when it's finished.. for now, thank you very much Jenefer.. :)

![erro8](https://github.com/microsoft/coe-starter-kit/assets/129080740/72b3f509-5f50-4ffb-a46a-5bb21dbe2968)

![Erro 6](https://github.com/microsoft/coe-starter-kit/assets/129080740/9daea676-d544-4964-8c3a-6c23d0d3084f)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team

**Comment by minobrega** [comment]
Hello Jenefer..

Sorry for the delay, but the flow worked for 7 days straight after correcting this email parameter.

It took a while to finish the execution but there were no more errors in the flow.

Thanks a lot for the help..
