### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by 1jena5** [microsoft/coe-starter-kit#7043]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In our App and Flow Inactivity Notifications Clean Up it shows that there's a lot of Yes in the Deleted column, but in the PowerBI Dashboard there's only few count of deletes apps and flows. I checked the table and it's different in the PowerBI dashboard I am referring to. Can you please how can I get the count of deleted apps and flows from the clean up? Are they really deleted?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2023

### What app or flow are you having the issue with?

App and Flow Inactivity Notifications Clean Up

### What method are you using to get inventory and telemetry?

Cloud flows

AB#753

**Comment by Jenefer-Monroe** [comment]
For the cloud flow architecture, the PBI reads directly from the table. Have you refreshed the dataset? 
You should consider configuring daily refresh: https://learn.microsoft.com/power-bi/connect-data/refresh-scheduled-refresh

**Comment by 1jena5** [comment]
Yes it has a daily refresh. Can you advise what column should I look at so I can get the count of the deleted apps and flows from the inactivity/clean up process flow? I am looking at admin_appdeleted, admin_appdeletedon, admin_flowdeletedon and admin_flowdeleted.

**Comment by 1jena5** [comment]
Are the apps and flows deleted will be deleted in the PowerBI dashboard as well after how many days? I checked the apps that are marked as deleted in the App and Flow Inactivity Notifications Clean Up app and they no longer shows in the dashboard the admin_appdeleted = true only shows 1 number which was deleted yesterday Nov 8 by a maker. I just thought they will be retained with deleted date because they are still in the app. Kindly advise.

**Comment by Jenefer-Monroe** [comment]
Sorry I'm having trouble following the issue here. Can you please share screenshots of what you see v what you expect to see?

**Comment by 1jena5** [comment]
![inactivityss](https://github.com/microsoft/coe-starter-kit/assets/94581451/7fac1a63-2892-48db-9ac7-14850a2c0c82)
![PBIss](https://github.com/microsoft/coe-starter-kit/assets/94581451/7611e901-6d0c-4a02-a4c0-d7000cc72ebe)


You can see in the screenshots that in PBI I can only see 2 items deleted but in the App and Flow Inactivity Notifications Clean Up app there should be more than that (Deleted = Yes column). I wanted to show in our dashboard how many were deleted from the Inactivity workflows. Can you please direct me on the correct column I should use in PBI?

**Comment by Jenefer-Monroe** [comment]
That is the correct field to use. But depending on this setting, we do clean up deleted objects from inventory periodically.
Can you please check its setting?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a4d6cf5b-6a54-40c3-8af8-5fb4ce51d737)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
