### ISSUE TITLE
[CoE Starter Kit - BUG Data Export] BYODL: Model Driven Apps Owners returned as System

### ISSUE THREAD

**Issue by tkudya** [microsoft/coe-starter-kit#7044]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Model Driven App owner/creators are not being populated correctly, it's return ownership as SYSTEM. when the app is actually now owned by Existing Owner and data in PPAC says the person. 
![image](https://github.com/microsoft/coe-starter-kit/assets/78653328/65412653-91df-43cd-8c59-e4ac0b3aefa4)

### Expected Behavior

have correct owner displayed

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

DataFlow

### What method are you using to get inventory and telemetry?

Data Export

AB#754

**Comment by Jenefer-Monroe** [comment]
I am seeing this too. Sending to owner for consideration with the other Dataflow work targetting Dec release.

**Comment by lukas-nC** [comment]
The DataExport does not export any Principal ID in the Modeldriven JSONs
<img width="191" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113470539/e546545c-6dfa-4b15-b2a8-bed27236f4d9">
in combination with this step in the dataflow
<img width="518" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113470539/c784b86d-1044-42c1-85da-2cbc4ab64e02">
every Modeldriven app is SYSTEM owned

@Jenefer-Monroe  Can you contact the DataExport team?

**Comment by Jenefer-Monroe** [comment]
Tracked by https://github.com/microsoft/coe-starter-kit/issues/6658
Manuela will be working with product team

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
