### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#7045]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Team

Can u please confirm when you will be releasing November month release.

Also please confirm in this Release have resolved the New Environment request creation. Because in last month release it's not working any alternative solution for this please share.. This is bit critical.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Maker - Environment Request.

### What method are you using to get inventory and telemetry?

None

AB#755

**Comment by Jenefer-Monroe** [comment]
Hello. We target shipping on the Wednesday of the first full week each month. So that's today! We are ready and just waiting for our partner teams to finish up a few tasks and then it will go live.

I'm not sure what bug you are referencing for Envt Request. Do you have one already posted that we are tracking?

**Comment by sunilmhatugade** [comment]
Referance Ticket no..#6815

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/cb38f5d7-ea75-42ee-baeb-36a2a3bcfa64)

**Comment by sunilmhatugade** [comment]
this is not working...

**Comment by Jenefer-Monroe** [comment]
This bug is marked as ready for the Nov release. 
Please be sure you remove any unmanaged layers during your upgrade so you can see the changes.
Thank you
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fb3d8950-2d17-4899-af92-1b02d368833d)

**Comment by sunilmhatugade** [comment]
Please confirm once Nov 2023 release published..

**Comment by sunilmhatugade** [comment]
Can u please confirm when your will be release Nov 2023 month release. We have to fix some bugs which were found in Oct month release. this is bit urgent

**Comment by Jenefer-Monroe** [comment]
Nov is out, although there is a product bug hitting some folks on upgrade: https://github.com/microsoft/coe-starter-kit/issues/7050

So I'll go ahead and close this,

**Comment by Jenefer-Monroe** [comment]
Work around has been posted in https://github.com/microsoft/coe-starter-kit/issues/7050
Please see https://github.com/microsoft/coe-starter-kit/issues/7050#issuecomment-1806035240
