### ISSUE TITLE
Getting CustomAzureDevOps.GetIdentities faild error while loading app

### ISSUE THREAD

**Issue by NIhil1409** [microsoft/coe-starter-kit#705]
HI Mike @mikefactorial 

I had some issue with ALM for Advance Makers App, so i have to re-configure app and now i am getting below error. 

I have re-checked custom connector but can't see what's the issue.

Can you please let me know what i am missing.? 

Any help would be appreciated. 

![image](https://user-images.githubusercontent.com/82605803/123822775-7c106080-d8f4-11eb-96e4-e49f3883d2d7.png)

**Comment by devkeydet** [comment]
Can you go into the custom connector test UI and try to call it from there?
![image](https://user-images.githubusercontent.com/4499296/124116232-b71dab80-da3c-11eb-8f50-11573048ad6b.png)

You can get organization from https://dev.azure.com/you-azure-devops-organization-here

Use **MailAddress** for **searchFilter**

Use the email address for the logged in user for **filterValue**

**Comment by mikefactorial** [comment]
Hey @NIhil1409,
Any update on this? Is it okay to close this issue?
Thanks
Mike

**Comment by NIhil1409** [comment]
@mikefactorial 

Sorry, i was on leave, so didnt update, 

Yes, thanks it worked you can close this issue

thanks
