### ISSUE TITLE
[ALM Accelerator - QUESTION] After pull request is complete, how to kick off pipeline?

### ISSUE THREAD

**Issue by FabianAckeret** [microsoft/coe-starter-kit#7057]
### What is your question?

When clicking on the _**DEPLOY**_ button the pull request will be created to merge it into the target branch. If the request is complete, how are the pipelines that import the solutions to the target environment being kicked off? 

So far, everything works great. Pipelines for my projects are being created automatically, pull requests are either completed automatically or manually, but no pipelines are being kicked off after that. What do I need to do, to make that happen?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20231012.1

AB#775

**Comment by RajeevPentyala** [comment]
@FabianAckeret Let me explain on how the pipeline trigger works using a scenario. Feel free to reach out if you have any questions or need clarifications.

- My solution name is 'Classic Plugin'. When I commit the solution for the first time, a set of deployment pipelines is created.
- Additionally, two new branches, 'user' branch and 'feature' branch (i.e., branch with the solution name), are created.
- When deploying the solution, selecting the 'Source Branch' as 'user' branch and 'Target Branch' as 'feature' branch (i.e., branch with the solution name), a pull request (PR) is generated.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/a218fc66-6c89-49fb-b684-b744c7d045fb)

- The deploy to test pipeline (i.e., 'deploy-test-{solution_name}') includes a trigger to your 'Solution Branch.' Consequently, upon approving the pull request, the 'deploy-test-{solution_name}' pipeline is triggered, deploying the solution to your test environment.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/49d71987-c203-4d1e-83d7-ed217b975269)

- Finally, to deploy the build to PROD, click on 'Deploy,' select the 'Source Branch' as 'feature' branch (i.e., branch with the solution name), and 'Target Branch' as 'Main.' This action creates a pull request (PR). After approving the PR, the 'deploy-prod-{solution_name}' pipeline is triggered, deploying the solution to the production environment.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/0f2c89cc-8a65-44d2-8c9a-cd2c93ed79b8)

**Comment by FabianAckeret** [comment]
Hi @RajeevPentyala 

Thanks so much for the detailed explanation. This makes it much more clear than it was before.

Cheers!

**Comment by jhasaroj** [comment]
Hi Rajeev,
Thanks for the pointer for query #7092 >
But still can't view any associated pipelines being called for "Deploy Solution" stage,.
![Deploy](https://github.com/microsoft/coe-starter-kit/assets/150776931/9b13ff03-bcea-406c-a4f7-1f2723a2041c)

Not sure, if I am missing something at which stage. Also for validation stage, if similar pull request being created and on approval, Pipeline will be invoked.
![Pull req approval](https://github.com/microsoft/coe-starter-kit/assets/150776931/58ee0b14-e3a0-4c32-9037-7a86eb85c771)

Kindly please elaborate if any specific details or pointers which I need to explore to make this work.

Also Import Solution, can be imported to any other environment other than Dev.. Is there any way to change / duplicate import-unmanaged-to-dev-environment and pass parameters by some .net application or otherwise.
 Thank you for your time and patience :)
Regards,
Saroj

**Comment by nrawev** [comment]
Hi Rajeev,

I've verified the yaml pipeline for solution branch (Test branch in our landscape) and looks correct. However, before Test branch, we have validation branch. 

The issue in our case is, when we run the deployment, validation branch skips and test branch starts to run and then ends up in some errors that is not so clear to back track.

We would appreciate any help/information. Thanks in advance. 

Kind regards,
Nikunj

**Comment by Srikanth-Singapuram** [comment]
> @FabianAckeret Let me explain on how the pipeline trigger works using a scenario. Feel free to reach out if you have any questions or need clarifications.
> 
> * My solution name is 'Classic Plugin'. When I commit the solution for the first time, a set of deployment pipelines is created.
> * Additionally, two new branches, 'user' branch and 'feature' branch (i.e., branch with the solution name), are created.
> * When deploying the solution, selecting the 'Source Branch' as 'user' branch and 'Target Branch' as 'feature' branch (i.e., branch with the solution name), a pull request (PR) is generated.
>   ![image](https://private-user-images.githubusercontent.com/104883923/282414942-a218fc66-6c89-49fb-b684-b744c7d045fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MDY4NDUsIm5iZiI6MTcyNDcwNjU0NSwicGF0aCI6Ii8xMDQ4ODM5MjMvMjgyNDE0OTQyLWEyMThmYzY2LTZjODktNDlmYi1iNjg0LWI3NDRjN2QwNDVmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQyMTA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjAxMzYxZmE5MWE3YmU2NTI2MDliOGU4OWIwZjg4MDlmMmFiMzZhMzI2YjllMGQzZWU3MzVkNWI4YzE5NGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z5trftwzRgp-NhcRPfMhxImAwcPHalrUInoOFJi7Oqs)
> * The deploy to test pipeline (i.e., 'deploy-test-{solution_name}') includes a trigger to your 'Solution Branch.' Consequently, upon approving the pull request, the 'deploy-test-{solution_name}' pipeline is triggered, deploying the solution to your test environment.
>   ![image](https://private-user-images.githubusercontent.com/104883923/282413318-49d71987-c203-4d1e-83d7-ed217b975269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MDY4NDUsIm5iZiI6MTcyNDcwNjU0NSwicGF0aCI6Ii8xMDQ4ODM5MjMvMjgyNDEzMzE4LTQ5ZDcxOTg3LWMyMDMtNGQxZS04M2Q3LWVkMjE3Yjk3NTI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQyMTA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDM5MGI2MDQ2YjZhYjc0MWZkZTJhNzIyMTI4YmNkMDU4NjVjZTQ3ZTkzY2Y4MmNiMzdhZmM3ZDM5YTIwMjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fyD-bpOm9tDtBFYEkToBXtefne9QSH94KrhM23O5dio)
> * Finally, to deploy the build to PROD, click on 'Deploy,' select the 'Source Branch' as 'feature' branch (i.e., branch with the solution name), and 'Target Branch' as 'Main.' This action creates a pull request (PR). After approving the PR, the 'deploy-prod-{solution_name}' pipeline is triggered, deploying the solution to the production environment.
>   ![image](https://private-user-images.githubusercontent.com/104883923/282418101-0f2c89cc-8a65-44d2-8c9a-cd2c93ed79b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MDY4NDUsIm5iZiI6MTcyNDcwNjU0NSwicGF0aCI6Ii8xMDQ4ODM5MjMvMjgyNDE4MTAxLTBmMmM4OWNjLThhNjUtNDRkMi04YzlhLWNkMmM5M2VkNzliOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQyMTA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzIxZWNlODEyNWI1NzY4MWQ1NTZhZjNiN2NkMzk0ZGZmYzFmYjdhMzhhODNiN2M0ZjgzYmViYjRjNWMyNWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7yaidVC8Dt1dk1WRiQXqumttyTmWiv3lgy4PEd3EPdU)

@RajeevPentyala I have followed the above steps, Upon committing the solution, only the user branch is created, and the feature branch is not generated. Is it necessary for us to create the feature branch manually? Furthermore, during the deployment of the solution throught the "Deploy Solution" button, a pull request (PR) is initiated. However, after approval and the completion of the merge, it does not trigger the build pipeline. In cases where PR "approval is not needed", the PR automatically approve and merges the feature branch changes into the master branch, but it does not trigger the build pipelines. 

After I configure the build policies and they are triggered, the feature branch merges into the master following the completion of the pipeline. Could you please inform me if we need to implement build validation for the branch policies?


![image](https://github.com/user-attachments/assets/4b4a8da2-17e9-4e2d-afbd-d4339647fde5)


![image](https://github.com/user-attachments/assets/4300a89f-7d42-42c9-ac1a-e6ad4412c7f6)
