### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Platform Admin View Active Flow Manage Permissions - What exactly does the "Can view" option? 

### ISSUE THREAD

**Issue by ramonabadea** [microsoft/coe-starter-kit#7058]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello,

I am trying to get around in understanding what exactly does the **"Manage permissions" feature do when I select "View Only" as permission level on an active flow when using the Power Platform Admin View**?

I tried to add myself as view-only on an active flow and I received a very nice notification email from PowerAutomateNoReply, but when clicking on "View flow", I get an error that I am not authorized to see the flow.
Also, if I share a flow from PPAC > Environment > Resources > Flows > select the flow > Share, there is no "ViewOnly" permission, so could someone please let me know what does this functionality in the Starter Kit does?

![image](https://github.com/microsoft/coe-starter-kit/assets/32679106/e8975073-d8b7-4597-b0cd-a2e6425f9c3f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#778

**Comment by Jenefer-Monroe** [comment]
This is one of the permission options available when changing permissions for a flow

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f798b859-53a6-4249-8190-405825385659)

It corresponds to the Run only users list: [Share a cloud flow with run-only permissions](https://learn.microsoft.com/power-automate/create-team-flows#share-a-cloud-flow-with-run-only-permissions)


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/214085a2-7531-47de-900a-e4abf0d66b36)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/affba1c6-7385-4213-8911-00d585875d6e)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
