### ISSUE TITLE
[CoE Starter Kit - QUESTION] COE query/save all audit logs or only app launches?

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#7059]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi CAT team,

I would like to check what COE audit log flows query/save to environment?

 does it first query all audit logs then only save app launches records to COE environment dataverse table?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Oct 2023

### What app or flow are you having the issue with?

Audit log flow

### What method are you using to get inventory and telemetry?

Cloud flows

AB#779

**Comment by Jenefer-Monroe** [comment]
That is correct. We pull in all the logs and the filter to the Power Platform ones we are tracking.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
