### ISSUE TITLE
[CoE Starter Kit - BUG] CenterofExcellenceCoreComponents_4.17 Import failure

### ISSUE THREAD

**Issue by SPMush** [microsoft/coe-starter-kit#7063]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to Import Core Components in November release. Attempting to upgrade from 4.16 & Attempting to Import into new environment failing every time:
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/4c88a8d0-d2f7-4089-967e-df9b245594f3)

### Expected Behavior

Unable to Import Core Components in November release. Attempting to upgrade from 4.16 & Attempting to Import into new environment failing every time:
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/4c88a8d0-d2f7-4089-967e-df9b245594f3)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Import Solution

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Create a Production Environment with Dataverse
Import Creator kit Solution
Import Core Components 4.17 
Add all Connections
Click Next 
![image](https://github.com/microsoft/coe-starter-kit/assets/55295944/68ced71b-3bab-4be0-9bde-7c3967660a79)

I get the same attempting to upgrade existing 4.16 Version.

### Anything else?

Can import other solutions without issue, Just the core failing, multiple attempts as an upgrade and in a newly provisioned  environment.

AB#805

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, this is an issue impact some but not all users and some but not all solutions
Product team is investigating and we are tracking with https://github.com/microsoft/coe-starter-kit/issues/7050
I'll go ahead and close as a dupe.

**Comment by Jenefer-Monroe** [comment]
Work around has been posted in https://github.com/microsoft/coe-starter-kit/issues/7050
Please see https://github.com/microsoft/coe-starter-kit/issues/7050#issuecomment-1806035240
