### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Unmanaged layer issue 

### ISSUE THREAD

**Issue by Isaiah-1234** [microsoft/coe-starter-kit#7066]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

We had issue on Prod COE Kit on few apps which we had customized and this formed an unmanaged layered, By mistake we deleted those layer and now its throwing error, Hence we want help in exporting the old solution from Dev and import on Prod.

### Expected Behavior

We had issue on Prod COE Kit on few apps which we had customized and this formed an unmanaged layered, By mistake we deleted those layer and now its throwing error, Hence we want help in exporting the old solution from Dev and import on Prod.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Developer center app

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Export the solution from Dev and import it in Prod as managed solution

### Anything else?

We had issue on Prod COE Kit on few apps which we had customized and this formed an unmanaged layered, By mistake we deleted those layer and now its throwing error, Hence we want help in exporting the old solution from Dev and import on Prod.

AB#808

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid I dont follow here what help you are asking for or what question you might have. 
Can you please be more specific? 
Here is our general documentation on how to [extend the kit](https://learn.microsoft.com/power-platform/guidance/coe/modify-components)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
