### ISSUE TITLE
[CoE Starter Kit - BUG] November Release has the October Version of the CoE Dashboard

### ISSUE THREAD

**Issue by BenUnlox** [microsoft/coe-starter-kit#7069]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Looks like the October version of the CoE Dashboard has been included in the November release.

![Screenshot 2023-11-10 at 12 26 46](https://github.com/microsoft/coe-starter-kit/assets/108944628/6c10200e-93ee-4492-9da2-f6572d09ed8b)

If this is the correct version, then [Issue #6900](https://github.com/microsoft/coe-starter-kit/issues/6900) has not been resolved. 

### Expected Behavior

November release should include November version of CoE Dashboard

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

N/A

### What app or flow are you having the issue with?

N/A - CoE Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Download latest CoE release.

AB#812

**Comment by manuelap-msft** [comment]
That's correct. We didn't make any changes to the dashboard this month.

**Comment by BenUnlox** [comment]
Thanks @manuelap-msft  - just to confirm that #6900 hasn't been resolved then and so we'll need to manually remove the filter?

**Comment by Jenefer-Monroe** [comment]
Correct, none of the bugs slated for Nov have been fixed, we just reshipped the Oct relesae of the PBI and all those bugs slipped out to Dec.
