### ISSUE TITLE
[CoE Starter Kit - BUG] CoE BYODL Makers failing with error: We found extra characters at the end of the JSON input. DetailsReason = DataFormat.Error Value = , Position = 26984

### ISSUE THREAD

**Issue by RebekkaAalbers** [microsoft/coe-starter-kit#7071]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to set up a fresh environment using the BYODL setup. 
After configuring the connections for the CoE BYODL Makers dataflow, I receive the error message:
DataFormat.Error: We found extra characters at the end of the JSON input.
DetailsReason = DataFormat.Error
Value = ,
Position = 26984

The error occurs during the second step of the Makers query:
<img width="178" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/30928094/3796d74e-01cc-4859-b8d7-8e23b93320e1">

### Expected Behavior

Dataflow runs without errors. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

CoE BYODL Makers

### What method are you using to get inventory and telemetry?

Data Export

AB#814

**Comment by manuelap-msft** [comment]
We fixed some of this in more recent releases (see https://github.com/microsoft/coe-starter-kit/issues/6577 
 and https://github.com/microsoft/coe-starter-kit/issues/6723). 

However, there's a larger rework of the Dataflows planned for December https://github.com/microsoft/coe-starter-kit/issues/6969

**Comment by RebekkaAalbers** [comment]
The documentation states you need to use this version to setup BYODL. Is that not the case?

**Comment by Jenefer-Monroe** [comment]
I believe that means the minimum version. Current versions of the kit do support BYODL.

**Comment by RebekkaAalbers** [comment]
@Jenefer-Monroe, the documentation specifically links to the version I imported and doesn't state anything about later versions. Maybe good to update the text a bit. I'll import the latest release.
<img width="623" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/30928094/17a0570e-dccc-40c0-b6f7-50ae90b3e022">

**Comment by manuelap-msft** [comment]
Thanks for letting us know about the incorrect link. Updated it now to point to the latest release!

**Comment by A-Demir-ilx** [comment]
Hi @manuelap-msft , Is this already fixed? I am now getting this in the January release. 

![image](https://github.com/microsoft/coe-starter-kit/assets/96475793/ff37ac71-2006-47d1-9d14-f5e075bca27e)
