### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Request is not working in CoE Maker Command Center

### ISSUE THREAD

**Issue by Ravindra-He** [microsoft/coe-starter-kit#7074]
**Describe the issue**
Environment Request process is not working in CoE Maker Command Center app.

![image](https://github.com/microsoft/coe-starter-kit/assets/150462869/c7adcd28-9f9f-48bc-97b1-282149c2d981)

**What solution are you experiencing the issue with?**
Core

**What solution version are you using?**
4.16

**What app or flow are you having the issue with?**
CoE Maker Command Center

**Steps To Reproduce**
Navigate to CoE Maker Command Center ---- > Play ----- > Create New Environment Request ---------> Select Connectors ----- > Click OK button (no any other options are present)

AB#816

**Comment by manuelap-msft** [comment]
This was fixed with the most recent release, see: https://github.com/microsoft/coe-starter-kit/issues/6967

You will have to upgrade to apply the fix.

**Comment by Ravindra-He** [comment]
Thanks you. Will upgrade and check this again.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by iSK101** [comment]
While creating an Environment creation request, nothing happens when I am clicking on the "Next" button after adding the connectors. Can anybody help me with this? Am I missing something?

![image](https://github.com/microsoft/coe-starter-kit/assets/171793932/1ac4c155-375e-4885-bbfa-ee1f3066aaa9)
