### ISSUE TITLE
Process Licensing

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#7076]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Were trying to see how the new Process License can be used with our flows, but we can't see any example of best practices, or whether or not you can assign the Process license to more than one flow.

Anyone have any ideas on how to best use this license with the Toolkit?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#818

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
