### ISSUE TITLE
CoE Compliance Detail Request v3 reviews Canvas Apps and Chatbots only

### ISSUE THREAD

**Issue by skarser** [microsoft/coe-starter-kit#7078]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

 I'm wondering if the introduction of Data Export is going to change how 'Admin|Compliance detail request v3' works?

 My experience is that 'Admin|Compliance detail request v3' only reviews Canvas apps and chatbots it does not review model driven apps and other objects for compliance?

Looking at the flow, the Dataverse action 'List Rows', named as 'List this envt apps', filters the rows of the dataverse table 'PowerApps Apps' with 'admin_powerappstype eq 597910000 ' which is a canvas app. Is there a reason for the filter excluding model-driven apps?

In the documentation for the Developer Compliance Center ([https://learn.microsoft.com/en-us/power-platform/guidance/coe/governance-components#compliance-statu...](https://learn.microsoft.com/en-us/power-platform/guidance/coe/governance-components#compliance-status)) it says:

"...allows makers to check the compliance status and submit more details for the following resources:

Canvas apps
Model-driven apps
Flows
Bots
Custom connectors
Desktop Flows
Solutions
Environments
So I assumed the compliance flow would be looking at all these objects.

am I missing something?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.4

### What app or flow are you having the issue with?

Admin|Compliance detail request v3

### What method are you using to get inventory and telemetry?

Cloud flows

AB#825

**Comment by Jenefer-Monroe** [comment]
We do not have usage information for MDAs even with the Data Export feature. So at this time we do not have a path to extend that system to include those types of apps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by KV-MY** [comment]
I believe my problematic orphaned app and environment does not has Solution installed, i went to Power Platform Admin View > Solutions and filter by the specific app environment, it shows nothing as well
