### ISSUE TITLE
Desktop Flows without inventory

### ISSUE THREAD

**Issue by jcgds** [microsoft/coe-starter-kit#7082]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Guys, Good morning! All my inventory flows are active, however, there is no collection of Desktop flows, is there any procedure that must be performed to enable collection in relation to Desktop Flows? Any documentation on this topic? I identified this problem when I enabled a DLP policy based on the connectors mentioned in the Power Platform Admin Center.
Thanks!
![1 1DesktopFlows](https://github.com/microsoft/coe-starter-kit/assets/147111987/e317688c-f80e-4d65-b610-9d0025c4e8f3)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#832

**Comment by Jenefer-Monroe** [comment]
Hello. Until the Nov release, the desktop flow inventory in the CoE Starter Kit had several limitations that made it insufficient for most organizations. In particular most desktop flows his a size limitation and were not able to be inventoried. This was tracked by https://github.com/microsoft/coe-starter-kit/issues/419 and we shipped it (off by default) in Nov release with https://github.com/microsoft/coe-starter-kit/issues/6946
So to get Desktop Flow inventory, please check out the steps described in https://github.com/microsoft/coe-starter-kit/issues/6946. Basically its turning off one flow and another one on.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
