### ISSUE TITLE
[CoE Starter Kit - QUESTION] Core Component Upgrade on 4.17 says a end time but it is still running in the background is that normal

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#7086]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Normally if this has a end time the solution is finished but this is clearly still running I even refreshed the paget and when I saw that I wanted to start the Check Deleted Cloud Flows it says the import is still going on. It has been an hour since the import started.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/bfad37a8-62c1-4126-ad1a-a2d8c1e8f6bd)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Cleanup Helper - Check Deleted (Cloud Flows) 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#836

**Comment by Jenefer-Monroe** [comment]
This is just a change in the product UX which unfortunately I cant comment on more than to say I've seen this myself as well. 
The uninstall has always been a separate step but it used to be explicitly listed in history and now its not. If you go look you shoudl see Core and Core_upgrade while you wait for the uninstall to complete.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
