### ISSUE TITLE
[CoE Starter Kit] Power BI can't open due to admin_containpasswordvalidation column

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/coe-starter-kit#709]
**Describe the bug**
When I refresh the Power BI Report I get the below error message. 

Data source error: The 'admin_containpasswordvalidation' column does not exist in the rowset.
Cluster URI: WABI-WEST-US-B-PRIMARY-redirect.analysis.windows.net
Activity ID: dcd0e311-e4a2-41dd-aceb-3fe91b6c91b5
Request ID: 6475d979-b25a-9b9c-1b0b-eb8ee85366a7
Time: 2021-06-30 00:33:13Z

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

thanks for providing this information - I'm not familiar with this field. What version of Core are you on?

Would you be able to please try something, we are just getting the dashboards ready for the July release and have made massive improvements in terms of what fields are brought back into the Power BI Dashboard. Would you be able to try the new dashboard out and see if you experience the same issue there? Please note, you will likely have to be on the last version of Core Components for those new dashboards to work. 

[CoE Power BI Dashboard - Common Data Service (Legacy) connector - July](https://github.com/microsoft/coe-starter-kit/raw/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/CDSLegacy_CoEDashboard_202107.pbit)
[CoE Power BI Dashboard - Dataverse connector - July](https://github.com/microsoft/coe-starter-kit/raw/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Dataverse_CoEDashboard_202107.pbit)

If you are not sure what version to pick we have some guidance on [which dashboard to pick](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#which-dashboard-to-use). 

Thank you
Manuela

**Comment by aakashpatel660** [comment]
Hi Manuela,

I have core 2.1 installed. Let me try the new Power BI dashboard and I will update you.


Best Regards,
Akash Patel

**Comment by aakashpatel660** [comment]
Hi @manuelap-msft 

I downloaded the CDS Legacy file because I have a production environment created. When I open the file and provide a URL that I receive an error message. 

![image](https://user-images.githubusercontent.com/59940632/123964343-53827800-d981-11eb-95dc-cc583cefff48.png)

**Comment by manuelap-msft** [comment]
Hello,

I think something is blocking the dashboard from connecting to the Dataverse tables. Do you have Admin mode enabled on the environment? Do you know if you're using encryption on the environment?

Here's some info on those two things
https://docs.microsoft.com/en-us/power-platform/admin/manage-encryption-key
https://docs.microsoft.com/en-us/power-platform/admin/admin-mode

Thank you
Manuela

**Comment by aakashpatel660** [comment]
Hi @manuelap-msft , 

Administrator mode is disabled. 

Currently, I am using the June Power BI version and I am able to pull the data then is there any difference in the configuration on June and July dashboard?

**Comment by manuelap-msft** [comment]
Hello,

sorry, I think I'm confused now - when you raised the issue, was that for the June dashboard and is it working now or are you still having the issue?

admin_containpasswordvalidation is not a column that we have as part of the CoE, that should not exist. The columns in the other screenshot do exist.

You can use both against a Production environment, but the Dataverse connector requires certain ports and the TDS endpoint to be enabled. We have seen some customers struggle with this as their network policies didn't allow the connection. But you can try both!

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Closing issues as no further action on the CoE team required.
