### ISSUE TITLE
[ALM Accelerator - Ques/BUG]: ALM Accelerator issue is not pushing solution in downstream environments (Validation /UAT / Prod)

### ISSUE THREAD

**Issue by jhasaroj** [microsoft/coe-starter-kit#7092]
### Describe the issue

Facing Issue in ALM Accelerator : 
Commit Solution  is pushing the solution ,as unpacked code base  Azure DevOps git repo. (Pipeline invoked : "export_solution_to_git")
Also Deploy Solution is creating a pull request for approval . (Pipeline invoked : None)
But its not moving the managed solution into downstream environments. (Validation / UAT / Prod).
Specifically no associated yml pipeline is called. Not sure what I am missing over here.
Its not throwing any error(s) or exception message.
Only yml pipeline called is "export_solution_to_git" . How to invoke other pipelines and associated variables and json files configuration for deploying solution to target environments.  (Validation / UAT / Prod)

### Expected Behavior

Commit Solution / Deploy Solution shall call specific pipelines based on template to deploy Power Apps / Flow based solution into downstream environments.
Not sure which specific steps needs to be configured. Also is it for solution specific or generic for all solutions.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20230906.1

### Steps To Reproduce

1. Accelerator Version: 1.0.20230906.1(Managed) 
2. Create a simple sample solution in power apps / power automate .
3. Set up ALM accelerator using ALM accelerator Power Platform Admin .
4. Configure User settings and User Profile. Setup Validations and UAT and Prod environment details.

AB#842

**Comment by RajeevPentyala** [comment]
@jhasaroj Please refer the steps detailed here #7057 to trigger the deployments.

**Comment by RajeevPentyala** [comment]
@jhasaroj As mentioned in my previous comment, kindly review the detailed explanation on how to trigger the deployment pipelines [here](https://github.com/microsoft/coe-starter-kit/issues/7057#issuecomment-1807753131) and let me know if any further queries.

**Comment by jhasaroj** [comment]
Thanks for the pointer Rajeev. But still can't make this work. 
Please find screen shorts for the same. Could you please point me which action activities, I might be missing.
I am new to DevOps / Pipelines.
![Deployment profile](https://github.com/microsoft/coe-starter-kit/assets/150776931/fc71b90a-cb26-42f7-85b2-77dac25a589d)
![DeploySol](https://github.com/microsoft/coe-starter-kit/assets/150776931/7f4592eb-db6d-4837-b008-4bedf331c2ab)
Even after pull request approval and marking it as complete no Pipeline is triggered.
Although I can see yml files being generated at both .
Could you please help be decipher this.
Except "Deploy Sol" all actions "Commit" ,"Delete Sol" & "Import"... All are working fine.

**Comment by jhasaroj** [comment]
![yml files at repo](https://github.com/microsoft/coe-starter-kit/assets/150776931/e4bb3bd8-e8c2-4b45-8e8a-0b27820d30e0)

**Comment by RickyTaneja12** [comment]
Hey @jhasaroj , wondering if this issue got solved?
Facing the same problem. Everything else works apart from actual deployment
