### ISSUE TITLE
[CoE Starter Kit - BUG] Admin person - configure group does not find all groups in tenant and button do not work

### ISSUE THREAD

**Issue by tomka75** [microsoft/coe-starter-kit#7094]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Installing Core Module 4.17. In the setup wizard when configuring the communication methods the dialog comes, but under find items not all groups are listed (tenant with a lot of groups). Entering a Group eMail address manually, the buttons "Cancel" and "Select group" are not working. For makers and user we edited the env. variables manuelly, this was than shown in this step, but what is the now of the admin persona env. variable?
![image](https://github.com/microsoft/coe-starter-kit/assets/32197566/b2a80257-81d0-4ef7-a853-20abd854c9e7)

### Expected Behavior

Searching for groups displays the existing group in tenant or entering the eMail allows to press "Select group" and recognizes the step in the wizzard.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Setup Wizzard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

- Install 4.17
- Open Setup Wizzard
- Press "Configure group" in the "Configure communication methods" step.
- Try find items or enter a Group email address manually, button do not work

No env. variable found for Admin persona eMail.

AB#844

**Comment by Jenefer-Monroe** [comment]
Its the admin email env var that is filled.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a431a337-2709-43ed-9939-84324678ce5e)

I dont repro this issue though. Can you plesae tell me, are you entering the email address of a group or an individual?

**Comment by Ronayne94** [comment]
I am experiencing the same issue, currently. Button unclickable, unable to configure MS365 groups via setup wizard.

![image](https://github.com/microsoft/coe-starter-kit/assets/110245654/3a01a9bb-ed30-4790-94d4-cce7b69f7a1f)

**Comment by Jenefer-Monroe** [comment]
Perhaps its because you have a value both in the drop down and the text field. Can you see if it works when you only have one of those filled?

**Comment by tomka75** [comment]
I am entering an M365 group email address, not the ID for the admin persona. Needed to fill the env. variable manually, because a flow does not turn on when the variable is not set. And also it does not matter if only one or both fields are filled, buttons do not work. Currently only the manual configuration of the variables work with the hint, admin is email, makers and users are IDs.

**Comment by Jenefer-Monroe** [comment]
@RahulBojji can you see if you can get a repro of this? I cannot repro.

**Comment by RahulBojji** [comment]
Before Configuring Communication Methods
<img width="932" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/7c7320ff-58d8-4990-bb4d-468f5d6a8f13">

Now Configuring Admin Persona, added email in text box and selected the M365 group from the dropdown. For me both "Cancel" and "Select Group" buttons are clickable.

<img width="923" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/d4a6797e-0fff-4ff6-8331-6ce9fd911066">

On click of Configure Group, 

<img width="932" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/35afc72f-c9c9-482f-afbc-5fce95acb3ff">

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
