### ISSUE TITLE
COE flows failing 

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#7095]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have an issue like so many of my flows in COE are failing.

This started in last week as observed there the secret key was about to expire and our Azure team has provided a new Azure secret key. 

We saw that there were some flows failing and then we have replaced the secret key with the new one.

Not sure what had happened, now all the flows are failing. 

Help me on this,

Adding the screenshots for reference:

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/eaec78ee-ac18-4502-a536-dd54c0996725)

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/70e29e33-3efd-421d-addb-b8faf8d7912a)

When I see the flow detials which got failed I see the below error:

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/699873aa-6e8b-41d6-ad5f-c130e612f013)

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/2622e0e2-750c-496d-978b-3f745401cfe2)

The error message as : The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'Required properties are missing from object: boolean.'.

### Expected Behavior

Flows should not fail after replacing the client secret.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

None

AB#845

**Comment by Neel1KNK** [comment]
Hello Shrikanth,
You were correct there is an issue with the inventory flow. The flow is turned ON but its getting failed and I see the error saying that there is an error in Trigger.
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/2bae1ca5-97f7-47d5-aa51-bbb8bc27c0aa)

 
All my connections seem to be good. But there is a issue with the trigger. We have our COE set up wizard running, and we are actively using that to check the status of the flows.

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/980b0b8c-e3be-4cb0-b7c0-b23e50320d9a)

 
I see both the Sync Helper (Cloud flows, Apps) both flows are failing and getting below error:
{
  "type": "object",
  "properties": {
    "text": {
      "title": "envtid",
      "type": "string",
      "x-ms-dynamically-added": true,
      "description": "Please enter your input",
      "x-ms-content-hint": "TEXT"
    },
    "text_1": {
      "title": "envtName",
      "type": "string",
      "x-ms-dynamically-added": true,
      "description": "Please enter your input",
      "x-ms-content-hint": "TEXT"
    },
    "text_2": {
      "title": "flowid",
      "type": "string",
      "x-ms-dynamically-added": true,
      "description": "Please enter your input",
      "x-ms-content-hint": "TEXT"
    },
    "boolean": {
      "title": "isBYODL",
      "type": "boolean",
      "x-ms-dynamically-added": true,
      "description": "Please select yes or no",
      "x-ms-content-hint": "BOOLEAN"
    }
  },
  "required": [
    "text",
    "text_1",
    "text_2",
    "boolean"
  ]
}


Tried to check but couldn't find anything on this. Please help on this,

**Comment by shrikant-singh31** [comment]
1. Can you please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and confirm that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)
2. Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by Neel1KNK** [comment]
1:  ![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/bc8f6bb4-be57-4718-8217-8ab17fab755c)

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/c9ff1286-1a7f-4827-b981-0a92d11fb22e)

We have totally 3 flows failing in the COE and there are 5 flows with the managed layers in it.

2: We have only Core solution installed in our environment; we don't have installed any other solutions. This COE kit is running successfully from past 1-2 years with only Core solutions installed in it.

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/c478d7d2-6214-4899-aa9f-25b21a74ec70)

We need to figure out why the flows are failing. We have replaced the secret key which got expired in last week and then the problem started.

**Comment by Jenefer-Monroe** [comment]
These flows do not use anything that involves a secret so unless I'm missing something I don't think these are related occurrences.

You have removed all the unmanaged layers now correct? I do see you had some for the 2 flows you posted about originally

- Admin | Sync Template v4 (Apps)
- Admin | Sync Template v4 (Flows)

Can you please also manually check for unmanaged layers on the two helpers?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c61f595a-0309-4e28-8f96-3845538f4ef3)

Then lets see if these two flows still fail after all the unmanaged layers are removed

**Comment by Neel1KNK** [comment]
Hello
I have removed all unmanaged layers on the flows and most of the flows are running successfully. But I have one flow which are still failing. By fixing the unmanaged layers all the flows got fixed. Thanks for that catch.
 
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/e6d63f17-84bd-4c95-a9c8-2d88ab47a7ec)

This time I have double checked manually and confirming that there no unmanaged layers in the flows. Only this flow is failing.

**Comment by Jenefer-Monroe** [comment]
Thank you can you please post a new issue for this? Please include screenshots of teh flow itself's failure.

The original bug you posted is resolved by
1. removing unmanaged layers
2. turning on child flows

So this one will be a different issue and a different fix.

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this one out then, thanks for using CoE
