### ISSUE TITLE
[ALM Accelerator - QUESTION] How to use the sync-pipeline-repo

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#7096]
### What is your question?

Hello,

I'm following this documentation: https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-pipeline-sync#pipeline-sync-setup.

I want to understand what the exact steps we need to perform in Azure DevOps to update the templates correctly.
It's just a matter of running the sync-pipeline-repo? What should we add in the options that are displayed after we click on 'run pipeline'?

![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/9be9fc84-f2b4-4bb0-845b-15ce1409c27e)

Thanks very much for clarifying!

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

November 2023

AB#846

**Comment by RajeevPentyala** [comment]
@LucX4 Use the following parameters when running the 'sync-pipeline-repo' pipeline.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/196c2172-3d28-4e4b-8f9a-4cfd60677692)

- Selecting 'SyncFrom = Tag' allows you to choose the latest 'ALM Accelerator' build based on the 'Tag'.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/344d28e9-9cf7-4d23-bcce-cc7f6ab5b51f)

- Enabling 'AutoCompletePR = true' will download the latest 'ALM Accelerator' build into the interim branch and automatically merge it into the 'Main' branch.

Feel free to reach out if you have any further queries.

**Comment by LucX4** [comment]
Hello @RajeevPentyala, 
Thanks very much!
