### ISSUE TITLE
[CoE Starter Kit - QUESTION] what flow updates the 'App Shared with' 

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#7097]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi
Sorry if this question has already been asked, I am looking to know what flow updates the 'App Shared with' when I look on the Power Platform Admin view then select shared, with this shows at the bottom with the total shared and last updated.
I have looked at the CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) and CLEANUP HELPER - Power Apps User Shared With but as these only run every 2 weeks I am no understanding how this is updated daily.
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/a15239b8-a83c-4c64-ba26-12fbd7e445f1)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Unsure which flow

### What method are you using to get inventory and telemetry?

Cloud flows

AB#847

**Comment by v-bjaiswal** [comment]
It had been updated by below flow. "DLP Request | Sync Shared Policies" which runs daily.

![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/2560a019-2db0-4820-b143-399fd349135e)

**Comment by Alyson95170** [comment]
Thanks for your response, this is not a flow we have turned on within our tenant, is there another flow that updates this record?

**Comment by v-bjaiswal** [comment]
This field is getting updated by the automated calculation based on the formula given. We called this as "Rollup Fields".
You can get more info on it from here, (https://learn.microsoft.com/en-us/dynamics365/customerengagement/on-premises/customize/define-rollup-fields?view=op-9-1)

![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/a877a3e8-fb29-4824-bb6e-ba19950ea514)

for the above field, the formula is basically to take the aggravated value of group size.
![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/1f63636b-e773-420e-9a2c-d1d8be6a2fb1)

and you are correct that the CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) flow is the one that fills the field being aggregated.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
