### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs - Client Azure Secret (Environment Variable)

### ISSUE THREAD

**Issue by johnravas** [microsoft/coe-starter-kit#7098]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have just upgraded from the May edition to the August edition.  I am trying to switch to the HTTP  method of getting log data.  When I attempt to set the environment variable for the Client Azure Secret, I get this error: This variable didn't save properly. User is not authorized to read secrets from <path to the key vault resource>

Per reading other bug reports, I have confirmed that the key vault is using RBAC - 
![image](https://github.com/microsoft/coe-starter-kit/assets/59970962/99f977e3-0d26-4fb0-8e0e-87d97175059e)
 
and the service account we are using for the CoE has the appropriate roles:
![image](https://github.com/microsoft/coe-starter-kit/assets/59970962/b7125256-4c05-4f4b-ad62-62e80935f9d2)

This bug report seems to claim that this will be fixed with the October edition - https://github.com/microsoft/coe-starter-kit/issues/6473 - I was under the impression that the August edition might fix this from other reading.  Can someone help me to understand if and why the October edition will fix this issue?

### Expected Behavior

Be able to set the Audit Logs - Client Azure Secret environment variable to the information from the key vault

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13 - August

### What app or flow are you having the issue with?

Process to set the environment variable

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Launch the CoE Admin Center app
2. Click on the Environment Variables option
3. Edit the Audit Logs - Client Azure Secret variable
4. Follow one of the Click here to edit options
5. In the Environment Variable screen, click on the variable
6. Use the + New Azure Key Vault Secret Reference option
7. Fill in the properties and save

AB#848

**Comment by Jenefer-Monroe** [comment]
The issue you are seeing is in the product itself and not the kit, so no updates from the kit woudl fix. 
The bug you reference was a documentation bug so we just updated notes about the product behavior.

**Comment by johnravas** [comment]
@Jenefer-Monroe are you referring to this documentation - https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#update-environment-variables ??  I tried to set this in the Default solution with the exact same result?  Am I missing something?

**Comment by Jenefer-Monroe** [comment]
Yes you have to go to the Default Solution to set Env Vars. 

It should look like this with a GUID for the subscription id and string names for everything else
Is that what yours shows? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/748673b2-be4e-4d62-8ff4-4444c6b22f3a)

This is just a product feature and our testing indicates that those are the permissions needed. 
I do know that this takes a very long time to propagate so if you just gotten those permissions you may need to wait.

**Comment by Jenefer-Monroe** [comment]
OK im afraid you've hit a product issue here then, this isnt our ux, but just product ux. 
You will need to contact product support to find out why you arent able to update this environment variable. 
Please do let us know if you learn something that we can use to benefit other users.
