### ISSUE TITLE
[CoE Starter Kit]: Charts in Power Platform Admin View - App empty

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#710]
Hello all, 

I installed the Starterkit in an production environment. 
The charts in the Power Platform Admin View app does not contain the sum of apps and flows (=0).
The rest is working and showing the apps and flows in the tables correctly.

 - Solution: Core
 - Version 2_1_70
 - App: Power Platform Admin View

![image](https://user-images.githubusercontent.com/62603605/123933001-41f59c00-d992-11eb-87f0-511db49fd30e.png)
![image](https://user-images.githubusercontent.com/62603605/123937700-b92d2f00-d996-11eb-8187-e8820f9f322f.png)

It woukd be great to get some help on how to solve the problem.

Best regards
Catherine

**Comment by manuelap-msft** [comment]
Hello,

Have you followed the steps to [activate the sync template flows](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows), and have you [waited for them to finish running](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#wait-for-flows-to-finish)?

Thank you
Manuela

**Comment by Cathi029** [comment]
Hello Manuela, 

thanks for your reply. Yes, I followed the instructions, and the tables are not empty.

Best regards Catherine

**Comment by manuelap-msft** [comment]
Hello,

so you can see information in the tables (under Power Apps and Flow) but not in the Dashboard? Did you install the kit just today? The dashboard is using calculated columns which take 24 hours to refresh. 

Thank you
Manuela

**Comment by Cathi029** [comment]
Hello Manuele, 

yes I installed it today. This is my view of the Dashboard:
![image](https://user-images.githubusercontent.com/62603605/123941426-6eadb180-d99a-11eb-914a-6be2a24c0d3e.png)

I installed the Kit a few weeks ago in another tenant and I didn´t have this issue.

Thank you
Catherine

**Comment by Cathi029** [comment]
You are right, I refreshed the data and the problem was solved. Thank you very much!

**Comment by manuelap-msft** [comment]
Thanks for confirming and using the CoE, Manuela
