### ISSUE TITLE
[ALM Accelerator - Feature]: Environment variables for BYODL dataflow slugs

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#7101]
### Describe the solution you'd like

In the current form of the kit, when BYODL is used, each Dataflow has to be edited with each update to the kit to rekey the Environment API and the Data Lake URL info that is the same on every one of them.  If an environment variable could store each of those data points for the environment and then just use that within all the Dataflows, each update would take significantly less effort (and time).

### Describe alternatives you've considered

Storing the info in Azure Key Vault could work also, just isn't as clean as environment variables.

AB#852

**Comment by Jenefer-Monroe** [comment]
Hello. Dataflows don't work with environment variables and connection references yet. 

Even if we stored a value in the Environment Variable, then we'd have to bring the env var table into the dataflow and you'd have to authenticate against that first. 

You also have to authenticate against each folder not just top level (so you auth for the applications folder, the environment folder, the usage folder) so it wouldn't be possible to make that easier by using environment variables unless I'm missing something. 

There is an effort by the product team to bring this in but until then I'm afraid we can't make this setup process easier.

**Comment by bartsneary** [comment]
Yeah, this was another one more for logging to give you ammo to push on the product teams to make something better in the core products...

***@***.***
Bart Sneary
MTC Architect | 952-837-4560 W or 507-403-3088 M
***@***.******@***.***>
3601 West 76th St, Suite 600, Edina, MN 55435 | www.microsoft.com/mtc<http://www.microsoft.com/mtc>
***@***.***

**Comment by Jenefer-Monroe** [comment]
Oh I see, thank you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
