### ISSUE TITLE
[CoE Starter Kit - BUG] Some components of this app require you to sign in to continue

### ISSUE THREAD

**Issue by kartrabby** [microsoft/coe-starter-kit#7102]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Team, after the issue we had as per https://github.com/microsoft/coe-starter-kit/issues/7050 ........

I managed to successfully import the Solution, but now I am facing this issue whenever I open any app that is installed as part of the solution!

Nothing works when I click on **sign-in** !

![image](https://github.com/microsoft/coe-starter-kit/assets/95188375/a0d3489d-dba4-4179-8ce3-5c8f78af4c2f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

All App in the Core Components

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

I just managed to import the solution after we the "Sorry there's been a disconnect" issue.

Now after successful import, if I launch any application from CoE Solution, it is showing "Some components of this app require you to sign in to continue"

**Comment by manuelap-msft** [comment]
What browser are you using? Can you try using Edge? This seems to be a browser / connection issue, rather than anything related to the CoE kit.

**Comment by kartrabby** [comment]
@manuelap-msft : It's working in Edge in (Incognito Browser). Thank you.

I might need to figure out, why it doesn't work in Firefox.

**Comment by Jenefer-Monroe** [comment]
Did you install with the "classic upgrade" workaround or the query parameter workaround? 
If the former, its likely that your connections did not get correctly setup. 
Can you look at Connection References in the Default Solution, open each one and make sure its resolving to you
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2269ba06-2901-43d3-9986-6771f072a1d3)

**Comment by DrFdisk** [comment]
I suddenly have the same effect when starting the CoE Admin Center.
I'm still on version 4.15 of Core Components, and did nor üpdate anyting.
![2023-11-17 16_10_45-CoE Admin Command Center](https://github.com/microsoft/coe-starter-kit/assets/76172630/843934b0-9335-4513-b983-2a4311d3be51)

All Connection References in the Default Solution are resolving to my account.

**Comment by Jenefer-Monroe** [comment]
There seems to be some kind of product issue impacting you, we dont repro. 

Can you please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/

Can you try different browsers? It sounds like the issue might be browser specific from the above.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
