### ISSUE TITLE
CoE Setup and Upgrade Wizard Error after update

### ISSUE THREAD

**Issue by D3L05** [microsoft/coe-starter-kit#7104]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

After updating to the last release I'm receiving this error when trying to play the app CoE Setup and Upgrade Wizard, also receiving errors in other apps.

Error Code: AppForbidden
Session Id: 1f482dfa-712f-4c04-a09c-b7bcfbd15779
Activity Id: 656621cd-2d77-4603-b5ff-eab6f89475ad
Timestamp: Wed Nov 15 2023 07:38:52 GMT-0300 (Argentina Standard Time)
{"error":{"code":"Forbidden","message":"The user with object id 'bc112cfd-4d37-44f8-9ee6-516bb86b8394' does not have permission to access this.","details":[{"code":"PowerAppsNoAccess","message":"The user does not have access to the app."}]}}
UciError: {"error":{"code":"Forbidden","message":"The user with object id 'bc112cfd-4d37-44f8-9ee6-516bb86b8394' does not have permission to access this."....

the user its a sys admin and its the same user used to import the solution.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

AB#856

**Comment by Jenefer-Monroe** [comment]
Were you impacted by the "Sorry, there's been a disconnect" bug from https://github.com/microsoft/coe-starter-kit/issues/7050 and if so did you do one of the workarounds to install?

**Comment by D3L05** [comment]
> Were you impacted by the "Sorry, there's been a disconnect" bug from #7050 and if so did you do one of the workarounds to install?

I received some errors but after a few tries I was able to import the solution

![image](https://github.com/microsoft/coe-starter-kit/assets/62146775/cf1a3e44-c7a6-4a78-af5a-48c764168477)

**Comment by Jenefer-Monroe** [comment]
ok so you installed with the regular ux, you did not do one of the workarounds in that bug?

**Comment by D3L05** [comment]
> ok so you installed with the regular ux, you did not do one of the workarounds in that bug?

no, i just repeated the same process

**Comment by Jenefer-Monroe** [comment]
Can you load any of the apps in the solution? For example the Coe Admin Command Center

**Comment by RahulBojji** [comment]
@D3L05 Can you please let us know if you are still facing this issue. Couple of days back there was a global outage of PowerApps, we are assuming this might be because of that. 
Can you please check at your end and confirm us if you are still facing this issue.

**Comment by D3L05** [comment]
> @D3L05 Can you please let us know if you are still facing this issue. Couple of days back there was a global outage of PowerApps, we are assuming this might be because of that. Can you please check at your end and confirm us if you are still facing this issue.

@RahulBojji, yes still the same error
![image](https://github.com/microsoft/coe-starter-kit/assets/62146775/a8654280-95ef-4e4e-83a8-e002cfc6a643)

**Comment by Jenefer-Monroe** [comment]
Are you logged in as the user that installed the kit? If not then the app does need shared with you.

**Comment by D3L05** [comment]
> Are you logged in as the user that installed the kit? If not then the app does need shared with you.

yes, I'm using the same user I used to import the solution

**Comment by Jenefer-Monroe** [comment]
Is there any more detail here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/905548ef-44e8-4c1f-b4ca-1b77f8bf272a)

Go look at who the app is shared with, do you see your identity there?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/87af3337-b037-402f-9532-c820f8b4866d)

Go double check your identity in the envt, are you still listed as sys admin? Do they show as enabled?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/341c5876-0b78-4003-87d4-cf8c13a8fa1b)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
