### ISSUE TITLE
[ALM Accelerator - Feature]: Feature to manage version number of the solution being deployed

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/coe-starter-kit#7105]
### Is your feature request related to a problem? Please describe.

Hi Team,

Could you please look into the possibility of specifying the version number of the solution being deployed.

As there could be scenarios where the managed solution with a higher version already existing in target environments (where the ALM was not used previously), it would be of great help if we could manage the version number at the time of deployment, for example through Deployment Settings screen.

Thanks,
Tom

### Describe the solution you'd like

For example, currently the ALM Accelerator deploys the solution with versioning in the format 1.0.Date.Attempt. 

If we could handle this versioning from Deployment Settings screen or by some other means, it could help us a lot.

AB#857

**Comment by RajeevPentyala** [comment]
@tomjosbin If you prefer not to use the 'ALM Accelerator' versioning pattern, you can set the variable 'skipSolutionVersioning' to true in the Deployment pipelines. This ensures that 'ALM Accelerator' will not override the original solution version during deployments.

**Comment by RajeevPentyala** [comment]
@tomjosbin Closing this issue as there is no further action needed. Please feel free to reach out if you require further assistance.

**Comment by iamaninda93** [comment]
@RajeevPentyala Can you clarify in which file I need to change the settings? Could you specify the yml file name?
