### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot save support details in DCC

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#7106]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When entering details in the support section of the Developer Compliance Center (DCC), the Save and Cancel buttons do not work i.e. nothing happens when they are clicked. 
This occurs for both admin accounts and Makers with the SR role.
Also, there's a message about a new version being available that won't go away.

(I reinstalled CoE on to my environment after resetting it and used the classic UI to import it due to this issue, so don't know if it's related https://github.com/microsoft/coe-starter-kit/issues/7050#issuecomment-1805699562 )

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/c8effaef-22ff-439e-a398-f74afe8a43ec)

I'm using the latest version of CreatorKit.

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/8003736a-39b6-4aac-a875-4feef684e259)

### Expected Behavior

When opening the DCC, clicking on an app and then clicking Support Details, I should be able to enter details and click Save to update them. Also, the Cancel button should close the support details window.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

DCC

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the DCC
Click on an App
Click on Support Details
Enter details into a text field
Click Save or Cancel (nothing happens)

AB#858

**Comment by Jenefer-Monroe** [comment]
Can you plesae check to see if you ended up with unmanaged layers when you were trying to edit the app? 
@RahulBojji to assist here

**Comment by MartinWGT** [comment]
I already thought about that :-) 
Here's what I see...

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/cdac5114-27f9-45a1-b1ce-4a87061a31dc)

**Comment by RahulBojji** [comment]
@MartinWGT, i have upgraded my solutions to novemeber release

<img width="824" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/5dd044f5-da76-401e-9025-bf832ecb8521">

 I have tried initially with both Powerplatform admin SR and Maker SR roles 
I wasnt able to repro it  and then i tried with maker SR separately and admin SR but i couldnt repro it. Attached the recording for reference
![Developer Compliance Center Canvas App page - Power Apps and 2 more pages -  InPrivate  - Microsoft_ Edge Beta 2023-11-16 13-33-53](https://github.com/microsoft/coe-starter-kit/assets/149372606/d3d74964-2945-4440-a73a-1005245735f1)

**Comment by MartinWGT** [comment]
Hi @RahulBojji Thanks for trying to replicate. Which version of CreatorKit are you using?

**Comment by MartinWGT** [comment]
And "as if by magic" as we say in the UK - today it is working fine. In fact the related issue where the attachment wasn't saving, is also working now (and you commented that you were able to repo the issue!) - https://github.com/microsoft/coe-starter-kit/issues/7056#issuecomment-1812556861

One thing that looks different, is the message "A new version of this app is available, please refresh to update" has finally gone away. 
![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/70e5ca96-ddfd-4702-94d9-b9e725376e6d)

**Comment by Jenefer-Monroe** [comment]
Thanks @RahulBojji and @MartinWGT for working together to find the magic!
closing out as no further action for starter kit team.
