### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to track progress of the Orphans Process

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#7107]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,

Is there any way for us to track the progress of the Orphans Process?
I created a view in the Admin View, and we can see the total numbers. However, I'm looking for more granular insights. 
For example: how many managers have deleted the components? How many components have been assigned to a different person? How many managers have assigned components to themselves? 

Thanks for your support!

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

November 2023

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#860

**Comment by Jenefer-Monroe** [comment]
We do not have this but we did just in the Nov release add a date to show when the Maker was marked orphan. So you can at least know how long its been sitting that way.
https://github.com/microsoft/coe-starter-kit/issues/6966

**Comment by LucX4** [comment]
Hi @Jenefer-Monroe,
Ok, thank you!
