### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Core Components Import 

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#7108]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team, 

While deploying the November Core Component zip file, here is an error I have received. What does it mean by "ImportAsHolding failed." 

<img width="621" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/100535041/80873f9a-dee7-4888-a47d-de36a8f483a0">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoreComponents

### What method are you using to get inventory and telemetry?

None

AB#861

**Comment by v-bjaiswal** [comment]
This usually happen when there is a solution upgrade error happen and we end up with 2 solutions, one is the actual solution and other is with "_upgrade" attach in it name. 

Please check the solution list in your environment if you are able to see multiple "Center of Excellence - core component" solution like below.  if yes then try to delete the upgrade solution first.

![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/13fd1453-3b79-4325-9a93-937e0f599ec5)

or check the below issue that got raised and see if you are able to resolve the issue.

https://github.com/microsoft/coe-starter-kit/issues/6018

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by iamjina** [comment]
Hi Jenefer, 

We did remove the CenterofExcellenceCoreComponents_Upgrade and re-imported; however, still showing a failure. It looks like it's got to do with Office 365 Management API? Do we have an known issue around this? 

![image](https://github.com/microsoft/coe-starter-kit/assets/100535041/56a93399-b97c-4d3a-9b8a-3e911b53b3e4)
