### ISSUE TITLE
[CoE Starter Kit - QUESTION] Plans for the January release: Answer: Skipping it

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7109]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Last year due to the holidays, the January release was skipped. Will there be a break in the release plan between Dec-Feb?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#862

**Comment by Jenefer-Monroe** [comment]
Thank you for asking. We will be skipping the Jan release. Happy holidays!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
