### ISSUE TITLE
[CoE Starter Kit - QUESTION] What does it mean if an app is named {GUID} forms

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7110]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Within the CoE dashboard, when analyzing Apps that are currently in flight within our tenant. There is multiple "Apps" that have this alpha-numeric nomenclature ex. "ab98745-f456-4a78-9sdf-34456967aa86 forms". Do you know what would cause this and why the proper App display name is not being retrieved?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#863

**Comment by RahulBojji** [comment]
we've seen this before and believe it had to do with SP Forms that were in a strange state, if this is your bug, please hop on and help us debug.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
