### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Request management - unable to proceed

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7111]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Environment request has been moved to "CoE Maker Command Center". Is it just me, or can nobody proceed, an delete added connectors?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#864

**Comment by manuelap-msft** [comment]
Likely related to https://github.com/microsoft/coe-starter-kit/issues/6815 which was fixed with the November release

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
