### ISSUE TITLE
[CoE Starter Kit - QUESTION] AI Builder consumption report

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7112]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I wasn't also able to look at AI Builder credit consumption in the CoE BI report, is it on me or not an provided information ? Is it planned to be added ?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#865

**Comment by Jenefer-Monroe** [comment]
Hello, this is tracked by the following feature request: https://github.com/microsoft/coe-starter-kit/issues/6100

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
