### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Apps status

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7116]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a plan to release a Status for Power Apps, such as Active/Inactive?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#869

**Comment by Jenefer-Monroe** [comment]
I believe you mean to flag an app as active or not wrt number of launches. No we do not plan to store that separate boolean as its varied what people think of as active.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
