### ISSUE TITLE
[CoE Starter Kit - QUESTION] permissions are required to pull the personal productivity in to the CoE admin view

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7117]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

what permissions are required to pull the personal productivity in to the CoE admin view?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#870

**Comment by Jenefer-Monroe** [comment]
You will get all environments to which you have sys admin access into the inventory system.
And if you have the Power Platform Admin Role permanently and directly assigned, you will get all environments.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
