### ISSUE TITLE
[CoE Starter Kit - QUESTION] model driven app usage

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7118]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way (connector actions/ PS cmdlets )to retrieve more information for model driven apps. Such as launch details, shares as there is for canvas app. Need this to make sure the MD app is still being used.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#871

**Comment by Jenefer-Monroe** [comment]
We do not have a way to gather these programatically at this time unfortunately.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
