### ISSUE TITLE
[CoE Starter Kit - QUESTION] license requirements for admin_AdminMail 

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7120]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

For the environment varaibles admin_AdminMail and admin_ApprovalAdmin. Is there any license or permissions requirements associated to them?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#873

**Comment by Jenefer-Monroe** [comment]
Hello. Requirements for these groups is outlined here: [How will you communicate with your admins, makers, and users?](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5704214e-cefc-4939-a9c8-a8b17d4bf00a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
