### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there a way to see what flows/apps have been deleted?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7121]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way to see what flows/apps have been deleted?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#874

**Comment by Jenefer-Monroe** [comment]
There is an environment variable called Also Delete from CoE. It governs if objects deleted in the tenant are also deleted from the CoE, or just marked as deleted. 

By default it is set to yes, so objects are removed from inventory when they are deleted from the tenant, but you can change this default to no, and then they would just be marked deleted.

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/807ee8d1-ccec-45b1-bf98-24789b4ccccb)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
