### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can the admin email be a distribution list or shared mailbox? I recall one environment variable for this asking for individual user.

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7122]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can the admin email be a distribution list or shared mailbox? I recall one environment variable for this asking for individual user.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#875

**Comment by Jenefer-Monroe** [comment]
Yes it can. Here are the requirements for it, as well as the comment on the "Individual Admin" user 

[How will you communicate with your admins, makers, and users?](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users)



![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b5b56c8c-3241-4757-8dea-8684c895f15e)

**Comment by Jenefer-Monroe** [comment]
You may not be able to perform some of the actions like reassigning orphans that come to you in teams since you don't have PPAdmin Role.
But you would get the list in teams, and be able to log in as the super user and do the things from the other UX points instead. 

Hope that makes sense

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
