### ISSUE TITLE
[CoE Starter Kit - QUESTION] more information in compliance center

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7123]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the compliance center could you give further information of the support details (f.e. what is meant by access management), as it's hard for a maker to know what to answer in the different sections

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#876

**Comment by Jenefer-Monroe** [comment]
Here is a detailed description of our Compliance (aka audit) processes

https://learn.microsoft.com/power-platform/guidance/coe/example-processes
