### ISSUE TITLE
Admin | Add Maker to Group fails with "Insufficient privileges to complete the operation."

### ISSUE THREAD

**Issue by MshulerIWT** [microsoft/coe-starter-kit#7138]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Since installing CoE, the "Admin | Add Maker to Group" Flow has been failing with the Error of "Insufficient privileges to complete the operation."

Our CoE service account is set as the owner of the group and is a Power Platform Admin.
Does the account need any special permission to edit the group?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Admin | Add Maker to Group

### What method are you using to get inventory and telemetry?

Cloud flows

AB#906

**Comment by Jenefer-Monroe** [comment]
It should not need anything besides being an owner of the group. I've never reprod this but I have seen it posted once before so we might be missing something. 
Can you please give us some more details on what the user type that is running the flow? And perhaps some information about the group type? 
Then one of us can try to repro with your specifics.

**Comment by MshulerIWT** [comment]
Would it be an issue that the mail enabled security group was created in Exchange on-prem and synchronized to O365?
It is available to view and accepts email, however even though the service account is the owner, it cannot modify membership.

The CoE service account has the following:
- Office365 F1
- Power Platform Administrator.
- Power Apps per user license.
- Power Automate per user license.
- Permission to read the M365 audit log.

**Comment by Jenefer-Monroe** [comment]
Oh yes, that likely is it. Thank you for raising that detail I never would have thought to ask that.
I'm afraid this is just a limitation we should document.

**Comment by Jenefer-Monroe** [comment]
- must be an email-enabled security group
- admin or service account setting up the [inventory components](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components) needs to be an owner of the group.
- cannot be a group created in Exchange on-prem and synchronized to O365

**Comment by ajdepoti** [comment]
we are seeing the same issue and it is an m365 group.

**Comment by SPMush** [comment]
> we are seeing the same issue and it the owner of an m365 group, not a group created on-prem and synced to m365.

Also have this issue , Mail enabled SG, Service Acc is owner, and was not created on Prem.

**Comment by JulesCam** [comment]
Just wanted to check that we don't need to assign any additional licenses to the security group, like E5?

**Comment by Jenefer-Monroe** [comment]
This issue has to do with the ability to add users to group through the office 365 groups connector. 
So with regards to that issue, no you would not need to any licenses on this group.

**Comment by tbartlett17** [comment]
Can I get clarification on the documentation for the personas for communication with admins, makers, users?

![Screenshot_20240605-122838](https://github.com/microsoft/coe-starter-kit/assets/36083073/4d30a219-4e01-4433-b346-34bf2d3b22c3)

It states "This group type is an email-enabled security group"

Should this be normal 365 group created through Azure AD/Entra? 

We created "Mail-enabled security groups", I believe through exchange admin center. The flow errors out with "cannot update a mail-enabled security groups and or distribution list".

**Comment by Jenefer-Monroe** [comment]
The requirements are those of the connector itself. We have seen it fail for people who create them in exchange. 
I'm afraid there is a bunch of complexity here around the connector and the miriad group options that we just cannot fully understand and explain as we are not funded for that level of product support (its just me for all 12k installs of the kit). 

So the recommendation is to use M365 groups. And other group types might also work. But it certainly needs to be email enabled as well as be able to be used as a security group.
