### ISSUE TITLE
[CoE Starter Kit - QUESTION] Has anyone seen where a Managed Environment that has a security group where the Service Admin is not added

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#7139]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

So I noticed when testing with the CoE Tool Kit, that we have managed environments with security groups where the service admin is not apart when going to Power Platform Service Admin view and go the environment and click on the URL it says I do not have access even though I am a service admin.

Just trying to see if anyone else has experienced this and I am also on GCC.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Dont know

### What method are you using to get inventory and telemetry?

Cloud flows

AB#907

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry I'm having a little trouble following since there are so many admin types in the system. 

Can you please share pictures where you do and do not see this user? And describe what roles the service admin user has?

**Comment by RahulBojji** [comment]
@mdphung  Please go through this [documentation](https://learn.microsoft.com/en-us/power-platform/admin/control-user-access)

<img width="733" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/dd0fea78-5e08-422a-a7db-a5f0b25eea00">

Hope this answers your question

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
