### ISSUE TITLE
[CoE Starter Kit - QUESTION]  appDocumentComplexity node missing from Get App as Admin

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#7140]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

There is no documentation on how this works or where it gets pulled from.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/68c365fb-c024-490c-980c-d4ddedf4b62e)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 Driver

### What method are you using to get inventory and telemetry?

Cloud flows

AB#908

**Comment by Jenefer-Monroe** [comment]
This was added with https://github.com/microsoft/coe-starter-kit/issues/6014 and is to be filled by just the regular sync flows but it looks like the app complexity node is missing from the output from the product now. 
Marking this as a product gap to follow up on what happened.

**Comment by Jenefer-Monroe** [comment]
Looks like this got removed from the product. Will clean up the feature for Dec release.
