### ISSUE TITLE
[CoE Starter Kit - BUG]  UpsertAuditLogEvent action gives duplicate key error

### ISSUE THREAD

**Issue by Siddhesh-S21** [microsoft/coe-starter-kit#7141]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

**Flow name:** Admin | Audit Logs | Sync Audit Logs (V2)

The UPSERT action is not working as it should be for one flow particularly.
Error message on UPSERT : "message": "A record with matching key values already exists.",

This is a strange issue that we are facing however, we could not see this on a regular basis. It's almost once in a week or two, we are experiencing this issue. 
We have observed 6-7 failed instances over the last couple of months.

![image](https://github.com/microsoft/coe-starter-kit/assets/134070821/5749365a-b65e-4ac7-92a0-f4e2d4bf48a8)

![image](https://github.com/microsoft/coe-starter-kit/assets/134070821/62f269aa-109e-42c2-a3d1-686edaf66970)

### Expected Behavior

As expected, the UPSERT should update the record as it already exists.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

**1. Environment Type:** Production
**2. Environment Region:** Europe
![image](https://github.com/microsoft/coe-starter-kit/assets/134070821/0638f1f4-691b-4db8-8f80-6c3bc2012292)

3. We have the **CoE Starter Kit Kit - May 2023** version installed over our environment.

![image](https://github.com/microsoft/coe-starter-kit/assets/134070821/ac54934e-7354-411b-8946-3d2be677d464)

4. The Action used in this flow is Dataverse action 'Update a row'

![image](https://github.com/microsoft/coe-starter-kit/assets/134070821/a1c42e89-b419-4852-b3af-43aed5c9836d)

AB#944

**Comment by RahulBojji** [comment]
@Siddhesh-S21 Can you please let us know if there are any non-unique Id's being returned from the below action

<img width="787" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/10173387-7aee-40e6-bbea-f6c220e60583">

We are assuming if non-unique Id's being iterated and the upsert operations are happening parallely for the same Id, it might cause an issue like this

**Comment by Siddhesh-S21** [comment]
@RahulBojji I've checked in the action named 'FilterEvents' and found that the Id for each log is unique and we have no duplicate values in that iteration.

![image](https://github.com/microsoft/coe-starter-kit/assets/134070821/657b2071-06da-4f74-98af-8d80912a213e)

**Comment by RahulBojji** [comment]
Hi @Siddhesh-S21 
I have tried to repro the issue at my end but couldn't repro it. We can try by adding a retry policy for "Upsert" action by clicking on the ellipsis present in the corner of the action

we can add a retry policy like below

Click on three elipsis and then Settings 

<img width="785" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/ab95c5b2-3061-4697-bd4f-d40a4db36997">

![MicrosoftTeams-image](https://github.com/microsoft/coe-starter-kit/assets/149372606/445c5cf7-fc9f-41a0-99cd-66389285d21a)

Of all the flows, only this flow has a retry policy of default and if it also doesn't work we need to raise a MS Support ticket, since we are leveraging MS OOB connectors

**Comment by Siddhesh-S21** [comment]
Hi @RahulBojji, I've changed the Retry policy from 'Default' to 'Exponential Interval' as per your suggestion. Will observe for while if this resolves the issue we faced sometimes.
