### ISSUE TITLE
[CoE Starter Kit - BUG] New Environment Request 

### ISSUE THREAD

**Issue by sunilmhatugade** [microsoft/coe-starter-kit#7142]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team

Not able to request for new environment using Maker command center App. The new environment request tab not showing..

Please find the below snap for your reference, 

![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/0f8bbe33-f64b-4b9b-bb67-e44acbb069e9)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoE Maker Command Center

### What method are you using to get inventory and telemetry?

None

AB#1016

**Comment by SteveBaillargeon** [comment]
+1

**Comment by RahulBojji** [comment]
@sunilmhatugade  Can you please let us know the version of creator kit you are using. 

You can find the version of creator kit by logging into https://make.powerapps.com/

<img width="900" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/ae5f603f-75a7-4611-87ce-1ad2ac46c969">

**Comment by RahulBojji** [comment]
i have tried by using Power Platform Maker SR only. I am not able to repro the issue
<img width="960" alt="MicrosoftTeams-image (1)" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/330764a0-6ea4-41c7-bb5c-1ab5733228a1">



<img width="959" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/407a6a4d-62b2-4e72-995c-4c31733798b0">

**Comment by sunilmhatugade** [comment]
Please find below snap  
![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/0490c378-c615-483d-9240-394699cf527a)

**Comment by sunilmhatugade** [comment]
also upgraded  creatorkit version but still same issue.
![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/b367bfbc-db5a-4177-8407-243ddb3394b9)

in you view some tabs areshowing but i'm not able to view tabs
![image](https://github.com/microsoft/coe-starter-kit/assets/136294373/e52ad77f-1ccc-4e59-8710-6068f17f2c24)

**Comment by RahulBojji** [comment]
please check if "Power Apps component framework for canvas apps" is enabled or not. 
https://learn.microsoft.com/en-us/power-apps/developer/component-framework/component-framework-for-canvas-apps#enable-the-power-apps-component-framework-feature

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
