### ISSUE TITLE
Trying to switch from Azure Data Lake Storage (BYODL) back to Cloud flows

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#7149]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v3 CoE Solution Metadata

Looks like your flow's c_kushner@boozallen.onmicrosoft.com connection needs to be signed-in again. The most common cause is a changed password or a policy set by your tenant administrator. Connections may also require reauthentication, if multi-factor authentication has been recently enabled for your account.

How/where do I fix the connection without creating an unmanaged layer?

### Expected Behavior

Fix the connection

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Examine error from recent run.

AB#1440

**Comment by Jenefer-Monroe** [comment]
You would first repair the connection (or create a new one) and then update the connection reference to point to the working connection

1. Look for and fix broken connections
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/52b05771-cffa-4058-98aa-018d4ec6a7f5)

2. Go to Default Solution > Conection References > Ensure it points to the new / fixed connection.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/240a02e4-1af4-4eee-91bb-329b44be1f66)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
