### ISSUE TITLE
[CoE Starter Kit - Question]: How update env vars in DfT

### ISSUE THREAD

**Issue by mreed75** [microsoft/coe-starter-kit#715]
**Describe the bug**
A clear and concise description of what the bug is. In Teams (Power Apps) click on Build then Installed Apps.  Center of Excellence Core Components click on See all. Click on Other and then Environment variables and then Developer Compliance Center URL  Why can't I set the default value here?  I think this is where I should enter the web link. The app wont launch or play within Teams

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**
1. Go to '...' Teams
2. Click on '....' Devoploper Compliance Center
3. Scroll down to '....' Click on Launch
4. See error  in screen shot below

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/86731249/123985990-eb895d00-d993-11eb-82ab-4f15607c97ec.png)

![image](https://user-images.githubusercontent.com/86731249/123986090-ffcd5a00-d993-11eb-927c-0bf96d2a12e6.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
I believe you are asking how to update the environment variable for solutions installed in Teams. We've made this answer easier to find in the July version of the documentation. But for now pasting here.  

1. Go to flow.microsoft.com
1. Select your Dataverse for Teams environment
1. Select Solution
1. Select Common Data Service Default Solution
1. Select + Add > Environment Variables
1. Select the existing Environment Variables from the managed solution that you want to update
1. After adding those, selected Environment Variables in the new menu navigation and you should then be able to add a default and current value

**Comment by JeneferM-MSFT** [comment]
Documents updated/ Thanks for helping make CoE great.
