### ISSUE TITLE
[ALM Accelerator - QUESTION] Custom Connector

### ISSUE THREAD

**Issue by rfarris2000** [microsoft/coe-starter-kit#7151]
### What is your question?

What is the guidance regarding the custom connector setup for the Redirect URI?  Do we need to update the app registration?

When updating the custom connector we are presented with the following banner:

![image](https://github.com/microsoft/coe-starter-kit/assets/1624416/4a2bfcbf-361a-45f5-8c0b-91361575c1dd)

The Custom Connector Doc says this:
https://learn.microsoft.com/en-us/connectors/custom-connectors/azure-active-directory-authentication#set-the-reply-url-in-azure
![image](https://github.com/microsoft/coe-starter-kit/assets/1624416/46586250-5966-49b4-8093-f5f61f2b07ff)

The documentation states this:
https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#import-the-solution-and-configure-the-app
![image](https://github.com/microsoft/coe-starter-kit/assets/1624416/137830d4-349c-427f-b606-998f43b0806b)

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

November 2023

AB#1442

**Comment by RajeevPentyala** [comment]
Same as #7174

**Comment by RajeevPentyala** [comment]
@rfarris2000 We will be updating the documentation to reflect these changes.

**Comment by RajeevPentyala** [comment]
@rfarris2000 [Documentation](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#configure-the-devops-custom-connector) has been updated.

**Comment by v-bjaiswal** [comment]
closing out this ticket. Please rasie the new issue if you face any issue. Thank you.
