### ISSUE TITLE
[CoE Starter Kit - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by abhijkumar-msft** [microsoft/coe-starter-kit#7152]
### Is your feature request related to a problem? Please describe.

As of the most recent release (BYODL version), there's ample reporting on Connector Actions when used in the context of a Flow. Can this be quickly extended to include when those same Connector Actions are performed in the context of an app as well?

### Describe the solution you'd like

Simply extend the "Connector Actions" reporting to include when used inside of apps as well as Flows.

AB#1443

**Comment by Jenefer-Monroe** [comment]
I'm not sure this is possible, but including area owner to let us know.

**Comment by Jenefer-Monroe** [comment]
Unfortunately we don't have connector actions that are used in an app, that level of reporting is only available for flows

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
