### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Request | Sync Policy to Dataverse (Child)

### ISSUE THREAD

**Issue by SannaHoglindABP** [microsoft/coe-starter-kit#7156]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow DLP Request | Sync Policy to Dataverse (Child) is not working for connectors that are not still in DLP policy. 

I think "Unrelate with"in "Unrelate rows" should be updated to @{items('Apply_to_each_Connector_in_Dataverse_Policy')?['@odata.id']} (see image)

![image](https://github.com/microsoft/coe-starter-kit/assets/150917538/2a216d0c-13b6-4ae0-b430-8dc9f1b0fac9)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 2023

### What app or flow are you having the issue with?

DLP Request | Sync Policy to Dataverse (Child)

AB#1456

**Comment by Jenefer-Monroe** [comment]
Can you please help us by outlining the steps you used to see this issue?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
