### ISSUE TITLE
[CoE Starter Kit - BUG] Solutions on Power Platform Admin View and Power BI Report are missing certain solutions.

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#7160]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/ccddd19e-0027-419a-ab61-3e64ce97cf42)
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/ed321100-9007-47f0-ba07-48520a52f482)

Maybe there is a reason but I noticed the following are missing is it because maybe these specific ones are system owned.
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/9eea1225-b0a5-4726-9d43-ab8587cff176)

Also I used to be able to see a list in the dashboard the system owned ones.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/167ffd3e-6f2f-454b-9f90-7ef38bcbc1c0)

Some other issues are in the Solutions Power BI Report:  Environment Name and Maker Name filters in the Power BI report.  The Environment Name filter doesn't return a list of environments and the Maker Names filter returns more maker names then what would be expected.
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/9afe3fb0-8535-4e51-9eed-e7b7b7c10dae)

The Solutions link from the introduction page is broken.  If we manually navigate to the page, it contains all the data elements that are expected.
When you click on the highlighted this message appears.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/11339952-6230-421d-af55-e97cf339df08)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1461

**Comment by Jenefer-Monroe** [comment]
We hide most solutions from Microsoft by default. You can see that here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e1732a06-d4c9-47d2-9128-fee5bae58cee)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
