### ISSUE TITLE
[CoE Starter Kit - BUG] Flows Deep Dive Report Several Isssues

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#7161]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When using the Explain Flow by different options like by Environment the Flows Detail Page is blank when you use any option.
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/d03eb9ec-9fb2-4bf4-ba79-f63993b314ac)

Also Flow details visual is broken once it is uploaded and published there is a hardcoded value of Adele Vance's Environment that was pushed in the report from Microsoft but once you select something else it goes away.
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/3cb966e5-e639-46a7-9569-e303ca6029d3)

The tree navigation says there are 158 flows total but if you drill in by environment name you can see the individual counts by environment are way off as they add up to well over 158.
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/d2f274cb-9a07-4028-9e15-9040c42a07a2)

If you drill in by Connector Tier that break down also doesn't match the total number of flows.
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/4a4190b8-14e1-4768-844d-375e2c002825)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Sync Template V3 alot of them

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1462

**Comment by Jenefer-Monroe** [comment]
I think this is the same as https://github.com/microsoft/coe-starter-kit/issues/7165
Where these numbers refer to different things. It depends on what table the field was dropped from. so this is saying you have 6 Production environments, not that you have 6 (for example) BPFs in that envt.
Ill dupe to that bug.
