### ISSUE TITLE
[CoE Starter Kit - BUG] Power Pages, Custom Connectors, and Business Process Flows Power BI Report Filters do not have correct counts on the filters and filters they dont work

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#7162]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/7f77d2c5-2099-44a9-bc9a-adc781c3a8a0)

I only have 3 on this whole tenant.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/1dd260e9-6503-40d5-8e85-8e942a87a688)
Everyone in the tenant has a 1 but I know there are only 3 different people that actually created one.

No longer can filter on different Environments.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/50d91a90-ea90-4185-8ca0-a64992da808f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1463

**Comment by Jenefer-Monroe** [comment]
I think this is the same as https://github.com/microsoft/coe-starter-kit/issues/7165
Where these numbers refer to different things. It depends on what table the field was dropped from. so this is saying you have 6 Production environments, not that you have 6 (for example) BPFs in that envt.
Ill dupe to that bug.
