### ISSUE TITLE
[CoE Starter Kit - BUG] App Deep Dive Power BI Report Filtering not working correctly or displaying correct numbers

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#7165]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/9e298731-9e49-47b3-977c-80c7757f7ac6)
When choosing by Environment Type the numbers are off and doesnt seem to be the correct listing but I am assuming it removes system generated apps from this list.
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/9672357c-5b6e-426c-834a-2444df247a78)
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/49e092e4-cd3c-4745-a52b-6c62b3c4d5e1)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1467

**Comment by Jenefer-Monroe** [comment]
This shows the number of environments, so you have 6 production envts
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6133d0b3-a2df-4a51-a411-2252566a29fa)

While this shows the number of apps in an envt, so Power Platform CoE envt has 137 apps
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/25faf323-bdff-4af0-80d7-e0c3d4d75e24)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
