### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis App - PPAC URL needs to get value from environment variable for Government Clouds

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#7166]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

If you select to include All Environments or Exclude Environments and select the environments, you always get this where it doesn't believe you have any environments even though I have like 13 environments and have 2 selected for excluding it does the same thing shows 0 environments. The only option that works properly is the Add Multiple Environments.

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/115affc4-f556-46f6-83b8-3a30ee0d36ce)

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/94bb9423-f318-4c16-927a-cbe4203ca23d)

Also, the Open Policy in PAC it is hardcoded for commercial versus just pulling in the field information I am on GCC tenant:
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/954af5e9-19f3-47ac-b552-ef3b5f8f87f9)

![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/392e7afb-b013-4643-ad0e-147faad648b3)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

not sure

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1486

**Comment by manuelap-msft** [comment]
The first two issues we're already tracking here https://github.com/microsoft/coe-starter-kit/issues/7036

We'll use this bug to track the PPAC URL updates needed to support Government clouds.

**Comment by manuelap-msft** [comment]
FYI here are the URLs for Power Platform Admin Center for different regions
https://learn.microsoft.com/en-us/power-platform/admin/powerapps-us-government#power-apps-us-government-service-urls

We will have to update the Setup Wizard to store the PPAC URL in a new environment variable - we don't have this today (we only have it for Power Apps/Automate Maker Portals)

**Comment by Jenefer-Monroe** [comment]
> FYI here are the URLs for Power Platform Admin Center for different regions https://learn.microsoft.com/en-us/power-platform/admin/powerapps-us-government#power-apps-us-government-service-urls
> 
> We will have to update the Setup Wizard to store the PPAC URL in a new environment variable - we don't have this today (we only have it for Power Apps/Automate Maker Portals)

Change made for DLP app only, no changes to setup wizard
