### ISSUE TITLE
[CoE Starter Kit - BUG] PowerApps Usage data does not get exported to Azure Data Lake

### ISSUE THREAD

**Issue by wlcmundp** [microsoft/coe-starter-kit#7170]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I'm currently testing the new data export feature for the CoE Starter Kit. 

Everything is set up correctly. However, I immediately noticed that the PowerApps and Power Automate usage data do not get exported. 

It took 3 days for the usage data for Power Automate to show up in my Azure Data Lake. But it's now the 6th day and the PowerApps usage data never showed up. 

### Expected Behavior

The folder (usage) should be created within 5 days of setting up data export under the path /powerplatform/powerapps and /powerplatform/powerautomate in Azure Data Lake. However, the usage data for the PowerApps never showed up. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

CoE BYODL Apps Last Launched Date

### What method are you using to get inventory and telemetry?

Data Export

AB#1494

**Comment by manuelap-msft** [comment]
The Data Export feature is a product feature unrelated to the CoE Starter Kit. The CoE kit just consumes the data. If you have issues with the Data Export product feature, you'll need to raise that through your regular support channels - https://learn.microsoft.com/en-us/power-platform/admin/get-help-support

We unfortunately can't help with issues related to the product feature itself.
