### ISSUE TITLE
Environment Variable CoE System User ID

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#7171]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 

it is not possible to turn on the inventory flow for Desktop Flow without the CoE System User ID.
What kind of user should this be? Can I add the ID of the Service User with which I imported the kit?

It would be geat to get help with this.

Kind regards
Cathi

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Desktop flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1495

**Comment by BB-BITS** [comment]
I have a similar question.  I started importing the November CoE update and one of the environment variables it prompts for is a CoE System User ID.  What type of value should go there?  A system admin user account such as admin@mycompany.com?

**Comment by shrikant-singh31** [comment]
Hi @Cathi029 & @BB-BITS , I drilled down the **Admin | Sync Template v4 (Desktop flows)** flow to check where is it being used I can see it is being in OwnerID Compose action(refer the screenshot below)
![image](https://github.com/microsoft/coe-starter-kit/assets/149066866/219a392c-37cb-4c40-baac-bbabe8527127)

 It contains below expression:
**if(equals(body('Get_Owner')?['azureactivedirectoryobjectid'], null), if(equals(body('Get_Owner')?['fullname'], 'SYSTEM'), parameters('CoE System User ID (admin_CoESystemUserID)'), ''), body('Get_Owner')?['azureactivedirectoryobjectid'])**
So, from the expression we can see that we need to give GUID of systemuser table record where fullname is SYSTEM. We can find it using Advanced Find.
Please refer below screenshots for getting GUID from User table with FullName SYSTEM.

<img width="960" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149066866/2ea90e24-f044-4899-a72a-cdf9335252b8">
From the URL extract the GUID
<img width="960" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149066866/12c8ed5b-589b-4ef9-9b05-6eb8c9aad75a">

**Comment by Cathi029** [comment]
I recogniced that there are two flows with different versions. I can now activate both, but I am not sure which one I should use, dokumentations only mentions v3.
<img width="930" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/62603605/3f1f69c5-89d0-4350-9e60-7b6fd5d912d8">

**Comment by shrikant-singh31** [comment]
Hi @Cathi029, please refer https://github.com/microsoft/coe-starter-kit/issues/6946 for clarification.
It is recommended to read the release notes every time before updating to a newer version. It contains all the details regarding the new update. The November release has this new feature released(refer below screenshot from Novemeber release notes).
<img width="960" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149066866/e8f75fdc-0510-4a1d-ac37-f887bf71a4db">
Please go through https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup#github-release-notes for updating CoE toolkit.

**Comment by Cathi029** [comment]
@shrikant-singh31 thank you very much for your help!
