### ISSUE TITLE
[CoE Starter Kit - QUESTION] Not able upgrade CoE core solution from 4.9 version to 4.17 version

### ISSUE THREAD

**Issue by PPTechy** [microsoft/coe-starter-kit#7172]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am trying to upgrade my core solution from 4.9 version to 4.17 version (latest one), but the upgrade is not going well, getting errors. First I got the below error:
<img width="476" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/2c1d8554-0d76-48b3-964d-64f5402f2406">

Then I referred to [this ](https://github.com/microsoft/coe-starter-kit/issues/6018)article for the above fix, then when I re-imported the core solution, about 2 hour later I got the below error:

<img width="569" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/370b3431-b6ed-40db-a554-cef55ad24ebc">

If I look at my default solution custom connectors section, I have this custom connector:

<img width="664" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/e98a9b6b-9686-4085-9f81-ff04e52dfeea">

It seems during the upgrade session, the upgrade process is trying to delete this custom connector but not able to do this.

Please help me how to successfully upgrade the core solution to 4.17 version.

@Jenefer-Monroe 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

November 2023

### What app or flow are you having the issue with?

Core solution upgrade

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1496

**Comment by RahulBojji** [comment]
Hi @PPTechy 
Please have a look into [this issue](https://github.com/microsoft/coe-starter-kit/issues/6018). This should resolve your issue as well.
Please feel free to let us know if it doesn't fix your issue

**Comment by RahulBojji** [comment]
#6018 #6816

**Comment by PPTechy** [comment]
@RahulBojji @Jenefer-Monroe  I have tried those links, it didn't work. It is failing on deleting the custom connector "**admin-5foffice-20365-20management-20api-**". When I tried to delete this manually from the "**Default**" solution, the delete option is disabled state but I can see the "**Delete**" option from the environment custom connectors section for this custom connector "**admin-5foffice-20365-20management-20api-**". Can I delete it manually this custom connector then re-import the core solution again? What do you suggest? The upgrade part is becoming frustrating, it shouldn't be this much complicated and confusing.

**Comment by RahulBojji** [comment]
@PPTechy In Issue #6018 There was a response from the customer about the deletion of the connector
<img width="788" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/8bb7840b-cf1f-45e8-8c9c-79c14f14f856">

Also please have a look into this issue created previously #6270

**Comment by PPTechy** [comment]
@RahulBojji - In that screenshot, the user user mentioned he deleted the Office 365 Management custom connector from the "**Default**" solution, then he re-upgraded the solution and worked. 

<img width="463" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/55948135/12dc1ee1-f222-4260-be5e-34d4727a0145">


For me, from "**Default**" solution I am not able to delete this Office 365 Management custom connector, the remove option is disabled. Then, how can I delete it? I have used the PowerShell command also, there also this custom connector is not listing out. Now, please tell me the way to delete this custom connector from the default solution.

**Comment by RahulBojji** [comment]
@PPTechy Hope you are trying to delete the custom connector with System Administrator role. 
Also, if you haven't tried can you please try [this](https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/Cannot-retrieve-Connectors-for-a-non-default-environment/m-p/819953#M3919).

**Comment by PPTechy** [comment]
> @PPTechy Hope you are trying to delete the custom connector with roles specified in the documentation and you have access to that custom connector. Also, if you haven't tried can you please try [this](https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/Cannot-retrieve-Connectors-for-a-non-default-environment/m-p/819953#M3919).

@RahulBojji I don't have access issue, and I tried that link also it it didn't work. I have gone through many similar links from GitHub, many of them reported the same issue, they are not able to delete the custom connector from the "**Default**" solution with modern view, earlier in classic view it was allowing.

@Jenefer-Monroe I request your help in this thread, please.

**Comment by PPTechy** [comment]
I am able to import the solution successfully.

**Comment by RahulBojji** [comment]
@PPTechy Can you please let us know what you did exactly that solution got imported successfully

**Comment by PPTechy** [comment]
I did the below:

1. I have deleted solution layers (customizations).
2. Imported the new core solution, got error, that was related to audit logs.
3. Deleted the core solution_upgrade version
4. Deleted the audit log solution.
5. Re-imported core solution, this time got error about custom connector references, but I could not see these references from the UI.
6. Again Deleted the core solution_upgrade version
7. Using PowerShell, tried to delete the custom connector itself, it didn't allow saying that it has connection references.
8. Deleted all connection references for that custom connector one bye one, and left the custom connector as un-deleted.
9. Re-imported core solution again, it took lot of times to complete but it was successful. After successful import, the custom connector got deleted automatically using the import core solution process. 
10. Done.

**Comment by dksamo1986** [comment]
We resolved the issue by doing the following: 

1. Run the following Power Shell script: Get-AdminPowerAppConnection -ConnectorName shared_runtimeservice for the Office 365 Management API customer connector. This returned all the connection references that we could not see from the Power Platform environment UI. (https://learn.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest)  

2. Run the following Power Shell script: Remove-AdminPowerAppConnection -ConnectionName [ConnectionName] -ConnectorName shared_twitter -EnvironmentName Default-[Guid] for all connection references. (https://learn.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest)  

3. Delete the customer connector from Power Automate.  

4. Delete the failed upgrade for Core 4.17.  (This could take time). 

5. Import the Core component 4.17. 

6. Success.
