### ISSUE TITLE
[ALM Accelerator - QUESTION] Guidance on applying Custom Connector Security Updates

### ISSUE THREAD

**Issue by JM-SHA** [microsoft/coe-starter-kit#7174]
### What is your question?

We are using the ALM Custom Connector "CustomAzureDevOps". 
![image](https://github.com/microsoft/coe-starter-kit/assets/120573109/b6789675-1fcb-4415-ba91-4749c6f0de39)

The following MsgCenter Post recommends changes on custom connectors: [Power Platform] Important Security Update for Custom Connectors using OAuth 2.0 authentication [MC690931]

![image](https://github.com/microsoft/coe-starter-kit/assets/120573109/79447328-06eb-46f0-b103-0bff47c99792)

Is an update of the ALM Solution necessary?
What are the recommended steps?

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

CenterofExcellenceALMAccelerator_1.0.20230802.1_managed.zip

AB#1499

**Comment by RajeevPentyala** [comment]
Same as #7151 7151

**Comment by RajeevPentyala** [comment]
@JM-SHA [Documentation](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#configure-the-devops-custom-connector) has been updated.
