### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Setup Wizard gets stuck at Run setup flows step - BYODL

### ISSUE THREAD

**Issue by RebekkaAalbers** [microsoft/coe-starter-kit#7179]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I made a fresh install of the CoE Kit to run using data export instead of flows for inventory. 
I am unable to get past the Run setup flows step in the Setup Wizard. 
The screen loads, the Refresh button becomes active at some point, but the flows you usually see in this screen are not shown and the Next button stays inactive. I have waited up to an hour and tried multiple times. The outcome stays the same. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Vanilla Sandbox environment with Dataverse
2. Imported Core-components
3. Configured the dataflows according to the docs. All dataflows ran successfully.
4. Started Setup Wizard.
6. Configured Amin persona, Maker persona, skipped User persona (is non-production install on prod tenant)
7. Settings configured: Commercial, Production environment no, tenant id & individual admin configured. 
8. Selected Data export(preview) as the inventory option
9. Get stuck on Run setup flows step.

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/30928094/293bb5a6-3734-4aa3-8b38-1911561a369c)

AB#1509

**Comment by Jenefer-Monroe** [comment]
Hitting Refresh here should show the flows after they get started. I have seen a delay here once in a while but eventually the button will show the flows running. 
Do you not see that?

**Comment by RebekkaAalbers** [comment]
He Jenefer,
No, the screen stays blank. 🤷🏻‍♀️

**Comment by RebekkaAalbers** [comment]
Ok, I tried again. After 10x hitting refresh the flows finally showed up.

**Comment by RebekkaAalbers** [comment]
Hi Jenever,
Something is still off. 
Of the 3 flows only 1 is now tagged as finished. The other ones remain in the running state. I checked the flow details and both flows have run about a week ago and finished successful, but have not been triggered today.  
<img width="1177" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/30928094/56ff4c48-5f26-4189-8d9d-77bc1f2ac9ad">

**Comment by Jenefer-Monroe** [comment]
Yes this logic is more complicated that you might imagine as we dont have a direct link to flow runs so we are approximating. 
There is often a pause between that metadata one running and the other two, so I would expect this to also be transitory.

**Comment by Jenefer-Monroe** [comment]
If you go look at the metadata table, do you see multiple copies of these flows? That might lead to this.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca6b4541-49f9-4e6f-abf2-6b9b6f1bea87)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
