### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade to 4.17 failure

### ISSUE THREAD

**Issue by dynam0r** [microsoft/coe-starter-kit#7180]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

My dataflows related to Power Automate seems to be failing because of transform error. The Power Apps flows are working fine, but everything related to Flows seem to fail in the same phase when Querying the dataflow. This leads to a situation where I can see the Apps data using the Power BI dashboard but not the Flow data (as the error query steps filters off the errored rows).
Here's the overview error:
![image](https://github.com/microsoft/coe-starter-kit/assets/151754252/463f2acb-3957-48b2-865e-beed30c402ae)
And if diven deeper:
![image](https://github.com/microsoft/coe-starter-kit/assets/151754252/628def00-a144-4059-933e-4d3e910eb289)
Seems to be a problem in the json files. Is this something I can fix or is the export pushing wrong kind of files to the storage account? All the neccessary folders and files are in the stroage account, nothing is missing.

The error msg:
---------- Message ----------
DataFormat.Error: We found extra characters at the end of the JSON input.

---------- Session ID ----------
084c1153-53f5-42a1-9967-25cc6e328e49

---------- Request ID ----------
47cc3c5b-faa6-4042-818e-d8e6aee3ebcc

---------- Mashup script ----------
section Section1;
shared #"Sample file (9)" = let
    Source = AzureStorage.DataLake(DatalakeURL & "/powerautomate/Flows"),
    #"Filtered hidden files" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    Navigation = #"Filtered hidden files"{0}[Content]
in
    Navigation;
shared #"Transform file (9)" = let
    Source = (Parameter as binary) => let
    Source = Text.FromBinary(Parameter),
    #"Imported JSON" = Replacer.ReplaceText(Source, "}", "},"),
    #"Trim last character" = Text.Trim(#"Imported JSON", ","),
    #"Insert bracket" = Text.Insert(#"Trim last character", 0, "["),
    #"Insert second bracket" = Text.Insert(#"Insert bracket", Text.Length(#"Insert bracket"), "]"),
    #"Parsed JSON" = Json.Document(#"Insert second bracket")
in
    #"Parsed JSON"
in
    Source;
[Description = "Storage account you've set up to receive the Power Platform Data Export. Get the URL by navigating to your Storage Account > Endpoints > Copy the Data Lake Storage endpoint (example https://mypowerpaltformexport.dfs.core.windows.net/powerplatform)"]
shared DatalakeURL = let
    DatalakeURL_Apps = "https://xxx.dfs.core.windows.net/powerplatform" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]
in
    DatalakeURL_Apps;
[Description = "Environment Web API endpoint. Get via make.powerapps.com > Settings Cog > Developer resources > Web API Endpoint value (example https://mycoe.api.crm.dynamics.com/api/data/v9.2)"]
shared EnvironmentAPI = let
    EnvironmentAPI = "https://xxx.org.api.crm4.dynamics.com/api/data/v9.2" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]
in
    EnvironmentAPI;
shared Flows = let
    Source = AzureStorage.DataLake(DatalakeURL & "/powerautomate/Flows"),
    excludehiddenfiles = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    excludezerolengthfiles = Table.SelectRows(excludehiddenfiles, each [Attributes]?[Size]? > 0),
  // Extract Environment GUID from File Name
  #"Extract Environment ID from File Name" = Table.TransformColumnTypes(Table.AddColumn(excludezerolengthfiles, "EnvironmentName", each if Text.Length([Name]) = 41 then Text.Range([Name], 0,36) else Text.Range(Text.AfterDelimiter([Name], "-", 0), 0, 36)), {{"EnvironmentName", type text}}),
  // Remove unnecessary columns from the folder system, like extension and folder path.
  #"Removed unneeded columns" = Table.RemoveColumns(#"Extract Environment ID from File Name", {"Folder Path", "Attributes", "Date created", "Date modified", "Date accessed", "Extension", "Name"}),
  // Inner join of flow table with environments table, only keep flows where the environment still exists. This filters out flows from deleted environments.
  #"Merge with environments" = Table.NestedJoin(#"Removed unneeded columns", {"EnvironmentName"}, admin_environments, {"admin_environmentid"}, "admin_environments", JoinKind.Inner),
  #"Expanded Environments" = Table.ExpandTableColumn(#"Merge with environments", "admin_environments", {"admin_environmentid", "admin_displayname"}, {"admin_environmentid", "admin_environmentdisplayname"}),
  // Transform the content from the json files in the storage account into tables
  #"Get content from json files" = Table.AddColumn(#"Expanded Environments", "Transform file", each #"Transform file (9)"([Content])),
  #"Drill down" = #"Get content from json files"{0}[Transform file],
  Custom = Table.RemoveRowsWithErrors(#"Drill down", {"Transform file"}),
  // Expand all the columns the json file in the storage account provides into individual columns, e.g. flow name, flow id, created by, created on...
  #"Expanded columns" = Table.ExpandTableColumn(Custom, "Transform file", {"resourceId", "name", "environmentId", "lifecycleState", "events_created_timestamp", "events_created_principalId", "events_modified_timestamp", "customExtensions"}, {"flowId", "name", "environmentId", "lifecycleState", "createdOn", "createdBy", "lastModifiedOn", "customExtensions"}),
    #"Expanded customExtensions" = Table.ExpandRecordColumn(#"Expanded columns", "customExtensions", {"events_created_usertype", "sharingType", "flowTriggerUri", "triggerKind", "flowSuspensionTime", "flowSuspensionReason"}, {"events_created_usertype", "sharingType", "flowTriggerUri", "triggerKind", "flowSuspensionTime", "flowSuspensionReason"}),
  #"Removed Content binary column" = Table.RemoveColumns(#"Expanded customExtensions", {"Content"}),
  // Merge flows with maker to get more maker details, such as maker display name, department, is orphaned etc for furhter logic (is the flow orphaned)
  #"Merged with makers" = Table.NestedJoin(#"Removed Content binary column", {"createdBy"}, admin_makers, {"admin_makerid"}, "admin_makers", JoinKind.LeftOuter),
  #"Expanded maker table" = Table.ExpandTableColumn(#"Merged with makers", "admin_makers", {"admin_makerid", "admin_userprincipalname", "admin_makerisorphaned", "admin_department", "admin_displayname", "admin_country", "admin_company", "admin_city"}, {"admin_makerid", "admin_userprincipalname", "admin_makerisorphaned", "admin_department", "admin_displayname", "admin_country", "admin_company", "admin_city"}),
  // Add utcNow timestamp which we use to identify when the dataflow last updated/created a row
  #"Added QueriedOn" = Table.AddColumn(#"Expanded maker table", "QueriedOn", each DateTimeZone.UtcNow()),
  // Add yes/no text field to identify if the flow is owned by a maker that no longer exists in the org
  #"Add IsOrphan" = Table.AddColumn(#"Added QueriedOn", "IsOrphanText", each if [admin_makerisorphaned] = true then "Yes" else "No"),
  #"Merged queries" = Table.NestedJoin(#"Add IsOrphan", {"flowId"}, admin_flows, {"admin_flowid"}, "admin_flows", JoinKind.LeftOuter),
  #"Expanded admin_flows" = Table.ExpandTableColumn(#"Merged queries", "admin_flows", {"admin_derivedownerdisplayname", "admin_derivedownermakerid"}, {"admin_derivedownerdisplayname", "admin_derivedownermakerid"}),
  #"Inserted conditional column" = Table.AddColumn(#"Expanded admin_flows", "DerivedOwnerFinal", each if [admin_derivedownermakerid] = null then [admin_makerid] else [admin_derivedownermakerid]),
  #"Add flowIsPublished" = Table.TransformColumnTypes(Table.AddColumn(#"Inserted conditional column", "flowIsPublished", each true), {{"flowIsPublished", type logical}}) //to replace with logic once available
  ,
  #"Add isNotDeleted" = Table.TransformColumnTypes(Table.AddColumn(#"Add flowIsPublished", "isNotDeleted", each false), {{"isNotDeleted", type logical}})
,
  #"Changed column type" = Table.TransformColumnTypes(#"Add isNotDeleted", {{"EnvironmentName", type text}, {"admin_environmentid", type text}, {"admin_environmentdisplayname", type text}, {"flowId", type text}, {"name", type text}, {"environmentId", type text}, {"lifecycleState", type text}, {"createdOn", type datetime}, {"createdBy", type text}, {"lastModifiedOn", type datetime}, {"events_created_usertype", type any}, {"sharingType", type any}, {"flowTriggerUri", type any}, {"triggerKind", type any}, {"flowSuspensionTime", type any}, {"flowSuspensionReason", type any}, {"admin_makerid", type text}, {"admin_userprincipalname", type text}, {"admin_makerisorphaned", type logical}, {"admin_department", type text}, {"admin_displayname", type text}, {"admin_country", type text}, {"admin_company", type text}, {"admin_city", type text}, {"QueriedOn", type datetimezone}, {"IsOrphanText", type text}, {"admin_derivedownerdisplayname", type text}, {"admin_derivedownermakerid", type text}, {"DerivedOwnerFinal", type text},  {"isNotDeleted", type logical},  {"flowIsPublished", type logical}})
in
    #"Changed column type";
shared admin_environments = let
    Source = OData.Feed(EnvironmentAPI, null, [Implementation = "2.0"]),
    #"Navigation 1" = Source{[Name = "admin_environments", Signature = "table"]}[Data],
    #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"_admin_maker_value", "admin_numberofflows_state", "utcconversiontimezonecode", "_owninguser_value", "admin_excusefromappquarantineflow", "modifiedon", "admin_adminreviewon", "importsequencenumber", "admin_environmentexternalconnectioncount_date", "coe_EnvironmentCreationRequest_Environmen", "coe_DLPPolicyChangeRequest_Environment", "cat_CloudFlowRuns_Environment_admin_Envir", "bpf_admin_environment_new_environmentapprovalbpf", "admin_RPA_DesktopflowEnvironment_admin_En", "admin_rel_PVAEnvironment", "admin_rel_Environment_CustomConnector", "admin_rel_AppEnvironment", "admin_PVAComponent_ComponentEnvt_admin_En", "admin_PowerPlatformUserRole_Environment_a", "admin_PortalEnvironment", "admin_policy_environments", "admin_FlowActionDetail_FlowActionDetailEn", "admin_Flow_FlowEnvironment_admin_Environm", "admin_Maker", "admin_EnvironmentCapacity_Environment_adm", "admin_EnvironmentAddons_Environment_admin", "admin_BusinessArea", "admin_DataverseTables_Environment_admin_E", "admin_ConnectionReferenceIdentity_admin_E", "admin_admin_solution_SolutionEnvironment_admin_", "admin_admin_businessprocessflows_BusinessProces", "admin_environment_Annotations", "stageid", "admin_environment_PrincipalObjectAttributeAccesses", "admin_environment_BulkDeleteFailures", "admin_environment_ProcessSession", "admin_environment_MailboxTrackingFolders", "admin_environment_AsyncOperations", "admin_environment_DuplicateBaseRecord", "admin_environment_DuplicateMatchingRecord", "admin_environment_SyncErrors", "owningbusinessunit", "ownerid", "owningteam", "owninguser", "modifiedonbehalfby", "modifiedby", "createdonbehalfby", "createdby", "_admin_businessarea_value", "admin_microsoftteamsurl", "admin_region", "_createdonbehalfby_value", "admin_environmentmakerdisplayname", "_stageid_value", "admin_environmentdeleted", "admin_numberofapps_state", "admin_numberofflows", "createdon", "admin_environmentsku", "admin_tenantid", "admin_numberofconnectors", "timezoneruleversionnumber", "admin_adminreason", "admin_numberofconnectors_state", "admin_connectedgroupid", "admin_environmentpurpose", "admin_numberofconnectors_date", "admin_environmentname", "_modifiedby_value", "_owningbusinessunit_value", "admin_excusefromcomplianceflow", "admin_excusefromarchivalflows", "admin_numberofapps", "admin_environmentexternalconnectioncount_state", "statuscode", "admin_environmentmodifiedon", "admin_allocatedenvironmentcapacity", "admin_environmentisorphaned", "admin_numberofapps_date", "processid", "admin_environmentmakerupn", "admin_numberofflows_date", "_modifiedonbehalfby_value", "admin_environmentcdsmetadataname", "admin_environmentpurposetext", "admin_environmentdeletedon", "admin_makerrequirementbusinessjustification", "_createdby_value", "versionnumber", "overriddencreatedon", "_ownerid_value", "admin_hascds", "admin_iscoe", "admin_environmentcdsinstanceurl", "statecode", "admin_environmentcreatedon", "admin_microsoftteamsid", "admin_hasdlppolicy", "admin_environmentowner", "admin_businessjustificationdate", "admin_makerrequirementbusinessimpact", "admin_environmentexternalconnectioncount", "traversedpath", "_owningteam_value", "admin_adminmicrosoftteamsenvironmentstatus"})
in
    #"Removed columns";
shared admin_makers = let
    Source = OData.Feed(EnvironmentAPI, null, [Implementation = "2.0"]),
    #"Navigation 1" = Source{[Name = "admin_makers", Signature = "table"]}[Data],
    #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"utcconversiontimezonecode", "admin_m2managerprinciplename", "modifiedon", "admin_lastpulsesurvey", "admin_preferredlanguage", "admin_numberofuiflows_state", "admin_numberofcustomconnectors", "admin_numberofsharepointapps_date", "admin_numberofpvas_date", "admin_userisserviceprinciple", "admin_numberofflows_date", "admin_numberofpvas_state", "importsequencenumber", "admin_numberofcustomconnectors_date", "admin_numberofuiflows", "admin_numberofuiflows_date", "timezoneruleversionnumber", "admin_photoobject", "admin_numberofflows_state", "admin_numberofenvironments_state", "admin_jobtitle", "admin_managerid", "_owningteam_value", "admin_numberofenvironments", "_owninguser_value", "admin_managerprinciplename", "_modifiedby_value", "admin_accountenabled", "admin_numberofenvironments_date", "admin_photoobject_url", "admin_numberofflows", "admin_office", "admin_numberofapps", "admin_numberofcanvasapps", "admin_numberofcanvasapps_state", "overriddencreatedon", "versionnumber", "_createdby_value", "admin_numberofsharepointapps", "_owningbusinessunit_value", "admin_numberofcanvasapps_date", "admin_photoobject_timestamp", "statecode", "admin_numberofapps_date", "admin_numberofpvas", "statuscode", "admin_photoobjectid", "_ownerid_value", "admin_photo", "admin_numberofapps_state", "admin_numberofcustomconnectors_state", "_modifiedonbehalfby_value", "admin_numberofsharepointapps_state", "_createdonbehalfby_value", "admin_numberofmodeldrivenapps_date", "createdon", "admin_numberofmodeldrivenapps", "admin_numberofmodeldrivenapps_state", "createdby", "createdonbehalfby", "modifiedby", "modifiedonbehalfby", "owninguser", "owningteam", "ownerid", "owningbusinessunit", "admin_maker_SyncErrors", "admin_maker_DuplicateMatchingRecord", "admin_maker_DuplicateBaseRecord", "admin_maker_AsyncOperations", "admin_maker_MailboxTrackingFolders", "admin_maker_ProcessSession", "admin_maker_BulkDeleteFailures", "admin_maker_PrincipalObjectAttributeAccesses", "admin_admin_bpf_maker", "admin_admin_solution_SolutionCreator_admin_make", "admin_App_AppOwner_admin_Maker", "admin_EnvironmentMaker", "admin_Flow_DerivedOwner_admin_Maker", "admin_Flow_FlowCreator_admin_Maker", "admin_portal_PortalOwner_admin_Maker", "admin_PVA_PVAOwner_admin_Maker", "admin_rel_ConnectorMaker", "admin_RPA_RPAOwner_admin_Maker", "coe_EnvCreationRequest_SystemAdmins"})
in
    #"Removed columns";
shared admin_flows = let
  Source = OData.Feed(EnvironmentAPI, null, [Implementation = "2.0"]),
  Navigation = Source{[Name = "admin_flows", Signature = "table"]}[Data],
  #"Choose columns" = Table.SelectColumns(Navigation, {"admin_displayname", "admin_flowid", "admin_DerivedOwner", "admin_FlowCreator", "admin_FlowEnvironment"}),
  #"Expanded admin_DerivedOwner" = Table.ExpandRecordColumn(#"Choose columns", "admin_DerivedOwner", {"admin_displayname", "admin_makerid"}, {"admin_derivedownerdisplayname", "admin_derivedownermakerid"}),
  #"Expanded admin_FlowCreator" = Table.ExpandRecordColumn(#"Expanded admin_DerivedOwner", "admin_FlowCreator", {"admin_displayname", "admin_makerid"}, {"admin_creatordisplayname", "admin_creatormakerid"}),
  #"Expanded admin_FlowEnvironment" = Table.ExpandRecordColumn(#"Expanded admin_FlowCreator", "admin_FlowEnvironment", {"admin_environmentid", "admin_displayname"}, {"admin_environmentid", "admin_environmentdisplayname"})
in
  #"Expanded admin_FlowEnvironment";

Any help would be greatly appreciated, thanks in advance!

### Expected Behavior

Flow dataflows would work properly in similar fashion as the apps 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

CoE BYODL FLows

### What method are you using to get inventory and telemetry?

Data Export

AB#1511

**Comment by manuelap-msft** [comment]
We fixed some of this in more recent releases (see https://github.com/microsoft/coe-starter-kit/issues/6577 
 and https://github.com/microsoft/coe-starter-kit/issues/6723). 

However, there's a larger rework of the Dataflows planned for December https://github.com/microsoft/coe-starter-kit/issues/6969 as well.

**Comment by dynam0r** [comment]
Thanks!
However, I encountered a new problem when trying to upgrade to 4.17 (I take that this is the newest version?). The importing failed after about 45 minutes with Task Cancelled error. Here's the log file at the point when the error happens: 
![image](https://github.com/microsoft/coe-starter-kit/assets/151754252/f8c232ce-216d-4738-9f14-58ab54a4933e)
Failure itself shows at the top like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/151754252/3e98efb6-eeaf-40a2-86f6-16d1ad78d1b0)

I know that this problem is not related to the one in the subject but any help would still be appreciated.

**Comment by shrikant-singh31** [comment]
Hi @dynam0r, yes 4.17 is the latest solution for CoE-Core solution. Request you to please refer https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup#remove-unmanaged-layers-from-inventory-flows and try removing any unamanged layers from the flows or apps and retry importing by following steps in the documentation link mentioned?

**Comment by dynam0r** [comment]
Hello there, I managed to install the solution and noticed that now the Dataflows in Power Platform are working correctly. However, it seems that the PowerPlatformAdminAnalytics-DF.json within the solution used for Power BI dashboard doesn't seem to contain the updates. I think I can manually overwrite the definition, but I'm not sure which parts I should overwrite. Any ideas/possibility to get an updated version of the json?

Thanks!

**Comment by dynam0r** [comment]
> Hello there, I managed to install the solution and noticed that now the Dataflows in Power Platform are working correctly. However, it seems that the PowerPlatformAdminAnalytics-DF.json within the solution used for Power BI dashboard doesn't seem to contain the updates. I think I can manually overwrite the definition, but I'm not sure which parts I should overwrite. Any ideas/possibility to get an updated version of the json?
> 
> Thanks!

It might be that they're both working but Cloud flows and Desktop flows aren't still listed on the dataflows. Is this something the next version will fix?

**Comment by Jenefer-Monroe** [comment]
There were no updates to that json file, and desktop flows are not part of the Data Export solution yet. 
I'm having a little trouble following now what is the issue you are seeing?

**Comment by dynam0r** [comment]
> There were no updates to that json file, and desktop flows are not part of the Data Export solution yet. I'm having a little trouble following now what is the issue you are seeing?

Ah thanks, didn't know about these two. Now I can also define the issue better - it seems that for Flows the dataflows aren't finding the Power Platform Default environment, which leads to missing Flows in the Admin View. In comparison, all the apps also from the Default environment are found in the Admin View. 

I'm probably scratching the data export and moving back to cloud flows for now.

**Comment by Jenefer-Monroe** [comment]
I am doing a bunch of work on the API count for the old architecture so hopefully you'll be happy with that in the Jan release :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
