### ISSUE TITLE
[CoE Starter Kit - BUG] Data Export - all ModelDriven Apps showing as owned by SYSTEM

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#7181]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In PowerApps App table I haven't data of usage from Model Driven Apps. Also de App Owner of Model Driven apps is SYSTEM:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/b6ea88a1-d9ab-491d-b83e-00c86fa78dcd)

Instead in Power BI Model I have the data usage and de App Owner correct:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/aac122bd-b6c6-4f17-960b-82165734d093)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2023

### What app or flow are you having the issue with?

PowerApps App table

### What method are you using to get inventory and telemetry?

Data Export

AB#1516

**Comment by Jenefer-Monroe** [comment]
We do not have data usage for Model Driven apps unfortunately so that is expected

**Comment by Jenefer-Monroe** [comment]
For app owner, if you are using data export then the table should be written to by the dataflow as you show. 
Can you please tell me, directly after you do a dataflow refresh does it show correctly? Wondering if some other process is changing it?

**Comment by Jenefer-Monroe** [comment]
Regarding MDA usage, in the past they did not include the AppID for MDA's only for canvas. Looks like they ahve resolved this now! Will get this on the backlog

**Comment by Jenefer-Monroe** [comment]
ok I repro the issue with the SYSTEM user as well.

**Comment by albertocastro365** [comment]
Yes, in this other issue I am talking about of canvas. It seems a change in the structure of json files that affects to apps dataflows.

**Comment by Jenefer-Monroe** [comment]
OK it appears they have stopped writing the creatorid, I'm getting nulls, casn you check to see if yours is coming through as nulls as well?

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/39cbf089-b335-4f2d-9370-fdb9158b8681)

**Comment by Jenefer-Monroe** [comment]
looks like this bug https://github.com/microsoft/coe-starter-kit/issues/6658 which used to be just in this persons tenant has now spread. I'll dupe to that issue and we can track with it

**Comment by albertocastro365** [comment]
> OK it appears they have stopped writing the creatorid, I'm getting nulls, casn you check to see if yours is coming through as nulls as well?
> 
> ![Image](https://private-user-images.githubusercontent.com/89584709/285955191-39cbf089-b335-4f2d-9370-fdb9158b8681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDYyOTMsIm5iZiI6MTcwMTEwNTk5MywicGF0aCI6Ii84OTU4NDcwOS8yODU5NTUxOTEtMzljYmYwODktYjMzNS00ZjJkLTkzNzAtZmRiOTE1OGI4NjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE3MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNTBlYjAwMmFiMzAwYTk1OGYzOTgzYmYyZjQ5NWUzNzlmOWM1M2U1Y2MwNDFmNGIyOWY5YjNkOTBiNmE5ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yU3kz8EDyZ3rRCkloFezCK1taQdq1dc-P5aDpBZsaOM)

Me too

**Comment by Jenefer-Monroe** [comment]
Can you create a support ticket? We are pressing as well but that will be helpful

**Comment by albertocastro365** [comment]
Done! 
Case 2312010050004046

**Comment by albertocastro365** [comment]
Feedback from support:
"I got feedback from the product team that for model apps, CreatedPrincipalId is set to null, this is a known issue. 
 They are working on the enhancement of this feature to include createdby value."

**Comment by Jenefer-Monroe** [comment]
thank you so much for the update!

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
