### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL - PBI Model - Sessions ID without App linked

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#7182]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
in Power BI data model of Data Export version, I can see that we have a lot of sessions ID in Power Apps Launches without App ID, App Name, Environent linked.
Why could be this?
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/65d0781e-8624-41a3-93c9-bd93147169f6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Octubre 2023

### What app or flow are you having the issue with?

PBI Data model

### What method are you using to get inventory and telemetry?

Data Export

AB#1517

**Comment by Jenefer-Monroe** [comment]
Can you please look at the data in the actual datalake to see if it is correct there?

**Comment by albertocastro365** [comment]
Hi Jennefer,
I am investigating from datalake side, like you suggest, and I see something rare.

I take this app for the troubleshooting: 9fae9c0c-02c4-...

The app exists:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/393e01b8-6e8a-45c9-987c-ce3ac8443787)

Exists usage of the app in last appusage.json from datalake:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/3cfae1b2-3ede-44ac-b011-e800ed1868fa)

But, the canvas json file of the environment of this app was modified by last time at 08 June 2023!!!
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/57a93e42-6df2-43d3-8d81-205a0d458671)

This file have the app information of the "orphaned" sessions:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/1cf0c558-755e-48d5-b2df-f335e315767f)

Do you know why this canvas.json file is older? Maybe this json files have update when the app is published? Could be this related with the app id missing in Power Apps table?

If I filter the last step of Apps query in Power BI dataflow, this app id is not exists:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/93d25d2c-65ed-4969-afa6-5465221cf45c)

But in the first step the canvas json file is recovered:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/9176897d-c784-471d-b04e-124f5dc1d9bf)

**Comment by albertocastro365** [comment]
Hi again,
I see errors in a step of the power query of Apps:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/bead4280-d035-4e36-9be3-649d11dbdabe)
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/f9fb609e-4d47-485d-acc8-c8ccc67bd3c0)

**Comment by Jenefer-Monroe** [comment]
We fixed some of this in more recent releases (see https://github.com/microsoft/coe-starter-kit/issues/6577 and https://github.com/microsoft/coe-starter-kit/issues/6723). 

However, there's a larger rework of the Dataflows planned for December https://github.com/microsoft/coe-starter-kit/issues/6969 as well.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
