### ISSUE TITLE
[CoE Starter Kit - BUG]-Unable to add the Azure Key vault for office 365 management API 

### ISSUE THREAD

**Issue by chakradharNalla** [microsoft/coe-starter-kit#7183]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to connect the Azure keyvaults (office 365 management api) to COE Kit

![error](https://github.com/microsoft/coe-starter-kit/assets/150845631/5a3a0830-dab1-4437-9f45-77496a66ebb9)

### Expected Behavior

Unable to connect the azure keyvault from environment variable

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

lattest file from microsoft site

### What app or flow are you having the issue with?

Envinonment variables Audit logs azure client secret and command center azure client secret variables

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Unable to connect the azure keyvault from environment variable

### Anything else?

Unable to connect the azure keyvault from environment variable
![error](https://github.com/microsoft/coe-starter-kit/assets/150845631/ccaa1f19-9abe-401c-b3ae-069f24268664)

AB#1518

**Comment by RahulBojji** [comment]
@chakradharNalla Please have a look into this issue #6172 and #6473

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by sadranyi** [comment]
We are still experiencing the same issue as of today any headway in solving this
