### ISSUE TITLE
[CoE Starter Kit - Feature]: BYODL - PowerApps usage in Dataverse

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#7184]
### Describe the solution you'd like

Using Data Export version:
In Power BI Dataset we have the session data by app and user, and the possibility to know, for example, the unique users that use the app in the last month. Usefull to identify Production Apps.

In Dataverse we don't have this information. Only the count of sessions by app in the last month.

Do you think that it would possible add this information in Dataverse. 

Thanks Team.

AB#1519

**Comment by Jenefer-Monroe** [comment]
Thank you for the suggestion! Putting on the feature backlog

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
