### ISSUE TITLE
BYODL - PowerBi showing only 30% of the flows - Probable cause ==> Error in transform file in Dataflow

### ISSUE THREAD

**Issue by WouterKessener** [microsoft/coe-starter-kit#7186]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![COE - Missing flows in report](https://github.com/microsoft/coe-starter-kit/assets/15956643/961678c0-81e6-4b25-aa91-a85a6ea40275)

see screenshot. A lot of FLOW data is lost in the Dataflow while transforming DL files

### Expected Behavior

complete overview of flows in the PowerBu BYODL report

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

PowerPlatformAdminAnalytics-DF

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

See screenshot - 

1) Open PowerBI dataflow - PowerPlatformAdminAnalytics-DF
2) Edit Tables
3) Query: Flows 
4) Get Content from Json File
5) > 50% errors ==> Filtererd in next Step ==> Result lot of data missing

AB#1533

**Comment by Jenefer-Monroe** [comment]
We fixed some of this in more recent releases (see https://github.com/microsoft/coe-starter-kit/issues/6577 and https://github.com/microsoft/coe-starter-kit/issues/6723). 

However, there's a larger rework of the Dataflows planned for December https://github.com/microsoft/coe-starter-kit/issues/6969 as well.
