### ISSUE TITLE
[CoE Starter Kit - BUG] Template Catalogue Setup hangs on requires fows

### ISSUE THREAD

**Issue by KjetilJar** [microsoft/coe-starter-kit#7187]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When trying to set up template catalogue the required prerequisite flows just hangs and never finish, even though they have been rund earlier

### Expected Behavior

They should be detecetd as ran during set-up

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.10

### What app or flow are you having the issue with?

Admin | Sync Template v3 Configure Emails

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Start the template catalogue fraom setup-wizard, more features

AB#1534

**Comment by shrikant-singh31** [comment]
Hi @KjetilJar, can you please share the screenshot of the issue that you are describing?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
