### ISSUE TITLE
[CoE Starter Kit - QUESTION] - Governance Components Permissions Requirements

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#7192]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What permissions are required for end users to interact with the Orphaned Object flows and Inactivity Flows?  

Wouldn't the approval processes be in that CoE environment?

Would every user need to have the role of "Approvals User" in that CoE environment?

Are there any other dependencies we should be aware of?

The reason I am asking these questions is we have the Starter Kit installed in a different CoE environment that no one in the organization has access to.   

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Sept 2023

### What app or flow are you having the issue with?

Goverance Components for Orphaned Objects and Inactivity

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1542

**Comment by RahulBojji** [comment]
@robertcaretta Can you please confirm if the end users trying to interact with the Orphaned Object flows and Inactivity Flows are part of the environment where COE kit is installed??

If not, please add those users to COE environment and add roles as required.

**Comment by RahulBojji** [comment]
@robertcaretta 

For end users to access these inactivity resources, they need to be added as users to that environment where COE kit is installed with a Maker SR.
All those apps will need to be shared with Maker SR. 

Please have a look at the below documentation
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users

<img width="441" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/175f4bc1-7cb1-4315-8eb7-b3e6a0f7d319">

Whenever a maker record gets created in the maker table, a flow "**Admin | Add Maker to Group**" kicks in and add the maker to the maker security group. 

For approvals, the product grants end users the "approval SR" automatically when they get assigned an approval.

**Comment by robertcaretta** [comment]
So just to confirm, if they have Maker SR (Security Role) they would also be able to create flows and other items in that environment? Is that correct?

I also found [this article](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#grant-makers-environment-access) which mentions NOT having a security group protect the environment that the CoE is in.  _This doesn't seem like a great design for protecting the CoE environment._   

What if we didn't use the Apps, and just used the Flows?
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#grant-makers-environment-access

What I am struggling with is how to take advantage of these CoE resources while still protecting the environment from users just creating stuff there. We currently have a security group protecting access. I also wouldn't want that to show up in the Environment drop-down panel inside of make.powerautomate.com.

**Comment by RahulBojji** [comment]
@robertcaretta 
**I also found [this article](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#grant-makers-environment-access) which mentions NOT having a security group protect the environment that the CoE is in. This doesn't seem like a great design for protecting the CoE environment.**

Regarding above, we are recommending not to use security group here as in below image, the reason being it overrides the security role behaviour

![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/c34a8ef0-caae-4da6-aeaf-b706fd0e80fc)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
