### ISSUE TITLE
All the mda apps in our tenant is getting marked as deleted in powerapp app table

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#7194]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

All the MDA app record for default environment is marked as deleted in powerapp app table.
And most of the mda app of other environment is also marked as deleted.

### Expected Behavior

It should have marked only those mda as deleted that were actually deleted and not all.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1546

**Comment by Jenefer-Monroe** [comment]
Does the identity running the flow have the Power Platform Admin Role permanently and directly assigned? 
Note that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management), this won't be sufficient to run the CoE Starter Kit.
For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by Rajatchopra3** [comment]
yes the identity has permanent pim, and the flow has been assigned per flow license as well

**Comment by Jenefer-Monroe** [comment]
Please go to the most recent run of Admin | Sync Template v3 (Model Driven Apps), Is it on, and has it been running daily? 

Find the Default environment (you can add columns to add the display name to find it) and click on the time stamp to open the run. You may need to go to "all runs" to find it
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/94d94fea-ffda-4556-a474-52451ffd9afa)

Then look at this call, do you see all the apps listed in the output?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/11f91826-04f8-46a6-b0ba-2639c28dfce4)

**Comment by Jenefer-Monroe** [comment]
Then do the same for this flow: **_CLEANUP HELPER - Check Deleted (Model Driven Apps)_**
This time you need to look for the "Name" which for default looks like as shown below
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cfbbeff6-95d1-4f2a-99a2-31b33c1f6b5b)

Are they returned here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/19c0f380-f94f-4872-80c0-8bf30a7366cb)

**Comment by Rajatchopra3** [comment]
Hi,
1. we can only find 698 records of model driven app for default environment in Admin | Sync Template v3 (Model Driven Apps), When we checked there are many model driven app of default environment whose record does not exist in PowerApps app table and list model driven apps action output, but they do exist.
2. Yes all the 698 records are returned in second flow.

**Comment by Jenefer-Monroe** [comment]
sorry it sounds like both the flows are returning all the mdas in that call, is that what you are saying?

**Comment by Rajatchopra3** [comment]
The model driven app returned in output of the **list model driven app action of Admin | Sync Template v3 (Model Driven Apps)**
are also getting returned in the output of **get this envs MDAs from appmodules action of CLEANUP HELPER - Check Deleted (Model Driven Apps)**
as you asked to check

But when we took some random app id from the output of the above action, it was marked as deleted in powerapps app table though it exist and is not deleted, but still coe is marking it as deleted

**Comment by Jenefer-Monroe** [comment]
closing out as no further action in starter kit team
