### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inventory new columns explained

### ISSUE THREAD

**Issue by iharabagiu** [microsoft/coe-starter-kit#7198]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have looked upon the data inventory and trying to understand some of the columns in the custom tables. There are some columns that I either don't understand what store or how they were populated and I couldn't find any other documentation on them:

**Environments**
Governance Protection Level - How is this calculated/added?
MS Teams URL / MS Teams ID - Would this be the URL of the Teams channel attached to a Dataverse for Teams environment? Would this be populated only for new environments in case the inventory was made with an earlier version of the CoE Starter Kit?

**Apps**
App Complexity score/Description - how are these calculated? Are they depending on the other columns I have seen - appDocumentComplexity?
Avg Rating - what should this column show?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Inventory

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1586

**Comment by RahulBojji** [comment]
@iharabagiu 

1. **Avg Rating** - Here is the formula for calculating Avg Rating 
<img width="959" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/33734139-eed7-4597-b7dd-fd01b5cdd23f">

It is a roll-up field, it automatically calculates values by taking average of rating column present in the **app catalog feedback** table for every 12 or 24 hrs depending on the timespan we set in the environment.
2. **Governance Protection Level** - This field is used to identify the protection level for an environment.
   For Managed Environment it will be **Standard** and for others it will be **Basic**
3. **MS Teams Id/ Teams URL** - This will store teams id and teams URL for Dataverse team's environment, these values will be populated when an environment is created/modified in the **Environment** table. Right now, these fields are not getting populated as expected and we have a [bug](https://github.com/microsoft/coe-starter-kit/issues/7199)created for the same.
4. **App Complexity Score** - For this please have a look at #6014, #7140

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
