### ISSUE TITLE
[CoE Starter Kit - QUESTION] Discrepancy between tables being populated between Data Export vs. Cloud Flows

### ISSUE THREAD

**Issue by abhijkumar-msft** [microsoft/coe-starter-kit#7208]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

This question just arose from our client:

Also, on the question related to the audit log. I’ve noticed that in the CoE which we have set up with cloud flows the dbo.admin_auditlog table is getting properly populated, but in the CoE with the data export version it’s not populating the table at all. Could you please help with identifying if there’s a config I’m missing?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.7 (June Version)

### What method are you using to get inventory and telemetry?

Data Export

AB#1623

**Comment by Jenefer-Monroe** [comment]
Thats correct. We do not store this data in the Data Export solution. Instead we calculate usage and store only that data. 
You can still run the audit logs solution if you would like to have the raw data as well.
