### ISSUE TITLE
COE starter kit Byodl - dataflow refresh error

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#7211]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are testing the coe starter byodl version for production tenant, 
we are getting dataflow refresh error , the publish was successful.

Error Code: Challenge Error, Error Details: Data source credentials are missing or invalid. Please update the connection credentials in settings, and try again. (Request ID: af5126a9-8a98-41f5-af55-ac82c3f3fff1).
<img width="799" alt="refresh error" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/3be6a77b-1a93-4d89-9f59-f0f3f3c69a8b">

The id running the whole process has permanent pim access and has system admin access as well in the environment.
have followed the msft document step by step. all the access is provided to the id.
Have rasied msft ticket as well, they are saying it might be a Coe starter kit issue. 

Is it possible that as our tenant is large, the dataflow might be hitting some limits behind the scene. Please help

### Expected Behavior

Should refresh successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Coe byodl makers dataflow

### What method are you using to get inventory and telemetry?

Data Export

AB#1626

**Comment by Jenefer-Monroe** [comment]
Likely you did not update the credentials in the dataflow. 
The setup wizard will tell you when to do this step. Please follow these instructions at that time: [Configure connections to data sources](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#configure-connections-to-data-sources)

**Comment by Rajatchopra3** [comment]
attaching the screenshot, there is no error, connections are proper, publish is successful, it throws error while refreshing.
followed all the steps as per the above documentation, as well followed set up wizard.
<img width="311" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/65c1c22c-82fa-427a-971e-091d49cc5925">
<img width="785" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/aef5e6ed-1bcb-480a-8406-f7021a6058d0">
<img width="784" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/0a861345-2a21-4632-8160-7055be9bb1e3">

**Comment by Jenefer-Monroe** [comment]
Can you see what error you get in the dataflow refresh?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6b0329da-bfff-406a-b679-a08d79aca6bd)

Is is that same error about the bad connection?

**Comment by Jenefer-Monroe** [comment]
I'm afraid this is not an issue with our kit but with your credentials or your tenant. I presume its a configuration issue, like perhaps you did not enter the variables correctly, but that is difficult to debug remotely. 

Issues I've seen people hit:
1. Only updating either DatalakeURL or EnvironmentAPI but not both
2. Selecting the wrong thing [Azure Storage Account URL](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#copy-azure-storage-account-url) for the DatalakeURL. I've seen people select the blob service for example.\
3. Forgetting to append /powerplatform to the URL for the DatalakeURL
4. Pasting the wrong URL and not the API one for EnvironmentAPI. See [Copy Environment Web API endpoint](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#copy-environment-web-api-endpoint)

**Comment by Rajatchopra3** [comment]
Only updating either DatalakeURL or EnvironmentAPI but not both - ** checked Updated both**
Selecting the wrong thing [Azure Storage Account URL](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#copy-azure-storage-account-url) for the DatalakeURL. I've seen people select the blob service for example.\ - **Checked selected the right url**
Forgetting to append /powerplatform to the URL for the DatalakeURL - **checked appended /powerplatform**
Pasting the wrong URL and not the API one for EnvironmentAPI. See [Copy Environment Web API endpoint](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#copy-environment-web-api-endpoint) - **Checked copied the right endpoint**

for all the above points have provided the correct value, The Id has storage blob data reader and owner access as well, I am not sure what more can I check.

**Comment by Jenefer-Monroe** [comment]
If you go look at the connections in the environment, are their broken ones? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb8cc099-51a4-4075-9d23-cdd8616b3986)

**Comment by Rajatchopra3** [comment]
Is it compulsory to have Power BI Premium per user or per capacity (if using [Data Export] for inventory) or powerbi pro will work ?

**Comment by Jenefer-Monroe** [comment]
You PBI license should not impact the dataflows running, no.

**Comment by Jenefer-Monroe** [comment]
OK I'm afraid I'm stuck then. The error message is in the product connection itself, not in the kits usage.

**Comment by Jenefer-Monroe** [comment]
Please go back to the previous screen and touch every Query, wait till it resolves and shows data, then touch the next one. Perhaps you missed a connection? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/745218e3-3080-4349-8d01-0fdb740a75fa)

**Comment by Rajatchopra3** [comment]
No error
<img width="213" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/bd3d8395-4086-4317-ac41-ed5b219efce7">

**Comment by Jenefer-Monroe** [comment]
And you touched all of those queries? (Makers, App Makers, Environment Makers, etc)
I believe Combined Makers is the last one but making sure you touch each to see if there are missing connections.

**Comment by Rajatchopra3** [comment]
Thank you for your inputs, working now

**Comment by Jenefer-Monroe** [comment]
oh wonderful. Thank you so much for letting me know!
