### ISSUE TITLE
[CoE Starter Kit - BUG] prd dashboard - Connectors deep dive - missing connectors used in flows

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#7214]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,

not all Connecotors which are currently used in Flows are shown in the prd Dashobard in Connecotor deep dive 

### Expected Behavior

All used Connectors should be shown

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October

### What app or flow are you having the issue with?

Production_CoEDashboard_October2023

### What method are you using to get inventory and telemetry?

None

### Anything else?

Because the Data is there and also correct, I had a look into the relations
When i switch this from Single to Both
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/01474e99-2850-49d0-abfb-6bef627397b7)
Several additional Connectors appear

AB#1629

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. To consider for the next release.
