### ISSUE TITLE
Inactivity notifications v2 (Clean Up and Delete) not working as expected

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#7216]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi. I have a question regarding this flow and a setting that we do not understand.
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/6414d899-55d2-46ca-b41a-d98f93f432cd)
In the flow the step "List Canvas Apps ready to delete" filters the Approval response date for a value that is LESS THAN the "Get past time for archivals ready to delete" value which is hard coded to 3 weeks. 
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/7687cddc-f00a-42b0-812d-2cc75700381e)
Should this value not be Greater Than? In the documentation it states "Deletes the flows and apps that were approved for deletion more than three weeks ago (configurable)." 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/governance-components#admin--inactivity-notifications-clean-up-and-delete
Also the configurable aspect. If we changed that it would create a layer.

The reason we are asking this is because we find that it is not deleting apps and flows on a regular basis.

Apologies if I have missed something here.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

October 2023

### What app or flow are you having the issue with?

Inactivity notifications v2 (Clean Up and Delete)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1632

**Comment by Jenefer-Monroe** [comment]
You're right, its not configurable via an env var, that must have been an oversite in our documentation. We do intend to make it configurable but have not been able to fund that yet. 

The less than is correct.
If it ran today, 
   Today: 12/1/2023
   3 weeks ago: 11/10/2023

Something approved last week
  Approved 11/24/2023
  Approved NOT lt 3 weeks ago, so do not yet delete

Something approved early Nov
  Approved 11/7/2023
  Approved lt 3 weeks ago, so go ahead and delete

Hope that makes sense!
