### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE Checking subscription leads to notification: The permission set () sent in the request does not include the expected permission.

### ISSUE THREAD

**Issue by Jurgenkula** [microsoft/coe-starter-kit#7217]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

1. Open CoE Admin Command Center.
2. Select CoE Flows from the left menu
3. Select Admin | Audit Logs | Office 365 Management API Subscription flow and click Turn on
4. When flow is turned on, switch to another browser tab from where you opened this app and select Solutions > Center of Excellence - Core Components
5. Click Run
6. Provide value start for the Operation parameter and click Run flow
7. This flow will start the Office 365 Management API subscribtion for the tenant to allow calls to be made against the API. Verify that flow runs successfully. It should take only few seconds to complete

The flow has run successfully. However, if you zoom in on the flow, the http task in the flow is not executed correctly and the following message appears: The permission set () sent in the request does not include the expected permission. Instead of that the subscription is retrieved/checked with this task.

### Expected Behavior

Flow runs successfully. Subscription has been checked.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open CoE Admin Command Center.
2. Select CoE Flows from the left menu
3. Select Admin | Audit Logs | Office 365 Management API Subscription flow and click Turn on
4. When flow is turned on, switch to another browser tab from where you opened this app and select Solutions > Center of Excellence - Core Components
5. Click Run
6. Provide value start for the Operation parameter and click Run flow
7. This flow will start the Office 365 Management API subscribtion for the tenant to allow calls to be made against the API. Verify that flow runs successfully. It should take only few seconds to complete

### Anything else?

How is it possible that audit data is still retrieved despite the error message on the subscription?
Are these overviews perhaps not retrieved via the subscription?
An empty overview is shown for the overview of Power Automate Desktop Flows and Virtual Agents. Is the audit data retrieved via the subscription or is this separate from the subscription problem?

[CoE Starter Kit - BUG ISSUE Checking subscription leads to notification- The permission set - sent in the request does not include the expected permission.docx](https://github.com/microsoft/coe-starter-kit/files/13527147/CoE.Starter.Kit.-.BUG.ISSUE.Checking.subscription.leads.to.notification-.The.permission.set.-.sent.in.the.request.does.not.include.the.expected.permission.docx)

For clarification of the problem, see the screenshots in the attachment.

AB#1633

**Comment by Jenefer-Monroe** [comment]
It could be that someone else started the subscription elsewhere. 
Are you storing the app registration secret in plain text or in Azure Key Vault?

**Comment by Jurgenkula** [comment]
Hi Jenefer,

The subscription flow that is started on the environment is not started elsewhere, I can strongly confirm that.
For now we have the app registration secret in a plain text field.
One of the points that we still have to address is to put this in an Azure KeyVault.
Even though the secret is not yet in the Azure KeyVault, this should work, right?
I assume that logic has been built into the CoE in which variable the secret is present, either the plain text or Azure KeyVault.

Regards
Jürgen Kula



________________________________
Van: Jenefer Monroe ***@***.***>
Verzonden: vrijdag 1 december 2023 19:45
Aan: microsoft/coe-starter-kit ***@***.***>
CC: Jurgenkula ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE Checking subscription leads to notification: The permission set () sent in the request does not include the expected permission. (Issue #7217)


It could be that someone else started the subscription elsewhere.
Are you storing the app registration secret in plain text or in Azure Key Vault?

**Comment by Jurgenkula** [comment]
Hi Jenefer,

Open the last attempted run for Admin | Audit Logs | Office 365 Management API Subscription
Is the app id correctly ingested here? It should be the GUID of the app.

image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/97eee119-aae8-4b4e-95f4-2f5e6bd49feb>


Answer: (theAppID = Client ID)


[cid:f03be268-db45-4f68-8721-a6dda3c9724c]


Is the secret correctly ingested here? This should be a secret and not a GUID. This is a common mistake so please do take a look and let me know.

image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/9783b8d9-4ddb-40d7-928f-eeeeb9c1145a>


Answer:  (theTextSecret = Value scret)


[cid:6351c64f-c47a-4c1f-b997-69541a4e0ffc]


Does this call fail hence correctly marking the variable as false?

image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/0da62240-6cef-42b5-96fd-6b8bea57cb48>


Answer:


[cid:053dc0ba-e582-4b87-b202-3b39caea94a1]


As additional information. We have a development-, test- and production-environment. On the development, we only perform the installation without running the CoE Setup and Upgrade Wizard. We only run the CoE Setup and Upgrade Wizard on the Test- and Production-environment. For the Test- and Production-environment, we have created two separate App-registrations, namely:

- CZ-PowerPlatform-LowCode-Test-Microsoft 365 Audit Log
- CZ-PowerPlatform-LowCode-Prod-Microsoft 365 Audit Log.

As additional information. We have a development-, test- and production-environment. On the development, we only perform the installation without running the CoE Setup and Upgrade Wizard. We only run the CoE Setup and Upgrade Wizard on the Test- and Production-environment. For the Test- and Production-environment, we have created two separate App-registrations, namely:
- CZ-PowerPlatform-LowCode-Test-Microsoft 365 Audit Log
- CZ-PowerPlatform-LowCode-Prod-Microsoft 365 Audit Log.

De App-registraties hebben delegated permission op Microsoft Graph (User.Read) en Office 365 Management APIs (ActivityFeed.Read).

The clientID and ClientSecret are now populated in the variable. The ClientSecret as mentioned in the plaintext variable instead of the AzureKeyVault variable.
Actions for the App registration.


Create Azure AD App Registration for Office 365 Management API operations

To collect usage information, such as app launches and unique users per app, you must have access to an Azure app registration. The app registrations needs to have permissions to read data from the Microsoft 365 audit log to complete the setup. You only need this app registration if you are using Cloud flows for inventory.

Action.

  *   Move to the browser session where you are logged in as Global Admin and browse to https://entra.microsoft.com <https://entra.microsoft.com/> (Opens in new window or tab)<https://entra.microsoft.com/>.
  *   Go to the Applications > App registration.

[cid:921e9e3d-9ef0-48f1-a72c-165b79ae9761]



  *   Open and click New registration.



[cid:21dd3d2a-e7f4-422f-b292-6f4b93c59c12]



  *   Enter a name Office 365 Management API but don't change any other setting. Click Register.



[cid:f9237f61-83e6-401a-a729-91c9332e2fc7]



  *   Enter a Select API Permissions > + Add a permission



[cid:0d797175-c43a-4935-89da-139afd27cb59]



  *   Select Office 365 Management APIs



[cid:51c0a4db-3844-447c-b6a3-b0d4afd2541e]



  *   Select following permissions:



[cid:ecf966f1-b2f9-4b94-b8ee-f67c158f206a]



  *   Click Grant Admin Consent for (your organization). This sends a request for approval to the Global Admin if the Global Admin consents, then the API Permissions will be granted. It is best to ask the Global admin for permissions via Teams or another channel.



[cid:0fc6805e-3ea1-4531-98cd-8c50163551df]

  *   Select Certificates and secrets > + New client secret



[cid:096a7c79-4eb9-4c91-93b3-dbb4aab00f4b]



  *   Go to Overview page and copy Application ID to notepad



[cid:ed2ae172-dd53-4442-87da-4b39f5288bc1]

  *   Now you should have Client ID and Secret copied to notepad matching your environment values



[cid:77be4e8a-30a7-4a4d-8169-1f60843c199b]


Regards
Jürgen Kula
________________________________
Van: Jenefer Monroe ***@***.***>
Verzonden: maandag 4 december 2023 14:09
Aan: microsoft/coe-starter-kit ***@***.***>
CC: Jurgenkula ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] ISSUE Checking subscription leads to notification: The permission set () sent in the request does not include the expected permission. (Issue #7217)


Thats correct, it just changes what questions I ask :)

Open the last attempted run for Admin | Audit Logs | Office 365 Management API Subscription
Is the app id correctly ingested here? It should be the GUID of the app.
image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/97eee119-aae8-4b4e-95f4-2f5e6bd49feb>
Is the secret correctly ingested here? This should be a secret and not a GUID. This is a common mistake so please do take a look and let me know.
image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/9783b8d9-4ddb-40d7-928f-eeeeb9c1145a>
Does this call fail hence correctly marking the variable as false?
image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/0da62240-6cef-42b5-96fd-6b8bea57cb48>

**Comment by Jenefer-Monroe** [comment]
It is application permissions that are needed. [Create an Azure AD app registration for the Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#create-an-azure-ad-app-registration-for-the-office-365-management-api)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/94956198-3f84-4870-9968-494eb4ce0cb0)

**Comment by PPMini** [comment]
Hi Jenefer, 

The problem with Kula and team is that the organization does not allow to use Applications permissions to connect to office 365 custom connector. The team needs to understand how safe it is to use Application permission options to connect to custom connector. Any guidance you can provide here?
