### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION Grammatical errors?

### ISSUE THREAD

**Issue by Idrilka** [microsoft/coe-starter-kit#7218]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Why have the Customized Email's subject been changed to something that's grammatically incorrect?  'Can we delete?' sounds like written by someone doesn't speak English and I'd consider getting such email as phishing. Not to mention that there is no such word as 'audiance' (per 'Target Audiance' column in Customized Email table. I appreciate it's backend stuff but surely it's a solution written by professionals...

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Sep 2023

### What app or flow are you having the issue with?

Inactivity Processes

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1634

**Comment by Jenefer-Monroe** [comment]
Hello. Please keep in mine that we are a very small 2 person team developing and supporting the entire kit. So a little patience and kindness would be appreciated. 

Also keep in mind that mails are configurable in the Command Center. 

That said, if you can please list specifically which emails you are seeing errors in, and the errors we can try to fix those up.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
