### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION Troubleshooting the search issue in the CoE Admin View

### ISSUE THREAD

**Issue by narumikato** [microsoft/coe-starter-kit#7223]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

As the title says, my client has a problem that some apps do not show up in the search results when they search for them in the CoE Admin View. Also, the language of the environment is English, but the apps contain two-byte characters like Japanese. I have confirmed that the Dataverse search in the environment is ON. I have also confirmed that the app synchronization Automation flow is ON.

Is there any other setting required besides the Dataverse search in the environment?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Oct2022

### What app or flow are you having the issue with?

Admin | Sync Template 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1642

**Comment by Jenefer-Monroe** [comment]
Hello. Can you confirm, is your Core version 3.53? 
I'm having a little trouble following, can you please share a screenshot of what you are doing? It sounds like you are just using the MDA search features of the views. Is that what you are doing?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
