### ISSUE TITLE
[CoE Starter Kit - QUESTION] Change Owner of solution flow

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#7224]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

we have identified several orphaned flows.
For the most of them, we could assign an owner with the flow permission app.
But for solution flows we assign a new owner through the product ux
<img width="335" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113470539/674dd940-fd05-4763-8d8a-e81a2b9f622e">
Now that we have changed the owner of these solution flows, how do we get these information transferred to the CoESK?
Because there the flows still have the "old" owner and are marked as orphaned?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1648

**Comment by Jenefer-Monroe** [comment]
Hello, we have not yet updated the kit to use this information but it is on our backlog. We are waiting for one more product change and then will fund this work. Please see https://github.com/microsoft/coe-starter-kit/issues/3052
