### ISSUE TITLE
[CoE Starter Kit - QUESTION] cannot save keyvault variable 

### ISSUE THREAD

**Issue by crowdedLeopard** [microsoft/coe-starter-kit#7225]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello - we are trying to enable the new audit log solution using a keyvault stored secret. When we try to update the secret  we get the error  "could not verify the user permission on < xxxx / xxxx / xxxx >  make sure that the Power Platform Provider is registered in the Azure Subscription"  - -- does this suggest the our app registration needs to have access to where the KV is stored

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#1649

**Comment by RahulBojji** [comment]
@crowdedLeopard Please have a look into this issue #6172, #6473, #7183

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
