### ISSUE TITLE
COE flows failing.

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#7227]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

 
We have flows failing in our COE. The error says: Insufficient privileges to complete the operation.

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/341e68f6-22fe-429d-ab70-4647347405a5)

 
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/cda3f311-d2d0-45b5-bdbb-82a50568a1ed)

We are using A1 account with admin privileges.
Need you help here.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

None

AB#1651

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
