### ISSUE TITLE
Admin | Sync Template v3 (Flow Action Details) runs but flow actions aren't added to the table

### ISSUE THREAD

**Issue by S0URCEC0D3** [microsoft/coe-starter-kit#7228]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When the Admin | Sync Template v3 (Flow Action Details) runs, it runs successfully, but nothing is getting added to the flow actions dataverse table. 

### Expected Behavior

Admin | Sync Template v3 (Flow Action Details) should grab the flow action details for all flows and add them to the dataverse table. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details) 

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1 - Re-run flow 
2 - Check table for new flow actions 
3 - Confirm flow in edit designer and it has multiple actions
4 - Table does not reflect these actions

AB#1672

**Comment by Jenefer-Monroe** [comment]
This flow runs per environment for flows that are flagged as modified in the inventory. 
So you might not expect to see the changes in the table that same day.

Can you confirm, there is data being written to the table, you just arent seeing this update right after you edit a flow?

**Comment by S0URCEC0D3** [comment]
Hi Jenefer, there is data in the table, just not the updated one. how do I get it to get that data on a daily basis?

**Comment by Jenefer-Monroe** [comment]
Each day you will get the fact that the flow itself was edited updated in inventory. 
So you made that change, the Driver flow runs, you will see the flow has been updated (with the flow modified date field) in the inventory
Then likely the next day this will get picked up by flow action details when the Driver flow runs. 

I hope that makes sense.

**Comment by S0URCEC0D3** [comment]
makes sense, can I keep this thread opened until I confirm tomorrow that the flow actions are now showing for this flow I'm testing with?

**Comment by Jenefer-Monroe** [comment]
yes of course! Thanks for checking for me!

**Comment by S0URCEC0D3** [comment]
I went into the app and the 'Flow Modified On' column did not change.

**Comment by Jenefer-Monroe** [comment]
We wont explore that audit logs failure here, we need to keep our issues to one at a time, do feel free to post it separately though.

**Comment by Jenefer-Monroe** [comment]
Can you open your test flow and validate that the changes are in there? 
Then look at what the product says is the last modified date. Compare with what the inventory says is the last modified date.

**Comment by S0URCEC0D3** [comment]
Ok I'll take a look and get back to you.

**Comment by S0URCEC0D3** [comment]
Hi Jenefer, so now i see the flow in the Admin Command Center with the modified date, but still can't see the Flow Action Details for this flow. Also I checked on the Admin | Sync Template v4 (Flows) for the last run on the env where the flow resides and under the 'List Flows as Admin (V2) action' output, the flow doesn't exist.

**Comment by Jenefer-Monroe** [comment]
ok if you arent reliably getting the flows listed here then you wont be able to know that you are getting them elsewhere either. 

This is usually due to a permissions issue or due to unmanaged layers breaking the behavior of the flow. 
Can you please share a screenshot like this showing the roles of the identity running the flow? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7e1b6ea7-d8a3-4d10-b8cd-91758c51e502)

**Comment by S0URCEC0D3** [comment]
I didn't find any unmanaged layers, and the service account used for the CoE has full power platform administrator, fabric administrator, dynamics 265 administrator and security reader roles. I can't paste the screenshot as this is my work account.

**Comment by S0URCEC0D3** [comment]
it has the same as yours but with a start time of 3/9/2022 11:09:25am

**Comment by Jenefer-Monroe** [comment]
Go to the environment of the flow you are testing with in the power platform admin center > Settings > Users + permissions > Users
Find the user that is running the flows > Check their permissions.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/48a528d4-542c-45d9-8062-2dd94e5346bd)

**Comment by Jenefer-Monroe** [comment]
ok i'm not sure how to assist you here remotely. The fact that you are not always returning all flows from that call indicates there is something wrong with your permissions. And the fact that it returns it sometimes but not always indicates the permissions are assigned via PIM which we do not support. But you report the role is assigned permanently.
I'm just not sure how to proceed.

**Comment by S0URCEC0D3** [comment]
ok I appreciate your help on this. If I find a solution, I'll post it here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
