### ISSUE TITLE
[AA4AM] Canvas app should check for dependent pipelines

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#723]
When a user configures an azdo org/proj/repo, we should do some sort of basic validation that the azdo project has been configured with the prerequisite pipelines.  If it hasn't we should provide the user an error message and point them to the documentation on how to get their azdo project configured.

**Comment by mikefactorial** [comment]
May want to consider incorporating the CoE CLI solution pipeline setup commands to the export solution pipeline to automatically create deployment pipelines first time a solution is exported from the AA4AM App

**Comment by mikefactorial** [comment]
Incorporated into #1118. Closing this issue
