### ISSUE TITLE
[CoE Starter Kit - BUG] : Deleted Custom Connectors are getting displayed in the POWER BI dashboard

### ISSUE THREAD

**Issue by JPRRao** [microsoft/coe-starter-kit#7230]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Deleted Custom connectors are getting displayed in the Custom Connector tab of POwer BI COE Dashboard. Upon further investigation, it appears that the "Deleted" flags are not getting synced. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Power BI - COE Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Create an Customer Connector and publish.
2. Delete it 
3. Wait for the sync flows to run. 
4. Once run successfully check if the "Is Deleted" flag set to "True". In our current environment it is "False" . 

AB#1687

**Comment by Jenefer-Monroe** [comment]
Checking for deleted objects is done by this flow and its child flows: CLEANUP - Admin | Sync Template v3 (Check Deleted)
It is a long running flow and so only runs every other week. 
Can you please run that and see if it marks for you?
