### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Audit Logs | Sync Audit Logs (V2)

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#7231]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi, I have received an email for a Performance Alert for  Admin | Audit Logs | Sync Audit Logs (V2)
Your flow may be performing slow because it's running more actions than expected. Your flow will be turned off in 7 days if it does not use fewer actions.
When I look at the flow runs this has been running since the 28th November every hour, are you able to confirm if this is expected behaviour and if there is any action I should take? Should I just continue to let the Flow run?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4,17

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1689

**Comment by Jenefer-Monroe** [comment]
Yes that is expected, it runs hourly in order to not miss launches for large. 
If the usage is too high for your tenant and hence the API count too high, you may want to add a Process License for it.
Please see https://learn.microsoft.com/power-platform/admin/power-automate-licensing/types

**Comment by Alyson95170** [comment]
Thanks Jennifer I will look at changing the license for this account.  Is it normally for the flow to be running for 3 days, I have multiple and they all seem to get to LoopContentIDS and not process further
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/1ee7ad0f-33d0-42f5-bf79-db5276d47273)

**Comment by Jenefer-Monroe** [comment]
No that is not normal. I presume this is because you are being throttled. I'm not sure if I can do anything here aside from you getting a license to not be throttled. 

Note that the Data Export technique to gather inventory does not use this technique so for large organizations that may also be the approach that is required.

**Comment by Alyson95170** [comment]
Thanks Jenefer

**Comment by Jenefer-Monroe** [comment]
Sorry I dont have better advice here. There are a few orgs that have asked about the high API count and so we do plan to investigate but it wont be for the next release due to competing priorities

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team

**Comment by Jenefer-Monroe** [comment]
I have a new theory today that this is due to throttling of the backend when we try to update the app with last-launched. 
I'm exploring a fix through https://github.com/microsoft/coe-starter-kit/issues/7240, please monitor!
