### ISSUE TITLE
[CoE Starter Kit - QUESTION] Any updates on "Flow Last Run ON"? 

### ISSUE THREAD

**Issue by kimjensen90** [microsoft/coe-starter-kit#7232]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team, 

You have previously told us that the product team was working to get the "Flow Last Run ON" (ref: https://github.com/microsoft/coe-starter-kit/issues/6670) 

In September it wasn't there, but it seems to be available through the admin center now: 
![image](https://github.com/microsoft/coe-starter-kit/assets/104207653/6e6c526e-0f13-4e99-acfd-844efb3f4441)

Are you working on adding the data to the CoE Starter Kit Admin View? If so, when can we expect to have it? 

Thank you so much for all your work on this! 

/Kim

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2023

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1690

**Comment by kimjensen90** [comment]
Okay so if I switched from Cloud Flows to Data Export, I would get the data?

**Comment by Jenefer-Monroe** [comment]
You would get this data item (last run) in the CoE yes. 
Here is the feature which would make it available for cloud flow architecture as well. Its listed as in public preview but we have not seen it yet. We've sent a ping for an update. 
https://learn.microsoft.com/en-us/power-platform/release-plan/2023wave2/power-automate/store-cloud-execution-history-dataverse

**Comment by kimjensen90** [comment]
Alright. Thank you so much for the answer. 

Do I get better data by using the Data Flows in general?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
