### ISSUE TITLE
CoE Admin Command Center - Save button not working in CoE Configuration

### ISSUE THREAD

**Issue by avinkaur1** [microsoft/coe-starter-kit#7233]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the CoE Admin Command Center, when I am trying to edit the CoE configuration, like Customized emails, and Environment variables, the edits are not getting saved. Basically both Save and Cancel buttons are not working. Please check the Reproduction steps for the attachments.

### Expected Behavior

The configuration items should get saved.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Play the Coe Admin Command Center app in the Core Components
2. Go to CoE Configuration
3. Go to Customized emails
4. Try to edit any email like Send welcome email, and try to change a field, like Importance and click on SAVE.
5. The confirmation dialog opens up. When you click on save or cancel, both buttons don't work. The close window works.
![image](https://github.com/microsoft/coe-starter-kit/assets/52736218/c3e85984-a396-40f6-99c7-fc944b5e7538)

6. Similarly open Environment Variables and try to edit any environment variable value and click on save. the save does not happen. The window keeps open. Even Revert does not happen. Both buttons are not working. Only window close on top right side works and closes the window.

AB#1691

**Comment by Jenefer-Monroe** [comment]
We had another user hit this with this bug: https://github.com/microsoft/coe-starter-kit/issues/7145
Here was their resolution: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fd91e410-b96a-459b-a629-01ebf40d4cbb)

I dont know why some people are hitting this but it appears to be something wrong with the way the solution was published / packages. 

Please try to resolve with their fix.

**Comment by Jenefer-Monroe** [comment]
Thanks for this note!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team here. 
will use your notes when I go to try and fix that issues
