### ISSUE TITLE
[CoE Starter Kit - BUG] Service principal setup of CoE failures

### ISSUE THREAD

**Issue by AnkitaJaintme** [microsoft/coe-starter-kit#7235]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

On running initial setup in CoE Setup Wizard application, getting error for Office365GroupsListGroup for unsupported or invalid query

### Expected Behavior

Initial Setup should run if the flows are turned on and inventory flows are turned on
SetupWizard>GetCurrentEnvironment
SetupWizard>GetTenantID
SetupWizard>GetUserDetails

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1703

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot? This will help us zoom in to where you are experiencing the issue. 
Note that you need to be logged in to GitHub to share images, responding in email will not share any images with us.

**Comment by AnkitaJaintme** [comment]
It is commercial cloud
These flows are turned on

**Comment by Jenefer-Monroe** [comment]
Did they run when you loaded the app? If so did they pass?

**Comment by Jenefer-Monroe** [comment]
screenshots really help going forward. That way I dont have to go open flows to do the next step of the investigation.

**Comment by Jenefer-Monroe** [comment]
Do the connections for this flow all show healthy and owned by a sys admin in the CoE Envt? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9cc46e6d-3dcb-4744-9672-18405dc3fb37)

Go to the connections in the envt, do any show errors?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b9b0b0a1-1695-47db-bade-b4c08cd98e6d)

**Comment by AnkitaJaintme** [comment]
Error image:
![image](https://github.com/microsoft/coe-starter-kit/assets/153090065/99be1dc9-beed-46b0-aae4-4f41d4fa740a)

yes all the connections are healthy
![image](https://github.com/microsoft/coe-starter-kit/assets/153090065/b633231d-5227-4c00-8044-ed856cb2e5bf)

**Comment by Jenefer-Monroe** [comment]
Is there any more detail here? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0476cce8-1407-4f98-bebf-ed70b328cce1)

This is an out of the box connector so there appears to be something wrong with the identity running the flow.

**Comment by AnkitaJaintme** [comment]
No details there only status code with 403 with Header details
"statusCode": 403

**Comment by Jenefer-Monroe** [comment]
Are you logged in as this user whos name is behind the blue sqare?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4774bf63-2b3d-422b-8142-55d37820de9f)

**Comment by Jenefer-Monroe** [comment]
Oh ok thats it then. Service principals are not supported with the kit as many connectors we use, including the Dataverse connector, do not yet support them. 

Please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by Jenefer-Monroe** [comment]
Now that there is support for [service principal owned flows](https://learn.microsoft.com/power-automate/service-principal-support) this will probably come up more so marking as a documentation bug for us to make more explicit.
