### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Upgrade Failure

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#7236]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team, 

Even though we did remove the CenterofExcellenceCoreComponents_Upgrade and re-imported; however, still showing a failure. It looks like it's got to do with Office 365 Management API? Do we have an known issue around this?

![image](https://github.com/microsoft/coe-starter-kit/assets/100535041/f74896d3-5705-49a2-8226-864bfd0d475f)

Before we upgrade to the latest CoE version, other than checking if any customization has been made, is there any action items we need to take for O365 Management API dependency as well? 

Thanks. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Upgrade 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1705

**Comment by RahulBojji** [comment]
@iamjina 
 Please have a look at below issues
#6018 , #6270, #6816
