### ISSUE TITLE
[CoE Starter Kit - QUESTION] Mensagem para o gerente - Objetos Órfãos

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#7238]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Jenefer

Please, a manager received the email about orphaned objects with the following message: <p>Hello, there are Power Platform objects in your tenant whose owner has left the company and are therefore orphaned.</p><p> We have sent these objects to the old manager for those that are known, but there is a group for which we do not have a registered manager.</p><p>Clean them up through the Power Platform Admin View app from your CoE Starter Kit. < /p >

Is it ok for a manager who is not a CoE admin to receive the message: Clean them up through the Power Platform Admin View app in your CoE Starter Kit?

We are asking this because a manager received this message and had a problem, he stated that it was not clear what he should do and our IT director forced us to stop all emails until we validated all the messages that the CoE sends.

![CoE orfao](https://github.com/microsoft/coe-starter-kit/assets/129080740/afd4ca07-fa31-42f7-a1a7-f15034a6380b)

![CoE_ne](https://github.com/microsoft/coe-starter-kit/assets/129080740/4fa0201a-3a9d-448c-bcfb-6cea0e53d350)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Outubro 2023 4.15

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1707

**Comment by Jenefer-Monroe** [comment]
You can review all mails in the kit in the CoE Admin Command Center
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9d0c4438-1647-46c9-8ad1-924596ed6216)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bf8b7634-dba4-45d6-8633-15582d602b85)

From your screenshot it looks like it was editted in the past as it does not have the default subject line. Perhaps you added someone to the CC accidently, or the person that receieved the mail is a member of the group configured in the Admin eMail env variable, as I did just check and we are correctly sending this mail to the Admin persona

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0fab65d3-ef99-42ba-b7b8-858cb59f7f44)

**Comment by minobrega** [comment]
What I see here would be sent to the administrator of the Admin eMail variable, but it was sent to her manager according to the Maker table.

That was a mistake, right?

![Maker orfão](https://github.com/microsoft/coe-starter-kit/assets/129080740/5292e23b-b171-420f-b2ad-99cf1672727f)

![gestor do maker](https://github.com/microsoft/coe-starter-kit/assets/129080740/7f8e8c8c-6b72-4a49-8f28-db036d34ae23)

**Comment by minobrega** [comment]
Look at the variable Admin eMail email

![Variavel admin](https://github.com/microsoft/coe-starter-kit/assets/129080740/3c732664-6cc0-4a67-a1cc-52959a391511)

**Comment by Jenefer-Monroe** [comment]
Please go to the **_Request Orphaned Objects Reassigned (Parent)_** flow and make sure you see this correctly being send to the admin email
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/53a1a4d4-66b9-4166-ae4c-516d09d41a1c)

Then go to the Command Center and make sure you have not added anyone to CC
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fded689e-2c6b-48db-818a-fd287a1619b3)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0209e80d-f5f9-49f2-a091-1975208bd851)

**Comment by Jenefer-Monroe** [comment]
I'm not sure how this happened then. We only send this mail in this spot. If this person was ever the admin email perhaps you need to turn that flow off and back on to uncache the env var. 
Or perhaps you edited another mail to have this text? You can see the mails we target managers with in that same Command Center app. Look to see if those have been edited to have this text?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/71399a53-c0aa-4553-bc8a-d5ead95a68e3)

**Comment by minobrega** [comment]
I checked and this message would be for the ADMIN, there is no other email with this same message, I even looked at the administrator's email and this message is always forwarded to the administrator, but within 3 months the CoE is active, this email was sent to 2 Maker Managers mistakenly, which could be this error because these two managers were never in the Email Admin variable and still received this message.

![E-mail 1](https://github.com/microsoft/coe-starter-kit/assets/129080740/8d94a53d-eabe-4b81-b7fe-ede9103f7d29)

![Email 2](https://github.com/microsoft/coe-starter-kit/assets/129080740/fff773ce-3244-4552-9848-527a363d232a)

**Comment by Jenefer-Monroe** [comment]
What do you mean by forwarded to them? Was the email received to them as a forward?

**Comment by Jenefer-Monroe** [comment]
ok im not sure how to help then. Thats the only place we send that mail, and we only send to the admin contact in the list.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
