### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Ai Models) failing

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#7242]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

@Jenefer-Monroe,

We are getting few flows failing to get AI models data. Not sure what was the issue. The action below screen being retried multiple times (8) then get failed. 

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/1f10a920-0181-4c80-b58c-b124dd18a328)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Ai Models)

### What method are you using to get inventory and telemetry?

Data Export

AB#1711

**Comment by devvelegandla** [comment]
@Jenefer-Monroe  - This account got Power Platform admin role and not using the PIM.

**Comment by Jenefer-Monroe** [comment]
As the identity running the flow, go into the trigger statement you will see the environment instance url. Can you browse to that? 
![image](https://user-images.githubusercontent.com/89584709/205936150-0d27aa3d-776b-4eaa-b28c-8cff91d8b7b8.png)

**Comment by devvelegandla** [comment]
@Jenefer-Monroe , yes the account can open the environment instance URL.
