### ISSUE TITLE
[CoE Starter Kit - QUESTION] How can I customize my Welcome Email to have my organization header and stylesheet

### ISSUE THREAD

**Issue by avinkaur1** [microsoft/coe-starter-kit#7249]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I would like to send the welcome email to the users but with my Organization header and footer. I would like to add images and html tags. How can I do that?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

None

AB#1722

**Comment by v-bjaiswal** [comment]
For Customizing the Email you can use the "CoE Admin command center > Customized Emails".

![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/c23c7278-e878-4b89-a129-d8b824db5d95)

For using the CSS you can use the Environment variable like below:
1. Store the CSS like below in one of the Variable.
![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/53eea96c-5c83-4ba6-9583-c36079b0e04d)

2. And then we put those into the body of the Helper flow that sends all these mails.
![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/ba6cffdc-4652-408e-b5c6-406eb53c6eff)

3. After Updating the variable make sure you restart the helper flow to ensure the env vars dont cache.

**Comment by avinkaur1** [comment]
Hello,

Thank you very much for your reply. This resolves my query.

Regards,
Avin
