### ISSUE TITLE
[CoE Starter Kit - BUG] Desktop Flows sync flow fails at Parse RPA JSON step

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/coe-starter-kit#725]
### Describe the issue

Hello,

I'm opening this ticket with regards to the ticket #645 that was closed two weeks ago. We have an issue with Admin | Sync Template v3 (Desktop flows). An error has occurred that's very similar to the initial error I reported. Refer to the latest screenshot:

![Capture](https://user-images.githubusercontent.com/62425530/124160226-f3c8c180-da93-11eb-9858-40348043f7aa.JPG)

I believe this is a bug from what Jenefer mentioned in her comments.

### Expected Behavior

The flow should run without any error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

### Steps To Reproduce

Jenefer requested to edit the flow and post what's in the schema for the Parse RPA JSON section.

### Anything else?

Refer to the attached text file that contains the schema content.

[Schema content.txt](https://github.com/microsoft/coe-starter-kit/files/6749681/Schema.content.txt)

**Comment by JeneferM-MSFT** [comment]
Can you please open the flow for edit and capture what is in the schema as shown here:
![image](https://user-images.githubusercontent.com/62659043/122427511-67c08100-cf4e-11eb-8afc-a8718696864f.png)

**Comment by melmgcoe** [comment]
I added a text file to the new ticket with the schema capture. Here it is again in case you have issues downloading the file.

[Schema content.txt](https://github.com/microsoft/coe-starter-kit/files/6753217/Schema.content.txt)

**Comment by JeneferM-MSFT** [comment]
Your schema looks correct. Thats good. Can you please go to this step above and get me the download? Perhaps you have hit a new case with your data that we havent seem before. 

![image](https://user-images.githubusercontent.com/62659043/124275858-548de380-db00-11eb-8e84-85dd7318ce46.png)

**Comment by JeneferM-MSFT** [comment]
I believe we found another repro of this. There are some desktop flows getting returned with empty content now. We believe a fix is to add a condition checking for this. Please let us know if this seems to be the issue for you as well. I'm marking as LF for July assuming it is. 

![image](https://user-images.githubusercontent.com/62659043/124619368-d5691a00-de35-11eb-812a-ce4dbdb5a98f.png)

**Comment by JeneferM-MSFT** [comment]
Fixed in July release. 
Please install [the July release](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by melmgcoe** [comment]
Thanks for the update, and apologies I couldn't get back to you sooner. I'll get the latest release installed and come back to you if I see any further issues with this flow, hopefully not.
