### ISSUE TITLE
[CoE Starter Kit - QUESTION] Sync Audit Logs V2 fails to run with error : Get_Azure_Secret 

### ISSUE THREAD

**Issue by timrefw** [microsoft/coe-starter-kit#7250]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

This is a freshly installed instance of CoE in a new PP environment.

I had CoE running in the same tenant in a different PP environment that has since been deleted as it was out of date and upgrades were not behaving. 

I am using the plain text secret (for now) which used to work in my previous environment (July 2023 version) 

Admin | Audit Logs | Sync Audit Logs (V2) fails after approx 2 mins 40 seconds. 

Action 'Get_Azure_Secret' failed
Error occured while reading secret: Value cannot be null.
Parameter name: input

![image](https://github.com/microsoft/coe-starter-kit/assets/74019170/2f18d8df-0464-4d97-a0ab-27d8cdbc5202)

I am using the secret value and not secret ID
I have given Application Permissions in the App Registration - both Delegate and Application to rule that out

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

November 2023

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1723

**Comment by RahulBojji** [comment]
@timrefw This is as expected. 

Since you are storing secret as plain text value, using this action it retrieves the secret stored in the plain text environment variable

**Comment by RahulBojji** [comment]
@timrefw Thanks for sharing screenshots
Can you please also share run history screenshots of below actions? we are assuming that the flow might have failed here.

<img width="713" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/01b8136e-3296-40a7-9182-17551cfd320a">

<img width="840" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/f56c4254-b7b9-4ea8-b728-23fb0e1d5852">

**Comment by Jenefer-Monroe** [comment]
The reference to the azure secret is a misdirection. 
If you are not using Azure Key Vault to store the secret, then failure is expected and caught. 
Note that flow always shows the first failure there, even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

**Comment by Jenefer-Monroe** [comment]
You are int he correct place you need to open the scopes and drill in. 
The other person is failing here can you confirm that is where you are failing as well?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3b4d0c3b-9656-4252-92d1-a48b1bb7a198)

**Comment by Jenefer-Monroe** [comment]
thank you so much for letting me know!

**Comment by mdodwani** [comment]
@Jenefer-Monroe  I am facing similar issue with Admin|Audit Logs| Sync Audit Logs (V2).
I have updated COE tool kit with version 4.48.2 and Admin audit logs is failing 

![Image](https://github.com/user-attachments/assets/3c836391-d926-4764-b529-a8e0491f625a)

It seems like http action (ListAuditLogContent) is failing  due  to Client ID missing.

![Image](https://github.com/user-attachments/assets/8f33d8cf-b485-42e1-b85a-4139488736d7)

Please let me know how to fix this issue
