### ISSUE TITLE
COE Starter kit byodl version - dataflow (replaced by system step error)

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#7252]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can someone please explain, why I am getting this error. and how to resolve it
<img width="785" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/50023fee-1bfc-4ca9-aef9-27eb96505652">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Coe byodl Environment dataflow

### What method are you using to get inventory and telemetry?

Data Export

AB#1725

**Comment by Jenefer-Monroe** [comment]
Can you open the advanced editor and show me what you have?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0c287eaa-5767-4b29-8e11-0462047a7edd)

**Comment by Rajatchopra3** [comment]
<img width="707" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/0717348e-5af4-4e8b-b41a-c7eb18595f42">

**Comment by Rajatchopra3** [comment]
<img width="712" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/872cadf1-092f-4926-a8be-c9135069b416">

Dataflow - coe byodl Apps

24the and 26th step

**Comment by Jenefer-Monroe** [comment]
Did you use the setup wizard to get the CoE BYODL system Setup? 

Can you please go to the Maker query in that Dataflow, do you see a SYSTEM user? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3137fc8b-3dbc-40dc-a54e-b8061c4d42be)

**Comment by Rajatchopra3** [comment]
created a fresh environment, started the activity fresh, not getting the error. hence closing the ticket, thanks
