### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit log table not showing the correct Creation Time for entries

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#7254]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

On Dec 7, 2023, I was configuring Audit Logs using the HTTP connector in my Test environment.
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

My timezone is Eastern Standard Time and I have the November 2023 release of the COE kit installed.

I turned on "Admin | Audit Logs | Sync Audit Logs (V2)" and the flow ran successfully.
Start time was 4pm on Dec 7, 2023.
Duration was 15 minutes and 41 seconds.

I then went into the "Power Platform Admin View" app and looked under the "Audit Log" section.
(see the screenshot below for an example of a row I see)

I see that there are entries, but the entries are showing a "Creation Time" that was in the future.
(The day is correct, but the time definitely isn't correct - I ran the flow around 4pm and it is showing 8:49pm)

Why is it showing a creation time in the future?
And how can I get this fixed?

![audit-log-1](https://github.com/microsoft/coe-starter-kit/assets/128085471/162f6f3b-19f5-4f28-9142-5cc0a337fc47)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 2023

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1730

**Comment by Jenefer-Monroe** [comment]
Time zones across services are quite difficult. In the flow we set it to be whatever the backend sets as creationtime, which is in utc. I dont think this is behavior we can fix up unfortunately.

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/96431d72-c7b4-4ded-a600-0121d5c8a6c2)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
