### ISSUE TITLE
coe byodl maker dataflow (a lot of unknown display name in maker table)

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#7258]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have installed the coe starter kit byodl version 4.16 in our tenant in a fresh environment, the dataflow refresh is successful and we are getting the maker data in the table using the data export feature, In the maker table we are getting a lot of records with unknown display name. could you please see why we are not getting the display name and instead getting unknown.
<img width="818" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/07969f96-674e-4e6c-884b-1ca36e300a59">
<img width="758" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/4b1401e2-c6d8-4dae-ab1a-5e7b2155ada7">
Can 14th step of the query be the reason?

### Expected Behavior

The record should display the maker name in display column instead of unknown.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Coe byodl makers dataflow

### What method are you using to get inventory and telemetry?

Data Export

AB#1734

**Comment by nickmac88** [comment]
This has happened to me as well. Would be interesting to see why this is happening... Maybe termed users?

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of your dataflows page so that I can see its success rate and scheduled refreshes? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3fd0727-8021-4f5f-a45c-f7e2563d2e3f)

Then please also a screenshot from the command center showing these flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/198edb52-2e1e-4934-9218-949c08f0f93f)

**Comment by Rajatchopra3** [comment]
<img width="821" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/7afbd9fa-54fe-49e6-a46d-0f638df24091">
<img width="779" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/bf7483d2-a83c-414d-a49c-cf3267b3c3cd">
<img width="512" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/66a7a9a8-efb5-46a6-967c-cb80ab91e3e8">

**Comment by Jenefer-Monroe** [comment]
ok so one thing you need to fix is the next refresh on the dataflows. Only the Makers one should be set to have a next refresh, the rest should not. They are triggered by the follow up flows and having them run on their own can lead to failures. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bf6eae12-5a12-480e-8d05-7faff7764790)

So please have yours look like mine here: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/926ee068-eb1f-45ef-8ebd-b14a480c6704)

**Comment by Rajatchopra3** [comment]
1st suggestion done
While checking the flow error, all the 2778 records where the display name is Unknown. They are not found in the Power platform user table.
<img width="819" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/afc90a4a-2b36-4ddd-9a30-5fd0fcf69538">

**Comment by Rajatchopra3** [comment]
and due to two records that are failed the flow is failing
<img width="820" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/9418764d-74c4-4a10-8a7d-8f6d46f3f5e1">

**Comment by Rajatchopra3** [comment]
Coe version we are using - 4.16
<img width="463" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/430aeff7-13b5-49ad-b0b8-322010bbae4e">

<img width="505" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/2eb5c633-3c36-479e-9a40-964fae589c23">

**Comment by Rajatchopra3** [comment]
Maker dataflow refresh successful, the flow run also successful,  but still we are getting unknown records in maker table
<img width="767" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/0bbd672f-e69e-471f-9330-234d8fa6e494">

**Comment by Rajatchopra3** [comment]
So basically all 2785 unknown users are not found in power platform user table, therefore it is  not updating there display name.
<img width="734" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/187e3fdb-afbf-4280-a9c8-a4de4fb3c6e4">

**Comment by nickmac88** [comment]
> Maker dataflow refresh successful, the flow run also successful, but still we are getting unknown records in maker table <img alt="image" width="767" src="https://private-user-images.githubusercontent.com/47393750/290166210-0bbd672f-e69e-471f-9330-234d8fa6e494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Nzk2MzQsIm5iZiI6MTcwMjQ3OTMzNCwicGF0aCI6Ii80NzM5Mzc1MC8yOTAxNjYyMTAtMGJiZDY3MmYtZTY5ZS00NzFmLTkzMzAtMjM0ZDhmYTZlNDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE0NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNWIzMTZlZTI1NDFjZmM4OWZlMzMyZmUyZWIyM2VmMDNmNjBjMTJhY2RjNjI3YWI2ZWQ5YzA5MTcyOTViNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I4S4E-YWxqnxi3X0kFYNGbaVkuK5hVKMk6gbTUFf5BU">

This is also my experience

**Comment by Jenefer-Monroe** [comment]
Yes we switched away from that logic in newer builds. I'm afraid you'll need to upgrade to see the new behavior.

**Comment by nickmac88** [comment]
> Yes we switched away from that logic in newer builds. I'm afraid you'll need to upgrade to see the new behavior. Amongst other changes it now calls the helper flow instead of referencing the user table ![image](https://private-user-images.githubusercontent.com/89584709/289874539-3b57f08d-9f31-4ade-ba76-6e934c916146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0OTA0MzgsIm5iZiI6MTcwMjQ5MDEzOCwicGF0aCI6Ii84OTU4NDcwOS8yODk4NzQ1MzktM2I1N2YwOGQtOWYzMS00YWRlLWJhNzYtNmU5MzRjOTE2MTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE3NTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMDZlNWE0MWZhMzMzMDVlYzMzZDkyYzk5MTRmMjMxNTY1MzRjYzkzYjgzYmMzODA5ZmRkNjJkNTg1NzFhYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w7uztkwAVfG_VOUG5UjFWsEZZDIn1RVa_qo3jF0WRCY)

Hey guys! I have recently upgraded to the latest build but I am still seeing these unknown users in the makers table. Is this expected?

I can share screenshots of the data flows and the coe flow runs if you need, but mine are running successfully except for the welcome makers flow. However, I believe this flow is failing for the same reason... The makers table has unknown users without emails.

**Comment by Jenefer-Monroe** [comment]
If you still have this section of code in your flow then you must have unmanaged layers on the flow. We shipped the Nov release without that, it now looks as I show above. Can you please check for an unmanaged layer?

**Comment by Jenefer-Monroe** [comment]
Can you please run this flow: CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

Then when it finished, add the **_Maker is Orphaned_** column to that view?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/535c602d-8090-469e-b1d7-cbe907865deb)

**Comment by nickmac88** [comment]
I  am running 4.17 and i do not have any unmanaged layers on this or any other flow. I did as you suggested and ran CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

Here is my maker list afterwards
![Screenshot 2023-12-14 094451](https://github.com/microsoft/coe-starter-kit/assets/54548626/e4e0d624-d8b5-4006-9a96-b88743384166)

**Comment by Jenefer-Monroe** [comment]
OK this is expected then. These are users that created objects but left the org before you set up the kit, so there is no information from AAD on who they are.

**Comment by Rajatchopra3** [comment]
Okay, got it.

If it's alright, we are facing another issue - in the powerapps app table we are not getting app last launched data, is ther any dependency or something.

<img width="227" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/dfeef7ee-a00e-4e85-b3fd-f50eb7b6015b">
<img width="788" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/0c48afa2-a8a7-4ab6-90bf-e6cfce3e9305">

**Comment by Jenefer-Monroe** [comment]
Can you please post a new issue for that? This issue is already a little difficult with multiple people involved.

**Comment by Rajatchopra3** [comment]
Okay sure, here is the ticket number 7311

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
