### ISSUE TITLE
[CoE Starter Kit - BUG] SetupWizard>GetUserDetails failing

### ISSUE THREAD

**Issue by nickmac88** [microsoft/coe-starter-kit#7262]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The flow SetupWizard>GetUserDetails is failing. I do not know if this is intended or not. I am pretty sure that this is not causing any major issues given that this flow is rarely used (maybe only once on initial setup?)

I only noticed the error after inspecting the Command Center Admin tool to ensure the CoE apps/flows were in a good state.

This issue occurs when i open the app "CoE Setup and Upgrade Wizard" Upon opening the app, it triggers this flow. It looks like the flow is attempting to connect to Graph and pull license details for the logged in user. The error details are listed below.

CoE Setup and Upgrade Wizard display error
![Screenshot 2023-12-10 102303](https://github.com/microsoft/coe-starter-kit/assets/54548626/2c759c0a-3529-48f6-87cb-16585342f2c0)

SetupWizard>GetUserDetails Flow error
![Screenshot 2023-12-10 103150](https://github.com/microsoft/coe-starter-kit/assets/54548626/3db6fbd7-1df0-4af6-bdf1-460182cc9a6b)

### Expected Behavior

The SetupWizard>GetUserDetails shoudl not fail and license information is displayed on the CoE Setup and Upgrade Wizard

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

SetupWizard>GetUserDetails

### What method are you using to get inventory and telemetry?

Data Export

AB#1738

**Comment by v-bjaiswal** [comment]
Hi, Please check the HTTP connection reference value in your environment:
![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/47605149-1efb-410f-a173-7c1e04998c71)

edit each one (if multiple) and see where its pointing. 
it needs to point to the graph url.

when you setup the kit you are supposed to make your HTTP on Azure AD connection (now called HTTO with Microsoft Entra ID (preauthorized) with the following url:
**https://graph.microsoft.com/**
 
unfortunately the product adds a connection to the local dynamics url sometimes too and can get picked up by the connection reference.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
