### ISSUE TITLE
[CoE Starter Kit - Question] Sync Audit Logs V2 fails to run with error : Get_Azure_Secret

### ISSUE THREAD

**Issue by HaoqingCai** [microsoft/coe-starter-kit#7263]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After CoE Nov release installed, there is an error for flow "Admin | Audit Logs | Sync Audit Logs (V2)"
There is a similar issue reported [https://github.com/microsoft/coe-starter-kit/issues/7250](url), but error step is different.

Action 'Get_Azure_Secret' failed
Error occured while reading secret: Value cannot be null.
Parameter name: input
![Snipaste_2023-12-11_14-49-49](https://github.com/microsoft/coe-starter-kit/assets/120713349/9a3fdea9-aa5c-42e5-91a9-2cbb4122ea3c)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1740

**Comment by Jenefer-Monroe** [comment]
If you are not using Azure Key Vault to store the secret, then failure is expected and caught. 
Note that flow always shows the first failure there, even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

**Comment by Jenefer-Monroe** [comment]
It looks like an SSL credentials failure? Are all iterations failing? If so, perhaps your secret expired?

**Comment by HaoqingCai** [comment]
> It looks like an SSL credentials failure? Are all iterations failing? If so, perhaps your secret expired?

Not all of the iterations failed, it failed start from 526. The error saying "The SSL connection could not be established."

![image](https://github.com/microsoft/coe-starter-kit/assets/120713349/76f26f17-d237-48dd-a285-fa613c7e0e57)

**Comment by HaoqingCai** [comment]
> I'm having the same problem - I posted it as a question instead of a bug as I was unsure if it was something on my end. #7250

Yes, i did find your post before. I'm not sure if this is the same issue as the error step is different, so i posted a new issue here.

**Comment by Jenefer-Monroe** [comment]
Can you go to the previous run (525 for you) and see if it returned a status code? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fcaedd0c-e589-4ed1-9903-6e94d037aaab)

**Comment by HaoqingCai** [comment]
> Can you go to the previous run (525 for you) and see if it returned a status code? ![image](https://private-user-images.githubusercontent.com/89584709/289595847-fcaedd0c-e589-4ed1-9903-6e94d037aaab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MjkyOTIsIm5iZiI6MTcwMjQyODk5MiwicGF0aCI6Ii84OTU4NDcwOS8yODk1OTU4NDctZmNhZWRkMGMtZTU4OS00ZWQxLTk5MDMtNmU5NGQwMzdhYWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAwNTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYTk0MDQzMjczNjU3NjFjODMyNDIxMDM0ZWM5YjlmNWNmYzA3OTE1NGY1OTEzODYyZjFhOGIyZDNiYTk5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._fi4jJ--j4rWerlms4fOf_msgdDWXTHcTGyrtYxo5SM)

Yes, there is a status code (200) in the previous run.
![image](https://github.com/microsoft/coe-starter-kit/assets/120713349/5ac97746-a94e-4670-97b3-79536b130a8e)

**Comment by Jenefer-Monroe** [comment]
Has this happened to you again since this failure? I looked around and had a few test tenants hit this once around that same date. But havent seen it since. Might have been a one off issue with the data provider we use here.

**Comment by Jenefer-Monroe** [comment]
Wonderful! I think the backend just had a hiccup.

**Comment by HaoqingCai** [comment]
> Has this happened to you again since this failure? I looked around and had a few test tenants hit this once around that same date. But havent seen it since. Might have been a one off issue with the data provider we use here.

The last failure happened on 12/8. I will keep monitoring on this. If there is no failure afterward, i will close this issue.
