### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Count in DLP Impact Analysis Doesn't Match with PPAC DLP Impact Analysis

### ISSUE THREAD

**Issue by RahulBojji** [microsoft/coe-starter-kit#7264]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In DLP Impact Analysis App, Applied To Column is not matching with Applied to on Power Platform Admin Center

<img width="912" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/42ccd35e-52e6-46f3-a694-b4257a2149d8">

In PPAC
<img width="789" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/b79557f8-a5df-4d4a-9b79-102e84b3ab6a">

### Expected Behavior

Count of Environments should be Identical

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

DLP Impact Analysis 

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Open DLP Impact Analysis app, compare "Applied To" column with "Applied To" on Power Platform Admin Center

AB#1741

**Comment by Jenefer-Monroe** [comment]
This was already tracked by https://github.com/microsoft/coe-starter-kit/issues/7036. 
We can hold two for this case but just FYI

**Comment by Jenefer-Monroe** [comment]
relating to https://github.com/microsoft/coe-starter-kit/issues/7265
