### ISSUE TITLE
[CoE Starter Kit - Can logic apps flows be included in the CoE starter kit

### ISSUE THREAD

**Issue by Ananass007** [microsoft/coe-starter-kit#7266]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can logic apps flows be included in the CoE starter kit?
Can a tenant isolation in power platform block logic apps?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1745

**Comment by Jenefer-Monroe** [comment]
Unfortunately our charter is to inventory the objects in the Power Platform suite and so we do not venture into the Azure space. 
This would be a great add on and quite popular in the market though if anyone is interested in doing this work!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
