### ISSUE TITLE
[CoE Starter Kit - BUG] Loading a stream video into Nurture Apps - Admin and Video Hub Not able to put stream videos that are from the same tenant.

### ISSUE THREAD

**Issue by mdphung** [microsoft/coe-starter-kit#7267]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Loaded a url from stream in the Nurture Admins App but when i got to Video hub it shows this:
![image](https://github.com/microsoft/coe-starter-kit/assets/117682988/1f2ec137-814b-42d6-bd65-27d47b8078a5)

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.1

### What app or flow are you having the issue with?

not sure

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1747

**Comment by RahulBojji** [comment]
@mdphung Can you please confirm the content URL you are using whether its "**sharepoint.com**" one or it contains "**microsoftstream.com**"

**Comment by RahulBojji** [comment]
@mdphung 
As per this [documentation](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-stream-video) the stream control is near deprecation, and it will support Only the URL which looks like this "https://somedomain.microsoftstream.com/" 
If the content URL has SharePoint version, we might need to wait until the product releases it and then we can incorporate that in the app.

**Comment by santiareh** [comment]
Hi, I am experiencing the same issue, my links contain sharepoint.com, does this mean we can only use videos that are saved within our SharePoint site or can we point to external like youtube?

**Comment by Jenefer-Monroe** [comment]
Rahul is away for the rest of the week, but we did some work to figure this out. So when he is back he will do a write up explaining it all for you guys. 
Thanks for your patience.

**Comment by RahulBojji** [comment]
> @RahulBojji Hi, I am experiencing the same issue, my links contain sharepoint.com, does this mean we can only use videos that are saved within our SharePoint site, or can we point to external like youtube?

@santiareh 
The control which we are using currently doesn't support links which contains sharepoint.com. This control will be deprecated in future and Microsoft will be releasing new control for this. Please have a look that [this ](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-stream-video)for more information. We have figured out an alternate approach to replace this control and add a new control which supports SharePoint links. We will try deep dive into that control and test it thoroughly and push it in the upcoming releases. 

Currently the control we are using supports links pointing to YouTube as well. 
FYI

<img width="786" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/d3b2a586-cd78-4fd3-a22c-d0c111c5a53c">

<img width="786" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/38b4dddf-50e2-4aa8-b63a-4609d39f1d01">

**Comment by gulzarudheen** [comment]
This issue will be covered in Feb release.

**Comment by Jenefer-Monroe** [comment]
in the admin app we will
- identify when you are adding a SP link
- in this case provide a link to help documentation on how to setup the lnks for them

In both admin and maker
- identify when you are adding a SP link
- in this case provide a generic thumbnail since they do not work for these types.
