### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Driver) flow errors when trying to turn on

### ISSUE THREAD

**Issue by fosttj** [microsoft/coe-starter-kit#7268]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In CoE Admin Command Center I select CoE Flows, Inventory, Admin | Sync Template v3 (Driver), Flow details, Turn On and I get this error message - 
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'OpenApiOperationParameterValidationFailed' and message 'Input parameter 'item' validation failed in workflow operation 'Insert_Legacy_Environment': The API operation 'CreateRecord' is missing required property 'item/----scrubbed----'.'."}}".

### Expected Behavior

In CoE Admin Command Center I select CoE Flows, Inventory, Admin | Sync Template v3 (Driver), Flow details, Turn On, flow starts and coordinates the starting of all of the other inventory flows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open CoE Admin Command Center
Select CoE Flows
Select Inventory
Select Admin | Sync Template v3 (Driver)
Select Flow details
Select Turn On

AB#1748

**Comment by v-bjaiswal** [comment]
Hi, Please check if any unmanaged layer is on the flow.

![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/74323597-42c2-4be3-a480-61a439cd917b)

**Comment by fosttj** [comment]
I do not have any unmanaged layers as seen with this screenshot.
![image](https://github.com/microsoft/coe-starter-kit/assets/136116520/1e2c73af-14fe-4e33-b866-724dc8b439fc)

**Comment by v-bjaiswal** [comment]
Can you validate ones if below action is available inside "Driver" flow.

![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/9fffc736-bd8b-4600-b162-9537b89bdb00)

1. expand "Store environments in the CoE CDS Entity" scope.
2. Expand "Appy to each Environment" for loop.
3. Expand "Inventory environment" scope.
4. Expand "Check if Legacy Environment" condition.
5. Expand "Yes".
6. Expand "If found, we've already created, just update it, else create" condition.

**Comment by v-bjaiswal** [comment]
closing out as no further action from starter kit team
