### ISSUE TITLE
[ALM Accelerator - BUG]: Production environment variable value is blank

### ISSUE THREAD

**Issue by KevinNowalski** [microsoft/coe-starter-kit#7269]
### Describe the issue

When deploying to the production environment, we are finding that an environment variable's value is showing up blank.

### Expected Behavior

The environment variable should have the same value that was added in the configure deployment settings of the ALM.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231207.2

### Steps To Reproduce

1.  In the ALM's configure deployment settings screen
2.  Add value to the field for the environment variable
3.  Deploy solution to the production environment
4.  Check the environment variable's value in the production environment
5.  The environment variable's value is blank

AB#1749

**Comment by RajeevPentyala** [comment]
@KevinNowalski Can you please confirm whether you did 'Commit' solution after configuring the deployment settings?

**Comment by KevinNowalski** [comment]
> @KevinNowalski Can you please confirm whether you did 'Commit' solution after configuring the deployment settings?
We have published the dev solution first and then configured the ALM and then did save the configuration.

**Comment by RajeevPentyala** [comment]
@KevinNowalski The general rule is that we should 'Commit' the solution after making any changes in 'Deployment Settings. Here are the steps.

- Make changes to 'Deployment Settings'.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/5d9d2286-a9bf-44f0-ab07-5676d0254262)

- Always 'Commit' the solution.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/5c056f86-ac41-4c64-9c5a-4dd7a1c7a3fc)

- Proceed with 'Deploy'.

Kindly confirm that you are following this procedure.

**Comment by KevinNowalski** [comment]
We usually click on save solution:

![save-solution](https://github.com/microsoft/coe-starter-kit/assets/22607204/ff45d2a8-d508-4f15-a090-c4accdc720bc)

**Comment by RajeevPentyala** [comment]
@KevinNowalski Button's label for you is 'SAVE SOLUTION' because you would have configured the 'Commit Solution' label as 'SAVE SOLUTION' in your 'Deployment User Settings' record. Please confirm if you clicked on 'SAVE SOLUTION' and if the pipeline ran successfully after configuring the settings.?
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/1e63bb3d-d0dc-47fc-af26-08eca7d4e676)

**Comment by KevinNowalski** [comment]
@RajeevPentyala After configuring the settings, the pipeline ran successfully from clicking on save solution.

**Comment by RajeevPentyala** [comment]
@KevinNowalski Thanks for the confirmation. Can you share the screenshot of **AzDo Repo > Solution folder name > config > Prod > deploymentSettings.json**. When you save or commit the solution, the 'EnvironmentVariables' node in the 'deploymentSettings.json' file should be populated with your Environment Variable entry.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/75682afc-11f2-4714-84ed-24180c4922a7)

**Comment by KevinNowalski** [comment]
@RajeevPentyala Here is the screenshot:
![MicrosoftTeams-image (1)](https://github.com/microsoft/coe-starter-kit/assets/22607204/0b7508db-b497-48f9-9e7b-e5cb65f9ea22)
Also, the environment variables are properly mapped.

**Comment by RajeevPentyala** [comment]
@KevinNowalski Thank you for providing the details and your patience. One last thing I'd like to verify is the pipeline variables.
- Connect to Azure DevOps portal.
- Go to **Pipelines**
- Select the 'deploy-prod-{solution_name}' pipeline. Click on 'Edit'.
- Click on 'Variables' in the top right corner and search for the pipeline variable with a 'Name' matching the '_Value_' from your 'deploymentSettings.json' screenshot above.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/4543354c-e424-4686-859a-b43717dc07e2)

- Once you locate the pipeline variable, check its value. 'ALM Accelerator' reads the values from the pipeline's 'Variables' and substitutes them in the 'deploymentSettings.json' file on the fly.

This troubleshooting step helps identify the value passed during deployment to the production environment.

**Comment by KevinNowalski** [comment]
@RajeevPentyala The correct value is being passed during deployment:
![deployment-env-variable](https://github.com/microsoft/coe-starter-kit/assets/22607204/2b22b3d8-e561-4cb3-a724-e024f2bd9c30)

**Comment by RajeevPentyala** [comment]
@KevinNowalski From your screenshot, it seems that you've made customizations to the pipeline .yml file in addition to what 'ALM Accelerator' generates. Can you please confirm this?

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/aec9702a-348b-4e47-9a9e-73bf6e3933b8)

**Comment by gerald560** [comment]
Yes we have ...but the only changes were to be able to trigger prod after test is done.

**Comment by RajeevPentyala** [comment]
@gerald560 @KevinNowalski I would like to have a troubleshooting session. Please reach out to me at rajeevpe(at)microsoft(dot)com.

**Comment by RajeevPentyala** [comment]
@KevinNowalski Closing this issue for now since there was no update from your side. Please reach out if you need further assistance.
