### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis very slow to respond and update

### ISSUE THREAD

**Issue by russrimm** [microsoft/coe-starter-kit#7271]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

- The DLP Impact Analysis model-driven application is very slow to update or respond when typing in the search blank.  It acts like it needs DelayOutput on the textinput or not use StartsWith on the Items property of the DetailsList control. The wizard sometimes just pauses for a few seconds randomly as well like it's very busy.

### Expected Behavior

When typing in the search blank and clicking through the wizard, the app should display the letters you type while you're typing instead of seconds later. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4,17

### What app or flow are you having the issue with?

DLP Impact Analysis model-driven app

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run DLP Impact Analysis Edit Policy wizard. After clicking through the initial steps of the wizard, search for connectors by typing multiple letters into the search blank without pausing for seconds between each keypress.

### Anything else?

Thank you!!!!

AB#1752

**Comment by RahulBojji** [comment]
@russrimm Thanks for reaching out. This is a known issue, and we will try to enhance the performance in the next releases. Will keep this open for tracking.

**Comment by Jenefer-Monroe** [comment]
Please add loading UX to the app in these slow spots, it will make it more clear that they are waiting and not just broken.
