### ISSUE TITLE
O365 security group is not shown in CoE setup wizard

### ISSUE THREAD

**Issue by saidireddy-basireddy** [microsoft/coe-starter-kit#7275]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have followed all the steps as per CoE setup documentation. We have imported CreatorKitCore_1.0.20230727.2_managed.zip, CreatorKitReferencesMDA_1.0.20221205.3_managed.zip and CreatorKitReferencesCanvas_1.0.20221205.1_managed.zip before importing the CenterofExcellenceCoreComponents_4.17_managed.zip. We have imported CenterofExcellenceCoreComponents_4.17_managed.zip successfully and trying to configure the CoE with setup wizard. 

We have created Microsoft 365 groups in Azure portal for Admin, Makers, and User personas. These groups are not shown in the list to configure the personas, but we can see some of the other groups which were created earlier. 
 
It is working smooth in our demo tenancy but it not working in our client's production environment. 
[Security group issue in CoE Setup Wizard.docx](https://github.com/microsoft/coe-starter-kit/files/13657523/Security.group.issue.in.CoE.Setup.Wizard.docx)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1) Create new Power Platform environment with dataverse enabled and other steps specified in CoE setup documentation.
2) Import CreatorKitCore_1.0.20230727.2_managed.zip, CreatorKitReferencesMDA_1.0.20221205.3_managed.zip and CreatorKitReferencesCanvas_1.0.20221205.1_managed.zip before importing the CenterofExcellenceCoreComponents_4.17_managed.zip.
3)Imported CenterofExcellenceCoreComponents_4.17_managed.zip.
4)Create M365 groups for Admin, Maker and User personas. (the creation of groups is done by Azure tenant admin).
5)Launch the CoE setup and upgrade wizard to configure and try to select the M365 groups for personas. 
This is where we are facing issue.

AB#1759

**Comment by Jenefer-Monroe** [comment]
Hello. There is a pagination issue here so you may not be able to find your group in larger tenants.

If you cannot find the maker / user groups here, you can enter the GUID of the group instead as shown here: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c7f17a1d-2609-41bd-aa9a-d45742537869)

For the admin you add the email instead of the GUID
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5e79132a-5eea-48b6-becc-8132922d9030)

**Comment by saidireddy-basireddy** [comment]
Thanks for the response.
