### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin Center - Data Export to Data Lake for CoE missing one table

### ISSUE THREAD

**Issue by BlackRifleCoE** [microsoft/coe-starter-kit#7277]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I've enabled Data Export for Data Lake for both Power Apps and Power Automate and configured them to point at a DLv2 Blob Store in our subscription. This has been setup for 5+ days now.

We have seen most of the expected data populated in the blob store, but are missing one expected directory/export. 

We do have:

**powerplatform/powerapps/Applications

powerplatform/powerapps/Connections

powerplatform/powerapps/environments

powerplatform/powerapps/usage

powerplatform/powerautomate/FlowConnectionReference

powerplatform/powerautomate/Flows

powerplatform/powerautomate/usage**
 

But we are missing the directory and included data file(s) in **powerplatform/powerapps/connectionreference** 

This is stopping the refresh of the CoE dataflow - **CoE BYODL Apps Connection**, all other dataflows are working.

Permissions are all correct and everything is working apart from that one missing directory. 

![image](https://github.com/microsoft/coe-starter-kit/assets/153179609/6d94034b-c52f-4215-8140-3fb2027d1d07)

### Expected Behavior

Expect to see the folder powerplatform/powerapps/connectionreference in the Blob store

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoE BYODL Apps Connection

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Configured the Data Export in Power Platform Admin for Data Lake as deocumented
Granted permissions on DL as Documented

AB#1762

**Comment by Jenefer-Monroe** [comment]
I'm afraid this is a product issue and not something we can assist with. Product support can take a look and hopefully see what is wrong and why you aren't getting that folder. 
I have seen it take a week to populate all the folders before fwiw, so you may want to wait another few days. Or if you have a good product support connection, go ahead and reach out now.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
