### ISSUE TITLE
[CoE Starter Kit - QUESTION] Will the enhancements/fixes in the 'skipped' December release be included with the features/fixes that were already on the January milestone?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7278]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Will the enhancements/fixes in the 'skipped' December release be included with the features/fixes that were already on the January milestone?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1763

**Comment by Jenefer-Monroe** [comment]
Yes we've already moved those issues over to the Jan release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
