### ISSUE TITLE
Azure DevOps AA4AM

### ISSUE THREAD

**Issue by arpitjain1470** [microsoft/coe-starter-kit#728]
HI Team,

I am facing issue since long in connecting my custom connector of ALM Accelerator of Advance maker solutions to the Azure DevOps .
Since for PowerApps I am using Client credentials and all dataverse environments rest inside it on which  ALM Accelerator of Advance maker app is installed.
and  for DevOps I am using different account in which my pipelines all pipelines are there.
I am unable to connect app with DevOps using O auth 2.0 in security in test either i am getting 203 response code or tennat issue if i use common in tenant at security tab.

is it possible to connect via Basic Authentication and API Key if yes please let me know the process.

I would request to either call me or take one session so that I can explain my issue to you once, 

Screen shot attached for your refrence.

![genraltab](https://user-images.githubusercontent.com/71654295/124418862-071cab00-dd7a-11eb-8096-726e676eb23d.jpg)

**Comment by arpitjain1470** [comment]
Since in security tab our tenant id is not common for both Azure DevOps and Application, may be due to this we are facing issue . we want to connect it cross tenant kindly let me the process how we can connect our app to the cross tenant .
is it possible via basic authentication or api key in security.

Please connect me on 8602928534
or connect me on Microsoft Team to share session once.

**Comment by arpitjain1470** [comment]
Hi Team,

can you please let me know if cross tenant connection  is possible using API Key and also share me the steps and process 

![image](https://user-images.githubusercontent.com/71654295/124430718-22dd7c80-dd8d-11eb-8688-9facdfcfe732.png)

I tried with basic authentication but it is not validating testing of custom connector.
let me know if any of this possible for it ?
Thanks in advance!

**Comment by jenschristianschroder** [comment]
Hi @arpitjain1470,

What you are trying to achieve is currently not supported by the AA4AM.

The tenant id should be "common". The authentication service will identify the correct tenant id based on the input parameters.

Also, you should leave the Base URL as "/". Adding your organization name in the base url will break all operations in the connector as they pass in the organization name as a parameter coming from the Canvas App.

**Comment by arpitjain1470** [comment]
Hi Thanks for your response,

So I understand , it  is not possible to connect via API key and Basic Authentication method, 
and also cross tenant is not possible in aa4am solutions to connect custom connectors. 
please confirm me if I understand correctly. 

![image](https://user-images.githubusercontent.com/71654295/124457594-97beaf80-dda9-11eb-9ec8-c75e9504305a.png)

Thanks and regards,
Arpit Jain

**Comment by jenschristianschroder** [comment]
Hi @arpitjain1470 ,

You are correct that neither API Key or Basic Auth is support in the AA4AM CustomAzureDevOps connector.

Cross tenant use case is not currently supported as the AA4AM does not have support for user cases that rely on authentication against multiple AAD tenants.

Br,
Jens

**Comment by arpitjain1470** [comment]
Thank you very much jens
