### ISSUE TITLE
[CoE Starter Kit - QUESTION] Has there been any thought to add Power BI reports to the Toolkit? It would be great to be able to have the same sort of insight into Power BI as we do with Apps of Flows.

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7281]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Has there been any thought to add Power BI reports to the Toolkit? It would be great to be able to have the same sort of insight into Power BI as we do with Apps of Flows.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1766

**Comment by Jenefer-Monroe** [comment]
Our charter is limited by the organizational structures within the company, and Power BI is in a different org than the rest of Power Platform. 
Unfortunately, as a result, we do not have the funding or the expertise to include it in the kit.
