### ISSUE TITLE
[CoE Starter Kit - QUESTION] Im still having issues with the new audit log connector, and Im thinking to do a brand new install with January release as there seems quite a lot of updates since my July version.. Q... Upgrade or re-install (I have only updated some system emails, everything else is default)

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7282]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Im still having issues with the new audit log connector, and Im thinking to do a brand new install with January release as there seems quite a lot of updates since my July version.. Q... Upgrade or re-install (I have only updated some system emails, everything else is default)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Thats difficult for me to say as I'm not sure why you were failing and what you have installed / using. 
If you are able to do a clean install and its the upgrade you've struggled with, that is great. You will lose any metadata you've collected though (ex excuse this flow from inactivity flows)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
