### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there a way to see which users have direct access to an environment, when looking at the admin view this shows a long list of users. And if a user has elevated to Global or Power Platform admin they are granted system admin is all environments, its not easy to audit this as involves checking individual user access.

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7283]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way to see which users have direct access to an environment, when looking at the admin view this shows a long list of users. And if a user has elevated to Global or Power Platform admin they are granted system admin is all environments, its not easy to audit this as involves checking individual user access.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We have done this work for the System Admin SR. You can see it in the Power Platform Admin View app
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ef2e36a9-8093-43c8-a0d0-b55b46503a8f)

Its done by the **_SYNC HELPER - Get Security Role Users_** flow which takes in Envt, SR, and BU. 
You can extend this flow to include more SRs but its rather API intensive as it does not just cover Direct Access but also access via Teams / Groups

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
