### ISSUE TITLE
[CoE Starter Kit - QUESTION] After doing a COE starterkit Update I got "14 environment variables need to be updated". this from my https://make.powerapps.com/environments, version used for the update was the November 2023 update.

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7285]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

After doing a COE starterkit Update I got "14 environment variables need to be updated". this from my https://make.powerapps.com/environments, version used for the update was the November 2023 update.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1767

**Comment by ghavbansnb** [comment]
What solution are you experiencing the issue with?
Center of Excellence-Core Components  

What solution version are you using?
version 4.17

What app or flow are you having the issue with?
None

What method are you using to get inventory and telemetry?
NONE

**Comment by RahulBojji** [comment]
@ghavbansnb 
Whenever you import a solution whether it's an upgrade or fresh solution import, if in that solution environment variables are present, they also get imported into the environment. While importing it will ask you to add values to those environment variables used in the solution 

<img width="853" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/29735feb-8ca8-4645-a397-177f83483217">

This is just a warning notification getting displayed here for the admin to update environment variables.  If we choose to ignore this, the processes using these variables will pick default value.
 Please have at a look at this documentation for more knowledge on [Environment Variables](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/environmentvariables#create-an-environment-variable-in-a-solution).

**Comment by Jenefer-Monroe** [comment]
Please note also that for the kit, every feature area supported by the Setup Wizard, it will fill these variables for you so you can leave them blank until you get to those areas.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
