### ISSUE TITLE
[CoE Starter Kit - QUESTION] Are there plans to improve the data available in the COE for PA flows? It would be great to see "Last Run Date", "State Change Date", "Run Count", etc. This would help us find the flows that have not been running for some time, and also help us work out what our top flows are for implementing better controls around these

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7286]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Are there plans to improve the data available in the COE for PA flows? It would be great to see "Last Run Date", "State Change Date", "Run Count", etc. This would help us find the flows that have not been running for some time, and also help us work out what our top flows are for implementing better controls around these

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
There is a product feature to track flow runs which is rolling out estimated for Feb 2024 at which time we do want to consider things like this yes!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team

**Comment by manuelpsnunes** [comment]
Hi @Jenefer-Monroe , @manuelap-msft , @RajeevPentyala 
Can you confirm if the product feature to track flow runs and with ETA for February already rolled out? If so, can you share some public documentation please?

Thank you!
