### ISSUE TITLE
[CoE Starter Kit - QUESTION] is it possible to get the unmanaged version of some of the canvas app to customise? ie innovation backlog

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7287]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

is it possible to get the unmanaged version of some of the canvas app to customise? ie innovation backlog

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1768

**Comment by Jenefer-Monroe** [comment]
Unmanaged versions of the kits are available on GitHub. 
If you go to https://github.com/microsoft/coe-starter-kit/releases/latest
Then scroll to the bottom to Assets, you will see CoEStarterKit-Unmanaged.zip. 
Once in a while the release tool messes up and doesn't include these but usually they will be there!
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/403378b8-4399-46df-959c-c2e6b4325035)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
