### ISSUE TITLE
[CoE Starter Kit - QUESTION] I want to Enable "Maker Assessment" feature and It's not available in my environment yet, message ""Mississing prerequiste: Import CenterofExellenceNutureCompnents before configuring this feature", Can I just download and import NutureComponent to our solution as a normal process? if not, do you have any tip, online document, how to quickly (understand timely sensitive in our Office Hours)

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7289]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I want to Enable "Maker Assessment" feature and It's not available in my environment yet, message ""Mississing prerequiste: Import CenterofExellenceNutureCompnents before configuring this feature", Can I just download and import NutureComponent to our solution as a normal process? if not, do you have any tip, online document, how to quickly (understand timely sensitive in our Office Hours)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The Nurture solution is another solution in the download where you got the Core Solution. In that same folder you will see another file with starter data
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ba0f2217-b9c0-4f27-a5d6-5267caf9a1ce)

You just install it like normal and then use the Setup Wizard to walk you through the rest, including reference to some learning materials and how to import the starter data

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/91b8c2f5-b52a-4c28-8411-6d68b6289467)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/293b15d2-8bd3-45bb-815c-d9ed8ada8de0)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2c408ffb-631e-45d9-b631-1da52931bad7)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
