### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can we redirect all the emails to our service account instead of sending them to all users or higher officials??

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7290]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can we redirect all the emails to our service account instead of sending them to all users or higher officials??

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1770

**Comment by Jenefer-Monroe** [comment]
Yes we have an env variable called Production Environment which can be set to no at which point all mail will go to the user / group set up in the admin email env var. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c4bbeb36-31db-4b80-86e1-6d579b58ed71)

Note that sometimes flows cache env vars so you may want to turn off and back on all flows that rely on this env var

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team

**Comment by rmedrano2** [comment]
Just to be clear, when this is set to no... there will be no emails sent to anyone other than admins?  Does this mean that the compliance process will only send emails to admins as well?  we are re-installing the CoE into a dev environment and are worried that this may start sending emails out to everyone in the company
