### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can you let me know why the "App Last Launched on" column in the PowerApps Apps table in my CoE is empty?

### ISSUE THREAD

**Issue by rpulcino** [microsoft/coe-starter-kit#7291]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can you let me know why the "App Last Launched on" column in the PowerApps Apps table in my CoE is empty?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1771

**Comment by RahulBojji** [comment]
@rpulcino 
Please have a look at these #7144,#6771,#6159

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
