### ISSUE TITLE
Related to Issue #7217

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#7292]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

The problem with Kula and team is that the organization does not allow to use Applications permissions to connect to office 365 custom connector. The team needs to understand how safe it is to use Application permission options to connect to custom connector. Any guidance provided by you in this case will help team to understand and implement Application permissions.

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#1772

**Comment by Jenefer-Monroe** [comment]
Hello. Im not sure how to answer this. The permissions outlined are what is granted for anyone who has access to the application. 
Do they have specific questions?

**Comment by PPMini** [comment]
Thanks Jenefer, I think Kula and team is good for now on this. Closing the issue.
