### ISSUE TITLE
Environment Capacity tracking over time

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#7293]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there any functionality in the toolkit that saves the history of the capacity that an environment uses over time?  We need to be able to track the growth of environments, and forecast capacity need based on historical data.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1774

**Comment by Jenefer-Monroe** [comment]
No we dont have that. The product does have something like this though, can you take a look and let me know what woudl be missing from your POV? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c2e9f7ed-995a-443a-958d-d813ae8579d4)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
