### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Driver) does not persist Teams Group ID

### ISSUE THREAD

**Issue by martincyr** [microsoft/coe-starter-kit#7294]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Might be a feature request or a bug, but the `Admin | Sync Template v3 (Driver)` flow gets and parses the  connectedGroups, and the columns seems to be present in admin_Environment (admin_MicrosoftTeamsID and admin_MicrosoftTeamsURL) but they never gets persisted.

### Expected Behavior

For Teams sku environment, the Teams related fields of the Envrionment should be filled with the scanned values from properties/connectedGroups.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.12

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1775

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. We found this a few weeks ago and have local fixed for the next release.
Please see https://github.com/microsoft/coe-starter-kit/issues/7199

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
