### ISSUE TITLE
Orphaned flows: Not sending the Teams chat to managers[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by a8kw** [microsoft/coe-starter-kit#7296]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the Governance solution, both the Parent and child flows for handling the orphaned objects are turned on. It is working for Admins and admin is getting the weekly report. But the managers are not receiving any Teams notification or emails.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.10

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

None

AB#1778

**Comment by RahulBojji** [comment]
@a8kw Can you please check if there are flow failures for both parent and child flows and whether the child flow is turned on or not.

<img width="552" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/f3029cfc-c7be-4727-a130-63be26dbd6da">

If the child flow is turned on and there are no failures. Can you please open the recent run history of the child flow share the outputs of below actions

<img width="758" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/6d55ccc8-9b08-4bf6-920c-e6e6539d6f67">
<img width="744" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/90204992-19cf-44d4-82b4-ee850ea7a7dc">

**Comment by a8kw** [comment]
Classification: Internal

++ Adding @Hermela ***@***.***> and @Bilbo, ***@***.***>, @Soria (DPCOE), ***@***.***>

Hi Rahul,
Can you please suggest for the managerEmail field? It will be based on the user,rt and thus will be dynamic. Am I missing something here?

This flow is turned on, but not running. While trying to run manually, getting this managerEmail field. Please suggest.

***@***.***

Thanks,

Amit Kumar
Power Platform Architect
DPCoE (Digital Productivity CoE<http://digitalproductivity/>)
Pacific Gas & Electric | IT Application Services
Mobile: +1-6025002342 | Email : ***@***.******@***.***>


From: Kumar, Amit ***@***.***>
Sent: Thursday, December 14, 2023 8:48 AM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] Orphaned flows: Not sending the Teams chat to managers[CoE Starter Kit - BUG] ISSUE TITLE (Issue #7296)


Classification: Internal

Hi Rahul,
Thanks for the inputs.
I see the child flow is turned off and needs manageremail as a mandatory field. Which email id to add here.

Thanks,

Amit Kumar
Power Platform Architect
DPCoE (Digital Productivity CoE<http://digitalproductivity/>)
Pacific Gas & Electric | IT Application Services
Mobile: +1-6025002342 | Email : ***@***.******@***.***>

**Comment by RahulBojji** [comment]
@a8kw 
**Request Orphaned Objects Reassigned (Parent)** Flow runs once in a week, if you have any orphaned flows, it should automatically call the child flow, if the child flow is turned on.
If you want to run it manually, I suggest you run the parent flow instead of child flow as the parameters will be passed to child flow from parent flow.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
