### ISSUE TITLE
Unable to map the flow connection reference and connector details with the flows in CoE toolki dashboard

### ISSUE THREAD

**Issue by saidireddy-basireddy** [microsoft/coe-starter-kit#7297]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We want the list of connections with connection details and connector details and the associated flows details in CoE dashboard. We are unable to establish relationship between Flow connection Reference with Connection Identity tables. 
When we export the data from flow connection references and connection identity tables, the GUIDs of connection reference ids are not matching.
[Connection References issue.docx](https://github.com/microsoft/coe-starter-kit/files/13667667/Connection.References.issue.docx)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1) Go to tables in Center of Excellence - Core Components
2) Try to establish relationship between CoE Connection Reference table and Connection Reference Identity table.
3) The values of connection reference ids are not matching.

AB#1780

**Comment by Jenefer-Monroe** [comment]
To our knowledge this information is not exposed by the product and so we cannot gather it. 
In other words, the product can tell us programatically that FlowA uses Dataverse but not which connection to Dataverse it is using.

**Comment by saidireddy-basireddy** [comment]
Ok so this could be treated as gap and try to include it in future releases. 

Can we get the requested information through PowerShell script? I have tried for some extent but not able to get complete details.

**Comment by Jenefer-Monroe** [comment]
I don't think this is available in Power Shell, but I could be wrong. We cannot use Power Shell for the kit. 
This is not the correct forum to drive product requests like that, we do raise it ourselves as well, but this is not a product team issues list. 
I suggest you post the request here: https://powerusers.microsoft.com, or find an existing post for it and express your interest. 
This is monitored by the product team for areas of improvement.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by saidireddy-basireddy** [comment]
May be your team should consider this to add it as todo list for future releases. It really doesn't make sense that instead of mapping the actual connection reference id the sync flows are generating the random GUIDs. I didn't get why this information is not exposed by product. As they are providing the other details, then they should have provide this information too.
