### ISSUE TITLE
[CoE Starter Kit - BUG] PBI - We cannot convert the value null to type Text

### ISSUE THREAD

**Issue by dspencelink** [microsoft/coe-starter-kit#7298]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I checked previous bugs and it looks like this question had the same issue in 2022: https://github.com/microsoft/coe-starter-kit/issues/2845
That issue was closed with no resolution.
I previously had COE core 4.13 installed and working great.  Today, I imported 4.17 (Nov 2023) which was successful.  Walking through the Upgrade wizard app and it gets to the PBI step.  When I open the 'Production_COEDashboard_October2023.pbit and put in the URL to my COE environment, it gets stuck trying to refresh and states that there are Pending changes to be applied.  No matter what I do, it won't complete refresh so it won't apply changes.  I manually confirmed that the inventory flows both ran successfully.  My screenshots are below.

![image](https://github.com/microsoft/coe-starter-kit/assets/133893716/dfeb55a6-d5b4-4322-bb6e-babcf4ea9e8b)

![image](https://github.com/microsoft/coe-starter-kit/assets/133893716/ebc10454-34c6-492c-86b4-e76be2cfbc07)

![image](https://github.com/microsoft/coe-starter-kit/assets/133893716/2754471a-e205-477a-ad16-4e4899940f93)

### Expected Behavior

When I upgraded in August, the PBI refresh and dashboard updated without issue and we've been using it ever since until today. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Power BI report

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Upgrade Core from 4.13 to 4.17
2. Open PBIT and attempt a refresh

AB#1781

**Comment by dspencelink** [comment]
Dang it.  Closed everything, restarted, reauthenticated and now it all works.  Forget I said anything.

**Comment by RahulBojji** [comment]
Closing out as no further action from starter kit team
