### ISSUE TITLE
Need help with generating a report

### ISSUE THREAD

**Issue by SomarajuA** [microsoft/coe-starter-kit#7299]
Hi, we will need your help to get the below data for the flows. Please see the data required below.

Creator Name, Creator's Country Name, Flow Name, Connectors used, Premium connectors used

AB#1789

**Comment by Jenefer-Monroe** [comment]
Hello, I'm not sure what you mean by report. We do have reports for you to use for both PBI and MDA views. 
Can you clarify what current report you are trying to augment?

**Comment by SomarajuA** [comment]
I am talking about the COE tool kit, PowerBI report

**Comment by Jenefer-Monroe** [comment]
ok i think you are asking for this: https://github.com/microsoft/coe-starter-kit/issues/6743
which we removed from the PBI with the rewrite.

**Comment by Jenefer-Monroe** [comment]
We are shipping the new release later today or tomorrow so you can please try then. 
Closing out as no further action for starter kit team
