### ISSUE TITLE
[CoE Starter Kit - BUG] COE BYODL Flows mashup error 

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#7300]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am getting error in refresh in coe byodl flow dataflow 
Error Code: Mashup Exception Error, Error Details: Couldn't refresh the entity because of an issue with the mashup document MashupException.Error: We're sorry, an error occurred during evaluation. Details: (Request ID: 33f11c2e-1ba2-4d64-b3c1-9f159c24e4e6).
Because of which I am not getting the correct flow data
<img width="727" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/2a90965c-e01c-4e27-8d26-b09a2f5421fb">
<img width="804" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/c5c2403c-370b-4cb4-8817-d5de72cb6123">

### Expected Behavior

Flow dataflow should refresh without error, thus provide correct flow data 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

COE BYODL FLOWS dataflow

### What method are you using to get inventory and telemetry?

Data Export

AB#1784

**Comment by Jenefer-Monroe** [comment]
Hello, we have some work that we hope will address this in testing via https://github.com/microsoft/coe-starter-kit/issues/6736
Please follow along for that bug being resolved.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
