### ISSUE TITLE
Connection Used in Desktop Flows [CoE Starter Kit - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by harsh-mehra-db** [microsoft/coe-starter-kit#7301]
### Describe the solution you'd like

For Cloud flows, when we export the the inventory details from the 'Power Platform Admin View', we get a column detailing what connections are used for a particular build. 
![image](https://github.com/microsoft/coe-starter-kit/assets/69756424/bb960f41-663c-4461-902d-a26bca178bc3)

But when this is done for Desktop Flows section, there is no field which shows what connections are used for a particular desktop flow.

We would like to have this column in the desktop flows as well.

### Describe alternatives you've considered

There are currently no alternative for this and we need to go and ask each user for what connection they are using, which is impacting the business.

AB#1785

**Comment by Jenefer-Monroe** [comment]
To our knowledge the connections for desktop flows are not exposed to us programmatically to collect. 
Once they are, we would add the to the kit.

**Comment by harsh-mehra-db** [comment]
That would be great!
Is there any other way to collect those connections automatically if you are aware?

**Comment by Jenefer-Monroe** [comment]
I am not aware of any way to gather these unfortunately.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
