### ISSUE TITLE
[CoE Starter Kit - BUG] Send Welcome Email - Cannot update the Organization Header and Footer in the Environment Variables : eMail Body Start, eMail Body Stop

### ISSUE THREAD

**Issue by avinkaur1** [microsoft/coe-starter-kit#7302]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to add my Organization header and footer in the welcome email. For this, I am updating the following Environment variables:
eMail Body Start
eMail Body Stop
 The values get reverted to Default values every time I save my custom values. Also please note that I am trying to load the header and footer pictures by converting images to Base 64. Please find the value of the email body start variable that I am trying to upload attached in the emailBodyStart_Variable.txt file.

[emailBodyStart_Variable.txt](https://github.com/microsoft/coe-starter-kit/files/13673274/emailBodyStart_Variable.txt)

The reason why I cant use image  source as a URL uploaded in the SharePoint site or a site because in my organization, they do not allow Share to Everyone permissions. So all users will not see the image or will see it as not loaded. 

### Expected Behavior

My organization header and footer to be shown in welcome email sent to new users. I would like to use Base 64 encoding forimage source.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Go to CoE Admin Command Center -> CoE Configurations -> Customized Emails
2. Update the eMail Body Start with the attached file 
[emailBodyStart_Variable.txt](https://github.com/microsoft/coe-starter-kit/files/13673295/emailBodyStart_Variable.txt)

3. Save the variable.
4. Wait for 2 mins, refresh
5. Value is reverted to original variable value

AB#1786

**Comment by Jenefer-Monroe** [comment]
I went to add your desired value in the product itself and see the issue. 
The product has a limit of 2000 characters for env variable values. This isnt something that we can change unfortunately. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/112c35c1-486e-4767-b76b-c4f4181238b1)

**Comment by avinkaur1** [comment]
Hello, surprisingly I do not even see this error, It save sand reverts in a while. Nevertheless, is there any other way that we can add header and footer to welcome email?

**Comment by Jenefer-Monroe** [comment]
We send all mails (except approvals mail) through this helper flow: **_HELPER - Send Email_**

So you could edit there but this will create an unmanaged layer, so you will want to remove and reapply with each upgrade. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2efd278e-ddfe-42e0-baff-545b81a73414)

**Comment by avinkaur1** [comment]
Hi Jenefer,

If I don't want to create an unmanaged layer, can I just add **HELPER - Send Email** to my custom solution and make changes there? This being child flow, can I just import this flow to my custom solution , or do I have to import the parent flow calling this child flow to the custom solution too?

Can you please write the steps how to import these to my custom solution to get them working.

Thanks,
Avin

**Comment by Jenefer-Monroe** [comment]
I'm not sure about that. My understanding is that you will need to edit this flow or create your own and edit all the flows that call it. Your best bet in my opinion is to edit this flow. You can pull it into another solution to make it more obvious though that you have done this.

**Comment by avinkaur1** [comment]
Hi Jenefer,

Yes I would like to pull the flow - HELPER - Send Email into another solution. My question is that, just pulling this flow is enough, or do I need to pull all the flows that call this Helper flow, like Admin | Welcome Email also to another solution?

**Comment by Jenefer-Monroe** [comment]
I dont think you would need to pull those no. But I've not played much with expanding on the kit so I'm not positive.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
