### ISSUE TITLE
[CoE Starter Kit - QUESTION] Maker Environment Request Documentation appears to be out of date???

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#7303]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Looking at the documentation and a previous question from March 2023 it would appear that the documentation is not up to date?

Does the Make Environment Request solution now use pages and a model driven app rather than a canvas app??

![image](https://github.com/microsoft/coe-starter-kit/assets/48433526/0b5ffee7-c451-4b19-849c-aac63f13e68c)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Nov 2023 4.17

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1787

**Comment by Jenefer-Monroe** [comment]
It does yes, marking as a documentation bug.
