### ISSUE TITLE
[CoE Starter Kit - BUG] Check deleted Cloud Flows is marking active Flows as deleted

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#7304]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I'm encountering a similar issue #5331, but it's with the November 2023 release. I manually ran this flow to update the deleted flows status for the Orphan process, only to discover that numerous Flows were incorrectly marked.
Could you please provide some advice?
Thank you!

### Expected Behavior

I would expect that only the actual deleted flows would be marked as delete.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Cloud Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

I ran the Flow manually for the Default Environment and encountered errors in the dataverse step while using the ID that began with Default: ')' or ',' expected at position 8 in '(Default-)'.
I had to remove the Default and use only the numbers and letters after the name to execute it successfully.

Then, I faced issues with the Power Platform for Admins connector. It was only working with the full ID.
To be able to run I had to input IDs like in the screenshot below:
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/e33d169f-67c2-434e-b3cd-f384e4bb2567)

AB#1788

**Comment by Jenefer-Monroe** [comment]
Yes the issue is that you entered this parameter to be false
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/90a7dc87-243e-4aca-9c82-639b6aec0287)

That is the parameter used when we detect an environment is deleted to mark all flows in it as deleted

**Comment by Jenefer-Monroe** [comment]
These flows should all get restored as part of normal inventory run now with **_Admin | Sync Template v4 (Flows)_**

And then I recommend you run the parent flow to get an up to date view of what is deleted: **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_**

**Comment by LucX4** [comment]
Hi @Jenefer-Monroe, the Admin | Sync Template v4 (Flows) has run several times today, but the Flows are still marked as deleted. Do you have any other recommendation?
Thanks!

**Comment by LucX4** [comment]
I used the Excel Online feature in the Admin View to set the Flows as not deleted again.
I'm going to run the parent Flow now CLEANUP - Admin | Sync Template v3 (Check Deleted) to get the up to date view of what is deleted.
Thanks Jenefer.

**Comment by Jenefer-Monroe** [comment]
You bet, we can hold this open while we make sure you settle in to correct data.

**Comment by LucX4** [comment]
It all looks good now. Thank you Jenefer! :)
