### ISSUE TITLE
[CoE Starter Kit - QUESTION] Orphaned Process

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#7305]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi guys!

I am planning to connect the app automations and orphaned flows, but I have a question

![orphans](https://github.com/microsoft/coe-starter-kit/assets/94450591/8cff13a8-b7d4-4a0f-9f47-8c95372de911)

The flow "Request Orphaned Objects Reassigned (Parent)" checks which app is marked as orphaned, and it has a schedule trigger. 

So, what is the automation that actually checks and updates in the PowerApps App table that the app is orphaned ?

![image](https://github.com/microsoft/coe-starter-kit/assets/94450591/4ddd7cf1-df7d-423d-830c-40b03fb5d364)

obrigado!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1790

**Comment by Jenefer-Monroe** [comment]
This happens in two places
1. in the orphan clean up flow: **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_**
In this flow if we detect a new maker being identified as orphan, we mark all their objects as orphaned
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d6732430-a01c-4379-bc37-eaeef2404a90)

1. in the individual object inventories
In this case if an object gets inventoried and we notice its orphaned, we mark it as such
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7c3ea975-75bd-485e-833b-bd978fdfaef0)

**Comment by ClaudioRWS** [comment]
Thanks a lot for the help @Jenefer-Monroe !!
