### ISSUE TITLE
[CoE Starter Kit - BUG] Pulse Survey is being sent out daily

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#7306]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have recently set up the Pulse Survey, in documentation and instructions it says we set the number of Makers that will receive this is on a weekly basis, but the flow is running on a daily schedule, thus multiplying the number of Makers that receive the survey. Seems like the trigger just needs to be corrected. Thank you and happy holidays.

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/a8eb1d06-c95c-4707-ba73-a693b29d1c83)

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/b53f0efc-8889-40ad-b7ee-e3b3e1895302)

### Expected Behavior

The flow trigger should be on schedule of Thursdays and send the survey only once per week.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.10

### What app or flow are you having the issue with?

Pulse - Survey Makers for CoE feedback

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1797

**Comment by Jenefer-Monroe** [comment]
You're right! Thanks for posting! I've fixed up for the next release.
