### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inventoring  and data show

### ISSUE THREAD

**Issue by fim34** [microsoft/coe-starter-kit#7307]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I have some bug with inventoring for owner and maybe maker of the flow

There on a modified Production_CoEDashboard_November2023 flow page the owner/maker is Julie
![flow1pbi](https://github.com/microsoft/coe-starter-kit/assets/89391607/63003ad7-c7ee-4084-9f93-63d8e97538fd)
the current owner is s_ppf... and not Julie for both.
owner is blank on pbi but not on flow and not the same owner but still has co-owner
![flow3pbi](https://github.com/microsoft/coe-starter-kit/assets/89391607/bf66e735-3436-4c8f-b1e2-7a3b08c95361)
owner is Julie on pbi but not on flow and not the same owner but still has co-owner, its also show as orphaned on pbi
![flow2pbi](https://github.com/microsoft/coe-starter-kit/assets/89391607/3e08d745-c7ea-4e18-8c31-e5061667ccd6)

There on Power Platform Admin View, also derived maker = owner ?
![flow4pbi](https://github.com/microsoft/coe-starter-kit/assets/89391607/95fc7fee-726d-4dc9-b4b4-3f1607191f36)

Also we have many flow when its show blank in flow maker and say orphaned yes but its not correct
![flow6pbi](https://github.com/microsoft/coe-starter-kit/assets/89391607/bfcac60a-0c90-4989-aef6-88bd9b79fa61)

I launched a full inventoring, no error on run flow of sync templace, but still show wrong information.
What is the issue and what to do to ahve the correct one ?

Another find its related to this add in Production_CoEDashboard_November2023 on app usage owner where other are blank or a admin user who never used power platform
![flow5pbi](https://github.com/microsoft/coe-starter-kit/assets/89391607/3225aefb-bbbe-4190-8320-c40e175d87ed)
![flow7pbi](https://github.com/microsoft/coe-starter-kit/assets/89391607/8ccf4f48-af98-4758-85b7-0422e06cbb36)

Thank in advance

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1798

**Comment by Jenefer-Monroe** [comment]
Hello, we have not yet updated the kit to use this information but it is on our backlog. We are waiting for one more product change and then will fund this work. Please see https://github.com/microsoft/coe-starter-kit/issues/3052

**Comment by fim34** [comment]
Ok,  thany for answer.

we have the powerbi report Production_CoEDashboard_November2023  restricted to each sub company and that a issue for them that is not the correct information show.

The second part of my post is also related to this  ? that a admin is designed as owner of action page or overview ?

Hope that may be available next year.

**Comment by Jenefer-Monroe** [comment]
Is the issue you are raising the zeros in the shared with column? 
Please run the **_CLEANUP HELPER - Power Apps User Shared With_** flow and see if they fill up when done. Note that it only fills for apps of type Canvas, not Model Driven Apps.

**Comment by fim34** [comment]
Yes the one with zero but also the one with admin as owner, why is set to this admin on multiple environment for same app ?
Ok will run this flow.

**Comment by Jenefer-Monroe** [comment]
Are these canvas apps or Model Driven?

**Comment by fim34** [comment]
Just checked that custom page for no owner or the admin.
For the flow its the name of the environment i set each time i run it?
![image](https://github.com/microsoft/coe-starter-kit/assets/89391607/9b744930-7f96-4a41-a509-6c2a4c03da04)

**Comment by Jenefer-Monroe** [comment]
That should be a GUID, not a display name. Did you call it yourself by hitting play and entering a parameter? Or did you run CLEANUP HELPER - Power Apps User Shared With

**Comment by fim34** [comment]
yes myself with run flow and added the display name, ok its GUID = EnvtName

**Comment by Jenefer-Monroe** [comment]
oh i see. I pasted the child flow and not the parent in my instructions. Apologies! 
Please run **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_**

**Comment by fim34** [comment]
ok,  CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) was run. 
Have to wait next pbi refresh to check the data.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
