### ISSUE TITLE
There is way to provide access to the Admin View for users who have their own environments (owners, head of groups), limiting the records they can view and ensuring that they are only restricted to the environments they manage?

### ISSUE THREAD

**Issue by federicoruiz** [microsoft/coe-starter-kit#7309]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi PowerCAT!

There is way to provide access to the Admin View for users who have their own environments (owners, head of groups), limiting the records they can view and ensuring that they are only restricted to the environments they manage?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1800

**Comment by Jenefer-Monroe** [comment]
We do not have this no, but you could implement it with the Row Level Security features of Dataverse using Modern Business Units. 
If you arent familiar with the Security Model features of Dataverse, its a bit of a learning curve but amazing once you get past that. 
Here are some starter links
https://learn.microsoft.com/power-platform/admin/wp-security-cds
https://learn.microsoft.com/power-platform/admin/control-user-access

**Comment by federicoruiz** [comment]
> We do not have this no, but you could implement it with the Row Level Security features of Dataverse using Modern Business Units. If you arent familiar with the Security Model features of Dataverse, its a bit of a learning curve but amazing once you get past that. Here are some starter links https://learn.microsoft.com/power-platform/admin/wp-security-cds https://learn.microsoft.com/power-platform/admin/control-user-access

Thanks for your help. I will take a look at that, and then if I can actually implement it I'll share it.

**Comment by Jenefer-Monroe** [comment]
You will have a very wonderful, powerful, and marketable skill when you get your head around that security model!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
