### ISSUE TITLE
[CoE Starter Kit - BUG] The setup wizard for the Center of Excellence (CoE) is unresponsive when attempting to configure it using the Audit Log component.

### ISSUE THREAD

**Issue by aarohbits** [microsoft/coe-starter-kit#7310]
### Does this bug already exist in our backlog?

- [X] I have checked and confirmed this is a new bug.

### Describe the issue

The **setup wizard for the Center of Excellence (CoE)** is unresponsive when attempting to configure it using the Audit Log component.  
Tried 3 different tenants and the results were the same. 

   
![Audit Componenet](https://github.com/microsoft/coe-starter-kit/assets/35991723/f2fcfbca-298c-42b4-92a3-ecf701f0fc95)

### Expected Behavior

It should be open up with configuration wizard just like other components Pulse, Maker assessment etc. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17 

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Tried it manually. 
1. Turned on CoE Core Solution >> Flows >> Admin | Audit Logs | Office 365 Management API Subscription 
2. The flow could not turn on. 

![Flow Issue](https://github.com/microsoft/coe-starter-kit/assets/35991723/5a459354-d895-4466-a182-81c4e0fd647a)

AB#1803

**Comment by v-bjaiswal** [comment]
Hi, 
Please validate that the Environment variable "" is filled up with the value. You can check it by going to "CoE Admin Command Center".

![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/ff71ff58-88b7-48e0-b9ac-61816608a861)

You can get more information from https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

**Comment by v-bjaiswal** [comment]
Hi, regarding the "Audit Log" component please look into the https://github.com/microsoft/coe-starter-kit/issues/7126 issue.
This has been resolved locally and is marked for January released. Till then please open the app manually from the app list.

**Comment by Jenefer-Monroe** [comment]
We are shipping later today or tomorrow  YAH so you will have this fix available. 
Closing out as no further action for starter kit team
