### ISSUE TITLE
[CoE Starter Kit - BUG] Not getting app last launched data 

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#7311]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have installed the coe starter kit byodl version 4.16 in our tenant in a fresh environment, the dataflow refresh is successful, we are getting app data in powerapp app table, but we are not getting app last launched date data in the table.
![image](https://github.com/microsoft/coe-starter-kit/assets/47393750/e950ada5-79a2-427e-9bd6-5f0e17770fbc)
![image](https://github.com/microsoft/coe-starter-kit/assets/47393750/352e2c3b-07f3-475c-b18e-ffd58549ebd1)

### Expected Behavior

We should get app last launched data in powerapp app table.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

coe byodl app last launched data dataflow

### What method are you using to get inventory and telemetry?

Data Export

AB#1804

**Comment by Rajatchopra3** [comment]
I suppose we are getting last launched data but only for last 30 days from the Coe starter kit installed date. And in all the records the time is 12:00 Am only.

<img width="149" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/daf4d9cb-960c-4cbd-88bd-15e7980cff00">

Is my understanding right, how can we get more than last 30 days.

**Comment by RahulBojji** [comment]
@Rajatchopra3
Can you please have a look at #7291 if this resolves your issue??

**Comment by Jenefer-Monroe** [comment]
Can you please confirm, are their blanks for Canvas apps as well?

**Comment by Rajatchopra3** [comment]
Closing the ticket as we are getting data, it is just we are getting last 30 days data that is due to dataflow query, on changing that we can get last x days data
