### ISSUE TITLE
[CoE Starter Kit - QUESTION] Blank records are saving in the PowerApps table

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#7316]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

After the inventory flow ran in PowerApps, we noticed that some blank records were added to the PowerApps table. 
I checked both the Power Platform Admin Center inventory and our Azure Data Lake (COE Environment with Data Export) inventory, but I couldn't find any apps created on that specific date(16th Dec, Saturday). 
It's puzzling why so many blank values were inserted into the Apps table on that date in our production environment (COE with regular flows). 

Verified inventory flows they are not failed and running successfully 

![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/0089d7ab-ba18-4d30-946a-2e86dde71841)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1814

**Comment by Jenefer-Monroe** [comment]
Can you please check the following for me? 

1. Can you confirm, are you using the Data Export feature? I'm just not sure from the language. Thank you!
1. Is the "Inventory Me" field flagged to yes for these? Thats another column in the table. 
1. Are their any fields filled in?

**Comment by pamatihyd** [comment]
Can you please check the following for me?

Can you confirm, are you using the Data Export feature? I'm just not sure from the language. **Regular Flows** 
Is the "Inventory Me" field flagged to yes for these? That's another column in the table.
**Inventory Me--No**
Are their any fields filled in?
How many are there?
**16**
If you delete them, do they come back?
**Not tested yet**

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team. Please try with the new version of the kit which has a big rewrite of the sync flows.
