### ISSUE TITLE
[CoE Starter Kit - QUESTION] Current Owner in Flow table

### ISSUE THREAD

**Issue by power-mike** [microsoft/coe-starter-kit#7317]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi CoE community
I have some cases, where the CoE Toolkit marks Flows as orphaned. Because the creator of the Flow is not there anymore.
In reality, the flow is not orphaned and has a new Owner that is also reflected in the "list flow owners" activity in power automate.

So the creator of the flow is not there anymore, but the flow has another owner and therefore is not orphaned.

In the flow table there still ist the creator of the flow listed as owner (derived owner). And when I look at the "SYNC HELPER - Cloud Flows" I see that this one is checking for the derivedOwner and orphaned state of the creator of the flow.

So my question, shouldn't be there a List Flow Owner Activity in this flow to check if the flow is really orphaned or if there are new owners and update the inventory accordingly? Or what is the concept to get new correct Owners into inventary?

It is a problem for us as we want to work with the orphaned flows and it lists a lot of such flows, that are not really orphaned and have new owners as described above.

Thank you for your support!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2023

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows  / Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1815

**Comment by Jenefer-Monroe** [comment]
Hello, we have not yet updated the kit to use this information but it is on our backlog. We are waiting for one more product change and then will fund this work. Please see [#3052](https://github.com/microsoft/coe-starter-kit/issues/3052)

**Comment by power-mike** [comment]
Thank you Jenefer-Monroe. Looking forward for this!

**Comment by Jenefer-Monroe** [comment]
ME TOO! :) 

I'll go ahead and close this out then.
