### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Check Deleted) Failing

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#7320]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The past two weeks this flow has been failing. CLEANUP - Admin | Sync Template v3 (Check Deleted). It has been failing at the last condition "See if anything Failed above". This part of the flow is being cancelled and I don't see why. The step above does have a status of True, but the step cancels and does not go through the true branch. I updated the starter kit on 11/29 with the November release. It ran on 12/2 and passed, but the last two weeks its failing. **Note:**  I keep trying to attach an image of the flow run, but the system is not letting me. It keeps removing it.

### Expected Behavior

I expect the condition to continue to the true branch instead of canceling.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

No steps to reproduce. I just checked the status of the flow run.

AB#1818

**Comment by Jenefer-Monroe** [comment]
Regarding inability to add pictures. I've seen that happen a few times, usually the next day I can add pictures. Just some GitHub intermittent bug. So please do try again. 

You should see something here that shows where the failure occurred. Do you know see anything in that call?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5d1bb990-6358-427b-9994-8144130ef62a)

**Comment by AUTigers16** [comment]
It still won't let me add the image. I see what you have in your screenshot except the condition "See if anything failed above" shows cancelled. The Compose step "Test- fail check" above it says true. It looks like the Condition fails, then I see where it looks like it gets to your highlighted step and then just stops. I will send the screenshot to you in email and reference this bug.

**Comment by Jenefer-Monroe** [comment]
Worked offline, here is the failure


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e9808521-8a7f-4405-9bdc-c25e5a9ee886)

**Comment by Jenefer-Monroe** [comment]
please see https://github.com/microsoft/coe-starter-kit/issues/7251, will mark as lf
