### ISSUE TITLE
[CoE Starter Kit - BUG] Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: {"error":{"code":"CannotDeleteApiDueToExistingConnections","message":"The custom connector admin-management cannot be deleted because there are connections associated with this api."}}.

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/coe-starter-kit#7323]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: {"error":{"code":"CannotDeleteApiDueToExistingConnections","message":"The custom connector admin-office-management- cannot be deleted because there are connections associated with this api."}}.

### Expected Behavior

When we try to import core component, it is failing with following error,

Unable to delete the custom connector, neither we are able to delete the connection eference, Audit log solution has been deleted

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Upgrade COE Core Component 

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/78148795/70f2f5c0-3eb2-45ee-bc90-fd16428efed1)

![image](https://github.com/microsoft/coe-starter-kit/assets/78148795/d4365416-5c05-467a-b8e9-a8b2d5ee090c)

![image](https://github.com/microsoft/coe-starter-kit/assets/78148795/08b96f86-10be-4d3f-bdea-d58d406494cf)

**Comment by ApoorvaKantale** [comment]
Can you please help me to delete the Office 365 Management API connection and Custom connector. SO I can upgrade my CORE Component

**Comment by RahulBojji** [comment]
Hi @ApoorvaKantale 

Thanks for reaching out. You can start initially by deleting the upgrade solution. Once upgrade solution is successfully deleted. Then Go to the Default Solution > Connnection References. Delete the connection references for Office 365 Management API
Same steps have been mentioned in below issues. Please have a look at issues mentioned below before proceeding
#6018 , #6270, #6816

**Comment by ApoorvaKantale** [comment]
Hi, 

I have tried all above steps, still it is not working

**Comment by Jenefer-Monroe** [comment]
Unfortunately we have seen people unable to delete all references easily as not all are exposed in the UX. 
These people have to use Power Shell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest)  these remaining connections to the old connector.

**Comment by ApoorvaKantale** [comment]
I'm able to find the connections reference in Default solution, but it is managed so unable to delete it 

![image](https://github.com/microsoft/coe-starter-kit/assets/78148795/dfcc18e7-e618-40a8-a3bb-d0522d4ce8d9)

**Comment by ApoorvaKantale** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/78148795/7f8a5113-49f3-471f-937f-280520997a92)

Through powershell also im unable to delete it, it says forbidden

**Comment by Jenefer-Monroe** [comment]
That is the **_connector_**, you need to find and delete the **_connections_**

In the UX that looks like this 

Connector  
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5e0e00d9-86aa-45b5-b35d-6612afd33036)

v this
Connection
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2167f615-ae51-46b2-98ee-6608c12d2aa1)

The Power Shell starters I shared are for connections not connectors. Please use them to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest)  these remaining **_connections_** to the old connector.

**Comment by ApoorvaKantale** [comment]
Hi ,

Thank you, it worked able to successfully install CORE component

**Comment by ApoorvaKantale** [comment]
Get-AdminPowerAppConnection -EnvironmentName [Guid]

Remove-AdminPowerAppConnection -ConnectionName [ConnectionName] -ConnectorName shared_twitter -EnvironmentName Default-[Guid]

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thanks for keeping at it! :)

I'll go ahead and close this then, thanks for using CoE
