### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis app - need search ability for envts since cannot show all in the drop down

### ISSUE THREAD

**Issue by cr0max** [microsoft/coe-starter-kit#7324]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We mainly use the DLP Impact analasis app for checking which policys that apply to different environments. But since the last update the search box can't find all environments. The list stops at "P" and any environment below that is not searchable or accessible. I have tried several different browser, to see if this was browser related, but it is not.

We have 811 active environments in the Environment table.
![image](https://github.com/microsoft/coe-starter-kit/assets/97740538/3457792d-e0a2-4c32-9901-9dc8ad7b6eb9)

 The collection shows 811 environments, but the combo box does not show all. 
![image](https://github.com/microsoft/coe-starter-kit/assets/97740538/eb5ef7ea-608b-46ab-9080-6e97473e3308)

The Impact Analysis Canvas App is setup to handle a data row limit of 2000. 
![image](https://github.com/microsoft/coe-starter-kit/assets/97740538/73be23de-f645-46eb-8149-2e600324991b)

But it still stops at 500, as I have selected all environments until where the combo box ends.
![image](https://github.com/microsoft/coe-starter-kit/assets/97740538/d24b099b-e2b3-44a2-baac-940b85942a33)

After investigating this and writing this bug report, I feel like this might be a Power App bug, more then a CoE bug.

### Expected Behavior

I expected to see all environments in our tenant.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17 (novemeber)

### What app or flow are you having the issue with?

DLP Impact Analysis

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1822

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of where in the DLP app you are experiencing this?

**Comment by cr0max** [comment]
Sure, it's the search combo box, when you search for your environments.
![image](https://github.com/microsoft/coe-starter-kit/assets/97740538/115fdd52-686a-4449-ac22-4ff1556d6f3b)

It doesn't show any environments after the 500 limit. It's also not possible to search for any environments past that limit.

**Comment by Jenefer-Monroe** [comment]
Aww yes. Thank you. Looks like we will need to add some kind of search methodology here to make it work. Sorry for this limit! 
Marking as a feature bug for that app.

**Comment by cr0max** [comment]
Thanks for the update.
However I can't remember that this has been an issue before our latest november update (we were running august before).
But it could be that I also did not try to search for any env that were below the 500 limit.

**Comment by cr0max** [comment]
Hello again, I think I need to reopen this. I finally got some time to review this, but it is still not working, for none of our admins, even though it is closed as completed.
![image](https://github.com/microsoft/coe-starter-kit/assets/97740538/c38670f1-3bb5-43ce-acb1-a2abc7035862)
