### ISSUE TITLE
[CoE Starter Kit - Feature]: Admin | Inactivity notifications v2 (Clean Up and Delete) Would like to Keep all the history of all the request.

### ISSUE THREAD

**Issue by cbennett8393** [microsoft/coe-starter-kit#7328]
### Is your feature request related to a problem? Please describe.

After a month, it tends to delete the history of the request. It would be nice to actually see all the request that went out. If a person never approved or rejected an inactive app or flow.
![image](https://github.com/microsoft/coe-starter-kit/assets/154289622/4d00cbcf-469a-4d17-8d95-74f4ec232337)

### Describe the solution you'd like

![image](https://github.com/microsoft/coe-starter-kit/assets/154289622/1da64f5f-7fe4-473e-ac13-5c1056b8c8fc)

After a month, it tends to delete the history of the request. It would be nice to actually see all the request that went out. If a person never approved or rejected an inactive app or flow.

AB#1832

**Comment by Jenefer-Monroe** [comment]
Hello. Thanks for posting. 
We used to do that actually and got a bunch of feedback that it was wasteful for space. It also made the logic more difficult to manage to have old ones laying around. 
So instead what we have is a date when the object had feedback requested.  

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fa022fd4-cb3a-43b2-8970-61b1b5bae227)

This date gets cleared when they respond so thats how you can tell how long they've been ignoring the requests. 

Hope that makes sense.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
