### ISSUE TITLE
[ALM Accelerator - QUESTION] How to force an update of deployment pipeline variables?

### ISSUE THREAD

**Issue by sefa-phaag** [microsoft/coe-starter-kit#7334]
### What is your question?

I have kind of a weird scenario. My company was purchased and so we have to move our ALM Accelerator / source code to the new tenant. I wanted to preserve my source code history (maybe a mistake, but we'll see), so I pushed the source code directly and created the various branches. I imported the unmanaged solution into my new development environment, created a solution profile, and committed the solution, but it didn't create the deployment pipelines, so I manually created them following the steps outlined here https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually. However, there are dozens of pipeline parameters and I suppose I could create them manually, but is there some way to get the accelerator app to create them like it normally does?

At what point, exactly, is it supposed to update the pipeline parameters when you add new deployment settings configurations? Half the time, if I make changes to the deployment settings and then commit the solution, it ends with a warning that no changes were committed to source control.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

November 2023

AB#1874

**Comment by RajeevPentyala** [comment]
@sefa-phaag The creation of 'pipelines' logic is in the 'Update Deployment Settings' task within the 'export-solution-to-git' pipeline. You can verify this by checking or sharing the log of the 'Update Deployment Settings' task to understand why the pipelines are not being created in your case.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/26dcc849-92e0-493d-b2b8-3c63f06f66f5)

Regarding your query about the warning _"it ends with a warning that no changes were committed to source control"_, it's expected. Subsequent commits won't alter anything at the repo level, unless you add new components to the solution, but will update the deployment pipeline variables.

**Comment by sefa-phaag** [comment]
I did my best to go through the log and templates / PowerShell and from what I can tell, by the time it finally calls Set-BuildDefinitionVariables, the parameter $newBuildDefinitionVariables is null. There aren't any errors, but it also never outputs the Body or BuildDefinitionResourceUrl like it should otherwise.

![image](https://github.com/microsoft/coe-starter-kit/assets/94123640/3d999e6d-7b6b-4bcc-9bc6-9690e8388693)

![image](https://github.com/microsoft/coe-starter-kit/assets/94123640/1cd92f7a-343d-4c27-a56d-42c8a5354fcb)

I can't figure out why they should be null, though. I verified that it found the build definition and that the variables property is not null (it has the required EnvironmentName and ServiceConnection variables defined). As far as I can tell, there's no other place that is setting it null, so I'm kind of at a loss.

![image](https://github.com/microsoft/coe-starter-kit/assets/94123640/ed4ec419-b28d-40c3-aba0-dd94dd358195)

![image](https://github.com/microsoft/coe-starter-kit/assets/94123640/3c68c112-ad28-47a7-bf9a-f79d25974591)

![image](https://github.com/microsoft/coe-starter-kit/assets/94123640/e8fcde5f-8597-4eed-87a3-d47b8eb7607b)

The full log is super long, but maybe it has something in it that I'm missing, but means something to you: [raw log.txt](https://github.com/microsoft/coe-starter-kit/files/13743010/raw.log.txt)

**Comment by RajeevPentyala** [comment]
@sefa-phaag We were unable to replicate this issue. Closing this issue for now. Kindly inform us if further assistance is required regarding this matter.

**Comment by mikefactorial** [comment]
@sefa-phaag thanks for following up and for detailing the issue. Always helps to get closure and I'm sure will help others as well. Thanks again!
