### ISSUE TITLE
[CoE Starter Kit - Bug] Cannot open the Core Admin | Sync Template v3 (Apps)

### ISSUE THREAD

**Issue by guillaumeKrupa** [microsoft/coe-starter-kit#734]
When we try to open the Power Automate Admin | Sync Template v3 (Apps), the page is blank.
We can open the Analytics but not the flow itself.
The "Center of Excellence - Core Components" solution is a managed solution. 
The flow if off due to an exceed of billable action, as I explain in the discussion (https://github.com/microsoft/coe-starter-kit/discussions/733).
Admin | Sync Template v3 (Flow Action Details) is turned off but editable.
Does this is related to licensing, or is this another issue ?
![Blank page for  Admin  Sync Template v3 -Apps](https://user-images.githubusercontent.com/26141208/124495493-787b4e80-ddb8-11eb-8303-9a00c824c2db.png)

**Comment by manuelap-msft** [comment]
Hello,

can you share a screenshot of the error you get from flow.microsoft.com when trying to Edit the flow?

Thank you
Manuela

**Comment by guillaumeKrupa** [comment]
Hello, Manuella, thanks for you quick answers. 
The page just turns white after a asecond. (The first screenshot was the errors in the console).
![Core components](https://user-images.githubusercontent.com/26141208/124554509-56281600-de36-11eb-95d4-82f13252f24e.png)
![white page](https://user-images.githubusercontent.com/26141208/124554526-5c1df700-de36-11eb-9fde-8e04a6f1bd95.png)

**Comment by guillaumeKrupa** [comment]
It seems the issue resolved itself this morning, shorly after I took the screenshot, after been turned off due to running too much actions. 
![Admin  Sync Template v3 -Apps resolved](https://user-images.githubusercontent.com/26141208/124566591-7ad6ba80-de43-11eb-80aa-4a31375d5a7a.png)
 (was occuring since last week).

**Comment by manuelap-msft** [comment]
Great, thanks for confirming. This is then not an issue with the CoE Starter Kit, but expected behaviour!
