### ISSUE TITLE
[CoE Starter Kit - BUG] Number of Apps/Flows not populating for Environments in Admin View app

### ISSUE THREAD

**Issue by accsimonwalsh** [microsoft/coe-starter-kit#7340]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In my Admin View app the "Active Environments" doesn't show any data:

![image](https://github.com/microsoft/coe-starter-kit/assets/126242929/dbc7ce75-a9c5-471d-81f1-1864354d4b06)

The Environments-table contains data, but does not get updated values for the flows/apps:

<img width="449" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/126242929/fedbd295-1773-45de-ba94-c9c6077adcaf">

All necessary cloud flows connected to the installations have been turned on and run successfully. Not sure what other sources of error that I'm missing, so would appreciate help on this matter. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1880

**Comment by Jenefer-Monroe** [comment]
These fields are roll up fields and so for a new install they take a while to update. It’s typically a 12 hour wait after the inventory completes before you can expect to see these populate but the product itself is what determines how frequently and when to update these roll up fields.
You can force these to calculate. Please see the tip in this product team article on [Rollup columns](https://learn.microsoft.com/power-apps/developer/data-platform/calculated-rollup-attributes#rollup-columns)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d374b7dc-82e2-499d-8855-be81a70bdb98)

**Comment by accsimonwalsh** [comment]
Thanks @Jenefer-Monroe, the rollup jobs had gone into error statuses and rerunning them solved the problem.
