### ISSUE TITLE
Core/Inventory Component Canvas Apps Dissappeared

### ISSUE THREAD

**Issue by VJGilead** [microsoft/coe-starter-kit#7342]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We've deployed the CoE Core component (inventory) successfully and verified all apps after installation. However, now after deploying the Governance component, we have noticed that 6 out of 14 Canvas apps are missing from Core component solutions. Can anyone help explain the issue or guide us in troubleshooting?

![Missing Canvas Apps](https://github.com/microsoft/coe-starter-kit/assets/154487730/8d9244bf-4ac5-4adf-a0f4-ae01230926f1)

![Missing Canvas Apps](https://github.com/microsoft/coe-starter-kit/assets/154487730/7fd6c574-6f7f-4b6a-b8b1-96a9eb8d1de9)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin - Access this App

### What method are you using to get inventory and telemetry?

None

AB#1883

**Comment by Jenefer-Monroe** [comment]
Hello. I'm sorry I'm not following you. Core currently ships with 14 apps: 6 Canvas, 8 Model Driven. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e43044bb-bb10-447a-be04-cae0abd3192d)

Gov has 3 apps: 2 canvas and 1 MDA
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ef4ff118-09eb-48ff-bbff-15088e9d6b8e)

You picture shows all the canvas apps present in both pictures. Can you please help me understand your issue a little better?

**Comment by VJGilead** [comment]
Hi Jenifer, thank you for your comment. The image in my post was originally taken upon completing the deployment of the core solution, and is now being used to identify which apps are we missing in our Prod environment. All 14 apps, including the highlighted apps deployed successfully upon completing the core solution installation, but are now missing from the core solution after the Governance deployment. Hope that clarifies.

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of where you are looking and expecting to see them? 
They are in there so you may be looking in the wrong place. 
Or perhaps, are you logged in as a different user than installed?

**Comment by spriya07** [comment]
Hi Jenefer,

The canvas apps in Centre of Excellence – Core components solution were deleted and we restored them. They appear in apps section in the environment. But, it doesn’t display in the solution.

Is there any way to add the apps in the managed solution?
If not, will there be any issues if the apps are not under the solution? Can we proceed with the setup?

Attached screenshots of apps and solution sections.

![CoE - Apps section](https://github.com/microsoft/coe-starter-kit/assets/155008952/507f03e8-c091-4c6d-ae6d-601db9dc46cb)
![CoE - core components solution](https://github.com/microsoft/coe-starter-kit/assets/155008952/a80c278e-bb89-4e3b-99a5-f078c5398970)

**Comment by Jenefer-Monroe** [comment]
ok I see. I believe this is due to them not being shared with you then. You must have installed as another identity that you are logging in with. 
If you share them with yourself (via Power Platform Admin View) you will se them.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e02e1c05-082f-41b7-ac97-3edb8122848b)


I'm not sure what you mean by "restored them" so I dont know what state you are in now.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
