### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Check Deleted) - Erro

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#7348]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

Please the FLOW: CLEANUP - Admin | Sync Model v3 (Check Deleted),
is having trouble getting to the Delete Old CoE Inventory Items step, with the message: This entity is being deleted as part of an asynchronous cascade delete job. Wait for the asynchronous job to complete before trying to delete this entity again. You can query the status of this job by searching for the following AsyncJobName in the system jobs view. (EntityId: 3f0b19c5-e144-42d9-810d-fee31c78f193, EntityName: admin_App, AsyncJobName: Cascade Delete:[admin_App]-[3f0b19c5-e144-42d9-810d-fee31c78f193], AsyncJobId: 556251b 2- f 799-ee11-be37- 000d3a88675f, AsyncDeleteOperationId: 8d030c8f-6805-428b-bda7-2ecef506543e)

Do you know what could be causing this error?

![Erro fluxo 1](https://github.com/microsoft/coe-starter-kit/assets/129080740/56f05a19-0c25-48a9-8b79-5565c9ffb244)

### Expected Behavior

Updating the inventory of deleted applications and flows

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1892

**Comment by Jenefer-Monroe** [comment]
Sounds like a background operation performed by the product is occurring. You will need to just wait and try again later unfortunately. 
The new versions of this flow (see https://github.com/microsoft/coe-starter-kit/issues/7322) no longer has this long chain of activity so you wont see this in the new flows either.

**Comment by minobrega** [comment]
I understand,

OK, I'll wait for the next official release to update the core components then...

Thanks a lot for the help..

**Comment by Jenefer-Monroe** [comment]
You are so welcome. Thank you for posting!

**Comment by Jenefer-Monroe** [comment]
We are shipping the new release today or tomorrow. YAH!
Closing out as no further action for starter kit team

**Comment by minobrega** [comment]
hi jenefer

Please, I updated CoE today with the most current version 4.22, but this error persists.

Do you know if you need to make any further configuration for this flow to work ?

![versão atual coe](https://github.com/microsoft/coe-starter-kit/assets/129080740/1112c766-3f37-4859-b91f-18e7ee13ad1a)

![Erro após versão atual](https://github.com/microsoft/coe-starter-kit/assets/129080740/823bed28-4fee-4763-b6f7-f4e608b031d2)
