### ISSUE TITLE
[CoE Starter Kit - BUG] Power Automate Flow Owner is not updating in Power BI Report

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#7349]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Power Automate Flow Owner is not updating.

### Expected Behavior

We have 3 Power Automate workflows that was recently orphaned, we already transferred the ownership to another individual by using a solution and the data has already been updated in the **Flow** table but is not reflecting in the Power BI Report.

**Power BI Repor (Old Owner):**
![Power BI Report (Old Owner)](https://github.com/microsoft/coe-starter-kit/assets/119695189/e3a0a619-131c-4333-a63b-547207272271)

**Flow Table (New Owner)**
![Flow Table (New Owner)](https://github.com/microsoft/coe-starter-kit/assets/119695189/8055bc53-ab47-470a-b394-faef131d8919)

It might also be worth noting that the 3 flows are part of the Default Solution, I'm not sure if that has an impact in terms of updating the flow ownership.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

CoE Starter Kit Power BI Report (June 2023)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open CoE Starter Kit Power BI Report.
2. Go to Cloud Flows.
3. Filter Cloud Flows to Old Owner.

AB#1893

**Comment by Jenefer-Monroe** [comment]
Hello, we have not yet updated the kit to use the information from the product when you chaneg owner through the product, but it is on our backlog. We are waiting for one more product change and then will fund this work. Please see [#3052](https://github.com/microsoft/coe-starter-kit/issues/3052)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
