### ISSUE TITLE
[CoE Starter Kit - QUESTION] What is the best way to change the sender of the Approval email?

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#7350]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,
Is there a way to change the sender of the approval emails that are sent on the inactivity process?

![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/f3bbef44-0253-45ac-b54c-6c622482b8c7)

I tried to add a service account on the 'Send on behalf' field, but the email is coming with wrong formatting. 

![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/366cdaee-c5cc-4272-8adc-f9c5359373bc)

Not sure if it's because of this note here, saying that approvals are not available for preview:

![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/08d85155-83e1-4a1d-9ef3-7ad28eddbbc0)

Thanks for the support!

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

November 2023

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1894

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately, approvals cannot participate in that feature as it is sent by the product itself and not by us.

**Comment by LucX4** [comment]
Hi @Jenefer-Monroe,

So, even changing the 'Send on behalf' field won't change anything?

**Comment by Jenefer-Monroe** [comment]
No it wont. We cannot control who these are sent from unfortunately.

**Comment by LucX4** [comment]
Ok @Jenefer-Monroe, thanks for clarifying! 
Wish you great Holidays.

**Comment by Jenefer-Monroe** [comment]
Thank you! Have a great holiday!
