### ISSUE TITLE
I can't open either of the two Command Centers as Play, only as Edit, which isn't full featured.

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#7351]
In fact, I can't Play any of the CoE PowerApps.

When I try to Play, I get this error:

Error Code: 2147746581
Session Id: deb2b61e-96fc-4a2d-a0d8-e088d4f1d5f4
Timestamp: Fri Dec 22 2023 13:47:38 GMT-0500 (Eastern Standard Time)
RetrieveUserContext: Cannot read properties of undefined (reading 'guid')
TypeError: Cannot read properties of undefined (reading 'guid') at https://content.powerapps.com/resource/uci-infra/scripts/app.c214471822fa9da395331e129d2dee0c.js:14:874176 at https://content.powerapps.com/resource/uci-infra/scripts/app.c214471822fa9da395331e129d2dee0c.js:14:874348 at async Object.boot (https://content.powerapps.com/resource/uci-infra/scripts/app.c214471822fa9da395331e129d2dee0c.js:14:871337)

AB#1895

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by RickKush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/e9326ccb-ac3a-42be-aded-5f9bccea8f49)

**Comment by RickKush** [comment]
[Center of Excellence - Core Components_import (2).zip](https://github.com/microsoft/coe-starter-kit/files/13822744/Center.of.Excellence.-.Core.Components_import.2.zip)

**Comment by RickKush** [comment]
I tried to upgrade to 4.17, and I got error code: 80048539

Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :Solution manifest import: FAILURE: Holding solution CenterofExcellenceCoreComponents_Upgrade already exists.



From: Jenefer Monroe ***@***.***>
Sent: Wednesday, January 3, 2024 12:10 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] I can't open either of the two Command Centers as Play, only as Edit, which isn't full featured. (Issue #7351)


Closed #7351<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/issues/7351__;!!May37g!IS3uoIrhIHQJTAyfjRgJAlPN-m7GMWTJVg1vI7y2tZe-z7vYyk2imtWjLUvC9Lscu_j9e5XYhr9FhAyK2FhrKGZlNA$> as completed.

-
