### ISSUE TITLE
[CoE Starter Kit - When will the DECEMBER 2023 kit will be released?

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#7353]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When will the DECEMBER 2023 kit will be released? we see some issue in our older release, waiting for December release. Please let us know when we will get the latest December Kit.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What method are you using to get inventory and telemetry?

Data Export

AB#1902

**Comment by Jenefer-Monroe** [comment]
The testing for the big changes to the kits inventory system (including the Data Export one) took longer than expected so we skipped the Dec release as a result. 
We have an early release available for testing of this big release. Please see https://github.com/microsoft/coe-starter-kit/issues/7322
Plan is to ship this as the Jan release.

**Comment by ALSPowerPlatform** [comment]
can you please give the Transform file 9 code for COE BYODL Flows dataflow

**Comment by Jenefer-Monroe** [comment]
Im sorry I dont know what that means. 
Please take a look at these two issues tracking the new release's early testing and see if you find anything related to your issue: 
https://github.com/microsoft/coe-starter-kit/issues/7322
https://github.com/microsoft/coe-starter-kit/issues/7345

**Comment by Jenefer-Monroe** [comment]
We will be shipping the new Jan release today or tomorrow! YAH!
closing out as no further action for starter kit team

**Comment by ALSPowerPlatform** [comment]
@Jenefer-Monroe  could you please help us with Transform file 9 code for COE BYODL Flows dataflow, the script is failing for us not updating flows to dataverse tables.
