### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYODL and historic data

### ISSUE THREAD

**Issue by nrd2015** [microsoft/coe-starter-kit#7354]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Dear Experts,

We are planning to upgrade the CoE toolkit to November release from February release and start using the BYODL. Can you please confirm if we need to perform any specific actions to view the historic data for our apps and flows in the Power BI report and the Power Platform dashboard model driven app ?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1904

**Comment by Jenefer-Monroe** [comment]
There there no required actions to transition from Sync Flow architecture to Data Export architecture aside from what you will be walked through with the Setup Wizard

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
