### ISSUE TITLE
admin_ConnectionReferenceidentityBase table takes up a lot of space in Dynamics 365. What is the purpose of this table?

### ISSUE THREAD

**Issue by Alexairrrr** [microsoft/coe-starter-kit#7357]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

admin_ConnectionReferenceidentityBase table takes up a lot of space in Dynamics 365. What is the purpose of this table and if deleting the data from this table has any impact on the environment？How should I delete it.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1907

**Comment by RahulBojji** [comment]
@Alexairrrr 
admin_ConnectionReferenceidentityBase stores the identity with which a connector is connected in an environment. For example if you are using a Dataverse connector which is used in flows is connected with a "admin@123456.onmicrosoft.com" account 
in Connection reference Identity Base table this information is stored. It captures the following information.

1. Connector -   the connector in use
2. Account Name - alias of service account or user account used to create a connection.
3. Connection Ref - power platform user reference
4. Environment - environment in which the connector is being used.

I suggest not to delete these.

**Comment by Jenefer-Monroe** [comment]
Quite a few months ago we did have a bug that was adding duplicate entries to this table. 
So depending on what version you are on, you could empty this table and let it refill and it will likely be smaller.

**Comment by Alexairrrr** [comment]
Thanks for the answer! 
We are using CenterofExcellenceCoreComponents_4.2, If I want to delete a record from this table can I use Bulk delete？ How can I let it refill after deletion?

**Comment by RahulBojji** [comment]
I believe you should be able to use Bulk delete if you want to delete those. The **Admin | Sync Template v3 (Driver)** which runs daily will check for changes and in turn triggers **Admin | Sync Template v3 (Connection Identities)** which will add data into the "admin_ConnectionReferenceidentityBase" table

**Comment by Alexairrrr** [comment]
Can I understand that after running bulk delete, the system will automatically re-synchronize the data to the table a day later?

**Comment by RahulBojji** [comment]
@Alexairrr Yes, Correct

**Comment by Alexairrrr** [comment]
If we don't upgrade CoE and directly delete the records of this table, can we temporarily clear the space usage of this table and at most duplicates will be written again subsequently. Does deleting records directly in the current version 4.2 have any impact on the use of CoE?

**Comment by RahulBojji** [comment]
@alexiarrr If you are deleting in the current version, there might be a chance of duplicate records getting inserted because of a bug which was mentioned above.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
