### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to remove connection reference from Audit log

### ISSUE THREAD

**Issue by rajaug3** [microsoft/coe-starter-kit#7358]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am try to remove the Audit log component from COE starter kit. Getting below error and unable to upgrade to newer version. Even we have tried to remove through powershell script, but no luck.
Exception message
Solution dependencies exist, cannot uninstall. DependencyCount : 30 RequiredComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Copy of - Admin | Sync Audit Logs, Id: 075833af-93de-ed11-a7c7-00224827b681, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: ChangedFlow - Admin | Sync Audit Logs, Id: 31d99671-a6de-ed11-a7c7-0022482a466b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: EnvironmentVariableDefinition, ObjectName: admin_StartTimeInterval, Id: 6ff0f71f-512f-4a52-a1b1-1b8625ef76ed, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: ChangedFlow - Admin | Sync Audit Logs, Id: 31d99671-a6de-ed11-a7c7-0022482a466b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: EnvironmentVariableDefinition, ObjectName: admin_StartTimeUnit, Id: b7e30647-7756-4b84-9a6a-232b27ba5f16, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: ChangedFlow - Admin | Sync Audit Logs, Id: 31d99671-a6de-ed11-a7c7-0022482a466b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: EnvironmentVariableDefinition, ObjectName: admin_TimeIntervalInterval, Id: f16d9640-9f22-494f-83da-32506412cd08, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: ChangedFlow - Admin | Sync Audit Logs, Id: 31d99671-a6de-ed11-a7c7-0022482a466b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: EnvironmentVariableDefinition, ObjectName: admin_TimeIntervalUnit, Id: 888c0303-9dc0-4123-9027-e6fb4ac2c665, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: ChangedFlow - Admin | Sync Audit Logs, Id: 31d99671-a6de-ed11-a7c7-0022482a466b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Template v3 (Solutions), Id: ee5e288e-42f2-ec11-bb3d-000d3a1342bf, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Template v3, Id: 9e9fff08-a643-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Orphaned Makers), Id: e05cfb27-740d-eb11-a814-000d3a1bb7bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Command Center App > Initially Populate Bookmarks, Id: 81ea7ac4-910a-ec11-b6e6-000d3a8c225c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Request Orphaned Objects Reassigned (Child), Id: a405dd4c-78e5-eb11-bacb-000d3a8edeaa, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Clean Up of Microsoft Teams environments - Upsert Records, Id: f846b73e-b6dd-eb11-bacb-000d3a8eeb41, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Template v3 (Connectors), Id: 7e1ddb35-613d-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP - Admin | Sync Template v3 (Check Deleted), Id: 41419923-ab44-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP HELPER - Check Deleted (Business Process Flows), Id: bc9de9b5-a8ed-ec11-bb3d-000d3a8fbe6e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Template v3 (PVA Usage), Id: 789b0f18-115b-ed11-9561-0022480462ed, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Add Maker to Group, Id: 0ad4fe7a-6a5f-ec11-8f8f-0022481d6e1e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Template v3 (Call Updates), Id: c41e6337-aa28-ed11-9db1-0022481ff2d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP HELPER - Check Deleted (Ai Models), Id: 37aaead3-1e31-ed11-9db3-002248226dcd, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: SetupWizard>GetCurrentEnvironment, Id: a13c1774-0723-ed11-b83e-00224822e3b9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP HELPER - Check Deleted (Canvas Apps), Id: 2e6ae3e2-8afb-eb11-94ef-002248237d7d, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Template v3 (Connection Identities), Id: 7deee377-b0d1-ec11-a7b5-002248250ae2, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - ObjectOperations, Id: 6fda1b2d-3904-ec11-94ef-00224826a4d2, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Copy of - Admin | Sync Audit Logs, Id: 075833af-93de-ed11-a7c7-00224827b681, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - Maker Check, Id: 9301f01a-cb40-ec11-8c62-00224829b4c1, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: ChangedFlow - Admin | Sync Audit Logs, Id: 31d99671-a6de-ed11-a7c7-0022482a466b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Command Center App > Set CoE Flows State, Id: 21a5c4f1-5080-ec11-8d21-002248320bcd, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedcommondataserviceforapps_8f10b, Id: 5eb14462-3ce6-414e-af3f-6441e06cc9d8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: SetupWizard>ShareApps, Id: 1ff39c14-fe60-ed11-9561-6045bd07536e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.3

### What app or flow are you having the issue with?

Admin | Sync Audit Logs

### What method are you using to get inventory and telemetry?

None

AB#1908

**Comment by RahulBojji** [comment]
@rajaug3 
Can you please let us know exactly which component you are trying to remove and the steps you followed?

**Comment by rajaug3** [comment]
@RahulBojji ,  I'm try to remove Audit log component as it's been obsolete in latest version. I have removed all dependencies except admin_sharedcommondataserviceforapps_8f10b connection reference. Through PowerShell script i'm able to run deletion command successfully. but not getting deleted.

**Comment by RahulBojji** [comment]
@rajaug3 

Please make sure you are following below steps.
1. Delete the connection Reference not the connector for the component you are trying to delete.
![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/3a6a2383-a10d-48fe-be14-2f312d94fa7f)
2. Also, please use them to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) these remaining connections to the old connector.
3.  Try to use the below powershell script if the above doesn't work

Get-AdminPowerAppConnection -EnvironmentName [Guid]
Remove-AdminPowerAppConnection -ConnectionName [ConnectionName] -ConnectorName shared_twitter -EnvironmentName Default-[Guid]


Please have a look at the similar issue for the same #7323.

**Comment by rajaug3** [comment]
@RahulBojji , I have tried the above steps. Received below msg. But no luck
![image](https://github.com/microsoft/coe-starter-kit/assets/80772804/0d833dda-0a7a-48e2-ae10-cd163d0650dd)
Then tried to delete COE audit logs and it shows me dependency
![image](https://github.com/microsoft/coe-starter-kit/assets/80772804/9540828d-1203-4dd1-bda4-65b7780b34ff)
and found below which i deleted in first step through powershell script
![image](https://github.com/microsoft/coe-starter-kit/assets/80772804/6073b3fb-ee55-48e3-bc65-37a81d272fc2)

**Comment by Jenefer-Monroe** [comment]
It looks like those two flows (**_Admin | Sync Template v3_** and **_Admin | Sync Template v3 (Solutions)_**) are pointing to the wrong connection reference. 
Can you please go see if they have unmanaged layers on them? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9b93b9b9-6bdd-414e-a42f-1fd8f9e22734)

Can you also validate? Are you on Core version 3.3? This would mean you last installed early 2022. Just making sure I understand.

**Comment by rajaug3** [comment]
@Jenefer-Monroe , Yes, it has, Should i delete it. 
![image](https://github.com/microsoft/coe-starter-kit/assets/80772804/f8ac9f86-2dfa-4d58-8bba-8d5b55799dd0)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
