### ISSUE TITLE
[CoE Starter Kit - BUG] Env Request | Cleanup Environments does not delete expired environments 

### ISSUE THREAD

**Issue by ghy8** [microsoft/coe-starter-kit#7359]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Asking for a Delete reason to delete the expired environment but that field itself is not existed how can I rectify it.

<img width="960" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/155138747/4c99c611-aeb5-4f29-b8ed-98c92e6e4a41">
 
 Help me to rectify this

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Env Request | Cleanup

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1911

**Comment by RahulBojji** [comment]
@ghy8
Looks like you are editing the existing flow by making a copy of it. Can you please check if the original flow gives the same error. If yes, can you please go to the action "Delete_expired_environment" in that CleanUp Environment Scope and click on the action and share us the request and response.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by tocri** [comment]
I alsa have the same issue @Jenefer-Monroe  @RahulBojji 
Here are the screenshots as requested

<img width="298" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/d83b9397-645d-4e98-a55b-eb02dc47e63c">
<img width="945" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/a92e1e9e-1371-46fc-aae9-ee641a269c2d">
