### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 CoE Solution Metadata failed to execute

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoft/coe-starter-kit#7361]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v3 CoE Solution Metadata failed to execute with this error message:

The access token has been obtained from wrong audience or resource 'https://graph.microsoft.com/'. It should exactly match (including forward slash) with one of the allowed audiences 'https://service.flow.microsoft.com/','https://management.core.windows.net/','https://management.azure.com/','https://service.powerapps.com/','https://service.kratosapps.com/'

### Expected Behavior

Should be run successful 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Failed to Run after installing the core CoE 4.17

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/b34f0e64-e895-4730-a108-8cc21b1d13ae)

AB#1920

**Comment by RahulBojji** [comment]
@sharmajitendralal 
Looks like your connection is broken. Can you check if all the connections are configured perfectly?

<img width="921" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/fceb16f1-082a-4abc-838c-d0998e5b701e">

**Comment by sharmajitendralal** [comment]
No, As you see in below screen shot all connections are connected and there is no break, only issue with "List Flow as Admin" action, However there is no connection issue

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/a4b08ebe-e893-4e9b-916a-4c99ceb6b231)

![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/1d0384a9-1b4c-4539-ad74-404a351d163d)

Screen Shot: This is new flow created to test the the existing connection and its seems working fine
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/2df9fad0-7c55-469b-a5d4-e20e34d0fb15)

**Comment by RahulBojji** [comment]
can you please confirm if the connection used in the newly created test flow is same as used in the main flow. 
If it's same, can you try running the main flow again. 
If it fails again, we can give it a try by running the test flow with the same parameters used in the main flow.

**Comment by sharmajitendralal** [comment]
I am not sure, How we can verify which one in use on test flow.
There is many connection visible here in screen shot:
![image](https://github.com/microsoft/coe-starter-kit/assets/30046543/7eea5efb-2b66-4fbe-80d4-6eace7a0aba0)

**Comment by RahulBojji** [comment]
<img width="774" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/a7ac4492-5d2e-44ec-bb61-ceeb74738b62">

In all the list of connections getting displayed, the one selected will have check mark like above. Can you compare the account used in test flow and in the main flow whether it is same or not?

Ideally, if it is working in the test flow then it should also work in the main flow.

**Comment by sharmajitendralal** [comment]
Seems that issue has been resolved but due to some modification unmanaged layer created.

I will keep in watch on this week and let you know about the Status till day after tomorrow.

**Comment by RahulBojji** [comment]
Sure, Thanks for the update

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
