### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - Which flow synchronizes the environment information? 

### ISSUE THREAD

**Issue by pp-panda** [microsoft/coe-starter-kit#7362]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Because the flow only collects the add-ons data but not the data of the environment? Because the flow Admin | Sync Template v3 (Environment Properties) only collects the add-ons data but not the data of the environment. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What method are you using to get inventory and telemetry?

None

AB#1921

**Comment by pp-panda** [comment]
Im searching for the Sync Flow, wich collects and write the information about the Environments into the Environment Table.

**Comment by RahulBojji** [comment]
@pp-panda 
**Admin | Sync Template v3 (Driver)** is the sync flow which add details related to environments in Environments Table

**Comment by pp-panda** [comment]
Thank you very much!
