### ISSUE TITLE
Cannot Update a mail-enabled security groups and or distribution list.

### ISSUE THREAD

**Issue by guymartinello** [microsoft/coe-starter-kit#7363]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am receiving "Cannot Update a mail-enabled security groups and or distribution list." for "Admin | Add Maker to Group" flow.
Is there a document specifically outlining how this group should be created that I can pass along to the Exchange/AAD administrators?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

CenterofExcellenceCoreComponents_4.17_managed

### What app or flow are you having the issue with?

Admin | Add Maker to Group

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1926

**Comment by Jenefer-Monroe** [comment]
Hello. We have this documented here. [How will you communicate with your admins, makers, and users?](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users)

We recommend using [Microsoft 365 Groups](https://learn.microsoft.com/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide#microsoft-365-groups). And then here are the other requirements:
- must be an email-enabled security group
- admin or service account setting up the [inventory components](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components) needs to be an owner of the group.
- cannot be a group created in Exchange on-prem and synchronized to O365

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
