### ISSUE TITLE
How to route makers away from Admin Centre for new Environment Creation

### ISSUE THREAD

**Issue by guymartinello** [microsoft/coe-starter-kit#7364]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have enabled (I think) the Admin Maker Environment Request portion of the CoE Core Components.  
With my test user, I noticed that they are still able to go to "https://admin.powerplatform.microsoft.com/environments" and either create a new environment (if permitted by Tenant settings) or, if not limited by tenant settings, create and receive a message of "Your tenant's administrators have disabled XXX creation for non-admin users...".

Is there a way to force them over to the CoE Maker Command Center - or to update the default message to make it more clear to the maker as to what they need to do?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_4.17_managed

### What app or flow are you having the issue with?

CoE Maker Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1928

**Comment by Jenefer-Monroe** [comment]
You can block people from creating envts in the admin pages yes. Here is now to do that, its a product feature you will use:
[Control who can create and manage environments in the Power Platform admin center](https://learn.microsoft.com/power-platform/admin/control-environment-creation)

There isnt a way to send them to the CoE elements from within the admin pages as we are just an add on tool.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
