### ISSUE TITLE
[CoE Starter Kit - QUESTION] can't import CenterofExcellenceCoreComponents_4.17 - The user, group or application does not have secrets get permission on key vault

### ISSUE THREAD

**Issue by wfw2046** [microsoft/coe-starter-kit#7368]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

can't import CenterofExcellenceCoreComponents_4.17_managed.zip,  our account  is in China  region,  encounter an 403 issue when importing
Error code
[80040224](http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=80040224&de=online)
Exception message
Exception while acquiring token: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: KeyVaultServiceProvider.GetKeyValueFromKeyVault error getting MicrosoftMashupWebDataflowCrmPlugin-AppId - Service request failed. Status: 403 (Forbidden) Content: {"error":{"code":"Forbidden","message":"The user, group or application 'appid=00000007-0000-0000-c000-000000000000;oid=0a24752c-7660-411f-b242-eba1f47df663;iss=https://sts.chinacloudapi.cn/a55a4d5b-9241-49b1-b4ff-befa8db00269/' does not have secrets get permission on key vault 'pqo-cc-ce2-crmplugin;location=chinaeast2'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287","innererror":{"code":"AccessDenied"}}} Headers: Pragma: no-cache x-ms-keyvault-region: chinaeast2 x-ms-client-request-id: b2f7fa6b-27f2-462b-a8aa-7ab72cbafc30 x-ms-request-id: b1e0a7f7-84dc-4dcf-98d0-a6b22cfe976a x-ms-keyvault-service-version: 1.9.1116.1 x-ms-keyvault-network-info: conn_type=Ipv4;addr=163.228.73.52;act_addr_fam=InterNetwork; X-Content-Type-Options: REDACTED Strict-Transport-Security: REDACTED Content-Length:... (Fault Detail is equal to Exception details: ErrorCode: 0x8009100C Message: KeyVaultServiceProvider.GetKeyValueFromKeyVault error getting MicrosoftMashupWebDataflowCrmPlugin-AppId - Service request failed. Status: 403 (Forbidden) Content: {"error":{"code":"Forbidden","message":"The user, group or application 'appid=00000007-0000-0000-c000-000000000000;oid=0a24752c-7660-411f-b242-eba1f47df663;iss=https://sts.chinacloudapi.cn/a55a4d5b-9241-49b1-b4ff-befa8db00269/' does not have secrets get permission on key vault 'pqo-cc-ce2-crmplugin;location=chinaeast2'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287","innererror":{"code":"AccessDenied"}}} Headers: Pragma: no-cache x-ms-keyvault-region: chinaeast2 x-ms-client-request-id: b2f7fa6b-27f2-462b-a8aa-7ab72cbafc30 x-ms-request-id: b1e0a7f7-84dc-4dcf-98d0-a6b22cfe976a x-ms-keyvault-service-version: 1.9.1116.1 x-ms-keyvault-network-info: conn_type=Ipv4;addr=163.228.73.52;act_addr_fam=InterNetwork; X-Content-Type-Options: REDACTED ...).

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1932

**Comment by Jenefer-Monroe** [comment]
We've seen this before when people try to enter secrets in the env variables while importing. 
Please see [Set up the Inventory components using the Setup Wizard](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-using-the-setup-wizard)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c42c5166-4aac-4ba8-a273-1762e1512475)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
