### ISSUE TITLE
[ALM Accelerator - BUG]:  Issue with sharing connection with SPN when moving to Test Environment

### ISSUE THREAD

**Issue by groypk** [microsoft/coe-starter-kit#7369]
### Describe the issue

Noticed this for a few deployments, users have updated the Deployment Settings correctly for connection references and  clicked on SHare ALl to share the connection with the SPN, but the deployment still fails in Test Environments saying the spn does not have the needed access.

As a workaround when I manually go into the Test environment and share the connection with the SPN it works.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231012.1

### Steps To Reproduce

1. Go to ALM Acc App
2. Choose your Deployment User and Dev Environment
3. Set the Deployment Profile
4. GO to your solution and update the Deployment Settings
5. Create and share your connection reference with the SPN
6. Commit the solution
7. Deploy to Test ( fails because cannot detect shared connection)
8. Deploy to Prod works

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/5492973/c58d37fd-a429-4f2d-95e7-4a6c886f4e07)

AB#1933

**Comment by RajeevPentyala** [comment]
@groypk Issue might be similar to #6971 when there are multiple connections. This has been addressed and will be available in the next release.

**Comment by groypk** [comment]
> @groypk Issue might be similar to #6971 when there are multiple connections. This has been addressed and will be available in the next release.

Hi Rajeev, I had a look at the bug, in their case the connections are all pointing to one, in ours the connection is not being shared with the Service Principal at all even when Share All  has been entered, could be related to the config file settings

**Comment by groypk** [comment]
> @groypk Can you confirm if you've shared the connections with the 'Deployment User' before deploying the solution?. In order for your solution to be deployed successfully your connection(s) must be shared with the deployment user (i.e., Your pipelines service connection principal user). Please be aware that simply checking the 'Share All' checkbox in 'Deployment settings' won't work unless you manually share the connections with the 'Deployment User'.
> 
> ![image](https://private-user-images.githubusercontent.com/104883923/294138803-ccad3662-4d64-4683-b93e-0926135e41b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzA1MjUsIm5iZiI6MTcwNDM3MDIyNSwicGF0aCI6Ii8xMDQ4ODM5MjMvMjk0MTM4ODAzLWNjYWQzNjYyLTRkNjQtNDY4My1iOTNlLTA5MjYxMzVlNDFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMjEwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2VkZjBmY2RhYjQxMDY5Y2UzZDNmODM3MGY1YmY2MWJhM2IyNzc0N2JjMjgyOGFkZjg3YTZiMjU5NmYyOTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8OeKZfgD9ylDIEkcJSNIpgaqI46rFnU4BA86avT3fqY)

Hi Rajeev, we don't manually share the connections in Production, and the flows work, from what I understand the tool takes care of this and there is no need to manually share the connections with the SPN? This is what we have been following and the pipelines have worked until recently where a few users reported this issue, then having the share button defeats the purpose right?

**Comment by RajeevPentyala** [comment]
@groypk When I mention that the connection needs to be shared manually, users must select the 'Share' or 'Share All' checkbox, which you are already doing according to the issue description.

After selecting 'Share' and saving the settings, can you confirm if the 'ShareConnectionWithServicePrincipal' flow is triggered?. 'ShareConnectionWithServicePrincipal' is the flow comes with 'ALM Accelerator' solution.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/af231a40-19ca-4804-940c-e1c2d699e254)

**Comment by groypk** [comment]
> @groypk When I mention that the connection needs to be shared manually, users must select the 'Share' or 'Share All' checkbox, which you are already doing according to the issue description.
> 
> After selecting 'Share' and saving the settings, can you confirm if the 'ShareConnectionWithServicePrincipal' flow is triggered?. 'ShareConnectionWithServicePrincipal' is the flow comes with 'ALM Accelerator' solution.
> 
> ![image](https://private-user-images.githubusercontent.com/104883923/294445905-af231a40-19ca-4804-940c-e1c2d699e254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODcyMzcsIm5iZiI6MTcwNTY4NjkzNywicGF0aCI6Ii8xMDQ4ODM5MjMvMjk0NDQ1OTA1LWFmMjMxYTQwLTE5Y2EtNDgwNC05NDBjLWUxYzJkNjk5ZTI1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNzU1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWVhODFiMjIxN2Q3ZjI4OWY3ZmMzOTc2NWFkNzM3ZDBjMzg0NjI0N2RlMGRmMDUwZTgxNWU4ZTVhMjBkMDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jenR0W843oSLS1WxKnyz6PNA_8Acd4iUZ2ETJMYEHRM)

Hi Rajeev, Apologies for the delay I missed the notification, in flow history I see that the flow has run but not sure what is the trigger for the flow is it selecting the check box or when I save deployment settings?

**Comment by groypk** [comment]
HI @RajeevPentyala , I do see flow runs in  history but will confirm if it runs every time I save the settings.

**Comment by groypk** [comment]
Hi @RajeevPentyala , the flow is running but not always, looks like the trigger may not be working , as a work around we have been manually sharing the connections, is there anything we can do to address this? We had a new user deploy this week and there are no flow runs for that

![image](https://github.com/microsoft/coe-starter-kit/assets/5492973/b18a43ef-2faa-4007-9017-740d90f51240)

**Comment by RajeevPentyala** [comment]
@groypk The 'ShareConnectionWithServicePrincipal' flow runs every time you save the configuration settings and if the following criteria are met.

- 'Share' checkbox is checked.
- Connections has to be resolved. You should see 'Connected' as highlighted below.

Can you confirm if the above-mentioned criteria were met in your scenario?

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/4deb2b6d-3698-468a-a731-df0bb092ec67)

**Comment by RajeevPentyala** [comment]
@groypk Closing this issue as there was no update. Please reach out if you need further assistance.
