### ISSUE TITLE
[CoE Starter Kit - BUG] Problem with Data Policy Error

### ISSUE THREAD

**Issue by RobCEviden** [microsoft/coe-starter-kit#7370]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

On installing the COE Core components I am seeing this error in pretty much everything I try to open and view. Installed version 4.17 this morning into a fresh new environment, created 30 minutes before the install was attempted. We have not setup any Data policies in this tenant, however it seems that the shared_webcontents connector has been replaced with the HTTP with Entra ID one, and if I had to guess, there is a hidden policy somewhere that is preventing the use of the old Azure AD one.

Error copied:
Error Code: AppForbidden
Session Id: e2ca00ff-713e-4f19-8aff-5b7fce288d10
Activity Id: ff4b44be-ac48-456c-af32-2daff8c391ed
Timestamp: Wed Jan 03 2024 10:40:32 GMT+0000 (Greenwich Mean Time)
{"error":{"code":"ApiPolicyViolated","message":"It looks like this app isn't compliant with the latest data loss prevention policies.","details":[{"code":"MultipleViolations","message":"Policy name: COE Policy\r\nBusiness connector: shared_office365users cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_webcontents.\r\nBusiness connector: shared_office365groups cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_webcontents.\r\nBusiness<truncated>
UciError: {"error":{"code":"ApiPolicyViolated","message":"It looks like this app isn't compliant with the latest data loss prevention policies.","details":[{"code":"MultipleViolations","message":"Policy name: COE Policy\r\nBusiness connector: shared_office365users cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_webcontents.\r\nBusiness connector: shared_office365groups cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_webcontents.\r\nBusiness<truncated> at s (https://content.powerapps.com/resource/uci-infra/scripts/app.29ee1811eef7cf7d229bbd1b396facb6.js:33:940216) at https://content.powerapps.com/resource/uci-infra/scripts/custompage.bcb2b52aca4e7f5714ce3b590818f454.js:4:221315

![Screenshot 2024-01-03 103950](https://github.com/microsoft/coe-starter-kit/assets/155537356/aad958ef-d0db-479c-a182-a19c0d746bd7)
![Screenshot 2024-01-03 104006](https://github.com/microsoft/coe-starter-kit/assets/155537356/3fe5fc25-932d-45ee-90d0-9acfcf77026f)

### Expected Behavior

I have tried to open the setup wizard, but cannot get to the main screen. I would expect it to get there

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

None

AB#1935

**Comment by Jenefer-Monroe** [comment]
Hello. 

The HTTP with Azure AD connector was just renamed so it has not caused technical issues for us (though it has caused plenty of confusion!) 
Do please be sure that you selected the preauthorized one.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a792491f-f0fe-4cfe-9544-17168e1102a2)

If that does not resolve then please log in as a Power Platform Admin to the Admin Center: https://admin.powerplatform.microsoft.com/dlp

**Comment by RobCEviden** [comment]
Hi Jenefer, we tried adding a policy and we did add that one, I ended up deleting the environments and starting again. Not sure why but it ran through this time.

**Comment by Jenefer-Monroe** [comment]
wonderful news! I'll go ahead and close this out then, please do return with new issues if you have them!
