### ISSUE TITLE
[CoE Starter Kit - QUESTION] Moving CoE Admin account to Exchange Online

### ISSUE THREAD

**Issue by G1982C** [microsoft/coe-starter-kit#7374]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

A very quick question if I may, we would like to migrate the service account that is used for the CoE Admin to Exchange Online, it is currently on-prem. Do you know if this will cause any issues? I have had a look at the environment variables and it uses the email address from what I can see, so this would not change. I just wanted to double check before we proceed. I wasn't sure if it would break any of the Outlook Connections used in the flows?

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

December 2023

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1937

**Comment by Jenefer-Monroe** [comment]
Unfortunately, I do not think that will work. We have not tested it but I believe others have tried it and it did not work. 

Here is what we understand to be the requirements for admin group. 

- must be an email-enabled security group
- admin or service account setting up the [inventory components](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components) needs to be an owner of the group.
- cannot be a group created in Exchange on-prem and synchronized to O365

**Comment by G1982C** [comment]
Thanks Jenefer. It is already a service account that has on-prem exchange. We are wanting to migrate the account to use Exchange Online. It currently works with exchange on-prem, the concern was whether it would continue to work if we migrate the mailbox to Exchange Online?

**Comment by Jenefer-Monroe** [comment]
Oh I see. I presume that would work then. I think thats what other people do. 
Thanks for letting me know about your old state! We don't have any on-prem anything around here for testing so thats good to here from you.

**Comment by G1982C** [comment]
Thanks Jenefer, appreciate the information.

**Comment by Jenefer-Monroe** [comment]
You bet. I'll go ahead and close out then but please do return with new issues or questions if they arise.
