### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Starter kit updating Default guid - It is removing Default- from guid which is failing connector action

### ISSUE THREAD

**Issue by umeshmurumkar** [microsoft/coe-starter-kit#7377]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have upgraded 4.17 version in November and we observed too many flow failures from CoE Kit. These are flows are pointing to Default environment. We found that record guid string in environment table is changed from Default-guid to just guid.

Due to this  all admin connectors referring environment id are failing. Kindly suggest if this is known issue or will there be any impact if we restore the guid string again to "Default-guid" Note that we have not changed default environment properties.

### Expected Behavior

Guid should be listed as Default-xxxxxxxxxxxxxxxx which  has changed to "xxxxxxxxxxxxxxxx"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin -Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Post upgrade, we can see the CoE Table has changed record value of default environment where most of apps & flows recite.

AB#1940

**Comment by Jenefer-Monroe** [comment]
This is not known. Can you please share the following? Screenshots would be beneficial and note that you need to be logged in to GitHub to share them. Just obfuscate the actual GUIDs. This will help me understand the issue. 

1. Where specifically are you seeing just the GUID that you expect Default-GUID?
2. What connectors / flows specifically are failing due to this?

**Comment by umeshmurumkar** [comment]
Thanks for responding Jenefer. Please find screenshot for record ID. It should have prefix "Default-" but got removed after starter kit upgrade

<img width="708" alt="Default Environment GUID record from Environmnet table" src="https://github.com/microsoft/coe-starter-kit/assets/26483756/cdc072dd-2f3f-4927-8425-3cbcbc08c251">


Flows not working due to environment ID String change

Admin | Sync Template v4 (Apps), Admin | Sync Template v4 (Flows), Admin | Sync Template v4 (Apps) , Admin | Sync Template v3 (Flow action details) , Admin | Sync Template v3 (Model Driven Apps)

Connectors not working due to name change for default environment guid (Example)

Get_App_as_Admin
Get_Flow_as_Admin

Error
Error details - The request failed with client error: 'The environment '<null>' could not be found in the tenant 'xxxxxxxx-xxxxxxxx-xx-xxx-xxxxxxxx'.'. The correlation Id is '131d187c-4ab4-4d96-a527-1b1bcd5e186b'.

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not sure from that screenshot what I'm looking at. 
The GUID of the record should be the GUID itself and not the name. Here is what we store. This is expected.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c86a1c02-f35c-415a-a111-c5b0510f69ca)

That failure sounds like a caught and expected failure for new environments. 
Can you please share a screenshot of the actual failure you are seeing?

**Comment by Rajatchopra3** [comment]
Hi Jenefer, In powerappsapp table in coe core, in some records we are getting default appended in the app environment id column and in some default is not there.
<img width="451" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/31f40412-ad7c-4387-94e2-6245ca23e040">
<img width="474" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/e07a397a-56e6-4cae-bbb7-3ca904ecce18">

**Comment by Rajatchopra3** [comment]
<img width="515" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/9ce43351-dd0a-433b-a048-56042c00b4d6">

In the above image some records have default and some do not

**Comment by Jenefer-Monroe** [comment]
Thank you! we are finally on the same page. I had been thinking you meant the rows GUID. 

Can you please confirm, all the ones showing **_Default-_** are Model Driven Apps yes? 

This has been this way through all of 2023 (I just validated). So I dont think this should be breaking any of our flows or processes. However its something I can clean up in a new release. I'll just need to think through to make sure we dont break others since its been that way so long before doing so.

**Comment by Rajatchopra3** [comment]
<img width="568" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/4d05fb6e-2a84-4a8e-9fce-6336725e5ffd">
no they are canvas, and the other one is also canvas

**Comment by Jenefer-Monroe** [comment]
Can you please take one of the canvas ones with Default- in that field, and **_Inventory Me_** flag to true? 
Then wait until the next days inventory run to see if its resolved.

**Comment by Jenefer-Monroe** [comment]
And in the meantime can you please also tell me which flow is failing as a result of this?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
