### ISSUE TITLE
[CoE Starter Kit - BUG] BYOD_CoEDashboard_October2023 - Power Automate overview not showing all

### ISSUE THREAD

**Issue by arpalmares** [microsoft/coe-starter-kit#7379]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Last year (2023) when the BYOD CoE Dashboard was setup, the overview for Power Automate was showing accurately all the flows.
It was showing 200K+ flows across the tenant.

This year (2024), the overview was **only showing 3K+ flows** with no filters applied. The refresh of the connected dataflow is successfully refreshing but data seems to be incomplete. No data is showing up for some environments, especially default environment which has the most flows in our tenant.

![image](https://github.com/microsoft/coe-starter-kit/assets/546819/6d9829d8-a90e-45d8-8b95-6293bf3eeeaf)

Upon checking the Power Platform Admin Center analytics, inventory of our power automate flows are still at **200k**.

![image](https://github.com/microsoft/coe-starter-kit/assets/546819/685a8914-c07c-49c9-8ca6-9882e16f4b92)

The BYOD CoE Dashboard is the one inaccurately displaying the count in the Power BI report.

### Expected Behavior

Count of Power Automate flows in the BYOD CoE Dashboard should be the same as what is reflected in the Power Platform Admin Center analytics.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

BYOD_CoEDashboard_October2023

### What app or flow are you having the issue with?

N/A - Report is connected thru Data Lake

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Power Platform Admin Center exports data to Azure Data Lake
2. Power BI Data Flow connects to Azure Data Lake
3. CoE Dashboard connects to Power BI Data Flow

*** Power BI Data Flow is taken from the CoEStarterKit (PowerPlatformAdminAnalytics-DF.json)

### Anything else?

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi

AB#1942

**Comment by Jenefer-Monroe** [comment]
Please go to the Datalake and find the flow file for an environment where you expect to see flows but do not. 
You can do this by going to the Storage Browser and searching for the GUID of the envt
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/160575cf-225f-4d31-b7db-88fc079f3ed7)

### Question 1: What is the last modified date shown for the file? 

Next please click on the file and download it to view
### Question: 2 Is the file formatted like image 1 with a single line per flow or like image 2 with a jumbled look?

**Image 1 : Well formatted**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dbf210ec-8544-4e82-a03e-e6196f0685fc)

**Image 2 : Not well formatted**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/589de3df-db6c-4101-ba16-05fd530c56c0)

**Comment by arpalmares** [comment]
Question 1: Recent Modified Date (1/4/2024 7:10:41 PM) from a Flow Id which is in the Default Environment.

![image](https://github.com/microsoft/coe-starter-kit/assets/546819/24428aa0-171b-49d0-a390-375a7ec85edc)

Question 2: Well formatted

![image](https://github.com/microsoft/coe-starter-kit/assets/546819/15f444ec-d024-4543-a723-720693bf4d7d)

Tried creating a separate Power BI Report directly connecting to the Data Lake storage...
The count looks correct. Issue is coming from the Data Flow of the **BYOD CoE Dashboard** in the CoE Toolkit.

![image](https://github.com/microsoft/coe-starter-kit/assets/546819/12d51492-e56b-474e-ae81-e9daf37dd1b4)

**Comment by Jenefer-Monroe** [comment]
ok good. Your data is solid. I think this was an issue with the dataflow and we shipped a fix to this in the Jan release. 
Please upgrade, you'll see a new Dataflow for the PBI's this month as shown here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3b8fd650-c88a-4010-9ef5-c24685ac5e89)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
