### ISSUE TITLE
Add appid and flowid as columns on the entities

### ISSUE THREAD

**Issue by samadane** [microsoft/coe-starter-kit#738]
The id of the app and flow records created into COE look to be the same guid as the canvas app / flow id that exists in the tenant.  This is not searchable though.  Many times we get a link and are asked "who owns this app" I need access.  We have to hit the url, hope to have access to it and then search in COE by app name.  If the guid was searchable in the COE then it could be put in views and searched on.

Example:
Can you please let me know the owner of the below power app?
https://apps.powerapps.com/play/<APPIDGUID>?tenantid=<Tenantid>
I would like to ask them for access. 

In order to find the name / owner of this app in the COE toolkit you have to first hit an app record and then insert the appidguid in the url.  It would be nice to be able to global search for this.  Same with flows. 

**Describe the solution you'd like**
Add an appid and a flowid column so it is searchable within COE.  Right now you have to go to a record and then copy in the guid to get directly to that record.

**Comment by manuelap-msft** [comment]
Hello,

thanks for this feedback! That's correct, we use the Resource ID (so app, flow, environment ID) as a Unique Identifier on the table. Would you expect to do this search in the Power Platform Admin View (model driven app)? If so, I'm wondering if we can enable relevance search (https://docs.microsoft.com/en-us/powerapps/user/relevance-search) to facilitate this in an easy way.

Thank you
Manuela

**Comment by samadane** [comment]
searching by guid in relevance search brings up nothing unless it is also a column in the table.

**Comment by mikefactorial** [comment]
@samadane This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by samadane** [comment]
> I did something for this via #870
> It will require a full inventory to get the benefit. And I only did it for Canvas Apps, Cloud Flows, and Model Driven Apps.

How do you do a full refresh? Is there a variable or setting to say "udpate everything"
