### ISSUE TITLE
Can't extract Jan 24 release; Path too long

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#7380]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/009d14a4-6ad7-446c-bfc2-840372eca1af)

AB#1943

**Comment by SPMush** [comment]
If it helps, I extracted using WinRAR and didn't experience this issue.

**Comment by manuelap-msft** [comment]
Please raise issues using the correct template from here so they get labelled and assigned to the correct project:
![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/f18fafce-3adf-4e32-9540-cdf3e217bd72)

**Comment by RickKush** [comment]
Should I call this a question?

From: Manuela Pichler ***@***.***>
Sent: Thursday, January 4, 2024 10:38 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Can't extract Jan 24 release; Path too long (Issue #7380)


Please raise issues using the correct template from here so they get labelled and assigned to the correct project:
image.png (view on web)<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/assets/55705669/f18fafce-3adf-4e32-9540-cdf3e217bd72__;!!May37g!OT6tao_5bNxvwQgBuR_c2A4gB5wDF-zh_TDQL9JpDG6w-P4mNmxwZZ0JmoKJzhsoyiaOSCooKYNFV0kT-uowNgNcfg$>

-

**Comment by manuelap-msft** [comment]
Yes, this would be a question. I've labelled it correctly and assigned it to correct project now so it will be picked up by our team who does issue triage - so there's no need to re-raise the issue, just for future reference!

**Comment by RickKush** [comment]
😊

From: Manuela Pichler ***@***.***>
Sent: Thursday, January 4, 2024 10:43 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Can't extract Jan 24 release; Path too long (Issue #7380)


Yes, this would be a question. I've labelled it correctly and assigned it to correct project now so it will be picked up by our team who does issue triage - so there's no need to re-raise the issue, just for future reference!

**Comment by Jenefer-Monroe** [comment]
I dont repro this. Can you please share how you attempted the extraction? Here is what worked for me
A right click on the zip file > Extract all
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/86f47aa2-121c-4a46-af35-8a91d51593f1)

**Comment by RickKush** [comment]
I also did "extract all..." as in my screenshot

**Comment by RickKush** [comment]
Yes, I did that first...

From: Jenefer Monroe ***@***.***>
Sent: Thursday, January 4, 2024 11:40 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Can't extract Jan 24 release; Path too long (Issue #7380)


Are you trying it with the zip file as a whole from https://aka.ms/coestarterkitdownload<https://urldefense.com/v3/__https:/aka.ms/coestarterkitdownload__;!!May37g!KGDv7JyLK16o_Le8N2TMZvSJcwqdCpsHck4oOg9zfYen-NtgH4bROo31iIZ7HQSwBuA3EZpS8nYCNrqkpEcIpk8GqQ$>?
It looks like you might be trying to unzip something else.

-

**Comment by Jenefer-Monroe** [comment]
Sorry I dont follow. That is the only thing you need to unzip.

**Comment by RickKush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/d6487ecd-c923-4789-b8b9-523db2a12249)

**Comment by manuelap-msft** [comment]
It looks like this is an issue with your system, rather than our zip file. I found some blog posts on how to solve this but this was just from a quick google - you may need to do some more research into your system settings
https://helpdeskgeek.com/windows-11/how-to-fix-the-path-too-long-error-on-windows/

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close out since there is no further action for the starter kit team.
