### ISSUE TITLE
 Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding.

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#7381]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The history shows success: 
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/59253d08-1b44-4b79-a6f1-cb0cdcc11f16)

But in Solutions, there is this big error msg:
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/c1678da6-ec84-42ac-ac87-3854ad85d3b1)

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 16 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_7af84, Id: b8da3cb1-8eb7-ed11-83fe-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_df614, Id: f4a6ae62-8fb7-ed11-83fe-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_c2c67, Id: 4ad4d2c5-4f01-ee11-8f6e-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_d8354, Id: 52f6944f-2c0a-ee11-8f6e-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_c2526, Id: 4b84915b-2c0a-ee11-8f6e-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_03262, Id: 0fccf84a-a8c9-ed11-b597-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_30d12, Id: 7c248de2-89b7-ed11-83fe-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_6f84c, Id: 8fbb7234-08b9-ed11-83fe-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_064b6, Id: 84849e3e-15bd-ed11-83ff-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_28a55, Id: b3a4efa1-f4bd-ed11-8400-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_7203c, Id: 3df04f95-4301-ee11-8f6e-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_d5c28, Id: d482f7bf-4f01-ee11-8f6e-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_a5360, Id: ebf8b819-a8c9-ed11-b596-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: 09745384-d36e-4138-99a3-6a621ea23583, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5ff18d20b7ec3dbffe_a3e3b, Id: 15638f75-996b-4f78-a65f-fb1a9b5f5789, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

 Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

AB#1945

**Comment by RickKush** [comment]
When I try to run any of the 3 main admin apps, I get this error: 
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/021c0742-9896-48d6-9f3e-bb652eda1b10)

**Comment by RickKush** [comment]
After importing 4.22, it failed to uninstall/upgrate 4.8:
Solution dependencies exist, cannot uninstall. DependencyCount : 16 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_7af84, Id: b8da3cb1-8eb7-ed11-83fe-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_df614, Id: f4a6ae62-8fb7-ed11-83fe-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_c2c67, Id: 4ad4d2c5-4f01-ee11-8f6e-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_d8354, Id: 52f6944f-2c0a-ee11-8f6e-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_c2526, Id: 4b84915b-2c0a-ee11-8f6e-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_03262, Id: 0fccf84a-a8c9-ed11-b597-0022481fb943, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_30d12, Id: 7c248de2-89b7-ed11-83fe-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_6f84c, Id: 8fbb7234-08b9-ed11-83fe-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_064b6, Id: 84849e3e-15bd-ed11-83ff-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_28a55, Id: b3a4efa1-f4bd-ed11-8400-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_7203c, Id: 3df04f95-4301-ee11-8f6e-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_d5c28, Id: d482f7bf-4f01-ee11-8f6e-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_sharedadmin5foffice2036520management20api5fa86a7a016182459a_a5360, Id: ebf8b819-a8c9-ed11-b596-0022481fbccb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: 09745384-d36e-4138-99a3-6a621ea23583, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5ff18d20b7ec3dbffe_a3e3b, Id: 15638f75-996b-4f78-a65f-fb1a9b5f5789, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

**Comment by Jenefer-Monroe** [comment]
Hello, is this after the other issue? I presume https://github.com/microsoft/coe-starter-kit/issues/7376 is now resolved then? 

Your issue here is the Audit Logs solution. This is a known and expected failure described here: https://github.com/microsoft/coe-starter-kit/issues/6018

First step is to remove the _upgrade and then proceed as described in that issue.

**Comment by RickKush** [comment]
After I delete 4.22 upgrade, I guess I will be back on 4.8. Then do I need to reinstall 4.22?

**Comment by Jenefer-Monroe** [comment]
You will need to delete the audit logs solution before you will succeed at installing the new builds. Please follow the instructions at https://github.com/microsoft/coe-starter-kit/issues/6018 for how to do that.

Regarding my recommendation. First we will need to decide between sync flow and BYODL architecture. 
About how many apps / flows / environments do you have in your tenant?

**Comment by RickKush** [comment]
Over 5,000 each Flows & Apps and over 600 environments.

**Comment by Jenefer-Monroe** [comment]
OK i think you are fine to use the sync flow architecture then. 
The BYODL one will be better in the long run but it has a couple bugs right now (like not bringing back the owners of MDA's) so I suggest continuing to use sync flows for now. 

So to proceed, please delete the audit log solution as shown in https://github.com/microsoft/coe-starter-kit/issues/6018 

then once that is complete, upgrade to the latest build. Then you can worry about getting audit logs going again, and I recommend with the http methodology.

**Comment by RickKush** [comment]
I'm not concerned about MDA owners. Could you tell me, or is there a reference, for the other bugs? The main things that interest me are environments, flows and apps for the audit logs.

**Comment by Jenefer-Monroe** [comment]
Thats the only big bug right now. Have you tried to do BYODL in the past? Did we iterate on that here in the bug list? Its more difficult so thats the other reason to stick with Sync Flows. They are an easier path.

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

Will it be convenient to switch to BYODL later?

And is it possible to change the COE owner?

From: Jenefer Monroe ***@***.***>
Sent: Friday, January 5, 2024 10:37 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. (Issue #7381)


Thats the only big bug right now. Have you tried to do BYODL in the past? Did we iterate on that here in the bug list? Its more difficult so thats the other reason to stick with Sync Flows. They are an easier path.

-

**Comment by Jenefer-Monroe** [comment]
BYODL will only get easier and better over time. So you arent losing anything by sticking with Sync Flows for now. 

Yes changing CoE Owner is as simple as having the new owner / identity create all the connections and then perform the next upgrade.

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

The Admin | Audit Logs | Office 365 Management API Subscription flow  says "not for BYOLD" I thought I was going to do BYODL. Is this what I should be doing?

From: Jenefer Monroe ***@***.***>
Sent: Friday, January 5, 2024 3:33 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. (Issue #7381)


BYODL will only get easier and better over time. So you arent losing anything by sticking with Sync Flows for now.

Yes changing CoE Owner is as simple as having the new owner / identity create all the connections and then perform the next upgrade.

-

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

Anyhow, I got return status 300 for StartSubscription

From: Jenefer Monroe ***@***.***>
Sent: Friday, January 5, 2024 3:33 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. (Issue #7381)


BYODL will only get easier and better over time. So you arent losing anything by sticking with Sync Flows for now.

Yes changing CoE Owner is as simple as having the new owner / identity create all the connections and then perform the next upgrade.

-

**Comment by RickKush** [comment]
Booz Allen Hamilton Internal

Status 400,

    "code": "AF20024",
    "message": "The subscription is already enabled. No property change."

The first two times that I ran it, I entered "Start" as the operation, and it took the default path. The 3rd time, I entered "start" and it took the START path...
From: Kushner, Rick [USA]
Sent: Friday, January 5, 2024 4:44 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [External] Re: [microsoft/coe-starter-kit] Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. (Issue #7381)

Anyhow, I got return status 300 for StartSubscription

From: Jenefer Monroe ***@***.******@***.***>>
Sent: Friday, January 5, 2024 3:33 PM
To: microsoft/coe-starter-kit ***@***.******@***.***>>
Cc: Kushner, Rick [USA] ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [External] Re: [microsoft/coe-starter-kit] Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. (Issue #7381)


BYODL will only get easier and better over time. So you arent losing anything by sticking with Sync Flows for now.

Yes changing CoE Owner is as simple as having the new owner / identity create all the connections and then perform the next upgrade.

-

**Comment by Jenefer-Monroe** [comment]
sorry im not sure where we are at. I suggest you go with the sync flow architecture. 

Have you uninstalled the Audit Logs solution? 
Have you upgraded to a current build?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
