### ISSUE TITLE
Got the "OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E" while importing the template

### ISSUE THREAD

**Issue by MTRTonyTsang** [microsoft/coe-starter-kit#7382]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Previous can load the template but unable to repeat the import after 2 weeks ago

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Version: 2.123.742.0 64-bit (November 2023)

### What app or flow are you having the issue with?

Power BI

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open "Power BI"
2. Import "Production_CoEDashboard_October2023.pbit"
3. Error show "OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E."

AB#1946

**Comment by RahulBojji** [comment]
@MTRTonyTsang 
This is working for most people so there must be something wrong with your setup.

Can you please share the format of the URL you entered? It should have a prefix https:// and the ending / as per this [documentation](https://orgd85e6c0e.crm.dynamics.com/)

If this is not the case, can you please share screenshots of the issue you are experiencing.

**Comment by MTRTonyTsang** [comment]
Here is the URL:
https://org9205bd05.crm5.dynamics.com/




Best Regards,



Tony Tsang

Systems Analyst

[Logo_w_tagline]

www.mtr.com.hk<http://www.mtr.com.hk/>



________________________________
From: RahulBojji ***@***.***>
Sent: Friday, January 5, 2024 18:15
To: microsoft/coe-starter-kit ***@***.***>
Cc: TSANG Tony Chung Leong (曾忠亮) ***@***.***>; Mention ***@***.***>
Subject: [External Email] Re: [microsoft/coe-starter-kit] Got the "OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E" while importing the template (Issue #7382)


CAUTION: This email originated from outside of MTR. Do not click links or open attachments unless you recognize the sender and know the content is safe.



@MTRTonyTsang<https://protect2.fireeye.com/v1/url?k=31323334-501d0a38-3133b849-454441504e31-dab49beb945158eb&q=1&e=7949a58b-8ee4-44fa-8731-4c157dca0629&u=https%3A%2F%2Fgithub.com%2FMTRTonyTsang>
This is working for most people so there must be something wrong with your setup.

Can you please share the format of the URL you entered? It should have a prefix https:// and the ending / as per this documentation<https://protect2.fireeye.com/v1/url?k=31323334-501d0a38-3133b849-454441504e31-7dc58002b525d74a&q=1&e=7949a58b-8ee4-44fa-8731-4c157dca0629&u=https%3A%2F%2Forgd85e6c0e.crm.dynamics.com%2F>

If this is not the case, can you please share screenshots of the issue you are experiencing.

—
Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=31323334-501d0a38-3133b849-454441504e31-c044c76a0559ab8b&q=1&e=7949a58b-8ee4-44fa-8731-4c157dca0629&u=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F7382%23issuecomment-1878431760>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=31323334-501d0a38-3133b849-454441504e31-0838ed5ae7e1866d&q=1&e=7949a58b-8ee4-44fa-8731-4c157dca0629&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBBK3X2NEKQCKBVUN3C76TFTYM7HD3AVCNFSM6AAAAABBOBKTVWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZYGQZTCNZWGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

E-mail Disclaimer

The information contained in this e-mail (including any attachments) is confidential and is intended solely for the addressee. If you are not the intended recipient, please notify the sender immediately and delete this e-mail from your system. Any unauthorized use, disclosure, copying, printing, forwarding or dissemination of any part of this information is prohibited. MTR Corporation Limited does not accept responsibility and shall not be liable for the content of any e-mail transmitted by its staff for any reason other than bona fide business purposes. There is no warranty that this e-mail is error or virus free. You should not rely on any information that is not transmitted via secure technology.

**Comment by Jenefer-Monroe** [comment]
Hello, screenshots do not come through if you respond in email. You need to log in to GitHub to share them. 

Typically this error is just a side effect and you need to browse through all the failures until you see one that has specifics. 
For example like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/137cf9c7-6971-42df-b0c7-917c6c5d88be)

Can you please scroll through and see if you find something like this? Meaning a failure with some specific issue stated.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
