### ISSUE TITLE
Power BI App App -> Drill Through Manage App Access

### ISSUE THREAD

**Issue by guymartinello** [microsoft/coe-starter-kit#7383]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I reviewed another similar question, and believe that I have configured the report properly and have share the report with myself (full environment access)

I have not yet installed Audit Logs, and so those screens are understandably blank.
Some other screens [Archive Score, Connectors] from the same drill through work

![image](https://github.com/microsoft/coe-starter-kit/assets/61239709/3953335e-b4cf-43d6-914f-ba2d509424b1)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Production_CoEDashboard_October2023.pbit

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1947

**Comment by Titoleto** [comment]
> ### Does this question already exist in our backlog?
> * [x]  I have checked and confirm this is a new question.
> 
> ### What is your question?
> I reviewed another similar question, and believe that I have configured the report properly and have share the report with myself (full environment access)
> 
> I have not yet installed Audit Logs, and so those screens are understandably blank. Some other screens [Archive Score, Connectors] from the same drill through work
> 
> ![image](https://private-user-images.githubusercontent.com/61239709/294449249-3953335e-b4cf-43d6-914f-ba2d509424b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTA4NTMsIm5iZiI6MTcwNDQ1MDU1MywicGF0aCI6Ii82MTIzOTcwOS8yOTQ0NDkyNDktMzk1MzMzNWUtYjRjZi00M2Q2LTkxNGYtYmEyZDUwOTQyNGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEwMjkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYjIxYTE5ZjBjMzIzMDU1NDUyZGYyOGY3ZjhkYTIxYjA4Y2E5ZjE4MWZmYTk1ZjQxYTY0MDJkYTE4MTE2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wUYUHrYtC8ws99nd-BnG7SsPzDV2QdxlJWY2O0u_Te0)
> 
> ### What solution are you experiencing the issue with?
> Core
> 
> ### What solution version are you using?
> Production_CoEDashboard_October2023.pbit
> 
> ### What app or flow are you having the issue with?
> N/A
> 
> ### What method are you using to get inventory and telemetry?
> Cloud flows
> 
> AB#1947

Have a look at this [link](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard) to setup the report
