### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to customize CoE Power BI Report?

### ISSUE THREAD

**Issue by YanNing97** [microsoft/coe-starter-kit#7384]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi all,

I am relatively new to the CoE Starter Kit, and am wondering if there's any ways to customize the CoE Power BI Report? I have created a copy of the report and made some customizations such as creating new pages in the report, new calculated tables, columns, measures and even updated some of the relationships between the tables. However, I believe that the entire customized report might not work once I upgrade the CoE starter kit to the latest version provided by Microsoft and refresh the dataset.

I have tried various ways such as ALM toolkit to deploy the changes from the customized report over to the latest version of the report, but a lot of manual work still needs to be done. Therefore, I am wondering if anyone has done this before?

Thank you and any help is greatly appreciated :)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1948

**Comment by Jenefer-Monroe** [comment]
There isnt a collaboration technique for merging changes in PBI, and we ship a template file so your approach of making your changes in a copy of the file makes sense. 

Ex:
We give you : Production_CoEDashboard_January2024.pbit
You hydrate that and create: Production_CoEDashboard_January2024.pbix
You save a copy: CoE_Base.pbix
You look at it and see if you want the changes from last time, if so you make your changes to CoE_Base and then save as to your production report

Note also that if you have changes you think others would benefit from you can request them here and we can consider adding them to our template file.

**Comment by YanNing97** [comment]
Hi Jenefer Monroe,

Thank you for the response. I have another question regarding the data refresh. Once I have upgraded the CoE to the latest version (CoE_Base_January_2024.pbix), will the new data get reflected in my previous version (CoE_Base_November_2023.pbix) if I refresh the power bi dataset (CoE_Base_November_2023.pbix)?

Thank you.

**Comment by Jenefer-Monroe** [comment]
I'm not a power bi expert so there may be ways around this that I'm unaware of but to my knowledge, each report has its own model. And so if you add a new report you will have to add an auto-refresh to its model. 

What I do is save as on top of the old in my PowerBi.com and store the iterations (ex CoE_Base_October_2023.pbix, CoE_Base_November_2023.pbix) in a folder in OneDrive

Here for example is the model that feeds by Production report
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1768de75-e127-46fe-97ad-b30f6f00ba31)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
