### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Power bi Production Dashboard showing wrong count for flows in 'Connector Deep Dive' page compared to other pages (Cloud Flows, Flow Deep Dive)?

### ISSUE THREAD

**Issue by muler-git** [microsoft/coe-starter-kit#7386]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

CoE Power bi Production Dashboard showing wrong count for flows in 'Connector Deep Dive' page compared to other pages (Cloud Flows, Flow Deep Dive)?

Which is the correct count i can consider?

For power apps it is showing correct.
 
CoE upgraded to Nov 2023 version: Production_CoEDashboard_October2023

Cloud Flows Page: filtered connector tier to Premium
<img width="315" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/125889020/83122239-317a-4d3d-9dd8-8bad9d1e62b0">

Flow Deep Dive page: 
<img width="289" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/125889020/19a104dc-84c1-41db-8349-bcc072984ba0">

Connector Deep Dive page: 
<img width="297" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/125889020/798560bb-6c3d-481b-8917-012aab3a2711">

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Nov 2023

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1950

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. This is known and has been fixed with the latest release. 
Please see https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-January2024

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
