### ISSUE TITLE
[CoE Starter Kit - QUESTION] A question I don't really want to ask but must. Security.

### ISSUE THREAD

**Issue by dbraben** [microsoft/coe-starter-kit#7387]
I want to express my appreciation for the significant effort you've invested in developing the Center of Excellence (CoE) and, particularly, the CoE Starter Kit. The managed nature of the application has been immensely beneficial, although it poses challenges in comprehending its internal components, especially from a security perspective.

While I acknowledge the widespread adoption of the CoE Starter Kit across various organizations and its alignment with Microsoft standards, my role as a contract technical architect requires me to navigate a meticulous process for its deployment. This involves presenting it to a Change Advisory Board (CAB), completing paperwork that outlines the APIs in use, detailing the level of permissions granted, and providing insights into delegation structures, among other aspects. The final stage usually involves scrutiny by Security Operations (SecurityOps), where approval is sought as an exception in most cases.

I understand that many others may have undergone a similar, sometimes arduous process. In light of this, I am reaching out to inquire if there's a comprehensive security overview for the CoE Starter Kit. A concise and informative document would greatly assist in streamlining the approval process, akin to the meticulously packaged applications we encounter.

I value efficiency and aim to avoid unnecessary repetition. However, the current circumstances necessitate a detailed understanding that is not easily replicated. Therefore, a security overview document would be immensely valuable in facilitating a smoother approval process.

I appreciate your attention to this matter and look forward to any assistance or documentation that can shed light on the security aspects of the CoE Starter Kit. Especially in concern to API's, delegated permissions and all the boring stuff needed!

AB#1952

**Comment by Jenefer-Monroe** [comment]
Hello. Thank you for your interest in the kit, and for your efforts being a Power Platform whisperer :)

Unfortunately, as a starter kit, we aren't a supported product and are therefore not staffed like a supported product either. We do not have security documentation as a result and I dont think we would be able to keep one sufficiently up to date were we to invest there.

We use only product features though, like Security Roles and Key Vault integration. So its really a security assessment of the product. I would be happy to answer any specific questions though. 

Sorry I cant be of more help.
