### ISSUE TITLE
[ALM Accelerator - QUESTION] Traditional Workflow Activation

### ISSUE THREAD

**Issue by alanrroberts** [microsoft/coe-starter-kit#7388]
### What is your question?

I notice that the November release added the ability to see all of the traditional workflows in addition to cloud flows in the ALM configuration page but there is no option to indicate whether a traditional workflow should be activated or not.  Is that something that will be added?  At the moment I am seeing workflows that are in draft/inactive mode in the source environment getting activated when deployed downstream.

Thanks

Alan

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

November 2023

AB#1951

**Comment by RajeevPentyala** [comment]
@alanrroberts We introduced the ownership configuration for Classic/Traditional workflows in the November release, but the Activation/Deactivation feature was not included. Based on your issue description, there might be a problem which activating the classic flows by default. We will investigate and provide updates.

**Comment by alanrroberts** [comment]
Thanks @RajeevPentyala

**Comment by RajeevPentyala** [comment]
@alanrroberts We have provided the option to configure the enable/disable of classic workflow. This will be available in March 2024 release.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/2da681fc-90a6-4f54-9e73-4b22db2db247)
