### ISSUE TITLE
[CoE Starter Kit - BUG] No desktop flow data for specific environment

### ISSUE THREAD

**Issue by onawoni** [microsoft/coe-starter-kit#7390]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After installing the CoE component V4.7, all the environments display in the Environment tab of the CoE. However only flows in the default environment shows in the Desktop Flow tab. None of the 121 desktop flows in production environment were displayed. I confirmed that the Admin | Sync Template v3 (Desktop flows) flow is turned on and ran successfully. I open the Power Platform Admin View (model driven app) and also observe all the Desktop flows in the Production Environment are not there.

### Expected Behavior

I expect to see all the flows in the Production environment in the "Desktop Flow" tab not just the Default environment. Also the filter should contain the Production environment and not just Default environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the Power BI Desktop
Load the Production_CoEDashboard_MMMYY.pbit  dashboard
Enter the URL of the production environment instance.
Desktop Flow Tab fails to load the flows in the production environment.

AB#1954

**Comment by Jenefer-Monroe** [comment]
Hello. This is a known limitation of the v3 version of the sync flows for desktop flows. Basically the old connector we used were unable to select fields and hence would be too large to collect. 
Good news is that we now have the modern connector working for this and you can collect these!

Please download the [Jan release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-January2024) and chose to opt in to the v4 sync flows in the setup wizard as shown in https://github.com/microsoft/coe-starter-kit/issues/7322

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
