### ISSUE TITLE
[CoE Starter Kit - BUG] GraphURL Environment Variable from the values table dropping the trailing '/' resulting in SetupWizard flow failures 

### ISSUE THREAD

**Issue by hp-bc** [microsoft/coe-starter-kit#7391]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When retrieving the GraphURL Environment Variable from the values table, the trailing '/' in the URL is lost resulting in failures in at least the lower three flows due to the concatenation in the value returned from "ListCurrents-GraphURL" and the end point in "Send an HTTP request" . 

SetupWizard>GetTenantID
SetupWizard>CreateGroup
SetupWizard>GetUserDetails

### Expected Behavior

I know this is not Dataverse support so I don't think you could do anything about the correct value not being returned from Dataverse, but I think ensuring there is a trailing '/' before the HTTP call would fix this issue. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

SetupWizard>GetUserDetails

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Define the GraphURL in the initial import step - Listed as step 4 here (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-the-core-components-solution)
2. Proceed through the setup process.

AB#1955

**Comment by Jenefer-Monroe** [comment]
Are you saying it comes back without the ending slash here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e43a22a1-546e-4a7d-a6bd-3624ed074347)

Can you validate its correct when you look in the command center? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dd14bcdd-3870-411f-b49c-7352b5a304c5)

**Comment by hp-bc** [comment]
That is correct!

![COE-URLEnvVar](https://github.com/microsoft/coe-starter-kit/assets/155746549/b3395db3-39bb-4e38-9ae8-3a68df5a3ac1)

![COE-URLFlow](https://github.com/microsoft/coe-starter-kit/assets/155746549/90b6bb8d-0fce-402e-a77a-34856e93b826)

![ReturnValue](https://github.com/microsoft/coe-starter-kit/assets/155746549/bd8c0b01-d3e2-4572-a295-e1d65f584610)

**Comment by Jenefer-Monroe** [comment]
Can you please check a few things for me? 

### Check for default value
Go to the Default Solution in your CoE Environment > Environment Variables > Find this Env Var
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d399a11b-6ee5-45fa-9979-f9b0e6aec488)

Click on it to open the side pane. 
Do you have a Default and a Current value? Is one of them without the slash?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/35fd173c-43d0-4b6b-9c65-825d0503f6f2)

### Check for multiple values
In the past the product used to support multiple current values. Can you please go see if you have multiple for this? 
In the default solution > Tables > open the **_Environment variable value_** table
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a09bff08-1cfb-488c-b43c-d691dd581538)

Click Edit to get full screen and then update the columns to be as shown
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d3379069-49d6-4268-9c1a-13111e6ae77c)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ab5d27df-f13c-4571-b25d-c62a7caf2b4e)

Filter to schema = admin_GraphURLEnvironmentVariable
Are there multiple?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/42432e90-09c6-4480-9720-abe8dd3763e7)
