### ISSUE TITLE
[CoE Starter Kit - BUG] Data not easy to see in Power Platform Admin View app

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#7392]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The data in the 'Power Platform Admin View' app under the tab 'Governance' is truncated for 'Access Management' & 'Dependencies'.
Can these fields be displayed in the same way as the 'Business Justification' field?

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/cb0050fd-950b-45ca-8332-f1570aff8a95)

### Expected Behavior

To be able to see all the data for the fields  'Access Management' & 'Dependencies'.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2.2

### What app or flow are you having the issue with?

'Power Platform Admin View' app 

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the 'Power Platform Admin View' app
Select an app to view that has a lot of data.
Click on the Governance tab

AB#1957

**Comment by Jenefer-Monroe** [comment]
Unfortunately this isnt actually something we can do easily. 
The fields were made as a single line of text not multi line for some reason. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9cb45a9a-9bc5-438d-be2e-e60af990b6e8)

And the platform does not allow you to change from one to the other.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
