### ISSUE TITLE
[CoE Starter Kit - BUG] Model driven apps Dataflow missing

### ISSUE THREAD

**Issue by nrd2015** [microsoft/coe-starter-kit#7393]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Dear Team,
I have updated the CoE toolkit to November release and have also ran the update wizard successfully. I have an issue with one of the dataflows. The “CoE BYODL Model Driven Apps” is available in the solution but I cannot find it when I navigate to Dataflows screen.

![image](https://github.com/microsoft/coe-starter-kit/assets/12375029/643a95a6-e88b-49d4-9bbd-597c6af2e2dc)
![image](https://github.com/microsoft/coe-starter-kit/assets/12375029/4fa2b1af-c59f-42ad-adb7-e64c2d2aacb6)

This is also causing the “CoE BYODL - When Environment dataflow refresh is complete” flow to fail

![image](https://github.com/microsoft/coe-starter-kit/assets/12375029/fd15f8f1-395f-44ab-ba31-6419cedc4378)

I have also confirmed that I am the owner of the dataflow in the solution.
Can you please advise what am I missing ?

### Expected Behavior

The “CoE BYODL Model Driven Apps” should be  available in Dataflows screen. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CoE BYODL - When Environment dataflow refresh is complete

### What method are you using to get inventory and telemetry?

Data Export

AB#1958

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not sure, if the dataflow isnt accessible to the platform even though its there, then this seems like a bug you would need to reach out to product support for. I've not seen this happen other than it being assigned to someone else. And that did not make it inaccessible to the flows. 

Here's a few ideas to try before contacting support:
- try upgrading again with a repair to Nov
- try upgrading to Jan which was just released. 
- go to the dataflow table in the product, you should see it twice in there (like all the dataflows). Do you see them both? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5e458dd2-a6d5-4c71-8075-1a8c7fa10ced)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by nrd2015** [comment]
Hi @Jenefer-Monroe , Thank you for your response. This worked !!!
