### ISSUE TITLE
[CoE Starter Kit - Int'l Sufficiency Issue] Error on Admin | Sync Template v3 (PVA)

### ISSUE THREAD

**Issue by orauch-a** [microsoft/coe-starter-kit#740]
### Describe the issue

![image](https://user-images.githubusercontent.com/34766578/124733142-32d39880-df14-11eb-8b85-7aac3a8faab7.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/34766578/124733380-6d3d3580-df14-11eb-82c7-6acaf5845b9a.png)

Error because your expression is only avaible for English tenant :
`if(equals(substring(body('Parse_Bot_JSON')?['_componentstate_label'], 0, 7), 'Deleted'), true, false)`

For example on French tenant _componentstate_label is "Publié" on cannot be "Deleted"
![image](https://user-images.githubusercontent.com/34766578/124733941-f5233f80-df14-11eb-96f4-219e780bd190.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.6

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA)

**Comment by orauch-a** [comment]
For information, i replaced
`if(equals(substring(body('Parse_Bot_JSON')?['_componentstate_label'], 0, 7), 'Deleted'), true, false)`
with
`contains(createArray(2, 3), body('Parse_Bot_JSON')?['componentstate'])`
And it seems to be ok

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid we do not support other languages. 
Please see [supported languages](https://docs.microsoft.com/power-platform/guidance/coe/limitations#supported-languages) in our limitations documentation. You will need to add the English language pack

**Comment by orauch-a** [comment]
And why test on label and not the id ?

**Comment by JeneferM-MSFT** [comment]
Hello. If this still doesnt work after you install the English language pack please let us know and we can explore changes.
