### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can we remove requirement for storage account?

### ISSUE THREAD

**Issue by mvigneshwaran1010** [microsoft/coe-starter-kit#7401]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Regarding the COE Starter Kit requirement for a storage account, the necessity is tied to the design of the Power BI dashboard report. You can explore the specifics at this link: COE Setup for Power BI. It delves into whether it's feasible to design the report without a storage account.

 

In case a storage account is deemed necessary, we need to determine the endpoint requirements for Cenovus. Specifically, we should identify whether the endpoint will be private or public.

 

Additionally, for the storage account, an estimation of the required storage capacity would be beneficial. This information will help in planning adequate storage resources.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1968

**Comment by Jenefer-Monroe** [comment]
Hello. The storage account is needed only for the BYODL implementation of the kit. 
Please see [What data source should I use for my Power Platform inventory?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory)

The requirements for the end point are derived by the product feature. Please see [Set up Microsoft Power Platform self-service analytics to export Power Platform inventory and usage data (preview)](https://learn.microsoft.com/power-platform/admin/self-service-analytics)

**Comment by Jenefer-Monroe** [comment]
Hello, please note the CoE Starter Kit is an unsupported set of templates: https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support 

We do best effort to assist our GitHub customers but we are not funded to meet with them outside of the context of communicating here. 

Thank you for your patience
