### ISSUE TITLE
[CoE Starter Kit - BUG] COE Admin Env Request (preview)

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#7403]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,

I was testing the new apps Env Request and when i want to add a data policy to the env i have this error error loading control.
My tenant is localized in canada

<img width="432" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/57f1faa1-2437-4a43-8080-3758cc98bd81">

I tried with the depreceated app, no issue .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Open the new submitted env
2. click on view policies

AB#1970

**Comment by Jenefer-Monroe** [comment]
Sorry I'm triaging the issues and am not sure where in the app you are at. Can you please show a broader image and some steps for how you got to this stage?
thank you

**Comment by tocri** [comment]
Sorry for the delay

<img width="957" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/8f23ad9f-4a95-4a65-859a-78d24dfd9358">

**Comment by tocri** [comment]
did it helps ?

**Comment by Jenefer-Monroe** [comment]
It does yes, thank you. 
This typically happens when the control cant render something in the grid, from looking at whats in this grid I'm not sure what could be the cause. maybe this character? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1939dfad-7fbb-4a6e-9878-92c354809c61)

Can you please go to the DLP Policy table in Core, Click edit to see all records and ensure you have the Is Shared field showing. 
How many records are there? Do you have any flagged as True for the Is Shared column? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/38db732b-e005-416a-95c0-f7b9bc6af24e)

**Comment by tocri** [comment]
Following your post, I removed the accented characters I had on my shared policies. Even so, the error is still present.

<img width="355" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/5564e68d-d30e-430d-ba40-d2642333a4bc">

I can't access the Data policies screen accessible by clicking on Configure Shared policies because I get the same error 

<img width="736" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/14351526-6b80-442d-a69a-2a84cdae2142">

I disabled policy sharing to test but it doesn't change anything, the message is still in error.

What's strange is that I don't have this problem with the old "Admin - Env request" app

Je ne sais pas si cela est utile dans ce contexte, mais les policies s'affichent bien dans l'application DLP impact analysis

**Comment by Jenefer-Monroe** [comment]
Yes the old app used a gallery which responds to issues rendering items differently that this Details List object from the Creator Kit.

How many records are in the DLP Policy table in Core? And do you have any flagged as True for the Is Shared column?

**Comment by tocri** [comment]
oh sorry i forgot to paste the screenshot.

<img width="529" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/79251775-bc04-44d1-9a27-f863533ebc5b">

Only 2 policies that i shared but the behavior is the same if i untick shared.

**Comment by Jenefer-Monroe** [comment]
if you unshare both and then reload the app, it still repros?

**Comment by tocri** [comment]
Yes, when disabling **ishared** on the **DLP policy table**, I still get the same error message **Error loading control** when I click on **Configure Shared policies** or in **View policies**.

Wouldn't this be related to a component version that wouldn't be up to date on my end? I remember last year I had a problem like this on the Power Platform Admin View app and the problem was with the version of the components for Canada that were not up to date?

**Comment by Jenefer-Monroe** [comment]
It could be. What version of creator kit do you have installed?

**Comment by tocri** [comment]
1.0.20230421.1

**Comment by tocri** [comment]
I don't understand, there are no special characters on the name of my DLPs.

In the meantime, I continue to use the old version.
I tested the app on 2 different environments for testing purposes and the error message is the same in both cases. 


![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/95b7949e-7a0b-4193-bd65-2ed6a0f2840e)

**Comment by Jenefer-Monroe** [comment]
ok thank you, I will set for the feature area owner to investigate.

**Comment by tocri** [comment]
@Jenefer-Monroe  Hi jenefer, do you remember my issue. It's still present even after the april update. So i have investigated a little more deep in the code.

Maybe i ve found the origin of the issue.

is this screenshot can help you ?

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/fca77bb6-2c92-4eed-b38c-64e29f738095)

the name of this DLP is 'Connecteurs Msft free et de base'

What does it means ?

**Comment by tocri** [comment]
@Jenefer-Monroe @gulzarudheen
Hi, i notify you because i found the bug but i don't know how to resolve it.

By default, i have the issue "Error loading control" when i click on Configure Default Share policy. I have one DLP on the default environnement but it seems there is some trouble to resolve a environnement that has a guid like that 

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/ac7f6166-709c-4947-a6c6-1c2823fa3927)

If i remove this environnement for my DLP the issue disappear. Any idea ?
