### ISSUE TITLE
[CoE Starter Kit - BUG] Cleanup Old Objects App typo

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#7404]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, this is a super small typo that was brought to attention. In the shown image should it be 'your' instead of 'you? Thank you!

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/1c8f36cd-5601-4eba-94d5-deff754057f9)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Cleanup Old Objects App

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1971

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting, we are planning a complete rewrite of this feature area in the next several months which will remove these (admittedly :)) ugly apps. 
As a result we will not be making changes like that to them, hope you understand.

**Comment by santiareh** [comment]
Makes total sense, thanks for sharing and looking forward to seeing it!

**Comment by Jenefer-Monroe** [comment]
ill go ahead and close since theres no near term action for starter kit team
