### ISSUE TITLE
Unable to play model driven apps in the COE

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#7406]
I can only use these apps in "edit" mode. I am logged in as the owner of the app who is also a Power Platform Admin. When I try to play I get this error message:

This action is not supported.

Error Code: 2147746581
Session Id: 61528744-f9df-48f6-b842-6719ae275ac1
Timestamp: Mon Jan 08 2024 12:14:09 GMT-0500 (Eastern Standard Time)
RetrieveUserContext: SecLib::CheckPrivilege failed. User: 80067d27-f650-ed11-bba1-0022481fb943, PrivilegeName: prvReadEntity, PrivilegeId: a3311f47-2134-44ee-a258-6774018d4bc3, Required Depth: Basic, BusinessUnitId: 3aa050b4-554c-ed11-bba2-000d3a1791ba, MetadataCache Privileges Count: 5767, User Privileges Count: 26
UciError: SecLib::CheckPrivilege failed. User: 80067d27-f650-ed11-bba1-0022481fb943, PrivilegeName: prvReadEntity, PrivilegeId: a3311f47-2134-44ee-a258-6774018d4bc3, Required Depth: Basic, BusinessUnitId: 3aa050b4-554c-ed11-bba2-000d3a1791ba, MetadataCache Privileges Count: 5767, User Privileges Count: 26 at s (https://content.powerapps.com/resource/uci-infra/scripts/app.86f18c81fe5e5b157dd865f33752650d.js:33:932262) at new h (https://content.powerapps.com/resource/uci-infra/scripts/app.86f18c81fe5e5b157dd865f33752650d.js:28:151971) at h.fromLegacyErrorStatus (https://content.powerapps.com/resource/uci-infra/scripts/app.86f18c81fe5e5b157dd865f33752650d.js:28:153998) at _ (https://content.powerapps.com/resource/uci-infra/scripts/app.86f18c81fe5e5b157dd865f33752650d.js:28:156371) at https://content.powerapps.com/resource/uci-infra/scripts/app.86f18c81fe5e5b157dd865f33752650d.js:28:716350

AB#1981

**Comment by RahulBojji** [comment]
@RickKush
Can you please share the apps which you aren't able to play. The error message says you don't have prvRead on one of the components. 
Note that the required roles and licenses must be available to this user continuously.

**Comment by Jenefer-Monroe** [comment]
Hello. 

It looks like the user you are attempting to log in to the app with does not have the required permissions to the environment. 

**_Question:_** Is this a different user identity than the one used to install the kit? 

If its the same user identity that installed the kit, note that this user needs to have the Power Platform Admin Role permanently and directly assigned. This will in turn give them sys admin access to the environment and so you would not see that error. 
For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

And you can check if you are assigned the role correctly in the [Azure Portal](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/67258ff2-7ef5-4207-945d-4f6f2337cfd0)


If its another user, that's totally fine! You can share these apps with other users. However these users will need to be in the correct SR assigned. It sounds like we are in the first case though.

**Comment by RickKush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/780f78ec-cbf9-41e4-82f7-0fedefa5eeb7)

The first originally installed it and also all of the upgrades until 4.22 which was installed by the second. The problem started before the 4.22 upgrade and the problem is the same for both of these users.

**Comment by RahulBojji** [comment]
We would like to understand what exactly the error is you are facing. Can you please list out the steps you have followed here.
Also, can you please share the screenshots of the error you are experiencing while opening the app. Can you also please share the app which you are trying to access.

**Comment by RickKush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/021cbaaf-76ae-4e96-9421-1bb9216f2f32)

**Comment by RahulBojji** [comment]
@RickKush 
Can you please confirm below?
1. Check if the user's have vaild licenses as per this [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

2. Can you check whether the user id given in the error is valid user or not. It should be either of the two users' you are trying to access.

3. Can you please go to Power Platform Center -> Environments -> Open the environment you are facing this issue and check if Sys Admin role is assigned to above both the users who are Power Platform Administrator. Whenever you add Power Platform Administrator role on Azure portal, the user will get System Administrator on all the environments in that tenant.

<img width="580" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/3da712b7-8746-4558-b5cd-44f9651a5686">

4. Got to make.powerapps.com - > click on ellipsis beside it -> click share -> Share Can you check the users with whom you are trying to access exists here or not. 
<img width="919" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/d3401c61-22c8-47c8-841c-f50ad7dfad92">

**Comment by RickKush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/170359ff-a1d3-434f-89e2-a2cfbfa160a3)

**Comment by RickKush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/01e8cbb8-ea20-4974-8c6f-b28de6bda0fe)
If this should be my guid, it is wrong. And I try two different users, but this guid doesn't change.

**Comment by RickKush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/b5598941-04d9-44f1-8fda-da4108d5e8f6)

**Comment by RickKush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/9b81818c-677a-4d89-a4ab-cbcbe781799f)

**Comment by RickKush** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/09173dd1-546c-4621-b138-675cf4822b1a)

**Comment by RahulBojji** [comment]
@RickKush 
Apologies for the delay, i was away for the weekend. Looks like the product is logging you with the wrong user. Because the below GUID is not your user GUID. The User id will be different in Dynamics.
![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/f264c31c-d32c-43f2-9ad5-db6ae2c89538)

Can you please try clearing the cache and then sign in again. Also, if you haven't done this setup, please do create profiles in edge so that it's easy to sign in to environments. You can setup profiles using [this](https://www.microsoft.com/en-us/edge/learning-center/how-to-add-new-profiles?form=MA13I2)

**Comment by RickKush** [comment]
I couldn't find how to clear the cache in Chrome, so I just created the profile, and I'm good now! Thanx!!!
