### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYODL

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#7409]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

Do you have any end to end documentation (how to setup) for BYODL?

Thank you,

### What solution are you experiencing the issue with?

None

### What solution version are you using?

January2024

### What method are you using to get inventory and telemetry?

None

AB#1976

**Comment by Jenefer-Monroe** [comment]
Hello. 
First you need to set up the Data Export product feature, 
[Set up Microsoft Power Platform self-service analytics to export Power Platform inventory and usage data (preview)](https://learn.microsoft.com/power-platform/admin/self-service-analytics#set-up-the-data-export-process-for-your-tenant)

This can take some time, up to a week or two for all the folders to get created and filled.

Then once you have all the data pumping in from the product, you can setup the Inventory through the Setup Wizard. There is a screen to select BYODL architecture type in that app.

To setup the PBI, you will need to follow the instructions here:  [Configure the BYODL Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-byodl-power-bi-dashboard)

Hope that helps

**Comment by lingutla123** [comment]
Thank you Jenefer.
