### ISSUE TITLE
[CoE Starter Kit - QUESTION] What is the best way to automate CoE deployments?

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#7410]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, everyone,

What is the best way to obtain the "unmanaged" copy corresponding to the CoE Core "managed" solution, as part of a certain release? Reason I ask is because unmanaged copies of the Core, that are being part of the CoEStarterKit-Unmanaged package are not always in sync with the provided managed Core solution. For example, September 2023 release has version 4.13 as unmanaged solution and 4.15 as managed solution. This makes it hard to determine if the unmanaged solution should be paired with the managed solution and be considered as a "true" release. 

My challenge comes when trying to automate CoE deployments via Pipelines, where an unmanaged copy is required to start the automation. Hope this all makes sense, your help is appreciated. Thanks!

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1977

**Comment by RahulBojji** [comment]
@VanIsleCA 
In the last releases there was an issue with the pipeline where it was not updating the correct unmanaged version when compared with the managed one. We reached out to concerned team on that and they have resolved that issue. In the January release both unmanaged and managed one's has identical version number.
You can download it at [this](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-January2024/CoEStarterKit-Unmanaged.zip)

**Comment by RahulBojji** [comment]
closing out as no further action for starter kit team
