### ISSUE TITLE
[CoE Starter Kit - BUG] Can not change Owner in PowerBI dashboards for Power Automate 

### ISSUE THREAD

**Issue by juergjue** [microsoft/coe-starter-kit#7415]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
previously I had the option to "Make Owner" in the PowerBi Dashboard for Flows, using the "Managed Flow Access" Tab in PowerBi Desktop. But now there is no possibility to do so.

Currently I'm using the CoeStarterkit: [CoE Starter Kit November 2023](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2023)

![image](https://github.com/microsoft/coe-starter-kit/assets/100994791/0a695d32-9f9a-47e0-953e-5f97e451b324)

I tried to import the source pbit file "Production_CoEDashboard_October2023.pbit" again from the CoEStarterkit, but the result is the same, I'm not able to change the Owner of a Flow.

For PowerApps it works, but looks different than before.
![image](https://github.com/microsoft/coe-starter-kit/assets/100994791/bda037a3-93b1-4046-afb0-433f146ea4e5)

### Expected Behavior

Expected behaviour shall be to being able to change the owner of a Flow within the PowerBi Dashboard.

![image](https://github.com/microsoft/coe-starter-kit/assets/100994791/b9dc31d6-4696-4b74-9b66-80277b362e32)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin - Access this Flow [works embedded in Power BI only]

### What method are you using to get inventory and telemetry?

None

AB#1988

**Comment by juergjue** [comment]
I have now figured out, that it was only possible for apps, but never for flows.
So it is more a feature request than a bug. 
Thanks

**Comment by Jenefer-Monroe** [comment]
Thank you for posting. Yes this is definitely something we want to do soon. Its a newer feature in the product to support a flow owner and we have not yet incorporated it. We are waiting for one more product change and then will fund this work. Please see [#3052](https://github.com/microsoft/coe-starter-kit/issues/3052)
