### ISSUE TITLE
[CoE Starter Kit - BUG] Inactivity notifications sent out even if all approvals have been responded to

### ISSUE THREAD

**Issue by hanuschkaih** [microsoft/coe-starter-kit#7416]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

- A manager has received escalation emails (you employees did not respond...) for flows where all approval requests had been responded to.
- The main reason seems to be that the "ignored since" field still had a date for those flows, even if no open approvals were left.
- To analyze this, I have created a fetchxml query to identify these flows (see below)
- I have manually deleted the "ignored since" field for all affected flows some weeks ago, thinking this comes from a bug from older versions
- However, some flows show up again that show the same behaviour

### Expected Behavior

"Ignored since" field is empty if there aren't any pending approvals

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

CoreComponents_4.22 and AuditComponents_3.14

### What app or flow are you having the issue with?

Admin | Email Managers Ignored Inactivity notifications Approvals

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Don't know how to reproduce this beaviour, buth let me send you the script to analyze flows (and apps)

Flows
```
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="admin_flow">
    <attribute name="admin_flowid" />
    <attribute name="admin_flowenvironmentdisplayname" />
    <attribute name="admin_displayname" />
    <attribute name="admin_flowarchiverequestignoredsince" />
    <attribute name="admin_flowexcusedfromarchival" />
    <attribute name="admin_flowcreator" />
    <attribute name="ownerid" />
    <filter>
      <condition attribute="admin_flowarchiverequestignoredsince" operator="not-null" />
      <condition attribute="admin_flowexcusedfromarchival" operator="eq" value="0" />
      <condition entityname="admin_archiveapproval" attribute="admin_archiveapprovalid" operator="null" />
    </filter>
    <link-entity name="admin_archiveapproval" from="admin_flowlookup" to="admin_flowid" link-type="outer">
      <attribute name="admin_appownername" />
      <attribute name="admin_approvalid" />
      <attribute name="admin_flowlookup" />
      <attribute name="admin_approvalresponse" />
      <attribute name="admin_approvalresponsedate" />
      <link-entity name="msdyn_flow_approval" from="msdyn_flow_approvalid" to="admin_approvalid" link-type="outer">
        <attribute name="msdyn_flow_approval_completedon" />
        <attribute name="msdyn_flow_approval_name" />
        <attribute name="msdyn_flow_approval_stage" />
        <attribute name="msdyn_flow_approvalid" />
        <attribute name="ownerid" />
        <attribute name="statecode" />
        <attribute name="msdyn_flow_approval_result" />
        <attribute name="createdon" />
      </link-entity>
    </link-entity>
  </entity>
</fetch>  
```
Apps
```
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="admin_app">
    <attribute name="admin_appid" />
    <attribute name="admin_appenvironmentdisplayname" />
    <attribute name="admin_displayname" />
    <attribute name="admin_apparchiverequestignoredsince" />
    <attribute name="admin_appexcusedfromarchival" />
    <attribute name="ownerid" />
    <filter>
      <condition attribute="admin_apparchiverequestignoredsince" operator="not-null" />
      <condition attribute="admin_appexcusedfromarchival" operator="eq" value="0" />
      <condition entityname="admin_archiveapproval" attribute="admin_archiveapprovalid" operator="null" />
    </filter>
    <link-entity name="admin_archiveapproval" from="admin_applookup" to="admin_appid" link-type="outer">
      <attribute name="admin_appownername" />
      <attribute name="admin_approvalid" />
      <attribute name="admin_applookup" />
      <attribute name="admin_approvalresponse" />
      <attribute name="admin_approvalresponsedate" />
      <link-entity name="msdyn_flow_approval" from="msdyn_flow_approvalid" to="admin_approvalid" link-type="outer">
        <attribute name="msdyn_flow_approval_completedon" />
        <attribute name="msdyn_flow_approval_name" />
        <attribute name="msdyn_flow_approval_stage" />
        <attribute name="msdyn_flow_approvalid" />
        <attribute name="ownerid" />
        <attribute name="statecode" />
        <attribute name="msdyn_flow_approval_result" />
        <attribute name="createdon" />
      </link-entity>
    </link-entity>
  </entity>
</fetch>  
```

### Anything else?

Not sure if this relates to https://github.com/microsoft/coe-starter-kit/issues/6784 

AB#1989

**Comment by hanuschkaih** [comment]
Hi Jenefer, thanks for your fast reply.
I'm pretty sure that users go through the approval mail or teams notificaition, not the app (that would require Premium licenses only few people have)
As some (not all) flows are from orphaned users, I have possibly deleted the approvals through the Inactivity Notification Cleanup App. I did that for some approvals, but don't remember if these are the same flows that still have an "ignored since" date.
Best regards, Ihno

**Comment by Jenefer-Monroe** [comment]
Thank you that is helpful. Ill set this for investigation.

**Comment by Jenefer-Monroe** [comment]
Do you have this flow turned on and running? **_Admin | Inactivity notifications v2 (Check Approval)_**

**Comment by hanuschkaih** [comment]
Hi Jenefer,
yes, the flow is turned on and runs on a daily base, see screenshot.
Best regards,
Ihno
[cid:754270f8-9ce1-41ed-9aa5-4b7dd228be7b]

**Comment by Jenefer-Monroe** [comment]
Your screenshot did not come through. 

That flow does mark the objects as no longer stale when they are responded to. 

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9aa90560-7a56-4be8-965f-1d5a2a727b6e)

So I'm not sure how this might be happening for you. Can you please make sure there are no unmanaged layers on the flows?

**Comment by hanuschkaih** [comment]
Hi Jenefer, nope, no unmanaged layer, the flow looks the same as in your screenshot.
When i check the flow logik, I see that it runs through all archive approval records and clears the "Ignored Since" date when needed. So, I assume that archive approval records get deleted somewhere else (no idea why, how, where) - then this flow would not remove the date.

**Comment by Jenefer-Monroe** [comment]
That is checking the products archival table. And we dont delete records from that, the product itself has hygiene for it. 
I'm afraid without a repro I'm not sure how to proceed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
