### ISSUE TITLE
[CoE Starter Kit - BUG] January Upgrade Fail 

### ISSUE THREAD

**Issue by KYT9212** [microsoft/coe-starter-kit#7419]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting following error message upgrading from November release to January release. Getting following error message during core solution import. I was not able to find the mentioned columns in November release so I don't believe there is any unmanged layer on the existing solution (version 4.17). 

Import failed: The column 'admin_makersubmittedrequirements' is dependent on column 'admin_requirement_2'. ALTER TABLE ALTER COLUMN admin_requirement_2 failed because one or more objects access this column.

### Expected Behavior

Import without issue

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Issue with Solution import

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Download the CoE Core component January release (managed)
2. Import it to CoE Environment with November release as 'Upgrade'
3. About 45 min into import error is received

### Anything else?

![Screenshot 2024-01-09 135605](https://github.com/microsoft/coe-starter-kit/assets/136002212/89af1710-fc17-4e57-8559-402839afe575)

AB#1992

**Comment by niwrejim21** [comment]
We are getting the same error: 

![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/68c5b670-96de-4659-877b-f41dcc0cc322)

**Comment by Jenefer-Monroe** [comment]
Changes in Dataverse will not show an unmanaged layer, and I dont see a dependency there in the calculated column so I suspect you may have a local change. 

Can you please go to the tables in the envt (dont go form within the solution or you wont be able to view the formula) 
Go to the columns > Maker Submitted Requirements > Edit on the calculated column
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2cf6eeab-3a60-4bb5-bfc9-346725a88486)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d35b646b-f5e4-408e-b902-711b5d4ead33)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/21aa0310-1474-4422-8e8b-b7aa4cc9856b)

What formula do you see?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/837cef19-3cc9-41f1-86c3-9637dce5b5a9)

**Comment by niwrejim21** [comment]
Here is what I am getting:

![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/a85ba5d6-206a-4475-b7f3-d86234b1f96a)

**Comment by KYT9212** [comment]
Seeing the same thing as niwrejim21
![image](https://github.com/microsoft/coe-starter-kit/assets/136002212/69cc6315-9bea-41af-956f-829c4b1f6ac3)

**Comment by niwrejim21** [comment]
@KYT9212 and @Jenefer-Monroe , I was able to upgrade the solution by updating to the formula shown in Jenefer's screenshot:


![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/5685d9ec-7b01-4a38-9ded-41b7a09f8fd0)

**Comment by KYT9212** [comment]
Thank you for the above. Was able to complete upgrade as well after updating the query. Marking this as closed.

**Comment by Jenefer-Monroe** [comment]
Thanks so much for posting and investigating with me!

**Comment by s-ahtesham** [comment]
I just made the changes as suggested above but still not able to upgrade Jan OR Feb upgrade. Any suggestions would be appreciated. Thank you!

![image](https://github.com/microsoft/coe-starter-kit/assets/162335599/e6a7fc46-8614-48be-8bb6-478e45a35014)
