### ISSUE TITLE
If we delete records of admin_ConnectionReferenceidentityBase via Bulk Delete, will it have any impact on the app or flow being used?

### ISSUE THREAD

**Issue by Alexairrrr** [microsoft/coe-starter-kit#7420]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

If we delete records of admin_ConnectionReferenceidentityBase via Bulk Delete, will it have any impact on the app or flow being used?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#1993

**Comment by RahulBojji** [comment]
@Alexairrrr 
 As per this #7357, we recommend you to upgrade first and then do a delete on the above table, because of a bug that might exist in your version which will add duplicate entries into the table which can increase its size again.

**Comment by Jenefer-Monroe** [comment]
It sounds like you are asking if you can ignore the usage of this table or what purpose it serves in the kit. Please let me know if I'm incorrect. 
This table is used to fill in this table to allow people to see cross tenant identities (ie b2b users)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ac369bf8-cbd6-44af-b36d-1c07ac5192a2)

Nothing else in the kit will break if you ignore this table. 
But do note that until you upgrade, bulk deleting them will likely just result in them refilling in the broken (aka repetative) state. 
To prevent this, aside from upgrading, you can turn off this flow: **_Admin | Sync Template v3 (Connection Identities)_**

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
