### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrading from version 4.13 to 4.22 displays both version. 

### ISSUE THREAD

**Issue by bhaski30** [microsoft/coe-starter-kit#7424]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We recently upgraded the CoE Starter kit in Production and are currently having two versions Old and new. 

We got the below error, when installing the new version.
Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Workflow uninstall: FAILURE, workflow id 5625768c-bd3d-ec11-8c63-00224829720b category ModernFlow name HELPER - Send Email .

For sending Welcome email to users, we have added company specific HTML template. This created an unmanaged layer. We did not face such issues in the previous upgrades.
![coe](https://github.com/microsoft/coe-starter-kit/assets/156193348/c5d19281-97a8-402e-8d51-bf14fe305ca0)

### Expected Behavior

Expected behavior would be to uninstall the old version

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

HELPER - Send Email 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1998

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by bhaski30** [comment]
Even after removing all unmanaged layers, facing the same issue
