### ISSUE TITLE
[CoE Starter Kit - QUESTION] Does turning on Quarantine flows immediately quarantine apps?

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#7425]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have been using the compliance functionality for over a month and we are ready to turn on the quarantine flows. We have configured it to quarantine apps after 3 weeks.
The question is, will apps be quarantined immediately because the compliance request emails were first sent more than 3 weeks ago, or does the quarantine flow start the 3 week timer from the point the flow is turned on?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

November 2023

### What app or flow are you having the issue with?

Admin | Quarantine non-compliant apps

### What method are you using to get inventory and telemetry?

Cloud flows

AB#1999

**Comment by RahulBojji** [comment]
@MartinWGT

maker would receive an automatic compliance request email. If the maker does not respond to it within x days which is configurable via Environment Variable and their app is in an environment where quarantine is "enabled" then app gets quarantined and is maker notified.

**Comment by Jenefer-Monroe** [comment]
I believe the question is, if they've been running the compliance flows in the past, and then later turn on **_Admin | Quarantine non-compliant apps_**, what is the behavior. 
@MartinWGT  please confirm
Then @RahulBojji see if you can please help with that.

**Comment by MartinWGT** [comment]
Yes that is correct @Jenefer-Monroe

**Comment by RahulBojji** [comment]
@MartinWGT 

Here is the condition on which apps gets picked up.

<img width="719" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/208963f8-391b-4980-be39-295df7229f85">

As per the above logic, if you are turning on **Admin | Quarantine non-compliant apps** now when compliance flows are turned on way back, the flow still picks the apps after x days which is configured via environment variable and the app shouldn't be quarantined before and also if it satisfies the other conditions.

**Comment by MartinWGT** [comment]
Thanks for confirming. When I turn on the flow next week I expect several apps to become quarantined in the same day.
