### ISSUE TITLE
[CoE Starter Kit - QUESTION] detection of MDAs in Default Envt

### ISSUE THREAD

**Issue by smwill365** [microsoft/coe-starter-kit#7426]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a flow in the starter kit for managing the creation of Model Driven apps in the Default environment? We know you can't prevent people from creating model driven apps, but we are looking for a flow to notify us and and the user when one is created and automatically give us the option to delete it.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

May 2023

### What method are you using to get inventory and telemetry?

None

AB#2001

**Comment by Jenefer-Monroe** [comment]
Hello we don't have something like that and its a bit too specific to put in the kit. But it would be an easy add for you to start extending the kit. 
You could make a flow that runs every day. Have it list all the MDAs in Default Envt made that dayj, then act on the results. 
Something like this to help you get started, where you would put your default ent guid in the spot crossed out.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/64753cc4-854c-4509-b8bd-8e86bf84c29d)
