### ISSUE TITLE
[CoE Starter Kit - Feature]: To be able to see Co-Owners

### ISSUE THREAD

**Issue by tlanim** [microsoft/coe-starter-kit#7427]
### Describe the solution you'd like

Is it possible to add a way for admins to be able to see who the co -owners are for Power Apps and Power Automate via CoE Starter Kit? 

AB#2002

**Comment by Jenefer-Monroe** [comment]
This is possible today for Power Apps
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0bdb142f-fb0f-4e86-bea9-a5ed76ddcf28)

For Flows, we do not yet have this but we do hope to get it implemented with the feature crew described here: [#3052](https://github.com/microsoft/coe-starter-kit/issues/3052)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
