### ISSUE TITLE
[CoE Starter Kit - QUESTION] May the starter kit be installed in Dataverse for Teams? I couldn't find that this was possible in the docs.

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7428]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

May the starter kit be installed in Dataverse for Teams? I couldn't find that this was possible in the docs.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2003

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
