### ISSUE TITLE
[CoE Starter Kit - QUESTION] I am trying to setup COE kit in my environment what is the best place to start with?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7431]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am trying to setup COE kit in my environment what is the best place to start with?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2004

**Comment by RahulBojji** [comment]
Thanks for reaching out. You can start by looking into this official [documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/starter-kit) of COE. This includes the setup of COE, the components inside it and also explaining you how to use it.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
