### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why there is a dataflow to use in Power BI Reports? Why don''t use directly the information of dataverse coe environment?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7432]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Why there is a dataflow to use in Power BI Reports? Why don''t use directly the information of dataverse coe environment?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2005

**Comment by Jenefer-Monroe** [comment]
This was done so that features like app and flow usage could be used directly from the datalake rather than going through a write to the dataverse tables.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
