### ISSUE TITLE
[CoE Starter Kit - QUESTION] What would be the effect of not assigning premium licenses to the service account? Would processes just take longer?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7433]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What would be the effect of not assigning premium licenses to the service account? Would processes just take longer?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2006

**Comment by Jenefer-Monroe** [comment]
We have not tested this so I cannot give you a full list. But I believe you would not be able to even boot the Setup Wizard to get going, nor be able to turn on any of the flows due to pagination requirements of those flows.

**Comment by LycheeYum** [comment]
If pagination were lowered, would that flow take a lot longer?  I could see this having an effect on a large organization, but maybe it wouldn't be so bad in a smalll one?

**Comment by Jenefer-Monroe** [comment]
If pagination were lower then the larger organizations would not be able to collect all their data. 
Its basically, how many pages of results do you want to return. 

See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses as described in our [prerequisites]( https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
