### ISSUE TITLE
[CoE Starter Kit - QUESTION] General information about Data Export:

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7434]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

General information about Data Export:

I noticed the last month that in at least in one environment I don't have the GUIDcanvas.json file in Power Apps folder in the Storage Account.
I have a support case open, at the moment without response.

This is just a warning to other users in case they are missing power apps data at any time.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2007

**Comment by Jenefer-Monroe** [comment]
Thank you, yes the Data Export product feature that the CoE kit depends on for the BYODL implementation continues to be in public preview and so you may hit bugs like this and product support will be required to assist and get you unblocked.
