### ISSUE TITLE
[CoE Starter Kit - QUESTION] I need to find apps in our Tenant that is using Per App license and also report of the users so we can get them properly licensed

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7435]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I need to find apps in our Tenant that is using Per App license and also report of the users so we can get them properly licensed

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2008

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately we do not have access to licensing information and so our kit does not have any features around that.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
