### ISSUE TITLE
[CoE Starter Kit - QUESTION] When you go through the CoE kit installation, it asks for 3 security groups mail enabled. I used M365 Groups and it worked perfectly also for sharing apps or enabling security roles for users. Is that correct or should i consider moving to Security Groups?

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7436]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When you go through the CoE kit installation, it asks for 3 security groups mail enabled. I used M365 Groups and it worked perfectly also for sharing apps or enabling security roles for users. Is that correct or should i consider moving to Security Groups?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by RahulBojji** [comment]
Thanks for reaching out. Yes, correct we also recommend you use M365 groups. Please also have a look at this [documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users) for more information

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
