### ISSUE TITLE
[CoE Starter Kit - QUESTION] can you help to find documentation on that cross division things, like adding the more screenshots like how dose that look after adding cross tenants. Waiting to check how does COE looks with two divisions.

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#7437]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

can you help to find documentation on that cross division things, like adding the more screenshots like how dose that look after adding cross tenants. Waiting to check how does COE looks with two divisions.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2009

**Comment by Jenefer-Monroe** [comment]
I think this is in regards to the new cross domain feature we showed today. Is that correct? 
If so we do have this documentation bug open for it. Please take a look and let me know if there are other things you'd like to see.
https://github.com/microsoft/coe-starter-kit/issues/7164

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
