### ISSUE TITLE
[CoE Starter Kit - BUG] App Detail page missing from BI report

### ISSUE THREAD

**Issue by uber-lord** [microsoft/coe-starter-kit#7439]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I'm trying to configure embedded apps as the last step of setting up my BI report for the core kit, I've imported through Flows and used the Production Report.
I've confirmed I meet the requirements, but when i go to embed the apps the App Details page is not part of my BI report (it looks very different from the version on the docs page).
As this documentation a few months old has this functionality been moved out to another page/part of the CoE kit?
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#embed-apps-into-the-power-bi-dashboard

### Expected Behavior

App details page available in the core BI report in order to enable embedded apps as per documentation

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Production_CoEDashboard_January2024

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

linked to the environment where CoE is installed.
Met the requirements.
Open the report and connect to environment
try to navigate to App Details page

### Anything else?

I've included screen shots of the pages available in the report to navigate to, App Details is not among them
<img width="204" alt="Screenshot 2024-01-10 at 16 35 42" src="https://github.com/microsoft/coe-starter-kit/assets/72256648/d0d48273-7fb6-4630-b146-91086be78070">
<img width="200" alt="Screenshot 2024-01-10 at 16 35 55" src="https://github.com/microsoft/coe-starter-kit/assets/72256648/2e5b1aa2-19c0-4bbc-95a7-e2754631bc00">

AB#2011

**Comment by Jenefer-Monroe** [comment]
Hello. We renamed these tabs and forgot to update the documentation. 
Please see https://github.com/microsoft/coe-starter-kit/issues/7399 for the correct information as its the documentation bug for us to fix that up
