### ISSUE TITLE
[CoE Starter Kit - Feature]: can the record owners be the Makers

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#7441]
### Is your feature request related to a problem? Please describe.

I was thinking if i can give the PP Admin view to everyone but I only want them to see their own apps, flows etc.
All of the records in my CoE has our CoE role account as the owner so its not possible

### Describe the solution you'd like

can the Owner be the same as the Maker

### Describe alternatives you've considered

I do have power BI RLS 

### Additional context?

none

AB#2013

**Comment by Jenefer-Monroe** [comment]
Hello. We will not be able to do this generally for the kit but yes I believe you could use either the owner field or the owning business unit field and assign out records to people or groups. 
If you experiment with this and get something cool in place it would be a great community post / blog you could publish!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
