### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is the Governance Component no longer needed?

### ISSUE THREAD

**Issue by tlanim** [microsoft/coe-starter-kit#7442]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have downloaded the new CoE Starter Kit and the Governance Component is not included in the kit. But upon attempting to install the Audit Log I get this error: Import failed due to missing dependencies for Center of Excellence - Governance Components.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.22

### What method are you using to get inventory and telemetry?

None

AB#2014

**Comment by RahulBojji** [comment]
@tlanim Governance components are required. In the latest [release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-January2024) 

<img width="925" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/c8f2e426-78c5-4723-87ed-4dfa8f75edd8">
You need to use audit log components solution for setting up governance in your environment. If your installing COE kit for the first time, please make sure you are following this [documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/before-setup-gov). This approval flow creation is required as it installs approval solutions which are needed to setup governance module. 
 
If this is not the case, can you please share the steps and the screenshots of the issues you are facing.

**Comment by tlanim** [comment]
The Audit Component you have circled is not located in the new release. I tried several times to upload a pic of the starter kit contents but Github kept removing it. How can I get the Audit Component?

**Comment by tlanim** [comment]
Hi Rahul, what about the error message I mentioned earlier. Why am I getting that error message when trying to install the governance component? The dependency says I need to install msdyn_FlowApprovalsCore (2.0.4.8) (1), where can I find this?

**Comment by RahulBojji** [comment]
if you create an approval flow as mentioned in the documentation, it will install two solutions related approvals one is msdyn_FlowApprovalsCore solution

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
