### ISSUE TITLE
[CoE Starter Kit - BUG] Set Flow Permissions App- Owner field is blank for all the flows

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#7443]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have recently upgraded COE starter kit January version. In Admin Set Flow Permissions app, we see that the Owner field is blank for all the flows of all the environments. Could you please help us on this.

![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/f164e999-e49a-4623-91bb-7be31d885e96)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

App

### What method are you using to get inventory and telemetry?

Data Export

AB#2018

**Comment by Jenefer-Monroe** [comment]
Can you please confirm, are these blank in the data itself or just the app? 
You can see this by comparing with what you see in the Power Platform Admin View model driven app.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
