### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade failure from Audit Logs solution

### ISSUE THREAD

**Issue by WABAM2406** [microsoft/coe-starter-kit#7446]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We get the following error when trying to import a new version 4.13

![image](https://github.com/microsoft/coe-starter-kit/assets/156316681/9278dd6b-3a8b-436a-bc8a-81df54ce62a6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Import new solution of coe core components 

AB#2022

**Comment by RahulBojji** [comment]
Hello, this is an expected upgrade failure due to the deprecation of the Audit Logs custom connector.
Please see the following to resolve. https://github.com/microsoft/coe-starter-kit/issues/6018

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
