### ISSUE TITLE
Multiplexing verification (using the COE Starter Kit data outside Dataverse)

### ISSUE THREAD

**Issue by MohamedSattar** [microsoft/coe-starter-kit#7447]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I would like to Utilize the COE Start Kit as Is for Admins only (Admin, Governance Modules in particular), The Nurture Module I'd like to do it differently and Based on SharePoint as a backend for licenses reasons.
 
Questions is, Can I use the COE starter Kit data (Apps, Flows, Solutions, etc.) to trigger a process on SharePoint?  Would that Scenario considered Multiplexing? 
 
Considering that Data is available anyway via PowerShell and through the Admin connector.
 

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2023

**Comment by Jenefer-Monroe** [comment]
Hello. Yes, as you correctly ascertain, that would be a multiplexing. 
While I am sure this is something that you could do, it isn't something that I can assist with as its against usage policy by the product. 
Sorry about that!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
