### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Administration Planning PBI Report

### ISSUE THREAD

**Issue by bocESMI** [microsoft/coe-starter-kit#7451]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to set up the Power BI Dashboard - Under "Set up administration planning components" section https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-admin-tasks-component#set-up-the-power-bi-dashboard
and have run into a bug when opening the Power Platform Administration Planning.pbit report. 

Error message at the top "Some of the tables have incomplete or no data and Load pop up appears as well. I have attached an image of what I am seeing

![2024-01-11_14-38-47](https://github.com/microsoft/coe-starter-kit/assets/32463806/1a85d5ef-7424-4831-ace7-15fa715f279f)
![2024-01-11_14-38-47](https://github.com/microsoft/coe-starter-kit/assets/32463806/ef1102f7-b673-4be7-b960-d643af5d586b)

### What solution are you experiencing the issue with?

Admin Task Planner

### What solution version are you using?

Oct 2023 version

### What app or flow are you having the issue with?

Power Platform Administration Planning PBI report

### What method are you using to get inventory and telemetry?

None

AB#2029

**Comment by Jenefer-Monroe** [comment]
Have you done the step to [import sample admin task data](https://learn.microsoft.com/power-platform/guidance/coe/setup-admin-tasks-component#import-sample-admin-task-data) and if so do you see the data as suggested here?

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d7077354-25c7-4058-ab72-ddc068fc8c4b)

**Comment by bocESMI** [comment]
Hi Jenefer, thank you for your response.
I did import the sample task list and here is a screenshot 
![Issue 7451 - 2024-01-12_11-07-57](https://github.com/microsoft/coe-starter-kit/assets/32463806/a367b14d-d424-4771-b7d7-f305d3ee09dc)

**Comment by Jenefer-Monroe** [comment]
There must have been some errors on data import. Can you try again? 
Please ensure you review the mapping 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/712f1651-c8d7-4b15-8c81-fc25c7da0063)

And track progress
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f04ced67-81d6-4f0c-9fc8-9f9059494741)

Then that all 77 succeed
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/291ae1a1-cbc8-42cc-9f52-00460478cbc2)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
