### ISSUE TITLE
[CoE Starter Kit - BUG]Power Automateの子フロー起動時にエラー

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#7452]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Power Automateの子フロー起動時に下記のようなエラーが出力されます
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"ID '9301f01a-cb40-ec11-8c62-00224829b4c1' のワークフローは、これまでに 1 回も発行されたことがないため、子ワークフローとして使用できません。発行された親ワークフローに含めるには、子ワークフローを少なくとも 1 回発行する必要があります。"}}".

エラーの影響でコアコンポーネントのデータ収集ができない状況です
エラーの回避方法などありましたら教えていただきたいです

### Expected Behavior

応答なし

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2024年1月版

### What app or flow are you having the issue with?

コンポーネントのPower Automate

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

応答なし

### Anything else?

応答なし

AB#2030

**Comment by RahulBojji** [comment]
@asuka1103131 Thanks for reaching out. Looks like the flow which you are trying to turn on is calling another flow inside it which is not yet turned on. Please turn on the child flow before turning the parent one.

Please open the flow which you are trying to turn on and see if you can find the flow inside it

For Example, if i am trying to turn on "**Admin | Sync Template v3 (Sync Flow Errors)**" i cant turn on it untill i turn on the child flow "**HELPER-Send Email**"

<img width="742" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/493b39cd-5220-4c0d-8436-f5428fd0337c">

**Comment by asuka1103131** [comment]
<img width="818" alt="キャプチャ" src="https://github.com/microsoft/coe-starter-kit/assets/156406138/5e26094a-79ab-4a11-b911-a08836cadad0">
@RahulBojji 
ご連絡ありがとうございます。
今回の場合だと、子フローの起動がうまくいっていません...
画像も添付いたします。
対象フロー：HELPER - CloudFlowOperations
![image](https://github.com/microsoft/coe-starter-kit/assets/156406138/f713d248-a8f2-4c95-be0f-e8a8834b9714)

**Comment by asuka1103131** [comment]
@RahulBojji 
日本語で分かりづらければ英語の画像添付します

**Comment by RahulBojji** [comment]
Moving forward, please convey in english. Looks like same issue, please open the flow and check the child flow inside it.
Looks like here you need to turn on "**HELPER - Maker Check**" flow first and then turn on HELPER - Cloud Flow Operations

**Comment by asuka1103131** [comment]
@RahulBojji 
I was able to resolve the issue regarding the child flow.
Thank you for your contact.
