### ISSUE TITLE
[CoE Starter Kit - QUESTION] If I rename an environment in the PP admin center, the name is not updated in the CoE admin center

### ISSUE THREAD

**Issue by bdcqr** [microsoft/coe-starter-kit#7458]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

If I rename an environment in the PP admin center, the name is not updated in the CoE admin center. I also do not see a way to edit the name in COE admin. Is there a way to do this automatically? if not, manually?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

October 2023

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2038

**Comment by Jenefer-Monroe** [comment]
Environment name changes should update in the CoE automatically with the next run of the inventory. 
Can you please share a screenshot of where you are expecting the name to show differently? 
Note that screenshots do not work if you respond in email, you will need to log in to GitHub to share them.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
