### ISSUE TITLE
[CoE Starter Kit - BUG] Dataflows DataFormat.Error

### ISSUE THREAD

**Issue by Vegaspower** [microsoft/coe-starter-kit#7462]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have installed the latest version of the CoE Starterkit (January 2024). We are trying to setup the dataflows. After entering the required parameters and creating the connection successfully;  We experience the following error: 
![image](https://github.com/microsoft/coe-starter-kit/assets/15385622/aa4da5cc-0783-4fa3-abde-c4e134637ee6)

**We are getting this issue with all dataflows in the solution.** 

DataFormat.Error: The Container name must be 3 to 63 lower case letters and numbers. It must start with a letter or number and can contain only letters, numbers, and the dash (-) character. No consecutive dashes are allowed. Every dash (-) character must be immediately preceded and followed by a letter or number.

### Expected Behavior

No errors after entering the parameters and creating the connection. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

CoE BYODL Makers

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Importing the core solution
2. Following the CoE setup wizard steps until the Dataflows Export step
3. For a dataflow: Entered the parameters
4. Configured the connection
5. Error appears

AB#2042

**Comment by Jenefer-Monroe** [comment]
We've seen this once before but I cant find it. It was some configuration issue I believe due to capturing the wrong string for Datalake URL

Please confirm:
1. You've had this working in the past before upgrade. This will make sure the issue actually is not in the way you named something in the datalake.
2. The string you entered for Datalake URL looks like this: 
    ### https://accountname.dfs.core.windows.net/powerplatform

Sometimes people grab the wrong endpoint in this step [Copy Azure Storage Account URL](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#copy-azure-storage-account-url). Its the Data Lake Storage endpoint you need to use.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e4f77c5c-d631-4343-a834-82eaa2f27bd2)

**Comment by Vegaspower** [comment]
> We've seen this once before but I cant find it. It was some configuration issue I believe due to capturing the wrong string for Datalake URL
> 
> Please confirm:
> 
> 1. You've had this working in the past before upgrade. This will make sure the issue actually is not in the way you named something in the datalake.
> 2. The string you entered for Datalake URL looks like this:
>    ### https://accountname.dfs.core.windows.net/powerplatform
> 
> Sometimes people grab the wrong endpoint in this step [Copy Azure Storage Account URL](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#copy-azure-storage-account-url). Its the Data Lake Storage endpoint you need to use. ![image](https://private-user-images.githubusercontent.com/89584709/296773746-e4f77c5c-d631-4343-a834-82eaa2f27bd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjc1NjQsIm5iZiI6MTcwNTMyNzI2NCwicGF0aCI6Ii84OTU4NDcwOS8yOTY3NzM3NDYtZTRmNzdjNWMtZDYzMS00MzQzLWE4MzQtODJlYWEyZjI3YmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE0MDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNmY2YzIzMGQ3ZDNiNTc1MDlhNzhiYjkyYjM2OWJlMTEwMzEyZWU3Yzc1ZWIyNjY5NDQyZmZhZTc5YjMxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HAIVdJ7os6ntNFDcBXqZridfknNhV30wMXnsvOyFM5U)

Thanks for the fast response! It was fixed by adding "/powerplatform" to the Datalake URL

**Comment by Jenefer-Monroe** [comment]
YEAH!!!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
