### ISSUE TITLE
[CoE Starter Kit - QUESTION] Office hours - what time ?

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#7463]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I'm sorry to ask my question here, but I don't know where to ask it, but it's still related to the COE.

I'm a little confused about the hours. It says 10 to 11 but I'm not sure what your time zone is. It says UTC+0 on my outlook. Is that right?

I have to be able to adjust the time since I live in Quebec City

Thanks for your reply

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2043

**Comment by Jenefer-Monroe** [comment]
Hello. You can get information about the office hours here: https://aka.ms/coeofficehours
They are held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
The file, if you download it, should open to the time configured in your outlook. 

I hope that helps!

**Comment by tocri** [comment]
thanks you it helps a lot

**Comment by Jenefer-Monroe** [comment]
YEAH!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
