### ISSUE TITLE
[CoE Starter Kit - QUESTION] How can I get a full inventory of AI Builder Models? 

### ISSUE THREAD

**Issue by niwrejim21** [microsoft/coe-starter-kit#7464]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Data about our AI Builder Models is not consistent on what we actually have (Right now, it is only showing 6). I am assuming that this is because of the new feature in the January release wherein it is getting only the recent data.  Is there a way I can get a full inventory of only AI Builder models? Due to the size of our org, I am a bit afraid to delete the DataRefreshHistory records as we have hit the dataflow limit before.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

January Release 4.22

### What method are you using to get inventory and telemetry?

Data Export

AB#2044

**Comment by Jenefer-Monroe** [comment]
The data refresh history table will not impact AI Models as the data for those does not come through the BYODL Data Export. 
Can you please see which of these flows you have on and running? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1623a81f-b75c-49aa-a888-7f6d2a65af84)

**Comment by niwrejim21** [comment]
@Jenefer-Monroe v3 is running

![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/f4a4940e-ac3a-4654-a9c9-b5c792dec8bc)

**Comment by Jenefer-Monroe** [comment]
Please find a recent run of the flow for an evnt where you expect to see AI models but do not

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4d3c6cf6-d58b-45c4-a667-7ca943f2b2b4)

See if you see the desired models as the output of this call:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/33053c5f-168f-4ece-bb66-d6a5e4e109d2)

**Comment by niwrejim21** [comment]
Yeah, I can see that AI Models are being returned per environment. However, it is not showing in the report (still showing 6). The flow output below returned 36 AI Models.

![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/037afc2c-92e4-4fdf-821e-5821aedb51e7)

![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/8fbcad42-2b32-45e0-8831-b8abf45933a6)

**Comment by Jenefer-Monroe** [comment]
By default that report only shows custom ones. 
Can you see if you see the rest by choosing another filter?
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/99dd1c82-5045-4c78-98e7-1798094e9b52)

**Comment by niwrejim21** [comment]
Found it! They are under deleted custom AI Models - just to confirm, they are only being marked deleted from the inventory, right ? not actually deleting it? 

![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/4c7b1920-20a8-4cb5-b887-8483e2712420)

**Comment by Jenefer-Monroe** [comment]
Correct, but they should not be marked deleted if they still exist in the tenant. But now we know where to look! 
The next version of the kit (Feb 2024) will have the v4 version of the flow here on by default which will restore issues like this. 
But lets see if we can deduce what is happening here. 

I presume you have these the v3 versions of these flows on and running. Can you please confirm? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/345ea813-d415-428e-89f4-5dfaea0306d5)

If so, please go clear the AI Model Deleted flag back to no for all the models in an environment. 
You can do this either by exporting to Excel or using the Dataverse UX like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/62cdbb32-9705-4e9a-8595-f5e8015bbf16)

Then go run this flow by entering the envt guid  in both the GUID params and checking "CheckIfDeleted" to true: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b8d9e305-6273-4254-a241-10e460b4db81)

Open the run that occurs and we can debug together when finished. But please check to see if they were marked deleted again.

**Comment by niwrejim21** [comment]
It is the other way around. All V4s are turned - on:

**Comment by niwrejim21** [comment]
@Jenefer-Monroe, would you know how I can revert back the value for the Deleted column for all resources and what is the reason behind this? I can see that this is happening for flows, apps, bots, connectors and environments. Even the default environment is now under the filter "deleted environment review".

**Comment by Jenefer-Monroe** [comment]
Typically this happens when someone does not have the Power Platform Admin Role permanently and directly assigned. When the check deleted flows run there is no access and then the objects are deemed deleted.

So we'll do V4 insetead then. If so, please go clear the AI Model Deleted flag back to no for all the models in an environment. 
You can do this either by exporting to Excel or using the Dataverse UX like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/62cdbb32-9705-4e9a-8595-f5e8015bbf16)

Then go run this flow by entering the envt guid  in both the GUID params and checking "CheckIfDeleted" to true: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b8d9e305-6273-4254-a241-10e460b4db81)

Open the run that occurs and we can debug together when finished. But please check to see if they were marked deleted again.

**Comment by niwrejim21** [comment]
- We are using an account with a permanent Power Platform admin role. 
- I have re-run the flows and only three AI models were marked for deletion this time. May I know what are the criteria for an AI model marked for deletion?
- There are quite a large number of flows and apps that are now marked for deletion. What is the easiest way to clear this again? our tenant is quite large - 30k flows and 5k+ apps

**Comment by niwrejim21** [comment]
Hi again @Jenefer-Monroe, I did a refresh of all dataflows and it seems data is now consistent on what we currently have. Thanks for all your inputs - appreciate all the help.

**Comment by niwrejim21** [comment]
3
