### ISSUE TITLE
[CoE Starter Kit - QUESTION] Question about how the COE audit logs works

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#7470]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am trying to explain to my cybersecurity department how the COE audit logs work.

So far, I have the quick summary below:

The **“COE Audit Log flow"** uses the “Audit Logs - Client Azure Secret” environment variable to
authenticate to the Azure Key Vault and get the secret to the “Office 365 Management API”
app registration. The **“COE Audit Log flow"** then uses the “Office 365 Management API” to gather audit log data from Microsoft Purview. It stores this audit log data in a Dataverse table. This Dataverse table can then be viewed using the "Power Platform Admin View" PowerApp.

Note: the **“COE Audit Log flow"** only gathers telemetry data (audit log data) on PowerApp launches.

I put **“COE Audit Log flow"** as a placeholder.
I'm not 100% sure which flow it is?

Is it this one?
Admin | Audit Logs | Sync Audit Logs (V2)

Also, if there is anything incorrect in my summary, please let me know.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2053

**Comment by Jenefer-Monroe** [comment]
Hello. Everything is correct here except this statement:

> Note: the “COE Audit Log flow" only gathers telemetry data (audit log data) on PowerApp launches.

Unfortunately this API odes not have a way to filter to only Power Apps launches. So it gathers much more (things like Dataverse actions) and then we filter down to the launches in the flow.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
