### ISSUE TITLE
[CoE Starter Kit - QUESTION] Nurture Component

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#7471]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team, 

Is there any way we could test out (for admin to see the results of those flows) 3 flows under the Nurture Component: (Admin | Newsletter with Product Updates and 2 Pulse Survey Flows)? I have already set the ProductionEnvironment variable to "No" which will redirect some flows to be sent to the admins, not to the resource owner. If that's not the case, how can we test out those flows before it gets sent off to the makers? 

Also, could we specify who will be getting the "Admin | Newsletter with Product Updates?" Would it be all the Admins for Power Platform Environments? Or only the service account that's deploying CoE? 

Please advise. 

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

Jan 2024

### What app or flow are you having the issue with?

Admin | Newsletter with Product Updates 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Unfortunately today we do not have a way to customize the cards, we have it on our backlog but do not expect it to be funded in the near term. Sorry about that!

**Comment by iamjina** [comment]
Thanks Jenefer!
