### ISSUE TITLE
[ALM Accelerator - QUESTION] Default configuration for Branches

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#7472]
### What is your question?

Hi Team,
What are the default configurations for the source and target branches for commits, as well as for each deployment stage (validation, test, and production)?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

January 2024

AB#2056

**Comment by RajeevPentyala** [comment]
@LucX4 To understand the configurations, please refer the documentation [here](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-deployment-user-settings)

To understand the complete commit process and how the branching works, please refer the previous [ticket](https://github.com/microsoft/coe-starter-kit/issues/7057#issuecomment-1807753131) similar to this.

**Comment by LucX4** [comment]
Hi @RajeevPentyala, thanks very much!
What about the Validation pipeline? I know it gets triggered as soon as we start the deployment to Test, right?
Just want to understand what happens here:
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/b742e6f9-8e9d-4c73-81dc-c3e91dc35761)

**Comment by RajeevPentyala** [comment]
@LucX4 Validation pipeline triggers when you create a Pull Request to marge changes in to your 'Solution' branch. To understand this better, please refer the paths rendered in 'paths:' tag of 'deploy-validation' yml file.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/36e3d6c6-1a82-4bf5-85e7-045c1d9aff45)
