### ISSUE TITLE
[ALM Accelerator - BUG]: No flow sort order in deployment settings

### ISSUE THREAD

**Issue by ryanmichaeljames** [microsoft/coe-starter-kit#7473]
### Describe the issue

I'm getting an error message when the flows are being activated.

I checked the flow activation order in the deployment settings and i do not see the flow order arrows as per the [official documentation](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/advanced-maker-experience). What am I doing wrong?

My Environment:
![image](https://github.com/microsoft/coe-starter-kit/assets/16380903/8e0c2d42-fef9-487d-8112-1c747c524391)

Offical Documentation:
![image](https://github.com/microsoft/coe-starter-kit/assets/16380903/db3938c3-cf73-4992-9876-1bad4d9897b7)

What am I doing wrong?

### Expected Behavior

I should be able order my flows

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231004.1

### Steps To Reproduce

1. Open ALM Accelerator app
2. Select environment
3. Click `Configure Deployment Settings`
4. Click `Flows` tab

### Anything else?

The committed `customDeploymentSettings.json` file's `ActivateFlowConfiguration` items look as follows. The `sortOrder` is not a numeric value. Is that correct?

```json
{
    "solutionComponentName":  "MyFlow",
    "solutionComponentUniqueName":  "7a18af0b-bc67-ee11-9ae7-00224893360d",
    "sortOrder":  "#{activateflow.order.MyFlow.7a18af0b-bc67-ee11-9ae7-00224893360d}#",
    "activate":  "#{activateflow.activate.MyFlow.7a18af0b-bc67-ee11-9ae7-00224893360d}#"
}
```

AB#2057

**Comment by MaheshSripada** [comment]
Hi @ryanmichaeljames,

We will look into this and update you.

**Comment by mikefactorial** [comment]
@ryanmichaeljames the flow activation order was removed in a previous release since it was no longer necessary. See this issue for more detail https://github.com/microsoft/coe-starter-kit/issues/7047#issuecomment-1801982780. It would help to see the specific error message / logs to determine the root cause of your issue, but you may need to export the solution again to update the custom deployment settings.

@MaheshSripada the documentation will need to be updated to reflect the removal of the sort order from the UX.

**Comment by mackemlad** [comment]
@mikefactorial I see commits against [#209 for the GitHub templates](https://github.com/rpothin/PowerPlatform-ALM-With-GitHub-Template/issues/209) to support the retry functionality you describe, but I don't see any retry logic in the [activate-flows script for Azure repos](https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/PowerShell/activate-flows.ps1).  It appears to continue to be entirely dependent upon sort order.

Would you please elaborate on whether the retry functionality is supported when using Azure Git repos and if not can you restore the sort order functionality in the ALM Accelerator UI until such time as it is?  Thanks!
