### ISSUE TITLE
[CoE Starter Kit - BUG] Accidently deleted or deactivated an envt in Power Platform Admin View, how get back.

### ISSUE THREAD

**Issue by mustafaevrenpolat** [microsoft/coe-starter-kit#7474]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When moving applications between environments on Power Platform Admin View . 
I may have pressed the button to delete or deactivate the environment.
I cannot see the default environment on Admin View Environment List. But I see all app on Default environment over make.powerapps.com.

### Expected Behavior

I would like to be able to view the Ford Otosan default environment in Admin view environment list.

![default](https://github.com/microsoft/coe-starter-kit/assets/19271919/597071f2-9fc7-454f-aa90-ca9d074d8b4f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Ford Otosan default environment

### What method are you using to get inventory and telemetry?

None

AB#2058

**Comment by RahulBojji** [comment]
@mustafaevrenpolat If you have deactivated the environment, you can find the environment like this
Environments -> Active Environments ->Click on Edit Filters -> Select Inactive and click Apply

<img width="659" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/77dc1cfc-c313-4419-abcc-0a4a420d5993">

If any environments are deactivated, you will be to see those here. If your environments are present here, you can open the environment and click activate button. Your environment will be visible in the Active Environments list once you have reverted back the filter.
If you have deleted the environments, **Admin | Sync Template v3 (Driver)** runs daily and checks the environments and adds the environment back. You should be able to see the environment in the next inventory run.

**Comment by mustafaevrenpolat** [comment]
Thank you. Problem solved.

**Comment by RahulBojji** [comment]
Cool, Thanks for confirming.

**Comment by RahulBojji** [comment]
closing out as no further action for starter kit team
