### ISSUE TITLE
[CoE Starter Kit - BUG] Permission issue in Add Maker to Group

### ISSUE THREAD

**Issue by uka-support** [microsoft/coe-starter-kit#7475]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We've set up the CoE starter kit in our test environment. The flow "Admin | Add Maker to Group" keeps failing:

![image](https://github.com/microsoft/coe-starter-kit/assets/6216577/4dcfacd4-6513-489d-9837-6640e122d225)

We checked other bug reports and ensured:

1. flow runs as the CoE service user which is a Power Platform Administrator
2. the group has been created as a mail-enabled security group within Exchange Admin center
3. AAD role assigment is not enabled for the group
4. the service user is owner of the group
5. we renewed several connections which are broken (the flow doesn't show broken connections)

The group is currently empty.

We tried recreating the group, changed the ID in Setup Wizard, tried to resubmit a failed flow - same error, only the group ID is the new one (so our change was reflected).

We were able to add users to the group manually using the service user and Exchange Admin Center.

Input of failing step:
```
{
    "host": {
        "connectionReferenceName": "shared_office365groups",
        "operationId": "AddMemberToGroup"
    },
    "parameters": {
        "groupId": "-redacted-newly-created-group-",
        "userUpn": "-redacted-"
    }
}
```

Output of failing step:
```
{
    "statusCode": 403,
    "headers": {
        "Cache-Control": "no-cache",
        "Transfer-Encoding": "chunked",
        "Vary": "Accept-Encoding",
        "Strict-Transport-Security": "max-age=31536000",
        "request-id": "2292060e-5bd1-4784-94ad-9b5f7261e095",
        "client-request-id": "2292060e-5bd1-4784-94ad-9b5f7261e095",
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"Germany West Central\",\"Slice\":\"E\",\"Ring\":\"5\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"FR3PEPF00000165\"}}",
        "x-ms-resource-unit": "1",
        "Timing-Allow-Origin": "*",
        "x-ms-apihub-cached-response": "true",
        "x-ms-apihub-obo": "false",
        "Date": "Wed, 17 Jan 2024 10:05:27 GMT",
        "Content-Type": "application/json"
    },
    "body": {
        "error": {
            "code": "Authorization_RequestDenied",
            "message": "Insufficient privileges to complete the operation.",
            "innerError": {
                "date": "2024-01-17T10:05:27",
                "request-id": "2292060e-5bd1-4784-94ad-9b5f7261e095",
                "client-request-id": "2292060e-5bd1-4784-94ad-9b5f7261e095"
            }
        }
    }
}
```

### Expected Behavior

The flow should add the maker to the group.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin - Add Maker to Group

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

We're not sure what triggers the flow usually.

Re-submitting the failed flow reproduces the error.

### Anything else?

We also checked #6849 and #7138 .

AB#2060

**Comment by Jenefer-Monroe** [comment]
This appears to be another issue with the types of groups the connector can interact with. 
Here is what we know today:

- must be an email-enabled security group
- admin or service account running the flow needs to be an owner of the group.
- cannot be a group created in Exchange on-prem and synchronized to O365

Here are some other properties of our typical use case. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c2f52f16-0fdd-44b9-bf41-ccb68b4779d3)

Does any of that seem different than yours?

**Comment by uka-support** [comment]
Your screenshot shows the group as "Microsoft 365" group type, but you state that it needs to be an email enabled security group which is a different type of group.

Our group looks like this:

![image](https://github.com/microsoft/coe-starter-kit/assets/6216577/272dd56b-70f6-45cb-8472-3d7c49e3264b)

I also cannot edit it in Entry since we created it in Exchange Admin center.

**Comment by Jenefer-Monroe** [comment]
is it created in Exchange on prem? Unfortunately that is a known limitation of this connector.

**Comment by uka-support** [comment]
I tested using an Microsoft 365 group and it worked instantly (I resubmitted a failed flow - the user was added to the group).

I suppose, I should create new groups for the Admin and User persona too? That would be cumbersome I suppose.

The documentation definititely needs clarification. A "mail enabled security" group is a different group type than a "Microsoft 365" group - see here: https://docs.microsoft.com/en/microsoft-365/admin/create-groups/compare-groups

**Comment by Jenefer-Monroe** [comment]
oh i see, yes those options are diffferent looking that when you create in Azure. It would be confusing form there. 
I can add screenshots when we make that documentation update so its more clear. 

Yes Microsoft 365 groups is our recomendation (and from an Azure POV those are mail enabled and security enabled hence the confusion)

**Comment by uka-support** [comment]
Can we just create new groups for Admins and Users and re-run the setup wizard? It looks like not all the steps are executed if I run the setup wizard a second time.

Or do we need to wait for the next update?

**Comment by Jenefer-Monroe** [comment]
You can do that and new makers will get added to the new group, but we dont have a migration story so you would need to migrate the existing makers over. 
Sorry for the confusion.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Fadel1949** [comment]
@Jenefer-Monroe   
Hello, I have the same confusion. In summary, do we need to use M365 Group? If we create it through the Admin center, when trying to share an app, we cannot use the group add functionality if using M365 Group because app sharing only supports Security group and Enabled-email security group. So, I'm not sure, can you clarify which type we should use?

**Comment by uka-support** [comment]
It only worked for us when using M365 groups.
