### ISSUE TITLE
App Usage trend graph is misleading [CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by nvarsha23** [microsoft/coe-starter-kit#7476]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have installed October 2023 version of CoE starter kit in our tenant. We see that the "App Launch Trend" visual in "App Usage" report page is not showing entire data. Also, there is a information icon on this visual mentioning "Showing representative sample. Click to see details." We have last launched data till today but this visual is not showing data from December 2023. We feel this visual is not configured correctly and misleading the users.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

October 2023

### What method are you using to get inventory and telemetry?

None

AB#2061

**Comment by Jenefer-Monroe** [comment]
Hello. I am not seeing this behavior so can you please help with some more details? Screenshots are very helpful in sorting these out as well and please note that you need to be logged in to GitHub to share them, responding in email with pictures will not work.

First, which template are you using? BYODL_CoEDashboard_October2023 or Production_CoEDashboard_October2023
Second, can you please share a screenshot of where you are seeing this error? I;ve never seen such an error message

**Comment by nvarsha23** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/134045427/0a5167dd-6e6e-4a95-8385-0c5aa79acffa)
Please find attached image where graph is not showing the data however, the table is having the data. Also, we are using Production_CoEDashboard_October2023.

**Comment by Jenefer-Monroe** [comment]
OK thank you. Do you have some filters applied on the chart? I dont repro this. Although I do have some changes I will make to hte chart to make it nicer by using a hierarchy for date
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6951fb3d-82d2-48fc-ab58-aaa6c7047805)

**Comment by nvarsha23** [comment]
We have not modified filters or field configurations which was given out of the box. So could you please check with OOTB configurations? Also, we are having huge data and i am suspecting that compared to 2023, 2024 is having very minimal data and hence it is not showing in graph due to configurations. Kindly confirm.

**Comment by Jenefer-Monroe** [comment]
I dont repro but it might be due to that same issue that I resolved with the picture above. Can you please change yours to match and see if that resolves? 


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5c76aea4-fcab-4947-9242-facad6308248)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
