### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is app quarantine status updated in Power App table

### ISSUE THREAD

**Issue by bhavikj65** [microsoft/coe-starter-kit#7477]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I can see there are columns related to App Quarantine Status and Date and also the Power Platform Admin app has a view for Quarantined Apps, we recently quarantined some applications however I don't see the status updated in Power App table. 

Are we tracking app quarantine status ? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2062

**Comment by RahulBojji** [comment]
@bhavikj65 
Please check if these flows turned on or not

**Admin | Quarantine non-compliant apps**
**Admin | Set app quarantine status**. If not please turn on

**Comment by bhavikj65** [comment]
Thanks, these were off. I will explore what these flows do and enable them accordingly

**Comment by Jenefer-Monroe** [comment]
Please see also this issue which is being addressed for Feb 
https://github.com/microsoft/coe-starter-kit/issues/7314

**Comment by bhavikj65** [comment]
We cannot use the governance components as we have developed some governance rules for Power Apps and have build custom automations. 

Will the apps quarantined by our automations will also be marked as quarantined in admin_app table in the Feb release ?

**Comment by Jenefer-Monroe** [comment]
I'm not sure, I have not yet investigated that issue. Please monitor that issue and I"ll keep it up to date with notes

**Comment by Jenefer-Monroe** [comment]
Looks like that fix will not make it till March release. 
I'll go ahead and close this issue then, please do reach out again with any other concerns!
