### ISSUE TITLE
[CoE Starter Kit - QUESTION] About HELPER - Maker Check's Power Automate

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#7482]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

HELPER - Maker Checkにおいてadmin_makerにユーザーを追加していくフローだと認識していますがどのような条件で追加されているのでしょか
またこのフローの親はどのフローですか

HELPER - Regarding Maker Check, I understand that the flow is to add users to admin_maker, but under what conditions are they added?
Also, which flow is the parent of this flow?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024年1月

### What app or flow are you having the issue with?

HELPER - Maker Check

### What method are you using to get inventory and telemetry?

None

AB#2068

**Comment by RahulBojji** [comment]
@asuka1103131 Can you please add the description in English, it will be easier for us to follow

**Comment by asuka1103131** [comment]
@RahulBojji 
Added explanation in English.
I'm using a translation, so sorry if the language is weird.

**Comment by RahulBojji** [comment]
@asuka1103131 Thanks for updating the description. 

The **HELPER - Maker Check** flow is the main flow which adds new people to the Maker table.
It is called from the various inventory flows (ex: **Admin | Sync Template v4 (Flows)** and its helper **SYNC HELPER - Cloud Flows**)
Which themselves are triggered when the **Admin | Sync Template v3 (Driver)** inserts or updates an environment.
Please have a look at [this](https://github.com/microsoft/coe-starter-kit/issues/7234) for more information

**Comment by asuka1103131** [comment]
@RahulBojji 
Who will be added to the Maker table?
I'd like to test it, but I'm having trouble getting people added automatically.

**Comment by RahulBojji** [comment]
For example, if a user 'A' is the owner of the flow or the app, then A will be added as a maker in the maker table.
If we are creating a flow once the driver flow gathers the inventory and updates the environment table then **Admin | Sync Template v4 (Flows)** will trigger which internally calls **SYNC HELPER - Cloud Flows** which then calls Maker check flow for adding the maker

 We can try creating a dummy flow for testing this functionality.
Got to https://make.powerautomate.com/ -> choose the correct environment on the top right corner. -> Create-> instant cloud flow 

<img width="933" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/f1e541fe-5b9b-484f-b9ca-17bd4b66f294">

<img width="562" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/c3d81c9a-1b13-40cf-ad79-57c01e5deb03">

click on create
<img width="702" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/9acf5309-d2f2-41a5-ba92-c7675eb003ff">

<img width="719" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/55aba4d1-c89a-49ad-84e8-0b4dd8d7bb0b">

<img width="437" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/07b7c91a-610c-4029-bac3-4cad364188bc">

Click on Save. In the next run of inventory this flow will be created in the flow table and owner of the table will be added as Maker in the Maker table

**Comment by asuka1103131** [comment]
@RahulBojji 
Thank you very much. Understood.
Is there any way to prevent the flow from affecting the members registered to admin_maker?
I had a problem when all members were invited to the M365 group!

**Comment by RahulBojji** [comment]
Maker check doesn't invite them to the group it's the "**Add Maker to Group**" flow that does that. They are related because its typically Maker Check that adds then to the table and Add Member to Group which then responds to this add. so, you can turn off Add Member to Group instead if you don't want makers to get added into maker groups.

**Comment by asuka1103131** [comment]
@RahulBojji 
Thank you very much.
How do I turn off adding members to a group?

**Comment by RahulBojji** [comment]
@asuka1103131
Go to https://make.powerautomate.com/ -> solutions-> core components ->open the flow and click on Turn off.

<img width="617" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/da91a60c-1657-47e8-abfc-f740be2b8a4c">

**Comment by asuka1103131** [comment]
@RahulBojji 
Does turning off a flow affect other flows?
Example: Admin｜Sync Template v3 (Driver)

**Comment by RahulBojji** [comment]
@asuka1103131 It shouldn't affect any other flows as Add Maker to Group triggers only when a new record is inserted into Makers table

**Comment by asuka1103131** [comment]
@RahulBojji 
HELPER - Can Maker Check be turned off?

**Comment by RahulBojji** [comment]
@asuka1103131 I would advise not to turn off Maker check as its being called from various flows. Turning off Maker check will make other flows fail.

**Comment by asuka1103131** [comment]
@RahulBojji 
Thank you very much. I have resolved this matter and will close it.
