### ISSUE TITLE
[CoE Starter Kit - QUESTION] Make Users that are not Makers as the Flow Owners

### ISSUE THREAD

**Issue by Jakrina** [microsoft/coe-starter-kit#7483]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello. We have been experiencing a problem for some time. We are using the "Request Orphaned Objects Reassigned" flows (both Parent and Child) where the Managers are asked to take action on the orphaned items.

There are cases when they reach out to us providing a user who should be the new Owner of the items. In the case of Flows, we are usually using the "Manage Flow Permissions" app to both share the flow with the user and later make them the Owner.

But it fails in some situations (technically the Helper flow fails). After some investigation, we found out that it looks like we can not assign Users who are not Makers as the Owners. In other words - if the Manager provides a user who has not been using Power Platform before, and thus is not in the Makers table, it fails when we want to assign them as the Owner. And we have also tested it from Dataverse directly - Users who are not Makers (they are present in the Users table, but not in the Makers table) cannot be selected as the Derived Owners.

In a large organization, it is a problem as such requests arrive repeatedly. Is there a workaround for this? Or should we ask the managers to ensure that the person who they want to be the new owner, has definitely built something in Power Platform before that? The second option might decrease the response rate a lot.

Thank you in advance!

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

AB#2069

**Comment by Jenefer-Monroe** [comment]
Can you please let me know what version of core and gov you have installed? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Jakrina** [comment]
It is these versions:

![image](https://github.com/microsoft/coe-starter-kit/assets/98682417/30f4ee3a-3089-4bb4-bf87-2256b2dad888)

**Comment by Jenefer-Monroe** [comment]
Thank you. 
So I do not think the issue has to do with the user being in the Maker table already or not. 
The helper function we use first ensures the maker is in the maker and user tables as shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0b99d61e-8d38-45c0-b947-e3ee79c7bb57)

Are you able to repro this? If so can you open the run of HELPER - CloudFlowOperations which results? We can debug together.

**Comment by Jakrina** [comment]
Thank you! I just noticed there seemed to be some connection error. We updated the connection and now the Helper flow does not get triggered at all. All we get is this error message:
![image](https://github.com/microsoft/coe-starter-kit/assets/98682417/a39b4af4-3d0a-4239-930c-7722f6c5a34e)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
