### ISSUE TITLE
[CoE Starter Kit - BUG] Solution Upgrade fails

### ISSUE THREAD

**Issue by bhaski30** [microsoft/coe-starter-kit#7484]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am struggling to upgrade the Solution for Centre of Excellence CoE Starter Kit.  Solution import fails with error message [80040224] - A task was cancelled. 

Anyone any ideas please?
![CoE_Error](https://github.com/microsoft/coe-starter-kit/assets/156193348/f66b24a2-a221-47fa-b4c8-32e2a7c1d4d5)

### Expected Behavior

Expected behavior would be to uninstall the old version and install the new version

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Solution

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2071

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by bhaski30** [comment]
please find the screenshot.
![CoESolutions](https://github.com/microsoft/coe-starter-kit/assets/156193348/5dc8019e-3668-4f9c-96af-f055124df1ac)

**Comment by bhaski30** [comment]
Thank you, Jenefer. I tried multiple times and got the same error.
![1](https://github.com/microsoft/coe-starter-kit/assets/156193348/e5b250fc-5700-4978-845a-c0492572a656)
![2](https://github.com/microsoft/coe-starter-kit/assets/156193348/b0c4dd6d-b573-4aec-9ad9-e8366592da2e)

**Comment by Jenefer-Monroe** [comment]
OK that was a long attempt not short, so I would have expected to see an _upgrade in the solution list. Do you not have one of those? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4a96b5e7-d19a-4908-a3f2-4b5dcfb52f61)

**Comment by bhaski30** [comment]
I don't see _upgrade. I have upgraded the creator kit and tried to upgrade CoE starter kit without success.
![creatorkit](https://github.com/microsoft/coe-starter-kit/assets/156193348/c289611a-22eb-4612-bcb1-97a0565d4659)
![error](https://github.com/microsoft/coe-starter-kit/assets/156193348/d85a8695-ca8f-49d3-af2b-3dab89ab9c26)

**Comment by Jenefer-Monroe** [comment]
I'm sorry I'm really not sure. This is working for others and there just isnt any details in that failure to point us in the correct direction. 
Perhaps you can try an overwrite type upgrade

### How to do an overwrite upgrade in the classic UX:
 
Switch to classic
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/690cafcb-ade8-4571-81d5-df70f97f6266)

Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/433cd2d8-7e2a-4d35-a86e-cf569b7777f2)

Select Core > Next
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f232f4b5-783d-4d8c-af94-21fb6dfd91bf)

Next
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/39c84d9b-7ccf-4aff-8861-6c70ed7cb237)

Overwrite customizations > Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7b23463c-2361-4135-81a8-363a96ca23d5)

**Comment by bhaski30** [comment]
Unfortunately i got the same error message
![Capture](https://github.com/microsoft/coe-starter-kit/assets/156193348/bb9518e3-8754-4c5c-8369-e6d52c6915e4)

![MicrosoftTeams-image (7)](https://github.com/microsoft/coe-starter-kit/assets/156193348/372a04dd-a8bc-4029-8d53-971be0ffc60c)
![MicrosoftTeams-image (8)](https://github.com/microsoft/coe-starter-kit/assets/156193348/c5cea4dd-9d21-4141-873f-d45685a4129b)

**Comment by bhaski30** [comment]
There were no plug-ins created or used in the environment by us. I can also confirm that I clicked the Overwrite customization in the classic upgrade process.

**Comment by Jenefer-Monroe** [comment]
Sorry I just dont know how to help. There is no detail on what is failing. This is working for most people so there must be something specific in your envt, but without details I have no idea how to help you find the issue.

**Comment by Jenefer-Monroe** [comment]
I'm afraid without more detail I just don't know how else to point you to where to look.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
