### ISSUE TITLE
[CoE Starter Kit - BUG] HELPER - CloudFlowOperations flow fails

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#7487]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello!
We encountered the problem that our HELPER - CloudFlowOperations flow started to fail. 
This is the error message:
<img width="776" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/0907a5f0-f81f-4d70-ab44-c8d8d9b7db9f">
Strange is that in the "Error Details" field the error is described as "Action 'Get_user_photo_(V2)' failed ". however, seems that the problem is in the "Mark app owner in CoE"
<img width="441" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/769657bc-d98d-4a78-8b2f-9e8e6bec507c">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

HELPER - CloudFlowOperations 

### What method are you using to get inventory and telemetry?

None

AB#2074

**Comment by Jenefer-Monroe** [comment]
The error sounds like one of your connections broke / expired. Can you please check that? 
Here are some places to look for broken things:

On the connections page: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c38b1b1e-ba82-473e-b03d-5e36fe404183)

On the details page of the suspected flows (click the edit shown to see more):
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a2fd2408-a4e8-49fa-b85c-096037310b88)

On that same page in the Run only users list
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b65262ae-1535-408e-816f-4e9ed191836a)

**Comment by JanetK12** [comment]
Thank you for your answer @Jenefer-Monroe !
I added these two connections for these actions
<img width="353" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/f958b5a8-4891-4588-8cad-03c947f9f762">
But what I also noticed is that it is written that there is a problem with the flow's trigger
<img width="267" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/f85dcf87-d4d7-4e40-8a16-5e82b063d927">
I thought that the problem is because I saved the new connections, and tried to test the flow, but somehow it failed with this error
<img width="942" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/4335e124-a04a-4b22-9034-7112c312640e">
So I tried to delete all the connection that this flow used and recreate them again - but the problem still remains.
This is the trigger's error:
<img width="166" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/0f2d00be-c445-443f-8169-9a0afaa6332f">

**Comment by JanetK12** [comment]
@Jenefer-Monroe 
I am sorry, I think I managed to solve this issue! Thank you one more time!
