### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE Data not pulling in

### ISSUE THREAD

**Issue by pathikrawalapm** [microsoft/coe-starter-kit#7488]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have installed Power Platform CoE in the a new envuronments. We following https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup 

Now after  almost 5 days, we still do not see any data in the the "Power Platform Admin View" App.

I tried all the steps in here https://github.com/microsoft/coe-starter-kit/issues/2138
but we could not find any flow with name "Admin | Sync Template v3" or "Admin | Sync Template v4"

We do have other flows like "Admin | Sync Template v3 (Environment Properties)" etc.

We have following all the steps carefully.

### Expected Behavior

We should see all the data

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2.2

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

As above

### Anything else?

NA

AB#2075

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
