### ISSUE TITLE
[CoE Starter Kit - BUG] App Deep Dive Total Shared With All 0s

### ISSUE THREAD

**Issue by bleno123** [microsoft/coe-starter-kit#7490]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

On the App Deep Dive page of the Power BI Dashboard, "Total Shared With" is all 0s. However, if I drillthrough on a specific app to review app shares, I'll see the data there.

### Expected Behavior

I expect to see something besides 0s for some of the apps

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2077

**Comment by Jenefer-Monroe** [comment]
These fields are roll up fields and so for a new install they take a while to update. It’s typically a 12 hour wait after the inventory completes before you can expect to see these populate but the product itself is what determines how frequently and when to update these roll up fields.
You can force these to calculate. Please see the tip in this product team article on [Rollup columns](https://learn.microsoft.com/power-apps/developer/data-platform/calculated-rollup-attributes#rollup-columns)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d374b7dc-82e2-499d-8855-be81a70bdb98)

**Comment by bleno123** [comment]
Looks like several of my rollup jobs failed when I first installed the CoE. I resumed the one job for total shared with and the data is now pulling in. Thanks for your help.

**Comment by bleno123** [comment]
This can be closed. The information provided above solved the issue.

**Comment by Fadel1949** [comment]
@Jenefer-Monroe  Hello, I have the same problem, the total share is 0. I checked the data in the "power app user role" table and there is normal data in the Group size, but why is the total share 0? The solution is managed, and I cannot view the formula of the Column Rollup.

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/96f94826-9848-4131-9bdf-f256427c531f)
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/e90cf47f-1750-4f7d-b866-e0488d3d22dc)
