### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Check Deleted) - Erro

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#7492]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

hi jenefer

About the error Error #7348

Please, I updated CoE today with the most current version 4.22, but this error persists.

Do you know if you need to make any further configuration for this flow to work ?

![versão atual coe](https://github.com/microsoft/coe-starter-kit/assets/129080740/7b1b084a-26a2-49d5-bdfe-c68f0ebe3d6b)

![Erro após versão atual](https://github.com/microsoft/coe-starter-kit/assets/129080740/aa7051f1-faee-488c-aa5f-03c1b1840f33)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2079

**Comment by Jenefer-Monroe** [comment]
Hello. Yes you should opt in to the V4 flows for this area. 

Please go turn **_off_** this flow: CLEANUP - Admin | Sync Template v3 (Check Deleted)

And turn **_on_** these flows in the order shown:
CLEANUP HELPER - Check Deleted v4 (Ai Models)
CLEANUP HELPER - Check Deleted v4 (Business Process Flows)
CLEANUP HELPER - Check Deleted v4 (Canvas Apps)
CLEANUP HELPER - Check Deleted v4 (Cloud Flows)
CLEANUP HELPER - Check Deleted v4 (Desktop flows)
CLEANUP HELPER - Check Deleted v4 (Model Driven Apps)
CLEANUP HELPER - Check Deleted v4 (Portals)
CLEANUP HELPER - Check Deleted v4 (PVA)
CLEANUP HELPER - Check Deleted v4 (Solutions)
CLEANUP - Admin | Sync Template v4 (Check Deleted)


Please do let me know how this works for you!

**Comment by minobrega** [comment]
Hello Jenefer,

I enabled all flows as instructed and ran CLEANUP - Admin | Sync Template v4 (Check Deleted), presented the error as shown in the image below, but I'm running it again to test.

![ativado fluxos](https://github.com/microsoft/coe-starter-kit/assets/129080740/e5a53d64-3b8e-4250-9247-ee00c32cbb3b)

![erro após update](https://github.com/microsoft/coe-starter-kit/assets/129080740/c71a294f-849d-464d-8f1f-27e11da9cdaa)

**Comment by Jenefer-Monroe** [comment]
For this error:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/40f3c2ed-a821-4330-9ba5-d120d044887c)

You just need to rerun your **_Admin | Sync Template v3 CoE Solution Metadata_** flow.

**Comment by Jenefer-Monroe** [comment]
For this error
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5443690c-db4a-4bf8-853a-ee55fc81a4dd)

Please open the scope and see which child failed.

**Comment by minobrega** [comment]
Hello Jenefer,

When we open the scope, there is a message that failed, but all children were executed and the status code was 200

![Mensagen de erro 1](https://github.com/microsoft/coe-starter-kit/assets/129080740/1205e516-2f7f-4863-8e06-148af2694039)

**Comment by minobrega** [comment]
Hi Jenefer,

After the last tests, the flow ran without error as shown in the image below.

![Sem erro](https://github.com/microsoft/coe-starter-kit/assets/129080740/e73021ee-96e5-4b11-90d2-a7d7156abeb7)

The question is that these abandoned flows that were manually deleted after running the cleaning flow shouldn't they be removed from here?

![Ja foi excluido](https://github.com/microsoft/coe-starter-kit/assets/129080740/02a104c0-746a-4ba8-b9a4-63ccc64c3677)

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not following. Sounds like you have a new issue. 
This symbol is not one that we see in our app so I dont know what it means. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cf0d5214-b66a-4729-b1cd-8c695f7214aa)

Can you plesae clarify your current issue?

**Comment by minobrega** [comment]
Yes, disregard this symbol, we put it in the default environment so that employees do not use this environment. the problem is that these abandoned flows were deleted, and to update that they were deleted we run the flow: CLEANING - Admin | Sync Template v4 (Check Deleted) did not remove them from the flow tables, and they continue to appear here.

For example, this stream was deleted

![deletado](https://github.com/microsoft/coe-starter-kit/assets/129080740/30d08677-7de4-49e8-afc0-c64bd305b141)

Even after running the CLEANUP - Admin | Sync Template v4 (Check Deleted) the flow continues to appear in Power platform Admin View

![Fluxo não apagado](https://github.com/microsoft/coe-starter-kit/assets/129080740/9ede259d-b6a7-450d-89cc-abb85020ab9e)

**Comment by Jenefer-Monroe** [comment]
Oh I see, thank you. I think this may be as simple as the filters on that view.
You can edit the view and add a new filter to remove deleted ones. Does that fix it?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/81b007d6-2bad-4f74-b127-9b618af3bfed)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4f1ebfcd-fdb8-4b4e-bdac-1e4a8f85b0d2)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/23392279-f162-4249-b784-3f9c63c9d299)

**Comment by minobrega** [comment]
Hello Jennifer

That's right, it worked... thank you very much for your help and patience. :)
