### ISSUE TITLE
[CoE Starter Kit - QUESTION] does flows imported from another environment that is turned off not collected by the CoE flows?

### ISSUE THREAD

**Issue by limyandi** [microsoft/coe-starter-kit#7494]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

does flows imported from another environment that is turned off not collected by the CoE flows?
I have several flows that are exported from the 'DEV' environment and imported to 'PROD' environment.

These flows are by default turned off, and when I check in the CoE Power BI Report, the flow isn't actually included, but this is only for flows that are off. For flows that are turned on, it is there.

I just want to clarify if this is an expected behaviour of the CoE flows? Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2082

**Comment by Jenefer-Monroe** [comment]
Hello. Yes these are called "unpublished" in the terminology of Power Automate. 
Today these are not collected, as they are not returned by the product in the **_List Flows as Admin_** action. 
The product team is working on a change which will make these collected and the kit has done its prep work to be ready for that as well. 

Please see [Flows that have never been turned on](https://learn.microsoft.com/power-platform/guidance/coe/limitations#flows-that-have-never-been-turned-on)

**Comment by limyandi** [comment]
Thanks for the clarification @Jenefer-Monroe
