### ISSUE TITLE
[ALM Accelerator - QUESTION] Configure deployment settings: Group Teams - where are they saved?

### ISSUE THREAD

**Issue by FabianAckeret** [microsoft/coe-starter-kit#7495]
### What is your question?

Dear CoE team,

 I have been working on configuring deployment settings and encountered a challenge when attempting to share an app/flow with a group team. The issue arises as the list appears mostly empty, presumably due to the utilization of M365 groups within the group teams, as opposed to security groups.

Upon investigating the 'SearchDeploymentEnvironmentTeams' flow, it appears that only teams with teamtype 2 are returned, which I assume correspond to security groups. On the other hand, teamtype 3 seems to represent M365 groups.

Furthermore, when adding a group team under the **Group Teams** tab, I am unable to locate this team in the environment's teams-section (https://admin.powerplatform.microsoft.com/environments/[ENVID]/teams).

I have a few questions that I hope you can assist me with:

1. Is my assumption correct that only security groups connected to group teams are visible?
2. Can the 'SearchDeploymentEnvironmentTeams' flow be modified to also filter by teamtype 3, or would this potentially cause other issues?
3. Where are the group teams saved that are created under the **Group Teams** tab? I couldn't find them in any location.

I appreciate your time and assistance in addressing these queries.
Thank you in advance!

Cheers

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231012.1

AB#2083

**Comment by RajeevPentyala** [comment]
@FabianAckeret Please refer this feature #5965 which explains why only the security-enabled group can be chosen for sharing. Regarding your question 3, 'Group Team' which you add from deployment settings, gets created in the selected environment for configuration.

In the scenario below, the 'Group Team' gets created in the 'Validation' environment that you mapped in your deployment profile.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/5ce09c33-4490-447c-b925-773196c6d50b)

**Comment by RajeevPentyala** [comment]
@FabianAckeret The 'Team' gets created in Dataverse during the respective 'Deploy' pipeline runs. In your case, please verify the 'Team' creation after the 'deploy-test-{solution_name}' pipeline run.

**Comment by RajeevPentyala** [comment]
@FabianAckeret Closing this issue. Please let me know if you need further assistance.
