### ISSUE TITLE
[CoE Starter Kit BYODL - BUG] After recent update i see less number of flows under powerautomate tab in powerBI and it is missing information from few environments.But powerapps is showing proper data

### ISSUE THREAD

**Issue by jayakumarkgds** [microsoft/coe-starter-kit#7498]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After recent update i see less number of flows under powerautomate tab in powerBI and it is missing information from few environments.But powerapps is showing proper data

### Expected Behavior

Should return all cloud flows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2.2

### What app or flow are you having the issue with?

PowerPlatformAdminAnalytics-DF

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Sync the dataflows
Sync the powerBi Report

AB#2088

**Comment by Jenefer-Monroe** [comment]
Hello, if your Core version if 4.2.2, then you are on an old version of the kit (April 2023) so its difficult to assist with debugging. 
I do vaguely remember, due to the unusual number, that we shipped a bug there with the introduction of a new connector. 
Can you see if you have an unmanaged layer there?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/41687ca3-5cbe-4de4-af9b-49e522de8aca)

**Comment by Jenefer-Monroe** [comment]
Oh never mind I see you are on Data Export feature? If so you will need to upgrade to the latest version of the kit (Jan 2024). 
There were changes to the schema of the Data Export file which we had to adapt to.

**Comment by Jenefer-Monroe** [comment]
ok great thank you! 
Did you upload the new dataflow? The Jan PBI relies on this new Dataflow.
And if so, did you note the new Dataflow ID for the template file?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e6230995-9ce3-4249-bb0c-bde784152d76)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by jayakumarkgds** [comment]
> ok great thank you! Did you upload the new dataflow? The Jan PBI relies on this new Dataflow. And if so, did you note the new Dataflow ID for the template file? ![image](https://private-user-images.githubusercontent.com/89584709/298213889-e6230995-9ce3-4249-bb0c-bde784152d76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDgxNzEsIm5iZiI6MTcwNjUwNzg3MSwicGF0aCI6Ii84OTU4NDcwOS8yOTgyMTM4ODktZTYyMzA5OTUtOWNlMy00MjQ5LWJiMGMtYmRlNzg0MTUyZDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA1NTc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ODhhZWY3NTI3OTZmOTUwNTQ4NGI3ODQ2MzcxY2I4YWE4NGViZTNlZGEyM2E2N2M0NTYwOTE3YzIwZmRkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nL59b01FiDVMmmDox4jfOLurTLQ_NoKIvJ9Tc9IYmzg)

Yes dataflow is updated but still same bahaviour
