### ISSUE TITLE
[CoE Starter Kit - BUG] Azure Resource Manager related error trying to turn on some "Admin | Sync Template" cloud flows

### ISSUE THREAD

**Issue by rpothin** [microsoft/coe-starter-kit#7502]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

I am working on a fresh deployment of the latest version of the CoE Starter Kit (Core) in a new environment and got the following errors trying to turn on some cloud flows (example below):
- **Admin | Sync Template v4 (Apps)** ==> Flow server error returned with status code "InternalServerError" and details "{"error":{"code":"AzureResourceManagerServerError","message":"Encountered internal server error from Azure Resource Manager. The tracking Id is 'a59fc974-9ada-4bc5-b4f0-24f875482f34'."}}".
- **Admin | Sync Template v3 (Solutions)** ==> Flow client error returned with status code "NotFound" and details "{"error":{"code":"AzureResourceManagerRequestFailed","message":"Request to Azure Resource Manager failed with error: '{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Logic/workflows/aa0e7d12-e5d5-91c9-2e2b-82f644e50bfb' under resource group '7BEF27DFBCED41B2957745C46604941E-1514944DB768ED63B435F969F77698F6-ENV' was not found. For more details please go to [https://aka.ms/ARMResourceNotFoundFix"}}'."}}".](https://aka.ms/ARMResourceNotFoundFix%22%7D%7D'.%22%7D%7D%22.)

The owner of these cloud flows (like for all the cloud flows of the solution even the ones turned on) is the service principal used to automatically deploy the solution.
But at least in these 2 cloud flows presented above, the "Tenant pool usage" (it is set to "Disabled") option is displayed on the main page.

Thank you in advance for your help and have a great day.
Regards,
Raphael

### Expected Behavior

I would like to be able to turn on all the cloud flows I want to use without an error - at least not one mentioning Azure Resource Manager or not one I cannot resolve myself (environment variable value missing...)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Apps), Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the main page of one of the listed cloud flows
2. Click on "Turn on"

After that you should get an error.

### Anything else?

Perhaps it could have an impact so I want to mention it: the deployment of the solution and the activation of the cloud is automated in an Azure DevOps pipeline.
So, even if I can now reproduce the error from the Power Automate portal, some tries have been done from the pipeline at first.

AB#2092

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately you can't use an app registration or service principle today to use the CoE kit, as not all of the connectors we use support authentication with a service principle.

Typically, customers use a named account with a "service name" to install the CoE kit - e.g. "CoE Admin". It's the same as a named account, but it's not tied to a "real" employee. The benefit is that if the employee leaves the organization or changes jobs/moves to a different department, the "named service account" can be handed over easily and you don't have to go through the trouble of changing ownership on all resources etc.

**Comment by rpothin** [comment]
Hey @Jenefer-Monroe,

I hope you are doing well.

I am sorry I forgot to add details regarding this part 😅

The cloud flows are owned by a service principal currently - due to the fact that the solution has been imported from an Azure DevOps pipeline - but all the connections configured in the connection references have been created with a user "service" account and then these connections have been shared with the service principal who owned the cloud flows (the one used for the deployment).

But perhaps even this approach does not work with all the connectors. Are you aware of such limitations?
As a reminder most cloud flows - with the configuration described above - from the solution have been turned on without error.

Thank you again for your help and have a great weekend.
Raphael

**Comment by Jenefer-Monroe** [comment]
oh I see. Yes I believe it is the connection owner that matters. I've not tested that configuration but just thinking through it, that should be fine. 

I've never seen this error, nor do I know what you mean by this: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/735079e5-9761-4005-88c8-1f8f7dc364f2)

Can you please share a screenshot so I can understand where you are seeing this?

**Comment by rpothin** [comment]
Hi @Jenefer-Monroe,

I hope you are doing well.

First, the "Tenant pool capacity" setting is sometimes displayed on the home page of a cloud flow - and when it is the case, it can be updated from the "Edit / Details" right pane opened from the cloud flow home page.
This option is described here if I am not wrong: https://learn.microsoft.com/en-us/power-automate/service-principal-support#tenant-pool

You will find below a few screenshots of the situation I am currently in:
- A cloud flow turned on as expected but with the "Tenant pool capacity" setting not "visible"

![image](https://github.com/microsoft/coe-starter-kit/assets/23240245/7a8abec4-59a0-4364-927f-4c23282582ab)

- **Admin | Sync Template v4 (Apps)** cloud flow with a part of the error message and the "Tenant pool capacity" setting "visible"

![image](https://github.com/microsoft/coe-starter-kit/assets/23240245/d345640b-d4d1-490c-b814-6570c0dcb3e9)

- **Admin | Sync Template v3 (Solutions)** cloud flow with a part of the error message and the "Tenant pool capacity" setting "visible"

![image](https://github.com/microsoft/coe-starter-kit/assets/23240245/46ca9a9c-b479-4854-bd7e-f4ef9fe9182d)

I hope these elements will help you in the analysis.
Have a great day and thank you for your help.
Raphael

**Comment by rpothin** [comment]
@Jenefer-Monroe,

Thank you for sharing this.

I came across this information while creating a support request for this issue.

Unfortunately, has you can see in the previous screenshots, the "Tenant pool capacity" setting - when displayed on the cloud flow home page - is already set to "Disabled".
Moreover, the error message presented in the article is pretty different from the ones I am getting.

Anyway, I tried to go through an "Enable" then "Disable" to be sure "Tenant pool capacity" would be correctly disabled and got the following error message: `Erreur: "Flow client error returned with status code "BadRequest" and details "{"error":{"code":"TenantPoolNotAllowed","message":"Cannot enable tenant pool for flow '375b22b2-daf7-bc39-76ba-92dc5c1e7e1d', the flow must be owned by an application user and in dynammics app context."}}".`
Just to confirm, for the **Admin | Sync Template v4 (Apps)** cloud flow I have the **Power Platform Admin View** app referenced in the **Associated Apps**.

Hope these new details will help find a solution.
Have a great day.
Raphael

**Comment by Jenefer-Monroe** [comment]
Yes all the inventory flows should be attributed to this app as its what displays the findings. And I do see this as the case for both of those apps in current bits.
Sounds like there is an issue with that feature, unfortunately you'll probably have to create a support ticket.

**Comment by rpothin** [comment]
Hey @Jenefer-Monroe,

Thank you for your help with this.
I had already started a thread with Microsoft support through a ticket about this but decided to give it a try here too.

I will then continue the investigation with Microsoft support and will try to put an update here if we find something relevant that could help others.

Have a great day.
Raphael
