### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to hide certain environments from the Power BI Dashboard view or inventory

### ISSUE THREAD

**Issue by Sinder088** [microsoft/coe-starter-kit#7503]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

There are some environments, like the one where i installed COE Toolkit, which i don't want to display in the Power BI Dashboard. IS there a way to disable or hide these environments? 

I tried to turned on the "Excuse from Inventory" but still the next day the report is still showing these.

Is this possible? Any Tips?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2093

**Comment by Jenefer-Monroe** [comment]
Hello. The Excuse from Inventory flag works in conjunction with an environment variable. 
Please see [Setting up CoE for a subset of environments](https://learn.microsoft.com/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments). 
If you have already used this env var, perhaps some of the flows ended up with a cached version of the env vars value. 
You can see what flows depend on the env var by going to the default solutions env var list and looking at the env vars dependencies
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d0f88362-4063-4276-b8d4-f429772f559f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/23225365-a37e-4b03-aa45-a74b340b3313)

Once you reset the flows, run the **_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_** flow as it has a section in which it cleans up objects in envts excused from inventory.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/75e33ab1-2f42-4c5e-8afb-4c908310fd44)

**Comment by Sinder088** [comment]
Thanks so much for the information. This definitely achieved what i wanted but seems to have created an unwanted knock on effect. I do not want to COE Toolkit components in the inventory of the Dashboard, so i marked the COE environment as "Exclude from Inventory". But now i see that all the apps i had made available in the App catalog are no longer appearing. 

Is it that you cannot have one without the other or is there something else i can configure to fix this?

**Comment by Jenefer-Monroe** [comment]
That's correct. You are saying you want something in the inventory or not. And if something is in the inventory you can decide to promote it in the app catalog. 

Unfortunately its a binary thing. 

I think otherwise you will need to just include everything in inventory and create a filter in the reports to target the things you are interested in monitoring. 

Hope that helps! Please do let me know.
