### ISSUE TITLE
Unble to Turn on flow

### ISSUE THREAD

**Issue by mvigneshwaran1010** [microsoft/coe-starter-kit#7505]
Hello Team,

I'm trying to configure audit log unable to turn on the flow. We are referring below articles to enabling this , getting below error.

Flow Name : Flow
Admin | Audit Logs | Office 365 Management API Subscription

Reference URL : https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

AB#2102

**Comment by RahulBojji** [comment]
@mvigneshwaran1010 
Can you please share the error you are facing while turning on the flow ??

**Comment by mvigneshwaran1010** [comment]
Hello Rahul,

Please find the error message below.




Thanks & Regards

Vigneshwaran.M

SharePoint Admin

Data & Information Management

Information Technology

Mobile : +91- 9788991307

***@***.******@***.***>

[Cenovus Energy]

________________________________

**Comment by mvigneshwaran1010** [comment]
++ Adding Hasan


Thanks & Regards

Vigneshwaran.M

SharePoint Admin

Data & Information Management

Information Technology

Mobile : +91- 9788991307

***@***.******@***.***>

[Cenovus Energy]

________________________________

**Comment by Jenefer-Monroe** [comment]
Please note that screenshots do not come through if you respond in email, you need to log in to GitHub to share them.

**Comment by mvigneshwaran1010** [comment]
![error](https://github.com/microsoft/coe-starter-kit/assets/155989298/7c6708f7-469f-43b6-a206-c2112ecae8e4)

**Comment by RahulBojji** [comment]
@mvigneshwaran1010 
As per [documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables) we need to fill the above environment variable before turning the flow.

<img width="727" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/c9b1d050-fb8f-4fc1-809f-a99b1f6cfb44">

You will not be able to update the environment variable from Core Components solution, you can open default solution and open the above environment variable and update the current value. Then try to turn on the flow

Hope this helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
