### ISSUE TITLE
[CoE Starter Kit - QUESTION] Turn off Flows as Admin - Not working?

### ISSUE THREAD

**Issue by SBadwal17** [microsoft/coe-starter-kit#7506]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

As part of our governance we mandate a set criteria for any Flows in Production. If you do not follow this criteria I wish to automatically turn off the flow. However when I use the Turn Off Flow action in Power Automate this fails with error

``You are not permitted to make flows in this 'xxxxxx-xxxx-xxxxx-xxxxx'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions.``

Am I using the wrong action? If so what is the correct way of doing this. This used to work previously so not sure what has changed?

Thanks in advance!

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#2097

**Comment by RahulBojji** [comment]
@SBadwal17
Turning off the flow have nothing to do with sending emails. Please check if you have any processes built to send emails when flow is turned off. If nothing is present, please let us know with the screenshots. Most probably, it has to do with flow sending emails on behalf of a user who doesn't sufficient permissions to send email.

**Comment by SBadwal17** [comment]
Apologies, I pasted the wrong error message! The error im receiving is as follows;

`You are not permitted to make flows in this 'xxxxxx-xxxx-xxxxx-xxxxx'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions.`

**Comment by RahulBojji** [comment]
The user with which you are trying to create flows doesn't have permissions to create a flow. The user must have a valid power automate license and some escalated privileges to create and save flows. For example, we advise users having Power Platform Admin Role permanently and directly assigned. This will in turn give them sys admin access to the environment and so you would not see that error.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
