### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot turn on Admin | Sync Template v3

### ISSUE THREAD

**Issue by VeryAccount** [microsoft/coe-starter-kit#7508]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello team,

I have encountered an unfortunate issue where I am unable to turn on Admin | Sync Template v3.
I have updated environment variables, started a subscription to audit log content, then turned on the flows as per guide. (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables)

P.s. All other related Sync Template V3 flows are turned on.
![error](https://github.com/microsoft/coe-starter-kit/assets/153821429/3547d175-c672-4d92-b27b-414fcdf21b74)

Please see the error below:

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'WorkflowOperationParametersExtraParameter' and message 'The API operation does not contain a definition for parameter 'item/admin_haspcfenabled'.'."}}".

Could you advise what could be causing the inability to turn on the flows?

Best regards,

Žilvinas Predkus

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Enter CoE Core Components 
2. Click on Cloud flows
3. Select Admin | Sync Template v3
4. Turn on the flow and receive the error

AB#2100

**Comment by RahulBojji** [comment]
@VeryAccount   Can you please share screenshot of the list of solutions you have installed in your environment just like below. Please make sure you are expanding the highlighted columns.

<img width="791" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/8d190ad7-9014-4d9c-95ea-b201fc9c73e3">

**Comment by VeryAccount** [comment]
Hi Rahul,

Thank you for such a quick response. Please see the requested screenshot below, please let me know if anything else would be needed.

![Screenshot_1](https://github.com/microsoft/coe-starter-kit/assets/153821429/976b505c-9e50-4bb7-9bc5-0f7e4f6101e7)

**Comment by RahulBojji** [comment]
Can you please check the below points?
1. Check if the flow has any unmanaged layers. If yes, remove it and then try to turn it on
2. As per this #5853 that field was removed completely in the previous releases. Check if the field still exists in the environment table and if any instances its being updated in the flow.

**Comment by VeryAccount** [comment]
Thank you. I have indeed found hasPcfEnabled field in the flow. 
![Screenshot_2](https://github.com/microsoft/coe-starter-kit/assets/153821429/08f9eb9c-a6a1-4884-8b1e-5df14c8f82b4)

Could you confirm if deleting this whole field is an okay decision to make?

Best regards,

Žilvinas

**Comment by VeryAccount** [comment]
Hey there,

The issue was related to an unmanaged layer, thank you again.

Best regards,

Žilvinas
