### ISSUE TITLE
[CoE Starter Kit - QUESTION] Number of Flows column blank in Maker table

### ISSUE THREAD

**Issue by blanghorst** [microsoft/coe-starter-kit#7509]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, I found an issue with a recent install and was hoping someone can point me in the right direction, as I've not encountered this issue before.  If I launch the Power Platform Admin View app, the All Makers - Flow Makers dashboard shows 0 workflows for all users:

![image](https://github.com/microsoft/coe-starter-kit/assets/18179178/7084cc46-caf0-4aa9-a1fd-70a8039b4ca1)

I reviewed the Makers table and sure enough, the "Number of Flows" column has 0 for all users:

![image](https://github.com/microsoft/coe-starter-kit/assets/18179178/292455c7-cc08-4b99-803f-81557676af15)

The Flows are successfully listed elsewhere in the app, such as the "Flows" section on the main dashboard page:

![image](https://github.com/microsoft/coe-starter-kit/assets/18179178/1c5b0c25-6c91-433f-a523-f2d8bfc4b86a)

Would someone be able to shed some light on which process populates the Flow column?  I've started going through the workflows to find it but hope someone can give me more information.  I've done the install many times and this is the first time I've seen this particular issue.  Thanks for any help!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Core 4.17, downloaded December 2023

### What app or flow are you having the issue with?

Unknown 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2103

**Comment by Jenefer-Monroe** [comment]
These fields are roll up fields and so for a new install they take a while to update. It’s typically a 12 hour wait after the inventory completes before you can expect to see these populate but the product itself is what determines how frequently and when to update these roll up fields.

You can force these to calculate sooner, and you can also go look at them to make sure they didnt get turned off somehow. 

Please see the tip in this product team article on [Rollup columns](https://learn.microsoft.com/power-apps/developer/data-platform/calculated-rollup-attributes#rollup-columns)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d374b7dc-82e2-499d-8855-be81a70bdb98)

**Comment by blanghorst** [comment]
Thank you so much Jennifer.  I reran that job and now the Flows are populated!  The issue was that it had errored out in mid-December due to the servers being "too busy."

**Comment by Jenefer-Monroe** [comment]
thank you for following up and letting me know!
