### ISSUE TITLE
[CoE Starter Kit - BUG] Questions on customizing mail

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#7510]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello all,

For the OWNER DOES NOT EXIST. APPROVAL SENT TO ADMIN. email that is sent to Admin.
The email content:

OWNER DOES NOT EXIST. APPROVAL SENT TO ADMIN.

You own an app that has not been modified or launched recently.
We want to make sure it is still useful, as if it is not then we would like to remove it to keep our Power Platform tenant tidy.

Please confirm this app is no longer being used and can be deleted by approving this task; or provide a business justification if you reject.

** PLEASE NOTE: **

If you select approve and want a copy as a backup, please create one manually as your app will be deleted from the tenant soon.
If you select approve and do NOT want a copy as a backup, consider deleting manually to avoid receiving a reminder to backup.
If you select reject, consider performing a re-save, to avoid receiving this email again in another month.

Questions:
1. Can this email be sent to its manager and cc: CoE Admin at the same time? 
2. Clarify: _"If you select approve and want a copy as a backup, please create one manually as your app will be deleted from the tenant soon."_ Once it is approved to be deleted, I assume I will delete it automatically.  I don't want to back up or delete them manually. How long do the apps get deleted from the environment once Admin approves the apps to be deleted?  can we adjust the delete period?
3.  Can we change/modify the content of this flow email?

Thank you so much.

### Expected Behavior

Verify and confirm questions.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

### What method are you using to get inventory and telemetry?

None

AB#2104

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by RyanCloud8888** [comment]
Thank you, Jenefer.
