### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard: "Run Setup Flows" has duplicate entries

### ISSUE THREAD

**Issue by russrimm** [microsoft/coe-starter-kit#7512]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

During the Setup Wizard on the "Run setup flows" step, the Admin | Sync Template v3 (Connectors) and Admin | Sync Template v3 Configure Emails flows appear twice.  One of each of the duplicated flows completes and the other does not, therefore you cannot click "Next".
![image](https://github.com/microsoft/coe-starter-kit/assets/10841574/d05475e6-8825-4813-890e-44f6a9151aac)

### Expected Behavior

Only 3 flows show in the "Run setup flows" action and all 3 flows complete.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Setup Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Run the Setup Wizard
2. Next until you get to the "Run setup flows" step

AB#2106

**Comment by Jenefer-Monroe** [comment]
This happens once in a while, the logic here is really quite difficult believe it or not. 
If you wait until the flows complete and then refresh the app you should be unblocked.

**Comment by russrimm** [comment]
OK what happened was we waited a while and kept re-launching and the wizard just kept showing everything was complete except the duplicates so we ended up just turning all the flows on manually as none were turned on.

**Comment by Jenefer-Monroe** [comment]
Thank you. Sorry about that. The page may be able to be simplified once flow runs are available in Dataverse at the end of the month.

**Comment by russrimm** [comment]
No worries!  So interestingly enough, the flows that it's showing two of actually both exist - so there's actually two flows for Admin | Sync Template v3 (Connectors), and two for Admin | Sync Template v3 Configure Emails when looking in cloud flows.  So it's not just an anomaly in the setup wizard, there's actually two of each of those flows in the environment.

**Comment by Jenefer-Monroe** [comment]
Did you have an upgrade failure? Can you share a screenshot showing your solutions like this? It should indicate if you have an _upgrade in there. 
Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by russrimm** [comment]
Hi Jenefer, it wasn't actually an upgrade, it was a fresh install in a freshly created environment.  Will get the screenshot to you shortly.

**Comment by Jenefer-Monroe** [comment]
oh ok if it wasnt an upgrade then thats not it. 
Hopefully we can make this logic simpler when we get flow runs then.
