### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Starter Kit reports that it is on the current version but flags warning that it is out of date.

### ISSUE THREAD

**Issue by tdryer-ukhs** [microsoft/coe-starter-kit#7513]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The COE Admin Command Center shows that our CoE Starter Kit is on the current version (4.22 - Jan 2024) but flags a yellow warning of "Your CoE Starter Kit solution was installed on Dec 2022. The latest version was released on Jan 2024. Please download and install the latest version."
Prior version was 4.2 As this is more than three months behind I performed an overwrite upgrade via classic UX per the instructions here: https://github.com/microsoft/coe-starter-kit/issues/5064#issuecomment-1479582662

### Expected Behavior

If the application is really on version 4.22 this warning flag should not be present.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

COE Admin Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open production environment.
2. Import CoE Core components 4.22 zip file.
3. Run COE Setup & Upgrade Wizard.
4. Open COE Admin Command Center 

### Anything else?

![Issue-screenshot](https://github.com/microsoft/coe-starter-kit/assets/153751982/2922558b-cdf2-406e-855f-5258acf12a21)

AB#2107

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for the starter kit team
