### ISSUE TITLE
[CoE Starter Kit - QUESTION] How and When or in What Flow is the DLP evaluation for apps being done and updated in the app properties that get retrieved by the Get App as Admin action?

### ISSUE THREAD

**Issue by Secretss7** [microsoft/coe-starter-kit#7514]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What I know
The **Get App As Admin** action in Power Automate retrieves app metadata/properties. Among these properties is
`outputs('Get_App_as_Admin')?['body/properties/executionRestrictions/dataLossPreventionEvaluationResult/status']`
and 4 others for lastEvaluationDate, violations, violationsByPolicy, violationErrorMessage.

The **Sync Helper - Apps** child flow is triggered daily to write from those above properties into relevant fields in the inventory records in the Power Apps table.

### What I want to know
How, when, and what flow (if any) updates the above app metadata/properties that the **Get App As Admin** action retrieves?

### My problem
We have apps with lastEvaluationDate that don't seem to coincide with any pattern. 

1. For some apps it's stuck on the app creation date from X years ago, even though the app has been modified since. 
2. For some apps it's stuck on some other date that isn't app creation nor app last modified nor initial full sync when CoE was installed, and is Y years ago. 
3. For some apps in a particular environment with a DLP policy applied, it's stuck on some date Z years ago even though the DLP policy was applied in Dec 2023.
4. For some apps it's updated recently this year but none on the same date, so it's doesn't look like there's a scheduled flow that runs through those apps to update them together.

![image](https://github.com/microsoft/coe-starter-kit/assets/37102423/f189a498-64a1-4e86-9fbc-0467a63c9237)

Is an evaluation being **secretly** done all the time but the _lastEvaluationDate_ is being conditionally updated? Is _lastEvaluationDate_ only updated if the _status_ changes? That is not giving confidence. "LAST evaluation date" very explicitly implies that that date was the last time an evaluation was done and that no further evaluations have been done since then. So if it was last done in 2022 but I've updated a policy in 2023, I cannot trust the _status_ value if it doesn't come with an assurance that a new evaluation had been done after the policy was applied. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15, 4.16, 4.17

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2108

**Comment by Jenefer-Monroe** [comment]
We look for changes in the DLP Status and error message in this flow here and inventory the app if those have changed.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/923dc6c4-a87c-499c-8186-93bf80c6dd32)

We explicitly decided not to do this for evaluation date as this changes so frequently you would end up inventorying apps most days, and that is an API hit that typically induces throttling. 

So you will not expect this date to change in the kit unless the DLP Status or DLP error message have changed.

Hope that makes sense.

**Comment by Secretss7** [comment]
Thank you! That satisfies my curiosity.
