### ISSUE TITLE
[ALM Accelerator - QUESTION] Deployment Settings - Flow overwritting

### ISSUE THREAD

**Issue by AdrianPPopa** [microsoft/coe-starter-kit#7517]
### What is your question?

Hi Team,

Part of the environment strategy, we are using isolated Dev environments to facilitate the delivery of features per developer. For branching strategy, we have a solution branch and feature branches created from the solution branch.

As a way of working, the developers start by importing the latest version of the solution from the solution branch into their dev environment. Afterwards, the developers commit their changes using ALM Accelerator by creating a new branch based on solution branch. 

We encountered a situation where 2 developers started the work simultaneously on Dev1 and Dev2. Each developer, besides other changes, added one new flow.

First developer was able to commit their changes into their feature branch then complete a pull request to solution branch. All good, changes were deployed into Validation environment and same build was further deployed into Test environment.

Here is where the issue starts. The second developer committed the changes from their environment into a new branch created from the solution branch that already had the updates made by the first developer then tried to complete a pull request. What happened is that the workflow created by first developer was replaced in the deployment configuration file and not added separately. Also, other solution files related to the workflow were removed. As a result, the second pull request removed all changes made by first developer.

Not sure if I'm missing a step here somewhere regarding your recommended environment/deployment strategy. When doing a pull request I would expect to see conflicts if the second developer removed files/updates that were added by the first developer but this did not happen.

Keeping the isolated dev environment up to date by regularly importing as unmanaged the latest solution version from solution branch does not seem to work either. As it might just remove their work in progress.

Any suggestions here?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20231012.1

AB#2111

**Comment by v-bjaiswal** [comment]
Hi @AdrianPPopa , we recommend following below guidelines for branching strategies. 

https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/branching-environment-strategy

**Comment by v-bjaiswal** [comment]
Marking this as close. Please create another ticket if you are still facing issue. Thank you
