### ISSUE TITLE
[ALM Accelerator - BUG]: Build silently fails to share canvas app

### ISSUE THREAD

**Issue by sefa-phaag** [microsoft/coe-starter-kit#7519]
### Describe the issue

Due to IT policy, we are unable to grant Power App Management permissions to our ALM Accelerator app registration as documented [here](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#give-power-app-management-permission-to-your-app-registration). First, that documentation only states that if the permission isn't added, "_certain capabilities_ don't work in the ALM Accelerator pipelines," but not which ones. It would probably be good to incorporate the content of [this page](https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceALMAccelerator/PREVIEW.md) into that documentation. Regardless, the actual issue is that the share request (via Set-AdminPowerAppRoleAssignment) fails, but the task seems to believe it completed successfully.

### Expected Behavior

If the share request fails, the build pipeline should fail.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

November 2023

### Steps To Reproduce

1. Do not make the app registration a Power Platform admin via New-PowerAppManagmentApp.
2. Configure Deployment Settings to share a canvas app in a downstream environment.
3. Deploy the solution to a downstream environment.
4. Observe that the build succeeded even though the app is not shared with the target security group.

### Anything else?

Here is the ouput of the Share Canvas App with AAD Group step. You can see that the Code for the HttpWebResponse was Forbidden.

```PowerShell
Starting: Share Canvas App with AAD Group
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.232.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\4e5ee2b7-85ad-4475-a77c-4a24ac49c1fb.ps1'"
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.AuthModule' include unapproved verbs 
that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again
 with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include 
unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the 
Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
AppId - [redacted] and UniqueCanvasAppId - [redacted]
Command Unique Id- Set-AdminPowerAppRoleAssignment -PrincipalType Group -PrincipalObjectId [redacted] -RoleName CanView -AppName [redacted] -EnvironmentName [redacted]


Code        : Forbidden
Description : Forbidden
Headers     : {Transfer-Encoding, Vary, Strict-Transport-Security, x-ms-islandgateway...}
Error       : 
Errors      : 
Internal    : System.Net.HttpWebResponse



Finishing: Share Canvas App with AAD Group
```

AB#2113

**Comment by v-bjaiswal** [comment]
Hi @sefa-phaag ,Thanks for reporting this issue. We will fix this issue by next release.
