### ISSUE TITLE
Notification by mail of the flows and apps orphans.

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#752]
Hi,
it would helpful that the flows "CLEANUP - Admin | Sync Template v3 (Orphaned Makers)" sends a mail to the Admin mail with a resume of the flows and apps orphans.
Thanks.

**Comment by JeneferM-MSFT** [comment]
The work in #731 sends some such lists
- to the admin email it sends the list of orphaned objects which have no manager to clean
-  to each former manager with orphaned objects it sends a list for them to clean. 

Shipping with August.
