### ISSUE TITLE
[CoE Starter Kit - BUG] Number of apps and flows showing incorrect against each connector

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#7523]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi @Jenefer-Monroe ,

Number of apps and flows associated with the connector table showing incorrect values. 

Admin App

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/5f8b2555-6b18-41b8-9151-1ccc298a551a)

PBI

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/d8c51fe3-ff67-44c2-8363-ad5301b69faa)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Power Platform Admin view

### What method are you using to get inventory and telemetry?

Data Export

AB#2116

**Comment by Jenefer-Monroe** [comment]
If you are using Data Export then this view will not work for you. We are waiting for the product to go to GA before we reinvest in that view.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2259da93-6635-497e-b821-40a5b8f84633)

This view should work though, did you use the BYODL_CoEDashboard_January2024 template file? 
And did you note that we have a new Dataflow for you to upload? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/98d684fc-6133-4864-9497-ae3ff7ac2a3c)

I did fix something there for the Feb release: https://github.com/microsoft/coe-starter-kit/issues/7389
That could be what you are seeing there.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for the starter kit team
