### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (BYODL App Properties) throttle issue

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#7525]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi @Jenefer-Monroe ,

We are getting throttle issue while getting the apps from evns.

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/285b906d-f5cf-41f4-891e-cd1b0117a1cf)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Sync Template v4 (BYODL App Properties)

### What method are you using to get inventory and telemetry?

Data Export

AB#2118

**Comment by Jenefer-Monroe** [comment]
Will put to the next month to consider. I'm not sure what we could do here, perhaps add a delay so not all the envts run at once? 
Will think it through.

**Comment by Jenefer-Monroe** [comment]
Added a delay
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6f56fc28-3262-4292-9f14-612c6c603cb4)
