### ISSUE TITLE
[CoE Starter Kit - QUESTION] HTTP with Microsoft Entra ID Graph scopes required permissions. - use preauthorized

### ISSUE THREAD

**Issue by MaciejFrydrychTS** [microsoft/coe-starter-kit#7527]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi i haven't found clear information about this in the documentation. 

CoE Kit uses "HTTP with Entra ID" connector to call MS Graph. 

![coe_kit_graph](https://github.com/microsoft/coe-starter-kit/assets/156932251/d73c5497-b987-4030-88ea-da5a31427bb7)

For what elements of CoE Kit this connector is required ? 

In the configuration page for this connector "HTTP with Entra ID there is this information. 

![coe_graph_scopes](https://github.com/microsoft/coe-starter-kit/assets/156932251/65cc575a-8ac1-4bf0-954f-1ae97c3cf018)

What scopes are required to be selected for this Graph app, for the connector to be working as expected. 

Regards 
Mathias 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

January 2024

### What app or flow are you having the issue with?

Setting up new CoE Kit.

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2122

**Comment by Jenefer-Monroe** [comment]
Its the preauthorized one that you use. Sorry the documentation missed that when they renamed the connector we missed to add that. 
Marked as a documentation bug
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9ad7b935-5a22-4b87-8e3c-ee41f1f3be28)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fc22a09b-962e-47d1-b10d-5a187a986e59)

**Comment by MaciejFrydrychTS** [comment]
Hi @Jenefer-Monroe Thank you for a such a fast response and clarification, i'll will try to use preauthorized connector.

**Comment by itebet** [comment]
Damn! I lost weeks of work on that due the complexity of installing the connector you indicate on your documentation :

1. Download the ps1 script
2. Installing Power Shell 7
3. Execute that script by a Global Administrator 
4. Try to figure out the required scopes on that huge list

All those actions required a lot of time on my hyper-restrictive banking sector. Can you please modify your doc to avoid people loosing their time trying to install a wrong connector? 
I really start to think that CoE installation was a real nightmare.
