### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Sync Log - Why do some environments have no app launches?

### ISSUE THREAD

**Issue by uzma-fis** [microsoft/coe-starter-kit#7528]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi there

I seem to get really good data from a default environment that we all use. But just noticed provisioned environments are not picking up canvas app launches. Most likely a permission issue. The account we are using is a PBI Admin/Service Admin and everything you can think of. Not sure why this is happening and looks like any provisioned environments are not being scanned

Any advise?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Nov 2023

### What app or flow are you having the issue with?

Audit Sync Log v2

### What method are you using to get inventory and telemetry?

None

AB#2123

**Comment by uzma-fis** [comment]
Additional notes, I saw that other environments are being scanned aokay, just wondering why this could be happening. What access should this flow have to apps?

**Comment by Jenefer-Monroe** [comment]
There are no per environment permissions on the audit log records. 
Are the apps in inventory and just not showing their launches? 
Have you tested by launching one and then waiting a few hours to see if it shows up?

**Comment by Jenefer-Monroe** [comment]
Sorry my question is, does the app show up in the inventory and just not as having a last launched?
And have you tried launching it yourself?

**Comment by uzma-fis** [comment]
Hi there, app is in the inventory and has no last launched date. I can confirm that the audit log is working okay and have latest app launches for many, many others. I haven't launched it myself as it's security trimmed.

**Comment by Jenefer-Monroe** [comment]
OK please go to the CoE Admin Command Center and see if you ahve any sync flow errors for the audit logs flows
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a691ac43-9ee2-41c9-a63d-b82d7f25f5c8)

And then go to the **_Admin | Audit Logs | Sync Audit Logs (V2)_** flow, is it on and running? Are there failures or runs that are not completing?

**Comment by uzma-fis** [comment]
No failures, running daily with success!

**Comment by uzma-fis** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/141040714/788c64b5-34d3-4148-89a0-0ece694f87d8)

Running daily as it suits our environment this way

**Comment by Jenefer-Monroe** [comment]
Do you have access to view the audit logs directly? https://compliance.microsoft.com/auditlogsearch?viewid=Async%20Search
If so please see if you find launches there.

**Comment by uzma-fis** [comment]
Will take a look

**Comment by uzma-fis** [comment]
Hi there, it's not being picked up, did a few days search.

**Comment by Jenefer-Monroe** [comment]
ok if the data is not in the raw export then it wont show up for us as we just read from here. 
To my knowledge there is not a way to hide activity from this log so perhaps no one is launching?

**Comment by uzma-fis** [comment]
There are people definitely launching it.

**Comment by Jenefer-Monroe** [comment]
To confirm, you went here and did not find launches correct? 
https://compliance.microsoft.com/auditlogsearch?viewid=Async%20Search
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2d91a000-77a1-4651-92fa-63af13ddd284)

**Comment by uzma-fis** [comment]
100% it is not in there. 
Another issue I've spotted with the power platform admin view to see the information such as shared with, only shows 1 when there's more

I've got a feeling it could be an app issue.

**Comment by uzma-fis** [comment]
OR it could be because the app is in dataverse. If you check the launch date/times for the COE environment, do you see any launch data on the canvas apps?

**Comment by Jenefer-Monroe** [comment]
When you say its an app in Dataverse, do you mean that its a Model Driven App? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/31e73bdc-3ee7-4856-9e99-02dbc1a1e1ab)

**Comment by uzma-fis** [comment]
No, it's a canvas app. I checked the environment, it has dataverse enabled. 

It doesn't make sense as to why this app isn't logging. 

Can you repo the app launch for any of the canvas apps in the COE starter kit please?

**Comment by Jenefer-Monroe** [comment]
Yes canvas apps work for me in all envt types. 
Unfortunately then, the fact that its not writing to the audit logs is a product issue, not something I can assist with. We just read form the audit logs. 
You'll need to create a support ticket to see why the launches are not writing to the audit logs.

**Comment by uzma-fis** [comment]
Hi there, support ticket has been raised. Will inform you guys. 

Also, how does COE scan for "shared with" components in canvas apps? I can see COE last scanned the app this morning, with no updated information on shared users (should be more than 1)

**Comment by Jenefer-Monroe** [comment]
That is done by this flow: CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)
And its helper. Its a long running operation and so only runs every two weeks. And it only works for Canvas apps.
Hope the ticket works! Please do let us know.

**Comment by uzma-fis** [comment]
Amazing great to know! That then resolves that question. Keep ticket open here so I can update everyone.

**Comment by uzma-fis** [comment]
Is there a limitation on how many sync log data there is?

**Comment by Jenefer-Monroe** [comment]
I just looked back up at your run history and it does look incorrect. This flow is supposed to run hourly. 
Can you please see, is this the flow you have running? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3e9dc670-b410-4387-8a8e-182388a68487)

**Comment by uzma-fis** [comment]
Yes we changed it to once a day. Is it a problem for it to change?

Uzma

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by uzma-fis** [comment]
Interesting, perhaps it's so much data it cannot load the additional but doesn't cause errors. 

Will monitor today and attempt several app launches to see this specific behavior

**Comment by uzma-fis** [comment]
Issue resolved! Getting the data now - will need to monitor our costings! Feel free to close, so my bad!

**Comment by Jenefer-Monroe** [comment]
Wonderful news! I'm so glad you kept pressing till we got tis resolved! 
Enjoy your logs, and please return with new issues as needed. 
I'll go ahead and close.
