### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit of how many apps have been shared with the whole tenant

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#7530]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!
We wanted to ask whether there is a possibility to get the information about how many apps have been shared with the whole tenant? So that we can mitigate the risk of exposing company data to the wrong users.
As it states in this documentation - https://www.theregister.com/2023/08/10/microsoft_365_guest_accounts_power/ , there seems to be a risk that to share an app with guests - it needs to be shared with everyone (so means with the "tenant") which poses a risk of oversharing.
But how to get this data? For example, we have more than 1000 environments in a tenant, and more than 6000 apps. To go through the apps manually will take a lot of time. 
Because of that we tried to create the flow to go through each environment and app; however, it seems as we have so many apps, the flow does not provide the information about each app because of the limitations. As, for example, one environment has 17 apps, but the flow for this particular environment will show only 2-3 apps. Because of that it seems that it is not possible to get the information that way. Do you know how that can be solved or perhaps you already have some other solution to get this information?
Thank you in advance!

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2124

**Comment by JanetK12** [comment]
Hi @Jenefer-Monroe!
Thank you for your answer! That is amazing that we have flows and app that store this important info!
So, if I understood correctly, in this app the information about "shared with tenant" is completed, right, and I can use it? 

and regarding the flag on makers showing if they are guest users or members - that would be also amazing if you could add this feature! I think that will be very useful. Thank you very much!

**Comment by Jenefer-Monroe** [comment]
Wonderful! I'm now preparing a set of work inspired by your issue. Including flagging guest users, trying to get this flow sped up so it can run more frequently, and a few other things. 

Please do let me know if you have other ideas! 

Also wanted to make sure you saw this. Its a way to limit the ability to share with everything to just admins. 
[Limit sharing with everyone](https://learn.microsoft.com/power-platform/guidance/adoption/secure-default-environment#limit-sharing-with-everyone)
And here is a quick video of Manuela walking through how to do it: https://www.youtube.com/watch?v=HwlhndJhsYY

**Comment by JanetK12** [comment]
@Jenefer-Monroe Thank you very much! That is really helpful as we wanted to limit the ability to share with everything!

**Comment by JanetK12** [comment]
Hi @Jenefer-Monroe !
Could we confirm one thing? Do you know what will happen if, for example, the user has the app shared with the tenant, and we will disable the ability to share the app with the tenant? Will this app be deleted automatically? Or nothing will happen with the app, just will be removed this option to be shared with tenant, but everything will be ok with app itself and it will be working as always? I am just asking as I heard that by disabling the ability to share the apps with tenant while someone still has this option used in their app - this app will be deleted when the ability will be disabled. Is that true?

**Comment by Jenefer-Monroe** [comment]
According to everything I've read, this does not impact apps already shared with tenant in any way. Meaning they will still be there and shared with tenant. You will need to go fix the old ones up to either no longer share with tenant.
The setting only disables the ability to share with the tenant in the future.

**Comment by JanetK12** [comment]
Hi @Jenefer-Monroe !
Thank you for your fast answer! And thank you for your explanation, good to hear!
Could I ask one more question if that is not taking your time? 
Am I understanding that right that only apps actually can be shared with tenant, but flows cannot? So like it is a problem only for the apps, but nothing else can be shared with tenant - like flows, solutions? Just wanted to confirm this.

**Comment by Jenefer-Monroe** [comment]
I'm really not sure of that answer. It appears to not be available to flows but I'm not sure about the suite as a whole.

**Comment by Jenefer-Monroe** [comment]
closing out, the action items from this will be tracked. Please see https://github.com/microsoft/coe-starter-kit/issues/7593 for the first one we will ship next month.
