### ISSUE TITLE
office365Users.UserProfileV2 failed

### ISSUE THREAD

**Issue by atnafsegedz** [microsoft/coe-starter-kit#7533]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

i am getting office365Users.UserProfileV2 failed error message when i try to update Flow owner using Add Permission. The error showed up when i start typing in Add New User  search box.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

not sure

### What app or flow are you having the issue with?

flow 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2128

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot? This will help us in deducing where to look for your issue. 
Note that you need to log in to GitHub to share images, responding in email will not share an image.

**Comment by atnafsegedz** [comment]
here is the screenshot
![UserProfileV2 error](https://github.com/microsoft/coe-starter-kit/assets/51202796/dd121284-4948-40e5-957f-4e9d5bfd1588)

**Comment by Jenefer-Monroe** [comment]
oh I gotcha thank you. 
This is an old app we are replacing, we've fought that bug quite a bit. You can expect to see a new version of these Permission Management apps soon.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
