### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Driver) Failed to Run

### ISSUE THREAD

**Issue by Sinder088** [microsoft/coe-starter-kit#7538]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Recently installed the COE toolkit. This flow successfully ran the first 3 times but has been failing since Saturday. When i compare the latest failure with the last successful run i see that in the action "Get Maker" the successful one looks for "SYSTEM" where as the failed ones is looking for my particular admin account. 

Any idea why this might be failing and how to fix it? 

One thing to note is i changed the name of the environment on Friday, so perhaps that is causing the issue? 
![Success](https://github.com/microsoft/coe-starter-kit/assets/120589120/fbd50e08-098a-41df-9208-938b2e208484)
![Failure](https://github.com/microsoft/coe-starter-kit/assets/120589120/e969e212-3d3d-480e-9bc9-1f98e2382e02)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2135

**Comment by Jenefer-Monroe** [comment]
Sometimes name changes do mess up things like the ability to call child flows. 
You may try to turn off and back on all the flows in the solution with the word **_help_** in the name. 
In particular for this issue that would be the flow **_HELPER - Maker Check_**

**Comment by Sinder088** [comment]
Thanks this solved the problem :)
