### ISSUE TITLE
 Invalid Trigger "CoE BYODL - When Environment dataflow refresh is complete" 

### ISSUE THREAD

**Issue by bbarlament** [microsoft/coe-starter-kit#7541]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The BYODL flows that trigger after dataflow refreshes are not being triggered correctly. The error message for the trigger is a BadRequest "The trigger is invalid" although the parameters look to be correct. It does seem to trigger when I do a flow test and refresh the Dataflow, but it still displays the trigger error.

Group Type = Environment
Group = CoE Environment GUID
Dataflow = Dataflow GUID

{
  "Message": "The trigger is invalid 'https://flow-apim-unitedstates-002-eastus-01.azure-apim.net/apim/dataflows/shared-dataflows-51e7b52e-5fbe-4cd5-8c41-821d6932d50a/api/groups/ENVGUID/dataflows/DATAFLOWGUID/onrefreshcomplete?workspaceType=Environment'",
  "Reason": "'InvalidTrigger' - GroupType 'Environment'",
  "WorkspaceType": "Environment",
  "OperationId": "OnRefreshComplete",
  "ClientRequestId": "16bb6c7e-4ba8-41a7-afd8-9790131befc2",
  "ClientRequestUrl": "https://flow-apim-unitedstates-002-eastus-01.azure-apim.net/apim/dataflows/shared-dataflows-51e7b52e-5fbe-4cd5-8c41-821d6932d50a/api/groups/ENVGUID/dataflows/DATAFLOWGUID/onrefreshcomplete?workspaceType=Environment"
}

### Expected Behavior

The flows should execute successfully after Dataflow refresh

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

CoE BYODL - When Environment dataflow refresh is complete

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Refresh environments dataflow

AB#2138

**Comment by Jenefer-Monroe** [comment]
Did you use the setup wizard to get setup? It sets up the needed Dataflow IDs. 
You can double check them in the CoE Admin Command Center
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7490d4f6-4114-4f72-8ef1-bd070999316a)

**Comment by bbarlament** [comment]
Yes, I used the wizard and confirmed the correct IDs are set in the
environment variables. I also verified they are correct in the error
message from the flow.

**Comment by Jenefer-Monroe** [comment]
Go to a successful run and see what you see in the trigger inputs. It should be Group Type Environment and the group shoudl be a guid with a region string at the end
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f825e0d8-8909-4c38-a7b6-1755fa24cb42)

Does the string in group match this env var?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3298e19a-6bcb-458f-9110-5ffd05d0d4bd)

**Comment by bbarlament** [comment]
The string in group does match the admin_CurrentEnvironment variable. It's just a GUID with no region string on the end, so perhaps that's the issue? To verify, I edited the CoE flow and chose the environment via the dropdown then ran a test and saw that the GUID it uses does indeed include a regional setting but also the GUID does not align with the Environment ID that I expected.

Where would I go to get the correct GUID for the Current Environment variable? I would have expected it to be the GUID in the URL when I'm in the environment in PowerApps/Automate. 

Updating the variable with the value obtained by editing the Flow solved the problem.

**Comment by Jenefer-Monroe** [comment]
Yes please put that string in the environment variable and then turn all these dataflow is complete flows off and back on to ensure the flows get the new value. That should fix it up!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
