### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Platform Admin View - Flows

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#7544]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the flows view, I have flows with the status Suspended and Stopped. I understand that flow is suspended when there is a problem with dlp or all runs were failed, but I have a question, when flow is stopped only when maker turns it off? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

December 2023

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2141

**Comment by Jenefer-Monroe** [comment]
I think flows get turned off (v suspended) for other reasons as well. Like if a flow fails consistently for some period of time, I believe that the product turns them off. I dont think the cause of off is recorded though for us to consume.
