### ISSUE TITLE
[CoE Starter Kit - QUESTION] About the Admin_maker table

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#7545]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Are co-owners or co-owners of Power Apps or Power Automate also included as eligible people in the Admin_maker table?
Also, will Power BI be included?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2024/1

### What app or flow are you having the issue with?

None  AB#2068

### What method are you using to get inventory and telemetry?

None

AB#2142

**Comment by Jenefer-Monroe** [comment]
If you add them as co owners through our tooling then they get added to the maker table and show up in the PBI. 

We do not yet scan and look for owners of flows though. Please see https://github.com/microsoft/coe-starter-kit/issues/1083 for that work item.
Once we do that feature we will have reports too.

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
Is it correct that the co-owners of the app and flow are also registered in the table?

**Comment by Jenefer-Monroe** [comment]
For apps yes. For flows, not yet (unless you add them through our tooling) . Please see https://github.com/microsoft/coe-starter-kit/issues/1083 for that work item to also include flow co-owners even if added outside our tooling.
