### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Check Deleted) needs to run weekly

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#7546]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Some users who receive the compliance request emails are choosing to delete their apps rather than supply support details. This is fine but they receive the same email a week later because the inventory is only updated fortnightly. 
Therefore can the flow "CLEANUP - Admin | Sync Template v3 (Check Deleted)" be changed to run weekly instead of fortnightly?
At present I have set a reminder to run the flow manually before the emails are sent.

### Expected Behavior

Requests for compliance should not be sent after apps are deleted.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2.2

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Wait until the flow 'CLEANUP - Admin | Sync Template v3 (Check Deleted)' has run (this will be a Saturday). Then wait for the compliance request emails to be sent (on a Monday). Then delete an app where a compliance email has been about it. Wait for the next run of the compliance emails (the following Monday). The email will be sent again.

AB#2143

**Comment by Jenefer-Monroe** [comment]
As part of the big refactoring work done fir the Feb release, as part of moving to the modern Dataverse connector, we also switched to using set logic for the Check Deleted work. This reduced the API count enough to have it run weekly. 
So good news starting with that release!

**Comment by Jenefer-Monroe** [comment]
You bet! I'll go ahead and close this out then but please feel free to reach out with new issues or questions as they come up!
