### ISSUE TITLE
[CoE Starter Kit - QUESTION] update the message when an apps is in quanrantine

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#7547]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

hi the fabulous team,

I'm getting old, i would like to update the message when an apps is in quarantine

<img width="653" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/1d162a5e-d36f-4ecc-b425-9e70516c2ec5">

I have forgotten where is the parameter. Could you tell me where is i can find it ?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.14

### What method are you using to get inventory and telemetry?

None

AB#2145

**Comment by Jenefer-Monroe** [comment]
This is the message directly from the product, to my knowledge its not configurable. Happy to leave open for a bit for others to see if they know of a way to change it.

**Comment by tocri** [comment]
Found it.   It took some time for the changes to take effect.

To define the message

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/cefd2664-426f-43c1-acef-5b9ee7a86516)

To update 

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/a85841e0-edcc-419f-a280-4f2cafb8fe8e)

**Comment by Jenefer-Monroe** [comment]
Wow thank you so much for following up here to share! People will love this!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
