### ISSUE TITLE
[CoE Starter Kit - Feature]: Filter Application Users And Guest Users from the System Admin Role Report

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7548]
### Is your feature request related to a problem? Please describe.

We have a lot of application users and this is causing an additional effort on filtering per user vs app user. 

### Describe the solution you'd like

Using the same CoE view have the ability to select and filter application user vs user. We cannot use the name as a way to filter given that some user account due share similar naming conventions as the application users. This needs to be filtered based on account properties. 

### Describe alternatives you've considered

No Alternatives. 

AB#2146

**Comment by Jenefer-Monroe** [comment]
We do have this field on the Maker table. Is that what you mean? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5ff4cd96-1cc3-43c4-b3f9-3d641236e32b)

**Comment by nasilvae** [comment]
> We do have this field on the Maker table. Is that what you mean? ![image](https://private-user-images.githubusercontent.com/89584709/300116102-5ff4cd96-1cc3-43c4-b3f9-3d641236e32b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMDU2NzQsIm5iZiI6MTcwNjMwNTM3NCwicGF0aCI6Ii84OTU4NDcwOS8zMDAxMTYxMDItNWZmNGNkOTYtMWNjMy00M2M0LWIzZjktM2Q2NDEyMzZlMzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDIxNDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNjM1OTU3ODhjMDJlOWFiYTkyZTkxMWNiMjAyMWE5YTRiMzc4MzY0NTNkYzdhMzhkMjU1MjUwOTQwMTgwY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ffeCSYxXyC4xny8_vycjdoyD86-uxf8hEbT0Vxi6Oo)

I did not knew this. Thank you.

**Comment by Jenefer-Monroe** [comment]
YEAH!

**Comment by nasilvae** [comment]
> YEAH!

Hey i tried to pull the same column on the security role permission view but I am not seeing that option?

**Comment by Jenefer-Monroe** [comment]
Oh yes we dont have that information there. 
Can you please find a service principle in the SR Permissions table and see what it shows today?

**Comment by Jenefer-Monroe** [comment]
OK we did not do this in the past but we happen to be redoing this for a March feature: https://github.com/microsoft/coe-starter-kit/issues/7593

I'd added tracking guest users with that already, so I'll use your bug to track app registration as well.

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/af14cf48-6f43-4a0b-94e0-a15f4a8e28eb)
