### ISSUE TITLE
[ALM Accelerator - QUESTION] Is it possible to set a Service Principal as owner of an App or a Flow?

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#7550]
### What is your question?

Hi Team,
Is it possible to set a service principal as owner of an App or a Flow on the Configure Deployment Settings screen?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

January 2024

AB#2148

**Comment by RajeevPentyala** [comment]
@LucX4 If the 'Service Principal' is added to Dataverse as an 'Application User,' you can copy the 'Email address' of the 'Application User' as highlighted below and configure it in the deployment settings screen.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/080b617e-4f3f-4ad0-ac89-d42a58fa8d30)

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/4194c33f-0cc5-47c1-ace2-79a2d64d41b8)


Please let me know if you would need any additional details.

**Comment by LucX4** [comment]
Hi @RajeevPentyala,
Thanks very much. 
It works as expected for Flows, but when I tried it with a Canvas App, the ownership didn't change. It set the Service Principal used for ALM as the owner.
Do you know if this isn't possible yet?

**Comment by RajeevPentyala** [comment]
@LucX4 We can set the Canvas App owner to an Application User. Can you please provide the logs of the 'Set Canvas App Ownership' task from your deployment pipeline run?

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/ce27a949-799f-4853-ad18-da1b3dd984a3)

**Comment by LucX4** [comment]
@RajeevPentyala, please, see the error message below:

Code        : 400
Description : Bad Request
Headers     : {Vary, Strict-Transport-Security, x-ms-islandgateway, Referrer-Policy...}
Error       : @{code=InvalidOwnerPrincipalType; message=Object id '' cannot be the 
              owner of app because their principal type is 'ServicePrincipal', and it must be 'User'.}

**Comment by LucX4** [comment]
Hi @RajeevPentyala, hope you are doing well!
Just checking if you had the opportunity to review the above error message.

**Comment by RajeevPentyala** [comment]
@LucX4 I could reproduce the issue. Please allow us sometime. We will check and revert.

**Comment by RajeevPentyala** [comment]
@LucX4 I can confirm that a **'Service Principal' cannot be set as an App owner**. However, a 'Service Principal' can be the owner for a flow. To avoid any confusion, we will include an 'Information' text in the 'ALM Accelerator' app. Thanks.

**Comment by LucX4** [comment]
Hi @RajeevPentyala,
Thanks for letting me know. 
When an owner isn't configured in this field, the app defaults to setting the Service Principal used in the ALM Accelerator as the owner. This lead me to believe that it would be possible to configure a different Service Principal as the owner.

**Comment by RajeevPentyala** [comment]
@LucX4 Closing the issue. Please feel free to reach out if you need any additional details.
