### ISSUE TITLE
[ALM Accelerator - Feature]: Customise Solution Version number post deployment to ALM

### ISSUE THREAD

**Issue by iamaninda93** [microsoft/coe-starter-kit#7553]
### Is your feature request related to a problem? Please describe.

Every time when we set up ALM of a new solution in AzDO we need to correct the versioning manually in the copied coe pipelines of the solution. This we don't want. We want the solution to have pipelines with the correct version number format YYYYMMDD.count.

Solutions deployed with the ALM Accelerator adhere to the version number format YYYYMMDD.countSolutions deployed to environments by the ALM Accelerator tools have the wrong version number format. It should be YYYYMMDD.revision but it is 1.0.YYYYMMDD.revision.

### Describe the solution you'd like

Solutions deployed with the ALM Accelerator adhere to the version number format YYYYMMDD.count. Solutions deployed to environments by the ALM Accelerator tools have the wrong version number format. It should be YYYYMMDD.revision but it is 1.0.YYYYMMDD.revision.

### Describe alternatives you've considered

Every time we need to change the format manually for each application.
![01gb9gvr](https://github.com/microsoft/coe-starter-kit/assets/38653460/887476c8-4b81-405a-aad0-90fbcf47e7b1)

AB#2152

**Comment by RajeevPentyala** [comment]
@iamaninda93 If you prefer not to use the 'ALM Accelerator' versioning pattern, you can set the variable 'skipSolutionVersioning' to true in the Deployment pipelines. Please refer the related issue here : #7105

**Comment by iamaninda93** [comment]
@RajeevPentyala The below screenshot is the Coe alm accelerator templates folder. Can you tell in which of the yml file I need to set the variable 'skipSolutionVersioning' to true ?
![01gb9gvr](https://github.com/microsoft/coe-starter-kit/assets/38653460/851a5368-b99c-4128-b8c8-55881d6e59a7)

**Comment by RajeevPentyala** [comment]
@iamaninda93 You don't need to change the yml files. Add a 'skipSolutionVersioning' variable under **Pipelines > Library > alm-accelerator-variable-group** as shown below.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/ad567868-d73f-40f1-80b9-e573e7333273)

**Comment by iamaninda93** [comment]
@RajeevPentyala I have added"SkipSolutionVersioning" to true in the varable group. Apart from that in which yml file the version format needs to be added?

Desired Version format: YYYYMMDD.revision

Cuurent YML file:
![MicrosoftTeams-image (4)](https://github.com/microsoft/coe-starter-kit/assets/38653460/791bfe5c-0b70-47f6-9539-3a6b17585123)

**Comment by iamaninda93** [comment]
Hi Rajeev,

I have added"SkipSolutionVersioning" to true in the variable group. Apart
from that in which yml file the version format needs to be added?
Desired Version format: YYYYMMDD.revision





Regards,
Aninda

upload image Aninda Kar M: 9748917049 E: ***@***.***

**Comment by RajeevPentyala** [comment]
@iamaninda93 Please note that ALM Accelerator exhibits two behaviors when it comes to solution versioning.

- If **SkipSolutionVersioning** is set to false, which is the default behavior, it assigns the version to an auto-generated build number. The corresponding logic can be found here: **..\Pipelines\Templates\build-Solution.yml > 'Update Solution XML with Build Number'** task.
- If **SkipSolutionVersioning** is set to true, 'ALM Accelerator' will not assign any version number, and it will consider whatever version number is set in the maker environment.

**Comment by mikefactorial** [comment]
@iamaninda93 have you seen this? https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/configure-azuredevops-pipelines#customize-versioning-of-solutions-when-you-use-the-alm-accelerator-pipelines-to-export-or-deploy-them

**Comment by iamaninda93** [comment]
@mikefactorial 
I have taken below steps. Still getting the default version number. My desired version number is  "20240112.1", "20240112.2"
What I am getting is  "1.0.$(Date:yyyyMMdd)$(Rev:.r)". I dont want the Dev environment version number in QA or in prod. Every deployment to Qa/prod will increase version number of QA and Prod.

Step 1 :
build-solution-pack-pre-hook.yml-----

steps:
  - script: echo Build Solution Pack Pre Hook
    displayName: 'Build Solution Pack Pre Hook'
    enabled: True

  # CUSTOMIZED: Using below template to customize solution version number.
  - template: CustomTemplates/custom-solution-version-number.yml




Step 2: custom-solution-version-number.yml


steps:
- task: PowerShell@2
  displayName: 'Set Solution Version'
  inputs:
    targetType: 'inline'
    script: |
      $date = Get-Date -Format yyyyMMdd
      $revision = $env:BUILD_BUILDNUMBER
      $version = "$date.$revision"
      Write-Host "##vso[task.setvariable variable=SolutionVersion]$version"

**Comment by mikefactorial** [comment]
@iamaninda93 thanks for the detailed response. Looks like you're pretty close. You'll just want to inject the version number you are creating in custom-solution-version-number.yml into the solution.xml similar to how we are doing it in the powershell script @RajeevPentyala mentioned above.

See here
https://github.com/microsoft/coe-alm-accelerator-templates/blob/d7c09997b129e4f0811e98a39e6ad2aa1724816a/Pipelines/Templates/build-Solution.yml#L91

and here
https://github.com/microsoft/coe-alm-accelerator-templates/blob/d7c09997b129e4f0811e98a39e6ad2aa1724816a/PowerShell/build-deploy-solution-functions.ps1#L314 

Something like the following. NOTE: This isn't tested just a sample

task: PowerShell@2
displayName: 'Set Solution Version'
inputs:
targetType: 'inline'
script: |
. "$env:POWERSHELLPATH/load-save-pipeline-parameters.ps1"
$parameters = Read-Pipeline-Parameters "$(Agent.BuildDirectory)\build-pipeline-parameters.json"
$solutionXMLPath = "$(Build.SourcesDirectory)\$(RepoName)\$parameters.solutionName\SolutionPackage\src\Other\Solution.xml"
$date = Get-Date -Format yyyyMMdd
$revision = $env:BUILD_BUILDNUMBER
$version = "$date.$revision"
[xml]$xmlDoc = Get-Content -Path $solutionXMLPath
$xmlDoc.ImportExportXml.SolutionManifest.Version ="$version"
$xmlDoc.save("$solutionXMLPath")
    }

**Comment by iamaninda93** [comment]
@mikefactorial 

Here is the code given below. While running the pipeline its throwing error.Can you have a look?
![MicrosoftTeams-image (5)](https://github.com/microsoft/coe-starter-kit/assets/38653460/a8193791-da6a-479b-8de7-ef72e89292ae)


steps:
- task: PowerShell@2
  displayName: 'Set Solution Version'
  inputs:
    targetType: 'inline'
    script: |
          . "$env:POWERSHELLPATH/load-save-pipeline-parameters.ps1"
          $parameters = Read-Pipeline-Parameters "$(Agent.BuildDirectory)\build-pipeline-parameters.json"
          $solutionXMLPath = "$(Build.SourcesDirectory)\$(RepoName)\$parameters.solutionName\SolutionPackage\src\Other\Solution.xml"
          $date = Get-Date -Format yyyyMMdd
          $revision = $env:BUILD_BUILDNUMBER
          $version = "$date.$revision"
          [xml]$xmlDoc = Get-Content -Path $solutionXMLPath
          $xmlDoc.ImportExportXml.SolutionManifest.Version ="$version"
          $xmlDoc.save("$solutionXMLPath")
          Write-Host "##vso[task.setvariable variable=SolutionVersion]$version"

**Comment by mikefactorial** [comment]
@iamaninda93 try replacing
```
$solutionXMLPath = "$(Build.SourcesDirectory)\$(RepoName)\$parameters.solutionName\SolutionPackage\src\Other\Solution.xml"
```

with 
```
$solutionName = $parameters.solutionName
$solutionXMLPath = "$(Build.SourcesDirectory)\$(RepoName)\$solutionName\SolutionPackage\src\Other\Solution.xml"

```
