### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View - Flows

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#7554]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello I found that I have some flows that are actually suspended but status in app is still started:

Admin View app:

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/ecd1bbed-a02c-46ab-817b-8f2bc96d68ec)

Action in Power Automate (Current status):

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/a4731cf4-1a24-4f8e-b0a7-c7d2765c90a0)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2153

**Comment by BartoszKaminski1999** [comment]
Another case: 

Suspension Reason is filled but actually flow is not suspended 

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/149cf76c-b194-438e-97bd-38588d608817)

<img width="1153" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/54030753/51cecfed-1b9b-409e-acf9-61cdfcca1952">

**Comment by Jenefer-Monroe** [comment]
Please note the environmet of your repro, go to the most recent run of **_Admin | Sync Template v4 (Flows)_** for that environment. Click the timestamp to open the run
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/96c8f10b-b481-4ad3-999d-d598f549a0c7)

Look at the output of **_List Flows as Admin (V2)_** and find your flow. What do you see for state?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1786f8ef-2bf4-47ef-8846-794e1a1c89a5)

**Comment by BartoszKaminski1999** [comment]
Hello,

I can see that this sync is not done for all environments (should be over 100 environments there) every day:

<img width="411" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/54030753/7d1c595b-1765-4ae5-94e1-70aa5ebb117e">

**Comment by BartoszKaminski1999** [comment]
I can see that my Driver Flow was turned off, I turned on it today and set full inventory evn to true, let's wait for the result.

**Comment by Jenefer-Monroe** [comment]
sounds good! if there are some still missing, please go to an environment tha tis missing in the product's admin page and see if your user running the flows is listed as a sys admin in those envts/

**Comment by BartoszKaminski1999** [comment]
Full inventory resolved the problem, thanks
