### ISSUE TITLE
[CoE Starter Kit - BUG] COE Toolkit Setup Instructions - Entra ID

### ISSUE THREAD

**Issue by nwmb** [microsoft/coe-starter-kit#7555]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The HTTP with Microsoft Entra ID connector has been been split into HTTP with Microsoft Entra ID and HTTP with Microsoft Entra ID (Preauthorized).  It looks like the "(preauthorized)" version is the correct one, given the technical name matches that of the previous HTTP with Azure AD - but the documentation does not include this descriptor.  

When attempting a fresh install using the (preauthorized) only, I am not prompted for a missing connection - so that appears to confirm the assumption above as well.

It may be worthwhile to adjust the DLP related documentation here to indicate that the (Preauthorized) version must be used:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

And the connection setup instructions here to indicate that the (Preauthorized) version must be used: 
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections

![image](https://github.com/microsoft/coe-starter-kit/assets/79591673/e73704ea-a1ed-4331-acf7-9bf942f1e3b4)

### Expected Behavior

Updated documentation to include the (preauthorized) denotation to alleviate user confusion when installing the COE

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Install

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Fresh install

AB#2157

**Comment by Jenefer-Monroe** [comment]
Hello. Thank you for posting. Yes we need to update this documentation. We do have https://github.com/microsoft/coe-starter-kit/issues/7527 for this but can hold this one too since that got closed.

**Comment by nwmb** [comment]
Thanks Jenefer!  Sorry I didn't see that one you linked, the default filter was only for open items and that one is in a closed status.

**Comment by pnoot7** [comment]
I think this needs to be a higher priority. There have been 3 releases now, and the documentation is still incorrect. I almost started down a very long and painful road with our GAs to have this done. When using the "HTTP with Microsoft Entra ID", it gives a link to how to fix the consent error with a script and a GA needed to run it. Good thing I checked here, but think of how many that don't check here and follow the official set up documentation. 

I think the documentation as a whole needs to be refreshed. Maybe have someone on your team (or even someone not - without your knowledge) go through the documentation and update where its changed/needed. A product is only as good as its documentation.

**Comment by GarryPope** [comment]
I also ran into this when doing a set up for the first time. 

![image](https://github.com/microsoft/coe-starter-kit/assets/68440710/053a7286-db97-4bea-92f1-cb44edf4dd82)

So I created the "Connection" of "HTTP with Microsoft Entra ID (preauthorised)" instead and didn't receive the above error. If I have any problems running Flows, I'll message back. @nwmb thanks for posting this here. Saved me a lot of headache.

**Comment by Jenefer-Monroe** [comment]
> I think this needs to be a higher priority. There have been 3 releases now, and the documentation is still incorrect. I almost started down a very long and painful road with our GAs to have this done. When using the "HTTP with Microsoft Entra ID", it gives a link to how to fix the consent error with a script and a GA needed to run it. Good thing I checked here, but think of how many that don't check here and follow the official set up documentation.
> 
> I think the documentation as a whole needs to be refreshed. Maybe have someone on your team (or even someone not - without your knowledge) go through the documentation and update where its changed/needed. A product is only as good as its documentation.

Folks please note that this was not an issue of prioritization but there were issues blocking us from doing this work. 
We are now unblocked yeah! And so I'm doing a documentation pass this month.

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5148f8d2-e854-4bcc-b1e0-1edb6fd63d6a)


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c57fe177-d6b3-4a0b-8c76-7bc04f5d1f5d)
