### ISSUE TITLE
[CoE Starter Kit - QUESTION] Issue on loading Production_CoEDashboard_January2024.pbit

### ISSUE THREAD

**Issue by JanusAllenCapili** [microsoft/coe-starter-kit#7556]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

**Hi Team,**

I have an inquiry with regards to loading the Production_CoEDashboard_January2024.pbit PowerBI File.

Specifically when I loaded the file, I get a list of messages which stops from loading the data into the list of PowerBI reports. 

![powerbicoe-error](https://github.com/microsoft/coe-starter-kit/assets/156774820/25e38e94-efae-4743-8bbe-337dca76c960)

You may refer to the message below for further information:

### ### ### 
AI Builder Models
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Power Apps
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

App Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Power Apps Launches
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Business Process Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Connectors
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Environments
Column 'Environment ID (with prefix)' in Table 'Environments' contains a duplicate value 'Legacy-216761f7-****-****-****-************' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.

Environment Capacity
Load was cancelled by an error in loading a previous table.

Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Flow Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Flow Action Details
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Makers
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Power Pages
Load was cancelled by an error in loading a previous table.

Power Platform Users
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Power Platform User Role
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Power Virtual Agent bots
Load was cancelled by an error in loading a previous table.

Desktop Flows
Load was cancelled by an error in loading a previous table.

Desktop Flow Sessions
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Solutions
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

NonProdWords
Load was cancelled by an error in loading a previous table.

Key Measures
Load was cancelled by an error in loading a previous table.

Power Virtual Agent bots usage
Load was cancelled by an error in loading a previous table.

Appreciate your inputs on this.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2158

**Comment by Jenefer-Monroe** [comment]
Can you please take a look in your environments table. 
Adjust the columns so that you can see Name and Display Name, then filter name to contains legacy-
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f7507ad2-8b48-48ba-ad31-2dc318960cbe)

How many records do you have? There should be only 1 legacy envt

**Comment by JanusAllenCapili** [comment]
Hi Jenefer,

Thank you for your response.

Please refer to the screenshot below as per request:

[
![legacy-environments](https://github.com/microsoft/coe-starter-kit/assets/156774820/dffdfb3e-353d-4f44-ad3d-ac48fd162db8)
](url)

It seems there are a lot of Environments with the name, "Legacy-".

Also, the one on the first row is the Environment that only has Apps and Flows, which is of type "Production".

Would you recommend to remove the rest of the Environments, retaining only the Environment indicated on the first row and configure the PowerBI report again?

**Comment by gregvolz** [comment]
I was just installing a fresh CoE Starter Kit and found I had to do the following steps to get the data to load.

**Pre-requisites**

- CoE Core version 4.22 solution
- Logged in user has Power Platform Admin RBAC
- Used the COE Dashboard included with the 

Repro steps that **DID NOT** work (produced the same errors as above)

1. Opened Power BI Desktop (PBID)
2. Logged in (upper right-hand corner) as same user that installed the CoE Starter Kit
3. From PBID, did File-> Open -> navigated to directory with .PBIT file in it.
4. System opened the file but did not prompt for ORG url.
5. System came up with the normal two refresh buttons but said that there was no data for quite a few of the tables.

Repro steps that DID work

1. Open PBID
2. Stay logged out.
3. File -> Open -> Browse this device -> navigated to the PBIT file and opened there.
4. System prompted for ORG URL.
5. System prompted for credentials.
6. Data loaded

**Comment by JanusAllenCapili** [comment]
After removing all of the duplicate Environment Names in the "Environments" table, I was able to load and configure the Production_CoEDashboard_January2024 in PBI. Here are the steps that I did:

1. Removed ALL duplicate Environment names
2. Loaded the PowerBI Report
3. Prompted to input the ORG URL
4. Signed-in and the data has been loaded successfully.

Many thanks for the assistance, Jenefer. Greg's steps can also be added as an alternative if in any case someone encountered a similar case like his.

**Comment by Jenefer-Monroe** [comment]
Oh wonderful news! Lets hold this open a few days. If those repeat LEgacy- records come back we can investigate.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
