### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inactivity deletion approval email received, but not seeing a record in "App and Flow Inactivity Cleanup and Notification View" app

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#7557]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

A user in my tenant is receiving an email about one of her employees not responding to inactivity deletion approval emails.

The employee had an inactive Dataverse for Teams app called "Milestones".

It shows up in "Power Platform Admin View", but when I look in the "App and Flow Inactivity Cleanup and Notification View" app, I don't see any record of the deletion approval being sent at all. I searched under "APPS - all approvals"

I'm assuming upgrading from the Nov 2023 release to the January 2024 release would perhaps fix this issue, but I'm curious on why that may have happened in the first place.
Any theories on why this happened?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

November 2023

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2159

**Comment by Jenefer-Monroe** [comment]
I've not heard of this bug so I would not expect an upgrade to resolve. Can you please confirm if you have all these flows turned on and running?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4651df10-d2c2-45cb-8ca4-ee847714ecfd)

**Comment by firefox-edge123** [comment]
In my COE production environment, all the Inactivity flows are turned on and running. (as per the screenshot below)

Note: I have made careful customizations to the each of the inactivity flows (except for "Admin | Email Managers Ignored Approvals")

In my COE test environment I have the exact same customizations, but the Milestones app shows up in "App and Flow Inactivity Notifications Clean Up View"

Note: My COE test environment is using the Jan 2024 release and has the "ProductionEnvironment" environment variable set to No.

Is there any other place I should look?

![COE-inactivity-flows](https://github.com/microsoft/coe-starter-kit/assets/128085471/b2a3ee44-8015-410f-83c0-684de3580850)

**Comment by firefox-edge123** [comment]
@Jenefer-Monroe 

I did a bit more digging and here is some more information that might offer a clue on what is causing the issue.

I noticed that in the PROD environment, in the "Admin | Inactivity notifications v2 (Start Approval for Apps)" flow, in the "Create Archival Request for Each", there are 97 instances for the most recent run on Jan 29.


While in the Test environment, there are 115 instances for the most recent run on Jan 29.

Note:
For both environments, the "InactivityNotifications-PastTime-Interval" and "InactivityNotifications-PastTime-Unit" are set to their default value.

In the PROD environment:
![image](https://github.com/microsoft/coe-starter-kit/assets/128085471/f5cdad6d-3300-4f8b-862f-f8cd846bdd6f)


In the TEST environment:
![image](https://github.com/microsoft/coe-starter-kit/assets/128085471/04eaf793-147b-4224-8b33-e8a53e178857)

**Comment by Jenefer-Monroe** [comment]
ok so this is resolved in the newer build for you then. In the Jan release install.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
