### ISSUE TITLE
[CoE Starter Kit - Feature]: Extend Audit Log User Job Title length from 100 to 150

### ISSUE THREAD

**Issue by ramontebar** [microsoft/coe-starter-kit#7560]
### Is your feature request related to a problem? Please describe.

We have some long employees job titles and the flow "Admin | Audit Logs | Update Data (V2)" fails when trying to update the Audit Log column "User Job Title". See screenshot below:

![powerplatform-update-auditlog-userjobtitle-error-240130](https://github.com/microsoft/coe-starter-kit/assets/7858467/ffa8bc1f-d97b-4f3e-be59-ffb4c9e47e82)

### Describe the solution you'd like

Extend Audit Log User Job Title maximum length column from 100 to 150

AB#2162

**Comment by RahulBojji** [comment]
Thanks for reaching out, this should be minor fix. Will fix this in the next release.

**Comment by Jenefer-Monroe** [comment]
Made all these newly used fields (eg Department, Job Title) slightly larger.

**Comment by ramontebar** [comment]
Thank you Team! 👏
