### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to get flow runs history? What is the data source.

### ISSUE THREAD

**Issue by Kamilschibsted** [microsoft/coe-starter-kit#7561]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I would like to retrieve history of flow runs like:

Flow A :
Run 1 Failed
Run 2 Cancelled
Run 3 Failed
Run3 Success

I need to make some some my charts with it.

Preferably in the table. What is the data source, how can I achieve that? I see that CoE has similar chart in Usage tab. (It shows how many times flow was run, but without success rate etc.) So data is somewhere there. Where exactly?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2163

**Comment by RahulBojji** [comment]
@Kamilschibsted 
Currently, COE kit doesn't store any information regarding the cloud flow runs as its not available from the product via any connectors. 
But the product itself is providing a table which has flow run information. Please go through [this](https://learn.microsoft.com/en-us/power-platform/release-plan/2023wave2/power-automate/store-cloud-execution-history-dataverse) for more information

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
