### ISSUE TITLE
Admin app- set app permissions- not able to see default environment

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#7563]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Today, I see that in admin app, set app permissions- we were not able to see the default environment, also checked the dataflows and they are running successfully.

<img width="733" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/f0890a14-5dfe-48e8-b7d7-41164f1a694f">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

app

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

<img width="733" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/d3bd4c5c-3ae3-436c-8df5-330ea1bf5ae2">

AB#2166

**Comment by Jenefer-Monroe** [comment]
My guess is that you hit this bug https://github.com/microsoft/coe-starter-kit/issues/7562
Please apply the fix described here: https://github.com/microsoft/coe-starter-kit/issues/7562#issuecomment-1916812148
And then wait for the next data refresh to see if the default envt returns.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
