### ISSUE TITLE
[CoE Starter Kit - QUESTION] Condition details for Inactive flows

### ISSUE THREAD

**Issue by rimoism** [microsoft/coe-starter-kit#7568]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The following document states that the conditions for an inactive flow are that there is no flow editing for a certain period of time (default 180 days) and **the status is Turn OFF.**
[Admin | Inactivity notifications v2 (Start Approval for Flows)
](https://learn.microsoft.com/en-us/power-platform/guidance/coe/governance-components#admin--inactivity-notifications-v2-start-approval-for-flows)

I think that Turn OFF refers to the flow status as shown below.
![image](https://github.com/microsoft/coe-starter-kit/assets/85472868/4755fcfd-ab43-42e5-be40-256d6cfcb7ef)

**Q. Is my understanding of the meaning of "Turn OFF" correct?**

On the other hand, the filter that retrieves the list of inactive flows has a condition where status ≠ Stopped.
![image](https://github.com/microsoft/coe-starter-kit/assets/85472868/b4a31577-af83-4224-97e5-edd1ebb337b4)

**Q. I think the correct code for this condition is "admin_flowstate ne 'Started'" or "admin_flowstate eq 'Stopped'", is that correct?**

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

January 2024

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2171

**Comment by RahulBojji** [comment]
Yes, whatever you are understanding the process is correct. You can make an unmanaged layer for now to remove this filter if you would like and that we will be making this configurable when we redo the feature.

**Comment by rimoism** [comment]
> Yes, whatever you are understanding the process is correct. You can make an unmanaged layer for now to remove this filter if you would like and that we will be making this configurable when we redo the feature.

Thank you for your reply.
Please tell me why the condition implemented in the actual flow is status ≠ Stopped (status = Started or status = Suspended) even though the reference says TurnOFF.

**Comment by RahulBojji** [comment]
status not equal to stopped is same as status = started or status= suspended. It retrieves both started flows and suspended flows.

**Comment by rimoism** [comment]
I believe that flows with a status of "Started" are generally **active**.
I feel strange that the default condition is like that.

**Comment by RahulBojji** [comment]
As mentioned above, feel free to make an unmanaged change as we will be redoing this feature to make it configurable
Thanks

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
