### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis - AppForbidden for System Administrator

### ISSUE THREAD

**Issue by RobH-CRT** [microsoft/coe-starter-kit#7570]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When opening the DLP Impact Analysis app, I get an error:

Error Code: AppForbidden

{"error":{"code":"Forbidden","message":"The user with object id '5XXXXXXXXXXXXXXXXXXXXXXXXXXXXX5' does not have permission to access this.","details":[{"code":"PowerAppsNoAccess","message":"The user does not have access to the app."}]}}
s@https://content.powerapps.com/resource/uci-infra/scripts/app.a504ad7c531d78054c9e4039a5903d60.js:33:999415 i+Mw/lt/</<@https://content.powerapps.com/resource/uci-infra/scripts/custompage.db6641a4eca50e303d77f4ca565aee4a.js:4:221444 

Going in to "Share" the app, the account I am using was already in the list with System Administrator role. Tried also adding the custom Power Platform Admin SR role, but still got the error.

![coe1](https://github.com/microsoft/coe-starter-kit/assets/149477319/4aed3809-8261-4f92-8e73-00218fea6aa9)
![coe2](https://github.com/microsoft/coe-starter-kit/assets/149477319/fa69002f-c14b-45e9-9d76-bd4beb21b3f4)

### Expected Behavior

The app opens without error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

DLP Impact Analysis

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Go to make.powerapps.com/environments/<ID of environment where CoE is deployed>/apps
2. Hover over DLP Impact Analysis, and select the "Play" icon

AB#2173

**Comment by RahulBojji** [comment]
Hi 
Please check below at your end

1. It looks like the user you are attempting to log in to the app with does not have the required permissions to the environment.

Question: Is this a different user identity than the one used to install the kit?

If its the same user identity that installed the kit, note that this user needs to have the Power Platform Admin Role permanently and directly assigned. This will in turn give them sys admin access to the environment and so you would not see that error.
For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

And you can check if you are assigned the role correctly in the [Azure Portal](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers)

![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/2d5a9136-7717-4600-bedf-88d3faa38480)

2. Check if the object id that is getting displayed in error is same as the object id of the user. For getting that
Go to [Azure Portal](https://portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/Overview) - > Select users on the left hand side -> open the user you are trying to login with -> Check the property object id
<img width="741" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/6458cffd-407c-4c06-b32e-ef32405d11d2">

**Comment by RahulBojji** [comment]
If it's not same, looks like product might be logging you with different user. Can you please try clearing the cache and then sign in again. Also, if you haven't done this setup, please do create profiles in edge so that it's easy to sign in to environments. You can setup profiles using [this](https://www.microsoft.com/en-us/edge/learning-center/how-to-add-new-profiles?form=MA13I2)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
