### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYODL - Lack of data

### ISSUE THREAD

**Issue by annsarP** [microsoft/coe-starter-kit#7575]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello! We decided to start using BYODL (Data export) as source for our new experimental CoE environment to have access to more advanced Power Bi report version. We configured data export in Azure storage account, and dataflows. Initial refreshes went smoothly, without any errors. However, we noticed lacks in data. We have another CoE environment that gathers data via sync Cloud flows. We compared both Power Platform Admin View apps and numbers are different:
1. No Maker is assigned to any flow.
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/ebc80a2c-e611-412c-882c-5c314470147b)

3. Numbers of apps, flows, connectors, desktop flows, power pages sites, business process flows, solutions and ai models are different. These differences goes up to even around 400 (always there's more existing rows in app where Cloud flows are a source).
4. Number of environments is the same in both apps.
5. App ownership is different. The twist to no.2 is that in Data export we have MORE apps owned by SYSTEM:
Cloud flows as data source:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/738fef98-95e2-48c2-b127-84ddebe67c19)
Data export as data source:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/bf18079d-abc8-4926-b3a1-d5a7412566c1)

We also made a mistake during setup because **we scheduled refresh for ALL dataflows instead for Makers dataflow only** which caused some failed refreshes for Flows dataflow (only) with message "A record with the specified key values does not exist in admin_maker entity". **We removed scheduled refreshes for all dataflows besides Makers and currently there's no fails but data is still missing.** I could not find missing Maker ID in Flow Makers dataflow table but currently there are no fails in refreshes, so that's interesting. 
Is it because of this mistake?
Is it possible that issue is on Data export side, not dataflow side?

Additional information:
- We did not set the Power Bi dataset / report / model yet because we want to make sure we see correct data first.
- _CoE BYODL - (...)_ Power Automate flows are running successfully.
- I reviewed https://github.com/microsoft/coe-starter-kit/issues/7396 but since we started setup of this feature in this month, there's no DataflowRefershHistory before the latest CoE upgrade. 
- I reviewed https://github.com/microsoft/coe-starter-kit/issues/6688 and https://github.com/microsoft/coe-starter-kit/issues/6766 but it seems for Jan ver these are no longer relevant. 
- Flow Makers' Get Content gives us 3 rows only and [Table] instead of [List] in Transform file column:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/387b2859-d769-4ceb-b16e-187170414d90)
I tired to change advance code of Transform flow file with following code:
```
let
Source = (Parameter as binary) => let
Source = Text.FromBinary(Parameter),
#"Imported JSON" = Replacer.ReplaceText(Source, "}", "},"),
#"Trim last character" = Text.Trim(#"Imported JSON", ","),
#"Insert bracket" = Text.Insert(#"Trim last character", 0, "["),
#"Insert second bracket" = Text.Insert(#"Insert bracket", Text.Length(#"Insert bracket"), "]"),
#"Parsed JSON" = Json.Document(#"Insert second bracket")
in
#"Parsed JSON"
in
Source
```
But after this change instead of [Table] I had [Error]. So I changed it back. 

Current setup is:
- Transform file (4):
```
let
    Source = (Parameter as binary) => let
    Source = Table.FromColumns({Lines.FromBinary(Parameter)}),
    #"Transformed Column" = Table.TransformColumns(Source, {"Column1", Json.Document}),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Transformed Column", "Column1", {"environmentId", "environmentName", "isDefault", "environmentState", "environmentUrl", "environmentType", "securityGroup", "purpose", "cdsInstanceId", "cdsInstanceUrl", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "deletedTime", "environmentRegion", "tenantGuid"}, {"environmentId", "environmentName", "isDefault", "environmentState", "environmentUrl", "environmentType", "securityGroup", "purpose", "cdsInstanceId", "cdsInstanceUrl", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "deletedTime", "environmentRegion", "tenantGuid"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1", {{"environmentId", type text}, {"environmentName", type text}, {"isDefault", type logical}, {"environmentState", type text}, {"environmentUrl", type text}, {"environmentType", type text}, {"securityGroup", type text}, {"purpose", type text}, {"cdsInstanceId", type text}, {"cdsInstanceUrl", type text}, {"createdTime", type datetime}, {"createdPrincipalId", type text}, {"lastModifiedTime", type text}, {"lastModifiedPrincipalId", type text}, {"deletedTime", type text}, {"environmentRegion", type text}, {"tenantGuid", type text}})
in
    #"Changed Type"
in
    Source
```

- Transform app file:
```
let
    Source = (Parameter as binary) => let
    Source = Table.FromColumns({Lines.FromBinary(Parameter)}),
    #"Transformed Column" = Table.TransformColumns(Source, {"Column1", Json.Document}),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Transformed Column", "Column1", {"resourceId", "environmentId", "type", "subType", "DocumentVersion", "name", "description", "uri", "tenantId", "lifecycleState", "owner", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "lastEnabledTime", "lastEnabledPrincipalId", "sharedUsers", "sharedGroups", "appPlanClassification", "bypassConsent", "canConsumeAppPass", "sharepointFormURL", "status", "almMode", "usesDataverseTables", "dlpEvaluationStatus"}, {"resourceId", "environmentId", "type", "subType", "DocumentVersion", "name", "description", "uri", "tenantId", "lifecycleState", "owner", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "lastEnabledTime", "lastEnabledPrincipalId", "sharedUsers", "sharedGroups", "appPlanClassification", "bypassConsent", "canConsumeAppPass", "sharepointFormURL", "status", "almMode", "usesDataverseTables", "dlpEvaluationStatus"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1", {{"resourceId", type text}, {"environmentId", type text}, {"type", type text}, {"subType", type text}, {"DocumentVersion", type any}, {"name", type text}, {"description", type text}, {"uri", type text}, {"tenantId", type text}, {"lifecycleState", type text}, {"owner", type text}, {"createdTime", type datetime}, {"createdPrincipalId", type text}, {"lastModifiedTime", type datetime}, {"lastModifiedPrincipalId", type text}, {"lastEnabledTime", type datetime}, {"lastEnabledPrincipalId", type text}, {"sharedUsers", Int64.Type}, {"sharedGroups", Int64.Type}, {"appPlanClassification", type text}, {"bypassConsent", type text}, {"canConsumeAppPass", type any}, {"sharepointFormURL", type any}, {"status", type any}, {"almMode", type any}, {"usesDataverseTables", type any}, {"dlpEvaluationStatus", type any}})
in
    #"Changed Type"
/*let
    Source = (Parameter as binary) => let
    Source = Text.FromBinary(Parameter),
    #"Imported JSON" = Replacer.ReplaceText(Source, "}", "},"),
    #"Trim last character" = Text.Trim(#"Imported JSON", ","),
    #"Insert bracket" = Text.Insert(#"Trim last character", 0, "["),
    #"Insert second bracket" = Text.Insert(#"Insert bracket", Text.Length(#"Insert bracket"), "]"),
    #"Parsed JSON" = Json.Document(#"Insert second bracket")
  /*  #"Navigation 1" = #"Parsed JSON"{0}
    #"Converted to table" = Record.ToTable(#"Navigation 1"),
    #"Transposed table" = Table.Transpose(#"Converted to table"),
    #"Promoted headers" = Table.PromoteHeaders(#"Transposed table", [PromoteAllScalars = true]),
    #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"resourceId", type text}, {"environmentId", type text}, {"type", type text}, {"subType", type text}, {"DocumentVersion", type text}, {"name", type text}, {"description", type text}, {"uri", type text}, {"tenantId", type text}, {"lifecycleState", type text}, {"owner", type text}, {"createdTime", type datetime}, {"createdPrincipalId", type text}, {"lastModifiedTime", type datetime}, {"lastModifiedPrincipalId", type text}, {"lastEnabledTime", type datetime}, {"lastEnabledPrincipalId", type text}, {"sharedUsers", Int64.Type}, {"sharedGroups", Int64.Type}, {"solution", type any}})
in
  #"Parsed JSON" */
in
    Source
```

- Transform flow file:
```
Source = (Parameter as binary) => let
    Source = Table.FromColumns({Lines.FromBinary(Parameter)}),
    #"Transformed Column" = Table.TransformColumns(Source, {"Column1", Json.Document}),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Transformed Column", "Column1", {"resourceId", "type", "subType", "name", "tenantId", "environmentId", "resourceVersion", "lifecycleState", "events_created_timestamp", "events_created_principalId", "events_modified_timestamp", "sharedUsers", "sharedGroups", "workflowEntityId", "flowSuspensionReason", "templateName", "flowFailureAlertSubscribed", "sharingType"}),
     #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1", {{"resourceId", type text}, {"environmentId", type text}, {"type", type text}, {"subType", type text}, {"name", type text},  {"tenantId", type text}, {"lifecycleState", type text}, {"resourceVersion", type text}, {"events_created_timestamp", type datetime}, {"events_created_principalId", type text}, {"events_modified_timestamp", type datetime}, {"sharedUsers", Int64.Type}, {"sharedGroups", Int64.Type}, {"workflowEntityId", type text}, {"flowSuspensionReason", type text}, {"templateName", type text}, {"flowFailureAlertSubscribed", type text}, {"sharingType", type text}})
 
in
    #"Changed Type"
in
    Source
```
- Transform environment file:
```
let
    Source = (Parameter as binary) => let
    Source = Table.FromColumns({Lines.FromBinary(Parameter)}),
    #"Transformed Column" = Table.TransformColumns(Source, {"Column1", Json.Document}),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Transformed Column", "Column1", {"environmentId", "environmentName", "isDefault", "environmentState", "environmentUrl", "environmentType", "securityGroup", "purpose", "cdsInstanceId", "cdsInstanceUrl", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "deletedTime", "environmentRegion", "tenantGuid"}, {"environmentId", "environmentName", "isDefault", "environmentState", "environmentUrl", "environmentType", "securityGroup", "purpose", "cdsInstanceId", "cdsInstanceUrl", "createdTime", "createdPrincipalId", "lastModifiedTime", "lastModifiedPrincipalId", "deletedTime", "environmentRegion", "tenantGuid"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1", {{"environmentId", type text}, {"environmentName", type text}, {"isDefault", type logical}, {"environmentState", type text}, {"environmentUrl", type text}, {"environmentType", type text}, {"securityGroup", type text}, {"purpose", type text}, {"cdsInstanceId", type text}, {"cdsInstanceUrl", type text}, {"createdTime", type datetime}, {"createdPrincipalId", type text}, {"lastModifiedTime", type text}, {"lastModifiedPrincipalId", type text}, {"deletedTime", type text}, {"environmentRegion", type text}, {"tenantGuid", type text}})
in
    #"Changed Type"
in
    Source
```

Can you please assist and help us find the source of an issue?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

January 2024

### What method are you using to get inventory and telemetry?

Data Export

AB#2181

**Comment by Jenefer-Monroe** [comment]
Thank you for investigating so thoroughly! 
I suggest you do the following:

1. Revert all the changes you've made so that you are in a clean state as of Jan release. 
2. Update the Environment dataflow as shown here: https://github.com/microsoft/coe-starter-kit/issues/7562#issuecomment-1916812148
3. Delete all the history in the DataflowRefreshHistory table.
4. Manually refresh the Makers table. 

Then see if you have the correct data. 

A few other notes. 
- More system users is a known product bug. Please see https://github.com/microsoft/coe-starter-kit/issues/6658
- The rollup fields in that chart can take time to resolve. I suggest checking in the tables themselves to start with and we can explore if they broke for you after we know if your data is coming in.

**Comment by annsarP** [comment]
Hello! Thank you for providing information. We performed above steps (all dataflows have refreshed successfully two times since that time), all PA flows are still 100% successful as well but unfortunately data is still missing. Flows have owners but none of them is assigned to any Maker:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/414689ee-e7e6-4c28-be93-83abc29302e2)
However numbers of resources were updated. Number of bots in both Cloud flow CoE and Data export CoE is now the same, rest is still missing but differences are lower from what I can see. With such large amount of environments it's hard to tell which exact data is missing but based on for example list of Power Pages, other pages from missing page's environment are listed, so it's not like whole environment is missing. What else can I do to fix this issue? Should I contact Microsoft Support as well?

**Comment by Jenefer-Monroe** [comment]
Hello, sorry too many issues here to iterate at once. I'm having trouble tracking what is from where, can we please take these one at a time? I suggest you find a case where an object is missing from either of your installs and we can iterate on that.

Note that there is a known issue with MDAs for Data Export, they do not return the Maker correctly from the Datalake.

**Comment by annsarP** [comment]
Sorry for confusing comment. We have 2 open cases right now
1. No flow is assigned to any Maker - is it because of mentioned known issue with MDAs for Data Export?
2. Missing data (apps, flows, power pages) - We have two CoE environments (one with cloud flows as a data source and second with data export as a data source) and we are comparing Power Platform Admin View apps from both environments. We found out that we have hundreds of apps and flows missing from CoE environment with data export as a source. Actually since I noticed amount of apps and flows is growing I think that this maybe connected to the known Data Export limitation regarding amount of data: 
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/17bcbaff-3711-47cf-b8f2-f882ae5ddc81)
We performed initial export at the end of January and I think the full data might be just not exported yet.

**Comment by Jenefer-Monroe** [comment]
### No flow is assigned to any Maker
This is just from that dashboard view yes? 
If you go look at the flows themselves they have a maker yes? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4ab5731f-358b-4b5a-a625-47457221ff98)

If so you are having issues with the rollup. Here is some help for that:
### Roll up field help
These fields are roll up fields and so for a new install they take a while to update. It’s typically a 12 hour wait after the inventory completes before you can expect to see these populate but the product itself is what determines how frequently and when to update these roll up fields.
You can force these to calculate. Please see the tip in this product team article on [Rollup columns](https://learn.microsoft.com/power-apps/developer/data-platform/calculated-rollup-attributes#rollup-columns)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d374b7dc-82e2-499d-8855-be81a70bdb98)
If its been a while since install and you still see zeros, it could be that the rollups broke or got deactivated somehow. Please [View Rollup Jobs](https://learn.microsoft.com/power-apps/maker/data-platform/define-rollup-fields#view-rollup-jobs) and see their state.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/50ca6f07-dc57-4188-8db6-47198478608b)

**Comment by Jenefer-Monroe** [comment]
For the Data Export, as described above, there was an issue with Data Export changes made in Jan, a fix will release with the March built next month. I suggest you continue using the Cloud Flow pattern for now, and then when the March release ships, try setting up the Data Export again.

**Comment by annsarP** [comment]
Hello, 
I can see that every day lists of apps and flows are growing. Yesterday app created on December appeared on the list which makes me think we still have to wait a couple of days  for a full data export due to some limitations. Looking forward for a March release as well! Until then we will monitor the data. 
Regarding missing Maker on rollup columns - totally correct. DerivedOwners are assigned to each flow, the only thing that is missing is calculation in Makers table and empty chart. I checked system jobs and they are running without any failures:
![image](https://github.com/microsoft/coe-starter-kit/assets/127112137/6a57c16a-b140-4be9-8076-efc739673d65)

**Comment by Jenefer-Monroe** [comment]
OK I'm not sure why the rollup isnt working for you. Unfortunately that is just a product feature we use, not something we made. So you may need to reach out to product support to deduce why its not working.

**Comment by annsarP** [comment]
I see, thank you for reviewing the case, we will keep monitoring it and reach out to Microsoft Support if required!  😊
