### ISSUE TITLE
[CoE Starter Kit - BUG] DCC Re-publish button not working

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#7577]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Several users have found the Re-publish button in the DCC doesn't work. Example below

![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/068d30cc-8ebc-4f8b-8dab-2534151ece1c)

### Expected Behavior

Clicking the Re-publish button should republish the app.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.14

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the DCC
Click the 'Re-publish needed' tab
Select an app
Click the Re-publish button

AB#2183

**Comment by Jenefer-Monroe** [comment]
Yes this is a poor message. Will take an as issue thanks for posting.

**Comment by Jenefer-Monroe** [comment]
ok looks like we dont clean this anywhere. I'll look into the inventory system for where to do that.

**Comment by Jenefer-Monroe** [comment]
Flagging app to go through inventory when you hit cancel
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6b4c2c98-700b-4446-b0ff-62ed66b2ebc9)

**Comment by MartinWGT** [comment]
Thanks Jenefer. So when the fix is made will the re-publish button re-publish the app? Currently it isn't re-publishing those that it says need re-publishing.
