### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why use PBI Dataflow in Data Export version?

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#7578]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,
why is the reason to have a PBI dataflow using Data Export version?

We already have dataflows in the environment to gathered all information and the PBI dashboard could use dataverse.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

January 2024

### What app or flow are you having the issue with?

PBI

### What method are you using to get inventory and telemetry?

Data Export

AB#2184

**Comment by Jenefer-Monroe** [comment]
This was a design decision to avoid the flow and storage requirements for some features like usage and connections. 
So there are some data points like those not stored in the Dataverse tables for BYODL users.  
Hope that makes sense.

**Comment by albertocastro365** [comment]
Yes, I have already seen that there is information in pbi dataflow that is not in the dataverse tables, but wouldn't it be more efficient to have all the information in dataverse and point the pbix to those tables?
Furthermore, this would allow us not to depend on pbi dataflows and avoid use premium licenses.
Don't you think that this scenario would have more sense?
All dataflows and data in the same location (CoE Environment), only unique datasource, better sync...

**Comment by Jenefer-Monroe** [comment]
Assuming we have to do something of a rewrite when Data Export goes to GA, we can consider this path instead. 
It really depends on the API hit of gathering it all.

**Comment by albertocastro365** [comment]
Sorry, but what API do you mean?

**Comment by albertocastro365** [comment]
OK understood. If the time comes and you need help, you know you can count on me.
Thanks!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team for now
