### ISSUE TITLE
Number of model driven app users.

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#7579]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I can see canvas app users in the auditlog table plus there is the ''launches in the past 30 days' column in App table. Is there any way to see this info for Model Driven apps ?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Data Export

AB#2187

**Comment by Jenefer-Monroe** [comment]
Unfortunately there are blocking bugs yet in the Data Export files which limit our ability to do this. As the Data Export feature completes its work and goes to GA we will be able to consume this.

**Comment by jimpreston29** [comment]
Thanks ! if there is any estimate timeline, please advise

**Comment by Jenefer-Monroe** [comment]
Unfortunately I don't have an estimate, its dependent on the product team's planning and work. But you can track here: https://learn.microsoft.com/power-platform/admin/self-service-analytics where it will be noted when its going to GA.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
