### ISSUE TITLE
Invalid type. Expected String but got Null.

### ISSUE THREAD

**Issue by cavando** [microsoft/coe-starter-kit#7582]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flows:
Admin | Sync Template v4 (Portals)
CLEANUP HELPER - Check Deleted v4 (Portals)

Error Screenshots:
![image](https://github.com/microsoft/coe-starter-kit/assets/9001701/56640fb7-1b16-47a8-82f6-af6664d33aa8)
![image](https://github.com/microsoft/coe-starter-kit/assets/9001701/0101d370-074c-418f-89cd-1fee8dc5be95)

CoE Starter Kit Version:
![image](https://github.com/microsoft/coe-starter-kit/assets/9001701/a55cbd2e-de15-4fba-998b-b132d66a73bc)

### Expected Behavior

There should be no errors when parsing inventory on flows: "Admin | Sync Template v4 (Portals)", and "CLEANUP HELPER - Check Deleted v4 (Portals)".

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Portals) and CLEANUP HELPER - Check Deleted v4 (Portals)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2189

**Comment by Jenefer-Monroe** [comment]
This is corrupt data in your table. Can you please go to the portal table in the CoE and delete records that have null in this column? Then this will pass, and we can see if the corrupt ones return.

**Comment by cavando** [comment]
> This is corrupt data in your table. Can you please go to the portal table in the CoE and delete records that have null in this column? Then this will pass, and we can see if the corrupt ones return.

That seems to have fixed the issue, thank you.
