### ISSUE TITLE
[ALM Accelerator - BUG]: Conditional Access policy defined by....

### ISSUE THREAD

**Issue by ccab247** [microsoft/coe-starter-kit#7583]
### Describe the issue

I have an issue where I am just trying to search for the projects within a DevOps area but I get the following error:

![image](https://github.com/microsoft/coe-starter-kit/assets/158636802/b5d4439a-4a57-404e-ae1a-15e7cd237b66)

### Expected Behavior

I should be able to just load the projects but this error is preventing me. If it's a setting in the DevOps, can someone point me out to this?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20240104.1

### Steps To Reproduce

Clicking on the Projects Under Azure DevOps in the ALM Accelerator for Power Platform App.

### Anything else?

N/A

AB#2190

**Comment by v-bjaiswal** [comment]
Hi @ccab247 ,can you Test the connection of your custom connector "CustomAzureDevOps"? and see if you are getting 200 response. 
![image](https://github.com/microsoft/coe-starter-kit/assets/102227309/29ab1e9c-bcab-47d9-8abb-f9f5a7297139)

**Comment by ccab247** [comment]
I do get a 200 response but when I go further is when I get the issue.

**Comment by v-bjaiswal** [comment]
Hi @ccab247 , can you check if any DLP policy has been configured into your environment. It might be preventing you to access project list.

**Comment by ccab247** [comment]
Is it possible to use a service principal to access instead of an account?

**Comment by ccab247** [comment]
@v-bjaiswal would I be able to use a service principal here instead of the account? The blocks using an account for their cap policy is a restriction. They want to be able to use the service principal to access. I added the check box for "Enable Service Principal Support" as well.

**Comment by v-bjaiswal** [comment]
Hi @ccab247 ,No the app is running under the running user context so you cannot use the service principle to access the app.
And also, upon checking i found out this feature is in public preview so please configure appropriately with respect to that.
Below is the article which can we used as a reference of its public preview.
https://powerapps.microsoft.com/en-us/blog/public-preview-of-new-custom-connector-enhancements/

**Comment by v-bjaiswal** [comment]
Closing this ticket. Please raise the new ticket if any issue persists or you have any query regarding other issue. Thank you.
