### ISSUE TITLE
[CoE Starter Kit - QUESTION] PVA Usage Data missing for certain days

### ISSUE THREAD

**Issue by Bezanca** [microsoft/coe-starter-kit#7586]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, I'm missing PVA Usage data for a period of 2 weeks. I've tried re-running the PVA Usage flow but if I'm understanding that flow correctly, it looks for the previous days PVA Usage data only. 
Is there a way get the PVA usage data for certain dates please?
Thanks for any assistance.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 23

### What app or flow are you having the issue with?

Admin | Sync Template v3 (PVA Usage)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2194

**Comment by Jenefer-Monroe** [comment]
You could go edit this flow temporarily. Right now it's set to go back 1 day, but you could change that 1 to a 30 (or whatever you need) and run it, then remove the unmanaged layer to get back to the regular flow runs. 
From looking at it, I dont think it will make duplicates as a result of this. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6f4c5021-986f-4f64-bb3e-a60620896368)

**Comment by Bezanca** [comment]
Thanks for the suggestion Jenefer. I have given that a go but not had much success.
I set the value to 14, saved and ran the flow. It ran successfully without errors, but it seems to have just duplicated yesterdays entry in the PVA Usage section for each chatbot. Odd that its only duplicated yesterdays and not the previous 14 days.

**Comment by Jenefer-Monroe** [comment]
Have you gone to the table in that environment and seen if additional records exist?

**Comment by Bezanca** [comment]
Hey Jenefer, yes i've checked and they do exist. Although when the PVA usage flow ran Initially there was an issue with the tables that Microsoft fixed. The PVA Usage flow never failed, I just think there was nothing there to find.

I have just spotted a way to manually enter the PVA usage into the CoE Starter Kit by clicking the 'New PVA Bot Usage' button. This is hopefully a one off so i'm happy to do that.

![image](https://github.com/microsoft/coe-starter-kit/assets/158779776/806d24c7-3da3-4dac-8145-d19faca6c9a8)

**Comment by Jenefer-Monroe** [comment]
Wonderful. Thanks for finding a workaround for yourself and letting me know what happened!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
