### ISSUE TITLE
[CoE Starter Kit - BUG] Command Center App > Get M365 Service Messages - Flow not turning on and Import of ALM Accelerator with warning

### ISSUE THREAD

**Issue by DheekshaSivaraj** [microsoft/coe-starter-kit#7588]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Error message :
Turn on failed. Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ApiPolicyDataFlowViolation","message":"Admin data policy 'COE upgrade DLP' restricts the use of /providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps with Http.","extendedData":{"violation":{"policyId":"/providers/Microsoft.BusinessAppPlatform/scopes/service/apiPolicies/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","policyDisplayName":"COE upgrade DLP","type":"BusinessAndNonBusinessConnector","parameters":["/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps","Http"]},"additionalInfo":{"adminContactEmailAddress":"[xxxxxxxxxxx@yyyy.com](mailto:xxxxxxxxxxx@yyyy.com)","policyWikiUrl":"[https://collaboration.xxx.com/sites/xxx-test-powerplatformhub](https://urldefense.com/v3/__https:/collaboration.xxxx.com/sites/xxxx-test-powerplatformhub__;!!OrxsNty6D4my!4BplKGfe4WA0WIAWbGPADdUdsV076CEJeMXenPRmwZ5ZthFIH-TkOQYXfpTD6gL-X8Elaf2hLCwaJx02Vs1muKGATJF2Nffxd3w$)"}}}}".

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Add Maker to Group and Command Center App > Get M365 Service Messages

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2196

**Comment by Jenefer-Monroe** [comment]
Hello. This error indicates that you have a DLP policy which conflicts with the required connectors in the CoE solution for the envt. 

From the error message it appears to be a problem with the **_COE upgrade DLP_** policy although there may be others impacting the environment as well. 

Note, you can always find our latest required DLP requirements in our documentation: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by DheekshaSivaraj** [comment]
Hi, I have all the connectors enabled in the DLP policy as per link: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies. Still getting this error.
Kindly help!
