### ISSUE TITLE
[CoE Starter Kit - BUG] cannot log into PowerBI dashboard

### ISSUE THREAD

**Issue by Ramazancz** [microsoft/coe-starter-kit#7590]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

While signing There is unexpected error occuring. Help please

![image](https://github.com/microsoft/coe-starter-kit/assets/137779034/52e06b9e-87b7-433f-8bbf-c6de92efb168)

![image](https://github.com/microsoft/coe-starter-kit/assets/137779034/1321fb30-2c08-4b14-bd3e-c2579a339028)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Production_CoEDashboard_January2024.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2198

**Comment by RahulBojji** [comment]
@Ramazancz Looks like you are entering incorrect url. Please go to [PowerPlatformAdminCenter](https://admin.powerplatform.microsoft.com/) -> Open the environment in which COE kit is installed -> Copy environment url and append https:// before the url if https not present. Please look into [this ](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#get-the-environment-url) for more information.

<img width="641" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/bba8e0a1-8af4-431a-b8df-33b67980c233">

**Comment by Ramazancz** [comment]
@RahulBojji Thank you this solved my issue
