### ISSUE TITLE
[CoE Starter Kit - QUESTION] License only part of it

### ISSUE THREAD

**Issue by Pharosz** [microsoft/coe-starter-kit#7591]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a best practice on how to partially license COE for end users? Everyone is using the free Automate/App license and we don't want to purchase thousand of per flow/app licenses. We would only need end user have access to use the Inactivity process and the Cleanup for Orphaned Resources. Are there real world experiences on someone did it without licensing all the company?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.17

### What method are you using to get inventory and telemetry?

None

AB#2199

**Comment by Jenefer-Monroe** [comment]
As long as the users respond to the inactivity approval mails and the orphan teams chats, then there is no premium license required. However if they want access to view the apps they will need premium license as the apps use the Dataverse connector. 
There are per-app licensing options as well if you decide there is a particular app you want to share broadly. [About Power Apps per app plans](https://learn.microsoft.com/power-platform/admin/about-powerapps-perapp)
Hope that helps.

**Comment by Pharosz** [comment]
Hi @Jenefer-Monroe , Sounds good, so in this case only per app license will be needed and not the per flow one?

**Comment by Pharosz** [comment]
Thank you, I will test it with a normal user and see how far we can get with a free license.
I guess the majority of companies using COE use per app licenses, too bad its not a free or coming by default with the Admin Center... maybe at some point? :)

**Comment by Jenefer-Monroe** [comment]
Yes, the kit is really just a starter kit to get the product time to iterate. If you look at the product's [managed environments](https://learn.microsoft.com/power-platform/admin/managed-environment-overview) you will see their work.
