### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is it possible to exclude users from inactivity flows?

### ISSUE THREAD

**Issue by tomtech1** [microsoft/coe-starter-kit#7594]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have some high-usage makers with over 300 resources each, and I would like to know if it's possible to exclude these users from the inactivity flows so they don't get spammed with notifications upon enabling.

Thanks

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Inactivity flows

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2209

**Comment by Jenefer-Monroe** [comment]
It is not today, no. We do have this on the backlog for when we do the Inactivity rewrite though, please see https://github.com/microsoft/coe-starter-kit/issues/6266
