### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Power Platform Admin View

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#7596]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

App Last Launched On" of Power Apps and "Flow Last Run ON" of Power Automate are not obtained.
What is Power Automate to get?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2024/1

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2213

**Comment by RahulBojji** [comment]
@asuka1103131 Can you please confirm which mechanism are you using to get this information. Is it via Cloud flows or Data Export Service ??

**Comment by asuka1103131** [comment]
@RahulBojji 
Retrieved via cloud flow.

**Comment by RahulBojji** [comment]
@asuka1103131 **Flow Last Run** is available only via Data export feature. Please have a look at [this](https://github.com/microsoft/coe-starter-kit/issues/7232) for more info.

**Comment by RahulBojji** [comment]
For "**App Last Launched Date**"

Please go to the details page on this flow. Are the flows running and passing?

![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/834fcd44-2eb2-4562-b397-57a4f1cb0871)


If so, open one of the runs and look for a filter event that has a "LaunchPowerApp" event

![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/8d562b8b-4b03-45ea-9427-0729ddeaf2d4)

Find that iteration in the loop and see where it falls here.


![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/2268b7cc-8e66-4181-94fd-ab67495ce5e2)

If everything looks fine, Do you have access to view the audit logs directly? https://compliance.microsoft.com/auditlogsearch?viewid=Async%20Search
If so please see if you find launches there.

**Comment by asuka1103131** [comment]
@RahulBojji 
Is the data export functionality the same functionality that uses Azure?

**Comment by asuka1103131** [comment]
@RahulBojji 
Could not turn on Admin | Audit Logs | Sync Audit Logs (V2) because the environment variable was not set.
What should I set for 'admin_AuditLogsAudience'?

**Comment by RahulBojji** [comment]
Please look at the official [documentation ](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#create-a-microsoft-entra-app-registration-for-the-office-365-management-api)

<img width="715" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/1268230d-701a-4534-9271-029eb3d8b0cc">

**Comment by asuka1103131** [comment]
@RahulBojji 
I was able to run it, but it outputs an error.
Can you tell me the cause of the problem?

![image](https://github.com/microsoft/coe-starter-kit/assets/156406138/6b9d7ca2-b671-4c42-84d3-4a34bd0b1174)

**Comment by Jenefer-Monroe** [comment]
Hello, per our [limitatons doc]( https://learn.microsoft.com/power-platform/guidance/coe/limitations#supported-languages), the CoE Starter Kit solutions are not localized, and only support English. Add the English language pack to your environment to make sure all apps and flows work. More information: [Regional and language options for your environment](https://learn.microsoft.com/en-us/power-platform/admin/enable-languages)
![image](https://user-images.githubusercontent.com/89584709/224966722-dd5d48e7-780d-46cb-b6ae-507318f03ad2.png)

**Comment by asuka1103131** [comment]
@RahulBojji 
Do you get the "App Last Launched On" for Power Apps via Power Automate?

**Comment by Jenefer-Monroe** [comment]
That field is not filled for the Sync Flow architecture, it is a Data Export only field.

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
Is there an additional cost for switching to data export?
