### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - Check users who have not used their license in long time in CoE toolkit

### ISSUE THREAD

**Issue by AakashKumar5066** [microsoft/coe-starter-kit#7597]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We need to check how many users in our organization have License but are not using it anymore. They tried building an app but have left the platform and we can take the licenses back.

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

AB#2214

**Comment by Jenefer-Monroe** [comment]
Unfortunately we dont have programmatic access to license information to use to build this feature for the kit.
I suggest you provide this request to the product team in whatever channels you have, or via https://powerusers.microsoft.com
 if you dont have any direct channels. The more people request it the more likely we are to get it!
