### ISSUE TITLE
Get all share point connected flows

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#7599]
### Is your feature request related to a problem? Please describe.

There are times when it would be great to have a List of all the Flows deployed on a SharePoint List/Library. This makes the users to know which flow is connected to share point site and he can make decision on removing or holding the flow as a part of Governance.

### Describe the solution you'd like

It would be great if we can get the feature to get all the list of the flows connected to the share point site/list.

AB#2217

**Comment by Jenefer-Monroe** [comment]
Hello. We do have a field which tracks the referenced resources in a flow. You can add this column and filter to see what is in there:
Unfortunately it the value used is a variable the product does not return it and we will see [DYNAMIC_VALUE] instead.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b057b2f3-4d0c-4688-a2ba-ca2470eea7b6)

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/623be2f8-d26e-4de4-a718-8e4c132763bf)

**Comment by Neel1KNK** [comment]
That was awesome, thanks Jenefer for letting me know about that. 

I found the app and was able to see the flows connected to the share point site.

Here my asks are like:

Dose it gives only info about the Share point triggers associated with flows or even if the flow having the share point action lists up??

I am facing issue like unable to get all the share point sites associated with the flows.

Please help me on this.
Thanks

**Comment by Jenefer-Monroe** [comment]
We use whatever is returned by the product in the Get Flow as Admin call. 
To my recollection this is for both triggers and calls like these
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fdf9a936-514d-4d2d-b40d-a84e83df22a5)

**Comment by Neel1KNK** [comment]
Jenefer, can you please give me more detail about this flow so that I deep dive and check my flow current status.
Thanks

**Comment by Jenefer-Monroe** [comment]
This is in the **_SYNC HELPER - Cloud Flows_** flow in the **_Referenced Resources_** scope.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3cb72f7e-73d8-485d-bf6e-2e2e776a75ce)

**Comment by Neel1KNK** [comment]
I see all those flows running successfully but still it not getting complete details. Do I need to check any of the flows to fetch more details??

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not sure what you mean. Are you saying its missing some flows? Or missing some SP references? 

Please take a flow where you are expecting to see SP data but do not, and run it through this flow as shown here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b049a697-54f4-4961-ae3b-7398b611541c)

What do you see?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4dbe236e-aa06-48b3-a3b9-8d80b33e66a2)
