### ISSUE TITLE
[CoE Starter Kit - BUG] Apps and Flow inventory does not have all the inventory

### ISSUE THREAD

**Issue by nrd2015** [microsoft/coe-starter-kit#7600]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Dear Team,

We have recently updated to the January release and have BYODL configured. We have noticed some discrepancy in the count of Apps//flows/Desktop Flows. The apps and flows inventory does not contain all all the apps/flows that are being created.

We have run the update wizard multiple times now. Can you please advise if I am missing anything ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows);Admin | Sync Template v4 (Apps)

### What method are you using to get inventory and telemetry?

None

AB#2218

**Comment by Jenefer-Monroe** [comment]
Unfortunately we shipped with a bug in the Jan release that impacts BYODL for Default envts. 

To local fix:

1. Update the Environment dataflow as shown here: https://github.com/microsoft/coe-starter-kit/issues/7562#issuecomment-1916812148
2. Delete all the recent history in the DataflowRefreshHistory table (since ~week before you upgraded)
3. Manually refresh the Makers table.

**Comment by nrd2015** [comment]
Hi @Jenefer-Monroe , Thank you for the quick response. Can you please confirm if you want me to delete all the rows in the "DataflowRefreshHistory" table since the upgrade ?

**Comment by nrd2015** [comment]
Hi @Jenefer-Monroe , I have performed the steps advised above. The default environment is not marked as deleted now, but the apps, flows in the default environment that were created after the CoE upgrade do not show up in the "[Power Platform Admin View" app.

**Comment by Jenefer-Monroe** [comment]
Can you confirm, do your "Next Refresh" options look like this? Only auto-refreshing Maker? (The rest get triggered by a flow run in progressions after Maker runs)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc968f0f-9f46-4ede-9a61-574695d83428)

**Comment by nrd2015** [comment]
Hi @Jenefer-Monroe , Yes it looks as above

<img width="796" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/12375029/0b093c69-179f-4f45-b9b2-73fac3cc0caa">

**Comment by nrd2015** [comment]
HI @Jenefer-Monroe ,

I see that the lot of the apps and flows are now showing up under the "Deleted Apps" or "Deleted Flows" view. They were probably marked as deleted when the default environment was marked as deleted. How do I revert it ? Can I just revert the "App Deleted" or "Flow Deleted" column ?

**Comment by Jenefer-Monroe** [comment]
The Check Deleted flow should repair this for you. And if it doesnt you casn export the data to edit in Excel and fix it up there.

**Comment by nrd2015** [comment]
Hi @Jenefer-Monroe ,

Thank you. I was able to revert the apps/flows marked as deleted. However, there are still apps that are not showing in the "Power Platform Admin View" app. Can you please advise the next steps ?

**Comment by Jenefer-Monroe** [comment]
Did you revert that by running the Check Deleted flow?

**Comment by nrd2015** [comment]
Hi @Jenefer-Monroe ,

Yes. 

I have verified that the missing app(s) are not present in the "admis_app" table. So I believe it is not picked up by the inventory flows.

**Comment by Jenefer-Monroe** [comment]
They are not present, or they are present and marked deleted?

**Comment by nrd2015** [comment]
They are not present in the "admin_app" table.

**Comment by Jenefer-Monroe** [comment]
ok we have made some changes to the dataflows for the MArch release. I suggest you wait for that upgrade and see if this is resolved for you

**Comment by nrd2015** [comment]
Thank you. I will wait for the March release.
