### ISSUE TITLE
[CoE Starter Kit - BUG] Update URL in the description for Flow Approvals URL: flow.microsoft.com vs flows.microsoft.com

### ISSUE THREAD

**Issue by gxgrammatikos** [microsoft/coe-starter-kit#7603]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The URL in the sentence "To get the URL, go to **flows.microsoft.com** for your CoE environment > Action Items > Approvals" should be updated to **make.powerautomate.com**

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.14

### What app or flow are you having the issue with?

Compliance process

### What method are you using to get inventory and telemetry?

None

AB#2222

**Comment by RahulBojji** [comment]
@gxgrammatikos When you navigate to "**flows.microsoft.com**" it automatically redirects to "**make.powerautomate.com**". Any way thanks for posting this. We will look into this.

**Comment by gxgrammatikos** [comment]
@RahulBojji Thank you for your response. That's what I expected, but as you can see from the screenshot, it doesn't happen. I tried it from different browsers and devices.

Please check the screenshot below:

![image](https://github.com/microsoft/coe-starter-kit/assets/10853004/0b8c5b63-a576-488c-b5c4-bd8c0616eeee)

**Comment by RahulBojji** [comment]
its "flow.microsoft.com" not flows can you try once with "flow.microsoft.com"

**Comment by gxgrammatikos** [comment]
@RahulBojji Τhe document needs to be updated because the url starts with flows and not flow.

![image](https://github.com/microsoft/coe-starter-kit/assets/10853004/5bb16df6-0d2a-4c14-88cc-c59a664f4c5a)

**Comment by gxgrammatikos** [comment]
Thank you @RahulBojji

**Comment by RahulBojji** [comment]
Re-opening this bug for us to track

**Comment by RahulBojji** [comment]
@Jenefer-Monroe FYI

Rajeev has created a PR for this and its been updated on the docs as well. 

<img width="446" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/1fb66d64-0bbf-425b-a0a5-75f39d34fd37">

Closing out as no further action for starter kit team
