### ISSUE TITLE
[CoE Starter Kit - BUG] Apps not showing correct numbers

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#7605]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We see that the apps are not showing correct numbers only showing 650 apps where as the actual number is 5000+, although the Dataflows are completing the refresh. We have applied the fix for default env being shown deleted. Although we still do not see the correct numbers.

### Expected Behavior

The numbers should be correct

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

BYOD Apps

### What method are you using to get inventory and telemetry?

Data Export

AB#2224

**Comment by Jenefer-Monroe** [comment]
You will also need to delete the dataflowhistory back to before you isntalled the Jan release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
