### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cross Tenant Connection References data for Tenant Isolation

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#7607]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are looking at turning on Tenant Isolation for our company as per recommendation of Microsoft. 

During our pre-checks, we are using the data from **Power Platform Admin View** > **Connection Identities** > **Cross Tenant Connection References** to identify possible issues when we turn on Tenant Isolation.

My questions are:
1. Is it accurate to use this data to check possible issues for turning on Tenant Isolation?
2. If yes, where are the data coming from? How does it determine if a connection reference is Cross Tenant?

Thank you for your help.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2230

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
