### ISSUE TITLE
[ALM Accelerator - BUG]: Pipeline token expires during execution if import/upgrade/data import steps take a long time

### ISSUE THREAD

**Issue by BJHF-power** [microsoft/coe-starter-kit#7608]
### Describe the issue

During a deploy-* pipeline run, the token generated at the beginning of the pipeline run can expire if the Import Solution, Apply Upgrade, or Import Configuration Migration Data tasks take over an hour (or any other task, but these tend to be the lengthiest).

This causes 401 Unauthorized errors in subsequent tasks and the pipeline fails. Example:
![image](https://github.com/microsoft/coe-starter-kit/assets/106766774/de18a1ad-1fbf-43db-8e69-ef793097e805)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

November release

### Steps To Reproduce

Run a deploy-* pipeline with a very large solution that takes 1hr+

AB#2232

**Comment by RajeevPentyala** [comment]
@BHJF-power Please note that we have made updates to the deployment pipelines with [Stage-and-upgrade](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/solution#--stage-and-upgrade--up) action. This action now performs both the import and upgrade of the solution in a single step, as opposed to the previous two-step process. We anticipate that this enhancement will contribute to an improvement in the overall pipeline runtime. 
This fix will be included in the upcoming March-24 release.
