### ISSUE TITLE
[CoE Starter Kit - BUG] Turning a flow off fails because of invalid connections

### ISSUE THREAD

**Issue by rooobeert** [microsoft/coe-starter-kit#7609]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have tried to turn off Flows from the Power Platform Admin View, but I get an error that my connection is not valid. I have checked if any of my actual Connections have an error or are expired.

Which flow is responsible for turning off Flows? I can check there as well.

![image](https://github.com/microsoft/coe-starter-kit/assets/87785803/a6e1aed8-938d-4645-9cb4-4ab6d69ce8cb)

EDIT: Deleting a flow works totally fine.

### Expected Behavior

The loading screen starts and the flow is turned off. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. In the Power Platform Admin View open Flows
2. Open the Details of any Flow
3. On the action bar click Turn Flow off
4. Confirm by Stop flow

AB#2233

**Comment by Jenefer-Monroe** [comment]
This is the flow that is used to turn flows on and off from the apps: **_Command Center App > Set CoE Flows State_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/660bdc27-dd4c-4ab8-83d7-3219647884c3)

You can also check on the connection reference it uses to see if the connection references have a good connection by going to the default solution
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4b769bfd-b13e-4fd4-8509-5a52bded3de1)

**Comment by rooobeert** [comment]
I have check both the connection references and the flow itself. I added a new connection inside the reference, same issue. I tried to manually start the flow with the correct inputs, works fine as well. 

The flow does not seem to get startet at all. Im using the the account with which the CoE was installed.

**Comment by Jenefer-Monroe** [comment]
Sorry there are two flows involved here so I'm a little confused

Command Center App > Set CoE Flows State
- Can this flow be turned on?
- Can this flow run?

Target Flow (that you were trying to turn on / off with the above)
- Can this flow be turned on manually?

**Comment by rooobeert** [comment]
Maybe I didn't understand fully the process. But I had to give Edit permissions to my user in order to turn off that flow. Is that the correct way?

I thought, as a Power Platform Administrator, I am able to use the Power Automate Actions to access all flows. Basically that's what I did, manually running the flow to turn off my example flow, and that worked without any issues.

**Comment by Jenefer-Monroe** [comment]
Does your user identity have System Admin permissions in the envt of the target flow?

**Comment by rooobeert** [comment]
The user I'm signed in with is Power Platform Administrator and is assigned System Administrator, Maker, and Basic User in the environment. The flow is located in the default environment.

**Comment by Jenefer-Monroe** [comment]
Sorry to clarify, the user is System Administrator in the Default environment correct?

**Comment by rooobeert** [comment]
Yes. The user I'm signed in with is System Administrator in the Default environment.

**Comment by rooobeert** [comment]
Yes, the user ID in the error message exactly belongs to that user that I'm signed in with.

**Comment by Jenefer-Monroe** [comment]
ok I'm not sure then. You are definately hitting some product issue in that your connection is not working but I'm not sure how to resolve.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
