### ISSUE TITLE
CoE x Dataverse for Teams

### ISSUE THREAD

**Issue by jcgds** [microsoft/coe-starter-kit#7613]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, please, does COE work in a Dataverse for teams environment? I question this, because in my environment the total number of apps and flows remains zero, as shown in the attached image. Do I need to start a flow manually?
![DataverseForTeams](https://github.com/microsoft/coe-starter-kit/assets/147111987/e0b632a7-9b20-4ef5-bdd6-da4f63bb57de)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2237

**Comment by RahulBojji** [comment]
@jcgds If you are trying to install COE into teams environment it's not supported. But ideally you should be able to see the list of apps and flows in the teams environment. 
Can you please check if these flows are turned on **Admin | Sync Template v3 (Apps)** **Admin | Sync Template v3 (Flows)**

If these are turned on please check the run history for both the flows by adding "admin_displayname"

<img width="785" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/96c149f4-609c-4ce4-afbb-a16d83e10cc3">

Check if any data is returned for teams environment.

<img width="795" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/d9ae9cfb-de0d-4d38-ab6a-828b74caffe6">

**Comment by jcgds** [comment]
> **Admin | Sync Template v3 (Apps)** **Admin | Sync Template v3 (Flows)**

Hi RahulBojji, I'm not trying to install COE in teams environment. My flows are in version v4, Admin | Sync Template v4 (Apps) Admin | Sync Template v4 (Flows) and are active and collecting data from the DataverseForTeams environment as you can see in the images, however, until now the dashboard in Power Platform Admin View has not been updated as you can see in the image.
![1 1 Image](https://github.com/microsoft/coe-starter-kit/assets/147111987/61dbed83-c945-493a-ad0e-4a644d964120)

![1 2 Image](https://github.com/microsoft/coe-starter-kit/assets/147111987/e1a1b5ee-0bc5-4f50-a141-1f6c24f30f00)
![1 3 Image](https://github.com/microsoft/coe-starter-kit/assets/147111987/f6e1d293-eaa7-46f1-b49f-6f71385b9548)

**Comment by RahulBojji** [comment]
Can you check in the flows what values are being returned from the above actions by opening the run history in both the flows?

**Comment by Jenefer-Monroe** [comment]
Please find this envt in the Power Platform Admin View app and see what values the envt has for these fields:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/852e2253-8206-497e-9b54-b586849e4f31)

**Comment by jcgds** [comment]
Jenefer and RahulBojji, today the values appeared, collection is normal, thank you very much!
