### ISSUE TITLE
[CoE Starter Kit - BUG] Issue with loading data into Production_CoEDashboard_February2024

### ISSUE THREAD

**Issue by vel-ig** [microsoft/coe-starter-kit#7614]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I recently downloaded the latest pbi file Production_CoEDashboard_February2024, and received the attached error

<img width="530" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/108309708/5e744b19-b99b-46dd-ace8-0c4fc76b2fe8">

"The column 'admin_applogicalname' of the table wasn't found"

After closing the error, no data appears in this report. I also downloaded the PowerPlatformGovernance_CoEDashboard_February2024, and there's no issues with this report, data does appear. A
I've checked that all flows have been turned on in the COE kit Core solution and running successfully. I also can see data in the Power Platform Admin view app, so I don't believe this is an issue with any flows.

Any help would be greatly appreciated.

Thanks

### Expected Behavior

Expected to see data in the reports, however the query error that I'm experiencing appears to be blocking data from displaying

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February2024

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard_February2024

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Install COE kit as per instructions
2. Launch the "PowerPlatformGovernance_CoEDashboard_February2024" pbi file
3. Enter in the environment url and provide credentials when prompted
4. Wait for queries to run

The following error appears

<img width="530" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/108309708/6cb8cb39-014f-42ed-ad7f-de0f3b9d5df4">

AB#2238

**Comment by Jenefer-Monroe** [comment]
That is a new field in the PowerApps Apps coe table that was released with the Feb release. In order to use the Feb PBI you will need to upgrade to the Feb Core components.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by ImranCodeBug** [comment]
i am getting this exact error while using the latest version **Production_CoEDashboard_September2024.pbit**. here is the image of the error
![image](https://github.com/user-attachments/assets/bf4a28b2-f768-4634-afb2-8ef947691b03)

**Comment by mppreethi** [comment]
Yes, I am also getting the same above error. Is there a fix for or steps to overcome this? Kindly advise.
