### ISSUE TITLE
[CoE Starter Kit - BUG] Command Center App --> Get M365 Service Messages not importing "Content not shown due to security configuration"

### ISSUE THREAD

**Issue by dtrandall** [microsoft/coe-starter-kit#7617]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Content not shown due to security configuration.
![image](https://github.com/microsoft/coe-starter-kit/assets/34244066/28196953-78ea-4254-b684-fa367356fd0e)

I have checked the DLP connectors for COE and are correct.
I have checked the App registration and API permissions are granted.
Also the environment variables are populated in Command Center - Application Client ID and Client Secret with value

### Expected Behavior

Would expect to see health messages from the message center but is blank
![image](https://github.com/microsoft/coe-starter-kit/assets/34244066/17c94fcd-c30b-4025-beb4-908ba626c598)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Command Center App > Get M365 Service Messages

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Try to resubmit flow but same security error

AB#2241

**Comment by Jenefer-Monroe** [comment]
are you storing the secret for the app registration as an azure secret or as plain text?

**Comment by dtrandall** [comment]
it is an azure client secret 

![image](https://github.com/microsoft/coe-starter-kit/assets/34244066/697258bb-5714-484f-9624-32f4008d876f)

**Comment by Jenefer-Monroe** [comment]
We've had people struggle to integrate with Azure Secrets in the past. What we have found is that it typically comes down to these two product integration issues between Power Platform and Azure Key Vault:

1. Validate that the azure key vault permissions are correct. User needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)

2. Validate that you do not have IP restrictions enabled, or if you do that you have Microsoft's internal outbound IP addresses to the firewall.

**Comment by dtrandall** [comment]
I am sorry maybe I am confused as not using data export but cloud flows to pull in the data thus I believe from documentation I do not need to configure Azure Storage Account or use the Env Variable to get Message center data.   Can you confirm that this is still required?

**Comment by Jenefer-Monroe** [comment]
This is for the the permissions on the key vault, not storage. You do not need a storage account for the Sync Flow architecture.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
