### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs not gathering

### ISSUE THREAD

**Issue by Harryprasanth** [microsoft/coe-starter-kit#7618]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have COE Toolkit (Core Components) and last upgraded in the month June 2023, and we upgraded the latest solution hence Custom connector was removed and deprecated from August 2023, but audit log not been captured through http and after updated the Client id and Client secret id for M365 Management API in environment variables. not being capture logs properly.

Note : Due to this issue in **Power Platform admin view**  app under PowerApps not able to see "App Last Launched date" and under Flows not able to see "Flow Last Run on" 

<img width="360" alt="1232" src="https://github.com/microsoft/coe-starter-kit/assets/64703887/a935f602-7185-4f95-8c98-b299243a530f">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2242

**Comment by Jenefer-Monroe** [comment]
1. Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

1. Validate that the azure key vault permissions are correct. User needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)

1. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

1. Turn the flows off and back on. Sometimes env vars get stuck in them with old values
1. Validate that you have [started the subscription](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
