### ISSUE TITLE
[CoE Starter Kit - BUG] How the Flow Last run data captured in the Dataverse table through Power Automate flow?

### ISSUE THREAD

**Issue by Harryprasanth** [microsoft/coe-starter-kit#7619]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

How the Flow Last run data captured in the Dataverse table through Power Automate flow? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

None

AB#2243

**Comment by Jenefer-Monroe** [comment]
Hello. The product team just recently started writing flow run information to a spot that is accessible to people. Please see [Store cloud flow execution metadata in Microsoft Dataverse](https://learn.microsoft.com/power-platform/release-plan/2023wave2/power-automate/store-cloud-execution-history-dataverse)

However we have not yet been able to fund consuming this data for the kit.

**Comment by Harryprasanth** [comment]
Can you please confirm they what was this column in Power Platform Admin View app under category "Flows" section.
<img width="773" alt="FCapture" src="https://github.com/microsoft/coe-starter-kit/assets/64703887/3117ff18-257b-49ff-bd31-c1822769f792">
 states that

**Comment by Jenefer-Monroe** [comment]
That is for if you use the [Data Export (preview)](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory) version of the kit. Also known as BYODL (Bring your own Datalake). 

It uses the following preview product features [Set up Microsoft Power Platform self-service analytics to export inventory and usage data](https://learn.microsoft.com/power-platform/admin/self-service-analytics)

**Comment by Harryprasanth** [comment]
Hello Jenefer ,

Can you please help to understand , is there anyway to capture last flow run details in COE Toolkit ?

Regards,
HARIPRASANTH
________________________________

**Comment by Jenefer-Monroe** [comment]
Not using the cloud flow architecture no there is not. We may do it at some point but for now its only available if you use the Data Export architecture.

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today

**Comment by juliopaz30** [comment]
Hi @Jenefer-Monroe,

I read all the details here and installed the latest version of the CoE Starter Kit. Regarding the LAST RUN information for cloud flows, you said it's only for Data Export, but that option is obsolete. And now only cloud flows are available.

How can we obtain this information? By customizing, using APIs, PowerShell commands? What is Microsoft's response on this?
