### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI dashboards are not updating the deleted cloud flows

### ISSUE THREAD

**Issue by pjarqueo** [microsoft/coe-starter-kit#7620]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,
The Power BI CoE dashboards are very useful for cleanup purposes such as applying the governance best practices. The problem we are experiencing is that despite some cloud flows are deleted from the default environment They are still visible in the Cloud flow dashboards. The default environment is called in the organization 'Personal Productivity'.
<img width="511" alt="Mistmatch with flow deleted_CoE dashboard" src="https://github.com/microsoft/coe-starter-kit/assets/158201814/0a110aa4-81a3-433b-bc02-a76463db0bde">

### Expected Behavior

After 24 hours of refreshing time all the cloud flows that have been deleted should not show up as they are already deleted. The point is that some of the cloud flows that were deleted several months ago still appear as available in the dashboards. It has been checked in the Power Platform admin center and indeed those are deleted. But They still appear in the dashboards. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.3.0 (January 2024)

### What app or flow are you having the issue with?

Some of the cloud flows created in the default environment.

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1.- Delete cloud flows.
2.- Wait between 24-48 hours as minimum in order to let time to refresh.
3.- Check the Power BI dashboards in order to review if those cloud flows id's have been removed.
4.- They still appear in the dashboards.

### Anything else?

As you can see in the screenshot, the cloud flow does not appear any more in the default environment once it has been deleted, which is correct.
<img width="612" alt="Cloud_flow_does_not_appear(correct)_in_default_environment_at_Power_Platform_admin" src="https://github.com/microsoft/coe-starter-kit/assets/158201814/d7119bbc-d47f-4226-957f-3475419ebd75">

AB#2244

**Comment by Jenefer-Monroe** [comment]
Do the flows show up in the Power Platform Admin View app of the Starter Kit?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/731e5faa-633a-4cd8-b9ec-f1a8acdf6efd)

**Comment by pjarqueo** [comment]
Yes, it does appear the flow in the Power Platform Admin View app of the Starter Kit.

**Comment by Jenefer-Monroe** [comment]
Ok great, then its likely just a refresh on the PBI you are missing as that is the table it reads from. 
Please be sure you have [Configured your PBI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard) for [scheduled refresh](https://learn.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh)

**Comment by pjarqueo** [comment]
But that is the point. If that table is the source of the CoE Power BI dashboards, it should not appear that flow in the table, as it has been removed already, right? It would be an issue of refresh if the case would be the contrary. I mean, that the flow would have been created but it would not appear in the dashboards.

**Comment by Jenefer-Monroe** [comment]
Sorry I dont follow. Can I repeat?
You have confirmed the flows no longer exist in the table itself
You have refreshed the PBI data source (per above links)
You still see them in the PBI

Is that correct?

**Comment by pjarqueo** [comment]
- The cloud flows no longer exist in the Power Platform admin center when you look for them (so they no longer exist, and that is correct as they were deleted). Which is the screenshot from above.
- However, the cloud flows do appear in the table of Power Platform Admin View app of the Starter Kit. Which they should NOT appear as they are deleted.
- In addition, the cloud flows appear too in the CoE Power BI dashboards (the same as the table of Power Platform Admin Vieww app of the starter kit, which is its data source) but it is not correct neither as those flows no longer exist.
- The Power BI dashboard has been refreshed and anything changes. Those deleted cloud flows still appear.

**Comment by pjarqueo** [comment]
You are welcome Jenefer. 
The flow that has been deleted does appear in the active flows as 'suspended' status.
<img width="296" alt="Cloud_flow_appears_on_active_flows_as_suspended" src="https://github.com/microsoft/coe-starter-kit/assets/158201814/dd41c2c3-e40c-4f08-8c45-4963cc26f0fc">
And there are not any deleted flows in the view of deleted flows, neither with 'deleted' in the title.:
<img width="340" alt="deleted_flows_no_data_available" src="https://github.com/microsoft/coe-starter-kit/assets/158201814/6af8e446-9f5b-4042-8e14-7e9cd2987091">

**Comment by Jenefer-Monroe** [comment]
Sorry that was not what I meant. We shipped the Jan release with both a v3 and a v4 version of the check deleted flows. 
If you go to the CoE Environment and look at the flows in the Core solution (not at the flows in PPAdmin), please let me know which flows are turned on that have the word "Deleted" in them
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/83c3c32a-1f78-4ac5-8512-1f1b113c0b58)

**Comment by pjarqueo** [comment]
Hello,
The version v3 is active while the version v4 is turned off. Should be both of them turned on in order to fix it?

**Comment by pjarqueo** [comment]
Once I try to run the flow v4 this error appears:
<img width="1116" alt="error_turning_on_flow_v4" src="https://github.com/microsoft/coe-starter-kit/assets/158201814/5e80b1f8-7865-4ae0-9ac8-77c026f53ddd">

**Comment by Jenefer-Monroe** [comment]
Yes it has child flows that are required. I cant remember the state we shipped with for Jan as it was the first release with them available. You will likely be better served by upgrading to Feb and using the Setup Wizard which will ensure all the correct flows are turned on, or waiting for March release when only the v4s will be available.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
