### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard - ARM Features missing a "Done" button to complete the steps

### ISSUE THREAD

**Issue by MeinaHe** [microsoft/coe-starter-kit#7621]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the February 2024 CoE Starter Kit upgrade, the app Setup Wizard - ARM Features, in the last step " Import Older Data", there is no "Done" or "Finish" button to click on to complete the process, only a "Back" button.
This is confusing and please help to look into it, thank you!

### Expected Behavior

What i expected is a "Done" or "Finish" button to indicate the user that the steps have been completed and redirect the user to the Bookmark Pages.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

3.15

### What app or flow are you having the issue with?

Setup Wizard – ARM Features 

### What method are you using to get inventory and telemetry?

None

AB#2245

**Comment by Jenefer-Monroe** [comment]
This is a temporary app we made just to plug a whole while we wait for a connector to be available in GCC / GCC High / DoD. So once that is available this app will go away and it will be with the regular setup wizard and follow the same pattern as other feature setups. 
Hope that makes sense.

**Comment by MeinaHe** [comment]
That clears up my question, thank you so much!

**Comment by Jenefer-Monroe** [comment]
You are quite welcome. I'll go ahead and close then but please do reach out again with new issues as needed.
