### ISSUE TITLE
In Powerapp app table all the model driven app are marked as deleted

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#7624]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the powerapp app table out of 3798 model driven app records 3729 model driven app records are marked as deleted. could you please help us out why this is happening.

### Expected Behavior

This many model driven app should not be marked as deleted

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted (Model Driven Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2248

**Comment by Jenefer-Monroe** [comment]
I just looked at our setup of the Nov 2023 version of the CoE, which is what I believe you have, and I do not see this behavior. So I'm not sure how you got into this state. 
Is it just MDAs? Or are other objects also marked as deleted? (ex Cloud Flows and Solutions)

**Comment by Rajatchopra3** [comment]
It is only happening for MDA, and could you please tell which flow is calling CLEANUP HELPER - Check Deleted (Model Driven Apps).

**Comment by Jenefer-Monroe** [comment]
It is called by the **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_** flow. 
You can see this by going to see dependencies for the flow:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/775c8024-0a04-47af-9d6d-f7c9c7772cec)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f39d1460-a08a-4153-8ccb-1e5722b97d8c)

**Comment by Jenefer-Monroe** [comment]
Are you using the Cloud Flow architecture? (v Data Export/BYODL)
I know you state Cloud Flow, but just making sure that was intentional.

**Comment by Rajatchopra3** [comment]
yes we are using Cloud Flow architecture

**Comment by Jenefer-Monroe** [comment]
OK I dont repro. The new versions of the kit with the v4 connector will fix up bad data like this so I suggest you upgrade to the March release when it comes out in a few weeks.

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today
