### ISSUE TITLE
[CoE Starter Kit - Feature]: Set env capacity alert threshold with env vars vs. it being 80 % by default

### ISSUE THREAD

**Issue by anttipajunen** [microsoft/coe-starter-kit#7626]
### Is your feature request related to a problem? Please describe.

Problem: Capacity increase in Dataverse environments might be rapid enough for an 80 % warning threshold to be too high.

### Describe the solution you'd like

I'd like to be able to set a threshold with environment variables, realizing that the threshold would apply equally to all environments.

### Describe alternatives you've considered

I could tap into Copy of - Admin | Capacity Alerts or create a flow of my own.

### Additional context?

![image](https://github.com/microsoft/coe-starter-kit/assets/64043240/599bdde1-d630-4e4a-846f-c5eb88ae1757)

Combine with #6759 or as a "quick win" solution of its own.

**Comment by Jenefer-Monroe** [comment]
This does seem like something we could do for a quick win! Will see if I can fit it in for March.

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1fa1649f-e6c2-4a43-9ef4-2a693821a3a5)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/aaa21023-ba46-463d-a8cc-86a0b987f89d)

**Comment by Jenefer-Monroe** [comment]
Ready for March

**Comment by anttipajunen** [comment]
Thanks Jenefer!

**Comment by Jenefer-Monroe** [comment]
Thanks for posting a quick win! They feel GOOOOD!
