### ISSUE TITLE
[CoE Starter Kit - BUG] Flow errors on Admin | Sync Template v4 (Portals) & CLEANUP HELPER - Check Deleted v4 (Portals). Parse action failing

### ISSUE THREAD

**Issue by melbare** [microsoft/coe-starter-kit#7627]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After installing the newest version of the February 2024 CoE Starter Kit, we are getting errors daily that sync flows related to Portals (Power Pages) are failing due to a bad parse action in 2 seperate flows:

- Admin | Sync Template v4 (Portals)
- CLEANUP HELPER - Check Deleted v4 (Portals)

Here are some screenshots showing the failing flow after the latest upgrade: 

![image](https://github.com/microsoft/coe-starter-kit/assets/149709693/02ee2054-b1a4-46f2-826c-53cff8ddedf9)
![image](https://github.com/microsoft/coe-starter-kit/assets/149709693/f6d872f4-db3e-4d1a-9901-b28834f58feb)

### Expected Behavior

It looks like these flows are failing due to not being able to Parse the JSON information in a previous step using the Parse JSON Action. Nothing else seems to be failing in the kit besides these 2 flows after the update and they both seem to relate to Power Pages (formerly Portals)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin - Sync Template v4 (Portals) & CLEANUP HELPER - Check Deleted v4 (Portals)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Update to newest environment
2. Wait for Portal flows to fail from bad JSON Parse

AB#2251

**Comment by melbare** [comment]
Here is the JSON for the Outputs:

{
    "errors": [
        {
            "message": "Invalid type. Expected String but got Null.",
            "lineNumber": 0,
            "linePosition": 0,
            "path": "[1].Portal_NonUnique",
            "schemaId": "#/items/properties/Portal_NonUnique",
            "errorType": "type",
            "childErrors": []
        },
        {
            "message": "Invalid type. Expected String but got Null.",
            "lineNumber": 0,
            "linePosition": 0,
            "path": "[3].Portal_NonUnique",
            "schemaId": "#/items/properties/Portal_NonUnique",
            "errorType": "type",
            "childErrors": []
        }
    ]
}

**Comment by melbare** [comment]
And here are the inputs, looks like a couple of null values are present: 

{
    "content": [
        {
            "Portal_Unique": "bfa329b2-db10-45a7-a2a4-53b80a5fb8f2_c0887167-3954-e611-80dc-00155d209102",
            "Portal_NonUnique": "c0887167-3954-e611-80dc-00155d209102"
        },
        {
            "Portal_Unique": "bfa329b2-db10-45a7-a2a4-53b80a5fb8f2_114b9b4e-b397-e711-80ec-00155d953a0d",
            "Portal_NonUnique": null
        },
        {
            "Portal_Unique": "bfa329b2-db10-45a7-a2a4-53b80a5fb8f2_be4aacbc-572d-4122-b31a-fbd4545cc76a",
            "Portal_NonUnique": "be4aacbc-572d-4122-b31a-fbd4545cc76a"
        },
        {
            "Portal_Unique": "bfa329b2-db10-45a7-a2a4-53b80a5fb8f2_d78574f9-20c3-4dcc-8d8d-85cf5b7ac141",
            "Portal_NonUnique": null
        }
    ],
    "schema": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "Portal_Unique": {
                    "type": "string"
                },
                "Portal_NonUnique": {
                    "type": "string"
                }
            },
            "required": [
                "Portal_Unique",
                "Portal_NonUnique"
            ]
        }
    }
}

**Comment by Jenefer-Monroe** [comment]
That data is corrupt. Can you delete the records that are like this in the table? Then lets see if they come back. I suspect they are a legacy issue from before the shift to V4. 

You can do this by going to the table, adding the columns shown, and then hit Edit to see more records


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8e7b3282-87b5-41b3-a940-fb3c764439f0)

Filter the columns one at a time to "does not contain data" and delete the records that have empties in one or more of the columns. 

At that point your flow will pass, then lets see if the bad data returns.

**Comment by Jenefer-Monroe** [comment]
If that cleans it up, and they dont return, then I'll add this clean up to the Delete Bad Data flow to ensure others dont have to do this manually.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by melbare** [comment]
This change worked, thank you Jenefer!

**Comment by PPTechy** [comment]
Hi @Jenefer-Monroe 

I am also facing the same issue after upgrading to 4.33 version from 4.17 version.

With this filter "Power Pages Website ID" does not contain data, I could see there are two pages with empty values:

<img width="646" alt="image" src="https://github.com/user-attachments/assets/9d658f81-3d55-4d84-a2a3-eead95bdea4b">

And for "Power Pages Unique ID" does not contain data filter I didn't get any pages:

<img width="623" alt="image" src="https://github.com/user-attachments/assets/ed28344d-76b2-48df-b895-f30697e1291c">

So, should I delete only those two records highlighted above which came from the "**Power Pages Website ID**" does not contain data filter?
