### ISSUE TITLE
Changing the COE Service Account

### ISSUE THREAD

**Issue by jcgds** [microsoft/coe-starter-kit#7628]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, for security reasons I need to change the password of the account that was used to configure all COE services. Can I change it normally? Or is there some procedure that should be carried out?

Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2252

**Comment by Jenefer-Monroe** [comment]
Hello. You should be fine to change the password as normal. 
After you do this just check to make sure none of your connections broke and if so just repair them
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3beb97e6-1194-43f6-b5d7-87531a4f8966)

**Comment by jcgds** [comment]
Thaank you!

**Comment by Jenefer-Monroe** [comment]
You bet! We are here to help.
