### ISSUE TITLE
Environment 'Generative AI features' column/field 

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#7629]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have the Feb release. i can see 'copilot enabled' column in Environment table (nice). Is there any column to see if 'Generative AI features' has been enabled

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Data Export

AB#2254

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today
