### ISSUE TITLE
[CoE Starter Kit - QUESTION] Exchange Logo in Mails

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#7631]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, I have to replace the Microsoft logo in all the mails, as we have to use our company logo here.

If I link one of our logos here (stored as attachment in SharePoint), it is not always displayed (not loading?). Where should the logo be stored? I have simply replaced the link in the corresponding environment variable.

When the logo is displayed from now and then, it is in very poor quality and the height is compressed. Where can I adjust the size of the image field and hight of the first two sections of the mails? Is is right to have the second separator below the colored separator? Or did I mess up something here?

<img width="406" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/62603605/de532c3c-081b-482b-b175-64688f0453c5">

It would be great to get some help here.

Best regards
Cathi

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

All Mails 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2255

**Comment by Jenefer-Monroe** [comment]
Unfortunately, there isnt anything we can really do about that. Images stored in SP dont always get fetched the easiest by other products like exchange or even PowerApps.

This is an integration issue between these products. 
Happy to hear if others in the community have an idea but I dont think we as a kit can do anything about that.

**Comment by Cathi029** [comment]
> Unfortunately, there isnt anything we can really do about that. Images stored in SP dont always get fetched the easiest by other products like exchange or even PowerApps.
> 
> This is an integration issue between these products. Happy to hear if others in the community have an idea but I dont think we as a kit can do anything about that.

Thank you for your response! There is no need to store the image in SharePoint. Couund you or anybody recommend a storage, that works fine for this Use Case?

Do you have recommendation regarding the compressed hight of the image?

**Comment by Jenefer-Monroe** [comment]
I'm not sure how others have used this. Do others here have a recommendation? The sample we ship with I believe is just a web hosted file.

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today
