### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#7632]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, everyone,

What is the best way to test some CORE CoE features without impacting the whole tenant? We do not have a test tenant and cannot test in Developer tenant as functionality of the COE is limited there (including the # of API calls), etc. That leaves us with our PROD tenant to try things out.

I'm thinking to isolate testing to a single environment, but how's that going to work with the CoE? Can I assume that, if I reduce the number on non-excused environments to a single test environment, once I turn on CORE features like the Welcome Email, they will only apply to users within the non-excused environment, and not to the whole tenant? Mainly, I am trying to avoid Welcome emails going out in our Default environment, which is already in use.

Your help is appreciated,
Thanks,

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2259

**Comment by Jenefer-Monroe** [comment]
We have an Env Var called **_Production Environment_** which will do the trick for you here 
Do be sure to reset the flows that depend on it (including your welcome mail) to ensure they get the new value. But with this env var, all communications go to the Admin Email you have conigured.

**Comment by VanIsleCA** [comment]
Thanks so much for your reply, that is very helpful. I tried it, and one thing that I guess we can't control is that a newly added Maker will receive an email stating that they have been added to the Maker Group of the CoE. However, I do understand that this email is not generated by the CoE, but it is a M365 email notification being sent out when a user joins a group. Something that we can't bypass even if we set Production Environment = NO. Just something to be aware of, in case real users are involved. 

Thanks again!

**Comment by Jenefer-Monroe** [comment]
Got it, thank you yes I presume there is a way to turn that off in Azure as well but I dont know what that would be. Perhaps others here know?

**Comment by Jenefer-Monroe** [comment]
It sounds like there is a PowerShell command to do this, but its outside the scope of the PP of course. 
I suggest you just bing it as well : disable m365 welcome mail

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today
