### ISSUE TITLE
[CoE Starter Kit - BUG] Need the latest version of Auditlog solution to be downloaded

### ISSUE THREAD

**Issue by DheekshaSivaraj** [microsoft/coe-starter-kit#7633]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Need the latest version of Auditlog solution (zip file )to be downloaded. Can someone please help with the link to download. Unable to find a link from which it can be downloaded.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Need Auditlog solution

### What method are you using to get inventory and telemetry?

None

AB#2260

**Comment by petepuu** [comment]
@DheekshaSivaraj AuditLog solution was retired in August as AuditLog sync flows are now part of Core solution since May release. If you still want to use old AuditLog sync method using custom connector then check these instructions https://github.com/microsoft/coe-starter-kit/issues/6017

**Comment by Jenefer-Monroe** [comment]
Thanks Pete, yes thats correct we will not be shipping the Audit Logs solution any longer due to its deprecation.

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today
