### ISSUE TITLE
[CoE Starter Kit - BUG] Inaccurate App Report

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7634]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are using data lake CoE and we noticed that our CoE is showing only 28 activate canvas apps where we should have more than 26k apps. We noticed that a lot of those apps are actually inventory but marked as deleted in the CoE.  These apps are on our default environment. Thoughts?

### Expected Behavior

Report should show 26k apps as activate instead of 28.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Open Admin View App

AB#2261

**Comment by Jenefer-Monroe** [comment]
Hello. Did you already perform the fix up described here?: https://github.com/microsoft/coe-starter-kit/issues/7562#issuecomment-1916812148

This fix did not make it into Feb release and will be available in March. 
After you apply the fix and clean the Check Deleted system should instantiate the missing apps/flows/etc that are marked deleted.

**Comment by nasilvae** [comment]
> Hello. Did you already perform the fix up described here?: [#7562 (comment)](https://github.com/microsoft/coe-starter-kit/issues/7562#issuecomment-1916812148)
> 
> This fix did not make it into Feb release and will be available in March. After you apply the fix and clean the Check Deleted system should instantiate the missing apps/flows/etc that are marked deleted.

Thank you

**Comment by Jenefer-Monroe** [comment]
Please do let me know.

**Comment by Jenefer-Monroe** [comment]
looks like we've moved on to the maker flow so ill go ahead and resolve.
