### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Business Process Flows) Failure with Feb 2024 CoE

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#7635]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team, 

Referencing this to the older issue: https://github.com/microsoft/coe-starter-kit/issues/7567#issue-2108684248

I have updated the CoE into the Feb 2024 release; however, is still receiving this error: "The supplied reference link -- admin_makers() -- is invalid. Expecting a reference link of the form /entityset(key)."

Just wanted to confirm with the team if this issue has been fixed. 

Thanks 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Business Process Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2262

**Comment by Jenefer-Monroe** [comment]
The fix was not applied to the old v3 versions of the sync flows. You will need to use the v4 versions to see the fix.

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today
