### ISSUE TITLE
[CoE Starter Kit - BUG] App Inventory inaccurate even after adding deletion code in Environments and Deleting dataflow Refresh history

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#7637]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have 6000+ apps but the inventory shows 650 only. 
We have upgraded to Feb kit. 
Also deleted the dataflow refresh history.
As well as added the code snipped in Environment dataflow. 

We are using CoE BYODL. 
Could you please help? Thanks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

BYOD Apps

### What method are you using to get inventory and telemetry?

Data Export

AB#2265

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today
