### ISSUE TITLE
[CoE Starter Kit - BUG] Error in Request Orphaned Objects Reassigned (Parent) flow

### ISSUE THREAD

**Issue by Papa-Cho** [microsoft/coe-starter-kit#7638]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The 2 flows (parent & child) to manage orphans have stopped working since we upgraded the CoE kit to the January 2024 version.
In parent flow named "Request Orphaned Objects Reassigned (Parent)", the step "Send admin email of orphans they will need to resolve" in "Send items without managers to admins" scope refers to a child flow. But the flow ID of that child flow is pointing to a flow that is deleted. 
How to fix it? What should be the child flow in this step?
![image](https://github.com/microsoft/coe-starter-kit/assets/92913718/4bf690c0-cdd2-43d0-9250-616b6f8aa9aa)
![image](https://github.com/microsoft/coe-starter-kit/assets/92913718/c8c7b094-5938-4b2f-adc4-7f5830c1a103)

### Expected Behavior

The 2 flows (parent & child) to manage orphans should execute correctly

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.14

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2267

**Comment by Jenefer-Monroe** [comment]
For whatever reason managed install flows dont show the name of the flow being called. But its calling the **_HELPER - Send Email_** flow which is part of the Core Components solution install.
Please go see if its turned on.

You can get an idea of what it might be by looking at its dependencies:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/aa581fbc-d884-44c2-bcd1-928a33bb8c62)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fecd109c-a577-4de0-bc9c-53424e5677f3)

**Comment by Papa-Cho** [comment]
Hello
Indeed the HELPER - Send email flow was off. I've turned it on and testing the orphan flow now
Thank you

**Comment by Jenefer-Monroe** [comment]
Please do let us know.
