### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by heatheronder** [microsoft/coe-starter-kit#7640]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Microsoft automatically cleans up unused developer environments however we noticed recently that this isn't happening. All but two of our developer environments are showing a "last activity" time stamp in the admin portal of yesterday morning at the same time our BYODL dataflow/sync flows run. Is there something in the CoE kit that is causing last activity to update on inventory? How can we get around this so our environments can get automatically deleted like they're supposed to? The odd thing is it doesn't seem to be impacting teams environments.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What method are you using to get inventory and telemetry?

Data Export

AB#2269

**Comment by Jenefer-Monroe** [comment]
Hello I presume you mean this as one of the Managed Environment features is that correct? If so, we do have outstanding work items in the product team around this.

**Comment by heatheronder** [comment]
@Jenefer-Monroe No, our company doesn't use managed environments yet. I'm talking about this: https://learn.microsoft.com/en-us/power-platform/admin/automatic-environment-cleanup#unused-environments

**Comment by Jenefer-Monroe** [comment]
This is the product feature I was thinking of, looks like it can work with the ME designation. 
Unfortunately this is an issue with the product and the PMs are already working together to come up with a plan. You can track that with https://github.com/microsoft/coe-starter-kit/issues/7574

**Comment by Jenefer-Monroe** [comment]
closing out then as no further action for starter kit team today
