### ISSUE TITLE
[CoE Starter Kit - Feature]: Cleanup Old Objects App - Sort & Filter

### ISSUE THREAD

**Issue by sasrsc** [microsoft/coe-starter-kit#7642]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

 I would like the ability to sort the "App" column asc or desc in the Clean Up App.
 If not default the gallery to sort by Env then App name. If there is a sort now I'm not clear what it is.
 
![sortRegion Capture](https://github.com/microsoft/coe-starter-kit/assets/8988793/942f5fbf-171e-4d76-ad00-e64498d0bc2d)

### Describe alternatives you've considered

I could do it myself but then I know have customized the CoE App and future updates could be problematic. We both know that's a very quick fix and yet very useful 

### Additional context?

This is very useful when you have pages of apps, flows to review and we've just launched the CoE after 4 years of accummulating a mess ;-)

Thanks for your consideration

AB#2271

**Comment by Jenefer-Monroe** [comment]
Hello, we do plan to redo this app along with the general redo of the inactivities feature area. With that work, we will also be using the same look /feel of the other recent kit apps which means we will use the Detail List from the Creator kit and hence all columns will be sortable.

**Comment by sasrsc** [comment]
Well, that would be terrific. I’ve just started playing with the Creator Kit.


Richard Clowes
Senior Director ● Travel Operations
Tel: + 1 919 531 7955 ● Cell: + 1 919 413 3084 ● ***@***.******@***.***>
Worldwide Headquarters ● Cary, NC

www.sas.com<http://www.sas.com/>
SAS(r) … THE POWER TO KNOW(r)

**Comment by Jenefer-Monroe** [comment]
Glad to have you in the Creator Kit! I love it. I'll go ahead and close this one then but please do return with new issues as they arise for you.
