### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Data Flow not working

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7643]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are having the following error when refreshing the environment dataflow. We are using the January release for CoE and have implemented the fix for the dataflow bug. https://github.com/microsoft/coe-starter-kit/issues/7562#issuecomment-1916812148

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/2f5b6bab-5d1f-464e-b78f-fe6c145a4a68)

Thoughts?

### Expected Behavior

It should run

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Enviornment DataFlow

### What method are you using to get inventory and telemetry?

Data Export

AB#2272

**Comment by Jenefer-Monroe** [comment]
This means that the Maker table has not filled with that user. Typcially this happens when you have periodic refresh on all the dataflows instead of just the Maker dataflow. 
Can you please validate that you only have the next refresh scheduled for Maker?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc968f0f-9f46-4ede-9a61-574695d83428)

**Comment by nasilvae** [comment]
> This means that the Maker table has not filled with that user. Typcially this happens when you have periodic refresh on all the dataflows instead of just the Maker dataflow. 
> 
> Can you please validate that you only have the next refresh scheduled for Maker?
> 
> ![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc968f0f-9f46-4ede-9a61-574695d83428)
> 
> 

Does this means that I should only have the maker dataflow scheduled? Would the other dataflows get triggered automatically?

**Comment by nasilvae** [comment]
> > This means that the Maker table has not filled with that user. Typcially this happens when you have periodic refresh on all the dataflows instead of just the Maker dataflow.
> > Can you please validate that you only have the next refresh scheduled for Maker?
> > ![image](https://private-user-images.githubusercontent.com/89584709/302956780-bc968f0f-9f46-4ede-9a61-574695d83428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTc0OTQsIm5iZiI6MTcwNzkxNzE5NCwicGF0aCI6Ii84OTU4NDcwOS8zMDI5NTY3ODAtYmM5NjhmMGYtOWY0Ni00ZWRlLTlhNjEtNTc0Njk1ZDgzNDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzMjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTBkOTljYjUwOThmYTRmNzhkMDA4OGQwZDgwMTI3NWZjMjhmMmQ2ZjkyOGE0ZDJhYThmNWM4OWMyMThkZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tn1vq5hEtLXcD1ojNAiPvb-yJxtLXEsebRIiNnVocVs)
> 
> Does this means that I should only have the maker dataflow scheduled? Would the other dataflows get triggered automatically?

I didnt knew about the dataflow refresh schedule. I'm making the adjustments now and will let you know if the error goes away. Thank you again for the quck response.

**Comment by Jenefer-Monroe** [comment]
Yes thats correct you should only have the Maker dataflow scheduled. The rest get triggered in the required order by the flows that you turn on after you set these up:
 

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d468cbaf-7fec-49e4-82e0-1398717984de)

**Comment by nasilvae** [comment]
> Yes thats correct you should only have the Maker dataflow scheduled. The rest get triggered in the required order by the flows that you turn on after you set these up:
> 
> ![Image](https://private-user-images.githubusercontent.com/89584709/304754767-d468cbaf-7fec-49e4-82e0-1398717984de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjMzNDksIm5iZiI6MTcwNzkyMzA0OSwicGF0aCI6Ii84OTU4NDcwOS8zMDQ3NTQ3NjctZDQ2OGNiYWYtN2ZlYy00OWU0LTgyZTAtMTM5ODcxNzk4NGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE1MDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YTQ4ZmU0M2UwMmJmNGU1YTJkYzhkMTE0NTA5ZDcwMWEzMWM1OTdmMmE0MjA0OWI2MWJkYmRkNWRlZTNjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZynrT4p79qD6bQriiZCTPfOmKYCTkWxt7ccBQmc2jDg)

I'm getting the following error now when I try refreshing the maker dataflow

https://github.com/microsoft/coe-starter-kit/issues/7648
