### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE WITH SETUP AUDIT LOGS

### ISSUE THREAD

**Issue by Bhawna199** [microsoft/coe-starter-kit#7645]
### Does this bug already exist in our backlog?

- [ ] I have checked and confirm this is a new bug.

### Describe the issue

I am not able to fetch the audit logs after setup of this component after following Documentation given.
Could you please let me know what should be the required steps 

### Expected Behavior

Audit log flows are getting failed

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

CreatorKitCore_1.0.20230727.2_managed

### What app or flow are you having the issue with?

Audit

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Audit log flows are getting failed

AB#2274

**Comment by Jenefer-Monroe** [comment]
The instructions given in the documentation are correct and up to date: https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http

Here are the most common issues people face:
1. Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

1. If you aer using Azure Key Vault for the secret and not plain text, validate that the azure key vault permissions are correct. User needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)

1. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

1. Turn the flows off and back on. Sometimes env vars get stuck in them with old values

1. Validate that you have [started the subscription](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

**Comment by Jenefer-Monroe** [comment]
Hello. The instructions given in the documentation are correct and up to date: https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http

Here are the most common issues people face:
1. Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

1. If you aer using Azure Key Vault for the secret and not plain text, validate that the azure key vault permissions are correct. User needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)

1. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

1. Turn the flows off and back on. Sometimes env vars get stuck in them with old values

1. Validate that you have [started the subscription](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

**Comment by Bhawna199** [comment]
Hi Jenefer,

Good day!

According to the documentation provided. I followed all the steps and all flows are On and succeeded.
I ran the flows yesterday, but didn't get any result in the Audit logs tables.

Could you please help me here.

Thanks and regards,
Bhawna Bansal
Sr. Associate L1 - CRM Functional
Planned OOO : Mon 19-Feb to Tue 20-Feb-2024
________________________________

**Comment by Bhawna199** [comment]
Hi Jenefer,

Could you please help me as early as possible as we need this data for our analysis.

Thanks and regards,
Bhawna Bansal
Sr. Associate L1 - CRM Functional
Planned OOO : Mon 19-Feb to Tue 20-Feb-2024
________________________________

**Comment by Jenefer-Monroe** [comment]
Hello, please note the CoE Starter Kit is an unsupported set of templates: https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support 

We do best effort to assist our GitHub customers but we do not have SLA. 

Thank you for your patience

**Comment by Jenefer-Monroe** [comment]
Please share screenshots of each of the items above (pasted again here for ease of reference). 
There is something just misconfigured as this works for people when correctly setup. 

1. Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

1. If you aer using Azure Key Vault for the secret and not plain text, validate that the azure key vault permissions are correct. User needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)

1. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

1. Turn the flows off and back on. Sometimes env vars get stuck in them with old values

1. Validate that you have [started the subscription](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

**Comment by Bhawna199** [comment]
________________________________

**Comment by Bhawna199** [comment]
Hi Jenefer,

Please find the attached screenshots for your reference

 App registration and validate that you have the correct API permissions (Application)

[cid:4426548a-379a-4b29-9b61-e5b4e4888d41]

2. I am not using Azure vault

3. Env variables

[cid:48a9009d-ad84-48d2-b822-df2fd55fe18b]

4. Turn the flows off and back on. Sometimes env vars get stuck in them with old values

[cid:39232e10-0738-4211-ae71-36df4e9b99ce]

Flow is succeed but not giving any result in Audit logs

[cid:a80a37e4-1ebf-4f4b-bf7f-09af1b590550]

[cid:ce6a224b-70d4-4027-bd52-1207af192cc4]

Validate that you have started the subscription

[cid:5bf598b1-0737-4fe1-a910-20083fe05b6a]

Kindly let me know what is missing in these config.

Thanks and regards,
Bhawna Bansal
Sr. Associate L1 - CRM Functional
Planned OOO : Mon 19-Feb to Tue 20-Feb-2024
________________________________

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately screenshots do not come through when you respond in email, you will need to log in to GitHub and share them.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
