### ISSUE TITLE
[CoE Starter Kit - QUESTION] Minimal permission to perform starter kit update actions.

### ISSUE THREAD

**Issue by GithMen** [microsoft/coe-starter-kit#7646]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

We have installed CoE Starter Kit and use it to monitor our Power Platform tenant. We would like to delegate the updating  process to an external provider service. 
We have to create a service account that will be used by the external provider service to perform updates actions.
Which minimum required access should we assign to the service account to be able to update the starter kit ?
Which account type we should  create ? 
    - The account must be email-enabled ? 
    - We should desactive MFA for the account ? 
    - A premium license for the account is required  ?
For security reasons, we want to provide  the least access to our tenant.
Any help will be appreciated.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2275

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately I dont know of any less privaledged way to do this. The requirements would be the same for an external user as for a member user, most people use a service account already so I think its exactly the same.
Here is that link: [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

Happy to hold this for a bit to hear if others in the community have ideas.

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately I dont know of any less privaledged way to do this. The requirements would be the same for an external user as for a member user, most people use a service account already so I think its exactly the same.
Here is that link: [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

Happy to hold this for a bit to hear if others in the community have ideas.

**Comment by GithMen** [comment]
Hello,
The link provided details account preprequisities needed in setup process and not in update process.
I would like to know if the user account that will be used to update the solution must have the same licenses and roles ?
Any help will be appreciated.
Thank you

**Comment by Jenefer-Monroe** [comment]
Yes that's correct. Whatever account is used to install or upgrade will be the account used to run the flows. And those are the requirements to run the flows.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
