### ISSUE TITLE
CoE Starter Kit - usable role instead of Power Platform Service Admin

### ISSUE THREAD

**Issue by gajdinet** [microsoft/coe-starter-kit#7647]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, we want to install CoE Starter Kit but our customer has sensitive data and own business policy. Their security team don't feel comfortable to assign us Power Platform Service Admin or similar admin role.
My question is, is there a way to create custom role similar like Power Platform Service Admin but with restriction on detailed features (ex: access to any feature on CRM)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2276

**Comment by Jenefer-Monroe** [comment]
If you install the kit without PPAdmin Role then it will gather data for the environments to which you have System Administrator access. And then the kit will work for those with some caveats. For example you may not be able to reassign apps. 

Aside from that, unfortunately, there is no way to gather inventory without this role today.

**Comment by gajdinet** [comment]
Many thanks the response.
It’s confirmed my opinion as well.

Many thanks.
Un cordial saludo. Best regards.
JANOS GAJDOS

Enviado desde mi iPhone. Sent from my iPhone.

2024. febr. 14. dátummal, 14:35 időpontban Jenefer Monroe ***@***.***> írta:

﻿

If you install the kit without PPAdmin Role then it will gather data for the environments to which you have System Administrator access. And then the kit will work for those with some caveats. For example you may not be able to reassign apps.

Aside from that, unfortunately, there is no way to gather inventory without this role today.
