### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Audit Logs | Update Data (V2) Looks new, should this be turned on?

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#7650]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I noticed that this flow was recently added when I updated for the month of February. It was not automatically turned on and I didn't see a description. Just confirming that I should be turning this on. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

na

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2279

**Comment by Jenefer-Monroe** [comment]
This is part of the audit logs set up so that’s the set up wizard that would turn it on. 

If you allay that configured and going you can just turn this one on

**Comment by AUTigers16** [comment]
ok thanks! The setup wizard didn't turn it on, so I wanted to double check since I saw it looked new. Thanks as always.

**Comment by Jenefer-Monroe** [comment]
You bet! Happy to help! OK to go ahead and close this then?

**Comment by AUTigers16** [comment]
Yep!

**Comment by Jenefer-Monroe** [comment]
Hello. I have also created a one-off flow to run which will go back and fix up app information for the ones you missed while the flow was off. 

### Import and Turn On the flow into CoE Environment
Go to https://make.powerautomate.com/ > select your CoE Environment > My flows > Import > Import Package (Legacy)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e2a7c2e7-1e63-4786-a097-b96c481ec51b)

Upload the following flow: 
[Fixupmissedauditlogentries_20240514131140.zip](https://github.com/microsoft/coe-starter-kit/files/15308849/Fixupmissedauditlogentries_20240514131140.zip)

Create the connection and Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/918baa95-1023-431e-a789-757ba832bd11)

When done click Open Flow to view and then back to see details and turn on.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f73573f1-e52b-496e-bdd4-acad4fce7df7)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a2acd671-7c52-4722-882e-9d8a23a52043)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed3f47f0-8c87-4b98-9713-1bfed6a4272b)

### Run the flow
Click Run enter the number of days back you need to go
For example if you missed 3 months of data you would put in 90 (for 90 days)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/74c77b1b-70aa-4f8f-8dcd-a6fdbb4bc4c9)

Flow will turn off your audit logs temporarily while it does this processing. Get everything fixed, and then turn them back on.
