### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by heatheronder** [microsoft/coe-starter-kit#7651]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am having an issue with the "cloud flows" tab on the BYODL power bi report. It is not showing all flows. The "total cloud flows" tile says 27. If I look at the data under byod_flows it is showing 85 rows but we have over 6000 flows in our tenant. I have gone completely back through the setup guide and there are no errors anywhere I can find. Everything else seems to be working so I am completely stumped what else to check. Any suggestions?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What method are you using to get inventory and telemetry?

Data Export

AB#2280

**Comment by Jenefer-Monroe** [comment]
Have you already looked at this known issue? https://github.com/microsoft/coe-starter-kit/issues/7562

The fix is easy for the March release but until then you need to some the fix described here
https://github.com/microsoft/coe-starter-kit/issues/7562#issuecomment-1916812148

 and then delete the history as described in the bug

**Comment by heatheronder** [comment]
I apologize but I don't think I understand enough about how this is all wired up in the backend to know if it's the same issue or not. I see 6792 rows in the Flows table in dataverse and none of them have admin_flowdeleted as true. I have looked at the dataflow that pulls from data lake and I can scroll through 300+ rows so I'm assuming all the data is there. It seems to go missing somewhere between that and Power BI.

**Comment by Jenefer-Monroe** [comment]
Oh sorry I misunderstood anyway, that issue is for the data being pulled into Dataverse
When did you set up the data export?

**Comment by heatheronder** [comment]
I can't remember exactly when we implemented BYODL but it was shortly after it came out. It looks like the issue is definitely with the Power BI dataflow. Somehow during all the transformations it only winds up with 27 rows.

**Comment by heatheronder** [comment]
It's starting to look more and more like https://github.com/microsoft/coe-starter-kit/issues/6577
I see errors on "Get content from json file" under the Transform file column. Can the same fix be applied to the transform file, or does it need to be tweaked for Flows since the one in 6577 is for Apps?

**Comment by Jenefer-Monroe** [comment]
Did you update to the new Json file with Jan update? That is where that fix lives.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/241f9ae8-baca-4a65-b7af-57709e71158b)

**Comment by heatheronder** [comment]
Thank you that fixed it!

**Comment by Jenefer-Monroe** [comment]
HOORAY! Sorry I have a little head cold that really should not have taken so many iterations haha
I'll go ahead and close but please do return if you have other issues in the future.
