### ISSUE TITLE
[ALM Accelerator - Feature]: Service principal owned flows

### ISSUE THREAD

**Issue by nrawev** [microsoft/coe-starter-kit#7652]
### Is your feature request related to a problem? Please describe.

On ALM Acc. canvas app, under configure settings we do not have possibility to choose a service principal as flow owner.
We need to manually assign SP as flow owners as a post deployment activity.

I would appreciate if we can get a feature to choose SP on configure deployment settings.

### Describe the solution you'd like

On configure deployment settings I can choose a service principal.

AB#2281

**Comment by ryanmichaeljames** [comment]
@nrawev I was looking for the exact same thing today and found this:

#7550

**Comment by RajeevPentyala** [comment]
@nrawev Please refer the discussion in the related issue #7550 and let me know if any questions.

**Comment by nrawev** [comment]
Hi Rajesh,

Can we propose to have a feature on ALM acc. to switch ON or OFF tenant pool usage when a service principal is entered as a flow owner.

I noticed that my flow was off and tenant pool usage by default is set to false.

Can you send some recommendation about tenant pool usage when flow owner is a service principal.

Thanks,
Nikunj Ranjan
[he/him]
Solution Architect | Dynamics Center Of Excellence(Dynamics CoE), IZED | Scania IT
Phone +46 700814650
***@***.*** ***@***.***>
www.scania.com<http://www.scania.com/> | www.facebook.com/scaniagroup<http://www.facebook.com/scaniagroup>

***@***.***
***@***.***

**Comment by RajeevPentyala** [comment]
@nrawev Could you please log a new feature request with the details? I am closing this issue since the related issue #7550 has information on how to achieve this.
