### ISSUE TITLE
[CoE Starter Kit - BUG] More than one concurrent Delete requests 

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#7654]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting the error below on SYNC HELPER - Get Security Role Users.

More than one concurrent Delete requests detected for an Entity 5f3d42bd-f9a0-ee11-be37-000d3acc166b and ObjectTypeCode 10332.

![image](https://github.com/microsoft/coe-starter-kit/assets/130560248/1b15b4bf-10b0-4386-9472-1be1d84daec1)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users

### What method are you using to get inventory and telemetry?

Data Export

AB#2284

**Comment by Jenefer-Monroe** [comment]
Seems like an intermittent issue, I've not seen it before.
We are redoing these flows or the March release. Please see if your issue repros once you upgrade.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by dasusairaviteja** [comment]
We are still getting this issue .our team has one flow which got failed with this error
