### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by tono0682** [microsoft/coe-starter-kit#7655]
### What is your question?

It is my first time trying to configure the ALM accelerator. I have followed Microsoft's guide to configure everything. However, I was unclear on updating the security of the service connections once they were created via the Admin app [(steps).](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-app-user-permissions#azure-devops-user-setup)

I have pushed forward and tried to a deploy a solution, however the deploy-validation-solutionName pipeline fails with the following error.

![image](https://github.com/microsoft/coe-starter-kit/assets/67246583/5baa7c26-6afb-4205-9fba-143262f09d90)

I have tried authorizing the resource and re-running but still no luck. 

Any advice would be greatly appreciated.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20240104.1

AB#2285

**Comment by RajeevPentyala** [comment]
@tono0682 Issue appears to be that the 'Service Connections' were not created for your deployment environments. Please follow the steps below to check the availability of 'Service Connections'.

- From your 'Deployment Profile', note down the _Environment Urls_ as shown below.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/4680efbe-560c-4466-9233-0dc47527e29e)

- Navigate to your Azure DevOps project,  **Project Settings > Service connections** and ensure that you have service connections available with the _Environment URLs_ you noted in the above step.
![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/fde9b64d-ca11-4a0c-a9c2-bb475a82863c)

- Please follow the steps documented [here](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#create-service-connections-for-azure-devops-to-access-power-platform) to create 'Service Connections'.

**Comment by tono0682** [comment]
I found that the service connection for the validation environment did not match. Updating this in Azure DevOps resolved the issue.

Thank you
