### ISSUE TITLE
[CoE Starter Kit - QUESTION] preserving existing inventory when installing fresh

### ISSUE THREAD

**Issue by DaveTheTeamsGuy** [microsoft/coe-starter-kit#7657]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

It has been over six months since we upgraded, and I see that there are a number of new features available, so I think we are just going to start with a fresh install in a clean environment.  We only use core for inventory.  Is there a simple way to bring over existing inventory data we've been collecting for the last two years so we don't lose that historical data?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#2287

**Comment by Jenefer-Monroe** [comment]
We do not have a system for this as maintaining it over changes would be too expensive, but there are ways to migrate data between environments including bulk upload, dataflows, and [the dataflow odata connetor](https://learn.microsoft.com/power-apps/developer/data-platform/dataverse-odata-dataflows-migration)

**Comment by DaveTheTeamsGuy** [comment]
Thanks.  Alternatively, if we've not upgraded in over six months, is it still ok to upgrade at this point, or better just to install fresh?

**Comment by Jenefer-Monroe** [comment]
Its fine for you to try and I think you should be ok. The worst case scenario is that you have to start fresh after trying.
Due to the upcoming forced upgrades (with things like the deprecation of the legacy dataverse connectors) I've been testing back further than normal so it should work.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
