### ISSUE TITLE
[CoE Starter Kit - Feature]: Enhancements to DLP Impact Analysis

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#7658]
### Is your feature request related to a problem? Please describe.

Currently Draft policies cannot be deleted or updated

### Describe the solution you'd like

It would be awesome if you could delete draft policies, if they´re rejected.

Furthermore it would be really helpful, if you were able to update existing draft policies. Currently a new one is created everytime you save a policy as a draft.

AB#2288

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, putting on the feature backlog for consideration.

**Comment by Jenefer-Monroe** [comment]
to new dev owner
