### ISSUE TITLE
Dose the COE kit fetched the data of apps and flows built in Teams

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#7659]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can we get the list of apps and flows, connectors and other stuff in COE??
Wanted to know the governance about the apps and flows built in MS Teams.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2289

**Comment by Neel1KNK** [comment]
Can you please help how to fetch them more in detailed.
Thanks

**Comment by Jenefer-Monroe** [comment]
They will be gathered for you when you install the Feb release or later and use the v4 versions of the inventory flows, which is the default in Feb and the only opton as of March. 

So just upgrade to Feb or later and use the Setup Wizard to configure and it will be going for you.

**Comment by Neel1KNK** [comment]
I have updated to Feb release; I was expecting like for eg: we have a place like power platform admin view where we can see like these number of apps/flows. Likewise, do we have a place to look for the apps/flows which are created in Microsoft Teams.

**Comment by Jenefer-Monroe** [comment]
This is the main app where you will see inventory once its complete:
[Power Platform Admin View](https://learn.microsoft.com/power-platform/guidance/coe/core-components#power-platform-admin-view)

If I remember correctly you will see some apps of interest for you when you get to the Finish page.

**Comment by Jenefer-Monroe** [comment]
And you can add filters from related tables like this if you'd like
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/13cb38da-0c65-4f70-94de-1694cfe41511)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2d4f8bf3-d3fd-4305-958e-a40e1ccdd86f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6ca3627e-bc62-431e-b484-1e1c95642075)

**Comment by Neel1KNK** [comment]
You are awesome. Thanks Jenefer.

**Comment by Jenefer-Monroe** [comment]
Thank you for the kind words!

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close out then, but please feel free to return with new issues as you have them!
