### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis not working for scope "Add all Environments"

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#7660]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When selecting the scope "Add all Environments" in the DLP Impact Analysis App, nothing get´s validated. I then tried to export the analysis to csv and checked the Flow and it didnt receive any Environment names as parameter, therefore it failed.

### Expected Behavior

When selecting scope "Add all environments", the system should check for DLP violations for all Environments. When pressing export to csv the Flow should receive all Environment names as parameter.

Expected behavior occured when I instead used the scope "Add multiple Environments" and just added all Environments to it. In this case it triggered the validation correctly and the export to csv flow was executed without failure

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

DLP Impact Analysis

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the "DLP Impact Analysis" App
2. Edit Policy
3. Choose scope "Add all environments"
4. Press next
5. No validation is triggered

AB#2290

**Comment by DominicMeznik** [comment]
Also a suggestion for the export to csv Flow.

Considering larger tenants, it might make sense to embed the "List apps" and "List flows" step into a Loop, going through Environments. Otherwise when selecting too many Environments, the Flow will return a "Request URL too long" error.

**Comment by Jenefer-Monroe** [comment]
Can you post the flow suggestion seperately? We can put on the feature backlog. 
We are shipping an update to the app for March which I believe fixes the first issue you mention.

**Comment by Jenefer-Monroe** [comment]
Yes these were broken unfortunately. This set of issues for the app are addressed for March
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b909aab7-6c01-4a61-b304-73f5b3cb6e8a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
