### ISSUE TITLE
Unable to install 4.23

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#7661]
I had to uninstall 4.22, and now I need to upgrade from 4.8. Or else maybe I need to start clean in a new environment. Can I (or do I even need to) migrate data from my old environment? And how? 

AB#2291

**Comment by Jenefer-Monroe** [comment]
Sorry we do not have a migration story built. But the product does have several techniques available for this including bulk upload, dataflows, and [the dataflow odata connetor](https://learn.microsoft.com/power-apps/developer/data-platform/dataverse-odata-dataflows-migration)

If you are only using us for inventory and not for the metadata you can do (ex compliance and things like that) then its not necessary to migrate the data, you can start fresh.

**Comment by RickKush** [comment]
[like]  Kushner, Rick [USA] reacted to your message:
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Thursday, February 15, 2024 6:51:26 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] Unable to install 4.23 (Issue #7661)


Sorry we do not have a migration story built. But the product does have several techniques available for this including bulk upload, dataflows, and the dataflow odata connetor<https://urldefense.com/v3/__https://learn.microsoft.com/power-apps/developer/data-platform/dataverse-odata-dataflows-migration__;!!May37g!IRyrZ_-R1EGfUzerO8BGojMlBZE3ji6IFleldnKxSoHeOw0SLpfhhfWOkGrQBB0smMCIZygBPJbJkayl6GFMKd31lQ$>

If you are only using us for inventory and not for the metadata you can do (ex compliance and things like that) then its not necessary to migrate the data, you can start fresh.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
