### ISSUE TITLE
[CoE Starter Kit - BUG] CoE BYODL Flows not working

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7662]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This is a different tenant.

Hi Team, 

All datalake flows works except the BYODL Flows. There are over 953 failed rows. 

Thoughts? This is a brand new installation. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/aef93b21-fd3a-448a-aee7-213fbbc52102)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Dataflow for Flows

### What method are you using to get inventory and telemetry?

Data Export

AB#2292

**Comment by Jenefer-Monroe** [comment]
Did you check the issue with the "Next Refresh" from the other bug? That is what this error message had always meant in the past.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
