### ISSUE TITLE
Error in 'Configure Deployment Settings'

### ISSUE THREAD

**Issue by tono0682** [microsoft/coe-starter-kit#7663]
### What is your question?

Within the ALM Accelerator for Power Platform application, when I click on **Configure Deployment Settings** I receive two error messages.

1. Error getting solution dependencies: SearchAADGroups.Run failed (error code 502)
2. Error reading environment configuration: SearchAADGroups.Run failed (error code 502)

When I deploy the solution, the pipeline succeeds. However, I noticed that the environment variables havent updated based on my config settings. I suspect this has to do with the second error. 

Any ideas on what I need to do to resolve the issue. 

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20240104.1

AB#2293

**Comment by v-bjaiswal** [comment]
Hi @tono0682  , We are not able to repro this into our system. For the testing can you do the following test and let us know ?

1. Open the Microsoft graph explorer : https://developer.microsoft.com/en-us/graph/graph-explorer
2. Login with the same tenant by which you are using ALM canvas app.
3. Run this query "https://graph.microsoft.com/v1.0/groups?$select=id,displayName,groupTypes,securityEnabled&$top=999"
4. See if you are getting 200 status if not then please validate the permissions that the logged in tenant have.

**Comment by tono0682** [comment]
> 4. See if you are getting 200 status if not then please validate the permissions that the logged in tenant have.

Hi @v-bjaiswal, I ran the query and received the error "Forbidden - 403 - 158 ms. Either the signed-in user does not have sufficient privileges, or you need to consent to one of the permissions on the Modify permissions tab"
```
{
    "error": {
        "code": "Authorization_RequestDenied",
        "message": "Insufficient privileges to complete the operation.",
        ...
}
```
The listed permissions in _Modify Permissions_ are familiar from when I manually set up a service principal for pipelines that I created manually before exploring the ALM accelerator. Who do these permissions need to be assigned to exactly? The person setting up the ALM accelerator, all users, etc? I've followed the documentation to set up the ALM Accelerator and am unsure what step I have missed.

![image](https://github.com/microsoft/coe-starter-kit/assets/67246583/f5c97bb3-0726-4114-841b-eabae313dad2)

**Comment by v-bjaiswal** [comment]
Hi @tono0682 , hope you have setup the service connection for all the environments which is on deployment profile.
And please try to follow the steps mentioned on the learn.

https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#configure-microsoft-entra-app-registrations

**Comment by v-bjaiswal** [comment]
Closing this ticket. Please raise the new ticket if the issue persists or you have any other query.
