### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE Admin | Sync Template v3 (Custom Connectors) Flow run failed

### ISSUE THREAD

**Issue by avinkaur1** [microsoft/coe-starter-kit#7665]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The flow - Admin | Sync Template v3 (Custom Connectors) run failed with the following error for all environments:
The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/778/properties/connectionParameters/username/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'
![coe error](https://github.com/microsoft/coe-starter-kit/assets/52736218/ba3c9642-5105-495d-81f9-cc8d38442ccd)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

The flow run failed with the following error for all environments:
he API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/778/properties/connectionParameters/username/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'

AB#2295

**Comment by jax-coe-admin** [comment]
Wee are also having this exact issue

**Comment by Jenefer-Monroe** [comment]
Hello this odd a known product issue that has recently started hitting people
Please see https://github.com/microsoft/coe-starter-kit/issues/7630

you can create a support ticket to assist in pressing for a fix, or wait while we press internally.

**Comment by avinkaur1** [comment]
Hello, can you please explain how to create a support ticket? Do you mean in the admin portal raising a support incidence? And when you say press it internally, do you mean you will provide a fix? Or would this issue be resolved in the next release?

**Comment by Jenefer-Monroe** [comment]
This is a product issue, not an issue with the kit. Evidently a new connector made it in which violated their type requirements. 
The product has its own release cycles and they are currently investigating a fix now. There is no need for you to create a ticket at this time as we already have traction with the product team.

**Comment by Jenefer-Monroe** [comment]
closing out as a dupe.

**Comment by heloizaleal1** [comment]
The error in the default environment has no longer happened since March 7th
