### ISSUE TITLE
[CoE Starter Kit - BUG] Dataflow errors in the Latest Release (February)

### ISSUE THREAD

**Issue by abhijkumar-msft** [microsoft/coe-starter-kit#7666]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team,

We're seeing the following data flow errors occur after having the client upgrade to the latest release of the CoE Starter Kit:

**Flows Data Flow:** 
![Flow Errors](https://github.com/microsoft/coe-starter-kit/assets/146243200/4615b962-0f53-484c-bf5b-2a7f72660962)

**Makers Data Flow:**
![Makers Errors](https://github.com/microsoft/coe-starter-kit/assets/146243200/dca0f837-7b01-4522-91b9-7dfa8fb58331)

Please advise on next steps as it's preventing important governance work.

### Expected Behavior

The data flows should run as expected.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February Release

### What app or flow are you having the issue with?

Sync Data Flows

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Install the latest version of the CoE Starter Kit and allow it to run during it's pre-scheduled times.

AB#2296

**Comment by Jenefer-Monroe** [comment]
Please validate the following

1. The "next refresh" is only set for makers 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/78ec13e3-6479-42c0-a9f1-80dc802433d6)

2. You applied the fix described here. It will be live in the March release

3. What information is given about the failures for flow
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f9113a14-a8f1-409e-b628-b7860ac78144)
Then click your error row for details on what failed
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2f42e99c-0bdc-4531-9e94-ed9bef507c4f)

**Comment by Jenefer-Monroe** [comment]
And please note also that since the Data Export area is still in preview we recommend people not rely on it for actual business work and instead use it exploratorily.

Please see https://learn.microsoft.com/power-platform/guidance/coe/setup#what-data-source-should-i-use-for-my-power-platform-inventory

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/200b6144-301a-4554-b11c-6a760730128c)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
