### ISSUE TITLE
[ALM Accelerator - QUESTION] Is it possible to run ALM accelerator with GitHub?

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#7668]
### What is your question?

Hi Team, 

Is it possible to run ALM Accelerator with GitHub?
Customer doesn't have Azure DevOps subscription and they are looking to run this with GitHub.
Is it possible to do so? 
If so, could you please guide me for the documentation or any bootcamp video for this.

Thanks.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

February

AB#2299

**Comment by v-bjaiswal** [comment]
Hi @PPMini , As of now we dont support the Github actions. Please look into the pre-requisite to use the ALM tool.

**Comment by PPMini** [comment]
[like]  Mini Kaushik reacted to your message:
________________________________

**Comment by MudassarAliakhtarAli** [comment]
Hi everyone,

**Is it still not possible to run ALM accelerator with GitHub?  or we have any update on this.**
