### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Power BI Administration

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#7669]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Are there any tools that manage Power BI in the core components?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024/1

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2300

**Comment by Jenefer-Monroe** [comment]
Unfortunately no there isnt. They are a separate org and so we are not really PBI experts to do such things.

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
Thank you very much.
