### ISSUE TITLE
[CoE Starter Kit - BUG] Multiple flows failed in last couple of days

### ISSUE THREAD

**Issue by shijuvijSan** [microsoft/coe-starter-kit#7671]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,
From last Friday (16 Feb 2024) we are getting admin mail alerts saying Some of the Sync Flows in the CoE Starter Kit have failed. Attaching the notification email also. Please help us to find the root cause for this. 
[AdminSyncFlowErrors.xlsx](https://github.com/microsoft/coe-starter-kit/files/14325986/AdminSyncFlowErrors.xlsx)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors)

### What method are you using to get inventory and telemetry?

None

AB#2301

**Comment by JaseRuss** [comment]
Yeah I'm getting the same on my environments Here's where the error appears on the Admin | Sync Template v4 (Custom Connectors) flow

<img width="369" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/46083341/8be90849-1255-45f1-a3f7-3d101456779c">

**Comment by Jenefer-Monroe** [comment]
closing out as a dupe.
