### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Report Production_CoEDashboard_February2024

### ISSUE THREAD

**Issue by garyfrostncc** [microsoft/coe-starter-kit#7674]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When opening the report in Power BI Desktop, after entering the environment url and selecting Commercial, I get the following error
21 queries are blocked by the following error
Power Apps
 The column 'admin_applogicalname' of the table wasn't found

![Production_CoEDashboard_February2024](https://github.com/microsoft/coe-starter-kit/assets/60133999/2f1dc8cd-272c-4f71-9644-2d2f9c542faa)

### Expected Behavior

Report runs all queries and shows report details

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Production_CoEDashboard_February2024.pbit

### What app or flow are you having the issue with?

Power BI Report

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2308

**Comment by Jenefer-Monroe** [comment]
Hello this is a new field in the Feb release. You will need to upgrade Core in order to use the new PBIT file.

**Comment by garyfrostncc** [comment]
Core has been upgraded to 4.23 and the CoE Setup and Upgrade wizard has been run and completed
We now get the following error in the report

![Screenshot 2024-02-19 144142](https://github.com/microsoft/coe-starter-kit/assets/60133999/8ff39eec-522a-4a3c-8e11-748a411d8768)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by krische98** [comment]
Hello Jenefer, I am having the same admin_applogicalname error above.  Can you give me the link to "upgrade Core" file?  I am not sure what file I need to upgrade. Thank you.
