### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - COE toolkit flows issue with usage data loading into PowerBI dashboard/report.

### ISSUE THREAD

**Issue by PrakasS1gh** [microsoft/coe-starter-kit#7675]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Team,

We have tried the installation of CoE starter kit (latest version) in our Power Platform environment and have successfully managed to import the solutions and get it up and running. We have set up the inventory components and also set up the Power BI dashboard.

However, we are unable to see the telemetry data of various apps/flows (usages & other data) from our different Power Platforms environments in some visuals/reports of our newly setup Power BI dashboard.

We believe that the flow responsible for populating the various audit logs data of the apps/flows to the respective dataset/tables is failing. Please find the details of the flow below.

Flow Name - Admin | Audit Logs | Sync Audit Logs (V2) (Solution Name – Center of Excellence - Core components)

The flow run instances fail due to error in reading the value of the following environment variable : (Please refer to the below image.)
Environment variable name - admin_auditlogsclientazuresecret

Here is the error observed during the flow run.

{
  "error": {
    "code": "0x80040216",
    "message": "Error occured while reading secret: Value cannot be null.\r\nParameter name: input"
  }
}

![CoE_AuditLog_Flow_Run_Error](https://github.com/microsoft/coe-starter-kit/assets/122976329/07cd1292-0d02-4575-8c88-1c0a8e1d465f)

Here is the screenshot of the Power BI report where we are expecting to see the App Usage and other telemetry data.

<img width="896" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/122976329/9d2a286e-3f64-4849-bcad-e321bcc3f5b2">

### Expected Behavior

We have an older version of CoE toolkit installed in one of our environments and have also set up Power BI report linked to it.
We should be able to view the app/flow data in the PowerBI dashboard in the visuals as shown above in the image.

 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2310

**Comment by Jenefer-Monroe** [comment]
Hello. The Audit Logs are a separate set of steps to set up, they do not come with the inventory. This is due to the Audit Logs setup being harder that most other parts of the kit to setup, it requires and app registration and things like that. 
Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by PrakasS1gh** [comment]
Hello Jenefer,
We have setup the Audit logs flows and we do have an App registration with required API permissions.
We are facing issue with the 'Audit Logs - Client Azure Secret' environment variable.
As it is said in the documentation -
 "Leave empty if you're storing your client ID in plain text in the Audit Logs - Client Secret environment variable."
 
 We have done that but still the flows expect some value in this particular variable. This is the blocker we have as of on now.

**Comment by Jenefer-Monroe** [comment]
You are not using Azure Key Vault so this failure is expected and caught. 
Note that flow always shows the first failure even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

**Comment by PrakasS1gh** [comment]
Hello Jenefer,
I thought that storing the secret in Azure Key Vault was an optional step if we store client ID in plain text in the Audit Logs - Client Secret environment variable.

Could you please send the documentation link for the Azure Key vault setup and configuration and also the necessary permission required to create the Azure key vault.

**Comment by Jenefer-Monroe** [comment]
It is optional, that's what I'm trying to show you here. It fails to get it (because its empty) and just moves on. 
So this failure is caught, and not actually causing the flow to fail. You will need to move further down in the flow to find the terminating failure.

**Comment by PrakasS1gh** [comment]
Hello Jenefer,
Apologies for the delay.

Thanks for helping out, we do see a different failure on going down the flow.
This is the error.
![image](https://github.com/microsoft/coe-starter-kit/assets/122976329/2a94af3b-a2fc-4ae9-add0-71a613fcfb45)

Besides, I also see an error asking to re-establish the connection reference for the flow.
We will get back once the connection reference has been established.

**Comment by Jenefer-Monroe** [comment]
ok great thank you. it looks like something is wrong with the configuration. Likely either one of teh env vars is setup incorrectly or the app permissions. 

Here are the most common mistakes made, please take a look

1. Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

1. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

1. Please be sure that you have entered the secret itself and not the secret id (the GUID). It’s a longer string with a larger character set than a GUID. This one has a tilda for example.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/983a39fb-0b23-4d1f-83d5-8b41bb2bf270)

1. Turn the flows off and back on. Sometimes env vars get stuck in them with old values
1. Validate that you have [started the subscription](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

**Comment by PrakasS1gh** [comment]
Thank you for the information Jenefer, we will set up the same permissions to the App registration and get back in case if we face any issue. Currently we have "delegated" API permission type.

**Comment by Jenefer-Monroe** [comment]
Gotcha. Yes that is likely it, and a very common configuration mistake we see.

**Comment by PrakasS1gh** [comment]
Hi Jenefer,
As we are supposed to provide "Application" permission to the app reg. , so is there a way to restrict the activity feed so it’s not providing all audit logs and just the Power Platform (Flow and App usage) relevant ones?

**Comment by Jenefer-Monroe** [comment]
Unfortunately there is not. The backend service we are using does not offer such permission nor filter granularity.

**Comment by PrakasS1gh** [comment]
We need the approval of our IT security team to grant this permission, I'll let you know once that is done.
Most probably I can provide an update within a day or a two.

**Comment by Jenefer-Monroe** [comment]
Please do let me know!

**Comment by PrakasS1gh** [comment]
Yes sure!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by dghavban** [comment]
@Jenefer-Monroe I am currently experiencing this same issue, followed provided step yet noting worked for me, the flow is still not running, update secret value but still got Error occurred while reading secret: Value cannot be null. Parameter name: input

**Comment by dghavban** [comment]
@Jenefer-Monroe ![Image](https://github.com/user-attachments/assets/9d8a9a53-b41a-49b5-afde-658fbb886c72)
![Image](https://github.com/user-attachments/assets/41339dc9-51f0-4f43-8883-2245a7273d89)
