### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE Admin | Sync Template v3 (Custom Connectors) Flow run failed #7665

### ISSUE THREAD

**Issue by sabrineayadi** [microsoft/coe-starter-kit#7676]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/778/properties/connectionParameters/username/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors) and CLEANUP HELPER - Check Deleted (Custom Connectors)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2312

**Comment by Jenefer-Monroe** [comment]
Hello this is a known product issue which is currently being addressed:  https://github.com/microsoft/coe-starter-kit/issues/7630

**Comment by qxaziz** [comment]
I have to install CoE starter kit on a client environment. I am having the same issue: 

The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/776/properties/connectionParameters/username/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'

The version I am using is: 4.23
Region: U.S

This is urgent. Please tell me when this will get fixed. I need this fixed within 1 day please.

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid this is a product issue and so we have no control over the release. We are pressing but cannot fix ourselves.

Please watch in https://github.com/microsoft/coe-starter-kit/issues/7630 for updates that is where we will notify when the fix is shipped.

**Comment by Jenefer-Monroe** [comment]
closing out as a dupe.
