### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE: Innovation Backlog "Invalid operation: division by zero"

### ISSUE THREAD

**Issue by cooperfl2023** [microsoft/coe-starter-kit#7678]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

#6346, issue still ongoing. I upgraded to version: 3.24015.12
When I open the Innovation Backlog app, the error appears right at the top of the screen. This has been happening for a year + now. I saw the ticket 6346 closed but no fix. What can I do to resolve

### Expected Behavior

I expect it to open cleanly and function completely without errors. The error that I am seeing feels like something will be thrown off if I decide to go through with the full usage of the app.
![InnovationBacklogError20240219](https://github.com/microsoft/coe-starter-kit/assets/136729560/263f0400-aa19-4f9d-af1f-9801a154d6fc)

### What solution are you experiencing the issue with?

Innovation Backlog

### What solution version are you using?

3.24015.12

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Login Powerapps.com
2. Go to Apps
3. Click vertical ellipses
4. Select Play
5. Innovation Backlog begins to load
6. Fully loaded on MS Edge browser, erorr appears.

AB#2314

**Comment by Jenefer-Monroe** [comment]
Hello, yes that issue was closed because it was not the issue we are using to track this work. 
Unfortunately we have not been able to fund the redesign here yet. You can track when that work is complete with https://github.com/microsoft/coe-starter-kit/issues/4285

**Comment by cooperfl2023** [comment]
Hi Jenefer,

I’ll raise this with my Microsoft personnel to see if there is something they can do to try to help or propose. I appreciate the insight and reason. I’ll respond here when I hear back.

Frederick

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid we cannot keep these open indefinitely. Typically we close after 1 week of inactivity. Do you have an update? If not you can always open a new issue later.

**Comment by cooperfl2023** [comment]
From Microsoft:

I have taken some time to investigate the issue and found that there is an ongoing issue from our backend team regarding the connectors. Our team has worked on it and every user who followed the process has resolved the issue.



The workaround/resolution for the issue is:
1.           Open your canvas app in the studio

2.           Refresh the connection to each flow

3.           Save and Publish



I hope this resolves your issue.

I understand you cannot keep ticket open on your end. I’ll continue working with Microsoft. I appreciate your engagement in this issue. I advised my CSAM of the funding part you mentioned so awaiting that answer as well.

Thank you,
Frederick

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jenefer-Monroe** [comment]
ok thank you. I'll go ahead and close this out then. Please do return with other questions and issues later!

**Comment by cooperfl2023** [comment]
Hi Jenefer,

I was given this as a workaround resolution. it is working for me, I have not seen the issue anymore. I also deleted all existing innovation backlog ideas to ensure no corruption is still in the app.


The workaround/resolution for the issue is:
1.           Open your canvas app in the studio

2.           Refresh the connection to each flow

3.           Save and Publish


Thank you,





Frederick Cooper

Senior Systems Administrator

OGE Energy Corp.

Work: (405) 553-3293

Mobile: (405) 953-4494

 [cid:c22226b3-e2e1-4699-9bd8-fa1965eda0af]

“Choose a job you love, and you will never have to work a day in your life." - Confucius

________________________________
