### ISSUE TITLE
[CoE Starter Kit - BUG] Error loading control in Setup and Upgrade Wizard 

### ISSUE THREAD

**Issue by tsileo-wdi** [microsoft/coe-starter-kit#7679]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After successfully importing the Feb 2024 CoE Core Components upgrade, I ran the CoE Setup and Upgrade Wizard.  First, I noticed  this error message at the top of the window: 

SetupWizard>GetCurrentEnvironment.Run failed: { "error": { "code": "WorkflowTriggerIsNotEnabled", "message": "Could not execute workflow '9ea0270c-0cf7-f37a-e7b5-dd2b3a71eee4' trigger 'manual' with state 'Disabled': trigger is not enabled." } }

Also the wizard is still on the last step in the workflow (e.g., where I left off during the last upgrade). 

If I roll the workflow back to the beginning, I acknowledge the first few pre-requisite checks, and then get to the page that says:

"The CoE Starter Kit requires access to your tenant's Power Platform environments. Therefore, the identity you set up the CoE Starter Kit requires admin privileges and licenses. Please confirm your account meets the prerequisites before continuing:"

Below that there is "Error loading control", with a hyperlink to the attached errordetails.txt file.

It is possible that the import/upgrade operation hasn't fully completed yet? I am still seeing the previous version of the solution in the environment. Perhaps that's what is leading to what I'm seeing?

### Expected Behavior

When I upgraded in the past, the CoE Setup and Upgrade Wizard re-started at the beginning of the workflow, without these error messages.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

See description above. Import solution, wait for the import to complete. Open the CoE Setup and Upgrade Wizard. Then I'm getting the unexpected behavior and error message.  

### Anything else?

[ErrorDetails.txt](https://github.com/microsoft/coe-starter-kit/files/14337019/ErrorDetails.txt)

AB#2315

**Comment by Jenefer-Monroe** [comment]
Yes it sounds like upgrade failed. When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. Is that what you see? 
These will never converge or repair on their own, you will need to take action to resolve. 
If you go to history you can find where the failure occurred and download details about it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb0966a6-dbfb-400b-b796-5ecb5d20c1da)

**Comment by tsileo-wdi** [comment]
Ah - yes - confirmed. I actually just needed to wait for the uninstall of the previous version to complete successfully. At least if anyone else searches for this they might come across this issue and stay patient!  :-)

**Comment by tsileo-wdi** [comment]
Closing
