### ISSUE TITLE
Flow's operation is hitting an action limit - [CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by bhupendra14** [microsoft/coe-starter-kit#7681]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

Getting error in Core Component's flows -

"Admin | Sync Template v3 (Solutions)" : Looks like your flow's operation is hitting an action limit designed to protect the connector service being called.

Also checked for any unmanaged layer for the flow  but there is nothing.

Can anyone please suggest a way to get rid of this.

![Screenshot 2024-02-20 095304](https://github.com/microsoft/coe-starter-kit/assets/35683189/2bb9cd02-3932-497e-87a2-c20838942a0c)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024 

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

None

### Anything else?

https://github.com/microsoft/coe-starter-kit/issues/7589

AB#2317

**Comment by Jenefer-Monroe** [comment]
The v4 versions of the inventory use less calls to the backend so that should help. They are available in the Feb release if youd like to turn them on instead. In March they will be the only ones available.

**Comment by bhupendra14** [comment]
Thanks for the response :) , so I'll turn OFF the **Admin | Sync Template v3 (Solutions)** and will turn ON **Admin | Sync Template v4 (Solutions)**.

Quick question - Is this applicable for all v3 , I can see same flows have 2 versions v3 and v4 ???? v3 needs to be turn OFF ???

**Comment by Jenefer-Monroe** [comment]
`@Jenefer-Monroe Thanks for the response :) , so I'll turn OFF the Admin | Sync Template v3 (Solutions) and will turn ON Admin | Sync Template v4 (Solutions).`
Yes that is correct. 
Perhaps just do it for this flow since its causing issues, and then wait for the rest of the V4's for March. That way you wont be missing any data.

**Comment by bhupendra14** [comment]
Sure, I'll do this for this flow only but today again I got the same error for other V4 flows as well.



![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/32baf841-90cd-4eea-baca-5dea9c8a91ef)

**Comment by bhupendra14** [comment]
Sure @Jenefer-Monroe , Thanks for the update.

**Comment by Jenefer-Monroe** [comment]
sound good. closing out then as no further action for starter kit team for now.
