### ISSUE TITLE
[CoE Starter Kit - BUG] Child workflow not published error 

### ISSUE THREAD

**Issue by Farahh26** [microsoft/coe-starter-kit#7684]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

when I am turning on the flows i get a "child workflow not published" error with a workflow guid. The only way i was able to fix it was by turning on all of the flows in the solution and then turning on the flows with these errors. Is there a more efficient way to fix this issue, or a way to search for flows using their guid rather than their names?

### Expected Behavior

The cloud flow would work with no errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows Admin | Sync Template v3 (Ai Models) Admin | Sync Template v4 (Apps) Admin | Sync Template v3 (Business Process Flows) Admin | Sync Template v3 (Desktop flows) (optional) Admin | Sync Template v3 (Flow Action Details) - not turning on Admin | Sync Template v4 (Flows) Admin | Sync Template v3 (Model Driven Apps) Admin | Sync Template v3 (Portals) Admin | Sync Template v3 (PVA) Admin | Sync Template v3 (Solutions) Admin | Sync Template v3 (Driver) CLEANUP - Admin | Sync Template v3 (Orphaned Makers) CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) Admin | Sync Template v3 (Call Updates)

### What method are you using to get inventory and telemetry?

None

AB#2329

**Comment by Jenefer-Monroe** [comment]
Its highly recommended that you use the **CoE Setup and Upgrade Wizard** to install or upgrade the kit. It allows you to not worry about the order of turning flows on / new environment variables etc. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d7901e1e-4c2a-442a-ba27-dfbeb62332bb)

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately that is a known product issue tracked by https://github.com/microsoft/coe-starter-kit/issues/7630
The product team already has a fix and is working to roll out.

**Comment by Jenefer-Monroe** [comment]
product fix will be rolled tomorrow at which time please run through the setup wizard and see where you land.
