### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Solutions)

### ISSUE THREAD

**Issue by LHRDamola** [microsoft/coe-starter-kit#7685]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v3 (Solutions)
The Parse JSON from the flow is expecting a String but gets a Null 
Scope - Put Solutions in CoE
     Apply to each soln
              Get Current Inventory of Solution Objects
                              Select Inventory Workflow
<img width="274" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/155642936/3a425075-9ed5-4a50-bd27-f72d8ec213d3">

### Expected Behavior

The parse JSON was expecting a string but got the Null value for
["String", Null] 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2330

**Comment by Jenefer-Monroe** [comment]
It looks like you have some mal formed data in your table. Can you please check that the following cleanup flow is running and passing? CLEANUP - Admin | Sync Template v3 (Delete Bad Data)

**Comment by LHRDamola** [comment]
Yes this flow runs successfully everyday

**Comment by LHRDamola** [comment]
Hi Jenefer 
Thanks for the help so far 
I think i have neem able to track this error 
From the List related flow Connector 
The Id is extracted from this column admin_flow1.admin_workflowentityid
But one of the rows is not returning values for this columns
"admin_flow1.admin_workflowentityid"
 "admin_flow1.admin_workflowentityid@OData.Community.Display.V1.AttributeName"
 Hence the Select connector is getting null instead of string

**Comment by Jenefer-Monroe** [comment]
Have you opted in to [solution by default](https://learn.microsoft.com/power-apps/maker/canvas-apps/add-app-solution-default) preview feature for these environments?

**Comment by Jenefer-Monroe** [comment]
hello we cannot hold issues open indefinitely, I'd love to see what the issue is here though, so please do let me know if you can find the answer to the question above if you are using  [solution by default](https://learn.microsoft.com/power-apps/maker/canvas-apps/add-app-solution-default) preview feature for these environments?

**Comment by LHRDamola** [comment]
Hi Jenefer
Apologies for the late response been swarmed with some tasks 
To answer your quest we do no use solution by default in the this environments and we have not opted for the feature yet 

Thanks

**Comment by Jenefer-Monroe** [comment]
ok I'm just not sure then, that is a required field for the object. 
Can you please see if you still repro after you upgrade to March? We redid this flow and there is not a v4 version of it.

**Comment by Jenefer-Monroe** [comment]
March is available now so please do upgrade and try it out and return with new bugs if you still have issues.
