### ISSUE TITLE
[CoE Starter Kit - BUG] admin_CoESystemUserID not filled

### ISSUE THREAD

**Issue by ValiPrk** [microsoft/coe-starter-kit#7686]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

I see that the Admin | Sync Template v4 (Apps) flow started to fail and the failure message is that it cannot start a child flow named "SYNC HELPER - Apps" because it is turned off.
When I try to turn on the "SYNC HELPER - Apps" flow, I have the following message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_CoESystemUserID'."}}".

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Apps)

### What method are you using to get inventory and telemetry?

None

AB#2331

**Comment by Jenefer-Monroe** [comment]
Its highly recommended that you use the **CoE Setup and Upgrade Wizard** to install or upgrade the kit. It allows you to not worry about the order of turning flows on / new environment variables etc. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d7901e1e-4c2a-442a-ba27-dfbeb62332bb)

In this case this env variable is used to identify who the SYSTEM user is in the envt. 
Can you confirm, did you use the setup wizard?

**Comment by ValiPrk** [comment]
Should i go until the end or just until the "run inventory flows" part?

**Comment by Jenefer-Monroe** [comment]
Walk through the whole thing. I just shared a random screenshot from when I was testing to show you the "initial setup" tab.

**Comment by ValiPrk** [comment]
Hello, I ran the wizard and can confirm that it solved the issue, it did exactly what you said, turned on some new flows and off old ones.
So, after every upgrade the best approach is to run the wizard in order not to have any unpleasant surprises?
Thank you for your help and collaboration

**Comment by Jenefer-Monroe** [comment]
Yes that is correct. We keep the setup wizard up to date with all changes even better than the documentation. 
Great news! And happy to help! 
I'll go ahead and close this out then.
