### ISSUE TITLE
[CoE Starter Kit - BUG] HELPER - Maker Check Flow Trigger Error

### ISSUE THREAD

**Issue by sambhrama28** [microsoft/coe-starter-kit#7687]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Issue with " HELPER - Maker Check Flow " 
<img width="809" alt="MakerError" src="https://github.com/microsoft/coe-starter-kit/assets/114514468/1e66da05-58c5-4ce8-9813-22a415230d9f">

![image](https://github.com/microsoft/coe-starter-kit/assets/114514468/d6e80961-8383-4334-a061-c27817d36af9)

### Expected Behavior

flow should triggered when called by parent flow but currently facing issue with trigger

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

HELPER - Maker Check

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

old solution was having same issue hence imported new solution and tried, initially faced issue with connections and those got fixed but trigger issue still persists

AB#2332

**Comment by Jenefer-Monroe** [comment]
This is a permission issue. I'm not sure how to resolve but we can try a few things together. 
First can you please see if there are unmanaged layers on the flow? And if there are, remove them and see if that resolves. 

Then if that does not resolve, please try the instructions here: [set flow run only users](https://learn.microsoft.com/power-platform/guidance/coe/faq#set-flow-run-only-users-properties)

**Comment by sambhrama28** [comment]
Hello Jenefer, thank you for your response but unfortunately that solution didn't work for me. I am struck with this issue now. any other solution? thank you in advance

**Comment by sambhrama28** [comment]
<img width="855" alt="Trigger issue" src="https://github.com/microsoft/coe-starter-kit/assets/114514468/9e8d5394-e993-4407-b4aa-8b7cfe2a65c6">
getting this trigger issue now

**Comment by Jenefer-Monroe** [comment]
sorry can you please clarify
1. did you get over the initial issue described above?
2. what flow are you looking at here?

**Comment by Jenefer-Monroe** [comment]
Please share a screenshot showing if all the connections are healthy
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/435d95ea-4e09-4b2f-a209-5f7b0fbf4ed1)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9813d27d-7aed-4b7c-8287-71cb8cfd7f06)

Then also a screenshot showing the Run only user that is configured
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/01d63a4b-c35f-4db9-9478-c6dbb5ec40ab)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9e0279f8-2ae7-4f85-bfd5-b3cb64cd7004)

**Comment by sambhrama28** [comment]
Hello Jenefer ,

i am attaching the screenshots as mentioned. For Connection reference i am not getting see more option but i could see you are getting that
<img width="249" alt="MakerConnectionFeb27a" src="https://github.com/microsoft/coe-starter-kit/assets/114514468/6dc4fc7b-8684-4901-9e68-093fc6142648">
<img width="896" alt="MakerConnectionFeb27" src="https://github.com/microsoft/coe-starter-kit/assets/114514468/542e5906-e517-45b4-a021-365d90eb9b04">

**Comment by Jenefer-Monroe** [comment]
### Layers
Can you please share a screenshot of the layers on the flow
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/68dd3e55-b22f-47ae-ba96-5ede14d31c26)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/751db96c-030d-4a7e-864e-c3c4c4ec63c8)

### Dependencies
Can you please share a screenshot of the dependencies on the flow
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/24932741-250f-4d92-8b1f-3de20295a6be)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dd85d157-fbe0-49d9-b100-9f3465660ef1)

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thank you so much for letting me know the cause! Thats a bummer that it didnt show us an error in the UX but good detective work :) 
I'll go ahead and close then since this is resolved now but feel free to reach out again with new issues.
