### ISSUE TITLE
[CoE Starter Kit - QUESTION] How Approved Capacity and Rated Consumption fields are filled in the "Environment Capacity" Table ?

### ISSUE THREAD

**Issue by JulietteMahe1** [microsoft/coe-starter-kit#7688]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, 
I try to understand how the "**Approved Capacity**" and "**Rated Consumption**" fields are filled in the "Environment Capacity" Table.
Approval Capacity is equal to **2,000.000** (the field updates itself) for many environments, but remains empty for some. Why is this?
The same thing for the Rated Consumption field : Some environments have a value, others don't.

![image](https://github.com/microsoft/coe-starter-kit/assets/159022938/66d4434a-ffda-4959-a27b-c8b97476f4b2)

Thanks to you !

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Environment Capacity Table

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2333

**Comment by Jenefer-Monroe** [comment]
Hello we fill types like Dev Envt for you as there is a soft-capacity enforced by the product of that amount. The rest of the envt types you fill in the approved capacity yourself as shown here: [Environment capacity management & alerting](https://learn.microsoft.com/power-platform/guidance/coe/capacity-alerting)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
