### ISSUE TITLE
CoE BYODL - The trigger is invalid

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#7691]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I did a new clean install in a new environment and I get this error in all 5 of the CoE BYODL Cloud Flows:
The trigger is invalid 'https://flow-apim-unitedstates-002-eastus-01.azure-apim.net/apim/dataflows/shared-dataflows-71c53046-9564-4eeb-94b1-e74f0b91ea5f/api/groups/ab904d39-7fb8-ec16-8c8b-22c15e79381e/dataflows/15d29316-3f29-44ad-a902-1d6c5757c4e6/onrefreshcomplete?workspaceType=Environment'

I verified that ab904d39-7fb8-ec16-8c8b-22c15e79381e is the new environment GUID.

### Expected Behavior

The triggers should be good

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

all 5 CoE BYODL - When... flows

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

View flow details

AB#2336

**Comment by RickKush** [comment]
Also CLEANUP HELPER - Check Deleted v4 (Custom Connectors) is failing many times with:
The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/777/properties/connectionParameters/username/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'

**Comment by Jenefer-Monroe** [comment]
Hello. We have been through this together in the past I believe. This is due to the input to those flows not being the actual GUID of the envt but the special string we found together. 
If you want to continue looking at Data Export path, can you please review the issues we've done together and try to fix up what we've covered in the past? 
I do believe you are going to need to revert to Cloud Flow technique or hire out a partner to help you with setup.

**Comment by RickKush** [comment]
I am going back to DebugBYODL>ConfigureEnvironment, but it fails. What should I put in for the Group? Should it be the envt GUID? Or the name, like CoE Power Platform Gov'n?

**Comment by Jenefer-Monroe** [comment]
Here is where I walked you through this before: https://github.com/microsoft/coe-starter-kit/issues/7595#issuecomment-1936741640

Please give that a try.

**Comment by RickKush** [comment]
I found issue #6042 which instructs to clear the Current Environment env var which I did, and then I got the Group dropdown with my env name. It put this into the Group, ab904d39-7fb8-ec16-8c8b-22c15e79381e-31c688f59-us

**Comment by Jenefer-Monroe** [comment]
Plesae follow the instructions from here: https://github.com/microsoft/coe-starter-kit/issues/7595#issuecomment-1936741640
which include using a drop down to select the group.

**Comment by Jenefer-Monroe** [comment]
looks like you moved on from this issue per other bugs so I'll go ahead and close
