### ISSUE TITLE
Detect app or flow used in context with Dynamics 365 apps or solutions?

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#7693]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi CAT team,
Is there any feature at COE kit to detect app or flow used in context with Dynamics 365 apps or solutions?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2339

**Comment by Jenefer-Monroe** [comment]
Hello. We do not focus on these and do not have any for testing in our test tenants, but they should work by default if you are on a somewhat recent version of the starter kit ~Nov 2023 (4.17) or higher.
What version of Core are you on? And have you looked for them in the inventory?

**Comment by SOMSGH** [comment]
Hello Jenefer,

Thanks for info, I'm at 4.23 version, where can I check D365 related apps and flows?

**Comment by Jenefer-Monroe** [comment]
You can just see if they are in the inventory. If you know the name of an environment / app / flow that is D365, you can try to find it here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/295edc2a-b3e6-4305-b50b-1c9fa0eae76f)

**Comment by SOMSGH** [comment]
Thank you for the information!
