### ISSUE TITLE
[CoE Starter Kit - BUG] Not able to turn on inventory flows at CoE Setup and Upgrade Wizard

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#7694]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

HI CAT team,

I found the account which deployed the kit cannot turn on inventory flows at CoE Setup and Upgrade Wizard (setup flows are successfully turned on)

While trying to turn on the inventory flows manually , it through below error message:

Turn on failed. Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is 'XXX-191cf08f35bf'. Connection 'admin_CoECorePowerAutomateAdmin' to 'shared_microsoftflowforadmins' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".

any clue? thanks for your assistance !

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Jan 2024

### What app or flow are you having the issue with?

inventory flows

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2340

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
