### ISSUE TITLE
Power Pages solution :can't get the connection references for a power pages solution

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#7695]
### Describe the issue

Hi,

Hello, when I try to display the connection references from AA4PP for a power pages solution, I get this error message. However, I have no problem displaying the connection references in other solutions located in environments other than Power Pages.

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/74bc407d-d9f9-4718-8054-737942d1188d)

The error details from the flow is "the response in not in a JSON Format"

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/b37c0868-ce0b-4658-a209-2dcee53cc7f8)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20240104.1

### Steps To Reproduce

1. Select a power pages environnment
2. Select configure deployment settings

AB#2341

**Comment by v-bjaiswal** [comment]
Hi @tocri , We will check and get back to you. Thank you for raising the issue.

**Comment by tocri** [comment]
Forget it, it was my solution. I have created and another solution and the error disappear.
