### ISSUE TITLE
[CoE Starter Kit - QUESTION]  How do you delete a row of data in the Power Platform Admin app, without also deleting the object?

### ISSUE THREAD

**Issue by clauslorenzen** [microsoft/coe-starter-kit#7699]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How do you delete a row of data in the Power Platform Admin app, without also deleting the object?  I need to remove some rows (e.g. flows), but when I click delete, I am prompted with a warning saying that it will also delete the flow from the tenant, not just from the inventory list. 

Can't find any documentation on this, I need to ensure that deleting the row via e.g. solution table - won't still trigger an automation to delete it from the tenant. 

![2024-02-21_08-41-27](https://github.com/microsoft/coe-starter-kit/assets/160688111/1799ee89-5242-498d-9c91-adf38a3a3b2d)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Power Platform Admin 

### What method are you using to get inventory and telemetry?

None

AB#2345

**Comment by Jenefer-Monroe** [comment]
Hello. Yes there are two delete concepts for inventory

1. **Delete from tenant**, which will then result in it being deleted from inventory.
2. **Delete from inventory**, which just deletes from the inventory, which result in it being left in tenant, and added back into inventory next run assuming it was a real record and not something for test.

The option in Power Platform Admin app that you show deletes it from the tenant. We do not offer UX here to just delete from inventory. But this can be done with other PP features. 

You can open the table for Edit in Excel if you need to delete a bunch of records, or you can open the tables in the PP UX if you just need to delete a few.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c6bb0e70-841d-4fdf-9766-95f53b44aa11)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b3fc675e-f50b-4b51-9dd8-19a92b83d41b)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c76461f8-cd0c-4a0b-ab18-94985b71f0cc)

**Comment by clauslorenzen** [comment]
Thank you for the detailed answer.

**Comment by Jenefer-Monroe** [comment]
You are so welcome, we are here to help. 
I'll go ahead and close then but please do feel free to reach out with new questions as you have them.
