### ISSUE TITLE
Fail to Get Security Group in Driver flow

### ISSUE THREAD

**Issue by bhupendra14** [microsoft/coe-starter-kit#7701]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting multiple errors in the latest CoE release.

SYNC HELPER - Get Security Role Users
Admin | Sync Template v4 (Driver)

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/627be75f-336e-4382-aa72-00dc446d56b5)

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/71528fc9-3fb2-4182-98c3-25d218463b7b)

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/a7ef8a99-14d0-4748-9b39-5d1baaee9fa2)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024 

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Driver)

### What method are you using to get inventory and telemetry?

None

AB#2347

**Comment by Jenefer-Monroe** [comment]
Can you please tell me, what is returned here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bea6199f-16fe-4622-8d93-99d965690d00)

**Comment by bhupendra14** [comment]
@Jenefer-Monroe  sure, here is the below output.

" {"error":{"code":"AuthorizationFailed","message":"The authentication credentials are not valid."}} "

**Comment by Jenefer-Monroe** [comment]
I think this expression here will make the flow not fail anymore

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5cef7943-4a44-4fb4-b034-11d02d9212b3)

`@{if(equals(outputs('Get_Security_Group')?['body/error'], null), coalesce(first(outputs('Get_Security_Group')?['body/value'])?['displayName'], 'Error'), 'Error')}`

**Comment by Jenefer-Monroe** [comment]
However I'd also like to know why it failed. Can you see if the group exists? You can search by GUID in Azure
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/302c55d8-f447-47b3-a768-a0700f44d11d)

And also see if you have any broken connections in the envt? 
Browse to the connections in the envt. If there are any broken connections please repair them
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2198fb17-1107-4851-a744-f3b34e89d11d)

**Comment by bhupendra14** [comment]
strangely Admin | Sync Template v4 (Driver) version only failing but Admin | Sync Template v3 (Driver) is working without any error so I did the changes but also turn OFF the v4 version.

**Comment by Jenefer-Monroe** [comment]
Yes V3 did not have this Security Group work so it will not fail. I'll go ahead and resolve with the above change then for March.
