### ISSUE TITLE
[CoE Starter Kit - BUG] Delete Environment Connector 404 not found and deletes environment

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#7702]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When using Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments
There is the below error when the flow gets to the Delete Environment action. 
    "body": {
        "statusCode": 404,
        "message": "Resource not found"
    }
}
When I checked the Admin centre the Environment is showing as deleted but the flow never completes the rest of the steps to let the user know the environment has been deleted as they have not provided a business justification.
The record is updated when the CLEANUP - Admin | Sync Template v4 (Check Deleted) runs and the field updated "Has the environment been deleted?" to Yes

### Expected Behavior

I would expect there not to be an error on the delete environment connector so the flow can then continue the steps and notify the maker that the environment has been deleted.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.15

### What app or flow are you having the issue with?

Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

I have created a button flow out with the solution to test the connector and receiving the same results.

AB#2349

**Comment by Alyson95170** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/050d539d-a167-4e15-b660-4ccbde6bf944)

**Comment by Jenefer-Monroe** [comment]
Ok so this is behaving as I expect then, since the team was already deleted the deletion here failed and we caught the failure so that the flow doesnt fail. I dont think we would want to ping the user here, they may have been the person that deleted the team themselves.

Can you please let me know what you think I'm missing here?

**Comment by Alyson95170** [comment]
Yeah the environment is being deleted even through the connector has an error stating 404 not found.

I created a new test environment, ran the flow to ask for a business justification, I then ran the driver flow to update the records and manually changed the date the business justification was asked for.
I then ran the weekly clean up for Teams environments which then had the error at the delete environment connector which did then not progress to the next steps to let the user know they environment was deleted.
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/3eeb8ad8-836d-4f3c-b299-26d08c1d7128)


I created a button flow out with the solution with just the 1 action and I see the same error.
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/36423a6c-33d9-4b8b-997a-f6ecc73b9d41)

**Comment by Alyson95170** [comment]
This then shows as deleting in the admin centre 
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/bca8dab1-0712-4af0-a518-cb0052ea79ec)

**Comment by Alyson95170** [comment]
Yeah let me just change the API and I will let you know

**Comment by Alyson95170** [comment]
Amazing thank you 2021-04-01 is now working and running the rest of the flow

**Comment by Jenefer-Monroe** [comment]
Wonderful thank you for helping me debug! I fixed the flow for this product change then for March release.
