### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE support for Microsoft Copilot Studio in Teams

### ISSUE THREAD

**Issue by Vegaspower** [microsoft/coe-starter-kit#7703]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Team, 

Currently users can create a chatbot using Teams: Microsoft Copilot Studio. This will result in a Dataverse for Teams environment to support the chatbot. We have options to monitor and act on the Dataverse for Teams environments. 

- **In the documentation it says the following regarding chatbots created by using Microsoft Copilot Studio:** Currently, bots created by using Power Virtual Agents in Microsoft Teams environments aren't discoverable in the CoE Starter Kit. Source: https://learn.microsoft.com/en-us/microsoft-copilot-studio/composer-concepts-preview 

**Two questions about this:**
1. Are there currently plans to support chatbots created using Microsoft Copilot studio in Teams for CoE Starterkit? (couldn't find anything in the backlog)
2. What options are the currently available to apply governance on these bots? Beside tenant wide settings: https://learn.microsoft.com/en-us/microsoft-copilot-studio/security-and-governance 

Hopefully you can help me with this inquiry. Please reach out if additional information is needed.

Kind regards,
Johan

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2350

**Comment by Jenefer-Monroe** [comment]
Hello that limitation was resolved with the move to the Modern Dataverse connector to gather the inventory. 
In Feb this is available for you to opt into use the V4 flows, and in March (est ship 3/6/24) it will be the default and only inventory mechanism available. 
So upgrade in a few weeks and you will see Bots in Teams envts!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Vegaspower** [comment]
Thanks for the response, we will update it soon.
