### ISSUE TITLE
[CoE Starter Kit - QUESTION] Role to use Set App Permission and Set Flow Permission

### ISSUE THREAD

**Issue by JulietteMahe1** [microsoft/coe-starter-kit#7704]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 
I have a question on the permission to access to the "Set App Permission" and the "Set Flow Permission".
![image](https://github.com/microsoft/coe-starter-kit/assets/159022938/67a4285b-5413-4f51-b268-743b2c41085d)

To use these app correclty, the  Power Platform administrator role is required for each admin ? (I'm talking about Office 365)
![image](https://github.com/microsoft/coe-starter-kit/assets/159022938/0065942f-8779-4fc3-b54c-3f5351a28935)

In this case, all admin can manage all applications in all environments? even on applications where they are not owner?

Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Set App Permission and Set Flow Permission

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2351

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
