### ISSUE TITLE
Power Platform Admin View App - Makers - Active Flows they 'own'

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#7705]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I'm trying to hunt down a Service Account that has been over used as flow owner across many flows and environments.

When I use the Admin View --> Maker--> Active Flow view, I can see the flows the SA owns, and what environment they are in.  However when I go to the actual flow details, the Owner in many cases is now the Pipeline Service Principal which is correct.

Why doesn't the Admin View owner data match the actual current ownership? 

I need this to work to find what environments, and flows need to be changed!  There are currently 100s listed in the Admin View and I don't want to check them one by one to see if they are actually still owned by the SA.

Admin View Owner
![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/f190c11c-6546-4527-b4fa-faa91ab760c0)

Actual Owner
![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/320bda1e-2c41-45db-917a-f8025532124a)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2353

**Comment by RahulBojji** [comment]
@PPCan  Can you please confirm which architecture are you using to fetch this information whether its Cloud Flows or Data Export ??

**Comment by PPCan** [comment]
Cloud flows

**Comment by PPCan** [comment]
Also, I deleted the records from the inventory table, reran Driver and the records came back wrong again.

**Comment by RahulBojji** [comment]
Can you please check the run history of the "Admin | Sync Template (Flows)" by adding below column for the environment you are facing the issue

<img width="523" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/a4e0c45c-5879-477f-b423-da4604747fc7">

Open the latest run history for that environment and see what you get here 

<img width="767" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/5e8a895c-4d33-446f-880d-b9265d9fbede">

If the Creator object if matches with the service prinicipal object id or not

**Comment by RahulBojji** [comment]
can you please confirm if the owner of the flow is modified in the power automate portal after creating it??

**Comment by pwbyrne** [comment]
Yes. If you read my original post, you'll see that I mentioned that the actual flow owner is different from the owner show in the Admin View.  At some point it must have changed.  

Also, as I mentioned I deleted all the data from the Flows table related to that flow, and when the inventory ran again, the flow table records still showed the wrong owner.

If I need to be more clear please let me know, otherwise I have provided what I believe is all the information you need.

**Comment by RahulBojji** [comment]
we have not yet updated the kit to use the information from changing the owner in the product but it is on our backlog. We are waiting for one more product change and then will fund this work. Please see https://github.com/microsoft/coe-starter-kit/issues/3052
In the meantime you likely want to set it in both places. In the product so that its correct from the product pov (the most important piece) and then in the kit so that the processes can see it

**Comment by PPCan** [comment]
@RahulBojji  @Jenefer-Monroe  

What is the current behaviour? The flow saves the owner that it finds the first time only?  Like I said I deleted the rows from the inventory and they came back with the same owner that was wrong.

Can you explain what the change is? I'll implement immediately and wait for the update.

**Comment by RahulBojji** [comment]
@PPCan Currently the change in the flow owner is not available to us programmatically via any api. If you delete the records also, it will return the same set of records with the previous owner. For time being, just to make it same at both places you can update the owner in the power platform admin view manually.

**Comment by PPCan** [comment]
@RahulBojji Yes. I tried to see if there was any of the connectors that could filter by owner for flows, and the closet thing is 'My Flows', which is useless for searching for a specific owner.

When it returns the exact same wrong owner, what are you reading from if you can't get the owner..?

BTW do you know if searching by owner if available in Powershell or Graph API?

**Comment by RahulBojji** [comment]
We consider the creator of the flow if I am correct. 

On the power shell or Graph Api I am not sure whether there is any such api's available

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for the starter kit team
