### ISSUE TITLE
Flow "Copy of - CLEANUP - Admin | Sync Template v3 (Check Deleted)" Failed[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by venkata-vijay** [microsoft/coe-starter-kit#7707]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The "Copy of - CLEANUP - Admin | Sync Template v3 (Check Deleted)" has failed with the below error:

WorkflowOperationParametersRuntimeMissingValue. The 'inputs.parameters' of workflow operation 'Update_Last_Run_Fail' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'
![Flow Issue](https://github.com/microsoft/coe-starter-kit/assets/160828280/14ff1f90-2914-47e1-b6b0-48726bbfeb7a)

### Expected Behavior

Flow should run successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Copy of - CLEANUP - Admin | Sync Template v3 (Check Deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. It is a scheduled flow which run every 2 weeks.
2. The last has failed with error

AB#2355

**Comment by venkata-vijay** [comment]
Hi @RahulBojji ,
This is the only flow in our solution. Attached screenshot for reference.
![image](https://github.com/microsoft/coe-starter-kit/assets/160828280/46f76645-0279-4729-b274-b40812ee5b6e)


The last successful run for this flow was on 3rd Feb (as it only runs every 2 weeks)
![image](https://github.com/microsoft/coe-starter-kit/assets/160828280/9a9a7883-eee7-4f34-8dc4-81ffe2e05e15)

**Comment by RahulBojji** [comment]
Can you please share screenshot of the list of solutions you have installed in your environment just like below. Please make sure you are expanding the highlighted columns.

![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/c1bee28e-e410-4cf3-92b6-45ad789ab3d0)

**Comment by venkata-vijay** [comment]
Please find below the requested screenshots:
![image](https://github.com/microsoft/coe-starter-kit/assets/160828280/f74b3c17-3e3b-43e5-9223-1c1b5422adec)

![image](https://github.com/microsoft/coe-starter-kit/assets/160828280/18ee3a6c-47fc-4838-90c4-31038aeaaec8)

**Comment by RahulBojji** [comment]
i believe you have some made customizations to the flow "CLEANUP - Admin | Sync Template v3 (Check Deleted)" by making a copy of it. The original flow "**CLEANUP - Admin | Sync Template v3 (Check Deleted)**" will be in the Center of Excellence - Core Components solutions, please check that if that is failing as well.

**Comment by venkata-vijay** [comment]
Thank you!
Will check and get back to you.

**Comment by venkata-vijay** [comment]
Hi Team,
This issue is resolved.
Thank you so much for your help and support.

**Comment by Jenefer-Monroe** [comment]
Wonderful! I'll go ahead and close then. Thank you
