### ISSUE TITLE
[CoE Starter Kit - BUG] Flow "Admin | Sync Template v3 (Custom Connectors)" Failed

### ISSUE THREAD

**Issue by venkata-vijay** [microsoft/coe-starter-kit#7708]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Flow "Admin | Sync Template v3 (Custom Connectors)" Failed with the below error"

The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/779/properties/connectionParameters/username/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'
![Flow Issue 2](https://github.com/microsoft/coe-starter-kit/assets/160828280/63079b3b-31de-49f2-960d-2d126bc2f565)

### Expected Behavior

Flow should run successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Custom Connectors)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. The last has failed with error

AB#2356

**Comment by Jenefer-Monroe** [comment]
Will go ahead and close as a dupe so we can keep all communication in that issue.
