### ISSUE TITLE
[CoE Starter Kit - BUG] App Deep Dive Power BI Report Filtering not working correctly or displaying correct numbers

### ISSUE THREAD

**Issue by kubilaygithub** [microsoft/coe-starter-kit#7709]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We would like to know how often and with how many people an App/Flow is shared.
However, we do see an App Deep Dive, but the value does not correspond to the Power App itself.
Where can we see this clearly in terms of content?

![1](https://github.com/microsoft/coe-starter-kit/assets/160839894/8485394e-d18f-4f9c-952a-1fa240ddd1d8)

I also added a user and waited for the result in sync, but the number remains the same.

![2](https://github.com/microsoft/coe-starter-kit/assets/160839894/eb99f1b4-5165-4bf3-8abd-319e43503ecb)
![3](https://github.com/microsoft/coe-starter-kit/assets/160839894/e49a4886-3838-4b43-8232-499af294052f)
![4](https://github.com/microsoft/coe-starter-kit/assets/160839894/11084956-3090-4ea9-bc4b-d3728e7bf4d8)

Also the run of '' Cloud flows > CleanUP - Admin | Sync Template v3 (Power Apps user Shared With)'' that I started manually was successful, but the overview of how often the apps mentioned were shared has not changed.

![5](https://github.com/microsoft/coe-starter-kit/assets/160839894/6f7bf9f4-8461-4186-af1a-e78ae5ef5e05)
![6](https://github.com/microsoft/coe-starter-kit/assets/160839894/d97d9a26-ea75-49af-9d1f-9f0d6e6ff4d2)

But this morning I made the nice discovery in PowerBI that a share has been added to the App:

![7](https://github.com/microsoft/coe-starter-kit/assets/160839894/3b3732ae-3002-4d47-a938-28bfc0b42303)

After I notice that the number is actually incorrect even though it has been updated:

Do you have an explanation for this?
Look at the Power App permissions (share) and see the App Deep Dive in CoE.
These are incorrect in terms of value.
 
3 people and 1 group (120 people).
 
Total Shared with 6 and Unique Users 20 shows the App Deep Dive.

![8](https://github.com/microsoft/coe-starter-kit/assets/160839894/6930dad3-d427-45b2-ac89-bd9896c12ae5)
![9](https://github.com/microsoft/coe-starter-kit/assets/160839894/56c825ca-4642-47ee-84d1-2604ead8d6a6)
![7](https://github.com/microsoft/coe-starter-kit/assets/160839894/4a984130-6033-45d6-86be-5bdcb34a483a)

### Expected Behavior

Center of Excellence - Core Components
1 month ago
4.22
Yes
Power Platform Admin
Checked by publisher

![2024-02-22 11_05_53-Power Apps _ Solutions — Mozilla Firefox](https://github.com/microsoft/coe-starter-kit/assets/160839894/0fa953ee-8c96-4d14-9472-262bfaca4aed)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

App Deep Dive

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2357

**Comment by Jenefer-Monroe** [comment]
Hello there are a few issues with this count currently. 

First note that the group count does not deep dive into it to get full count of a group only its first level. This is something we will be repairing in the next few months. 

Secondly the helper flows are very high hitting and as such can only run every other week. Not sure we can change that but we do plan to do a dive to see if there is any way to refactor and make more often. 

Total Shared is a rollup field and so sometimes takes a while to run.

Then on top of this please note that the PBI has its own refresh cycle that you set when you configure. 
I suggest after reading the above, if the number still looks incorrect with this new knowledge, please see if it looks correct in the Power Platform Admin View app
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d6f9435e-bd0d-4e97-a9fb-8380e01b586c)

**Comment by kubilaygithub** [comment]
rgergerg

**Comment by kubilaygithub** [comment]
Hello Jenefer,

I have discussed it with my colleague and you can archive the ticket.

If we have any questions regarding the COE starter kit in the future, we will post them on this forum.

**Comment by Jenefer-Monroe** [comment]
Wonderful thank you so much and have a great day
