### ISSUE TITLE
[CoE Starter Kit - BUG] Null Unique Users and # of Sessions for Model Driven Applications.

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#7710]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

CoE Power BI Report not showing the Unique Users and # of Sessions for Model Driven Applications.

### Expected Behavior

CoE Power BI Report to show the Unique Users and # of Sessions for Model Driven Applications.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Production_CoEDashboard Power BI

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open Production_CoEDashboard.
2. Navigate to App Deep Dive.
3. Filter Model Driven Application.
4. Check the Unique Users and # of sessions for the Model Driven Application.

### Anything else?

N/A

AB#2359

**Comment by Jenefer-Monroe** [comment]
Hello, yes unfortunately that information is not available to us for Model Driven Apps, its only available for Canvas.
