### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why is the Developer Compliance Center App not available to users to update compliance details for their apps?

### ISSUE THREAD

**Issue by mrmonto1** [microsoft/coe-starter-kit#7712]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, being that the Developer Compliance Center is a Model Driven App, do users have to have a per user Power Apps or per user Power Automate license to access it?  I have made sure that users are in the appropriate Environment security group and that they have the Basic User role in the COE Production environment.  This is what the users are seeing once they click the link in the compliance email they receive to submit compliance details for their apps.

![image](https://github.com/microsoft/coe-starter-kit/assets/142948654/86628428-dcde-4cd2-a939-e141154a2f1a)

![image](https://github.com/microsoft/coe-starter-kit/assets/142948654/e17f44ea-f57c-4255-bdc6-4a7b099c0dde)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Feb 2024

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2361

**Comment by RahulBojji** [comment]
@mrmonto1 Users needs to have **Power Platform Maker SR** along with the power apps license. Can you please confirm if the below environment variable was set with a appropriate value. See this for more [information](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#all-environment-variables)

<img width="545" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/1cca4995-c672-4457-942a-9cf9a6ef547b">

**Comment by mrmonto1** [comment]
I have confirmed the Citizen Developer Team (users that can't access the Dev Compliance Center) in the COE Production environment have the Power Platform User SR role assigned and the Power Apps and Power Automate for O365 for Government licenses through our Office 365 G5 GCC licensing agreement. I also confirmed that the Dev Compliance Center URL variable is correct and I am able to launch the app from the compliance emails I received with my regular (non-Power Platform Admin) account.  My regular account has both Power Apps Premium for Government and Power Automate per user plan for Government licenses assigned. All of our other Citizen Developers DO NOT have the Power Apps Premium for Government and Power Automate per user plan for Government licenses.

![image](https://github.com/microsoft/coe-starter-kit/assets/142948654/299fba52-eb0a-4b4c-9972-f5b301aec44e)
![image](https://github.com/microsoft/coe-starter-kit/assets/142948654/76e02cf6-3422-4b52-afa1-398fc166df65)

**Comment by RahulBojji** [comment]
@mrmonto1 

As per your latest comment, it looks like you have power apps premium license and you are able to access the app without any issues whereas the citizen developer team has power apps for office 365 license. 
You are checking with us whether is this the reason the users in the citizen developer teams cannot access the app. Is my understanding correct on the issue you are facing? If not, please let me know else let me get back to you with my analysis on this. 
Thanks

**Comment by RahulBojji** [comment]
Looks like with the office 365 license which is now know Microsoft 365 license users have limited capabilities withhin the dataverse. It's not specifically mentioned whether users can access model driven apps or not but accessing dataverse seems to have some limitations.

<img width="593" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/4137a27a-cea8-4d67-aa3b-c1c8e91d12ea">


Please have a look at [this](https://learn.microsoft.com/en-us/power-platform/admin/pricing-billing-skus#capabilities-included) for more information

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
