### ISSUE TITLE
How to rescan outdate status in tables without trigger approval email

### ISSUE THREAD

**Issue by KV-MY** [microsoft/coe-starter-kit#7713]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have few governance approval flows being trigger daily/weekly to app/flow owner/manager, such as Orphaned Object Reassign and Cleanup Old Objects App.  What happen is often these app/flow has been manually updated by admin without user response from the CoE approval email, but the CoE still triggering the approval email because of the outdated status still keep in CoE tables.

1. How could we update the outdated status in coe table with latest Owner and activity status? Perhaps is there a coe flow to rescan the app/flow so the tables could update with latest activity/orphan/owner status without keep sending the approval/notification.

2. Is there an easy way for us to manage these approval email send to owner/manager, such as cancelling the approval on behalf of owner/manager that is no longer require.

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

AB#2362

**Comment by Jenefer-Monroe** [comment]
Sorry its a little difficult to answer without more specifics as each solution area behaves differently. 

There is an orphan check flow that runs weekly which should unmark any orphans that have been cleaned. **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_**

For inactivity, there is this app which can be used to manage outstanding approvals. Do note that it is up for rewrite soon so its not the best. 
**_App and Flow Inactivity Notifications Clean Up_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/de7ef297-0041-4068-83bd-54956d395278)

**Comment by KV-MY** [comment]
HI Jenefer, Thanks for comments.  When i requesting a 30 days trail access to App and Flow Inactivity Notifications Clean Up View, it is requesting access permission from app owner, do you know where could i approve this or grant access to this app?  Thanks.

**Comment by KV-MY** [comment]
Hi Jenefer, Thanks for the comments, CLEANUP - Admin | Sync Template v3 (Orphaned Makers) i can see each completed job for this flow was only checking for first 256 list row from tables, is this explain why some of our updated app/flows still not being cleanup by this flow?

![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/d4133588-6110-4e82-a5dc-f18574782615)

**Comment by Jenefer-Monroe** [comment]
Without an explicit case its difficult to debug. 
Is the app getting the owner updated in the inventory and just the app-is-orphan flag stale? That is the case that would get caught here. 
Where / what tool are you using to fix up orphans?

**Comment by KV-MY** [comment]
Hi Jenefer, i'm not sure where and who updated the new owner before, but from Power Platform Admin Center, i can see the app has new owner assigned with latest modified date.  

Could you guide me where to check the inventory so i can get the app detail and orphan flag status for you?

**Comment by Jenefer-Monroe** [comment]
If you go to the Power Platform Admin View app you can adjust the columns to display the current owner and the App is Orphaned fields. Can you find your app there and see if the owner is correct? And the value in App is Orphaned?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/af46fe15-59b1-4b7b-88cc-295548306bd3)

**Comment by KV-MY** [comment]
From Power Platform Admin View app > PowerApps Apps, i can see the app still showing old owner and still mark as Yes in App is Orphaned

From Power Platform Admin Center > Environment > Resources > Power Apps, i can see the app is showing new owner

i have also check and confirm the app ids are same in above Power Platform Admin portal.

**Comment by KV-MY** [comment]
When i was in Solutions, that problematic app's environment does not show in the selection on top right corner, is that means this app does not has solutions installed?

**Comment by Jenefer-Monroe** [comment]
Are you saying the environment does not show up here? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c9179110-73f9-48c4-9fb7-822cc2efb2e6)

**Comment by KV-MY** [comment]
Yes, the specific environment that has outdated app is not show up there.

**Comment by Jenefer-Monroe** [comment]
OK if its not showing up there then you do not have sys admin access to the environment. 

Does the identity running the flow have the Power Platform Admin Role permanently and directly assigned? 

Has your organization opted in to the [Manage admin roles with Microsoft Entra Privileged Identity Management (preview)](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles) preview feature?

**Comment by KV-MY** [comment]
We dont assign any Power Platform Admin Role to identity running the flow.

Let me get back to you once i opt in for Entra ID PIM in Power Platform

**Comment by Jenefer-Monroe** [comment]
The coe kit does not yet work with this feature: [Manage admin roles with Microsoft Entra Privileged Identity Management (preview)](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)
Thats why I asked, people who have opted in are broken with the kit. The feature is blocked from rolling further until they add a feature we need to make it work with the kit. 

The identity running the flow needs to have the Power Platform Admin Role permanently and directly assigned. 
Please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

Without this you will only get environments for which the identity running the flow happens to have admin access

**Comment by KV-MY** [comment]
Thanks for clarification. in this troubleshooting, i'm using Admin account that has power platform admin role permanently and directly assigned but still cant see the solution for problematic app, i can see many other apps and solutions, just this orphaned app does not has any solutions show up.

**Comment by Jenefer-Monroe** [comment]
So you see the envt of the app in question here now? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c9179110-73f9-48c4-9fb7-822cc2efb2e6)

**Comment by KV-MY** [comment]
it is still not shows up there, but i know why now, i notice that selection is only for environment with "Dataverse", my envt of the app in question does not has Dataverse.

**Comment by Jenefer-Monroe** [comment]
oh ok great. 
So I'm not sure what specific issue you are seeing, but if an app appears to be out of date you can flag it to be inventoried. 
Here is a screenshot showing how to do that for flows, the concept is the same for apps and all other objects: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/191fdbac-2c9b-4a46-8d88-90dd23cef268)

Change this flag to yes and the next day stale objects should be updated.

**Comment by KV-MY** [comment]
Thanks, let me try that and monitor next day

**Comment by KV-MY** [comment]
unfortunately the app still show as orphaned app after 24 hours

**Comment by Jenefer-Monroe** [comment]
I'm still not entirely following here, sorry. 
Please go to the actual object in the product and find who is the owner.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0e142264-43e5-4f9d-905a-5f688ac24b9f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/44c4c9ae-6505-4bc7-83ec-996053a4a224)

Is that person still in the Entra under all users? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a93fa12c-64c2-497b-91e0-9f9e00f9d619)

Do they show as enabled?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f396857f-5940-4d35-b673-ce44e9afc8f8)

**Comment by KV-MY** [comment]
This is the App showing new owner Luiz and his account is enabled in Azure
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/c69e0f4d-f046-4cf4-9e88-02f21b30cf7b)
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/59b9cabb-2a55-401a-9c93-199a252c1756)
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/a9eff297-56e7-4cb9-8830-fadc1ef11488)


But from Power Platform Admin View app > PowerApps Apps, i can see the app still showing old owner Zaid and App is Orphaned
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/76306b42-55e8-4c5b-93a2-db056eec655a)

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by KV-MY** [comment]
Thanks for update, but unfortunately i cant do that, as mentioned earlier, this environment does not has Dataverse so it would not show in the solution

**Comment by Jenefer-Monroe** [comment]
I'm talking about the CoE envt now. I need to know what you have installed. The CoE envt must have a dataverse is otherwise it cannot support a CoE install.

**Comment by KV-MY** [comment]
This is the screen shot for Coe Environment
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/66d2d1e0-c49e-407f-a00e-025983aec214)

**Comment by Jenefer-Monroe** [comment]
ok yes your upgrade failed. That was my suspicion, so you are in kind of an unknown state right now. 
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5c9f5626-b536-43c1-be8f-3e6f35f643b0)

When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. 
These will never converge or repair on their own, you will need to take action to resolve. 
If you go to history you can find where the failure occurred and download details about it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb0966a6-dbfb-400b-b796-5ecb5d20c1da)

**Comment by KV-MY** [comment]
Thanks for the finding, we have separated github case #7880 to work on the upgrade issue.

**Comment by Jenefer-Monroe** [comment]
ok until that is resolved there isnt anything we can do here. It's unclear what state your kit is in so we cant debug further. And the oddness of your behavior indicates to me that once you get on a clean build your issue here will resolve.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by KV-MY** [comment]
Hi Jenefer, follow up on the case that we have been working on. The issue is still not resolved, even though we have solved the build issue.  Wonder should i open a new issue or we can continue from here, let me know, thanks.
