### ISSUE TITLE
Is it recommended to install COE tool Kit solution in non production environment under the production tenant, to understand COE Kit features?

### ISSUE THREAD

**Issue by NANDINV** [microsoft/coe-starter-kit#7714]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is it recommended to install COE tool Kit solution in non production environment under the production tenant, to understand COE Kit features?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2363

**Comment by Jenefer-Monroe** [comment]
Yes that is a good thing that many people do. You can use this env variable to ensure mails and things like that do not go out to anyone but the registered admin while exploring:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1539079d-2cc3-4c82-9ef0-426afc0df34a)

**Comment by NANDINV** [comment]
Id there any risk in configuring the Power Platform Admin credentials in apps and flows in COE kit?

**Comment by Jenefer-Monroe** [comment]
Sorry I dont understand your question. Can you clarify what you mean? What types of risks do you mean?

**Comment by NANDINV** [comment]
There are few flows and apps which will take admin privileges . And while going through the flow we saw that there are actions which will delete a Pva bot or apps or flows.
So I wanted to check if it affects any apps or flows or bots present in our tenant

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
