### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE for Teams

### ISSUE THREAD

**Issue by rghughescec** [microsoft/coe-starter-kit#7715]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, Can i confirm that the CoE is available to install into a Dataverse for Teams environment?
Assuming that is still supported then we only need the Power Automate Premium licence?

Thanks

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2364

**Comment by RahulBojji** [comment]
@rghughescec  If you are trying to install COE into team's environment it's not supported

**Comment by rghughescec** [comment]
Thanks. Does that mean anyone interacting with the CoE requires a Power App user licence also? for example anyone interacting with the compliance app would need a Power Apps per user licence?
