### ISSUE TITLE
Hi, I have the env variable "Also Delete from CoE" set to no. Is there an option within to CoE to delete these records after a certain period of time to clean up the tables? or would I create a separate flow out with the solution for this?

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#7716]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, I have the env variable "Also Delete from CoE" set to no.  Is there an option within to CoE to delete these records after a certain period of time to clean up the tables? or would I create a separate flow out with the solution for this?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.15

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2365

**Comment by Jenefer-Monroe** [comment]
Hello. No there is not, you would need to setup your own flow to do this. 
Do note, however, that with recent releases, we do keep deleted objects in inventory (marked as deleted) for 2 months by default for easy restore, even if you have this set to yes. https://github.com/microsoft/coe-starter-kit/issues/7501

**Comment by Alyson95170** [comment]
Thanks Jenefer

**Comment by Jenefer-Monroe** [comment]
You are so welcome! I'll go ahead and close then but please do return with other questions as they arise.
