### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL Dataflow Flows Mashup Error

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7719]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team, 

We are experiencing an error with the Dataflow flows. This tenant has about 50k cloud flows. All other dataflows are working properly but the Flows data flow is generating a Mashup error. We have gone over the query and the query seems to be working fine, however it errors out upon refresh.  Thoughts?

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/bbd62090-085d-496c-b64b-eb8e03d1f71b)
<img width="703" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/95443860/60a7fced-59fe-48db-bf6b-f4cf617957a6">

### Expected Behavior

Dataflow flows should run

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Dataflow Flows

### What method are you using to get inventory and telemetry?

Data Export

AB#2367

**Comment by Jenefer-Monroe** [comment]
Is this reproing after the fixes we discovered together? With all the changes to envt dataflow, app dataflow, and the flow?

**Comment by Jenefer-Monroe** [comment]
ok please update so that you are in the state we will be shipping for March and let me know if you still have an issue.

**Comment by nasilvae** [comment]
> ok please update so that you are in the state we will be shipping for March and let me know if you still have an issue.

Sounds like a plan will check today.

**Comment by nasilvae** [comment]
Hi @Jenefer-Monroe, We are still getting the same error after checking for junk data in the makers table and applying the cloud flow fix for the makers dataflow. 

We have gone over the tables in the powerquery window and they dont show any issues with the information. We suspect to be an issue with the amount of information being processed at the dataflow level. We are attempting an incremental refresh with this dataflow with the following settings to see if we still get the same issue.

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/a3818f95-761b-493b-82a4-39db18cfd181)

**Comment by nasilvae** [comment]
I can now confirm that even with the incremental refresh we are having that error.

**Comment by Jenefer-Monroe** [comment]
Incremental refresh cannot be used unfortunately it needs to be on full refresh. 

Did you also do the fix to the default envt issue? https://github.com/microsoft/coe-starter-kit/issues/7562#issuecomment-1916812148

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by nasilvae** [comment]
@jenefer this has not been solved, please re-open ticket.
