### ISSUE TITLE
Spelling mistake - Inventory Settings in Power Apps solution

### ISSUE THREAD

**Issue by girishuppal** [microsoft/coe-starter-kit#7720]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Spotted a typo while working on Solution. It seems couple of entries on Settings have a typo

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/be37baa8-708f-4e6b-b686-c80519aeecd1)

![image](https://github.com/microsoft/coe-starter-kit/assets/17232756/86238627-0d93-4e36-9e31-de8e9296f249)

### Expected Behavior

Typo fixed for Inventory

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Jan 2024

### What app or flow are you having the issue with?

Power Apps Solution Area

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Navigate to CoE Environment
2. Create or Open any solution
3. Add existing > setting
4. There you will find some typo error with regards to inventory

AB#2368

**Comment by Jenefer-Monroe** [comment]
Hello. Thanks for spotting. We likely wont fix this though as it would require a little more effort and testing that seems worth it. These settings are not easy to set or test.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
