### ISSUE TITLE
Is there an automatic sync between the security groups of the CoE Kit and Environment Teams

### ISSUE THREAD

**Issue by ecelermi** [microsoft/coe-starter-kit#7721]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

A customer has recently installed CoE Kit to their environment and have seen that CoE Security groups were added as Team to the environment. I would like to learn if there is an automatic sync between the security groups of the CoE Kit and Environment Teams.
Thank you for your help!

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#2369

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid you are asking about product behavior and not kit behavior. We are not staffed to assist with product support issues but I can give you my anecdotal knowledge about these. 
First note that there is not Team automatically created for each SR, I dont believe that is what you are saying please do let me know. 
I use Teams to associate with SRs in another world and they work quite well and yes the product keeps up to date the Team to the Azure SG automatically assuming you've created the correct Team type (Microsoft Entra ID Security Group or Microsoft Entra ID Office Group)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
