### ISSUE TITLE
Nurture : where are the solution assessment results which come from end users are stored within the nurture components

### ISSUE THREAD

**Issue by ecelermi** [microsoft/coe-starter-kit#7724]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Team,
 I am currently exploring the Center of Excellence (CoE) Kit Nurture Components, specifically focusing on solution assessment. While it is evident that we store the questions we ask in Dataverse, I am unable to locate information regarding where the solution assessment results which come from end users are stored within the nurture components.

Could you kindly provide clarification on this matter?

### What solution are you experiencing the issue with?

Nurture

### What method are you using to get inventory and telemetry?

None

AB#2372

**Comment by Jenefer-Monroe** [comment]
Hello, we do not store these, we send them to the admin persona as an email.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
