### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flows using Azure Key vault connector showing as plain text password

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#7725]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi we have a flow that is using azure key vault to get the secret, then using the http connector and within the password field we are using the dynamic content for the secret value.  This is showing in the Power BI report as contains plain text password when there is no plain text within the flow.
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/8224fe2b-db68-4dc7-a04c-ecfe09af2c72)
Is this expected behaviour as using the http connector? If so is there a way to change this if the connector is Azure Key Vault it does not show as Plain text password.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.15

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2379

**Comment by Jenefer-Monroe** [comment]
Hello. No this is not expected behavior and I did just test a case in our env't and it did not flag as plain text for me. 
Can you please tell me what version of Core you have? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/86f64499-6894-48fa-a0bc-42fbfbe27cd0)


You can flag the flow to go through the the system to double check this here in the Power Platform Admin View app:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5fc780c8-3601-4c81-a818-8bd59b50609e)

**Comment by Alyson95170** [comment]
We are using 4.23 core

**Comment by Alyson95170** [comment]
This is the flow that is showing within the Power BI report for containing plain text password

![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/15a5784f-077b-4792-b878-1ccd716adfd3)

**Comment by Jenefer-Monroe** [comment]
oh ok then yes that would count as plain text as the secret is shown in plain text in the flow run
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/33a25ef2-da6b-4915-b02a-a19a0d7b4304)

You can hide the secret if you use an env variable for the secret as we do in the Audit Logs flows.

**Comment by Alyson95170** [comment]
Thanks Jenefer I will give that a try :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action at this time for the kit, but please do return if you have other issues in the future!
