### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to open CoE Setup and Upgrade Wizard

### ISSUE THREAD

**Issue by KevDaRed** [microsoft/coe-starter-kit#7727]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Installing the February update and getting an error when trying to use the CoE Setup and Upgrade Wizard.

The first error I get when loading the wizard is:

**Some components of this app require you to sign in. If you don’t sign in, parts of the app may not work.**

I click sign in and get the next set of errors.

**Please refresh the page and try signing in again. If that doesn't work, contact your admin.**

Error Code: UserNotLoggedIn
Session Id: 6dfaa735-cfed-4f07-81ea-8fc2ac42e5ba
Activity Id: 434c9d6b-5621-4a4c-9004-0d1fa05733f0
Timestamp: Mon Feb 26 2024 11:25:39 GMT+0000 (Greenwich Mean Time)

[PopupError] Failed to open the popup
UciError: [PopupError] Failed to open the popup at s (https://orgee4baa85.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.8083-2402.1:33:924010) at https://orgee4baa85.crm11.dynamics.com/uclient/scripts/custompage.js?v=1.4.8083-2402.1:4:224341

I've logged out, logged in, refreshed the page but nothing, just cannot proceed.

### Expected Behavior

Being able to use the CoE Setup and Upgrade Wizard and complete the installation.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard.

### What method are you using to get inventory and telemetry?

None

AB#2381

**Comment by Jenefer-Monroe** [comment]
Unfortunately you are experiencing issues with the product itself to correctly authenticate you, and not with issues with the kit. 
We have seen people have the wrong user being logged in when they try to log in. Can you please clear the cache in your browser and try again? And then if you still get an error message, see if the USER ID it is saying has failed to authenticate matches your expected one as seen in the Entra ID portal.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by RickKush** [comment]
My problem is similar, but I think it's not the same. Here's the error: 
![image](https://github.com/user-attachments/assets/f88a2b4f-7ee2-4aa0-8701-90a8496efdfb)

I am trying to upgrade to 4.37. I have recently upgraded from 4.8 to 4.13 with no problem.
