### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Inactivity notifications v2 (Start Approval for Flows) referes to admin_appowner

### ISSUE THREAD

**Issue by SannaHoglindABP** [microsoft/coe-starter-kit#7728]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Inactivity notifications v2 (Start Approval for Flows) refers to admin_appowner in condition "Get Assignee". I think this is correct in Start Approval for Apps but not in Start Approval for Flows. Referring to admin_flowcreator here would be more correct. Im not using the flow so I did not run inte any sort of issue but I happened to see this and think that it must be a bug. 

<img width="521" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/150917538/e6b5dba1-4263-49ec-9752-38b9122680f1">

items('Create_Archival_Request_for_Each')?['admin_appowner/admin_userisserviceprinciple']

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

February release

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Flows)

### What method are you using to get inventory and telemetry?

None

AB#2382

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/441bbac4-1d69-4b2e-969d-3ecbe88ac93d)
