### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to provide environment system admin access to COE core, governance admin apps

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#7730]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi CAT team,

In my company, there are environments created by country level IT team, which they do not have PP admin nor D365 admin permission. 

Is it possible to govern the environments just with one set of COE kit. Meaning, just share the COE core, governance apps to these system admins Power Platform Admin SR security role, would they be able to use apps to manage their own environments through **Core, Gov components apps** ? 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.23

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2384

**Comment by SOMSGH** [comment]
Hi @Jenefer-Monroe ,

Thank you for the response, it'll be very appreciated if this scenario can be tested out, since we're not sure what could be the best approach to manage the kit under one tenant.

The global team won't be able to manage the object for country level, while the country level system admin won't be granted as power platform service admin..

We want to avoid country level system admin install their own starter kit since the update is time consuming and would be better managed by global IT. How would you recommend it? 

Would the system admin have a view of the objects from own environment? and be manage obj from own environment? which apps are possible to used by system admin who has per app license and power platform Admin SR?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
