### ISSUE TITLE
[CoE Starter Kit - QUESTION] Which are the apps can be used for environment request management?

### ISSUE THREAD

**Issue by SOMSGH** [microsoft/coe-starter-kit#7731]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I noticed, there is one CoE Admin Environment Request (preview), and 2 environment request canvas apps are deprecated... which are the actual apps that can manage the environment and DLP request at COE starter kit?
![image](https://github.com/microsoft/coe-starter-kit/assets/131751950/12bc1c2c-e99b-42d7-9b3c-ebf6e37c6481)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

CoE Environment Request

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2385

**Comment by Jenefer-Monroe** [comment]
Its recommended you us the preview as its the newer one and the old ones are the ones that we shipped and used in the past will be removed eventually. 

The Maker side of it is in the Maker Command Center:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/87ce35d4-3c95-4075-a85f-b643747fdb67)

**Comment by SOMSGH** [comment]
thank you!
