### ISSUE TITLE
[CoE Starter Kit - QUESTION] Upgrading Power Platform Creator Kit

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#7739]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I noticed that the upgrade instructions for the COE kit (in the link below) don’t mention to upgrade the “Power Platform Creator Kit” so unfortunately, I’ve been forgetting to upgrade the Creator Kit when I upgrade the COE kit.
https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup

I’m currently using the December 2022 release of the Creator Kit.

Will I be fine to upgrade directly to the July 2023 of the Creator Kit (the latest version), 
Or do I have to install the April 2023 release before I install July 2023 release of the Creator Kit?

https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/setup#upgrading
https://github.com/microsoft/powercat-creator-kit/releases

### What solution are you experiencing the issue with?

None

### What solution version are you using?

January 2024

### What method are you using to get inventory and telemetry?

None

AB#2393

**Comment by Jenefer-Monroe** [comment]
You should be fine to upgrade directly. 
We do not test the mix max of builds between CoE and Creator Kit, but generally speaking you should be fine to upgrade Creator Kit less frequently or to do the automatic upgrade path which is their recommendation. 
Please see [install from appsource](https://learn.microsoft.com/power-platform/guidance/creator-kit/setup#option-2-install-from-appsource)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
