### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Delete Bad Data) Not Working

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7740]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow is failing seems to be stuck on one environment. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/51c0944f-907c-4859-ab5e-d154d80ff973)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/eb0ef769-6cb1-4012-9e47-6157fa7d4960)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/899e74e9-e287-4fc0-b016-321a5309c494)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/73da030c-7188-4dee-bcde-fa350959ad76)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/267a24c1-5ba9-4fae-96fa-a82b1d8005e0)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Delete Bad Data)

### What method are you using to get inventory and telemetry?

Data Export

AB#2394

**Comment by Jenefer-Monroe** [comment]
Did the user change the relationship type for these tables? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f70fb7e4-eda0-40e0-8f93-9121af862eab)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
