### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Tool

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7742]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

DLP Impact tool does not list all environments. Its missing the default environment.  Per CoE BYODL we should have 2631 environments, but DLP Impact tool is only showing 1996 environments. We suspect the reason is a limit to how many items we can display in a gallery. Can we have a filter before hand that will help us have different views so we dont go over the limit?

### Expected Behavior

We should be able to evaluate all environments. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

DLP Impact Tool

### What method are you using to get inventory and telemetry?

Data Export

AB#2396

**Comment by Jenefer-Monroe** [comment]
Hello. I believe we have this tracked with https://github.com/microsoft/coe-starter-kit/issues/6555
We have someone owning this app now so hopefully it will be addressed soon.

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close this one as a dupe then.
