### ISSUE TITLE
COE flow time frame duration setting

### ISSUE THREAD

**Issue by expn17ivany** [microsoft/coe-starter-kit#7744]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

how long the flow consider flow/app inactivity and trigger the inactivity flow to maker? Where is the global environment variable setting we can refer and update?

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

AB#2398

**Comment by RahulBojji** [comment]
@expn17ivany "**InactivityNotifications-PastTime-Interval**" and "**InactivityNotifications-PastTime-Unit**" are the two environment variables where we can configure for the inactivity notifications to trigger

Please see [this ](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components#all-environment-variables) for more information

**Comment by expn17ivany** [comment]
Hi Rahulbojji,

Could you please provide me the screenshot as well, so that I can easily look for it.



Thanks.

Regards
Ivan
***@***.***

From: RahulBojji ***@***.***>
Sent: Wednesday, February 28, 2024 2:41 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Yap, Ivan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] COE flow time frame duration setting (Issue #7744)

@expn17ivany "InactivityNotifications-PastTime-Interval" and "InactivityNotifications-PastTime-Unit" are the two environment variables where we can configure for the inactivity notifications to trigger Please see this for more information —Reply


@expn17ivany<https://urldefense.com/v3/__https:/github.com/expn17ivany__;!!MfzFaTml5A!hdhKWe-FzfaS2UxOVxBVHWdWD0688wVKlM0-gDFOeW23qMPNhorJXXv976tXXa-0ZBBIQ_6hTUen50sn8uuEhYceFw$> "InactivityNotifications-PastTime-Interval" and "InactivityNotifications-PastTime-Unit" are the two environment variables where we can configure for the inactivity notifications to trigger

Please see this <https://urldefense.com/v3/__https:/learn.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components*all-environment-variables__;Iw!!MfzFaTml5A!hdhKWe-FzfaS2UxOVxBVHWdWD0688wVKlM0-gDFOeW23qMPNhorJXXv976tXXa-0ZBBIQ_6hTUen50sn8uth8Hd_SQ$> for more information

**Comment by expn17ivany** [comment]
It is ok, I got it.



Thanks.

Regards
Ivan
***@***.***

From: Yap, Ivan ***@***.***>
Sent: Wednesday, February 28, 2024 2:46 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [EXTERNAL] Re: [microsoft/coe-starter-kit] COE flow time frame duration setting (Issue #7744)

Hi Rahulbojji,

Could you please provide me the screenshot as well, so that I can easily look for it.



Thanks.

Regards
Ivan
***@***.***

From: RahulBojji ***@***.******@***.***>>
Sent: Wednesday, February 28, 2024 2:41 PM
To: microsoft/coe-starter-kit ***@***.******@***.***>>
Cc: Yap, Ivan ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] COE flow time frame duration setting (Issue #7744)

@expn17ivany "InactivityNotifications-PastTime-Interval" and "InactivityNotifications-PastTime-Unit" are the two environment variables where we can configure for the inactivity notifications to trigger Please see this for more information —Reply


@expn17ivany<https://urldefense.com/v3/__https:/github.com/expn17ivany__;!!MfzFaTml5A!hdhKWe-FzfaS2UxOVxBVHWdWD0688wVKlM0-gDFOeW23qMPNhorJXXv976tXXa-0ZBBIQ_6hTUen50sn8uuEhYceFw$> "InactivityNotifications-PastTime-Interval" and "InactivityNotifications-PastTime-Unit" are the two environment variables where we can configure for the inactivity notifications to trigger

Please see this <https://urldefense.com/v3/__https:/learn.microsoft.com/en-us/power-platform/guidance/coe/setup-archive-components*all-environment-variables__;Iw!!MfzFaTml5A!hdhKWe-FzfaS2UxOVxBVHWdWD0688wVKlM0-gDFOeW23qMPNhorJXXv976tXXa-0ZBBIQ_6hTUen50sn8uth8Hd_SQ$> for more information

**Comment by Jenefer-Monroe** [comment]
looks like we're set here then. I'll go ahead and close, please feel free to reach out again if you have more questions!
