### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact analysis not displaying applied environment with its Default Envt

### ISSUE THREAD

**Issue by HenningStrand** [microsoft/coe-starter-kit#7747]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Our default environment is assigned to one specific DLP policy. On the overview page of the DLP impact anylysis app this shows as 'applied to: 1 environments' as shown here.
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/9fe1287f-7673-4fea-8c79-3b9fade8bf0e)

However, when I edit the policy and get to the Environments step, this shows 0 in the Added to policy tab. 
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/67eba886-cfa2-4f1e-a751-c71ac2ed3c9d)

In the Impact analysis I get no impacted apps or flows.

### Expected Behavior

I expect to see the actually assigned environment and get results in the impact analysis. In the PPAC UI I see the default environment assigned to this DLP. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

DLP Impact analysis

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open DLP impact analysis app
2. Edit a policy
3. Make a change moving a connector from business to blocked
4. Click next to Environments step
5. Look for the actually assigned environment in the 'Added to Policy' tab

AB#2406

**Comment by Jenefer-Monroe** [comment]
How many environments are in your tenant?

**Comment by RahulBojji** [comment]
@HenningStrand 
Thanks for reaching out. This issue is resolved and is part of march release. While fixing this we have not created any bug to track it, now will use it to track. We will let you know whether to upgrade or not once march release is out. 

<img width="789" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/4db7a5df-da45-46e4-90f0-a55baf10b7b2">

**Comment by HenningStrand** [comment]
OK, but does this mean that the tool has never really worked? In which cases can we actually trust that the tool is giving us the proper impact analysis or not? As there is also the 2000 items limit, does this also mean that for any setup that has more than 2000 flows and apps, it will not provide the correct analysis - also after fixing this bug?

**Comment by RahulBojji** [comment]
Yeah, because of the 2000 limit the impact analysis considers only 2000 items if there are more than 2000.

**Comment by Jenefer-Monroe** [comment]
Thanks for clarifying Rahul, one additional note. If there are more than 2000 results to the impact analysis, you can export them to CSV.
