### ISSUE TITLE
[CoE Starter Kit - QUESTION] Should I use Sync V4 flows or V3?

### ISSUE THREAD

**Issue by inquisitive-identity** [microsoft/coe-starter-kit#7748]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi everyone!
This is my first post ever on Github, so please be understanding. :)

I have recently installed the CoE Starter Kit and enabled all the V4 flows (relatively still new to the whole thing), but I have noticed that, at least for the Desktop Flows and Desktop Flow Runs, the Dataverse connector is giving blank value as output when listing the flows and flow details tables respectively.
I haven't checked the other V4 flows because I've been trying to troubleshoot the RPA Sessions table that came with the CoE kit, which is currently blank, and I saw that the action "List RPA Flow Sessions" in the V4 version queries the "flowsessions" table but provides a blank value.
**The problem is that the entire flow is marked as Successful, but it seems that the connector doesn't provide proper output, which then means that the RPA Sessions table is not populated (if my understanding of the flow is correct), which then means that I might have wrong data from the rest of V4 flows as well, as I imagine they're all using Dataverse in place of Dataverse (legacy)...**

I created a manual simple flow where I used both Dataverse and Dataverse (legacy) connectors in one environment where I knew there were desktop flows, and the Dataverse (legacy) gave the proper output, but the "modern" Dataverse one still gave a blank value.

I am not sure if I explained it well, but I have also attached a screenshot, which will hopefully be more helpful. :)

Thank you very much in advance for the help!

![Dataverse Connector - Blank Value - Desktop Flow Runs](https://github.com/microsoft/coe-starter-kit/assets/156682353/61958b6c-6116-44d7-99b7-1f7f08348848)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024

### What app or flow are you having the issue with?

Admin - Sync Template (Desktop Flow Runs)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2407

**Comment by Jenefer-Monroe** [comment]
V4 are the only ones that will ship starting in the March release as they use the new connector. V3s use an old connector being deprecated by the product team. 

These V4 flows for the Desktop Flows are working for others so I presume there is some issue with the install. 
For that flow in particular its looking for recent flow runs. Can you please browse to the target envt and look at the table manually and see when the last RPA run was performed?

**Comment by Jenefer-Monroe** [comment]
Its a product table called flow session that you will be looking for, and we inventory runs from the past two days. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0565288e-26d4-4906-afe8-0b603212a5fd)

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Yes you'll want to keep the V4's going. The V3s will be removed in the next release. 
We're so happy to help you here with the starter kit so please feel free to raise questions anytime!

**Comment by inquisitive-identity** [comment]
Thank you very much for the help, Jenefer! 
Also, you all have done an absolutely incredible job with this starter kit! 
Thank you very much for the kind and fast support
Have a lovely day :)

**Comment by Jenefer-Monroe** [comment]
Awww thank you so much. Kind words like these really do make my day! 
I'll go ahead and close then but feel free to return with new issues in the future.
