### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to email to all makers for all environments at once

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#7749]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Team,

I know how to email makers for individual environments but I have close to 200 environments and growing.  How can I email all makers for all environments at once?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What method are you using to get inventory and telemetry?

None

AB#2408

**Comment by Jenefer-Monroe** [comment]
We dont do this in the kit anywhere, but all your makers are in the Maker table, so you could pull in and concatenate from that table: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/47ce8d06-375d-4166-b284-f6f5c488bc06)

Or if you set up the kit with the maker group being email enabled then you could just use that alias. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2820c3d3-4082-487e-947e-c3e73de162c3)

Hope that helps

**Comment by RyanCloud8888** [comment]
Thank you, Jenefer.  I will explore that option.
