### ISSUE TITLE
[CoE Starter Kit - BUG]: Error on import

### ISSUE THREAD

**Issue by etrentman** [microsoft/coe-starter-kit#775]
I am installing the CoE Starter kit, and receiving an error while importing the solution. I have followed the guide on https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components and when I start to import I get an error about:
"Connector import: FAILURE: The API call failed with http status code 'InternalServerError' and response content '{"error":{"code":"InternalServerError","message":"Encountered internal server error. The tracking Id is '8a7f3601-a3b7-4b59-981b-8dbc60deb374'."}}'" 

Inside the error log it also says that two of the fields have errors with them as well.
Field - admin_Connector.admin_usedbyappsnumber - 0x80060439 - The formula is empty.
Field - admin_Maker.admin_numberofmodeldrivenapps - 0x80060439 - The formula is empty.

I have tried older versions, deleting and remaking the production instance, and trying both modern UX and the legacy UX. All of these have had no success.

Attached is the import error log:
[Center of Excellence - Core Components_import.zip](https://github.com/microsoft/coe-starter-kit/files/6779509/Center.of.Excellence.-.Core.Components_import.zip)

I saw that someone else had opened a ticket here with a very similar issue, and was directed to open a Microsoft support ticket. I have already reached out to support and they directed me to create a ticket here. Support told me to check my licenses, and they are all correct with an Office 365 E3 and Power Automate per user plan license.

**Comment by Dlutchy** [comment]
I also have the same problem.

**Comment by JeneferM-MSFT** [comment]
Can you please share what version you attempted to install?

**Comment by etrentman** [comment]
Version 2.1.70

**Comment by JeneferM-MSFT** [comment]
the new version is 2.2.20210707.3 (we changed the way we do versioing and it appends a date and some other things)

**Comment by JeneferM-MSFT** [comment]
are you upgrading or clean installing? I was able to install this version

**Comment by etrentman** [comment]
I have been doing a clean install every time. Where can I find this new version? When I pull from the Microsoft doc attached or from your github link from June (https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-June2021) I get the "CenterofExcellenceCoreComponents_2_1_70_managed" file and nothing with the new version number. 

One thing I am unsure of, when importing, am I supposed to fill out all of the environment variables able I set up all of my connections? When I attempted to import I would either fill out some or none, but still get the same error. I ask because it says that you can change the variables later but it doesn't say they are required to import.

**Comment by Dlutchy** [comment]
I just tried to import CenterofExcellenceCoreComponents_2.2.20210707.3_managed.zip and it failed with the same error. 
This was a new environment with no previous COE installed.

Please see attached Log.
[Center of Excellence - Core Components_import (1).zip](https://github.com/microsoft/coe-starter-kit/files/6787812/Center.of.Excellence.-.Core.Components_import.1.zip)

**Comment by Dlutchy** [comment]
I found out the problem was that I did not have a Premium Power Apps License. Once I signed up to the Trial license it imported fine.

**Comment by etrentman** [comment]
> I found out the problem was that I did not have a Premium Power Apps License. Once I signed up to the Trial license it imported fine.

What was the trial license named you applied to the user?

**Comment by manuelap-msft** [comment]
It sounds like you may be missing some pre-requisites. Please see https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites. And also limitations on trial licenses: https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#trial-licenses

**Comment by Dlutchy** [comment]
> > I found out the problem was that I did not have a Premium Power Apps License. Once I signed up to the Trial license it imported fine.
> 
> What was the trial license named you applied to the user?

Power Apps Per User Plan trial
