### ISSUE TITLE
[CoE Starter Kit - BUG] In a COE Test Envionment after usinge the Wizard & configuring al Flows (With DataExport): Pages Data is not right

### ISSUE THREAD

**Issue by BroxCJ** [microsoft/coe-starter-kit#7750]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi, 
Recently, we are trying to use another COE environment to check if we can improve the performance (that's why we decided to use the DataExport feature instead of FLows) to get all the data. We have followed the steps with the Wizard Update App, and except a few bugs in other flows -not related to Pages/Portals- it shuld work.

Point is that whereas we have 136 Pages detected (although not deleted, only  around 20, but that's another story.....), in the Test COE we have only 105, also we noticed that Created Date does not goes more than July 22, in PROD COE, we have 136). Moreover, we detected that the Sync Template v3 (Portals) is returning Error because the field admin_lastmofiedon is not returned in the last step of the flow. Could that be the cause why we are missing Pages & information of them in the COE?. Thanks

### Expected Behavior

Have the same number of pages in bothe COE:

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin Sync Template V3 (Portals)

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1st) Configure Environment
2nd) Install COE Core version 4.23
3rd) Install all the dependencies (Feb 24 COE Toolkit)
4th) Follow the Setup & Upgrade Wizard (2 flows have an issue, not related to this).
5th) Instal DataFlow on PBI
6th)Check results

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/62092099/23a90588-7195-4d3f-9790-20000e51d5ac)
![image](https://github.com/microsoft/coe-starter-kit/assets/62092099/deae92c1-1e83-4e75-90a4-377b7e791b9a)
![image](https://github.com/microsoft/coe-starter-kit/assets/62092099/4965720c-ef38-4f11-b480-72eb16f5d580)
![image](https://github.com/microsoft/coe-starter-kit/assets/62092099/7bd82f1e-3bf3-417f-a622-9b2680e79255)

AB#2409

**Comment by Jenefer-Monroe** [comment]
The portals inventory is the same regardless of sync flow v data export methodology. 
It just triggers off the envt being updated each day. So the issues are not related to Data Export at all. 

The V3 versions of the flow are deprecated as of the March release as the connector it uses to gather the inventory is being deprecated by the product team. We took the opportunity to refactor and the V4's (along with using the Modern connector) are also more performant and so dont miss "old" objects as much. 

Please turn off the V3 version and turn on the V4 for this flow
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eea265f1-faff-47f7-986f-7b1d80fc1399)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
