### ISSUE TITLE
[CoE Starter Kit - BUG] Power Bi reports failing

### ISSUE THREAD

**Issue by JordanMcNamee** [microsoft/coe-starter-kit#7751]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We've had a few issues this week with the platform, but our CoE reports have now started to fail to refresh as well. The error message is that 'the credentials provided for the cds source are invalid'. We've tried re-adding the credentials and forcing a refresh but still the same error. Any ideas?

### Expected Behavior

Reports would refresh

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.5

### What app or flow are you having the issue with?

Power Bi Reports

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/161586296/7d001828-ef58-4644-ae76-e743b08ff741)

AB#2410

**Comment by Jenefer-Monroe** [comment]
I'm afraid I don't know how to resolve this issue. Its definitely a product issue with credentials expiring or something. But if you've already tried to repair them I don't know what else to offer. 
We can keep open if the community has ideas, otherwise you may need to contact product support.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
