### ISSUE TITLE
[CoE Starter Kit - QUESTION] What is the impact if the admin/Maker/User persona group is deleted?

### ISSUE THREAD

**Issue by CodeNinjapan** [microsoft/coe-starter-kit#7754]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

This question was created using the translation function, so the text may be incorrect.

When deploying the CoE Starter Kit, the recognition is to set up three Microsoft 365 groups (Admin/Maker/User)

If these groups were removed, what would be the possible impact on functionality in the CoE Starter Kit?
(What will no longer be possible, etc.)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2413

**Comment by Jenefer-Monroe** [comment]
You can detect many dependencies by looking at the env var itself as shown here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8a85f9c9-9d4d-442c-a23d-4ec6a1e85445)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/878ee9a2-725b-49ae-9ad7-7762381a5a95)

In short though:
- the admin one is quite mandatory. Many flows in the kit rely on it for (ex) sending notifications to the admins about things
- the maker one is needed if you've used it for giving permissions to users to tables / apps, and for the Admin | Add Maker to Group flow
- the user one is only needed if you've used it for giving permissions to users, we do not use it for any flows today. 

Hope that helps

**Comment by CodeNinjapan** [comment]
Thank you for your response.

We are concerned that these groups will not be subject to automatic deletion if, for example, we have an operation (configuration) in our tenants that automatically deletes Microsoft 365 groups that have not been used for a year.

Is it correct to assume that these groups (especially the admin group) are always used (active) as long as the CoE starter kit is used?

**Comment by Jenefer-Monroe** [comment]
The admin group is needed to stay around for the lifetime of the kit yes. 
I'm not familiar with this configuration for group cleanup of how it detects inactive groups. The admin group will likely be getting mails at least monthly if you are using the kit so it should not be considered inactive.

**Comment by CodeNinjapan** [comment]
Thank you for your response!
I would like to close this case if the following understanding is correct.

・As long as I continue to use the CoE Starter Kit, I cannot delete the Admin Group.
・At least the admin group will receive monthly emails so they can remain active.

**Comment by CodeNinjapan** [comment]
Thank you for your response.
We will consider the information you provided!

By the way, a little off topic, but is this persona group in this case different from the security group when creating the environment?

For example, is it possible to have the same security group and admin persona group when creating the environment?

**Comment by Jenefer-Monroe** [comment]
We recommend not using a security group for the envt as this prevents some automatic features from occurring.
Please see [Create your environments](https://learn.microsoft.com/power-platform/guidance/coe/setup#create-your-environments)

**Comment by CodeNinjapan** [comment]
Thank you for your response.
There is no problem to have this one closed for now.
