### ISSUE TITLE
Are there known issues custom connector used for Audit Logs ? 

### ISSUE THREAD

**Issue by goroy1** [microsoft/coe-starter-kit#7755]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We applied a tenant level policy where all the connectors were allowed (business) and custom connectors were set to Ignored later to business, however a flow using the Audit log custom connector was flagged for violating DLP, when we reached out the MS support the engineer guided us to COE team as its a custom connector created by this team, so my question would be any known issue with the connector that would flag the flow for DLP even when nothing is blocked.  There are no other conflicting DLP polices applied to the environment, its the environment which has the COE starter kit installed
![image](https://github.com/microsoft/coe-starter-kit/assets/125452130/80f3d228-e153-4b54-85c6-cc7c063fcb8a)
![image](https://github.com/microsoft/coe-starter-kit/assets/125452130/44aefb4b-76cb-49bb-b9f0-5821a27e5842)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

New Audit Log solution 1.0.0.3

### What method are you using to get inventory and telemetry?

None

AB#2414

**Comment by Jenefer-Monroe** [comment]
Hello. They really should not have sent you to us, this is just a question about how any custom connector interacts with DLP, but I can try to help. 

If your goal is to have the DLP allow all behavior for now, which is what it sounds like, then you would need that Custom Connector pattern to be Ignore
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cc196978-be4e-4f16-871e-165137c1a5fc)

**Comment by goroy1** [comment]
Hi Jennifer,

That's what we did actually, the DLP was set to Ignore for custom connector and it still flagged, so makes me think its more of a platform issue and not related to the connect at all.

Thank you anyway, will let the engineer know.

Gowri

**Comment by pre2024** [comment]
Hi Jennifer , Thank you for your inputs. The issue here stated is related to CoE Starter kit custom connector and is not a custom connector that we may develop in power automate platform. If this would be related to more of a pattern to be ignored , please share us a workaround on how this can be resolved . Is there a way to understand the pattern which will work for the environment using this CoE Starter kit custom connector. Can we use the same CoE Starter kit custom connector in an environment which is not a CoE Environment. Please share your thoughts here . Thank you

**Comment by Jenefer-Monroe** [comment]
Hello we have deprecated the custom connector path for collecting audit logs.  But like any custom connector the DLP needs to be adjusted to work for the custom connector. If the ignore feature of the DLP is not working, that is a product issue not an issue with the kit. Wouldnt you agree?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
