### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is the setup of the "Template Catalog" completed in the Setup Wizard?

### ISSUE THREAD

**Issue by CodeNinjapan** [microsoft/coe-starter-kit#7756]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

This question was created using the translate function, so the text may be incorrect.

I tried to set up a template catalog using the following site as a reference, but can I really consider the setup complete just by following the setup wizard?

[https://learn.microsoft.com/ja-jp/power-platform/guidance/coe/setup-nurture-components#set-up-template-catalog](https://learn.microsoft.com/ja-jp/power-platform/guidance/coe/setup-nurture-components#set-up-template-catalog)

What other setup is required besides the setup wizard to use the template catalog?

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.11

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2415

**Comment by Jenefer-Monroe** [comment]
You do need to populate it with data. Please see [Add your own templates to the Template Catalog](https://learn.microsoft.com/power-platform/guidance/coe/setup-nurture-components#add-your-own-templates-to-the-template-catalog)

**Comment by CodeNinjapan** [comment]
Thank you for your response.

When I perform the procedure you suggested, the following message appears at the top of the screen and I am unable to add data. Is this the wrong procedure?

"You cannot directly edit objects in a Managed Solution.
If the managed properties of the solution object are set to allow customization,
You can edit these from another solution that is unmanaged."

![image](https://github.com/microsoft/coe-starter-kit/assets/160689265/79793a9e-1cea-472c-aa15-e99a2f0e7f06)

**Comment by CodeNinjapan** [comment]
I understand the content.
Thank you for your response!

**Comment by Jenefer-Monroe** [comment]
Wonderful! I'll go ahead and close then but please feel free to return with new issues as they arise!
