### ISSUE TITLE
How can I (as an Admin) approve the deletion of an app/flow on behalf of someone?

### ISSUE THREAD

**Issue by sasrsc** [microsoft/coe-starter-kit#7757]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In App and Flow Inactivity Notifications Clean Up View I can Excuse and App or Delete the Approval, but I can't approve the deletion of something.
In the CleanUp Old Objects App if they are one of my employees, I can reject the deletion or I can remind the user but I can't approve the deletion of something.
I'm guessing your argument is that this is "final" and therefore the user should do it themselves. 
Or am I missing something. 
I have situations where I have lazy or confused employees and it would be easier if I can just delete them.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Feb 24

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2416

**Comment by Jenefer-Monroe** [comment]
Hello We do not have any UX for this but I've put that as an ask for the upcoming feature to redo this area. 

In the meantime what you can do is manually update in the **_Archive Approvals_** table manually.
Search for the Envt by its GUID and then the app. 
You'll need to enter the Approval Response field with the following string: **_Approve_** or **_Reject_**

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2085a556-ff6a-4173-8547-f0540b17a37e)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
