### ISSUE TITLE
[CoE Starter Kit - BUG] After upgrading to latest version, 4.23, no data is shown

### ISSUE THREAD

**Issue by StigMortenNegard** [microsoft/coe-starter-kit#7758]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This might not be a bug, but a issue with the my environment. Give me a message if I shall move it to the questions thread.

After I update from 4.14 to 4.23 I find my CoE empty. No flows, environments or apps. I see it best in the power platform admin view, but in the Set App Permissions and Set Flow Permissions it is the same.

There where a lot of flows which did not start by it self, but starts when I start them manually. Sync Flow Errors do not report anything, but that might be the same reason that the complete problem fases. I use the same account as before, unless some values have been reset during the upgrade.

Any thoughts? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

CoE in total

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2417

**Comment by Jenefer-Monroe** [comment]
Did you use the Setup Wizard? Its highly recommended that you use the **CoE Setup and Upgrade Wizard** to install or upgrade the kit. It allows you to not worry about the order of turning flows on / new environment variables etc. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d7901e1e-4c2a-442a-ba27-dfbeb62332bb)

**Comment by StigMortenNegard** [comment]
I think I followed the steps in the guide - https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup.

But I first run the upgrade with my admin account. Did a "reupgrade" logged on as the prefered systemaccount. It seemed to be some ownership that followed the logged on user.

**Comment by StigMortenNegard** [comment]
Looking into it now, and under the upgrade history the last operation is Import with suksess as status

**Comment by StigMortenNegard** [comment]
and by the way. There were created a new environment after the upgrade was done, and that shows in the dashboard page, and is shown in the environment list (from the environments menu on the left).

**Comment by Jenefer-Monroe** [comment]
You need to perform the upgrade as the identity that will run the flow. And then please boot the setup wizard and walk through the steps. It will ensure you have the correct flows turned on.

**Comment by Jenefer-Monroe** [comment]
If its easy for you to start over that may be easiest. 
But the kit is a great way to learn how to debug the product which, as you say, is not obvious how to debug :)

Another option is to see if you can fix up via the connection references. 
Log in as the user you want to be owning / running the kit, browse to Solutions > Default Solution > Connection References
Click each connection reference and validate that it is resolved to you (the logged in user). If its not it will be some strange string. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ac9ee337-9d99-4e83-94ea-603f19f6dc54)

**Comment by StigMortenNegard** [comment]
Thanks! Most of them where correct, but at the bottom the "datavers" had no connection. I selected the correct one (I only have one). After doing this change I clicked "publish all customizations". I'll wait a bit now, but is it correct that all of them should have status "off"? Both in the default solution and the managed one all of them is off.

**Comment by StigMortenNegard** [comment]
And one more thing. In the environment table in the dataverse base I can see all the environments. Strange things :-)

**Comment by Jenefer-Monroe** [comment]
That on/off there is meaningless unfortunately. Connections dont have a state like that but they werent hidden. Confusion results :)

**Comment by Jenefer-Monroe** [comment]
Sorry if the old envts are showing there, where are they missing? Perhaps I got caught in minutia here.

**Comment by StigMortenNegard** [comment]
this is what I see in the admin view of environments:
![image](https://github.com/microsoft/coe-starter-kit/assets/161565237/0124020b-5bb2-4fad-8fd6-cbc583f36899)

This is some rows from the environments table in dataverse:
![image](https://github.com/microsoft/coe-starter-kit/assets/161565237/ff0db431-db96-4f48-96f1-72aec69acd68)

What I see is that new environments created the last weeks has value for security group name, even if it is "not assigned". Environments from earlier do have empty for this value. The value for how many apps and flows are 0 for all the environments, beside the new one, here the counter is correct.

**Comment by StigMortenNegard** [comment]
I think that things could look better if I could have CoE to do a full scan of the environment, not the way flows are created now, which is when there is a change in the datavers's tables.

**Comment by Jenefer-Monroe** [comment]
Environments do get updated every day. 

Can you please log into the product admin pages as the user running the flow? How many environments do you see there? https://admin.powerplatform.microsoft.com/

**Comment by StigMortenNegard** [comment]
Hi, here I see everyone and everything looks normal. In the power platform admin view I only see the environments created after I updated to the latest version of CoE.

I'm gratefull for the help I'm getting and understand that it's hard to see what could be the error. I guess it's just a parameter or a setting that makes everything starts working :-) . Do not hasitate to tell me to remove and install CoE again, I totally understand.

**Comment by Jenefer-Monroe** [comment]
Lets check one more thing before you reinstall. Lest you end up in the same spot there. 
Please go to this flow: **_Admin | Sync Template v4 (Driver)_**
And see if all the envts are returned in this call
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ee54e196-59b6-40d4-94a5-d2f0a96876a9)

**Comment by StigMortenNegard** [comment]
Hi! I can find them all in that list. It ran for about 14hours since. What I see is that I'm the owner of the flow, not the service account I expected. It is not even a co-owner. I think this could be a result of my first update where I ran it with my admin account, not the service account. I'm changing the owner to the serviceaccount on this, and all the ...V4 flows, rerun the flows and see if this  have any impact.

**Comment by StigMortenNegard** [comment]
Tanks!

**Comment by StigMortenNegard** [comment]
Ups, all the text was not included. In last posting

Thank you for helping me out. Since I did "everything" wrong in the first step, not using the correct account, I'll will try the upgrade again and if this do not work, I'll perform a complete new-installation.
