### ISSUE TITLE
[CoE Starter Kit - BUG] The environment variable admin_HostDomains is too short

### ISSUE THREAD

**Issue by jay-dee-20** [microsoft/coe-starter-kit#7759]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I need to put almost 800 domains in here, to make the cross-tenant reporting more accurate.  But they don't all fit.

Can this field be longer?

My list is 11,000 characters long.

### Expected Behavior

If I can put a longer list in here, that would be great.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Command Centre

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open up the Command Centre environment variables
2. Paste the domains in - a string of almost 11,000 characters.

### Anything else?

No

AB#2418

**Comment by Jenefer-Monroe** [comment]
Unfortunately I dont think we can do anything to fix that. Its an env var so we do not control the size, but even if we could I think the product has a limit of ~4k characters in those fields. 
You may need to spin up your own solution here to hte problem of identifying cross tenant given your extreme case. 
Sorry we cant be of more help.

**Comment by jay-dee-20** [comment]
OK - thanks for the update :)

**Comment by Jenefer-Monroe** [comment]
You're welcome. I'll go ahead and close then but please do return with other questions in the future should they arise.
