### ISSUE TITLE
[CoE Starter Kit - QUESTION] More recent flow usage info from Data Export

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#7760]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I would like to provide a "yesterday" view of failed flows to the flow makers. 
In the Power BI  BYODL Dashboard report, in the 'flow usage' table, the latest flows are is 3 to 4 days behind. i.e. on 1st March, the latest records is from 26 Feb.

My dataflows are refreshing daily

is there a way to get the flow usage from "yesterday" ? 

I am using Feb 2024 core components

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Data Export

AB#2419

**Comment by Jenefer-Monroe** [comment]
Hello. We are limited here by how quickly the data comes from the products Data Export feature so unfortunately we are not able to get more recent information than that. You can provide this feedback to the product team though via the https://powerusers.microsoft.com/ community.

**Comment by jimpreston29** [comment]
Thanks for the update

**Comment by Jenefer-Monroe** [comment]
You are so welcome. I'll go ahead and close then as there is no action item for the starter kit team today. But please do return with other issues as they arise in the future.
