### ISSUE TITLE
Failed to upgrade solution. Solution dependencies exist, cannot uninstall. DependencyCount : 5 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API

### ISSUE THREAD

**Issue by LouieAloy511U5** [microsoft/coe-starter-kit#7761]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to update Solutuion:
error message: 
Failed to upgrade solution. Solution dependencies exist, cannot uninstall. DependencyCount : 5 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f691c36f6fa56d15c_faecd, Id: 12d7e988-a7b8-4ed6-ae0b-0896adb06d31, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_Office365ManagementAPI2, Id: 8515fd7c-3dcf-ee11-9078-6045bdcf57e5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: new_Office365ManagementAPI3, Id: 8e664b9b-3dcf-ee11-9078-6045bdcf57e5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f691c36f6fa56d15c_374b1, Id: 619d825f-fed3-49cb-a2fc-6bf624dcf1ad, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published

### Expected Behavior

Success message without errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

COE - Solution import

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Importing the solution
Unable to add existing connection as its a managed solution , in the default solution section.

### Anything else?

.N/A

AB#2420

**Comment by Jenefer-Monroe** [comment]
Hello, this is a known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018
We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors. 
If you have tried those steps and still see this error, note that some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use  powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest)  these remaining connections to the old connector.

**Comment by Nanthini2414** [comment]
Hi,

I have followed the steps given in that article and tried to delete the 'CenterofExcellenceCoreComponents_Upgrade' solution but unable to delete to do the below dependencies.

I am getting the error while deleting the solution 

**Failed deleting solution Center of Excellence - Core Components. Solution dependencies exist, cannot uninstall.**
 
Please suggest me the solution.

**Comment by Jenefer-Monroe** [comment]
Unfortunately that just means there are connections remaining, likely just not visible from the UX. 

You can use powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) these remaining connections to the old connector.

**Comment by Nanthini2414** [comment]
Morning Jenefer,

The Dependencies are not only connector

Most of the dependencies are tables, sitemaps and web resources which we can't delete because it's referring the flows and apps

Please let me know your availability to have a call to discuss further.

![image](https://github.com/microsoft/coe-starter-kit/assets/161862249/ad33a87e-385a-44bf-bc8b-791c4bf1b7a5)

**Comment by Nanthini2414** [comment]
Hi,

I've tried to delete the 'CenterofExcellenceCoreComponents_Upgrade' solution and find the screenshot below

Solutions List in the COE Environment:
![image](https://github.com/microsoft/coe-starter-kit/assets/161862249/f4a3e19a-14fc-47db-b931-53e8b7331028)

**Comment by Jenefer-Monroe** [comment]
Oh i see. Unfortunately you are trying to upgrade from a build released in July 2022. 
I'm afraid we cannot assist with upgrade problems of this age / complexity as there are just too many specifics and unknowns of how you got into this state. We recommend upgrading at least every 3 months, see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/after-setup#installing-upgrades). That is how far back we test as well.

If all you are using us for is inventory, with or without audit logs, then we recommend you start from a clean environment. 
Here is a write up to help you get started with migrating the audit log data [issue 1507](https://github.com/microsoft/coe-starter-kit/issues/1507)

If you are using us for more than that, you may need to hire a partner to manually clean up the state of the environment. You can find some via you can find them via [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1)

Some people have cleaned themselves from this state by manually cleaning out the references listed. In your case, this would mean, for example, going to the (Check Deleted) cleanup flow and deleting the connection reference listed. 

Sorry we cannot be of more assistance here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
