### ISSUE TITLE
Proper ALM for CoE since copying dataflows as part of Power Platform environment copy operation is not supported

### ISSUE THREAD

**Issue by KristenStanley** [microsoft/coe-starter-kit#7762]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

A while back, I reported an issue we experienced when trying to update our CoE toolkit ([7493](https://github.com/microsoft/coe-starter-kit/issues/7493#issuecomment-1899097794)).  After many failed attempts and no other options to consider, I entered a support ticket with Microsoft thinking maybe something is just technically wrong.  The Microsoft support person who helped me, was quick to reference a documented [limitation ](https://learn.microsoft.com/en-us/power-query/dataflows/create-use#known-limitations) with dataflows: "Copying dataflows as part of a [Power Platform environments copy](https://learn.microsoft.com/en-us/power-platform/admin/copy-environment) operation isn't supported."  I am wondering if this limitation is the source of my problem.

Our ALM process for updating our CoE is to create a sandbox environment, copy our production CoE environment into the sandbox and then perform the update to the sandbox copy.  This is standard ALM practice.  Applying updates to the production environments directly without testing first poses great risks.  Since the Center of Excellence - Core Components solution contains 9 dataflows, what is your recommendation for implementing proper ALM for the CoE since dataflows cannot be copied from one environment to another?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

dataflows

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2421

**Comment by KristenStanley** [comment]
OK, I see.  Yes, we can alter our process a bit to just recreate the production environment in a sandbox.  Install the creator kit solution and the coe core components solution that exists in prod.  Then run the update on the sandbox.  We will try this process instead of creating a copy of the production environment into a sandbox.  Thanks for the quick response.

**Comment by Jenefer-Monroe** [comment]
You bet we're here to help! Please do let us know if you have other questions.

**Comment by KristenStanley** [comment]
Thank you!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
