### ISSUE TITLE
[CoE Starter Kit - BUG] Dataflow errors in the Latest Release (February)

### ISSUE THREAD

**Issue by abhijkumar-msft** [microsoft/coe-starter-kit#7763]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team,

We're seeing the following data flow errors occur after having the client upgrade to the latest release of the CoE Starter Kit:

**Flows Data Flow:**
![image](https://github.com/microsoft/coe-starter-kit/assets/146243200/25a8266f-8167-46ce-a8e2-1f820253e859)

**Makers Data Flow:**
![image](https://github.com/microsoft/coe-starter-kit/assets/146243200/e1f23079-a510-4f02-a0a8-78e248d9f05f)

**Latest Errors:**
![image](https://github.com/microsoft/coe-starter-kit/assets/146243200/ea74f46f-7750-4cd7-923e-04a4ec0e3df5)

**UPDATES FROM THE CLIENT:**
1. _The "next refresh" is only set for makers._ Yes; verified with the client that the "next refresh" is set only for Makers.
2. _You applied the fix described here. It will be live in the March release: https://github.com/microsoft/coe-starter-kit/issues/7562._ Verified that this fix does NOT fix the issues currently driving the errors.
3. _What information is given about the failures for flow._ The detailed errors are provided in the initial snapshots in the ticket description (Flows Data Flow and Makers Data Flow).

Let me know if there's anything in addition you're looing for,  @jenef.

### Expected Behavior

The data flows should run as expected.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February Release

### What app or flow are you having the issue with?

Sync Data Flows

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Install the latest version of the CoE Starter Kit and allow it to run during it's pre-scheduled times.

AB#2422

**Comment by Jenefer-Monroe** [comment]
Hello there were some new changes to the data sources and the data export file we had to adapt to for the March release including a new bad user type. We fixed these up via https://github.com/microsoft/coe-starter-kit/issues/7697 so please do try again with the March release which will ship next week and let me know.

**Comment by abhijkumar-msft** [comment]
Will do!
