### ISSUE TITLE
[CoE Starter Kit - Feature]: CoE Starter Kit Documentation Role Clarification Required

### ISSUE THREAD

**Issue by jjfallete** [microsoft/coe-starter-kit#7764]
### Is your feature request related to a problem? Please describe.

From: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with

The documentation currently states that any of these 3 roles can be used for the CoE:

- Microsoft Power Platform service admin, global tenant admin, or Dynamics 365 service admin.

The documentation fails to note an important limitation to the later. The Dynamics 365 Administrator role does not provide access to Teams Dataverse environments. Access with this role only works if the account is manually added as an Owner or a Member of each Team. This is documented elsewhere, outside of the CoE documentation, in [About the Microsoft Dataverse for Teams environment - Role assignments](https://learn.microsoft.com/en-us/power-platform/admin/about-teams-environment#role-assignments)

### Describe the solution you'd like

This should be clarified in the documentation, perhaps via an "Important" alert box or sub-bullet.

### Describe alternatives you've considered

N/A

### Additional context?

I've opened an Issue for the documentation in the MicrosoftDocs GitHub as well. I'm opening this as a separate Issue here to help others experiencing this and to raise visibility of it to the CoE team. Thank you.

Ref: https://github.com/MicrosoftDocs/power-platform-pr/issues/7938

AB#2423

**Comment by Jenefer-Monroe** [comment]
Thank you for posting! I was unaware of this limitation. Will update with our documentation.

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b2fc9ed2-044b-48bf-b338-efea9898c66e)
