### ISSUE TITLE
[ALM Accelerator - QUESTION] How are the environment variable values updated?

### ISSUE THREAD

**Issue by ryanmichaeljames** [microsoft/coe-starter-kit#7765]
### What is your question?

Firstly, please confirm my assumptions...

During a deployment the `deploymentSettings.json` file's environment variable value's tokens are replaced during the **Replace Tokens: deploymentSettings.json** step.

![image](https://github.com/microsoft/coe-starter-kit/assets/16380903/07d4f1a3-9290-49e9-ba5a-2e1489452a1c)

These tokens are replaced by the variables that are added to deployment pipeline for the solution.

![image](https://github.com/microsoft/coe-starter-kit/assets/16380903/3151b032-ef2c-4f5c-ae69-14b14a15c2ad)

Finally my question... 

How are the variables in the deployment pipeline maintained? Is it the  canvas app updating it directly when the deployment settings are saved? Or, is it updated during the `export-solution-to-git` pipeline run?

How is the correct pipeline found during the update of the variables? Is it the naming convention of the pipeline, i.e. `deploy-<environemtn_name>-<solution_name>` or something else?

A more technical answer would be greatly appreciated as this will help me better understand how the ALM Accelerator works as a whole and how I can better support our development teams. 😊

Thanks!

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20231004.1

AB#2424

**Comment by mikefactorial** [comment]
@ryanmichaeljames the export-solution-to-git pipeline is responsible for maintaining the deployment pipeline variables based on the deployment settings created in the app and passed as a parameter to that pipeline (this happens in the Update Deployment Settings step in the pipeline). By default the naming convention you mentioned is how the pipeline is identified. The Update Deployment Settings step is also responsible for creating the deployment pipelines on the initial export of the solution.

**Comment by ryanmichaeljames** [comment]
Thanks @mikefactorial :)
