### ISSUE TITLE
No data in App Usage page of CoE Power BI Dashboard - Follow up issue 7581(https://github.com/microsoft/coe-starter-kit/issues/7581)

### ISSUE THREAD

**Issue by diltont** [microsoft/coe-starter-kit#7766]
This is the follow up of the issue I raised.[Link](https://github.com/microsoft/coe-starter-kit/issues/7581).

After the conversation, I finished setting up collecting the audit logs using an HTTP action using the CoE start up and Upgrade wizard.
The following steps went good
1) After a new app registration , Audit Logs client secret and Audit  Logs Client ID were updated.
2) Admin | Audit Logs | Office 365 Management API Subscription was turned on and got 200 response.
3)Admin | Audit Logs | Sync Audit Logs (V2) is also turned on and is also running successfully every 1 hour.

But still I see blank data in CoE Power Bi dashboard in app usage page.
The App launced between part in Power BI report is frozen as seen belown.
![image](https://github.com/microsoft/coe-starter-kit/assets/47943660/4ba05cf7-00ef-4787-9e16-dd57fe4ae769)

Did I miss something? 
What shall I do next to fix the issue?
Thanks in advance
Kind regards

AB#2431

**Comment by RahulBojji** [comment]
@diltont 
Can you please confirm below things
1. Are you are seeing data in the power Platform Admin View or not??
2. i) Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/a200a2e3-660e-4f69-82aa-9b54166a4129)

ii) Validate that the azure key vault permissions are correct. User needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update.
![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/6088f466-30af-4d9d-8c5e-cb1e9045b29d)

**Comment by diltont** [comment]
Thnaks for the quick reply
1) Yes we are seeing the data in Power Platform admin view
![image](https://github.com/microsoft/coe-starter-kit/assets/47943660/97cf6496-cc6b-4189-8ea6-5c78da0db5d7)
2) The perimission given to the app registration is also right
![image](https://github.com/microsoft/coe-starter-kit/assets/47943660/42f17c03-45d9-4e10-8260-8f1f11504aa3)
3)We didnt use Azure key vault. Instead we used plain text option

I think to add . I checked the CoE ToolKit PBI report  and it shows the last data updated on 15/01/ 2024.

**Comment by RahulBojji** [comment]
From the screenshot you have attached above, looks like you are still on older version. Can you please confirm currently on which version you are on. 
Can you please share screenshot of the list of solutions you have installed in your environment just like below. Please make sure you are expanding the highlighted columns.

![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/d5e47c18-ad3b-46e5-9406-ce456ad78f7f)

**Comment by diltont** [comment]
Hello
Here is the screenshot of all solutions installed in CoE ToolKit environement
![image](https://github.com/microsoft/coe-starter-kit/assets/47943660/e2d38caa-af73-4b63-8e17-6f92e0b7ca2b)

**Comment by RahulBojji** [comment]
Looks like you have not updated your PBI report. The latest report looks like this

<img width="600" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/b761c2e6-0e15-4e7a-b436-2fbaeb1c360c">

Please see [this](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi) for setting up the PBI reports. Check the version you are on and open that PBI report

**Comment by diltont** [comment]
Do I have to do all the steps explained in the setting up of PBI reports?
We already have a  PBI report. Does dataflows refreshing or something else can also solve the problem?

**Comment by RahulBojji** [comment]
In recent times, we have fixed some critical bugs on reports so we suggest to update the report as well.

**Comment by diltont** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/47943660/136b4b53-229e-4141-a855-a826fafbc419)

**Comment by Jenefer-Monroe** [comment]
Sorry are you using the Data Export methodology for inventory?

**Comment by diltont** [comment]
I have set up the audit logs thorugh the wizard as suggested by you. I have turned on the flows as suggested in the audit log set up.
Hence I think the inventory is set up using cloud flows not Data export method.
Is there a way to check this to be sure?
I have opened Governace dashabord and it didnt show any error

**Comment by diltont** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/47943660/3d339810-c73d-4604-9ed6-1299093af98c)
These are some warnings shown before error

**Comment by Jenefer-Monroe** [comment]
ok yes I thought you were on cloud flows, there are no dataflows in that architecture that is why I asked. 
The admin_applogicalname is a new field to the Feb release which is build 4.23. You need to use the PBIT files associated with the build you have installed. So in this case you have the Feb PBIT but then Jan core components. 

I suggest you ugprade later this week or next week to March release (4.24) and then use the PBIT files that come with it.

**Comment by diltont** [comment]
I treid the PBI report from version 4.22 and it works
"I suggest you ugprade later this week or next week to March release (4.24) and then use the PBIT files that come with it." 
Does this mean both CoE ToolKit and PBI reports or only PBI report?

**Comment by RahulBojji** [comment]
Both. If you are updating COE tool kit it's better to update PBI reports as well because we might have introduced some new changes or might have some bugs.

**Comment by diltont** [comment]
We updated  CoE ToolKit last month and dont want to do it every month.
Does the PBI report of version 4.22 have any issues ? Otherwise I will move with PBI report 4.22  versiona dnupdated PBI nad COE ToolKit together in our next CoE ToolKit update

**Comment by Jenefer-Monroe** [comment]
Hello. Yes you just have to match the PBIT file with the correct Core version. If you are on Core 4.22 then this means you need to use the January version of the PBI. To my knowledge that version is in good shape. 

I've attached it here for you in case you dont still have it from the download.
[Production_CoEDashboard_January2024.zip](https://github.com/microsoft/coe-starter-kit/files/14499067/Production_CoEDashboard_January2024.zip)
