### ISSUE TITLE
[CoE Starter Kit - BUG] Quarantine Flow getting triggered from inventory

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#7770]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

the flow "Admin | Set app quarantine status" gets triggered each time when the flow "CoE BYODL - When App dataflow refresh is complete" runs.
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/0a9d76a4-44af-4f5c-a974-8918e93018e4)
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/8531eea9-f50d-4688-a5f9-32d7255a50ac)

### Expected Behavior

That the flow "Admin | Set app quarantine status" only gets triggered if the colum "admin_quarantineapp" gets chaneged not updated

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.15

### What app or flow are you having the issue with?

Admin | Set app quarantine status

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

"CoE BYODL - When App dataflow refresh is complete" has to updated the info about some Canvas and the quarantine process is on

AB#2462

**Comment by Jenefer-Monroe** [comment]
Thank you for posting, will investigate for April release.
