### ISSUE TITLE
[CoE Starter Kit - BUG] Flow "Admin | Sync Template v3 (Connectors)" failed. Error throw in action "Get_Connectors"

### ISSUE THREAD

**Issue by HaoqingCai** [microsoft/coe-starter-kit#7771]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

CoE Admin flow "Admin | Sync Template v3 (Connectors)" is failed when running setup flow during the CoE upgrade. An error thrown in action "Get_Connectors". Tested this action in a separated flow, it failed again. After checking this flow, i found it started to fail from 1 week ago. So i don't think it's related with CoE upgrade. I've checked the raw response from the last successful run, the type of this property is inconsistent even in the same connector definition. Not sure if some recent update on this action changed the behavior. 

Error Message:
The API 'powerappsforappmakers' returned an invalid response for workflow operation 'Get_Connectors' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-Connectors' requires the property 'body/value/785/properties/connectionParameters/username/uiDefinition/constraints/required' to be of type 'String' but is of type 'Boolean'.'

Screenshot:
Error Message
![image](https://github.com/microsoft/coe-starter-kit/assets/120713349/4414ee6e-3a47-4bcd-bf80-60b1b7277ef4)

Started to fail from 1 weeks ago
![image](https://github.com/microsoft/coe-starter-kit/assets/120713349/58f0832a-7541-4d44-abe1-ddf78eccc943)

Raw response from the last successful run
![image](https://github.com/microsoft/coe-starter-kit/assets/120713349/611536ea-fd6a-4953-a7bd-e62a47c18b27)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Run Setup flow in "CoE Setup and Upgrade Wizard". 
2. Error occurred on flow "Admin | Sync Template v3 (Connectors)"

AB#2463

**Comment by RahulBojji** [comment]
@HaoqingCai this is a product issue where the customers experienced across regions
.
 Please watch in https://github.com/microsoft/coe-starter-kit/issues/7630 for the latest updates

**Comment by Jenefer-Monroe** [comment]
closing as a duplicate so we are tracking in one spot.
