### ISSUE TITLE
List of Compliance emails sent 

### ISSUE THREAD

**Issue by karbip** [microsoft/coe-starter-kit#7773]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have two queries/ concerns, hoping someone can help me out or point me in the right direction. Thank you in advance!

1. Is there a way to find out or generate a list of all compliance emails sent to makers?

One of the maker got the compliance email even though ProductionEnvironment variable was set to 'No'. I would like to know why the email was triggered and where can I who else received these emails.

2. DLP Editor V2 app launch from CoE Command Center Bookmarks page give me error: "Sorry, we didn't find that app"

Screenshot attached
![For CoE-github query](https://github.com/microsoft/coe-starter-kit/assets/131582958/509268dd-75f4-40b1-9acd-b0d81ed532d8)

  

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

February 2024

### What app or flow are you having the issue with?

Admin | Compliance detail request v3

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2471

**Comment by Jenefer-Monroe** [comment]
Hello. In the future please post a single issue per question. that makes tracking for us much easier. I'll us this for the first question, please post a separate one for the DLP as there will be some back and forth to get through it. 

### Is there a way to find out or generate a list of all compliance emails sent to makers?
You can look at the Sent Items for the user identity running the flow. Here for example I've found all the "Sync Flow Error" mails sent.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0256f766-c87a-41d0-b704-a43225cfe478)


### One of the maker got the compliance email even though ProductionEnvironment variable was set to 'No'. I would like to know why the email was triggered and where can I who else received these emails.
If you changed the value of the env var after the solution was installed and used, it may have gotten cached in the flow. This is not supposed to happen but that is likely what occurred. 
You can turn the flow off and on and to ensure the correct env var is used. And you can reach out to product support to let them know the cache occurred as this is an unfortunate product bug.

**Comment by karbip** [comment]
Thank you!
