### ISSUE TITLE
[CoE Starter Kit - QUESTION] Make the Creator as Owner through the "Set Flow Permissions" app

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#7780]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi!
We had the question about the flow and app that are connected.
To explain the problem I will give the example:
We have the flow that is called "Test123". This flow is considered to be as orphaned as it has no owner. We wanted to make this user that already has the "Creator" role as owner through the app that is called "Set Flow Permissions".
<img width="658" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/0aa84c82-90e9-444e-b619-2a80fb711e1a">
When we are clicking to the button "Make Owner", we see this error message that is also shown in the screenshot above "Changing owner failed, try to set via product UX". 
We checked the flow that is connected to this app and needed to proceed with this action of "making the user as owner" - in "HELPER - CloudFlowOperations"
And in the action "Edit Flow Owner Role as Admin" we see that it failed as well with the message 
"{
  "error": {
    "code": "PermissionDowngradeNotAllowed",
    "message": "Principal '305f....' already has greater permissions to the flow. The permission cannot be downgraded."
  }
}"
<img width="548" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/f5fabb5a-24fd-430e-932f-ee52940fe10d">
Our questions are:
1) Why cannot we make the creator as owner? As we understood the Creator is much higher than owner because of the message "Principal '305f....' already has greater permissions to the flow. The permission cannot be downgraded.", are we right? But then how can we make this one exact user to be an owner as otherwise the flow will become orphaned?
2) Is that ok that we see this button in the app in case we really cannot set up Creators as owners? I mean, if this button needs to be there, it is visible, does it mean that the error we receive means that something is wrong in our end? Or this button is always visible if it doesn't work for certain users?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Set Flow Permissions app and HELPER - CloudFlowOperations flow

### What method are you using to get inventory and telemetry?

None

AB#2477

**Comment by Jenefer-Monroe** [comment]
From looking at your screenshot. There appears to be only 1 records shown, and its not the owner already. This is not an expected state so the app behaving oddly may occur. 

This app is being replaced with something quite similar to what you see in the Power Platform Admin View. 
Can you please go there and try to update the permissions? 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6e585f37-7685-48fb-8b07-392f6a7fb1ee)

**Comment by JanetK12** [comment]
Thank you for your answer @Jenefer-Monroe!
We went to the Power Platform Admin View app to check the option you provided, but when we just clicked to the "manage permissions" button, this is what we got
<img width="231" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/b2ba0833-e3a1-4449-a8a6-c1b946309ed4">

**Comment by Jenefer-Monroe** [comment]
OK it seems like this app is in a strange state. 
Can you please go see in the product what state it is in? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d21a85bf-7848-4b5c-b1ba-20ab88684577)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f6a9a781-5669-4335-8aea-30c437415fd3)

**Comment by JanetK12** [comment]
> OK it seems like this app is in a strange state. Can you please go see in the product what state it is in? ![image](https://private-user-images.githubusercontent.com/89584709/310526068-d21a85bf-7848-4b5c-b1ba-20ab88684577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTgyOTAsIm5iZiI6MTcwOTc5Nzk5MCwicGF0aCI6Ii84OTU4NDcwOS8zMTA1MjYwNjgtZDIxYTg1YmYtNzg0OC00YjVjLWIxYmEtMjBhYjg4Njg0NTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA3NTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YWU3OGE1YWRiYWI4YmI2YTU3ZDBmN2NlNjJhYTNjZmUyZjU2ZmU2NWY3NjhlYzUwNjk0NDE3MDkzMzg3NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3IBt0LRzVHPqz1jEhBOUjTGZM_wwwTD0yD2MpdMWvvs) ![image](https://private-user-images.githubusercontent.com/89584709/310526339-f6a9a781-5669-4335-8aea-30c437415fd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTgyOTAsIm5iZiI6MTcwOTc5Nzk5MCwicGF0aCI6Ii84OTU4NDcwOS8zMTA1MjYzMzktZjZhOWE3ODEtNTY2OS00MzM1LThhZWEtMzBjNDM3NDE1ZmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA3NTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMzQ4NTU2MzBiNzYwNzQzZDdlYmU2MmI5M2FiYjIzZTBlZjFjYzcyMGI3NWZjMTY1YjdjYTAzMWI2NTQ5YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aCpzzySqX6hK7Ow9m3GmBWpGQh2bjR4fynIs2L_S7ac)

Hi @Jenefer-Monroe !
Could I just clarify, I need to check the state of the Power Platform Admin View app? Or you meant other app/flow? And I need to do that through the "share" button?

**Comment by Jenefer-Monroe** [comment]
Sorry for not being clear. The product itself offers these same sharing features. I'm wondering what it shows. 
So go to the product itself and click share, see what it shows for current membership.

**Comment by JanetK12** [comment]
@Jenefer-Monroe 
Thank you for the clarification!
 
The sharing as such works fine. But today the "Manage Permissions" also seems to be working in the Admin View App.
 
So I checked the Manage Permissions for the "problematic" item. From the Admin View App the user is shown as an Owner:
<img width="252" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/d859af8c-69ca-4f62-88d6-5830b75a8b15">

But in the Set Flow Permissions they are still displayed as Creator - I double-checked today:
![image](https://github.com/microsoft/coe-starter-kit/assets/113427788/1e014df3-06a8-45b0-adc7-41f7b37d2435)

Also in the Flows table the Derived owner is empty so it is still "orphaned":
<img width="378" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/fe449859-e8b7-46c5-8f7a-553114771de5">

**Comment by Jenefer-Monroe** [comment]
thanks, so its working today from the Power Platform Admin View app > Manage Permission button yes? This one? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6e585f37-7685-48fb-8b07-392f6a7fb1ee)

**Comment by JanetK12** [comment]
> thanks, so its working today from the Power Platform Admin View app > Manage Permission button yes? This one? ![image](https://private-user-images.githubusercontent.com/89584709/310480897-6e585f37-7685-48fb-8b07-392f6a7fb1ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODMzNDUsIm5iZiI6MTcwOTg4MzA0NSwicGF0aCI6Ii84OTU4NDcwOS8zMTA0ODA4OTctNmU1ODVmMzctNzY4NS00OGZiLThiMDctMzkyZjZhN2ZiMWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMjY0MTYxZGRiNTk4YmJhNzUxZDgwOWQ5YTA2YjRhYTE1ZWNhMTJmOGY1MmZhYzQ3ODNiZDg3ZjMxMmE3ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GFl7KQlCoRzNwO1651WwHpttl-XNglt8BuG36sFW_jU)

yes, you are correct! We were able to click to this button and then this opens
![image](https://github.com/microsoft/coe-starter-kit/assets/113427788/1e0bf207-fe1d-4e3a-9040-50ce3f1f3e87)
However, as I explained previously, seems we have something wrong or there is a bug?
 
> So I checked the Manage Permissions for the "problematic" item. From the Admin View App the user is shown as an Owner: <img alt="image" width="252" src="https://private-user-images.githubusercontent.com/113427788/310907236-d859af8c-69ca-4f62-88d6-5830b75a8b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODMzNDUsIm5iZiI6MTcwOTg4MzA0NSwicGF0aCI6Ii8xMTM0Mjc3ODgvMzEwOTA3MjM2LWQ4NTlhZjhjLTY5Y2EtNGY2Mi04OGQ2LTU4MzBiNzVhOGIxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQwNzMwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNThkYjRmN2RmZWRhNDhkZWMzNjczM2E2ODIzNTRmM2JiY2UyNTZlYTA1OTA1NGVjNmU0NjBlNjUyYjkxMGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CWGF1DYFUwK4K3Cw1kHGJ6Xk9KKJTMfU_-4J2zqj058">
> 
> But in the Set Flow Permissions they are still displayed as Creator - I double-checked today: ![image](https://private-user-images.githubusercontent.com/113427788/310907380-1e014df3-06a8-45b0-adc7-41f7b37d2435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODMzNDUsIm5iZiI6MTcwOTg4MzA0NSwicGF0aCI6Ii8xMTM0Mjc3ODgvMzEwOTA3MzgwLTFlMDE0ZGYzLTA2YTgtNDViMC1hZGM3LTQxZjdiMzdkMjQzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQwNzMwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTIyMWY0MDA3MDJjZTU5NDlkYTQyZmIzNjZmMWU5NDE3ZTU5MTM0OTFiMjkwNTcwOWU1NDc0MDdhZGZjNmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.daKg77G8ajoD8tJDOJXv7dkqRAvRYUxViXqM1-M2cIM)
> 
> Also in the Flows table the Derived owner is empty so it is still "orphaned": <img alt="image" width="378" src="https://private-user-images.githubusercontent.com/113427788/310907461-fe449859-e8b7-46c5-8f7a-553114771de5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODMzNDUsIm5iZiI6MTcwOTg4MzA0NSwicGF0aCI6Ii8xMTM0Mjc3ODgvMzEwOTA3NDYxLWZlNDQ5ODU5LWU4YjctNDZjNS04ZjdhLTU1MzExNDc3MWRlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQwNzMwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTZiODdlZGJhNjlhZTM5NTY3NDliYzQ2NzNlMGVhMDVjOGIxMGE0MzIwYzc5ZDg0ZmY2ZDU4OWQ1ZjJkOGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y8BYCRNaAXOvz7FXcCi3d4dICIQHU-eC1R3lYjJLZhQ">

**Comment by Jenefer-Monroe** [comment]
Please find the problematic flows in the Power Platform Admin View app and flag them for inventory. That shoudl fix up that field. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/191fdbac-2c9b-4a46-8d88-90dd23cef268)


Or you can manually fill the Derived Owner field with the user.

**Comment by JanetK12** [comment]
> Please find the problematic flows in the Power Platform Admin View app and flag them for inventory. That shoudl fix up that field. ![image](https://private-user-images.githubusercontent.com/89584709/311218410-191fdbac-2c9b-4a46-8d88-90dd23cef268.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTk0MTMsIm5iZiI6MTcwOTg5OTExMywicGF0aCI6Ii84OTU4NDcwOS8zMTEyMTg0MTAtMTkxZmRiYWMtMmM5Yi00YTQ2LThkODgtOTBkZDIzY2VmMjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDExNTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMWQ0ODdiZTRiZmY5ODRjNTY5ZTJmZDczNjgxYmNkZjE4MGZlNzhjMjdhODdjOTY3ZDg4NDgzODdmNGRlZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UpSH9pWAdNkmUxazGuQabhCl8FA3-1ExbV-WVUpLfXc)
> 
> Or you can manually fill the Derived Owner field with the user.

Thank you for your answer!
Yes, we have done it through the app! Could we ask, do you know how soon should we check whether it has helped?
 
Because if we start manually assigning owners, that might take some time as we have some 30-40 items that we have identified, and it might be even more.

And also, could we ask whether you know why it even happened like that? That it is shown as owner in one place, but in another as creator?

**Comment by Jenefer-Monroe** [comment]
If you flip that **_Inventory Me_** to Yes, it will run in the next day's inventory. 
I really dont know how you got into this state, but hopefully this will resolve.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
