### ISSUE TITLE
[CoE Starter Kit - QUESTION] Service account setup for coe kit/best practices.

### ISSUE THREAD

**Issue by Liam126126** [microsoft/coe-starter-kit#7781]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I've been through the documentation and I cant find any information on setting the coe up using a service account.

Would you be able to provide some info on how this would be done, in terms of setting up the service account? 

I've seen it mentioned a few times that the kit cant be setup with a service principal account, is that still the case?

Just trying to work out the best way to setup the kit without using a standard user account.

Any information would be greatly appreciated.

Thanks,

Liam

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2479

**Comment by Jenefer-Monroe** [comment]
Hello I think there may be some terminology issues here

You cannot use an app registration or **_service principle_** today to use the CoE kit, as not all of the connectors we use support authentication with a service principle.

Typically, customers use a named account with a "service name" to install the CoE kit - e.g. "CoE Admin". It's the same as a named account, but it's not tied to a "real" employee. The benefit is that if the employee leaves the organization or changes jobs/moves to a different department, the "named service account" can be handed over easily and you don't have to go through the trouble of changing ownership on all resources etc.

**Comment by Liam126126** [comment]
Great, thanks for the info, could MFA be used on the named account?

**Comment by Jenefer-Monroe** [comment]
The basic problem is that you need access at all times as you don't know when the flows will run. 
So MFA can be used with power automate, but you need to configure multi-factor authentication for the account by following the recommended settings for [conditional access and multi-factor authentication in Power Automate](https://learn.microsoft.com/troubleshoot/power-platform/power-automate/conditional-access-and-multi-factor-authentication-in-flow).

More details about the user that can be used for setup can be found here: [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
