### ISSUE TITLE
[CoE Starter Kit - Cleanup Old Objects App - Follow up to •	#5456-[CoE Starter Kit - QUESTION] CleanUp Old Objects

### ISSUE THREAD

**Issue by sasrsc** [microsoft/coe-starter-kit#7782]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I put in a comment after the 5456 item was closed so I'm guessing you will not be triggered to see it.
•	[#5456](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fissues%2F5456&data=05%7C02%7Crichard.clowes%40sas.com%7C78ba393579a24bcd3e9608dc3de2f9df%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C638453292266501037%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=OPcSzvOYMPDStGrP8T8rpUradifqOlaMMRMaBsOYxoo%3D&reserved=0)-[CoE Starter Kit - QUESTION] CleanUp Old Objects

Can you look at that question I asked please, as this appears to be not "uncommon". We will load the March release asap too.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Feb 24

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2480

**Comment by Jenefer-Monroe** [comment]
Hello can you please try out the March release and then let me know if you still have issues?

**Comment by sasrsc** [comment]
Will do…


Richard Clowes
Senior Director ● Travel Operations
Tel: + 1 919 531 7955 ● Cell: + 1 919 413 3084 ● ***@***.******@***.***>
Worldwide Headquarters ● Cary, NC

www.sas.com<http://www.sas.com/>
SAS® … THE POWER TO KNOW®

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
