### ISSUE TITLE
[CoE Starter Kit - QUESTION] DLP Editor v2 app launch error

### ISSUE THREAD

**Issue by karbip** [microsoft/coe-starter-kit#7784]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

DLP Editor V2 app launch from CoE Command Center Bookmarks page give me error: "Sorry, we didn't find that app"
Screenshot attached
![For CoE-github query](https://github.com/microsoft/coe-starter-kit/assets/131582958/e58f44a6-fbbf-4890-9268-19b58d163210)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2482

**Comment by Jenefer-Monroe** [comment]
Hello the canvas version of the app was removed in Sept 2023 version of the CoE Starter Kit (Core version 4.15)
The new version of the app is the Model Driven App: DLP Impact Analysis

We do not have a process to delete the removed connections from the bookmark page so you need to remove it manually 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/08851014-b275-4eb5-8bb1-4b4ad302cef1)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f9821a67-ffaa-4afd-9a07-f686aae8a0d4)

**Comment by karbip** [comment]
Thank you for the quick responses!
