### ISSUE TITLE
[CoE Starter Kit - QUESTION] Not able to create a group from Setup Wizard

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#7785]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 

We are getting this error while we are trying to create a group from setup wizard, though the user have GA permissions

<img width="449" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/9cc498f9-ebcb-4997-beb1-6ae8a0484cc3">

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2483

**Comment by Jenefer-Monroe** [comment]
We have seen this from time to time. The best option here is to go ahead and create the group in the Azure portal and then select from here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
