### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade of Core solution failed

### ISSUE THREAD

**Issue by Gpn85** [microsoft/coe-starter-kit#7789]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have tried to update the Center of Excellence - Core Component to the Release March 2024 (version 4.24), upgrading from version 4.22. Unfortunately, we keep getting the following error message.
![image](https://github.com/microsoft/coe-starter-kit/assets/162493817/35103519-e25b-4dfe-96d4-514ddab28d5d)
"Connection State is closed. Please open the connection before executing the command."
(in the log there are 52 instances of the error).
As a result, we now have both solutions 4.22 and 4.24.
In the solution history, import of 4.24 shows as successful, however 4.22 was not uninstalled.
Would you know what could be an issue here and how should we procced with the upgrade?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

AB#2487

**Comment by Jenefer-Monroe** [comment]
We did delete the Legacy Dataverse connector this month ahead of its deprecation, so if you had your own dependencies on it that may cause issues. 

You can go look for that in the Default Solution > Connection References > Find the legacy dataverse connectors and look at dependencies
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fdaf3842-4f05-466c-96a8-0c0e4da3408c)

These are the ones we ship with
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8b3844c4-f421-4cfc-becb-227ecc9b7d60)

Any outside of these you will need to cleanup manually, then you can delete the _upgrade version of Core and try again.

**Comment by Gpn85** [comment]
I can see these 17, same as on your screenshot with only one additional: Admin | Sync Template v3 (Driver) - which is not on your screenshot.

![image](https://github.com/microsoft/coe-starter-kit/assets/162493817/fb4fad91-e414-481f-a0d6-56e1c6d93175)

**Comment by Jenefer-Monroe** [comment]
ok I looked this error message up online and it appears unrelated to my first guess so I'll hide all that information to avoid confusion.

**Comment by Jenefer-Monroe** [comment]
It sounds like this is a product bug around the connection ux. My my reading, if you create the connections before you install this should be avoidable. In particular I think you just need to create this one: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cb6252bb-f686-4f45-89ba-12ecb42bf881)

Plesae go make sure it exists already, and if so check to be sure it has the graph url for its url
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1e058787-ce33-4dc9-9c5e-12787d47ae4b)

**Comment by Gpn85** [comment]
Hi Jenefer,
I have verified the HTTP with Microsoft Entra ID connection is there and has correct url: https://graph.microsoft.com/

**Comment by Jenefer-Monroe** [comment]
ok please do try again today. PErhaps there was some transitory issue for you. 
Others are successfully upgrading so there is something happening to you that isnt universal. We can bang around a bit more and try to resolve together though.

**Comment by Gpn85** [comment]
Hi Jenefer,
since I had the 4.24_upgrade in place, I have decided to go with the 'Apply upgrade' option. It was spinning for a moment and then failed with Timeout error. However, it still triggered uninstallation of the old solution and it removed it successfully. The upgrade shows as successful now, went through the upgrade wizard as well and everything seems to be working as expected.
Thanks a lot for your help, you can go ahead and close this issue:)

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thanks for following up to let me know. I’ll go ahead and close
