### ISSUE TITLE
[CoE Starter Kit - BUG] Upgrade from 2.1.70 Core

### ISSUE THREAD

**Issue by CarstenGrowth** [microsoft/coe-starter-kit#779]
### Describe the issue

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 3 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoEAuditConnection, Id: b092e10f-fa4d-44d4-9f6b-90c1d2ef2431, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEAuditConnection, Id: c64d690b-d47d-4c93-b765-9a1b674e5bbf, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEConnection, Id: a4a56882-4723-48de-b646-debab953e358, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

### Expected Behavior

Upgrade without errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### Steps To Reproduce

Import CenterofExcellenceCoreComponents_2.2.20210707.3_managed

**Comment by manuelap-msft** [comment]
Hello,

we had some issues with the releases from yesterday and just re-released: https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-July2021a

We removed some cross-dependency issues between solutions, so you may have to upgrade Audit Logs first to ensure the flows in that solution only use connection references from its own solution.

Thank you
Manuela

**Comment by CarstenGrowth** [comment]
Tried the new packages by starting with the Audit-Log solution upgrade first. Unfortunately, this resulting in another error message: Solution "Center of Excellence - Audit Logs" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f691c36f6fa56d15c_4a1b8, Id: 71eb08d0-4d25-4fba-a84a-90d6f5b3c6bb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

**Comment by manuelap-msft** [comment]
Hello,

as discussed offline, please use **Update** instead of Upgrade during the Import. This should resolve the dependency issues. 

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
closing out now that we've moved on to August
