### ISSUE TITLE
[CoE Starter Kit - BUG] DATA EXPORT BLOCKING BUG: BYODL Maker Dataflow Refresh Cloud Flow has Terminate step that needs to be removed

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#7790]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the latest release of Core (4.24), the BYODL Maker Dataflow Refresh Cloud Flow has a Terminate step in the middle of the Update makers and refresh next dataflow Scope right after the List Makers step that needs to be removed.  As long as it's there, the maker updates don't happen and it doesn't kick off the next Dataflow or update the last run as a pass.  Once removed, things seem to work correctly again.

### Expected Behavior

Cloud Flow execution should move past that point.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

CoE BYODL - When Maker dataflow refresh is complete

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Run that Flow and see that things don't happen that are supposed to happen.
![Screenshot 2024-03-06 133652](https://github.com/microsoft/coe-starter-kit/assets/41799380/562f8f17-5c86-40d8-8d3c-4324666be443)

AB#2488

**Comment by Jenefer-Monroe** [comment]
Thanks for posting! Thats embarassing! 
I've local fixed this but given the low usage and preview nature of the Data Export feature we wont reship with this. Folks will need to local fix by deleting that action and we will have it correct for April.

**Comment by RickKush** [comment]
I can't find the terminate step in the CoE BYODL Makers Dataflow.
