### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Apps Launches table location

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#7791]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, I am trying to establish a process to identify which Power Apps are actively used. My plan was to leverage the table Power App Launches that I see in the reports but I am unable to find it in Dataverse. Could you please direct me where I can get it from? Thanks!

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/1a0b22f5-20ee-4410-a9b2-7851aa3b2da5)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2490

**Comment by Jenefer-Monroe** [comment]
If you are using the Cloud Flow architecture, then the launch information is stored in a table called Audit Logs in Core.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c4a906c1-ae42-4d37-a599-3b223c848a33)

Hope that helps!

**Comment by santiareh** [comment]
@Jenefer-Monroe That was it! Thank you so much Jenefer!

**Comment by Jenefer-Monroe** [comment]
wonderful!
