### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE Total share is 0

### ISSUE THREAD

**Issue by Fadel1949** [microsoft/coe-starter-kit#7793]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

@Jenefer-Monroe  Hello, I have problem, the total share is 0. I checked the data in the "power app user role" table and there is normal data in the Group size, but why is the total share 0? The solution is managed, and I cannot view the formula of the Column Rollup.

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/96f94826-9848-4131-9bdf-f256427c531f)
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/e90cf47f-1750-4f7d-b866-e0488d3d22dc)

### Expected Behavior

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/96f94826-9848-4131-9bdf-f256427c531f)
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/e90cf47f-1750-4f7d-b866-e0488d3d22dc)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

filed in Dataverse "PowerApps App" Column "Total Shared"

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2492

**Comment by Jenefer-Monroe** [comment]
Hello. Here is the formula it dips into the related table and pulls the sum
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e29281e8-bb38-4c9a-b8f9-10db32e8ef37)

Can you see when it was last updated? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dbff25e5-88b0-472b-829e-08597bf92ecc)

**Comment by Fadel1949** [comment]
@Jenefer-Monroe  
I have checked and updated daily. The data in the table, in the Group size field, is available, but Total Shared is not calculated. I cannot access the formulas because the solution is managed.

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/52a78bd9-05dd-497d-9eb9-ed1d73c13174)

**Comment by Jenefer-Monroe** [comment]
These are just roll up fields so not something we can really control. 
Can you add and expand all the columns shown here, so we can see which is which? And sort so we can see the largest number number in the Total Shared column
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b051a3a6-6166-44de-aa91-8141766d5015)

**Comment by Fadel1949** [comment]
@Jenefer-Monroe   Yes 

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/bb4769e6-03d7-4f70-b0f2-e484e8eda9b1)
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/e430f186-9c6f-496e-9b3e-afd20a5e2c53)

**Comment by Jenefer-Monroe** [comment]
These roll up fields are just an out of the box product feature we are using. It could be that the rollups broke or got deactivated somehow. Please [View Rollup Jobs](https://learn.microsoft.com/power-apps/maker/data-platform/define-rollup-fields#view-rollup-jobs) and see their state.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/50ca6f07-dc57-4188-8db6-47198478608b)

**Comment by Fadel1949** [comment]
@Jenefer-Monroe 
Status looks like it's finished.
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/55bd0175-e30f-4065-a8be-3f5f5a1672df)

**Comment by Jenefer-Monroe** [comment]
OK im not sure then. I'm afraid these are just roll up fields, not something we control. If they are not working then that would be a product issue. 
I guess its possible you have these records without the child table filled. 
This flow is running and passing without unmanaged layers correct? CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

**Comment by Fadel1949** [comment]
@Jenefer-Monroe 

Yes, it run successfully.
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/b0811e9d-517b-4b6c-ac94-ded4035b5163)


According to what I explained, if it's just a Sum Rollup from the Power Platform User Roles table, field Group size, can I use my own Sum formula instead? Without using the Rollup field since it's not yielding results, is that possible?
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/f5097ce1-825e-4ef8-ba7a-3cf2bc1b3cb9)

**Comment by Jenefer-Monroe** [comment]
One last thing we can try is to make sure the formula hasn't changed in your envt. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e29281e8-bb38-4c9a-b8f9-10db32e8ef37)

You can do that by going to the table outside the context of the solution. Here is a write up for Makers you can mimic
### Check roll up formula in managed install
This example uses the Number of Apps field in the Maker table. Match with your case.
Go to tables outside of a solution, find the Maker Table, go to coumns, find this column and look at the formula
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/aa04dde8-0501-4485-aaec-6a48c80e0ae1)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f578ff89-0c7a-4337-991f-54a610ba0e62)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0952c430-4614-4b10-8842-a06b1e7f6c84)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1536eb88-3277-4f7b-b4c2-9c969c1c9019)

**Comment by Fadel1949** [comment]
@Jenefer-Monroe  I checked it, there were no errors displayed.
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/10ee2cd1-81a6-440e-a258-f7380731a52e)

However, when I tried to resume, it appeared that the Rollup system had already provided it. Thank you very much.
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/df374a8a-c59c-457b-bb49-351940455236)
