### ISSUE TITLE
[CoE Starter Kit - QUESTION] Minimal privileges for Add-Maker-to-group Flow

### ISSUE THREAD

**Issue by Saxsma** [microsoft/coe-starter-kit#7794]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

Since we installed CoE-Starterkit, we get an error on 'Add Maker to Group:

![1](https://github.com/microsoft/coe-starter-kit/assets/160040344/a7e7cbe4-bf02-4872-af8d-f299445d88b1)

![2](https://github.com/microsoft/coe-starter-kit/assets/160040344/7e0c1176-abe9-4534-a84c-a795c43699c8)

![3](https://github.com/microsoft/coe-starter-kit/assets/160040344/c334c363-cd7a-43fa-ac29-57c7710892d0)

The account running the routine has permanent PowerPlatform Administrator priveleges, but what else is needed to be granted to add Makers to the Entra Group?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2496

**Comment by kubilaygithub** [comment]
@Saxsma 
Subscribed waiting for an answer/solution. :) ;)

**Comment by Jenefer-Monroe** [comment]
Hello. The identity running the flow needs to be owner of the group that is used. This is just a requirement for Groups generally. 
Hope that makes sense.

**Comment by Saxsma** [comment]
Hello Jenefer, thanks for your quick reaction! Makes perfect sensse, I'll go and check it out on this particular Group, I'll let you know.

**Comment by Jenefer-Monroe** [comment]
We're here to help. Please do let me know!

**Comment by Saxsma** [comment]
@jenefer
Just checked, shocking to see there are zero owners. I don't have the privelege to add owners to an Entra-ID Group, does one need Global Admin rights to do so? Then I know who to ask.

![image](https://github.com/microsoft/coe-starter-kit/assets/160040344/3d987531-fb5a-4e85-b561-17cd9684a5dc)

**Comment by Jenefer-Monroe** [comment]
Thats my understanding yes. And I'm so glad you know who to ask! Not everyone does. YEAH

**Comment by Saxsma** [comment]
Haha, point taken! Thanks for your help so far, in case I more questions, I'll mention them here.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
