### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Logs - Client Azure Secret

### ISSUE THREAD

**Issue by L0k33** [microsoft/coe-starter-kit#7797]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What am I doing wrong, with the "Audit Logs - Client Azure Secret". I created a flow which is able to get the secret, but when I setup up the environment variable, it asks me to ensure that "Microsoft.PowerPlatform provider is registered in the Azure subscription", which it is. Other times, I get the error stating that the User is not authorised to access the Key Vault secret, but it has, as the test Get-Secret workflow is able to...

![image](https://github.com/microsoft/coe-starter-kit/assets/107485479/9038dede-68b8-47c2-a51b-3ad1a6d55d4c)

![image](https://github.com/microsoft/coe-starter-kit/assets/107485479/105c888b-b097-4f31-b75d-720b7b4265aa)

![image](https://github.com/microsoft/coe-starter-kit/assets/107485479/ebc5ece8-a8ec-4fa0-b972-55ba010c5861)

Test workflow:

![image](https://github.com/microsoft/coe-starter-kit/assets/107485479/7944463f-7c2d-47bc-8a01-8fe76bb073de)

Any ideas? :)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

4.23

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2499

**Comment by Jenefer-Monroe** [comment]
Hello. Here are the minimum permissions needed to access and setup secrets in Power Platform. 
If you have these permissions and cannot create the env variable I'm afraid this is a product issue. 

You must have both these roles explicitly. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d8a6d0dc-21f6-494c-91c0-eff853da0c0a)
