### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs - Client Azure Secret (Environment Variable) #7098

### ISSUE THREAD

**Issue by L0k33** [microsoft/coe-starter-kit#7799]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

See links:

https://github.com/microsoft/coe-starter-kit/issues/7797
https://github.com/microsoft/coe-starter-kit/issues/7098

### Expected Behavior

Unable to configure Environment Variable - Audit Logs - Client Azure Secret

Do we have any time scales for resolving this issue? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Audit Logs - Client Azure Secret

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

See ticket 7798

### Anything else?

No

AB#2501

**Comment by Jenefer-Monroe** [comment]
Seems like a dupe to the other issue you posted today. https://github.com/microsoft/coe-starter-kit/issues/7797
Closing out as dupe.
