### ISSUE TITLE
Custom Connector oauth settings break after Solution Import

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#78]
**Describe the bug**
Every time we import a Solution with a Custom Connector that's configured for oauth the connector stops working and oauth needs to be reconfigured.

**To Reproduce**
1. Import Solution with a Custom Connector that has already been configured to use oauth  
2. Wait long enough for token refresh 
3. Connector stops working

**Expected behavior**
After Solution Import a custom connector should have its oauth configuration preserved

**Additional context**
This is not an issue we can fix.  This is an issue in the platform.  However, we are working with internal teams to get this addressed.

_**Please vote this one up with  👍 so we can help show demand.**_

**Comment by rpothin** [comment]
I am not sure custom connector oauth configuration should be preserved because sometimes you will not have the same configuration for non-production and production environment.

But, yes, for sure the lifecycle management of the oauth configuration in the custom connectors should be improved.
The fact that we need to reconfigure that after import is not really "user friendly".

**Comment by mikefactorial** [comment]
@rpothin the idea is not to preserve the oAuth between environments, but to not break the existing oAuth once the connector is configured in an environment. So, if the custom connector is already configured with oAuth in production then deploying the solution shouldn't disturb the existing oAuth. As of today the oAuth has to be reconfigured as you mentioned.

**Comment by rpothin** [comment]
😅 oh ok, thank you for the precision @mikefactorial and sorry for the misunderstanding.
In that case we need a solution yes 😊

And, do we have a way to do the oauth configuration for a custom connector in a pipeline / workflow?

**Comment by devkeydet** [comment]
Not today.  It's possible with paconn, but that doesn't have a headless login option and the backing API doesn't support service principals today.  See:
https://github.com/microsoft/PowerPlatformConnectors/issues/678

We're in ongoing discussions about a headless / automated approach.  But today, the only successful way I have been able to automate this is through RPA using Desktop Flows.

**Comment by devkeydet** [comment]
After discussing this with the team that owns this, we have discussed how to address this quickly.  Today, when you export a custom connector that has an oauth configuration, you will see a *_connectionparameters.json file.  Here is an example.
https://github.com/microsoft/coe-starter-kit/blob/main/PowerPlatformDevOpsALM/SolutionPackage/Connectors/cat_5Fcustomazuredevops_connectionparameters.json

When the file has any valid json, including {}, the Solution engine will attempt to update the custom connector with the values in the file.  Since the secret is never exported, the oauth configuration is getting updated with the values in the file and therefore clearing out the secret after import.  The short-term fix will be to empty out the contents of the *_connectionparameters.json file.  When the file is empty, the solution engine will not attempt to update the oauth configuration.  Therefore, the previous configuration will be preserved.

This will require a fix in the platform to be rolled out.  That can take 4-6 weeks before it is live.  We will keep this issue open until the fix is live.
