### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by mabaugh83** [microsoft/coe-starter-kit#7800]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

From power bi report Production_CoEDashboard_March2024.pbit - after importing and resetting up the apps for flow and app access, the app deep dive has no link from drill thru to the manage app access app. Flow deep dive does
![image](https://github.com/microsoft/coe-starter-kit/assets/70452834/b5e2535d-df3e-4f28-b550-877fd5c5f3f4)
![image](https://github.com/microsoft/coe-starter-kit/assets/70452834/50207437-5256-4947-98e6-98b8279d4e4a)

### Expected Behavior

would have link on power bi drill thru to the manage app access

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Power BI Dashboard

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Open power bi dashboard
click on App deep dive
right click on app
click on drill through
link is missing

AB#2502

**Comment by mabaugh83** [comment]
from the exact same page - app deep dive. we are GCC but wouldnt think that would make any difference - i see the other 4

**Comment by mabaugh83** [comment]
I reimported pbit saved, then reset the apps. The only thing i did different was save prior to resetting the apps and now it works.

**Comment by Jenefer-Monroe** [comment]
Thanks for letting me know!
