### ISSUE TITLE
[CoE Starter Kit - QUESTION] Subscription not selectable

### ISSUE THREAD

**Issue by emcsweeney** [microsoft/coe-starter-kit#7801]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

After following the instructions for the creation of premium blob storage [https://learn.microsoft.com/en-us/azure/storage/blobs/create-data-lake-storage-account](url) and confirming all settings match requirements [https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics#set-up-the-data-export-process-for-your-tenant](url), when I go to the setup wizard for Data Export in the Power Platform Administration portal I can see and select my subscription, see and select my resource group, but cannot see nor select my storage account.

<img width="1152" alt="DataLakeExportIssue" src="https://github.com/microsoft/coe-starter-kit/assets/162609377/44791dc4-32e7-4d50-9f61-251c158e9162">

Interestingly, this only happens if the storage account is premium blob (which, per the requirements, should work). If I set up a standard storage account, I can see and select it. I would prefer not to use a standard account for performance reasons.

I also confirmed this same issue with an internal Microsoft contact whose name I can share if that will help. He likewise set up a premium block blob storage account per the instructions, verified all RBAC settings, and experienced the same problem. When he set up a standard storage account, he was able to see and select the storage account. So I do not think this is a misconfiguration issue on my side.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Data Export

AB#2503

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately this is not something we can assist with. This is the product feature itself and so issues with the set up of the Data Export feature will need to go to Product Support team. 
https://learn.microsoft.com/power-platform/admin/get-help-support

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
