### ISSUE TITLE
[CoE Starter Kit - BUG] Video Hub Page not found in Nurture Apps Maker

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#7802]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After finishing the update to the latest CoE version I wanted to see how the Video Hub was looking with the new updates to begin using it, but I get an error message saying the page does not exist in the Nurture apps - Maker.

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/c8a7f3b2-527f-487c-b4e1-b7eeb9253c43)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Nurture apps -Maker

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the Nurture apps - Maker App
2. Open the Video Hub page

AB#2505

**Comment by santiareh** [comment]
Even when I try to edit the app I get the same error.

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/f285a27f-9662-4ef1-a4f5-b5934cc056cf)

**Comment by RahulBojji** [comment]
Thanks for posting. We can repro this issue. Assigning to area owner for further investigation

**Comment by lukas-nC** [comment]
@santiareh if you add the custom pages "Video Hub New" and publish, it seems to work

**Comment by Jenefer-Monroe** [comment]
Hello this is present in the Nurture apps - Maker app, not in the Maker Command Center
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/01fcfb6c-e2eb-464f-8209-2691e186e8f8)

One of the reasons we switched to Model Driven Apps though was for this flexibility to allow people to customize. So if you wish to have this in the Maker Command Center as well you've found how to do that. 

Hope that helps!

**Comment by Jenefer-Monroe** [comment]
Looks like we didnt publish before we shipped? Odd. 
Fixed now for April. Thank you for posting!

**Comment by santiareh** [comment]
@Jenefer-Monroe @lukas-nC Thanks for the help, I got it going now. Hopefully I remember to remove the unmanaged layer for the next update lol

**Comment by Jenefer-Monroe** [comment]
@santiareh, the Setup Wizard does not tell you about unmanaged layers on custom pages too :) YEAH
