### ISSUE TITLE
GHD CoE Power BI Dashboard has failed to refresh.

### ISSUE THREAD

**Issue by santanuchokda** [microsoft/coe-starter-kit#7803]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

GHD CoE Power BI Dashboard has failed to refresh.
Failure details: The last refresh attempt failed because of an internal service error. This is usually a transient issue. If you try again later and still see this message, contact support. 
The '<ccon>admin_user</ccon>' column does not exist in the rowset. Table: Power Platform User.

### Expected Behavior

The error appears after the update of COE Core components from May 2022 to February 2024 version. Didn't had any errors before the update.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

GHD CoE Power BI Dashboard 

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Go to dashboard
Data sets
Center of excellence data set
Refresh data
Error

AB#2506

**Comment by Jenefer-Monroe** [comment]
Hello. You need to have the PBIT file and the Core version match. Every time you upgrade you need to do this to overwrite the current PBI. Sometimes you may be able to get away without doing it but then you might miss new features too! 

In the download file you will find PBIT files named with the month. 
For Feb 2024 you will see Core version 4.23 which you say you now have installed. So you will need to use its matching PBIT: **_Production_CoEDashboard_February2024_**

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9d5fdad5-c610-479e-b20d-3efc7df54895)

**Comment by santanuchokda** [comment]
Thanks Jenefer. Can you please guide me the steps how to overwrite this file?


Cheers
Santanu Chokda
SharePoint Administrator

GHD
Proudly employee-owned | ghd.com<http://www.ghd.com/>
Level 9/180 Lonsdale St, Melbourne VIC 3000
D +61 0 38687 8254 | M +61 470 230 248 | E ***@***.******@***.***>

***@***.***
The Power of Commitment

Connect

[linkedin icon]<https://www.linkedin.com/company/ghd/>
[facebook icon]<https://www.facebook.com/GHDGroup>
[twitter icon]<https://twitter.com/GHDspeaks>
[youtube icon]<https://www.youtube.com/channel/UCwUGfe6zgaddIXqA7entIwQ>
Please consider the environment before printing this email

**Comment by santanuchokda** [comment]
I was able to overwrite the package and error message has disappeared now. Thanks for your help!

**Comment by santanuchokda** [comment]
I was able to overwrite the package and error message has disappeared now. Thanks for your help!
