### ISSUE TITLE
Unable to upgrade "Center of Excellence - Core Components" from 4.2

### ISSUE THREAD

**Issue by kiri-devanayagam** [microsoft/coe-starter-kit#7804]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I am trying to upgrade  "Center of Excellence - Core Components" from 4.2 and getting the following error message.

Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :Import failed: The column 'admin_makersubmittedrequirements' is dependent on column 'admin_requirement_2'. ALTER TABLE ALTER COLUMN admin_requirement_2 failed because one or more objects access this column.

Can you kindly help?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponents

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2507

**Comment by RahulBojji** [comment]
@kiri-devanayagam  Thanks for reaching out, we have seen a few people hit this and it was because they had customized one of the fields.
Please check [this](https://github.com/microsoft/coe-starter-kit/issues/7419)

**Comment by kiri-devanayagam** [comment]
Thank you for that information. I'll give it a go and let you know.
Appreciate your help.

Regards,
Kiri

**Comment by kiri-devanayagam** [comment]
Got the error below trying to import,

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 2 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: ed64cb76-0187-4f4c-9467-1945d50e5071, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published .

**Comment by RahulBojji** [comment]
ok, but I am not pretty sure how were you able to update till 4.23 version, as we have removed the Office 365 Managament API connector long back. This is a known issue documented here: https://github.com/microsoft/coe-starter-kit/issues/6018
We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors.
If you have tried those steps and still see this error, note that some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) these remaining connections to the old connector.

**Comment by kiri-devanayagam** [comment]
Hi Rahul,

I've tried deleting the existing upgrade component and it still complaining about non office 365 API connectors as below.
I read through the document and uninstalled the audit log component and also reference to office 365 API connector but still can't delete the core-components upgrade.

![image](https://github.com/microsoft/coe-starter-kit/assets/162652795/c4a0cb58-be3f-4431-bfa0-494c4584d0f4)


![image](https://github.com/microsoft/coe-starter-kit/assets/162652795/4da60c79-e023-49f8-8287-cd00c0d5ec97)

**Comment by RahulBojji** [comment]
Just wanted to understand the state in which your environment is on. Can you please share screenshot of the list of solutions you have installed in your environment just like below. Please make sure you are expanding the highlighted columns.
![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/bf36b1ac-199e-48cd-9951-bfd1132af095)

**Comment by kiri-devanayagam** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/162652795/740ca7ac-2dfa-4ca4-9cc2-5d123d03fe03)

Thanks Rahul

**Comment by RahulBojji** [comment]
Can you please confirm if you have removed the office 365 api because some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) these remaining connections to the old connector.

**Comment by kiri-devanayagam** [comment]
Hi Rahul, I have not had the chance to use the powershell method. I will try and get back to you.

**Comment by kiri-devanayagam** [comment]
Hi Rahul,
Does the following qualify as office 365 connectors?
![image](https://github.com/microsoft/coe-starter-kit/assets/162652795/1803a555-0915-4c0b-845a-1dd5be4d1d7c)

**Comment by RahulBojji** [comment]
No, the above can't be removed as those are product offered connectors. Look for "**admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08**" as this is the custom connector that needs to be removed. Name of the connector: "**Office 365 Management API**"

**Comment by kiri-devanayagam** [comment]
Then I can confirm that there's no connector with that name that exist.

**Comment by RahulBojji** [comment]
@kiri-devanayagam Well, the steps we mentioned above worked for everyone. We are also not sure how to make you unblocked as we haven't seen the upgrade error you are experiencing before. One last thing we can give it a try is to click on "Apply Solution Upgrade".  This uninstalls all previous patches and the base solution then rename the _Upgrade solution to be the same name as the previous base solution. Please look at [this](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/update-solutions) for more information

<img width="473" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/e6ab3912-9b59-41e2-b9e1-d847a12e9a90">

For doing that

You can click on "switch to Classic"

<img width="791" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/3dcf205c-3a8e-4667-b0d9-3ab7ca56b84c">



<img width="923" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/9199df70-71b2-461f-8723-40ba5d462ead">

**Comment by kiri-devanayagam** [comment]
Thanks Rahul. The upgrade went alright. Do I need to do the same for other components?

![image](https://github.com/microsoft/coe-starter-kit/assets/162652795/b0392277-2ad8-4a9f-ba66-f56f1c022ac2)

**Comment by RahulBojji** [comment]
Looks like all the components are in the perfect state. Can you please let me know what your ask was for my better understanding ??

**Comment by kiri-devanayagam** [comment]
Thanks Rahul. That's good to know. I wondered if I need to update the other components. Thanks for your help. Much appreciated.

**Comment by RahulBojji** [comment]
We recommend upgrading the CoE Starter Kit solution at least every three months. If you want to update the other solutions now you can do it as per your requirements if there is any by checking the [release notes](https://github.com/microsoft/coe-starter-kit/releases) which is in sync with the core components solution version.

**Comment by Jenefer-Monroe** [comment]
Please note that this was a one off known complication for upgrade due to the deprecation of the Audit Logs custom connector.
Typically our upgrades go pretty smoothly for most people and as Rahul says, yes we recommend upgrading all components when you upgrade Core.

**Comment by kiri-devanayagam** [comment]
No Worries. I got it. Thanks Jenefer.
Thanks heaps for all your help Rahul.
