### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis shows every app & flow being in violation

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#7807]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The DLP Impact Analysis tool has started showing all the apps and flows as violating DLP policies which is incorrect.
e.g. the Jan 2024 version shows no violations but the March 2024 version shows 65 apps and 263 flows. 
![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/d0cf0a4a-60ca-4caf-af1a-254d8b803e80)

### Expected Behavior

The DLP analysis tool should show only the apps/flows that are in violation of the DLP policies.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

CoE SetDLP Impact Analysisup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the DLP Impact Analysis app
Select a DLP policy and click edit policy
Click Next until you reach the Impact Analysis step
All the flows and apps are listed.
Clicking the View Impact icon shows the connection in violation but it is allowed.

AB#2513

**Comment by Jenefer-Monroe** [comment]
to app owner for investigation.

**Comment by RahulBojji** [comment]
@MartinWGT  There was a bug on impact analysis not displaying the apps and flows correctly. We fixed that bug in the march release. 

Can you please share the connectors you have under Business and Blocked in the DLP policy.

<img width="799" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/10cbd3b9-e7af-4e16-8421-1e9fd2223910">

Also please verify on the Impacted apps and flows if the apps have the correct connectors or not that you have under Business and Blocked

<img width="630" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/a1e11ac7-a678-4d93-bc5a-45d8b032cf8b">

<img width="675" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/31d7d1a8-cb8c-4a05-9041-778ebe7d1b82">

**Comment by MartinWGT** [comment]
Hi @RahulBojji 
Here's a couple of screen shots of the business connectors
![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/1656cdd8-c77b-4908-b8b5-0f9053ce3581)
![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/4497c234-2dd1-41bf-9fb5-602b2b9ae02e)


It shows SharePoint and Outlook are allowed togther.

And here's an example app. It only uses the SharePoint connector and this is allowed in the Business group, so it should not show up as violating DLP.
![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/33999096-1613-44ba-a27e-9dbae43ce78b)


And here's a flow using SharePoint and Outlook. It is running, as expected, so should not show here.
![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/66c204f9-a959-4b6b-9f52-f30d2802b5b5)

**Comment by RahulBojji** [comment]
@MartinWGT This is as expected. We are displaying app or flow as impacted by considering both Business and confidential connectors. Taking SharePoint connector as an example, apps using only SharePoint connector will also be displayed along with a combination of other business classified connector.

**Comment by RahulBojji** [comment]
Confidential connectors are blocked connectors.

**Comment by MartinWGT** [comment]
Thanks. I've not heard them called that before.

**Comment by Jenefer-Monroe** [comment]
Thanks for your patience. Have confirmed this is a regression from the recent changes to the app in March. 
Rahul will resolve for April. In the meantime do note that the CSV export is not broken so you can use that.

**Comment by accvik** [comment]
I can confirm I have the exact same issue as @MartinWGT 

As @Jenefer-Monroe said above though, workaround is to use the "Export to CSV" which does not have the same bug.

**Comment by MartinWGT** [comment]
Agreed, the Export function works.

**Comment by PetarHr** [comment]
For us the Export to CSV option also returns wrong results. In a DLP change we are blocking the "Project Roadmap" connector. When we run the Impact Analysis & export the CSV we get only 4 rows as affected by the change. However we have many flows & apps in the environment that will be actually affected by this. Example below: 

1. CSV shows 4 flows will be impacted
![image](https://github.com/microsoft/coe-starter-kit/assets/46760757/ac883782-9a21-46e2-8cef-82974c78067f)

2. In the same environment we know that there are multiple flows that use that connector. For example the below app is not present in the CSV export
![image](https://github.com/microsoft/coe-starter-kit/assets/46760757/3f804b34-f85d-4de0-9d41-82bdc2a76084)

We also noticed that the CSV shows only suspended & stopped flows.

Same issue is observed for the Apps export CSV - it lists only 3 records, when we check there are more apps that will be impacted by the DLP policy change.

**Comment by RahulBojji** [comment]
@PetarHr Can you please open the below flow which will be present in the Core Components solution and check the run history

Please check whatever the apps or flows the connector is using is available in the output or not. Click on "Click to Download" and check if the apps or flows are available or not.

<img width="814" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/7c114b7a-a216-46bf-af72-23f37e7b2e39">

<img width="548" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/0eafa72a-d753-42fb-8532-d1b8bb40d833">

**Comment by PetarHr** [comment]
@RahulBojji - In the List Apps & List Flows outputs I can see multiple flows & apps, yes. (313 apps & 1179 flows) This still looks odd, as I can see in the results flows & apps from different environments, when we run the DLP Analysis for only a specific one. Let me know if there is something else I can help with here? :)

**Comment by RahulBojji** [comment]
> @PetarHr Can you please open the below flow which will be present in the Core Components solution and check the run history
> 
> Please check whatever the apps or flows the connector is using is available in the output or not. Click on "Click to Download" and check if the apps or flows are available or not.
> 
> <img alt="image" width="814" src="https://private-user-images.githubusercontent.com/149372606/317154678-7c114b7a-a216-46bf-af72-23f37e7b2e39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzMwNDEsIm5iZiI6MTcxMTUzMjc0MSwicGF0aCI6Ii8xNDkzNzI2MDYvMzE3MTU0Njc4LTdjMTE0YjdhLWEyMTYtNDZiZi1hZjcyLTIzZjM3ZTdiMmUzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwOTQ1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzJhYmI0OGJhYzQwZThlNTVmZGVhMWE5YzExNWJlMTQzMWFlMzA1NzA3YWM3M2M3MWJkMWVkNGJkYzM0ZDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8XYhg75yxiW_LTB1t3094ErzvpZ6q-Gq66gDcYc8mk4"> <img alt="image" width="548" src="https://private-user-images.githubusercontent.com/149372606/317155448-0eafa72a-d753-42fb-8532-d1b8bb40d833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzMwNDEsIm5iZiI6MTcxMTUzMjc0MSwicGF0aCI6Ii8xNDkzNzI2MDYvMzE3MTU1NDQ4LTBlYWZhNzJhLWQ3NTMtNDJmYi04NTMyLWQxYjhiYjQwZDgzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwOTQ1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTZiNzY3ODU1YmE4ZWI0ZmQ1MGFiNjIyZTczZmQ1OTU2ZWYwM2UyZDM2MGI2Mzk2YmE1N2JiNzIzYzhhMzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aMVMdmCbkg4G7r7RRaxlEsgSC8H-wxVjb353rN8pmNE">

Please check in the outputs of List apps and in the list flows whether the apps and flows which uses connector "Project Roadmap" is available or not. If those are not available in that they will not be added into the CSV.  Basically, the list apps and list flows action will fetch all the apps and flows from environments on which the DLP policy is applied. 
Also check the outputs of this action here. This shows on how many environments the policy is applied

<img width="638" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/1c5b302c-c0b1-44e9-ae61-1ba50a25ccc1">

Verify this with environments added on that particular DLP policy.

**Comment by PetarHr** [comment]
Hi @RahulBojji, 

The Select environments block has the correct count of environment - 15 in total, I see the last one we added and try to evaluate the impact on is the last value in that list. 

However I don't see the flows that I know will be affected by this policy change, in the output. I see the suspended flow from the same owner, however his other flows that use the Project Roadmap connector are not in the output in the List Flows step.

One question for my understanding - why is the analysis showing that apps & flows from the already added environments will be affected by the policy? My understanding is that the policy already has an effect on the environments & those apps & flows should follow it, without being marked as in violation.

**Comment by RahulBojji** [comment]
@PetarHr  

Please check if the flows are available for the connector using this filter. You can check this in the power platform admin center itself.

<img width="415" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/990545ab-8c1c-40e0-bdd8-98038e71a357">


<img width="844" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/699a4a14-8062-4ba0-8e06-d9267dacf103">

Open Power Platform Admin Center -> Click on APP Environment -> in the filter add those environments added in the policy 
then Click on Edit filters - > Add row -> Add the remaining filters as per the screenshot present in filter rows

Check if the apps are available. Similarly, do it for the flows and verify if the flows that are supposed to be impacted are present or not
<img width="398" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/e45a5b8b-5f36-4761-9668-1705b5f4f3b5">


While performing impact analysis we consider all the environments added to the policy irrespective of whether they are added as new or the old ones.

**Comment by RahulBojji** [comment]
@PetarHr If the flows are returned in the List flows action they should be considered. Can you find the iteration of the flow which are excluded from CSV, and check the output of below actions?

<img width="790" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/c177a002-7355-4323-ba02-2a280ec7701b">

Ideally for blocked connectors they should get added in the "Add flow to impacted flows" action.
