### ISSUE TITLE
[CoE Starter Kit - BUG] Date format not consistent in DCC

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#7808]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the Developer Compliance Center (DCC), can we have the date for "App Published" the same format as the dates above it please. This will avoid date/month mix up in non-US countries.
![image](https://github.com/microsoft/coe-starter-kit/assets/142497418/010cbafa-009f-4ddd-a792-485062d0c0c0)

### Expected Behavior

Consistent date formats and clarity of the date.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

DCC

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the DCC
Select an app

AB#2514

**Comment by Jenefer-Monroe** [comment]
Yep easy fix. Thanks for posting. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/77db8dea-3a57-4ceb-815a-d6787cb09952)
