### ISSUE TITLE
[CoE Starter Kit - BUG] Error to import CenterofExcellenceAuditComponents July 2021

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#781]
### Describe the issue

To import the solution CenterofExcellenceAuditComponents of July 2021 I have this error:
_The import solution must have a higher version than the existing solution it is upgrading._

Now I have installed the version: 1.61

### Expected Behavior

n/a

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.7.20210707.1

### What app or flow are you having the issue with?

Solution: CenterofExcellenceAuditComponents_1.7.20210707.1_managed.zip

### Steps To Reproduce

n/a

### Anything else?

![image](https://user-images.githubusercontent.com/57954993/124881913-290f6b00-dfd0-11eb-861c-bf5f204e9d89.png)

**Comment by manuelap-msft** [comment]
We're on it! Will let you know when we fixed that - we will have to run our release again.

**Comment by manuelap-msft** [comment]
With this release I learned: 61 is higher than 7  The new versions are now live: https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-July2021a

**Comment by albertocaa1317** [comment]
Hi @manuelap-msft,
after the new release I can import this solution correctly!
Thanks!.
