### ISSUE TITLE
[CoE Starter Kit - QUESTION] Manage Permissions App

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#7811]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi
This new app is great thank you for adding this.  Before this was released I had signed our test tenant up to a new preview feature https://learn.microsoft.com/en-us/power-platform/admin/manage-high-privileged-admin-roles#changes-to-feature-support

One of the know limitations is "The Microsoft Power Platform CoE Starter Kit no longer works and we're working on updating the kit"

Does this mean that if using the preview feature and a System Admin is added to an environment, this will not update in the CoE tables and the user will not show within the Manage Permissions app?

For managing system admins would it be better for me to remove my tenant from the preview feature and use the Manager Permissions app?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Manage Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2520

**Comment by Jenefer-Monroe** [comment]
Hello. Thanks for posting and asking about [this limitation](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles#known-limitations) for this preview feature:
[Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles): 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/552e5e9c-79c5-4791-b732-1820710dbffe)

The limitation is quite fundamental actually. 
In the past, as the identity running the inventory flows had the PPAdmin Role, it would get added as a Sys Admin of any new environments as they came in. 
This new PIM feature means that the user will no longer be added there, and so the inventory will not gather new environments. 

There are existing steps to [elevate the user](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles#self-elevate-to-the-system-administrator-role) and hence be added, but they are not in a form that the kit can consume yet. The product team is actively working to unblock us but we are not yet able to do this elevation for you. 

As a result, here are your options:
- implement this logic yourself to add the identity running the kit to new environments
- not have the new environments be in the inventory until the kit can be fixed up
- remove yourself from the preview temporarily until the kit can do the elevation for you. 

Hope that makes sense. Please do let me know if I've not yet answered your question.

**Comment by Alyson95170** [comment]
Thanks for the update Jenefer that does make sense.
