### ISSUE TITLE
[CoE Starter Kit - QUESTION] Storage History

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#7812]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello everything is fine?

Today needs have arisen,

The first is a history of the environments' capacity. I'm analyzing it and actually, in order to resolve this issue, I must create a capacity history table, because today we don't have anything like that, right?

History of components excluded by the orphan process (we have it due to the inactivity process). We also don't have a counter of how many components (flows and Canvas) were deleted, month by month, right?

Thank you in advance for all the attention the team gives

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

February

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2521

**Comment by ClaudioRWS** [comment]
@Jenefer-Monroe 

No problem,

My friend and I have this request, we are from different companies, so we are observing that companies that adopt CoE somehow want numbers after implementation

I'm going to create a model here, and share it with you, if you like the idea.

**Comment by Jenefer-Monroe** [comment]
Oh that would be wonderful! Thank you!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
