### ISSUE TITLE
[CoE Starter Kit - BUG] Incorrect Data in Maker Table

### ISSUE THREAD

**Issue by Chitusnair** [microsoft/coe-starter-kit#7813]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I recently implemented CoE Starter kit - February release in Test. I found that the Maker table shows users with 0 resources. When I cross checked, for one user and she is the owner of an Environment, but the 'No. of Environments' field shows count 0 for her.

In the Power Platform Admin View App, the environment is listed with 5 Apps (default that comes with developer plan). None of these are entered in the maker table. The Active Environment View lists the Environment as well as the 5 apps.
For another user, (different environment) who has a Flow to his account, also shows 'No.of Flows' as 0

The environments are only excused from 'Excuse from Empty environment clean up'  and 'Excuse from App Quarantine Flow' 

### Expected Behavior

The count of resources for all the Makers should be correct.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

All Makers view in Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. In CoE, go to Power Platform Admin View.
2. Go to Users (section) -> Makers
3. Select All Makers
4. Sort Number of Apps column by smallest to largest and find the users with No.of Apps as zero to have no entries on any other "No.of" columns.

AB#2523

**Comment by Jenefer-Monroe** [comment]
These fields are roll up fields and so for a new install they take a while to update. It’s typically a 12 hour wait after the inventory completes before you can expect to see these populate but the product itself is what determines how frequently and when to update these roll up fields.
You can force these to calculate. Please see the tip in this product team article on [Rollup columns](https://learn.microsoft.com/power-apps/developer/data-platform/calculated-rollup-attributes#rollup-columns)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d374b7dc-82e2-499d-8855-be81a70bdb98)
If its been a while since install and you still see zeros, it could be that the rollups broke or got deactivated somehow. Please [View Rollup Jobs](https://learn.microsoft.com/power-apps/maker/data-platform/define-rollup-fields#view-rollup-jobs) and see their state.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/50ca6f07-dc57-4188-8db6-47198478608b)

**Comment by Chitusnair** [comment]
I see that all Calculate Rollup Field jobs are succeeded. I filtered the status reason column with other statuses and there were no results.

Also to note that, I installed CoE on mid Feb and its been a while already. I see that only the Number of Apps column is displaying with the correct data. Was there a recent change on the roll up field conditions for other columns?

![image](https://github.com/microsoft/coe-starter-kit/assets/29492335/e1fd6bff-5482-40de-8c3e-a70e5dca28ae)

**Comment by Jenefer-Monroe** [comment]
No we did not change these fields. You can go make sure the formula is correct. Sometimes people change it. 
Go to tables outside of a solution, find the Maker Table, go to coumns, find this column and look at the formula

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/aa04dde8-0501-4485-aaec-6a48c80e0ae1)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f578ff89-0c7a-4337-991f-54a610ba0e62)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0952c430-4614-4b10-8842-a06b1e7f6c84)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1536eb88-3277-4f7b-b4c2-9c969c1c9019)

**Comment by Jenefer-Monroe** [comment]
I just looked through all my test envts and did find one that repro'd. 
I went to the rollup fields as described here: [View Rollup jobs](https://learn.microsoft.com/power-apps/maker/data-platform/define-rollup-fields#view-rollup-jobs)

Found the one that wasnt working for me (for me its admin_maker.admin_numberofflows)
I opened it by clicking the name, it shows as server busy broken
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/81cbcdb4-a3e4-4560-98f7-f7eef7f41957)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1ef4d2ce-ddc3-4d61-8d56-607aca710a80)

Where as ones that were working show no error
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/216da34a-891d-49fb-9e51-6ca47f955b7e)

I clicked resume
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c1cbbdd3-c02c-46bf-b4f7-eb9457a2b5b0)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8f38fc72-4fc1-48c2-a147-c681d3830494)

And then close. It did seem to fix. 
Can you try?

**Comment by Chitusnair** [comment]
Thanks so much. That seems to fix the issue. The Flow count and the environment count is populated now.

**Comment by Jenefer-Monroe** [comment]
YEAH! Wonderful! Thanks for letting me know. We both learned something today!
