### ISSUE TITLE
[CoE Starter Kit - BUG] Tried loading MPP CoE Setup and Upgrade Wizard, got no response from server error

### ISSUE THREAD

**Issue by tyanling1998** [microsoft/coe-starter-kit#7814]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

1. I have turned on the required flows. However, there is error shown when opening app - "SetupWizardGetCurrentEnvironment.Run failed: { "error": { "code": 504, "source": "singapore-001.azure-apihub.net", "clientRequestId": "dc029403-ee06-49bf-bc91-5c335832e8ce", "message": "BadGateway", "innerError": { "code": "UnexpectedError", "message": "An unexpected error occurred." } } }“. Upon checking, the flows completed the trigger step but could not move on to the next steps. 
 
2. Cannot pass ‘Run Setup Flow’ step even after refreshing and clicking on "Re-try running setup flows" multiple times.

### Expected Behavior

1. Flow should run and page should load properly. 

2. Several setup flows should be shown.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. In HT_UAT_CoE, go to Solutions.
2. Solutions > Center of Excellence - Core Components > Apps
3. Apps > CoE Setup and Upgrade Wizard > Right click on ... and click play
4. Page shows error. 
5. Able to click 'Next' even when there is error.
6. Until reach 'Run Setup Flow' page, cannot run this page. 

AB#2526

**Comment by tyanling1998** [comment]
Is this issue still open? I received an email saying the run was cancelled

**Comment by Jenefer-Monroe** [comment]
This usually means that the following flows which are supposed to be on when you install / upgrade are not on:

- SetupWizard>CreateGroup
- SetupWizard>GetCurrentEnvironment
- SetupWizard>GetTenantID
- SetupWizard>GetUserDetails

And that typically means that the **_HTTP with Microsoft Entra ID (preauthorized)_** connection was not configured correctly. 
Sometimes the product will setup one of these with the wrong URL

Please find this connector and validate its pointing to the graph URL for your tenant.

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d17f395e-d935-4e76-b62f-e6ce444897af)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/13cbb030-aa19-4e73-bf2b-cc4b0b692418)

**Comment by tyanling1998** [comment]
Hi Jenefer, thanks for getting back. 

For the network error, the 4 flows you mentioned above have been turned on in my environment. However, I noticed that the flows have been running for a few days but only passed the initial trigger step. The subsequent steps have not been reached yet even though it has and is still running for a few days. Could this be an issue in my power automate flow?

For the HTTP with Microsoft Entra ID (preauthorized), my URL is the same as the one you provided in the SS.

**Comment by Jenefer-Monroe** [comment]
Yes can you please share a screenshot with me showing where they are stuck?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
