### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Desktop flows) error after upgrade

### ISSUE THREAD

**Issue by santanuchokda** [microsoft/coe-starter-kit#7815]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Sync Template v4 (Desktop flows) fails after the recent upgrade to February 2024 release. 
Error - Action 'Parse_Inventory_-_New_RPAs' failed. The schema validation failed.

### Expected Behavior

There was no error before the upgrade.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Desktop flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Re-running the flow will fail it again.

AB#2528

**Comment by Jenefer-Monroe** [comment]
Can you please share the details of the schema validation? You can see this in the output of the failure.

**Comment by santanuchokda** [comment]
{
    "errors": [
        {
            "message": "Invalid type. Expected String but got Null.",
            "lineNumber": 0,
            "linePosition": 0,
            "path": "[0].RPA_Unique",
            "schemaId": "#/items/properties/RPA_Unique",
            "errorType": "type",
            "childErrors": []
        },
        {
            "message": "Invalid type. Expected String but got Null.",
            "lineNumber": 0,
            "linePosition": 0,
            "path": "[1].RPA_Unique",
            "schemaId": "#/items/properties/RPA_Unique",
            "errorType": "type",
            "childErrors": []
        },
       .
       .
       .
       .
       .
       .
       .
       .
    ]
}

**Comment by Jenefer-Monroe** [comment]
OK thank you. I believe you had some stale bad data in your table.  
Can you please go to the Desktop Flows table, filter to rows where that column does not contain data, and delete those records.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9c49a8ca-51c7-461c-ab14-c520eee0c126)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c33e43fa-8d3f-45d7-a902-f0cdd94c5a4a)

**Comment by santanuchokda** [comment]
ok thanks. There are about 60 records which does not contain data. Do I need to delete all?

**Comment by santanuchokda** [comment]
@Jenefer-Monroe - Infact it has only 60 rows, so if we delete them then the table will be empty.

**Comment by Jenefer-Monroe** [comment]
The old v3 version of the flow must have been writing them wrong for you. Please go ahead and do the delete. Next inventory will fill them. Them please let me know if you see the issue any longer.

**Comment by santanuchokda** [comment]
Ok thanks, I have removed all the rows. Let's wait for couple of days.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
