### ISSUE TITLE
[ALM Accelerator - QUESTION] Replace Tokens ADO Extension replacement

### ISSUE THREAD

**Issue by zellos13** [microsoft/coe-starter-kit#7816]
### What is your question?

Hello,

The "Replace Tokens" ADO Extension won't be allowed in our organization. Is there any other extension for Azure Pipelines that might replace this, and would ALM Accelerator still work?

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20240104.1(Managed)

AB#2529

**Comment by zellos13** [comment]
Hello @v-bjaiswal 

Is the any other extension that can replace this one?

**Comment by v-bjaiswal** [comment]
Hi @zellos13, unfortunately this is only ADO extension that allows token replacement as of now.
As an alternative you can consider writing custom PowerShell script here.

**Comment by v-bjaiswal** [comment]
closing this ticket. Please raise the new ticket if the issue persists or you have any other query. Thank you.
