### ISSUE TITLE
how do I view a list of "Inactivity Flow" COE

### ISSUE THREAD

**Issue by expn17ivany** [microsoft/coe-starter-kit#7817]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Support,

How do we view a list of "Inactivity flow" for all environments and also specify environment? The reason we asking because we need to turn on the inactivity flow for specify environment and we need to know how many flow is classify as "inactivity" before we turn on.

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

AB#2530

**Comment by Jenefer-Monroe** [comment]
We do not have such a forward looking view today but it is in the plans for when we rework this feature area. 
This write up has a quick video that might help you understand how to roll out slowly so that you can get a good handle on things before going broadly though.
https://learn.microsoft.com/power-platform/guidance/coe/governance-components#inactivity-processes

**Comment by LucX4** [comment]
You could write a flow using the same configuration of the Dataverse List Rows Step and adding a Compose action to check the total number of the components using the length function.
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/c4fd6649-9f11-4e1e-9c2a-12353a5f62da)

**Comment by expn17ivany** [comment]
thanks for replied. Can you help to answer: what attribute the coe flow use to identify the app/flow are inactive, so we can manually filter those attributes

**Comment by LucX4** [comment]
You can find the Dataverse steps in the following flows (they are part of the governance Solution):
**Admin | Inactivity notifications v2 (Start Approval for Apps) 
Admin | Inactivity notifications v2 (Start Approval for Flows)**

![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/833f2b96-7c8e-4cf5-a567-1e706182e8ab)
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/c3e7f00a-3d34-4d80-b153-6456ba74f25a)

**Comment by LucX4** [comment]
Just be aware that any changes made to these flows will add an unamanged layer. Remember to remove the layer before an upgrade.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
