### ISSUE TITLE
[CoE Starter Kit - BUG] Old Core Components still there after upgrade

### ISSUE THREAD

**Issue by Nomester** [microsoft/coe-starter-kit#7818]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After updating the new Center of Excellence - Core Components, the old one has not been removed and is still in the list of Solutions.

I'm updating from 4.17.

Should I just delete the old one?

### Expected Behavior

The old version should have been removed as part of the import of the new version

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Core Components

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

CoE Environment, import the new Core components.

AB#2531

**Comment by RahulBojji** [comment]
@Nomester 
Can you please share screenshot of the list of solutions you have installed in your environment just like below. Please make sure you are expanding the highlighted columns.

![image](https://github.com/microsoft/coe-starter-kit/assets/149372606/be40e140-c3ed-4cdc-9180-4224e9fbfbc8)

**Comment by Nomester** [comment]
Thanks for your help, I've done more investigation and it turns out we were having network issues and the uninstall barfed, I'm just running it again and it looks a bit more promising this time.

I'll get back to you if the uninstall doesn't work this time.

Many thanks,
Naomi
