### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Solutions) - Your flow is running too many actions (throttled or slowed down)

### ISSUE THREAD

**Issue by bhupendra14** [microsoft/coe-starter-kit#7819]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Just upgrade the CoE kit for March2024 and getting this throttled warning from the day one, not sure if it is because of the bug or config problem or bad loop. We cant have the platform being throttled because of a Bad flow.

Your flow is running too many actions
Your flow has used more than 80% of its Power Platform Requests (https://aka.ms/pa-ppr) limit in the past 24 hours. The performance is currently not impacted as it is below limits. But if the usage grows, further actions may be throttled or slowed down. Power Platform Requests used: 168243, Power Platform Requests transition limit: 200000.

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/7aac6bae-5a40-4cde-a700-38ea9de2c4c5)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Core 4.24

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/17860c25-51cf-4b15-87ca-aed75d06ba05)

AB#2532

**Comment by Jenefer-Monroe** [comment]
This is a little higher api hit flow that most of the inventory flows but I'm not seeing that level of impact. 
Can you please make sure the flow does not have unmanaged layers on it? We did remove a bunch of the processing from it for the March release into a lower frequency flow run.

**Comment by Jenefer-Monroe** [comment]
Oh nope looks like we forgot to remove it from this flow after our testing for the new flow. 
You can open this flow and remove this scope to local fix. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a7b570fc-0443-4dee-b23a-948c51f441f8)

This code has been moved to this flow which is now called weekly instead by **_CLEANUP - Admin | Sync Template v4 (Other Objects)_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f96d1914-f5a2-47d2-a409-bf128b529f82)

**Comment by bhupendra14** [comment]
Sure, Thanks for the update @Jenefer-Monroe .
