### ISSUE TITLE
[ALM Accelerator - BUG]: Branch Policy not being created after Commit

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#7822]
### Describe the issue

Hi Team,
After a Commit, the branch policy is not being automatically created and thus, the Validation pipeline is not getting triggered.
Could you please assist me in understanding why this is happening?
Thanks!

### Expected Behavior

A branch policy should be created automatically in the feature branch (Solution branch) after commiting.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

March 2024

### Anything else?

You can see that other Branchs have the branch policy:
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/2efa57d3-28cc-478b-a84d-f68fb4cb7994)

AB#2536

**Comment by v-bjaiswal** [comment]
Hi @LucX4 , 

The policy is currently being created/updated within the "export_solution_to_git" pipeline during the "Creating a new policy" step. Upon successful completion, it will provide you with the policy ID.

![pipeline](https://github.com/microsoft/coe-starter-kit/assets/102227309/f3a8997c-9e2c-4d80-8f3f-f394bdc51efa)

Please verify at your end whether this step was successful. Based on that, we can proceed further.

**Comment by LucX4** [comment]
Hi @v-bjaiswal,
Thanks for pointing me to the correct place. I'm getting an error:
"Error while creating new policy. Message - The remote server returned an error: (403) Forbidden."
I'm checking all the permissions for the user that attempted to deploy.

**Comment by v-bjaiswal** [comment]
Hi @LucX4 ,
403 means that the user does not have permission to access the requested resource. In this case, the pipeline user is trying to create a new policy in Azure DevOps but are not authorized to do so. Ask the user if they configured the permissions as specified [here](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-components-manually#set-permissions-for-the-project-build-service).

**Comment by LucX4** [comment]
Hi @v-bjaiswal,
It's all configured as described in the documentation. Just to confirm, is the pipeline user the person running the ALM Canvas App?

I was also checking this:
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/99338e6f-d362-4182-9f6d-80a6a6a141ec)
https://learn.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser#prerequisites
https://learn.microsoft.com/en-us/azure/devops/repos/git/set-git-repository-permissions?view=azure-devops

The user has the 'Edit Policies' permission inherited by the group membership.

Do you have any additional suggestion?

Thanks in advance!

**Comment by piyushpaliwal** [comment]
I am hitting the same issue here. Getting 403 forbidden while updating policies even though the necessary permissions are set for the build service account.

Is there any workaround we can try here?
Maybe downgrade to previous version?

**Comment by LucX4** [comment]
Dear @v-bjaiswal, hope you are doing well!
Do you have any additional comments?
Thank you!

**Comment by mikefactorial** [comment]
Hey all, have an update for this issue over here https://github.com/microsoft/coe-starter-kit/issues/7930#issuecomment-2024283993. Closing this one out as the dupe even though you all get credited for reporting it first :)
