### ISSUE TITLE
[CoE Starter Kit - QUESTION] Modify Power Apps Apps table

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#7823]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, can you recommend what is the best option if we want to customize a table? I have created custom columns and had no issues so far but now I would like to add more choices for the Power Apps Apps table to use in the compliance process. Would this be possible without creating an unmanaged layer in the kit?

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/b21b16cc-ba00-4539-b2d6-91c93c14466f)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

March 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2537

**Comment by RahulBojji** [comment]
@santiareh You can create your own unmanaged solutions and add new columns in that solution. Please have a look at [this](https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components#what-components-can-i-customize) for more information

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
