### ISSUE TITLE
[CoE Starter Kit - QUESTION] HELPER - CanvasAppOperations is off

### ISSUE THREAD

**Issue by KV-MY** [microsoft/coe-starter-kit#7824]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The coe flow **Request Orphaned Objects Reassigned (Child)** fail when trigger **HELPER - CanvasAppOperations**

{
  "error": {
    "code": "WorkflowTriggerIsNotEnabled",
    "message": "Could not execute workflow '56c29b5e-b139-96c6-f259-bdc3e89484da' trigger 'manual' with state 'Disabled': trigger is not enabled."
  }
}

![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/1e3120b8-da21-4ad5-956b-b0f1e1d39252)

Should i just turn on HELPER - CanvasAppOperations without any impact?
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/51fb1f73-4844-4b50-853c-8b1c6cacf974)

Also it appears we have two version of Core Components, should i turn on HELPER - CanvasAppOperations in both components?
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/92cf88e3-6630-41ab-9224-202d8c9b165c)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2538

**Comment by RahulBojji** [comment]
@KV-MY When upgrade fails the product often leaves an _Upgrade and an original solution sitting there.
These will never converge or repair on their own, you will need to take action to resolve.
You must first delete the _Upgrade before you can try to upgrade again.

**Comment by KV-MY** [comment]
Thanks for update, while waiting for this to fix, could we turn on the flow first? HELPER - CanvasAppOperations

**Comment by RahulBojji** [comment]
I suggest try to fix the issue first and then you turn it on otherwise you might encounter other issues as well.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
