### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Connection Identities)

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#7826]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, this is something that should be raised to Microsoft?

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/909f389d-023f-4e1e-b858-d79efac5132e)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Likely you just hit a raise condition where it was trying to do the same action twice. If you rerun the flow it should pass.

**Comment by BartoszKaminski1999** [comment]
Rerun pass, thanks
