### ISSUE TITLE
[ALM Accelerator - QUESTION] Replace Tokens' version 3 (replacetokens@3) is deprecated

### ISSUE THREAD

**Issue by goroy1** [microsoft/coe-starter-kit#7827]
### What is your question?

See the following warnings when we Deploy a solution to  Test/Prod, not sure if this is addressed in the new version or if we need to  do any settings changes in AzureDevOps.

All our pipelines use the October version 

Any help appreciated.

![image](https://github.com/microsoft/coe-starter-kit/assets/125452130/a08d5265-04e7-4e8b-bf73-dd31a42c3e99)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20231012.1

AB#2543

**Comment by v-bjaiswal** [comment]
Hi @goroy1, thank you for bringing this issue to our attention. Rest assured we will look into this and work towards resolving it as quickly as possible.
If you have any additional information or concerns regarding this, please feel free to post here or create new ticket.

**Comment by v-bjaiswal** [comment]
We have incorporated the changes into our developement. This will be availaible in the April release. Thank you.
