### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Connection Identities)

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#7828]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We noticed this error:

<img width="670" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/54030753/72a7f2b0-147c-4d03-ae35-839182ea12ac">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connection Identities)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2544

**Comment by Jenefer-Monroe** [comment]
Likely the same race condition. I suspect you have multiple instances of the flow running at the same time and so the two flows are fighting for records. 
A rerun should pass.

**Comment by BartoszKaminski1999** [comment]
Rerun pass, thanls
