### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Solutions)

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#7829]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We noticed few situations where there is attempt to add record to table that already exist:

<img width="676" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/54030753/47f27c21-b9a7-44e1-9f17-b64cab927460">

<img width="836" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/54030753/76309821-5330-47b6-9d42-26511d723d01">

<img width="946" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/54030753/508ee9e0-515f-45ab-999c-294b7b67dbc1">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2545

**Comment by Jenefer-Monroe** [comment]
Hello you have hit a lot of these. THis is a race condition where multiple flows are trying to do the same thing at once. We dont see this very often though. 
Can you please tell me:

- is this a new install of the kit? 
- do you have a fairly large tenant?
- if you go see the Driver flow, does it appear to have overlapping runs? Where its running multiple instances at once? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a92b3d06-8510-4bad-83cd-9691dc86b8ab)

**Comment by BartoszKaminski1999** [comment]
Hello,

We have 4.24 version

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/2675fc94-d181-4081-9b14-1fb314296d61)

We don't have overlapping runs

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/95440abc-a4be-4230-ac75-98ed2a90276d)

About tenant size

252 environments
1309 apps
689 flows
40 bots

**Comment by Jenefer-Monroe** [comment]
oh I see you had both the v3 and the v4 versions of the flow running. 
The intention was that you would use the v4's and we just kept the v3's in there for one release as a backup since we had made so many changes. 
So it makes sense that you may hit this error in that case. 
As of the new release the v3's are removed so this issue should not hit you again.

**Comment by BartoszKaminski1999** [comment]
We have only one driver flow (v4)

![image](https://github.com/microsoft/coe-starter-kit/assets/54030753/0a729d15-2e79-47a2-96b3-cf90b21a7c6f)

**Comment by Jenefer-Monroe** [comment]
correct but your screenshots show both v3 and v4 flows running for solutions.

**Comment by BartoszKaminski1999** [comment]
A yes you are right, thanks
