### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (PVA)

### ISSUE THREAD

**Issue by BartoszKaminski1999** [microsoft/coe-starter-kit#7830]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello we noticed attempt to add record that already exists

<img width="871" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/54030753/6d0fc0d5-afd6-4c04-932d-99c518f07831">
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v4 (PVA)

### What method are you using to get inventory and telemetry?

None

AB#2546

**Comment by Jenefer-Monroe** [comment]
Same race condition. Please rerun. I've asked another question in https://github.com/microsoft/coe-starter-kit/issues/7829

**Comment by BartoszKaminski1999** [comment]
Rerun pass, thanks
