### ISSUE TITLE
[CoE Starter Kit - BUG] Getting error while upgrading Core Component Solution

### ISSUE THREAD

**Issue by NemadeUjwal** [microsoft/coe-starter-kit#7831]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When updating solution I am getting below error 
Import failed: The column 'admin_makersubmittedrequirements' is dependent on column 'admin_requirement_2'. ALTER TABLE ALTER COLUMN admin_requirement_2 failed because one or more objects access this column.

### Expected Behavior

Solution should be updated

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponents_4.24_managed

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2547

**Comment by RahulBojji** [comment]
@NemadeUjwal Thanks for reaching out, we have seen a few people hit this and it was because they had customized one of the fields.
Please check https://github.com/microsoft/coe-starter-kit/issues/7419

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
