### ISSUE TITLE
[CoE Starter Kit - QUESTION] Linking Connection Reference table to Flows

### ISSUE THREAD

**Issue by WilliamJYoung** [microsoft/coe-starter-kit#7833]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I'm trying to identify all shared flows with the "Office 365 Outlook" connector. I'm struggling to link the "Connection References" table to the Flows. Is there a connecting table that I'm missing? Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2549

**Comment by Jenefer-Monroe** [comment]
In the Power Platform Admin View app you can go to Connectors and find your target connector then select its to open its form.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c0c847bd-8146-4c68-8563-c02bca19fcf6)

In there you will see tables for **_Used in - Apps_** and **_Used in - Flows_** and you can filter here by Envt and things like that.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/03663b39-acd5-4806-911c-5ba0b94b2d81)

Hope that helps!

**Comment by WilliamJYoung** [comment]
Thanks Jenefer
My query is how these are linked? I want to generate this list myself and subsequently identify which of the items have been shared. It's how the "Connection Reference" is connected to the Flow that I'm struggling with
![image](https://github.com/microsoft/coe-starter-kit/assets/15154437/726015db-4826-41e4-b1d7-0cafa7c79818)

**Comment by WilliamJYoung** [comment]
No problem. Thanks Jenefer. I think I can do it via the "Get Flow as Admin" action

**Comment by Jenefer-Monroe** [comment]
Yes thats how we find what connectors are used as well. But it wont tell you about individual connections to my knowledge. If you find a way around this please do let me know!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
