### ISSUE TITLE
[CoE Starter Kit - BUG] cross-tenant connections not being excluded from report

### ISSUE THREAD

**Issue by Service-WebDevPowerP** [microsoft/coe-starter-kit#7834]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have configured some additional domains in Admin_HostDomains but these are not being excluded from the Power Platform Compliance and Governance Power Bi report and are still showing as cross-tenant connections

### Expected Behavior

If a domain is listed in the Admin_HostDomains variabkle then these would be excluded from the Power bi report

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Power Platform Compliance and Governance Power Bi

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2550

**Comment by Jenefer-Monroe** [comment]
Hello we do not go back and update existing data when you change this setting. We do this to avoid the recurring API hit that would be required
Please see [How to update data to respect configured local tenants](https://github.com/microsoft/coe-starter-kit/issues/7164#issuecomment-1819498144) for how to do this.

**Comment by Service-WebDevPowerP** [comment]
Thanks for the info, I am in the process of updating
