### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Gather Tenant SRs fails with The number of array items in variable 'TenantSRs' reached the limit: maximum '100000' and actual '100000'.

### ISSUE THREAD

**Issue by martintoelk** [microsoft/coe-starter-kit#7838]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Admin | Gather Tenant SR adds all found SR into an array. For medium/ Large tenants this will to much to handle for the array and the Cloud Fails with

BadRequest. The number of array items in variable 'TenantSRs' reached the limit: maximum '100000' and actual '100000'.

![image](https://github.com/microsoft/coe-starter-kit/assets/24940711/730a5d53-f1bf-43b9-9deb-35ada2963a0c)

Additional Info: 
We have ~90 Environments. Some Environments are having a lot of Business Units and therefor a very big amount of Security Roles (Roles get multipled by each Business Unit)

Edit:
We also have a bunch of deprecated SR's that we did not /cant delete which makes the situation even more worse. The flow fails roughly after processing half of the Environments

### Expected Behavior

Flow does not fail

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Gather Tenant SRs

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Create a bunch of Environment + BU + Roles until you have > 100.000 Array Entries

AB#2555

**Comment by Jenefer-Monroe** [comment]
Thanks for posting! I bet its all those BUs. Since they are dupes we can ignore them. Let me get you a filter to try.

**Comment by martintoelk** [comment]
Awesome! It worked and it very fast. The old version did for 2 hours, before it crashed.

![image](https://github.com/microsoft/coe-starter-kit/assets/24940711/7fcc13d2-2a89-42ff-b1dc-aa2e32c358fb)


![image](https://github.com/microsoft/coe-starter-kit/assets/24940711/e8895164-4535-497a-9ed8-080c1fb8052a)

https://github.com/microsoft/coe-starter-kit/issues/7838

**Comment by Jenefer-Monroe** [comment]
Huzzah! Thank you so much for testing for me! 
Ready for April.
