### ISSUE TITLE
[CoE Starter Kit - BUG] PowerBI CDSLegacy July 2021 defects

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/coe-starter-kit#784]
### Describe the issue

1. In General, the most makers of flows or chatbots are SYSTEM.

2. In "Cloud flows", the chart "Top 10 Active Departments" doesn't correct information. In fact, it shows the same information that the same chart in "apps" section.

3. In "Cloud flows", the selector to filter "Connector" has this error: "There was an error with one or more fields:  (Flow Connection Reference) admin_displayname.

### Expected Behavior

n/a

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

Power BI: CDSLegacy_CoEDashboard_202107.pbit

### Anything else?

1.
PowerBI Report June2021:
![image](https://user-images.githubusercontent.com/57954993/124892784-7690d580-dfda-11eb-86c9-7bdfaf3414da.png)
PowerBI Report July2021:
![image](https://user-images.githubusercontent.com/57954993/124892940-988a5800-dfda-11eb-9c35-7d5bf23abfb5.png)

2.
PowerBI Report June2021:
![image](https://user-images.githubusercontent.com/57954993/124893084-b8ba1700-dfda-11eb-8698-2ec05ab047a8.png)
PowerBI Report July2021:
![image](https://user-images.githubusercontent.com/57954993/124893400-fd45b280-dfda-11eb-9e19-fb77b7629311.png)

3. 
![image](https://user-images.githubusercontent.com/57954993/124893257-dc7d5d00-dfda-11eb-9d68-39508e905251.png)

**Comment by HamishSheild** [comment]
I have the same issue.  Looks like a field has been renamed and it should be using **admin_connectordisplayname** instead of admin_displayname

![image](https://user-images.githubusercontent.com/41050216/125174996-6ddc1180-e21d-11eb-805c-ed4010eafbe0.png)

**Comment by albertocaa1317** [comment]
Hi @manuelap-msft ,
one question about the tag "vNext". It means that will be fixed in the next release or asap?
Thanks.

**Comment by manuelap-msft** [comment]
Hello,

fixed this issue and the new version of the Dashboard is now available either via the main download aka.ms/coestarterkitdownload or directly here: https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/CDSLegacy_CoEDashboard_202107_v2.pbit

Thank you
Manuela
