### ISSUE TITLE
[CoE Starter Kit - BUG] Manage Permissions App -- too many rows to count causes failure to load

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7841]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Error when trying to retrieve data from the network

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/6233b977-5ce5-432c-8c77-9b5e6877790b)

### Expected Behavior

App should run

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Manage Permissions App

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Open App
App Shows Empty

AB#2558

**Comment by Jenefer-Monroe** [comment]
What state are you in here? Have you run the setup wizard already in this envt?
I dont think you are seeng that due to an empty table.

**Comment by Jenefer-Monroe** [comment]
Here's the table it reads from I presume it already has data as its not a new table: 'Environment Security Role Permissions'

**Comment by nasilvae** [comment]
Its on my test tenant. I ran it on both environments and I am able to repro on both. One has the data export another has the cloud flow version. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/165c9587-1b1d-44ff-98f2-f98166b50537)

**Comment by Jenefer-Monroe** [comment]
I don’t repro so not sure how you got this
Can you open in edit mode and see where it’s failing?

**Comment by nasilvae** [comment]
> I don’t repro so not sure how you got this Can you open in edit mode and see where it’s failing?

I found the issue. If I filter the table then I don't get the error. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/e887f7e8-5b21-47af-bf40-5a285be57b55).

I suspect that it has to do with how many items can be displayed at one time in the power app. I have over 60k records on this table that should be shown all at the time in the app. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/3148d76d-b2f1-46cf-84c4-93517077b3f8)

We need a way to paginate the information for large tenants.

**Comment by Jenefer-Monroe** [comment]
Count rows should be delegatable so I dont think thats it. What filter did you use? Maybe there is some malformed data?

**Comment by Jenefer-Monroe** [comment]
I'm trying an upgrade from Feb to see if its something you experience before inventory cleans up / adds new stuff to the table.

**Comment by nasilvae** [comment]
> I'm trying an upgrade from Feb to see if its something you experience before inventory cleans up / adds new stuff to the table.

Gotcha, so far on my side the following filters work
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/5f50e0d6-fa91-4f0f-a16b-925facf66af2)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/74bb4023-447f-4a39-a16a-1121c60204ce)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/ec69c67b-a56d-4c11-a17d-c1c0c6e8d787)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/c0374502-a04a-4859-81f0-4b3e26118154)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/22079848-556d-40e1-8d79-33e96e1226b2)

If I filter to All then I get 4 error messages 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/3f0019c7-02e5-4534-8550-3eff0e6d2374)

**Comment by Jenefer-Monroe** [comment]
Upgrade theory failed. 

Can you go to the developer tools (in edge browse settings >  more tools > developer tools) and then find the network tab
Filter to Guest, wait till it resolves, and then filter back to All
Do you see an error in the network trace?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1b4c842d-d23e-4db9-b951-22594663e50f)

**Comment by AUTigers16** [comment]
I am experiencing the same issue. However, I cannot filter the list to be able to get data to appear like the person reporting the bug. It was working fine before I ran this flow, Admin | Gather Tenant SRs, which I think pulls in all permissions in our tenant besides the Security Administrator role.  Since I still can't post images here, I will email them to you and reference the bug. I edited the app and grabbed screenshots of where I was getting errors.

**Comment by Jenefer-Monroe** [comment]
thanks guys. Looks like count isnt delegating after all and is failing for you. I can put some fake data in to see if I can repro

**Comment by Jenefer-Monroe** [comment]
Well thats an error I didnt know existed
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/49ec3a29-dcfb-4969-ac3e-4d06a1cb0afd)

**Comment by Jenefer-Monroe** [comment]
Looks like CountRows isnt delegating after all. Which it is supposed to be supported for Dataverse. But let me try to find a workaround.

**Comment by Jenefer-Monroe** [comment]
looks like there isnt a solution to getting count for tables this big without using middleware. 
But its just for the pagination number so here is what you will see for your large cases now:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/671d187e-f3ce-44a3-a03c-ec1064843309)

**Comment by nasilvae** [comment]
> looks like there isnt a solution to getting count for tables this big without using middleware. But its just for the pagination number so here is what you will see for your large cases now: ![image](https://private-user-images.githubusercontent.com/89584709/315326033-671d187e-f3ce-44a3-a03c-ec1064843309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzE2NjEsIm5iZiI6MTcxMTAzMTM2MSwicGF0aCI6Ii84OTU4NDcwOS8zMTUzMjYwMzMtNjcxZDE4N2UtZjNjZS00NGEzLWEwM2MtZWMxMDY0ODQzMzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0MjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MGYyMDMyMmI5YTU5MzM4MTMxNjkxMGY4ODhmMzVhNDA0N2U1N2I4ZWQzMjg3MTIyYTI2ODJiZTM0NzcxZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zo5qSECt3nAI125aEZ524Nw3jCBhTjl8rdua_n95t6g)

This is good thank you. We can load the list but not get counts I believe is fine.
