### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE Admin | Sync Template v4 (PVA) Error

### ISSUE THREAD

**Issue by Fadel1949** [microsoft/coe-starter-kit#7842]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow of Admin | Sync Template v4 (PVA) fails every day.

It is a Step Action to Upsert PVA Component Flow (no bot).

{
"error": {
"code": "0x80060888",
"message": "The supplied reference link -- admin_pvacomponents() -- is invalid. Expecting a reference link of the form /entityset(key)."
}
}
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/a052b7e6-4c0b-4dc6-93cc-fcea25e280d7)

### Expected Behavior

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/380a66d7-1f89-47cc-9642-77973c2b0b88)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (PVA)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2559

**Comment by Jenefer-Monroe** [comment]
Can you go up in the flow and look at what is in the output of this action? 
All records returned should have FlowID, ComponentID, and ID. 
Do any have one or more of those missing? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/445dfb20-b51c-45e3-bae4-1201881a21f8)

**Comment by Fadel1949** [comment]
I checked, there are:
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/9b0cbd9b-8d9b-4e47-9394-be5a94be90bf)

I looked into all 'Apply to each' loops. There are 9 total, with 8 failures and 1 pass. The passing condition is: 'If flow found, put component flow inventory = false'.

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/1b1b3c89-02f1-41c0-ab1c-c4574c6721ad)

**Comment by Fadel1949** [comment]
I checked, and there's this part where there's no value, which it's not taking from the value above. 
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/5583300e-1871-412d-bcb4-3530df0ab287)

Instead, it's taking it from this 'Compose' value.
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/5e272772-d3bb-4c77-91c4-2490d2c1374a)

**Comment by Jenefer-Monroe** [comment]
I think thats correct to refer to that compose as that shows the ComponentID. 
However I think the Bot Component existing without the Bot is a transitory thing before a cleanup routine happens. 
So here instead I should just not be adding anything as the bot is deleted.

**Comment by Jenefer-Monroe** [comment]
Thanks for helping me debug. Will fix up for April release.
