### ISSUE TITLE
How to export the data from dynamic 365?

### ISSUE THREAD

**Issue by expn17ivany** [microsoft/coe-starter-kit#7844]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Support,

We have make some filter to get the data from dynamics 365. However, we have no idea how the data can be exported to excel sheet. Would you able to advice how to export the data from dynamics 365?

Attached is the data collection.
![dynamics 365 data](https://github.com/microsoft/coe-starter-kit/assets/158439768/8f6bf20e-e494-4bc9-9dff-1825e8c8af69)

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

AB#2562

**Comment by RahulBojji** [comment]
@expn17ivany Another way exporting data via excel is Go to Power Platform Admin View -> Power Apps Apps - > Add the columns you want by clicking on edit columns -> Click on Export to Excel

<img width="808" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/a76d6700-e375-41c8-b2d0-94f213bc3f86">

You can add filters by clicking on Edit filters

**Comment by expn17ivany** [comment]
Thanks, but I don’t see there is a “last launch on” filter available? Do you know what is the filter to replace this?



Thanks.

Regards
Ivan
***@***.***

From: RahulBojji ***@***.***>
Sent: Thursday, March 14, 2024 4:11 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Yap, Ivan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] How to export the data from dynamic 365? (Issue #7844)

@expn17ivany Another way exporting data via excel is Go to Power Platform Admin View -> Power Apps Apps - > Add the columns you want by clicking on edit columns -> Click on Export to Excel image. png (view on web) You can add filters


@expn17ivany<https://urldefense.com/v3/__https:/github.com/expn17ivany__;!!MfzFaTml5A!jkQ-6mdEiCUyy1XBnTDZ3Ra7248Pe021pNOFjnSarfQuM8UsxtljvIi2vEl3ZuC9DFLHEF8ddinE7U2nMLuzsxdkrg$> Another way exporting data via excel is Go to Power Platform Admin View -> Power Apps Apps - > Add the columns you want by clicking on edit columns -> Click on Export to Excel
image.png (view on web)<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/assets/149372606/a76d6700-e375-41c8-b2d0-94f213bc3f86__;!!MfzFaTml5A!jkQ-6mdEiCUyy1XBnTDZ3Ra7248Pe021pNOFjnSarfQuM8UsxtljvIi2vEl3ZuC9DFLHEF8ddinE7U2nMLvcxMf0BA$>

You can add filters by clicking on Edit filters

**Comment by RahulBojji** [comment]
Use "App Last Launched on" if you are looking for app last launched date as a filter

<img width="953" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/b4e26f9d-4501-4f3b-84f1-711f7c6d8d4d">

**Comment by expn17ivany** [comment]
Hi, thank for the information. How about in Flow? is this call "flow last run on" in Power Platform Admin View -> flow - > Add the columns you want by clicking on edit columns

**Comment by RahulBojji** [comment]
There is a field with the same name in Flows table.

**Comment by Jenefer-Monroe** [comment]
Do note that this last run field is not filled for Flows unless you are using the Data Export architecture for gathering inventory.

**Comment by expn17ivany** [comment]
Hi Jenefer, could you please provide me more information and guide about using the data export architecture for gathering inventory?

**Comment by Jenefer-Monroe** [comment]
Hello, here is the [FAQ for the Data Export feature](https://learn.microsoft.com/power-platform/guidance/coe/faq-dataexport)

Please note this important caveat
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/52a30fcb-27ef-41d4-939a-f09e650cef97)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
