### ISSUE TITLE
[CoE Starter Kit - Feature]: Please Ignore the environments, Dynamics 365 organization you are attempting to access is currently disabled.

### ISSUE THREAD

**Issue by bhupendra14** [microsoft/coe-starter-kit#7845]
### Is your feature request related to a problem? Please describe.

Getting multiple flow failures because of Dynamics access is disable and we cant enable it because anything to do with Dynamics environments we don't touch in our platform, but its also worth mentioning to the CoE developers this error because they should probably ignore the environment ????

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/3a082c1a-50e2-470f-a0e9-6fb90aa14b2f)

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/4b5f388f-8ccd-4a1e-9d0b-efd2bddf4c93)

### Describe the solution you'd like

The Dynamics 365 organization you are attempting to access is currently disabled.  Please contact your system administrator.

AB#2563

**Comment by Jenefer-Monroe** [comment]
Looks like an accidental double post to https://github.com/microsoft/coe-starter-kit/issues/7846. Closing out.
