### ISSUE TITLE
[CoE Starter Kit - BUG] Ignore environments with Disabled Runtime State from inventory flows

### ISSUE THREAD

**Issue by bhupendra14** [microsoft/coe-starter-kit#7846]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting multiple flow failures because of Dynamics access is disable and we cant enable it because anything to do with Dynamics environments we don't touch in our platform, but its also worth mentioning to the CoE developers this error because they should probably ignore the environment ????

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/3a082c1a-50e2-470f-a0e9-6fb90aa14b2f)

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/4b5f388f-8ccd-4a1e-9d0b-efd2bddf4c93)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

The Dynamics 365 organization you are attempting to access is currently disabled.  Please contact your system administrator.

AB#2564

**Comment by Jenefer-Monroe** [comment]
Can you please go to the product's admin pages > environments > find one of the environments that is failing here and click to open it > Details > See All
What does it show for the Type, Administration Mode, and State?
https://admin.powerplatform.microsoft.com/environments
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e6e1e6e4-df55-43ad-afb7-f3ed1b3a2316)

**Comment by bhupendra14** [comment]
Hi @Jenefer-Monroe , sure. Please see the details below.

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/73c180fe-c07d-4fe8-83a3-b69c4dd79ef0)

**Comment by Jenefer-Monroe** [comment]
sorry I dont mean for your CoE environment, I mean for the envt that is failing here. 
You can look in the trigger and it will show you what envt it is
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9f70ba2a-cc61-4123-8fc2-f51c304cb948)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/422b2772-824f-459f-b6ab-186262392a4b)

**Comment by bhupendra14** [comment]
Yeah, it for the same environment which I shared above.

**Comment by Jenefer-Monroe** [comment]
Can you open this to see which action is failing? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/de861aad-58af-4c50-a2a7-8fec8b222305)

**Comment by bhupendra14** [comment]
Sorry @Jenefer-Monroe , it's my bad, actually it's failing for different environment which is Disabled. I missed it.

But can we just ignore the environment name from the flow to avoid this error.

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/3ab87c06-5f05-4b74-80b7-a26614ce1daa)

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/455500f5-0a74-4845-8c74-a0760d6dae76)

**Comment by Jenefer-Monroe** [comment]
I'm not sure what you mean by envt name. In order for me to help fix in the kit I will need to be able to find a way to identify this generally.
Can you please share, are you able to see these properties for this envt still? That will help me know how to map the properties.
https://admin.powerplatform.microsoft.com/environments
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e6e1e6e4-df55-43ad-afb7-f3ed1b3a2316)

**Comment by bhupendra14** [comment]
So if you can ignore this type of inactive environments in the flow so it won't fail and give us so much error messages. 😒

**Comment by Jenefer-Monroe** [comment]
Can you find the environment in the inventory (via the Power Platform Admin View app) and see what properties it has for these fields? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/37549ce3-e799-4072-a095-6934518fad91)

**Comment by bhupendra14** [comment]
sure, please check this

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/4184ba93-87a4-480b-8228-b3c54b22fcdd)

**Comment by bhupendra14** [comment]
sure @Jenefer-Monroe , please check this

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/44512637-7af9-44b7-b750-1a97f267561e)

**Comment by Jenefer-Monroe** [comment]
How about Environment Runtime State?

**Comment by bhupendra14** [comment]
it's disable

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/0b9f58d3-59b3-4256-8386-7a36736224f5)

**Comment by Jenefer-Monroe** [comment]
ok great. We can use this as our flag to ignore then. 
Thanks for helping me debug. Easy fix for April.

**Comment by Jenefer-Monroe** [comment]
Can you please tell me, does it fail for these flows too? I'm wondering if its just the ones we use the dataverse connector for that need fixed up: 

- Admin | Sync Template v4 (Flows)
- Admin | Sync Template v4 (Apps)

**Comment by bhupendra14** [comment]
Thanks for the help.

No it's working absolutely fine for above both. 😊

**Comment by Jenefer-Monroe** [comment]
Most were as simple as adding this to the early exit condition: 
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0139c647-03c3-45f6-92f1-329210518135)

These two will need a little something more. 
Admin | Sync Template v4 (Desktop Flow - Runs)
Admin | Sync Template v4 (PVA Usage)

**Comment by Jenefer-Monroe** [comment]
Can you please try these two for me?

### Admin | Sync Template v4 (Desktop Flow - Runs)
Put this:

`admin_environmentdeleted eq false and admin_excusefrominventory eq false and admin_environmentruntimestate ne 'Disabled'`

Here:
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8afccf71-f39f-47c7-88b1-064ba3d7f0dc)




### Admin | Sync Template v4 (PVA Usage)
Put this:
`admin_pvadeleted eq false and _admin_pvaenvironment_value ne null and admin_PVAEnvironment/admin_environmentdeleted ne true and admin_PVAEnvironment/admin_environmentruntimestate ne 'Disabled'`

Here:


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/30d746ec-8ece-406c-ba9c-0c6db4196db7)

**Comment by bhupendra14** [comment]
Hi, unfortunately I do not currently have a trial instance, and I am unable to test it in production. I apologize, I wish I could have been of more assistance. 😐

**Comment by Jenefer-Monroe** [comment]
No problem. I feel pretty confident there.
Here is another flow I missed though:
This filter: 
`@and(not(equals(item()?['properties/states/runtime/id'], 'Disabled')), not(equals(item()?['properties/linkedEnvironmentMetadata/instanceUrl'], null)))`

Here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/49bba9ee-54fb-4d50-9c8a-3e557cef5e3a)

**Comment by bhupendra14** [comment]
Thanks @Jenefer-Monroe for the help and quick support. 😊

**Comment by lr-arbin99** [comment]
@Jenefer-Monroe Really sorry to comment on an old item and I'm probably missing something, but this stops the flows running unless the Environment is in 'Admin Mode'.
https://learn.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/set-adminpowerappenvironmentruntimestate?view=pa-ps-latest
But wouldn't 'Admin Mode' block non Admins from signing into the environment? The flows aren't gathering data as our Environments aren't in Admin Mode.
Thanks
