### ISSUE TITLE
[CoE Starter Kit - BUG] Help uninstalling Core from Default.

### ISSUE THREAD

**Issue by HHSowmya** [microsoft/coe-starter-kit#7847]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

2 starter kit has been imported.
Not able to delete starter kit (Solutions).
Kindly help on this.

### Expected Behavior

Not able to delete starter kit.
Delete button is disabled for apps/flows/tables etc..

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.4 and 1.0

### What app or flow are you having the issue with?

All

### What method are you using to get inventory and telemetry?

None

AB#2565

**Comment by Jenefer-Monroe** [comment]
Hello can you please share a screenshot so we can better understand what you are describing? I think you are saying you have Core installed twice in one envt but I'm not sure. 

If that is what you are saying please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

Note that you need to be logged in to GitHub to share screenshots. Responding in email does not share images with us.

**Comment by HHSowmya** [comment]
Hi Team,

Please find the below screenshots while deleting the solution.

***@***.***

***@***.***
***@***.***

***@***.***



Thank You,
Sowmya H K

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately screenshots do not come through if you respond in email. You will need to log in to GitHub to share it with us.

**Comment by HHSowmya** [comment]
Please find the 
![1](https://github.com/microsoft/coe-starter-kit/assets/163411904/97f9e959-2a90-4815-b1d4-e7f6a3ecd8af)
![2](https://github.com/microsoft/coe-starter-kit/assets/163411904/99b35fe5-272b-43c3-9031-c03e220eab86)
![3](https://github.com/microsoft/coe-starter-kit/assets/163411904/fdd7fc87-cbb3-44ed-aced-15d46f14a512)
![4](https://github.com/microsoft/coe-starter-kit/assets/163411904/04b1a0c7-8f13-4083-884e-b51aaae9e250)
screenshots

**Comment by HHSowmya** [comment]
Hi Jenefer,

I have added the screenshots.

Thank You,
Sowmya H K

**Comment by HHSowmya** [comment]
Hi Jenefer,

Can we have a call on this so that I can show you all the solutions.
I will be available from 9 AM to 4:30 PM IST.

Thank You,
Sowmya H K

**Comment by HHSowmya** [comment]
Can you please take it on priority

**Comment by Jenefer-Monroe** [comment]
Hello sorry we are a very small team and not staffed to take calls with our GitHub users. 
Without knowing what is installed the envt I can't help with dependencies. So please share the requested screenshot if you would still like our help in getting unblocked.

**Comment by HHSowmya** [comment]
Hi Jenefer,

Please find the below screenshots.

2 starter kits has been installed and it is not used anywhere. We need these 2 kits removed from back end.
Need to remove all tables ,apps, flows etc.. associated with it.

Regards,
Sowmya H K

**Comment by HHSowmya** [comment]
Hi Jenefer,

Please find the below screenshots.

2 starter kits has been installed and it is not used anywhere. We need these 2 kits removed from back end.
Need to remove all tables ,apps, flows etc.. associated with it.

Regards,
Sowmya H K
![starterkit1](https://github.com/microsoft/coe-starter-kit/assets/163411904/df12117b-d4ce-464f-ba7c-11625f9f595a)
![Uploading starterkit2.png…]()

**Comment by HHSowmya** [comment]
![Uploading starterkit1.png…]()

**Comment by Jenefer-Monroe** [comment]
sorry one of your pictures did not come through. 
Again if you would like me to assist here I need to see all the rows so please remove the filter and show me all solutions in the envt


![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/74f497a2-8a61-473d-ae8c-c78c44fc0af6)

**Comment by HHSowmya** [comment]
Hi Jenefer,

Please find the below screenshots.

2 starter kits has been installed and it is not used anywhere. We need these 2 kits removed from back end.
Need to remove all tables ,apps, flows etc.. associated with it.

Screenshot (to be deleted) highlighted solutions need to be deleted.
![1](https://github.com/microsoft/coe-starter-kit/assets/163411904/cdb61375-7180-44af-886c-50ec99483978)
![2](https://github.com/microsoft/coe-starter-kit/assets/163411904/06e82d95-e332-4119-b959-28e7e581424a)
![5](https://github.com/microsoft/coe-starter-kit/assets/163411904/bcba403c-0cd2-4a7b-ac2f-dad074b56662)
![6](https://github.com/microsoft/coe-starter-kit/assets/163411904/b81dbcf1-9c23-4f1f-aa2e-30a5ebd11b74)
![7](https://github.com/microsoft/coe-starter-kit/assets/163411904/f3d70674-3f84-4bd1-97b6-fc1315b78452)
![8](https://github.com/microsoft/coe-starter-kit/assets/163411904/57250af0-03df-43ac-bca5-32d7ae41f12f)
![9](https://github.com/microsoft/coe-starter-kit/assets/163411904/6aa2a058-9d1d-4ed9-9880-c9b9b6ee448a)
![10](https://github.com/microsoft/coe-starter-kit/assets/163411904/c337d59d-c0db-4068-a4e3-6e24882c73f9)
![12](https://github.com/microsoft/coe-starter-kit/assets/163411904/096444a5-c2e1-4ca0-8286-cab4ac6c79c1)
![13](https://github.com/microsoft/coe-starter-kit/assets/163411904/7829a4e3-c4ea-4b3a-bfaa-2e98909f8379)
![14](https://github.com/microsoft/coe-starter-kit/assets/163411904/e0b2245f-e00d-4e2a-8d72-d3279a9f0f91)
![15](https://github.com/microsoft/coe-starter-kit/assets/163411904/d562deb1-d5d7-4e82-9a9f-6b9d85d2abea)
![16](https://github.com/microsoft/coe-starter-kit/assets/163411904/e39e26b1-eb52-4f8f-b570-5ad9301170e9)
![17](https://github.com/microsoft/coe-starter-kit/assets/163411904/017930fa-b5d4-4a85-b978-509a08a0c78c)
![18](https://github.com/microsoft/coe-starter-kit/assets/163411904/c94cd82c-2746-4505-b577-ad94e5a358d7)
![19](https://github.com/microsoft/coe-starter-kit/assets/163411904/588c0b69-74cc-4c2e-9926-ee4b2428864d)
![20](https://github.com/microsoft/coe-starter-kit/assets/163411904/ceea1197-31b1-4474-92a9-8a1d5494f65e)
![21](https://github.com/microsoft/coe-starter-kit/assets/163411904/06fd56f2-6483-4b67-b7c9-45fa3619b5cd)
![To be deleted](https://github.com/microsoft/coe-starter-kit/assets/163411904/982cff7c-315d-42d4-8619-089e81766710)
![11](https://github.com/microsoft/coe-starter-kit/assets/163411904/c2b6ae4a-2a58-46dc-ba7e-95f0b168ddac)
![4](https://github.com/microsoft/coe-starter-kit/assets/163411904/ba01fbea-0246-4ea4-b0c3-50ce8df1c181)
![3](https://github.com/microsoft/coe-starter-kit/assets/163411904/600ac030-b69c-45a9-aafd-470402dc0498)


Regards,
Sowmya H K

**Comment by HHSowmya** [comment]
Kindly treat this on priority

**Comment by Jenefer-Monroe** [comment]
I see you've installed the kit into your Default envt,. And what do you see when you try to delete the solution as a whole? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9fb9b454-754a-4065-995d-22c1a32c3ebe)

**Comment by HHSowmya** [comment]
Yes. Installed in default environment.

I get below message while deleting it.



Failed deleting solution Creator Kit. Solution dependencies exist, cannot uninstall.

**Comment by HHSowmya** [comment]
Yes. Installed in default environment.

I get below message while deleting it.



Failed deleting solution Creator Kit. Solution dependencies exist, cannot uninstall.
![remove_option_disabled](https://github.com/microsoft/coe-starter-kit/assets/163411904/c00eb6f5-89b3-40c4-8f86-6ab6531489b8)
![dependencies](https://github.com/microsoft/coe-starter-kit/assets/163411904/31017e71-4345-46de-ab19-bbfcd1654f91)
![sol](https://github.com/microsoft/coe-starter-kit/assets/163411904/547d1b34-7df8-4984-bb2b-e840715d3023)

**Comment by Jenefer-Monroe** [comment]
You need to delete the Core components before you can delete creator kit

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9fb9b454-754a-4065-995d-22c1a32c3ebe)

**Comment by Jenefer-Monroe** [comment]
This is just a permissions issue then, not an issue with the kit. If you do not have permission to remove solutions in Default then you will not be able to. 
I believe the min SR is SYSTEM CUSTOMIZER but I'm not certain. Please go see what permissions you have in the Default envt. 

If you go to https://admin.powerplatform.microsoft.com/environments do you see the default envt listed? 
If so click into it > Settings > Users + Permissions > Users 
Find your user > click the name > See your permissions
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a264e277-a8c6-4387-adfd-a328d2e72301)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e7c0172a-75eb-4c69-90f6-22875ecc73d4)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0606d7b8-62cd-42b8-907b-f4768eb04ba8)

**Comment by HHSowmya** [comment]
I have admin rights.
I have permission to delete it but when I go inside solutions the remove option is disabled.

Can you please let me know if you can remove the whole solution from backend.

**Comment by Jenefer-Monroe** [comment]
You cannot delete objects from managed solutions. This is product behavior. 
Here is an article to get you started: https://learn.microsoft.com/power-apps/maker/data-platform/solutions-overview

I would recommend you delete the solution as a whole from the Default envt.

**Comment by Jenefer-Monroe** [comment]
I cannot delete the solution for you no, you will need to delete it yourself.

**Comment by HHSowmya** [comment]
I am not able to delete it that’s why I am asking your help. I already sent you the screenshots that I am getting while deleting the solution. Why the remove options are greyed out for the apps inside the solution?
Kindly help us here.

**Comment by Jenefer-Monroe** [comment]
Your screenshot is of trying to delete Creator Kit. 
As described above, you cannot delete Creator Kit until you delete Center of Excellence - Core Components. 

Above it sounds like the delete object is grayed out trying to delete objects *inside* Center of Excellence - Core Components but that is expected product behavior to not be able to delete objects inside a managed solution. 

Please try to delete the Center of Excellence - Core Components solution and share that screenshot.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9fb9b454-754a-4065-995d-22c1a32c3ebe)

**Comment by HHSowmya** [comment]
Attached the screenshot while deleting "Center of Excellence"
![error](https://github.com/microsoft/coe-starter-kit/assets/163411904/e0b4bfa2-8fce-46f6-9132-41546cfacd51)
 solution

**Comment by HHSowmya** [comment]
Attached the screenshot while deleting "Center of Excellence"

***@***.***

**Comment by Jenefer-Monroe** [comment]
It sounds like you may have succeeded at deleting some parts of the kit manually and now you're in a strange state. 
Can you Switch to classic and delete?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ef2b8d8e-9381-4412-b84c-628afa467434)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a9051fa7-2dc4-4682-b78d-c148568534c7)

**Comment by HHSowmya** [comment]
I took help from Microsoft team and tried deleting the kit in classic mode we faced the same problem.
They told us to raise ticket in GitHub and told us to get help from you.

We have a deadline to delete this.
We need to delete the associated apps on priority.

Kindly take this on priority.

Best Regards,
Sowmya H K

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by HHSowmya** [comment]
Kindly open this ticket as we couldn’t delete it.
