### ISSUE TITLE
[CoE Starter Kit - BUG] Dataflows not working properly - null users coming from Data Export

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7848]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

CoE BYODL Flows & CoE BYODL Makers Data flows are not working. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/c9faad70-9e68-4df2-98cd-1a0d1678596a)

This is due to a mashup error related to the admin_maker entity. 

### Expected Behavior

Dataflows should run. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

BYODL DataFlows Maker/Flow 

### What method are you using to get inventory and telemetry?

Data Export

### Anything else?

Reference: 
https://github.com/microsoft/coe-starter-kit/issues/7719

https://github.com/microsoft/coe-starter-kit/issues/7648

AB#2566

**Comment by Jenefer-Monroe** [comment]
Is this for the client we have in active email about? If so can we please schedule?

**Comment by nasilvae** [comment]
> Is this for the client we have in active email about? If so can we please schedule?

Yes. Will send a poll in a moment. Thank you again.

**Comment by Jenefer-Monroe** [comment]
Worked with another customer and found that there were null creators getting sent through from flow data export file. 
Here is a fix we are trying. Can you please try it and let me know if they still repro.

### CoE BYODL Flows
Replace the entire content of the script in **_Advanced editor_** for **_Flows_** query with the below
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/95367b94-8884-4514-9a46-2f9c10207146)

```
let
    Source = AzureStorage.DataLake(DatalakeURL & "/powerautomate/Flows"),
      #"Changed modified" = Table.TransformColumnTypes(Source, {{"Date modified", type date}}),
  // Filter to files that have been updated since the last Dataflow refresh OR all files if initial inventory
  #"Filter to recent" = Table.SelectRows( #"Changed modified", each [Date modified] >= (if List.IsEmpty(DataflowRefresh) then Date.From("1900-01-01") else Date.From(DataflowRefresh{0}))),
    excludehiddenfiles = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    excludezerolengthfiles = Table.SelectRows(excludehiddenfiles, each [Attributes]?[Size]? > 0),
  // Extract Environment GUID from File Name
  #"Extract Environment ID from File Name" = Table.TransformColumnTypes(Table.AddColumn(excludezerolengthfiles, "EnvironmentName", each if Text.Length([Name]) = 41 then Text.Range([Name], 0,36) else Text.Range(Text.AfterDelimiter([Name], "-", 0), 0, 36)), {{"EnvironmentName", type text}}),
  // Remove unnecessary columns from the folder system, like extension and folder path.
  #"Removed unneeded columns" = Table.RemoveColumns(#"Extract Environment ID from File Name", {"Folder Path", "Attributes", "Date created", "Date modified", "Date accessed", "Extension", "Name"}),
  // Inner join of flow table with environments table, only keep flows where the environment still exists. This filters out flows from deleted environments.
  #"Merge with environments" = Table.NestedJoin(#"Removed unneeded columns", {"EnvironmentName"}, admin_environments, {"admin_environmentid"}, "admin_environments", JoinKind.Inner),
  #"Expanded Environments" = Table.ExpandTableColumn(#"Merge with environments", "admin_environments", {"admin_environmentid", "admin_displayname"}, {"admin_environmentid", "admin_environmentdisplayname"}),
  // Transform the content from the json files in the storage account into tables
  #"Get content from json files" = Table.AddColumn(#"Expanded Environments", "Transform file", each #"Transform file (9)"([Content])),
  // Expand all the columns the json file in the storage account provides into individual columns, e.g. flow name, flow id, created by, created on...
  #"Expanded columns" = Table.ExpandTableColumn(#"Get content from json files", "Transform file", {"resourceId", "name", "environmentId", "lifecycleState", "events_created_timestamp", "events_created_principalId", "events_modified_timestamp", "workflowEntityId", "flowSuspensionReason", "templateName"}, {"flowId", "name", "environmentId", "lifecycleState", "createdOn", "createdBy", "lastModifiedOn", "workflowEntityId", "flowSuspensionReason", "templateName"}),
  #"Removed errors" = Table.RemoveRowsWithErrors(#"Expanded columns", {"flowId"}),
  #"Removed Content binary column" = Table.RemoveColumns(#"Removed errors", {"Content"}),
  #"Remove null creators" = Table.SelectRows(#"Removed Content binary column", each [createdBy] <> null),
  // Merge flows with maker to get more maker details, such as maker display name, department, is orphaned etc for furhter logic (is the flow orphaned)
  #"Merged with makers" = Table.NestedJoin(#"Remove null creators", {"createdBy"}, admin_makers, {"admin_makerid"}, "admin_makers", JoinKind.LeftOuter),
  #"Expanded maker table" = Table.ExpandTableColumn(#"Merged with makers", "admin_makers", {"admin_makerid", "admin_userprincipalname", "admin_makerisorphaned", "admin_department", "admin_displayname", "admin_country", "admin_company", "admin_city"}, {"admin_makerid", "admin_userprincipalname", "admin_makerisorphaned", "admin_department", "admin_displayname", "admin_country", "admin_company", "admin_city"}),
  // Add utcNow timestamp which we use to identify when the dataflow last updated/created a row
  #"Added QueriedOn" = Table.AddColumn(#"Expanded maker table", "QueriedOn", each DateTimeZone.UtcNow()),
  // Add yes/no text field to identify if the flow is owned by a maker that no longer exists in the org
  #"Add IsOrphan" = Table.AddColumn(#"Added QueriedOn", "IsOrphanText", each if [admin_makerisorphaned] = true then "Yes" else "No"),
  #"Merged queries" = Table.NestedJoin(#"Add IsOrphan", {"flowId"}, admin_flows, {"admin_flowid"}, "admin_flows", JoinKind.LeftOuter),
  #"Expanded admin_flows" = Table.ExpandTableColumn(#"Merged queries", "admin_flows", {"admin_derivedownerdisplayname", "admin_derivedownermakerid"}, {"admin_derivedownerdisplayname", "admin_derivedownermakerid"}),
  #"Inserted conditional column" = Table.AddColumn(#"Expanded admin_flows", "DerivedOwnerFinal", each if [admin_derivedownermakerid] = null then [admin_makerid] else [admin_derivedownermakerid]),
  #"Add flowIsPublished" = Table.TransformColumnTypes(Table.AddColumn(#"Inserted conditional column", "flowIsPublished", each true), {{"flowIsPublished", type logical}}) //to replace with logic once available
  ,
  #"Add isNotDeleted" = Table.TransformColumnTypes(Table.AddColumn(#"Add flowIsPublished", "markDeleted", each false), {{"markDeleted", type logical}}),
  #"Inserted conditional column 1" = Table.AddColumn(#"Add isNotDeleted", "markDeletedDate", each if [markDeleted] = false then null else [QueriedOn]),
  #"Changed column type" = Table.TransformColumnTypes(#"Inserted conditional column 1", {{"EnvironmentName", type text}, {"admin_environmentid", type text}, {"admin_environmentdisplayname", type text}, {"flowId", type text}, {"name", type text}, {"environmentId", type text}, {"lifecycleState", type text}, {"createdOn", type datetime}, {"createdBy", type text}, {"lastModifiedOn", type datetime}, {"admin_makerid", type text}, {"admin_userprincipalname", type text}, {"admin_makerisorphaned", type logical}, {"admin_department", type text}, {"admin_displayname", type text}, {"admin_country", type text}, {"admin_company", type text}, {"admin_city", type text}, {"QueriedOn", type datetimezone}, {"IsOrphanText", type text}, {"admin_derivedownerdisplayname", type text}, {"admin_derivedownermakerid", type text}, {"DerivedOwnerFinal", type text}, {"flowIsPublished", type logical}, {"markDeleted", type logical}, {"markDeletedDate", type datetimezone}})
in
    #"Changed column type"

```

### CoE BYODL Makers
Replace the entire content of the script in **_Advanced editor_** for **_Combined Makers_** query with the below
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/24a0bfa2-763f-4d10-bb95-e04869c0d51d)

```
let
  Source = Table.Combine({#"Environment Makers", #"App Makers", #"Flow Makers"}),
  #"Removed duplicates" = Table.Distinct(Source, {"createdBy"}),
  #"Remove nulls" = Table.SelectRows(#"Removed duplicates", each ([createdBy] <> null))
in
  #"Remove nulls"

```

**Comment by nasilvae** [comment]
Hey @Jenefer-Monroe, we noticed the following on the Makers Sync Cloud flow. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/504dcc91-8c17-4d24-a106-3adaa5340ae4)

Is this intentional? We suspect that this is not letting the dataflows do a full sync.

**Comment by nasilvae** [comment]
> Hello yes this is known please see #7790 Sorry I thought I had let you know about this in our email but it appears I did not.

gotcha no worries. I got confused I thought it was for the February release instead of march. Thank you again for the prompt support.

**Comment by Jenefer-Monroe** [comment]
My bad for shipping it :D

**Comment by Jenefer-Monroe** [comment]
Can you try something for me? I looked at the code a little more and I think this might be an issue of the refresh completions and the dataflows not running in the required order

1.	Confirm you only have “Next Refresh” for the Maker dataflow and not the others
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b510a94a-4570-4cbd-91c7-4cf3a5274467)
 
2.	Delete the Dataflow run history back a few weeks for all the Dataflows. You can do this in the Command Center
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8316fd00-6ade-4ab9-8381-6b158be58fa2)

3.	Manually refresh the Maker dataflow
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bd9fc3f6-de14-4286-b4ee-da4da376896b)

4.	Wait to see them run in order and if they pass.

Thank you so much!
Jenefer

**Comment by nasilvae** [comment]
> Can you try something for me? I looked at the code a little more and I think this might be an issue of the refresh completions and the dataflows not running in the required order
> 
> 1. Make the changes  above to Maker and Flow dataflows
> 2. Confirm you only have “Next Refresh” for the Maker dataflow and not the others
>    ![image](https://private-user-images.githubusercontent.com/89584709/313731697-b510a94a-4570-4cbd-91c7-4cf3a5274467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3Nzk3MzUsIm5iZiI6MTcxMDc3OTQzNSwicGF0aCI6Ii84OTU4NDcwOS8zMTM3MzE2OTctYjUxMGE5NGEtNDU3MC00Y2JkLTkxYzctNGNmM2E1Mjc0NDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE2MzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNGZkZWEyNGFkNjNlYTQ3YTkyNGI1MGQ0ZTE0Y2UwOWQxMTc3M2M3ODllNGJlYzAwZTc3M2ZlMjVkZjQzYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H6hvhqPAC5RoAT0X_KsWchk-GRuAb1T-F0Ur0xoQtfY)
> 3. Delete the Dataflow run history back a few weeks for all the Dataflows. You can do this in the Command Center
>    ![image](https://private-user-images.githubusercontent.com/89584709/313731738-8316fd00-6ade-4ab9-8381-6b158be58fa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3Nzk3MzUsIm5iZiI6MTcxMDc3OTQzNSwicGF0aCI6Ii84OTU4NDcwOS8zMTM3MzE3MzgtODMxNmZkMDAtNmFkZS00YWI5LTgzODEtNmIxNThiZTU4ZmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE2MzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNDhiZWFlM2NhNTk1MDhkMDUyMWQ2YzY2YTQyYzIwNTViY2M2NzM0ZmUwNWM4YmUyNjY2OTVkZGIxOTliZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.50s2-_H-MoC_0Z3x0bokNjCYwsFUK7_0ErJlTaPfTXI)
> 4. Manually refresh the Maker dataflow
>    ![image](https://private-user-images.githubusercontent.com/89584709/313731828-bd9fc3f6-de14-4286-b4ee-da4da376896b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3Nzk3MzUsIm5iZiI6MTcxMDc3OTQzNSwicGF0aCI6Ii84OTU4NDcwOS8zMTM3MzE4MjgtYmQ5ZmMzZjYtZGUxNC00Mjg2LWI0ZWUtZGE0ZGEzNzY4OTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE2MzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjlkMDA2MDE1M2Q0ZTIzOTQ4YjhhYzZiOGM3MjkyYmRkZjIzMTZhNWNjOGU5MTQyYmIyYWU0NTBlZTE0NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AoR3nkmpEagcE2jwkTYp4eA5y0E2QVePiyXS6c3OLGM)
> 5. Wait to see them run in order and if they pass.
> 
> Thank you so much! Jenefer

sounds like a plan. Will communicate with the team.

**Comment by Jenefer-Monroe** [comment]
The above with both the changes to Maker and Flow as well as the adjustment to be sure they run in order is working now for the other enormous org I'm working with so I'm hopeful.

**Comment by nasilvae** [comment]
> The above with both the changes to Maker and Flow as well as the adjustment to be sure they run in order is working now for the other enormous org I'm working with so I'm hopeful.

We just implemented the changes. Now we are waiting for the dataflows to refresh.

**Comment by nasilvae** [comment]
> > The above with both the changes to Maker and Flow as well as the adjustment to be sure they run in order is working now for the other enormous org I'm working with so I'm hopeful.
> 
> We just implemented the changes. Now we are waiting for the dataflows to refresh.

Dataflows are working as of now. However orphan app are not being tagged properly. We suspect because the orphaned flow is being throttled. https://github.com/microsoft/coe-starter-kit/issues/7889
