### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to complete data load on 4.24 CoE Power BI Dashboard

### ISSUE THREAD

**Issue by tripdes** [microsoft/coe-starter-kit#7849]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

As-per the titlewe have recently upgraded our Center of Excellence Toolkit from version 4.3 to 4.24. However, unfortunately we are seeing the following error when trying to perform the initial data load on the Power BI Dashboard Production_CoeDashboard_March2024:

![Screenshot 2024-03-14 090845](https://github.com/microsoft/coe-starter-kit/assets/1639769/6964bf90-7d17-483e-9b31-077cbb9e30dc)

I have checked and can confirm the following clean-up task is turned on and running:

![Screenshot 2024-03-14 114922](https://github.com/microsoft/coe-starter-kit/assets/1639769/97bfd534-74fd-486c-a92d-6d62001a952e)

### Expected Behavior

We should be able to successfully pull all data from the CoE into the report to then allow us to republish the dashboards.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2567

**Comment by Jenefer-Monroe** [comment]
Hello. Sounds from https://github.com/microsoft/coe-starter-kit/issues/7832 like you might be stuck in the old **_Teams_** version of the kit and so I dont think this will work. You'll need to uninstall core unfortunately and start from scratch.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
