### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to retrieve the components within the Solution?

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#7850]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hey Team,

I'm trying to figure out how to get the components belonging to a specific Solution using Power Automate. Is there a simple way to do this?

I'm basically looking for something similar to what we see on the Solutions page in the Admin View, where we can easily see the Apps and Flows associated with a selected Solution by navigating to Related > PowerApps Apps or Related > Flows.

Any help on this would be awesome!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024

### What app or flow are you having the issue with?

Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2568

**Comment by Jenefer-Monroe** [comment]
Hello. Its not very simple unfortunately. We use a table in each envt called solutioncomponents which is hidden and has some undocumented fields we use to find object types. 
Honestly we kind of force tested this until it returned what we wanted. 
You can play around though and see if you find something better / easier. If you do please let us know!
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3562f923-a77c-44b9-b9fa-67b4a703ede2)

You can find this in the **_CLEANUP HELPER - Solution Objects_** flow (note in Feb it was still part of the **_Admin | Sync Template v4 (Solutions)_** flow)

**Comment by LucX4** [comment]
Hey @Jenefer-Monroe, thanks a lot!
I started grabbing the values from this table and realized that the App ID matches with the value that we currently have in the PowerApps App Table. However, for Flows, we need to search the ID based on the Process Table because it doesn't match the one from the Flow Table.

**Comment by Jenefer-Monroe** [comment]
Yes its returning another flow guid, not the one we get from the connectors. We do store it in the inventory though as admin_workflowentityid

**Comment by LucX4** [comment]
Thank you so much!

**Comment by Jenefer-Monroe** [comment]
You bet! Enjoy the hunt!
