### ISSUE TITLE
Action 'Update_the_component' failed on Admin | Sync Template v4 (PVA)

### ISSUE THREAD

**Issue by rarroyo111** [microsoft/coe-starter-kit#7853]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

**Action 'Update_the_component' failed** on **Admin | Sync Template v4 (PVA)** because _Component Description_ column on **PVA Components** table has a max length of 1000 characters, but our descriptions are over 1600 characters.

### Expected Behavior

Max Characters be increased to at least 1800

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v4 (PVA)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2571

**Comment by RahulBojji** [comment]
Thanks for posting. We will check and fix this

**Comment by Jenefer-Monroe** [comment]
Thanks for reaching out. Easy fix and ready for the April release.
