### ISSUE TITLE
[CoE Starter Kit - Feature]: Expose SP detailed information in PBI (ex site name)

### ISSUE THREAD

**Issue by rarroyo111** [microsoft/coe-starter-kit#7854]
### Is your feature request related to a problem? Please describe.

I cannot identify the OneDrive or SharePoint site whose item is created or updated that is used as a source to trigger a flow.  I cannot evaluate whether makers are using best practices.   

### Describe the solution you'd like

In the Bi Report for Core Components, In the Connectors Deep Dive section, add a drill down or add a column to the _Show Data Point as a Table_ in the section _Connectors Used in Apps and Flow_ .  If the trigger is SharePoint:xxxxx then show the URL of the List or Library.

AB#2572

**Comment by Jenefer-Monroe** [comment]
Hello we are limited in knowledge about the SP usage here but for flows, we do know if SP is a referenced resource and if so we can get the site name if its not dynamically gathered. 
We do have this today in the Power Platform Admin View as a field. You can add the columns shown and filter to referencedResources_Services contains Sharepoint.,
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8a8e16e1-825d-42bb-856b-2d6705e396e6)

We can add as a backlog item to also have PBI reports but it will likely be a while before we can fund, so I wanted you to be able to see where to find the data yourself in the meantime.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
