### ISSUE TITLE
[CoE Starter Kit - BUG] environments created by SYSTEM are blank

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#7857]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
in a fresh CoESK installation environments like default appear with Environment Maker blank and orphaned

### Expected Behavior

Environment created by SYSTEM should show Environment Maker SYSTEM and not orphaned

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Install CoESK Core Components
Let the inventory flows run
have a look through the admin view at the environment without maker

### Anything else?

Possible solution
modify the Owner id 
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/78712e89-aec4-4e91-b285-c0e4dd55df08)
from
if(equals(items('Apply_to_each_Environment')?['properties/createdBy/id'], null), if(equals(items('Apply_to_each_Environment')?['properties/createdBy/type'], 'NotSpecified'), parameters('CoE System User ID (admin_CoESystemUserID)'), ''), items('Apply_to_each_Environment')?['properties/createdBy/id'])
to
if(equals(items('Apply_to_each_Environment')?['properties/createdBy/id'], null), 
    if(equals(items('Apply_to_each_Environment')?['properties/createdBy/type'], 'NotSpecified'), 
        parameters('CoE System User ID (admin_CoESystemUserID)'), 
        ''),
    if(equals(items('Apply_to_each_Environment')?['properties/createdBy/id'], 'SYSTEM'),
        variables('systemMaker'),
        items('Apply_to_each_Environment')?['properties/createdBy/id']
    )
)

AB#2575

**Comment by Jenefer-Monroe** [comment]
I think the issue is that you do not have the environment variable filled for SYSTEM user. 
If you use the Setup Wizard this is filled for you. Its highly recommended that you use the setup wizard as it will ensure such things get plugged on each upgrade.
However if you would like to fill manually you can do so by finding this SYSTEM user in the Maker table, grabbing its GUID and putting it into the env var manually:

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/99d6ee1e-1cb4-4804-95b8-adb6c379ca24)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a29d92b4-06b1-41c0-a6aa-d62147578e60)

**Comment by lukas-nC** [comment]
@Jenefer-Monroe 
I have had used the setup wizard and the env var is filled
Nevertheless, I got the described issue

**Comment by Jenefer-Monroe** [comment]
OOf yes it looks like they changed this back to sending SYSTEM and not null
Thanks for posting. Will investigate for April.

**Comment by Jenefer-Monroe** [comment]
ok here is the formula we will use for that compose statement: 
`if(equals(items('Apply_to_each_Environment')?['properties/createdBy/id'], null), if(equals(items('Apply_to_each_Environment')?['properties/createdBy/type'], 'NotSpecified'), parameters('CoE System User ID (admin_CoESystemUserID)'), ''), if(equals(items('Apply_to_each_Environment')?['properties/createdBy/id'], 'SYSTEM'), parameters('CoE System User ID (admin_CoESystemUserID)'), items('Apply_to_each_Environment')?['properties/createdBy/id']))`

I looked through other system owned type objects (ex MDAs) and think this only reprod for Envts but please do let me know if you see elsewhere.
