### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to Remove Direct Assignment in Manage Permission app

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/coe-starter-kit#7859]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In Manage SRs screen of 'Manage Permissions' app, while trying to remove direct assignment of user with SA role under 'Assigned Directly' tab, it throws this error message: 'HELPER-RemoveUserfromSecurityRole.Run failed: {"error":{"code":"0x80048d0b","message":"Failed to install the flow"}}'

I am in GCC instance and i have SA role through Group. 

![image](https://github.com/microsoft/coe-starter-kit/assets/3292092/6fa0e5c2-11fc-445f-9ae5-70287d14979a)

### Expected Behavior

The direct assignment role from the user is removed. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.2.4

### What app or flow are you having the issue with?

Manage Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Run Manage Permissions app
2. Under Manage SRs, switch to 'Assigned Directly' tab
3. Select user and click on 'Remove Direct Assignment' button 
4. You will get error message: 'HELPER-RemoveUserfromSecurityRole.Run failed: {"error":{"code":"0x80048d0b","message":"Failed to install the flow"}}'

![image](https://github.com/microsoft/coe-starter-kit/assets/3292092/5dbf8e75-0d77-4595-9504-f969a72aacfd)

AB#2578

**Comment by Jenefer-Monroe** [comment]
Hello it sounds like the flows did not get turned on. Did you use the Setup Wizard for your upgrade? If not, that is highly recommended for both clean installs and upgrades. It will ensure that new env vars get filled, new flows get turned on in the correct order, etc

You can manually turn it on the needed flows instead as well : HELPER - Remove User from Security Role

**Comment by sanjeev40084** [comment]
@Jenefer-Monroe looks like we haven't run the setup wizard after the solution import. We will run the setup wizard and give it a try again.

**Comment by sanjeev40084** [comment]
This is working now after we ran the setup wizard. 👍
