### ISSUE TITLE
[CoE Starter Kit - QUESTION] Usage of field in DLP Analysis

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#7861]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi!
I was wondering if the field "Trigger Delete Resource" on the "DLP Impact Analysis" Entity is currently being used to trigger any automation and what the purpose of it is.

Thanks.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2580

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, to area owner for investigation.

**Comment by RahulBojji** [comment]
@DominicMeznik Currently, it's not been used to trigger any automation and also currently we are not updating that field either
It does not have any dependencies either.

<img width="893" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/2d371947-408e-4466-be8c-2a7933108fc5">

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
