### ISSUE TITLE
"The identity must have access to an Office 365 mailbox that has the REST API enabled"

### ISSUE THREAD

**Issue by Mvcster** [microsoft/coe-starter-kit#7863]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The install docs at https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with say "The identity must have access to an Office 365 mailbox that has **the REST API enabled**"

Where, in the Mailbox settings, can I check that "the REST API is enabled". Is this content up to date? I can't see that setting in Exchange Online. Does this mean Graph API nowadays, for Exchange Oinline users?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2582

**Comment by Jenefer-Monroe** [comment]
I think the setting depends on which UX you look at. This UX I think is only present in the Exchange Admin page if I'm correct. We add this kind of stuff to make debugging failures easier but then makes it harder. 
Likely we should just simplify here and say the following:
The identity must have access to an Office 365 mailbox that meets all requirements to use the [Office 365 Outlook](https://learn.microsoft.com/en-us/connectors/office365/) connector.

**Comment by Mvcster** [comment]
Thank you Jenefer. That is a much more helpful explanation, and would resolve this issue for me.

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0614e99a-966a-455f-aaa3-42022aa73ffd)

**Comment by Mvcster** [comment]
Hi, just going back to Jenefer’s original comment on this where she said:

“Likely we should just simplify here and say the following:
The identity must have access to an Office 365 mailbox that meets all requirements to use the [Office 365 Outlook](https://learn.microsoft.com/en-us/connectors/office365/) connector.”

The key word is simplify. My expectation was that the whole 5th bullet point beginning “The identity must…” would be replaced by the text that Jenefer suggested, replacing any mention of the REST API. The resolution so far has just added an additional statement, it has not simplified. It still leaves scope for confusion about the REST API.

Please could you revert to Jenefer and verify whether her intention was for the whole 5th bullet point to be simplified so that it simply reads:

“The identity must have access to an Office 365 mailbox that meets all requirements to use the [Office 365 Outlook](https://learn.microsoft.com/en-us/connectors/office365/) connector.”

Thank you
