### ISSUE TITLE
[CoE Starter Kit - QUESTION] Orphaned Dataverse for Teams Environments

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#7864]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way to set a new owner to a Dataverse for Teams environment that has become orphaned?
The environment will not be picked up by https://learn.microsoft.com/en-us/power-platform/admin/inactive-teams-environment as there are other users creating flows and apps so the environment is not inactive.
I have looked in the admin centre and also the admin view app and cannot see a way to set a new owner.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2585

**Comment by Jenefer-Monroe** [comment]
Hello. Thank you for posting. This is not an uncommon request. 
We do not have a concept of an additional or derived owner for Environments We are hesitant to do so as it leads to eventual issues like we see with Flows today where once the product introduces this we will then have two versions of the truth. 

I suggest you please request an owner concept (seperate from creator) for environments from the product team itself. If you do not have direct access to the product team please consider using https://powerusers.microsoft.com

**Comment by Alyson95170** [comment]
Thanks for the update Jenefer
