### ISSUE TITLE
[CoE Starter Kit - QUESTION] How is the Environment Variable, admin_PowerPlatformUserGroupID, used if there are no process dependencies.

### ISSUE THREAD

**Issue by RA1449** [microsoft/coe-starter-kit#7865]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How is the Environment Variable, admin_PowerPlatformUserGroupID, used if there are no process dependencies.

![image](https://github.com/microsoft/coe-starter-kit/assets/56046272/783cf47b-2557-4c63-b502-59c824d82f47)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feb 2024

### What method are you using to get inventory and telemetry?

None

AB#2586

**Comment by Jenefer-Monroe** [comment]
It is not used today. There are plans to move people into this group from the Power Platform Users table but they have not been done yet.
