### ISSUE TITLE
[CoE Starter Kit - BUG] Innovation Backlog - Cannot submit with painpoint and ROI

### ISSUE THREAD

**Issue by ramonck** [microsoft/coe-starter-kit#7867]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

On the first save of the Innovation Backlog is not working if people save initially with Paintpoints and ROI, I have to ask the people to save without these items and then save afterwards with this information filled in.

The problem occurs because the item is created inside 
Innovation Backlog Workitem

without an item being created and filled in for the BacklogIdea column which reflects from the Table Innovation Backlog Idea.

### Expected Behavior

Save without issues on the first save all the information provided, not having the user have to come in a couple of times to complete the Innovation Backlog.

The user gets frustrated because he cannot see the idea a lot of times.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

No sure how I can see version of Innovation Backlog

### What app or flow are you having the issue with?

Innovation Backlog

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Go to Innovation Backlog, insert new idea with Painpoints and ROI on the first save.

AB#2588

**Comment by Jenefer-Monroe** [comment]
Hello, thanks for reporting this! We have a larger rework of the Innovation Backlog planned to update the UX to Fluent UI guidelines and using the Creator Kit (similar to the work we've done for other CoE kit apps recently), as well as refresh some of the functionality and usability of that app. 

This work is planned for the next few months, so we're likely unable to fix the bug you raised and instead will make sure this works in the new version. 

Thank you!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
