### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Capacity table is empty

### ISSUE THREAD

**Issue by blanghorst** [microsoft/coe-starter-kit#7868]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I recently installed v4.24 of the core components and then published the Power BI reports.  I noticed that the Environment Capacity tab of the report was empty in the Environment Capacity Overview and Top 10 Capacity tiles.  I reviewed Dataverse and while the Environment table seemed to be populated, the Environment Capacity table was empty.  Can you tell me the workflow or mechanism by which this table is populated so I may investigate further?  I also noticed that the Admin | Sync Template v3 (Environment Properties) flow is not in v4.24 but was in 4.17 but I'm assuming that's by design.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Unknown 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2589

**Comment by Jenefer-Monroe** [comment]
Hello. Please take a look at this article which describes the system. [Environment capacity management & alerting](https://learn.microsoft.com/power-platform/guidance/coe/capacity-alerting)

**Comment by nmarija** [comment]
@Jenefer-Monroe I did fresh installation of the CoE kit 4.24 and I'm facing the same issue. 
Furthermore, in the documentation it is specified to configure approved capacity in the environment details section. https://learn.microsoft.com/en-us/power-platform/guidance/coe/media/capacity-2.png

However In the environment details there is no section to set environment capacity
![image](https://github.com/microsoft/coe-starter-kit/assets/13290218/0643c8df-bbd6-4def-b533-65e5c2d881d6)

Same in the Capacity and Add-ons tab, there is no option to set capacity
![image](https://github.com/microsoft/coe-starter-kit/assets/13290218/93671788-d833-4cdf-b304-72d3c029f6d3)

**Comment by Jenefer-Monroe** [comment]
These records are created by the following flow: **_CLEANUP HELPER - Environment Capacity_**
Which is called to run for each envt weekly by the following flow: **_CLEANUP - Admin | Sync Template v4 (Other Objects)_**

**Comment by nmarija** [comment]
@Jenefer-Monroe thanks for the response. I have those flows turned on. However, I still can't set environment capacity. Can you please assist on this?

**Comment by Jenefer-Monroe** [comment]
Can you please go validate that CLEANUP HELPER - Environment Capacity has been running and passing? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1d4f4485-168e-4730-8f09-b897249f93f2)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
