### ISSUE TITLE
[CoE Starter Kit - QUESTION] Behavior when records are deleted in Dataverse

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#7870]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

If I delete app information or user information in the Dataverse of the CoE starter kit, will it automatically reacquire it?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2024/1

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2592

**Comment by RahulBojji** [comment]
@asuka1103131 Yes, in the next run of the inventory, the inventory flows will create the deleted data again.

**Comment by asuka1103131** [comment]
@RahulBojji 
Is it still covered if I have deleted it manually?

**Comment by RahulBojji** [comment]
Yes it does.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
