### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 CoE Solution Metadata failed run

### ISSUE THREAD

**Issue by accvik** [microsoft/coe-starter-kit#7871]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting failed runs for multiple iterations within this loop. Do I need to act upon this anyhow? Appears after upgrading to latest core 4.24

![image](https://github.com/microsoft/coe-starter-kit/assets/106146275/806583a7-78b6-41a7-8e29-299e2126e8e6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2595

**Comment by Jenefer-Monroe** [comment]
This likely just means that you had the flow running twice at the same time and so they were competing to delete the same resource. Can you validate this? 
The flow here is just deleting things removed from the kit and so you dont need to worry about this failure. It means it was already deleted by (in my assumption above) another iteration of the flow running.

**Comment by Jenefer-Monroe** [comment]
Good news! Thanks for using CoE

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
