### ISSUE TITLE
[CoE Starter Kit - BUG] Flow Broken Connections Report Not Accurate

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7874]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Orphaned cloud flows are being marked as not having broken connections but upon verification this is not correct. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/3cbf0725-1553-4b40-9eae-f542347528d1)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/eac029da-461c-4521-b13e-b3fa0eca0026)

### Expected Behavior

Report should be accurate regarding broken connections

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Open Power Platform Admin View. Add Flow has broken connections column. Verify data. 

AB#2598

**Comment by Jenefer-Monroe** [comment]
Hello. That is not what that field means. It's an internal field we use to identify when a flow or app has connectors which have not yet been inventoried. 
So imagine you create a custom connector, then add an app to it. And then the app goes into inventory before the custom connector goes into inventory. In this case we need to send the app through inventory again the next day after the custom connector has been inventoried. 

The thing you are trying to find is useful but its not something we have programmatic access to. We only know what **_connectors_** an app/flow uses. We do not know which **_connection_** it uses.

**Comment by nasilvae** [comment]
> Hello. That is not what that field means. It's an internal field we use to identify when a flow or app has connectors which have not yet been inventoried. So imagine you create a custom connector, then add an app to it. And then the app goes into inventory before the custom connector goes into inventory. In this case we need to send the app through inventory again the next day after the custom connector has been inventoried.
> 
> The thing you are trying to find is useful but its not something we have programmatic access to. We only know what **_connectors_** an app/flow uses. We do not know which **_connection_** it uses.

gotcha that makes sense. If possible, can we rename that column. It caused some questions on our side regarding report accuracy.

**Comment by Jenefer-Monroe** [comment]
I have heard this one other time, and recently. My only concern is if other things are relying on it and some PP objects look at display name not schema/logical.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
