### ISSUE TITLE
[CoE Starter Kit - QUESTION] Manage Permissions

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#7875]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,
   
How Tracking SRs suppose to work in Manage Permissions? Do you have any document?

Thank you,

### What solution are you experiencing the issue with?

None

### What solution version are you using?

March  2024

### What method are you using to get inventory and telemetry?

None

AB#2599

**Comment by Jenefer-Monroe** [comment]
We do not have documentation yet, no. 
But you can run this flow if it hasn't run already: **_Admin | Gather Tenant SRs_**
And that will populate the table where you can select which Security Roles you want to track, of those SR's if you want to track permissions via their Business Units as well. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e571b614-2c3a-4fde-ac1c-674c8191df5e)

Once you have the Permissions populated you can then manage them in the Manage SR's page:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8d4803aa-0455-4747-8f11-1029e1ca3dec)

**Comment by lingutla123** [comment]
Thank you Jenefer.

 When i select an user in Configure SRs why the 'Track BU' option is disabled?

Thank you,

**Comment by Jenefer-Monroe** [comment]
You first need to configure the SR to be tracked. And then once the SR is tracked you can chose to track the SR through BUs.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
