### ISSUE TITLE
[CoE Starter Kit - BUG] Grandfathered Connections API Column not accurate

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7878]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Power Platform Admin View Grandfathered Connection Column is not accurate. 

As an example the report is showing apps that have rss and sharepoint online connectors to be grandfathered which is not the case. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/af9b34c4-c4c3-462c-aab9-cfdc1b1dda5e)

https://learn.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#power-platform-use-rights-included-with-microsoft-365

### Expected Behavior

Report should accurately reflect apps that are using grandfathered connections per MS docs

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Open Power Platform Admin View
Add Uses Only Grandfathered Premium APIs column. 
Set Filter to True
Add/Compare App Connections column to validate grandfathered connections. 

AB#2602

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately that data is not yet returned in the payload from data export. Please provide that feedback to the product team as they continue to iterate on the schema.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by sayedpfe** [comment]
i am still facing this issue with some apps doesn't have any connections 

<img width="1680" height="542" alt="Image" src="https://github.com/user-attachments/assets/22a8c02e-87b2-48bd-bd59-9e8371690931" />

<img width="1628" height="79" alt="Image" src="https://github.com/user-attachments/assets/b86aa9ba-aebd-41f3-a947-83e0577bd47a" />
