### ISSUE TITLE
[CoE Starter Kit - BUG] Error 8004F01D and old CoE core component is not removed

### ISSUE THREAD

**Issue by faszul** [microsoft/coe-starter-kit#7880]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We upgraded the CoE - Core Components with February 2024 patch and ran the Wizard and found no issue but the old CoE still visible and not yet removed.

In history we found this error:
Error code
[8004F01D](http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=8004F01D&de=online)
Exception message
Solution dependencies exist, cannot uninstall. DependencyCount : 2 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: 8816b727-f46b-4433-b020-6f2e6931cb08, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000
See less
Total operation time
6 sec
Patch
Yes
Managed
Yes
Overwrite customizations
No
Activity id
8ce5a8a7-3b7f-4c33-b333-996d9bd4fa73

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.4.6070-2307.1

### What app or flow are you having the issue with?

CoE Core Components

### What method are you using to get inventory and telemetry?

None

### Anything else?

@
![image99](https://github.com/microsoft/coe-starter-kit/assets/142005629/404c6cbe-7a8d-4a64-8163-fdba71ecaa93)

AB#2603

**Comment by RahulBojji** [comment]
@faszul 
Hello, this is an expected upgrade failure due to the deprecation of the Audit Logs custom connector.
We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors.
Please see the following to resolve. https://github.com/microsoft/coe-starter-kit/issues/6018
If you have tried those steps and still see this error, note that some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use powershell to [find](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest) and [delete](https://learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest) these remaining connections to the old connector

**Comment by faszul** [comment]
Thanks Rahul. We will try to perform the steps and let you know.

BTW, our management have a question – by best practise how often we should perform the upgrade as it seems the upgrade is released monthly?
And what is the differences with the updates that being pushed automatically to the CoE.

Regards,
Fahdzul
[Image]


From: RahulBojji ***@***.***>
Date: Tuesday, 19 March 2024 at 4:15 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Aziz, Fahdzul ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Error 8004F01D and old CoE core component is not removed (Issue #7880)
@faszul Hello, this is an expected upgrade failure due to the deprecation of the Audit Logs custom connector. We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues


@faszul<https://urldefense.com/v3/__https:/github.com/faszul__;!!MfzFaTml5A!jYHK-eqWPEXzKTXj2RVRU06a0ZoM5bkVDdJfTdogunIVYhHkTDQubugOG-PfeguaYW3RVUlv1DQuXYgaGKyB7GCQhRyL-91EMp48i2wu$>
Hello, this is an expected upgrade failure due to the deprecation of the Audit Logs custom connector.
We have deprecated the custom connector technique to gather Audit Logs due to several issues like lack of pagination and upgrade issues with custom connectors.
Please see the following to resolve. #6018<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/issues/6018__;!!MfzFaTml5A!jYHK-eqWPEXzKTXj2RVRU06a0ZoM5bkVDdJfTdogunIVYhHkTDQubugOG-PfeguaYW3RVUlv1DQuXYgaGKyB7GCQhRyL-91EMg9shDj5$>
If you have tried those steps and still see this error, note that some people have found that there are still references to the connector remaining that they cannot see in the UX and hence have to use powershell to find<https://urldefense.com/v3/__https:/learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/get-adminpowerappconnection?view=pa-ps-latest__;!!MfzFaTml5A!jYHK-eqWPEXzKTXj2RVRU06a0ZoM5bkVDdJfTdogunIVYhHkTDQubugOG-PfeguaYW3RVUlv1DQuXYgaGKyB7GCQhRyL-91EMuObqV9r$> and delete<https://urldefense.com/v3/__https:/learn.microsoft.com/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappconnection?view=pa-ps-latest__;!!MfzFaTml5A!jYHK-eqWPEXzKTXj2RVRU06a0ZoM5bkVDdJfTdogunIVYhHkTDQubugOG-PfeguaYW3RVUlv1DQuXYgaGKyB7GCQhRyL-91EMk7MzU5-$> these remaining connections to the old connector

**Comment by RahulBojji** [comment]
We recommend upgrading the CoE Starter Kit solution at least every three months. We release updates to our kit every month. This might contain some new features or fixes to the bugs that the customers have reported. You can decide your update frequency by looking into [this](https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup#how-often-should-you-update-the-coe-starter-kit)

**Comment by faszul** [comment]
Thanks Rahul.

I also saw in KB that there will be update pushed automatically as long the unamanged layers is cleared. Is this is a different update from the updates that came out once a month?

Regards,
Fahdzul
[Image]


From: RahulBojji ***@***.***>
Date: Wednesday, 20 March 2024 at 3:16 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Aziz, Fahdzul ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Error 8004F01D and old CoE core component is not removed (Issue #7880)
We recommend upgrading the CoE Starter Kit solution at least every three months. We release updates to our kit every month. This might contain some new features or fixes to the bugs that the customers have reported. You can decide your update


We recommend upgrading the CoE Starter Kit solution at least every three months. We release updates to our kit every month. This might contain some new features or fixes to the bugs that the customers have reported. You can decide your update frequency by looking into this<https://urldefense.com/v3/__https:/learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup*how-often-should-you-update-the-coe-starter-kit__;Iw!!MfzFaTml5A!mCt4JQgrMYJEeMuNzuepLIFRvjtc8CDg7cJkz2rXohviD5Iq2aXTmQAi2sLPcRjHBmGwDXvvV_ot0hF0chvyRNjj9cA-_-7Pf1Ik63Cb$>

**Comment by RahulBojji** [comment]
Before upgrading the Kit, we are asking the customers to remove the unmanaged layers manually if they have performed any unmanaged customizations on any of the flow or the app so that whatever updates we release gets deployed successfully. Hope this answers your query

**Comment by Jenefer-Monroe** [comment]
Hello there are no automatic upgrades for the CoE in place. I'm not sure what you are referencing. 
You may have set up the Creator Kit for atuomatic upgrade which is a dependency the kit has. Or you may be referencing the product feature releases themselves. I'm not sure. 

But for the CoE Starter Kit there are no automatic updates sent.

**Comment by Jenefer-Monroe** [comment]
Here is what you'll need to do, this is outlined here as well with pictures so just putting the simple steps below so they are easier to see: https://github.com/microsoft/coe-starter-kit/issues/6018
Please reference https://github.com/microsoft/coe-starter-kit/issues/6018 for more assistance in how to do each of the steps below.

1. Uninstall the _Upgrade version of Core
1. Delete Audit Logs solution which is deprecated now
1. Make sure all connections to the old audit log custom connector are deleted (lots of detail in https://github.com/microsoft/coe-starter-kit/issues/6018 for this)
1. Upgrade to latest Core

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
