### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is it possible to obtain the list of applications shared with guest users ?

### ISSUE THREAD

**Issue by JulietteMahe1** [microsoft/coe-starter-kit#7881]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 
I would like to know if it is possible to obtain the list of applications shared with **guest users** ?
How to find this information in the dasboard or Power Platform Admin View ?
Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2605

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/da3523e9-1b66-4e1e-a8a6-c6f0f2c4a319)

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/292d5fdc-f9e6-4261-b0d9-935c274fcf44)
