### ISSUE TITLE
[CoE Starter Kit - BUG] Error when creating connection for HTTP with Microsoft Entra ID for URL https://graph.microsoft.com/ @ManagePermissionGrant.ps1

### ISSUE THREAD

**Issue by NarendraRWE** [microsoft/coe-starter-kit#7882]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are trying to install Microsoft Center of Excellence. 
When creating connection for HTTP with Microsoft Entra ID for URL https://graph.microsoft.com/ I get error "Consent Required: To enable the HTTP With Microsoft Entra ID connector to access resources on behalf of a signed-in user, grant consent to this application. 
We tried steps in https://learn.microsoft.com/en-us/connectors/webcontentsv2/#authorize-the-connector-to-act-on-behalf-of-a-signed-in-user. 
However the Power Shell script (ManagePermissionGrant.ps1) provided on the site is also failing with following error

Join-String : The term 'Join-String' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\UI906541\Downloads\ManagePermissionGrant.ps1:227 char:35
+ $joinedScopes = $selectedScopes | Join-String -Property {$_.Value} -S ...
+                                   ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Join-String:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

we need to understand what this powershell script is doing and and which all permissions we need to assign

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.0.20230727.2

### What app or flow are you having the issue with?

HTTP with Microsoft Entra ID connection

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

- Try to add the connector "HTTP with Microsoft Entra ID". 

- We receive error Consent Required: To enable the HTTP With Microsoft Entra ID connector to access resources on behalf of a signed-in user, grant consent to this application. More information: https://go.microsoft.com/fwlink/?linkid=2249190

- To Authorize the connector to act on behalf of a signed-in user we run the powershell script "ManagePermissionGrant.ps1" provided at https://learn.microsoft.com/en-us/connectors/webcontentsv2/#authorize-the-connector-to-act-on-behalf-of-a-signed-in-user.

- However the script fails to run with following error 
Join-String : The term 'Join-String' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\UI906541\Downloads\ManagePermissionGrant.ps1:227 char:35
+ $joinedScopes = $selectedScopes | Join-String -Property {$_.Value} -S ...
+                                   ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Join-String:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

AB#2606

**Comment by Jenefer-Monroe** [comment]
Hello. You need to use the **_HTTP with Microsoft Entra ID (preauthorized)_** connector. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f2e257bb-63ea-40a9-8db4-037321eb1cab)

**Comment by NarendraRWE** [comment]
Thanks Jenefer!! 
I tried the  HTTP with Microsoft Entra ID (preauthorized) connector and it worked

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Please let me know if there's anything else I can do for you, or if we're ok to close.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
