### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Get Security Role Users - BUFFER issue

### ISSUE THREAD

**Issue by robertobudelo-armacell** [microsoft/coe-starter-kit#7883]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When there is a high amount of teams associated to a role, Power Automate Buffer limit is reached.

![image](https://github.com/microsoft/coe-starter-kit/assets/108522258/cdc2dbb3-8e41-4f0b-8437-181be77b6b4f)

### Expected Behavior

Shouldn't fail.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Inventory flow

### Anything else?

Select columns, as teams return a lot of metadata.

![image](https://github.com/microsoft/coe-starter-kit/assets/108522258/2a97e8ef-f5a3-4b13-a6d9-f7c9e5465722)

AB#2607

**Comment by Jenefer-Monroe** [comment]
Thank you for posting. Good idea. I'll send you what I put in there and you can please test for me.

**Comment by Jenefer-Monroe** [comment]
I believe it is only this: `azureactivedirectoryobjectid`

Can you please try? 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/300070cb-572a-4937-bc96-1a12332a4a8e)

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot (you'll need to log in to GitHub to do that) to show me where you mean to add the filter?

**Comment by Jenefer-Monroe** [comment]
I think the second issue you raised about teams is this: https://github.com/microsoft/coe-starter-kit/issues/7917
Please do let me know in that issue if you have feedback.

**Comment by robertobudelo-armacell** [comment]
Jenner, i am on annual leave now, so harder to test for you, but will do when back and if still necessary!

Thx

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Friday, March 22, 2024 8:01:57 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Roberto Budelo Garcia ***@***.***>; Author ***@***.***>
Subject: [{EXT}] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] SYNC HELPER - Get Security Role Users - BUFFER issue (Issue #7883)


CAUTION: This email originated from outside Armacell. Do not click links or open attachments unless you recognize the sender and know the content is safe.

I think the second issue you raised about teams is this: #7917<https://github.com/microsoft/coe-starter-kit/issues/7917>
Please do let me know in that issue if you have feedback.

**Comment by Jenefer-Monroe** [comment]
Enjoy your break!
