### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Get Security Role Users - Users with ' in their name break the flow

### ISSUE THREAD

**Issue by robertobudelo-armacell** [microsoft/coe-starter-kit#7884]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

User having a ' in their display name break Odata syntax:

![image](https://github.com/microsoft/coe-starter-kit/assets/108522258/aa97f522-8c19-48c1-b464-21bdc1bae5e5)

### Expected Behavior

' is being escaped

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2608

**Comment by Jenefer-Monroe** [comment]
Thank you I'll try to get you something to test here in time for the April release.

**Comment by Jenefer-Monroe** [comment]
I think the fix is to put this:  `replace(item()?['admin_name'], '''', '''''')`

Here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/727c9577-5a29-4ba5-8113-d71242417fa3)

Can you please test for me?

**Comment by robertobudelo-armacell** [comment]
Almost. Correct would be:

replace(items('Apply_to_each_still_unknown'), '''', '''''')

(It’s in a Apply to Each).

You’d also need to update the next step where it’s being re-used:

***@***.***

Thanks!

Roberto Budelo
Power Platform Lead
IT/DIGITAL – Software and Application Services
Insultation Spain Holdings S.L.
Armacell Group

M.  +34 637 836 998
E.   ***@***.******@***.***>

www.armacell.com<http://www.armacell.com/de>

From: Jenefer Monroe ***@***.***>
Sent: Tuesday, March 19, 2024 4:27 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Roberto Budelo Garcia ***@***.***>; Author ***@***.***>
Subject: [{EXT}] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] SYNC HELPER - Get Security Role Users - Users with ' in their name break the flow (Issue #7884)


CAUTION: This email originated from outside Armacell. Do not click links or open attachments unless you recognize the sender and know the content is safe.

I think the fix is to put this: replace(item()?['admin_name'], '''', '''''')

Here
image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/727c9577-5a29-4ba5-8113-d71242417fa3>

Can you please test for me?

**Comment by Jenefer-Monroe** [comment]
I moved the change up to the Select Name outside of the apply to each so that we wouldnt have to do it multiple times. But let me test a little to see if that works ok.

**Comment by Jenefer-Monroe** [comment]
From my quick testing that does seem to address the issue. And we arent writing this name out so I think this works. 
Can you plesae put it here and let me know?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e90ac65f-6ce5-4745-9f25-d869f4ec462f)
