### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to set expertise level for training event

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#7886]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When creating a new training event in the Nurture Apps - Admin, the form does not have the field Expertise Level available for editing. 

### Expected Behavior

We should be able to apply the level of expertise to the training event so that the Maker can filter upcoming events.
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/c58efd02-0543-4d44-a24d-57daa8113f4c)
In order to achieve above we edited the form to make the field available but this will create an unwanted solution layer.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.12

### What app or flow are you having the issue with?

Nurture Apps - Admin

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2610

**Comment by Jenefer-Monroe** [comment]
Thanks to MDA this is super easy to fix! YEAH!
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d1725a7b-1377-4d40-acac-617807c46fbd)

**Comment by Jenefer-Monroe** [comment]
Ready for April.

**Comment by medicineshow** [comment]
Fabulous. Well done.
