### ISSUE TITLE
[ALM Accelerator - BUG]: Pipeline throwing deprecated tokens warnings. 

### ISSUE THREAD

**Issue by Aditi3981** [microsoft/coe-starter-kit#7887]
### Describe the issue

We are getting following warnings in 'initialize job' step of pipeline run.
![image](https://github.com/microsoft/coe-starter-kit/assets/60483804/1eb2c7a2-60bf-47c3-b8cd-e6e84cd958fb)

### Expected Behavior

There should not be any warnings after the pipeline run.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20240306.1(Managed)

### Steps To Reproduce

Run the build and deploy pipeline for any environment. 

AB#2611

**Comment by v-bjaiswal** [comment]
Hi @Aditi3981 , Thank you for bringing the issue to us. We are already looking this the issue.

**Comment by v-bjaiswal** [comment]
Closing this. please track it from the duplicated ticket. Thank you.
