### ISSUE TITLE
[CoE Starter Kit - BUG] Is it mandatory to have Azure secret key for populating App last launch date?

### ISSUE THREAD

**Issue by DheekshaSivaraj** [microsoft/coe-starter-kit#7888]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am currently storing the client secret in plain text in the Audit Logs - Client Secret environment variable. Yet the App last launch date is not populating. Is it mandatory to have Azure Key Vault for App last launch to be populated?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2612

**Comment by Jenefer-Monroe** [comment]
No its not. You can use a plain text secret instead. Here are some common troubleshotting tips that help most people out of the issue: 

1. Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

1. Please be sure that you have entered the secret itself and not the secret id (the GUID). It’s a longer string with a larger character set than a GUID. This one has a tilda for example.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/983a39fb-0b23-4d1f-83d5-8b41bb2bf270)

1. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

1. Turn the flows off and back on. Sometimes env vars get stuck in them with old values
1. Validate that you have [started the subscription](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

**Comment by DheekshaSivaraj** [comment]
Hi Jenefer, the registered app has the required API permission. I have confirmed this. I am using only Audit Log- Client secret environment variable. Please refer to the attached action outcome of the power automate flow.
![ListAuditLogcontent_error](https://github.com/microsoft/coe-starter-kit/assets/158851346/c0ea3f02-2d85-4290-8dcc-5579688b8098)
![AzureSecretKey_null error](https://github.com/microsoft/coe-starter-kit/assets/158851346/93baedf8-cb91-4b56-968d-95ecb1bdc8dd)

**Comment by DheekshaSivaraj** [comment]
![AppRegistration_permissions](https://github.com/microsoft/coe-starter-kit/assets/158851346/dcfd08e0-3a3e-4083-b789-2cb2e05899f8)
Please refer to the permissions we have.

**Comment by DheekshaSivaraj** [comment]
Please refer to the attached screenshot for the permissions that is currently present.
![AzureAppPermissions](https://github.com/microsoft/coe-starter-kit/assets/158851346/986608f7-c5c1-4824-bb3c-740d056e917b)

**Comment by Jenefer-Monroe** [comment]
I have seen issues where having both Delegated and Application permissions causes a failure. You might want to try removing the delegated permissions. 

Regarding that failure, as you are not using Azure Key Vault so this failure is expected and caught. 
Note that flow always shows the first failure even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by DheekshaSivaraj** [comment]
This issue is not resolved. We removed the delegated API permission, turned the flow off and on after the changes made in azure. Still the flow is not updating the last launch date. 
Please help!
