### ISSUE TITLE
[CoE Starter Kit - QUESTION] Inactivity Notifications: This flow owner cannot perform approval - person no longer with the company

### ISSUE THREAD

**Issue by johnravas** [microsoft/coe-starter-kit#7890]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

As a CoE admin , I am receiving these notifications for flows for people who are no longer with the organization.  I have other situations where it tells me: "Owner does not exist.  Sent to Admin".  I am surprised that the first situation doesn't send me owner does not exist notifications.  What is the appropriate way to handle these situations?  Why am I just not receiving Owner does not exist notifications for these users?  Is it because they are still in a table somewhere?

The owner does not exist situations allow me to approve or reject as an admin.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

November 2023

### What app or flow are you having the issue with?

Inactivity notifications

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2614

**Comment by Jenefer-Monroe** [comment]
Can you please share screenshots so I know what notifications you are referencing?

**Comment by johnravas** [comment]
Thanks @Jenefer-Monroe here are the screenshots:

This first screenshot is the main source for my question.  The person named in the subject is no longer employed with the company, and thus cannot response.  As named CoE admins, we receive this notification.  There has to be a recommended approach to handle these, but my searching hasn't revealed anything - 
<img width="659" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/59970962/bdc195f4-41a5-4171-b2ff-b81cb0c5667b">

versus a notification that looks like this:
<img width="490" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/59970962/e31705cc-5c66-4096-bf76-78eeb0335c4b">

Where it claims that the owner does not exist (but did at one point) and allows me to determine a disposition of the flow (at the bottom of the notification not shown.

Thanks in advance and let me know if there's anything else you need

**Comment by Jenefer-Monroe** [comment]
Oh I understand now, thank you so much for the screenshots. 
My initial guess is that the user and its objects are not yet identified as orphaned in the inventory. 
Can you please to the Power Platform Admin View app > Users > Makers and find this person. 
Click their name to open the form.
Are they shown as orphaned? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b07f2795-1138-4d95-b236-601f741bdf3f)

If not, please run the **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** flow
If so, let me know and we can look elsewhere.

**Comment by johnravas** [comment]
Thanks @Jenefer-Monroe.  I checked my users and the Maker is Orphaned field was no.  I checked the status of the users in the M365 admin portal and their status was sign-in blocked and they were unlicensed.

The flow has been running successfully every Tuesday at noon.  Ran it again today and no change in the status.  Is this because of their status in M365?

**Comment by Jenefer-Monroe** [comment]
Are you saying that this status is disabled? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d1afcf1e-26c1-4cc2-87c6-b2f4b138030f)

**Comment by johnravas** [comment]
@Jenefer-Monroe - correct.  Confirmed.
![image](https://github.com/microsoft/coe-starter-kit/assets/59970962/bf7d598c-2cfb-4b1c-b146-17f6761b0845)

**Comment by Jenefer-Monroe** [comment]
Got it. By default we do not treat Disabled accounts as orphaned, but you can set this environment variable so that we do.
In the command center you can set **_Disabled Users are Orphaned_** to **_yes_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c2fa58c2-8622-4fd0-b7ed-6d74a8f754de)

You may want to also restart the following flow to be sure the env var is not cached: **_HELPER - Maker Check_**

Then after the next run of **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** you should see them correctly marked as orphaned.

**Comment by johnravas** [comment]
Perfect!!  Thank you @Jenefer-Monroe.  Just switched the environment variable and I check again after the run of the flow.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
