### ISSUE TITLE
[CoE Starter Kit - BUG] Import is getting failed while upgrading COE starter kit core component from 4.3 to 4.22

### ISSUE THREAD

**Issue by rajaug3** [microsoft/coe-starter-kit#7898]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When i'm importing 4.22 core component version i'm getting below error. However i have full access to keyvault and the srevice account. Help which account it is looking for?
Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :User is not authorized to read secrets from '/subscriptions/3xxxxxxxxxx/resourceGroups/RG-xxxx-Prod/providers/Microsoft.KeyVault/vaults/ABC-AV-ppkeyvault/secrets/COECommandCenter' resource.

### Expected Behavior

when you import corecomponent

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

*

### What method are you using to get inventory and telemetry?

None

AB#2623

**Comment by Jenefer-Monroe** [comment]
Sometimes solution upgrade fails when key vault env vars are present. I dont experience this myself so its some intermittent or inconsistent product issue. 
I do know that the workaround that has worked for others is to remove the key vault values, do the upgrade, and reapply the key vault env vars.

**Comment by rajaug3** [comment]
If i am removing key vault i'm getting below error
Import failed: Null or empty secret reference value found.

**Comment by Jenefer-Monroe** [comment]
Unfortunately what you are experiencing is a product issue with solution import and not an issue with the kit.
But hopefully we can find the workaround. 

If you go to the Default Solution > Environment Variables > filter to this env var
Note that Env Vars have both "Current Values" and "Default Values"
Yours should always be in the "Current Values" as Default Values are things that are overwritten when you upgrade. 
Can you please go see, do you have values in either Current or Default? 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a32f803e-ec06-4d13-ad1c-b12cf38b1f38)

**Comment by rajaug3** [comment]
The problem lies within the COE Command Center. Upon inspection of the azure-secret for the coe command center, it was found to have a value in the current section, while the default section remains empty. However tried to update the default value got the above error "This variable didn't save properly. User is not authorized to read secrets from '/subscriptions/3xxxxxxxxxx/resourceGroups/RG-xxxx-Prod/providers/Microsoft.KeyVault/vaults/ABC-AV-ppkeyvault/secrets/COECommandCenter' resource"
![image](https://github.com/microsoft/coe-starter-kit/assets/80772804/5a349542-af21-4d39-95e6-3f908b96cdce)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
