### ISSUE TITLE
[CoE Starter Kit -BYODL- BUG] PVA Flow Error

### ISSUE THREAD

**Issue by jayakumarkgds** [microsoft/coe-starter-kit#7899]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting "The user is not a member of the organization." error in couple of execution for the PVA Flow
<img width="186" alt="PVA-Error" src="https://github.com/microsoft/coe-starter-kit/assets/87489417/64f67fd1-4169-4f38-9d30-854fa8f1fe87">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (PVA)

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Validate Admin | Sync Template v4 (PVA) run status and open failed execution
 

AB#2624

**Comment by jayakumarkgds** [comment]
same error for desktop Flows as well.
![image](https://github.com/microsoft/coe-starter-kit/assets/87489417/d4e22c01-74a9-4005-8cec-62247128cdba)

**Comment by Jenefer-Monroe** [comment]
This means that you do not have access to that envt. Can you please go check to be sure you have Sys Admin SR in the envt being inventoried in this run?

**Comment by Jenefer-Monroe** [comment]
Then if you do not, that means that either you dont have your Power Platform Admin Role permanently and directly assigned. Or you've opted in to the new PIM feature for the role which is not yet integrated with the kit. 
Please let me know your thoughts and we can debug further.

**Comment by jayakumarkgds** [comment]
> Then if you do not, that means that either you dont have your Power Platform Admin Role permanently and directly assigned. Or you've opted in to the new PIM feature for the role which is not yet integrated with the kit. Please let me know your thoughts and we can debug further.

I am running with permanently assigned power platform admin account and this is running for most of them and only few am getting this error.

Also getting such errors
![image](https://github.com/microsoft/coe-starter-kit/assets/87489417/d5e757a7-72b4-4d0d-b466-3370f2dd6fad)

**Comment by Jenefer-Monroe** [comment]
Can you please check to see if the user running the flow has Sys Admin permissions in the envt itself? There are some new features in preview you may have opted into in your org that cause bugs like this. 
https://admin.powerplatform.microsoft.com/environments/ > Select Envt > Settings > 
Users + Permissions > Users
Click the users name > Look at Roles

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/54fffc7b-5d9e-4988-bcfa-98b405d469d0)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9605f18d-8ae7-4fb6-9901-6423378b0761)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0dae9546-5183-47b1-abf1-b404847ce5ac)

**Comment by jayakumarkgds** [comment]
i can see the accounts as disabled.This account is powerplatform adminuistrator but those environments are updated with teams groupMay be because of that the account is showing disabled?

**Comment by Jenefer-Monroe** [comment]
Yes thats the problem. 
Not sure why the user is showing disabled in that envt, but you will need to enable and set them as System Administrator

Once you fix that up and confirm you are unblocked we can see how you got into this state.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
