### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Wizard error looking for Sync v3 and should be Sync v4

### ISSUE THREAD

**Issue by ken-hansen-rga** [microsoft/coe-starter-kit#7904]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When trying to set up compliance pieces with the Setup App, it fails saying it is waiting for Sync v3 to finish. The newest CoE is using Sync v4. I updated this in the App.OnStart for each compliance page and it worked after that change.

### Expected Behavior

It should recognize v4 sync runs

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Center of Excellence Setup Wizard

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

In fresh environment go through the setup process in order. 
When you attempt Compliance Process it will fail looking for Sync v3 runs

AB#2629

**Comment by ken-hansen-rga** [comment]
Also happens with Nuture Components

**Comment by RahulBojji** [comment]
@ken-hansen-rga Thanks for posting this. There is a similar bug created recently which has been tracked [here](https://github.com/microsoft/coe-starter-kit/issues/7806). Marking this as a duplicate

**Comment by Jenefer-Monroe** [comment]
The dupe did not fix this for Nurture apps. I will take a look.
