### ISSUE TITLE
[CoE Starter Kit - Feature]: Canvas App "App and Flow Inactivity Notifications Clean Up" Sort by "Created On" Column

### ISSUE THREAD

**Issue by VolkerSteltenkamp** [microsoft/coe-starter-kit#7908]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

The Canvas App shows every inactivity notification sent out to the maker unsorted. I´d like to sort the gallery at least by the "Created On" (by "Maker" or by "Name" would be awesome!) column so I can remove doubled entries easily.

AB#2633

**Comment by Jenefer-Monroe** [comment]
Hello thank you for posting. 

We have a complete remake of this app on the list for upcoming months so we are not likely to make changes to these at this time. You can feel free to make some changes locally if needed. Or do know that its based off the Archive Approval table so you can sort/filter and delete records there.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
