### ISSUE TITLE
[ALM Accelerator - QUESTION] commiting and deploying solution fron Devloper evnironment

### ISSUE THREAD

**Issue by MudassarAliakhtarAli** [microsoft/coe-starter-kit#7909]
### What is your question?

consider we have 3 developer env, 1 dev master and UAT, if Developer is working on his env (dev1) and we have installed ALM accelerator in dev master so How developer will access ALM accelerator  to commit and deploy the solution.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20240104.1

AB#2634

**Comment by mikefactorial** [comment]
@MudassarAliakhtarAli the recommendation is that the ALM Accelerator app be installed in an environment that all makers / devs have access to (https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-admin-tasks#prerequisites). You should only need one instance of the ALM Accelerator for all projects. You can restrict access to specific profiles and features using Deployment User Settings (https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-deployment-user-settings)

**Comment by MudassarAliakhtarAli** [comment]
Thanks mikefactorial
