### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis - Name Change doesn't update

### ISSUE THREAD

**Issue by Sinder88** [microsoft/coe-starter-kit#7912]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When editing an existing DLP and renaming the policy, the app will say successfully saved but the DLP name will not have been updated. 

### Expected Behavior

DLP name should be updated

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

DPL Impact Analysis

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2637

**Comment by Jenefer-Monroe** [comment]
We can take a look but this app is quite complicated so I would suggest making that particular change in the product itself. 
The main point of this app is the impact analysis which is not yet available from within the product. 
Please do let me know your thoughts there.

**Comment by Jenefer-Monroe** [comment]
Got it, thank you for posting!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
