### ISSUE TITLE
[CoE Starter Kit - Feature]: AI Events - change to built in pagination

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#7913]
### Is your feature request related to a problem? Please describe.

Today the flow was written with some home made pagination
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7faabdcc-9c30-4b27-9a9c-30aa299178fe)

### Describe the solution you'd like

Switch to built in pagination
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1a2444fd-41e4-4262-b622-69fe1f5bffdd)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1c5ccdf9-6448-4844-9d41-3af1ba3dd812)

AB#2638

**Comment by MaheshSripada** [comment]
@Jenefer-Monroe: This has been implemented in June release.
