### ISSUE TITLE
COE starter kit Flows not running

### ISSUE THREAD

**Issue by Avinash-2024** [microsoft/coe-starter-kit#7924]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

COE starter kit Flows not running.

Please confirm what all the flows needed to be turned on to make the COE starter kit working without any issues.

Due to this COE starter kit Power BI dashboard report is showing 7 months old data and it is not showing latest data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2651

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

Then see if there are any sync flow errors to investigate. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d43b50b3-84d1-4894-a9a3-04d5d95fe8dc)

**Comment by Avinash-2024** [comment]
Hi Team,

Please find the attached screenshots of the status of all inventory flows and Sync Flow errors.

Appreciate if any one can provide the resolution.
![5](https://github.com/microsoft/coe-starter-kit/assets/164846088/425aca60-0c19-4a6b-9ed1-6e42a5bdd73f)
![6](https://github.com/microsoft/coe-starter-kit/assets/164846088/34f92f22-6d20-44ae-94a2-e1865227067a)
![Syncflows](https://github.com/microsoft/coe-starter-kit/assets/164846088/eede11c8-fa88-456c-bbd9-ac310570241f)

![2](https://github.com/microsoft/coe-starter-kit/assets/164846088/bacb4cb4-ac31-43fd-b97b-7363f6efccf5)
![3](https://github.com/microsoft/coe-starter-kit/assets/164846088/3903d115-ffcf-42dc-b0bf-1af06c14fb41)
![4](https://github.com/microsoft/coe-starter-kit/assets/164846088/1cb1abfb-c6a7-437a-a5d5-ce96901e334d)


![1](https://github.com/microsoft/coe-starter-kit/assets/164846088/d5ed803d-9c4d-4493-973f-f964813e7efa)

Regards.
Avinash.

**Comment by Avinash-2024** [comment]
Hi Team,

As requested please find the attached solutions screenshot which are installed in the environment.

![Solutions](https://github.com/microsoft/coe-starter-kit/assets/164846088/a25518d1-12d6-4770-9037-8f16545ba793)

Regards.
Avinash.

**Comment by Jenefer-Monroe** [comment]
Ok here is your problem. Your upgrade failed and so you are in an unknown state
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7feed92a-1cbc-497b-b567-bf110e50093a)

When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. 
These will never converge or repair on their own, you will need to take action to resolve as a result. And until you do, you are in an unknown state.
If you go to history you may find where the failure occurred and download details about it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb0966a6-dbfb-400b-b796-5ecb5d20c1da)
And if you don’t, then you should delete the _upgrade. And try to upgrade again to see either if it succeeds this time, or if you see the error message this time.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/44eafb8d-a0b1-40e5-af3b-b3f1b502146c)

**Comment by Avinash-2024** [comment]
Hi Team,

As suggested I have deleted the _upgrade and _upgrade got deleted successfully.

Please find the attached screenshot after deletion of _upgrade. Appreciate if you can please help us with the next steps.

Still we are facing the issues with inventory flows and inventory flows are not getting turned on successfully.

![Solutions1](https://github.com/microsoft/coe-starter-kit/assets/164846088/beff1cea-0222-45bc-9aff-b4cb617946c4)

Regards.
Avinash.

**Comment by Jenefer-Monroe** [comment]
Now we need to get you updated.

Seeing that you have Audit Logs installed, I'm certain that is what caused your upgrade failure to occur when you tried it in the past. We deprecated the custom connector for this in August of last year so your next upgrade attempt would also fail.

You will need to follow the steps documented here: https://github.com/microsoft/coe-starter-kit/issues/6018
In short its these steps, and you have now already completed step 1

1. Delete _upgrade
2. Delete Audit Logs solution and any other dependencies
3. Try your upgrade of Core again
4. Setup new Audit Logs collection technique

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Avinash-2024** [comment]
Please close this ticket and this is working perfect now.
