### ISSUE TITLE
COE starter kit Core components Solution Upgrade Issue

### ISSUE THREAD

**Issue by Avinash-2024** [microsoft/coe-starter-kit#7925]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Even though the core components solution got updated to the latest version 4.23 the old version of core components 4.9 version is not getting deleted automatically.

Ideally the old version should get deleted automatically.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2652

**Comment by Jenefer-Monroe** [comment]
When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. 
These will never converge or repair on their own, and you are in an unknown state until it is resolved. You will need to take action to resolve as a result.
If you go to history you can find where the failure occurred and download details about it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb0966a6-dbfb-400b-b796-5ecb5d20c1da)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Avinash-2024** [comment]
Please close this ticket and this is working perfect now.
