### ISSUE TITLE
[CoE Starter Kit - QUESTION]: Developer Compliance App 

### ISSUE THREAD

**Issue by thotavinod590** [microsoft/coe-starter-kit#7927]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can you please help us to understand below points:

1. In latest version of CoE toolkit currently in which solution developer compliance app is available and share the solution version ID.
2. How developer compliance App is useful to adopt in our organization.
3. How to customize the email notification from developer compliance app. 
4. If we plan to customize in developer compliance app in terms of Adding a new column in data verse table, email customization will be impact any further upgrades

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

AB#2654

**Comment by Jenefer-Monroe** [comment]
### Developer Compliance Center
Here is some links to get you started on the Developer Compliance Center: 

- [App auditing process](https://learn.microsoft.com/power-platform/guidance/coe/example-processes)
- [Compliance process components](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#compliance-processes)
- [Set up Developer Compliance components](https://learn.microsoft.com/power-platform/guidance/coe/setup-governance-components)

This has been part of the kit for years and is in the latest release. You will find the apps in the Governance solution. I suggest you take a look at the Setup document above to find it. 

### Customize Emails
Please see [Customize emails](https://learn.microsoft.com/power-platform/guidance/coe/faq#customize-emails) from our FAQ. 
At a high level, all emails sent by flows in the kit are customizable in the Admin Command Center
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/faab74ce-11b0-4164-bac1-a61c44d7f091)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1c3d0774-7176-4ac6-9d45-8f127d8c823d)

**Comment by Jenefer-Monroe** [comment]
Yes the app is in governance component. Please see [Set up Developer Compliance components](https://learn.microsoft.com/power-platform/guidance/coe/setup-governance-components)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/438ec8f3-a971-4a12-929b-ac3c7a6cec50)

**Comment by Jenefer-Monroe** [comment]
The impact of changes on the ability to upgrade is not a simple answer unfortunately. 

Adding new columns to a table **_does not_** block ability to see changes to that table on upgrade
Adding new objects onto the app/custom pages **_does_** block ability to see changes to that app on upgrade

For customizing mail, we have created a custom solution to support this. Please see [customizing emails](https://learn.microsoft.com/power-platform/guidance/coe/faq#customize-emails) from our FAQ

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
