### ISSUE TITLE
[CoE Starter Kit - BUG] DLP policy scope gets changed from "Exclude certain environments" to "Add multiple environments" when updating a DLP policy

### ISSUE THREAD

**Issue by ramontebar** [microsoft/coe-starter-kit#7928]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The DLP policy scope gets changed from "Exclude certain environments" to "Add multiple environments" when updating a DLP policy using the DLP Impact Analysis tool. This issue has been identified in the March 24 release.

### Expected Behavior

DLP policy scope must not change unless it is the expected required change.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

DLP Impact Analysis

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Go to [Power Platform Admin Center](https://admin.powerplatform.microsoft.com/dlp/new), create a new DLP policy where scope is "Exclude certain environments"

![7928-coekit_bug-update-DLP_new-exclusion-policy_2024-03-26](https://github.com/microsoft/coe-starter-kit/assets/7858467/b2c5da16-2dee-401e-b7d4-03b64bbb66fb)

![7928-coekit_bug-update-DLP_new-exclusion-policy-review_2024-03-26](https://github.com/microsoft/coe-starter-kit/assets/7858467/a153ecbc-613c-4579-8931-15e99d77c1b7)

2. Once the policy is created, go to DLP Impact Analysis tool, open the same policy and update some of the environments in this policy and save changes.

![7928-coekit_bug-update-DLP_new-exclusion-policy-list_2024-03-26](https://github.com/microsoft/coe-starter-kit/assets/7858467/3b051701-0b40-4153-942d-8f9898f7f4b4)

![7928-coekit_bug-update-DLP_impact-analysis-tool_exclusion-scope_2024-03-26](https://github.com/microsoft/coe-starter-kit/assets/7858467/490440ec-ac6a-4a13-9801-584465138562)

![7928-coekit_bug-update-DLP_impact-analysis-tool_update-policy_2024-03-26](https://github.com/microsoft/coe-starter-kit/assets/7858467/fa503827-8387-4791-a216-84d07e086872)

3. Once the policy is updated, its **scope** will change automatically and unexpectedly **from "Exclude certain environments" to "Add multiple environments"** 

![7928-coekit_bug-update-DLP_impact-analysis-tool_add-multiple-environments-scope_2024-03-26](https://github.com/microsoft/coe-starter-kit/assets/7858467/373b7fc5-b635-4e62-b1cb-d28ce1f34733)

AB#2655

**Comment by Jenefer-Monroe** [comment]
Thank you for posting. To area owner for investigation.

**Comment by RahulBojji** [comment]
@ramontebar Thanks for posting this. Can you please share the screenshots of what you are doing for my better understanding??

**Comment by ramontebar** [comment]
Hi @rahulbojji, I have updated the issue descrition to provide some screenshots and additional details. Hope that helps.

**Comment by RahulBojji** [comment]
Thanks for adding screenshots in detail. I was able to repro the issue now. Will add it for May Release.
