### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Data Export Method

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#7929]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

There doesn't appear to be any information on the last start date of Power Apps or the last execution of Automate in M365, where are you picking up this information from?
The following questions are tied to the following questions.
https://github.com/microsoft/coe-starter-kit/issues/7596#issue-2119754439

I am signing up for Azure blob storage but I don't know how to estimate the logs.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2024/1

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2656

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry I'm not following your question. Once you get set up for the Data Export system through the product then this data is returned in the Storage Account that you create:

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a8c41cbc-1a91-4d41-85aa-94b253c9f7dc)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e61aa6f4-9f16-4323-a9a6-624010d48503)

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
If I sign up for Azure blob storage, does that mean the data is automatically retrieved and stored in the USAGE folder?

**Comment by Jenefer-Monroe** [comment]
Yes that is correct. Once you set up the Data Export feature:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/25a897ac-2e2a-4429-8467-d1d1b76af333)

The usage will flow into the storage account:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0b75adf8-83e9-4235-bf9d-544347e59738)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/41512df0-4bb7-4f2c-aa41-421b8c1acef9)

Note that this can take 1-2 weeks to populate. If it does not end up there you will need to contact [product support](https://learn.microsoft.com/power-platform/admin/get-help-support) who can help get the feature working for you.

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
Is it possible to know the amount of data in advance?
I would like to know how much it will cost to sign the contract.

**Comment by Jenefer-Monroe** [comment]
Unfortunately we don't have that. There is a request for the Data Export product feature to document a sizing estimate but it has not been made yet.
However I can tell you loosely that you will have a usage file for each day, and every launch (or run) will be in that file.

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
Does "All launches (or executions)" include Power Automate and Power Apps?

**Comment by Jenefer-Monroe** [comment]
Sorry can you show me what you are referencing? Where is that string?

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
It seems there was something wrong with the translation.
I mean every launch (or run).

**Comment by Jenefer-Monroe** [comment]
Sorry I see, you were referring to my own words haah. Got it :)
Yes that will be all the Power Automate Cloud Flow runs and all the Power Apps Canvas App launches.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
