### ISSUE TITLE
Cloud flows "Flow Last Run ON" not updating in CoE.

### ISSUE THREAD

**Issue by muler-git** [microsoft/coe-starter-kit#7931]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Cloud flows "Flow Last Run ON" not updating in CoE.

When we check for flow last run in CoE 'Flow' table, we see it's not updating from few months for all cloud flows. Below is the screenshot for reference.

<img width="406" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/125889020/a526c6a6-6ddd-4417-b066-47ddb45af81f">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feb 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2658

**Comment by Jenefer-Monroe** [comment]
Hello. Note that this field is filled only if you are using Data Export methodology to gather inventory. It is not filled if you are using the cloud flow architecture.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
