### ISSUE TITLE
[CoE Starter Kit - QUESTION] PBI connector count for and or flows

### ISSUE THREAD

**Issue by muler-git** [microsoft/coe-starter-kit#7932]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

CoE Power bi Production Dashboard showing wrong count for flows in 'Connector Deep Dive' page compared to other pages (Cloud Flows, Flow Deep Dive)?

Previously mentioned that its fixed, but i see the same issue "Production_CoEDashboard_February2024"
https://github.com/microsoft/coe-starter-kit/issues/7386

<img width="194" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/125889020/f312a273-de7c-49f3-ac6c-5e439d84c300">

<img width="291" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/125889020/3714187d-d0e1-44ea-9d52-ddf661b1f99c">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feb 2024

### What app or flow are you having the issue with?

Production_CoEDashboard_February2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2659

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, to investigate soon.

**Comment by lukas-nC** [comment]
@Jenefer-Monroe 
please also have a look into the BYODL Dasboard 
in Connector deep dive I get quite a few blanks ones
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/d16a4a13-54a8-4236-b6de-4cd15ac66e9a)

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortuantely we are not able to get this visual to work correctly for connectors due to the relationship complexity.
For non-BYODL we are now working correctly on the connector deep dive screen and we have removed it form the drill down on the app and flow deep dives

**Comment by Jenefer-Monroe** [comment]
For the BYODL DB, we will update that with the upcoming FC for the Data Export schema changes.

**Comment by Jenefer-Monroe** [comment]
Removing this visualization type from the PBIT file
