### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power BI

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#7933]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

Where we can see list of Connectors are using in Power BI report?
I looked into 'Connector Deep Dive'. But it is not giving full list.

Thank you,

### What solution are you experiencing the issue with?

None

### What solution version are you using?

March  2024

### What method are you using to get inventory and telemetry?

None

AB#2661

**Comment by Jenefer-Monroe** [comment]
The PBI does not have a list of all connectors, you will only find there connectors that are used by Cloud Flows and Canvas Apps.
If you want to see the full list of connectors you can use the Power Platform Admin View app:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4e9d2035-613f-4d74-b05b-0f21058ad631)

Please let me know if I've misunderstood the question.

**Comment by lingutla123** [comment]
Thank you.
