### ISSUE TITLE
[CoE Starter Kit - QUESTION] Orphaned Objects

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#7935]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, I am looking to turn on the flows to handle the Orphaned Objects, when looking at the Admin view there is a column for M2 Manager Principle Name.
Do the flows automatically send the Teams bot message to clean up orphaned objects to the M2 Manager if the manager of the original manager is no longer with the company, or would these not be picked up by the orphaned clean up process?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.16

### What app or flow are you having the issue with?

Request Orphaned Objects

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2663

**Comment by Jenefer-Monroe** [comment]
It does not, no. We added that field for people who wanted to extend the kit to do that themselves.

**Comment by Alyson95170** [comment]
Thanks Jenefer
