### ISSUE TITLE
PowerPlatform App/Flows - Archival Process

### ISSUE THREAD

**Issue by iprasadraju** [microsoft/coe-starter-kit#7936]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Team, 

We appreciate the Power Platform CoE Starter Kit, which has allowed us to identify eligible components (Apps & Flows) for archival using the Archival score. 
Could you please advise on recommended options for archival, including application data? Additionally, do we have any available processes within the CoE Starter Kit for this purpose?

Thanks,
Prasad

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

October 2023

### What method are you using to get inventory and telemetry?

None

AB#2664

**Comment by Jenefer-Monroe** [comment]
Hello. Thanks for the kind words! 

I'm not sure what you mean by application data. But it sounds like you are using the PBI solution for identifying unused objects. We do have a solution area separate from the PBI tool for this. 
Please see :

- [Set up inactivity processes](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components)
- [Whats in the inactivity processes](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
