### ISSUE TITLE
[CoE Starter Kit - BUG] BYOD_CoEDashboard_Jan2024 / BYOD_CoEDashboard_March2024 - Power Automate overview not showing all

### ISSUE THREAD

**Issue by arpalmares** [microsoft/coe-starter-kit#7938]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Encountered same issue as [#7379](https://github.com/microsoft/coe-starter-kit/issues/7379). Tried upgrading to March 2024 version but still not reflecting the overall Cloud Flow count accurately.

BYOD Dashboard count
![image](https://github.com/microsoft/coe-starter-kit/assets/546819/42fc0244-7a18-471a-8e2a-8cf536c1cca8)

Upon checking the Power Platform Admin Center analytics, inventory of our power automate flows are still at 190k+.
![image](https://github.com/microsoft/coe-starter-kit/assets/546819/b0decde5-07a5-4b22-964e-cd8501641f06)

### Expected Behavior

Expecting around 190k+ flows for the Power Automate Overview count in BYOD dashboard. Only shows 78,000+ flows on the dashboard.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

BYOD_CoEDashboard_Jan2024 and BYOD_CoEDashboard_March2024

### What app or flow are you having the issue with?

N/A - Report is connected thru Data Lake

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Power Platform Admin Center exports data to Azure Data Lake
2. Power BI Data Flow connects to Azure Data Lake
3. CoE Dashboard connects to Power BI Data Flow

*** Power BI Data Flow is taken from the CoEStarterKit (PowerPlatformAdminAnalytics-DF.json)

### Anything else?

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi

AB#2669

**Comment by Jenefer-Monroe** [comment]
Did you see and local fix this issue already? https://github.com/microsoft/coe-starter-kit/issues/7790

**Comment by arpalmares** [comment]
How does the CoE BYODL Power Platform Dataflow affect the Data Export? Tried querying the storage container directly to check flow count of just the default environment (should be around 160k). Please see screenshots.

![image](https://github.com/microsoft/coe-starter-kit/assets/546819/6caf4a5b-70f2-40fd-a9d2-6da440d4a98a)

![image](https://github.com/microsoft/coe-starter-kit/assets/546819/9a65afb2-f5c9-4d20-a7bb-ad682d6c7b8d)

**Comment by Jenefer-Monroe** [comment]
It sounds like you are looking at the count from the Data export file directly in your first screenshot. Is that correct? 
And the second screenshot is from the product's admin pages. 
I dont think our dataflows are involved in either number here. Please let me know if I'm missing something.

**Comment by arpalmares** [comment]
The transform function (parsing the json file) from the CoE dataflow was copied to get this count.

**Comment by Jenefer-Monroe** [comment]
Please go to the Datalake and find the flow file for an environment where you expect to see flows but do not. 
You can do this by going to the Storage Browser and searching for the GUID of the envt
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/160575cf-225f-4d31-b7db-88fc079f3ed7)
### Question 1: What is the last modified date shown for the file? 
Next please click on the file and download it to view
### Question: 2 Is the file formatted like image 1 with a single line per flow or like image 2 with a jumbled look?
**Image 1 : Well formatted**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dbf210ec-8544-4e82-a03e-e6196f0685fc)
**Image 2 : Not well formatted**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/589de3df-db6c-4101-ba16-05fd530c56c0)

**Comment by arpalmares** [comment]
I had previous copies of the same file. Filesize is less than expected. Used to be around 100+MB. Now only 20+MB.

Last modified 4/1/2024.
JSON file is well-formatted.

**Comment by Jenefer-Monroe** [comment]
Are the flows you expect to see in there, in there? Or is the count approximately correct looking for the envt?

**Comment by arpalmares** [comment]
No. Incomplete.

**Comment by arpalmares** [comment]
Got it. Already have a Microsoft Premiere ticket open. Thank you.

**Comment by Jenefer-Monroe** [comment]
you bet, please let me know what you hear from them

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
