### ISSUE TITLE
[CoE Starter Kit - QUESTION] Teams作成時にユーザが警告メールを受領する件

### ISSUE THREAD

**Issue by MOLIS-citizen** [microsoft/coe-starter-kit#7940]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

お世話になっております。
 現在、弊社ではCoEスタータキットの導入を実施しており、以下ユーザより問い合わせありました件についてお伺いしたく。
Teamsを作成した際、作成したユーザへ警告メッセージのメールが送信される事象を確認いたしました。 
こちらはMS社へお問合せしたところ、CoEスタータキットの自動クリーンアップによるものとの回答をいただきました。

また、通知機能をオフすることは可能だが、機能をオフにするとDataVerse for Teamsの環境が続々と作成されてしまうという点、ご教示いただきました。
つきましては、対象のメッセージはオフにしない方が良いと考えますが、その場合、通知を受領したユーザ側で何かアクションが必要になるのかを教えていただきたく。

----------------------------
■公開情報
Title : 環境の作成の管理
URL : https://learn.microsoft.com/ja-jp/power-platform/guidance/adoption/teams-environment-strategy#govern-environment-creation
----------------------------

上記の「環境の作成の管理」の公開情報に、下記の記載があることから、ユーザ側での「業務上の理由の提供」が必要になるのかと考えますが、認識合っていますでしょうか？
またその場合、どのように対応すれば良いでしょうか？

・チームの所有者は業務上の正当な理由を提供する
　⇒管理者が承認または拒否を実施
　⇒自動クリーンアップが定期的に実行され、拒否された環境または要求されていない（正当な理由が提供されていない）環境を削除

また、ついでに恐縮ですが、当通知については、CoEスタータキットの導入時に作成されたPowerAutomateのフローの機能によるものかと思いますが、こちらはどのフローの機能により発砲されているか分からず、合わせてご教示いただけますと幸いです。
 
お忙しいところ恐れ入りますが、ご確認をよろしくお願いいたします。

添付：[Teams作成時の警告メール.xlsx](https://github.com/microsoft/coe-starter-kit/files/14756850/Teams.xlsx)

### What solution are you experiencing the issue with?

Audit Log

### What method are you using to get inventory and telemetry?

None

AB#2671

**Comment by MOLIS-citizen** [comment]
ご担当者

意恧证晷沥ぶ小⒔庹iいただきありがとうございました。

＞If that is the case, then yes your Makers will get a prompt to provide business justification for teams environments when they create them, and if they do not do so, they will get a reminder email, and then if they still do not respond, their teams environment will be deleted.
こちらの、「ビジネス上の正当な理由を提供する」とは具体的にどのような辘颏工欷肖瑜恧筏い扦筏绀Δ
また、この通知に甏黏筏胜龊稀h境が削除されてしまうとのことですが、それはどのくらいで期限となるのでしょうか。

更に|してしまい申しUありませんが、ご_Jをいただけますと幸いです。
よろしくおいいたします。

--------------------------------------------
To whom it may concern

Thank you for your understanding even though it was difficult to understand us intentions.

＞If that is the case, then yes your Makers will get a prompt to provide business justification for teams environments when they create them, and if they do not do so, they will get a reminder email, and then if they still do not respond , their teams environment will be deleted.

What concrete response should we take when we get "a prompt to provide business justification for teams environments"?
Also, if we don't respond to this notification, the environment will be deleted, but how long does that take?

We apologize for asking more questions, but we would appreciate it if you could confirm.
Best regards.

________________________________
差出人: Jenefer Monroe ***@***.***>
送信日r: 2024年3月26日 22:15
宛先: microsoft/coe-starter-kit ***@***.***>
CC: Citizen_Development ***@***.***>; Author ***@***.***>
件名: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - QUESTION] Teams作成rにユ`ザが警告メ`ルを受Iする件 (Issue #7940)


Hello. Sorry with the language difference I hope the translation service got me the correct idea.

It sounds like you have the Dataverse for Teams Governance solution area from the Governance starter kit solution on and running. You can validate this in the CoE Admin Command Center app.
image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/b3c10009-71af-4621-a044-18bc31afcf2c>

If that is the case, then yes your Makers will get a prompt to provide business justification for teams environments when they create them, and if they do not do so, they will get a reminder email, and then if they still do not respond, their teams environment will be deleted.

Here is another article on how to use the Microsoft Dataverse for Teams environment management solution area<https://learn.microsoft.com/power-platform/guidance/coe/teams-governance>

Please let me know if you still have a specific question after looking through here. Happy to iterate if I misunderstood your question.

―

**Comment by Jenefer-Monroe** [comment]
Please review this article. https://learn.microsoft.com/power-platform/guidance/coe/teams-governance

Business justification just means the reason they want to have a teams envt. 
They will put this reason here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2f4fc703-a3f4-4916-8b37-42422e3fd1e1)

If they do not respond in time their Dataverse for Teams environment is deleted from their Team. 
"In time" means a week. We check each week for D4T's created >= 7 days ago without business justification.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
