### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Helper - Cloud Flows Throttling

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#7941]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team, 

I'm experiencing throttling for this specific flow, **Sync Helper - Cloud Flows**. It says, "Your flow is running too many actions," which could lead to throttling and slowness. Could we please get some advisory on this. Is this a known bug? 

<img width="438" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/100535041/5c318bd9-8abd-412e-9b6d-50fcef0c5d15">

Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Sync Helper - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2672

**Comment by Jenefer-Monroe** [comment]
The cloud flow architecture depends on Power Automate flow to gather all the inventory from the tenant. This can be quite a lot of API calls for large tenants and even for medium sized ones for a first install. 

Can you please tell me
1. How many environments do you have in your tenant? 
2. How many cloud flows do you have in your tenant? 
3. Did you just install the kit? Or has it been running for a while?

**Comment by Pyksel** [comment]
We are also seeing this same issue in our tenant. Version 4.23 core
1. 17 including the CoE
2. 2700 flows
3. Installed into a new environment from the February 2024 version.

**Comment by Jenefer-Monroe** [comment]
OK the cloud flow system should be able to handle this then once initial inventory is complete. 

I suggest you do the following:
1. Turn off this flow: **_Admin | Sync Template v4 (Driver)_**
2. Wait for the API counts to drain. 
One way to check this is to wait for this flow (**_SYNC HELPER - Cloud Flows_**) to no longer have running flows. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0f409113-01d4-453d-a1f9-1e8ad55c74e2)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5dc31bd8-97cf-463b-81f2-13ebb2bb7657)

3. The next day after that completes, turn this flow back on: **_Admin | Sync Template v4 (Driver)_**

**Comment by Pyksel** [comment]
We walked through and executed the steps provided but this did not resolve it. Ultimately the SYNC HELPER - Cloud Flows flow was disabled due to throttling.

**Comment by Jenefer-Monroe** [comment]
Once the API calls drain you should be able to turn it back on.

**Comment by Pyksel** [comment]
Hi Jenefer, I should have mentioned that the flow had completed all its runs when this occurred again.

**Comment by Jenefer-Monroe** [comment]
Is the identity used to install the kit dedicated just to the CoE? Or is it used for other solutions as well? 

Can you please see what value you have for this env var? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dcd111e1-54be-46cb-9627-1c69e51c9eec)

**Comment by Pyksel** [comment]
Good day, the id that was used to install the CoE kit is an author or 1 or 2 flows but other than that, it's primary purpose is for the CoE.

The admin_FullInventory environment variable was set to yes so we've switched it to no.

**Comment by Jenefer-Monroe** [comment]
wonderful. You may need to reset all the flows that are dependent on the env var in order to ensure the new value comes through. To see what flows this would be you can go to the default solution > environment variables > show dependencies for this env var
Then used by > view the processes. Please restart those.

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/73da470b-5710-4523-9de1-7d93f33cf80f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7f500c56-5b37-4435-b9bd-aa103b99d9e5)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
