### ISSUE TITLE
Unable to save the environment variable for Audit Logs - Client Azure Secret  

### ISSUE THREAD

**Issue by hasanjamal21** [microsoft/coe-starter-kit#7942]
This variable didn't save properly. Could not verify the user permission on '/subscriptions/4dae279a-f0df-4055-912e-e10f2d082682/resourceGroups/shared-npd-westus2-coestarterkit-rg-01/providers/Microsoft.KeyVault/vaults/akv-wus2-npd-coekit-01/secrets/akv-wus2-npd-coekit-01-secret' resource. Make sure that Microsoft.PowerPlatform provider is registered in the Azure subscription.

AB#2694

**Comment by hasanjamal21** [comment]
We have updated the environment variable, and I was trying to turn on the flow like "Office 365 Management API Subscription" getting below error message.:

Turn on failed. Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ApiPolicyDataFlowViolation","message":"Admin data policy 'CoE Starter Kit Data Policy' restricts the use of /providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps with Http.","extendedData":{"violation":{"policyId":"/providers/Microsoft.BusinessAppPlatform/scopes/service/apiPolicies/06db7a03-6c9e-4709-908e-659c128a2385","policyDisplayName":"CoE Starter Kit Data Policy","type":"BusinessAndNonBusinessConnector","parameters":["/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps","Http"]},"additionalInfo":{}}}}".

**Comment by hasanjamal21** [comment]
Any update @

**Comment by Jenefer-Monroe** [comment]
Hello. This didn't get classified into a project so we missed it. Sorry about that. 
This reads as a DLP error. So you'll need to update the DLP that impacts the CoE Envt to allow HTTP and and Dataverse to be in the same bucket.

**Comment by hasanjamal21** [comment]
Hi Jenefer,

Please share more details, and could we do a remote session in your available time?

Hasan Jamal Siddiqui
Lead - SharePoint Online / Power Platform
Data & Information Management
Information Technology
Cell: 403.973.3012
***@***.******@***.***>
Calgary, Alberta
[Cenovus Energy]

**Comment by Jenefer-Monroe** [comment]
Hello. We are a very small team and note the CoE Starter Kit is an [unsupported set of templates](https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support ). As a result we are not staffed to meet with our GitHub users. 
However what you are struggling with is a product feature known as [Data loss prevention policies](https://learn.microsoft.com/power-platform/admin/wp-data-loss-prevention). So you'll need to find the policies that impact this CoE envt and update them as described above.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
