### ISSUE TITLE
[CoE Starter Kit - BUG] Invalid Character in admin_displayname - CoE BYODL Apps Dataflow

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#7943]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

CoE BYODL Apps Dataflow is erroring out due to an invalid character in the admin_displayname.

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/0c43f069-bb17-428a-b4fa-bdf3a92e35fc)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/abe549a1-75aa-4a74-9299-841de0506a30)

### Expected Behavior

Dataflow should validate normally and work. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

CoE BYODL Apps Dataflow

### What method are you using to get inventory and telemetry?

Data Export

AB#2673

**Comment by nasilvae** [comment]
We added a replace "\" with "" step in the admin_makers table inside the apps dataflow. Seems to be working but verifying right now.

**Comment by Jenefer-Monroe** [comment]
Please do let me know the character that you believe was causing issues so I can test locally. I have some special character test users and dont repro so would like to be able to see the issue locally before we make a change here.

**Comment by nasilvae** [comment]
> Please do let me know the character that you believe was causing issues so I can test locally. I have some special character test users and dont repro so would like to be able to see the issue locally before we make a change here.

I tried filtering the makers table in the dataflow and deleted the refresh history but I still get the same error after we reran the dataflows after clearing the dataflowrefreshhistory. 

the value is "\b"

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/10da7840-a628-4b74-8e52-c958db5087c9)

**Comment by Jenefer-Monroe** [comment]
Thanks we'll create a test user and explore to see if we can fix this up

**Comment by Jenefer-Monroe** [comment]
pushing to the FC for data export updates

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
