### ISSUE TITLE
AI Builder Consumption Report by Power App and/or Flow

### ISSUE THREAD

**Issue by bonniearmenda1104** [microsoft/coe-starter-kit#7944]
Hi, I am the technical manager for M365 Custom App Dev at WBD and recently we had an incident where we hit capacity with our AI Builder consumption.  The report that we were able to generate via PP Admin Center only provides usage by UserID.  I worked with Microsoft support (TrackingID#2403130040012766) and they suggested I open a ticket with you to see if this is something this team can build - a report on AI Builder Consumption by Power App and Power Automate Flow.  Going by UserID doesn't necessarily show us what app or flow the users might be using for the consumption.

Please contact me at bonnie.armendariz@wbd.com

AB#2695

**Comment by Jenefer-Monroe** [comment]
Hello. This didn't get classified into a project so we missed it. Sorry about that.
Good news, this feature has been worked upon for the upcoming April release: https://github.com/microsoft/coe-starter-kit/issues/6100

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
