### ISSUE TITLE
[CoE Starter Kit - BUG] Orphaned App / Flow spelling errors in Adaptive Cards

### ISSUE THREAD

**Issue by bwieland86** [microsoft/coe-starter-kit#7945]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Found a series of adaptive cards in the Orphaned App / Flow that have spelling errors. Rather than trying to correct these each release, can these please be quickly corrected?

![CoE Orphaned Flow Spelling Errors](https://github.com/microsoft/coe-starter-kit/assets/13457692/83af6521-3c64-46d5-8161-fa765c5a4910)

Additionally, it would be helpful to be able to store the adaptive card boilerplate text as environment variables that can be adjusted in the CoE Admin Command Center, just as the text for the emails are stored.

### Expected Behavior

Spelling and grammar of messages sent to users, managers, and admins is correct

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.14

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2675

**Comment by Jenefer-Monroe** [comment]
Can you please highlight the spelling errors in your screenshots?

**Comment by bwieland86** [comment]
Hi Jenefer, sure:

![CoE Orphaned Flow Spelling Errors](https://github.com/microsoft/coe-starter-kit/assets/13457692/2b5daff2-4798-4ee1-b2b9-b6c63e5bb34b)

**Comment by Jenefer-Monroe** [comment]
Thanks! With your help in spotting I fixed these all up for April release. Just in time! Also found one more spot with that same **_address_** mis-spelling

**Comment by Jenefer-Monroe** [comment]
Regarding having these be configurable like our emails are. This is on our backlog but its more difficult due to the format required here so its not likely to be funded in the near future.
Appreciate your help in spotting!
