### ISSUE TITLE
[CoE Starter Kit - QUESTION] Only CoE BYODL Makers is being refreshed. 

### ISSUE THREAD

**Issue by niwrejim21** [microsoft/coe-starter-kit#7947]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Would you know why only CoE BYODL Makers is being refreshed?

![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/ecb25764-1792-48f6-b2f5-4dcdacd60b1e)

Looking at the  flow "When Maker dataflow refresh is complete":

![image](https://github.com/microsoft/coe-starter-kit/assets/144838350/d896d014-f6a2-49ff-9c41-4c7c9a14f543)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2024 / 4.24

### What app or flow are you having the issue with?

Dataflow

### What method are you using to get inventory and telemetry?

Data Export

AB#2678

**Comment by Jenefer-Monroe** [comment]
Hello. Yes this is a known issue which is fixed for the April release targeting next week. Please see https://github.com/microsoft/coe-starter-kit/issues/7790

**Comment by Jenefer-Monroe** [comment]
closing out as a duplicate
