### ISSUE TITLE
CoE is showing 1300 apps as deleted but when checking the environments they're still there. 

### ISSUE THREAD

**Issue by saptarsibiswas** [microsoft/coe-starter-kit#7950]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

One of our customers is facing the issue where the CoE report says that 1300 Apps are deleted, however they are all System Owned CRM Apps present in Power Platform. 
Customer wants to know why this is showing like that in the CoE report. 
I am sharing the below information for your reference. 

Required information: 
- Which App is getting affected? Multiple System owned apps as shown in the report. 
Mainly Model driven Apps are there. 
- When does the issue appear? 16th March, however, only noticed yesterday.
- How did you delete the Apps? They were deleted automatically
- Are you able to see all the Apps in edit mode? Yes
- Are you able to play the Apps anymore. Yes
- Is this happening only in the specified Environment? No - All
- Org URL: removed for privacy
CoE report is attached. 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

NA

### What app or flow are you having the issue with?

Model Driven App. 

### What method are you using to get inventory and telemetry?

None

AB#2682

**Comment by Jenefer-Monroe** [comment]
Hello. I removed the org url for privacy as this is a public forum. 

Can you please tell me what version of the kit you are using. Specifically what version of Core components. And then are you using Data Export or Cloud Flow architecture?

**Comment by saptarsibiswas** [comment]
Let me check with customer that details and will share with you here and thanks for necessary action taken.

**Comment by Jenefer-Monroe** [comment]
Thank you, this will likely be quite a bit of back and forth so perhaps you can arrange to have access for a bit and we can iterate here together.

**Comment by JordanMcNamee** [comment]
Hi Jenefer - this is an issue I raised with MS. Happy to set up a call if it is easier to go through. To answer your first questions we are using cloud architecture for our CoE currently and I believe it is the August or September version.

**Comment by Jenefer-Monroe** [comment]
Sorry we are a very small team and this is not a supported product, rather a set of sample templates. We do our best to assist our GitHub users but are not able to take calls with our GitHub users as a result. 

We recommend upgrading at least every 3 months, please see [How often should you update the CoE Starter Kit?](https://learn.microsoft.com/power-platform/guidance/coe/after-setup#how-often-should-you-update-the-coe-starter-kit)

This kit is 8-9 months old as so as a result the first thing we will recommend is to do an upgrade. 
The March release is available and is a very reliable build for cloud flow architecture. And we will be releasing the April release next week. 

Please let me know if you have any questions.

**Comment by Jenefer-Monroe** [comment]
Makes sense. You can also try the product's [managed environments](https://learn.microsoft.com/power-platform/admin/managed-environment-overview) for out of the box administration capabilities. 
Or there are third parties that produce similar Power Platform governance tooling. 
I hope you are able to find what you need!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
