### ISSUE TITLE
[CoE Starter Kit - BUG] report dashboard query block, no data available

### ISSUE THREAD

**Issue by AlainCote** [microsoft/coe-starter-kit#7951]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi we seems to have difficulties trying to publish the Prodcution_CoEdashboard march 2024 with the following error. We check out this case #3467 (similar) and validate that we have data in that table, flow are running but we cannot open the dashboard no matter what. Any ideas ? We keep having this error saying that query are block because of null variable. COE is in place as far as we know. 

![Capture d’écran 2024-03-27 115437](https://github.com/microsoft/coe-starter-kit/assets/83082048/205ef537-f022-48e0-a382-eb3836285165)

### Expected Behavior

See the data available in CoE environment.  

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.3.2 march 2024

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Business Process Flows)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Open power BI desktop
2. Log in user with Tenant cred
3. Open the dashboard from unzipped folder
4. In the loading process, error occur. 

### Anything else?

n/a

AB#2683

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by AlainCote** [comment]
<img width="794" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/83082048/366e6c83-7907-4fca-8bf4-5d2c2db6fa00">

OMG ! i think i just understood, do we have to install the governance and nurtur component as well ? we want to proceed by step not deploying everything in the same time.

**Comment by Jenefer-Monroe** [comment]
No you should not need those for the **_Production_CoEDashboard_March2024_** PBIT file. 
Is this a clean install or an upgrade?

**Comment by Jenefer-Monroe** [comment]
Have you run through the setup wizard already?

**Comment by AlainCote** [comment]
Yes. Also checked in the list (CoE setup) that all essentials  flows are activated.

**Comment by Jenefer-Monroe** [comment]
Is there any error message in the list that is unique? Or do they all say that same error?

**Comment by AlainCote** [comment]
The only thing that i still have to do is to setup the environment variables. It's a test environment so i dont' want to disturb everybody. Not yet :)

**Comment by Jenefer-Monroe** [comment]
The required env vars should will be set for you with the setup wizard so that should be fine

**Comment by AlainCote** [comment]
> Is there any error message in the list that is unique? Or do they all say that same error?

All the same

**Comment by Jenefer-Monroe** [comment]
I've never seen this error before, including for clean installs that havent done an inventory yet. 
Let's just pick one then. Can you go to the PowerApps table, set it to show the columns as show here. Are there blanks in any of these columns? You can use the filter on each column to check
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9c74cc59-2ca5-4062-9df8-088e08ec1949)

**Comment by AlainCote** [comment]
Sry but i don't how create this view, it is a managed solution so i cannot add any columns. When o go to power apps | Tables i don't see any options to add a columns for a particular view ? 

<img width="940" alt="CoE bug" src="https://github.com/microsoft/coe-starter-kit/assets/83082048/eb02561a-3381-4adf-89f8-603f0dc3ea89">

**Comment by Jenefer-Monroe** [comment]
Go to Tables > All > PowerApps Apps
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/15f80904-4e3c-421d-80e0-d206421070f6)

Then hit edit to see all the data
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f5edbd09-6b77-4c79-be52-6dc3a18888fd)

Then you can change what fields you see by hitting the carrot shown here. And you can add and remove columns from this default view
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fafe2bf8-f9c8-4ddb-8717-a018a372e1fd)

**Comment by Jenefer-Monroe** [comment]
Once you have this view you can filter each column one by one to "Does not contain data", to see if there are records with nulls here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a060c055-0b49-48ed-a44b-4f59333d4767)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f56093db-9c89-457e-b314-2933bda6ffd2)

**Comment by AlainCote** [comment]
Wow tks did not know that., but no empty element 

<img width="729" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/83082048/6d4c9942-244b-49da-9c4b-8c9c9f156a79">

**Comment by AlainCote** [comment]
Tks for the trick but no empty element.

**Comment by AlainCote** [comment]
I am able to publish the dashboard but no data is visible 

![image](https://github.com/microsoft/coe-starter-kit/assets/83082048/6454efe9-8244-4607-9f77-25e3b7a26770)

But if i go to the power platform admin view inside the CoE i can see all my data 
![image](https://github.com/microsoft/coe-starter-kit/assets/83082048/6640e6c5-3321-4a91-80ab-3deecf66f241)

Could it be related to my licence ? I use a fabric licence (FREE). I think it is provided from our privilege because we are gold partner.

**Comment by Jenefer-Monroe** [comment]
I dont think its the PBI license. That should only impact if you can publish to a sharable workspace. 

Can you please try again? Making sure you

1. Use the correct PBIT file
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5dd8f3e5-56e2-4dd0-a4e8-c2afa349a144)

2. Enter the parameter with prefix and trailing slash
https://myorgenvturlhere.crm.dynamics.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5207061f-6923-4a07-92ae-aecf977e783e)

**Comment by AlainCote** [comment]
WORKING ! Super tks :)

<img width="722" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/83082048/f9b757eb-cccd-43f8-8be4-4e25fad6e7bf">

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thanks for sticking with it!

**Comment by Jenefer-Monroe** [comment]
Will go ahead and close now that we are resolved. Thanks for using CoE Starter Kit!

**Comment by fannazephyr** [comment]
Hi Jenefer, i am having same error, isee no data as well. i am using April pbit file.
![1](https://github.com/microsoft/coe-starter-kit/assets/160732775/e44696e8-9816-4b8b-bbed-70eaf1f10e34)
