### ISSUE TITLE
[CoE Starter Kit - BUG] New environments are being inventoried even though admin_isFullTenantInventory variable is set to False

### ISSUE THREAD

**Issue by dteggmoh** [microsoft/coe-starter-kit#7953]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have a similar scenario as Question #5747 where we want to exclude certain environments that have previously been scanned (e.g. CoE Toolkit environment) & remove their App/Flow inventory from Dataverse).
We followed steps in https://learn.microsoft.com/en-nz/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments by setting admin_isFullTenantInventory environment variable to false and then ensuring valid environments are set as not excused from inventory.  Then we deleted the certain environments we wanted to exclude, from the environments table.
We then rant the Delete Bad Data Flow, which did remove the App/Flow inventory from the respective Dataverse tables and all was ok at this point.

The issue arose when the "Admin | Sync Template v4 (Driver)" Flow next ran & as expected it added those environments that we'd deleted from the Environments table, however it did not set the "Excuse From Inventory" flag to True.

After digging in to the Flow, noticed that near the bottom of the Inventory Management Scope, it has a condition to "See if need to add to inventory" where if "is_New_Envt" = true OR "Excused_From_Inventory" = false.  That seemed ok under Run History for these environments as they were detected as "New", so it then dropped down the left hand side (YES) 
![Issue with Starter Kit 28 March](https://github.com/microsoft/coe-starter-kit/assets/162236883/9eb5b059-ba73-4884-9ca7-c496ec573b18)
& then for the "Upsert Environment" action it sets the properties of the Environment.  We noticed that setting the "Excuse from Inventory" field in this action is blank.  Which then causes the subsequent Sync Template Flows to run and inventory all that Environments assests.
![Issue with Starter Kit 28 March B](https://github.com/microsoft/coe-starter-kit/assets/162236883/01a253f9-30e7-4d4d-b21a-8d267cc5885c)
You can then repeat the steps above to remove the data but it comes back due to what we see as a bug.

We modified the Flow & for this "Excuse from Inventory" field in this action, we set it to outputs('Excused_From_Inventory') which is a variable that's set earlier in the Flow.  This seemed to solve the issue for us, as after cleaning up again, when the "Admin | Sync Template v4 (Driver)" Flow ran, it didn't inventory the environment, because the "Excuse from Inventory" field was set from the get go.  Obviously this creates an Unmanaged Layer, so hoping this can be addressed in a future release (if confirmed as a bug).

Let us know if you need any further information.
Thanks

### Expected Behavior

When admin_isFullTenantInventory is set to False, new environments should have "Excuse from Inventory" set to False by Flow "Admin | Sync Template v4 (Driver)" to ensure the environment is not scanned

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Mentioned is issue description

AB#2687

**Comment by Jenefer-Monroe** [comment]
Yes thank you so much for posting! It seems I forgot to put that value in the upsert when I redid these flows to v4. SORRY! And thank you for confirming. That is the fix I would do too: 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c0ff7874-9bb8-4893-9c2b-a0e45a315466)

Can you confirm this is the change you made? 
I'll test to make sure this works for the general case as well but its clearly why I made that compose output and then just lost it. 

Assuming my testing works, and you confirm this is the change you made, then I will be able to patch for April release (just in time!)

**Comment by Jenefer-Monroe** [comment]
Local fixed for April.

**Comment by dteggmoh** [comment]
No problem Jenefer - yes that's how we fixed it 😀

Also do you know if there's a way to schedule this main Sync Flow for a certain time of day, other than editing and creating an Unmanaged Layer?
Thanks
