### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Gather Tenant SRs Flow fail

### ISSUE THREAD

**Issue by Fadel1949** [microsoft/coe-starter-kit#7954]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Gather Tenant SRs fail 
Error Detail 
The Dynamics 365 organization you are attempting to access is currently disabled.  Please contact your system administrator
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/8475a32f-0476-44ac-a632-deffd06dbcff)

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/ea8e3fc1-67a5-4ff7-a68f-0ad907c4ba92)

### Expected Behavior

Admin | Gather Tenant SRs fail not found !
Error Detail 
The Dynamics 365 organization you are attempting to access is currently disabled.  Please contact your system administrator
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/8475a32f-0476-44ac-a632-deffd06dbcff)

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/ea8e3fc1-67a5-4ff7-a68f-0ad907c4ba92)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Gather Tenant SRs

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Admin | Gather Tenant SRs fail not found !
Error Detail 
The Dynamics 365 organization you are attempting to access is currently disabled.  Please contact your system administrator
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/8475a32f-0476-44ac-a632-deffd06dbcff)

![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/ea8e3fc1-67a5-4ff7-a68f-0ad907c4ba92)

AB#2688

**Comment by Jenefer-Monroe** [comment]
Hello. Thanks for posting. This is a known integration bug with Managed Environments.
We have local fixed this area generally for April, including for this flow. 
Please see https://github.com/microsoft/coe-starter-kit/issues/7846

**Comment by Jenefer-Monroe** [comment]
Will go ahead and close as a dupe
