### ISSUE TITLE
Version 4.24 Still not showing number of Flows correctly

### ISSUE THREAD

**Issue by RosThom** [microsoft/coe-starter-kit#7956]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have updated to version 4.24.
The number of flows is still not showing correctly - is anyone else seeing this issue?
We use Data Export and I have implemented change from #7790 so refreshes now OK.  I have deleted refresh history. Have I missed something?
Thanks
Ros

### Expected Behavior

PPCoE is showing that we have only 29 flows between all environments.  We know we have thousands.  Uncertain why these are not showing.
Powerapps are showing correctly as far as we can tell.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

PBI refresh

### What method are you using to get inventory and telemetry?

Data Export

AB#2690

**Comment by Jenefer-Monroe** [comment]
Are all your dataflows running and passing? 
And do you have "Next refresh" set only for Maker as expected?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6f46ea76-1f81-4dba-a74c-90e7c1543e19)

**Comment by RosThom** [comment]
Yes - all as expected.
![image](https://github.com/microsoft/coe-starter-kit/assets/148232935/b5e70fb5-78f2-4cab-b2d5-ba26ffb9dcc6)

**Comment by Jenefer-Monroe** [comment]
Are you sure you deleted the history for flows? If you use the Command Center to delete them, it will remove all back some number of days. I ask because it seems like the flows dataflow ran very quickly, implying it did not have much to process. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6a7e5cc0-6241-48b7-a5a2-8bcda347fee8)

**Comment by Jenefer-Monroe** [comment]
Actually I just looked in my storage account and I'm missing some envts. Can you go look? 
Get the Envt ID for your default envt
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1b7ff86c-43db-4d49-afd6-9a9d635f9139)

Go to your storage account > Storage browser > Blob containers > powerplatform > powerapps > applications > Search for this GUID. 
Do you find it? Please do the same for flows as well. 
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/72252993-1414-4ec5-8918-c68b755de7cb)

**Comment by RosThom** [comment]
Hi,
I checked my deletion of refresh history and this is as expected - no files from before 28/03 when I deleted history.
I have also checked the storage account and can see the default environment in both powerapps and powerautomate folders.

**Comment by Jenefer-Monroe** [comment]
Please go to the Datalake and find the flow file for an environment where you expect to see flows but do not. 
You can do this by going to the Storage Browser and searching for the GUID of the envt
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/160575cf-225f-4d31-b7db-88fc079f3ed7)
### Question 1: What is the last modified date shown for the file? 
Next please click on the file and download it to view
### Question: 2 Is the file formatted like image 1 with a single line per flow or like image 2 with a jumbled look?
**Image 1 : Well formatted**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dbf210ec-8544-4e82-a03e-e6196f0685fc)
**Image 2 : Not well formatted**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/589de3df-db6c-4101-ba16-05fd530c56c0)

**Comment by RosThom** [comment]
Definitely jumbled

**Comment by Jenefer-Monroe** [comment]
OK unfortunately this is a product issue then. You will need to contact product support and have them do what they call a "full inventory run" on your Data Export files.

**Comment by RosThom** [comment]
Thanks for your help.  How do I contact Product support? Do I raise a Microsoft support case through the portal?  Or is there a different procedure for Centre of Excellence?

**Comment by Jenefer-Monroe** [comment]
Yes you are correct, you raise it there. The CoE is just a consumer of this product feature. The data in the datalake is written by the product itself and so thats why you will raise the issue with product support.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
