### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to remove deletes objects from inventory

### ISSUE THREAD

**Issue by bethleota** [microsoft/coe-starter-kit#7957]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

This is a follow-up to this question - https://github.com/microsoft/coe-starter-kit/issues/7622. I've deleted a lot of flows and apps over the last 4 months. For Flows, I typically use PowerShell to assign myself as the owner and then to the Flow and delete it. For Apps, I've used either PowerShell Set App Permissions app to assign myself as owner, then go to make.powerapps.com and deleted them. It seems many of these that I've deleted still show up in PBI report like App Deep Dive > App Details. Do I need to turn ON additional flows? I've been searching this github to find documentation, but I'm lost.
![PPCoE-CloudFlows](https://github.com/microsoft/coe-starter-kit/assets/40639953/a2d9c483-0a8b-4721-9a42-63977c16fe40)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Feb 2024

### What app or flow are you having the issue with?

Admin - Sync Template v4

### What method are you using to get inventory and telemetry?

Data Export

AB#2691

**Comment by Jenefer-Monroe** [comment]
Yes it looks like you dont have all the inventory flows turned on. 
It's highly recommended that you use the setup wizard to turn on features, as well as you configure the kit after installs / upgrades. 
This will ensure all new flows are on and env vars are configured.

To use it, first perform the import of the solution install or upgrade manually, then boot the app and walk through the screens.
The "Initial Setup" screens will get you the inventory system configured, including the "Check Deleted" system to remove deleted objects from inventory. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b84cc1ff-383a-497c-9236-569e8313c73c)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed02f0d0-c276-48cc-90af-47e5bf5a928e)

At other times you can also use the Command Center to be sure that all the flows for a particular area are turned on. Here for example you can see the flows needed for the Inventory system. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8ead242f-c429-421b-b53d-708c3984cd2c)

**Comment by bethleota** [comment]
Hello Jenefer,
Thanks for providing the screen shots. I've been using the Setup Wizard when I run updates to the CoE. The Feb 2024 update was the first one where I noticed the "Check Deleted" system to remove deleted objects from inventory and I am certain I checked it (I think it was toggled on by default and I left it on). The last update I ran before that was Oct 2023 so I was behind. Perhaps if I install March or April 2024 CoE, it will pick up these flows. 

Warm regards,
Beth

**Comment by bethleota** [comment]
Sure - here it is.
![CoESolutions2024-03-29](https://github.com/microsoft/coe-starter-kit/assets/40639953/95ac0a94-126e-402d-87ad-e00924d6ca1c)

**Comment by Jenefer-Monroe** [comment]
No the setup wizard should turn these all on for you. 
In the Feb release we had both the old (v3) versions of these and the new (v4) versions. And I think the setup wizard may have messed up in configuring them correctly. 
The new releases this is no longer the case as the V3's are gone. 

### Turn off these
So please go **_turn off these flows_** if they are on:
CLEANUP HELPER - Check Deleted (Ai Models)
CLEANUP HELPER - Check Deleted (Business Process Flows)
CLEANUP HELPER - Check Deleted (Canvas Apps)
CLEANUP HELPER - Check Deleted (Cloud Flows)
CLEANUP HELPER - Check Deleted (Custom Connectors)
CLEANUP HELPER - Check Deleted (Model Driven Apps)
CLEANUP HELPER - Check Deleted (PVA)
CLEANUP HELPER - Check Deleted (Solutions)
CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Turn on these
And **_turn on these flows_** in the order shown.
CLEANUP HELPER - Check Deleted v4 (Ai Models)
CLEANUP HELPER - Check Deleted v4 (Business Process Flows)
CLEANUP HELPER - Check Deleted v4 (Canvas Apps)
CLEANUP HELPER - Check Deleted v4 (Cloud Flows)
CLEANUP HELPER - Check Deleted v4 (Custom Connectors)
CLEANUP HELPER - Check Deleted v4 (Desktop flows)
CLEANUP HELPER - Check Deleted v4 (Model Driven Apps)
CLEANUP HELPER - Check Deleted v4 (Portals)
CLEANUP HELPER - Check Deleted v4 (PVA)
CLEANUP HELPER - Check Deleted v4 (Solutions)
CLEANUP - Admin | Sync Template v4 (Check Deleted)

**Comment by Jenefer-Monroe** [comment]
The v4's will mark the object as deleted and then remove it after some time (enough time to restore in the event you restore the actual object). So please do also look at the "app deleted" type columns in all the objects to see if its flagged but not yet removed. 

Then note one more thing, there is a rarely used env var to never remove these objects from inventory, they woudl just sit forever marked as deleted if you've set this env var to no.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/08093832-83ed-48ac-ba46-2239a2cb92b8)

**Comment by bethleota** [comment]
Hi again. From what I can tell, my CoE flows and Env Var match what you have.
![CoEFlows2024-03-29](https://github.com/microsoft/coe-starter-kit/assets/40639953/12b43c81-3948-437c-a34e-e775e54694d0)
![CoE EVadminDeleteFromCoE2024-03-29](https://github.com/microsoft/coe-starter-kit/assets/40639953/fe66bb4b-fa20-4d85-a8c9-d66217695040)

**Comment by Jenefer-Monroe** [comment]
Is the CLEANUP - Admin | Sync Template v4 (Check Deleted) flow running and passing?

**Comment by bethleota** [comment]
Yes. 
![CoECleanupFlow2024-03-29](https://github.com/microsoft/coe-starter-kit/assets/40639953/947d676a-7c80-4538-aab6-7df6e89f2682)

**Comment by Jenefer-Monroe** [comment]
Can you show me an example of an app where you expect it to be deleted but its still in the inventory? What is its value in the AppDeleted column? 
And when did you do the delete? 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/23bb7af3-f706-43da-b04e-f001f87975c7)

**Comment by bethleota** [comment]
Hi again. Thank you SO much for all your help. I checked several apps I had deleted in December '23 or had tried to. It appears all the canvas apps I deleted are removed from dataverse. The only ones remaining are SharePoint List forms that are "un-deletable" - meaning the list itself or the site where the list was located has been deleted or removed. I apologize for taking up your time as all is working as it should.  See example. Is there a way to remove these from dataverse? PowerShell doesn't work like it does with canvas apps and I can't get to List Settings in SharePoint since the lists are gone.
![PowerApps Apps Deleted 2024-03-29](https://github.com/microsoft/coe-starter-kit/assets/40639953/f9b3aa2d-c804-4b38-9aa0-4eccebdb0f54)

**Comment by bethleota** [comment]
Hi there. One more quick thing. Is this Flow DV table the one I should check to confirm flows I've deleted either using PoSh or UI get removed from inventory? Like the PowerApps Apps DV table you included in screen shot above?
![Flow-DVTable2024-04-02](https://github.com/microsoft/coe-starter-kit/assets/40639953/8fddc5df-9296-465d-ad72-53d7b05e83c3)

**Comment by Jenefer-Monroe** [comment]
Correct that is the table where we store the flows from inventory.

**Comment by bethleota** [comment]
Thank you. I'm going to Close this thread as you have answered my questions and helped immensely. Thank you!!!

**Comment by bethleota** [comment]
Thank you. I'm going to Close this thread as you have answered my questions and helped immensely. Thank you!!!
