### ISSUE TITLE
Admin | Sync Template v3 (Flow Action Details) fails

### ISSUE THREAD

**Issue by qxaziz** [microsoft/coe-starter-kit#7960]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The Admin | Sync Template v3 (Flow Action Details) flow is failing. Below is the screenshot:

![image](https://github.com/microsoft/coe-starter-kit/assets/30298848/a599d99e-5c82-4118-914f-59228d1f8790)

Please advise how to resolve this error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CoE version 4.23

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2697

**Comment by Jenefer-Monroe** [comment]
Hello. You will need find the failing call and get me the specific error message from the output. 
My guess is that it is failing on this parse. Can you please find it and let me know what the error says? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c93ff453-8757-4101-ad52-a67ec574ccb8)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
