### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync template v4 (Security Roles) does not handle apostrophe in French names

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#7961]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Some instances of our Admin | Sync template v4 (Security Roles) flow are failing. The action that fails is "Find this users records - still unknown" and the error message goes as following : "There is an unterminated literal at position 101 in 'admin_name eq <user_name> and _admin_environment_value eq <env_guid>." The only thing that is different with this user is that her last name uses an apostrophe (french name)

### Expected Behavior

Expected behavior is to handle special characters in names, like apostrophes. We are a canadian company with a large number of french employees, so this aspect is important for us. 
Also, I'm thinking it shouldn't filter by the admin_name column but rather by a guid identifier in that table.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Security Roles)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2698

**Comment by Jenefer-Monroe** [comment]
Hello. We have two issues tracking this. 
The first, and the one impacting you, is covered by https://github.com/microsoft/coe-starter-kit/issues/7884 and local fixed for April release. 
The second is https://github.com/microsoft/coe-starter-kit/issues/7958 and will target May release.

**Comment by VanIsleCA** [comment]
Sounds great, thanks for letting me know,

**Comment by Jenefer-Monroe** [comment]
You bet! Please do consider adding a watch to https://github.com/microsoft/coe-starter-kit/issues/7958 so that when I put the solution in there for testing you can take a look.

**Comment by Jenefer-Monroe** [comment]
closing out as a duplicate
