### ISSUE TITLE
[CoE Starter Kit - QUESTION] Changing Flow Main Owner does not Update the Maker during the Sync Flow

### ISSUE THREAD

**Issue by ValentinMaz** [microsoft/coe-starter-kit#7964]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

- After changing the main owner of a Cloud Flow, it seems like the "SYNC HELPER - Cloud Flows" flow is not picking up the change. The "Maker" and "Derived Owner" columns of the CoE Flow table row remain unchanged.
- The same test with the Canvas Apps works as expected. After changing the main owner of the App, the "SYNC Helper - Apps" flow picks up the change and updates the App Owner column in the CoE App table.
- I assume it is because the "Creator" property that we get from the "Get Flow as Admin" action is not updated when the main owner of a flow changes

Just a thought: maybe instead of taking the Flow Creator information, the SYNC Helper flow could make use of the action "Get Flow Owner Role as Admin" from the Power Automate for Admins connector? This way it could identify the current Owner by filtering the body/value to keep the user with properties/rolename = Owner? This could then be updated in the Flow CoE Kit table

I understand this might be related to https://github.com/microsoft/coe-starter-kit/issues/3052 and could be released in April/August?

Many thanks for the confirmation and all the work you do.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2701

**Comment by Jenefer-Monroe** [comment]
Hello, we have not yet updated the kit to use the information from changing the owner in the product but it is on our backlog. We are waiting for one more product change and then will fund this work. Please see [[#3052](https://github.com/microsoft/coe-starter-kit/issues/3052)]( https://github.com/microsoft/coe-starter-kit/issues/3052)

In the meantime you likely want to set it in both places. In the product so that its correct from the product pov (the most important piece) and then in the kit so that the processes can see it.

Sorry for the inconvenience.

**Comment by ValentinMaz** [comment]
Hello @Jenefer-Monroe , thanks for clarifying. My understanding is that we then need to update three properties in the admin_flow table, do you see something else which would need an update as well?
- DerivedOwner
- Maker
- Maker DisplayName

One last question... What is the use of DerivedOwner?

Many thanks!

**Comment by Jenefer-Monroe** [comment]
You dont need to update Maker. That is the creator and should not change from within the flow. 

Derived owner is the concept we created becuase for years you could not update a flow owner. So we added this column. 
Now that the product supports setting this property we will be able figure out how to reconcile but we have not yet. 

So its derived owner that you will want to backfill.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
