### ISSUE TITLE
[CoE Starter Kit - BUG] AggregateQueryRecordLimit

### ISSUE THREAD

**Issue by KiraXie2** [microsoft/coe-starter-kit#7965]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

No data returned in the custom page "Manage Permissions - Environment Security Role Users" in the model-driven app "Manage Permissions". Why this issue happens and how to resolve this issue? Does it mean this is not suitable for enterprise as there are too many records?

### Expected Behavior

The data can be shown in the model-driven app "Manage Permissions" correctly and without errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Manage Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the model-driven app, the error shows like:
<img width="913" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/108067225/06d593b9-7f46-47fa-b705-30353373995d">
Open the custom page in the model-driven app, and the error shows like:
<img width="721" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/108067225/6bf70bfd-be88-44e0-ab6e-b54b28ac6b28">

AB#2702

**Comment by Jenefer-Monroe** [comment]
Hi there. This issue was just do the pagination technique we employed. 
We have resolved this issue in the May release by changing the pagination to just say 50,000+ when your record set is too large, and then displaying the data.

**Comment by Jenefer-Monroe** [comment]
closing out as this release is now available.
