### ISSUE TITLE
[CoE Starter Kit - QUESTION] PowerApps  report does not remove deleted Apps.

### ISSUE THREAD

**Issue by anilkumar1575** [microsoft/coe-starter-kit#7966]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

PowerApps report still shows SharePoint Form Apps even after deleting /removing customization on SharePoint list form.
Is it by design or how to refresh PowerApps report?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin Sync v4

### What method are you using to get inventory and telemetry?

None

AB#2703

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately this is a known product limitation in that there is no way to remove these once the list is deleted. 
Please see https://github.com/microsoft/coe-starter-kit/issues/6493

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
