### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by ArunimaTalukdar** [microsoft/coe-starter-kit#797]
### Describe the issue

Not able to see owner names in "Apps" page in Power BI report, we only see owners represented as for the Default environment "SYSTEM".

### Expected Behavior

"Owners" field should show usernames instead of "SYSTEM"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

None

**Comment by JeneferM-MSFT** [comment]
looks to be the same issue as #784 
Can you confirm?

**Comment by JeneferM-MSFT** [comment]
#
Duplicate of #784
