### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow Admin | Gather Tenant SRs needed?

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#7971]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 

is the Flow Admin | Gather Tenant SRs, I can not find a documentation on this flow.
Could you please update the set up instructions wilth all new flows? THis wpuld be very helpful.
<img width="501" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/62603605/df0a38a2-01a5-4f71-8339-04d16012568b">

Kind regadrs
Caddy

### What solution are you experiencing the issue with?

None

### What solution version are you using?

March 2024

### What app or flow are you having the issue with?

Admin | Gather Tenant SRs

### What method are you using to get inventory and telemetry?

None

AB#2717

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry we are a very small team and so have not been able to fund our documentation recently. 
Will mark as a documentation bug for us which we can hopefully fund soon.

**Comment by Cathi029** [comment]
Hello, so should the specific Flow mentioned above be activated or not necessarily?
