### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Security Roles) Syntax Error

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#7972]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Syntax error at position 22 in 'admin_name eq 'J'nelle Lawrence' and _admin_environment_value eq 123-123-1234-123698'."

![image](https://github.com/microsoft/coe-starter-kit/assets/110540273/38602c2f-d21a-44a1-946b-08c98b7fcce5)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Security Roles)

### What method are you using to get inventory and telemetry?

Data Export

AB#2718

**Comment by Jenefer-Monroe** [comment]
Hello. This is covered by https://github.com/microsoft/coe-starter-kit/issues/7884 and fixed for the upcoming April release.

**Comment by AkashPatel136** [comment]
Great, Thank You @Jenefer-Monroe
