### ISSUE TITLE
[CoE Starter Kit - BUG] Missing prerequisite - Compliance Process Setup Wizard

### ISSUE THREAD

**Issue by ShanujPatel-DMs** [microsoft/coe-starter-kit#7974]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, 
I followed the guide and setup a new install of the core solution and followed the steps to setup the inventory process. However, after importing the Governance solution - CenterofExcellenceAuditComponents_3.16_managed
I get the following error when trying to use the setup wizard:
![image](https://github.com/microsoft/coe-starter-kit/assets/116726185/fd62820a-9de6-427b-aa54-4f1810aca9d8)

However, there is only a V4 version of the flow.
![image](https://github.com/microsoft/coe-starter-kit/assets/116726185/1d11a042-9a18-4cdd-b5c6-ca3ca040b77b)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.16

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver) / Admin | Sync Template v4 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Install Core Solution and setup
2. Install Governance Solution
3. Attempt to use setup wizard to setup the solution
4. Error should appear.

AB#2720

**Comment by ShanujPatel-DMs** [comment]
Thanks @RahulBojji , Apologies it did not show up when I searched for similar tickets.
Thanks

**Comment by Jenefer-Monroe** [comment]
closing out as a duplicate
