### ISSUE TITLE
[CoE Starter Kit - BUG] Error on opening Setup and Upgrade Wizard

### ISSUE THREAD

**Issue by uillia** [microsoft/coe-starter-kit#7978]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We'v instaled the Center of Excellence - Core Components and start the CoE Setup and Upgrade Wizard to begin the process but we got this error:

Error Code: AppForbidden
Session Id: 3acd266f-0fb4-42a6-8363-4150ec830093
Activity Id: 0162c880-fa83-46e3-8271-0c3422b17284
Timestamp: Tue Apr 02 2024 11:53:05 GMT-0300 (Horário Padrão de Brasília)
The user with object id '' does not have permission to access this.
UciError: The user with object id '' does not have permission to access this. at s (https://content.powerapps.com/resource/uci-infra/scripts/app.f7835d832416bb14d3872bf96aff17d2.js:33:962243) at https://content.powerapps.com/resource/uci-infra/scripts/custompage.f27bc5629f6152d6fd69d4a5e0ae288f.js:4:24677

### Expected Behavior

CoE Setup and Upgrade Wizard works

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

CoE Setup Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1 - In enviroment CoE, Go to solutions
2 - Enter in solution Center of Excellence - Core Components
3 - Start Setup and Upgrade Wizard
4 - The error happens

### Anything else?

The type of Enviroment is SandBox e the default language are English.

AB#2725

**Comment by Jenefer-Monroe** [comment]
Are you logging in as the user identity that installed the kit?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
