### ISSUE TITLE
[CoE Starter Kit - QUESTION] Manage reference connection

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#7981]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 
Is there a view available on PPf Admin tools that list all reference connection that are orphan ? If i delete a solution that contains reference connexion, and if i check connection reference table the connection are still there 😱

Maybe an app like Manage Permission but for connection reference will be very useful ? What do you think ?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Core - 4.24

### What method are you using to get inventory and telemetry?

None

AB#2728

**Comment by Jenefer-Monroe** [comment]
Hello. Well timed question. The April release has a new set of functionality around connections, including the orphaned ones: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/938eff13-bd12-4101-a1a0-cf3c0386b86e)

Then you can click one to open a tool to mananage it
Here to show you a screenshot of the type of exploration you can do in that app, and then remove connections
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/94bc3037-59d6-49ce-8c0c-5591d3adecde)

**Comment by Jenefer-Monroe** [comment]
You can certainly say that, I appreciate the kind words :)

**Comment by Jenefer-Monroe** [comment]
closing out as this release is now available.
