### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoEDashboard 

### ISSUE THREAD

**Issue by Fadel1949** [microsoft/coe-starter-kit#7982]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

1.What does "Custom pages" mean? Are they Power pages?
2.Does "Component libraries" refer to the components that are imported into the Solution?
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/de8dd98d-8d39-4748-b3e4-bccb6a4e6a09)

4.For Power Apps Adoption MOM, why is it 0.00% across the board? Is a 0% normal? What does it mean?
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/144b4663-f1e6-48c7-893d-05c116e5fa50)
5.Why is "Maker YoY" blank? Is it only for one year? Why isn't there data for previous years? Is there a reason?
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/e51bf376-ce0d-4cda-8a20-d53558827f0a)
6.What does "Grandfathered apps" refer to in terms of quantity?
![image](https://github.com/microsoft/coe-starter-kit/assets/126840838/f6105454-6f28-490d-950b-500604fa85c3)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2729

**Comment by Jenefer-Monroe** [comment]
In the future please address with a single question per issue posted. It gets very difficult to manage any back and forth for multiple issues. 
Please do let me know if the below helps. 

### 1.What does "Custom pages" mean? Are they Power pages?
### 2.Does "Component libraries" refer to the components that are imported into the Solution?
These are objects classified as "canvas" in the data sources which do canvas type things in the Model Driven App world. 
You can learn about them here: [Component Libraries](https://learn.microsoft.com/power-apps/maker/canvas-apps/component-library), [Custom pages](https://learn.microsoft.com/power-apps/maker/model-driven-apps/page-canvas-components)

### 4.For Power Apps Adoption MOM, why is it 0.00% across the board? Is a 0% normal? What does it mean?
It means you've not had any growth yet this month, that is normal at the start of the new period yes. 

### 5.Why is "Maker YoY" blank? Is it only for one year? Why isn't there data for previous years? Is there a reason?
New-Maker is based on when maker was added to the Maker table so likely you generated the kit this year? 

### 6.What does "Grandfathered apps" refer to in terms of quantity?
This is a legacy concept from the product team regarding licensing. You will likely need to work with your account rep or product support to discover your specific case. [Grandfathered apps](https://learn.microsoft.com/power-platform/admin/powerapps-flow-licensing-faq#how-does-the-change-to-power-apps-and-power-automate-use-rights-for-microsoft-365-applications-affect-me-if-i-purchased-the-subscriptions-prior-to-oct-1-2019-will-my-existing-apps-and-power-automate-workflows-continue-to-work)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
