### ISSUE TITLE
[CoE Starter Kit - QUESTION] Developer Compliance Center stuck having System Admin security role, cannot remove. Does this affect Makers' access?

### ISSUE THREAD

**Issue by Secretss7** [microsoft/coe-starter-kit#7984]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

**Situation**
I took over the CoE toolkit so I don't know what happened before during set up. The Developer Compliance Center MDA has the roles
- Power Platform Maker SR
- System Administrator
- Basic User
- System Customizer

In the share list, there are 5 entries:
- the Microsoft Entra ID group of CoE Admins (this group has the System Administrator role)
- the 4 people inside that group (who have inherited the System Administrator role)

**Problem**
I have tried removing the System Administrator role from the MDA but it keeps coming back. I then switched to Classic to remove the role that way, but it also keeps coming back. (I switched to Classic by going to https://[environmenturl].crm6.dynamics.com/main.aspx?settingsonly=true)

I haven't created the Microsoft Entra ID group for Makers yet but that is on my agenda. I understand I will give the Makers group the Power Platform Maker SR role. They obviously will not and should not have the System Administrator role. But the MDA has it and is stuck with it. 

**Questions**
1. As a general question for MDA access: Do my app users need to have every role - that is assigned to the app - to be assigned to themselves too? Will this issue prevent my makers from using the app? 
2. Or worse, will adding my Maker group to the share list inevitably assign the System Administrator role to the group and hence all my makers?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

October 2023

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2731

**Comment by RahulBojji** [comment]
@Secretss7 That's the behaviour of Model driven apps, by default those will be accessible by users who has System Administrator or System Customizer role

The users with whom the app is shared might need not have all the privileges. User need to have either of those roles to access the app. For example this user has only Power Platform Maker SR assigned to him but he is able to access the Developer Compliance Center App. 

<img width="420" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/c7609a0f-07e5-4ed2-96b9-4eb05a7c72e1">

<img width="955" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/bea8a487-89a8-41f1-92f3-76214e87afc7">

**Comment by Secretss7** [comment]
Thank you! I wasn't sure if it was someone else before me who added the System Administrator role to the Developer Compliance Center app. Good to know it was already like that by default!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
