### ISSUE TITLE
What is the reason why Power Platform admin SR is needed?

### ISSUE THREAD

**Issue by Sasae528** [microsoft/coe-starter-kit#7986]
I do not speak English well, so my sentences may not be correct as English. Please understand.

Most of the Apps shared to Admin personas included in the CoE starter kit use admin connectors such as PowerPlatform for Admins.
To use these administrative connectors, we must have PowerPlatform administrator privileges, but if we grant PowerPlatform administrator to our accounts, they will be granted System Administrator privileges on Dataverse.

According to the Micrpsoft documentation, the App to be shared to the Admin persona should be granted Power Platform admin SR, but it is recognized that all operations can be performed with System Administrator privileges. In other words, there seems to be no point in granting Power Platform admin SR.

What is the reason why Power Platform admin SR is needed?

AB#2745

**Comment by RahulBojji** [comment]
@Sasae528 Power Platform Administrator Privilege and Power Platform Admin SR are two different things. If you have Power Platform Admin Privilege you will have System Administrator role on all the environments in that particular tenant. But if you have Power Platform Admin SR you will be having limited privileges on the environment that the user is part of, and this role is not as same as System Administrator. All the admin connectors will run under the user who has System Administrator Privileges not the Power Platform Admin SR. 

Hope this answers your question

**Comment by Sasae528** [comment]
Thank you for your response.
I understand that Power Platform Administrator Privilege and Power Platform Admin SR are different and that Power Platform Administrator Privilege is a higher level privilege.
However, if that is the case, isn't Power Platform Admin SR completely unnecessary?
Will deleting the Power Platform Admin SR have no effect?

**Comment by Sasae528** [comment]
@RahulBojji 
Thank you for your response.
Are you saying that you intend that Power Platform Admin SR is necessary to grant access rights to each app included in the COE kit?
However, by granting Administrator Privilege, System Administrator role is also granted to each app, so it should be possible to access each app with only Administrator Privilege.
In other words, Power Platform Admin SR should not be necessary in terms of granting access rights.
What do you think?

**Comment by RahulBojji** [comment]
@Sasae528 Every security role we create is a subset of System Admin role. Here as well the operations that users with Power Platform Admin SR does will be for sure be able to do with System Admin role as well but it doesnt mean for everything we use sys admin role. In the COE kit, we use sys admin role only for fetching and creating the inventory. Please [this](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#how-will-you-communicate-with-your-admins-makers-and-users) and [this](https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components#security-roles) for more information. We create custom roles to restrict the access to data. Please use [this](https://learn.microsoft.com/en-us/power-platform/admin/security-roles-privileges) for more info on security roles

**Comment by Sasae528** [comment]
@RahulBojji 
> In the COE kit, we use sys admin role only for fetching and creating the inventory.
You say that the COE kit has limited use of the admin role, but [this article](https://learn.microsoft.com/ja-jp/power-platform/guidance/coe/core-components#security-roles) states that all PowerApps apps for admin require the admin role.

・CoE Admin Command Center
・DLP Editor v2
・Set App Permissions
・Set Flow Permissions
・Power Platform Admin View
・Admin - Environment Requests
------
Permission: Intended to be used only by admins. Power Platform Service Admin or Global Admin permission is required. Share this app with your CoE Admins.
------
![image](https://github.com/microsoft/coe-starter-kit/assets/78455821/dc24b672-c8c0-4040-806c-1c299908172a)


Is it possible to use the above apps without admin role?
If it is not possible to use the above apps without the admin role, then as you have indicated below, there is nothing that can only be done with Power Platform Admin SR, which means that Power Platform Admin SR is meaningless. I guess so.
>Here as well the operations that users with Power Platform Admin SR does will be for sure be able to do with System Admin role as well

**Comment by Sasae528** [comment]
@Jenefer-Monroe 
As I commented in the last issue, I recognize that "most" functionality, not "some" functionality, will not work without Power Platform Admins.
In other words, the number of cases where an account that does not have the Power Platform Admins rights but has the Admin SR rights is close to zero,
In most cases, the account will be used with Power Platform Admins privileges (which encompass the Admin SR privileges).
Is this correct?
If there are any scenarios where an account that does not have Power Platform Admins privileges but does have the Admin SR privilege is used, please let me know.

**Comment by Jenefer-Monroe** [comment]
I'm afraid I'm not entirely following. 
The point of the Power Platform Admin SR is to grant users permissions to view the inventory. All it does is grant permissions to see the data in the tables in the CoE envt. 
It does not elevate them or give them rights to other envts.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
