### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can the CoE delete connections and connection references in our environments?

### ISSUE THREAD

**Issue by julian0723** [microsoft/coe-starter-kit#7987]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am writing a new thread for the issue in reference to a question made 2 yrs ago.
https://github.com/microsoft/coe-starter-kit/issues/4183

I see that the [Admin | Broken Connection Cleanup](https://learn.microsoft.com/en-us/power-platform/guidance/coe/governance-components#admin--broken-connection-cleanup) is no longer available.

Is there now a new feature or an equivalent flow created/release/plan for deleting the broken connections in the current version of COE? Any ETA if any.

Regards,
Julian

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024 4.23

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2738

**Comment by Jenefer-Monroe** [comment]
Hello. Well timed question. The April release has a new set of functionality around connections, including the orphaned ones: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/938eff13-bd12-4101-a1a0-cf3c0386b86e)

Then you can click one to open a tool to manage it
Here to show you a screenshot of the type of exploration you can do in that app, and then remove connections
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/94bc3037-59d6-49ce-8c0c-5591d3adecde)

**Comment by Jenefer-Monroe** [comment]
closing out as this release is now available.

**Comment by lukas-nC** [comment]
@Jenefer-Monroe  how to I get to that Connection Celanup View in the Manage Permission App?
