### ISSUE TITLE
[CoE Starter Kit - QUESTION] Get list of Power Apps that have Connections to specific Sharepoint site

### ISSUE THREAD

**Issue by Vegaspower** [microsoft/coe-starter-kit#7988]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

My Question: **How can I extract a list of all Power Apps within the Tenant that use a SharePoint connection, the requirement is to see the SharePoint site the connection in the Power App is referring to.** 

The Goal: **To troubleshoot which App is making changes within a SharePoint Library.** 

Context:
- Tried the PowerShell for: GetAdminPowerApp and GetAdminPowerAppConnection 
- Neither provides this information
- For Flows I currently use the field: ReferencedResources_SharepointSite to fulfill this requirement

Thanks for looking into this, if additional information is required, please reach out. 

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2743

**Comment by RahulBojji** [comment]
@VegasPower You can open the environment where COE tool kit is installed and navigate to "**Power Platform Admin View**"  and click on **PowerApp Apps** -> Click on Add Columns -> Add App Connections as a column

<img width="907" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/40c1154a-b043-47ca-b41e-80c35d4eb83e">
 
You can add additional columns as well.
Add below filter on the column. This will display all the apps which uses sharepoint connection. For exporting this you can click on **Export to Excel** button. This will display all the apps in the tenant which uses sharepoint connection if inventory is enabled on all the environments.

<img width="545" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149372606/1988b0ed-832d-4cf8-9840-8b559b601598">

**Comment by Vegaspower** [comment]
> @Vegaspower You can open the environment where COE tool kit is installed and navigate to "**Power Platform Admin View**" and click on **PowerApp Apps** -> Click on Add Columns -> Add App Connections as a column
> 
> <img alt="image" width="907" src="https://private-user-images.githubusercontent.com/149372606/319557265-40c1154a-b043-47ca-b41e-80c35d4eb83e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjkyNDgsIm5iZiI6MTcxMjIyODk0OCwicGF0aCI6Ii8xNDkzNzI2MDYvMzE5NTU3MjY1LTQwYzExNTRhLWIwNDMtNDdjYS1iNDFlLTgwYzM1ZDRlYjgzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMTA5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDAxYzUzYWI4NmM2YzE3MDgwMWE5MzYwOGMyNDFkZjJjOWZkMDI3YTg1N2U5NmUwNmRhNzkxZTlmZTg5MzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PDp8dp_AHweGEuLCCuQxvJWIAnVhB-v49TrC2XHfgGQ">
> You can add additional columns as well. Add below filter on the column. This will display all the apps which uses sharepoint connection. For exporting this you can click on **Export to Excel** button. This will display all the apps in the tenant which uses sharepoint connection if inventory is enabled on all the environments.
> 
> <img alt="image" width="545" src="https://private-user-images.githubusercontent.com/149372606/319557818-1988b0ed-832d-4cf8-9840-8b559b601598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjkyNDgsIm5iZiI6MTcxMjIyODk0OCwicGF0aCI6Ii8xNDkzNzI2MDYvMzE5NTU3ODE4LTE5ODhiMGVkLTgzMmQtNGNmOC05ODQwLThiNTU5YjYwMTU5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMTA5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzAyNjJhYTFlMTVkODY0OGQ2YmUxOTkxNmM3M2VlZjUyYjZiNzJmYjYzYWI0Njc4NTRhNzc5ZDFmNjk2N2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H-A-I5PaXEwIcmFo7ovr5rpUH_fGrHtq03snhB5xA3g">

**I know this, how can we get a list that shows the Sharepoint site? because we want to check one specific site.**

**Comment by Jenefer-Monroe** [comment]
Unfortunately this information, while exposed to us for flows as you mention, is not exposed to us in apps. 
So as far as I know there isnt a way for us to gather this. 
Happy to hear from the community if anyone knows of a way to do this!

**Comment by Vegaspower** [comment]
@Jenefer-Monroe Thanks for the response. I will then explore other ways, possibly this can be achieved with the Graph API.

**Comment by Jenefer-Monroe** [comment]
Please do let us know if you find something!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
