### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Power Apps User Shared With (Action 'List_group_members' failed)

### ISSUE THREAD

**Issue by Chandra1247** [microsoft/coe-starter-kit#7990]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

CLEANUP HELPER - Power Apps User Shared With is getting failed with the error message "Action 'List_group_members' failed" for some of the Group ID.

Seeing failure in parent flow - CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With) due to this issue.

![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/a3f34c5b-b9cc-446b-b470-89f18027018d)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

### What method are you using to get inventory and telemetry?

None

AB#2746

**Comment by Jenefer-Monroe** [comment]
Hello, can you please check for an unmanaged layer on this flow? We did fix this bug some time ago to add a catch there.
In March release (4.24) it looks like this: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2cb646a7-f9d3-4f96-a18e-f55665a22625)

**Comment by Chandra1247** [comment]
Hello Jenefer,

Yes. I missed to remove the unmanaged layer and i see the the catch action now.

![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/702a51c3-cf79-4b45-b31b-73112bae8ed3)
