### ISSUE TITLE
[CoE Starter Kit - Feature]: ProductionEnvironment default value to No

### ISSUE THREAD

**Issue by sandeepnahta** [microsoft/coe-starter-kit#7991]
### Is your feature request related to a problem? Please describe.

Imagine some installed the to CoE kit - installed it in their tenant - and all of sudden 100s of emails are coming

### Describe the solution you'd like

For CoE starter kit - I am not sure why Environment Variable "ProductionEnvironment" default value is set to **Yes** ?? It should be "No" to avoid scary emails coming out by mistake. Logically in documentation - it should be clearly mention - post testing - change value of "ProductionEnvironment" to **Yes**

AB#2747

**Comment by sandeepnahta** [comment]
thanks for details Jenefer - but that doesn't make sense. If we made a mistake in past by choosing Yes as default - we should not carry it all along life of CoE kit / assuming every day CoE kit is growing and have a potential to send 1000s of email in an organization with big adoption. This setting need a rethink for sure

**Comment by Jenefer-Monroe** [comment]
Sorry to hear you disagree. Few things to note: 

1. The setup wizard does expose this for you for easy update
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e73a3116-2022-433b-a11d-5062ea016a12)

2. You can also update it at any other time in the Command Center
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6f75a06b-8bcd-4c7c-a8d6-b450f00c51a4)

3. The setting does persist, so once you set it to "no" it stays that way (unless you are changing the default value which is not the recommended approach)

We have 11 k installs of the kit with a variety of sophistication of users. and so we cannot really make changes that drastic on the user base. 
As an open toolset you can also extend the kit to change its behavior. IF you are doing a bunch of installs for example you could add a flow that you call before you run the setup wizard.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
