### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can I create a record in the inventory tables?

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#7993]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,
I'm creating a Compliance Process based on the client's needs. Sometimes, I list a component (App or Flow) that hasn't been created yet in the CoE Tables. Can I create the record to update only the fields I need and rest assured that the other fields filled by the inventory run will eventually be updated? Or, is it more complicated than that, and I'll have to create the record just as the inventory flows are doing?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2749

**Comment by Jenefer-Monroe** [comment]
I have not tested this but I think you will most likely just want to wait for it to be in inventory. I cant imagine this happens that often, is it something you run up against often?

**Comment by LucX4** [comment]
Thanks Jenefer, will try and let you know.

**Comment by LucX4** [comment]
Hi @Jenefer-Monroe, hope you are doing well!
It did work in the end, but unfortunately, all the data I had added to my custom columns was deleted. Do you have any insights into why this might have happened? Also, for better understanding, could you please clarify the exact purpose of the 'Inventory Me' field?
Thank you so much!

**Comment by LucX4** [comment]
Actually, it didn't considerer it as a record already present in the inventory. I'm checking this filter here: 
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/e8a4c51a-4270-4ed2-a3f7-3c7ae24a999c)
I think I left the environment record empty.

**Comment by Jenefer-Monroe** [comment]
Yes that would make sense, and something I've done myself before! :D 

Inventory Me flag sends an object through inventory even if it wouldnt normally qualify. 
To save API calls we only inventory objects which we recognize as "dirty". Typcially this means a recent modified-on stamp from the product. 
Inventory Me flag sends it through inventory even if it not recognize as dirty.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by LucX4** [comment]
Hi @Jenefer-Monroe, it worked. The record was updated successfully. Just to update you!
Thank you so much for the help!
