### ISSUE TITLE
Is there a security role in COE tool kit which provides only read access? 

### ISSUE THREAD

**Issue by DheekshaSivaraj** [microsoft/coe-starter-kit#7994]
### Describe your bug, question or feature ask.

With the previous versions of COE tool kit, we need to give system admin role to read data within the coe apps. Can we provide any security role with lower privileges that allows read access to data in Power Platform Admin view app? Or can we create a custom security role?

**Comment by Jenefer-Monroe** [comment]
Hello sorry for the delay this was put into the wrong product and so we missed it.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
