### ISSUE TITLE
Can anyone please help me with a test script for new versions COE tool kit?

### ISSUE THREAD

**Issue by DheekshaSivaraj** [microsoft/coe-starter-kit#7995]
### Describe your bug, question or feature ask.

We had very outdated versions of COE tool kit in our environments and update was not easy due to a lot of dependency. So we have created new environments to install the latest version of the COE tool kit. To make sure everything is working as expected, it would be very helpful to know the tests that is commonly run with the COE tool kit. Kindly share the criteria's to focus on and any recommended tests to be performed after the installation.

AB#2967

**Comment by Jenefer-Monroe** [comment]
Hello sorry for the delay this was put into the wrong product and so we missed it. 
Unfortunately we have no such write up but we can put here in the community to see if others have something written up

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
