### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYOD_CoEDashboard Apps & Cloud Flows tab Missing Connector Filter

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/coe-starter-kit#7996]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When I go to BYOD_CoEDashboard for Apps and Cloud Flow tabs, On the Filters on this page section, the Connector Name is not showing up.

![image](https://github.com/microsoft/coe-starter-kit/assets/110540273/bd5fa88f-bc7d-409e-ab57-a96fb03959c0)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

BYOD_CoEDashboard

### What method are you using to get inventory and telemetry?

Data Export

AB#2750

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. Putting with the BYODL backlog

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
