### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unable to install Creator Kit

### ISSUE THREAD

**Issue by Sasae528** [microsoft/coe-starter-kit#7997]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I tried to install the Creator Kit as a preliminary step to install the CoE Starter Kit today, but the installation seems to fail.
It had not failed until yesterday.
This is happening in multiple tenants and environments.
The error codes are as follows
DB.PDInvoker Assembly Find
6044437
![image](https://github.com/microsoft/coe-starter-kit/assets/78455821/f19f2127-32ed-4ebd-b87e-8fbd1d867368)

Is the incident occurring at Microsoft?
Is it currently possible to install in your environment?
If anyone knows how to resolve this error, please let us know how to do so.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2751

**Comment by Jenefer-Monroe** [comment]
Hello. I am able to install the creator kit. Unfortunately that is a different set of resources that take care of that kit and so you'll need to put the issue there for them to assist you: https://github.com/microsoft/powercat-creator-kit/issues
