### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Security Roles) - Getting error because of the name formatting.

### ISSUE THREAD

**Issue by bhupendra14** [microsoft/coe-starter-kit#7998]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting error for one of the user's name "NAME = **Arthur D'IXXY**" , error message below-

There is an unterminated literal at position 98 in 'admin_name eq 'Arthur D'IXXY' and _admin_environment_value eq dbxxxx2-8xx7-4xx9-bxxe-edxxxxxbxaxx'.

I can notice the name format is different but this is not unique, we may have many users with this type of naming format. Can't we handle this in the flow to avoid this error.

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/2bd1e41e-1a02-4058-9938-c466e89d5b5d)

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/241b3d93-2f6d-4f0e-9cc7-fe15d277c4a2)

### Expected Behavior

Flow should ignore the single inverted comma in between the name or consider the full name.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Security Roles)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2757

**Comment by RahulBojji** [comment]
@bhupendra14 . We have two issues tracking this.
The first, and the one impacting you, is covered by https://github.com/microsoft/coe-starter-kit/issues/7884 and local fixed for April release.
The second is https://github.com/microsoft/coe-starter-kit/issues/7958 and will target May release.

**Comment by Jenefer-Monroe** [comment]
The one you are hitting is the first issues listed, fixed in April (just shipped!) 
The second one is a less common scenario that you may not hit at all (we'll still fix it!) and so on your next upgrade you wont see this anymore. 
I'll go ahead and close as a dupe since the fix is now available.
