### ISSUE TITLE
Pipelines: ensure build fails when there are no changes to commit in export-solution-to-git.yml

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#8]

**Comment by rpothin** [comment]
In a pipeline, what is the behavior when you try to make a commit and then a push without any changes?
And why do you want to have a failed build in that case?

**Comment by devkeydet** [comment]
Complete in our internal repo. Won't mark as complete here until we are able to transfer what's in our internal repo here. Our internal repo uses some unannounced tools and soon to be released bug fixes in the service. We will need to wait to bring these enhancements into this repo.

**Comment by devkeydet** [comment]
@rpothin - to answer your question, the canvas app user can initiate a "export to git branch" action in the app.  It's possible to attempt to import something that won't result in a commit (if there are no changes).  The canvas app will check the status of the pipeline that implements the export/commit process.  If the pipeline execution doesn't result in a valid commit, it will notify the user.

**Comment by devkeydet** [comment]
Resolved in private preview repo.
