### ISSUE TITLE
[CoE Starter Kit - BUG] Edit Data option greyed out performing configure CoE settings table steps of core components installation

### ISSUE THREAD

**Issue by michaelgottwals** [microsoft/coe-starter-kit#800]
### Describe the issue

I have been following the instructions to setup the CoE Starter Kit (Option 2: Import the solution into Dataverse for Teams environment) per article https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components. I have successfully implemented all steps up to "Configure the CoE Settings table". I am performing Option 2 of the "configure CoE settings" steps and substep e. "Select Edit data" is greyed out for me, preventing me from entering the required values. (See screenshot 1 attached) I tried using the "Edit data in Excel" but that exports a spreadsheet to my local downloads folder which contains a table with all of the columns from the CoE Settings table and no rows. This indicates to me the Teams Dataverse table contains no rows which may be why the "Edit data" option is greyed out. I thought maybe there was a link from the exported spreadsheet to the Dataverse table but I did not see any data connection defined there. This appears to be a bug as the behavior is not matching the Microsoft provided instructions.
<img width="530" alt="Screenshot_1" src="https://user-images.githubusercontent.com/79226165/124977427-b319fc80-dfed-11eb-9f71-f7828e883e7a.png">

### Expected Behavior

I expect the "Edit data" option to be clickable when performing configure CoE settings step as the Microsoft provided instructions state.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponentsTeams_1_998_managed

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponentsTeams

### Steps To Reproduce

Steps to produce the error have been described in the issue description

**Comment by JeneferM-MSFT** [comment]
It does appear that the product has changed here unfortunately.

If you can Edit data in Excel, you are unblocked. You can add your row and publish it back up. 

Open the file > Enable Editing
![image](https://user-images.githubusercontent.com/62659043/124979718-a519ab00-dff0-11eb-8fae-b902718af9c7.png)

Ignore this error if you see it, just hit OK
![image](https://user-images.githubusercontent.com/62659043/124979779-bc589880-dff0-11eb-9ec1-1c992ad577f4.png)

Fill in the information and hit Publish
![image](https://user-images.githubusercontent.com/62659043/124980083-2e30e200-dff1-11eb-83a3-6d8252500421.png)

**Comment by michaelgottwals** [comment]
Hello Jenefer,

I open the file on my local downloads folder, it appears I am already in edit mode by default as I do not see the Enable Editing button. I added a value for the Company Name column and saved the document. However, I do not see any option publish nor do I see any information in the Data connections ribbon option showing it is linked back to the Teams environment. Can you provide a little more details to help me out?

Thanks.


Kind Regards / Mit freundlichen Grüßen,

***@***.***D77408.1A256E20]<https://www.boehringer-ingelheim.us/>

Michael Gottwals
IT EDS Content Life Cycle Services
Boehringer Ingelheim USA Corporation
900 Ridgebury Road, Ridgefield, CT 06877
P: +1 203-778-7305
***@***.******@***.***>
Facebook<https://www.facebook.com/BoehringerUS/> | Twitter<https://twitter.com/boehringerus> | Instagram<https://www.instagram.com/boehringerus/> | LinkedIn<https://www.linkedin.com/company/boehringer-ingelheim>

**Comment by JeneferM-MSFT** [comment]
Sounds like you dont have the addin. We will see if there is some workaround

**Comment by michaelgottwals** [comment]
Hello Jenefer, 
Just curious as to what the excel add-in is that you were referring to? 
Also, any ideas for a workaround to this issue? I see the July 2021 CoE starter kit was released today in Github, any chance this version addresses this issue?

**Comment by JeneferM-MSFT** [comment]
Your issue is a product change, not a change in our toolkit, so upgrade will not help. 

We are exploring a workaround but the good news is that you can proceed without this step, we only rely on this table for formatting things so you can get your inventory going. 

Here is a blog a out the [Excel Add-In](https://powerapps.microsoft.com/blog/use-edit-in-excel-in-dataverse-for-teams/)

**Comment by michaelgottwals** [comment]
Thanks for the information it is much appreciated. Unfortunately my company blocks office add-ins so I am unable to install that. So if I skip this step is their some way to update that table in the future? It sounds like not until a change is made to the CoE starter kit and if that is the case is this fix/change planned for a future version?

**Comment by michaelgottwals** [comment]
Also, one other question, do you think it makes sense to install the latest release of the CoE starter kit at this stage to get the latest and greatest?

**Comment by JeneferM-MSFT** [comment]
We have just removed the CoE settings from the setup instructions entirely and now surface these as env variables. 
Will release with August.

**Comment by michaelgottwals** [comment]
Great News. I took your advice and moved on with the installation, How do I get the new functionality into my existing Dataverse for Teams installation once it is released in August?

**Comment by mikefactorial** [comment]
@michaelgottwals This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
