### ISSUE TITLE
[CoE Starter Kit - BUG] Too many actions in flow 'Admin | Sync Template v3 (Flow Action Details)

### ISSUE THREAD

**Issue by PaWeg** [microsoft/coe-starter-kit#8000]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The flow 'Admin | Sync Template v3 (Flow Action Details)' failed on a limit of number of array items in array ActualFlowActionDetails. In this environment there are a lot of flows and some with a lot of actions.
![image](https://github.com/microsoft/coe-starter-kit/assets/32161465/630b130a-ad58-4884-8073-7dbf34db54aa)
![image](https://github.com/microsoft/coe-starter-kit/assets/32161465/802641c3-a945-4a8a-98e4-7f2bb86d12eb)
Can we increase this limit ?

And actually the flow is now suspended because of it was running more actions than expected
![image](https://github.com/microsoft/coe-starter-kit/assets/32161465/0fcc25e3-7f64-4244-9fa8-a4c7451c9132)

### Expected Behavior

process all action in all our flows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin Sync Template V3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2777

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately this is a known limitation currently. We will have to rearchitect the flow to be per-flow to get unblocked and then need to find a way to do that that isnt too crazy API wise. 
This is tracked by https://github.com/microsoft/coe-starter-kit/issues/6819

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
