### ISSUE TITLE
[CoE Starter Kit - BUG] Hardcoded URL in AI Credits Usage table in BYODL_CoEDashboard_April2024 PBI Report

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#8004]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This URL should not be hardcoded.
![image](https://github.com/microsoft/coe-starter-kit/assets/41799380/8197b51c-ee20-4a76-8b28-685049e5049b)

### Expected Behavior

It should use the parameter instead.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

BYODL_CoEDashboard_April2024

### What app or flow are you having the issue with?

BYODL_CoEDashboard_April2024

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Open the PBI Template and look.

AB#2781

**Comment by Jenefer-Monroe** [comment]
Thank you! Might re-release this PBIT on Monday.

**Comment by Jenefer-Monroe** [comment]
[Production_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14890912/Production_CoEDashboard_April2024.zip)
[BYODL_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14890913/BYODL_CoEDashboard_April2024.zip)

**Comment by Jenefer-Monroe** [comment]
There are the new files. will upload on Monday. thank you!
