### ISSUE TITLE
[CoE Starter Kit - QUESTION] Turn on Copilot Studio Chat Bot for CoE Tables

### ISSUE THREAD

**Issue by kashanico** [microsoft/coe-starter-kit#8007]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I would like to plug in some of the CoE dataverse tables to a Copilot Studio chatbot and be able to ask questions Apps and Flows on the tables. Currently, I am not able link copilot studio with the CoE tables.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2784

**Comment by Jenefer-Monroe** [comment]
Can you please share a little more information here? What feature are you wanting to be enabled?

**Comment by kashanico** [comment]
I'm
