### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why aren't new environments showing up in COE Admin View app

### ISSUE THREAD

**Issue by bdcqr** [microsoft/coe-starter-kit#8008]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I created a new environment several days ago but it's not showing up in the COE admin view app. Perhaps it's a sync issue with one of the COE flows, but I am not sure which one that would be. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

March 2024

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2785

**Comment by Jenefer-Monroe** [comment]
Can you please go see if you have been assigned the System Administrator role in the new environments? 
Your organization may have opted in to this preview security feature for which the CoE kit is still blocked. 

The new feature : 
[Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles): 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/552e5e9c-79c5-4791-b732-1820710dbffe)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
