### ISSUE TITLE
[CoE Starter Kit - BUG] Couldnt find Admin | Sync Template v3 (Driver) flow in CoE flows page of the Admin - Command Center app

### ISSUE THREAD

**Issue by pavanmanideep** [microsoft/coe-starter-kit#8009]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I was trying to install COE-Compliance components from the setup wizard itself, I cant proceed as I  get this error
<img width="947" alt="COE Error to Microsoft" src="https://github.com/microsoft/coe-starter-kit/assets/27499846/6b53868e-48d5-4ad0-9945-545e11a62ac7">
I couldn't find the respective flows, I couldnt find Admin | Sync Template v3 (Driver) flow in CoE flows page of the Admin - Command Center app.

### Expected Behavior

I should be able to find Admin | Sync Template v3 (Driver) flow in CoE flows page of the Admin - Command Center app.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Driver) flow 

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

From the Set up wizard, i try to run Compliance components solution, I get this error...

### Anything else?

<img width="947" alt="COE Error to Microsoft" src="https://github.com/microsoft/coe-starter-kit/assets/27499846/cc2d5993-6bae-45cf-9d6e-a6592f1c50d8">

AB#2786

**Comment by Jenefer-Monroe** [comment]
Hello. This one is fixed in the April release. Please see https://github.com/microsoft/coe-starter-kit/issues/7806 for [a workaround](https://github.com/microsoft/coe-starter-kit/issues/7806#issuecomment-1998401773) in your current build.

**Comment by pavanmanideep** [comment]
I see, when I was installing April COE Core Components solution, I get this error 

![COE Error 2](https://github.com/microsoft/coe-starter-kit/assets/27499846/5004c4c6-fed4-4642-aeb7-e62d68f097c3)

**Comment by Jenefer-Monroe** [comment]
Hello. I'm not sure what that error is. I am able to upgrade and install fine as are others. 
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)
And also please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by pavanmanideep** [comment]
Here is the snap
![Error Installing](https://github.com/microsoft/coe-starter-kit/assets/27499846/c103e9de-70ab-436d-a600-ed7a115e1344)

I am using Default Environment.
![Environment COE](https://github.com/microsoft/coe-starter-kit/assets/27499846/7b9e33fd-4a17-40d8-8e0a-ada4da07bb3d)

**Comment by pavanmanideep** [comment]
> Hello. I'm not sure what that error is. I am able to upgrade and install fine as are others. Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names ![image](https://private-user-images.githubusercontent.com/89584709/294178041-8dd512cc-21fc-4c64-adab-0f64c29b9bf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Njk0NTUsIm5iZiI6MTcxMzU2OTE1NSwicGF0aCI6Ii84OTU4NDcwOS8yOTQxNzgwNDEtOGRkNTEyY2MtMjFmYy00YzY0LWFkYWItMGY2NGMyOWI5YmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDIzMjU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMTg1MmIwYjExZWQ3YzA1MjdkNzZlZjBiYWZiMTQyOWZlNzZiNzJjOTdhOWU3YWU2ZWY3NjdlNTc1ZDM0MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.opcw6OH9Ky5_DcZD8P11V2XHFio8Mm17a33wLs1lVLQ) And also please let us know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/ ![image](https://private-user-images.githubusercontent.com/89584709/237367659-4c23e8c8-2f8b-4d8b-af43-79a9f289be69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Njk0NTUsIm5iZiI6MTcxMzU2OTE1NSwicGF0aCI6Ii84OTU4NDcwOS8yMzczNjc2NTktNGMyM2U4YzgtMmY4Yi00ZDhiLWFmNDMtNzlhOWYyODliZTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDIzMjU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZjIyYTM3ZjIwNWQxMWM4Yjk0MDg4ZjQ5NTI1OTk5NmJiMjEyOGRmNWRhNmVkOTgzY2Q4MWI4MDEyMjZiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ILSKFHp8oEBgghLgIfUqnSu029sSpQph2KukhH8AtnI)

Please see my latest comment
