### ISSUE TITLE
[ALM Accelerator - BUG]: Variable EnvironmentName in deploy-Solution.yml - 'Check if Deployment Settings Exist' not defined

### ISSUE THREAD

**Issue by stefanjackmuth** [microsoft/coe-starter-kit#801]
### Describe the issue

deploy-Solution.yml
powershell-task 'Check if Deployment Settings Exist'

Pipeline in Branch devkeydet-652 is using $(EnvironmentName) which is unknown. 

Fixed it via using $(EnvironmentId)

Same issue in import-configuration-migration-data.yml

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20210521.1

**Comment by mikefactorial** [comment]
@stefanjackmuth this issue slipped past us. Pardon the delay. As a heads up the pipelines in the branches other than main are in flux at any given point during our development of the monthly release. Feel free to use the bits in other branches but there's not guarantee that those will be in a working state best to use main. 

One of the side effects of importing the template repo into Azure DevOps is that AzDO will just pick the first branch as the default which is likely why you got into the state your in. You can update the default branch in AzDO after the import to be the main branch like below.

![image](https://user-images.githubusercontent.com/42348035/125520852-5cc44ee3-6e44-4110-adf8-987b18fe93f4.png)

**Comment by mikefactorial** [comment]
Closing this issue for now.
