### ISSUE TITLE
[CoE Starter Kit - QUESTION] Creating a custom email utilizing CoE starter kit

### ISSUE THREAD

**Issue by accvik** [microsoft/coe-starter-kit#8013]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hey,

I'm looking into a use case where we want to send a totally custom email when a Teams Environment is created (or after x days passed after creation). 

My question - is it "safe", meaning is it low risk it will break in the future, to utilize CoE starter kit  "Helper - Send Email" flow for this cause to keep styling consistent with the rest of CoE emails? (For example, the input variables into the Helper flow could change, etc.) 
I have the same question for the Data - how likely is it that the Dataverse Environment table will change and affect my automation? (Environment type, creation date, environment GUID, etc.). 

Thanks,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Mars 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2839

**Comment by Jenefer-Monroe** [comment]
Hello. We don't make changes to the flow often and rarely make breaking changes wrt tables. Lots of people extend the kit like this so its got a good precedent.

However it could happen.

If you take a dependency like this you would probably want to walk the change list before you upgrade for that release and the interim ones (ex look at March changes if you skipped it) 
https://github.com/microsoft/coe-starter-kit/releases/latest

Or, for the flow, you could make a copy of the flow and call it from your custom one instead to be more certain.

**Comment by accvik** [comment]
Thanks!
