### ISSUE TITLE
[CoE Starter Kit - QUESTION] Request Orphaned Objects Reassigned (Child)

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#8017]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi I have noticed the Request Orphaned Objects Reassigned (Child) shows as a successful run when it failed to get the manager ID. 
 Within the admin view app the orphaned user has a manager showing, but the manager has also left the company.
Is it possible to have these showing as failed runs, that way when looking at the runs they are easier to find, as going through the successful runs can be time consuming if there are a lot of orphaned objects.
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/d7bb8e34-222d-42a9-b52c-5031ea83d512)

![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/19a3ef06-81dd-4092-b209-66e14964e617)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.16

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2844

**Comment by Jenefer-Monroe** [comment]
Hello yes we can put this on the backlog with the rework to the orphan flows processes. 
Thanks for posting.

**Comment by Alyson95170** [comment]
That's great thanks Jenefer
