### ISSUE TITLE
[CoE Starter Kit - QUESTION] Welcome Email covers PVA Makers

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8018]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Team, 

Does the welcome email in core components covers when I user creates a PVA for the first time? 

Use Case: User has never created anything and has created a PVA for the first time. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Welcome Email v3

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2845

**Comment by Jenefer-Monroe** [comment]
Hello. Yes, anything that causes the user to be added to the Maker table will trigger the welcome mail.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
