### ISSUE TITLE
[ALM Accelerator - BUG]: Update Solution Component Ownership Failed

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/coe-starter-kit#802]
### Describe the issue

Getting following error while setting up ownership.

{"error":{"code":"MissingUserDetails","message":"The user details for tenant id '***' 
and principal id '58faa18e-651c-4539-b8d1-e16ebda87b88' doesn't exist."}}
{"error":{"code":"MissingUserDetails","message":"The user details for tenant id '***' 
and principal id '58faa18e-651c-4539-b8d1-e16ebda87b88' doesn't exist."}} => 
{"error":{"code":"MissingUserDetails","message":"The user details for tenant id '***' 
and principal id '58faa18e-651c-4539-b8d1-e16ebda87b88' doesn't exist."}}[TerminalFailure] Failed to Execute Command - 
Assign : RequestID=1521e05e-345d-4f75-be62-ca75b1587864 : Routing a Ticket to User WIP Bin duration=00:00:01.6544465 
ExceptionMessage = {"error":{"code":"MissingUserDetails","message":"The user details for tenant id 
'***' and principal id '58faa18e-651c-4539-b8d1-e16ebda87b88' doesn't exist."}}
{"error":{"code":"MissingUserDetails","message":"The user details for tenant id '***' 
and principal id '58faa18e-651c-4539-b8d1-e16ebda87b88' doesn't exist."}} => 
{"error":{"code":"MissingUserDetails","message":"The user details for tenant id '***' 
and principal id '58faa18e-651c-4539-b8d1-e16ebda87b88' doesn't exist."}}

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20210521.1

**Comment by mikefactorial** [comment]
@aakashpatel660 can you try running the pipeline again with diagnostics turned on and export the logs for me? Instructions here https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops

**Comment by aakashpatel660** [comment]
@mikefactorial 

Below are the logs.

[logs_229.zip](https://github.com/microsoft/coe-starter-kit/files/6792277/logs_229.zip)

**Comment by mikefactorial** [comment]
@aakashpatel660 can you verify the ids being used in the pipeline variable configuration for solution component ownership? I'm going to setup a call for us tomorrow to continue troubleshooting this.

**Comment by aakashpatel660** [comment]
Hi @mikefactorial 

I did make sure and their ids are correct and we can take a look into it tomorrow.

**Comment by mikefactorial** [comment]
@aakashpatel660 I have a working theory on this. It appears as if the ownership can't be updated after the flows are activated which would be a bug in the pipeline. Can you help test this theory by commenting out the following in the update-connection-references.yml template temporarily and running the build again?

```
#Set-CrmRecordState -conn $impersonationConn -EntityLogicalName workflow -Id $c.objectid -StateCode Activated -StatusCode Activated
```

**Comment by PPMarkO365** [comment]
@mikefactorial I was having the exact same issue. I couldnt have stumbled across this at a better time. I have just tried what you suggested and commented out that line and it does now set the owner correctly.

**Comment by mikefactorial** [comment]
@PPMarkO365 thanks for confirming. @aakashpatel660 also verified offline. The issue here is that we are turning on flows as part of reconnecting connection references but that is happening prior to the solution component ownership updates running. The ultimate fix will be to move enabling flows to be the last step after connection references and ownership are set. The recommendation to comment out the activation code was to test the theory. We are planning on putting out a new release this week. Hoping to have the updates to the pipeline done tomorrow. I'll update here if you want to assist with testing the updates ahead of time. Thanks again!

**Comment by mikefactorial** [comment]
@aakashpatel660 This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.
