### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Dashboard PowerBI Report asks to authenticate with PowerCAT Tenant

### ISSUE THREAD

**Issue by kashanico** [microsoft/coe-starter-kit#8021]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When authenticating the April 2024 Production_CoEDashboard_April2024.pbit it asks to authenticate vs orgfa61f382.crm.dynamics.com, even after I put our own custom env url, when you try to login with your account you get a error message.

AADSTS90072: User account ****** from identity provider 'https://sts.windows.net/ceec000-1cfa-49c2-a24f-7db63c8a9a52/ does not exist in tenant
'TEST_TEST_POWERCAT_TOOLS' and cannot access the application 'a672d62c-fc7b-481-a576-|
e60dc46e951d'(Microsoft Power Query for Excel) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

PowerBI Report

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2848

**Comment by Jenefer-Monroe** [comment]
Hello, we reshipped these over the weekend with the fix. Please see https://github.com/microsoft/coe-starter-kit/issues/8004 where we have a copy shared, or redownload from https://github.com/microsoft/coe-starter-kit/releases/latest

**Comment by kashanico** [comment]
Ok thank you, I can confirm the new file works now.
