### ISSUE TITLE
[CoE Starter Kit - BUG] The schema validation failed.

### ISSUE THREAD

**Issue by julz-opy** [microsoft/coe-starter-kit#8023]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have recently upgraded my CoE toolkit and am seeing parsing null issues on at least 2 flows: 
- Admin | Sync Template v3 (Flow Action Details) - Action 'Get_Flow_Permissions_Check' failed
- Admin | Sync Template v4 (Model Driven Apps) - Action 'Parse_Inventory_-_New_MDAs' failed

Both are complaining about null data where a string was expected

example from a failed run on Model Driven apps:

<img width="434" alt="error model driven" src="https://github.com/microsoft/coe-starter-kit/assets/166464034/b277a322-ff3c-4896-8745-e3aececbb9ed">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Model Driven Apps)

### What method are you using to get inventory and telemetry?

None

AB#2850

**Comment by julz-opy** [comment]
I've been looking at the apps table and have noticed many of the entries  have no unique name, could it be the issue?

<img width="191" alt="emptyappsunique" src="https://github.com/microsoft/coe-starter-kit/assets/166464034/8f91d660-72ee-4fc1-b8bb-97e019d26ae6">

**Comment by Jenefer-Monroe** [comment]
Yes that is the issue. Thanks for continuing to investigate! Likely something in the old sync flows added these bad data records and it was just not known until now as we changed to this set logic technique. 

Please delete these bad records, and the flow will pass and re-enter these rows with all the fields populated. 
Then lets hold for a few days to make sure it doesnt return.

**Comment by julz-opy** [comment]
I thought the platform was going to have a conniption there were thousands that were blank. Things seemed to go much, much better over night. Hopefully that has sorted it moving forward. I do have some issues with missing launch data but I'll open a question on that one. Thanks for the support
