### ISSUE TITLE
[CoE Starter Kit - BUG] Change action to Remove app as Admin in Helper - CanvasAppsOperations

### ISSUE THREAD

**Issue by santhods** [microsoft/coe-starter-kit#8025]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We noticed that the action 'Remove App' in the flow Helper - CanvasAppsOperations (under Canvas App Operation -> If found in inventory then continue -> If Yes -> Switch on action input -> Case delete) causes the flow to fail as it couldn't delete an app.

We noticed that this action, unlike other switch cases, does not ask for the environment name. We found this action comes from Power Apps for Makers connector.

![image](https://github.com/microsoft/coe-starter-kit/assets/25540261/cf9ab7e6-d07a-43b6-8c4d-4933b93e31bc)

We fixed it by replacing the action with the new 'Remove App' action from Power Apps for Admins connector which this time asks for the environment name.

![image](https://github.com/microsoft/coe-starter-kit/assets/25540261/b3605c1c-2c8d-4ec3-8d6b-8cb92b1de209)

We upgraded our CoE core solution to the version 4.29 on our pre-prod tenant with no customisation applied, but this action is still there.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

HELPER - CanvasAppOperations

### What method are you using to get inventory and telemetry?

None

AB#2853

**Comment by Jenefer-Monroe** [comment]
This was working for me as is, but its better to use the Admin one for sure! So I went ahead and fixed that up for May. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b3ba3d04-26d1-4938-b1c5-45433fd431c8)
