### ISSUE TITLE
[CoE Starter Kit - QUESTION] Secure cloud and/or classified cloud offerings

### ISSUE THREAD

**Issue by mrmonto1** [microsoft/coe-starter-kit#8028]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Will the COE function on tenants within secure cloud and/or classified cloud offerings? 

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2856

**Comment by Jenefer-Monroe** [comment]
Hello. I'm sorry can you clarify what that means? The kit is set to be mostly agnostic to the cloud type. We do some special work to make sure that things like redirects to the cloud for GCC/GCC High work. 

What cloud are you in?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
