### ISSUE TITLE
Environment variable value can't be an empty string.

### ISSUE THREAD

**Issue by varmadvss** [microsoft/coe-starter-kit#8029]
[ "Error: Environment variable value can't be an empty string." ]
{
    "EnvironmentVariables":  [
                                
                                 {
                                     "SchemaName":  "sre_technicalerrorhandlingteam",
                                     "Value":  "#{environmentvariable.sre_technicalerrorhandlingteam}#"
                                 },
                                
                             ],
}

1)  I have this Enviroment variable in the git. still getting this error.

**Comment by varmadvss** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/166595910/3cb1f9e1-5e85-4785-a8af-52926c8b23aa)

**Comment by varmadvss** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/166595910/72e66e00-7608-41a2-a8df-b49d45954882)

**Comment by varmadvss** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/166595910/ad4e1618-aba9-4d03-b907-99695d896a3f)

**Comment by varmadvss** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/166595910/189f80b6-8743-4219-ab8e-88c929cbb706)

**Comment by varmadvss** [comment]
Hi - Can we  get some help onthis?

**Comment by RajeevPentyala** [comment]
@varmadvss Can you please provide more detail? Specifically, which 'Deploy' pipeline were you encountering this error in?
