### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Dashoard AI Credits Usage by Makers show date not maker

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#8030]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

the visual shows the credit consumption to processing date not maker
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/1c0683ab-8917-4b00-b228-e893f086cad8)
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/b2028361-adb3-40c3-8f05-19cbb94acf59)

### Expected Behavior

It should show the credit consumption by maker

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Production_CoEDashboard_April2024 & Production_CoEDashboard_April2024

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

open the Dashboard

### Anything else?
only for Production_CoEDashboard_April2024
adding a relationship
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/eb77257b-2a90-4412-88d4-6c16bebb4d0c)

for both
and changing the data 
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/d3692dda-303d-4b16-9834-29abfe607fd6)
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/d43e21b8-1519-4656-9c3c-965dd2e8d4e7)
is fixing this

PS: Adding also the shadow like the 3 over visuals to this one would be nice 😉 

AB#2858

**Comment by Jenefer-Monroe** [comment]
thanks for posting, will fix up for May release.

**Comment by LucX4** [comment]
Hi @Jenefer-Monroe,
I'm getting the following error in the 'AI Credits Usage' tab:
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/7907d954-0f7a-47ce-a113-142bde0c2682)

**Comment by Jenefer-Monroe** [comment]
Please try the attached. 

[BYODL_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14958010/BYODL_CoEDashboard_April2024.zip)
[Production_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14958009/Production_CoEDashboard_April2024.zip)

**Comment by fannazephyr** [comment]
For me, older version of CoE dashboard for example Nov is working fine and i am able to view Power BI dashbaord but March and April release are not working( for instance the attached [Production_CoEDashboard_April2024.zip] above). I keep getting error AI cerdits usage, key didnt match any rows.
