### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Dashboard, App Deep Dive, no Connector or Connector Tier are shown

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#8033]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, 

in the BYODL_CoEDashboard_April2024 under App Deep dive, if you select Connector or Connector tier no additional info is shown
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/95222f91-e2f0-4035-a819-b4208b8cea1e)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

BYODL_CoEDashboard_April2024

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

open Dashoard
Got App deep Dive
Select Connectir or Connector tier
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/21b11aea-ceea-438a-9816-1dffc76eade1)

### Anything else?

select 
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/e216d717-617e-419b-95c9-7f7a8720bc62)
instead of
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/44b20fae-adaa-4031-b86f-aa4e60ea8734)

AB#2863

**Comment by Jenefer-Monroe** [comment]
Hello. Thank you for posting, this was recently posted by another person as well and so is sitting targeting to be fixed soon. Plesase see https://github.com/microsoft/coe-starter-kit/issues/7932

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
