### ISSUE TITLE
[CoE Starter Kit - QUESTION] HTTP Connectors not showing for all environments

### ISSUE THREAD

**Issue by omalss** [microsoft/coe-starter-kit#8034]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I set up CoE and the data seems to mostly be accurate with the exception of the http connector. 

Before setting up CoE, in a test environment, I created several flows (both solution and non solution aware) using the HTTP connector but it is not showing up in the CoE Power BI reports when I view connectors and associated flows in a table. Other connectors are showing. 
Using the DLP Impact Analysis app also results in the http connector Flows not being flagged as impacted even though http was added to the blocked list and the policy applied to the test environment.

http request received is showing up correctly in report and I haven't identified issues with any connectors except http.

The http connector in the CoE environment is being recognised in CoE - it is part of the Flow: "Command Center App >  Get M365 Service Messages". 

I'm not sure what's going on but I definitely want visibility on the http connector.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2864

**Comment by Jenefer-Monroe** [comment]
To my understanding this is working, so let's make sure everything is running before we start debugging. 

Can you please first go to the Admin Command Center > CoE Flows > Inventory. 
Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246

**Comment by lukas-nC** [comment]
I have the same problem with 4.29

regarding the "normal" Power BI Dashboard this might help
[https://github.com/microsoft/coe-starter-kit/issues/7932#issuecomment-2047548218](https://github.com/microsoft/coe-starter-kit/issues/7932#issuecomment-2047548218)

regarding the BYODL dashboard there might be an issue because of the different connector identifier for http
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/eae673b4-09ac-4f21-b28b-f0560557b5a1)
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/6255cf88-42fe-4995-8c56-08dc926a3e7d)

**Comment by Jenefer-Monroe** [comment]
@lukas-nC can you please post this identification of the issue for BYODL for me seperatly? 

@omalss  can you please share a screenshot of where you are seeing things incorrectly? Perhaps I was thinking of a different spot.

**Comment by omalss** [comment]
Hi, this was an error on my part. Apologies, the data is ok.

**Comment by Jenefer-Monroe** [comment]
Wonderful news thank you so much for taking the time to let me know! 
I'll go ahead and close then but please do reach out with new issues as they arise for you in the future.
