### ISSUE TITLE
Unable to turn on Flows in CoE Core Components

### ISSUE THREAD

**Issue by fbellavf** [microsoft/coe-starter-kit#8035]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This issue was bought to your team in March 2023:
https://github.com/microsoft/coe-starter-kit/issues/5029

We turned off the CoE as we were lacking resources but are looking to get it up and running once more. I contacted MS support, they troubleshooted with me and was not successful. They then suggested that I reach out to you again.

We have the correct license and the connections are correct. Our Core Component version is 4.3 and would like to update to the most recent version but I am unable to proceed due to the flows not turning on. I also read that updates cannot span over 3 versions so I would need to incrementally update all past version to be current. Hoping that since then you have come across this issue and can suggest a solution.

Thank you!

I was able to turn on all but the following flows in the Core solution:

Admin | Sync Template v3 (Ai Models)
Admin | Sync Template v3 (Business Process Flows)
Admin | Sync Template v3 (Connection Identities)
Admin | Sync Template v3 (Environment Properties)
Admin | Sync Template v3 (Solutions)

I get the following error:

Turn on failed. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'List_Environments_as_Admin' of type 'OpenApiConnection' at line '1' and column '10239' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

### Expected Behavior

Would like to turn on the following workflows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Ai Models) Admin | Sync Template v3 (Business Process Flows) Admin | Sync Template v3 (Connection Identities) Admin | Sync Template v3 (Environment Properties) Admin | Sync Template v3 (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2866

**Comment by lukas-nC** [comment]
Hi,
does the user runing the CoESK have a Power Automate per user licence?

**Comment by Jenefer-Monroe** [comment]
Hello. I know I posted the below last time too but I will go ahead and post here for completeness

> All the flows have this pagination policy. The error indicates that you are using an insufficient or trial license.
> Note that we do not support trial licenses for the toolkit due to them having this lower pagination support.
>  
> See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
> And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)
> 
> And hence our requirements for licenses as described in our [prerequisites]( https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with). 
> 

Unfortunately we're not licensing experts so the exact impact of that on your license type is not something I can comment on. 
If your license type is supposed to support this pagination, per support, then this would be a product issue around their license checks.

**Comment by Jenefer-Monroe** [comment]
Thats the type I use too so it should work. 
1. Is that license permanently assigned? Or is it assigned via something like PIM? 
2. If you create a separate flow that uses pagination does it work? 


### Make your own flow to test
1. Create a new flow as a user with the license type
3. Add a List rows action form the Dataverse connector
4. Have it list from any table, doesn't really matter
5. Settings > Turn on Pagination > Threshold = 100000 > Done
![image](https://user-images.githubusercontent.com/89584709/226338926-aa5f5d5f-9c26-4935-8160-c19d9d4db1eb.png)
6. Save > Ignore the warning > Test > Manual > Test
![image](https://user-images.githubusercontent.com/89584709/226339240-028b0c9d-930e-437e-956c-ef6aca8aba83.png)

### Result
If you get a pagination warning then your license type is insufficient. 
If it passes then you have a sufficient license type.

**Comment by fbellavf** [comment]
> Thats the type I use too so it should work.
> 
> 1. Is that license permanently assigned? Or is it assigned via something like PIM?
> 2. If you create a separate flow that uses pagination does it work?
> 
> ### Make your own flow to test
> 1. Create a new flow as a user with the license type
> 2. Add a List rows action form the Dataverse connector
> 3. Have it list from any table, doesn't really matter
> 4. Settings > Turn on Pagination > Threshold = 100000 > Done
>    ![image](https://user-images.githubusercontent.com/89584709/226338926-aa5f5d5f-9c26-4935-8160-c19d9d4db1eb.png)
> 5. Save > Ignore the warning > Test > Manual > Test
>    ![image](https://user-images.githubusercontent.com/89584709/226339240-028b0c9d-930e-437e-956c-ef6aca8aba83.png)
> 
> ### Result
> If you get a pagination warning then your license type is insufficient. If it passes then you have a sufficient license type.

Hi Jenefer,

Azure PIM is not required and I have also done the Flow pagination test as well.

**Comment by Jenefer-Monroe** [comment]
Unfortunately I dont know how to help. 
If your license type is supposed to support this level of pagination but does not, that is an issue with the product's license checks.

**Comment by fbellavf** [comment]
> Unfortunately I dont know how to help. If your license type is supposed to support this level of pagination but does not, that is an issue with the product's license checks.

If I were to remove the flows from the solution would it re-install on an update?

**Comment by Jenefer-Monroe** [comment]
Yes it should. Thats a good idea.

**Comment by fbellavf** [comment]
> Yes it should. Thats a good idea.

Will try this and let you know. I much appreciate your prompt as always!

Thanks
Fernand

**Comment by fbellavf** [comment]
> You bet! I'm hopeful here

Am I correct is stating that I cannot upgrade to the most recent version and it should be done incrementally? If yes, can I upgrade in every 3 month updates?

**Comment by Jenefer-Monroe** [comment]
Do you have other solutions installed besides Core?

**Comment by fbellavf** [comment]
> Do you have other solutions installed besides Core?

I do, I have the Governance Components installed.

**Comment by Jenefer-Monroe** [comment]
So I believe you have the Feb 2023 release installed (Core 4.3)
If that is the case, and you dont have Audit Logs installed, then you should be ok to just upgrade directly. 
Please do let me know.

**Comment by fbellavf** [comment]
> So I believe you have the Feb 2023 release installed (Core 4.3) If that is the case, and you don't have Audit Logs installed, then you should be ok to just upgrade directly. Please do let me know.

Oh oh. I do have audit logs installed but they are all off. Another thig I noticed is that many of the items in the solution shows as modified 6 months ago as well as 2 days ago. Could this happen from an incomplete attempt at uprading?

**Comment by Jenefer-Monroe** [comment]
Yes that could happen if the upgrade partially succeeded. You'll have to delete the _upgrade and I'm not sure but would presume that will also mark them modified.

For the audit logs, you'll need to delete that solution before you can upgrade. Here is a big write up to help you through this: 
https://github.com/microsoft/coe-starter-kit/issues/6018

**Comment by fbellavf** [comment]
> Yes that could happen if the upgrade partially succeeded. You'll have to delete the _upgrade and I'm not sure but would presume that will also mark them modified.
> 
> For the audit logs, you'll need to delete that solution before you can upgrade. Here is a big write up to help you through this: #6018

Ok I will give it a go. Thank you!

**Comment by Jenefer-Monroe** [comment]
Please do let me know!

**Comment by fbellavf** [comment]
> Please do let me know!

I was unable to delete the specific flows so I went ahead and bit the bullet. Rather than using the wizard I just imported version 4.24 (Feb) and all seems well so far. I am able to turn of the problematic workflows now. I will run the wizard to upgrade to version 4.29.

**Comment by Jenefer-Monroe** [comment]
oh wonderful news! Please do keep me in the know. I'm hopeful for you!

**Comment by fbellavf** [comment]
Hi Jenefer, I was able to upgrade to 4.29 and all seems to be well so far! Thanks again.

**Comment by Jenefer-Monroe** [comment]
Great news! Please do let me know, is there anything else I can do for you now? Or shall we close. 
Please note you are welcome to come post new issues any time you need help.

**Comment by fbellavf** [comment]
> Great news! Please do let me know, is there anything else I can do for you now? Or shall we close. Please note you are welcome to come post new issues any time you need help.

Please close this. Thanks!
