### ISSUE TITLE
[CoE Starter Kit - BUG] AI Credit Usage Broken

### ISSUE THREAD

**Issue by Sinder88** [microsoft/coe-starter-kit#8036]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Just installed the April release and when opening the Power BI Dashboard i noticed that the AI Credit usage page is showing errors 

<img width="941" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/109826106/e0121ffc-eb8d-465c-bf5f-cc4d01f66ddf">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Production COE Toolkit

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2867

**Comment by Jenefer-Monroe** [comment]
thanks for posting, tracking for May

**Comment by LucX4** [comment]
I'm having the same problem:

![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/f3468016-4beb-4d90-8cce-a4dd4bd63bee)

**Comment by MeinaHe** [comment]
We had the similar error earlier, but we fixed it by checking and updating the environment URL in Power Query Editor for the AI Credit Usage table are sourced to the right environment URL.  Hope this helps.

**Comment by Sinder88** [comment]
Hi. I used the [Production_CoEDashboard_April2024.zip] and the error message is now gone, however the views are totally blank. We have current AI Credits assigned and in use, so i find that strange. Which flows pull this data? I'd like to check if they are running successfully.

**Comment by LucasCXavier** [comment]
Hi @Sinder88,
Please check this out: https://github.com/microsoft/coe-starter-kit/issues/8066
The Flow has the following filter in the list rows step:(Microsoft.Dynamics.CRM.LastXDays(PropertyName='msdyn_processingdate',PropertyValue=1)
This means the data collection is only looking back one day.

**Comment by Sinder88** [comment]
Thanks for this info. By checking the flow, i found out that the environment is marked as excused from inventory. So i have switched it to no longer excused and will wait for the flow to run tomorrow. 

Strange it seems all of my new environments default to excused from inventory. Is that normal?

**Comment by Jenefer-Monroe** [comment]
@sinder88 what value do you have for this env var?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bbecd1b2-fb47-4cd0-8e33-0696015ea03b)

**Comment by Sinder88** [comment]
It's set to No
![image](https://github.com/microsoft/coe-starter-kit/assets/109826106/84d577f1-d546-4baf-afd7-d88007b13b0b)

**Comment by Jenefer-Monroe** [comment]
Yes that needs to be set to yes. A value of no says that all new envts will be excused from inventory.

**Comment by Sinder88** [comment]
Noted thanks. I've made the change. Will review results on Monday.

**Comment by Jenefer-Monroe** [comment]
great. You may need to reboot the flows that reference it. Sometimes env vars get cached in flows.

**Comment by Sinder88** [comment]
Checked the flow and we see there is data pulling for the AI builder credits but seems the dashboard is not working:

![image](https://github.com/microsoft/coe-starter-kit/assets/109826106/e53f87d7-c8de-40e2-903a-bdbd5b3decbf)

![image](https://github.com/microsoft/coe-starter-kit/assets/109826106/56f7b38b-729e-438c-b65c-d2abe983f764)

**Comment by Jenefer-Monroe** [comment]
great! You now have your data!

Did you use the attached from above? Note we shipped with a bug the first time where we pointed to our own test tenant.
[BYODL_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14958010/BYODL_CoEDashboard_April2024.zip)
[Production_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14958009/Production_CoEDashboard_April2024.zip)

**Comment by Sinder88** [comment]
Thanks. This one is working now :)
