### ISSUE TITLE
[CoE Starter Kit - BUG] Filters not working in Cloud flows Power BI report

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#804]
### Describe the issue

The filters for Creator, Department, Connector and Action do not filter the list of Cloud Flows shown on the Cloud Flows tab of the legacy Power BI report.

### Expected Behavior

I am expecting that when values are selected in either of the Creator, Department, Connector or Action drop downs the Cloud flows list is filtered.  This is the same behavior as when a Display Name or Environment is selected, which does filter the Cloud flows list.

![image](https://user-images.githubusercontent.com/41050216/125040794-25710680-e0ec-11eb-8641-537ac6a5a987.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Dataverse_CoEDashboard_202106

### Steps To Reproduce

1. Open the Dataverse_CoEDashboard_202106 Power BI report
2. Navigate to the Cloud flows tab
3. Select a value from the Creator drop down
4. The flow list refreshes but does not filter

### Anything else?

Looks like the wrong fields are being used for the drop down filter fields.  For example, the Creator drop down is using the **Maker** table's **admin_displayname** field, however, it should be using the **Flow Makers** table's **admin_displayname** field - this gives the expected behaviour

![image](https://user-images.githubusercontent.com/41050216/125040332-a2e84700-e0eb-11eb-8a3f-e9da7a93737b.png)

**Comment by manuelap-msft** [comment]
Hello,

we released the July version of the reports yesterday, would you be able to try those please? We have looked at many of these issues and fixed them. You can download the latest version of the dashboard directly from here: https://github.com/microsoft/coe-starter-kit/tree/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit

Please let me know if you continue to see issues with the July version!

Thank you
Manuela

**Comment by HamishSheild** [comment]
Hi @manuelap-msft , thanks, I have now got the new version of the Power BI report and looks like changes have been made to this report which kind of address this issue.  However,  I now have new issues.  I will close this issue and raise new ones
