### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE- Core Component not generating "Office 365 Management API" custom connector

### ISSUE THREAD

**Issue by JO20232425** [microsoft/coe-starter-kit#8042]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Core Component not generating "Office 365 Management API" custom connector. 

### Expected Behavior

"Office 365 Management API" custom connector should be visible after core component gets installed 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Core component

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Download latest version COE Starter Kit.
Extract COE Starter Kit zip files
Import "CenterofExcellenceCoreComponents_4.29_managed" solution by selecting Upgrade Option.
Click next 
Once installed, check custom connectors

AB#2874

**Comment by Jenefer-Monroe** [comment]
Hello, the custom connector was deprecated in August 2023. 

We have switched to the following more reliable mechanism to gather audit logs [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)
If you are able to convert to using this you should. Please look at step 4a in this write up for how to do that: https://github.com/microsoft/coe-starter-kit/issues/6018#issue-1792462718

If you would like to continue using the old methodology to collect audit logs, we did capture the CC and put it in a separate solution that you can download and use. Do note though that its not something we will be able to help with: https://github.com/microsoft/coe-starter-kit/issues/6017

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
