### ISSUE TITLE
[CoE Starter Kit - QUESTION] Populating Power Platform User table with Azure Groups from Azure Entra ID

### ISSUE THREAD

**Issue by VVictor99** [microsoft/coe-starter-kit#8043]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have installed CoE Starter Kit v4.22.

I have attached a screenshot of the table I am trying to populate with Azure Groups records. I can see no Processes(flows) related to this table(dependencies) which would query the Azure Entra ID for groups. Does CoE have such a functionality? Any tips on how I can implement it myself or which connectors I should use/look into?

![image](https://github.com/microsoft/coe-starter-kit/assets/166723202/6daf1b73-6431-4260-91bf-9533c4258696)

Thank you!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

AB#2875

**Comment by Jenefer-Monroe** [comment]
Hello this is populated by the **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_** flow and its helpers. It finds groups (and users and service principles) with which canvas apps are shared and enters then into this table. We are currently doing a big rework of this flow to make it nicer so and then hope to extend to do the same for flows and Model Driven Apps. 

So if you run that flow you should see examples you can simulate for accuracy of the data format. 

As of the new April release, the following flow also keeps it the table up to date for things like the group size: **_CLEANUP - Admin | Sync Template v3 (Orphaned Users)_**

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
