### ISSUE TITLE
Search is not working in "Set App Permissions" Canvas App.

### ISSUE THREAD

**Issue by potluri96** [microsoft/coe-starter-kit#8044]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Search is not working in "Set App Permissions" Canvas App. The admin is trying to use search for the orphaned app section.

### Expected Behavior

Search should be working

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Set App Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1) Played the "Set Permission App"
2) Selected "Orphaned App" 
3) Searched for an app in the search box
4) The search is happening but results are not yielding

AB#2876

**Comment by Jenefer-Monroe** [comment]
Hello this app is being deprecated in favor of the new Manage Permissions app which you will see in the April release. 
Please take a look!
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d4a5bd1b-dc45-443c-b4d2-cacdde1d8b0a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
