### ISSUE TITLE
power bi usage in coe starter kit

### ISSUE THREAD

**Issue by Sahar-rad** [microsoft/coe-starter-kit#8045]
### Describe the solution you'd like

I recently set up the starter kit and noticed there isn’t a report page for Power BI usage. Considering Power BI is a key component of the Power Platform, I'm exploring how to integrate this into our reports.

AB#2877

**Comment by Sahar-rad** [comment]
Thank you for the reply. How can I connect with them?

**Comment by Jenefer-Monroe** [comment]
Sorry I'm really not sure. I tried to find an access point to them online and cant find one. 
Perhaps someone else in the community here can assist.

**Comment by Sahar-rad** [comment]
Thank you for your follow up

**Comment by Sahar-rad** [comment]
Thank you for your assistance.

**Comment by Jenefer-Monroe** [comment]
sorry I dont understand your question. 
we do not have the ability to add information about PBI to the kit, you are welcome to extend it yourself though

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Sahar-rad** [comment]
Hi Jenefer, I can extend starter kit through new solution, correct?
