### ISSUE TITLE
Error with HTTP Request in Flow - SetupWizard>GetUserDetails

### ISSUE THREAD

**Issue by v7herman4** [microsoft/coe-starter-kit#8046]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The COE Setup and Upgrade Wizard shows "error loading control". I've tracked it down to an error in the flow SetupWizard>GetUserDetails. On the step "Invoke an HTTP request" I get the following error: <redacted>: Tenant '<redacted>' request is being redirected to the National Cloud 'MicrosoftOnline.COM'.

Note that I'm running in a GCC tenant. My connection AND my Graph URL variable are using the GCC endpoint: https://graph.microsoft.us/

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

SetupWizard>GetUserDetails

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Launch the COE Setup and Upgrade Wizard application. Note the "error loading control" message. Navigate to the SetupWizard>GetUserDetails last known run and view the error.

### Anything else?

![Screenshot 2024-04-11 121244](https://github.com/microsoft/coe-starter-kit/assets/89024016/9c9c04b8-4e00-4d0e-9f57-51493130156a)

**Comment by v7herman4** [comment]
I'm assuming this Flow is doing this because it may be calling this non-GCC cloud URL:  https://learn.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=http 

I updated the flow to immediately always return Yes to the PowerApps trigger and the COE Setup and Upgrade Wizard app now loads. Not ideal but a workaround.

**Comment by Jenefer-Monroe** [comment]
Hello. Yes unfortunately we coudl not find a way around you folks doing this manual step of adding the env var during import of the solution. Please see:

https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#set-up-the-inventory-components-using-the-setup-wizard

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/969182dd-94a0-43a7-95d2-a803420a1129)

**Comment by v7herman4** [comment]
Hi Jenefer - Assigning the variable in gov clouds is straightforward and easy enough. The challenge here is that the HTTP connector is calling a URL outside the gov clouds to get user info and thereby causing the app error.

**Comment by Jenefer-Monroe** [comment]
Correct but its only doing that because the env var wasnt filled. 
Basically we had to do it this way because this flow needs to run at boot of the setup wizard, so we couldnt wait to find out your cloud before we do this work. So for non-commercial you need to fill this in on first setup (its remembered so you only need to do it that one time)

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6f925d3d-b955-4b08-aba7-240cbfdbf8d7)

**Comment by v7herman4** [comment]
I assume you're talking about a potential problem or often users forget to fill in the env var? I had the environment variable filled in as well as a valid HTTP connection with the appropriate URLs for government and am experiencing the error above.

**Comment by Jenefer-Monroe** [comment]
Can you please show me its path in this section?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d0b73abf-e0ea-4065-a47b-9cd05f2c75f6)

**Comment by v7herman4** [comment]
![1-Screenshot 2024-04-19 130233](https://github.com/microsoft/coe-starter-kit/assets/89024016/672f503a-5f3b-41de-94c4-baa2f7bbe436)
![2-Screenshot 2024-04-19 130321](https://github.com/microsoft/coe-starter-kit/assets/89024016/4163c73a-53a6-4927-8115-a3340fdcf3a1)
![3-Screenshot 2024-04-19 130427](https://github.com/microsoft/coe-starter-kit/assets/89024016/6505dcd5-bbcf-4dea-8134-2ffcb15ff8c0)

**Comment by Jenefer-Monroe** [comment]
Is this the correct graph url for you? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3267db6e-5c64-4eae-91e3-175161c52ef0)

If so, please go see if the connector got pointed to the wrong URL:
Make sure all the **_HTTP with Microsoft Entra ID (preauthorized)_** connections are pointing to your graph URL ![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/911668af-099e-41a5-a248-40e98bb9fc4e)

**Comment by v7herman4** [comment]
Yes, that's the correct URL. The TK is in GCC. Both the environment variable and the connecter have the URL as noted.

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of the connection you used?

**Comment by Jenefer-Monroe** [comment]
OK I"m not sure. It looks like the URL is correct so I dont know why its failing for you. Seems like it might be a product bug. 
You said you did a workaround, what did you do?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by v7herman4** [comment]
Sorry for the delay, if you can still look into this it would be appreciated. My work-around was to edit the Get User Details Flow and hard-code a positive result. Then the app started just fine.

That doesn't solve the issue with the cross-cloud error but it does get the app running.
