### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Portals) fails

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#8047]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting the below error 

![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/ec7c12e5-d808-4a25-8438-8a5c7be323fc)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Portals)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2879

**Comment by Jenefer-Monroe** [comment]
Hello. Likely something in the old sync flows added bad data and it was just not known until now as we changed to this set logic technique. 

Please go to the **_Power Pages Site_** table > Click edit to see all data > Add/Remove columns until you see the below
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/292196d3-0d52-4134-be06-1f43c048fa87)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc9846fd-2f42-44a4-81c2-a632fab12052)

Now filter to where there Power Pages Website ID - Does not contain data > Delete these records. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7698e381-4d67-4b26-ad24-a7a37af6686c)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/02046caa-6c18-42d2-a738-d722918ee886)

Then do the same for the Power Pages Unique ID column. 
Now the flow will pass and lets hold for a few days to make sure it doesnt return.

**Comment by PPCan** [comment]
Done.  Thanks.  I'll report back with results.

**Comment by PPCan** [comment]
Seems to have fixed it!

**Comment by Jenefer-Monroe** [comment]
Wonderful! I'll go ahead and close out then.
