### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Security Roles) fails

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#8048]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting the below.  Not sure what's wrong.
![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/9fdfff22-ec7f-4795-8c2f-2564e0a9a42c)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Security Roles)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2880

**Comment by Jenefer-Monroe** [comment]
Hello can you please get me the error from that point of failure? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0df985d6-0294-4eed-929a-358848071877)

**Comment by PPCan** [comment]
{
    "statusCode": 400,
    "headers": {
        "Cache-Control": "no-cache",
        "x-ms-service-request-id": "15baab5d-1e7c-4201-8714-7e689de29d2c,81af4ab3-1d1b-4134-948f-229b54c188e6",
        "Set-Cookie": "ARRAffinity=4a5bce33e77c478e022c509def064bdc137b7e2dba9b0c9d9756ee83dee52eb3f16921585aa9d18b9e2a3e899a56f8075a9e4d1d722668af0a49aafc12547a0608DC59C42115CCE01431146031; path=/; secure; HttpOnly,ReqClientId=d2963a03-c1e0-47ef-8021-3caf074728b0; expires=Wed, 11-Apr-2074 00:40:08 GMT; path=/; secure; HttpOnly,ARRAffinity=4a5bce33e77c478e022c509def064bdc137b7e2dba9b0c9d9756ee83dee52eb3f16921585aa9d18b9e2a3e899a56f8075a9e4d1d722668af0a49aafc12547a0608DC59C42115CCE01431146031; path=/; secure; HttpOnly",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
        "REQ_ID": "81af4ab3-1d1b-4134-948f-229b54c188e6,81af4ab3-1d1b-4134-948f-229b54c188e6",
        "CRM.ServiceId": "CRMAppPool",
        "AuthActivityId": "2849b514-52cd-4c5e-a42b-f2339c0ba5d0",
        "x-ms-dop-hint": "48",
        "x-ms-ratelimit-time-remaining-xrm-requests": "1,170.30",
        "x-ms-ratelimit-burst-remaining-xrm-requests": "6663",
        "OData-Version": "4.0",
        "X-Source": "55191200832471071381061731456103245179181149424424919219156191972191431791712420155213,4249140120132821715923315717771187120912710923899861222202511959281761761081563",
        "Public": "OPTIONS,GET,HEAD,POST",
        "Date": "Thu, 11 Apr 2024 00:40:07 GMT",
        "Allow": "OPTIONS,GET,HEAD,POST",
        "Content-Type": "application/json; odata.metadata=full",
        "Expires": "-1",
        "Content-Length": "193"
    },
    "body": {
        "error": {
            "code": "0x0",
            "message": "There is an unterminated literal at position 101 in 'admin_name eq 'stephane D' and _admin_environment_value eq 626ab826-237c-4ba9-aa78-25f663aeba1b'."
        }
    }
}

**Comment by Jenefer-Monroe** [comment]
Please open the flow in edit mode and show me what you see here: it should be the equation shown:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4603cf86-c790-4ead-9e69-b8212e757d17)

And then also here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/696ba790-a72d-43dd-84c3-b7c543747efe)

**Comment by JawnLegend** [comment]
Hi, 

Any update on this? My flow is still failing..

**Comment by Jenefer-Monroe** [comment]
Hello it sounds like you either arent on the build where this was fixed (4.29) or you have unmanaged layers on the flow. Can you please check?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
