### ISSUE TITLE
[CoE Starter Kit] Innovation Backlog - new version is lower

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#805]
The version of the new release is lower than the previous version, so upgrade does not work.

**Comment by JeneferM-MSFT** [comment]
looks like you are resolving now

**Comment by medicineshow** [comment]
Is there an update to this as I have the same issue and it is the latest download from Git?

**Comment by JeneferM-MSFT** [comment]
closing out now that we've moved on to August
