### ISSUE TITLE
[CoE Starter Kit - BUG] Governance Dashboard Listing all Environments Missing DLP in GCC 

### ISSUE THREAD

**Issue by Kappen1** [microsoft/coe-starter-kit#8050]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

On a GCC tenant the Environments without DLP card lists a number equal to all of the environments in the tenant.  

### Expected Behavior

Would only show the environments that are missing a DLP policy

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April Release 

### What app or flow are you having the issue with?

Power Platform Governance Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Install the Power Platform Governance Dashboard.  I'm not 100% sure this is only happening on GCC tenants but since it hasn't been reported already its likely  

### Anything else?

Looking in the raw data I am noticing some URL issues in the PPAC column.  The URL is pointing to commercial, instead of GCC.  I'm unsure if this is causing the issue or not.   

AB#2883

**Comment by Jenefer-Monroe** [comment]
Hello. Are you referring to this one we just shipped? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4d1b6743-5a5d-40dd-a92d-0313b5e15ecd)

If so, has the driver run since you upgraded? I think the default answer here is "no DLP" and so until the driver runs these would all show a false positive.

**Comment by Kappen1** [comment]
No it was just upgraded this morning, when I saw the wrong urls in the ppaq column I figured they might be related.

**Comment by Jenefer-Monroe** [comment]
Gotchal. OK please do let me know if its showing correctly after an inventory run.

**Comment by Kappen1** [comment]
Jenifer,

Can you identify the flow that has to run to update the data?

**Comment by Jenefer-Monroe** [comment]
Do you use the Setup Wizard on upgrade? Please do use that as it will ensure all the new/correct flows are on and all the new/correct env vars are filled. 

For this in particular it is the driver flow: **_Admin | Sync Template v4 (Driver)_**

**Comment by Jenefer-Monroe** [comment]
I'm not sure what issue you are referencing. To my knowledge there are no known issues with GCC today.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
