### ISSUE TITLE
[CoE Starter Kit - QUESTION] Getting Microsoft.SharePoint.Client.ResourceNotFoundException with "Admin | Sync Template v4 (Connection Identities) flow

### ISSUE THREAD

**Issue by whorn76** [microsoft/coe-starter-kit#8052]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

it looks like we're getting some sort of user not found error when the above flow is running.  I'm not sure if the user has some sort of orphaned account that isn't being properly handled.  It appears that the GUID for the UPN its referencing no longer exists, but I'm not sure how its supposed to handle it and whether its a bug or another issue.
![Screenshot 2024-04-11 122453](https://github.com/microsoft/coe-starter-kit/assets/4932270/383a19e1-05ec-4381-b141-b913c5168523)
![Screenshot 2024-04-11 122321](https://github.com/microsoft/coe-starter-kit/assets/4932270/27473012-de68-47e6-80c0-3b308a9917df)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 2024 4.94

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Connection Identities)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2886

**Comment by whorn76** [comment]
Hi Jenefer.  I don't have a screenshot directly.  but it goes down the "404 User Not Found" path of that switch statement.  And then that is where that first screen shot comes from is down the yes path of the condition under that 404 path.

**Comment by Jenefer-Monroe** [comment]
Please validate that the user identity running the flow has System Admin permission to the environment.

**Comment by Jenefer-Monroe** [comment]
But can you please go check in that individual environment for the Sys Admin SR?
There have been some recent changes and sometimes users are given the role even though they have the PPAdmin Role
https://admin.powerplatform.microsoft.com/environments > select environment > Settings > Users + Perissions > Users
Find the user and click their name to see their roles
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f9b856f2-e671-43a5-acd8-77f8ed271336)

**Comment by whorn76** [comment]
Can you explain a little more?  Why would it need the SA role if it's a Power Platform Admin?  And if that was indeed the case would we then need to add it as an SA to each environment?  Thanks for your help!

**Comment by Jenefer-Monroe** [comment]
In the past, PPAdmin Role users would get added as a Sys Admin of any new environments as they came in. And if you tried to remove them from existing environments they got re-added automatically. This was just the way the product team dealt with their privaledged roles.

However there is a new PIM feature in Preview that changes this behavior and so some tenants are seeing this early (before the kit has been able to adapt). 

Can you please check for me?

**Comment by whorn76** [comment]
Thanks.  Asking the customer now.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
