### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is the acquired data stored?

### ISSUE THREAD

**Issue by syou0224ondr176mocoksrg** [microsoft/coe-starter-kit#8053]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Tenant apps, flows, and audit logs acquired by Admin-Sync Template v3(driver) are stored in a table.
Is the stored data appended to or overwritten from the previous data?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin-Sync Template v3(driver)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2887

**Comment by Jenefer-Monroe** [comment]
Hello. In most places in the kit we update existing records if they exist or write new ones if they do not.
This is done by using the products IDs (ex Flow id) as they same ID for our inventory wherever possible, or adding unique fields to lookup so we dont lose track of records. 
Hope that makes sense.

Please also consider attending our monthly office hours. We talk about new features, upcoming changes, and spend most of the time answering your questions. 
More information:
Join the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours) held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
Click here to download the calendar file to add to your calendar: [Calendar file](https://aka.ms/coeofficehours/ics)

**Comment by Jenefer-Monroe** [comment]
Correct there are a set of flows that check for deleted items in the tenant and then cleans up the inventory.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
