### ISSUE TITLE
[CoE Starter Kit - BUG] I CoE BYODL - Power Query admin_CoEBYODLPowerQuery error

### ISSUE THREAD

**Issue by Haleon-COE** [microsoft/coe-starter-kit#8054]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

CoE BYODL - Power Query admin_CoEBYODLPowerQuery has connected and showing green tick mark but next button is not working while importing Core solution
<img width="934" alt="coe-2" src="https://github.com/microsoft/coe-starter-kit/assets/166788634/636fd80d-b53e-4525-8e55-bca82b43d16f">
<img width="913" alt="COE-1" src="https://github.com/microsoft/coe-starter-kit/assets/166788634/b7c63c6d-d573-4081-b012-1bb5d1732418">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Core component

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Upgrading the coe - core component from 3.53 to 4.29
2. Downloaded the latest version and imported the solution 

### Anything else?

<img width="934" alt="coe-2" src="https://github.com/microsoft/coe-starter-kit/assets/166788634/3bc9708d-6f32-4c26-b514-0f89bb76e079">

AB#2888

**Comment by Jenefer-Monroe** [comment]
Unfortunately this appears to be an issue with the product's import feature and not something with the kit. 
My assumption is that this was intermittent and will correct itself and if you try again it will work. 
Please let me know.

**Comment by Haleon-COE** [comment]
Hi Jenefer,

We have tried to import multiple times past from yesterday, but with same error.

Thanks,
Pp

________________________________

**Comment by Jenefer-Monroe** [comment]
Unfortunately this is an issue before the kit even comes into play so I'm not sure how to help. 
Perhaps go look at your connections and make sure they are all in a healthy state. 
Perhaps there delete this connection and create a new one just in case, and try again.

**Comment by Haleon-COE** [comment]
Hi Jenefer,

We delete all the connections and tried to import the solution but still we still don’t see Next button.
Please assist us.

***@***.***


Thanks,
PP

**Comment by Haleon-COE** [comment]
<img width="915" alt="COE-Day2" src="https://github.com/microsoft/coe-starter-kit/assets/166788634/27af9f69-5018-4aca-bbe0-5e3e49e9888a">

**Comment by Haleon-COE** [comment]
Hi Jenefer,

We were able to install the Core components However we are getting the below error

***@***.***

Thanks,
PP

**Comment by Jenefer-Monroe** [comment]
Hello pictures do not come through if you reply in email, you must log in to GitHub to share them.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
