### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot import nurture solution. Solution dependencies exist.

### ISSUE THREAD

**Issue by Wookie2024** [microsoft/coe-starter-kit#8057]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Previous upgrade completed successfully (Nurture components 3.13). Import failed due to solution dependencies - cannot uninstall. Custom flows noted and ObjectName: admin_sharedcommondataserviceforapps_77293.

![NurtureImportError](https://github.com/microsoft/coe-starter-kit/assets/166804074/a46b28a8-c395-45e6-9739-d1629d3427a1)

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

April release

### What app or flow are you having the issue with?

Import

### What method are you using to get inventory and telemetry?

None

AB#2891

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Wookie2024** [comment]
![CoESolutions](https://github.com/microsoft/coe-starter-kit/assets/166804074/c2be5197-0f6d-454f-b480-09680689d406)

**Comment by Wookie2024** [comment]
![CoESolutions](https://github.com/microsoft/coe-starter-kit/assets/166804074/984186ba-06a7-4a40-889d-3708c382cfdc)

**Comment by Jenefer-Monroe** [comment]
what were you upgrading from?

**Comment by Wookie2024** [comment]
The previous version. I was facing an issue with the previous update whereby the DLP Request | Process approved policy change flows were failing so I was hoping the latest update would resolve that, but now I am facing the import issue with the nurture component .

**Comment by Wookie2024** [comment]
The error notes several custom flows I have created. "Failed to upgrade solution. Solution dependencies exist, cannot uninstall." Then it lists all my custom flows and ObjectName: admin_sharedcommondataserviceforapps_77293.

**Comment by Jenefer-Monroe** [comment]
Can you please go find this connection reference and look at its dependencies:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a2c7deb9-a2e3-4d73-a9f4-8ef35be779b3)

Show me the list you see there please.

**Comment by Wookie2024** [comment]
I don't have the "CoE Core - Dataverse Legacy" in my default soluion/connection references:
![ConnectionRef](https://github.com/microsoft/coe-starter-kit/assets/166804074/5d61e0e6-48e5-4c5c-9a35-ec06b15258a5)

**Comment by Wookie2024** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/166804074/e4a8c52f-5d72-4964-8e25-c66ed48d1c80)

**Comment by Wookie2024** [comment]
All resolved now. Thank you.

**Comment by Jenefer-Monroe** [comment]
wonderful thanks for the update! I'll go ahead and close but please do return with new issues as needed.
