### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to find the connections used by environments

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#8058]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way to see the connections used by an environment?

We need to see what projects are using certain connections.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2892

**Comment by Jenefer-Monroe** [comment]
You can do this on a connector by connector basis in the Power Platform Admin View app
Select a connection of interest and then you can see what apps/flows use it, and sort/filter by envts
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b8c72664-6f9f-41f4-a78b-0544a10c1995)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4ba4c21e-bf27-41d0-b5fa-b1f04a437fd7)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
