### ISSUE TITLE
[CoE Starter Kit - QUESTION] Request Orphaned Objects Reassigned (Parent)

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#8060]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I turned on the Orphaned Object flows on the 1/4/24, all of the child flows have run successfully but the parent flow has not completed.
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/836d4d55-ad59-412a-a838-5debfea49c0e)
as this runs every 7 days I now have 3 still running.
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/43102fbf-306c-4988-b529-be0970113a2b)
Is there anything I can do? This is is out production tenant, I have set this up in test and not having this issue, I do not want to cancel and re-submit the flow as it will send out the notifications again to the users.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.16

### What app or flow are you having the issue with?

 Request Orphaned Objects Reassigned (Parent)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2896

**Comment by Alyson95170** [comment]
All of the child flows are showing with a completed run for the parent flow that started running on 1/4/24.
for the 2nd run on 8/4/24 I have some child flows till running, these have been running for over 7 days, I expect these to complete tomorrow.

**Comment by Jenefer-Monroe** [comment]
Please open one of the child flows that is still running for the 8/4/24 instance to see where it is sitting in the run.

**Comment by Alyson95170** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/e2bd2d07-8682-4ae2-a768-36619a386708)

**Comment by Jenefer-Monroe** [comment]
OK yes that should expire today then.

**Comment by Jenefer-Monroe** [comment]
Please open the 1/4/24 parent instance, how many iterations is this loop performing?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7cb9298d-54bb-4b30-a253-d960c589790a)

**Comment by Alyson95170** [comment]
All my child flows have successfully ran for this parent flow 
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/c13f477b-7283-4824-935f-f2d928ad4081)

**Comment by Jenefer-Monroe** [comment]
Aw there it is. We can only concurrently run 50 at a time. 
Thanks for posting had not even thought of this as an issue. 
As a workaround, can you take this return call in the child and move it to the top? 
Basically we would just not wait for the result and that should allow all 127 to run at the same time. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/24bbc433-ab91-4bce-8b61-92fabf2914b5)

**Comment by Alyson95170** [comment]
Yeah I can give that a try, I guess this will create an unmanaged layer?
Will I need to cancel previous runs of the parent flow and re-submit?

**Comment by Jenefer-Monroe** [comment]
Yes it will create an unmanaged layer. If it works for you I can make the change locally though so it wouldn't be forever.

Yes I suggest you cancel all the existing runs, both Parent and Child, before you try it

**Comment by Alyson95170** [comment]
Thanks Jenefer, I will wait till the end of the week to cancel these runs, this will allow time for the users that received the notification today to respond.

**Comment by Alyson95170** [comment]
Hi Jenefer
I completed the steps you suggested within out test tenant, unfortunately this did now work.
Is there anything else I can try ?
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/6503271b-ad4f-4646-8ca5-31ecc6b1b930)

**Comment by Jenefer-Monroe** [comment]
Oh yes sorry that is a variable in the return, you'll want to hard code that as shown here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ad545c56-f959-4a43-86bb-8fb57945315b)

And then also change the **_Configure run after_** settings for the next action to both successful or skipped
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/67456d2a-6e9b-4f0a-ab1c-1c4faa66393d)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/06fccb39-d0a0-4d1d-981d-10e90c16988e)

**Comment by Alyson95170** [comment]
Thanks its running now in test.
I will change this in production at the end of the week, then when the parent flow runs on Monday hopefully this will only be for 1 week :)

**Comment by Alyson95170** [comment]
Perfect. I will keep you updated

**Comment by Alyson95170** [comment]
Hi Jenefer, the flow is running as expected and sending out the Teams message to the users, I will let you know once the parent flow completes.
I did notice that the flow shows as a successful run when the user is not found, is there something that can be done in a future release to show these as failed runs?
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/37d7093b-9b2f-4cec-b3a5-8630a7506a50)

**Comment by Jenefer-Monroe** [comment]
Can you please make that change and validate by just rerunning this one failure in you showed? 
Then we'll be code complete for May

**Comment by Jenefer-Monroe** [comment]
Marking as code complete for May

**Comment by Alyson95170** [comment]
Hi Jenefer
I have noticed that the parent flow runs on the one day now rather than for the 7 days, is this expected?

**Comment by Jenefer-Monroe** [comment]
No that is not expected to me. From reading the description it looks like it was to someone though.
I've quickly changed this back to weekly for May as well. Thank you so much!
