### ISSUE TITLE
Admin | Sync Template v3 (Environment Properties) fails after update

### ISSUE THREAD

**Issue by mirnablazincic** [microsoft/coe-starter-kit#8061]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I don't have much experience in the Center of Excellence, so I would like to ask for help with this issue.
Before the update, all flow runs were executed successfully, so I'm not sure why this error occurs.

Also, on some environments, the flow is executed successfully, and on others it fails. We are getting following error: The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'Required properties are missing from object: boolean, text_3.'.

![2024-04-15 11_21_16-Run History](https://github.com/microsoft/coe-starter-kit/assets/114922804/6c5fac65-cf67-4698-ab53-d1da580b1f86)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Environment Properties)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2897

**Comment by Jenefer-Monroe** [comment]
Hello, that flow no longer exists in the kit in the 4.29 build. 
I suspect you have a failed upgrade.
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by mirnablazincic** [comment]
Hi Jenefer,
Thank you for your quick reply. Here is the requested screenshot.

I belive I know why there is flow in the kit that is no longer being used. A colleague suggested that instead of the 'Upgrade' option I should choose 'Update', so that components that are no longer in use were not deleted. Is there a way to handle this?

***@***.***


Many thanks,
Mirna

**Comment by Jenefer-Monroe** [comment]
Hello please note that screenshots do not come through if you respond in email, you need to log in to GitHub to share them. 

Yes you should always use the Upgrade option when upgrading the kit solution. That should keep your object list clean. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/90f0ffe2-6dd2-4821-8c23-a13f546980dd)

**Comment by mirnablazincic** [comment]
I apologize, here is the screenshot again:

![image](https://github.com/microsoft/coe-starter-kit/assets/114922804/a003e287-e85f-4f60-9daf-fb68911251d5)

Is it ok if import the solution again and choose the 'Upgrade' option?

**Comment by Jenefer-Monroe** [comment]
I'm not sure I havent done that before but I presume that should work yes.

**Comment by mirnablazincic** [comment]
Hi, I just tried to import the solution again, but there is no Upgrade option available. Could you please tell me what other options I have to solve this issue? Thank you in advance!

![image](https://github.com/microsoft/coe-starter-kit/assets/114922804/778a1355-498b-4d3e-bc55-24ce7df1ab3e)

**Comment by Jenefer-Monroe** [comment]
Yes it appears not. 
You should always do the upgrade going forward. I suppose you can just turn this flow off for now and next time when you upgrade (with upgrade) it will be removed.

**Comment by mirnablazincic** [comment]
Thank you for your help. The flow is now turned off. I hope that with the next upgrade, all components that are no longer used will be deleted. 
May I just ask one more thing - since this flow is no longer in use, which one collects data about environments instead?

**Comment by Jenefer-Monroe** [comment]
It has been incorporated into other existing flows.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
