### ISSUE TITLE
[CoE Starter Kit - BUG] Importing CenterofExcellenceAuditComponents 3.20 - (Solution dependencies exist - admin_CoEGovDataverseLegacy)

### ISSUE THREAD

**Issue by wramey82** [microsoft/coe-starter-kit#8063]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Importing CenterofExcellenceAuditComponents 3,20 as an upgrade to our currently installed version of 3.16 and are getting this error message:  "Solution "Center of Excellence - Governance Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoEGovDataverseLegacy, Id: b666b0cc-37c2-4b6c-b978-52ebfeb9c883, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - CloudFlowOperations Gov, Id: b538d20c-d1ef-eb11-bacb-00224820693c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published ."  
![image](https://github.com/microsoft/coe-starter-kit/assets/1717478/6fc48d5e-5b12-48e8-9487-eee9fcd9e2e2)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.16

### What app or flow are you having the issue with?

admin_CoEGovDataverseLegacy

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Import Solution -> Upgrade -> Next
![image](https://github.com/microsoft/coe-starter-kit/assets/1717478/4c58e02d-4e3b-42cc-a1df-226c52a99516)

### Anything else?

[Center of Excellence - Governance Components_import.zip](https://github.com/microsoft/coe-starter-kit/files/14979594/Center.of.Excellence.-.Governance.Components_import.zip)

AB#2900

**Comment by Jenefer-Monroe** [comment]
The flow listed is no longer part of the gov solution for quite some while now. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e7ac1a02-66b2-497a-9394-511c8da18980)

Can you please find that flow in the envt and delete it?

**Comment by wramey82** [comment]
So, for some reason I found the "HELPER - CloudFlowOperations Gov" in the Default Solution and was able to remove the Flow and its other dependences.  This has resolved the issue.  Thanks for the help!

**Comment by wramey82** [comment]
<html>
<body>
<span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14.6667px; line-height: inherit; font-family: &quot;Aptos Narrow&quot;, Calibri, sans-serif, &quot;Mongolian Baiti&quot;, &quot;Microsoft Yi Baiti&quot;, &quot;Javanese Text&quot;, &quot;Yu Gothic&quot;; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">DAWN.HARDING@LibertyMutual.com;RENEE.STEPHENS@LibertyMutual.com;Charmian.Toh@LibertyMutual.com;KIRA.WAKEFIELD@LibertyMutual.com;Anthony.Scarnati@LibertyMutual.com;TIMOTHY.MILLER@LibertyMutual.comVirginie.Bindeus@LibertyMutual.com;ERIC.HARTER@LibertyMutual.com;Joyce.Witham@LibertyMutual.com;Virginie.Bindeus@LibertyMutual.com;ERIC.HARTER@LibertyMutual.com;Joyce.Witham@LibertyMutual.com;Wendy.Bradley@LMI.com;Brian.Riley@LibertyMutual.com;Wendy.Bradley@LMI.com;Gael.Henville@LibertyMutual.com;MATTHEW.KEANE@LibertyMutual.com;MATTHEW.KEANE@LibertyMutual.com;SUZANNE.MALLETT@LibertyMutual.com;Sean.McKeon@LibertyMutual.com;DANIEL.GRAICHEN@LibertyMutual.com;Amy.Bruno@LibertyMutual.com;Wendy.Bradley@LMI.comWendy.Bradley@LMI.com;christopher.cookinham@LibertyMutual.com;Angela.Moynahan@libertymutual.com;JESSICA.SCHNIEPP@LibertyMutual.com;JESSICA.SCHNIEPP@LibertyMutual.com;Larry.Gibson@LibertyMutual.com;Wendy.Bradley@LMI.com;MICHAEL.BRANCA@LibertyMutual.com;Angela.Moynahan@libertymutual.com;JESSICA.SCHNIEPP@LibertyMutual.comAnthony.Scarnati@LibertyMutual.com;SCOTT.JOY@LibertyMutual.com;ERIC.HARTER@LibertyMutual.com;Penny.Kingston@LibertyMutual.com;ERIC.HARTER@LibertyMutual.com;DONNA.FINLEY@LibertyMutual.com;JOEL.GILLIES@LibertyMutual.com;Sean.McKeon@LibertyMutual.com;JEFFREY.POMROY@LibertyMutual.com;BROOKE.SOKOLNICKI@LibertyMutual.comStacey.Mason@LibertyMutual.com;Wendy.Bradley@LMI.com;Tony.Nuhn@LibertyMutual.com;Erika.Conrad@libertymutual.com;Angela.Moynahan@libertymutual.com;Jerry.Robbins@LibertyMutual.com;Wendy.Bradley@LMI.com;Erik.Larson@LibertyMutual.com;Erik.Larson@LibertyMutual.com;Serkan.Varlikli@LibertyMutual.com;Matthew.Therault@LibertyMutual.com;RENEE.STEPHENS@LibertyMutual.com;CARLO.LAGLE@LibertyMutual.com;CARLO.LAGLE@LibertyMutual.com;Heather.Johnson0969@libertymutual.com;WENDY.BATES@LibertyMutual.com;Scott.Houghtaling@LibertyMutual.com;Josh.Guardino@LibertyMutual.com;Rich.Scaramozza@LibertyMutual.com;RENEE.STEPHENS@LibertyMutual.com;SALLYANN.TAYLOR@LibertyMutual.com;Andrew.Carr@libertyglobalgroup.com;Douglas.Cote@LibertyMutual.com;JOE.TURNER@LibertyMutual.com;Scott.Houghtaling@LibertyMutual.com;KRISTY-LYNN.BAKKE@LibertyMutual.com;CHUCK.BYERS@LibertyMutual.com;Timothy.Mahoney@LibertyMutual.com;Aeron.Babcock@LibertyMutual.com;Kenneth.Chen@LibertyMutual.com;TRAVIS.GODDARD@LibertyMutual.com;John.McBrine@LibertyMutual.com;Jean.Westfall@LibertyMutual.com;ROBERT.FAUCI@LibertyMutual.com;JAMES.MADDISON@LibertyMutual.comPATRICK.CALLAGHAN@LibertyMutual.com;WILLIAM.RAMEY@LibertyMutual.com;Casey.Rydzewski@LibertyMutual.comSALLYANN.TAYLOR@LibertyMutual.com;Erik.Larson@LibertyMutual.com;SUZANNE.MALLETT@LibertyMutual.com;CHRISTOPHER.BRODEUR@LibertyMutual.com;Jennifer.LaPointe@LibertyMutural.com;Julie.Racic@LibertyMutual.com;William.Saunders@LibertyMutual.com;Erik.Larson@LibertyMutual.com;Wendy.Bradley@LMI.com;Wendy.Bradley@LMI.com;ADAM.OPITZ@LibertyMutual.com;RENEE.STEPHENS@LibertyMutual.com;RENEE.STEPHENS@LibertyMutual.com;SCOTT.JOY@LibertyMutual.comErik.Larson@LibertyMutual.com;Erika.Conrad@libertymutual.com;Erika.Conrad@libertymutual.com;MICHAEL.STANTON@LibertyMutual.com;Virginie.Bindeus@LibertyMutual.com;Wendy.Bradley@LMI.com;Thomas.McGuinness@LibertyMutual.com;Anthony.Scarnati@LibertyMutual.com;Erik.Larson@LibertyMutual.com;MITCHELL.SNYDER@LibertyMutual.com;</span><div style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br></div><div style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br></div><div id="Signature" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"><div style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">
  | Billy RameyPrincipal Infrastructure EngineerGlobal Digital Services \| End-User Technology────────────────────Liberty Mutual Insurance225 Borthwick Ave, Portsmouth, NH 03824Phone 603-245-6640 Mobile 603-812-5358Email william.ramey@libertymutual.com
-- | --


</div><p><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 10pt; line-height: inherit; font-family: &quot;Gill Sans MT&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(26, 20, 70);"><a href="https://forge.lmig.com/issues/servicedesk/customer/portal/427/group/3980" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">Click for SharePoint, Power Platform and OneDrive Jira Support</a></span></p><p><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 10.5pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">Have a feature suggestion for us? Submit it<span> </span><a href="https://libertymutual.sharepoint.com/sites/SharePoint/SitePages/OneSharedPower-Feature-Request.aspx" target="_blank" title="https://libertymutual.sharepoint.com/sites/sharepoint/sitepages/onesharedpower-feature-request.aspx" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">here</a>!</span></p><p><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 8pt; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"> </span></p><p> </p></div><div style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br></div><div style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br style="color: rgb(0, 0, 0); font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 14.6667px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</body>
</html>DAWN.HARDING@LibertyMutual.com;RENEE.STEPHENS@LibertyMutual.com;Charmian.Toh@LibertyMutual.com;KIRA.WAKEFIELD@LibertyMutual.com;Anthony.Scarnati@LibertyMutual.com;TIMOTHY.MILLER@LibertyMutual.comVirginie.Bindeus@LibertyMutual.com;ERIC.HARTER@LibertyMutual.com;Joyce.Witham@LibertyMutual.com;Virginie.Bindeus@LibertyMutual.com;ERIC.HARTER@LibertyMutual.com;Joyce.Witham@LibertyMutual.com;Wendy.Bradley@LMI.com;Brian.Riley@LibertyMutual.com;Wendy.Bradley@LMI.com;Gael.Henville@LibertyMutual.com;MATTHEW.KEANE@LibertyMutual.com;MATTHEW.KEANE@LibertyMutual.com;SUZANNE.MALLETT@LibertyMutual.com;Sean.McKeon@LibertyMutual.com;DANIEL.GRAICHEN@LibertyMutual.com;Amy.Bruno@LibertyMutual.com;Wendy.Bradley@LMI.comWendy.Bradley@LMI.com;christopher.cookinham@LibertyMutual.com;Angela.Moynahan@libertymutual.com;JESSICA.SCHNIEPP@LibertyMutual.com;JESSICA.SCHNIEPP@LibertyMutual.com;Larry.Gibson@LibertyMutual.com;Wendy.Bradley@LMI.com;MICHAEL.BRANCA@LibertyMutual.com;Angela.Moynahan@libertymutual.com;JESSICA.SCHNIEPP@LibertyMutual.comAnthony.Scarnati@LibertyMutual.com;SCOTT.JOY@LibertyMutual.com;ERIC.HARTER@LibertyMutual.com;Penny.Kingston@LibertyMutual.com;ERIC.HARTER@LibertyMutual.com;DONNA.FINLEY@LibertyMutual.com;JOEL.GILLIES@LibertyMutual.com;Sean.McKeon@LibertyMutual.com;JEFFREY.POMROY@LibertyMutual.com;BROOKE.SOKOLNICKI@LibertyMutual.comStacey.Mason@LibertyMutual.com;Wendy.Bradley@LMI.com;Tony.Nuhn@LibertyMutual.com;Erika.Conrad@libertymutual.com;Angela.Moynahan@libertymutual.com;Jerry.Robbins@LibertyMutual.com;Wendy.Bradley@LMI.com;Erik.Larson@LibertyMutual.com;Erik.Larson@LibertyMutual.com;Serkan.Varlikli@LibertyMutual.com;Matthew.Therault@LibertyMutual.com;RENEE.STEPHENS@LibertyMutual.com;CARLO.LAGLE@LibertyMutual.com;CARLO.LAGLE@LibertyMutual.com;Heather.Johnson0969@libertymutual.com;WENDY.BATES@LibertyMutual.com;Scott.Houghtaling@LibertyMutual.com;Josh.Guardino@LibertyMutual.com;Rich.Scaramozza@LibertyMutual.com;RENEE.STEPHENS@LibertyMutual.com;SALLYANN.TAYLOR@LibertyMutual.com;Andrew.Carr@libertyglobalgroup.com;Douglas.Cote@LibertyMutual.com;JOE.TURNER@LibertyMutual.com;Scott.Houghtaling@LibertyMutual.com;KRISTY-LYNN.BAKKE@LibertyMutual.com;CHUCK.BYERS@LibertyMutual.com;Timothy.Mahoney@LibertyMutual.com;Aeron.Babcock@LibertyMutual.com;Kenneth.Chen@LibertyMutual.com;TRAVIS.GODDARD@LibertyMutual.com;John.McBrine@LibertyMutual.com;Jean.Westfall@LibertyMutual.com;ROBERT.FAUCI@LibertyMutual.com;JAMES.MADDISON@LibertyMutual.comPATRICK.CALLAGHAN@LibertyMutual.com;WILLIAM.RAMEY@LibertyMutual.com;Casey.Rydzewski@LibertyMutual.comSALLYANN.TAYLOR@LibertyMutual.com;Erik.Larson@LibertyMutual.com;SUZANNE.MALLETT@LibertyMutual.com;CHRISTOPHER.BRODEUR@LibertyMutual.com;Jennifer.LaPointe@LibertyMutural.com;Julie.Racic@LibertyMutual.com;William.Saunders@LibertyMutual.com;Erik.Larson@LibertyMutual.com;Wendy.Bradley@LMI.com;Wendy.Bradley@LMI.com;ADAM.OPITZ@LibertyMutual.com;RENEE.STEPHENS@LibertyMutual.com;RENEE.STEPHENS@LibertyMutual.com;SCOTT.JOY@LibertyMutual.comErik.Larson@LibertyMutual.com;Erika.Conrad@libertymutual.com;Erika.Conrad@libertymutual.com;MICHAEL.STANTON@LibertyMutual.com;Virginie.Bindeus@LibertyMutual.com;Wendy.Bradley@LMI.com;Thomas.McGuinness@LibertyMutual.com;Anthony.Scarnati@LibertyMutual.com;Erik.Larson@LibertyMutual.com;MITCHELL.SNYDER@LibertyMutual.com;




 

 

Billy Ramey

Principal Infrastructure Engineer

Global Digital Services | End-User Technology

────────────────────

Liberty Mutual Insurance

225 Borthwick Ave, Portsmouth, NH 03824

Phone 603-245-6640 Mobile 603-812-5358

Email [william.ramey@libertymutual.com](mailto:william.ramey@libertymutual.com)

 

[Click for SharePoint, Power Platform and OneDrive Jira Support](https://forge.lmig.com/issues/servicedesk/customer/portal/427/group/3980)

Have a feature suggestion for us? Submit it [here](https://libertymutual.sharepoint.com/sites/SharePoint/SitePages/OneSharedPower-Feature-Request.aspx)!

**Comment by wramey82** [comment]
So, for some reason I found the "HELPER - CloudFlowOperations Gov" in the Default Solution and was able to remove the Flow and its other dependences.  This has resolved the issue.  Thanks for the help!

**Comment by Jenefer-Monroe** [comment]
Wonderful thank you so much for letting me know!
