### ISSUE TITLE
[CoE Starter Kit - BUG] 'AI Credits Usage' Table Empty

### ISSUE THREAD

**Issue by LucX4** [microsoft/coe-starter-kit#8066]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team,
Although the 'Admin | Sync Template v4 (AI Events)' flow ran successfully, the AI Credits Usage table appears to be empty.
Do you have any insights into what might be causing this issue?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Admin | Sync Template v4 (AI Events)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2903

**Comment by Jenefer-Monroe** [comment]
Do you know if you have AI Credits being used? And if so, in which environment?
https://learn.microsoft.com/ai-builder/credit-management

**Comment by LucX4** [comment]
Hi Jenefer, 
Yes, at least one environment is using it.

**Comment by LucX4** [comment]
@Jenefer-Monroe
I noticed that the last AI credits usage was on April 3rd. I found successful runs from April 2nd and April 3rd. Could you please confirm the name of the Flow that pulls data into the AI Credits Usage table?
Thanks!

**Comment by LucX4** [comment]
Hi @Jenefer-Monroe,
It's not returning anything in the list step:
![image](https://github.com/microsoft/coe-starter-kit/assets/105860879/abf5dfa9-d367-40e0-84fe-bdef78d7e951)

**Comment by LucX4** [comment]
Got it now, thank you Jenefer.
I noticed that the last AI credits usage was on April 3rd. I asked the user to spend more credits, and now the data is being pulled in correctly.

**Comment by Jenefer-Monroe** [comment]
Sorry thought I did that above but I didn't! : Admin | Sync Template v4 (AI Events)

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thank you so much for following up and letting me know!
