### ISSUE TITLE
[CoE Starter Kit - BUG] Failed to delete Sharepoint form app

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#8069]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have turned on the Orphaned Objects, as the App type is Canvas but this is a SharePoint form app the manager of the orphaned user is unable to delete the app and as admins we are also unable to delete this in the admin view app.

![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/3052859f-bc2b-4393-aa6d-7b5c5ed1b67f)

What would be the best way to remove this from the tenant to ensure the manager of the orphaned user does not continue to receive notifications when unable to delete?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.16

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2906

**Comment by Alyson95170** [comment]
I have managed to find a way to delete this by going through the recourses on the Environment within the admin view.  Found a similar issue in [https://github.com/microsoft/coe-starter-kit/issues/6493]

**Comment by Jenefer-Monroe** [comment]
Thanks for letting us know!
