### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin| Add Maker to group

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8071]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We were setting up CoE and when Add Maker to group flow ran we realized no Maker was added to the group because no sufficient permission was provided to the service Account. So, our OOB flow will never pick up the maker record again as it has already been added to table but never get added to Maker group because of insufficient privileges.
 
Suggested to change the trigger to instant and get all the records in Maker group. However, would like to understand if we can make changes from the product side itself so that this scenario can be handled automatically. Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2908

**Comment by Jenefer-Monroe** [comment]
Hello, thanks for the suggestion. We do have on the backlog a flow people can run to sync up the group and the table at some point later.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
