### ISSUE TITLE
[CoE Starter Kit - BUG] Env Request - Enable Cost Tracking - Clean up 

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8072]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team , please remove these environment variables from the UI if we not using them, it simply creates confusion everytime we do a setup. Thanks 

### Expected Behavior

Should be cleaned from solution if not required

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024

### What app or flow are you having the issue with?

Admin sync Template- V3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Installation of the kit requires this , but not seeing getting used this

AB#2909

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of what you are referencing?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
