### ISSUE TITLE
[CoE Starter Kit - BUG] Admin environment request the page is not back to the detailed page

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8073]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

<img width="830" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/a3dbec42-4669-446b-ac13-6619c3baa7d0">

Go to view policies 

<img width="1163" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/22947e53-aa2f-491b-b565-02bae9d0cfa3">

select Creation Request on Bread Crum to go back 

<img width="746" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/990a8664-b280-4982-b1b5-b672fd0a757f">

Select View button from top ---> it doesn't open the details page as earlier , stuck on the policy page 

<img width="829" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/ccb16d00-3ad6-42a7-ac5f-6818ef2aaa19">

### Expected Behavior

It should display details page 

<img width="713" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/f431f8b4-583b-4156-bf44-62cfc922aa8c">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Admin sync Template- V3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Logged in 

AB#2910

**Comment by Jenefer-Monroe** [comment]
thannks for posting, to area owner for investigation.
