### ISSUE TITLE
[CoE Starter Kit - BUG] "CoE BYODL - When Flow dataflow refresh is complete" flow has wrong child flow defined in "Call Admin | Sync Template v3 (BYODL Flow Properties) action"

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#8074]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The **Call Admin | Sync Template v3 (BYODL Flow Properties)** action in the flow **CoE BYODL - When Flow dataflow refresh is complete** has wrong child flow defined. Should be 

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/f91fd32d-b696-4588-bbfb-a45d60a7b1dd)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CoE BYODL - When Flow dataflow refresh is complete

### What method are you using to get inventory and telemetry?

Data Export

AB#2911

**Comment by Jenefer-Monroe** [comment]
thanks for posting. It looks broken in my dev envt showing the GUID only as though it were a managed envt.
same bug repros in the app version. 
Easy fix for May but will walk to make sure there isnt a generalized issue with the child flows.
