### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Audit Logs V2 missing actions

### ISSUE THREAD

**Issue by DevVarshaM** [microsoft/coe-starter-kit#8075]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,  after the 4.17 release, all new releases of Core components doesn't have some actions in Admin | Audit Logs | Sync Audit Logs (V2) to Update the APP Last launched On field in the PowerApps App tables(which in turn enables us to show the App Last Launched on in the Power Platform Admin view app). Attaching the screenshots of 4.17 release and new release. Is there any other way to update the App last launched on.
<img width="714" alt="Audit Sync Flow 4 17 Release" src="https://github.com/microsoft/coe-starter-kit/assets/114746256/99d3eaa7-0ce7-461d-9d64-2a342b680d44">
<img width="664" alt="Audit Sync Flow" src="https://github.com/microsoft/coe-starter-kit/assets/114746256/f444baaa-be76-4128-8d8d-f423adb14884">

### Expected Behavior

After configuring the steps mentioned in the below URL, app last launched should be populated.

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22 4.24 4.29

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

App Launched is not displayed after configuring the Collect audit logs using an HTTP action,  noticed that some steps are missing in the Admin | Audit Logs | Sync Audit Logs (V2).

If those steps to Update the app launched are removed from the flow, how is the App last launched populated.
I have tried to populate the earlier data by using the CSV file download from Audit search and it is working perfect.

AB#2912

**Comment by Jenefer-Monroe** [comment]
Hello, this was moved into a separate flow in order to help with run time. 
Please ensure have the following flow turned on: **_Admin | Audit Logs | Update Data (V2)_**
It responds to a new audit log record being recorded and updates the app with this information, along with some other things we track for you.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/73a78fc8-ea45-4d39-8e1f-09967582c178)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
