### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Process configuration dependent on Admin | Sync Template v3 flow to finish running

### ISSUE THREAD

**Issue by haithemhasni** [microsoft/coe-starter-kit#8077]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The issue presented in the thread link below is still happening in March 2024 version
Link: https://github.com/microsoft/coe-starter-kit/issues/5532

We had to update the entry in the CoE Solution Metadata table for this to work.

I think the fix always search by guid and not by name as Admin | Sync Template v3 is no longer valid and it is now Admin | Sync Template v4

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1 - Installed CoE Starter Kit
2- Installed all the requirements
3- Started the Compliance Process feature

AB#2915

**Comment by Jenefer-Monroe** [comment]
Hello. We renamed the flow and missed the case in the wizard. Please see https://github.com/microsoft/coe-starter-kit/issues/7904, fixed for April release.

**Comment by haithemhasni** [comment]
Ok, thank you for the quick reply. I will close this bug then. 
Thank you
