### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cross Tenant Connectors View

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#8078]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

On the Cross Tenant view of the Manage Permissions App, all the connection references that show are 'Yes' for NoneOrCrossTenantIdentity.

We have Cross Tenant Isolation ON and no Cross tenants added in PPAC.

What is the significance of the NoneOrCrossTenantIdentity column?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#2916

**Comment by Jenefer-Monroe** [comment]
The identity running the flow will have a "host" identity. Ex: CoEAdmin@myco.onmicrosoft.com

By default any other identity (ex Jon@OtherCo.onmicrosoft.com) will show as cross tenant. You can configure this though by entering into this environment variable.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/36b1dec5-e7e7-464e-a065-d77cb29e4ead)

**Comment by pnoot7** [comment]
Since this is also missing from the documentation as something to configure, does this properly support wild card? i.e. *.mydomain.com to be able to get all sub domains?

**Comment by Jenefer-Monroe** [comment]
No we do not support wildcards.

**Comment by Jenefer-Monroe** [comment]
Can you show me some examples of what these look like? Obfuscate obviously but show me what a few look like.

**Comment by pnoot7** [comment]
I'm not sure how to meaningfully share this while removing usernames and actual domains. I am assuming this process looks at a users UPN or primary SMTP address (our UPN matches our primary SMTP)? We have our users in one tenant (fed by multiple on prem domains), but they are grouped by where they work/domain. So, each user will have something like "John.Doe@sub1.mydomain.com", where another group would be "Jane.Doe@sub2.mydomain.com". We have ~30 of those sub domains. 

Additionally, I put a handful of them in the host domains field. It does not appear to make a difference. I had a ', ' after each one. So, I just removed the space and will see if it makes a difference.

**Comment by Jenefer-Monroe** [comment]
You do need to restart the flow to ensure that the old env var value is not cached. Can you please try that? 
While not an unreasonable request for wildcards, we are a very small team and I just dont see us getting to that soon, so if we can get it to work for you as is, that would be ideal.

**Comment by Jenefer-Monroe** [comment]
Additionally, we dont update old data with the change of the env var. Please see [How to update data to respect configured local tenants](https://github.com/microsoft/coe-starter-kit/issues/7164#issuecomment-1819498144)

**Comment by pnoot7** [comment]
Which flow would need to be restarted?

I understand it is likely a low hanging item, would a feature request not be the best route? I suspect I am not the only customer with a similar issue. Not a critical item to be fixed by any means, so I understand if it takes time. - That said documentation about the feature/variable needs to be made a higher priority.

I'll see if I can take time to remove the old - Thinking out loud, wouldn't that be a good feature/process to do as well inside the CoE? It will almost certainly grab bad information with users not knowing to update that variable.

**Comment by Jenefer-Monroe** [comment]
The reason we don't update the old records automatically is to avoid the API hit. We try to be careful with those. 
And agree on the documentaiton. We've had a paperwork issue which has kept our documentation stale. We've just found a workaround so I'll be working on that next.

I agree its a fair ask but we are a **_very_** small team, and this area in particular is one the product team is investing in right now, so we are likely to let them finish it up. 
Please see [Generate cross-tenant connection report or return an existing report](https://learn.microsoft.com/connectors/powerplatformadminv2/#generate-cross-tenant-connection-report-or-return-an-existing-report)

**Comment by Jenefer-Monroe** [comment]
This is the flow that uses this env var: Admin | Sync Template v4 (Connection Identities)

Lastly, I'm happy to hold this request on the backlog. We're just unlikely to do this work anytime soon, perhaps not this year kind of soon, so I'm trying to unblock you. 
This type of string parsing, which is how we do this, is actually pretty difficult to get right so I dont think we have a quick fix or idea. 
If others do, please let us know and we can reconsider.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
