### ISSUE TITLE
flow and apps volume number is match in power BI and power platform admin view

### ISSUE THREAD

**Issue by expn17ivany** [microsoft/coe-starter-kit#8079]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I would like to know where is the data pulling from between power BI and power platform admin view? Because the number is matched between this 2 platform.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2917

**Comment by Jenefer-Monroe** [comment]
Hello. Are you using Data Export or Cloud Flow architecture for your CoE inventory?

**Comment by expn17ivany** [comment]
Hi Jenefer,

How do I identify it?

Thanks.

Regards
Ivan
***@***.***

From: Jenefer Monroe ***@***.***>
Sent: Wednesday, April 17, 2024 8:49 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Yap, Ivan ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] flow and apps volume number is match in power BI and power platform admin view (Issue #8079)

Hello. Are you using Data Export or Cloud Flow architecture for your CoE inventory? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <microsoft/coe-starter-kit/issues/8079/2061184021@ github. com>


Hello. Are you using Data Export or Cloud Flow architecture for your CoE inventory?

**Comment by expn17ivany** [comment]
Hi Jenefer,

Here is the pbi setting. is this mean we are in cloud flow architecture?
![2024-04-19 12_50_16-Power BI and 8 more pages - Work - Microsoft​ Edge](https://github.com/microsoft/coe-starter-kit/assets/158439768/b51529f1-6481-4324-8643-69933d267404)

**Comment by Jenefer-Monroe** [comment]
You likely are cloud flow yes. 
It looks like you dont have the auto-refresh done. Please follow these instructions: https://learn.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by expn17ivany** [comment]
Hi Jenefer,
thanks for your support. I have another question about Power Platform admin center -> Analytics -> Power Automate
The total number flows of "Default environment" is not matched with the number of flow in "Power platform admin view",

Screenshot 1: Power Platform admin center -> Analytics -> Power Automate
![Power Automate analytics _ Power Platform admin center](https://github.com/microsoft/coe-starter-kit/assets/158439768/b7b96f39-0e36-4691-b619-7c5a98b59470)

Screenshot 2: Power Platform admin view
![Power Platform admin view](https://github.com/microsoft/coe-starter-kit/assets/158439768/175664a2-732c-4a3d-ad75-79ac094741da)

1. Is the total number of flow show in Power Platform admin center and power platform admin view is inter-related?
