### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI BYODL Dashboard - Environment State doesn't show isManaged

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#8083]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hallo,

this visual in the environment page
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/2a72de77-a304-454f-a11b-b0637fa501cb)

doesn't show the % of managed environments like it does in the normal (cloud flow) dashboard.

### Expected Behavior

here the result of the cloud flow based Dashboard
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/9464690f-f18d-4388-9eda-00cf73022f2d)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

BYODL_CoEDashboard_April2024

### What app or flow are you having the issue with?

BYODL_CoEDashboard_April2024

### What method are you using to get inventory and telemetry?

Data Export

AB#2921

**Comment by Jenefer-Monroe** [comment]
moving to the upcoming FC for the data export schema changes.
