### ISSUE TITLE
[CoE Starter Kit - QUESTION] Scheduled refresh for Datalake version "CoE BYODL Makers dataflow"

### ISSUE THREAD

**Issue by soniacervantes** [microsoft/coe-starter-kit#8088]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Configure scheduled refresh for Datalake version: Why do you have to set the schedule refresh to the **CoE BYODL Makers dataflow** table and not to all of them?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 2024

### What method are you using to get inventory and telemetry?

None

AB#2926

**Comment by albertocastro365** [comment]
Hi,
the dataflows need to be runned in order, by this, there are cloud flows to sync the launches of the rest of dataflows:

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/e71e26c0-f2ca-48db-b786-93f341e3a6c0)

**Comment by Jenefer-Monroe** [comment]
thanks for the help!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
