### ISSUE TITLE
Deleted Flows not deleted in CoE Kit

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#8092]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, 
We have over 60 Flows in our tenant that have already been deleted, but are not deleted in the CoE Kit and are not marked as deleted. This also includes the V3 flows from the older version of the kit. Recognising deleted flows does not seem to work properly. I will test this for the apps as well. I sed the Power Automate Management connector to check if I can get the Flows listed in CoE to create a list with als the deleted flows still existing in CoE Kit.

All corresponding flows of the kit are on and run without errors.
As further governance measures are based on the kit data, it is very important for us that the data in the kit is up to date. It would be great to get help here!

Update: Same Problem for Apps (over 100 Apps)

Best regards
Cathi

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Cleanup

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2929

**Comment by Jenefer-Monroe** [comment]
Hello this is driven by the following flow and its helpers which are long running and so only run once per week: **_CLEANUP - Admin | Sync Template v4 (Check Deleted)_** 
Please run it and see if the objects get marked deleted. 

I was also unclear from this comment what the finding was, I presume the objects are missing from the output, can you confirm? 
>  I sed the Power Automate Management connector to check if I can get the Flows listed in CoE to create a list with als the deleted flows still existing in CoE Kit.

**Comment by Cathi029** [comment]
Hello, I ran the flow you mentioned above but nothing changed. 
Would it be a quick fix to just delete the flows from the Flows-Table? And do the same for Apps?
When a flow ist marked deleted, when should the item be deleted from CoE? Is there a delay? Is it possible to configue this delay?

**Comment by Jenefer-Monroe** [comment]
Are you saying its marked as deleted (as shown here) but just not removed?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a52703df-79e2-4f54-bca3-0c720a4a0862)

That is expected behavior. It sits in the inventory marked as deleted for a while, I believe its two months so you have time to restore the record and its metadata in the event the flow/app/etc is restored. At that point the record is deleted from the CoE inventory.
All our reports ignore Deleted so them sitting marked and prepared for restore should not impact any of the kit operations.

**Comment by Cathi029** [comment]
Hello, no, unfortunately none of the flows that have been deleted weeks ago get´s marked as deleted. Same problem with apps. I testet with a newly deleted flow again, this one gets marked deleted. Would it be possible a quick fix to just delete the entries from coe tables for Flows and Power Apps?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by SnowTech23** [comment]
Can we force delete the objects?
