### ISSUE TITLE
The Flow Trigger field is not populated

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#8093]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the Flows table, there is no data in the Flow Trigger field for any of the rows.

### Expected Behavior

To see the Flow Trigger field in at least some of the rows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Look for the the Flow Trigger field in at least some of the rows.

AB#2930

**Comment by Jenefer-Monroe** [comment]
This is filled by the following flow: **_Admin | Sync Template v3 (Flow Action Details)_** 
This flow is very API intensive and so once its turned on, will only do its operations on flows that go through inventory (ex are recently modified). 
Please go make sure you have this flow turned on.

**Comment by RickKush** [comment]
The _Admin | Sync Template v3 (Flow Action Details)_ flow is on and running many, many times...  But there are no Triggers in the Flow table.

**Comment by Jenefer-Monroe** [comment]
Please select a flow in an environment which you would like to use as your test case

**Comment by RickKush** [comment]
That worked! And now I am dividing my 10k flows into several groups to get all of them, but what about the new ones that get created every day? Will I need to intervene manually on a regular schedule?

**Comment by Jenefer-Monroe** [comment]
No the new ones will get sent through this system. Any flow that goes through inventory will go through this flow action details inventory. So that will be covered!

**Comment by Jenefer-Monroe** [comment]
Do you have failures in the flow runs?

**Comment by RickKush** [comment]
The Admin | Sync Template v3 (Flow Action Details) flow ran over 1,000 times last night with no failures and none cancelled and none still running. All of the runs were about 10 seconds...

**Comment by Jenefer-Monroe** [comment]
Do you have over 1000 environments? This flow runs once per environment.
It may take the second day as it runs concurrent to the other flow inventory system.
Does your test case haev its flow details now? 
If not please find its run here and open it
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/08372946-f81e-4cf7-94e1-b2d9c2694b6a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
