### ISSUE TITLE
[CoE Starter Kit - BUG] Video Hub URL is not launching from Nurture Apps Maker App

### ISSUE THREAD

**Issue by shaktisrm** [microsoft/coe-starter-kit#8094]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I am trying to launch the Video Hub link from Nurture Apps Maker app, it says the page doesn't exist. Please see the error below:

Error Code: 2147873362
Session Id: 78fbfeb4-3586-4402-b713-025ccc14e5e4
Activity Id: a7b2b5a7-79aa-4e9e-96ed-93f4a73ffc97
Timestamp: Thu Apr 18 2024 16:50:53 GMT+0530 (India Standard Time)
Page does not exist in this app
UciError: Page does not exist in this app at s (https://content.powerapps.com/resource/uci-infra/scripts/app.578a6df93b024869cc1cd035326dfb39.js:33:960540) at Object.execute (https://content.powerapps.com/resource/uci-infra/scripts/custompage.b8165b5bc03958c90049348b15fb814e.js:4:26968) at https://content.powerapps.com/resource/uci-infra/scripts/app.578a6df93b024869cc1cd035326dfb39.js:14:591754 at new Promise (<anonymous>) at w._executeAsyncAction (https://content.powerapps.com/resource/uci-infra/scripts/app.578a6df93b024869cc1cd035326dfb39.js:14:591455) at w._executeAsync (https://content.powerapps.com/resource/uci-infra/scripts/app.578a6df93b024869cc1cd035326dfb39.js:14:591299) at w.executeAction (https://content.powerapps.com/resource/uci-infra/scripts/app.578a6df93b024869cc1cd035326dfb39.js:14:590564) at t.dispatch (https://content.powerapps.com/resource/uci-infra/scripts/app.578a6df93b024869cc1cd035326dfb39.js:14:595925) at Object.dispatch (https://content.powerapps.com/resource/uci-infra/scripts/app.578a6df93b024869cc1cd035326dfb39.js:14:863806) at Object.dispatch (https://content.powerapps.com/resource/uci-infra/scripts/app.578a6df93b024869cc1cd035326dfb39.js:14:595414)

<img width="815" alt="Video Hub Issue" src="https://github.com/microsoft/coe-starter-kit/assets/20084759/28be8c46-2415-4eca-9749-2ab5666253f9">

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Nurture apps - Maker

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2931

**Comment by Jenefer-Monroe** [comment]
Hello there was an issue with the solution production in our first relase of this. It was resolved in the April release of the kit (Nurture build 3.17)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
