### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Solutions) - Parse inventory - New Solutions - The schema validation failed

### ISSUE THREAD

**Issue by BillatClearBank** [microsoft/coe-starter-kit#8096]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

For many of the daily runs, the "Sync Template v4 (Solutions)" Flow fails at the "Parse Inventory - New Solutions" action with error: "The schema validation failed.". The runs are per environment and the problem seems to be that the schema does not allow for null values, returned from these environments:
      "Soln_Unique": {
        "type": "string"
      },
      "Soln_NonUnique": {
        "type": "string"
      }

### Expected Behavior

All runs complete succesfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2933

**Comment by Jenefer-Monroe** [comment]
Hello. Likely something in the old sync flows added bad data and it was just not known until now as we changed to this set logic technique.  

Please go to the **_Power Platform Solution_** table > Click edit to see all data > Add/Remove columns until you see the below 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d2c04931-1f0d-49a6-ac5d-5d981823889d)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/46068b8b-bbf4-4b73-9f3c-7b91149bf108)

Now filter to where Solution Envt Object GUID String - Does not contain data > Delete these records. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/791d5705-7049-499e-a0e7-a6221ff5b71c)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/632c5b1d-16f8-4623-98ed-36e17a2b082e)
 
Then do the same for the Solution GUID in Envt column.  

Now the flow will pass and lets hold for a few days to make sure it doesnt return.

**Comment by BillatClearBank** [comment]
Thanks Jenefer
The only Power Platform Solutions records which contain data in the Solution Envt Object GUID String and the Solution GUID in Envt columns are those created on the day that the 4.23 update was installed.
There are 2,000+ older records with nothing in and no new solutions indicated since then
Perhaps there's a flow that I'm not running. Do you have any advice?
Thanks again for the speedy response :)

**Comment by BillatClearBank** [comment]
Hi Jenefer
Update on this. You were right. I deleted records for 2 environments and they've been recreated with data in the Solution Envt Object GUID String and the Solution GUID in Envt columns! :)
Thanks again for your help.
Please close this now

**Comment by BillatClearBank** [comment]
Please close
