### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Environment Properties) Missing in 4.29

### ISSUE THREAD

**Issue by StephenBarn** [microsoft/coe-starter-kit#8097]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi All

We have recently imported the CentreOfExcellence Core Components 4.29 and when attempting to configure Capacity Monitoring, we are missing a flow. The flow that isnt showing is Admin | Sync Template v3 (Environment Properties) 

Checking in previous versions, the flow exists. We have attempted to re-import the core components again but the flow still isnt showing

### Expected Behavior

We would have expected the flow to be showing to allow us to configure capacity monitoring on environments

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Import compressed file
Check in solution for flow

### Anything else?

n/a

AB#2934

**Comment by Jenefer-Monroe** [comment]
Hello the driving flow was shifted to this one which now calls that helper: **_CLEANUP - Admin | Sync Template v4 (Other Objects)_**

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of what you are looking at and point out where you are expecting to see information?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by asdkjlkfjgkfdg** [comment]
I am also experiencing this issue after setting up the CoE Starter kit a few days ago. I expect to see Environment Capacity info in the Environment Capacity Table and the Environment Capacity page of the Power BI dashboard. This information did not populate after the sync flows have run, including CLEANUP - Admin | Sync Template v4 (Other Objects), which ran successfully. 
![image](https://github.com/microsoft/coe-starter-kit/assets/168126047/60b66c58-02fd-4837-adf8-e7a5ded31f05)
![image](https://github.com/microsoft/coe-starter-kit/assets/168126047/0a754d5d-7106-4d24-a7a0-b51305311b4a)
![image](https://github.com/microsoft/coe-starter-kit/assets/168126047/3dfedfab-9b5d-4b6e-a61b-f20273ca0289)
