### ISSUE TITLE
I cannot configure Compliance process from CoE Setup and Upgrade Wizard bacause of Missing prerequisite.

### ISSUE THREAD

**Issue by hiroakimori-01** [microsoft/coe-starter-kit#8098]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I cannot configure Compliance process from CoE Setup and Upgrade Wizard bacause of Missing prerequisite.

Popup window says "It looks like some inventory flows required to set up the Compliance process haven't finished running yet. Please check the CoE flows page of the Admin - Command Center app, and return to this setup wizard when the Admin | Sync Template v3 (Driver) flow has finished running".
However the core coponent does not include "Admin | Sync Template v3 (Driver)" but "Admin | Sync Template v4 (Driver)".

### Expected Behavior

I can configure Compliance process with "Admin | Sync Template v4 (Driver)".

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

 4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Driver)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Download CoE Starter Kit from https://aka.ms/CoeStarterKitDownload
2. Install Core Component
3. Install  Governance Components
4. Open CoE Setup and Upgrade Wizard 
5. Configure Compliance process

AB#2936

**Comment by Jenefer-Monroe** [comment]
Hello. This one is fixed in the April release. Please see https://github.com/microsoft/coe-starter-kit/issues/7806 for [a workaround](https://github.com/microsoft/coe-starter-kit/issues/7806#issuecomment-1998401773) in your current build.

**Comment by Jenefer-Monroe** [comment]
closing out as dupe, as no further action for starter kit team
