### ISSUE TITLE
[CoE Starter Kit - BUG] Data Export BYODL CoE shows all environments without DLP in Power Platform Admin View app and in Governance Dashboard

### ISSUE THREAD

**Issue by bilodeauju** [microsoft/coe-starter-kit#8101]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After installing the April update in Data Export mode and waiting 48 hours for data to update, I noticed the "Has DLP Policy" and "DLP Policies" data columns are still not populating and reflecting our configured DLP policies correctly in the Power Platform Admin View app. It is listing all of our environments as not having a DLP policy. 
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/1dcf2636-6116-4f70-8e29-deb213ed45f4)

When opening the Governance Dashboard, it also shows all of our environments without a DLP Policy which is incorrect. 
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/7655e192-3b2e-4d60-a42c-ac3142220562)

### Expected Behavior

Prior to this, I have installed the April update in a separate environment in Cloud flow inventory mode, and after turning on and running the Admin | Sync Template v4 (Driver) flow, the "Has DLP Policy" and "DLP Policies" data columns started populating right away in Power Platform Admin View app. 
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/748bd67f-8eef-4e71-a413-e88f5ac59da4)

Same with the Governance dashboard. (Initially 3 were missing a DLP Policy and were addressed so it is working perfectly for Cloud flow mode)
![image](https://github.com/microsoft/coe-starter-kit/assets/81716086/5b0196d5-dca3-435b-aa5e-5a6682e4c412)

I would expect this feature to work for both Cloud flow and Data export inventory as this is a very useful tool we want to monitor. 
By default the Admin | Sync Template v4 (Driver) flow is turned off in Data export mode. Is there a separate mechanism to capture this data for Data Export?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29 (April)

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Installed CoE April update (Core + Governance solutions)
Ran setup wizard for Data Export mode
Setup dataflows as part of the setup wizard
Allowed 48 hours + for dataflows and other cloud flows to run
Opened Power Platform Admin View App and added DLP columns 

AB#2939

**Comment by Jenefer-Monroe** [comment]
Hello, yes this information was not yet available to us in the Data Export so we are targeting it for the upcoming schema changes and feature work that will result. Marking for that feature.

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
