### ISSUE TITLE
[CoE Starter Kit - QUESTION] Which flow updates "has DLP Policy" in the environment table

### ISSUE THREAD

**Issue by Chandra1247** [microsoft/coe-starter-kit#8104]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I see a column in environment table "Has DLP Policy" but it is not being updated. I want to know which flow is responsible to updating this column

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What method are you using to get inventory and telemetry?

None

AB#2942

**Comment by Jenefer-Monroe** [comment]
This was blank until the April release (4.29) when it started being filled by the main Driver flow. So you will need to upgrade to see this feature light up.

**Comment by Chandra1247** [comment]
Thanks for info. I will upgrade the solution to 4.29.
