### ISSUE TITLE
[CoE Starter Kit - Feature]: Pull Date for when an Apps or Flows become Orphaned

### ISSUE THREAD

**Issue by AllyThorne** [microsoft/coe-starter-kit#8105]
### Is your feature request related to a problem? Please describe.

I would like to be able to identify when a resource became orphaned.

### Describe the solution you'd like

We would like the date to be included when an app or flow is orphaned. 

### Describe alternatives you've considered

We can do this by triggering custom flow when row is added/modified with condition resource = orphaned.
 

AB#2943

**Comment by Jenefer-Monroe** [comment]
Hello we do track this today, I think we shipped this ~3-4 months ago so any orphans before that build was installed will be unknown. Its filled by this flow **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/145aabdb-3c18-4624-9d90-c6971f453873)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
