### ISSUE TITLE
[CoE Starter Kit - QUESTION]  How to get  Sum duration of all Flows in a tenant

### ISSUE THREAD

**Issue by gregroe** [microsoft/coe-starter-kit#8107]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there a way to get the sum total duration fo all flow.  so for example in the Power Automate 28-day run history i can see the Duration (how long each flow ran) .   I'd like to retrieve the total duration for all flows in a tenant.   and filter by Status (Succeeded) and Flow name.   ive parsed thru all the tables and  coe power bi reports. I wonder if its available  somewhere?  (e.g. run logs). I can see the total number times a flow is run, but i want to find out the total Duration  for all runs of a particular flow and all flows in a tenant.

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#2945

**Comment by Jenefer-Monroe** [comment]
Hello we do not have access to run information for flows today. The product team is doing work to make this available but I'm unsure of availability date.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
