### ISSUE TITLE
(Reopen) [CoE Starter Kit - BUG] Couldnt find Admin | Sync Template v3 (Driver) flow in CoE flows page of the Admin - Command Center app

### ISSUE THREAD

**Issue by pavanmanideep** [microsoft/coe-starter-kit#8108]
Here is the snap
![Error Installing](https://github.com/microsoft/coe-starter-kit/assets/27499846/c103e9de-70ab-436d-a600-ed7a115e1344)

I am using Default Environment.
![Environment COE](https://github.com/microsoft/coe-starter-kit/assets/27499846/7b9e33fd-4a17-40d8-8e0a-ada4da07bb3d)

_Originally posted by @pavanmanideep in https://github.com/microsoft/coe-starter-kit/issues/8009#issuecomment-2067518391_
            

AB#2950

**Comment by Jenefer-Monroe** [comment]
Hello this flow has been deprecated in favor of a v4 version of it. The issue you point to is fixed in the April release which you are not yet on.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
