### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis - HTTP Connector

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#8109]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,
In the DLP impact analysis app, the HTTP connector is not considered in the impact analysis. It does not appear in the app nor in the CSV export.

### Expected Behavior

All Connectors should be included

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

DLP Impact Analysis

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Simulate an DLP für an environment (like the CoE) without HTTP connector.

### Anything else?

If using the cloud flow inventory, the HTTP is shown in the CSV export. but in app just as a blank row
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/73d72b4e-f367-4db8-8388-372cfd95179c)

AB#2946

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. I do repro. Rahul please make sure all these "specialty connectors" work with your next set of fixes.

**Comment by Jenefer-Monroe** [comment]
Moving to new dev and to June. This one cant be placed on the backlog, its a must fix for June.
