### ISSUE TITLE
[CoE Starter Kit - BUG] CoE setup and upgraded wizard gets stuck on "Run setup flows" (new install)

### ISSUE THREAD

**Issue by anttipajunen** [microsoft/coe-starter-kit#8110]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

On a new install to a **reset env**, the wizard freezes at the "Run setup flows" step. Flows aren't displayed and the "Refresh" button is grayed out. I'm blocked from proceeding to the next step in the wizard. The model-driven app "new look" as no impact, albeit turning it off significantly increases the wizard's performance.

![image](https://github.com/microsoft/coe-starter-kit/assets/64043240/678ef986-f6cf-4c68-92e9-0a7c01cd0763)

FYI:
Admin | Sync Template v3 CoE Solution Metadata has run successfully
Admin | Sync Template v3 Configure Emails has run successfully
Admin | Sync Template v3 (Connectors) has run successfully
Admin | Sync Template v4 (Driver) remains turned off

### Expected Behavior

Flow status is displayed and I can proceed to "Run inventory flows" step in the wizard.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Setup wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Install CoE core components in a reset env that had CoE
2. Open setup wizard
3. Proceed to step "run setup flows" in wizard.

AB#2947

**Comment by anttipajunen** [comment]
Seems these are the only ones I have there:
![image](https://github.com/microsoft/coe-starter-kit/assets/64043240/8601af61-bce1-4029-9c2f-a092a9227ae3)

**Comment by Jenefer-Monroe** [comment]
ok another person hit this recently and the issue was that not all the flows were getting returned by the products connector.
The issue was transient and went away. Please open the run of **_Admin | Sync Template v3 CoE Solution Metadata_**

Are these three flows returned in this action here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c4e8f224-cf2c-4c4e-af04-7c5a2a602c87)

**Comment by Jenefer-Monroe** [comment]
Did it work?

**Comment by anttipajunen** [comment]
Environment reset isn't enough. The same issue reproduces. I did install the April solution in a completely new environment (I've actually installed it in 3 different tenants) without any problems.

**Comment by Jenefer-Monroe** [comment]
For the envt you reset that still didnt work, what are the properties here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b2640bf2-7387-461a-8c3d-3a25ec3b2f85)

**Comment by anttipajunen** [comment]
Admin mode is disabled. I also checked the table data and what the flow you mentioned above contains, and the 3 flows aren't returned in data or in the flow.

**Comment by Jenefer-Monroe** [comment]
gotcha. thank you yes annoying indeed! 
OK we can set down. Thanks for your diligence!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
