### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Chaudharyk22** [microsoft/coe-starter-kit#8111]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have created a development environment through Power Platform admin center and there was no security group and no security role assigned to it. After creation I can see it in Power Platform admin center but not in COE started toolkit Power platform admin view. However, on the make.powerapps.com site if I search the environment name then in dropdown its appearing.
Kindly suggest what am I missing?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#2949

**Comment by Jenefer-Monroe** [comment]
Hello is your identity, that created the dev envt, the same identity that runs the flows in the kit? 
Did you wait for the next day for the inventory flows to run?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
