### ISSUE TITLE
[CoE Starter Kit - QUESTION] Does changing UPN potentially impact COE Starter Kit inventory like Audit etc

### ISSUE THREAD

**Issue by ajeyng** [microsoft/coe-starter-kit#8112]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Looking into changing the User UPN's. How is this going to affect PowerApps and Power Automate inventory data in CoE Starter Kit?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Mar 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2951

**Comment by Jenefer-Monroe** [comment]
Hello can you please clarify what you mean? Do you mean the identity that is running the flows? 

There shouldnt be any impact from changing the UPN.

**Comment by ajeyng** [comment]
Hi Jenefer, Thank you for your prompt reply. I actually meant the inventory of flows from maker/usage reporting perspective. Due the changes in UPN, will the sync flows update the existing inventory  to reflect those changes?

As far as the identity, I am aware that can be updated with a new account. I hope I am correct there. Thank you for your time.

**Comment by Jenefer-Monroe** [comment]
There are some places where it will not update where we made copies of the data. For example in the Apps table you will see text strings that are filled with user information at time of inventory. 
But the data in the maker table will be updated.

**Comment by ajeyng** [comment]
Thanks again, Jenefer. I understand that the core data (Maker table) will be updated. That's good.
