### ISSUE TITLE
Apps are missing from inventory

### ISSUE THREAD

**Issue by iprasadraju** [microsoft/coe-starter-kit#8113]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Team,

I wanted to bring to your attention that we have the CoE Starter Kit March 2024 version installed in our environment. However, I've observed that couple of apps seem to be missing from the "Power Platform Admin View". One of the missing apps was created just 6 days ago. I have verified that the flow "Admin | Sync Template v3 (Driver)" is running daily without encountering any issues.

Could you please assist me in determining which Dataverse table (Power Platform OOTB table) stores the Canvas App and MDA information?

Does the "PowerApp Apps" table refresh its entire dataset daily, or does it solely incorporate new changes made within the environment?

### Expected Behavior

After every run PowerApp Apps table should have all the Canvas apps and MDA information

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2024

### What app or flow are you having the issue with?

Admin - Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

I was trying to delete the missing model driven app, I am facing issue (screenshot attached)
![MDA Delete Error](https://github.com/microsoft/coe-starter-kit/assets/16459499/b8e0f420-0bf9-4183-8dcd-83ca3dfffe86)

When I try to check the same MDAs using "Power Platform Admin View", I didn't found the entry. However in make.powerapps.com screen I am able to see the app

AB#2952

**Comment by Jenefer-Monroe** [comment]
Hello the v3 version of the driver flow was deprecated as of the release you are on so I suspect something is broken in your install. 
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by iprasadraju** [comment]
Apologies for the confusion. Instead of referring to v4 (Admin | Sync Template v4 (Driver)), I mistakenly mentioned v3. Could you kindly assist me in identifying the table name (Power Platform OOTB table) that stores the information for Canvas App and MDA?

![CoE Solution List](https://github.com/microsoft/coe-starter-kit/assets/16459499/09cff8b4-fe76-4702-a654-7c5fabae26ce)

**Comment by Jenefer-Monroe** [comment]
Those are stored in the PowerApps App table
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0c3d2ca4-b3ff-45c8-9d1b-547cc0de7f66)

**Comment by Jenefer-Monroe** [comment]
After looking in that table, if you do not see the expected app, please follow these instructions

### Find a repro
You will need to find a repro of this in your tenant to see what is going wrong. 
1. Find an environment in your tenant where you expect to see the object (ex this app missing, that chatbot missing, etc)

2. Go to the Power Platform Admin view app and find that environment. Open the record, edit some field, and save
Note you will want to change back so be aware of the change. 
![image](https://user-images.githubusercontent.com/89584709/181270817-0ead36c3-0b67-4b85-9efc-ef218c61f77f.png)

3. This will trigger all the object flows to run for that environment. Find the flow for your object of interest and open it to details page.
Ex: if you are looking for missing canvas apps chose **_Admin | Sync Template v4 (Apps)_**, if you are looking for missing Model Driven Apps chose **_Admin | Sync Template v4 (Model Driven Apps)_**, etc
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/76aace97-2f05-4134-9786-cb6c5910dfa5)

4. Click on the timestamp of run in progress (or the one that just finished) to see the run itself. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7b07b78c-1cf2-4452-bd6c-631c401cb97e)

5. From here you can explore if there is a failure, or if a bad return set, etc. And let us know if you have questions

**Comment by iprasadraju** [comment]
In my scenario, the Model Driven App is absent. After adhering to your guidance, the workflow "Admin | Sync Template v4 (Model Driven Apps)" executed smoothly. This workflow pertains to the "appmodules" table. 

While I can spot the "appmodules" table in the security role permissions list
![AppModule Table - SecurityRole](https://github.com/microsoft/coe-starter-kit/assets/16459499/e8c78b2c-1dc9-4313-8bf8-6c12de9c397a)

### "appmodules" (Model-driven App) table is missing from the tables list.

![AppModule Table](https://github.com/microsoft/coe-starter-kit/assets/16459499/ff3bf72c-4461-4e9a-aaab-8d85619775c2)

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately its a hidden product table, so you can't view it in the UX.

**Comment by girishuppal** [comment]
Hello @iprasadraju 

In case you want to view the list of entire model driven apps in your tenant see this video 

https://youtu.be/uFwkanybCXI?list=PL5xdZrvu1OhUISeASn3Zi1gTWwlZRGfQT

You can write a simple power automate flow to view all of the apps in your tenant. Thanks

**Comment by Jenefer-Monroe** [comment]
You MDA inventory should be in the CoE tables as well. Please find a repro for us as described above and we can debug

**Comment by iprasadraju** [comment]
@girishuppal, Thanks for the link

@Jenefer-Monroe, MDA is not appearing in the CoE tables "PowerApps App" or "appmodules". However, I can confirm that the app is visible in the UX

**Comment by Jenefer-Monroe** [comment]
Are you saying that here:

the app is not returned for that envts run? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/76aac2fe-7cfa-4eaf-a2a1-c2425286de91)

If so, please go check the SR of the identity running the flow in that envt.

**Comment by iprasadraju** [comment]
Yes, I'm referring to "List Envt MDAs". I've specifically created a new workflow to query the "appmodules" table. The missing Model-Driven App (MDA) did not exist in the first place.

**Comment by Jenefer-Monroe** [comment]
Did anything return? Any Model Driven Apps? 
Please go check the Security Role of the identity running the flow in the environment permissions.

**Comment by iprasadraju** [comment]
Indeed, "List Envt MDAs" returns the list of Model-Driven Apps (MDAs) excluding the missing app. I am executing the flow using the Power Platform admin account.

**Comment by Jenefer-Monroe** [comment]
Can you please go check the Security Role of the identity running the flow in the environment permissions? 
There are some changes happening that make it so you dont get added to envts as Sys Admin anymore by default.

**Comment by iprasadraju** [comment]
I have double-checked the flow identity, and it indeed has the "System Administrator" security role.

**Comment by Jenefer-Monroe** [comment]
OK so to summarize. 

- Your user has Sys Admin in the Envt
- When you query the App Modules table in that Envt you do not get a list of apps
- This is true even with your own test flow you created as well as with the flows from the kit.

Is that accurate?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
