### ISSUE TITLE
[CoE Starter Kit - BUG] Import is getting failed while upgrading COE starter kit core component from 4.3 to 4.29

### ISSUE THREAD

**Issue by rajaug3** [microsoft/coe-starter-kit#8114]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When i'm importing 4.29 core component version after removing unmanaged layers. i'm getting below error.

Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :Import failed: The column 'admin_makersubmittedrequirements' is dependent on column 'admin_requirement_2'. ALTER TABLE ALTER COLUMN admin_requirement_2 failed because one or more objects access this column.

### Expected Behavior

when you import core component

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3

### What app or flow are you having the issue with?

*

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. click on Import solution
2. select CenterofExcellenceCoreComponents_4.29_managed file
3. Ensure upgrade option choose
4. next
5. provide all parameter

### Anything else?

When i'm importing 4.29 core component version after removing unmanaged layers. i'm getting below error.

Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :Import failed: The column 'admin_makersubmittedrequirements' is dependent on column 'admin_requirement_2'. ALTER TABLE ALTER COLUMN admin_requirement_2 failed because one or more objects access this column.

AB#2953

**Comment by Jenefer-Monroe** [comment]
Hello, a few people have hit this and it turns out that they had customized some column. Please see notes in https://github.com/microsoft/coe-starter-kit/issues/7419 for how to resolve.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by rajaug3** [comment]
HI,

Sorry for late response. After following https://github.com/microsoft/coe-starter-kit/issues/7419, i got the below errors
Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 28 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_bd471, Id: ca495141-98c9-4baf-a89e-167192547fc1, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - CanvasAppOperations, Id: 41263d72-4dea-eb11-bacb-000d3a5786fb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_bd471, Id: ca495141-98c9-4baf-a89e-167192547fc1, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - CloudFlowOperations, Id: 6093b58a-4fea-eb11-bacb-000d3a578f6c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_bd471, Id: ca495141-98c9-4baf-a89e-167192547fc1, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: SetupWizard>ShareApps, Id: 1ff39c14-fe60-ed11-9561-6045bd07536e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Reminder 3 days prior event, Id: bc9a9f1a-afe6-e911-a86a-000d3a37207b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Newsletter with Product Updates, Id: e7a96786-c7e5-e911-a860-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Feedback Reminder, Id: 2c42d11c-afe6-e911-a860-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Training In A Day | Registration Confirmation, Id: bdd94919-afe6-e911-a85c-000d3a372ab9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365OutlookCoEConnection, Id: 0beca3ce-bebe-4618-93bf-524f4618f84e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Check Approvals, Id: c7982cc4-3024-eb11-a813-000d3a8c389b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_PowerAutomateManagementCoEConnection, Id: e637dd14-f8ba-4788-88ae-7de354023898, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoEConnection, Id: acf087ad-3e8c-4dbc-9603-c8fa6164e5a4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: cd430ab8-e1fe-4286-bc1c-ec1ec0df097e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Flow Archive and Clean Up - Start Approval, Id: 27700ed2-db1e-eb11-a813-000d3a1bb495, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: cd430ab8-e1fe-4286-bc1c-ec1ec0df097e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: cd430ab8-e1fe-4286-bc1c-ec1ec0df097e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: (OFF Currently) Flow Upsert, Id: 2e4250f6-6ddd-eb11-bacb-000d3a8eeb41, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_Office365UsersCoEConnection, Id: cd430ab8-e1fe-4286-bc1c-ec1ec0df097e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Flow Upsert without adding EAOps team, Id: 58eeff0c-78dd-eb11-bacb-000d3a8eeb41, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365groups_d6648, Id: b25abec2-afed-427c-babe-ed0b6462c270, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP HELPER - Power Apps User Shared With, Id: 1f3f24ff-c717-ec11-b6e6-000d3a1c26f9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365groups_d6648, Id: b25abec2-afed-427c-babe-ed0b6462c270, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - Add User to Security Role, Id: 1edb4715-b85b-ed11-9561-0022480819d7, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365groups_d6648, Id: b25abec2-afed-427c-babe-ed0b6462c270, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: SetupWizard>CreateGroup, Id: 2fbe886b-e51f-ed11-b83e-00224822fb7e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365groups_d6648, Id: b25abec2-afed-427c-babe-ed0b6462c270, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: SetupWizard>ShareApps, Id: 1ff39c14-fe60-ed11-9561-6045bd07536e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f656d4006af872ade_92273, Id: 8c5c4ab9-6004-ee11-8f6e-00224827b509, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f656d4006af872ade_d5cf1, Id: 45a3d8f5-19aa-ee11-be37-00224827b509, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f656d4006af872ade_d9385, Id: 9e184fb6-edaa-ee11-be37-00224827b509, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f656d4006af872ade_5d68b, Id: 218bbd34-6e0b-ee11-8f6e-00224827b681, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f656d4006af872ade_5eb1e, Id: 62062b43-0fb9-ee11-a569-0022482a466b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5ff18d20b7ec3dbffe_a3e3b, Id: a15d5b6b-f5b6-46fa-8ba9-a139444da43b, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f7fc9343cf45734fe_8f08c, Id: b590cbe2-362c-4184-b3b7-e8ca810950f5, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published .
