### ISSUE TITLE
[CoE Starter Kit - BUG] Manage Permissions App Data Error

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8115]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to get Connection Clean Up information.
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/400dd2c3-820c-47b5-9c12-19074813bb54)

### Expected Behavior

it should work.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Manage Permissions App

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open App, Navigate to Connections

AB#2954

**Comment by Jenefer-Monroe** [comment]
Hello there is something wrong with the default value on the connector filter. 
In the meantime if you go hit the x next to it (or select a connector), the button will work. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/351fbf05-5612-404c-b3fc-7c0506229fa4)
