### ISSUE TITLE
[CoE Starter Kit - BUG] CoE_ProductionDashboard PowerBI Failure 

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#8116]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team, 

We are getting an error, when we are trying to bring up the April CoE_Production Dashboard. We do have the most up to date PowerBI Desktop (April version), as well as, the account having the System Admin and PowerBI Pro license. Is this an known error? Or how can we fix this? 

![image](https://github.com/microsoft/coe-starter-kit/assets/100535041/bc00a88a-1950-46f5-9614-63f789477c60)

Thanks! 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Production_CoEDashboard_April2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2955

**Comment by Jenefer-Monroe** [comment]
Please try the attached. 

[BYODL_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14958010/BYODL_CoEDashboard_April2024.zip)
[Production_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14958009/Production_CoEDashboard_April2024.zip)

We shipped with one hard coded envt at first.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
