### ISSUE TITLE
[CoE Starter Kit - BUG] AI Consumption Report Not Accurate

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8117]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

AI Builder Consumption Report Not Accurate. AI Model and AI Events flows are running correctly per run history.
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/a5108fbc-4ff5-4428-89c5-0f610be26db7)

AI Status does inactive even do model is being used per PPAC AI Credit report. 

PPAC Report Shows Model to have consumed 800 credits within the span of one month.

CoE will show all AI Models but it will not show credit consumption for any of the reports. 

### Expected Behavior

Report should correctly show AI Credit Consumption

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

AI Builder Consumption Report

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2956

**Comment by Jenefer-Monroe** [comment]
Do note that the reports start when you turn the flows on and only look back one day for consumption. 
Please see if there is a case where you use a credit and the next day that is not showing up after inventory.

**Comment by nasilvae** [comment]
> Do note that the reports start when you turn the flows on and only look back one day for consumption. Please see if there is a case where you use a credit and the next day that is not showing up after inventory.

we have the coe setup for a 2 day refresh due to api request limits (big tenant). Will this affect the report.

**Comment by Jenefer-Monroe** [comment]
Yes it will, you'll need to go make an unmanaged layer to customize this to look back 2 days instead.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/57639dd7-8ee9-4d2a-b405-09e17154e50d)

**Comment by nasilvae** [comment]
> Yes it will, you'll need to go make an unmanaged layer to customize this to look back 2 days instead. ![image](https://private-user-images.githubusercontent.com/89584709/324640619-57639dd7-8ee9-4d2a-b405-09e17154e50d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzU4MTUsIm5iZiI6MTcxMzg3NTUxNSwicGF0aCI6Ii84OTU4NDcwOS8zMjQ2NDA2MTktNTc2MzlkZDctOGVlOS00ZDJhLWI0MDUtMDllMTcxNTRlNTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyMzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZTA3Mjc1MGM1NDY0N2Q2MGJiNmNhODgyYzFlNDhhYzdjN2EyYjEwMGM0M2U2ODNkZjI3Njg5OTdlYzA1ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FREaGfrw0i6YAYnjQkO4eAcEsriiQBFD1T1YhSlc4O8)

I see, we did this with the driver flow, for this one the drive flow doesnt kick it off.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
