### ISSUE TITLE
[CoE Starter Kit - BUG] Manage Permission App Performance

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8118]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

App is too slow to bring up App/Flow owner information. It would take over 5 minutes to get the information and in some scenarios time out. 

### Expected Behavior

it should get resource information in a timely manner.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Manage Permissions App

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2957

**Comment by Jenefer-Monroe** [comment]
Hello. There is nothing we can do about this to my knowledge. If you have ideas we are open to them.

**Comment by nasilvae** [comment]
> Hello. There is nothing we can do about this to my knowledge. If you have ideas we are open to them.

Is there a way we can prepopulate the values in the main screen that shows the resource name and users and then have the api calls only happen when you drill through the resource?

**Comment by Jenefer-Monroe** [comment]
I'm not following sorry. Can you show me what you mean with some pictures?

**Comment by nasilvae** [comment]
I meant these fields 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/779d3fb3-2204-4d50-b8c8-27a85c28060e)

**Comment by Jenefer-Monroe** [comment]
Oh sorry I thought you were talking about a different feature. 
Can you clarify, when is it that you are seeing the five minute delay? I have not seen that myself. That will help the dev here investigate.

**Comment by LucasCXavier** [comment]
Facing the same delay to manage the owners.

**Comment by julian0723** [comment]
Issue still persist on 4.31 version. The app only contains 1 owner but the fetching of the details takes a while.

**Comment by RajeevPentyala** [comment]
@nasilvae We could not reproduce this issue on our end and need a few more details. Can you please reach out to me at rajeevpe(at)microsoft(dot)com?

**Comment by Alyson95170** [comment]
I am having the same issue very slow at showing all the information.  When I click on the Owner Button within Apps and Flows nothing Populates.  When searching for the name of the app or flow this then shows but assigning a new owner did not complete, after 5 minutes I closed the app

**Comment by Jenefer-Monroe** [comment]
I went ahead and stored this information in the Apps table with https://github.com/microsoft/coe-starter-kit/issues/8333
And so am now able to just show the number of editors in the app like this: 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bec3241f-1af6-4868-a48e-66d2329541ae)

Do note: you'll need to run this flow before you see the values showing up: **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_**
