### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Platform Admin View

### ISSUE THREAD

**Issue by AzizAQureshi** [microsoft/coe-starter-kit#8121]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have an issue with the Power Platform Admin View. 
Whenever I select an app in the PowerApps Apps category I get a notice like the following:
![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/7049feea-3fad-46d3-8fd3-0adf1f6c3470)

The notice is in the red box. What has been deactivated? and how do I activate it?

And when  I click the 'Validate Maker Business Requirements' I cannot click on the 'Next Stage' button:

![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/80849df1-d263-4b61-a1d3-5f3e4e17dce0)
as shown in the red box.

When I hover the button it turns blue. But when I click it nothing happens. I have seen videos where when the button can be clicked 
but not in my scenario. 

Please advice.
Thank you

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2960

**Comment by Jenefer-Monroe** [comment]
Please go make sure all the BPFs are turned on. Sometimes these get turned off for people
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6b91c96f-0b87-4044-bafe-7cd29ba55cde)

**Comment by AzizAQureshi** [comment]
Thank you for your response
![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/cfdd530d-5124-4b5a-a00a-a557405c741f)
As you can see from the red box the 'Turn on' button has been disabled. 
Please advice how do I turn these processes on.
Thank you

**Comment by AzizAQureshi** [comment]
Thank you I have figured it out how to activate it and it is now working.

Thank you soo much

**Comment by Jenefer-Monroe** [comment]
Wonderful! Thanks for letting me know. I'll go ahead and close but please do return with new issues in the future as needed.
