### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow Last run date in Power Platform Admin View App

### ISSUE THREAD

**Issue by DevVarshaM** [microsoft/coe-starter-kit#8123]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

HI Team,
Is there any way to get the Flow Last run date for all flows in our tenant. There is a Flow Last Run column in Power Platform Admin view app but the value is not populated. Could you please help how to get this data. I am using the cloud flows method to get the inventory.

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2962

**Comment by Jenefer-Monroe** [comment]
Unfortunately this information is not yet available to us. The product team is shipping something soon to expose but its not yet available. And once it is we would need to find an API efficient way to collect.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
