### ISSUE TITLE
[CoE Starter Kit - BUG] AI Consumption Report Not retreiving correct values

### ISSUE THREAD

**Issue by silvafr1** [microsoft/coe-starter-kit#8124]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, I´ve installed the April version however the PBI report AI Credits usage is not giving the correct values!

We have several Environments set with AI Builder credits and a lot of consumption and as you can see in the attached picture attached, CoE PBI Report is totally different from PPAC report.

![AiBuilder_Consumption](https://github.com/microsoft/coe-starter-kit/assets/49397248/6bf2f1d4-840c-482a-9f0f-c42eb0acbe03)

### Expected Behavior

We aren´t able to see in the CoE PBI Abril version the correct information regarding the Ai Build Consumption

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v4 (AI Events)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2963

**Comment by Jenefer-Monroe** [comment]
Please try the attached, we shipped the first time with a bug in the report.

[BYODL_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14958010/BYODL_CoEDashboard_April2024.zip)
[Production_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14958009/Production_CoEDashboard_April2024.zip)

**Comment by silvafr1** [comment]
Thank you! It worked!
Best regards

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thanks for letting me know! I'll go ahead and close out then.
