### ISSUE TITLE
[CoE Starter Kit - BUG] 'SYNC HELPER - Cloud Flows'  flow was turned off because it was running more actions than expected

### ISSUE THREAD

**Issue by ramontebar** [microsoft/coe-starter-kit#8125]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The flow 'Admin | Sync Template v4 (Flows)' is failing when trying to trigger the child flow 'SYNC HELPER - Cloud Flows', which has been turned off (suspended) because it was running more actions than expected.

**Error in 'Admin | Sync Template v4 (Flows)'**

"Could not execute workflow '9e3bebf9-e157-79a0-4dc8-b94d91494a0e' trigger 'manual' with state 'Suspended': trigger is not enabled."

![image](https://github.com/microsoft/coe-starter-kit/assets/7858467/e73446c1-57cf-43f6-9366-97644b9aa64d)

**Error in 'SYNC HELPER - Cloud Flows'**

"Your flow was turned off because it was running more actions than expected"

![image](https://github.com/microsoft/coe-starter-kit/assets/7858467/2a99d2d6-632f-4993-836a-84b30a5a30c6)

This issue seems to be similar to [7941](https://github.com/microsoft/coe-starter-kit/issues/7941).

We have noticed the flow 'SYNC HELPER - Cloud Flows' has already been suspended twice. We turn it on and it seems to work for a while until it gets suspended again.

### Deployment details

- Core version: 4.29 (April 24 release)
- Number environments in tenant: 1324
- Number cloud flows in tenant: 25505
- Kit has been running since version 4.17 (November 2023 release)
- admin_FullInventory environment variable set to No

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2964

**Comment by ramontebar** [comment]
Thank you @Jenefer-Monroe for reviewing my issue and share a little bit of that potential solution coming in the roadmap. Looking forward to testing it.

**Comment by Jenefer-Monroe** [comment]
You bet, sorry I dont have a better answer for the near term!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
