### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Change request creation, missing permissions

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#8127]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Missing permissions to create a DLP Change request

![image](https://github.com/microsoft/coe-starter-kit/assets/109345362/8c8de53d-18c1-44d1-878f-87441a10943c)

### Expected Behavior

Power Platform Make SR role needs the "Append" privilege in order to create a DLP change request.

Setting this permissions to "User scope" seems to fix the issue.
![image](https://github.com/microsoft/coe-starter-kit/assets/109345362/1badf3ea-1c19-49ab-9702-940edea023f8)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Maker Command Center -> Data Policy Request Page

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Try creating a DLP Change Request with the "Power Platform Maker SR" role assigned.

AB#2966

**Comment by Jenefer-Monroe** [comment]
Thanks for investigating! Easy fix with your help! 
Ready for May
