### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION about interference with actvity-based automatic cleanup.

### ISSUE THREAD

**Issue by birgeravo** [microsoft/coe-starter-kit#8129]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have been relying on the built-in actvity-based automatic cleanup of environments to handle our unused teams and developer environments (which there are a lot of). But I now see that all of our environments have registered activity at 5:30am last night. I suppose this is due to CoE toolkit actions. From this I have some questions. 
Is the activity generated by CoE toolkit?
Will the activity interefere with actvity-based automatic cleanup?
Is there a way to avoid this activity, so the cleanup can run as intended?
![image](https://github.com/microsoft/coe-starter-kit/assets/83594333/5add9483-6f4a-43f9-8f86-7ff156d81e98)

Example Logs from one environment
<img width="1037" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/83594333/38e74e42-3b1a-4a7d-8409-ea301dc0e6e7">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

February 2024

### What app or flow are you having the issue with?

unknown

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2969

**Comment by Jenefer-Monroe** [comment]
Hello this is a known product limitation. Please add your comments in this issue, Grant is driving with the product team
https://github.com/microsoft/coe-starter-kit/issues/5968

**Comment by birgeravo** [comment]
Thank you, then I know why this is happening. I hope for a speedy resolution by the product team, as we realy rely on the built-in governance features to work.

**Comment by Jenefer-Monroe** [comment]
Indeed. I think they know how now so its just a matter of the work itself. 
I'll go ahead and close as a duplicate.
