### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Maker SR role missing permissions

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#8131]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Power Platform Maker SR role is missing permissions to view & edit DLP impact analysis tasks

First I got the message for missing privileges for "organization" and then for DLP Impact Analysis

### Expected Behavior

User able to view and save decision for their DLP impact analysis tasks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Maker Command Center -> Non-compliant tasks page

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Try viewing / editing Non-compliant tasks in Maker Command Center

### Anything else?

These permissions might be overkill, but they fixed the issue. Probably needs investigation, which permission scope makes sense:

Custom Entities -> DLP Impact Analysis
Read + Write (Organization)

![image](https://github.com/microsoft/coe-starter-kit/assets/109345362/cce3be8a-ef0f-492c-adce-812c1dd604d5)

Business Management -> Organization
Read

![image](https://github.com/microsoft/coe-starter-kit/assets/109345362/e10e1c60-846b-4281-8dd8-32f5e5cb84ed)

AB#2971

**Comment by Jenefer-Monroe** [comment]
to area owner to find least priv way to do this.

**Comment by Jenefer-Monroe** [comment]
to new dev owner
