### ISSUE TITLE
[CoE Starter Kit - BUG] HELPER - Get Connections to Clean

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#8133]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

HELPER - Get Connections to Clean inventory flow fails with the below.  Note 3 times this flow failed on the same inventory run.

![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/9ca5f81c-30bf-4cb4-aaf1-7f53a0e51d87)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

HELPER - Get Connections to Clean

### What method are you using to get inventory and telemetry?

Cloud flows

AB#2973

**Comment by Jenefer-Monroe** [comment]
Please go to the step above and get the output of this action
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d57b540b-2b63-4a28-960b-027fdcac79f3)

Does it return records? 
Its saying that that properties > apiId is null which does not seem possible. 
Do you see any that are malformed there?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e3a79de7-3d77-4242-ba2a-5f8ccf23c3bb)

**Comment by PPCan** [comment]
Yes there are records in the output.
![image](https://github.com/microsoft/coe-starter-kit/assets/93291159/4da5e94a-ac70-4e51-807c-38f525a619ae)

**Comment by Jenefer-Monroe** [comment]
I believe the error in that select statement is saying that there are rows in there without the highlighted field (properties / apiId)
Can you please look through and see if you find cases like that?

**Comment by PPCan** [comment]
Well, there are 118889 lines of code in the output.  Do you have a suggestion on how to do that in a practical way?  

Do you have an email address I can send the file too?
