### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can we add custom environment variables in CoE admin command center?

### ISSUE THREAD

**Issue by Wookie2024** [microsoft/coe-starter-kit#8135]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Has the environment variables in the CoE admin command center been locked down? We can only see one of our custom env variables there.
![envvariablesCoE](https://github.com/microsoft/coe-starter-kit/assets/166804074/6fb17d77-ffcb-4ffc-943d-2eae30ecbe5c)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

None

AB#2975

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
