### ISSUE TITLE
[CoE Starter Kit - INFO] Possible bug in Data Export - Flows deleted stills are in json file

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#8136]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

FYI

Hi,

I have detected that the data in some json files is not real, at least in one environment.

Flows in PPAC (Same data from PowerShell) > 12 Flows
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/6fb288b3-1008-4cb9-aa17-b9306e4ee208)

In the Storage Account:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/d6b29658-cc45-4687-9921-4f30164c2fa8)

18 Flows!!!
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/5dd1bc12-0240-4d8e-9d8c-7564edbf2c61)

By this, the data retrieve in Coe Starter Kit may don't be real using BYODL version.

I gave this information to product team and I wait answer about this.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What method are you using to get inventory and telemetry?

Data Export

AB#2976

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. Please do let us know what you find.

**Comment by albertocastro365** [comment]
Without response from product team but after days the data was correct.
