### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE: Innovation backlog app Invalid operation: division by zero.

### ISSUE THREAD

**Issue by MCGDRO** [microsoft/coe-starter-kit#8137]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am running what appears to be the same issue as many other users. I have reviewed the other bug reports and did see the workaround posted in #7678 that states the following.

1.           Open your canvas app in the studio

2.           Refresh the connection to each flow

3.           Save and Publish

However, when I follow the steps above, I have no flows listed in Power Apps studio.

This is a brand new solution, and I have only entered an example idea to present this to my manager, and citizen developers.

![2024-04-24 10_01_10-Innovation Backlog - Power Apps and 12 more pages - Work - Microsoft​ Edge](https://github.com/microsoft/coe-starter-kit/assets/168016371/9265dbc6-ebab-42cc-b04d-d821d667e5d5)
![2024-04-24 10_15_17-Power Apps and 12 more pages - Work - Microsoft​ Edge](https://github.com/microsoft/coe-starter-kit/assets/168016371/c7ea392d-c446-4150-9a58-ad617e489117)

### What solution are you experiencing the issue with?

Innovation Backlog

### What solution version are you using?

3.1

### What app or flow are you having the issue with?

COE Innovation Backlog

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Import COE Innovation backlog into my dev environment.
2. Follow all the steps to set up the solution.
3. Create a new idea
4. Refresh the app

AB#2977

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately we will not be iterating further on these apps, they are being redesigned for a modern version of them: https://github.com/microsoft/coe-starter-kit/issues/4285

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
