### ISSUE TITLE
[CoE Starter Kit - BUG] Failure to upgrade to 4.29 version. A Custom field cannot be deleted (AI Credits Usage)

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#8142]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi, all,

I have tried to upgrade our CORE module from 4.24 to 4.29 in our PROD instance and I get **Cannot delete attribute: utcconversiontimezonecode from Entity: admin_AICreditsUsage since the attribute is not a custom field**

There seems to be a new Table that has been introduced with 4.29, which is **AI Credits Usage**. 

I have previously upgraded our TEST instance from 424 to 4.29, successfully, so I find it odd that this happens in PROD. 

Can you please advise as to what can be done?

I always use "Upgrade" option, my understanding is that, if we use "Update", those old objects will be stuck in the system. Basically, once we use "Update", we'll always have to use "Update", because I cannot get rid of this error.

Please advise,
Thanks,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CORE module upgrade to 4.29

### What method are you using to get inventory and telemetry?

None

AB#2980

**Comment by Jenefer-Monroe** [comment]
One other person saw this and it went away on its own. Which correlates to the fact that it worked for you in a different envt

Can you please let us know what region your envt is in as well as its type? Both for your prod (where it failed) and your test (where it succeeded)

This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

**Comment by VanIsleCA** [comment]
Thanks, Jenefer, region is Canada for both, PROD is a Production environment and TEST is a Sandbox. 

Hope this helps,

BTW, I tried an Update last night and it was successful, but those objects need to be deleted from the system, eventually, so any insight on how to best approach this is appreciated.

**Comment by Jenefer-Monroe** [comment]
Unfortunately there appears to be some ALM bugs in the system lately that are causing issues with folks in random places in the upgrade. I'm not sure how to assist with those.

**Comment by VanIsleCA** [comment]
I understand,

Since last night, I get the error below in the COE, but also all apps in our tenant are affected by this error: 
![error](https://github.com/microsoft/coe-starter-kit/assets/149435271/e28f7798-6bbd-4914-b3f1-e508e9f50bd2)

We are now not sure if this is somehow coming from the COE, because the timing coincides with the COE upgrade. But the COE is also affected by it: "Tenant does not have a SPO license". 

Any thoughts?
Thanks,

**Comment by Jenefer-Monroe** [comment]
No this error in your tenant is not coming from the CoE upgrade. It appears that either a product change impacted licensing requirements (I am unaware of any such change) or your license changed. 
I would suggest reaching out to support with some other app repro, not the CoE, and let me know what they tell you.

**Comment by VanIsleCA** [comment]
Thanks, Jenefer,

As an update, Microsoft got involved and they fixed the issue for the "Tenant does not have a SPO license". In case some others are asking, this was related to an **incorrect rebalancing of licensing in the system**. Indeed, it had nothing to do with the COE and the COE has also been affected by it. Perfect example of an unfortunate coincidence.

Thanks so much for all your help with the COE,

Regards,

**Comment by Jenefer-Monroe** [comment]
Yes please try "Upgrade" again next time. That is the desired way to do it, and I think there was just some product issue blocking you folks from the proper path. Hopefully its resolved next time.

**Comment by VanIsleCA** [comment]
Much appreciated, thanks,

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
