### ISSUE TITLE
CoE Tool kit audit logs not capturing App launch date for any apps 

### ISSUE THREAD

**Issue by Suveemani** [microsoft/coe-starter-kit#8144]
After setting up the new CoE tool kit, we noted that, **Power platform admin view Model-Driven app** is not capturing the App last launch date for any of our apps in our tenant. We initially thought it could be something due to that particular CoE toolkit setup and tried to setup up one more instance of CoE toolkit and ended up in the same behavior. Please find the details below and help us with fixing this issue at the earliest. 

![Audit log issue_CoE](https://github.com/microsoft/coe-starter-kit/assets/168065367/163a42b9-e915-42d0-ba50-5a837571cc11)
![Audit log issue_CoE1](https://github.com/microsoft/coe-starter-kit/assets/168065367/81f4199a-638d-4486-9ab2-99d63360e9e7)

AB#3005

**Comment by Jenefer-Monroe** [comment]
Hello the last launched field is not filled with the basic setup of the kit. This is because the setup is more complex than the initial setup. It requires and app registration and things like that. 
Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Suveemani** [comment]
Hi Jeneffer, We followed all the steps mentioned in the article which includes app registrations along with adding  environmental variables, everything went through fine without any issues. Infact we followed both the approached for storing the client secret as plain text and in secret vault, the associated flow went through without any issues but still the app launch date is not populated.

**Comment by Jenefer-Monroe** [comment]
Hello. Please go launch a few apps, and then see if the following run catches those launches. 
Do note that the flows do not go back for historical launch information, it only starts storing launches from the time you turn on the flows.

**Comment by Jenefer-Monroe** [comment]
Resolved offline, the **_Admin | Audit Logs | Update Data (V2)_** flow was not turned on

**Comment by Jenefer-Monroe** [comment]
Hello. I have created a one-off flow to run which will go back and fix up app information for the ones you missed while the flow was off. 

### Import and Turn On the flow into CoE Environment
Go to https://make.powerautomate.com/ > select your CoE Environment > My flows > Import > Import Package (Legacy)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e2a7c2e7-1e63-4786-a097-b96c481ec51b)

Upload the following flow: 
[Fixupmissedauditlogentries_20240514131140.zip](https://github.com/microsoft/coe-starter-kit/files/15308849/Fixupmissedauditlogentries_20240514131140.zip)

Create the connection and Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/918baa95-1023-431e-a789-757ba832bd11)

When done click Open Flow to view and then back to see details and turn on.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f73573f1-e52b-496e-bdd4-acad4fce7df7)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a2acd671-7c52-4722-882e-9d8a23a52043)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed3f47f0-8c87-4b98-9713-1bfed6a4272b)

### Run the flow
Click Run enter the number of days back you need to go
For example if you missed 3 months of data you would put in 90 (for 90 days)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/74c77b1b-70aa-4f8f-8dcd-a6fdbb4bc4c9)

Flow will turn off your audit logs temporarily while it does this processing. Get everything fixed, and then turn them back on.
