### ISSUE TITLE
Ceo Starter Kit - Audit Logs Component Error

### ISSUE THREAD

**Issue by ecelermi** [microsoft/coe-starter-kit#8145]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,
We are currently trying to implement CoE Starter Kit Audit Logs component with going through the steps described here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

We have filled all prerequisites and have checked them couple times. Also, tried to delete environment variables , publishing the solution and then insert them again and publishing the changes again.

Although we have tried couple solutions which we could find in different entries of CoE Starter Kit Audit Logs, we still get the following errors from the Kit:

- The Flow Admin | Audit Logs | Office 365 Management API Subscription works successfully.
- However, when we try to run the flow Admin | Audit Logs | Sync Audit Logs (V2), we get the following errors:

1. 
"error": {
    "code": "0x80040216",
    "message": "Error occured while reading secret: Value cannot be null.\r\nParameter name: input"

2. 
{
  "error": {
    "code": "AF10001",
    "message": "The permission set () sent in the request does not include the expected permission."
  }
} 

The first error is happening in the action Get Azure Secret and the second one is happening in the action ListAuditLogContent.

Could you give information about what can be the possible reason behind it?
Thank you for your help!
Best
Ece

### What solution are you experiencing the issue with?

Audit Log

### What method are you using to get inventory and telemetry?

None

AB#3002

**Comment by Jenefer-Monroe** [comment]
### Azure Key Vault Failure
Are you using Azure Key Vault to store your secret? If not, this failure is expected and caught. 
Note that flow always shows the first failure even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

**Comment by Jenefer-Monroe** [comment]
### Permission set
The most common issue is in the API Permissions. 
Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
Please share a screenshot (and note that you need to be logged in to GitHub to share images, responding in email will not share them)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

**Comment by ecelermi** [comment]
We are not using the Key Vault but directly inserting the secret value. Also, we have checked the API permissions for the App Registrations and it seems that it is granted for the organisation.

**Comment by Jenefer-Monroe** [comment]
Thanks for confirming on the secret. 
For the App Registration. Is it Delegated or Application Type? Please share pictures it helps us to get to the bottom faster.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
