### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to deploy PowerBI Dashboard

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#8146]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to publish the dashboard getting below error

![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/af6d62e8-21fd-42e2-9a6e-d136046b4658)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Power BI Dashboard

### What method are you using to get inventory and telemetry?

Data Export

AB#3003

**Comment by Jenefer-Monroe** [comment]
Please try the attached. We did ship with a bug in the reports at first.

[BYODL_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14958010/BYODL_CoEDashboard_April2024.zip)
[Production_CoEDashboard_April2024.zip](https://github.com/microsoft/coe-starter-kit/files/14958009/Production_CoEDashboard_April2024.zip)

And then if you still fail:
- have you successfully set up the BYODL report in the past? 
- Are there any queries with a different error message?

**Comment by ALSPowerPlatform** [comment]
Unfortunately, still the same error..

![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/9d83af8b-f05b-4b63-a790-a28b8c8416d7)

**Comment by Jenefer-Monroe** [comment]
And then if you still fail:
- have you successfully set up the BYODL report in the past? 
- Are there any queries with a different error message?

**Comment by ALSPowerPlatform** [comment]
have you successfully set up the BYODL report in the past? - Yes we are using since April 2023.
Are there any queries with a different error message? - No

**Comment by Jenefer-Monroe** [comment]
### Solutions Healthy?
1. When did you last upgrade before this one?
2. Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

### Data in the Dataverse Tables
3. Are you able to view the data (environments, apps, etc) in the Dataverse tables? You can see this in the **_Power Platform Admin View_** app
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/55e638ed-07da-4fee-91d5-5b62279d0505)

### Dataflow Health
View the pbi dataflows in [PowerBi.Com](https://app.powerbi.com/home?experience=power-bi)
4. Is it the Jan version of the Dataflows?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0d774d1e-352e-4f74-82f5-09a2527f3e73)
5. Is it refreshing successfully?

**Comment by ALSPowerPlatform** [comment]
1) Screenshot for solutions : 
We upgraded in Feb before this release. 

![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/6fd158ab-ee94-4eaf-8ce7-5af8bc48b893)

2) Data in dataverse table : 

We are able to see apps and envs etc in the Power Platform Admin View. 

![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/af455601-ab8d-45b6-8a1a-dcf4a649a0d5)

3) Dataflow health : 
Yes it is refreshing daily.

![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/fe4b6bc1-51eb-497f-a042-e0585145673b)

**Comment by Jenefer-Monroe** [comment]
I'm really unsure what is happening for you. But we can keep exploring to see what we find. 

### Correct Dataflow ID?
The DF was a new one in that last upgrade so perhaps you didnt update your notes as the dataflow id was a new one. 
Can you make sure the Workspace ID and Dataflow ID are correct?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a1c23af4-d606-41d4-b5f8-10ee30bcda62)

### Queries resolving?
Please open the DF and open all the queries in edit to see if they resolve to good data:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2e94373a-90ce-43d8-9040-0cfe08a9de92)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fc03a16a-7c4f-4e9a-a9a7-12f45c4282de)

**Comment by ALSPowerPlatform** [comment]
Hello we were able to figure out the problem, somehow the workspace ID was incorrect. Now the PBI is published..

However the number of Flows is incorrect. It is more than 22K but shows only 7.5K.

Can you help us figure out why?

![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/95e97598-bf68-40c0-b9cd-98640204548e)

**Comment by ALSPowerPlatform** [comment]
I have compared. in the table it is 22000+.

![image](https://github.com/microsoft/coe-starter-kit/assets/106515181/cc54ed53-6719-4612-ac87-b5f5ea75410a)

**Comment by Jenefer-Monroe** [comment]
I'm really not sure, I know we had a problem like this in the past with the old Dataflow. 
Are you sure your pointed to the correct, new dataflow and not the old one?

**Comment by ALSPowerPlatform** [comment]
Exactly, even I am wondering why PBI is not showing all numbers, when it does in Power Platform dataflows. Yes it is the new dataflow from April release.

**Comment by Jenefer-Monroe** [comment]
Do you have both the old and new dataflows still in your PBI.Com workspace?

**Comment by ALSPowerPlatform** [comment]
Yes I do have

**Comment by Jenefer-Monroe** [comment]
Ok please delete the old one and see if the PBIT loads correctly.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
