### ISSUE TITLE
[CoE Starter Kit - BUG] Premium connector - Maker report

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#8148]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello there,

We plan to deploy the DLP policy and want to take an overall premium connector so we can contact makers.
Is there a report we can find in our CoE for all premium connectors tagged with Maker/Apps/ Flows/ Environment?

Thanks.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Premium connectors Report

### Anything else?

n/a

AB#3008

**Comment by Jenefer-Monroe** [comment]
In the PBI there is a page called Connector Usage that can be filtered by Premium to get all apps/flows with Premium connectors. 
Is that what you are looking for? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/353fb921-9db8-433f-8102-51fc0998a2aa)

**Comment by RyanCloud8888** [comment]
Thanks Jenefer, that is the new update Dashboard, just updated mine and I saw it now. Thank you.
