### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Power Apps User Shared With Failure - Unable to remove ghost permissions

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#8149]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

From time to time I get an email about a sync flow that has failed.
![Flow error](https://github.com/microsoft/coe-starter-kit/assets/125403575/f0066150-dc32-48b4-8fd0-d86e97421fd9)

I can go to the link it provides, and after enough digging I can find the app GUID that it fails on where it tries to resolve the group name that the app is shared with. If I go to the app, I don't see anything wrong. The maker is in the same boat. However, in the manage permissions app from the CoE, I can see the problem group that the app is shared with. I full suspect that at one point it was shared with a group, but now that group no longer exists. If I try to remove the group shared with, I get an error.

![ManagePermissionsError](https://github.com/microsoft/coe-starter-kit/assets/125403575/b62364f3-d195-4bb3-9078-1519d70a48c4)

I was able to remove these via PowerShell with Remove-AdminPowerAppRoleAssignment. 

I understand this is very likely a fringe case, but it may be something to look at how it removes it on the back end. Using the RoleID, I was able to remove it. 

### Expected Behavior

Able to remove shared with item if it knows there is an item there. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Find app with broken/ghost permission, try to remove via manage permissions app. 

### Anything else?

I don't need this item worked. So, unless you want to keep it open as something for the CoE team to work on, I am okay with it being closed. Just wanted to report it and let you know. 

AB#3009

**Comment by pnoot7** [comment]
You do need to fix this emailing users when submitting a new issue. I got this email:

![IssueSubmissionEmail](https://github.com/microsoft/coe-starter-kit/assets/125403575/7dcf228c-83de-4e45-9ca0-ca292fda69c7)

**Comment by Jenefer-Monroe** [comment]
For the second issue, I've been told by our tools team that its because you are oversubscribed. 
You will need to reduce your watches in the kit: https://github.com/microsoft/coe-starter-kit
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5cdff92e-c99b-4357-b7bc-3a96c9b5501e)

**Comment by Jenefer-Monroe** [comment]
For the first issue, are you able to delete via the product UX? Or only through PowerShell?

**Comment by pnoot7** [comment]
> For the second issue, I've been told by our tools team that its because you are oversubscribed. You will need to reduce your watches in the kit: https://github.com/microsoft/coe-starter-kit ![image](https://private-user-images.githubusercontent.com/89584709/325677460-5cdff92e-c99b-4357-b7bc-3a96c9b5501e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAzNDgsIm5iZiI6MTcxNDA2MDA0OCwicGF0aCI6Ii84OTU4NDcwOS8zMjU2Nzc0NjAtNWNkZmY5MmUtYzk5Yi00MzU3LWI3YmMtM2E5NmM5YjU1MDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1NDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NTVkNmU4OTdlYjZhNjFmNjE0MDdmZDhiNjQ5M2Y3MWVlYjc0MzVjMGViMWJmYzljMjc2OTM4ZWYzOWQyMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rpG890Y-6JSrUYS41REy4R908mbIGkwMNXjU21MN_j4)

Only watching releases, as per the directions in the readme. Not sure this is it. This is the only repo I watch.

**Comment by pnoot7** [comment]
> For the first issue, are you able to delete via the product UX? Or only through PowerShell?

Only via PowerShell, no GUI/web/app worked.

**Comment by Jenefer-Monroe** [comment]
> > For the second issue, I've been told by our tools team that its because you are oversubscribed. You will need to reduce your watches in the kit: https://github.com/microsoft/coe-starter-kit ![image](https://private-user-images.githubusercontent.com/89584709/325677460-5cdff92e-c99b-4357-b7bc-3a96c9b5501e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAzNDgsIm5iZiI6MTcxNDA2MDA0OCwicGF0aCI6Ii84OTU4NDcwOS8zMjU2Nzc0NjAtNWNkZmY5MmUtYzk5Yi00MzU3LWI3YmMtM2E5NmM5YjU1MDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1NDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NTVkNmU4OTdlYjZhNjFmNjE0MDdmZDhiNjQ5M2Y3MWVlYjc0MzVjMGViMWJmYzljMjc2OTM4ZWYzOWQyMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rpG890Y-6JSrUYS41REy4R908mbIGkwMNXjU21MN_j4)
> 
> Only watching releases, as per the directions in the readme. Not sure this is it. This is the only repo I watch.

Can you please post separately? Ill get to the tools team.

**Comment by Jenefer-Monroe** [comment]
> > For the first issue, are you able to delete via the product UX? Or only through PowerShell?
> 
> Only via PowerShell, no GUI/web/app worked.

Thanks, we are redoing some of this work soon so I'll put investigating this with that feature.
Appreciate you helping.

**Comment by Jenefer-Monroe** [comment]
I think the issue with this causing a failure in the Power Apps User Shared With system was resolved with the re-do of that flow in June release. Please do let me know.
