### ISSUE TITLE
Issue with DLP Policy.

### ISSUE THREAD

**Issue by VenugopalDakoji** [microsoft/coe-starter-kit#8150]
I have imported a solution to new environment before adding the Power BI, and O365 groups connectors which are required connectors for the one of the apps in solution, after that i realized and added Power Bi and O365 connectors to the Data Policy. Even though I'm getting similar issues as shown below. 

(It looks like this app isn't compliant with the latest data loss prevention policies.
Policy name: Business - PROD
Business connector: shared_sharepointonline cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_powerbi.
Business connector: shared_office365 cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_powerbi.
Business connector: shared_office365groups cannot be used with non-business connector: /providers/microsoft.powerapps/apis/shared_powerbi.)

Session ID: adf586a1-c065-4195-80a8-434f20e80fd3

![DLP Issue](https://github.com/microsoft/coe-starter-kit/assets/166607688/da2504b1-757b-4a65-810d-731070b0b3fa)

And aslo getting error after I refreshed the SharePoint list which I'm using as one of data source. Please find the screen shot below

![image](https://github.com/microsoft/coe-starter-kit/assets/166607688/f5b3af08-7ff6-49ed-949d-642f4967b0c7)

Please assist me to find a way to my issue.

AB#3012

**Comment by Jenefer-Monroe** [comment]
Hello I'm not sure how to help here. It does not appear what you are using is one of the tools from the cat team. 
Are you just looking for general product support?

**Comment by VenugopalDakoji** [comment]
Hi, yes, I was looking for general support, infract the issue has been resolved now. Thank you very much for your response.

**Comment by Jenefer-Monroe** [comment]
oh wonderful. I'll go ahead and close then.

**Comment by TodoroskiAco** [comment]
@VenugopalDakoji Can you please help me out with this one? How this issue was resolved? I'm still trying to figure it out.
