### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit Logs Migration from Dataflow to Cloud Flow

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8151]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I'm transferring all of the audit information from my data flow coe to the cloud flow coe instance. I'm looking at using the "admin_AuditLogID" field as the foreignkey to prevent duplicates as we have the audit cloud flow activated in the coe cloud flow architecture. 

Is this the right approach to prevent duplicates or should I use the admin_title? Or should I empty the cloud flow table first and just copy over all the values from the data flow coe? Another question is once the information is loaded would the cloud flow coe update the app session information once the inventory flows run and detect the new data in the audit table?

I'm trying to address the issue of historical audit data that would not be available in a cloud flow coe. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Audit Logs

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3010

**Comment by Jenefer-Monroe** [comment]
I've never done this so I'm not entirely sure of the answer unfortunately.  I think that session id is unique though, we seem to use it as a key in our flows too. 

Regarding it upating. If you are on a recent enough build you will have this flow separately in the cloud flow architecture : **_Admin | Audit Logs | Update Data (V2)_**
It keys off rows being added or updated and does things like update the "last launch" so you should be good there. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dfc6ac8f-1c6c-4282-aa82-d5314577578c)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
