### ISSUE TITLE
[CoE Starter Kit - BUG] 'Admin | Sync Template v4 (AI Events)' flow failing when updating AI credits usage. Entity 'admin_Maker' With Id Does Not Exist

### ISSUE THREAD

**Issue by ramontebar** [microsoft/coe-starter-kit#8158]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The flow 'Admin | Sync Template v4 (AI Events)' is failing in the step '**Upsert AI Credits Usage record**' with the error:

"Entity 'admin_Maker' With Id = [userID] Does Not Exist"

![image](https://github.com/microsoft/coe-starter-kit/assets/7858467/35efd62e-7399-4af7-84a1-c89cb4874b36)

So based on what I have found out so far, it looks like there are rows in the **msdyn\_aievent** table of several environments whose users are not registered as makers in the **admin\_Maker** table in the CoE environment. So when the flow **'Admin | Sync Template v4 (AI Events)'** tries to execute the step **'Upsert AI Credits Usage record'** to update the table **admin\_aicreditsusages,** it fails because it cannot create the association.

I have reviewed the failing users and they are active accounts in Azure Entra ID.

### Expected Behavior

I'm still trying to understand what should be the right behaviour here.

Should these users be part of the CoE  **admin\_Maker** table? Or could it happen these users are just consuming the application but they are not actual makers?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v4 (AI Events)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3015

**Comment by Jenefer-Monroe** [comment]
We should probably be using the other User table instead. I will work with the area owner on this one. Likely wont make it for May but we'll try

**Comment by bilodeauju** [comment]
Hi, I just want to report I am also experiencing this same error with 'Admin | Sync Template v4 (AI Events)' flow failing daily since upgrading to 4.29. 
I checked the failing user id doesn't exist in the Maker table but it is active in Azure Entra ID and it exists in the "Power Platform User" table. 
I will look forward to the next update, thanks!

**Comment by Jenefer-Monroe** [comment]
### The work
Deprecated old column
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fd0d6b11-7ee0-4599-b9b1-ac1cab0389f9)

Added new column
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/efa3deb2-da33-4ac1-865c-e3caef46e79c)

Ensure they are in the User table
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ad6d7749-1188-499c-b8db-38f589f73e20)

Change the upsert to point to User table only
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a00464a5-9b40-4cd5-acf7-eb09a1d02e30)

Update PBI
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b079dd97-4b23-42af-819e-ecad86b14756)

**Comment by Jenefer-Monroe** [comment]
Ready for May release.

**Comment by Alyson95170** [comment]
Hi We have upgraded to version 4.31 and the property value is still showing as 1, is this something we need to update manual or should this be fixed in this release?

**Comment by Jenefer-Monroe** [comment]
Yes the value being 1 here is correct, changing to 45 was just suggested as a workaround to backfill data. 
Here shows you how to set and then get back to the correct value of 1 once you backfill
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1a6bea34-2353-4e4d-80c9-31136d610b22)
