### ISSUE TITLE
Developer Compliance App - Licensing requirement

### ISSUE THREAD

**Issue by Chitusnair** [microsoft/coe-starter-kit#8159]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Dear Team,

As I understood, Developer compliance app requires users to have premium license or the app should be assigned per app license. However, when I try to open the app from my normal account with no special privileges (license screen attached), I was able to open the app and add the required missing compliance details through it. This was visible in the Power App admin app in CoE and all looks good. So question is , does this actually require stand alone license? Or am I missing something?

I tried with some other users as well. They also could open the app. For permission, I gave them System Customiser role while sharing app. The app sharing screen **doesn't display** any license warning unlike other Apps like Clean up App. But in the documentation it mentions that for users to use developer Compliance App there are licensing requirements.

Please clarify. Thank you.

<img width="306" alt="LicenseDoc" src="https://github.com/microsoft/coe-starter-kit/assets/29492335/3377e655-f01c-4034-9f70-79f0659ce461">

<img width="559" alt="CleanUpApp" src="https://github.com/microsoft/coe-starter-kit/assets/29492335/6055c2ba-ef56-461b-95e6-128ef449e9dc">

<img width="662" alt="LicenseScreen" src="https://github.com/microsoft/coe-starter-kit/assets/29492335/21407c04-e90a-4f00-a1f3-e2fc68f163ab">

<img width="512" alt="ShareCompApp" src="https://github.com/microsoft/coe-starter-kit/assets/29492335/697a08a3-6fa8-4594-835c-1717a551f9c7">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

February 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3017

**Comment by Jenefer-Monroe** [comment]
Yes it is a requirement to have the Power Apps premium license to use the Dataverse connectors that the app depends upon. It appears that this warning you reference is only shown for Canvas apps and not Model Driven Apps. 

I'm not a license expert, these capabilities are often baked into strange licensing spots in my experience. And some tenants have special grandfather clauses that make debugging such things impossible for a random person outside the org like me. 

However the kit's usage is not unique. So any app with Dataverse connector will behave the same (with the small difference between things like Canvas and MDA like that warning as you referenced)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
