### ISSUE TITLE
[CoE Starter Kit - BUG] Data flows not turning on

### ISSUE THREAD

**Issue by sdadageico** [microsoft/coe-starter-kit#8160]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Data flows are not turning on even though i follow the exact steps described. The data flows that would not turn on are :
CoE BYODL- Apps, CoE BYODL Flows, CoE BYODL Environments

### Expected Behavior

Flows published and refreshed successfully

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CoE BYODL Dataflows

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Navigate to CoE BYODL Dataflows update below:

Data Lake URL:https://gzfpbistrpd1sto001.dfs.core.windows.net/powerplatform

API: https://coepd.api.crm.dynamics.com/api/data/v9.2

AB#3025

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of what you are seeing? I"m not sure what you mean by turn on.

**Comment by sdadageico** [comment]
I have never been able to paste images here. However, I was referring to Data Flows not being published and failing to refresh

**Comment by sdadageico** [comment]
I updated the data lake url, Environment API and map the appropriate table. For instance for the CoE BYODL Apps I map the admin_App table and select primary key and publish it after automapping of columns but the publish keeps failing and sometimes it succeeds but the refresh fails

**Comment by Jenefer-Monroe** [comment]
I'm not sure we will be able to assist without pictures unfortunately as I cant tell what is the matter. 

However, you should not be touching those mapping screens at all other than to click next.

A few notes from the [Configure connections to data sources](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#configure-connections-to-data-sources) documentation

1. Note that you need to do these steps for every query. So touch every one of these queries and create the connection
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a36e9139-297c-42f7-a815-b8836eb4b324)

2. Dont touch any of these mapping configurations
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4a863dad-1e10-424a-8c6e-b140d4076405)

**Comment by sdadageico** [comment]
I followed the exact same steps but the Apps, Model Driven Apps and Flows are failing. The Maker and Environment data flows worked

**Comment by sdadageico** [comment]
while reviewing the error apparently there are syntax errors for some the failed refreshes

**Comment by Jenefer-Monroe** [comment]
Per this comment it appears you are interacting with the mapping 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/21f0d548-90ef-4abc-a987-b24febce9d1a)

It's important that you not change any of the mapping configurations
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e749138a-b018-4f49-842b-c72fd8118723)

**Comment by sdadageico** [comment]
Basically there was no mapping at all. So i clicked ther auto map. Are you saying there should be no mapping at all ?

**Comment by Jenefer-Monroe** [comment]
Yes all the mapping is already done. If you arent seeing it then something is already broken. 
I would presume this means you have not done all the connections. 
I suggest you click each query in the left pane one by one and wait until they resolve. That way you will know if you are missing a connection.

**Comment by sdadageico** [comment]
I followed the steps but publish fails. Is there a way for us to get into a call to look at this issue ?

**Comment by sdadageico** [comment]
I looked at the failed runs and below is the error we saw for the CoE BYODL Apps Data Flow:
{"message":"A validation error occurred. The length of the 'cr9c8_admin_office' attribute of the 'cr9c8_admin_makers_2' entity exceeded the maximum allowed length of '100'.","cdsErrorCode":"0x80044331","HelpLink":"http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80044331&client=platform","InnerErrorMessage":"A validation error occurred. The length of the 'cr9c8_admin_office' attribute of the 'cr9c8_admin_makers_2' entity exceeded the maximum allowed length of '100'.","cdsRequestId":"b783f7d3-6158-4567-95dd-ab9e3ac9f6cd","cdsRequestUtcTime":"4/26/2024 2:37:01 PM"}

**Comment by sdadageico** [comment]
Below is the error for CoE BYODL Environments:

{"message":"Syntax error at position 34 in '(admin_environmentid=Default-7389d8c0-3607-465c-a69f-7d4426502912)'.","cdsErrorCode":"0x80060888","cdsRequestId":"d28ae0d4-7bc1-4465-8a1e-04f6a892aefc","cdsRequestUtcTime":"4/29/2024 3:25:13 PM"}

**Comment by Jenefer-Monroe** [comment]
Sorry no, we are a very small team, only 1 person (me) staffed to assist with GitHub questions and issues. 
As such we are just not funded to meet with our GitHub users 

Have you ever succeeded at setting up the Data Export solution in the past?

**Comment by sdadageico** [comment]
yes it worked in our prior upgrade a few months ago

**Comment by Jenefer-Monroe** [comment]
It looks like you have custom entities / fields
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2534565c-bce8-4655-a024-ef8c6c5e8bc7)

I dont know if this is from you changing the map configuration page? That would do it if you told it to create a new table.

**Comment by Jenefer-Monroe** [comment]
Can you please go to the tables in the CoE envt and search for the following and let me know what you see
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/60a2679f-9707-40bc-9070-8ab01d587496)

**Comment by sdadageico** [comment]
For powerapps I see PowerApps App, PowerApps App Approval Bpf, PowerApps Connector

**Comment by sdadageico** [comment]
For maker I see admin_makers(cr9c8_admin_makers), admin_makers(cr9c8_admin_makers_2), Maker(admin_makers), MakerFew Shot(makerfewshot)

**Comment by Jenefer-Monroe** [comment]
Yes it looks like you've somehow gotten yourself into a bad state there. My guess is that you've changed the destination table in the dataflow. 
I think you'll need to reinstall to get to the correct base state for the dataflows, and then when you get to this step, do not touch anything besides the publish button
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4bc503aa-7da6-44ef-9b5a-202b34d62258)

**Comment by sdadageico** [comment]
your screenshot is referencing Maler table and that data flow is running without any issue. However, I am not sure what/how it happened if there was any mapping misconfig. I am not sure how the misconfig happened. What are my next steps here ?

**Comment by sdadageico** [comment]
ok I will delete the core and re-import

**Comment by sdadageico** [comment]
I deleted the solution and re-imported and now working on data flows but I still see the extra admin_maker tables. IS it still going to be an issue and what are my options

**Comment by Jenefer-Monroe** [comment]
Wonderful news! 
Yes you made those accidently so I suggest you delete them. They should be unmanaged and available to delete.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
