### ISSUE TITLE
COE Starter KIT Governance Component Version 3.20 April Release

### ISSUE THREAD

**Issue by julakantisaiabhinav** [microsoft/coe-starter-kit#8161]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I am trying to upload the Governance Component solution(CenterofExcellenceAuditComponents_3.20_managed) into the Power Platform environment I am getting the error of Connections Timeout.
The exact error says "A timeout occurred while loading the connections picker. Widget ID:'8b055996-1aaa-46c1-aa75-2982-7b5306fd'."
Re-establish Connections to activate your solution.
The connections could not be loaded. Please try again later.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

Governance Component CenterofExcellenceAuditComponents_3.20_managed

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3026

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately that is not an issue with the kit but rather with the product UX. 
The message implies that it was taking too long and should be intermittent. Have you retried? 
If so and its still stuck, perhaps creating the connections ahead of time will help.

**Comment by julakantisaiabhinav** [comment]
Yes I tried multiple times. Connections are created yesterday and completed the Core Components Solution, Audit logs, Power BI dashboard setup today. Then started importing the governance solution then found the issue. Unable to resolve from last one hour by signing out and signing in tried.

**Comment by Jenefer-Monroe** [comment]
Sorry this is a product bug with these new import features and not a bug in the kit solution. 
I suggest you try to install / ugprade other solutions to see if you can repro elsewhere and then you will need to reach out to product support.
