### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Solutions) - Solution modification don't get reflected in CoESK tables

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#8163]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

I've notized that the Solution Version in CoESK and the Environment are different for some solutions.
When the solution version increases you don't see it in the Power Platfom Admin View. Unless you don't make a full inventory run

### Expected Behavior

Information should be up to date

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Increase the version of a solution 
Let the inventory flows run
Check if updated

### Anything else?

this action seems to cause this
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/5f58f6ba-2cc8-4063-8c85-d2f06f9d4d11)
If you change the expression form
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/6cfaccca-7756-4cc7-aca2-4db972cbcb5b)
to
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/e1b508a9-c1a6-4595-a872-eb46bafd7447)
it seems to work

AB#3038

**Comment by Jenefer-Monroe** [comment]
thanks for posting and investigating! Will investigate for an upcoming release.

**Comment by Jenefer-Monroe** [comment]
Thank you so much! That was a terrible copy/paste type mistake. Appreciate you debugging and saving me a bunch of investigation time! 
Ready for June
