### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Sync Template V4 Connection Identities

### ISSUE THREAD

**Issue by inquisitive-identity** [microsoft/coe-starter-kit#8166]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi again,

I apologize in advance if this is something that I could potentially figure out, but I just haven't been able to...

I updated the environment variable _Host Domains_ with additional domains that I need to be excused / filtered out of the PBI Governance Dashboard, and I ran the Admin Sync template for the Connection identities, but it doesn't really do anything to the Connection Identity References table at all... 

All the domains I put in the variable are still toggled to _Yes_, which means that they are considered foreign domains, but they shouldn't be...
Am I missing something obvious or? :)

And one more thing if you don't mind - I tried searching in the docs, but I was wondering if there is a way for me to see which table is used by which flow in the kit? 

Thank you very much in advance for the help! :)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Admin - Sync Template V4 - Connection Identities

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3068

**Comment by Jenefer-Monroe** [comment]
Hello, we had some paperwork issues that kept our documentation stale for a bit. We have hopefully overcome this and will be able to update with June release. 

We do not update the existing data set when you change the host domain, due to the API impact of having to check this every time the flows run. However new data collected going forward will respect the change.

To go back and change the existing data please see: https://github.com/microsoft/coe-starter-kit/issues/7164#issuecomment-1819498144

**Comment by Jenefer-Monroe** [comment]
Regarding flow to table documentation. Unfortunately no we do not have such documentation, and if we did I doubt we would be able to keep it up to date. 
That said, every object holds and can display its dependencies. 
So if you go the default solution > cloud flows > Select an object to show its dependencies you can see them. Like this:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c684ab3f-a562-4f83-ba89-e45e80a07d40)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fc4c2da7-4a71-4d73-b89f-13d6fc3fdf71)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
