### ISSUE TITLE
Maker table lists non-makers

### ISSUE THREAD

**Issue by akumar194** [microsoft/coe-starter-kit#8167]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Maker table consist of a number of users who never created anything in Power Platform. Everything is 0 against their name.

### Expected Behavior

Maker table should only contain makers who has created something in an environment

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What app or flow are you having the issue with?

Maker Table

### What method are you using to get inventory and telemetry?

None

AB#3069

**Comment by Jenefer-Monroe** [comment]
They probably had objects at one point. You can delete them from the Maker table if you'd like and see if they return.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by akumar194** [comment]
I deleted a non-maker and he got added without doing anything in power platform.
