### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by avinajbani** [microsoft/coe-starter-kit#8170]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have a customer asking a few questions for the COE toolkit dashboard from the screenshot attached.

What do the below mean
is Blank = zero?

Apps with open compliance requests? 

Quarantined Apps?

HTTP flows & connectors?

![IMG_0560](https://github.com/microsoft/coe-starter-kit/assets/168463009/480b89ac-5976-42a4-9616-efeda40a9044)

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#3073

**Comment by Jenefer-Monroe** [comment]
Hello. I'm not sure how to answer some of these without just restating the title. So please take a look and let me know where your question lies:

### is Blank = zero?
correct

### Apps with open compliance requests?
They have opt-ed in to this feature and there are apps with open requests
[Setup Developer Compliance components](https://learn.microsoft.com/power-platform/guidance/coe/setup-governance-
components)
[Sample Auditing Process](https://learn.microsoft.com/power-platform/guidance/coe/example-processes)

### Quarantined Apps?
Apps that have been quarantined

### HTTP flows & connectors?
Flows with HTTP actions in them

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
