### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Capacity info missing

### ISSUE THREAD

**Issue by asdkjlkfjgkfdg** [microsoft/coe-starter-kit#8171]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After setting up the CoE Starter kit a few days ago, I don't see Environment Capacity info in the Environment Capacity Table and the Environment Capacity page of the Power BI dashboard. This information did not populate after the sync flows have run, including CLEANUP - Admin | Sync Template v4 (Other Objects), which ran successfully.
![image](https://private-user-images.githubusercontent.com/168126047/325724661-60b66c58-02fd-4837-adf8-e7a5ded31f05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjM3NDgsIm5iZiI6MTcxNDQyMzQ0OCwicGF0aCI6Ii8xNjgxMjYwNDcvMzI1NzI0NjYxLTYwYjY2YzU4LTAyZmQtNDgzNy1hZGY4LWU3YTVkZWQzMWYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQyMDQ0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmU0NGM4N2RmODFjMTc2YTZmOWYwNDVkMDlhY2FiMjYyY2MxYTYxNWRiMGIwZDIzMjgwYWRkOGRhOGUyMmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d_z2QnLdumOligkPYbGVCESS5Y1RolBd_lEUNqXFnlM) ![image](https://private-user-images.githubusercontent.com/168126047/325725041-0a754d5d-7106-4d24-a7a0-b51305311b4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjM3NDgsIm5iZiI6MTcxNDQyMzQ0OCwicGF0aCI6Ii8xNjgxMjYwNDcvMzI1NzI1MDQxLTBhNzU0ZDVkLTcxMDYtNGQyNC1hN2EwLWI1MTMwNTMxMWI0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQyMDQ0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjlmM2FjYmVkNDk3NjZmOTRjODI0NjZjOTEzYjg5N2ZiYzY1YWJlN2JlOWI1ZTAxZWQ0YTU5ZTZmODlkM2NjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kfIvK8R_1yUCUu-TkegtU41LWCBVc028KU5LsJtbjt8) ![image](https://private-user-images.githubusercontent.com/168126047/325726297-3dfedfab-9b5d-4b6e-a61b-f20273ca0289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjM3NDgsIm5iZiI6MTcxNDQyMzQ0OCwicGF0aCI6Ii8xNjgxMjYwNDcvMzI1NzI2Mjk3LTNkZmVkZmFiLTliNWQtNGI2ZS1hNjFiLWYyMDI3M2NhMDI4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQyMDQ0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODRhZWI5Yzk4NzU5YWJlNzE3YTllOTY3YzY3M2MxMDY2OGVjYWNiNGE2ODVlYWNlY2ZmYjE4MzNjNTY1MjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bbbe30rkKAlLF3rH2q70hAvxvN8qeZCBe_QkmS9h_HY)

### Expected Behavior

The Environment Capacity info should populate in the relevant table and therefore the Power BI dashboard as well. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v4 (Other Objects)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Import CenterofExcellenceCoreComponents_4.29_managed.zip to a new production environment
2. Run setup wizard to get flows running
3. Check Environment Capacity Table 

### Anything else?

#8097
OP never replied and the issue was closed, so I am opening a new issue to address this issue. They noticed an old flow was removed, but the environment capacity information should now be captured by CLEANUP - Admin | Sync Template v4 (Other Objects). It appears the environment capacity information is not being captured. 

AB#3074

**Comment by Jenefer-Monroe** [comment]
grabbing your pictures from the other bug as they failed to paste here
![image](https://github.com/microsoft/coe-starter-kit/assets/168126047/60b66c58-02fd-4837-adf8-e7a5ded31f05)
![image](https://github.com/microsoft/coe-starter-kit/assets/168126047/0a754d5d-7106-4d24-a7a0-b51305311b4a)
![image](https://github.com/microsoft/coe-starter-kit/assets/168126047/3dfedfab-9b5d-4b6e-a61b-f20273ca0289)

**Comment by Jenefer-Monroe** [comment]
Let's focus first just on the table to make sure the data gets in there
![image](https://github.com/microsoft/coe-starter-kit/assets/168126047/60b66c58-02fd-4837-adf8-e7a5ded31f05)

First find the recent runs of **_CLEANUP HELPER - Environment Capacity_**
This runs once per envt so we should see some envt getting its rows in this run.
Open one of them, do you see come capacity information in the trigger here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bbed9ae5-e075-4ddb-b3b2-891dda963c7a)

**Comment by Jenefer-Monroe** [comment]
Aww gotcha. Great news. 
Yes on first setup a bunch of these clean up flows run in a way that is a no-op.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
