### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View not showing Default Environment

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8172]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Power Platform Admin View is not showing default environment. We have checked on overview and environment list reports and the default environment is not showing up. Our tenant has about 2747 environments. We did however look for the environment in the environment Dataverse table and it does show up in the environment Dataverse table. We have also validated that this environment is not excused. 

### Expected Behavior

Default environment should show up. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3075

**Comment by Jenefer-Monroe** [comment]
Does the identity running the flow have the Sys Admin SR in the Default envt? 
There is a new PIM feature rolling that is causing some issues for people. We have a workaround for you if you can confirm this is the case.

**Comment by nasilvae** [comment]
> Does the identity running the flow have the Sys Admin SR in the Default envt? There is a new PIM feature rolling that is causing some issues for people. We have a workaround for you if you can confirm this is the case.

We are using an account that has Power Platform administration rights. We can check if it has a specified sys admin role assigned.

**Comment by Jenefer-Monroe** [comment]
oh ok 
As an FYI the PIM feature makes the PP Admin role no longer grant Sys Admin, thats why I asked. 
But if its in the table thats not it.

Click Edit Filters > Delete all the filters
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/52bf090f-18c7-46b3-bf37-e05e6f787344)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1098b206-cf9c-4aac-b4c5-ad8a3cceb19a)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/db489d75-35f2-4745-a706-f247f96c59ac)

I'm sure you'll see it now as you say its in the table, so add these columns and see what their values are
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c87dcecd-16d1-4640-a4fe-cdc9e68227da)

**Comment by nasilvae** [comment]
We noticed the Status column is showing as inactive instead of active. We tried to edit it using the Dataverse table browser and we are unable to do so. We are trying to edit it using a flow.

**Comment by Jenefer-Monroe** [comment]
that is strange, I've never seen that before. We dont use that column its just something the product has. So I presume that got manually flagged as inactive. Once you can get it set back please let me know if it chagnes again.

**Comment by nasilvae** [comment]
> that is strange, I've never seen that before. We dont use that column its just something the product has. So I presume that got manually flagged as inactive. Once you can get it set back please let me know if it chagnes again.

We changed the status and status reason to active and now it shows in the CoE Admin View. We are going over the flows and we noticed that the inventory flows are taking about a day to run which is great given the size of the tenant. We also noticed the cleanup sync template v4 (check deleted) takes about one week to run not sure if this is expected or is getting throttled.

**Comment by Jenefer-Monroe** [comment]
I've worked very hard to make the daily runs faster so YEAH YEAH YEAH!
Once the check deleted flow completes, open the run and see where it spent all its time. It might have gotten throttled I wish there was a way to check that.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
