### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power BI Report - Desktop Flows

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#8174]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

I have two scenarios where the Desktop Flows are appearing in Power BI report - Desktop flows.
1. User created the flows and left the company and his laptop is not active.
2. A resource got new laptop and old laptop is not active.

Why are these old laptop flows are appearing in the report?

Thank you,

### What solution are you experiencing the issue with?

None

### What solution version are you using?

 February 2024

### What method are you using to get inventory and telemetry?

None

AB#3077

**Comment by Jenefer-Monroe** [comment]
Hello, we gather the information for Desktop Flow inventory from the tables that store the the Desktop Flows in each environment. So if the product itself holds these records in those tables we will show them. I'm not sure when or why they decide to clean up records here, you may need to ask https://powerusers.microsoft.com

To ensure the inventory is correct wrt what the product shows, 

### Still in Power Platform Admin View
Do these records still show in the Power Platform Admin View? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b19df3d5-cfe2-41b1-a714-7215d321725f)

### Find the run
If so please find the run for this envt of Admin | Sync Template v4 (Desktop flows)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1d623f5b-3682-4e83-9559-5e2012ab9935)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/750d6c65-2a30-48fc-9f47-a1be93d44007)

**Comment by lingutla123** [comment]
Hi Jenefer,

The flows are showing up in Power Platform Admin View.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/72121238-0625-4909-b2c3-1bdacae3c4b8)

**Comment by lingutla123** [comment]
Thank You Jenefer!

Okay, will follow up with product team. However, I have another question related to report.
Are you excluding any status flows in the report? Is there any filter criteria used to exclude records?

Thank you,

**Comment by Jenefer-Monroe** [comment]
We read directly from the Dataverse tables and then there are some filters, like objects marked deleted. 
You can see these in the PBI Reports:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/93faea5b-254b-48ba-9b35-80b96115ea15)
Hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
