### ISSUE TITLE
[CoE Starter Kit - QUESTION] Custom Connectors Not Found in Connector List - DLP Impact Analysis App (and PPAC)

### ISSUE THREAD

**Issue by inquisitive-identity** [microsoft/coe-starter-kit#8176]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team,

It's me, yet again, after only one day of posting a question with the simplest answer. Thank you again, Jenefer! :)

**Question 1**
Right, so, I am trying to create a new DLP policy, but I seem to be having troubles locating Custom Connectors... 
Truth be told, I don't see them in either the PPAC policy editor or the DLP Impact Analysis app, which is quite strange, because I do have the Power Platform Administrator role and at least one Custom Connector has been shared with me...
But that connector is just not on the list of all other connectors...

**Question 2**
If I compare the numbers of available connectors from the PPAC to the number of connectors in the DLP Editor app, the number is very different (haven't tested to see which ones might be missing as it would take a long time, I presume), so just wanted to ask if it might have been something I did wrong with the CoE installation perhaps?
There are in total 30 custom connectors in my tenant created by multiple people, so the number discrepancy below is _probably_ not because of that.

PPAC:
![image](https://github.com/microsoft/coe-starter-kit/assets/156682353/99eb7bb9-9962-4bbe-bd09-c99a1696c0e8)

DLP Impact Analysis app:
![image](https://github.com/microsoft/coe-starter-kit/assets/156682353/162a7be5-123d-4ad5-86a3-6d774821de9f)

**Question 3**
Please forgive me as this is in reality unrelated to the CoE Starter Kit, but I am still learning about the connectors, APIs, etc., but I was wondering if I got this right. :)
So if I allow a certain API endpoint here, all custom connectors using this endpoint will be put in the proper bucket of connectors, for instance, _Non-Business_, right? :)

![image](https://github.com/microsoft/coe-starter-kit/assets/156682353/197946c4-9318-4bd3-ad4b-83f9764e4e1c)

Again, my sincere apologies, but I am just apprehensive a bit when it comes to things I'm still learning about. :)

Thank you very much in advance for the help! :)

Best regards,
Stefan

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3080

**Comment by Jenefer-Monroe** [comment]
Sorry for the delay. Been prepping the release. 

**Question 1**
Can you show an example of where you do see it, and the two places you mention where you expect to see it but do not? 

**Question 2**
Can you please post this one separately? I'll send to the area owner to investigate.

**Question 3**
I believe you need to add the wildcard star in there. Please see https://powerapps.microsoft.com/blog/new-data-loss-prevention-policies-for-enhanced-power-platform-governance-available-for-public-preview
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ceedc03a-b648-42b2-a8c3-4e05116653d1)

**Comment by inquisitive-identity** [comment]
Hi Jenefer, 
My sincere apologies for the terrible delay, but there were some national holidays and I really needed a short break from work. :)

Right, so, Question 1: 
Essentially, when I try to edit a DLP policy (in either PPAC or DLP Impact Analysis app), I was hoping I would see the custom connectors in my tenant along with all the other build-in connectors, but they are just not there in the list...
Also, in the filtering area, there's no "Custom" at all, meaning that the list is not showing any Custom connector... 
In all other reporting areas (Power BI Dashboard, Power Platform Admin View app), I can see all Custom connectors, but not when I try to work with the DLP policies. :/ 
This screenshot is from the PPAC, but the same problem happens with the DLP Impact Analysis app from the CoE Kit:

![image](https://github.com/microsoft/coe-starter-kit/assets/156682353/37642f90-cda2-41be-83b9-83a5fda786d5)

Q2: Will post another issue for this!

Q3: Oh, wow, okay, thank you very much for the clarification! :)

Again, my apologies for the delay, and thank you very much for all the help, as always! :)

**Comment by Jenefer-Monroe** [comment]
Oh I see now, evidently I needed a break from work to :) 

Yes to my understanding Custom Connectors do not show up here and rather you use the host work from your third question to manage them in DLP.

**Comment by inquisitive-identity** [comment]
Hey Jenefer,
I suppose all of us need breaks sometimes... ;) 

Got it, thank you very much for the help, as always! :) 
Apologies for stupid questions, though :)

Stefan (I should probably change my username :D )

**Comment by Jenefer-Monroe** [comment]
No stupid questions at all. DLP is a very complex area. 
Feel free to return with new questions anytime!
