### ISSUE TITLE
[CoE Starter Kit - BUG] Admin - Gather Tenant SRs

### ISSUE THREAD

**Issue by miroslav-harlas** [microsoft/coe-starter-kit#8177]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,
Cloud Flow "Admin | Gather Tenant SRs" is failing in our tenant at the step "Get SRs from envt with TIDs" for about 200-300 environments out of 1034 environments in total. I have identified no similarities after comparing a number of environments for which it failed and for which it went fine.

Error message in Run Details section is "The specified user is disabled."

When I download response for the failed environments, I can see "statusCode":"403" a following response body:
`
"body": {
        "error": {
            "code": "0x80040225",
            "message": "The specified user is disabled."
        }
    }
`

I'm attaching some screenshots:
![image](https://github.com/microsoft/coe-starter-kit/assets/16306406/d522b4bf-2d82-4195-a12e-e4e42a220253)
![image](https://github.com/microsoft/coe-starter-kit/assets/16306406/a23f447e-1209-4207-a80d-778ad431f06a)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin - Gather Tenant SRs

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Not sure.

AB#3082

**Comment by Jenefer-Monroe** [comment]
Can you please validate the user identity running the flow in one of the environments? 
- Does the User show up as enabled? 
- Do they have the System Admin SR?
- Hit Run diagnostics, what do you see?

https://admin.powerplatform.microsoft.com/ > Find Envt > Settings > Users + permissions > Users

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a802bc2a-2059-4bd7-a929-c4752810ab59)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
