### ISSUE TITLE
DLP Drafts

### ISSUE THREAD

**Issue by rcalmann** [microsoft/coe-starter-kit#8178]
### Is your feature request related to a problem? Please describe.

1. Cannot remove (delete) draft policies, so they keep accumulating and becomes unmanageable
2. Cannot RENAME a draft policy that gets error due to spaces in name

### Describe the solution you'd like

1. allow deletions of draft policies
2. allow updates of policy name if new name matches rules

### Describe alternatives you've considered

none

AB#3083

**Comment by Jenefer-Monroe** [comment]
To feature owner for consideration.

**Comment by rcalmann** [comment]
Looks like the PPAC has different naming rules than the CoE.
PPAC allows spaces in names and CoE does not! 
This is the source of my renaming issue
