### ISSUE TITLE
[CoE Starter Kit - BUG] Orphan Flows still showing Orphaned after new coowner added

### ISSUE THREAD

**Issue by Sinder88** [microsoft/coe-starter-kit#8179]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We had a bunch of flow showing as orphaned and we updated the owner a few weeks ago. Yesterday we picked up that these flows are still showing as orphaned. We can't seem to pick up where the issue might be. 

We noticed that the CLEANUP - Admin | Sync Template v3 (Orphaned Users) has never run before. Seems the weekly trigger is not working, but we can't seem to find out why. We managed to run the flow manually and it was successful. No sure how long we should wait to see if this fixes the orphaned flow issue. Also, how do we get this flow to run weekly? 

Admin view app shows as orphaned:
![image](https://github.com/microsoft/coe-starter-kit/assets/109826106/4c54acc4-ce29-4d2e-b21f-10902fad18aa)

Flow details shows there is an active owner: 
![image](https://github.com/microsoft/coe-starter-kit/assets/109826106/52540077-a9f0-44d5-a722-a8c9d932c541)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Orphaned Users)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3084

**Comment by Jenefer-Monroe** [comment]
Regarding this

> We noticed that the CLEANUP - Admin | Sync Template v3 (Orphaned Users) has never run before. Seems the weekly trigger is not working, but we can't seem to find out why. We managed to run the flow manually and it was successful. No sure how long we should wait to see if this fixes the orphaned flow issue. Also, how do we get this flow to run weekly?

The flow is not a scheduled flow, its called from this flow: CLEANUP - Admin | Sync Template v4 (Other Objects)
Although we did forget to call it from there in the April release, its a new flow. You will see it called from there in May 

All that said, that would not impact the base question you have.

Co-owners do not impact the orphan concept today although it is something we are considering in an upcoming change around ownership.

**Comment by Sinder88** [comment]
Thanks for the information.

Just a slight correction. As you can see from the images in my original request, I am referring to the primary owner and not coowner. So the primary owner there is me and I am active in AD. So not sure why this flow is still showing as orphaned.

**Comment by Jenefer-Monroe** [comment]
Oh I see. Gotcha. So unfortunately, we have not yet updated the kit to use the information from changing the owner in the product but it is on our backlog. We are waiting for one more product change and then will fund this work. Please see [[#3052](https://github.com/microsoft/coe-starter-kit/issues/3052)]( https://github.com/microsoft/coe-starter-kit/issues/3052)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
