### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Desktop flows) failed

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/coe-starter-kit#818]
### Describe the issue

Desktop flow get failed because desktop flow does not exist. My question is that if the desktop flow does not exist then why is it looking for that desktop flow? Where is it getting that data, if the data does not exist in the Desktop Flow table?

    "body": {
        "error": {
            "code": "0x80040217",
            "message": "admin_rpa With Id = 831a4e9d-3802-ea11-a811-000d3a192c48 Does Not Exist",
            "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_rpa With Id = 831a4e9d-3802-ea11-a811-000d3a192c48 Does Not Exist"

![image](https://user-images.githubusercontent.com/59940632/125142064-cb207780-e0e4-11eb-801c-6bd6d4bd8deb.png)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

**Comment by JeneferM-MSFT** [comment]
I've never seen this failure with this object type before. Can you please see if it repros on rerun?

**Comment by aakashpatel660** [comment]
Hi @JeneferM-MSFT 

I rerun the flow and still failed.

**Comment by JeneferM-MSFT** [comment]
Can you please get the data returned in this step 
![image](https://user-images.githubusercontent.com/62659043/125145501-b0e39b00-e0de-11eb-9378-153820089fda.png)

**Comment by JeneferM-MSFT** [comment]
and then please tell me, how many items in the loop fail. Is it just this one? Or is it all of them?

**Comment by JeneferM-MSFT** [comment]
sorry just realized this is an expected and caught failure for flows that are new to the inventory. was it caught? 
can you get a larger screenshot so I can see what happens after the failure? 
![image](https://user-images.githubusercontent.com/62659043/125145628-3404f100-e0df-11eb-9479-fbc55f5d8217.png)

**Comment by aakashpatel660** [comment]
![image](https://user-images.githubusercontent.com/59940632/125145959-a1218200-e0f1-11eb-9bb3-731ca4c976c8.png)

**Comment by JeneferM-MSFT** [comment]
yes, as you can see, the failure **Get Desktop Flow from CoE** was caught, and the variable isNewToCoE is set to true as a result. This is because the flow is new to the inventory. 
You will need to dive into the switch statement to find the actual failure.

**Comment by aakashpatel660** [comment]
Hi @JeneferM-MSFT  

Below is the error message on the switch statement. it is trying to process template language and it cannot process that. 

![image](https://user-images.githubusercontent.com/59940632/125284369-5e28ff80-e2e7-11eb-800a-f4925d5d91b7.png)

**Comment by JeneferM-MSFT** [comment]
This was a known issue fixed quite a while ago in the **_Configure run after_** settings of that switch statement. You are either using an old version of the toolkit or you have unmanaged layers preventing you from receiving updates.

Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by aakashpatel660** [comment]
Hello Jenefer,

I completely deleted the core solution and reinstall the solution. I installed the unmanaged solution which was published on July. I did make sure already and there is no unmanaged layer in the flow. 

Best Regards,
Akash Patel

**Comment by JeneferM-MSFT** [comment]
You should not use unmanaged solutions from us. If one was shipped to you it was not intentional. You cannot change from unmanaged to managed so you will need to start from scratch I believe, perhaps even with a new environment as you cannot uninstall unmanaged solutions.
