### ISSUE TITLE
[CoE Starter Kit - BUG] Cleanup Helper - Check Deleted v4 (Portals)

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8180]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/7060d04c-403e-49a3-a0c3-be998383c0fe)

Schema is not valid given the json output. 

### Expected Behavior

Helper should run. Details sent privately. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Cleanup Helper - Check Deleted v4 (Portals)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3085

**Comment by Jenefer-Monroe** [comment]
Hello. Likely something in the old sync flows added bad data and it was just not known until now as we changed to this set logic technique. 

Please go to the **_Power Pages Site_** table > Click edit to see all data > Add/Remove columns until you see the below
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/292196d3-0d52-4134-be06-1f43c048fa87)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc9846fd-2f42-44a4-81c2-a632fab12052)

Now filter to where there Power Pages Website ID - Does not contain data > Delete these records. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7698e381-4d67-4b26-ad24-a7a37af6686c)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/02046caa-6c18-42d2-a738-d722918ee886)

Then do the same for the Power Pages Unique ID column. 
Now the flow will pass and lets hold for a few days to make sure it doesnt return.

**Comment by nasilvae** [comment]
> Hello. Likely something in the old sync flows added bad data and it was just not known until now as we changed to this set logic technique.
> 
> Please go to the **_Power Pages Site_** table > Click edit to see all data > Add/Remove columns until you see the below ![image](https://private-user-images.githubusercontent.com/89584709/320476697-292196d3-0d52-4134-be06-1f43c048fa87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQxNTIsIm5iZiI6MTcxNDU2Mzg1MiwicGF0aCI6Ii84OTU4NDcwOS8zMjA0NzY2OTctMjkyMTk2ZDMtMGQ1Mi00MTM0LWJlMDYtMWY0M2MwNDhmYTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDExNDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjM2Y1MjA5NTIyMWMyNTVjYzEyNmYyNmRmZTYxMzJjZTA3MjE2YzU5NjM0MzFkOTUzMWEzN2ZmMGUwNGVkNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2TCzC34sAof2tpN_V8pc9cHPwize6COPfLyT5socFLQ) ![image](https://private-user-images.githubusercontent.com/89584709/320477864-bc9846fd-2f42-44a4-81c2-a632fab12052.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQxNTIsIm5iZiI6MTcxNDU2Mzg1MiwicGF0aCI6Ii84OTU4NDcwOS8zMjA0Nzc4NjQtYmM5ODQ2ZmQtMmY0Mi00NGE0LTgxYzItYTYzMmZhYjEyMDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDExNDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NDA0NTFjNDk3Yjg5ZmFkOTU0NzcyMjM3ZDQ2ODFlY2Y4ZTExYTgxZGViYWYyNmVlNzUyMmQwMDhhYmFmMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.psuTalj4IFoqhFgbblzPS7ueESR6k93055Z7jFkruXI)
> 
> Now filter to where there Power Pages Website ID - Does not contain data > Delete these records. ![image](https://private-user-images.githubusercontent.com/89584709/320478508-7698e381-4d67-4b26-ad24-a7a37af6686c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQxNTIsIm5iZiI6MTcxNDU2Mzg1MiwicGF0aCI6Ii84OTU4NDcwOS8zMjA0Nzg1MDgtNzY5OGUzODEtNGQ2Ny00YjI2LWFkMjQtYTdhMzdhZjY2ODZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDExNDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MzM3ZWM0ZTQ4YjRjMDU2MWFhMzU4NWZkZjExY2Y3OWFjODlkZThmZDc4ZTBmNDRiOTE5YzAyNTdjNDQzNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Cy7yvp1HDD0qoOpwBmPlR3jh46Ae-0RJ0S6fJKuKrM) ![image](https://private-user-images.githubusercontent.com/89584709/320478756-02046caa-6c18-42d2-a738-d722918ee886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQxNTIsIm5iZiI6MTcxNDU2Mzg1MiwicGF0aCI6Ii84OTU4NDcwOS8zMjA0Nzg3NTYtMDIwNDZjYWEtNmMxOC00MmQyLWE3MzgtZDcyMjkxOGVlODg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDExNDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOWUzMmY3YzZmYzFiZDg3YzVhYmJkOTcxMWM4Y2MwYjA4NzliMDVlNTg3ZGQ3Yzc3ZjJkZDBiMTk0OTk1ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8_S_CpsYsA_zi9_82zy4CihNaSo2sf4iIW0KdBy4Pxw)
> 
> Then do the same for the Power Pages Unique ID column. Now the flow will pass and lets hold for a few days to make sure it doesnt return.

We just applied the fix. We are now waiting.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
