### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Helper - Apps Not working

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8181]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Helper is unable to find app due to special character. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/6b4ceef5-f0d0-4266-82b7-dd7e0eebaf77)

### Expected Behavior

It should work. Additional Details sent offline. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Sync Helper - Apps

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3086

**Comment by Jenefer-Monroe** [comment]
working offline

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
