### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to change the user that all the flows run as

### ISSUE THREAD

**Issue by mattriesae** [microsoft/coe-starter-kit#8185]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We have the need to change the "owning" user of the CoE solution and flows. Currently, it's a named user and we would like to change the inventory flows and everything else to run as an appropriately-licensed service user. Is there an easy process for that?

Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3090

**Comment by Jenefer-Monroe** [comment]
Hello. The easiest way to do this is to perform your next upgrade as that new user identity. That will transfer all the connections to them.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
