### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE Developer Compliance Center Unresponsive when using Chrome browser.

### ISSUE THREAD

**Issue by cbennett8393** [microsoft/coe-starter-kit#8188]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When using the Google chrome browser to access the developer compliance center, the Canvas Application tiles do not load the selected application's details page.  However, tiles are reactive when hovered over. 

![Dev Compliance Center Non Responsive image](https://github.com/microsoft/coe-starter-kit/assets/154289622/5a2ffab6-6c32-4694-abcb-447b07135412)

### Expected Behavior

When on the app page in the Developer Compliance Center, clicking on the application should open a new window with the details of the application. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Using Chrome Browser Launch Developer Compliance Center. 
2. Locate and Select application that meets filtered criteria. 

AB#3093

**Comment by Jenefer-Monroe** [comment]
I dont repro this. Can you go see what version of Chrome you are using? 
In chrome, navigate to chrome://settings/help
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c147f00f-48c3-4709-a8c5-9da3c533800b)

If you do have a browser specific issue here, unfortunately it will be a product issue and not an issue with the kit. 
These are out of the box controls, and so the on-click is handled by the product.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
