### ISSUE TITLE
COE flows in Core solution are not running

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#8189]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Team,
My COE flows in core solution are not running which caused our database is not up to date. We have only Core installed and today all of sudden we encountered that data is not completely fetched. 
I went to the COE admin center app to check the status of the flows and it was like not all flows are running.
Need your help here:

Attaching the screenshots for the better details. We have only the following flows turned ON.
 
![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/8fab2aee-0d50-430d-a0e5-9894e5d7cd75)

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/143d3a02-4ddd-43fe-8e53-21d594de99f8)

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/c05f92db-6100-48a7-934a-934207dc2f19)

![image](https://github.com/microsoft/coe-starter-kit/assets/111575586/86a4d8f1-8b2e-4275-bffa-d4247df5cee3)

 
 

### Expected Behavior

All flows should run automatically based on scheduled times or depending on the other flows which is not happening.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin - Sync Template V3

### What method are you using to get inventory and telemetry?

None

AB#3094

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
