### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flow Action Details) not working - flows without derived owner

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8191]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/9a83ed1d-caba-4ccf-b3af-78e78c0eb450)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/8ff7e8a3-7c12-490f-959a-62a43ffd146b)

### Expected Behavior

Additional Details sent offline.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3096

**Comment by Jenefer-Monroe** [comment]
working offline

**Comment by Jenefer-Monroe** [comment]
this one ready for May

**Comment by Jenefer-Monroe** [comment]
1.	Add this field to the select columns of this call
Field: `_admin_flowcreator_value`
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0b61edd4-54ca-48b3-ad3a-a5469c9f9214)

 
 
2.	Change the expression here to the below
Expression: 
`@{coalesce(items('Apply_to_each_flow')?['_admin_derivedowner_value'], items('Apply_to_each_flow')?['_admin_flowcreator_value'])}`
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/78350b3a-e99a-4f1d-977a-47c9d713e012)
