### ISSUE TITLE
[CoE Starter Kit - BUG] Orphaned Objects fail to delete app - no permission

### ISSUE THREAD

**Issue by KV-MY** [microsoft/coe-starter-kit#8193]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The manager try to delete the orphaned objects from former employees. The Governance CoE flow "Request Orphaned Objects Reassigned (Child)" fail to delete the app, here is the error

The user with object id 'a0e36fc1-f903-424f-a552-3e353d9dc705' does not have permission to access this.

This object id is our service account when first build the CoE

May i know what permission is missing for our CoE account to perform the deletion?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.15

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

None

AB#3099

**Comment by Jenefer-Monroe** [comment]
The identity that runs the flow is the one that does the delete. 
So please go see if all the connections for these flows are healthy, and if they are the expected identity to run the kit:
### Request Orphaned Objects Reassigned (Child)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c1fa0560-8d86-4c4d-8707-5dc1497a8669)
### HELPER - CanvasAppOperations
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b1f143b7-e424-4a5e-bbb5-051d0177fcf8)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7e2649e2-d0a3-4d62-85b3-450a91df5844)
### HELPER - CloudFlowOperations
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4b2f3532-7e5c-4082-834d-e2fee419c379)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cdd145fd-adf5-4545-9019-d8a9c936e81d)

**Comment by KV-MY** [comment]
Hi Jenefer,

I check the connectors all seem to be healthy, attach the screen shot and error

Request Orphaned Objects Reassigned (Child)
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/6994e398-0470-429f-9861-0eef76d994c1)

HELPER - CanvasAppOperations
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/95c4ad54-0b5c-46d5-bbec-93c3048263e9)

HELPER - CloudFlowOperations
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/80e1d6c7-d353-4e7e-a316-0de7e8a34833)

Error
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/2c0c468c-9048-4020-bba2-2e574af47781)

**Comment by Jenefer-Monroe** [comment]
And does this user (svcO365) has the Power Platform Admin Role directly and permanently assigned? 

Note that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily ![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/67258ff2-7ef5-4207-945d-4f6f2337cfd0)

**Comment by KV-MY** [comment]
checked user (svcO365) has the Power Platform Admin Role directly and permanently assigned.  Also i tested if i use this svcO365 account to delete other app on behalf of owner, i get the same permission error.

![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/253df5f3-2eb8-4d66-9945-9aa8e1b36c43)
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/a4828150-174c-426d-babc-a8906565ba08)

**Comment by Jenefer-Monroe** [comment]
Can you please check the permissions of the svcO365 user in the target envt where you are trying to delete? 
See what SR they have there?

**Comment by KV-MY** [comment]
i checked it is a Team Environment, i could not find it in PPAC, but it appears in PPAV, am i able to check the permissions here?
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/00942375-5297-4550-a293-c07d1e48eee4)
![image](https://github.com/microsoft/coe-starter-kit/assets/160987323/1984743a-baba-498c-9cae-5f8cb73d3622)

**Comment by Jenefer-Monroe** [comment]
Did you try to find it in PPAC as svcO365 ?

**Comment by KV-MY** [comment]
Cant find it in PPAC as svcO365, does it means the environment and app is no longer exit/deleted but still having outdated data in PPAV?  Which CoE flow should we turn on so the environment and app can be updated in PPAV?

Additional Info, In PPAV, this environment is mark as Orphaned but not delete

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
