### ISSUE TITLE
App launch date not getting captured in CoE Tool kit 

### ISSUE THREAD

**Issue by Suveemani** [microsoft/coe-starter-kit#8195]
closing out as no further action for starter kit team

_Originally posted by @Jenefer-Monroe in https://github.com/microsoft/coe-starter-kit/issues/8144#issuecomment-2089380495_
            

AB#3111

**Comment by Jenefer-Monroe** [comment]
Let's just reopen the other issue where all the details are, we can close this one as a dupe.
