### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to exempt flows running steady via service account in clean up process ? 

### ISSUE THREAD

**Issue by TifChen** [microsoft/coe-starter-kit#8196]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We set for the flows that haven't been modified in last 6 months to get this notification : Admin | Inactivity notifications v2 (Start Approval for Flows)

However, there are some business flows running steady via service account in PROD environment. The flows running steady may not have been modified for a long time unless there is an issue. May I know how to exempt those flows in the clean up process ? 

1. Not all the service accounts has a mailbox
2. Users will not login to service account to reject the notification of still in used or not

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.16

### What app or flow are you having the issue with?

Admin - Inactivity notification

### What method are you using to get inventory and telemetry?

None

AB#3105

**Comment by TifChen** [comment]
One thing to add, what will happen if service account did not reply any notification ? Will app / flow being deleted ? 
Thanks.

**Comment by Jenefer-Monroe** [comment]
Hello. If the user (or service account) ignores the pings, we do nothing. You can see the workflow for these here:
https://learn.microsoft.com/power-platform/guidance/coe/governance-components#admin--inactivity-notifications-v2-start-approval-for-flows
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d6f34f5b-42aa-4e7c-8b64-190857e40933)

**Comment by Jenefer-Monroe** [comment]
You can ignore any environment and/or any app or flow at any time, you dont need to wait for the approval process to identify it. 
You can do that manually in the **_Power Platform Admin View_** app, all these objects have a Settings page where you can set this
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ad8ad31c-9b6e-4d09-9396-13247293fbb4)


If you have a large amount you want to exempt, you can either open the inventory in the Excel Add-In and do it there, or write a little flow which identifies the set you want to exempty (ex all owned by the service account) and marks them exempt. 

Hope that helps!

**Comment by TifChen** [comment]
Thank you Jenefer for the details. I think it is safe to use service account for those flows.
