### ISSUE TITLE
[CoE Starter Kit - Feature]: Speed increase on connector setup during initial installation

### ISSUE THREAD

**Issue by redleo85** [microsoft/coe-starter-kit#8197]
### Is your feature request related to a problem? Please describe.

When initially setting up the CoE Starter Kit in an environment a flow sets up all connectors. This flow takes a long time to run (30 minutes).

### Describe the solution you'd like

The apply to each loop, which sets up the connectors does not use concurrency. If the concurrency is activated and set to 25 the flow will run a ot faster (4 mins.).

![image](https://github.com/microsoft/coe-starter-kit/assets/9613325/da894232-92ac-4562-a812-a7e5d0cd20c2)

### Describe alternatives you've considered

I tried setting the concurrency to 50, 25 and 15 and 25 was the fasted execution time out of these 3 options.

AB#3108

**Comment by Jenefer-Monroe** [comment]
Good catch! We dont have any variables in there so we must have just missed setting that property. 
Done for May.

**Comment by Jenefer-Monroe** [comment]
Do you come to our office hours? People are going to love this tiny change and what it does for their life, I'll be calling it out :)

### Office Hours
Please consider attending our monthly office hours. We talk about new features, upcoming changes, and spend most of the time answering your questions. 
More information:
Join the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours) held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
Click here to download the calendar file to add to your calendar: [Calendar file](https://aka.ms/coeofficehours/ics)

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2352f17e-1d9b-4527-b2e6-87648e22ceba)

**Comment by redleo85** [comment]
Great. Thanks! :-)
I need to check, if I find the time to attend the office hours.
