### ISSUE TITLE
Gater Tenant SRs - Error

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#8198]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 

I have the following error, and I am not sure how to get rid of it. Would be great to get help with this. :)

<img width="984" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/62603605/101240e6-0e4a-482e-9f0d-c06ec02360b4">

The respective User has the Power Platform Admin role and created the respective Environment (System Admin in Environment)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Gather Tenant SRs

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3109

**Comment by Jenefer-Monroe** [comment]
This indicates the user running the flow does not have permission to that environment. 
Please find the environment, you can get it by following the url or getting it from the filter out put shown here.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/acb41547-255a-495f-a4a0-031e1d729421)

Then go see what permissions the identity has in that envt

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
