### ISSUE TITLE
[CoE Starter Kit - AI Credits Usage] Table AI Credits Usage (cleanup)

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#8200]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello everyone, everything good?

I have a question, how long have the records in this table been cleaned?

What is the maximum period, as I will use this table with a customized dashboard, analyzing the history

obrigado!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3112

**Comment by Jenefer-Monroe** [comment]
Hello we don't do any clean up on this table. Like the audit logs table we have left it to you all to clean up after whatever period of time you wish to no longer store these.

**Comment by ClaudioRWS** [comment]
obrigado pela ajuda!
