### ISSUE TITLE
[CoE Starter Kit - BUG] Error when upgrading CoE from version 4.22 to 4.29

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#8202]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

Please, I am trying to update CoE from version 4.22 to 4.29 but it is giving an error as shown in the attached images.

I installed the new version but there was an error when uninstalling the old version, can you tell me what I can do to remove the old version and only have the new one?

![CoE1](https://github.com/microsoft/coe-starter-kit/assets/129080740/91ad4c35-7d7e-4766-a09e-2c155760d29f)

![CoE2](https://github.com/microsoft/coe-starter-kit/assets/129080740/815a0253-8a59-4dac-84c6-ba5ae045d41e)

### Expected Behavior

Stay only CenterofExcellenceCoreComponents_4.29 in solutions

### What solution are you experiencing the issue with?

Admin Task Planner

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Update CoE

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3118

**Comment by Jenefer-Monroe** [comment]
Hello, you will need to get the error message from the failure in order to assist.

**Comment by minobrega** [comment]
Hi Jennifer,

Sorry, follow the error messages:

![CoE2](https://github.com/microsoft/coe-starter-kit/assets/129080740/7ce6ed12-cc93-4300-b64d-b86d8d34fb20)

![CoE3](https://github.com/microsoft/coe-starter-kit/assets/129080740/e40c22b4-8dc7-4b9c-81cc-35a43a7a9d08)

![CoE4](https://github.com/microsoft/coe-starter-kit/assets/129080740/e8c62317-fcec-4901-8502-b376402017f4)

![CoE5](https://github.com/microsoft/coe-starter-kit/assets/129080740/fc087e21-4e9c-4755-8a3a-a4ad0b9f4497)

**Comment by Jenefer-Monroe** [comment]
ok this just says that some other operation was happening already. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e28b2551-5b56-4daa-9c25-2359c68e2f32)

So perhaps the real failure is in a different instance, or perhaps the product was doing some solution maintenance of its own. 
Please try again later and then hopefully it works, or if it still fails gives an error message about the solution itself.

**Comment by minobrega** [comment]
But what do I do, do I delete the solution from the previous version, or do I delete the new solution that was imported and try to import again?

![Updatate CoE7](https://github.com/microsoft/coe-starter-kit/assets/129080740/9349f9c3-9246-43fe-a805-0744ea7dcf1e)

**Comment by Jenefer-Monroe** [comment]
You can try to apply the upgrade to the original, 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/994d3c30-eb5e-42df-b34b-24e4792c430a)

or if you have already tried that, you can delete the _upgrade
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/964a2be3-31ff-480a-b5e2-027617a14ec0)

**Comment by minobrega** [comment]
It worked, Jenefer...

Thanks a lot for the help!

![CoE8](https://github.com/microsoft/coe-starter-kit/assets/129080740/86b54a9e-3a4c-48ca-9d00-93faa0b99306)
