### ISSUE TITLE
HELPER - Send Email cannot be used as a child workflow because child workflows only support embedded connection

### ISSUE THREAD

**Issue by ecelermi** [microsoft/coe-starter-kit#8203]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,
We are currently trying to troubleshoot the error we are encountering in CoE Kit.
We have been seent he following error in the flows, where send an email helper flow is used:

Flow client error returned with status code 'BadRequest' and details ''{''error'':{''code'':ChildFlowUnsupportedForInvokerConnections'',''message'':The Workflow with id ...: name HELPER - Send Email cannot be used as a child workflow because child workflows only support embedded connections.''}}''

We could not resolve this issue. 
Could you help what could be causing this problem?

Thank you!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

HELPER - Send Email

### What method are you using to get inventory and telemetry?

None

AB#3129

**Comment by Jenefer-Monroe** [comment]
Hello, it sounds like the **_HELPER - Send Email_** child flow's connections are messed up. 
Please to the child flow, are the connections healthy? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e37a2c74-28c8-4b63-bc52-544da40a05fa)

Click to view the Run only users, these should be the same identity 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b7ee57c2-4aaa-420a-8927-b9975a636666)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/38f3655d-5ace-487c-83bc-5ee0e95ef02a)

If not, please check for an unmanaged layer on the flow.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
