### ISSUE TITLE
[CoE Starter Kit - BUG] : The key didn't match any rows in the table.. Key 

### ISSUE THREAD

**Issue by AleckTK** [microsoft/coe-starter-kit#8204]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

PowerBI BYODL Dashboard report refresh keeps bring this error message up but it refreshes fine in PowerBI Desktop. it used to refresh just fine before. I uploaded it and it refreshed without problems

Table = #table({"workspaceId", "workspaceType", "Data", "workspaceName", "Tags", "ItemKind", "ItemName", "IsLeaf"}, {}). </ccon>;<ccon>The key didn't match any rows in the table.</ccon>. The exception was raised by the IDbCommand interface. Table: Flows.

### Expected Behavior

To refresh without erroring

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

Powerbi

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Setup BYODL Report in PowerBI Desktop
2. Refresh data on Desktop working
3. Step up Dataflow
4. Upload Report to PowerBI Workspace
5. Set refresh time
6. Refreshes fails

AB#3131

**Comment by Jenefer-Monroe** [comment]
This typically means that the data source is wrong. 

Please view the pbi dataflows in [PowerBi.Com](https://app.powerbi.com/home?experience=power-bi)
1. Is it the Jan version of the Dataflows?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0d774d1e-352e-4f74-82f5-09a2527f3e73)
2. Is it refreshing successfully?
3. Make sure the Workspace ID and Dataflow ID are correct?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a1c23af4-d606-41d4-b5f8-10ee30bcda62)

**Comment by AleckTK** [comment]
The dataflow refreshes fine. I have it PowerBI Desktop and I can refresh it without seeing any errors. the report works for a few days and then stops
![image](https://github.com/microsoft/coe-starter-kit/assets/153608822/b6c089ea-eba8-4c36-a9bc-40255f91dee4)

**Comment by AleckTK** [comment]
It's resolving fine no errors
![image](https://github.com/microsoft/coe-starter-kit/assets/153608822/fd99523e-a21e-47b3-a0fc-bc84a42b2bd2)

**Comment by Jenefer-Monroe** [comment]
Did you check all of them? Ex the flows/apps.

**Comment by AleckTK** [comment]
yes they are all okay

**Comment by Jenefer-Monroe** [comment]
1. Have you ever gotten the Data Export PBIT files to work in the past? 
2. Do you have both the old and new dataflows in PBI.com?

**Comment by AleckTK** [comment]
Yes, it worked for months until it just started putting out that error message. I can refresh it fine and reupload it. 

I jus thave the new dataflow. i no longer have the old one

**Comment by Jenefer-Monroe** [comment]
I'm just not sure I'm sorry. This is working for others so there must be something broken on your side.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
