### ISSUE TITLE
App Catalog Usage By Citizen Developer

### ISSUE THREAD

**Issue by iprasadraju** [microsoft/coe-starter-kit#8205]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We aim to establish an app catalog within our organization to centralize apps and reusable components. This setup would enable citizen developers to easily access and reuse these resources, as well as extend their functionality when needed. I've recently come across the "App Catalog" feature as part of CoE - Core Components, and I'm eager to understand how citizen developers can leverage this App Catalog to achieve the mentioned functionality.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

March 2024

### What app or flow are you having the issue with?

App Catalog

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3132

**Comment by Jenefer-Monroe** [comment]
Hello, here is our documentation about our app catalog: 
https://learn.microsoft.com/power-platform/guidance/coe/core-components#app-catalog

Please take a look and let me know if you have specific questions.

**Comment by iprasadraju** [comment]
After reviewing the "App Catalog" link, I've noticed that it only offers partial details, specifically regarding how to add an app to the App Catalog. It lacks information on how a citizen developer can request an app if they are interested in using it on their environment. I've managed to categorize the app in an App Catalog using the "Power Platform Admin View" app. However, I'm seeking functionality similar to installing an app from an app store (App Catalog).

**Comment by Jenefer-Monroe** [comment]
Do you already have the kit installed and inventory running?

**Comment by iprasadraju** [comment]
Yes, March 2024 version

**Comment by Jenefer-Monroe** [comment]
Oh I see, no this app does not off a "take this app and install" type concept. It's just a "get access" type thing. 

For that they click Learn more > Request access
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d478a715-9205-4ab8-a7c4-dac7cb88cefe)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed7617f0-6bd2-4cfd-a003-59fb28cbf859)

**Comment by iprasadraju** [comment]
Thanks for the information
