### ISSUE TITLE
[CoE Starter Kit - QUESTION] What does the "Admin | Sync Template v4 (Portals)" do?

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#8206]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I noticed that the "Admin | Sync Template v4 (Portals)" flow does Not have a description.

Can you tell me what this flow does exactly?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3136

**Comment by Jenefer-Monroe** [comment]
Hello. 

This flow gets power pages information by using the modern Dataverse connector to fetch from the product tables in each environment. It identifies which ones from inventory need updated and updates them.

I've updated the description with this information as well. 

Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
