### ISSUE TITLE
[CoE Starter Kit - BUG] Maker Assessment Starter Dataflow Failed

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/coe-starter-kit#821]
### Describe the issue

I created a connection and after that when I click on configure the connection it still did not configure and when I refresh on the connection that connection is no longer available and I get the below error message. 

![image](https://user-images.githubusercontent.com/59940632/125146060-12613500-e0f2-11eb-90b0-f4805d359794.png)

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

1.60.20210708.1

### What app or flow are you having the issue with?

Maker Assessment Starter Dataflow

**Comment by JeneferM-MSFT** [comment]
You are having issues with the dataflow feature itself, not something with the toolkit. So you will need to seek support from the product team or by hiring a partner who is familiar with the platform. 

Note that the toolkit is not a supported toolkit, and you are experiencing way more issues than most customers do. So you may need to seek partner support.

**Comment by JeneferM-MSFT** [comment]
Closing this one out as it is not a toolkit issue
