### ISSUE TITLE
[CoE Starter Kit - BUG] Missing Informations 

### ISSUE THREAD

**Issue by AbderBPCE** [microsoft/coe-starter-kit#8210]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

we coudn't find some infos related to the admin Flow_lastRunOn as well as the AdminApplastLunchtime ; it's always blank and it's not  normal.
We need those informations on our side in order to create cloud flows for our cleaning environnement strategy.
On top of that we would like to know were to  find the names and mails  of the people to whom the objects , weather it be Apps or flow are shared to besause the number of share is not enough.

thank you for your help.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

power automate 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3149

**Comment by AbderBPCE** [comment]
thank you for your respond.
The problem is that we can find the info sometimes but in 80% of flows and applications there is no data !

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry perhaps I misunderstood, and I missed your question about last launched. 

### Flow_lastRunOn 
It is expected that this be blank for you. We do have plans to fills this for cloud flow architecture but it is not yet available for us.

### AdminApplastLunchtim
Do you have both these flows on? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/dfed1fb1-54bf-4167-a158-8338ff7688e6)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by AbderBPCE** [comment]
Hello, regarding the flows you asked for they are both on for us : 
![MicrosoftTeams-image (1)](https://github.com/microsoft/coe-starter-kit/assets/169038982/55bf33c2-fcca-4791-9783-99fcdf2fa604)
