### ISSUE TITLE
Issue on loading Production_CoEDashboard_April2024.pbit 

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#8212]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

I have an inquiry with regards to loading the Production_CoEDashboard_April2024.pbit PowerBI File.

Specifically when I loaded the file, I get this popup error

<img width="378" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/e106a95f-7204-4a24-bcc3-8601092fd035">

### Expected Behavior

Should load properly without error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Production_CoEDashboard_April2024.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3150

**Comment by Rajatchopra3** [comment]
<img width="378" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/ac818d86-e4e4-4d3f-9df6-20cb16c201a9">
Still getting the same error, maybe because we are using coe version 4.24 and this report is of april.
let me try with march report

**Comment by Jenefer-Monroe** [comment]
Oh yes thats correct. You must match the version of the PBIT with the version in Core.
This table did not yet exist in 4.24

**Comment by Rajatchopra3** [comment]
Matched my coe version 4.24 with the report (march), but now getting this error
<img width="379" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/ccb8aee4-f4d4-4911-9df0-7eda81fb7334">

AI Builder Models
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Apps
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
App Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Apps Launches
Load was cancelled by an error in loading a previous table.
Business Process Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Connectors
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Environments
Column 'Environment ID (with prefix)' in Table 'Environments' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. (Environment ID with prefix (535)).
Environment Capacity
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow Action Details
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Makers
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Pages
Load was cancelled by an error in loading a previous table.
Power Platform Users
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Platform User Role
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Virtual Agent bots
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Desktop Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Desktop Flow Sessions
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Solutions
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
NonProdWords
Load was cancelled by an error in loading a previous table.
Key Measures
Load was cancelled by an error in loading a previous table.
Power Virtual Agent bots usage
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Query parameters
CoE Starter Kit Environment URL
Load was cancelled by an error in loading a previous table.
Tenant Type
Load was cancelled by an error in loading a previous table.

I have followed this steps from other ticket
Open PBID
Stay logged out.
File -> Open -> Browse this device -> navigated to the PBIT file and opened there.
System prompted for ORG URL.
System prompted for credentials.
Data loaded

But still getting this error

When I go to transform data, I can see that all the tables data is getting loaded.

**Comment by Jenefer-Monroe** [comment]
In the Power Platform Admin View app, do you have data for Environments there? 
Please filter the Name column to "Does not contain data". Are there records with this column blank?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4b3922ab-77a6-4cd3-b3dd-395217677906)

**Comment by Rajatchopra3** [comment]
In the Power Platform Admin View app, do you have data for Environments there? - **yes**
Please filter the Name column to "Does not contain data". Are there records with this column blank? - **no**

**Comment by Jenefer-Monroe** [comment]
Can you please share screenshots of
1. The Power Platform Admin View app showing the Envt list? 
2. The solutions installed in the envt
3. The transform data for Envts

**Comment by Rajatchopra3** [comment]
<img width="503" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/80b2b68d-8a14-4dc1-8018-2465c87715ed">
<img width="736" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/baae1f89-d8f1-4534-9f0e-9c8809b9be66">
<img width="389" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/0e6f09a3-f1c8-4d1b-8f78-44b0f2c61ccd">

**Comment by Rajatchopra3** [comment]
<img width="389" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/268f1103-dcd1-4ac7-8388-703d73d49e51">

**Comment by Rajatchopra3** [comment]
![Screenshot 2024-05-07 124557](https://github.com/microsoft/coe-starter-kit/assets/47393750/3744e622-0ef8-4c9e-bb10-152c1ee87032)
![Screenshot 2024-05-07 124452](https://github.com/microsoft/coe-starter-kit/assets/47393750/3b8646b0-5a9f-4cdc-8d08-a7a9fa10fdfa)
![Uploading Screenshot 2024-05-07 125237.png…]()

**Comment by Rajatchopra3** [comment]
![Screenshot 2024-05-07 125237](https://github.com/microsoft/coe-starter-kit/assets/47393750/e38790be-4b52-46b4-ab7b-9fd45421cfe7)

**Comment by Jenefer-Monroe** [comment]
Open the transform again > Environment > Advanced Editor
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/45d28b04-d938-4d47-aa72-2022721feadd)

Paste the following > Done > Share a screenshot
```
let
    Source = Cds.Entities(#"CoE Starter Kit Environment URL", [ReorderColumns=null, UseFormattedValue=null]),
    entities = Source{[Group="entities"]}[Data],
    admin_environments = entities{[EntitySetName="admin_environments"]}[Data],
    #"Removed Other Columns" = Table.SelectColumns(admin_environments,{"admin_displayname", "admin_environmentcreatedon", "admin_environmentdeleted", "admin_environmentdeletedon",  "admin_environmentid", "admin_environmentmakerdisplayname", "admin_environmentmakerupn", "admin_environmentmodifiedon", "admin_environmentsku", "admin_governanceprotectionlevel", "admin_hascds", "admin_maker", "admin_microsoftteamsid", "admin_microsoftteamsurl", "admin_pcfenabled_display", "admin_region", "admin_tenantid", "admin_environmentname"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"admin_displayname", "Environment Name"}, {"admin_environmentcreatedon", "Created On"}, {"admin_environmentdeleted", "Deleted"}, {"admin_environmentdeletedon", "Deleted On"}, {"admin_environmentid", "Environment ID"}, {"admin_environmentmakerdisplayname", "Environment Maker"}, {"admin_environmentmakerupn", "Environment Maker UPN"}, {"admin_environmentmodifiedon", "Last Modified On"}, {"admin_environmentsku", "Environment Type"}, {"admin_governanceprotectionlevel", "Governance Protection Level"}, {"admin_hascds", "Has CDS"}, {"admin_maker", "Environment Maker ID"}, {"admin_microsoftteamsid", "Microsoft Teams ID"}, {"admin_microsoftteamsurl", "Microsoft Teams URL"}, {"admin_pcfenabled_display", "Has PCF Enabled"}, {"admin_region", "Environment Region"}, {"admin_tenantid", "Tenant ID"}, {"admin_environmentname", "Environment ID (with prefix)"}}),
    #"Added Created Month" = Table.AddColumn(#"Renamed Columns", "Created on (Month)", each if ([Created On] <> null) then #date(Date.Year([Created On]), Date.Month([Created On]), 1) else null, type date),
    #"Added PPAC Capacity URL" = Table.AddColumn(#"Added Created Month", "PPAC (Capacity)", each "https://admin.powerplatform.microsoft.com/resources/capacity/environment/" & [Environment ID]),
    #"Added PPAC URL" = Table.AddColumn(#"Added PPAC Capacity URL", "PPAC", each "https://admin.powerplatform.microsoft.com/environments/environment/" & [Environment ID] & "/hub"),
    #"Added Is Managed Environment" = Table.AddColumn(#"Added PPAC URL", "Is Managed Environment", each if [Governance Protection Level] = "Standard" then true else false),
    #"Changed Type" = Table.TransformColumnTypes(#"Added Is Managed Environment",{{"Is Managed Environment", type logical}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [#"Environment ID (with prefix)"] = null or [#"Environment ID (with prefix)"] = "")
in
    #"Filtered Rows"
```

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/67e8bcc5-ae7f-4309-8464-15999bc8ee8b)

**Comment by Jenefer-Monroe** [comment]
ok yes so there are rows in your dataverse table where the name is null. 
Please try this step again, and be sure to use the Name column, not Display Name
In the Power Platform Admin View app, do you have data for Environments there? 
Please filter the Name column to "Does not contain data". Are there records with this column blank?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4b3922ab-77a6-4cd3-b3dd-395217677906)

**Comment by Rajatchopra3** [comment]
Please filter the Name column to "Does not contain data". Are there records with this column blank? - **No**
<img width="736" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/bfd559fb-29cd-49e8-a5b3-e7206e2e2be2">

**Comment by Rajatchopra3** [comment]
yes, that worked thanks
