### ISSUE TITLE
[CoE Starter Kit - BUG] HTTP Entra ID connection error in GCC High

### ISSUE THREAD

**Issue by marcegd19** [microsoft/coe-starter-kit#8213]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I´m running the CoE installation in a GCC High tentant, when I try to create the Connection of "HTTP with Microsoft Entra ID" I get the following error:

<img width="274" alt="Microsft Entra ID error" src="https://github.com/microsoft/coe-starter-kit/assets/169068268/0a87d1bd-01c2-471b-9da3-60332cfb71c6">

The Power Shell script to "Authorize the connector to act on behalf" was run and complete successfully, however the error is still present when try to create the connection. [(https://learn.microsoft.com/en-us/connectors/webcontentsv2/)]

So I tried with HTTP with Microsoft Entra ID (preauthorized) connector instead and receive the below error. 
<img width="446" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/169068268/f5fa627e-719c-4afa-9069-eb4e48f39cb3">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Microsoft Entra ID connector

### What method are you using to get inventory and telemetry?

None

AB#3152

**Comment by Jenefer-Monroe** [comment]
**HTTP with Microsoft Entra ID (preauthorized)** is the correct connector. 
What url did you put in for it?

**Comment by marcegd19** [comment]
> **HTTP with Microsoft Entra ID (preauthorized)** is the correct connector. What url did you put in for it?

I used the endpoints for the Azure portal and Microsoft Graph required for GCC High: https://portal.azure.us and https://graph.microsoft.us

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
