### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Kargadong-Putik** [microsoft/coe-starter-kit#8216]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to save custmize emails

### Expected Behavior

when customizing email from CoE Admin command center, clicking save nothing happens.
![saving](

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CoE Admin Command Center Cutomized Email

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1) Go to CoE Admin Command Center
2) Go to Customized emails
3) In my case I selected "Edit mail: Send list to manager - failed or timed out". Edit the body
4) Nothin happens, it just sit on the dialogue to save.

### Anything else?

n/a

AB#3155

**Comment by Jenefer-Monroe** [comment]
Hello. I dont repro this. Can you please do the following?

### See if you have layers and missing data
1. Ensure you dont have an unmanaged layer on **_Admin | Sync Template v3 Configure Emails_**
2. Run it with the parameters as shown here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0abc835f-2adc-4e85-bb87-e7f215f5919e)

3. Ensure you don't have an unmanaged layer on Command Center Email Configuration page

### Now try again
1. Boot the Command Center > Customize Emails > select your mail
2. Add some test text and hit save
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c63f335f-b2bf-4afe-83e7-3c736320862c)

3. This pops the confirmation dialog
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cf47ef5c-0435-499b-bdad-56a96958d8a0)

4. Hit Save and it shows as saved
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/946547c5-cc72-4581-811c-fc6871a34a5e)

**Comment by Kargadong-Putik** [comment]
Hi Jenefer,

- There are no unmanaged layer on the flow. Please see screenshot.
![image](https://github.com/microsoft/coe-starter-kit/assets/52743509/5425013b-b8e0-4e79-a06f-bb909f67fee4)

- Tried running the workflow "Admin | Sync Template v3 Configure Emails" 
![image](https://github.com/microsoft/coe-starter-kit/assets/52743509/ad588827-97b5-4461-bcc1-3b9cfb069f57)

- Still cannot save the changes on the template, nothing happend when I click on save.
![image](https://github.com/microsoft/coe-starter-kit/assets/52743509/c4bedcae-523c-42e2-83e2-16604fcbccfd)

**Comment by Jenefer-Monroe** [comment]
It sounds like its not even getting the click? Can you try a different browser?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
