### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Tracharr** [microsoft/coe-starter-kit#8219]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi I have tried updating the c of e but cannot get the march or april update to install - it fails and I have a half installed version with the old v3 flows and the new v4 flows. I have tried deleting the update and re-installing but get the same issue.
![image](https://github.com/microsoft/coe-starter-kit/assets/135856790/8ed30c1b-7e04-4253-863a-b33cd0c27b05)
![image](https://github.com/microsoft/coe-starter-kit/assets/135856790/d2db7c84-1d23-4df3-9939-b43109f08fca)
Please help as my environment is in a half installed state and need some help getting it fixed

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

All V3 flows

### What method are you using to get inventory and telemetry?

None

AB#3162

**Comment by Jenefer-Monroe** [comment]
Hello, I will need to know the error message from the failure in order to assist.

**Comment by Tracharr** [comment]
Hi I think I may have fixed the issue, the wizard is now running and getting to additional features. I will double check and close tomorrow if all ok

**Comment by Jenefer-Monroe** [comment]
wonderful, thanks for the update!

**Comment by Tracharr** [comment]
Hi set-up wizard working however when I try to configure compliance or inactivity I get this 
![image](https://github.com/microsoft/coe-starter-kit/assets/135856790/425953b4-d0d3-4ca4-9ed6-816c22b6f251)
However both flows are on and already run???

**Comment by Tracharr** [comment]
Ignore that even though they had run - I ran again manually and seems to have sorted itself.
