### ISSUE TITLE
[CoE Starter Kit - BUG] Legacy Power BI - Cloud flows issue with Creator filter

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#822]
### Describe the issue

The Creator filter in the Cloud flows report does not show all makers.  There are 85 makers in total in my client's tenant but only 12 show in the Creator drop down
![image](https://user-images.githubusercontent.com/41050216/125175173-69fcbf00-e21e-11eb-9c65-1f2c6abc4fd2.png)

### Expected Behavior

The Creator drop down list should contain all makers

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_2.2.20210707.3_managed

### What app or flow are you having the issue with?

CDSLegacy_CoEDashboard_202107

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/41050216/125175236-d1b30a00-e21e-11eb-87b0-3115e487de32.png)

### Anything else?

From what I can tell, it looks like the Creator list is only showing environment makers / owners.

**Comment by manuelap-msft** [comment]
Hello,

I'm working on fixing this but in the meantime, you can swap this filter to the admin_flowcreatorname field of the Flow table:
![image](https://user-images.githubusercontent.com/55705669/125255277-29bb4080-e2f3-11eb-918f-9ecd49e37296.png)

**Comment by manuelap-msft** [comment]
Hello,

fixed this issue and the new version of the Dashboard is now available either via the main download aka.ms/coestarterkitdownload or directly here: https://github.com/microsoft/coe-starter-kit/blob/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/CDSLegacy_CoEDashboard_202107_v2.pbit

Thank you
Manuela

**Comment by manuelap-msft** [comment]
(re-opened this issue, as this will be included in the August release and our release notes are generated based on Open Issues in a Milestone)

**Comment by mikefactorial** [comment]
@HamishSheild This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
