### ISSUE TITLE
[CoE Starter Kit - BUG] Solution Assessment App - Admin Email Variable Not Populating

### ISSUE THREAD

**Issue by inquisitive-identity** [microsoft/coe-starter-kit#8221]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi team,

I just wanted to report this bug with a **prepared simple fix**, so that you could potentially roll it out with the next CoE iteration. :)

**Problem**: The Solution Assessment app is using an Environment Variable called "admin_MakerAssessmentAdminEmail", however, I noticed that whatever I put into that variable, the "To" field on the final screen of the app where you can choose to contact the support team is always blank.

**Solution**: 
1. Edit the canvas app that's embedded into the Solution Assessment model-driven app
2. In the "OnStart" property, search for the "EmailDefnID" variable
3. Just replace what I suppose was an old value for the "Schema Name" from "**admin_MakerJourneyAdminEmail**" to "**admin_MakerAssessmentAdminEmail**" 
4. This way, the variable gets populated with a proper value from the Dataverse table "Environment Variable Values"
5. I have already replaced it in my app (as shown in the screenshot), but I wouldn't like to publish this because of the unmanaged layer and whatnot, so I thought to tell you about it and perhaps get it fixed for the next iteration. :)

![image](https://github.com/microsoft/coe-starter-kit/assets/156682353/0bd77dd5-fe6b-4124-b811-10b7e6d8ee1c)

Thank you for the wondrous work you all do! :)

Best regards,
Stefan

P.S. I'm so proud of myself for having resolved this on my own :D

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Nuture Apps - Maker

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3173

**Comment by Jenefer-Monroe** [comment]
WAY TO GO! YEAH!!! 
Thanks for your help, I've local fixed this for the next release. Unfortunately we just missed the May release pipelines but we are all set for June. 
Thank you!

**Comment by inquisitive-identity** [comment]
Hey Jenefer,
Thank you for the kind words, it truly means a lot! ^^
I'm glad to have contributed! 
To be honest, day by day, I get more and more fascinated by all the stuff you've made in the kit. :)
I suppose you can close this issue then :)

Stefan

**Comment by Jenefer-Monroe** [comment]
Let's do keep it open if its ok with you. That way it will track and close with the release of the June build where you will see your fix.

**Comment by Jenefer-Monroe** [comment]
By the way, are you aware of our office hours? Its a monthly sync where we show new features and answer questions. You should consider joining! 

### Office Hours
Please consider attending our monthly office hours. We talk about new features, upcoming changes, and spend most of the time answering your questions. 
More information:
Join the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours) held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
Click here to download the calendar file to add to your calendar: [Calendar file](https://aka.ms/coeofficehours/ics)

**Comment by inquisitive-identity** [comment]
Oh, that's perfectly fine by me; I just thought you'd like to have it closed. :)
Open it shall remain then! :)

**Comment by inquisitive-identity** [comment]
Ah, missed the message about the office hours - yep, I have the meeting in my calendar, but the last two times I couldn't join due to some heavy workloads, but I was planning on actually joining this (and every consecutive) time! :)
