### ISSUE TITLE
[CoE Starter Kit - QUESTION] - Column "Flow contains broken connections" is OFF

### ISSUE THREAD

**Issue by SegoleneDuong** [microsoft/coe-starter-kit#8222]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How can an update my column "Flow contains broken connections" from my Flow table ?
Every line in equal to No but it’s not reflecting the reality.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.16

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3174

**Comment by Jenefer-Monroe** [comment]
Hello. That is not what that field means. It's an internal field we use to identify when a flow or app has connectors which have not yet been inventoried. 
So imagine you create a custom connector, then add an app to it. And then the app goes into inventory before the custom connector goes into inventory. In this case we need to send the app through inventory again the next day after the custom connector has been inventoried. 

This has been renamed recently to make this more clear
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/556f2e7d-2cc2-459f-acf3-282a2bbf8c1f)

The thing you are trying to find is useful but its not something we have programmatic access to. We only know what **_connectors_** an app/flow uses. We do not know which **_connection_** it uses.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
