### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v4 (Check Deleted)

### ISSUE THREAD

**Issue by JuanCatolico** [microsoft/coe-starter-kit#8223]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Unable to establish connections for this flow. BadRequest error. Flow does not turn on.
![2024-05-07_8-22-21](https://github.com/microsoft/coe-starter-kit/assets/169176625/b582dae9-0325-44e5-b9da-0a4dc7d516cd)
![2024-05-07_8-19-11](https://github.com/microsoft/coe-starter-kit/assets/169176625/690fb349-34c7-4784-8d99-ab6cb43aa8b6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.02

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Check Deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Edit flow
2. Confirm connections
3. Save Flow

AB#3175

**Comment by Jenefer-Monroe** [comment]
We've seen this happen before. I believe the solution was as follows: 

Please log in as the user who’s identity installs and runs the kit and do the following:
### Unmanaged layers.
Make sure you dont have unmanaged layers on the flow
### Fix connections. 
Browse to the connections in the envt. If there are any broken connections please repair them
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2198fb17-1107-4851-a744-f3b34e89d11d)
### Fix Connection References
Go to the Default Solution > Connection References
Make sure they are all pointed to the correct identity which is intended to run the flows by doing the below for all connection references.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f630670f-9bf5-4c56-bf18-9693e0eeea01)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d4a34cc4-5d46-494e-9a7d-e9d570489159)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by JuanCatolico** [comment]
Apologies for the delayed response. I followed the instructions and fixed the connection references. However, I am still getting the same error message when attempting to turn on the flow. Please advise.
