### ISSUE TITLE
[CoE Starter Kit - BUG] Apps with SPN owner are marked like Orphaned

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#8224]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
now like you know, after the arrives of the Power Platform Pipelines, we can deploy solutions delegated in a Service Principal.

Then, the owner of the flows or apps in the target environment will be this SPN.

But these apps or flows are been marking like Orphaned:

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/c424cd6f-8680-4939-abc1-a48c9b28018d)
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/178f7407-7b3c-4845-8cfe-fbf77feea731)
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/3c8018ed-4548-49e5-93de-af7cf64ade7f)

### Expected Behavior

If a flow or power app have a SPN like owner is not orphan, only if this spn is deleted from Entra ID

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Power platform admin view

### What method are you using to get inventory and telemetry?

Data Export

AB#3176

**Comment by Jenefer-Monroe** [comment]
I dont repro this. I do see Service principles correctly identified as non-orphan. So lets please debug together. Can you do the below and let me know what you see?

Here is my test case
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/89419956-64a6-4f78-a2e4-ee1bb361e816)

Please go to **_HELPER - Maker Check_** and run your test case. 
Be sure to enter the GUID and select "Recheck" as true
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3955a780-844d-4308-8fa4-f721a7657f03)

Open the run and follow its path. Its long and windy, sorry. Should look like this
Goes down to checking if user. This fails and is caught in the next screenshot
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/17c7ab96-83d0-48e0-8f68-a6285293baed)

On catch it tries to get it as a service principle
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3d2c9f55-3d6a-482f-b0d1-fdfb4357b29b)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/013f8e9a-b49e-42c8-9ecf-facb64b03692)

**Comment by albertocastro365** [comment]
Hi @Jenefer-Monroe,
After run this flow with the spn ID, the data is updated.
I mean:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/76eed19a-cd59-4bc7-8fd3-3eea4cf39fef)
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/d98eef97-b228-4766-9090-5cecfcd6e504)

But the app still is marked like Orphan. To this point, I supose that I have to wait to execution other flows to sync all data, but, what could be the reason because the SPN are not retrieve the data from "HELPER - Maker Check"? What is the parent flow of this HELPER?

**Comment by Jenefer-Monroe** [comment]
Its called from serveral places, but if you can please share what happens in the flow per my request above, then we can debug together. That's what I need to see.

**Comment by albertocastro365** [comment]
OK, here the execution:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/e3dcc824-3685-4fea-a6f0-660e657337c8)
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/76e99b18-8cda-412e-b237-57d3f7ce4fa6)

**Comment by Jenefer-Monroe** [comment]
ok wonderful, so it is found. I'm glad to see that! 
Now what path does it take in these? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6f4e849f-556b-4587-9d86-2963427d666a)

**Comment by albertocastro365** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/a3cf466f-1855-4b6d-9c81-691c8e346503)

**Comment by Jenefer-Monroe** [comment]
Great so its correct here: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d242b398-ef13-4d9a-a6b1-6fde30718d6f)

Can you confirm what you see here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/85a1ffa9-a9b9-4c54-9333-db0d8e6cb9ac)

**Comment by albertocastro365** [comment]
Do you mean this?
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/8b6701d7-94ec-4c77-9426-fd121f3620f8)

**Comment by Jenefer-Monroe** [comment]
I did yes and it looks like it also correctly marks the object as not orphaned.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/aeda401d-2dd6-4ac0-a19a-166c6f88470d)

**Comment by Jenefer-Monroe** [comment]
So after you run this flow and refresh the user, it should show as not orphaned yes?

**Comment by Jenefer-Monroe** [comment]
Oh I see and then its the app that is still marked orphan. So the following flow is supposed to correct that. 
So make sure that maker itself is no longer marked orphan after the above, then run **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_**

It should fix up the apps

**Comment by albertocastro365** [comment]
After run the flow:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/02f2d1c6-49fa-417c-ba14-7836c1a28770)

The app still is orphaned::
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/cf6a1186-fe08-4cb8-aada-aadb45a0a71f)

**Comment by Jenefer-Monroe** [comment]
Is this app marked deleted? 

Please open CLEANUP - Admin | Sync Template v3 (Orphaned Makers) in edit. 
Is this what you see? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/46ec6324-871e-47d4-a700-ada611ec82af)

**Comment by albertocastro365** [comment]
No, the app is not marked deleted:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/2507da20-0a2f-46bc-aa0a-9a80da6686dd)

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/376d4011-03bc-4233-ab61-243b6321a452)

**Comment by Jenefer-Monroe** [comment]
OK according to this screenshot the owner did get set to not orphaned. Can you please validate? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/061c5882-5962-4462-9a3f-210fc01dcdcd)

**Comment by albertocastro365** [comment]
Hi!:

I don't know what is happening! 😞  Again the spn owner it's showed like "unknown" 

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/c34e1d9d-f109-42d5-a22b-4a04521bf0b1)

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/cd6581ed-53f5-4fdc-9877-2d3101db202c)


PowerApps App table:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/1c544e2c-8492-4cc6-a2c2-0fb54259c987)

**Comment by Jenefer-Monroe** [comment]
Are you sure you are looking in the same environment? You're not looking across dev/prod for example? 
That action that you screenshot showed it setting the field.

**Comment by albertocastro365** [comment]
Yes Jennefer, it's the same environment, Production. I only use Development environment to test the import of new releases but I have have all dataflows/flows turned off.

**Comment by albertocastro365** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/321357ca-eab1-41e7-8bc1-17c8bff81d41)

**Comment by Jenefer-Monroe** [comment]
and is that the correct GUID? for your SPN?
Meaning now that this has run is it correct?

**Comment by albertocastro365** [comment]
Yes, that is the GUID of SPN owner of the app.
Now, after run this flow, the info showed of app is totally correct, the app is not orphan.
But I still have the doubt why this info is not updated automatically and what other process reset this info? Because I have other case with this issue.

App:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/374d241d-86fa-4257-ad58-f250b7bae057)

SPN:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/57f47d66-4779-44b3-8b40-61f9b8484c42)

**Comment by Jenefer-Monroe** [comment]
For cases where you still have the issue, please see when that inventory row was last updated. 
This SPN code is newer, both for the product returning correctly, and for our ability to detect it. 
My guess is that the app was just populated in inventory before we knew how to do them.

**Comment by albertocastro365** [comment]
Record of the app was updated by my manual execution of the flow:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/d281c1f9-8da9-4d15-9a75-cad3edbda9aa)

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/3c703556-affa-4fc9-b08d-62b19724d53e)

**Comment by Jenefer-Monroe** [comment]
Sorry I meant for other cases that are still incorrect.

**Comment by Jenefer-Monroe** [comment]
My theory is that this case was not updated "automatically" because the records last went through inventory before this code was in place. And so now that this code is in place, any apps that go through inventory will be correct.

**Comment by albertocastro365** [comment]
More info:
I have spns OK, but other not, just after update to lastes release:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/f85baf6b-96bc-47b4-9e20-d432033c3b45)

**Comment by Jenefer-Monroe** [comment]
And are those SP's real and still in the system?

**Comment by albertocastro365** [comment]
Yes, of course:

Lastest dataflows refresh:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/857c84be-e474-4e0b-b5db-8d691a1b6c7e)

Makers table:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/dda63328-e484-4580-9562-8619c9359b96)

SPN exists:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/136d5a96-0f01-4993-9001-fa1d1de04a4b)

The flow HELP - Maker Check is running now:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/caba84b4-825f-4612-b6bf-8557546eb405)

But the flow SYNC HELPER - Apps has finished:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/1006f687-c8f2-4b43-98f2-e0d4c91c311e)

Then, I supose that when apps are syncronized with SYNC HELPER - Apps the owner still is unkown and orphaned, by this the app is orphaned.

If the order of execution will be inverse, first execution to HELP - Maker Check and after SYNC HELPER - Apps, the info of the app will be correct.

But, I don't find the root issue: why the dataflow mark these spn like Unknow.

**Comment by Jenefer-Monroe** [comment]
Looking through the Data Export specifics, I do see that this is supposed to be fixed up in the following flow.

So if these are added by the Dataflows, this flow is supposed to call to fix them up. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8aee9191-7953-4213-b64a-d18b2f0dafe8)

Can you please : 

1. Delete these "unknown" records from the maker table
2. Delete the refresh history for all dataflows back to before you saw this bug repro
3. Ensure this flow is on and has no unmanaged layers
4. Trigger the dataflows to run.

**Comment by albertocastro365** [comment]
Solved! 
I had other users (spn and normal users) like "Unknow", deleted them, clean history of dataflows and after run the dataflows again thier data is ok!

**Comment by Jenefer-Monroe** [comment]
oh goodness. I am so glad we persisted here!
