### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v4 (Check Deleted)

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8225]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Slow performance it takes 8 days for the flow to complete which creates overlap for the next run. 
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/3e647335-a708-4e1f-83b5-fb4a553fbfba)

More details offline

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v4 (Check Deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3177

**Comment by Jenefer-Monroe** [comment]
Unfortunately there isn’t anything I know to make this more performant. We are open to ideas but I don’t see any sections here that I can make better with current architecture. 

You will need to change the trigger to be less frequent and just have this be an unmanaged layer on the system. When we get the next set of Data Export features, hopefully they will work and this nice big tenant wont have to rely on the sync flows.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
