### ISSUE TITLE
[CoE Starter Kit - BUG] Note from your Power Platform Admin: This flow appears to be unused; but the just saved in the AM

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#8226]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The user still gets an email notification for  "Note from your Power Platform Admin: This flow appears to be unused: Can we delete it? <Flow name>; but they just saved in the AM and on the same day, in the afternoon they got the notification?  Is there any way that where we can check or tune-up? or can we extend the check time at least 60 days? instead of 30 days (I think?).

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CLEANUP - Admin

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3178

**Comment by Jenefer-Monroe** [comment]
Yes this just means that the inventory does not yet know they modified the flow. I dont think you can work around that other than checking each one before you send, which would be too API intensive.

For settings, you can change how far back to consider "inactive" with these [env vars](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components#all-environment-variables). Is that what you mean? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bca912c7-2ad9-49ed-9720-e98e57dc8ad4)

**Comment by RyanCloud8888** [comment]
Thanks Jenefer.
You said, "_Yes this just means that the inventory does not yet know they modified the flow. I dont think you can work around that other than checking each one before you send, which would be too API intensive_."  so how often does the inventory check? 24 hours?
For the setting, I already set to 12 months.

**Comment by Jenefer-Monroe** [comment]
Yes it is set to run each day, so ~24 hour delay between inventories. 
The flow will look for things then that havent been edited in a year. And sounds like your user just got unlucky there in when they did the edit. 
Please let me know if I misunderstand.

**Comment by RyanCloud8888** [comment]
Thanks Jenefer.  
Another question, i'm now confused, I thought if the flow has been modified within the last 6 months, user should not get a clean up notification? am I wrong?
Is there anyway, we can set it to 12 months to check for modified date?

**Comment by Jenefer-Monroe** [comment]
Now I'm confused too haha

Here is a visual to assist us. Taken from [Whats in the kit](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#inactivity-processes) section of the documentation. 

This is where that env var is used. And yes you can set it to say, ignore if modified in the last 12 months. By default its 6 months. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9db32959-2e85-463a-8d9d-9494acbc7e5d)

Here is the env var:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/22a740b9-a7bc-41aa-93ca-4cc4a770b5a2)

**Comment by RyanCloud8888** [comment]
:)
hmm, I already set to 12 months, it doesn't take effect?  how can I check Jenefer?
![image](https://github.com/microsoft/coe-starter-kit/assets/133137665/15b359ed-faf6-49dc-a3ea-dabe10b827b5)

**Comment by Jenefer-Monroe** [comment]
Can you please restart these flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/77c4fc05-9f4d-487c-b4eb-d80915d2f965)

Sometimes flow caches env var values

**Comment by RyanCloud8888** [comment]
Ok, I'll restart and watch out for the error.  Thanks again Jenefer.  I'll leave this thread open for a few weeks to see if anyone complains.
I will update.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
