### ISSUE TITLE
[CoE Starter Kit - BUG] Documentation Set Up Environment Request Flow Name Changed

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#8228]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello CoE Team,
In the documentation: "[Set up environment request components](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-environment-components)" in the "[Turn on flows](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-environment-components#turn-on-flows)" section it mentions the Flow "Env Request | Cleanup environments" this Flow appears to be renamed in the solution to "Env Request | Cleanup".

### Expected Behavior

The documentation to not contain the Flow "Env Request | Cleanup environments" and have this one instead "Env Request | Cleanup"

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Documentation

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Go [here](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-environment-components#turn-on-flows) 
2. See https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-environment-components#turn-on-flows
3. Go to Cloud Flows in the solution and search for "Env Request | Cleanup environments" and you won't find it.

### Anything else?

Hello Jennifer,
Let me know if you don't want me to keep posting about these documentation changes if you have them already sorted. Don't want to give you extra work by managing these tickets if they are not needed.
Thanks! 

AB#3180

**Comment by Jenefer-Monroe** [comment]
I'll be doing a full review, including looking at flow lists and things like that. But these dont hurt Ill scrub them when I think I'm done :)
