### ISSUE TITLE
[CoE Starter Kit - BUG] Missing some launch information in audit logs

### ISSUE THREAD

**Issue by ecelermi** [microsoft/coe-starter-kit#8230]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello CoE Team,

I’m not sure if this is a bug in the system, but I would like to ask a question regarding an issue we’re encountering with the Audit Log Data in the Power BI Report. We’re attempting to create custom reports using the Audit Log data in the Power BI Report of the CoE Kit, but we’ve noticed that there seems to be missing audit log data in the report.

We’re currently troubleshooting to identify the possible issue with the Audit Logs data in the system, which we suspect could be related to either the connector or the Graph API.
The connector does not show any error and looks like it is working well.

Do you have any suggestions on how we can resolve this issue to ensure we can rely on the audit log data in the CoE?

Thank you in advance for your assistance.

### Expected Behavior

We are expecting to be able to get all relevant data from the Audit Logs connector.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

CoE Power BI Governance Report

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

I am not sure how to reproduce the problem in the system

### Anything else?

-

AB#3182

**Comment by Jenefer-Monroe** [comment]
When you say missing data, can you describe a little better? 
- Do you mean big chunks of time without records where you expect them? 
- Do you mean just there generally seems to be a few missing records throughout the day? 
- Something else?

**Comment by Jenefer-Monroe** [comment]
Sorry I'm still not quite sure I understand. It sounds like you are saying that its missing records throughout the day. 
Have you checked the data source itself to see if they are there? 
Here is where we get this data: https://compliance.microsoft.com/auditlogsearch

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
