### ISSUE TITLE
Problems updating the Core Component

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#8231]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, one of our customers was running the Core Component in 4.17 and I have tried to install the new release. This did not work. Even when I try to import an earlier release (V 4.24) I get an error during the import. It is the same error for both versions. However I was able to install V 4.22, but no higher version.
Is it possible to solve the problem by just deleting the Flow from the Default Solution?

It would be great to get help with this.

Best regards 
Caddy

<img width="982" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/62603605/811ea9d8-199b-443b-9083-f02cd742205f">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Import Fail  CLEANUP HELPER - Check Deleted (Solutions)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3183

**Comment by Jenefer-Monroe** [comment]
Hello. Some folks are hitting this product issue, we are tracking and discussing in this issue. 
https://github.com/microsoft/coe-starter-kit/issues/8130

Please try the suggested workaround if you can : [workaround](https://github.com/microsoft/coe-starter-kit/issues/8130#issuecomment-2101226902). And respond in that bug with findings.

Will close so we track in one place.
