### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by 8HarjotSingh8** [microsoft/coe-starter-kit#8232]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are setting up CoE Power Platform in our Tenant – We are following the Microsoft guide to installing it, and we are having issue when we are updating the Client Secret – Key Vault value:
[https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables]

**Steps to reproduce the issue.** 
1.	We have setup Microsoft Graph setup
2.	The Client Secret stored in Key Vault on Azure
3.	When we updating the Audit Logs – Client Azure Secret environment variables by creating a Key vault reference, we are getting User authentication errors

**We have confirmed the permissions are all setup and the users can access the Key Vault from Portal.Azure.com but just cannot access the the Key Vault as a reference.**
4.	Can you identify any changes that might have taken place when the issue started happening?
5.	Error Message: This variable didn't save properly. User is not authorized to read secrets from '/subscriptions/<<KEY>>/resourceGroups/PowerPlatformKeyVaultsRg/providers/Microsoft.KeyVault/vaults/JuCorePowerPlatformKv/secrets/JUS-CoECommandCenterCS' resource.

![error](https://github.com/microsoft/coe-starter-kit/assets/169282832/b36144b0-daed-4c7a-98d0-6a478b4ce150)
Also Attached a screenshot

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Audit Log 3.15

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

**Steps to reproduce the issue.** 
1.	We have setup Microsoft Graph setup
2.	The Client Secret stored in Key Vault on Azure
3.	When we updating the Audit Logs – Client Azure Secret environment variables by creating a Key vault reference, we are getting User authentication errors

**We have confirmed the permissions are all setup and the users can access the Key Vault from Portal.Azure.com but just cannot access the the Key Vault as a reference.**
4.	Can you identify any changes that might have taken place when the issue started happening?
5.	Error Message: This variable didn't save properly. User is not authorized to read secrets from '/subscriptions/00f86ba8-694f-4db2-8159-08ac9cc9cbcc/resourceGroups/PowerPlatformKeyVaultsRg/providers/Microsoft.KeyVault/vaults/JuCorePowerPlatformKv/secrets/JUS-CoECommandCenterCS' resource.

### Anything else?

Shared above

AB#3186

**Comment by Jenefer-Monroe** [comment]
Hellom. from our testing, the user needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update. Can you please check that?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
