### ISSUE TITLE
[CoE Starter Kit - BUG] Rename of the default environment not reflected in "admin_AppEnvironmentDisplayName" column of the "admin_App" table 

### ISSUE THREAD

**Issue by ocioppcoe** [microsoft/coe-starter-kit#8234]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In December 2023 we [renamed our default environment through the PPAC](https://learn.microsoft.com/en-us/power-platform/admin/edit-properties-environment).

Since then we have found that the "PowerApps Apps" (admin_App) dataverse table has successfully reflected the name change in the "App Environment" (admin_AppEnvironment) column for all apps, but the "App Environment Display Name" (admin_AppEnvironmentDisplayName) column only reflects the change for some apps with other apps still containing the old default environment name in that column.

### Expected Behavior

The "App Environment Display Name" (admin_AppEnvironmentDisplayName) column in the "PowerApps Apps" (admin_App) dataverse table should contain the new default environment name for all apps listed in the table that exist in the default environment. 

ie. The "App Environment Display Name" (admin_AppEnvironmentDisplayName) column should match the "App Environment" (admin_AppEnvironment) column.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

"PowerApps Apps" (admin_App) dataverse table

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. CoE Starter Kit v4.16 was installed and had collected inventory for all Power Apps in our tenant into the "PowerApps Apps" (admin_App) dataverse table.
2. Renamed the default environment.
3. Waited for inventory flows to run successfully.
4. The "App Environment" (admin_AppEnvironment) column was updated successfully for all apps, but the "App Environment Display Name" (admin_AppEnvironmentDisplayName) column does not reflect the new default environment name for all apps in the default environment.
5. Upgraded CoE Starter Kit to v4.23.
6. Waited for inventory flows to run successfully.
7. Issue persists.

AB#3188

**Comment by Jenefer-Monroe** [comment]
Hello. Yes these fields were made years ago before the power fx features made them anything besides a static string. And you cannot change their type unfortunately. 
We have not updated these as so many people rely on them for their own needs. 

To update them you either need to send the objects through inventory or (you can use the "Inventory Me" flag) or you could write a quick flow to do it, or export to Excel Add-in and update there.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
