### ISSUE TITLE
[CoE Starter Kit BYODL - BUG] Data Export classifying SP Forms as Canvas apps

### ISSUE THREAD

**Issue by jayakumarkgds** [microsoft/coe-starter-kit#8235]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Sharepoint Form apps information is not getting updated in the BYODL solution

### Expected Behavior

![image](https://github.com/microsoft/coe-starter-kit/assets/87489417/281027e6-e646-4732-b800-379b2e55a4fb)
Sharepoint form apps should display

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Apps)

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Valiodate the Sharepoint Form Apps Count in PowerBi dashboard

AB#3189

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
