### ISSUE TITLE
[CoE Starter Kit - BUG] "User is not authorized to read secrets from...(Path)" during COE setup wizard

### ISSUE THREAD

**Issue by scottsmithWCG** [microsoft/coe-starter-kit#8237]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

During the COE setup wizard for collect audit log data, I'm receiving an error message when trying to configure environment variable for azure secret key vault for Audit Log - user is not authorized to read secrets from (path).  We have confirmed that the identity does have proper permissions.  

### Expected Behavior

expecting the wizard to complete setup so that we can begin collecting inventory on our power platform environments

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CoE Starter Kit April 2024

### What app or flow are you having the issue with?

Setup Wizard - ARM Features (collect audit log data setup)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. In this environment - Power Platform COE (production environment)
2. Configure environment variables as per setup guide
3. Run COE Setup Wizard - Collect Audit Log Data (says ARM Features at top menu)
4. Steps in wizard: Create an app (successfully created and consented with proper API delegated permissions)
5. Steps in wizard: configure mandatory values: commercial; App reg secret = Azure Key Vault; Configure secret: entered all information from drop downs for azure sub, resource group, key vault and secret name
6. steps in wizard: configure Audit Logs -ClientID 
7. these values save successfully as indicated by wizard
8. Clicking 'Next' to 'Start subscription' is where some problems arise: Network errror using patch function
9. when attempting to circumvent by adding correct environment variable for 'Audit Logs - Client Azure Secret' is where we receive the error "user not authorized to read secrets from (path)", but it has been confirmed that the user does have the correct permissions

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/165808518/1ef3756a-83e4-4733-ad1a-b299abc7b541)

AB#3191

**Comment by Jenefer-Monroe** [comment]
Can you please validate that the azure key vault permissions are correct. 
From our testing, user needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)

**Comment by scottsmithWCG** [comment]
+Vicky; Jonathan

Hi Jenefer,

Thanks for the quick response last week.  I attached results for the KV and RG permissions adjustments according to your guidance, please see attached.  I'm still receiving the same error message though.  I'm wondering if this simply needs time to propagate the permissions on MS end.

Can you please advise?

[A picture containing graphics, screenshot, font, graphic design  Description automatically generated]
Scott Smith
Architect, IT Architecture Services
212 Carnegie Center, Suite 301
Princeton, NJ 08540
m/ +1 412.512.2388
***@***.******@***.***> | wcgclinical.com<https://www.wcgclinical.com/>

**Comment by Jenefer-Monroe** [comment]
Sorry images do not come through if you respond in email. You need to be logged in to GitHub to share them. 
However, yes. I've seen the propagation time for these to be quite long, a few days even once. Sorry about that pain. 
Please do try again later today and tomorrow if needed and let me know.

**Comment by scottsmithWCG** [comment]
Hi, here is the attachment containing the note and screenshot from my cloud architect that you couldn't see from email: 

Hey Scott- 
  It didn’t have the contributor role on the KV.   I added this, and removed some others that didn’t match the below that we tried during troubleshooting.  These are on the KV itself, and not the Resource group the KV resides in.  Please try.

![image](https://github.com/microsoft/coe-starter-kit/assets/165808518/79b08073-dd6b-466e-a4fb-050349f7e2d6)

**Comment by scottsmithWCG** [comment]
Hi, we're still recieving an error when attempting to set the environment variable: 
![image](https://github.com/microsoft/coe-starter-kit/assets/165808518/54bf9386-5255-427f-a150-dda92084b6f3)

And when attempting to configure the mandatory values to start the subscription: 
![image](https://github.com/microsoft/coe-starter-kit/assets/165808518/1c4bbaac-f5aa-4a6e-a11e-d615437d1352)

**Comment by Jenefer-Monroe** [comment]
Please go try to do this from the Product UX directly instead. 
Default solution > Environment variables > Audit Logs - Client Azure Secret
Are you able to read and write the secret from there? 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5d808c21-864e-484a-a5de-426b009297cd)

**Comment by scottsmithWCG** [comment]
Same error message as shown in screenshots:

![image](https://github.com/microsoft/coe-starter-kit/assets/165808518/c027104a-b02d-4180-97e1-e39a976f4438)

![image](https://github.com/microsoft/coe-starter-kit/assets/165808518/e281daa7-1fa2-42f4-9005-acc61c97a8e0)

I'm going to doublecheck the Azure Subscription ID value with the cloud team

**Comment by scottsmithWCG** [comment]
Also wanted to let you know that i've confirmed i'm in the correct target PP environment

**Comment by scottsmithWCG** [comment]
We confirmed that I'm using the correct Azure Sub ID.

**Comment by Jenefer-Monroe** [comment]
I'm afraid what you are experiencing in a product integration issue between Key Vault and Power Platform. 

Another person that hit this found that they had to do the following: Validate that you do not have IP restrictions enabled, or if you do that you have Microsoft's internal outbound IP addresses to the firewall.

**Comment by scottsmithWCG** [comment]
HI, thanks for the continued support on this.  Here's a response to your notes regarding IP restrictions and firewalls:  

The KV is open to the public right now, no FW or IP restrictions.  We would like to lock it down, but lets figure this out first. 

As mentioned – the permissions were on the KV only, can you ask if it needs to be on the Resource group?

**Comment by Jenefer-Monroe** [comment]
I'm afraid I'm not sure, that was just a note from someone in the past after they interacted with product support. Are you able to contact product support? They will likely be able to get you unblocked the fastest.

**Comment by scottsmithWCG** [comment]
Yes I have the original MS support ticket still open.  Is it possible to share this ticket with them?

**Comment by Jenefer-Monroe** [comment]
I dont have access to that system. But you can offer them my name or my PMs (who is MSFT Full Time and so will be easier for them to find) : Grant Archibald

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
