### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow : Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created NOT triggering

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8238]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 

Testing April version to send an adaptive card when a new Teams environment is created. Teams environment got created, however, the Environment Table did not get updated with new Teams Environment resulting the flow not triggering. Please suggest what I am missing on. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Governance solution

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3192

**Comment by Jenefer-Monroe** [comment]
Hello. What type of Admin Role are you using? 
Please note that Dynamics 365 service admin do not collect Teams environments. 

Please see documentation bug https://github.com/microsoft/coe-starter-kit/issues/7764

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b2fc9ed2-044b-48bf-b338-efea9898c66e)

**Comment by ClaudioRWS** [comment]
@PPMini 

I have an observation, because I just worked on customizing this flow, it is triggered, but it takes a while for the inventory to collect the information from the new Teams environment, here with me, I created it and the next day the environment

**Comment by PPMini** [comment]
@ClaudioRWS , you are absolutely right! Today I could see the results :), but its good to know @Jenefer-Monroe that it does not work with D365 Admin role. Thanks a million both. Closing this issue
