### ISSUE TITLE
CoE Starter Kit - Flow Action Details not reporting data in key fields

### ISSUE THREAD

**Issue by mpigott08** [microsoft/coe-starter-kit#8239]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

COE Team,

We are currently trying to gather some flow detail information using the Admin | Sync Template v3 (Flow Action Details). When navigating to the storage location inside of Dataverse, as well as viewing the information in the Power App, we noticed that there is no data being recorded in the following fields: "Flow Action Detail Metadata" and the "Action Information"

<img width="1376" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/37882536/c3deb90f-d690-483c-ac6b-a152ffbefafe">

This is an example of just some of the actions we are looking for more information in.
As we did some digging into the flow it looks like these fields might be set to NULL. Is this intended to be the case?

<img width="470" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/37882536/d42257ed-6f45-44ce-add6-0b5d36f0e646">

This tool has been extremely helpful so far and we are very grateful for any additional input you have on this particular issue :)

### Expected Behavior

We were expecting to see more details about the flow actions specifically in the "Flow Action Detail Metadata" and the "Action Information" fields.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

The steps are really just to let the flow run as it is configured.

AB#3193

**Comment by Jenefer-Monroe** [comment]
Hello. These were legacy from before a product change. To our knowledge there is no information to collect and put in these. 
We left it in there to minimize the change needed in the flow. 

Please do let us know if you think we are missing something. Happy to reconsider.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
