### ISSUE TITLE
[CoE Starter Kit - QUESTION] Test vs Production M365 Groups?

### ISSUE THREAD

**Issue by SteveWinward** [microsoft/coe-starter-kit#8241]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

If we want to setup a Test and Production COE environment, is it recommended to configure both environments with the same M365 groups for admins, makers and users?  Or should the Test and Production environments have separate M365 groups (i.e. "Test Makers Group" and "Prod Makers Group").  I see there is a ProductionEnvironment setting that should be turned off for Test environments, however its not clear if that allows us to use the same M365 groups in test and prod.

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#3202

**Comment by Jenefer-Monroe** [comment]
Hello I dont think we actually have a recommendation here. For my testing and in my own business's tenant, I use the same group for these. 
Happy to hear if others in the community have other practices.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
