### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Security Roles) Error on "List SystemUser Record"

### ISSUE THREAD

**Issue by hanuschkaih** [microsoft/coe-starter-kit#8244]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This error comes up for 2 users in 2 environments.
It seems to me as if disables users should be excluded in an earlier step of the flow.
![image](https://github.com/microsoft/coe-starter-kit/assets/83971745/7adce6e4-f037-4814-aef4-12d36bbe24cb)

### Expected Behavior

No error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Security Roles)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Activate Flow
Receive COE Error notification by email 

AB#3214

**Comment by Jenefer-Monroe** [comment]
Can you please check in Entra if these use cases are disabled there? I ask as Envts also have their own concept of enabled so wondering what your case is.

**Comment by hanuschkaih** [comment]
Hi Jenefer, thanks for your fast reply.

I did not find the users in Entra ID at all (tried to search in many ways, same result for both users)
![image](https://github.com/microsoft/coe-starter-kit/assets/83971745/c2c63ab0-42ec-4a19-8b91-88170b59b0f5)

**Comment by Jenefer-Monroe** [comment]
Thank you for checking that. 
Can you please see if this fixes it for you? 

Put this expression: `isdisabled eq false and fullname eq '@{items('Apply_to_each_still_unknown')}'`

Here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e17ef027-821b-46e5-9589-31cc0ee347ce)

Result you should see:
The flow should pass and these users should be entered as "Unknown" for UserType column.

**Comment by hanuschkaih** [comment]
Hi Jenefer,
I have changed the Filter but the result remains the same
![image](https://github.com/microsoft/coe-starter-kit/assets/83971745/c3dc0b83-309a-4246-a495-1977eb4ef514)

By the way - another flow now fails with a quite similar message - maybe that helps...
![image](https://github.com/microsoft/coe-starter-kit/assets/83971745/e8690b88-21ef-454a-99ca-ad8c2eceff0b)

**Comment by Jenefer-Monroe** [comment]
oh interesting. In that case we arent querying for users at all, I think it might be referencing the user identity running the flow. Which would correlate to the Forbidden message better. 

Can you please : 

1. Confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently? 
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

2. Confirm that the user identity installing and running the flow has the System Administrator Security Role in the environment targetted here: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a79cff7c-b31d-453f-b9b8-9b246e12c17b)

**Comment by hanuschkaih** [comment]
Hi Jenefer,

1) The user has the PP Admin role through Group Assignment - we don't use direct assignments and never had issues with it
![image](https://github.com/microsoft/coe-starter-kit/assets/83971745/c308cef8-9c51-4e68-aae2-e6e3ce8b8704)

2) The user does **not** have the System Administrator role in the target environment.
We are aware of that and there are both organizational and technical reasons for this.
* Organizational: The environment is a dedicated environment for our subsidiary in Hungary and a security group is assigned to the environment where only dedicated Hungarian users may pe part of. The environemnt is managed by the Hungarian colleagues.
* Technical: The security group is managed in local Hungarian AD, then synced to Entra-ID, so the Power Platform Admin could not be selected to be part of the group
* The workaround to manually create an additional Entra ID group that holds both the PP Adnin and the original Security group would both break organizational requirements and security standards as well as standardized technical processes.

**Comment by Jenefer-Monroe** [comment]
Unfortunately you need to have System Admin permission in the environment in order for our kit to be used to gather inventory. 

In the past this requirement was not as obvious to people as the presence in the PPAdmin Role assigned the permission automatically. However this behavior is changing (feature in preview) and so that's why I asked as we will be adding tooling to add the PPAdmin to this role automatically going forward, once the connector is supported in all regions. 

Please see https://github.com/microsoft/coe-starter-kit/issues/8119

**Comment by hanuschkaih** [comment]
OK, I see... so we need to finde a solution here... 
In our case, it's not about the SysAdmin role, it's about the environment access at all, so the PIM workaround might not help...
When "security group" is enabled for an environemnt, is there another option to give the COE admin user access to the environment than adding the user to the security group?
![image](https://github.com/microsoft/coe-starter-kit/assets/83971745/6d9e535b-995a-4dcb-a9fb-0636c5be06b7)

**Comment by Jenefer-Monroe** [comment]
Thanks for the suggestion. I did go test this after your note and found that the technique offered by the product team to escalate privaledge does work even if the user is not in the SG. 
In my testing, it does not add them to the SG but does add them as a System Admin in the envt. 

Please see the workaround solution file in https://github.com/microsoft/coe-starter-kit/issues/8119

**Comment by hanuschkaih** [comment]
Hi Jenefer, I tried out the workaround but the PIM Workaround flow also fails for this environment (and some others) for the same reasons that the user is not part of the security group...
![image](https://github.com/microsoft/coe-starter-kit/assets/83971745/5c13a0e8-bcbc-4dad-a023-d79db0c17f48)

**Comment by Jenefer-Monroe** [comment]
Are you running the flow as someone who is directly and permanently part of the Power Platform Admin Role?

**Comment by hanuschkaih** [comment]
No and yes - the role was assigned through a group, but it's permanent and without PIM.

A Global admin has now changed it to a direct assignment with the following result

  *
The PIM Flow still had 2 errors, but NOT for the respective environment
  *
the Sync Template v4 (Security Role) Flow now ran succesfully when resubmitting the faulty runs

Thanks for solving the issue!

Best regards
  Ihno

**Comment by hanuschkaih** [comment]
Hi Jenefer,
exactly. We changed the CoE Admin user from group assignment (see screenhot above, May 13th 3:33pm) to direct assignement
![image](https://github.com/microsoft/coe-starter-kit/assets/83971745/16af928b-11ce-4751-a05f-6b413684c0d4)

After that, I ran the PIM Workaround flow again 
> it did not run into errors any more for the environment where the CoE Admin user is not member of the security group
After that, I ran the Admin | Sync Template v4 (Security Roles) flow again 
> it terminatesd successfully for the same environment

Best regards 
  Ihno

**Comment by Jenefer-Monroe** [comment]
Really appreciate your response. This is a new feature and so we are still working to understand the limitations it has.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
