### ISSUE TITLE
[CoE Starter Kit - BUG] failed to install CenterofExcellenceCoreComponents_4.31_managed solution

### ISSUE THREAD

**Issue by Chandra1247** [microsoft/coe-starter-kit#8245]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Team,

I am unable to import CenterofExcellenceCoreComponents_4.31_managed solution using upgrade.

"Error message :
Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :The uninstall operation will delete the base layer for the component 'AppModuleRoles' with id '0fcf308f-309c-4407-855f-b240a1664bba'. The operation cannot continue because there are other managed layers over the base layer. You can use the solution layers to find out which other solutions are blocking the operation."

Help me to find AppModuleRoles in the solution and to install the solution.

![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/b5b47f17-19b2-47bf-80e3-1faaf8726572)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Solution

### What method are you using to get inventory and telemetry?

None

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/c376b3ba-751d-49bd-b6ef-88275921285e)

AB#3215

**Comment by ClaudioRWS** [comment]
Hello @Chandra1247 

Use the CoE Admin Command Center to identify the layers created in the flows and remove them, according to the guidance that is already documented

Yesterday the same thing happened to me, but I remembered that I had customized one of the flows.

**Comment by Jenefer-Monroe** [comment]
Thank you! Thats interesting as I've not seen solution layers block upgrade before. 
@Chandra1247 please do try Claudio's recommendation and let us know!

**Comment by Chandra1247** [comment]
Hi @ClaudioRWS @Jenefer-Monroe 

I do not see any unmanaged layers in any of the flows from command center. I did try to upgrade it again from 4.24 to 4.29 and 4.31 i still see the same error.

How do i the find the component which is blocking the upgrade ?
'AppModuleRoles' with id '0fcf308f-309c-4407-855f-b240a1664bba'.

![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/e593f1b4-fe0e-4298-bb83-abb097c541ff)

**Comment by Jenefer-Monroe** [comment]
It looks like that's the product table for Security Roles. So perhaps you've made a change there? I had thought these were mergable but perhaps not. 
Can you please go see if you have unmanaged layers on any of these? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a6de88a1-0b7d-415b-86e3-1023f35afb0d)

**Comment by Chandra1247** [comment]
Hi @Jenefer-Monroe,

I do not see any unmanaged layers in any of these three security roles.

![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/14fd6d4e-0bdf-4e80-8035-4b9bcf70bb1a)

![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/cda252fd-0826-4de5-a3de-573a8c25d244)

![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/56ba5e99-85f3-4c47-af37-92ec03f8a86b)

**Comment by Jenefer-Monroe** [comment]
On further exploration, this is not the table that holds the SR's themselves but the sharing relationship between the SR's and the MDA's. This is a hidden product table that we do not touch so something seems to have broken on your side. 

The only way I know to view this table in particular is to open it in PBI. That will hopefully show you which relationship is bothering you. 

So open PBI > new report > dataverse > select coe envt > appmodeuleroles > Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/78faf6bc-2106-40e9-8a67-435d4bf0683f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d011b4b5-6afe-4a18-b23f-f548f8f9faaa)

Now click Tranform data
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/24c1f9f2-d1e1-4719-ae99-79f47e58c840)

You'll now see the contents of this hidden product table. Look for this GUID its complaining about. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ccb8146b-f180-427d-ac6a-2497a187f37c)

**Comment by Chandra1247** [comment]
Hi @Jenefer-Monroe,

I could not find this GUID "0fcf308f-309c-4407-855f-b240a1664bba" in the appmoduleroles table. I also tried to find it in the solution dependencies but it is difficult to navigate through each dependencies. 

Any other ways to find what is causing this issue ?

[Appmoduleroles.csv](https://github.com/microsoft/coe-starter-kit/files/15291014/Appmoduleroles.csv)

**Comment by Jenefer-Monroe** [comment]
I'm really not sure. Sorry I'm afraid you may need to contact product support. None of our apps are listed as shared in there, and we dont touch that table at all.

**Comment by Chandra1247** [comment]
I was able to trace the ID with the product support team and understood it is Admin View - Development app which has a managed customization from another managed solutions "(Center of Excellence - Customizations)". 

Is it not possible to upgrade of the solution with another managed layer on top of "Admin View - Development" app ?
 
![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/6eb7cc33-2b47-44d3-a4fd-77dd4006b152)

"solutionid": "ac8913f8-a439-4a47-bf06-01f88f3bc69b", (Center of Excellence - Customizations)
Appmoduleid- "74cc7ccb-bf29-ed11-9db2-0022480e5474" - Admin View - Development

![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/d3557305-0345-4c5f-9ad3-9b42e9605437)

**Comment by Jenefer-Monroe** [comment]
I have personalized the Power Platform Admin View MDA, and I've also customized custom pages, in my own tenant and am able to upgrade, so yes it should be expected that you can upgrade with changes. 

This app ("Admin View - Development") is not one of the apps in the kit. It appears to be part of your customizations solution. I would suggest you continue to pursue with support as there appears to be something wrong with their upgrade code. 

For more information, in case I can help. 
Is "Admin View - Development" your own MDA? Does it utilize custom pages from the Core components?

**Comment by Chandra1247** [comment]
@Jenefer-Monroe  
"Admin View - Development" in my case it is Power Platform Admin View. 
I was able to upgrade the solution after removing system administrator role which was assigned to user in the app share.
![image](https://github.com/microsoft/coe-starter-kit/assets/164719064/59e33acc-c0a5-4bf8-bc0c-a62028d91c93)

**Comment by Jenefer-Monroe** [comment]
I'm glad you were able to upgrade. Perhaps there is something about the name being changed and the way they do the relationships. 
What a fantastic mystery though! Thanks for persevearing

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by redleo85** [comment]
Hi @Chandra1247,
we have the same issue, but with the System Customizer role. Could you please describe in more detail what you did to get rid of the error? I understand you somehow "unshared" the System Administrator role from the app/user. How exactly did you do this?
