### ISSUE TITLE
[CoE Starter Kit - BUG]  failed to install CenterofExcellenceAuditComponents_3.21_managed solution

### ISSUE THREAD

**Issue by Titoleto** [microsoft/coe-starter-kit#8246]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Once version 3.21 was installed (supposedly it finished correctly), I got an error when it started to uninstall the version we had before (3.15).

![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/ed08fc8e-17b6-4ac9-b92f-06ed16b5a6bf)

![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/544e76ae-3447-4056-90e7-6c95d7f39ded)

This is the log in solution history
_Solution dependencies exist, cannot uninstall. DependencyCount : 3

RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoEGovDataverseLegacy, Id: 9bf172b5-087f-47fc-b65b-241bd84e6bd2, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Get Teams From Environment, Id: 76de489d-ab0e-ee11-8f6d-000d3aaa0519, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published
RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoEGovDataverseLegacy, Id: 9bf172b5-087f-47fc-b65b-241bd84e6bd2, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Create Team and Assign Roles, Id: 4568aa18-520f-ee11-8f6d-000d3aaa0c0a, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published_

When I press in solution layers
![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/abd83eb7-d9c0-4ad5-802c-01f46f4fba25)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.21

### What app or flow are you having the issue with?

Installing solution

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3216

**Comment by ClaudioRWS** [comment]
hi @Titoleto 

Have you ever done this procedure before? to remove the layers?

![image](https://github.com/microsoft/coe-starter-kit/assets/94450591/57de0fd7-4e25-4809-95e7-6e799910fb36)

**Comment by Jenefer-Monroe** [comment]
It sounds like you've taken a dependency on one of our connectors in a custom flow. And we've deleted that reference. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0b5b3326-1f64-43af-a61f-cbaac68b2177)

Please go to the default solution and find that connection reference and see what dependencies exist.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a8b9b841-93fd-4b16-b377-dab6d8c68940)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a9280e7a-2345-42f0-805c-20bc9613345b)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
