### ISSUE TITLE
[CoE Starter Kit - QUESTION] April 2024 CoE Upgrade. Previous old Core and Audit solution could not uninstall automatically. 

### ISSUE THREAD

**Issue by MgNa-H2O** [microsoft/coe-starter-kit#8248]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We usually upgrade CoE Starter Kit in a monthly basic and the old solutions always uninstalled after they are install the new version successfully. 

However, after importing the new version of the Core solution (4.31 version) and Audit solution (3.21 version) successfully, i noticed that the old solution did not uninstall automatically(Please refer to the screenshot). Consequently, all the CoE apps still display latest modification data as 4 weeks ago, How can I uninstall the old version solutions?

Here is the screenshot ( PS: I removed the publisher info for security reason in the screenshot )

![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/0258d0f3-469a-460a-bd45-4f84a2fae786)
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/8ef72c86-c153-44d8-ab96-dc66bd8d1e68)
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/109c83a0-76b1-4d48-ba0a-cfcc1729f1dd)

Would you please help to advise how we can uninstall the old version so we can run the May's CoE solution?

Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What method are you using to get inventory and telemetry?

None

AB#3218

**Comment by MgNa-H2O** [comment]
Thank you for your comment. 
If I look at the managed solution view ( Please view below), both versions for the Core and Audit solution are update to date (4.31 and 3.21) but the Create column is 4 weeks ago, which is not update properly.

![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/a4d00190-eebc-45dd-8e0b-cf55776fd54a)

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by MgNa-H2O** [comment]
Hi @Jenefer-Monroe , thanks for your suggestion, please look at the screenshot of our current solutions and help to advise how we can uninstall the old version, thank you!

![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/de55536a-a2ef-4666-96bd-12c7984061ab)

**Comment by Jenefer-Monroe** [comment]
Can you please share the screenshot the screenshot again, this time please show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by MgNa-H2O** [comment]
@Jenefer-Monroe Thanks for your feedback. We also imported the Core solution successfully twice, but the older version did not uninstall/removed at all. Please see my updated screenshots with more solutions info for your reference, much appreciated!
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/edbbff18-2e2c-46c8-bd62-2a81f3ff6322)
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/8d118cf7-546c-4716-9425-15fccab8f7c9)

**Comment by Jenefer-Monroe** [comment]
sorry im still not seeing both instances of Core here, nor the name column. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/feab3c1e-7b18-4d2f-ac9f-c0d19c8f637e)

Is 4.31 named with _upgrade?

**Comment by Jenefer-Monroe** [comment]
It looks like not, it looks like the old version successfully uninstalled. 
So the only question you have now is why the Created field did not update correct?

**Comment by MgNa-H2O** [comment]
Hi Jenefer.

Yes my question is the created field did not update and previous Core solution 4.29 did not uninstall.

The version 4.31 is good, but if you look at the create date it shows a month ago which is not match the Core version 4.31. 
What is more, if you look at the May's history screenshot, it only shows import Core solution successfully, but not show uninstall previous Core version 4.29.

Thank you so much for your time.

**Comment by Jenefer-Monroe** [comment]
Gotcha. I'm not sure about that. I do usually see the created update when you upgrade. And I did this time too. I'm afraid that is a product feature to upgrade that date though so if there is a bug there, then product support would need to assist. 

Happy to leave open to see if others in the community have an idea of what might have happened as well.

**Comment by MgNa-H2O** [comment]
Thank you so much for your help. We have to hold on the April release due to this bug.  If that possible you please help to move this issue to the product feature team? @Jenefer-Monroe

**Comment by Jenefer-Monroe** [comment]
Sorry I am not able to transfer this to product team. This would be something you need to contact product support about.

**Comment by MgNa-H2O** [comment]
Ok, thank you so much for your help @Jenefer-Monroe

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
