### ISSUE TITLE
[CoE Starter Kit - QUESTION] Remove Core

### ISSUE THREAD

**Issue by johnmsaxton** [microsoft/coe-starter-kit#8252]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am trying to remove the COE from my main environment and install it in its own environment. I cannot remove Core because it looks there are circular dependencies. When I attempt to remove Center of Excellence - Core Components v4.8, it tells me I cannot remove it because it has the following list of dependencies. 

Power Platform Dashboard
PowerApps App
Dataverse Tables
PowerApps App
admin_5Foffice-20365-20management-20api

When I attempt to remove these dependencies so I can remove the solution, I get an error telling me they cannot be removed because they depend on the solution. 

How do I get past this seemingly circular reference? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

The entire solution

### What method are you using to get inventory and telemetry?

None

AB#3223

**Comment by Jenefer-Monroe** [comment]
It sounds like you have the audit logs solution installed in the environment which has been deprecated. 

Can you please confirm? 
Are you in your default envt now?

**Comment by johnmsaxton** [comment]
Hi Jenifer.

I have the entire COE installed in an environment I created. COE is not installed in the Default Environment. Environment, of course, has Dataverse.

I was able to remove the Audit Solution, but am stuck on the Core Solution.

Best Regards,

John Saxton
________________________________

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by johnmsaxton** [comment]
Sorry I was in PTO


Best Regards,

John Saxton
________________________________
