### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION I get numerous emails that I'm added as Co-owner to a flow

### ISSUE THREAD

**Issue by Roelof-BAM** [microsoft/coe-starter-kit#8255]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I get numerous email to the account with which I have set up Center of Excellence - Core Components. It states that I was added as coowner. I think this is scary. Why is this done and what flow does this and is it possible to stop this? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3226

**Comment by Jenefer-Monroe** [comment]
This happens during the execution of the following flow: **_Admin | Sync Template v3 (Flow Action Details)_**
When a flow contains certain connections (like http connections) we cannot gather some details, like the authentication pattern or the referenced http host, without calling the **_Get Flow_** action as these details are not returned in the **_Get Flow as Admin_** call. 
As a result, we add the identity running the flow, fetch the needed details, and then reset the permissions 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1556f9bb-4ff3-4d77-8479-26431b9d4358)
Unfortunately there is no option to do this without the mail getting sent. 
So if you want to gather the information like the details about flow actions this is just some noise you will need to deal with, perhaps with exchange rules. 
Hope that makes sense.

**Comment by Roelof-BAM** [comment]
thank you, this makes sens
