### ISSUE TITLE
[CoE Starter Kit - BUG]  ImportAsHolding failed with exception :Cannot delete Primary UI Attribute: admin_name from Entity: admin_TenantSecurityRoles

### ISSUE THREAD

**Issue by orauch-a** [microsoft/coe-starter-kit#8257]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I upgrade the core component version (4.22 to 4.31), we get the following error message :
 ImportAsHolding failed with exception :Cannot delete Primary UI Attribute: admin_name from Entity: admin_TenantSecurityRoles

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

upgrade

### What method are you using to get inventory and telemetry?

None

AB#3229

**Comment by Jenefer-Monroe** [comment]
Tenant Security Roles is a new table for you, did not exist in Jan 2024 version of the kit. So it doesn't make sense that its trying to delete something there. 

Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by orauch-a** [comment]
My screenshot
![image](https://github.com/microsoft/coe-starter-kit/assets/34766578/1c09a7bc-7b87-409d-854a-91cc83e25067)

**Comment by orauch-a** [comment]
History page : 
![image](https://github.com/microsoft/coe-starter-kit/assets/34766578/5417981f-eb63-47ca-b0fb-852d4baf9b41)

First error :
![image](https://github.com/microsoft/coe-starter-kit/assets/34766578/4abdb1a7-7d9a-4238-8255-7449e56ce42b)
Solved by your workarround : https://github.com/microsoft/coe-starter-kit/issues/8130 

Second error :
![image](https://github.com/microsoft/coe-starter-kit/assets/34766578/b63d838f-5a98-4761-acf4-8a665bec6a68)

**Comment by Jenefer-Monroe** [comment]
OK it could be that your language has a different way of naming default columns. 
Per our [limitatons doc]( https://learn.microsoft.com/power-platform/guidance/coe/limitations#supported-languages), the CoE Starter Kit solutions are not localized, and only support English. Add the English language pack to your environment to make sure all apps and flows work. More information: [Regional and language options for your environment](https://learn.microsoft.com/en-us/power-platform/admin/enable-languages)
![image](https://user-images.githubusercontent.com/89584709/224966722-dd5d48e7-780d-46cb-b6ae-507318f03ad2.png)

**Comment by orauch-a** [comment]
This environment use english language :
![image](https://github.com/microsoft/coe-starter-kit/assets/34766578/40cc9414-cc2d-4ffa-9630-1425c2607323)

**Comment by Jenefer-Monroe** [comment]
The screenshots and error messages are showing in non-English

**Comment by hbazerbashi** [comment]
Hi,

Here are the solutions in the environment:
![image](https://github.com/microsoft/coe-starter-kit/assets/18416556/7f51ba5a-f32d-4259-bfe0-52f1223e8314)

History:
![image](https://github.com/microsoft/coe-starter-kit/assets/18416556/c806803f-68ba-4737-a9c7-12f727836d80)

First Error:
![image](https://github.com/microsoft/coe-starter-kit/assets/18416556/a5225fcd-761c-46ff-9f5a-09ddc1780ee9)

I already have English when checking the language option in the environment:
![image](https://github.com/microsoft/coe-starter-kit/assets/18416556/f3ada0c4-677f-42dd-9ce6-d79cf8172401)

**Comment by Jenefer-Monroe** [comment]
ok great. Have you tried again since changing the language?

**Comment by hbazerbashi** [comment]
I haven't changed the language, I think it was always there, but I did try again moments ago 
![image](https://github.com/microsoft/coe-starter-kit/assets/18416556/d84ee6ee-304c-48df-ad07-57736a41b4a0)

It is still erroring out. Thank you for your awesome and quick responses. Let me know if you want me to provide more info or even open a live session :)

**Comment by Jenefer-Monroe** [comment]
Sorry we are not staffed to meet with our GitHub users. It's just me doing this support type work for all 11k installs, along with my feature work.

So I'm not sure what to say here. The table is a new table here so there is nothing to delete.

The fact that your UX used to show in French(?) I think it still the needed clue here but now I dont understand your language state. 
Please go see if you have that table present in the environment:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1186da79-2ef6-46f7-805a-97695ab05740)

And if so

**Comment by hbazerbashi** [comment]
I don't see the Tenant table
![image](https://github.com/microsoft/coe-starter-kit/assets/18416556/89e2c482-95a6-4b3a-abe9-6083c049d286)

**Comment by Jenefer-Monroe** [comment]
OK that is expected as it did not yet exist in 4.22. But then why would it complain that it cant delete it when its trying to install it? Mystery. 

Let's look in another table. Please go to the AIBuilderModel table > columns > search for Name
And show me what you see
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/20432e04-30d4-4ea9-803b-0f4722dd2ba0)

**Comment by hbazerbashi** [comment]
Here you go:
![image](https://github.com/microsoft/coe-starter-kit/assets/18416556/8e06fcd9-3532-4b45-937d-6b643eb200a8)

**Comment by Jenefer-Monroe** [comment]
OK I'm afraid I don't know how to help. The product is complaining it cannot delete a column that should not be deleted. 
I think you may need to reach out to product support or, if you are only using us from inventory, just delete core and try again from a clean envt.

**Comment by hbazerbashi** [comment]
Do you think it is safe to try updating our Test Environment and Production afterwards?

**Comment by orauch-a** [comment]
I tried to update the CoE Starter kit from version 4.22 to 4.29 and I get the same error message.
I think it's related to my first attempt to update from version 4.22 to 4.31.
During this first attempt I got the error described https://github.com/microsoft/coe-starter-kit/issues/8130 and I think this attempt left traces.
I'm going to try to reset the environment, but I'm going to lose all the Starter Kit data history... :(

This is a little scary regarding the developments of the Power Platform.
We wonder if the product group controls and tests before delivering...
I do not think so.

**Comment by Jenefer-Monroe** [comment]
Perhaps if you try an overwrite instead before you reset. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b3222c59-7251-4950-a02b-6524a7bc54d7)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7f07b348-fbe8-4281-a8f7-36d6b6b6d474)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2e97f4ab-6fc3-4a1f-8e5b-0531150b873c)

**Comment by orauch-a** [comment]
Thanks a lot Jenefer.
I will try this and I get back to you

**Comment by orauch-a** [comment]
Thank you, thank you and thank you very much Jenefer !
It seems to have worked !
![image](https://github.com/microsoft/coe-starter-kit/assets/34766578/7da6d85f-778b-4c07-9a74-3eef15c94637)
I'm going to do some tests next week to get some feedback.
This bug is still very strange !

**Comment by hbazerbashi** [comment]
> It seems to have worked !

Nice. Did it keep the customization thought?
I'm afraid I face this in Test/Prod too and we lose customizations.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by hbazerbashi** [comment]
Hi, I just wanted to give an update. I was going to test out the Overwrite option, but I thought to give it one last try, and what do you know, it worked! I haven't made any change from my side except opening a ticket with Microsoft Support which is still not assigned to the proper team as the last update I got.
![image](https://github.com/microsoft/coe-starter-kit/assets/18416556/817264c2-fe95-45ad-b65a-111e0d6b8273)
