### ISSUE TITLE
[CoE Starter Kit - QUESTION] Correlation between usage and last launched

### ISSUE THREAD

**Issue by StevensonUK** [microsoft/coe-starter-kit#8259]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are noticing a difference in dates between the usage tab and the last launched columns - for example 

App last launched on says 2/26/2024
usage last creation time shows 2/13/2024

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3231

**Comment by Jenefer-Monroe** [comment]
Sorry can you please share a screenshot of where you are seeing these two numbers?

**Comment by StevensonUK** [comment]
> Sorry can you please share a screenshot of where you are seeing these two numbers?

Here are the screenshots
![Screenshot 2024-05-13 at 16 53 34](https://github.com/microsoft/coe-starter-kit/assets/169688792/f8bf99d7-d222-4f16-95bb-39b519a43927)
![Screenshot 2024-05-13 at 16 53 09](https://github.com/microsoft/coe-starter-kit/assets/169688792/569bd6b2-9803-45a5-b30b-54ca582f3b75)
![Screenshot 2024-05-13 at 16 52 45](https://github.com/microsoft/coe-starter-kit/assets/169688792/2e3fbb33-14e7-4d66-a1a1-6c3f5cf778ec)

**Comment by StevensonUK** [comment]
I can only see one of the flows (Sync Audit Logs) in CoE, which is running,  the other (Update Data) does not show - please see attached screenshots

<img width="1518" alt="Screenshot 2024-05-13 at 17 51 17" src="https://github.com/microsoft/coe-starter-kit/assets/169688792/985c5a8a-e023-4bb8-b03b-8c2cf26691a4">
<img width="977" alt="Screenshot 2024-05-13 at 17 48 04" src="https://github.com/microsoft/coe-starter-kit/assets/169688792/e9ca689b-c9e6-46eb-a582-9a0a25ca89e0">

**Comment by StevensonUK** [comment]
Found it, it was turned off. I have turned the flow on, will update tomorrow if it has run successfully, and resolved the issue. Thank you

**Comment by Jenefer-Monroe** [comment]
wonderful! sorry for the confusion.

**Comment by Jenefer-Monroe** [comment]
Note that it will not go back and fix this field for records unless they get a new launch read.

**Comment by StevensonUK** [comment]
That has worked, I see updated launch dates, thank you for your help with this.

**Comment by Jenefer-Monroe** [comment]
Hello. I have also created a one-off flow to run which will go back and fix up app information for the ones you missed while the flow was off. 

### Import and Turn On the flow into CoE Environment
Go to https://make.powerautomate.com/ > select your CoE Environment > My flows > Import > Import Package (Legacy)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e2a7c2e7-1e63-4786-a097-b96c481ec51b)

Upload the following flow: 
[Fixupmissedauditlogentries_20240514131140.zip](https://github.com/microsoft/coe-starter-kit/files/15308849/Fixupmissedauditlogentries_20240514131140.zip)

Create the connection and Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/918baa95-1023-431e-a789-757ba832bd11)

When done click Open Flow to view and then back to see details and turn on.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f73573f1-e52b-496e-bdd4-acad4fce7df7)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a2acd671-7c52-4722-882e-9d8a23a52043)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed3f47f0-8c87-4b98-9713-1bfed6a4272b)

### Run the flow
Click Run enter the number of days back you need to go
For example if you missed 3 months of data you would put in 90 (for 90 days)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/74c77b1b-70aa-4f8f-8dcd-a6fdbb4bc4c9)

Flow will turn off your audit logs temporarily while it does this processing. Get everything fixed, and then turn them back on.

**Comment by StevensonUK** [comment]
Amazing, thank you
