### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by S0URCEC0D3** [microsoft/coe-starter-kit#8260]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is the CoE starter kit able to retrieve the following for Power Automate flow? 

- Flow Sessions
- Actions
- Unique users
- Last Launched

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin 

### What method are you using to get inventory and telemetry?

None

AB#3232

**Comment by Jenefer-Monroe** [comment]
Dupe to https://github.com/microsoft/coe-starter-kit/issues/8261
