### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by S0URCEC0D3** [microsoft/coe-starter-kit#8261]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is the CoE starter kit able to retrieve the following for Power Automate flow? 

- Flow Sessions
- Actions
- Unique users
- Last Launched

I'm not sure which flow is supposed to provide this information if it's capturing it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3233

**Comment by S0URCEC0D3** [comment]
Thank you, Jenefer. Do you know if this will be available in the coming releases?

**Comment by Jenefer-Monroe** [comment]
We do plan to show "last run" once that information is available from the product for us to consume. 
But we do not plan to collect all the sessions for a flow. We will have to see how that data surfaces to us so that we can determine how to collect efficiently.

**Comment by S0URCEC0D3** [comment]
Ok thanks for the update and the assistance.
