### ISSUE TITLE
[CoE Starter Kit - QUESTION] Create a DLP policy draft from scratch

### ISSUE THREAD

**Issue by rarroyo111** [microsoft/coe-starter-kit#8264]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How come we cannot _create_ draft DLP policies in CoE?  The only way I have been able to save a draft is from an Applied Policy.   

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What method are you using to get inventory and telemetry?

None

AB#3235

**Comment by Jenefer-Monroe** [comment]
Hello. The app is built around that presumption, for better or worse. 
We could put this on the backlog as I agree ideally we wouldn't have done that. But I don't expect it to be funded soon due to competing priorities

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
