### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Update Policy

### ISSUE THREAD

**Issue by rarroyo111** [microsoft/coe-starter-kit#8265]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After editing a draft policy, I select Update Policy and get this error: 

PowerPlatformforAdmins.UpdatePolicyV2 failed: { "error": { "code": "ApiPolicyNotFound", "message": "The API policy 'Template' could not be found in the tenant 'my-tenant-guid'.", "detailUrlType": "NotSpecified" } }

### Expected Behavior

I expected the draft policy to become an applied policy

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

DLP Impact Analysis

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Edit a draft policy.  Select Update policy button at the end.

AB#3236

**Comment by Jenefer-Monroe** [comment]
To area owner to investigate.
