### ISSUE TITLE
[CoE Starter Kit - BUG] 'Center of Excellence - Core Components' ' Admin | Capacity Alerts ' flow doesn't gives any information 

### ISSUE THREAD

**Issue by krishnasubhashb** [microsoft/coe-starter-kit#8271]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Recently we notied that Admin | Capacity Alerts doesn't gives any information even the enviornment crossed the approved capacity. Please find the attachment.

I'm not sure about the depedancy flows anything to check from my end. Please advise on this issue.

![Admin - Capacity Alerts](https://github.com/microsoft/coe-starter-kit/assets/136664183/83cf8dbf-7bd0-4553-9773-b15e53fa2ad3)
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4,24

### What app or flow are you having the issue with?

Admin | Capacity Alerts

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Just run the Admin | Capacity Alerts flow. Don't get enviornments under list enviornments action.

AB#3244

**Comment by Jenefer-Monroe** [comment]
Have you filled in the approved capacities for some environments? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2e348ab7-e9e1-402d-93f8-383f1ab23aa6)

**Comment by krishnasubhashb** [comment]
yes, i have updated

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of this so I can validate? 
The two criteria are that Approved Capacity not be null and the Environment not be marked deleted.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/903b381e-346d-48cd-91c8-788452c8fa4d)

**Comment by krishnasubhashb** [comment]
Thanks for the update. Here is the screenshot
![image](https://github.com/microsoft/coe-starter-kit/assets/136664183/88a61925-7973-44f8-b194-991a939d2c42)
![Uploading env.png…]()

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
