### ISSUE TITLE
[CoE Starter Kit - QUESTION] App Deep Dive

### ISSUE THREAD

**Issue by gghaleb** [microsoft/coe-starter-kit#8272]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Did you chage the "app deep dive" report in the dashboard, the documentation shows a tree visual that is not here in the latest version, as well as the old "License assessment" report. Thanks

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3245

**Comment by Jenefer-Monroe** [comment]
Hello. Yes the tree visual has been removed. After some feedback we found that the numbers were not reliable. 
I'm not sure what license assessment report you are referencing. Can you share a picture?

**Comment by gghaleb** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/40804402/8e2cc3f6-b533-4a09-8796-c7471b7ea2c0)

something like this

**Comment by Jenefer-Monroe** [comment]
oh I see. I think you must have just had that name for the same tree-view. 
Yes we removed the tree views, they were not reliably returning correct data.

**Comment by gghaleb** [comment]
thanks!
