### ISSUE TITLE
Support for cases where transitive attributions in http call are not supported

### ISSUE THREAD

**Issue by MgNa-H2O** [microsoft/coe-starter-kit#8273]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have a failed flow CLEANUP HELPER - Power Apps User Shared With for all of our environments. Please help to look into it, thank you.

The error message is _"Unable to process template language expressions in action 'Tenant_Has_Guests' inputs at line '0' and column '0': 'The template language expression 'if(equals(length(outputs('Get_Tenant')?['body/value']), 0), false, coalesce(first(outputs('Get_Tenant')?['body/value'])['admin_grouphasguestusers'], false))' cannot be evaluated because property 'admin_grouphasguestusers' doesn't exist, available properties are '@odata.type, @odata.id, @odata.etag, @odata.editLink, admin_powerplatformuserid@odata.type, admin_powerplatformuserid, admin_groupsize@OData.Community.Display.V1.FormattedValue, admin_groupsize'. Please see https://aka.ms/logicexpressions for usage details.'."_

### Expected Behavior

The flow ran without error.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

Here is the screenshot of the error flow.
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/f16f1590-6d27-4c72-933e-86220081e176)

AB#3246

**Comment by Jenefer-Monroe** [comment]
Looks like you don;t have the Tenant user in the list yet. 
Please go run the following flow: **_CLEANUP - Admin | Sync Template v3 (Orphaned Users)_**
That will add the tenant as a user
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/19af85c0-6751-48dc-b52d-d9239c88f80d)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3e2aa603-bc71-4d6e-a32e-ae6d623e944e)

**Comment by MgNa-H2O** [comment]
Hi @Jenefer-Monroe  Thanks for your quick feedback. 
I have checked based on the screenshot you provided, the tenant is already there even without the flow's running. Any idea why the flow _CLEANUP HELPER - Power Apps User Shared With_ still failed?
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/8e439fd6-387f-4b7b-b833-f14d60ecb40d)
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/6624ea2e-f9c4-4757-a12e-58b531ed5eed)

**Comment by Jenefer-Monroe** [comment]
Please do go ahead and run the orphaned user flow. It will also clean up malformed records there as we used to store them a different way.

**Comment by MgNa-H2O** [comment]
Sounds good, we will try it, thank you so much @Jenefer-Monroe

**Comment by MgNa-H2O** [comment]
We ran the flow CLEANUP - Admin | Sync Template v3 (Orphaned Users) but unfortunately received the error as the following screenshot. It seems like the flow can find the group but could not process further. Would you please help to look into it? @Jenefer-Monroe Thank you!
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/df608056-758c-4aff-a46a-4001d72d80e8)
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/4554fa63-8701-4888-a1dd-a7e7c9042081)

**Comment by Jenefer-Monroe** [comment]
Looks like we got past that first issue with the Tenant and are on to something new here. 

What is the error output from this call? Note that the error in yellow is just the first error the flow encountered which was, in this case, a caught error. So you'll need to look at the output of the action itself to see the error at hand. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/44cb15d2-d221-4465-9ee5-d87f869d17ac)

**Comment by MgNa-H2O** [comment]
Hi @Jenefer-Monroe 
This is the output value from this call. It looks like the flow found the group but could not list group member. Please help to look at the following screenshot. Much appreciate it.
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/f8a3fde5-2149-4bf7-9d8d-bc449108d532)
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/58b79530-86be-48f7-b985-4b1a36ac5678)

**Comment by Jenefer-Monroe** [comment]
Do any of the groups return correctly? 
If you just keep clicking next in this loop, do they all fail or just this one?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9f8ab21a-942f-4463-b824-19e4ae597f25)

**Comment by MgNa-H2O** [comment]
If I keep clicking next to this loop, all of the groups(Total 5 groups) are failed with the same output as I showed you to the ListGroupMembersTransitive action.

**Comment by Jenefer-Monroe** [comment]
Can you please tell me, are you a regular commercial tenant? Or are you in one of the sovereign gov type clouds? 

Then also what region your coe envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

**Comment by MgNa-H2O** [comment]
We are the regular commercial Canada tenant. The CoE environment is production environment. 
There is one more insight we got from this flow. When we keep clicking those 5 groups from the loop as you mentioned from previous instructions, we find that  those groups are from our 5 Teams environments, the groups in these Teams environments are not regular security group but the M365 groups. Will this cause the issue? Any thought?

**Comment by Jenefer-Monroe** [comment]
I just did some testing and found both Security and M365 groups to work for me. 
I looked online and it seems like maybe sometimes the accept gets corrupted for users from this. 
Can you try adding this explicitly to the call? 
Accept    text/html, application/json
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7da19414-0883-470e-b27d-9b6dfa3928cb)

**Comment by Jenefer-Monroe** [comment]
I tested around that and it didnt seem, to work. Can you click Show raw input and paste what you see? Obfuscate the GUIDs too

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a50bacbd-734a-4ca2-9b9f-af9013e96fdf)

{
    "host": {
        "connectionReferenceName": "shared_webcontents",
        "operationId": "InvokeHttp"
    },
    "parameters": {
        "request/method": "GET",
        "request/url": "https://graph.microsoft.com/v1.0/groups/aaaaaaaa-aaaa-aaaa-aaaa-19ea6a0b759b/transitivemembers?$select=odata.type, id, userType"
    }
}

**Comment by MgNa-H2O** [comment]
Hi here is the screenshot after I click on the "Show raw input".
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/9e8a1591-5cb6-4d45-abd3-a1ac46c707c4)
{
    "host": {
        "connectionReferenceName": "shared_webcontents",
        "operationId": "InvokeHttp"
    },
    "parameters": {
        "request/method": "GET",
        "request/url": "https://graph.microsoft.com/v1.0/groups/bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb/transitivemembers?$select=odata.type, id, userType",
        "request/headers": {
            "Accept": "text/html,application/json"
        }
    }
}

**Comment by VolkerSteltenkamp** [comment]
Just want to let you know that we had exactly the same error with the CLEANUP HELPER - Power Apps User Shared With flow. After re-runnnig the orphaned user flow the above error is gone for now. Thanks Jennefer for this!
I also would like to state that we don´t have any Teams envs around and having only three groups which are all security groups. Maybe this helps?

**Comment by Jenefer-Monroe** [comment]
I don't think the issue is the group type, but I could be wrong. I created these types and they worked fine. 
Can you import and run the following flow and see if any groups in your tenant can do the requested action? 
[test-GetGroupMembershipTransitive_20240517125957.zip](https://github.com/microsoft/coe-starter-kit/files/15349543/test-GetGroupMembershipTransitive_20240517125957.zip)

We are hoping for these two numbers to be the same, but I'm wondering if your second number will be zero.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3b235376-618b-41b8-8fa4-43c1befcbe0f)


Let me know if you need help importing a flow.

**Comment by VolkerSteltenkamp** [comment]
Yep, you´re right, the numbers are the same here:
![image](https://github.com/microsoft/coe-starter-kit/assets/133634324/bfa5fd0d-4fe9-4371-94da-31d58c409a07)

**Comment by MgNa-H2O** [comment]
Before we run the test solution, we are trying to understand more about the flow _CLEANUP - Admin | Sync Template v3 (Orphaned Users)_
, as we saw from the Power Platform Users table, there are more than 5 groups are list in the CoE Command Center app, but why in the loop to Get Groups action, there are only 5 Teams group showing up? Should be more as we assume. 
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/444f73cb-115a-4e74-befd-380e8a049314)
Any thoughts?

**Comment by Jenefer-Monroe** [comment]
It should return all rows that are set with Type = Group
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f2924ecb-fe3f-40c7-9139-135b07d15eb6)

Do you have other groups in the table that are not marked with Type = Group?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e36a9487-0705-40e9-8213-6af72e6eb505)

**Comment by MgNa-H2O** [comment]
This screenshot shows all the rows with Type =  Group in the table, it matches the record from the flow Get Group action. The table has Type= User, service principal and Tenant. However, _**GroupHasGuestUsers**_ options is off. Is that the cause?
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/99e4d55c-7715-4d1a-991a-7d628d465c09)
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/3734f3a9-db48-4a7b-98b0-10084fd1c4ec)

**Comment by Jenefer-Monroe** [comment]
No GroupHasGuestUsers is something we populate. Its not an option so much as its us recording state. 
So once we get you unblocked you'll know know which groups have Guest users, and therefore which apps are shared with Guest users.

So it looks like we'll have two issues to resolve here.

1. Can you get transitive counts in your tenant (from you running that test flow)
2. What are these 13 blanks for type. 

Lets get through issue 1 then look at issue 2

**Comment by MgNa-H2O** [comment]
Hi @Jenefer-Monroe , we are working on the test flow and will back to you.

**Comment by MgNa-H2O** [comment]
Hi @Jenefer-Monroe sorry for our late reply. I finally ran the test flow, however we could not run it successfully. Here is the error message. Do you have any insight for what is the number of 2486?
![image](https://github.com/microsoft/coe-starter-kit/assets/86013325/0caba42d-4ca3-4e9f-a793-2e11e5a56618)

**Comment by Jenefer-Monroe** [comment]
Sorry I should have added a catch here. Can you please re-import this or make this change locally? 
I knew these failed sometimes, I'm trying to see how often
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/809a1995-a9e4-4271-b4c1-9856232bc46f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1b81694f-fe08-4bef-a023-5cc960f7ada8)

[test-GetGroupMembershipTransitive_20240522210637.zip](https://github.com/microsoft/coe-starter-kit/files/15408751/test-GetGroupMembershipTransitive_20240522210637.zip)

**Comment by Jenefer-Monroe** [comment]
Thank you. I'll work to make the flow not fail for you, I'm trying to do that for the June release. 

But I wont be able to get true count of users in the group, or the presence of guest users so I'll add a warning to the Sync Flow Errors table so that admins are aware they are in this state. 

Can you take this flow (the test one that counts groups) to product support. Hopefully they can tell you why you are unable to use this call. So far you are the only tenant I've seen in this state. Hopefully there is some setting I'm unaware of, or something else the product team can fix up for you quickly.

**Comment by Jenefer-Monroe** [comment]
ok I've updated the flow such that if this call fails, it will get the values from the group connector. Unfortunately as I stated, while this will unblock you and allow you to get the information we used to show, you will not benefit from these changes which let you know if there are guest users with access to apps, or the true count of users an app is shared with. 

As a result I will have it register a failure in the sync flow table so that admins are aware.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed3786d8-fab3-4427-b1c8-754ca62232c6)

Please do let us know what support says about the inability to make this call. As far as I can tell there should be no reason you cannot make the call.

**Comment by MgNa-H2O** [comment]
Sounds good, thank you so much for your help Jenefer, much appreciate it.
