### ISSUE TITLE
[CoE Starter Kit - QUESTION] Nurture Components

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#8274]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

I am trying to turn on the 'Training In A Day | Feedback Reminder'  flow in Nurture Components but getting below error.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/792fa775-35b7-443f-954d-dcebe3f2a765)

When we get Training Feedback form? Do we have any documentation?

Thank you,

### What solution are you experiencing the issue with?

None

### What solution version are you using?

March  2024

### What method are you using to get inventory and telemetry?

None

AB#3247

**Comment by Jenefer-Monroe** [comment]
Hello, here are the instructions to [Set up training in a day components](https://learn.microsoft.com/power-platform/guidance/coe/setup-nurture-components#set-up-training-in-a-day-components) which includes a reference to this environment variable: 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4ae9bdce-0040-4f2e-87cc-8eaf790f95e6)

Alternatively you can use the **_CoE Setup and Upgrade Wizard_** and it will take the env var in for you as well: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7ae1100d-08d3-436f-ab63-95d134eab421)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
