### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Welcome Mail

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#8275]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What are the conditions under which the Welcome email is sent and when is it activated?
If the text is modified, will it revert if the CoE is updated?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024/1

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3248

**Comment by Jenefer-Monroe** [comment]
Hello. We do support a path to customize emails without having to edit the flows themselves. 
Please see [Customize emails](https://learn.microsoft.com/power-platform/guidance/coe/faq#customize-emails)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/36f58da7-2187-448e-bafe-ad9b121e9f19)

**Comment by Jenefer-Monroe** [comment]
The flow that sends the mail is **_Admin | Welcome Email v3_**
It is triggered when new users are added to the Maker table. Which happens when we see them as the owner of an object being inventoried.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ea5932f5-4a72-4536-a035-febd89566b0f)

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
 Are users added to the Maker table when an app or flow is created?

**Comment by Jenefer-Monroe** [comment]
If they are new to the inventory yes. 
So the first time Jon adds any of the objects we inventory (including apps/flows) they are added to the Maker table.
The next time we see an object from Jon they are not touched there.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
