### ISSUE TITLE
[CoE Starter Kit - Flow Last Run ON field on Flows table empty

### ISSUE THREAD

**Issue by astar01** [microsoft/coe-starter-kit#8276]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In My CoE Starter Kit, the Flow Last Run ON field data is empty for all my flows. I have implemented the Audit log, and App Last Launched date is working fine, but flow last run on date is blank.

![image](https://github.com/microsoft/coe-starter-kit/assets/52736218/72fb910c-aa0b-461d-9df3-8b766b7bc121)

This is the flow run statuses from Command Center:

![image](https://github.com/microsoft/coe-starter-kit/assets/52736218/cb437860-dcd8-4c0b-9f89-a10c0ed0cb15)
![image](https://github.com/microsoft/coe-starter-kit/assets/52736218/030fc818-a2e4-4ed2-a5f3-2574d7bae230)
![image](https://github.com/microsoft/coe-starter-kit/assets/52736218/d3a0a889-3ee8-4b46-997e-c3d412b1b21e)
![image](https://github.com/microsoft/coe-starter-kit/assets/52736218/c23d4343-03ce-4ae6-b6a8-8ca46838f8f6)

### Expected Behavior

Flow Last Run ON should show the last run date for the flow.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Not sure, all flows are working fine

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open CoE Starter Kit
2. Go to Flows
3. Check the Flow last Run ON field - it is empty

AB#3249

**Comment by Jenefer-Monroe** [comment]
Hello. This information is not yet available to us for the cloud flow architecture. 

The product team does not write this in a consumable way but its not yet Generally Available. Please see [Store cloud flow execution metadata in Microsoft Dataverse](https://learn.microsoft.com/power-platform/release-plan/2023wave2/power-automate/store-cloud-execution-history-dataverse)

Once this is GA we will be able to fill this column.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Madhumita-Questions** [comment]
Is this fixed for **Flow last run**, i can only see for App last launched on.
