### ISSUE TITLE
[CoE Starter Kit - BUG] Admin view data disappears throughout the day

### ISSUE THREAD

**Issue by mspo5** [microsoft/coe-starter-kit#8277]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, I have installed the Coe starter kit (umanged solution) with data export a while ago and since a couple of months it seems like in the afternoon there is less data in the admin view than in the morning. Always around midday I can just see some data but not all of it and when I look in the morning again it looks fine again. I have installed the last couple of months (since around January/February) always the new unmanged solution and checked issues like
[CoE Starter Kit - BUG] Dataflows not working #7946
https://github.com/microsoft/coe-starter-kit/issues/7848
https://github.com/microsoft/coe-starter-kit/issues/2138
https://github.com/microsoft/coe-starter-kit/issues/8001
https://github.com/microsoft/coe-starter-kit/issues/2674
https://github.com/microsoft/coe-starter-kit/issues/7575
https://github.com/microsoft/coe-starter-kit/issues/7396
https://github.com/microsoft/coe-starter-kit/issues/7412
https://github.com/microsoft/coe-starter-kit/issues/7562

to transform the dataflows as lots of data was missing anyways and got worse in the afternoons again. But nothing works for me. 
I have installed the new core components and set it up with the setup and upgrade wizard --> everything seemed to work and the dataflows run through properly at 4am as well. 
![AdminView_Maker_Morning](https://github.com/microsoft/coe-starter-kit/assets/151022094/d5328a41-1b6d-4b1e-9575-3327b617428c)
![AdminView_Maker_Afternoon](https://github.com/microsoft/coe-starter-kit/assets/151022094/d834feea-550a-4f1b-aa15-381f19c08ff2)

Can you please help me with this issue? 

### Expected Behavior

Constant data in the Admin view

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

dataflows

### What method are you using to get inventory and telemetry?

Data Export

AB#3250

**Comment by Jenefer-Monroe** [comment]
Hello. Might I ask why you installed unmanaged? It makes it difficult for us to know the state you are in as we can't simply check for unmanaged layers to get you back to a known state.

**Comment by mspo5** [comment]
Thanks for the quick reply, we have installed it unmanged as we want to extend the coe starter kit and that for in Dev environment we use the coe starter kit unmanaged files and transfer it through pipelines to prod. 

The last couple of weeks I could see in the Admin view the sum of flows (which seemed correct) but none where shown in the list and other data was missing too. Because of that I checked the byodl dataflow problems (most of them I listed above) and changed all of the transform files to what you recommended. This worked for the afternoon problem so the data seemed stabil but not all of the data was shown - a lot better though.
After the new update data seems fine but just in the morning. 
Could you give me a hint where I could first start searching where the problem is?

**Comment by Jenefer-Monroe** [comment]
Please note that there is a really big schema change coming in this area soon and so we have de-prioritized investment in this space awaiting that work. 

What we are recommending at this time, is that you continue to use the Cloud Flow infrastructure for your day to day work and then when the schema change comes experiment with the Data Export again after we have shipped to utilize it.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
