### ISSUE TITLE
[CoE Starter Kit - QUESTION] Production Power BI Dashboard: Govern Section: Connectors (Usage)

### ISSUE THREAD

**Issue by gghaleb** [microsoft/coe-starter-kit#8278]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

we see nothign related to connector usage in this report:
![image](https://github.com/microsoft/coe-starter-kit/assets/40804402/c9b0f2f7-3a38-4261-ad63-33325e152b1a)

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3251

**Comment by Jenefer-Monroe** [comment]
Hello. Not sure what you are hoping to see here. What we show is the list of Apps and Flows that are filterable by connector.

**Comment by gghaleb** [comment]
got it so it is filtering by the connector
