### ISSUE TITLE
500 error on repo creation

### ISSUE THREAD

**Issue by Nohj101** [microsoft/coe-starter-kit#828]
Testing project creation from the ALM Accelerator for Makers after setting up the COE Starter Kit, and we have an issue on the create repo step. It gives a 500 error, and gives a general error of "Cannot create repo with name ****"

We are using a non-paid git hub org account setup.

{
"statusCode": 500,
"headers": {
"x-ms-workflow-run-id": "08585855019469477994336743357CU53",
"x-ms-correlation-id": "d7190980-78c4-4871-9963-2844111e9f86",
"x-ms-client-tracking-id": "08585855020515451346868756993CU78",
"x-ms-trigger-history-name": "08585855019469477994336743357CU53",
"x-ms-execution-location": "westus",
"x-ms-workflow-system-id": "/locations/westus/scaleunits/prod-109/workflows/2e83030f9f664db6bba1fe7800c25f65",
"x-ms-workflow-id": "2e83030f9f664db6bba1fe7800c25f65",
"x-ms-workflow-version": "08585855072469115110",
"x-ms-workflow-name": "f3e8da8e-f407-a2fa-1662-c5187c99fbe1",
"x-ms-tracking-id": "1f2a83f7-4a2c-4412-b417-4eaef40d0d9f",
"Content-Type": "text/plain; charset=utf-8"
},
"body": "Error Creating Repo with name thistime"
}

wondering if this may have something to do with the admin account we are using for creation.  It is a service account without an email address, so that account doesn't have access to the repo.

![image](https://user-images.githubusercontent.com/60517236/111996931-83032800-8ae8-11eb-8d4e-cc9b14f576c6.png)

**Comment by mikefactorial** [comment]
@zafarabhatti transferring this issue here as we've moved to a new repo. Might this be related to #799? Granting oAuth Access for App.

**Comment by zafarabhatti** [comment]
**@mikefactorial , Hi Mike, oAuth Access is already granted. I think the issues is related to something else. As below you can see the power apps have the permission :**

![image](https://user-images.githubusercontent.com/86948940/125410440-2d1afe80-e3bd-11eb-9912-32976d575d86.png)

**Comment by mikefactorial** [comment]
@zafarabhatti just getting back to this. The CreateRepo flow in  the screenshot above is a child flow. Could probably get more information about the actual error if you look at the failed run of the CreateRepo and add a screenshot and/or specific error text here. 
![image](https://user-images.githubusercontent.com/42348035/129221619-0152e7d0-a474-4ef1-a811-ff23ddf303ae.png)

**Comment by mikefactorial** [comment]
@zafarabhatti closing this issue since we haven't received a response. Feel free to open another issue if more assistance is required
