### ISSUE TITLE
[CoE Starter Kit - BUG] Power Pages inventory not accurate

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8282]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Power Page inventory is not accurate. We have deleted Power Pages from our tenant and our CoE is still showing them as current inventory even though have been deleted for months. We have checked the cleanup flows and they seem to be running fine. 

### Expected Behavior

Power Page inventory data should be accurate. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3256

**Comment by Jenefer-Monroe** [comment]
Hello. This is a known limitation with Power Pages today in that they are not cleaned up from the product tables and not even marked as de-activated, so most of the time we dont know when they've been removed.

This information is finally available in the new Power Platform for Admins V2 connector but it is not yet rolled to all regions.

Once that happens we will rewrite this feature area. 
https://github.com/microsoft/coe-starter-kit/issues/7255
https://github.com/microsoft/coe-starter-kit/issues/8038

**Comment by inquisitive-identity** [comment]
Hey Jenefer,

I'm not sure if I should open a new issue for this, but this **might** be related to what I'm seeing in my tenant...

I deleted a handful of environments and also removed some apps from the Default environment, but even after all the flows running successfully, I still see those show up in the CoE Overview dashboard. :/

I checked the Dataverse tables and those have not been updated for either environments nor apps - the columns "Is Deleted" has not been toggled to yes for any environment or app in those tables...
Not sure if I should wait a little longer though as I only deleted those things yesterday, but the sync flows did seem to run after that.

If required, I can create a separate issue for this, just let me know :)

Thank you in advance for the help! :)

**Comment by Jenefer-Monroe** [comment]
Hello, checking for deleted objects is a long running operation and so runs only weekly. 
Please validate that this flow is running and passing: **_CLEANUP - Admin | Sync Template v4 (Check Deleted)_**
And the next time it runs you should see the inventory updated (modulo power pages which its known issues above)

**Comment by inquisitive-identity** [comment]
Hey Jen,

 Ahhhhh, oh my god, I literally totally forgot about the CleanUp flows..... 
Of course! I knew this, but then it seems like I forgot about it somewhere along the way. :)
 
My apologies to both you and the OP for digressing needlessly in this post... :/

Have a lovely day! 

Best regards,
Stefan

**Comment by Jenefer-Monroe** [comment]
No problem at all. Glad we figured it out :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
