### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Setup and Upgrade Wizard is not in the Core Components solution ?

### ISSUE THREAD

**Issue by MikkelMusen** [microsoft/coe-starter-kit#8287]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The CoE Setup and Upgrade Wizard app is not in the Core Components solution. Is this intentional?

### Expected Behavior

The CoE Setup and Upgrade Wizard should be there so I can run it, like all the guides say I should :)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Downloaded latest version
2. Unzipped it
3. Imported it

AB#3261

**Comment by Jenefer-Monroe** [comment]
It's in there. Can you please share a screenshot of what you are looking at?

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b5c311d7-1005-4bfb-8c00-304046fa67aa)

**Comment by MikkelMusen** [comment]
Hi Jenefer

You're right, I found. Looked under Wizard and Setup and Center. Have the name changed from Center of Exellence to CoE ?
Think my main issue is I used the search field, which cant find anything on those search words 🙂

Thanks a lot for the help


Med venlig hilsen

Mikkel Rønde Jensen

 +45 51519939 | ***@***.******@***.***>­



[cid:4d144a8c-7621-469b-b791-41ed404c79e7]

Købmagergade 11
1150 København K

www.carve.dk<http://www.carve.dk/>



________________________________
Fra: Jenefer Monroe ***@***.***>
Sendt: 16. maj 2024 15:37
Til: microsoft/coe-starter-kit ***@***.***>
Cc: Mikkel Rønde Jensen ***@***.***>; Author ***@***.***>
Emne: Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] CoE Setup and Upgrade Wizard is not in the Core Components solution ? (Issue #8287)


It's in there. Can you please share a screenshot of what you are looking at?

**Comment by Jenefer-Monroe** [comment]
Wonderful news! I'll go ahead and close this out then but please do feel free to reach out with new issues as needed.
