### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Service-WebDevPowerP** [microsoft/coe-starter-kit#8288]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

On running the May update, after importing Core components and then running Center of excellence upgrade Wizard and Running the setup flows I came across an issue:

Initially all 3 flows showed as running:
![image](https://github.com/microsoft/coe-starter-kit/assets/105202791/118f9cf5-3678-4831-bdc1-65819fa27273)

But it didnt run
Admin | Sync Template v3 CoE Solution Metadata

The flow comes up with this error: 
Action 'Update_Metadata_-_Flows' failed:
{
  "error": {
    "code": "0x80041103",
    "message": "'admin_CoESolutionMetadata' entity doesn't contain attribute with Name = 'admin_lastrunstarted' and NameMapping = 'Platform'. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=21174800, MinActiveRowVersion=21174800, MetadataInstanceId=30798001, LastUpdated=2024-05-16 09:34:37.600, OrgId=54548ea4-1ed7-4e5d-a5ab-11a22c83424d"
  }
}

![image](https://github.com/microsoft/coe-starter-kit/assets/105202791/6a4350d3-ba39-45bc-bd46-0d9242ef64f6)

__

### Expected Behavior

For the flow to run 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

 4.31

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Run COE setup and upgrade wizard and try running the flows

AB#3262

**Comment by Jenefer-Monroe** [comment]
This is a field we deprecated sometime last year and finally removed this month. It is not called form this action 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b0d3eeb8-5ead-470f-a4b4-cb50182c28e5)


So you likely have an unmanaged layer on this flow preventing you from receiving updates. Can you please check?

**Comment by Service-WebDevPowerP** [comment]
Hi

Thank you for your reply, I am not sure what you mean that I have an unmanaged layer in this flow? Do you mean from this menu should that flow be listed as having an umanaged layer? If so it just shows as failed, it doesnt list any unmanaged layers 

![image](https://github.com/microsoft/coe-starter-kit/assets/105202791/7c3af8bd-0f44-46c8-8c4d-1b0a76dac70f)

**Comment by Service-WebDevPowerP** [comment]
Hi

This is on our test environment where we are experiencing the issue:

![image](https://github.com/microsoft/coe-starter-kit/assets/105202791/d0306de4-7435-45ed-b49b-ad593569b404)


I have checked and there is no unmanaged layers.

**Comment by Jenefer-Monroe** [comment]
Please open the flow in edit and show me what you see in that failing action. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/188d4bd3-ef8c-447d-800a-f8b404c1cc4d)

**Comment by Jenefer-Monroe** [comment]
ok great, so there is no reference to the column it is complaining about, as expected. 
I dont know what to say, it appears the flow has cached the old action here. Can you try restarting the flow? Sometimes that clears whatever caching issues are at hand.

**Comment by Service-WebDevPowerP** [comment]
Thank you, turning the flow off and back on again worked
