### ISSUE TITLE
[CoE Starter Kit - QUESTION] Missing Dataflows in list

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#8289]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I´m exploring the BYODL feature currently by moving the tst Environment from cloud flows to data export. While configuring the dataflows, I´ve noticed a lot of them are missing in the Dataflows section.

I have confirmed all are there in the managed core solution and also checked the "all Dataflows" section, where also only 2 show up. I have also checked the "Dataflow" table in dataverse and it contains 9 entries as expected. 

Any ideas on how to solve this?

![image](https://github.com/microsoft/coe-starter-kit/assets/109345362/a3637d90-ba7c-4da3-b5f9-9ed647674d0f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What method are you using to get inventory and telemetry?

Data Export

AB#3263

**Comment by Jenefer-Monroe** [comment]
They are probably owned by another identity. Unfortunately these are super easy to find. But if you see them in the table hopefully you can see who owns them, and then use this screen to find them
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1aac3dc6-acdb-4d8f-966c-ae698f03e1f3)

Please do let me know.

**Comment by DominicMeznik** [comment]
They are actually all owned by the same account. I now tried to import the core solution again in the classic interview and choosing "Overwrite customizations". That seems to have fixed it.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
