### ISSUE TITLE
[CoE Starter Kit - BUG] Could not acquire Write lock in time 30000 milliseconds

### ISSUE THREAD

**Issue by bhupendra14** [microsoft/coe-starter-kit#8290]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the latest CoE upgrade, getting this error in **SYNC HELPER - Get Security Role Users** flow.

Action **'Direct_System_User_Access'** failed. Flow error below -

{
"Code":"0x80040216",

"Description":"Could not acquire Write lock in time 30000 milliseconds.
Lock mode: Write. Lock name: UserGroupsCache:fXXXXXXd-4XX4-4XXf-bXX2-4XXXXXXXXXXXX2-8XX7-4XX9-bXXe-edXXXXX44",

"DisplayText":"An error has occurred. Try this action again. If the problem continues, check the Microsoft Dynamics 365 Community for solutions or contact your organization's Microsoft Dynamics 365 Administrator. Finally, you can contact Microsoft Support.",

"Title":"Unexpected Error"}
}

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/8158e765-da8f-476d-837a-ff7f860b203d)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users

### What method are you using to get inventory and telemetry?

None

AB#3264

**Comment by Jenefer-Monroe** [comment]
Is the user running the flow a member of the System Administrator Security Role in the environment that this call is targetting? 
You can find the target envt from the trigger of the run
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d3eff99e-d91c-4131-b657-9d70ef7702a1)

**Comment by bhupendra14** [comment]
@Jenefer-Monroe  FYI

![image](https://github.com/microsoft/coe-starter-kit/assets/35683189/d2e68547-3c6f-4590-9255-57ca7eecc0ef)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
