### ISSUE TITLE
[CoE Starter Kit - BUG] Erro CLEANUP - Admin | Sync Template v4 (Check Deleted)

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#8295]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

Please, there is an error when running the CLEANUP flow - Admin | Sync Template v4 (Check Deleted), displays the error message below, says that the app cannot be deleted as there is a task in progress, but it has been displaying this error for over 1 month as shown in the screenshots below. I tried to delete the applications manually in the dataverse, but it won't let me delete them. Can you guide me on what to do in this case, I think that deleting the row of these 2 apps in the dataverse will solve the problem, however when trying to delete it manually in the dataverse it shows the same error message.

Erro: This entity is currently being deleted as part of an asynchronous cascade delete job. Please wait for the asynchronous job to complete before attempting to delete this entity again. You may look up the status of this job by searching for the following AsyncJobName in the system jobs view. (EntityId: a4556abc-fc7e..., EntityName: admin_App, AsyncJobName: Cascade Delete:[admin_App]-[a4556abc-fc....], AsyncJobId: c551b1b4-f79...., AsyncDeleteOperationId: 6553a11a-c2....)

![Erro CoE](https://github.com/microsoft/coe-starter-kit/assets/129080740/9e9d49db-ae44-499a-9f95-1b912c055fa2)

![Erro CoE2](https://github.com/microsoft/coe-starter-kit/assets/129080740/4e08ba8d-5d3d-4934-b062-3c8df6234e2f)

![Erro CoE3](https://github.com/microsoft/coe-starter-kit/assets/129080740/60b60f71-6595-4a49-b9f3-47570ef653d5)

![Erro CoE versao](https://github.com/microsoft/coe-starter-kit/assets/129080740/defe3e24-a673-492a-84b9-c4449ec0390f)

### Expected Behavior

The CLEANUP Flow - Admin | Sync model v4 (check deleted) should run without errors to run child flows also without errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v4 (Check Deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3268

**Comment by Jenefer-Monroe** [comment]
Oh wow, thats a strange issue! Let's see what type of relationship you have between these tables. 

Please go to PowerApps App > Relationships > App Environment > Edit > Advanced Options. 
Share what you have for these settings.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c4f72e15-a117-4f30-a397-3c78fe592a65)

**Comment by minobrega** [comment]
Follow the data as requested

![Erro CoE 4](https://github.com/microsoft/coe-starter-kit/assets/129080740/78417bea-99ca-4716-9acc-5d0bb72a27be)

**Comment by minobrega** [comment]
But as I said, this error is only happening in these two applications that were deleted, I think if you delete them from the dataverse table it will no longer give this error, but when I try to delete them manually from the dataverse table it shows this error.

![Erro CoE3](https://github.com/microsoft/coe-starter-kit/assets/129080740/f305f7bd-5864-49c9-a94a-af284ffc9817)

**Comment by Jenefer-Monroe** [comment]
Unfortunately it appears you've hit some kind of product bug here. 
We can try a few more things but you may need to contact product support. 

Let's go see about this system job its referencing. 
From the CoE Envt, go to Advanced Settings > Settings > System Jobs
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fa97094e-e2ab-4cc2-8a80-e7a95de87ceb)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8f4e410d-a060-45fd-a258-659ad15dedf7)

From here search by Entity or View, see if you can find the job its referencing.

**Comment by minobrega** [comment]
![Erro CoE5](https://github.com/microsoft/coe-starter-kit/assets/129080740/14192374-65fc-413a-babc-1167ffeac0e9)

![Erro CoE 6](https://github.com/microsoft/coe-starter-kit/assets/129080740/43d2497c-7e7b-4466-aa59-f2f00592cf3f)

**Comment by minobrega** [comment]
Mensagem:  Sql error: Statement conflicted with a constraint. The DELETE statement conflicted with the REFERENCE constraint "admin_AuditLog_AppLookup_admin_App". The conflict occurred in database "db_crmcoresam_20230323_03475413_ef75", table "dbo.admin_AuditLogBase", column 'admin_AppLookup'.
The statement has been terminated. CRM ErrorCode: -2147185375 Sql ErrorCode: -2146232060 Sql Number: 547

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]:  Sql error: Statement conflicted with a constraint. The DELETE statement conflicted with the REFERENCE constraint "admin_AuditLog_AppLookup_admin_App". The conflict occurred in database "db_crmcoresam_20230323_03475413_ef75", table "dbo.admin_AuditLogBase", column 'admin_AppLookup'.
The statement has been terminated. CRM ErrorCode: -2147185375 Sql ErrorCode: -2146232060 Sql Number: 547 (Fault Detail is equal to Exception details: 
ErrorCode: 0x80048D21
Message:  Sql error: Statement conflicted with a constraint. The DELETE statement conflicted with the REFERENCE constraint "admin_AuditLog_AppLookup_admin_App". The conflict occurred in database "db_crmcoresam_20230323_03475413_ef75", table "dbo.admin_AuditLogBase", column 'admin_AppLookup'.
The statement has been terminated. CRM ErrorCode: -2147185375 Sql ErrorCode: -2146232060 Sql Number: 547
TimeStamp: 2023-12-17T07:17:07.0081912Z
--
Exception details: 
ErrorCode: 0x80048D21
Message:  Sql error: Statement conflicted with a constraint. The DELETE statement conflicted with the REFERENCE constraint "admin_AuditLog_AppLookup_admin_App". The conflict occurred in database "db_crmcoresam_20230323_03475413_ef75", table "dbo.admin_AuditLogBase", column 'admin_AppLookup'.
The statement has been terminated. CRM ErrorCode: -2147185375 Sql ErrorCode: -2146232060 Sql Number: 547
TimeStamp: 2023-12-17T07:17:07.0081912Z
--
Exception details: 
ErrorCode: 0x80040216
...).

**Comment by minobrega** [comment]
Jenefer, I did this so I canceled those tasks that were stuck and manually deleted the two applications that the tool was unable to delete from the dataverse, now I put the flow to run again, as soon as I finish I'll let you know if it worked...

![Erro CoE 7](https://github.com/microsoft/coe-starter-kit/assets/129080740/bd7f1d80-6e6c-4f1a-b9b9-4d48028515e3)

![Erro CoE 8](https://github.com/microsoft/coe-starter-kit/assets/129080740/5d168903-3ddd-4d85-b6b0-6bc6eb8d4714)

![ERro CoE 9](https://github.com/microsoft/coe-starter-kit/assets/129080740/1dbe63b1-daa1-4b53-81a0-eabcef164fa8)

**Comment by Jenefer-Monroe** [comment]
Well done investigating! Please do let me know what you find.

**Comment by Jenefer-Monroe** [comment]
Better together! WOOHOO! Have a happy weekend with this off your list :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
