### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power BI Documentation App Detail tab

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#8298]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Good morning CoE Team, 

I hope all is well. Nothing important here, but the documentation for [Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard) I believe needs updating. 

If you look at what the tab name is step 2 it says "App Detail" this, I believe is now called "Manage App Access"? Or I might be wrong. Image also shows the same information. 

As I said, nothing important. Just wanted to make you aware.

Thanks very much.

Garry

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2024

### What app or flow are you having the issue with?

Production_CoEDashboard_202405

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3272

**Comment by Jenefer-Monroe** [comment]
Hello. thanks for posting, we do have this one tracked already to fix with this push: https://github.com/microsoft/coe-starter-kit/issues/7399

I'll go ahead and close as a dupe as a result but do appreciate you helping get this documentation in order!
