### ISSUE TITLE
[ALM Accelerator - BUG]: Stuck on getting solution dependencies - flows are not trigerred

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#8299]
### Describe the issue

Since I am experiencing issues with ALM in Production, I decided to create a personal DEV Tenant  I installed ALM in the default environment because I cannot share the customazuredevops connector in DEV-type environments.

When I open ALM with an account that has the Power Platform Administrator role, it can click on Configure Deployment settings and the configuration appears.

If I log in with a user who has the SR Basic user + ALM Power App access and she clicks on Configure deployment settings, it stays on Getting solution dependencies. I checked some flows that are executed as soon as we click on CDS, for example "GetOrganizationSettings" and "GetSolutionCanvasApps" and I have nothing in the history. If I manually run the flow with this user, the flow executes without any error.

I tested the customazuredevops connector with the user, she gets a 200 code and in any case, I have no error with ALM.

Anyway, it is clear that there is a problem because with a PPF admin account if I click on CDS, I see spinners at the top of the screen, but with my user, I see none.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

March 2024

AB#3273

**Comment by tocri** [comment]
hi, 

I follow all the articles, and this documentation. 

[ALM Accelerator for Power Platform Lab - Setup Demo Tenant.pdf](https://github.com/microsoft/coe-starter-kit/files/15402588/ALM.Accelerator.for.Power.Platform.Lab.-.Setup.Demo.Tenant.pdf)

Pipelines are working for dev users and for me. But i still don't understand why my flows are not trigerred when a dev users clicks on CDS. It works for me and people that have the SR admin role.

What is the minimum SR or Table permisson that i need to setup for my dev that he can use CDS ?

For now, they have the SR basic user and ALM Power APP access. The AAE4PP is shared to them with theses permissions. 

Any help will be very appreciate. It very important..Or can i create a ticket to the support team ?

**Comment by mikefactorial** [comment]
@tocri the Basic User and ALM Power App Access SR should be all they need. You may want to start a monitoring session with the user to see if there are any errors when opening the CDS screen https://learn.microsoft.com/en-us/power-apps/maker/monitor-canvasapps.

**Comment by mike-g-msft** [comment]
@tocri   I believe you are using the wrong @ mention. Thanks  😸

**Comment by tocri** [comment]
OK sorry

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tocri** [comment]
Hi @mikefactorial 

I believe I have identified the problem. I now have a copy of an account where the issue occurs. After several tests, it seems to be related to my AZDO configuration but i'm not certain

I have two profiles: one named DEP SQI associated with the REPO DEV SQI, and another named DEP UA associated with the REPO DEV UA.

After sharing the app with the SR App deployment configuration to my user, and attempting to create a new deployment profile, I encounter this error 

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/16ff9cf2-e32c-49d8-a775-1418ed4f2984)


And in the dropdown, some environnements are missing 

<img width="210" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/dd331d45-7613-42bd-bbba-5cd64c89860e">


What i don't understand, the production SQI environnement is listed. I have the SR basic user and the Acceptation SQI environnement is not list and i have the same SR. It's a nonsense.

**Comment by tocri** [comment]
I think i will become crazy.
If i give the SR Environnement maker to the team that contain my user, the environnment is listed.
If i give the SR basic user the environnement disappear from the dropdown.

Why it doesn't work !! I I compared SR basic from my acceptation that is listed form prod environnment that is listed...no difference. I have copied my profile from production to acceptation with xrm toolbox but no changes.

I'm desesperate

**Comment by tocri** [comment]
Finally, the problem has been solved. After several tries, I had to share an app in the test environment with users who didn't see the environment in ALM. Even with the SR basic user it wasn't enough. This is a strange behavior of the Power Apps for Maker connector. Thank you @mikefactorial  for your help
