### ISSUE TITLE
[CoE Starter Kit] Admin | Audit Logs | Office 365 Management API Subscription - Unauthorized "Content not shown due to security configuration." - Error Message: "The permission set () sent in the request does not include the expected permission."

### ISSUE THREAD

**Issue by JulesCam** [microsoft/coe-starter-kit#8300]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

[CoE Starter Kit] Admin | Audit Logs | Office 365 Management API Subscription - Unauthorized "Content not shown due to security configuration." - Error Message: "The permission set () sent in the request does not include the expected permission."

<img width="313" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/132581331/28f89e73-8a84-4492-9e1f-bdf098d22f67">

What do I need to do to resolve this?

Your help is much appreciated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by petepuu** [comment]
Have you verified that your Entra ID app registration is configured to have **ActivityFeed.Read** Application permissions?

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/992af230-b6ac-4672-842e-3835cdadd934)


https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#create-a-microsoft-entra-app-registration-for-the-office-365-management-api

**Comment by JulesCam** [comment]
Thanks for responding so quickly! Yes I checked but thought I would double check and we have the following permissions

![image](https://github.com/microsoft/coe-starter-kit/assets/132581331/058c52a6-c44d-42af-ad2a-be397da39e22)

Again, much appreciated.

**Comment by petepuu** [comment]
Ok, the Delegated does not work it need to be **Application**

**Comment by JulesCam** [comment]
Ah okay. Did this change at some point or have I simply captured the wrong permissions - which was a while ago. 

I will try this and confirm if this resolves the issue.

Honestly, your help and support is so appreciated and the quick response - so thank you :) I'll come back, let you know.

**Comment by petepuu** [comment]
Yes it changed about a year ago when Audit Log sync was changed to use HTTP action in flow. Before that it used custom connector and Delegated permissions

**Comment by JulesCam** [comment]
Should it be 'Application' rather than 'Delegated' for both App Regs needed for the COE? Assume it is and the documentation seems to reflect that but wanted to double check.

**Comment by JulesCam** [comment]
Ah okay, gotcha! :) Thank you so much for confirming. We'll make the changes then confirm back.

Very much appreciated again!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
