### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by flippedcoin** [microsoft/coe-starter-kit#8301]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have missing names in CoE. Although it is expected because the person names are all company leavers, running a PowerShell script seems to capture the names. 

Here is a sample of the PowerShell script that was used

$currentTime=$(get-date).ToString("yyyyMMddHHmmss");    
$outputFilePath="C:\Users\adm-ilamr\Documents\PowerAppsInventory_24Jan2024 -"+$currentTime+".csv"    
$resultColl=@() 

# Get all the PowerApps  
$apps=Get-AdminPowerApp -Environment Default-ec85c1f0-148f-4d0f-b9f5-bfd62a99ed8c
foreach($app in $apps)  
{  
    $result = New-Object PSObject
    $role= Get-PowerAppRoleAssignment -AppName $app.AppName

    $result | Add-Member -MemberType NoteProperty -name "AppName" -value $app.AppName -Force
    $result | Add-Member -MemberType NoteProperty -name "DisplayName" -value $app.DisplayName -Force
    $result | Add-Member -MemberType NoteProperty -name "AppType" -value $app.Internal.appType -Force
    $result | Add-Member -MemberType NoteProperty -name "Environment" -value $app.EnvironmentName -Force
    $result | Add-Member -MemberType NoteProperty -name "OwnerDisplayName" -value $app.Owner.displayName -Force
    $result | Add-Member -MemberType NoteProperty -name "OwnerEmail" -value $app.Owner.email -Force
    $result | Add-Member -MemberType NoteProperty -Name "CreatedTime" -value $app.CreatedTime -Force
    $result | Add-Member -MemberType NoteProperty -Name "CreatedByDisplayName" -value $app.Internal.properties.createdBy.displayName -Force
    $result | Add-Member -MemberType NoteProperty -Name "CreatedByEmail" -value $app.Internal.properties.createdBy.email -Force
    $result | Add-Member -MemberType NoteProperty -Name "LastModifiedTime" -value $app.LastModifiedTime -Force
    $result | Add-Member -MemberType NoteProperty -Name "LastModifiedByDisplayName" -value $app.Internal.properties.lastModifiedBy.displayName -Force
    $result | Add-Member -MemberType NoteProperty -Name "LastModifiedByEmail" -value $app.Internal.properties.lastModifiedBy.email -Force

    $result | Add-Member -MemberType NoteProperty -name "AppLocation" -value $app.Internal.appLocation -Force
    $result | Add-Member -MemberType NoteProperty -Name "IsAppComponentLibrary" -value $app.Internal.isAppComponentLibrary -Force
    $result | Add-Member -MemberType NoteProperty -name "IsFeaturedApp" -value $app.IsFeaturedApp -Force
    $result | Add-Member -MemberType NoteProperty -name "IsHeroApp" -value $app.IsHeroApp -Force
    $result | Add-Member -MemberType NoteProperty -name "BypassConsent" -value $app.BypassConsent -Force
    $result | Add-Member -MemberType NoteProperty -name "UsesCustomApi" -value $app.Internal.properties.usesCustomApi -Force
    $result | Add-Member -MemberType NoteProperty -name "UsesPremiumApi" -value $app.Internal.properties.usesPremiumApi -Force
    $result | Add-Member -MemberType NoteProperty -name "UsesOnlyGrandfatheredPremiumApis" -value $app.Internal.properties.usesOnlyGrandfatheredPremiumApis -Force
    
    $resultColl += $result
}  

#Export the result Array to CSV file  
$resultColl | Export-Csv $outputFilePath -Encoding UTF8 -NoTypeInformation

### Expected Behavior

I am wondering why is there a discrepancy between the data from CoE vs PowerShell script. I supposed they should be coming from the same source. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin - Sync Template v3

### What method are you using to get inventory and telemetry?

None

AB#3275

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not following. What CoE table are you comparing with?

**Comment by flippedcoin** [comment]
Basically I am comparing it with the Power BI Dashboard. Some of the data there has missing App Owners name. I reckon that this is normal because if the person leave the company, it will cause a void. But what confuses me is that when I am running a PowerShell script to get the all apps created in my default environment, it managed to capture all the owner names even though some of them has left the company. 

I suspect the CoE table responsible for this might be the Maker or perhaps the Audit Log

**Comment by Jenefer-Monroe** [comment]
I see. I'm not sure how the Power Shell grabs the owner, they might reference the environments local user table which does cache users that no longer appear in Entra by default, though this can be cleaned by admins. 

We use the O365 connector to grab owner information and so once they are removed from Entra this is no longer available, at which point we flag them as orphaned. 

If someone leaves the org (and hence Entra) after you capture the inventory their information like name / dept / etc is not lost, they just get flagged as orphan. 

Hope that helps clarify.
