### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION: Using the Setup Wizard for Audit Logs - Are there subscription costs we need to consider?

### ISSUE THREAD

**Issue by JulesCam** [microsoft/coe-starter-kit#8305]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Using the Setup Wizard for Audit Logs and I've been asked if there are any subscription costs we need to consider for the audit logs and the step "start subscription" but I couldn't find anything in the online documentation or in this community. Hope you can help confirm.

Much appreciated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3281

**Comment by petepuu** [comment]
No there isn't any extra costs to use Office 365 Management API but as in any APIs there are limits how many requests we can execute. All organizations get baseline of 2000 requests per minute but that can be more based on the number of O/M365 licenses in the tenant 

See more info about the API from https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference#api-throttling

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
