### ISSUE TITLE
[PBI] Power Pages section shows inconsistent Environment values

### ISSUE THREAD

**Issue by erickovach** [microsoft/coe-starter-kit#8307]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are not seeing all the Power Pages in the CoE.  In the Power Pages section, the Power Pages per Environment lists Environment Names that are not available to choose in the right-hand Filter drop down.  The two lists do not match.
![missing environments](https://github.com/microsoft/coe-starter-kit/assets/28988976/ff8096ce-c6d5-45af-aca5-6b54bc59d0cb)

### Expected Behavior

Expect the CoE to identify all Power Pages in all environments.  Expect the CoE to identify all Environments that have Power Pages.
![missing environments](https://github.com/microsoft/coe-starter-kit/assets/28988976/4eb038db-fd5c-4c89-95bb-1a3c2da094d2)
![missing environments](https://github.com/microsoft/coe-starter-kit/assets/28988976/4eb038db-fd5c-4c89-95bb-1a3c2da094d2)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

none

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Browe to the Power Pages section of the dashboard and notice the inconsistency.

AB#3290

**Comment by Jenefer-Monroe** [comment]
I'm not sure what's happening here but it looks like the environment filter got broken on the entire PBI. 
Thanks for posting will fix up for June release.
In the near term if you delete the filter and re-add it seems to work
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0aa7f300-4749-4318-8da3-6efc1b6a0ee7)

**Comment by Jenefer-Monroe** [comment]
Can you try this out early? It works with the May release of the kit (no new data sources etc)

[Production_CoEDashboard_June2024.zip](https://github.com/microsoft/coe-starter-kit/files/15392809/Production_CoEDashboard_June2024.zip)

**Comment by erickovach** [comment]
Hi Jennifer,

Yes, this worked.  Thank you,

Eric

**Comment by erickovach** [comment]
Hi Jennifer,

The real problem I'm trying to fix is there are Power Pages in Environments that just don't show up in the CoE dashboard.

For example, I see there is a Power Page PRO ERM - pro-erm-pirelli in Environment PRO-TC-IT-PPPM-DEV in the Power Platform Admin view:

***@***.***

But the CoE dashboard sees no Power Pages for that Environment:

***@***.***

The dashboard isn't empty, but it doesn't see everything.

***@***.***

From: Kovach, Eric (HQP)
Sent: Tuesday, May 21, 2024 10:05 AM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [PBI] Power Pages section shows inconsistent Environment values (Issue #8307)

Hi Jennifer,

Yes, this worked.  Thank you,

Eric

**Comment by Jenefer-Monroe** [comment]
Hello again, screenshots do not come through if you respond in email. Can you please post this as a new issue since I already did a fix here thats ready to go. And share the images in the new issue.

**Comment by erickovach** [comment]
Sure, will do.  Thanks
