### ISSUE TITLE
Where to find the value of Environment Variable "CoE System User ID".  I do not want to use "Set Wizard" app.

### ISSUE THREAD

**Issue by PrasannaKumarPenumarthi** [microsoft/coe-starter-kit#8308]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Please let me know where can we find the value of Environment Variable "CoE System User ID". It is not mentioned in documentation. I do not want to use "Set Wizard" app to update my environment variables and flows due to some internal reasons. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Environment Variable "CoE System User ID"

### What method are you using to get inventory and telemetry?

None

AB#3291

**Comment by PrasannaKumarPenumarthi** [comment]
I just wanted to understand the functionality and have an idea on how things were working at backend without automation through some app.Please let me know if you could help me out on the same where to find the CoE system user id environment variable value.

**Comment by Jenefer-Monroe** [comment]
So this is a user that the setup wizard itself creates and then fetches. If you are upgrading an old version of the kit then you will already have this user in your Maker table:

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/99d6ee1e-1cb4-4804-95b8-adb6c379ca24)

Basically there are system owned objects (ex "System" creates the default envt and sample MDAs). But these will have a unique GUID in all envts in the tenant, so this is the GUID we will use to represent SYSTEM user in your inventory.

**Comment by PrasannaKumarPenumarthi** [comment]
Thanks for the information. I had upgraded my coe kit to latest "May 2024" version from old version. Can I use the above "Maker GUID" Value which is present in "Power Platform Admin View" app to update the environment variable "CoE System User ID" manually??

**Comment by Jenefer-Monroe** [comment]
You can, yes.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
