### ISSUE TITLE
[CoE Starter Kit - BUG] Typo in the description for the "Set up the CoE Starter Kit" documentation link

### ISSUE THREAD

**Issue by slodplaadmin** [microsoft/coe-starter-kit#8309]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I go to the CoE Admin Command Center and then to "CoE Support" in the collapsible left-hand menu.

On this page is a "CoE Starter Kit Documentation" section.  One of the linked tiles in that section is to "Set up the CoE Starter Kit".  The description on this tile reads:

`Learn  how to set up the CoE Starter Kit, using eithe the Setup Wizard or manual import.`

The "eithe" should read "either".

File that this error is found in is CenterofExcellenceCoreComponents/SolutionPackage/src/CanvasApps/src/admin_commandcentercoesupportpage_06f77/Src/CommandCenterCoEScreen.fx.yaml, and at the time of this writing the erroneous text is on line 211.

This is in the May 2024 release.

### Expected Behavior

Typo should be corrected.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CoE Admin Command Center - Documentation section

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Go to the CoE Admin Command Center and then to "CoE Support" in the collapsible left-hand menu.

2.  On this page is a "CoE Starter Kit Documentation" section.  One of the linked tiles in that section is to "Set up the CoE Starter Kit".   Note the error.

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/29456842/39d29feb-909d-476c-838b-a66b50778f3a)

AB#3292

**Comment by Jenefer-Monroe** [comment]
thanks for posting, we're doing a little doc pass this month so can fix up while there.
