### ISSUE TITLE
[CoE Starter Kit - Feature]: Governance for Power BI reports

### ISSUE THREAD

**Issue by johnravas** [microsoft/coe-starter-kit#8310]
### Describe the solution you'd like

Has any thought been given to extending the CoE to manage and govern Power BI reports?  We have built our own extension to the CoE to manage Power BI reports and apps.  Right now it's pretty simple.  However, we are looking to extend the functionality to do many of the kinds of things that are done as part of governance.  Before we build, I wanted to check to see if this is in the works for the CoE

AB#3293

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately not. There is an entirely separate CAT team charged with Power BI / Fabric and so they would be the ones to make such an investment.

**Comment by johnravas** [comment]
Thank you.

**Comment by Jenefer-Monroe** [comment]
You bet, sorry I didn't have better news for you. I'll go ahead and close this out then.
