### ISSUE TITLE
[CoE Starter Kit - BUG] PBI - We cannot convert the value null to type Text

### ISSUE THREAD

**Issue by jmukeshkumar** [microsoft/coe-starter-kit#8311]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I checked the bug #7298 and that solution is not working. After installing the core and the governance components of May 2024 version, i tried to upload the PBI by opening the Power BI desktop. When i tried to open the Production COE May 2024 dasboard and click on Refresh after loading, i get the below error

<img width="407" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/142143043/56ff80b5-2558-4bb7-a4cb-8951edb017c7">

### Expected Behavior

The dashboard should load without error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Production_CoEDashboard_May2024

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Upgrade Core to 4.31 version
Open PBIT and attempt a refresh

AB#3298

**Comment by Jenefer-Monroe** [comment]
Are all the error messages the same in the list there? Or are there any that are unique?

**Comment by RandomDept** [comment]
Experiencing the same issues:

<img width="241" alt="Errortypetext" src="https://github.com/microsoft/coe-starter-kit/assets/151495228/8f94249f-43f6-4658-87b2-d16df03d531b">

<img width="743" alt="currentsolutions" src="https://github.com/microsoft/coe-starter-kit/assets/151495228/c83fc97d-212f-40e0-b5ec-df0088c1d0fd">

Using Power BI Desktop 
Version: 2.129.1229.0 64-bit (May 2024)

Trying to open Production_CoEDashboard_May2024.pbit
I have also tried renaming to CorpCoEDashboard_May2024.pbit same issue.

**Comment by Jenefer-Monroe** [comment]
Hello, typically you need to have the version of Core installed match the month of the PBIT file you use. It looks like you have the Feb 2023 version of Core installed so you will need to match with that PBIT file.

**Comment by RandomDept** [comment]
Thank you,

Did you mean Feb 2024? Not sure what version 4.23 corresponds to?

I did upgrade earlier this year and had a few issues. 

https://github.com/microsoft/coe-starter-kit/issues/7680

**Comment by Jenefer-Monroe** [comment]
oops haha yes I meant Feb 2024 :) 
thanks for reading my mind and testing it out !

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
