### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (AI Events) failed because maker not in admin_maker table

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#8312]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,

the Admin | Sync Template v4 (AI Events) is failing because the maker Id is not in the admin_maker table:
In my case this user is a service account, which does not own any apps or flows just connections

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v4 (AI Events)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3299

**Comment by Jenefer-Monroe** [comment]
Hello, this was fixed for the May release. Please see https://github.com/microsoft/coe-starter-kit/issues/8158

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
