### ISSUE TITLE
Several capacities with no environment display name in environment capacity table

### ISSUE THREAD

**Issue by rashibhalla** [microsoft/coe-starter-kit#8315]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Several capacities with no environment display name in environment capacity table due to which power automate flow is failing. Please refer to screenshot for more details. In power Platform admin portal, there are no orphan capacities which are not bound to any environment.
![image (1)](https://github.com/microsoft/coe-starter-kit/assets/170408880/051da0f9-b7a4-4f5a-9858-5ccc35009ac6)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Cloud Flow

### What method are you using to get inventory and telemetry?

None

AB#3302

**Comment by Jenefer-Monroe** [comment]
Not sure how you got into this state, but we do have clean up for it in the following flow. 
Please be sure its turned on, running, and passing

**_CLEANUP - Admin | Sync Template v3 (Delete Bad Data)_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2412ecd2-aa8a-4e72-a520-886a35bb96cf)

**Comment by rashibhalla** [comment]
Hi Thanks for the response. 
Did we delete those entries because the data was incorrect, rather than representing actual capacity?

**Comment by Jenefer-Monroe** [comment]
I dont know how those got into your database. Usually its just the regular clean up. So if an envt gets deleted we have to manually delete its child objects due to the relationship type.
