### ISSUE TITLE
[CoE Starter Kit - QUESTION] Manage App Access not able to embed in Power BI Dashboard report

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8317]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 

Was trying to embed the Manage app access via Power BI Dashboard. I enabled the Power BI visualization setting on my COE environment and I have owner role for that app. But still when I try to embed via App deep dive drill through tab, I always get below 
<img width="758" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/49a00485-9616-44eb-a971-5553316d3587">

Apologies, but the documentation is not at all clear how to do this. Suggest to mention about the Power BI setting as well in the documentation. Also, When you access the manage app tab , its shows some instructions but the instructions just vanishes. Which is again not a good experience. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3319

**Comment by Jenefer-Monroe** [comment]
Hello. What PBI setting are you referencing? We've never had to change settings to get this to work.

**Comment by PPMini** [comment]
Hi Jenefer, 

Found this on web , while trying to trouble shoot and get this working 
<img width="347" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/ee9b8fae-64ff-4433-afb7-d5021171e6b4">

Could see things moving like "fetching your App" and then got the error mentioned above.

Could you please share the steps to get this working? Thanks.

**Comment by Jenefer-Monroe** [comment]
Oh I see, that is the other way around. That setting is for embedding PBI in Power Apps. What we are doing here is the other way around, we are in the embedding Power Apps in PBI. 

So I'm not sure what is wrong as this works for most people. Can you please share a screenshot of where you are stuck?

**Comment by PPMini** [comment]
Thanks a million, hopefully should be able to get through this now. :)

**Comment by PPMini** [comment]
Yes, it worked, thanks again :). Closing this thread.
