### ISSUE TITLE
[CoE Starter Kit - BUG] Power Pages missing from the COE dashboard

### ISSUE THREAD

**Issue by erickovach** [microsoft/coe-starter-kit#8318]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

There are Power Pages in the tenant that do not show up in the CoE Dashboard.

For example, I see there is a Power Page PRO ERM - pro-erm-pirelli in Environment PRO-TC-IT-PPPM-DEV in the Power Platform Admin view:

 
![image](https://github.com/microsoft/coe-starter-kit/assets/28988976/498d355b-23ce-416a-93f1-3d59f75db764)

But the CoE dashboard sees no Power Pages for that Environment:

 
![image](https://github.com/microsoft/coe-starter-kit/assets/28988976/3adeb86d-29dc-44d8-89bc-e056195ab247)

 

### Expected Behavior

Expect to see all Power Pages in the tenant in the CoE Dashboard.  The dashboard isn't empty, but i don't see all the power pages.
![image](https://github.com/microsoft/coe-starter-kit/assets/28988976/ddbf6bcf-a0fd-46f7-9d65-c1e03909dd2d)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

none

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Compare the Power Pages listed in the Power Platform Admin view under resources and compare it to the Power Pages displayed in the CoE dashboard.

AB#3320

**Comment by Jenefer-Monroe** [comment]
OK I think this is the issue: https://github.com/microsoft/coe-starter-kit/issues/8038
The product team changed the way they create / store power pages and we are not able to shift over until the connector is GA. 
Sorry about that. Please monitor **https://github.com/microsoft/coe-starter-kit/issues/8038** for updates as we will work on it once the connector can be used

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team, please monitor with the duplicate
