### ISSUE TITLE
[CoE Starter Kit - BUG] Cannot read properties of null (reading 'colorNeutralBackground1')

### ISSUE THREAD

**Issue by declawson** [microsoft/coe-starter-kit#8319]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Using the Power Platform Admin View if I go into pretty much anything under Monitor (Apps, Flows, Envs ...) I will see a list of the relevant apps, flows, envs ... However, if I select a specific item I get the 'Something went wrong' error with details of:
Cannot read properties of null (reading 'colorNeutralBackground1')
TypeError: Cannot read properties of null (reading 'colorNeutralBackground1') at <URL of my COE env>

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Power Platform Admin View
PowerApps Apps
Select an App

AB#3321

**Comment by Jenefer-Monroe** [comment]
strange. I've never seen this error before. Can you try turning off the New Look feature? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/61c4f3b0-6af6-490e-8cea-848342c4ae2d)

**Comment by declawson** [comment]
Ok, that was fun.

Turned New look off and it worked as expected so turned back on and still working as expected.

Thanks, I never would have thought to turn off/on.



[https://webmail.atcc.org/owa/auth/image001.jpg]
Debbie Clawson
Lead Architect

10801 University Boulevard
Manassas, VA 20110-2209
Tel: (703) 365-2700 ext. 2820
Fax: (703) 365-2701
Email: ***@***.******@***.***>

**Comment by Jenefer-Monroe** [comment]
Thank you for letting me know it worked, honestly I was just guessing. It seems to be some product bug with that new feature. 

A nice success for us today :)

**Comment by Jenefer-Monroe** [comment]
Are we ok to close this one out then?

**Comment by declawson** [comment]
Sure, the workaround is simple enough.

[https://webmail.atcc.org/owa/auth/image001.jpg]
Debbie Clawson
Lead Architect

10801 University Boulevard
Manassas, VA 20110-2209
Tel: (703) 365-2700 ext. 2820
Fax: (703) 365-2701
Email: ***@***.******@***.***>
