### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log Setup - Network error when using an UpdateIf function: The requested operation is invalid.

### ISSUE THREAD

**Issue by phil0074** [microsoft/coe-starter-kit#8321]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Deploying May 2024 release and running the Audit Logs Setup wizard running into the following error at "Start subscription" step:
Network error when using an UpdateIf function: The requested operation is invalid. See attached screenshot.

In addition, I notice two flows related to this process fail:

1. Admin | Audit Logs | Office 365 Management API Subscription     Error: BadRequest. Http request failed as there is an error getting AD OAuth token: 'AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app... However, I am using the Client Secret Value and not the Client Secret ID.
2. Audit Log Wizard>Start Audit Log subscription     Error: InvalidJSON. The 'content' property of actions of type 'ParseJson' must be valid JSON. The provided value cannot be parsed: 'Unexpected character encountered while parsing value: F. Path '', line 0, position 0.'.
![Screenshot 2024-05-21 155016](https://github.com/microsoft/coe-starter-kit/assets/41122379/7b007c23-01b6-48a1-9481-d89a71bfb388)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Setup Wizard - ARM Features - Audit Logs Setup

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3323

**Comment by JulesCam** [comment]
Hi there, I am getting the same error so it is not isolated.

**Comment by petepuu** [comment]
@phil0074 Are you using Azure KeyVault or plaintext for client secret?

**Comment by petepuu** [comment]
@phil0074 @JulesCam Can you check in Coe Admin Command Center that all Audit Log environment variables are configured correctly. If you are **not** using Azure KeyVault to store the secret then you need to have it set in the AuditLogsClientSecret environment variable like here

<img width="602" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/8dff0493-c41c-47f0-a530-97b3970831aa">

**Comment by JulesCam** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/132581331/1e565b53-a15b-4ecb-a7ad-2c048fc4fd78)

Does this look right?

**Comment by petepuu** [comment]
@JulesCam yes that look correct if the client id/secret are correct. 

<img width="309" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/acf55ad3-709e-4cb9-b3d0-12b7e2bcc189">

<img width="422" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/8307644/035ab271-d8a8-451d-9ad8-2f9e3b9eacf8">

.
.
If you are not able to configure Audit Log sync using Setup Wizard then try manually using following steps

1. Verify that Audit Log environment variable values are defined correctly
2. Start **Admin | Audit Logs | Update Data (V2)** flow
3. Start **Admin | Audit Logs | Office 365 Management API Subscription** flow
4. If you haven't start the Office 365 Management API subscription then run **Admin | Audit Logs | Office 365 Management API Subscription** flow and set Operation = **start**

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/3c9bcc3a-3b0d-4a13-acbe-0d8a464d11cc)



5. Start **Admin | Audit Logs | Sync Audit Logs (V2)** flow

**Comment by Jenefer-Monroe** [comment]
Thanks for helping with the manual setup Pete! I can take investigating the Setup Wizard error for an upcoming release.

**Comment by JulesCam** [comment]
Thank you so much! Following the manual process seems to have worked. I can now see the audit data.

Thanks again, you guys have been great!

**Comment by phil0074** [comment]
> @phil0074 Are you using Azure KeyVault or plaintext for client secret?

I am using plaintext, but another member of our team has Azure KeyVault configured too.

**Comment by phil0074** [comment]
> @JulesCam yes that look correct if the client id/secret are correct.
> 
> <img alt="image" width="309" src="https://private-user-images.githubusercontent.com/8307644/332765957-acf55ad3-709e-4cb9-b3d0-12b7e2bcc189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODQzNDEsIm5iZiI6MTcxNjM4NDA0MSwicGF0aCI6Ii84MzA3NjQ0LzMzMjc2NTk1Ny1hY2Y1NWFkMy03MDllLTRjYjktYjNkMC0xMmI3ZTJiY2MxODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTMyMDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDcwNjA5OGVhYzlkMWRiMmM3ZDRmMjhhYjc1MDYyYmM5ZmM3Mzg3NTFmOTA4MjU3MTNkODM1OTRiYWU2Yzc5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TYJAcKYSjWhZ7Yl1mcsX1mlgjH2a4AJFp85sYXOSXY0"> <img alt="image" width="422" src="https://private-user-images.githubusercontent.com/8307644/332766106-035ab271-d8a8-451d-9ad8-2f9e3b9eacf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODQzNDEsIm5iZiI6MTcxNjM4NDA0MSwicGF0aCI6Ii84MzA3NjQ0LzMzMjc2NjEwNi0wMzVhYjI3MS1kOGE4LTQ1MWQtOWFkOC0yZjllM2I5ZWFjZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTMyMDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTc4NzI4YjI0NjdhZDdkNTdmODRiMjhlM2FiNDc5OTUwYjk3NjE4NzdjZTJkODhkNjVmNzNiOWY2Y2IyMGU3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o9jRw1G1UbjxbkU_SvxMvzbNa8U7cxb0SD0kICP3-Vo">
> . . If you are not able to configure Audit Log sync using Setup Wizard then try manually using following steps
> 
> 1. Verify that Audit Log environment variable values are defined correctly
> 2. Start **Admin | Audit Logs | Update Data (V2)** flow
> 3. Start **Admin | Audit Logs | Office 365 Management API Subscription** flow
> 4. If you haven't start the Office 365 Management API subscription then run **Admin | Audit Logs | Office 365 Management API Subscription** flow and set Operation = **start**
> 
> ![image](https://private-user-images.githubusercontent.com/8307644/332767418-3c9bcc3a-3b0d-4a13-acbe-0d8a464d11cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODQzNDEsIm5iZiI6MTcxNjM4NDA0MSwicGF0aCI6Ii84MzA3NjQ0LzMzMjc2NzQxOC0zYzliY2MzYS0zYjBkLTRhMTMtYWNiZS0wZDhhNDY0ZDExY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTMyMDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmRmYTc0M2U1NTYxMDBhYjI1MDgyODcwNjM4NjgxY2NlZjhmODNkMGI1YjEzMDlhOTVhYTYzYjRkMThmYWIwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E4CCEeFEHGUafVznPKdbsrRN4lDINsf_8BgxLrtI8ps)
> 
> 5. Start **Admin | Audit Logs | Sync Audit Logs (V2)** flow

I tried running these steps. However, step #2 will not do anything unless a value is changed. Step #3 is the flow with error that seems to indicate that the flow believes I have not added the Client Secret Value, but I have checked an it is the correct value.

**Comment by Jenefer-Monroe** [comment]
Hello. Can you please share a screenshot of the issue you are facing with the API subscription flow?

**Comment by phil0074** [comment]
> Hello. Can you please share a screenshot of the issue you are facing with the API subscription flow?

![image](https://github.com/microsoft/coe-starter-kit/assets/41122379/ce535f59-6d63-42c0-83b7-74f7e1761823)

**Comment by Jenefer-Monroe** [comment]
Please go to your Connections in the coe envt, find the HTTP with Microsoft Entra ID (preauthorized) connection. 
Is it in a healthy state? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/06dcf1a6-c5b6-4b27-bb55-4ce019fc732e)

Click to edit
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1d84ca1d-53d7-49b9-bb91-58e48dc46892)

Is your graph url here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed6c54bc-8bc3-4190-8d32-9b45a768eb24)

**Comment by phil0074** [comment]
> Please go to your Connections in the coe envt, find the HTTP with Microsoft Entra ID (preauthorized) connection. Is it in a healthy state? ![image](https://private-user-images.githubusercontent.com/89584709/332835101-06dcf1a6-c5b6-4b27-bb55-4ce019fc732e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODgyODUsIm5iZiI6MTcxNjM4Nzk4NSwicGF0aCI6Ii84OTU4NDcwOS8zMzI4MzUxMDEtMDZkY2YxYTYtYzViNi00YjI3LWJiNTUtNGNlMDE5ZmM3MzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE0MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYmJmZTk2NGQ4NjgxN2JjZDJkOTkzYWNkNjg0MGQ0NGM5MTk0MWQ0ODcyYzc2M2ZiMTFhZWIyYjU0MjdlODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VUY_VxnrcFIc9XGsVQrfgyylGuU_BH1YgGNtgt3VbeQ)
> 
> Click to edit ![image](https://private-user-images.githubusercontent.com/89584709/332837182-1d84ca1d-53d7-49b9-bb91-58e48dc46892.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODgyODUsIm5iZiI6MTcxNjM4Nzk4NSwicGF0aCI6Ii84OTU4NDcwOS8zMzI4MzcxODItMWQ4NGNhMWQtNTNkNy00OWI5LWJiOTEtNThlNDhkYzQ2ODkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE0MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZTE3NTQ0MWJjMjJjMWFhN2I3ZDU2YTRiMzE3MDU4ZjkzZDI2OTI2NTRkN2I5MjYyYTMzMmE4ZGJiNzlhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h2ROkqU4fA0_KcsmGQVWOr9N9r7iMS9-X49JMtwFRXc)
> 
> Is your graph url here? ![image](https://private-user-images.githubusercontent.com/89584709/332837468-ed6c54bc-8bc3-4190-8d32-9b45a768eb24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODgyODUsIm5iZiI6MTcxNjM4Nzk4NSwicGF0aCI6Ii84OTU4NDcwOS8zMzI4Mzc0NjgtZWQ2YzU0YmMtOGJjMy00MTkwLThkMzItOWI0NWE3NjhlYjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE0MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZmMyYzY3MWFkMzhiNDJiZmNiZTdmNDFiNGZmMTZhMjMyYzA0Mzg0ZmQxN2IzZGQwZTlmMDNkNTkyZTE0OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uu1lE6KxqCWLLIA67SemoQfcfBmWMviAm04Ds8cz4h4)

Yes healthy state and correct URL/URI:
![Screenshot 2024-05-22 073213](https://github.com/microsoft/coe-starter-kit/assets/41122379/6940f9cb-ecc0-4265-8978-65d20aa79531)
![Screenshot 2024-05-22 073226](https://github.com/microsoft/coe-starter-kit/assets/41122379/69372f23-9cc6-4874-99c1-b9a7e962c5c3)

**Comment by Jenefer-Monroe** [comment]
And now check the environment variable to make sure its correctly formatted (ex ending slash present)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ee71f35a-2728-4909-af32-7298e8ab98bd)

**Comment by phil0074** [comment]
> And now check the environment variable to make sure its correctly formatted (ex ending slash present) ![image](https://private-user-images.githubusercontent.com/89584709/332840848-ee71f35a-2728-4909-af32-7298e8ab98bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODg4MzMsIm5iZiI6MTcxNjM4ODUzMywicGF0aCI6Ii84OTU4NDcwOS8zMzI4NDA4NDgtZWU3MWYzNWEtMjcyOC00OTA5LWFmMzItNzI5OGU4YWI5OGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE0MzUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZjA2ZDEzMTMxMWM1OGQ1MTcxNTRkZDI3YTNhZTk3ZWE4NjI3YmE5MWIxNzU3MTU3MWM3Y2Q0MzY4OWY0N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.32a9ZI1qlGs4HynMoWWGsT2vPkjEPCHdgh31xzl7aoM)

Yes, same as above

**Comment by Jenefer-Monroe** [comment]
OK I'm not sure then, you may have copied the wrong app registration ID or the wrong secret. 

Note the ID is the Application (client) ID, not the Object ID
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e03cb5d9-caa9-43a8-9784-2951fecbb083)

**Comment by phil0074** [comment]
> OK I'm not sure then, you may have copied the wrong app registration ID or the wrong secret.
> 
> Note the ID is the Application (client) ID, not the Object ID ![image](https://private-user-images.githubusercontent.com/89584709/332847100-e03cb5d9-caa9-43a8-9784-2951fecbb083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODk4MzgsIm5iZiI6MTcxNjM4OTUzOCwicGF0aCI6Ii84OTU4NDcwOS8zMzI4NDcxMDAtZTAzY2I1ZDktY2FhOS00M2E4LTk3ODQtMjk1MWZlY2JiMDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE0NTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOThkMDUxMzliODM5NmNlMWZjZjM4ZjBjZWY3MzJiY2NjMTJmNTQyMWYzMTIyNzdjY2ZlMGNkZjA0ZGY5ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OxY5Oee0rnhpoIwrd8RYHmS6DXKiYfy3pzx1iruTn78)

I understand and I have verified environment variables as noted earlier. I will try creating a new secret and entering in the wizard to see if it runs correctly.

**Comment by Jenefer-Monroe** [comment]
I've had people in the past copy from the wrong tenant (they had a test tenant) for this case. So its not an uncommon mistake. 
Please do let us know.

**Comment by petepuu** [comment]
@phil0074 other permissions does not matter. Based on the error message it still seems that client secret is not correct.

**Comment by phil0074** [comment]
They are correct:
![Screenshot 2024-05-22 080641](https://github.com/microsoft/coe-starter-kit/assets/41122379/afe1409f-afd8-462a-af99-d1ae33d0d5e7)
![Screenshot 2024-05-22 080740](https://github.com/microsoft/coe-starter-kit/assets/41122379/b8d9efc3-eb76-4022-b7e9-8e7ab65671b8)

**Comment by petepuu** [comment]
@phil0074 you have configured Azure KeyVault as well and is what is used by the flow. Do you have the same client secret there?

**Comment by phil0074** [comment]
No, that was setup previously by another Engineer on the team. I will work to clear it or investigate that further.

**Comment by phil0074** [comment]
I removed the AzureKey and it seems to be working now. Thank you @petepuu and @Jenefer-Monroe for all your help!

**Comment by Jenefer-Monroe** [comment]
Wonderful news! This was a great team effort, way to persevere everyone :) 

I'll go ahead and close then since this is working now.
