### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Request Management - handling extend situation

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8323]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 

In Environment Request Management app or Environment Clean up flow, is it possible to handle the situation if the user wants to extend the number of days to utilize the environment. 

For example, while generating the request to create an environment, say user just wants it for 30 days. In current scenario, my understanding is after 30 days the clean up flow will remove the environment. Say if the user changes his mind to extend and keep the environment for another 30 days basically changing this value from 30 to 60 , is it possible to do this today? Or do you think if we can take this as a new feature request? Thanks 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Core - Solution

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3329

**Comment by Jenefer-Monroe** [comment]
To area owner to please respond.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
