### ISSUE TITLE
[CoE Starter Kit - QUESTION] Hide Admin Command Centre Release Waves page (or find dynamic way to get the information)

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#8326]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi I have noticed within the CoE Admin Command Center App under the Release Waves, these are all showing from 2023.  Does this section of the App get updated?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3332

**Comment by Jenefer-Monroe** [comment]
No it looks like these were hard coded when the feature was implemented. Likely we should just hide this pages unless we can figure out how to get these dynamically. 
Thanks for pointing out.

**Comment by Jenefer-Monroe** [comment]
I had to touch the page anyway for a control change so went ahead and updated them to 2024 wave 1. Will update for wave 2 when its out this fall.
