### ISSUE TITLE
[CoE Starter Kit - How to set default value of new Environment record - Excuse from Compliance Flows value to Yes

### ISSUE THREAD

**Issue by astar01** [microsoft/coe-starter-kit#8327]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When a new environment is created and Admin Sync Flow creates a new environment record in CoE Starter Kit, we would like the default value of all the compliance related column values to set to Yes, like Excused from Compliance Flow, Excused from Inactivity Flows to Yes. How can I do that? That is because we don't any new environment to get into these compliance flows, unless explicitly turned to No. 
By default, when a new Environment record is created in the Dataverse tables, the value for Excused from Compliance Flow is set to No. We would like it to be yes.

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

None

AB#3333

**Comment by Jenefer-Monroe** [comment]
Hello. I suggest an add-on flow which listens for new environments added to this table and then updates the fields. 
Let me know if you need help understanding how to do that, happy to help.

**Comment by astar01** [comment]
Hi Jenefer,

Can you please help me how do I identify the new Environments that are newly added?

Thanks.

**Comment by Jenefer-Monroe** [comment]
Hello yes certainly. 

### existing envts
So for your existing environments, you will need to walk through and configure those manually. 
If you are doing a bunch at once likely the easiest way to do that is through the Excel Add In
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5df73852-8046-4361-836e-295e5f2d0d1b)

### trigger for new envts
Then going forward you can catch new environments added to the inventory by making a new flow with this trigger type:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/09b499d9-b44e-45f7-9c1b-c0cd11e142ca)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2351f3c8-57a0-4103-a62c-8c7a764322d9)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/934492a7-c006-4604-a672-68c2a67820cb)

### update the envt record
then you'll want to update the envt as the other step in the flow

**_chose the action and select the row from the trigger (the newly detected envt)_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/52112f55-aa59-4fba-b421-4060036846e8)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/53e4242d-b9c9-4f01-82b8-10adf29d4b19)

**_select the envt to update_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/193f495a-e22e-484c-a30a-ed1028ed176a)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/638ebc31-b691-4deb-a222-74bbd6d49d04)

**_select what fields to update_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/99eb74ea-210c-4ab5-becc-9efa95a6796e)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/db3c0554-6cde-49e9-985b-516a69b742db)

### Save and test 
Now save and test it by manually adding a fake record to the envt table manually.

**Comment by astar01** [comment]
Thank you very much for your prompt help. This resolves our issue.
