### ISSUE TITLE
AI Credits Usage The key didn't match any rows in the table.

### ISSUE THREAD

**Issue by Sraya114** [microsoft/coe-starter-kit#8328]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi we are trying to set up BYODL_CoEDashboard
and encounter an error:
21 queries are blocked by the following error:
Using AI credit
The key does not match any row in the table.
query parameters

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

BYODL_CoEDashboard

### What method are you using to get inventory and telemetry?

Data Export

AB#3334

**Comment by Jenefer-Monroe** [comment]
1. Have you successfully setup the BYODL dashboards in the past?
2. Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Sraya114** [comment]
1. No it's the first time
2. 
<img width="480" alt="COE" src="https://github.com/microsoft/coe-starter-kit/assets/73830354/d57c42f8-f394-46a8-9ff0-959dcf553eba">

**Comment by Jenefer-Monroe** [comment]
At this time we are not recommending new people try out the Data Export feature as a large re-arch is in the works and so any frustration you have with setup will soon be undone, and walls you hit with the data itself will likely not be considered in the near term just due to the re-schema in play.

**Comment by Sraya114** [comment]
So do you recommend changing to cloud flow instead of data export?

**Comment by Jenefer-Monroe** [comment]
Yes at this time we are recommending cloud flow architecture. Depending on your tenant size you may still hit errors but its the more dependable system at this time. 

What is the approximate size of your tenant? Approx number of envts for example.
