### ISSUE TITLE
[CoE Starter Kit - QUESTION] ActionFailed. An action failed. No dependent actions succeeded.

### ISSUE THREAD

**Issue by L0k33** [microsoft/coe-starter-kit#8329]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The "Admin | Inactivity notifications v2 (Check Approval)" workflow failed due to "ActionFailed. An action failed. No dependent actions succeeded".

![image](https://github.com/microsoft/coe-starter-kit/assets/107485479/40a1f893-2433-4c3c-8db2-a576a67e099c)

I am struggling with finding a solution for this issue. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.16

### What app or flow are you having the issue with?

CLEANUP HELPER - Check Deleted v4 (PVA

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3335

**Comment by Jenefer-Monroe** [comment]
Hello, you will need to dive in and find where in the loop the failure occurred.
You can click "Next failed" and then look for where the flow terminates in that loop with the error.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3c4bb414-5ad8-4c36-8f49-5022c1595fed)

**Comment by L0k33** [comment]
Apologies.

![image](https://github.com/microsoft/coe-starter-kit/assets/107485479/3620d029-1d04-416f-a515-f0b61b93bbec)

**Comment by L0k33** [comment]
{
    "host": {
        "workflowReferenceName": "5625768c-bd3d-ec11-8c63-00224829720b"
    },
    "body": {
        "email": "b57c91d0-b6dc-49c9-a0b7-31e044821ba8",
        "text": "CoE Starter Kit - Inactivity Notifications: Delete Power Apps has been rejected for  When a new response is submitted -> Get response details,Create item",
        "text_1": "<p>The following object went through the Inactivity Notification processes and was rejected by the owner for the reason listed.<br />If the reason seems like a persistent one you can excuse it from going through the processes again in the future using the&nbsp;App and Flow Inactivity Notifications Clean Up View app.</p><br>\n<strong>Maker</strong>: Alan Barnett  <br>\n<strong>Display Name</strong>: When a new response is submitted -> Get response details,Create item<br>\n<strong>Environment</strong>:  Personal Productivity<br>\n<strong>App ID</strong>: 8d1ff8aa-b116-ef11-840a-6045bdcf76dd<br>\n<strong>Reason</strong>:  <br>",
        "email_1": "",
        "email_2": "",
        "email_3": "",
        "text_2": ""
    }
}

**Comment by Jenefer-Monroe** [comment]
Is this flow in Core turned? **_HELPER - Send Email_**

That is the child called here. If so, do you see your failure in the run list?

**Comment by L0k33** [comment]
The **HELPER - Send Email** flow had a warning, which stated that there was an issue with the manual trigger. I resubmitted the last flow which resolved it. I then resubmitted the **Admin | Inactivity notifications v2 (Check Approval)** which succeeded. 

![image](https://github.com/microsoft/coe-starter-kit/assets/107485479/43045749-400b-49c2-a0b3-cb2cb4141060)

**Comment by Jenefer-Monroe** [comment]
Wonderful. Sounds like your trigger was broken somehow but is now resolved.

**Comment by L0k33** [comment]
Your help is much appreciated, as always. :)

**Comment by Jenefer-Monroe** [comment]
YEAH! I'll go ahead and close this out then.
