### ISSUE TITLE
[CoE Starter Kit - QUESTION] Change Flow Owner for Orphaned Flows - for Solution/non Solution aware flows

### ISSUE THREAD

**Issue by astar01** [microsoft/coe-starter-kit#8330]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

If a flow is orphaned, but still has co-owner, is it possible to change the flow ownership to the co-owner? If this feature does not exist, is it possible to create our own flow with Power Automate for admin connector or some other way? Please not that I am asking for both solution aware and non solution aware flows. Thanks a lot for your help.

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#3336

**Comment by Jenefer-Monroe** [comment]
We have adjusting flow ownership on the task list for the next few months. Sorry we dont have this today for you.

**Comment by astar01** [comment]
Hi Jenefer,

Thank you for getting back. But I would like to know how it would be possible to change the owner of a flow for a non solution aware flow? Is that even a possibility when it is not supported even via UX or PP admin portal or powershell. If there is a possibility, I can create my own flow, but I used Power Automate for Admin connector and it throws an exception when we try to change membership with role as Owner. Is there any way to accomplish this?

Also Microsoft documentation states this - https://learn.microsoft.com/en-us/power-automate/change-cloud-flow-owner
So  I am not sure if it will be even a possibility in the future.

**Comment by Jenefer-Monroe** [comment]
No its not possible unfortunately. These flows don't actually have a concept of Owner at all, they just have Creator. And thats what is exposed in the UX is the flow creator. 
So the product's suggestion is that you re-create the flow as the new owner or add it to a solution.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
