### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow option without the Clean up old Objects app

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#8331]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, I would really like to implement this into our production tenant, are there any plans to have other flows for the Inactivity that do not need to use the Model Driven app?  We do not have premium licenses for all our users and although the message in teams gives the option of either the app or the workflow ux this may still be confusing to users and we want to try and make the process as simple as possible.
Thanks

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Admin | Inactivity Notifications

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3337

**Comment by Jenefer-Monroe** [comment]
Unfortunately no, we do not have plans to replat these features to not require a premium license. 
Even if we were to use Canvas apps everywhere the apps would still rely on Dataverse as the base which is a premium connector.

**Comment by Alyson95170** [comment]
No worries Jenefer thanks for letting me know :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
