### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI report failed to refresh because of missing column in AI Credit Usage table

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#8335]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Error below happens on scheduled refreshes for Power BI Report based of **Production_CoEDashboard_May2024**
An error occurred while processing the data in the dataset. 
Refresh failed:

<PowerBIReport> has failed to refresh.
Failure details: The last refresh attempt failed because of an internal service error. This is usually a transient issue. If you try again later and still see this message, contact support. 
The '<ccon>admin_aibuildermodel</ccon>' column does not exist in the rowset. Table: AI Credits Usage.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Production_CoEDashboard_May2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3342

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Jenefer-Monroe** [comment]
Are you in a commercial tenant? Or one of the sovereign clouds?

**Comment by VanIsleCA** [comment]
Commercial

**Comment by Jenefer-Monroe** [comment]
I'm not sure. We dont have that connection in the table. 
Can you please try with the PBIT for next month? It does not have any new data sources and so works with May CoE release.
[Production_CoEDashboard_June2024.zip](https://github.com/microsoft/coe-starter-kit/files/15420991/Production_CoEDashboard_June2024.zip)

**Comment by VanIsleCA** [comment]
Thanks, that worked? Not sure why, because it was still missing that column from the AI Credits Usage table. But thanks for suggesting this!

**Comment by Jenefer-Monroe** [comment]
Wonderful. I'll go ahead and close this out then but please do return with new issues as they occur!
