### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION: Related to #2946 - Require multiple Power BI Dataverse connections across different tenants, environments, and using different accounts

### ISSUE THREAD

**Issue by JulesCam** [microsoft/coe-starter-kit#8337]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I read in one of the other posts that it is recommended that if you need to create multiple Power BI dashboards and you need to switch from one tenant to another for the dataverse data source, that you should edit or clear all permissions from existing dataverse connections in Power BI desktop to reset it. I will be creating 8 different Power BI Dashboards connecting to 8 different dataverses, across four tenants [2 each tenant - test and prod] and using 8 different dedicated accounts [2 each tenant - test and prod]. 

My concern is that by clearing all permissions from the connections I've made, it might impact the already published models and reports in one of our tenants. 

Does clearing my permissions for dataverse in power bi impact the published sematic and report in power bi service?

I have managed to connect to two dataverses but one does have the https:// in front of the URL and that is because when I attempted to open the template, it opened without asking me for details of the environment I wanted to connect to, like it did the first time - any idea why it wouldn't have prompted me? I wasn't logged in but the Dataverse connection remained. I managed to add another connection via the Data Source Settings and established a connection but it is not allowing me to sign in using my dedicated account [set up correctly as far as I can tell] There doesn't seem to be a way to edit the URL once it has established a connection so feel a bit stuck. 

I wonder if your advice to clear the permissions is the best route to ensure I can cleanly create the many dashboards for each of our partner tenants for both test and prod environments - just cautious of any impact the the existing published report in one of our partner tenants.

First connection steps taken [partner one - test environment]
1. Opened Power BI Desktop [for the first time, not used before]
2. Clicked 'Open' and selected the Power BI Dashboard Core
3. Prompted to input environment URL > entered
4. Prompted to sign in > signed in with the dedicated account used to install the starter kit core components and creator kit
5. Established connection and data visible

Second connection steps taken [partner two - test environment- separate tenant - separate account]
1. Opened Power BI Desktop [for the second time now]
2. Prompted to login > ignored
3. Navigated to Data Source Settings
4. Selected 'Dataverse'
5. Clicked Edit to update my credentials to the new tenant with the different dedicated account
6. Connection seems to be established and I could see the environments [connection shows without the https:// and I can't edit]
7. Asked to choose the tables to connect to
8. No idea what I should be selected since I only entered the URL the first time

Any support would be much appreciated.

<img width="610" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/132581331/9cb17a1f-e373-4585-84c1-c631c1fc9077">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3345

**Comment by Jenefer-Monroe** [comment]
Hello, sorry I'm afraid we are not Power BI experts as that is a separate team internally here. Our CAT team does not cover that product.

The advice we offered there is for when connections become corrupt. Especially when trying to combine multiple sources like in the BYODL dashboard. It's not something we suggest you do regularly. 

Any long term impacts of Power BI permissions and settings, and using across tenants and things like that, I'm afraid you'll need to find a Power BI expert to interact with and find answers.

Sorry I can't be of better assistance.

**Comment by JulesCam** [comment]
Thank you. That is no problem, I will go to the Power BI Community.

Just wondering, appreciate you are not Power BI expects, but do you know why there would be occasions when you are not prompted to provide the environment URL when you open the dashboard? If not, no worries.

Appreciate you coming back to me so quickly - once again :)

**Comment by Jenefer-Monroe** [comment]
Yes we have hit that one once or twice and just added notes about it for an upcoming docs release please see this comment from this issue
https://github.com/orgs/microsoft/projects/195/views/58?pane=issue&itemId=49444477
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f7275f20-a934-4cd0-baa5-6a622641e8c2)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
