### ISSUE TITLE
[CoE Starter Kit - QUESTION] Federated Credentials

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8338]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 

Is it possible to use Federated credentials to utilize our Audit log API though not sure how it works.
<img width="836" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/88de5965-baa6-44de-9bde-1a499deeeaab">
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Core - Solution

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3346

**Comment by Jenefer-Monroe** [comment]
We've not tested that, or used that type of credential before, so I wouldn't be able to advice how to use it. 
From my quick read I think it would create a larger security surface to manage so we likely would not have it be our recommendation. But please let me know if you understand differently.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
