### ISSUE TITLE
[CoE Starter Kit - QUESTION] Clarification on location of makers on Power Apps tab in CoE Dashboard

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8340]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 

Could you please clarify on how the locations are detected, is it the IP location or ??. Customer is in Ireland but see some makers in US as well.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Core - Solution

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3349

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
