### ISSUE TITLE
[CoE Starter Kit - Feature]: Mandatory check on Support details fields of Developer Center App

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8341]
### Is your feature request related to a problem? Please describe.

Hi Team, 

Is it possible to make mandatory to fill support details by maker on developer compliance app as it will help the admin and this way they can make sure that all the support details are provided by the maker. 

### Describe the solution you'd like

<img width="758" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/debc8a0b-affe-45a7-b6cb-41f563bb9065">

AB#3350

**Comment by Jenefer-Monroe** [comment]
Unfortunately not. Different organizations have different required fields here. So if you want some to be required that is an unmanaged layer you will need to put on the custom page.

**Comment by PPMini** [comment]
Yeah, I think then to go custom is the best. Thanks a million for taking out time and answering all these questions. I really appreciate the effort you are giving in this. Closing this one.
