### ISSUE TITLE
[CoE Starter Kit - QUESTION] Difference in order of Compliance parameters 

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8344]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team , 

While deploying this to a customer, we observed that the parameter order on compliance parameter screen on CoE Setup Wizard is different for both of us. Is it normal?

For CSA : 
<img width="799" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/21cf7bfb-868a-474d-93dc-4ddc8e005fe1">

For Customer:

<img width="915" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/607f5305-00ee-4885-ab28-ab909a2533b4">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Governance - Solution

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3353

**Comment by Jenefer-Monroe** [comment]
Yes the order of the env variables on the screen is not fixed.

**Comment by PPMini** [comment]
Thanks a million for confirming.

**Comment by Jenefer-Monroe** [comment]
You are so welcome, I'll go ahed and close then but please return with new issues as you have them!
