### ISSUE TITLE
[CoE Starter Kit - QUESTION] Display group name as well on the governance dashboard report

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8346]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is it possible to display group name as well on the below report?

<img width="720" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/803fe4af-b35d-4dae-9748-4c6c5879ae1c">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Governance - Solution

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3355

**Comment by Jenefer-Monroe** [comment]
Not in this same visual, no. As this is a single row per app. However we do have this information in the Power Platform Admin View app. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc8e5159-daaf-478c-b749-34c77f56138c)

**Comment by PPMini** [comment]
ok! got you. Thanks

**Comment by Jenefer-Monroe** [comment]
Wonderful! I'll go ahead and close then but please do return with new issues.
