### ISSUE TITLE
[CoE Starter Kit - Innovation Backlog]: Ability to change currency

### ISSUE THREAD

**Issue by jondoesflow** [microsoft/coe-starter-kit#8352]
### Is your feature request related to a problem? Please describe.

The Innovation Backlog money icons and other references to money are all depicted as USD.

### Describe the solution you'd like

It would be good to have as part of the COE Setup tool, to be able to determine your currency.

### Describe alternatives you've considered

Creating an unmanaged solution, putting the Innovation Backlog into the solution, and changing the icons and $ to £ myself.

AB#3361

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
