### ISSUE TITLE
[CoE Starter Kit - Dashboard] Empty PowerBi Dashboard after installation 

### ISSUE THREAD

**Issue by gsabisch** [microsoft/coe-starter-kit#8353]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have installed the CoE Core Components and try to open the Power BI Dashboard. While doing this i receive a blank dashboard. Every Tab is empty. The only error i receive ist by starting some cloud flows 

<img width="621" alt="Screenshot 2024-05-24 140254" src="https://github.com/microsoft/coe-starter-kit/assets/170728951/75b010f9-c4e1-41ac-aa78-4058a8cc9a4d">

During the installation process i didn't receive any errors.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 2023

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3362

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
