### ISSUE TITLE
[CoE Starter Kit - QUESTION] How do i see which flows are premium

### ISSUE THREAD

**Issue by jpreston4** [microsoft/coe-starter-kit#8356]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I dont see this in the Flow table and have not found it in the Power BI reports

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Data Export

AB#3367

**Comment by Jenefer-Monroe** [comment]
Unfortunately the V1 of the Data Export feature did not make this easy for us but its on the list for the big upcoming work for the new schema.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
