### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Power Apps User Shared With flow failing as Tenant has no Guests

### ISSUE THREAD

**Issue by MartinneJohnsonTSA** [microsoft/coe-starter-kit#8358]
![CLEANUP HELPER - Power Apps User Shared With Flow Error](https://github.com/microsoft/coe-starter-kit/assets/170910534/2fa15b6d-58e6-44fd-ae0a-03aed4594d54)
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The flow fails at the Tenant Has Guests action.  This flow started failing after installing the May 2024 Core solution.  Previously installed solution was March 2024 solution.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

### What method are you using to get inventory and telemetry?

None

AB#3370

**Comment by Jenefer-Monroe** [comment]
I actually this may be because you have a bad record for Tenant in the user table. 
Please run the following flow which will make sure this user is set up correctly: **CLEANUP - Admin | Sync Template v3 (Orphaned Users)**
After that flow completes, please let me know if you still see issues with this flow.

**Comment by MartinneJohnsonTSA** [comment]
Thank you.  I ran the CLEANUP - Admin | Sync Template v3 (Orphaned Users) flow and then resubmitted the failed CLEANUP HELPER - Power Apps User Shared With flows.  They all worked this time.

Much appreciated the help.

Regards
[The Salvation Army Red Shield logo.]<https://www.salvationarmy.org.au/>

Martinne Johnson
Senior Application Developer
Information Technology
The Salvation Army Australia Territory
salvationarmy.org.au<https://www.salvationarmy.org.au/>
[Red Shield Appeal 2024 Image]
Email: ***@***.******@***.***>
Address: Level 2, 262-265 Chalmers St, Redfern NSW 2016
Phone: +61 2 9466 3233
Want to know more about our local activities?
Click here to find out<https://www.salvationarmy.org.au/locations/>
[Facebook]<https://www.facebook.com/TheSalvationArmyAustralia/>[Instagram]<https://www.instagram.com/salvosau/>[X]<https://www.instagram.com/salvosau/>[LinkedIn]<https://www.linkedin.com/company/the-salvation-army-australia>[YouTube]<https://www.youtube.com/user/SalvArmyAUS>
Wherever there is hardship or injustice, Salvos will live, love and
fight, alongside others, to transform Australia one life at a time
with the love of Jesus.
[The Salvation Army Australia Inclusion and Diversity Icons]
Read about our commitment to reconciliation,<https://www.salvationarmy.org.au/about-us/inclusion/>
inclusion and diversity.<https://www.salvationarmy.org.au/about-us/inclusion/>

________________________________

**Comment by Jenefer-Monroe** [comment]
Wonderful! Thanks for returning to let us know! I'll go ahead and close this out then.

**Comment by RickKush** [comment]
The closest flow I have to that cleanup is _CLEANUP - Admin | Sync Template v3 (Orphaned **Makers**)_
