### ISSUE TITLE
[CoE Starter Kit - QUESTION] work of the flow after 30 days

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#8359]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!
I had the question about the duration/limit of the flow's run.
I found an information on the internet about the 30 days limit of duration of the flow's run. As I understood, it means that after 30 days the flow will just stop working.
I wanted to confirm that - is that correct that the flow really will just stop working when it reaches 30 days? We see that the history of the flow's work can be seen for 28 days. 
<img width="587" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/ec6a0044-9682-4ce4-89c3-de0df97915c8">

So, if the flow's run will disappear after 28 days, it still will run for more 2 days? or it will just disappear from the view but will run till the flow works is done completely, meaning, even more than 30 days? 

If the right option is that anyway in both situations - whether we see the view or not - it will stop exactly after reaching 30 days, then I have the question how to manage the flow's work, for example, in these two flows:

Request Orphaned Objects Reassigned (Parent) 
Request Orphaned Objects Reassigned (Child) 

For example, we have big organization where we have a lot of orphaned items. Every time we run the Parent (Request Orphaned Objects Reassigned) flow, it never manages to go through all the items as it sends the requests to the Child flow, then , let's imagine, that a lot of users do not respond to the adaptive cards that they receive in Teams, and as the time out is 7 days if the user do not respond, it means already 30-7 = 23 days left but still a lot of items that needs to be checked. So how to handle then all the items and run the parent flow successfully through all the items if there is a limit of 30 days in the flow (I mean, in case the information about 30 days as a limit is correct)

Thank you in advance!

### What solution are you experiencing the issue with?

Governance

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent) ; Request Orphaned Objects Reassigned (Child) 

### What method are you using to get inventory and telemetry?

None

AB#3371

**Comment by Jenefer-Monroe** [comment]
I believe your perception of how this works is correct, but it would really be a question for the product team. 
Regardless, I believe what you are facing is

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
