### ISSUE TITLE
[CoE Starter Kit - QUESTION] Concurrency Control as 50 requests maximum 

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#8360]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!

I have the question about the Concurrency Control in the flows.
For example, in the "Request Orphaned Objects Reassigned (Parent)" flow I have the maximum allowed number applied as 50.

<img width="427" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/3e3783c5-a5cb-4551-b512-5a2e1aca4419">

Am I correct that this Concurrency Control means the maximum number of the requests that will be sent out to the child flow at once?
If yes, I noticed that at the beginning of the parent flow's run it was sending 50 requests to the Request Orphaned Objects Reassigned (Child) flow. But after ~ 20 days, I saw that if all the previous child flow's runs are done and again needs to be sent 50 new requests from the Parent to the Child flow, it sent exactly 10 cards only. At first when I noticed that, I thought that maybe there are only 10 child flow's running because maybe they are the last runs of the child flow and then the parent flow will be done running. However, when I just stopped the 10 child flow's running to check that it is true, the other new 10 requests were sent to the child flow, that means that my hypothesis was wrong, and somehow it really started to send only 10 requests instead of 50 even as I did not change any setting inside the flow. 
What could that mean and why this is happening?  

### What solution are you experiencing the issue with?

None

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent); Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

None

AB#3373

**Comment by Jenefer-Monroe** [comment]
Likely you are getting old runs coming through. We changed these flows slightly in May release with this bug https://github.com/microsoft/coe-starter-kit/issues/8060

We did this to allow the parent to run through all the children and not wait for them to complete. 
So it will now kick off the children in batches of 50 but not wait for them to complete before starting the next 50.

**Comment by Jenefer-Monroe** [comment]
Yes I am just not sure if all the changes are documented. You can certainly try to do that though. 

I've updated the bug with the changes I made for your other issue for June: https://github.com/microsoft/coe-starter-kit/issues/8362#issuecomment-2135628614

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
