### ISSUE TITLE
[CoE Starter Kit - QUESTION] issue with the "Assign to all" button in the Request Orphaned Objects Reassigned (Child) flow

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#8362]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!

I had the question regarding the Request Orphaned Objects Reassigned (Child) flow and the action "Assigntoall".
<img width="171" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/290cc4ec-b586-4241-8c4b-db24a586e194">

I noticed that usually when users click to the button "Assigntoall" - it fails. 

<img width="613" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/c73c18b2-18b2-4c29-97f1-7c9364d6ce5d">
<img width="618" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/113427788/99ba945f-cdca-4cf2-807c-bb12519adea9">

I tested the flow to see what happens If I will click to this button, but for me it works successfully. Also, I noticed that sometimes when the users click to it, it also works successfully for some of them. So, it is not always failing and not all the users fail if this action is clicked. So, I assume this action is not allowed for everyone? Or that is not right, and this action needs to work for all the users? Do you know what could be the problem?

### What solution are you experiencing the issue with?

Governance

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

None

AB#3375

**Comment by Jenefer-Monroe** [comment]
Looks like this happens if they dont enter anything for the user to reassign to. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/769be65f-b627-48a8-bb11-eadfefe23541)

Let me see if there is an easy fix

**Comment by Jenefer-Monroe** [comment]
ok just added a coalesce statement so that was an easy fix for June release.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f9d65496-4604-4962-b5f6-3f458b3a295b)

Same bug also existed in the "see each" branch so fixed there too.

**Comment by JanetK12** [comment]
Hi @Jenefer-Monroe !
Thank you for your answer!
Oh, I see!
I hope this is the case. 
Just in case I will try to contact with the user that has this issue to understand that indeed they did not write the email in the field. 
But could I ask something? As We have the custom version of the flows, would that be possible for you to show what steps you added and where in the flow, so that we can add them manually to our custom flow now? of course, in case this is possible!
Thank you advance!

**Comment by Jenefer-Monroe** [comment]
Here are the changes made for this issue:

### Assign all
This expression: @`{coalesce(outputs('Send_Table_For_Response')?['body/data/toWhom'], 'No data entered')}`
Here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7d51e40d-3d37-4388-b422-9aebcf1b80b6)

### Assign each - app
This expression: `@{coalesce(outputs('SendAppForResponses')?['body/data/toWhom'], 'No data entered')}`
Here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/90540a7b-fad6-4e6a-afd2-61e3004e8621)

### Assign each - flow
This expression: `@{coalesce(outputs('SendAppForResponses_flow')?['body/data/toWhom'], 'No data entered')}`
Here
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/23beb395-b87e-4aca-add9-dbd305bab802)

**Comment by JanetK12** [comment]
Hi @Jenefer-Monroe !
Oh, thank you very much for all these steps!!! I will try that! Hope will work!

**Comment by Jenefer-Monroe** [comment]
You bet!
