### ISSUE TITLE
[CoE Starter Kit - QUESTION] Dataverse for Teams Environment review date

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#8364]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Within the admin centre app there is a  Admin - Review Teams Environment Status On for Dataverse for Teams Environments,  I cannot see a flow within the governance solution that will trigger on this record, is this something that is expected in a future release?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.21

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3377

**Comment by Jenefer-Monroe** [comment]
Here are the three flows responsible for this feature and where you should see them in the Admin Center assuming you have the Governance solution installed. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/64a33141-6668-4d71-a774-ec500ea8efbb)

**Comment by Jenefer-Monroe** [comment]
Wonderful! Thanks for letting me know! I'll go ahead and close this one out then.
