### ISSUE TITLE
[CoE Starter Kit - BUG] Environnement Request : Next or cancel button are inactive after select a connector

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#8365]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After i have selected a connector, and if i click on next nothing happens. 

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/2333d0a1-54ab-45c7-b0c2-377ae90c04a3)

### Expected Behavior

I expeted to have the next step. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Environnement Request 

### What method are you using to get inventory and telemetry?

None

AB#3379

**Comment by Jenefer-Monroe** [comment]
to area owner for investigation.

**Comment by gulzarudheen** [comment]
@tocri Started investigating on it.
