### ISSUE TITLE
[CoE Starter Kit - QUESTION] AI Credits Usage used by Unknown

### ISSUE THREAD

**Issue by pezlin** [microsoft/coe-starter-kit#8366]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the Power BI report _PowerBICoeReportMay2024_ AI Credits Usage shows data correctly. However, the top "user" is **Unknown**. What could be the reasons for the Unknown tag? 
<img width="655" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47033099/e399bf6c-e054-48e2-8cb4-d2507f6aaca8">

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3388

**Comment by Jenefer-Monroe** [comment]
Hello, we changed the concept of a user for this solution area from Maker to User, as non-Makers can also use AI Credits. 

Please see [issue 8158](https://github.com/microsoft/coe-starter-kit/issues/8158) for more information about that change.

We did a little write up in that same issue to help you fix up the old data. Please see [The workaround - fix up old data](https://github.com/microsoft/coe-starter-kit/issues/8158#issuecomment-2088960986)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
