### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Sync Template v3 (Flow Action Details) Error

### ISSUE THREAD

**Issue by AzizAQureshi** [microsoft/coe-starter-kit#8371]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am having an Error in a CoE flow 'Admin | Sync Template v3 (Flow Action Details) and the error is the following:
![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/69c6f989-1a39-4a21-b899-b3193d2eba02)

Please advise a solution to this.

Thank you

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)	

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3394

**Comment by Jenefer-Monroe** [comment]
What is the failure? Please click Next failed to find the failing iteration and find where the flow terminates with the failure.

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/63e3e21e-c3fb-49e0-97c1-0f680eba24cc)

**Comment by AzizAQureshi** [comment]
I have checked the next failure and they all look the same:
![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/3fe06da6-40ed-4060-ac4a-1d1777fbf413)

![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/976b3b29-0818-4e09-9233-ee516c63f5b7)


The actions after 'Reset needPermissions to false' are all blank.

On another CoE flow 'Admin | Gather Tenant SRs' is also failing and here is the screenshot:
![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/0b17e076-2fc2-410b-a015-0f7c138af6e9)

The Error for the CoE flow 'Admin | Gather Tenant SRs' is: 'The user is not a member of the organization. How do I fix this, please?

Thank you so much!

**Comment by Jenefer-Monroe** [comment]
sorry we can only cover one bug per issue it just gets too hard to track otherwise. 
Please create a separate issue for this SR one.

**Comment by Jenefer-Monroe** [comment]
Without seeing where it fails I'm not sure how to help. Can you please load the flow run again and see if it resolves to show where the failure is?

**Comment by AzizAQureshi** [comment]
Sure I will try that. Thanks for your response. 
And thank you once again

**Comment by AzizAQureshi** [comment]
The action that is failing in the first flow is the following:
![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/17dad004-2171-46f3-ab6c-cca243e64d69)

The error is:
Unexpected error. Request to Azure Resource Manager failed with error: '{"error":{"code":"ActionRepetitionNotFound","message":"The specified repetition '000014' of workflow action 'get_flow_defn' is not found."}}'

Please let me know what else you would need. 
Please advise how to fix this. 
Thank you.

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately it sounds like you are having trouble with the product in retrieving the run information. 
I suggest trying a more recent run of the flow for the failure.

**Comment by AzizAQureshi** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/543395e3-ff14-4780-96c3-69a263ec9869)
The above screen shot shows the most recent error and the error is the following:

![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/22a382e3-a0ec-4aba-8fb3-aa817288fec1)

**Comment by Jenefer-Monroe** [comment]
I'm afraid we can't help without access to the failure. That failure message you pasted is from the product failing to access the run history. Unfortunately, that isnt something I can assist with.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
