### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there a report to monitor Power Apps per app licenses?

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#8372]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I have per app licenses distributed across multiple environments. I find it very difficult to see the number of remaining per app licenses by environment, which users are using them, and which premium applications are the most used, etc.

Currently, I have to click on "Licenses", select my license type, then select the environment to see the applications using a per app license... It's quite a tedious process.

If you have a report or tool to make this tracking easier, you will make my day!

Thank you in advance for your help.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2024

### What method are you using to get inventory and telemetry?

None

AB#3395

<img width="679" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/eabb82c4-6df8-4d1a-bf4f-df04b74df83f">

**Comment by Jenefer-Monroe** [comment]
Unfortunately no, we do not have programmatic access to the license information. Sorry about that!

**Comment by tocri** [comment]
No problem. Thank you for you quick reply. It's very appreciate

**Comment by Jenefer-Monroe** [comment]
You bet, I'll go ahead and close this out then but please don't hesitate to reach out with other questions in the future!
