### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Request Attachment

### ISSUE THREAD

**Issue by alanmWDC** [microsoft/coe-starter-kit#8375]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Whilst reviewing a copy of the new Environment Request page that includes attachments an error is shown in the canvas app for all references to {Attachments}.
DataSourceInfo([@'Environment Creation Requests'],DataSourceInfo.DisplayName,'{Attachments}')
Error is Expected Text Value.

ThisItem.Attachments on the Attachments_DataCard1_2 shows the error "Name isn't valid. 'Attachments' isn't recognized"

The Environment Creation Requests Table does not have Attachments enabled and there is no column called attachments.

I only found this whilst checking the updates to include in my customized version of the page.

### Expected Behavior

Attachments references do not have errors.
Able to upload an attachment to a request. This is currently blocked by another logged issue that the Next button does not work.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CoE Maker Command Center Environment Request

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Add the Environment Request Page to another solution
2. Open the page to edit it
3. Error messages are shown in page and App Checker

AB#3398

**Comment by alanmWDC** [comment]
I enabled attachments on the Environment Creation Request table in my customization solution and that resolved the errors. Issue is this is not enabled on the managed solution

**Comment by Jenefer-Monroe** [comment]
To area owner for investigation.

**Comment by Jenefer-Monroe** [comment]
Please validate in the Prod Install envt that has the managed envt installed. 
Also perhaps this is a SR issue. Can you please iterate with the customer to see if you can find a repro?

**Comment by gulzarudheen** [comment]
@Jenefer-Monroe Found that it is not enabled in Prod Install environment, will import the component once again as part of next release.



![Image](https://github.com/microsoft/coe-starter-kit/assets/149140128/8c632e6f-8816-4a75-ac85-5c8c40fac51f)
