### ISSUE TITLE
"App Last Launched On" and  "Flow Last Run ON" not populated with values in the Tables

### ISSUE THREAD

**Issue by ValiPrk** [microsoft/coe-starter-kit#8376]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

"App Last Launched On" and  "Flow Last Run ON" not populated with values in the Tables, I saw a similar [question](https://github.com/microsoft/coe-starter-kit/issues/7619) was asked and wanted to know if any progress has been made on this topic.
Is there any chance to get this columns populated with values?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What method are you using to get inventory and telemetry?

None

AB#3400

**Comment by Jenefer-Monroe** [comment]
Flow Last Run On - this is not yet filled as we still do not yet have access to the information programmatically. The product team is working on exposing it but we don't have it yet.

**Comment by Jenefer-Monroe** [comment]
For app last launched, this is filled by the following solution area, have you done this setup?

[Collect audit logs](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by ValiPrk** [comment]
Hi, 

I solved the "App Last launched" situation (thank you for your reply), but regarding the "Flow Last Run On", do you have a time frame for when this will be implemented?

Also another question regarding the "Active Audit Logs" page from the Power Platform Admin View, is there any Lifecycle for the Audit logs in place? Or do we need to clean the old logs by ourselves?

Thank you very much for your reply!

**Comment by Jenefer-Monroe** [comment]
I'm afraid I cant offer a timeline on that other than to loosely say I think it will be late summer or early fall that this is ready for us to use in the product, and are able to get it into the kit. 

We do not have any lifecycle on the audit logs table at all, so if you wish to do some clean up of it after some time, thats something you will need to do yourself. 

Thank you

**Comment by ValiPrk** [comment]
One more question, is there some special procedure to remove the audit logs? Do you have an article on that?

Thank you for your reply!

**Comment by Jenefer-Monroe** [comment]
Hello. I presume you mean how to remove old audit log records over time? No we do not have an article on this in the kit.

**Comment by ValiPrk** [comment]
Hi, 

I would like to remove audit logs from the year 2022 for example (see attached screenshot), how would that be possible in a safe way? I would not want to do some damage there.

Thank you for your reply
![Audit Logs](https://github.com/microsoft/coe-starter-kit/assets/147488275/c067e8b8-c19e-4a71-ae41-047b0322331d)

**Comment by Jenefer-Monroe** [comment]
Hello. There are many ways to delete old data from tables:

1. Bulk delete - https://learn.microsoft.com/power-platform/admin/delete-bulk-records
2. The Excel Add in - https://learn.microsoft.com/en-us/power-apps/teams/edit-data-in-excel
3. Or write a flow which queries and deletes using the dataverse connector - https://learn.microsoft.com/connectors/commondataserviceforapps/

Please take a look and do whichever suits your needs best.

**Comment by ValiPrk** [comment]
Thank you for all the provided information and wish you a great day forward
