### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYODL

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#8377]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

The Flows and Apps remainder email  looking 'last launched app or flow' field. By setting up BYODL is going to change the flows and apps filter criteria?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3401

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not sure what you are referencing. Do you mean the Inactivity processes? 

We have not adopted those to the new "last run" concept yet, no. The Data Export feature has a big schema change coming and so we are paused on development until that comes through, and we are recommending people new to Data Export wait for the schema change before trying it at this point.

**Comment by lingutla123** [comment]
yes. I am asking about Inactivity processes.

Thank you,

**Comment by Jenefer-Monroe** [comment]
Got it. ok then no we have not done that work. And we likely wont until we are able to support for cloud flow arch as well which is targetted by the product team for some time this summer.

**Comment by lingutla123** [comment]
Hi Jenefer,

What are the benefits of setting up the BYODL?

Thank you,

**Comment by Jenefer-Monroe** [comment]
Hello at this time we do not recommend new users onboard to the existing BYODL experience as we are actively working with the product team on a big schema change which will heavily impact the setup process.

**Comment by lingutla123** [comment]
We are not starting. Just want to know the benefits of BYODL.

**Comment by Jenefer-Monroe** [comment]
closing out v1 data export bugs as plans for that are deprecated. 
will be posting v2 product blocking issues today
