### ISSUE TITLE
[CoE Starter Kit - QUESTION] Setting "Audit Logs - Client Azure Secret" Environment Variable

### ISSUE THREAD

**Issue by DCC-DM** [microsoft/coe-starter-kit#8378]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Greetings

We've recently been attempting to setup the audit components of the CoE Starter Kit.  However, we've hit an issue with populating the "Audit Logs - Client Azure Secret" environment variable and Microsoft Premier Support aren't willing to assist.

I've spent many hours reading through previous threads here and thus far haven't found a solution, despite seeing the same/similar error messages.

We had a right palaver getting a new Key Vault created to store the Enterprise App Secret (no previous experience with that or Power Apps tbf), but we got there in the end.

When we tried to save the Secret in the environment variable, either from the yellow warning banner at the top or directly in the "Default" solution, we got the following error:
"Could not verify the user permission on '/stuff' resource. Make sure that Microsoft.PowerPlatform provider is registered in the Azure subscription."

Loads more reading later, I think I was able to register the provider in the related subscription.  Since then, it appears to have been a bit hit and miss between the above, and this error:
"User is not authorized to read secrets from '/stuff' resource."

I didn't find the documentation for this particularly good at all.  It mentions the Key Vault permissions but not at what level they need to be applied etc., or for what account, or even App?  I presumed the Secrets User and Secrets Contributor roles would likely just need applying at the "Secret" level in IAM, so I did that for the our CoE Starter Kit service account.  Still no joy.

I'd be pulling my hair out if I had any...

Do we just store the "secret" in plain text against Microsoft advice and move on, or should this process be way more simple that we seem to be experiencing? 😬

Warm regards

Dan

![Power_Apps_EV_02](https://github.com/microsoft/coe-starter-kit/assets/171041567/2c1a06a9-2d98-455c-9eb0-459d69e23239)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

I believe we're on a 2024 version

### What app or flow are you having the issue with?

Audit components

### What method are you using to get inventory and telemetry?

None

AB#3402

**Comment by Jenefer-Monroe** [comment]
Hello. Please do push back on Product Support here. And have them reach out to Grant Archibald, the main CoE Starter Kit PM, with questions. 
This is a product feature and they really need to not push you off to me. 

That said, I'm happy to try and assist but if I can't, again, I'm afraid we need to get product support to do their side of the work here.

One thing we've noticed for azure key vault permissions, is that the user needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update. Can you please check that?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)

**Comment by DCC-DM** [comment]
Many thanks for the super swift response.

And alas, I've pushed back twice already, but they called me up today and basically said log a ticket on GitHub and we're closing this case off...  To be honest, we've not had great experiences at all with Microsoft "Premier" Support recently 😔  I can certainly add your extra voice to that though, and mention the name provided, thanks.

This permissions bit is one that had me a touch confused, it doesn't really specify exactly where to apply it, or whether it needs to be the service account you used to install the Starter Kit, or perhaps the Enterprise App?  I'm not familiar with Power Apps/Platform at all.

I went with the assumption it was the service account, and that I only needed to apply the permissions to the secret itself, not the root Key Vault or resource group etc.

![Key_Vault_01](https://github.com/microsoft/coe-starter-kit/assets/171041567/4054f1d0-613a-4484-b5c7-ef1f5e77bbd6)

I notice "Dataverse" in your screenshot.  If you don't mind me asking, what is that, and is it also required? 😊

**Comment by Jenefer-Monroe** [comment]
From the product documentation I do actually see that you need to grant **_Key Vault Secrets User_** role to the Dataverse service principal

From the product's learn documentation: [Use environment variables for Azure Key Vault secrets](https://learn.microsoft.com/power-apps/maker/data-platform/environmentvariables-azure-key-vault-secrets)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/02d0194a-0eab-42c3-920f-f60a0db7509a)

**Comment by DCC-DM** [comment]
Amazeballs, as soon as I added "Dataverse" to the "Key Vaults Secrets User" role at Secret level in the Key Vault in IAM, I was able to successfully store the environment variable immediately!

**However**, I have muddied the water somewhat...

After reading through one of the other threads on this issue, I noted someone mentioning the Network possibly being a factor, certainly if the business has restricted public access (which we have).

![Azure_KV_Network_01](https://github.com/microsoft/coe-starter-kit/assets/171041567/65fddf44-0b8b-4e4a-82ab-d6f46007452b)

To test, I flipped the setting to allow public access temporarily and left it to propagate over night.  I still got the same error when trying to store the environment variable this morning, that is until I added the "Dataverse" to the role you mentioned.

So, before I pop the champagne, I'll remove the environment variable again, switch the Network settings back to what they were previously, and check whether or not I can add it back.  If I can't, it would suggest we'll need to look at the Network settings as well.  Because I'm not sure how long the Network settings take to fully apply, I'll give it a few hours/overnight before testing again.

If it turns out that we need to address the Network settings as well, would you know if there might be a Power IP to whitelist or some such? 😊

**Comment by Jenefer-Monroe** [comment]
I don't understand that world well enough to even guess. However, if you still need help we can get you a repro outside the kit, which will be quite easy to do, and you can use that to return to support with that.

**Comment by DCC-DM** [comment]
Well, I think that's the Network settings confirmed.  I can no longer store the environment variable.  So adding "Dataverse" to the IAM roll along with the service accounts would work if it wasn't for the limited Network settings.

I doubt the business will be happy about opening that up to all pubic addresses, so we'll need to find out if Power Apps has a public IP we can whitelist specifically.

I'll get back to Premier Support now (wish us luck!), but thank you so much for your assistance with this 😊

**Comment by petepuu** [comment]
@DCC-DM  the network requirements are mentioned in the Use environment variables for Azure Key Vault secrets doc and there is a link to Power Platform URLs and IP ranges. CoE reads the Key Vault value in the flow, so you most likely need to allow Power Automate URLs and IPs in the Key Vault firewall https://learn.microsoft.com/en-us/power-platform/admin/online-requirements#urls-for-power-platform-services

_If you have enabled [Azure Key Vault Firewall](https://learn.microsoft.com/en-us/azure/key-vault/general/network-security) you'll have to allow Power Platform IP addresses access to your key vault. Power Platform isn't included in the "Trusted Services Only" option. Hence, refer to [Power Platform URLs and IP address ranges](https://learn.microsoft.com/en-us/power-platform/admin/online-requirements#ip-addresses-required) article for the current IP addresses used in the service._

https://learn.microsoft.com/en-us/power-apps/maker/data-platform/environmentvariables-azure-key-vault-secrets#configure-azure-key-vault

**Comment by DCC-DM** [comment]
Thanks @petepuu.  The Microsoft Engineer got back to me in the end linking us to the page of IP addresses/ranges the same as above.  I've since run it by senior Org/Operations management and they aren't happy just blanket whitelisting so many addresses.  They'd rather target only those required, so it looks like I'll have to put in a bit more legwork yet 😔

@Jenefer-Monroe Our Microsoft Account Manager said to mention that the Microsoft Engineer supporting us with this case is Tumu Nirosha.  They're still continuing to assist at present.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
