### ISSUE TITLE
[CoE Starter Kit - BUG] Total Shared With PBI Report not accurate

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8379]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The total shared with column under App Deep Dive using the PBI report is not accurate. All apps are showing 0 where in the Power Platform Admin View is showing the correct amount. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/7e128a8a-10ec-47d6-aa46-6e0a53951850)

### Expected Behavior

PBI Report should reflect accurate numbers

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Production PBI Report

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3403

**Comment by nasilvae** [comment]
> Have you run the flow which collects this since your upgrade? CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

Its a new installation. The Power Platform Admin view shows the right information though.

**Comment by Jenefer-Monroe** [comment]
Which PBIT file did you use?

**Comment by nasilvae** [comment]
> Which PBIT file did you use?

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/eae660b2-99a4-49de-8684-9ef12ed80acb)

**Comment by Jenefer-Monroe** [comment]
I dont repro. I presume the thing in the Power Platform Admin View you are seeing is the old way we used to track total users. Its a new field now. 
Please run **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_** now that your inventory is in place, and see if that populates.

**Comment by mwebervz** [comment]
I'm seeing the same issue. Total Shared is 0 but the flow ran initially two weeks ago when I manually started it as well as again 4 days ago.
![flowruns](https://github.com/microsoft/coe-starter-kit/assets/132452167/1a4f7295-2818-4153-aee7-a3ee2e3d1fad)

**Comment by mwebervz** [comment]
I wonder if the Power BI is pulling in the deprecated column as I so do see total counts in the new column. I'll run this down:

![Total Shared](https://github.com/microsoft/coe-starter-kit/assets/132452167/1c5d373a-3012-406c-819e-e837e6c9ba68)

**Comment by Jenefer-Monroe** [comment]
You're right, it looks like I was the one with the stale data. Will fix up for next release. 
Thanks for posting and commenting.

**Comment by mwebervz** [comment]
Final comment. See attached. Looks like both Power BI and flow will need some troubleshooting. 
- The shared counts are not making it into the admin_appsharedusers column on the PowerApps Apps table for a given app.
- The Power BI may be still using the deprecated total shared column.
[Not Populating Total Shared.docx](https://github.com/user-attachments/files/15821552/Not.Populating.Total.Shared.docx)

Can you let me know the version of CoE that does not have this issue? I may rollback with a client.

**Comment by mwebervz** [comment]
Here are some more findings.
[Not Populating Total Shared.docx](https://github.com/user-attachments/files/15821646/Not.Populating.Total.Shared.docx)

**Comment by Chandra1247** [comment]
@Jenefer-Monroe Quick question on the new App shared users. How it recalculates groups users ?
it my case it is showing 100 for one of the group but it has more than 100. I also noticed it checks the count of only new group.

**Comment by Jenefer-Monroe** [comment]
This 100 limit was due posted by another person and fixed for July release as well. Please see https://github.com/microsoft/coe-starter-kit/issues/8475

**Comment by Chandra1247** [comment]
@Jenefer-Monroe 
Thank you. I will upgrade it to July release. Quick question will the July release update existing group member count to the table.

**Comment by Jenefer-Monroe** [comment]
Wonderful, it should be shipping next week. 
These will update in the **_Power Platform User_** table on the next run of **_CLEANUP - Admin | Sync Template v3 (Orphaned Users)_** after upgrade to July
