### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to Use the Business Area Feature ?

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#8380]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I have been wondering about this feature available in Admin View for a while now, and I can't find any documentation about it. I have several questions.

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/b4b4fe7e-a6bb-4b92-abfa-a8699048ccee)

- What is the purpose of this feature?

- Why should it be used? What scenarios does it address?

- Do Business Areas correspond to my work department whose property is present in Entra?

- If so, is there a way to synchronize departments with Business Units, perhaps through a flow?

Sorry for all these questions, but I think this feature is interesting, and it would be a shame not to use it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2024

### What method are you using to get inventory and telemetry?

None

AB#3404

**Comment by Jenefer-Monroe** [comment]
Hello, there is no automation around this, no. It's simply a way for you to classify your objects.  You can create business areas and then link them with environments for your own reporting. 

I think it was an ask we did very early in the kit's creation and then it never took off. So feel free to make it your own!

**Comment by tocri** [comment]
Thant you @Jenefer-Monroe 

i have added 2 BU and I would like to tag an app or a solution to one of this BU 

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/aaddacec-b6c3-49fb-9a5e-495601fde665)

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/bac99ce6-1c9c-4c3e-be73-0db78cce3da2)


But i don't find where i can put the value. My idea is to classify all the solutions that made by BU

**Comment by tocri** [comment]
Oh no, that's sad. It will be very interesting (i suppose) to classify solution by BU. Maybe one day.
By the way, thank you for your very quick reply
