### ISSUE TITLE
How to find the URLs that are used within a "HTTP with Entra ID" and SQL servers referenced in SQL connections

### ISSUE THREAD

**Issue by gghaleb** [microsoft/coe-starter-kit#8381]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, is there a way we can through the CoE, now or in the future, find the URLs that are used within a "HTTP with Entra ID" in our tenant for example or the SQL server name used within a SQL Server connector? We are trying to avoid going and open each identified flow related action or app connexion individually.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3405

**Comment by Jenefer-Monroe** [comment]
We do not have this today, no. And I don't know how we would fetch this data. If people have ideas of how to gather this information, I'm happy to add to the backlog for implementation.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
