### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Email Managers Ignored Inactivity notifications Approvals

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#8382]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

We received below email on Monday. 
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/aa379379-6822-401a-ba8d-0800444a5424)

Except 4 flows the other two flows have owner.  Why these two flows included in this email?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3406

**Comment by Jenefer-Monroe** [comment]
When you say they have an owner, can you please show me what you mean? Note that the product implemented the notion of an owner recently that we have not yet incorporated into the kit (targetted for next month). 

Plesae check to see what they are marked for owner both in the product :
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/817c9fc6-5c69-4b6d-8a2c-89fccf482bdb)

And in the inventory:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66f56996-5934-40d3-9d30-1e47a9bfd542)

**Comment by lingutla123** [comment]
Hi Jenefer,

These flows created our Employees. I don't see the 'Primary Owner' on the flow. This flow is shared with 'Sheryl'.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/f56d912b-3943-4055-acf8-8e8e38a15f2e)

I can see the owner in Flows details.

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/b89a0209-e6cd-40e1-b67a-06399d4cb7da)
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/4deef94d-a79d-4d77-ab58-023f217ec9ce)


Other Flows have Owner is Service account. I can't see Christine's flow. She is out of office.
 The other flow Owner.
![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/c5949257-19f5-42fe-ac9a-204a141cb81a)

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/c44063d9-0253-41bd-b786-fda2a33c1e0a)

Thank you.

**Comment by Jenefer-Monroe** [comment]
Yes thats correct we do not look for co-owners in that flow at this time. 
It is on the backlog to do so.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
