### ISSUE TITLE
[CoE Starter Kit - Feature]: Configurable Owners of resources

### ISSUE THREAD

**Issue by birgeravo** [microsoft/coe-starter-kit#8386]
### Is your feature request related to a problem? Please describe.

When a maker that owns model driven apps leaves the company or the original maker is no longer the one maintaining the resource, we don't have a way to register this in the toolkit. Especially for model driven apps, copilot bots and solutions this would be useful. For flows and canvas apps we have the option to change ower / recreate flow.

### Describe the solution you'd like

Clearly defined fields in the toolkit to define current owner or use som clearer term. Inactivity flow/compliance etc. should use this value when sending messages.

### Describe alternatives you've considered

Tried to change owner of model driven app in dataverse, but apparently not possible. I guess the automated sync flows will owerride any changes I make to the owner field in admin_app and admin_bot.
We are making a separate table to store this information on a meta level as well, but that is only intended for larger solutions where we have multiple stakeholders.

### Additional context?

Possibly related to #8258

AB#3410

**Comment by Jenefer-Monroe** [comment]
Hello, thank you yes the product itself does not offer an owner concept for these, only a "creator". 

We do have adding a concept of "Derived Owner" on the backlog for these but its not targetted for the near term.

I do also suggest adding this as a product request in the user community: https://powerusers.microsoft.com

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
