### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE flow Admin | Gather Tenant SRs failing

### ISSUE THREAD

**Issue by AzizAQureshi** [microsoft/coe-starter-kit#8387]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have a CoE flow 'Admin | Gather Tenant SRs' is failing. Here is the snapshot of the error:

![image](https://github.com/microsoft/coe-starter-kit/assets/167378166/59975f1e-2d71-4906-b3a0-92c977070184)

The error is:
'The user is not a member of the organization.'

Who is the user that is not a member of the organization? e.g. is it the service account?

Please advise. Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Gather Tenant SRs

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3411

**Comment by Jenefer-Monroe** [comment]
Please find if the user running the flow is a Sys Admin in the environment that is failing. Meaning this one: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cc72b85a-9853-40a4-ba6e-94dc03a1bd58)

**Comment by AzizAQureshi** [comment]
Is there a way to make sure that the environments that are created has full access to the service account?
Do we have to manually add the service account to each environment that we create?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
