### ISSUE TITLE
[CoE Starter Kit - BUG] Register for Upcoming Event not working

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#8388]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello CoE Team,

Hope all is well. 

I'm using the "Nurture apps - Maker" app.

I'm trying to register for an event as if I was a maker, but when I click the register link and the custom page pops up with the "Register" button, whenever I click that button nothing happens. Tried with 2 different user accounts. I'm using latest version of Google Chrome, logged in and out over different days. 

![image](https://github.com/microsoft/coe-starter-kit/assets/68440710/31e9f8e4-bebb-4463-8a54-73e3414c596f)

Also, the three Flows in this [documentation](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#turn-on-flows) are enabled.

Any thoughts on why this is not working, please?

Thanks very much,

Garry

### Expected Behavior

If I click the "Register" button I'm registered.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.17

### What app or flow are you having the issue with?

Nurture apps - Maker

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Go to "Nurture apps - Maker" app,
2. Click "Upcoming Events" in the navigation pane,
3. Find an event and click the "register" link,
4. A custom page pops up with the "Register" button,
5. Click the button, nothing happens, no confirmation screen or error screen or email sent.

AB#3412

**Comment by Jenefer-Monroe** [comment]
Hello, there was a product change that broke the Creator Kit components we are using here. 
Please see https://github.com/microsoft/coe-starter-kit/issues/8350 for our version of the bug. I just got a drop and will be able to fix for the June release.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
