### ISSUE TITLE
Command Center App > Get M365 Service Messages flow is not capturing the variable (App ID)

### ISSUE THREAD

**Issue by SivarajDheeksha** [microsoft/coe-starter-kit#8390]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In COE Admin Command Center App, the Message center is not populating the messages. So I checked the flow 'Command Center App > Get M365 Service Messages' flow and noticed that the variable (theAppID) initialized within the flow is not capturing the App ID. As per the articles and the checks that I have made, I believe we have all the pre-requisites in place.
![MessageCenterError_Coetoolkit](https://github.com/microsoft/coe-starter-kit/assets/167132858/3e1bb2e0-dedc-43f3-ac1c-8a0139d83d7b)
![MessageCenterVariable_CoeToolKit](https://github.com/microsoft/coe-starter-kit/assets/167132858/9d4dae99-cb44-4c74-b380-877746418c93)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Command Center App > Get M365 Service Messages

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3414

**Comment by Jenefer-Monroe** [comment]
Please go up to this part of the code. Is it filled with the app registrations application (client) id?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca587ab1-cbbb-402f-853b-fdaee1379a13)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66742436-972f-487b-9a05-99890e51cfc9)

**Comment by SivarajDheeksha** [comment]
![MessageCenterFlow_Coetoolkit](https://github.com/microsoft/coe-starter-kit/assets/167132858/353b216b-5bf6-439f-b228-07a3154c8755)
The condition is false and the app value is still empty.

**Comment by Jenefer-Monroe** [comment]
OK it looks like you did not update the environment variables then. 
Unfortunately there is currently a product change which broke our tooling to update them, so you'll need to do it manually. 

Please update the env vars described here: [Update environment variables](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#update-environment-variables)

Using this technique [How to update environment variables](https://learn.microsoft.com/power-platform/guidance/coe/faq#update-environment-variables)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8bb2d53d-58c0-4c9d-8273-2d1beb7b815d)

**Comment by SivarajDheeksha** [comment]
Hi Jenefer, is it mandatory to have Azure Key Vault to get Message Center updated? 
For the audit logs, I am using only client ID and client secret.

**Comment by Jenefer-Monroe** [comment]
No its not. You can use the text secret. That is just showing you that you have to go to the Default envt and add the secret (text or Azure).

**Comment by Jenefer-Monroe** [comment]
Great now please rerun that flow

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
