### ISSUE TITLE
[CoE Starter Kit - QUESTION] Maker Assessment Excel Sheet with Example Questions

### ISSUE THREAD

**Issue by Tylerman012** [microsoft/coe-starter-kit#8391]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello Everyone!

I am going through the COE Starter Kit and after reading through the documentation I am wondering if anyone here has a hold of or knows where I can find an excel sheet with example questions for the Makers Assessment. I have heard word of this excel sheet but I cannot find it through all of my research online, looking through blogs, YouTube videos, etc.

I wish I had more information about this excel sheet that I am searching for but I only have word of mouth hearing about so sorry about if my question seems like a wild goose chase!

Thanks

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3415

**Comment by Jenefer-Monroe** [comment]
Hello, when you download the coe starter kit (https://aka.ms/coestarterkitdownload) and extract all, you will see the file in there
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4a1702a2-4190-416c-b7a1-9e2b3cb7fcc0)

Please let me know if that's what you were referencing.

**Comment by Tylerman012** [comment]
That is what I was looking for! Cant believe I didn't think to check there. Thanks so much!
