### ISSUE TITLE
CoE -  Innovation Backlog component 

### ISSUE THREAD

**Issue by johnpenagoscabrera** [microsoft/coe-starter-kit#8392]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am dabbling in power platform CoE implementation.

I have a question regarding the implementation of the Innovation Backlog component and the licensing required for its use.

I have downloaded the component and installed it following the installation and configuration steps. I have been able to get it working, but only with the user who has a premium license.

For other users who have E5 and E3 licenses, the component does not work, and a message appears indicating that they do not have the required license.

Is there any document that can guide me in the required licensing and configuration?

Thank you in advance for the support you can give me.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3416

**Comment by Jenefer-Monroe** [comment]
Hello, all apps in the kit rely on the Dataverse connector, including the Innovation Backlog. 

As a result they require the Premium license for users, or to have a per-app license on the app itself. 

Unfortunately the license topic is quite complex and I am not an expert so I'm not able to assist with the best way to get their for your organization. 

Please see https://learn.microsoft.com/en-us/power-platform/admin/powerapps-licensing-faq
Or talk to your account rep if you have one.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by johnpenagoscabrera** [comment]
thanks...
