### ISSUE TITLE
[CoE Starter Kit - QUESTION] Use of Global Admin vs. Power Platform Admin installation

### ISSUE THREAD

**Issue by vicksoulios** [microsoft/coe-starter-kit#8394]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi guys,

My team and I are working our way through the CoE Starter Kit installation and noticed that a Global Admin is required to register **HTTP with Microsoft Entra ID** connector.

1. Does the Global Admin used to register the HTTP with Microsoft Entra ID connector need to have [consistent Power Apps Premium and Power Automate Premium Licensing](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with) assigned at all times?
2. Can you get away registering the **HTTP with Microsoft Entra ID** connector with using a service account that only has the Power Platform Administrator role assigned, and not a Global Admin role?
3. When it comes to working through the rest of the install after registering the HTTP with Microsoft Entra ID connector, can use a [Power Platform Administrator](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup) with the appropriate Power Apps and Power Automate Premium licensing to install the rest of CoE Stater Kit?

So, in the above scenario, is the best practice approach to use two service accounts (a Global Admin for the HTTP with Microsoft Entra ID connector and a Power Platform Administrator for the rest) with Premium Licensing assigned to each account?

Thanks for your time and help. Kind regards,
VS

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#3418

**Comment by Jenefer-Monroe** [comment]
Hello, I'm not sure what you mean about registering the HTTP with Microsoft Entra ID connector.

The only thing you need the Global admin for in the kit is for granting admin consent for the app registrations (ex in [Audit Logs setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http))

Everything else can be setup, configured, and run as the Power Platform Admin Role. 

It could be that you are being bit by the old documentation issues (which are finally local fixed and in review). I know some places still did not clarify that its the preauth version of that connector that you need:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9217d78d-d30c-4263-ac96-9bda796c6987)

**Comment by vicksoulios** [comment]
Thanks Jenefer!

We'll give it another go and setup the **HTTP for Entra ID (preauthorized)** connector with a Power Platform Admin user - if we don't get a warning around running PowerShell to authorize the connector, then it'll be a good sign and we'll proceed with installing the CoE under a Power Platform Admin service account.

You're right about the documentation. It looks like the documentation makes mention of [**HTTP with Microsoft Entra ID**](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections), has a screen shot   of a connector that refers to **HTTP with Azure AD**, and when you click the [**HTTP with Microsoft Entra ID** link in the page](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections), it takes you to the [HTTP with Microsoft Entra ID (preauthorized)](https://learn.microsoft.com/en-us/connectors/webcontents/) documentation. 

There appear to be two HTTP with Microsoft Entra ID connectors. One that has (preauthorized) after its name and one that doesn't (which requires manual authorisation, via PowerShell); but I can now see that the documentation is referring to the preauthorized version of the connector.

Thanks for your help. We'll give it a go.
