### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Administration Planning.pbit | The key didn't match any rows in the table

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#8396]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello CoE Team.

I hope you are well.

I've seen this error "The key didn't match any rows in the table" on other tickets raised for other reports, but couldn't find it for the "Power Platform Administration Planning.pbit".

When I first open Power BI Desktop with the file I get this error.

![image](https://github.com/microsoft/coe-starter-kit/assets/68440710/3668e0b6-ba53-4c66-9272-bee99986e7ae)

I click "Refresh now" and get the below error.

![image](https://github.com/microsoft/coe-starter-kit/assets/68440710/8421fdaa-bfde-404e-8444-546929159388)

When I look at the "Model view" I see this warning.

![image](https://github.com/microsoft/coe-starter-kit/assets/68440710/9f63761d-4922-4f22-a562-cf44400c52be)

Here's a screenshot of solutions imported, as I saw you asked for this on other tickets.

![image](https://github.com/microsoft/coe-starter-kit/assets/68440710/24358b53-b95f-46b5-8b42-158ce99d84d1)

PowerBI is not my strongest skill, so any help would be greatly appreciate.

Thanks very much,

Garry

### Expected Behavior

Power BI report to have no errors.

### What solution are you experiencing the issue with?

Admin Task Planner

### What solution version are you using?

1.3.20230724.1

### What app or flow are you having the issue with?

Power Platform Administration Planning.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. open Power BI Desktop with the file "Power Platform Administration Planning.pbit"
2. Click "Refresh now" on any notifications.
3. Receive the below error.

![image](https://github.com/microsoft/coe-starter-kit/assets/68440710/8421fdaa-bfde-404e-8444-546929159388)

AB#3420

**Comment by Jenefer-Monroe** [comment]
Hello, have you completed the setup instructions here? 
https://learn.microsoft.com/power-platform/guidance/coe/setup-admin-tasks-component

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe,
Yes, all the setup steps have been completed. before I got this error.
Thanks,
Garry

**Comment by Jenefer-Monroe** [comment]
Do you see the data if you browse in the solution to the table? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/16187e7f-b8e4-4799-aecf-da0fd7d96c4a)

If you adjust the columns do you see the Frequency column filled? Perhaps the data ingest did not map correctly?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8a5e5dd1-9536-4fc2-8fb6-a66212595607)

**Comment by GarryPope** [comment]
Good morning @Jenefer-Monroe,

Thanks for the reply. Please see image below showing data in that column.

![image](https://github.com/microsoft/coe-starter-kit/assets/68440710/5a9828ed-b9a2-4f25-80b0-62fbbaeb231d)

Thanks,

Garry

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe,

Thanks for the advice. 

I deleted the data and the Power BI report, then imported the data and opened the Power BI report again, and saw that it didn't ask me for the URL, so once I configured that in "Transform Data" it worked a treat.

Sorry to have wasted your time. Please close the ticket and have a good day!

Garry

**Comment by Jenefer-Monroe** [comment]
No worries at all, we are happy to help. So glad we got it working! 
Will go ahead and close but please feel free to raise other issues in the future as needed.

**Comment by rmedrano2** [comment]
Just wanted to add that I ran into this issue after deploying to our test environment yesterday. I was never prompted for the environment URL.  I was able to set it manually, which after doing so allowed the report to function without throwing the error. But before that was basically stuck because the report would not allow itself to be saved while the error existed.
