### ISSUE TITLE
[CoE Starter Kit - BUG] Missing Informations

### ISSUE THREAD

**Issue by AbderBPCE** [microsoft/coe-starter-kit#8398]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

we coudn't find some infos related to the admin Flow_lastRunOn as well as the AdminApplastLunchtime ; it's always blank and it's not normal.
We need those informations on our side in order to create cloud flows for our cleaning environnement strategy.
On top of that we would like to know were to find the names and mails of the people to whom the objects , weather it be Apps or flow are shared to besause the number of share is not enough.
And we have this flows already on : 
![MicrosoftTeams-image (2)](https://github.com/microsoft/coe-starter-kit/assets/169038982/fa4514c5-c09c-43b1-98c3-723cd61e7e6d)

thank you for your help.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

power automate

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3424

**Comment by Jenefer-Monroe** [comment]
Flow_lastRunOn being blank is normal. It is not yet populated for the cloud flow architecture but we do hope to be able to fill it after the product team finishes a blocking feature. Hopefully late in the summer or early fall.

**Comment by Jenefer-Monroe** [comment]
For AdminApplastLunchtime, is that running for you hourly? I ask because it shows a last run of a date from a few weeks ago. 
Did you do this setup work? https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http

**Comment by AbderBPCE** [comment]
yes we already had this setup work and the problem is that we have informations for some apps and flows and not for the others

**Comment by Jenefer-Monroe** [comment]
For last launched, you will not have that information for anything that was last launched before you turned on the audit log flows.

Here is some information on [How to get older data](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#how-to-get-older-data)

However the audit logs themselves do not retain information for very long.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
