### ISSUE TITLE
Inactivity flow excludes "stopped" flows

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#8399]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, 

"stopped" Flows are excluded from Inactivity-Process. Is there a reason why?
<img width="823" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/62603605/400d493a-c1f8-436c-9641-4569222fe340">

Could I just delete this part in the condition to apply it to all flows?

Kind regards
Cathi

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

Admin - Inactivity notifications v2 (Start Approval for Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3425

**Comment by Jenefer-Monroe** [comment]
Hello, yes you can do that and make a local change. I don't know why this decision was made to begin with but having it be configurable is on the list of changes when we redo this feature, hopefully in the fall.

**Comment by Cathi029** [comment]
Ah okay, thank you for the fast response!
