### ISSUE TITLE
[CoE Starter Kit - BUG] Governance Power BI dashboard has lot of blank data

### ISSUE THREAD

**Issue by chandni-agarwal** [microsoft/coe-starter-kit#8401]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Lot of data cards says blank in the power BI dashboard like apps launched in last month or last quarter and many more 
<img width="677" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/23003280/a310456f-1d08-439d-9e12-4addbccf1ad0">

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.16

### What app or flow are you having the issue with?

its PBI template issue

### What method are you using to get inventory and telemetry?

None

AB#3427

**Comment by Jenefer-Monroe** [comment]
1. Is this a new install and has your inventory completed? 
2. Did you use the Setup Wizard to ensure all flows are turned on? 
3. Did you do the setup for Audit Logs? [Collect Audit Logs](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by chandni-agarwal** [comment]
1. Its not a new install, inventory is complete
2. All flows are turned on
3. Yes Audit log with management api permissions are working

**Comment by Jenefer-Monroe** [comment]
Please go to the Power Platform Admin View app, do you see the expected data there? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bb96056c-5909-4274-b343-bbf907554b63)

**Comment by medicineshow** [comment]
I have the same issue. 

1. Its not a new install, inventory is complete
2. All flows are turned on
3. Yes Audit log with management api permissions are working

When I try to install both the Production and PowerPlatform Governance CoE Dashboard I get the same error messages:

![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/f74d40c1-6b6a-4eb3-bd88-f3b9de4109e9)
 then 
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/19bcffe6-bd4f-40e6-9423-224b016e20bc)

**and in the transform data window:**

![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/78a6ec30-e72c-4bc8-9e1f-7983f93915d5)

**The error:**

![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/6e6c8f1d-8e0c-4393-986b-72e1a4987ade)

**Comment by medicineshow** [comment]
@Jenefer-Monroe any update on this?

**Comment by Jenefer-Monroe** [comment]
This does not appear to be the same issue, as the op did not mention issues loading. 
I just tested the PBIT files for June and they do have the parameter correctly included. Were you prompted for an input parameter?

**Comment by medicineshow** [comment]
Yes it is just my dashboard does look exactly the same and No, I was not prompted for an input, it starts exactly as you see it in my first picture. Do you want me to raise a separate issue?

**Comment by Jenefer-Monroe** [comment]
No need, this is a known product issue with PBI that happens sometimes. Someone in the community found the workaround which gets you back to functioning. Please see https://github.com/microsoft/coe-starter-kit/issues/7417#issuecomment-1883545471
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/50bcc31f-4767-4278-98ea-1df868b606a1)

**Comment by medicineshow** [comment]
strange quirk. That has worked thanks.

**Comment by Jenefer-Monroe** [comment]
thanks for that extra information!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
