### ISSUE TITLE
App State is blank- Flows are not capturing App State for PowerApps

### ISSUE THREAD

**Issue by SivarajDheeksha** [microsoft/coe-starter-kit#8404]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In 'PowerApps Apps' data verse table, the 'App State' is not being captured. The entire column in empty. Please help.
![AppStateBlank_CoeToolKit](https://github.com/microsoft/coe-starter-kit/assets/167132858/c55a17b1-3e1e-4ca7-9f73-5d16851ab778)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

AB#3430

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
