### ISSUE TITLE
Newly installed COE Tool Kit's title in Dynamics365 and not PowerApps. Why?

### ISSUE THREAD

**Issue by SivarajDheeksha** [microsoft/coe-starter-kit#8405]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Newly installed COE Tool Kit's title in Dynamics365 and not PowerApps. But in Microsoft articles, we see its PowerApps. Will this be of any concern or limitation? How can we ensure for the title to be PowerApps and not Dynamics 365?
![AppTitle_COEToolKit](https://github.com/microsoft/coe-starter-kit/assets/167132858/96a1347f-df0b-4ea7-adde-18d57f823541)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

AB#3431

**Comment by Jenefer-Monroe** [comment]
I really don't know. That is a string written by the product (similar to the string Sandbox), so I dont know why they would chose to put that there instead.
Perhaps someone else in the community knows? Happy to leave open for a bit to see if others know.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
