### ISSUE TITLE
Can we deploy unmanaged solution using ALM accelerator.

### ISSUE THREAD

**Issue by CharuKumar1412** [microsoft/coe-starter-kit#8406]
Hello team,

I have a requirement where I have one dev env, 3 UAT envs and 3 prod envs. I want to deploy unmanaged solution from Dev to UATs and then deploy managed solutions from UATs to prods. I am currently able to only deploy managed solutions and I dont know how to deploy unmanaged solution. Can you please tell me if this is possible ? If yes, please help me with this setup by explaining me steps or keeping a call with me to understand.

Thanks,
Charu

**Comment by RajeevPentyala** [comment]
@CharuKumar1412 Even though we don't recommend deploying unmanaged solutions in higher environments, you can import unmanaged solutions by passing the variable '**ImportUnmanaged**' as '**true**' in deployment pipelines.

Another option to manually import an unmanaged solution to other environments is to use the 'Import Solution' option as highlighted below.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/e0c24d9b-8b89-4b83-9d91-844338b3066e)

**Comment by CharuKumar1412** [comment]
Hello Rajeev,

Thanks for your response. The issue is that using this I am always able to import only in my dev environment. Is it possible to have a call with you so I can set it up properly please ?

**Comment by RajeevPentyala** [comment]
@CharuKumar1412 It looks like you have not configured the profile with the deployment environments.
Please go through following recordings:
[Recording 1](https://www.youtube.com/watch?v=daK6LuR9Uuk)
[Recording 2](https://www.youtube.com/watch?v=oe7zPIoSWpo)
[Documentation](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/branching-environment-strategy)

**Comment by MaheshSripada** [comment]
Closing this as there is no response. Please reach out if you need further assistance
