### ISSUE TITLE
[ALM Accelerator - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#8407]
### Is your feature request related to a problem? Please describe.

I can't get the actual users from Environment Security Role Permission. The user name is often ambigous, like 3 different John Smiths...

### Describe the solution you'd like

A lookup column from Environment Security Role Permission to Users

### Describe alternatives you've considered

I can try to code to identify that ones that are ambiguous and resolve them manually.

AB#3461

**Comment by RajeevPentyala** [comment]
@RickKush Can you please provide more details so we can better understand your request? Information such as app details or screenshots would be helpful.

**Comment by MaheshSripada** [comment]
Closing this as there is no response. Please reach out if you need further assistance
