### ISSUE TITLE
[CoE Starter Kit - BUG] BYODL_CoeDashboard_May2024 error "The key didn't match any rows in the table."

### ISSUE THREAD

**Issue by briangre** [microsoft/coe-starter-kit#8409]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

During an upgrade from Oct 2023 COE to May 2024, everything goes well except for the refresh of the BYODL Power BI template. I imported the Jan data model (PowerPlatformAdminAnalytics-DF-Jan2024.json) as that was newer than what I had previously and the refresh of the data flow works without error. 

After opening the PBIT and entering the COE URL, PBI workspace ID, PBI dataflow ID, and Tenant type, the error appears on refresh:

![image](https://github.com/microsoft/coe-starter-kit/assets/16060122/81a858ef-2ce4-479a-8c8b-6d7e13d697a4)

### Expected Behavior

The data refresh should complete without error. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

BYODL_CoeDashboard_May2024.pbit

### What method are you using to get inventory and telemetry?

Data Export

### Anything else?

I see a couple of other bugs filed on this, but no definitive resolution. 

AB#3465

**Comment by Jenefer-Monroe** [comment]
We've seen people hit something similar when upgrading with the dataflow. 

Typically I advise you to delete the old dataflow in PowerBi.com, and then make sure that you have taken the new Dataflow ID for the input parameters. That has taken care of it for others.

**Comment by briangre** [comment]
ugh... even though I *thought* i had the correct parameter information, I actually did NOT have the correct PBI workspace ID... user error...  🤷‍♂️
