### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Adds Co-Owners to Flows

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8410]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Does the CoE automatically adds and then remove the main account used for the CoE as a co-owner for flows in the tenant? We are noticing multiple emails regarding the account used in the coe to be added as a co-owner. We are not sure if this is part of the coe automation or something else. 

We have the governance components off. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3469

**Comment by Jenefer-Monroe** [comment]
This happens during the execution of the following flow: **_Admin | Sync Template v3 (Flow Action Details)_**
When a flow contains certain connections (like http connections) we cannot gather some details, like the authentication pattern or the referenced http host, without calling the **_Get Flow_** action as these details are not returned in the **_Get Flow as Admin_** call. 
As a result, we add the identity running the flow, fetch the needed details, and then reset the permissions 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1556f9bb-4ff3-4d77-8479-26431b9d4358)
Unfortunately there is no option to do this without the mail getting sent. 
So if you want to gather the information like the details about flow actions this is just some noise you will need to deal with, perhaps with exchange rules. 
Hope that makes sense.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
