### ISSUE TITLE
CoE is showing over 5,000 apps as deleted but when checking the environments they're still there. 

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#8411]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The lookup field in the Environment Security Role Permission table does not point to the parent record, Environment. You can see in the screenshot that the parent environment is the same for all of the rows shown, but the lookup field value is different for every row, like a rowID.

![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/3170829d-a3fd-49ac-9f2c-b17b5030b184)

### Expected Behavior

I expect to be able to filter the child rows in Environment Security Role Permission based on the Environment ID in the parent, Environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Table and get rows in Flow.

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Make a flow which tries to get the child records based on the parent record.

### Anything else?

I also tested with a hard coded Env GUID, and it failed. 
![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/38210bb8-e0d7-4a5f-ac4f-880e1a4db1fa)

![image](https://github.com/microsoft/coe-starter-kit/assets/116654106/c7e08651-8365-4d93-9190-dda09cdba08f)

AB#3470

**Comment by Jenefer-Monroe** [comment]
Hello sorry I'm not following. The records in this table do reflect the SRs of each environment, and the environment field does correctly map to the environment. 
If you go to the table you can see the environments offered in a drop down of all the collected environments.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e029b41f-f6da-4469-ad95-7983c387e6ad)

Can you please clarify why you think otherwise?

**Comment by Jenefer-Monroe** [comment]
Also this table has nothing to do with apps, and I just re-read your title, so I'm rather confused.

**Comment by RickKush** [comment]
They are just two tables inside of the CoE, and I need to join their data.

From: Jenefer Monroe ***@***.***>
Sent: Tuesday, June 4, 2024 7:56 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] CoE is showing over 5,000 apps as deleted but when checking the environments they're still there. (Issue #8411)

Also this table has nothing to do with apps, and I just re-read your title, so I'm rather confused. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: 


Also this table has nothing to do with apps, and I just re-read your title, so I'm rather confused.

**Comment by RickKush** [comment]
I have spent two days trying to join the two tables on the child lookup field and the parent primary key.

From: Jenefer Monroe ***@***.***>
Sent: Tuesday, June 4, 2024 7:55 PM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Kushner, Rick [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/coe-starter-kit] CoE is showing over 5,000 apps as deleted but when checking the environments they're still there. (Issue #8411)

Hello sorry I'm not following. The records in this table do reflect the SRs of each environment, and the environment field does correctly map to the environment. If you go to the table you can see the environments offered in a drop down of


Hello sorry I'm not following. The records in this table do reflect the SRs of each environment, and the environment field does correctly map to the environment.
If you go to the table you can see the environments offered in a drop down of all the collected environments.
image.png (view on web)<https://urldefense.com/v3/__https:/github.com/microsoft/coe-starter-kit/assets/89584709/e029b41f-f6da-4469-ad95-7983c387e6ad__;!!May37g!LCUcrlLruEcmYVt2BGj6Sn5Vx9NVNB4bZs2dLiLIJc1Wj17duKPdDOIveYlpnOGDOlgg4u0F1chr1IUDnROyfJKncQ$>

Can you please clarify why you think otherwise?

**Comment by RickKush** [comment]
Sorry about the title of the ticket. It is just wrong. I don't know how it got there. Perhaps my browser defaulted it. I see the Environment field in the ESRP table which is fine if you want to join it to the Environment table manually, but it just doesn't work in the List Rows of the Flow.

**Comment by Jenefer-Monroe** [comment]
What two tables are you trying to join and why? All needed joins should be done for you already.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
