### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis - Showing inaccurate details of a DLP policy applied to an Environment

### ISSUE THREAD

**Issue by JanusAllenCapili** [microsoft/coe-starter-kit#8412]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi CoE Team,

We have found this issue on one of the Model-Driven Apps, and maybe it’s a good thing to check and remediate.

We have configured a DLP policy's scope to exclude certain Environments, and excluded our Default Environment on the scope:

![image](https://github.com/microsoft/coe-starter-kit/assets/156774820/11f5f007-887b-4b30-ac61-1969c47082af)

![image](https://github.com/microsoft/coe-starter-kit/assets/156774820/74bbb457-08c9-41b2-bdcc-b0838521df83)

However, when we checked the details on the DLP Impact Analysis Model-Driven App, it is reflecting that the policy is applied on the Environment:

![image](https://github.com/microsoft/coe-starter-kit/assets/156774820/90b33b70-ce0e-4405-b6a1-a11d3e289031)

Most likely that the details on the column should reflect the exact scope to how the policy is applied on a certain Environment. 

Please advise if this is a feature to be checked, or provide inputs on how to better configure the details on the app to reflect the accurate details.

Appreciate your response.

### Expected Behavior

It is expected that the appropriate details of the scope should be indicated so as to avoid confusion of the DLP settings applied when reviewing a DLP applied to a specific Environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

AB#3471

**Comment by Jenefer-Monroe** [comment]
I believe this was a known and recently fixed issue but Gulzar please work with this user to validate

**Comment by gulzarudheen** [comment]
@JanusAllenCapili I believe that you are updating a policy from PPAC and found it is not updated in CoE DLP Impact analysis app, it is working as expected now. Kindly update your CoE version to latest release and test it.



![Image](https://github.com/microsoft/coe-starter-kit/assets/149140128/cf744307-6a01-42f5-bcb5-37e2994cb5d9)



![Image](https://github.com/microsoft/coe-starter-kit/assets/149140128/87f6cad2-db66-4cf9-86ca-7f0edbd79527)

**Comment by JanusAllenCapili** [comment]
Thanks @gulzarudheen . I will revert back for any other inquiries. Until then, I will update the CoE on our Dev Environment to check on the updated version of the DLP Impact Analysis App.

**Comment by JanusAllenCapili** [comment]
Hi @gulzarudheen ,

I have updated the CoE on our Dev Environment and checked on the DLP Impact Analysis App.

It seems there is still a bug in the App, where it shows incorrect details of the DLP policy applied to the Environment. Here is an example:

- I searched for "Personal Productivity (Default)" Environment to check for the DLP policy applied into it. Here, it shows the policy applied on the "Applied Policies" tab:

![image](https://github.com/microsoft/coe-starter-kit/assets/156774820/10570098-9673-4259-85d3-1763ec0032d4)

- However, upon viewing the Power Platform Admin Center, this Environment is excluded from the policy.
![image](https://github.com/microsoft/coe-starter-kit/assets/156774820/2cd3e2a1-f583-4a59-83c4-86ad2daa2bb5)

- Even on the DLP Impact Analysis App, it shows that it's excluded from the policy:
![image](https://github.com/microsoft/coe-starter-kit/assets/156774820/ea1f8d1b-1a89-4347-b6a0-cc13672e5bc2)

So, the expected outcome in the details is that it should reflect the correct info, where in this case, "Personal Productivity" is excluded in the policy. It should not show that the policy is applied to the Environment to avoid confusion. Or if its excluded, the policy should not reflect on the list.

Let me know if it makes sense or if you need further info.

Thanks in advance.

**Comment by JanusAllenCapili** [comment]
To add further details, it shows the correct configuration for that Environment when I edit the DLP policy on the DLP Impact Analysis App:

![image](https://github.com/microsoft/coe-starter-kit/assets/156774820/9ebbc22a-7f8e-4874-bd0e-ae3095e136c0)

However, when I go to the main dashboard of the app, and search for the same Environment, the details showing on the "Applied Policies" tab seem to show the incorrect info. It states that the policy applies to the Environment. 

Shouldn't it show the appropriate details that its excluded?

![image](https://github.com/microsoft/coe-starter-kit/assets/156774820/ab0807e2-0b5d-40c8-9d98-7ff90d453a30)
