### ISSUE TITLE
[ALM Accelerator - BUG]: GetEnvironmentSolutions error, failed to install flow

### ISSUE THREAD

**Issue by scjrowlands** [microsoft/coe-starter-kit#8413]
### Describe the issue

I have the following error when running the ALM Accelerator app: GetEnvironmentSolutions.Run failed: {"error":{"code":"0x80048d0b","message":"Failed to install the flow"}}

Accelerator version: 1.0.20240104.1

I've seen other posts about this general issue with calling flows directly within powerapps, I assume its some sort of permissions issue ?

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20240104.1

### Steps To Reproduce

App startup fails

AB#3476

**Comment by RajeevPentyala** [comment]
@scjrowlands Can you confirm if this is a transient issue or if it is persisting? I recommend testing the **Solution** table fetch using WebAPI to ensure the calling user has sufficient permissions.

![image](https://github.com/microsoft/coe-starter-kit/assets/104883923/2f30dcf4-69f0-44be-b069-cecc18dc75da)

**Comment by scjrowlands** [comment]
It was a permissions issue - i switched the connection reference used by the GetEnvironmentSolutions flow to use a different account. All good now.
