### ISSUE TITLE
[CoE Starter Kit - Flow Derived Owner Field in CoE Starter Kit flows

### ISSUE THREAD

**Issue by astar01** [microsoft/coe-starter-kit#8415]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What is the difference between the fields Flow Maker and Derived Owner? How is the Derived Owned field updated? Can I update the Derived Owner field and it won't be overwritten by the sync flows?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#3478

**Comment by Jenefer-Monroe** [comment]
Hello. Flow ownership is a bit tricky. 

In the past, flows had no concept of owner, they only had Creator. 
So we added the concept of Derived Owner to allow you to give ownership to someone within the context of the kit. This field is kit only, the product does not us or update it. 

Recently, the product team did add a feature such that solution aware flows now do have the concept of owner. While non-solution flows still do not. 

So : 
- for flows in a solution, please use the product itself to update ownership, we will be updating Derived Owner with this soon (my next work item).
- for flows not in a solution, you can continue to update Derived Owner field. We will use it for things like inactivity and orphan checks. 

Hope that makes sense.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
