### ISSUE TITLE
DLP - Test and fix search, panel, and dialog behavior

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#8419]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Some product behavior broke search, panels and dialogs recently.
I have attempted to fix this for you but please test for July release.

1. Install latest creator kit
2. Get latest CoE unmanaged
3. Browse to DLP app
4. Test all screens and controls

NOTE : you have to test in the player itself (not from the Maker, everything still works there.)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

DLP Editor

### What method are you using to get inventory and telemetry?

None

AB#3482

**Comment by gulzarudheen** [comment]
@Jenefer-Monroe Tested the app, found below issue that on load of the control no records are displayed by deafult though there are records, it is displayed when we search with some characters in search box. 

<img width="923" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149140128/6286727f-52b1-4d65-a51b-823b186e46a4">

<img width="801" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149140128/d2998a50-2e34-4185-8145-7a8cb73c0f9c">

**Comment by gulzarudheen** [comment]
This issue is fixed now. 
<img width="832" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149140128/7d549ad3-3bb7-4c6e-8141-5ce11893b329">
