### ISSUE TITLE
Envt Request - Test and fix search, panel, and dialog behavior

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#8420]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Some product behavior broke search, panels and dialogs recently.
I have attempted to fix this for you but please test for July release.

1. Install latest creator kit
2. Get latest CoE unmanaged
3. Browse to Envt Request apps (both admin and maker ones)
4. Test all screens and controls

NOTE : you have to test in the player itself (not from the Maker, everything still works there.)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Envt Request

### What method are you using to get inventory and telemetry?

None

AB#3483

**Comment by gulzarudheen** [comment]
@Jenefer-Monroe Tested the app, there was an issue with side pane in app that 'Cancel' or 'Next' button was not working. Issue is fixed now.
<img width="333" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/149140128/f69fda01-e25e-40dc-9c79-9332d9885b71">
