### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by leighmilbourne** [microsoft/coe-starter-kit#8422]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

 I am trying to use the COE for tracking storage consumption growth and ensuring we are staying within the platform tenant licensed storage, but the actual consumption in the CoE environment capacity record is always higher than what is reported in power platform admin center. Is this a bug or can you please explain why there is a difference - from my analysis it doesn't appear to be due to Power Platform only "refreshing" the useage numbers periodically.

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#3485

**Comment by Jenefer-Monroe** [comment]
We take these numbers directly from the product's connector, and its updated weekly. So the product may have differences in the way it reports in the UX and the way it reports by the connector. 

Not sure what build you are on, but in current builds. 
Here is the flow that collects them: CLEANUP HELPER - Environment Capacity
Its called once per week by this flow: CLEANUP - Admin | Sync Template v4 (Other Objects)

Here is where we get the capacity information:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5b64a6c9-4993-4e5c-81d7-a304b128559b)

Then we send to the child which parses and populates our tables: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a8d4f180-3b58-48f1-af35-0b735e90b114)

I would suggest exploring these and seeing what the product offers for capacity compared to the ux. 
If it appears to be a delay you could run the flow more frequently, and if it appears the product is returning different information then I"m afraid a call to product support will be the next step.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
