### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flag any apps/workflows as inactive or non-compliant.

### ISSUE THREAD

**Issue by Voidyyyy** [microsoft/coe-starter-kit#8423]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi @Jenefer-Monroe,I have a question regarding how I as an admin can manually flag any apps/workflows as inactive or non-compliant using CoE toolkit?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3486

**Comment by Jenefer-Monroe** [comment]
Hello, we do not have this today for the inactivity feature. We do have it on the backlog though for when we redo this feature area.

For compliance, all features have this capability as shown here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc034eb9-8e5d-4f30-ab15-adf6fab08fa1)

Hope that helps.

**Comment by Voidyyyy** [comment]
Thanks, @Jenefer-Monroe, I also have one more issue my Admin Sync template v3 for PVA is throwing error for all personal productivity environments. So is it because of the environment or something else. Below I've attached the screenshots for your reference.
![PVAError0](https://github.com/microsoft/coe-starter-kit/assets/72079788/26befb56-4286-4986-a237-1f30c2c1b48d)
![PVAError1](https://github.com/microsoft/coe-starter-kit/assets/72079788/983e484b-6758-4d19-8e59-64bc5033bc70)
![PVAError2](https://github.com/microsoft/coe-starter-kit/assets/72079788/cbe3d91a-8485-42d4-b82d-f9be67511bc7)


Thanks again,

**Comment by Voidyyyy** [comment]
Yeah sure I will. Thanks for the help I'm closing this one.
