### ISSUE TITLE
[CoE Starter Kit - BUG] Imported + not started flows have no owner

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#8426]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
i've recognized that a few of my flows are displayed without an owner in the dashboard or admin view app.
These flows have in common that they are imported and have not been active.
The problem seems to be that the Get Flows as Admin action of the Power Automate Management connector does not return any creator information for these flows.

### Expected Behavior

Also for these flows the owner should be displayed

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Import solution with deactive flows in environment
2. Let the inventory run
3. Check the Owner

or

1. Import solution with deactive flows in environment
2. Note flow and env Id
3. Test the Connector
![image](https://github.com/microsoft/coe-starter-kit/assets/113470539/c14cef5a-dc1b-40de-a825-c3268bbf54ae)

### Anything else?

I've not witnessed this with the previous design of the SYNC HELPER - Cloud Flows flow (Core V. 4.22)

AB#3492

**Comment by Jenefer-Monroe** [comment]
What region are you in? We did work with the product team to fix this before they re-shipped unpublished flows so I will be sad to see this. I

**Comment by lukas-nC** [comment]
Europe

**Comment by Jenefer-Monroe** [comment]
Thank you, it looks like they changed the property to look for to detect unpublished.

Fix is to update the following filters to this expression, hit Edit in advanced mode and put this:
`@equals(equals(item()?['name'], item()?['properties/workflowUniqueId']), true)`

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c54e7515-08e9-4ee5-b328-c8850cd42d99)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3e033916-a284-4109-b88b-3ddccf24cda1)

**Comment by Jenefer-Monroe** [comment]
testing for June release

**Comment by Cathi029** [comment]
Hi, I importet the June release today, I triggered the Driver-Flow, but the Kit-Flows are still "orphaned" in the Manage Permission App. 
<img width="300" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/62603605/cdde4528-2ff8-4461-a87f-6958d913a0b1">

**Comment by Jenefer-Monroe** [comment]
Shipped with the wrong expression above, sorry.  (fixed above too to avoid people copy/pasting wrong)

Expression is `@not(equals(equals(item()?['name'], item()?['properties/workflowUniqueId']), true))`
In these two places:

![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b9fc5c74-5595-4fe8-aa15-3dea3cd45449)
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d6ab0421-4512-4e76-bfed-a91d1481724f)

**Comment by Jenefer-Monroe** [comment]
And this build does not take in unpublished flows, that will require additional work, so after the next run of Check Deleted these will be cleaned up and removed from inventory. Note that these unpublished flows were always a limitation because they were never returned from the product until this change that just broke us

**Comment by Cathi029** [comment]
Hi Jenefer-Monroe, thank you for your help!

**Comment by Jenefer-Monroe** [comment]
OK thank you for your help on this one. I have re-shipped with this fixed as 4.32.2
