### ISSUE TITLE
[CoE Starter Kit - BUG] Flow Run dataverse table is blank in our COE

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#8427]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow Run dataverse table in our COE is blank. Please let us know should we turn on any specific flows to capture the data into Flow runs table.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Dataverse

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Flow Run dataverse table in our COE is blank. Please let us know should we turn on any specific flows to capture the data into Flow runs table.

AB#3496

**Comment by ALSPowerPlatform** [comment]
<img width="317" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/106515181/cbe1df03-3578-450f-bab6-78a75f6797e1">

**Comment by Jenefer-Monroe** [comment]
This table has never been filled and has been deprecated. 
We do finally have ability to collect run information from the product team coming shortly but we will not be storing them in this table when we do that, only doing things like "last run"

**Comment by ALSPowerPlatform** [comment]
Please let us know where the data of flow run status is captured currently in COE, whether the flow run status is success or failed, like we want to have flow monitoring setup.

**Comment by Jenefer-Monroe** [comment]
It is not captured today at all. The product feature to get it to us is not yet implemented.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
