### ISSUE TITLE
Unable to create persona for Admin, Maker and User

### ISSUE THREAD

**Issue by fbellavf** [microsoft/coe-starter-kit#8428]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I keep getting the following error message anytime I try adding a group. When I add the object id of the group it then add this value to the others.

![image](https://github.com/microsoft/coe-starter-kit/assets/104634753/09163ef2-2030-4e66-adf9-9a7f6aa7c4bd)

Also do I have the correct settings for the group?
![image](https://github.com/microsoft/coe-starter-kit/assets/104634753/e72f5337-2602-4621-9a63-72eda17b0d59)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3499

**Comment by Jenefer-Monroe** [comment]
Sometimes people struggle to create the group from within the app. When this happens please do just go create in the Azure Portal and then select the existing group in the app. 

Yes thats correct, here is a picture of the one we use
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/72b7230a-d15a-446d-a57c-54cfa5834ba0)

**Comment by fbellavf** [comment]
> Sometimes people struggle to create the group from within the app. When this happens please do just go create in the Azure Portal and then select the existing group in the app.
> 
> Yes thats correct, here is a picture of the one we use ![image](https://private-user-images.githubusercontent.com/89584709/337661399-72b7230a-d15a-446d-a57c-54cfa5834ba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3Njc5NjAsIm5iZiI6MTcxNzc2NzY2MCwicGF0aCI6Ii84OTU4NDcwOS8zMzc2NjEzOTktNzJiNzIzMGEtZDE1YS00NDZkLWE1N2MtNTRjZmE1ODM0YmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzNDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYTQ0ZjQ4MzZlN2MzYzM2MmY0ODA0Nzg3MDhkNWFjZjhjOGQyYmQ5YjA2NjM3ODViNWMyYjczYTkxMzI2OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GKKJ9V7Lvc3zxpcRgA5SJ3lD-AO2d3obQ0T-zTzmLKQ)

Hi Jenefer,

We created the groups in Azure multiple times but they do not appear in the dropdown.

**Comment by Jenefer-Monroe** [comment]
Does the identity loading the app have access to the group? 

Please also share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by fbellavf** [comment]
> Does the identity loading the app have access to the group?
> 
> Please also share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names ![image](https://private-user-images.githubusercontent.com/89584709/294178041-8dd512cc-21fc-4c64-adab-0f64c29b9bf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjkwMjIsIm5iZiI6MTcxNzc2ODcyMiwicGF0aCI6Ii84OTU4NDcwOS8yOTQxNzgwNDEtOGRkNTEyY2MtMjFmYy00YzY0LWFkYWItMGY2NGMyOWI5YmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzNTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZjVjOWQ2NDZlZjg0N2IyMzIyZjQ3NDRmNDFmYWY5NGM5ODhjY2EwZTAzOTJkODY0NTAxMzA3ZmE2MDQ2MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGyqPK7CWzyuiQldU1MgMKgjn2YLKgs2WTKZdQ9RSZc)

Yes our admin granted the identity permission to create the groups as well.

![image](https://github.com/microsoft/coe-starter-kit/assets/104634753/3c90f66d-d4d8-4128-a178-d25c7900dbe3)

**Comment by Jenefer-Monroe** [comment]
And what happens if you just enter the GUD here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/73ac65c1-134e-434f-8b36-514801e75e35)

**Comment by fbellavf** [comment]
I get the following and the value remains in that field for all personas:

![image](https://github.com/microsoft/coe-starter-kit/assets/104634753/0d33ff5a-87f7-47f1-84b3-1d47de96cede)

**Comment by Jenefer-Monroe** [comment]
I've never seen anyone hit this. I suggest perhaps just go update the env vars manually in your case. 

You can do this by going to the default env't, select the env var, add current, add put in your values

For Admin, add the email to Admin eMail
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/45f54e91-9132-49a4-9e9b-7eed8c43122d)


For Maker and User, and the GUID
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c9ff3947-6e37-4f55-aa42-bf167a235178)

**Comment by fbellavf** [comment]
I have done this but they do not show in the Wizard app... is this ok? If I want to test the persona emails, is there a way to do this within the CoE?

**Comment by Jenefer-Monroe** [comment]
yes it seems like you're setup wizard isnt behaving as expected. 
We dont have tests but you can look at the values set in the Command Center:

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f06d251b-839f-44e9-af58-fcb820e739db)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f7dd991d-8e45-4daf-9a46-13e6b253f7f3)

**Comment by fbellavf** [comment]
I can see them in the Command Center!
