### ISSUE TITLE
In coe dataverse flow table - flow pending suspension reason column data suddenly went down from 1100 to 23

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#8429]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

hi team some days back were getting around 1100 rows of data where flow pending suspension reason column contains data, bu t today suddenly that data went down to 23 rows.
and we think the data is also not correct because there are some flows that are premium and not associated with power apps, and the user donot have a power automate premium license but still the column is blank.

please help us out it is urgent

### Expected Behavior

the data must be correct and the rows should be around 1100 where flow pending suspension reason column contains data

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

do not know

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3500

**Comment by Jenefer-Monroe** [comment]
Hello, I'm afraid we'll need more information to assist

1. Did the number of suspended flows also change? 

2. Do you remember which if there was an environment that accounted for most of them? Perhaps default? If so, can you please check to see if you have the System Admin role in that environment?

3. Do you have an example flow you expect to me marked suspended but which is not?

**Comment by Rajatchopra3** [comment]
<img width="682" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/47393750/9857dcdd-2e63-4d70-8b6a-e880d66f74e8">
We checked again the count is back to 900+ from 23  (flow pending suspension reason -  "contains data" )
could you please tell why this is happening  and which flow might be responsible for this

**Comment by Jenefer-Monroe** [comment]
I don't know how this might have happened. I've not seen it occur before. 

Please note the following information and then we can investigate if this happens again:
- What are the envts that have the most of these (that will make testing if it repros later easier)
- Check that the user running the flows has the Power Platform Admin Role permanently and directly assigned. 
![image](https://user-images.githubusercontent.com/89584709/226924688-ea65a5cc-c5ce-4bf7-9172-38a34347a6bf.png

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
