### ISSUE TITLE
[CoE Starter Kit - BUG] Question: How is Last App Launched Time populated?

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#843]
### Describe the issue

Hi Team,

While testing latest CoE Audit flows, It's noticed that, even if user launches an app, It keep receiving the value as null from the PowerApps App table, later I have checked that the Sync flow, does not log "Last App Launched datetime" as indicated in the following screen:

![image](https://user-images.githubusercontent.com/13658386/125591310-dc49bfd9-4394-499e-ad0c-4cac3e056790.png)

Therefore, even if user launches app as suggested in the Audit process instruction, user keep receiving an email.

Can you please help clarify?

### Expected Behavior

Once User launches an app after rejecting the Audit process, the same user should not receive an approval email for Archiving.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Archival and Clean Up (Start Approval for Apps)
Admin | Sync Template v3 (Apps)

### Steps To Reproduce

As an App Maker, After receiving an approval email, Reject the archiving process and launch the same app manually.
Next day, after successful run of all sync flows, run the "Start Approval for Apps" 
User receives an email, which should not happen.

**Comment by JeneferM-MSFT** [comment]
Hello. You are in the (apps) sync flow yes? This is not where we write the value for app last launched. It is not a property that we can collect from the product. 

We write the value for App Last Launched via the Audit Logs solution:
![image](https://user-images.githubusercontent.com/62659043/125628935-2505f358-c580-418d-bf8f-8efd358b2c4e.png)

**Comment by JeneferM-MSFT** [comment]
thanks for using CoE

**Comment by DiptiC-InsightRun** [comment]
Great to know this, Thank you Jenefer for your time on clarifying it!

Best Regards,
Dipti
