### ISSUE TITLE
[CoE Starter Kit - BUG] CoE flows error out regarding unassigned privileges

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#8433]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Some of the CoE CORE Flows error out with the following message: 
RetrievePrivilegeForUser: The user with id [id_placeholder] has not been assigned any roles. They need a role with the **prvReadAppModule** privilege.
RetrievePrivilegeForUser: The user with id [id_placeholder] has not been assigned any roles. They need a role with the **prvReadWorkflow** privilege.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Model Driven Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3505

**Comment by Jenefer-Monroe** [comment]
Hello likely you have been impacted by new product behavior that just shipped around the way the product treats privileged roles (ex Power Platform Admin role, Global Admin role)

While there is a workaround we can put into the kit to fix this directly, we cannot ship it with the kit until the workaround is available in all regions. Hopefully for the July release.

### The product change
Here is information about the product feature: [Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)

### How to check if this is the case
1. Validate the user running the flow has direct and permanent assignment to the Power Platform Admin role.
2. Take one of the target environments in your repro, one of the environments which is failing, and make sure the user running the flow has System Admin security role in that target environment.

### How to address and More information
Please see https://github.com/microsoft/coe-starter-kit/issues/8119 for a write up on this change. 
Included also is a workaround you can do until we can have it natively in the kit.

**Comment by VanIsleCA** [comment]
ok, thanks for your reply,

Will check this again with July's release, then. Thanks!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
