### ISSUE TITLE
[CoE Starter Kit - BUG] Flows that are not urphaned is marked as orphaned

### ISSUE THREAD

**Issue by larhem** [microsoft/coe-starter-kit#8436]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Since last week we suddenly had a lot of orphaned flows according to CoE in our environements, included a lot of the CoE Flows.
When looking at the flows they are not oprhaned, but it looks like most of them are turned off.
We have beed using Core Components 4.24 for a while, but this issue suddenly appeared last week.
Looks similar to issue #66

### Expected Behavior

CoE should only list flows that are really orphaned. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Set Flow Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3509

**Comment by Jenefer-Monroe** [comment]
They product started shipping unpublished flows but the detection mechanism was not what was expected

Fixing for June with https://github.com/microsoft/coe-starter-kit/issues/8426

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
