### ISSUE TITLE
[AA4AM] - Make docs more clear that we're in public preview

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#844]
People often don't realize we are in public preview until they get to the releases section.  We should update our documentation and perhaps the canvas UI to be clearer that we are in public preview and explain why.  We should explain our dependency on preview features like canvas code.  We should consider linking to the issues we think need to be address before we come out of public preview.

**Comment by mikefactorial** [comment]
Thanks @devkeydet! Rolling this feedback into #513.

**Comment by mikefactorial** [comment]
@devkeydet This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.
