### ISSUE TITLE
[CoE Starter Kit - QUESTION] Quarantined App - Browser is displaying incorrect information when app is quarantined

### ISSUE THREAD

**Issue by ortizh** [microsoft/coe-starter-kit#8440]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How can I modify the information that is displayed on the browser page of an application that is quarantined ?  
I want to add the admin email address on the highlighted section. Please note that I verified all admin environment variables and they seem to be correct. 

![image](https://github.com/microsoft/coe-starter-kit/assets/16614595/2d0c613b-ea11-49e7-9c3e-b0855842d397)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.15

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3513

**Comment by Jenefer-Monroe** [comment]
This is a product screen and not one from the kit. So unfortunately I dont know how to customize that, or if there is a way to do so. 
Perhaps others in the community know, happy to leave open for a bit to see, else I suggest you post here for help: https://powerusers.microsoft.com

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
