### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION | Related to #8086

### ISSUE THREAD

**Issue by JulesCam** [microsoft/coe-starter-kit#8444]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, I appreciate Issue #8086 has been closed but I am facing the same behaviour and we will most likely seek to purchase a per-flow license for this flow, however, I wanted to check something. I have installed the COE for four of our partners who each have their own tenant. We are only seeing this for one partner and not the others. Is this due to the volume of Database and Log used within the partner Power Platform, i.e., the partner impacted has 822.10 GBs of Database data and 437.62 GBs of Log data, whereby the others are below 200 GB for Database and 100 GB for Log - is this a key contributor? Are there other contributors like the number of Makers, Users? Is it the number of flows and apps? Your clarification would be much appreciated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3517

**Comment by JulesCam** [comment]
Thank you responding.

Do you mean within the COE environment itself? If so, no, the Database and Log storage usage is 2-3 GB combined. 

I understand that Dataverse storage is a different limit to the API allowance inherited by a user or flow via a license. I just wasn't sure whether the amount of data across the Dataverse's and the fact we have auditing enabled in every environment had contributed to the high API volume, or whether it is solely associated with the number of makers, flows, apps, user activity, etc.

I received the exact same message as detailed in #8086

**Comment by petepuu** [comment]
@JulesCam Yes meant CoE environment. But ok if you received this same Power Platform Request usage message for **Admin | Audit Logs | Sync Audit Logs (V2)** flow then CoE service account is executing too many requests on daily basis and the audit sync flow is one of the heaviest one. 

_Your flow has exceeded its Power Platform Requests (https://aka.ms/pa-ppr) limit in the past 24 hours. If this high usage persists, your flow actions may get throttled and slowed down. Power Platform Requests used: ??????, Power Platform Requests transition limit: 200000._

Can you check how many requests it is executing 

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/bef3c914-c625-474b-8e5a-9f5e67417911)


![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/2ac35e06-c125-4113-996f-ed8d63a8e67f)

**Comment by JulesCam** [comment]
It seems to be between 40000 up to 190000 depending on the day.

**Comment by petepuu** [comment]
Ok, limit in transition period is 200k/**flow** per 24h, so that should not be a problem if it stays under 200k. 

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/1590b4dd-edc7-4c18-8ea5-d3e3446eb734)

https://learn.microsoft.com/en-us/power-platform/admin/power-automate-licensing/types#power-platform-requests

**Comment by Jenefer-Monroe** [comment]
We do have work coming which will reduce the API count for the flow if you are able to setup the new API registration. We are not able to integrate this into the kit yet, but it is available for early testing if you would like.

Here is our tracking issue to integrate the new work with the kit : https://github.com/microsoft/coe-starter-kit/issues/8482

And here is the work which you can integrate with already if you are able: https://github.com/petepuu/coekit-auditlogsync-v3

The work is done by Pete here, who also did the other work in the kit so you know its good :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
