### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to Update Environment Variable 'Admin eMail'

### ISSUE THREAD

**Issue by LucasCXavier** [microsoft/coe-starter-kit#8447]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,
I'm unable to update the environment variable 'Admin eMail'. After entering the new value and clicking the 'Save' button, nothing happens. Do you have any ideas on how to resolve this issue?
Thank you.

### Expected Behavior

I expect that after clicking the 'Save' button, the value would be saved and displayed in the 'Value in use' column.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2024

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the 'CoE Admin Command Center' Model Driven App.
2. Go to the 'Environment Variables' tab.
3. Search for 'Admin eMail'.
4. Enter the new value.
5. Click 'Save'.

AB#3519

**Comment by Jenefer-Monroe** [comment]
Hello, 

All dialogs and panels were broken in the kit due to a product change that broke the creator kit components that we use. 
This has been resolved with the latest version of the creator kit: https://aka.ms/creatorkitdownload
- Creator Kit Core 1.0.20240529.1

Then this new version of creator kit has been adopted and used to fix in the June 2024 release of the kit which will ship later today or tomorrow.
- Core 4.32
- Gov 3.24
- Nurture 3.18 

You will need to upgrade to the June release to see this fix across the kit when its available.

**Comment by Jenefer-Monroe** [comment]
If you wish to proceed with this install instead, here is how to update these manually

### How to update env vars manualy
You can manually update environment variables by doing the following: 
1. Browse to the default solution > environment variables 
2. Find the env var you wish to update and edit
3. Add a new current value (do not update default as it is overwritten on upgrade)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/027b6a7c-b105-4fdc-90fb-005c8e2ed71b)

### For these env vars in particular:
**Admin eMail** : 
Required
The email address of the admin group you want to use for communications. 
Ex: PowerPlatformAdmins@myCompany.onmicrosoft.com

**Power Platform Maker Group ID** : 
Required
The group ID of the maker group you want all your Power Platform makers to be a part of (for communication and app sharing)
Ex: a11aa111-a1a1-a1a1-a1a1-abc123abc123

**Power Platform User Group ID** : 
Optional
The group ID of the user group you want all your Power Platform users to be a part of (for communication and app sharing)
Ex: a11aa111-a1a1-a1a1-a1a1-abc123abc123

**Comment by LucasCXavier** [comment]
Thank you @Jenefer-Monroe!

**Comment by Jenefer-Monroe** [comment]
We are here to help :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
