### ISSUE TITLE
[CoE Starter Kit - QUESTION] Suspension for Power Automate Flows

### ISSUE THREAD

**Issue by ortizh** [microsoft/coe-starter-kit#8448]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Via de CoE, is it possible to Suspend a Power Automate Flow ? 

Basically we are looking into managing orphaned Flows. We would like to suspend them (as there is no option to quarantine like there is for Canvas Apps). 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.23

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3520

**Comment by Jenefer-Monroe** [comment]
Unfortunately it is not yet today. The quarantine in canvas uses a product call to force an app into quarantine and this does not exist for cloud flows. 
I have heard that the product team is working on this though, and when available we can do something similar to force a cloud into suspended state from the CoE.
