### ISSUE TITLE
[CoE Starter Kit - BUG] Attempting to upgrade Core from 4.22 to 4.32

### ISSUE THREAD

**Issue by yearwoodm15** [microsoft/coe-starter-kit#8450]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

I am trying to upgrade my Core Components from 4.22 to 4.32. However, I am running into the below error. Any assistance would be greatly appreciated.

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CoECoreDataverseLegacy, Id: 11e3a3d9-ec29-4185-b6b7-a0206d8aabbd, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - CloudFlowOperations, Id: 6093b58a-4fea-eb11-bacb-000d3a578f6c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

admin_CoECoreDataverseLegacy, HELPER - CloudFlowOperations

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

In my environment, I go to solutions
Import solution
Import Core zip for June 2024
Core Component uploads for about half an hour until above error is received
There are now two Core Components under my Managed Solution
![CoE_Core_Error](https://github.com/microsoft/coe-starter-kit/assets/83036044/75da24c6-e28d-4832-8cab-ebe536bca67a)

### Anything else?

This is within the GCC High tenant.

AB#3522

**Comment by Jenefer-Monroe** [comment]
This is a connector we removed from the kit. Likely you have attached yourself to it in your own flows accidently. 

Please go to the default solution > connection references > look at the dependencies for both of these connection references
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f3bdbd49-f77b-42bb-be7f-fb665db85734)

Look for ones not included in the coe starter kit to find those that you may have taken a dependency on
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0b5e8e64-e32f-43d6-a6de-ce45a04b5925)

**Comment by yearwoodm15** [comment]
Hi Jenefer,

Thank you for this. It looks like all of what I have is part of the CoE Core Components. I also only see one Connection Reference when searching for Legacy. It is CoE Core - Dataverse Legacy.

<img width="821" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/83036044/64d3ec87-739a-4840-90e8-af8563d14b3d">
<img width="823" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/83036044/c950c67e-c6bd-46b8-8147-560cdcfb3e23">

**Comment by yearwoodm15** [comment]
Sorry, I think I misunderstood the first time around. I see the HELPER - CloudFlowOperations but I cannot delete it/remove from dependencies. Are you saying remove this from the CoE Core Components solution?

**Comment by Jenefer-Monroe** [comment]
No I was saying you had non-coe dependencies on the connection reference but it appears you do not. 

I think you've hit a product bug we've seen before where the ALM does not clean up dependencies in the correct order. 
I'm not sure how to fix this, perhaps if you just edit that flow to remove the dependency manually? Unfortunately we are in workaround territory for a product bug so this will be difficult and likely frustrating to do. 

If you'd like to give it a try I think the first thing to do is to open this flow and delete the whole scope as shown below.
Don't worry after upgrade you can remove the unmanaged layer and you will have the whole flow back. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e590b4a7-e8c2-45f8-85d8-a5204f65b3ac)

Once you do that, try the upgrade again and see if the error moves

**Comment by yearwoodm15** [comment]
Sorry for the delayed response. Interestingly enough, that Perform Cloud Flow Operation is not present under that flow. Double interestingly enough was when I attempted to upgrade 2 weeks ago, I now have two Core Component solutions. Any suggestions on this puzzling piece?
