### ISSUE TITLE
[CoE Starter Kit - BUG] Manage Permissions Apps: Get Connections flow fails sometimes - no connector listed for a small set of connections

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#8451]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
I would to delete old cross tenant reference that was made by users before i activated the option.
If i click on Manage connection, the flow helper-getconnectiontoclean gives me this error 
![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/44eaeb5d-44f3-4f4b-918e-03f5cb3a6375)

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/a04ce821-61f3-4779-92b4-f3a2e94a9365)

`The execution of template action 'Select' failed: The evaluation of 'query' action 'where' expression '{
  "connectorName": "@tolower(last(split(item()?['properties/apiId'], '/')))",
  "accountName": "@if(equals(item()?['properties/accountName'], null), '', tolower(item()?['properties/accountName']))",
  "connectionCreator": "@item()?['properties']?['createdBy']?['id']",
  "connectionCreatorUPN": "@item()?['properties']?['createdBy']?['userPrincipalName']",
  "connectionEnvt": "@items('Apply_to_each_envt')?['EnvtName']",
  "connectionEnvtDisplay": "@items('Apply_to_each_envt')?['EnvtDisplayName']",
  "connectionIdentifier": "@item()?['name']",
  "StatusIsError": "@if(equals(item()?['properties/statuses'][0]?['status'], 'Connected'), false, true)",
  "StatusString": "@if(equals(item()?['properties/statuses'][0]?['status'], 'Connected'), 'Connected', 'Error')",
  "StatusColorString": "@if(equals(item()?['properties/statuses'][0]?['status'], 'Connected'), '#dff6dd', '#fed9cc')",
  "noAccount": "@if(equals(item()?['properties/accountName'], null), true, false)",
  "connectionParamater": "@if(equals(item()?['properties/connectionParametersSet/name'], null), \r\nif(equals(item()?['properties/connectionParameters/workflowName'], null), '', \r\nitem()?['properties/connectionParameters/workflowName']), item()?['properties/connectionParametersSet/name'])",
  "propertyDisplayName": "@if(equals(item()?['properties/displayName'], null), '', item()?['properties/displayName'])",
  "flowURL": "@if(equals(tolower(last(split(item()?['properties/apiId'], '/'))), 'shared_logicflows'), concat(parameters('Power Automate Environment Variable (admin_PowerAutomateEnvironmentVariable)'), substring(items('Apply_to_each_envt')?['EnvtName'], sub(length(items('Apply_to_each_envt')?['EnvtName']), 36), 36), '/flows/', if(equals(item()?['properties/connectionParameters/workflowName'], null), '', item()?['properties/connectionParameters/workflowName']), '/details'), '')"
}' failed: 'The template language function 'split' expects its first parameter to be of type string. The provided value is of type 'Null'. Please see https://aka.ms/logicexpressions#split for usage details.'.`

do you have any idea ? It seems i have not the permission to delete the connection ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2024

### What app or flow are you having the issue with?

Manage Permisions

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Open cross tenant
2. Select one connection
3. Selecti Manage connection

AB#3523

**Comment by Jenefer-Monroe** [comment]
Cross tenant connections do work for me, so let's see what i happening in your case. 

Please share what is being sent in for the parameters to HELPER - Get Connections to Clean for your failure. 
Are there any nulls? If so which ones? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f82c7265-f2b7-4d98-9f54-8936076e8c52)

**Comment by tocri** [comment]
It's exactly the same as you

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/4728cfa8-f57c-46cf-9cfd-8234f3e3a923)

**Comment by tocri** [comment]
Ok that's happen only for all cross tenant connection that are in Default Environnment. It works for the others.
Maybe my issue is also related to the Environnement request issue that i have.

Is there some tables or permissions do i need to have ? I have the  Power platform Admin role though

**Comment by Jenefer-Monroe** [comment]
Can you share what this string looks like? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3fa7c157-2863-4bed-ae35-c4183db21382)

You can still obfuscate the name if there is one, but I need to know what it looks like.

**Comment by tocri** [comment]
<img width="246" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/be869910-55b0-4092-bdbe-1fecf1fbf51c">

is it okay ?

**Comment by Jenefer-Monroe** [comment]
Yes thank you that works. I dont think its the user after all. 
It seems like you are getting null apikey's from the Get Connections as Admin call, which should not happen.

Can you edit the flow and add these lines? 

**Select** 
NAME: Select key
FROM: @{outputs('Get_Connections_as_Admin_for_this_Envt')?['body/value']}
MAP: apikey - @item()?['properties/apiId']
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2a5fee92-a9b2-47c6-921a-45f9d35dd3f9)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9b1ceed3-573c-4cac-b253-5a79b7a89814)

**Filter**
NAME: Filter array
FROM: @body('Select_key')
Filter (Put in advanced mode): @equals(item()?['apikey'], null)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/08c6d813-edf1-4288-b883-028fcb84bdd5)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3b65b937-2231-46ef-8693-2acd554b53e4)

Then rerun this failure. 
1. Do you end up with values in that Filter?
2. Does the number of items in Get Connections as Admin for this Envt = the number returned in the Select Key

**Comment by tocri** [comment]
I hope i've understand that you want

<img width="295" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/7c811c53-cd08-4cd3-b88d-e4cccef5549f">

<img width="808" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/4f78e1ae-cde4-4d65-ae09-bf816ade3a10">

**Comment by tocri** [comment]
i forgot to rename the action

<img width="339" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/10110260/f620eeab-3054-430c-810b-9843853bc1ae">
![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/b2c856e4-f6aa-4a98-a282-747a6d2f03f4)

and the output

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/2644fc53-768b-4c23-8c4f-6fdc63ddafdb)


![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/8a414dc0-4547-4720-9c9e-8daa97d87f23)
in input

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/9d53f2f6-ac06-4cad-be5f-7e1728036cd7)

**Comment by tocri** [comment]
is this helps ?

**Comment by Jenefer-Monroe** [comment]
i had hoped it would but it did not. Do you know how to import flows? I can make you one that we can use for testing.

**Comment by tocri** [comment]
hi 

Yes of course ;-) A minimum skills is required to install & setup COE  
I think i can import a flow or a solution :😋

**Comment by Jenefer-Monroe** [comment]
haha flow import is kind of a legacy feature thats why I ask, no shame to people who dont know it :)

Can you please import this one for me into the CoE envt? 
[debugconnectionsissue_20240612214154.zip](https://github.com/user-attachments/files/15811184/debugconnectionsissue_20240612214154.zip)

And then run it and get me this information
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5ee103ce-89a1-42bb-889c-347d48fdd0af)

**Comment by tocri** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/9cbcb365-825f-4d34-a853-e1d15c20504b)

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/6f1ca3af-6d9f-45bd-8f7e-694a73c392f0)

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/321112de-e1f3-4fef-9190-026a7e37a833)

 The execution of template action 'Select_test_2' failed: The evaluation of 'query' action 'where' expression '{ "connectorName": "@split(item()?['properties/apiId'], '/')" }' failed: 'The template language function 'split' expects its first parameter to be of type string. The provided value is of type 'Null'

**Comment by tocri** [comment]
is it bad doctor ?

**Comment by Jenefer-Monroe** [comment]
its very strange that you have connections being returned with no connector! 
But I think we can work around this and just filter them out now that we know whats going on. 
Give me a day or so and I'll get you something to try out before I ship. 
Thanks for debugging with me!

**Comment by tocri** [comment]
Thank to you for fantastic support.

**Comment by Jenefer-Monroe** [comment]
ok can you try this test flow now? It should succeed all the way down to the last call. If it does, I can apply the fix to the flow of interest in the kit

[debugconnectionsissuewithfix_20240613235022.zip](https://github.com/user-attachments/files/15829845/debugconnectionsissuewithfix_20240613235022.zip)


![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6d8204d8-8a6a-438e-9e26-35c34d512e6f)

**Comment by Jenefer-Monroe** [comment]
Fix in the flow is to put that **_Filter to non-null api id_** filter statement above the select, and then to use it for the select.
Would be great if you could test and validate. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9ca81650-a6f7-470f-8709-9bd13f4daecc)

**Comment by tocri** [comment]
Sorry for the delay, wife's birthday. 

And 🥁

![image](https://github.com/microsoft/coe-starter-kit/assets/10110260/cef2a0bc-e245-4191-8030-56750f448105)

It works for me and i tried multiple times. Thanks a lot for your support and your time.

![WellDoneGIF](https://github.com/microsoft/coe-starter-kit/assets/10110260/02e13dfe-2d0a-4c55-abba-11dad4a3df30)

**Comment by Jenefer-Monroe** [comment]
And happy birthday to wifey!!!

**Comment by tocri** [comment]
thanks for her.
