### ISSUE TITLE
[CoE Starter Kit - QUESTION] Full inventory update did not add all Makers to our M365 group

### ISSUE THREAD

**Issue by GertjanM** [microsoft/coe-starter-kit#8456]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are using the CoE Start kit for almost 2 years now but, since last month, we've set up an M365 group to hold all the Makers. The **Admin | Add Maker to Group** flow adds new Makers to our M365 Group. However, our M365 group only contain new makers since last month. It does not add the existing Makers. To add all Makers, we tried running a Full inventory update as described [here](https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#running-a-full-inventory) but this did not add any of the existing Makers. Is there a way to add all the Makers from the Maker table to our M365 group once? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3532

**Comment by Jenefer-Monroe** [comment]
Hello, makers are only added to the group when they are first inventoried. 

This happens by the following flow: **_Admin | Add Maker to Group_**
Which only triggers when the makers are added to the Maker table, not if they are updated
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f609c66b-bba0-4c71-b263-2e3eb6707887)

We do not have a tool to go back and add old makers to the group but you could write a quick one off flow to do it. Just iterate all the makers in the table with this same scope in the loop 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5babc2e1-ec32-48f3-9915-1fc0574f5973)

**Comment by GertjanM** [comment]
Ok clear. We are going to add this functionality ourselves. In any case, we now know for sure that we will not build functionality that is already included in the CoE Starter kit. Thanks for the information!
