### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin Sync Template v3 for PVA throwing error at Get Inventory action.

### ISSUE THREAD

**Issue by Voidyyyy** [microsoft/coe-starter-kit#8457]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi @Jenefer-Monroe , I have some issue in CoE my "Admin Sync template v3 for PVA" is throwing error for all personal productivity environments. So is it because of the environment or something else. Below I've attached the screenshots for your reference.
![PVAError0](https://github.com/microsoft/coe-starter-kit/assets/72079788/dc0637ea-6ed0-4fdc-a0e8-02d34bcf8728)
![PVAError1](https://github.com/microsoft/coe-starter-kit/assets/72079788/7336fb45-86bd-43db-9819-89f74cbcd182)
![PVAError2](https://github.com/microsoft/coe-starter-kit/assets/72079788/4ff385e1-4b7c-4012-b389-d037770e0a4c)

Thanks,

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3549

**Comment by Jenefer-Monroe** [comment]
Hello. Likely something in the old sync flows added bad data and it was just not known until now as we changed to this set logic technique.  
 
Please go to the **_PVA Bot_** table > Click edit to see all data > Add/Remove columns until you see the below 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3591d936-6021-443b-9d8b-a921157ff17d)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4585ecfd-8175-4ec7-a1ac-94cbae6a8fe8)
 
Now filter to where Bot Id - Does not contain data > Delete these records. 
 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/92cf54a4-96b9-4d68-9935-9f6a5b30a159)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d2440cc0-ec5d-4de3-9737-6a7b61e34012)
 
Now the flow will pass and lets hold for a few days to make sure it doesn't return.

**Comment by Voidyyyy** [comment]
Thanks alot @Jenefer-Monroe, I'm closing this ticket as I don't have any issue for now.
