### ISSUE TITLE
One app repeatedly gets flagged for Republish Needed

### ISSUE THREAD

**Issue by MshulerIWT** [microsoft/coe-starter-kit#8459]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have one app that repeatedly gets flagged for Republish Needed.

When I navigate to the link in the email to resolve it, I get the message "The latest version of the app is already published.
Re-publishing is not available.  Marking as Submitted."

The app in question is a test app that does not get edited or run at this time.

What would be triggering this to keep requesting a Republish?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

April 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3551

**Comment by Jenefer-Monroe** [comment]
The flow checks for recent publish, not just that the latest is published. The reason being that the desire to to have people periodically checking that the apps have been validated and published. 

So likely it is the app that needs to change to tell you to go publish through the ux.

Please republish the test app to no longer see the message, and we can use this bug to change the UX in the app to tell people to manually republish the app.

**Comment by Jenefer-Monroe** [comment]
Here is the UX they should see, is that not what they see? Can you please share a screenshot? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e776b2d3-b37b-4ae9-a36e-15c55a6b8ffc)

**Comment by MshulerIWT** [comment]
Excellent.

Thank you very much for the quick response on this!

-Mark


[https://www.infiltratorwater.com/Customer-Content/www/CMS/files/EmailSignaturelogo.gif]
Mark Shuler​​​​
IT Operations Manager
Phone: +1-860-577-7163<tel:+1-860-577-7163>      |      Mobile: +1-860-510-1951<tel:+1-860-510-1951>
4 Business Park Road            Old Saybrook    ,       CT
06475
Website | <http://www.infiltratorwater.com/>    Facebook | <https://www.facebook.com/infiltratorwater>  LinkedIn | <http://www.linkedin.com/company/infiltrator-water-technologies>     You Tube | <https://www.youtube.com/user/InfiltratorSysInc>     IWT Careers<https://iwtcareers-ads-pipe.icims.com/jobs/search?ss=1&hashed=-435715736>

**Comment by MshulerIWT** [comment]
The "Republish Needed" message has returned.
There must be something I am missing?

Attached is a screen shot of the message we are getting.
![Republish Needed](https://github.com/user-attachments/assets/bfe680e8-99d0-4d8e-b750-f14e20a3e21b)
