### ISSUE TITLE
[CoE Starter Kit] Add impact analysis to DLP Editor for Child Flows that indirectly depend on HTTP actions

### ISSUE THREAD

**Issue by chrispiasecki** [microsoft/coe-starter-kit#846]
Currently the DLP Editor is able to identify impacts where the HTTP action is explicitly used in a flow. From what has been observed, child flows that use the button trigger with a Respond to a PowerApp or flow action would not be identified in the impact analysis section if the HTTP connector is added to DLP blocked group. Since child flows depend on the HTTP connector under the hood, then those flows would stop working as a result.

Accounting for child flows in the DLP Editor impact analysis would be a desirable enhancement.

**Comment by manuelap-msft** [comment]
Thank you for this feedback! We will need to do some analysis to see how this can be achieved!

**Comment by manuelap-msft** [comment]
Hello,

have you found a way to identify Child flows? 

I have just looked at the output of the [List Flow as Admin](https://docs.microsoft.com/en-us/connectors/flowmanagement/#list-flows-as-admin) action that we use to gather the inventory and the trigger of a child flow just shows up as a "Button" trigger (the same is true for other manual trigger flows). So I'm not sure how we can identify child flows.
![image](https://user-images.githubusercontent.com/55705669/125799863-09eae145-3888-4033-af17-cf2c741553c8.png)

Let me know if there's a way you found,
Manuela

**Comment by JeneferM-MSFT** [comment]
It appears that child flows **are** just button flows that happen to be in a solution and which are called from another flow (or from a powerapps it seems). 
So the only way to do this as far as I can tell would be to integrate with Flow Action Details of the parent flow and then see if that contains the child, and mark up the child.

**Comment by chrispiasecki** [comment]
> Hello,
> 
> have you found a way to identify Child flows?
> 
> I have just looked at the output of the [List Flow as Admin](https://docs.microsoft.com/en-us/connectors/flowmanagement/#list-flows-as-admin) action that we use to gather the inventory and the trigger of a child flow just shows up as a "Button" trigger (the same is true for other manual trigger flows). So I'm not sure how we can identify child flows.
> ![image](https://user-images.githubusercontent.com/55705669/125799863-09eae145-3888-4033-af17-cf2c741553c8.png)
> 
> Let me know if there's a way you found,
> Manuela

Hi Manuela,

If the flow has a button trigger, and the actions contain a response kind of PowerApp or Flow, that would indicate its a child flow yes?

![image](https://user-images.githubusercontent.com/39163673/125805241-6b057fc9-9752-41b7-801b-bd3424552b7a.png)

**Comment by manuelap-msft** [comment]
@chrispiasecki Not necessarily, Flows triggered from Power Apps also respond to Power Apps (to send info back to the app) and these are not child flows. 

@JeneferM-MSFT Great idea on looking at the parent flow instead, I didn't think of that! We can investigate that.

**Comment by chrispiasecki** [comment]
> @chrispiasecki Not necessarily, Flows triggered from Power Apps also respond to Power Apps (to send info back to the app) and these are not child flows.
> 
> @JeneferM-MSFT Great idea on looking at the parent flow instead, I didn't think of that! We can investigate that.

If you look at the parent flow Admin | Sync Audit Logs as an example, it has an action of type **Workflow**.  I think this could be sufficient to identify impacts where a parent flow is calling a child flow.

![image](https://user-images.githubusercontent.com/39163673/125808377-855e8b61-fca7-40c8-b548-ffab4c384844.png)

You are correct though in that you'll also need to account for triggers of Power Apps (V1 and V2) and response kind of PowerApps.

**Comment by manuelap-msft** [comment]
Due to the complexity of the DLP Editor, we are unable to implement this. There is also work in the product planned for child flows to no longer take a dependency on the HTTP action.
