### ISSUE TITLE
[CoE Starter Kit - BUG] FLOW DATA NOT POPULATING POWERBI REPORTS

### ISSUE THREAD

**Issue by afoncann** [microsoft/coe-starter-kit#8462]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After following all the steps in the CoE toolkit documentation provided by Microsoft, I get to the final steps of setting up the Production_CoEDashboard_MMMYY.pbit file in PowerBI, and as I click through the tabs, the data looks as expected, except on the Cloud Flow-specific tabs. It is not collecting any data/inventory around my Power automate flows in the entire tenant. 
![image](https://github.com/microsoft/coe-starter-kit/assets/68955154/4a48f9f6-e0b5-42a6-bbfd-e00768c0c76a)

My first thought was that there was a flow erroring out, so I went to the Admin | Sync Template v4 (Flows) Power Automate flow and observed this. 
![image](https://github.com/microsoft/coe-starter-kit/assets/68955154/1026048b-cd69-4c8f-91ca-77ae549d0879)

And then I saw that there was an issue in the trigger of this flow:
![image](https://github.com/microsoft/coe-starter-kit/assets/68955154/31c94877-2ced-4f47-b522-aa934ba85152)

### Expected Behavior

I would expect that the Power BI Cloud-Flow related tabs would have data the reflects the cloud flows that exist in my tenant. 
![image](https://github.com/microsoft/coe-starter-kit/assets/68955154/345315c0-20f6-41a1-8bf9-22943a04475f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Follow steps in setup
2. Turn on inventory and audit flows
3.  Setup PowerBI Report and test

AB#3555

**Comment by Jenefer-Monroe** [comment]
Looks like there is something wrong with the identity running the flow. 
Here are a few questions: 
- What is the full error message you received? 
- Are you trying to run it as a service principle? That is not supported for Dataverse connector.
- Are other flows like Admin | Sync Template v4 (Apps) also experiencing this? Do they have the same primary owner?

**Comment by afoncann** [comment]
Answers to your questions below:
**What is the full error message you received?**
This is the full error message - Invalid PrincipalId=00000000-0000-0000-0000-000000000000 Guid.Empty doesn't exist. 

**Are you trying to run it as a service principle? That is not supported for Dataverse connector.**
No - I am not trying to run as a service principle. 

**Are other flows like Admin | Sync Template v4 (Apps) also experiencing this? Do they have the same primary owner?**
Doing some quick spot checking, I can already see a handful of flow that are having a similar trigger issue. Here are a few of them:
![image](https://github.com/microsoft/coe-starter-kit/assets/68955154/e38290e2-7ee8-48b3-90b0-675a8fb02fd5)
![image](https://github.com/microsoft/coe-starter-kit/assets/68955154/baf00b68-e8ce-4add-8332-845f8c24a9c1)

But I can see instances of working Dataverse triggers - these are all using the same Owner and Dataverse connector. I see some different connection references used without though.

**Comment by Jenefer-Monroe** [comment]
You've definitely hit some product bug here, not an issue with the kit. But hopefully we can get you unblocke.d 
Perhaps the connection references are broken. Can you please go to the connection references and check that all are correctly assigned? 
Solutions > Default > Connection References > Check each one of the CoE Connection References for the identity its using:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4f9975d2-8331-4dd9-9250-69553af805d4)

**Comment by afoncann** [comment]
All CoE Connection References are using the same identity - 
![image](https://github.com/microsoft/coe-starter-kit/assets/68955154/747a641e-50cb-4b1d-8bb6-c0b07b5baa3e). 

Would it make sense to try to create new connection references within the flows that are not triggering properly. I'm most confused around how there are Dataverse triggers working elsewhere inside the CoE solution.

**Comment by afoncann** [comment]
I do not believe the issue above is related to mine. Similar end result, but the flows in my environment will not even kick off. The last thing I tried yesterday was to create a new connection reference in one of the flows that was experiencing errors and the issue still persists in my environment. Not sure how to progress passed this.

**Comment by Jenefer-Monroe** [comment]
Agreed, you have a unique issue on your hands. And unfortunately what you are experiencing is a product issue dealing with your user / tenant state, not something with the kit. 
However sometimes these self resolve. I suggest trying to upgrade again, the June release just shipped, you can try with that one.
https://aka.ms/coestarterkitdownload

**Comment by afoncann** [comment]
Thank you Jenefer - appreciate your timeliness and staying on top of these sort of things!

**Comment by Jenefer-Monroe** [comment]
I try 🤣

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
