### ISSUE TITLE
[CoE Starter Kit - BUG] Flows Not being populated in COE

### ISSUE THREAD

**Issue by whorn76** [microsoft/coe-starter-kit#8464]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

All other inventory seems to be happening, however flows are not being inventoried.
![Screenshot 2024-06-11 162033](https://github.com/microsoft/coe-starter-kit/assets/4932270/e8d7e19b-b8b7-49d3-944a-bffc589f51a4)
![Screenshot 2024-06-11 163630](https://github.com/microsoft/coe-starter-kit/assets/4932270/74516f16-7c57-4c7c-be99-6871f7c5b1c1)

### Expected Behavior

Flows should be populated in inventory

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Flows) ?

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

New June Install of COE.

### Anything else?

Doesn't seem to be related #8462 as the Admin Sync | Template (Flows) appears to be running fine without errors and returns flow lists from connector.  However we are seeing no flow data in the apps or power bi reports.

AB#3557

**Comment by Jenefer-Monroe** [comment]
Hello, lets see if we can figure this out: 

1. Is the data present in the Power Platform Admin View app? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e37dfbee-d821-4359-babf-f2fdd94fca52)

2. Find a run with an environment you expect to have flows and open it, is there data returned here?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/accc0ba6-3cfc-4271-950b-108f0923570e)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/53094d0c-cb9d-4df4-9662-8686a2430c2c)

**Comment by Jenefer-Monroe** [comment]
thank you, I got it. Its a bug on my side. I'm reshipping. Sorry. 

The fix, if you want to try with me, is to change two expressions to not-equals. 
You can find those details here:
https://github.com/microsoft/coe-starter-kit/issues/8426#issuecomment-2161921418
