### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Audit Logs (V2) - Your flow is running too many actions

### ISSUE THREAD

**Issue by astar01** [microsoft/coe-starter-kit#8465]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are receiving these emails - Your flow is running too many actions - Admin | Audit Logs | Sync Audit Logs (V2)

Following is the email

<html>
<body>

Your flow is running too many actionsYour flow has exceeded its Power Platform Requests (https://aka.ms/pa-ppr) limit in the past 24 hours. If this high usage persists, your flow actions may get throttled and slowed down. Power Platform Requests used: 482350, Power Platform Requests transition limit: 200000.Flow name: Admin \| Audit Logs \| Sync Audit Logs (V2)View Detail > | Your flow is running too many actionsYour flow has exceeded its Power Platform Requests (https://aka.ms/pa-ppr) limit in the past 24 hours. If this high usage persists, your flow actions may get throttled and slowed down. Power Platform Requests used: 482350, Power Platform Requests transition limit: 200000.Flow name: Admin \| Audit Logs \| Sync Audit Logs (V2) | Your flow is running too many actionsYour flow has exceeded its Power Platform Requests (https://aka.ms/pa-ppr) limit in the past 24 hours. If this high usage persists, your flow actions may get throttled and slowed down. Power Platform Requests used: 482350, Power Platform Requests transition limit: 200000.Flow name: Admin \| Audit Logs \| Sync Audit Logs (V2) |   | View Detail > | View Detail > | View Detail > | View Detail > |  
-- | -- | -- | -- | -- | -- | -- | -- | --

View Detail > | View Detail >
View Detail > | View Detail >
View Detail > | View Detail >
View Detail >

</body>
</html>Your flow is running too many actions
Your flow has exceeded its Power Platform Requests ([https://aka.ms/pa-ppr](https://urldefense.com/v3/__https://aka.ms/pa-ppr__;!!F8xy4SI!wD7GAp3IOjIHQ6eg2ZCFAelDnrfnuBNiO3QiU5iOsBl_CXYiws8JzBNieT-r0flHzk60AlY0WrO-HbLH8QzqvTXAl9bTXSygx9uJig$)) limit in the past 24 hours. If this high usage persists, your flow actions may get throttled and slowed down. Power Platform Requests used: 482350, Power Platform Requests transition limit: 200000.

Flow name: Admin | Audit Logs | Sync Audit Logs (V2)

[View Detail >](https://urldefense.com/v3/__https://emails.azure.microsoft.com/redirect/?destination=https*3A*2F*2Fmake.powerautomate.com*2Fenvironments*2F1365757d-6753-e08e-9c59-94eeae80d146*2Fflows*2Fc36d73d9-c3d7-7a92-72b2-4f959f7d269e*2Fdetails*3Futm_source*3DHighUsageAlert*26utm_medium*3Demail&p=bT1jZjg0MGZmOC03YmIyLTQ0ZTAtOGYwMi0zNzFmMzM1YTQ4N2QmdT1hZW8mbD1kZXRhaWxz__;JSUlJSUlJSUlJSUl!!F8xy4SI!wD7GAp3IOjIHQ6eg2ZCFAelDnrfnuBNiO3QiU5iOsBl_CXYiws8JzBNieT-r0flHzk60AlY0WrO-HbLH8QzqvTXAl9bTXSzj1XVpWA$)
One of the following is causing the problem:
There's a design issue that's resulting in excessive actions. View [usage analytics](https://urldefense.com/v3/__https://make.powerautomate.com/environments/1365757d-6753-e08e-9c59-94eeae80d146/flows/c36d73d9-c3d7-7a92-72b2-4f959f7d269e/analytics__;!!F8xy4SI!wD7GAp3IOjIHQ6eg2ZCFAelDnrfnuBNiO3QiU5iOsBl_CXYiws8JzBNieT-r0flHzk60AlY0WrO-HbLH8QzqvTXAl9bTXSwwY9nRCg$) to view execution trends.
The Power Platform requests transition limit is insufficient for your usage.
Here are a few recommendations:
If you have 'do until' or 'apply to each' loops in your flow, see if you can reduce the number of loop iterations, possibly by retrieving fewer items to iterate through.
Many connectors have 'filter query' and 'top count' parameters that can be used to reduce the number of items retrieved.
If you have a scheduled flow that runs frequently, consider reducing the frequency. Many flows that run once per minute could be revised to occur less often.
Use process mining to analyze your flow and improve the efficiency. See [Process Mining overview](https://urldefense.com/v3/__https://aka.ms/paprocessmining__;!!F8xy4SI!wD7GAp3IOjIHQ6eg2ZCFAelDnrfnuBNiO3QiU5iOsBl_CXYiws8JzBNieT-r0flHzk60AlY0WrO-HbLH8QzqvTXAl9bTXSxkkqDj7Q$).
Assign "Power Automate process" plan to the flow. See [types of Power Automate licenses](https://urldefense.com/v3/__https://aka.ms/pa-license-types__;!!F8xy4SI!wD7GAp3IOjIHQ6eg2ZCFAelDnrfnuBNiO3QiU5iOsBl_CXYiws8JzBNieT-r0flHzk60AlY0WrO-HbLH8QzqvTXAl9bTXSwAdGJ2Eg$).

### Expected Behavior

Is there any way to put this flow under the limit.
This flow is quite important to us because we have created our own compliance process for canvas apps which checks the app last launched date. If we have any issues in this flow then this will cause major issues with our compliance process, in fact lead to deletion of flows because app last launched date was not updated. Please give us a way to resolve this issue

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

[Your flow is running too many actions - Orbia PowerPlatform Admin - Outlook.pdf](https://github.com/user-attachments/files/15802496/Your.flow.is.running.too.many.actions.-.Orbia.PowerPlatform.Admin.-.Outlook.pdf)

AB#3558

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately today we do not have another option. The back end we have available does not allow filtering and so it processes all activity in the tenant, which of course is quite costly / API intensive.

The good news is that a new backend is in preview right now and we have someone exploring it on a large tenant. We should be able to have it out there for folks to use in the next couple months.

**Comment by astar01** [comment]
Hi Jenefer,

Thank you for your reply. I would like to know the following:
1. Is there a chance when I’m getting these messages that some audit log
activity is not recoded because the number of api calls have exceeded? I’m
asking because we are running our own compliance process that monitors and
deletes apps whose last launched dates are not updated. Is there a chance
that this date is not updated? This will be a big problem for us.

2. Is there a chance to have this audit log working for only certain
environments? May be this will reduce the api calls

3. Is there some other license we can use which will give us more API calls.

Thanks for your help.

**Comment by Jenefer-Monroe** [comment]
1 - missing logs / last launces
It is possible, yes. But likely its something else. 
We moved the updating of the Power Apps table to its own flow for performance reasons and it looks like you may not have turned it on. Please validate that both these turned on. Please do let me know as I have a helper to fix the backlog of data if you did not have it on.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5447542a-72d7-448b-9556-c6ef0c5e0cf8)

2 - filter envts
Just as we cannot filter on activity, we also cannot filter on Environment. By the time we find out what app was launched we've done most of the API hit, which is around filtering down to launches. In fact, mapping to which app it was that was launched is done in another flow, as per the above. 

3 - licenses
You can purchase a per-flow (Power Automate process plan) type license for the flow. But they are not cheap. Please see [Types of Power Automate licenses](https://learn.microsoft.com/power-platform/admin/power-automate-licensing/types). Unfortunately I'm not a license expert and so don't have much advice on this.

**Comment by Jenefer-Monroe** [comment]
Also note that we do have access to a new preview backend to use which will decrease the API count quite a bit. We are working through this and hopefully it will ship with the kit this summer.

**Comment by astar01** [comment]
Hi Jenefer,

Yes noted that you are releasing a new version this summer, so I would wait for it. Will it be released in as a new monthly release? Can you please inform me how to keep a watch for this release?

Secondly, for your point 1), I do not have the Audit Logs | Update Data (V2) in my solution, may be I am using older version, is that the reason? Please see the screen shot below from the Core Components. The Sync Audit Log V2 was always turned on.

![image](https://github.com/microsoft/coe-starter-kit/assets/52736218/b4167ec3-0e3a-48c1-9d86-384723ee5ecb)

Please can you share what should my next steps be with regard to these flows.

Thanks.

**Comment by Jenefer-Monroe** [comment]
Yes I suggest updating to the latest release and then be sure to turn that **_Update Data_** flow on. 
We did do a little tweaking to reduce API count recently but it wont be dramatic. Every bit helps though!

**Comment by Jenefer-Monroe** [comment]
Regarding way to track, we will have the tracking bug for the work posted next week so I can give you a link. The fix will be shipped with a regular monthly release yes.

**Comment by Jenefer-Monroe** [comment]
Here is our tracking issue to integrate the new work with the kit 
https://github.com/microsoft/coe-starter-kit/issues/8482

And here is Pete's work which you can integrate with already if you are able: https://github.com/petepuu/coekit-auditlogsync-v3

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
