### ISSUE TITLE
Helper flows to turn on / off all the CoE flows

### ISSUE THREAD

**Issue by brentellingwoodevr** [microsoft/coe-starter-kit#8467]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jennifer, you asked me to post this question so you could share your helper script. This was the question i posted in todays Office hours. Any help you provide here is greatly appreciated!

On the topic of the Unpublished flows feature, we want to programmatically turn on/off CoE Core flows during our deployment from dev. We have had to manually turn on all of the flows in our Stage environment to generate the Name property of the flow which is needed from the PowerShell "Enable Enable-AdminFlow" action. Is there a better way to do this or to automatically enable all flows so we don't have to manually enable the flows in our target environment?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

None specifically

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3560

**Comment by Jenefer-Monroe** [comment]
Happy to help. Here are the helpers I use when we prep to ship. I hope they are helpful!

### Turn them off
This one turns all flows in the CoE Solution Metadata table off, and turn turns back on the ones we want to ship in the on state. you may want to cut that second part depending on your needs
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/57b0d91d-63f7-4427-bee4-029f4d05d5c2)
[TurnCoEflowsoff_20240612201848.zip](https://github.com/user-attachments/files/15810535/TurnCoEflowsoff_20240612201848.zip)

### Turn them on
This one first determines if you are BYODL (Data Export) or Cloud Flow for inventory, then turns on the correct inventory flows for that architecture. It also turns back on the Audit Logs. You may need to add other solution areas to turn back on if you want them on. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e2d45172-36e9-4f2c-aa47-0a5f590e7a8d)

[TurnCoEflowson_20240612201833.zip](https://github.com/user-attachments/files/15810534/TurnCoEflowson_20240612201833.zip)

**Comment by brentellingwoodevr** [comment]
This is so helpful! Thank you! I had no idea the admin_installorder column existed.

**Comment by Jenefer-Monroe** [comment]
Yes! We use it in the setup wizard too. There are so many nooks and crannies in this kit, I forget some of them myself!

**Comment by Jenefer-Monroe** [comment]
So glad it was helpful.,

**Comment by brentellingwoodevr** [comment]
Yes, certainly a lot of hidden gems. I can think of a number of processes this is going to help out with. Thank you again!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by tschwa21** [comment]
Hello, @Jenefer-Monroe, I'm looking to utilize this TurnCoEFlowsOn package, but when I import the solution I receive  the error

"The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported."

Is there an updated version I can pull from? Thanks in advance for all your help!
