### ISSUE TITLE
Child Admin | Sync logs

### ISSUE THREAD

**Issue by kast2L** [microsoft/coe-starter-kit#847]
Hey, I am guessing this is new? I have never had to enter tenantID and a start/end date here before and I don't know the format for the start/end date so the flow just keeps failing. I cannot omit it.

![image](https://user-images.githubusercontent.com/79542230/125671069-6acde76e-bd32-4f70-a6e2-aed885805f47.png)

**Comment by manuelap-msft** [comment]
Hello,

this is not new - those are parameters passed to the Child flow by the parent flow Admin | Sync Audit Logs. 

Thank you,
Manuela

**Comment by chrispiasecki** [comment]
> Hello,
> 
> this is not new - those are parameters passed to the Child flow by the parent flow Admin | Sync Audit Logs.
> 
> Thank you,
> Manuela

It looks like it is indeed new. I have v1.41 of the CenterofExcellenceAuditLogs solution and the only env variable is Tenant ID. I recall having to modify the [Child] Admin  | Sync Logs flow directly to change those parameters. I'm guessing these environment variables were added in order to reduce creating additional unmanaged layers on the CoE components, which is quite cumbersome to remove and reapply after every upgrade.

**Comment by kast2L** [comment]
I am also receiving this error now from the Admin | Sync Audit Logs which is the opposite of the instructions provided so I am just a bit confused. 


Update the child flow for action 'Run_a_Child_Flow' to not use 'run-only user' connections.

**Comment by manuelap-msft** [comment]
There are new environment variables with the new solution, that's true - they are for the Interval and have been added to our setup documentation.

The above highlighted Start Date and End Date are however not environment variables but parameters that the parent flow passes to the child flow. They don't need to be set when you run the Audit Log sync flow.

**Comment by kast2L** [comment]
This may be separate, but when I imported the new 1.50 version of audit logs, it still shows my existing 1.40 

![image](https://user-images.githubusercontent.com/79542230/125675488-0bf1d273-9a36-48bd-8c47-86d8cd4f9e6a.png)

**Comment by manuelap-msft** [comment]
That likely means the Import/Upgrade has failed. Can you check the solution history for more details?

**Comment by kast2L** [comment]
It appears it did,

![image](https://user-images.githubusercontent.com/79542230/125676047-2795861c-0c45-4db2-b216-35853de16e83.png)

![image](https://user-images.githubusercontent.com/79542230/125676259-b27d3bac-7fa8-4efc-9cfd-e1ad82f621a7.png)

**Comment by kast2L** [comment]
it appears I may be having this same issue as others here https://github.com/microsoft/coe-starter-kit/issues/803

**Comment by kast2L** [comment]
were the screenshots helpful at all?

**Comment by manuelap-msft** [comment]
If you look through #803, that has been solved by using Update instead of Upgrade during Import. We left the issue open in case others face the same, but those who had it solved it by using Update. Please try the same!

**Comment by kast2L** [comment]
Okay, thank you for the quick response, I will try that now.

**Comment by kast2L** [comment]
just wanted to share I manually removed the solution(s) and reinstalled, now working fine.
