### ISSUE TITLE
[CoE Starter Kit - BUG] PBI Not showing correct app makers

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8470]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

App Makers field in Apps Page is not accurate. This is showing Environment maker count instead of App Owner count which sould be the app makers. 

![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/e41ccd85-b316-4109-9652-141da80dba73)
![image](https://github.com/microsoft/coe-starter-kit/assets/95443860/800f90f0-8a35-4790-b18b-050830d01327)

### Expected Behavior

Data should be accurate. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

PBI Production CoE Report

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3566

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, will try to fix for next release.
