### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Request - PCF feature is not enabled even when selected to be enabled in the request 

### ISSUE THREAD

**Issue by petepuu** [microsoft/coe-starter-kit#8471]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When creating environment request with PCF enabled it will not get actually enabled in the  **Env Request | Create Approved Environment** flow

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/5baec010-88fd-42bb-9305-80fd9651146a)

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/e5f28f83-0e68-4bd0-9c64-7bb3a76aec5a)

<br><br>
varErrorMessage action is not executed when environment creation is successful. We enter to PCF condition only if DLP change request and varErrorMessage actions are successful, so I think we need to remove the varErrorMessage from the configure run after conf

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/163c3cb1-56c7-444c-a797-31674e79f7ee)

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/7c1d5e6c-af03-4ae1-a251-67548fc9e92f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32

### What app or flow are you having the issue with?

Env Request | Create Approved Environment

### What method are you using to get inventory and telemetry?

None

AB#3576

**Comment by Jenefer-Monroe** [comment]
thanks for posting. To area owner for investigation.
