### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Audit Log does not capture MDA app launches similar to canvas app launches 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#8474]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Can we try to capture Model Driven App launch events similar to Canvas App Launches 

If not possible is there any technical explanation, please provide 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

4,31

### What app or flow are you having the issue with?

Admin-Sync V3 Template 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3579

**Comment by Jenefer-Monroe** [comment]
Hello. 

The CoE Starter Kit gets Audit Log information from the [Microsoft 365 Purview Audit Log](https://docs.microsoft.com/power-platform/admin/logging-powerapps) and only canvas app launches are logged there. We do not currently have a feature to monitor model driven app launches, cloud flow runs, etc. 

Some of this type of information is available if you set up [Application Insights](https://docs.microsoft.com/power-platform/admin/analyze-telemetry) but this is not something that the kit is integrated with.

**Comment by lukas-nC** [comment]
@pamatihyd If you use the Data Export feature, you can get this info
https://learn.microsoft.com/en-us/power-platform/admin/self-service-analytics

@Jenefer-Monroe Cloud Flow runs are now available in Dataverse (preview feature)
https://learn.microsoft.com/en-us/power-automate/dataverse/cloud-flow-run-metadata

**Comment by Jenefer-Monroe** [comment]
Thanks Lukas for the help! Do note that there are currently bugs in the Data Export feature which prevent it from mapping correctly to the MDA but the Data Export team is working to address for the upcoming big schema change!

**Comment by lukas-nC** [comment]
thanks for the info

**Comment by Jenefer-Monroe** [comment]
thanks for all your help!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
