### ISSUE TITLE
[CoE Starter Kit - BUG] Group Size limited to 100 in Power Platform Users

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#8475]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I noticed that in Power Platform Users table, the column Group Size is not over 100. These groups have more members.
How is calculate this number? Maybe there is a pagination that limit to 100?
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/91137f0f-33a9-4d65-8b71-ddd2b21648c2)

### Expected Behavior

Then number correct of the groups with more of 100 members.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Core

### What app or flow are you having the issue with?

Power Platform Users table

### What method are you using to get inventory and telemetry?

Data Export

AB#3580

**Comment by Jenefer-Monroe** [comment]
thanks for posting! I will investigate

**Comment by Jenefer-Monroe** [comment]
This isnt perfect yet but you can do this to get better while I investigate to see if there is something even better I can do. 
Let me know if these still seem capped to know my priority to fix. I'll have to add a do until 

Go to **_CLEANUP - Admin | Sync Template v3 (Orphaned Users)_**

And change the expression shown to this: 
`@{parameters('Graph URL Environment Variable (admin_GraphURLEnvironmentVariable)')}v1.0/groups/@{items('Apply_to_each_group')?['admin_powerplatformuserid']}/transitivemembers?$top=999&$select=odata.type, id, userType`

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/14eeb58b-7899-4515-a7af-73285690d4c0)

**Comment by albertocastro365** [comment]
Hi again.
this workaround works fine :)
One question: The value 999 is the limit? Like you see I have groups with more members.
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/c8083fc4-417b-4563-8b70-7193cbab1536)

**Comment by Jenefer-Monroe** [comment]
Yes 999 is as high as you can go with the top function for this csall, which is more than 100 but .... 

I'll have to add a do-until and look for the next, to collect into an array which I'm afraid may also mean I cant use the concurrency in the for-all anymore and will slow down the flow but .... I'll explore more to see if I can come up with something clever

**Comment by albertocastro365** [comment]
Hi,
A tried with a value = 1500 and runs fine also, it takes more time but I supose that is normal because I have a group with 40k members.

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/9252f59d-35d2-4d1d-b3a9-42a466bd6a9b)
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/22693362-cfd1-4035-8df5-3cd95f6b0483)
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/577970b8-91ee-416d-82a4-e3c2a429d728)

**Comment by Jenefer-Monroe** [comment]
oh nice ! It failed for me in the graph explorer above 999, and I just assumed the same limit would exist in flow. 
YEAH !!! Thank you for testing that!

**Comment by Jenefer-Monroe** [comment]
I get an error with that
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/59ba7d75-69c3-4fe9-b46b-1f6e017105dd)

I think I'll have to implement the do-until code.

**Comment by Jenefer-Monroe** [comment]
Here is just this flow in its own little solution, can you please import it and try?

It will be slower running now as we cannot use the concurrent runs on this section any longer (for groups) but that's ok, this flow runs only weekly and the true count here is quite important. And it's not many more API calls.

[testgrouppagination_1_0_0_1_managed.zip](https://github.com/user-attachments/files/15829603/testgrouppagination_1_0_0_1_managed.zip)

**Comment by albertocastro365** [comment]
Hi Jennefer,
I tested this flow in my Test environment and I confirm you that works fine!
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/5b770c3c-67b9-476f-ac1c-fe90eb7a2804)

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/98347dd4-d3da-4b68-b5c2-dc9805b17421)
