### ISSUE TITLE
[CoE Starter Kit - QUESTION] API Calls Report

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8477]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Team, 

We are looking at API Call reports from PPAC to understand the impact our CoE has with the user account that currently hosts it. We noticed that API calls are spread out throughout multiple environments meaning that we have the CoE User account having API calls in environments that don't have any CoE related resources. Is this intended? 

We were expecting to have all the API requests to come from the environment that hosts the CoE not from all the environments that CoE inventories. 

We are using the Power Platform Requests Report in the Power Platform Admin Center. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2024

### What app or flow are you having the issue with?

API Calls

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3582

**Comment by Jenefer-Monroe** [comment]
I'm not sure how they allocate API calls, can you share exactly which report you are viewing? 
I suppose if they are tracking by person it might make sense to allocate the Dataverse calls to (for example) get hte MDAs from different environments to that environment.

**Comment by nasilvae** [comment]
> I'm not sure how they allocate API calls, can you share exactly which report you are viewing? I suppose if they are tracking by person it might make sense to allocate the Dataverse calls to (for example) get hte MDAs from different environments to that environment.

I'm referring to this report. 

https://learn.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations

It makes sense to report per environment and the coe account would make calls to those environments but I'm not sure.

**Comment by Jenefer-Monroe** [comment]
I see. Yes I'm not sure either. I'm afraid you'll need to find a product PM to talk with them to understand. We dont put anything in any other envt, but we do read from other environments. So perhaps that is why the calls are showing across the tenant.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
