### ISSUE TITLE
[CoE Starter Kit - QUESTION] Sys Admin PIM Enforcement 

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8478]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Team,

Considering the new changes regarding Sys Admin roles not being added automatically to a tenant. Is this only applicable when PIM is enabled or is this is something that we have to consider moving forward and enable the provided workaround fix. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2024

### What app or flow are you having the issue with?

System Roles

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3583

**Comment by Jenefer-Monroe** [comment]
Hello. Here is our write up for this https://github.com/microsoft/coe-starter-kit/issues/8119. 
It includes a workaround that you will need to download and install on your own for now. Once the connector / action is supported in all regions / clouds, then we can incorporate into the kit natively. 
Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
