### ISSUE TITLE
[CoE Starter Kit - BUG] Connection Page is not opening in the COE Power Platform Admin View app

### ISSUE THREAD

**Issue by Brice235i** [microsoft/coe-starter-kit#8479]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the Connection Identities page we are unable to open the details page for connections.  We have tried with multiple browsers and accounts. 
![image](https://github.com/microsoft/coe-starter-kit/assets/44307143/837ff78c-4faf-4afa-860f-1ef2b6d62ad3)
![image](https://github.com/microsoft/coe-starter-kit/assets/44307143/973da759-e96d-4d28-941e-effb322ac773)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Power Platform Admin View App

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

go to the app, click connection identities then click a particular connection name.

AB#3584

**Comment by Jenefer-Monroe** [comment]
Can you try from this app instead? **_Manage Permissions_**

Thats where we intended to have the custom page open. We can probably add to this other MDA app too but ... this way you wont be blocked and we'll know for sure if that's the issue.

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/94ca1f30-200f-4a02-8876-114f235964fc)

**Comment by Jenefer-Monroe** [comment]
I added the custom page to PPAdmin as well for July, thanks for posting!
