### ISSUE TITLE
[CoE Starter Kit - Feature]: CoE Dashboard PBI - Measure to show number of Production Apps

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#8480]
### Is your feature request related to a problem? Please describe.

Actually CoE Dashboard shows like Production Apps a count of all apps:
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/3c94398d-9bf6-4cac-a2bb-8484010d3c4a)

### Describe the solution you'd like

In CoE Dashboard PBI adding this measure:
Count of Production App = COUNTROWS(FILTER('Power Apps', [Production App] = TRUE()))
we can know the production apps following the criteria of sessions per month or usique users per month
![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/1fd91467-ef48-4e97-aaf5-301fc6ee0a83)

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/054583c3-95df-4bf0-8298-7d2164b5205d)

![image](https://github.com/microsoft/coe-starter-kit/assets/57954993/eb140f02-7c84-42a6-be54-70133da69f79)

AB#3585

**Comment by Jenefer-Monroe** [comment]
I'm not a PBI expert so thanks for these steps. Please let me know if it looks correct. 
[July PBITs.zip](https://github.com/user-attachments/files/15887015/July.PBITs.zip)
