### ISSUE TITLE
[CoE Starter Kit - Feature]: Integrate new audit log methodology into the kit for API reduction

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#8482]
### Is your feature request related to a problem? Please describe.

Here is the link to Pete's work https://github.com/petepuu/coekit-auditlogsync-v3
We will integrate with it.
Please investigate on your own if you need this early and get him feedback!

### Describe the solution you'd like

Unsure but current idea is to have a single flow with a env var to switch which method to use. 
This so that people dont have to re-setup unless they are able to use the new methodology.

AB#3598

**Comment by Jenefer-Monroe** [comment]
To convert from the old API (Office 365 Management API, https://manage.office.com) to new API (Graph API, https://graph.microsoft.com)

1. Add the API permission to the existing app registration, and get it granted by admin.
Microsoft Graph - Application permissions - AuditLogsQuery.Read.All
![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2ffc1a62-a501-407d-a307-6bcdc9a64b42)


2. Import a version of the kit with the new API integrated (estimate ship in August 2024 version or use the below).  

3. Set the env variable **_Audit Logs - Use Graph API_** to yes (true)![Image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d5a2fc82-19ed-40ff-ba3c-09ab8c8c7a9b)

4. Restart **_Admin | Audit Logs | Sync Audit Logs (V3)_** flow to ensure it gets the env var change

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by Daren2023** [comment]
Good Morning Jenefer,
After attending the CoE Office Hours, I followed your directions list above and made the required changes to Sync Audit Logs V2 and app registration. In this thread, there is reference to Pete’s work on Sync Audit Logs V3. Should we be adding the V3 version to the CoE or wait and it will be included in the September core solution?

**Comment by Jenefer-Monroe** [comment]
It should be v2 still. At first it had been renamed v3 but I changed it back. Sorry for the confusion!

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by plattasia** [comment]
Hello, can we please update the official instruction on the audit log - https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http about using this as well, easier to know what to do then finding it in change logs. 

thanks :)

**Comment by tocri** [comment]
Hi, How can i see the changes in COE ? Active audit logs (in PP Admin View) looks the same as before
