### ISSUE TITLE
[CoE Starter Kit - QUESTION] Can I extend the starter kit with managed solutions

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#8484]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have created a couple of flows that use two tables from the starter kit. Environment and Flow. I have created the customisations in a managed solution and that solution sits on top of the starter kit.
![image](https://github.com/microsoft/coe-starter-kit/assets/17124284/52f6a66f-141f-465b-9b8e-3c90aa25742c)
Is there any issue with upgrading the starter kit if I use a managed solution for our customisations? Your documentation says to use an unmanaged solution but I have just upgraded the CoE and there were no errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2024

### What app or flow are you having the issue with?

Customised

### What method are you using to get inventory and telemetry?

None

AB#3600

**Comment by DominicMeznik** [comment]
Hi, yes it´s possible. You can find instructions and best practices here:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

**Comment by medicineshow** [comment]
Hi, thanks but that hasn't answered my question. I have read that and it is in that document that it says use unmanaged solutions but does not state why. I want to know if I use a managed solution that includes the two tables, will that impact on any future upgrades to the CoE?

**Comment by DominicMeznik** [comment]
You should use unmanaged solutions on your dev system but the deployment to your production system should be as managed solution.

**Comment by Jenefer-Monroe** [comment]
I'm not an ALM expert and have never tested this personally, so I really don't know the consequences you would face. 
My own extensions in my personal tenant are built in an unmanaged solution as suggested so I've never tested this. 

Here is a starter link to get you the information you may need to explore. https://learn.microsoft.com/power-platform/alm/solution-concepts-alm

And perhaps, let us know why you would want to build in a managed one instead of unmanaged?

**Comment by Jenefer-Monroe** [comment]
I think you can deploy both as managed to your prod envt, that is fine. Is that what you mean?

**Comment by medicineshow** [comment]
Yes that is what I mean. I want to confirm that I can deploy a managed solution on top of the CoE managed solution that uses two of the tables from the CoE solution and that it will not affect any future CoE updates.

**Comment by Jenefer-Monroe** [comment]
I have not tested this so I cant say for sure if that will work. However it is similar to what we do all the time (deploy managed gov on top of managed core) so I think it should work.

**Comment by medicineshow** [comment]
Thanks
