### ISSUE TITLE
Solution "Center of Excellence - Core Components" failed to import

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#8485]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :The uninstall operation will delete the base layer for the component 'AppModuleRoles' with id 'e50feeb1-6fba-4390-84ac-5005a84f226d'. The operation cannot continue because there are other managed layers over the base layer. You can use the solution layers to find out which other solutions are blocking the operation.

### Expected Behavior

Solution "Center of Excellence - Core Components" should be imported successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32

### What app or flow are you having the issue with?

enter of Excellence - Core Components

### What method are you using to get inventory and telemetry?

Data Export

AB#3601

**Comment by Jenefer-Monroe** [comment]
Hello, Another person hit this before. It is a very bizarre issue, some kind of odd product issue. He was able to resolve and here are his notes: https://github.com/microsoft/coe-starter-kit/issues/8245

Please explore that issue to see if you can resolve.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
