### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE: DebugBYODL>ConfigureEnvironment Forbidden The backend request failed with error code '403'

### ISSUE THREAD

**Issue by JulesCam** [microsoft/coe-starter-kit#8486]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Flow: DebugBYODL>ConfigureEnvironment has failed continuously. I receive the message "Forbidden" "The backend request failed with error code '403'". Can you help me to resolve?

We are not using data export. 

### Expected Behavior

Unknown

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

DebugBYODL>ConfigureEnvironment

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

<img width="835" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/132581331/5d8a39b6-b475-4d6a-b683-54e9a6c8aae6">

AB#3602

**Comment by Jenefer-Monroe** [comment]
This is a helper flow, only for those struggling with a specific step in the Data Export (BYODL) setup. 
So if you are not using that architecture, you will not need this flow.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
