### ISSUE TITLE
[CoE Starter Kit - Feature]: Licensing Details

### ISSUE THREAD

**Issue by DominicMeznik** [microsoft/coe-starter-kit#8488]
### Is your feature request related to a problem? Please describe.

It would be awesome to have some metrics on the licensing situation of a tenant such as:

1. How many people are licenses
2. How efficiently are those licenses used (e.g. 1 licensed user using multiple premium apps)
3. Suggestions on licensing new people

### Describe the solution you'd like

It could make sense to introduce a new inventory metric (licensing) if it´s possible to get this data.

Based on that enhancements to the CoE & Power BI Dashboards can be made

AB#3604

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. This is a highly requested feature, but unfortunately we don't have access to the required information for this for the kit. I suggest asking for this as a product feature in their reports
