### ISSUE TITLE
[CoE Starter Kit - QUESTION] Non-Prod Environment Install Notifications and Actions

### ISSUE THREAD

**Issue by rmedrano2** [microsoft/coe-starter-kit#8493]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

If we mark the environment as non-prod - can we get some clarification as to what the implications of this are to the install.  We have an existing install in a Prod Environment, but are installing the latest version into a non-prod environment with the hopes of being able to test out changes and features before rolling out to prod.  It looks like it mostly revolves around not sending any notifications out, but will the inventory and compliance flows still be taking action on our apps our other environments?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

June 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3610

**Comment by Jenefer-Monroe** [comment]
Hello, are you referencing the environment variable? 
Yes that is what it does. It wont send out mails to end users, just to admin. It wont actually delete any objects, things like that. 
Hope that helps.

**Comment by rmedrano2** [comment]
> Hello, are you referencing the environment variable? Yes that is what it does. It wont send out mails to end users, just to admin. It wont actually delete any objects, things like that. Hope that helps.

Great, does that mean that the compliance / quarantine process also won't take any action on the objects in the environment?

**Comment by Jenefer-Monroe** [comment]
It will send the mails for your testing, to the admin email configured. This is so that you can do your testing. 
But operations like quarantine check for this env var before proceeding as shown here:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a81eccdd-242a-4f23-b1a2-1262790bbf3c)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
