### ISSUE TITLE
[CoE Starter Kit - QUESTION] Hello,  I noticed in Audit logs | Sync Audit Logs V2 secret expired. 

### ISSUE THREAD

**Issue by rjpiazza** [microsoft/coe-starter-kit#8498]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Thanks in advance....
I noticed  the secret expired.  I created a new secret; how do I update the value in the CoE to reflect the new value?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April solution

### What app or flow are you having the issue with?

Audit logs | Sync Audit Logs V2

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3615

**Comment by Jenefer-Monroe** [comment]
If you are storing as a plain text secret then you just go update the environment variable, if you are using Key Vault then you go update the secret there. 

Sorry I'm not quite sure I understand the question. Can you please let me know where you might need help from above? Happy to help if I can.

**Comment by rjpiazza** [comment]
Hi and thanks for responding.  

I noticed that flow Sync Audit Logs 2 V2 AdminlogsClientSecret expired.  I updated this  environment variable via the command center app, along with the AuditLogsClientId.

Now I still get an error running this flow....see screen shot below.  Thanks for your help....
![Synch flow error](https://github.com/microsoft/coe-starter-kit/assets/18033351/aed8f759-3d3b-430b-8d16-f91365c52980)

**Comment by Jenefer-Monroe** [comment]
Can you please let me know, are you storing the secret as plain text or in the Azure key vault? That will help me give you the next set of investigation steps to take.

**Comment by rjpiazza** [comment]
Plain text....thank you

**Comment by Jenefer-Monroe** [comment]
Thank you, ok please open the last attempted run for Admin | Audit Logs | Office 365 Management API Subscription
### Client ID
Is the app id correctly ingested here? It should be the Application ID of the app, not its Object ID.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/97eee119-aae8-4b4e-95f4-2f5e6bd49feb)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f7537bcb-73f6-41b6-bff3-2d60bf9a947f)
### Secret
Is the secret correctly ingested here? This should be a *secret* and not a GUID. This is a common mistake so please do take a look and let me know.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/9783b8d9-4ddb-40d7-928f-eeeeb9c1145a)
Does this call fail hence correctly marking the variable as false?
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0da62240-6cef-42b5-96fd-6b8bea57cb48)

**Comment by rjpiazza** [comment]
Secret
Is the secret correctly ingested here? This should be a secret and not a GUID. This is a common mistake so please do take a look and let me know.
[image.png (view on web)](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fassets%2F89584709%2F9783b8d9-4ddb-40d7-928f-eeeeb9c1145a&data=05%7C02%7Crichard.piazza%40stonybrookmedicine.edu%7C0747ccd7f87842bfc5c908dc91208316%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C638544816057882319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=0l2zNlOvyWIXJ8F2thMmQF7jwPvlaE4QNNfmYv%2FeBnM%3D&reserved=0)
Does this call fail hence correctly marking the variable as false?
[image.png (view on web)](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcoe-starter-kit%2Fassets%2F89584709%2F0da62240-6cef-42b5-96fd-6b8bea57cb48&data=05%7C02%7Crichard.piazza%40stonybrookmedicine.edu%7C0747ccd7f87842bfc5c908dc91208316%7Ceafa1b31b194425db36656c215b7760c%7C0%7C0%7C638544816057889456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=OXoAvRKOcqTLhJhvKCJF5HDW4v05ywvK55RlYzOL2ts%3D&reserved=0)




The secret value i correct and yes this call fail hence correctly marking the variable as false?

**Comment by rjpiazza** [comment]
Hi,


var Secret_AzureType is false
