### ISSUE TITLE
[CoE Starter Kit - QUESTION] Orphans in Inactive Notifications

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#8499]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

When a user leaves the company their sign-in is blocked and takes about 30 days for the account to get deleted. This week I noticed that the inactivity notifications for these users are sent to the admin, which makes sense since they can no longer receive them. 
In the flow 'Admin | Inactivity notifications v2 (Start Approval for Flows)' I see the re-assignment to the Admin for the notification but I wasn't able to find something that categorizes that flow/app as orphan right there and then. I take it we have to wait until the orphan process picks it up and ignore the inactive notifications? 

Thank you in advance PowerCAT team!

![image](https://github.com/microsoft/coe-starter-kit/assets/70606628/ba7b9d49-21de-44c8-971a-6f132c8a540c)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2024

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3617

**Comment by Jenefer-Monroe** [comment]
Yes thats correct. If you de-activate them and then later delete, you can set this env var, and they will be treated as orphaned once they are disabled (and orphan check flow runs)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/abe26f5f-3a2a-4093-a2e8-0477b95b9a04)

If you set it, please be sure to turn that flow off and back on to ensure the env var value isnt cached in the flow.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
