### ISSUE TITLE
CoE App Deep Dive returning app not found for multiple CoE in different tenants and environments

### ISSUE THREAD

**Issue by DaymondMartin** [microsoft/coe-starter-kit#8502]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

app deep dive in CoE returning app not found - The environment '5730bbd8-************-28cdadcb1a1e' could not be found in the tenant '588cadf4-************-8bcf04f4f102'. Session ID: d86e976c-************-842a52facac1 
this error is common to different environments... (All different tenant environments returning same error) 
How do I go about that?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Power Bi visualization - app deep dive

### What method are you using to get inventory and telemetry?

None

AB#3620

**Comment by Jenefer-Monroe** [comment]
Did you do this steps to [configure the embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard)?

**Comment by DaymondMartin** [comment]
Thank you, that assisted me.

here is the solution in a video format

https://www.youtube.com/watch?v=-flTFzomkdc
