### ISSUE TITLE
[CoE Starter Kit - Feature]: FEATURE TITLE

### ISSUE THREAD

**Issue by alanmWDC** [microsoft/coe-starter-kit#8504]
### Is your feature request related to a problem? Please describe.

Flow last launch isn't populated when using the Flow sync method

### Describe the solution you'd like

I have implemented a Flow that runs daily looping through eligible environments to query the new "Flow Runs" table in each environment. This gets all successful Flow runs for the previous day and then updates the Flows table row matching on the resourceid to the table unique identifier that is returned in the List Rows on the Flow Runs table.

### Describe alternatives you've considered

Using the Data Export but has a cost associated with it that organizations do not want.

### Additional context?

![image](https://github.com/microsoft/coe-starter-kit/assets/144744864/405d0ef6-6b0f-408c-95dd-2b6a78617015)

AB#3622

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, yes this is the type of thing we plan to do once the product associated is GA and then we are able to get a resource to do this. In the near term, you will want to do this work though on your own so I'm glad you got unblocked!

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
