### ISSUE TITLE
[CoE Starter Kit - BUG] Cloud Flow Runsにレコードが表示されない

### ISSUE THREAD

**Issue by kameitakahiro2com** [microsoft/coe-starter-kit#8505]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

現在、ver 4.29のCoE Starter Kitを利用しております。
私は「Power Platform Admin View」アプリ内でクラウドフローの実行履歴を確認したいと考えています。
しかし、アプリ内で「Flows」> 「Related」 >「Cloud Flow Runs」を確認したが、何も表示されません。

恐らくCoE Starter Kitインストール時に問題点があったのではないかと考えていますが、具体的な問題点は不明です。

この問題の原因と対応策を教えていただけますでしょうか。

※確認しているユーザー(私)はM365テナントのグローバル管理者権限を持っています。

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

 Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

AB#3623

**Comment by Jenefer-Monroe** [comment]
Hello. This table has been deprecated and we have never filled it with anything.

This information is not yet available to us. The product team does not write this in a consumable way but its not yet Generally Available. Please see [Store cloud flow execution metadata in Microsoft Dataverse](https://learn.microsoft.com/power-platform/release-plan/2023wave2/power-automate/store-cloud-execution-history-dataverse)

Once that is available generally we will likely consume it for something but it will not be to populate this table it will more likely be something like just a "last run" column being filled.

**Comment by kameitakahiro2com** [comment]
Thank you for your answer Ms Jenefer-Monroe!
