### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Starter Kit setup upgrade wizard configure communication methods fail to get groups created in azure

### ISSUE THREAD

**Issue by JasonWoon** [microsoft/coe-starter-kit#8506]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Already import CenterofExcellenceCoreComponents_4.31_managed zip in but still cannot find the azure group admin/maker/user in configure communication methods.
refer to attachment pictures. 

### Expected Behavior

expecting able to search Azure group but didnt show up

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

CoE Starter Kit setup upgrade wizard

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. In dev environment.
2. imported in CenterofExcellenceCoreComponents_4.31_managed zip
3.  setup upgrade wizard configure communication methods fail to search All Azure group created 

### Anything else?

![3COEGroupsCreated](https://github.com/microsoft/coe-starter-kit/assets/172562861/aa854d68-1d7b-453d-85cd-64e5a03753fe)
![AZO-ACC-PowerPlatformCoE-Admin](https://github.com/microsoft/coe-starter-kit/assets/172562861/d3b577cf-97f8-4686-978b-95ea1ba74edb)
![AzureCOEAdminProperties](https://github.com/microsoft/coe-starter-kit/assets/172562861/ee3ee1ee-70ed-4564-822e-07ee34c078f0)
![configure communication methods](https://github.com/microsoft/coe-starter-kit/assets/172562861/afbeca32-8515-40a5-ac39-cf4b9e070f70)

AB#3625

**Comment by Jenefer-Monroe** [comment]
Hello, we have had people struggle with this sometimes. We are using an out of the box connector for the search.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f91bd173-2faa-41bc-a00c-171a4d259c4d)

Im afraid in this case we just instruct people to paste the group id (for makers/users) and the email (for admin)

**Comment by JasonWoon** [comment]
when paste email for admin it shows this error
![Uploading COE-AdminEmailError.jpg…]()

**Comment by Jenefer-Monroe** [comment]
I can help you find a repro for outside the kit if you'd like, to take to support, or we can just get you unblocked. 

### Here is how you can upate the env vars manually :  

Go to the default env't, select the env var, add current, add put in your values

For Admin, add the email to Admin eMail
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/45f54e91-9132-49a4-9e9b-7eed8c43122d)


For Maker and User, and the GUID
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/c9ff3947-6e37-4f55-aa42-bf167a235178)

**Comment by JasonWoon** [comment]
Hi,
I'm able to add the Emails and ID already thanks
