### ISSUE TITLE
[CoE Starter Kit - QUESTION] Not showing the Orphaned status for canvas apps and flows 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#8508]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the CoE toolkit, we use regular flows to crawl the tenant and retrieve information about apps and flows. Occasionally, after a user leaves the organization, their apps and flows are marked as orphaned.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3627

**Comment by Jenefer-Monroe** [comment]
Sorry not quite following, what is your question? We do detect orphans each week via this flow: CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

**Comment by Jenefer-Monroe** [comment]
Looks like this was an accidental duplicate post to https://github.com/microsoft/coe-starter-kit/issues/8509, will close this one out.
