### ISSUE TITLE
[CoE Starter Kit - QUESTION] Discrepancy in Orphaned Status for Apps and Flows in CoE Toolkit

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#8509]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In the CoE toolkit, we use regular flows to crawl the tenant and retrieve information about apps and flows. Occasionally, after a user leaves the organization, their apps and flows are marked as orphaned.
What criteria are used to mark apps and flows as orphaned in the CoE tables?
What we have noticed is that some users who have already left the organization have their respective apps and flows still not marked as orphaned in tables.
I have seen the co-owners' status, and a few apps don't have any co-owners at all and few have. Ideally, these should be marked as orphaned in the CoE apps table.
![image](https://github.com/microsoft/coe-starter-kit/assets/29652263/e8a60358-b9ae-455c-a22b-9cf48b842c31)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4,31

### What app or flow are you having the issue with?

Admin-Sync V3 Template 

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3628

**Comment by Jenefer-Monroe** [comment]
Hello, we do not consider co-owners for the notion of orphans, only the primary owner. It is on our backlog to consider co-owners but that isnt something we have resources to fund in the near term. 

A maker being an orphan by default means they have been deleted from Entra but we do have an environment variable you can use if you want us to also consider disabled users as orphaned. 
Note you will want to restart all flows that have a dependency on this env var if you change it as sometimes flows cache env vars. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3f0e2d8d-dcfd-433d-989b-dc4dc82c4aa2)

The above is all done by this flow: CLEANUP - Admin | Sync Template v3 (Orphaned Makers) which runs weekly.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
