### ISSUE TITLE
[CoE Starter Kit - BUG] - Audit Log Power Automated Flows Failing to Complete its Run with Error Message

### ISSUE THREAD

**Issue by David-Liong** [microsoft/coe-starter-kit#851]
### Describe the issue

Dear Team,

I have successfully installed one of the component  audit log solution **CenterofExcellenceAuditLogs_1_3_2_managed.zip** into the organisation Power Platform environment by following https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector back in December 2020.

As more end-users in the company are starting to use CoE,  I've recently activated (turn on) the **[Child] Admin | Sync Logs** and **Admin | Sync Audit Logs** flows. The Admin | Sync Audit Logs is scheduled to run every 24 hours every morning.

I notice that the [Child] Admin | Sync Logs runs multiple instances of the flows at around the same batch time in the morning and most of these flows has failed every morning
![image](https://user-images.githubusercontent.com/71060262/125727319-151e9f99-064b-4b5a-811d-d9f8f1ca5413.png)

All the failed flows shows the same error message:
_Rate limit is exceeded. Try again in 2 seconds. Please see https://docs.microsoft.com/azure/logic-apps/handle-throttling-problems-429-errors for more details._

Reading the error from the link means that Microsoft is throttling during business hours, which cause the number of requests exceed the rate at which the destination can handle over a specific amount of time. Throttling can create problems such as delayed data processing, reduced performance speed, and errors such as exceeding the specified retry policy.

1. Do you know why if this issue is a normal expectation. If not how do I solve this error?
2. Do you think I need to get the latest audit log solution CenterofExcellenceAuditLogs_x_x_x_managed.zip and install the latest? If so which version of audit log solution is stable?

I also notice this warning message displayed on Power Automated platform
"Your flow's performance may be slow because it's been consuming more data than expected since 06/07/2021 16:03:45 (1 week ago). Learn more"
![image](https://user-images.githubusercontent.com/71060262/125727913-00de8f0e-01ee-48fb-82ff-db8a1b1be909.png)

3. What do this error mean when I visit the error link https://docs.microsoft.com/en-us/power-automate/limits-and-config ?

Thanks and hear from you soon.

Kind regards
David Liong

### Expected Behavior

I expect the error flows to go away or have less errors appearing in  [Child] Admin | Sync Logs flow

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.3.2

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs & 

### Steps To Reproduce

1. Logged into https://australia.flow.microsoft.com/manage/environments. Navigate to solution from left menu and double click  Center of Excellence - Audit Logs solution
![image](https://user-images.githubusercontent.com/71060262/125728405-abf0419e-330d-4866-b7f7-d6b31c8e2cc8.png)
2. Double click   [Child] Admin | Sync Logs

**Comment by JeneferM-MSFT** [comment]
Hello you have hit a throttling limit with your flow. This is an expected failure used to protect the service from DOS type attacks. This means you have a lot of data returned. The good news is that the product team is working to write the inventory and usage natively and we will no longer use these sync flows. This is in a feature called Bring your own Datalake (BYOD). 

While you await the BYOD feature, you can request an exemption to the throttling, but please note that it will be temporary and expire once that feature is available. 

Here are the steps to follow to request the exemption: 
1)	Gather the flow ids for the flows that are being throttled. 
2)	Create a support ticket with the following information: 
        - Purpose of ticket: Power Automate throttle request - raise throttle limit 
        - Refer support to this GitHub item: [# 548]([CoE Starter Kit - BUG]: Admin | Sync Template v3 (Check Deleted) does not finish · Issue #548 · microsoft/coe-starter-kit · GitHub).  It contains information that will help support work more quickly through the process.

**Comment by JeneferM-MSFT** [comment]
No further action for the toolkit so closing out.
