### ISSUE TITLE
[CoE Starter Kit - Feature]: PowerApps App View Abandoned PowerApps View - confusing so please remove it

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#8511]
### Is your feature request related to a problem? Please describe.

When researching abandoned apps the view "Abandoned PowerApps" on the table "PowerApps Apps" in the app "Power Platform Admin View" doesn't show me as much useful information as possible and always results in my editing the view.

The problem is that the view also shows "Deleted" apps, so I might look at the view and see 100 records. But actually 70 of them have been deleted, so they are not abandoned any more as they don't exist. So really there are only 30 abandoned apps. Also it shows model-driven apps, which I believe, can't, or can't easily have an owner assigned to them so they are useless information for this view.

### Describe the solution you'd like

- In the app "Power Platform Admin View",
- On the table "PowerApps Apps",
- On the View "Abandoned PowerApps",
- Two additional filters added of 
- "App Deleted" Equals "No"
- "App Type" Does not equal "Model Driven"

This would then filter out all deleted apps and model-driven apps, making the View a lot more useful.

### Describe alternatives you've considered

Alternatives are either edit the View for a moment in time and then when done let it revert back, or create a personal view. 

Both are okay options, but it would be better if the product provided this view.

AB#3630

**Comment by Jenefer-Monroe** [comment]
I think you are looking for the "Orphaned Canvas" view which should be there already. Can you please check?

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe,
Thanks for the quick response, you're right. I can see that view. 
May I ask, what is the "Abandoned PowerApps" view for, please?

**Comment by Jenefer-Monroe** [comment]
I don't know. I think someone maybe just added that without finishing it all the way or something. To my knowledge its not really used. Perhaps I should just remove it.

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe,

Thanks for the reply. I agree, if it's not being used and not useful, then remove it. It's probably causing more confusion than good. 

Thanks for pointing out the "orphaned canvas apps" view.

Garry

**Comment by Jenefer-Monroe** [comment]
Will do.
