### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flow Action Details) Failed , where is the connection ?

### ISSUE THREAD

**Issue by fim34** [microsoft/coe-starter-kit#8512]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello we have email notification of one flow run was failed because of Get Flow action. its same as #7825 but after checking with a service account,  there no connection to fix in connection tab and i not find one with name "shared_logicflows" or id.
All connection reference are good.
The service account is owner of this flow.

So what next to check? there is a way to check with connection id ?

            "code": "ConnectionAuthorizationFailed",
            "message": "The caller object id is '7d18c858-5dd0-4549-95ba-d5784afc83cf'. Connection 'f40b6a84-dff9-497a-a418-fb124741fbd0' to 'shared_logicflows' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."
        }
    }
}
![flow issue](https://github.com/microsoft/coe-starter-kit/assets/89391607/7c313c9c-cde0-4da1-a67e-87b883df13e3)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3631

**Comment by fim34** [comment]
to be sure created a new connection and changed it to new one. 
Still had one failed run today.

**Comment by Jenefer-Monroe** [comment]
Glad you got the connection fixed. 

Sounds like you don't have permissions then to the default envt. You have likely been impacted by new product behavior that just shipped around the way the product treats privileged roles (ex Power Platform Admin role, Global Admin role)

While there is a workaround we can put into the kit to fix this directly, we cannot ship it with the kit until the workaround is available in all regions. Hopefully for the July release.

### The product change
Here is information about the product feature: [Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)

### How to check if this is the case
1. Validate the user running the flow has direct and permanent assignment to the Power Platform Admin role.
2. Take one of the target environments in your repro, one of the environments which is failing, and make sure the user running the flow has System Admin security role in that target environment.

### How to address and More information
Please see https://github.com/microsoft/coe-starter-kit/issues/8119 for a write up on this change. 
Included also is a workaround you can do until we can have it natively in the kit.

**Comment by fim34** [comment]
Yes the service account have the Power Platform Admin role and is system admin in default environment.
Will check #8119 .
That may be good we update each three months and next update have to be the july release.

**Comment by Jenefer-Monroe** [comment]
Did you check today to see that they are sys admin there? I ask because Power Platform Admin Role no longer guarantees that (per the bug I referenced)

Please share the error you are getting from the flow for default. It likely a different one now right? The connection was broken before for all environments correct?

**Comment by fim34** [comment]
Yes the account is still sys admin on the default environment.
No the run flow failed is only for default, its worked before for other environment.

No still the same error.
```
![flow issue2106](https://github.com/microsoft/coe-starter-kit/assets/89391607/60ff4e96-9a4b-4c13-8948-1cdf7b121e4c)
```

**Comment by Jenefer-Monroe** [comment]
First, please summarize:

1. The account in question is this one: admin.g2s.svc-PowerPlatform....
2. This is the account that you verified is a System Admin in the default envt
3. This is the account that now has been selected here: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/76005e2f-06ce-4e63-a404-ad24fbc233a7)

Then please note, above this failure the user is explicitly granted access.
Can you please go up in the flow run for this loop and see what happens here? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4beff6b5-7cd1-4978-9973-1cf6fcd12c8f)

**Comment by fim34** [comment]
The account in question is this one: admin.g2s.svc-PowerPlatform.... > Yes
This is the account that you verified is a System Admin in the default envt > Yes
This is the account that now has been selected here > Yes connection existed and created and selected the new one.

![flow issue2406](https://github.com/microsoft/coe-starter-kit/assets/89391607/24405395-a36d-42df-a139-bb39ac194e52)

**Comment by Jenefer-Monroe** [comment]
1. Is 7d18... the correct GUID for admin.g2s.svc-PowerPlatform? 
2. Please go run this flow: **_HELPER - CloudFlowOperations_**

Using the parameters as sent form the failing flow:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bcf2abc7-8f0e-40c9-b853-c78e17c79033)

3. Open the run you created and see if it falls correctly into this case
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/cf338a76-63c5-46c2-9191-dc1ff2694119)

4. If so, what happens within the case? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1b1ee8cd-31e1-422e-8bb1-190370c7fcf2)

**Comment by Jenefer-Monroe** [comment]
according to that then the user should already have permission to the flow, so I'm not sure what state you are in. 
Please go to the flow in question itself, the one for which you ran this helper just now, and see what permissions are applied to it.

**Comment by fim34** [comment]
Permissions for Admin | Sync Template v3 (Flow Action Details), this ?
![flow permission](https://github.com/microsoft/coe-starter-kit/assets/89391607/954e0619-af22-4a45-9c93-e759c746b57f)

**Comment by Jenefer-Monroe** [comment]
Are you running the kit as a service principle? (not a service account but a service principle)

**Comment by fim34** [comment]
No all the flow use the service account.

**Comment by Jenefer-Monroe** [comment]
Oh sorry I didnt mean the owner of the flow action details flow, I mean the owner of the flow for which this is failing. 
The flow being called here: 
![Uploading image.png…]()

**Comment by fim34** [comment]
Its the same account for all flow so service account

**Comment by Jenefer-Monroe** [comment]
OK. Sorry I'm not sure I'll be able to assist here then. It seems like there is something going on with this particular flow but without being able to log in with you and explore we seem to be at an impasse.

**Comment by fim34** [comment]
If a teams call is needed i can be available next week

**Comment by Jenefer-Monroe** [comment]
Sorry we are not staffed up to meet with our GitHub users. There are 12k of you and only one of me, so we have to do our investigation here. 
Unfortunately I've run out of ideas, likely there was some miscommunication above, or something broken in your tenant. So perhaps re-walk the above and see if something new pops out to you, or pull in a local Power Platform expert to have them review.

**Comment by fim34** [comment]
Still here after udpate, so will check again all step in this post.
