### ISSUE TITLE
Not able to see data from other environment

### ISSUE THREAD

**Issue by aditijha005** [microsoft/coe-starter-kit#8513]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have installed the coe kit in a separate environment, and only for that environment data is showing the dashboard not for the other environments.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3632

**Comment by aditijha005** [comment]
Hi Jenefer,
We are installing coe kit for the first time in our organization. And the identity has given Power Platform Admin role through PIM.

Is this related to the previous case?

**Comment by Jenefer-Monroe** [comment]
Hello, yes you likely dont have the System Admin role for the identity running the flow in those environments. 
This is due to the product change I referenced. 
Please explore this write up and let me know if you have questions: https://github.com/microsoft/coe-starter-kit/issues/8119

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
