### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Audit Log

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#8516]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The output of the Audit log is only the startup of Power apps, but I wonder if other items are not captured.

![image](https://github.com/microsoft/coe-starter-kit/assets/156406138/04829b59-45ca-4978-8c37-c4325dba8b4c)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024 - 04

### What app or flow are you having the issue with?

none

### What method are you using to get inventory and telemetry?

None

AB#3637

**Comment by asuka1103131** [comment]
@petepuu I want the PowerBi audit log, where do I modify the flow?
If an app/flow is deleted, is the record not deleted but only the status is changed to this?

**Comment by petepuu** [comment]
@asuka1103131 You should create your own unmanaged solution for CoE Kit customizations and then copy the **Admin | Audit Logs | Sync Audit Logs (V2)** flow to your solution. Then modify flow in your own solution by adding new switch case for you event(s) in the **Apply to each Audit Log** apply to each loop similar like it is done for LaunchPowerApp events. 

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/aeddc0e7-3b7e-4d6b-9328-23c62bacbc9a)

<br><br>
See more details how customize the Kit from this doc
https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

<br><br>

Yes delete app/flow just the status is changed

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/37cfe076-741b-47e7-a156-7015fd5bd486)

**Comment by asuka1103131** [comment]
@petepuu 
Thanks for the clarification.
Where is the information obtained from the audit log?

**Comment by Jenefer-Monroe** [comment]
Here is the API used: [Office 365 Management APIs overview](https://learn.microsoft.com/office/office-365-management-api/office-365-management-apis-overview)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
