### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there a report that we can get that shows all the instant flows

### ISSUE THREAD

**Issue by henryed07** [microsoft/coe-starter-kit#8517]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are in a position that we ned to migrate to a different Dataverse environment, due to the Default being in Europe and we need it in the UK, Microsoft have said we need to export all Instant Flows. There doesn't seem to be a report anywhere that shows the flows that are instant. Or what is this called in the tables that store this information?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3639

**Comment by petepuu** [comment]
@henryed07 One way is to use Power Platform Admin View and add Flow Trigger column to the Cloud Flows list. Then add "Contains = Request" filter to that column. To have trigger info in the table you have to have Flow Action Details sync flow running. 

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/ae6f7253-ec3d-4fed-b9f1-2439121ed8f3)

![image](https://github.com/microsoft/coe-starter-kit/assets/8307644/d25e7acf-ce4c-4fbe-88d8-9065a2b80c5a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
