### ISSUE TITLE
[CoE Starter Kit - BUG] Missing apps for personal productivity (Default Environment) in the governance details report

### ISSUE THREAD

**Issue by LowCode-sudo** [microsoft/coe-starter-kit#8522]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Due to an empty column in the details dataset, there are no apps displayed for the personal productivity environment. I compared it to the normal report, where it works correct. Seems like an issue with the details dataset. Flows are displayed but apps are empty, the "Environment Name" column is empty, this should be the issue.
![Bild](https://github.com/microsoft/coe-starter-kit/assets/173452926/b3a2a04f-811b-4ddc-a126-91478ed07756)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June2024

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard_June2024

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

In the PowerPlatformGovernance_CoEDashboard_June2024 open the App Table, there you can see that the Environment Name Colum is Empty for the default Environment Apps.

AB#3651

**Comment by Jenefer-Monroe** [comment]
The envt filter is on the page as a whole, so I dont think that is the issue. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca042618-8012-4d7e-8424-6b373d1fe084)

Can you please go look in the Power Platform Admin View to see if there is data that fits these filters? 
You can add related fields as shown here for things like app owner is orphan.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f1b65a52-f66a-4530-b4bf-2399086a9381)

**Comment by Jenefer-Monroe** [comment]
Also note that PBI shows <<blank>> instead of 0 so blank = 0

**Comment by LowCode-sudo** [comment]
Hi, the Data is there, i think there is a problem with the provided PowerBI Report. Here is a screenshot of the Table if i try to get the Environment Name by the Environments Table and link it with apps: 

![image](https://github.com/microsoft/coe-starter-kit/assets/173452926/45c73d92-a085-4654-b0f9-5f448e483662)
![image](https://github.com/microsoft/coe-starter-kit/assets/173452926/dc9505e1-5501-41a7-8356-a777b7f589d6)


In the first column should be the environment name. When I access it through the Production_CoEDashboard_June2024 it works. So it seems like there is an issue with the data relation in the PowerPlatformGovernance_CoEDashboard_June2024

**Comment by Jenefer-Monroe** [comment]
ok looks like we didnt transform envtid for this case. Fix is to add this replace statement in the transform
`= Table.ReplaceValue(#"Replaced Value","Default-","",Replacer.ReplaceText,{"Environment ID"})`
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b3dcb922-ce1b-459e-bb4c-2048e6ba4c3f)
