### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION about the description of some certain flows and apps

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#8523]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!
Could I ask whether it is possible to find anywhere the description of these flows and apps? Or whether it is possible for you to share at least a short description of the flows and the app. As the description for these flows is not available in Power apps:

flows:

- Admin | Gather Tenant SRs
- HELPER - Delete Connection
- CLEANUP HELPER - Solution Objects
- CLEANUP HELPER - Environment Capacity
- HELPER - Get Connections to Clean

app:

CoE Admin Environment Request (preview)

Thank you in advance!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What method are you using to get inventory and telemetry?

None

AB#3652

**Comment by Jenefer-Monroe** [comment]
Hello, we have a big update coming to the documentation that is still in review, and we did add these to the flows themselves when we made that change. Sharing them here for you: 

Admin | Gather Tenant SRs
This flow retrieves the Security Roles in your tenant and ensures they are in the Tenant Security Roles table for management.

HELPER - Delete Connection
This flow is called from Manage Permissions app and deletes connections from the tenant.

CLEANUP HELPER - Solution Objects
Does the solution to object mapping work which is too API intensive to do daily.

CLEANUP HELPER - Environment Capacity
Gathers the Capacity information for each environment.

HELPER - Get Connections to Clean
This flow is called from Manage Permissions app and returns connections from the tenant for the admin to explore.

**Comment by JanetK12** [comment]
> Hello, we have a big update coming to the documentation that is still in review, and we did add these to the flows themselves when we made that change. Sharing them here for you:
> 
> Admin | Gather Tenant SRs This flow retrieves the Security Roles in your tenant and ensures they are in the Tenant Security Roles table for management.
> 
> HELPER - Delete Connection This flow is called from Manage Permissions app and deletes connections from the tenant.
> 
> CLEANUP HELPER - Solution Objects Does the solution to object mapping work which is too API intensive to do daily.
> 
> CLEANUP HELPER - Environment Capacity Gathers the Capacity information for each environment.
> 
> HELPER - Get Connections to Clean This flow is called from Manage Permissions app and returns connections from the tenant for the admin to explore.

Hello @Jenefer-Monroe ! Thank you for your answer! It helped a lot!
Great to hear that in the future we will receive an update to the documentation!

**Comment by Jenefer-Monroe** [comment]
The documentation update should ship this week.

**Comment by Jenefer-Monroe** [comment]
going to go ahead and close this out although we still await the documentation ship. 
please feel free to open new issues as they arise
