### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE User Set Up Best Practice

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#8526]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello CoE Team,

Hope you are well. 

I have a question about the best practice when installing and using the Centre of Excellence. I read the information on this [document ](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)about identity.

What is the recommended approach for the "user" of the CoE implementation and maintenance? 

1. Is it use a service account to own the components like apps and flows?
2. Does the service account need MFA disabled? 
3. Can a service principal be used to own the components such as apps and flows and run the flows?

Any help would be much appreciated.

Thanks very much,

Garry

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3656

**Comment by Jenefer-Monroe** [comment]
Thanks for posting

1. Is it use a service account to own the components like apps and flows?
We don't really have a recommendation for this. I can tell you that this is what most people do, yes. 
That way you can share the account amongst a team and there is not disruption when people leave the organization.

2. Does the service account need MFA disabled?
The product does support MFA, you can see how to set this up here: 
https://learn.microsoft.com/power-platform/guidance/coe/limitations#mfa-multi-factor-authentication

3. Can a service principal be used to own the components such as apps and flows and run the flows?
Many of the connectors we use do not yet support service principals. For example the Dataverse connector does not support them. As a result, the kit cannot be installed as one. 
Note that we do have this listed in the upcoming release of the documentation limitations, but its still in review.

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe, 

Thanks so much for the information above, really useful. I'll investigate about the MFA, thanks for the link.

Please close this ticket. 

Garry
