### ISSUE TITLE
[CoE Starter Kit - BUG] GetAzureTenantInformation.Run failed: BadGateway for the Center of Excellence - ALM Accelerator - 1.0.20240305.1 Solution

### ISSUE THREAD

**Issue by Singapuram** [microsoft/coe-starter-kit#8528]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Upon opening the ALM Accelerator Admin APP, the following error is displayed. I have successfully set up and confirmed the configuration of the ALM Accelerator Custom Connector - CustomAzureDevOps, with the connection status response showing as 200.

GetAzureTenantInformation.Run failed: { "error": { "code": 502, "source": "unitedstates-002.azure-apim.net", "clientRequestId": "840ff97d-f2b6-4323-ba97-11c37686fec6", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not receive a response from an upstream server. Request tracking id '08584824246876458256096279417CU48'." } } } }

![image](https://github.com/microsoft/coe-starter-kit/assets/78669287/b444bb42-a725-42e6-98de-657b2ac45e76)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Center of Excellence - ALM Accelerator - 1.0.20240305.1

### What app or flow are you having the issue with?

ALM Accelerator for Power Platform Admin App

### What method are you using to get inventory and telemetry?

None

### Anything else?

Center of Excellence - ALM Accelerator - 1.0.20240305.1

AB#3658

**Comment by MaheshSripada** [comment]
Can you pls verify / provide the screenshot of the below flow run

GetAzureTenantInformation from the Center of Excellence - ALM Accelerator solution

**Comment by Srikanth-Singapuram** [comment]
@MaheshSripada  this was fixed and here are the [details ](https://github.com/microsoft/coe-starter-kit/issues/7256#issuecomment-2227820375)

Thank you.

**Comment by MaheshSripada** [comment]
Thank you @Singapuram, Closing this ticket as it is resolved now.
