### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Centre - Re-publishing is not available

### ISSUE THREAD

**Issue by FQ365Microsoft** [microsoft/coe-starter-kit#8529]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In Developer compliance centre, users get request to republish the app but when they open, they are seeing the message: "The latest version of the app is already published. Re-publishing is not available. Marking as Submitted".

When we look into the code, it is showing the condition, 

> DateValue(vSelectedAppN.'App Modified On') = DateValue(vSelectedAppN.'App Published')

This doesnot look correct as the complaince email must have been sent by checking the last publish date that it is older than the enviornment variable but this check is not looking for current date or enviornment variable at all. Can you please suggest?

### Expected Behavior

Republish option should be available instead of the message.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Developer Compliance Center Canvas App page

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Open the App for which republish is due but the app modified date and App published date is same.

AB#3659

**Comment by Jenefer-Monroe** [comment]
Here is the UX they should see, is that not what they see? Can you please share a screenshot? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e776b2d3-b37b-4ae9-a36e-15c55a6b8ffc)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
