### ISSUE TITLE
[CoE Starter Kit - BUG] Core components Flow Admin | Sync Template v3 (Apps) - Shared with Tenant not being set

### ISSUE THREAD

**Issue by SBadwal17** [microsoft/coe-starter-kit#853]
### Describe the issue

Hello all,

We have the COE Starter kit setup in our COE environment and when the Admin Sync template runs it triggers the (Apps) Flow too. This Flow also checks whether an app is being shared with the Tenant and if so it sets "Shared with Tenant" to true in the PowerApps App entity for the app. This used to work fine however more recently doesn't work.

We have tested this with a app in Personal Productivity being shared with "Everyone" and yet when we run the flow the flag always False. Has something changed? Is anyone else experiencing this too?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.1.70

### What app or flow are you having the issue with?

Admin - Sync Template v3 (Apps)

**Comment by JeneferM-MSFT** [comment]
investigating

**Comment by JeneferM-MSFT** [comment]
I have just validated that this works for us, both for default environments and non-default. 
Can you please validate
1) Is the (apps) sync flow running and passing for the default environment?
1) Do you have any [unmanaged layers](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) which would prevent you from seeing the flow as currently released?
1) Does this repro for several apps or just one? 
1) Does this repro for several envts or just default? 
1) Is the app of type Canvas? 

You may also want to try installing [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

**Comment by SBadwal17** [comment]
Hi Jenefer,

Thanks for your reply. Please see answers below;
**Is the (apps) sync flow running and passing for the default environment?**
The flow runs successfully in all environments
**Do you have any unmanaged layers which would prevent you from seeing the flow as currently released?**
No unmanaged layers, upon upgrading the version I removed all the unmanaged layers
**Does this repro for several apps or just one?**
So far tested on about 3-4 different apps
**Does this repro for several envts or just default?**
This is in all environments. Our default is the personal productivity and also tried with apps in other environments. 
**Is the app of type Canvas?**
All the apps tried are of type Canvas.

Thanks

**Comment by JeneferM-MSFT** [comment]
Can you share a screenshot of what sharing with the tenant looks like for you, from the product ux, for one of your repro apps? 
Note that screenshots can only be shared from GitHub, they will not show up if you put then in an email response.

**Comment by SBadwal17** [comment]
Apologies for late response. Please see screenshot below.
The way we share with the tenant is to go to Share screen, and add Everyone in "company name". Is this correct?

![screenie](https://user-images.githubusercontent.com/87474942/126284998-b25a35e8-88c9-4257-8719-4f8bed3f8952.PNG)

**Comment by JeneferM-MSFT** [comment]
Yes, thats correct. 
I'm unsure how to proceed as I do see this working. Can you find an app that repros in one of the runs? To see how it goes down the flow paths?

**Comment by SBadwal17** [comment]
Hi Jenefer,

Ive been investigating this further today and it seems that the Sync Template v3 (Apps) Flow has a switch statement which looks at whether an app has been editted and if so it adds it to the Editted Array. It looks like apps are never added to the array because the switch statement never goes true.

So my question is, when an app is shared with the tenant should the variable "sharedGroupsCount" be 1?
I ask because I have an app which is shared with just the tenant and yet both sharedGroupsCount and sharedUsersCount remain 0 therefore in the Flow this app is never being added to the Editted array as described above.

Thanks in advance!

**Comment by JeneferM-MSFT** [comment]
That is correct. Sharing an app does not dirty it. We have a flow called **_CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)_**, also in Core, which does the periodic clean up to ensure the inventory has this information as a result. Is that on and running?

**Comment by JeneferM-MSFT** [comment]
Closing out as no further action for toolkit. Thanks for using CoE
