### ISSUE TITLE
Deleted Environments in CoE and Flow Failing

### ISSUE THREAD

**Issue by Deesingh1992** [microsoft/coe-starter-kit#8531]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Under the Admin View: I have a list of environments marked as deleted for some reason. 
We need assistance with why all these environments are marked as deleted. 

### Expected Behavior

Should have all these environments under the "Active environment" drop-down.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

admintaskanalysis_core_1.3.20230724.1_managed

### What app or flow are you having the issue with?

1.3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Admin View> Enviornments> Deleted Environments

AB#3661

**Comment by Jenefer-Monroe** [comment]
To start, please do let me know the version of Core you have. 
You can do this by sharing a screenshot like this so we can see what solutions you have installed in this environment.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Deesingh1992** [comment]
Hi Jenefer, 
The version is 4.31. 
Screenshot: 
![2024-06-25 09_19_57-Power Apps _ Solutions and 1 more page - Work - Microsoft​ Edge](https://github.com/microsoft/coe-starter-kit/assets/173658746/f63ac417-65ae-4d7c-bcc1-48162d65765c)

**Comment by Deesingh1992** [comment]
Hi Jenefer, 
Could you please guide me on where I can find out if the Power Platform Admin Role is permanently and directly assigned or not?

**Comment by Jenefer-Monroe** [comment]
Sure thing.
https://portal.azure.com/ > Users > User identity running the kit > Assigned roles

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/799ee768-d9c8-4ddf-a5de-eb5253194134)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ef0a48ce-727b-4c65-b79d-3b10185dea51)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/931e32fb-b332-4ef1-8950-206b0407424a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
