### ISSUE TITLE
[CoE Starter Kit - BUG] different data from dataflows retrieving inventory from Data Export

### ISSUE THREAD

**Issue by MaryamA123** [microsoft/coe-starter-kit#8532]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have been using the inventory cloud flows so far to retrieve inventory in the PRD environment. In the CI environment with the same version of the starter kit installed, we wanted to test using dataflows to retrieve inventory from Data Export. When comparing the data, it was different to the one retrieved from the cloud flows. Now we're not sure which method is providing the correct data. 
We followed the instructions to set up both from here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#set-up-dataflows-to-retrieve-your-inventory-from-data-export  

### Expected Behavior

We expected to see the same data from the starter kit in both environments

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Jan 2024

### What app or flow are you having the issue with?

Set up dataflows to retrieve your inventory from Data Export

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. In the CI environment 
2. Set up dataflows to retrieve your inventory from Data Export
3. set up the power bi dashboard 
4. found data was different to that produced from cloud flow method

AB#3662

**Comment by Jenefer-Monroe** [comment]
Hello, at this time we do not recommend new people onboard to the Data Export methodology as we are receiving a large schema change from the product team responsible for this work. We expect to have something for people to review early fall.

**Comment by MaryamA123** [comment]
Okay, thanks for your response. Is there an easy way to know when it will be ready, or do I just have to keep looking back in the fall?

**Comment by Jenefer-Monroe** [comment]
The best way to stay in touch with us is to come to the office hours. 
[CoE Starter Kit Office Hours](https://www.linkedin.com/events/powerplatformcenterofexcellence7150932453543563266#:~:text=Join%20the%20CoE%20Starter%20Kit,and%208%3A00AM%20Pacific%20time.)

Or you can follow Grant's linked in, he's charge with publishing updates to the kit there: https://www.linkedin.com/in/grantarchibald/?trk=_hosting-company

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
