### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Variable (admin_DeleteFromCoE) Purpose?

### ISSUE THREAD

**Issue by inquisitive-identity** [microsoft/coe-starter-kit#8534]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team,
Hope you're doing well!

I just have a simple question regarding one environment variable - _admin_DeleteFromCoE_ - because I was wondering what that variable does exactly?

My understanding was that when something gets removed from the tenant, its record (for instance a Canvas app) also gets removed from the Canvas Apps table in CoE Dataverse, but I am starting to think that it does not mean that, so I was wondering if you could shed some light on this. 

Thank you very much in advance! :)

Best regards,
Stefan 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3665

**Comment by Jenefer-Monroe** [comment]
Hello. You are correct, that is what it means. 
A few months ago we did make a change such that even for envts with this env set to true, we wait for a few weeks before doing that delete. This is to allow for the metadata about the object (ex if you've excused it from some process) to be persisted in the event you restore the object through the product. 

Restore scenario now supported:
- flow X is in inventory
- flow X gets excused from inactivity processes
- flow X gets deleted from the tenant
- flow X gets marked as deleted in inventory
- flow X gets restored in tenant
- flow X gets unmarked as deleted, still has its excused from inactivity processes flag set

If no restore
- flow X is in inventory
- flow X gets excused from inactivity processes
- flow X gets deleted from the tenant
- flow X gets marked as deleted in inventory
- two months pass, flow is no longer available for restore in tenant
- in the flow below, if you have the env var set to true, flow gets deleted from inventory

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3f61a941-816f-4621-9a98-1ff237070d6f)

**Comment by inquisitive-identity** [comment]
Hi Jen,

Ahhh right, that makes perfect sense, and is brilliant actually... 
Thank you very much for the clarification, I really appreciate that! :) 

Best regards,
Stefan

**Comment by Jenefer-Monroe** [comment]
Thank you :)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
