### ISSUE TITLE
[CoE Starter Kit - BUG] Flows empty on new installation of CoE

### ISSUE THREAD

**Issue by AOkeACCA** [microsoft/coe-starter-kit#8535]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After installing the CoE none of the Flow related tables or charts have any information. the flows appear to run without any failure.

<img width="1061" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/173702015/afdfd4e2-3845-433a-a034-e7199e7b2bf4">

### Expected Behavior

The dashboard should display flow counts

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32

### What app or flow are you having the issue with?

Power Platform Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1 browse to the Power platform Coe dashboard 
2 click on flows

AB#3666

**Comment by Jenefer-Monroe** [comment]
Hello. We had to hot fix the June release to address this. Basically the product team shipped the unpublished flows feature and we had a bug in our prep work for it: https://github.com/microsoft/coe-starter-kit/issues/8426

**Comment by Jenefer-Monroe** [comment]
The current download contains version 4.23.2

**Comment by AOkeACCA** [comment]
thanks for your response ,How do i apply the hotfix?

**Comment by Jenefer-Monroe** [comment]
you just install again as you would any normal upgrade.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
