### ISSUE TITLE
[CoE Starter Kit - QUESTION] Broken Email Header, Footer and Logo

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#8536]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!
Today, 24.06.24, I have noticed that suddenly all the emails in Outlook that have email headers, footers and logos now have them in a broken way, meaning, they do not look as they looked previously - in the beautiful, correct way. Now the Logo is really big, and the email header and footer are broken as well, like the structure is broken.
On Wednesday - Friday (19-21.06) I did the CoE upgrade by using the April releases. Could it be that something happened because of the upgrade? As I think we didn't have something like this previously but this time it happened almost after the coe upgrade.
What is strange, I would understand if all the emails that were sent/received after the CoE upgrade would look broken. But I see that If i click now to the older emails, they also are shown now as broken. So, it somehow also seems to be related to Outlook, could it be like that? Am confused about that.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 2024

### What method are you using to get inventory and telemetry?

None

AB#3667

**Comment by Jenefer-Monroe** [comment]
Nothing has changed in this area so it does appear that outlook may have changed the way it reads the HTML. 
Here is what its looking like for me today. Is this what you are seeing? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e64de95d-1b69-48d7-8386-04b49c85fa4b)

**Comment by JanetK12** [comment]
> Nothing has changed in this area so it does appear that outlook may have changed the way it reads the HTML. Here is what its looking like for me today. Is this what you are seeing? ![image](https://private-user-images.githubusercontent.com/89584709/342493705-e64de95d-1b69-48d7-8386-04b49c85fa4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNjc1NDQsIm5iZiI6MTcxOTI2NzI0NCwicGF0aCI6Ii84OTU4NDcwOS8zNDI0OTM3MDUtZTY0ZGU5NWQtMWI2OS00OGQ3LTgzODYtMDRiNDljODVmYTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDIyMTQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YTg0OGU3NzhjMzFhMTgyNzg3YTM3MTgzNzk0ZDc5NmNkZTkyN2ZlN2NiZWM3NmQ2MzVkMzlhN2RjNTAzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ISLhzFtOED5HggeptP_I8GbnHrx_-BuvnaKSa3Uk_s)

Thank you for your answer @Jenefer-Monroe, as always! 🥇 

Of course I am not sure, just thoughts, but could it be then that maybe some flow that needs to be turn on is turn off? I mean, in case there is a flow that checks these as well?
Because I am not sure why it suddenly happened that way. I just remember that some time ago I raised ticket #6411 where you explained about the "coe admin command center" app, and there we modified the env. variable. And after that everything worked correctly for almost a year. But not sure what could have happened now.

For me right now it looks like approximately like this and even bigger.
![image](https://github.com/microsoft/coe-starter-kit/assets/113427788/4d694f04-49e5-42df-a3bb-0b5d021cc1e8)
 
 but in case this is just an outlook in general, then is there a way to improve that? Just then I wonder whether everyone else that use Power Platform will receive emails that way, if the outlook changed the way of reading httml? If yes, then there will be a new release with the fix to cooperate with the outlook?

**Comment by Jenefer-Monroe** [comment]
The only issue then is this sizing correct? Everything else is ok? 
If so you could edit the email Header Style env variable in your envt to remove the logo 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/59053ae5-e812-4e98-abfd-0f91f54d79c4)

I'm not a CSS / HTML type person so I don't know what string there woudl do that without playing around and testing myself. Please let me know if you are able to do that and what you end up getting working.

**Comment by JanetK12** [comment]
> The only issue then is this sizing correct? Everything else is ok? If so you could edit the email Header Style env variable in your envt to remove the logo ![image](https://private-user-images.githubusercontent.com/89584709/342711922-59053ae5-e812-4e98-abfd-0f91f54d79c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTYyNzcsIm5iZiI6MTcxOTMxNTk3NywicGF0aCI6Ii84OTU4NDcwOS8zNDI3MTE5MjItNTkwNTNhZTUtZTgxMi00ZTk4LWFiZmQtMGY5MWY1NGQ3OWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDExNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMmE4YmJkMGVkMTEyZTM3OThkZWNiMjkxZjFkYjJlMmIwNWQ4M2Q5ZjQzNTgzNTlmZDQ1ZWZlN2NiNjE5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ad1DQj4noL5vbn0hZcK8GUCI3SLLbRytgHfkEWEORZk)
> 
> I'm not a CSS / HTML type person so I don't know what string there woudl do that without playing around and testing myself. Please let me know if you are able to do that and what you end up getting working.

Hello @Jenefer-Monroe !
Thank you for your answer!
I will test the variables from the app to see the difference, yes.
However, it is not only Logo, but also header and footer. I just cannot show the screenshot of the brand Logo, header, etc., unfortunately. 
But still, interesting why could this happen so suddenly? we didn't change anything, and this is what I noticed yesterday in the outlook.

**Comment by JanetK12** [comment]
> As you suggest, it appears that the Outlook Web App may have shipped something that changed the way it reads the CSS. Unfortunately I do not repro anything in OWA or this Desktop clients so I'm not sure what you are seeing.
> 
> Have you customized the env vars? If so you may want to re make your customizations. ![image](https://private-user-images.githubusercontent.com/89584709/342727586-7af98ec6-8501-4c1f-9db2-4be44619f55a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODY4ODMsIm5iZiI6MTcxOTM4NjU4MywicGF0aCI6Ii84OTU4NDcwOS8zNDI3Mjc1ODYtN2FmOThlYzYtODUwMS00YzFmLTlkYjItNGJlNDQ2MTlmNTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MjMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYmJhYTM1ZjA4ZGZlYzZjNjgzN2E3YzA0NTAyMjE2OWQzZDM3YmYzYjY2NGY3MTIzMmVkOTI3ZjA1NDQzZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eog5B-bmcSF2RJGOe_-dCnHiKX36atac-B6oD0AM24U)

Hi @Jenefer-Monroe !
Thank you for your answer!
yes, some time ago, ~ 1 year ago, we did customize these variables to match the criteria that was required. So, then that means that we need to do adjustments now again, am I right? 
Just was thinking how to understand what exactly there is wrong with the code.. because as long time ago, when we decided to modify the env. variables, the thing was similar, that the Logo was big, etc. , and because of that we applied the modification to the variables. However, as the code still is the same, meaning, needs to be "correct", but somehow the outlook cannot read it anymore, then what exactly needs to be changed and how, not sure right now

**Comment by JanetK12** [comment]
@Jenefer-Monroe 
Also, strange, but when I open the CoE admin command center app, and these variables that I want to change, I cannot save the changes. I am clicking to the button "save" or button "revert", but nothing happens. They are clickable but as I said, nothing happens, no message as "successful", and when I refresh the app, also nothing changes. What could that mean? maybe then it is not the outlook as a problem but something else? The app or flows that need to be connected to the app? Because I thought if it is really the outlook, then more people need to have it, if not everyone, and then wouldn't more people reach out in GitHub about the "issue" of the broken logo, header, footer? because I was not able to find similar request. Just my thoughts as trying to understand why it suddenly happened and why the app doesn't "work" now.

**Comment by Jenefer-Monroe** [comment]
Regarding the buttons not working, there was a product change and the creator kit (who made that panel component) had to reship to fix. Please see below

### Buttons and Panels Broken
Hello, 

All dialogs and panels were broken in the kit due to a product change that broke the creator kit components that we use. 
This has been resolved with the latest version of the creator kit: https://aka.ms/creatorkitdownload
- Creator Kit Core 1.0.20240529.1

Then this new version of creator kit has been adopted and used to fix in the June 2024 release of the kit: https://aka.ms/coestarterkitdownload
- Core 4.32.2
- Gov 3.24
- Nurture 3.18 

You will need to upgrade to at least the builds above to see this fix across the kit.

**Comment by Jenefer-Monroe** [comment]
Regarding your case, others are not posting this and I do not repro myself. It could be that you are in an early release ring for the Office organization and so the rest of us will see this broken sometime soon. 

I would suggest doing the required upgrades suggested above, then see if you still repro. And if so test with an admin oriented mail (like sync flow errors) with the env vars we ship with. This will help us know if its something with your customized values or not.

**Comment by Jenefer-Monroe** [comment]
The Creator Kit is a separate download of separate components. The CoE Starter kit uses the Creator Kit. 

There was a product change that broke the Creator Kits dialog and panel components. So they had to ship a new release to address. 
Please download and install the latest creator kit to resolve that: https://aka.ms/creatorkitdownload

Once that is done you will also need to download and install the latest CoE Starter Kit as it had to be updated to use these new controls from Creator Kit: 
Please download and install the latest coe starter kit to resolve that: https://aka.ms/coestarterkitdownload

**Comment by Jenefer-Monroe** [comment]
The bug that hit the creator kit is surely not the same bug that is impacting your email configuration. 
That bug had to do with the way canvas components treat return types to the canvas applications.

So please do perform the upgrades. And then once you complete that, see if your bug still exists.
If so remove your customizations and see if the env vars we ship with also repro for you.

**Comment by JanetK12** [comment]
> The Creator Kit is a separate download of separate components. The CoE Starter kit uses the Creator Kit.
> 
> There was a product change that broke the Creator Kits dialog and panel components. So they had to ship a new release to address. Please download and install the latest creator kit to resolve that: https://aka.ms/creatorkitdownload
> 
> Once that is done you will also need to download and install the latest CoE Starter Kit as it had to be updated to use these new controls from Creator Kit: Please download and install the latest coe starter kit to resolve that: https://aka.ms/coestarterkitdownload

Hi again and thank you for your answer!
So, this kit can just be installed in the environment, am I right? no prerequisites or something else? Just straightaway, right?
And the latest CoE Starter Kit is a June release? or we have now even the newest version that goes after the June release?

**Comment by JanetK12** [comment]
> The bug that hit the creator kit is surely not the same bug that is impacting your email configuration. That bug had to do with the way canvas components treat return types to the canvas applications.
> 
> So please do perform the upgrades. And then once you complete that, see if your bug still exists. If so remove your customizations and see if the env vars we ship with also repro for you.

Thank you!
Am I correctly understanding that you are saying that for now I do not need to change the env. variables for the emails, but better first of all do the upgrade because it could be that it can help even the env. variables? Or you think the upgrade still cannot help the env. variables  (logo, header, footer), but will help only for the buttons to be clickable? 
I apologize if I have a lot of questions.

**Comment by Jenefer-Monroe** [comment]
The upgrade will allow you to use the apps to adjust the env vars. So you may as well get that done. It will not fix your bug no. 

Here is the setup instruction page for the Creator Kit: https://learn.microsoft.com/power-platform/guidance/creator-kit/setup
It is simple yes you should just be able to upgrade it.

**Comment by JanetK12** [comment]
> The upgrade will allow you to use the apps to adjust the env vars. So you may as well get that done. It will not fix your bug no.
> 
> Here is the setup instruction page for the Creator Kit: https://learn.microsoft.com/power-platform/guidance/creator-kit/setup It is simple yes you should just be able to upgrade it.

I see, thank you for your answer @Jenefer-Monroe !

By the way, I noticed something interesting while checking the outlook mailboxes from different accounts. So, when in the flow the sender of the emails is the person "A", then the emails look beautiful, not broken, but only from the view of mailboxes "A". Like, meaning, when I am checking what was sent from the "A" account as he was also the sender in the flows, everything looks great. However, the receiver, let's say person "B" , see these emails broken as I explained previously (broken logo, fotter, etc). 

I hope you were able to understand my explanations of the example. could I ask, What could that mean?

**Comment by Jenefer-Monroe** [comment]
You've been correct this whole time. It appears that Outlook is displaying your CSS in a new away that it used to in some folders. 
Since I do not repro I'm afraid you'll need to test to see if you repro without your customized env vars, with the ones we've shipped.
My guess is that there is some change you will need to make to your customized CSS to deal with this change in outlook behavior.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
