### ISSUE TITLE
[CoE Starter Kit - QUESTION] The flow maker assigned does not have a mailbox.  Resulting in Inactivity Notification failure message.

### ISSUE THREAD

**Issue by dchrist27** [microsoft/coe-starter-kit#8537]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

A couple of the schools within the university purchased Anthology Reach (a CRM solution built on Power Platform).    Turns out a service account is set as the owner of the flows but this account doesn't have a mailbox which is (what I believe) why I receive Inactivity Notification failure messages.
![image](https://github.com/microsoft/coe-starter-kit/assets/52799471/d441c3d3-b17b-42b6-b7ed-8761a43b122c)

![image](https://github.com/microsoft/coe-starter-kit/assets/52799471/bd202f98-9428-4664-a3ba-454322d119cc)

Is there a way to override the maker on a flow (by flow) basis and set a backup maker so that the approval flow runs and the approvals are sent to the backup maker?

Dave

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.20

### What app or flow are you having the issue with?

 Admin | Inactivity notifications v2 (Start Approval for Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3668

**Comment by dchrist27** [comment]
Wanting to call out the note I see on the flow overview page in Manage Permissions app.    I think this is OK since I'm looking to redirect the approvals for inactivity flow to the 'new' owner.  Please advise.

![image](https://github.com/microsoft/coe-starter-kit/assets/52799471/a1914f94-dd39-46b0-92e1-35cdebfcc5bb)

**Comment by Jenefer-Monroe** [comment]
Correct. Non solution aware flows do not allow you do change ownership in the product. 
Here is how that looks in the product itself: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66e3089c-985f-4778-b5cc-3ea3186c8ccd)

The kit allows you to assign to a "Derived Owner" meaning that we will locally treat whomever you chose as the owner for thigns like inactivity processing.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
