### ISSUE TITLE
[CoE Starter Kit - Connectors]  Legacy / Deprecated

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#8538]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Olá pessoal!!!!

I just saw a third-party tool classifying PowerPlatform connectors as "deprecated" and in need of review.

Now curiosity came, does this classification really exist by PowerPlatform? I know we have legacy connectors, and we can visualize this through the Started Kit (Dataverse Legacy), is there this vision in PowerPlatform governance of deprecated connectors?

thank you for your support

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3669

**Comment by Jenefer-Monroe** [comment]
To my knowledge there is not a flag on connectors indicating they are deprecated, so we would not be able to automatically surface this to you.

We did add a tile in the governance PBI file for the list flows v1 action in particular though, as a known connector being deprecated. You could do something similar for whatever set of connectors you have found that need exploration. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/251af96e-f3a8-4f37-bb9b-02f454e511a5)


Please let me know if I've misunderstood the question.

**Comment by ClaudioRWS** [comment]
I believe that's it.

Because the market is offering third-party tools for governance, with the same proposal as the Started Kit, but we know that our tool is growing exponentially, and with a lot of collaboration.

When the third-party tool proposed reporting a number of obsolete connectors, I was confused, as it is difficult, or rare, for someone to comment on which connectors in the environment are "deprecated".

So I wanted to understand if there is a criterion for this, and if we can bring this information to the Started Kit. It is a way of informing product or environment owners that it is time to recycle their automations or apps.


And inform anyone watching a third-party demonstration ( Zé ruela*** )that the term "deprecated" is not recognized, or does not exist for PowerPlatform.


***_And inform anyone watching a third-party demonstration that the term "deprecated" is not recognized, or does not exist for PowerPlatform_

**Comment by Jenefer-Monroe** [comment]
Correct, to my knowledge it does not. Connectors and actions are deprecated but I dont think there is a way to find that out programmatically. Please let me know if you find something that says otherwise!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
