### ISSUE TITLE
[CoE Starter Kit - QUESTION] The flows are not showing in the dashboard

### ISSUE THREAD

**Issue by Lhamo65** [microsoft/coe-starter-kit#8541]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I've installed the CoE starter kit but it only shows the number of Apps and not the number of Flows. 

<img width="666" alt="Power Platform Dashboard" src="https://github.com/microsoft/coe-starter-kit/assets/73664888/98551172-5aed-42ac-b5c4-ebccb131f3df">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_4.32_managed

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3676

**Comment by Jenefer-Monroe** [comment]
Hello. We had to reship the June release to address this. Basically the product team shipped the unpublished flows feature and we had a bug in our prep work for it: https://github.com/microsoft/coe-starter-kit/issues/8426

Please upgrade again with the latest download and rerun the Setup Wizard

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Lhamo65** [comment]
Yes, thank you Jenefer! The latest version seems to fix the issue.
