### ISSUE TITLE
[CoE Starter Kit - QUESTION] Sync Flow Error - Admin Sync | Sync Template v4 (Security Roles)

### ISSUE THREAD

**Issue by DKeyesOCC** [microsoft/coe-starter-kit#8542]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

Apologies if the below is a simple fix, I'm new to Power Platform. We are receiving a Sync Flow error on Admin - Sync Template v4 (Security Roles). 

So far I think I have determined that the issue is due to a missing user in the SystemUsers table. 

Screenshot 1 - Shows the error
Screenshot 2 - Shows table with user missing. 

![Screenshot 1 - Error](https://github.com/microsoft/coe-starter-kit/assets/160625015/d0c54022-f449-4e53-9995-6bdca9bc02e2)
![Screenshot 2 - User List](https://github.com/microsoft/coe-starter-kit/assets/160625015/31c2beeb-2fd6-4952-acd4-ea1558f8c7b5)

My question is what is the best approach to fix this issue? Would it be to create this user or assign another user?

Thanks in advance,

Daniel

### What solution are you experiencing the issue with?

None

### What solution version are you using?

May 2024

### What app or flow are you having the issue with?

Admin - Sync Template v4 (Security Roles)

### What method are you using to get inventory and telemetry?

None

AB#3677

**Comment by Jenefer-Monroe** [comment]
Hello and welcome to Power Platform! 

This is a list-rows action and so it simply not being found would not cause it to fail. If its simply not found it would return no records and the next condition in the flow behaves differently based on that. 

What is the error message you are given? This will be in the output of the call

**Comment by DKeyesOCC** [comment]
Hi Jenefer, 

Thanks so much for the quick reply.

Please see attached screenshot of the error message on the output. 

![Screenshot 3 - Error Output](https://github.com/microsoft/coe-starter-kit/assets/160625015/18835a99-82df-4dbe-8b6d-42dd16ad32d2)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
