### ISSUE TITLE
[CoE Starter Kit - BUG] Clean up - Sync Template v4 (check deleted)

### ISSUE THREAD

**Issue by Isaiah-1234** [microsoft/coe-starter-kit#8543]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,

We have installed the latest version of COE kit and ran the flows which was mentioned in the MS article, However we are encountering issue
Issue: As a process, we a customized developer app( users needs to fill the data , when reminder auto mail will be send to users every day), when Users are deleting the apps/flows manually this reminder auto mail shouldn't trigger to them, but now the mail is going to all the users, even if their app/flow is deleted.

What we found:
As per the previous kit, if the user deletes an app/flow, it will get deleted from COE table as well and reminder will not go to them, but after installing new version, app/flow are not getting deleted from coe table and we see there is an error in cleanup- sync template v4 (check deleted)
 

<img width="610" alt="v4-error1" src="https://github.com/microsoft/coe-starter-kit/assets/146922216/f00cd57f-2c65-40df-8e8e-71389ba5d266">
<img width="571" alt="v4-error" src="https://github.com/microsoft/coe-starter-kit/assets/146922216/38936a41-a4ee-4a2c-ac9c-344b5c626624">

### Expected Behavior

As per the previous kit, if the user deletes an app/flow, it will get deleted from COE table as well and reminder will not go to them, 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Clean up - Sync Template v4 (check deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3679

**Comment by Isaiah-1234** [comment]
Hi Team,

any updates?

**Comment by Jenefer-Monroe** [comment]
Hello, Sorry I'm not sure about your custom processes. I presume the question is about why the flow is failing. 
Can you please dive down into the failing scope and find where it terminates with a failure? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/32ffa060-8d4a-4e76-abc8-0722e4db2b4f)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Isaiah-1234** [comment]
Please close it, its working fine now :)
I just resubmitted the flow as per your comment from another issue page and it worked for me.
