### ISSUE TITLE
[CoE Starter Kit - QUESTION] PBI Report - App Shared Groups

### ISSUE THREAD

**Issue by silvafr1** [microsoft/coe-starter-kit#8544]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

From the Power Platform Admin View App we can get the detail "App Shared with User or Group", however is there a way to get a "view" or a "PBI Report" with all Apps and the "Shared with" details?

Our main goal is to be able from the "Shared with a Security group" information, to verify which apps are using that specific Security group! And since the information "Shared with users/groups" is being collected, maybe there is a way to get that report!

Thank you very much!

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April version

### What method are you using to get inventory and telemetry?

None

AB#3680

**Comment by Jenefer-Monroe** [comment]
Hello. We have some big competing priorities over the next several months and so will not be investing in other new features than those for the near term. 
However I believe you have what you need for this in the Power Platform Admin View app today. 
Browse to **_Power Platform Users_** table in the **_Power Platform Admin View_** app, and find your user or group of interest, click on its name to open the record
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0e94531c-f2b9-4246-b6f5-82159ea11421)

Expand Related > Power Platform User Roles
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/95a60e08-93d2-4c82-a00b-4328368df2bc)

You will see the list of apps the user or group is shared with. 
Please let me know what you think.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
