### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Upgrade best practice

### ISSUE THREAD

**Issue by tiagosazevedo** [microsoft/coe-starter-kit#8545]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I want to upgrade the CoE (Core Components) in my production environment from version 4.9 to next version 4.11. I've tried to clone my production CoE environment to a new test environment and import the new CoE Solution (version 4.11), but I've got the following error:

Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :Code: BadRequest Content: DataflowId already exists under a different environment

It seems that the clone has some reference to the other environment. 
- Is there a better way to test this upgrade process?
- Is there a way to clone a CoE environment to another test environment avoiding the reference to the source object?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.9

### What app or flow are you having the issue with?

All

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3681

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately dataflows do not work in a cloned envt. The product team is aware of this limitation but a fix has not yet been made. 

Most people just have a test envt that they keep around for testing upgrade path. Its not perfect but its the best the platform has for now to test upgrades like this. 

Hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
