### ISSUE TITLE
[CoE Starter Kit - QUESTION] Deleting Solution Aware Flows in CoE

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#8549]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team, 

We are aware that it is best practice to use Solutions when creating our apps and flows. However, this inactivity flows do not delete out the flows that are in solutions. Is there any workaround? Or, if it's a solution aware flows, could we, as a CoE admin, not delete the flow?
 
<img width="821" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/100535041/90301d0e-6bec-47bc-bc5d-63805ad91e09">

<img width="824" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/100535041/6d2f5648-6f85-4aed-9798-4d9eb17741a2">

Thanks

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

June 2024

### What app or flow are you having the issue with?

Inactivity Flow

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3685

**Comment by Jenefer-Monroe** [comment]
You actually can delete these now, the helper flow was updated with this already but we did not update this flow. 
I can fix that up in the next couple releases.

**Comment by iamjina** [comment]
Thanks Jenefer. When you mean by we can delete these now, are you referring to Inactivity Flow? Or which flow would it be? 

Also, with this change be coming up in August?

**Comment by Jenefer-Monroe** [comment]
What I mean is that in the past, the product failed when you tried to delete a flow in a solution. 
They changed that behavior and now you can delete them. The helper flow that is called no longer checks this and allows you to delete these, however the inactivity flow checks and prevents. 

I cannot promise this change will make it to August as we have some big competing priorities, but I have set it to try for that.

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by iamjina** [comment]
Thank you! We'll test it out!

**Comment by iamjina** [comment]
Hi Jenefer, 

It is working as expected. Thanks for working on this!

**Comment by Jenefer-Monroe** [comment]
Hurrah!!! Thanks for testing for me!

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
