### ISSUE TITLE
Prevent all Maker Communications from going to Makers in TEST environment

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#8550]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

If the Production Environment variable is set to 'no' will this send ALL communications, whether email or Teams to the admin listed in the admin variable?

We are testing modifications to all the governance flow (orphan, inactive, compliance center, welcome emails etc) and we don't want ANYTHING to go to the actual makers.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3686

**Comment by Jenefer-Monroe** [comment]
That is what we have implemented yes.

**Comment by PPCan** [comment]
Ok. So even the team messages will go to the admin?

**Comment by Jenefer-Monroe** [comment]
Correct, you can do look through the flows if you'd like to validate before running but we have not heard about mistakes or missing cases here in years. 

It surfaces in different ways in the flows, here is an example: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ab3cd44a-66d7-4b00-956c-e68442f46733)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
