### ISSUE TITLE
[CoE Starter Kit - QUESTION] Did our upgrade work ?

### ISSUE THREAD

**Issue by picotanthony** [microsoft/coe-starter-kit#8557]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello everyone,

We just did an upgrade from 4.16 to 4.32.2.  The status column says "success" but we are wondering why this time we don't see the operation "Upgrade (Uninstall)" ?

- Import is there but we do not see the Upgrade (Uninstall) line:
![2024-06-26_090350](https://github.com/microsoft/coe-starter-kit/assets/60710994/d59e5da8-4ad2-46a3-8554-5a77e85e7f62)

- We are not sure if the "Power Plateform admn view" app has been updated as it says "Last modified - 3month ago":
![2024-06-26_091244](https://github.com/microsoft/coe-starter-kit/assets/60710994/d50761f2-df9c-45c3-93e4-bc53101c6deb)

- Last upgrade we had "import" + "upgrade (Uninstall)":
![2024-06-26_090331](https://github.com/microsoft/coe-starter-kit/assets/60710994/f9335a48-8df4-4b10-9379-b3ad1b62aa19)

Thank you for your help!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2024 - 4.32.2

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

AB#3693

**Comment by Jenefer-Monroe** [comment]
Hello. I have seen the "last update" stamp not updating sometimes recently as well. I"m not sure why this happens, unfortunately its outside of my ability to debug or control. 

There is sometimes a delay in the uninstall occurring. Has it appeared now that some time has passed? 
Do you have two instances of Core showing? One with an _upgrade postfix to the name?

**Comment by picotanthony** [comment]
We have only one instance of the Core showing! I just checked and I still don't see any "uninstall" action in the history. 

Is there a way to make sure the "Power Platform Admin View" app is running the correct version?

**Comment by Jenefer-Monroe** [comment]
I just looked around and also dont see the uninstall anymore. I think they may have just changed the UX to hide these. 
So you should be good

**Comment by picotanthony** [comment]
Thank you for the verification!

**Comment by Jenefer-Monroe** [comment]
You bet! I'll go ahead and close this then but please feel free to reach out in the future with other questions.
