### ISSUE TITLE
[CoE Starter Kit - Azure Key Vault Configuration and security concerns

### ISSUE THREAD

**Issue by whorn76** [microsoft/coe-starter-kit#8558]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

This could be an issue with my understanding of how Key Vault and the COE work together, so please correct me if I'm wrong.  However, I have a customer that has some reservations about adding the Dataverse user/service as permissions to read Key Vaults. 

Doing permissions this way would seem to indicate that anytime you want Dataverse to have access to a Key Vault its going to have access to any vault that it was already setup for.  Thus, you couldn't do anything environment specific as every environment would have access to each vault.

For the Audit Log sync setup, would it be better if they Audit Flow that gets the secret used the "Get Secret" action of the Azure Key Vault connector?  That way it would require only the Service Account to have access to the secret in the vault.

Please let us know if we are totally misunderstanding the concept.  Thanks!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2024

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3694

**Comment by Jenefer-Monroe** [comment]
I'm afraid this is really a question for the product organization. We are just using this feature. 
Here is the starter documentation for it, hope that is helpful. [Use environment variables for Azure Key Vault secrets](https://learn.microsoft.com/power-apps/maker/data-platform/environmentvariables-azure-key-vault-secrets)

**Comment by whorn76** [comment]
I guess I understand the limitation and its limitation from the product side.  I'm wonder if it might make more sense for the COE to reach out to the Key vault in the flow and grab the secret on the fly rather than storing it in the Dataverse and requiring the dataverse to have access to the key vault.  To me that would be more secure because then you could secure the vault down to a single user/service principle per vault.  The customer had that concern and it would eliminate that concern regarding the COE, but it would still exist for any other vault configuration for Dataverse that would have to be addressed by the PG.   Thanks for listening!

**Comment by Jenefer-Monroe** [comment]
Happy to listen. We won't be shifting to this for the kit as we want to use the out of the box features as they exist when possible. I do suggest you get this feedback to the product team though in whatever mechanisms you have available. And perhaps ask around in the power users community if others have heard the same concern https://powerusers.microsoft.com

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
