### ISSUE TITLE
[CoE Starter Kit - BUG] Innovation Backlog - divide by zero bug

### ISSUE THREAD

**Issue by lmundia** [microsoft/coe-starter-kit#8559]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Issues with apps loading, we see these errors consistently with our customers. 
![solution_error](https://github.com/microsoft/coe-starter-kit/assets/16409270/0c97bcd2-9dc3-49e5-ac1e-b918cb9342fb)

### Expected Behavior

No errors 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June release 

### What app or flow are you having the issue with?

Backlog

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Run the Backlog application
2. On load there are errors as displayed in the screenshot above.

AB#3695

**Comment by Jenefer-Monroe** [comment]
Hello, this app is being remade and so we are no longer funding this old version of it.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
