### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Admin | Audit Logs | Sync Audit Logs (V2)

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#8560]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I can only get the last startup date and time of PowerApps, but is it possible to get other audit logs?

If I want to modify the flow, where should I do it?

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

2024 - 04

### What app or flow are you having the issue with?

none

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3696

**Comment by Jenefer-Monroe** [comment]
Hello. You are correct we only gather the launches from the audit logs. 

If you are going to explore developing your own solution, I suggest you switch to this new API. We will be offering it in the kit soon as well, but you can download the solution now for testing. 

This new API allows for filtering on the backend so its much more performant from an API pov.
Here is the new solution: https://github.com/petepuu/coekit-auditlogsync-v3/releases
Here is a write up on how to set it up: https://github.com/petepuu/coekit-auditlogsync-v3

Here is our generalized article about [How to extend and customize CoE Starter Kit components](https://learn.microsoft.com/power-platform/guidance/coe/modify-components)

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
We are considering modifying our own flow for Power BI.
What modifications should be made to enable the data acquisition?

**Comment by Jenefer-Monroe** [comment]
Sorry we are a very small team, with only me staffing GitHub for all 12K installs of the CoE Starter Kit, so we are just not staffed to assist with customizations.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
