### ISSUE TITLE
[CoE Starter Kit - Env, DLP sync

### ISSUE THREAD

**Issue by JO20232425** [microsoft/coe-starter-kit#8562]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After installation on COE -April 2024 version, new enviornments, DLP policies not reflecting on dashboard

### Expected Behavior

It should sync.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Core component

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Create an Env or Data policy. Check Dashboard after sync

AB#3699

**Comment by Jenefer-Monroe** [comment]
Can you please share screenshots?

**Comment by Jenefer-Monroe** [comment]
Sorry those screenshots did not come through, here is what I see:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/88c1fb6e-eb85-47e7-9c7b-9c7a6a19164c)

**Comment by JO20232425** [comment]
Could we have a call please to share my concerns


Regards,

Jayshree



________________________________

**Comment by JO20232425** [comment]
The images aren't getting shared. Could we have a screenshare call.


Regards,

Jayshree



________________________________

**Comment by Jenefer-Monroe** [comment]
Sorry we are a very small team, with only me managing the GitHub issues from all 12K installs of the kit. So we just are not staffed to have calls with our users. 
Which dashboard are you referencing?

**Comment by JO20232425** [comment]
Hi so sorry to hear this. Please find attached dashboard.

Also due to installation of COE ,
1.Immediatly Dataverse for Teams environments got deleted , could you guide which flows are triggering that action.
2. If I restore these environments, the flows shows disabled, could you suggest resolution to this.

Regards,
Jayshree



Regards,

Jayshree



________________________________

**Comment by Jenefer-Monroe** [comment]
Hello. Attachments do not come through if you respond in email. You need to be logged in to GitHub to share them. 

We need to keep these issues to a single issue or we will not be able to track them. Please keep in mind that I work with ~12K users and so issues here that convolute across several different issues for you become very difficult to track. So plesae do post new issues for these. 

I believe there are several people at your company that have successfully setup the kit so you may want to reach out internally to get assistance.

**Comment by Jenefer-Monroe** [comment]
Regarding the issue tracked here: new enviornments, DLP policies not reflecting on dashboard
I need to know which dashboard you are referencing, as I do not know of dashboards that track both DLP and environments, so perhapsI am just not understanding you correctly. 

If new environments are not showing it could be your permissions.
Does the identity running the flow have the Power Platform Admin Role permanently and directly assigned? 
Note that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management), this won't be sufficient to run the CoE Starter Kit.
For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/67258ff2-7ef5-4207-945d-4f6f2337cfd0)

**Comment by JO20232425** [comment]
Hi Jennifer,

Hope you're well. I had already tried sending screenshots however couldn't get through. I would appreciate if we can have a quick call please



Regards,

Jayshree



________________________________

**Comment by Jenefer-Monroe** [comment]
Unfortunately we are just not staffed to have calls with our GitHub users. There are 12K of you all and only one of me :)

Please note that you cannot add screenshots if you respond in email which is what you appear to be doing. You have to log in to GitHub to share images. 
If that is not possible for you or does not work, perhaps another person in your organization can try to upload a screenshot. Or you can try to describe it with words.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
