### ISSUE TITLE
[CoE Starter Kit - Managed Environment details in environment table

### ISSUE THREAD

**Issue by Chandra1247** [microsoft/coe-starter-kit#8563]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

Do we have information whether environment is managed or not in the Environment table or any other table in the COE kit ?

Thanks!
Chandra

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What method are you using to get inventory and telemetry?

None

AB#3700

**Comment by Jenefer-Monroe** [comment]
Yes we do, we store this in the Governance Protection Level column for the environment. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5ab1ee32-ad5b-445d-99e0-58d443a72d3b)

**_Standard_** is the string the product uses for **_managed_**
And you can see a build in view of just the managed environments as well
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/75de2b33-86ed-41d9-bdff-e4e32b10fee9)

**Comment by Chandra1247** [comment]
Great. This is what i was looking.

Thank you!
