### ISSUE TITLE
[CoE Starter Kit - Feature]: Data Export Roadmap

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/coe-starter-kit#8564]
### Is your feature request related to a problem? Please describe.

The current Power BI reports for the CoE Starter Kit Core provide two modes of setup [Power Automate based and BYODL](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi)

Evaluate results of the private preview program for the Data Export to determine how it will offer improvements for cases where out of the box reporting where Power Platform tenants scale beyond the scope of only using the Power Automate based data collection for inventory and usage to leverage platform collected usage and telemetry.

### Describe the solution you'd like

Evaluate the changes in the following:
- Which Power Automate Cloud flows and the needs to "opt out" of data that is collected by Data Export?
- Data Pipeline - How will data collected by CoE Kit custom tables and platform collected inventory and usage be collected and merged?
- Data Analytics - How will merged data be presented to allow customizable analytics reporting?
- Business Process Triggers - How can business processed by triggered as a result of the collected inventory and usage data?
- Upgrade Path - How will earlier installations of the CoE Kit migrate and integrate with inventory and usage data that is available?

AB#3701

**Comment by Jenefer-Monroe** [comment]
Moving all V2 deliverables to Dec release

**Comment by Jenefer-Monroe** [comment]
This work is complete
