### ISSUE TITLE
[CoE Starter Kit - Feature]: Automated Install Roadmap

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/coe-starter-kit#8565]
### Is your feature request related to a problem? Please describe.

Today the [Set up inventory components](https://learn.microsoft.compower-platform/guidance/coe/setup-core-components) for CoE Kit requires the following:
- A created environment
- Imported instance of Creator Kit
- Created connections
- A [HTTP with Microsoft Entra ID](https://learn.microsoft.com/en-us/connectors/webcontents/) for https://graph.microsoft.com for commercial tenants
- Download and import of Core components from GitHub release

This process can:
- Take time to manually initially setup and then upgrade. 
- Be affected by regional as part of [General availability deployment](https://learn.microsoft.com/en-us/power-platform/admin/general-availability-deployment) or selected [regions](https://learn.microsoft.com/power-platform/admin/regions-overview)
- Be affected by updates to dependent components like Creator Kit from [App Source](https://appsource.microsoft.com/en-us/product/dynamics-365/microsoftpowercatarch.creatorkit1) or [GitHub Releases](https://github.com/microsoft/powercat-creator-kit/releases)
- Take time to verify and correlate data between CoE Starter Kit Analytics reporting data and data available in Power Platform [Tenant-level analytics](https://learn.microsoft.com/power-platform/admin/tenant-level-analytics)

### Describe the solution you'd like

Evaluate the following items and provide an incremental milestone strategy that allows a prioritized implementation considering the ability to:
- Make use of Terraform sample of [CoE Kit install](https://github.com/microsoft/power-platform-terraform-quickstarts/blob/mawasile/coe-kit-iac-quickstart/quickstarts/202-coe-starter-kit/main.tf)
- Automated download of current CoE Kit Release or a specific release
- Extract CoE Kit Core module
- Create an Environment
- Setup the required [DLP Policy](https://learn.microsoft.com/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies)
- [Create connections](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#create-connections) required for solution using an account
- Import Solution
- Login for System Account using Certificate based authentication
- Automate Install Wizard using [Power Apps Test Engine](https://github.com/microsoft/PowerApps-TestEngine)
- Verify that the install has completed as expected
- Automate steps to compare data in Power Platform Admin center and CoE Kit Reports
- Include setup installation and test files as part of the GitHub site

AB#3702

**Comment by Grant-Archibald-MS** [comment]
Summary of roadmap:
![image](https://github.com/user-attachments/assets/d591282c-0e83-4134-bd1b-3cfc40bcf2b0)

Notes:
- Provide terraform script automates steps 1-4. Example script [202-coe-starter-kit](https://github.com/microsoft/power-platform-terraform-quickstarts/tree/mawasile/coe-kit-iac-quickstart/quickstarts/202-coe-starter-kit)
- Automate the Creation of Connection and Connection References [Power Apps Portal Sample](https://github.com/microsoft/PowerApps-TestEngine/blob/grant-archibald-ms/power-apps-portal-348/samples/portal/testPlan.fx.yaml)
- Automate the Setup and Upgrade wizard [coe-kit-setup-wizard](https://github.com/microsoft/PowerApps-TestEngine/tree/grant-archibald-ms/provider-mda-342/samples/coe-kit-setup-wizard/testPlan.fx.yaml)
- Will start with low code Power Platform Pipeline example that allows deployment from development, to test environment execution of tests and deployment to production environment
- Consider how test environment created via terraform is added to Power Platform Pipeline for deployment
- Provide roadmap on how framework can be expanded to include test matrix execution globally. For example first release regions other global regions.
- Install and upgrade examples. For example install of release version and upgrade from old release and then upgrade to newer release

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by tocri** [comment]
Do you have a video about this functionnality ? How to implement it ? How to use ? etc...
