### ISSUE TITLE
[CoE Starter Kit - QUESTION] About table data deletion

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#8566]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

For PowerApps, PowerAutomate, and PowerAutomateDesktop, if an app is deleted, is the data in the table also deleted?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2024 - 04

### What app or flow are you having the issue with?

none

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3705

**Comment by Jenefer-Monroe** [comment]
Hello, please see below for an explanation of how we managed deleted objects in the CoE inventory

### Deleting objects from inventory
**How it works**
When objects are deleted from the tenant, they get marked deleted in the inventory when the following flow is run, along with its helpers: **_CLEANUP - Admin | Sync Template v4 (Check Deleted)_**
This is a long running flow and so it only runs once per week. 

Objects will stay in this state, marked as deleted from inventory, for ~2 months. This is to allow the record to be restored with its metadata in the event the object itself is restored in the tenant. 

At that point, once restore is no longer possible in the tenant, then the records themselves are deleted from the inventory tables as well. 

**Why keep them around for two months?** 
Here is the scenario we are supporting by keeping these around

- Flow X created in tenant
- Flow X added to the CoE inventory tables
- Flow X marked as exempt from inactivity processing in the CoE
- Flow X deleted from tenant
- Flow X marked as deleted in CoE inventory tables
- Flow X restored in tenant
- Flow X unmarked deleted in CoE inventory tables, exemption from inactivity processing remains in place.

**I need these records to stay in perpetuity**
We have an env var, _Also Delete from CoE_, which allows you to prevent the deletion from the inventory tables. Default behavior (yes) described above, but if you set it to no then these records will never be deleted by the kit

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/af05bf15-e937-4032-9eab-e4d290108147)


**I don't want these records sitting around at all**
If you want the deletion from inventory to occur immediately, or at some other cadence like 6 months, then you will need to create your own flow on the side to do this. You can use the mechanism used in _CLEANUP - Admin | Sync Template v4 (Check Deleted)_ as a template for how to do this.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/187ec89f-77d7-48d4-8fb3-ca6df9b704d5)

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
Is CLEANUP - Admin | Sync Template v4 (Check Deleted) the only flow that actually deletes the flagged flow?

**Comment by Jenefer-Monroe** [comment]
I believe so, yes. It is the only place that deletes objects from inventory.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
