### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Gather Tenant SRs

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#8567]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi, I have noticed Admin | Gather Tenant SRs is failing due to -
 RetrievePrivilegeForUser: The user with id *******e46ee*******-***** has not been assigned any roles. They need a role with the prvReadBusinessUnit privilege.
 The account has System Admin within the environment the CoE is installed in, is there something I have missed?

### Expected Behavior

This had no issues running prior to the upgrade

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32

### What app or flow are you having the issue with?

Admin | Gather Tenant SRs

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3707

**Comment by eeuo** [comment]
I have the same issue. The flow fails at the point "Get Parent BU for ID". In my situation it fails on 5 out of 138 environments for different user ids.

![image](https://github.com/microsoft/coe-starter-kit/assets/171147560/7b6d4f9d-6360-4a94-9f20-dde6697301c1)

**Comment by Alyson95170** [comment]
I have just checked the environment and the service account running the CoE was not listed as system admin in the environment it was trying to gather the information from, I have added this now and re-submitted and now running successful .

**Comment by eeuo** [comment]
I got this also working after installing this workaround solution "PIMWorkaroundSolution_1_0_0_3_managed.zip" and running the flow in it. After that I manually run the "Admin | Gather Tenant SRs" flow and it succeeded.

The instructions to workaround can be found here: https://github.com/microsoft/coe-starter-kit/issues/8119

**Comment by Alyson95170** [comment]
Hi Jenefer
I have noticed that the new environment that did not have the my CoE service account added as system admin, had not updated the dataverse tables with the flows that are in the environment.
The Driver flow had ran and sync template v4 (flows).
How do I get this to update? when checking through the flows they have ran on 01/07/24
Thanks

**Comment by Alyson95170** [comment]
Ah there is a new version of the CoE I need to update to as I have no flows showing since my update on 18th June

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not entirely sure what you are seeing. 

Regarding new environments not getting their data filled. Yes that is due to the issue described above. https://github.com/microsoft/coe-starter-kit/issues/8119

We cannot ship yet with a fix to this as it relies on a connector action not yet available in some regions. However we do have ICM for the remaining regions and believe this should be fixed for August release.

Until then you will need to download the solution in https://github.com/microsoft/coe-starter-kit/issues/8119 to get data from new envts in place. I've pasted that here for your ease as well

**The workaround until we ship with the kit**

1. Create connections to both Power Platform for Admins and Power Platform for Admins V2 connectors
2. Install this solution: [PIMWorkaroundSolution_1_0_0_3_managed.zip](https://github.com/microsoft/coe-starter-kit/files/15294724/PIMWorkaroundSolution_1_0_0_3_managed.zip)
3. Turn on the flow: PIM Workaround Flow

**Comment by Alyson95170** [comment]
Thanks Jenefer, I had missed the post about updating to 4.32.2, I have now done this but seeing 2 versions withing the solution, should I delete the old version?
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/c98ca50e-eb08-4292-823c-1b3dc5443d16)

**Comment by Jenefer-Monroe** [comment]
Do you mean you see two Core Components solutions?

**Comment by Alyson95170** [comment]
Yeah, I have 4.32 and 4.32.2 showing, should I deleted the lower version?
![image](https://github.com/microsoft/coe-starter-kit/assets/82215551/43224e13-872f-4401-abec-4288a5b25537)

**Comment by Jenefer-Monroe** [comment]
ok thanks I wasn't sure from the first picture. This usually means that the uninstall of the old one failed. 
Here is a blurb about this we have written up, please let me know what error you see.

### Two Solutions!
When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. 
These will never converge or repair on their own, you will need to take action to resolve as a result. And until you do, you are in an unknown state.
If you go to history you may find where the failure occurred and download details about it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb0966a6-dbfb-400b-b796-5ecb5d20c1da)
And if you don’t, then you should delete the _upgrade. And try to upgrade again to see either if it succeeds this time, or if you see the error message this time.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
