### ISSUE TITLE
[CoE Starter Kit - Feature]: Flows Roles inventory synch

### ISSUE THREAD

**Issue by kskramki** [microsoft/coe-starter-kit#8570]
### Is your feature request related to a problem? Please describe.

As the Flows too have Co-Owners but roles are not synched up in the inventory as like Power Apps roles. 

### Describe the solution you'd like

Have the inventory of roles for Flows synched so that can be used in orphaned reassignment, inactivity process and communications

**Comment by Jenefer-Monroe** [comment]
Hello, well timed request. This work has been done for the upcoming July release later this week. Please see https://github.com/microsoft/coe-starter-kit/issues/1083

**Comment by kskramki** [comment]
Thats great update. Thank you.

**Comment by Jenefer-Monroe** [comment]
I've set the milestone of this question so it will close with that release. That way you'll know when its available.

**Comment by Jenefer-Monroe** [comment]
Build is available.
