### ISSUE TITLE
[CoE Starter Kit - BUG] Blogs in CoE Admin Command App

### ISSUE THREAD

**Issue by Titoleto** [microsoft/coe-starter-kit#8573]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Power Apps, Power Automate and Power Virtual Agents ((this name should be changed) blogs are not being filtered correctly.
In the Items of the element pivotNav:
- for Power Apps the ItemKey property should be power-apps instead of powerapps.
- for Power Automate the ItemKey property should be power-automate instead of power-automate
- for Power Virtual Agents the ItemKey property should be microsoft-copilot instead of power-virtualagents

It doesn't show icons either, probably because the OnStart when creating the colRSSNew collection is not doing it right in the If condition filtering by the primaryLink. For example, it is searching for powervirtualagents.microsoft.com when it should be searching for microsoft-copilot.

![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/fea69d38-581c-4808-9e73-96427b30a8f3)

![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/769a2da6-6527-4c71-9dc7-8e19248aefe3)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3796

**Comment by Jenefer-Monroe** [comment]
Looks like some things shifted since we shipped this. Easy fix. Done for August. Thanks for posting

**Comment by Titoleto** [comment]
> Looks like some things shifted since we shipped this. Easy fix. Done for August. Thanks for posting
In addition to what I said yesterday, no blog is listed today.
![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/6705354a-690c-481d-9b6f-4ed9ca03aa10)
I've made a small canvas application in which I've only put the collection
ClearCollect(
            tempCollection,
            RSS.ListFeedItems("https://powerapps.microsoft.com/en-us/blog/feed/"),
            RSS.ListFeedItems("https://powerautomate.microsoft.com/en-us/blog/feed/"),
            RSS.ListFeedItems("https://microsoftcopilotstudio.microsoft.com/en-us/blog/feed/"),
            RSS.ListFeedItems("https://powerbi.microsoft.com/en-us/blog/feed/")
        )

 and I'm getting the following error
![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/144971c5-8a9d-40b5-8f2a-fcdb53376f43)

From what I've seen, the error occurs in exactly this RSS Feed
RSS.ListFeedItems("https://powerautomate.microsoft.com/en-us/blog/feed/")
If I remove it from the collection, the rest of the RSS Feed are fetched correctly.

**Comment by Jenefer-Monroe** [comment]
Looks like the product is continuing to iterate here as this behavior has changed from yesterday for me. 
Let's let it sit for a bit and see what flushes out in the end.

**Comment by Jenefer-Monroe** [comment]
it looks like that power automate redirect is working again

**Comment by Titoleto** [comment]
> it looks like that power automate redirect is working again

They must be doing something since it failed again today.

**Comment by Jenefer-Monroe** [comment]
I just gave up on redirects:

    ClearCollect(
            colRSS,
            RSS.ListFeedItems("https://www.microsoft.com/en-us/power-platform/blog/power-apps/feed/"),
            RSS.ListFeedItems("https://www.microsoft.com/en-us/power-platform/blog/power-automate/feed/"),
            RSS.ListFeedItems("https://www.microsoft.com/en-us/microsoft-copilot/blog/copilot-studio/feed/"),
            RSS.ListFeedItems("https://powerbi.microsoft.com/en-us/blog/feed/")
        )



![Image](https://github.com/user-attachments/assets/daa7f64b-70ac-465d-94b9-0abdb33f4e88)

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
