### ISSUE TITLE
Issue with CLEANUP Admin - Sync Template v3 (Orphaned Users)

### ISSUE THREAD

**Issue by ThomAstra11** [microsoft/coe-starter-kit#8574]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Suddenly the flow CLEANUP Admin - Sync Template v3 (Orphaned Users) is not running anymore. After many minutes of runtime (> 20 min) the flow fails in the step - Tenant - Apply to each Tenant - Look up in AD - Tenant User Count with an "Unauthorized" error message (see picture below) when it tries to get access to the URL https://graph.microsoft.com/v1.0/users/$count. Unfortunately we've no clue why this happens. So could you please be so kind and help us?

![Cleanup - Admin - Sync Template v3 (Orphaned Users)](https://github.com/microsoft/coe-starter-kit/assets/120015451/a714e9f3-6021-4606-a7f4-3b4ce0d13847)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Admin Sync Template v3 (Orphaned Users)

### What method are you using to get inventory and telemetry?

Data Export

### Anything else?

![Cleanup - Admin - Sync Template v3 (Orphaned Users)](https://github.com/microsoft/coe-starter-kit/assets/120015451/acff1afd-0424-4ff2-b8c8-e4a34716e79d)

**Comment by Jenefer-Monroe** [comment]
Can you plese go check to see how your **_HTTP with Microsoft Entra ID (preauthorized)_** connection is configured? 

Please go to connections and make sure the connection for these is as follows (or your tenant equivalent if you are not a commercial tenant: https://graph.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f49797b8-0f48-4884-a026-2580bbc8b96f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a31b22b8-bc81-4d81-a5b7-80dc740f2b82)

**Comment by ThomAstra11** [comment]
Hi Jenefer, indeed the settings were wrong. After changing them according your advice everything went well. Thanks a lot for your help. Really appreciated.

**Comment by Jenefer-Monroe** [comment]
Hurrah!!! Thanks for following up to let me know!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
