### ISSUE TITLE
Manage Permissions App - Not all flows are shown

### ISSUE THREAD

**Issue by Mmace123** [microsoft/coe-starter-kit#8578]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have an issue where not all flows are being shown in the Manage Permissions App.

The user has multiple flows, but only three are being shown in the app
![image](https://github.com/microsoft/coe-starter-kit/assets/114146687/95179983-578d-4203-a4c7-449bd0f54c93)

Here is the full list that I got from Powershell
![image](https://github.com/microsoft/coe-starter-kit/assets/114146687/466f6fbd-038b-4b47-98c1-63326e7783a6)

We are using BYODL, and all sync flows are turned on.

### Expected Behavior

All flows should be shown in the app

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Manage Permissions

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. Go to Manage Permissions App
2. Change to default environment
3. Search for Owner Name

**Comment by Jenefer-Monroe** [comment]
Can you please check to see if these flows exist in the inventory at all by looking in the Power Platform Admin View app? 

Looks like you are checking for the environment as a whole, not for an individual user and that you only have a few flows shown from Default envt, is that accurate? 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ea5b68f2-960b-4400-a4d2-4380f69c4b9a)

**Comment by Mmace123** [comment]
Yes, they all exist in the **Power Platform Admin View** app
![image](https://github.com/microsoft/coe-starter-kit/assets/114146687/6eb8d1cc-6273-49df-932c-ed0403e42820)

But do not all appear in the **Manage Permissions** app.

**Comment by Mmace123** [comment]
I see. If I go via the Owners tab, then yes all show up.

But, if I go via the environment tab and then use the search and put in the Owner's name only three show up. Is that how it is supposed to work, and I should avoid searching the environment tab version?

**Comment by Jenefer-Monroe** [comment]
Yes we dont have the owner name when in the envt tab for searching. 
So glad we found the answer!

**Comment by Mmace123** [comment]
I will use the owner tab only to search owner apps/flows
