### ISSUE TITLE
[CoE Starter Kit - QUESTION] Do we have anything in COE for list of on-premised gateways are used and Power Platform 

### ISSUE THREAD

**Issue by pamatihyd** [microsoft/coe-starter-kit#8579]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Do we have anything in COE for list of on-premised gateways are used and Power Platform 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4,31

### What app or flow are you having the issue with?

Admin-Sync V3 Template 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Unfortunately no, we do not have any tracking of gateways. To our knowledge this is not something exposed to us in a way that can be consumed by the kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by lukas-nC** [comment]
@Jenefer-Monroe you can get gateway information via the Power Apps for Admins connector and the Get Connections as Admin action.
<img width="116" alt="image" src="https://github.com/user-attachments/assets/fc20f323-1e4f-4db6-8ba7-13361c8c26ae">

Would be nice to know which ressources use a gateway
