### ISSUE TITLE
[CoE Starter Kit - QUESTION] Consumption BOT 

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#8583]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Olá, bom dia!

do we have anything related to bot consumption?

obrigado pela ajuda!

### What solution are you experiencing the issue with?

Governance

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Yes you can see it in the Power Platform Admin View app
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/15b989d1-8f59-4b29-8aea-ba331e2248ed)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
