### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE Missing security roles from environment

### ISSUE THREAD

**Issue by Tracharr** [microsoft/coe-starter-kit#8586]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

One of my production environments is missing the approvals security roles, they exist in the other environments - how to I fix it please? the environment is in the same dlp policy as the others
I have attached screenshots 
![problem environment](https://github.com/microsoft/coe-starter-kit/assets/135856790/1d1e42ac-3384-43af-aa1b-c61f75713621)
![Ok environment](https://github.com/microsoft/coe-starter-kit/assets/135856790/d4084f5f-7a32-4701-8c37-5ebd5b3d6896)

### Expected Behavior

Expected to have approvals admin & approvals user security role in environment

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

approvals security roles

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

see screenshots

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately this is a product issue and not an issue with the kit. However I think I know how to repair so let's see if this answers. 
Basically by default the power automate approvals system is not automatically installed in environments, you need to instantiate it. Here are the instructions from the kit which describe how to do this: [Initialize flow approval tables in your environment](https://learn.microsoft.com/power-platform/guidance/coe/before-setup-gov#initialize-flow-approval-tables-in-your-environment)

**Comment by Tracharr** [comment]
Hi - thanks and apologies it had been so long had forgotten about that doc - am going to run on all environments now.
