### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE: No data being shown in Power Pages dashboard on CoE.

### ISSUE THREAD

**Issue by MarkMcCrory67** [microsoft/coe-starter-kit#8587]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have deployed three Power Pages in our MPP Environments but we cannot see anything in the Power Pages Dashboard or gather any data to generate a report.  We have recently updates the CoE core components and all other available updates but this has made not difference.

I have seen these related bugs but with no real solution 

[CoE Starter Kit - BUG] Power Pages missing from the COE dashboard #8318

which then refers to this but with no relevant solution. 

[CoE Starter Kit - BUG] Redo Portals flow with their new architecture #8038

### Expected Behavior

should show data

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

not sure

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

look at the Power Pages dashboard

**Comment by Jenefer-Monroe** [comment]
Hello. Yes unfortunately we are blocked for the time being. The product changed its architecture and we cannot yet use the new connector for gathering the needed data to get this inventory. Please monitor https://github.com/microsoft/coe-starter-kit/issues/8038 to be aware of when we can do that work.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
