### ISSUE TITLE
[CoE Starter Kit - BUG] App Usage are blank in the COE report

### ISSUE THREAD

**Issue by NileshEcleva** [microsoft/coe-starter-kit#8588]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi All, I have installed COE but App usage is not showing anything.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.3.2

### What app or flow are you having the issue with?

App Usage

### What method are you using to get inventory and telemetry?

None

### Anything else?

Over App usage all data is blank
![image](https://github.com/microsoft/coe-starter-kit/assets/170582749/68ba209d-5c7c-4619-aac3-ad86a5e9e2d0)

**Comment by Jenefer-Monroe** [comment]
Hello, 

Which architecture are you using? (cloud flow or Data Export). And which PBIT file are you using? 
I will presume cloud flow architecture and Production_CoEDashboard_ _MonthYear_ for this conversation as that is the normal one.

Have you setup the audit log flows? These two flows should be running and passing often.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/34a80640-af17-407f-8185-b882c482e562)

**Comment by NileshEcleva** [comment]
Hi Jenefer,

I have turned on both the flows, but still App usage showing blank.




Thanks & Regards,


[cid:d72c02ea-9499-4c43-acd2-f12c7b67e096]<https://www.ecleva.com/>



Level 9, Suite 12, 100 Walker St.

North Sydney 2060

www.ecleva.com<http://www.ecleva.com/>



Nilesh Vaishnav

Sr. Support Engineer

+91 8824980951 |+61 2 9467 9300<tel:+61%202%209467%209300>

***@***.******@***.***>































________________________________

**Comment by Jenefer-Monroe** [comment]
Which architecture are you using? (cloud flow or Data Export). And which PBIT file are you using?

**Comment by NileshEcleva** [comment]
Hi,

I am using cloud flow, and PBIT file is Production one.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
