### ISSUE TITLE
[CoE Starter Kit - BUG] App Usage has stopped collecting

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#8589]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi - Our CoE is using BYODL. Our Apps usage numbers in the BYODL dashboard power bi reports only show model driven apps. the canvas apps stopped about 5 weeks ago
If i go to the dataflow in the power bi workspace , i see records for the dates since it stopped working. 
If i click on the 'source'from the dataflow table (see image below), i get 'we encountered an unexpected error for the Azure Data Lake Storage Gen2 - i am troubleshooting this but posting here aswell in case anyone has seen this

### Expected Behavior

show app usage for canvas apps. its showing zero

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

no flows are part of this

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

view app usage dataflow results

### Anything else?

![image](https://github.com/microsoft/coe-starter-kit/assets/78494876/a77d8e30-fbbc-4510-a68d-a8ebb890db6d)

**Comment by Jenefer-Monroe** [comment]
I'm afraid I dont know what's happening for you. I do see this working on my side. 
Perhaps ensure you are using the DFs from the Jan 2024 release and that the Datalake URL is in a format like this: https://storageaccountname.dfs.core.windows.net/powerplatform

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/6f1ef3d5-fbc7-4bdd-b8bd-b83242244a23)

**Comment by ryan-stuchbery** [comment]
Hi, 
We're experiencing the same issue with app usage data not making it through the data flow into the Dv table. It appears to have started at around 22-May. 
Investigating the dataflow, I can see plenty of usage data in the first screenshot below, but it is filtered away at the next step in the second screenshot. However, I don't know how to fix this.
![image](https://github.com/microsoft/coe-starter-kit/assets/175266045/c5f934b7-657e-4e55-a3cd-7863f059917c)
![image](https://github.com/microsoft/coe-starter-kit/assets/175266045/6eb14109-1956-456e-9ba9-9105a7f64af8)

**Comment by ryan-stuchbery** [comment]
When we started experiencing the issue we were also using Core Components 4.23 but I have just upgraded to 4.32.2 and the issue has not resolved itself.

**Comment by Jenefer-Monroe** [comment]
Ryan, I think your issue is different as I believe you are using the Dataflows for import into DV tables while OP is using the DF for the PowerBI. They are different Dataflows and behave diferently. Can you post your own issue as a result ?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by ryan-stuchbery** [comment]
We figured out the issue we were experiencing with the app usage dataflow. The app usage data is being merged with the admin_app table using the "Admin_App" column but it should have been using the "Admin_appidstring" column
![image](https://github.com/user-attachments/assets/8c87d03a-0548-4faa-a6b7-8ce9b6e72f27)
