### ISSUE TITLE
[CoE Starter Kit - BUG] Circular Dependencies Preventing solution deletion

### ISSUE THREAD

**Issue by j-saxton** [microsoft/coe-starter-kit#8590]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Attempting to remove Center of Excellence - Core Components. When I attempt to remove the solution I get a list of dependencies shown in the first image. 
![image](https://github.com/microsoft/coe-starter-kit/assets/47197212/bddf713f-611c-4566-b1e6-a49bd58fdbfd)

When I attempt to delete the dependencies, in this case PowerApps App table, so that I can remove the Center of Excellence - Core Components solution, I get a list of dependencies that includes Center of Excellence - Core Components. See second image attached. 
![image](https://github.com/microsoft/coe-starter-kit/assets/47197212/85d9f37f-f709-4c9c-aabe-e9e1431c2eba)

### Expected Behavior

I'd like to be able to cleanly remove the solutions from this environment. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.8

### What app or flow are you having the issue with?

Center of Excellence - Core Capabilities

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Try to remove the Center of Excellence - Core Capabilities solution

List of dependencies should be returned. Try to remove a dependency.

Should point back to Center of Excellence - Core Capabilities solution as a dependency

**Comment by Jenefer-Monroe** [comment]
If you have other CoE solutions installed, remove those first. 
But if you don't then I'm afraid you are just hitting product issues with ALM and uninstall and we may not be able to assist from afar. We can try though. 

I see the old audit logs custom connector in there. I know sometimes people struggle with that as they will have connections to it hidden from the UX. 
Please see steps and community notes in https://github.com/microsoft/coe-starter-kit/issues/6018
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7b1c80f4-7b22-4a2f-b1b9-6eb5f57d9de5)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
