### ISSUE TITLE
[CoE Starter Kit - Feature]: Automated Install - Setup Wizard - Connection consent

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/coe-starter-kit#8591]
### Is your feature request related to a problem? Please describe.

To support [Automated Install Roadmap](https://github.com/microsoft/coe-starter-kit/issues/8565) when automating the install of CoE Kit a consent dialog is shown. Until all the connections are created and confirm with selection of "Allow" the wizard process will not proceed.

![image](https://github.com/microsoft/coe-starter-kit/assets/31553604/80d29aef-47d6-4c8a-a1e5-edb1511959ab)

### Describe the solution you'd like

1. Combine with [Test Engine Create Connection](https://github.com/microsoft/PowerApps-TestEngine/issues/352) to first ensure that all the required connections are created.
2. Validate of connections have been consented by user
3. Select Allow if prompted

**Comment by Grant-Archibald-MS** [comment]
Included as part of Power Apps Test Engine [Create Connection](https://github.com/microsoft/PowerApps-TestEngine/issues/352) and the Model Driven Application [Model Driven Application - Consent Dialog](https://github.com/microsoft/PowerApps-TestEngine/issues/353).

Samples created to support this scenario:
- [Power Apps Portal - Create connection](https://github.com/microsoft/PowerApps-TestEngine/blob/grant-archibald-ms/power-apps-portal-348/samples/portal/testPlan.fx.yaml)
- [Model Driven Application - Consent Dialog](https://github.com/microsoft/PowerApps-TestEngine/blob/grant-archibald-ms/provider-mda-342/samples/coe-kit-setup-wizard/testPlan.fx.yaml)

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
