### ISSUE TITLE
[CoE Starter Kit - QUESTION] Video hub Excel with Microsoft Curated learning Import failed with Invalid Format error

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8602]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

@manuelap-msft , followed the steps to get the Microsoft curated learning starter data, but I am getting the error that Excel is in Invalid Format. Please help to understand if its a bug or I am missing something.

<img width="613" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/bfcbb8e2-222a-46bd-9c26-cbffdd29eae4">

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

June 2024

### What app or flow are you having the issue with?

Nurture-Admin App

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I just tested with the sample file and it worked for me. Can you please try again? Perhaps some intermittent product issue.

This is just an out of the box product feature we are using so not much we can do here.

**Comment by PPMini** [comment]
Hi @Jenefer-Monroe , thanks for looking into this. I realized that I have upgraded only the Nurture components of the kit with June version. I think that mismatch have led to this error. I believe I will be good once I will have all streamlined versions. Closing this out.
