### ISSUE TITLE
[CoE Starter Kit - BUG] In Power Platform admin view app, Active environments moved to deleted state in 

### ISSUE THREAD

**Issue by thotavinod590** [microsoft/coe-starter-kit#8603]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have turned on the flow. CLEANUP - Admin | Sync Template v4 (Check Deleted) Yesterday, flow was run successfully, but active environments also moved to the deleted state. Can I know why those active environments moved to the deleted state. How can we move those to environment active state. 850 environments moved to deleted state. 

Related issue : https://github.com/microsoft/coe-starter-kit/issues/8553

image

image

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Power Platform Admin view

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently? 
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

**Comment by thotavinod590** [comment]
@Jenefer-Monroe user role is Global Administrator and Membership is Direct

**Comment by Jenefer-Monroe** [comment]
It is also permanent?

**Comment by thotavinod590** [comment]
@Jenefer-Monroe Yes it marked 850 environments deleted

![image](https://github.com/microsoft/coe-starter-kit/assets/164856137/99c1e1ff-e0fd-4401-b6c6-03b1dd63238c)

**Comment by thotavinod590** [comment]
How can we revert these 850 records data to normal state

**Comment by Jenefer-Monroe** [comment]
So you need to have the role have permanent access to the role or this will just happen again. 
If you cannot get permanent access to Global Admin then Power Platform Admin Role will work as well. 

After you correct this issue with the role, then the next run of **_Admin | Sync Template v4 (Driver)_** will fix it up.

**Comment by thotavinod590** [comment]
@Jenefer-Monroe Admin | Sync Template v4 (Driver) is a scheduled flow; it ran yesterday, and now we can see all the active environments, including the 850 environments that were moved to deleted yesterday. This will also apply to apps and flows, or only environments. Can you please elaborate what is the dependency of Assigned role permanent to this flow and why we have to update because these flow running with the global admin privileges.

![image](https://github.com/microsoft/coe-starter-kit/assets/164856137/755809da-f1f2-455d-99fd-fa9a361917f3)
![image](https://github.com/microsoft/coe-starter-kit/assets/164856137/01dcde6b-59b5-4348-8a4d-70c15b782fc6)

**Comment by Jenefer-Monroe** [comment]
The kit only gathers information about the envts to which the identity running the flow has admin access. 
The Power Platform Admin Role, permanently assigned, is required to fetch information about the tenant as a whole regardless of the time of the flow run. 

Note that the required roles and licenses must be available to this user continuously; if admin access is granted only temporarily via [Privileged Identity Management (PIM)](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management), this won't be sufficient to run the CoE Starter Kit.
For more information please see [What identity should I install the CoE Starter Kit with?](https://learn.microsoft.com/power-platform/guidance/coe/setup#what-identity-should-i-install-the-coe-starter-kit-with)

If the flow runs when you do not have the correct access it will not get the objects and they will detected as deleted.

**Comment by Jenefer-Monroe** [comment]
Please grant the user identity running the flow permanent and direct access to either Global Admin or Power Platform Admin Role. Then all your objects will be restored as the flows run and they will not be removed later.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
