### ISSUE TITLE
[CoE Starter Kit - QUESTION] How works InventoryMe and InventoryMyFlowActionDetails

### ISSUE THREAD

**Issue by albertocastro365** [microsoft/coe-starter-kit#8605]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team,
I am reading the documentation and topics in this forum but I don't have clear the use of InventoryMe and InventoryMyFlowActionDetails in tables Flow or Power Apps App.
Could you explain it?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2024

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
These are flags you can use to force inventory. 

So all objects have an "Inventory Me" flag, and if you set it, then the object will be forced through inventory even if its not identified as new or modified recently. 

Then the same is true for InventoryMyFlowActionDetails expect that this only applies to cloud flows. If you set it to true then we will inventory the flows details in **_Admin | Sync Template v3 (Flow Action Details)_**  even if the flow is not identified as new or recently modified.

Hope that helps.

**Comment by albertocastro365** [comment]
Ok, then in a normal situation and using Data Export, the "InventoryMe" flag should be enable or disable?

**Comment by Jenefer-Monroe** [comment]
Data Export will impact only the apps and cloud flows so other objects will use the fields in the same manner

We do not set this in the dataflows, no. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7e27a6b4-20e1-4fb3-9242-b3d104c01044)

But we do read it and manually inventory in the event that is something that is requested:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc39aaa0-858c-4c89-9fa1-ff3fe26321f0)

**Comment by albertocastro365** [comment]
Sorry, I mean, what is the best practice? To disable this flag in all rows of flows/apps and only enable it in the items that we need to force re-inventory?

**Comment by Jenefer-Monroe** [comment]
The flag should clear itself when the kit goes through inventory. I would suggest not touching it unless you want to set the flag to true.

**Comment by albertocastro365** [comment]
Ok, understood it! Thanks!
