### ISSUE TITLE
Admin | Sync Template v3 (Flow Action Details) run failed - Append http Action

### ISSUE THREAD

**Issue by EggertN** [microsoft/coe-starter-kit#8610]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello together,
since one week the Flow runs failed in only one Environment. This environment has a lot of solutions and flows with http connectors and many arrays in different connectors/flows.
The first failure is shown in the Scope **Update flow action details**:
![image](https://github.com/microsoft/coe-starter-kit/assets/112888571/a4633a58-1857-49e2-8036-195f876fc884)

Then in the scope **Get Specialty ActionDetails**:
![image](https://github.com/microsoft/coe-starter-kit/assets/112888571/599e8159-334b-45de-9d44-a39e065dd37a)

And than you see it in the **Append each Http Action**:
![image](https://github.com/microsoft/coe-starter-kit/assets/112888571/6944dbcf-8260-4a86-bcde-772699109952)

What can I do ?

Thanks for your help.
Regards
Nicole

### Expected Behavior

this is a standard flow from the coe and I don´t know there is a restriction for Arrays... and we are not such a big company so i am wondering what greater companies do with much more flows withs arrays

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Environment AKA-DLS_DEV

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately you've hit a product limitation described and tracked here: https://github.com/microsoft/coe-starter-kit/issues/6819

We do have this on our backlog for consideration but don't have an idea of how to make this better without blowing out the API calls by removing the set logic which makes this flow feasible for others.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by michael-wright-pwc** [comment]
@Jenefer-Monroe we just upgraded to Sept version of Core Components also w/sync flow architecture and are hitting this same issue in our DEV tenant which is 1/1000 of the size of our PROD tenant. To this user's point, if we're hitting this product limit with relatively small tenants it's going to blow up in even medium size tenants. Any chance for revisiting this one or any suggestions on how to deal with it?
