### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE Admin | Newsletter with Product Updates flow, List Flow Blog RSS feed items fails

### ISSUE THREAD

**Issue by MgNa-H2O** [microsoft/coe-starter-kit#8612]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have a failed flow Admin | Newsletter with Product Updates, under the action "List Flow Blog RSS feed items" with the following error message "Failed to read requested feed because the content returned is not valid XML format. Details: The element with name 'html' and namespace '' is not an allowed feed format.
clientRequestId: 042xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
![Untitled](https://github.com/microsoft/coe-starter-kit/assets/86013325/26209c1b-a3f0-41a7-b6aa-0033c501215e)

### Expected Behavior

Flow run successully.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Admin | Newsletter with Product Updates

### What method are you using to get inventory and telemetry?

None

AB#3797

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. The product seems to have been changing these urls so we will need to update here and in a few other spots for August.

**Comment by MgNa-H2O** [comment]
Thank you for your reply @Jenefer-Monroe , will you provide the update link here or we will need to wait for the August CoE update to resolve this?

**Comment by Jenefer-Monroe** [comment]
I can share a screenshot of my changes when I do them, and you can local apply if you would like. I'll probably take a look at this one later this week or early next week.

**Comment by MgNa-H2O** [comment]
Sounds good, please share the changes when it is available. Thank you!

**Comment by Jenefer-Monroe** [comment]
Looks like this is working again. I think one of the redirects was just broken temporarily.

**Comment by MgNa-H2O** [comment]
Ok, I will re-run it again, thank you for checking.

**Comment by Jenefer-Monroe** [comment]
They broke again. Ugh. I just gave up on redirects. 


Here are the new URLS


![Image](https://github.com/user-attachments/assets/058f422d-73c9-43ee-ba6c-937066ece020)

https://www.microsoft.com/en-us/power-platform/blog/power-apps/feed/

https://powerusers.microsoft.com/jgvjg48436/rss/board?board.id=PowerAppsBlog

https://www.microsoft.com/en-us/power-platform/blog/power-automate/feed/

https://powerbi.microsoft.com/en-us/blog/feed/

https://www.microsoft.com/en-us/microsoft-copilot/blog/copilot-studio/feed/

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
