### ISSUE TITLE
CoE Flows consuming too much data, running too many actions, throttled

### ISSUE THREAD

**Issue by johnravas** [microsoft/coe-starter-kit#8613]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In reviewing the email used for the service account that manages our CoE, I am noticing messages that indicate things like "Your flow is running too many actions", "your flow is consuming too much data" and in some cases flows have been throttled.  I searched on these types of issues and reviewed the responses.  The flows that are seeing these messages are:

- Admin | Sync Template v3 (Flow Action Details) - running too many actions
- Sync Helper - Cloud Flows - running too many actions- and frequently exceeds the limit
- Admin | Sync Template v3 (Solutions) - running too many actions & throttled
- Admin | Sync Template v3 (Ai Models) - throttled (regularly)
- Admin | Audit Logs | Sync Audit Logs (V2) - consuming too much data

All of these flows are still running.  None have been shut down.  We are currently running the November edition of the CoE starter kit.  The issued with the Sync Template v3 (Solutions) flow started in late January, just before we upgraded to the Nov edition (in mid-Feb).  The other issues started on 3/27/24.

Here are my questions:

- Will upgrading to a more recent version of the kit help?
- The flows all seem to be running successfully, are they collecting all of the data correctly?  Some of these flows are exceeding the limit of 200000
- Are there any settings we can tweak to fix this?

We are not a huge tenant, but large enough at 1,700 users and a growing number of Power Automate flows.  It seems that we must have grown to a point where this became an issue?  It wasn't an issue earlier.

Thanks in advance

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

See above

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, the Power Automate product is slowly ramping down the number of API calls that you can call for a single identity. 
Here is some information about these licenses:
[Compare Power Automate plans](https://learn.microsoft.com/power-platform/admin/power-automate-licensing/types#compare-power-automate-plans)
[License entitlements - Power Platform requests](https://learn.microsoft.com/power-platform/admin/power-automate-licensing/types#power-platform-requests)

**Comment by Jenefer-Monroe** [comment]
The plan is for the product team to take over this inventory system over time. The first attempt at this was with the Data Export methodology currently in preview. And we are working with the product team now on a big schema update for that which we hope will get us over the finish line. 
It is not recommended at this time to try out the current Data Export feature for new customers but instead wait for us to release something in the fall with the big schema change.
Until then, unfortunately, the only solution here is to add per-flow (aka process) type licenses for these.

**Comment by Jenefer-Monroe** [comment]
Two things to check in the meantime
1. Does the user identity running the kit have direct and permanent access to the Power Platform Admin role? 
If not permanent then you may be spending cycles re-adding objects over and over
2. Does the user identity running the kit have a **_Power Automate premium_** plan? If you are just re-using the **_Power Apps Premium_** license then this may be a cheap way to get a bunch more API calls for the near term.

**Comment by johnravas** [comment]
@Jenefer-Monroe Thank you for your response.  For your questions above:

1.  Yes, direct and permanent Power Platform Administrator role plus the System Administrator role in the environment that contains our CoE.
2. So interesting, the account has Power Apps Premium, **but not Power Automate Premium**.  Going to make this assignment too.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
