### ISSUE TITLE
Issue with loading data into Production_CoEDashboard_June2024

### ISSUE THREAD

**Issue by Agentebrink** [microsoft/coe-starter-kit#8614]
When I try to open the CoE Production_CoEDashboard_June2024 dashboard, I get the following error:

"22 queries are blocked by the following error:
AI Credits Usage
The key didn't match any rows in the table."

![image](https://github.com/microsoft/coe-starter-kit/assets/174495479/fbda528c-5a7e-4828-b288-79b91e32d0a5)

When reviewing the transform data I see that query "AI Credit Usage" is generating the following error:

Expression.Error: The key didn't match any rows in the table.
Details:
    Key=
        EntitySetName=admin_aicreditsusages
    Table=[Table]

![image](https://github.com/microsoft/coe-starter-kit/assets/174495479/c677a690-9b5a-4a29-a44f-8560bc2996a1)

**Comment by Jenefer-Monroe** [comment]
Hello. 

1. Please be sure you are using a matching version of Core. The PBI and the solutions must match. So for _June2024 you will want to have Core version 4.32.2 installed.

2. Please validate that you have entered the URL for your envt correctly including prefix and ending slash. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed605483-330a-434f-b83f-c5ccb3d884c6)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1caa55a2-14e7-4336-860f-5dbcc1576e1a)

3. Please view the Power Platform Admin View app, do you see data for objects there? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f37bd3c7-66ab-46bd-a19b-53fdd9df8dd6)

**Comment by Agentebrink** [comment]
Hi Jenefer

Indeed, I was using different versions. When I opened the dashboard corresponding to the installed version, everything worked perfectly. 

Thank you so much for your response; without your help, I would never have found this error. I keep learning more and more about this CoE solution. 

Have a great day.

**Comment by Agentebrink** [comment]
Hi Jenefer

Indeed, I was using different versions. When I opened the dashboard corresponding to the installed version, everything worked perfectly. 

Thank you so much for your response; without your help, I would never have found this error. I keep learning more and more about this CoE solution. 

Have a great day.
