### ISSUE TITLE
[CoE Starter Kit - BUG] Flows missing from COE Admin portal

### ISSUE THREAD

**Issue by Brice235i** [microsoft/coe-starter-kit#8615]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, flows in solutions are no longer appearing in the admin portal.  The solution is there, as are related apps, just not flows. I checked some older solutions and the flow inventory was complete.  Seems to be only solutions built recently.  Anyone else seeing this?

### Expected Behavior

a full inventory of solution aware flows appears in the COE portal

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.1

### What app or flow are you having the issue with?

possible the sync flow

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

create a solution, add some flows.  Then go to admin portal > flows.  recent solution aware flows are missing.  Go to a recent solution > related > flows... flows also missing.

**Comment by Jenefer-Monroe** [comment]
Hello, I'm not sure what build you are on, can you please share that information? 
There was a recent change in the product which started to return unpublished flows and we did have to ship an update in June (4.32.2) to ensure the correct flows are inventoried. 
So please make sure your version of core is at least 4.32.2

**Comment by Brice235i** [comment]
Thank you, we are 1 version behind so will update on Monday.  Thanks!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
