### ISSUE TITLE
[CoE Starter Kit - QUESTION] Is there a way to find apps/flows using premium features?

### ISSUE THREAD

**Issue by rooobeert** [microsoft/coe-starter-kit#8616]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi all, 

I saw that there is a property in the powerapps app table for "uses premium api". This way we can check if there is premium apps in our environments, right?

Is there any way to do this with flows? I have not yet found a property for that. 

Thanks
Robert

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Yes this does appear to correctly show if a canvas style app contains premium features. 
Note that it is gathered directly from the product, its not something we deduce. You can see it in the return of Get App as Admin

coalesce(outputs('Get_App_as_Admin')?['body/properties/usesPremiumApi'], '')

This is not returned for flows and so we we do not have that to consume.

**Comment by rooobeert** [comment]
Alright, thanks for the quick answer.
