### ISSUE TITLE
CLEANUP - Admin | Sync Template v3 (Orphaned Users) and SetupWizard>GetTenantID flows failing at HTTP request with BadRequest

### ISSUE THREAD

**Issue by muler-git** [microsoft/coe-starter-kit#8617]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have upgraded Coe to June 2024 version, we see the below flows failed at HTTP request with BadRequest.

CLEANUP - Admin | Sync Template v3 (Orphaned Users)
SetupWizard>GetTenantID

As i verified the connections looks good and rerun also got failed. I didn't find any github articles related to it Please let me know if there is any fix for this issue.

Find the screenshots for reference.

<img width="536" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/125889020/00ab0e3e-2178-4523-bc01-68f38d957b19">

<img width="521" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/125889020/313afeff-5113-4bf1-a5d0-badfaf47d1bd">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2 (June 2024)

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Orphaned Users) and SetupWizard>GetTenantID

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
