### ISSUE TITLE
[CoE Starter Kit - BUG] I have issues in COE dashboard

### ISSUE THREAD

**Issue by Vishruth586** [microsoft/coe-starter-kit#8618]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have installed COE kit in our tenant, however when i open the Dashboard PowerPlatformGovernance_CoEDashboard_May2024 all the pages are not loading in the Power BI application. I need some assistance here.
![screenshot_pages_2](https://github.com/microsoft/coe-starter-kit/assets/43142224/9404c499-8402-473e-9f43-784ff2e0041f)
![screenshot_pages_1](https://github.com/microsoft/coe-starter-kit/assets/43142224/a78938b6-4433-4007-80c9-406d93d44807)

### Expected Behavior

Not able to see the pages in the Dashboard in Power BI

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.3.20

### What app or flow are you having the issue with?

Dashboard PowerPlatformGovernance_CoEDashboard_May2024 

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Not able to see the pages in the Dashboard in Power BI

### Anything else?

Not able to see the pages in the Dashboard in Power BI

AB#3831

**Comment by Jenefer-Monroe** [comment]
Hello. Blanks are expected for some cases in the Governance Dashboard, thats how PBI shows zeros. So you will need to find if those cases are incorrect. Let's focus in this issue instead on the Production_CoEDashboard

For the apps overview page in Production_CoEDashboard
1. Please view the Power Platform Admin View app, do you see data there for apps? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f37bd3c7-66ab-46bd-a19b-53fdd9df8dd6)

2. In the PBI, please validate that you have entered the URL for your envt correctly including prefix and ending slash. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed605483-330a-434f-b83f-c5ccb3d884c6)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1caa55a2-14e7-4336-860f-5dbcc1576e1a)

3. Are other screens in the PBI showing data? Ex Environments

**Comment by Vishruth586** [comment]
Hi Jenefer

Thanks for your response. If we can connect for a call and discuss it would
be great.

Regards
VISHRUTH KM

**Comment by Jenefer-Monroe** [comment]
Hello, sorry we are not staffed to have calls with our GitHub users. Please do try the above and let me know what you see.

**Comment by Vishruth586** [comment]
Hi Jenefer,

Could you please guide me on how to navigate to this page in our tenant,  I
tried to look out couldn't find the same.

Regards
Vishruth

**Comment by Jenefer-Monroe** [comment]
This is one of the main apps you'll use in the kit. You can find more information about the app here: 
[Power Platform Admin View](https://learn.microsoft.com/power-platform/guidance/coe/core-components#power-platform-admin-view)

You'll find it in the solution file: 
![image](https://github.com/user-attachments/assets/13f75b6e-d667-43b4-82e3-2ba3f10a69d1)

**Comment by Vishruth586** [comment]
Hi Jenefer,

I could see this

Please let me know if u need any further information

Regards
Vishruth

**Comment by Jenefer-Monroe** [comment]
Please confirm, so you booted the Power Platform Admin View app and see data for apps there?

**Comment by Vishruth586** [comment]
No I have not booted.

**Comment by Vishruth586** [comment]
I went to the app which you had mentioned and went on play it and the page
viewed which I shared in my previous email.

**Comment by Jenefer-Monroe** [comment]
Sorry I'm not seeing a screenshot. Do you see data in the Power Platform Admin View app? 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f37bd3c7-66ab-46bd-a19b-53fdd9df8dd6)

**Comment by Jenefer-Monroe** [comment]
ok good. So you have data. 
Now return to the Power BI
1. In the PBI, please validate that you have entered the URL for your envt correctly including prefix and ending slash. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ed605483-330a-434f-b83f-c5ccb3d884c6)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1caa55a2-14e7-4336-860f-5dbcc1576e1a)

2. Are other screens in the PBI showing data? Ex Environments

**Comment by Vishruth586** [comment]
I could see pages with data in default environment page.

**Comment by Vishruth586** [comment]
Also when I try to refresh data in PowerBi. I get these errors
Could u please advice

**Comment by Jenefer-Monroe** [comment]
Hello. those would likely be the causing errors. However I cannot see them. Note that you need to log in to GitHub to share screenshots.

**Comment by Vishruth586** [comment]
Kindly find the screenshots
![Screenshot_20240719_135606_Gallery](https://github.com/user-attachments/assets/1769d792-efdb-4e86-9ebc-bab73386fa6d)
![Screenshot_20240719_135609_Gallery](https://github.com/user-attachments/assets/72a63331-3a98-46a7-89ad-f5c23b1d0acf)

**Comment by Vishruth586** [comment]
I am still getting same error

**Comment by Jenefer-Monroe** [comment]
Sorry I'm really not sure. It appears you are having issues with PBI before our report even comes in to the picture. I can offer a few other suggestions but I'm really not able to offer very good PBI product support.

1. Are you logged in to PBI as an identity with access to the dataverse organization 
2. Can you try to set the Privacy level to organization and hit edit?

**Comment by Vishruth586** [comment]
I have PBI setup installed on a server, i use my elevated account and login to server and open the PBI app with same account.
regards to first point i didnt understand could u please tell me more

I tried 2 & 3 nothing worked out.

**Comment by Jenefer-Monroe** [comment]
You installed the kit as some identity. Perhaps your own identity or something like CoEAdmin@yourorg.com
Is that the id which is logged in to PBI?

**Comment by Vishruth586** [comment]
Yes i have installed the kit using my elevated account in my organization and i have logged in PowerBI with the same account

**Comment by Jenefer-Monroe** [comment]
Unfortunately I'm not sure how to help. It appears that PBI is rejecting your credential, closing the connection. 
Not sure if you tried the "Clear permissions" or not but if not please do. 
For both the radio buttons (Data sources in current file and Global permissions), hit clear permissions for everything listed
![image](https://github.com/user-attachments/assets/cea927a4-14da-4947-a133-33dd1281dbf3)

**Comment by Vishruth586** [comment]
yes i tried to clear permissions and for global permissions i get this message
![image](https://github.com/user-attachments/assets/0f9fced7-62f7-43fa-a11d-d3bd4d0c7b6d)

**Comment by Vishruth586** [comment]
Main problem is when i refresh data its not getting signed in with my elevated account which i used to configure COE setup

**Comment by Jenefer-Monroe** [comment]
Sorry I may have misread above, so you are logged in to PBI a different user than the elevated account that setup and configured the CoE?

Meaning, is it that elevated user that is signed in here?
![image](https://github.com/user-attachments/assets/68ea6ead-f1c3-4ebc-8079-060ab17942b6)

**Comment by Vishruth586** [comment]
no i have used my elevated account only

**Comment by Vishruth586** [comment]
i have used elevated account and that is only signed in the power BI app

**Comment by Jenefer-Monroe** [comment]
And this user is System Admin in the CoE environment correct?

**Comment by Vishruth586** [comment]
yes

**Comment by Jenefer-Monroe** [comment]
ok I dont know how to help then. 
PowerBI is rejecting/closing your connection for some reason and I don't know why that could be. Perhaps its license related or some PBI setting that is configured. As I'm not a PBI expert I really don't know how to debug that further.

**Comment by Vishruth586** [comment]
okay sure thank you for all your help, whom can i contact further

**Comment by Jenefer-Monroe** [comment]
I think you'll need to reach out to PBI product support or see if you have a local PBI expert in your organization that can help you get unblocked. 
Unfortunately I'm not sure the best approach forward here.

**Comment by Vishruth586** [comment]
Does the DLP policy will there be any issues in getting the data

**Comment by Jenefer-Monroe** [comment]
No, DLP does not apply to Power BI. DLP will impact the ability to fill the inventory / use the apps / etc. 
But nothing about the PBI connections will be impacted. 

You could try setting this privacy level to organization, that might help. 
![image](https://github.com/user-attachments/assets/4012810a-b3f7-44a4-9427-1a8cafbdf389)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
