### ISSUE TITLE
PIM impact on Toolkit Service Account

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#8621]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Our org is planning on implementing PIM on all 'tenant' admin roles, including the Power Platform Admin role.

I understand that the docs say it must be an active role, however there seems to be changes with respect to the connectors need for the inventory, so I wanted to verify that toolkit SA will need to be 'active' for PP admin role, and that regardless of the coming connector changes that will continue to be the case.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Correct. The identity running the flows needs permanent and direct access to either Global Admin or Power Platform Admin Role. This does not change with the recent product PIM work.

Ex: if the check deleted flows run when the identity does not have access to the role, then some envts may not be returned from that call, and will be detected as deleted.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
