### ISSUE TITLE
[CoE Starter Kit - QUESTION] For Power User site Environment Variable - Can a on-prem SharePoint link be provided?

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8624]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 

We would like to understand that if we could provide the URL of an on-prem SharePoint Site for Power User Site Environment Variable. or do we need gateway to access this? We understand that this variable is not getting used at the moment, but would like to understand this from future perspective.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

April 2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
