### ISSUE TITLE
[CoE Starter Kit - QUESTION] Training Feedback Form Responses

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8625]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 

Could you please help understand where the responses of the training feedback form are getting saved. 
When we tested, we observed neither an email or teams adaptive card is received by the Admin to see the responses of the training feedback form. Responses could only be seen at the form itself, is the correct behaviour? 

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Nurture - Training in a Day component

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello we do not store the feedback within the kit, its stored by whatever feedback system you use. So for the kit we just point them to a (per the recommendation) office form. And then that form stores the feedback in its own system.

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/86bad9bc-2fff-4f91-89dc-52d7aabfcdec)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
