### ISSUE TITLE
[CoE Starter Kit - BUG] Comments doesn't work when enabled along with Related videos

### ISSUE THREAD

**Issue by PPMini** [microsoft/coe-starter-kit#8626]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team, 

Comments on the Nurture - Maker app doesn't work when we have related videos environment variable as 'Yes' . The screen messes up and does not allow maker to enter the comments.

<img width="1127" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/112712553/dc6ae2d5-3bcf-4df7-9fd1-036866f17c19">
 

### Expected Behavior

The screen should not mess up and allow maker to enter comments  

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Nurture - Maker App

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. While setup configure both comments and Related Video environment variable as 'Yes'
2. Add the videos via Nurture - Admin app
3. Access the videos via Nurture Maker app 
4. The related videos and comments screen is messed up and does not allow to enter comments

**Comment by Jenefer-Monroe** [comment]
I do repro this. Investigating for August release.

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8b1ed877-c879-4641-8a49-6064093bad81)

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.
