### ISSUE TITLE
Fix reference to "preview" in command center support page

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#8627]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I did an upgrade to CenterofExcellenceCoreComponents_4_33_5_managed, now I got this error, big problem. can't access anything.

![image](https://github.com/microsoft/coe-starter-kit/assets/133137665/5f570f37-5c94-4f24-aa2d-427adc779cc6)

![image](https://github.com/microsoft/coe-starter-kit/assets/133137665/9289e984-66c1-4248-8efd-546bab6b5672)

how can I revert this to 4.31 for now. 

HELP!

### Expected Behavior

HELP

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33.5

### What app or flow are you having the issue with?

Upgrade

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Upgrade to 4.33.5

### Anything else?

n/a

**Comment by RyanCloud8888** [comment]
I re-added the security group from environment management and can get back to it now.  I can see the import successfully.  

![image](https://github.com/microsoft/coe-starter-kit/assets/133137665/589221aa-a371-4ed9-a0bc-ab365ec7506d)

but when I went to CoE Suppor to verify, I got a blank screen.

all the updates, this is the first time it has happened. any idea?

**Comment by Jenefer-Monroe** [comment]
Actually I only fixed that issue for the Bookmark page so I'll need to fix for the support page too. 
Thanks for posting!

**Comment by Jenefer-Monroe** [comment]
![Image](https://github.com/user-attachments/assets/cad3192e-f427-49bc-adf2-2bc8232c3ccf)

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
