### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power BI Report | Flows using plain text passwords

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#8629]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello @Jenefer-Monroe,

Hope all is well. I asked this question on the office hours, so you asked me to post here. My question is:

In the Power BI report "PowerPlatformGovernance_CoEDashboard_June2024" on the page "Compliance and Governance" which has a tile of "Flows using plain text passwords".

Can you please explain the following: 

1. What does this mean when they are using plain text passwords? Where is this information stored in the Flow? E.g. is the password added to a "note" a description etc?
2. How does the CoE know this is the case? What Flow is discovering this information.

Thanks very much,

Garry

### What solution are you experiencing the issue with?

Governance

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard_June2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. This is found in the following flow: **_Admin | Sync Template v3 (Flow Action Details)_**
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e96bee1c-1b17-4187-9242-074d39ef70bd)

We look for it when the flow has an HTTP type connection as that is where these passwords are located. 
We basically just look for string "password" in the action definitions as that is how the property shows up:
@{split(string(body('Parse_Flow_Definition')?['actions']), '"password"')}

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/14d16831-a383-4cba-9c1b-3acda51d534a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by GarryPope** [comment]
@Jenefer-Monroe sorry for the delay in replying. This information was really useful. Like always, thanks for your help!

**Comment by izabellore** [comment]
@Jenefer-Monroe, please let me know if this is creating any risks for the Flows? Or you are just searching for the string "password" and the report is generating all the flows that are using the string you mentioned above? Many thanks for your answer!
