### ISSUE TITLE
[CoE Starter Kit - QUESTION] Changing Service Accounts for the Kit

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#8632]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello PowerCat team,

I looked around and found similar questions on this topic but not exactly the answer I was looking for. We currently have the CoE running under a service account and want to switch it to a new service account dedicated to the CoE only. Apart from the normal requirements, what is the recommended process to change ownership of all the objects in the kit? My understanding is that only doing an upgrade won't cut it. 
Also, do you know if having a password rotation will cause any issues with the kit? I'm thinking no since everything is OAuth as far as I know.

Thanks in advance much for your help!

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, upgrading as the new service account should do what is needed. I'm not sure what others are seeing that is missing there. 

Regarding password reset. I'm not sure as I've not tested that. I think this would surface as broken connections and you would get sync flow errors at which point you can repair the connections. 

Hope that helps.

**Comment by santiareh** [comment]
Thanks for the reply, Jenefer. From what I've seen upgrading with a different account works but the objects maintain the original ownership, the connections do seem to change though.

**Comment by santiareh** [comment]
I'll give it a try that way then. Thank you Jenefer!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
