### ISSUE TITLE
[CoE Starter Kit - BUG] Core Component Uninstall failed due to dependencies

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#8635]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are currently upgrading our Core Component Solution from 4.29 (March) to 4.33 (July).
Unfortunately, we encountered the following error when uninstalling the 4.29 Solution.

![image](https://github.com/microsoft/coe-starter-kit/assets/119695189/51a0efee-053f-4013-b3d1-1c6db85011d9)
![image](https://github.com/microsoft/coe-starter-kit/assets/119695189/3f43a827-28bb-4877-a730-f0915ff76a0c)

### Expected Behavior

Core Component Solution (4.29) Uninstall is sucessful.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

admin_dataversetables

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Upgrade CoE Starter Kit - Core Component.

**Comment by Jenefer-Monroe** [comment]
Hello, yes that is a CoE table that was never used by the kit and so we removed it. It looks like you have made a local dependency on it and so you will need to remove that dependency. 

You can go find the dependencies as shown here: 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/16c148dc-8dca-4afb-a6cc-d6022af053ad)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/0545c7b8-43db-412a-ab7f-9f39adf46a3e)

And you'll need to go update that object to not rely on the table. 
Once complete you can delete the failed install. You'll see a second version of core with _Upgrade, delete that. 
And try again.

**Comment by Jenefer-Monroe** [comment]
If you are able to delete the table then yes go ahead and do that. We've deleted it. 
It appears that the dependency is on some Azure feature that I've not heard of before

https://learn.microsoft.com/power-apps/developer/data-platform/reference/entities/entityanalyticsconfig
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f30c56ec-78e9-4fef-bea8-394e8d19b5ff)
