### ISSUE TITLE
[CoE Starter Kit - QUESTION] Power Platform Admin View shows incorrect Total Shared for one canvas app

### ISSUE THREAD

**Issue by MatthewEWells** [microsoft/coe-starter-kit#8636]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

In our CoE Power Platform Admin View app for **just one** of our canvas apps it shows a zero "Total Shared"  even though the numbers above appear correct. I hit the [Recalculate] button but it doesn't resolve the problem. What can I do to try and resolve this please?
![CoE Screenshot](https://github.com/microsoft/coe-starter-kit/assets/13522769/afa53b99-ee27-4f3a-9910-a6f989c6d6e2)

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. This is a deprecated field and we did not remove it straight away from the form accidently. 
I'm not sure what  build you are on but here is the June release and you can see where you should be looking instead
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f278a256-d164-4f7f-a52c-2c28ec1ac28e)

And then here is the July release where we have completed the work in this space and here is how we now like to display this information and have removed this deprecated field
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7d039882-d268-47d0-8434-54c65baf0443)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
