### ISSUE TITLE
[CoE Starter Kit - Suggestion] New Updates

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#8637]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello everyone how are you?

I wanted to leave a comment,

What do you think about increasing the time between one update and another?

I believe this practice would give us, Kit consumers, more time to check what is not working correctly (or not) and the team, time to correct and make the tool more reliable (not that it isn't, it is!). And of course you wouldn't be pressured to deliver.

As an example of correcting the dashboard regarding the published Apps card, I confess that I didn't realize it, but for an internal presentation to the board, we would be seen badly (as a tool).

I hope you understand this constructive criticism.

Abraço a todo o time, estão fazendo um trabalho incrível!

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Thank you for the suggestion. We have considered longer cycles and shorter. We've landed on monthly as the correct cycle for our support costs at this time but likely this will become less frequent as the product team takes over parts of the kit into native product behavior.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
