### ISSUE TITLE
[CoE Starter Kit - BUG] "App Plan Classification" column not updated correctly by the flow "SYNC HELPER - Apps"

### ISSUE THREAD

**Issue by waelyh** [microsoft/coe-starter-kit#8638]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

**We have a canvas application witch is classified as "Standard" (doesn't use premium connectors) as it's shown the picture bellow.**

![AppPlanClassification_Bug_DetailsView](https://github.com/user-attachments/assets/af3a24bc-97b7-4987-838f-33f628f5b333)

**The same app is shown in the "Power Platform Admin View" app as a "Premium"**

![AppPlanClassification_Bug_AdminView](https://github.com/user-attachments/assets/0479d2d6-4c35-4537-995c-60cbb9a98706)

**After investigations, we found that the issue is coming from the flow "SYNC HELPER - Apps" witch is not updating the column "App Plan Classification" in the table "PowerApps App" correctly.**

### Expected Behavior

The app should be marked as "Standard" in the "Power Platform Admin View" app

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, we do get this straight from the product. 
![image](https://github.com/user-attachments/assets/719fa4d2-3688-484e-881c-dac275b11473)

Please call SYNC HELPER - Apps with the apps evnt and app id and see if it repairs. 
See what is returned from the product here:
![image](https://github.com/user-attachments/assets/d0044dff-42e3-471e-be72-237a5b754462)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
