### ISSUE TITLE
[CoE Starter Kit - BUG] Issue with 'App Last Launched On' being blank in the PowerApps App table in the June 2024 version.

### ISSUE THREAD

**Issue by Kebo-ard** [microsoft/coe-starter-kit#8639]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the June 2024 version of the CoE Starter Kit, the 'App Last Launched On' field in the PowerApps App table is blank. Despite following the setup steps outlined in the [Microsoft Learn guide](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http), the issue persists.

### Expected Behavior

**Expected Behavior:**
The 'App Last Launched On' field should display the last launch date of the app.

**Actual Behavior:**
The 'App Last Launched On' field is blank.

**Additional Context:**

- The setup of the custom connector was not performed, as it is already part of the deprecated guide in Microsoft Learn.
- There is no 'Office 365 Management API' custom connector listed in the environment.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Follow the steps in [this guide](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http) to set up the audit log.
2. Ensure that the 'Admin | Audit Logs | Sync Audit Logs (V2)' flow runs successfully.
3. Launched some apps. 
4. Check the 'App Last Launched On' field in the PowerApps App table.

AB#3790

**Comment by Jenefer-Monroe** [comment]
Hello, do you have these two flows turned on? Are they running and passing? 
![image](https://github.com/user-attachments/assets/40f1b084-a0e3-40eb-94c1-1b4d772c5e89)

**Comment by Kebo-ard** [comment]
Hello,

Yes, the flow 'Admin | Audit Logs | Sync Audit Logs (V2)' is turned on and running as per the guide in Microsoft Learn.

However, 'Admin | Audit Logs | Update Data (V2)' was not initially turned on since there wasn't a step indicating to do so. I have now turned it on, as shown in the attached screenshot. I attempted to trigger it by launching a Model-driven App and a Canvas App, but it did not activate.
![Screenshot 2024-07-13 120133](https://github.com/user-attachments/assets/435aec93-c66c-462c-98d2-8f1e433aebe0)


Is there any additional step required to ensure this flow triggers correctly?

Thank you.

**Comment by Kebo-ard** [comment]
Hello,

I wanted to follow up on the previous issue regarding the 'Admin | Audit Logs | Update Data (V2)' flow not triggering. After further monitoring, I found that the flow is now running successfully. It appears there was just a delay in triggering after I turned it on.

The 'App Last Launched On' field now contains data in the 'PowerApps App' table. However, it's worth noting that only the 'Canvas' App Type has the 'App Last Launched On' field populated.

For your reference, please see the attached screenshots.

![Screenshot 2024-07-13 122752](https://github.com/user-attachments/assets/b911d76d-c318-4002-ac5c-7d6d3dae3e5a)

![Screenshot 2024-07-13 122910](https://github.com/user-attachments/assets/05829c8b-bb7c-4b54-b7d0-dc393b9a86e7)

![Screenshot 2024-07-13 123131](https://github.com/user-attachments/assets/d9a7efeb-dec9-42d5-aa11-d2b701cce295)

Additionally, could you please confirm if manually turning on the 'Admin | Audit Logs | Update Data (V2)' flow should be included as a step in setting up the Audit Logs for the CoE Starter Kit?

On a different note, I wanted to check if the status regarding the 'Flow Last Run On' issue raised here (https://github.com/microsoft/coe-starter-kit/issues/8276) is still the same, that it is not yet available.

Thank you for your patience.

**Comment by Jenefer-Monroe** [comment]
Happy to help. 

Yes it should be in the documentation. We do have it fixed locally but have had some issues getting our updates published. Hopefully we will have that published this week. 

Unfortunately, Flow Last Run on is not filled at this time by the kit.

**Comment by Kebo-ard** [comment]
Thank you for your assistance. I was able to resolve the issue with your help.

**Comment by Jenefer-Monroe** [comment]
You are so welcome. I'll go ahead and close then but please feel free to open new issues as they arise.
