### ISSUE TITLE
[CoE Starter Kit - Need Help] What happens if we keep environment variable value "Auto Delete On Archive" == No?

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#864]
### Describe the issue

What happens if we keep environment variable value "Auto Delete On Archive" == No?

For example, if user approve to delete an app, however "Auto Delete On Archive" == No, it will not delete an app. In that case, will user receive the "Approval Email" again, even if it's approved by user and not deleted from the environment?

Can you please help clarifying the consequences if  "Auto Delete On Archive" == No ?

Kindly help!

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Apps) > Admin | Archive and Clean Up v2 (Start Approval for Flows) > Admin | Archive and Clean Up v2 (Check Approval) >  Admin | Archive and Clean Up v2 (Clean Up and Delete)

**Comment by JeneferM-MSFT** [comment]
Please see our documentation and let us know what you think it does. [update environment variables](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components#update-environment-variables) as we believe we have this documented and need to know if you are still confused after reading or just did not see the documentation.

**Comment by DiptiC-InsightRun** [comment]
Hey Jenefer,

Thanks for the response, yes, I have seen the documentation earlier before raising this query. My current understanding is as follows:

1. If "Auto Delete On Archive" == "Yes", then it will remove the apps/flows from the environment on user approval.
2. If "Auto Delete On Archive" == "No", then it will not remove the apps/flows from the environment even if user approve to archive app/flow. However, I require clarification, if this is true, and if that's the case, then will Audit flow send the "Approval Email" again as app/flow still exist but approved to archive by user?

Did I understand correctly?

Thank you for your time!

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Correct. the user can say approve, and then it will not actually be deleted. And it will still be a regular app (or flow) and be subject still to the same flows. 
It is for debugging purposes to ensure you are satisfied with the functionality before turning on.

**Comment by JeneferM-MSFT** [comment]
thank for using CoE
