### ISSUE TITLE
[CoE Starter Kit - BUG] "SYNC HELPER - Cloud Flows" is Failing - There's a problem with the flow's trigger

### ISSUE THREAD

**Issue by venkata-vijay** [microsoft/coe-starter-kit#8640]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The flow started failing suddenly with the error "There's a problem with the flow's trigger"

![image](https://github.com/user-attachments/assets/f1c12900-a8f4-4284-85c2-1a713f08270b)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
It looks like you've hit some kind of product issue here. I'm not sure what to say. 
- Did you try to turn it off and back on? 
- What version of core are you on?

**Comment by venkata-vijay** [comment]
Hello Jenefer,
Thank you for looking into the issue.
We have identified an unmanaged layer on one of the child flow, as the cause of the issue.

We are working on to delete the unmanaged layer and will keep you updated on the same.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
