### ISSUE TITLE
[CoE Starter Kit - BUG] Dashboard failed to refresh 'admin_totalshared' table wasn't found

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#8643]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I'm not too fond of the new July dashboard, which is missing many tabs I use.

Still using the May update dashboard and after the update to 4.33.5

**Error:**
The dashboard has failed to refresh.

Failure details: The last refresh attempt failed because of an internal service error. This is usually a transient issue. If you try again later and still see this message, contact support.

<ccon>Expression.Error: The column 'admin_totalshared' of the table wasn't found.. admin_totalshared. </ccon>. The exception was raised by the IDbCommand interface. Table: Power Apps.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33.5

### What app or flow are you having the issue with?

CoE dashboard/Power Bi Refresh

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Yes that field was removed we now use the field below to represent total shared users. So if you want to stick with an old dashboard you'll need to swap that out in the transform and the dashboard.
![image](https://github.com/user-attachments/assets/9eb10c66-1705-4e17-b75c-a94be907bce8)

**Comment by RyanCloud8888** [comment]
- Thanks Jenefer.  I want to use the new dashboard but there are so many tabs that got removed.  How can I update that on the PowerBi dashboard? if you have a screenshot, That would be helpful.

**Comment by RyanCloud8888** [comment]
That helps.  Thanks Jenefer as always.
