### ISSUE TITLE
No environments or Flows after May 13, 2024 showing up in the Environment or Flow table in Dataverse

### ISSUE THREAD

**Issue by dcurt1977** [microsoft/coe-starter-kit#8645]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

About a month ago the latest version 4.31 was deployed to a production environment. Noticed today that environments and flows created after May 13, 2024 not showing up in the Power Platform Admin View Model Driven App.

### Expected Behavior

When new environments and flows get created in our tenant, new objects show up in the Power Platform Admin View Model Driven App.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. New environment or flow created in tenant
2. Check environment and flow table

**Comment by Jenefer-Monroe** [comment]
Hello likely you have been impacted by new product behavior that shipped recently around the way the product treats privileged roles (ex Power Platform Admin role, Global Admin role)

While there is a workaround we can put into the kit to fix this directly, we cannot ship it with the kit until the workaround is available in all regions. Hopefully for the July release.

### The product change
Here is information about the product feature: [Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)

### How to check if this is the case
1. Validate the user running the flow has direct and permanent assignment to the Power Platform Admin role.
2. Take one of the target environments in your repro, one of the environments which is failing, and make sure the user running the flow has System Admin security role in that target environment.

### How to address and More information
Please see https://github.com/microsoft/coe-starter-kit/issues/8119 for a write up on this change. 
Included also is a workaround you can do until we can have it natively in the kit.

**Comment by dcurt1977** [comment]
System user running the flow has direct and permanent assignment to the Power Platform Admin role. However, user was not assigned System Admin in the target environment, so checking all environments created after May 13, 2024.

**Comment by dcurt1977** [comment]
Are there any flows that I should be checking if turned on.

**Comment by Jenefer-Monroe** [comment]
Here is how to fix this in the near term until we can ship natively with the kit (hopefully in August)

### How to address and More information
Please see https://github.com/microsoft/coe-starter-kit/issues/8119 for a write up on this change. 
Included also is a workaround you can do until we can have it natively in the kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by dcurt1977** [comment]
After stepping through the CoE Setup and Upgrade Wizard, the **Admin | Sync Template v4 (Apps)** and **Admin | Sync Template v4 (Flows)** that previously failed now passed and the environments and flows are now up to date in the Power Platform Admin View Model-driven App.
