### ISSUE TITLE
Deployment settings in ALM 

### ISSUE THREAD

**Issue by iamaninda93** [microsoft/coe-starter-kit#8650]
### What is your question?

I can see there are different approval types. Can you please tell what is suggested approach?

![Screenshot 2024-07-15 180916](https://github.com/user-attachments/assets/17603529-5ee9-437b-ab6f-ee3004f295fc)

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

Accelerator Version: 1.0.20240305.1(Managed)

**Comment by MaheshSripada** [comment]
@iamaninda93 
Please go through below link for more info:

https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/advanced-maker-experience#deploy-the-solution
