### ISSUE TITLE
[CoE Starter Kit - Feature]: Install Documentation Improvement

### ISSUE THREAD

**Issue by samhms** [microsoft/coe-starter-kit#8652]
### Is your feature request related to a problem? Please describe.

In the setup documentation, some connector could be clarified.
When configuring the **HTTP with Azure AD**, it does not say if it should be the **regular one or the preauthorized.**
When configuring the **Power Platform for Admin**, it does not say if it should be the **regular or the V2**.

**Source**
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections

### Describe the solution you'd like

Explaining which connector to pick would clarify these steps and empower multiple people to install the CoE more confidently.

**Comment by Jenefer-Monroe** [comment]
Hello. Thank you yes this is known. We have fixed this documentation issue locally but unfortunately it is stuck in review as it was a very large change.
