### ISSUE TITLE
[CoE Starter Kit - BUG] Solution Failed to uninstall

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#8653]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi, I could not find if there was a post for this issue, I have upgraded to 4.33 and the uninstall has failed with error code 8004F01D
![image](https://github.com/user-attachments/assets/3170aa21-7f8d-4ee3-95bb-5bfa2774ac22)

I have the following error message showing in the solution - 

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: Entity, ObjectName: DEPRECATED: COE Settings, Id: fc926eb2-0244-4271-a093-bec9aecb9e4e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: CanvasApp, ObjectName: admin_traininginadaymanagement_3a72b, Id: 5fa74fba-8d8e-4a15-aa0d-4f45caf69b33, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Install

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3793

**Comment by Jenefer-Monroe** [comment]
Looks like you are using a very old version of Nurture as we deprecated this CoE Settings table about 2 years ago. 

You will need to upgrade Nurture (and maybe Gov) or remove it if you arent actively using it in order to remove the dependency on this table as it no longer exists in Core.

**Comment by Alyson95170** [comment]
Thanks Jenefer, should I upgrade the Nurture then delete the previous version of the Core Components?

**Comment by Jenefer-Monroe** [comment]
Yes upgrade nurture. Then delete the _Upgrade of Core and try upgrade again.

**Comment by bhavikj65** [comment]
@Jenefer-Monroe I upgrade to July 2024 release, I don't see any errors but there is no Uninstall operation listed in Solutions history nor in the CoE Setup & Upgrade app, see below screenshots:

![image](https://github.com/user-attachments/assets/daecb590-f8fd-4e0c-bc80-313dcd0b5589)
![image](https://github.com/user-attachments/assets/a5289415-6c6a-437b-9131-004d1d4de270)

There are no old solutions as well:
![image](https://github.com/user-attachments/assets/1a04a64f-3df8-40c1-9213-5a74b335d27b)

**Comment by Jenefer-Monroe** [comment]
Yes I've noticed that lately, that sometimes the product does not list the uninstalls anymore. I think they may be changing the way they show this in the UX. 
So as long as you dont see the two solutions, one with the _Upgrade, then you have succeeded. YEAH

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Alyson95170** [comment]
Hi Jenefer, is it ok to comment here or would you like another issue opened?
I have installed Core Components version 4.37, this has been successful but the pervious version 4.33 has not been uninstalled.
The nurture components has been upgraded, I have the governance solution, Pim Workaround Solution and the Business Value solution.
I have tried to reinstall 4.37 and the previous version is still showing, is it ok to manually delete this?

What is causing this to happen?

Thanks Alyson
