### ISSUE TITLE
[CoE Starter Kit - BUG] Inactive resources not deleted

### ISSUE THREAD

**Issue by L0k33** [microsoft/coe-starter-kit#8655]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The resources have been approved for deletion and I keep getting following message:

Flow Environment: Personal Productivity
Flow: [CapacityModel-Manager]
Approved on: 21 May 2024
Estimated date of deletion: 11 Jun 2024

How do I establish if there is an issue, as I cant see anything wrong. I wonder if there is an issue with a child flow, which I have missed. 

![image](https://github.com/user-attachments/assets/004682aa-58da-432a-ab38-9669be886d3e)

### Expected Behavior

I expect the flow / apps to be deleted once approved for deletion by the resource owner.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.16

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Clean Up and Delete)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3794

**Comment by Jenefer-Monroe** [comment]
What value do you have for this environment variable? 
![image](https://github.com/user-attachments/assets/8f8dd89f-1041-466d-8908-39a95d4b7ca4)

**Comment by L0k33** [comment]
![image](https://github.com/user-attachments/assets/1a4e3904-b334-4eba-b5c9-8b5ba3ad9811)

I assume that Value is supposed to be set to "Yes"

**Comment by Jenefer-Monroe** [comment]
Yes it is. You can update it as shown below and then please restart that flow
![image](https://github.com/user-attachments/assets/ca7035e0-c2d5-48a5-8928-1a81461b2409)

**Comment by L0k33** [comment]
Hi, I changed the value and noticed that the admin_AutoDeleteOnArchive has been depreciated.

![image](https://github.com/user-attachments/assets/a56b415f-c663-4444-ba6b-6eee9adecbc0)
 
I then re ran the Admin | Inactivity notifications v2 (Clean Up and Delete), but it not pick up the new value.

![image](https://github.com/user-attachments/assets/8b324b1d-d70a-4cd0-9281-e391de353014)

**Comment by Jenefer-Monroe** [comment]
yes sometimes flow cache env vars. If you restart the flow it will pick it up.

**Comment by L0k33** [comment]
I turned off the flow and back on again and ran it with the same result. Any ideas?

**Comment by Jenefer-Monroe** [comment]
From your screenshot it seems like your change did not save. Can you please see what value you have? 
![image](https://github.com/user-attachments/assets/b48130fe-9019-44b0-a085-000bfa152112)

**Comment by L0k33** [comment]
I had to go to Solutions / Default Solution to change the variable, it then worked. Thank you for your help as always. :)

**Comment by Jenefer-Monroe** [comment]
wonderful news!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
