### ISSUE TITLE
[CoE Starter Kit - QUESTION] About where archive scores are stored

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#8656]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Which table and column name contains the archive score information?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2024/1

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3789

**Comment by Jenefer-Monroe** [comment]
Hello. We do not store archive scores in the kit. We generate our archive concepts when we use them but do not store them anywhere.

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
Is it not stored in a table, just displayed within Power BI?

**Comment by Jenefer-Monroe** [comment]
That's correct. Its derived and displayed in PBI
