### ISSUE TITLE
[CoE Starter Kit - BUG] Orphaned Objects: Manager did not respond - Blank emails. No Apps or Flows

### ISSUE THREAD

**Issue by tkudya** [microsoft/coe-starter-kit#8657]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have receiving these emails
Orphaned Objects: Manager did not respond but all of them are blank, 

No Apps or flows are showing, this is happening to several managers, they are also blank on their end. 
This include a manager that doesn't exist
![image](https://github.com/user-attachments/assets/9fa32eed-3c07-4b95-9d15-005c1911003a)

### Expected Behavior

I would expect to see the flows and Apps or the flow stops running completely

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

Data Export

AB#3791

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. Putting on the backlog for investigation.
