### ISSUE TITLE
[CoE Starter Kit - BUG] Nurture Component fails to import

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#866]
### Describe the issue

I am unable to import the latest Nurture Components solution version 1.60.20210708.1

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

1.60.20210708.1

### What app or flow are you having the issue with?

The whole solution

### Steps To Reproduce

I am failing to import the latest Nurture Components solution version 1.60.20210708.1
The status is failure and the message is "A task was cancelled"
I even tried deleting the old solution but it still failed to import. Had to re-install version 1.51

I have successfully updated all of the other solutions from the latest release.

**Comment by medicineshow** [comment]
is there any update on this?

**Comment by JeneferM-MSFT** [comment]
This sounds like a service issue. You will need to try again and if you still fail you will need to share more details on your error message. Nurture has not had install issues this month for others.

**Comment by medicineshow** [comment]
I was able to resolve it by selecting Update rather than Upgrade
