### ISSUE TITLE
[CoE Starter Kit - QUESTION] Setup Wizard and GCCH

### ISSUE THREAD

**Issue by yearwoodm15** [microsoft/coe-starter-kit#8660]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I am having trouble getting the SetupWizard to work in GCCH. Due to issues with my previous CoE, I am starting new within a new PPE. I would like to leverage the SetupWizard, but am getting errors. Is this is a limitation within GCCH? I have made sure my endpoints are https://graph.microsoft.us/ within the environment variables, and altered the flow a bit on SetupWizard>GetUserDetails to reflect .us. Is there something I may be missing if this is allowed in GCCH?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33 Core Components

### What app or flow are you having the issue with?

SetupWizard>GetUserDetails

### What method are you using to get inventory and telemetry?

None

AB#3802

**Comment by Jenefer-Monroe** [comment]
To my knowledge the setup wizard works for GCCH and should work without altering any flows. 
Can you please share the specific issue you are seeing?

**Comment by Jenefer-Monroe** [comment]
repros as admin too.

**Comment by Jenefer-Monroe** [comment]
Yes you'll want to ensure the env var has the ending slash. (my pictures shows commercial)
![image](https://github.com/user-attachments/assets/cdff7938-b022-456c-9475-60c71ac96b6f)

**Comment by yearwoodm15** [comment]
Hey Jenefer, that worked - thank you!!
