### ISSUE TITLE
[CoE Starter Kit - BUG] - Can not change the Ownership of Model-driven app using CoE toolkit ? 

### ISSUE THREAD

**Issue by Ravindra-He** [microsoft/coe-starter-kit#8662]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Tried to change the ownership of the Model-driven app through apps available in CoE toolkit. No options to change the ownership. "Set App Permissions" seems now deprecated(new version "Manage Permissions") and does not listed down any Model-driven apps from the inventory but display all the canvas apps only. We can change the ownership of any Canvas app but not Model-driven app. I have seen a command available in "Power Platform Admin View" app to Manage Access but I can not access that. Could it be the one we can use to change the ownership of a Model-driven App ?

Thanks

### Expected Behavior

Should be able to change ownership of a Model-Driven app

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Manage Permissions, and Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Tried to change the ownership of the Model-driven app through apps available in CoE toolkit. No options to change the ownership. "Set App Permissions" seems now deprecated(new version "Manage Permissions") and does not listed down any Model-driven apps from the inventory but display all the canvas apps only. We can change the ownership of any Canvas app but not Model-driven app. I have seen a command available in "Power Platform Admin View" app to Manage Access but I can not access that. Could it be the one we can use to change the ownership of a Model-driven App ?

AB#3817

**Comment by Jenefer-Monroe** [comment]
Hello, you are correct, ownership of Model Driven Apps is not something that is exposed to us programmatically and so the kit does not support doing that. Only canvas type apps can have their ownership changed.
