### ISSUE TITLE
New version of Maker -Environment Request [deprecated]

### ISSUE THREAD

**Issue by bobii123** [microsoft/coe-starter-kit#8663]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, 

I am working on the automation creation of environments. I discover that the Admin - Environment Request has been deprecated but replaced with CoE Admin Environment Request. 
What about Maker -Environment Request [deprecated] ? 

Do wa have a new application to replace it ? 

Best regards,

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

AB#3818

**Comment by Jenefer-Monroe** [comment]
Hello, the Maker pov has been moved to the CoE Maker Command Center. 

Note that there is a bug currently local fixed for August release: https://github.com/microsoft/coe-starter-kit/issues/8644

![image](https://github.com/user-attachments/assets/0843ab64-4d99-49b7-aa50-d7a621af7a00)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
