### ISSUE TITLE
[ALM Accelerator - QUESTION] Solution is not fully overwritten after import

### ISSUE THREAD

**Issue by tt-dawid-zawadzki** [microsoft/coe-starter-kit#8665]
### What is your question?

Hi, 

I have a question regarding import behaviour of ALM Accelerator.
Lets say there are developer environments A and B containing same version of the unmanaged solution. 
When I remove the **custom connector**, **environment variable** or **table column** from the environment A, merge changes to the repository and import the latest version with ALM Accelerator to the environment B, the components are not removed from the environment B after the import. 

Is this an expected behaviour or could it be configured somehow?
Is the only solution to this problem to remove those components manually from both environments?

I would be glad for any feedback. Thanks! 

### What component are you experiencing the issue with?

ALM Accelerator Custom Conenctor

### What solution version are you using?

1.0.20240104.1

AB#3821

**Comment by MaheshSripada** [comment]
If you import the solution as Unmanaged solution, the components do not get deleted. You have to import it as Managed solution using deploy option choosing the updated repository / profile or you have manually delete the components.

cc - @RajeevPentyala

**Comment by tt-dawid-zawadzki** [comment]
Thank you for the response. I'm closing the issue.
