### ISSUE TITLE
PowerApps is not displaying when click on Drill Through from Apps

### ISSUE THREAD

**Issue by stalinprotiviti** [microsoft/coe-starter-kit#8666]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the Power Platform COE Starter Kit Power BI report, open the COE Dashboard and select "Apps" from the left navigation. This will display the report for Power Apps. In the bottom-left list, click on the app and then select "Drill through" > "App Detail". Getting the error message saying "Sorry, We didn't find that app" 
![App Error 1](https://github.com/user-attachments/assets/bf39a7d1-e582-471f-8e93-4224bf4163f2)
![App Error 2](https://github.com/user-attachments/assets/3c0304cc-c95e-4675-ad03-8476248b93da)

### Expected Behavior

App should display with other details.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Any App

### What method are you using to get inventory and telemetry?

None

AB#3822

**Comment by Jenefer-Monroe** [comment]
It looks like you have not done the setup steps for the emedded apps. 
Please see [Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard)

It looks like you are on an older version of the kit/dashboard so the instructions may refer to different pages than you have but once you find the correct page you will be able to follow the steps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
