### ISSUE TITLE
[CoE Starter Kit - QUESTION]How do you manage flows created in the default environment to prevent them from becoming workflows used as PROD ?

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#8675]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have an issue with Power Platform governance. I just realized that some flows that are created in the default environment are used as prod. Is there a compliance process used for apps but for Flows?

And it would be nice to have a link that shows how many times the flow is running over a time interval. 

![image](https://github.com/user-attachments/assets/f7b3c045-073f-4311-9b3b-a308738a86ae)

That would be a useful indicator. Example: If the flow has been run more than 50 times in a week, there is a high chance that the flow will be used as production.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What method are you using to get inventory and telemetry?

None

AB#3849

**Comment by Jenefer-Monroe** [comment]
Hello we do not have a compliance process for flows and do not yet have access to flow run information. 
These are good suggestions so I can place on the backlog but unfortunately we will not be able to fund them soon due to competing priorities.

**Comment by lukas-nC** [comment]
You can get information about flowruns now from dataverse.
If it is enabeled in the environment settings

https://learn.microsoft.com/en-us/power-automate/dataverse/cloud-flow-run-metadata

**Comment by tocri** [comment]
Thank you guys. I saw you use this table on some flows to handle error. i thought  i never think to use it for monitoring execution flows.
I will give it some try
