### ISSUE TITLE
CoE App/Flow Deep Dive returning the same permissions for ALL Apps and Flows no matter what I do.

### ISSUE THREAD

**Issue by Olena-UMPQ** [microsoft/coe-starter-kit#8676]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

This is the original issue https://github.com/microsoft/coe-starter-kit/issues/8502. I've followed the article and the video and got it showing the permissions, but it shows the same permissions for every app and every flow.
This is what I see when I do right click on the app->Drill through-> Manage App Access
![Permission1](https://github.com/user-attachments/assets/17b84e86-23e3-4501-a568-ca821a5041e5)
Same for Flows no matter what flow I choose
![Permission2](https://github.com/user-attachments/assets/236d460f-8de5-48de-982a-a6bc3c630147)
The account I'm logged in under has correct license and met all requirements.

One more thing: if I add new user to one specific app, I will see that user in for ALL apps.

### Expected Behavior

I should see different owners for different apps and flows.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Service version:13.0.23725.63 Client version:2407.2.20139-train

### What app or flow are you having the issue with?

Every flow/app

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Open Production_CoEDashboard_July2024
2. App Deep Dive
3. Choose any app
4.Right click->Drill through-> Manage App Access

AB#3853

**Comment by Jenefer-Monroe** [comment]
We did not make the video but I see they directly you to recreate the control where you do not need to do that. 
Please reboot the PBIT and try to configure again following the instructions here: 
[Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard)
You'll see that you need only "Reset to default" not recreate
![image](https://github.com/user-attachments/assets/8ccec96a-1a66-4c73-8299-accace993c3f)

**Comment by Olena-UMPQ** [comment]
Thank you for the quick response, Jenefer-Monroe! I understood that PBIT is Power BI file, but I'm not sure how to reboot one thought. Can you please provide any guidance of how to reboot PBIT?

**Comment by Jenefer-Monroe** [comment]
Just return to the PBIT file in the download from the coe starter kit and then follow the instructions at [Set up the Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi)
Basically you just re-enter the parameter

![image](https://github.com/user-attachments/assets/610864dd-b1f3-4c10-bee5-0eb7264bd853)

and then follow the instructions from above to setup the app.

**Comment by Olena-UMPQ** [comment]
Thank you so much for your help! It worked great- I can see correct owners of apps/flows. Appreciate your help!

**Comment by Jenefer-Monroe** [comment]
Thanks great news, thanks so much for sharing it with me!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
