### ISSUE TITLE
CLEANUP - Admin | Sync Template v3 (Flow Shared With) failed

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#8679]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

**CLEANUP - Admin | Sync Template v3 (Flow Shared With)** has failed during our last install.
The error points to its call to the **CLEANUP HELPER - Cloud Flow User Shared With** flow that has indeed failed originally, by not being part of the COE Solution Metadata table. The later flow eventually run successfully, but the parent shows as failed.

Do I need to rerun the **CLEANUP - Admin | Sync Template v3 (Flow Shared With)** to trigger a successful run, or just wait for it to get triggered? What triggers this flow?

Thank you,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Flow Shared With)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3852

**Comment by Jenefer-Monroe** [comment]
You can just wait, if you failed at the "update success / failure" portion at the bottom of the flow, that just means you wont see the flow completion in the Admin Command Center. Now that the record is in the metadata table is will pass next time at this step.

**Comment by VanIsleCA** [comment]
Thanks so much for letting me know, makes sense.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
