### ISSUE TITLE
[CoE Starter Kit - BUG] Apps/Flows deep dive pages are missing decomposition tree visual

### ISSUE THREAD

**Issue by bhavikj65** [microsoft/coe-starter-kit#8680]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the July 2024 release, I have observed that the decomposition tree visual has been removed from Apps & Flows deep dive pages of the CoE Dashboard Power BI report. 

Previous versions:
![image](https://github.com/user-attachments/assets/91122c01-8e43-4a9f-b433-810f4d7f1c8c)

July 2024 version:
![image](https://github.com/user-attachments/assets/9c580a63-da18-4a35-a939-445ffd8a32e4)

It was very useful visual to navigate through different parameters like Environment, Connector Tier, App Type, App Plan Classification etc. 

### Expected Behavior

Would be nice to have that decomposition tree visual in the Apps and Flows deep dive pages of CoE Dashboard Power BI report. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Production_CoEDashboard_July2024.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3854

**Comment by Jenefer-Monroe** [comment]
Hello these visuals were found to not display the correct data due to some data model issues and so we removed them. 
In the future we will likely be shifting away from these enormous single pbi files with complex data models as they do not seem to be able to display the correct data reliably. As a result we just had to simplify the report for now so that the data could be reliable.

**Comment by Jenefer-Monroe** [comment]
> @Jenefer-Monroe - Can you confirm that the new flow share columns are omitted from the dashboards for now? Here are some of my observations. #8713

We can track in that other issue. Will hide the comments here to avoid confusion for OP

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
