### ISSUE TITLE
[ALM Accelerator - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Roelof-BAM** [microsoft/coe-starter-kit#8681]
### What is your question?

Hi, I can not find the managed solution to download on the location as indicated on this  [page](https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/setup-upgrade-configuration#download-the-latest-release)

Could you please tell me where I can find the latest release of this solution.

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

January 2024

AB#3861

**Comment by MaheshSripada** [comment]
Hi @Roelof-BAM,

Latest version of ALM Accelerator is available in below link.
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-March2024
