### ISSUE TITLE
[CoE Starter Kit - BUG] Get_toWhom_profileo issue with the "Assign to all" button in the Request Orphaned Objects Reassigned (Child) flow

### ISSUE THREAD

**Issue by Marius-Bjorni** [microsoft/coe-starter-kit#8683]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We got the following error message when a user pressed the "assign to all" button in the orphaned objects process:
"WorkflowOperationParametersRuntimeMissingValue. The 'inputs.parameters' of workflow operation 'Get_toWhom_profile' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'id'"
![image](https://github.com/user-attachments/assets/68e8dbaf-8870-4624-b618-b66d6414a9ca)

It seems like the issue is that the toWhom is empty:
![image](https://github.com/user-attachments/assets/92fcac64-ca51-4a43-8e9e-13eb2af9cc6d)

But according to issue 8362 https://github.com/microsoft/coe-starter-kit/issues/8362 this problem should've been fixed?

The flow looks like this:
![image](https://github.com/user-attachments/assets/8c160d92-dc96-400e-b1b4-9ee54705fbb3)

Using the june 2024 version of CoE.

### Expected Behavior

No error message

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.24

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, thanks for posting. This issue was posted and fixed for the June 2024 release of the kit. Please see https://github.com/microsoft/coe-starter-kit/issues/8362

**Comment by Jenefer-Monroe** [comment]
oh sorry I got mixed up by the version number you listed. 
When we did the testing for this fix, "No data entered" is what is sent in to _Get toWhom profile_, which sent 404 status code to the switch statement. 
It looks like this product behavior may have changed and due to some competing priorities investigating this will have to go on the backlog.

**Comment by Jenefer-Monroe** [comment]
I think for now that's all I can advise for now, to not do that. I would have to debug to see what expression will work now instead. Hopefully I can do that in the next couple weeks.

**Comment by Jenefer-Monroe** [comment]
I just got around to testing this and it does appear to still work for me. I'm not sure how you are not getting 'No data entered' as I did. 

Can you try this equation? I can't test as I dont repro, but I did validate that I still work with this expression instead.
`@{coalesce(if(equals(length(coalesce(outputs('Send_Table_For_Response')?['body/data/toWhom'], '')), 0), 'No data entered', outputs('Send_Table_For_Response')?['body/data/toWhom']), 'No data entered')}`

Here is what I see


![Image](https://github.com/user-attachments/assets/c34725d2-60ee-4f06-9aa3-e4d02f980046)

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.
