### ISSUE TITLE
Is there any flow in the COE Starter Kit to Extract all the Audit logs related to Power Platform from Purview.

### ISSUE THREAD

**Issue by Chandra1247** [microsoft/coe-starter-kit#8685]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Is there any flow in the COE Starter Kit to Extract all the Audit logs related to Power Platform from Purview.
I am looking logs related to Environment Provisioned, Environment Deletion, Environment Settings change and other logs related to DLP etc

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.33

### What method are you using to get inventory and telemetry?

None

AB#3866

**Comment by Jenefer-Monroe** [comment]
Hello. No we only extract the Power App launch from this source, however you can use the same pattern and extend the kit to track other properties. Hopefully the template is useful.
Do note that there is a new Graph API in the that is better than Purviews as it allows filtering of the action type for much lower flow action hit. So you may want to consider using it instead. We will be taking it as an option in the kit soon as well. Here is some more information. 

### Audit Logs redo #3
Hello 
We do have work coming which will reduce the API count for the flow if you are able to setup the new API registration. We are not able to integrate this into the kit yet, but it is available for early testing if you would like.

Here is our tracking issue to integrate the new work with the kit : https://github.com/microsoft/coe-starter-kit/issues/8482

We do have a sample solution you can use already to test with the new API. 
Here is the new solution: https://github.com/petepuu/coekit-auditlogsync-v3/releases
Here is a write up on how to set it up: https://github.com/petepuu/coekit-auditlogsync-v3

**Comment by Chandra1247** [comment]
Hi @Jenefer-Monroe,

I made a copy of the flow and tried to filter with "@or(equals(item()?['Operation'], 'environmentprovision'), equals(item()?['Operation'], 'environmentdelete'), equals(item()?['Operation'], 'environmentsettingchange'), equals(item()?['Operation'], 'updatedlppolicy'))" but didn't get any related event.

I will try using auditlogsync-v3 flow and see if it fulfills my requirements.

Thank for the quick help.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
