### ISSUE TITLE
Environments not listed

### ISSUE THREAD

**Issue by gghaleb** [microsoft/coe-starter-kit#8686]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am setting up the compliance process.
Setup & Upgrade wizard feature for Compliance, should display the list of all environments to choose what to exempt from Compliance. I am getting an empty page though we have environments, any idea why?

### Expected Behavior

generate the list of envs. created in the tenant

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Setup and Upgrade wizard
More features
Compliance process
Env to exempt from Compliance (empty)

### Anything else?

thanks

AB#3867

**Comment by Jenefer-Monroe** [comment]
Has your initial inventory completed? Do you see the environments listed here in the Power Platform Admin View app? 
![image](https://github.com/user-attachments/assets/56cd7641-6410-4be8-ab76-1de8529c39f3)

**Comment by gghaleb** [comment]
so first when i open the screen here i see no environments:
![image](https://github.com/user-attachments/assets/e46e24ec-ee06-4fb9-8035-c19a64c9e322)
and then when i attempt to search for one, i can find it:
![image](https://github.com/user-attachments/assets/04850c79-60ce-448a-ba71-0bd93a5eb086)

finally, removing the above filter will show all :)

**Comment by Jenefer-Monroe** [comment]
Thank you for testing that. I had forgotten about this bug, yes there was a change in the product and we had to update the formula we used here in order to not start with blank. 
This was fixed for the June release. 
https://github.com/microsoft/coe-starter-kit/issues/8449

Hope thats helpful!

**Comment by gghaleb** [comment]
Thanks Jenefer!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
