### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Admin Center - Warning Messages and No Version Data - Potential Issue Detected

### ISSUE THREAD

**Issue by inquisitive-identity** [microsoft/coe-starter-kit#8689]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team,

First off, I would like to say that I'm loving what you're doing with every new update of the CoE kit! :)
You are all absolute legends!

I just have one question regarding some warning messages I get when I open the CoE Admin Center app. 

![image](https://github.com/user-attachments/assets/4473657d-56f0-4427-9ac6-bd1fca770adf)

From what I've looked into, I believe this is related to that latest post you made on CoE Releases page on GitHub. :)

The CoE Kit is picking up the "Preview builds for testing" post instead of the CoE Kit July 2024, so it's corrupting the data in the code.

![image](https://github.com/user-attachments/assets/c085ad2e-9f3b-4f57-a9b0-1c53f91b810b)

I just figured you should know for the future reference. :)

Best regards and keep up the awesome work,
Stefan

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2024

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3871

**Comment by Jenefer-Monroe** [comment]
Hello this is known and fixed for the August release. 

You can apply the fix locally if you would like as well and then just remove the unmanaged layer on your next upgrade: 

[Bookmark page](https://github.com/microsoft/coe-starter-kit/issues/8611)
[Support page](https://github.com/microsoft/coe-starter-kit/issues/8627)

**Comment by inquisitive-identity** [comment]
Hi Jen,

Ah apologies, I could have sworn I had searched the existing questions/issues already...

Understood, thank you! :)

Best regards,
Stefan

**Comment by Jenefer-Monroe** [comment]
no worries at all. I have trouble keeping track of the list myself :D

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
