### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION How I can restore deleted app/fow in COE toolkit.

### ISSUE THREAD

**Issue by abdulf555** [microsoft/coe-starter-kit#8693]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

How I can restore deleted apps and flows from CoE toolkit by using Cleanup Old Objects App or any other app I deleted app/flow. How I can restore that app/flow any way in CoE tookit to restore? 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

how to restore 

### What method are you using to get inventory and telemetry?

None

AB#3876

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately there is no mechanism in the starter kit to recover deleted apps and flows. To my knowledge you need to use Power Shell to do this. Here are some articles to get you started: 

[Restore Deleted Flows](https://learn.microsoft.com/power-automate/how-tos-restore-deleted-flow)
[Restore Deleted Apps (and Flows)](https://community.dynamics.com/blogs/post/?postid=6cbb3914-1ee1-423d-8ac4-156e97cf58df)

Hope that helps
