### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by AimanNishat** [microsoft/coe-starter-kit#8694]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I am trying to install CentreofExcellenceCoreComponent but my import is getting failed. Attaching Screenshot for reference. Kindly help me on the same.

![image](https://github.com/user-attachments/assets/7ec706b1-e6a5-4e05-8527-1d7f3024a5e4)

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

AB#3885

**Comment by AimanNishat** [comment]
![image](https://github.com/user-attachments/assets/b8bee34c-9424-40e1-864a-6a308cf7588d)
Do I need to fill data in all fields before importing? Is that the cause of failure?

**Comment by Jenefer-Monroe** [comment]
No, you do not need to fill in those variables. And we suggest people do not as the Setup Wizard will walk you through them. 

You'll need to get the error message in order for us to help investigate. 

A few questions
1. Is this a clean install? Meaning do you already have Core in this environment or is this the first time installing into this environment. 
2. What type and region is this environment?

**Comment by AimanNishat** [comment]
[CoEerror.txt](https://github.com/user-attachments/files/16370501/CoEerror.txt)
I have already installed CreatorKitCore.
It is developer environment and region is Europe.

**Comment by Jenefer-Monroe** [comment]
I just tested and upgrade/install is working in Europe. 

I'm not sure what happened to you. Are you sure you selected the Core solution file? Can you share screenshots of the install in progress?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
