### ISSUE TITLE
Dataflow Refresh Doesn't happens automatically for All the Dataflows after July 2024 upgrade to CoE starter kit

### ISSUE THREAD

**Issue by Kumarez007** [microsoft/coe-starter-kit#8695]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

After the July 2024 release Upgrade to our Environment, We see that the Dataflows refresh happen
![Dataflows failure 1](https://github.com/user-attachments/assets/ce7dfa26-93c8-40a1-80f5-c96b38dcb627)
s automatically only for Makers and Environment, rest all doesn't refreshes automatically like before. I don't see any error. Please help to resolve this issue

### What solution are you experiencing the issue with?

None

### What solution version are you using?

July 2024 - 4.33

### What method are you using to get inventory and telemetry?

None

AB#3887

**Comment by Jenefer-Monroe** [comment]
Are these flows still on? 
![image](https://github.com/user-attachments/assets/ab455f7d-2150-4fd2-ae53-9496ed30fe15)

**Comment by Kumarez007** [comment]
Hi Jenefer,

Thanks for the update and I see checked the cloud flows and see that the status of CoE BYODL - When Environment Dataflow is complete -- status as OFF. Should I change the status to ON? PFA Screenshot.
![Dataflow - status OFF](https://github.com/user-attachments/assets/28146545-88d8-4822-ac5f-80cc7f48300a)

**Comment by Kumarez007** [comment]
I have turned it ON and now the refresh happens automatically.. thanks for the support Jenefer
