### ISSUE TITLE
[CoE Starter Kit - BUG] COE Admin Env Request

### ISSUE THREAD

**Issue by minobrega** [microsoft/coe-starter-kit#8696]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello Jenefer,

Please, we are having a problem after updating CoE to version 4.33, the Environment Request, SET APP PERMISSIONS and SET FLOW PERMISSIONS apps are no longer appearing. Can you tell me if the name changed or how do I open these apps?

![Erro CoE ATUAL](https://github.com/user-attachments/assets/bc18ca84-9edf-4e6c-8f6f-a1decf99e8c7)

![Erro CoE ATUAL 1](https://github.com/user-attachments/assets/137c8205-c6d3-4659-8457-40ba58207097)

![Erro CoE ATUAL 2](https://github.com/user-attachments/assets/0de7ae8e-817b-4efc-ab11-014a6ef2cdb3)

![Versão atual do CoE o](https://github.com/user-attachments/assets/c0f1c7d6-5d77-4207-b94a-7f359440d4a6)

### Expected Behavior

The application was supposed to appear after the update

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Maker - Environment Request

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3888

**Comment by Jenefer-Monroe** [comment]
Hello, yes those apps were deprecated in favor of the Manage Permissions app. Please go check it out! 
![image](https://github.com/user-attachments/assets/1bee89b1-65ed-46cc-b379-991749ec2a48)

Thank you

**Comment by minobrega** [comment]
I found the other app Manage Permissions Jenefer. Regarding the environment request, I found information in another ticket that is now in the CoE Maker command center. 

Thanks a lot for the help!!

![Manage permission](https://github.com/user-attachments/assets/b4549d15-c682-4385-8347-28d78e4a3377)

![CoE Command Center](https://github.com/user-attachments/assets/bc583e0b-faf7-4222-9f40-9e3420f2ec1e)
