### ISSUE TITLE
[CoE Starter Kit - BUG] Wrong email sent to managers from Orphaned Objects "Email Me" option

### ISSUE THREAD

**Issue by MMuck-AW** [microsoft/coe-starter-kit#8697]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When a manager responds to the orphaned objects cleanup Teams message with the option "Email Me", they receive the Customized Email with `admin_name` = "**Request Orphaned Objects Reassigned (Parent) -- **Send admin email of orphans they will need to resolve** -- en-US**".

This email is written for CoE admins, so it is confusing for managers to receive.

### Expected Behavior

I would assume managers are supposed to receive the Customized Email with `admin_name` = "**Request Orphaned Objects Reassigned (Child) -- **Send list to manager** -- en-US**".

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.24

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Navigate to your CoE test environment
2. Ensure the current value of the "Individual Admin" environment variable is set to your email (so you will receive the Teams messages for the Cleanup Orphans flows)
3. Ensure the current value of the "Admin eMail Preferred Language" environment variable is en-US
4. Ensure there is at least one orphaned app or flow in your test environment
5. Run the "Request Orphaned Objects Reassigned (Parent)" flow
6. Once you receive the Teams message from the child flow, click the option labeled "Email Me"
7. Check the email you receive.  Notice it uses the "**Request Orphaned Objects Reassigned (Parent) -- **Send admin email of orphans they will need to resolve** -- en-US**" customized email template and not the manager-oriented template

### Anything else?

The cause for this issue seems to be an incorrect hard-coded ID in the **emailGUID to en-US 3** action.  See these screenshots:

**"Request Orphaned Objects Reassigned (Child)" flow **emailGUID to en-US 3** action:**

![image](https://github.com/user-attachments/assets/002807af-5d7e-4b5f-9c08-7a4e6740ab1d)

***

**Compare to Customized Emails:**

![image](https://github.com/user-attachments/assets/70f53abd-ca8b-4a1d-bbc9-cf1dd75e9fff)

***

**Greater context for the **emailGUID to en-US 3** action in the "Request Orphaned Objects Reassigned (Child)" flow:**
>Request Orphaned Objects Reassigned (Child) SCOPE
--> If not timed out
----> True/If yes
------> Switch
--------> Case EmailMe
----------> If apps or flows exist for mail, send it
------------> True/If yes
--------------> Get Row - Send list to manager

![image](https://github.com/user-attachments/assets/86f5375f-a49b-44c2-af32-a5d3efa56fb4)

AB#3889

**Comment by Jenefer-Monroe** [comment]
wow nice catch. you're right! This should be this one instead
8532d7fe-6086-ed11-81ac-0022480813ff
![image](https://github.com/user-attachments/assets/b9a4130f-1af3-4245-8e3a-669ca22d5177)

Fix is to just put that GUID here:
![image](https://github.com/user-attachments/assets/83725a48-bb80-4b3b-8653-c81191b054bf)

Thanks again for posting, local fixed for August.

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
