### ISSUE TITLE
License discovery for power platform 

### ISSUE THREAD

**Issue by krishnakishore1983** [microsoft/coe-starter-kit#8698]
### Is your feature request related to a problem? Please describe.

Is it possible to get license inventory(premium or standard)inside coe starter kit tables or apps it's useful for admins to validate number of active license in the tenant and user information 

### Describe the solution you'd like

Develop an app or custom Connectors to ingest the data into table and populate inside the apps

AB#3890

**Comment by Jenefer-Monroe** [comment]
Unfortunately license information is not provided to us in a way that is consumable for the kit so this is not something we can provide.

**Comment by krishnakishore1983** [comment]
As we can see the licensing information from Microsoft 365 admin center will graph api not sufficient to fetch information from admin center

**Comment by Jenefer-Monroe** [comment]
You may be able to create some http call that will fetch the list of licenses, I do this in my own tenant for some other things as my licensing model in my own tenant is simple.

However the licensing technique varies so much tenant to tenant, and the license names are not uniform across languages. And so we cannot do this in any API performant manner nor in a way that will gather the truth of the matter for all tenants.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
