### ISSUE TITLE
Coe governance 

### ISSUE THREAD

**Issue by krishnakishore1983** [microsoft/coe-starter-kit#8699]
### Is your feature request related to a problem? Please describe.

I am unable find audit logs related to Power Automate and connector audit logs and other Power platform related information in the Power platform audit log I can able to see launch app information 

### Describe the solution you'd like

Please include purview features of Power Platform inside admin view for better governance and incorporate audit log mechanism inside Power bi dashboard 

### Additional context?

9

AB#3891

**Comment by Jenefer-Monroe** [comment]
Hello, yes that is correct. We only gather information about powerapps launches in the audit log solution. 
We do have adding more features to this on the backlog but its unlikely that we will do this as the source of data is not that reliable and the API hit is quite large. 
Likely this will be solved instead as we start to consume the product's Data Export features instead. 
You can stay tuned or come to the office hours to hear more there. 

### Office Hours
Please consider attending our monthly office hours. We talk about new features, upcoming changes, and spend most of the time answering your questions. 
More information:
Join the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours) held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
Click here to download the calendar file to add to your calendar: [Calendar file](https://aka.ms/coeofficehours/ics)
