### ISSUE TITLE
Add new TeamsWebhook specialty connector to the kit

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#8701]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What happens when a new connector is added to the Connectors in the Power Platform Admin view?
I don't see a webhook, will it be added?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2024/1

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3893

**Comment by Jenefer-Monroe** [comment]
We have a flow that runs regularly (weekly) : **_Admin | Sync Template v3 (Call Updates)_**
It, in turn, calls the following flow: **_Admin | Sync Template v3 (Connectors)_**

This will pick up new connectors in the tenant.

Webhook, assuming you mean **_HttpWebhook_** is a "specialty" connector in that its not treated as one by the product and is not returned by the normal systems to list connectors. 
We have a small number of these, also filled by the same flow:
![image](https://github.com/user-attachments/assets/95ec356a-3220-479d-98a5-2ebfee855861)

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
For those that are not treated as connectors, will updating the CoE solution help me get them?

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
Both are running.
HttpWebhook was available!
Incoming Webhook is being discontinued and I would like to manage Microsoft Teams Webhook as a replacement, but it has not been added.

**Comment by Jenefer-Monroe** [comment]
Can you point me to how to create this feature? Meaning the steps to create this connection. I will need a local repro in order to do this work but if you can provide that then I'm likely able to add this for August.

**Comment by Jenefer-Monroe** [comment]
I dont see a way that this Teams webhook interacts with Power Platform. Please do let me know if there is a repro you can walk me through for integrating the webhook with a Power Automate cloud flow and/or a Power Apps canvas app.

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
It will be this connector in the template.
![image](https://github.com/user-attachments/assets/a8b0030b-de53-4029-8b2c-281b419daff8)

**Comment by Jenefer-Monroe** [comment]
ok thank you for posting. I've added this connector for the August relesae.
![image](https://github.com/user-attachments/assets/54aaf259-d4e6-4fe6-8040-dbefd153f63c)

**Comment by asuka1103131** [comment]
Thank you for your response.

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by asuka1103131** [comment]
I can see it in the list of connectors, but it doesn't seem to be sensing the app, so what should I do?

![image](https://github.com/user-attachments/assets/d35042c8-66d4-438b-987b-2e15e25570c5)

![image](https://github.com/user-attachments/assets/a18c5801-e349-4d87-8d47-19818ebcc772)
