### ISSUE TITLE
[ALM Accelerator - QUESTION] Reverting Solution Changes in ALM Accelerator for Power Platform

### ISSUE THREAD

**Issue by Kebo-ard** [microsoft/coe-starter-kit#8704]
### What is your question?

I have deployed new changes to a solution using ALM Accelerator for Power Platform to both the Test and Production environments. However, I need to revert these changes to a previous version of the solution.

Does ALM Accelerator for Power Platform support reverting solution changes? If so, could you provide guidance on how to accomplish this? If not, are there any workarounds or recommended approaches for reverting to a previous version of the solution?

Thank you for your assistance!

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

1.0.20240305.1

AB#3896

**Comment by MaheshSripada** [comment]
@Kebo-ard : Ideal way to reverting changes to solutions is to do remove / delete changes from Dev environment and commit the solution using ALM Accelerator App and Deploy the solutions to Test / Prod.

(Or) You can create a branch from the main / Solution branch and remove the unwanted changes on that branch and create & complete PR which will trigger deployment to Test / Prod envs.

**Comment by Kebo-ard** [comment]
I want to confirm if my approach to reverting to an older solution using the ALM Accelerator is correct and follows best practices. Here's what I did:

1. From the ALM Accelerator for Power Platform, I used the DELETE SOLUTION function.
2. After deletion, I used the IMPORT SOLUTION function to import the solution from the feature branch (the previously committed solution I wanted to revert to).
3. This reverted the solution in the DEV environment.
4. To revert the solution in the TEST and PROD environments, I used the COMMIT SOLUTION function. 
   - I committed the solution and created a new branch based on the solution branch.
   - After the commit, I deployed the solution to TEST by executing a pull request from the new branch to the solution branch.
   - Subsequently, I also deployed the solution to PROD.

As a result, all three environments (DEV, TEST, PROD) were successfully reverted to the older solution.

Please confirm if this method is ideal and adheres to best practices.

**Comment by Kebo-ard** [comment]
Thank you for your assistance.
