### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Sync Template v4 (PVA)  - many actions

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#8706]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello everyone, how are you?

Today, I noticed that I received an alert email from the Platform regarding several executions of a flow, I will put it here so that you can understand and classify whether it is normal or a case of improvement.

![image](https://github.com/user-attachments/assets/3d13937e-cbc7-45e7-abf7-65e6baffa290)
![image](https://github.com/user-attachments/assets/1d325dd8-2d71-4a30-87c1-197adafb585d)

View Detail
![image](https://github.com/user-attachments/assets/abf7fa4a-9a64-41d0-8b16-449b653372b5)
![image](https://github.com/user-attachments/assets/22221866-a5bf-4bf6-81c6-f8b0d9710986)
![image](https://github.com/user-attachments/assets/67c6423d-bbdd-44ca-b684-b71055468cb7)

Process mining (preview)
![image](https://github.com/user-attachments/assets/ec735bf4-c942-4e24-9fc3-1600a2340e67)

Other flow: Admin | Sync Template v4 (AI Events)
![image](https://github.com/user-attachments/assets/17236a17-00fc-4ac2-a560-6c766289326a)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Admin | Sync Template v4 (PVA)

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3898

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately these flows have been streamlined as much as we know how, and they have been reviewed / vetted by product team and the broader community. Your organization may just be too large or too active for our sync flow architecture to cover you. 

The good news is that the product team is working hard now to create the second derivation of the Data Export system which will make inventory natively gathered, and we are working with them to create a new system to use that platform for extension.

**Comment by ClaudioRWS** [comment]
@Jenefer-Monroe 

Hello, I sent the screen as information, but this alert is not affecting the core, it is running without problems and the flows are completing quickly.

It would really be information for you, it's ok!

No problem!!!!!! Relax!!!!!!
