### ISSUE TITLE
[CoE Starter Kit - The connectionreference (.....) component cannot be deleted because it is referenced by 17 other components

### ISSUE THREAD

**Issue by Durk1969** [microsoft/coe-starter-kit#8707]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

In issue #8561 and #8466  the solution is to delete some parts of the flows mentioned in Center of Excellence - Core Components, CoE Core - Dataverse Legacy, Delete blocked by.

For example is this what you have to do:
![image](https://github.com/user-attachments/assets/5fd6235d-70b3-43f0-ae20-0a369c13e00b)
But not all flows are like this. The CLEANUP HELPER flos are different. What should i delete there within these flow?

And than i saw something else. I see in my Center of Excellence - Core Components V2, V3 and V4 flows. Is that how it shoult be?
[Core Components - Admin V.docx](https://github.com/user-attachments/files/16378680/Core.Components.-.Admin.V.docx)

Ik hope you can help me.
We are now running on version 4.23 of the core components. Due to a sick colleague, we are behind with updates.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What method are you using to get inventory and telemetry?

None

AB#3899

**Comment by Durk1969** [comment]
Hi @Jenefer-Monroe , thank you for your explanation. I'm going to get started today and let you know if it worked out

**Comment by Durk1969** [comment]
@Jenefer-Monroe , as you mentioned i deleted all the calls in the flow. Then a did an upgrade and ran the setup wizard. I had no unmanaged layers.
![image](https://github.com/user-attachments/assets/50cbcf5f-89e1-48e3-adb3-e2390f817b08)
As you can see on the picture the solution was successfully implemented. 👍

I am not sure that a have to do an action to update the PowerBI Dashboard. Judging by what the dashboard indicates, I don't think so. You agree?
![image](https://github.com/user-attachments/assets/3e066f3a-bbc7-4722-94c7-98ef73db0621)

**Comment by Jenefer-Monroe** [comment]
Wonderful, so glad it worked! 
We ship a new PBIT file each month and its suggested that you use it as it will expose new fields to you. Sometimes you'll find that you cannot refresh the old PBI anymore due to fields being removed as well. 

You can just re-instantiate the PBIT, save as that same name (Dashboard COE for you it seems) and then re-publish to the same workspace.

**Comment by Durk1969** [comment]
Goodmorning @Jenefer-Monroe, last thursday i succeeded in upfdating the PowerBI Dashboard. I had to followed these intructions: https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-the-power-bi-dashboard

Now our COE-kit is up to date and everything works like charm.
Thanks for your help.

**Comment by Jenefer-Monroe** [comment]
Wonderful news! I appreciate you taking the time to follow up and let me know! 

I'll go ahead and close this out then, but please feel free to open new issues in the future as they arise.
