### ISSUE TITLE
Coe starter kit with sharepoint as backwnd

### ISSUE THREAD

**Issue by krishnakishore1983** [microsoft/coe-starter-kit#8708]
### Is your feature request related to a problem? Please describe.

Coe starter kit requires premium connector as it needs lots of licensing cost for organization also lot dlp policies for dataverse will it possible to implement functionality in sharepoint or any standard connector which helps to explore more organizations 

### Describe the solution you'd like

Sharepoint standard solution 

AB#3900

**Comment by Jenefer-Monroe** [comment]
Hello. 

This is not something that we will be able to do for users, but as a starter kit you are certainly welcome to use what we've done as a starter implementation and make something of your own.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
