### ISSUE TITLE
DLP Impact Analysis - cannot see 'edit policy'

### ISSUE THREAD

**Issue by jimpreston29** [microsoft/coe-starter-kit#8710]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have upgraded to July release. I cannot see 'edit policy'. I've made sure its not a zoom in/out issue

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

DLP Impact Analysis

### What method are you using to get inventory and telemetry?

Data Export

### Anything else?

![Screenshot 2024-07-25 214545](https://github.com/user-attachments/assets/213e7b0a-4ae4-4ad4-9fc8-980f06426994)

AB#3902

**Comment by Jenefer-Monroe** [comment]
I don't repro this. What version of creator kit do you have installed?

**Comment by jimpreston29** [comment]
Hi, i have just upgraded creator kit to 1.0.20240529.1.
Still same problem
Thanks

**Comment by Jenefer-Monroe** [comment]
What region and type is your environment?

**Comment by Jenefer-Monroe** [comment]
Can you also try some other apps and see if the controls show in those? Here for example in the **_Manage Permissions_** app

![image](https://github.com/user-attachments/assets/3b40bd32-c5bb-4192-8916-8e57459bd7ec)

**Comment by jimpreston29** [comment]
Hi, Its a Prod environment in Europe. 
Yes, the 'Manage Permissions' app is showing correct
![image](https://github.com/user-attachments/assets/41daff1f-936b-4157-b186-932f1a35d5e3)

**Comment by Jenefer-Monroe** [comment]
OK that happens to be the type and region I tested so I know its not due to region, which is also hinted at by them showing in this other app.

Can you see if you have unmanaged layers on the app or the custom page?

**Comment by jimpreston29** [comment]
Hi, I did not have unmanaged layers. I installed core components in another environment and I can see the 'edit policy' etc. 

I noticed that 3 of our biggest environments are missing from the dropdown list. I see there is some other 'issues' reported on missing environments - is there a trend that its the 'biggest' environments ?

**Comment by Jenefer-Monroe** [comment]
I just looked at the custom page itself and there is no logic on that command bar's visibility so I don't know how this could be due to tenant size. 
![image](https://github.com/user-attachments/assets/fbf26dcb-b41c-422d-85d5-73f18e8eb992)

I'm afraid you'll need to bring this to the creator kit team for investigation. 
https://github.com/microsoft/powercat-creator-kit/issues

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
