### ISSUE TITLE
[CoE Starter Kit - QUESTION]app or anything that allows us to change owner of flow

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#8712]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

Do we have coe app or anything that allows us to change owner of flow?

Thank you,

### What solution are you experiencing the issue with?

None

### What solution version are you using?

March  2024

### What method are you using to get inventory and telemetry?

None

AB#3906

**Comment by Jenefer-Monroe** [comment]
Hello. Yes if you upgrade to the July release you will see this ability in the Manage Permissions app. 

Note that the product itself only allows you to change owner for flows that are part of a solution so this app changes the owner in the product for solution aware flows, and sets the "derived owner" field in the kit. So all processes will use this new owner and the product processes will also be aware of it and use it.

But for non-solution aware flows, as you cannot update the field in the product, we only update the "derived owner" field in the kit. This means that all the kit processes will use the new owner but the product will not be aware of the new owner, as they do not allow you to set this. 

![image](https://github.com/user-attachments/assets/b511614d-7eaf-4ffb-8bbf-1fa091d25259)

**Comment by lingutla123** [comment]
We changed Owner of a flow through the Manage Permissions app. But flow still showing Primary Owner is previous owner.

Thank you,

**Comment by lingutla123** [comment]
Thank You.
