### ISSUE TITLE
[CoE Starter Kit - BUG] PBI Dashboards - Flow Share Data

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#8713]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

**BUG:**
PBI - PowerPlatformGovernance_CoEDashboard_July2024 - Compliance and Governance
- The numbers don't appear to be accurate based on what I am seeing the dataverse table.

![image](https://github.com/user-attachments/assets/0f934c8c-6d72-47d8-a52d-aa458a6c5504)

![image](https://github.com/user-attachments/assets/496fb8e5-47ee-40bc-a64f-b78bb4c34933)

### Expected Behavior

Would expect the numbers on this dashboard to be accurate:
PBI - PowerPlatformGovernance_CoEDashboard_July2024 - Compliance and Governance

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_4.33_managed

### What app or flow are you having the issue with?

PowerPlatformGovernance_CoEDashboard_July2024 - Compliance and Governance

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Upgrade the environment
2. Enable the flows and let them run
3. Upload the new dashboard, configure, and refresh data.
4. Review the dashboards

AB#3907

**Comment by Jenefer-Monroe** [comment]
Hello, sorry I'm having a little trouble parsing the feature requests vs the bug you believe to be present. And we also need to have separate issues per request as that makes tracking the work possible. 

Can you please post two separate issues for these two feature requests?
1. Add flow shared with info to **_Production_CoEDashboard_August2024 - Flow Deep Dive_**
2. Add flow shared with info to **_PowerPlatformGovernance_CoEDashboard_August2024 - Default Environment_**

Then we can use this issue to clear up what you see as an issue on the Gov home screen.

**Comment by robertcaretta** [comment]
Ok I removed the feature request ideas out of this thread.  Will get new ones created. So basically the issue here is I can see lots of compiled data in the dataverse table for flow shares, but the numbers in the Governance dashboard do not reconcile.  I did refresh the PBI dataset too just to be sure.

**Comment by Jenefer-Monroe** [comment]
The two cards in the PBI sum up the number of guest users shared, not the total number shared. 
So in your picture it would be a sum of the yes's in two of these columns. 
![image](https://github.com/user-attachments/assets/12b4efda-bce1-4c3a-8766-cc14edfd7955)

**Comment by robertcaretta** [comment]
I see, thank you. I misunderstood that calculation then. You close this and I will put in a feature request. What I was hoping to see is total flows shared with Owners and total flows Shared with Editors. The first 2 columns in the graphic, not the Yes/No columns.
