### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by noorilal24** [microsoft/coe-starter-kit#8714]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I cannot access the Coe Environment dashboard. I'm getting the error message: 
{0} with id {1} does not have {2} right(s) for record with id {3} of entity {4}. Consider assigning a role with the required access level to the user or team. For further troubleshooting, please work with a system administrator to use the Access Checker tool on this record: {5}. More details: {6}

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

N/a

### What app or flow are you having the issue with?

Power Platform Dashboard

### What method are you using to get inventory and telemetry?

None

AB#3908

**Comment by Jenefer-Monroe** [comment]
It looks like you are logging in as a user that doesn't have access to the environment. 
If this is a user you want managing the CoE environment as a whole you should give them System Admin access to the environment. 
If you just want this user to be able to access apps / data, then you will want to give them one of our other custom SR's
Please see https://learn.microsoft.com/power-platform/guidance/coe/core-components#security-roles

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
