### ISSUE TITLE
Office365Users.MyProfileV2 failed: { "error": { "code": "accessDenied", "message": "Your organization's policies prevent you from seeing OneDrive content.", "innerError": { "code": "conditionalAccessPolicyEnforced",

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#8715]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have installed the core components for July, when going to complete the setup and upgrade wizard I receive this error

Office365Users.MyProfileV2 failed: { "error": { "code": "accessDenied", "message": "Your organization's policies prevent you from seeing OneDrive content.", "innerError": { "code": "conditionalAccessPolicyEnforced", 

The account we have for the CoE does not have a OneDrive account, is this something that is now required?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Setup and upgrade

### What method are you using to get inventory and telemetry?

Cloud flows

AB#3909

**Comment by Jenefer-Monroe** [comment]
We do not have a OneDrive connection in the app, or in the kit generally. So I don't know why it would say that. 
I'm afraid I can't really help debug conditional access issues, as I'm not that familiar with them. 
Though I can say that the error message does not seem to be correctly identifying the source of the access issue as there is no OneNote connection in the app. 

We do make a call to Office365Users.MyProfileV2 though. Perhaps under the covers that call makes a call to OneDrive?

**Comment by Alyson95170** [comment]
Thanks Jenefer, I will keep an eye on this and see if there are any issues when we import into production

**Comment by Jenefer-Monroe** [comment]
Sorry I don't have a better answer for you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
