### ISSUE TITLE
[CoE Starter Kit - Feature]: PBI Dashboards - Production_CoEDashboard - Flow Deep Dive Page

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/coe-starter-kit#8716]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

PBI Dashboards - Production_CoEDashboard_July2024 - Flow Deep Dive Page

On the dashboard there are no columns present for Flow shares, however I can see the new columns in the Flows dataverse table. Can you please upgrade the PBI report so the new columns are available?

![image](https://github.com/user-attachments/assets/7629aad9-3462-406c-bbce-18bb6d5ae583)

![image](https://github.com/user-attachments/assets/086c50f3-c595-40ad-8674-7f669826ba51)

### Describe alternatives you've considered

N/A

### Additional context?

N/A

AB#3910

**Comment by Jenefer-Monroe** [comment]
Will try to do this for August release. Should be quick.

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/user-attachments/assets/11072205-5900-4ad0-8d26-961636837ec9)
![image](https://github.com/user-attachments/assets/d54627aa-4e62-4508-9ee7-ca7747d94ed7)

**Comment by robertcaretta** [comment]
Yes that's what we are looking for. Having all those new data details for sharing in the dashboards is going to be super useful to us!!  Especially for flow sharing, since credentials are also shared. Thank you.

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
