### ISSUE TITLE
Makers getting added to Makers table without any objects

### ISSUE THREAD

**Issue by akumar194** [microsoft/coe-starter-kit#8718]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have upgraded the CoE starter kit to May 24 version. Performed a cleanup of blank makers. Some of them got added back again to the table. Core component version in 4.29

### Expected Behavior

Blank Makers keep getting added to Makers table

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Core Component

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Sync process

### Anything else?

In the previous ticket, Jeniffer asked to upgrade the kit and this should get resolved.

AB#3912

**Comment by Jenefer-Monroe** [comment]
Can you please point to your previous ticket? If objects are shared for edit with users, those users will also show in the Maker table.

**Comment by Jenefer-Monroe** [comment]
You can do some kind of investigation between the **_Maker_** table and the **_Power Platform User Role_** table: 

That table is related to the User table not maker, but an identity has the same GUID in both (their Entra id). So you could explore there. 

It will point to an envt, a flow or app, and then the role. Owner's and Co-Owners (aka editors) should all also appear in the maker table. 
![image](https://github.com/user-attachments/assets/c921748e-2318-4b2f-afac-b7d454c6cbf1)

**Comment by akumar194** [comment]
I checked the Power Platform User Role table and the subjected users do not have Edit role. They just have CanView role still they are part of Maker table. Where should I be looking at next?

**Comment by Jenefer-Monroe** [comment]
How many users are we talking about here? 
And are you saying these users are "Blank"? What do you mean by that?

**Comment by akumar194** [comment]
After I deleted users with zero objects from the maker table two weeks ago, 15 got added back. This happens every time after I cleanup such entries. 
Blank makers mean makers with zero object in Power Platform and they do not have Edit role in the User Role table either. 

We are trying to identify how are such users getting added to Makers table when they are not actually a maker.

**Comment by Jenefer-Monroe** [comment]
OK I don't know how thats happening for you. You may want to delete them and then run each of the clean up flows one at a time and see if they re-appear with that run

![image](https://github.com/user-attachments/assets/e88360dc-5172-43ff-86f4-ef862d9c0333)

If they re-appear after one of these run do let me know and we can debug from there.
