### ISSUE TITLE
[CoE Starter Kit - QUESTION] Request for Step-by-Step Guide on Creating Microsoft 365 Groups for CoE Starter Kit Setup

### ISSUE THREAD

**Issue by Kebo-ard** [microsoft/coe-starter-kit#8722]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I am in the process of installing and setting up the CoE Starter Kit. According to the prerequisites outlined [here](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#how-to-communicate-with-your-admins-makers-and-users), it is recommended to use Microsoft 365 groups to facilitate communication with Admins, Makers, and Users. This requires creating separate Microsoft 365 groups for each persona: Admin, Maker, and User.

Could you please provide a detailed, step-by-step guide on how to create these Microsoft 365 groups? Additionally, if there are any official references or documentation that could assist in this process, I would greatly appreciate it if you could share those as well.

Thank you for your support.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, there are many ways to create these groups. Different organizations make them in different ways. 

Here is a good write up about what these groups are from a non-MSFT source: https://www.avepoint.com/blog/manage/microsoft-365-groups-explained

I make them in the Azure portal: https://portal.azure.com/#view/Microsoft_AAD_IAM/AddGroupBlade
Make sure you put the identity running the flow as an Owner or they will not be able to manage the group in the flows. 
![image](https://github.com/user-attachments/assets/1b876c48-f2d9-41f0-93ca-be2a406d6d20)

Hope that helps.

**Comment by Kebo-ard** [comment]
Hello,

Thanks for the information and resources. I created my groups in Microsoft Entra Admin, which seems similar to your method in the Azure portal. See screenshots below.

Are the groups email-enabled with this setup?

![image](https://github.com/user-attachments/assets/0a6d9fcf-922e-4cab-adcd-6d80a15d2446)

![image](https://github.com/user-attachments/assets/f24ccd15-058a-4655-aa16-3e506e859dcc)

![image](https://github.com/user-attachments/assets/0d642c57-42dc-41b8-afa2-04fccb3d8d0a)

**Comment by Jenefer-Monroe** [comment]
It does appear to have a mail address, yes. 
The note about mail is really just there for people who create these in more complex (legacy) manners. Doing it in Entra / Azure and you'll be fine.

**Comment by Kebo-ard** [comment]
Hi @Jenefer-Monroe, 

Thank you for clarifying!

I have a follow-up question regarding adding members to the group. Is it also done through Entra/Azure? I added a member to the Admin Group, and there's a flow that sends an email notification to the admin group. However, the members of the Admin Group didn't receive the notification.

Is there something I might be missing in the setup?

**Comment by Jenefer-Monroe** [comment]
We don't have a notification for admins when new makers are added to that group. 
You could add a new flow to do this, you would use the same trigger as **_Admin | Welcome Email v3_**, and just send an email to the admins instead of all the things we do in our flows.
![image](https://github.com/user-attachments/assets/aadc67bf-e2eb-4576-ba59-131d5cb6b2f5)

**Comment by Kebo-ard** [comment]
Sorry for the misunderstanding. Let me be more specific. There's a flow in the CoE Starter Kit named "Env Request | Notify admin when new request submitted." This flow is triggered when a maker submits a new environment request. Upon submission, the flow should notify the Admin Group.

Although the flow runs successfully and sends the notification to the Admin Group, the members of that group didn't receive any email notification.

Could there be an issue with how the group is configured or how the flow sends the email?

**Comment by Jenefer-Monroe** [comment]
oh I see. Yes another person posted this issues yesterday. It's on the owning dev for investigation
![image](https://github.com/user-attachments/assets/88639866-2e9f-4034-951e-dcbc2abe629f)

**Comment by Kebo-ard** [comment]
Actually, that was also me. I initially thought the problem was due to how I created the Admin Group. At least now I know there is no issue with how I created the Admin Group, as well as the Maker and User Groups. I'll wait for the response to the other ticket. Thank you for your assistance!

**Comment by Jenefer-Monroe** [comment]
Happy to help, yes lets track this in the other issue then. I'll go ahead and close this one.
