### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Not Receiving Notification Emails for Environment Requests in CoE Starter Kit

### ISSUE THREAD

**Issue by Kebo-ard** [microsoft/coe-starter-kit#8723]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The admin does not receive email notifications when a new environment request is submitted via the 'CoE Maker Command Center'. Although the flow "Env Request | Notify admin when new request submitted" runs successfully and indicates that the notification was sent to the Admin Group, the members of the Admin Group do not receive any emails.

### Expected Behavior

Admin group members should receive an email notification whenever a new environment request is submitted.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Env Request | Notify admin when new request submitted

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. A maker submits a request for a new environment using the 'CoE Maker Command Center'.
2. The flow "Env Request | Notify admin when new request submitted" is triggered and runs successfully.
3. Check the flow history, which shows that the email was sent to the Admin Group.
4. Members of the Admin Group do not receive any notification emails.

### Anything else?

**Screenshots:**
Please find the screenshots attached showing:

1. The successful run of the flow "Env Request | Notify admin when new request submitted".
![image](https://github.com/user-attachments/assets/748e75e4-07a6-4f8b-8aac-19c1880a9a89)

3. The flow history indicating the email was sent to the Admin Group.
![image](https://github.com/user-attachments/assets/28341ec6-1caf-458e-a882-a8d2fa435ddc)

5. The configuration details of the Admin Group in Microsoft Entra Admin.
![image](https://github.com/user-attachments/assets/d68212a2-3ed8-40f5-9432-a17230201e13)

![image](https://github.com/user-attachments/assets/f10d451e-291e-4488-95ce-b55389c9ffad)

![image](https://github.com/user-attachments/assets/66458155-e921-4937-bc15-ce11b3bece6b)

**Comment by Kebo-ard** [comment]
Hi @Jenefer-Monroe / @gulzarudheen,

Just checking in to see if there are any updates regarding the issue. Thank you!

**Comment by Kebo-ard** [comment]
Thank you for your assistance. I’m now seeing the emails. They are located in the group in Outlook, so I just need to go there to view them.

**Comment by Jenefer-Monroe** [comment]
Oh wonderful news! Thank you for taking the time to let me know. 
I'll go ahead and close this out then but please feel free to reach out with new issues in the future.
