### ISSUE TITLE
[CoE Starter Kit - BUG] Maker Not Notified of Rejected Environment Request - Flow "Env Request | Notify requestor when rejected" Not Triggered

### ISSUE THREAD

**Issue by Kebo-ard** [microsoft/coe-starter-kit#8724]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The maker does not receive an email notification when their environment request is rejected by the admin. The flow "Env Request | Notify requestor when rejected" is not triggered upon rejection.

### Expected Behavior

When an admin rejects an environment request, the maker should receive an email notification informing them about the rejection. The flow "Env Request | Notify requestor when rejected" should be triggered.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Env Request | Notify requestor when rejected

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. A maker submits an environment request.
2. An admin reviews and rejects the environment request.
3. The maker does not receive an email notification about the rejection.
4. Upon checking, the flow "Env Request | Notify requestor when rejected" is not triggered.

### Anything else?

"Env Request | Notify requestor when rejected" was not triggered

![image](https://github.com/user-attachments/assets/a5798626-08bd-4c99-ad36-ff9ced8b250f)

![image](https://github.com/user-attachments/assets/8bc9b131-a28e-4bd1-8475-423b8b0c0634)

**Comment by Jenefer-Monroe** [comment]
To area owner for investigation.

**Comment by Jenefer-Monroe** [comment]
Looks like this happened with the April relesae.

**Comment by Jenefer-Monroe** [comment]
local fixed for August

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by Kebo-ard** [comment]
Thank you for accommodating my concerns and providing the early release for testing. I will try to test the new builds in my free time and provide feedback accordingly.

Thanks again for your support!

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
