### ISSUE TITLE
[CoE Starter Kit - BUG] Failed to upgrade to CenterofExcellenceCoreComponents_4.17_managed solution from 4.33 - connection reference component cannot be deleted because it is referenced by other components

### ISSUE THREAD

**Issue by PPTechy** [microsoft/coe-starter-kit#8726]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I was upgrading the CoE core solution from the 4.17 version to 4.33 version where I was getting this error "Failed to upgrade to CenterofExcellenceCoreComponents_4.17_managed solution from 4.33 - connection reference component cannot be deleted because it is referenced by other components" , then using this [thread ](https://github.com/microsoft/coe-starter-kit/issues/8466)I am able to import the solution successfully. 

Now, I am yet to run the Set up Wizard where @Jenefer-Monroe mentioned the below:

"Those flows are getting deleted so you don't need to worry about the unmanaged layers. And any flows that are left but which we just removed the refence, you can remove the unmanaged layer after upgrade."

Now, I have a question on this point: You can remove the unmanaged layer after  the upgrade." After successfully importing the solution, while I am running the setup wizard, I am getting the below message:

image
Here, either I can click on the acknowledge button or remove the solution layer before I run the setup wizard. Here my question is, as it is mentioned on the alert message:

<img width="502" alt="image" src="https://github.com/user-attachments/assets/fa088749-04d4-4c1f-a3ba-c9d65765c2fc">

"Canvas apps, custom pages, and Cloud flows that have unmanaged layers. This means customizations have been done to this app or flow in the managed solution, and they didn't receive the latest version during the upgrade. Remove the unmanaged layer to revert to our version, or acknowledge that you want to keep the unmanaged layer with your customizations."

Here, my question is, as I have already upgraded my solution, and then if I remove the solution layer, then my solution layered flow (affected flow SYNC HELPER - Get Security Role Users) will not receive the latest update from this upgraded solution, right? Then, how to handle this one? Kindly guide me on this. 

Before running the Wizard should I remove the solution layer for this flow "SYNC HELPER - Get Security Role Users" then run the wizard, in this case, this flow will not receive the latest update of 4.33 version, Can I do this way or how?

@jene

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Having a little trouble following but hopefully this helps

Unmanaged layers represents edits you've made on top of what we delivered. The way it works is that its actually a whole copy of the flow with your changes in it. 

When you upgrade you will get the changes from us but you wont see them in the flow/app, you will see your version of the object. When you delete your unmanaged layer you will see our version. 

So now that you have done the work to ensure all dependencies to the connection reference:

1. Do the upgrade again (sounds like you did and it worked yeah)
2. Boot the setup wizard it will show you these unmanaged layers. Click the button (See layers) and remove them. 
3. Continue with the setup wizard

Hope that helps!

**Comment by PPTechy** [comment]
H @Jenefer-Monroe, thanks for your reply. Yes, I have completed the below steps:

- Do the upgrade again (sounds like you did and it worked yeah) - Done 
- Boot the setup wizard it will show you these unmanaged layers. Click the button (See layers) and remove them. - Done
- Continue with the setup wizard - Done

**Comment by Jenefer-Monroe** [comment]
Great news! Seems like you're all set then.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
