### ISSUE TITLE
Failure in CLEANUP - Admin | Sync Template v3 (Orphaned Users) when cannot get tenant count

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#8728]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When this flow runs, it always produces this error on the "Tenant Has Guests" compose action:  
Action 'Tenant_Has_Guests' failed: Unable to process template language expressions in action 'Tenant_Has_Guests' inputs at line '0' and column '0': 'The template language expression 'if(equals(length(outputs('Get_Tenant')?['body/value']), 0), false, coalesce(first(outputs('Get_Tenant')?['body/value'])['admin_grouphasguestusers'], false))' cannot be evaluated because property 'admin_grouphasguestusers' doesn't exist, available properties are '@odata.type, @odata.id, @odata.etag, @odata.editLink, admin_powerplatformuserid@odata.type, admin_powerplatformuserid, admin_groupsize@OData.Community.Display.V1.FormattedValue, admin_groupsize'. Please see https://aka.ms/logicexpressions for usage details.'.

### Expected Behavior

expect for it to work

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Run the Flow

**Comment by Jenefer-Monroe** [comment]
I believe your tenant user isnt set up correctly. 
This is fixed by the following flow: CLEANUP - Admin | Sync Template v3 (Orphaned Users)
![image](https://github.com/user-attachments/assets/4d619a41-e1ab-4a39-ad70-fb6d5ddf4107)

The flow should run with the Setup Wizard

**Comment by Jenefer-Monroe** [comment]
After looking at the failure it appears the issue here is in CLEANUP - Admin | Sync Template v3 (Orphaned Users) causing it to fail.
Will reuse this issue for that.

**Comment by Jenefer-Monroe** [comment]
The same tenants that cannot do this action (and hence why we catch)
![image](https://github.com/user-attachments/assets/a14e72bd-36c6-4573-ac60-f24b666b685e)

Also cannot do these
![image](https://github.com/user-attachments/assets/4de2d5f2-7214-4002-8f68-8d1c65a1a038)

**Comment by Jenefer-Monroe** [comment]
Will fix in a way such that users can manually enter the tenant count and it wont get over ridden for these users.

**Comment by Jenefer-Monroe** [comment]
![image](https://github.com/user-attachments/assets/4cade0ca-8cff-40b2-b0b2-93dc86dd0de3)

**Comment by anttipajunen** [comment]
@Jenefer-Monroe what exactly/what conducted action should trigger the "CLEANUP - Admin | Sync Template v3 (Orphaned Users)" flow?

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by RickKush** [comment]
I am using the August release, 4.37.
I don't have this flow, CLEANUP - Admin | Sync Template v3 (Orphaned Users)
