### ISSUE TITLE
Admin | Gather Tenant SRs fails in June's Release

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#8730]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,

I thought this flow will stop failing once we upgrade to June's Release of the COE CORE. Would you happen to know if July's kit will fix it? In the meanwhile, should we just ignore it? 

thanks,
![pic](https://github.com/user-attachments/assets/17649bdc-fdb3-4055-8f34-fbaa56e0dcae)
![pic2](https://github.com/user-attachments/assets/1ea502b8-c02e-4ac4-b797-f26bdcfffe1e)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Admin | Gather Tenant SRs

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello likely you have been impacted by new product behavior that shipped recently around the way the product treats privileged roles (ex Power Platform Admin role, Global Admin role)

While there is a workaround we can put into the kit to fix this directly, we cannot ship it with the kit until the workaround is available in all regions. **_Hopefully for the August release but we are still blocked by the roll out of this connector to some regions._**

### The product change
Here is information about the product feature: [Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)

### How to check if this is the case
1. Validate the user running the flow has direct and permanent assignment to the Power Platform Admin role.
2. Take one of the target environments in your repro, one of the environments which is failing, and make sure the user running the flow has System Admin security role in that target environment.

### How to address and More information
Please see https://github.com/microsoft/coe-starter-kit/issues/8119 for a write up on this change. 
Included also is a workaround you can do until we can have it natively in the kit.
