### ISSUE TITLE
[CoE Starter Kit - BUG] "Admin - Access this Flow [works embedded in Power BI only]" Error

### ISSUE THREAD

**Issue by Kebo-ard** [microsoft/coe-starter-kit#8732]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When launching the app named "Admin - Access this Flow [works embedded in Power BI only]", an error occurs as shown in the screenshot below. Upon further investigation, it appears that this app is intended to be embedded in the Power BI report on the "Manage App Access" page. However, there is no "Manage App Access" page available in the report.

Question: Is this app already deprecated and no longer in use in the Power BI report? If it is deprecated, can it be safely ignored? If not, can you help me fix the error in the app?

### Expected Behavior

The app should either launch without errors or, if it is indeed deprecated, it should be removed from the CoE Starter Kit to prevent confusion.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Admin - Access this Flow [works embedded in Power BI only]

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the "Admin - Access this Flow [works embedded in Power BI only]" app.
2. Observe the error that appears upon launching.

### Anything else?

Screenshot of Error Message:
![image](https://github.com/user-attachments/assets/45e5ffff-1a03-41ec-bb50-bc760cdbab2c)

**Comment by Jenefer-Monroe** [comment]
There is a Manage App Access page in the PBI, though its a hidden one. You will see it if you scroll to the right in the PBI Desktop.

![image](https://github.com/user-attachments/assets/8589b531-48e4-4d1d-bbb2-231325ea6cba)

Hope that helps.

**Comment by Jenefer-Monroe** [comment]
Here are the steps to [configure the embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard)

And you are correct, the app only works when embedded into PBI. It will not work for you if you launch outside of the context of PBI.

**Comment by Kebo-ard** [comment]
Thank you for the clarification and the steps to configure the embedded apps in the CoE dashboard. I appreciate your assistance. I will proceed with ignoring the error message when the app is launched outside of Power BI, as it functions correctly when embedded.

If I have any more questions or need further assistance, I'll reach out. Thanks again!

**Comment by Jenefer-Monroe** [comment]
Glad we were able to get this resolved for you, and thanks for reaching out. I'll go ahead and close.
