### ISSUE TITLE
HTML Templates in Power Automate O364 Outlook connector

### ISSUE THREAD

**Issue by josellevw** [microsoft/coe-starter-kit#8734]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We would like to deploy a new welcome email every time a new user registers in Power Apps.
Currently, we are using a regular email (text), but we want to improve the visuals using HTML. 
We are having issues deploying the HTML template – can you advise who can help us with this?

![image](https://github.com/user-attachments/assets/407c436e-8a04-422e-a8ca-81352392d02d)

### Expected Behavior

Be able to load the HTML template in the Welcome Email workflow

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Client version: 1.4.8870-2407.1

### What app or flow are you having the issue with?

Other Core Components - Send Welcome Email

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

COE Toolkit > Customized Emails > Send Welcome Mail

### Anything else?

None

**Comment by Jenefer-Monroe** [comment]
Hello, that looks great! Unfortunately we are not staffed to assist with customizations to the kit. 
I hope you are able to get it working though it looks great. 
Happy to leave this open for a bit to see if others in the community can assist.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
