### ISSUE TITLE
Where can we find a list of all the notifications sent out by the CoE?

### ISSUE THREAD

**Issue by AzizAQureshi** [microsoft/coe-starter-kit#8735]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team,

Where can we find a list of all the notifications sent out by the CoE? 

How can we make some notifications to be sent to makers only, or to admins only, or both makers and admins?

Thank you

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We have a place you can review all mails sent in the CoE Admin Command Center. There isnt an easy way to change who the mail is sent to, as that is rather complex in each flow's logic. But you can add people or groups to the CC. 

![image](https://github.com/user-attachments/assets/6baf988e-defd-45c9-9326-860dba8fd01d)
![image](https://github.com/user-attachments/assets/4ff523ae-223e-4f13-ae8f-6263e8be2790)



In addition there is an env var called **_ProductionEnvironment_** which you can set to "No" and then all communications (mail and teams) will be sent to the admin only. Do note that sometimes flows cache env vars so you'll want to turn the flows off and back on. 
![image](https://github.com/user-attachments/assets/7b096a5b-9e7d-4eae-8098-ad71ed74ee63)

**Comment by Jenefer-Monroe** [comment]
For teams communications, we do not have any collection of these but you can go see where the teams connection reference is called and then explore those flows:

![image](https://github.com/user-attachments/assets/dd05ac5b-9be6-4731-b77c-a9873e716eec)
![image](https://github.com/user-attachments/assets/f7ceaa9a-0dc7-467b-92f4-0b0d437137bc)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
