### ISSUE TITLE
[CoE Starter Kit - BUG] Core Component - Flows and some Apps Show Blank Values as Makers

### ISSUE THREAD

**Issue by inquisitive-identity** [microsoft/coe-starter-kit#8737]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

I was just looking around the Power BI Dashboard and I noticed that there are a lot of Flows (and some Apps) that have _Blank_ values as _Makers_.

![image](https://github.com/user-attachments/assets/50ba91bb-646c-473e-8b94-dee77007d355)

I looked at the _Flow_ table in Dataverse and it is indeed showing that plenty of flows have no Maker information.

- All 3 flow states are impacted (Stopped, Started, Suspended)
- Interestingly enough, some flows are actually from the CoE Kit itself
- I don't remember, but I **think** this worked properly in the past

Thank you very much in advance for your help!

Best regards,
Stefan

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We do expect blank makers in the case where a flow is inventoried after the maker has already left the organization. 
In this case the Maker table will not be filled as Entra will no longer have the information. 

However that is typically a small number of flows. So lets investigate.

Please take a flow you expect to not have a blank maker and note its flow ID an envt ID
Go to the following flow : SYNC HELPER - Cloud Flows
And run it with this flow as a test case

![image](https://github.com/user-attachments/assets/c3591b5d-aed9-44c7-829f-bb3d37d9df17)
![image](https://github.com/user-attachments/assets/6c44dcd2-fcbf-4493-8e92-fa8550ee34f3)

1. Does the maker get filled now? 
2. If not, open the run, what is returned here
![image](https://github.com/user-attachments/assets/c39922c9-5a36-4e24-bb2c-6b5d321a4e69)

**Comment by inquisitive-identity** [comment]
Hey Jen,

I ran the Sync Helper flow on the _Admin | Quarantine non-compliant apps_ that should have my service account as the Maker of it.

Did everything, and it turns out the output of the Get Flow as Admin is missing the entire _Creator_ object... :O

![image](https://github.com/user-attachments/assets/d0dc966d-4a7c-4e55-86ac-356942e0ef82)

Any thoughts?

**Comment by Jenefer-Monroe** [comment]
Well thats a product bug. Ugh. 
CAn you please check if this "workflowUniqueId" 
![image](https://github.com/user-attachments/assets/efe7bf51-3093-469a-a71d-f02193086606)

Is equivalent to "Name" from the output?
![image](https://github.com/user-attachments/assets/1ba7c19d-57d9-4f8b-baa9-4a9e853d3440)

**Comment by inquisitive-identity** [comment]
Yeah, the Uniqueid is the same as the Name, so that is fine at least. 

I don't get it...
I tried running a separate flow with only "Get Flow as Admin" action, and the results are literally arbitrary...

For additional flows (_Welcome Email & Admin | Set app quarantine status_, and some more) the _Creator_ object is missing, but for some others, it's there...
Regardless of the trigger type as well, tested both Scheduled and Automated, Disabled and Enabled flows... It's strange :O

For what is worth, my company is running a Pay-as-You-Go plan for some environments, one of which is CoE Prod, where the CoE kit is hosted, but I don't see how that would prevent any Power Automate action from sending over all objects through API...

**Comment by Jenefer-Monroe** [comment]
Those two fields being the same means its an unpublished flow. We shouldnt be collecting those into inventory at this time as things like this are still bugs in the product. The product returning unpublished flows is a new feature. 

Can you please spot check some more of these two see if they are all unpublished flows? 
And also double check to make sure your version of core?

**Comment by Jenefer-Monroe** [comment]
Yes they seem to be changing the verbiage that goes in here and its been a little confusing. 

These unpublished flows should not be gathered. It's possible that they were accidently gathered at some point as the product is iterating on the feature. 

Can you please go run this flow: **_CLEANUP - Admin | Sync Template v4 (Check Deleted)_**

When it calls **_CLEANUP HELPER - Check Deleted v4 (Cloud Flows)_** it should find all these unpublished flows to be deleted and mark them as such.
![image](https://github.com/user-attachments/assets/49180ad6-254f-4cd3-bc0f-ebe0cfec6a2e)

**Comment by inquisitive-identity** [comment]
Hey Jen,

Apologies for the delay; I will run the flow but it will take some time for it to complete - I will update you on the results.

In the meantime, the flows that are in the "Started" state and have no Makers were indeed created by the users who are not in the company anymore :)

**Comment by Jenefer-Monroe** [comment]
OK good thank you. sounds like you just ended up with these in your inventory somehow. Likely due to product issues as they rolled out this feature. 
Please do let me know if they are cleaned up from the run of Check Deleted. 
And then let me know as well if they come back.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
