### ISSUE TITLE
[CoE Starter Kit - BUG] Manage Permissions App fails when trying to delete orphaned flows

### ISSUE THREAD

**Issue by Knowone27** [microsoft/coe-starter-kit#8738]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When trying to delete any number of orphaned flows in the Manage Permissions app I get the following error. 
"Deleting some flows failed, try to delete via product UX"

<img width="1914" alt="Screenshot 2024-07-23 102144" src="https://github.com/user-attachments/assets/7d5286d5-96d0-4387-a01b-a3e9c854fc95">

<img width="1915" alt="Screenshot 2024-07-23 102231" src="https://github.com/user-attachments/assets/9fd3879e-c26c-4e00-bac4-97d8c0920c8c">

### Expected Behavior

Whether it be 1 or 100 flows, I expect the app to be able to delete the number of flows selected, but it fails no matter how many flows are selected.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Manage Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Login to Power Apps as the Power Platform Global Administrator
2. Navigate to the Manage Permissions app
3. Click on the "Flows" tab
4. Click on the "Orphaned Flows" Button
5. Click the checkbox of any, or all flows from the list
6. Click the "Delete Selected" button
7. Wait a minute for the error message to popup saying "Deleting some flows failed, try to delete via product UX" 

### Anything else?

I have reached out to our MS contact and he advised me to submit an issue here. He was able to see the issue in a call we had to discuss a potential support ticket.

**Comment by Jenefer-Monroe** [comment]
Can you please browse to one of the flows and try to delete manually? This way we can see the error message you get.

**Comment by Knowone27** [comment]
> Can you please browse to one of the flows and try to delete manually? This way we can see the error message you get.
Deleting manually works correctly, it does not have any errors. Only the "Manage Permissions" application. There are hundreds of flows to delete, and deleting each one on an individual basis would take days or weeks.


> And also, are you logged in as a user with the Power Platform Admin role?
Yes, as described in the steps to reproduce using the Power Platform Global Administrator role.

**Comment by Jenefer-Monroe** [comment]
Can you validate, are these solution aware flows? 

We did just, in the July release, unblock deleting of solution aware flows through the helpers:
https://github.com/microsoft/coe-starter-kit/issues/3052

**Comment by Knowone27** [comment]
These are older flows from 2021-2022, so I do not believe any of them are in solutions.

**Comment by Jenefer-Monroe** [comment]
ok you'll need to open the flow that is called and see where it is failing then. 
Browse to this flow, open the recent run and show me what happens inside there
HELPER - CloudFlowOperations

Here, for example, you can see it failing due to a product limitation. 
![image](https://github.com/user-attachments/assets/83c9ada0-7589-4abf-a0e9-325e7acdb577)

**Comment by Knowone27** [comment]
> ok you'll need to open the flow that is called and see where it is failing then. Browse to this flow, open the recent run and show me what happens inside there HELPER - CloudFlowOperations
> 
> Here, for example, you can see it failing due to a product limitation. ![image](https://private-user-images.githubusercontent.com/89584709/353540317-8582b989-1c70-4d46-9c9b-9c93de17a406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTcyMjUsIm5iZiI6MTcyMjM1NjkyNSwicGF0aCI6Ii84OTU4NDcwOS8zNTM1NDAzMTctODU4MmI5ODktMWM3MC00ZDQ2LTljOWItOWM5M2RlMTdhNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE2Mjg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNWEzNWU0MTdlZDJhZWMzMmI2OGVkMzBhZjJhMTY1MmY4ZTg0NDcxMzQ0ZWVkMjBjM2U3ZDUyNmM0NTliNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K25qCkw0_HFPipFgAyjnIve8h3hJHUOTl5vjiRwLguk)

it does not appear to be failing
<img width="584" alt="image" src="https://github.com/user-attachments/assets/2ec6a81e-ddaf-4285-b098-a677a924d431">

**Comment by Knowone27** [comment]
Just confirmed, it does not show any failures in the 30 day run history

**Comment by Jenefer-Monroe** [comment]
yes we catch these failures. Please open the run for when it fails for you and see what happens there.

**Comment by Knowone27** [comment]
Okay, this is what it's giving me 

<img width="1914" alt="image" src="https://github.com/user-attachments/assets/af6e4dca-df82-4891-a815-4c19e6fd5aa3">

**Comment by Jenefer-Monroe** [comment]
Did you erase the inputs?  Or were they blank?

**Comment by Jenefer-Monroe** [comment]
Can you please share the body of the output?

**Comment by Knowone27** [comment]
Everything is blank.

**Comment by Knowone27** [comment]
{
  "error": {
    "code": "EnvironmentAccessDenied",
    "message": "You are not permitted to make flows in this '9407f998-df4c-49e1-bb48-b181e9e3f8dc'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions."
  }
}

**Comment by Jenefer-Monroe** [comment]
The user that is logged in to the app appears to not have elevated permissions for that environment. 

Can you please validate that the user logged into the app has the power platform admin role assigned?
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

**Comment by Knowone27** [comment]
<img width="1881" alt="image" src="https://github.com/user-attachments/assets/1664c1e9-9ff7-4ee3-827b-5c08dc5f6038">

**Comment by Jenefer-Monroe** [comment]
Is that envt your default environment?

**Comment by Knowone27** [comment]
> Is that envt your default environment?

You mean in Azure? I think we only have one Azure Environment.

**Comment by Jenefer-Monroe** [comment]
no I mean the envt in which the flow lives. Is the flow you are trying to delete in your power platform default environment?

**Comment by Jenefer-Monroe** [comment]
I will presume that they are, but please do confirm. 

It looks like the dev that made this app sent in the id of the envt and not the name. 
Many calls take "name" not "id" and this is only obvious if one tests default as its the only one where they arent identical. 

Basically for a default envt
if id = abc123a1-aabb-bbaa-aa11-a11aa11a1a1a
then name = Default-abc123a1-aabb-bbaa-aa11-a11aa11a1a1a

**Comment by Jenefer-Monroe** [comment]
quick testing shows the issue is only with delete, not updating permissions or browsing to the app, etc

fixes are to the custom pages as shown: 

![image](https://github.com/user-attachments/assets/ab5669bd-c6b0-4e6a-9573-4f7595f63427)
![image](https://github.com/user-attachments/assets/1c004859-e2dc-44cb-8714-c6d38ae3c422)

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, unless I hear from you otherwise I'll assume these were flows in default. 
And that we are now local fixed for August release.

**Comment by Knowone27** [comment]
Yes Jenefer, These flows are in default. So in the upcoming release (August) these fixes will be rolled out?

**Comment by Knowone27** [comment]
> Thats correct, thanks for confirming!

Thanks, Jenefer. You've been a major help! I'll go ahead and close this thread.

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
