### ISSUE TITLE
[CoE Starter Kit - QUESTION] Understanding Security Role Feature in the Manage Permissions App

### ISSUE THREAD

**Issue by LucasCXavier** [microsoft/coe-starter-kit#8740]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team,
I'm trying to fully understand the new feature to Manage and Configure SRs that is part of the Manage Permissions Model Driven App. I couldn't find any information in the documentation.

My questions is: How do we determine whether a Security Role was created by a user or if it was automatically added to the Tenant by Microsoft?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2024

### What app or flow are you having the issue with?

Manage Permissions App

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by LucasCXavier** [comment]
Got it! Thanks so much @Jenefer-Monroe!

**Comment by Jenefer-Monroe** [comment]
You bet, happy to help

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
