### ISSUE TITLE
Environment Capacity for no Dataverse environment doesn't have capacity

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#8741]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Environment with no dataverse still consume 1GB of database storage.  Since the change back in March to reduce Power Platform Request limits, the actual storage of environments is conditional on whether or not it has 'admin_hascds'.  This makes sense, however it's not actually true from a capacity usage point of view.  The Capacity tab of environments should reflect the actual consumption on the _tenant_. 

This is throwing us off as we are building a Power BI report to forecast environment usage based on historical data and no data is being added to the environment capacity table since March.

Other than maybe reverting to tracking the actual consumption regardless of environments, the rated and actual consumption should match.

![image](https://github.com/user-attachments/assets/40e5e906-9c0a-4181-b00a-f77fd745c1d4)

![image](https://github.com/user-attachments/assets/07a2c557-3818-4f42-a1bf-97202c967de6)

### Expected Behavior

Actual tenant consumption is tracked again.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Environment Capacity Flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
It looks like, when this change happened, we stopped making this call for non-CDS environments. 
Can you please delete this clause and see if that gets you what you want? 

In **_CLEANUP - Admin | Sync Template v4 (Other Objects)_**
![image](https://github.com/user-attachments/assets/82ec2aca-c810-41c7-8d8b-1f704a67c618)

**Comment by PPCan** [comment]
Yeah, that's the condition that's causing the issues.  What's the parent flow to trigger to test the dataverse update?

**Comment by Jenefer-Monroe** [comment]
That (Other Objects) is the parent flow. So if you remove that clause and then run that flow, you can see if it fixes things.
Thanks for testing!

**Comment by PPCan** [comment]
Something blew.  It's looking for the cds url
{
  "error": {
    "code": "TriggerInputSchemaMismatch",
    "message": "The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'Invalid type. Expected String but got Null.'."
  }
}
![image](https://github.com/user-attachments/assets/7d0eaea1-9f72-4d8f-a413-4a3ba317d63b)

**Comment by Jenefer-Monroe** [comment]
oh yep we would need to change this to call those separately. That failure is unrelated to capacity though. 
Can you see if you got what you need from the capacity pov?

**Comment by Jenefer-Monroe** [comment]
How we would split these assuming the change described above fixes it for your from the capcity POV
![image](https://github.com/user-attachments/assets/9738c3bc-bcfa-43e5-9cf4-faf405a7200f)

**Comment by PPCan** [comment]
Looks like it. 

![image](https://github.com/user-attachments/assets/f36d4bcc-2489-4ea6-9721-8925138424eb)

**Comment by PPCan** [comment]
However... the model view doesn't show it, and the environment is not in active but deleted.  This is a test environment, but it's not that old and I'm the only one in it so it's not polluted. Related issue?

![image](https://github.com/user-attachments/assets/e071537c-e272-4285-aa7e-a09d14018676)

**Comment by Jenefer-Monroe** [comment]
The MDA just pulls from that table, so I dont know how you would be seeing that but it would be unrelated. We just populate the table with that flow which it looks like it does.

**Comment by Jenefer-Monroe** [comment]
An early release of the August bits are available for testing. 
Please see our [Preview Builds](https://github.com/microsoft/coe-starter-kit/releases/edit/CoEStarterKit-PreviewBuilds)

Please test for us! But do not install these in your production environment but rather in a test envt to get us feedback. 

Here are the August release candidate solutions.
[Core 4.33.14](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceCoreComponents_4_33_14_managed.zip)
[Gov 3.24.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceAuditComponents_3_24_1_managed.zip)
[Nurture 3.18.1](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/CenterofExcellenceNurtureComponents_3_18_1_managed.zip)

And the PBIT files
[Production CoE Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/Production_CoEDashboard_August2024.pbit)
[Governance Dashboard August 2024](https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-PreviewBuilds/PowerPlatformGovernance_CoEDashboard_August2024.pbit)

It contains all the changes targeting August: https://github.com/orgs/microsoft/projects/195/views/59

Including these two very impactful changes: 
https://github.com/microsoft/coe-starter-kit/issues/8016 - Update Kit to respond to new Power Platform Admin Role PIM feature
https://github.com/microsoft/coe-starter-kit/issues/8482 - Integrate new audit log methodology into the kit for API reduction. Please see issue for setup instructions.

**Comment by PPCan** [comment]
Ok! So the preview has the fix?

**Comment by Jenefer-Monroe** [comment]
correct!

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
