### ISSUE TITLE
Data Export and Legacy environments doesnt work.

### ISSUE THREAD

**Issue by NGseb** [microsoft/coe-starter-kit#8742]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello, we can see a bug.
Our default envrionment is : "Default-11111111-2222-3333-4444-555555555555"
However, we also have an old environment which contains (from preview) (Upgrade) and the id is : "Legacy-11111111-2222-3333-4444-555555555555"
The inventory component has mistaken and assigned the apps and flow to the legacy environment for the Default and when we try to manage permissions for an app, it triggers this error : 
![image](https://github.com/user-attachments/assets/f59f1687-c59d-4cd6-913a-6deb3c171d00)

We use July edition.

### Expected Behavior

use the default instead of the legacy

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.3.20230724.1

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Can you please provide more detailed repro steps? I do not repro this issue so I would like to understand what you are seeing.

**Comment by NGseb** [comment]
For example in the environment lists : 
![image](https://github.com/user-attachments/assets/f39939c4-6734-45e8-a99a-f3f15a75a9f8)
All our environments ID are using the same format except 2 : the Default and the Legacy (from 2016) where it is pre-fixed to the ID.

**Comment by Jenefer-Monroe** [comment]
I see. OK thats why I dont repro. Legacy environments have been deprecated by the product team for about 10 years now. 

Unfortunately fixing this would be a sizable change to the apps so I will need to place on the backlog. In the meantime you will need to manage the permissions of these objects using the product UX.

**Comment by Jenefer-Monroe** [comment]
After offline conversation it appears this is actually a generalized issue with Legacy envts and BYODL which is unfortunately known.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
