### ISSUE TITLE
[CoE Starter Kit - BUG] - Connecting Dataverse Tables into Power BI Produces an Error

### ISSUE THREAD

**Issue by AllyThorne** [microsoft/coe-starter-kit#8743]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are trying to created a report in Power BI that is connected to the "admin_app" Dataverse table that contains all the information about the Power Apps in the CoE toolkit. 

However, we are getting an error: DataSource.Error: Microsoft SQL: "Invalid column name 'admin_totalshared'.\r\nInvalid column name 'admin_totalshared_date'.\r\nInvalid column name 'admin_totalshared_state'." 

This would suggested that the columns - admin_totalshared - admin_totalshared_date - admin_totalshared_state have been removed or no longer exist, however we cannot find them in our dataverse tables. Is there a dependency on these that still exists as we cannot understand the reason for the error. 

I have however been able to find the columns in a previous version of the CoE I have installed (4.23) and I am able to import the data into Power BI. Can we confirm if this is a bug in the kit or a product issue we are having? 

### Expected Behavior

Would expect to be able to connect directly to the dataverse table without it throwing errors to say that columns are missing. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Admin_App Table

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

In Power BI, create a new report from existing data > Select Datasource as Dataverse > Select The CoE Environment > Select the Admin App Table.

**Comment by Jenefer-Monroe** [comment]
Hello. We're not staffed to assist with custom reports but I'll see if I can help with what I know about the solution. 

We did use to have a column called admin_totalshared in the PowerApps table. It was removed in favor of a different setup of columns as shown here:

OLD
![image](https://github.com/user-attachments/assets/d29e2e2d-6e63-453e-a81c-d33192205f91)

NEW
![image](https://github.com/user-attachments/assets/9e86e11e-8b28-4ec0-9a2d-26fe0e5e15a1)

**Comment by Jenefer-Monroe** [comment]
So it could be that you have a reference to that in the transform. If you started your report with one of ours then you likely do. Here is where you would find it, and you'll know you've cleaned up all the way when the query completes.

![image](https://github.com/user-attachments/assets/45c42f83-05fb-4401-8786-4616834c0529)
![image](https://github.com/user-attachments/assets/800b86b9-a688-4ca6-be46-12e38ada17e7)
![image](https://github.com/user-attachments/assets/3e41fa39-9e05-4d7f-a981-e111f3498f63)
