### ISSUE TITLE
Renamed envt not showing in object data

### ISSUE THREAD

**Issue by aemirandas** [microsoft/coe-starter-kit#8744]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

ACP has an original environment named Autoridad del Canal de Panama (Upgrade). After a Power Platform Maturity Assessment made by Microsoft, one of their recommendation was (change the default environment to Personal Productivity. So, I changed the default environment from Autoridad del Canala de Panama (Upgrade) to Productividad Personal (ACP). But until today I was thinking that, just by changing the name all the artifacts (apps and flows) will not suffered any changes. But, today with a power platform maker, trying to find an app but it is not show in the apps section at the Power Apps tool. Few months ago (almost two) I download from the Power Platform CoE, the full list of apps and flows and their makers/owners. In that list, an app name "Planes de Retiro Voluntario on Auditorias forms" exists in the Autoridad del Canal de Panama (Upgrade). The specific questions are: 1. Why, if I just change the name of the default environment, not all of the apps and flows are shown under the new name of the default env? 2. More than just change the name, did I have to do something else? 3. Why I can still see the name of the default emv (the original one) in every option inside the CoE? I am attaching some pics just taken at the Power Platform CoE.

### Expected Behavior

Be able to see all my flows and apps under the new default env name in the CoE.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin - sync template v3

### What method are you using to get inventory and telemetry?

None

### Anything else?

Microsoft support to raise a ticket to GitHub.

**Comment by Jenefer-Monroe** [comment]
Hello, your pictures did not come through. However I think that I can follow along with your notes. 

### Text fields
There are some fields like the ones shown here, which are (unfortunately) text fields. 
When the object is inventoried it makes a copy of the name of the environment into the field. 

### Why would we do this???? 
Lame I know. Sorry. The kit was made years ago before PowerFX columns existed and before hopping to other references in PowerApps and Power Automate worked very well. And given our ISV nature its hard to make dramatic changes like removing these. 
![image](https://github.com/user-attachments/assets/e922d851-f414-4f60-a5f6-b3ee7da1c762)

### Test it
You can test this theory by marking one of the apps you see to be inventoried and then looking the next day, you'll see it be corrected. 
![image](https://github.com/user-attachments/assets/894aed90-ccae-4dbd-87de-c8c869751831)


### Fix it
To fix this I would suggest opening the tables in Excel and updating the fields there. That way there isnt an API impact and it wont take you long.
Here is some information about the [Excel Addin for for Dataverse](https://learn.microsoft.com/power-apps/teams/edit-data-in-excel)
![image](https://github.com/user-attachments/assets/b28b7957-68b8-459d-95b4-7464dac5b98e)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
