### ISSUE TITLE
[CoE Starter Kit - QUESTION] About the Maker Table.

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#8745]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have a question about members being added to the Maker table.
・Will co-owners of the app or flow be added?
・Will people who use the app or flow be added?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2024/4

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. 

### Will co-owners of the app or flow be added?
Yes people who have edit permissions to apps/flows should be added to the Maker table.

### Will people who use the app or flow be added?
No people who have view permissions for or who just use (as viewer) an app/flow should not be added to the Maker table.

**Comment by asuka1103131** [comment]
・If I delete all the apps I own, will they be removed from the Maker table?

・What is the case for the following data?
![image](https://github.com/user-attachments/assets/ebb00d76-d2a9-4114-8111-5291c9503f20)

**Comment by Jenefer-Monroe** [comment]
No they will not. We don't have any clean up of that table.

**Comment by asuka1103131** [comment]
Are the people with Number of apps and Number of flows of 0 those who created the app but deleted it?

**Comment by Jenefer-Monroe** [comment]
It could be that, or other situations:

- if they own other objects types like Desktop Flows or Power Pages.
- if they have been granted edit permissions to apps / flows they are considered makers as well.

**Comment by Jenefer-Monroe** [comment]
No the **_number of_** fields just sum up where they are primary owner.
Perhaps this visual will help? 
![image](https://github.com/user-attachments/assets/33c0bc5c-0fa4-4ec5-82f9-8d009f881feb)

**Comment by asuka1103131** [comment]
Thank you for the very clear table!
If an app or flow is deleted, is the count reflected immediately?

**Comment by Jenefer-Monroe** [comment]
No its not immediately reflected. 
First the inventory needs to identify that the flow was deleted, which is done by the following flow which runs weekly: **_CLEANUP - Admin | Sync Template v4 (Check Deleted)_**

Then the column itself is a rollup field and so there is some delay on themselves of ~6-12 hours.
https://learn.microsoft.com/power-apps/maker/data-platform/define-rollup-fields

**Comment by asuka1103131** [comment]
If a user is deleted, when will this be reflected, as I assume the flow or app is no longer owned by the user?

**Comment by Jenefer-Monroe** [comment]
If the user is deleted from Entra, they will remain in the maker table but get marked as orphaned by the following flow: 
CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

It will also mark all the users objects as orphaned.

**Comment by asuka1103131** [comment]
If marked, will the table owner for app flow still have a value in it?

**Comment by Jenefer-Monroe** [comment]
It will yes, in the situation described here. 
It will be blank if the user is already deleted from the entra before the app/flow is inventoried.

**Comment by asuka1103131** [comment]
Is there any way to notice that the owner of a registered app/flow is no longer in possession?

**Comment by asuka1103131** [comment]
I want to delete an app that has no owner. Is there a way to notice it?

**Comment by Jenefer-Monroe** [comment]
Yes you can use the Manage Permissions app, and look at the orphan tab there for both cloud flows and canvas apps.
![image](https://github.com/user-attachments/assets/492f0e64-044d-4df2-92b0-fd5d69c64701)

**Comment by asuka1103131** [comment]
Are you managing with flags?

**Comment by Jenefer-Monroe** [comment]
Sorry I don't follow your question.

**Comment by asuka1103131** [comment]
We look at the CoE table and create our own flow.
We envision something that would notify the administrator for apps that no longer have an owner.
So I'd like to know if there is any movement that would trigger the activation.

**Comment by Jenefer-Monroe** [comment]
We do have a process for orphaned objects, yes. 
You can read about it here: [Cleanup for orphaned resources](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#cleanup-for-orphaned-resources)
And here are the setup instructions: [Set up clean-up for orphaned objects](https://learn.microsoft.com/power-platform/guidance/coe/setup-orphan-components)

**Comment by asuka1103131** [comment]
I am aware that there was a delete flag on the app and flow, but is there one on the user side as well?

**Comment by Jenefer-Monroe** [comment]
Sorry I dont understand your question.

**Comment by asuka1103131** [comment]
Is there some sort of delete flag on the Maker table?

**Comment by Jenefer-Monroe** [comment]
When a maker is deleted from Entra we mark them as orphaned. So there is a field called **_Maker Is Orphaned_**

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
