### ISSUE TITLE
[CoE Starter Kit - BUG]  Power BI Connector Deep Live DashBoard

### ISSUE THREAD

**Issue by mancgianni74** [microsoft/coe-starter-kit#8746]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Power BI Dashboard Connector Deep Live does not consider some used connector in a production Environment. 
Could be a Bug in Power BI DashBoard or Daata model or there is a specific reason ?
![Connectors](https://github.com/user-attachments/assets/e5271a4c-eb40-428d-815a-6edf40d1f025)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Power BI Connector Deep Live Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Access to Power Bi DashBoard Connector Deep Live
2. Filter on specific Environment Name
3. Filter the first Deleted on False
4. Filter the second Deleted on False

**Comment by Jenefer-Monroe** [comment]
There was an issue in the data model trying to show both objects on one visual and so this was broken out into two visuals later. 
On your next upgrade you will see the following two screens in PBI instead
![image](https://github.com/user-attachments/assets/9d6b24a1-47b4-4d64-ac33-0af9c8f14a66)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
