### ISSUE TITLE
How fill App Last Launch and Flow Last Run?

### ISSUE THREAD

**Issue by Tomozo-No1** [microsoft/coe-starter-kit#8749]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Admin | Sync Template v4 (Apps) and Admin | Sync Template v4 (Flows) collects the last usage date, but it does not. 
I used it at 17 o'clock on 8/1, but it was not updated. Why?
<img width="635" alt="31" src="https://github.com/user-attachments/assets/06400f5c-086c-4891-a473-b093e195c65c">
<img width="636" alt="32" src="https://github.com/user-attachments/assets/dc61e133-2721-4333-bced-a1e904409533">

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024/6

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Apps),Admin | Sync Template v4 (Flows)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We do not fill the **_Flow Last Run_** column today. It is there in preparation for a future feature. 

For **_App Last Launch_**, you need to setup another solution area. Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http). 

Note we are shipping with another API option for Last Launch soon as well. See [Integrate new audit log methodology into the kit for API reduction](https://github.com/microsoft/coe-starter-kit/issues/8482)

**Comment by Tomozo-No1** [comment]
For App Last Launch, you need to setup another solution area. Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http).

I tried setting it again, but it was not displayed.
What should I do in this case?

**Comment by Jenefer-Monroe** [comment]
1. Did you validate that the flows you turned on are running and passing? 
2. Note also that this does not go back in time it only starts to collect launches from the time you turn on the flows. 
3. The flow also only collects launches for canvas apps (not MDA)


Please boot some sample canvas apps and then see if they get their last launched gets flagged after the next run of **_Admin | Audit Logs | Sync Audit Logs (V2)_**

**Comment by Jenefer-Monroe** [comment]
Once you do the above and validate that the flows are working for you, you can go load older data with this helper flow:
[How to get older data](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#how-to-get-older-data)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
