### ISSUE TITLE
How to setup quarantine processes

### ISSUE THREAD

**Issue by Tomozo-No1** [microsoft/coe-starter-kit#8750]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Admin | Quarantine non-compliant apps.
Is there a Dataverse to see what the criteria for non-compliance will be?
Can I add criteria?
How do I do that?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024/6

### What app or flow are you having the issue with?

Admin | Quarantine non-compliant apps

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, here is the article we have describing how to setup the quarantine processes: [Set up app quarantine components](https://learn.microsoft.com/power-platform/guidance/coe/setup-quarantine-components)

In it you will see the environment variable we offer to configure the number of days of non-compliance
![image](https://github.com/user-attachments/assets/aca91993-f5b2-4dbf-9a53-7a06dd650268)

Please review the article and let us know if you have any questions remaining.

**Comment by Tomozo-No1** [comment]
I don't know what the standards of compliance are. Is there an article somewhere?
What are the criteria for non-compliance?

**Comment by Jenefer-Monroe** [comment]
I'm not sure what you mean by standards of compliance. 
But the above (after x days of non-compliance) references our compliance feature: 

[Whats in the compliance components](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#compliance-processes)
[Set up Developer Compliance components](https://learn.microsoft.com/power-platform/guidance/coe/setup-governance-components)
[Process sample](https://learn.microsoft.com/power-platform/guidance/coe/example-processes)

Hope that helps

**Comment by Tomozo-No1** [comment]
What items should I check when banning compliance?
Is there a page that describes it somewhere?

**Comment by Jenefer-Monroe** [comment]
Sorry I dont follow your question. To setup compliance you can follow these instructions [Set up Developer Compliance components](https://learn.microsoft.com/power-platform/guidance/coe/setup-governance-components)

It will walk you through any options we offer in the setup wizard.
