### ISSUE TITLE
Can you manually trigger the archival processes?

### ISSUE THREAD

**Issue by Tomozo-No1** [microsoft/coe-starter-kit#8751]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

 Admin | Inactivity notifications v2  (Start Approval for Apps) Can I manually do the same thing
In my own way, I think I will use the PowerPlatform admin View.
I don't know how to operate it.
If so, please let me know.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024/6

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2  (Start Approval for Apps)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately no there is no manual flagging for the archival processes.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
