### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Power Apps User Shared With

### ISSUE THREAD

**Issue by GauriWani11** [microsoft/coe-starter-kit#8754]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are using the Jun Month COE version 4.32.2.

Issue:
Flow “CLEANUP HELPER - Power Apps User Shared With” has been failed.
This is the child flow, triggered from the parent flow. "CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)"

Error Message: (Please find the attached error screenshot)
Unable to process template language expressions in action 'Tenant_Has_Guests'.
cannot be evaluated because property 'admin_grouphasguestusers' doesn't exist.

![CLEANUP HELPER - Power Apps User Shared With](https://github.com/user-attachments/assets/35f0ff26-2ca1-46f1-9c91-fa2781d28de4)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Go to the solutions: Center of Excellence 
2. Go to cloud flows
3. Search for CLEANUP HELPER - Power Apps User Shared With
4. Click on Run

**Comment by Jenefer-Monroe** [comment]
This implies that you do not have the Tenant user (meaning a user for when apps are shared with everyone) correctly configured. 
Please run **_CLEANUP - Admin | Sync Template v3 (Orphaned Users)_**, that should clean it up for you.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
