### ISSUE TITLE
[CoE Starter Kit - QUESTION] Identifying Flow and Email Recipients for Environment Expiration Notifications

### ISSUE THREAD

**Issue by Kebo-ard** [microsoft/coe-starter-kit#8756]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

In the CoE Starter Kit, there is a feature that checks daily if an environment has expired or is nearing its expiration date. If the environment is close to expiration, an email is sent to notify about the upcoming deletion unless an extension is requested.

For reference: https://learn.microsoft.com/en-us/power-platform/guidance/coe/env-mgmt#process-description

1. What is the name of the flow responsible for this daily check and email notification?
2. Who are the recipients of this email? Specifically, do both the environment admins and the owner receive this notification, or is it limited to certain roles?

Thank you for your assistance!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello this is done with the **_Env Request | Cleanup_** flow. 
You can find the list of flows used in this solution area in [Set up environment request components](https://learn.microsoft.com/power-platform/guidance/coe/setup-environment-components)
![image](https://github.com/user-attachments/assets/f593b932-9a69-42ac-9c02-fd4e254b4617)

The email is sent to to only the environment owner who you enter here in the request app
![image](https://github.com/user-attachments/assets/79a7b6a2-7dbd-45e0-a990-f789916d092f)

Hope that helps!

**Comment by Kebo-ard** [comment]
Thank you for the response. I asked this question because I’m considering the possibility of notifying the Admins as well about environments scheduled for deletion, to keep them informed. This might be a nice-to-have feature for the future.

**Comment by Kebo-ard** [comment]
Yes, I mean the CoE Admins. Thank you for the guidance. I’ll follow the steps to customize the emails and include the CoE Admins in the CC field. This will ensure they are notified about environment deletions.

**Comment by Jenefer-Monroe** [comment]
You're quite welcome!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
