### ISSUE TITLE
[CoE Starter Kit - QUESTION] Impact of Installing CoE Starter Kit and ALM Accelerator on App Sharing Capabilities

### ISSUE THREAD

**Issue by Kebo-ard** [microsoft/coe-starter-kit#8758]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have recently installed the CoE Starter Kit and ALM Accelerator in our tenant. Following the installation, I observed that we are unable to share apps with "Everyone." When attempting to do so, we receive the following prompt:

"The ability to share with everyone is restricted to specific admins."

Could you please clarify if there are any effects or restrictions introduced by the CoE Starter Kit and ALM Accelerator that might impact app sharing capabilities? Specifically, does the installation of these solutions modify or restrict sharing settings for apps across the tenant?

Any insights or recommendations on how to resolve this issue would be greatly appreciated.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.32.2

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. I presume the timing matching with the ALM Accelerator is coincidental. 

There are admin settings to limit sharing who can share with everyone. 
For unmanaged environments you will need to use a power shell command to configure this.
Please see [limit sharing with everyone](https://learn.microsoft.com/power-platform/guidance/adoption/secure-default-environment#limit-sharing-with-everyone)
Here is a video where Manuela walks you through how to do that: https://www.youtube.com/watch?v=HwlhndJhsYY 

If you are using Managed Environments there are further configuration capabilities for this. Please see [Limit sharing for Managed Environments](https://learn.microsoft.com/power-platform/admin/managed-environment-sharing-limits)

**Comment by Kebo-ard** [comment]
Thank you for the clarification. I understand now that the issue is related to tenant-wide sharing settings and not directly caused by the CoE Starter Kit or ALM Accelerator.

Thanks for your help!

**Comment by Jenefer-Monroe** [comment]
You are quite welcome. I'll go ahead and close then but do feel free to open new issues in the future as needed.
