### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Portals) failure

### ISSUE THREAD

**Issue by gvanderven** [microsoft/coe-starter-kit#8759]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We've been receiving daily notifications about the 'Admin | Sync Template v4 (Portals)' flow failing for a particular portal. The portal in question is the 'Event Management' portal, as part of D365 Customer Insights.

The error occurs on the 'Parse Inventory - New Portals' action due to the "Portal_NonUnique" value being null. Investigating the flow shows that the data returned on the 'List Inventory Portals' action does indeed not include the "admin_portalwebsiteid" which is mapped to "Portal_NonUnique". It does however return an "admin_portalid", but I'm not sure if that's the same thing.

### Expected Behavior

Either the flow is expecting an incorrect property when collecting the portal data or should be able to handle these kind of exceptions. As to prevent further notifications about failure from being sent.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Admin | Sync Template v4

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by gvanderven** [comment]
Thanks for the explanation and suggested fix @Jenefer-Monroe.

I've deleted the rows with an empty Power Pages Unique ID and I'll let you know whether this fixed the issue.

**Comment by Jenefer-Monroe** [comment]
Wonderful. This has worked for others so I feel confident, but please do reach out and let me know. I love to hear good news too :)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
