### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Flow Action Details) Append HTTP reached the limit

### ISSUE THREAD

**Issue by santiareh** [microsoft/coe-starter-kit#8761]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hey everyone,

I've been experiencing an issue with the Admin | Sync Template v3 (Flow Action Details) flow for a while now and finally got to where the issue is coming from. 
The 'Append http action' is failing: The number of array items in variable 'ActualFlowActionDetails' reached the limit: maximum '100000' and actual '100000'. Even though I found the error I am not exactly sure where it is coming from, potentially having too many flows? Any help would be appreciated. Thank you!

![image](https://github.com/user-attachments/assets/9c32b968-72d6-45e4-ae2e-3001a908402c)

![image](https://github.com/user-attachments/assets/6cae8953-9f1a-4613-9c97-44be6d8c47d6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flow Action Details)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately this is just a product limitation on array size. The only workaround we have thought of is to do this on a per-flow instead of per-envt level, and that would blow out the API hit even more. 
We do have this on the backlog to consider but just have not been able to fund yet: https://github.com/microsoft/coe-starter-kit/issues/6819

**Comment by santiareh** [comment]
Aah I see, makes perfect sense. Thank you Jenefer and apologies I was not able to find that other issue before posting.

**Comment by Jenefer-Monroe** [comment]
No problem at all!
