### ISSUE TITLE
[CoE Starter Kit - QUESTION]Power BI report

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#8762]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

Which one gives correct data about Connectors are used in Apps and Flows in Power BI report?

Thank you

### What solution are you experiencing the issue with?

None

### What solution version are you using?

March  2024

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I'm not certain about the state of the PBI's from the March release. But currently you can find this information in the following two pages
![image](https://github.com/user-attachments/assets/d478054e-7d45-45ff-89dc-c3291e458c48)

**Comment by lingutla123** [comment]
How can i export the data?

**Comment by Jenefer-Monroe** [comment]
I dont know if PBI has export capability, The underlying data here is stored in the **_Connection Reference_** table in the Core components. So you can go download that table and explore it.

![image](https://github.com/user-attachments/assets/b7039f87-e397-4949-b48c-c3cbef2215ae)

**Comment by lingutla123** [comment]
Power Platform Admin View gives correct information?

![image](https://github.com/user-attachments/assets/836ad67a-63ca-4291-af21-9f109413c19b)

**Comment by Jenefer-Monroe** [comment]
It does yes, but I think exporting from there would be difficult which is why I pointed you to the other table. 
Hope you can find what you need!

**Comment by lingutla123** [comment]
Okay. Thank you Jenefer.
