### ISSUE TITLE
Admin | Sync Template - page size error

### ISSUE THREAD

**Issue by hikmatune** [microsoft/coe-starter-kit#8763]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

All admin Sync Template flows have a bug with the page size set to 100000, where it only accepts 1000 page size. Please fix this:

### Expected Behavior

Flows should not fail

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33.5

### What app or flow are you having the issue with?

Admin | Sync Template v4

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Flow runs failing

**Comment by Jenefer-Monroe** [comment]
Sorry I dont follow you question. We do have pagination at 100,000 is that what you mean?

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
