### ISSUE TITLE
[CoE Starter Kit - BUG] COE starter kit Flows table "Flow last Run On" column is blank

### ISSUE THREAD

**Issue by RajanPatel81** [microsoft/coe-starter-kit#8764]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I want to get last execution time of flow in my environment. I dont see any Power Automate connector that gives this information. Also there is a column in COE starter kit Flows table with column name "Flow last Run On". But I see the column value is blank. How can we fill data in this column.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Table

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1 Open https://make.powerapps.com/environments/d1005663-10cc-e8f1-b1c5-711e00d0f050/solutions/fd140aaf-4df4-11dd-bd17-0019b9312238
This environment has COE toolkit installed
2 Open Table
3 Edit Flow table
4 Check value on "Flow last Run On" column. This column is blank for all the rows.
5 How can we fill this column .

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
