### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Add Maker to Group fails when trying to add user to Entra ID group 

### ISSUE THREAD

**Issue by jephal** [microsoft/coe-starter-kit#8767]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When the "Admin | Add Maker to Group" flow gets the users within the Entra group the filter cannot find it in the group. so it passes the condition to then add it to the group. Then when attempting to add the user to the Entra group, it fails with 

    "code": "Request_BadRequest",
    "message": "One or more added object references already exist for the following modified properties: 'members'."

I have manually checked the input from the "List group Members", and the person is not in there, so the filtering seems to work fine, therefore I do not know why it fails to add the user. Though when I check the Group in Azure, the person is in there. Does the "List group members" connector not get the whole group? 

This has happened every time the flow runs recently, but from all the failed runs I can find the users in the Azure group. 

I have checked that the connectors have the same group Ids

### Expected Behavior

When the flow gets members in the azure makers group, it should see that the user is already in there, and not attempt to add. Or if the user is not in the list, it should be able to add the user. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Admin | Add Maker to Group

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

In Power Platform CoE Environment, when a new user is added to the maker table, it triggers the flow, which fails. 

### Anything else?

![image](https://github.com/user-attachments/assets/e56b0c0d-ca04-4d5a-a5f5-30ca2dc5983d)
![image](https://github.com/user-attachments/assets/ce786276-3b6c-48c0-8741-99e52c5c1a92)
![image](https://github.com/user-attachments/assets/efbd58c8-d37a-4486-8f59-04a8078cda83)

**Comment by Jenefer-Monroe** [comment]
It looks like you hit a race condition where this flow was running 2+ times at the same time for this user. 
Please validate the desired user is now in the group as desired.

**Comment by jephal** [comment]
The user is added to the group as it should yes, but in the flow runs there is no double triggers. Could there be other flows or something else causing the situation? I have no problem with the outcome, but it would be nice to not have the failure notifications

**Comment by Jenefer-Monroe** [comment]
Yes I hear you. We had to chose between an occasional race condition failure and masking failures. 

Note that the product team has taken these welcome mails in natively and so they do have a much better solution than us in the starter kit :)
[Enable maker welcome content](https://learn.microsoft.com/power-platform/admin/welcome-content)

**Comment by jephal** [comment]
thank you for the quick responses Jenefer :)
