### ISSUE TITLE
blank owner 

### ISSUE THREAD

**Issue by gghaleb** [microsoft/coe-starter-kit#8768]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

So i have a few client's app/flows with blank owner, can we safely say they deleted the owner from their organisation instead of deactivating? Will his apps be automatically considered orphaned, and what 's the difference between these and other orphaned objects where the owner is known? will the orphaned process flows consider objects as "no manager found" and ask the environment manager to decide what to do with them? thanks

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

June 2024

### What app or flow are you having the issue with?

none

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We get the owner information from O365User connector, so if an object is inventoried after the owner are already removed from Entra, then this information will be blank. IF they are removed after the object is inventoried, you will see the old owner.

In this case we dont know who the user was or who their manager was, and so it will be sent to the CoE Admin to address.

**Comment by gghaleb** [comment]
as always, Thanks Jenefer!
