### ISSUE TITLE
[CoE Starter Kit - BUG] App and Flow inactivity flows resends approval if not answered within the current week

### ISSUE THREAD

**Issue by jephal** [microsoft/coe-starter-kit#8769]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The cleanup approval for flows and apps, when the owner doesnt exist anymore is sent to the individual administartor. Though, as I had 700 of them, I didn't have time to clean all of them within the week, and for the ones I didnt respond to I got sent another approval. 
![image](https://github.com/user-attachments/assets/c8afa5df-9c2b-4451-84ac-26dad3499626)

I can see it has also created a duplicate row in the Archive approvals table. This is something that could spiral with reminder emails etc. 

This has also happened for other users (non-admins) who didnt answer the approvals the first week. 

### Expected Behavior

Second week, only a reminder is sent, not a new approval

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.24

### What app or flow are you having the issue with?

App and Flow Inactivity Notifications Clean Up

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Yes you are correct, probably a better pattern could have been put in place. 

At this time we aren't planning to redo the process though as the product is working to support it natively from the Power Platform Admin Center, which will be fabulous.

**Comment by Jenefer-Monroe** [comment]
Here is some information about that in [CoE Starter Kit vs Managed Environments](https://learn.microsoft.com/power-platform/guidance/white-papers/managed-environment-activation#coe-starter-kit-vs-managed-environments)

**Comment by jephal** [comment]
Thank you :)
