### ISSUE TITLE
[AA4AM] - Replace button functions with component properties

### ISSUE THREAD

**Issue by devkeydet** [microsoft/coe-starter-kit#877]
In the canvas app, we currently use an approach people often call "button functions" for code reuse.  This is no longer necessary now that we have behavioral enhancements to components:
https://powerapps.microsoft.com/en-us/blog/enhanced-component-properties/
Rewrite all "button functions" as user defined functions in a component.

**Comment by mikefactorial** [comment]
Closing this out as this will likely be part of the larger redesign of the UX
