### ISSUE TITLE
[CoE Starter Kit - QUESTION] TABLE Connection Reference Identities

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#8771]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello everyone! How are you?

I would like to know if I can safely delete all the records in this table?

I have noticed that I have over 1.2 million records and when I try to create a report, I can't.

If I delete all the records in this table, will the inventory recreate the records that are still in the environments? Or if you do this, will it break some other automation, perhaps causing an error in another one.

My idea is to delete everything, and the inventory will create new records that are part of the current scenario.

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. We add/remove records from this table in the sync flows on a per object basis as shown here.
![image](https://github.com/user-attachments/assets/00676bec-c651-4e01-b000-4650dfa0622f)

These should be kept clean for you. 
Ex: If you remove a connector from a flow, the flow is shown as edited, it will go through the above and have the connector removed from this table. 

If you remove all the records from this table they will re-populate but only for apps / flows that go through inventory.

**Comment by ClaudioRWS** [comment]
@Jenefer-Monroe 

when you say: 
"If you remove all the records from this table they will re-populate but only for apps / flows that go through inventory."

Does this mean that all rooms that are marked for inventory will be filled again?

![image](https://github.com/user-attachments/assets/d9dced47-acbf-4e87-99ce-0dba7917446d)

**Comment by Jenefer-Monroe** [comment]
No sorry I'm not referencing that field. 

Basically to avoid needless API calls, we dont inventory every app/flow every day. We only inventory those that have been modified. 
You can see that in **_Admin | Sync Template v4 (Flows)_** for example. 
the point of this flow is mainly to see what apps/flows should go through inventory. 
![image](https://github.com/user-attachments/assets/c5cb4185-2993-4e3e-8336-13cd0c3b7380)

In that loop we call **_SYNC HELPER - Cloud Flows_** which, as shown in the picture form my previous response, is where you get the connection references table filled.

So if you delete the connections for an old flow that is no longer being modified, then it will not repopulate. 
Where if you delete the connections for a flow that is still being modified, it will repopulate the next time **_Admin | Sync Template v4 (Flows)_** identified it as needing inventoried, and sends it to **_SYNC HELPER - Cloud Flows_**

I hope that all makes sense.

**Comment by ClaudioRWS** [comment]
got it!

Muito obrigado pela ajuda!
