### ISSUE TITLE
[CoE Starter Kit - BUG] Env Request | Cleanup : Failed to delete an environnement

### ISSUE THREAD

**Issue by tocri** [microsoft/coe-starter-kit#8772]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello

I have an environment that was created by user and the expiration date is outdated. each day, the flow gives me this error :  

**"The delete reason was null or invalid. Valid values are: User, Tenant, Expiration, LinkedResourceDeleted, Manual, CommonDataServiceMigration, Application, Service, TeamDeleted, ConnectedGroupDeleted, CreateFailed, InactivityThreshold, DeletedByTenantPolicyEvaluation, InconsistencyDetection**"

![image](https://github.com/user-attachments/assets/3fc63648-5e28-4890-8121-c8d0c2da3392)

the initial request :

<img width="853" alt="image" src="https://github.com/user-attachments/assets/c894db94-5297-47f1-a0f8-ed3b1535d012">

Any idea ? How can i help you ?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Env Request | Cleanup

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
It looks like the product changed what its expecting here. I tried a more current API Version and it did not fix unfortunately
Here is the error received: InvalidOrMissingDeleteCode

I'm afraid you'll need to contact product support and I'll also post something internally.

Before contacting product support please create a flow outside the context of the CoE. Its as simple as the only shown here. 
Just the single action, select the envt, and have the API version of 2022-05-01 (although it also repros for more current versions)

![image](https://github.com/user-attachments/assets/7f07c5d7-5a65-4529-b4f0-66888f5a5811)

**Comment by tocri** [comment]
Thank you. I have added this task to my bucket list for tomorrow. Thanks as usual for your quick reply.

**Comment by tocri** [comment]
If I add the delete environment action, the API version is 2018-10-01 and if I try to delete an environment, it says "not found" after a few seconds but in fact the action does delete the environment with this version of the API. 

I tried 2 times and each times the environment is deleted. 

![image](https://github.com/user-attachments/assets/c262f585-55a5-48da-834b-95382ef90f9b)
![image](https://github.com/user-attachments/assets/b8cbdfca-2e3c-4435-9f74-34a28b247ffc)

**Comment by Jenefer-Monroe** [comment]
Thanks yes we used to use that version but bumped it forward at the product teams request, I dont recall why. 
I've created an internal incident too but your customer report will help bump it in priority.

**Comment by tocri** [comment]
Ok but what can i say to the support team. "The  flow env Requsest | cleanup" doesn't work because the API that is use for deleting an environment is buggy ? " Are they going to tell me to see this with you?

**Comment by Jenefer-Monroe** [comment]
Before contacting product support please create a flow outside the context of the CoE. Its as simple as the one shown here. 
Just the single action, select the envt, and have the API version of 2022-05-01 (although it also repros for more current versions as well)

![image](https://github.com/user-attachments/assets/7f07c5d7-5a65-4529-b4f0-66888f5a5811)

**Comment by tocri** [comment]
Sorry for the delay. A lot of work since the holidays. As you thought, it doesn't work. I'll create the post in a few hours. Any recommendations that will be useful to the support team that you can provide me?

**Comment by tocri** [comment]
Ticket is created. Fingers crossed

**Comment by lsavard** [comment]
Hi, we are having the same issue. Any news about it ? Thanks.

**Comment by tocri** [comment]
@lsavard @Jenefer-Monroe I've opened a ticket to Microsoft and an engineer is on this. She tried to contact @Jenefer-Monroe on teams without success but i think she is on vacation.

I'll keep you posted

**Comment by tocri** [comment]
Ok i've an answer :

"They have found this to be a bug which seems to be affecting API versions, and they have created an internal bug ticket to work on it. There is currently no ETA as to when the fix will be developed and deployed

In the meantime, they have suggested that you use the API version 2018-10-01 for now since the environment does get deleted using that API even though an error is thrown."
