### ISSUE TITLE
[CoE Starter Kit - QUESTION] what are the differences between the May 2023 version of Core components and the July 2024 core components version?

### ISSUE THREAD

**Issue by Vignes29** [microsoft/coe-starter-kit#8774]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

what are the differences between the May 2023 version of Core components and the July 2024 core components version?
I want to know the difference between the two versions as I am analyzing the changes before implement the latest version. Also studying the benefits of latest version. I see the approach is -now different from the May 2023 version.
I cannot follow the code when I have two versions side by side.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

May 2023

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello. We do our best to track the work in each release with tags on work items in GitHub. You can review the changes by looking at the change log of the release: 
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-July2024
![image](https://github.com/user-attachments/assets/a86d881f-7281-4f4d-a8bc-b13bc969d02a)

**Comment by Jenefer-Monroe** [comment]
We do have an update for August we are working on now that will ship once we get testing sign off from a partner team. 
You can see the full list of what we are fixing for August here: https://github.com/orgs/microsoft/projects/195/views/59
And note that in particular these two big issues are finally addressed in the changes:
https://github.com/microsoft/coe-starter-kit/issues/8016
https://github.com/microsoft/coe-starter-kit/issues/8482

**Comment by Jenefer-Monroe** [comment]
Further we have office hours where we present the changes for each month:

### Office Hours
Please consider attending our monthly office hours. We talk about new features, upcoming changes, and spend most of the time answering your questions. 
More information:
Join the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours) held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
Click here to download the calendar file to add to your calendar: [Calendar file](https://aka.ms/coeofficehours/ics)

**Comment by Vignes29** [comment]
> Hello. We do our best to track the work in each release with tags on work items in GitHub. You can review the changes by looking at the change log of the release: https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-July2024 ![image](https://private-user-images.githubusercontent.com/89584709/355800932-a86d881f-7281-4f4d-a8bc-b13bc969d02a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTA0MjIsIm5iZiI6MTcyMzA5MDEyMiwicGF0aCI6Ii84OTU4NDcwOS8zNTU4MDA5MzItYTg2ZDg4MWYtNzI4MS00ZjRkLWE4YmMtYjEzYmM5NjlkMDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYzEwNGIyMTRiZTgyMjAyZDgwNDFiZGIwNTMzNGVlYTdmZjhlOTdlYTg3MmUzODM5NWM2Y2QzYTgxZjE0OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wXIBffLrMWoziiz8DA_hFLd-vp_N9RpSwLBw1Io3Rxk)

Thank You for this information, I would also like to know the benefits of updating to the latest version?

**Comment by Jenefer-Monroe** [comment]
The list of changes are above and so those really describe the benefits. 
Personally I think this is the most beneficial work from that month: https://github.com/microsoft/coe-starter-kit/issues/1083

You may want to wait for the August release which has two much larger benefits.
https://github.com/microsoft/coe-starter-kit/issues/8016
https://github.com/microsoft/coe-starter-kit/issues/8482

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
