### ISSUE TITLE
[CoE Starter Kit - CoE Admin Command Center] The value 'Preview builds for testing' cannot be converted to a date or time value.

### ISSUE THREAD

**Issue by sabrineayadi** [microsoft/coe-starter-kit#8775]
###
Dears,

After upgrading to the July version, this error message is displayed. Does anyone have any suggestions or ideas on how to resolve this issue?

Thank you!

- [X] I have checked and confirm this is a new bug.

### Describe the issue

<img width="878" alt="error coe starterkit" src="https://github.com/user-attachments/assets/d373b5b8-0d14-47a9-9d3f-f45197d6ac33">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting. This is known and fixed for the August release. 
https://github.com/microsoft/coe-starter-kit/issues/8627
