### ISSUE TITLE
[CoE Starter Kit - BUG] Video thumbnails not showing in MDA Video Hub New

### ISSUE THREAD

**Issue by dd767** [microsoft/coe-starter-kit#8776]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

In the new Video Hub page, Youtube videos do not show any thumbnails on the Main page, they only display a generic image.

The thumbnails appear OK once you click "View" to open the item.
The thumbnails appear OK in the old Video Hub (deprecated) canvas app.
Once you go back to Main page, thumbnails are not visible.
All video links are created via the Nurture Apps - Admin page.

![videohub](https://github.com/user-attachments/assets/3a236d8a-14d0-4d45-b0de-b0702ee4da9f)

### Expected Behavior

Show (external/Youtube) video thumbnail previews as in the old deprecated Video Hub canvas app.

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.17 installed in April 2024

### What app or flow are you having the issue with?

Video Hub New

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Open Nurture Apps - Admin
2. Create a new video item using external (Youtube) URL
3. Assign platform, difficulty, title, description, etc.
4. Save & Close
5. Open Nurture Apps - Maker
6. Open Video Hub Page
7. Video has no thumbnail in the main page
8. If you click "View" to open the item, the thumbnail is visible
9. Go back to main view, thumbnail is not visible

**Comment by Jenefer-Monroe** [comment]
Looks like the screenshot expects the video id to always be the last 11 characters and its not
![image](https://github.com/user-attachments/assets/3a8cef10-5ff8-41f5-83be-b34faafb4ad7)

Here are two sample urls, we need the 11 chars after ?v=
https://www.youtube.com/watch?v=WDHdo-kGCr4
https://www.youtube.com/watch?v=exxos1gaLsg&list=PLTyFh-qDKAiFUEgsXoQ9E-LJu4lcS0iMI

Let me see if I can fix this quickly for August.

**Comment by dd767** [comment]
This is the URL we used for the first video (PowerBI for beginners)

https://youtu.be/NNSHu0rkew8

I got it by finding the video on YT, right-click the video, select "copy video URL" and paste it into Nurture Apps - Admin "Content URL" field for a new item.

Is there anything else from my side i can test/help you with?
It would be awesome if it gets fixed for the august release, as we're planning on upgrading COE anyway :)

**Comment by Jenefer-Monroe** [comment]
oh for you it was actually this that as the problem
![image](https://github.com/user-attachments/assets/a48e097c-77d5-459d-876e-8f9c3596cbdc)

As we only show the image when its a youtube video (not stream) which we identify with the url as shown here. 
![image](https://github.com/user-attachments/assets/af83a5e9-7b47-4b41-ba24-5ef8695bcbe8)

I've got a fix here for both cases almost ready.

**Comment by Jenefer-Monroe** [comment]
ok I have this local fixed including for your link for August.
![image](https://github.com/user-attachments/assets/30302257-9e85-4461-8fb0-192bfffcb7a2)

**Comment by dd767** [comment]
Thank you Jennefer!

**Comment by Jenefer-Monroe** [comment]
Happy to help. I really like this app :)

**Comment by dd767** [comment]
> Happy to help. I really like this app :)

yeah same here, we're exploring it currently quite a lot. Not sure if it's appropriate to ask 2 additional questions here, since it's not part of this bug, but...

- can we customize the main screen with company logo or custom text (instead of "Video Hub") or something similar?
- can the page (video hub new) be shared as standalone app/page and not part of the whole Nurture - Maker portal? (since we're not using the templates/app in a day/solution assessment parts)

**Comment by Jenefer-Monroe** [comment]
Thats one of the reasons we switched over to the MDA + Pages approach, its easier to customize! 

So yes you can create your own MDA that contains only the pages you want your users to reference. 
And you can customize the page as well although it will create an unmanaged layer and so you wont get new updates from us. So I might suggest creating a copy instead, and wait till we ship this :)

**Comment by dd767** [comment]
Jen, thanks for heads-up! One more though: what dataverse tables are used by the video hub? We need to grant users access only to those in order to use (per-app licenses for now) the page. Thanks!

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
