### ISSUE TITLE
[CoE Starter Kit - QUESTION] PIM Requirement for the Identity to set up the CoE-SK 

### ISSUE THREAD

**Issue by shidinh** [microsoft/coe-starter-kit#8777]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi - 

Previously, the documentation at https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#which-identity-should-i-use-to-install-the-coe-starter-kit had explicitly called out that PIM should NOT be enabled on the identity used to set-up the CoE-SK. 
However, the recent edits to the Wiki has taken that out. 
Can you please confirm if the set-up can be done with an user account that only gets Power Platform Service Admin privileges via PIM?

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Yes you still should not use PIM for this. The user identity running the flows needs to direct and permanent access to the role. 
![image](https://github.com/user-attachments/assets/5eb6e31d-48f3-4524-b3ea-80bdcca8acc8)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
