### ISSUE TITLE
[CoE Starter Kit - QUESTION] Update Multiple Versions

### ISSUE THREAD

**Issue by SysAdmin1258** [microsoft/coe-starter-kit#8778]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We installed Power Platform CoE Starter Kit version 2.77. It wasn't apparent to us at the time that there were monthly updates to be installed and that it was recommended that it be updated at least every 3 months. This information was discovered while researching an error we are getting. We are receiving emails stating "Flow maker [user@domain.com](mailto:user@domain.com) does not have permissions to perform Archive Approval". I have confirmed this user has the Approvals User role in the environment. We are not using security groups in this environment. I saw that there could be a bug (not sure which version). My concern is that we will run into more errors if we install updates since it has been more than a few months (years now) since the current version was installed. Is there anything that we should do in advance of the updates? Is there anything that we should consider before moving forward with that step?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.77

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Clean Up and Delete)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. It looks like you are on August 2021. Yes unfortunately you will likely not be able to upgrade smoothly from there, and I cannot comment really on the state of your kit and issues you are facing due to that age.
Likely you will just need to start fresh with a new install of the kit and the try to migrate in data from the old one as possible.
Sorry for the pain.

**Comment by SysAdmin1258** [comment]
Thank you for your guidance. We will work on reinstalling in a new environment and setup a maintenance plan.
