### ISSUE TITLE
[CoE Starter Kit - QUESTION] How is "the "Type" column populated in Power Platform Users table?

### ISSUE THREAD

**Issue by anttipajunen** [microsoft/coe-starter-kit#8779]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I'm seeing a small subset of Power Platform Users missing a value in the Type column. Which flow(s) are used to add a value to the column? Any specific diagnostics steps that I could take? I've checked that all these users are in Entra.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by anttipajunen** [comment]
Hmm are those app role assignment "types" and if there are no app role assignments, there is no type?

**Comment by Jenefer-Monroe** [comment]
We recently did a big set of changes on user types in the June / July timeframe. Objects in this list without type wont ever get cleaned up. 

Can you see if there is a duplicate entry for those users which has type? If so please just delete the untyped ones ,they were likely entered before this big chunk of work.

**Comment by anttipajunen** [comment]
It seems none of the untyped ones are duplicates. Can they still be deleted for a resync later?

**Comment by Jenefer-Monroe** [comment]
Yes they could. Or if there are few enough of them, you can go mark them as type **_User_** manually

**Comment by anttipajunen** [comment]
Got it. Thanks Jenefer!
