### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Portals) should catch null values for "Portal_NonUnique"

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#8783]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

My Portals sync template fails many times on each run because for some reason many of the portals have a null value in the "Portal_NonUnique" field and the parse step fails because it's expecting a string value and gets a null.  Can that be caught and handled somehow to prevent failure?

### Expected Behavior

Catch the null value and handle the case to prevent flow run failure.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.34

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Portals)

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Run the flow and it fails in 15 different environments in my tenant for this reason.

### Anything else?

![image](https://github.com/user-attachments/assets/ab08c108-f103-4eb0-bd33-6127999cc188)

**Comment by Jenefer-Monroe** [comment]
Hello. Likely something in the old sync flows added bad data and it was just not known until now as we changed to this set logic technique. 

Please go to the **_Power Pages Site_** table > Click edit to see all data > Add/Remove columns until you see the below
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/292196d3-0d52-4134-be06-1f43c048fa87)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc9846fd-2f42-44a4-81c2-a632fab12052)

Now filter to where there Power Pages Website ID - Does not contain data > Delete these records. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7698e381-4d67-4b26-ad24-a7a37af6686c)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/02046caa-6c18-42d2-a738-d722918ee886)

Then do the same for the Power Pages Unique ID column. 
Now the flow will pass and lets hold for a few days to make sure it doesnt return.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
