### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (AI Events)

### ISSUE THREAD

**Issue by bartsneary** [microsoft/coe-starter-kit#8784]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When running the Admin | Sync Template v4 (AI Events) flow, in the step that takes the full list of user ID's and pares it back to just the unique ones, can we also remove the nulls from that list completely?  The null value causes future steps to fail when it is iterated through.

### Expected Behavior

If the null value is removed from the list, the flow won't error anymore when running.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.34

### What app or flow are you having the issue with?

Admin | Sync Template v4 (AI Events)

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Run the flow.

### Anything else?

![image](https://github.com/user-attachments/assets/6b57c8cc-ca1e-49f3-8a96-e3c3691fa353)

**Comment by Jenefer-Monroe** [comment]
Hello, thank you for posting, this issue is tracked by https://github.com/microsoft/coe-starter-kit/issues/8729 and we hope to figure it out soon.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
