### ISSUE TITLE
[CoE Starter Kit - BUG] August 2024 Power BI .pbit files not working

### ISSUE THREAD

**Issue by declawson** [microsoft/coe-starter-kit#8786]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Trying to use the new .pbit files with the August release; PowerPlatformGovernance_CoEDashboard_August2024.pbit & Production_CoEDashboard_August2024.pbit but when I try and open in the PowerBi Desktop App I get the error 'Some of the tables have incomplete or no data'  Refresh Now which leads to a Load error of '2 queries are blocked by the following errors:'.
We cannot convert the value null to type Text.  for pretty much everything (ie. envs, power apps, flows, makers etc.)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.34

### What app or flow are you having the issue with?

Power BI Dashboards

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

I got the .pbit files from the CoEStarterKit.zip file that was pushed out again today about an hour ago with the August release files and got the same error

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
