### ISSUE TITLE
[CoE Starter Kit - QUESTION] App Catalog ＆ Maker-Environment Request

### ISSUE THREAD

**Issue by Tomozo-No1** [microsoft/coe-starter-kit#8787]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

App Catalog ＆ Maker-Environment Request are scheduled to be discontinued, is that true?
If so, may I ask when it is scheduled to end?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024/6

### What app or flow are you having the issue with?

App Catalog , Maker-Environment Request

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We switched from using Canvas Apps to using Model Driven Apps for these. The canvas apps are removed now, I think it was in July release. 

You can view the documentation to see the new apps you will use
[Environment Request Apps](https://learn.microsoft.com/power-platform/guidance/coe/core-components#environment-request-apps)
[Other Apps, App Catalog](https://learn.microsoft.com/power-platform/guidance/coe/core-components#app-catalog)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
