### ISSUE TITLE
Can I get Session details of apps from Starter Kit? If yes, how?

### ISSUE THREAD

**Issue by harsh-mehra-db** [microsoft/coe-starter-kit#8791]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,
I want to know if there is a possibility to check the app sessions from Starter Kit. Like how we get from Admin center where it says which app had how many sessions. 
Please do let me know if this is possible.
Thanks

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.29

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I think you are asking about getting usage information for Model Driven Apps. 
Unfortunately this is not possible today, no. The product team is working to deliver this feature but we do not have access to that yet as of today.

**Comment by harsh-mehra-db** [comment]
Hey
No, I am not asking about the usage of Model Driv
![image](https://github.com/user-attachments/assets/32200103-f2e3-47d8-aedb-ca208c696825)
en Apps but the sessions of Canvas Apps as shown in the screenshot attached.

**Comment by Jenefer-Monroe** [comment]
You can get the session count for canvas apps in the kit yes. It requires a service principal to be created though. 
Please see [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
