### ISSUE TITLE
[CoE Starter Kit - BUG] Orphan Flow/Permission App not inSync

### ISSUE THREAD

**Issue by Sinder88** [microsoft/coe-starter-kit#8795]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Continuation of Orphan Flow/Permission App not inSync #8719

So the flow ran again this morning and many of the previously orphaned flows are still coming through. see below images:
here is the email i receive:
![image](https://github.com/user-attachments/assets/b10a4ec7-c31e-495c-9f43-ec9c952595e9)

Here is what admin app is saying: 
![image](https://github.com/user-attachments/assets/1ea7ac65-9720-4e76-9bbf-8fb34f5abcfc)

I don't understand why its still sending emails on this one. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.21

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Parent)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
1. Is Christopher the correct person to whom you assigned the flow? 

2. Do you have unmanaged layers on either of these flows?
Request Orphaned Objects Reassigned (Child)
Request Orphaned Objects Reassigned (Parent)

3. Find the run associated with this flow, you can do this by adding "ManagerEmail" to the list of runs. When did it run? After you re-assigned?

4. Open the run, is the flow returned here?
![image](https://github.com/user-attachments/assets/2cec7b6a-1dae-473c-9750-50baf860c17b)

5. follow down to this switch statement, where does it go? 
![image](https://github.com/user-attachments/assets/c379661e-b82d-48b3-bf95-ce15d97e9c9a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Sinder088** [comment]
1. Yes
2. No
3. I found it, it ran after i changed the value in the permission app. 
4. I an see the value passed here: 
![image](https://github.com/user-attachments/assets/1bec4fd9-2a27-476c-a5e0-e3527ca43bbd)
5.It says timeout true so it doesn't go to the switch: 
![image](https://github.com/user-attachments/assets/947b0fb5-48f4-404a-86ad-bfa309492327)
