### ISSUE TITLE
[CoE Starter Kit - QUESTION] High dataverse usage of cat_CloudFlowRunsBase

### ISSUE THREAD

**Issue by OColak24** [microsoft/coe-starter-kit#8797]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

![chart](https://github.com/user-attachments/assets/7d08cc6f-e2b4-4a72-979d-48b0f8794067)

We have had a high utilisation of our dataverse capacities for about 2 weeks. According to the chart, table cat_CloudFlowRunsBase receives 3.5 GB more data every day. Where can we start to bring this back to normal levels?

Which processes clean up and fill the table?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello this is not a table the CoE Starter Kit made or uses. I dont have that table installed in any of my environments. 
Can you please go find it, and look at its dependencies? That should tell you what is populating and reading from it. 

![image](https://github.com/user-attachments/assets/7ffd51f6-3b58-4f42-bdbf-24484f10fa2d)

**Comment by OColak24** [comment]
We suspect that it is this table. No idea why the table is displayed in the Power Platform Admin Centre with the other name.

<img width="745" alt="image" src="https://github.com/user-attachments/assets/b028f377-b4d3-4ec6-a697-9da4de52941e">

**Comment by Jenefer-Monroe** [comment]
Please check the dependencies of that table to see what is writing to it.
