### ISSUE TITLE
[CoE Starter Kit - BUG] RSS feed not found

### ISSUE THREAD

**Issue by Service-WebDevPowerP** [microsoft/coe-starter-kit#8799]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Newsletter with Product Updates keeps failing with the error: RSS feed not found

This is under Newsletter with Product Updates Scope > List PowerApps Community Blog RSS feed items

The full eroror is:

{
  "status": 404,
  "message": "RSS feed not found.\r\nclientRequestId: 51db0d42-c6d6-425a-9bf7-07caf3d2b10e",
  "error": {
    "message": "RSS feed not found."
  },
  "source": "rss-uks.azconn-uks-002.p.azurewebsites.net"
}

### Expected Behavior

To produce Newsletter

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

3.18

### What app or flow are you having the issue with?

Admin | Newsletter with Product Updates

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Run the flow

### Anything else?

![image](https://github.com/user-attachments/assets/e092159b-f492-4953-aec9-e313ba794564)

**Comment by Jenefer-Monroe** [comment]
Hello. Yes the product team changed their RSS feed URLs. 
We have local fixed this for August: https://github.com/microsoft/coe-starter-kit/issues/8612

Thanks for posting.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
