### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Power Apps User Shared With flow failed for all environments

### ISSUE THREAD

**Issue by Olena-UMPQ** [microsoft/coe-starter-kit#8801]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

CLEANUP HELPER - Power Apps User Shared With flow failed for all environments at the same time with this error message:
![CLEANUP HELPER - Power Apps User Shared With](https://github.com/user-attachments/assets/e0f7e9f6-a0a4-4221-8418-6b9835d88828)

Action 'Tenant_Size' failed: Unable to process template language expressions in action 'Tenant_Size' inputs at line '0' and column '0': 'The template language expression 'if(equals(length(outputs('Get_Tenant')?['body/value']), 0), 0, coalesce(first(outputs('Get_Tenant')?['body/value'])['admin_groupsize'], 0))' cannot be evaluated because property 'admin_groupsize' doesn't exist, available properties are '@odata.type, @odata.id, @odata.etag, @odata.editLink, admin_powerplatformuserid@odata.type, admin_powerplatformuserid, admin_grouphasguestusers@OData.Community.Display.V1.FormattedValue, admin_grouphasguestusers'. Please see https://aka.ms/logicexpressions for usage details.'.

### Expected Behavior

CLEANUP HELPER - Power Apps User Shared With flow runs successfully.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Service version:13.0.23725.63 Client version:2407.2.20139-train

### What app or flow are you having the issue with?

CLEANUP HELPER - Power Apps User Shared With

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
This implies that your tenant user is not correctly setup. Please go run the following flow and ensure it passes: CLEANUP - Admin | Sync Template v3 (Orphaned Users)

**Comment by Olena-UMPQ** [comment]
Thank you for your reply! I've run CLEANUP - Admin | Sync Template v3 (Orphaned Users) and received following error:
InvalidTemplate
Unable to process template language expressions in action 'Group_hasGuests' inputs at line '0' and column '0': 'The template language function 'length' expects its parameter to be an array or a string. The provided value is of type 'Null'. Please see https://aka.ms/logicexpressions#length for usage details.'.
![orphaned users1](https://github.com/user-attachments/assets/b05255e0-0f96-4a8f-b5b7-68b506e54081)
![orphaned users2](https://github.com/user-attachments/assets/93b656ab-5d35-4b51-89e6-f1018a7c234f)
{  "error": {    "code": 400,    "message": "Invalid base url:'d2ebd3a9-1ada-4480-8b2d-eac162716601'",    "source": "usa002-004.azure-apihub.net",    "path": "choose[4]\\when[1]\\choose[1]\\otherwise",    "policyId": "",    "clientRequestId": "0a5977b3-2eeb-4ed8-9a18-7f78d1dcc4ce"  }}
I'm wondering if something should be here for Homepage URL:
![orphaned users3](https://github.com/user-attachments/assets/9cdcaa24-5023-4ccc-b002-acc2feb2b2b7)

**Comment by Jenefer-Monroe** [comment]
This usually happens when the **_HTTP with Microsoft Entra ID (preauthorized)_** connection is broken or misconfigured.
Please go to connections and make sure the connection for these is as follows (or your tenant equivalent if you are not a commercial tenant: https://graph.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f49797b8-0f48-4884-a026-2580bbc8b96f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a31b22b8-bc81-4d81-a5b7-80dc740f2b82)

Sometimes the product creates one of these connected to the envt and this will not work.

**Comment by Olena-UMPQ** [comment]
Thank you so much. You are amazing! I've updated HTTP with Microsoft Entra ID (preauthorized) connection and both flows run successfully. 
![orphaned users4](https://github.com/user-attachments/assets/7b66f21f-4ace-4533-9876-24428c25c2c1)
![orphaned users5](https://github.com/user-attachments/assets/b2c2968a-4c6e-4df6-807d-1ad3064a643e)
Appreciate your help always.

**Comment by Jenefer-Monroe** [comment]
Hurrah! Thanks for letting me know! I love getting good news.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
