### ISSUE TITLE
[CoE Starter Kit - BUG]  Power Apps Deep Dive : Shared users count getting 0

### ISSUE THREAD

**Issue by powerplatformgovernance** [microsoft/coe-starter-kit#8802]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

 Dashboard : Power Apps Deep Dive : Shared users count getting  Zero
![Shared with](https://github.com/user-attachments/assets/e0064b57-fef8-493b-92dc-5bdc06f0abd1)

### Expected Behavior

1. publish the dashboard 
2. Go to App Usage tab
3. look the column " Total Shared With"
4.  the value is zero for all the Power Apps

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

### What method are you using to get inventory and telemetry?

None

**Comment by powerplatformgovernance** [comment]
Understand, I would like to understand why the value of the column is Zero, even though the users are assigned to respective Power App

**Comment by Jenefer-Monroe** [comment]
These values are filled by the flows listed below. Please be sure they are running and passing.

Cloud Flows:
- CLEANUP - Admin | Sync Template v3 (Flow Shared With)
- CLEANUP HELPER - Cloud Flow User Shared With

Canvas Apps:
- CLEANUP - Admin | Sync Template v3 (App Shared With)
- CLEANUP HELPER - Power Apps User Shared With

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
