### ISSUE TITLE
[CoE Starter Kit - BUG]  Dashboard : Power Apps Adoption :  Month over Month change of app users and change of Launches getting as 0.00%

### ISSUE THREAD

**Issue by powerplatformgovernance** [microsoft/coe-starter-kit#8803]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Dashboard : Power Apps Adoption :  Month over Month change of app users and change of Launches getting as 0.00%
<img width="395" alt="MoM " src="https://github.com/user-attachments/assets/82f8d9c2-fc1f-42c9-9bc0-b78bc19196a7">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, these are calculated to show 0% growth unless there is growth. 

Take a look at your charts, likely the are showing less now (August) than last month (July)

![image](https://github.com/user-attachments/assets/97da74dd-543c-4f71-bd51-a5baf3836188)

**Comment by powerplatformgovernance** [comment]
![image](https://github.com/user-attachments/assets/b264dcaa-bb07-49c3-9566-a4d7622aece4)
Why we are nit getting the users over time the previous months . However makers are good MOM

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
