### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Upgrade Wizard - Error in button "Refresh dataflow for initial inventory"

### ISSUE THREAD

**Issue by fim34** [microsoft/coe-starter-kit#8805]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
Checked issue 7595,6042 and 7007 but not find the answer.
We created a new environment for test the other inventoring method with data export.
But in coe upgrade wizard i have this error "Échec de PowerQueryDataflows.RefreshDataflow : La fonction 'RefreshDataflow' une valeur non valide pour le paramètre 'groupIdForRefreshDataflow', car une valeur vide lui a été transmise là où elle n’était pas prévue. Assurez-vous qu’un argument valide est transmis à la fonction."

All Dataflow and json file in powerbi desktop are good and refresh.
![image](https://github.com/user-attachments/assets/73781418-962f-4d45-bae3-a3b1c45722a0)
The powerbi dashboard is also is partially filled like only information of environment.

All BYODL flow in core solution are on.
So what may be the cause for the error and I imagine linked with an incomplete dashboard

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

BYODL

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Create the storage account and add user role for acces
create link  to the storage account in power platform admin (wait 7 day)
create the environment and power bi workspace
Configure the dataflow with web api endpoint and storage account url
Install the core solution in the environment and set up the coe upgrade wizard

**Comment by Jenefer-Monroe** [comment]
Hello. It is not recommended at this time that new users try to spin up the old Data Export (BYODL) system. 
We are actively working with the product team on the new Data Export system and it will not use these same tools so any struggling you do to get this setup will be wasted effort.

Please come to office hours to hear more about this work.

### Office Hours
Please consider attending our monthly office hours. We talk about new features, upcoming changes, and spend most of the time answering your questions. 
More information:
Join the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours) held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
Click here to download the calendar file to add to your calendar: [Calendar file](https://aka.ms/coeofficehours/ics)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
