### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Pyksel** [microsoft/coe-starter-kit#8807]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Teams for Dataverse environment was deleted as per the governance flows. User requested it be restored and wanted to keep the environment so we've restored it and went through the BPF to approve the initial justification. The environment was again deleted the following week. How do we prevent this?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

None 

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Create a Teams for Dataverse environment
2. Reject the approval once it comes in
3. Let the environment get deleted
4. Restore the environment
5. Approve the original approval
6. Env will still get deleted the following week

**Comment by Jenefer-Monroe** [comment]
Here is the condition we check 
![image](https://github.com/user-attachments/assets/36e25f6a-4c6e-4037-aeba-83d08b4faf5d)

On the following query:
![image](https://github.com/user-attachments/assets/e7220cb7-358c-41e8-a335-7fabc4d01572)

In short it will be deleted if either of these are true for teams environments created 7+ days ago.
- **_Admin - Microsoft Teams Environment Status_** = Rejected
- **_Maker Requirement - Business Justification_** is blank

So likely you will need to put something in the **_Maker Requirement - Business Justification_** field.

**Comment by Pyksel** [comment]
Thank you Jenefer. The maker did put something in the Maker Requirement - Business Justification field and I do still see that justification in the Business Process Flow step under "Validate Maker Business Justification".

**Comment by Jenefer-Monroe** [comment]
Can you validate that your flow loos the same? It may be old or have unmanaged layers. 

Do you have the run available to view that deleted it the second time? 
If not, I'm afraid you may have to run it and see it get deleted to know where / why it is getting deleted.

**Comment by Pyksel** [comment]
Our flow looks the same and there are no unmanaged layers. We're on the July release of the CoE kit.

I do see the run available when it was deleted a second time under the 90 day review. It shows the following:
admin_environmentdeleted: false
admin_makerrequirementbusinessjusticiation: The justification is present here
admin_adminmicrosoftteamsenvironmentstatus: Approved

Looking at this more I believe what has occurred is that the environment was created on 5/6 and there has been 0 activity since so the env. was getting flagged & deleted for 90 day inactivity. If that's expected behavior for restored environments then I believe I have a better understanding, and this can be archived.  Thank you!

**Comment by Jenefer-Monroe** [comment]
Thank you for checkign! Yes I wondered if this wasnt happening over there. 

This side checks to see if there are any apps or flows in the envt and cleans them up as "inactive'. 

Appreciate your help in debugging!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
