### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Orphaned Users)

### ISSUE THREAD

**Issue by steph-ong98** [microsoft/coe-starter-kit#8808]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When we run this flow, it runs for 2 hours (compared to less than 5 mins) and it always ends up having a failure at the Tenant User Count. It worked for us in test but not in prod environment. We have four HTTP connects with Microsoft  (two are graph.microsoft, the other two directs us to another dataverse environment)
![image](https://github.com/user-attachments/assets/432337b3-88ec-454b-8128-436680db67f5)
![image (1)](https://github.com/user-attachments/assets/918d05d5-3cec-485f-89fe-fcdfe4f158a1)

Because of that we can't run the CLEANUP HELPER - Power Apps User Shared With, this is why we are still capturing the older data (not the latest version). 
We are wondering if there is a replacement for admin_totalshared_date, since we notice it has been removed. 

In addition, we realised that when we run Admin | Syn Template v4 (flows), whenever we run it manually sometimes, it skips the steps. As shown, in below screenshot. 
![image (4)](https://github.com/user-attachments/assets/fd59f1a4-52cc-47f0-8896-77921bad1f08)

### Expected Behavior

We expected for the CLEANUP - Admin | Sync Template v3 (Orphaned Users) to run successfully less than 5 minutes and therefore, for CLEANUP HELPER - Power Apps User Shared With to run successfully too. We also expect the data to the latest updated version. 
![image (2)](https://github.com/user-attachments/assets/5bd9c768-9d42-4a72-9fbd-2daf43aac241) The screenshot is from the test environment after we upgraded the Core components 4.33. 
![image (3)](https://github.com/user-attachments/assets/5069acb0-ec4a-49a7-b252-9a330a0a26d5)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Orphaned Users)

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

We manually trigger the flow.

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately sometimes the product creates these non-graph endpoint connections. They will break you at this spot. You will need to update those connections to also point to Graph.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by steph-ong98** [comment]
Hi @Jenefer-Monroe, 
we tried your suggestion, by changing the URL to the Graph, however, it is coming up with an error, stating that an item with the same key has already been added. So out of the 4 connectors, 2 is linked to the Graph URL (but they are not connected to any flows), while the other 2 linked to the wrong URLs (are connected to flows) - these 2 are the ones coming back with an error when we try to change it to the Graph URL. 

![Screenshot 2024-08-23 120340](https://github.com/user-attachments/assets/25ea2d20-31d2-4c0f-b4b8-ccce12430a84)

**Comment by steph-ong98** [comment]
Hi Jenefer,

We are having a few more issues regarding this flow.

***@***.***
