### ISSUE TITLE
[CoE Starter Kit - QUESTION] Fix up spots that still have the removed "Total Shared With" field

### ISSUE THREAD

**Issue by ADMIN-SKE2388** [microsoft/coe-starter-kit#8809]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi!
I have upgraded my CoE kit to latest version juli 2024 v. 4.33, everthing went smoothed. 
The production dashboard report failes beacause "Total Shared With" column does not exist. I tried to find information about this in the forum but did not find anything regadring this issue. Any idea on what is going on here?
The text over the filed is in Norwegian and it says "This field has been deleted and can't be used in this visualization"

![Totalsharedwith](https://github.com/user-attachments/assets/63ba6011-d342-4bbf-8c1f-90baf002eae1)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Yes that is correct, that field is deprecated in favor of the following:
![image](https://github.com/user-attachments/assets/04a46d09-09df-46a0-aa2c-6a3e4ffadf97)

I thought we updated the PBIT file when we did that. Did you take in the new PBIT?
I have validated that the current PBIT is correctly pointing to this field.

**Comment by ADMIN-SKE2388** [comment]
Hi Jenefer! 
I thought about that and I made sure that I am using the july PBIT three times but it did not work!
It seems that the report is not updated. I just downloaded CoE folder and tried the PBIT again for July, still the same problem.

**Comment by Jenefer-Monroe** [comment]
Ok perhaps we did not update for July. Sorry about that. The August release is available, you can try that PBIT file. 
[augustbpitfiles.zip](https://github.com/user-attachments/files/16617096/augustbpitfiles.zip)

**Comment by ADMIN-SKE2388** [comment]
I have just imported the august PBIT file and It works for the "App Usage" page but It is still the old column in "Sharepoint Form Apps" page. I can just change manually for now until you can update the report. Thank you for the help! :)
![image](https://github.com/user-attachments/assets/5a53d223-6ddb-4036-9a42-e2a534ffbba0)

**Comment by ADMIN-SKE2388** [comment]
![image](https://github.com/user-attachments/assets/b3498084-ed79-4840-826c-5c99897096b6)

**Comment by ADMIN-SKE2388** [comment]
![Skjermbilde 2024-08-15 085051](https://github.com/user-attachments/assets/16d9128d-9025-49b8-8bfd-a5a3fb5ba5af)

**Comment by Jenefer-Monroe** [comment]
Thanks for your help this is local fixed now in the release at https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by ADMIN-SKE2388** [comment]
Thank you!

**Comment by Jenefer-Monroe** [comment]
fixed in August release https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
