### ISSUE TITLE
[CoE Starter Kit - QUESTION] Cross Tenant Connections References

### ISSUE THREAD

**Issue by silvafr1** [microsoft/coe-starter-kit#8810]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,
I´ve updated the HostDomains Environment Variable with a list of Domains we have, as mention here: https://learn.microsoft.com/en-us/power-platform/guidance/coe/faq#how-to-configure-what-is-a-local-connection-identity 
 
However when I retrieve the "Cross Tenant Connections References" list at the "Manage Permissions" App, we still have those domains as "other tenants".
Is there a flow that we need to run to update that data?
Thank you!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August version, 4.34

### What app or flow are you having the issue with?

Don´t know

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Yes we do not go back and update old connections when you change the env var, this is to avoid costly api hit regularly as this is an uncommon task. 

Here is [How to update data to respect configured local tenants](https://learn.microsoft.com/power-platform/guidance/coe/faq#how-to-update-data-to-respect-configured-local-tenants)

**Comment by silvafr1** [comment]
Thank you Jenefer-Monroe! I saw that solution you gave but I was wondering if there were an automatic update! That´s why I´ve created this "Question" :)
Thank you again!
Best regards

**Comment by Jenefer-Monroe** [comment]
Happy to help. We do not have an automated update. Please do let me know if the help document gets you what you need!

**Comment by silvafr1** [comment]
Thank you! :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
