### ISSUE TITLE
[CoE Starter Kit - BUG] Help deleting core components

### ISSUE THREAD

**Issue by 12Khyati12** [microsoft/coe-starter-kit#8811]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We try to remove Solution from environment but this solution can not be delete from environment. 
Name of environment : Center of Excellence - Core Components

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.11

### What app or flow are you having the issue with?

Power Platform Admin

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, sorry you will need to give more details. 

1. What type of environment is this installed in? (Namely is it installed in default)
2. What error are you given when you try to delete? 
3. What other solutions are installed in the envt? (Namely have you installed other starter kit solutions)

**Comment by 12Khyati12** [comment]
Hello,

  1.
What type of environment is this installed in :  it installed in default
dynatechconsultancy.com (default)
  2.
What error are you given when you try to delete : not getting any error when I try to delete
  3.
What other solutions are installed in the envt : other solutions are delete form this environment



Best Regards,

Khyati Shah

Application Developer



[cid:d64d3adc-4843-40ed-b100-e2828c543a68]

 +91 9574993043 |   www.dynatechconsultancy.com<http://www.dynatechconsultancy.com/>





________________________________

**Comment by Jenefer-Monroe** [comment]
It being installed in default is unfortunate as it means there are many possibilities for what has taken a dependency here. 
You need to find what the dependency is and then clean that up, then you will be able to uninstall. 
To find the dependency you will need to find the error from when you tried to uninstall. 
To find this you can try the uninstall again and look for the error to pop on top of the page, or you can look in the solution history. 
![image](https://github.com/user-attachments/assets/0b90d8ac-932f-40b5-8118-32c789c6adbe)

**Comment by 12Khyati12** [comment]
Hi

Please check below error

Error code
8004F01D<http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=8004F01D&de=online>
Exception message
Solution dependencies exist, cannot uninstall. DependencyCount : 3 RequiredComponentObject details: Type: SystemForm, ObjectName: Power Platform Dashboard, Id: cf839870-ff70-e911-a833-000d3a375590, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: dtpl_Account_MD, Id: 5a4f1a82-8036-ee11-bdf4-002248d5d340, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Unpublished RequiredComponentObject details: Type: SystemForm, ObjectName: Power Virtual Agents Dashboard, Id: afc4003a-835c-ed11-9561-00224805c003, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: AppModule, ObjectName: dtpl_Account_MD, Id: 5a4f1a82-8036-ee11-bdf4-002248d5d340, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Unpublished RequiredComponentObject details: Type: EnvironmentVariableDefinition, ObjectName: admin_AdminMail, Id: 88adcb0b-65c6-49f8-ad3d-5cd878bfd635, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: PowerApp -> Send me an email notification,Send me an email notifica..., Id: d9264122-9f36-ee11-bdf4-002248d5d340, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 DependencyType: Published


Best Regards,

Khyati Shah

Application Developer



[cid:7df68dc8-1f72-472c-9f98-205333e57eec]

 +91 9574993043 |   www.dynatechconsultancy.com<http://www.dynatechconsultancy.com/>





________________________________

**Comment by Jenefer-Monroe** [comment]
It sounds like someone made a MDA with a custom dashboard which relies on the tables in the kit. 
You'll need to find it, open it, and delete its components which refernce the kit. 

The logical name is given for it in the error

- Type: AppModule, ObjectName: dtpl_Account_MD,

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
