### ISSUE TITLE
[CoE Starter Kit - BUG] PowerBI August - App Shared With Error

### ISSUE THREAD

**Issue by Sinder088** [microsoft/coe-starter-kit#8812]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

after installing the August Core & PowerBI dashboard, i notice there is an error on the "App usage" page relating to App Shared With value. The chart is not displaying. 

![image](https://github.com/user-attachments/assets/a34db07f-a58d-4f62-8dfe-a45014bf19a1)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.35

### What app or flow are you having the issue with?

Production_CoEDashboard_August2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Sinder088** [comment]
I notice this step in the upgrade documentation, but when i look into my tenant, i don't ven see this custom connector. How is that possible? 
https://github.com/microsoft/coe-starter-kit/issues/1424

**Comment by Jenefer-Monroe** [comment]
Thanks for posting, I had missed that bug in the PBIT file. I've fixed it up now and updated the release file with new pbit.

**Comment by Jenefer-Monroe** [comment]
Regarding that custom connector. It was deprecated about a year ago so you would not expect to see it in the solution any longer.

**Comment by Sinder088** [comment]
That was quick. AWESOME! thank you. I will republish tomorrow and revert if there are further issues.
