### ISSUE TITLE
[CoE Starter Kit - BUG] Issue with the FLOW>Admin | Sync Template v3

### ISSUE THREAD

**Issue by HarishDhauta** [microsoft/coe-starter-kit#8813]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Issue with the FLOW>Admin | Sync Template v3
  "error": {
    "code": "0x80040217",
    "message": "Entity 'admin_Maker' With Id = ffea7c76-282b-4864-b3af-4f0050c1d098 Does Not Exist",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "Entity 'admin_Maker' With Id = ffea7c76-282b-4864-b3af-4f0050c1d098 Does Not Exist"
  }
}

### Expected Behavior

It should succeed 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin | Sync Template v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

 
 IN this Env :Global SONY COE Sandbox
with Admin | Sync Template v3 flow we have encountered below error , and flow status is showing failed.
 "error": {
    "code": "0x80040217",
    "message": "Entity 'admin_Maker' With Id = ffea7c76-282b-4864-b3af-4f0050c1d098 Does Not Exist",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "Entity 'admin_Maker' With Id = ffea7c76-282b-4864-b3af-4f0050c1d098 Does Not Exist"
  }
}

### Anything else?

NA

**Comment by Jenefer-Monroe** [comment]
Hello, that particular flow as named does not exist in the current version of the kit any longer and it appears you may be on a version of the kit well over a year old. 

Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by HarishDhauta** [comment]
Hi, Here is the requested screenhot>
![image](https://github.com/user-attachments/assets/2b1d95e5-e1f0-42fe-96e1-0fe576d02f28)
![COE ver](https://github.com/user-attachments/assets/d7b4d7b9-ebde-4449-9ee8-78505049b954)

**Comment by Jenefer-Monroe** [comment]
OK yes you re on the Nov 2023 release. Thanks for sharing. I'm afraid I don't recall that build sufficiently to assist. I know we did change how we dealt with SYSTEM owned objects between then and now as the product changed how they returned it. The helper flow that is called was updated to address. 
I presume that you'll need to upgrade to have this working correctly.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
