### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Capacity Alerts Flow fails to complete - 'List_Environment_Capacity_information' failed

### ISSUE THREAD

**Issue by DAWC21GOA** [microsoft/coe-starter-kit#8816]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Noob warning! 

Flow has not been successful since installation.  The action 'List_Environment_Capacity_information" Times out after 3 hours and  fails with "Action 'List_Environment_Capacity_information' failed: Sql error: Generic SQL error. CRM ErrorCode: -2147204784 Sql ErrorCode: -2146232060 Sql Number: 207" 

The connections to the dataverse appear to be ok.

### Expected Behavior

A connection is established and the required capacity data is retrieved.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Admin | Capacity Alerts Flow

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Unknown, has not worked since installation a year ago or so....

### Anything else?

![image](https://github.com/user-attachments/assets/9707bece-f71e-4898-892c-2f8e4cbb0635)
![image](https://github.com/user-attachments/assets/795e7aa8-e7ed-4f81-96a3-cc6f49d795e9)

**Comment by Jenefer-Monroe** [comment]
Hello. Welcome to CoE! 

Is the user identified here a user (or shared user) or a service principal? 
![image](https://github.com/user-attachments/assets/3dc2d722-d924-43aa-81d7-65a88b7312f5)

**Comment by DAWC21GOA** [comment]
Hello, It is a service account that COE was installed with.



Classification: Protected A

**Comment by Jenefer-Monroe** [comment]
Can you please clarify, do you mean a service account (a shared user account) or a service principle (an app registration)?

**Comment by DAWC21GOA** [comment]
It is a Shared user account that has the Power Platform Administrator Role Permanently assigned.



Classification: Protected A

**Comment by Jenefer-Monroe** [comment]
Is the identity running the flow a sys admin in the coe environment? 

### How check to see a users environment permissions 
Browse to https://admin.powerplatform.microsoft.com/environments/ > find your environment > Settings > Users + permissions > Users
![image](https://github.com/user-attachments/assets/0ee1dadd-9dc5-487a-8b7a-a1cce0843094)
![image](https://github.com/user-attachments/assets/35aa7aae-8162-43cd-8101-6678b3792b7a)
![image](https://github.com/user-attachments/assets/425bf786-31b9-462e-9c92-650584f41f56)
Find your user > Click to see their settings > are they enabled? What role do they have?
![image](https://github.com/user-attachments/assets/a8e17a78-1ee7-416e-b974-6d21fbc298f3)
![image](https://github.com/user-attachments/assets/ea312158-6170-461b-b814-54da4bac6f85)

**Comment by DAWC21GOA** [comment]
Account has System Administrator, Approvals user and Basic User Roles. The account is enabled.

***@***.***



Classification: Protected A

**Comment by Jenefer-Monroe** [comment]
Are other flows running and passing? ex: Admin | Sync Template v4 (Driver)

**Comment by DAWC21GOA** [comment]
Yes, It has been running successfully...

***@***.***





Classification: Protected A

**Comment by Jenefer-Monroe** [comment]
I'm really not sure then. It appears to be some product internal error unrelated to the kit. 
Perhaps see if there are unmanaged layers on the flow?

**Comment by DAWC21GOA** [comment]
There does not appear to be any unmanaged layers...
***@***.***




Classification: Protected A

**Comment by Jenefer-Monroe** [comment]
What is the type and region of your environment?

**Comment by DAWC21GOA** [comment]
Production - Canada



Classification: Protected A

**Comment by Jenefer-Monroe** [comment]
Sorry I'm just out of ideas here. I just tested early release environments and Canada and this is working. 
It appears that there is something wrong with the user or the connection, or perhaps the environment except that you say this users credentials work in the rest of the kit. 
I would probably try re-creating the connections to dataverse but I'm just throwing darts at this point. 
I suggest you give it a try. 

- Delete the connections as this user. 

- Create a new Dataverse connection as this user
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc387351-bebf-456c-b133-d04a88292917)

- Go to solutions > Default Solutions > Connection References
Look up the connection reference from above > Edit > Chose the new connection
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598483f6-b5b6-44d1-9cc6-351d3798a34b)

**Comment by DAWC21GOA** [comment]
Ok, deleted and re-created connections and it still fails.  I have another application that is accessing the environments table using the same account and it works...



Classification: Protected A

**Comment by Jenefer-Monroe** [comment]
Sorry I'm just not sure how to help then. This is clearly a product bug unrelated to the kit, you may need to get product support.

**Comment by DAWC21GOA** [comment]
I had tried that, and they directed me to the GIthub side of it… ☹



Classification: Protected A

**Comment by Jenefer-Monroe** [comment]
Yes I'm sorry they did that. The error message itself clearly marks this as a product issue, they should not have pointed you here.

Perhaps if you delete the actions in that flow entirely, and then upgrade the kit, and remove the unmanaged layer. 
The August release is available now and has some important features.

**Comment by DAWC21GOA** [comment]
Ok, We'll give that a try!



Classification: Protected A

________________________________

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
