### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Add Maker to Group flow fails

### ISSUE THREAD

**Issue by PPTechy** [microsoft/coe-starter-kit#8818]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,
The "**Admin | Add Maker to Group**" flow fails in our CoE environment, we get the below runtime failure error:

<img width="779" alt="image" src="https://github.com/user-attachments/assets/9abf4098-4f54-4e13-8b40-e7648e20c98e">

It seems the error coming for the email id, it has to be a Group ID in string or UUID format.

What type of group we should have, and where to pass this group to avoid this issue?

Hi @Jenefer-Monroe - I request your help here.

Thank you!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Admin | Add Maker to Group

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Yes that is correct. There are 3 groups that you setup with the kit per [How to communicate with your admins, makers, and users](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-to-communicate-with-your-admins-makers-and-users). These are configured as shown here:

Admin persona : as an email address
Maker persona : as a group id
User persona : as a group id

You can update these by going to the command center as shown here:
![image](https://github.com/user-attachments/assets/0666bb1f-2203-4895-8a45-049d1b68d67b)

Hope that helps

**Comment by PPTechy** [comment]
> Hello. Yes that is correct. There are 3 groups that you setup with the kit per [How to communicate with your admins, makers, and users](https://learn.microsoft.com/power-platform/guidance/coe/setup#how-to-communicate-with-your-admins-makers-and-users). These are configured as shown here:
> 
> Admin persona : as an email address Maker persona : as a group id User persona : as a group id
> 
> You can update these by going to the command center as shown here: ![image](https://private-user-images.githubusercontent.com/89584709/358571827-0666bb1f-2203-4895-8a45-049d1b68d67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTA5MDQsIm5iZiI6MTcyMzgxMDYwNCwicGF0aCI6Ii84OTU4NDcwOS8zNTg1NzE4MjctMDY2NmJiMWYtMjIwMy00ODk1LThhNDUtMDQ5ZDFiNjhkNjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEyMTY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYzY2YWY3ZDJiZDNiMDkwZWJhNDI4MmYyYmFiNjNkMWYyMDJmZGVjZWQ2YjA1MWY5OTU3ZGRiMTkyYzQ3ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Va5wPO2KMHAIoCIBtELA55riZta4POiZT3rz8M5erK8)
> 
> Hope that helps

Hi @Jenefer-Monroe,

Thanks for your quick reply. Could you please help me to find the corresponding variable name you mentioned above:

Admin persona : as an email address -> admin_AdminMail
Maker persona : as a group id -> admin_PowerPlatformMakeSecurityGroup
User persona : as a group id ->admin_PowerPlatformUserGroupID

Above environment variable mapping is my understanding, could you please confirm whether this is correct?

**Comment by Jenefer-Monroe** [comment]
Yes those are correct. 
If you prefer you can boot the setup wizard as well which will walk you through this without having to worry about finding them:

![image](https://github.com/user-attachments/assets/40111e18-bbdb-4278-9fb7-f41b725ac847)


Generally speaking, you should always use the Setup Wizard for both new installs and after each upgrade as it will ensure you have all new env vars provided to fill, all new flows turned on, etc.

**Comment by PPTechy** [comment]
Hi @Jenefer-Monroe 
Thanks for the confirmation. Yes, already I have run the set up after the new upgrade, again I will run it, if needs. Thank you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
