### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Cloud Flows is taking hours to complete the each run

### ISSUE THREAD

**Issue by devipriyanka414** [microsoft/coe-starter-kit#8820]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Most of the runs from SYNC HELPER - Cloud Flows are taking so many hours to complete.

![Sync Helper - Cloud Flows](https://github.com/user-attachments/assets/8d4cbe8e-8c88-4830-8eae-7e011af32a97)
![Sync Helper - Cloud Flows 2](https://github.com/user-attachments/assets/b97684cf-0f5f-47f9-b573-10622282c2d2)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
This implies that your user is being throttled. 
Might I ask about how many environments are in your tenant? And about how many flows? That will help me advice what to do next.

**Comment by devipriyanka414** [comment]
We have 1500+ environments and 27k flows exist in our tenant

**Comment by Jenefer-Monroe** [comment]
Thank you, and is this a new install? Or has it been around for a while?

**Comment by devipriyanka414** [comment]
It's been more than 2 years and we've been encountering this issue for several months. It only affects this particular flow.

**Comment by Jenefer-Monroe** [comment]
Can you please check the value of these environment variables? 

- Full Inventory
- is All Environments Inventory
- InventoryFilter_DaysToLookBack

You can do this in the CoE Admin Command Center as shown here
![image](https://github.com/user-attachments/assets/6e7db65f-8056-4203-a647-ec798bee6307)

**Comment by devipriyanka414** [comment]
Below are the values of the environment variables
Full Inventory - Yes
is All Environments Inventory - Yes
InventoryFilter_DaysToLookBack - 7

**Comment by devipriyanka414** [comment]
We'll update the environment variable and restart the flows to check if the issue is resolved. Thanks! :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
