### ISSUE TITLE
[CoE Starter Kit - QUESTION] Where is the full package for the July release?

### ISSUE THREAD

**Issue by adamx9035** [microsoft/coe-starter-kit#8821]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I need to download the full package of the July release again. Could you please put it back there?
I can't install the August release because it says it's not ready for sovereign cloud.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately we had to pull the full July version due to the following bug https://github.com/microsoft/coe-starter-kit/issues/8814 and we cannot reshare it.
Sorry for the inconvenience.

**Comment by adamx9035** [comment]
Got it. Two questions: 1) When will the full August version be ready for sovereign clouds, like GCC? 2) Currently, our CoE production instance is at the May version. Is there any risk to upgrade it directly to the full August version when it is released for GCC?

**Comment by Jenefer-Monroe** [comment]
Hello no there should not be any issues upgrading directly from May to August, I have tested that specifically for you all. 
If you do have issues specific to your tenant please reach out and we'll get you unblocked.

Regarding when sovereign clouds will be unblocked, the current issue is with the ability to create the **_Power Platform for Admins V2_** connector. Our sovereign cloud experts are actively working with the product owners to get you unblocked and are making progress through the issues. We will let you know when this is complete.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
