### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by amalarajaf** [microsoft/coe-starter-kit#8822]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After COE Starter Kit upgrade, Maker Command Center App - Environment request creation is not working when using maker role (Power Platform Maker SR). Please refer screenshot

![Environmentcreationerror](https://github.com/user-attachments/assets/ae54c5f5-7e9c-401d-b206-2f504f5d0d8c)

Do I need to make any changes to the permission as Environment Request App was Canvas App previously?
Environment Request (Canvas App) was working for Makers previously (Power Platform Maker SR).

Note: It is working when using Power Platform Admin SR

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

CoE Maker Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the CoE Maker Command Center App using Power Platform Maker SR and create the Environment request

**Comment by Jenefer-Monroe** [comment]
Hello, thanks for posting. Please see https://github.com/microsoft/coe-starter-kit/issues/8644 which is fixed in the August release.

**Comment by amalarajaf** [comment]
Thanks for the prompt response!! I will apply the local patch instructed by you and confirm.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
