### ISSUE TITLE
[CoE Starter Kit - QUESTION] - It seems like my flow "HELPER - CloudFlowOperations" is missing something

### ISSUE THREAD

**Issue by SegoleneDuong** [microsoft/coe-starter-kit#8823]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I tried to delete a flow via the app "Manage permissions", i also tried to add maker and nothing is happening. So i went to check the flow "HELPER - CloudFlowOperations",  i campared this flow with the "HELPER - CanvasAppOperations" and my flow is missing a lot of steps...

How can I fix it ? 

Thank you very much.

![flow helper cloudflowoperation](https://github.com/user-attachments/assets/29767bf6-3653-4fdf-b8c5-10182b58e6cb)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

HELPER - CloudFlowOperations

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Yes it appears that you have lost most of the flow there. I just validated the flow is fine in your release.

Can you please check to see if you have unmanaged layers on the flow? You can do that as shown here: 
![image](https://github.com/user-attachments/assets/03a533e4-59f9-4af0-9b0e-c6253953bda4)
![image](https://github.com/user-attachments/assets/ca0d67a4-ff5c-4f52-aff5-67d80bd46a27)

Or you can go to the command center and see if you have any across the kit as a whole. 
![image](https://github.com/user-attachments/assets/9c4e2cf8-a5dd-48fe-92bc-841604ff838c)

If you have an unmanaged layer please remove it.

**Comment by Jenefer-Monroe** [comment]
wonderful! I'll go ahead and close this out then but please do return with new issues as needed.
