### ISSUE TITLE
[CoE Starter Kit - How to add users automatically to User Persona

### ISSUE THREAD

**Issue by fbellavf** [microsoft/coe-starter-kit#8824]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The Maker group now adds makers to the persona but how do we get users in the org access?

### Expected Behavior

Would like new staff in org with license to be added to the User Persona

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

CoE

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately we are not staffed to assist with customizations. We do have prorogating such a group from our data on the backlog but it will not likely be funded anytime soon. 

I think what you would need to do is match the **_Admin | Add Maker to Group_** flow, which does this for Makers. You could use the **_Power Platform User_** table as your source. So when new users are added to that you add them to the User Group. 

Hope that helps.

**Comment by Jenefer-Monroe** [comment]
Correct, the way people extend the kit is by creating their own solution (MyOrgCoE_Extended) and putting their new flows in there. 

You can read about that here: [Extend and customize CoE Starter Kit components](https://learn.microsoft.com/power-platform/guidance/coe/modify-components)

**Comment by fbellavf** [comment]
> Correct, the way people extend the kit is by creating their own solution (MyOrgCoE_Extended) and putting their new flows in there.
> 
> You can read about that here: [Extend and customize CoE Starter Kit components](https://learn.microsoft.com/power-platform/guidance/coe/modify-components)

Ah yes, this sounds good.

Thank you!
Fernand
