### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance and Inactivity Flows not picking up for some environments

### ISSUE THREAD

**Issue by Chitusnair** [microsoft/coe-starter-kit#8828]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Dear Team,

I recently included the Default and some other environments to the compliance and inactivity flows through the Power Platform admin view App >Environment > Settings, in the CoE Production environment. However, the flows still work only for the previously included environments. The settings are the same in the test environment which is working well.

Am I missing something?

Thanks,
Chitra

### Expected Behavior

By turning the 'Excuse form Inactivity flows' and 'Excuse form Compliance flow' toggle to 'NO' should trigger compliance emails and inactivity notifications to those environments.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.24

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please go to the most recent run of **_Admin | Compliance detail request v3_** and look at the raw output of **_List Environments not excused from compliance_** action. 

Do you see your Default environment listed? Or the other environments you just recently un-excused?

![image](https://github.com/user-attachments/assets/f9ea0168-8ffe-4933-9a32-cf21fcbbdd97)

**Comment by Chitusnair** [comment]
Hi Jenefer,

Sorry for the late reply.

Yes, can I see the Default environment in the raw output of 'List
Environments not excused from compliance'.

Thanks,

**Comment by Jenefer-Monroe** [comment]
Thank you, please denote its location in that array and find it in the apply to each that follows
Be sure you've found the correct environment (may be off by one if your counter was zero based and apply to each being 1 based)

Are there any apps returned? 
![image](https://github.com/user-attachments/assets/1a6da24e-6774-4692-b877-8cb6cc02267c)

There filter is as follows:
`admin_powerappstype eq 597910000 and _admin_appowner_value ne null and admin_appdeleted ne true and admin_appownerdisplayname ne 'SYSTEM' and _admin_appenvironment_value  eq '67c96cd6-4a95-46ee-ac9b-8ee13ae256c4' and admin_appexcusedfromcompliance ne true`

Which means the following:
admin_powerappstype eq 597910000 >> type canvas 
_admin_appowner_value ne null >> not missing an owner
admin_appdeleted ne true >> app not marked deleted
admin_appownerdisplayname ne 'SYSTEM' >> not system owned
_admin_appenvironment_value  eq 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'  >> your default envt id here
admin_appexcusedfromcompliance ne true >> app not excused

Please find such an app you expect to be found if none are returned.

**Comment by Chitusnair** [comment]
Dear Jenefer,

I can see the compliance emails and inactivity emails are being sent for
the Default environment now. This can be closed now. Not sure why it
took so long.

Thanks,
Chitra

**Comment by Jenefer-Monroe** [comment]
Wonderful news! Thanks so much for following up to let me know, I love getting good news.
I'll go ahead and close but do feel free to open new issues in the future.
