### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI dashboard Error in App Usage page | Something's wrong with one or more fields: (Power Apps) App Shared With (Total)

### ISSUE THREAD

**Issue by kskramki** [microsoft/coe-starter-kit#8832]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have upgraded to July release recently and we are noticing the error in App Usage an SP Form Apps page in Power BU Dashboard. The error is "Something's wrong with one or more fields: (Power Apps) App Shared With (Total)"
![image](https://github.com/user-attachments/assets/4792c4f9-40d8-4e6d-a365-cbd2fbfebcd2)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Power BI Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. There was a spot we missed cleaning up this deprecated field, that is fixed in the August release. 
I think that the PBIT files in August are usable by the July release so please do give that a try:
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team

**Comment by kskramki** [comment]
Thank you. Aug PBIT files worked.
