### ISSUE TITLE
[CoE Starter Kit - QUESTION] Place to view compliance status

### ISSUE THREAD

**Issue by Tomozo-No1** [microsoft/coe-starter-kit#8833]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, I have a question about compliance.
I understand that the CoE Setup and Upgrade Wizard allows you to set environment variables.
Do you have an overview like a Power BI dashboard?
For example, let's say a pending paused flow is out of compliance
Is there such a thing?
If so, I would appreciate it if you could tell me.
This is just an example, so don't worry if it's different.
If you don't understand the meaning, please tell me where and how you don't understand it.

Can you tell me more about where on the page where the overview is located?

CoE Power BI Dashboard
https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-compliance

Where we understand
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components

<img width="408" alt="スクリーンショット 2024-08-20 171905" src="https://github.com/user-attachments/assets/7263ad10-ea16-4650-9200-94921773ce8b">

### What solution are you experiencing the issue with?

None

### What solution version are you using?

2024/6

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello we do not have a PBI of this, no. 
However we do have some views you can look at in the Power Platform Admin View MDA. You can use that to create some PBI's of your own if you'd like. 

![image](https://github.com/user-attachments/assets/7334739a-38cf-44fa-b6c5-65e990f72eb3)

Please let me know if that answers your question.

**Comment by Tomozo-No1** [comment]
I want an overview of the flow that violates compliance, just like the summary like the previous attachment. There is a summary of PBI compliance and governance, but is there no summary in the flow of this attached file?
![IMG_4686](https://github.com/user-attachments/assets/6c6b9e6e-7df4-4585-b5aa-1e95a0e2296b)

**Comment by Jenefer-Monroe** [comment]
sorry no we do not have such a thing.

**Comment by Tomozo-No1** [comment]
Are you saying that the compliance flow standards will be as follows?
<img width="842" alt="スクリーンショット 2024-08-21 091528" src="https://github.com/user-attachments/assets/d6bcf5e9-688b-4ac6-a9cd-aa64e0f08e8c">

**Comment by Tomozo-No1** [comment]
The Non-Compliance flow is an app considered non-compliant if it does not comply with the following thresholds?

- The app is shared with more than 20 users or at least one group, and no business justification details have been provided for it.

- The app does have business justification details, but hasn't been published in 60 days (so it's likely not on the latest version of Power Apps) or is missing a description.

- The app has business justification details and an indication of high business impact, but no mitigation plan has been submitted to the attachments field.

**Comment by Jenefer-Monroe** [comment]
The first link is the compliance flows. Its how you flag apps (and chatbots) as requiring feedback from author. 
Here are the setup instructions. [Compliance process](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#compliance-processes)

The second link you sent is an addition solution area you can enable, which builds on the first. 
Its for when to flag an app to be marked quarantined if they ignore your requests via the compliance flows (first one above)
Here are the setup instructions for that : [App Quarantine process](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#app-quarantine-process)

**Comment by Tomozo-No1** [comment]
“The first link is the compliance flows. Its how you flag apps (and chatbots) as requiring feedback from author.
Here are the setup instructions. [Compliance process](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#compliance-processes)”
What is the basis for flagging?

**Comment by Jenefer-Monroe** [comment]
Those bullets you posted are the basis, modified by the env variables.

You may need to just explore the flow yourself in order to feel more comfortable: Admin | Compliance detail request v3

![image](https://github.com/user-attachments/assets/c55857c0-183e-4a0c-bb8e-f6e892027dc4)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
