### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE Cannot republish apps via Developer Compliance Center

### ISSUE THREAD

**Issue by Service-WebDevPowerP** [microsoft/coe-starter-kit#8834]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Every week we get emails stating:
You own an app that's currently shared or used broadly but which has not been published recently. It is best practice to test and republish such apps regularly in order to ensure they stay up to date with product changes.
Please test and republish the app to ensure that it continues to operate in the most effective way. You can use the Developer Compliance Center app to view all required work.

We attempt to use the Developer Compliance center to publish the app but every time we get:

![image](https://github.com/user-attachments/assets/b32cfcff-0738-4449-9b17-3dac35f8af30)

I see this issue has been brought up before but I cannot find a fix within any of the reports and all of them are closed. How can I fix this?

Currently on July release for production and August for Test, but Test gets the same issue  as well. 

### Expected Behavior

Button should republish the app 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.24

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We dont support publishing from the compliance center. We only warn them to go and publish in the product. Here is the UX they should see. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/e776b2d3-b37b-4ae9-a36e-15c55a6b8ffc)


Can you please see if you have unmanaged layers on that custom page?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team

**Comment by Service-WebDevPowerP** [comment]
Thank you for your reply. So does the re-publish button not function at all? I don't get the same as what you have in your screenshot I just get whats in my screenshot.
