### ISSUE TITLE
[CoE Starter Kit - BUG] Business Value Tool: Flows fails with: "Model not supported: Your model is using preview features that are no longer supported"

### ISSUE THREAD

**Issue by martintoelk** [microsoft/coe-starter-kit#8837]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We wanted to take a loot a the Business Value Tool and installed in in a *.crm4 region (early feature is on).

When we try to "Assess and existing app" / "Assess a proposal", via the "  Business value capture" Aoo the app is stuck, when it tries to do its AI Magic.

Installed solution: business_value_core_2_1_managed.zip

The Underlying AI Flows, will fail with:

 "Model not supported: Your model is using preview features that are no longer supported"

![image](https://github.com/user-attachments/assets/4dd93114-0ce7-4012-8930-8a3539b9df06)

![image](https://github.com/user-attachments/assets/fc307f89-c924-4642-a451-b9cd0bb11c7b)

### Expected Behavior

The epxected behaviour is:

The AI Generation works 

Alternative:
In case it is a Geo problem: 
- Please provide a concrete list of requirements for this feature  (Geo / Environment Setting / Licensing). 
-  or provide a more detailed gudie on how determin if the required "generative AI actions in Power Automate" is available for a given environment

The documentation is a bit vague
![image](https://github.com/user-attachments/assets/00354b32-b923-4270-9304-ed592c1172c0)

### What solution are you experiencing the issue with?

Innovation Backlog

### What solution version are you using?

2.1

### What app or flow are you having the issue with?

AI-EnhancedStoryGen

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. spin up a *.crm4 Environemnt
2. install business_value_core_2_1_managed.zip
3. Run the App and try to Assess An existing App

**Comment by Jenefer-Monroe** [comment]
over to area owner for investigation

**Comment by stjeffer** [comment]
Please can you confirm the region and environment type so that we can repro?

**Comment by martintoelk** [comment]
Sure 
![image](https://github.com/user-attachments/assets/9dc3acad-b018-4186-b6b2-7f4410f4d45d)

![image](https://github.com/user-attachments/assets/846b3d39-f7a3-40dc-ab10-a4fd6f9f5072)

**Comment by stjeffer** [comment]
Hi Martin,

A quick repo and it looks like the 'create text using a prompt' action that is used by several cloud flows is not available in sandbox environments.  I will double check with the owner of this prompt, but in the meantime, if you can provision a developer environment and assign AI Builder credits, you should be fine.

I'll update the documentation - appreciate your comments about it being vague, this was due to the fast changing capabilities, and linking our article to existing documentation felt more appropriate.  I will update the docs.

Thanks!
Steve

**Comment by martintoelk** [comment]
Same issue happens with a Developer environemnt. I will spin up an US based Developer Environment after lunch and try it again

![image](https://github.com/user-attachments/assets/e3031add-199c-48e4-abf7-a04f89cf7412)

![image](https://github.com/user-attachments/assets/a5be5602-befc-46c5-ae1b-5cf59a214fc8)

**Comment by stjeffer** [comment]
Thank you Martin - I've created a few environments to check, the only time the 'create text with GPT' action is NOT visible is when I select 'Get new features early'.  It does not appear to relate to the type of environment as I previously thought.  I will check internally.  If you don't mind, could you provision a new environment without selecting 'Get new features early' please.

**Comment by martintoelk** [comment]
I can confirm:

Works like a charm with "None Preview" and "Environment Type" equals production

Thanks for the assistance :)

![image](https://github.com/user-attachments/assets/c342a6c6-eee0-4605-83c0-b295f88222f1)

**Comment by stjeffer** [comment]
Thanks for collaborating Martin. I'll put this into the 'FAQ' section of docs.
