### ISSUE TITLE
[CoE Starter Kit - BUG] Abandoned PowerApps

### ISSUE THREAD

**Issue by send2mark** [microsoft/coe-starter-kit#8838]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I followed the fix that was reported earlier [here](https://github.com/microsoft/coe-starter-kit/issues/8747) and didn't get a response. Maybe because is was closed.

**Trying to install 4.33 I get the following.**
Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: The uninstall operation will delete the base layer for the component 'SavedQuery' with id 'f9d327af-b6b4-e911-a85b-000d3a372932' and name 'Abandoned PowerApps'. The operation cannot continue because there are other managed layers over the base layer. You can use the solution layers to find out which other solutions are blocking the operation..

### Expected Behavior

A successful installation

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. unintalled failed solution
2. In the apps area for the Power Platform Admin View I removed the Abandon Apps
3. Saved
4. Published
5. Opened the app again to make sure the changes too affect which it did.
6. Same error

Doing all these steps produces and unmanaged layer. When I remove that it reverts my changes of removing the Abandon Apps from the Power Platform Admin view. 

I have tried installing the new solution by both removing the unmanged layer and view seporately with no success. 
<img width="953" alt="2024-08-16_08-43-43" src="https://github.com/user-attachments/assets/308a058e-2ad2-46e7-935f-6136e10dc210">
<img width="860" alt="2024-08-16_07-22-04" src="https://github.com/user-attachments/assets/0e0c07da-86fa-49c9-a993-7ac10d7c7b0e">

**Comment by Jenefer-Monroe** [comment]
Hello, yes I dont get notifications about comments on closed bugs. 

I'm sorry this is a product bug and not an issue with the kit. So if our workaround doesnt work I'm afraid I don't know how to assist. 

That said it worked for others so hopefully its just the ordering of steps that is tripping you up. 

It sounds like perhaps you are removing that unmanaged layer before you upgrade? Is that true?
Please do not remove it. And try the ugprade. 

If that doesnt work, worst case you can do an update instead of an upgrade.

**Comment by send2mark** [comment]
I have done both removed and not removed, but ok I will get this figured out. Thanks

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
