### ISSUE TITLE
[CoE Starter Kit - BUG] Missing Fields in Power BI Dashboard for Dataverse for Teams

### ISSUE THREAD

**Issue by sqirrel** [microsoft/coe-starter-kit#884]
### Describe the issue

Microsoft support has directed us here. We have been given a 90 day trial environment for Power Automate by Microsoft to try CoE on.

We followed this [YouTube - Center of Excellence Starter Kit - Setup Instructions](https://www.youtube.com/watch?v=Z9Vp2IxFzpU) video to set it up.

However, when we set up the Power BI Dashboard "Dataverse_CoEDashboard_202107_v2" we got errors.
In this video, embedded apps were also replaced and re-linked to the data. [YouTube - Center of Excellence Starter Kit - Setup Instructions - Minute 47:25](https://youtu.be/Z9Vp2IxFzpU?t=2497)

This also worked well. However, now we have more errors on different pages.
For example on "Enviroments" top right "Something's wrong with one or more fields. See details"

> **Fields that need to be fixed**
Something's wrong with one or more fields: (Environment) admin_numberofflows, (Environment) admin_numberofapps
Please try again later or contact support. If you contact support, please provide these details.
Hide details
Activity ID5b107ea5-b134-4550-9080-8c06de006ab0
Request ID19cf4ebd-bf21-e3a0-c7f7-d70cf1fbd8bd
Correlation ID9817f4a8-dcfc-ba3f-bf9f-6b79dfb1524c
TimeWed Jul 21 2021 12:50:26 GMT+0200 (Mitteleuropäische Sommerzeit)
Service version13.0.16442.42
Client version2107.2.06866-train
Cluster URIhttps://wabi-west-europe-e-primary-redirect.analysis.windows.net/ 

On "Apps" in the filter area.

> **Fields that need to be fixed**
Something's wrong with one or more fields: (App) admin_powerappstype_display
Please try again later or contact support. If you contact support, please provide these details.
Hide details
Activity ID5b107ea5-b134-4550-9080-8c06de006ab0
Request ID001ef4eb-3cae-72ec-b385-2b2f07800bc1
Correlation ID8993498e-c8aa-ae09-41e6-948bc2d6c011
TimeWed Jul 21 2021 12:48:02 GMT+0200 (Mitteleuropäische Sommerzeit)
Service version13.0.16442.42
Client version2107.2.06866-train
Cluster URIhttps://wabi-west-europe-e-primary-redirect.analysis.windows.net/

We are not sure what this is due to. Do fields have to be re-inserted here as well, as described above, or is the error coming from somewhere else?

### Expected Behavior

The fields are displayed.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

202107_v2

### What app or flow are you having the issue with?

Dataverse_CoEDashboard_202107_v2

**Comment by JeneferM-MSFT** [comment]
Sorry your description has me a little lost. Is the issue to do with the embedded apps? Can you please share screenshots of what you are seeing? Note that screenshots have to be added in GitHub, responding to this in email will not share them. 

Please also validate that
1) You have set up the Core components
1) All the sync flows are running and passing
1) Look in the Model Driven App in core to see if the data missing from the PBI is present.

**Comment by sqirrel** [comment]
1. You have set up the Core components
- Yes, i think we did.
2. All the sync flows are running and passing
- All sync Flows running
3. Look in the Model Driven App in core to see if the data missing from the PBI is present.
- First Error is a stacked bar chart
- Second Error is a Slicer
![image](https://user-images.githubusercontent.com/87756636/126617852-e8b38ce0-22d9-42be-936b-fa565c1826d3.png)

![image](https://user-images.githubusercontent.com/87756636/126618027-e12f8c86-d8a1-4abc-8377-5825ec7b53af.png)

**Comment by manuelap-msft** [comment]
Thank you for providing those details! Fixed for the August release, which should go live next week.

**Comment by sqirrel** [comment]
@mikefactorial Reopen this or create a new one?

Hi!

Thank you for your answer.We did not update the existing CoE version. Instead of updating, we created a new empty environment and installed CoE there.
Also, it was a newer version of the CoE than stated here in the post:
CenterofExcellenceCoreComponents_3.7_managed
CenterofExcellenceAuditLogs_2.3_managed
Dataverse_CoEDashboard_202109


Unfortunately, we continue to have errors:
1. On one error we get the possibility to run an autodetect, which unfortunately is unsuccessful (No relationships where detected).
Befor:
![DesktopFlowRunDetailsBeforFixThis](https://user-images.githubusercontent.com/87756636/133453242-ca600757-fc4b-4f97-aee1-b1adc290007e.JPG)
After:
![DesktopFlowRunDetailsAfterFixThis](https://user-images.githubusercontent.com/87756636/133453310-e725e0df-068d-41c4-85d5-2c859687f383.JPG)


2. With another error it is not clear to us what should be selected there:
Befor:
![AppsBeforFixThis](https://user-images.githubusercontent.com/87756636/133453405-b106e75f-fbd0-47e4-b4f7-c66587b876ec.JPG)
After:
![AppsAfterFixThis](https://user-images.githubusercontent.com/87756636/133453444-a8296732-7c79-4cf7-8652-3718e9a4f347.JPG)

3. With another error the "Fix this" seems to work:
Befor:
![AppLicenseAssessmentBeforFixThis](https://user-images.githubusercontent.com/87756636/133453514-7d14d7b4-a189-4143-91bc-c6d222d898a8.JPG)
After:
![AppLicenseAssessmentAfterFixThis](https://user-images.githubusercontent.com/87756636/133453548-0aa68303-571d-4588-ba25-ff1e2ae42865.JPG)

4. Most often this error occurs in the gray box ( Filter, if I'm right). Here nothing happens when "Fix This" is clicked:
![image](https://user-images.githubusercontent.com/87756636/133454791-356154da-fce6-46e3-9ee2-20543f91ea25.png)

It is not clear to us if we are making mistakes in the installation steps, if it is normal and things need to be fixed by us or if this is not supposed to happen.

**Comment by manuelap-msft** [comment]
If you do not have any Desktop flows (and it looks like you don't) than it is expected that the visuals won't work.

**Comment by sqirrel** [comment]
Thank you for your reply.

When I took the screenshots there was a desktop flow. There were also others already existing, but I had not refreshed Power BI. I created also a Desktop flow that ended in an error and run it once.
All flows ran at least once (screenshots directly from Power BI Desktop Client):
![image](https://user-images.githubusercontent.com/87756636/133475653-e7bc9343-5616-40e6-bb83-a4dc75c48bc8.png)

![image](https://user-images.githubusercontent.com/87756636/133475885-30cdd78c-e1a9-4046-b4de-328ef22c76b9.png)

So if I see it correctly, the execution time data is missing . Therefore it is not a Power BI error, it is already in the audit logging or in the import flows?

**Comment by manuelap-msft** [comment]
Great, thanks for confirming. It's unfortunately become a bit challenging for to maintain two versions of the dashboard (but equally it is required as the CDS Legacy connector in Power BI does not work with Teams environments). It looks like the errors are just in the Power BI, if your flows are running successfully - I will try and have a look at this by the end of the week. Thanks for providing all the screenshots, this is helpful!

**Comment by sqirrel** [comment]
> if your flows are running successfully

All Flows are looking good:
Admin | Sync Audit Logs -> successful
Admin | Sync Template v3 -> successful
Dataset Refreshed
15.9.21, 18:12:45 (UTC+2)

>I will try and have a look at this by the end of the week. Thanks for providing all the screenshots, this is helpful!

Sounds great, thank you!

**Comment by manuelap-msft** [comment]
Hello,

thanks for the detailed error write up! I think I fixed those issues - before we release, could you try the new version please. You can download that from here: https://github.com/microsoft/coe-starter-kit/raw/coe-october/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Dataverse_CoEDashboard_202110.pbit

Thank you
Manuela

**Comment by sqirrel** [comment]
Thanks for the quick feedback.

Unfortunately, when I open with Power BI, I get the error message:

![image](https://user-images.githubusercontent.com/87756636/134942476-d5cd2009-b50b-4f4f-9f30-4745d62fd66c.png)

I have already tried to update my Power BI version. I have the version from the Microsoft Store and there it shows that I already have the latest version:

![image](https://user-images.githubusercontent.com/87756636/134942973-51eec8bb-9211-4c70-ae13-bfac4adf9cb6.png)

I am not sure if I can ignore the message and continue or try to update Power BI first.

**Comment by manuelap-msft** [comment]
We have seen this error in the past, and it was fine to ignore it and continue. I think because I'm in the Microsoft tenant, we sometimes get earlier updates automatically before they get released.  If you select Close, it should still load the data. But please let me know how you get on!

**Comment by sqirrel** [comment]
It already looks very good. There are only 2 errors left in the filter areas:

App Risk Assessment
![image](https://user-images.githubusercontent.com/87756636/135266191-1d2d2c07-02d9-4af4-b86b-7250eed84477.png)


Cloud Flows
![image](https://user-images.githubusercontent.com/87756636/135266294-bfcb1afe-21f4-4f7c-80bf-9bcd5817f302.png)

**Comment by manuelap-msft** [comment]
Thank you for spotting those!! I think I got it now: https://github.com/microsoft/coe-starter-kit/raw/coe-october/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/Dataverse_CoEDashboard_202110.pbit

**Comment by sqirrel** [comment]
Thank you!
At the moment I can not find any other errors, Great!

**Comment by manuelap-msft** [comment]
Amazing, thank you so much for your patience here!

**Comment by mikefactorial** [comment]
@sqirrel This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
