### ISSUE TITLE
Unable to install Coe Toll Kit components.

### ISSUE THREAD

**Issue by Anjaneyulu2347720** [microsoft/coe-starter-kit#8841]
Unable to install Coe Toll Kit components.
<img width="687" alt="COE error" src="https://github.com/user-attachments/assets/c9f24940-2fb8-4037-a5d7-d3ac8c1a55dc">
<img width="687" alt="COE error" src="https://github.com/user-attachments/assets/b6634869-bd61-4418-a39a-12c401353344">

**Comment by Jenefer-Monroe** [comment]
Hello, there is some prework that you need to do before installing the kit. 

Please review and do the steps described in [Before setting up the CoE Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/setup)

Once you have done that, you can begin the steps at [Set up inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components). 
In there you'll see a list of prerequisites, which includes installing the Creator Kit

![image](https://github.com/user-attachments/assets/3f290e8d-bfc8-4d50-b27b-b0f4ee07f673)

**Comment by Anjaneyulu2347720** [comment]
Hi Team

I have system admin access on environment where I am installing components.

This permission is enough to install or configure COE or do we need any additional permissions.

Regards
Anajneyulu

**Comment by Anjaneyulu2347720** [comment]
Hi Team

Please provide an update on my below query.

Regards
Anjaneyulu

From: Anjaneyulu Yalagala
Sent: Wednesday, August 21, 2024 12:40 PM
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] Unable to install Coe Toll Kit components. (Issue #8841)

Hi Team

I have system admin access on environment where I am installing components.

This permission is enough to install or configure COE or do we need any additional permissions.

Regards
Anajneyulu

**Comment by Jenefer-Monroe** [comment]
Please see [Which identity should I use to install the CoE Starter Kit?](https://learn.microsoft.com/power-platform/guidance/coe/setup#which-identity-should-i-use-to-install-the-coe-starter-kit) which will show you what the user that installs the kit requires. 
It includes things like the Power Platform Admin role directly and permanently assigned.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
