### ISSUE TITLE
[CoE Starter Kit - QUESTION] The July 2024 upgrade 

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#8843]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!
Hope you are doing well!

I have the question about the July 2024 upgrade - packages.
Usually, we are doing upgrade each 3 months. Last time it was April upgrade, so now we are doing the July upgrade.
We always took the package from this place:

![image](https://github.com/user-attachments/assets/06e24e5e-ce69-4ef8-8bc8-6acbe4d02015)

But this time I see that the July release has only these packages:

![image](https://github.com/user-attachments/assets/e7d40e9a-f3bf-4438-a4ab-4e9283c8f301)

So, there won't be just one big package "CoEStarterKit,zip" with all these zip files inside for the Core, Nurture, Governance components update? 
In the July upgrade I see now only these three separate zip files. But I do not see the core component file. So in July upgrade, there is no upgrade for the Core Components solution?

![image](https://github.com/user-attachments/assets/73e63504-6267-40c5-8c57-ccf2cde0cc61)

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

None

**Comment by PPCan** [comment]
Yes. I noticed this too.  What's happened to the monthly all solutions files, and the individual Core.zip?  Is there going to be a issue installing August, without the previous versions?

**Comment by Jenefer-Monroe** [comment]
June and July releases were pulled due to a bug in the API impact of one of the flows. 

Please see the top of the August release for notes: https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

We have tested May to August upgrade so you should be fine. 

Sorry for the bother.

**Comment by JanetK12** [comment]
Hello @Jenefer-Monroe !
Thank you for your answer!

So, could I just confirm: that means there is no July upgrade for the Core components, right? And then we need to do straight away the upgrade of the August releases? All the components of the August packages?

And would it be ok to upgrade the August packages if the last upgrade was the April upgrade? as we need to do the upgrade each three months, but here it means it will be four months this time? won't be anything broken?

**Comment by JanetK12** [comment]
Thank you @Jenefer-Monroe !

Also, the important question - 
I remember that few months ago we were discussing with you about the Power Platform for Admins V2 connector, that it will be already not just "preferably" to use, but in the August upgrade it will already automatically be used as a "must". Is it like that? Because we in our tenant decided not to use this connector. 
And If this is indeed already must be used, could I ask which flows and apps are now using this Power Platform for Admins V2 connector, so that we know what potentially will be turned off since we do not use the Power Platform for Admins V2 connector?

And the reason we decided not to use this connector is because the Power Platform for Admins V2 connector was in **preview**, and that means that it was risky to use it. Could I ask whether it is still in the preview? it was stated that :
"Microsoft wants to make sure that a connector is stable before we release it to general availability. Until that time, the connector is in preview. Previews are provided "as is," "with all faults," and "as available". 
We encourage you to use preview connectors in your development apps only and provide feedback. Preview functionality, including connectors, isn't recommended for use in production apps.
https://learn.microsoft.com/en-us/connectors/custom-connectors/preview-connector-faq"

**Comment by Jenefer-Monroe** [comment]
Yes the kit requires this connector now. And its in the main driving flow so the kit will not function without it by default. 

You may want to ask for a reconsideration from whomever made this decision. This was done due to a change in the product functionality in which you will not gather data for the entire tenant any longer without a feature enabled by this connector to escalate your user. 

You can read more about this here:  

### The product change
Here is information about the product feature which will make it so that you no longer gather all inventory without this change. 
[Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)

### How to address
There is a system to [escalate a user to system admin](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles#self-elevate-to-the-system-administrator-role) in an environment provided by the product team.
That is what this connector has done now as of the August 2024 (4.37) release.

**Comment by JanetK12** [comment]
> Yes the kit requires this connector now. And its in the main driving flow so the kit will not function without it by default.
> 
> You may want to ask for a reconsideration from whomever made this decision. This was done due to a change in the product functionality in which you will not gather data for the entire tenant any longer without a feature enabled by this connector to escalate your user.
> 
> You can read more about this here:
> 
> ### The product change
> Here is information about the product feature which will make it so that you no longer gather all inventory without this change. [Manage admin roles with Microsoft Entra Privileged Identity Management](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles)
> 
> ### How to address
> There is a system to [escalate a user to system admin](https://learn.microsoft.com/power-platform/admin/manage-high-privileged-admin-roles#self-elevate-to-the-system-administrator-role) in an environment provided by the product team. That is what this connector has done now as of the August 2024 (4.37) release.

Thank you for your answer @Jenefer-Monroe !
Just to confirm, maybe I understood wrong - 
1) so this connector is needed not only for one/two flows to work correctly, or some apps, but for the whole upgrade? Or I am wrong here? 
2) And What will happen if we still decide not to use this V2 connector? we cannot then do the upgrade? I am sorry, I am a little bit confused.
3) also, is this connector still in preview or maybe it is already not, so it could be safe to use it now?

**Comment by Jenefer-Monroe** [comment]
If your organization prevents you from creating this connection then you will not be able to to upgrade to August. 
When you say you are not allowed to use it, is that what you mean? Or is it a "best practice"

**Comment by Jenefer-Monroe** [comment]
To answer with your other questions

_1. so this connector is needed not only for one/two flows to work correctly, or some apps, but for the whole upgrade? Or I am wrong here?_

Its only called from two flows, but without it your inventory will not be complete. 
And as the inventory is the heart of the kit, therefore the kit as a whole will not function correctly without it.
There are the places its called
**_Admin | Sync Template v4 (Driver)_**
![image](https://github.com/user-attachments/assets/07c02439-612e-4d0f-bcf6-1c919d126814)

**_HELPER - Driver Escalation Check_**
![image](https://github.com/user-attachments/assets/3c02350c-398a-4d98-8cd3-ebea33a6865a)

_2. And What will happen if we still decide not to use this V2 connector? we cannot then do the upgrade? I am sorry, I am a little bit confused._

If you cannot create the connection, then you cannot upgrade
If you can create the connection but not use it (best practice), you you can upgrade, you would need to change the flows above to not use it, and then your inventory will not be complete.

_3. also, is this connector still in preview or maybe it is already not, so it could be safe to use it now?_

Sorry this is really feedback to the product team on the timing. There is little we can do. Without this action in this connector, the kit no longer works, so we had to use it early before the preview marker is removed.

To my knowledge its still marked preview only as they fix something for the sovereign clouds. And once that is fixed it will lose its preview marker.

I dont know what you mean by safe but we are only using the escalation call and so I would say its safe to use yes.

**Comment by JanetK12** [comment]
@Jenefer-Monroe thank you for your answers!

**Comment by Jenefer-Monroe** [comment]
You are so welcome. I'll go ahead and close then as no further action from starter kit team
