### ISSUE TITLE
[CoE Starter Kit - QUESTION] PowerBI COE service account required permission

### ISSUE THREAD

**Issue by BlueTongueBlueTongue** [microsoft/coe-starter-kit#8844]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Need guidance in setting up PowerBI CoE using a service account.

Does the PowerBI CoE service account need to be granted permission to access ExchangeOnline?
2 years ago, someone in my organisation has created a COE service account and given the account ApplicationImpersonation-Organization Management which I think is incorrect.
I think the person was trying to give access to the COE service account audit log read permission.
I read in here
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#create-your-environments

Here it mentions about setting up an Azure app for audit log reading but there are no details.

Can you please let me know what I should do?
Thanks.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I'm a little thrown off by you calling it a Power BI CoE user. I'll assume you mean the user setting up the kit. 

If so here is some help to know what you need form this user: [Which identity should I use to install the CoE Starter Kit?](https://learn.microsoft.com/power-platform/guidance/coe/setup#which-identity-should-i-use-to-install-the-coe-starter-kit)

The user does need to have access to an Office 365 mailbox that meets all requirements to use the [Office 365 Outlook](https://learn.microsoft.com/en-us/connectors/office365/) connector.

If you want to set up audit logs, you can do that with an app registration as described here: [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)
It used to be the case that the user needed permissions to that backend as we used a custom connector. But now with using HTTP that is no longer the case. 

Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
