### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - Data Export to Data Lake for CoE

### ISSUE THREAD

**Issue by Fuchs-b** [microsoft/coe-starter-kit#8846]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I've enabled Data Export for Data Lake for both Power Apps and Power Automate and configured them to point at a DLv2 Blob Store in our subscription. This has been setup for 5+ days now. We have seen most of the expected data populated in the blob store, but are missing several expected directory/export.

after we have setup the data export again. Is the same problem still present.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello, we just consume that DL we do not make it ourselves so you would need to reach out to product support to assist you with any issues there.

That said, at this time we do not recommend new users to onboard to the BYODL infrastructure. We are working actively on the second version of the Data Export feature and it does not use the DataLake any longer so any efforts you put in here would be wasted efforts.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
