### ISSUE TITLE
Can we Setup COE Toolkit using Service Principal?

### ISSUE THREAD

**Issue by patchivs** [microsoft/coe-starter-kit#8847]
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup
According to the above article I see identity used for setting up COE requires few roles and licenses like below

1. Power Platform Admin Role 
2. Power Apps Per User license
3. Power Automate Per User license
4. Power BI Premium per use
5. Office 365 Outlook mailbox enabled

All the above roles and licenses can be assigned to a Service Account undoubtedly. 

We have below doubts w.r.t Service Principal:

1. Please confirm if all the roles can be assigned to a Service Principal as we are planning to Set up COE using Service Principal.
2. Please provide us with an article regarding how to set up Solutions and Connections associated with COE using Service Principal. To be more specific, if it's a Service Account we just login to it and import all the required solutions into our Environment.  How can this be achieved with a Service Principal as it's not an account to login?
3. As COE is a combination of multiple connections, can we setup all the connections using a Service Principal?
4. What additional licenses and roles are required apart from the one's mentioned above?

**Comment by Jenefer-Monroe** [comment]
Hello. No unfortunately Service Principals cannot yet be used to install the kit. Not all the connectors that the kit uses support it yet.

**Comment by patchivs** [comment]
++ @Cooper, ***@***.***>

Please have a look into this

Regards,
Vaishnavi
Power Platform Admin Team
________________________________

**Comment by patchivs** [comment]
I sent this up to our security to see if we can go ahead and get exception for our existing service account.


Thank you,





Frederick Cooper

Applications Engineer

OGE Energy Corp.

Work: (405) 553-3293

Mobile: (405) 953-4494

 [cid:580cdceb-6206-48e8-b7d2-8a7d43f4aebe]

“Choose a job you love, and you will never have to work a day in your life." - Confucius

________________________________

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by kast424** [comment]
Is this still the case that we cannot install or upgrade the coe solutions using a service principal?
