### ISSUE TITLE
Compliance and Quarantine 

### ISSUE THREAD

**Issue by pakalask** [microsoft/coe-starter-kit#8849]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I have configured the feature **Compliance Process** and turned on Quarantine too for couple of environments in the CoE Setup and Upgrade Wizard. When makers don't respond  to that compliance request the app will be quarantined based on the environment variable we set and they get email every week that their app is quarantined. The question is how long / how many weeks CoE will send this email to makers about quarantine and will the CoE delete the app after certain number of these reminder emails. If we want CoE to delete the app automatically after certain number of reminders what flows do i need to turn on?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We do not have a technique in the kit to delete apps that are ignored for compliance, only to quarantine them, which you've already used. 

You could setup and use the [Inactivity Processes](https://learn.microsoft.com/power-platform/guidance/coe/setup-archive-components) though. if the app is quarantined then it will not getting launched anymore, and then they would be asked if its ok to delete with these processes. 
You can view this article on [Inactivity Processes](https://learn.microsoft.com/power-platform/guidance/coe/governance-components#inactivity-processes) to see a diagram that shows when we send mails.

If you want something more proactive than that, this would be a great place to extend the kit.

**Comment by pakalask** [comment]
So basically until they submit the compliance details the makers continuously receive email every week about their app being quarantined until we set up the inactivity processes like you suggested.

**Comment by Jenefer-Monroe** [comment]
The app will be quarantined at that point if you are using the [app quarantine features](https://learn.microsoft.com/power-platform/guidance/coe/setup-quarantine-components)

But yes we do not delete them. That would be a great spot to augment the solution if that is what you would like!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
