### ISSUE TITLE
[CoE Starter Kit - BUG] In the Power Platform admin view, makers data count is mismatched with the Power Bi report.

### ISSUE THREAD

**Issue by thotavinod590** [microsoft/coe-starter-kit#8850]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

In the Power Platform Admin View App, maker data count is mismatched with the Power Bi report. We are not understanding which data correct power Bi report data or In Power Platform Admin View App data

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Power Platform Admin view

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
You can expect small differences in the count here depending on last refresh. 

In the PPAdmin View App, there is a roll up formula that runs periodically according to the product itself, its a product feature. 
You can see when it was last run in the table and you casn force it to run
You can force these to calculate. Please see the tip in this product team article on [Rollup columns](https://learn.microsoft.com/power-apps/developer/data-platform/calculated-rollup-attributes#rollup-columns)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d374b7dc-82e2-499d-8855-be81a70bdb98)

In the PBI, you can refresh the datasource to see the current data, please see [Configure Scheduled Refresh](https://learn.microsoft.com/power-bi/connect-data/refresh-data#configure-scheduled-refresh)

**Comment by Jenefer-Monroe** [comment]
If this does not resolve, please dive down into a repro case and see which is the correct answer by exploring the data shown in each case.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
