### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow Last Run

### ISSUE THREAD

**Issue by SwatiMittal28** [microsoft/coe-starter-kit#8851]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are looking for cleanup and reassignment of orphaned flows. Unable to get the last flow run and it is blank. This is needed to identify if the flow is in use or not. Kindly help to get this info.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

April 2024

### What app or flow are you having the issue with?

Orphaned Flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, the kit does not yet collect the last run information for flows.
The product team has just recently made this available but we have not yet been able to collect it.

**Comment by SwatiMittal28** [comment]
May i know when this will be available in kit to collect the data?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
