### ISSUE TITLE
[CoE Starter Kit - QUESTION] is the May v4.31 CoreComponents the recommended install for Sovereign Clouds? 

### ISSUE THREAD

**Issue by wdanhof** [microsoft/coe-starter-kit#8852]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Ive had two customers install July CoreComponents v4.33 (this now appears to be removed everywhere on Git) we cannot upgrade to August due to the inclusion of the Power Platform for Admins V2 connector and being in GCC/GCC-H tenants.  Due to the issues with Julys CoreComponents is the solution for Gov to install the May v4.31 of Core? 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Admin - Sync Template V3 (Portals) 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
You can keep the July release if its already installed. The one flow that will be turned off by Microsoft is **_Admin | Sync Template v4 (AI Events)_**

You can go proactively turn that off as well. 
Then the rest of the kit will be fine while you wait for August release.

**Comment by wdanhof** [comment]
The July release in every instance across multiple tenants is failing to inventory any security roles or power pages sites. So had planned to role back anyways. Thanks for the response.

**Comment by Jenefer-Monroe** [comment]
I am unaware of any issues doing inventory of security roles. 

Power Pages are blocked now as they moved to the requiring that same connector (Power Platform Admin V2).

**Comment by wdanhof** [comment]
That’s good to know, is there road map for the V2 connector in Gov?

**Comment by Jenefer-Monroe** [comment]
The sovereign team and the product team are actively working on it now. Sorry I dont have an update. 
Here is the issue that will track it, that you can watch: https://github.com/microsoft/coe-starter-kit/issues/8835

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
