### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Toolkit Power BI template not showing auditlog data since June 21

### ISSUE THREAD

**Issue by CoryAMoore** [microsoft/coe-starter-kit#886]
### Describe the issue

Although the daily Power BI scheduled refresh is successful, our auditlog data is not updating since June 21. The usage data in the Power Platform Admin Center is showing up-to-date metrics.

### Expected Behavior

The Power BI report should contain the most up-to-date data in the auditlog, through previous day.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

Multiple versions

### What app or flow are you having the issue with?

Power BI report

### Steps To Reproduce

1. In the Power BI report, after successfully refreshing the data in PBI Desktop or PBI Service, the most recent data showed in the charts for Power Apps is June 21. 

### Anything else?

I have tried old and new template versions that are either Import or Direct Query and the same issue exists in both versions.

**Comment by JeneferM-MSFT** [comment]
Can you please go validate that the flows in the audit logs solution are still running and passing? The most common reason for failure of these flows, when they used to run, is that the connection got broken somehow. You may need to fix the connection and then the flows will work again.

**Comment by CoryAMoore** [comment]
You were correct - I had to recreate a new secret for the Azure App Reg being used for the custom connector, then was able to resolve the broken connections.  The data looks like it's flowing again now.  Thank you.

Do you know if there is a way to get the audit log history we've missed while this issue has been going on?  It's roughly a month's worth of data that's now missing from the Power BI CoE report.

**Comment by JeneferM-MSFT** [comment]
There is not. However the new version of the audit logs solution does send an email alert to the admin email when it fails, so you will be notified in the future when this happens

Thanks for using CoE!
