### ISSUE TITLE
[CoE Starter Kit - BUG] Blogs in CoE Admin Command App

### ISSUE THREAD

**Issue by Titoleto** [microsoft/coe-starter-kit#8864]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

If we visualise the blogs that are in the Platform news group, when we click on Launch, it always opens the first news (regardless of whether it is from the Power Apps, Power Automate or Microsoft Copilot product), it only works well if the news is from Power BI.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. I do repro and will investigate for upcoming release.

**Comment by Jenefer-Monroe** [comment]
It appears this is due to the way Details List is capturing clicks. I do see it work sometimes and other times it does not.

**Comment by Jenefer-Monroe** [comment]
ok issue ended up being that the id field started coming back blank from the RSS field so we have to derive it

![Image](https://github.com/user-attachments/assets/25e6e70c-4ac3-44da-9947-00caf136f299)
![Image](https://github.com/user-attachments/assets/a815f663-73cb-4d3f-b7c9-5355f7d1fa93)
![Image](https://github.com/user-attachments/assets/0edb84f3-4e34-44ce-b5a3-035828b808f8)

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
