### ISSUE TITLE
[CoE Starter Kit - QUESTION] Audit log App registration configuration for CoE Starter Kit

### ISSUE THREAD

**Issue by zellos13** [microsoft/coe-starter-kit#8869]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

In relation to this article: [Audit logs configuration](https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup#updating-the-audit-log-solution) and this one: [Audit Logs solution fails after upgrade](https://github.com/microsoft/coe-starter-kit/issues/1424), I would like to know how to configure an app registration in Azure so the permissions are sufficient.

I could not find the information in the CoE documentation in MS Learn, or I needed to search harder.

Please point me in the right direction.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2024

### What app or flow are you having the issue with?

App registration

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, here is how to configure it using the [Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#create-a-microsoft-entra-app-registration-for-the-office-365-management-api)

Note there is a new API, we shipped with that for the August release and documentation will be available later this week, but here is a bug that describes it for now: https://github.com/microsoft/coe-starter-kit/issues/8482#issuecomment-2211797168

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
