### ISSUE TITLE
CoE core component solution upgrade failure

### ISSUE THREAD

**Issue by gauti786** [microsoft/coe-starter-kit#8870]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Upgrade failure from version 4.4.2 to 4.11 and error is 'solution "center of excellence - core components" failed to import : import as holding failed with exception : cannot delete attribute : admin_AuditLogId from Entity: admin_AdminLog since the attribute is not a custom field.

### Expected Behavior

It should upgrade as happened in dev and test tenant. Issue is occuring just in production tenant.

I am upgrading manually.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What app or flow are you having the issue with?

Entity- admin_AuditLog

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
It appears this is happening for a variety of tables, complaints about the ID field of a table. 
That field does still exist. This is a bug in product upgrade code. Please create a support ticket with the product, we are also tracking internally via https://github.com/microsoft/coe-starter-kit/issues/8831

**Comment by gauti786** [comment]
@Jenefer-Monroe Apparently, I could get it done by first importing the solution and choosing the option to 'stage for upgrade' instead of upgrade.

Once new solution is there, I can click 'Apply for upgrade' and it works like a charm.

**Comment by Jenefer-Monroe** [comment]
oh nice! Thanks for letting me know! Ill add to to the notes in the other issue.

**Comment by shmcarth** [comment]
There was a regression in the solution framework that is fixed. It will be completed rollout worldwide by this weekend. Please retry.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
