### ISSUE TITLE
[CoE Starter Kit - BUG] Inactivity Notifications - can base on usage rather than modified?

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#8872]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Currently, many Power Platform admins face the challenge that the CoE (Center of Excellence) does not provide Flow Inactivity Notifications based on usage, only on the modified date. We have makers with numerous flows. Is there a way to run a flow that automatically handles "Excuse from Inactivity Flows" instead of manually going to each flow and clicking "Yes," then "Save & Close"?

### Expected Behavior

Flow Inactivity Notifications based on usage rather than modified date.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.24

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We do not have such a flow, no. Seems like a great add on you could do for "on new" for the flow table. 

We do have a re-design for the feature on the backlog but it's not something we will be able to fund soon due to our current efforts.
