### ISSUE TITLE
[CoE Starter Kit - QUESTION] Updated documentation on DLP Policy - Power Platform Admin V2

### ISSUE THREAD

**Issue by radityoardi** [microsoft/coe-starter-kit#8874]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are using COE Starter Kit to analyze our Power Platform usage in the organization and frequently updated in almost monthly basis.

For this August 2024 release, we noticed that there's a new connector introduced in the Core Component, and that is "Power Platform for Admins V2". We're planning to upgrade to August 2025. Since we already have DLP in place for all requirements, we need official documentation to justify the Change Request. However, we found the new connector is not listed in https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

Can we ask if any of the COE team here to update, or is there avenue for us to update on our own?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2024

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Oh no, thank you! I thought I had added that for sure! 
Steve is making some quick updates for us this week and I just asked if he would add this for us too. 
Thank you Steve!
And apologies again.

**Comment by radityoardi** [comment]
Thank you!
I guess I'll monitor the page in 1 week forward. Thanks for the swift response! I'll close this issue once I see it's listed on the page.

**Comment by MartinWGT** [comment]
Hi. I've come across this issue while deploying the September release. The documentation still does not mention "Power Platform for Admins V2".  https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

**Comment by radityoardi** [comment]
> Hi. I've come across this issue while deploying the September release. The documentation still does not mention "Power Platform for Admins V2". https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies

Yep. Me too, waiting for this to happen.

**Comment by Jenefer-Monroe** [comment]
Sorry we have some issues updating documentation lately. Steve is pressing.

**Comment by Jenefer-Monroe** [comment]
This has finally been resolved yeah! The two connectors that were missing from the list are now fixed. 

![image](https://github.com/user-attachments/assets/adc658e3-8638-4cb6-b867-a0f1429e1fc0)
