### ISSUE TITLE
[CoE Starter Kit - QUESTION] CLEANUP Orphaned users flow QUESTION

### ISSUE THREAD

**Issue by steph-ong98** [microsoft/coe-starter-kit#8876]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

This is a follow up to #8808.
Through this we have two issues/questions.

1. We have tried to change the http connection to the graph URL as recommended, however, it is coming up with an error stating that there is an item with the same key already in placed, as shown below. How can we check which item is causing this error?
![image](https://github.com/user-attachments/assets/d662d908-4054-4ff7-89d8-a168c5c5b036)

2. So, we tried a different method of creating a new http connection with the right graph URL, and connected the flow to that. However, the flow is still not working as it runs longer than an hour and fails (when it is suppose to be less than 5mins). We keep getting stuck at the Get Group action under the Find New Orphans and Update Existing Users action. We are unsure at this stage on how to approach this.  

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Orphaned Users)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Issue 1 about the error connecting is unfortunately a product issue. If you fail to create a connection there isnt much we can do. Glad you got around that. 

For the second issue, can you please share a screenshot of where you failed?

**Comment by steph-ong98** [comment]
Hi Jenefer,

It took 3 hours to get group, as shown below.
![image](https://github.com/user-attachments/assets/d5fc8f71-a7b7-4d90-b186-fff4c620e97f)

But failed here.
![image](https://github.com/user-attachments/assets/1b173ef0-0b47-4c2d-b849-ca4b59d1ff29)

The errors are from Apply to each group action -> Group Found scope, and as there's no group returned so we will go to "Get Transitive Members" scope, and then got Bad Request on List Group Members Transitive step

![image](https://github.com/user-attachments/assets/60c133c0-6cb8-4d90-a291-5b667e2fde01)

![image](https://github.com/user-attachments/assets/c9d77505-7013-48e8-acee-a3edbd1ec3d6)

![image](https://github.com/user-attachments/assets/6cb9293c-33c2-405d-96ce-6f21e3ab7137)

**Comment by Jenefer-Monroe** [comment]
This started running before you fixed up your connection correct?

**Comment by steph-ong98** [comment]
Hi Jenefer, unfortunately no, when the connection is correct, we are getting the same error. 
So currently there seems there are two connectors connecting to the flow, one is the correct url and the other is not. We think it is still taking the wrong connector (we were worried if we delete that connector, it might disrupt other flows as it is connected to many other flows). Therefore, we tried manually changing the flow to the right one which incorporates an unmanaged layer, but this one also fails at the same spot. 

Could you please let us know which step in the orphaned user flow is using this HTTP connector? Just so we can double check if we are setting the connector correctly?

**Comment by steph-ong98** [comment]
Hi Jenefer, thank you. We did what you suggested and it works. The flow run succeeded. But with the change there is currently an unmanaged layer. Would that be an issue? (especially when it comes to upgrading in the future - with the remove unmanaged layers step).
![image](https://github.com/user-attachments/assets/4dc44294-6841-49ab-ac32-be586cba14a6)

**Comment by Jenefer-Monroe** [comment]
The change I recommended would not produce an unmanaged layer as the changes were not done to the flow itself but just to the connection and the connection reference. So please go ahead and remove that and make sure that its still working for you, perhaps a change was made unintentionally

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
