### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION Power Platform Solution

### ISSUE THREAD

**Issue by thenchozGRE** [microsoft/coe-starter-kit#8877]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I was looking for a way to regroup flows and apps into solution in a custom dashboard, but I can't find the link between those table.
From the BI semantic model of the CoE, there is no link between solution and apps/flow, and looking into the Dataverse table I couldn't find any link. But this relationship should exist somewhere, as one can go from flow to solution in the Admin View app.

Does anyone know how to access this data?
Thanks !

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2024

### What app or flow are you having the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. 
Retrieving the components of a solution is not very simple unfortunately. We use a table in each envt called solutioncomponents which is hidden and has some undocumented fields we use to find object types. 
Honestly we kind of force tested this until it returned what we wanted. 
You can play around though and see if you find something better / easier. If you do please let us know!
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3562f923-a77c-44b9-b9fa-67b4a703ede2)

You can find this in the **_CLEANUP HELPER - Solution Objects_** flow (note in Feb it was still part of the **_Admin | Sync Template v4 (Solutions)_** flow)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
