### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI - Flow Deep Dive Does Not Filter 

### ISSUE THREAD

**Issue by Sinder088** [microsoft/coe-starter-kit#8881]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When using the COE Dashboard August 2024 version, i am unable to filter for environment name in the page

![image](https://github.com/user-attachments/assets/36b71428-e7ae-4065-97cd-5cf9ed500139)

### Expected Behavior

When i filter for environment name, i expect to only see flows for that environment in the list. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.35

### What app or flow are you having the issue with?

Production_COEDashboard_August

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open COE Dashboard
Naviaget to flow deep dive
select specific environment in environment name filter.

**Comment by Jenefer-Monroe** [comment]
release is now available. https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2024
