### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Center Command Center showing old update warning message

### ISSUE THREAD

**Issue by hbazerbashi** [microsoft/coe-starter-kit#8882]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After upgrading to August 4.37 release, I noticed the Admin Command Center is showing a message saying "Your CoE Starter Kit solution was installed on Feb 2024. The latest version was released on Jul 2024. Please download and install the latest version.".

Just so you know, this issue exists only in the PROD environment. Before the PROD upgrade, DEV and TEST upgrades to 4.37 didn't show the same issue.

Is there a step I missed or something I need to do?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open Admin Command
2. Observe the update warning message

### Anything else?

CoE version
![image](https://github.com/user-attachments/assets/23f5d575-78a5-4b81-a2cc-5cb4f237b485)
Solution upgrade history showing no errors
![image](https://github.com/user-attachments/assets/66f3ffc5-2fb0-43db-a770-5ba9c97399aa)
Warning message showing incorrect info
![image](https://github.com/user-attachments/assets/85d76bac-7623-46d7-b89e-5687e76a38ad)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
