### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (Orphaned Users); Look up in AD - Tenant User Count returns error code 400

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#8885]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I get a 400 in that action of that flow. 

I also get this error in the Get Tenant User for Details action.
{
  "error": {
    "code": "0x80040217",
    "message": "Entity 'admin_maker' With Id = d5fe813e-0caa-432a-b2ac-d555aa91bd1c Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "ceb443ab-b150-ed11-bba2-0022481ffab0",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "e64fde1a-2666-4a54-905a-ddd4e91bca2a",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMessageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "Entity 'admin_maker' With Id = d5fe813e-0caa-432a-b2ac-d555aa91bd1c Does Not Exist"
  }

### Expected Behavior

Flow run without error

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Orphaned Users)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run flow; see error

**Comment by Jenefer-Monroe** [comment]
Hello please share a screenshot of the failure you are referencing.

**Comment by RickKush** [comment]
![image](https://github.com/user-attachments/assets/6a6e9e4b-7b07-4d06-8961-eae5770be247)

**Comment by Jenefer-Monroe** [comment]
This is typically due to a mis configured connection.

### Fix HTTP with Microsoft Entra ID (preauthorized)
Make sure all the **_HTTP with Microsoft Entra ID (preauthorized)_** connections are pointing to your graph URL ![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/911668af-099e-41a5-a248-40e98bb9fc4e)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1a39d4c4-9135-4c1e-9c49-7ec05d5921db)

**Comment by RickKush** [comment]
All good now!
