### ISSUE TITLE
[CoE Starter Kit - QUESTION] Unable to open issues in github

### ISSUE THREAD

**Issue by nasilvae** [microsoft/coe-starter-kit#8887]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Team, 

Can we add antonrobbins@microsoft.com to the CoE github group to be able to submit issues? He doesnt have access to submit bugs to the channel. 

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
