### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - CHanges are not being saved

### ISSUE THREAD

**Issue by kundan76** [microsoft/coe-starter-kit#8889]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to chnage the logo on admin_emailbodyStart on variable . I put the logo url and kepp changes and nothing happen . When i refresh the page it bremain same. I even stopped the Hepper-email flow and tried . 

### Expected Behavior

Logo changes on EMail 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

Admin Command Center

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Play  COE Admin Command Center
Click on environment variables
Select Admin_eMailbodystart
Click Edit and change the url of logo 
Save
CLose 
Refresh athe page and changes made are revered to default

**Comment by Jenefer-Monroe** [comment]
Please go update the env variable in the product itself. See if you fail there too and you will see the error message / reason
Make sure you add a current value dont update default or it will get overwritten at some point.
![image](https://github.com/user-attachments/assets/00aa61b9-fe50-4f2b-a336-d148913c76ac)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
