### ISSUE TITLE
Admin Sync Template workflow fails to update cloned environments in COE due to missing App ID error when calling Sync Helper Apps flow.

### ISSUE THREAD

**Issue by rajamanickamg2** [microsoft/coe-starter-kit#8890]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are experiencing an issue with the Microsoft Center of Excellence (COE) Starter Kit, specifically within the Admin Sync Template workflow. When attempting to update cloned environments, the process fails due to a missing App ID error when invoking the Sync Helper Apps flow. The error occurs during the sync process, preventing the cloned environments from being correctly updated in the inventory. We have verified that the necessary environment variables and flows are configured correctly, yet the issue persists. This is impacting our ability to maintain an up-to-date inventory of apps across environments. We require assistance to resolve this error and ensure that the sync process functions as expected

### Expected Behavior

The workflow has to capture the information when the environment has been cloned

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Admin Sync Template V4

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1.Clone the Existing environment
2.Create.modify the app in New Cloned environment
3.After changes happened in  the environment ,Admin Sync Template workflow will be trigeered to check any app changes happened in this environment and this will check with APP id into Dataverse inventory Tables by calling SYNC Helper Apps flow .this flow checks new app/existing app and getting failed due to app id is missing in inventory. 

### Anything else?

Entity 'admin_app' With Id = 1717e948-28f7-407c-94dd-6668c228434a Does Not Exist

**Comment by Jenefer-Monroe** [comment]
Sorry I am not following you. You cannot expect GUIDs to match in a cloned environment, if that is what you mean.

**Comment by rajamanickamg2** [comment]
THis is the error:
Error:
Action 'Get_App_from_Inventory' failed

Error Description:Entity 'admin_app' With Id = 688cb629-6ed3-4634-82ef-d4a9c3f54564 Does Not Exist
Environment :Cloned environment (NOT COE) .The Team has cloned environment and getting this error for their environment

Based on our understanding this 688cb629-6ed3-4634-82ef-d4a9c3f54564 Powerapp does not exist in COE Data verse inventory. But this app is exists in environment .SO we are thinking how it is missed in our COE Dataverse and how we can add it back .Daily basis we are getting this error for cloned environment

**Comment by Jenefer-Monroe** [comment]
Got it, please find the environment in the product's admin page: https://admin.powerplatform.microsoft.com/environments
And see what its settings are for admin mode and state.
![image](https://github.com/user-attachments/assets/5c169eac-54e2-46d5-8ca5-abd7be893b88)

The kit cannot gather data for some states because they are not returned in the connectors, and I've noticed that right after an envt copy the state is not what we need for a few days. 

While you are there please also check if the identity running the flow has System Admin permissions to the new environment.

**Comment by rajamanickamg2** [comment]
I have checked cloned environment is Admin mode is enabled ."This environment is currently in administration mode, so only admins can sign in to it. You can turn off administration mode in settings"

**Comment by Jenefer-Monroe** [comment]
OK yes that means that the information will not be collected into the kit. This is just a product limitation in the way the connectors work.

**Comment by rajamanickamg2** [comment]
I got it. " the way the connectors work."- Here you have mentioned about workflows right ?

**Comment by Jenefer-Monroe** [comment]
Yes we use connectors to fill the inventory in the cloud flows. So since they cannot collect the data we cannot inventory it.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
