### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to load CoE Admin Command Center Due to DLP Policy Error

### ISSUE THREAD

**Issue by ChrisWiANZ** [microsoft/coe-starter-kit#8891]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When attempting to open the [CoE Admin Command Center](https://make.powerapps.com/environments/47d35a81-xxxx/apps#), it returns the error: 

Error Code: AppForbidden
Session Id: ccdbf0ad-a6a3-4e59-ac09-baf1c6515ce6
Activity Id: eadf887f-14a4-4f5d-b5d7-8a680b0e1e5b
Timestamp: Fri Aug 30 2024 11:21:14 GMT+1200 (GMT+12:00)
It looks like this app isn't compliant with the latest data loss prevention policies.
UciError: It looks like this app isn't compliant with the latest data loss prevention policies. at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.0603383745d94ae72950081593f63a69.js:33:973470) at https://content.powerapps.com/resource/uci-infra-bus/scripts/custompage.3b5f3b6a202e09e8331ab52bcfb28324.js:4:23196

We were able to access this app before setting up a new DLP Policy. The details of the policy are:

We have a default company dlp policy - which allowed the COE Admin Center to work.
Once we have created a new COE policy, we have excluded it from the default policy and set up the new policy as multiple environments, only selecting the new dlp policy.

Once we have setup the new dlp policy,  we have allowed the following connectors:

Approvals
Azure Resource Manager
HTTP
HTTP with Microsoft Entra ID (preauthorized)
Microsoft Dataverse
Microsoft Teams
Office 365 Groups
Office 365 Outlook
Office 365 Users
Power Apps for Admins
Power Apps for Makers
Power Automate for Admins
Power Automate Management
Power Platform for Admins
Power Query Dataflows
RSS

We have attempted to wait for approx. 1 hour for the policy to take effect, after the policy was amended due to missing one of the required connectors. 

We have again attempted to load the CoE Admin Command Center app and still receive the same error. We are also receiving this same error for the following other apps:

- [CoE Maker Command Center](https://make.powerapps.com/environments/47d35a81-xxxx/apps#)
- [Data Policy Impact Analysis](https://make.powerapps.com/environments/47d35a81-xxxx/apps#)
- [Manage Permissions](https://make.powerapps.com/environments/47d35a81-xxxx/apps#)

Any assistance with resolving this issue would be greatly appreciated. Thank you

### Expected Behavior

The list of apps should work properly.
![CoEError1](https://github.com/user-attachments/assets/49f16e29-4d64-4dbb-a6d3-dd0185d3e63f)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

When attempting to open the [CoE Admin Command Center](https://make.powerapps.com/environments/47d35a81-xxxx/apps#), it returns the error: 

Error Code: AppForbidden
Session Id: ccdbf0ad-a6a3-4e59-ac09-baf1c6515ce6
Activity Id: eadf887f-14a4-4f5d-b5d7-8a680b0e1e5b
Timestamp: Fri Aug 30 2024 11:21:14 GMT+1200 (GMT+12:00)
It looks like this app isn't compliant with the latest data loss prevention policies.
UciError: It looks like this app isn't compliant with the latest data loss prevention policies. at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.0603383745d94ae72950081593f63a69.js:33:973470) at https://content.powerapps.com/resource/uci-infra-bus/scripts/custompage.3b5f3b6a202e09e8331ab52bcfb28324.js:4:23196

We were able to access this app before setting up a new DLP Policy. The details of the policy are:

We have a default company policy - which allowed the COE Admin Center to work.
Once we have created a new COE policy, we have excluded it from the default policy and set up the new policy as multiple environments, only selecting the new dlp policy.

Once we have setup the new dlp policy,  we have allowed the following connectors:

Approvals
Azure Resource Manager
HTTP
HTTP with Microsoft Entra ID (preauthorized)
Microsoft Dataverse
Microsoft Teams
Office 365 Groups
Office 365 Outlook
Office 365 Users
Power Apps for Admins
Power Apps for Makers
Power Automate for Admins
Power Automate Management
Power Platform for Admins
Power Query Dataflows
RSS

We have attempted to wait for approx. 1 hour for the policy to take effect, after the policy was amended due to missing one of the required connectors. 

We have again attempted to load the CoE Admin Command Center app and still receive the same error. We are also receiving this same error for the following other apps:

- [CoE Maker Command Center](https://make.powerapps.com/environments/47d35a81-xxxx/apps#)
- [Data Policy Impact Analysis](https://make.powerapps.com/environments/47d35a81-xxxx/apps#)
- [Manage Permissions](https://make.powerapps.com/environments/47d35a81-xxxx/apps#)

Any assistance with resolving this issue would be greatly appreciated. Thank you
![CoEError1](https://github.com/user-attachments/assets/2b861213-3f62-4ca9-ac6f-813febc462f4)

**Comment by Jenefer-Monroe** [comment]
Hello you must be missing some DLP. If you already have the inventory complete you can see what DLPs impact an envt in the Power Platform Admin View app
![image](https://github.com/user-attachments/assets/73999aaa-795f-4714-9eba-45d89c933ff8)

**Comment by ChrisWiANZ** [comment]
issue appears to be resolved by adding additional connectors - 

HTTP With Microsoft Entra ID (deprecated) [DEPRECATED]
Microsoft Dataverse (legacy)

And also resaved the DLP Policies.

Working now ! thank you for the help!
