### ISSUE TITLE
[CoE Starter Kit - BUG]  Solution "Center of Excellence - Core Components" imported successfully with warnings:

### ISSUE THREAD

**Issue by HarithaE508** [microsoft/coe-starter-kit#8892]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After importing the solution, im getting the following error. 

Solution "Center of Excellence - Core Components" imported successfully with warnings: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute 'value' was not found for environment variable 'admin_AuditLogsAudience'."}}".

What I need to do?

### Expected Behavior

The solution needs to be imported successfully! without warnings

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.34

### What app or flow are you having the issue with?

Importing

### What method are you using to get inventory and telemetry?

None

**Comment by bethleota** [comment]
@HarithaE508 I got this same error when importing the Core solution.  I see you marked this as Completed. Do you have a fix for this?
