### ISSUE TITLE
[CoE Starter Kit - QUESTION] Orphaned Connection References

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#8893]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello CoE Team,

Hope all is well.

I have two questions please:

1. Could you please clarify what the "Orphan Connection Reference Identities" are? 
2. And what functionality do you provide in the "Manage Permissions" app for these?

I looked in the "Manage Permissions" app, and saw in the navigation pane under "Connections" the "Orphan" option.

![image](https://github.com/user-attachments/assets/1f9003fd-68d6-4556-83bd-746359b2bb72)

In my test tenancy I don't have any orphaned, but have seen them before in customers' tenancies previously. 

Any help would be greatly appreciated.

Thanks very much,

Garry

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Manage Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Connection Reference Identities are stored with the following flow: **_Admin | Sync Template v4 (Connection Identities)_**

As part of that we find connections that were made by people no longer in the organization (Entra) 

Manage Permissions lets you clean these up
![image](https://github.com/user-attachments/assets/71ba72e3-687c-4899-8f8e-381c629ae782)
![image](https://github.com/user-attachments/assets/a0b1324c-e131-4178-9a06-9e5cb711a0f6)

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe,

Thanks so much for the quick reply and all the information. 

Just to clarify, when you say "clean them up" they delete them from the tenancy or just the dataverse environment where the CoE is installed? I imagine it's from the tenancy, right?

Thanks very much,

Garry

**Comment by Jenefer-Monroe** [comment]
Correct, it deletes the connection from the power platform tenant itself, not just the inventory.

**Comment by GarryPope** [comment]
Thanks @Jenefer-Monroe. Like always, superb support. Please close this ticket. Have a nice weekend!

**Comment by Jenefer-Monroe** [comment]
you bet, thanks for the kind words :)
