### ISSUE TITLE
[CoE Starter Kit - BUG] "App Excused From Compliance" setting not taking effect

### ISSUE THREAD

**Issue by adamx9035** [microsoft/coe-starter-kit#8894]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

With the "App Excused From Compliance" already set to "Yes" for an app, the app still keep getting quarantined due to not being compliant. The setting appears not taking effect.

### Expected Behavior

Expect the setting can take effect, so the app is not getting quarantined due to not being compliant.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.21

### What app or flow are you having the issue with?

Admin | Quarantine non-compliant apps

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello the setting does not impact quarantine only the compliance side. 
So you can say excuse from compliance and it will never get put into the compliance process at all. Once its in the compliance process the quarantine process is separate.

**Comment by adamx9035** [comment]
Got it. One more question. -- Is there a way to cancel the compliance process already kicked off for the app? For example, if I set the "Admin Requirement - Risk Assessment State" to "None", and with the "App Excused From Compliance" set to "Yes", will this prevent the compliance process kicking off for the app again?

**Comment by Jenefer-Monroe** [comment]
That should do it, yes.

**Comment by adamx9035** [comment]
Yep, it did. You can close this issue now. Thank for the quick support!

**Comment by Jenefer-Monroe** [comment]
You bet, thanks for using the CoE Starter Kit!
