### ISSUE TITLE
Insufficient permissions error in archive and clean up flows

### ISSUE THREAD

**Issue by AhmadiRamin** [microsoft/coe-starter-kit#89]
Hi,

In the **Admin | Archive and Clean Up v2 (Start Approval for Flows)** and **Admin | Archive and Clean Up v2 (Start Approval for Apps)** flows, we get following error:

The request was archiving was unable to process as the user has insufficient permissions to the CoE Environment. Please give them permissions to Approvals in the CoE to proceed.

The action throwing that 400 error is "**Create an approval**"

Do you have any idea how we can fix it?

**Comment by devkeydet** [comment]
This is a repo in transition.  We are not ready to track CoE Starter Kit issues here.  Please use the existing repo.  See https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support for more details.

**Comment by andersidahl** [comment]
Did you ever figure this one out in a easy way? Same issue here. Can't find anything in the docs on how to properly give access.
