### ISSUE TITLE
Time out trying to uninstall core

### ISSUE THREAD

**Issue by AbuLLcc** [microsoft/coe-starter-kit#8902]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have been trying to uninstall the Power Platform Centre of Excellence Core Component Solution for around five hours, however, the only thing I got is this error: 
![Screenshot 2024-09-02 182603](https://github.com/user-attachments/assets/ebdf9810-0935-484c-a824-ca48d204aa45)
I have treid using different account but still getting the same result.

### Expected Behavior

Uninstall the Centre of Excellence Starter Kit Core component from two of our environments.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.3.3

### What app or flow are you having the issue with?

The solution itself cannot be uninstalled

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello the UX often times out before the action is complete. If you go look at solution history you can watch and wait for it to complete
![image](https://github.com/user-attachments/assets/5b3ea315-5cb6-44df-8861-cce99350d108)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
