### ISSUE TITLE
Update PBI to fill have data on last-30-day-launch for all apps

### ISSUE THREAD

**Issue by ValiPrk** [microsoft/coe-starter-kit#8906]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, 

We are trying to find out what usage we had on apps in the last month, so we found the "Launches in the last 30 days" column that would be exactly what we need, but it's not populated with values. I checked previous comments and saw that it is somehow dependend on BYODL and as we are not using BYODL, is there anyway that we can obtain this info for Model-Driven and Canvas apps?

Thank you very much for your help!

Valentin

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents 4.37

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. BYODL is no longer a recommended pattern today as we are working on Data Export V2 which will not rely on the Data Lake. 

For Cloud flow infra you can collect launches for Canvas apps but not MDAs as only Canvas launches are included in the data source we use. 
To setup please see: [Collect audit logs using an HTTP action](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by ValiPrk** [comment]
Thank you for your reply, I will try to make the steps from the article, but I will be out of office for the next 2 weeks, so I think we can close this section and if I still have questions, then I will contact you again.
Wish you a great day forward
Valentin

**Comment by ValiPrk** [comment]
Hello,

I've checked everything in our system as in the shared article and it's strange, we have the app in Azure from a period, our audit flow are working properly, we already have the "App Last launched on" column populated.
My question would be, what is different from the "App Last launched on" column? how can we also populate the "Launches in the last 30 days" column?

Thank you

**Comment by Jenefer-Monroe** [comment]
Launches in the last 30 days is a calculation done in the BYODL architecture in Power Query for the Dataflows that do write back.

**Comment by ValiPrk** [comment]
Ok, since BYODL is no longer recommended and we do not use it, is there any other way to obtain the valuable data in the column? 
I also found out that "Power Query Dataflows connector is not supported in sovereign cloud clusters (e.g. China, Germany) other than US Government Community Cloud" and I'm guessing that this is why we don't have it (we are not is the US)

Thank you for your reply

**Comment by Jenefer-Monroe** [comment]
You could do this in power automate instead. We have not done that as the API cost hit to do this per app regularly is too high for large organizations. Or you could probably do the calculation in PBI as that has the same Power Query capabilities. 
We do have making this available to non BYODL users on the backlog but unfortunately with just me on the kit at this time, its doubtful I will be able to fund it anytime soon.

**Comment by ValiPrk** [comment]
Thank you for your reply, do you have an example of such a flow? or at least a calculation formula? It would help us allot.

**Comment by Jenefer-Monroe** [comment]
I dont have one no. Nor a clever idea that wont blow out the API calls. 
But for a random app you could filter the audit logs for the last 30 days then get a count of what is returned. 
This doesnt really scale for all apps in the tenant unfortunately.

**Comment by ValiPrk** [comment]
The idea was to have this info for all apps present in that column, but if it's not possible and it will blow out the API calls, then I guess that we have to wait for further improvements.
Can this feature be suggested to be introduced in the future?

Valentin

**Comment by Jenefer-Monroe** [comment]
Yes happy to put this on the backlog though do note that it will sit for a bit as we focus exclusively on Data Export V2 work

**Comment by ValiPrk** [comment]
Thank you very much for your collaboration!
