### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION "Last launched on" column not populated for Model-Driven apps

### ISSUE THREAD

**Issue by ValiPrk** [microsoft/coe-starter-kit#8907]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello,

I would like to have some analytics data for model-driven apps in the CoE tabels (PowerApps app), but I see that the "Last launched on", "Launches in the past 30 days" columns do not have any values for the model-driven apps.
Is there any chance to get those columns populated and obtain some analytics for the model-driven apps?

Thank you for your reply
Valentin

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents 4.37

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello yes thats correct unfortunately we do not have launch information available to us from MDA's, only from Canvas apps.

**Comment by Jenefer-Monroe** [comment]
I believe the product team is working to make the MDA information available but I cannot comment on when that may complete. Until then we have no source to collect this information.

**Comment by ValiPrk** [comment]
Thank you very much, I'm looking forward to having all the info in the same place. Until then., thank you very much for your reply.
Wish you a great day forward!
Valentin
