### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION "App Modified By" column displays "Microsoft Power Platform" instead of actual user

### ISSUE THREAD

**Issue by ValiPrk** [microsoft/coe-starter-kit#8908]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello, 

With the MC757614 update, "App Modified By" column displays "Microsoft Power Platform" instead of actual user that last modified the app, is there a way now to obtain the name of the user who last modified the app?

Thank you 
Valentin

### What solution are you experiencing the issue with?

None

### What solution version are you using?

CenterofExcellenceCoreComponents 4.37

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello we do not track who last modified objects in the kit. Perhaps I misunderstand the question, can you please share a screenshot?

**Comment by ValiPrk** [comment]
Hi, 

I'm referring to the users who last edited the app from the version history, if you go to an app you will see the exact user who last edited, but on the tables it will appear as "Microsoft Power Platform".
![Modified by](https://github.com/user-attachments/assets/00b1bb5f-dbb8-4d65-a5e5-57f9b110f19a)
![Change message](https://github.com/user-attachments/assets/30e92313-765f-4c19-888c-db06e9301349)

**Comment by Jenefer-Monroe** [comment]
Ok I see now, thank you. 
Yes unfortunately this is feedback for the product team and not the kit. 
The kit is only able to show what the product records. And we dont keep track of who most recently modified apps anyway. 

Sorry I couldn't be of more assistance.

**Comment by ValiPrk** [comment]
Thank you very much for your help so far, wish you a great day forward!
Valentin
