### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why am I getting Notifications about job assignments from git on this project.

### ISSUE THREAD

**Issue by binaryjam** [microsoft/coe-starter-kit#8909]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

m getting CI notifications,,

Something about the proejct isnt quite right, I think Ive been assigned something erroneously casuing this.  Can you look at that. please

---------- Forwarded message ---------
From: Simon Tocker <[notifications@github.com](mailto:notifications@github.com)>
Date: Mon, 2 Sep 2024, 14:57
Subject: [microsoft/coe-starter-kit] Run failed: Auto Assign Issues to Projects - main (e82238a)
To: microsoft/coe-starter-kit <[coe-starter-kit@noreply.github.com](mailto:coe-starter-kit@noreply.github.com)>
Cc: Ci activity <[ci_activity@noreply.github.com](mailto:ci_activity@noreply.github.com)>

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
If you go to the project https://github.com/microsoft/coe-starter-kit
You can see what you have set for watch. We suggest people setup for Releases only. 
![image](https://github.com/user-attachments/assets/08d84876-0d3e-4b6b-a130-a431644aa571)
![image](https://github.com/user-attachments/assets/0f002035-6614-436b-9f0c-7a65bc3d0edf)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
