### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Call Updates)

### ISSUE THREAD

**Issue by anu7382** [microsoft/coe-starter-kit#8910]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Here the child flow is running successfully with no errors but when the same child flow is called in a parent flow, it is throwing an error - "Failed to parse invoker connections from trigger 'manual' outputs. Exception: Could not find property 'headers.X-MS-APIM-Tokens' in the trigger outputs. Workflow has connection references '["shared_webcontents-1"]' with invoker runtime source."
![Screenshot (123)](https://github.com/user-attachments/assets/1dce84d2-0d63-4661-9c21-aefd5cbd2cab)
![Screenshot (124)](https://github.com/user-attachments/assets/a261bde9-d15b-4071-a403-2f5011d54bcf)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Call Updates)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Please make sure you dont have unmanaged layers on the (orphaned users) flow, and then also restart it. 
Sometimes flows cache trigger properties until they are reset.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
