### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Setup and Upgrade Wizard App does not play

### ISSUE THREAD

**Issue by sirdiogoamorim** [microsoft/coe-starter-kit#8911]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After opening the CoE Setup and Upgrade Wizard app in play mode, I get an "AppForbidden" error code:

"It looks like this app isn't compliant with the latest data loss prevention policies.
UciError: It looks like this app isn't compliant with the latest data loss prevention policies. at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.7cfa05fae26ee87406cebe5572f461ee.js:33:948189) at https://content.powerapps.com/resource/uci-infra-bus/scripts/custompage.eb2f10d511b21bc791c8eaacc6132a60.js:4:207675"

I have configured the DLP according with the documentation (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies).

### Expected Behavior

The app should play.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Open the app in play mode.

### Anything else?

![image](https://github.com/user-attachments/assets/402d3096-6ea6-46b9-aa98-c0d324636ca0)

**Comment by sirdiogoamorim** [comment]
Hello Jenefer,

I've already reviewed and changed the impacting DLP. Currently, I only have one DLP impacting the new environment I've created specifically for the CoE (without Dynamics365 apps).

Yes, this is a new install (August 2024 version).

Best regards,

Diogo Amorim
Software Developer | Portals - Office365, SharePoint & .NET

+351223751350<tel:+351223751350> | +351967094476<tel:+351967094476>
                     devscope.net<http://www.devscope.net/> | linkedin<https://www.linkedin.com/company/devscope> | facebook<https://www.facebook.com/devscope/> | twitter<https://twitter.com/DevScope> | blog<https://devscope.wordpress.com/>
***@***.***

**Comment by Jenefer-Monroe** [comment]
DLP is a product feature so if you've set it up correctly and its not working then unfortunately you've hit a product issue. 
I'm used to it giving a clue on what is wrong with the DLP though which is unfortunate. 

Not sure when you changed the DLP last but it could be that you need to wait, sometimes these changes take a while to update across the tenant. 

If its been a while then I'm afraid you'll need to walk the DLPs again and look for one that impacts the envt.

**Comment by sirdiogoamorim** [comment]
I've changed the DLP yesterday, and still not working.

Could it be caused by the Environment not having Dynamics 365 apps?

**Comment by Jenefer-Monroe** [comment]
No I dont think that would be why. You can go look at the DLPs in JSON format and search for your environment. That way you can see if its listed in any unexpected DLPs

## Create and flow to See DLPs
You can go see the state of DLP by creating a one off flow and calling **_List DLP Policies V2_**
Add the connector and action and then save and run
![image](https://github.com/user-attachments/assets/499f5f62-f7ad-4406-b048-22d2f1e73b9e)
![image](https://github.com/user-attachments/assets/a40973d1-1b0a-4671-94fa-75eec5e5ef7b)

## View results
View the outputs in a json viewer tool. You will see the impacted environments iterated. You can search the output for your target environment GUID. 
![image](https://github.com/user-attachments/assets/75c660b5-f4f6-4d2a-b46f-0bd8a89aa5d9)
![image](https://github.com/user-attachments/assets/91ba2ae5-c01b-4fb1-854e-9605bf3993b2)

**Comment by sirdiogoamorim** [comment]
I've just confirmed and I have only the new DLP impacting the environment with the connectors, specified in the documentation, in the Business group:

Approvals
Azure Resource Manager
HTTP
HTTP with Microsoft Entra ID (reauthorized)
Microsoft Dataverse
Microsoft Teams
Office 365 Groups
Office 365 Outlook
Office 365 Users
Power Apps for Admins
Power Apps for Makers
Power Automate Management
Power Automate for Admins
Power Platform for Admins
Power Query Dataflows
RSS

Am I missing any? Is the documentation correct?

**Comment by Jenefer-Monroe** [comment]
There is one more connector that is being added to the list per https://github.com/microsoft/coe-starter-kit/issues/8874
Power Platform Admin V2
https://learn.microsoft.com/connectors/powerplatformadminv2/

However it is not used in that app so I do not expect that will be the issue.

**Comment by sirdiogoamorim** [comment]
It did not work when I added it to the DLP.

Can you please tell me which connectors does this app use?

**Comment by Jenefer-Monroe** [comment]
Sorry its not that simple to answer as its a MDA. It uses all the connectors in all the custom pages. 
The list of connections is a subset of the ones used to install. So if you go look at the default solution and look at all the connection references, that will be the ones used to install. 
I just confirmed that the list above is correct other than that V2 (which would not block boot)
So perhaps you have some other settings on the DLP that isnt correct. 
For example have you set some patterns here? 
![image](https://github.com/user-attachments/assets/6f2f9e96-bd33-4552-931c-3cb0ab91ce40)

**Comment by sirdiogoamorim** [comment]
The only pattern I have is the default one, the one on the image you shared.

**Comment by Jenefer-Monroe** [comment]
OK I'm not sure then. If you are certain that you have the DLP setup correctly, and its still not letting you load, then that would be a product issue and I am not able to assist with those.

**Comment by Jenefer-Monroe** [comment]
Please do the below to find your coe environment's impacting DLP policies.

## Create and flow to See DLPs
You can go see the state of DLP by creating a one off flow and calling **_List DLP Policies V2_**
Add the connector and action and then save and run
![image](https://github.com/user-attachments/assets/499f5f62-f7ad-4406-b048-22d2f1e73b9e)
![image](https://github.com/user-attachments/assets/a40973d1-1b0a-4671-94fa-75eec5e5ef7b)

## View results
View the outputs in a json viewer tool. You will see the impacted environments iterated. You can search the output for your target environment GUID. 
![image](https://github.com/user-attachments/assets/75c660b5-f4f6-4d2a-b46f-0bd8a89aa5d9)
![image](https://github.com/user-attachments/assets/91ba2ae5-c01b-4fb1-854e-9605bf3993b2)

**Comment by Jenefer-Monroe** [comment]
Can you try adding this connector to the business bucket for your policy and see if that resolves? 
![image](https://github.com/user-attachments/assets/3e03b664-49d6-4027-a67f-f485b1628756)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
