### ISSUE TITLE
[CoE Starter Kit - BUG] Discrepancy on the list of Environments affected by the policy from the DLP Impact Analysis App and Power Platform Admin Center

### ISSUE THREAD

**Issue by JanusAllenCapili** [microsoft/coe-starter-kit#8914]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi PowerCAT team,

There seems to be a bug in the DLP Impact Analysis App. When we try to make changes or update a policy from the DLP Impact Analysis App, we noticed that the number of Environments affected by a DLP Policy is not the same as what is reflecting on the Power Platform Admin Center. You may refer to the list of screenshots as illustrated below:

Here is a screenshot upon trying to configure a policy from the DLP Impact Analysis App:

![image](https://github.com/user-attachments/assets/e03ecdbb-0494-414d-b5d9-dcc68bdf895b)

![image](https://github.com/user-attachments/assets/0195947c-206a-4402-aae8-238f6bf2d62f)

![image](https://github.com/user-attachments/assets/dbe3c3fd-c2c4-47bf-a96d-274604ac7433)

The next screenshots are what is configured on the same DLP Policy from the Power Platform Admin Center:

![image](https://github.com/user-attachments/assets/90cebff4-3f5a-47fa-9f2d-fe928e6eb3ac)

![image](https://github.com/user-attachments/assets/568e8b13-9c5d-4a5e-a4ad-69e1f43a508d)

![image](https://github.com/user-attachments/assets/ad4ce780-48b9-4644-a0f0-2a70a4da73e5)

As you can see, the list of Environments are different from the DLP Impact Analysis App compared to the Admin Center. With this, we disabled the functionality to update the policy in the DLP Impact Analysis App, and advised our Ops team to update the policy in the Admin Center instead.

Any inputs on this is appreciated.

### Expected Behavior

It is expected that the list of Environments affected by a policy is the same as what is configured in the Power Platform Admin Center.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

DLP Impact Analysis App

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
