### ISSUE TITLE
Setup Wizard and Command Center failing to set env vars

### ISSUE THREAD

**Issue by kartrabby** [microsoft/coe-starter-kit#8916]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

**CoE Setup and Upgrade Wizard** is giving multiple errors.
‎ 
‎ 
1. When clicked on **Refresh,**  I get the error as **Network error when using Patch function: The requested operation is invalid.**
‎ 
![image](https://github.com/user-attachments/assets/1616f743-f277-481a-934e-21f9a5d1d255)
‎ 
‎ 
2. As soon as I open the **Inactive Notifications Process**, I see the error as **The requested operation is invalid. Server Response: Environment Variable Values failed: It is invalid to create component EnvironmentVariableValue with the same export key value(s) as an existing component. Please change the key. The current value(s) are environmentvariabledefinitionid: 694b02af-05e6-4cca-87b7-9d4922c7b918**
‎ 
![image](https://github.com/user-attachments/assets/41b57a01-62d7-4ff4-a591-8c02abe4b87a)
‎ 
‎ 
3. When clicked on **Refresh,**  I get the error as **The requested operation is invalid. Server Response: Environment Variable Values failed: It is invalid to create component EnvironmentVariableValue with the same export key value(s) as an existing component. Please change the key. The current value(s) are environmentvariabledefinitionid: 6bcb04cc-667f-4c20-a1a0-6e7052810000**
‎ 
![image](https://github.com/user-attachments/assets/b9845f35-335f-4596-bcfd-48468ee23b7b)
‎ 
‎ 
All SetupWizard flows are **turned-on** and **ran successfully**
‎ 
![image](https://github.com/user-attachments/assets/708aaa12-5dd2-41fd-b816-2e48d601206a)
‎ 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I do not repro, did you already walk through the initial setup?

**Comment by kartrabby** [comment]
@Jenefer-Monroe : Yes, the initial setup was successful. Since I updated the toolkit last month, Initial Setup had no issues!

Now, I can see the errors in the initial setup as well.

![image](https://github.com/user-attachments/assets/b0aadaad-edc4-40f2-9dcf-1ad6e6c760fb)

**Comment by kartrabby** [comment]
@Jenefer-Monroe :

![image](https://github.com/user-attachments/assets/8593fa04-8d99-48b0-a61b-edd9308bd82c)

**Comment by Jenefer-Monroe** [comment]
ok looks like your coe envt is in the preview region which is not recommended as you will hit issues like this. 
I do repro in preview as well. 

It looks like in the past you could basically **_upsert_** env vars. In others add or update and the product would know which to do
![image](https://github.com/user-attachments/assets/ecc139c1-d6c2-41ae-923e-7d043a23ee49)

But now you need to update or insert
![image](https://github.com/user-attachments/assets/947095ed-4b25-4877-bdd7-6d699c002ebe)

**Comment by Jenefer-Monroe** [comment]
ok updating all the setup wizard pages to ship for Sept

**Comment by kartrabby** [comment]
> ok updating all the setup wizard pages to ship for Sept

@Jenefer-Monroe : Thank you for the highlighting it. So hope to see this update in the Sept-2024 toolkit. Hope the issue will be resolved after the update!

**Comment by Jenefer-Monroe** [comment]
similar issue in the env var page. 
product change made that no longer work so updating there too

**Comment by Jenefer-Monroe** [comment]
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2024
