### ISSUE TITLE
Insert or update TeamsWebhook

### ISSUE THREAD

**Issue by ThomAstra11** [microsoft/coe-starter-kit#8918]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

since we upgrade to the August release 4.34 we face issues with the Flow

Admin | Sync Template v3 (Connectors)

because the step "Update TeamsWebhook" ended up with the error: WorkflowOperationParametersRuntimeMissingValue.

"Action 'Update_TeamsWebhook' failed: The 'inputs.parameters' of workflow operation 'Update_TeamsWebhook' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'"

In your 'Update_TeamsWebhook' operation, the error is due to the 'recordId' parameter being invalid or empty. To fix this, ensure that the 'recordId' parameter is correctly referencing the unique identifier (GUID) of the record you want to update. Double-check the flow logic to ensure the correct value is being passed to the 'recordId' parameter.

for further information please refer also to the attached pictures

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.34

### What app or flow are you having the issue with?

Admin Sync Template v3 (Connectors)

### What method are you using to get inventory and telemetry?

Data Export

### Anything else?

![image](https://github.com/user-attachments/assets/0e75c4a9-72d8-448c-94f9-0efab8fce43d)

**Comment by Jenefer-Monroe** [comment]
Hello that was fixed in the current release for August: 
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by ThomAstra11** [comment]
Ok. Thanks for letting me know.
Thomas Trauernicht
Senior System Engineer MS Power Platform

Sika Informationssysteme AG
Tüffenwies 16 · 8048 Zürich · Switzerland
***@***.*** information contained herein and any other advice are given in good faith based on Sika's current knowledge and experience of the products when properly stored, handled and applied under normal conditions in accordance with Sika's recommendations. The information only applies to the application(s) and product(s) expressly referred to herein. In case of changes in the parameters of the application, such as changes in substrates etc., or in case of a different application, consult Sika's Technical Service prior to using Sika products. The information contained herein does not relieve the user of the products from testing them for the intended application and purpose. All orders are accepted subject to our current terms of sale and delivery. Users must always refer to the most recent issue of the local Product Data Sheet for the product concerned, copies of which will be supplied on request.
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Wednesday, September 4, 2024 15:59
To: microsoft/coe-starter-kit ***@***.***>
Cc: Thomas Trauernicht ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [microsoft/coe-starter-kit] Insert or update TeamsWebhook (Issue #8918)


Hello that was fixed in the current release for August:
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by Jenefer-Monroe** [comment]
You bet! Thanks for reaching out.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
