### ISSUE TITLE
[CoE Starter Kit - QUESTION]Power BI 

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#8920]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi Jenefer,

Is there a way to find if powerbi is being used to connect to dataverse enviornment using coe toolkit?

Thank you

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, no we do not track any properties from PBI in the kit as its organizationally a different set of experts.

**Comment by lingutla123** [comment]
Okay. Thank you.
