### ISSUE TITLE
Flow action information (COE Stater kit Question)

### ISSUE THREAD

**Issue by SREENIVASULU1993** [microsoft/coe-starter-kit#8921]
We are not getting data flow action information column   (Flow action detail table) please refer the attachments.
<img width="730" alt="Flow action GitHub" src="https://github.com/user-attachments/assets/ff7a0591-5052-403b-871b-e63ea9a05d74">
<img width="729" alt="Flow action gethub" src="https://github.com/user-attachments/assets/bbfeb601-abf0-488d-a440-3336dd1e44a1">

**Comment by Jenefer-Monroe** [comment]
Hello sorry this didnt get put into our repository for some reason. 
Yes this appears to be a dead column we did not end up using.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
