### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Security Roles) flow BadRequest error with last names containing an apostrophe

### ISSUE THREAD

**Issue by johnravas** [microsoft/coe-starter-kit#8922]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are receiving BadRequest errors with this flow in the "Find this users records - still unknown" action when you encounter a last name with an apostrophe.  Here is the $filter parameter for the raw inputs for one of the failures:
"$filter": "admin_name eq 'Charlie O'Brien' and _admin_environment_value eq <ID masked>"
Name changed and ID removed to protect the data.  In some run instances of the flow, they show successful even though there are some issues with the names in the apply to each.  In other instances, they seem to only focus on 8 of these names and the flow shows as failure and the admins receive a notification.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.24

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Security Roles) flow

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Daily runs of the flow.  See details above

**Comment by Jenefer-Monroe** [comment]
I believe this has been addressed in later builds, please upgrade to August release to see this working.
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024
![image](https://github.com/user-attachments/assets/86726804-0bea-4b94-afe0-6a3bc89c9e4b)

**Comment by johnravas** [comment]
@Jenefer-Monroe - will do thank you!!

**Comment by johnravas** [comment]
@Jenefer-Monroe - I know the general rule is to jump only 3 months at a time.  Do you think there is any harm in upgrading from March to August all in one fell swoop?

**Comment by Jenefer-Monroe** [comment]
Sorry I missed your question somehow. 
There are some product issues with upgrade at this time but they are not dependent on the builds being used. So you may hit something please let me know if you do. 
However my testing of direct upgrade March to August did work.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
