### ISSUE TITLE
[CoE Starter Kit - QUESTION] reference architecture

### ISSUE THREAD

**Issue by renrous** [microsoft/coe-starter-kit#8924]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Dear, I need to know if there is a reference architecture of the starter kit components

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, I'm not sure specifically what you are requesting. Can you clarify? When I think reference architecture I think of the solution files themselves, which of course we do have: https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

So please do let me know what you are hoping to see.

**Comment by renrous** [comment]
Hi, what I'm looking for is a diagram of the coe solutions, apps, flows, connections and how the different components interact with each other.

**Comment by Jenefer-Monroe** [comment]
I see, sorry no we dont have such a thing.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
