### ISSUE TITLE
Help extending orphan flows to always send communication to CoE Team not Managers

### ISSUE THREAD

**Issue by dixitatul1** [microsoft/coe-starter-kit#8926]
### Describe the solution you'd like

we have installed power platform COE toolkit. in COE toolkit, there is governance component. in governance component, there is Orphaned process flows automation (Request Orphaned Objects Reassigned (Parent),  Request Orphaned Objects Reassigned (Child)).  On a daily basis, this collects all the orphaned objects in the tenant and attempts to associate them with the manager of the former owner. It then sends a Teams bot note to each impacted manager and lets them know there are objects to clean.

**We are looking to update existing flow, instead  to send teams bot to mangers, only COE team will get notify for all orphaned object.**

**Comment by Jenefer-Monroe** [comment]
We are not staffed to assist with customizations unfortunately but I can get you started. 

Here is a link to our description of how to extend/modify the kit generally: https://learn.microsoft.com/en-us/power-platform/guidance/coe/modify-components

And then for these flows in particular, this should get you going. 

In the child flow we have a "SendTo" compose that you can update. You can put the CoE team mail address in there 
![image](https://github.com/user-attachments/assets/3b8177a5-4a63-4084-921e-a44f5d075b60)

In the parent flow you can put it here:
![image](https://github.com/user-attachments/assets/3f8d7f50-8313-4f3d-b418-d3d7bbf2f577)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
