### ISSUE TITLE
Microsoft Dataverse (Legacy) missing from list of connectors for DLP (needed for apps)

### ISSUE THREAD

**Issue by thotavinod590** [microsoft/coe-starter-kit#8929]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

When we are trying to play the CoE Setup and Upgrade Wizard App it is giving an error.

![image](https://github.com/user-attachments/assets/130e8a32-8a73-4183-9b50-fb21799a3198)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard App

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Please do the below to find your coe environment's impacting DLP policies.

## Create and flow to See DLPs
You can go see the state of DLP by creating a one off flow and calling **_List DLP Policies V2_**
Add the connector and action and then save and run
![image](https://github.com/user-attachments/assets/499f5f62-f7ad-4406-b048-22d2f1e73b9e)
![image](https://github.com/user-attachments/assets/a40973d1-1b0a-4671-94fa-75eec5e5ef7b)

## View results
View the outputs in a json viewer tool. You will see the impacted environments iterated. You can search the output for your target environment GUID. 
![image](https://github.com/user-attachments/assets/75c660b5-f4f6-4d2a-b46f-0bd8a89aa5d9)
![image](https://github.com/user-attachments/assets/91ba2ae5-c01b-4fb1-854e-9605bf3993b2)

**Comment by Jenefer-Monroe** [comment]
Can you try adding this connector to the business bucket for your policy and see if that resolves? 
![image](https://github.com/user-attachments/assets/3e03b664-49d6-4027-a67f-f485b1628756)

**Comment by Jenefer-Monroe** [comment]
I confirmed this, will mark as a documentation bug. 
It seems that the apps require this connector even though we are using the non-legacy version.,

**Comment by thotavinod590** [comment]
Hi @Jenefer-Monroe 

We have added all the required the connectors to the DLP policy but still facing same issue.

![image](https://github.com/user-attachments/assets/c3470aee-9969-402f-abba-65adb6d503f2)
![image](https://github.com/user-attachments/assets/54668073-2881-4340-988c-af61048f5a3c)

**Comment by Jenefer-Monroe** [comment]
I've validated this is the fix for the recommended DLP. 
These policies can take 24 hours to apply unfortunately so you may need to wait. 
You should also look in the recommendation above to make sure that this is the only policy impacting the envt

**Comment by Jenefer-Monroe** [comment]
This has finally been resolved yeah! The two connectors that were missing from the list are now fixed. 

![image](https://github.com/user-attachments/assets/adc658e3-8638-4cb6-b867-a0f1429e1fc0)
