### ISSUE TITLE
[CoE Starter Kit - QUESTION] Why is the RPA Sessions table not populating?

### ISSUE THREAD

**Issue by joelzehring** [microsoft/coe-starter-kit#8931]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The flow Admin | Sync Template v4 (Desktop Flow - Runs) appears to be running successfully, and the actions appear to be returning results from some of our environments with flow session data. But the condition to add the flow session data to the RPA Sessions table never evaluates to true, so the data isn't added to the RPA Session table, and our reports around desktop flows are all empty.

Is this a known issue?

Is there some configuration step we missed?
![image](https://github.com/user-attachments/assets/c903afcc-1bbc-49b7-afc4-76894a2ac98d)
![image](https://github.com/user-attachments/assets/20b40f4c-f883-4e70-a22d-7c6252bf2270)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Desktop Flow - Runs)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Do you find the desktop flows in question in the inventory? 
![image](https://github.com/user-attachments/assets/5443eeee-4e49-42ac-99e7-df7cddd5a0fa)

**Comment by joelzehring** [comment]
No that inventory is empty.

**Comment by Jenefer-Monroe** [comment]
oh ok thats why this isnt working then. Its failing to find the RPAs in inventory. 

Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
