### ISSUE TITLE
How to make apps multi-lingual

### ISSUE THREAD

**Issue by lsavard** [microsoft/coe-starter-kit#8932]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

What would be the recommended way to make canvas and model apps from the CoE starter kit bilingual? I do not want to make copies of all the apps and stop receiving updates from future releases.

Email are easy enough to translate, but I don't think apps can be translated in the same way ? Multilingual apps would be appropriate for any app accessible by makers.

Thanks !

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

August 2024

### What app or flow are you having the issue with?

Any Canvas and Model apps accessible by makers

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Sorry I dont have advice on this as I've never made a multi-lingual app myself. I do see lots of MVP folks talking about it in on their channels from a brief look but as someone who has never done this I wouldnt know how to approach.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
