### ISSUE TITLE
[CoE Starter Kit - BUG] "App Last Launched On" not populated in Power Platform Admin View MDA

### ISSUE THREAD

**Issue by whorn76** [microsoft/coe-starter-kit#8933]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

It appears in the PowerApps App view of the Power Platform Admin View MDA that "App Last Launched On" field isn't being populated even though there is data.  You can see the data in the Usage section of the App details and you can see it populated in the Power BI report, but the MDA isn't displaying it.
![Screenshot 2024-09-05 132221](https://github.com/user-attachments/assets/0b088217-af18-4a06-be43-6311d22b9544)
![Screenshot 2024-09-05 132246](https://github.com/user-attachments/assets/444e111b-fecb-461c-96ff-d678fde3a548)

### Expected Behavior

it should display the last launched time gathered from the Audit logs.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please share a screenshot of where you are expecting to see this

**Comment by whorn76** [comment]
Hello,

The first screenshot above should have the last launched date for the app like it shows in the PowerBI report in the second screenshot.

So the date is missing from that view in the Power Platform Admin View app view.

**Comment by Jenefer-Monroe** [comment]
Oh I see sorry it was tiny :)

These read from the same field so they should show the same thing. 
Are you sure you're looking at the same envt in both? In PBI you can look to see what envt is configured here:

![image](https://github.com/user-attachments/assets/d20d3e08-4e06-430f-91f3-0b7c6a4b08a4)
![image](https://github.com/user-attachments/assets/3de0d742-f065-4840-8f84-6c3d55f24a3f)

**Comment by whorn76** [comment]
Its the same environment. I can see the usage data under the Usage tab of the app details.

![Screenshot 2024-09-05 153129](https://github.com/user-attachments/assets/f8e231c0-7a74-42d3-8517-ac50bc9d95ee)

I'm just replicating in my environment.  I saw the same issue in a customer's environment today which made me start looking closer.

**Comment by Jenefer-Monroe** [comment]
Do you have this flow turned on? Admin | Audit Logs | Update Data (V2)

**Comment by whorn76** [comment]
Ah, no, that may have been what's missing.

**Comment by Jenefer-Monroe** [comment]
i wouldnt think it would be populated in the PBI then but perhaps we calculate it there.

**Comment by whorn76** [comment]
It appears to be showing up now.  But it does seem weird that in the app details, and the power bi report, but not in that table view in the MDA.

Thanks for your help!

**Comment by Jenefer-Monroe** [comment]
You bet. Glad to help!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
