### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE Errors with loading the data in the PBI reports

### ISSUE THREAD

**Issue by DS2019** [microsoft/coe-starter-kit#8934]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When open the CoE Dashboard report (August 2024)
![CoEDashboardErrors](https://github.com/user-attachments/assets/f93e8626-c2be-41ae-bfff-1b0d7d3556e5)
and enter in the environment URL (with the https) I get load errors:
AI Builder Models
Load was cancelled by an error in loading a previous table.
Power Apps
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Power Apps Launches
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Business Process Flows
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Connectors
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Environments
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Environment Capacity
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Flows
Load was cancelled by an error in loading a previous table.
Flow Action Details
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Makers
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Power Pages
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Power Platform Users
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Power Platform User Role
Load was cancelled by an error in loading a previous table.
Power Virtual Agent bots
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Desktop Flow Sessions
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Solutions
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Desktop Flows
Load was cancelled by an error in loading a previous table.
NonProdWords
Load was cancelled by an error in loading a previous table.
App Connection Reference
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Flow Connection Reference
Load was cancelled by an error in loading a previous table.
Key Measures
Load was cancelled by an error in loading a previous table.
Power Virtual Agent bots usage
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
AI Credits Usage
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
![GovernanceErrors](https://github.com/user-attachments/assets/a73027d8-bf3d-4973-ac46-e7398b491f73)

### Expected Behavior

I would have expected the PBI report to load, with all its data. It gives errors and loads no data currently. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Power BI CoE Dashboard and Governance reports

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

I've upgraded the CoE to August 2024
I then take the CoE Dashboard and Governance PBI templates, open them to enter in the environment URL and as the data loads I receive errors and the data does not load

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by DS2019** [comment]
![Solutions](https://github.com/user-attachments/assets/9c815d03-e698-47e9-865e-cadaf1ac4ab4)
You bet, here you are, thank you.

**Comment by Jenefer-Monroe** [comment]
ok your solutions look fine. The PBIT file is working for me so I'm not sure. 

1. Have you already done the setup wizard to turn everything on? 
2. Does the data show as you expect in the [Power Platform Admin View]( https://docs.microsoft.com/power-platform/guidance/coe/core-components#power-platform-admin-view) app? 
![image](https://user-images.githubusercontent.com/89584709/172395280-11a99b41-6201-43f3-b06a-bc95393ac816.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
