### ISSUE TITLE
[CoE Starter Kit - Feature]: Install Documentation Improvement

### ISSUE THREAD

**Issue by doublebuckets** [microsoft/coe-starter-kit#8935]
### Is your feature request related to a problem? Please describe.

The documentation is not correct around the setup of connections.

**Link 1**
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies
This one refers to "HTTP" without any related link.

**Link 2**
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#create-connections
This one says "Create these connections manually ahead of installing the kit to ensure they're correctly configured." but there are no connections listed under that point.

### Describe the solution you'd like

**Link 1**
Remove the word "HTTP"

**Link 2**
List all the connections needed

**Comment by Jenefer-Monroe** [comment]
Hello. Thanks for reaching out. These two are both actually correct. 

## Link 1 This one refers to "HTTP" without any related link.
Unfortunately there is nothing to link to, the product does not have a page for HTTP like the others. 
You will see it listed for the DLP setup though

## Link 2 Create these connections manually
There is only one that you need to create manually, the HTTP with Microsoft Entry ID (preauthorized). The rest are created for you automatically when you install the solution. 
![image](https://github.com/user-attachments/assets/40f2676a-c9b7-488e-a2a9-902449a0c02b)

## DLP Policy
Do note however, that there are two connectors missing from that list. 
1. per https://github.com/microsoft/coe-starter-kit/issues/8929 the **_Microsoft Dataverse (Legacy)_** connector
2. per https://github.com/microsoft/coe-starter-kit/issues/8874 the **_Power Platform Admin V2_** connector

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
