### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP - Admin | Sync Template v3 (App Shared With)

### ISSUE THREAD

**Issue by steph-ong98** [microsoft/coe-starter-kit#8936]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We tried manually running this flow, since our change from Issue #8876, and we are getting an error:
{
  "code": "InvokerConnectionOverrideFailed",
  "message": "Failed to parse invoker connections from trigger 'manual' outputs. Exception: Could not find property 'headers.X-MS-APIM-Tokens' in the trigger outputs. Workflow has connection references '[\"shared_webcontents_1\"]' with invoker runtime source."
}

![image](https://github.com/user-attachments/assets/10715194-5e26-4ceb-9501-183b86d9e08e)

### Expected Behavior

We expected it to run and succeed.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Admin | Sync Template v3 (App Shared With)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Those flows are not related so I doubt these are related. 
Please do the following: 

## Double check that connection
Make sure you fixed up the connector correctly from the other bug
Go to connections and make sure the connection for these is as follows (or your tenant equivalent if you are not a commercial tenant: https://graph.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f49797b8-0f48-4884-a026-2580bbc8b96f)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a31b22b8-bc81-4d81-a5b7-80dc740f2b82)

## Fix Connection References
Lastly go to the Default Solution > Connection References
Make sure they are all pointed to the correct identity which is intended to run the flows by doing the below for all connection references.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f630670f-9bf5-4c56-bf18-9693e0eeea01)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d4a34cc4-5d46-494e-9a7d-e9d570489159)

## Unmanaged Layers
Make sure you dont have unmanaged layers on any of your flows
Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
