### ISSUE TITLE
[CoE Starter Kit - BUG] admin_EnvironmentSecurityRolePermission increasing Storage

### ISSUE THREAD

**Issue by backiii** [microsoft/coe-starter-kit#8937]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are observing that the storage of this table is going up.

admin_EnvironmentSecurityRolePermission

However, we cannot explain why this is the case

### Expected Behavior

It should not use this amount of storage space for EnvironmentSecurityRolePermissions

![image](https://github.com/user-attachments/assets/20835e7f-d64a-441b-bd37-b41874770fce)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Security Roles)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I don't repro this in any of our test tenants. 

1. Can you please validate that you don't have unmanaged layers on that flow? 
2. Looking through the records in the database for a target environment, do they seem incorrect? Do they cluster on a single envt?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by tamdva21** [comment]
Hello. We also are experiencing the same issues. We currently have the version 4.24. This issue could be solved installing the latest version?
