### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Inactivity notifications v2 where is the approval?

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#8939]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi everyone, how are you?

I'm trying to understand this part of the flow, could you answer this question for me?

In which part of the flow is the record being fed with Approved or Rejected, since the "Create an Approval" action is being used here to validate whether there was a response from the maker or not?

In my ignorance, I've already tried to analyze the flow as a whole and I'm not seeing it.

![image](https://github.com/user-attachments/assets/37f973f6-1002-499e-b21d-7bbc1b9c330f)

![image](https://github.com/user-attachments/assets/32eb1494-2af8-47be-b2d3-ad8546ab1c00)

Why I'm doing this: I want to monitor who isn't filling out the comment field. I notice that many users are rejecting it, but without any justification, which has already caused some inconvenience.

I created a scope that I will apply if the response is successful

![image](https://github.com/user-attachments/assets/2e7b56e6-82f2-4b6d-98e2-6ca7d43767d7)
---
![image](https://github.com/user-attachments/assets/e4413fa4-1828-43e4-8fb1-0fe8283911dd)

obrigado por toda atenção!

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.25

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Apps)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello these approvals do not wait for response. There are several Approvals actions and this flow uses the one that kicks it off and then doesnt wait.
![image](https://github.com/user-attachments/assets/a7fe8165-ce50-4b10-b5f2-7d8c31329205)

Instead we have another flow that runs and checks for approval response later:
**_Admin | Inactivity notifications v2 (Check Approval)_**

![image](https://github.com/user-attachments/assets/fa54e5e2-f402-4089-b8fb-f410aaa9de3d)

**Comment by ClaudioRWS** [comment]
@Jenefer-Monroe 

Wouldn't it be interesting to store the user's response at this stage? We can get the response with a Wait for an approval action on the Success decision.


What do you think?

![image](https://github.com/user-attachments/assets/d04f1141-925e-413b-b2e7-7becb092e4b9)


Wouldn't it be interesting to store the user's response at this stage? We can get the response with a Wait for an approval action on the Success decision.

What do you think?

**I used "First" because compose understands multiple alternatives if you put an attribute on the wait action

**Comment by Jenefer-Monroe** [comment]
This is definitely a different approach that could taken and you are welcome to do that on your side. 
I did not create this flow to begin with, so I dont know why they went this way. My guess would be so that the flow could complete. Perhaps the apply-to-each at that time had variables and so you couldnt use parralelized runs. I'm not sure. 

That said, its been in the wild for ~4 years and since the technique we have does work, won't be revamping to do it a different way. 

Hope that makes sense.

**Comment by ClaudioRWS** [comment]
@Jenefer-Monroe 

As the Brazilian saying goes, "you don't change a winning team."

Thanks for the clarification, Jennefer!
obrigado!
