### ISSUE TITLE
[CoE Starter Kit - Feature]:  Can you add Assigned Licences column to Power Platform User table in Center of Excellence - Core Components

### ISSUE THREAD

**Issue by Prudhvi-Kunapareddy** [microsoft/coe-starter-kit#8942]
### Is your feature request related to a problem? Please describe.

By Adding Assigned Licences column, can help us to understand what licences the power platform Users have and by drilling down on the other related tables we can find what apps they have access and when was the last time the app is launched. 

### Describe the solution you'd like

A column in power platform users table to show what licences user have and a flow to run every day and update the latest licences , then a power bi report to show detailed information about , the users who have premium licences and which apps they have access to and when was the last time this app has be accessed.

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately we do not have license information available to us in a way that is appropriate for the kit. 
This is a common governance ask though so good feedback for the product team. https://powerusers.microsoft.com

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
