### ISSUE TITLE
The flow owner name and flow is orphaned column not getting updated in coe

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#8944]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We found that in the flow table the flow derived owner column and flow is orphan column is not getting updated, we tested out  by changing the owner of the flow that was orphaned, we checked in the flow detail page itself the flow owner was successfully changed and I was able to see the new owner name there, but in flow table it is still showing old owner name and is still showing as orphaned .

I have checked the coe flow that are related to flows they are working fine.

could you please help us out why this happening

### Expected Behavior

The flow owner and orphan column should get updated

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Do not know which flow is causing this

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
How did you change the flow owner? What UX did you use?

**Comment by Rajatchopra3** [comment]
I used Admin connector to change the owner of the flow, just to make sure, I checked in the flow details page, there it was showing me as the primary owner, but when i checked the coe table , the record was not updated

**Comment by Jenefer-Monroe** [comment]
Yes this is unfortunately not returned today from the admin connectors so we do not update in the regular flows. Product team is aware of this and working to address but it will be awhile. 

In the meantime, you will need to update to a later build to have access to the following flows: 
CLEANUP - Admin | Sync Template v3 (Flow Shared With)
CLEANUP HELPER - Cloud Flow User Shared With

Then when they run they will flag the flow as having a new owner and then next inventory it will get patched up.

**Comment by Rajatchopra3** [comment]
Okay, please correct me if I understood incorrectly.
Due to admin connector issue, even if the flow owner is changed the coe flow records is not updated 

Is it the same case with **orphan** flows as well, will that also not get updated ?

will the two new flows solve the problem of flow owner  and orphan column not getting updated ?

**Comment by Jenefer-Monroe** [comment]
orphan is based off owner. so once it notes it has a new owner it should also note its no longer orphan yes. 

correct, you run those flows and it will note that the flow has a new owner and mark it to be inventoried
then the next day's inventory will get the new owner.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
