### ISSUE TITLE
Copilot studio not able to provide the correct outcome in embedded third party app using BOT framework webchat

### ISSUE THREAD

**Issue by Azizkhanss** [microsoft/coe-starter-kit#8946]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Cx has written the code in standard web chat interface, and they followed the documents that are available on git hub copilot studio sample to build own sample canvas BOT.
They have pulled the webchat interface from CDN and that is the latest version of Web chat by following the below articles.
[GitHub - microsoft/BotFramework-WebChat: A highly-customizable web-based client for Azure Bot Services.](https://github.com/microsoft/BotFramework-WebChat)
[CopilotStudioSamples/BuildYourOwnCanvasSamples at master · microsoft/CopilotStudioSamples · GitHub](https://github.com/microsoft/CopilotStudioSamples/tree/master/BuildYourOwnCanvasSamples)
They have not embedded the BOT into the website yet because user was not having the access. But they have generated an HTML file and testing the BOT there.

### Expected Behavior

Bot is working fine in copilot studio, but it is not giving the expected answers in webchat i.e, in web browser.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CopilotStudioSamples/BuildYourOwnCanvasSamples at master · microsoft/CopilotStudioSamples · GitHub

### What app or flow are you having the issue with?

Sample canvas in copilot studio

### What method are you using to get inventory and telemetry?

None

### Anything else?

<img width="776" alt="WebChat Interface" src="https://github.com/user-attachments/assets/e5f4e0c5-f853-4df0-afd9-6f62a1e3569e">
Web chat interface

**Comment by Jenefer-Monroe** [comment]
Hello. This is not a Sample Implementation of the CoE Starter Kit so I cannot assist. 
Please post your question in their GitHub repository for assistance: https://github.com/microsoft/CopilotStudioSamples/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

![image](https://github.com/user-attachments/assets/48c9bf37-49c5-4f2b-9b61-43e778ec59a2)
![image](https://github.com/user-attachments/assets/15716563-9cf8-4aaa-855f-59aa1e862507)

**Comment by Jenefer-Monroe** [comment]
I'll go ahead and close as this is not the correct repository. Best of luck.
