### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by henkdafreak** [microsoft/coe-starter-kit#8951]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I'm new to using CoE - Using the Power Platform Admin View app, I can only see data up until July this year. clicking the Refresh button doesn't load in newer data. How do I make sure the data is regularly updated? with live app and flow data? Is there a sync flow that i need to run/schedule?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 4.32.2

### What app or flow are you having the issue with?

Power Platform Admin View 

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
