### ISSUE TITLE
[CoE Starter Kit - QUESTION] Trying to understand impact of power platform admins not added as system administrator when syncing CoE Inventory

### ISSUE THREAD

**Issue by neethomas27** [microsoft/coe-starter-kit#8952]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Previously, all Power Platform admins were automatically added as System Administrator for all newly created environments. In a recent update, this has changed and the Power Platform admins are no longer automatically assigned the system administrator role in the environment and we need to self-elevate. The link below explains this process.

https://learn.microsoft.com/en-us/power-platform/admin/manage-high-privileged-admin-roles#self-elevate-to-the-system-administrator-role

Will syncing environment inventory to the CoE be impacted with this change? The CoE connections are configured using the one of the Power Platform admin accounts. if this account is not added as an environment system administrator for the newly created environment, what impact will this have on the inventory sync on the CoE solution?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Yes we have been able to integrate this product change into the kit. The August release uses the Power Platform for Admins V2 connector to escalate the user running the flow in all environments. 

Are you a sovereign cloud? Or a regular commercial cloud? 

If commercial you can go ahead and upgrade to August and this will be solved for you:
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
