### ISSUE TITLE
[CoE Starter Kit - QUESTION] some questions regarding the set up of the wizard app

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#8955]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hello!
I had some question regarding the setup of the wizard app.
There were some steps where I am not 100% sure what should we choose.
Could we ask for your help in understanding?
for example, 
1) the step about the "Configure communication methods" - admin persona and maker persona are configured, but the "user persona" - no. Is this obligatory to configure the "user persona", or I can leave it as "not configured" and then click "next"?
![image](https://github.com/user-attachments/assets/896e9e9e-f4fe-4e5b-9e8e-7d1a55dc683e)

2) the pre-requisites step: it is mentioned that the account that does the setup needs to have the "Microsoft power platform service admin, global tenant admin, or Dynamic 365 service admin". For example, we are using the service account to set up the app but the roles these account has are "Dynamics 365 Administrator (that needs to be activated when the role is needed); Power Platform Administrator; Developer (the role that grants access to create app registrations with self as owner)". Will these roles alone be enough? Or the roles I provided are exactly that are needed but just with a little bit different naming convention?

![image](https://github.com/user-attachments/assets/a8f535c8-f29b-460a-8ab1-ac6b9eea954a)

3) the step about the configuration of the inventory data source - there we see two options. What option is the best to choose?
![image](https://github.com/user-attachments/assets/a073aa16-8ac9-4d05-ba7f-438f567fbf55)
Am I right that the best one is the "cloud flows" since the "data export" is in preview?

4) the step "share apps"  - Am I right to assume that if I click just "next" nothing will be done and nothing will be shared? And that is ok if I not share anything, am I right?
![image](https://github.com/user-attachments/assets/ce2db6d6-eeb0-4448-96e4-ef3d6e53a080)

5) The step "publish power BI dashboard" - there is written that we need to configure and publish the dashboard, but this step is only informative, am I right? meaning that this step will not publish anything, but we need to do that manually as we always did before? and for now just "next" needs to be clicked?
![image](https://github.com/user-attachments/assets/edfd8feb-610e-4b57-8e59-1c7ea991529f)

6) After the setup will be done, we still can go to the app and change the setup, am I right? in case we decided to change something?
7) do we need to do the setup after each upgrade? or once it is done, there no need to do that again after?

Thank you in advance!

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello hope the below helps.

1) "user persona"
This can be left blank yes

2) roles question
Power Platform Administrator is sufficient, yes.

3) data source
we do not recommend new users try out the data export v1 today as we are shifting to data export v2 over the next several months. so choose cloud flows

4) sharing
correct

5) pbi
correct

6) After the setup
correct 

7) do we need to do the setup after each upgrade? or once it is done, there no need to do that again after?
yes run this after every upgrade it will show you new env vars, and turn on new flows, etc.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by JanetK12** [comment]
Hello @Jenefer-Monroe !
Could I clarify two things about the Wizard app if that is possible?

1) After the setup was completed, the app moved to the section "more features". And here I see a lot of features that can be configured. Am I understanding that right, that this section just shows what we can setup as a feature to use. So, not obligatory, but just what we can find useful for us and then decide just what we want to configure and what not?
2) I have noticed that some of the flows in our Customization solution had some unmanaged layers occurred, and as checked them, I see that they were created automatically at one and the same day and time , and as I checked what is this time, I see that it is the time when the setup of the wizard app was done. Could I ask whether the Wizard app also affects the flows that are not from the CoE solutions, so the custom flows as well? And do you perhaps know what exactly this app did with the custom flows, as not sure how to check what exactly was done in the flows for the unmanaged layer to occur.

Thank you in advance!
