### ISSUE TITLE
Notification to the maker, but the 'Modified Date' for the flow appears to be outdated

### ISSUE THREAD

**Issue by RyanCloud8888** [microsoft/coe-starter-kit#8958]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

HI Jenefer,
(suggest to post here :) )
The Center of Excellence (CoE) cleanup flow sends a notification to the maker, but the 'Modified Date' for the flow appears to be outdated, instead of showing the recent modification. This triggers an email asking the maker to approve or decline the flow's removal. Is there a workaround to improve or adjust this process?
Thanks for your help.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.34

### What app or flow are you having the issue with?

CLEANUP - Admin

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hi Ryan, thanks for the great questions today. Can you confirm if the date is wrong in the inventory itself? 
![image](https://github.com/user-attachments/assets/9e6f306f-dc74-4f70-a862-02944b4cf903)

**Comment by RyanCloud8888** [comment]
Hi Jenefer,
Yes, the date in the inventory itself is wrong.

![image](https://github.com/user-attachments/assets/9699b9f2-f19c-48dc-af4c-496f3a4c5586)

The real flow modification date is this: LastModifiedTime : 2024-04-03T11:39:35.1289138Z

how can I get the up-to-date, I already set the environment variables "InventoryFilter_DaysToLookBack" to 30 days ( I know it's far apart) how can we get this flow (we have lots of flows that have the wrong modified date).  How can we address this issue so it doesn't trigger the maker?

Thank you so much.

**Comment by Jenefer-Monroe** [comment]
Where are you seeing this ? 
LastModifiedTime : 2024-04-03T11:39:35.1289138Z

**Comment by Jenefer-Monroe** [comment]
Oh sorry I didnt see the 2023 and so was confused as I thought the kit showed a more recent date. 

For ones like these you can flag them manually to go through inventory as shown here. Then the next day they will be inventoried to current state. 
![image](https://github.com/user-attachments/assets/673e2bc8-64d6-4fb4-b481-fee7fb47bae0)

Generally speaking you can do a one off full inventory as well however this will be API intensive: [run a full inventory run](https://learn.microsoft.com/power-platform/guidance/coe/faq#running-a-full-inventory). 
Be sure to restart the inventory flows after changing the env variable as sometimes flows cache them. 
And be sure to set by to "no" when done so you dont blow out your API calls.

**Comment by RyanCloud8888** [comment]
Thank you, Jenefer as always.
