### ISSUE TITLE
[AA4AM]: Rerunning Build Fails if Artifacts Already Published

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#896]
### Describe the issue

This is a known issue in Azure DevOps (https://github.com/MicrosoftDocs/azure-devops-docs/issues/6677). Since our deployment pipelines produce artifacts that remain even when the steps subsequent to publishing artifacts fail. Rerunning the pipeline will always fail when attempting to publish artifacts with the same name again. The referenced AzDO issue describes this behavior. This is particularly an issue with our integration to GitHub PRs where the only way to get the PR to pass the build validation check is to rerun the pipeline that failed initially.

### Expected Behavior

Rerunning deployment pipelines should not fail when attempting to publish artifacts that already exist. One possible solution is to give the artifacts unique names based on the buildId or date/time stamp them and update the pipelines to use the latest / most recent version of the artifacts. However, this could be brittle. Another possibility is to require resubmitting PRs if  the initial PR doesn't pass the validation check.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20210521.1

**Comment by jenschristianschroder** [comment]
Closing this as we have decided not to implement staging in deployment pipelines for now.

The scenarios where one would rerun a failed pipeline are limited and usually are an effect of debugging pipeline yaml or configurations.

Making the deployment pipeline multistage will make performance worse as the each stage will wait for an available agent.
