### ISSUE TITLE
Deal with System Owned flows

### ISSUE THREAD

**Issue by PiZe0** [microsoft/coe-starter-kit#8966]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have encountered a bug withing the "SYNC HELPER - Cloud Flows" Flow. I have a couple of flows "Load training data flow" or "Skill finder model status update flow" where "SYSTEM" is the owner of the flow. However, the sync helper always tries to get the actual owner of the record because there is no flow owner. Unfortunately it throws an error.

![image](https://github.com/user-attachments/assets/e679fca6-0d64-47b5-9ff8-26af6e723739)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)

Then run the following flow: CLEANUP - Admin | Sync Template v4 (Check Deleted)

Then wait to see if you still see this failure on the next inventory run.

**Comment by PiZe0** [comment]
Hello Jenefer,

i do have this issue a couple of weeks now. There are no unmanaged layers. I've done exactly what you suggest this week.

**Comment by Jenefer-Monroe** [comment]
I see. So the product is not storing these system owned flows in a way that notes who is the owner? What do you see when you browse here? 
![image](https://github.com/user-attachments/assets/e0b38b10-be73-4e95-aa90-a8634502fe73)
![image](https://github.com/user-attachments/assets/ce8fbd9b-157c-41c9-a89b-7b0ba10efceb)

I'm not sure how to create a flow owned by system. Would it be possible to share the solution with me so that I can test? I can give you my email.

**Comment by Jenefer-Monroe** [comment]
Hmm I am not seeing this when I use that feature. I'll need to find a way to test this before I can address

**Comment by PiZe0** [comment]
This is the solution where the flow is stored. I can neither delete the flow nor the solution.

![image](https://github.com/user-attachments/assets/042069f2-eb65-4ab5-9d8b-14c974a4e857)

**Comment by Jenefer-Monroe** [comment]
Thanks for showing me that. I dont have Dynamics unfortunately so will need to find some other way to get a system owned flow.

**Comment by PiZe0** [comment]
I do have now multiple flows which end up in an error in the CoE StarterKit. They do not have an "owner" additionally they all are Dynamics Flows. For Example the "Sales Insights sequence daily usage flow". The interesting thing is, multiple dynamics flows are in this environment, and do not lead into an error in CoE, only 1 or 2 flows end up in errors. These 2 flows are the only ones which are "Enabled" and not "Disabled". But disabling them, does not help :(

**Comment by Jenefer-Monroe** [comment]
thanks for the additional info

**Comment by Jenefer-Monroe** [comment]
Can I please ask, what is returned from these two steps? 

![Image](https://github.com/user-attachments/assets/f16d5df8-6b0d-4b0c-b5c2-7ce0c6a17ffc)

**Comment by PiZe0** [comment]
Sure .. here it is (sorry for german layout)

![Image](https://github.com/user-attachments/assets/ce26082d-ad7f-4943-8e98-f99b1d57e220)

**Comment by Jenefer-Monroe** [comment]
Resolution here is as shown. We have another work item (https://github.com/microsoft/coe-starter-kit/issues/9164) for more thorough integration with System owned flows for V2

1. `length(outputs('Get_actual_object_for_owner')?['body/value'])`
2. @{''}

![Image](https://github.com/user-attachments/assets/5ad5c34f-d39c-4b0a-ba4f-c81b19482899)

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
