### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - Data segragation.

### ISSUE THREAD

**Issue by FC-SMS** [microsoft/coe-starter-kit#8971]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

If i were to set up a new CoE Test environment and install the core components, how can i then configure the toolkit to only have data from my coe test, coe live, and default environment in it? I don't want any of our other environments data in the CoE Test Environment.

Then with our live environment, if i set the coe live and coe test environments to exused from inventory, will this then remove the associated data from the live toolkit?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Here is our write up on how to [Setting up CoE for a subset of environments](https://learn.microsoft.com/power-platform/guidance/coe/faq#setting-up-coe-for-a-subset-of-environments)

**Comment by FC-SMS** [comment]
Thank you Jenefer. Apologies, school boy error, i should have checked the FAQ section. Tomorrow is a new day :)

**Comment by FC-SMS** [comment]
Thank you Jenefer. Aplogies, i should have checked the FAQ section.
