### ISSUE TITLE
[CoE Starter Kit - BUG]  PowerBI Dataflow refresh failed for Apps Usage and Flow Usage

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#8972]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have imported August 2024 DF file into our PowerBI Workspace and when we provide datalake URL and configure the connections and try to refresh for the first time, we are receiving below error.

<img width="934" alt="image" src="https://github.com/user-attachments/assets/d289372a-3935-4699-abd4-ff977cd06429">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

PowerBI

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately it looks like you've hit some product limitation in Dataflows. You may need to investigate this dataflow caching its referencing and see about changing that

**Comment by ALSPowerPlatform** [comment]
COE_BYODL dashboard is blank, is this because of hitting production limit only?
<img width="580" alt="image" src="https://github.com/user-attachments/assets/ec8b48f4-3ea9-47bb-96a9-5d78fbeaec28">

**Comment by Jenefer-Monroe** [comment]
I was referencing only the failure you noted in the original post.  
I have network issues and so cannot walk you through how to check details until next week. But can you check to see if the other individual dataflows completed? 

Also may I ask, is this your first time setting up the BYODL side? I ask because we do not recommend new people onboard to that platform. Its rather difficult to setup correctly and will not benefit you long term as its no longer the pattern for the new Data Export plans. 

Data Export v2 is in development now and does not use the datalake, does not have any of these limitations (ex big bulky dataflows), nor will it have the product limitations that are present still in v1.

**Comment by ALSPowerPlatform** [comment]
All the dataflows refresh is happening daily. We had BYODL setup around 8 months ago.

<img width="815" alt="image" src="https://github.com/user-attachments/assets/d965f584-2a9b-4b0b-8673-da0ff5bcfacc">

**Comment by ALSPowerPlatform** [comment]
All the dataflows refresh is happening daily. We had BYODL setup around 8 months ago.

<img width="815" alt="image" src="https://github.com/user-attachments/assets/d965f584-2a9b-4b0b-8673-da0ff5bcfacc">

**Comment by Jenefer-Monroe** [comment]
The PBI in V1 is connected to dataflows in PBI.com not those. Those fill the inventory tables for other processing. 
Unfortunately this may need to wait until next week when I am back and able to share screenshots to assist

**Comment by Jenefer-Monroe** [comment]
Please go to PowerBI.Com and find the workspace where you hosted the dataflows. 
Ensure you have the Jan 2024 version of the dataflow and make sure its been refreshing
![image](https://github.com/user-attachments/assets/b54caafd-09a1-4673-9d0b-ba15e2a3b6ca)

Make sure you have the correct Dataflow and Workspace IDs for the input parameters
![image](https://github.com/user-attachments/assets/9b69fb2e-ff98-4262-836a-4193c9b4ca06)
Please see [Configure the BYODL Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-the-byodl-power-bi-dashboard)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team

**Comment by BroxCJ** [comment]
I think I may have to open this ticket as I'm facing this error since more than a month. I checked the tutorial, and it seems configuration was right.

What can I be missing?

BTW, I'm using the COE version of August, as I haven't uploaded to the September one.

Thanks.
