### ISSUE TITLE
[CoE Starter Kit - BUG] Not able to see any user dash board

### ISSUE THREAD

**Issue by laxmichaithanya14** [microsoft/coe-starter-kit#8973]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team, not finding any dashboard which will show user related information like what access on the environments and what access on apps and flows, what connections the user built. Please let me know which dashboard/app will have this information.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Dashboard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, We do have some of the things you reference in an app called the Manage Permissions which you will find in Core. 
It shows things like permissions to apps/flows, Security Roles in different environments, and connections made by different users.

I cannot share images today for some reason so hopefully you can find that app and explore.

**Comment by laxmichaithanya14** [comment]
yes gone through Manage permissions app but there is no dashboard like If I want to see any user related permissions like what are all the environments he has the access and what access on it.

**Comment by Jenefer-Monroe** [comment]
OK sorry we dont seem to have what you want available then today.
If you'd like to leave this open I can share some screenshots next week when I'm available to see if they help

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
