### ISSUE TITLE
[CoE Starter Kit - QUESTION] How can we hide maker's information from Power BI reports

### ISSUE THREAD

**Issue by djscotia** [microsoft/coe-starter-kit#8974]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

hi CAT team, 

I am part of an internal COE team and we are seeking guidance on resolving a privacy issue in one of our Power BI reports from the COE starter kit. this report displays the cities of all our makers which is a concern for us and has been flagged as a risk. This prevents us from sharing the report with executives and stakeholders. 

Dashboard Name: Production_COEDashboard

Page Name: Overview- Power Apps Visual name: Top App Maker Cities
Page Name: Overview- Power Automate Visual name: Top App Maker Cities
Page Name: Makers Visual name: Maker cities

We considered removing the visual from the report, but this would stop us from receiving updates or require manual removal each time we update. 

Do you have any other workarounds that you can suggest regarding this issue? We update our kit and Power BI reports every two months. 

Thanks

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, no we do not have the ability to make this portion of the report optional, and its a highly used one so we would not be able to remove. To my knowledge there would not be a way for you to hide this without either changing the PBI or the backing flows. I think the PBI is the less risky place for you to make the change.
Sorry I dont have a better suggestion for you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
