### ISSUE TITLE
[CoE Starter Kit - QUESTION] September update for sovereign cloud

### ISSUE THREAD

**Issue by github1339** [microsoft/coe-starter-kit#8975]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We are in a sovereign cloud (GCC High), currently have the July release installed. Core 4.33 and Audit 3.24
For the September release we will plan to install the managed Core 4.42 solution. Should we also install Audit 3.25 from the main September release? Are the dashboards included in the latest StarterKit ok for sovereign clouds?

Thank you!

### What solution are you experiencing the issue with?

Core and Audit

### What solution version are you using?

4.33 and 3.24

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Yes you should install Core 4.42 and then everything else, including Audit (Gov) 3.25 and the dashboards from the regular Sept release. 

Everything will behave the same as the commercial folks (Core 4.43) expect you will not have the Power Platform V2 connector and hence will not get the automatic escalation to System Admin role for new environments. 

Hope that all makes sense.

**Comment by github1339** [comment]
Hello Jenefer, that makes perfect sense. I really appreciate your quick reply!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
