### ISSUE TITLE
Flow 'CLEANUP - Admin | Sync Template v4 (Other Objects)' failing

### ISSUE THREAD

**Issue by mirnablazincic** [microsoft/coe-starter-kit#8981]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello!

After installing the September update, we noticed that flow 'CLEANUP - Admin | Sync Template v4 (Other Objects)' failed. 
Error message: "message": "Could not execute workflow 'b1cd7c59-9d1b-4703-ca19-d06f8ec7da56' trigger 'manual' with state 'Disabled': trigger is not enabled."

We checked and the flow from the error message is turned on (CLEANUP HELPER - Environment Capacity), but we noticed that input regarding add-on is missing which is required in the child flow trigger.

![image](https://github.com/user-attachments/assets/d412ad16-1b45-420e-b771-7940bf12c52a)

We also ran the CoE Setup and Upgrade Wizard successfully after the upgrade.

Could you please check and let us know how to solve this issue? Where is this input about add-on being collected?

Thank you and best regards,

Mirna

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v4 (Other Objects)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I think the issue is likely a cached trigger. Can you please try to turn off and back on **_CLEANUP HELPER - Environment Capacity_**

**Comment by mirnablazincic** [comment]
Thank you for the suggestion, turning off the flow and then back on solved the issue.

**Comment by Jenefer-Monroe** [comment]
Thank you for tagging the time to jet me know this of wonderful news!
