### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to upgrade the CoEStarter Kit - 4.37 - August 2024

### ISSUE THREAD

**Issue by karthi-madheswaran** [microsoft/coe-starter-kit#8982]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I’m unable to upgrade the CoEStarter Kit to 4.37 due to a ‘Missing prerequisite’ error during the Center of Excellence Setup Wizard - Compliance Process. Manually turning on the ‘Admin | Sync Template v4 (Driver)’ flow didn’t work either. This is blocking to finalize the upgrade. Please help us.

### Expected Behavior

Unable to complete the Setup Wizard in 'Center of Excellence Setup Wizard - Compliance Process'

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1) Successfully imported all the below upgrade component solutions : https://github.com/microsoft/coe-starter-kit/releases/download/CoEStarterKit-August2024/CoEStarterKit.zip
2) Open solution Center of Excellence – Core Components from Power Apps
3) Under Apps, select the CoE Setup and Upgrade Wizard app, and click Play
4) Go through all the config Initial Setup
5) Go to more features, click on each setup wizard to complete the configuration
Afterwards I'm unable to complete the step 'Center of Excellence Setup Wizard - Compliance Process'

**Comment by Jenefer-Monroe** [comment]
Hello the compliance processes are not hosted in Core. You need to install another solution for this. 
Please see [Set up Developer Compliance components](https://learn.microsoft.com/power-platform/guidance/coe/setup-governance-components)

**Comment by Jenefer-Monroe** [comment]
For the driver, go try to turn it on manually and see what error message you are given.

**Comment by karthi-madheswaran** [comment]
Still the same issue even after following the above recommended solution. 
We are not able to finish the compliance setup. Any other alternative idea for this issue?

**Comment by Jenefer-Monroe** [comment]
Hello you will need to resolve your issue with the Driver flow before you can use compliance so please do go turn  that on manually and see what error message you receive

**Comment by karthi-madheswaran** [comment]
Hello , I tried to turn ON the flow ‘Admin | Sync Template v4 (Driver)’ manually, It didn’t work either.

**Comment by karthi-madheswaran** [comment]
I didn't try to update anything as the flow  ‘Admin | Sync Template v4 (Driver)’ imported from the core solutions. I even tried to Turn ON CoE Flows page and tried directly the flow itself. both doesn't react.

**Comment by Jenefer-Monroe** [comment]
What error message do you receive when you try to turn that flow on from the Product UX?

**Comment by karthi-madheswaran** [comment]
Got the below error when running 'Compliance Process' from Center of Excellence Setup Wizard page : "Missing prerequisite
It looks like some inventory flows required to set up the Compliance process haven't finished running yet. Please check the CoE flows page of the Admin - Command Center app, and return to this setup wizard when the Admin | Sync Template v4 (Driver) flow has finished running."

So I tried to TURN ON the flow , even from the solution, then received below errors : 
"Turn on failed. Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ApiPolicyDataFlowViolation","message":"Admin data policy 'CoE StarterKit Policy' restricts the use of /providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps with /providers/Microsoft.PowerApps/apis/shared_powerplatformadminv2.","extendedData":{"violation":{"policyId":"/providers/Microsoft.BusinessAppPlatform/scopes/service/apiPolicies/7fc30ff1-5542-47ed-becd-a5d9097ea289","policyDisplayName":"CoE StarterKit Policy","type":"BusinessAndNonBusinessConnector","parameters":["/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps","/providers/Microsoft.PowerApps/apis/shared_powerplatformadminv2"]},"additionalInfo":{}}}}"."

**Comment by Jenefer-Monroe** [comment]
It looks like your DLP needs updated. 
Please make sure you have both of these connectors included with the others. They both have documentation bugs tracking them missing from the list

[Power Platform Admin V2](https://github.com/microsoft/coe-starter-kit/issues/8874)
[Microsoft Dataverse (Legacy)](https://github.com/microsoft/coe-starter-kit/issues/8929)

**Comment by karthi-madheswaran** [comment]
Indeed, requested for DLP update. Will try and let you know asap.

**Comment by Jenefer-Monroe** [comment]
Wonderful, please do let me know!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
