### ISSUE TITLE
[CoE Starter Kit - BUG] Inconsistent Power BI Templates

### ISSUE THREAD

**Issue by RandomDept** [microsoft/coe-starter-kit#8983]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

There is inconsistency with the initial setup of below Three Power BI Dashboards.

Power Platform Administration Planning
PowerPlatformGovernance_CoEDashboard_September2024
Production_CoEDashboard_September2024
Pulse_CoEDashboard

When asked for the Centre of Excellence URL some require the full 'https://URL', and fail if you miss the 'https://'
While others require 'URL' and will fail if you add 'https://'

### Expected Behavior

Would be nice if they were all consistent

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

PowerBI Dashboards

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open .pbit file with Desktop Power BI
Enter URL

**Comment by Jenefer-Monroe** [comment]
Hello, yes these were made by different people and they went different directions there. 
Short of a remake I dont think this is something we can resolve Good news is that only two reports receive monthly updates and they both use the same parameter technique

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
