### ISSUE TITLE
[CoE Starter Kit - BUG] Getting error in Admin | Audit Logs | Sync Audit Logs (V2) flow - RetryLogic-ListAuditLogContent'

### ISSUE THREAD

**Issue by bhupendra14** [microsoft/coe-starter-kit#8984]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I have done CoE upgrade for Aug month and since that time I'm getting this error in " Admin | Audit Logs | Sync Audit Logs (V2)
" flow.

InvalidTemplate. Unable to process template language expressions for action 'RetryLogic-ListAuditLogContent' at line '1' and column '12249': 'The template language expression 'equals(outputs('ListAuditLogContent')['statusCode'], 200)' cannot be evaluated because property 'statusCode' cannot be selected. Please see https://aka.ms/logicexpressions for usage details.'.

![image](https://github.com/user-attachments/assets/8b308c2a-b29d-489f-adc0-ae377a5ab7e7)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello are you using plain text or Azure Key Vault for your secret? Can you please go validate that the secret is still valid and that you have entered it in the environment variables? Also perhaps turn the flow off and back on to ensure it gets any env var changes.

**Comment by bhupendra14** [comment]
@Jenefer-Monroe Hi, I have checked secret is still valid, also tried to turn off and turn on the flow. No success yet.

**Comment by Jenefer-Monroe** [comment]
Which secret type are you using?

**Comment by bhupendra14** [comment]
plain text, also we haven't created any Key Vault.

**Comment by Jenefer-Monroe** [comment]
1. Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

1. Please be sure that you have entered the secret itself and not the secret id (the GUID). It’s a longer string with a larger character set than a GUID. This one has a tilda for example.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/983a39fb-0b23-4d1f-83d5-8b41bb2bf270)

1. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

1. Turn the flows off and back on. Sometimes env vars get stuck in them with old values
1. Validate that you have [started the subscription](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
