### ISSUE TITLE
New connectors notification

### ISSUE THREAD

**Issue by TammoJ-S** [microsoft/coe-starter-kit#8986]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Not sure if this is a question for this board, but it's very much Power Platform related.

I'm looking at the Docs page https://learn.microsoft.com/en-us/power-platform/guidance/adoption/new-connectors and try to download the Power Automate templates, but the links bring me to an error page:

![image](https://github.com/user-attachments/assets/3408993d-2deb-46e0-a99c-3ec3de5bff35)

Is there a way to be notified about new connectors, because that's what i want?
Thanks.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Please do go give this team feedback about those links broken as shown here

![image](https://github.com/user-attachments/assets/3d734739-eb02-4067-ae15-8d5722993192)

**Comment by Jenefer-Monroe** [comment]
We do not have anything in the kit that monitors new connectors but if you have the kit installed you could listen for new records to the **_PowerApps Connector_** table. That runs weekly today so you would know within the week one new ones are added to inventory. 

Hope that helps!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
