### ISSUE TITLE
Compliance for COE

### ISSUE THREAD

**Issue by pakalask** [microsoft/coe-starter-kit#8991]
I have configured the compliance feature for COE in the default environment and been implementing in phases. The first phase is apps shared with greater than equal to 25 users and second phase is greater than equal to 10 users. I have completed the phase 1 (Compliance & Quarantine), copied the apps from default to production environment, gone through the BPF and completed the process. Now if i implement the phase 2 do the phase 1 users get the compliance email again because it satisfies the users shared with?

**Comment by Jenefer-Monroe** [comment]
Hello As long as you approved them in the process, then they should not be asked again.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
