### ISSUE TITLE
[CoE Starter Kit - BUG] COE Dashboard - App Shared With (Total) missing from model

### ISSUE THREAD

**Issue by dd767** [microsoft/coe-starter-kit#8992]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Open September COE PowerBi Dashboard.
Navigate to App Deep Dive
Filters on the right include "App Shared With (Total)" and is reported & marked as missing.

### Expected Behavior

To have a total number of "shared with", both from individual users as well as via groups.
Ex: app shared with 10 users and 2 groups (each with 10 users) -> total shared with: 30 users

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

PowerBI Dashboards

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open September COE PowerBi Dashboard.
Navigate to App Deep Dive
Filters on the right include "App Shared With (Total)" and is reported & marked as missing.

### Anything else?

![total](https://github.com/user-attachments/assets/a50cb7e9-1aa5-44be-89e6-042e0f536751)

**Comment by Jenefer-Monroe** [comment]
Hello, I don't repro this. We did remove this field and replace it with another, non-rollup field and in August we forgot to update the PBIT file to match. However in Sept this is fixed. 
Can you please ensure you are using the PBIT file from the Sept release? https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2024

**Comment by Jenefer-Monroe** [comment]
Oh I see we left it in the filters. Yes you can just ignore it, we'll remove in a future version.

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
