### ISSUE TITLE
[CoE Starter Kit - BUG] Discrepancy in data for Power Pages in CoE Admin View and Power Platform Admin Center

### ISSUE THREAD

**Issue by petar2010** [microsoft/coe-starter-kit#8993]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello team,

There is a significant discrepancy between the numbers shown for Power Pages in the CoE Admin View under Power Pages Sites and those displayed in the Power Platform Admin Center under Resources > Power Pages Sites.

### Expected Behavior

We expect the same number, as it should look at the same data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Power Pages inventory is currently broken awaiting the Power Platform Admin V2 connector being GA. 
They did a redesign and they are returned there now. And we cannot yet use them.

**Comment by Daren2023** [comment]
Hi Jenefer,
In the Power Platform Admin View application, within the Power Pages Sites, under overview, can the Application Id be added? This would be beneficial when cross referencing app registrations in Azure AD since AAD does not recognize Power Pages Website ID or Power Pages Unique ID.
Thanks
Daren

**Comment by Jenefer-Monroe** [comment]
That will be the goal yes but we are blocked at this time awaiting the GA of the Powr Platform Admin V2 connector.

**Comment by Jenefer-Monroe** [comment]
The following issue tracks this work
https://github.com/microsoft/coe-starter-kit/issues/8038

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
