### ISSUE TITLE
[CoE Starter Kit - BUG] Embedded PowerApp to manage apps/flows in PowerBI Dashboard does not work after August COE release

### ISSUE THREAD

**Issue by dd767** [microsoft/coe-starter-kit#8996]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Everything worked fine before upgrade to August release files.

When trying to manage access for a powerapp using the embedded app in the Powerbi Dashboard, i get an error related to access to another environment which has nothing to do with the one i'm currently viewing (filtered) and where the Powerapp that i try to manage access permissions resides on.

When trying to manage Powerapps access i get:

PowerAppsforAdmins.GetAdminApp failed: { "error": { "code": "EnvironmentAccess", "message": "The user with object id 'AAAAAAA' in tenant 'BBBBBBB' does not have access to permission 'List Any PowerApps' in environment 'CCCCCC'. Error Code: 'UserMissingRequiredPermission'" } }

When trying to manage Automate Flows, i get:

PowerAutomateManagement.AdminGetFlow failed: { "error": { "code": "EnvironmentAccessDenied", "message": "You are not permitted to make flows in this 'DEFAULT ENVIRONMENT(default)'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions." } }

I am an admin on the COE environment and admin as well on the environment i try to manage apps/flows access on.
As i mentioned before, this worked fine before we updated COE package with August release.

### Expected Behavior

To open & use the embedded PowerApp in the COE PowerBI Dashboard to manage apps & flows access (add/remove users, owners, grant myself access, etc.)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Admin - Access this App [works embedded in Power BI only]

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open COE PBI Dashboard
Go to Apps Deep Dive
Filter by environment where i am admin
Find app in table
Rightclick, drill-thru, manage app access

**Comment by Jenefer-Monroe** [comment]
Dupe to https://github.com/microsoft/coe-starter-kit/issues/8997
