### ISSUE TITLE
[CoE Starter Kit - BUG] Embedded PowerApp to manage apps/flows in PowerBI Dashboard does not work after August COE release

### ISSUE THREAD

**Issue by dd767** [microsoft/coe-starter-kit#8997]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Everything worked fine before upgrade to August release files.

When trying to manage access for a powerapp using the embedded app in the Powerbi Dashboard, i get an error related to access to another environment which has nothing to do with the one i'm currently viewing (filtered) and where the Powerapp that i try to manage access permissions resides on.

When trying to manage Powerapps access i get:

PowerAppsforAdmins.GetAdminApp failed: { "error": { "code": "EnvironmentAccess", "message": "The user with object id 'AAAAAAA' in tenant 'BBBBBBB' does not have access to permission 'List Any PowerApps' in environment 'CCCCCC'. Error Code: 'UserMissingRequiredPermission'" } }

When trying to manage Automate Flows, i get:

PowerAutomateManagement.AdminGetFlow failed: { "error": { "code": "EnvironmentAccessDenied", "message": "You are not permitted to make flows in this 'DEFAULT ENVIRONMENT(default)'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions." } }

I am an admin on the COE environment and admin as well on the environment i try to manage apps/flows access on.
As i mentioned before, this worked fine before we updated COE package with August release.

### Expected Behavior

To open & use the embedded PowerApp in the COE PowerBI Dashboard to manage apps & flows access (add/remove users, owners, grant myself access, etc.)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Admin - Access this App [works embedded in Power BI only], Admin - Access this Flow [works embedded in Power BI only]

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open COE PBI Dashboard
Go to Apps Deep Dive
Filter by environment where i am admin
Find app in table
Rightclick, drill-thru, manage app access

**Comment by Jenefer-Monroe** [comment]
Hello you need to reconfigure these apps whenever you upgrade the kit and dishboard.
[Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard)

**Comment by Jenefer-Monroe** [comment]
Did you do the setup which includes the Reset to Default? 
![image](https://github.com/user-attachments/assets/f0d3c377-6d54-4f8f-941a-05cd7ce5c245)

Then chose the app in your own CoE envt?
![image](https://github.com/user-attachments/assets/27d55c28-f93a-49c2-b6e6-e96da6f1234c)

Are you trying to use with a Canvas app? Note that Model Driven Apps do not work. 

I know there are some instructions online that send you down another path.

**Comment by Jenefer-Monroe** [comment]
I'm really not sure. This is working for me. Can you share a screenshot of where you are failing? 
Are you logged in to PBI as a user with Admin permissions to the CoE Environment? 
Do you have unmanaged layers on those apps?

**Comment by Jenefer-Monroe** [comment]
Are the false envt GUIDs it gives you in your tenant?

**Comment by Jenefer-Monroe** [comment]
Sorry I still dont follow. Are you saying this was possible before? 

**Default envt**
- you are a maker there for SR
- another maker make app "Foo" to which you did not have acccess at all

**CoE Envt**
- you are sys admin there for SR

**PBI**
You used to be able to update the permissions of the app Foo?

**Comment by Jenefer-Monroe** [comment]
ok sorry we are talking over each other. I believe your answer is no then. That is not what was possible. 
You've only ever been able to update permissions to apps/flows in environments to which you were admin.

**Comment by Jenefer-Monroe** [comment]
I just tested this in a test tenant and it does still work. 
Can you confirm the envt you picked here when setting up? 
![image](https://github.com/user-attachments/assets/59bb32af-0617-413e-a0de-be89a13457a1)

**Comment by Jenefer-Monroe** [comment]
Sorry it sounds like it was misconfigured then. That is behavior we see when it is misconfigured. 

1. Validate you are logged in as the expected user in the correct tenant
![image](https://github.com/user-attachments/assets/529b8aa2-b9a8-4003-ba4f-2a2f8506bb70)

2. Validate by hitting refresh on the PPT to see that it refreshes correctly. If it does not then perhaps you need to clear permissions inside of PBI

3. In App deep dive select a canvas app and go to manage app access
![image](https://github.com/user-attachments/assets/1c41cb54-d991-4f79-a462-597dcfa7e3e1)
Should see the name of the app, owner, and envt where the app lives at the top
![image](https://github.com/user-attachments/assets/9c3c4149-6207-4faa-94fd-a352a5a4baa3)

4. Select the control, should see these two fields selected
![image](https://github.com/user-attachments/assets/d11cac32-ae48-4fa7-a475-63704bb8f2ce)

**Comment by Jenefer-Monroe** [comment]
Sorry we are not able to have calls with our users. There is only one person staffing all 12k installs. 
You can try to delete the control and re-add.

**Comment by Jenefer-Monroe** [comment]
ok it looks like there may have been a change in canvas such that the input fields are not deterministically being picked up. 
The issue here was from an upgrade to the product not the kit. 
I'll have to investigate so placing to look for an upcoming release.

**Comment by Jenefer-Monroe** [comment]
It does pay off! haha

**Comment by Jenefer-Monroe** [comment]
It looks like these just needed republished in order to be fixed. I have republished both the embedded apps and now they appear to consistently get the correct app and envt id

**Comment by Jenefer-Monroe** [comment]
May have just been a bug in the version they were using before republish

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
