### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Service Account getting added as co-owner

### ISSUE THREAD

**Issue by patchivs** [microsoft/coe-starter-kit#9000]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Our service account is getting added as co-owner to all the flows in tenant.
Help us with identifying which flow is responsible for this and purpose of getting added. We would need to turn off the flow at the moment
<img width="563" alt="image" src="https://github.com/user-attachments/assets/58773f5d-3b33-43ad-9197-940775256fbb">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Audit Logs | 

### What method are you using to get inventory and telemetry?

None

**Comment by patchivs** [comment]
hello,

Issue is not yet resolved.

Issue still persists.

Please keep the ticket open.

Regards,
Vaishnavi
________________________________

**Comment by Jenefer-Monroe** [comment]
Hello. Note that we dont typically monitor issues that are closed I just happened to see this. 

this behav

**Comment by mohamrizwa** [comment]
We haven’t heard back in a while, so we’ll proceed to close this issue for now. If the issue persists or you need further assistance, feel free to a new issue. We’re happy to help anytime. Thanks again for your engagement!

**Comment by mohamrizwa** [comment]
We haven’t heard back in a while, so we’ll proceed to close this issue for now. If the issue persists or you need further assistance, feel free to a new issue. We’re happy to help anytime. Thanks again for your engagement!
