### ISSUE TITLE
configure the Business Area field of the New Environment Request form in the Maker Command Center

### ISSUE THREAD

**Issue by ktaria11** [microsoft/coe-starter-kit#9003]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I need to be able to configure the Business Area field of the New Environment Request form in the Maker Command Center. I don't see how to configure this for our BU cost centers for billing and reporting purposes. I saw one post about this back in January but I don't see this in the backlog. Can I get an update on this field or if there is a different field that I can use to tie Environments to cost centers? Please and thank you! ;)

![2024-09-20_13-54-24](https://github.com/user-attachments/assets/c20211f4-d3cd-4b28-a958-ab1c2869a98b)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Core/Maker Command Center/Environment Request

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
It does not appear that this field has been integrated into the Environment Creation Request app. 

If you were to add it, I presume you would connect it to this table which is part of the kit: 
![image](https://github.com/user-attachments/assets/ab6e40ae-4580-4576-bd8e-8c6680fa2078)

Please let me know if I've misunderstood your question.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
