### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - PULSE Feedback setup  Power BI dashboard to view feedback

### ISSUE THREAD

**Issue by vivekbillore23** [microsoft/coe-starter-kit#9006]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) . Simplify this issue

### Expected Behavior

It should open the Pulse COE dashboard powerbi report

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

3.29

### What app or flow are you having the issue with?

COE - Nurture component

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

when open pulse COE dashboard , after pasting environment url , this issue is coming

**Comment by Jenefer-Monroe** [comment]
What format did you use to paste the URL? 

Please refer to [Set up the Power BI dashboard to view pulse feedback](https://learn.microsoft.com/power-platform/guidance/coe/setup-nurture-components#set-up-the-power-bi-dashboard-to-view-feedback)

**Comment by vivekbillore23** [comment]
Enter the URL of your environment instance. Don't include the https:// prefix or / postfix for OrgUrl. this format I have used

**Comment by vivekbillore23** [comment]
![image](https://github.com/user-attachments/assets/0f5e511e-5ebc-4d16-a78d-afdc5361483d)

**Comment by Jenefer-Monroe** [comment]
Sorry you are having problems with the platform here not the PBIT file itself. Please look through our troubleshooting guide, it contains workarounds other users have given us for PBI issues. 

https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#troubleshooting

**Comment by vivekbillore23** [comment]
I have checked the above URL . But still not able to solve this error , I want ask one question do I need to have Global Admin access to setup power bi report for COE ?

**Comment by Jenefer-Monroe** [comment]
No you do not need Global Admin. You only need access to the envt. Are you logged in to PBI as the user that setup the kit? 
Is this the format of that you are entering for the parameter? orgname.crm.dynamics.com

**Comment by vivekbillore23** [comment]
yes ,  I have logged in PBI as the user that setup the kit , yes I am following this parameter - orgname.crm.dynamics.com

**Comment by Jenefer-Monroe** [comment]
Ok sorry I'm not sure how to help then. This is an issue with PBI not our template.
