### ISSUE TITLE
[CoE Starter Kit - BUG] - COE Admin Command Center is giving DLP issue

### ISSUE THREAD

**Issue by vivekbillore23** [microsoft/coe-starter-kit#9007]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Error Code: AppForbidden
Session Id: da36488e-6276-4de5-baba-08a579a6134e
Activity Id: 119302d9-8aee-4810-a01c-cf099c5a2f8e
Timestamp: Mon Sep 23 2024 13:47:09 GMT+0530 (India Standard Time)
It looks like this app isn't compliant with the latest data loss prevention policies.
UciError: It looks like this app isn't compliant with the latest data loss prevention policies. at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.7b13b88bb556c4c2fe1101c29c9032c9.js:33:973470) at https://content.powerapps.com/resource/uci-infra-bus/scripts/custompage.df406b42dc7ff3c466cb7f6d72ba9141.js:4:23196

### Expected Behavior

It should open app , I have added all connectors suggester here   [Connectors ](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#validate-data-loss-prevention-dlp-policies) but still not working.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

COE Admin Command Center App

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. COE Environment
2. Open COE Admin Command Center App

**Comment by Jenefer-Monroe** [comment]
Please ensure you have the Microsoft Dataverse (Legacy) included in the DLP. 
Please see https://github.com/microsoft/coe-starter-kit/issues/8929

**Comment by vivekbillore23** [comment]
It is working now , I had assigned those connectors to different environment ,  that was the reason it was not working

**Comment by Jenefer-Monroe** [comment]
oh wonderful news, thanks for taking the time to let me know! 
I'll go ahead and close this out then
