### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION Is there a way to get a list of app/flows from an owner who has departed the company?

### ISSUE THREAD

**Issue by snl-meg** [microsoft/coe-starter-kit#9010]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

A user has recently left the company. When I look at Power Platform Admin View I look for the make and found 1 app and 72 flows. When I click on it, it doesn't show me a list. Is there another app I should be using to obtain this information?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

PowerPlatform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, yes please go to the Manage Permissions app and you will see the following for both canvas apps and cloud flows

![image](https://github.com/user-attachments/assets/e769d6e7-35fa-4539-acb5-1fa015086f45)

**Comment by snl-meg** [comment]
When I go to manage permissions it only shows me 1 flow, but when I looked at PowerPlatform Admin View it shows 72.

***@***.***

Maria

**Comment by Jenefer-Monroe** [comment]
Can you please share screenshots? Note you will need to log in to GitHub to share them you cannot share images when responding in email.

**Comment by snl-meg** [comment]
![image](https://github.com/user-attachments/assets/7cb14c85-7382-48aa-ae36-d0bfed6f764e)

**Comment by snl-meg** [comment]
![image](https://github.com/user-attachments/assets/d0cbce80-507c-439a-a9f6-cb5ba20639a7)

**Comment by Jenefer-Monroe** [comment]
Your first screenshot did not come through. 
Note that in the screenshot from Managed Environment app you are filtered to a single owner though.

**Comment by snl-meg** [comment]
Yes in the power platform view it shows that user has 72 flows.
When I go to Manager Permission apps it only shows that user has 1.

Maria

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by snl-meg** [comment]
Sorry I never received a notification about your earlier message. I have it filter under the users name but I don't see the 72 flows its referring to in Manage Permissions.
