### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Log View in Power platform Admin view creation time is not displaying correct timezone

### ISSUE THREAD

**Issue by Jash718** [microsoft/coe-starter-kit#9011]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I upgraded the  Coe starter kit to the September version in my test environment and now despite being in EDT time zone, the audit clogs creation time in "Power platform admin view" app is showing in UTC.
When checked in the "Audit log" table itslef, it shows correct timezone.
![image](https://github.com/user-attachments/assets/a0b6b60c-8f3d-4d48-a14d-48538250359d)
![image](https://github.com/user-attachments/assets/7bc3c965-5810-4f4f-8b5e-53a539048bc3)

### Expected Behavior

The timezone should be EDT

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
The logs come to us in UTC so that is what we store but the field is set to show user local time. I just tested and this is working for me. Perhaps you are using a shared account whos time zone setting is utc?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
