### ISSUE TITLE
[CoE Starter Kit - BUG] Too many actions - Sync Template v4 (Security Roles)

### ISSUE THREAD

**Issue by sboddez** [microsoft/coe-starter-kit#9012]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Since upgrading to the August 2024 release, I'm intermittently getting an email stating that "Admin | Sync Template v4 (Security Roles)" is running too many actions. I never received this message for this flow prior to the upgrade. I run two copies of the CoE kit in separate environments, one with cloud flows and one with data export. This only seems to occur in the cloud flows version.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Security Roles)

### What method are you using to get inventory and telemetry?

Cloud flows

### Anything else?

![image](https://github.com/user-attachments/assets/c6c7766a-1009-4e5e-b649-34c927f1048e)

**Comment by Jenefer-Monroe** [comment]
There has not been a change here in this flow so its likely that you are just monitoring too many SRs for the cloud flow infra to work. 

The only thing that did change in August was that we fixed up the situation where people were not getting access to new environments, so it could be that too. 

If you wish to continue monitoring the SRs, you may need to reduce the number of SRs you monitor, which can be done here: 
![image](https://github.com/user-attachments/assets/e6182a9d-67fc-4b6f-a623-258713985703)


Or you can wait to see if this was a one off while the new roles populate. 
Or you can purchase a per-flow license to allocate api calls for it and make the flow run more quickly.

**Comment by sboddez** [comment]
Thanks Jenefer, I appreciate the insights!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
