### ISSUE TITLE
[CoE Starter Kit - BUG] Audit History in Power Platform Admin View App

### ISSUE THREAD

**Issue by Sinder088** [microsoft/coe-starter-kit#9013]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When using the Power Platform Admin View app, we are unable to view Audit History on any items, for example a specific flow, it is just blank: 
![image](https://github.com/user-attachments/assets/07843693-c316-472b-b6b5-c63f3628fd90)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.35

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open Power Platform Admin View
2. Click on Flows
3. Select a flow
4. Click on "Related"
5. Click on "Audit History"

**Comment by Jenefer-Monroe** [comment]
Hello, we do not store any information in there, so its expected to be blank.

**Comment by Sinder088** [comment]
Ah ok, thanks. Is there another way we can get specific audit history on a flow to understand why it was turned off? We are trying to understand if it was user or system driven. As Power Platform admin we don't have access to purview, so wondering if there is another option?

**Comment by Jenefer-Monroe** [comment]
To my knowledge the edits and such for a flow are not stored anywhere by the product other than the logs. So you could explore through Microsoft Purview: https://purview.microsoft.com/audit/ 

You can select all the flow actions, though I do not see enable/disable in there.
![image](https://github.com/user-attachments/assets/cc000279-5ef3-4768-b7d6-4079e5d1baf1)

Unfortunately there does not seem to be a way to filter to an individual flow in their ux so you have to get all flow activity and find your target flow in the output.

**Comment by Sinder088** [comment]
Thank you.
