### ISSUE TITLE
[CoE Starter Kit - QUESTION] PowerApps App Total Shared

### ISSUE THREAD

**Issue by iamjina** [microsoft/coe-starter-kit#9014]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi team, 

I noticed under the new CoE version (Sept 4.43) Total Shared column has been deprecated within the PowerApps App table. This information is critical to understand the app usage. Has this column been officially deprecated, if so, do we have any other columns that provide similar information? Please advise. 

Thank you! 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello yes we replaced this with another column. We just had too many issues with the roll up field in many tenants. 

You can see a bunch of information about shared with now as shown here, where total is called out in red.

![image](https://github.com/user-attachments/assets/183ef9a9-4139-4846-9d75-05ad560298c1)

**Comment by Jenefer-Monroe** [comment]
The naming changed as well as how its filled. In the past it was a roll up field and now it is not. 

We also now get a better tally for number of viewers. In the past we only counted users directly added (not users in groups) and now we count both users directly added as well as users that are in groups.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
