### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION About CoE's app execution log.

### ISSUE THREAD

**Issue by syou0224ondr176mocoksrg** [microsoft/coe-starter-kit#9015]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Why is the CoE app execution log so small compared to the number of records in Purview's app execution log?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What method are you using to get inventory and telemetry?

None

**Comment by syou0224ondr176mocoksrg** [comment]
Thanks for the reply.

The Canvas app execution log is less than expected.
For example, when I search the Purview audit log record type as LaunchPowerApp, it shows 3984 records.
However, the “Audit log” table in CoE shows only 3708 records.

I examined the differences and found that 376 records appeared only in the Purview audit log and 100 records appeared only in the CoE's “Audit log” table.

Do you know the reason for this difference?

**Comment by pete-msft** [comment]
@syou0224ondr176mocoksrg could it be that some of those apps are deleted? CoE Audit Log sync inserts the event to Audit Log table only if app exists in CoE. Also you can try to manually import LaunchPowerApp events from Purview to CoE if needed

**Comment by syou0224ondr176mocoksrg** [comment]
I checked the list of apps and the Purview deletion log, but the apps do not appear to have been deleted.

In addition, I checked the app execution log again and found no records stored only in the CoE execution log. (I had filtered the logs to show only the logs during August, but it seems the filtering point was different.)

One more question,
It seems that not all of Purview's LaunchedPowerApp records are stored in CoE's audit log table.
Is this behavior in accordance with the specification?

**Comment by pete-msft** [comment]
@syou0224ondr176mocoksrg yes CoE Kit takes only DeleteApp, DeleteFlow and LaunchPowerApp event and only LaunchPowerApp event is stored in Audit Log table

**Comment by pete-msft** [comment]
@syou0224ondr176mocoksrg Have you tried to export LaunchPowerApp events which are missing and import to CoE? If you can clearly see gaps in the events for time ranges then I would try to export and import those events.

**Comment by syou0224ondr176mocoksrg** [comment]
I understand.
Thanks for the answer.
