### ISSUE TITLE
[CoE Starter Kit - BUG] Data Mismatch error #8960

### ISSUE THREAD

**Issue by rashibhalla** [microsoft/coe-starter-kit#9016]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

My previous GitHub case was closed without providing an update or solution. 
Case details : [CoE Starter Kit - BUG] Data Mismatch error #8960

### Expected Behavior

CoE Starter kit data should match with environment consumption data from Power Platform admin portal.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

NA

### What app or flow are you having the issue with?

Data in CoE Toolkit

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Export the dataverse consumption data from CoE Toolkit and Export the data from Power Platform admin portal
compare the data and it shows data from CoE toolkit is consistent where data in Power Platform admin portal is gradually increasing

**Comment by Jenefer-Monroe** [comment]
Hello we close issues after a week of inactivity to keep the list tidy. 
I'll re-open that one for you instead where we have the details.
