### ISSUE TITLE
[CoE Starter Kit - QUESTION] CoE Starter Kit - Inactivity Notifications: How do we stop them?

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#9022]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Every Sunday/Monday we get hundreds of inactivity notifications that are flooding our inboxes, so we are trying to just stop the inactivity flows all together. After turning off all the Governance Solution flows and anything that says inactivity, we are still getting the notifications. Where do we turn off the Inactivity notifications, If not the governance flows?

Example email:  "CoE Starter Kit - Inactivity Notifications: This app owner cannot perform approval" notification. 

The following object was attempted to go through the Inactivity Notification processes but the creation of the approval failed.
Please see Common errors creating and assigning flow approvals to troubleshoot why this can occur

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

September 2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
The flows are in the governance solution. You can validate you have them all turned off in the command center as shown below. 
For runs that have already started, these will complete though and can be long running, so you may want to go cancel any running instances, you can get to those from the command center as well

![image](https://github.com/user-attachments/assets/b6af12a8-4d1d-497b-968a-accfe5542105)

**Comment by Jenefer-Monroe** [comment]
You bet. I'll keep this open for a week or so to see if it clears for you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
