### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by mppreethi** [microsoft/coe-starter-kit#9023]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Expression.Error: The column 'admin_appenvironmentlogicalname' of the table wasn't found.
Details:
    admin_appenvironmentlogicalname

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.7

### What app or flow are you having the issue with?

Import kit

### What method are you using to get inventory and telemetry?

None

### Anything else?

Failed to load the file. Kindly advise to overcome this issue. Can I remove those columns?

![image](https://github.com/user-attachments/assets/c12d4718-f313-4287-8f91-4b9001e76a61)

**Comment by Jenefer-Monroe** [comment]
Hello. Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

Then what version of the PBIT did you use?

**Comment by mppreethi** [comment]
Requested screenshot:
![image](https://github.com/user-attachments/assets/44b25277-c861-4d02-94e5-542885b1827c)

PBIT - September2024

![image](https://github.com/user-attachments/assets/263156ef-2fc9-4035-8cb7-5abb83011ae6)

**Comment by Jenefer-Monroe** [comment]
I see you are on the April 2024 release of Core. (4.29) you need to match the version of the PBIT file with the version of Core. 
Those fields are newer than April. 

You will need to either upgrade or use April's pbit file.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
