### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by tiis-stakazawa** [microsoft/coe-starter-kit#9025]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

The number of flows created with PowerAutomate output by Flows in the Power Platform Admin View was 6,567 flows when acquired around 10:30 AM on September 16, 2024, and 7,762 flows when acquired around 8 PM on the same day.
It is unlikely that more than 1,000 flows were created in such a short period of time.
Please investigate the cause of this increase in the number of flows created in such a short period of time.
[Active Flows 9-16-2024 10-33-45 AM.xlsx](https://github.com/user-attachments/files/17126006/Active.Flows.9-16-2024.10-33-45.AM.xlsx)
[Active Flows 9-16-2024 7-59-03 PM.xlsx](https://github.com/user-attachments/files/17126010/Active.Flows.9-16-2024.7-59-03.PM.xlsx)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry we are not able to investigate for you from afar like this. Keep in mind the kit is a template and not a product. 
However I'm happy to work with you here if you'd like to investigate. 

First note that you are on the Feb 2024 release so I don't remember exactly what the flows were like back then. 
Please go look at the 1,000 new flows, 
- what is their flow created on date? 
- what is their state? are they all on/off/etc?
- are they all in the same environment(s)?
