### ISSUE TITLE
The number of PowerAutomate flows created obtained in the Power Platform Admin View is not accurate.

### ISSUE THREAD

**Issue by TAKAZAWA-SAKURAKO** [microsoft/coe-starter-kit#9029]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

The number of flows created with PowerAutomate output by Flows in the Power Platform Admin View was 6,567 flows when acquired around 10:30 AM on September 16, 2024, and 7,762 flows when acquired around 8 PM on the same day.
It is unlikely that more than 1,000 flows were created in such a short period of time.
Please investigate the cause of this increase in the number of flows created in such a short period of time.
[Active Flows 9-16-2024 7-59-03 PM.xlsx](https://github.com/user-attachments/files/17128882/Active.Flows.9-16-2024.7-59-03.PM.xlsx)
[Active Flows 9-16-2024 10-33-45 AM.xlsx](https://github.com/user-attachments/files/17128883/Active.Flows.9-16-2024.10-33-45.AM.xlsx)

### Expected Behavior

The number of flows created with PowerAutomate output by Flows in the Power Platform Admin View does not increase or decrease by 1,000 flows in a short period of time.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Select Flows under Monitor in the Power Platform Admin View app.
2. Click Export to Excel at the top to export the Excel sheet.
3. Open the Excel sheet and check the number of flows created.
<img width="635" alt="20240925" src="https://github.com/user-attachments/assets/e3f8ceb8-66d9-462a-9479-0386c3a242d6">

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry we are not able to investigate for you from afar like this. Keep in mind the kit is a template and not a product. 
However I'm happy to work with you here if you'd like to investigate. 

First note that you are on the Feb 2024 release so I don't remember exactly what the flows were like back then. 
Please go look at the 1,000 new flows, 
- what is their flow created on date? 
- what is their state? are they all on/off/etc?
- are they all in the same environment(s)?

**Comment by TAKAZAWA-SAKURAKO** [comment]
Hello.
Thank you for your cooperation in the investigation.

＞what is their flow created on date?
There is no creation date information in the exported Excel. I know the Flow Modified On date, but it spans from 2018 to 2024.

＞what is their state? are they all on/off/etc?
Flow states are started, stopped, and suspended.

＞are they all in the same environment(s)?
No

**Comment by Jenefer-Monroe** [comment]
Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently? 
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

**Comment by TAKAZAWA-SAKURAKO** [comment]
Yes.
<img width="955" alt="20240926_1" src="https://github.com/user-attachments/assets/ea7da8a8-1135-4d58-b72b-c4d4b5c3ec25">

**Comment by Jenefer-Monroe** [comment]
OK I’m afraid you’ll need to find a case where the inventory is incorrect. And with that we can investigate.

**Comment by TAKAZAWA-SAKURAKO** [comment]
Are you asking for an excel sheet that had a small number of flows when I output it?

**Comment by Jenefer-Monroe** [comment]
No sorry we are not a product and so I do not have access to your tenant. 
If you find a repro, meaning one of these situations
- a flow that is is inventory and should not be
- a flow that should be inventory but is not

then I can walk you through how to investigate with me to see what might be the problem.

**Comment by TAKAZAWA-SAKURAKO** [comment]
I understand that the current information is not enough for you to investigate.
I will contact you again when I experience a similar sudden increase or decrease in the number of Power Automate flows.

**Comment by Jenefer-Monroe** [comment]
Sounds good. Please do let me know if you find inaccuracies.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
