### ISSUE TITLE
[CoE Starter Kit - QUESTION] orphaned process --> email me

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#9031]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

how is the orphaned process supposed to proceed after the manager clicks on email me?
![image](https://github.com/user-attachments/assets/6e682174-6c42-41e4-ab9f-254fafb4734c)

Because after the manager clicks email me, the adaptive card gets edited to "trying.." 
![image](https://github.com/user-attachments/assets/a0dfa0e5-7478-4bf8-92af-37f2c412acd2)
or "Mail sent" and the manager get an Overview of the orphaned resources via mail.

But there is no possibility that he can now decide what to do with these resources or is there?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

august 2024

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Thats correct. The idea here was that they can get a list in email with which to prepare for the next time they are asked (the next week's run)

**Comment by lukas-nC** [comment]
thanks
