### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to upgrade 4.43 -  issue with 'admin_totalshared' column

### ISSUE THREAD

**Issue by Gpn85** [microsoft/coe-starter-kit#9034]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We are upgrading Solution "Center of Excellence - Core Components from version 4.33 to 4.43. However the solution import fails with:

Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding failed with exception :The FetchXml (<fetch version="1.0" output-format="xml-platform" mapping="logical" savedqueryid="c454b997-4940-436b-b2db-31f344ddc4bf"><entity name="admin_app"><attribute name="admin_appid"/><attribute name="admin_displayname"/><attribute name="admin_appenvironment"/><attribute name="admin_appowner"/><attribute name="admin_appmodifiedon"/><attribute name="admin_powerappstype"/><attribute name="admin_applastlaunchedon"/><attribute name="admin_appidstring"/><filter type="and"><condition attribute="statecode" operator="eq" value="0"/><condition attribute="admin_appdeleted" operator="eq" value="0"/></filter><order attribute="admin_applastlaunchedon" descending="false"/><attribute name="admin_appcreatedon"/><attribute name="admin_appdeleted"/><attribute name="admin_appdeletedon"/><attribute name="admin_appenvironmentid"/><attribute name="cr5d5_appisorphaned"/><attribute name="admin_appownerdisplayname"/><attribute name="admin_apppublished"/><attribute name="admin_appsharedgroups"/><attribute name="admin_appsharedusers"/><attribute name="admin_appsharedwithtenant"/><attribute name="admin_appuniquename"/><attribute name="admin_appstate"/><attribute name="createdby"/><attribute name="createdon"/><attribute name="admin_issolutionapp"/><attribute name="admin_totalshared"/><attribute name="admin_totalshared_date"/><attribute name="admin_totalshared_state"/><attribute name="admin_usescustomapi"/><attribute name="admin_usespremiumapi"/><attribute name="versionnumber"/><attribute name="admin_appconnections"/><attribute name="admin_appdescription"/><attribute name="admin_launchesinthepast30days"/><attribute name="admin_mau"/><attribute name="admin_mau_date"/><attribute name="admin_mau_state"/><attribute name="ppautoma_settobedeletedon"/></entity></fetch>) is invalid. Failure ('admin_App' entity doesn't contain attribute with Name = 'admin_totalshared' and NameMapping = 'Logical'. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = True, Timestamp=15262473, MinActiveRowVersion=15262473, MetadataInstanceId=53282292, LastUpdated=2024-09-24 09:25:21.870, OrgId=5697f2f2-64ea-ed11-a80b-000d3a3a2963) occurred while calculating dependencies for SavedQuery (Id=c454b997-4940-436b-b2db-31f344ddc4bf).

Seems to be referencing the column 'admin_totalshared' which was deprecated in earlier release?
<img width="893" alt="coe_4 43" src="https://github.com/user-attachments/assets/fe536fe0-300f-4f8b-a4b7-497a239a4db6">
 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Yes it was deprecated. You may have taken local dependencies. You'll need to go find the dependencies and clean them up. 
![image](https://github.com/user-attachments/assets/9d8099ff-90f3-4155-85cd-47bb2e0438d1)

**Comment by Gpn85** [comment]
This column does not seem to be present in our solution
![image](https://github.com/user-attachments/assets/89e4bc24-21cf-4f7e-a980-e4cf03fc607e)

**Comment by Gpn85** [comment]
I think I found the issue. There is a View created on the table that contains these deprecated columns. I will try to delete the view ad re-import.
![image](https://github.com/user-attachments/assets/45565264-2f5a-4111-b6ee-2476d8eb4c32)
![image](https://github.com/user-attachments/assets/80680507-e689-4449-9a32-275a698685f6)

**Comment by Jenefer-Monroe** [comment]
Thank you for exploring and finding resolution! you're great!

**Comment by Gpn85** [comment]
Removing active customizations from the Views on the PowerApps table solved the issue :) Thanks for your help!

**Comment by Jenefer-Monroe** [comment]
Wonderful news!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action from starter kit team
