### ISSUE TITLE
[CoE Starter Kit - QUESTION] "PowerApps App" relationship with "Power Platform Solutions"

### ISSUE THREAD

**Issue by russxi** [microsoft/coe-starter-kit#9036]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi,

I just wanted to check, How is an app related to a solution in CoE Starter Kit? Is there a column used to related both tables?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. 
Retrieving the components of a solution is not very simple unfortunately. We use a table in each envt called solutioncomponents which is hidden and has some undocumented fields we use to find object types. 
Honestly we kind of force tested this until it returned what we wanted. 
You can play around though and see if you find something better / easier. If you do please let us know!
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3562f923-a77c-44b9-b9fa-67b4a703ede2)

You can find this in the **_CLEANUP HELPER - Solution Objects_** flow (note in Feb it was still part of the **_Admin | Sync Template v4 (Solutions)_** flow)
