### ISSUE TITLE
Cannot upgrade to version 4.43 of Core. Upgrade and Update solution fail.

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#9037]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hi,

We tried to recently upgrade to version 4.43 of Core Components, with no luck. It usually goes smooth, but this time, neither the Upgrade nor the Update did it for us.

Screenshot below shows how we tried an Upgrade, followed by an Update, with the same failure result (error code 80072352). 
![image](https://github.com/user-attachments/assets/4551737c-172e-4e7d-88b8-a3504115b1fc)

This below is all that I was able to find about the failure code:

0x80072352   : CanvasAppsServiceRequestClientFailure   Message: The request to the PowerApps service failed with a client   failure.

Can you please shed some light as to what we should do next?
Previous version was 4.37 (August).

Much appreciated,

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Upgrading to September Release

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Sorry I dont think we can help there. That error message is pointing to product issues not issues with the solution file. There was an issue sending something to the server. 

When did it fail in the process? Early? Did it leave behind an _upgrade? Please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by VanIsleCA** [comment]
Hi, Jenefer,

Thanks so much for getting back to me. Here's the requested screenshot, it did not leave any _Upgrade. I noticed that, more recently, it no longer leaves a trace of the uninstall too, so just hard to know what is actually doing.

![image](https://github.com/user-attachments/assets/0c03e224-6363-496d-bd87-5bdb58f80639)


In terms of when does it fail, I would say that within the first hour of the import, considering that it usually takes it 3h or so to finish.

Thanks!

**Comment by Jenefer-Monroe** [comment]
OK unfortunately I think you will just have to try again. It looks like you tried last a few days ago. This may have been some intermittent issue with the product's ALM code. Hopefully it works this time but if not you may need to contact product support as this failure is in the products communication front to back end, not in the kit's solution file. 

Please let me know if this works on retry.

**Comment by VanIsleCA** [comment]
Thanks, Jenefer,
Retried for 3 days in a row now, no success
![image](https://github.com/user-attachments/assets/1923ceb3-12bd-4f34-bea8-dec044c9f7c9)

I have also opened a ticket with Microsoft, will let you know how that goes,

Thank you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
