### ISSUE TITLE
[ALM Accelerator - QUESTION] Deploy Pipelines in the solution folders are created without content

### ISSUE THREAD

**Issue by FQ365Microsoft** [microsoft/coe-starter-kit#9038]
### What is your question?

HI,
The deploy pipelines are being created for the solutions on commit. The issue is the pipeline yml files are empty in the solutions folder. If I manually add the content to the file it works fine. But it would be a lot of manual work for every solution we need to deploy. Any clues why the content are not copied. Following is the screenshot from the logs.

![image](https://github.com/user-attachments/assets/23baa567-09ff-4cd5-bcc0-a9a4a4a753b2)

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

March 2024

**Comment by mikefactorial** [comment]
@FQ365Microsoft if you're adding a new Deployment step you'll need to provide a template for it in Azure DevOps. There's instructions here with an example for an acceptance environment but you can follow the same steps for your dev environment. https://learn.microsoft.com/en-us/power-platform/guidance/alm-accelerator/customize-deployment-pipelines#customize-the-pipeline-template-for-a-new-acceptance-environment

**Comment by FQ365Microsoft** [comment]
Thank you. Yes, I can use deployment steps like mentioned above.
