### ISSUE TITLE
[CoE Starter Kit - BUG] Existing CoreComponents package not recognized during import

### ISSUE THREAD

**Issue by Gpn85** [microsoft/coe-starter-kit#9039]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We would like to upgrade our CoE core solution from 4.33 to 4.43. Current installation:

![image](https://github.com/user-attachments/assets/aa894ae6-d1b3-4007-ab69-beddec1c31a1)

However, when importing the new version 4.43. it does not give as the option to Upgrade. It does not seem to recognize the existing solution and is trying to import it as New:

![image](https://github.com/user-attachments/assets/1e8ec3d4-74eb-44c4-a8c0-693cf53bcc60)

Some background information:
During last upgrade (4.31->4.33) the 4.31 package was not uninstalled properly because of the following error:

![image](https://github.com/user-attachments/assets/f8c0630a-c0ab-4b52-8a43-5405e65d230d)

Because of the error we ended up removing the old package (4.31) manually . 
Could you please advise why the existing package wouldn't be recognized during the import? How can we proceed to ensure we can upgrade without doing a fresh installation and losing the existing inventory?

### Expected Behavior

Existing package is recognized and upgraded.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponents_4_43_managed

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Gpn85** [comment]
oh now when you asked me to expand the columns I can see the current solution comes with the "_upgrade" suffix which I guess is a consequence of the previous failed upgrade/uninstallation.

![image](https://github.com/user-attachments/assets/526cf5da-ef70-4d17-9213-46c8079a5575)

The option to "Apply upgrade" is grayed out.. Anything I can try to fix this state?

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot so that I can see all the solutions?

**Comment by Gpn85** [comment]
Here you go:

![image](https://github.com/user-attachments/assets/7730e84a-da55-448f-80e6-e90ace72471f)

**Comment by Jenefer-Monroe** [comment]
Yes it appears that the original Core is gone. I've never seen that happen before! I'm used to seeing in this case two solution files 

CenterofExcellenceCoreComponents and CenterofExcellenceCoreComponents_upgrade

You can try doing an overwrite, that may work, can you try?

### How to do an overwrite upgrade in the classic UX:
 
Switch to classic
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/690cafcb-ade8-4571-81d5-df70f97f6266)

Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/433cd2d8-7e2a-4d35-a86e-cf569b7777f2)

Select Core > Next
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f232f4b5-783d-4d8c-af94-21fb6dfd91bf)

Next
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/39c84d9b-7ccf-4aff-8861-6c70ed7cb237)

Overwrite customizations > Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7b23463c-2361-4135-81a8-363a96ca23d5)

**Comment by Gpn85** [comment]
Unfortunatelly it is the same, it does not recognize the existing solution and does not offer me to do an upgrade/overwrite:

![image](https://github.com/user-attachments/assets/04e4c1eb-1b8b-4967-a3a7-c33b4e45372a)

**Comment by Jenefer-Monroe** [comment]
Do you have tables currently with inventory? If the solution is gone I'm not sure if the tables will even be there.

**Comment by Gpn85** [comment]
Yes, the tables with inventory data are present.

**Comment by Jenefer-Monroe** [comment]
ok I'm really not sure then. There is a product bug here in that the Core_upgrade is present but not Core. I've never seen this. 
It's possible that installing Core again as if it were new would fix. The tables are all the same after all. I don't know what would happen to the _upgrade in that case, but I think you could delete it once you have Core.

I think your options are to try the above or contact product support.
Sorry!

**Comment by Gpn85** [comment]
I have now imported the Core solution and it imported successfully. Now I have both Core and Core_upgrade.  Deleting Core_upgrade fails with a timeout error.. I have opened a case with MS for that. Thanks for all your help, please go ahead and close this issue.

**Comment by Jenefer-Monroe** [comment]
Is the timeout error in the UX or the solution history? A timeout in the UX (a ribbon) is fairly normal unfortunately.

**Comment by Gpn85** [comment]
It's a timeout in the UX (a ribbon)

**Comment by Jenefer-Monroe** [comment]
oh good so it may still work. Fingers crossed please do let me know.

**Comment by Jenefer-Monroe** [comment]
thanks for walking through it with me, if others hit it I can feel confident about the suggestion now ! 
I'll go ahead and close this out then but please do feel free to return with new issues if you have other questions.
