### ISSUE TITLE
[CoE Starter Kit - BUG] Most of the Power Automate Cloud Flows are failing with the same error - The specified user(Id = {0}) is disabled. Consider enabling this user. Additional Details: {1}.

### ISSUE THREAD

**Issue by johnvittneyk** [microsoft/coe-starter-kit#9040]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We installed/Upgraded the latest version of the CoE and a few flows are failing with the same error - The specified user(Id = {0}) is disabled. Consider enabling this user. Additional Details: {1}.

### Expected Behavior

We installed/Upgraded the latest version of the CoE and a few flows are failing with the same error - The specified user(Id = {0}) is disabled. Consider enabling this user. Additional Details: {1}.

<img width="1404" alt="Screenshot 2024-09-26 at 7 08 13 PM" src="https://github.com/user-attachments/assets/20d0b4b7-2dee-4103-85c0-7f3cc0b84e2e">

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

These flows run by default, scheduled flows.
<img width="1404" alt="Screenshot 2024-09-26 at 7 08 13 PM" src="https://github.com/user-attachments/assets/a071ba8b-ab1a-439b-bf64-3438c51209ca">

**Comment by Jenefer-Monroe** [comment]
Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently? 
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

**Comment by johnvittneyk** [comment]
Yes, we do have the role Power Platform Administrator and is Direct and Permanent for the two accounts that are being used on the CoE.

**Comment by Jenefer-Monroe** [comment]
Can you please show me where in the flow this is failing? Ideally with a screenshot

**Comment by johnvittneyk** [comment]
Here is one example @Jenefer

<img width="1716" alt="Screenshot 2024-09-26 at 9 39 50 PM" src="https://github.com/user-attachments/assets/aabfa827-8fd5-41a5-8d9b-03be37fde227">

**Comment by Jenefer-Monroe** [comment]
This is saying that the user is disabled so there must be something wrong with the user in the target envt. 

1. What type of user is this? (service principle, shared account, personal account)
2. In [PPAC](https://admin.powerplatform.microsoft.com/environments), go to the target envt that they are trying to fetch desktop flows here, this one
![image](https://github.com/user-attachments/assets/225e4c9a-ab79-49f2-89cb-620528ba800a)
3. Go to users and find the user running the flow. What is their user status and are they System Admin?
![image](https://github.com/user-attachments/assets/727b0f75-81eb-4532-9005-945d62505e2e)

**Comment by johnvittneyk** [comment]
Thank you for all the guidance. The user account is a service account (shared) created exclusively for the CoE alone.
As you guided, we don't see this user in the users list.

Are we supposed to add the account that is owning the CoE to all Environments as System Administrator exclusively? Is the Power Platform Admin Role enough on the environment?

**Comment by Jenefer-Monroe** [comment]
If you are on 4.37 then this should be happening for you automatically. It added the work to escalate the logged in user as the system admin in each envt. 
Can you see if you unmanaged layers on the driver flow? That is where the escalation occurs. Admin | Sync Template v4 (Driver)

**Comment by johnvittneyk** [comment]
Jenefer, We upgraded the CoE on 9th Sept, 2024. But looks like this layer is added on 11th Sept, 2024. I don't any one of us made an edit to the flow. 
<img width="804" alt="image" src="https://github.com/user-attachments/assets/ecb3b1f5-d183-4a08-b25c-00bbe42c7791">

<img width="840" alt="Screenshot 2024-09-27 at 8 35 13 AM" src="https://github.com/user-attachments/assets/dbd732c3-e298-4bdc-8901-2852d824d7f6">

![image](https://github.com/user-attachments/assets/8d7012d7-ce4b-45e8-9a4c-4ce944f7571d)

**Comment by Jenefer-Monroe** [comment]
This typcially means that you either are using the Dynamics Admin role (not Power Platform Admin) or your Power Platform Admin role is not directly assigned.

**Comment by johnvittneyk** [comment]
As I already confirmed you, we are are Directly assigned to a Power Platform Admin Role

**Comment by Jenefer-Monroe** [comment]
Please remove the unmanaged layer and see if that works. 

If not then you've hit a product issue if that call does not work while running the flow as a PPAdmin that is directly and permanently assigned.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by bnerdco** [comment]
@johnvittneyk did you ever get to the bottom of this?

I have a similar situation, getting the same error, but only after I removed the Global Admin role from the account used to run the flows. The account has Power Platform Admin role and some other roles permanently:
![Image](https://github.com/user-attachments/assets/5e357c4c-93e9-41ed-bf4c-f46cc7f64ccd)

Check CoE environment > Settings > Users I can see in user properties that this account has System Administrator role:

![Image](https://github.com/user-attachments/assets/1300f67a-d670-4e5c-a1f0-06b6f0fb3c68)

However, it fails to get into Team environments when running HELPER - Driver Escalation Check:

![Image](https://github.com/user-attachments/assets/54bfd93f-2cff-4255-afef-80122bd738d4)

Also, when I go PPS and go into one of the Team Environments > Membership, I get the following error:
`Loading system admins failed, please retry Hide technical details

Error code: Unknown. { "error": { "code": "0x80040225", "message": "The specified user(Id = {0}) is disabled. Consider enabling this user. Additional Details: {1}" } } - [ Timestamp : 9:52 am, 11/12/2024, Session ID: 4f502fd1-a0d8-11ef-bcff-097b0eb964f5 ]`

.. or if I click on Settings I get

![Image](https://github.com/user-attachments/assets/8289714c-be4d-4a66-a762-02aa3fc6ce00)


It's the same for all Teams that this account is not a member of. None of these errors come up if I enable Global Admin role for this account.

Any help would be greatly appreciated.

**Comment by johnvittneyk** [comment]
@bnerdco - Hey, sorry for the delayed response, I was out past couple of weeks.
Unfortunately, I couldn't resolve the issue. I get the same error message every day.

**Comment by bnerdco** [comment]
@johnvittneyk - thanks for the reply. I got mine sorted with @Jenefer-Monroe 's help. See here: https://github.com/microsoft/coe-starter-kit/issues/9245
