### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance App Email always englisch

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#9042]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

the admin|compliance details request email (apps) always sends out the default email and don't take the language from the User
left current & right a suggestion for the fix
![image](https://github.com/user-attachments/assets/5cff827d-bc93-4b86-a7dd-0bf308ee966b)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

sep 2024

### What app or flow are you having the issue with?

admin|compliance details request email (apps)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Thanks for posting! I looked through and it appears that this was the only one of these that had the bug (ex Admin | Compliance Details Request eMail (Chatbots) did not have it) 

I've local fixed this for an upcoming release.
