### ISSUE TITLE
[CoE Starter Kit - Feature]: Rename Abandoned Flow view to be Orphaned Flow for consistency 

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#9044]
### Is your feature request related to a problem? Please describe.

The model drive app Power Platform Admin view contains a view for Orphaned Power Apps, but the same view for flows is called Abandoned Flows. This should be updated to be called Orphaned Flows for consistent naming convention throughout the product. Additionally, it should default to Flow Deleted = No for this view on orphaned flows. 

### Describe the solution you'd like

Rename flows view from "Abandoned Flows" to "Orphaned Flows". Filter out deleted flows by default on this view. 

### Describe alternatives you've considered

I understand I can make a custom view, but these out of box views should be consistent across the product.

### Additional context?

Adding issue as suggested improvement for product. I do not need support on this. If this is not something the CoE team is willing to do, just close the issue.

**Comment by Jenefer-Monroe** [comment]
Hello we have orphaned view for flows as well and as you suggest it does filter out deleted flows. 
![image](https://github.com/user-attachments/assets/596226cb-fe8b-41c5-b263-87f39612e592)
![image](https://github.com/user-attachments/assets/c8e3bec1-3e28-4e5e-9ea5-e2878573bc7e)

I know we did this somewhat recently so you may just need to upgrade to see it. 
Thanks for posting.

**Comment by Jenefer-Monroe** [comment]
We have done that for the big update coming ~Nov. 
![image](https://github.com/user-attachments/assets/05da4d9a-a1da-42f9-847e-7c2533467550)

**Comment by pnoot7** [comment]
Thanks! Can be marked complete from my end, but not sure if you are using it for tracking.
