### ISSUE TITLE
[CoE Starter Kit - QUESTION] Definition of orphaned apps and flows? What if co-owned by SharePoint list?

### ISSUE THREAD

**Issue by HenningStrand** [microsoft/coe-starter-kit#9050]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Do you have somewhere a current definition of what is an orphaned app or flow, and how sharing a flow with e.g. a SharePoint list as owner appears in the CoE? 

It looks like the focus is on the original maker and/or current main owner of the app or flow, but what about co-owners? We have flows showing up as orphaned that are shared with multiple co-owners (users or groups) or shared with a SharePoint list or library. 

For cleanup activities I am now only using the orphaned status as a starting point for e.g. deleting obsolete flows, but I don't want to delete flows that have active co-owners (users or groups) or even have a SharePoint list as owner (This I do not think is identifiable through the CoE reports..). 

Hence, I start with the orphaned status, then run these through other checks to identify if the flows are shared with alternate co-owners of all types. The image shows an example of three types of co-owners found, but there are other types also (e.g. for MS project flows, I think).
![image](https://github.com/user-attachments/assets/e6c23693-89b0-412a-b98f-4d6e8c846fcd)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Aug 24

### What app or flow are you having the issue with?

Admin view app

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
We do not consider co-owners for determining if a object is an orphaned. 
And we do not consider SharePoint ownership at all yet. Someone just posted that for us today actually and its now on the backlog: https://github.com/microsoft/coe-starter-kit/issues/9045

The person currently listed as the owner of the object is how we determine if its orphaned.
As you say we do store the number of co-owners though so you can use that:
![image](https://github.com/user-attachments/assets/3caaba16-e736-4b98-89b3-e24108276618)

**Comment by HenningStrand** [comment]
OK. As expected. I take it you are aware that Microsoft has a different definition of orphaned. That can cause some confusion when searching for documentation. https://learn.microsoft.com/en-us/troubleshoot/power-platform/power-automate/flow-management/manage-orphan-flow-when-owner-leaves-org#what-are-orphaned-flows

**Comment by Jenefer-Monroe** [comment]
Yes understood, thanks for sharing. Ours was written several years ago before you could even get the flows co-owners programmatically. 
The starter kit is intended to feed the product group with design suggestions and fill the gap while they do the work to support natively. So I do agree theirs is better. But with just me supporting the kit we just dont hvae the time to go back and fix this. It is on the backlog but doubtful we will get to it soon.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
