### ISSUE TITLE
Hello, unfortunately you are hitting product issues and not issues with the kit. I can share what we've seen other people hit though, hopefully it helps

### ISSUE THREAD

**Issue by patchivs** [microsoft/coe-starter-kit#9053]
Hello, unfortunately you are hitting product issues and not issues with the kit. I can share what we've seen other people hit though, hopefully it helps

## Key Vault:
We've had people struggle to integrate with Azure Secrets in the past. What we have found is that it typically comes down to these two product integration issues between Power Platform and Azure Key Vault:
1. Validate that the azure key vault permissions are correct. User needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)
To check your permission, go to the keyvaule, and select Access control (IAM) View my access
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/16bdc166-0fab-47c2-bfae-7ffd00699d04)
2. Validate that you do not have IP restrictions enabled, or if you do that you have Microsoft's internal outbound IP addresses to the firewall.

_Originally posted by @Jenefer-Monroe in https://github.com/microsoft/coe-starter-kit/issues/8990#issuecomment-2359570878_

**Comment by patchivs** [comment]
Inspite of creating the same azure roles. I am still getting same error
![image](https://github.com/user-attachments/assets/b3bfde79-c504-488f-b28b-252765fa7d21)

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately that is product UX you are looking at there, so the issue you are facing is a product issue and not an issue with the kit. 
It could be that you have IP restrictions per 
2. Validate that you do not have IP restrictions enabled, or if you do that you have Microsoft's internal outbound IP addresses to the firewall.


You may have to contact product support unfortunately.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
