### ISSUE TITLE
[CoE Starter Kit - BUG] PBI Reports - Load was cancelled by an error in loading a previous table

### ISSUE THREAD

**Issue by DS2019** [microsoft/coe-starter-kit#9060]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I'm afraid I let the CoE Starter Kit go too long between upgrades - from March 2024-August 2024 and I'm now upgraded to the Sept 2024 version. 
When I go to load the PBI reports (CoE Dashboard and Governance) I get table loading errors:
CoE Dashboard:
AI Builder Models
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Apps
Load was cancelled by an error in loading a previous table.
Power Apps Launches
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Business Process Flows
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Connectors
Load was cancelled by an error in loading a previous table.
Environments
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Environment Capacity
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow Action Details
Load was cancelled by an error in loading a previous table.
Makers
Load was cancelled by an error in loading a previous table.
Power Pages
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Platform Users
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Power Platform User Role
Load was cancelled by an error in loading a previous table.
Power Virtual Agent bots
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Desktop Flow Sessions
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Solutions
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Desktop Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
NonProdWords
Load was cancelled by an error in loading a previous table.
App Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Key Measures
Load was cancelled by an error in loading a previous table.
Power Virtual Agent bots usage
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
AI Credits Usage
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

Governance Dashboard:
CoE Starter Kit Environment URL
Load was cancelled by an error in loading a previous table.
Environments
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Apps
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Makers
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Connectors
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
App Connection Reference
Load was cancelled by an error in loading a previous table.
Flow Connection Reference
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Audit Log
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
NonProdWords
Load was cancelled by an error in loading a previous table.
Connection Identity
OLE DB or ODBC error: Exception of type 'Microsoft.Mashup.Engine.Interface.ResourceAccessForbiddenException' was thrown..
Environment Capacity
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Environment Request
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flow Action Details
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

-the data I see in the Power Platform Dashboard in the Power Platform Admin view looks correct
- the PBI reports says there are pending changes in your queries that haven't been applied and that some of the tables have incomplete or no data
-When I look at environments in the Power Platform Admin View, they all have apps and flows associated with them
-When I look at Transform data > Edit parameters in the PBI reports, the CoE Starter Kit environment URL is correct

### Expected Behavior

Before when I opened the CoE Dashboard and Governance Dashboards, there was data in each of the tabs. Now I get "Couldn't load the data for this visual, for example, in the governance dashboard it says this:
![image](https://github.com/user-attachments/assets/de316a06-8030-4c4d-8aae-e2adb8e32d3f)

![image](https://github.com/user-attachments/assets/bf7da2c1-6e4b-4e78-a2b4-f0cafa9e6df8)
![image](https://github.com/user-attachments/assets/96020317-e2a1-4c49-8753-799cb0ed599b)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Power BI CoE Dashboard and Governance reports

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1) in our CoE environment
2) with 4.43 Core Components
3) and the PBI reports PowerPlatformGovernance_CoEDashboard_September2024 and Production_CoEDashboard_September2024
4) the PBI reports throw loading errors and do not have data in them
5) However, I can see the data in the Power Platform Admin View

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by DS2019** [comment]
you bet, thank you, here you are: 
![image](https://github.com/user-attachments/assets/b313054c-124e-46a8-9baf-169809c498c1)

**Comment by DS2019** [comment]
With expanded columns: 
![image](https://github.com/user-attachments/assets/92879f86-8f5a-4245-8e7f-67cfef977ed3)

**Comment by Jenefer-Monroe** [comment]
ok that all looks good. 
Question: did you run the setup wizard after you did the install?

**Comment by DS2019** [comment]
I did

**Comment by DS2019** [comment]
Set up Flows have green checks
![image](https://github.com/user-attachments/assets/7f484511-363f-48d0-90c4-72933ca1ce65)

**Comment by DS2019** [comment]
Inventory Flows turned on
![image](https://github.com/user-attachments/assets/428b3d06-eeb1-4331-b106-58642e134d3d)

**Comment by Jenefer-Monroe** [comment]
OK let's start with the CoE Dashboard. 

Lets try to fix Power Platform Users first. 
Run this flow: **_CLEANUP - Admin | Sync Template v3 (Orphaned Users)_**

And then load the pbit file again. 
Be sure to enter the url parameter in this format with prefix and ending slash: https://mycoe.crm.dynamics.com/

**Comment by DS2019** [comment]
Thanks so much - I just ran  CLEANUP - Admin | Sync Template v3 (Orphaned Users) and it completed successfully. I then loaded the CoE Dashboard, and made sure that the url was in that parameter and with the ending slash. This is what errors I receive:
 AI Builder Models
Load was cancelled by an error in loading a previous table.
Power Apps
Load was cancelled by an error in loading a previous table.
App Connection Reference
Load was cancelled by an error in loading a previous table.
Power Apps Launches
Load was cancelled by an error in loading a previous table.
Business Process Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Connectors
Load was cancelled by an error in loading a previous table.
Environments
Load was cancelled by an error in loading a previous table.
Environment Capacity
OLE DB or ODBC error: Exception of type 'Microsoft.Mashup.Engine.Interface.ResourceAccessForbiddenException' was thrown..
Flows
Load was cancelled by an error in loading a previous table.
Flow Connection Reference
Load was cancelled by an error in loading a previous table.
Flow Action Details
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Makers
Load was cancelled by an error in loading a previous table.
Power Pages
Load was cancelled by an error in loading a previous table.
Power Platform Users
Load was cancelled by an error in loading a previous table.
Power Platform User Role
Load was cancelled by an error in loading a previous table.
Power Virtual Agent bots
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Desktop Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Desktop Flow Sessions
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Solutions
Load was cancelled by an error in loading a previous table.
NonProdWords
Load was cancelled by an error in loading a previous table.
Key Measures
Load was cancelled by an error in loading a previous table.
Power Virtual Agent bots usage
Load was cancelled by an error in loading a previous table.
AI Credits Usage
Load was cancelled by an error in loading a previous table.
Query parameters
CoE Starter Kit Environment URL
Load was cancelled by an error in loading a previous table.
Tenant Type
Load was cancelled by an error in loading a previous table.
I really appreciate the help, thank you.

**Comment by DS2019** [comment]
This is what I see when I go to a tab
![image](https://github.com/user-attachments/assets/145f3eee-15c7-4fd3-bc2a-edbdeb187860)

**Comment by DS2019** [comment]
Before it errors out, I do see this:
![image](https://github.com/user-attachments/assets/bf828e2f-32eb-4087-8347-1141b69b0ed7)

**Comment by DS2019** [comment]
This is what I see in the CoE Dashboard just before it errors out: 
![image](https://github.com/user-attachments/assets/6656c8b1-a4ec-426a-9cac-79ce1f4a159c)

**Comment by Jenefer-Monroe** [comment]
Are you logged in to PBI as the user that setup the kit?

**Comment by DS2019** [comment]
Hi,
I usually access it with my account that has Power Platform Admin rights, but I closed PBI, logged into PBI as the service account that set up the kit, and I'm still getting the same errors. 
Thanks so much,

**Comment by Jenefer-Monroe** [comment]
The error indicates there is something wrong with permissions. Sometimes if you log in to PBI with various users things get cached. 
While your error in particular doesnt look like one I've seen the internet confirms that this is indeed a permissions issue: ResourceAccessForbiddenException

Please look through our [troubleshooting](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#troubleshooting) for pbi. In particular the [sign in issues](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#sign-in-issues)

**Comment by DS2019** [comment]
Thank you, Jenefer. I've cleared the permissions and in opening the CoE Dashboard with the service account for the CoE environment, the permissions error is not there. The "we cannot convert the value null to type Text" is back though:
AI Builder Models
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Power Apps
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Apps Launches
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Business Process Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Connectors
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Environments
Load was cancelled by an error in loading a previous table.
Environment Capacity
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Flows
Load was cancelled by an error in loading a previous table.
Flow Action Details
Load was cancelled by an error in loading a previous table.
Makers
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Power Pages
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Platform Users
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Platform User Role
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Power Virtual Agent bots
Load was cancelled by an error in loading a previous table.
Desktop Flow Sessions
Load was cancelled by an error in loading a previous table.
Solutions
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Desktop Flows
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
NonProdWords
Load was cancelled by an error in loading a previous table.
App Connection Reference
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Flow Connection Reference
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..
Key Measures
Load was cancelled by an error in loading a previous table.
Power Virtual Agent bots usage
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
AI Credits Usage
OLE DB or ODBC error: [Expression.Error] We cannot convert the value null to type Text..

**Comment by DS2019** [comment]
Clearing the cache and permissions in Power Bi, completely exiting out and logging in as the service account has done the trick! Thank you so much Jenefer - I'd not seen errors like this before and really appreciate your pointing the way. Very grateful!

**Comment by DS2019** [comment]
Clearing the cache and permissions in Power Bi, completely exiting out and logging in as the service account has done the trick! Thank you so much Jenefer - I'd not seen errors like this before and really appreciate your pointing the way. Very grateful!
