### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Security Role Permission Base

### ISSUE THREAD

**Issue by Alyson95170** [microsoft/coe-starter-kit#9064]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Hi, I am noticing the Database use for the CoE environment is constantly increasing.  Recently the admin_Environment Security Role Permission Base has significantly increased 
![image](https://github.com/user-attachments/assets/6b2386b3-4e1d-41bf-bb69-bcf884463dc3)

As the Data export is still within experimental preview I am not looking to implement this, is there anything I can do to reduce the storage?  What would cause this table to increase?
Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Gather Tenant SRs

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Alyson95170** [comment]
Perfect thanks Jenefer I will give this a go

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
