### ISSUE TITLE
[CoE Starter Kit - BUG] Error message received when attempting to set quarantine state for an app

### ISSUE THREAD

**Issue by derekmorgan-oly** [microsoft/coe-starter-kit#9065]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Hello!

I am working with a team who leverages the Power Platform CoE kit and they receive an error message when attempting to set the quarantine state for an app: "Only admins can set app quarantine state". The strange behavior is that they have the same security roles assigned as myself (i.e., Power Platform Admins SR & System administrator) and I am able to set the app quarantine state on the same app they were attempting to set.

Any help or guidance on where to start would be highly appreciated! 😊
![372465306-0d92bd4a-e09a-4315-83d7-55b0a9e676cc](https://github.com/user-attachments/assets/9e6474e4-972d-4b63-8bea-ee5820544361)

### Expected Behavior

1. Open browser and go to "Power Platform Admin View" app
2. Click on "PowerApps Apps"
3. Search and click on the name of the app.
4. Click on "Quarantine App"
5. Click on "Quarantine app"
![image](https://github.com/user-attachments/assets/bf9e3a22-adec-44e1-9a36-c2f73a8f0598)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.25

### What app or flow are you having the issue with?

Admin | Set app quarantine status

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open browser and go to "Power Platform Admin View" app
2. Click on "PowerApps Apps"
3. Search and click on the name of the app.
4. Click on "Quarantine App"
5. Click on "Quarantine app"

**Comment by Jenefer-Monroe** [comment]
All we are doing in this case is calling a product action to set the quarantine so that error message is from the product itself not from us. 
![image](https://github.com/user-attachments/assets/01cefd60-caad-4543-b130-a4a34b430dec)

Perhaps they do not have PPAdmin role permanently assigned and so did not have it while they were attempting this step?

**Comment by derekmorgan-oly** [comment]
Thanks for the clarification! I checked and confirmed the internal team did not have a security role assigned in the Power Platform environment where the app resides. I adjusted their security roles and awaiting confirmation.

In the meantime, what confused me was clicking on "Check Access" for the app and it stated they had the "System administrator" security role assigned. Checking now, I see the "Business unit" value is not equivalent to the Power Platform environment where the app resides. Is my assumption correct or am I looking at this incorrectly?

**Comment by Jenefer-Monroe** [comment]
If you mean the PP Admin View app, check access will show you if they can view the data in the app. So access here means they can view the data, see the environments, apps, etc... 

There are some behaviors in the app that are only available to the PP Admin role. For example quarantining and app or changing its permissions. 

Hope that makes sense.

**Comment by derekmorgan-oly** [comment]
internal team just confirmed they're able to quarantine the app, after adjusting their security roles in the Power Platform environment where the app resides.

thanks again for your help and apologies for reporting this as a bug! 😆

**Comment by Jenefer-Monroe** [comment]
no problem at all. I'm happy to help :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
