### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Admin Command Center View Flow - Error 429 Rate Limit Exceeded

### ISSUE THREAD

**Issue by beowulf005** [microsoft/coe-starter-kit#9066]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When in the CoE Admin Command Center and attempting to view CoE Flows, none of the flows will return. 

Dev Tools shows a 404 not found error and then a number of 429 Rate limit exceeded errors.  

![image](https://github.com/user-attachments/assets/c4a56d22-8f95-4b5b-bf46-0302f9833f49)

### Expected Behavior

Flows get listed on the page. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.42

### What app or flow are you having the issue with?

CoE Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Launch CoE Admin Command Center
Click on CoE flow under Command Center heading

### Anything else?

Tenant type GCC H

**Comment by Jenefer-Monroe** [comment]
I dont have a GCCH tenant to test on, can you please try a few things for me as a result? 
Do other pages in the app load? In particular, do these three pages load? 
![image](https://github.com/user-attachments/assets/825e5d52-2a19-4227-bc65-47910b60abce)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by beowulf005** [comment]
Sorry was out of the country for a bit. 
Not getting any errors on the other pages. Just get the 429 on the flow page. I thought the 429 was that a throttling limit was hit. 
But not sure why that is getting triggered. Unless it is related to the 400 error at the start of the list.
