### ISSUE TITLE
CoE issue - pagination error

### ISSUE THREAD

**Issue by henkdafreak** [microsoft/coe-starter-kit#9068]
Hello, you are probably using a trial account for Power Apps. That's what it typically is. Or perhaps a delay if you just turned on the license. 
This is product behavior though, and not something we can impact. So if you believe you have the correct license but aren't afforded the correct pagination, then you will need to contact product support as there isn't anything we can do to resolve that.

_Originally posted by @Jenefer-Monroe in https://github.com/microsoft/coe-starter-kit/issues/5029#issuecomment-1477116812_

**Comment by henkdafreak** [comment]
Hi @Jenefer-Monroe 
Does the trial versions override the per user licences I have applied to my profiles? FOr some reason I'm getting the pagination errors even though I have the per user and premium linceses for both PowerApps and PowerAutomate

**Comment by Jenefer-Monroe** [comment]
Hello. No that should not happen. Perhaps the flow is running in the context of a different user?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
