### ISSUE TITLE
CoE Setup and Upgrade Wizard Error

### ISSUE THREAD

**Issue by phil0074** [microsoft/coe-starter-kit#9069]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Initial Setup not loading

Error Code: AppForbidden

### Expected Behavior

Loading of wizard.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Click Run next to app in solution with account used to import solution.

### Anything else?

I have validated DLP to allow all documented Connectors for given environment.

**Comment by Jenefer-Monroe** [comment]
There are two connectors missing from the documented list for DLP. We have someone set to patch the documentation this week. 
They are:
[Power Platform for Admins V2 (Preview)](https://learn.microsoft.com/connectors/powerplatformadminv2/)
[Microsoft Dataverse (legacy)](https://learn.microsoft.com/connectors/commondataservice/)

**Comment by phil0074** [comment]
Adding Dataverse (legacy) connector to DLP. I was aware of the other connector. Will wait about 20 minutes for DLP to process and try again.

**Comment by phil0074** [comment]
Receiving a new error.

Error Code: 2147873366
Session Id: 6a2e4e0f-af5d-47b0-9e22-45c03229de27
Activity Id: ef6bd780-5fdb-4a8f-a009-18ba4b66112a
Timestamp: Wed Oct 02 2024 11:22:06 GMT-0700 (Pacific Daylight Time)
The script https://apps.powerapps.com/apphost/clientsdkproxy?version=1 didn't load correctly.
UciError: The script https://apps.powerapps.com/apphost/clientsdkproxy?version=1 didn't load correctly. at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.9bfa873a8412319c44f38e34756503b6.js:33:977541) at o (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.9bfa873a8412319c44f38e34756503b6.js:28:275608)

**Comment by phil0074** [comment]
Now back to original error.

Error

Something has gone wrong. Check technical details for more details.

Error Code: AppForbidden
Session Id: 53385db5-24d3-4bbd-8725-3965346927a3
Activity Id: aed6ad6d-f824-4599-81ea-ef0dd0fcebc4
Timestamp: Wed Oct 02 2024 11:24:36 GMT-0700 (Pacific Daylight Time)
It looks like this app isn't compliant with the latest data loss prevention policies. Your organization’s governance reference material:  Your organization’s governance contact: _scrubbedSensitiveData_
UciError: It looks like this app isn't compliant with the latest data loss prevention policies. Your organization’s governance reference material:  Your organization’s governance contact: _scrubbedSensitiveData_ at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.9bfa873a8412319c44f38e34756503b6.js:33:977541) at https://content.powerapps.com/resource/uci-infra-bus/scripts/custompage.9e28f0856a41561935696f93e07bc694.js:4:23200

**Comment by Jenefer-Monroe** [comment]
I've seen this take up to 24 hours to sync the DLP policy unfortunately.

**Comment by phil0074** [comment]
I will check again tomorrow.

**Comment by phil0074** [comment]
The Dataverse (legacy) connector seems to have resolved the issue.

**Comment by Jenefer-Monroe** [comment]
Wonderful news. I'll go ahead and close then but please do feel free to reach out if you need anything else in the future.
