### ISSUE TITLE
I need help to configure the COE report from scratch so that I can monitor the environment of PowerApps and power automate

### ISSUE THREAD

**Issue by ISPlatformCloud** [microsoft/coe-starter-kit#9071]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

I need help to configure the COE report from scratch so that I can monitor the environment of PowerApps and power automate 

### What solution are you experiencing the issue with?

Admin Task Planner

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Setting up the kit has gotten a lot easier over the years as we have a setup wizard now. 

Please read [Before setting up the CoE Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/setup) and do any steps outlined there. 
Note if you setup the DLP there are two missing from the documentation today They are:
[Power Platform for Admins V2 (Preview)](https://learn.microsoft.com/connectors/powerplatformadminv2/)
[Microsoft Dataverse (legacy)](https://learn.microsoft.com/connectors/commondataservice/)

Then [set up inventory components](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components) and let us know if you have any specific questions.

**Comment by ISPlatformCloud** [comment]
We have existing report in Power BI but not sure how we can refresh it to get the latest data. Can you help with that?

**Comment by Jenefer-Monroe** [comment]
Hello. I'm afraid I cant assist unless you have more specific questions. Do you know who setup the kit for you? If so please reach out to them.

**Comment by ISPlatformCloud** [comment]
Hi, is there any technical support on the call who can help to set up the kit from scratch because our environment a bit complicated.

**Comment by Jenefer-Monroe** [comment]
Sorry we are a very small team and so are not staffed to do calls with users. There are partners that focus on the kit though who you can find on [AppSource](https://appsource.microsoft.com/en/marketplace/consulting-services?product=powerapps&src=pa-m&search=coe&page=1). 

Or you can follow the steps above and let me know when you have specific questions.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
