### ISSUE TITLE
[CoE Starter Kit - BUG] Inactivity Notifications triggered even after Resave and republish the app/flow

### ISSUE THREAD

**Issue by Chitusnair** [microsoft/coe-starter-kit#9072]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Dear Team,

I have users complaining that even when they resave the flow the inactivity emails are still being sent. The inactivity notification past time is 6 months. Where can I check if the resave or republish is updated properly ?

Thanks.

### Expected Behavior

After the Maker do a resave of flows or republish of Apps, they should not get any more requests for the next 6 months.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.24

### What app or flow are you having the issue with?

Inactivity Notifications start approvals

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
You can go see in the inventory if the flow is updated to reflect the new saved date (Flow Modified On)
![image](https://github.com/user-attachments/assets/f7e4e6e2-44f5-4f87-8950-d3726dcf7a24)

Generally speaking make sure your inventory is on and funning successfully:
Please go to the Admin Command Center > CoE Flows > Inventory. Validate that all flows are turned on and that there are no unmanaged layers as shown here. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/598b5024-2e1a-4390-a6b2-49644368c246)
Then see if there are any sync flow errors to investigate. 
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d43b50b3-84d1-4894-a9a3-04d5d95fe8dc)

**Comment by Chitusnair** [comment]
Hi Jenefer,

Thank you. So far the modified date is working. There were unmanaged layers
in one of the flows, but it was related to compliance and not to
inactivity. No sync flow errors.

I have asked the user to provide a particular flow/app name to troubleshoot.

Thanks,
Chitra Nair

**Comment by Jenefer-Monroe** [comment]
Thank you, yes once you have a specific example please can go see if they are marked with correct modified / published dates in the inventory.

**Comment by Chitusnair** [comment]
Thank you. You may close this for now. Once I test with an example, if the
issue still exists, I will reopen the ticket for your assistance.

**Comment by Jenefer-Monroe** [comment]
thank you!
