### ISSUE TITLE
[CoE Starter Kit - BUG] - Admin | Sync Template v3 (check deleted) flow run issue.

### ISSUE THREAD

**Issue by AkhilReddy21** [microsoft/coe-starter-kit#9073]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Recently I had shifted our prod environment to a newer coe environment(from 3.49 to 4.15) and imported/updated all the apps and flows coe records from old to new using Dataflows. And the new environment worked well for the initial 14 days. then the sync template check deleted coe flow ran, and unfortunately I missed to change the environment variable of "Also delete from Coe" to No. Which resulted in deleting the records which has been deleted from the tenant. But it had also deleted 270+ flow records and 80+ app records which are already available in the tenant. So I just needed to confirm whether 1.the records got deleted due to invalid connection references in newer environmnet after the import . 2. Or due to bulk operation?

### Expected Behavior

The Sync Template Check Deleted flow should delete only the deleted records of the tenant from the CoE.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.15

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Migrate the data of app and flows records from one environmnet (CoE 3.49) to other environment (CoE 4.15) using Dataflow.
2. Turn on the CoE flows and monitor the Check Deleted flow functionality.

**Comment by Jenefer-Monroe** [comment]
Hello you upgraded to a build that is still about a year old (Sept 2023) so I really am afraid that I cannot comment or conjecture much of what could have happened as I dont remember the specifics of the kit at that time. 

I suggest you upgrade to current builds, the data should flow back in and then we can see what state you are on. 

Sorry I can't be of more assistance.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
