### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE:  CoE Setup and Upgrade Wizard App Error Code: AppMetadataParserFailed

### ISSUE THREAD

**Issue by jjbadura** [microsoft/coe-starter-kit#9077]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I was performing my monthly update of CoE StarterKit, specifically upgrading from  CoE StarterKit Core Components 4.37 to 4.43.  The import states that it was successfully imported. However, when opening the "Setup and Upgrade Wizard"  App, I am getting this error: 

Error Code: AppMetadataParserFailed
Timestamp: Thu Oct 03 2024 11:11:59 GMT-0400 (Eastern Daylight Time)
AppLogicalName admin_initialsetuppage_d45cf does not have an AppPackage
UciError: AppLogicalName admin_initialsetuppage_d45cf does not have an AppPackage at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.69b92dc58391939fa2f73c0e70e8cfa9.js:33:961647) at https://content.powerapps.com/resource/uci-infra-bus/scripts/custompage.c74d0b5c086ad270032b999bd951290c.js:4:23208

Any help would be appreciated.  I have opened a case with MS Support so will update this forum as I find out further details.

### Expected Behavior

I have been performing the upgrade monthly without any issues. This is the first time in a year and a half I have run into an issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, another user hit this as well. It was some issue in the upgrade process. Please see https://github.com/microsoft/coe-starter-kit/issues/9056
They fixed it by doing a classic overwrite re-install. Please see https://github.com/microsoft/coe-starter-kit/issues/9056#issuecomment-2386439537

**Comment by jjbadura** [comment]
Hi Jenefer, the fix you provided worked.  Thanks again for you assistance and have a great weekend!

**Comment by Jenefer-Monroe** [comment]
What great news, thanks for letting me know! I'll go ahead and close out but please return with new issues as needed.
