### ISSUE TITLE
[CoE Starter Kit - QUESTION] BYODL implementation of the COE Toolkit 

### ISSUE THREAD

**Issue by Chaitra1006** [microsoft/coe-starter-kit#9080]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

1. What is the road map to roll out BYODL Data Export integration of the tool kit as general available feature? If yes, please share the details.
2. Will the Storage Account be made available to use Private endpoint in future?
3. Can you please share the data flow diagram of the BYODL Data Export integration using the public endpoint Storage Account.
4. What is need to use public endpoint Storage Account in Data Export integration?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Data flows

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately these are questions for the product team and not the kit, and so they need to be addressed to the product team. We are just consumers of the Data Export features. 

What I can tell you, is that we are now working on what we think of as V2 of the Data Export feature and it does not rely on the datalake architecture. Rather it focuses on using Fabric as the Export endpoint for the inventory data from the product. 
We do not recommend that new users onboard to V1 (BYODL) at this time as a result as the kit will not be focused on consuming that going forward.

**Comment by Chaitra1006** [comment]
Appreciate your quick response. Can you share an estimated timeline when the V2 of the Data Export feature using Fabric as the Export endpoint for the inventory data is planned?

**Comment by Jenefer-Monroe** [comment]
My current understanding is that this will be in public preview in November timeframe and the first version of the starter kit which integrates it will be available for preview Dec release.

**Comment by Chaitra1006** [comment]
that is good news. Hope there will NOT be any restriction similar to public endpoint in the new feature.

**Comment by Jenefer-Monroe** [comment]
Once the product feature is in public preview you will be able to get answers like that from their documentation, and give them feedback as needed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
