### ISSUE TITLE
Manage Permissions App is not displaying all Flows/Apps

### ISSUE THREAD

**Issue by shanemeisnerdhg** [microsoft/coe-starter-kit#9083]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

When we open the Manage Permissions App and check Flows, we are not seeing all the Flows.

If I go to the Table I can see the flows for an owner there:
![image](https://github.com/user-attachments/assets/a0f203a7-36d2-4a0c-bbc5-a3ca5db68907)

From Manage Permissions App, I am only able to see one of the Owners flows:
![image](https://github.com/user-attachments/assets/bfa4fb50-c059-461f-9316-fc48fdb1c99b)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please share a screenshot of the app so I can understand what you are filtering on there.

**Comment by Jenefer-Monroe** [comment]
As I recall, we shipped a first version of this app where it was filtered by maker not owner. Can you please do the following: 

1. See if you have unmanaged layers on the page
![image](https://github.com/user-attachments/assets/77b52f7f-4137-4ffe-bcaf-9edd79dd5896)

2. Share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by shanemeisnerdhg** [comment]
Thank you Jennifer.. 
Here is the Dependencies view of that page:
![image](https://github.com/user-attachments/assets/eff2262f-0930-44c4-8c04-9b0bb97a0ad4)

And the Solution Versions:
![image](https://github.com/user-attachments/assets/f7a7dc2d-3e69-4a54-a9ae-1d8e4a638282)

**Comment by Jenefer-Monroe** [comment]
oh sorry I highlighted the wrong thing, I meant to see if there are unmanaged layers on the page
![image](https://github.com/user-attachments/assets/90b56587-9032-4b40-b27b-f672ec132c11)

**Comment by shanemeisnerdhg** [comment]
No unmanaged layers:
![image](https://github.com/user-attachments/assets/740ee28b-3efb-4ea8-b155-3480ae2b8a45)

**Comment by shanemeisnerdhg** [comment]
Unfortunately the objects available in The Manage Permissions app are still not syncing correctly with what is in the table itself.

Any thoughts on how to get the two in sync?

**Comment by Jenefer-Monroe** [comment]
Here are the filters on that data. 
- Derived Owner = selected person
- Flow Deleted = No
- Flow is Published = No
- Search Flows string in Display name or Owner display name

So please add the following columns to your table view and see if the other flows are deleted/published.
![image](https://github.com/user-attachments/assets/bf1ce726-723e-4ae4-88fe-d849f3c405fc)

**Comment by shanemeisnerdhg** [comment]
That was it.. Thank you!!

Once I added the "Flow Deleted" column I can see that he has now deleted all the other flows, thus the reason I can no longer Manage them.
![image](https://github.com/user-attachments/assets/2a36a03d-f95f-4702-a6ad-9afb16b4aba8)

Kind of interesting it says "Started" for some Deleted Flows, but I am good now.
Thanks again,
Shane Meisner

**Comment by Jenefer-Monroe** [comment]
You are quite welcome. Yes we do not update the state field when we mark the object deleted. 
I'll go ahead and close then but please feel free to return with new issues as you have them.
