### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Dataflows are not getting refreshed automatically after the Sep 2024 Upgrade for Test Governance Env. #8987 - Still issue is not resolved

### ISSUE THREAD

**Issue by Kumarez007** [microsoft/coe-starter-kit#9087]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

 Dataflows are not getting refreshed automatically after the Sep 2024 Upgrade for Test Governance Env. #8987 - Still issue is not resolved Even after adding the values manually.

If I check it after sometime, the values are not present in those columns. Please help to resolve this issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Dataflows

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I'll go ahead and re-open your other issue so we have all the history, and close this one. Thanks
