### ISSUE TITLE
[CoE Starter Kit - BUG] Inactivity flows triggering even when the resource has already been deleted.

### ISSUE THREAD

**Issue by tomtech1** [microsoft/coe-starter-kit#9088]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We've just had some reports of inactivity teams cards being sent to users who have already approved the request and the resource has already been deleted a month ago. Any idea how to troubleshoot this?

### Expected Behavior

I'd expect that once a resource has been through the process and is deleted, the user shouldn't be prompted again for that resource.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32

### What app or flow are you having the issue with?

Inactivity process

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. The starter kit does not send out teams cards for inactivity. It sends out approvals in mail. 

Can you please share a screenshot of the UX they are approving?

**Comment by tomtech1** [comment]
Hi, sorry I mean they approval they are getting in Teams not an adaptive card.



Tom Ryan

Corporate Applications Engineer  – AO Tech

[cid:6a1aab4d-a53b-424a-ab53-02e4ad86a053]

Visit ao.com<https://ao.com/>

AO, let’s go!



________________________________

**Comment by Jenefer-Monroe** [comment]
Got it. Please go make sure you have all the flows for the feature area turned on and if they are running and passing
![image](https://github.com/user-attachments/assets/debb9dde-93d1-461c-95d3-c18164f1c73a)

**Comment by tomtech1** [comment]
All turned on, all have passed except for the 'Email managers ignored' one.



Tom Ryan

Corporate Applications Engineer  – AO Tech

[cid:a55b744d-c37a-403d-901c-f877006859ba]

Visit ao.com<https://ao.com/>

AO, let’s go!



________________________________

**Comment by Jenefer-Monroe** [comment]
Is the object marked as deleted in the inventory? Can you find it in the PPAdmin View app? 
![image](https://github.com/user-attachments/assets/e80fcafe-d9c2-4324-a06e-4c2ad4a3c3c3)

**Comment by tomtech1** [comment]
Turns out it's not deleted, although the user has approved deletion 3 times. I can see this across a few different resources.

Is there a way to see things that have failed on the deletion step so I can clean up manually?

**Comment by Jenefer-Monroe** [comment]
We don't actually have UX to tell an admin the list of objects that fail to delete, but the Maker/Owner should get a warning that it could not be deleted in email as shown here
![image](https://github.com/user-attachments/assets/879adfb2-60b1-4556-8db2-90b781da9302)

Can you go to the most recent run of (Clean Up and Delete) 
See if it goes not the path here to early exit
![image](https://github.com/user-attachments/assets/f4301a79-c748-4228-9686-8949e4a29c4d)

**Comment by Jenefer-Monroe** [comment]
Yes that would be a good add and not too difficult. You could just put it here.
![Image](https://github.com/user-attachments/assets/6ee04f7e-6499-4687-8ceb-2d05b60dc07f)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
