### ISSUE TITLE
[CoE Starter Kit - BUG] your issue

### ISSUE THREAD

**Issue by highsmithjd** [microsoft/coe-starter-kit#909]
### Describe the issue

I'm trying to import the CoE solution (CenterofExcellenceCoreComponets) and getting the following error. I've tried multiple times and continue to get the same error:

Connector   import: FAILURE: The API call failed with http status code   'InternalServerError' and response content   '{"error":{"code":"InternalServerError","message":"Encountered   internal server error. The tracking Id is   '8c90c52e-99dc-4fa3-9e54-77be1f674e32'."}}'

Any help is much appreciated. The steps to setup the connectors went fine but the import always fails. I'm using a Global Admin account for all connectors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_2.2.20210707.3_managed

### What app or flow are you having the issue with?

CoE

**Comment by JeneferM-MSFT** [comment]
Is this an upgrade or a clean install? 
If upgrade, please try to **_update_** instead of **_upgrade_** (note you typically want to do **_upgrade_** but there was an issue with an old version that blocks this)

**Comment by highsmithjd** [comment]
I'm following the MS documentation. I created a new Production environment, with database. We set up the connectors without issue but the import fails repeatedly

**Comment by JeneferM-MSFT** [comment]
OK so a new clean install correct? No CoE on it in the past. 
Can you please state your tenant type? Ex: GCC, GCC High, Commercial, ...

**Comment by highsmithjd** [comment]
I followed this document, Option 1 https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components

This is our first CoE and we have an Azure Tenant with Azure AD Premium P2 license. We're not government or anything special

**Comment by highsmithjd** [comment]
We did skip step 10, "Update Environment Variables." The MS resource said we could update those at a later time, after the import.

**Comment by JeneferM-MSFT** [comment]
I'm afraid I've never seen a clean install fail. It sounds like it was an issue with the service. Have you tried again?

**Comment by highsmithjd** [comment]
I've tried 4-5 times and it fails every time. The MS resource said the same thing about never seeing a clean install fail but he didn't know what to do after that. So, that's why i'm here. Do i need to delete the CoE environment and start again from a clean environment?

**Comment by highsmithjd** [comment]
I can have a quick Teams screen share if you'd like to see the failure.

**Comment by JeneferM-MSFT** [comment]
I'm afraid I cannot do support calls with our GitHub customers. 
Yes please try with a fresh environment. And ensure you followed all the [pre-reqs](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites)

Including specifics about envt
![image](https://user-images.githubusercontent.com/62659043/127166298-c01c7011-3cd0-486f-a0d5-30f0cf111eaa.png)

**Comment by highsmithjd** [comment]
Is it safe to delete the CoE environment and database i have now? I guess the connections will go with it (which is fine)?

**Comment by JeneferM-MSFT** [comment]
From the CoE pov there is no need to keep it around. 
Regarding permissions. Please walk the [pre-reqs](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites)
documentation.

**Comment by highsmithjd** [comment]
Trying from a clean install. What do other companies normally use for the Approval Admin, Power Platform Maker Microsoft 365 group, and Community URL? Is the Community URL a Teams Channel?

**Comment by JeneferM-MSFT** [comment]
Please see our documentation on the environment variables in [Core Set Up](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#option-1-import-the-solution-into-a-production-environment) (below step 10)
![image](https://user-images.githubusercontent.com/62659043/127188824-549aca62-501b-419b-997b-a6846c2574d0.png)

**Comment by highsmithjd** [comment]
Looks like the new install worked! I didn't update the variables yet since i don't have a group created. I did see the documentation but was curious what others were doing with these variables.

**Comment by highsmithjd** [comment]
Thank you for all your help!

**Comment by JeneferM-MSFT** [comment]
wonderful!
