### ISSUE TITLE
Nurture APP MAker  Nurture Admin App and other app Does not open After  Sept Update 

### ISSUE THREAD

**Issue by kghimire76** [microsoft/coe-starter-kit#9091]
Hello, 
I updated my COE Sept Update. I update the 3 components 
CenterofExcellenceAuditComponents_3_25_managed.zip
CenterofExcellenceCoreComponents_4_43_managed.zip
CenterofExcellenceNurtureComponents_3_19_managed.zip
After this update All of my Apps stops working . Screen shots are attached
[github.docx](https://github.com/user-attachments/files/17298240/github.docx)

**Comment by Jenefer-Monroe** [comment]
Hello, other users hit this as well. It was some bug in the upgrade process. Please see https://github.com/microsoft/coe-starter-kit/issues/9056
They fixed it by doing a classic overwrite re-install. Please see https://github.com/microsoft/coe-starter-kit/issues/9056#issuecomment-2386439537

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
