### ISSUE TITLE
[CoE Starter Kit - BUG] Administration Planning dashboard not loading

### ISSUE THREAD

**Issue by kevinli629** [microsoft/coe-starter-kit#9093]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

When I tried to open the dashboard for the first time and entered the environment URL, I got this error.

pcat_admintasks
Microsoft SQL: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - The semaphore timeout period has expired.)

### What solution are you experiencing the issue with?

Admin Task Planner

### What solution version are you using?

1.3.20230724.1

### What app or flow are you having the issue with?

n/a

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Import 'Power Platform Administration Planning'
2. In Power BI Desktop, open the file Power Platform Administration Planning.pbit
3. Enter the URL of the environment

**Comment by Jenefer-Monroe** [comment]
Hello unfortunately this sounds like an issue with Power BI itself not our PBIT file 

Please make sure you've walked through all our [Set up instructions for the Microsoft Power Platform administration planning component](https://learn.microsoft.com/power-platform/guidance/coe/setup-admin-tasks-component)

That you have entered the URL parameter correctly as showin in [set up the Power BI dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-admin-tasks-component#set-up-the-power-bi-dashboard)
![image](https://github.com/user-attachments/assets/526971b9-034b-4284-8b3d-41bd40ddd516)

If that does not resolve, please view our [pbi troubleshooting suggestions](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#troubleshooting)
