### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE - CoE Command center apps are not working

### ISSUE THREAD

**Issue by tajuddin335** [microsoft/coe-starter-kit#9094]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have upgraded the CoE Core Components from 4.32 to 4.43 by importing the solution and using the upgrade wizard. Most of the applications from this solution work, however, all the Command applications e.g. CoE Admin Command Center etc. are not working throwing the following error. I have reimported the solution a couple of times, but I still have the same issue.

Error Code: 2147873362
Session Id: c6df65dc-bc9c-4a14-a19e-a20d3d8f2d19
Activity Id: cee32164-bed7-4f15-b3e6-976bd5cc25c8
Timestamp: Wed Oct 09 2024 09:32:46 GMT+0800 (Australian Western Standard Time)
Page does not exist in this app
UciError: Page does not exist in this app at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.fd3fb478dbf7cd68db6b78dbb1a203bb.js:33:961647) at Object.execute (https://content.powerapps.com/resource/uci-infra-bus/scripts/custompage.3db6d13f2dd48983e7cec0e34c1ca719.js:4:25499) at https://content.powerapps.com/resource/uci-infra-bus/scripts/app.fd3fb478dbf7cd68db6b78dbb1a203bb.js:14:647939 at new Promise (<anonymous>) at w._executeAsyncAction (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.fd3fb478dbf7cd68db6b78dbb1a203bb.js:14:647640) at w._executeAsync (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.fd3fb478dbf7cd68db6b78dbb1a203bb.js:14:647484) at w.executeAction (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.fd3fb478dbf7cd68db6b78dbb1a203bb.js:14:646749) at t.dispatch (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.fd3fb478dbf7cd68db6b78dbb1a203bb.js:14:652110) at Object.dispatch (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.fd3fb478dbf7cd68db6b78dbb1a203bb.js:14:926585) at Object.dispatch (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.fd3fb478dbf7cd68db6b78dbb1a203bb.js:14:651599)

### Expected Behavior

The application should open as usual after the upgrade.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Center of Excellence - Core Components

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Downloaded the CoE toolkit zip file from https://github.com/microsoft/coe-starter-kit
2. Unzipped and imported the CenterofExcellenceCoreComponents solution
3. Followed the upgrade wizard steps
4. Import was successful without any error
5. Tried to open the apps from this solution and got the above-mentioned error
6. Tried switching the UI look between legacy and new with no success
7. Tried a different browser but still the same issue
8. Tried reimport several times with no luck

### Anything else?

![image](https://github.com/user-attachments/assets/81e7af2d-386a-45bb-abf8-909decc8de75)

**Comment by Jenefer-Monroe** [comment]
Hello, other users hit this something similiar. It was some bug in the upgrade process. Please see https://github.com/microsoft/coe-starter-kit/issues/9056

They fixed it by doing a classic overwrite re-install. It sounds like you tried to install via classic but did you try the overwrite? Please see https://github.com/microsoft/coe-starter-kit/issues/9056#issuecomment-2386439537

**Comment by tajuddin335** [comment]
Importing in classic view and overwriting works for me. Thanks for your help.
