### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to mark orphaned flows as no longer orphaned?

### ISSUE THREAD

**Issue by ragnolothbrok** [microsoft/coe-starter-kit#9100]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I found a couple of other questions/issues and saw there currently is no way to reassign Orphaned flows to new owners, you can only add co-owners.

How would you then mark those same flows not being orphaned through the Power Platform Admin View app? 

Or is there another process for this?

We have recently added the COE to our environment, and we are very new to it.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello if you view the manage permissions app you will see a way to change owner for flows. 
![Image](https://github.com/user-attachments/assets/fb0b6181-e3cb-426d-ae5f-872b5693410d)

**Comment by ragnolothbrok** [comment]
Hey Jennifer, which app is it that you are using? Also, which Solution is it apart of?

I was trying to do this in the Power Platform Admin View app.

**Comment by ragnolothbrok** [comment]
I was actually able to find this. Thank you so much for clarifying!

**Comment by Jenefer-Monroe** [comment]
Happy to help!
