### ISSUE TITLE
[CoE Starter Kit - BUG] missing expression in a condition of Compliance Details Request eMail (Apps) flow cause HELPER - send mail to fail

### ISSUE THREAD

**Issue by kumashiro17** [microsoft/coe-starter-kit#9101]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

in the flow **Admin | Compliance Details Request eMail (Apps)**, at the step **Check if Maker is orphaned**, the missing expression 

`body('Check_Maker_status')?['userisserviceprinciple'] is equal to true`

is causing the condition not to verify if the maker is a **user service principle** and then, the email of the maker will be empty (users service principles don't have email).

it will then makes the flow **HELPER - Send Email** called at the later step **Send Audit Mail to Owner Apps** fail because the email passed is empty.

```
 "body": {
        "error": {
            "code": "Request_ResourceNotFound",
            "message": "Resource 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' does not exist or one of its queried reference-property objects are not present.",
            "innerError": {
                "date": "2024-10-08T19:40:29",
                "request-id": "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy",
                "client-request-id": "zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz"
            }
        }
    }
```

![Image](https://github.com/user-attachments/assets/daa3106d-d069-4098-869a-36e0a8882ef4)

### Expected Behavior

after the expression `body('Check_Maker_status')?['userisserviceprinciple'] is equal to true` is added to the step  **Check if Maker is orphaned**, the expected behavior is :

- the step **Check Maker status** will get the information of the **maker**
- the condition **Check if Maker is orphaned** will also check if the **maker** is a **user service principle**
- the **TRUE** path of that condition will be executed and the **varAssignee** will be initiated with the admin email 
- the later step **Send Audit Mail to Owner Apps** will send a valid email to the **HELPER - send mail** flow
- the admin user will receive the email asking to check for compliance

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Compliance Details Request eMail (Apps)

### What method are you using to get inventory and telemetry?

None

### How i found the problem
I compared the flow **Admin | Compliance Details Request eMail (Apps)** to the flow **Admin | Compliance Details Request eMail (Flows)**. It's how I saw what was missing in the expression of the condition.

![Image](https://github.com/user-attachments/assets/29e81bed-48e6-41e0-8c96-319e890190d0)

### Other flows ?
maybe also check if the other flows have the same problem

![Image](https://github.com/user-attachments/assets/dd739c64-25e0-4042-af78-61dbb1326956)

**Comment by Jenefer-Monroe** [comment]
Thanks for the detailed investigation! I will try to add this for an upcoming release.

**Comment by Jenefer-Monroe** [comment]
repro was flow all except flow, so I fixed them all up. 
Thanks again for spotting and getting me the resolution, made this quick and easy.

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
