### ISSUE TITLE
[CoE Starter Kit - QUESTION] What Power Admin Solutions are and how they were created?

### ISSUE THREAD

**Issue by zellos13** [microsoft/coe-starter-kit#9103]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello,

I upgraded CoE recently and discovered that we have five new managed solutions for all upgraded CoE Environments.

![Image](https://github.com/user-attachments/assets/d4ca6b51-e12a-4c9d-9b51-3fb1fd143afb)

After an upgrade, I ran the CoE Setup Wizard app and nothing else. I just let Inventory Flows run and update the CoE. The day after, these solutions were visible, and they were created at the same time when Inventory Flows were running.

Could you let me know what these are? What do they do, and how were they created?

Cheers,
Daniel

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Core Components 4.31

### What method are you using to get inventory and telemetry?

None

**Comment by zellos13** [comment]
Hello,

They were created when Inventory Flows were running - at exactly the same time.

What I did after the upgrade? I just went through the configuration wizard and didn't touch anything. So, I am pretty sure it's something with CoE.. I just want to know how they were created - is there any trigger in CoE Core Component solution flows?

**Comment by Jenefer-Monroe** [comment]
Sorry I hear you that this is suspicious but they were not created by the CoE starter kit. The product installed solutions quite frequently for their work so it was happenstance the timing. I've not seen these solutions yet myself anywhere.

## I asked chatgpt what they were and these is what I got

**Power Admin Settings Security Solution (msdyn_PowerAdminSettingsSecuritySolution):**
This solution manages security settings within the Power Platform environment. It includes features like assigning security roles, managing application users, and controlling access through field-level and hierarchy security. [1](https://learn.microsoft.com/en-us/power-platform/admin/admin-settings).

**Power Admin Settings Auditing Solution (msdyn_PowerAdminSettingsAuditingSolution):**
This solution is used for auditing and tracking changes within the Power Platform environment. It helps maintain logs of changes to data and settings, ensuring compliance and security [2](https://learn.microsoft.com/en-us/power-platform/admin/admin-activity-logging) [3](https://learn.microsoft.com/en-us/power-platform/admin/system-settings-dialog-box-auditing-tab).

**Power Admin Settings Administration Solution (msdyn_PowerAdminSettingsAdministrationSolution):**
This solution allows administrators to manage various settings and configurations within the Power Platform environment. It includes system settings, business management, and service management settings [1](https://learn.microsoft.com/en-us/power-platform/admin/admin-settings)[4](https://benediktbergmann.eu/2021/12/04/settings-solution-component-explained/).

**Power Admin Settings Data Management Application Solution (msdyn_PowerAdminSettingsDataManagementSolution):**
This solution focuses on managing data within the Power Platform environment. It includes settings for data integration, data policies, and data loss prevention [1](https://learn.microsoft.com/en-us/power-platform/admin/admin-settings) [4](https://benediktbergmann.eu/2021/12/04/settings-solution-component-explained/).

**Power Admin Settings Document Management Solution (msdyn_PowerAdminSettingsDocumentManagementSolution):**
This solution integrates document management capabilities, allowing users to store, access, and manage documents within the Power Platform environment, often through integration with SharePoint [5](https://learn.microsoft.com/en-us/power-platform/admin/enable-sharepoint-document-management-specific-entities) [6](https://learn.microsoft.com/en-us/power-platform/admin/troubleshoot-doc-management-issues).

## I asked who made them and it told me this:
These solutions were created by Microsoft as part of the Power Platform suite. They are designed to help administrators manage various aspects of their Power Platform environments, including security, auditing, administration, data management, and document management  [1](https://learn.microsoft.com/en-us/power-platform/admin/admin-documentation) [2](https://www.youtube.com/watch?v=NajxakJ1HmY).

If you need more detailed information about these solutions or how to manage them, you can refer to the [Power Platform admin documentation](https://learn.microsoft.com/en-us/power-platform/admin/admin-documentation)[1](https://learn.microsoft.com/en-us/power-platform/admin/admin-documentation).

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
