### ISSUE TITLE
Connectors issue: http webhook v when http request received

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#9104]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi CoE Team, 

is it possible that the connector “When a http reuqest is received” is not included in the Impact Analysis App. The corresponding flows with this trigger are not displayed as impacted.
I have already had problems because productive flows were deactivated without warning.

Best regards
Cathi

### Expected Behavior

Showing impacted Flows with this trigger

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43 and earlier

### What app or flow are you having the issue with?

Data Policy Impact Analysis

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Is this the trigger that you are wondering about? 
![Image](https://github.com/user-attachments/assets/49315094-e715-4b47-b8a1-7310dd34887a)

It does appear we have some confusion in the inventory flows about that vs this trigger
![Image](https://github.com/user-attachments/assets/1b067947-cefa-4242-a78a-141a38855784)

Setting to investigate for an upcoming release.

**Comment by Cathi029** [comment]
> Hello. Is this the trigger that you are wondering about? ![Image](https://github.com/user-attachments/assets/49315094-e715-4b47-b8a1-7310dd34887a)
> 
> It does appear we have some confusion in the inventory flows about that vs this trigger ![Image](https://github.com/user-attachments/assets/1b067947-cefa-4242-a78a-141a38855784)
> 
> Setting to investigate for an upcoming release.

Yes, the first one is the trigger action I mean. I did not test the impact analysis for the Trigger in your second screenshot. Also the usage of Connektors in the Power Platform Admin Center ist not showing the trigger, so there is no possibility to see that these flows will be blockt.

Thanks for reviewing the problem! :)

**Comment by Jenefer-Monroe** [comment]
Looks like the return for this connector changed slightly when they added the other new teams hook.

Fix is in SYNC HELPER - Cloud Flows

1. `@coalesce(item()?['kind'], item()?['type'])`
2. `@{if(contains(body('Select_triggers'), 'HttpWebhook'), ',HttpWebhook', '')}`

![Image](https://github.com/user-attachments/assets/34a8aa82-6b59-472a-8f3e-5427b9cc5114)

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload

**Comment by Jenefer-Monroe** [comment]
Hiding above, tracked by https://github.com/microsoft/coe-starter-kit/issues/9277
