### ISSUE TITLE
[CoE Starter Kit - BUG Cannot do a wildcard search in Power Platform Admin View Filter by keyword field

### ISSUE THREAD

**Issue by Jodarcy1** [microsoft/coe-starter-kit#9107]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Is there a way to do a wildcard search in the Power Platform Admin View > Filter by keyword field?  I can do a contains filter under each column name (Filter by > Contains) but not in the Filter by Keyword field at the top right of the page. 

Power Platform > PowerApps Apps > > Filter by keyword > search for any word within app name = nothing comes up.  You can only search on first word in the name.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. In Power Platform Admin View, select **PowerApps Apps** in the left navigation.
2. In the **Filter by keyword** field at the top right of the page, type a part of a display name of the app.
3. Press Return
4. Result: if the word is not the first word of the app name, nothing shows up.

**Comment by Jenefer-Monroe** [comment]
Hello you can change what columns are included in the wildcard search by changing the "Quick Find View" view for the table. 
Here is what is currently configured for PowerApps for example. You can add your columns there
![Image](https://github.com/user-attachments/assets/0b15598b-05c1-4b8d-bbfa-f085eb07c172)


Here is some more information about this product feature: [Configure Dataverse search for your environment](https://learn.microsoft.com/power-platform/admin/configure-relevance-search-organization)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
