### ISSUE TITLE
[CoE Starter Kit - BUG] Typo in records created by HELP - Driver Escalation Check in Sync Flow Errors table

### ISSUE THREAD

**Issue by jean-goyat** [microsoft/coe-starter-kit#9109]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

An easy one - there is a typo in flow **HELP - Driver Escalation Check** which creates rows in the **Sync Flow Errors** table with the following hard-coded prefix:

> Driver flow: Failed to escalate **privaledges** for

instead of 

> Driver flow: Failed to escalate **privileges** for

![Image](https://github.com/user-attachments/assets/bbd5e9b5-b080-454d-aecd-1a9a5e894a59)

### Expected Behavior

Typo is distracting to admins and would expect it to be easily fixed - but admittedly a very minor thing
![Image](https://github.com/user-attachments/assets/5bd35072-8589-415a-8b51-fb60a6dd9101)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4_43_1 (September 2024)

### What app or flow are you having the issue with?

HELP - Driver Escalation Check

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open CoE Command Center
2. Check the Sync Flow Errors for a "Failing flow name" value that starts with "Driver flow"
3. That name column should show that typo

**Comment by Jenefer-Monroe** [comment]
Thanks for posting. I'll try to fix for an upcoming release.

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
