### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Audit Logs | Sync Audit Logs (V2) 

### ISSUE THREAD

**Issue by bnerdco** [microsoft/coe-starter-kit#9110]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Admin | Audit Logs | Sync Audit Logs (V2) flow failing on ListAuditLogContent with:
`{
  "error": {
    "code": "AF20023",
    "message": "The subscription was disabled."
  }
}`

Checked everything and I can't find any reason why.

Audit is enabled: 
![Image](https://github.com/user-attachments/assets/b2d3869a-26ca-4480-9a0e-8b95d83d1f8f)

App registration/ Permissions
![Image](https://github.com/user-attachments/assets/f7077917-4990-4826-9faf-73df66e73e8c)

Flow error:
`statusCode: 400`
`headers:
{
  "Cache-Control": "no-cache",
  "Pragma": "no-cache",
  "Server": "Microsoft-IIS/10.0",
  "mise-correlation-id": "c184b168-8440-4919-a3fc-a39e2782329f",
  "X-AspNet-Version": "4.0.30319",
  "X-Powered-By": "ASP.NET",
  "Date": "Fri, 11 Oct 2024 03:46:12 GMT",
  "Content-Type": "application/json; charset=utf-8",
  "Expires": "-1",
  "Content-Length": "71"
}`
`{
  "error": {
    "code": "AF20023",
    "message": "The subscription was disabled."
  }
}`

### Expected Behavior

Flow should be able to get audit logs.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Enable flow **Admin | Audit Logs | Sync Audit Logs (V2)** and Run.

**Comment by bnerdco** [comment]
Just adding another screenshot to show action failing:
![Image](https://github.com/user-attachments/assets/a9f717bc-e3d3-4792-9ad2-c8cb1b870b0c)

**Comment by pete-msft** [comment]
@bnerdco You need to start the Office 365 Management API subscription first by running **Admin | Audit Logs | Office 365 Management API Subscription** flow defining Operation = **start**

![Image](https://github.com/user-attachments/assets/b6470e4c-7d2f-4cfb-b446-74a084900498)


Or recommendation is to use **Setup Wizard - ARM Features** which runs that flow

![Image](https://github.com/user-attachments/assets/3bef6ba4-e450-405f-8d36-7b8b42f37263)

**Comment by bnerdco** [comment]
Not sure how I missed this as I was following the step by step guide, but this solved my problem. Thanks very much @pete-msft

**Comment by Jenefer-Monroe** [comment]
We do just rely on the backend responding correctly so if its not responding correctly to it being turned on I'm not sure how we can fix that. 
However lets try this helper flow in the kit and see if it resolves.

First run this flow with the input: list
**_Admin | Audit Logs | Office 365 Management API Subscription_**
![Image](https://github.com/user-attachments/assets/9666a19b-fb33-4cc7-9f88-2e06986fd32d)

Look at the run itself and see what it sys is the state of the subscription
![Image](https://github.com/user-attachments/assets/c077fe54-23f1-418c-94c9-ae064339e0cb)

**Comment by Jenefer-Monroe** [comment]
oh look who didnt refresh their page haha 
thanks PEte!
