### ISSUE TITLE
CoE (App Last Launched On) not populating

### ISSUE THREAD

**Issue by pakalask** [microsoft/coe-starter-kit#9113]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi, I have CoE installed in my environment and its been a while that i observed for all the PowerApps in our tenant for some of them "App Last Launched On" field is not populating and some of them its populating incorrect launch date. I am looking at list of all the apps from the model driven app "Power Platform Admin View". Can you please let me know how can i address this issue?
![Image](https://github.com/user-attachments/assets/91da4261-fe9e-49e6-9bbb-970d9554bef4)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

None

**Comment by pete-msft** [comment]
@pakalask Verify that **Admin | Audit Logs | Update Data (V2)** flow is turned on. That is the flow which updates app last launch info

![Image](https://github.com/user-attachments/assets/3782be7b-fdc9-424f-a2bb-3237243f6355)

**Comment by pete-msft** [comment]
@pakalask That is a bit misleading error as it is handled and happens when you do not use Azure KeyVault to store the secret. See this for more info https://github.com/microsoft/coe-starter-kit/issues/9116#issuecomment-2411147642

Check the next failing action in the flow. Most likely first HTTP action is failing

**Comment by pete-msft** [comment]
@pakalask Check that the Entra ID application is configured correctly especially the API permissions

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http#create-a-microsoft-entra-app-registration-for-the-office-365-management-api

**Comment by pakalask** [comment]
Thanks i set up the API permissions for the app registration and the flow run was a success. But how soon the app last launched on will be populated? Its been couple hours and i don't see it.

**Comment by pete-msft** [comment]
@pakalask if update data flow is turned on and there are app lauches for the apps you are checking then immediately. When sync flows runs it queries events one hour back in time

**Comment by pakalask** [comment]
So this will turn on the "app last launched date" going forward as the apps are launched but not for all the existing apps that's been already launched for the last few weeks?

**Comment by pete-msft** [comment]
Yes, CoE processes only one hour back of events when those flows run. If you want to get older events then you need to manually export Launched app events from Audit Log and use **Admin | Audit Logs | Load events from exported Audit Log CSV file** flow to import to CoE

https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http-old-data

![Image](https://github.com/user-attachments/assets/1f812ffe-07c8-414a-a9b3-0e5fe8db33dd)

**Comment by pakalask** [comment]
Thanks, one last thing is our team is planning to upgrade the CoE to latest version, can you please send me a link for instructions?

**Comment by pete-msft** [comment]
@pakalask https://learn.microsoft.com/en-us/power-platform/guidance/coe/after-setup

**Comment by Jenefer-Monroe** [comment]
Here you go: [Updating the Center of Excellence (CoE) Starter Kit](https://learn.microsoft.com/power-platform/guidance/coe/after-setup)

The short answer is:
- upgrade creator kit
- upgrade Core
- boot the setup wizard

**Comment by pakalask** [comment]
So basically download latest version of coe starter kit, use import solution for each of the solution components, choose upgrade and repeat the process for all solution components. Once everything is done boot the setup wizard.

I also see Creator kit in the list of solution components but i never touched it. Do i need to download creator kit too and can you let me know the what are the steps to follow in order?

**Comment by Jenefer-Monroe** [comment]
Sure. 

Here is the link to download latest Creator Kit https://aka.ms/creatorkitdownload
And their setup instructions: [Install Creator Kit](https://learn.microsoft.com/power-platform/guidance/creator-kit/setup)

Its a much simpler install. And you must have it already unless you are on a very very old version of the kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
