### ISSUE TITLE
[CoE Starter Kit - QUESTION] Environment Capacity Process

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#9114]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello everyone, how are you?

I would like to know which flow feeds the Environment Capacity table. I need to reduce the scheduling time because some environments are growing exponentially.

### What solution are you experiencing the issue with?

Core

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Generally speaking you can find this information by looking at the helper flows dependencies
![Image](https://github.com/user-attachments/assets/e8ab7f26-9b26-4a68-bf5c-055bda29f3a7)
![Image](https://github.com/user-attachments/assets/f7423b90-a7f8-4668-9509-0e1a8089d44c)

In this case you will find this flow to be called by **_CLEANUP - Admin | Sync Template v4 (Other Objects)_**

Note that this calls other long running child flows and so runs only every other week. 
You may want to instead add your own additional flow which just calls this separately more frequently. 
I suggest doing a save as, and then in your new copy changing the triggers frequency, and then deleting the non-capacity oriented branch of the flow. 
![Image](https://github.com/user-attachments/assets/cf922021-2836-4fe1-8f7d-a070868ca47a)

**Comment by ClaudioRWS** [comment]
Thank you very much for your help @Jenefer-Monroe ! I will create an extended solution with your idea.

Muito obrigado!
