### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Email Managers Ignored Inactivity notifications Approvals Wrong Manager

### ISSUE THREAD

**Issue by tomtech1** [microsoft/coe-starter-kit#9115]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi

I've had a report of someone in our tenant receiving an ignored email for another user that is not their direct report.

I've had a look through the flow run, and the only thing I can think of that may be related is that the users actual manager has left the business and the next manager in the loop is the user that has received the email for the wrong employee.

### Expected Behavior

I'd expect that if the manager does not exist, then it should be skipped and shouldn't go to the next manager in the loop? Unless this is totally unrelated and there's something else going on.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32

### What app or flow are you having the issue with?

Admin | Email Managers Ignored Inactivity notifications Approvals

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
The users manager will be updated by the following flow. So if the users manager has changed it will get updated there.
Please be sure its turned on, running, and passing: **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_**

And see who is listed as their manager in the Maker table today
![Image](https://github.com/user-attachments/assets/8fb8dd3a-5500-44eb-91a4-d894eb683937)

**Comment by Jenefer-Monroe** [comment]
You can find this information generally by looking at the child flows dependencies. 
![Image](https://github.com/user-attachments/assets/f6c2811b-2dd7-4195-a765-ace37f199953)
![Image](https://github.com/user-attachments/assets/350d5d21-4c41-404a-93c5-f5264c874bdc)

In this case its the flow is run once by the Setup Wizard when you use that, and then weekly by the **_Admin | Sync Template v3 (Call Updates)_** flow.
![Image](https://github.com/user-attachments/assets/443ceae6-c40c-4490-bdf7-62b98abd4f2a)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
