### ISSUE TITLE
[CoE Starter Kit - BUG] Admin Azure Key Vault - Sync Flow Failing - Cannot read value as null

### ISSUE THREAD

**Issue by crowdedLeopard** [microsoft/coe-starter-kit#9116]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

We're doing a test install of the COE toolkit and are using the ClientSecret environment variable (stored as string/bad I know). We're being given the error (error occured while reading secret value value cannot be null) except we arent using key vault. Its causing the flow to fail and no data is ingested. Ive checked that the value is null in the corresponding env variable. 

![Image](https://github.com/user-attachments/assets/69cde77f-ebb3-4b87-b384-861ca4975ede)

Should I edit the flow to ignore the kv variable

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Sep 2024

### What app or flow are you having the issue with?

Admin Audit Logs Sync Audit Logs V2

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
If you are not using Azure Key Vault then this failure is expected and caught. 
Note that flow always shows the first failure even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
