### ISSUE TITLE
[CoE Starter Kit - Feature]: Setup Wizard addition - check that required HTTP with Entra ID Scopes are all approved and working

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#9118]
### Is your feature request related to a problem? Please describe.

Per https://admin.cloud.microsoft/?ref=MessageCenter/:/messages/MC901932, need to have scopes approved by admin. 

### Describe the solution you'd like

Will add checks for this to the Setup Wizard

**Comment by Jenefer-Monroe** [comment]
Special thanks to @SPmush for getting this alert to us so quickly

**Comment by SPMush** [comment]
Thank you @Jenefer-Monroe  and @Grant-Archibald-MS  for doing all the leg work to find the answers!

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
