### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Starter Kit forbids automatic deletion of inactive developer environments

### ISSUE THREAD

**Issue by madwalter3** [microsoft/coe-starter-kit#9119]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Dear all,
I found a bug in the CoE Starter Kit Flows and would ask you to change the flow for next release (or even find a better solution).

**Our Problem:** Even though we exclude our developer environments from CoE Inventory, the developer environment were no longer deleted, because the "Last activity" column for each developer environment was updated daily. Please also see the issue #5968. 

**Possible Solution:** We added the following attributes to the condition in the flow **_**CoE BYODL - When Environment dataflow refresh is complete**_**: 
![Image](https://github.com/user-attachments/assets/7991578a-25b0-4957-bdc7-3f69f1bf88dd)
The flow no longer needs to log into each environment to get the data for PCF State --> no more activity on developer environments --> automatic deletion works again --> problem solved.

 

### Expected Behavior

Inactive developer environments are automatically disabled and then deleted to free up resources for improved performance.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

CoE BYODL - When Environment dataflow refresh is complete

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. For the CoE Environment,
2. With "Exclude from Inventory" turned on for all developer environments
3. Run _CoE BYODL - When Environment dataflow refresh is complete_
4. See https://admin.powerplatform.microsoft.com/environments and the Last activity column notices an update for each environment with a Dataverse instance.

**Comment by Jenefer-Monroe** [comment]
Hello this keep alive issue is a product issue that our PM is working on with them. Here is our tracking issue for it: 
https://github.com/microsoft/coe-starter-kit/issues/5968

We have finally gotten traction and the plan is to change the way they track some programmatic changes. 
My suggestion is that you keep your work around in place and then hopefully by EOY the proper product fix will be in place.

**Comment by madwalter3** [comment]
Ok, we will work with a workaround and see if it interferes with any updates. Hope to have a fix by EOY. Thanks :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by KRhoadesHyp** [comment]
I realize this issue is closed but I wanted to just make a quick note to say this is definitely an issue, we are presenting the developer environments as 'self-maintaining', yet none of them are being deleted because of the activity.  Also looking forward to a fix!
Thanks.

**Comment by Jenefer-Monroe** [comment]
Yes I didnt realize this was being used to get around the keep alive issue. So I've posted https://github.com/microsoft/coe-starter-kit/issues/9169 for Nov release.

**Comment by Jenefer-Monroe** [comment]
Since this bug is closed I may not see further responses here. Can you please test the proposed fix? Its in https://github.com/microsoft/coe-starter-kit/issues/9169#issuecomment-2432462926 and add responses to that issue so that i am sure to see them.
