### ISSUE TITLE
[CoE Starter Kit - BUG] Assign new owner to orphaned app --> app still flaged as orphaned

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#9120]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi,

if I assign a new owner to an orpahend app via Power Platfrom Admin View --> Manage Permission the app is still flagged as orphaned.

### Expected Behavior

The app should get flaged as not orphaned

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Sep 2024

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Nice catch! 

In the new version of the kit this is actually a powerfx formula so we dont store if its orphan independently of who you assign to. So going forward this will not be an issue.

To local fix ahead of that you can either edit the flow to mark this explicitly as shown here
![Image](https://github.com/user-attachments/assets/278db381-9a37-4b8d-86a0-145703a1d247)

Or just wait until the next run of **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** which should clean it up.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by Jenefer-Monroe** [comment]
We are actually reshipping V1 for another issue so I've patched this one for V1 as a result. 
Thanks again for posting.

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
