### ISSUE TITLE
[CoE Starter Kit - Feature]: Orphaned Process Assignment Fails Due to Manager Not Being Part of Environment Security Group

### ISSUE THREAD

**Issue by lukas-nC** [microsoft/coe-starter-kit#9121]
### Is your feature request related to a problem? Please describe.

Hi,
We have enabled the Orphaned Process feature, and a manager provided feedback that orphaned flows should be assigned to them. However, the assignment failed, and we received the following error message:

The supplied reference link -- systemusers() -- is invalid. Expecting a reference link of the form /entityset(key).

Upon investigation, we discovered that the environment where these flows reside is protected by a security group. The manager is not a member of this security group, which prevented them from being found in the SystemUser table. As a result, the assignment process could not locate the manager's SystemUserId.

### Describe the solution you'd like

![Image](https://github.com/user-attachments/assets/2a7e5b7e-f304-4474-a182-f8d32da6722a)

I would like to propose a change to enhance the error notification. If the Compose action (Get new owner SystemUserId) returns empty, the error notification should clarify the issue by stating:

The flows could not be assigned because the selected owner is not a member of the corresponding environment's security group. Please Contact your Power Platform Team 

This would help clarify why the assignment failed and provide guidance on how to resolve the issue, for the admins and consumer of this process

**Comment by lukas-nC** [comment]
Hi @Jenefer-Monroe,

to answer your question, yes, this flow is running in context of the flow owner.

But I don't think that's the problem.
![Image](https://github.com/user-attachments/assets/fedbb994-7631-40c2-a783-d90f203f6033)
In my case, I got an error because 1 was empty.
1 was empty because of 2, 
which was empty because of 3,
 which was empty because the manager (4) is not in the systemuser table.
And his Id is not in the systemuser table because he is not a member of the environment security group of the environment where the orphaned flows reside in.

**Comment by Jenefer-Monroe** [comment]
Oh I see. Yep I can add something different there that validates thats the issue and updates the return string correctly. 
Thanks for posting.

**Comment by Jenefer-Monroe** [comment]
Can you please test this for me? 

`@{if(equals(length(outputs('Get_first_from_list')), 0), concat(body('Maker_Check')?['userdisplayname'], ' cannot be added as they are not a member of the environment security group'), outputs('Update_flow_owner')['body/error/message'])}`

Here: 
![Image](https://github.com/user-attachments/assets/0650b22a-ad24-4a3c-a7e3-2e2a6fff24fe)

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
