### ISSUE TITLE
[CoE Starter Kit - QUESTION] New Environment Variable Errors

### ISSUE THREAD

**Issue by kholley01** [microsoft/coe-starter-kit#9128]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I am trying to create a new environment variable and I am getting the following two errors: 

"This variable didn't save properly. User is not authorized to read secrets from '/subscriptions/13eba60d-16d5-4b55-9f9d-eee2547deae5/resourceGroups/AzureFiles-RG/providers/Microsoft.KeyVault/vaults/PowerPlatformKeyVault3/secrets/PowerPlatformSecret3' resource."
 
"This variable didn't save properly. Cannot complete the creation of EnvironmentVariableDefinition because it violates a database constraint. The violation happens on the key schemaname: cre7e_PowerPlatformKeySecret. Please delete the existing record or use update."

I have added myself as a Key Vault Secrets User in the Subscription, Resource Group, Key Vault, and the Secret itself and I am getting either one of these errors. When I change the "schemaname", I then get the "not authorized to read secrets" error. Not sure where to go for both errors. Any help would be appreciated. 

Thank you!!
[Image](https://github.com/user-attachments/assets/b5088d32-da3d-4418-8f3a-331abda10499)
![Image](https://github.com/user-attachments/assets/51107166-79ea-4efb-a341-f3d3ad310a2a)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

New Environment Vairable

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by pete-msft** [comment]
@kholley01 So are you trying to set the value for CoE Kit environment variables **Audit Logs - Client Azure Secret** and/or **Command Center - Client Azure Secret**?

![Image](https://github.com/user-attachments/assets/557398b6-6ead-4155-b0b1-4a9e5353ee95)



If yes then you do not need to create new environment variable for CoE but configure the value for these existing environment variables available in CoE solution. As you are configuring secret you need to do this in Default solution of the environment

![Image](https://github.com/user-attachments/assets/a11bbfab-96c5-46f5-b264-92f3bbd9cef7)

**Comment by kholley01** [comment]
Thank you for the response. I have tried to change the variable in the Default solution and I’m still receiving the error.

***@***.***

Thank you!

Kennith “Kenny” Holley
IT Systems Administrator
Primoris Services Corporation
www.prim.com<http://www.prim.com>
***@***.***
“Primoris, building America’s future, today.”

**Comment by Jenefer-Monroe** [comment]
Validate that the azure key vault permissions are correct. User needs to be in Key Vault Secret User role explicitly to read, and in the Key Vault Contributor Role to update. And your access needs to be via RBAC
For more information [Use environment variables for Azure Key Vault secrets](https://learn.microsoft.com/power-apps/maker/data-platform/environmentvariables-azure-key-vault-secrets)
1. RBAC
![Image](https://github.com/user-attachments/assets/0ef44c27-050c-4c0e-8166-3446d44a0d60)
2. Specific Roles
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/ca0d1074-755e-4fe9-8903-e12a6d94614b)

**Comment by kholley01** [comment]
Verified that roles and RBAC is correct and still receiving the read secrets error message.

**Comment by Jenefer-Monroe** [comment]
Did you validate this step from the document:  [Use environment variables for Azure Key Vault secrets](https://learn.microsoft.com/power-apps/maker/data-platform/environmentvariables-azure-key-vault-secrets)
![Image](https://github.com/user-attachments/assets/e28bdbd5-7fb8-408c-bb0d-2d615dfb002d)

**Comment by kholley01** [comment]
Confirmed that step was completed![Image](https://github.com/user-attachments/assets/11d9d210-43c9-42dc-958b-4ecd90cb8080)
.

**Comment by Jenefer-Monroe** [comment]
ok unfortunately you will need to reach out to product support. This is product UX we are looking at and those are the troubleshooting steps I know. 
Sorry I cant be of more assistance.

**Comment by pete-msft** [comment]
@kholley01 So you have verified that the account you are using to set the value of the environment variable has **Key Vault Secrets User**  permissions in the KeyVault?

![Image](https://github.com/user-attachments/assets/bc3b3691-7df1-49c1-9d91-a77ebee3d05a)

![Image](https://github.com/user-attachments/assets/0ff716b2-7976-4c54-932f-38b6966f8bb0)

![Image](https://github.com/user-attachments/assets/f42df6ac-af67-4a4b-be32-e728be1d7133)

**Comment by kholley01** [comment]
Yessir. I have confirmed that the account has Key Vault Secrets User permissions in the Key Vault.

Again, I really do appreciate the help.

Thank you!

Kennith “Kenny” Holley
IT Systems Administrator
Primoris Services Corporation
www.prim.com<http://www.prim.com>
***@***.***
“Primoris, building America’s future, today.”

**Comment by pete-msft** [comment]
@kholley01 **Key Vault Secrets User** is only permission what is needed for the user who sets Audit Logs - Client Azure Secret environment variable value

**Comment by Jenefer-Monroe** [comment]
Unfortunately that UX is the product's and you are struggling with a product feature to connect Azure Key Vault with Power Platform Environment Variables. We just consume those environment variables once configured. 
So you will likely need to contact product support at this point to get unblocked.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by manjugundala** [comment]
I have  a workaround for this issue.
