### ISSUE TITLE
What columns got relation between Solutions and Apps Tables

### ISSUE THREAD

**Issue by devvelegandla** [microsoft/coe-starter-kit#9130]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

We are trying to cleanup large set of unused apps within the solutions. We are struggling to find the related information between the apps and solution tables. Could you please let us know if we can add a solution Name to the Power Apps Table?

Thanks,
Devendra

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello. 
Retrieving the components of a solution is not very simple unfortunately. We use a table in each envt called solutioncomponents which is hidden and has some undocumented fields we use to find object types. 
Honestly we kind of force tested this until it returned what we wanted. 
You can play around though and see if you find something better / easier. If you do please let us know!
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/3562f923-a77c-44b9-b9fa-67b4a703ede2)

You can find this in the **_CLEANUP HELPER - Solution Objects_** flow (note in Feb it was still part of the **_Admin | Sync Template v4 (Solutions)_** flow)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
