### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION About coe starter kit setup

### ISSUE THREAD

**Issue by syou0224ondr176mocoksrg** [microsoft/coe-starter-kit#9131]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

When following the setup and upgrade wizard instructions, it is necessary to set up admin persona, maker persona, and user persona.
If we proceed with the setup as is, will we be able to complete the setup?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I hope this helps

**Admin eMail** : 
Required to run the kit generally
The email address of the admin group you want to use for communications. 

**Power Platform Maker Group ID** : 
Required to run the following flow: Admin | Add Maker to Group
The group ID of the maker group you want all your Power Platform makers to be a part of (for communication and app sharing)

**Power Platform User Group ID** : 
Optional
The group ID of the user group you want all your Power Platform users to be a part of (for communication and app sharing)

**Comment by syou0224ondr176mocoksrg** [comment]
Thank you for your answer.
Is the following recognition correct?


Administrator's email:
Required to use the kit.

Power Platform Maker Group ID :
Not required if we are not using the kit as a way to contact the administrator and maker.

Power Platform User Group ID :
Not required if we do not plan to contact the user.

**Comment by Jenefer-Monroe** [comment]
No the groups are not just for contact but also for sharing. So if you do not wish to fill a Azure Security/Distribution Group with all the makers (for communication or for sharing/permissioning) then you do not need that one.

**Comment by syou0224ondr176mocoksrg** [comment]
I am not sure if my understanding is correct, so please let me know if I am correct below just to be sure.

When I set up the maker persona group in CoE, the Azure security/distribution group will reflect the group I set up, but if I do not want to add the maker to the security/distribution group, I do not have to.
As for the other groups, my message from the other day is correct.

**Comment by Jenefer-Monroe** [comment]
Correct.

**Comment by syou0224ondr176mocoksrg** [comment]
Thank you for your thoughtful response.
We will close the question now that it has been clarified.
