### ISSUE TITLE
The 'Load events from exported Audit Log CSV file' fails.

### ISSUE THREAD

**Issue by meywenz** [microsoft/coe-starter-kit#9136]
Hi. 

We have received the .csv file with Audit logs. The logs are from 90 days, 1000002 rows in the file. The Global Admin that sent this file to me says that the report was exported from the M365 Admin Center. 

In the file there are 2 sheets with logs, same logs but the structure of the data is different:

Sheets
![Image](https://github.com/user-attachments/assets/77c594d7-163f-49d2-b5c3-33ea7e0dd526)

Table1
![Image](https://github.com/user-attachments/assets/af70fdc7-17a4-4ab3-bd07-b502c56d24ac)

3aaa3ee0-bc4e-459f-9fba-3802707
![Image](https://github.com/user-attachments/assets/e4f8dc2b-ac21-4dd7-87f8-24ab95532a46)

From the copy of the file I have deleted all of the rows despite headers and the first row just to test the **Admin | Audit Logs | Load events from exported Audit Log CSV file** flow. (Btw, I know the file should not have more than 50k rows. We will prepare 21 files that will contain max 50k rows. )

I have tried multiple combinations with this flow:
- 1 row in each sheet
- 1 row and only the Table1 sheet
- 1 row and only the 3aaa3ee0-bc4e-459f-9fba-3802707 sheet.

When I trigger the flow, it fails at the 'ParseAuditData'

![Image](https://github.com/user-attachments/assets/d0421b23-c668-41d9-95fe-05313e18c1d9)

The content from the file looks very weird in the flow and I have no idea why.

I'd like to ask how the file should be prepared so it's compatible with this flow? How should the logs be exported?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
