### ISSUE TITLE
[CoE Starter Kit - BUG] Apps do not work after upgrade to version 4.43 (Error Code: AppMetadataParserFailed)

### ISSUE THREAD

**Issue by VanIsleCA** [microsoft/coe-starter-kit#9140]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi, Jenefer,

This is also a follow-up to a previous issue that I have described here: https://github.com/microsoft/coe-starter-kit/issues/9037

We followed up with Microsoft as per your indications and they could not find anything wrong with their deployment pipeline, so they sent me back to COE support. To avoid the back-and-forth, I decided to start fresh, and build a new environment for this instance of the COE. 

1. I have first created a brand new environment to accommodate a new CoE instance.
2. I have then installed version 4.37 (August), tested, and validated that everything works. I wanted to have a working version in the environment, before installing the "problematic" 4.43.
3. I have then proceeded and upgraded to version 4.43. Everything worked and upgrade showed successful (please see attachment labeled "two").
4. Published ALL, and then tried to open the Setup Wizard app. At this point, I get an error on the page. All apps are now erroring out like this below:

**Error Code: AppMetadataParserFailed**
Session Id: 3109b7e2-f9b5-476d-968e-6de6cc1104c7
Activity Id: 5af7c15f-f9db-457e-9f85-528b0bba6087
Timestamp: Wed Oct 16 2024 16:37:51 GMT-0700 (Pacific Daylight Time)
**AppLogicalName admin_commandcenterappspage_fdc96 does not have an AppPackage**
UciError: AppLogicalName admin_commandcenterappspage_fdc96 does not have an AppPackage at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.95a4a628bf012ee56664e59e7cebb0d8.js:33:955344) at https://content.powerapps.com/resource/uci-infra-bus/scripts/custompage.cc27900c85b56a5139909dd3b7408512.js:4:23208 

Can you please shed some light into what is going on with this version 4.43? This version seems to be the only one causing this type of behavior. I have upgraded the CoE at least 10 times now in tandem ALM environments and have never encountered this error before.

I have added more attachments for context:

- Attachment labeled "one" shows the actual error: ![Image](https://github.com/user-attachments/assets/59ca4893-1ed1-4e5b-a0e4-8f6f86f54622)
- Attachment labeled "two" shows Successful message when upgrading to version 4.43 ![Image](https://github.com/user-attachments/assets/d07da62b-48ca-4624-a960-5f66fd088573)
- Attachment labeled "three" shows all managed solutions in this "clean" new environment ![Image](https://github.com/user-attachments/assets/3f19a8b9-e8b5-48c4-87e3-f5a59b6b670a)

Hope this can provide a good starting point for troubleshooting,

Thanks in advance!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

All apps in Core Components

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I've never seen this suboperation when doing upgrades
![Image](https://github.com/user-attachments/assets/57eec137-af1c-4a24-abee-6759a3d61e8e)

Here is what I always see.
![Image](https://github.com/user-attachments/assets/0524a43c-cd00-4aea-8376-250162b6bb6b)

The 4.43 is a good build, might I suggest you just start with that since you are starting over anyway?

**Comment by VanIsleCA** [comment]
Thanks, Jenefer,

What worked was to Switch to Classic and Upgrade to the same version, using the "Overwrite customizations" option. Maybe something to pass along, in case anyone else is running into the same issue as I did.

Thanks & have a great weekend!

**Comment by Jenefer-Monroe** [comment]
Wonderful! Thanks for sharing!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
