### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Vignes29** [microsoft/coe-starter-kit#9146]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

We are trying to upgrade our CoE Core Components from the June 2023 version to the July 2024 version, but we are encountering an error message:

"Solution 'Center of Excellence - Core Components' failed to import: ImportAsHolding failed with exception: Import failed: The DELETE statement conflicted with the REFERENCE constraint 'connector_connectionreference'. The conflict occurred in the database 'db_crmcoreemea_20201020_10215685_101e', table 'dbo.connectionreferenceBase', column 'CustomConnectorId'. The statement has been terminated."

We have also attempted all the steps and workaround provided for previously reported issues ([8507](https://github.com/microsoft/coe-starter-kit/issues/8507)), but we still cannot import the solution into our target environment. We would like to request a resolution for this issue.

![Image](https://github.com/user-attachments/assets/2a9e56d4-51ee-4a87-9f98-7dc96bb3225b)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Cloud Flows

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately those look like product tables and we do not have any custom connectors in the kit at this time. So this appears to be a product upgrade bug unrelated to our package. We have seen several like these recently. 

You may need to attempt an overwrite to proceed.

### How to do an overwrite upgrade in the classic UX:
 
Switch to classic
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/690cafcb-ade8-4571-81d5-df70f97f6266)

Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/433cd2d8-7e2a-4d35-a86e-cf569b7777f2)

Select Core > Next
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f232f4b5-783d-4d8c-af94-21fb6dfd91bf)

Next
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/39c84d9b-7ccf-4aff-8861-6c70ed7cb237)

Overwrite customizations > Import
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/7b23463c-2361-4135-81a8-363a96ca23d5)

**Comment by Vignes29** [comment]
We have followed the same steps as You have mentioned and imported the solution in the target environment, but I can see all the v3 flows and v4 flows in the solution. unfortunately, it didn't remove the older flows from the solution.

![Image](https://github.com/user-attachments/assets/27df56cd-ef01-4c82-b286-0c21c47af221)

![Image](https://github.com/user-attachments/assets/2dd4fe31-e57a-4607-b0eb-bc73237f64c2)

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Vignes29** [comment]
Previous version installed was 4.9 June 2023, we have tried to upgrade to the sept 2024 version and used the update method to import the solution in the environment. so the version right now is 5.0
![Image](https://github.com/user-attachments/assets/0e7d4a8c-f881-49b2-b57e-1594030de4e0)

**Comment by Jenefer-Monroe** [comment]
Ok these do not appear to be the solutions that we deliver as we are not on version 5, nor do we product the other solutions in that list. 
I'm not clear on the situation here. Can you please provide some context?

**Comment by Vignes29** [comment]
Apologies for the confusion. we previously had July 2021 version installed. We are now trying to upgrade to July 2024 version. During import in classic mode, we didn't have the option for update or upgrade. So now we have the v3 version and v4 versions of the flow. 
![Image](https://github.com/user-attachments/assets/28219d5b-d2f0-4b06-8bb3-1d03706ed3aa)

**Comment by Jenefer-Monroe** [comment]
I see. Unfortunately I just do not expect upgrade to succeed for that long of a time between. I also don't recognize these solution names
![Image](https://github.com/user-attachments/assets/6144c37f-dd2d-4de5-ad17-8dfbe0fefd18)

It appears you may be creating your own solutions somewhere. Is that the case?

**Comment by Vignes29** [comment]
The ones highlighted in yellow are different custom solutions we created internally, But they do not have any dependency or link to Core components solution

**Comment by Jenefer-Monroe** [comment]
OK Im not sure I will be able to assist you. The core components version you have is higher than the latest version we have released. And given that your last install was in 2021 I think you will likely be best served just starting over. 

Can you please tell me, what do you use the kit for? Do you just use it for inventory? Or have you collected metadata (ex compliance processes)

**Comment by Vignes29** [comment]
We use the CoE kit for inventory management.

**Comment by Vignes29** [comment]
This is the error we have got in the latest import 
"The uninstall operation will delete the base layer for the component 'EntityRelationship' with id 'fcbd0977-20c2-eb11-8235-000d3abd4592' and name 'admin_FlowResource_Flow'. The operation cannot continue because there are other managed layers over the base layer. You can use the solution layers to find out which other solutions are blocking the operation."

![Image](https://github.com/user-attachments/assets/9998a9c2-edef-4453-9b29-02d93213d886)

we were trying to remove the solution layers, but the "Remove active customization" button is disabled.

**Comment by Jenefer-Monroe** [comment]
Sorry you are really in an unknown state here, with none of these being solutions we release.
![Image](https://github.com/user-attachments/assets/5eabacda-555c-4ed9-b5f4-e8500a4a1423)

I think you are going to be best served starting over in a new environment. What do you mean by solution management? I'm trying to see if you will need to migrate any data or if a clean install will get you what you need.

**Comment by Vignes29** [comment]
We would like to know how to ensure that our data is not deleted. The solutions mentioned above are some of the custom approaches we currently have in our environment.

**Comment by Jenefer-Monroe** [comment]
I understand. I wish I could better assist but since the issue you are having is with your custom solutions there isnt a way for me to predict or understand what may be happening.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
