### ISSUE TITLE
Is it possible to install CoE core components without a O365 Outlook licence?

### ISSUE THREAD

**Issue by HendrikCRM** [microsoft/coe-starter-kit#9152]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi,
Is it possible to install CoE core components without a O365 Outlook licence?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

CenterofExcellenceCoreComponents_4_43_managed

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry no its not. The kit uses and requires an O365 license to proceed as thats the main form of communication it uses.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
