### ISSUE TITLE
[CoE Starter Kit - BUG] var Audit Logs Secret doesn't get saved.

### ISSUE THREAD

**Issue by lucasubieta** [microsoft/coe-starter-kit#9154]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi there!
I'm having an issue with the audit logs. It was working properly until I opened the app CoE Setup and Upgrade Wizard -> More features -> Audit Log -> Configure this feature. I just entered to show it to a college butI didn't change anything as the process was already running without issues.

But now the Audit Logs flows are running into an error, saying that the variable Audit Logs - Client Secret is empty. The problem is that if I enter the "CoE Environment Variables" and reenter the secret value, it looks like it’s saved, but if I exit and reenter the apps, it's empty again, so it is not saving the value. That's why the flows are not running properly and i cannot configure it...

What can i do? thanks a lot.

![Image](https://github.com/user-attachments/assets/66ecc64b-00b5-4ce1-b13b-d6dd576518ef)

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

July

### What app or flow are you having the issue with?

Admin | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by lucasubieta** [comment]
i already tried reconfigurating the proccess in CoE Setup and Upgrade Wizard -> More features -> Audit Log -> Configure this feature and still the same

**Comment by Jenefer-Monroe** [comment]
Hello there was a product change in the way Environment Variables are set and the kit had to update to use that change. Your next upgrade (to Sept build) you will be able to use the app to update env vars again. Please see https://github.com/microsoft/coe-starter-kit/issues/8916

In the meantime you can use the product ux to change env vars. 
You will need to go to the default solution to do that though, please do let me know if you need help with that.

**Comment by lucasubieta** [comment]
Thanks for the quick solution and support !
