### ISSUE TITLE
Can I upgrade directly from April to August / Sept?

### ISSUE THREAD

**Issue by jay-dee-20** [microsoft/coe-starter-kit#9156]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi, I can't see this anywhere, but did note that the July version was pulled.

I'm hoping to upgrade from April -> July.  Am I safe to go from April -> August, or do I need to do April-> June -> August?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

April 2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
There are some product upgrade bugs in play right now that may end up with you hitting hurdles. But otherwise you should be fine there. Go ahead and give it a try and let me know how it goes.

**Comment by Jenefer-Monroe** [comment]
I do suggest Sept rather than August as there were some product changes around environment variables which were adjusted to in the Sept release.

**Comment by jay-dee-20** [comment]
Thanks Jenefer - is it OK to go straight from April -> September?

**Comment by Jenefer-Monroe** [comment]
It should be, but as I said, we have some upgrade issues with the product recently around dependency ordering. So go ahead and give it a try and then if you get an error let me know, we can get you unblocked.

**Comment by jay-dee-20** [comment]
Thanks Jenefer - will give it a go!
