### ISSUE TITLE
Inactivity Notification flow runs on last modified date not as per last run.

### ISSUE THREAD

**Issue by Ppallavi93** [microsoft/coe-starter-kit#9159]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team, 

Inactivity Notification flow runs on last modified date not as per last run.
It is suppose to send notification to apps and flows which are not active.
But it is not taking last run data and sending notification to apps and flows which are in production.

### Expected Behavior

it must take last run of the flows and app.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.25

### What app or flow are you having the issue with?

Admin | Inactivity notifications v2 (Start Approval for Flows) Details

### What method are you using to get inventory and telemetry?

None

**Comment by Ppallavi93** [comment]
Please help me on this as I am still getting messages from users that it is not running correctly

**Comment by Jenefer-Monroe** [comment]
Yes thats correct. Flow run information is not incorporated into the kit at this time. That information was just put into the product recently and we have not yet incorporated though it is on our backlog.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
