### ISSUE TITLE
[CoE Starter Kit - BUG] Managed Permissions app not allowing search

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#9161]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

The Managed Permissions app is extremely slow and it does not allow me to search for a flow so that I can change the derived owner because the current owner is no longer with the company. I used to be able to change via the Power Platform Admin View app, but not anymore, so was trying to use the managed Permissions app and it doesn't allow me to search. When I try to search for the flow by the name of ID no results come back, or it doesn't do anything when I try to search. I am not sure if it is because we have a large tenant.

### Expected Behavior

Search for the flow or the orphaned owner and it pulls up the flow. Not pulling anything for the flow.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2024

### What app or flow are you having the issue with?

Managed Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open Managed Permissions app
2. Go to the Environments section and choose Personal Productivity
3. Search for flow via name and then by flow ID
4. No results
5. Tried to find the flow in orphaned flows. Search isn't working
6. Tried the Owner section, not finding the owner.

**Comment by AUTigers16** [comment]
I will shoot you an email because for some reason my images still do not post here, but this would be the first time using the app so i don't have any unmanaged layers.

**Comment by Jenefer-Monroe** [comment]
thank you. I see you meant the envt search. I can repro if I change the data row count. Looks like they used collections when they should not have. Should be an easy fix. Targeting for November.

**Comment by Jenefer-Monroe** [comment]
same delegation bug for apps

**Comment by Jenefer-Monroe** [comment]
ready for Nov

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
