### ISSUE TITLE
[CoE Starter Kit - QUESTION] Which Flow is filling the Environment Table?

### ISSUE THREAD

**Issue by Grandepaci** [microsoft/coe-starter-kit#9162]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello everyone,

i cant find the Flow that is filling the Environment Dataverse Table inside the CoE - Core Solution.
The Other Tables have Admin Sync Template Flows, f.e. "Admin | Sync Template v4 (Flows)".
I cant find such a flow for the Environment.
Can you help me find the flow that is filling the Environment Table?

I read old threads saying you can find that in the flow "Admin | Sync Template v3", but that one is not existing anymore.

Thanks in advance
GP

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Version 4.43

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. This is the flow that fills environments and drives the rest of the object flows: Admin | Sync Template v4 (Driver)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
