### ISSUE TITLE
Sync Audit Logs failed because application ID has no permissions

### ISSUE THREAD

**Issue by PatrickGroen1** [microsoft/coe-starter-kit#9163]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

We received an error since October in the Sync Audit Logs flow: Action 'AuditLogQuery' failed: {"message":"App:********** dont have any permissions"}

The API permissions of the App registration look like in this picture: 
![Image](https://github.com/user-attachments/assets/09b9d0c3-79a6-4331-b158-192be004cec4)

We are referencing the Audit Logs - Client Azure Secret environment variable. Client Secret valid until 1/18/2026.
The Admin | Audit Logs | Office 365 Management API Subscription flow runs successfully
Admin | Audit Logs | Update Data (V2) flow is On, with no recent runs in 28-day history
Admin | Audit Logs | Sync Audit Logs (V2) flow is now turned off because of the error.

The (Dataverse, O365 Users) connections run under an account with these licenses/roles: PowerApps Premium, Power Automate per user plan, Office 365 E5, System Admin of CoE environment). The account has access to the Client Secret in Azure Key Vault (Key Vault Secrets User).
 
More detailed error in the flow:
![Image](https://github.com/user-attachments/assets/b49d5720-3cec-45a5-84e1-5656c2ecf4c7)

Step "RetryLogic-AuditLogRecords"
InvalidTemplate. Unable to process template language expressions for action 'RetryLogic-AuditLogRecords' at line '1' and column '11757': 'The template language expression 'equals(outputs('AuditLogRecords')['statusCode'], 200)' cannot be evaluated because property 'statusCode' cannot be selected. Please see https://aka.ms/logicexpressions for usage details.'.

Step"AuditLogRecords"
InvalidTemplate. Unable to process template language expressions in action 'AuditLogRecords' inputs at line '0' and column '0': 'Required property 'uri' expects a value but got null. Path ''.'.

Can you please advise on solving the error? Thank you very much.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2024 4.43

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Have you done the step to start the subscription? 

Please see [Start a subscription to audit log content](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

I've also seen this fail for people if they do not remove the delegated version, if you try turning on the subscription and that does not work, please try removing this unused delegated version of the permissions.
![Image](https://github.com/user-attachments/assets/b02b2faf-9140-4136-ad27-8ad88b090e3b)

**Comment by PatrickGroen1** [comment]
Thank you for your clear response, Jenefer. The subscription to audit log content run successfully (LastRunPassed: Yes). We removed the unused delegated permission (Revoke admin consent). We turned on the Admin | Audit Logs | Sync Audit Logs (V2) flow and manually started the flow. After 2 minutes and 30 seconds the flow failed again with the same error in the action AuditLogQuery: {"message":"App:**** dont have any permissions"}. 

Are there other options to investigate and solve the error?

**Comment by Jenefer-Monroe** [comment]
Can you please share

**Comment by PatrickGroen1** [comment]
Please find the values in screenprint below. ![Image](https://github.com/user-attachments/assets/fdbc6c29-c6c4-4e3d-9f71-250c4a668f7d)

**Comment by Jenefer-Monroe** [comment]
I see. You have set up the permissions in your app registration for the [Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http) but have selected via that last environment variable to use the [Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)

I presume you intended to use the Office 365 Management API, if so please set that last env var to no and restart the flow. 
If you intended to use the Graph API, you will need to update the app registration per the [Graph API setup instructions](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)

**Comment by PatrickGroen1** [comment]
Thank you! After I set the environment variable to No indeed the flow succeeded. I will take a look into the Graph API setup. 

This issue can be closed as it is resolved for now.
