### ISSUE TITLE
[CoE Starter Kit - BUG] Error when launching CoE Apps after upgrade to Version 4.43

### ISSUE THREAD

**Issue by BimzK** [microsoft/coe-starter-kit#9165]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

Last week I did an upgrade on my CoE toolkit to version 4.43 from 4.24. Everything seemed to be working fine when I did the testing after the upgrade until yesterday when I logged in to access the app during our Power Platform Workshop and found that I am getting this error message: 

 Error Code: AppMetadataParserFailed
Session Id: 12506a10-124e-494f-be3c-0f50bf4423b7
Activity Id: 5b1be02c-cf52-464c-939b-d72a8f8261a4
Timestamp: Wed Oct 23 2024 10:47:53 GMT+1300 (New Zealand Daylight Time)
AppLogicalName admin_commandcentermakerapps_92d6f does not have an AppPackage
UciError: AppLogicalName admin_commandcentermakerapps_92d6f does not have an AppPackage at s (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.0c7878b883ed40c9f612f6466aa636cf.js:33:955344) at https://content.powerapps.com/resource/uci-infra-bus/scripts/custompage.3901e0831f0df9c3c77c4f574984ed80.js:4:23208

I tried searching the github and found a similar case which is now closed : https://github.com/microsoft/coe-starter-kit/issues/9140, but in this case the user had to start all over. 

I have tested this over different browsers, different accounts and on different machines but it gives the same error every time. 
Can some one please assist me with resolving this issue? 

Thanks in Advance!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

All apps in CoE Toolkit

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, other users hit this as well. It was some bug in the upgrade process. Please see https://github.com/microsoft/coe-starter-kit/issues/9056

They fixed it by doing a classic overwrite re-install. Please see https://github.com/microsoft/coe-starter-kit/issues/9056#issuecomment-2386439537

So you wont need to start over in a new environment, just upgrade again in the technique shown in that comment.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
