### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by MuSantana1** [microsoft/coe-starter-kit#9166]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I use a "service account" to import the CoE Solutions and configure them. If I remove interactive logon for that account once I'm done with the setup, will it cause any problems?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

N/A

### What app or flow are you having the issue with?

N/A

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
By service account, you do not mean app registration correct? You mean some shared user type account? 

I've never tested with removing interactive login from regular users, so I presume you mean a service principle?

**Comment by MuSantana1** [comment]
It's one of those shared user type accounts (we call those "service accounts"). We use that account to manually import the managed solution into our environments - is this the best approach?

Or is it better to import the unmanaged solution into a "Dev" environment and automate the deployments using pipelines?

**Comment by Jenefer-Monroe** [comment]
Yes thats what I call them too :) I was just confused as I have never put such a user into interactive mode. 
And yes you are doing the correct approach now. 

This is a good idea to put the user in interactive mode but I've never tested it. Can you try it and let me know how it goes? And how to put a user into that mode too haha.

Thank you!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
