### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by mwiecm** [microsoft/coe-starter-kit#9167]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

According to article https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup#which-identity-should-i-use-to-install-the-coe-starter-kit
identity should have:
Power Apps Per User license (nontrial) and Microsoft 365 license.
Power Automate Per User license, or Per Flow licenses (nontrial).

Should we licensing other users who are using only Power BI reports provided by CoE?
Does utilization of Power BI CoE by users without a license for Power Apps of Power Automate generate multiplexing issues?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I am not a licensing expert, especially for Power BI, so I cannot comment on the multiplexing on that side. 

However I can tell you that you will need Power Apps Premium licenses for users that need access to the apps in the kit. 
So other admins that want to view Power Platform Admin View app, or Makers with whom you want to share the Developer Compliance Center, they would need PowerApps Premium as the data is stored in Dataverse. 

Hope that makes sense.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
