### ISSUE TITLE
[CoE Starter Kit - QUESTION] Copilot Studio overview page on the CoE Dashboard

### ISSUE THREAD

**Issue by zellos13** [microsoft/coe-starter-kit#9168]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello,

In our organization, we are investigating Copilot Studio and we found out that in CoE Starter Kit Dashboard, there should be a report showing Copilot Studio overview. Here is a link to the article [link](https://learn.microsoft.com/en-us/microsoft-copilot-studio/admin-data-loss-prevention#use-auditing-or-soft-mode-to-see-dlp-errors-in-the-copilot-studio-web-or-teams-apps). In there, you can find the screenshot from the report.

I can't find this page in any of CoE Starter Kit Power Bi dashboards. Can you tell me if this is even there, or it was just one time thing and now it's not available in the CoE package?

Cheers,
Daniel

### What solution are you experiencing the issue with?

None

### What solution version are you using?

May 2024

### What app or flow are you having the issue with?

Copilot Studio overview page on the CoE Dashboard

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I believe you will find these referenced as bots in your PBIT file. Can you please take a look?
![Image](https://github.com/user-attachments/assets/1206e395-4507-4b6c-a5d1-2aecca4e59c4)

**Comment by Jenefer-Monroe** [comment]
I believe that is the same content we just did a pass on the visuals. So the coloration is "bot" colored, and the per envt is a bar chart instead of pie, etc. Please let me know if there is something specific missing.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
