### ISSUE TITLE
Envt Keep Alive - we check for states (ex PCF) for all envts, even ones excused from inventory

### ISSUE THREAD

**Issue by Jenefer-Monroe** [microsoft/coe-starter-kit#9169]
### Is your feature request related to a problem? Please describe.

Per https://github.com/microsoft/coe-starter-kit/issues/5968 we are using "excuse from inventory" as the temporary workaround to the keep alive problem while we await the connector solution from product team.

However we check for things like PCF before we look to see if the envt is excused.

### Describe the solution you'd like

Will need to figure out the best way here. We need to check for new evnts etc... Will experiment and get this fixed for Nov

**Comment by Jenefer-Monroe** [comment]
We wanted to make the most minimal change possible so we are only skipping the org check for excused environments. 
Here is the change. Can you please test? 

1. `@outputs('Excused_From_Inventory')`

![Image](https://github.com/user-attachments/assets/720f648a-c245-4c3d-80e6-461e747dfcb3)

**Comment by millsmi** [comment]
@Jenefer-Monroe I don't think this solution will work for us.  We are regulated and we do get audited, so we need to provide evidence that all environments are being scanned and inventory is up to date, hygiene is the other requirement which we did recently get audited on (for Power BI this time), we can't exclude environments which are being used in the business.  I hope this makes sense.

**Comment by Jenefer-Monroe** [comment]
yes it does make sense. For you then, you will need to wait for the official solution from the product team in which they will grant us a way to make these calls "silently" with regards to keep alive pings.

**Comment by KRhoadesHyp** [comment]
@Jenefer-Monroe I made the changes and will check back tomorrow.  We have 11 environments currently excused from inventory so I will check activity dates tomorrow to see if this reflects the change.  Thanks!

**Comment by Jenefer-Monroe** [comment]
Thank you! I'm worried that the escalation may keep alive too but I dont think so. Then if so I'll need to sort out what to do there

**Comment by Jenefer-Monroe** [comment]
Hey folks. Any update on this? I'm code complete for the Nov release right now but want to make sure I didnt keep these alive for you.

**Comment by Jenefer-Monroe** [comment]
One more spot to put the check
![Image](https://github.com/user-attachments/assets/a6e1e241-474d-453e-953a-7f3640eb2b94)

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload

**Comment by millsmi** [comment]
@Jenefer-Monroe It might be that Microsoft have fixed the 'Environment last activity' issue themselves.  Since the 16th October, the last activity indicator has started working for all environment types (Developer, Sandbox, Teams etc).  We have done nothing on our side, it just started working.  I am wondering if this is part of the Release Wave 2 work or getting some bugs fixed before Ignite.

**Comment by millsmi** [comment]
@KRhoadesHyp Forget it, looks like Microsoft just reverted several features including;  Security hub (the preview screen), the 8th environment group rule and environment last activities are all again showing todays date.

**Comment by KRhoadesHyp** [comment]
@millsmi 

Had you updated your CoE with the November update?  We haven't updated yet, curious if you are seeing it even with the fix.  Can confirm, November 3 Last Activity :-(
