### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Admin View app no longer allows you to change the owner of a flow or app

### ISSUE THREAD

**Issue by AUTigers16** [microsoft/coe-starter-kit#9172]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I have already been communicating with Jenefer via email, but the Power Platform Admin view app no longer allows you to change the derived owner of a flow. I went ahead and checked changing the owner of an app and it doesn't allow you to change the owner of an app either. I am not able to post images but have provided them to Jenefer.

### Expected Behavior

Go to flows section of the app and when clicking on Manage Permissions, have the ability to assign owner to a user.
For apps, manage permissions does not come up just check access.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Power Platform Admin View app

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Search for Flow
2. Click Manage Permission in the ribbon
3. Select a user and click change permissions
4. User role should display owner or it used to it no longer does.

**Comment by Jenefer-Monroe** [comment]
I don't know who took this away but I've got it back in there now.

![Image](https://github.com/user-attachments/assets/1e30914c-0e2f-43b8-b7b9-8ae9cdb80981)

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload
