### ISSUE TITLE
[CoE Starter Kit - BUG] This is regarding previous GitHub case "[CoE Starter Kit - BUG] Data Mismatch error #8960"

### ISSUE THREAD

**Issue by rashibhalla** [microsoft/coe-starter-kit#9174]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

This is regarding our previous GITGUB case "[CoE Starter Kit - BUG] Data Mismatch error #8960"

As mentioned, we have updated COEToolkit however the flow is still not running. Please check why my CoEToolkit is not refreshed, which flow I should pay attention to.

### Expected Behavior

CoE Starter kit data should match with environment consumption data from Power Platform admin portal.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

NA

### What app or flow are you having the issue with?

Data in CoE Toolkit

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

Export the dataverse consumption data from CoE Toolkit and Export the data from Power Platform admin portal
compare the data and it shows data from CoE toolkit is consistent where data in Power Platform admin portal is gradually increasing

### Anything else?

No

**Comment by Jenefer-Monroe** [comment]
Hello. 
In our last correspondence I had asked you to boot the setup wizard to ensure all the flows were on, as most of your flows were turned off. 
Have you done that? 

You are on an older build of the kit at this point as well, one that is missing some changes for product work. So I suggest you upgrade at this point, and then boot the setup wizard.

**Comment by rashibhalla** [comment]
Yes, we have upgraded the COEToolkit already however the flows are still not running after upgrade.

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

Please also confirm that you booted and walked through the Setup Wizard

**Comment by rashibhalla** [comment]
Hi Jennifer,

Please find requested screenshot attached.

[cid:a910c93f-0e37-4aaf-9a98-c69e887cebd4]



Thanks & Regards

Rashi Bhalla

AIA MW Support




[AIA - INTERNAL]

________________________________

**Comment by rashibhalla** [comment]
Hi Jennifer,

I am not able to attach the screenshot.  Tried in JPEG and PNG format both. it says failed to upload. Is there any other way to share screenshot? via email?

**Comment by Jenefer-Monroe** [comment]
Strange, you were able to in the past. You may need to look in GitHub support for that. 

Before you had the following. Can you confirm, do you still have only a single instance of Core Components in the list? Sometimes there will be multiple listed if the upgrade failed. 
And what is the version? 
Lastly please confirm: **_did you walk through the setup wizard?_**
![Image](https://github.com/user-attachments/assets/04dc3fd8-5c9b-4f60-a487-907c108ec2e3)

**Comment by Jenefer-Monroe** [comment]
Please try to turn them on manually via the product itself. You can find the required order to turn them on in the CoE Solution Metadata table. 
Go to the table, ensure you have ObjectName, ObjectType, CoESolutionArea, and InstallOrder showing.
Filter ObjectType to CloudFlows
Filter CoESolutionArea to Inventory
Sort InstallOrder Smaller to Larger.
Try to turn the flows on in that order and let me know what error you see.

![Image](https://github.com/user-attachments/assets/ee7d1aa6-e510-4cd4-8b2e-3ff1a25b38bb)

**Comment by rashibhalla** [comment]
Hi Jennifer,

I've turned on the flows as mentioned above without any errors. Sorry unable to attach the screenshot. what will be next step?

**Comment by Jenefer-Monroe** [comment]
Great so you your inventory should start getting filled. 
Please watch for errors in

**Comment by rashibhalla** [comment]
Hi jennifer

We found 4 distinct flows showing errors on the "CoE Admin Command Center > Active Sync Flow Errors" page. They are
Admin | Sync Template v3 (Connector)
Admin | Sync Template v3 CoE Solution Metadata
Admin | Sync Template v3 (Sync Flow Errors)
SetupWizard > Update InventoryTypeAppSetting
Upon closer inspection, we are able to resolve the errors on three of those flows by re-establishing the connector credentials, however we are still blocked on "Admin | Sync Template v3 (Sync Flow Errors)". It is timing out on execution of the child flow step "Send Sync Flows to admin". But when attempting to troubleshot that, we are unable to find the referenced child flow "HELPER ,Send Email" from the "COE Core Components Solution > Cloud Flow" list. 
Also despite the other sync flows being able to execute, the "Last Modified" column of COE Table "Environment Capacity"  value is still not updating to the latest date.
Please help us with
- Troubleshooting advice for "Admin | Sync Template v3 (Sync Flow Errors)", especially where to find the child flow
- What other troubleshooting is needed for "Environment Capacity" to correctly update to latest data

**Comment by Jenefer-Monroe** [comment]
It sounds like you are still not correctly configured. I'm not sure if we will be able to resolve this without screenshots as I just cannot see what's happening in your tenant. 
Many flows will not run correctly without the Send Email helper turned on. 
The Metadata flow needs to pass in order for anything to be running correctly, 
And without connector running correctly your inventory will not resolve either. 

I suggest you please attempt to work with GitHub to resovle your issue with adding screenshots
