### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by folkestad96** [microsoft/coe-starter-kit#9178]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi,
I am trying to activate Audit logs for COE and wish to use the client azure secret.  Please help me to understand how the flow 
"Admin | Audit Logs | Office 365 Management API Subscription" works with dataverse action "Get Azure Secret" compared to just write the Client Secret directly in the COE Environment Variables in the COE Admin Command Center. Is the output from the dataverse action supossed to be the exact same secret value to be used in the HTTP Post action later on or are they supposed to be different?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

September 2024 4.43

### What app or flow are you having the issue with?

Admin | Audit Logs | Office 365 Management API Subscription

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I'm not entirely following your question. Can you please tell me, which setup are you using? 

[Graph API setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)
[Office 365 Management API setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by folkestad96** [comment]
Graph API

**Comment by Jenefer-Monroe** [comment]
ok fort the GraphAPI side you do not need to start the subscription. That is for the Office365Management API. 
You need to Turn search on as shown below, but the api for graph does not need turned on explicitly outside of the other steps outlined in the setup documentation. [Graph API setup](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)

![Image](https://github.com/user-attachments/assets/114a415f-1317-4f99-a0ec-6a804d517e18)

**Comment by folkestad96** [comment]
The audit log is turned on, since it works when I am using client secret in plain text

**Comment by folkestad96** [comment]
When I am using Client Secret as plain text it works fine, when I am trying to use Client Azure Secret I get an error in the sync audit logs flow.
Use Graph API env variable is set to yes and I get the error below.

It must be something that I am missing

Unable to process template language expressions for action 'RetryLogic-StartAuditLogQuery' at line '1' and column '11901': 'The template language expression 'equals(outputs('AuditLogQuery')['statusCode'], 201)' cannot be evaluated because property 'statusCode' cannot be selected. Please see https://aka.ms/logicexpressions for usage details.'.

**Comment by folkestad96** [comment]
Using the Graph API

The flow "Admin | Audit Logs | Office 365 Management API Subscription" is working and succeeds

"Admin | Audit Logs | Sync Audit Logs (V2)" fails and I get the error
![Image](https://github.com/user-attachments/assets/22ec4f3d-03c2-453d-aa52-1d8ea2649e9e)

**Comment by folkestad96** [comment]
that Env variable is set to yes
![Image](https://github.com/user-attachments/assets/be215f2c-fc9f-4a29-aad1-b462615c4be8)

But it fails when using Client Azure Secret

**Comment by Jenefer-Monroe** [comment]
Please restart the flow, and run it again. 
Failing to get the Azure secret is fine, its a caught error that we use to set a variable which indicates you are using plain text for secret. I'll share a picture of what that means below. 

If after restart you still see the flow fail you will need to share a screenshot of where it fails later in the flow

## Azure failure but not using azure secret
You are not using Azure Key Vault so this failure is expected and caught. 
Note that flow always shows the first failure even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

**Comment by folkestad96** [comment]
![Image](https://github.com/user-attachments/assets/574af285-28ab-4416-8f12-db6459923128)

**Comment by Jenefer-Monroe** [comment]
Please validate that you have used used the secret value for the environment variable, not the secret GUID. 
Thats something people do fairly often
![image](https://user-images.githubusercontent.com/89584709/225953435-8d2d5b8c-1fdd-4e24-92c0-e4618c23f1fa.png)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
