### ISSUE TITLE
[CoE Starter Kit - BUG] App Deleted Flag is not updated in admin_app table

### ISSUE THREAD

**Issue by ALSPowerPlatform** [microsoft/coe-starter-kit#9181]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Its been 4 days, we deleted 900+ apps and the app deleted flag is still shows as No in admin_app table, Please let us know which flow is responsible to update this app deleted flag and on what frequency the flow runs in COE to update this data.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.22

### What app or flow are you having the issue with?

Apps

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello. When objects are deleted from the tenant, they get marked deleted in the inventory when the following flow is run, along with its helpers: **_CLEANUP - Admin | Sync Template v4 (Check Deleted)_**

This is a long running flow and so it only runs once per week.

**Comment by ALSPowerPlatform** [comment]
Thankyou , this helps, and the deleted apps will be deleted from dataverse admin_app soon?

**Comment by Jenefer-Monroe** [comment]
Objects will stay in this state, marked as deleted from inventory, for ~2 months. This is to allow the record to be restored with its metadata in the event the object itself is restored in the tenant. 

At that point, once restore is no longer possible in the tenant, then the records themselves are deleted from the inventory tables as well. 

While they are in the "marked deleted" state they can be viewed in the kit using selecting that view for all the objects as shown here for apps.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/42ae9af2-6bb5-49fe-afba-838d5f925c68)

**Why keep them around for two months?** 
Here is the scenario we are supporting by keeping these around

- Flow X created in tenant
- Flow X added to the CoE inventory tables
- Flow X marked as exempt from inactivity processing in the CoE
- Flow X deleted from tenant
- Flow X marked as deleted in CoE inventory tables
- Flow X restored in tenant
- Flow X unmarked deleted in CoE inventory tables, exemption from inactivity processing remains in place.

**I need these records to stay in perpetuity**
We have an env var, _Also Delete from CoE_, which allows you to prevent the deletion from the inventory tables. Default behavior (yes) described above, but if you set it to no then these records will never be deleted by the kit

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/af05bf15-e937-4032-9eab-e4d290108147)


**I don't want these records sitting around at all**
If you want the deletion from inventory to occur immediately, or at some other cadence like 6 months, then you will need to create your own flow on the side to do this. You can use the mechanism used in _CLEANUP - Admin | Sync Template v4 (Check Deleted)_ as a template for how to do this.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/187ec89f-77d7-48d4-8fb3-ca6df9b704d5)

**Comment by ALSPowerPlatform** [comment]
Thanks so much, clear.

**Comment by Jenefer-Monroe** [comment]
Wonderful, I'll go ahead and close out then. Thanks for using CoE
