### ISSUE TITLE
[CoE Starter Kit - QUESTION] Licensing

### ISSUE THREAD

**Issue by TOM-DBG** [microsoft/coe-starter-kit#9183]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello Everyone !

I hope you are doing well!

We are using CoE Starter Kit for inventory process now and would like to expand to use other features.

We don't want to license all the makers as Premium licenses are something we can't afford this FY (we do have the required premium licenses for account running CoE components and admins).

Could someone help us with what features can be used without giving premium licensing to the makers.

I was hoping the Orphaned Process and Inactivity Process could work but could someone confirm on this please.

Thanks,
Tom

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

September 2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Basically they cannot interact with a canvas app unless they have a premium license. 

Both teams card integration (the orphan processes) and approvals (the inactivity processes) allow users to interact with you without having direct access to the premium connectors. 

Those are really he only two that have such things in place. 
Hope that helps!

**Comment by TOM-DBG** [comment]
Thanks Jenefer!
