### ISSUE TITLE
[CoE Starter Kit - QUESTION] Fetching App Shared Info for Apps in Specific Environments

### ISSUE THREAD

**Issue by TOM-DBG** [microsoft/coe-starter-kit#9184]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello Team,

Is there an easy way we can get the App Shared Users List of All Apps inside an Environment using CoE Starter Kit. Currently I could see we do have an option in Admin View to go inside each environment and export for each apps. Since this is time consuming and in some scenarios, we have App Shared with groups as well, is there an easy way to fetch this information.

Thanks in advance!

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
You can use the Power Platform User Roles table to do this. You will have to do it just for Apps or Flows, you wont be able to get info about both at the same time with this technique. 
Please let me know if that is what you were looking for. 

Go to that table in Power Platform Admin View app > 
1. Add epp envt : Edit columns > Add columns > Related > App (PowerApps App) > App Environment (App)
2. Add Power Platform User: Edit columns > Add columns > Power Platform User
![Image](https://github.com/user-attachments/assets/68b6f090-7c06-4297-9096-7f0a631a790d)
![Image](https://github.com/user-attachments/assets/fe600bca-f7b1-469f-bfb4-82a709593e82)
![Image](https://github.com/user-attachments/assets/16ba74bf-cd50-48db-9e5a-9b2803b264d6)

Now you can filter by environment
![Image](https://github.com/user-attachments/assets/be0beac9-c00d-440b-b984-e391c5e9cfb2)

**Comment by TOM-DBG** [comment]
Thanks a lot Jenefer, this helps :)
