### ISSUE TITLE
How to deal with API hit from the kit?

### ISSUE THREAD

**Issue by jchwila** [microsoft/coe-starter-kit#9185]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

After implementing CoE Starter kit in medium size tenant the dedicated service account under which all flows are run is consuming 100-400k api request daily. What is the recommended approach when Microsoft will start enforcing api limits? Typically power automate premium license provides 48000 daily api calls. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

September 2024

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Yes we recognize the impact of the kit on API counts for flow. 
First note that the product team is working on having native inventory and administration features for you to use OOB in [PPAC](https://admin.powerplatform.microsoft.com/)
Then we are also working with the product team on a feature called Data Export which will allow you to extend those capabilities using the kit in the future. That feature is in private preview and we will be letting you know status as we go in the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours). 
Until then you will need either need to purchase process licenses if the flows time out. However even our large tenants are able to do their inventory without process licenses today so hopefully you are ok.

**Comment by jchwila** [comment]
Thanks Jenefer for thorough answer!
