### ISSUE TITLE
[CoE Starter Kit - BUG] Setup Wizard Communication Method

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#9189]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

We are seeing an error when trying to add the 3 communication groups in the Setup wizard. This is a completely clean install of the CoE Starter Kit 

![Image](https://github.com/user-attachments/assets/f677c2b3-7453-41a4-b886-181ab9c4cf21)

Office365Groups.ListGroups failed: { "error": { "code": "Request_BadRequest", "message": "Invalid object identifier '<pii>PowerPlatformUsers</pii>@abc.com'.", "innerError": { "date": "2024-10-28T13:25:41", "request-id": "e87fcc8c-9d68-47a0-97ba-8de5ae368320", "client-request-id": "e87fcc8c-9d68-47a0-97ba-8de5ae368320" } } }

### Expected Behavior

Accept the M365 Groups defined as the Admin, Maker and user groups.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Setup Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Can you please share how you entered the values? If you cannot find your groups in the dropdown, for Maker and User they are supposed to be entered as GUIDs not emails.

![Image](https://github.com/user-attachments/assets/8688bead-9842-4af3-832e-2394a743b6d3)

**Comment by myatix** [comment]
@Jenefer-Monroe Thanks for the feedback... It seems to work with the email for the Admin but not the others... Then I used the Group GUID then it worked. 👍

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
