### ISSUE TITLE
[CoE Starter Kit - BUG] Sync Audit Logs V2 - Not Capturing all Audit Logs due to minimal delay

### ISSUE THREAD

**Issue by michael-wright-pwc** [microsoft/coe-starter-kit#9190]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Currently, the Sync Audit Logs V2 flow triggers every hour and gathers audit logs from 65 minutes before the trigger time up to the trigger time. The problem with that is not all logs are available in Purview within 1 hour, so this approach is not capturing all logs. I did some experimenting with this recently and found that only 80% or so of Power Platform logs are collected in the 1st hour, 95% of logs within 24 hours, 99.8% of logs within 48 hours, and 100% of logs after 7 days.

https://learn.microsoft.com/en-us/purview/audit-search?tabs=microsoft-purview-portal#before-you-search-the-audit-log confirms this:
- "Microsoft doesn't guarantee a specific time after an event occurs for the corresponding audit record to be returned in the results of an audit log search. For core services (such as Exchange, SharePoint, OneDrive, and Teams), audit record availability is typically 60 to 90 minutes after an event occurs. For other services, audit record availability may be longer."

For this reason, I'd like to request you create an environment variable called something like "Audit Logs - Delay in Hours", then modify the Sync Audit Logs V2 flow "startTime variable" and "endTime variable" actions to additionally delay in hours by the value of this new variable. With this approach, different customers can easily configure the delay they prefer in the env var without needing to create an unmanaged layer directly on the flow.

It may also be worth updating your docs to explain this variable is a tradeoff between speed of data (how quickly usage data is seen in reporting) & completeness of data (what % of audit logs are we collecting) so clients can make a more educated decision.

For our company (PwC), we find the ideal balance at 48 hours, as thoroughness of data is more important than speed of data (but waiting the extra 5 days to get the extra 0.2% isn't worth that additional delay for app launches). I would suspect most other clients would agree with this number as a reasonable approach, and would suggest you consider setting the default value of this new env var to 48 (or at the lowest, 24). 

### Expected Behavior

A greater % of audit logs are captured.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Thanks for the suggestion. Do note that we cannot change the run frequency with an env var. So this would still run every hour and reprocess logs and hence cause an API hit unless you change the recurrence manually. 
![Image](https://github.com/user-attachments/assets/659a2480-1d0f-4ac9-b595-e50e8d8a8e1c)

I did go ahead and create the env var for you though. So please note that if you have this look back 48 hours in a large tenant, then you will likely either need to change the run frequency to be ~daily or add a process license.
![Image](https://github.com/user-attachments/assets/ac73bd7f-a03f-47c9-a68b-178c1f7c8b42)

**Comment by michael-wright-pwc** [comment]
So the window is always 1 hour, it's just a matter of how far back the 1 hour window goes (immediately as currently implemented, or a 1 hour window 24 hours ago, or a 1 hour window 48 hours ago, etc.). But each flow run still represents 1 hour's worth of logs.

**Comment by Jenefer-Monroe** [comment]
Oh I see. So you would never have current data, meaning the data would always be ~2 days old. Is that what you mean?

**Comment by michael-wright-pwc** [comment]
Correct - that's what I meant above about the tradeoff between data completeness (more of a delay) & data speed (less of a delay). I think the solution you mentioned above is the ideal case to get both aspects together (speed & completeness), but as you mentioned it'll blow up the dataverse calls & flow PP request limits.

**Comment by michael-wright-pwc** [comment]
I suppose if you wanted to leave that door open for smaller tenants you could have 2 env vars - one for start delay in mins & one for end delay in mins. Then clients can set is it 49 hours ago to 48 hours ago (as we'd do), or 49 hours ago to 0 hours ago (as smaller tenants might do), or 49 hours ago to 24 hours ago if you want some overlap, etc. It introduces more complexity to the solution which isn't always great but offers more customization. Totally your call.

**Comment by Jenefer-Monroe** [comment]
ok I get it, thanks! This is a great idea. 

Here is the env var then. 
![Image](https://github.com/user-attachments/assets/72763e0c-e4af-45b9-98d4-a4e8442905c6)

I went ahead and made the hour configurable too
![Image](https://github.com/user-attachments/assets/c42069ac-427f-4533-90a3-8dcafa996a31)


And here is the flow

**Comment by michael-wright-pwc** [comment]
This looks fantastic! And I don't have an intimate knowledge of the Sync Audit Logs V2 flow, but just confirming - there's no harm in collecting the same audit logs multiple times right? Like there won't be duplicate events in the audit logs table?

**Comment by michael-wright-pwc** [comment]
That's fantastic! Thanks Jenefer you rock as always!!!

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload

**Comment by Martijnsmeitink** [comment]
Thanks for this insight & update. Never realised we might be missing entries from the audit log as they might not have made it there yet.

Want to ask one thing though, is this already compatible with using the Graph API method? 
Using the Graph API method my "sync audit logs (v2)" errors out. The "AuditLogQuery gives me a Status code 400 and the accompanying message body contains: "  "message": "Invalid request data", 

  ![Image](https://github.com/user-attachments/assets/811ca957-c57d-46d3-acff-415dd9974210)

This is with leaving the "Audit logs - minutes to look back" untouched and "Audit logs - End Time Minutes Ago" tested with a value of 1410 and 2820.

After reverting back to default the flow runs again, so I'll for now leave it at that :-)
This is with the November release by the way.

**Comment by DarkestOfNights** [comment]
There's a bug in how the start time is calculated. The start time was left as-is: addMinutes(utcNow(), outputs('start_time_minutes_back')) rather than using minutes back from the end time, making filterEndDateTime < filterStartDateTime, causing that error. I just tested out using desired look back + end time value successfully at least until this is resolved (so 1440 end time and 1505 look-back for 24 hours with 65 minute look-back for example).

**Comment by Martijnsmeitink** [comment]
Realizing the ticket is closed, so tagging @Jenefer-Monroe. Thanks for your work on this! Looks like @DarkestOfNights found a bug after the ticket was closed. Do you need me to raise a new one, or can you look at the above?

**Comment by Jenefer-Monroe** [comment]
hey sorry I did not see this comment. Plesae do post a new issue for me if it repros in the Nov release.
