### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by harshshah126** [microsoft/coe-starter-kit#9192]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hello 

I have an issue when i updated CoE Kit to Sept version with the following flow

Admin | Audit Logs | Sync Audit Logs (V2) - Error occured while reading secret: Value cannot be null.
Parameter name: input

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.0.20230727.2

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2) 

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Note that flow always shows the first failure even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

Can you please validate the following
1. Which api are you using for the audit log? 
- [Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)
- [Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)
2. Are you storing your app registration in Azure Key Vault? Or as plain text.

**Comment by harshshah126** [comment]
> Note that flow always shows the first failure even if its a caught failure, so you need to go further down in the flow to find the flow actually terminates (fails) the flow
> 
> ![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)
> 
> Can you please validate the following
> 
> 1. Which api are you using for the audit log?
> 
> * [Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)
> * [Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)
> 
> 2. Are you storing your app registration in Azure Key Vault? Or as plain text!


I uploaded  where its "Failing"  
>[Image](https://github.com/user-attachments/assets/bbaf50a2-c368-44e9-b406-11484a506606)

**Comment by Jenefer-Monroe** [comment]
sorry I'm not seeing any failure.

**Comment by harshshah126** [comment]
![Image](https://github.com/user-attachments/assets/e26f0795-399a-4834-a344-785a9c246802)

**Comment by Jenefer-Monroe** [comment]
Are you storing your secret in Azure or as plain text?

**Comment by harshshah126** [comment]
Plain text, we not using Azure Key Vault

**Comment by Jenefer-Monroe** [comment]
ok then this is an expected and caught failure. You will see that when this failure occurs the next thing that happens is the varaible below is set by catching that failure
 ![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

Which api are you using for the audit log?

- [Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)
- [Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by harshshah126** [comment]
How to fix the issue?

I'm using Graph API

**Comment by Jenefer-Monroe** [comment]
I still dont know where you are failing but I can take a guess based on what is typically wrong. 

1. Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated.
![Image](https://github.com/user-attachments/assets/392bb125-4656-4069-90c6-ce833767dc73)

2. Please be sure that you have entered the secret itself and not the secret id (the GUID). It’s a longer string with a larger character set than a GUID. This one has a tilda for example.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/983a39fb-0b23-4d1f-83d5-8b41bb2bf270)

3. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

4. Turn the flows off and back on. Sometimes env vars get stuck in them with old values

**Comment by harshshah126** [comment]
Hello this is what i have as API Permissions and for Azure Secret Value

Also, I turned off and turned back on the flow ![Image](https://github.com/user-attachments/assets/c84292cd-4104-493c-be2b-e1babdfedccb)
![Image](https://github.com/user-attachments/assets/964d400e-2cc0-4877-9428-4108ba251f95)

**Comment by Jenefer-Monroe** [comment]
3. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

**Comment by harshshah126** [comment]
Yes

**Comment by Jenefer-Monroe** [comment]
What value you do have for the last one? Use Graph API

**Comment by harshshah126** [comment]
Looks like i dont have anything there?

I just use the url ![Image](https://github.com/user-attachments/assets/3822dc09-2299-4fed-9965-aa92b1588424)

**Comment by harshshah126** [comment]
![Image](https://github.com/user-attachments/assets/78b88d82-9bd4-4ea0-8cb0-06d8f733543e)

**Comment by Jenefer-Monroe** [comment]
ok you did not set this env var to yes so its looking for data from the other API
![Image](https://github.com/user-attachments/assets/fbcc1609-1f00-4549-b144-a1dac9e59ca4)

Please make sure you update all the env vars from the instructions: [Update environment variables](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi#update-environment-variables)
Then restart the flow and try again.

**Comment by harshshah126** [comment]
The environment variables worked
