### ISSUE TITLE
[CoE Starter Kit - BUG] Environment Capacity capture dates are off by one day

### ISSUE THREAD

**Issue by PPCan** [microsoft/coe-starter-kit#9194]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Not sure what's going on, but it looks like the modified date is AFTER the capacity updated on date.  Is this supposed to be the way it works?

We are taking snap shots of the environment capacity data to create a forecasting report and the dates not matching is throwing off the report.

It looks like the dates started to be different around August 4th... 

Any thoughts..? 

![Image](https://github.com/user-attachments/assets/3713898e-028f-4f9c-aa40-0498ccfc14af)
![Image](https://github.com/user-attachments/assets/0722fd85-3dc1-461c-923c-6d18dbe5fe6f)

### Expected Behavior

Dates for modified and capacity updated should match.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Environment Capacity from Inventory Run

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
We get the value to put in the update field from the **_Power Platform for Admin_** connector's **_List Environments as Admin_** action. See [List Environments as Admin](https://learn.microsoft.com/connectors/powerplatformforadmins/#list-environments-as-admin)

We do this in the **_CLEANUP - Admin | Sync Template v4 (Other Objects)_** flow. 
It looks like it returns UTC time per the format `"updatedOn": "2024-10-26T23:20:03Z"`
![Image](https://github.com/user-attachments/assets/2c5b41e3-6085-4623-9f1c-7b6fe22f84ef)

Whereas both **_Capacity Updated On_** and **_Modified On_** fields from the **_Environment Capacity_** custom table are set to show Local Time. 
![Image](https://github.com/user-attachments/assets/d31dd50b-931c-4ac5-b988-6e57739d5769)

So I think you should be able to extract or infer the UTC version of the time in your custom flows. 
Hope that helps.

**Comment by PPCan** [comment]
Ok. If I understand this properly, the 'capacity updated' timestamp is Zulu and is not adjusted for EST.  Modified is using EST.

**Comment by PPCan** [comment]
@Jenefer-Monroe  Another question on this.  If you look at the report image, you'll notice the zig zag lines after Aug 4 .  That's happening as the environment capacity is not being updated on the same day, which we may have covered.

Was this Zulu issue introduced in the August release? I'm trying to figure out why from Jan until Aug all the environments updated on the same days, and the cumulative totals for the tenant worked.  What's happening is instead of there being a repeatable pattern of all environments on Sunday, some environments are being updated the next day and it's introducing a separate data point the day later.

Hence the zig zag pattern.  Was the Zulu issue introduced, or something else changed in August...?

**Comment by Jenefer-Monroe** [comment]
I'm not sure what you mean by zulu. This z represents that the dt information is coming back in UTC 
"updatedOn": "2024-10-26T23:20:03Z"`
![Image](https://github.com/user-attachments/assets/2c5b41e3-6085-4623-9f1c-7b6fe22f84ef)

I dont think there was a change here but if there was its form the product team's return as we have not changed our flows or our table properties. But that seems unlikely. 

Perhaps you changed the identity who was running the flow? The local time will be in the context of the identity running the flow.
You can extract the value from our tables and convert to UTC though. 

Without understanding your custom process I'm not sure I can help debug the zig zag in your report. 
But I do know that the dataverse table stores the UTC value and just presents the value as local time per that table setting, so you should be able to extract and convert

**Comment by PPCan** [comment]
The 'Z' is Zulu in the timestamp, also known as UTC / GMT. :)  ![Image](https://github.com/user-attachments/assets/ff24eb40-8841-4288-80e6-73c5e7a91b32)

I'll check on the user.  Th toolkit is installed with a Service Account so it should be the same. 

Basically the data is coming from a flow that triggers on the environment capacity table when it is modified. The new flow takes a copy of the modified environment table information and inserts a copy of the information into another table called environment capacity tracking.  It's forward only and inserts a new record every time.  What this does is populate a separate 'tracking' history table of all the environment capacities over time.  Every Sunday.

The report is using this data to create the graph, but as you can see the data is not being saved at the same time for some reason.  I'm questioning the UTC issue there has been no problem since Jan, but as you pointed out maybe something changed on our end.  But it's not that the data isn't being saved, it's just off by a day in some cases.

**Comment by Jenefer-Monroe** [comment]
How funny I've never heard of it referred to that way!
