### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by iamaninda93** [microsoft/coe-starter-kit#9196]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

What are the minimum roles required for an user to access the Power automate flow details, viewing table data?
We dont want to allow users to edit the flow or tables in QA and Production environment. Many of our users wants to access table data for reporting purpose.

I tried gibving them System customizer access but it has edit access.

Thanks.

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Latest Version

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello here are the SR's we ship with the kit. 
https://learn.microsoft.com/power-platform/guidance/coe/core-components#security-roles

The Power Platform Admin View app is intended for the **_Power Platform Admin SR_** which does grant other permissions than read. 
Most people who want to grant read only permissions to the kit give people the Power Platform Admin SR and then share the Power BI file. See [Setup PBI Reports](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
