### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Developer Compliance Center

### ISSUE THREAD

**Issue by KenEddie** [microsoft/coe-starter-kit#9197]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I needed to make a small edit to the form in the developer compliance centre to add some governance criteria. When trying to edit the Developer Compliance Centre App, even without completing an edit, the text in the navigation bar (ActionHeader_1) goes completely clear. When on play the options to select are still there, but are invisible to the end user (see attached)![Image](https://github.com/user-attachments/assets/11958544-21b5-423f-a4dd-0fc5a9b09e98)
![Image](https://github.com/user-attachments/assets/6ca0d2a7-7c5c-4472-a030-7d03c6db6f4a)
. This happens in both dev and prod

### Expected Behavior

I should be able to save the changes to the form without affecting the nav bar

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. edit Developer Compliance Centre
2. push play to preview app
3. navigation bar (ActionHeader_1) goes completely clear

**Comment by Jenefer-Monroe** [comment]
Hello, unfortunately that is not something I can assist with as its a control owned by the creator kit team. 
You will need to post in this repository for help form them. 
https://github.com/microsoft/powercat-creator-kit/issues

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by KenEddie** [comment]
@Jenefer-Monroe I am being pushed back to your team.... are you able to help please?https://github.com/microsoft/powercat-creator-kit/issues/502#issuecomment-2447014223
