### ISSUE TITLE
[CoE Starter Kit - QUESTION] How do to use Power Platform administration planning

### ISSUE THREAD

**Issue by tkudya** [microsoft/coe-starter-kit#9199]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I am starting to use the Power Platform administration planning tool and I wanted to understand abit on how it's supposed to be used. 
1. Are the tasks meant to be assigned to specific people? or that's not a concept in this
2. Are the tasks meant to be opened and closed when they are dealt with? 

### What solution are you experiencing the issue with?

Admin Task Planner

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello have you already found and read this documentation? [Use Microsoft Power Platform administration planning](https://learn.microsoft.com/power-platform/guidance/coe/admin-tasks-component)
