### ISSUE TITLE
[CoE Starter Kit - QUESTION] What's the roadmap for Center of Excellence (CoE) and Starter Kit?

### ISSUE THREAD

**Issue by hbazerbashi** [microsoft/coe-starter-kit#9200]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Is there a general plan or roadmap for the Center of Excellence for Power Platform and the CoE Starter kit in particular?

From my experience, the Center of Excellence is usually used in larger enterprises, and it is important to understand the investment we make in working with the Starter Kit. With time, more features are being added to Managed Environments, closing the gap on missing governance pieces, which raises the question of where the Starter Kit is going.

Also, I noticed there was no release this month (October 2024). We're used to seeing monthly releases. Is there a reason there isn't one this month?

Sorry if this is not the right place to ask these questions. Please let me know if these discussions have been held somewhere else.

Thanks for all the awesome work you do!

Regards,
Hasan :)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. We did not release an Oct release as we were busy working on Data Export V2 integration, something that is not ready to ship yet. Hopefully we will release that Dec or Jan. 

We do plan to release a Nov release though that I am just finalizing which integrates with some product changes. 

For the larger plan for CoE v Managed Envts, that is something we are iterating on now and hope to have some plans next week. We do discuss this in the office hours so please come if you can. 

### Office Hours
Please consider attending our monthly office hours. We talk about new features, upcoming changes, and spend most of the time answering your questions. 
More information:
Join the [CoE Starter Kit Office hours]( https://aka.ms/coeofficehours) held on the second Wednesday of each month between 7:00AM and 8:00AM Pacific time.
Click here to download the calendar file to add to your calendar: [Calendar file](https://aka.ms/coeofficehours/ics)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
