### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Power Platform Governance PowerBI report showing Flows using Plain Text Password

### ISSUE THREAD

**Issue by gargkr** [microsoft/coe-starter-kit#9202]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hello,
We installed the CoE starter kit along with dashboard. Dashboard is showing us the count for "Flows using plain text password". We are not sure what exactly we should look for? We haven't created any flows in our environment who has plain text password.
Also we haven't used HTTP connector  much so definitively its a bug that it says more than 300 places we have used plain text password. 
Please provide more context on this. How we can identify the flows and what causing this report to show  this count. 

Kind Regards
Krishn

### Expected Behavior

Either it should be shown as 0 or very less but not the more than 300 plain text password. or we don't have clue what's causing this. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Power Platform Compliance and Governance Dashboard Power BI report

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Open the CoE Dashboard Governance report
2. Open section Comliance and Governance
4. ![Image](https://github.com/user-attachments/assets/fa3143a7-af44-42bb-871d-b5db381512bc)

**Comment by Jenefer-Monroe** [comment]
Did you spot check a few to validate? Just in case. You can do this by drilling through to flow details
![Image](https://github.com/user-attachments/assets/6e7d8ddf-46af-4c34-b8a1-8309a2d00128)

The only place we touch this column is in the **_Admin | Sync Template v3 (Flow Action Details)_** flow. 
Can you check for failures from that flow or unmanaged layers?

What percentage of your total flow count is this? It could also be that this was manually updated accidently. 
If you clear it back to "No" you can see if it returns.

**Comment by gargkr** [comment]
Hi @Jenefer-Monroe 
I can see that this flow is running without any errors in last 30 days. However, After i updated the CoE to latest version and updated the PowerBI report from November, i could check that there is no count for plain text password. I hope that this is correct now. 

![Image](https://github.com/user-attachments/assets/03ffc348-944a-4600-b790-ea1bd9bd22da)
