### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE - Power BI dashboard update failing

### ISSUE THREAD

**Issue by a8kw** [microsoft/coe-starter-kit#9208]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

We have updated the solutions successfully from Aug-2024 to Oct-2024. But while importing the latest PBIT file (Production_CoEDashboard_September2024.pbit)getting query blocked error.
![Image](https://github.com/user-attachments/assets/5485e5cd-7229-443a-a1e8-2816fda6a61b)

### Expected Behavior

In past we have successfully imported the latest PBIT files every 3 months along with the corresponding solutions.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Production_CoEDashboard_September2024.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open PBI desktop
2. Import the Production_CoEDashboard_September2024.pbit file
3. Input the environment url with Https://
4. Sign in and Import

### Anything else?

![Image](https://github.com/user-attachments/assets/5d59a06a-b523-4d69-8199-8e50df0525c4)

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Jenefer-Monroe** [comment]
Sorry you need to log in to GitHub to share images, responding in email does not share them.

**Comment by a8kw** [comment]
Oh, sorry for delay, was ooo.
Attache dthe screenshots below.[PBIIssue.docx](https://github.com/user-attachments/files/17638929/PBIIssue.docx)

**Comment by a8kw** [comment]
Classification: Internal

Okay, just now uploaded the file in github.
Accidentally I have closed the issue, please reopen it.

Thanks,

Amit Kumar
Power Platform Architect
DPCoE (Digital Productivity CoE<http://digitalproductivity/>)
Pacific Gas & Electric | IT Application Services
Mobile: +1-6025002342 | Email : ***@***.******@***.***>
