### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Center error "does not have an AppPackage"

### ISSUE THREAD

**Issue by MartinWGT** [microsoft/coe-starter-kit#9215]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Started getting an error when opening the Developer Compliance Center. The app cannot be used. This is for all users including the service account that owns the app.
The error points at the 'Developer Compliance Center Canvas App page'.

Error Code: AppMetadataParserFailed

AppLogicalName admin_developercompliancecenterapppage_775de does not have an AppPackage
UciError: AppLogicalName admin_developercompliancecenterapppage_775de does not have an AppPackage at s (https://xxxx.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.9334-2410.2:33:976836) at https://xxxx.crm11.dynamics.com/uclient/scripts/custompage.js?v=1.4.9334-2410.2:4:23193

However, our developer environment works ok. 

![Image](https://github.com/user-attachments/assets/00beedb4-95bf-42e2-a6e1-dc5a700c7c32)

### Expected Behavior

The app should open without any errors.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.25 (September 2024)

### What app or flow are you having the issue with?

Developer Compliance Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Open the Developer Compliance Center app.

**Comment by Jenefer-Monroe** [comment]
Hello, other users hit this as well. It was some bug in the upgrade process. Please see https://github.com/microsoft/coe-starter-kit/issues/9056
They fixed it by doing a classic overwrite re-install. Please see https://github.com/microsoft/coe-starter-kit/issues/9056#issuecomment-2386439537

**Comment by MartinWGT** [comment]
Thanks Jenefer, I will try that.

**Comment by MartinWGT** [comment]
Redploying the Governance solution using the classic method has worked, thank you. https://github.com/microsoft/coe-starter-kit/issues/9056
