### ISSUE TITLE
[CoE Starter Kit - QUESTION] How to get list of Environments Associated with Multiple DLP Policy

### ISSUE THREAD

**Issue by rajamanickamg2** [microsoft/coe-starter-kit#9216]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I would like to generate a report to get the environment names associated with Multiple DLP Policy. Do we have any CoE Feature available like view /Report ? IF we don't have anything ,I would like to create a power automate flow to get those information but guide  me the right table that to fetch those information.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

NA

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Each environment does have the impacting DLPs listed in a field. Its a comma separated list.
![Image](https://github.com/user-attachments/assets/353279a9-7da5-43dc-836d-7581b24a0e63)

Its filled in the driver flow: **_Admin | Sync Template v4 (Driver)_**
![Image](https://github.com/user-attachments/assets/eae17d49-72fb-4331-b8bc-4fb2ed2c06fa)

So you could use this as the basis of a report, hope that helps.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
