### ISSUE TITLE
Please share COE tool kit flow diagram components of it, how it will work, security limitations and how it prevents from internal data leakage.

### ISSUE THREAD

**Issue by Anjaneyulu2347720** [microsoft/coe-starter-kit#9219]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Please share COE tool kit flow diagram components of it, how it will work, security limitations and how it prevents from internal data leakage.

### Expected Behavior

Please share COE tool kit flow diagram components of it, how it will work, security limitations and how it prevents from internal data leakage.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

coe

### What method are you using to get inventory and telemetry?

None

### Anything else?

Please share COE tool kit flow diagram components of it, how it will work, security limitations and how it prevents from internal data leakage.

**Comment by Anjaneyulu2347720** [comment]
Please share COE tool kit flow diagram components of it, how it will work, security limitations and how it prevents from internal data leakage.

**Comment by Anjaneyulu2347720** [comment]
Please schedule a meeting to discuss further on this ticket

**Comment by Jenefer-Monroe** [comment]
Hello, please note the CoE Starter Kit is an unsupported set of templates: https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support. We do best effort to assist our GitHub users but we do not have SLA. 

We are also a very small team with only one person staffing all 12k user installs, so we are not able to have calls with our GitHub users. All investigations would need to be done here with images or descriptions.

**Comment by Jenefer-Monroe** [comment]
Sorry we dont have any such diagram. Do you have specific questions about the way the kit works? Or can you describe more what you are looking for?

**Comment by Anjaneyulu2347720** [comment]
I want away it works

**Comment by Jenefer-Monroe** [comment]
ok unfortunately we don't have a great write up for how the coe kit works as a whole. I suggest you join the office hours and ask this question, we can go over it together there. 

https://aka.ms/coeofficehours

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
