### ISSUE TITLE
[CoE Starter Kit - Dataverse for Teams environment

### ISSUE THREAD

**Issue by raj835** [microsoft/coe-starter-kit#923]
### Describe the issue

How can i test CoE Dataverse for Teams environment without impacting my Production environment .
I do not want to disturb my users on Production while testing it  .Is there any setting/variable to be set so that we can make it  Dev environment and it will not affect anyone in Production .

Please suggest .

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.998

### What app or flow are you having the issue with?

no issue with flow

### Anything else?

We have Power Apps plan 2 license ,will it work for activating the flows ?

**Comment by JeneferM-MSFT** [comment]
I'm afraid I do not have a complete answer for you. You will need to find the flows that send email and not turn them on, or edit them to not send to the end user. 

We do also have an environment variable (ProductionEnvironment) which sends communications to the admin in some flows, but it is not a universally used setting. 

Hope that helps get you started. Thanks for using CoE
