### ISSUE TITLE
Power BI Dashboard not refreshing

### ISSUE THREAD

**Issue by PrasannaKumarPenumarthi** [microsoft/coe-starter-kit#9231]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi,

I am using Power BI Dashboard "Production_CoEDashboard". In Dashboard the "App Usage" report is not showing the latest data. Please help me out what is the issue here.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Power BI Dashboard

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Please go validate the following

1. Do you see the more recent data in the Power Platform Admin View app? 
![Image](https://github.com/user-attachments/assets/8f2005be-dbd6-4414-9efc-c4286479c9c8)

2. Are the Audit Log flows turned on, running, and passing? In particular the two highlighted ones should run regularly. 
![Image](https://github.com/user-attachments/assets/46829dc4-fcb6-4948-889e-ffaeacc4cef2)

**Comment by PrasannaKumarPenumarthi** [comment]
Thanks for your response. I can see the above highlighted flows that were mentioned in the screenshot are turned off in my production environment. Can I please know if there are any implications if we turn on above two highlighted flows that were mentioned in the screenshot above and can you please provide me an description what these two flows will do??

**Comment by Jenefer-Monroe** [comment]
Those are the flows that collect the audit logs (the PowerApp launches). Without these turned on you will not be collecting this data. 

However you cannot just turn them on, the setup requires an app registration. Please see [Collect audit logs using Microsoft Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)

**Comment by PrasannaKumarPenumarthi** [comment]
Thanks for providing the steps. We are happy to follow the steps mentioned in the article. But we would like to understand if these flows are enabled what can be the implications on the data verse storage. Also we would like understand the data storage is allocated on the entire tenant or it is allocated on the environment basis.

**Comment by Jenefer-Monroe** [comment]
With these turned on we will store all the canvas app launches that occur in your tenant in a table called Audit Logs. 
We do not have a system to clean these when they are old, so if you would like to keep the storage here lower you would need to add some system to do that. 

Dataverse capacity is a tenant wide thing. Here is a link to get you going learning about dataverse capacity
https://learn.microsoft.com/power-platform/admin/add-storage

Hope that helps

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by PrasannaKumarPenumarthi** [comment]
Hi Jenefer,

We had performed the steps that was mentioned in the article "https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http-graphapi" .

We had Turned on the below 2 flows:
1.Admin | Audit Logs | Update Data (V2)
2.Admin | Audit Logs | Sync Audit Logs (V2)
which are in the Core-Component solution.

But issue is
1.Admin | Audit Logs | Update Data (V2)- This flow is not at all Running and we are not able to find any option to manually run this flow.
2.Admin | Audit Logs | Sync Audit Logs (V2)- This flow is throwing error message " Error occurred while reading secret: Value cannot be null. Parameter name: input"

Also we had tried to turn these flows through setup Wizard app but the results were not fruitful. Also Set up Wizard app is turning On the flows which were not required by our Organization use.

Request to please help over this issue.

**Comment by Jenefer-Monroe** [comment]
Can you please validate the following
1. Which api are you using for the audit log? 
- [Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)
- [Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)
2. Are you storing your app registration in Azure Key Vault? Or as plain text.

**Comment by PrasannaKumarPenumarthi** [comment]
Hi Jenefer,

Regarding the first question I am using office 365 management API
And regarding second question I am storing app registration in plain text.

But, I had found some resolution to fix the issue. I have granted application permission "activityfeed.read" for office 365 management api and that worked.

Here there is one issue that we have encountered today in power BI report"production coe dashboard" the "AI Credits Usage" is showing empty.

Could you please help to resolve the issue.

**Comment by PrasannaKumarPenumarthi** [comment]
Hi Jenefer

Thanks for your inputs. I had turned on Admin |  sync Template v4 (AI Events) flow. It took some time to run the flow after which I got the data in AI credits usage power bi dashboard report.

I had one final query if you could help.

I had turned on "Admin | Audit Logs | sync Audit Logs(V2)" flow and after some flow runs I am receiving message like"Your flow is consuming an excessive amount of data and reached 80% of the content throughput" limit  if the usage grows, further actions may be throttled or slowed down"


Can you please confirm what action needs to be taken to avoid this warning? So, we can take necessary actions to avoid any future issues.

**Comment by Jenefer-Monroe** [comment]
There are two ways to setup the audit logs, which was did you do? If the old way, please do consider setting up via the Graph API instead.

The old way 
- [Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)
- This did not support filtering of the actions and so was much more API intensive.

The new way
- [Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)
- allows us to filter what we pull in, so we pull in only Power Platform activity and has a much lower API hit as a result.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
