### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Cloud Flows Action 'Parse_Actual' failed

### ISSUE THREAD

**Issue by rajamanickamg2** [microsoft/coe-starter-kit#9232]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

The CoE workflow recently throws an error Action 'Parse_Actual' failed and i have checked the error log 
![Image](https://github.com/user-attachments/assets/d9633a3f-ed1b-496f-90d8-d519bdf43eed)

We dont have this error earlier and we see this kind of error recently and guide us what could be the reason.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

 SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
When was the last time this flow ran? **_Admin | Sync Template v3 (Connectors)_**

Can you please run that and then resubmit this failure?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
