### ISSUE TITLE
Issue During Upgrade to November 2024 Version - Missing CreatorKitCore Components?

### ISSUE THREAD

**Issue by geoff-lennon** [microsoft/coe-starter-kit#9233]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi COE Team,

My colleague reported that his attempted upgrade to the November 2024 version (from October 2024 version) failed.

![Image](https://github.com/user-attachments/assets/d61cc538-0feb-4d19-88ac-6139c0d19d37)

![Image](https://github.com/user-attachments/assets/da14ca98-0f31-43a3-ab37-f09cfbc1a531)

Not sure if this is a new requirement, since prior upgrades have proceeded without issue, so figured I'd check.  

He uses the COE Set-Up + Upgrade Wizard for this process.

If we need to install the Creator Kit, wanted to confirm that we can get the latest version from the below link?

https://learn.microsoft.com/en-us/power-platform/guidance/creator-kit/setup

Appreciate your help!

Thanks,

Geoff

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Upgrading to November 2024 from October 2024

### What app or flow are you having the issue with?

No Particular App or Flow - Issue During Solution Upgrade Process

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Yes that's correct. You can download creator kit from that link
The Creator Kit does not ship with the CoE Starter Kit as its a separate tools team that creates it and they have their own shipping cadence.

**Comment by geoff-lennon** [comment]
Thanks Jenefer!

Is there a new reliance on the Creator Kit with the November 2024 Release or was that dependency there for October 2024 too?

Wondering if my Admin colleague did something different during the upgrade attempt or if something changed on the solution side.

**Comment by Jenefer-Monroe** [comment]
Yes its been there for about a year I think, maybe a little longer. When we redid all the apps to have the consistent UX.

**Comment by geoff-lennon** [comment]
Interesting - thanks!  I'll check with him to see what he might have done differently this time.

Can always install the Creator Kit items if he insists he's following the same steps he has before.

**Comment by Jenefer-Monroe** [comment]
Yep yep. Never a dull moment :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
