### ISSUE TITLE
[CoE Starter Kit - QUESTION] Orphaned User Governance Component

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#9234]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Dear Power Cat Team,

Are there any plans to update the orphaned user app within the Governance components? I can see that this has been requested previously and that there was talks about integrating it into a model driven app rather than the current canvas app.

The current Canvas app doesn't offer the best user experience for non-technical users especially when it comes to the main app interface. It would be great if the PowerApps And Flow buttons actually looked like buttons rather than images... etc...

I would love to hear what the roadmaps is for this?

Thank you for all the great work!

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

Nov 2024

### What app or flow are you having the issue with?

Cleanup Orphaned Resources

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Sorry we have been unable to find funding to redo this UX. Currently there are not plans to make this UX modernized as we just do not have the funding. But we have kept it on the backlog in the hope that resourcing becomes available.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
