### ISSUE TITLE
[CoE Starter Kit - BUG] Set App/Flow Permissions apps are missing from the COE starter kit.

### ISSUE THREAD

**Issue by racker-darren** [microsoft/coe-starter-kit#9235]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I cannot find the following apps in my 'Centre of Excellence - Core Components' solution within the Power Platform COE starter kit:

- Set App Permissions
- Set Flow Permissions

### Expected Behavior

These apps should be present in my COE starter kit according to the following video:
https://www.youtube.com/watch?v=0zptiBppTNo

The following video indicates that these apps should be present in the 'Centre of Excellence - Core Components' solution:
https://www.youtube.com/watch?v=xOnHf8oaXfs

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Set App Permissions

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Import the following solution into my Centre of Excellence environment: CenterofExcellenceCoreComponents_4_37_managed.zip
2. Check that the following apps are present in it:
- Set App Permissions
- Set Flow Permissions

**Comment by Jenefer-Monroe** [comment]
Hello. These apps were replaced by a model driven app called Manage Permissions where you will find the ability to manage permissions for apps and flows, along with several other permissions related features (depending on your build). 

![Image](https://github.com/user-attachments/assets/2d84ee52-92a9-4190-8e6e-643b4db0eac5)
![Image](https://github.com/user-attachments/assets/05b56a26-f16d-4f8e-89e8-d277c0d484fa)

**Comment by racker-darren** [comment]
@Jenefer-Monroe thank you so much for the fast response. That answers my question!
