### ISSUE TITLE
[CoE Starter Kit - QUESTION] The specified user(Id = {0}) is disabled. Consider enabling this user. Additional Details: {1}.

### ISSUE THREAD

**Issue by bnerdco** [microsoft/coe-starter-kit#9245]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I have removed the Global Admin role from the sys account used to run the flows. The account has Power Platform Admin role and some other roles permanently:

![Image](https://github.com/user-attachments/assets/db48302b-49a2-4f9d-bff9-2cf1e97f1f5f)

When I go into our CoE Environment > **Settings** > **Users** I can see in the properties that this account is enabled and it has System Administrator role:

![Image](https://github.com/user-attachments/assets/35b44537-ec26-461b-9022-289a753c161b)

However, it fails to get into Team environments when running **HELPER - Driver Escalation Check**:

![Image](https://github.com/user-attachments/assets/a312a502-437a-4b20-a5c4-e5f4a8b0f87a)

Also, when I go PPS and go into one of the Team Environments > Membership, I get the following error:

`Loading system admins failed, please retry Hide technical details

Error code: Unknown. { "error": { "code": "0x80040225", "message": "The specified user(Id = {0}) is disabled. Consider enabling this user. Additional Details: {1}" } } - [ Timestamp : 9:52 am, 11/12/2024, Session ID: 4f502fd1-a0d8-11ef-bcff-097b0eb964f5 ]`

.. or if I click on Settings for any Environment linked to any Team, I get:

![Image](https://github.com/user-attachments/assets/e3d29d10-c51e-4953-b122-86859ddd5bad)

It's the same for all Teams that this account is not a member of. **None of these errors come up if I enable Global Admin role for this account!..**

Any help would be greatly appreciated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Center of Excellence - Core Components 4.43

### What app or flow are you having the issue with?

HELPER - Driver Escalation Check

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently? 
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles

Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

Note that it must be direct for the escalation to work for some environments. Group assignment will not be sufficient.

**Comment by bnerdco** [comment]
Thank you very much @Jenefer-Monroe. We changed the PPA role from Group to Direct now. We'll check the run in the morning and let you know.
Many thanks!

**Comment by Jenefer-Monroe** [comment]
My fingers are crossed :)

**Comment by bnerdco** [comment]
Dear @Jenefer-Monroe, we had no errors today, the direct role membership fixed the problem.
You're a star, thanks very much!

**Comment by Jenefer-Monroe** [comment]
Oh wonderful news. Thank you so much for getting back to me with it!
