### ISSUE TITLE
[CoE Starter Kit - BUG] Not able to create an automation project

### ISSUE THREAD

**Issue by benjaminhambra** [microsoft/coe-starter-kit#9247]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi all, I'm having a problem with the app automation project trying to load a new automation project. I fill every field, click on next and nothing happened, i don't have any error, or pop-up the app just stay in the same screen, if i try to click on cancel, the same, nothing happened, the only way to close that windows is by clicking in the cross. 

I tried to import the solution in different environment, also i I tried with the unmanaged solution, loading all data into automation project load, with some data less but always i had the same result. 

I tried to run it with the application analyzer but no errors appear when clicking on the next button.

I also tried importing previous versions of the solution but with the same result.

Any help is welcome.

Regards!

### Expected Behavior

That allows me to create an automation project in the automation project application.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.0.20230907.1_managed.zip

### What app or flow are you having the issue with?

automation project

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. execute the automation project
2. fill every field in the automation project app
3. click on next

**Comment by Jenefer-Monroe** [comment]
Removing CoE-Starter-Kit designation. I'm not sure what project you are referencing but I dont believe its the starter kit. 
Please do let me know if I"m wrong and add some screenshots if so to help provide clarity.

**Comment by benjaminhambra** [comment]
> Removing CoE-Starter-Kit designation. I'm not sure what project you are referencing but I dont believe its the starter kit. Please do let me know if I"m wrong and add some screenshots if so to help provide clarity.

Hi Jenefer, sorry what was that "CoE-Starter-Kit designation" it's an app? a flow? in which solution should i take a look?
