### ISSUE TITLE
Issue with sharing a MDA

### ISSUE THREAD

**Issue by myatix** [microsoft/coe-starter-kit#9248]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

We recently installed a completely fresh install of the CoE Starter Kit with a new environment and have been having a number of issues.

One issue is with access to the Maker Command Center. Users are getting the following access error:

![Image](https://github.com/user-attachments/assets/473ee758-1f99-456a-92ed-378ff6dd5955)

I have checked that the maker dashboard has been shared and as far as I can see it seems to have been.

![Image](https://github.com/user-attachments/assets/b41f279d-cc53-4331-aa45-993d202ece08)

![Image](https://github.com/user-attachments/assets/575f3979-37f8-4bbf-9599-187a7bbd144c)

I have also confirmed the users are a member of the M365 Group.

I am however able to access the maker dashboard with the Installation Administrator account???

### Expected Behavior

I would expect users to be able to access the Maker Command Center if they are a member of the makers group in Entra ID.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Make Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Have you given that team access to the SR?

**Comment by myatix** [comment]
@Jenefer-Monroe I think I have discovered the "Power Platform CoE" - Maker Team. (It would appear that the group in the error message is not the same group as the M365 Group specified in the Power Platform Team) Which seems quite strange...

![Image](https://github.com/user-attachments/assets/8620271a-e3e7-45ac-876b-f90260edd986)

![Image](https://github.com/user-attachments/assets/8aaec9c1-0a6b-475f-a5e2-6c32e3e6a4bb)

however the group that is assigned to the Power Platform Team is as follows.
![Image](https://github.com/user-attachments/assets/e22a2ff0-52d0-4461-9bc1-cf7bf9705821)

![Image](https://github.com/user-attachments/assets/4ef5254c-563e-43de-8899-90e6c5b8a685)

I am not sure how this has occurred but this definitely appears to be the problem.

![Image](https://github.com/user-attachments/assets/c328ac38-e39c-4c27-9d95-f7b84b3d2aed)

Is there an easy way to fix this without resetting the whole environment??? Your assistance would be appreciated!

**Comment by Jenefer-Monroe** [comment]
It sounds like the Maker group is just misconfigured, is that what you are saying? 
If so, easy to fix. 

1. Update value in the kit
You can use our CoE Admin Command Center app to update environment variables. 
I suggest you restart the **_Admin | Add Maker to Group_** flow after you do this to be sure the value is not cached in that flow. 
Then going forward new makers will be added to this correct group.
![Image](https://github.com/user-attachments/assets/757c3e91-4945-429c-8572-8407a9262d82)

2. Manually migrate existing makers
We do not have a flow to migrate users from the incorrect group to this corrected group, so you will want to go make sure all your makers are in it. You can either refer to the incorrect group or you can refer to the Maker table.
![Image](https://github.com/user-attachments/assets/e7bb2e8a-7639-454a-9bc5-35804e266cf9)

**Comment by myatix** [comment]
Hi @Jenefer-Monroe,

There is something VERY strange going on here... Our Power Platform Team ("Power Platform CoE - Maker Team") and all the Environment variables point at the correct Entra ID Group ID, as you can see from all the screenshots above. 

HOWEVER...

The Maker Apps are all trying to authenticate with a completely different Microsoft 365 Group than the one specified in the Power Platform Team.

Group Shown in Power Platform Team = "Power Platform - Makers" 
![Image](https://github.com/user-attachments/assets/3123fede-48ce-4988-a454-6531c5a0c7d8)


Group being authenticated with "Power Platform - Admin - Test" (This is the group it is using despite having specified and showing the group above the solution simply uses the incorrect M365 Group?????)
![Image](https://github.com/user-attachments/assets/a2b2492e-8010-48f6-9fa7-0b7cf0d0f22a)

**Comment by Jenefer-Monroe** [comment]
Sorry it sounds like you are having issues with the product's SRs and Sharing, which is something outside of my ability to help debug. I think you'll need to have someone local assist who can explore and debug with you, and maybe contact product support if needed.

**Comment by myatix** [comment]
Hi @Jenefer-Monroe,

This is Microsoft's Unified Support Response...

![Image](https://github.com/user-attachments/assets/b9e9f711-6184-44cf-a84a-b207b9223033)

It feels a little like no one is taking ownership of this issue. I would agree with you that this appears to be a core Power Platform issue but they seem to think it is a CoE issue as can be seen above.

**Comment by Jenefer-Monroe** [comment]
Sorry I'm a little lost. Let's forget the kit for a minute and see if you can explain the situation without the context of the kit. 

You have a team in the envt : **_Power Platform CoE - Maker Team_**
You have associated this team with an entra group: **_Power Platform CoE - Makers_**
You have given this team access to the SR: **_Power Platform Maker SR_**
You've shared the MDA with the Team

Then people from the team do not have access? 
Is that the issue?

**Comment by myatix** [comment]
Hi @Jenefer-Monroe,

Yes that is completely correct... So you are saying we should share it with the M365 Group not the "Power Platform - Maker Team"?

We didn't create the "Power Platform - Maker Team"??? It was done as part of the install wizard. We have done the full install with the Installation wizard. So I presumed that the Team was part of the automated setup that occurs via the installation wizard???
Where does that Power Platform Team ("Power Platform CoE - Maker Team") get created?

**Comment by myatix** [comment]
> Sorry I'm a little lost. Let's forget the kit for a minute and see if you can explain the situation without the context of the kit.
> 
> You have a team in the envt : **_Power Platform CoE - Maker Team_** You have associated this team with an entra group: **_Power Platform CoE - Makers_** You have given this team access to the SR: **_Power Platform Maker SR_** You've shared the MDA with the Team
> 
> Then people from the team do not have access? Is that the issue?

Yes that is correct but we didn't create the "Power Platform CoE - Maker Team" this was created as part of the installation wizard process I presume.

**Comment by Jenefer-Monroe** [comment]
It looks like the product behavior changed here and this action
![Image](https://github.com/user-attachments/assets/4004c2a3-aca1-4c04-838d-23b41d1459b5)

Which used to grant the group permission (as seen here for a case when run in the past)
![Image](https://github.com/user-attachments/assets/4dcba950-83c1-43d5-8574-40b192651df6)

Now does not and only shares with the team. 
You will need to manually share the app with your group today instead and I will add to hte backlog investigating this.

**Comment by myatix** [comment]
Hi @Jenefer-Monroe,

I have tried manually removing the Power Platform Team and adding the group directly to the Makers Dashboard but the M365 Group gets automatically replaced by the Power Platform Team. What is really worrying however is how the Power Platform Team shows that it is mapped to the correct M365 Group but actually Mapped to a completely different M365 Entra ID group. That is a bit worrying if you ask me from a security prespective.

**Comment by Jenefer-Monroe** [comment]
For me, I had to wait ~12-18 hours but then the team finally sunk up with entra and now its working. 

![Image](https://github.com/user-attachments/assets/2a5876e3-2b7f-4ce9-b4eb-70ed2700f9e6)

Please let me know where in the above you differ.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
