### ISSUE TITLE
Managed Permissions app too slow in searching of select user and other search

### ISSUE THREAD

**Issue by Rajatchopra3** [microsoft/coe-starter-kit#9249]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

The Managed Permissions app is extremely slow, maybe as our tenant is large.
1. envt search is slow
2. flow/app search is too slow in the app
3. In manage permission > add user > not able to search user

Could you please look into the reason for the app being slow and the search user not working in manage permission.

our ops used to use the previous set app/flow permission app but as that is deprecated and now the manage permission app is there but it is not working as expected.
 
could you please help us out with the app or maybe provide us a way to use the old set permission app.

### Expected Behavior

The app is too slow and the user search functionality not working

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

manage permission

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. We did just make a change here for the Nov release that should alleviate the issue: https://github.com/microsoft/coe-starter-kit/issues/9161

**Comment by Rajatchopra3** [comment]
Hello @Jenefer-Monroe, would the Nov release fix all the search issues in the app or as I see issue 9161 was only for environment search

**Comment by Jenefer-Monroe** [comment]
We applied a fix for both environment screen and maker screen. Please do let us know.

**Comment by Jurny123** [comment]
Hello,

Fresh instalation of CoE, so the fix should be already applied, but unfortunately, still can't search for the users when trying to edit the app permissions:

![Image](https://github.com/user-attachments/assets/084e6156-ffed-4c20-9aca-be4b618a2c97)

Core Components version 4.50.1. Should I open a new bug report, or the case will be investigated in here?
