### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by firefox-edge123** [microsoft/coe-starter-kit#9250]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I noticed that there wasn't an October 2024 release of the COE kit.
I am currently on the August 2024 release of the COE kit.
Will I be okay upgrading from the August 2024 release to the November 2024 release?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Yes that should be fine. 
There have been some product related and intermittent setup issues lately though. So if you hit something just let me know and we can get you unblocked.
