### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Damie-B** [microsoft/coe-starter-kit#9255]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi team,

I have been trying to update the CoE to the Novemeber feature release among with inculde the core components.
However each time to import a new solution, i am getting an error messahe below:

Solution "Center of Excellence - Core Components" failed to import: The account (5c117a7a-b02e-4fce-9424-65d7497d7be8) used to import the dataflow 'CoE BYODL Environments' (f550e5e1-0fc8-47c9-81af-7bd8ffa9bee6) does not match the dataflow owner account (81b626f3-aa13-4c95-bb08-7b969c7884e6). Please change the dataflow ownership or import the dataflow using the dataflow owner's account.

I have then updated the related flows and sahred ownership with another account and re-ran the update but still fails
![Image](https://github.com/user-attachments/assets/dd0170fe-ad8f-467a-8b55-c273f579972a)
![Image](https://github.com/user-attachments/assets/9d4130a4-f51e-4e97-b752-3d8369058ba4)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.17

### What app or flow are you having the issue with?

 'CoE BYODL Environments' 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Damie-B** [comment]
**Error code:** [80040265] (http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=80040265&de=online)
**Exception Message:** The account (5c117a7a-b02e-4fce-9424-65d7497d7be8) used to import the dataflow 'CoE BYODL Environments' (f550e5e1-0fc8-47c9-81af-7bd8ffa9bee6) does not match the dataflow owner account (81b626f3-aa13-4c95-bb08-7b969c7884e6). Please change the dataflow ownership or import the dataflow using the dataflow owner's account.
**Activity ID:** c8dfa10e-92ab-442d-b619-77bc24f82057

**Comment by Jenefer-Monroe** [comment]
Hello, seems like some new product issue people are hitting, conversation about this issue being tracked with this issue: https://github.com/microsoft/coe-starter-kit/issues/9242

**Comment by Damie-B** [comment]
Thank you Jenefer i will check the details now and follow the conversation. Hopefully that should help

**Comment by Jenefer-Monroe** [comment]
closing out as a duplicate
