### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by johnvittneyk** [microsoft/coe-starter-kit#9259]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

We are trying to quarantine the PowerApp (Canvas) as soon as it is created. Only option we have right now to use as trigger is the the **PowerApps App** table record that gets created. But there is a huge delay in creating this app record in the Dataverse table after creating a new app in the platform. Need more information on which flows are responsible to add records to PowerApps App Table and what is trigger? Is there a way to make this data insertion instant or is there a way to quarantine the app as soon as it is created?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by johnvittneyk** [comment]
Thanks for this information @Jenefer-Monroe . Can you please help me understand how the objects are being added to the PowerApps Apps table right now?

**Comment by Jenefer-Monroe** [comment]
Sure thing. 

The driver flow runs daily and updates the Environment custom table in Core for all environments in the tenant: **_Admin | Sync Template v4 (Driver)_**

This triggers the **_Admin | Sync Template v4 (Apps)_** flow to run for each environment. It identifies new and updated canvas apps that need updated in inventory, and then calls **_SYNC HELPER - Apps_** to update each.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
