### ISSUE TITLE
[CoE Starter Kit - BUG]  Environment Request Management - Error Loading Control

### ISSUE THREAD

**Issue by bocESMI** [microsoft/coe-starter-kit#9261]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Error Loading Control error when configuring mandatory values on the Environment Request Management Wizard

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

CenterofExcellenceCoreComponents_4_45_managed

### What app or flow are you having the issue with?

Environment Request Management

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. In our CoE DEV environement
2. Setting up the Environment Request Management Wizrd
3. on the Configure mandatory values screen
4. Env Request - Enable Cost Tracking - the choice combo box is showing an "Error Loading Control" and "no" values

**Comment by bocESMI** [comment]
Thanks Jenefer, reloading the page fixed the issue.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
