### ISSUE TITLE
[CoE Starter Kit - BUG] Unable to Upgrade CoE to Nov 2024 and Remove Previous Version with Error Code 8004F020

### ISSUE THREAD

**Issue by Ace0751** [microsoft/coe-starter-kit#9262]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to upgrade our CoE to the latest version which is Nov 2024 4.45.  We are able to install the latest solution but the issue is the environment is showing the solution as a new solution and not an upgrade.  We are currently on the July update 4.33.  If we add the CoE as a new solution, we need to add all of our security credentials again while the upgrade we don't need to do that.  If we do import the solution as new and enter our security creds then try to uninstall the previous version, we run into an error with the description below.  

We did find a typo in the new version, instead of saying 4.45 in the zip, it is instead 4_45.  I thought that the type would cause the issue but it did not.  We don't want to remove the old solution as a different solution runs off of the previous CoE.  

### Expected Behavior

When trying to uninstall, the error message mentions AppModuleRoles, but we are unable to find where that is located.
![Image](https://github.com/user-attachments/assets/e87c4d4e-51be-463d-9ff1-9b0c04ba16ae)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

CoE Solution

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Click on import solution
2. Browse and select latest CoE zip file 4.45, click next
3. Under advanced settings, upgrade should be an option but it's not there.  Patch also is set to no
4. Enter security credentials
5. Import solution
6. One imported, uninstall previous version
7. Run into error message

**Comment by Jenefer-Monroe** [comment]
Hello that _ isnt a typo, thats just how those are stored. Another user hit this, its a product issue. And they found a resolution as shown here. 

Please take a look:
https://github.com/microsoft/coe-starter-kit/issues/8995
https://github.com/microsoft/coe-starter-kit/issues/8995#issuecomment-2373695281

**Comment by Ace0751** [comment]
Looking at the thread now and see if we can replicate this and get it resolved.  Thanks for responding, will let you know the outcome.

**Comment by Jenefer-Monroe** [comment]
Please do, I'll have my fingers crossed.

**Comment by Ace0751** [comment]
We were able to remove the previous version of the CoE core components from our prod environment.  Plus our naming on the previous version was different than the new version which is why we could not upgrade, just had to import as now.  We had to modify our customization solution in dev by following the link you provided.  The power platform admin view app had to be removed then added back to get the previous CoE to be removed.  In the end, everything is working and hoping nothing like that happens in the future.  Appreciate the help.

**Comment by Jenefer-Monroe** [comment]
So glad to hear it worked out! I'll go ahead and close out then but please do return with new issues if they occur in the future.
