### ISSUE TITLE
[CoE Starter Kit - BUG] Request Orphaned Objects Reassigned (Child) Time out

### ISSUE THREAD

**Issue by SkippingAdi** [microsoft/coe-starter-kit#9264]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Above mentioned flow has a time out for one specific user. Inputs of Task "Create HTML table OrphanedFlows" shows 7 objects. There are no other orphaned objects. The manager addressed in the Teams task is active, exists in EntraID, has an E-Mail address. It seems not a problem with managers account. The flow has not problem if there are only one or two objects in the MTL table.
![Image](https://github.com/user-attachments/assets/a3e6eb66-56e5-445b-be0d-e9e76dcb4210)

### Expected Behavior

- No timeout
- No successful completion of the flow in case of timeout. Currently the email text is not clear: "The request to this manager failed or timed out." In the former case, immediate action may not be necessary, but in the latter case, action is absolutely necessary because the flow has a problem.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.25

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, this means that the manager did not respond to the card sent to them. It sits and waits for them to respond for 7 days and then if they don't, it times out.

**Comment by SkippingAdi** [comment]
Hello Jenefer-Monroe.
Thank you for clarification. 
It would be advantageous if this 7-day timeout were added to the documentation for the flow. There are certainly other people like me who do not derive this directly from the properties of the teams task when analyzing bugs. And as already mentioned, it would make more sense not to close the flow with the status Error in this case. As the admin, I receive an email in this case. This means that the flow has successfully completed its tasks.

You can close the bug.

**Comment by Jenefer-Monroe** [comment]
It should not end with an error in this case, it should send the admin and the manager a notification that the manager did not respond.
Please let me know if I misunderstand.

And note also that all emails in the kit are configurable so you can make it more clear for your admins and managers here. 
![Image](https://github.com/user-attachments/assets/41d839c6-304a-464e-83f5-cba6e647426b)
![Image](https://github.com/user-attachments/assets/5d5bbef6-e5ce-4694-88d4-ab06ddd06f64)

Hopefully that helps

**Comment by SkippingAdi** [comment]
Hi Jenefer
you are right. It's not an error when the flow time outs. I'm wrong. And thank you for the tip regarding modification of the email.
