### ISSUE TITLE
[CoE Starter Kit - QUESTION] I changed my COE environment URL and now flows won't run. Couldn't find spot to update the url

### ISSUE THREAD

**Issue by RandomDept** [microsoft/coe-starter-kit#9269]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi all,

When I initially setup the COE, I just went with whatever default URL was generated for the environment.
We have since updated to a custom URL customurl.cr6m.dynamics.com

I was looking for the Environment variable / place I can update the URL as now flows seem to have stopped working.
I tried running the COE Admin Command Center and update the variables through there, but I couldn't find anything obvious / or am blind.

Thank you.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Admin | Sync Template v3  Admin | Sync Template v3 CoE Solution MetadataAdmin | Sync Template v3 Configure Emails

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. We don't store this as an Environment Variable. The issue you are facing is likely a product one. I've seen this happen where flows break after you change the URL. 

Typically what has fixed it is turning the flows off and back on. 
I do have this helper flow which will turn everything off and then you can use the setup wizard to turn it back on. [

PrepSolution-Turnflowsoff_20241029194544.zip](https://github.com/user-attachments/files/17800046/PrepSolution-Turnflowsoff_20241029194544.zip)

**Comment by RandomDept** [comment]
Thank you for such a quick resposne.

Looks like a few of the CoE Core - Connection references were a guid instead of the connection.
I've now fixed those, but now get the below when trying to run the Prep Solution - Turn flows off.

Encountered internal server error from Azure Resource Manager. The tracking Id is 'XYZ.

Thank you
RD

**Comment by Jenefer-Monroe** [comment]
ok im not sure. That helper is just something I use internally I havent tested it for others to use, you may need to manually turn things off then.

**Comment by RandomDept** [comment]
Thank you,

Is there a list of what flows should be on / off in the final state so I can make sure to match?

RD

**Comment by Jenefer-Monroe** [comment]
I suggest you turn all the flows off and then boot the setup wizard, it will ensure you have all the env vars and the correct flows turned on.

**Comment by RandomDept** [comment]
Thank you, Jenefer.

I turned all the flows off, confirmed connections in default solution / coe solution are not a guid, but an account.

When trying to run Admin Sync | Template v3 Configure Emails, I get a 


Error from token exchange: Permission denied due to missing connection ACL: User = XYZ appid=XYZ, connection=australia-001/logicflows/XYZ

Request failed with status code 401,

**Comment by RandomDept** [comment]
Looks like everything is fine now, thank you for the hell Jenefer!

**Comment by Jenefer-Monroe** [comment]
what wonderful news to come back to!

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
