### ISSUE TITLE
[CoE Starter Kit - QUESTION] Admin | Audit Logs | Sync Audit Logs (V2) error

### ISSUE THREAD

**Issue by lucasubieta** [microsoft/coe-starter-kit#9271]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi there, im having a problem with the flow "Admin | Audit Logs | Sync Audit Logs (V2) error " as it is requesting the "Audit Logs - Client Azure Secret", but and have my secret in the "Audit Logs - Client Secret" variable, so it should run with error..

![Image](https://github.com/user-attachments/assets/17883171-e1d1-4398-a8fb-f3bab2fa28ad)

### What solution are you experiencing the issue with?

None

### What solution version are you using?

July

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
You are not using Azure Key Vault so this failure is expected and caught. 
Note that flow always shows the first failure even if its a caught failure, so you need to go further down in the flow to **_find where the flow actually terminates (fails)_** the flow

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/b60457d6-0645-4e2f-b23e-2507828af826)

**Comment by lucasubieta** [comment]
Thanks Jenefer, 

I didn’t mention that the flows appear as "Failed," notifying the admins by email.
So, shouldn’t it be "Succeeded" if there’s a catch for that error?

**Comment by Jenefer-Monroe** [comment]
Per this, it appears that the flow is failing. Its just not failing on this call as that failure is caught. You will need to go further down in the flow and find where its actually failing.
![Image](https://github.com/user-attachments/assets/b195502c-50e8-4223-8646-3f8fb95c38f9)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
