### ISSUE TITLE
DLP transversal communication between business and non-business connectors.

### ISSUE THREAD

**Issue by bleaeib** [microsoft/coe-starter-kit#9272]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

In DLP,  we came across a set up where  business and non-business connectors cannot speak to each other. 
is it done by design or could he be a bug?
also it should be highlighted in the DLP impact analysis and it is not the case.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

DPL/DPL impact analysis

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I believe you are asking about the product behavior for DLP policies is that correct? 

You are correct. The idea of business and non-business classification is that they are two buckets to use for when connectors can be used together. 

Please see this product article to get you started here: [Connector classification](https://learn.microsoft.com/power-platform/admin/dlp-connector-classification)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
