### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by jasl07** [microsoft/coe-starter-kit#9278]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I'm using these CoE Starter Kit solutions since 2021:
- Center of Excellence - Governance Components: Version 1.25
- Center of Excellence - Core Components: Version 1.71.7
About 8 months, I'm having issues with the flow visualization from the Power Platform Admin View (Power App included in the solution). I can only see the flows created until March. I don't have issues with the other components as Power Apps.

![Image](https://github.com/user-attachments/assets/102db0f7-cd11-4833-8d6c-7ec89a221611)
![Image](https://github.com/user-attachments/assets/3eb8f0ec-2904-4d13-8cca-c0ea8f667e25)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

1.71.7

### What app or flow are you having the issue with?

Admin | Sync Template v2 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Unfortunately we are unable to assist with installs of the kit this old. We are on V4 of the sync flows at this time and so we do not have the capability to go back and relearn the kit from that long ago. 

Please do get yourself onto a new version of the kit though, its much more performant and feature rich. 

If you have what you need from the kit in the version you have today you may be able to just use the out of the box admin features that are live now. These in PPAC: https://admin.powerplatform.microsoft.com/analytics/flow
