### ISSUE TITLE
[CoE Starter Kit - BUG] Embedded Power BI manage access app error for Flows

### ISSUE THREAD

**Issue by STLCC-SPOSA** [microsoft/coe-starter-kit#9279]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I upgraded our CoE toolkit to the November 2024 release and updated the power bi reports. When on The PowerBI "Flow Deep Dive" tab.   I tried to right click a flow -> Drill Through -> Manage Flow Access.  The page that comes up has the error like in the screenshot below.

![Image](https://github.com/user-attachments/assets/8f2459e5-c341-4571-b787-1f93b873a686)

Tried resetting the visual to default, but it didn't fix.

### Expected Behavior

Load a page that will allow the change of permissions.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Power BI report

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Update solution to latest November 2024 release
Update Power BI report 
embed the app for manage access
Go to flow detail and drill through to manage access on a flow in the default environment

### Anything else?

Looks to be the similar issue that was fixed in August 2023 (https://github.com/microsoft/coe-starter-kit/issues/6246)

**Comment by Jenefer-Monroe** [comment]
I dont repro this. We did just have to republish these though as it appears that some product change had occurred. 
Please do the following 

1. Make sure you don't have unmanaged layers on the apps
![Image](https://github.com/user-attachments/assets/b4383059-e937-43f0-b4d3-e01365ac7a54)

2. Make sure you are logged in as a user with PPAdmin Role permanently and directly assigned
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles
Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

3. Be sure you selected the app from your CoE envt during [Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard)

**Comment by STLCC-SPOSA** [comment]
#1 no layers
#2 permissions were already set.
#3 Wasn't working at first.  But one time added the app vs the flow, and then was prompted to confirm permissions.  Then the app deep dive broke when the flow's started working.  After retrying the app several times it started working as well.  
Thanks for the help.
