### ISSUE TITLE
[CoE Starter Kit - QUESTION] Access to Center of Excellence Applications - Core Components

### ISSUE THREAD

**Issue by jcgds** [microsoft/coe-starter-kit#9280]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello, what is the procedure to grant access to a user to only use the Center of Excellence - Core Components applications, such as Set App and Flow Permissions? Does this user need to be a global Admin? What procedures should I follow, what permissions should I grant and in which Microsoft for Apps locations? In my tenant I already have the Coe Admins and Coe Makers groups.

Thanks!

![Image](https://github.com/user-attachments/assets/8af1f88f-6c1b-4036-8b94-4e5297225837)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Core Componentes 4.17

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, each setup area (ex inventory, inactivity, etc) has a section describing how to share the apps and data. 
For example see [Share apps with other admins](https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components#share-apps-with-other-admins) for sharing PPAdmin View app with other admins. 

And in our FAQ you can see the general idea for the SRs to use for Admin, Maker, User: [Share an app from a production environment](https://learn.microsoft.com/power-platform/guidance/coe/faq#share-an-app-from-a-production-environment)

Please let me know if this resolves for you.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
