### ISSUE TITLE
[CoE Starter Kit - BUG] Audit Logs/ PowerBi Production dashboard

### ISSUE THREAD

**Issue by brigidaanne94** [microsoft/coe-starter-kit#9282]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I am having issues with setting up CoE audit logs and the production coe dashboard for powerbi. I followed the instructions that are listed on Microsoft (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http) and as you can see in the attached images, everything is empty. I went through the CoE setup wizard and audit log wizard multiple times. The power platform admin center is completely empty, audit logs empty, and same with the powerbi dashboard. Can anyone offer some solution?

![Image](https://github.com/user-attachments/assets/ad5c0004-1684-4a4c-ac12-fac9d4cb6272)
![Image](https://github.com/user-attachments/assets/9718dd11-f721-42bd-a0b5-0a7dec01dc01)
![Image](https://github.com/user-attachments/assets/420f505b-cfd3-4f63-9931-0f2f84e64d81)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Production_CoEDashboard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
1. (O365) Go to your app registration and validate that you have the correct API permissions. Note that it requires application permissions not delegated and they need to be Granted with Admin Consent.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/bc0331a0-02d8-4306-8d70-dbe96f6f49a8)

1. Are you storing the secret in Azure or in plain text?

1. Validate that you have entered all the env variables
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/fec00bdd-5b8d-4a54-8a6e-f72fef04a3a9)

1. Turn the flows off and back on. Sometimes env vars get stuck in them with old values
1. Validate that you have [started the subscription](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http#start-a-subscription-to-audit-log-content)

**Comment by Jenefer-Monroe** [comment]
Is this flow turned on, running, and passing? **_Admin | Audit Logs | Sync Audit Logs (V2)_**

If so, find one of your launches here and look at the output:
![Image](https://github.com/user-attachments/assets/c93bddf5-fee2-4832-baf2-fe1a858c435a)

What is shown for the **_RecordType_**
![Image](https://github.com/user-attachments/assets/10b87bd8-89f3-4b88-90cd-445b096476d3)

**Comment by brigidaanne94** [comment]
It is so long that I have to click to download, so there is data in there. However, the recordtype comes back as 25, 83 and 84. Also, the action after this is blank and then the following step doesn't run: 
![Image](https://github.com/user-attachments/assets/03d16464-adb2-481d-b56c-2371d11fd1ab)

**Comment by Jenefer-Monroe** [comment]
You will need to find an instance where you have a launch to test this. 

My suspicion is that you are impacted by this: https://github.com/microsoft/coe-starter-kit/issues/9268

So if you prefer you can just do the workaround for now that is described there.

**Comment by brigidaanne94** [comment]
I just did the workaround instructions and same problem, no data:

![Image](https://github.com/user-attachments/assets/e7b634a8-82bd-4e44-b458-eecc0c2d1486)

**Comment by brigidaanne94** [comment]
So before I do that, I went into another bug discussion and saw that you mentioned to make sure these 2 flows were turned on. However, I was facing a Policy error. In my attempt to fix it, I am now unable to even edit these flows. I am getting this error message: "The XRM workflow table row could not be found." 

I was thinking maybe I should try to delete them and reimport them?


![Image](https://github.com/user-attachments/assets/19b3cd25-cacf-4e07-af4e-ad4125c1b2d4)

**Comment by brigidaanne94** [comment]
I did the export, and yes the record types are 45 and 256: 

![Image](https://github.com/user-attachments/assets/9fedf7e6-13b3-4ee9-a9e8-49e36ff692cc)

**Comment by Jenefer-Monroe** [comment]
ok the issue should not be schema then. You can delete that second solution ([auditlogsbackupwithoutpurview](https://github.com/user-attachments/files/17722348/auditlogsbackupwithoutpurview_1_0_0_1_managed.zip)) and return to the flow in core : Admin | Audit Logs | Sync Audit Logs (V2)


You will need to find cases where you have Power Apps activities which are 45 ad 256
![Image](https://github.com/user-attachments/assets/76282a5b-8b7a-4cd5-9213-53658e290f47)

**Comment by brigidaanne94** [comment]
So I did what you said and then I launched an app and ran the sync audit log flow. I went to the filter event action and there are 67 tries. On the 2nd try and 26th try, there was data but in the launchpowerapp case, it says that the app does not exist:

![Image](https://github.com/user-attachments/assets/543f2e77-ae07-4d5a-b883-2224e88b7236)

**Comment by Jenefer-Monroe** [comment]
There are duplicate records for every launch that comes through, both types 45 and 256. 

What you see there is likely a type 45, can you check? 
And are there any that come through with the type 256?


Find one of your launches here and look at the output:
![Image](https://github.com/user-attachments/assets/c93bddf5-fee2-4832-baf2-fe1a858c435a)

What is shown for the **_RecordType_**
![Image](https://github.com/user-attachments/assets/10b87bd8-89f3-4b88-90cd-445b096476d3)

**Comment by Jenefer-Monroe** [comment]
Please post a separate issue for issues with that new flow, we have to keep issues to single topic in order to manage them all. 

This flow, Admin | Audit Logs | Sync Audit Logs (V2), is also API intensive especially when you use the O365 Management API technique to get the Purview logs. This is because it cannot filter with the call to the API and you have to filter in the app, hence all those other recordtypes.

I suggest you change to use the [Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi) to get Purview. It's a new API offered and our new recommendation. It allows us to filter with the call to the API to Power Platform only, and hence we dont have to spend API hits on all those other record types.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
