### ISSUE TITLE
[CoE Starter Kit - BUG] XrmEnvironmentVariableAttributeNotFound

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#9283]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hello CoE Team,

I hope you are well.

Can you please help?

i'm setting up the core component solution from scratch in a new environment. I'm not using the wizard, sorry. I'm manually turning flows on. 
All is going well, but for some Flows i'm getting the following error. 

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmEnvironmentVariableAttributeNotFound","message":"Attribute ----scrubbed---- was not found for environment variable ----scrubbed----."}}".

An example is on the Flow called SYNC HELPER - Apps

![Image](https://github.com/user-attachments/assets/de3fc8cb-a48b-4fb4-839f-6fbf273a5884)

Any idea what I'm missing here, please? Sorry.

Thanks very much,

Garry

### Expected Behavior

Ability to turn the flow on.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

SYNC HELPER - Apps

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

- Open Flow SYNC HELPER - Apps
- Click Turn on
- Error appears

**Comment by Jenefer-Monroe** [comment]
It's likely the **_CoE System User ID_** environment variable, just a guess I wish they would tell us with the error! 

Here is how you can fill it manually is the SYSTEM user has already been added to the Maker table. However we add it with the setup wizard too. So it may not be there. Can you check? 

Findithis SYSTEM user in the Maker table, grab its GUID and putting it into the env var manually:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/99d6ee1e-1cb4-4804-95b8-adb6c379ca24)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/a29d92b4-06b1-41c0-a6aa-d62147578e60)

If its not there yet you will have to add manually. I think its as simple as creating a user with SYSTEM for the display name.

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe,

Thanks for the advice. 

I wasn't able to manually create a System user. I went to the wizard app, as you mentioned the System user record gets created. and went through the first couple of steps and I now have the System user. I was then able to turn on the flow. Woohoo!

Thanks so much for your help!

Garry

**Comment by Jenefer-Monroe** [comment]
Yeah! Happy to help. 

I'll go ahead and close out, but feel free to return with new issues as they arise.
