### ISSUE TITLE
[CoE Starter Kit - BUG] The connectionreference(111e6575-5fea-41bd-844a-2188584a7759) component cannot be deleted because it is referenced by 3 other components. For a list of referenced components, use the RetrieveDependenciesForDeleteRequest.

### ISSUE THREAD

**Issue by sakshiporwal95** [microsoft/coe-starter-kit#9293]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

The connectionreference(111e6575-5fea-41bd-844a-2188584a7759) component cannot be deleted because it is referenced by 3 other components. For a list of referenced components, use the RetrieveDependenciesForDeleteRequest.

We are seeing this issue when trying to update the COE starter kit. PFA logs

 [4483b7ca-e2e7-4fc2-8930-286154c10ec8_CenterofExcellenceCoreComponents_reports (2).zip](https://github.com/user-attachments/files/17831142/4483b7ca-e2e7-4fc2-8930-286154c10ec8_CenterofExcellenceCoreComponents_reports.2.zip)

![Image](https://github.com/user-attachments/assets/79290970-3423-4049-a9ef-51b7c84f48d4)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

admin - sync template v3 apps

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Please go find what objects have that dependency. You can do that as shown here (shown for a different connection of course) 

![Image](https://github.com/user-attachments/assets/7baf8100-6bbe-40d6-a940-3f145591985a)

**Comment by sakshiporwal95** [comment]
![Image](https://github.com/user-attachments/assets/4e66500a-831d-43f4-9bd2-1d3aa179b66e)
![Image](https://github.com/user-attachments/assets/536ba789-dd6a-417c-b45e-3c860876559b)

**Comment by Jenefer-Monroe** [comment]
ok the latter is the issue. 

So what you've hit here is a product bug in their upgrade processes where you have a flow thats been deleted (**_Admin | Sync Template v3 (Apps)_**) referencing a connection referencing that has also been deleted (**_CoE Core - HTTP Azure AD_**)

But during upgrade it fails because it thinks it cannot delete the connection reference as it does not check to see if the dependencies are also deleted.

The product team is aware of this issue and is working on it. However in the meantime you will need to remove the dependency. 
The images below are for a different flow/connection reference, but the same idea applies, you will do the delete from your **_Admin | Sync Template v3 (Apps)_** flow

### How to work around the bug
As a result, in order to upgrade you will break the dependencies. 
You will need to:
1. Delete the _Upgrade solution (if one was left behind)
2. Open all the flows above, delete most of whats in them, and resave
3. Do this until the connection reference no longer shows dependencies
4. Try the upgrade again
### Step 2 example
Example of how to do the workaround for one of the flows:
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5044cf53-6776-411c-bc70-d0205227755c)
### Thats just awful!
Yes I apologize for the hassle.
The product team is aware of this issue but the fix has not yet come out.

**Comment by sakshiporwal95** [comment]
No upgrade worked but flows are not getting turned ON.

Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is '###################################'. Connection 'admin_CoECoreDataverseEnvRequest' to 'shared_commondataserviceforapps' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".

**Comment by Jenefer-Monroe** [comment]
Great news we've gotten past that issue. It sounds now like your connections are either wrong or misconfigured

Please log in as the user who’s identity installs and runs the kit and do the following:
### Fix connections. 
Browse to the connections in the envt. If there are any broken connections please repair them
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2198fb17-1107-4851-a744-f3b34e89d11d)
### Fix HTTP with Microsoft Entra ID (preauthorized)
Make sure all the **_HTTP with Microsoft Entra ID (preauthorized)_** connections are pointing to your graph URL ![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/911668af-099e-41a5-a248-40e98bb9fc4e)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/1a39d4c4-9135-4c1e-9c49-7ec05d5921db)
### Fix Connection References
Lastly go to the Default Solution > Connection References
Make sure they are all pointed to the correct identity which is intended to run the flows by doing the below for all connection references.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f630670f-9bf5-4c56-bf18-9693e0eeea01)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d4a34cc4-5d46-494e-9a7d-e9d570489159)

**Comment by AAKP95** [comment]
> ok the latter is the issue.
> 
> So what you've hit here is a product bug in their upgrade processes where you have a flow thats been deleted (**_Admin | Sync Template v3 (Apps)_**) referencing a connection referencing that has also been deleted (**_CoE Core - HTTP Azure AD_**)
> 
> But during upgrade it fails because it thinks it cannot delete the connection reference as it does not check to see if the dependencies are also deleted.
> 
> The product team is aware of this issue and is working on it. However in the meantime you will need to remove the dependency. The images below are for a different flow/connection reference, but the same idea applies, you will do the delete from your **_Admin | Sync Template v3 (Apps)_** flow
> 
> ### How to work around the bug
> As a result, in order to upgrade you will break the dependencies. You will need to:
> 
> 1. Delete the _Upgrade solution (if one was left behind)
> 2. Open all the flows above, delete most of whats in them, and resave
> 3. Do this until the connection reference no longer shows dependencies
> 4. Try the upgrade again
> 
> ### Step 2 example
> Example of how to do the workaround for one of the flows: ![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/5044cf53-6776-411c-bc70-d0205227755c)
> 
> ### Thats just awful!
> Yes I apologize for the hassle. The product team is aware of this issue but the fix has not yet come out.

Hi, 

I got the same connection reference issue for Dataverse -legacy. When I tried above method by- removing actions in flows, now it has created unmanaged layers in flows. How to resolve it?

**Comment by Jenefer-Monroe** [comment]
Yes thats correct, however those are unmanaged layers in flows that will be deleted. 

The issue is that the product upgrade code said... we cant delete connection x because its used in flow y! 
But flow y is also deleted so its ok to remove the connection. 

So on your upgrade these flows will be removed.

**Comment by AAKP95** [comment]
> Yes thats correct, however those are unmanaged layers in flows that will be deleted.
> 
> The issue is that the product upgrade code said... we cant delete connection x because its used in flow y! But flow y is also deleted so its ok to remove the connection.
> 
> So on your upgrade these flows will be removed

I've got 17 flows with dependency. So all these will be removed and re-added?

**Comment by Jenefer-Monroe** [comment]
Are referring to the 17 that you did the above workaround for? If so yes those are all the old v3 versions of the sync flows that used the old dataverse connector.

**Comment by sakshiporwal95** [comment]
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowNeverPublished","message":"The workflow with id 'b677aa25-8de4-ed11-a7c7-0022480813ff' cannot be used as a child workflow because it has never been published. Child workflows need to be published at least once before they can be included in a published parent workflow."}}".

This is the new error we are seeing :( after fixing connection references

**Comment by Jenefer-Monroe** [comment]
Sorry what state are you in? Did you perform these steps already? 
1. Delete the _Upgrade solution (if one was left behind)
2. Open all the flows above, delete most of whats in them, and resave
3. Do this until the connection reference no longer shows dependencies
4. Try the upgrade again

And if so did you boot the setup wizard? It will turn the flows on in the correct order.

**Comment by sakshiporwal95** [comment]
I did followed all the steps but now when I am running set up wizard.

![Image](https://github.com/user-attachments/assets/18bb8cda-f673-4be4-b0e5-6434a9a2666d)

When trying to turn on : helper maker check , below is the error :(

Turn on failed. Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller object id is 'd3bbb0b6-4e6b-4614-a883-3c3a4d98a153'. Connection 'admin_CoECoreO365Users' to 'shared_office365users' cannot be used to activate this flow, either because this is not a valid connection or because it is not a connection you have access permission for. Either replace the connection with a valid connection you can access or have the connection owner activate the flow, so the connection is shared with you in the context of this flow."}}".

**Comment by Jenefer-Monroe** [comment]
ok there is something wrong with your user then. 

1. Are you logged in as the user that setup the kit? 
If not please do so and try again

2. If you are, please return to the connections suggestions above.

**Comment by AAKP95** [comment]
> I can see the edited flows while setting up through set up wizard
> 
> ![Image](https://github.com/user-attachments/assets/721b03da-8023-4fbc-8e62-09efb78eceeb)

And the flows are getting on when the toggle button is clicked

**Comment by Jenefer-Monroe** [comment]
ok sounds like you are still in a bit of an unknown state then. 

Please follow these steps. I've included a screenshot form another bug on how to delete the _Upgrade

1. Delete the _Upgrade solution (if one was left behind)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/44eafb8d-a0b1-40e5-af3b-b3f1b502146c)

2. Open all the flows above, delete most of whats in them, and resave
3. Do this until the connection reference no longer shows dependencies
4. Try the upgrade again
