### ISSUE TITLE
Power BI Dashboard not refreshing

### ISSUE THREAD

**Issue by PrasannaKumarPenumarthi** [microsoft/coe-starter-kit#9294]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi Jenefer,

This issue is reference of #9231 

We had performed the steps that was mentioned in the article "https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog-http-graphapi" .

We had Turned on the below 2 flows:
1.Admin | Audit Logs | Update Data (V2)
2.Admin | Audit Logs | Sync Audit Logs (V2)
which are in the Core-Component solution.

But issue is
1.Admin | Audit Logs | Update Data (V2)- This flow is not at all Running and we are not able to find any option to manually run this flow.
2.Admin | Audit Logs | Sync Audit Logs (V2)- This flow is throwing error message " Error occurred while reading secret: Value cannot be null. Parameter name: input"

Also we had tried to turn these flows through setup Wizard app but the results were not fruitful. Also Set up Wizard app is turning On the flows which were not required by our Organization use.

Request to please help over this issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Power BI Dashboard

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Thank you for posting, I went ahead and reactivated that issue now. I'll close this one and we can iterate there.
