### ISSUE TITLE
[CoE Starter Kit - QUESTION] "Flow Last Run On" column is blank in Admin View

### ISSUE THREAD

**Issue by carusyte** [microsoft/coe-starter-kit#9298]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

We wanted to check the last run timestamp for the flows, but the column for all flows seems to be empty. Wondering if this is this expected, or any possible error in one of the sync flows?
![Image](https://github.com/user-attachments/assets/6f9efd58-a9a7-40f2-a36d-cdc0ec255cd5)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 2024

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. This information is not yet available to us for the cloud flow architecture. 

The product team does now write this in a consumable way for us but it would be API prohibitive to consume. Please see [Store cloud flow execution metadata in Microsoft Dataverse](https://learn.microsoft.com/power-platform/release-plan/2023wave2/power-automate/store-cloud-execution-history-dataverse)

However the Data Export product feature (still in private preview) will make this available and we are doing the work to make this consumable for an upcoming release of the kit.
