### ISSUE TITLE
[CoE Starter Kit - QUESTION] Only Admin View app was NOT upgraded

### ISSUE THREAD

**Issue by Mina-mppm** [microsoft/coe-starter-kit#9301]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello everyone.

I recently upgraded CoE Core Components solution from ver. 3.20 to ver. 4.45. I had not upgraded in a very long time and had some issues, but finally it seemed to work.
After the import process, I opened the Power Platform Admin View app and the sitemap still seemed to be on the old version. 
When I checked the last update date of the app, everything else was up to date, but only Admin View was 2 years old. Next, I checked the Admin View solution layer and again the "modifiedon" was 2 years old (no unmanaged layer).

What is the best way to resolve this situation?
Any comments are appreciated.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot like this so we can see what solutions you have installed in this environment? Be sure to show all records (all rows) and expand the indicated columns so that we can see full names
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8dd512cc-21fc-4c64-adab-0f64c29b9bf2)

**Comment by Mina-mppm** [comment]
@Jenefer-Monroe 
Thanks for the reply.
I have captured the screen of the solution list.
(Please excuse the labels are in Japanese)

![Image](https://github.com/user-attachments/assets/4dcb9c7e-a7e8-46e1-87a2-67c5eaf31f46)
![Image](https://github.com/user-attachments/assets/0143eec9-8b32-4c9c-95cd-caecf861d109)

**Comment by Jenefer-Monroe** [comment]
Do you have an unmanaged layer on the site map? If so, please remove it and see if that resolves.
You may need to hit "Publish all customizations" after you do this. 
![Image](https://github.com/user-attachments/assets/c335bdfe-e4d3-4962-849e-b22b92e878b5)
![Image](https://github.com/user-attachments/assets/d6f9d45b-2c83-4005-b412-e78c5d2eb111)
![Image](https://github.com/user-attachments/assets/5e67f95e-4a50-4a4f-9cb5-421fbc4bdb08)

**Comment by Mina-mppm** [comment]
@Jenefer-Monroe 
There are no unmanaged layers in the sitemap.
Also, I pressed “publish all customizations” after importing a new version of the solution.

The upgrade did not work, so I restored this environment.
I will try upgrade solution again and see if the same event occurs.

**Comment by Jenefer-Monroe** [comment]
sounds good. unfortunately the upgrade not working (ex site map not getting updates) is something the product team would need to investigate. Although I'm happy to keep debugging if you still repro after you try to upgrade again.

**Comment by Mina-mppm** [comment]
I restored the environment and attempted a two-step upgrade.
First, I upgraded from version 3.20 to 3.56. (I chose this version because 3.56 appeared to be the final minor version of the 3.x series.)
This seemed to work; Admin View had some sitemap updates and I could see that menus had been added.
Next I upgraded from 3.56 to 4.45. However, this yielded the same results as before. (sitemap not updating)

Is there any solution to this problem? The only ideas I can think of right now are

1. For some reason 4.45 is not compatible with my environment, so I try the September 2024 release, which is one version earlier
2. Try a 3-step upgrade from 3.20 -> 3.56 -> 4.x (smallest minor version of the 4.x series) -> 4.45
3. Give up everything and import the latest components into the new environment
4. Send a service request to product support to investigate the cause

Thank you all for your kindness.

**Comment by Jenefer-Monroe** [comment]
Yes unfortunately I am not sure how to assist here. If the upgrade is not working I dont know if smaller version hops will work. 

If you open a product support request. I suggest you tell them just that a site map is not updating. And if they push back that this is CoE Starter Kit and so they wont help, point them to the FTE PM in the space @Grant-Archibald-MS 

Sorry I can't be of more assistance here.

**Comment by Mina-mppm** [comment]
I will follow your suggestion and make a query to the product support focusing on the fact that the sitemap of Managed Solution is not updated.

I greatly appreciate the several kind comments you have made so far. And I trust that this community will continue to grow.
Thanks so much. @Jenefer-Monroe

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
