### ISSUE TITLE
[CoE Starter Kit - BUG] CLEANUP HELPER - Solution Objects failed flow's runs

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#9303]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hello!

We have the last November upgrade - the version 4.45 in the Core components solution.

We noticed that the CLEANUP HELPER - Solution Objects flow started to fail after the upgrade.

The issue that we see is this:
![Image](https://github.com/user-attachments/assets/90619642-2ab8-4491-8f02-a1af963bdcf3)

![Image](https://github.com/user-attachments/assets/4172c91c-206e-490a-bfaa-6188a5207ff9)

This flow fails quite often.

![Image](https://github.com/user-attachments/assets/7ca473a5-e1db-44b7-b501-5f4f158ac73b)

May we ask what could be the reason for this, and whether this can be fixed?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45 

### What app or flow are you having the issue with?

CLEANUP HELPER - Solution Objects

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
What is the output of the call? That will show us the error.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
