### ISSUE TITLE
CoE Environment Variable setup

### ISSUE THREAD

**Issue by RakeshSidd** [microsoft/coe-starter-kit#9307]
1) Please guide-us for bellow mentions environment variables, as there value are missing, what should i add in it.
List of flows
App Connections Dataflow ID
App Dataflow ID
App Usage Dataflow ID
BusinessValueAppUrl
BVA_AdminEmail
Environment Dataflow ID
Environment Request Admin App Url
Flow Connections Dataflow ID
Flow Dataflow ID
Flow Usage Dataflow ID
Host Domains
InnovationBacklogAppURL
InnovationBacklogLink
Maker Dataflow ID
Model App Dataflow ID
Training In a Day - Feedback Form

2) we are also getting the bellow error need help for the same.
The environment '00000000-0000-0000-0000-000000000000' could not be found in the tenant '00000000-0000-0000-0000-000000000000'.
 
Session ID: 00000000-0000-0000-0000-000000000000

**Comment by Jenefer-Monroe** [comment]
dupe to https://github.com/microsoft/coe-starter-kit/issues/9323
