### ISSUE TITLE
Updating policies in the DLP Impact Analysis tool

### ISSUE THREAD

**Issue by zPowerPlatform** [microsoft/coe-starter-kit#9309]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Created a policy and ran DLP impact analyzer but it looks like the policy was actually applied to the tenant. Microsoft team confirms that a user account changed the policy and after 2 mts revert the change. Its the same account we used to run the DLP impact analyzer at that time. So wanted to understand if some thing went wrong at that time or it was a user error

### Expected Behavior

If we ran DLP impact analyzer it should just let us know the impact without applying the policy itself

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

data policy impact analysis

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by QuinnNguyen-WI** [comment]
Hi @Jenefer-Monroe , I'm Quinn, a support engineer from Dynamics 365 Power Platform team. I'm currently the onwer of the ticket with the customer on this issue. Here is the current information from our side:
- The customer created a DLP policy which applied to an environment.
- The policy used to include 1 environment but on 31th Oct (2024-10-23 03:44 AM UTC), a user (likely accidentally) changed it to exclude 1 environment (i.e., changed it's type from OnlyEnvironments to ExceptEnvironments). This resulted in the policy being applied to all environments except 1.
- We want to double check with your side on this.

**Comment by Jenefer-Monroe** [comment]
I went ahead and added an "are you sure" dialog so people won't accidently update. Locasl fixed for Jan with https://github.com/microsoft/coe-starter-kit/issues/9344

![Image](https://github.com/user-attachments/assets/473785fe-813b-4a83-88a6-3bf5ef2df4c6)
![Image](https://github.com/user-attachments/assets/95c8088d-c15f-4e7d-ba17-ced9a5cfb65d)
