### ISSUE TITLE
[CoE Starter Kit - BUG] CoE Admin Command Center - Please download and install the latest version banner

### ISSUE THREAD

**Issue by Daren2023** [microsoft/coe-starter-kit#9310]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

After completing the November 2024 CoE update, the Admin Command Center has the following yellow banner in the bookmarks section: Your CoE Starter Kit solution was installed on Jul 2024. The latest version was released on Nov 2024. Please download and install the latest version.
![Image](https://github.com/user-attachments/assets/1b80b883-e2e6-4e98-a4bd-34b63dc3778a)

Also, after the updating Core solution to version 4.45, it still shows the created date as 4 months ago. 
![Image](https://github.com/user-attachments/assets/fb0df37a-0232-4667-90ac-a5281a271484)
Is this a similar glitch as was reported during the August update? Or should I reinstall the core solution?

### Expected Behavior

A recent install date associated with the core solution install.
No warning saying that the last update was in July 2024 in the Admin Command Center. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Admin Command Center

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Import core solution 4.45.
Run CoE Setup and Upgrade Wizard.
Run Admin Command Center app.
Review core solution creation date column.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
