### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Impact Analysis don't recog 'HttpRequestReceived' conector

### ISSUE THREAD

**Issue by lucasubieta** [microsoft/coe-starter-kit#9311]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

When using the app "DLP Impact Analysis", we need to be cautious because it doesn't detect the "HttpRequestReceived" connector. I added an environment under a DLP policy, and before save the changes, the "Impact Analysis" showed impacted apps or flows. However, I later discovered an error within my environment related to the HttpRequestReceived connector, there were few flows stopped because of dlp.

Upon reviewing the production Power BI dashboard for that environment, I noticed that the HttpRequestReceived connector was not included in the list of connectors for that environment.

Regards, 
Business Conectors :
![Image](https://github.com/user-attachments/assets/1b5aec26-a834-425c-844f-d841933f5388)

Blocked Conectors :
![Image](https://github.com/user-attachments/assets/4859175a-5234-44c6-95e5-64df39919a59)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

DLP Impact Analysis

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello, this was posted and addressed for the Nov release via https://github.com/microsoft/coe-starter-kit/issues/9104
