### ISSUE TITLE
Setup Wizard Next button grayed out

### ISSUE THREAD

**Issue by AnjaliBargota** [microsoft/coe-starter-kit#9317]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Center of excellence setup wizard-Why is the "Next" button on the Run Setup Flow page not enabling even after all flows have run successfully for two days?
![Image](https://github.com/user-attachments/assets/4f730ca4-7090-4d20-a53d-c8c74647e39b)

### Expected Behavior

The run setup flow page should have the next button enable as all the flows run backend as follows
1)
![Image](https://github.com/user-attachments/assets/c6735a4d-5586-4060-9a85-78aa785674ed)
2)
![Image](https://github.com/user-attachments/assets/6cafe3c8-f772-42ac-a951-5cad34ef88e5)
3)
![Image](https://github.com/user-attachments/assets/d997b8d6-d99e-425f-965e-522b32e1c99a)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

CoE setup and update wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Sometimes a second record for the flows gets added to the metadata. Please boot the app again today and try again.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
