### ISSUE TITLE
[CoE Starter Kit - BUG] Production PA flow suspended in Power Automate due to DLP policy in draft

### ISSUE THREAD

**Issue by ahanjra** [microsoft/coe-starter-kit#9320]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Production PA flow suspended in Power Automate due to DLP policy in draft. ![Image](https://github.com/user-attachments/assets/d9ccb232-73d6-4f98-ae4a-ae708a19abf2)
![Image](https://github.com/user-attachments/assets/549149f0-7acb-4ec5-92df-ebb4b505f387)
![Image](https://github.com/user-attachments/assets/c6ff8697-fb00-4483-a5c6-b5d4ac716234)
. However, we halted at the impact analysis step and did not proceed to save the policy(Screenshot 1). The owner of the flow received 160 emails that his Power Automate flows for the Luware/VOIP integration using connectors Nimbus DE and HTTP connector were suspended, due to an Admin data policy called "Test". A thing to note that we never added these mentioned connectors in "test" DLP policy that we were configuring and never published the policy.

### Expected Behavior

 The DLP policy in draft should not be auto published and block connectors which are not even part of it.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.43

### What app or flow are you having the issue with?

Data Policy Impact Analysis

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
I have validated both by testing and looking inside the custom page that we do not update the policy when you create a draft. 
Please take a look and let me know your thoughts.

## Update policy
Here is the call that updates the policy, caslled form "Update policy" button
![Image](https://github.com/user-attachments/assets/3e5c59cc-472b-4e3d-84c0-106f4ff40892)

And that is the only place we call it
![Image](https://github.com/user-attachments/assets/51d536b8-cb02-47bc-912f-35168125bb34)

## other write operations
I looked for all PowerPlatformforAdmins actions and you see we do set type things in the following cases:
![Image](https://github.com/user-attachments/assets/85008e6e-07f1-4c06-bbaf-de99c05bcd92)
![Image](https://github.com/user-attachments/assets/8885aa1a-4610-4f67-bf66-871278bcc303)
![Image](https://github.com/user-attachments/assets/594f4e2b-bc0f-486d-808f-6608a4c84407)

**Comment by Jenefer-Monroe** [comment]
I went ahead and added an "are you sure" dialog so people won't accidently update. Locasl fixed for Jan with https://github.com/microsoft/coe-starter-kit/issues/9344

![Image](https://github.com/user-attachments/assets/473785fe-813b-4a83-88a6-3bf5ef2df4c6)
![Image](https://github.com/user-attachments/assets/95c8088d-c15f-4e7d-ba17-ced9a5cfb65d)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
