### ISSUE TITLE
Changed envt url and now flow not gathering correctly

### ISSUE THREAD

**Issue by RickKush** [microsoft/coe-starter-kit#9322]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

The CLEANUP - Admin | Sync Template v4 (Check Deleted) flow has an error in the CurrentEnvtInventory, The provided host name ... could not be resolved. I changed it. Where can I correct it?

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v4 (Check Deleted)

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Can you please share a screenshot of where you are seeing an issue? 

Note that you need to be logged in to GitHub to share images, responding in email does not share them.

**Comment by RickKush** [comment]
TYVM!!!
