### ISSUE TITLE
[CoE Starter Kit - QUESTION] COE Setup on Trial Instance or other Instance ?

### ISSUE THREAD

**Issue by rs06051998** [microsoft/coe-starter-kit#9325]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I want to demo the COE Capability to the client, before I can implement the COE in the client environment.
So is there a way to setup the COE in Trail Instance or any dummy environment created by Microsoft where I can setup the COE and explore the functionality without any license requirement.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately no there is not.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
