### ISSUE TITLE
[CoE Starter Kit - Audit logs]  Microsoft Graph and Office 365 Management simult.

### ISSUE THREAD

**Issue by lucasubieta** [microsoft/coe-starter-kit#9326]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi, i have a question as my audit logs process is failing, i activated both procceses. 
What happens if I activate both Microsoft Graph and Office 365 Management APIs in Azure apps to collect audit log data? thanks

### What solution are you experiencing the issue with?

None

### What solution version are you using?

July 24

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Do you mean that you have both API permissions in the app registration? Thats totally ok. I do that myself so I can go back and forth when testing. 
![Image](https://github.com/user-attachments/assets/8dbf1e82-4a59-443d-bfe9-e646d171d2bc)

The flow will only use one or the other depending on this environment variable: 
![Image](https://github.com/user-attachments/assets/37099c70-f347-4437-9502-e3dd40b9e2ab)

**Comment by lucasubieta** [comment]
I understand now, thanks a lot!
