### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Gather Tenant SRs flow failing due to an environment not present anymore

### ISSUE THREAD

**Issue by madijk1969** [microsoft/coe-starter-kit#9327]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

The Admin | Gather Tenant SRs flow is hitting an environment that is not available anymore and as such can't access the DNS link anymore. 

![Image](https://github.com/user-attachments/assets/2faf8899-b6cb-4354-9f1d-a764243ae147)

![Image](https://github.com/user-attachments/assets/b0033674-e099-4bcd-85b8-aac30c2d7cb7)

I contacted Microsoft Power Platform support who mentioned "The second environment is not retrievable in our telemetry and the Product group has confirmed that it has been deleted in 2021. Therefore, we have suggested raising the concern to CoE to check on their end."

### Expected Behavior

Obviously we expected the flow to go only through environments that are available and online. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Admin | Gather Tenant SRs

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Open the Admin | Gather Tenant SRs
2. Run the flow
3. No issues

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
