### ISSUE TITLE
[CoE Starter Kit - QUESTION] Flow Last run ON FIELD is blank

### ISSUE THREAD

**Issue by ClaudioRWS** [microsoft/coe-starter-kit#9328]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello everyone, how are you?

There was something I wasn't noticing in the Admin View, column "Flow Last run ON" is coming up blank regardless of whether the flow was recently modified or not.

Is there something broken?

![Image](https://github.com/user-attachments/assets/045d0703-8cd3-433f-b5d8-82438000cdc0)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. This information is not yet available to us for the cloud flow architecture. 

The product team does now write this in a consumable way for us but it would be API prohibitive to consume. Please see [Store cloud flow execution metadata in Microsoft Dataverse](https://learn.microsoft.com/power-platform/release-plan/2023wave2/power-automate/store-cloud-execution-history-dataverse)

However the Data Export product feature (still in private preview) will make this available and we are doing the work to make this consumable for an upcoming release of the kit. Target Jan 2025
