### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Vignes29** [microsoft/coe-starter-kit#9329]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

We have got an error "Your flow has been turned off because flow is running more actions than expected".

As the result of this error the flow is suspended and turned off.  We have to fix this issue as it happened only 2 days back.

![Image](https://github.com/user-attachments/assets/50a28576-7f28-48e5-b99b-4bf77cccd7d6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

July 2024

### What app or flow are you having the issue with?

SYNC HELPER - Get Security Role Users

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately this is a high API activity. I've added a few options for you here, please let me know your thoughts. 

## Reduce what is tracked
There are two ways you can do this, both via the Manage Permissions app
1. Reduce the number of SR's you track
By default we only track a small set of SR's as shown here. Have you increased what is tracked? If so you may need to reduce.
![Image](https://github.com/user-attachments/assets/dfe0843e-bca0-4a1e-86c2-6aa6e2cc261e)

2. Do not track BU's 
By default we do not track these via BU, but if you have configured it that way then you may need to reduce that granularity
![Image](https://github.com/user-attachments/assets/279f5e9d-9161-4bfd-a793-9a2d34153aa3)

## Buy additional licenses
There are a few options here, and I am not a licensing expert, but this should get you started.
1. Buy a Per Process license and apply it to this flow. See [Capacity licenses](https://learn.microsoft.com/power-platform/admin/power-automate-licensing/types?tabs=power-automate-premium%2Cpower-automate-process%2Cconnector-types#capacity-licenses)
2. Buy add-ons for the flow. See [Types of Power Automate add-ons](https://learn.microsoft.com/power-platform/admin/power-automate-licensing/add-ons)

**Comment by Vignes29** [comment]
I did checked this earlier but we used to track only the default SRs. 

![Image](https://github.com/user-attachments/assets/3d6a854b-2606-4a6b-aaf8-8d463fc5c45e)

**Comment by Jenefer-Monroe** [comment]
OK unfortunately then you will either need to just turn this off and not gather this information, or buy licenses to get this data. 

## Buy additional licenses
There are a few options here, and I am not a licensing expert, but this should get you started.
1. Buy a Per Process license and apply it to this flow. See [Capacity licenses](https://learn.microsoft.com/power-platform/admin/power-automate-licensing/types?tabs=power-automate-premium%2Cpower-automate-process%2Cconnector-types#capacity-licenses)
2. Buy add-ons for the flow. See [Types of Power Automate add-ons](https://learn.microsoft.com/power-platform/admin/power-automate-licensing/add-ons)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
