### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v3 (Environment Properties) Flow Missing

### ISSUE THREAD

**Issue by GintasKun** [microsoft/coe-starter-kit#9337]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

We were looking for a '**Admin | Sync Template v3 (Environment Properties)**' flow on the CoE SK and could not find it.

It is listed in the documentation here: [https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components](https://learn.microsoft.com/en-us/power-platform/guidance/coe/core-components)

Description of the flow is as follows:
"This flow retrieves add-on, capacity, and security role information for environments. This information is retrieved from the Power Platform admin connector and from underlying Dataverse tables, and requires the user running the flow to have system administrator privileges in the environment."

We tried running the CoE Core Components Solution through PowerDocu and the flow is just not there. Also, couldn't find any mention of it i nthe release notes.

Can you please advise if this flow exists / did exist?

We are looking at retrieving security role information, which I assume populates the **Environment Security Role Permission** table?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Environment Properties)

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
This flow was deprecated some time ago, maybe 6 months? I dont recall specifically. 

Here is where you can find the functionality: 

The **_CLEANUP HELPER - Environment Capacity_** flow which is triggered by the **_CLEANUP - Admin | Sync Template v4 (Other Objects)_** flow
add-on, capacity

The **_Admin | Sync Template v4 (Security Roles)_** flow which is triggered by the **_Admin | Sync Template v4 (Driver)_** flow
security role information

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
