### ISSUE TITLE
[CoE Starter Kit - QUESTION] Tracking Flow Run History

### ISSUE THREAD

**Issue by GarryPope** [microsoft/coe-starter-kit#9340]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello CoE Team,

I hope you are well. Can you please confirm that the CoE doesn't track Flow run history? 

What I mean by this is, for a Flow called "The important Flow" if it ran 3 times, then we have each run logged in the CoE.

I don't think it does, but wanted to check. I know there are other options out there now, such as "[Manage cloud flow run history in Dataverse (preview)](https://learn.microsoft.com/en-us/power-automate/dataverse/cloud-flow-run-metadata)" and also "[Set up Application Insights with Power Automate](https://learn.microsoft.com/en-us/power-platform/admin/app-insights-cloud-flow)", but I wanted to check if anything is in the CoE first.

Thanks very much,

Garry

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. You are correct, this information is not yet available to us for the cloud flow architecture. 

The product team does now write this in a consumable way for us but it would be API prohibitive to consume. Please see [Store cloud flow execution metadata in Microsoft Dataverse](https://learn.microsoft.com/power-platform/release-plan/2023wave2/power-automate/store-cloud-execution-history-dataverse)

However the Data Export product feature (still in private preview) will make this available and we are doing the work to make this consumable for an upcoming release of the kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by GarryPope** [comment]
Hello @Jenefer-Monroe,

Thanks for the advice. Have a good day.

Garry
