### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by jachalou** [microsoft/coe-starter-kit#9342]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello,

i would like to know what flow does feed table Makers? I want to create my own welcome email, which would be triggered be new record in this table, however i cannot identify how this is feeded and if its working properly or not as i have different Makers data in TEST vs PROD.

Thank you

Regards,
Jakub Chaloupka

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
The welcome mail is triggered when a user is added to the maker table by this flow: **_Admin | Welcome Email v3_**

Users are added to the Maker table in various spots in the kit. The main one is **_HELPER - Maker Check_**

You can have different groups for dev/test/prod if you'd like. Each envt stores this as an envt variable and is filled by the setup wizard when you run it. 

You can avoid an envt sending anything to any users for your testing with the **_Production Environment_** env var which you will also see in the setup wizard

Hope that all helps.
