### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by bdestrada** [microsoft/coe-starter-kit#9346]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi,

Recently, we encountered an issue with the connection reference for the **Admin | Sync Template v3 CoE Solution Metadata** flow. We had to reestablish the connection, which led to the error: "InvokerConnectionOverrideFailed. Failed to parse invoker connections from trigger 'manual' outputs. Exception: Could not find property 'headers.X-MS-APIM-Tokens' in the trigger outputs. Workflow has connection references." I attempted to recreate the trigger, but without success.

Can anyone help me?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.31

### What app or flow are you having the issue with?

Admin | Sync Template v3 CoE Solution Metadata

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Please log in as the user who’s identity installs and runs the kit and do the following:

### Fix connections. 
Browse to the connections in the envt. If there are any broken connections please repair them
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2198fb17-1107-4851-a744-f3b34e89d11d)

### Fix Connection References
Go to the Default Solution > Connection References
Make sure they are all pointed to the correct identity which is intended to run the flows by doing the below for all connection references.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/f630670f-9bf5-4c56-bf18-9693e0eeea01)
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/d4a34cc4-5d46-494e-9a7d-e9d570489159)

### Restart the flow
If the above does not resolve it, also try to restart the flow in case anything in there is cached.
