### ISSUE TITLE
[CoE Starter Kit - BUG] SYNC HELPER - Cloud Flows Fails to run if the flow owner is a Service Principle

### ISSUE THREAD

**Issue by johnvittneyk** [microsoft/coe-starter-kit#9349]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Core Components Flow - "SYNC HELPER - Cloud Flows" - Fails to run if the flow owner is a Service Principle.

Action "Get Flow Owner Role as Admin" returns an empty array. This is being used in the later action "Get actual object for owner" which uses the output of first action as filter. This fails with this error message - The specified user(Id = {0}) is disabled. Consider enabling this user. Additional Details: {1}

![Image](https://github.com/user-attachments/assets/bcddc869-d04f-4c25-a499-516ecbb5b6b6)

![Image](https://github.com/user-attachments/assets/a1c72827-1efd-4425-a6a1-0d48341a149e)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

 SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Can you please share what this looks like during a run?

**Comment by johnvittneyk** [comment]
Hello Jenefer.
Here is what you asked. Appreciate all that you do to resolve the issues.
![Image](https://github.com/user-attachments/assets/161e818c-f2a0-43eb-801e-111d5b2f15e5)

**Comment by Jenefer-Monroe** [comment]
We've made some changes to this flow since your build to deal with this failure
![Image](https://github.com/user-attachments/assets/54ff63b8-8cb3-4468-b6c1-e6bab02e8f15)

I can't find the bug to point you for details. But I believe this should be addressed with your next upgrade.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
