### ISSUE TITLE
July release upgrade error

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#935]
### Discussed in https://github.com/microsoft/coe-starter-kit/discussions/925

<div type='discussions-op-text'>

<sup>Originally posted by **fz8975** July 28, 2021</sup>
While upgrading Core component solution to July release (from June release), I am facing below error. 
![image](https://user-images.githubusercontent.com/3690380/127333010-1e6cd826-a136-4644-80d4-82f273a873cc.png)

Error Text :
`Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 3 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoEAuditConnection, Id: 517df35f-3bd9-4424-993b-8988d6ba956c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEConnection, Id: ef2663c0-c9f1-4c38-b191-b18e4d62d6b7, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Audit Logs, Id: fa91974d-6e68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEAuditConnection, Id: ce3e2314-4d6d-4072-8ca9-bcc565fdac04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .`

 
I get an __Upgrade_ solution of the new version after this. 

I have tried to do upgrade from _Classic_ view but I get the same error. What am I doing wrong here ?

</div>

**Comment by manuelap-msft** [comment]
@fz8975 Please try Update, instead of Upgrade.

**Comment by fz8975** [comment]
It worked, thaks.
But while updating Innovation Backlog component, it is showing error **The import solution must have a higher version than the existing solution it is upgrading.**
Although Currently Installed version is 1.31, what could be the problem ?


![image](https://user-images.githubusercontent.com/3690380/127537278-c5eb65a1-e9a6-4d17-b2af-80560fce16bf.png)

**Comment by manuelap-msft** [comment]
This is a known issue tracked in #805. We had an error in our release pipeline (31 is higher than 4). We will address this as part of our August release, currently targeted for first week of August.
