### ISSUE TITLE
Power Platform Makers Group for COE (all makers not listed)

### ISSUE THREAD

**Issue by pakalask** [microsoft/coe-starter-kit#9350]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Good Morning, I have updated the COE few months ago and i have used M365 power platform admins, makers and visitors groups created in Azure AD to configure during the update. For some reason when i go to Azure AD and look at the Power Platform Makers group i don't see all the  makers (Users) who created the apps in that M365 group. Can you please let me know if there is a way to get all the makers so far listed in that group?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.29

### What app or flow are you having the issue with?

Not sure

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. 

There is a flow which adds new makers to the group: **_Admin | Add Maker to Group_**
Where the group used is configured in this environment variable: 
![Image](https://github.com/user-attachments/assets/e87f06c2-df2e-4266-b063-7502067a06e1)

It is triggered when new users are added to the Maker table in the CoE. Please be sure this flow is turned on.
Note though that if you configure this after your inventory has started being gathered then it will not go back and add the existing users in the Maker table. 
We do not have a technique for doing this in the kit but you could tweak the flow temporarily to perform the operation on new or edit in the trigger and then run the **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers)_** flow. 
That should do it. 
Be sure to remove the unmanaged layer afterwards if you decide to tray that.
![Image](https://github.com/user-attachments/assets/335e0d46-cb1a-4d5c-9f92-cdf9701864e4)

**Comment by pakalask** [comment]
Thank You. Yes i need to add existing makers too before this is configured. So for this i need to change the trigger from Added to "Added or Modified" for the Admin | Add maker to Group flow and run the flow CLEANUP - Admin | Sync Template v3 (Orphaned Makers) manually right?

**Comment by Jenefer-Monroe** [comment]
I believe that would work, yes.
Then be sure to return your flow to its original state by removing the unmanaged layer

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
