### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by Twoody8020** [microsoft/coe-starter-kit#9351]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Question: The 'Admin | Sync Template v4 (AI Usage)' flow is running successfully but only picking up unmanaged environments where I have AI Credits assigned.  It is skipping Managed environments (About 4) that I know is also using AI Credits that are assigned.  These Managed environments are also recognized in the Power Platform Admin View (Environments, PowerApps and Flows) but not showing in the AI Credits Usage section.  Am i missing a step to have Managed Environments picked up for the AI Credits Usage section.

The account has the System Admin role.    
The Managed environments are not excused from Inventory, compliance, cleanup, etc.
It seems that Managed Environments are not populating the table.

Flow: Admin | Sync Template v4 (AI Usage)
Toolkit Version: Governance - 3.25 , Core - 4.45

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Admin | Sync Template v4 (AI Usage)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
I believe you are experiencing this issue: https://github.com/microsoft/coe-starter-kit/issues/9343

I plan to fix for the January release. 

Thanks for posting.

**Comment by Twoody8020** [comment]
I checked #9343.  My users are only using credits in their own environment where it's allowed.  It's just weird that the only environments showing usage are unmanaged.  None of the Managed environments are showing at all with usage.  Look forward to the update in Jan!

**Comment by Jenefer-Monroe** [comment]
Appreciate your test case and I'll be sure to validate it with my fix.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
