### ISSUE TITLE
[CoE Starter Kit - QUESTION] The new features/ bug fixes Update for the CoE flows

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#9356]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello!
We had a question regarding some CoE flows from the Core and Governance solutions.
In our environment we have a "Custom flows" solution where we store some CoE flows with our own customizations. That means these flows will never automatically receive the updates that you add to these original flows. 
This is the list of flows that we have in this custom solution:

- CLEANUP HELPER - Power Automate User Shared With FLOW
- CLEANUP - Admin | Sync Template v3 (Power Automate User Shared With FLOWS)
- Request Orphaned Objects Reassigned (Parent)
- Request Orphaned Objects Reassigned (Child)
- HELPER - Send Email
- HELPER - Maker Check
- HELPER - CloudFlowOperations 
- HELPER - CanvasAppOperations
- Microsoft Teams Admin | Welcome to Your Teams Environment
- Admin | Welcome Email v3
- Admin | Archive and Clean Up v2 (Clean Up and Delete)
- Admin | Archive and Clean Up v2 (Start Approval for Flows)
- Admin | Archive and Clean Up v2 (Start Approval for Apps)

Since these flows are customized by us, and as we said we do not receive the updates for them, we were thinking to have a "rule" of how often we need to check the original CoE flows, to collect all the new features/bugs, and then either manually insert these changes to the custom flows or if the features and bug fixes are "big", then to take the original CoE flow, delete our custom flow, and just apply our customizations to these coe flows again from the beginning, so that it automatically stores all the features. We were thinking what is better to do and how often we need to do that, as we, for example, can leave the flow for 1-2 years without touching it, but it could be that by this time the original CoE flow already received a lot of new changes that also might be great to have. That is why, we were thinking, could we ask you how often you add changes/features/ bug fixes to these particular flows? Based on that we might think of the best approach here.  As we need to decide how often we then need to adjust our custom flows and what is the best approach - manually or by copying the flow itself. Because it could be that some of them you change also once in 1-2 years, that means we do not think a lot about the particular flow, But also could be the opposite - you adjust some flows every month, meaning it is better for us to check frequently the flows. But if the changes are small - we can add manually. If a lot of changes that difficult to just manually add - then we can decide to create a new copy.

Could we also ask for your opinion?

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately I couldn't give you a good answer on this. I can tell you that we do our best efforts to expose all changes we make in the kit in the summaries for each release. So your best bet will be to monitor those monthly, even if you don't do the upgrade. And that way you can see if a change is impacting one of these flows, and if so if its a sufficient improvement for you to do the work to merge into your customized flows. 

Here is an example from Nov 2024 release
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024
![Image](https://github.com/user-attachments/assets/e979e4a7-21ad-4512-8ead-c883a4eb93b1)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
