### ISSUE TITLE
[CoE Starter Kit - QUESTION] question regarding some apps

### ISSUE THREAD

**Issue by JanetK12** [microsoft/coe-starter-kit#9358]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello!
We had some questions regarding some certain apps.

We noticed that some apps are either too slow or just does not show any information, and we wanted to understand whether it needs to be like that or no:

1) Admin - Access this Flow app

This app just opens this view
![Image](https://github.com/user-attachments/assets/883f037a-c305-4ee1-b47b-e4e088ba431d)

I am not sure to what exactly app I can grant access or add new users as it does not show any apps. Does it needs to be like that? because we wanted to test the buttons, whether they work, but it wont show anything correctly if the app is not shown.

Also the button to delete app is there, but again,it does not show what app will be deleted if i click to this button
![Image](https://github.com/user-attachments/assets/f7ff72ae-9876-4bee-89dc-500c7491a0de)

2) CoE Theme Editor

![Image](https://github.com/user-attachments/assets/5e75b37a-e34c-412b-9d20-303d81bcf3fc)

when I click to the button to create the new theme, it shows empty screen; or it just shows these points as it is refreshing or loading, but I waited for some time and still nothing showed.

 ![Image](https://github.com/user-attachments/assets/07adca74-7d9a-4130-b4c7-bc19e3ce3a50)

does it needs to be like that?

3) App Catalog

this app does not show anything in each of these 12 fields. Maybe it needs to be like that?

![Image](https://github.com/user-attachments/assets/e715d31c-5524-4ec1-8142-3174ae3e4b34)

4) Manage permissions app

This app is just really slow. It shows result but it takes a lot of time to just find one item. Could we ask, what does the speed depend on and should it be that slow? 

Thank you in advance! We just wanted to understand whether there is an issues in the apps or they need to stay that way, and that ok for now.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. Hope the below helps.

## Access this App/Flow
These work only when embedded in the PBI. Please see [Configure embedded apps in the CoE dashboard](https://learn.microsoft.com/power-platform/guidance/coe/setup-powerbi#configure-embedded-apps-in-the-coe-dashboard)

## CoE Theme Editor
This app was cut from the CoE Starter Kit several years ago as theming features were brought into the product itself.

## App Catalog
This app being blank by default is expected, you will configure what apps are shown there. 
Please see [App Catalog](https://learn.microsoft.com/power-platform/guidance/coe/core-components#app-catalog)
![Image](https://github.com/user-attachments/assets/2a6d0830-fb74-413e-af6c-8880b19d245a)

## Manage Permissions
I presume you mean for these screens is that correct? If so we did do a few perf improvements to this in the Nov release. 
In the past the app was using collections needlessly and now its attached directly to the data.
Please be sure you don't have unmanaged layers on the custom page, and if you still have bad performance perhaps do your permission updates from the Power Platform Admin View. 
![Image](https://github.com/user-attachments/assets/fdeef8cf-2f2b-4408-b1d4-9ee686c80c36)

**Comment by JanetK12** [comment]
@Jenefer-Monroe   thank you for your answer!

Could I ask what means custom page from your sentence "Please be sure you don't have unmanaged layers on the custom page"?

**Comment by Jenefer-Monroe** [comment]
Certainly, if you have unmanaged layers on objects then you wont receive updates. 

You can check for those as shown below, and we also do let you know about them when you upgrade in the Setup Wizard

![Image](https://github.com/user-attachments/assets/f01345a4-308f-4ee0-97ee-d2e77e5ce6c7)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
