### ISSUE TITLE
[CoE Starter Kit - BUG] if App is deleted manually by App Owner, it still sends reminder for the app backup to App Owner

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#936]
### Describe the issue

Hello Team,

This is regarding the Audit process of CoE Governance component version 1.61.

It's noticed as I test, that once the user deletes an app manually before the "Delete Date" - In this case, the user still receives a reminder of backing up an email.

It seems, if a user deletes an app manually after "Approve" - it does not store "Delete Completion" as "True" in the "Archive Approvals" table.

Should not we have a condition that sends backup reminders only if an app is not deleted?

![image](https://user-images.githubusercontent.com/13658386/127475664-280b2c6e-72b3-4d0f-8815-f72523c113a9.png)

Could you please share when "admin_appdeleted" == true in the "PowerApps App" table and "Delete Completion" == true in the "Archive Approvals" table is updated in case if a user deletes the app manually? - I think this will clarify my doubt.

Kindly help!

Thanks and Regards,
Dipti

### Expected Behavior

App Owner should not receive reminders if App is deleted manually by app owner.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Admin | Archive and Clean Up v2 (Start Approval for Apps) Admin | Archive and Clean Up v2 (Start Approval for Apps)  Recurrence

### Steps To Reproduce

1. App Owner receives "Approval Email" to archive an app.
2. App Owner approves to delete.
3. App Owner manually deletes an app.
4. App Owner receives reminder email to backup an app next week.

**Comment by JeneferM-MSFT** [comment]
Hello. Another flow tests for this. The person should not receive emails again if they manually delete. Please let us know if you see otherwise.

**Comment by DiptiC-InsightRun** [comment]
Hi Jenefer,

Maker is receiving the backup reminder, in case if the maker has deleted an app manually in my case.

Can you share what could be wrong? what does it mean about "Another flow tests for this."? Do you want me to check any other specific flow?

Looking forward!

Thanks,

**Comment by JeneferM-MSFT** [comment]
Did they approve and manually delete or just manually delete? 
Is your Check Deleted flow running and passing successfully?

**Comment by JeneferM-MSFT** [comment]
We had the configure run after incorrect at this step for the apps version of the flow (correct for flow)
![image](https://user-images.githubusercontent.com/62659043/127550202-15f5e1a8-6a61-40bd-bafd-a8bb1e798379.png)

Thanks for catching. Fixed for August

**Comment by DiptiC-InsightRun** [comment]
Hi Jenefer,

**Regarding questions:**
Did they approve and manually delete or just manually delete? - Yes, they approved and then deleted manually.
Is your Check Deleted flow running and passing successfully? - Yes, but it did not change the "admin_appdeleted" == true in the "PowerApps App" table OR "Delete Completion" == true in the "Archive Approvals" table

Can you please share what has been changed as the "configure run after" for the "send email" step?

For me it works as follows for Send email action:

1. If I set, configure **_run after as failed_**, It does not send back up reminder email even if the app exists. - which should not happen.
2. If I set, configure **_run after has succeeded_**, it does send the backup reminder email if the app is deleted - which should not happen.

I think it should be handled via condition control? as we require to satisfy both the condition 1) Send an email if the app is not deleted 2) do not send an email if the app is deleted.

Kindly help if I have miss understood anywhere.

Looking forward.

Thanks and Regards,
Dipti

**Comment by DiptiC-InsightRun** [comment]
Awesome! Thank you very much for clarifying!

**Comment by DiptiC-InsightRun** [comment]
Meanwhile, the "Get Flow"  action is currently failing at the Power Platform end, therefore, it will not send the reminder at all - which is a concern too.

For an instance,  "See if Flow still Exists" action is failing even though the flow resides in the environment that avoids sending the reminder to FLow Maker in any case. which should not happen as well.

![image](https://user-images.githubusercontent.com/13658386/127662292-a587a385-9cef-4856-adda-4829cbb057d0.png)

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Please post that issue separately, and when you do show the input parameters, aka what environment and flow it was. 
Please also create a new flow which just calls that action for that envt and flow and see if it returns correctly.
