### ISSUE TITLE
User is not authorized to read secrets - error trying to update secret env var

### ISSUE THREAD

**Issue by Pete1230z** [microsoft/coe-starter-kit#9360]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I am trying to input the environment variable in the Center of Excellence for the Command Center - Client Azure Secret, but when I do so I continually get an error saying User is not authorized to read secrets from - my secret key input here - resource.

I have tried several different steps, all the way up to being given administrative Azure rights, and still don't have access. 

I looked into past bugs and explicitly was given the ability to read in the Key Vault Secret User and update in the Key Vault Contributor Role with no luck.  I was then also given the contributor role as that was mentioned and the CoE still said I did not have access the the vault.

Is this a bug that is known, if not are there any troubleshooting steps?

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Command Center - Client Azure Secret 

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Pete1230z** [comment]
![Image](https://github.com/user-attachments/assets/1fc71b79-6a9f-4342-9b5f-f8ab815c897d)

I was given all of these rights and even created the key myself with no luck. I am still getting the same error message every time. We also validated that we do not have any IP restrictions enabled.

Are there any further troubleshooting steps?

**Comment by Jenefer-Monroe** [comment]
Can you make sure your permission settings are RBAS?
![Image](https://github.com/user-attachments/assets/8e230883-8da8-41ec-aac8-531930d2f8fd)

**Comment by Pete1230z** [comment]
I double-checked and I do have Azure role-based access control selected.

**Comment by Jenefer-Monroe** [comment]
From our app you see this correct? 
![Image](https://github.com/user-attachments/assets/77e2ef74-92f7-4e17-8fe5-b69f433968c4)

And then you click and are brought to the Default Solution > Environment Variables. 
![Image](https://github.com/user-attachments/assets/fd5774f3-165b-4b54-b151-16b7f4d06148)

So in the end you are trying to configure from this product UX correct? 
![Image](https://github.com/user-attachments/assets/689110e0-dd81-4a82-9c07-91b1e7a00a4d)

**Comment by Pete1230z** [comment]
Yes I just attempted to do it that way and I received the exact same error.

**Comment by Jenefer-Monroe** [comment]
Have you made sure that the Dataverse app is a Secret user? 
![Image](https://github.com/user-attachments/assets/e59d23cf-f4aa-4b49-9ef2-e7970789e872)

**Comment by Pete1230z** [comment]
This solved the issue, my admin gave me access but not Dataverse or the other applications access. Thank you very much for your responsiveness and support Jenefer, I really appreciate it!

**Comment by Jenefer-Monroe** [comment]
Glad I could help :)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
