### ISSUE TITLE
Not all flows represented in CoE Kit (System Flows)

### ISSUE THREAD

**Issue by Cathi029** [microsoft/coe-starter-kit#9361]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hi, 

there are flows that are not represented in CoE kit. The way I see it, these flows are not user-related flows created by the system. Is there a reason why these flows are not in the kit?
Here are a few examples: 
![Image](https://github.com/user-attachments/assets/7e9de43c-20fc-46a3-b7cf-a711b446354e)

Kind regards
Caddy

### What solution are you experiencing the issue with?

None

### What solution version are you using?

November 2024

### What app or flow are you having the issue with?

Power Platform Admin View

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
My guess is that these flows are unpublished. 
[Flows that don't get activated](https://learn.microsoft.com/power-platform/guidance/coe/limitations#flows-that-dont-get-activated)

And that if you turned them on they would show up after the next inventory run.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
