### ISSUE TITLE
[CoE Starter Kit - QUESTION] About Deleted Accounts

### ISSUE THREAD

**Issue by asuka1103131** [microsoft/coe-starter-kit#9364]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I am aware that “Maker is Orphaned” in the Maker table will be set to Yes when the account is deleted, is this correct?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

none

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
That is correct. When an account is deleted from Entra it will be recognized as such on your next run of **_CLEANUP - Admin | Sync Template v3 (Orphaned Makers_**) and be marked as “Maker is Orphaned”

Note that there is also an env var that you can set which will also make users marked "Disabled" in Entra to be considered orphan.
![Image](https://github.com/user-attachments/assets/642b7677-2a3d-4140-a511-5557101f7bbd)

**Comment by asuka1103131** [comment]
@Jenefer-Monroe 
What happens if my email address changes?

**Comment by asuka1103131** [comment]
The user will be a registered user in the Maker table.
What happens when a Power Platform user changes his/her email?

**Comment by Jenefer-Monroe** [comment]
Got it, thank you. 
We have two flows that run regularly and go update the information about users in the Maker and Power Platform Users tables, including their current email from Entra: 

- CLEANUP - Admin | Sync Template v3 (Orphaned Makers)
- CLEANUP - Admin | Sync Template v3 (Orphaned Users)

They are both called weekly by the **_Admin | Sync Template v3 (Call Updates)_** flow.

**Comment by asuka1103131** [comment]
Thank you. Is “Maker is Orphaned” only marked if the account is deleted from Entra?

**Comment by Jenefer-Monroe** [comment]
Yes, unless you have this env var set in which case users marked "Disabled" in Entra will also be considered orphan.
![Image](https://github.com/user-attachments/assets/642b7677-2a3d-4140-a511-5557101f7bbd)

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
