### ISSUE TITLE
CoE Starter Kit - Questions Regarding Deprecated Components in CoE Deployment

### ISSUE THREAD

**Issue by JJ-SJG** [microsoft/coe-starter-kit#9367]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

After conducting a SonarQube scan on the repository, we contacted Grant Archibald from Microsoft regarding the results. The scan highlighted 27 security hotspots [attached]. Grant confirmed that both the outdated coe_cli tool and the ALM Accelerator Sample are no longer actively used or required for any current or future low-code Power Platform solutions. He also informed us that the bundle contains deprecated components that may be triggering these alerts.

In light of this, I would like to inquire about the following:

1. Is there a way to deploy the CoE without including the deprecated components?
2. Is there an updated bundle available that excludes this outdated code?

Our Cybersecurity team has expressed concerns about deploying code to Production that raises code review alerts. We aim to mitigate any potential risks or, at the very least, better understand how we can implement effective mitigations.

Thank you for your assistance.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Sending to @Grant-Archibald-MS for comment.

**Comment by Grant-Archibald-MS** [comment]
@JJ-SJG Based on earlier discussion node NodeJs command line components (coe cli) are not used in the low code Power Platform Solutions of the CoE Kit.

The Release assets of the CoE Kit do not include or make use of the coe cli.

 The coe cli as noted in https://learn.microsoft.com/en-us/power-platform/guidance/coe/cli/overview has been deprecated and will be removed from the main branch of the GitHub repository and the Learn Documentation on this removed. 

The use of the coe cli is completely optional and requires the git clone of the repository and install of the components. This decision is completely separate that the decision to import and use Power Platform solution components of the CoE Kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
