### ISSUE TITLE
[CoE Starter Kit - BUG] Admin - App Permission Center not reliably listing or finding members

### ISSUE THREAD

**Issue by stevenhayles** [microsoft/coe-starter-kit#9368]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Admin - App Permission Center (AKA Manage Permissions) doesn't reliably list members or find new members to add. More often than not, it doesn't.

No list of members is displayed
![Image](https://github.com/user-attachments/assets/7e6ec6bc-89b5-438f-b3b8-9925bd99f6c1)

When trying to select a user, no results found is reported after about 7 seconds
![Image](https://github.com/user-attachments/assets/b005df28-0153-4414-9d53-bfb34fa0d9e1)

### Expected Behavior

Start Admin - App Permission Center
Select Apps or Flows in the left navigation
Click a check box beside an app or flow
Click Manage Permissions (towards top left, next to Refresh)

List of members pane appears on right, showing a list of accounts with permissions
![Image](https://github.com/user-attachments/assets/a3828644-6b5e-4aff-b137-d0ccaf5d2e1d)

Click Add User above the list and begin typing user name in search box. After 3 characters, list of matching account will be displayed
![Image](https://github.com/user-attachments/assets/a343aaba-831e-4bb4-8a96-7446cb8e5be6)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Admin - App Permission Center

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

Start Admin - App Permission Center
Select Apps or Flows in the left navigation
Click a check box beside an app or flow
Click Manage Permissions (towards top left, next to Refresh)
List of members pane appears on right, with no members shown
Click Add User and begin typing user name in search box. About 7 seconds after the first three characters have been typed, no results found is reported

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
