### ISSUE TITLE
How to look at User Billable Actions Per Day

### ISSUE THREAD

**Issue by Pete1230z** [microsoft/coe-starter-kit#9369]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

What is the best way to look at billable actions per day per user? I have looked at several different automation and dashboards and can not find this anywhere.

I want to find this feature so that I know if users are getting close to reaching their limits every day. Is there something premade within the CoE? 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

4.45

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Unfortunately this information is not available to use for consumption and I am also unaware of anywhere this is available in the product. 
Holding open to see if the community or internal pings I will start now surface any new information here.

**Comment by Pete1230z** [comment]
Thanks for the information Jenefer, do you happen to know of any best practices then on at least how to monitor this to ensure users do not go over?

**Comment by Jenefer-Monroe** [comment]
Unfortunately I do not know of a way.
