### ISSUE TITLE
[CoE Starter Kit - BUG] : Connection references not showing in PBI

### ISSUE THREAD

**Issue by yearwoodm15** [microsoft/coe-starter-kit#937]
### Describe the issue

Hello,

This is a follow up to ticket #640. After updating the CoE to its latest version, we still are unable to see some historical data through the Power BI dashboard. We would just like to see if there are any other options to try to retrieve this data, if possible. 

I have also found that some of the flows behind the Core Components solution are taking a long time to run. Main example being Admin | Sync Template v3 (Flows) - there are some jobs that have been running for 2+ days. I haven't encountered this issue before with other versions. Can you please provide assistance as to what the next steps are to resolve this and further prevent long running jobs like this in the future?

Thank you!

### Expected Behavior

I thought the update would help clear up some missing historical we couldn't see where users said that they're using certain connectors for apps. We're still unable to see it, what is the expected behavior?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### Anything else?

It's not letting me gather a screen shot of the different jobs running in the Admin | Sync Template v3 (Flows) right now, but will try to post it later if I can.

**Comment by JeneferM-MSFT** [comment]
What do you mean by historical data? 
For the long run, please see #917

**Comment by yearwoodm15** [comment]
Hi Jenefer,

Thank you for providing info on #917 - I do have some questions regarding this but I'm guessing I will need to put in a separate ticket, is that correct? When speaking about historical data, we had an issue in the past where users said they were using particular connectors, but we couldn't (and still cannot) see those analytics through the CoE dashboard. It sounded like the CoE version update may help resolve those issue but we are without luck in retrieving the connector data for some of these users. I was able to run an app test that verified that one of the connectors a user has used shows up behind CoE for me, but still nothing from them. I think you had suggested to verify if the Power Platform Admin View app could show the user data and it did - but for whatever reason it wasn't/isn't translating to CoE dashboard.

**Comment by JeneferM-MSFT** [comment]
Got it, so the issue is that the PBI is not showing connection references but the data is correct (aka they are showing in the MDA). 
Assigning to Manuela to take a look. 
Yes if you have an issue other than this one, please post separately.

**Comment by manuelap-msft** [comment]
Hello,

I will need a bit more details to help you here. What specific page are you looking at in the Power BI Dashboard? Are you on the very latest version of the dashboard - https://github.com/microsoft/coe-starter-kit/raw/main/CenterofExcellenceResources/Release/Collateral/CoEStarterKit/CDSLegacy_CoEDashboard_202107_v2.pbit?

Thank you
Manuela

**Comment by yearwoodm15** [comment]
Hi Manuela,

This was under the Connections area of the Power BI Dashboard. I do have the CDSLegacy_CoEDashboard_202107.pbit installed, last modification was 7/8/2021 for that file. Should I be running v2 instead?

**Comment by manuelap-msft** [comment]
Yes please, there were some known issues with the 202107.pbit version that were fixed with the _v2.pbit. If you could try that instead and let me know if you continue to see issues, that would be great!

**Comment by yearwoodm15** [comment]
Hi Manuela,

Sounds good - I will try to update today/tomorrow and let you know. Thank you!

**Comment by yearwoodm15** [comment]
Hi Manuela, quick question. With #917 am I creating a support ticket here to raise the throttle limit, or does it need to be placed elsewhere? Just wanted to confirm first before making one. Thank you!

**Comment by manuelap-msft** [comment]
Hello - it has to be a support request through the Power Platform Admin Center: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support#view-solutions-or-enter-a-support-request-through-the-new-support-center

**Comment by yearwoodm15** [comment]
Thanks Manuela, I spoke with MSFT about this as well. I think it's safe to close this one out, so I will go ahead and do so. Thank you!
