### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION

### ISSUE THREAD

**Issue by kotesharepoint1** [microsoft/coe-starter-kit#9370]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

https://github.com/microsoft/coe-starter-kit/issues/433

We are looking for flow run history or retrieve the last execution date of Power Automate since we have a problem in organization that one of the users has sent the emails using Power Automate with major impact. 

Please let us know if we have the capability in CoE toolkit to fetch the data and stop such flows immediately from Admin end instead finding the specific flow manually.

Looking for an alternative or latest product information on priority. 

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

September 2024 

### What app or flow are you having the issue with?

Audit log for cloud flows

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. This information is not yet available to us for the cloud flow architecture. 

The product team does now write this in a consumable way for us but it would be API prohibitive to consume. Please see [Store cloud flow execution metadata in Microsoft Dataverse](https://learn.microsoft.com/power-platform/release-plan/2023wave2/power-automate/store-cloud-execution-history-dataverse)

However the Data Export product feature (still in private preview) will make this available and we are doing the work to make this consumable for an upcoming release of the kit.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
