### ISSUE TITLE
[CoE Starter Kit - QUESTION] Uninstall of old core components solution not starting

### ISSUE THREAD

**Issue by TiBa7879** [microsoft/coe-starter-kit#9373]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Hello, 
I've upgraded the core-components solution from 4.37 to 4.45. Everything seems to work fine, but for the old version 4.37 the uninstall doesn't start. I've installed the 4.45 two weeks ago, and 4.37 is still there. The solution has no dependencies. I've tried to install 4.45 again today and it was successful again, but uninstall of 4.37 will not start. Shall I try a manually uninstall? Or what would you recommend?
Thanks & best regards

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
When upgrade fails the product often leaves an _Upgrade and an original solution sitting there. 
These will never converge or repair on their own, you will need to take action to resolve as a result. And until you do, you are in an unknown state.
If you go to history you may find where the failure occurred and download details about it.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/eb0966a6-dbfb-400b-b796-5ecb5d20c1da)
And if you don’t, then you should delete the _upgrade. And try to upgrade again to see either if it succeeds this time, or if you see the error message this time.
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/44eafb8d-a0b1-40e5-af3b-b3f1b502146c)
