### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance Process - Missing prerequisite - metadata flows to set up compliance process haven't finished running yet

### ISSUE THREAD

**Issue by bocESMI** [microsoft/coe-starter-kit#9376]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I am getting a "Missing prerequsite " error when set up the Compliance process https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components. 
Looking at the Admin | Sync Template v3 Configure Emails, the error is on Get ID Pass (under Uplodate last run as pass) and the error is UnresolvableHostName. The provided host name "XXXX" could not be resolved. 

The same issue is present in the Admin | Sync Template v3 COE Solution Metadata.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

Nov 2024

### What app or flow are you having the issue with?

Admin | Sync Template v3 COE Solution Metadata

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by bocESMI** [comment]
Hi Jenefer, sure I have attached some screenshots

The missing prerequisite error comes up when setting up the Compliance Process and Inactivity notifications process.
Flow #1 Admin | Sync Template v3 Configure Emails
Failure step is "Get ID Pass" The provided host name 'orgXXX.crm3.dynamics.com' could not be resovled
Flow #2 Admin | Sync Template v3 COE Solution Metadata
Failure Step is "List Envt Solutions" and the error is The provided host name 'orgXXX.crm3.dynamics.com' could not be resovled

I tried to upload screenshots but unable to do so.

**Comment by Jenefer-Monroe** [comment]
Can you please confirm that the user identity installing and running the flow has the Power Platform Admin Role assigned both directly and permanently? 
[Microsoft Azure Users](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/AllUsers) > Your User > Assigned Roles

Ensure Power Platform Administrator is Direct and Permanent
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/66096cf4-67ad-41c9-9900-0b3e46de0cee)

**Comment by bocESMI** [comment]
Hi Jenefer, just had a look and the account i am using has : Dynamics 365 administrator, Power Platform administrator, Fabric Administrator - all have membership = Direct , End time = Permanent and State = Active

**Comment by bocESMI** [comment]
Is it possible that creating the environment orgXXX original and then changing the name (https://centerofexcellencecoe-dev.crm3.dynamics.com/) somehow is causing this issue. Maybe the organXXX environment is registered in on of the tables and can no longer be found ...

**Comment by Jenefer-Monroe** [comment]
That is possible, its hard to tell without seeing an image, but I do know flows cache these urls sometimes. 
Can you restart whichever flow is failing? 
And see if the inventory has the new URL already in place?
![Image](https://github.com/user-attachments/assets/a02adc21-d8ce-42a3-b943-2fe1f94bf6da)

**Comment by bocESMI** [comment]
Finally got the flows to run by changing the connection on the action step that is failing .. for example, in the Admin | Sync Template v3 Coe Solution Metadata, I updated the connection for "List Envt Solutions" action.

**Comment by bocESMI** [comment]
> That is possible, its hard to tell without seeing an image, but I do know flows cache these urls sometimes. Can you restart whichever flow is failing? And see if the inventory has the new URL already in place? ![Image](https://github.com/user-attachments/assets/a02adc21-d8ce-42a3-b943-2fe1f94bf6da)

FYI .. I am not able to upload images here, it give me a fail error.

Thanks

**Comment by Jenefer-Monroe** [comment]
sorry im not sure what you mean by "updated the connection" can you clarify?

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
