### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Ashish-tripathi-dfi** [microsoft/coe-starter-kit#9378]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

After updating the COE kit and setting up with the CoE Setup and Upgrade Wizard, the flow does not complete and is running since 3 days, which leads to not syncing of some of the Environments which exists.

I tried cancelling and running it again but same issue is occurring
![Image](https://github.com/user-attachments/assets/048cb0d1-e5ab-4227-b771-d6ebfffd719a)

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
1. How many environments do you have in your tenant? 
2. Is the following flow turned on? Is it passing? **_HELPER - Driver Escalation Check_**

**Comment by Ashish-tripathi-dfi** [comment]
1. I have total 59 environments, currently 52 is showing in environments view
2. yes, the flow is turned on, yes it passes HELPER - Driver Escalation Check

![Image](https://github.com/user-attachments/assets/4fa1c9d6-e1d9-425b-843c-2067ca5528a6)

**Comment by Jenefer-Monroe** [comment]
ok. unfortunately you may just have to let the flow complete then so that we can see where its failing. That number of environments should only take maybe 15 minutes to run once it gets to that step.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
