### ISSUE TITLE
[CoE Starter Kit - QUESTION] Nurture Component

### ISSUE THREAD

**Issue by rs06051998** [microsoft/coe-starter-kit#9386]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

While I was exploring the Nurture component, I came across COE template.
So want to know what the featured flag do?
![Image](https://github.com/user-attachments/assets/72b50fab-c056-4bdd-afc2-f1888773c4e4)

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
You can make templates to share with your Makers. 
See [Template Catalog page in Nurture apps - Maker app](https://learn.microsoft.com/power-platform/guidance/coe/nurture-components#apps-3)

## Admin POV
![Image](https://github.com/user-attachments/assets/3f3f8810-0f1d-4d35-ae61-e41daa4d8faf)

## Maker POV
![Image](https://github.com/user-attachments/assets/1beeac1d-c65a-486e-a0b0-46684170535c)

**Comment by rs06051998** [comment]
Hi @Jenefer-Monroe , 
I have set the featured flag to No , still I can see the template in maker app.
So still want to know what the featured flag do?
Admin App
<img width="448" alt="Image" src="https://github.com/user-attachments/assets/569821c8-fcef-4919-ab91-acef2ccf4c4d" />

Maker App
<img width="462" alt="Image" src="https://github.com/user-attachments/assets/14283cbe-4c66-4ddd-9fb9-c5fe8ee06724" />

**Comment by Jenefer-Monroe** [comment]
It looks like we don't use that flag today. Not sure if it used to be used or if it was put in their for people's customizations. But we do not use it today.

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
