### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by ShreshtaShetty07** [microsoft/coe-starter-kit#9389]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

I am working with DLP impact analysis and few app and flow owner details are not recorded within DLP impact analysis even though they are using blocked connectors in the environment.

Please help in getting the proper data in DLP impact analysis

### Expected Behavior

We need all app and flow details in DLP impact analysis whenever the owners are using blocked connectors .
Currently not all details are recorded and we are facing the issue.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Data Policy Impact Analysis

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Hello. I do not repro this issue. 

Please share screenshots of the flows in question with their connectors (you can get this in the Power Platform Admin View app) 
Then screenshots of the DLP app as you walk through and expect to see them shown. 

Note that you need to be logged in to GitHub to share images.

**Comment by ShreshtaShetty07** [comment]
Hi Jenefer,
Thanks for the reply.
To add to the issue we are facing, when checked Power Platform Admin View app --> Flows --> we are not able to see all the connectors which is used in flows.
May be that's the reason the flow details were not recorded in DLP impact analysis.
Can you help here please.

Thanks again!

**Comment by Jenefer-Monroe** [comment]
It sounds like your Microsoft contact is trying to get approval for you to have time with me. 
Its very difficult to debug without screenshots so hopefully he succeeds. :)

**Comment by Jenefer-Monroe** [comment]
worked together offline. inventory was not running so should be all fixed up now. YEAH

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
