### ISSUE TITLE
[CoE Starter Kit - BUG] CoE does not inventory unpublished Model Driven apps

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#9390]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

When the inventory runs for CoE, it is not collecting inventory information for un-published Model Driven apps, so they do not show up in any reports/admin views.

If I go to the Power Apps maker portal, I can see the apps listed, but no record exist in CoE. 

I have run a full inventory as well, no change. 

### Expected Behavior

Expected to inventory ALL items in environments, even if unpublished. There is even a column that has published status, so I would expect an unpublished model driven app to show. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45 - Nov 2024

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Driver)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Create new model driven app. Save it. Do nothing else.
2. Inventory runs for CoE.
3. See new model driven app does not appear in inventory. 

### Anything else?

I need to be able to get accurate reporting, as Model Driven apps are premium, but there is nothing that lets me stop users from creating them in the default environment. I need to be able to run automated reports from CoE to alert me when a new item is created so I can take action as an admin. Currently CoE is not pulling accurate information.

**Comment by Jenefer-Monroe** [comment]
Hello. Unfortunately this is a known limitation. The product does not surface these to us in the tables where we gather Model Driven Apps. 

Please see [Unpublished model-driven apps](https://learn.microsoft.com/power-platform/guidance/coe/limitations#unpublished-model-driven-apps) from our [limitations](https://learn.microsoft.com/power-platform/guidance/coe/limitations) page.

The "published" field is used for the canvas type apps.

**Comment by pnoot7** [comment]
Ah, well that explains it. Hopefully PG will make this available, as it would be very useful. Thank you for the reply.
