### ISSUE TITLE
[CoE Starter Kit - QUESTION] Does Audit Log with Graph API handle fewer loads compared to the Office Management API?

### ISSUE THREAD

**Issue by syncmaster851** [microsoft/coe-starter-kit#9392]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

We have two environments, 
1. For Test env, we switched to the Graph API by update the environment variable, 
2. For Production env, it still using the original office 365 Management API version.

The audit log flows in these two environments are functioning correctly; however, there is a discrepancy in the number of LaunchApp logs. Additionally, the Graph API appears to handle fewer loads compared to the Office Management API.

Date | Prod (Office 365 Management API) | Test (Graph API)
-- | -- | --
Dec 3rd, 2024 | 5079 | 4816
Dec 4th, 2024 | 5320 | 5009
From this week (Dec 12th, 2024) | 9500 | 8700

Is that expected? 

### What solution are you experiencing the issue with?

None

### What solution version are you using?

Nov 2024

### What app or flow are you having the issue with?

Audit Log v2 (Graph API)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by syncmaster851** [comment]
I suppose this is discussed in https://github.com/microsoft/coe-starter-kit/issues/9190, We are trying with 2880 end time and 2945 look back, hope to get a 99.8% completion in next few days testing.

**Comment by Jenefer-Monroe** [comment]
Yes I believe you found it. Unfortunately it appears (anecdotally from my experience as well) that the Graph API takes longer to see the records that the O365 Management API for non-small tenants.
