### ISSUE TITLE
I need support to upgrade the CoE toolkit

### ISSUE THREAD

**Issue by KarumanchiVenkat** [microsoft/coe-starter-kit#9393]
I need support to upgrade the CoE toolkit and i heve old coe toolkit version i.e may2024. colud you please guide new version to upgrade coe [toolkit.](![Image](https://github.com/user-attachments/assets/207c5010-bc97-45e7-adb0-dbc9b9cd513e)
)

**Comment by Jenefer-Monroe** [comment]
Hello, this appears to be a duplicate posting to the following issue: https://github.com/microsoft/coe-starter-kit/issues/9388
Will go ahead and close this one, and we have an active question for you in the other issue.
