### ISSUE TITLE
[CoE Starter Kit - QUESTION] When a user submits requested information via the Developer Compliance app, what mechanism changes the status from "Requested" to "Submitted"

### ISSUE THREAD

**Issue by hp-bc** [microsoft/coe-starter-kit#9397]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

When a user submits requested information via the Developer Compliance app, what mechanism changes the status of Admin Requirement - Risk Assessment State (admin_adminrequirementriskassessmentstate) from "Requested" to "Submitted" in that objects respective table?

Manual edits do not seem to trigger the change.

I believe I have looked in the most likely flows and the support details form code within the Developer Compliance app but nothing appears obvious to me.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.25

### What app or flow are you having the issue with?

Developer Compliance

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
The app itself flags it when you save the support details
![Image](https://github.com/user-attachments/assets/60394637-0c3c-4888-823f-88731216d2fe)

If you want to manually update, in the PPAdmin App for example, you will need to also change the flag to submitted manually
![Image](https://github.com/user-attachments/assets/54e81bfb-0b04-44af-a0d8-6496fe61b010)

**Comment by hp-bc** [comment]
Thank you very much! This is exactly what I was missing. I looked at the form element but not the panel.
