### ISSUE TITLE
System Admins details

### ISSUE THREAD

**Issue by Neel1KNK** [microsoft/coe-starter-kit#9399]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

Is there a way that we get all the list users who hold the system admin role either in PPAC/COE dashboard or the other place.

### What solution are you experiencing the issue with?

None

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
