### ISSUE TITLE
Help with audit logs

### ISSUE THREAD

**Issue by baklimek** [microsoft/coe-starter-kit#9404]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

I updated to the December 24 release for the core components, which updated the Admin | Audit Logs | Sync Audit Logs (V2) flow.

Since updating, the flow has failed every time. We are using not using the vault. 
Fails this scope:
 ![Image](https://github.com/user-attachments/assets/94950a28-ba5a-4fd9-b41c-428fb03a70e8)
![Image](https://github.com/user-attachments/assets/f4587c5b-574c-4b86-a50a-ebbb39cc4efd)

All 5 items failed in the scope in AuditLogQuery (The status code for that step was 403) before which was causing Set-InitialAuditLogsQueryReecordsURL to stay blank aka not be set. The status code for that step was 403
![Image](https://github.com/user-attachments/assets/3ec0de89-69e0-4a57-bf7a-3827c00a9955)
![Image](https://github.com/user-attachments/assets/4fbb7555-09f3-4b5b-af0d-472b14b639ed)

The status code of 403 is confusing also because i should have the necessary privledge
![Image](https://github.com/user-attachments/assets/3d872a3d-474d-480d-87f2-d12cc2b46f50)

Therefore, when it got to this step for AuditLogRecords, it failed because the URI was blank because @{variables('AuditLogQueryRecordsURL')} is blank aka the HTTP request doesn't work properly. 

So I believe if we resolve the 403 status for the http request, that would be the main idea

Please provide guidance on the issue. Thanks

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Admin | Audit Logs | Sync Audit Logs (V2)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Your API permissions are set for the O365 Management API technique of getting the audit logs 
[Collect audit logs using Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)
![Image](https://github.com/user-attachments/assets/d5a1e86f-3a73-4ea1-8034-f0edb63ec20c)

Whereas you are going down the path for the Graph API technique of getting the audit logs 
[Collect audit logs using Microsoft Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)
![Image](https://github.com/user-attachments/assets/8d426ec6-10e8-447a-9c85-ea412d70bc77)

This is configured with the following environment variable:
Set it to no and restart the flow and you should be working again using the O365 Management API technique
Or follow these instructions to update to use the [Microsoft Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi) technique. 

![Image](https://github.com/user-attachments/assets/e49d5973-e7ba-4dc4-a76d-4ca86afe0923)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
