### ISSUE TITLE
[CoE Starter Kit - BUG] - Orphaned Process

### ISSUE THREAD

**Issue by TOM-DBG** [microsoft/coe-starter-kit#9408]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi Team,

Could you please let me know how the Orphaned Process will proceed on the below scenario.

![Image](https://github.com/user-attachments/assets/4487be79-0c7e-4bd6-b25b-b35391c6d413)

Here the App Owner field is blank so as the Manager information is not available I believe.

So, these will be sent to the admins to decide?

Thanks,
Tom

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Admin View

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
