### ISSUE TITLE
[CoE Starter Kit - Request Orphaned Objects Reassigned (Child) flow failing

### ISSUE THREAD

**Issue by giramS09** [microsoft/coe-starter-kit#9410]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hi,

I tried to run the Request Orphaned Objects Reassigned (Child) flow, but in flow "Send Table For Response" action is failing and getting below error.<img width="593" alt="Image" src="https://github.com/user-attachments/assets/32a5049d-654c-48fc-9a49-949c1bccc463" />

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.25

### What app or flow are you having the issue with?

Request Orphaned Objects Reassigned (Child) flow failing

### What method are you using to get inventory and telemetry?

None

**Comment by Jenefer-Monroe** [comment]
Looks like your json isnt valid. I've not seen this happen before. 
Go into the scope above. Do these all run and pass? 
![Image](https://github.com/user-attachments/assets/0a9ae1b7-a5b3-47d5-8802-d96d81546a65)

Grab the output of this call which is the card json and put it into a json parser. What do you see? 
![Image](https://github.com/user-attachments/assets/88e14a69-1832-4961-af36-fa81e35be728)

What you should see
![Image](https://github.com/user-attachments/assets/60ef343e-bf52-4879-8269-e2b9aefa095b)

**Comment by giramS09** [comment]
@Jenefer-Monroe , I tried above steps, my scope is executed successfully and the output I am getting in the card content is as below:
<img width="408" alt="Image" src="https://github.com/user-attachments/assets/6e85f193-647a-4117-9303-eeb86dba94c2" />

{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "You can decide what to do with all the objects at once or go through them one at a time",
            "wrap": true,
            "weight": "Bolder"
        },
        {
            "type": "ColumnSet",
            "columns": [
                {    }
                    ],
                    "width": "auto"
                }
            ]
        },
        {
            "type": "ColumnSet",
            "columns": [
                { "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "bolder",
                            "text": "Flow Name"                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": " " }
                    ],
                    "width": "auto"
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "bolder",
                            "text": "Employee Name"                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "  " }
                    ],
                    "width": "auto"
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "bolder",
                            "text": "Flow Status"                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "  "    }
                    ],
                    "width": "auto"
                }
            ]
        },
        {
            "type": "ActionSet",
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Take Ownership",
            "style": "positive",
            "id": "TakeOwnership"
        },
        {
            "title": "Delete All",
            "type": "Action.Submit",
            "id": "DeleteAll"
        },
     {
            "title": "Assign Ownership",
            "type": "Action.ShowCard",
            "id": "AssignAll",
            "card":{
                 "type": "AdaptiveCard",
                 "body": [
                            {
                             "type": "Input.Text",
                             "id": "toWhom",
                             "placeholder": "AssignToWhom@example.com",
                             "style": "Email",
                             "spacing": "None"
                           }
                         ],
                  "actions":[
                         {
                            "type": "Action.Submit",
                            "id": "AssignAllDone",
                            "title": "Assign Now"
                         }
                       ],
                   "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
              }
        },
        {
            "title": "Email Me",
            "type": "Action.Submit",
            "id": "EmailMe"
        },
        {
            "title": "See Each",
            "type": "Action.Submit",
            "id": "SeeEach"
        }
            ]
        }
    ]
}

and when I tried to parse this json, it is giving error as below:
<img width="736" alt="Image" src="https://github.com/user-attachments/assets/20299ede-20ad-4cb7-b681-506f0a7f0ddf" />

**Comment by Jenefer-Monroe** [comment]
It looks like your flow is not filling in the json blocks.
Do you have unmanaged layers on this flow? 
![Image](https://github.com/user-attachments/assets/a5e70383-c329-4ad8-84c5-ced515c73484)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
