### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE

### ISSUE THREAD

**Issue by Chitusnair** [microsoft/coe-starter-kit#9411]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Dear Team,

I noticed that some of the Flows are missing from some of the environments in the Centre of Excellence > Power Platform Admin View > Environments > Environment X > Resources > Cloud Flows. These Flows were not listed in the Power Platform Admin View > Flows either. 

The environment actually has 28 flows, when checked from the Power Platform Admin Portal > Environments > Environment X > Resources. Only 20 were listed in CoE. This is same with another environment which is having 20 flows, but only 14 are listed.

The environments are not excused from inventory.

Please advice on what could be missing so that I could get a full list of resources within Power Platform Admin App.

Thanks,
CN

### Expected Behavior

CoE >  Power Platform Admin View > Flows > Filter by Environment X >  number of Flows should be same as Power Platform Admin Centre > Environments > Environment X > Resources > Flows > number of Flows

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.32.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Flows)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Eusemazo** [comment]
Hi everyone, I’ve already updated to the February 2025 version, but I’m still seeing the same issue—there are missing resources in the Admin view inventory. Any ideas on how to fix this? 

![Image](https://github.com/user-attachments/assets/ac51004a-d71e-4989-91c6-3466183de02a)
