### ISSUE TITLE
[CoE Starter Kit - BUG] Shared Users is overwritten from Data Export (v1)

### ISSUE THREAD

**Issue by madwalter3** [microsoft/coe-starter-kit#9415]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Problem: For apps the shared number of users is not correct.

Possible Reason: The Flow CLEANUP HELPER - Power Apps Shared With sets the right number of shared users for the apps. However, the next day, the shared with user is set back to 0 or any other number, I guess is coming from the .json of the data extract. 

### Expected Behavior

The number of app shared users should display the sum of editors and viewers.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Dataflow CoE BYODL Apps

### What method are you using to get inventory and telemetry?

Data Export

### Steps To Reproduce

1. In the CoE environment run CLEANUP – Admin | Sync Template vs (App Shared With). 
2. The flow calls CLEANUP HELPER– Power Apps User Shared with
3. The correct number of app users shared with is calculated and added.

![Image](https://github.com/user-attachments/assets/73672a30-8eed-4c9d-93e1-0d938512a739)

5. The next morning the dataflow CoE BYODL Apps runs automatically
6. The wrong number of app users shared with is displayed.

![Image](https://github.com/user-attachments/assets/ad39c0ef-11ae-47dd-a652-b445e4054d30)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team
