### ISSUE TITLE
[CoE Starter Kit - Feature]: Can we restrict Request Orphaned Objects Reassigned (Parent) flow to be run on selective environment instead of scanning entire tenant

### ISSUE THREAD

**Issue by giramS09** [microsoft/coe-starter-kit#9416]
### Is your feature request related to a problem? Please describe.

If we turn on these flows Request Orphaned Objects Reassigned (Parent), Request Orphaned Objects Reassigned (Child), they are scanning entire tenant which is not required. It should be based on selective environment for clean up of orphan app or flows.

### Describe the solution you'd like

Want to restrict Request Orphaned Objects Reassigned (Parent) flow to be run on selective environments instead of scanning entire tenant.
The solution can be in SetUp Wizard app, provide an option to exclude the environment which are not required to scan for orphan app or flows cleanup.

**Comment by Jenefer-Monroe** [comment]
Unfortunately we do not have an "excuse from" feature set for the orphan process today, no. We do have this on the backlog but do not expect it to be able to do it anytime soon. 

Sorry about that.

**Comment by Jenefer-Monroe** [comment]
I hear you, unfortunately we just arent staffed today for those features. But if funding returns we can certainly look at that one. 

Closing out as no further action for starter kit team as of now.
