### ISSUE TITLE
[CoE Starter Kit - Documentation] update notes about env var as they imply solution already installed.

### ISSUE THREAD

**Issue by MattCollins-Jones** [microsoft/coe-starter-kit#942]
### Describe the issue

I'm installing the latest version of the CoE starter kit and installing the nuture components. I create the SharePoint site and it tells me to update the Environment variable and then import and run a flow. The Environment Variable doesn't seem to exist. I'm following the instructions here:

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#create-the-site

And the variable the flow tries to retrieve and subsequently fails is new_admin_PowerUserURLSharePointSite

Is the environment variable in the nuture solution or should it be in the core or governance solutions? Also, should the flow have this as the name for the environment variable, all the other environment variables are admin_EnvVar, not new_admin_EnvVar?

![2021-07-30_16-09-33](https://user-images.githubusercontent.com/60160115/127673682-22f684d2-e310-46a5-95a4-714dd57b14c2.png)

### Expected Behavior

The Environment Variable should be something previously installed or the instructions should detail creating it (but not in the default solution because nobody wants new_Component names in systems 😁)

### What solution are you experiencing the issue with?

Nurture

### What solution version are you using?

1.0.20210521.1

### What app or flow are you having the issue with?

Missing Env Var stopping Nuture Install

### Steps To Reproduce

1. Install Core and Governance Components in New Environment
2. Follow instructions for Nuture install by creating SharePoint site and update Env Var
3. Can't find Env Var, flow fails to create library.

**Comment by JeneferM-MSFT** [comment]
sorry can you please clarify what flow are you looking at there?

**Comment by JeneferM-MSFT** [comment]
Here are the environment variables in Nurture. I do see that one listed so I dont know where in the solution you are finding a reference to it that is broken. 

![image](https://user-images.githubusercontent.com/62659043/127684478-05bf0b7e-fb25-4e3b-bab8-e679c9ab8ca0.png)

**Comment by MattCollins-Jones** [comment]
The instructions on the docs site [here](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#create-the-site) tell you to create a SharePoint site update the Environment Variable and then run the flow to create a library, before it tells you to import the Nuture Solution. I think the instructions need to be updated because you can't update the Environment variable before the solution is installed.

**Comment by JeneferM-MSFT** [comment]
can you paste the exact line where you see that instruction?

**Comment by MattCollins-Jones** [comment]
Hi Jen

_If you don't already have a SharePoint site for the Microsoft Power Platform power users in your tenant, create a new team now for them to access. This site is the one specified in the following environment variable: Power User Site URL (SharePoint Site)_

After this, the next step is to run the flow to create a library, instructions [here](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#create-the-library) and this bit fails because the Environment Variable is not in the environment. Am I reading the instructions incorrectly?

**Comment by JeneferM-MSFT** [comment]
Got it, yes we moved instructions and didnt think of that. I'm just going to remove the reference to the helper flow, but if you want to use it, you will need to use it after you install.

**Comment by JeneferM-MSFT** [comment]
Let me know if the flow still works for you, if so I'll add a note instead of removing the reference :)

**Comment by MattCollins-Jones** [comment]
Hi Jen, that makes sense. The next step down about creating the Microsoft form tells you to update the Environment variable as well, so maybe along with the reshuffle, that wording needs to be updated as it's confusing. Maybe "Store this link so we can update the environment variable after we import the solution"?

Once I imported the solution and updated the environment variables, I could run the flow to create the Library, so if the instructions are updated/moved around, this should resolve this for me and other. 😊

**Comment by JeneferM-MSFT** [comment]
Thanks Matt. I'll add this as a documentation bug to fix.

**Comment by mikefactorial** [comment]
@MattCollins-Jones This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
