### ISSUE TITLE
[CoE Starter Kit - QUESTION] QUESTION - GCCHigh / Graph Access / HTTP PreAuthorized Connector

### ISSUE THREAD

**Issue by powerplatformdevteam** [microsoft/coe-starter-kit#9420]
### Does this question already exist in our backlog?

- [x] I have checked and confirm this is a new question.

### What is your question?

I am trying to set up the CoE and the prerequisite of "Application.ReadAll Graph Permissions" says Fail.  My IT Team says that it has the necessary permissions.  Is there a way to troubleshoot this?  This is for a GCCHight Tenant so I'm using the parameters: https://graph.microsoft.us for the pop up.  We have a service principal setup but the connection says it is using the PowerPlatform Admin account.  When I try to switch account or create a new conncetion with the service principal, the authentication is for userIDs.  

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by powerplatformdevteam** [comment]
Ok - I met the CoE Team at the Power platform conference in Vegas and was assured that CoE worked for GCCHigh tenants as I'd avoided setting it up expecting limitations.  Are there work arounds?  The documentation offers an end point for GCCHigh tenants but you are saying that is not sufficient?  ![Image](https://github.com/user-attachments/assets/fd3b04a1-d3a3-407b-b6d6-4b7283093c87)

**Comment by Jenefer-Monroe** [comment]
You can still use the old technique for gathering audit logs:

Recommended technique but still blocked for GCCHigh and DoD 
note last thread I saw they found a technique to unblock you folks but its not yet been documented.
- [Graph API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http-graphapi)

The old technique that does work for all tenant types. 
- [Office 365 Management API](https://learn.microsoft.com/power-platform/guidance/coe/setup-auditlog-http)

**Comment by Jenefer-Monroe** [comment]
Closing out as no further action for starter kit team.
