### ISSUE TITLE
[CoE Starter Kit - BUG] Deleted copilot (PVA bots) inventory is not reflected on Admin | Sync Template v4 (PVA)

### ISSUE THREAD

**Issue by TUB98** [microsoft/coe-starter-kit#9421]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Deleted copilot (PVA bots) inventory is not reflected on Admin | Sync Template v4 (PVA)

### Expected Behavior

Admin | Sync Template v4 (PVA) should have marked deleted bots as deleted

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Admin | Sync Template v4 (PVA)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Run Admin | Sync Template v4 (PVA) - COE inventory out of sync with actual environment inventory 

### Anything else?

there is 8 total in the environment but shows 31 in inventory and not marked deleted. Sync flow ran multiple time against this environment ![Image](https://github.com/user-attachments/assets/b71a13d3-ed71-4c96-b314-35a7389bdf85)
![Image](https://github.com/user-attachments/assets/8b4e0593-d1ea-44bb-87bf-23d91d3c96f0)
![Image](https://github.com/user-attachments/assets/a943ec55-00ab-46b5-be3a-9c724055d99c)

**Comment by TUB98** [comment]
Hi Jenefer,

Thanks for the quick answer, I appreciate it!

Sorry I missed this!

Thanks!

Thomas ***@***.***>
Low Code Support Team
Enterprise Technology | Associate Collab & Productivity
State Farm®

From: Jenefer Monroe ***@***.***>
Sent: Tuesday, December 17, 2024 9:10 AM
To: microsoft/coe-starter-kit ***@***.***>
Cc: Thomas Banasik ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Deleted copilot (PVA bots) inventory is not reflected on Admin | Sync Template v4 (PVA) (Issue #9421)


Hello, please see below for an explanation of how we managed deleted objects in the CoE inventory.
The short answer for you is that a long running weekly flow called CLEANUP - Admin | Sync Template v4 (Check Deleted) is charged with deleting removed objects.

Deleting objects from inventory

How it works
When objects are deleted from the tenant, they get marked deleted in the inventory when the following flow is run, along with its helpers: CLEANUP - Admin | Sync Template v4 (Check Deleted)
This is a long running flow and so it only runs once per week.

Objects will stay in this state, marked as deleted from inventory, for ~2 months. This is to allow the record to be restored with its metadata in the event the object itself is restored in the tenant.

At that point, once restore is no longer possible in the tenant, then the records themselves are deleted from the inventory tables as well.

While they are in the "marked deleted" state they can be viewed in the kit using selecting that view for all the objects as shown here for apps.
image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/42ae9af2-6bb5-49fe-afba-838d5f925c68>

Why keep them around for two months?
Here is the scenario we are supporting by keeping these around

  *   Flow X created in tenant
  *   Flow X added to the CoE inventory tables
  *   Flow X marked as exempt from inactivity processing in the CoE
  *   Flow X deleted from tenant
  *   Flow X marked as deleted in CoE inventory tables
  *   Flow X restored in tenant
  *   Flow X unmarked deleted in CoE inventory tables, exemption from inactivity processing remains in place.

I need these records to stay in perpetuity
We have an env var, Also Delete from CoE, which allows you to prevent the deletion from the inventory tables. Default behavior (yes) described above, but if you set it to no then these records will never be deleted by the kit

image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/af05bf15-e937-4032-9eab-e4d290108147>

I don't want these records sitting around at all
If you want the deletion from inventory to occur immediately, or at some other cadence like 6 months, then you will need to create your own flow on the side to do this. You can use the mechanism used in CLEANUP - Admin | Sync Template v4 (Check Deleted) as a template for how to do this.
image.png (view on web)<https://github.com/microsoft/coe-starter-kit/assets/89584709/187ec89f-77d7-48d4-8fb3-ca6df9b704d5>

**Comment by Jenefer-Monroe** [comment]
Glad I was able to help! Closing out as no further action for starter kit team.
