### ISSUE TITLE
[CoE Starter Kit - BUG] Remove helper flows around doc lib creation and reference in documentation. 

### ISSUE THREAD

**Issue by azhar2501** [microsoft/coe-starter-kit#943]
### Describe the issue

When running the flow 'Create CoE TemplateLibary Doc Library in SP - 2' ,  the document library is created successfully however arriving on the scope "Scope - Add New Fields to Default View" the flow fails.

![Full flow view](https://user-images.githubusercontent.com/87812978/127847629-2ce8ef54-f4ad-461e-a84d-deafa2a85ba5.PNG)

Error details : L'affichage spécifié est incorrect. clientRequestId: d32482b7-f680-49a1-85c2-d1c127983f7c serviceRequestId: ac88e19f-d0a4-3000-16a6-a55b348a0c25

Final Result from failed flow. However the document library is a blank 
![image](https://user-images.githubusercontent.com/87812978/127847963-9892f3c4-2644-4b61-bef8-07ea4f36a5a3.png)

Thanks in advance,
Azhar

### Expected Behavior

A successful run which will create a document library allowing us to upload Power Apps/ Power Automate

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

'Create CoE TemplateLibary Doc Library in SP - 2

### Steps To Reproduce

- Import the flow ''Create CoE TemplateLibary Doc Library in SP - 2'
- set connectors
- add environment variable new_admin_PowerUserURLSharePointSite and set value to sharepoint site
- then turn on the flow
- run it

**Comment by JeneferM-MSFT** [comment]
These are helper flows, and if they have stopped working them I'm afraid we will just remove them from the list. 
You will need to generate these lists by hand. 
Thank you

**Comment by azhar2501** [comment]
ok, thank you
