### ISSUE TITLE
[CoE Starter Kit - BUG] Flow "Archive and Clean Up (Start Approval for Flows)" is taking longer than expected which stops sending backup reminder emails

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#944]
### Describe the issue

This is regarding one of the Audit flows, where it seems the "Get Flow" action used to check if flow still exists is not working at present.

![image](https://user-images.githubusercontent.com/13658386/127852715-f2c35086-e43c-4358-8dcf-1967d768c24c.png)

I assume this is happening from the Power Platform end, hence raised a support ticket for the same. It basically throws the following error even if flow exists in the environment:

Unable to parse JSON token. Token https://global.consent.azure-apim.net/redirect returned by ApiHub is malformed. Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject'.

Due to the above error, backup reminders will never be sent to users regardless if they approve/reject to archive the flow.

Can you share, how should we approach if such an event occurs? Should we stop the Audit process for the flow? what are your suggestions?

Thanks and Regards,

### Expected Behavior

Flow should send a backup reminder email if the flow is approved to the archive by the owner.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Archive and Clean Up (Start Approval for Flows)

**Comment by JeneferM-MSFT** [comment]
I'm confused by your title. Are you saying that the flow is getting throttled? Where do you see something about taking longer than expected?

**Comment by DiptiC-InsightRun** [comment]
Yes, that's correct, and I was referring to the "GEt flow as Admin" action as indicated in the earlier screen.

However we can ignore this issue, it has happened due to an error with the connection which is not related to CoE. Sorry for the trouble here.

Thank you for your understanding!

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
great news, thanks!
