### ISSUE TITLE
[CoE Starter Kit - Documentation] The caller with object id 'GUID' does not have permission for connection - add documentation on how to fix this co-auth issue

### ISSUE THREAD

**Issue by dmaloney02** [microsoft/coe-starter-kit#947]
### Describe the issue

While upgrading the core components to 2.2.20210707.3 we received upgrade errors.  Eventually it seems the upgrade went through.  After were are unable to run core component flows, perhaps the upgrade was not 100% successful  Should we reinstall from scratch?  If so, how?  If not how do we solve these permission issues?

Your flow could not turn on: CLEANUP - Admin | Sync Template v3 (Check Deleted). Error: The caller with object id 'serviceAccounts AzureAD ObjectID' does not have permission for connection '/providers/Microsoft.PowerApps/apis/shared_commondataservice/connections/20ffd580ac644ba094b06b0a767fea11' under Api 'shared_commondataservice'.

Your flow could not turn on: Admin | Sync Template v3. Error: The caller with object id '9a7d96cb-7a44-4543-8f29-912fd9e14398' does not have permission for connection '/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps/connections/897feafbf0604908b6ce0f885496b7aa' under Api 'shared_commondataserviceforapps'.

### Expected Behavior

COE flows execute without permission issues

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

CLEANUP - Admin | Sync Template v3 (Check Deleted)

### Steps To Reproduce

make.powerapps.com
Solutions
COE Core Components
Double-click flow name (opens flow in new window)
Click Turn-On flow

**Comment by JeneferM-MSFT** [comment]
It sounds like this is the issue you are asking for help with, two of your connectors are failing with the error: **_The caller with object id '<guid>'does not have permission for connection_**

I presume you are trying to turn them on with a different identity than the one you installed with. My recommendation is that you log in with the identity which installed to turn them on. But if that is not possible you will need to add connections for all these connection references. To do that, go to the Default Solution, filter to Connection References, edit each connection references and add a new connection reference for the identity you are using
![image](https://user-images.githubusercontent.com/62659043/127902451-50cb9e71-76f8-490c-a4bf-40b2be21e143.png)

**Comment by dmaloney02** [comment]
That seems to be the issue.  I've reconnected the correct account.  They all had the correct account as an option in the dropdown.  The only exception is the "CoE Core - HTTP AZURE AD" connection.  Are there special instructions for this one?

**Comment by JeneferM-MSFT** [comment]
wonderful. I'll hold this issue open to make a note in documentation for others

**Comment by JeneferM-MSFT** [comment]
Documentation updated for August
