### ISSUE TITLE
[CoE Starter Kit - BUG] Audit log solution: Invalid type. Expected String but got Null - ObjectId and UserKey

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/coe-starter-kit#959]
### Describe the issue

Hello,

I raised a previous ticket (#648) to report an issue with the Audit Log solution back in June. The advice was to re-install the solution which I've recently done after checking there were no unmanaged layers added to the parent and child admin flows contained with the solution.

Both flows are currently running successfully which is good news. However, I've spotted a number of intermittent failures with each flow, the details of which are described below. 

### Expected Behavior

Both the parent and child flows should run consistently without issue.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.50.20210708.1

### What app or flow are you having the issue with?

Admin | Sync Audit Logs and [Child] Admin | Sync Logs

### Steps To Reproduce

I've attached screenshots for the error I see along with the output for the failed step within each flow.

[Child Admin - Sync Log Raw Output.txt](https://github.com/microsoft/coe-starter-kit/files/6930416/Child.Admin.-.Sync.Log.Raw.Output.txt)
![Child Admin - Sync Logs](https://user-images.githubusercontent.com/62425530/128163377-9dfb06e7-ee34-47d8-a2b0-7eb97c62ae51.JPG)
[Admin - Sync Audit Log Raw Output.txt](https://github.com/microsoft/coe-starter-kit/files/6930417/Admin.-.Sync.Audit.Log.Raw.Output.txt)
![Admin - Sync Audit Logs](https://user-images.githubusercontent.com/62425530/128163381-ea5a94e8-13ff-4c23-bf8c-6c93c799ccba.JPG)

**Comment by JeneferM-MSFT** [comment]
For the intermittent issue on the parent flow, this is the office audit logs themselves not responding: **The server did not receive a response from an upstream server**

There isn't anything we can do about that, but the product team is currently working on a more robust solution for power apps action tracking. Please see [Bring your own Azure Data Lake](https://docs.microsoft.com/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate) for details. That solution will not have this dependency any longer and will be more robust

**Comment by melmgcoe** [comment]
Thanks Jenefer, I'll wait for your update re the child flow error once you've taken a look.

**Comment by JeneferM-MSFT** [comment]
For the child flow, I would not expect that those being null would fail, can you please open the child flow in edit mode and paste here what is in the schema? 
![image](https://user-images.githubusercontent.com/62659043/128189185-c5efb788-6d70-4d5a-b7cd-183238e4ac11.png)

Then if its what I have, I do have an experiment we can try.

**Comment by JeneferM-MSFT** [comment]
They used to send "unknown" for the UserKey field if it was blank but it looks like some tenants don't do that, or it has changed. Please try this for the schema instead and let me know if it works by doing a resubmit of your failures. My concern is that it will fail later when trying to insert a null but we can try. 

```
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "UserId": {
                "type": "string"
            },
            "UserKey": {
                "type": [
                    "string",
                    "null"
                ]
            }
        }
    }
}
```

**Comment by melmgcoe** [comment]
Before I end up updating the schema to what you suggested, here's the existing schema for the child flow:

{
    "items": {
        "properties": {
            "AppName": {
                "type": "string"
            },
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "ObjectId": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "UserId": {
                "type": "string"
            },
            "UserKey": {
                "type": "string"
            },
            "Workload": {
                "type": "string"
            }
        },
        "type": "object"
    },
    "type": "array"
}

**Comment by melmgcoe** [comment]
I'll wait for your comments before updating the schema and running the flow again. The child flow is running correctly at the moment so would it better to monitor for now and update the schema if I see another failure?

**Comment by JeneferM-MSFT** [comment]
Hmmm that is strange. Your schema is not correct, the elements are not in the correct order and the object type is out of its scope. I wouldnt expect that to work generally but have no idea how you ended up that way. Perhaps it pasted incorrectly? 

Here is what is live today, please update it and let me know.
```
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": "string"
            },
            "UserId": {
                "type": "string"
            },
            "UserKey": {
                "type": "string"
            }
        }
    }
}
```

**Comment by melmgcoe** [comment]
I've attempted to update the schema but wasn't able to run the flow after saving. A message appears saying the flow was overwritten by someone else. When I exit the flow and go back in to edit, the wrong schema is still in place. I then attempted to update the schema by clicking the option to generate from sample and inserting the schema you provided. This allowed me to save the flow but I'm no longer able to run the flow. A message appears in the filter array step which says it's expecting an array value type. See the screenshot below:

![Filter array error](https://user-images.githubusercontent.com/62425530/128322767-e46ce398-5e02-4221-8b9e-3e3c55ca2c8a.JPG)

Apologies, it doesn't look like the option to generate schema content from a sample was the correct option to go for.

**Comment by melmgcoe** [comment]
Ok, I re-inserted the schema you provided me and saved the flow again and it's now retained the updated schema:

![Schema update confirmation](https://user-images.githubusercontent.com/62425530/128353228-3177901b-9c1f-4787-aeab-8f3da25bbe60.JPG)


However when I run the flow again using a trigger from last nights run (which coincidentally failed), the flow still fails with the following error:

![Parse JSON error](https://user-images.githubusercontent.com/62425530/128353246-a7cf47e1-3b0c-4bd8-a3eb-e85f8ad04380.JPG)

**Comment by JeneferM-MSFT** [comment]
ok it looks like we are back to my original idea then. 
Pasting here for you to try:
-----------------------------
They used to send "unknown" for the UserKey field if it was blank but it looks like some tenants don't do that, or it has changed (though still working in my tenants). Please try this for the schema instead and let me know if it works by doing a resubmit of your failures. My concern is that it will fail later when trying to insert a null but we can try. 

```
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "UserId": {
                "type": "string"
            },
            "UserKey": {
                "type": [
                    "string",
                    "null"
                ]
            }
        }
    }
}
```

**Comment by melmgcoe** [comment]
Ok I've updated the schema to the original one you provided and this afternoon's run seems to have worked. I'll monitor for the next few days and let you know how I get on.

**Comment by JeneferM-MSFT** [comment]
updated august release with this change as well.

**Comment by JeneferM-MSFT** [comment]
I also just received the error you see above for the parent flow and it was my connection being broken. That may be what you were seeing as well
![image](https://user-images.githubusercontent.com/62659043/128397099-81f87abc-c2ff-4766-8d85-3cab6ecfd50e.png)

**Comment by melmgcoe** [comment]
I've double checked my connections and don't see any that are broken. Yesterday afternoon's run for the parent flow was successful, if I see any issues again it could well be related to the upstream issue you pointed out the other day.

**Comment by mikefactorial** [comment]
@melmgcoe This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
