### ISSUE TITLE
Audit Log Power Automated Flows Failing to Complete its Run with Error Messages

### ISSUE THREAD

**Issue by David-Liong** [microsoft/coe-starter-kit#961]
### Describe the issue

Dear Team,
Attetion to: @JeneferM-MSFT 

In regards to close ticket https://github.com/microsoft/coe-starter-kit/issues/851, I have contacted Microsoft to increase throttle limit on both log flows **[Child] Admin | Sync Logs & Admin | Sync Audit Logs**

Microsoft has increased the throttle limit to the highest settings for 60 days on the 2 log flows. See attached email below
The same error message still appearing on the [Child] Admin | Sync Logs flow as described in issue#851 even after Microsoft has increased the throttling. 

Until the product team is working to write the inventory and usage natively in a feature called Bring your own Datalake (BYOD) which will no longer use these sync flows, then can you please help me how to resolve this occurring error messages?

e.g. Do you suggest that perhaps I need to update Center of Excellence - Audit Logs solution version 1.3.2 from the CoE toolkit GitHub and which solution version is the latest and stable?

Thanks.
David

--------------------

From: Ajay Dhingra <ajdhingr@microsoftsupport.com> 
Sent: Monday, 2 August 2021 1:41 PM
To: David Liong <David.Liong@rac.com.au>
Subject: RE: Power Automate throttle request - raise throttl... - TrackingID#2107190060001052

CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.

Dear David,

Thanks so much for your response. For Both the Flows we have increased the throttle limit to highest level possible and even then they are failing so you will need to escalate this issue back the COE toolkit as per this document because we can assist with platform related issues and we have already provided the best subscription possible. Therefore COE engineering team  needs to look into it further. I am happy to keep this case open until COE team accepts the case for further troubleshooting . If you need any other assistance within the scope, then I am happy to assist.

Issue:
===== 
Flows below are throttling  and and throwing error.

[Child] Admin | Sync Logs	 - c8f15757-c64c-4e0d-9c93-713d0cd9f181
Admin | Sync Audit Logs		- 15d27af9-cb4e-4437-a1de-4fbc7f4322ee

Troubleshooting Performed:
=======================
To assist to resolve the issue we exceeded the throttling limit to the highest subscription possible,
 
![image](https://user-images.githubusercontent.com/71060262/128274867-054da188-b214-419a-9dbe-26703a0ffdbd.png)

 

Next:
===== 
              COE engineering team needs to investigate the issue further as per this document. 
                

Kind Regards,
Ajay

### Expected Behavior

I expect the error flows to go away or have less errors appearing in [Child] Admin | Sync Logs flow

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.3.2

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs & Admin | Sync Audit Logs

### Steps To Reproduce

1. Logged into https://australia.flow.microsoft.com/manage/environments. Navigate to solution from left menu and double click Center of Excellence - Audit Logs solution

![image](https://user-images.githubusercontent.com/71060262/128274151-7e6440a0-1043-4c04-982f-71dc8ff0e51a.png)

2. Double click [Child] Admin | Sync Logs

**Comment by JeneferM-MSFT** [comment]
One thing to consider is that you need to cancel any runs that started before you got the throttle limit raised. Cancel those and then try again.

If that does not work, then I'm afraid we don't have an interim solution for you here. And with traffic so high that the throttle limits cant be raised enough, even if we didn't throttle you the back end would here, meaning you wouldn't get all the logs from the office audit logs. 

The public preview of BYOD is available now and you can begin experimenting with it if you'd like. 

Sorry we cannot assist further.

**Comment by David-Liong** [comment]
All the instance flows for [Child] Admin | Sync Logs & Admin | Sync Audit Logs that are were running have failed. So when a flow instance have failed, I don't have any option to cancel it because I don't think it is running. Is this correct?

What about the solution of upgrading our Audit component solution to latest version if that will fix it? Because it is an older version 1.3.2?

Thanks

**Comment by JeneferM-MSFT** [comment]
Correct. If they failed then they are no longer running. 
You can try an upgrade but I don't think that will help you, unless you are just incorrect about the cause of the failure. It has not been updated to reduce API calls as there is no such change available to us.

**Comment by David-Liong** [comment]
As CoE team haven't made any such available changes/update to audit solution to reduce API calls, then do you think that using the native/out of the box MS audit log report to monitor activities for Power Platform would be sufficient that has similar functions covered in CoE audit log features?

e.g. https://protection.office.com/unifiedauditlog or  https://compliance.microsoft.com/auditlogsearch

![image](https://user-images.githubusercontent.com/71060262/129120948-947e4d34-6c57-46b7-b3df-298332535623.png)

**Comment by JeneferM-MSFT** [comment]
That is what the current solution is based on, the API of that product. 
I'm afraid there isnt anything further we can do until BYOD ships. I recommend you explore that solution. 
Thanks
