### ISSUE TITLE
[CoE Starter Kit - BUG] [Child] Admin | Sync Logs - fail to parse ResultStatus

### ISSUE THREAD

**Issue by silvafr1** [microsoft/coe-starter-kit#964]
### Describe the issue

From last July I started to get the bellow error on the flow "[Child] Admin | Sync Logs" on the  Action 'Parse JSON' failed:

![Parse_Error](https://user-images.githubusercontent.com/49397248/128323297-1cdfa326-d65e-42ec-a972-a9e2ae045373.PNG)

the Output error is:

[
  {
    "message": "Invalid type. Expected Integer but got String.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[137].RecordType",
    "value": "83",
    "schemaId": "#/items/properties/RecordType",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected Integer but got String.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[137].UserType",
    "value": "0",
    "schemaId": "#/items/properties/UserType",
    "errorType": "type",
    "childErrors": []
  }
]

This is wierd because isn´t "0" an Integer?
We updated the CoE on March and since then everything was working without problems, except from July on..
Thank you for your help!!

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.3.5

### What app or flow are you having the issue with?

[Child] Admin | Sync Logs

**Comment by JeneferM-MSFT** [comment]
We dont have anything in the schema that expects a string. Here is the current JSON schema that is live, can you please validate that it matches yours? And if not can you paste it instead to see if it works?

**Comment by silvafr1** [comment]
Hello,
Thank you for your quick answer!
Here are the JSON schema since the Solution installation:

{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "OrganizationId": {
                "type": "string"
            },
            "RecordType": {
                "type": "integer"
            },
            "ResultStatus": {
                "type": "string"
            },
            "UserKey": {
                "type": "string"
            },
            "UserType": {
                "type": "integer"
            },
            "Version": {
                "type": "integer"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": "string"
            },
            "UserId": {
                "type": "string"
            },
            "CrmOrganizationUniqueName": {
                "type": "string"
            },
            "Fields": {
                "type": "array"
            },
            "InstanceUrl": {
                "type": "string"
            },
            "ItemType": {
                "type": "string"
            },
            "ItemUrl": {
                "type": "string"
            },
            "UserAgent": {
                "type": "string"
            },
            "CorrelationId": {
                "type": "string"
            },
            "EntityId": {
                "type": "string"
            },
            "EntityName": {
                "type": "string"
            },
            "Message": {
                "type": "string"
            },
            "PrimaryFieldValue": {
                "type": "string"
            },
            "Query": {
                "type": "string"
            },
            "QueryResults": {
                "type": "string"
            },
            "ServiceContextId": {
                "type": "string"
            },
            "ServiceContextIdType": {
                "type": "string"
            },
            "ServiceName": {
                "type": "string"
            },
            "SystemUserId": {
                "type": "string"
            },
            "UserUpn": {
                "type": "string"
            },
            "AdditionalInfo": {
                "type": "string"
            },
            "Name": {
                "type": "string"
            }
        }
    }
}

**Comment by JeneferM-MSFT** [comment]
Ok it looks like you have an old version or else the flow has been edited. 

Please install [the latest version of the audit logs](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.  

We are shipping August early next week so you are welcome to wait for that release as well, or to update the schema with what I have pasted above.

**Comment by silvafr1** [comment]
Thank you! 
I will do install the new version.
Regards

**Comment by JeneferM-MSFT** [comment]
This has been fixed in the latest release 

Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
