### ISSUE TITLE
[CoE Starter Kit - BUG] POwerBI pbit file failed to build

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#965]
### Describe the issue

When creating the .pbix file - I get this error - 
![image](https://user-images.githubusercontent.com/8484048/128329958-4ba17045-7374-4f54-bfea-3b8f6804fac9.png)

### Expected Behavior

The .pbit file should be able to build the .pbix file

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

POwerBI report

### Steps To Reproduce

load .pbix, file enter url of CoE Environment.  Error occurs

**Comment by NPrice99** [comment]
Found Issue - updated PowerBI Desktop to July 2021edition and then it worked - was March 2021

**Comment by manuelap-msft** [comment]
I was just about to say that I was able to repo the issue and am looking into it! I just checked and I'm also on the March 2021 version. Will upgrade on my end as well! 

Thanks for helping with the debugging, you just saved me some time! 👍
