### ISSUE TITLE
[CoE Starter Kit - BUG] No Environments After April 2021 Showing up in Environments Table of DataVerse

### ISSUE THREAD

**Issue by NPrice99** [microsoft/coe-starter-kit#975]
### Describe the issue

In a Tenancy with 80 Environments - ClearCollect(collEnvironments,PowerPlatformforAdmins.GetAdminEnvironment().value); CoE is only finding 30 and nothing after April 2021.

### Expected Behavior

I expect to find more than 30 environments

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2.20210707.3

### What app or flow are you having the issue with?

Admin | Sync Template v3

### Steps To Reproduce

run Admin | Sync Template v3

**Comment by JeneferM-MSFT** [comment]
Hello. The way you have written this leaves me a little confused. Are you creating a powerapp of your own and the expression didnt work? Are the sync flows not picking up all the environments? Or both? 

For the sync flows, we have seen this caused via two issues, so perhaps one of these has changes in your tenant, or you are on a new tenant. 

1) The tenant uses [PIM (Privileged Identity Management)](https://docs.microsoft.com/power-platform/guidance/coe/limitations#pim-privileged-identity-management) to manage accounts, which we do not support.
2) The user does not have the PPAdmin role. Here is a document in case you need help ensuring you have it: [PPAdmin Role.pdf](https://github.com/microsoft/coe-starter-kit/files/6555374/PPAdmin.Role.pdf) 

Please let me know if you are talking about something other than the sync flows. Thank you

**Comment by NPrice99** [comment]
Hi Jenifer

I created a PowerApp to get all of the environments in a Tenancy and it came back with 80 environments.

The CoE PowerAoutomate Flow on the same environment – Admin | Sync Template v3 only returned 30.

I hope this helps.  Please let me know if I need to clarify further.

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
ok it sounds like there is something with the identity running the sync flow then. 
Please do the following:
1) Validate that the connections being used for the **Sync Template V3** flow have the PPadmin role (as described above) and that it is not subject to PIM. 
![image](https://user-images.githubusercontent.com/62659043/128717727-f379e33b-fd8c-4c9b-879f-cc553125595c.png)
2) Let me know, is that identity you or some other identity. 
3) If you, please kick off the flow now and the power app at the same time. See that they return the same number of environments.

**Comment by JeneferM-MSFT** [comment]
Hi Nigel. Checking in here on the answers for the above. Please let me know
Thank you

**Comment by NPrice99** [comment]
Hi Jenefer
We have an issue here due to security, we do not allow service accounts to have PPAdmin roles.
However PowerPlatformforAdmins.GetAdminEnvironment() does get all of the environments.
Regards
Nigel

**Comment by JeneferM-MSFT** [comment]
Got it. Unfortunately, I'm afraid you will either need to switch back to using a person's account then, or change that perspective and add PPAdmin to this user.

**Comment by JeneferM-MSFT** [comment]
closing out as no further work for the toolkit
