### ISSUE TITLE
[CoE Starter Kit - BUG] App Launch Trend in Power BI dashboard showing gaps

### ISSUE THREAD

**Issue by patrickpooon02** [microsoft/coe-starter-kit#986]
### Describe the issue

There are issue on "App Usage" page of the Power BI Dashboard. when it is in default date filter, we can see some gap in the app launch trend graph. However if we tune the filter to include that gap, there is actually data.

![App Usage Dashboard missing data in graph](https://user-images.githubusercontent.com/82566841/128825876-f885d830-21db-4225-ba97-0d252174e36b.png)
![App Usage Dashboard with date filter actually got data](https://user-images.githubusercontent.com/82566841/128825889-ac2c1a19-98cf-4dcb-b7c0-781bc169676a.png)

### Expected Behavior

The graph should be showing accurate app launch count, at least not empty if there is data.

### What solution are you experiencing the issue with?

Audit Log

### What solution version are you using?

1.70

### What app or flow are you having the issue with?

CDSLegacy_CoEDashboard_202107 v2

### Steps To Reproduce

1. Make sure Audit Log module is in-place and works fine.
2. Open Power BI Dashboard and go to "App Usage" page.

### Anything else?

The wording "App Count" in Y-axis should be fine tune as "App Launch Count"?

**Comment by manuelap-msft** [comment]
Hello,

I changed the wording to App Launch Count for the September release, and I think I found the issue with the data - the graph was using admin_creationhour as value, and the filter for launches between was using admin_creationtime as value. I have made those adjustments and it looks to be working now. 

The September release will launch next week, and the new dashboard will be available then.

Thank you
Manuela

**Comment by mikefactorial** [comment]
@patrickpooon02 This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
