### ISSUE TITLE
[CoE Starter Kit - Enhancement] Archival Flows for users without mailbox/mail

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/coe-starter-kit#989]
### Describe the issue

There are few apps created by user "TestUser1" without mailbox assigned, meaning when flow created by "TestUser1" gets audited every Monday, the flow will not execute the "Create Approval" action, not because the user does not have permission, but because "Var Assignee" value is NULL, as there is no mail value for "TestUser1"

In this scenario, CoE Admin will receive an email "Flow maker "TestUser1"does not have permissions to perform Archive Approval"

I was wondering if the following approaches can be implemented:

1. is it a good idea to check the "Mail" property of the existing User as well before creating an approval?
2. should it be handled by sending a separate email saying that "User is not assigned with mail/mailbox OR not an actual user" 
3. is it a good idea to change the content of the email "Flow maker "TestUser1" does not have permissions to perform Archive Approval" itself with point 1/2 information?

Any suggestions?

Thanks and Regards,
Dipti

### Expected Behavior

If the user does not have mail value, an appropriate email should be sent to CoE Admin.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

1.61

### What app or flow are you having the issue with?

Archive and Clean Up (Start Approval for Flows)

**Comment by JeneferM-MSFT** [comment]
Added to backlog.

**Comment by manuelap-msft** [comment]
Not enough indication that this is a common scenario for our customers. Closing out.
