### ISSUE TITLE
[AA4AM] End to End Integration Tests

### ISSUE THREAD

**Issue by Grant-Archibald-MS** [microsoft/coe-starter-kit#996]
Set of automated tests that verify end to end functionality of AA4AM
- Optionally setup Environments
- Create Dataverse Connection
- Install AA4AM (AAD, Azure DevOps and Import Managed Solution)
- Create Developer Environment
- Register Developer Environment
- Create Maker Solution Branch
- Create Unmanaged solution
- Run Canvas tests that 
   - Export solution to GitHub
   - Pull Request into Solution Branch
   - Pull Request into Main Branch
 - Verify changes in dependent systems made (e.g. Updates to Azure DevOps)

**Comment by mikefactorial** [comment]
Closing this out. Integration tests are already running in our Template PR Loop
